### PR TITLE
[clang] Fix crash when #embed data does not fit into an array

### LINKED ISSUE #128987: Buffer overflow with excess array initializers in #embed
Testcase:

```
void f(int x) {
  int p[8] = {x, x, x, x, x, x, x,
#embed __FILE__ limit(3)
};
}
```

This stores to `p[8]` and `p[9]`, which are past the end of the array.

Related assertion:
```
void f(int x) {
  int p[8] = {x, x, x, x, x, x, x,
#embed __FILE__ limit(10)
};
}
```
```
llvm/include/llvm/Support/Casting.h:109: static bool llvm::isa_impl_cl<clang::ImplicitValueInitExpr, const clang::Expr *>::doit(const From *) [To = clang::ImplicitValueInitExpr, From = const clang::Expr *]: Assertion `Val && "isa<> used on a null pointer"' failed.
```

CC @Fznamznon

### PR DESCRIPTION
**Pull request by Fznamznon**
Tune SemaInit code handling #embed to take into account how many array elements remains to initialize.
Also issue a warning/error message when the array/struct is at the end but there is still #embed data left.

Fixes https://github.com/llvm/llvm-project/issues/128987

### CODE REVIEW

File: clang/test/CodeGen/excess-embed-data.c [hunk 1]
```diff
@@ -0,0 +1,55 @@
+// RUN: %clang_cc1 -std=c23 -emit-llvm %s -o - | FileCheck %s
```
Comment (cor3ntin) [inline clang/test/CodeGen/excess-embed-data.c:1]: We probably need to specify a target here (linux x64) as we rely on the size of int

**Review by cor3ntin — APPROVED** [review]
