### PR TITLE
[WebAssembly][FastISel] Emit signed loads for sext of i8/i16/i32

### LINKED ISSUE #180783: [WebAssembly][FastISel] should emit sign-extending loads (load8_s/load16_s) to fold sext instructions
Description

Currently, the WebAssembly FastISel implementation conservatively emits unsigned loads (i32.load8_u or i32.load16_u) for all i8 and i16 loads, regardless of how the loaded value is used.

When the loaded value is subsequently sign-extended (sext), this results in suboptimal code generation. FastISel emits an unsigned load followed by an explicit sign-extension sequence (often a shift-left/shift-right pair or an extend_s instruction).

WebAssembly supports sign-extending loads (i32.load8_s and i32.load16_s). FastISel should utilize these instructions when the loaded value is used by a sext instruction, effectively folding the extension into the load itself.

Reproduction Steps

Create a file named sext_load.ll:
```llvm
target datalayout = "e-m:e-p:32:32-i64:64-n32:64-S128"
target triple = "wasm32-unknown-unknown"

define i32 @test_sext_i8(ptr %p) {
entry:
  %val = load i8, ptr %p
  %ext = sext i8 %val to i32
  ret i32 %ext
}

define i32 @test_sext_i16(ptr %p) {
entry:
  %val = load i16, ptr %p
  %ext = sext i16 %val to i32
  ret i32 %ext
}
```

Current Behavior

FastISel generates an unsigned load followed by sign-extension logic (2+ instructions).
```wasm
test_sext_i8:
    local.get 0
    i32.load8_u 0   # Unsigned load
    i32.extend8_s
    end_function
```
Expected Behavior

FastISel should generate a single sign-extending load instruction.
```wasm
test_sext_i8:
    local.get 0
    i32.load8_s 0   # Optimized: Load + Sext in one
    end_function
```

Proposed Solution

We can implement a look-ahead heuristic in SelectLoad and a look-back check in SelectSExt:

    In WebAssemblyFastISel::SelectLoad: Check the first user of the LoadInst. If it is a SExtInst, emit WebAssembly::LOAD8_S_I32 (or LOAD16_S_I32) instead of the default unsigned load.

    In WebAssemblyFastISel::SelectSExt: Check if the operand is defined by a LOAD8_S (or LOAD16_S) instruction. If so, elide the extension (emit a COPY or no-op), as the value is already sign-extended.

Additional Context

    Target: WebAssembly (wasm32)

    Component: WebAssemblyFastISel.cpp

This optimization would align FastISel's output closer to SelectionDAG's behavior for this common pattern, reducing code size and instruction count.

### PR DESCRIPTION
**Pull request by ParkHanbum**
FastISel currently defaults to unsigned loads for i8/i16/i32 types, leaving any sign-extension to be handled by a separate instruction. This patch optimizes this by folding the SExtInst into the LoadInst, directly emitting a signed load (e.g., i32.load8_s).

When a load has a single SExtInst use, selectLoad emits a signed load and safely removes the redundantly emitted SExtInst.

Fixed: #180783

### CODE REVIEW

File: llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp [hunk 1]
```diff
@@ -1267,6 +1306,61 @@ bool WebAssemblyFastISel::selectBitCast(const Instruction *I) {
   return true;
 }
 
+static unsigned getSExtLoadOpcode(unsigned Opc, bool A64) {
```
Comment (QuantumSegfault) [inline llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp]: This is intended to return an opcode, but sometimes returns `false`, which is confusing. Perhaps `std::optional` would be a better fit? Or a boolean return value with mutable ref `Opc`?

Comment (ParkHanbum) [reply llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp]: got it!

**Review by QuantumSegfault — APPROVED** [review]
Alright then. If you are handling the rest in a future PR, then this LGTM, other than some minor comments/suggestions.

We'll see what @dschuff thinks of this approach.

**Review by dschuff — COMMENTED** [review]
One suggestion, otherwise LGTM

File: llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp [hunk 2]
```diff
@@ -1267,6 +1271,62 @@ bool WebAssemblyFastISel::selectBitCast(const Instruction *I) {
...
+  case WebAssembly::I64_EXTEND32_S_I64:
+  case WebAssembly::I64_EXTEND_S_I32:
+    Opc = A64 ? WebAssembly::LOAD32_S_I64_A64 : WebAssembly::LOAD32_S_I64_A32;
+    break;
+  }
+
+  return Opc;
+}
+
+bool WebAssemblyFastISel::WebAssemblyEmitLoad(unsigned Opc, Register &ResultReg,
```
[the remark this answers is not in the document]
Comment (dschuff) [reply llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp]: I think it's fine to have the logic separated for selecting the opcode (getSextLoadOpcode makes sense as its own function). I'm just thinking the BuildMI and the call to addLoadStoreOperands can just go down into tryToFolLoadIntoMI unless you want to reuse WebAssemblyEmitLoad somewhere else.

File: llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp [hunk 3]
```diff
@@ -171,6 +171,8 @@ class WebAssemblyFastISel final : public FastISel {
   unsigned getRegForPromotedValue(const Value *V, bool IsSigned);
   unsigned notValue(unsigned Reg);
   unsigned copyValue(unsigned Reg);
+  bool WebAssemblyEmitLoad(unsigned Opc, Register &ResultReg, Address &Addr,
+                           MachineMemOperand *MMO);
```
Comment (QuantumSegfault) [inline llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp]: Leftover declaration
```suggestion
```

**Review by dschuff — APPROVED** [review]

**Review by QuantumSegfault — APPROVED** [review]

**Comment by sbc100** [comment]
It looks like this change broke the emscripten waterfall.   I bisects the failure to this PR:

```
$ ./test/runner other.test_safe_heap_2
AssertionError: subprocess exited with non-zero return code(1): `/usr/local/google/home/sbc/dev/wasm/emscripten/emcc /usr/local/google/home/sbc/dev/wasm/emscripten/test/safe_heap_2.c -o safe_heap_2.js -sNO_DEFAULT_TO_CXX -Wclosure -Werror -Wno-limited-postlink-optimizations -sSAFE_HEAP=1`

Stdout:
clang: /usr/local/google/home/sbc/dev/wasm/llvm-project/llvm/include/llvm/CodeGen/Register.h:88: unsigned int llvm::Register::virtRegIndex() const: Assertion `isVirtual() && "Not a virtual register"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/usr/local/google/home/sbc/dev/wasm/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Werror -c /usr/local/google/home/sbc/dev/wasm/emscripten/test/safe_heap_2.c -o /tmp/emscripten_temp_3fxmekot/safe_heap_2.o
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/usr/local/google/home/sbc/dev/wasm/emscripten/test/safe_heap_2.c'.
4.	Running pass 'WebAssembly Register Stackify' on function '@__original_main'
 #0 0x00007f18613d2d18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMSupport.so.23.0git+0x1d2d18)
 #1 0x00007f18613cfb25 llvm::sys::RunSignalHandlers() (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMSupport.so.23.0git+0x1cfb25)
 #2 0x00007f18612e8856 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f1860c49df0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fdf0)
 #4 0x00007f1860c9e95c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007f1860c49cc2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #6 0x00007f1860c324ac abort ./stdlib/abort.c:81:3
 #7 0x00007f1860c32420 __assert_perror_fail ./assert/assert-perr.c:31:1
 #8 0x00007f186784e0f9 (anonymous namespace)::WebAssemblyRegStackify::runOnMachineFunction(llvm::MachineFunction&) WebAssemblyRegStackify.cpp:0:0
 #9 0x00007f18653a5873 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMCodeGen.so.23.0git+0x3a5873)
#10 0x00007f1861861cd5 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMCore.so.23.0git+0x261cd5)
#11 0x00007f18618699e2 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMCore.so.23.0git+0x2699e2)
#12 0x00007f186186274b llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMCore.so.23.0git+0x26274b)
#13 0x00007f1865d25220 clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangCodeGen.so.23.0git+0x125220)
#14 0x00007f18660f236a clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangCodeGen.so.23.0git+0x4f236a)
#15 0x00007f185feb5409 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/../lib/libclangParse.so.23.0git+0x3e409)
#16 0x00007f1863960576 clang::FrontendAction::Execute() (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangFrontend.so.23.0git+0x160576)
#17 0x00007f18638bd09d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangFrontend.so.23.0git+0xbd09d)
#18 0x00007f186771e20a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangFrontendTool.so.23.0git+0x420a)
#19 0x00005608ec294385 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang+0x12385)
#20 0x00005608ec2902f5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#21 0x00005608ec29278d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::$_0>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#22 0x00007f1863cb9069 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#23 0x00007f18612e856e llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libLLVMSupport.so.23.0git+0xe856e)
#24 0x00007f1863cb8763 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangDriver.so.23.0git+0xb8763)
#25 0x00007f1863c6e3bc clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangDriver.so.23.0git+0x6e3bc)
#26 0x00007f1863c6e5d7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangDriver.so.23.0git+0x6e5d7)
#27 0x00007f1863c96088 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/../lib/libclangDriver.so.23.0git+0x96088)
#28 0x00005608ec28fb88 clang_main(int, char**, llvm::ToolContext const&) (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang+0xdb88)
#29 0x00005608ec29f70d main (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang+0x1d70d)
#30 0x00007f1860c33ca8 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#31 0x00007f1860c33d65 call_init ./csu/../csu/libc-start.c:128:20
#32 0x00007f1860c33d65 __libc_start_main ./csu/../csu/libc-start.c:347:5
#33 0x00005608ec28dd31 _start (/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang+0xbd31)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 23.0.0git (https://github.com/sbc100/llvm-project 4147cd29e1f2ecbc3bcd609b23d02ddd7fab4502)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/google/home/sbc/dev/wasm/llvm-build/bin
Build config: +assertions
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/safe_heap_2-326f2e.c
clang: note: diagnostic msg: /tmp/safe_heap_2-326f2e.sh
clang: note: diagnostic msg: 

********************
emcc: error: '/usr/local/google/home/sbc/dev/wasm/llvm-build/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/usr/local/google/home/sbc/dev/wasm/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Werror -c /usr/local/google/home/sbc/dev/wasm/emscripten/test/safe_heap_2.c -o /tmp/emscripten_temp_3fxmekot/safe_heap_2.o' failed (received SIGABRT (-6))

None

----------------------------------------------------------------------
Ran 1 test in 0.981s

FAILED (failures=1)
```

See https://ci.chromium.org/ui/p/emscripten-releases/builders/try/mac/b8688703966461485713/overview

**Comment by sbc100** [comment]
I attached the pre-processed source as out.c.

You can repro using `$ ../llvm-build/bin/clang  -target wasm32-unknown-emscripten -c out.c`

[out.c](https://github.com/user-attachments/files/25687991/out.c)

**Comment by ParkHanbum** [comment]
@sbc100 I sent PR for fix crash  https://github.com/llvm/llvm-project/pull/184203
