### PR TITLE
[InstCombine] Ensure Safe Handling of Flags in foldFNegIntoConstant

### LINKED ISSUE #93769: foldFNegIntoConstant incorrectly preserves fast math flags for 0 constants
https://alive2.llvm.org/ce/z/MHShQY longer version

_Originally posted by @arsenm in https://github.com/llvm/llvm-project/pull/92512#discussion_r1619895371_

Some of the combines in foldFNegIntoConstant are unsafely taking the flags directly from the original fneg instruction, when the preservation logic requires dropping ninf in some cases.

### PR DESCRIPTION
**Pull request by SahilPatidar**
Fix #93769 

alive2: https://alive2.llvm.org/ce/z/MHShQY

### CODE REVIEW

**Comment by SahilPatidar** [comment]
@arsenm

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp [hunk 1]
```diff
@@ -2653,8 +2653,15 @@ static Instruction *foldFNegIntoConstant(Instruction &I, const DataLayout &DL) {
   // Fold negation into constant operand.
   // -(X * C) --> X * (-C)
   if (match(FNegOp, m_FMul(m_Value(X), m_Constant(C))))
-    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL))
+    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL)) {
+      if (match(C, m_AnyZeroFP()) && I.getFastMathFlags().noInfs()) {
+        return BinaryOperator::CreateFMulFMF(
+            X, NegC,
+            I.getFastMathFlags() &
+                cast<FPMathOperator>(I.getOperand(0))->getFastMathFlags());
```
[the remark this answers is not in the document]
Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2661]: Could we do it this way?
```cpp
      FastMathFlags FMF = cast<FPMathOperator>(I.getOperand(0))->getFastMathFlags();
      if (I.getFastMathFlags().noInfs() && !FMF.noInfs()) {
        return BinaryOperator::CreateFMulFMF(X, NegC, FMF);
      }
```

[the remark this answers is not in the document]
Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2661]: Ok, we need to check all alive2 cases and then generate the flags.

[the remark this answers is not in the document]
Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2661]: alive2: https://alive2.llvm.org/ce/z/DHmA7a
I apologize for the delay; I was quite busy. Based on my observation, I came up with this combination: if we have `nnan` in any instruction, we can propagate flags to our transformation.

```cpp
FastMathFlags NF1 = F1 & F2;
FastMathFlags NF2 = F1 | F2;

if (NF2.noNaNs()) {
    return F2;
}

if (NF1.any() || (F1.none() && F2.none())) {
    return NF1;
}

if (F1.all() || F2.all()) {
    return F2;
}

return NF1;
```

Let me know what you think.

[the remark this answers is not in the document]
Comment (arsenm) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2661]: `NF1.any() || (F1.none() && F2.none())` case is equivalent to just NF1.any.

Not sure why you need the all || all fixup either

**Comment by jayfoad** [comment]
Why not just copy FMF from FNegOp (the fmul) instead of from I (the fneg)? It's simple and correct and it seems pretty unlikely that you'd ever get a real world case where the flags on the fneg would add any extra useful information.

**Comment by SahilPatidar** [comment]
Since it was breaking the `fsub` test with the `reassoc` flag, I conditionally propagated the `FNegOp` FMF flag.

**Comment by jayfoad** [comment]
> Since it was breaking the `fsub` test with the `reassoc` flag, I conditionally propagated the `FNegOp` FMF flag.

Personally I think _all_ cases in this function should be copying FMF from `FNegOp`, not from `I`. That is simple, correct (I think!) and useful.

In some cases you might be able to infer additional flags from `I` but that is much more subtle and (I assert!) far less useful. For example copying `nnan` from `I` is probably OK, but in that case it should be ORed into the flags from `FNegOp`.

**Comment by jayfoad** [comment]
> Since it was breaking the `fsub` test with the `reassoc` flag, I conditionally propagated the `FNegOp` FMF flag.

Maybe we should just update the expected output for that test? It is not at all clear to me that propagating `reassoc` from the fsub to the fmul is desirable or even correct.

**Comment by SahilPatidar** [comment]
This is a test we are breaking:
```llvm
; With nsz and reassoc: Y - ((X * 5) + Y) --> X * -5

define float @sub_add_neg_x(float %x, float %y) {
; CHECK-LABEL: @sub_add_neg_x(
; CHECK-NEXT:    [[R:%.*]] = fmul float [[X:%.*]], -5.000000e+00
; CHECK-NEXT:    ret float [[R]]
;
  %mul = fmul float %x, 5.000000e+00
  %add = fadd float %mul, %y
  %r = fsub nsz reassoc float %y, %add
  ret float %r
}
```

**Comment by arsenm** [comment]
reverse ping

**Comment by SahilPatidar** [comment]
If we directly use `FNegOp`, it breaks some `reassoc` tests.

**Comment by arsenm** [comment]
> If we directly use `FNegOp`, it breaks some `reassoc` tests.

Do you have an example? Those tests might just be wrong

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (arsenm) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp]: I think ninf is the only problematic flag, since ninf on the fneg does not imply fneg on fmul, and fmul inf * 0 = nan. 

So you need something like

Flags = FnegFlags | FMulFlags
Flags.ninf &= FmulFlags.ninf

**Comment by SahilPatidar** [comment]
> Do you have an example? Those tests might just be wrong

It looks like the changes are affecting the propagation of the `reassoc` flag. I've pushed updated tests to reflect this.

**Comment by SahilPatidar** [comment]
@arsenm  Now check that out. Does it look alright?

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp [hunk 2]
```diff
@@ -2682,8 +2682,12 @@ static Instruction *foldFNegIntoConstant(Instruction &I, const DataLayout &DL) {
   // Fold negation into constant operand.
   // -(X * C) --> X * (-C)
   if (match(FNegOp, m_FMul(m_Value(X), m_Constant(C))))
-    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL))
-      return BinaryOperator::CreateFMulFMF(X, NegC, &I);
+    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL)) {
+      FastMathFlags Flag = I.getFastMathFlags() | FNegOp->getFastMathFlags();
+      Flag.setNoInfs(I.getFastMathFlags().noInfs() &&
+                     FNegOp->getFastMathFlags().noInfs());
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2688]: Avoid repeated calls to I.getFastMathFlags() and FNegOp->getFastMathFlags()?

File: llvm/test/Transforms/InstCombine/fneg.ll [hunk 3]
```diff
@@ -1109,4 +1109,96 @@ define float @test_fneg_select_maxnum(float %x) {
...
+define <2 x float> @test_fneg_nnan_ninf_mul_with_vec_const(<2 x float> %a) {
+; CHECK-LABEL: @test_fneg_nnan_ninf_mul_with_vec_const(
+; CHECK-NEXT:    [[F2:%.*]] = fmul nnan <2 x float> [[A:%.*]], <float -0.000000e+00, float 0.000000e+00>
+; CHECK-NEXT:    ret <2 x float> [[F2]]
+;
+  %f1 = fmul <2 x float> %a, <float 0.000000, float -0.000000>
+  %f2 = fneg nnan ninf <2 x float> %f1
+  ret <2 x float> %f2
+}
+
```
Comment (arsenm) [inline llvm/test/Transforms/InstCombine/fneg.ll:1203]: Missing a test where ninf is present on both, and is preservable

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp (hunk 2 above)
Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp]: done

File: llvm/test/Transforms/InstCombine/fneg.ll (hunk 3 above)
Comment (SahilPatidar) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: Let me know if we need more tests of that kind?.

File: llvm/test/Transforms/InstCombine/fneg.ll [hunk 4]
```diff
@@ -1201,4 +1201,14 @@ define <2 x float> @test_fneg_nnan_ninf_mul_with_vec_const(<2 x float> %a) {
...
 }
 
+define <2 x float> @test_fneg_nnan_ninf_mul_ninf_with_vec_const(<2 x float> %a) {
+; CHECK-LABEL: @test_fneg_nnan_ninf_mul_ninf_with_vec_const(
+; CHECK-NEXT:    [[F2:%.*]] = fmul nnan ninf <2 x float> [[A:%.*]], <float -0.000000e+00, float 0.000000e+00>
+; CHECK-NEXT:    ret <2 x float> [[F2]]
+;
+  %f1 = fmul ninf <2 x float> %a, <float 0.000000, float -0.000000>
+  %f2 = fneg nnan ninf <2 x float> %f1
+  ret <2 x float> %f2
```
Comment (arsenm) [inline llvm/test/Transforms/InstCombine/fneg.ll:1211]: I would have tested the ninf preservation case above with the scalar case, but this covers it

File: llvm/test/Transforms/InstCombine/fneg.ll (hunk 3 above)
Comment (arsenm) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: The ninf combinations are most important because you need to special case them

Comment (arsenm) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: Should also test reassoc on one, other, and both instructions. Best to require it be present on both instructions

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp [hunk 5]
```diff
@@ -2757,8 +2757,13 @@ static Instruction *foldFNegIntoConstant(Instruction &I, const DataLayout &DL) {
   // Fold negation into constant operand.
   // -(X * C) --> X * (-C)
   if (match(FNegOp, m_FMul(m_Value(X), m_Constant(C))))
-    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL))
-      return BinaryOperator::CreateFMulFMF(X, NegC, &I);
+    if (Constant *NegC = ConstantFoldUnaryOpOperand(Instruction::FNeg, C, DL)) {
+      FastMathFlags FMF = I.getFastMathFlags();
+      FastMathFlags OpFMF = FNegOp->getFastMathFlags();
+      FastMathFlags Flag = FMF | OpFMF;
+      Flag.setNoInfs(FMF.noInfs() && OpFMF.noInfs());
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2764]: Should and the rewrite flags too (reassoc, contract, afn). We probably should have a helper for the rewrite flags

File: llvm/test/Transforms/InstCombine/fneg.ll (hunk 3 above)
Comment (SahilPatidar) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: @arsenm  We require the `reassoc` flag to be present on both instructions before propagating it, but only if `noinf` is also present, right?

Comment (arsenm) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: No, there is no direct connection between reassoc and ninf. They both separately are anded

Comment (SahilPatidar) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: This change causes the test to fail:
```llvm
; With nsz and reassoc: Y - ((X * 5) + Y) --> X * -5

define float @sub_add_neg_x(float %x, float %y) {
; CHECK-LABEL: @sub_add_neg_x(
; CHECK-NEXT:    [[R:%.*]] = fmul nsz float [[X:%.*]], -5.000000e+00
; CHECK-NEXT:    ret float [[R]]
;
  %mul = fmul float %x, 5.000000e+00
  %add = fadd float %mul, %y
  %r = fsub nsz reassoc float %y, %add
  ret float %r
}
```

Comment (arsenm) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: Fail, meaning it now preserves nsz and not the reassoc? That's fine. That is more in line with what the LangRef states the rules are for reassoc: https://llvm.org/docs/LangRef.html#rewrite-based-flags

**Review by arsenm — APPROVED** [review]

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp [hunk 6]
```diff
@@ -2741,6 +2741,17 @@ Instruction *InstCombinerImpl::visitSub(BinaryOperator &I) {
...
+static FastMathFlags combineFastMathFlagsForFNeg(FastMathFlags FMF,
+                                                 FastMathFlags OpFMF) {
+  FastMathFlags Flag = FMF | OpFMF;
+  Flag.setNoInfs(FMF.noInfs() && OpFMF.noInfs());
+  Flag.setAllowReassoc(FMF.allowReassoc() && OpFMF.allowReassoc());
+  Flag.setApproxFunc(FMF.approxFunc() && OpFMF.approxFunc());
+  Flag.setAllowReciprocal(FMF.allowReciprocal() && OpFMF.allowReciprocal());
+  Flag.setAllowContract(FMF.allowContract() && OpFMF.allowContract());
+  return Flag;
+}
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2753]: We should have an | value flag & rewrite flag helper in FastMathFlags but can do API cleanups later

File: llvm/test/Transforms/InstCombine/fneg.ll (hunk 3 above)
Comment (andykaylor) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: > ```llvm
> ; With nsz and reassoc: Y - ((X * 5) + Y) --> X * -5
> ```

That transformation should require `nnan` or isKnownNeverNaN(Y)

Comment (arsenm) [reply llvm/test/Transforms/InstCombine/fneg.ll:1203]: Somewhere else's bug though

File: llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp [hunk 7]
```diff
@@ -2742,6 +2742,17 @@ Instruction *InstCombinerImpl::visitSub(BinaryOperator &I) {
   return TryToNarrowDeduceFlags();
 }
 
+static FastMathFlags combineFastMathFlagsForFNeg(FastMathFlags FMF,
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2745]: Name is too specific, but I'm not sure what to call this. Also, it should be directly in FastMathFlags.

Maybe unionWithRewriteIntersect? Plus the no infinity special case can be applied after

Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2745]: Can we try this approach in `FMF`?
```cpp
    FastMathFlags Result = this->Flags & Other.Flags;
    Result.setNoNaNs(this->noNaNs() || Other.noNaNs());
    Result.setNoSignedZeros(this->noSignedZeros() || Other.noSignedZeros());
    return Result;
```

Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp:2745]: @arsenm

Comment (SahilPatidar) [reply llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp]: @arsenm

**Comment by vgvassilev** [comment]
Any plans on landing this?

**Review by dtcxzyw — APPROVED** [review]
LGTM. Thank you!
However, this PR only fixes FMF propagation for `fneg + fmul`. The remaining part of the original issue (`fsub + fmul` and `fneg + fdiv`) is still outstanding: https://alive2.llvm.org/ce/z/Jt3n6P

**Comment by dtcxzyw** [comment]
> The remaining part of the original issue (fsub + fmul and fneg + fdiv) is still outstanding: https://alive2.llvm.org/ce/z/Jt3n6P

Double confirmed that they don't exist: https://alive2.llvm.org/ce/z/GELV_d
