### PR TITLE
[HLSL] Add additional overloads for min and max to allow for mixed scalar and vector arguments

### LINKED ISSUE #128231: [HLSL] `max` and `min` overloads with mixed scalar and vector arguments
Presently Clang fails to resolve `max` and `min` function calls when the arguments are mixes of scalar and vector type. This prevents common code patterns such as:

```hlsl
export int4 call(int4 I, int Min) {
    return min(I, Min); // calls min(int4, int4)
}
```

These patterns are particularly useful with literal values.

### PR DESCRIPTION
**Pull request by spall**
Add additional overloads for min and max to support
min(vector<T,N>, T) and min(T, vector<T,N>)
max(vector<T,N>, T) and max(T, vector<T,N>)
Add tests
Closes #128231

### CODE REVIEW

File: clang/lib/Headers/hlsl/hlsl_intrinsics.h [hunk 1]
```diff
@@ -1678,6 +1678,30 @@ half3 max(half3, half3);
 _HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)
 _HLSL_BUILTIN_ALIAS(__builtin_elementwise_max)
 half4 max(half4, half4);
+_HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)
+constexpr half2 max(half2 p0, half p1) {
```
Comment (bob80905) [inline clang/lib/Headers/hlsl/hlsl_intrinsics.h:1682]: If a user were to call the max function with, say, a half2 and a half3, is it our intention to reject that / emit an error?

Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_intrinsics.h:1682]: We only want to allow things of the form max(vector<T,N>, T) or max(T, vector<T,N>)

File: clang/test/CodeGenHLSL/builtins/min.hlsl [hunk 2]
```diff
@@ -131,3 +157,9 @@ double3 test_min_double3(double3 p0, double3 p1) { return min(p0, p1); }
 // CHECK-LABEL: define noundef nofpclass(nan inf) <4 x double> @_Z16test_min_double4
 // CHECK: call reassoc nnan ninf nsz arcp afn <4 x double> @llvm.minnum.v4f64
 double4 test_min_double4(double4 p0, double4 p1) { return min(p0, p1); }
+// CHECK-LABEL: define noundef nofpclass(nan inf) <4 x double> {{.*}}test_min_double4_mismatch
+// CHECK: call reassoc nnan ninf nsz arcp afn <4 x double> @llvm.minnum.v4f64
+double4 test_min_double4_mismatch(double4 p0, double p1) { return min(p0, p1); }
+// CHECK-LABEL: define noundef nofpclass(nan inf) <4 x double> {{.*}}test_min_double4_mismatch2
+// CHECK: call reassoc nnan ninf nsz arcp afn <4 x double> @llvm.minnum.v4f64
+double4 test_min_double4_mismatch2(double4 p0, double p1) { return min(p1, p0); }
```
Comment (bob80905) [inline clang/test/CodeGenHLSL/builtins/min.hlsl:165]: Shouldn't this parameter swap test be applicable to all the rest of the tests? Why just double?

Comment (spall) [reply clang/test/CodeGenHLSL/builtins/min.hlsl:165]: Yes, I just didn't want to add tons of tests; I also didn't add a test for each size of vector, only the vec4s. I can add more tests if you think its important.

**Review by bob80905 — APPROVED** [review]
I can approve this, though it might be worth considering adding a macro at the top of hlsl_intrinsics.h, along with some of the other macros there, to shrink the change and possibly simplify future changes that need these types of sets of overloads.

**Review by damyanp — COMMENTED** [review]
Are there any error conditions that need testing as well?

**Comment by spall** [comment]
> Are there any error conditions that need testing as well?

I don't think there were error tests for min and max originally. I could add some to make sure things like min(int4, int3) are still now allowed.

**Review by bob80905 — APPROVED** [review]
