### PR TITLE
[RISCV][llvm] Handle `ptr` element type in `lowerDeinterleaveIntrinsicToLoad` and `lowerInterleaveIntrinsicToStore`

### LINKED ISSUE #106970: [RISCV] Assertion failed: (MinNumElts > 0 && "#Elements of a VectorType must be greater than 0")
I'm running into a crash when building SPEC CPU 2017 with rva22u64_v -O3 that I've bisected back to 239127d731e633f89b912b0775b638c0e8b4a9eb

```llvm
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @Perl_sortsv_flags() #0 {
entry:
  ret void

while.cond.i.i:                                   ; preds = %vector.ph165, %while.cond.i.i
  br label %while.cond.i.i

vector.ph165:                                     ; No predecessors!
  %wide.vec = load <vscale x 4 x ptr>, ptr null, align 8
  %strided.vec = call { <vscale x 2 x ptr>, <vscale x 2 x ptr> } @llvm.vector.deinterleave2.nxv4p0(<vscale x 4 x ptr> %wide.vec)
  br label %while.cond.i.i
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare { <vscale x 2 x ptr>, <vscale x 2 x ptr> } @llvm.vector.deinterleave2.nxv4p0(<vscale x 4 x ptr>) #1

attributes #0 = { "target-features"="+64bit,+a,+c,+d,+f,+m,+relax,+v,+za64rs,+zba,+zbb,+zbs,+zfhmin,+zic64b,+zicbom,+zicbop,+zicboz,+ziccamoa,+ziccif,+zicclsm,+ziccrse,+zicntr,+zicsr,+zihintpause,+zihpm,+zkt,+zmmul,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvl128b,+zvl32b,+zvl64b,-b,-e,-experimental-smctr,-experimental-smmpm,-experimental-smnpm,-experimental-ssctr,-experimental-ssnpm,-experimental-sspm,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-h,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zbc,-zbkb,-zbkc,-zbkx,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfinx,-zhinx,-zhinxmin,-zicond,-zifencei,-zihintntl,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-ztso,-zvbb,-zvbc,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl4096b,-zvl512b,-zvl65536b,-zvl8192b" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(none) }
```

The reduced case above hits an assertion in `llvm::RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad`:

```
Assertion failed: (MinNumElts > 0 && "#Elements of a VectorType must be greater than 0"), function get, file Type.cpp, line 711.
```

I haven't looked into it fully just yet, but I wonder if it's something related to pointer types.

### PR DESCRIPTION
**Pull request by 4vtomat**
Resolve https://github.com/llvm/llvm-project/issues/106970

currently it returns 0 fixed size for `ptr` element type. The `ptr`
element size should depend on `XLen` which is 64 in riscv64 and 32 in
riscv32 respectively.

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -21951,7 +21951,9 @@ bool RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(
         Intrinsic::riscv_vlseg6, Intrinsic::riscv_vlseg7,
         Intrinsic::riscv_vlseg8};
 
-    unsigned SEW = ResVTy->getElementType()->getScalarSizeInBits();
+    unsigned SEW = ResVTy->getElementType()->isPointerTy()
+                       ? Subtarget.getXLen()
+                       : ResVTy->getElementType()->getScalarSizeInBits();
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:21956]: Can we use DataLayout instead of hardcoding XLEN?
```suggestion
unsigned SEW = DI->getDataLayout().getTypeSizeInBits(ResVTy->getElementType());
```

Comment (4vtomat) [reply llvm/lib/Target/RISCV/RISCVISelLowering.cpp:21956]: Sure~ it's a good idea!

**Review by lukel97 — APPROVED** [review]
LGTM, thanks for fixing this!

**Review by wangpc-pp — APPROVED** [review]

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 2]
```diff
@@ -21951,7 +21951,8 @@ bool RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(
         Intrinsic::riscv_vlseg6, Intrinsic::riscv_vlseg7,
         Intrinsic::riscv_vlseg8};
 
-    unsigned SEW = ResVTy->getElementType()->getScalarSizeInBits();
+    unsigned SEW =
+        DI->getDataLayout().getTypeSizeInBits(ResVTy->getElementType());
```
Comment (topperc) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:21955]: Can we save the DataLayout in a variable? We used it earlier for the `isLegalInterleavedAccessType` check.

Comment (4vtomat) [reply llvm/lib/Target/RISCV/RISCVISelLowering.cpp]: Sure we can~

**Review by topperc — APPROVED** [review]
LGTM

**Comment by mshabunin** [comment]
Apparently this change also fixes a problem with illegal instructions being generated for some RISC-V RVV code which we have observed with llvm 18 and 19. I'm not sure if it is a coincidence or both issues have the same root cause. I've found this commit and PR by bisecting llvm between start of 20th dev cycle and some commit at the main (10c6d6349e51bb245b9deec4aafca9885971135b - 4822e9dce3483fdec7957cea092384041c8ca013).

Our issue was with `vfncvt` instruction being added in the generated code with register overlap (source is a register group of 2 = v8-v9 and destination is a single register v9) which is illegal instruction:
```
vsetvli	a0, zero, e32, m1, ta, ma
vfncvt.f.f.w	v9, v8
```

I couldn't create small reproducer, so I'm attaching a larger one for completeness: [repro-19.1.0.zip](https://github.com/user-attachments/files/17187374/repro-19.1.0.zip)

**Comment by topperc** [comment]
> Apparently this change also fixes a problem with illegal instructions being generated for some RISC-V RVV code which we have observed with llvm 18 and 19. I'm not sure if it is a coincidence or both issues have the same root cause. I've found this commit and PR by bisecting llvm between start of 20th dev cycle and some commit at the main ([10c6d63](https://github.com/llvm/llvm-project/commit/10c6d6349e51bb245b9deec4aafca9885971135b) - [4822e9d](https://github.com/llvm/llvm-project/commit/4822e9dce3483fdec7957cea092384041c8ca013)).
> 
> Our issue was with `vfncvt` instruction being added in the generated code with register overlap (source is a register group of 2 = v8-v9 and destination is a single register v9) which is illegal instruction:
> 
> ```
> vsetvli	a0, zero, e32, m1, ta, ma
> vfncvt.f.f.w	v9, v8
> ```
> 
> I couldn't create small reproducer, so I'm attaching a larger one for completeness: [repro-19.1.0.zip](https://github.com/user-attachments/files/17187374/repro-19.1.0.zip)

I checked out 19.1 and built it. I don't see `vfncvt.f.f.w	v9, v8`. The only `vfncvt.f.f.w` I see is `vfncvt.f.f.w v10, v8`.

**Comment by mshabunin** [comment]
Sorry for misleading comment, with that reproducer incorrect instruction is `vfncvt.x.f.w v11,v10` with m1 group:
```
/work/chains/llvm-19.1.0/bin/llvm-objdump -d test_intrin-72f8b0.o | grep -B 2 vfncvt
<cut>
     50e: 0aab5557     	vfsub.vf	v10, v10, fs6
     512: 0d007557     	vsetvli	a0, zero, e32, m1, ta, ma
     516: 4aa895d7     	vfncvt.x.f.w	v11, v10
<cut>
```

**Comment by topperc** [comment]
> Sorry for misleading comment, with that reproducer incorrect instruction is `vfncvt.x.f.w v11,v10` with m1 group:
> 
> ```
> /work/chains/llvm-19.1.0/bin/llvm-objdump -d test_intrin-72f8b0.o | grep -B 2 vfncvt
> <cut>
>      50e: 0aab5557     	vfsub.vf	v10, v10, fs6
>      512: 0d007557     	vsetvli	a0, zero, e32, m1, ta, ma
>      516: 4aa895d7     	vfncvt.x.f.w	v11, v10
> <cut>
> ```

It's possible this was fixed by bf8101e4fd1a532aed4c6b6a33d202e143ce303fc

**Comment by mshabunin** [comment]
> It's possible this was fixed by [bf8101e](https://github.com/llvm/llvm-project/commit/bf8101e4fd1a532aed4c6b6a33d202e143ce303f)

Yes, it seems so. I don't observe this issue with our tests with the patch #110603.
Thank you!
