### PR TITLE
[HLSL] Do not print details in IR for target extension types

### LINKED ISSUE #114131: Invalid type description generated in DXIL IR for StructuredBuffer
An invalid form of a type was being generated in the DXIL IR for the StructuredBuffer type.  This form was causing 'opt' to fail with a syntax error while parsing the IR.

godbolt: https://godbolt.org/z/zf7TTWa5q

Shader compiled with -T cs_6_6
```
struct mystruct
{
    float4 Color;
};

StructuredBuffer<mystruct> my_buffer : register(t2, space4);

export float4 test()
{
    return my_buffer[0].Color;
}

[numthreads(1,1,1)]
void main() {}
```

See `%"class.hlsl::StructuredBuffer" = type { target("dx.RawBuffer", %struct.mystruct = type { <4 x float> }, 0, 0), %struct.mystruct }`

Type section for IR
```
%"class.hlsl::StructuredBuffer" = type { target("dx.RawBuffer", %struct.mystruct = type { <4 x float> }, 0, 0), %struct.mystruct }
%struct.mystruct = type { <4 x float> }
%dx.types.Handle = type { ptr }
%dx.types.ResBind = type { i32, i32, i32, i8 }
%dx.types.ResourceProperties = type { i32, i32 }
```

The part "%struct.mystruct = type" is causing the parsing error.

I believe the expected form is:
```
%"class.hlsl::StructuredBuffer" = type { target("dx.RawBuffer", { <4 x float> }, 0, 0), %struct.mystruct }
```

### PR DESCRIPTION
**Pull request by bob80905**
This PR changes how target extension types are printed when they are emitted as IR.
This prevents repetitive phrases like "struct = type {...}" from being repeated over and over in the outputted IR.
Additionally, it should allow opt to not crash when parsing the DXIL output.

Fixes [#114131](https://github.com/llvm/llvm-project/issues/114131)

### CODE REVIEW

**Comment by bogner** [comment]
This doesn't look right to me. Changing the type printer so it doesn't differentiate between named and anonymous structs inside a target extension type like this looks like it will break round-tripping through LLVM IR, since the fact that this was associated with a named struct and not an anonymous one is lost.

I suspect we're actually creating the wrong types (in DirectXTargetCodeGenInfo::getHLSLType) in the first place, since target extension types don't seem to handle named structs at all. Additionally, we should probably add checks when creating a target extension type to prevent creating them with named struct types.

File: llvm/unittests/IR/TypesTest.cpp [hunk 1]
```diff
@@ -40,10 +40,43 @@ TEST(TypesTest, TargetExtType) {
...
   // Opaque types with same parameters are identical...
   EXPECT_EQ(Aparam, Aparam2);
   // ... but just having the same name is not enough.
   EXPECT_NE(A, Aparam);
+
+  // ensure struct types in targest extension types
+  // only show the struct name, not the struct body
+  Type *Int32Type = Type::getInt32Ty(Context);
+  Type *FloatType = Type::getFloatTy(Context);
+  std::vector<Type *> OriginalElements = {Int32Type, FloatType};
```
Comment (bogner) [inline llvm/unittests/IR/TypesTest.cpp:53]: No need for a vector here - this is a fixed size array. Also what's "original" about these elements?
```suggestion
  std::array<Type *, 2> Elements{Int32Type, FloatType};
```

File: llvm/unittests/IR/TypesTest.cpp [hunk 2]
```diff
@@ -40,10 +40,43 @@ TEST(TypesTest, TargetExtType) {
...
+  StructType *Struct = llvm::StructType::create(Context, "MyStruct");
+  Struct->setBody(OriginalElements);
```
Comment (bogner) [inline llvm/unittests/IR/TypesTest.cpp:55]: There's an overload of `create` that sets the elements directly:
```suggestion
  StructType *Struct = llvm::StructType::create(Context, Elements, "MyStruct",
                                                /*isPacked=*/false);
```

File: llvm/unittests/IR/TypesTest.cpp [hunk 3]
```diff
@@ -40,10 +40,43 @@ TEST(TypesTest, TargetExtType) {
...
+
+  // the other struct is different only in that it's an anonymous struct,
+  // without a name
```
Comment (bogner) [inline llvm/unittests/IR/TypesTest.cpp:58]: The StructType docs call an unnamed struct a "literal struct" rather than anonymous: https://llvm.org/doxygen/classllvm_1_1StructType.html#details.

I would probably just say something to the effect of "ensure that literal structs in the target extension type print the struct body" to mirror the comment earlier.

File: llvm/unittests/IR/TypesTest.cpp [hunk 4]
```diff
@@ -40,10 +40,43 @@ TEST(TypesTest, TargetExtType) {
...
+  llvm::raw_svector_ostream TETStream(TETV);
+  TargetExtensionType->print(TETStream);
+
+  llvm::raw_svector_ostream OtherTETStream(OtherTETV);
+  OtherTargetExtensionType->print(OtherTETStream);
+
+  EXPECT_STREQ(TETStream.str().str().data(),
+               "target(\"structTET\", %MyStruct, 0, 1)");
+  EXPECT_STREQ(OtherTETStream.str().str().data(),
+               "target(\"structTET\", { i32, float }, 0, 1)");
```
Comment (bogner) [inline llvm/unittests/IR/TypesTest.cpp:79]: It'd be better to do all of the work to test the identified struct, and then do the work for the literal struct as a second step. This way you can avoid the duplicate `StructType *`, `TargetExtensionType *`, `SmallVector`, and `raw_svector_ostream` variables, and it will be clearer that these are two related but entirely independent tests.

**Review by bogner — APPROVED** [review]
Looks good!

**Comment by bogner** [comment]
The title and description are out of date since we changed the approach here - please update them.

**Review by bogner — APPROVED** [review]

**Comment by hekota** [comment]
LGTM!
