### PR TITLE
[OpenACC] Fix Crash on collapse that doesn't check its transform

### LINKED ISSUE #191833: [clang][OpenACC] crash when using #pragma acc loop collapse in a template
Reproducer:
https://godbolt.org/z/ezWaxfTcq
```cpp
struct S {
  typename T;
};

template<typename T>
void foo() {
#pragma acc loop collapse(T{})
}

void bar() {
  foo<S>();
}
```

Backtrace:
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -fopenacc <source>
1.	<eof> parser at end of file
2.	<source>:6:6: instantiating function definition 'foo<S>'
 #0 0x00000000044c3f98 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44c3f98)
 #1 0x00000000044c0dc4 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44c0dc4)
 #2 0x00000000044c13e4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44c13e4)
 #3 0x00000000043ff128 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x000070801a042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x0000000008528415 clang::Stmt::getBeginLoc() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x8528415)
 #6 0x00000000079414b9 clang::OpenACCClauseVisitor<clang::(anonymous namespace)::OpenACCClauseTransform<(anonymous namespace)::TemplateInstantiator>>::Visit(clang::OpenACCClause const*) (.constprop.0) SemaTemplateInstantiate.cpp:0:0
 #7 0x0000000007941e4f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformOpenACCClauseList(clang::OpenACCDirectiveKind, llvm::ArrayRef<clang::OpenACCClause const*>) SemaTemplateInstantiate.cpp:0:0
 #8 0x0000000007945c47 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformOpenACCLoopConstruct(clang::OpenACCLoopConstruct*) SemaTemplateInstantiate.cpp:0:0
 #9 0x0000000007943925 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#10 0x000000000794cd23 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x794cd23)
#11 0x00000000079eb2ec clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x79eb2ec)
#12 0x00000000079e9556 clang::Sema::PerformPendingInstantiations(bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x79e9556)
#13 0x0000000006f4e872 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::TUFragmentKind) (.part.0) Sema.cpp:0:0
#14 0x0000000006f4ebf2 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f4ebf2)
#15 0x0000000006db36ea clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db36ea)
#16 0x0000000006d944aa clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d944aa)
#17 0x0000000004fc9d58 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4fc9d58)
#18 0x00000000052e3ae5 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52e3ae5)
#19 0x00000000052627be clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52627be)
#20 0x00000000053e029d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x53e029d)
#21 0x0000000000de1e52 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde1e52)
#22 0x0000000000dd878a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#23 0x0000000000dd890d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#24 0x0000000005033f69 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#25 0x00000000043ff564 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43ff564)
#26 0x0000000005034596 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#27 0x0000000004ff2ca2 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ff2ca2)
#28 0x0000000004ff3c4e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ff3c4e)
#29 0x0000000004ffb915 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ffb915)
#30 0x0000000000dde1b4 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdde1b4)
#31 0x0000000000c9728a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc9728a)
#32 0x000070801a029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#33 0x000070801a029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#34 0x0000000000dd8225 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd8225)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by erichkeane**
GH191833 reports a problem with tree transformation of a collapse clause when the expression in the clause is invalid. This patch makes sure we skip out of transforming this clause if it ever encounters an invalid expression.

I also analyzed the rest of the clauses in this visitor and found 1 other that was suspicious, so I added a check for that one as well.  The rest seemingly were all done correctly.

Fixes: #191833

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -12651,13 +12651,22 @@ void OpenACCClauseTransform<Derived>::VisitCollapseClause(
...
   ExprResult NewLoopCount = Self.TransformExpr(LoopCount);
 
+  if (!NewLoopCount.isUsable())
+    return;
+
   NewLoopCount = Self.getSema().OpenACC().ActOnIntExpr(
       OpenACCDirectiveKind::Invalid, ParsedClause.getClauseKind(),
       NewLoopCount.get()->getBeginLoc(), NewLoopCount.get());
 
+  if (!NewLoopCount.isUsable())
```
Comment (shafik) [inline clang/lib/Sema/TreeTransform.h:12663]: So at least some of these are defensive and we don't have a test for them, IIUC, then we should probably leave a FIXME for those cases.

**Review by shafik — APPROVED** [review]
LGTM besides my nit.

File: clang/lib/Sema/TreeTransform.h (hunk 1 above)
Comment (erichkeane) [reply clang/lib/Sema/TreeTransform.h:12663]: The secret of tree-transform is that basically ALL of these are defensive and untested lol.  I'd suggest not doing a code-coverage on these :D
