### PR TITLE
[HLSL] set alwaysinline on HLSL functions

### LINKED ISSUE #89282: [DXIL] Always inline HLSL functions by default
### Summary

At present, inlining in HLSL follows the existing heuristics which will inline if the function is short enough. To be correct in HLSL, we need to inline all non-entry functions. To do this we need to annotate either calls or function definitions (or some combination of both) as alwaysinline so that the inliner forces them to be inlined.

For HLSL shader and library targets, automatically apply the alwaysinline attribute to non-entry functions with tests regardless of qualifiers. The exception is the autogenerated unmangled main() function

Note that there are cases where not everything should be inlined (eg noinline attribute). This is out of scope for this issue.

### PR DESCRIPTION
**Pull request by pow2clk**
HLSL inlines all its functions by default. This uses the alwaysinline attribute to force that in the corresponding pass for user functions by default and overrides the default noinline of some implicit functions. This makes an instance of explicit inlining for buffer subscripts unnecessary.

Adds tests for function and constructor inlining and augments some existing tests to verify correct inlining of implicitly created functions as well.

incidentally restore RUN line that I believe was mistakenly removed as part of #88918

fixes #89282

### CODE REVIEW

File: clang/lib/CodeGen/CGHLSLRuntime.cpp [hunk 1]
```diff
@@ -414,9 +414,20 @@ void CGHLSLRuntime::emitEntryFunction(const FunctionDecl *FD,
...
+      Fn->addFnAttr(ExportAttrKindStr);
+    }
+    // Respect noinline if the explicit functions use it
+    // otherwise default to alwaysinline
+    if (!Fn->hasFnAttribute(Attribute::NoInline))
+      Fn->addFnAttr(llvm::Attribute::AlwaysInline);
+  } else { // "implicit" autogenerated functions with no declaration
+    // Implicit functions might get marked as noinline by default
+    // but we override that for HLSL
+    Fn->removeFnAttr(Attribute::NoInline);
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CGHLSLRuntime.cpp:429]: Which auto-generated functions are getting noinline attached to them? Do you know where that is happening?

File: clang/lib/Sema/HLSLExternalSemaSource.cpp [hunk 2]
```diff
@@ -290,8 +290,6 @@ struct BuiltinTypeDeclBuilder {
                                              SourceLocation()));
     MethodDecl->setLexicalDeclContext(Record);
     MethodDecl->setAccess(AccessSpecifier::AS_public);
-    MethodDecl->addAttr(AlwaysInlineAttr::CreateImplicit(
-        AST, SourceRange(), AlwaysInlineAttr::CXX11_clang_always_inline));
```
Comment (llvm-beanz) [inline clang/lib/Sema/HLSLExternalSemaSource.cpp:294]: Why was it necessary to remove this? I think we want this because we'll want these calls inlined even in separate compilation cases.

File: clang/lib/CodeGen/CGHLSLRuntime.cpp (hunk 1 above)
Comment (llvm-beanz) [reply clang/lib/CodeGen/CGHLSLRuntime.cpp:429]: It seems to me like it might make more sense to change that condition to not do that for HLSL rather than to modify the IR after we generate it incorrectly.

File: clang/lib/Sema/HLSLExternalSemaSource.cpp (hunk 2 above)
Comment (llvm-beanz) [reply clang/lib/Sema/HLSLExternalSemaSource.cpp:294]: We don't really have a workflow in Clang implemented yet for separate compilation. The analog in DXC would be something like `-T lib_6_x -default-linkage=external`. In that case we would still want these functions to be inlined, and we can accomplish that with this attribute.

**Review by pow3clk — COMMENTED** [review]
On my laptop account. I assure you it's who you think it is.

**Review by python3kgae — APPROVED** [review]

File: clang/lib/CodeGen/CodeGenFunction.cpp [hunk 3]
```diff
@@ -1239,9 +1239,9 @@ void CodeGenFunction::StartFunction(GlobalDecl GD, QualType RetTy,
...
     CGM.getOpenMPRuntime().emitFunctionProlog(*this, CurCodeDecl);
 
-  if (FD && getLangOpts().HLSL) {
+  if (getLangOpts().HLSL) {
     // Handle emitting HLSL entry functions.
-    if (FD->hasAttr<HLSLShaderAttr>()) {
+    if (FD && FD->hasAttr<HLSLShaderAttr>()) {
       CGM.getHLSLRuntime().emitEntryFunction(FD, Fn);
     }
     CGM.getHLSLRuntime().setHLSLFunctionAttributes(FD, Fn);
```
Comment (damyanp) [inline clang/lib/CodeGen/CodeGenFunction.cpp:1247]: Maybe not for this change, but a bit of me is wondering if the two CGHLSLRuntime functions emitEntryFunction and setHLSLFunctionAttributes should be somewhat combined so that we end up with something like:

```c++
if (getLangOpts().HLSL)
    CGM.getHLSLRuntime().emitFunctionProlog(FD, Fn);
```

Similar to how this is encapsulated for OpenMP above.  That way we get more of the HLSL-specific stuff in CGHLSLRuntime.cpp.

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 4]
```diff
@@ -2474,7 +2474,9 @@ void CodeGenModule::SetLLVMFunctionAttributesForDefinition(const Decl *D,
     // If we don't have a declaration to control inlining, the function isn't
     // explicitly marked as alwaysinline for semantic reasons, and inlining is
     // disabled, mark the function as noinline.
+    // HLSL functions must be always inlined
     if (!F->hasFnAttribute(llvm::Attribute::AlwaysInline) &&
+        !getLangOpts().HLSL &&
```
Comment (damyanp) [inline clang/lib/CodeGen/CodeGenModule.cpp:2479]: A bit lower down there's some similar checks that seem to involve `AlwaysInline` and `OnlyAlwaysInlining` (around line 2536).  Does this also need to be updated for HLSL mode?

File: clang/lib/CodeGen/CodeGenFunction.cpp (hunk 3 above)
Comment (pow2clk) [reply clang/lib/CodeGen/CodeGenFunction.cpp:1247]: Yeah, the `emitFunctionProlog` form is how it looked in an earlier version of a change Helena made. I think it was #102275 which introduced `setHLSLFucntionAttributes`. I decided to follow her lead, but I don't know the reasoning behind it. 

This becomes moot with the new approach I'm taking.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 4 above)
Comment (pow2clk) [reply clang/lib/CodeGen/CodeGenModule.cpp:2479]: I investigated this in some depth. The situation is that the autogenerated initialization and destruction functions get their attributes set through this call and others before their bodies are generated, which calls `setHLSLFunctionAttributes` while user functions generate their bodies and make the hlsl attributes call before this one. This seems error-prone to me, but the code has been around long enough that I'm not ready to go changing it even though some initial experiments showed no regressions. 

In the meantime, since so much inline attribute logic is in this function, I've concluded that the best solution is to add our inline logic here and not in `setHLSLFunctionAttributes` at all. That way it doesn't matter as much where in the IR function creation process it takes place and any consequences can be accounted for along with the existing logic. That's what my latest commit does.

File: clang/test/CodeGenHLSL/inline-functions.hlsl [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+// This includes exported functions and mangled entry point implementation functions.
+// The unmangled entry functions must not be alwaysinlined.
+
+#define MAX 100
+
+float nums[MAX];
+
+// Verify that all functions have the alwaysinline attribute
+// CHECK: Function Attrs: alwaysinline
+// CHECK: define void @"?swap@@YAXY0GE@III@Z"(ptr noundef byval([100 x i32]) align 4 %Buf, i32 noundef %ix1, i32 noundef %ix2) [[IntAttr:\#[0-9]+]]
```
[the remark this answers is not in the document]
Comment (pow2clk) [reply clang/test/CodeGenHLSL/inline-functions.hlsl:16]: The reason why some of these won't be removed is because of the `-disable-llvm-passes` flag which skips optimizations that remove trivially dead functions.

This comment did make me realize there is a bug in waiting though. We don't yet remove trivially dead functions like this at all because the internal linkage marking takes place after any pass that would remove them. I have a tentative fix that depends on this change here #106146. Once this is in, I'll focus on that. Once that's in, these won't show up in the INLINE case, so I moved them to be NOINLINE exclusive.

**Review by pow2clk — COMMENTED** [review]
Thanks Damyan!

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 6]
```diff
@@ -2471,11 +2471,14 @@ void CodeGenModule::SetLLVMFunctionAttributesForDefinition(const Decl *D,
     B.addAttribute(llvm::Attribute::StackProtectReq);
 
   if (!D) {
+    // HLSL functions must always be inlined
+    if (getLangOpts().HLSL && !F->hasFnAttribute("hlsl.shader"))
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CodeGenModule.cpp:2475]: What if we put `noinline` on the entry function? Does that simplify this logic? Since we'll also at some point need to support the `noinline` keyword we'll need to be checking that attribute somewhere.

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 7]
```diff
@@ -2471,11 +2471,14 @@ void CodeGenModule::SetLLVMFunctionAttributesForDefinition(const Decl *D,
     B.addAttribute(llvm::Attribute::StackProtectReq);
 
   if (!D) {
+    // HLSL functions must always be inlined
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CodeGenModule.cpp:2474]: nit: we do try have comments be complete sentences and puctuated.
```suggestion
    // HLSL functions must always be inlined.
```

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 8]
```diff
@@ -2502,9 +2505,12 @@ void CodeGenModule::SetLLVMFunctionAttributesForDefinition(const Decl *D,
   ShouldAddOptNone &= !D->hasAttr<MinSizeAttr>();
   ShouldAddOptNone &= !D->hasAttr<AlwaysInlineAttr>();
 
-  // Add optnone, but do so only if the function isn't always_inline.
-  if ((ShouldAddOptNone || D->hasAttr<OptimizeNoneAttr>()) &&
-      !F->hasFnAttribute(llvm::Attribute::AlwaysInline)) {
+  // alwaysinline all HLSL functions save entry points
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CodeGenModule.cpp:2508]: nit: 
```suggestion
  // Add alwaysinline on all HLSL functions except entry points.
```

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 6 above)
Comment (pow2clk) [reply clang/lib/CodeGen/CodeGenModule.cpp:2475]: In earlier discussion, we resolved to make this the default and not worry about noinline as of yet seeing as there are a lot of issues to resolve before that can work properly. In a previous version, I was forced to check for noinline as it was a sign that a function had passed through this function, but my preference is to not respect it until we've worked out the issues that prevent it from working right. 

 It wouldn't simplify the logic since the entry function doesn't get marked inline until it is passed into this function.

**Review by damyanp — APPROVED** [review]
LGTM, but would be good to get a review from someone more knowledgeable in the area than I am.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 6 above)
Comment (pow2clk) [reply clang/lib/CodeGen/CodeGenModule.cpp:2475]: Just an update. As a result of the waning minutes of a design discussion, we resolved to produce a warning when users apply noinline and explicitly set noinline for the outermost entry function which would allow checking for that in place of hlsl.shader here, which might allow graceful resolution of any other functions that happen to get it applied here which we could have an assert for.

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 9]
```diff
@@ -2502,9 +2505,16 @@ void CodeGenModule::SetLLVMFunctionAttributesForDefinition(const Decl *D,
...
 
-  // Add optnone, but do so only if the function isn't always_inline.
-  if ((ShouldAddOptNone || D->hasAttr<OptimizeNoneAttr>()) &&
-      !F->hasFnAttribute(llvm::Attribute::AlwaysInline)) {
+  // Non-entry HLSL functions must always be inlined.
+  if (getLangOpts().HLSL && !F->hasFnAttribute(llvm::Attribute::NoInline)) {
+    if (D->hasAttr<NoInlineAttr>())
+      getDiags().Report(D->getLocation(),
+                        diag::warn_unsupported_attribute_ignored)
+          << "noinline" << "HLSL";
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CodeGenModule.cpp:2513]: Why are we warning on this? Does the Clang implementation not work?

If we're going to warn on this, it needs to be in Sema not CodeGen!

File: clang/test/SemaHLSL/noinline.hlsl [hunk 10]
```diff
@@ -0,0 +1,13 @@
+// RUN: %clang_cc1 -triple dxil-pc-shadermodel6.0-compute -emit-llvm-only %s -verify
```
Comment (llvm-beanz) [inline clang/test/SemaHLSL/noinline.hlsl:1]: We should not need to emit IR to test a warning. This should work with `-fsyntax-only` or without the `-emit-llvm-only` flag.

**Review by llvm-beanz — APPROVED** [review]

**Comment by nico** [comment]
Looks like the _revert_ broke check-clang: http://45.33.8.238/linux/148045/step_6.txt

Please take a look, and uh, mark that test as UNSUPPORTED if it takes a while to fix, I suppose.

**Comment by nico** [comment]
@thurstond ^

**Comment by thurstond** [comment]
@nico Sorry, my bad. I didn't notice the test was also updated as a companion to this change (https://github.com/llvm/llvm-project/pull/109023). I'll revert the test as well.

**Comment by thurstond** [comment]
Oh, actually, I just realized the test update was the fix-forward. So the correct fix would be to reland both the change and the test update. Sorry!

**Comment by thurstond** [comment]
I've reverted both of my reverts

**Comment by pow2clk** [comment]
Sorry I didn't mention here that the fix was in. It looks like everything is clean now?

**Comment by thurstond** [comment]
> Sorry I didn't mention here that the fix was in. It looks like everything is clean now?

Yes, both your changes are back in and I anticipate the buildbots will be green again. Sorry for the noise!
