### PR TITLE
[InstCombine] Fold comparison of adding two z/sext booleans

### LINKED ISSUE #64859: Comparison of add of extended booleans not folded to xor
I was looking at [some code that tried to compute a sort of enum scheme by adding booleans, and comparing to constant values which failed to form nice boolean code](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/46939af92ad91238c878a82aad2220822073ffa1/ocml/src/powF_base.h#L64). This is really just an xor.

https://alive2.llvm.org/ce/z/RSnV-d

```
define i1 @src(i1 %arg, i1 %arg1) {
bb:
  %i = zext i1 %arg to i32
  %i2 = zext i1 %arg1 to i32
  %i3 = add nuw nsw i32 %i2, %i
  %i4 = icmp eq i32 %i3, 1
  ret i1 %i4
}

define i1 @tgt(i1 %arg, i1 %arg1) {
bb:
  %xor = xor i1 %arg, %arg1
  ret i1 %xor
}

```

### PR DESCRIPTION
**Pull request by elhewaty**
- Add test coverage for sext/zext boolean additions
- [InstCombine] Fold comparison of adding two z/sext booleans

Fixes https://github.com/llvm/llvm-project/issues/64859.

### CODE REVIEW

**Comment by elhewaty** [comment]
alive2 links:
// zext i1 X + zext i1 Y != 0 --> or i1 X, Y
https://alive2.llvm.org/ce/z/Rg3mm7

// zext i1 Op0 + zext i1 Op1 != 1 --> !(xor i1 Op0, Op1)
https://alive2.llvm.org/ce/z/WFyF_2

// zext i1 Op0 + zext i1 Op1 != 2 --> !(and i1 Op0, Op1)
https://alive2.llvm.org/ce/z/-QgaLR

// sext i1 Op0 + sext i1 Op1 != 0 --> or i1 Op0, Op1
https://alive2.llvm.org/ce/z/oPXhLY

// sext i1 Op0 + sext i1 Op1 != 1 --> true
https://alive2.llvm.org/ce/z/xTWVYh

// sext i1 Op0 + sext i1 Op1 != 2 --> true
https://alive2.llvm.org/ce/z/GoroRZ

// sext i1 Op0 + zext i1 Op1 != 0 --> xor i1 Op0, Op1
https://alive2.llvm.org/ce/z/mN7g3V

// sext i1 Op0 + zext i1 Op1 != 1 --> Op0 | (!Op1)
https://alive2.llvm.org/ce/z/FT_8iD

// sext i1 Op0 + zext i1 Op1 != 2 --> true
https://alive2.llvm.org/ce/z/ih8K7-

**Review by nikic — COMMENTED** [review]
As a high level comment, I'm not a big fan of this long list of special cases. An alternative approach to this would to construct the truth table for this explicitly (i.e. evaluate `icmp pred (ext1 x), (ext2 y)` explicitly for all 4 x, y) and then use a helper that converts a binary truth table into logic.

Unfortunately, I don't think we have an existing helper to convert a truth table to logic (I think @goldsteinn wrote something for vternlog, which is not quite what we'd need here).

**Comment by elhewaty** [comment]
Do we have functions for building truth tables?

**Comment by dtcxzyw** [comment]
Hi! I wrote a Python script to generate the lookup table.
Python script: https://paste.ubuntu.com/p/HTqRkYJ7hT/
Generated code: 
```
Instruction *ExtA, *ExtB;
if (Cmp.isEquality() &&
      match(Add, m_c_Add(m_CombineAnd(m_Instruciton(ExtA), m_OneUse(m_ZExtOrSExt(m_Value(Op0)))),
                         m_CombineAnd(m_Instruciton(ExtB), m_OneUse(m_ZExtOrSExt(m_Value(Op1)))))) &&
      Op0->getType()->isIntOrIntVectorTy(1) &&
      Op1->getType()->isIntOrIntVectorTy(1) &&
      C.sge(-2) && C.sle(2)) {
    bool ZExtA = ExtA->getOpcode() == Instruction::ZExt;
    bool ZExtB = ExtB->getOpcode() == Instruction::ZExt;
    bool PredNe = Cmp.getPredicate() == CmpInst::ICMP_NE;
    // (zextA, zextB, pred, val, inv) -> op
    // op: 0 - false, 1 - true, 2 - and, 3 - or, 4 - xor, 5 - nand, 6 - nor, 7 - xnor, 8 - invalid
    const unsigned LUT[2][2][2][5][3] = {
2 ,8 ,8 ,4 ,8 ,8 ,6 ,8 ,8 ,0 ,8 ,8 ,0 ,8 ,8 ,5 ,8 ,8 ,7 ,8 ,8 ,3 ,8 ,8 ,1 ,8 ,8 ,1 ,8 ,8 ,0 ,8 ,8 ,8 ,6 ,2 ,7 ,8 ,8 ,8 ,2 ,6 ,0 ,8 ,8 ,1 ,8 ,8 ,8 ,3 ,5 ,4 ,8 ,8 ,8 ,5 ,3 ,1 ,8 ,8 ,0 ,8 ,8 ,8 ,2 ,6 ,7 ,8 ,8 ,8 ,6 ,2 ,0 ,8 ,8 ,1 ,8 ,8 ,8 ,5 ,3 ,4 ,8 ,8 ,8 ,3 ,5 ,1 ,8 ,8 ,0 ,8 ,8 ,0 ,8 ,8 ,6 ,8 ,8 ,4 ,8 ,8 ,2 ,8 ,8 ,1 ,8 ,8 ,1 ,8 ,8 ,3 ,8 ,8 ,7 ,8 ,8 ,5 ,8 ,8 ,};
    unsigned op = LUT[ZExtA][ZExtB][PredNe][C.getSExtValue() + 2][0];
    if (op == 8) {
      if (isFreeToInvert(Op0, Op0->hasOneUse())) {
        Op0 = Builder.CreateNot(Op0);
        op = LUT[ZExtA][ZExtB][PredNe][C.getSExtValue() + 2][1];
      }
      else {
        Op1 = Builder.CreateNot(Op1);
        op = LUT[ZExtA][ZExtB][PredNe][C.getSExtValue() + 2][2];
      }
    }
    switch(op) {
      case 0: return replaceInstUsesWith(Cmp, Builder.getFalse());
      case 1: return replaceInstUsesWith(Cmp, Builder.getTrue());
      case 2: return BinaryOperator::CreateAnd(Op0, Op1);
      case 3: return BinaryOperator::CreateOr(Op0, Op1);
      case 4: return BinaryOperator::CreateXor(Op0, Op1);
      case 5: return BinaryOperator::CreateNot(Builder.CreateAnd(Op0, Op1));
      case 6: return BinaryOperator::CreateNot(Builder.CreateOr(Op0, Op1));
      case 7: return BinaryOperator::CreateNot(Builder.CreateXor(Op0, Op1));
      default: llvm_unreachable("Invalid Ops");
    }
}
```
Alive2: https://alive2.llvm.org/ce/z/JgcfFJ

**Comment by elhewaty** [comment]
@dtcxzyw So you fixed the issue?

**Comment by dtcxzyw** [comment]
> @dtcxzyw So you fixed the issue?

You can use the script/generated code in this PR.
If necessary, I am willing to add a compile-time helper.

**Comment by elhewaty** [comment]
How should I use it?
Should I replace my code with the generated code?

**Comment by nikic** [comment]
@dtcxzyw I don't see how the lookup-table based implementation improves this code. It makes it impossible to understand or verify the logic behind the transform.

**Comment by dtcxzyw** [comment]
> @dtcxzyw I don't see how the lookup-table based implementation improves this code. It makes it impossible to understand or verify the logic behind the transform.

I will add a compile-time helper for this PR. Then we can write a constexpr binary function and match the truth tables.

**Comment by dtcxzyw** [comment]
BTW, [D143373](https://reviews.llvm.org/D143373) does a similar transformation with this PR. We should put the logic in `foldICmpUsingBoolRange` rather than `foldICmpAddConstant`.

**Comment by nikic** [comment]
To expand on my initial comment, what I had in mind is something like this (completely untested, probably will not compile):

```
if (match(Add, m_c_Add(m_CombineAnd(m_Instruction(Ext0), m_OneUse(m_ZExtOrSExt(m_Value(Op0)))),
                       m_CombineAnd(m_Instruction(Ext1), m_OneUse(m_ZExtOrSExt(m_Value(Op1)))))) &&
    Op0->getType()->isIntOrIntVectorTy(1) &&
    Op1->getType()->isIntOrIntVectorTy(1)) {
  std::bitset<4> Table;
  auto ComputeTable = [&](bool Op0Val, bool Op1Val) {
    int Res = 0;
    if (Op0Val)
      Res += isa<ZExtInst>(Ext0) ? 1 : -1;
    if (Op1Val)
      Res += isa<ZExtInst>(Ext1) ? 1 : -1;
    return ICmpInst::compare(APInt(BW, Res, true), C, Pred);
  };
  Table[0] = ComputeTable(false, false);
  Table[1] = ComputeTable(false, true);
  Table[2] = ComputeTable(true, false);
  Table[3] = ComputeTable(true, true);
  return createLogicFromTable(Table, Op0, Op1);
}

// ...

static Value *createLogicFromTable(const std::bitset<4> &Table, Value *Op0, Value *Op1, IRBuilderBase &Builder) {
  switch (Table.to_ulong()) {
  case 0: // 0 0 0 0
    return Builder.getTrue();
  case 1: // 0 0 0 1
    return Builder.CreateAnd(Op0, Op1);
  // etc.
  }
}
```

The computation of the logic table is pretty straightforward and can be done explicitly, without a static lookup table. The conversion from the table to logic is generic and not specific to this transform.

This approach also automatically works with all predicates, not just equality predicates, so I think this would also subsume the code from D143373 linked above.

**Comment by elhewaty** [comment]
I will update the pull, and add the lookup table.

**Comment by elhewaty** [comment]
@nikic  Just to make sure that I didn't miss something.
I should write tests for every comparisons operator against the constants(-2, -1, 0, 1, 2), right?
so (eq, ne, ugt, uge, ult, ule, sgt, sge, slt, sle)[10] * 5 = 50 tests.
and some tests for other numbers just for confirmation like 10, -5, .. etc

**Comment by nikic** [comment]
@elhewaty Given that the implementation is predicate-independent, I don't think you need the complete test matrix, just some representative tests for other predicates. Also keep in mind that uge, ule, sge, sle will be canonicalized to ugt, ult, sgt, slt, so it will not be possible to test those predicates in the first place.

**Comment by elhewaty** [comment]
@nikic what does m_CombineAnd function do?

**Comment by nikic** [comment]
> @nikic what does m_CombineAnd function do?

It requires that both arguments match. Here it is used to capture the sext/zext into a variable. You could also just use `X` and `Y` instead (I didn't do that because m_c_Add may change the order of Op0/Op1, but in this case the use of m_c_Add is actually unnecessary, and you could use the non-commutative m_Add instead).

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 1]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+    case 11: // 1 0 1 1
+      return Builder.CreateOr(Builder.CreateNot(Op0), Op1);
+    case 12: // 1 1 0 0
+      return Builder.CreateNot(Op1);
+    case 13: // 1 1 0 1
+      return Builder.CreateOr(Op0, Builder.CreateNot(Op1));
+    case 14: // 1 1 1 0
+      return Builder.CreateOr(Op0, Op1);
+    case 15: // 1 1 1 1
+      return Builder.getTrue();
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2933]: Add `default` with `llvm_unreachable`.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 2]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
 Instruction *InstCombinerImpl::foldICmpAddConstant(ICmpInst &Cmp,
                                                    BinaryOperator *Add,
                                                    const APInt &C) {
   Value *Y = Add->getOperand(1);
+  Value *X = Add->getOperand(0);
+
+  Value *Op0, *Op1;
+  Instruction *Ext0, *Ext1;
+  const CmpInst::Predicate Pred = Cmp.getPredicate();
+  if (match(Add, m_c_Add(m_CombineAnd(m_Instruction(Ext0),
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2948]: m_c_Add -> m_Add

Also, we are missing a one-use check on the add itself. The one-use checks on the extensions are pointless if the add itself is multi-use.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 3]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+                                      m_OneUse(m_ZExtOrSExt(m_Value(Op0)))),
+                         m_CombineAnd(m_Instruction(Ext1),
+                                      m_OneUse(m_ZExtOrSExt(m_Value(Op1)))))) &&
+    Op0->getType()->isIntOrIntVectorTy(1) &&
+    Op1->getType()->isIntOrIntVectorTy(1) &&
+    C.sge(-2) && C.sle(2)) {
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2954]: The condition on the constant looks unnecessary.

**Review by nikic — COMMENTED** [review]
Can you please try removing the code that was added in [D143373](https://reviews.llvm.org/D143373)? As far as I understand, your fold should fully subsume the old one.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp (hunk 2 above)
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2948]:
```suggestion
  if (match(Add, m_OneUse(m_c_Add(m_CombineAnd(m_Instruction(Ext0),
```
It will address the regression in `zext_sext_add_icmp_slt_1_no_oneuse`.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 4]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+                                   Value *Op1, IRBuilderBase &Builder) {
+  switch (Table.to_ulong()) {
+    case 0: // 0 0 0 0
+      return Builder.getFalse();
+    case 1: // 0 0 0 1
+      return Builder.CreateNot(Builder.CreateOr(Op0, Op1));
+    case 2: // 0 0 1 0
+      return Builder.CreateAnd(Builder.CreateNot(Op0), Op1);
+    case 3: // 0 0 1 1
+      return Op1;
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2909]:
```suggestion
      return Builder.CreateNot(Op0);
```

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 5]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+    case 4: // 0 1 0 0
+      return Builder.CreateAnd(Op0, Builder.CreateNot(Op1));
+    case 5: // 0 1 0 1
+      return Op0;
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2913]:
```suggestion
      return Builder.CreateNot(Op1);
```

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 6]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
   return new ICmpInst(SwappedPred, Add, ConstantInt::get(Ty, ~C));
 }
 
+static Value *createLogicFromTable(const std::bitset<4> &Table, Value *Op0,
+                                   Value *Op1, IRBuilderBase &Builder) {
+  switch (Table.to_ulong()) {
+    case 0: // 0 0 0 0
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2902]: Please check again the following code and attach alive2 proof. I think you may have gotten the order of bits backward.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 7]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+    case 8: // 1 0 0 0
+      return Builder.CreateAnd(Op0, Op1);
+    case 9: // 1 0 0 1
+      return Builder.CreateNot(Builder.CreateXor(Op0, Op1));
+    case 10: // 1 0 1 0
+      return Builder.CreateNot(Op1);
+    case 11: // 1 0 1 1
+      return Builder.CreateOr(Builder.CreateNot(Op0), Op1);
+    case 12: // 1 1 0 0
+      return Builder.CreateNot(Op1);
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2927]:
```suggestion
      return Op0;
```

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 8]
```diff
@@ -2895,19 +2896,86 @@ Instruction *InstCombinerImpl::foldICmpSubConstant(ICmpInst &Cmp,
...
+    case 6: // 0 1 1 0
+      return Builder.CreateXor(Op0, Op1);
+    case 7: // 0 1 1 1
+      return Builder.CreateNot(Builder.CreateAnd(Op0, Op1));
+    case 8: // 1 0 0 0
+      return Builder.CreateAnd(Op0, Op1);
+    case 9: // 1 0 0 1
+      return Builder.CreateNot(Builder.CreateXor(Op0, Op1));
+    case 10: // 1 0 1 0
+      return Builder.CreateNot(Op1);
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:2923]:
```suggestion
      return Op1;
```

**Review by dtcxzyw — CHANGES_REQUESTED** [review]

**Comment by dtcxzyw** [comment]
Alive2: https://alive2.llvm.org/ce/z/b9NdVW

**Comment by elhewaty** [comment]
@dtcxzyw Thanks, I will update the pull now.
should I make a new clean pull?

**Comment by dtcxzyw** [comment]
> @dtcxzyw Thanks, I will update the pull now. should I make a new clean pull?

I recommend you work on this PR to track the review progress. Don't worry about creating a bunch of commits since they will be squashed before merging.

File: llvm/test/Transforms/InstCombine/icmp-range.ll [hunk 9]
```diff
@@ -879,7 +879,8 @@ define i1 @zext_sext_add_icmp_slt_minus_1_no_oneuse(i1 %a, i1 %b) {
 ; CHECK-NEXT:    [[SEXT_B:%.*]] = sext i1 [[B:%.*]] to i8
 ; CHECK-NEXT:    [[ADD:%.*]] = add nsw i8 [[ZEXT_A]], [[SEXT_B]]
 ; CHECK-NEXT:    call void @use(i8 [[ADD]])
-; CHECK-NEXT:    ret i1 false
+; CHECK-NEXT:    [[R:%.*]] = icmp slt i8 [[ADD]], -1
```
Comment (dtcxzyw) [inline llvm/test/Transforms/InstCombine/icmp-range.ll:882]: Regressions here. I think we should remove the `m_OneUse` constraint and pass `Add->hasOneUse()` to `createLogicFromTable`.

Comment (elhewaty) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]: @dtcxzyw can you explain further?

Comment (dtcxzyw) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]:
```
static Value *createLogicFromTable(const std::bitset<4> &Table, Value *Op0,
                                   Value *Op1, IRBuilderBase &Builder, bool HasOneUse) {
  switch (Table.to_ulong()) {
  case 0: // 0 0 0 0
    return Builder.getFalse();
  case 1: // 0 0 0 1
    return HasOneUse ? Builder.CreateNot(Builder.CreateOr(Op0, Op1)) : nullptr;
  case 2: // 0 0 1 0
    return HasOneUse ? Builder.CreateAnd(Builder.CreateNot(Op0), Op1) : nullptr;
  case 3: // 0 0 1 1
    return Builder.CreateNot(Op0);
  case 4: // 0 1 0 0
    return HasOneUse ? Builder.CreateAnd(Op0, Builder.CreateNot(Op1)) : nullptr;
  case 5: // 0 1 0 1
    return Builder.CreateNot(Op1);
  case 6: // 0 1 1 0
    return Builder.CreateXor(Op0, Op1);
  case 7: // 0 1 1 1
    return HasOneUse ? Builder.CreateNot(Builder.CreateAnd(Op0, Op1)) : nullptr;
  case 8: // 1 0 0 0
    return Builder.CreateAnd(Op0, Op1);
  case 9: // 1 0 0 1
    return HasOneUse ? Builder.CreateNot(Builder.CreateXor(Op0, Op1)) : nullptr;
  case 10: // 1 0 1 0
    return Op1;
  case 11: // 1 0 1 1
    return HasOneUse ? Builder.CreateOr(Builder.CreateNot(Op0), Op1) : nullptr;
  case 12: // 1 1 0 0
    return Op0;
  case 13: // 1 1 0 1
    return HasOneUse ? Builder.CreateOr(Op0, Builder.CreateNot(Op1)) : nullptr;
  case 14: // 1 1 1 0
    return Builder.CreateOr(Op0, Op1);
  case 15: // 1 1 1 1
    return Builder.getTrue();
  default:
    llvm_unreachable("Invalid Operation");
  }
  return nullptr;
}
```
```
 if (match(Add, m_Add(
                     m_CombineAnd(m_Instruction(Ext0),
                                  m_OneUse(m_ZExtOrSExt(m_Value(Op0)))),
                     m_CombineAnd(m_Instruction(Ext1),
                                  m_OneUse(m_ZExtOrSExt(m_Value(Op1)))))) &&
```
```
  if (auto *Cond = createLogicFromTable(Table, Op0, Op1, Builder, Add->hasOneUse()))
    return replaceInstUsesWith(Cmp, Cond);
```
Then we can apply these optimizations for adds with multi-use without penalty.

Comment (elhewaty) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]: Do you mean to add an additional bit for the OneUse?

Comment (dtcxzyw) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]: Yes.

Comment (elhewaty) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]:
```
static llvm::BinaryOperator* llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value*, llvm::Value*, const llvm::Twine&, llvm::Instruction*): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt -passes=instcombine -S
 #0 0x0000558a8819fa60 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x2cb2a60)
 #1 0x0000558a8819ce6f llvm::sys::RunSignalHandlers() (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x2cafe6f)
 #2 0x0000558a8819cfc5 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007ff28d842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007ff28d896a7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007ff28d896a7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x00007ff28d896a7c pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x00007ff28d842476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007ff28d8287f3 abort ./stdlib/abort.c:81:7
 #9 0x00007ff28d82871b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x00007ff28d839e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x0000558a87af08a5 (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x26038a5)
#12 0x0000558a87aff874 (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x2612874)
#13 0x0000558a8732cd00 llvm::IRBuilderBase::CreateOr(llvm::Value*, llvm::Value*, llvm::Twine const&) AtomicExpandPass.cpp:0:0
#14 0x0000558a87d35ebb llvm::InstCombinerImpl::foldICmpAddConstant(llvm::ICmpInst&, llvm::BinaryOperator*, llvm::APInt const&) InstCombineCompares.cpp:0:0
#15 0x0000558a87d4c7a8 llvm::InstCombinerImpl::foldICmpBinOpWithConstant(llvm::ICmpInst&, llvm::BinaryOperator*, llvm::APInt const&) InstCombineCompares.cpp:0:0
#16 0x0000558a87d4ca53 llvm::InstCombinerImpl::foldICmpInstWithConstant(llvm::ICmpInst&) InstCombineCompares.cpp:0:0
#17 0x0000558a87d51c88 llvm::InstCombinerImpl::visitICmpInst(llvm::ICmpInst&) InstCombineCompares.cpp:0:0
#18 0x0000558a87cb725c llvm::InstCombinerImpl::run() InstructionCombining.cpp:0:0
#19 0x0000558a87cb891d combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, bool, llvm::LoopInfo*) InstructionCombining.cpp:0:0
#20 0x0000558a87cb98d1 llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x27cc8d1)
#21 0x0000558a883ab0b6 llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#22 0x0000558a87b8a5b1 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x269d5b1)
#23 0x0000558a883a3bc6 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#24 0x0000558a87b892ab llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x269c2ab)
#25 0x0000558a883aad46 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) PassBuilder.cpp:0:0
#26 0x0000558a87b87091 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x269a091)
#27 0x0000558a86b14fb5 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x1627fb5)
#28 0x0000558a86b247b8 main (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x16377b8)
#29 0x00007ff28d829d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#30 0x00007ff28d829e40 call_init ./csu/../csu/libc-start.c:128:20
#31 0x00007ff28d829e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#32 0x0000558a86b077a5 _start (/media/mohamed/Local-Disk/open-source/New-LLVM/build/bin/opt+0x161a7a5)
Aborted (core dumped)
```

Comment (dtcxzyw) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]: Could you please update this pull? I have no idea why it crashed.

Comment (nikic) [reply llvm/test/Transforms/InstCombine/icmp-range.ll:882]: Did you maybe drop the isIntOrIntVectorTy(1) checks?

**Review by dtcxzyw — APPROVED** [review]
LGTM. I will test on my machine to reproduce this crash.

**Comment by elhewaty** [comment]
@dtcxzyw Are you one of the reviewers or code owners?
should I mention you for any future review?

**Comment by dtcxzyw** [comment]
> @dtcxzyw Are you one of the reviewers or code owners? should I mention you for any future review?

No. But I am willing to review PRs related to the middle-end/RISC-V backend :)

File: llvm/test/Transforms/InstCombine/icmp-range.ll (hunk 9 above)
Comment (dtcxzyw) [reply llvm/test/Transforms/InstCombine/icmp-range.ll]: The latest version works fine on my machine.

**Comment by dtcxzyw** [comment]
Should we add some multi-use/vector tests?

**Review by nikic — COMMENTED** [review]
This looks basically good to me. Only one suggestion to relax the one-use checks.

Can you please squash the changes such that all the test additions are in the first commit and the implementation (and test diffs) are in the second one?

**Comment by nikic** [comment]
I'd suggest to also add a (negative) test where the sext/zext is from something other than i1. (Unless it already exists and I missed it...)

**Comment by elhewaty** [comment]
@nickc Please if there are any further modifications will do them, but not in the next few weeks, as I am busy with other things. please keep the issue assigned to me and I will complete the work.

**Review by nikic — APPROVED** [review]
LGTM
