### PR TITLE
[Clang][Sema] Fix type of enumerators in incomplete enumerations

### LINKED ISSUE #84712: [clang] Invalid rejection of enum arithmetic
The following valid translation unit

```cpp
enum e1 {
	value = 0
};

enum e2 {
	a = 0,
	b = e1::value,
	c = a + b
};
```

is incorrectly rejected by clang when compiled in C++26 mode with

```console
<source>:8:8: error: invalid arithmetic between different enumeration types ('e2' and 'e1')
    8 |         c = a + b
      |             ~ ^ ~
1 error generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/v4sG9YqMb

In earlier versions of C++, it incorrectly warns saying the conversion is deprecated.

This was accepted in clang 18.1.0, but is failing on current trunk (15e9478187d594016c2c355d8688be2e0a9b554e).

### PR DESCRIPTION
**Pull request by martinkupa**
Enumerators dont have the type of their enumeration before the closing brace. In these cases Expr::getEnumCoercedType() incorrectly returned the enumeration type.

Introduced in PR #81418
Fixes #84712

### CODE REVIEW

**Comment by Kupa-Martin** [comment]
@erichkeane I cant add the previous reviewers myself, could you do it for me please?

File: clang/lib/AST/Expr.cpp [hunk 1]
```diff
@@ -264,10 +264,13 @@ namespace {
...
+  if (isa<EnumType>(this->getType())) {
     return this->getType();
-  else if (const auto *ECD = this->getEnumConstantDecl())
-    return Ctx.getTypeDeclType(cast<EnumDecl>(ECD->getDeclContext()));
+  } else if (const auto *ECD = this->getEnumConstantDecl()) {
+    const auto *ED = cast<EnumDecl>(ECD->getDeclContext());
+    if (ED->isCompleteDefinition())
+      return Ctx.getTypeDeclType(ED);
+  }
   return this->getType();
```
Comment (Sirraide) [inline clang/lib/AST/Expr.cpp:274]: Erm, is there a good reason why we’re doing `this->` here? I can see it was doing that before too, but it just seems really unnecessary to me...

**Comment by Sirraide** [comment]
Also, this probably needs a release note.

**Comment by Kupa-Martin** [comment]
> Also, this probably needs a release note.

If you want I'll add one but this bug has been on main no longer than a week, so I didnt think it would be necessary.

File: clang/lib/AST/Expr.cpp (hunk 1 above)
Comment (Kupa-Martin) [reply clang/lib/AST/Expr.cpp]: Force of habit. I already changed it.

**Comment by Sirraide** [comment]
> > Also, this probably needs a release note.
> 
> If you want I'll add one but this bug has been on main no longer than a week, so I didnt think it would be necessary.

I see. Yeah, I don’t think we really need one if the bug was introduced and fixed in the same version.

**Comment by erichkeane** [comment]
> > > Also, this probably needs a release note.
> > 
> > 
> > If you want I'll add one but this bug has been on main no longer than a week, so I didnt think it would be necessary.
> 
> I see. Yeah, I don’t think we really need one if the bug was introduced and fixed in the same version.

Thats correct, a release note is only necessary in cases where the bug existed in a release.

**Review by shafik — COMMENTED** [review]
Should we also have a C++ test for this fix?

**Comment by Kupa-Martin** [comment]
> Should we also have a C++ test for this fix?

clang/test/Sema/warn-compare-enum-types-mismatch.c should cover both C and C++. Or do you mean some other kind of test?

File: clang/test/Sema/warn-compare-enum-types-mismatch.c [hunk 2]
```diff
@@ -6,7 +6,9 @@ typedef enum EnumA {
 } EnumA;
 
 enum EnumB {
-  B
+  B,
```
Comment (AaronBallman) [inline clang/test/Sema/warn-compare-enum-types-mismatch.c:9]: It might be good to capture some of what I wrote in the review summary as a comment here so it's clear why this is correct in both C and C++.

**Review by AaronBallman — APPROVED** [review]
Hmm, the rules are different between C and C++, but I think we may be okay. In C++:

https://eel.is/c++draft/enum#dcl.enum-5.sentence-6
Following the closing brace of an enum-specifier, each enumerator has the type of its enumeration.

In C23 6.7.3.3p12:
During the processing of each enumeration constant in the enumerator list, the type of the enumeration constant shall be: <long list of things>

p15:
The enumeration member type for an enumerated type without fixed underlying type upon completion is:
— int if all the values of the enumeration are representable as an int; or,
— the enumerated type.140)

Footnote 140) The integer type selected during processing of the enumerator list (before completion) of the enumeration may not be the same as the compatible implementation-defined integer type selected for the completed enumeration.

So I believe:
```
typedef enum EnumA {
  A
} EnumA;

enum EnumB {
  B,
  B1 = 1,
  B2 = A == B1
};
```
is not an enum compare warning in C++ because `B1` doesn't have an enumeration type due to the enumeration not being fully-defined, and is not an enum compare warning in C because `A` has type `int` (due to p15) and `B1` has type `int` (due to p12).

I think we play a bit fast-and-loose with the way we treat enum constants in C in Clang, but that's outside of the scope of this patch. So LGTM aside from some tiny nits!

**Comment by Kupa-Martin** [comment]
> not an enum compare warning in C++ because `B1` doesn't have an enumeration type due to the enumeration not being fully-defined, and is not an enum compare warning in C because `A` has type `int` (due to p15) and `B1` has type `int` (due to p12).

Yes, you are correct.

> I think we play a bit fast-and-loose with the way we treat enum constants in C in Clang, but that's outside of the scope of this patch.

There are enough differences between the C23 and C++ standards to produce different diagnostics. I've made a godbolt [snippet](https://godbolt.org/z/741W1356r) that tries to keep track of the type of different enumerators in C23 and C++; we warn when we shouldnt and we dont warn when we should. In any case, this patch didnt intend to cover C23.

File: clang/lib/AST/Expr.cpp [hunk 3]
```diff
@@ -264,11 +264,14 @@ namespace {
...
-  else if (const auto *ECD = this->getEnumConstantDecl())
-    return Ctx.getTypeDeclType(cast<EnumDecl>(ECD->getDeclContext()));
-  return this->getType();
+  if (isa<EnumType>(getType())) {
+    return getType();
+  } else if (const auto *ECD = getEnumConstantDecl()) {
+    const auto *ED = cast<EnumDecl>(ECD->getDeclContext());
+    if (ED->isCompleteDefinition())
+      return Ctx.getTypeDeclType(ED);
+  }
```
[the remark this answers is not in the document]
Comment (Kupa-Martin) [reply clang/lib/AST/Expr.cpp]: done

File: clang/test/Sema/warn-compare-enum-types-mismatch.c (hunk 2 above)
Comment (Kupa-Martin) [reply clang/test/Sema/warn-compare-enum-types-mismatch.c:12]: done

**Comment by shafik** [comment]
> So I believe:
> 
> ```
> typedef enum EnumA {
>   A
> } EnumA;
> 
> enum EnumB {
>   B,
>   B1 = 1,
>   B2 = A == B1
> };
> ```
> 
> is not an enum compare warning in C++ because `B1` doesn't have an enumeration type due to the enumeration not being fully-defined, and is not an enum compare warning in C because `A` has type `int` (due to p15) and `B1` has type `int` (due to p12).

Right, so do we have a test for C++ that verifies that.

File: clang/test/Sema/warn-compare-enum-types-mismatch.c (hunk 2 above)
Comment (shafik) [reply clang/test/Sema/warn-compare-enum-types-mismatch.c:12]: I think what I was asking, was do we have an equivalent C++ test that verifies in a `.cpp` file that we also do not obtain a diagnostic for this.

**Comment by Kupa-Martin** [comment]
@shafik We dont have a dedicated cpp test for this. I can add one if you want, but clang/test/Sema/warn-compare-enum-types-mismatch.c runs clang both on C and C++ mode, so I didnt think it necessary.

**Comment by shafik** [comment]
> @shafik We dont have a dedicated cpp test for this. I can add one if you want, but clang/test/Sema/warn-compare-enum-types-mismatch.c runs clang both on C and C++ mode, so I didnt think it necessary.

I think we just a bug that demonstrates this issue: https://github.com/llvm/llvm-project/issues/84712

So if this fixes that as well then we should add tests for those cases too.

**Comment by Sirraide** [comment]
Regarding #84712: From what I can tell, the behaviour of cases such as
```c++
enum e1 { a };
enum e2 { b = a };
```
has changed between C++11 and C++14 (at least the wording is different starting with C++14; there may be some other section that states the same for C++11, but I couldn’t find one); specifically, C++11’s [[dcl.enum]p5](https://eel.is/c++draft/enum#dcl.enum-5) states that:
> If the underlying type is not fixed, the type of each enumerator is the type
of its initializing value:
> - If an initializer is specified for an enumerator, the initializing value **has the same type as the expression**
and the constant-expression shall be an integral constant expression (5.19)

Whereas in C++14, that same section reads:
> If the underlying type is not fixed, the type of each enumerator prior
to the closing brace is determined as follows:
> - If an initializer is specified for an enumerator, the constant-expression shall be an integral constant
expression (5.20). **If the expression has unscoped enumeration type, the enumerator has the underlying
type of that enumeration type, otherwise it has the same type as the expression**.

That is, not only is the type of `b` above not `e2` before the closing brace, but it would seem that its type is supposed to be `e1` before C++14, and whatever the underlying type of `e1` is starting with C++14.

**Comment by Kupa-Martin** [comment]
> > @shafik We dont have a dedicated cpp test for this. I can add one if you want, but clang/test/Sema/warn-compare-enum-types-mismatch.c runs clang both on C and C++ mode, so I didnt think it necessary.
> 
> I think we just a bug that demonstrates this issue: #84712
> 
> So if this fixes that as well then we should add tests for those cases too.

I've included a separate test for C++. If there are no more changes, could someone please merge this for me? I dont have commit access.

File: clang/test/Sema/warn-compare-enum-types-mismatch.c [hunk 4]
```diff
@@ -1,12 +1,19 @@
 // RUN: %clang_cc1 -x c -fsyntax-only -verify -Wenum-compare -Wno-unused-comparison %s
 // RUN: %clang_cc1 -x c++ -fsyntax-only -verify -Wenum-compare -Wno-unused-comparison %s
 
+// In C enumerators (i.e enumeration constants) have type int (until C23). In order to support diagnostics such as
```
Comment (AaronBallman) [inline clang/test/Sema/warn-compare-enum-types-mismatch.c:4]: There's trailing whitespace here and it goes over the 80-col limit; can you reformat?

File: clang/test/Sema/warn-compare-enum-types-mismatch.c [hunk 5]
```diff
@@ -1,12 +1,19 @@
...
+
 typedef enum EnumA {
   A
 } EnumA;
 
 enum EnumB {
-  B
+  B,
+  B1 = 1,
+  // In C++ this comparison doesnt warn as enumerators dont have the type of their enumeration before the closing
```
Comment (AaronBallman) [inline clang/test/Sema/warn-compare-enum-types-mismatch.c:14]: Same issue here as above with trailing whitespace and 80 col.

**Review by AaronBallman — APPROVED** [review]
Aside from some formatting issues, this LGTM. Once you push up a fix for the formatting, I'll land. Thank you!

File: clang/test/Sema/warn-compare-enum-types-mismatch.c (hunk 5 above)
Comment (Kupa-Martin) [reply clang/test/Sema/warn-compare-enum-types-mismatch.c]: done

File: clang/test/Sema/warn-compare-enum-types-mismatch.c (hunk 4 above)
Comment (Kupa-Martin) [reply clang/test/Sema/warn-compare-enum-types-mismatch.c]: done
