### PR TITLE
[LifetimeSafety] Suppress suggestion/inference for moved loans

### LINKED ISSUE #193747: [LifetimeSafety] False-positive std::shared_ptr constructed from std::unique_ptr
```cpp
#include <memory>

std::unique_ptr<int> create_up();
std::shared_ptr<int> create_sp() { return create_up(); }
```

Fails with 

```
<source>:4:43: warning: address of stack memory is returned later [-Wlifetime-safety-return-stack-addr]
    4 | std::shared_ptr<int> create_sp() { return create_up(); }
      |                                           ^~~~~~~~~~~
<source>:4:43: note: returned here
    4 | std::shared_ptr<int> create_sp() { return create_up(); }
      |                                           ^~~~~~~~~~~
1 warning generated.
Compiler returned: 0
```

https://godbolt.org/z/xor7fofrE

### PR DESCRIPTION
**Pull request by usx95**
Fixes https://github.com/llvm/llvm-project/issues/193747

### CODE REVIEW

**Comment by usx95** [comment]
* **#193899** <a href="https://app.graphite.com/github/pr/llvm/llvm-project/193899?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/llvm/llvm-project/193899?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: clang/lib/Analysis/LifetimeSafety/Checker.cpp [hunk 1]
```diff
@@ -143,6 +143,10 @@ class LifetimeChecker {
           AnnotationWarningsMap.try_emplace(MD, ReturnEsc->getReturnExpr());
     };
     for (LoanID LID : EscapedLoans) {
+      // Skip annotation suggestion for moved loans, as ownership transfer
+      // obscures the lifetime relationship (e.g., shared_ptr from unique_ptr).
+      if (MovedLoans.getMovedLoans(OEF).lookup(LID))
+        continue;
```
Comment (aeft) [inline clang/lib/Analysis/LifetimeSafety/Checker.cpp]: Since continue sits at the top of the loop, it also bypasses the `NoEscapeAttr` branch inside `CheckParam`, not just the `LifetimeBoundAttr` suggestion. Since NoEscape is a violation check rather than a suggestion, is skipping it for moved
loans intended?

Comment (Xazax-hun) [reply clang/lib/Analysis/LifetimeSafety/Checker.cpp]: Agreed, maybe we want to be more strict about noescape.

File: clang/lib/Analysis/LifetimeSafety/Checker.cpp [hunk 2]
```diff
@@ -143,6 +143,10 @@ class LifetimeChecker {
           AnnotationWarningsMap.try_emplace(MD, ReturnEsc->getReturnExpr());
     };
     for (LoanID LID : EscapedLoans) {
+      // Skip annotation suggestion for moved loans, as ownership transfer
+      // obscures the lifetime relationship (e.g., shared_ptr from unique_ptr).
+      if (MovedLoans.getMovedLoans(OEF).lookup(LID))
```
Comment (Xazax-hun) [inline clang/lib/Analysis/LifetimeSafety/Checker.cpp]: Nit: hoist `MovedLoans.getMovedLoans(OEF)` out of the loop? Probably not a big win, but might help a bit.

File: clang/lib/Analysis/LifetimeSafety/Checker.cpp (hunk 1 above)
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/Checker.cpp]: Makes sense. Done.

File: clang/lib/Analysis/LifetimeSafety/Checker.cpp (hunk 2 above)
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/Checker.cpp]: Done.

**Review by Xazax-hun — APPROVED** [review]

**Comment by usx95** [comment]
Landing this for now (after rebase). Happy to address more comments as a followup.
