### PR TITLE
[VPlan] Add initial loop-invariant code motion transform.

### LINKED ISSUE #107501: [clang] Assertion failed in Vectorize
I compiled this code with -O2 flag and it crashed:

```c
#include <stdint.h>
long a;
struct g {
  uint64_t h
};
int8_t i, j;
void b(int c, int, int d) {
  for (int e = 0; e < c; e++)
    a *= e * d;
}
long f() { return 1; }
int16_t k();
int16_t l(int16_t, uint8_t, struct g, int8_t, int64_t);
int32_t *m();
int64_t n();
int16_t o() {
  struct g p[8][1] = {};
  k(l(0, 0, p[4][1], 0, 0), p);
}
int16_t l(int16_t, uint8_t, struct g q, int8_t, int64_t) {
  int32_t *r;
  m(r, i && f() + (int)q.h + q.h);
}
int16_t safe_sub_func_int16_t_s_s(int16_t si1, int16_t si2)
{
  return (si1 - si2);
}
int32_t *m(int32_t *, int32_t s) {
  for (;; b(s + 3, 0, s + 1))
    if (s >= (j && &safe_sub_func_int16_t_s_s))
      n();
}
```

The crash is: 
```
clang: /root/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:7389: llvm::VectorizationFactor llvm::LoopVectorizationPlanner::computeBestVF(): Assertion `(BestFactor.Width == LegacyVF.Width || planContainsAdditionalSimplifications(getPlanFor(BestFactor.Width), CostCtx, OrigLoop)) && " VPlan cost model and legacy cost model disagreed"' failed.
```
The details can be found here: https://godbolt.org/z/Gc9T5v5Yx

### PR DESCRIPTION
**Pull request by fhahn**
Add initial transform to move out loop-invariant recipes.

This also helps to fix a divergence between legacy and VPlan-based cost model due to legacy using ScalarEvolution::isLoopInvariant in some cases.

Fixes https://github.com/llvm/llvm-project/issues/107501.

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 1]
```diff
@@ -1586,3 +1587,22 @@ void VPlanTransforms::createInterleaveGroups(
...
+  VPRegionBlock *LoopRegion = Plan.getVectorLoopRegion();
+  VPBasicBlock *Preheader =
+      cast<VPBasicBlock>(LoopRegion->getSinglePredecessor());
+  // Hoist any loop invariant recipes from the vector loop region to the
+  // preheader.
+  for (VPBasicBlock *VPBB : VPBlockUtils::blocksOnly<VPBasicBlock>(
+           vp_depth_first_shallow(LoopRegion->getEntry()))) {
+    for (VPRecipeBase &R : make_early_inc_range(*VPBB)) {
+      if (R.mayHaveSideEffects() || R.mayReadFromMemory() || R.isPhi() ||
+          any_of(R.operands(), [](VPValue *Op) {
```
Comment (rengolin) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1601]: Technically an op can still be hoisted if it reads from memory with no side effects, as long as the pointer is constant throughout the loop, which the `nay_of` takes care. It may increase register pressure inside the loop, but only if the liveness of the value is short, and the cost model should take care of the comparison.

What cases are you thinking here?

Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1604]: If the memory is not modified in the loop we could also hoist out reads, but I think at the moment we don't yet have to utilities available to check that on the VPlan level.

Added a TODO to further relax the checks and improve the analysis.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 2]
```diff
@@ -2382,7 +2382,8 @@ void InnerLoopVectorizer::scalarizeInstruction(const Instruction *Instr,
     AC->registerAssumption(II);
 
   // End if-block.
-  bool IfPredicateInstr = RepRecipe->getParent()->getParent()->isReplicator();
+  VPRegionBlock *Parent = RepRecipe->getParent()->getParent();
+  bool IfPredicateInstr = Parent ? Parent->isReplicator() : false;
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2386]: Is this change related to the main LICM routine that this patch adds?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 3]
```diff
@@ -7294,7 +7295,7 @@ static bool planContainsAdditionalSimplifications(VPlan &Plan,
   };
 
   DenseSet<Instruction *> SeenInstrs;
-  auto Iter = vp_depth_first_deep(Plan.getEntry());
+  auto Iter = vp_depth_first_deep(Plan.getVectorLoopRegion()->getEntry());
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:7298]: Seems like an unrelated change?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 4]
```diff
@@ -1587,3 +1588,24 @@ void VPlanTransforms::createInterleaveGroups(
...
+      cast<VPBasicBlock>(LoopRegion->getSinglePredecessor());
+  // Hoist any loop invariant recipes from the vector loop region to the
+  // preheader.
+  for (VPBasicBlock *VPBB : VPBlockUtils::blocksOnly<VPBasicBlock>(
+           vp_depth_first_shallow(LoopRegion->getEntry()))) {
+    for (VPRecipeBase &R : make_early_inc_range(*VPBB)) {
+      // TODO: Relax checks in the future, e.g. we could also hoist reads, if
+      // their memory location is not modified in the vector loop.
+      if (R.mayHaveSideEffects() || R.mayReadFromMemory() || R.isPhi() ||
+          any_of(R.operands(), [](VPValue *Op) {
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1604]: I'd recommend changing this to if `if (all_of(R.operands(), ... Op->isDefinedOutsideVectorRegions())) R.moveBefore(...)`, and having the continue branch for `R.mayHaveSideEffects()` etc.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 5]
```diff
@@ -1587,3 +1588,24 @@ void VPlanTransforms::createInterleaveGroups(
...
 }
+
+void VPlanTransforms::licm(VPlan &Plan) {
+  VPRegionBlock *LoopRegion = Plan.getVectorLoopRegion();
+  VPBasicBlock *Preheader =
+      cast<VPBasicBlock>(LoopRegion->getSinglePredecessor());
+  // Hoist any loop invariant recipes from the vector loop region to the
+  // preheader.
+  for (VPBasicBlock *VPBB : VPBlockUtils::blocksOnly<VPBasicBlock>(
+           vp_depth_first_shallow(LoopRegion->getEntry()))) {
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1599]: Why is this `vp_depth_first_shallow`, and not `vp_depth_first_deep`?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 4 above)
Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1604]: Also, I was thinking: the right condition for LICM is "def dominates all its uses"; do you think this is feasible to check with the current infrastructure?

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1598]: I was commenting purely from the perspective of ease of comprehension of the negative-`any_of`, but it's not a strong preference.

**Review by artagnon — COMMENTED** [review]
LGTM, modulo pending test updates.

**Comment by fhahn** [comment]
> LGTM, modulo pending test updates.

Thanks, all tests should be passing now. Had to add an extra check to disallow hoisting Allocas, similar to https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Scalar/LICM.cpp#L1112

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 6]
```diff
@@ -2378,7 +2378,8 @@ void InnerLoopVectorizer::scalarizeInstruction(const Instruction *Instr,
     AC->registerAssumption(II);
 
   // End if-block.
-  bool IfPredicateInstr = RepRecipe->getParent()->getParent()->isReplicator();
+  VPRegionBlock *Parent = RepRecipe->getParent()->getParent();
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2381]: (strictly speaking, qualifies as `GrandParent` ;-))

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 7]
```diff
@@ -971,6 +971,40 @@ static void simplifyRecipe(VPRecipeBase &R, VPTypeAnalysis &TypeInfo) {
     return R.getVPSingleValue()->replaceAllUsesWith(A);
 }
 
+/// Move loop-invariant recipes out of the vector loop region in \p Plan.
+static void licm(VPlan &Plan) {
+  VPRegionBlock *LoopRegion = Plan.getVectorLoopRegion();
+  VPBasicBlock *Preheader =
+      cast<VPBasicBlock>(LoopRegion->getSinglePredecessor());
+
+  // Return true if-and-only-if we know how to (mechanically) both hoist a given
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:980]: both?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 8]
```diff
@@ -971,6 +971,40 @@ static void simplifyRecipe(VPRecipeBase &R, VPTypeAnalysis &TypeInfo) {
...
+  // recipe out of a loop region.  Does not address legality concerns such as
+  // aliasing or speculation safety.
+  auto CanHoistRecipe = [](VPRecipeBase &R) {
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:983]: CannotHoistRecipe than double negate? Inline?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 9]
```diff
@@ -971,6 +971,40 @@ static void simplifyRecipe(VPRecipeBase &R, VPTypeAnalysis &TypeInfo) {
...
+    // Allocas cannot be hoisted.
+    auto *RepR = dyn_cast<VPReplicateRecipe>(&R);
+    return !RepR || RepR->getOpcode() != Instruction::Alloca;
+  };
+
+  // Hoist any loop invariant recipes from the vector loop region to the
+  // preheader.
+  for (VPBasicBlock *VPBB : VPBlockUtils::blocksOnly<VPBasicBlock>(
+           vp_depth_first_shallow(LoopRegion->getEntry()))) {
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:992]: shallow to exclude going into replicate regions (we also check for side effects), visit only blocks that post-dom the header?
Should be fine also when folding the tail (right?)

**Review by ayalz — APPROVED** [review]
Nice!

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 6 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2381]: Perhaps we should introduce `getParentRegion` or `getRegion`, similar to `Instruction::getFunction`?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 7 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Dropped thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 8 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: adjusted, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 9 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:993]: Yes, I'll add a comment to clarify re shallow traversal.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 6 above)
Comment (ayalz) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2381]: Maybe `getEnclosingRegion()`, to complement and serve `getEnclosingLoopRegion()`?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 10]
```diff
@@ -971,6 +971,41 @@ static void simplifyRecipe(VPRecipeBase &R, VPTypeAnalysis &TypeInfo) {
...
+  VPBasicBlock *Preheader =
+      cast<VPBasicBlock>(LoopRegion->getSinglePredecessor());
+
+  // Return true if we do not know how to (mechanically) hoist a given recipe
+  // out of a loop region. Does not address legality concerns such as aliasing
+  // or speculation safety.
+  auto CannotHoistRecipe = [](VPRecipeBase &R) {
+    // Allocas cannot be hoisted.
+    auto *RepR = dyn_cast<VPReplicateRecipe>(&R);
+    return RepR && RepR->getOpcode() == Instruction::Alloca;
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:986]: nit: match?

**Comment by dyung** [comment]
@fhahn one of our internal tests started hitting an assertion failure that I bisected back to this change. I have put the details in #109510, can you take a look?

**Comment by fhahn** [comment]
Thanks @dyung should be fixed now. The issue was that `licm` would run before expansion of replicate regions. Moved afterwards for now as fix
