### PR TITLE
[Clang] [C23] Fix typeof_unqual for qualified array types

### LINKED ISSUE #92667: typeof_unqual does not remove qualifiers from qualified array types
Clang does not remove qualifiers from qualified array types, i.e. array types with qualified element types with typeof_unqual in some situations. See [GCC bug 112841](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112841) which has the following example:
```cpp
const char* const animals[] = {
"aardvark",
"bluejay",
 "catte",
};
int main (int argc, char* argv[]) {
 const char* animals2_array1[3];
 typeof_unqual(animals) animals2_array;
 animals2_array1[0] = 0;
 animals2_array[0] = 0;
 return 0;
}
```
Clang has `typeof_unqual(animals)` result in a const qualified type which results in the assignment `animals2_array[0] = 0;` failing.

### PR DESCRIPTION
**Pull request by MitalAshok**
Properly remove qualifiers for both the element type and the array type

Fixes #92667

### CODE REVIEW

File: clang/include/clang/AST/Type.h [hunk 1]
```diff
@@ -2092,8 +2096,8 @@ class alignas(TypeAlignment) Type : public ExtQualsTypeCommonBase {
 
     LLVM_PREFERRED_TYPE(TypeBitfields)
     unsigned : NumTypeBits;
-    LLVM_PREFERRED_TYPE(bool)
-    unsigned IsUnqual : 1; // If true: typeof_unqual, else: typeof
+    LLVM_PREFERRED_TYPE(TypeOfKind)
```
Comment (AaronBallman) [inline clang/include/clang/AST/Type.h:2099]: Good drive-by catch! Technically unrelated to this PR, but I think it's fine to leave in.

File: clang/test/Sema/c2x-typeof.c [hunk 2]
```diff
@@ -92,3 +92,35 @@ extern __attribute__((address_space(0))) int type_attr_test_2;          // expec
...
+extern typeof_unqual(arpi) api;
+extern typeof(arpii) arpii;
+extern typeof_unqual(arpii) apii;
+
+extern int _Atomic aAi[2];
+extern int _Atomic aAii[2][2];
+extern typeof(aAi) aAi;
+extern typeof_unqual(aAi) ai;
+extern typeof(aAii) aAii;
+extern typeof_unqual(aAii) aii;
```
Comment (AaronBallman) [inline clang/test/Sema/c2x-typeof.c:126]: <i class='graphite__hidden'>[Re: line 127]<br/><br/></i>

Can you also add a test case like the one from #92667?<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/92767?utm_source=unchanged-line-comment">Graphite</a>.</span>

**Review by AaronBallman — COMMENTED** [review]
The changes generally LG, but there's a merge conflict preventing the PR from going through precommit CI.

**Review by AaronBallman — APPROVED** [review]
LGTM! Precommit CI failure is unrelated to your changes.

File: clang/test/Sema/c2x-typeof.c [hunk 3]
```diff
@@ -92,3 +92,43 @@ extern __attribute__((address_space(0))) int type_attr_test_2;          // expec
...
+
+// Ensure array qualifications are removed
+extern const int aci[2];
+extern const int acii[2][2];
+extern int ai[2];
+extern int aii[2][2];
+extern typeof(aci) aci;
+extern typeof_unqual(aci) ai;
+extern typeof(acii) acii;
+extern typeof_unqual(acii) aii;
```
Comment (AaronBallman) [inline clang/test/Sema/c2x-typeof.c:110]: Curiously, this is different from the results in GCC: https://godbolt.org/z/5rczxdGKn

Based on my understanding of "An array and its element type are always considered to be identically qualified.", I think GCC's behavior is incorrect, but it would be good to file an issue with them to let them know to ensure we agree.

File: clang/test/Sema/c2x-typeof.c [hunk 4]
```diff
@@ -92,3 +92,43 @@ extern __attribute__((address_space(0))) int type_attr_test_2;          // expec
...
+
+extern int *restrict arpi[2];
+extern int *restrict arpii[2][2];
+extern int *api[2];
+extern int *apii[2][2];
+extern typeof(arpi) arpi;
+extern typeof_unqual(arpi) api;
+extern typeof(arpii) arpii;
+extern typeof_unqual(arpii) apii;
```
Comment (AaronBallman) [inline clang/test/Sema/c2x-typeof.c:119]: GCC also disagrees on these `typeof_unqual`s, but I think that behavior is also incorrect for the same reason as above.

File: clang/test/Sema/c2x-typeof.c [hunk 5]
```diff
@@ -92,3 +92,43 @@ extern __attribute__((address_space(0))) int type_attr_test_2;          // expec
...
+
+extern int _Atomic aAi[2];
+extern int _Atomic aAii[2][2];
+extern typeof(aAi) aAi;
+extern typeof_unqual(aAi) ai;
+extern typeof(aAii) aAii;
+extern typeof_unqual(aAii) aii;
```
Comment (AaronBallman) [inline clang/test/Sema/c2x-typeof.c:126]: I think this is a more complicated situation, perhaps. `_Atomic` as a type qualifier (as with `_Atomic type`) is excluded in terms of arrays and elements being identically qualified (see footnote 42, which says "This does not apply to the _Atomic qualifier.") so the array is not atomic to begin with. So `typeof_unqual` would strip the non-existent qualifiers from the array in this case but leave them alone in the element type. However, `_Atomic` as a type specifier (as with `_Atomic(type)`) is an atomic-qualified type and so it would be stripped in that case (see footnote 146 which also reminds us that `_Atomic(type-name)` is an atomic-qualified type).

So I think the behavior of this case is correct but we need another test for `_Atomic(int)`.

File: clang/test/Sema/c2x-typeof.c (hunk 3 above)
Comment (MitalAshok) [reply clang/test/Sema/c2x-typeof.c:110]: Yeah, there's a GCC bug for this already: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112841

File: clang/test/Sema/c2x-typeof.c (hunk 5 above)
Comment (MitalAshok) [reply clang/test/Sema/c2x-typeof.c:126]: I don't think this is the correct behaviour now. `_Atomic(int) x[2][2]` and `int _Atomic y[2][2]` have the same type, and `typeof_unqual(int _Atomic[2][2])` and `typeof_unqual(_Atomic(int)[2][2])` should return the same type unchanged because, as you've said, the array isn't `_Atomic` qualified (and arrays cant be `_Atomic` in C). So I'll probably have to remove `Context::getAtomicUnqualifiedArrayType`  and replace it with `Context.getUnqualifiedArrayType(Can.getAtomicUnqualifiedType())`

Comment (AaronBallman) [reply clang/test/Sema/c2x-typeof.c]: Ah, so yeah, I think I was confused above. Both `typeof(_Atomic(int)[2][2])` and `typeof(_Atomit int[2][2])` would return a two-dimensional array of atomic-qualified ints, and `typeof_unqual` is defined to return the non-atomic, unqualified version of the type that would come out of `typeof`, so that would mean both forms come out of `typeof_unqual` the same.

**Review by AaronBallman — APPROVED** [review]
LGTM thank you!

**Comment by AaronBallman** [comment]
Just making sure that this didn't fall off your radar; it seems like a good fix for us to get into Clang 19 before the branch, if possible.

**Comment by MitalAshok** [comment]
@AaronBallman was there anything else that needed to be done? Just did a merge because ReleaseNotes was edited but this should be fine

**Comment by AaronBallman** [comment]
> @AaronBallman was there anything else that needed to be done? Just did a merge because ReleaseNotes was edited but this should be fine

Nope, this is approved to land.

**Comment by cor3ntin** [comment]
@MitalAshok ping
