### PR TITLE
[DirectX] Match DXC's resource order in DX container

### LINKED ISSUE #130232: [DirectX] Resources in PSV0 need to be in a specific order to match validation
DXC and the DXIL validator expect resources in a DX container to be specifically ordered CBuffers, Samplers, SRVs, and then UAVs. We currently do not match this order, which causes us to fail the validator if cbuffers, SRVs, and UAVs are all present in a shader.

### PR DESCRIPTION
**Pull request by bogner**
DXC and the DXIL validator expect resources in a DX container to be specifically ordered CBuffers, Samplers, SRVs, and then UAVs. Match this behaviour so that we can pass the validator.

Fixes #130232.

### CODE REVIEW

**Review by hekota — APPROVED** [review]
LGTM!

File: llvm/lib/Target/DirectX/DXContainerGlobals.cpp [hunk 1]
```diff
@@ -186,51 +186,71 @@ void DXContainerGlobals::addResourcesForPSV(Module &M, PSVRuntimeInfo &PSV) {
...
+  auto MakeBinding =
+      [](const dxil::ResourceBindingInfo::ResourceBinding &Binding,
+         const dxbc::PSV::ResourceType Type, const dxil::ResourceKind Kind,
+         const dxbc::PSV::ResourceFlags Flags = dxbc::PSV::ResourceFlags()) {
+        dxbc::PSV::v2::ResourceBindInfo BindInfo;
+        BindInfo.Type = Type;
+        BindInfo.LowerBound = Binding.LowerBound;
+        BindInfo.UpperBound = Binding.LowerBound + Binding.Size - 1;
+        BindInfo.Space = Binding.Space;
+        BindInfo.Kind = static_cast<dxbc::PSV::ResourceKind>(Kind);
```
Comment (alsepkow) [inline llvm/lib/Target/DirectX/DXContainerGlobals.cpp:198]: Would this conversion be safer done with a helper function or constructor? I couldn't find the definition for dxbc::PSV::ResourceKind but dxil::ResourceKind was just an enum. Seems like something that we could accidentally break ?

Comment (bogner) [reply llvm/lib/Target/DirectX/DXContainerGlobals.cpp:198]: `dxbc::PSV::ResourceKind` and `dxil::ResourceKind` happen to be the exact same enum. One is defined in [DXContainerConstants](https://github.com/llvm/llvm-project/blob/llvmorg-21-init/llvm/include/llvm/BinaryFormat/DXContainerConstants.def#L168) and the other in [DXILABI](https://github.com/llvm/llvm-project/blob/llvmorg-21-init/llvm/include/llvm/Support/DXILABI.h#L34), but if they didn't match exactly we would have a serious problem.

This means that technically the static cast is safe - but it's definitely a break in abstraction. Arguably we should tie these two enums together in a clearer way, though I'm not sure exactly where that should best happen.

In any case, I think that should be out of scope of this PR - I am just moving this cast after all, not introducing it here.

**Review by alsepkow — APPROVED** [review]
lgtm
