### PR TITLE
[X86][MC][AsmParser] Reject H-byte regs with VEX/EVEX-encoded 8-bit RR (NDD)

### LINKED ISSUE #158585: [MC][x86-64] Clang silently mis-assembles instructions with high-byte registers and `EVEX/VEX` prefixes in release mode and crashes with assertion enabled
# Description
When using Clang's integrated assembler (LLVM-MC), an interesting issue arises when assembling an instruction that both requires an `EVEX or VEX prefix` for encoding and uses a high-byte register (`ah`, `ch`, `dh`, or `bh`). The fundamental incompatibility between these two encoding requirements leads to a silent misassembling bug in the release mode of Clang.

This results in a dangerous discrepancy between different build modes:

+ In `debug/assertion builds`: The assembler's internal checks correctly identify the invalid instruction. This leads to a crash with an informative error message: "LLVM ERROR: Cannot encode high byte register in VEX/EVEX-prefixed instruction." This behavior, although it causes a crash, is useful for development as it clearly signals a fatal error.

+ In `release builds`: The internal checks are disabled. The assembler silently proceeds with the invalid instruction, resulting in a **silent mis-assembly.** This behavior is problematic and dangerous as it produces a defective executable without any warning or error. The resulting binary's behavior is unpredictable, potentially leading to security vulnerabilities or silent data corruption.

# Impact and Scope
+ This bug is not limited to a single instruction but affects a broad range of opcodes. Any instruction that the assembler attempts to encode with an EVEX/VEX prefix will exhibit this issue if a high-byte register is used. This includes:

+ Instructions that natively use EVEX/VEX: The entire `ccmp*` and `ctest*` family of instructions from `AVX-512` are directly affected.

+ Standard instructions that can be implicitly encoded with EVEX/VEX: Many traditional opcodes (add, sub, and, or, etc.) can be affected when the assembler chooses to use these prefixes for specific operand combinations or modern CPU features.

+ The list of potentially affected opcodes is extensive, including but not limited to:

> adc, add, and
> 
> All ccmp* and ctest* instructions
> 
> dec, inc, neg, not
> 
> or, sbb, shl, shr
> 
> All setzu* instructions
> 
> sub, xor

# Expected Behavior
An assembler should always be robust and predictable. The correct behavior is to consistently fail with an explicit error message when given an impossible instruction, regardless of the build mode. This is demonstrated by GAS binutils, which rejects the instruction with the clear error: "Error: can't encode register 'ah' in an instruction requiring EVEX prefix." The silent mis-assembly in release mode is an unacceptable form of Undefined Behavior.

# Ways to Reproduce
Godbolt Link: https://godbolt.org/z/jhP3o4v8q

# Observation
+ `Clang 17.0.1` is the latest version that does not have that problem.
+ The behaviour of `trunk binutils GAS` is correct.

### PR DESCRIPTION
**Pull request by woruyu**
### Summary
This PR resolves https://github.com/llvm/llvm-project/issues/158585.

### CODE REVIEW

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 1]
```diff
@@ -4044,6 +4044,24 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
     }
   }
 
+  unsigned Enc = TSFlags & X86II::EncodingMask;
+  if (Enc == X86II::VEX || Enc == X86II::EVEX || Enc == X86II::XOP) {
```
Comment (phoebewang) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4048]: Do you have VEX/XOP example? I assume only EVEX and REX2 have this problem.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 2]
```diff
@@ -4044,6 +4044,24 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
...
+    unsigned NumOps = Inst.getNumOperands();
+    for (unsigned i = 0; i != NumOps; ++i) {
+      const MCOperand &MO = Inst.getOperand(i);
+      if (!MO.isReg())
+        continue;
+      MCRegister Reg = MO.getReg();
+      if (Reg == X86::AH || Reg == X86::BH || Reg == X86::CH ||
+          Reg == X86::DH) {
+        StringRef RegName = X86IntelInstPrinter::getRegisterName(Reg);
```
Comment (KanRobert) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4057]: Could you share the code w/ the check above?

Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4057]:
```
// Disallow AH/BH/CH/DH with VEX/EVEX/XOP encodings.
unsigned Enc = TSFlags & X86II::EncodingMask;
if (Enc == X86II::VEX || Enc == X86II::EVEX || Enc == X86II::XOP) {
  for (unsigned i = 0, e = Inst.getNumOperands(); i != e; ++i) {
    const MCOperand &MO = Inst.getOperand(i);
    if (!MO.isReg()) continue;
    MCRegister Reg = MO.getReg();
    if (Reg == X86::AH || Reg == X86::BH || Reg == X86::CH || Reg == X86::DH) {
      StringRef RegName = X86IntelInstPrinter::getRegisterName(Reg);
      return Error(Ops[0]->getStartLoc(),
        "can't encode '" + RegName + "' in a VEX/EVEX-prefixed instruction");
    }
  }
}
```

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 1 above)
Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4048]: Thanks for the question. I don’t have a realistic VEX/XOP reproducer here. The concrete failure I'm fixing is EVEX (e.g. NDD/NF 8-bit RR/MR forms) selecting for cases like `add ah, ah, ah`.I’ve narrowed the parser diagnostic to EVEX.If/when REX2 becomes exposed via TSFlags, we can add it similarly.

Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Here is a REX2 example: https://godbolt.org/z/xzYxrGrPn. You may check `ForcedOpcodePrefix == OpcodePrefix_REX2` for it.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 3]
```diff
@@ -4031,16 +4034,23 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
...
-                   "REX prefix");
+                   "can't encode '" + RegName +
+                       "' in an instruction requiring REX prefix");
+    }
+
+    if ((UsesEvex || UsesRex2) && HReg) {
+      StringRef RegName = X86IntelInstPrinter::getRegisterName(HReg);
+      return Error(Ops[0]->getStartLoc(),
+                   "can't encode '" + RegName.str() +
+                       "' in an instruction requiring EVEX/REX2 prefix");
```
Comment (phoebewang) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4053]: This can be combine to:
```
if (HReg) {
  if (UsesRex) ...
```

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 4]
```diff
@@ -4031,16 +4034,23 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
       MCRegister Reg = MO.getReg();
       if (Reg == X86::AH || Reg == X86::BH || Reg == X86::CH || Reg == X86::DH)
         HReg = Reg;
-      if (X86II::isX86_64NonExtLowByteReg(Reg) ||
-          X86II::isX86_64ExtendedReg(Reg))
+      if (Enc == 0 && (X86II::isX86_64NonExtLowByteReg(Reg) ||
```
Comment (phoebewang) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4037]: `Enc == 0` is not needed.

Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4037]: Done! removed

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 5]
```diff
@@ -4031,16 +4034,23 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
...
+                       X86II::isX86_64ExtendedReg(Reg)))
         UsesRex = true;
     }
 
-    if (UsesRex && HReg) {
+    if (Enc == 0 && UsesRex && HReg) {
```
[the remark this answers is not in the document]
Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4042]: Done! removed

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 3 above)
Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4053]: Done!

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4042]: But if you delete all of Enc == 0 check, `if (Enc == X86II::EVEX || ForcedOpcodePrefix == OpcodePrefix_REX2)` branch must be before `if (UsesRex)`, which means code sequence will affect robustness, for example, `ccmpae {dfv=of,cf} byte ptr [r8 + 4*rax + 291], ah`, UsesRex is true and  HReg is true and Enc == X86II::EVEX is true, wich should report `can't encode 'ah' in an instruction requiring REX prefix`.

**Review by phoebewang — APPROVED** [review]
LGTM.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 6]
```diff
@@ -4020,7 +4020,10 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
 
   // Check that we aren't mixing AH/BH/CH/DH with REX prefix. We only need to
   // check this with the legacy encoding, VEX/EVEX/XOP don't use REX.
-  if ((TSFlags & X86II::EncodingMask) == 0) {
+  const unsigned Enc = TSFlags & X86II::EncodingMask;
+  const bool UsesEvex = (Enc == X86II::EVEX);
+  const bool UsesRex2 = (ForcedOpcodePrefix == OpcodePrefix_REX2);
+  if (Enc == 0 || UsesEvex || UsesRex2) {
```
[the remark this answers is not in the document]
Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: A new encoding would have its rules. We cannot forsee if it supports AH or not.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 7]
```diff
@@ -4018,9 +4018,14 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
...
+  // High 8-bit regs (AH/BH/CH/DH) are incompatible with encodings that imply
+  // extended prefixes:
+  //  * Legacy path that would emit a REX (e.g. uses r8..r15 or sil/dil/bpl/spl)
+  //  * EVEX
+  //  * REX2
+  // VEX/XOP don't use REX; they are excluded from the legacy check.
+  const unsigned Enc = TSFlags & X86II::EncodingMask;
+  if (Enc != X86II::VEX && Enc != X86II::XOP) {
     MCRegister HReg;
     bool UsesRex = TSFlags & X86II::REX_W;
```
Comment (KanRobert) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4030]: This seems an incomplete fix. In addition to `REX_W`,  we may use REX prefix when other bit is set, e.g. REX_R/X/B.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 8]
```diff
@@ -4036,11 +4041,19 @@ bool X86AsmParser::validateInstruction(MCInst &Inst, const OperandVector &Ops) {
         UsesRex = true;
     }
 
-    if (UsesRex && HReg) {
-      StringRef RegName = X86IntelInstPrinter::getRegisterName(HReg);
-      return Error(Ops[0]->getStartLoc(),
-                   "can't encode '" + RegName + "' in an instruction requiring "
-                   "REX prefix");
+    if (HReg) {
+      if (Enc == X86II::EVEX || ForcedOpcodePrefix == OpcodePrefix_REX2) {
```
[the remark this answers is not in the document]
Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4045]: https://godbolt.org/z/EM87o65Ws

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 7 above)
Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4030]: I don't think we can specify REX_R/X/B in assemble.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (woruyu) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4045]: Done! add `{rex} add ah, al` for testcase.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 7 above)
Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4030]: Yes, I mean we don't need extra change here.

**Comment by phoebewang** [comment]
The failures look unrelated. Please merge main and try again.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 7 above)
Comment (KanRobert) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:4030]: Okay. I missed the line 4041

**Review by KanRobert — APPROVED** [review]
LGTM in general
