### PR TITLE
[mlir][SCF] Do not peel already peeled loops

### LINKED ISSUE #71469: [mlir][linalg] Peeling can't determine when scalable-tiled loops shouldn't be peeled
I think there is a gap in the analysis that determines if a loop needs peeling or not.

Let's say we have the following loop, tiled for scalable vectorization (see %0 and %1):

```
#map = affine_map<(d0)[s0, s1] -> (-d0 + s1, s0)>
module {
  func.func @dot_dispatch_0_matmul_DxDxD_f32(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>, %arg2: tensor<?x?xf32>) -> tensor<?x?xf32> {
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %cst = arith.constant 0.000000e+00 : f32
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c0 : tensor<?x?xf32>
    %dim_0 = tensor.dim %arg1, %c1 : tensor<?x?xf32>
    %dim_1 = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    %0 = vector.vscale
    %1 = arith.muli %0, %c32 : index
    %2 = scf.for %arg3 = %c0 to %dim step %c1 iter_args(%arg4 = %arg0) -> (tensor<?x?xf32>) {
      %3 = scf.for %arg5 = %c0 to %dim_0 step %1 iter_args(%arg6 = %arg4) -> (tensor<?x?xf32>) {
        %4 = affine.min #map(%arg5)[%1, %dim_0]
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %4] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %4] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %5 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %6 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %5) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %4] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %4] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %7 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %7 into %arg8[0, 0] [1, %4] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %6 into %arg6[%arg3, %arg5] [1, %4] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      scf.yield %3 : tensor<?x?xf32>
    }
    return %2 : tensor<?x?xf32>
  }
}
```
We then apply peeling with `--scf-for-loop-peeling` and we get the following output, which looks good to me:

```
#map = affine_map<()[s0, s1] -> (s0 - s0 mod s1)>
#map1 = affine_map<(d0)[s0] -> (-d0 + s0)>
module {
  func.func @dot_dispatch_0_matmul_DxDxD_f32(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>, %arg2: tensor<?x?xf32>) -> tensor<?x?xf32> {
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %cst = arith.constant 0.000000e+00 : f32
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c0 : tensor<?x?xf32>
    %dim_0 = tensor.dim %arg1, %c1 : tensor<?x?xf32>
    %dim_1 = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    %0 = vector.vscale
    %1 = arith.muli %0, %c32 : index
    %2 = scf.for %arg3 = %c0 to %dim step %c1 iter_args(%arg4 = %arg0) -> (tensor<?x?xf32>) {
      %3 = affine.apply #map()[%dim_0, %1]
      %4 = scf.for %arg5 = %c0 to %3 step %1 iter_args(%arg6 = %arg4) -> (tensor<?x?xf32>) {
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %1] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %6 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %7 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %6) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %8 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %8 into %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %7 into %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      %5 = scf.for %arg5 = %3 to %dim_0 step %1 iter_args(%arg6 = %4) -> (tensor<?x?xf32>) {
        %6 = affine.apply #map1(%arg5)[%dim_0]
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %6] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %6] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %7 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %8 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %7) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %6] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %6] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %9 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %9 into %arg8[0, 0] [1, %6] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %8 into %arg6[%arg3, %arg5] [1, %6] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      scf.yield %5 : tensor<?x?xf32>
    }
    return %2 : tensor<?x?xf32>
  }
}
```

However, if we take the output after peeling above and remove the partial iteration:

```
#map = affine_map<()[s0, s1] -> (s0 - s0 mod s1)>
#map1 = affine_map<(d0)[s0] -> (-d0 + s0)>
module {
  func.func @dot_dispatch_0_matmul_DxDxD_f32(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>, %arg2: tensor<?x?xf32>) -> tensor<?x?xf32> {
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %cst = arith.constant 0.000000e+00 : f32
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c0 : tensor<?x?xf32>
    %dim_0 = tensor.dim %arg1, %c1 : tensor<?x?xf32>
    %dim_1 = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    %0 = vector.vscale
    %1 = arith.muli %0, %c32 : index
    %2 = scf.for %arg3 = %c0 to %dim step %c1 iter_args(%arg4 = %arg0) -> (tensor<?x?xf32>) {
      %3 = affine.apply #map()[%dim_0, %1]
      %4 = scf.for %arg5 = %c0 to %3 step %1 iter_args(%arg6 = %arg4) -> (tensor<?x?xf32>) {
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %1] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %6 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %7 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %6) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %8 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %8 into %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %7 into %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      scf.yield %4 : tensor<?x?xf32>
    }
    return %2 : tensor<?x?xf32>
  }
}
```

And apply peeling again, the loop is peeled again, which is wrong:

```
#map = affine_map<()[s0, s1] -> (s0 - s0 mod s1)>
#map1 = affine_map<()[s0, s1] -> (s1 - s1 mod s0 - (s1 - s1 mod s0) mod s0)>
module {
  func.func @dot_dispatch_0_matmul_DxDxD_f32(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>, %arg2: tensor<?x?xf32>) -> tensor<?x?xf32> {
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %cst = arith.constant 0.000000e+00 : f32
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c0 : tensor<?x?xf32>
    %dim_0 = tensor.dim %arg1, %c1 : tensor<?x?xf32>
    %dim_1 = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    %0 = vector.vscale
    %1 = arith.muli %0, %c32 : index
    %2 = scf.for %arg3 = %c0 to %dim step %c1 iter_args(%arg4 = %arg0) -> (tensor<?x?xf32>) {
      %3 = affine.apply #map()[%dim_0, %1]
      %4 = affine.apply #map1()[%1, %dim_0]
      %5 = scf.for %arg5 = %c0 to %4 step %1 iter_args(%arg6 = %arg4) -> (tensor<?x?xf32>) {
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %1] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %7 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %8 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %7) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %9 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %9 into %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %8 into %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      %6 = scf.for %arg5 = %4 to %3 step %1 iter_args(%arg6 = %5) -> (tensor<?x?xf32>) {
        %extracted_slice = tensor.extract_slice %arg1[%arg3, 0] [1, %dim_1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %extracted_slice_2 = tensor.extract_slice %arg2[0, %arg5] [%dim_1, %1] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
        %extracted_slice_3 = tensor.extract_slice %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
        %7 = linalg.fill ins(%cst : f32) outs(%extracted_slice_3 : tensor<1x?xf32>) -> tensor<1x?xf32>
        %8 = scf.for %arg7 = %c0 to %dim_1 step %c1 iter_args(%arg8 = %7) -> (tensor<1x?xf32>) {
          %extracted_slice_4 = tensor.extract_slice %extracted_slice[0, %arg7] [1, 1] [1, 1] : tensor<1x?xf32> to tensor<1x1xf32>
          %extracted_slice_5 = tensor.extract_slice %extracted_slice_2[%arg7, 0] [1, %1] [1, 1] : tensor<?x?xf32> to tensor<1x?xf32>
          %extracted_slice_6 = tensor.extract_slice %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
          %9 = linalg.matmul ins(%extracted_slice_4, %extracted_slice_5 : tensor<1x1xf32>, tensor<1x?xf32>) outs(%extracted_slice_6 : tensor<1x?xf32>) -> tensor<1x?xf32>
          %inserted_slice_7 = tensor.insert_slice %9 into %arg8[0, 0] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<1x?xf32>
          scf.yield %inserted_slice_7 : tensor<1x?xf32>
        }
        %inserted_slice = tensor.insert_slice %8 into %arg6[%arg3, %arg5] [1, %1] [1, 1] : tensor<1x?xf32> into tensor<?x?xf32>
        scf.yield %inserted_slice : tensor<?x?xf32>
      }
      scf.yield %6 : tensor<?x?xf32>
    }
    return %2 : tensor<?x?xf32>
  }
}
```

Peeling should be able to determine that the loop will compute a number of iterations multiple of `%1`, which also happens to be the step, and don't peel the loop again:
```
      #map = affine_map<()[s0, s1] -> (s0 - s0 mod s1)>

      %3 = affine.apply #map()[%dim_0, %1]
      %4 = scf.for %arg5 = %c0 to %3 step %1 iter_args(%arg6 = %arg4) -> (tensor<?x?xf32>) {
```

This issue shows up in IREE, where we peel the same loop multiple times.

### PR DESCRIPTION
**Pull request by matthias-springer**
Loop peeling is not beneficial if the step size already divides "ub - lb". There are currently some simple checks to prevent peeling in such cases when lb, ub, step are constants. This commit adds support for IR that is the result of loop peeling in the general case; i.e., lb, ub, step do not necessarily have to be constants.

This change adds a new affine_map simplification rule for semi-affine maps that appear during loop peeling and are guaranteed to evaluate to a constant zero. Affine maps such as:
```
(1) affine_map<()[ub, step] -> ((ub - ub mod step) mod step)
(2) affine_map<()[ub, lb, step] -> ((ub - (ub - lb) mod step - lb) mod step)
(3)                                         ^ may contain additional summands
```
Other affine maps with modulo expressions are not supported by the new simplification rule.

This fixes #71469.

### CODE REVIEW

**Comment by matthias-springer** [comment]
Note: This new simplification rule is based on the tree-based representation of affine maps. I was trying to implement the simplification logic based on the flattened representation (with the hope that more simplifications around modulo expressions could be supported), but I think that is not possible if the RHS of the modulo expression is not a constant.

Please let me know if you know a better way to do this.

File: mlir/lib/IR/AffineExpr.cpp [hunk 1]
```diff
@@ -444,12 +444,88 @@ static AffineExpr symbolicDivide(AffineExpr expr, unsigned symbolPos,
...
+  }
+  return false;
+}
+
+/// Return "true" if `lhs` % `rhs` is guaranteed to evaluate to zero based on
+/// the fact that `lhs` contains another modulo expression that ensures that
+/// `lhs` is divisible by `rhs`. This is a common pattern in the resulting IR
+/// after loop peeling.
+///
+/// Example: lhs = ub - ub % step
```
Comment (Groverkss) [inline mlir/lib/IR/AffineExpr.cpp:487]: Is this supposed to be `ub - lb`?

File: mlir/lib/IR/AffineExpr.cpp [hunk 2]
```diff
@@ -444,12 +444,88 @@ static AffineExpr symbolicDivide(AffineExpr expr, unsigned symbolPos,
...
+///          rhs = step
+///       => (ub - ub % step) % step is guaranteed to evaluate to 0.
```
Comment (Groverkss) [inline mlir/lib/IR/AffineExpr.cpp:489]: `ub - lb`?

File: mlir/lib/IR/AffineExpr.cpp [hunk 3]
```diff
@@ -444,12 +444,88 @@ static AffineExpr symbolicDivide(AffineExpr expr, unsigned symbolPos,
...
+static bool isModOfModSubtraction(AffineExpr lhs, AffineExpr rhs,
```
Comment (Groverkss) [inline mlir/lib/IR/AffineExpr.cpp:490]: This looks very similar to computing a bound over lhs. Do you think we can improve https://github.com/llvm/llvm-project/blob/main/mlir/lib/IR/AffineExpr.cpp#L1441 to do something like this? I think it handles bounds already. Maybe we can teach it to return a symbolic result instead?

File: mlir/lib/IR/AffineExpr.cpp (hunk 1 above)
Comment (matthias-springer) [reply mlir/lib/IR/AffineExpr.cpp:487]: This example is for the frequent case where `lb = 0`. (`scf.for` often have a lb of zero.) This function is not specific to loop peeling, so you can think of `ub` and `step` as just `s0` and `s1`.

File: mlir/lib/IR/AffineExpr.cpp (hunk 2 above)
Comment (matthias-springer) [reply mlir/lib/IR/AffineExpr.cpp:489]: Same as above, think of this as `(s0 - s0 mod s1) mod s1`. This affine expr appears during loop peeling of `scf.for` loops with `lb = 0`.

File: mlir/lib/IR/AffineExpr.cpp (hunk 3 above)
Comment (matthias-springer) [reply mlir/lib/IR/AffineExpr.cpp:490]: That is tricky because we need to be able to handle cases such as:
```
Mod(Add(Add(a, Mul(-1, Mod(Add(a, b), c))), b), c)
```

Because of the nested `Mod` we cannot use the flattened representation to handle `Mul` and `Add`.

File: mlir/lib/IR/AffineExpr.cpp (hunk 1 above)
Comment (Groverkss) [reply mlir/lib/IR/AffineExpr.cpp:487]: I see. Here it makes sense.

File: mlir/lib/IR/AffineExpr.cpp (hunk 2 above)
Comment (Groverkss) [reply mlir/lib/IR/AffineExpr.cpp:489]: Makes sense.

File: mlir/lib/IR/AffineExpr.cpp (hunk 3 above)
Comment (Groverkss) [reply mlir/lib/IR/AffineExpr.cpp:490]: Right, that function also does some non-flattened floordiv/mod handelling as well. I was hoping we could combine both of these functions to get better bounds.

I would appreciate A TODO for merging these functions for now, but that is optional.

**Review by Groverkss — APPROVED** [review]
LGTM

**Comment by dcaballe** [comment]
Thanks! @banach-space is verifying that this works

**Comment by banach-space** [comment]
> Thanks! @banach-space is verifying that this works

I actually haven't been able to trigger "double" peeling in IREE, but have verified this with a small standalone repro with scalable sizes:
```mlir
func.func @matmul(%A: tensor<?x?xf32>, %B: tensor<?x?xf32>, %C: tensor<?x?xf32>) -> tensor<?x?xf32> {
  %out = linalg.matmul ins(%A, %B: tensor<?x?xf32>, tensor<?x?xf32>)
            outs(%C: tensor<?x?xf32>) -> tensor<?x?xf32>
  return %out : tensor<?x?xf32>
}

module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg1: !transform.any_op {transform.readonly}) {
    %matmul_0 = transform.structured.match ops{["linalg.matmul"]} in %arg1 : (!transform.any_op) -> !transform.any_op
    %1, %loop_1, %loop_2, %loop_3 = transform.structured.tile_using_for %matmul_0 [8, [32], 1] : (!transform.any_op)
      -> (!transform.any_op, !transform.op<"scf.for">, !transform.op<"scf.for">,!transform.op<"scf.for">)
    %main_loop, %remainder_loop = transform.loop.peel %loop_2 : (!transform.op<"scf.for">) -> (!transform.op<"scf.for">, !transform.op<"scf.for">)
    // "Double" peeling - fails after this change, which is correct.
    %main_loop_2, %remainder_loop_2 = transform.loop.peel %main_loop : (!transform.op<"scf.for">) -> (!transform.op<"scf.for">, !transform.op<"scf.for">)

    transform.yield
  }
}
```

 Thanks for the fix @matthias-springer !
