### PR TITLE
[Offload] Optimistically accept SM architectures

### LINKED ISSUE #138532: CUDA offload fails to verify devices > SM90
The most likely reason is the line here: https://github.com/llvm/llvm-project/blob/f49ee00ec47f596269639987f5ea8755a358ca16/offload/plugins-nextgen/common/src/Utils/ELF.cpp#L79.

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
We try to clamp these to ones known to work, but we should probably just
optimistically accept these. I'd prefer to update the flag check, but
since NVIDIA refuses to publish their ELF format it's too much effort to
reverse engineer.

Fixes: https://github.com/llvm/llvm-project/issues/138532

### CODE REVIEW

**Review by shiltian — COMMENTED** [review]
I think it is fine but I'd wait for @Artem-B for the final jurisdiction. :-D

File: offload/plugins-nextgen/common/src/Utils/ELF.cpp [hunk 1]
```diff
@@ -75,8 +75,7 @@ checkMachineImpl(const object::ELFObjectFile<ELFT> &ELFObj, uint16_t EMachine) {
   } else if (Header.e_machine == EM_CUDA) {
     if (~Header.e_flags & EF_CUDA_64BIT_ADDRESS)
       return createError("Invalid CUDA addressing mode");
-    if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35 ||
-        (Header.e_flags & EF_CUDA_SM) > EF_CUDA_SM90)
+    if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35)
```
Comment (Artem-B) [inline offload/plugins-nextgen/common/src/Utils/ELF.cpp:78]: What exactly does `checkMachineImpl` check for? That the ELF file is valid in principle? Or that it was created with specific set of parameters?

If it's the former, then the check should be removed altogether -- I can create a perfectly valid GPU ELF for sm_30 or even sm_20 using an older CUDA SDK. The fact that the newer CUDA versions can no longer do that does not make that ELF invalid.

If we do want to check that the ELF is for specific subset of the architectures, then it's up to you what you want to do here. Considering that we can't do much with the NVIDIA's ELF files themselves, I suspect we do not really care which SM it's for, except for, perhaps, making sure that it matches the GPU the compilation is targeting, but that would be checked somewhere else, I assume.

**Review by Artem-B — APPROVED** [review]
LGTM. We're not doing anything interesting with these SM versions, so being permissive here is probably fine.

File: offload/plugins-nextgen/common/src/Utils/ELF.cpp (hunk 1 above)
Comment (jhuber6) [reply offload/plugins-nextgen/common/src/Utils/ELF.cpp:78]: It's supposed to check if we can run it, so we can be optimistic. Kind of just assumed that since sm_35 is fully deprecated we should reject it.

Comment (Artem-B) [reply offload/plugins-nextgen/common/src/Utils/ELF.cpp:78]: > It's supposed to check if we can run it,

Well, then these checks are neither here, nor there.

Even when the checks on SM version succeed, you may not be able to run the executable because the machine has no GPU, has GPU of a wrong kind, does not have the recent enough version of the driver, and possibly other reasons.

The check may also reject perfectly valid ELF that would be runnable on the given machine (old GPU, with old drivers). The remaining check may make sense if we only intend to run the ELF executables created by us, and carrying something that would not be present in the older binaries, but then I'd argue that it's that *something* that we should be checking. GPU arch is not a good proxy for that info.

In the end it probably does not matter -- new GPUs are accepted now, and I doubt anybody cares about sm_30 any more.
