### PR TITLE
[mlir][vector] Fix parser of vector.transfer_read

### LINKED ISSUE #132851: [mlir] TransferReadOp::parse crashes in AffineMap::getMinorIdentityMap with Assertion `dims >= results && "Dimension mismatch"' failed
git version: 59fd2878fce470f02058f43d4b818ed68ce04094

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt  a.mlir`

a.mlir:  
``` 
module {
  func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
    %c3_i32 = arith.constant 3 : i32
    %0 = vector.transfer_read %arg1[%c3_i32, %c3_i32], %c3_i32 : memref<?xindex>, vector<3x4xi32>
    return %0 : vector<3x4xi32>
  }
}

``` 
stack trace:

``` 
mlir-opt: /data/szy/MLIR/llvm-project/mlir/lib/IR/AffineMap.cpp:137: static AffineMap mlir::AffineMap::getMinorIdentityMap(unsigned int, unsigned int, MLIRContext *): Assertion `dims >= results && "Dimension mismatch"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/szy/MLIR/llvm-project/install/bin/mlir-opt /data/szy/MLIR/seed/seed3/tmp.NpmIVbapK0.mlir
1.      MLIR Parser: custom op parser 'builtin.module'
2.      MLIR Parser: custom op parser 'func.func'
3.      MLIR Parser: custom op parser 'vector.transfer_read'
 #0 0x0000560611faadb8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11bddb8)
 #1 0x0000560611fa88be llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11bb8be)
 #2 0x0000560611fab736 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007feede5d5420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007feeddc1200b raise /build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007feeddbf1859 abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007feeddbf1729 get_sysdep_segment_value /build/glibc-LcI20x/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007feeddbf1729 _nl_load_domain /build/glibc-LcI20x/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007feeddc02fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x00005606150644c7 mlir::AffineMap::getMinorIdentityMap(unsigned int, unsigned int, mlir::MLIRContext*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x42774c7)
#10 0x00005606148261ce mlir::vector::getTransferMinorIdentityMap(mlir::ShapedType, mlir::VectorType) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x3a391ce)
#11 0x0000560614840fe1 mlir::vector::TransferReadOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x3a53fe1)
#12 0x00005606181137e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#13 0x000056061811e9a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#14 0x000056061811c85c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#15 0x000056061811aacc (anonymous namespace)::CustomOpAsmParser::parseOptionalRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#16 0x000056061821ce32 mlir::function_interface_impl::parseFunctionOp(mlir::OpAsmParser&, mlir::OperationState&, bool, mlir::StringAttr, llvm::function_ref<mlir::Type (mlir::Builder&, llvm::ArrayRef<mlir::Type>, llvm::ArrayRef<mlir::Type>, mlir::function_interface_impl::VariadicFlag, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)>, mlir::StringAttr, mlir::StringAttr) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x742fe32)
#17 0x000056061262d7fa mlir::func::FuncOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x18407fa)
#18 0x00005606181137e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#19 0x000056061811e9a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#20 0x000056061811c6d5 (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#21 0x00005606150d1b9e mlir::ModuleOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x42e4b9e)
#22 0x00005606181137e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#23 0x00005606181125ad mlir::parseAsmSourceFile(llvm::SourceMgr const&, mlir::Block*, mlir::ParserConfig const&, mlir::AsmParserState*, mlir::AsmParserCodeCompleteContext*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x73255ad)
#24 0x0000560614fb1f0f mlir::parseSourceFile(std::shared_ptr<llvm::SourceMgr> const&, mlir::Block*, mlir::ParserConfig const&, mlir::LocationAttr*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c4f0f)
#25 0x0000560614fb0e8e mlir::parseSourceFileForTool(std::shared_ptr<llvm::SourceMgr> const&, mlir::ParserConfig const&, bool) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c3e8e)
#26 0x0000560614fb067f performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#27 0x0000560614fb03ed llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#28 0x000056061505b275 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x426e275)
#29 0x0000560614faa405 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd405)
#30 0x0000560614faa6af mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd6af)
#31 0x0000560614faa9de mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd9de)
#32 0x0000560611f89337 main (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119c337)
#33 0x00007feeddbf3083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#34 0x0000560611f88e9e _start (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119be9e)
```

### PR DESCRIPTION
**Pull request by douyixuan**
This PR adds a check in the parser to prevent a crash when vector.transfer_read fails to create minor identity permutation. map.
Fixes #132851

a.mlir

```
module {
  func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
    %c3_i32 = arith.constant 3 : i32
    %0 = vector.transfer_read %arg1[%c3_i32, %c3_i32], %c3_i32 : memref<?xindex>, vector<3x4xi32>
    return %0 : vector<3x4xi32>
  }
}
```

### CODE REVIEW

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 1]
```diff
@@ -4260,6 +4264,10 @@ ParseResult TransferReadOp::parse(OpAsmParser &parser, OperationState &result) {
   AffineMap permMap;
   if (!permMapAttr) {
     permMap = getTransferMinorIdentityMap(shapedType, vectorType);
+    if (!permMap) {
+      return parser.emitError(
+          typesLoc, "failed to create minor identity permutation map");
```
Comment (CoTinker) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4269]: I think the error message should be more intuitive, clearly indicating that the source and vector ranks do not match, so the user can fix the invalid operation. Also we should add error for `TransferWriteOp`

Comment (douyixuan) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4269]: Thank you for the suggestion; I’ll take it into consideration.

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 2]
```diff
@@ -164,6 +164,10 @@ AffineMap mlir::vector::getTransferMinorIdentityMap(ShapedType shapedType,
     return AffineMap::get(
         /*numDims=*/0, /*numSymbols=*/0,
         getAffineConstantExpr(0, shapedType.getContext()));
+  if (shapedType.getRank() < vectorType.getRank() - elementVectorRank) {
+    return AffineMap(); // Not enough dimensions in the shaped type to form a
```
Comment (CoTinker) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:168]: The comments couldn't in same line with code.

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 3]
```diff
@@ -4260,6 +4264,11 @@ ParseResult TransferReadOp::parse(OpAsmParser &parser, OperationState &result) {
   AffineMap permMap;
   if (!permMapAttr) {
     permMap = getTransferMinorIdentityMap(shapedType, vectorType);
+    if (!permMap) {
+      return parser.emitError(typesLoc,
+                              "expected the same rank for the vector and the "
```
Comment (CoTinker) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4269]: Actually not same rank, `shapedType.getRank() >= vectorType.getRank() - elementVectorRank`

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp (hunk 2 above)
Comment (banach-space) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp]: Does `elementVectorRank` matter here? If yes, could you write a test to showcase this?

Separately, given that this is effectively checking some basic pre-conditions, could you move it all the way to the top?

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 4]
```diff
@@ -4668,6 +4677,11 @@ ParseResult TransferWriteOp::parse(OpAsmParser &parser,
...
+                              "results of the permutation map");
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp]: This is documenting _why_ `getTransferMinorIdentityMap` has failed without checking any error codes. This error will be out-of-date should `getTransferMinorIdentityMap` start failing for other reasons.

I recommend a more generic error msg, e.g. "failed to create a minor identity map". 

On a related note, it feels that we should make this example fail much earlier:
```mlir
  %0 = vector.transfer_read %arg1[%c3_i32, %c3_i32], %c3_i32 : memref<?xindex>, vector<3x4xi32>
```

So I am also thinking that this would make more sense:
```cpp
    if (!permMapAttr) {
      if (shapedType.getRank() < vectorType.getRank() - elementVectorRank) {
        return parser.emitError(typesLoc,
                                "In the absence of a permutation map, expected (...)");
     }                             
```

First, let's see what's the answer re `elementVectorRank` (see my question in the other thread).

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 5]
```diff
@@ -525,6 +525,15 @@ func.func @test_vector.transfer_read(%arg0: memref<?x?xvector<2x3xf32>>) {
 
 // -----
 
+func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
+  %c3_i32 = arith.constant 3 : i32
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:529]: Let's follow the style that's already used in this file and avoid encoding the type in the variable name. `%c3_i32` -> `%c3`.

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 6]
```diff
@@ -646,6 +655,14 @@ func.func @test_vector.transfer_write(%arg0: memref<?xf32>, %arg1: vector<7xf32>
 
 // -----
 
+func.func @test_vector.transfer_write(%vec_to_write: vector<3x4xi32>, %output_memref: memref<?xindex>) {
+  %c3_idx = arith.constant 3 : index
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:659]: Could this be made symmetric to `@test_vector.transfer_read, i.e. use `i32` instead?

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 7]
```diff
@@ -525,6 +525,15 @@ func.func @test_vector.transfer_read(%arg0: memref<?x?xvector<2x3xf32>>) {
 
 // -----
 
+func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
+  %c3_i32 = arith.constant 3 : i32
+  // expected-error@+1 {{expected the same rank for the vector and the results of the permutation map}}
+  %0 = vector.transfer_read %arg1[%c3_i32, %c3_i32], %c3_i32 : memref<?xindex>, vector<3x4xi32>
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:531]: I actually didn't realise that we allow different source and destination element type. This doesn't feel right. Is it in any way significant for this patch? If not, let's stick to e.g. `i32` and I can investigate mixing different element types separately.

**Review by banach-space — COMMENTED** [review]
Thanks! I've left some suggestions.

File: mlir/test/Dialect/Vector/invalid.mlir (hunk 7 above)
Comment (dcaballe) [reply mlir/test/Dialect/Vector/invalid.mlir]: Hmmm... that's surprising to me as well... Probably not intentional? Should we open an issue to fix this?

**Review by dcaballe — APPROVED** [review]
Thanks for fixing this! LGTM

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp (hunk 3 above)
Comment (douyixuan) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp]: Change to "source rank is less than required for vector rank",  `TransferWriteOp` error message is "result rank is less than required for vector rank"

File: mlir/test/Dialect/Vector/invalid.mlir (hunk 7 above)
Comment (douyixuan) [reply mlir/test/Dialect/Vector/invalid.mlir]: I adjusted it to `%c3` as recommended to maintain consistency. Could we use this conversation as a reference for a new issue?

Comment (banach-space) [reply mlir/test/Dialect/Vector/invalid.mlir]: > Should we open an issue to fix this?

@douyixuan , could you open an issue and assign to me? Thanks!

> I adjusted it to %c3 as recommended to maintain consistency. 

Could you update `@test_vector.transfer_write` as well? Thanks!

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 8]
```diff
@@ -4260,6 +4264,10 @@ ParseResult TransferReadOp::parse(OpAsmParser &parser, OperationState &result) {
   AffineMap permMap;
   if (!permMapAttr) {
     permMap = getTransferMinorIdentityMap(shapedType, vectorType);
+    if (!permMap) {
+      return parser.emitError(
+          typesLoc, "failed to create a minor identity map, source rank is less than required for vector rank");
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4269]: OK, based on your reply `elementVectorRank`, this would make more sense to me (apologies about formatting):

```suggestion
    if (!permMap) {
       int64_t elementVectorRank = 0;
       VectorType elementVectorType = llvm::dyn_cast<VectorType>(shapedType.getElementType());
       if (elementVectorType)
         elementVectorRank += elementVectorType.getRank();
       if (shapedType.getRank() < vectorType.getRank() - elementVectorRank)
         return parser.emitError(
          typesLoc, "expecting a custom permutation_map when source rank is less than required for vector rank");
```

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp (hunk 2 above)
Comment (banach-space) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp]: OK, could you add tests for this in invalid.mlir? Thanks!

Comment (douyixuan) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp]: Actually, the provided MLIR is valid, and the `elementVectorRank` calculation is tested in `test/Dialect/Vector/vector-transfer-to-vector-load-store.mlir`. Additionally, it is verified by the test case related to this issue, where the `elementVectorRank` is `0`.
```
module {
  func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
    %c3_i32 = arith.constant 3 : i32
    %0 = vector.transfer_read %arg1[%c3_i32, %c3_i32], %c3_i32 : memref<?xindex>, vector<3x4xi32>
    return %0 : vector<3x4xi32>
  }
}
```

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp (hunk 8 above)
Comment (douyixuan) [reply mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4269]: Initially, I removed the `elementVectorRank` calculation since the snippet was repetitive. I noticed there might be other instances where an invalid `permMap` is returned from `getPermutationMapAttrName`. Following your suggestion, I added the snippet, which seems more reasonable now.

File: mlir/test/Dialect/Vector/invalid.mlir (hunk 7 above)
Comment (douyixuan) [reply mlir/test/Dialect/Vector/invalid.mlir]: Thanks, I’ve updated @test_vector.transfer_write too. You can check the new issue here: #134268. Apologies, I currently don’t have the necessary write permissions to assign it.

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 9]
```diff
@@ -152,18 +152,22 @@ static bool isSupportedCombiningKind(CombiningKind combiningKind,
...
         getAffineConstantExpr(0, shapedType.getContext()));
+  int64_t elementVectorRank = 0;
+  VectorType elementVectorType =
+      llvm::dyn_cast<VectorType>(shapedType.getElementType());
+  if (elementVectorType)
+    elementVectorRank += elementVectorType.getRank();
+  if (shapedType.getRank() < vectorType.getRank() - elementVectorRank) {
+    // Not enough dimensions in the shaped type to form a minor identity map.
+    return AffineMap();
+  }
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:170]: I think that you can restore it back to the top and also add an `assert` instead of `return AffineMap()`:
```suggestion
  int64_t elementVectorRank = 0;
  VectorType elementVectorType =
      llvm::dyn_cast<VectorType>(shapedType.getElementType());
  if (elementVectorType)
    elementVectorRank += elementVectorType.getRank();
  assert(shapedType.getRank() < vectorType.getRank() - elementVectorRank && "Not enough dimensions in the shaped type to form a minor identity map.")
  }
```

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 10]
```diff
@@ -4260,6 +4264,17 @@ ParseResult TransferReadOp::parse(OpAsmParser &parser, OperationState &result) {
...
+    if (!permMap) {
+      int64_t elementVectorRank = 0;
+      VectorType elementVectorType =
+          llvm::dyn_cast<VectorType>(shapedType.getElementType());
+      if (elementVectorType)
+        elementVectorRank += elementVectorType.getRank();
+      if (shapedType.getRank() < vectorType.getRank() - elementVectorRank)
+        return parser.emitError(typesLoc,
+                                "expected a custom permutation_map when source "
+                                "rank is less than required for vector rank");
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:4276]:
```suggestion
                                "expected a custom permutation_map when rank(source) != rank (destination)";
```

Same comment for the `transfer_write` part. This way these conditions are identical and can later be extracted to a helper function (I can do it in a separate PR).

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 11]
```diff
@@ -525,6 +525,15 @@ func.func @test_vector.transfer_read(%arg0: memref<?x?xvector<2x3xf32>>) {
 
 // -----
 
+func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xi32> {
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:528]: Let's not mix types: `index` -> `i32`. Same comment for `@test_vector.transfer_write`.

**Review by banach-space — COMMENTED** [review]
Thanks for the updates, just a few final nits.

File: mlir/test/Dialect/Vector/invalid.mlir (hunk 11 above)
Comment (douyixuan) [reply mlir/test/Dialect/Vector/invalid.mlir:528]: The test case associated with this issue utilizes `i32` instead of `index`, while the transfer_write test case serves as its inverse. Should I include an additional test case specifically for `i32`?

Comment (banach-space) [reply mlir/test/Dialect/Vector/invalid.mlir:528]: From the point of view of the issue that you are fixing, the underlying element type is not relevant. Hence, this should be totally sufficient:
```
func.func @test_vector.transfer_read(%arg1: memref<?xi32>) -> vector<3x4xi32> {
  %c3 = arith.constant 3 : index
  // expected-error@+1 {{expected a custom permutation_map when rank(source) != rank(destination)}}
  %0 = vector.transfer_read %arg1[%c3, %c3], %c3 : memref<?xi32>, vector<3x4xi32>
  return %0 : vector<3x4xi32>
}
```

> Should I include an additional test case specifically for i32?

One test case per Op (using either `i32` or `index` for all element types) will be sufficient.

Thanks for asking!

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 12]
```diff
@@ -525,6 +525,24 @@ func.func @test_vector.transfer_read(%arg0: memref<?x?xvector<2x3xf32>>) {
...
+}
+
+// -----
+
+func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xindex> {
+  %c3 = arith.constant 3 : index
+  // expected-error@+1 {{expected a custom permutation_map when rank(source) != rank(destination)}}
+  %0 = vector.transfer_read %arg1[%c3, %c3], %c3 : memref<?xindex>, vector<3x4xindex>
+  return %0 : vector<3x4xindex>
+}
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:542]: My comment for these tests has not been addressed yet (re mixing types), hence commenting through a "suggestion" (to avoid confusion):
```suggestion
func.func @test_vector.transfer_read(%arg1: memref<?xindex>) -> vector<3x4xindex> {
  %c3 = arith.constant 3 : index
  // expected-error@+1 {{expected a custom permutation_map when rank(source) != rank(destination)}}
  %0 = vector.transfer_read %arg1[%c3, %c3], %c3 : memref<?xindex>, vector<3x4xindex>
  return %0 : vector<3x4xindex>
}
```

File: mlir/test/Dialect/Vector/invalid.mlir [hunk 13]
```diff
@@ -646,6 +664,22 @@ func.func @test_vector.transfer_write(%arg0: memref<?xf32>, %arg1: vector<7xf32>
...
+  vector.transfer_write %vec_to_write, %output_memref[%c3, %c3] : vector<3x4xi32>, memref<?xindex>
+}
+
+// -----
+
+func.func @test_vector.transfer_write(%vec_to_write: vector<3x4xindex>, %output_memref: memref<?xindex>) {
+  %c3 = arith.constant 3 : index
+  // expected-error@+1 {{expected a custom permutation_map when rank(source) != rank(destination)}}
+  vector.transfer_write %vec_to_write, %output_memref[%c3, %c3] : vector<3x4xindex>, memref<?xindex>
+}
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/invalid.mlir:679]: My comment for these tests has not been addressed yet (re mixing types), hence commenting through a "suggestion" (to avoid confusion):
```suggestion
func.func @test_vector.transfer_write(%vec_to_write: vector<3x4xindex>, %output_memref: memref<?xindex>) {
  %c3 = arith.constant 3 : index
  // expected-error@+1 {{expected a custom permutation_map when rank(source) != rank(destination)}}
  vector.transfer_write %vec_to_write, %output_memref[%c3, %c3] : vector<3x4xindex>, memref<?xindex>
}
```

File: mlir/test/Dialect/Vector/invalid.mlir (hunk 11 above)
Comment (banach-space) [reply mlir/test/Dialect/Vector/invalid.mlir:528]: I don't believe this has been resolved, so I posted a new comment with a suggestion to make my expectations a bit clearer. Thanks!

File: mlir/lib/Dialect/Vector/IR/VectorOps.cpp [hunk 14]
```diff
@@ -151,13 +151,18 @@ static bool isSupportedCombiningKind(CombiningKind combiningKind,
   return false;
 }
 
-AffineMap mlir::vector::getTransferMinorIdentityMap(ShapedType shapedType,
-                                                    VectorType vectorType) {
-  int64_t elementVectorRank = 0;
+static unsigned getRealVectorRank(ShapedType shapedType,
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/IR/VectorOps.cpp:154]: Please document this method. In particular, what's "real vector rank" in this context? Thanks!

**Review by banach-space — COMMENTED** [review]
The current implementation is very clean, well done! I've left a couple of final comments, but these are very minor.

Your contribution is much appreciated, thank you 🙏🏻

**Review by CoTinker — APPROVED** [review]
LGTM, thanks. And please wait @banach-space to check finally.

**Comment by douyixuan** [comment]
> LGTM, thanks. And please wait @banach-space to check finally.

@banach-space Could you please help check this issue again?

**Review by banach-space — APPROVED** [review]
LGTM, thanks for the fix and for working on this, that's much appreciated!

As a side note, given that the description of  `getRealVectorRank` is much longer then the implementation, we should look into simplifying it. I am happy to look into this separately.

Do you have commit access?

**Comment by douyixuan** [comment]
> LGTM, thanks for the fix and for working on this, that's much appreciated!
> 
> 
> 
> As a side note, given that the description of  `getRealVectorRank` is much longer then the implementation, we should look into simplifying it. I am happy to look into this separately.
> 
> 
> 
> Do you have commit access?

No, I don't. Apologize for the long comments.

**Comment by banach-space** [comment]
> Apologize for the long comments.

No need to - this is incredibly fiddly and hard to document properly. In fact, I owe you an apology — I initially thought we could simplify it, but after trying myself, I realized it’s nearly impossible.

> I am happy to look into this separately.

Done - please take a look: https://github.com/llvm/llvm-project/pull/137144
