### PR TITLE
[clang] Restrict the use of scalar types in vector builtins

### LINKED ISSUE #84047: Unexpected codegen for __builtin_elementwise_bitreverse on unsigned char and short
Given the following: https://godbolt.org/z/M1hEqs9q5

```cpp
unsigned char f(unsigned char a) {
  return __builtin_elementwise_bitreverse(a);
}

unsigned short f(unsigned short a) {
  return __builtin_elementwise_bitreverse(a);
}

signed char f3(signed char a) {
  return __builtin_elementwise_bitreverse(a);
}

signed short f3(signed short a) {
  return __builtin_elementwise_bitreverse(a);
}
```

for the `unsigned char` and `unsigned short` cases it automatically returns `0` w/ any level of optimization e.g.

```llvm
define dso_local noundef zeroext i8 @f(unsigned char)(i8 noundef zeroext %a) local_unnamed_addr {
entry:
  tail call void @llvm.dbg.value(metadata i8 %a, metadata !16, metadata !DIExpression())
  ret i8 0
}
```

Based on the documentation: https://clang.llvm.org/docs/LanguageExtensions.html

This is not expected behavior.

### PR DESCRIPTION
**Pull request by frasercrmck**
This commit restricts the use of scalar types in vector math builtins, particularly the `__builtin_elementwise_*` builtins.

Previously, small scalar integer types would be promoted to `int`, as per the usual conversions. This would silently do the wrong thing for certain operations, such as `add_sat`, `popcount`, `bitreverse`, and others. Similarly, since unsigned integer types were promoted to `int`, something like `add_sat(unsigned char, unsigned char)` would perform a *signed* operation.

With this patch, promotable scalar integer types are not promoted to int, and are kept intact. If any of the types differ in the binary and ternary builtins, an error is issued. Similarly an error is issued if builtins are supplied integer types of different signs. Mixing enums of different types in binary/ternary builtins now consistently raises an error in all language modes.

This brings the behaviour surrounding scalar types more in line with that of vector types. No change is made to vector types, which are both not promoted and whose element types must match.

Fixes #84047.

RFC: https://discourse.llvm.org/t/rfc-change-behaviour-of-elementwise-builtins-on-scalar-integer-types/83725

### CODE REVIEW

**Comment by frasercrmck** [comment]
I just realised this is also a problem with the `bitreverse` and `popcount` builtins on signed types for the same reason.

**Comment by RKSimon** [comment]
I thought bitreverse/popcount are only supposed to work with unsigned types?

**Comment by frasercrmck** [comment]
> I thought bitreverse/popcount are only supposed to work with unsigned types?

Good question. The [documentation](https://clang.llvm.org/docs/LanguageExtensions.html) doesn't mention they're only for signed types, as `abs` does, for example. So if there is such a restriction, it's not documented, nor checked in the code.

Tangentially, in OpenCL (where I'm coming from) there's no restriction on `popcount` to be only on unsigned types.

**Comment by efriedma-quic** [comment]
Even with this fix, the behavior with mixed types still seems really confusing, especially if you mix signed/unsigned inputs.  Can we address that somehow?

**Comment by frasercrmck** [comment]
> Even with this fix, the behavior with mixed types still seems really confusing, especially if you mix signed/unsigned inputs. Can we address that somehow?

I totally agree.

The (elementwise) builtins won't let you mix `ext_vector_type`s of different signs or element sizes, so maybe we should extend logic that to all scalars too? Ban mixed signs? Ban mixed sizes entirely? This would be a larger change that would probably need documenting - an RFC? Worth noting perhaps that maybe the current vector behaviour depends on the type of vectors you use (OpenCL, AltiVec, GCC, NEON, SVE) - I haven't checked that.

I note also that the documentation says that `For scalar types, consider the operation applied to a vector with a single element.`. This is misleading, as the usual implicit conversions don't behave the same way for scalars as they do for vectors.

CC @arsenm - might be of interest to you.

**Comment by efriedma-quic** [comment]
If people aren't using the edge cases, they won't notice if we start error'ing out.  If they are, it's pretty easy to adapt the code to build with both old and new compilers.  A quick GitHub search shows exactly one user of the builtins outside of clang itself, and that code uses a vector input.

Maybe makes sense to RFC it for wider exposure, but I doubt anyone will object.

We should probably write a release note for this in any case.

**Comment by frasercrmck** [comment]
RFC: https://discourse.llvm.org/t/rfc-change-behaviour-of-elementwise-builtins-on-scalar-integer-types/83725. I don't expect anyone to say anything at all, tbh, especially during the holidays.

> If people aren't using the edge cases, they won't notice if we start error'ing out. If they are, it's pretty easy to adapt the code to build with both old and new compilers. A quick GitHub search shows exactly one user of the builtins outside of clang itself, and that code uses a vector input.

That's useful context, thank you

> We should probably write a release note for this in any case.

Makes sense. I'll implement the RFC in the new year. We might run into further questions about what to do with enums and other things currently handled for us by the usual unary conversions. I think we'll have to roll our own solution as I haven't seen anything suitable. My knowledge of Sema isn't great, though.

File: clang/test/CodeGen/builtins-elementwise-math.c [hunk 1]
```diff
@@ -68,15 +66,18 @@ void test_builtin_elementwise_add_sat(float f1, float f2, double d1, double d2,
...
+                                      unsigned short us1, unsigned short us2) {
   // CHECK:      [[I1:%.+]] = load i64, ptr %i1.addr, align 8
   // CHECK-NEXT: [[I2:%.+]] = load i64, ptr %i2.addr, align 8
   // CHECK-NEXT: call i64 @llvm.sadd.sat.i64(i64 [[I1]], i64 [[I2]])
   i1 = __builtin_elementwise_add_sat(i1, i2);
 
   // CHECK:      [[I1:%.+]] = load i64, ptr %i1.addr, align 8
   // CHECK-NEXT: call i64 @llvm.sadd.sat.i64(i64 [[I1]], i64 10)
-  i1 = __builtin_elementwise_add_sat(i1, 10);
+  i1 = __builtin_elementwise_add_sat(i1, (long long int)10);
```
Comment (frasercrmck) [inline clang/test/CodeGen/builtins-elementwise-math.c:80]: I've implemented a naive version of the RFC, but I'm not sure if we want to require explicit casting of immediates in this case. It arguably matches the vector behaviour, and floating-point behaviour, but it's still awkward. Thoughts?

File: clang/test/CodeGenHLSL/builtins/dot-builtin.hlsl [hunk 2]
```diff
@@ -6,7 +6,7 @@
 // CHECK: %conv2 = fptrunc double %hlsl.dot to float
 // CHECK: ret float %conv2
 float builtin_bool_to_float_type_promotion ( float p0, bool p1 ) {
-  return __builtin_hlsl_dot ( p0, p1 );
+  return __builtin_hlsl_dot ( (double)p0, (double)p1 );
```
Comment (frasercrmck) [inline clang/test/CodeGenHLSL/builtins/dot-builtin.hlsl:9]: @farzonl I've quickly hacked this in place to satisfy the tests. The HLSL builtins use the same Sema APIs as the ones I'm interested in changing. Is the old behaviour something that needs preserved?

Comment (farzonl) [reply clang/test/CodeGenHLSL/builtins/dot-builtin.hlsl:9]: From the checks it looks like you have just made the double more explicit. Codegen doesn't look different. So I'm fine with this change.

Also most of the type promotion rules for HLSL are enforced on the HLSL header. We are just using the builins as aliases for the cases we need to invoke an intrinsic.

Note to myself though these tests don't look correct and should probably be removed. DXC would have promoted bool to a float. Short of setting the builtin as `CustomTypeChecking` I don't think that can be achieved here. But again it does not matter because the promotion rules are handled on the hlsl `dot` api which only aliases to the builtin.

Comment (frasercrmck) [reply clang/test/CodeGenHLSL/builtins/dot-builtin.hlsl:9]: Thanks for the reply. I think that make sense, thank you.

Note though that I had to make a change to what I think is a user-facing `pow` builtin [here](https://github.com/llvm/llvm-project/pull/119423/files#diff-fdbd201243000d44dd63e6af5706293c968588d762bed9e050d27e0abd6e80acR40), so this PR might still impact HLSL users directly.

File: clang/lib/Sema/SemaChecking.cpp [hunk 3]
```diff
@@ -14585,11 +14585,18 @@ void Sema::CheckAddressOfPackedMember(Expr *rhs) {
                      _2, _3, _4));
 }
 
+static ExprResult UsualUnaryConversionsNoPromoteInt(Sema &S, Expr *E) {
+  // Don't promote integer types
+  if (QualType Ty = E->getType(); S.getASTContext().isPromotableIntegerType(Ty))
+    return S.DefaultFunctionArrayLvalueConversion(E);
+  return S.UsualUnaryConversions(E);
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaChecking.cpp:14592]: If I'm following correctly, this specifically skips promoting integers... but it allows promoting floats?  I think I'd prefer to factor out the unary-float conversions into a separate function, and call that here, for clarity.

File: clang/lib/Sema/SemaChecking.cpp [hunk 4]
```diff
@@ -14604,57 +14611,63 @@ bool Sema::PrepareBuiltinElementwiseMathOneArgCall(CallExpr *TheCall) {
...
 
-  ExprResult A = TheCall->getArg(0);
-  ExprResult B = TheCall->getArg(1);
-  // Do standard promotions between the two arguments, returning their common
-  // type.
-  Res = UsualArithmeticConversions(A, B, TheCall->getExprLoc(), ACK_Comparison);
-  if (A.isInvalid() || B.isInvalid())
-    return true;
+  checkEnumArithmeticConversions(TheCall->getArg(0), TheCall->getArg(1),
+                                 TheCall->getExprLoc(), ACK_Comparison);
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaChecking.cpp:14640]: Changning whether enums are allowed based on the language mode seems unintuitive and unnecessary.  Either allow them, or forbid them.

File: clang/test/CodeGen/builtins-elementwise-math.c (hunk 1 above)
Comment (efriedma-quic) [reply clang/test/CodeGen/builtins-elementwise-math.c:80]: It's a little awkward, but integer constants in C are awkward in general; not sure there's any better way to handle it.  You can write this more concisely as `10ll`.

Comment (unpacklo) [reply clang/test/CodeGen/builtins-elementwise-math.c:80]: Maybe `INT64_C(10)` from the stdint.h header instead?

Comment (arsenm) [reply clang/test/CodeGen/builtins-elementwise-math.c:80]: If you were using int64_t, should use ll if using long long

File: clang/lib/Sema/SemaChecking.cpp (hunk 3 above)
Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp:14592]: Yes, pretty much. `UsualUnaryConversions` does `DefaultFunctionArrayLvalueConversion` first, then floating-point specific logic. However, it also handles `isPromotableBitField`s.

In your other comment you ask about enums, and perhaps bitfields also falls into that category? Do we really need to support these types in vector maths/arithmetic builtins? There are tests for them, so I preserved the existing logic (though seemingly not for bitfields) but I see the argument for removing that support.

**Comment by fhahn** [comment]
Would be good to also update the documentation for the builtins the clarify the behavior.

File: clang/test/CodeGen/builtins-elementwise-math.c (hunk 1 above)
Comment (frasercrmck) [reply clang/test/CodeGen/builtins-elementwise-math.c]: Using `ll` now.

File: clang/lib/Sema/SemaChecking.cpp (hunk 3 above)
Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp:14601]: Could we perhaps extend `UsualUnaryConversions` with a default-true bool flag to control the handling of integers/bitfields? I can see that it might be exposing too many internal details to users of `UsualUnaryConversions`, so I'm not sure. I don't know the best practices of clang/sema design here.

**Comment by frasercrmck** [comment]
> Would be good to also update the documentation for the builtins the clarify the behavior.

I've added some words to that effect. Is that what you had in mind?

File: clang/docs/LanguageExtensions.rst [hunk 5]
```diff
@@ -649,7 +649,9 @@ Unless specified otherwise operation(±0) = ±0 and operation(±infinity) = ±in
 
 The integer elementwise intrinsics, including ``__builtin_elementwise_popcount``,
 ``__builtin_elementwise_bitreverse``, ``__builtin_elementwise_add_sat``,
-``__builtin_elementwise_sub_sat`` can be called in a ``constexpr`` context.
+``__builtin_elementwise_sub_sat`` can be called in a ``constexpr`` context. No
```
Comment (RKSimon) [inline clang/docs/LanguageExtensions.rst:652]: New paragraph to make this clearer.

Comment (frasercrmck) [reply clang/docs/LanguageExtensions.rst]: Good idea, thanks.

File: clang/lib/Sema/SemaChecking.cpp (hunk 3 above)
Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp:14601]: Yep, makes sense. I've added `Sema::UsualUnaryFPConversions` and am using that where appropriate. I didn't want to fold in the use of `DefaultFunctionArrayLvalueConversion`  into that even though that would have saved a bit of duplicated code.

Regarding bitfields: with the current version of this patch (i.e., without the implicit promotion) we are calling the builtin according to the type you specify in the bitfield:

``` c
struct StructWithBitfield {
  int i : 4;
  char c: 4;
  short s : 4;
};
```

`__builtin_elementwise_abs(s.i)` calls `llvm.abs.i32`, `s.c` calls `llvm.abs.i8`, `s.s` `llvm.abs.i16`, etc. I wonder if this is consistent enough behaviour to permit them?

File: clang/lib/Sema/SemaChecking.cpp (hunk 4 above)
Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp:14649]: Can you clarify what you mean here, sorry? I assume you mean just in the context of these vector builtins. This call looks like it's just checking the following:

```
  // C++2a [expr.arith.conv]p1:
  //   If one operand is of enumeration type and the other operand is of a
  //   different enumeration type or a floating-point type, this behavior is
  //   deprecated ([depr.arith.conv.enum]).
  //
  // Warn on this in all language modes. Produce a deprecation warning in C++20.
  // Eventually we will presumably reject these cases (in C++23 onwards?).
```

So it's not really whether "enums are allowed", but whether you're allowed to mix different enums, or enums with floating-point values, in binary builtins.

I agree the inconsistency here is not desirable, especially as we're not doing the same for the ternary elementwise builtins.

Should we just forbid this in all binary/ternary vector elementwise builtins?

File: clang/lib/Sema/SemaChecking.cpp (hunk 3 above)
Comment (efriedma-quic) [reply clang/lib/Sema/SemaChecking.cpp]: It's a little weird that the resulting type can be larger than what integer promotion would produce (without this patch, `struct S { long l : 4; }; S s; static_assert(sizeof(__builtin_elementwise_abs(s.l)) == 4);`).  But maybe that's fine.

File: clang/lib/Sema/SemaChecking.cpp (hunk 4 above)
Comment (efriedma-quic) [reply clang/lib/Sema/SemaChecking.cpp:14654]: I think so.

Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp]: Alright, I've forbidden mixed enum types and have added some tests for them.

File: clang/lib/Sema/SemaChecking.cpp (hunk 3 above)
Comment (frasercrmck) [reply clang/lib/Sema/SemaChecking.cpp]: I don't have strong opinions either way. I've added some CodeGen tests for bitfields so at least the current behaviour is tested.

**Comment by frasercrmck** [comment]
ping

**Review by RKSimon — COMMENTED** [review]
LGTM - but we should have a frontend specialist approve

**Comment by frasercrmck** [comment]
@efriedma-quic are you happy with this PR?

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by frasercrmck** [comment]
> LLVM Buildbot has detected a new failure on builder `llvm-clang-aarch64-darwin` running on `doug-worker-4` while building `clang` at step 6 "test-build-unified-tree-check-all".
> 
> Full details are available at: https://lab.llvm.org/buildbot/#/builders/190/builds/13711
> Here is the relevant piece of the build log for the reference

I don't believe this failure was caused by this PR. The test looks flaky to me. The [log](https://lab.llvm.org/buildbot/#/builders/190/builds/13711/steps/6/logs/FAIL__Clang__live-stmts_cpp) seems to show that the order of the output isn't deterministic

``` spoiler
         153: [ B2 (live expressions at block exit) ] 
check:221     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         154:  
empty:222     ^
         155: IntegerLiteral 0x11e810600 'int' 0 
         156:  
         157: IntegerLiteral 0x11e810620 'int' 1 
         158:  
         159: ImplicitCastExpr 0x13f811978 '_Bool' <LValueToRValue> 
check:223     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         160: `-DeclRefExpr 0x13f811938 '_Bool' lvalue ParmVar 0x13f8117b8 'b' '_Bool' 
check:224     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         161:  
empty:225     ^
         162: ImplicitCastExpr 0x13f811990 '_Bool' <LValueToRValue> 
check:226     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         163: `-DeclRefExpr 0x13f811958 '_Bool' lvalue ParmVar 0x13f8117b8 'b' '_Bool' 
check:227     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         164:  
empty:228     ^
         165: BinaryOperator 0x13f8119a8 '_Bool' '||' 
check:229     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         166: |-ImplicitCastExpr 0x13f811978 '_Bool' <LValueToRValue> 
check:230     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         167: | `-DeclRefExpr 0x13f811938 '_Bool' lvalue ParmVar 0x13f8117b8 'b' '_Bool' 
check:231     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         168: `-ImplicitCastExpr 0x13f811990 '_Bool' <LValueToRValue> 
check:232     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         169:  `-DeclRefExpr 0x13f811958 '_Bool' lvalue ParmVar 0x13f8117b8 'b' '_Bool' 
check:233      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         170:  
empty:234     ^
         171:  
         172: [ B3 (live expressions at block exit) ] 
```

Whereas the checks are clearly:

```
// CHECK: [ B2 (live expressions at block exit) ]
// CHECK-EMPTY:
// CHECK: ImplicitCastExpr {{.*}} '_Bool' <LValueToRValue>
// CHECK: `-DeclRefExpr {{.*}} '_Bool' lvalue ParmVar {{.*}} 'b' '_Bool'
// CHECK-EMPTY:
// CHECK: ImplicitCastExpr {{.*}} '_Bool' <LValueToRValue>
// CHECK: `-DeclRefExpr {{.*}} '_Bool' lvalue ParmVar {{.*}} 'b' '_Bool'
// CHECK-EMPTY:
// CHECK: BinaryOperator {{.*}} '_Bool' '||'
// CHECK: |-ImplicitCastExpr {{.*}} '_Bool' <LValueToRValue>
// CHECK: | `-DeclRefExpr {{.*}} '_Bool' lvalue ParmVar {{.*}} 'b' '_Bool'
// CHECK: `-ImplicitCastExpr {{.*}} '_Bool' <LValueToRValue>
// CHECK:   `-DeclRefExpr {{.*}} '_Bool' lvalue ParmVar {{.*}} 'b' '_Bool'
// CHECK-EMPTY:
// CHECK: IntegerLiteral {{.*}} 'int' 0
// CHECK-EMPTY:
// CHECK: IntegerLiteral {{.*}} 'int' 1
// CHECK-EMPTY:
// CHECK-EMPTY:
```

Note how the position of the two `IntegerLiteral` statements isn't as expected, and this seems to trip up FileCheck.
