### PR TITLE
[Clang] Fix crash on `void{}`

### LINKED ISSUE #116440: [Clang] ICE on `void{}`
This expression `void{}` causes an ICE in clang trunk. In clang 19.1, it gets rejected.
See compiler Explorer: https://godbolt.org/z/e85YYTaTx

### PR DESCRIPTION
**Pull request by cor3ntin**
Caused by an incorrect assertion.

Fixes #116440

### CODE REVIEW

File: clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp [hunk 1]
```diff
@@ -5,3 +5,12 @@ void f()
   // CHECK: store i32 0
   int i{};
 }
+
+
+namespace GH116440 {
+void f() {
+  void{};
+  void();
+}
```
Comment (erichkeane) [inline clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp:14]: Can you add check-lines to this one?

Comment (cor3ntin) [reply clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp:14]: What do you want me to check? noting is emitted

Comment (erichkeane) [reply clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp:14]: Just the function header then `CHECK-NEXT: ret void` confirms that it actually does nothing/makes it through codegen without going sideways.

So:
```
// CHECK: define{{.*}} void @{{.*}}GH116440{{.*}}()
// CHECK-NEXT: {{.*}}:
// CHECK-NEXT: ret void
```

That should work on both windows and itanium manglers, though be more specific on the function name if this test uses a triple.

File: clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp [hunk 2]
```diff
@@ -13,4 +13,7 @@ void f() {
   void();
 }
 
+// CHECK: define{{.*}} void @_ZN8GH1164401fEv()
```
Comment (erichkeane) [inline clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp:16]: There is no target-triple on this test, so this will fail in windows mode.  You can try running it with `-triple x86_64-windows-pc` to see what I mean.

**Review by erichkeane — APPROVED** [review]

File: clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp (hunk 2 above)
Comment (cor3ntin) [reply clang/test/CodeGenCXX/cxx0x-initializer-scalars.cpp:16]: oups!

**Review by shafik — COMMENTED** [review]
I guess we missed a release note?
