### PR TITLE
[Thumb,ELF] Fix access to dso_preemptable __stack_chk_guard with static relocation model

### LINKED ISSUE #64999: [LTO][PIC][ARM][SSP] extra indirection accessing __stack_chk_guard
After commit [e018cbf7208b](https://github.com/llvm/llvm-project/commit/e018cbf7208b3d34f18997ddee84c66cee32fb1b) we're seeing segfaults when accessing __stack_chk_guard when using LTO. I'm attaching a small test case (3 source files and small build script) that shows the problem). When compiling with -flto -fPIC and linking without any additional flags, we're seeing the following code in the function foo:
```   
201dc: e59f006c      ldr     r0, [pc, #0x6c]         @ 0x20250 <foo+0x80>
201e0: e5900000      ldr     r0, [r0]
201e4: e5900000      ldr     r0, [r0]
201e8: e50b000c      str     r0, [r11, #-0xc]
...
20250: 54 02 03 00   .word   0x00030254
```
And from the linker map file:
```
30254    30254        4     1                 __stack_chk_guard
```
So we're seeing an extra indirection, causing the segfaults.

If we're adding -pie to the link line, things work fine. We see:
```
   10280: e59f0074      ldr     r0, [pc, #0x74]         @ 0x102fc <foo+0x88>
   10284: e08f0000      add     r0, pc, r0
   10288: e5900000      ldr     r0, [r0]
   1028c: e5900000      ldr     r0, [r0]
    ...
   102fc: e4 00 01 00   .word   0x000100e4
```
with the GOT present in the executable.

Note that the the test case is not meant to execute anywhere. A rudimentary module (rt.c) supplies the missing definitions.
[stack_check.zip](https://github.com/llvm/llvm-project/files/12444315/stack_check.zip)

### PR DESCRIPTION
**Pull request by MaskRay**
PR #70014 fixes A32 to use GOT for dso_preemptable `__stack_chk_guard`
with static relocation model (e.g. -fPIE/-fPIC LTO compiles with -no-pie
linking).

This patch fixes such `__stack_chk_guard` access for Thumb1 and Thumb2.
Note: `t2LDRLIT_ga_pcrel` is only for ELF. mingw needs
`.refptr.__stack_chk_guard` (https://reviews.llvm.org/D92738).

Fix #64999

### CODE REVIEW

File: llvm/lib/Target/ARM/Thumb1InstrInfo.cpp [hunk 1]
```diff
@@ -135,14 +135,15 @@ void Thumb1InstrInfo::loadRegFromStackSlot(MachineBasicBlock &MBB,
 void Thumb1InstrInfo::expandLoadStackGuard(
     MachineBasicBlock::iterator MI) const {
   MachineFunction &MF = *MI->getParent()->getParent();
-  const TargetMachine &TM = MF.getTarget();
   const ARMSubtarget &ST = MF.getSubtarget<ARMSubtarget>();
+  const GlobalValue *GV =
+      cast<GlobalValue>((*MI->memoperands_begin())->getValue());
```
Comment (nickdesaulniers) [inline llvm/lib/Target/ARM/Thumb1InstrInfo.cpp:140]: `const auto *GV = ...`

https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

(this can be fixed in llvm/lib/Target/ARM/Thumb2InstrInfo.cpp L264 as well)

**Comment by nickdesaulniers** [comment]
(the commit message seems odd; intentional?)

File: llvm/lib/Target/ARM/Thumb1InstrInfo.cpp (hunk 1 above)
Comment (MaskRay) [reply llvm/lib/Target/ARM/Thumb1InstrInfo.cpp]: Thanks for the suggestion. Done

**Comment by MaskRay** [comment]
> (the commit message seems odd; intentional?)

Hopefully clarified:)

File: llvm/lib/Target/ARM/Thumb1InstrInfo.cpp [hunk 2]
```diff
@@ -135,14 +135,14 @@ void Thumb1InstrInfo::loadRegFromStackSlot(MachineBasicBlock &MBB,
...
-  const TargetMachine &TM = MF.getTarget();
   const ARMSubtarget &ST = MF.getSubtarget<ARMSubtarget>();
+  const auto *GV = cast<GlobalValue>((*MI->memoperands_begin())->getValue());
 
   assert(MF.getFunction().getParent()->getStackProtectorGuard() != "tls" &&
          "TLS stack protector not supported for Thumb1 targets");
 
   unsigned Instr;
-  if (TM.isPositionIndependent())
+  if (!GV->isDSOLocal())
```
Comment (nickdesaulniers) [inline llvm/lib/Target/ARM/Thumb1InstrInfo.cpp:145]: does Thumb1 need similar guards for whether the target is elf?

Comment (MaskRay) [reply llvm/lib/Target/ARM/Thumb1InstrInfo.cpp:145]: Based on my archaeology to the  `Thumb1InstrInfo::expandLoadStackGuard` function, the changes haven't been related to Thumb1-only microarchitectures (before v6T2/v7) for non-ELF object file formats.

https://reviews.llvm.org/D75453 says that Windows AArch32 requires at least v7.

**Review by nickdesaulniers — APPROVED** [review]

**Comment by nico** [comment]
Is http://45.33.8.238/linux/128720/step_12.txt due to this? Is this a problem on my end?

**Comment by gulfemsavrun** [comment]
> Is http://45.33.8.238/linux/128720/step_12.txt due to this? Is this a problem on my end?

We started seeing the same issue on our Clang toolchain builders on Linux:
```
******************** TEST 'LLVM :: CodeGen/Thumb/stack_guard_remat.ll' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 1: /b/s/w/ir/x/w/llvm_build/bin/llc < /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -mtriple=thumb-apple-darwin -relocation-model=pic -no-integrated-as | /b/s/w/ir/x/w/llvm_build/bin/FileCheck /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -check-prefix=PIC
+ /b/s/w/ir/x/w/llvm_build/bin/llc -mtriple=thumb-apple-darwin -relocation-model=pic -no-integrated-as
+ /b/s/w/ir/x/w/llvm_build/bin/FileCheck /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -check-prefix=PIC
warning: inline asm clobber list contains reserved registers: R7, R9, SP
note: Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
RUN: at line 2: /b/s/w/ir/x/w/llvm_build/bin/llc < /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -mtriple=thumb-apple-darwin -relocation-model=static -no-integrated-as | /b/s/w/ir/x/w/llvm_build/bin/FileCheck /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -check-prefix=NO-PIC  -check-prefix=STATIC
+ /b/s/w/ir/x/w/llvm_build/bin/llc -mtriple=thumb-apple-darwin -relocation-model=static -no-integrated-as
+ /b/s/w/ir/x/w/llvm_build/bin/FileCheck /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll -check-prefix=NO-PIC -check-prefix=STATIC
warning: inline asm clobber list contains reserved registers: R7, R9, SP
note: Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
/b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll:23:15: error: NO-PIC-NEXT: is not on the line after the previous match
;NO-PIC-NEXT: ldr [[ORIGINAL_GUARD]], [[[ORIGINAL_GUARD]]]
              ^
<stdin>:35:2: note: 'next' match was here
 ldr r1, [r1]
 ^
<stdin>:32:17: note: previous match ended here
 ldr r1, LCPI0_2
                ^
<stdin>:33:1: note: non-matching line after previous match is here
LPC0_2:
^

Input file: <stdin>
Check file: /b/s/w/ir/x/w/llvm-llvm-project/llvm/test/CodeGen/Thumb/stack_guard_remat.ll

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         .
         .
         .
        30:  add r0, sp, #904 
        31:  ldr r0, [r0, #124] 
        32:  ldr r1, LCPI0_2 
        33: LPC0_2: 
        34:  add r1, pc 
        35:  ldr r1, [r1] 
next:23      !~~~~~~~~~~~  error: match on wrong line
        36:  cmp r1, r0 
        37:  bne LBB0_2 
        38: @ %bb.1: 
        39:  movs r0, #0 
        40:  subs r6, r7, #7 
         .
         .
         .
>>>>>>

--

********************
```
https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8758166179301265441/overview

**Comment by MaskRay** [comment]
> Is http://45.33.8.238/linux/128720/step_12.txt due to this? Is this a problem on my end?

Sorry, I missed this failure. `llvm/test/CodeGen/Thumb/stack_guard_remat.ll` needed adjustment (relocation model pic/dynamic-no-pic should be used without "PIC Level" if thumb-apple-darwin doesn't use LTO).
I fixed it in eaef645a5836df56b53800383022a3a384305c6b

**Comment by gulfemsavrun** [comment]
> > Is http://45.33.8.238/linux/128720/step_12.txt due to this? Is this a problem on my end?
> 
> Sorry, I missed this failure. `llvm/test/CodeGen/Thumb/stack_guard_remat.ll` needed adjustment (relocation model pic/dynamic-no-pic should be used without "PIC Level" if thumb-apple-darwin doesn't use LTO). I fixed it in [eaef645](https://github.com/llvm/llvm-project/commit/eaef645a5836df56b53800383022a3a384305c6b)

[eaef645](https://github.com/llvm/llvm-project/commit/eaef645a5836df56b53800383022a3a384305c6b) fixed the test failure, thanks!
