### PR TITLE
[OMPIRBuilder] Pass work loop type in ident flags

### LINKED ISSUE #112545: [Flang][OpenMP][OMPT] Warning for loop types not needed anymore
Back in https://github.com/llvm/llvm-project/issues/63904, I've reported that the OpenMP Tools Interface implementation in LLVM fails to transfer the loop type to an attached tool, giving only a limited amount of information.

At some point between the reported issue and https://github.com/llvm/llvm-project/pull/97429, a warning was added for Flang explicitly:

```
OMP: Warning #189: OMPT: Cannot determine workshare type; using the default (loop) instead. This issue is fixed in an up-to-date compiler.
```

Back when the issue was not fixed in `libomp`, the warning was a bit weird, as the issue was not fixed in an up-to-date compiler. However, the issue is now irrelevant, as the information is transferred correctly:

```fortran
program parallel_sum
    use omp_lib
    implicit none

    integer(8) :: sum
    integer :: i

    sum = 0

    call omp_set_num_threads( 2 )

    !$omp parallel do reduction(+:sum) default(none)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

    !$omp parallel do reduction(+:sum) default(none) schedule(static)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

    !$omp parallel do reduction(+:sum) default(none) schedule(dynamic)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

    !$omp parallel do reduction(+:sum) default(none) schedule(guided)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

    !$omp parallel do reduction(+:sum) default(none) schedule(auto)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

    !$omp parallel do reduction(+:sum) default(none) schedule(runtime)
    do i = 0, 99
        sum = sum + i
    end do
    !$omp end parallel do

end program parallel_sum
```

Attaching a basic information dumping tool, the following information is obtained:
```console
$ flang --version
flang version 20.0.0git (https://github.com/llvm/llvm-project.git 77f8297c6fdaa62121ddb108043dcaad5c45c7ad)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/apps/software/Clang/trunk/bin
Build config: +assertions
$ flang -fopenmp test.f90
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
$ ./a.out | grep "callback_work"
OMP: Warning #189: OMPT: Cannot determine workshare type; using the default (loop) instead. This issue is fixed in an up-to-date compiler.
[0][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000001 (0x55b5b7030f60) | task_data->value = 555000002 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591b310
[0][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000001 (0x55b5b7030f60) | task_data->value = 555000002 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591b34d
[1][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000001 (0x55b5b7030f60) | task_data->value = 555000003 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591b310
[1][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000001 (0x55b5b7030f60) | task_data->value = 555000003 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591b34d
[0][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000002 (0x55b5b7030f60) | task_data->value = 555000004 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591b140
[0][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000002 (0x55b5b7030f60) | task_data->value = 555000004 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591b17d
[1][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000002 (0x55b5b7030f60) | task_data->value = 555000005 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591b140
[1][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000002 (0x55b5b7030f60) | task_data->value = 555000005 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591b17d
[0][callback_work] work_type = loop_dynamic | endpoint = begin | parallel_data->value = 666000003 (0x55b5b7030f60) | task_data->value = 555000006 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591af5f
[1][callback_work] work_type = loop_dynamic | endpoint = begin | parallel_data->value = 666000003 (0x55b5b7030f60) | task_data->value = 555000007 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591af5f
[0][callback_work] work_type = loop_dynamic | endpoint = end | parallel_data->value = 666000003 (0x55b5b7030f60) | task_data->value = 555000006 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591af82
[1][callback_work] work_type = loop_dynamic | endpoint = end | parallel_data->value = 666000003 (0x55b5b7030f60) | task_data->value = 555000007 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591af82
[0][callback_work] work_type = loop_guided | endpoint = begin | parallel_data->value = 666000004 (0x55b5b7030f60) | task_data->value = 555000008 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591ad8f
[1][callback_work] work_type = loop_guided | endpoint = begin | parallel_data->value = 666000004 (0x55b5b7030f60) | task_data->value = 555000009 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591ad8f
[1][callback_work] work_type = loop_guided | endpoint = end | parallel_data->value = 666000004 (0x55b5b7030f60) | task_data->value = 555000009 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591adb2
[0][callback_work] work_type = loop_guided | endpoint = end | parallel_data->value = 666000004 (0x55b5b7030f60) | task_data->value = 555000008 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591adb2
[0][callback_work] work_type = loop_guided | endpoint = begin | parallel_data->value = 666000005 (0x55b5b7030f60) | task_data->value = 555000010 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591abbf
[0][callback_work] work_type = loop_guided | endpoint = end | parallel_data->value = 666000005 (0x55b5b7030f60) | task_data->value = 555000010 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591abe2
[1][callback_work] work_type = loop_guided | endpoint = begin | parallel_data->value = 666000005 (0x55b5b7030f60) | task_data->value = 555000011 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591abbf
[1][callback_work] work_type = loop_guided | endpoint = end | parallel_data->value = 666000005 (0x55b5b7030f60) | task_data->value = 555000011 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591abe2
[0][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000006 (0x55b5b7030f60) | task_data->value = 555000012 (0x55b5b7039640) | count = 100 | codeptr_ra = 0x55b5b591a9ef
[0][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000006 (0x55b5b7030f60) | task_data->value = 555000012 (0x55b5b7039640) | count = 0 | codeptr_ra = 0x55b5b591aa12
[1][callback_work] work_type = loop_static | endpoint = begin | parallel_data->value = 666000006 (0x55b5b7030f60) | task_data->value = 555000013 (0x55b5b7039780) | count = 100 | codeptr_ra = 0x55b5b591a9ef
[1][callback_work] work_type = loop_static | endpoint = end | parallel_data->value = 666000006 (0x55b5b7030f60) | task_data->value = 555000013 (0x55b5b7039780) | count = 0 | codeptr_ra = 0x55b5b591aa12
```

This matches the information obtained with a C / C++ source code. 
Therefore, the warning can probably just be removed.

### PR DESCRIPTION
**Pull request by Thyre**
Flang uses the OMPIRBuilder to lower OpenMP constructs to LLVM IR.
When dealing with work sharing constructs, such as DO, DISTRIBUTE or SECTIONS/SECTION, OMPIRBuilder needs to construct the call to the OpenMP runtime, typically `__kmpc_for_static_init` or `__kmpc_dist_for_static_init`.

The first passed flag to these functions is the `ident_t` struct, defined in `kmp.h`. Most of the arguments are reserved for usage in Fortran and unused in `openmp`. However, the `flags` argument is used throughout the code base to identify specific constructs, such as the type of work sharing construct.

In https://github.com/llvm/llvm-project/issues/112545, it was identified that Flang does not provide the correct `ident_t` flags when calling into e.g. `__kmpc_for_static_init`, causing the following runtime warning to appear when the OpenMP Tools Interface is used:

```
OMP: Warning #189: OMPT: Cannot determine workshare type; using the default (loop) instead. This issue is fixed in an up-to-date compiler.
```

This PR adds a test, verifying that the work sharing constructs provide the correct flags to the runtime call. The IR check for SECTIONS/SECTION maps against `KMP_IDENT_WORK_LOOP`, as the OMPIRBuilder converts the SECTIONS construct into a DO loop with a switch-case for every SECTION clause.

In addition, `OMPIRBuilder` is modified, so that the work loop type is passed via `ident_t.flags` to the respective `__kmpc_for_static_init`/`__kmpc_dist_for_static_init` calls, letting the test pass and the `libomp` warning disappear.
Wherever possible, provide the mapping based on the passed `LoopType`. If not available, I implemented the decision based on the `DistScheduleSchedType`, or in case of `applyDynamicWorkshareLoop`, hard-coded this to `OMP_IDENT_FLAG_WORK_LOOP`.

---

As this is the first time dealing with `OMPIRBuilder`, I'm not sure if I missed anything while implementing these changes.
If there's anything that can be improved here, e.g. with the ident flag mapping, I'm very grateful for any feedback. I tried to implement this with the best of my understanding based on taking a look at the existing code and tests.

For example, I was not sure if adding a test to `flang/test/Integration/OpenMP/` is the correct approach here, or if I rather should try to modify `unittests/Frontend/OpenMPIRBuilderTest.cpp`. In the end, the former looked to me more straight-forward.

---

Fixes https://github.com/llvm/llvm-project/issues/112545

### CODE REVIEW

**Comment by Thyre** [comment]
@ergawy, @abidh, @tblah, I'm sorry for pinging you.
I'd like to ask if anyone of you has some spare cycles to take a look at this PR, or if you know someone who could take a look at it.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -5498,7 +5510,8 @@ OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::applyStaticWorkshareLoop(
   Builder.CreateStore(UpperBound, PUpperBound);
   Builder.CreateStore(One, PStride);
 
-  Value *ThreadNum = getOrCreateThreadID(SrcLoc);
+  Value *ThreadNum =
+      getOrCreateThreadID(getOrCreateIdent(SrcLocStr, SrcLocStrSize));
```
Comment (tblah) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:5525]: Shouldn't this use the `Flag` from above?

Comment (Thyre) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:5525]: In an earlier revision, I used the created `Flag`. This seemed to work fine as well.
Looking at [`__kmpc_global_thread_num`](https://github.com/llvm/llvm-project/blob/f5eb99ac14a1ca5f2a9771ada2c8c672b430f253/openmp/runtime/src/kmp_csupport.cpp#L100), the passed `ident_t` seems to be entirely unused.

The current implementation is more consistent with the remainder of `OMPIRBuilder`. All Idents passed to `getOrCreateThreadID` do not use any `LocFlags` or `Reserve2Flags` as far as I can tell. 

I'm fine with changing this to whatever fits best.

**Review by tblah — APPROVED** [review]
LGTM, sorry this took a while to get a review

**Comment by Thyre** [comment]
Thanks a lot for taking the time to review the PR.
Just as a heads up, I'm not able to merge this PR, as I don't have the permissions for it.

Also, regarding the failure in "[CI Checks / Build and Test Linux AArch64 (pull_request)](https://github.com/llvm/llvm-project/actions/runs/24234179757/job/70752547618?pr=189347)", should I just try to rebase this PR and hope that the CI passes then? The last few times I saw failures, they were in LLDB, which seem to be entirely unrelated to what I'm touching here (the last failure was e.g. in `lang/cpp/static_members/TestCPPStaticMembers.py`).

**Comment by tblah** [comment]
I agree that failure doesn't look related to your work. I've pressed github's rebase button to re-run the CI and if it passes I'll merge.
