### PR TITLE
[AArch64] Allow peephole to optimize AND + signed compare with 0

### LINKED ISSUE #154387: [AArch64] AND optimization does not work if there is a freeze between AND and the cmp
Here is a case from the real world where this happens:
```
define i1 @test_disjoint(i1 %0, i32 %1, i32 %2) {
  %3 = or disjoint i32 %2, 8388608
  %4 = shl nuw i32 1, %1
  %5 = and i32 %3, %4
  %6 = icmp eq i32 %5, 0
  %7 = select i1 %0, i1 true, i1 %6
  ret i1 %7
}
```
We get:
```
test_disjoint:                          // @test_disjoint
        mov     w8, #1                          // =0x1
        orr     w9, w2, #0x800000
        lsl     w8, w8, w1
        and     w8, w9, w8
        cmp     w8, #0
        cset    w8, eq
        orr     w8, w0, w8
        and     w0, w8, #0x1
        ret
```
There are many ways to solve this problem. 

In the short term, I guess we can fix this by special casing it. However, I am not sure of if this will be safe every time.

In all honesty, I think that perhaps this optimization should not be done at all in the long term. Why? This seems more like a peephole optimizer job.

So, my solution to this problem, and yes this definitely will not catch all cases because this works on a different domain to the SelDAG, is https://github.com/llvm/llvm-project/pull/153608, but also we don't do the replace all users in GISel anyway, so this benefits that too.

### PR DESCRIPTION
**Pull request by AZero13**
This should be the peephole's job. Because and sets V flag to 0, this is why signed comparisons with 0 are okay to replace with tst. Note this is only for AArch64, because ANDS on ARM leaves the V flag the same.

Fixes: https://github.com/llvm/llvm-project/issues/154387

### CODE REVIEW

**Comment by AZero13** [comment]
@davemgreen

**Comment by AZero13** [comment]
> I think the utility of your change would be more apparent if you pre-comitted some tests. IIUC this is folding things like:
> 
> ```
> 
>         and     w8, w9, w8
> 
>         cmp     w8, #0
> 
> ```
> 
> to
> 
> ```
> 
> tst w9, w8
> 
> ```
> 
> ?

Yes exactly that's the point

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 1]
```diff
@@ -1433,6 +1433,34 @@ static unsigned convertToNonFlagSettingOpc(const MachineInstr &MI) {
...
+  case AArch64::BICSWrs:
+    return AArch64::BICWrs;
+  case AArch64::BICSXrs:
+    return AArch64::BICXrs;
+  case AArch64::SBCSXr:
+    return AArch64::SBCXr;
+  case AArch64::SBCSWr:
+    return AArch64::SBCWr;
+  case AArch64::ADCSXr:
+    return AArch64::ADCXr;
```
Comment (MacDue) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:1461]: Are all of these changes used? I don't see how SBC/ADC is relevant here?

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 2]
```diff
@@ -1921,7 +1998,8 @@ static bool canInstrSubstituteCmpInstr(MachineInstr &MI, MachineInstr &CmpInstr,
   // 1) MI and CmpInstr set N and V to the same value.
   // 2) If MI is add/sub with no-signed-wrap, it produces a poison value when
   //    signed overflow occurs, so CmpInstr could still be simplified away.
-  if (NZVCUsed->V && !MI.getFlag(MachineInstr::NoSWrap))
+  // 3) ANDS/BICS on AArch64 always sets V to 0, so it is safe to look through.
```
Comment (MacDue) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:2001]: I think this case is already covered by `"MI and CmpInstr set N and V to the same value"`, which I think is true in this case.

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:2001]: It's not.

SLE 0 is not MI

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:2001]: AND instructions are not tagged as no overflow

And, the peephole as is checks for no touching of V and C.

However, and instructions on AArch64 (NOT ARM as in the 32 bit ISA) ALWAYS set C and V to 0.

As to when the C being 0 can be useful, I'm trying to figure that out and that's for another PR, but for now,know that cmp with 0 also always clears V, but the peephole doesn't know that.

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:2001]: Ah I get what you mean, but I think it's important to clarify that AND does not set N and V to the same value, because AND sets V to 0 always, and N to if the value is negative.

**Comment by AZero13** [comment]
@MacDue Done!

**Comment by AZero13** [comment]
@davemgreen

**Comment by AZero13** [comment]
@davemgreen @MacDue ping?

**Comment by AZero13** [comment]
@MacDue ping?

File: llvm/lib/Target/AArch64/GISel/AArch64PostSelectOptimize.cpp [hunk 3]
```diff
@@ -87,6 +87,26 @@ unsigned getNonFlagSettingVariant(unsigned Opc) {
     return AArch64::ADDXri;
   case AArch64::ADDSWri:
     return AArch64::ADDWri;
+  case AArch64::ANDSWri:
```
[the remark this answers is not in the document]
Comment (MacDue) [reply llvm/lib/Target/AArch64/GISel/AArch64PostSelectOptimize.cpp]: This was marked as resolved and ignored, but this change does not relate to the rest of this PR (which is not in global ISEL). You can remove this, and all tests still pass. 

Your tests are only for a few AND cases, but you've implemented hooks for many more instructions that are untested. I think it would be better if you reduce the size of the PR to match the code paths you've tested.

[the remark this answers is not in the document]
Comment (AZero13) [reply llvm/lib/Target/AArch64/GISel/AArch64PostSelectOptimize.cpp]: Many more? Just BICS.

**Review by MacDue — APPROVED** [review]
LGTM

**Comment by AZero13** [comment]
Thank you @MacDue can you please merge?
