### PR TITLE
[clang-tidy][NFC] Fix `bugprone-unchecked-optional-access` warnings in codebase

### LINKED ISSUE #156151: [clang-tidy] Enable 'bugprone-unchecked-optional-access' check in clang-tidy config.
The check could be enabled in [.clang-tidy](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/.clang-tidy) or given reason why it shouldn't

### PR DESCRIPTION
**Pull request by zeyi2**
Closes [#156151](https://github.com/llvm/llvm-project/issues/156151)
Assisted-by: Gemini 3 via Gemini CLI

### CODE REVIEW

File: clang-tools-extra/clang-tidy/ClangTidyProfiling.cpp [hunk 1]
```diff
@@ -43,21 +43,21 @@ void ClangTidyProfiling::printUserFriendlyTable(llvm::raw_ostream &OS,
...
+  OS << R"("timestamp": ")" << Storage.Timestamp << "\",\n";
   OS << "\"profile\": {\n";
   TG.printJSONValues(OS, "");
   OS << "\n}\n";
   OS << "}\n";
   OS.flush();
 }
 
-void ClangTidyProfiling::storeProfileData(llvm::TimerGroup &TG) {
-  assert(Storage && "We should have a filename.");
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/ClangTidyProfiling.cpp]: Will fix the removal of this `assert` soon.

File: clang-tools-extra/clang-tidy/abseil/TimeSubtractionCheck.cpp [hunk 2]
```diff
@@ -96,6 +96,8 @@ void TimeSubtractionCheck::registerMatchers(MatchFinder *Finder) {
     const std::string TimeInverse = (llvm::Twine("ToUnix") + ScaleName).str();
     std::optional<DurationScale> Scale = getScaleForTimeInverse(TimeInverse);
     assert(Scale && "Unknown scale encountered");
+    if (!Scale)
+      continue;
```
[the remark this answers is not in the document]
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/abseil/TimeSubtractionCheck.cpp]: It feels weird that dataflow framework didn't count it as "validation", could it be a FP?
Later, you used `assert(BestConversion && "text");` for the same purpose of validation

File: clang-tools-extra/clang-tidy/readability/IdentifierNamingCheck.cpp [hunk 3]
```diff
@@ -1344,10 +1346,14 @@ IdentifierNamingCheck::getFailureInfo(
     ArrayRef<std::optional<IdentifierNamingCheck::NamingStyle>> NamingStyles,
     const IdentifierNamingCheck::HungarianNotationOption &HNOption,
     StyleKind SK, const SourceManager &SM, bool IgnoreFailedSplit) const {
-  if (SK == SK_Invalid || !NamingStyles[SK])
+  if (SK == SK_Invalid)
     return std::nullopt;
 
-  const IdentifierNamingCheck::NamingStyle &Style = *NamingStyles[SK];
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/readability/IdentifierNamingCheck.cpp]: So dataflow couldn't handle checking for multiple optional values in one go? Seems like FP.

**Review by EugeneZelenko — APPROVED** [review]
But please wait for other reviewers.

**Review by vbvictor — APPROVED** [review]
