### PR TITLE
[InstCombine] Fix miscompile in negation of select

### LINKED ISSUE #89669: miscompile of vector double-negation + select by InstCombine
https://alive2.llvm.org/ce/z/N1RVAr

this:
```llvm
define <4 x i32> @f(<4 x i32> %0) {
  %2 = sub <4 x i32> zeroinitializer, %0
  %3 = select <4 x i1> <i1 false, i1 true, i1 poison, i1 poison>, <4 x i32> %2, <4 x i32> %0
  %4 = sub <4 x i32> zeroinitializer, %3
  ret <4 x i32> %4
}
```
is being optimized to:
```llvm
define <4 x i32> @f(<4 x i32> %0) {
  ret <4 x i32> %0
}
```
here's Alive's work explaining why this is wrong:
```
ERROR: Value mismatch

Example:
<4 x i32> %#0 = < #x00000001 (1), poison, poison, poison >

Source:
<4 x i32> %#2 = < #xffffffff (4294967295, -1), poison, poison, poison >
<4 x i32> %#3 = < #x00000001 (1), poison, poison, poison >
<4 x i32> %#4 = < #xffffffff (4294967295, -1), poison, poison, poison >

Target:
Source value: < #xffffffff (4294967295, -1), poison, poison, poison >
Target value: < #x00000001 (1), poison, poison, poison >
```

cc @nunoplopes @hatsunespica

### PR DESCRIPTION
**Pull request by nikic**
Swapping the operands of a select is not valid if one hand is more poisonous that the other, because the negation zero contains poison elements.

Fix this by adding an extra parameter to isKnownNegation() to forbid poison elements.

I've implemented this using manual checks to avoid needing four variants for the NeedsNSW/AllowPoison combinations. Maybe there is a better way to do this...

Fixes https://github.com/llvm/llvm-project/issues/89669.

### CODE REVIEW

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -8042,17 +8042,28 @@ static SelectPatternResult matchMinMax(CmpInst::Predicate Pred,
...
+      return false;
+
+    auto *Zero = cast<Constant>(BO->getOperand(0));
+    if (!AllowPoison && !Zero->isNullValue())
+      return false;
+
     return true;
+  };
 
+  // X = sub (0, Y) || X = sub nsw (0, Y)
```
Comment (goldsteinn) [inline llvm/lib/Analysis/ValueTracking.cpp:8064]: Think 2x comments is unnecessarily verbose, people will get it.

**Comment by goldsteinn** [comment]
This seems like a reasonable way to fix it to me.

LGTM.

**Review by dtcxzyw — APPROVED** [review]
LGTM.
