### PR TITLE
[Clang][RFC] Bypass TAD during overload resolution if a perfect match exists

### LINKED ISSUE #53454: Class with constructor template requiring copyable argument is not copyable by itself
In the following program `struct A` has a constructor template `A(T)` requiring that the type `T` be copy-constructible. At the same time `A` itself must have implicitly defined copy-constructor:
```
#include <type_traits>

struct A {
    template <class T>
    A(T) requires(std::is_copy_constructible_v<T>) {}
};
static_assert(std::is_copy_constructible_v<A>);
```
and the last static_assert(std::is_copy_constructible_v<A>) passes in GCC and MSVC, but Clang rejects it, complaining:
```
error: substitution into constraint expression resulted in a non-constant expression
    A(T) requires(std::is_copy_constructible_v<T>) {}
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/12.0.1/../../../../include/c++/12.0.1/type_traits:971:30: note: while checking constraint satisfaction for template 'A<A>' required here
    : public __bool_constant<__is_constructible(_Tp, _Args...)>
                             ^~~~~~~~~~~~~~~~~~
...
```
Demo: https://gcc.godbolt.org/z/shKe7W1jr

Related discussion: https://stackoverflow.com/q/70874679/7325599

### LINKED ISSUE #62096: Clang complains about concept depending on itself
### Version of Clang
```console
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 5b461d5ec172d21029da492064704fe3da6f8bab)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
```

### Steps to reproduce the problem
Try to compile the following program with `clang++ main.cpp -std=c++20 -ftemplate-backtrace-limit=0`:
```cpp
#include <type_traits>

template <class OPERATOR>
concept Operator = std::is_nothrow_copy_constructible_v<OPERATOR>;

struct AnyOperator {

  template <Operator OP>
  explicit AnyOperator(OP op) noexcept {}

  /// Copy constructor
  AnyOperator(const AnyOperator&) noexcept = default;
};


static_assert(Operator<AnyOperator>);
```
It produces the following output (see also [Godbolt](https://godbolt.org/z/9sTz3ajTM)):

```console
<source>:4:20: error: satisfaction of constraint 'std::is_nothrow_copy_constructible_v<OPERATOR>' depends on itself
concept Operator = std::is_nothrow_copy_constructible_v<OPERATOR>;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:4:20: note: while substituting template arguments into constraint expression here
concept Operator = std::is_nothrow_copy_constructible_v<OPERATOR>;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:8:13: note: while checking the satisfaction of concept 'Operator<AnyOperator>' requested here
  template <Operator OP>
            ^
<source>:8:13: note: while substituting template arguments into constraint expression here
  template <Operator OP>
            ^~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.1/../../../../include/c++/13.0.1/type_traits:3306:7: note: while checking constraint satisfaction for template 'AnyOperator<AnyOperator>' required here
    = __is_nothrow_constructible(_Tp, __add_lval_ref_t<const _Tp>);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.1/../../../../include/c++/13.0.1/type_traits:3306:7: note: in instantiation of function template specialization 'AnyOperator::AnyOperator<AnyOperator>' requested here
<source>:4:25: note: in instantiation of variable template specialization 'std::is_nothrow_copy_constructible_v<AnyOperator>' requested here
concept Operator = std::is_nothrow_copy_constructible_v<OPERATOR>;
                        ^
<source>:4:20: note: while substituting template arguments into constraint expression here
concept Operator = std::is_nothrow_copy_constructible_v<OPERATOR>;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:16:15: note: while checking the satisfaction of concept 'Operator<AnyOperator>' requested here
static_assert(Operator<AnyOperator>);
              ^~~~~~~~~~~~~~~~~~~~~
<source>:16:1: error: static assertion failed
static_assert(Operator<AnyOperator>);
^             ~~~~~~~~~~~~~~~~~~~~~
<source>:16:15: note: because substituted constraint expression is ill-formed: constraint depends on a previously diagnosed expression
static_assert(Operator<AnyOperator>);
              ^
2 errors generated.
```

### Correct behavior

Clang should accept the code. As far as I know the code is valid. It compiles fine with MSVC and GCC.

### LINKED ISSUE #74581: Clang crashes with error: satisfaction of constraint 'std::is_constructible_v<std::decay_t<F>, F>' depends on itself
[godbolt](https://godbolt.org/z/jrc8a3nax)
This is valid code but clang errors and crashes with an assertion failure.
```cpp
#include <functional>
#include <type_traits>

class Co {};

struct Derived {
    Derived() = default;

    template <typename F>
        requires std::is_constructible_v<std::decay_t<F>, F>
    Derived(F&& f);

    Co operator()();
};

void foo() { std::function<Co()> f = Derived(); }
```
error:
```
<source>:10:18: error: satisfaction of constraint 'std::is_constructible_v<std::decay_t<F>, F>' depends on itself
   10 |         requires std::is_constructible_v<std::decay_t<F>, F>
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:10:18: note: while substituting template arguments into constraint expression here
   10 |         requires std::is_constructible_v<std::decay_t<F>, F>
```

<details>
<summary>Crash stacktrace</summary>

```
clang++: /root/llvm-project/clang/include/clang/AST/DeclCXX.h:869: void clang::CXXRecordDecl::setImplicitCopyConstructorIsDeleted(): Assertion `(data().DefaultedCopyConstructorIsDeleted || needsOverloadResolutionForCopyConstructor()) && "Copy constructor should not be deleted"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 -stdlib=libc++ <source>
1.	<eof> parser at end of file
2.	/opt/compiler-explorer/clang-assertions-trunk-20231206/bin/../include/c++/v1/__functional/function.h:1113:30: instantiating function definition 'std::function<Co ()>::function<Derived, void>'
3.	/opt/compiler-explorer/clang-assertions-trunk-20231206/bin/../include/c++/v1/__functional/function.h:440:36: instantiating function definition 'std::__function::__value_func<Co ()>::__value_func<Derived, 0>'
4.	/opt/compiler-explorer/clang-assertions-trunk-20231206/bin/../include/c++/v1/__functional/function.h:412:27: instantiating function definition 'std::__function::__value_func<Co ()>::__value_func<Derived, std::allocator<Derived>>'
5.	/opt/compiler-explorer/clang-assertions-trunk-20231206/bin/../include/c++/v1/__functional/function.h:310:14: instantiating function definition 'std::__function::__func<Derived, std::allocator<Derived>, Co ()>::__func'
 #0 0x00000000037935b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x37935b8)
 #1 0x000000000379129c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x379129c)
 #2 0x00000000036d9db8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fbc92c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007fbc92c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007fbc92c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007fbc92c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007fbc92c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007fbc92c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00000000063de33d clang::Sema::DeclareImplicitCopyConstructor(clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63de33d)
#10 0x000000000609e201 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x609e201)
#11 0x0000000006702f4f clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6702f4f)
#12 0x00000000063d8852 specialMemberIsConstexpr(clang::Sema&, clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, unsigned int, bool, clang::CXXConstructorDecl*, clang::Sema::InheritedConstructorInfo*) SemaDeclCXX.cpp:0:0
#13 0x00000000063d8b87 defaultedSpecialMemberIsConstexpr(clang::Sema&, clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, clang::CXXConstructorDecl*, clang::Sema::InheritedConstructorInfo*) SemaDeclCXX.cpp:0:0
#14 0x00000000063ddc71 clang::Sema::DeclareImplicitCopyConstructor(clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63ddc71)
#15 0x000000000609e201 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x609e201)
#16 0x0000000006702f4f clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6702f4f)
#17 0x00000000063d8852 specialMemberIsConstexpr(clang::Sema&, clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, unsigned int, bool, clang::CXXConstructorDecl*, clang::Sema::InheritedConstructorInfo*) SemaDeclCXX.cpp:0:0
#18 0x00000000063d8c9b defaultedSpecialMemberIsConstexpr(clang::Sema&, clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, clang::CXXConstructorDecl*, clang::Sema::InheritedConstructorInfo*) SemaDeclCXX.cpp:0:0
#19 0x00000000063ddc71 clang::Sema::DeclareImplicitCopyConstructor(clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63ddc71)
#20 0x00000000066cfb5f void llvm::function_ref<void ()>::callback_fn<clang::Sema::LookupConstructors(clang::CXXRecordDecl*)::'lambda'()>(long) SemaLookup.cpp:0:0
#21 0x000000000609e201 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x609e201)
#22 0x00000000066cfe73 clang::Sema::LookupConstructors(clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66cfe73)
#23 0x00000000066a334b TryConstructorInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType, clang::QualType, clang::InitializationSequence&, bool, bool) SemaInit.cpp:0:0
#24 0x00000000066abe5e clang::InitializationSequence::InitializeFrom(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66abe5e)
#25 0x000000000634e4b4 clang::Sema::BuildMemberInitializer(clang::ValueDecl*, clang::Expr*, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x634e4b4)
#26 0x0000000006aedf18 clang::Sema::InstantiateMemInitializers(clang::CXXConstructorDecl*, clang::CXXConstructorDecl const*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6aedf18)
#27 0x0000000006af3d69 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af3d69)
#28 0x0000000006af21cf clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af21cf)
#29 0x0000000006af403e clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af403e)
#30 0x0000000006af21cf clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af21cf)
#31 0x0000000006af403e clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af403e)
#32 0x0000000006af21cf clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af21cf)
#33 0x0000000006af403e clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af403e)
#34 0x0000000006af21cf clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af21cf)
#35 0x00000000060c2479 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#36 0x00000000060c2c52 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x60c2c52)
#37 0x0000000005f54331 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f54331)
#38 0x0000000005f470fa clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f470fa)
#39 0x000000000400fd28 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x400fd28)
#40 0x000000000427aad9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x427aad9)
#41 0x00000000041fa96e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41fa96e)
#42 0x0000000004359f5e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4359f5e)
#43 0x0000000000c013d6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc013d6)
#44 0x0000000000bf8c9a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#45 0x0000000004051049 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#46 0x00000000036da264 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x36da264)
#47 0x000000000405163f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#48 0x00000000040195b5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40195b5)
#49 0x000000000401a01d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x401a01d)
#50 0x0000000004021f45 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4021f45)
#51 0x0000000000bfe87c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbfe87c)
#52 0x0000000000af7b41 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xaf7b41)
#53 0x00007fbc92c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#54 0x00007fbc92c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#55 0x0000000000bf877e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf877e)
```
</details>

### PR DESCRIPTION
**Pull request by cor3ntin**
This implements the same overload resolution behavior as GCC, 
as described in https://wg21.link/p3606 (sections 1-2, not 3)

If, during overload resolution, a non-template candidate is always picked because each argument is a perfect match (i.e., the source and target types are the same), we do not perform deduction for any template candidate that might exist.

The goal is to be able to merge #122423 without being too disruptive.

This change means that the selection of the best viable candidate and template argument deduction become interleaved.

To avoid rewriting half of Clang, we store in `OverloadCandidateSet` enough information to deduce template candidates from `OverloadCandidateSet::BestViableFunction`. This means the lifetime of any object used by the template argument must outlive a call to `Add*Template*Candidate`.

This two-phase resolution is not performed for some initialization as there are cases where template candidates are a better match per the standard. It's also bypassed for code completion.

The change has a nice impact on compile times
https://llvm-compile-time-tracker.com/compare.php?from=719b029c16eeb1035da522fd641dfcc4cee6be74&to=bf7041045c9408490c395230047c5461de72fc39&stat=instructions%3Au .

Fixes #62096
Fixes #74581
Fixes #53454

### CODE REVIEW

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -10918,7 +11083,44 @@ bool OverloadCandidate::NotValidBecauseConstraintExprHasError() const {
...
+      return OR_Success;
+    }
+  }
+  InjectNonDeducedTemplateCandidates(S);
+  return BestViableFunctionImpl(S, Loc, Best);
+}
+
+OverloadingResult OverloadCandidateSet::BestViableFunctionImpl(
+    Sema &S, SourceLocation Loc, OverloadCandidateSet::iterator &Best) {
+
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaOverload.cpp:11121]: This is the meat of the change (that and the definition of `isPerfectMatch`)

File: clang/lib/Sema/SemaOverload.cpp [hunk 2]
```diff
@@ -10918,7 +11083,44 @@ bool OverloadCandidate::NotValidBecauseConstraintExprHasError() const {
 OverloadingResult
 OverloadCandidateSet::BestViableFunction(Sema &S, SourceLocation Loc,
                                          iterator &Best) {
+
+  bool TwoPhaseResolution =
+      !NonDeducedCandidates.empty() && Kind != CSK_CodeCompletion &&
+      Kind != CSK_InitByUserDefinedConversion && Kind != CSK_InitByConstructor;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:11089]: I must be missing something, are `CSK_InitByUserDefinedConversion` and `CSK_InitByConstructor` something special that we can't apply to them?

(explanations are appreciated!)

File: clang/lib/Sema/SemaOverload.cpp [hunk 3]
```diff
@@ -10918,7 +11083,44 @@ bool OverloadCandidate::NotValidBecauseConstraintExprHasError() const {
...
+    Best = end();
+    for (auto It = begin(); It != end(); ++It) {
+      if (It->isPerfectMatch(S.getASTContext())) {
+        if (Best == end()) {
+          Best = It;
+        } else {
+          Best = end();
+          break;
+        }
+      }
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:11101]: If there are two+ perfect matches, I presume the reason for going on adding template candidates is that we want every candidates to be present in the diagnostic?

File: clang/lib/Sema/SemaOverload.cpp [hunk 4]
```diff
@@ -10918,7 +11083,44 @@ bool OverloadCandidate::NotValidBecauseConstraintExprHasError() const {
...
+    }
+    if (Best != end()) {
+      Best->Best = true;
+      if (Best->Function && Best->Function->isDeleted())
+        return OR_Deleted;
+      if (auto *M = dyn_cast_or_null<CXXMethodDecl>(Best->Function);
+          Kind == CSK_AddressOfOverloadSet && M &&
+          M->isImplicitObjectMemberFunction()) {
+        return OR_No_Viable_Function;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:11110]: This does not look obvious to me. Can you explain?

File: clang/lib/Sema/SemaOverload.cpp [hunk 5]
```diff
@@ -10905,6 +10983,93 @@ bool OverloadCandidate::NotValidBecauseConstraintExprHasError() const {
...
+      CandidateSet, C.FunctionTemplate, C.FoundDecl,
+      /*ExplicitTemplateArgs=*/nullptr, C.Args, C.SuppressUserConversions,
+      C.PartialOverloading, C.AllowExplicit, C.IsADLCandidate, C.PO,
+      C.AggregateCandidateDeduction);
+}
+
+static void AddTemplateOverloadCandidate(
+    Sema &S, OverloadCandidateSet &CandidateSet,
+    NonDeducedConversionTemplateOverloadCandidate &&C) {
+  return S.AddTemplateConversionCandidateImmediately(
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:11055]: Can we reuse `InjectNonDeducedTemplateCandidates` for `*Immediately` functions or vice versa?

File: clang/lib/Sema/SemaOverload.cpp [hunk 6]
```diff
@@ -10975,9 +11176,8 @@ OverloadCandidateSet::BestViableFunction(Sema &S, SourceLocation Loc,
   if (Best == end())
     return OR_No_Viable_Function;
 
+  llvm::SmallVector<OverloadCandidate *, 4> PendingBest;
   llvm::SmallVector<const NamedDecl *, 4> EquivalentCands;
-
-  llvm::SmallVector<OverloadCandidate*, 4> PendingBest;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:10980]: unrelated changes (sorry for nitpicks at this point)

File: clang/lib/Sema/SemaOverload.cpp (hunk 2 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaOverload.cpp]: I fixed that / added comments

**Comment by cor3ntin** [comment]
I could use help understanding how to fix `clang/test/Templight/templight-empty-entries-fix.cpp` - it always eludes me how to make FileCheck happy @AaronBallman

File: clang/lib/Sema/SemaInit.cpp [hunk 7]
```diff
@@ -10043,12 +10043,19 @@ QualType Sema::DeduceTemplateSpecializationFromInitializer(
     //   When [...] the constructor [...] is a candidate by
     //    - [over.match.copy] (in all cases)
     if (TD) {
-      SmallVector<Expr *, 8> TmpInits;
-      for (Expr *E : Inits)
+
+      // As template candidates are not deduced immediately,
+      // persist the arry in the overload set.
```
Comment (Sirraide) [inline clang/lib/Sema/SemaInit.cpp:10048]:
```suggestion
      // persist the array in the overload set.
```

File: clang/lib/Sema/SemaOverload.cpp [hunk 8]
```diff
@@ -14689,18 +14934,24 @@ void Sema::LookupOverloadedBinOp(OverloadCandidateSet &CandidateSet,
   // rewritten candidates using these functions if necessary.
   AddNonMemberOperatorCandidates(Fns, Args, CandidateSet);
 
+  // As template candidates are not deduced immediately,
+  // persist the arry in the overload set.
```
Comment (Sirraide) [inline clang/lib/Sema/SemaOverload.cpp:14938]:
```suggestion
  // persist the array in the overload set.
```

**Review by Sirraide — COMMENTED** [review]
Just a few typos I noticed

File: clang/lib/Sema/SemaOverload.cpp [hunk 9]
```diff
@@ -10230,9 +10307,15 @@ Sema::AddArgumentDependentLookupCandidates(DeclarationName Name,
           /*AllowExplicit=*/true, ADLCallKind::UsesADL);
       if (CandidateSet.getRewriteInfo().shouldAddReversed(
               *this, Args, FTD->getTemplatedDecl())) {
+
+        // As template candidates are not deduced immediately,
+        // persist the arry in the overload set.
```
Comment (zygoloid) [inline clang/lib/Sema/SemaOverload.cpp:10312]:
```suggestion
        // persist the array in the overload set.
```

**Review by zygoloid — COMMENTED** [review]
I think we should do this. Even if WG21 decides that they only want to allow this and not require it, it seems like a good change that we stand a decent chance of reaching implementation consensus on.

File: clang/include/clang/Sema/Overload.h [hunk 10]
```diff
@@ -1126,7 +1208,8 @@ class Sema;
     OperatorRewriteInfo RewriteInfo;
 
     constexpr static unsigned NumInlineBytes =
-        24 * sizeof(ImplicitConversionSequence);
+        32 * sizeof(ImplicitConversionSequence);
```
Comment (zyn0217) [inline clang/include/clang/Sema/Overload.h:1211]: Can we add some comments? what causes us to change it from 24 -> 32

File: clang/lib/Sema/SemaOverload.cpp [hunk 11]
```diff
@@ -10933,27 +11096,100 @@ OverloadCandidateSet::BestViableFunction(Sema &S, SourceLocation Loc,
...
+
+  return BestViableFunctionImpl(S, Loc, Best);
+}
+
+void OverloadCandidateSet::PerfectViableFunction(
+    Sema &S, SourceLocation Loc, OverloadCandidateSet::iterator &Best) {
+
+  Best = end();
+  for (auto It = begin(); It != end(); ++It) {
+    if (It->isPerfectMatch(S.getASTContext())) {
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:11160]: maybe
```cpp
if (!It->isPerfectMatch(S.getASTContext()))
  continue;
```
to reduce the curley nesting.

File: clang/lib/Sema/SemaOverload.cpp [hunk 12]
```diff
@@ -14354,6 +14584,17 @@ ExprResult Sema::BuildOverloadedCallExpr(Scope *S, Expr *Fn,
   OverloadingResult OverloadResult =
       CandidateSet.BestViableFunction(*this, Fn->getBeginLoc(), Best);
 
+  // [C++23][over.call.func]
+  // if overload resolution selects a non-static member function,
+  // the call is ill-formed;
+  if (CSK == OverloadCandidateSet::CSK_AddressOfOverloadSet &&
+      Best != CandidateSet.end()) {
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:14591]: Hmmm. I'm surprised this wasn't caught until now. Do you have a test case? (or is this something copied from elsewhere?)

**Review by zyn0217 — COMMENTED** [review]
Thanks!

File: clang/lib/Sema/SemaOverload.cpp (hunk 12 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaOverload.cpp:14591]: nevermind I realized it is https://github.com/llvm/llvm-project/pull/133426#discussion_r2018513280 :P

File: clang/include/clang/Sema/Overload.h (hunk 10 above)
Comment (cor3ntin) [reply clang/include/clang/Sema/Overload.h:1214]: I added some. We may be storing additional data in the slab allocator ( When we need to keep the argument array expression around for deferred candidates), so I made the storage a tad bigger to accomodate.  There is no reason for this thing to not be quite large frankly. it's short lived

File: clang/lib/Sema/SemaInit.cpp (hunk 7 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaInit.cpp]: Copy-pasted in a whole bunch of places too!

File: clang/include/clang/Sema/Overload.h [hunk 13]
```diff
@@ -1116,17 +1197,22 @@ class Sema;
   private:
     SmallVector<OverloadCandidate, 16> Candidates;
     llvm::SmallPtrSet<uintptr_t, 16> Functions;
+    SmallVector<DeferredTemplateOverloadCandidate, 8> DeferredCandidates;
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:1200]: This is DEFINITELY cleaner, but a future 'optimization' here might store a single candidates list, then maintain a single 'index' to the first deferred candidate.  This would save a potential allocation/potentially improve perf, but at the expense of some complexity.  

I AM somewhat concerned about the increased size here though.  That SmallVector here is going to be HUGE, and Candidates is already quite large.  These are done often on the stack unfortunately, so this is going to have some effect on instantiation depth.

**Review by erichkeane — COMMENTED** [review]
I agree completely with Richard, we should just do this.  We have prior art (GCC), the standard currently permits it as an implementation strategy, and it is an improvement in basically EVERY way with mild/barely-justifiable downsides.

File: clang/include/clang/Sema/Overload.h (hunk 13 above)
Comment (cor3ntin) [reply clang/include/clang/Sema/Overload.h:1200]: I actually thought about that - but I have not implemented it yet.
Are the cases where we do a lot of overload resolution recursively that common?

Comment (erichkeane) [reply clang/include/clang/Sema/Overload.h:1200]: I recall Aaron I thought at one point working on reducing the overload-candidates size which showed great improvement, but that would have been ~9 months ago now.  I remember being surprised at how much of a difference it made.

File: clang/include/clang/Sema/Overload.h [hunk 14]
```diff
@@ -407,6 +407,18 @@ class Sema;
              Third == ICK_Identity;
     }
 
+    bool isPerfect(const ASTContext &C) const {
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:410]: I would LOVE a comment here, the implementation isn't particularly clear what is going on here.

File: clang/include/clang/Sema/Overload.h [hunk 15]
```diff
@@ -979,6 +995,20 @@ class Sema;
       return false;
     }
 
+    bool isPerfectMatch(const ASTContext &Ctx) const {
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:998]: `isPerfect` vs `isPerfectMatch` are... confusing.  Work to make these easier to understand together would be appreciated.

File: clang/include/clang/Sema/Overload.h [hunk 16]
```diff
@@ -1117,16 +1205,27 @@ class Sema;
     SmallVector<OverloadCandidate, 16> Candidates;
     llvm::SmallPtrSet<uintptr_t, 16> Functions;
 
-    // Allocator for ConversionSequenceLists. We store the first few of these
+    DeferredTemplateOverloadCandidate *FirstDeferredCandidate;
+    unsigned DeferredCandidatesCount : 8 * sizeof(unsigned) - 2;
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:1209]: isn't this size possibly different on platforms, and thus makes the `32` on 1227 unreliable?

File: clang/include/clang/Sema/Overload.h [hunk 17]
```diff
@@ -1015,6 +1045,62 @@ class Sema;
           RewriteKind(CRK_None) {}
   };
 
+  struct DeferredTemplateOverloadCandidate {
+    DeferredTemplateOverloadCandidate *Next = nullptr;
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:1049]: Comment here + on the slab allocator function as to WHY we are doing this instead of a std::vector/etc would probably be helpful.  I understand it, but I probably won't next time I see this code ;)

File: clang/include/clang/Sema/Overload.h [hunk 18]
```diff
@@ -1159,12 +1256,29 @@ class Sema;
       return reinterpret_cast<T *>(FreeSpaceStart);
     }
 
+    template <typename T> T *allocateDeferredCandidate() {
+      T *C = slabAllocate<T>(1);
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:1260]: Seems funny to me to `slab` allocate in increments of 1.  I have a 'silly' idea... Since 'deferred candidates' are likely to only be a handful per lookup... I wonder if we could:

1- Add a few-bits to `DeferredTemplateOverloadCandidate` for `leftInSlab`.  
2- on `!FirstDeferredCandidate`, allocate (say)4 items.  Set the 1st item to '3' left.
3- Then, find the last candidate the same way.  if `leftInSlab` != 0, emplacement-new/etc into the 'next' location, set the `leftInSlab` to be the previous `-1`.  If `leftInSlab == 0`, allocate.

I realize it is more work here, and can be done in a followup, but there might be a mild perf improvement for cache locality.  I suspect if we set this to something like 4, which requires 2 bits in the structure, high-90%s of lookups will take only 1 allocation.

WDYT?

**Review by erichkeane — COMMENTED** [review]
A few mean comments, but the approach still seems solid here.  I think this is a solid patch

File: clang/include/clang/Sema/Overload.h (hunk 16 above)
Comment (cor3ntin) [reply clang/include/clang/Sema/Overload.h:1209]: The 32 on line 1227 is super arbitrary and not tied to the size of `unsigned`.
It did felt worth making bigger as we are now storing more than conversion sequences in the overload set.

File: clang/include/clang/Sema/Overload.h (hunk 14 above)
Comment (erichkeane) [reply clang/include/clang/Sema/Overload.h:410]: Still would like comments on these functions that say what 'perfect' means here.

File: clang/include/clang/Sema/Overload.h [hunk 19]
```diff
@@ -743,6 +759,13 @@ class Sema;
       Standard.setAllToTypes(T);
     }
 
+    /// A conversion sequence is perfect if
+    /// it is an identity conversion and
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h:763]: your formatting of this comment is a little weird re-newlines.

File: clang/include/clang/Sema/Sema.h [hunk 20]
```diff
@@ -10382,6 +10383,7 @@ class Sema final : public SemaBase {
   /// Add a C++ function template specialization as a candidate
   /// in the candidate set, using template argument deduction to produce
   /// an appropriate function template specialization.
+
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:10386]: Pretty sure we don't want this :)

**Review by erichkeane — APPROVED** [review]
I have a handful of comments that are all nits/minor enough I trust you on, but overall this looks fine. 

Lets ship it!

File: clang/include/clang/Sema/Overload.h [hunk 21]
```diff
@@ -1043,6 +1141,8 @@ class Sema;
       /// C++ [over.match.call.general]
       /// Resolve a call through the address of an overload set.
       CSK_AddressOfOverloadSet,
+
+      CSK_CodeCompletion,
```
[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/include/clang/Sema/Overload.h:1145]: Ah, I see.  Can you clarify that in a comment above this as to why this is a separate category?  It was pretty jarring to see in general, let alone here.

File: clang/include/clang/Sema/Overload.h (hunk 18 above)
Comment (erichkeane) [reply clang/include/clang/Sema/Overload.h:1277]: Thinking further, the whole point of the slab is to put all the stuff in the same location, so this is a silly suggestion.  Disregard.

File: clang/include/clang/Sema/Overload.h [hunk 22]
```diff
@@ -1216,6 +1352,24 @@ class Sema;
...
+    llvm::MutableArrayRef<Expr *> getPersistentArgsArray(unsigned N) {
+      Expr **Exprs = slabAllocate<Expr *>(N);
+      return llvm::MutableArrayRef<Expr *>(Exprs, N);
+    }
+
+    template <typename... T>
+    llvm::MutableArrayRef<Expr *> getPersistentArgsArray(T *...Exprs) {
+      llvm::MutableArrayRef<Expr *> Arr =
+          getPersistentArgsArray(sizeof...(Exprs));
+      llvm::copy(std::initializer_list<Expr *>{Exprs...}, Arr.data());
```
[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/include/clang/Sema/Overload.h:1371]: ah, hrmph, thats unfortunate.  There is _A_ good reason that was brought up on me in the past, but everything I can remember/think of is sort of a "well, i guess it is 'more' correct'" when it comes to pointers. So don't change it here, as the init-list stuff makes it more error prone.

File: clang/lib/Sema/SemaOverload.cpp [hunk 23]
```diff
@@ -7919,7 +7951,7 @@ void Sema::AddTemplateOverloadCandidate(
     Candidate.Function = FunctionTemplate->getTemplatedDecl();
     Candidate.Viable = false;
     Candidate.RewriteKind =
-      CandidateSet.getRewriteInfo().getRewriteKind(Candidate.Function, PO);
+        CandidateSet.getRewriteInfo().getRewriteKind(Candidate.Function, PO);
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:7954]: unrelated?

File: clang/lib/Sema/SemaOverload.cpp [hunk 24]
```diff
@@ -7834,7 +7838,7 @@ void Sema::AddMethodTemplateCandidate(
     Candidate.Function = MethodTmpl->getTemplatedDecl();
     Candidate.Viable = false;
     Candidate.RewriteKind =
-      CandidateSet.getRewriteInfo().getRewriteKind(Candidate.Function, PO);
+        CandidateSet.getRewriteInfo().getRewriteKind(Candidate.Function, PO);
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:7841]: ditto

File: clang/lib/Sema/SemaOverload.cpp [hunk 25]
```diff
@@ -45,6 +45,7 @@
 #include <cstddef>
 #include <cstdlib>
 #include <optional>
+#include <variant>
```
Comment (zyn0217) [inline clang/lib/Sema/SemaOverload.cpp:48]: We no longer use variant, right?

**Review by zyn0217 — APPROVED** [review]
Some nits, and thanks for helping us in this area!

**Comment by nikic** [comment]
The final version had a 4% improvement on clang bootstrap: https://llvm-compile-time-tracker.com/compare.php?from=23324b8b109aed1f77cb20cef476b795f33b6835&to=8c5a307bd8d406e6167a5cd3ce3c74e2e3bfb2a6&stat=instructions:u

Wow.
