### PR TITLE
[PowerPC] Fix handling of undefs in the PPC::isSplatShuffleMask query

### LINKED ISSUE #141642: PowerPC regressions introduce by 3469db82b5c821c94b58c0b81f03bbef51efa30b
I'm seeing a test failure in our Fedora builds of the [highway]( https://github.com/google/highway) package on ppc64le, and I've bisected the failures down to 3469db82b5c821c94b58c0b81f03bbef51efa30b (#108430) 

How to reproduce in the `fedora:rawhide` container for ppc64le:

```
$ curl -O -L https://download.copr.fedorainfracloud.org/results/tstellar/clang-fedora-centos-testing/fedora-rawhide-ppc64le/09017423-highway/highway-1.2.0-5.fc43.src.rpm
$ dnf builddep highway-1.2.0-5.fc43.src.rpm
$ dnf install rpm-build
$ rpmbuild -D "%_distro_extra_ldflags -fuse-ld=lld" -rb highway-1.2.0-5.fc43.src.rpm
```

cc @alexey-bataev

### PR DESCRIPTION
**Pull request by w2yehia**
Currently, the query assumes that a single undef byte implies the rest of the `EltSize - 1` bytes are undefs, but that's not always true.
e.g. isSplatShuffleMask( <0,1,2,3,4,5,6,7,undef,undef,undef,undef,0,1,2,3>,   8) should return false.

### CODE REVIEW

File: llvm/lib/Target/PowerPC/PPCISelLowering.cpp [hunk 1]
```diff
@@ -2242,10 +2242,15 @@ bool PPC::isSplatShuffleMask(ShuffleVectorSDNode *N, unsigned EltSize) {
       return false;
 
   for (unsigned i = EltSize, e = 16; i != e; i += EltSize) {
-    if (N->getMaskElt(i) < 0) continue;
-    for (unsigned j = 0; j != EltSize; ++j)
-      if (N->getMaskElt(i+j) != N->getMaskElt(j))
-        return false;
+    // An UNDEF element is a sequence of UNDEF bits.
```
Comment (RolandF77) [inline llvm/lib/Target/PowerPC/PPCISelLowering.cpp]: These are bytes, not bits.

**Review by RolandF77 — APPROVED** [review]
Please fix comment, but otherwise LGTM.
