### PR TITLE
[AArch64] Disable loop alignment for Windows targets

### LINKED ISSUE #66912: fatal error: error in backend: Failed to evaluate function length in SEH unwind info
I've encountered a crash of clang from LLVM 17.01 when trying to build openblas 0.3.24 for Windows/aarch64 on a Linux machine. The crash files and full output with stacktrace are attached in [crash.zip](https://github.com/llvm/llvm-project/files/12674259/crash.zip)

The output includes:

fatal error: error in backend: Failed to evaluate function length in SEH unwind info

#5 0x00005579fe4a4f70 llvm::report_fatal_error(llvm::Twine const&, bool) (/home/tomas/toolchain/clang/toolchain_libs/mxe/usr/x86_64-pc-linux-gnu/bin/clang+0x1c72f70)
 #8 0x00005579fe2627dd llvm::MCStreamer::emitWinCFIEndProc(llvm::SMLoc) (/home/tomas/toolchain/clang/toolchain_libs/mxe/usr/x86_64-pc-linux-gnu/bin/clang+0x1a307dd)
#11 0x00005579ff1be469 llvm::AsmPrinter::emitFunctionBody() (/home/tomas/toolchain/clang/toolchain_libs/mxe/usr/x86_64-pc-linux-gnu/bin/clang+0x298c469)
#14 0x00005579fdff2eea llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/tomas/toolchain/clang/toolchain_libs/mxe/usr/x86_64-pc-linux-gnu/bin/clang+0x17c0eea)

### PR DESCRIPTION
**Pull request by mstorsjo**
This should fix #66912. When emitting SEH unwind info, we need to be able to calculate the exact length of functions before alignments are fixed. Until that limitation is overcome, just disable all loop alignment on Windows targets.

### CODE REVIEW

File: llvm/lib/MC/MCWin64EH.cpp [hunk 1]
```diff
@@ -1402,6 +1402,9 @@ static void ARM64EmitUnwindInfo(MCStreamer &streamer, WinEH::FrameInfo *info,
     // here, but we'd have to emit the pdata, the xdata header, and the
     // epilogue scopes later, since they depend on whether the we need to
     // split the unwind data.
+    //
+    // If this is fixed, remove code in AArch64ISelLowering.cpp that
```
Comment (DavidSpickett) [inline llvm/lib/MC/MCWin64EH.cpp:1406]: What's "this" here and what would "fixed" mean. Maybe it needs a "see <link>". As out of the context of this PR it doesn't make much sense.

File: llvm/test/CodeGen/AArch64/sched-loop-align.ll [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  br label %for.cond
+
+for.cond:
+  tail call void @a()
+  br label %for.cond
+}
+
+declare dso_local void @a(...)
+
+attributes #0 = { noreturn nounwind uwtable "tune-cpu"="cortex-a53" }
```
Comment (DavidSpickett) [inline llvm/test/CodeGen/AArch64/sched-loop-align.ll:15]: Nit but do you need a tune-cpu setting?

File: llvm/lib/MC/MCWin64EH.cpp (hunk 1 above)
Comment (mstorsjo) [reply llvm/lib/MC/MCWin64EH.cpp:1406]: This is a large comment block, that starts out with:
```
    // FIXME: GetAbsDifference tries to compute the length of the function
    // immediately, before the whole file is emitted, but in general
    // that's impossible: the size in bytes of certain assembler directives
    // like .align and .fill is not known until the whole file is parsed and
    // relaxations are applied. Currently, GetAbsDifference fails with a fatal
    // error in that case.
```
(And then goes on about potential ways of fixing it.) So this comment says that if this whole general issue/limitation is fixed, we can remove this tweak.

File: llvm/test/CodeGen/AArch64/sched-loop-align.ll (hunk 2 above)
Comment (mstorsjo) [reply llvm/test/CodeGen/AArch64/sched-loop-align.ll:15]: Kinda, although it's probably testable differently too. The issue I'm fixing, #66912, is that `-mtune=cortex-a53` did get added loop alignment in 7d676714fbf2dd4bcdd15bd63d6b43b467ceccb1 - which is what broke things. This test uses that tune in order to trigger the issue. I guess it could be tested a bit more explicitly with a direct option to `llc` as well; but if we'd pass an option requesting an explicit loop alignment (if there's such a thing?), things would break - the point here is that we want to disable the implicit loop alignment for these targets.

**Review by DavidSpickett — APPROVED** [review]
