### PR TITLE
[Clang] Fix handling of references to variable templates with an empty argument list

### LINKED ISSUE #191016: [Clang] [Regression] Constraint satisfaction fails for funcion constrained by member variable template with empty variadic/defaulted arguments
The following code fails to compile in Clang trunk/22 but works on 21:

([godbolt](https://godbolt.org/z/dsbEqErW7), [conformance](https://godbolt.org/z/nfox5o377))
```cpp
template<typename T = int>
struct S {
	// template<typename Args = int>
	// constexpr static bool P = true;

	template<typename... Args>
	constexpr static bool Q = true;

	// S() requires P<> {}
	S() requires Q<> {}
};

int main() {
	S s;
}
```
```cmd
error: use of variable template 'Q' requires template arguments
```

Fails with bots parameter pack and defaulted parameter.

### PR DESCRIPTION
**Pull request by cor3ntin**
In some cases they were treated as having no argument list at all.

Fixes #191016.

### CODE REVIEW

File: clang/include/clang/AST/ExprCXX.h [hunk 1]
```diff
@@ -3281,12 +3281,14 @@ class OverloadExpr : public Expr {
   bool hasExplicitTemplateArgs() const {
     if (!hasTemplateKWAndArgsInfo())
       return false;
+    if (getLAngleLoc().isValid())
+      return true;
```
Comment (zyn0217) [inline clang/include/clang/AST/ExprCXX.h]: The FIXME on line 3286 looks fishy, I'm confused if we have any tests for that cases.

Also, I wonder if we have messed up with NumTemplateArgs since clang 22. Where does this diagnostic come from, normalization or substitution?

Comment (cor3ntin) [reply clang/include/clang/AST/ExprCXX.h]: Note this might have been broken by concept template parameters, but it has nothing to do with constraint checking or normalization

**Review by zyn0217 — APPROVED** [review]
Thanks

File: clang/include/clang/AST/ExprCXX.h [hunk 2]
```diff
@@ -3279,14 +3279,10 @@ class OverloadExpr : public Expr {
...
-      return false;
-    // FIXME: deduced function types can have "hidden" args and no <
-    // investigate that further, but ultimately maybe we want to model concepts
-    // reference with another kind of expression.
-    return (isConceptReference() || isVarDeclReference())
-               ? getTrailingASTTemplateKWAndArgsInfo()->NumTemplateArgs
-               : getLAngleLoc().isValid();
+    if (getLAngleLoc().isValid())
+      return true;
+    return hasTemplateKWAndArgsInfo() &&
```
Comment (shafik) [inline clang/include/clang/AST/ExprCXX.h:3284]: So `getLAngleLoc()` starts w/ `!hasTemplateKWAndArgsInfo()` and so it is a bit unclear going through the code paths what this is checking for in totality. It seems like it is worth a more extended comment.

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -426,6 +426,7 @@ Bug Fixes to C++ Support
   template parameters when one of its parameters is also a pack. (#GH181166)
 - Fixed a crash when a default argument is passed to an explicit object parameter. (#GH176639)
 - Fixed an alias template CTAD crash.
+- Fix handling of ``Var<>`` when refering to a static member variable template. (#GH191016)
```
[the remark this answers is not in the document]
Comment (frederick-vs-ja) [reply clang/docs/ReleaseNotes.rst]: There's a recent bug report (#191154) where the bug is possibly fixed by this. I want to backport the patch.

**Comment by DiegoBaldassarMilleuno** [comment]
@frederick-vs-ja @zyn0217 I just tested on clang 22.1.8 and the same bugs as reported by #197408 and #191016 are still present there. On 23.1.0 it's fixed. It seems that there was the intention to backport to clang 22, but it was never done AFAICT. Maybe it was forgotten? Pinging just in case.
