### PR TITLE
[libc][POSIX][poll.h] implement poll

### LINKED ISSUE #124647: [libc][POSIX] implement poll from poll.h
building clang against llvm-libc fails with:
```
llvm-project-main/llvm/lib/Support/raw_socket_stream.cpp:24:10: fatal error: 'poll.h' file not found.
   24 | #include <poll.h>
      |           ^~~~~~~~
```
it looks like `poll` is used.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Simple syscall.

Fixes: #124647

### CODE REVIEW

File: libc/src/poll/linux/poll.cpp [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+#include "src/__support/common.h"
+#include "src/__support/macros/config.h"
+#include "src/errno/libc_errno.h"
+
+#include <sys/syscall.h> // SYS_poll
+
+namespace LIBC_NAMESPACE_DECL {
+
+LLVM_LIBC_FUNCTION(int, poll, (struct pollfd * fds, nfds_t nfds, int timeout)) {
+  int ret = LIBC_NAMESPACE::syscall_impl<int>(SYS_poll, fds, nfds, timeout);
```
Comment (nickdesaulniers) [inline libc/src/poll/linux/poll.cpp:23]: Looks like SYS_poll does not exist for all architectures.
https://gpages.juszkiewicz.com.pl/syscalls-table/syscalls.html
I think we can fall back to `SYS_ppoll` in that case.

Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp:23]: Also, looks like there's a newer ppoll_time64...

File: libc/test/src/poll/poll_test.cpp [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+//
+//===----------------------------------------------------------------------===//
+
+#include "src/errno/libc_errno.h"
+#include "src/poll/poll.h"
+#include "test/UnitTest/Test.h"
+
+TEST(LlvmLibcPollTest, SmokeTest) {
+  LIBC_NAMESPACE::libc_errno = 0;
+  int ret = LIBC_NAMESPACE::poll(nullptr, 0, 0);
```
Comment (michaelrj-google) [inline libc/test/src/poll/poll_test.cpp:15]: ideally there'd also be a test that fails, to make sure both branches are exercised.

**Review by michaelrj-google — COMMENTED** [review]
overall LGTM

File: libc/src/poll/linux/poll.cpp (hunk 1 above)
Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp:26]: a860748c9d56. Will omit ppoll_time64 since that will only help riscv32 at the moment.

File: libc/test/src/poll/poll_test.cpp (hunk 2 above)
Comment (nickdesaulniers) [reply libc/test/src/poll/poll_test.cpp:16]: 19e043956d2926a405d1f261989176741e76ab6b

File: libc/src/poll/linux/CMakeLists.txt [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+  poll
+  SRCS
+    poll.cpp
+  HDRS
+    ../poll.h
+  DEPENDS
+    libc.hdr.types.nfds_t
+    libc.hdr.types.struct_pollfd
+    libc.hdr.types.struct_timespec
+    libc.include.poll
```
Comment (nickdesaulniers) [inline libc/src/poll/linux/CMakeLists.txt:11]: This is not correct. Instead, I should put this line exactly in libc/config/linux/{arch}/headers.txt.

via https://github.com/llvm/llvm-project/issues/125102#issuecomment-2625933083

Comment (nickdesaulniers) [reply libc/src/poll/linux/CMakeLists.txt]: 6fc7519871b6

**Comment by nickdesaulniers** [comment]
ping for review

File: libc/src/poll/linux/poll.cpp [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+#include "src/__support/OSUtil/syscall.h" // syscall_impl
+#include "src/__support/common.h"
+#include "src/__support/macros/config.h"
+#include "src/errno/libc_errno.h"
+
+#include <sys/syscall.h> // SYS_poll, SYS_ppoll
+
+namespace LIBC_NAMESPACE_DECL {
+
+LLVM_LIBC_FUNCTION(int, poll, (struct pollfd * fds, nfds_t nfds, int timeout)) {
```
Comment (lntue) [inline libc/src/poll/linux/poll.cpp:23]: nit: `struct` is not needed.

File: libc/src/poll/poll.h [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+#ifndef LLVM_LIBC_SRC_POLL_POLL_H
+#define LLVM_LIBC_SRC_POLL_POLL_H
+
+#include "hdr/types/nfds_t.h"
+#include "hdr/types/struct_pollfd.h"
+#include "src/__support/macros/config.h"
+
+namespace LIBC_NAMESPACE_DECL {
+
+int poll(struct pollfd *fds, nfds_t nfds, int timeout);
```
Comment (lntue) [inline libc/src/poll/poll.h:18]: nit: `struct` is not needed.

File: libc/src/poll/linux/poll.cpp (hunk 4 above)
Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp:23]: heh, can you tell I still default to C sometimes..?

Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp]: 9fbba8a4ffb8

File: libc/src/poll/poll.h (hunk 5 above)
Comment (nickdesaulniers) [reply libc/src/poll/poll.h]: 9fbba8a4ffb8

**Review by lntue — APPROVED** [review]

File: libc/src/poll/linux/poll.cpp [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+    ts.tv_sec = timeout / 1000;
+    ts.tv_nsec = (timeout % 1000) * 1000000;
+    tsp = &ts;
+  } else {
+    tsp = nullptr;
+  }
+  int ret =
+      LIBC_NAMESPACE::syscall_impl<int>(SYS_ppoll, fds, nfds, tsp, nullptr, 0);
+#else
+#error "SYS_ppoll_time64?"
```
[the remark this answers is not in the document]
Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp:39]: https://github.com/llvm/llvm-project/issues/125940

[the remark this answers is not in the document]
Comment (nickdesaulniers) [reply libc/src/poll/linux/poll.cpp:39]: #125941
