### PR TITLE
[Clang][Concepts] Normalize SizeOfPackExpr's pack declaration

### LINKED ISSUE #93099: [clang] Bug with constraints when using nested classes and sizeof causing compilation failure of GNU ranges library
Newer versions of the library compile due to a workaround in the library for clang. I think the issue described below is still a bug though.

Short reproducer - https://godbolt.org/z/1qzac3vEj

```
template<typename T=int>
class bg {
public:
  template <int... h>
      requires (sizeof...(h) > 0) friend class l;
};
template <int... h>
    requires (sizeof...(h) > 0) class l;
void m() { bg v; } 
```

You need the nested class in a template (https://godbolt.org/z/1qzac3vEj) and sizeof (https://godbolt.org/z/3exhT3ahh) to reproduce this. 

It might be related to https://github.com/llvm/llvm-project/issues/61763

### PR DESCRIPTION
**Pull request by zyn0217**
SizeOfPackExpr has a pointer to the referenced pack declaration, which is left as-is during the transformation process.

The situation could be subtle when a friend class template declaration comes into play. The declaration per se would be instantiated into its parent declaration context, and consequently, the template parameter list would have a depth adjustment; however, as we don't evaluate constraints during instantiation, those constraints would still reference the original template parameters, which is fine for constraint evaluation because we have handled friend cases in the template argument collection.

However, things are different when we want to profile the constraint expression with dependent template arguments. The hash algorithm of SizeOfPackExpr takes its pack declaration as a factor, which is the original template parameter that might still have untransformed template depths after the constraint normalization.

This patch transforms the pack declaration when normalizing constraint expressions and pluses a fix in HandleFunctionTemplateDecl() where the associated declaration is incorrect for nested specifiers.

Note that the fix in HandleFunctionTemplateDecl(), as well as the handling logic for NestedNameSpecifier, would be removed once Krystian's refactoring patch lands. But I still want to incorporate it in the patch for the correction purpose, though it hasn't caused any problems so far - I just tripped over that in getFullyPackExpandedSize() when I tried to extract the transformed declarations from the TemplateArgument.

Fixes #93099

### CODE REVIEW

**Comment by zyn0217** [comment]
The CI failure looks unrelated - it also *failed* in other PRs e.g.

https://buildkite.com/llvm-project/github-pull-requests/builds/104957#019238e6-fd32-40a1-987a-4cd1c539926a

(Which happens to fail in `std::common_type` that might have connections with the `sizeof...` expression)

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -1722,6 +1722,32 @@ namespace {
...
+        return inherited::RebuildSizeOfPackExpr(OperatorLoc, Pack, PackLoc,
+                                                RParenLoc, Length, PartialArgs);
+
+#ifndef NDEBUG
+      for (auto *Iter = TemplateArgs.begin(); Iter != TemplateArgs.end();
+           ++Iter)
+        for (const TemplateArgument &TA : Iter->Args)
+          assert(TA.getKind() != TemplateArgument::Pack || TA.pack_size() == 1);
+#endif
+      Sema::ArgumentPackSubstitutionIndexRAII SubstIndex(SemaRef, 0);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1741]:
```suggestion
      Sema::ArgumentPackSubstitutionIndexRAII SubstIndex(SemaRef, /*NewSubstitutionIndex=*/0);
```
Though why is the Substitution index always 0 here?

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 2]
```diff
@@ -1722,6 +1722,32 @@ namespace {
...
+          Sema::CodeSynthesisContext::ConstraintNormalization)
+        return inherited::RebuildSizeOfPackExpr(OperatorLoc, Pack, PackLoc,
+                                                RParenLoc, Length, PartialArgs);
+
+#ifndef NDEBUG
+      for (auto *Iter = TemplateArgs.begin(); Iter != TemplateArgs.end();
+           ++Iter)
+        for (const TemplateArgument &TA : Iter->Args)
+          assert(TA.getKind() != TemplateArgument::Pack || TA.pack_size() == 1);
+#endif
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1740]: Is this assert really only relevant during Constraint Normalization?

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1741]: That is used for transforming TemplateTemplateParmDecls e.g. in the following case:
```cpp
template <template <typename> class... TTp>
    requires(sizeof...(TTp) > 0)
  friend class TTP;
```
The TTP here is a ParameterPack, and our transformation assumes a non-negative ArgumentPackSubstitutionIndex. Fortunately, we can always expand it to the first element during the normalization because we would have only one (injected) template argument for the pack.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 2 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1740]: I think so - the template arguments are in fact `getInjectedTemplateArgs()`'ed from template parameters, which ensure the pack size.

(I think I'm making sure setting ArgumentPackSubstitutionIndex to 0 is right later)

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks!
