### PR TITLE
[libc][sched] Implement `CPU_ZERO`, `CPU_ISSET`, `CPU_SET` macros

### LINKED ISSUE #124642: [libc][sched] missing macros `CPU_ZERO`, `CPU_ISSET`, and `CPU_SET`
building clang against llvm-libc fails with:
```
In file included from /llvm-project-main/llvm/lib/Support/Threading.cpp:67:
/llvm-project-main/llvm/lib/Support/Unix/Threading.inc:348:3: error: use of undeclared identifier 'CPU_ZERO'
  348 |   CPU_ZERO(&Enabled);
      |   ^
/llvm-project-main/llvm/lib/Support/Unix/Threading.inc:380:11: error: use of undeclared identifier 'CPU_ISSET'
  380 |       if (CPU_ISSET(CurProcessor, &Affinity))
      |           ^
/llvm-project-main/llvm/lib/Support/Unix/Threading.inc:381:9: error: use of undeclared identifier 'CPU_SET'
  381 |         CPU_SET(CurPhysicalId * CurSiblings + CurCoreId, &Enabled);
      |         ^

```
looks like these are macros we'd probably need to define in libc/include/llvm-libc-macros/linux/sched-macros.h.

### PR DESCRIPTION
**Pull request by krishna2803**
This PR implements the following macros for `sched.h`:
- `CPU_ZERO`
- `CPU_ISSET`
- `CPU_SET`

Fixes #124642

### CODE REVIEW

**Comment by krishna2803** [comment]
@jhuber6 @lntue could you please review this

File: libc/include/llvm-libc-types/cpu_set_t.h [hunk 1]
```diff
@@ -9,6 +9,9 @@
 #ifndef LLVM_LIBC_TYPES_CPU_SET_T_H
 #define LLVM_LIBC_TYPES_CPU_SET_T_H
 
+#define __CPU_SETSIZE 1024
+#define __NCPUBITS 8 * sizeof(unsigned long)
```
Comment (jhuber6) [inline libc/include/llvm-libc-types/cpu_set_t.h:13]: Does this need parens?

Comment (krishna2803) [reply libc/include/llvm-libc-types/cpu_set_t.h]: fixed in [c94712f1](https://github.com/llvm/llvm-project/pull/131524/commits/c94712f13285a9657e35f982e081e4c28ec12b69)

File: libc/src/sched/linux/sched_getcpuisset.cpp [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+namespace LIBC_NAMESPACE_DECL {
+
+LLVM_LIBC_FUNCTION(int, __sched_getcpuisset,
+                   (int cpu, const size_t cpuset_size, cpu_set_t *set)) {
+  if (static_cast<size_t>(cpu) / 8 < cpuset_size) {
+    const size_t element_index = static_cast<size_t>(cpu) / NCPUBITS;
+    const size_t bit_position = static_cast<size_t>(cpu) % NCPUBITS;
+
+    const unsigned long mask = 1UL << bit_position;
+    return (set->__mask[element_index] & mask) != 0;
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/src/sched/linux/sched_getcpuisset.cpp:27]: these macros are [glibc extensions](https://man7.org/linux/man-pages/man3/CPU_SET_S.3.html), the man page itself doesn't define a way to deal with null pointers. i found an implementation of those in [glibc's code](https://codebrowser.dev/glibc/glibc/posix/bits/cpu-set.h.html) and surprisingly even that _doesn't_ handle null pointers. ref:

```c
#define __CPU_ISSET_S(cpu, setsize, cpusetp) \
  (__extension__							      \
   ({ size_t __cpu = (cpu);						      \
      __cpu / 8 < (setsize)						      \
      ? ((((const __cpu_mask *) ((cpusetp)->__bits))[__CPUELT (__cpu)]	      \
	  & __CPUMASK (__cpu))) != 0					      \
      : 0; }))
```

for implementing these macros (`CPU_ZERO` et al), i looked at our existing implementation for `CPU_COUNT` ref:
https://github.com/llvm/llvm-project/blob/c94712f13285a9657e35f982e081e4c28ec12b69/libc/src/sched/linux/sched_getcpucount.cpp#L19-L26  

and even that doesn't handle null pointers!

---
should i implement a nullptr guard for these?

[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/src/sched/linux/sched_getcpuisset.cpp:30]: done! [522c6697](https://github.com/llvm/llvm-project/pull/131524/commits/522c6697db9d9d8072dc3ecb190ebe71a853a145)

**Review by RossComputerGuy — APPROVED** [review]

File: libc/src/sched/linux/sched_getcpuisset.cpp [hunk 3]
```diff
@@ -8,8 +8,9 @@
 
 #include "src/sched/sched_getcpuisset.h"
 
-#include "src/__support/common.h"        // LLVM_LIBC_FUNCTION
-#include "src/__support/macros/config.h" // LIBC_NAMESPACE_DECL
+#include "src/__support/common.h"            // LLVM_LIBC_FUNCTION
```
Comment (lntue) [inline libc/src/sched/linux/sched_getcpuisset.cpp:11]: Nit: Update the cmake dependency of these targets.

Comment (krishna2803) [reply libc/src/sched/linux/sched_getcpuisset.cpp:11]: done! [9b0d165e](https://github.com/llvm/llvm-project/pull/131524/commits/9b0d165e9f752b3e82c9bfc836c55a596d64104b)

**Review by lntue — APPROVED** [review]
