### PR TITLE
[libc] Use proxy headers for `limits.h` values

### LINKED ISSUE #102368: libc fails to build on `error "Assumed value of MB_LEN_MAX wrong"`
On linux ubuntu mantic arm64:
https://llvm-jenkins.debian.net/job/llvm-toolchain-mantic-binaries/architecture=arm64,distribution=mantic,label=arm64/592/consoleFull

```

FAILED: libc/src/math/generic/CMakeFiles/libc.src.math.generic.daddf128.dir/daddf128.cpp.o
/build/source/build-llvm/./bin/clang++ --target=aarch64-unknown-linux-gnu -DLIBC_NAMESPACE=__llvm_libc_20_0_0_ -I/build/source/libc -isystem /build/source/build-llvm/runtimes/runtimes-bins/libc/include -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -fdebug-prefix-map=/build/source/= -no-canonical-prefixes -ffile-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -O3 -DNDEBUG -std=gnu++17 -DLIBC_QSORT_IMPL=LIBC_QSORT_QUICK_SORT -fpie -ffixed-point -fno-builtin -fno-exceptions -fno-lax-vector-conversions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -Wall -Wextra -Werror -Wconversion -Wno-sign-conversion -Wimplicit-fallthrough -Wwrite-strings -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wstrict-prototypes -Wthread-safety -Wglobal-constructors -O3 -DLIBC_COPT_PUBLIC_PACKAGING -MD -MT libc/src/math/generic/CMakeFiles/libc.src.math.generic.daddf128.dir/daddf128.cpp.o -MF libc/src/math/generic/CMakeFiles/libc.src.math.generic.daddf128.dir/daddf128.cpp.o.d -o libc/src/math/generic/CMakeFiles/libc.src.math.generic.daddf128.dir/daddf128.cpp.o -c /build/source/libc/src/math/generic/daddf128.cpp
In file included from /build/source/libc/src/math/generic/daddf128.cpp:10:
In file included from /build/source/libc/src/__support/FPUtil/generic/add_sub.h:17:
In file included from /build/source/libc/src/__support/FPUtil/BasicOperations.h:12:
In file included from /build/source/libc/src/__support/FPUtil/FEnvImpl.h:13:
In file included from /build/source/libc/hdr/math_macros.h:23:
In file included from /usr/lib/gcc/aarch64-linux-gnu/13/../../../../include/c++/13/math.h:36:
In file included from /usr/lib/gcc/aarch64-linux-gnu/13/../../../../include/c++/13/cmath:49:
In file included from /usr/lib/gcc/aarch64-linux-gnu/13/../../../../include/c++/13/bits/std_abs.h:38:
In file included from /usr/include/stdlib.h:1159:
/usr/include/aarch64-linux-gnu/bits/stdlib.h:86:3: error: "Assumed value of MB_LEN_MAX wrong"
   86 | # error "Assumed value of MB_LEN_MAX wrong"
      |   ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
This defines some constants that may conflict with the system when in
overlay mode. Use the proxy header instead.

Fixes: https://github.com/llvm/llvm-project/issues/102368

### CODE REVIEW

File: libc/src/__support/CPP/limits.h [hunk 1]
```diff
@@ -9,10 +9,10 @@
 #ifndef LLVM_LIBC_SRC___SUPPORT_CPP_LIMITS_H
 #define LLVM_LIBC_SRC___SUPPORT_CPP_LIMITS_H
 
-#include "include/llvm-libc-macros/limits-macros.h" // CHAR_BIT
+#include "hdr/limits-macros.h" // CHAR_BIT
```
Comment (michaelrj-google) [inline libc/src/__support/CPP/limits.h:12]:
```suggestion
#include "hdr/limits_macros.h" // CHAR_BIT
```

**Review by michaelrj-google — APPROVED** [review]
Overall LGTM but also remember to update the cmake and the bazel. Here's the diff that fixes the bazel:
``` diff
diff --git a/utils/bazel/llvm-project-overlay/libc/BUILD.bazel b/utils/bazel/llvm-project-overlay/libc/BUILD.bazel
index 253b89216a88..e52bf2782638 100644
--- a/utils/bazel/llvm-project-overlay/libc/BUILD.bazel
+++ b/utils/bazel/llvm-project-overlay/libc/BUILD.bazel
@@ -150,6 +150,12 @@ libc_support_library(
     hdrs = ["hdr/stdio_macros.h"],
 )
 
+
+libc_support_library(
+    name = "hdr_limits_macros",
+    hdrs = ["hdr/limits_macros.h"],
+)
+
 ############################ Type Proxy Header Files ###########################
 
 libc_support_library(
@@ -362,7 +368,7 @@ libc_support_library(
         "__support_cpp_type_traits",
         "__support_macros_attributes",
         ":__support_macros_properties_types",
-        ":llvm_libc_macros_limits_macros",
+        ":hdr_limits_macros",
     ],
 )
```
