### PR TITLE
[Clang][Sema] Fix incorrect rejection default construction of union with nontrivial member

### LINKED ISSUE #81774: Clang incorrectly rejects default construction of union with nontrivial member, part 2
Accepted by VS 2022 17.10 Preview 1, rejected by Clang 17.0.3.

On Compiler Explorer, accepted by GCC 13.2, rejected by Clang 17.0.1 and trunk: https://godbolt.org/z/8fGhWa1ss

Presumably related to #48416 which was previously reported and fixed, but this larger repro is still failing.

```
C:\Temp>type meow.cpp
```
```cpp
enum class BasicFormatArgType { NoType, CustomType };

struct Monostate {};

struct Handle {
    Handle(int, int) {}
};

template <typename Context>
struct BasicFormatArg {
    BasicFormatArg() = default;

    BasicFormatArg(int x, int y) : ActiveState(BasicFormatArgType::CustomType), CustomState(x, y) {}

    BasicFormatArgType ActiveState = BasicFormatArgType::NoType;

    union {
        Monostate NoState = Monostate{};
        Handle CustomState;
    };
};

int main() {
    BasicFormatArg<double> arg{};
    (void) arg;
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c meow.cpp
meow.cpp

C:\Temp>clang-cl -v
clang version 17.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\Llvm\x64\bin

C:\Temp>clang-cl /EHsc /nologo /W4 /std:c++latest /c meow.cpp
meow.cpp(24,28): error: call to implicitly-deleted default constructor of 'BasicFormatArg<double>'
   24 |     BasicFormatArg<double> arg{};
      |                            ^  ~~
meow.cpp(11,5): note: explicitly defaulted function was implicitly deleted here
   11 |     BasicFormatArg() = default;
      |     ^
meow.cpp(19,16): note: default constructor of 'BasicFormatArg<double>' is implicitly deleted because field 'CustomState'
      has no default constructor
   19 |         Handle CustomState;
      |                ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by shafik**
In 765d8a192180f8f33618087b15c022fe758044af we impelemented a fix for incorrect deletion of default constructors in unions. This fix missed a case and so this PR will extend the fix to cover the additional case.

Fixes: https://github.com/llvm/llvm-project/issues/81774

### CODE REVIEW

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -9442,9 +9442,21 @@ bool SpecialMemberDeletionInfo::shouldDeleteForSubobjectCall(
...
+    if (CSM == Sema::CXXDefaultConstructor && Field &&
+        Field->getParent()->isUnion()) {
+      // [class.default.ctor]p2:
+      //   A defaulted default constructor for class X is defined as deleted if
+      //   - X is a union that has a variant member with a non-trivial default
+      //     constructor and no variant member of X has a default member
+      //     initializer
+      const auto *RD = cast<CXXRecordDecl>(Field->getParent());
+      if (!RD->hasInClassInitializer())
+        DiagKind = !Decl ? 0 : 1;
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclCXX.cpp:9455]: So what is going on here?  this is the same value as its 'else' clause, and leaves DiagKind as -1 otherwise?  I might suggest making this a single 'if' and getting rid of the 'else' here.

Comment (shafik) [reply clang/lib/Sema/SemaDeclCXX.cpp:9455]: I have three different states I need to check, I can remove a check by setting `DiagKind` unconditionally and then check `if(RD->hasInClassInitializer())` instead and in that case set it back to `-1` but that does not express the intent as clearly. So I think what I have now is more maintainable although slightly more verbose.

Comment (AaronBallman) [reply clang/lib/Sema/SemaDeclCXX.cpp:9455]: FWIW, I ran into exactly the same issue that Erich did in noticing that both branches do `DiagKind = !Decl ? 0 : 1;`.  That two of us ran into the same readability issue suggests that this should be modified to be more clear.

**Comment by MitalAshok** [comment]
This is [CWG2084](https://wg21.link/CWG2084). Could you also add some tests to CXX/drs/ so that www/cxx_dr_status.html can be updated?

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 1 above)
Comment (MitalAshok) [reply clang/lib/Sema/SemaDeclCXX.cpp:9455]: You can refactor it like this: https://github.com/MitalAshok/llvm-project/commit/a119d89788c2c642b5a13ea00b2ea649b04a418e and I would suggest changing to an enum for readability: https://github.com/MitalAshok/llvm-project/commit/38ca82e1a55012e7d37fd8c6d049d1f00bb50835 (This can then be extracted out into a static function that returns the enum and each `DiagKind = ...` can turn into `return ...`, and the `if`/`else if` ladder can be dismantled)

**Comment by void2012** [comment]
@shafik any updates?

**Comment by cor3ntin** [comment]
> This is [CWG2084](https://wg21.link/CWG2084). Could you also add some tests to CXX/drs/ so that www/cxx_dr_status.html can be updated?

Can you address that? thanks!

**Review by cor3ntin — APPROVED** [review]
Thanks!

**Comment by Endilll** [comment]
Worth noting that this PR is missing changes to `cxx_dr_status.html`, which are done via `clang/www/make_cxx_dr_status` script. For `main` this is not too big of a deal, because the change will be included the next time I run the script, but it makes backporting more annoying.
