### PR TITLE
[OpenMP] Fix node destruction race in __kmpc_omp_taskwait_deps_51

### LINKED ISSUE #85963: [OpenMP] Race condition in __kmpc_omp_taskwait_deps_51
The target_nowait_target test is sporadically failing on the openmp-s390x-linux builder.  When enabling debug assertions, the failure case triggers a
```
Assertion failure at kmp_taskdeps.h(26): n >= 0.
```
with the following stack trace
```
#6  0x000003fff7a47d5e in __kmp_debug_assert (msg=0x3fff7b6d296 "n >= 0", file=0x3fff7b6ec37 "kmp_taskdeps.h", line=26)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_debug.cpp:74
#7  0x000003fff7aa0728 in __kmp_node_deref (thread=0x3ffe4073a00, node=0x3ffffff8200) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_taskdeps.h:26
#8  0x000003fff7aa2b0c in __kmp_release_deps (gtid=7, task=0x2aa001be480) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_taskdeps.h:193
#9  0x000003fff7a9db2c in __kmp_task_finish<false> (gtid=7, task=0x2aa001be780, resumed_task=0x3ffe400be00)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_tasking.cpp:1179
#10 0x000003fff7a91936 in __kmp_invoke_task (gtid=7, task=0x2aa001be780, current_task=0x3ffe400be00)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_tasking.cpp:1944
#11 0x000003fff7a968e4 in __kmp_execute_tasks_template<kmp_flag_64<false, true> > (thread=0x3ffe4073a00, gtid=7, flag=0x3ffe89001c0, final_spin=1, 
    thread_finished=0x3ffe88fff54, itt_sync_obj=0x0, is_constrained=0) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_tasking.cpp:3486
#12 0x000003fff7aa8bca in __kmp_execute_tasks_64<false, true> (thread=0x3ffe4073a00, gtid=7, flag=0x3ffe89001c0, final_spin=1, thread_finished=0x3ffe88fff54, 
    itt_sync_obj=0x0, is_constrained=0) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_tasking.cpp:3599
#13 0x000003fff7ac136a in kmp_flag_64<false, true>::execute_tasks (this=0x3ffe89001c0, this_thr=0x3ffe4073a00, gtid=7, final_spin=1, thread_finished=0x3ffe88fff54, 
    itt_sync_obj=0x0, is_constrained=0) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_wait_release.h:874
#14 0x000003fff7ababfc in __kmp_wait_template<kmp_flag_64<false, true>, true, false, true> (this_thr=0x3ffe4073a00, flag=0x3ffe89001c0, itt_sync_obj=0x0)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_wait_release.h:539
#15 0x000003fff7ac11aa in kmp_flag_64<false, true>::wait (this=0x3ffe89001c0, this_thr=0x3ffe4073a00, final_spin=1, itt_sync_obj=0x0)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_wait_release.h:881
#16 0x000003fff7ab2310 in __kmp_hyper_barrier_release (bt=bs_forkjoin_barrier, this_thr=0x3ffe4073a00, gtid=7, tid=-2, propagate_icvs=1, itt_sync_obj=0x0)
    at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_barrier.cpp:1161
#17 0x000003fff7ab7970 in __kmp_fork_barrier (gtid=7, tid=-2) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_barrier.cpp:2474
#18 0x000003fff7a65baa in __kmp_launch_thread (this_thr=0x3ffe4073a00) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/kmp_runtime.cpp:6033
#19 0x000003fff7b1f3b2 in __kmp_launch_worker (thr=0x3ffe4073a00) at /home/uweigand/llvm/llvm-head/openmp/runtime/src/z_Linux_util.cpp:565
```

The node=0x3ffffff8200 pointer argument to __kmp_node_deref points to a local variable on the stack frame of __kmpc_omp_taskwait_deps_51 here:
```
  kmp_depnode_t node = {0};      
```
but that function is actually not running any more.  The function had been called from the test case's main routine in the main thread, has returned, and the main thread is now executing glibc cleanup handlers as part of exiting the process.

The __kmpc_omp_taskwait_deps_51 function does the following before returning:
```
  int thread_finished = FALSE;
  kmp_flag_32<false, false> flag(
      (std::atomic<kmp_uint32> *)&node.dn.npredecessors, 0U);
  while (node.dn.npredecessors > 0) {
    flag.execute_tasks(thread, gtid, FALSE,
                       &thread_finished USE_ITT_BUILD_ARG(NULL),
                       __kmp_task_stealing_constraint);
  }
```
and it seems to assume that as soon as the dn.npredecessors counter drops to zero, it is OK to deallocate the local stack frame.

However, the __kmp_release_deps routine does the following:
```
  for (kmp_depnode_list_t *p = node->dn.successors; p; p = next) {
    kmp_depnode_t *successor = p->node;
#if USE_ITT_BUILD && USE_ITT_NOTIFY
    __itt_sync_releasing(successor);
#endif
    kmp_int32 npredecessors = KMP_ATOMIC_DEC(&successor->dn.npredecessors) - 1;

    // successor task can be NULL for wait_depends or because deps are still
    // being processed
    if (npredecessors == 0) {
[...]
    }

    next = p->next;
    __kmp_node_deref(thread, p->node);
[^^^ crash here]
```

Note that p->node->dn.npredecessors is decremented relatively early in the loop, but the kmp_depnode_t struct pointed to by p->node is still being accessed throughout the remainder of the loop.   This seems to open a race where another thread deallocates the kmp_depnode_t struct immediately after npredecessors goes to zero.

### PR DESCRIPTION
**Pull request by uweigand**
The __kmpc_omp_taskwait_deps_51 allocates a kmp_depnode_t node on its stack, and there is currently a race condition where another thread might still be accessing that node after the function has returned and its stack frame was released.

While the function does wait until the node's npredecessors count has reached zero before exiting, there is still a window where the function that last decremented the npredecessors count assumes the node is still accessible.

For heap-allocated kmp_depnode_t nodes, this normally works via a separate ndeps count that only reaches zero at the point where no accesses to the node are expected at all; in fact, at this point the heap allocation will be freed.

For this case of a stack-allocated kmp_depnode_t node, it therefore makes sense to similarly respect the ndeps count; we need to wait until this reaches 1 (not 0, because it is not heap-allocated so there's always one extra count to prevent it from being freed), before we can safely deallocate our stack frame.

As this is expected to be a short race window of only a few instructions, it should be fine to just use a busy wait loop checking the ndeps count.

Fixes: https://github.com/llvm/llvm-project/issues/85963

### CODE REVIEW

File: openmp/runtime/src/kmp_taskdeps.cpp [hunk 1]
```diff
@@ -1030,6 +1030,12 @@ void __kmpc_omp_taskwait_deps_51(ident_t *loc_ref, kmp_int32 gtid,
                        __kmp_task_stealing_constraint);
   }
 
+  // Wait until the last __kmp_release_deps is finished before we free the
+  // current stack frame holding the "node" variable; once its nrefs count
+  // reaches 1, we're sure nobody else can try to reference it again.
+  while (node.dn.nrefs > 1)
```
Comment (shiltian) [inline openmp/runtime/src/kmp_taskdeps.cpp:1036]: I'm not sure this is the right way to do that, especially using task yield. @jprotze might have a better idea.

Comment (uweigand) [reply openmp/runtime/src/kmp_taskdeps.cpp:1036]: An alternative solution would be to just not use a stack-allocated node, but allocate it on the heap like everywhere else.  Then there'd still be a race which thread would be the one to free it, but that race would be harmless ...  Let me know if you'd like me to try this (or any other) approach.

**Comment by jprotze** [comment]
This fix makes sense to me.

Looking at the code, I realized that the current implementation is still stupid. The function should really create an empty task to be inserted into the DAG, if has_no_wait is set.

**Review by jprotze — APPROVED** [review]
