### PR TITLE
Fix `pragma-comment.c` test failing on false match

### LINKED ISSUE #145453: [clang] `pragma-comment.c` test fails when developer's GitHub handle is `dbartol`
I've certainly had many encounters with tests that only fail on my machine, but this is the first time the test was specifically out to get me:

### To repro
```bash
llvm-lit -v ./clang/test/CodeGen/pragma-comment.c
```

### Actual result:
```
/Volumes/LocalData/Code/Public/bar/llvm-project/clang/test/CodeGen/pragma-comment.c:33:13: error: ELF-NOT: excluded string found in input
// ELF-NOT: bar
            ^
<stdin>:16:55: note: found here
!6 = !{!"clang version 21.0.0git (https://github.com/dbartol/llvm-project 97e8266172533fe9deb701a0851b442298f0f011)"}
                                                      ^~~

Input file: <stdin>
Check file: /Volumes/LocalData/Code/Public/bar/llvm-project/clang/test/CodeGen/pragma-comment.c
```

### Expected result
Successful test

### PR DESCRIPTION
**Pull request by dbartol**
Sometimes the forbidden text `foo` or `bar` could appear in the Clang version string metadata. Treating the version string as a `CHECK-LABEL:` prevents this.

Fixes #145453

### CODE REVIEW

File: clang/test/CodeGen/pragma-comment.c [hunk 1]
```diff
@@ -32,3 +32,6 @@
 // ELF: ![[space]] = !{!"with space"}
 // ELF-NOT: bar
 // ELF-NOT: foo
+// This following match prevents the clang version metadata from matching the forbidden 'foo' and 'bar' tokens.
+// This can happen if the clang version string contains a Git repo URL that includes one of those substrings.
+// ELF-LABEL: !"clang version
```
Comment (AaronBallman) [inline clang/test/CodeGen/pragma-comment.c:37]: I wonder if using regex is a better approach. e.g.,
```
// ELF-NOT: {{\bbar\b}}
// ELF-NOT: {{\bfoo\b}}
```
WDYT?

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! I think this approach works, but there may be a slightly improved approach that uses regex word boundaries worth considering.

File: clang/test/CodeGen/pragma-comment.c (hunk 1 above)
Comment (dbartol) [reply clang/test/CodeGen/pragma-comment.c:37]: I was considering the word boundary approach before I discovered `CHECK-LABEL:`. Using word boundaries would have fixed the problem for me, but not for someone whose GitHub handle was literally just either `foo` or `bar` (or any other use of those words in a URL or whatever else can wind up in the version string).

I also just considered using random strings instead of `foo` and `bar`, which would have made a match much less likely.

Ultimately, the behavior of `CHECK-LABEL:` works pretty well here. While we don't really care whether the Clang version is present or not, the additional behavior of ignoring the label line for any other matches is what we're looking for.

Comment (AaronBallman) [reply clang/test/CodeGen/pragma-comment.c:37]: Okay, that's compelling logic, thank you!

**Review by AaronBallman — APPROVED** [review]
LGTM! Thank you!

I'll land the changes on your behalf once precommit CI comes back green.

**Comment by dbartol** [comment]
This caused a buildbot failure because I forgot to take the vendor string into account. Working on a fix now.

**Comment by Sharjeel-Khan** [comment]
This PR also broke Android's buildbots too. In Android, it will appear as `!"Android (13563557, +pgo, +bolt, +lto, +mlgo, based on r563880) clang...` so try to keep this in account too in your fix

**Comment by dbartol** [comment]
Opened #145612 with the fix
