### PR TITLE
[clang] Introduce "binary" StringLiteral for #embed data

### LINKED ISSUE #119256: #embed incorrectly assumes numbers are negative
very hard to reproduce as I have no idea what triggers it. it should never ever happen though.

```cpp
static constexpr unsigned char data[] = {
#if __has_embed("data.bin")
#embed "data.bin"
#endif
};
```

`error: constexpr initializer evaluates to -41 which is not exactly representable in type 'const unsigned char'`

### PR DESCRIPTION
**Pull request by Fznamznon**
StringLiteral is used as internal data of EmbedExpr and we directly use it as an initializer if a single EmbedExpr appears in the initializer list of a char array. It is fast and convenient, but it is causing problems when string literal character values are checked because #embed data values are within a range [0-2^(char width)] but ordinary StringLiteral is of maybe signed char type.
This PR introduces new kind of StringLiteral to hold binary data coming from an embedded resource to mitigate these problems. The new kind of StringLiteral is not assumed to have signed char type. The new kind of StringLiteral also helps to prevent crashes when trying to find StringLiteral token locations since these simply do not exist for binary data.

Fixes https://github.com/llvm/llvm-project/issues/119256

### CODE REVIEW

File: clang/include/clang/AST/Expr.h [hunk 1]
```diff
@@ -4965,9 +4966,9 @@ class EmbedExpr final : public Expr {
       assert(EExpr && CurOffset != ULLONG_MAX &&
              "trying to dereference an invalid iterator");
       IntegerLiteral *N = EExpr->FakeChildNode;
-      StringRef DataRef = EExpr->Data->BinaryData->getBytes();
       N->setValue(*EExpr->Ctx,
-                  llvm::APInt(N->getValue().getBitWidth(), DataRef[CurOffset],
+                  llvm::APInt(N->getValue().getBitWidth(),
+                              EExpr->Data->BinaryData->getCodeUnit(CurOffset),
```
Comment (cor3ntin) [inline clang/include/clang/AST/Expr.h:4971]: If you change that line (and nothing else) does it still works?
I have a feeling this is enough

**Comment by Fznamznon** [comment]
ping

File: clang/lib/AST/Expr.cpp [hunk 2]
```diff
@@ -1332,6 +1334,11 @@ StringLiteral::getLocationOfByte(unsigned ByteNo, const SourceManager &SM,
                                  const LangOptions &Features,
                                  const TargetInfo &Target, unsigned *StartToken,
                                  unsigned *StartTokenByteOffset) const {
+  // No source location of bytes for binary literals since they don't come from
+  // source.
+  if (getKind() == StringLiteralKind::Binary)
+    return getStrTokenLoc(0);
```
Comment (AaronBallman) [inline clang/lib/AST/Expr.cpp:1340]: Does this mean that diagnostics involving invalid use of binary string literals will have no source location to point to?

**Review by AaronBallman — COMMENTED** [review]
Thanks for this! It also needs a release note for the fix. :-)

In general, I think this seems reasonable, but I'd like confirmation from @cor3ntin given his somewhat recent thinking about unevaluated string literals and where those end up touching the rest of the compiler.

File: clang/lib/AST/Expr.cpp (hunk 2 above)
Comment (Fznamznon) [reply clang/lib/AST/Expr.cpp:1340]: It will point at the beginning of the StringLiteral, but not to a particular problematic byte (which this function intends to find). In case of `#embed` it will point to the directive location. The test I'm adding should exercise that.

File: clang/include/clang/AST/Expr.h [hunk 3]
```diff
@@ -1752,7 +1752,8 @@ enum class StringLiteralKind {
   UTF8,
   UTF16,
   UTF32,
-  Unevaluated
+  Unevaluated,
+  Binary
```
Comment (cor3ntin) [inline clang/include/clang/AST/Expr.h:1756]: Can you add a comment explaining this is for embed?

I'm sorry it took me a while to understand how this patch works.
(The reason is that this allows us to not "cast" to char in `getCodeUnitS()` - which is only used in C23 mode)

Maybe also add a comment in `getCodeUnitS` and/or `CheckC23ConstexprInitStringLiteral`

**Review by cor3ntin — APPROVED** [review]
Sorry for the delay

No changelog because we want to backport?

LGTM, but i think this could use some comments

**Review by AaronBallman — APPROVED** [review]
LGTM!

File: clang/include/clang/AST/Expr.h (hunk 3 above)
Comment (cor3ntin) [reply clang/include/clang/AST/Expr.h:1766]: Yup, Thanks!

**Review by cor3ntin — APPROVED** [review]

**Comment by Fznamznon** [comment]
Ooops, I'll fix the bots quickly
