### PR TITLE
[libc++][test] Fixes constexpr char_traits.

### LINKED ISSUE #74221: [libc++][test] `nasty_char_traits::move` is incompatible with `constexpr`
Found while running libc++'s test suite with MSVC's STL.

`nasty_char_traits::move` is marked `constexpr` but compares unrelated pointers `s1 < s2`. This is forbidden, and `nasty_char_traits::copy` acknowledges this immediately below:

https://github.com/llvm/llvm-project/blob/38f75d606f94e6b552fd74d487b061a1f8f907fa/libcxx/test/support/nasty_string.h#L120-L141

<details><summary>Click to expand compiler error:</summary>

With libc++'s test suite, MSVC's STL, and Clang/LLVM, `std/strings/basic.string/string.modifiers/string_append/initializer_list.pass.cpp` emits this error:

```
D:\GitHub\STL\llvm-project\libcxx\test\std\strings\basic.string\string.modifiers\string_append\initializer_list.pass.cpp(53,17): error: static assertion expression is not an integral constant expression
  static_assert(test());
                ^~~~~~
D:\GitHub\STL\llvm-project\libcxx\test\support\nasty_string.h(122,10): note: comparison between '&s._Mypair._Myval2._Bx._Buf[3]' and '&{CharT(('a')), CharT(('b')), CharT(('c'))}[0]' has unspecified value
  if (s1 < s2) {
         ^
D:\GitHub\STL\out\x64\out\inc\xstring(3311,13): note: in call to 'move(&s._Mypair._Myval2._Bx._Buf[3], &{CharT(('a')), CharT(('b')), CharT(('c'))}[0], 3)'
            _Traits::move(_Old_ptr + _Old_size, _Ptr, _Count);
            ^
D:\GitHub\STL\out\x64\out\inc\xstring(3152,16): note: in call to '&s->append(&{CharT(('a')), CharT(('b')), CharT(('c'))}[0], 3)'
        return append(_Ilist.begin(), _Convert_size<size_type>(_Ilist.size()));
               ^
D:\GitHub\STL\llvm-project\libcxx\test\std\strings\basic.string\string.modifiers\string_append\initializer_list.pass.cpp(27,5): note: in call to '&s->append({&{CharT(('a')), CharT(('b')), CharT(('c'))}[0], &{CharT(('a')), CharT(('b')), CharT(('c'))}[3]})'
  s.append({CharT('a'), CharT('b'), CharT('c')});
    ^
D:\GitHub\STL\llvm-project\libcxx\test\std\strings\basic.string\string.modifiers\string_append\initializer_list.pass.cpp(44,3): note: in call to 'test()'
  test<nasty_string>();
  ^
D:\GitHub\STL\llvm-project\libcxx\test\std\strings\basic.string\string.modifiers\string_append\initializer_list.pass.cpp(53,17): note: in call to 'test()'
  static_assert(test());
                ^
```
</details>

In microsoft/STL's product code, I have a truly marvelous way to avoid this problem - a linear scan to detect whether the first iterator of the destination is within the source range, in which case a backward loop is necessary. See https://github.com/microsoft/STL/blob/0403d19f5461fd15983737c3f01ec34800ea9275/stl/inc/xstring#L85-L93 .

### PR DESCRIPTION
**Pull request by mordante**
The issue in nasty_char_traits was discovered by @StephanTLavavej who provided
the solution they use in MSVC STL. This solution is based on that example.

The same issue affects the constexpr_char_traits which was discovered in
https://github.com/llvm/llvm-project/pull/88389. This uses the same fix.

Fixes: https://github.com/llvm/llvm-project/issues/74221

### CODE REVIEW

File: libcxx/test/support/constexpr_char_traits.h [hunk 1]
```diff
@@ -98,23 +122,21 @@ constexpr_char_traits<CharT>::find(const char_type* s, std::size_t n, const char
...
-    }
-    else if (s2 < s1)
-    {
-        s1 += n;
-        s2 += n;
-        for (; n; --n)
-            assign(*--s1, *--s2);
-    }
-    return r;
+TEST_CONSTEXPR_CXX14 CharT* constexpr_char_traits<CharT>::move(char_type* s1, const char_type* s2, std::size_t n) {
```
Comment (Zingam) [inline libcxx/test/support/constexpr_char_traits.h:125]: Maybe also add `constexpr_char_traits` to the PR title?

File: libcxx/test/support/nasty_string.h [hunk 2]
```diff
@@ -16,6 +16,7 @@
 
 #include "make_string.h"
 #include "test_macros.h"
+#include "constexpr_char_traits.h" // is_nonoverlapping_range
```
Comment (h-vetinari) [inline libcxx/test/support/nasty_string.h:19]:
```suggestion
#include "constexpr_char_traits.h" // is_overlapping_range
```

File: libcxx/test/support/constexpr_char_traits.h [hunk 3]
```diff
@@ -16,6 +16,30 @@
 
 #include "test_macros.h"
 
+// Tests whether the range [p1, p1 + n) overlaps with the range [p2, p2 + n).
+//
+// precondition The ranges [p1, p1 + n) and [p2, p2 + n) are valid ranges.
```
Comment (ldionne) [inline libcxx/test/support/constexpr_char_traits.h:21]:
```suggestion
// Precondition: The ranges [p1, p1 + n) and [p2, p2 + n) are valid ranges.
```

File: libcxx/test/support/constexpr_char_traits.h [hunk 4]
```diff
@@ -16,6 +16,30 @@
...
+//
+// Typically the pointers are compared with less than. This is not allowed when
+// the pointers belong to different ranges. This is UB. Typically, this is
```
Comment (ldionne) [inline libcxx/test/support/constexpr_char_traits.h:24]:
```suggestion
// the pointers belong to different ranges, which is UB. Typically, this is
```

File: libcxx/test/support/constexpr_char_traits.h [hunk 5]
```diff
@@ -16,6 +16,30 @@
...
+// benign at run-time, however since UB is not allowed during constant
+// evaluation this does not compile. This function does the validation without
+// UB.
+//
+// When the ranges overlap the ranges can be copied from the beginning to the
```
Comment (ldionne) [inline libcxx/test/support/constexpr_char_traits.h:29]:
```suggestion
// When the ranges overlap they can be copied from the beginning to the
```

File: libcxx/test/support/constexpr_char_traits.h [hunk 6]
```diff
@@ -16,6 +16,30 @@
...
+// end. Otherwise they need to be copied from the end to the beginning.
+template <class Traits>
+TEST_CONSTEXPR_CXX14 bool is_overlapping_range(Traits* p1, const Traits* p2, std::size_t n) {
```
Comment (ldionne) [inline libcxx/test/support/constexpr_char_traits.h:32]:
```suggestion
template <class CharT>
TEST_CONSTEXPR_CXX14 bool is_overlapping_range(const CharT* p1, const CharT* p2, std::size_t n) {
```

Comment (ldionne) [inline libcxx/test/support/constexpr_char_traits.h:32]: As-is, this function does not catch the following case:

```
|-----------------------|
^              |---------------------|
|              ^
p2             |
               p1
```

I think the name of this function is misleading. Maybe the following API would be better instead?

```c++
template <class CharT>
bool is_pointer_in_range(CharT* first, CharT* last, CharT* p) {
  // return whether p falls inside [first, last)
}
```

Then below you basically query for `is_pointer_in_range(p1, p1+n, p2)` which tells you whether `p1 <= p2 < p1+n`.

File: libcxx/test/support/nasty_string.h (hunk 2 above)
Comment (ldionne) [inline libcxx/test/support/nasty_string.h:19]: This comment is (or will be) outdated.

**Review by ldionne — APPROVED** [review]
LGTM w/ some comments.

File: libcxx/test/support/nasty_string.h (hunk 2 above)
Comment (mordante) [reply libcxx/test/support/nasty_string.h:19]: Applied with the new name `is_pointer_in_range`.

File: libcxx/test/support/constexpr_char_traits.h (hunk 1 above)
Comment (mordante) [reply libcxx/test/support/constexpr_char_traits.h:126]: I like short titles, so I made the title more generic and updated the commit message.
