### PR TITLE
[SPIRV]  Create a new OpSelect selector and fix register types.

### LINKED ISSUE #135572: [SPIRV] Floating point select operands cause the machine verifier to trip
Here's a minimal test case that results in the failure when using `llc -verify-machineinstrs`:

```
define spir_func float @test(float %x, float %y, float %z) {
entry:
   %0 = call float @llvm.maxnum.f32(float %x, float %y)
   %1 = fcmp ogt float %0, %z
   %2 = select i1 %1, float %y, float %0
   ret float %2
}
```

Godbolt: https://godbolt.org/z/54K5KvdfP

### PR DESCRIPTION
**Pull request by farzonl**
fixes #135572

There are two problems that are causing problems first register types are copied from older registers instead of evaluating the spirv types.

Second the way OpSelect is defined in SPIRVInstrInfo.td we always default to integer for TernOpTyped. There seems to be a problem of multiple matches in the getMatchTable so when executeMatchTable runs we aren't getting the right opSelect.

Correcting the tablegen wasn't very easy so instead created an emitter for Select that evaluated the register types. this passes the original llvm/test/CodeGen/SPIRV/instructions/select.ll tests and the new float ones I'm adding in issue-135572-emit-float-opselect.ll

### CODE REVIEW

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 1]
```diff
@@ -222,6 +222,8 @@ class SPIRVInstructionSelector : public InstructionSelector {
 
   bool selectSelect(Register ResVReg, const SPIRVType *ResType, MachineInstr &I,
                     bool IsSigned) const;
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:224]: remove `IsSigned` since never used.

**Review by Keenuts — COMMENTED** [review]
A small code change, a question, otherwise looks good, thanks!

**Review by Keenuts — APPROVED** [review]
Thanks!

File: llvm/test/CodeGen/SPIRV/instructions/issue-135572-emit-float-opselect.ll
Comment (inbelic) [inline llvm/test/CodeGen/SPIRV/instructions/issue-135572-emit-float-opselect.ll:1]: Can we also add a test case for when it is a scalar condition and vector of floats?

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 2]
```diff
@@ -2565,8 +2578,52 @@ Register SPIRVInstructionSelector::buildOnesVal(bool AllOnes,
...
+    if (IsFloatTy) {
+      Opcode = IsScalarBool ? SPIRV::OpSelectVFSCond : SPIRV::OpSelectVFVCond;
+    } else if (IsPtrTy) {
+      Opcode = IsScalarBool ? SPIRV::OpSelectVPSCond : SPIRV::OpSelectVPVCond;
+    } else {
+      Opcode = IsScalarBool ? SPIRV::OpSelectVISCond : SPIRV::OpSelectVIVCond;
+    }
+  } else {
+    if (IsFloatTy) {
+      Opcode = IsScalarBool ? SPIRV::OpSelectSFSCond : SPIRV::OpSelectVFVCond;
```
Comment (inbelic) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2607]: IIUC, `IsScalarBool` detects if the condition is a scalar or vector.

Shouldn't we assert that `IsScalarBool` is true? `VFV` doesn't seem correct because the float operands would be a scalar in this case.

Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2607]: Thats not correct.
