### PR TITLE
[DirectX] Scalarize `extractelement` and `insertelement` with dynamic indices

### LINKED ISSUE #141136: [DirectX] Legalize dynamic vector indexing
Dynamic vector indexing (i.e., indexing a vector using a non-constant index) currently becomes scalarized into a series of `select` instructions, with the first `select` containing a poison value that will fail to pass validation. (See #139011)

https://godbolt.org/z/shnW4P1hz

```llvm
define float @_Z4testDv4_fi(<4 x float> %0, i32 %1) local_unnamed_addr #0 !dbg !14 {
  %3 = icmp eq i32 %1, 0, !dbg !31
  %4 = extractelement <4 x float> %0, i32 0, !dbg !31
  %5 = select i1 %3, float %4, float poison, !dbg !31
  %6 = icmp eq i32 %1, 1, !dbg !31
  %7 = extractelement <4 x float> %0, i32 1, !dbg !31
  %8 = select i1 %6, float %7, float %5, !dbg !31
  %9 = icmp eq i32 %1, 2, !dbg !31
  %10 = extractelement <4 x float> %0, i32 2, !dbg !31
  %11 = select i1 %9, float %10, float %8, !dbg !31
  %12 = icmp eq i32 %1, 3, !dbg !31
  %13 = extractelement <4 x float> %0, i32 3, !dbg !31
  %14 = select i1 %12, float %13, float %11, !dbg !31
  ret float %14, !dbg !32
}
```

Instead of the above form currently generated by Clang, we should replicate DXC's behavior of transforming the vector into an array and using a getelementptr and load to return the value at the dynamic index.

```llvm
define float @"\01?test@@YAMV?$vector@M$03@@H@Z"(<4 x float> %v, i32 %i) #0 {
  %1 = alloca [4 x float], align 4
  %2 = extractelement <4 x float> %v, i64 0
  %3 = getelementptr inbounds [4 x float], [4 x float]* %1, i32 0, i32 0
  store float %2, float* %3, align 4
  %4 = extractelement <4 x float> %v, i64 1
  %5 = getelementptr inbounds [4 x float], [4 x float]* %1, i32 0, i32 1
  store float %4, float* %5, align 4
  %6 = extractelement <4 x float> %v, i64 2
  %7 = getelementptr inbounds [4 x float], [4 x float]* %1, i32 0, i32 2
  store float %6, float* %7, align 4
  %8 = extractelement <4 x float> %v, i64 3
  %9 = getelementptr inbounds [4 x float], [4 x float]* %1, i32 0, i32 3
  store float %8, float* %9, align 4
  %10 = getelementptr [4 x float], [4 x float]* %1, i32 0, i32 %i, !dbg !42 ; line:2 col:12
  %11 = load float, float* %10, align 4, !dbg !42, !tbaa !43 ; line:2 col:12
  ret float %11, !dbg !47 ; line:2 col:5
}
```

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #141136

- Implement `visitExtractElementInst` and `visitInsertElementInst` in `DXILDataScalarizerVisitor` to scalarize `extractelement` and `insertelement` instructions whose index operand is not a `ConstantInt` by converting the vector to an array and then loading from the array
- Rename the `replaceVectorWithArray` helper function to `equivalentArrayTypeFromVector`, relocate the function toward the top of the file, and remove the unused `Ctx` parameter

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 1]
```diff
@@ -173,6 +171,38 @@ bool DataScalarizerVisitor::visitStoreInst(StoreInst &SI) {
   return false;
 }
 
+bool DataScalarizerVisitor::visitExtractElementInst(ExtractElementInst &EEI) {
```
Comment (Icohedron) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:174]:
```suggestion
bool DataScalarizerVisitor::visitExtractElementInst(ExtractElementInst &EEI) {
  // Shader Model 6.9 and above supports dynamic vector indexing and therefore
  // does not need to be scalarized
  VersionTuple ShaderModelVersion =
      EEI.getModule()->getTargetTriple().getOSVersion();
  if (ShaderModelVersion >= VersionTuple(6, 9))
    return false;
    
```
Should I add a shader model check here for 6.9? SM 6.9 isn't currently a supported target. Perhaps a TODO comment instead?

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:175]: I don't know if this is needed we likely need to disable the entire data scalarization pass  for 6.9 not just this one behavior.

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:175]: I also don't like to prematurely assume correct behavior for something we haven't planned out. So would prefer we don't make any assumptions about 6.9.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 2]
```diff
@@ -173,6 +172,38 @@ bool DataScalarizerVisitor::visitStoreInst(StoreInst &SI) {
...
+  // If the index is a constant then we don't need to scalarize it
+  Value *Index = EEI.getIndexOperand();
+  Type *IndexTy = Index->getType();
+  if (isa<ConstantInt>(Index))
+    return false;
+
+  IRBuilder<> Builder(&EEI);
+  VectorType *VecTy = EEI.getVectorOperandType();
+  assert(VecTy->getElementCount().isFixed() &&
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:184]: seems like an unnecessary assert whether the vector is of fixed size does not seem to impact the correctness of the algorithm below.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 3]
```diff
@@ -27,6 +27,20 @@ static const int MaxVecSize = 4;
 
 using namespace llvm;
 
+// Recursively creates an array-like version of a given vector type.
+static Type *equivalentArrayTypeFromVector(Type *T) {
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:31]: This is fine I would have just made a function declaration at the top so the implementation could live anywhere.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 4]
```diff
@@ -55,7 +69,7 @@ class DataScalarizerVisitor : public InstVisitor<DataScalarizerVisitor, bool> {
   bool visitCastInst(CastInst &CI) { return false; }
   bool visitBitCastInst(BitCastInst &BCI) { return false; }
   bool visitInsertElementInst(InsertElementInst &IEI) { return false; }
```
[the remark this answers is not in the document]
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:71]: `insertelement` isn't an issue because its scalarization doesn't produce any `select` with `poison`.
https://godbolt.org/z/YrfEohcTs

But if we want it to be consistent with `extractelement` then I could implement vector-to-array data scalarization for `insertelement`.

[the remark this answers is not in the document]
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:71]: Actually the shader I linked fails validation.
```
Function: _Z4testRDv4_fif: error: Access to out-of-bounds memory is disallowed.
note: at '%v.i1 = getelementptr float, float* %v, i32 1' in block 'entry' of function '_Z4testRDv4_fif'.
Function: _Z4testRDv4_fif: error: Access to out-of-bounds memory is disallowed.
note: at '%v.i2 = getelementptr float, float* %v, i32 2' in block 'entry' of function '_Z4testRDv4_fif'.
Function: _Z4testRDv4_fif: error: Access to out-of-bounds memory is disallowed.
note: at '%v.i3 = getelementptr float, float* %v, i32 3' in block 'entry' of function '_Z4testRDv4_fif'.
Validation failed.
```
I will scalarize `insertelement` as well.

File: llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll
Comment (inbelic) [inline llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll:1]: Does it make sense to have a multi-dimension testscase, `<2 x <3 x float>>`?

Comment (inbelic) [reply llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll:1]: Also, if we have two successive extract (or insert) elements, do we want to ensure that they will both index from the same newly allocated array? Or is it safe to assume that the un-required extra allocations of the array will get cleaned up?

**Review by inbelic — COMMENTED** [review]
Implementation looks great to me. Just want a check on the commented cases

File: llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll:1]: I didn't think 2D vectors were a valid type.

You do make a good point about extra allocas when there are successive insert/extractelement instructions on the same vector. Is there an existing pass that could clean it up?

Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll:1]: I am confident that multi-dimensional vectors are not a valid type in LLVM.

Comment (farzonl) [reply llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll:1]: Oh sorry i thought you were asking if arrays of vectors were valid

**Comment by Icohedron** [comment]
This legalization will also need to place allocas in the entry block of the function.

**Review by farzonl — DISMISSED** [review]

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 5]
```diff
@@ -172,38 +183,61 @@ bool DataScalarizerVisitor::visitStoreInst(StoreInst &SI) {
...
+
+  AllocaAndGEPs ArrAllocaAndGEPs =
+      createArrayFromVector(Builder, Vec, IEI.getName());
+  AllocaInst *ArrAlloca = ArrAllocaAndGEPs.first;
+  SmallVector<Value *, 4> &ArrGEPs = ArrAllocaAndGEPs.second;
+
+  Type *ArrTy = ArrAlloca->getAllocatedType();
+  Value *GEPForStore =
+      Builder.CreateInBoundsGEP(ArrTy, ArrAlloca, {Builder.getInt32(0), Index},
+                                IEI.getName() + ".dynindex");
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp]: nit: This code seems used in both cases and if it makes sense, it could be moved inside the `createArrayFromVector` and returned instead of the alloca?

File: llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll [hunk 6]
```diff
@@ -1,25 +1,76 @@
 ; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
 ; RUN: opt -S -passes='dxil-data-scalarization' -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s
 
+; Allocas should be placed in the entry block.
+; Allocas should also be reused across multiple insertelement and extractelement instructions for the same vector
+define void @alloca_placement_and_reuse(<3 x i32> %v1, <3 x i32> %v2, i32 %a, i32 %i, i32 %j) {
```
Comment (inbelic) [inline llvm/test/CodeGen/DirectX/scalarize-dynamic-vector-index.ll]: nit: it might be easier to read if this was split out into two tests to test the independent things here

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 7]
```diff
@@ -79,6 +79,16 @@ class DataScalarizerVisitor : public InstVisitor<DataScalarizerVisitor, bool> {
   friend bool findAndReplaceVectors(llvm::Module &M);
 
 private:
+  typedef std::pair<AllocaInst *, SmallVector<Value *, 4>> AllocaAndGEPs;
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:82]: This seems fine given the number of elements is currently capped at 4. But I think we should be very cautious if we consider any larger numbers, and that might very well be the case soon. Edit: 4 being the max size of a vector.

It think it is probably fine to just re-create the GEP's when we need them and let another optimization pass remove all of those instead of retaining them here.

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:82]: When HLSL has vectors larger than 4 may be also when DXIL has native support for dynamic vector indexing, thus this data structure may not be used.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp (hunk 5 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp]: Makes sense, but also feels kind of weird to not return the Alloca, given the name of the function. I would need to think of a new name. The createArrayFromVector function would also need a new arg for the index.

**Comment by Icohedron** [comment]
It just came to me that the implementation still needs more work. Two issues:
1. Two `insertelement` instructions on the same vector currently is incorrect because they affect each other's results, which shouldn't be the case.
2. If `extractelement` or `insertelement` is used on a vector that is not a function arg, then the stores to the alloca are invalid because they reference a vector that is not yet defined.

**Comment by Icohedron** [comment]
> It just came to me that the implementation still needs more work. Two issues:
> 
> 1. Two `insertelement` instructions on the same vector currently is incorrect because they affect each other's results, which shouldn't be the case.
> 2. If `extractelement` or `insertelement` is used on a vector that is not a function arg, then the stores to the alloca are invalid because they reference a vector that is not yet defined.

Fixed 1. by loading the original value and storing it back after constructing the vector for insertelement.
Fixed 2. by moving the array initialization (i.e., copying vector contents to the array) to immediately after the instruction where the vector is defined.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 8]
```diff
@@ -173,6 +183,125 @@ bool DataScalarizerVisitor::visitStoreInst(StoreInst &SI) {
...
+    return VA->second;
+
+  auto InsertPoint = Builder.GetInsertPoint();
+
+  // Allocate the array to hold the vector elements
+  Builder.SetInsertPointPastAllocas(Builder.GetInsertBlock()->getParent());
+  Type *ArrTy = equivalentArrayTypeFromVector(Vec->getType());
+  AllocaInst *ArrAlloca =
+      Builder.CreateAlloca(ArrTy, nullptr, Name + ".alloca");
+  const uint64_t ArrNumElems = ArrTy->getArrayNumElements();
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:200]: nit:
```suggestion
  const uint64_t ArrNumElems = ArrTy->getArrayNumElements();
  assert(ArrNumElems =< 4 && "For vectors larger than 4, dynamic indexing must be natively supported.");
```

We could also use `Value *[4]` instead of the `SmallVector` if we want to be strict on our assumption above.

**Review by inbelic — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp (hunk 8 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILDataScalarization.cpp:200]: It is not certain whether or not HLSL will have large vectors before or after dynamic vector indexing is natively supported, so this assert may not necessarily be correct in the future.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 9]
```diff
@@ -173,6 +183,125 @@ bool DataScalarizerVisitor::visitStoreInst(StoreInst &SI) {
   return false;
 }
 
+DataScalarizerVisitor::AllocaAndGEPs
+DataScalarizerVisitor::createArrayFromVector(IRBuilder<> &Builder, Value *Vec,
+                                             const Twine &Name = "") {
+  // If there is already an alloca for this vector, return it
+  auto VA = VectorAllocaMap.find(Vec);
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp]: nit: i would prefer if the name would indicate we are using an iterator,
Also maybe we should do a more modern way like
```cpp
if (auto IT = VectorAllocaMap.find(Vec); IT != VectorAllocaMap.end()) {
    return IT->second; 
}
```
 or maybe something using contains `if (VectorAllocaMap.contains(Vec)) {`

**Review by farzonl — APPROVED** [review]
LGTM
