### PR TITLE
[Mips] When emit instruction, ignore JUMP_TABLE_DEBUG_INFO

### LINKED ISSUE #134916: [MIPS] Compiler crash when using -O3
Using clang version 20.1.2

clang -target "mipsel-w64-windows-gnu" -c test.cpp
```
typedef unsigned int size_t;
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned uint32_t;
typedef unsigned long long uint64_t;
typedef unsigned int uintptr_t;
typedef signed char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef long long int64_t;

size_t readULEB128(const uint8_t **data);

// read a pointer encoded value and advance pointer
static uintptr_t readEncodedPointer(const uint8_t **data, uint8_t encoding) {
  const uint8_t *p = *data;
  uintptr_t result = 0;

  // first get value
  switch (encoding & 0x0F) {
  case 0x01:
    result = readULEB128(&p);
    break;
  case 0x0A:
    result = *((const int16_t *)p);
    p += sizeof(int16_t);
    break;
  case 0x0B:
    result = *((const int32_t *)p);
    p += sizeof(int32_t);
    break;
  case 0x0C:
    result = *((const int64_t *)p);
    p += sizeof(int64_t);
    break;
  default:
    // not supported
    return 0;
  }

  *data = p;
  return result;
}

int __gcc_personality_v0(const uint8_t* lsda)
{
  uint8_t callSiteEncoding = *lsda++;
  const uint8_t *p = 0;
  while (1) {
    uintptr_t start = readEncodedPointer(&p, callSiteEncoding);
    size_t length = readEncodedPointer(&p, callSiteEncoding);
    size_t landingPad = readEncodedPointer(&p, callSiteEncoding);
    readULEB128(&p); // action value not used for C code
  }

  // No landing pad found, continue unwinding.
  return 0;
}
```
gives
```
fatal error: error in backend: Not supported instr: <MCInst 45 <MCOperand Imm:0>>
```
Possible workaround: add `-O0`

### PR DESCRIPTION
**Pull request by yingopq**
When -triple is windows, SelectionDAGLegalize process Legalizing br_jt, would generate ISD::JUMP_TABLE_DEBUG_INFO.
Then Mips process emitInstruction, would think JUMP_TABLE_DEBUG_INFO is a pseudo instruction and generate an error `Pseudo opcode found in emitInstruction()`.
This instruction `TargetOpcode::JUMP_TABLE_DEBUG_INFO` is only used to note jump table debug info, so we can ignore it when Mips emit instruction.

Fix #134916.

### CODE REVIEW

File: llvm/lib/Target/Mips/MipsAsmPrinter.cpp [hunk 1]
```diff
@@ -269,6 +269,10 @@ void MipsAsmPrinter::emitInstruction(const MachineInstr *MI) {
       continue;
     }
 
+    // This instruction is only used to note jump table debug info, we
+    // did not need to emit it.
+    if (I->getOpcode() == TargetOpcode::JUMP_TABLE_DEBUG_INFO)
```
Comment (wzssyqa) [inline llvm/lib/Target/Mips/MipsAsmPrinter.cpp:274]: Should it emit some debug info?

Comment (yingopq) [reply llvm/lib/Target/Mips/MipsAsmPrinter.cpp:274]: OK, I would add it.

Comment (yingopq) [reply llvm/lib/Target/Mips/MipsAsmPrinter.cpp]: Applied.

**Comment by s-barannikov** [comment]
This pseudo instruction is already skipped by the generic code in `AsmPrinter.cpp`:
https://github.com/llvm/llvm-project/blob/97a58b04c6813d8cab1bfb47ce5023895b016319/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp#L1918

The reason it got to MipsAsmPrinter is because it was bundled with `PseudoIndirectBranch`:
```
  PseudoIndirectBranch killed renamable $at {
    JUMP_TABLE_DEBUG_INFO 0
  }
```
I don't think it is intentional.

**Comment by s-barannikov** [comment]
I think a better fix would be to add `|| CurrI->isJumpTableDebugInfo()` here:
https://github.com/llvm/llvm-project/blob/b4ab53c3b04787f430c2e3484998951c48b05968/llvm/lib/Target/Mips/MipsDelaySlotFiller.cpp#L698

File: llvm/test/CodeGen/Mips/jumptable_windows.ll [hunk 2]
```diff
@@ -0,0 +1,119 @@
+; RUN: llc -mtriple=mipsel-windows-gnu < %s | FileCheck %s -check-prefix=MIPSEL
```
Comment (MaskRay) [inline llvm/test/CodeGen/Mips/jumptable_windows.ll:1]: Should use an existing jumptable*.ll test and add the windows-gnu triple there

**Comment by yingopq** [comment]
> I think a better fix would be to add `|| CurrI->isJumpTableDebugInfo()` here:
> 
> https://github.com/llvm/llvm-project/blob/b4ab53c3b04787f430c2e3484998951c48b05968/llvm/lib/Target/Mips/MipsDelaySlotFiller.cpp#L698

Good idea, thanks!

File: llvm/test/CodeGen/Mips/jumptable_windows.ll (hunk 2 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/jumptable_windows.ll:1]: The existing file named `jumptable_labels.ll`, I thought this file mainly focused on testing `labels`, so I choose to add a new file.
Since you think this is OK, I will add a -mtriple=mips-windows-gnu there.
Thanks!

Comment (MaskRay) [reply llvm/test/CodeGen/Mips/jumptable_windows.ll]: mips is under-maintained and I find many tests need refactoring. It's great to think about whether tests can be enhanced before adding a new one:) https://maskray.me/blog/2021-08-08-toolchain-testing#the-test-checks-too-little#i-dont-know-an-existing-test-can-be-enhanced

**Comment by brad0** [comment]
@wzssyqa @s-barannikov Ping.

File: llvm/lib/Target/Mips/MipsDelaySlotFiller.cpp [hunk 3]
```diff
@@ -694,8 +694,10 @@ bool MipsDelaySlotFiller::searchRange(MachineBasicBlock &MBB, IterTy Begin,
     IterTy CurrI = I;
     ++I;
     LLVM_DEBUG(dbgs() << DEBUG_TYPE ": checking instruction: "; CurrI->dump());
-    // skip debug value
-    if (CurrI->isDebugInstr()) {
+    // Skip debug value.
+    // Instruction TargetOpcode::JUMP_TABLE_DEBUG_INFO is only used to note
+    // jump table debug info, we did not need to emit it.
```
Comment (s-barannikov) [inline llvm/lib/Target/Mips/MipsDelaySlotFiller.cpp]: The last part of the comment is misleading, otherwise LGTM.

Comment (yingopq) [reply llvm/lib/Target/Mips/MipsDelaySlotFiller.cpp]: Thanks, I delete that part.

**Comment by yingopq** [comment]
@brad0 Could you help merge this pr? Maybe network problem, I can not click merge button. Thanks!
