### PR TITLE
[clang-repl] Fix error recovery while PTU cleanup

### LINKED ISSUE #123300: Clang-repl fails while trying Lambdas with capture
Unfortunately I didn't have clang-repl built locally while trying this but I tried in through xeus-cpp (a C++ Jupyter Kernel that is based on clang-repl) and also through xeus-cpp-lite (xeus-cpp + jupyterlite that helps run clang-repl completely in the browser, here's a link to try it out https://compiler-research.github.io/xeus-cpp/lab/index.html

The following fails (or rather leads to a kernel crash in my case)

```
int x = 42;
auto capture = [&]() { return x * 2; };
std::cout << capture() << "\n"; // Output: 84
```

Image

The error message is this 

Image
```
Assertion failed: getPtr() && "getFETokenInfo on an empty DeclarationName!", at: /home/runner/work/recipes/recipes/output/bld/rattler-build_llvm_1734801187/work/clang/include/clang/AST/DeclarationName.h,503,getFETokenInfo)
```

### PR DESCRIPTION
**Pull request by anutosh491**
Fixes #123300

What is seen 
```
clang-repl> int x = 42;
clang-repl> auto capture = [&]() { return x * 2; };
In file included from <<< inputs >>>:1:
input_line_4:1:17: error: non-local lambda expression cannot have a capture-default
    1 | auto capture = [&]() { return x * 2; };
      |                 ^
zsh: segmentation fault  clang-repl --Xcc="-v"

(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x0000000107b4f8b8 libclang-cpp.19.1.dylib`clang::IncrementalParser::CleanUpPTU(clang::PartialTranslationUnit&) + 988
    frame #1: 0x0000000107b4f1b4 libclang-cpp.19.1.dylib`clang::IncrementalParser::ParseOrWrapTopLevelDecl() + 416
    frame #2: 0x0000000107b4fb94 libclang-cpp.19.1.dylib`clang::IncrementalParser::Parse(llvm::StringRef) + 612
    frame #3: 0x0000000107b52fec libclang-cpp.19.1.dylib`clang::Interpreter::ParseAndExecute(llvm::StringRef, clang::Value*) + 180
    frame #4: 0x0000000100003498 clang-repl`main + 3560
    frame #5: 0x000000018d39a0e0 dyld`start + 2360
```

Though the error is justified, we shouldn't be interested in exiting through a segfault in such cases.

The issue is that empty named decls weren't being taken care of resulting into this assert 

https://github.com/llvm/llvm-project/blob/c1a229252617ed58f943bf3f4698bd8204ee0f04/clang/include/clang/AST/DeclarationName.h#L503

Can also be seen when the example is attempted through xeus-cpp-lite.

image

### CODE REVIEW

**Comment by anutosh491** [comment]
cc @ferdymercury @vgvassilev

**Comment by anutosh491** [comment]
Hmmm, the code formatter has a suggestion. Just increases the lines on a simple test. Not sure if the code formatter should be respected here !

**Comment by anutosh491** [comment]
For anyone interested in seeing the error at realtime, I am just leaving the static link for xeus-cpp-lite here.

https://compiler-research.org/xeus-cpp/lab/index.html

Possibly trying something like 
```
int x = 5;
auto capture = [&]() { return x * 2; };
```
Should display the assertion error in the console.

**Comment by anutosh491** [comment]
cc @vgvassilev

File: clang/lib/Interpreter/IncrementalParser.cpp [hunk 1]
```diff
@@ -178,8 +178,8 @@ void IncrementalParser::CleanUpPTU(TranslationUnitDecl *MostRecentTU) {
     if (!ND)
       continue;
     // Check if we need to clean up the IdResolver chain.
-    if (ND->getDeclName().getFETokenInfo() && !D->getLangOpts().ObjC &&
-        !D->getLangOpts().CPlusPlus)
+    if (!ND->getDeclName().isEmpty() && ND->getDeclName().getFETokenInfo() &&
```
Comment (vgvassilev) [inline clang/lib/Interpreter/IncrementalParser.cpp:181]: The `ND->getDeclName().isEmpty() ` needs to go in the `continue` clause.

File: clang/unittests/Interpreter/InterpreterTest.cpp [hunk 2]
```diff
@@ -114,6 +114,13 @@ TEST_F(InterpreterTest, Errors) {
 
   RecoverErr = Interp->Parse("var1 = 424;");
   EXPECT_TRUE(!!RecoverErr);
+
+  Err = Interp->Parse("int x = 5; auto capture = [&]() { return x * 2; };").takeError();
```
Comment (vgvassilev) [inline clang/unittests/Interpreter/InterpreterTest.cpp:118]: Can we move this test perhaps somewhere in `test/Interpreter/lambda.cpp`?

Comment (anutosh491) [reply clang/unittests/Interpreter/InterpreterTest.cpp:118]: Hmmm @vgvassilev 

Don't you think we should look at this from an error recovery perspective rather than something for lambdas ? If that's the case, the test is placed correctly.

The above test cause clang-repl to crash but should work if wrapped in a function or not presented as a top level decl.

Comment (vgvassilev) [reply clang/unittests/Interpreter/InterpreterTest.cpp:118]: There is no such a distinction in the test suite.

Comment (anutosh491) [reply clang/unittests/Interpreter/InterpreterTest.cpp:118]: I meant I see quite some error recovery stuff being added in this place hence I added it here !

File: clang/test/Interpreter/lambda.cpp [hunk 3]
```diff
@@ -1,7 +1,8 @@
 // REQUIRES: host-supports-jit
 // UNSUPPORTED: system-aix
 // RUN: cat %s | clang-repl | FileCheck %s
-// RUN: cat %s | clang-repl -Xcc -O2 | FileCheck %s
+// RUN: cat %s | not clang-repl -Xcc -Xclang -Xcc -verify -Xcc -O2 | FileCheck %s
```
Comment (vgvassilev) [inline clang/test/Interpreter/lambda.cpp:4]: We should not need a `not` here. You can probably avoid it by adding a correct C++ code before calling `quit`.

Comment (anutosh491) [reply clang/test/Interpreter/lambda.cpp:4]: Sure shall take care of it. Thanks

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by anutosh491** [comment]
Thanks for the review. The test lamda.cpp passes (https://github.com/llvm/llvm-project/actions/runs/13810830928/job/38631851756?pr=127467#step:4:20415) and I think this should be ready now.

**Review by vgvassilev — APPROVED** [review]
Lgtm!

File: clang/test/Interpreter/lambda.cpp [hunk 4]
```diff
@@ -14,4 +15,13 @@ auto r2 = l2();
 auto r3 = l2();
 // CHECK: TWO
 
-%quit
+// Verify non-local lambda capture error is correctly reported
+int x = 42;
+
+// expected-error {{non-local lambda expression cannot have a capture-default}}
+auto capture = [&]() { return x * 2; };
+
```
Comment (vgvassilev) [inline clang/test/Interpreter/lambda.cpp:23]: Don’t we want to check the value of X here to be 84?

Comment (anutosh491) [reply clang/test/Interpreter/lambda.cpp:23]: Sorry, I think I might have missed this. 

If I remember correctly, the above is an expected error 
```
clang-repl> int x = 42; auto capture = [&]() { return x * 2; };
In file included from <<< inputs >>>:1:
input_line_1:1:28: error: non-local lambda expression cannot have a capture-default
    1 | int x = 42; auto capture = [&]() { return x * 2; };
      |                            ^
error: Parsing failed.
```
So we wouldn't have to check for the value to be 84 here !

Comment (anutosh491) [reply clang/test/Interpreter/lambda.cpp:23]: I think this is all that we need here. Should be ready. let me try updating !

**Review by vgvassilev — APPROVED** [review]
LGTM! Thank you.

**Comment by anutosh491** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/3b4c51bb3243a02526313c51207a674139b67a00

**Comment by DavidSpickett** [comment]
After this change the test labda.cpp is failing on Linaro's Windows on Arm clang bots. They were stuck for other reasons and only just got back up to date, so here's a new build showing the failure:
https://lab.llvm.org/buildbot/#/builders/161/builds/6473
```
cat C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp | c:\users\tcwg\llvm-worker\clang-arm64-windows-msvc\build\bin\clang-repl.exe -Xcc -Xclang -Xcc -verify -Xcc -O2 | c:\users\tcwg\llvm-worker\clang-arm64-windows-msvc\build\bin\filecheck.exe C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp
# executed command: cat 'C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp'
# executed command: 'c:\users\tcwg\llvm-worker\clang-arm64-windows-msvc\build\bin\clang-repl.exe' -Xcc -Xclang -Xcc -verify -Xcc -O2
# .---command stderr------------
# | error: Parsing failed.
# `-----------------------------
# executed command: 'c:\users\tcwg\llvm-worker\clang-arm64-windows-msvc\build\bin\filecheck.exe' 'C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp'
# .---command stderr------------
# | C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp:26:11: error: CHECK: expected string not found in input
# | // CHECK: x = 42
# |           ^
# | <stdin>:4:28: note: scanning from here
# | clang-repl> clang-repl> TWO
# |                            ^
# | <stdin>:5:9: note: possible intended match here
# | clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> 
# |         ^
# | 
# | Input file: <stdin>
# | Check file: C:\Users\tcwg\llvm-worker\clang-arm64-windows-msvc\llvm-project\clang\test\Interpreter\lambda.cpp
# | 
# | -dump-input=help explains the following input dump.
# | 
# | Input was:
# | <<<<<<
# |             1: x = 42 
# |             2: clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> ONE 
# |             3: clang-repl> clang-repl> TWO 
# |             4: clang-repl> clang-repl> TWO 
# | check:26'0                                X error: no match found
# |             5: clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl>  
# | check:26'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# | check:26'1             ?                                                                                                                                                     possible intended match
# | >>>>>>
# `-----------------------------
# error: command failed with exit status: 1
--
```
I've confirmed locally that the test passed before this change.

The first RUN line is ok:
```
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\build>cat C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\clang\test\Interpreter\lambda.cpp | .\bin\clang-repl.exe
clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> ONE
clang-repl> clang-repl> TWO
clang-repl> clang-repl> TWO
clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> In file included from <<< inputs >>>:1:
input_line_21:1:17: error: non-local lambda expression cannot have a capture-default
    1 | auto capture = [&]() { return x * 2; };
      |                 ^
error: Parsing failed.
clang-repl> clang-repl> clang-repl> x = 42
clang-repl> clang-repl> clang-repl>
```
The second one fails to parse the lambda:
```
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\build>cat C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\clang\test\Interpreter\lambda.cpp | .\bin\clang-repl.exe -Xcc -Xclang -Xcc -verify -Xcc -O2
clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> ONE
clang-repl> clang-repl> TWO
clang-repl> clang-repl> TWO
clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> clang-repl> error: Parsing failed.
clang-repl> clang-repl> clang-repl> x = 42
clang-repl> clang-repl> clang-repl>
```
(also the repeated `clang-repl>` is strange but maybe that is expected?)

How can I debug this further, is there a way to enable some verbose parsing / verification? (seems more likely that verification is actually the failing part)

**Comment by DavidSpickett** [comment]
Also failing on Windows x64, but this time the error is better:
https://lab.llvm.org/buildbot/#/builders/63/builds/7023

And now I see the actual problem, all I had to do was scroll up :)
```
# .---command stderr------------
# | In file included from <<< inputs >>>:1:
# | input_line_22:1:17: error: non-local lambda expression cannot have a capture-default
# |     1 | auto capture = [&]() { return x * 2; };
# |       |                 ^
# | error: Parsing failed.
# `-----------------------------
```

Puzzling that we don't see this on other platforms though.

But this is the error message you are expecting. So it is doing what you expect but the test isn't finding the output.

**Comment by anutosh491** [comment]
Hi, 

On phone right now so shall have a better look at the error in sometime but just for some clarification, the parsing error is expected (we had a seg fault on master for this whereas a parsing error is expected and that's what the Pr is trying to achieve)

Edit: We weren't notified by any failures by the bot or the CI so it's the first time I'm seeing this. Thanks for the report.

**Comment by DavidSpickett** [comment]
Thanks for confirming, yes, your patch is working as expected but something about Windows' output is tripping up FileCheck I think.

Linux does not print the `clang-repl>` (maybe because it can tell it's outputting to a non-interactive pipe):
```
$ cat ../llvm-project/clang/test/Interpreter/lambda.cpp | ./bin/clang-repl -Xcc -Xclang -Xcc -verify -Xcc -O2
ONE
TWO
TWO
error: Parsing failed.
x = 42
```
Which should not be a problem in theory.

I'll figure it out.

**Comment by DavidSpickett** [comment]
I've disabled the failing `RUN` line on Windows and opened https://github.com/llvm/llvm-project/issues/143547 with details of what's happening.

Let me know if anything stands out to you. Also would be useful if I can see the code produced at the different optimisation levels.
