### PR TITLE
[clangd] Support .clangd command line modifications for C++ modules

### LINKED ISSUE #112635: [Clangd] C++20 modules support ignores CompileFlags.Add/Remove compiling a module preamble
When used with `compile_commands.json` clangd seem to ignore flag modifications from `.clangd` when (and only when) compiling module information, leading to module search issues

Given `compile_commands.json`:
```
[
    {
      "directory": "/path/to/example",
      "command": "/usr/bin/clang++ -std=c++23 -ffoobar test.cppm",
      "file": "test.cppm",
      "output": "build/test.cppm.o"
    },
    {
        "directory": "/path/to/example",
        "command": "/usr/bin/clang++ -std=c++23 -ffoobar main.cpp",
        "file": "main.cpp",
        "output": "build/main.cpp.o"
    }
  ]
```

`.clangd`:
```
CompileFlags:
    CompilationDatabase: "."
    Remove:
    - "-ffoobar"
```

`test.cppm`:
```
export module test;

export void test() {}
```

`main.cpp`:
```
import test;

int main() { return 0; }
```

Results in:
image

```
E[02:40:54.668] Scanning modules dependencies for /home/test/clangd_modules_test/test.cppm failed: error: unknown argument: '-ffoobar'

I[02:40:54.668] Built prerequisite modules for file /home/test/clangd_modules_test/test.cppm in 0.00 seconds
E[02:40:54.668] Scanning modules dependencies for /home/test/clangd_modules_test/main.cpp failed: error: unknown argument: '-ffoobar'

I[02:40:54.668] Built prerequisite modules for file /home/test/clangd_modules_test/main.cpp in 0.00 seconds
```

If I remove `-ffoobar` from `compile_commands.json` it works correctly

This breaks support for compiling with gcc (that requires `-fmodule-ts` and other arguments clang does not understand) and using clangd, while generating `compile_commands.json` with cmake. Using `.clangd` to remove unsupported options (and add other options needed for clang) works for the rest of the functionality but not for modules

### PR DESCRIPTION
**Pull request by petr-polezhaev**
Tunnels `Manger` object into the `ScanningAllProjectModules` so it can be used to perform necessary command-line modifications (which also adds `--resources` path previously added there explicitly). This allows using the experimental C++ modules support with gcc.

This was discussed in the issue with @ChuanqiXu9 and @kadircet

Closes #112635

### CODE REVIEW

**Review by ChuanqiXu9 — COMMENTED** [review]
Do we need to update `buildModuleFile` in `clang-tools-extra/clangd/ModulesBuilder.cpp` to update the commands to build the module interfaces?

**Comment by petr-polezhaev** [comment]
> Do we need to update `buildModuleFile` in `clang-tools-extra/clangd/ModulesBuilder.cpp` to update the commands to build the module interfaces?

It uses `GlobalCompilationDatabase::getCompileCommand` (if I correctly understand what you mean) which is overridden by `OverlayCDB::getCompileCommand` which does call the `Mangler` before returning the command, so that should already be covered

**Review by ChuanqiXu9 — APPROVED** [review]
Thanks. This looks good to me. And please give @kadircet some time to give it a look. I'll try to land this in the next week if no more comments came in.

**Comment by petr-polezhaev** [comment]
Ok. I'll wait for review confirmation and then fix the clang-format thing and merge new main

File: clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp [hunk 1]
```diff
@@ -191,6 +211,29 @@ export module M;
...
+  CDB.addFile("M.cppm", R"cpp(
+export module M;
+import Dep;
+  )cpp");
+
+  auto ProjectModules = CDB.getProjectModules(getFullPath("M.cppm"));
+  EXPECT_TRUE(
+      ProjectModules->getRequiredModules(getFullPath("M.cppm")).empty());
+
+  CDB.addExcludedFlag("-invalid-unknown-flag");
```
Comment (kadircet) [inline clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp:232]: instead of adding a new method/field to test fixture, i'd just call `ProjectModules.setCommandProvider` here.

**Review by kadircet — CHANGES_REQUESTED** [review]
thanks for working on this!

File: clang-tools-extra/clangd/ScanningProjectModules.cpp [hunk 2]
```diff
@@ -32,6 +32,9 @@ namespace {
 /// interfere with each other.
 class ModuleDependencyScanner {
 public:
+  using CommandProvider =
```
[the remark this answers is not in the document]
Comment (petr-polezhaev) [reply clang-tools-extra/clangd/ScanningProjectModules.cpp:35]: In my original approach I just made the original CommandMangler (a struct) shared_ptr and passed it here. It is also safer than to capture a reference since that's the only way how I can pass it inside the ProjectModules with the unique_function. I don't know why it's converted to a function object. Should I do it this way (shared_ptr) or keep the function thing?

It would be basically
```
virtual void setCommandMangler(std::shared_ptr<CommandMangler> Mangler);
```

File: clang-tools-extra/clangd/ScanningProjectModules.cpp [hunk 3]
```diff
@@ -32,9 +32,6 @@ namespace {
 /// interfere with each other.
 class ModuleDependencyScanner {
 public:
-  using CommandProvider =
-      llvm::unique_function<void(tooling::CompileCommand &, PathRef) const>;
-
```
Comment (petr-polezhaev) [inline clang-tools-extra/clangd/ScanningProjectModules.cpp]: Or `using CommandMangler = ProjectModules::CommandMangler`?

File: clang-tools-extra/clangd/GlobalCompilationDatabase.cpp [hunk 4]
```diff
@@ -833,8 +833,8 @@ bool OverlayCDB::setCompileCommand(PathRef File,
 std::unique_ptr<ProjectModules>
 OverlayCDB::getProjectModules(PathRef File) const {
   auto MDB = DelegatingCDB::getProjectModules(File);
-  MDB->setCommandProvider([&Mangler = Mangler](tooling::CompileCommand &Command,
-                                               PathRef CommandPath) {
+  MDB->setCommandMangler([&Mangler = Mangler](tooling::CompileCommand &Command,
```
Comment (petr-polezhaev) [inline clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:836]: @kadircet this is what I was talking about with unsafe reference capturing. The solution (while keeping lambda compatibility for unit-tests) would be to make the function copyable but pass the Mangler by the `shared_ptr` into the very first instance.

File: clang-tools-extra/clangd/ProjectModules.h [hunk 5]
```diff
@@ -9,12 +9,17 @@
...
 
+#include "support/Function.h"
 #include "support/Path.h"
 #include "support/ThreadsafeFS.h"
 
 #include <memory>
 
 namespace clang {
+namespace tooling {
+class CompileCommand;
```
Comment (kadircet) [inline clang-tools-extra/clangd/ProjectModules.h:20]: ah sorry I missed the dep on `tooling::CompileCommand`. feel free to re-add `#include "clang/Tooling/CompilationDatabase.h"` instead of the forward-decl.

File: clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp [hunk 6]
```diff
@@ -38,10 +39,6 @@ class MockDirectoryCompilationDatabase : public MockCompilationDatabase {
 
   void addFile(llvm::StringRef Path, llvm::StringRef Contents);
 
-  std::unique_ptr<ProjectModules> getProjectModules(PathRef) const override {
-    return scanningProjectModules(MockedCDBPtr, TFS);
-  }
-
```
Comment (kadircet) [inline clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp:44]: i think we still need to override this

File: clang-tools-extra/clangd/ScanningProjectModules.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (kadircet) [reply clang-tools-extra/clangd/ScanningProjectModules.cpp]: Sorry I was just trying to say we don't need to have the same type-alias both in ModuleDependencyScanner and ProjectModules, you already unified them, so my comment is addressed.

**Review by kadircet — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp (hunk 6 above)
Comment (petr-polezhaev) [reply clang-tools-extra/clangd/unittests/PrerequisiteModulesTest.cpp:44]: True. My bad, removed that accidentally - should have ran unit-tests before updating.

**Review by kadircet — APPROVED** [review]
thanks!

**Comment by petr-polezhaev** [comment]
rebased on the latest main squashing all fixes

**Comment by ChuanqiXu9** [comment]
Given @kadircet is approved and @petr-polezhaev is marked as `first-time contributor`, I'll merge this by assuming you don't have the commit access.

**Comment by ChuanqiXu9** [comment]
@petr-polezhaev please update the mail address. We don't like github.reply mail address.

**Comment by petr-polezhaev** [comment]
Didn't knew that's a thing now. Removed the checkbox over the private email, should be ok now. Somehow missed the clang-format issue again (I thought I fixed it) - updated to calm it down

File: clang-tools-extra/clangd/GlobalCompilationDatabase.cpp [hunk 7]
```diff
@@ -830,6 +830,16 @@ bool OverlayCDB::setCompileCommand(PathRef File,
...
 }
 
+std::unique_ptr<ProjectModules>
+OverlayCDB::getProjectModules(PathRef File) const {
+  auto MDB = DelegatingCDB::getProjectModules(File);
+  MDB->setCommandMangler([&Mangler = Mangler](tooling::CompileCommand &Command,
+                                              PathRef CommandPath) {
+    Mangler(Command, CommandPath);
+  });
+  return std::move(MDB);
```
Comment (mikaelholmen) [inline clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840]: Hi @petr-polezhaev 

I see that clang (18.1.8) complains on this move:
```
12:29:43 ../llvm-project/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840:10: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
12:29:43   840 |   return std::move(MDB);
12:29:43       |          ^
12:29:43 ../llvm-project/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840:10: note: remove std::move call here
12:29:43   840 |   return std::move(MDB);
12:29:43       |          ^~~~~~~~~~   ~
12:29:43 1 error generated.
```

Comment (petr-polezhaev) [reply clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840]: :disappointed: Can't do anything about it - I don't have write permissions. Can you revert it and I'll resubmit the review?

Comment (kadircet) [reply clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840]: oops sorry for missing that, should be fixed with a2063ba7ffdbbb4faf5da5f32739ab761c2e4289

Comment (mikaelholmen) [reply clang-tools-extra/clangd/GlobalCompilationDatabase.cpp:840]: Thanks!
