### PR TITLE
[clang-tidy] Fix performance-move-const-arg false negative in ternary…

### LINKED ISSUE #126515: `performance-move-const-arg` not detected with ternary
```cpp
#include <string>

void func(const std::string&);

void f(bool b)
{
    std::string s;
    func(b ? "" : std::move(s));
}
```

https://godbolt.org/z/q8Phdzfea

### PR DESCRIPTION
**Pull request by RiverDave**
This PR aims to fix `performance-move-const-arg` #126515

## Changes
Enhanced the `performance-move-arg` check in Clang-Tidy to detect cases where `std::move` is used
 in **ternary operator expressions which was not being matched therefore being tagged as a false negative**

## Testing
- A new mock class has been where the changes have been tested  & all tests pass

I'd appreciate any feedback since this is my first time contributing to LLVM.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp [hunk 1]
```diff
@@ -44,6 +44,12 @@ void MoveConstArgCheck::registerMatchers(MatchFinder *Finder) {
                unless(isInTemplateInstantiation()))
           .bind("call-move");
 
+  // Match ternary expressions where either branch contains std::move
+  auto TernaryWithMoveMatcher =
+      conditionalOperator(
+            hasDescendant(MoveCallMatcher)
+      ).bind("ternary-move");
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp:51]:
```suggestion
      );
```
bind isonly needed when you want to use it later.

**Review by HerrCai0907 — APPROVED** [review]
lgtm. please run git-clang-format also. i think there are format issue in the new code.

File: clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp (hunk 1 above)
Comment (RiverDave) [reply clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp]: Amazing! Appreciate your feedback, all of your comments should be addressed by now.

**Comment by RiverDave** [comment]
Thx @HerrCai0907, your feedback has been addresed.

**Comment by RiverDave** [comment]
> lgtm. please run git-clang-format also. i think there are format issue in the new code.

Thx @HerrCai0907, your feedback has been addresed.

**Comment by RiverDave** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> 
> You can test this locally with the following command:
> ```shell
> git-clang-format --diff 5d501c6137976ff1f14f3b0e2e593fb9740d0146 848be2ccd25fd68b6a2d2037198184b08ff5d6e2 --extensions cpp -- clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp clang-tools-extra/test/clang-tidy/checkers/performance/move-const-arg.cpp
> ```
> 
> View the diff from clang-format here.
> ```diff
> diff --git a/clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp b/clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp
> index 553c1d20cb..703ad162f9 100644
> --- a/clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp
> +++ b/clang-tools-extra/clang-tidy/performance/MoveConstArgCheck.cpp
> @@ -63,16 +63,15 @@ void MoveConstArgCheck::registerMatchers(MatchFinder *Finder) {
>    // Matches respective ParmVarDecl for a CallExpr or CXXConstructExpr.
>    auto ArgumentWithParamMatcher = forEachArgumentWithParam(
>        anyOf(MoveCallMatcher, TernaryWithMoveMatcher),
> -      parmVarDecl(anyOf(hasType(ConstTypeParmMatcher),
> -                                         hasType(RValueTypeParmMatcher)))
> -                           .bind("invocation-parm"));
> +      parmVarDecl(
> +          anyOf(hasType(ConstTypeParmMatcher), hasType(RValueTypeParmMatcher)))
> +          .bind("invocation-parm"));
>    // Matches respective types of arguments for a CallExpr or CXXConstructExpr
>    // and it works on calls through function pointers as well.
>    auto ArgumentWithParamTypeMatcher = forEachArgumentWithParamType(
>        anyOf(MoveCallMatcher, TernaryWithMoveMatcher),
>        anyOf(ConstTypeParmMatcher, RValueTypeParmMatcher));
>  
> -
>    Finder->addMatcher(
>        invocation(anyOf(ArgumentWithParamMatcher, ArgumentWithParamTypeMatcher))
>            .bind("receiving-expr"),
> ```

This should be fixed now
