### PR TITLE
[LLVM] Update CUDA ELF flags for their new ABI

### LINKED ISSUE #148703: [Offload] Failure to check validity of image for sm_120 architecture
When compiling an offloading capable compiler with the recommended CMake cache file,
```
cd llvm-project
mkdir build
cd build
cmake ../llvm -G Ninja \
    -C ../offload/cmake/caches/Offload.cmake \
    -DCMAKE_BUILD_TYPE="Release" \
    -DCMAKE_INSTALL_PREFIX="/opt/llvm/llvm-project/install" \
    -DCMAKE_C_COMPILER="clang-19" \
    -DCMAKE_CXX_COMPILER="clang++-19" \
    -DLIBOMPTARGET_ENABLE_DEBUG=ON
ninja -j 24 install
```
running an executable containing any offloading with `OMP_TARGET_OFFLOAD=mandatory ./a.out` and `LIBOMPTARGET_DEBUG=1` crashes with
```
omptarget --> Init offload library!
OMPT --> Entering connectLibrary
OMPT --> OMPT: Trying to load library libomp.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomp_connect
OMPT --> OMPT: Library connection handle = 0x70ef79559e60
OMPT --> Exiting connectLibrary
omptarget --> Loading RTLs...
omptarget --> RTLs loaded!
PluginInterface --> Failure to check validity of image 0x5651b5deed20: Invalid CUDA addressing modePluginInterface --> Failure to check validity of image 0x5651b5deed20: Invalid CUDA addressing modePluginInterface --> Failure to check validity of image 0x5651b5deed20: Invalid CUDA addressing modeomptarget --> No RTL found for image 0x00005651b5dea120!
omptarget --> Done registering entries!
omptarget --> Entering target region for device -1 with entry point 0x00005651b5dea047
omptarget --> Use default device id 0
omptarget --> Call to omp_get_num_devices returning 0
omptarget --> omp_get_num_devices() == 0 but offload is manadatory
omptarget error: Consult https://openmp.llvm.org/design/Runtimes.html for debugging options.
omptarget error: No images found compatible with the installed hardware. Segmentation fault (core dumped)

```
on an RTX 5070ti (sm_120 architecture).

In the related discussion on the llvm discourse (https://discourse.llvm.org/t/issues-compiling-with-offloading-support/87258/7), @jhuber6  suspects a change in the CUDA ELF ABI, see `PluginInterface --> Failure to check validity of image 0x5651b5deed20: Invalid CUDA addressing mode`, which is related to (https://github.com/llvm/llvm-project/blob/main/offload/plugins-nextgen/common/src/Utils/ELF.cpp#L76) is causing this issue.

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
We rely on these flags to do things in the runtime and print the
contents of binaries correctly. CUDA updated their ABI encoding recently
and we didn't handle that. it's a new ABI entirely so we just select on
it when it shows up.

Fixes: https://github.com/llvm/llvm-project/issues/148703

### CODE REVIEW

**Comment by jhuber6** [comment]
@jafudev can you confirm this works, I don't have an sm_100 or sm_120 to test it on.

File: llvm/lib/Object/ELFObjectFile.cpp [hunk 1]
```diff
@@ -679,7 +681,18 @@ StringRef ELFObjectFileBase::getNVPTXCPUName() const {
 
   // Hopper architecture.
   case ELF::EF_CUDA_SM90:
-    return getPlatformFlags() & ELF::EF_CUDA_ACCELERATORS ? "sm_90a" : "sm_90";
+    return getPlatformFlags() & ELF::EF_CUDA_ACCELERATORS_V1 ? "sm_90a"
+                                                             : "sm_90";
```
Comment (Artem-B) [inline llvm/lib/Object/ELFObjectFile.cpp:685]: Do they have any extra flags for the recently added `f` variants of the architecture?

**Review by Artem-B — APPROVED** [review]
LGTM

File: llvm/lib/Object/ELFObjectFile.cpp (hunk 1 above)
Comment (jhuber6) [reply llvm/lib/Object/ELFObjectFile.cpp:685]: Oh, I don't know about those. I just checked `-march=sm_100a` or whatever. Do we support those variants?

Comment (Artem-B) [reply llvm/lib/Object/ELFObjectFile.cpp:685]: They've been added in LLVM, but we didn't plumb that through into clang driver yet.

https://github.com/llvm/llvm-project/blob/de59e7b86cd349f9f74b7561594aeae410477326/llvm/lib/Target/NVPTX/NVPTXSubtarget.h#L158

File: llvm/lib/BinaryFormat/ELF.cpp [hunk 2]
```diff
@@ -652,6 +652,7 @@ uint8_t ELF::convertNameToOSABI(StringRef Name) {
       .StartsWith("fenixos", ELFOSABI_FENIXOS)
       .StartsWith("cloudabi", ELFOSABI_CLOUDABI)
       .StartsWith("cuda", ELFOSABI_CUDA)
+      .StartsWith("cuda", ELFOSABI_CUDA_V2)
```
Comment (arsenm) [inline llvm/lib/BinaryFormat/ELF.cpp:655]: This won't be reachable?

Comment (jhuber6) [reply llvm/lib/BinaryFormat/ELF.cpp:655]: Right, forgot that this is the reverse where it's impossible.

Comment (jhuber6) [reply llvm/lib/BinaryFormat/ELF.cpp:655]: I guess this part doesn't matter that much, we can probably just replace the old one. No clue why they changed this part honestly.

**Comment by jafudev** [comment]
> @jafudev can you confirm this works, I don't have an sm_100 or sm_120 to test it on.

Does not work on my system yet, getting similar errors as before. I will try to make it work

File: offload/plugins-nextgen/common/src/Utils/ELF.cpp [hunk 3]
```diff
@@ -73,10 +73,17 @@ checkMachineImpl(const object::ELFObjectFile<ELFT> &ELFObj, uint16_t EMachine) {
...
+      if (~Header.e_flags & EF_CUDA_64BIT_ADDRESS)
+        return createError("Invalid CUDA addressing mode");
+      if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35)
+        return createError("Unsupported NVPTX architecture");
+    } else if (Header.e_ident[EI_ABIVERSION] != ELFABIVERSION_CUDA_V2) {
+      if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM100)
+        return createError("Unsupported NVPTX architecture");
+    } else {
+      return createError("Invalid CUDA ABI version");
+    }
```
Comment (jafudev) [inline offload/plugins-nextgen/common/src/Utils/ELF.cpp:86]: Here I don't understand the reason for flipping the comparison operator to `!=`. If we use `==` instead, then the checks for CUDAv1 are still the old behavior while for CUDAv2 we only check if the architecture if below 100 to create an error. To get the correct SM for CUDAv2 I think we should also change the flag to `EF_CUDA_SM_MASK`.
This way I can pass these checks with sm_120 on my machine. But please correct me if my logic is flawed.

```suggestion
    if (Header.e_ident[EI_ABIVERSION] == ELFABIVERSION_CUDA_V1) {
      if (~Header.e_flags & EF_CUDA_64BIT_ADDRESS)
        return createError("Invalid CUDA addressing mode");
      if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35)
        return createError("Unsupported NVPTX architecture");
    } else if (Header.e_ident[EI_ABIVERSION] == ELFABIVERSION_CUDA_V2) {
      if ((Header.e_flags & EF_CUDA_SM_MASK) < EF_CUDA_SM100)
        return createError("Unsupported NVPTX architecture");
    } else {
      return createError("Invalid CUDA ABI version");
    }
```

File: offload/plugins-nextgen/common/src/Utils/ELF.cpp [hunk 4]
```diff
@@ -60,23 +60,30 @@ static Expected<bool>
...
-      return createError("Invalid CUDA addressing mode");
-    if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35)
-      return createError("Unsupported NVPTX architecture");
+    if (Header.e_ident[EI_ABIVERSION] == ELFABIVERSION_CUDA_V1) {
+      if (~Header.e_flags & EF_CUDA_64BIT_ADDRESS)
+        return createError("invalid CUDA addressing mode");
+      if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM35)
+        return createError("unsupported NVPTX architecture");
+    } else if (Header.e_ident[EI_ABIVERSION] == ELFABIVERSION_CUDA_V2) {
+      if ((Header.e_flags & EF_CUDA_SM) < EF_CUDA_SM100)
```
Comment (jfuchs-kmt) [inline offload/plugins-nextgen/common/src/Utils/ELF.cpp:82]: Just want to point this out again such that it does not get lost in the resolved thread.
```suggestion
      if ((Header.e_flags & EF_CUDA_SM_MASK) < EF_CUDA_SM100)
```

Comment (jfuchs-kmt) [reply offload/plugins-nextgen/common/src/Utils/ELF.cpp]: @jhuber6 Perfect, all good now from my side and testing with sm_120 (sorry for mixing up accounts now)
