### PR TITLE
[OpenMP][OMPIRBuilder] Support complex types in atomic update/capture

### LINKED ISSUE #191317: [Flang][OpenMP] Compiler crach on OpenMP atomic capture with complex type swap
Flang crashes with an assertion failure when compiling `!$omp atomic capture`
with complex types in the swap pattern (`v = x; x = expr`). The crash occurs
in `llvm::IntegerType::get()` because `getScalarSizeInBits()` returns 0 for
struct types like `{float, float}`.

Reproducer (https://godbolt.org/z/s3q433E9e):

```fortran
subroutine test_swap(x, v, expr)
  complex(4) :: x, v, expr
  !$omp atomic capture
  v = x
  x = expr
  !$omp end atomic
end subroutine
```

```
flang -fopenmp -fopenmp-version=40 repro.f90 -c
```

Error message:
```
flang-23: warning: argument unused during compilation: '-c' [-Wunused-command-line-argument]
warning: OpenMP support for version 40 in flang is still incomplete
atomic memory access' size must be byte-sized
 i0  %.atomic.load = load atomic i0, ptr %0 monotonic, align 1
IntToPtr result must be a pointer
  %.atomic.ptrCast = inttoptr i0 %5 to { float, float }
atomic memory access' size must be byte-sized
 i0  %7 = cmpxchg ptr %0, i0 %5, i0 %6 monotonic monotonic, align 9223372036854775808
error: failed to create the LLVM module
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by chichunchen**
Route struct-typed values through the libcall path in `emitAtomicUpdate`.

Previously, the libcall path was gated on `RMWOp == BAD_BINOP`, so atomic capture swap patterns (`v = x; x = expr`) for complex values lowered as structs fell through to the cmpxchg path. That path called `getScalarSizeInBits()` on a struct type, produced 0, and triggered an assertion in `IntegerType::get()`.

Remove the `BAD_BINOP` restriction so struct types always use the libcall path. This is safe because the libcall path does not use `RMWOp` and already handles arbitrary type sizes correctly.

Also fix `LoadSize` in the libcall path to use `XElemTy` rather than the pointer type, which previously gave the wrong size for larger complex types such as `complex(8)`.

Fixes https://github.com/llvm/llvm-project/issues/191317

Assisted with copilot and GPT-5.4

### CODE REVIEW

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
Comment (NimishMishra) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:10554]: If I understand correctly, earlier `llvm::AtomicRMWInst::BinOp::BAD_BINOP` was leading to emission of the atomic libcall, which this PR removes. So what is the fallback execution path for `llvm::AtomicRMWInst::BinOp::BAD_BINOP` or is BAD_BINOP removed completely?

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -10694,7 +10664,7 @@ OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::createAtomicCapture(
            "OMP Atomic expects a pointer to target memory");
     Type *XElemTy = X.ElemTy;
     assert((XElemTy->isFloatingPointTy() || XElemTy->isIntegerTy() ||
-            XElemTy->isPointerTy()) &&
+            XElemTy->isPointerTy() || XElemTy->isStructTy()) &&
            "OMP atomic capture expected a scalar type");
```
Comment (NimishMishra) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp]: We can update this assertion's statement, since clearly we support non-scalar (i.e. structure types) now.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
Comment (NimishMishra) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:10554]: This is especially important if there exist cases which emit BAD_BINOP for non-struct types too (pointers, intrinsics etc; I am not very sure, but I think we have to think beyond structure types).

**Review by NimishMishra — COMMENTED** [review]
Thanks for the PR. A few comments

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
Comment (chichunchen) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:10554]: The `BAD_BINOP` fallback is unchanged for non-struct types. The three paths in `emitAtomicUpdate`:

1. emitRMWOp: integer types with recognized binop -> atomicrmw
2. isStructTy(): structTypes (any RMWOp) -> libcall path
3. else: everything else (float, pointer with `BAD_BINOP` or unrecognized ops) -> cmpxchg loop via `Integer::get(getScalarSizeInBits())`

`BAD_BINOP` for non-struct types still reaches path 3, which works fine because `getScalarSizeInBits()` returns correct values for floats and pointers. (Only struct returns 0).

Comment (NimishMishra) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:10554]: Okay thanks

Comment (chichunchen) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:10554]: Only the scalar types can trigger the Default(BAD_BINOP) case in`convertBinOpToAtomic` (OpenMPToLLVMIRTranslation.cpp), 

```
/// Converts an LLVM dialect binary operation to the corresponding enum value
/// for `atomicrmw` supported binary operation.
static llvm::AtomicRMWInst::BinOp convertBinOpToAtomic(Operation &op) {
  return llvm::TypeSwitch<Operation *, llvm::AtomicRMWInst::BinOp>(&op)
      .Case([&](LLVM::AddOp) { return llvm::AtomicRMWInst::BinOp::Add; })
      .Case([&](LLVM::SubOp) { return llvm::AtomicRMWInst::BinOp::Sub; })
      .Case([&](LLVM::AndOp) { return llvm::AtomicRMWInst::BinOp::And; })
      .Case([&](LLVM::OrOp) { return llvm::AtomicRMWInst::BinOp::Or; })
      .Case([&](LLVM::XOrOp) { return llvm::AtomicRMWInst::BinOp::Xor; })
      .Case([&](LLVM::UMaxOp) { return llvm::AtomicRMWInst::BinOp::UMax; })
      .Case([&](LLVM::UMinOp) { return llvm::AtomicRMWInst::BinOp::UMin; })
      .Case([&](LLVM::FAddOp) { return llvm::AtomicRMWInst::BinOp::FAdd; })
      .Case([&](LLVM::FSubOp) { return llvm::AtomicRMWInst::BinOp::FSub; })
      .Default(llvm::AtomicRMWInst::BinOp::BAD_BINOP);
}
```

**Comment by chichunchen** [comment]
Updated assert message and add more tests (double complex using libcall and fallback tests for BAD_BINOP) in https://github.com/llvm/llvm-project/pull/191490/changes/2db12cc7ecc667e3ce1628f54fd3b4a4b5177436

**Comment by chichunchen** [comment]
ping

**Review by NimishMishra — APPROVED** [review]
LGTM. 

Please wait a while to see if anyone else wishes to take a look

**Review by Meinersbur — APPROVED** [review]
