### PR TITLE
[libc] Update the AMDGPU implementation to use code object 5

### LINKED ISSUE #72517: [AMDGPU] Kernel hangs when compiled with code-object version 5 due to insufficient stack
The `libc` test suite currently cannot be updated to code-object version 5 because of  an observed hang while calling global constructors. The following LLVM-IR also in https://godbolt.org/z/9j9TWPfaK causes issues only when the `amdgpu_code_object_version` metadata is set to `500` and when optimizations are turned on. This is taken from the kernel in `libc` that simply iterates the `__init_array_end` and `__init_array_start` array and invokes function pointers. Note that this issue is present even when the loop body is never executed.

```llvm
; ModuleID = 'image.0.5.precodegen.bc'
source_filename = "ld-temp.o"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8"
target triple = "amdgcn-amd-amdhsa"

@__init_array_end = external hidden addrspace(1) global [0 x i64], align 8
@__init_array_start = external hidden addrspace(1) global [0 x i64], align 8

; Function Attrs: mustprogress
define protected amdgpu_kernel void @_begin(i32 noundef %argc, ptr noundef %argv, ptr noundef %env) local_unnamed_addr #0 {
entry:
  br i1 icmp eq (i64 sub (i64 ptrtoint (ptr addrspacecast (ptr addrspace(1) @__init_array_end to ptr) to i64), i64 ptrtoint (ptr addrspacecast (ptr addrspace(1) @__init_array_start to ptr) to i64)), i64 0), label %exit, label %for.body.preheader.i

for.body.preheader.i:                             ; preds = %entry
  %sub.ptr.div.i = ashr exact i64 sub (i64 ptrtoint (ptr addrspacecast (ptr addrspace(1) @__init_array_end to ptr) to i64), i64 ptrtoint (ptr addrspacecast (ptr addrspace(1) @__init_array_start to ptr) to i64)), 3
  %umax.i = tail call i64 @llvm.umax.i64(i64 %sub.ptr.div.i, i64 1)
  br label %for.body.i

for.body.i:                                       ; preds = %for.body.i, %for.body.preheader.i
  %i.04.i = phi i64 [ %inc.i, %for.body.i ], [ 0, %for.body.preheader.i ]
  %arrayidx.i = getelementptr inbounds [0 x i64], ptr addrspace(1) @__init_array_start, i64 0, i64 %i.04.i
  %0 = load i64, ptr addrspace(1) %arrayidx.i, align 8, !tbaa !8
  %1 = inttoptr i64 %0 to ptr
  tail call void %1(i32 noundef %argc, ptr noundef %argv, ptr noundef %env) #4
  %inc.i = add nuw i64 %i.04.i, 1
  %exitcond.not.i = icmp eq i64 %inc.i, %umax.i
  br i1 %exitcond.not.i, label %exit, label %for.body.i, !llvm.loop !12

exit: ; preds = %for.body.i, %entry
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.umax.i64(i64, i64) #1

attributes #0 = { mustprogress "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { mustprogress nofree norecurse nounwind willreturn memory(argmem: readwrite) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #3 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #4 = { nobuiltin }

!opencl.ocl.version = !{!0, !0, !0}
!llvm.ident = !{!1, !2, !1, !2, !1, !2}
!llvm.module.flags = !{!3, !4, !5, !6, !7}

!0 = !{i32 2, i32 0}
!1 = !{!"clang version 18.0.0"}
!2 = !{!"clang version 16.0.0"}
!3 = !{i32 1, !"amdgpu_code_object_version", i32 500}
!4 = !{i32 1, !"wchar_size", i32 4}
!5 = !{i32 8, !"PIC Level", i32 1}
!6 = !{i32 1, !"ThinLTO", i32 0}
!7 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!8 = !{!9, !9, i64 0}
!9 = !{!"long", !10, i64 0}
!10 = !{!"omnipotent char", !11, i64 0}
!11 = !{!"Simple C++ TBAA"}
!12 = distinct !{!12, !13}
!13 = !{!"llvm.loop.mustprogress"}
```

The issue I have found is caused by the emission of the `.private_segment_fixed_size` kernel metadata being incorrectly set to zero after optimizations. If I take the GCN and manually edit the metadata to set `private_segment_fixed_size` to a non-zero value the kernel no longer hangs. To reproduce, use the following command line invocation:
```
$ clang bad.ll --target=amdgcn-amd-amdhsa -mcpu=gfx1030 -O1 -c; llvm-readelf --notes bad.o | grep 'private_segment'
```

If you change the `amdgpu_code_object_version` value to instead be `400` in the source, the issue goes away as the stack is no-longer set to zero.

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
This patch includes the necessary changes to make the `libc` tests
running on AMD GPUs run using the newer code object version. The 'code
object version' is AMD's internal ABI for making kernel calls. The move
from 4 to 5 changed how we handle arguments for builtins such as
obtaining the grid size or setting up the size of the private stack.

Fixes: https://github.com/llvm/llvm-project/issues/72517

### CODE REVIEW

File: libc/utils/gpu/loader/amdgpu/Loader.cpp [hunk 1]
```diff
@@ -34,6 +34,19 @@
...
+// The implicit arguments of COV5 AMDGPU kernels.
+struct implicit_args_t {
+  uint32_t grid_size_x;
+  uint32_t grid_size_y;
+  uint32_t grid_size_z;
+  uint16_t workgroup_size_x;
+  uint16_t workgroup_size_y;
+  uint16_t workgroup_size_z;
+  uint8_t Unused0[46];
+  uint16_t gird_dims;
```
Comment (arsenm) [inline libc/utils/gpu/loader/amdgpu/Loader.cpp:46]: 'gird'

File: libc/utils/gpu/loader/amdgpu/Loader.cpp [hunk 2]
```diff
@@ -222,17 +250,15 @@ hsa_status_t launch_kernel(hsa_agent_t dev_agent, hsa_executable_t executable,
...
+  uint16_t setup = (dims) << HSA_KERNEL_DISPATCH_PACKET_SETUP_DIMENSIONS;
   packet->workgroup_size_x = params.num_threads_x;
   packet->workgroup_size_y = params.num_threads_y;
   packet->workgroup_size_z = params.num_threads_z;
   packet->reserved0 = 0;
   packet->grid_size_x = params.num_blocks_x * params.num_threads_x;
   packet->grid_size_y = params.num_blocks_y * params.num_threads_y;
   packet->grid_size_z = params.num_blocks_z * params.num_threads_z;
-  packet->private_segment_size = private_size;
+  packet->private_segment_size = !dynamic_stack ? private_size : 16834;
```
Comment (arsenm) [inline libc/utils/gpu/loader/amdgpu/Loader.cpp:261]: This is backwards, the assume dynamic access is 16k thing was a backend hack that doesn't require runtime replication. Also that's unnecessary in v5 anyway, so just use the raw size?

Also we really need some unit tests that stress dynamic alloca somewhere

Comment (jhuber6) [reply libc/utils/gpu/loader/amdgpu/Loader.cpp:261]: If the `dynamic_stack` is set then I think the private segment is just zero and the runtime is expected to set it like here. I'm pretty sure the expectation is that `dynamic_stack` only applies if the `private_segment` couldn't be determined.

Comment (arsenm) [reply libc/utils/gpu/loader/amdgpu/Loader.cpp:261]: CUDA and HIP have a runtime API to set the assumed stack size in the unknown case, this ideally would replicate such an API

File: libc/utils/gpu/loader/amdgpu/Loader.cpp [hunk 3]
```diff
@@ -34,6 +34,19 @@
 #include <tuple>
 #include <utility>
 
+// The implicit arguments of COV5 AMDGPU kernels.
```
Comment (saiislam) [inline libc/utils/gpu/loader/amdgpu/Loader.cpp:37]: Is there a way to share this structure between here and `openmp/libomptarget/plugins-nextgen/amdgpu/utils/UtilitiesRTL.h`?

Otherwise, someone will have to keep updating this whenever there are changes in the AMDGPU plugin (like #65325 )

Comment (jhuber6) [reply libc/utils/gpu/loader/amdgpu/Loader.cpp:37]: Yeah that's a future endeavor. Probably something that could be solved by having the offloading  directory for a lot of these HSA wrappers. For now it's easier to keep them separate.

File: libc/utils/gpu/loader/amdgpu/Loader.cpp [hunk 4]
```diff
@@ -222,17 +250,15 @@ hsa_status_t launch_kernel(hsa_agent_t dev_agent, hsa_executable_t executable,
...
+  uint16_t setup = (dims) << HSA_KERNEL_DISPATCH_PACKET_SETUP_DIMENSIONS;
   packet->workgroup_size_x = params.num_threads_x;
   packet->workgroup_size_y = params.num_threads_y;
   packet->workgroup_size_z = params.num_threads_z;
   packet->reserved0 = 0;
   packet->grid_size_x = params.num_blocks_x * params.num_threads_x;
   packet->grid_size_y = params.num_blocks_y * params.num_threads_y;
   packet->grid_size_z = params.num_blocks_z * params.num_threads_z;
-  packet->private_segment_size = private_size;
+  packet->private_segment_size = !dynamic_stack ? private_size : 3 * 1024;
```
[the remark this answers is not in the document]
Comment (jhuber6) [reply libc/utils/gpu/loader/amdgpu/Loader.cpp:261]: So, this is a sufficiently small amount to run all the `libc` tests and mimics the size used for the NVIDIA tests. It's easier on resources when running a bunch of these in parallel to keep the stack usage small.

File: libc/utils/gpu/loader/amdgpu/Loader.cpp [hunk 5]
```diff
@@ -222,17 +250,16 @@ hsa_status_t launch_kernel(hsa_agent_t dev_agent, hsa_executable_t executable,
...
   packet->workgroup_size_x = params.num_threads_x;
   packet->workgroup_size_y = params.num_threads_y;
   packet->workgroup_size_z = params.num_threads_z;
   packet->reserved0 = 0;
   packet->grid_size_x = params.num_blocks_x * params.num_threads_x;
   packet->grid_size_y = params.num_blocks_y * params.num_threads_y;
   packet->grid_size_z = params.num_blocks_z * params.num_threads_z;
-  packet->private_segment_size = private_size;
+  packet->private_segment_size =
+      dynamic_stack ? 16 * 1024 /* 16 KB */ : private_size;
```
Comment (JonChesterfield) [inline libc/utils/gpu/loader/amdgpu/Loader.cpp:262]: maybe write `enum {stack_size_default = 16*1024} or similar instead of the comment

**Review by JonChesterfield — APPROVED** [review]

**Review by saiislam — APPROVED** [review]
LGTM!

File: libc/utils/gpu/loader/amdgpu/Loader.cpp (hunk 5 above)
Comment (arsenm) [reply libc/utils/gpu/loader/amdgpu/Loader.cpp:262]: Should probably get a fixme to add some knob for this
