### PR TITLE
[Clang] enhance loop analysis to handle variable changes inside lambdas

### LINKED ISSUE #132038: [clang++]: Incorrect warning emited for [-Wfor-loop-analysis]
Warning correctly states that the variables are not modified in the loop body, but `height` is incremented nevertheless (in the  `incr_height` lambda) and the loop is fine.

See example program:

```
// compile with `clang++-20 -std=c++20 -Wall -c loop.cpp`
//
// ~/tmp ❯ clang++-20 -std=c++20 -Wall -c loop.cpp
// loop.cpp:10:35: warning: variables 'height' and 'end_height' used in loop condition not modified in loop body [-Wfor-loop-analysis]
//    10 |    for (uint32_t end_height = 27; height <= end_height; incr_height())
//       |                                   ^~~~~~    ~~~~~~~~~~
// 1 warning generated.
// -----------------------------------------------------------------------------------------------------------------------------------
#include <cstdint>

extern void add_to_expected_table(uint32_t h);

void test() {
   uint32_t height = 0;

   auto incr_height = [&height]() { ++height; };

   for (uint32_t end_height = 27; height <= end_height; incr_height())
      add_to_expected_table(height);
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #132038 

--- 

This PR extends `-Wloop-analysis` to handle variable modifications inside lambda expressions.

### CODE REVIEW

File: clang/test/SemaCXX/warn-loop-analysis.cpp [hunk 1]
```diff
@@ -299,3 +299,18 @@ void test10() {
   for (auto[i, j, k] = arr; i < a; ++i) { }
   for (auto[i, j, k] = arr; i < a; ++arr[0]) { }
 };
+
+extern void foo(int);
```
Comment (shafik) [inline clang/test/SemaCXX/warn-loop-analysis.cpp:303]: We normally wrap tests from bug reports in `namespace GHXXXX` where XXXX is the bug report number.

Comment (shafik) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:303]: Can we also get tests that show diagnostics for lambda cases as well.

Comment (a-tarasyuk) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:304]: @shafik, thanks for the review. I've updated tests

**Review by cor3ntin — APPROVED** [review]
LGTM, Thanks!

File: clang/test/SemaCXX/warn-loop-analysis.cpp [hunk 2]
```diff
@@ -299,3 +299,38 @@ void test10() {
...
+  auto incr_a = [&a]() { ++a; };
+
+  for (int b = 10; a <= b; incr_a())
+    foo(a);
+
+  for (int b = 10; a <= b;)
+    incr_a();
+
+  for (int b = 10; a <= b; [&a]() { ++a; }()) { }
+  for (int b = 10; a <= b; [&a]() { }()) { }
```
Comment (zyn0217) [inline clang/test/SemaCXX/warn-loop-analysis.cpp:316]: do you know why we don't complain about this case?

Comment (a-tarasyuk) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:316]: @zyn0217, that's a good question. In this case, I followed a similar example with functions where the body isn't taken into account

https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L23

https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L8

Comment (zyn0217) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:316]: Can you test this case?

```cpp
void test() {
  int a = 0;
  int *b = &a;
  auto increase = [b]() { ++*b; };
  for (int a = 10; a <= 20; increase()) {}
}
```

**Review by zyn0217 — COMMENTED** [review]
@cor3ntin I question if `-Wloop-analysis` should be completely rewritten using dataflow analysis, rather than AST based matching.

**Comment by cor3ntin** [comment]
> @cor3ntin I question if `-Wloop-analysis` should be completely rewritten using dataflow analysis, rather than AST based matching.

That's an interesting idea, but I don't think that should stop us from landing this improvement.
Maybe we want to open an issue for that?
@AaronBallman

File: clang/test/SemaCXX/warn-loop-analysis.cpp (hunk 2 above)
Comment (zyn0217) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:316]: Or if that is something we can't handle at the moment, can you please add a FIXME?

Comment (a-tarasyuk) [reply clang/test/SemaCXX/warn-loop-analysis.cpp:316]: @zyn0217 I've added a test case with a FIXME. The original test already briefly mentions cases involving dereferencing...

https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L40-L41 

> rewritten using dataflow analysis

I suppose it’s better to rely on dataflow analysis when handling more complex cases...

**Comment by AaronBallman** [comment]
> > @cor3ntin I question if `-Wloop-analysis` should be completely rewritten using dataflow analysis, rather than AST based matching.
> 
> That's an interesting idea, but I don't think that should stop us from landing this improvement. Maybe we want to open an issue for that? @AaronBallman

Yeah, that really should be reworked -- the diagnostic is already off-by-default, so users need to explicitly request it, which means making it an analysis-based diagnostic based on the CFG isn't going to cause compile time performance concerns IMO.

**Comment by a-tarasyuk** [comment]
@AaronBallman Should this issue ideally be resolved by CFG rather than the current AST matcher fix?

**Comment by AaronBallman** [comment]
> @AaronBallman Should this issue ideally be resolved by CFG rather than the current AST matcher fix?

I think so. CC @gribozavr @ymand @sgatev for additional opinions

**Comment by a-tarasyuk** [comment]
> I question if -Wloop-analysis should be completely rewritten using dataflow analysis, rather than AST based matching.

should changes inside functions be handled in the following cases?

https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L23

https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L8

> rewritten using dataflow analysis

[`ExprMutationAnalyzer`](https://github.com/llvm/llvm-project/blob/main/clang/lib/Analysis/ExprMutationAnalyzer.cpp)?

/cc @AaronBallman @zyn0217 @cor3ntin

**Comment by AaronBallman** [comment]
> > I question if -Wloop-analysis should be completely rewritten using dataflow analysis, rather than AST based matching.
> 
> should changes inside functions be handled in the following cases?
> 
> https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L23
> 
> https://github.com/llvm/llvm-project/blob/db0f754c5af8e6c96770533520bf8b17fc0dc977/clang/test/SemaCXX/warn-loop-analysis.cpp#L8
> 
> > rewritten using dataflow analysis
> 
> [`ExprMutationAnalyzer`](https://github.com/llvm/llvm-project/blob/main/clang/lib/Analysis/ExprMutationAnalyzer.cpp)?
> 
> /cc @AaronBallman @zyn0217 @cor3ntin

Oh that's a fun case. I think the behavior of that test makes sense if there was no definition for `by_ref` because we'd want to assume the non-`const` reference parameter is modified. But because we can see the definition for `by_ref`, we know the body is empty and so the variable is not modified, and so issuing the diagnostic there would be reasonable. WDYT?

**Review by zyn0217 — APPROVED** [review]
I want to leave the final approval to @AaronBallman , but I think I'm fine with the status quo.

**Review by AaronBallman — APPROVED** [review]
LGTM with some coding style nits (take or leave them).
