### PR TITLE
[Clang][Sema] Prevent implicit casting Complex type to Vector

### LINKED ISSUE #186805: Clang allows `CK_VectorSplat` cast expressions from complex types
See https://godbolt.org/z/WTh1Y3rjW

The generated node is:
```
          |-ImplicitCastExpr 0x4e1e5748 <col:9> 'V':'__attribute__((__vector_size__(64 * sizeof(char)))) char' <VectorSplat>
          | `-ImplicitCastExpr 0x4e1e5718 <col:9> '_Complex double' <LValueToRValue>
          |   `-DeclRefExpr 0x4e1e56d8 <col:9> '_Complex double' lvalue Var 0x4e1e54f0 'x' '_Complex double'
```

and clang crashes in codegen for this node:
```console
clang++: /home/tbaeder/code/llvm-project/llvm/lib/IR/Type.cpp:807: static FixedVectorType *llvm::FixedVectorType::get(Type *, unsigned int): Assertion `isValidElementType(ElementType) && "Element type of a VectorType must " "be an integer, floating point, " "pointer type, or a valid target " "extension type."' failed.
```

I think this should simply be disallowed.

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Emitting an error message in case of implicit casting of a complex type to a built-in vector type in C

Fixes: #186805

### CODE REVIEW

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -13073,9 +13073,12 @@ void Sema::CheckImplicitConversion(Expr *E, QualType T, SourceLocation CC,
       if (SourceMgr.isInSystemMacro(CC) || Target->isBooleanType())
         return;
 
+      const Type *OriginalTargetTy = Context.getCanonicalType(T).getTypePtr();
       return DiagnoseImpCast(*this, E, T, CC,
                              getLangOpts().CPlusPlus
                                  ? diag::err_impcast_complex_scalar
+                             : OriginalTargetTy->isVectorType()
+                                 ? diag::err_impcast_incompatible_type
```
Comment (Sirraide) [inline clang/lib/Sema/SemaChecking.cpp]: Instead of nesting ternary expressions like this, could you move the new check into an if statement before this return statement here. Also, I believe just calling `T->isVectorType()` is enough.

Comment (AmrDeveloper) [reply clang/lib/Sema/SemaChecking.cpp]: Sure, I will move it to an if statement before

> I believe just calling T->isVectorType() is enough

T is TypeDef, so I think we need to desugar it first, then check if the actual type is vector

File: clang/lib/Sema/SemaChecking.cpp [hunk 2]
```diff
@@ -13069,6 +13073,11 @@ void Sema::CheckImplicitConversion(Expr *E, QualType T, SourceLocation CC,
       if (SourceMgr.isInSystemMacro(CC) || Target->isBooleanType())
         return;
 
+      if (!getLangOpts().CPlusPlus && T->isVectorType()) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaChecking.cpp]: Why is this only an error in C mode? Presumably this is a 'nicer' error message that we should use in both cases.

I suspect it is because the warning below allowing it as a warning?

Also, instead of `T`, we should match what everything else does and use `Target`.

File: clang/test/Sema/implicit-cast-complex-to-vector.c [hunk 3]
```diff
@@ -0,0 +1,13 @@
+// RUN: %clang_cc1 -fsyntax-only -verify=c %s
+// RUN: %clang_cc1 -x c++ -fsyntax-only -verify=cxx %s
+
+typedef char __attribute__((__vector_size__(64))) V;
+
+void implicit_cast_complex_to_vector() {
+  _Complex double x;
+  V y;
+  // c-error@+2 {{implicit conversion from '_Complex double' to incompatible type 'V' (vector of 64 'char' values)}}
+  // cxx-error@+1 {{implicit conversion from '_Complex double' to 'V' (vector of 64 'char' values) is not permitted in C++}}
```
[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/implicit-cast-complex-to-vector.c]: I think to do that, we need to update the `DiagnoseImpCast` helper to be aware of the select index if it exists to get the benefits of removing AddrSpaceQual 🤔

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/test/Sema/implicit-cast-complex-to-vector.c]: Oh shoot... yeah, i see that now.

**Review by erichkeane — APPROVED** [review]
