### PR TITLE
[DirectX] Set shader feature flags MinimumPrecision and NativeLowPrecision, and refactor the logic for setting low-precision-related flags

### LINKED ISSUE #138997: [DirectX] DXIL container shader flags are incorrect when using native low precision
If we build any shader with `clang-dxc -enable-16bit-types`, we fail the validator.

Given `x.hlsl`:
```hlsl
RWBuffer<half> Out : register(u0);
[numthreads(1,1,1)] void main() {
  Out[0] = 0;
}
```

We see:
```
$ clang-dxc -enable-16bit-types -T cs_6_4 -Fo x.o x.hlsl
error: Container part 'Feature Info' does not match expected for module.
Validation failed.

clang-dxc: error: dxv command failed with exit code 1 (use -v to see invocation)
```

This looks like a problem with `NativeLowPrecision` vs `UseNativeLowPrecision` in `DXContainerConstants.def`

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #138997 and does refactoring for low-precision-related flags.

The shader feature flags MinimumPrecision and NativeLowPrecision were not being set, leading to validation errors.
This PR sets these shader feature flags [as in DXC](https://github.com/microsoft/DirectXShaderCompiler/blob/377c4ca6d82adb83bf2eaf978a7040443848d6fd/lib/DXIL/DxilShaderFlags.cpp#L58-L63) and adds tests for them.

This PR also performs some refactoring of low-precision-related flags to make it less confusing.
- The `UseNativeLowPrecision` DXIL module flag has been renamed to `NativeLowPrecisionMode` to imply that it is setting some execution state which the module should be interpreted with
- The LLVM module flag `dx.nativelowprec` is now read only once and sets a bool to be used by `updateFunctionFlags()` and for setting the DXIL module flag `NativeLowPrecisionMode`
- The `MinimumPrecision`, `NativeLowPrecision`, and `LowPrecisionPresent` shader feature flags are all set together under `updateFunctionFlags()`
- Moved the logic for setting DXIL module flags `NativeLowPrecisionMode` and `ResMayNotAlias` out of the per-function loop and placed it alongside the logic for setting other DXIL module flags (`DisableOptimizations`, `Max64UAVs`, and `UAVsAtEveryStage` flags)

### CODE REVIEW

**Comment by bogner** [comment]
I think we need to refactor / clean up the handling of the MinimumPrecision/NativeLowPrecision and LowPrecisionPresent/UseNativeLowPrecision flags. This code is starting to become very hard to follow.

1. I'm not 100% convinced we really need all four, and if we do we should probably do some renaming as it's very confusing to have "NativeLowPrecision" and "UseNativeLowPrecision" be so subtly different.
2. It's really awkward how setting these is spread out across three different places.

For (1), it does look like we need MinimumPrecision, NativeLowPrecision, and LowPrecisionPresent. LowPrecisionPresent seems to be set in the container regardless of whether 16 bit types are enabled so I don't think it can be folded in to the other two. UseNativeLowPrecision on the other hand feels redundant to me. The one place that's tricky here is related to a comment in [use-native-low-precision-1.ll](https://github.com/llvm/llvm-project/blob/ad66e5495d598c9f64cfafba92ba48f2a24b8278/llvm/test/CodeGen/DirectX/ShaderFlags/use-native-low-precision-1.ll#L21-L23) - if we set the function flag purely based on the compiler flag but the container flag depends on actual use, then they do need to be separate. Is this done by dxc intentionally or is it a bug? It seems weird to have a flag that says there are 16 bit types when there aren't any present.

For (2), I think we should move the logic that reads the module metadata out of the loop and precalculate a bool to look it up rather than calculate it every time, and then put all of the logic to set these correctly where we handle LowPrecisionPresent today. IIUC The module flags aren't involved in the function flag calculation, so it should be fine to set those here, and that way we can have one place that has all of this logic and can be commented appropriately to explain what's happening.

**Comment by Icohedron** [comment]
> I think we need to refactor / clean up the handling of the MinimumPrecision/NativeLowPrecision and LowPrecisionPresent/UseNativeLowPrecision flags. This code is starting to become very hard to follow.
> 
> 1. I'm not 100% convinced we really need all four, and if we do we should probably do some renaming as it's very confusing to have "NativeLowPrecision" and "UseNativeLowPrecision" be so subtly different.
> 2. It's really awkward how setting these is spread out across three different places.
> 
> For (1), it does look like we need MinimumPrecision, NativeLowPrecision, and LowPrecisionPresent. LowPrecisionPresent seems to be set in the container regardless of whether 16 bit types are enabled so I don't think it can be folded in to the other two. UseNativeLowPrecision on the other hand feels redundant to me. The one place that's tricky here is related to a comment in [use-native-low-precision-1.ll](https://github.com/llvm/llvm-project/blob/ad66e5495d598c9f64cfafba92ba48f2a24b8278/llvm/test/CodeGen/DirectX/ShaderFlags/use-native-low-precision-1.ll#L21-L23) - if we set the function flag purely based on the compiler flag but the container flag depends on actual use, then they do need to be separate. Is this done by dxc intentionally or is it a bug? It seems weird to have a flag that says there are 16 bit types when there aren't any present.
> 
> For (2), I think we should move the logic that reads the module metadata out of the loop and precalculate a bool to look it up rather than calculate it every time, and then put all of the logic to set these correctly where we handle LowPrecisionPresent today. IIUC The module flags aren't involved in the function flag calculation, so it should be fine to set those here, and that way we can have one place that has all of this logic and can be commented appropriately to explain what's happening.

Good points. I will refactor the logic for these shader flags to hoist the reading of the dx.nativelowprec module flag out of loops and consolidate the code for setting MinimumPrecision, NativeLowPrecision, and LowPrecisionPresent into where LowPrecisionPresent is currently being set to make the code more readable.

I do agree that having two similar but subtly different flags UseNativeLowPrecision and NativeLowPrecision is rather confusing. Perhaps UseNativeLowPrecision could be renamed to NativeLowPrecisionAvailable, and NativeLowPrecision could be renamed to UsesNativeLowPrecision? The former to indicate availability of native low-precision data types because they have been enabled via a command-line flag / module flag (and the hardware supports it), and the latter to indicate the actual use of native low-precision data types?

Regarding the comment in [use-native-low-precision-1.ll](https://github.com/llvm/llvm-project/blob/ad66e5495d598c9f64cfafba92ba48f2a24b8278/llvm/test/CodeGen/DirectX/ShaderFlags/use-native-low-precision-1.ll#L21-L23) and whether or not it is a bug in DXC: I think it probably doesn't matter if it is a bug in DXC. It would probably be fine to set UseNativeLowPrecision only when there are low-precision data types present in the module.
If a module doesn't use low-precision data types, then whether or not the UseNativeLowPrecision flag is set does not matter -- it shouldn't change the semantics of the shader, and it should still pass the Validator. This would need verification/testing, but if this works then the UseNativeLowPrecision and the NativeLowPrecision could be combined into a single SHADER_FEATURE_INFO entry in DXContainerConstants.def.

**Review by inbelic — APPROVED** [review]

**Review by inbelic — CHANGES_REQUESTED** [review]
Hm sorry, I must have been looking at an outdated version of the pull request when reviewing, and didn't see the comments. I will un-approve for now, just ping me directly when it is ready for review with the comments addressed

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp [hunk 1]
```diff
@@ -286,6 +290,17 @@ void ModuleShaderFlags::initialize(Module &M, DXILResourceTypeMap &DRTM,
...
+  // Set ResMayNotAlias to true if DXIL validator version < 1.8 and there
+  // are UAVs present globally.
+  if (CanSetResMayNotAlias && MMDI.ValidatorVersion < VersionTuple(1, 8))
+    CombinedSFMask.ResMayNotAlias = !DRM.uavs().empty();
+
+  // Set the module flag that enables native low-precision execution mode. This
+  // is needed even if the module does not use 16-bit types because a
+  // corresponding debug module may include 16-bit types, and tools that use the
+  // debug module may expect it to have the same flags as the original
+  CombinedSFMask.NativeLowPrecisionMode = NativeLowPrecisionMode;
```
Comment (Icohedron) [inline llvm/lib/Target/DirectX/DXILShaderFlags.cpp:302]: Setting the flag in CombinedSFMask instead of SCCSF will make the module flags be set on the module only and not the functions themselves. This is consistent with the way the DisableOptimizations flag is currently set in Clang. 
However, it does not match the behavior of DXC (see [DxilShaderFlags.cpp](https://github.com/microsoft/DirectXShaderCompiler/blob/fb4d7d17bd5104cbbf259e8484390175fdc23192/lib/DXIL/DxilShaderFlags.cpp#L412-L413)) which sets every flag at the function level.
I don't think it matters though? The final DXIL module flags and shader feature flags work out to be the same in the end.

**Comment by Icohedron** [comment]
The refactoring is complete and the PR is ready for re-review.
- The `UseNativeLowPrecision` DXIL module flag has been renamed to `NativeLowPrecisionMode` to imply that it is setting some execution state which the module should be interpreted with
- The LLVM module flag `dx.nativelowprec` is now read only once and sets a bool to be used by `updateFunctionFlags()` and for setting the DXIL module flag `NativeLowPrecisionMode`
- The `MinimumPrecision`, `NativeLowPrecision`, and `LowPrecisionPresent` shader feature flags are all set together under `updateFunctionFlags()`
- I moved the logic for setting DXIL module flags `NativeLowPrecisionMode` and `ResMayNotAlias` out of the per-function loop and placed it alongside the logic for setting other DXIL module flags (`DisableOptimizations`, `Max64UAVs`, and `UAVsAtEveryStage` flags)

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp [hunk 2]
```diff
@@ -206,14 +213,23 @@ void ModuleShaderFlags::initialize(Module &M, DXILResourceTypeMap &DRTM,
...
 
+  // NativeLowPrecisionMode can only be set when the command line option
+  // -enable-16bit-types is provided. This is indicated by the dx.nativelowprec
+  // module flag being set
+  NativeLowPrecisionMode = false;
+  if (auto *NativeLowPrec = mdconst::extract_or_null<ConstantInt>(
+          M.getModuleFlag("dx.nativelowprec")))
+    if (MMDI.ShaderModelVersion >= VersionTuple(6, 2) &&
+        NativeLowPrec->getValue() != 0)
+      NativeLowPrecisionMode = true;
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILShaderFlags.cpp:231]: I think it's slightly clearer to assign the boolean value directly here:
```suggestion
    if (MMDI.ShaderModelVersion >= VersionTuple(6, 2))
      NativeLowPrecisionMode = NativeLowPrec->getValue().getBoolValue();
```

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp (hunk 1 above)
Comment (bogner) [reply llvm/lib/Target/DirectX/DXILShaderFlags.cpp:302]: Yeah, this feels like an implementation detail - I don't think there's any way to see a difference in the end.

File: llvm/lib/Target/DirectX/DXILShaderFlags.h [hunk 3]
```diff
@@ -91,7 +91,10 @@ struct ModuleShaderFlags {
   const ComputedShaderFlags &getCombinedFlags() const { return CombinedSFMask; }
 
 private:
-  bool CanSetResMayNotAlias;
+  // Booleans set by module flags
+  bool CanSetResMayNotAlias;   // dx.resmayalias
+  bool NativeLowPrecisionMode; // dx.nativelowprec
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILShaderFlags.h:96]: Should we name these similarly to reflect their similar usage/purpose? Does `CanSetNativeLowPrecision` make sense? If that feels forced I think `HasResMayAlias` and `HasNativeLowPrec` wouldn't be bad, though that would require flipping the value of the existing member.

File: llvm/test/CodeGen/DirectX/ShaderFlags/res-may-not-alias-sm6.7.ll [hunk 4]
```diff
@@ -2,8 +2,8 @@
 
 ; This test checks to ensure the behavior of the DXIL shader flag analysis
 ; for the flag ResMayNotAlias is correct when the DXIL Version is >= 1.7 and the
-; DXIL Validator Version < 1.8. The ResMayNotAlias flag (0x20000000) should be
-; set on all functions if there are one or more UAVs present globally in the
+; DXIL Validator Version < 1.8. The ResMayNotAlias module flag (0x20000000)
+; should be set if there are one or more UAVs present globally in the
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/ShaderFlags/res-may-not-alias-sm6.7.ll:6]: Should we add an `llc | obj2yaml` run line to this test like we have in low-precision.ll?

**Review by bogner — APPROVED** [review]
Looks good. A couple of minor comments on naming and tests

File: llvm/test/CodeGen/DirectX/ShaderFlags/res-may-not-alias-sm6.7.ll (hunk 4 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/ShaderFlags/res-may-not-alias-sm6.7.ll:6]: There is nothing to test in the obj2yaml because ResMayNotAlias is only a module flag. It doesn't have a related shader feature flag that will show up in SFI0

File: llvm/lib/Target/DirectX/DXILShaderFlags.h (hunk 3 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILShaderFlags.h:96]: I think `CanSetNativeLowPrecisionMode` would make more sense

**Review by inbelic — APPROVED** [review]
