### PR TITLE
[LSV] Merge contiguous chains across scalar types

### LINKED ISSUE #97715: [LSV] Load Store Vectorizer failed to combine two related loads.
The LSV pass doesn't combine the loads even though the base address remain the same for them.
There are many instances found in the AMDGPU codegen lit test folder. For example, llvm/test/CodeGen/AMDGPU/GlobalISel/fp-atomics-gfx940.ll (in function local_atomic_fadd_v2bf16_noret) should have the two loads combined earlier. But they are merged using the target specific Load Store Optimizer pass (si-load-store-opt) after ISel.

### PR DESCRIPTION
**Pull request by gandhi56**
This change enables the LoadStoreVectorizer to merge and vectorize contiguous chains even when their scalar element types differ, as long as the total bitwidth matches. To do so, we rebase offsets between chains, normalize value types to a common integer type, and insert the necessary casts around loads and stores. This uncovers more vectorization opportunities and explains the expected codegen updates across AMDGPU tests.

Key changes:
- Chain merging
  - Build contiguous subchains and then merge adjacent ones when:
    - They refer to the same underlying pointer object and address space.
    - They are either all loads or all stores.
    - A constant leader-to-leader delta exists.
    - Rebasing one chain into the other's coordinate space does not overlap.
    - All elements have equal total bit width.
  - Rebase the second chain by the computed delta and append it to the first.

- Type normalization and casting
  - Normalize merged chains to a common integer type sized to the total bits.
  - For loads: create a new load of the normalized type, copy metadata, and cast back to the original type for uses if needed.
  - For stores: bitcast the value to the normalized type and store that.
  - Insert zext/trunc for integer size changes; use bit-or-pointer casts when sizes match.

- Cleanups
  - Erase replaced instructions and DCE pointer operands when safe.
  - New helpers: computeLeaderDelta, chainsOverlapAfterRebase, rebaseChain, normalizeChainToType, and allElemsMatchTotalBits.

Impact:
- Increases vectorization opportunities across mixed-typed but size-compatible access chains.
- Large set of expected AMDGPU codegen diffs due to more/changed vectorization.

This PR resolves #97715.

### CODE REVIEW

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 1]
```diff
@@ -3496,6 +3496,51 @@ void llvm::copyMetadataForLoad(LoadInst &Dest, const LoadInst &Source) {
...
+    case LLVMContext::MD_noundef:
+    case LLVMContext::MD_noalias_addrspace:
+    case LLVMContext::MD_mem_parallel_loop_access:
+      Dest.setMetadata(ID, N);
+      break;
+
+    case LLVMContext::MD_tbaa: {
+      MDNode *NewTyNode =
+          MDB.createTBAAScalarTypeNode(NewType->getStructName(), N);
+      Dest.setMetadata(LLVMContext::MD_tbaa, NewTyNode);
```
Comment (arsenm) [inline llvm/lib/Transforms/Utils/Local.cpp:3524]: I'm not sure you can safely preserve this in the vectorization case

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 2]
```diff
@@ -424,6 +432,20 @@ PreservedAnalyses LoadStoreVectorizerPass::run(Function &F,
...
+    // The select's themselves are distinct instructions even if they share
+    // the same condition and evaluate to consecutive pointers for true and
+    // false values of the condition. Therefore using the select's themselves
+    // for grouping instructions would put consecutive accesses into different
+    // lists and they won't be even checked for being consecutive, and won't
+    // be vectorized.
+    return Sel->getCondition();
+  }
+  return ObjPtr;
+}
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:447]: I don't understand this function, and don't really follow the comment. 

"PtrObject" sounds like it's supposed to return a pointer to an object, which it does, unless it's a select, in which case it returns a boolean value? Plus what happens if the pointer is a select of 2 pointers derived from the same base object?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 3]
```diff
@@ -467,6 +489,98 @@ bool Vectorizer::run() {
...
+    } else if (auto *SI = dyn_cast<StoreInst>(Inst)) {
+      Builder.SetInsertPoint(SI);
+      Value *CastVal = insertCast(SI->getValueOperand(), CastTy);
+      if (!CastVal)
+        llvm_unreachable("Failed to insert cast");
+      StoreInst *NewStore =
+          Builder.CreateStore(CastVal, SI->getPointerOperand());
+      NewStore->setAlignment(SI->getAlign());
+      NewStore->setVolatile(SI->isVolatile());
+      copyMetadataForStore(*NewStore, *SI);
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:577]: This is creating an equivalently sized store, that hasn't been vectorized?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 4]
```diff
@@ -479,49 +593,111 @@ bool Vectorizer::runOnPseudoBB(BasicBlock::iterator Begin,
...
+
+    // Merge C2 into C1 by appending all elements of C2 to C1, then erase C2
+    // from ContiguousSubChains.
+    C1.insert(C1.end(), C2.begin(), C2.end());
+    ContiguousSubChains.erase(ContiguousSubChains.begin() + I);
+
+    // Normalize the value operand/result type of each instruction in C1 to
+    // C1CastTy.
+    Type *C1CastTy =
+        Type::getIntNTy(C1ElemTy->getContext(), DL.getTypeSizeInBits(C1ElemTy));
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:681]: Slightly nicer to directly use IntegerType

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 5]
```diff
@@ -467,6 +489,98 @@ bool Vectorizer::run() {
   return Changed;
 }
 
+Value *Vectorizer::insertCast(Value *Val, Type *DstTy) {
+  if (DL.getTypeSizeInBits(Val->getType()) == DL.getTypeSizeInBits(DstTy)) {
+    return Builder.CreateBitOrPointerCast(Val, DstTy, Val->getName() + ".bc");
```
[the remark this answers is not in the document]
Comment (gandhi56) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:494]: `CreateBitOrPointerCast` does not emit an addrspacecast. It's `CreatePointerBitCastOrAddrSpaceCast` which does.

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 6]
```diff
@@ -479,49 +593,111 @@ bool Vectorizer::runOnPseudoBB(BasicBlock::iterator Begin,
...
+    for (auto &AlignedSubChain : splitChainByAlignment(C))
+      Changed |= vectorizeChain(AlignedSubChain);
+  }
+
+  // Erase all instructions scheduled for deletion in this pseudo-BB.
+  for (Instruction *I : ToErase) {
+    auto *PtrOperand = getLoadStorePointerOperand(I);
+    if (I->use_empty())
+      I->eraseFromParent();
+    RecursivelyDeleteTriviallyDeadInstructions(PtrOperand);
```
[the remark this answers is not in the document]
Comment (gandhi56) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:697]: No, the operand needs to be handled separately.

File: llvm/lib/Transforms/Utils/Local.cpp (hunk 1 above)
Comment (gandhi56) [reply llvm/lib/Transforms/Utils/Local.cpp:3524]: Can you please elaborate? Vectorization hasn't occurred yet, and this function should serve a general scenario where metadata is being copied over.

**Comment by gandhi56** [comment]
Internal PSDB passed.

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 7]
```diff
@@ -3140,6 +3140,51 @@ void llvm::copyMetadataForLoad(LoadInst &Dest, const LoadInst &Source) {
...
+
+    case LLVMContext::MD_align:
+    case LLVMContext::MD_dereferenceable:
+    case LLVMContext::MD_dereferenceable_or_null:
+      // These only directly apply if the new type is also a pointer.
+      if (NewType->isPointerTy())
+        Dest.setMetadata(ID, N);
+      break;
+
+    case LLVMContext::MD_range:
```
Comment (LU-JOHN) [inline llvm/lib/Transforms/Utils/Local.cpp:3182]: Range metadata is not valid for stores.  https://llvm.org/docs/LangRef.html#range-metadata

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 8]
```diff
@@ -3496,6 +3496,51 @@ void llvm::copyMetadataForLoad(LoadInst &Dest, const LoadInst &Source) {
...
+      Dest.setMetadata(ID, N);
+      break;
+
+    case LLVMContext::MD_tbaa: {
+      MDNode *NewTyNode =
+          MDB.createTBAAScalarTypeNode(NewType->getStructName(), N);
+      Dest.setMetadata(LLVMContext::MD_tbaa, NewTyNode);
+      break;
+    }
+    case LLVMContext::MD_nonnull:
```
[the remark this answers is not in the document]
Comment (gandhi56) [reply llvm/lib/Transforms/Utils/Local.cpp:3171]: How about setting it if the value operand of the new store is a pointer?

[the remark this answers is not in the document]
Comment (gandhi56) [reply llvm/lib/Transforms/Utils/Local.cpp:3171]: StoreInst.getType() would yield `VoidTy` so it probably doesn't make sense to set `MD_nonnull`.

**Review by LU-JOHN — APPROVED** [review]

**Review by nikic — COMMENTED** [review]
I've not looked at the LSV changes (leaving this to @arsenm), but I'll note that the IR test coverage here looks pretty weak for a significant change to the pass. The part I looked at (the Local.cpp changes) don't appear to have any test coverage at all.

**Comment by gandhi56** [comment]
I added a comprehensive set of normalization tests in merge-vectors-complex.ll, functionality tests in merge-vectors.ll to ensure all checks are doing their job before deciding to merge loads/stores and finally introduced copy-metadata-loads-stores.ll for metadata preservation checks.

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 9]
```diff
@@ -3153,6 +3153,48 @@ void llvm::copyMetadataForLoad(LoadInst &Dest, const LoadInst &Source) {
...
+    case LLVMContext::MD_access_group:
+    case LLVMContext::MD_noundef:
+    case LLVMContext::MD_noalias_addrspace:
+    case LLVMContext::MD_mem_parallel_loop_access:
+      Dest.setMetadata(ID, N);
+      break;
+
+    case LLVMContext::MD_tbaa: {
+      MDNode *NewTyNode =
+          MDB.createTBAAScalarTypeNode(NewType->getStructName(), N);
```
[the remark this answers is not in the document]
Comment (gandhi56) [reply llvm/lib/Transforms/Utils/Local.cpp]: Removed the store block.

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 10]
```diff
@@ -1625,8 +1782,7 @@ std::vector<Chain> Vectorizer::gatherChains(ArrayRef<Instruction *> Instrs) {
   Ret.reserve(Chains.size());
   // Iterate over MRU rather than Chains so the order is deterministic.
   for (auto &E : MRU)
-    if (E.second.size() > 1)
-      Ret.emplace_back(std::move(E.second));
+    Ret.emplace_back(std::move(E.second));
```
Comment (dakersnar) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp]: Can you explain this change? Are you basically allowing chains that have a size of 1 in order to merge them later?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 11]
```diff
@@ -480,49 +582,120 @@ bool Vectorizer::runOnPseudoBB(BasicBlock::iterator Begin,
...
+  }
 
-  std::vector<Chain> Chains = gatherChains(EqClass);
-  LLVM_DEBUG(dbgs() << "LSV: Got " << Chains.size()
-                    << " nontrivial chains.\n";);
-  for (Chain &C : Chains)
-    Changed |= runOnChain(C);
-  return Changed;
-}
+  // Merge chains in reverse order, so that the first chain is the largest.
```
Comment (dakersnar) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp]: This comment concerns me. We don't have a guarantee that chains are in increasing size order at this point in the code. Am I missing something?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 12]
```diff
@@ -480,49 +582,120 @@ bool Vectorizer::runOnPseudoBB(BasicBlock::iterator Begin,
...
+    // Power-of-two span ensures we can form a legal, single vector access
+    // without padding or splitting. Many targets and cost models assume POT
+    // widths, and it guarantees an integral element count for the chosen
+    // VecElemTy.
+    APInt Sz = C2.front().OffsetFromLeader +
+               DL.getTypeStoreSize(getLoadStoreType(C2.front().Inst)) -
+               C1.back().OffsetFromLeader + *DeltaOpt;
+    if (!Sz.isPowerOf2())
+      continue;
+
```
Comment (dakersnar) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp]: Do you mind explaining this calculation? This doesn't seem right to me.
