### PR TITLE
[clang-format] Detect nesting in template strings

### LINKED ISSUE #107571: Regression in formatting for JS template strings
Actual formatting:
```
# clang-format a.ts

`${
    (
        FOOFOOFOOFOO____FOO_FOO_FO_FOO_FOOO -
            (barbarbarbar____bar_bar_bar_bar_bar_bar +
                bar_bar_bar_barbarbar___bar_bar_bar + 1),
        )}`;
```

Expected formatting:
```
`${
    (
        FOOFOOFOOFOO____FOO_FOO_FO_FOO_FOOO -
            (barbarbarbar____bar_bar_bar_bar_bar_bar +
             bar_bar_bar_barbarbar___bar_bar_bar + 1),
        )}`;
```

i.e. no extra indentation for the inner subexpression, as that's the formatting we got without template strings:
```
# clang-format a.ts

FOOOOOOOOFOOFOOFOOFOO____FOO_FOO_FO_FOO_FOOO -
    (barrrrbarbarbarbar____bar_bar_bar_bar_bar_bar +
     barrrrbar_bar_bar_barbarbar___bar_bar_bar + 1),
```

### PR DESCRIPTION
**Pull request by gedare**
The helper to check if a token is in a template string scans too far backward. It should stop if a different scope is found.

Fixes #107571

### CODE REVIEW

File: clang/unittests/Format/FormatTestJS.cpp [hunk 1]
```diff
@@ -2157,6 +2157,13 @@ TEST_F(FormatTestJS, TemplateStringMultiLineExpression) {
                "                          aaaa:  aaaaa,\n"
                "                          bbbb:  bbbbb,\n"
                "                        })}`;");
+
+  verifyFormat("`${\n"
+               "    (\n"
+               "        FOOFOOFOOFOO____FOO_FOO_FO_FOO_FOOO -\n"
+               "            (barbarbarbar____bar_bar_bar_bar_bar_bar +\n"
+               "             bar_bar_bar_barbarbar___bar_bar_bar + 1),\n"
+               "        )}`;\n");
```
Comment (owenca) [inline clang/unittests/Format/FormatTestJS.cpp:2166]:
```suggestion
               "        )}`;");
```

**Review by owenca — APPROVED** [review]
