### PR TITLE
[clang] Fix implicit integer conversion for opaque enums declared in class templates

### LINKED ISSUE #117960: Crashes When Compiling Template Enum with Function and Static Assertions
This crash can be observed in both LLVM 18 and LLVM trunk versions.[https://godbolt.org/z/v57annjGn](https://godbolt.org/z/v57annjGn)
# Command
`clang++ bug.cpp`

# Code
```cpp
template < typename T > struct A
{
  enum E : T;
  E h ();
};

A < int > a;
A < int >::E b = a.h () + 1;

int i = b.e ();
static_assert (i == 1, "i");
A::E e = b.e ();
static_assert (e, "");

A::E e = A::h () + 1;

template < typename T > enum A < T >::E : T { e };  

template < typename T > typename A < T >::E A < T >::h ()
{
  return e;  
}
```
# Version
clang-18
```sh
Ubuntu clang version 18.1.8 (++20240731025011+3b5b5c1ec4a3-1~exp1~20240731145104.143)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
# Error Output
```sh
Stack dump:
0.      Program arguments: /usr/lib/llvm-18/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name bug.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/bugs -fcoverage-compilation-dir=/home/bugs -resource-dir /usr/lib/llvm-18/lib/clang/18 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/x86_64-linux-gnu/c++/13 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/backward -internal-isystem /usr/lib/llvm-18/lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -dwarf-debug-flags "/usr/lib/llvm-18/bin/clang --driver-mode=g++ bug.cpp -dumpdir a-" -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/bug-2ab286.o -x c++ bug.cpp
1.      bug.cpp:8:28: current parser token ';'
 #0 0x00007fb2523ecb46 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd93b46)
 #1 0x00007fb2523eaaf0 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd91af0)
 #2 0x00007fb2523ed210 (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd94210)
 #3 0x00007fb25123c090 (/lib/x86_64-linux-gnu/libc.so.6+0x43090)
 #4 0x00007fb2598f2639 clang::ASTContext::getIntegerRank(clang::Type const*) const (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc9b639)
 #5 0x00007fb2598f30c5 clang::ASTContext::getIntegerTypeOrder(clang::QualType, clang::QualType) const (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc9c0c5)
 #6 0x00007fb25a2fcdf3 (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16a5df3)
 #7 0x00007fb25a2fc132 clang::Sema::UsualArithmeticConversions(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, clang::Sema::ArithConvKind) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16a5132)
 #8 0x00007fb25a32095b clang::Sema::CheckAdditionOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, clang::BinaryOperatorKind, clang::QualType*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16c995b)
 #9 0x00007fb25a30de92 clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16b6e92)
#10 0x00007fb25a5f3d74 clang::Sema::CreateOverloadedBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::UnresolvedSetImpl const&, clang::Expr*, clang::Expr*, bool, bool, clang::FunctionDecl*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x199cd74)
#11 0x00007fb25a32cf2c (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16d5f2c)
#12 0x00007fb25a32cb10 clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16d5b10)
#13 0x00007fb25a2fba9f clang::Sema::ActOnBinOp(clang::Scope*, clang::SourceLocation, clang::tok::TokenKind, clang::Expr*, clang::Expr*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x16a4a9f)
#14 0x00007fb2598250a4 clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xbce0a4)
#15 0x00007fb259823e8f clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xbcce8f)
#16 0x00007fb2597f44fe clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xb9d4fe)
#17 0x00007fb2597f1884 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xb9a884)
#18 0x00007fb2598a6e7a clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc4fe7a)
#19 0x00007fb2598a6843 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc4f843)
#20 0x00007fb2598a5aa6 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc4eaa6)
#21 0x00007fb2598a3eda clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xc4ceda)
#22 0x00007fb2597dcc7e clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0xb85c7e)
#23 0x00007fb25b614415 clang::FrontendAction::Execute() (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x29bd415)
#24 0x00007fb25b58e674 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2937674)
#25 0x00007fb25b68e69e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-18/bin/../lib/libclang-cpp.so.18.1+0x2a3769e)
#26 0x000055ecd5475c62 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-18/bin/clang+0x12c62)
#27 0x000055ecd5473095 (/usr/lib/llvm-18/bin/clang+0x10095)
#28 0x000055ecd5472256 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm-18/bin/clang+0xf256)
#29 0x000055ecd547faf6 main (/usr/lib/llvm-18/bin/clang+0x1caf6)
#30 0x00007fb25121d083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#31 0x000055ecd546fb0e _start (/usr/lib/llvm-18/bin/clang+0xcb0e)
```
clang-truck
```sh
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:8:28: current parser token ';'
#0 0x00000000039bee18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bee18)
#1 0x00000000039bcf64 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bcf64)
#2 0x000000000390d898 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
#3 0x0000791d8a842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x0000000007025f38 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x7025f38)
#5 0x00007ffcdfa753a0 
```

### PR DESCRIPTION
**Pull request by thebrandre**
This commit fixes issues with enumeration types instantiated from an opaque-enum-declarations 
(see [dcl.enum]) in class templates broke basic assumptions during parsing of arithmetic
expressions due to absent (NULL TYPE) promotion types of instances of EnumDecl.

To this end, we repeat the simple steps in `Sema::ActOnTag` to evaluate the promotion type
of a fixed enumeration based on its underlying type (see C++11 [conv.prom] p4).

Note that if, instead, a full *enum-specifier* (subsequent curly braces) is provided,
`Sema::ActOnEnumBody` is re-invoked on template instantiation anyway overriding the
promotion type and hiding the issue. This is analog to how enumerations declarations
outside of template declarations are handled.
Note that, in contrast to `Sema::ActOnEnumBody`, `Sema::ActOnTag` is *not* called again
for the instantiated enumeration type.

Fixes #117960.

### CODE REVIEW

**Comment by cor3ntin** [comment]
Thanks for the PR. Can you update the commit message to be more descriptive?

I'm not sure the fix is sufficient.
I think most of the checks done in `ActOnEnumBody` should be (re) performed on instantiation.

Maybe we should instead

- Add a new `BuildEnumBody` function, move most (all?) the implementation of  `ActOnEnumBody` to that
- call `BuildEnumBody` from both `ActOnEnumBody` and `RebuildEnumType`

That would not only fix the crash but also the fact that we are seemingly missing a lot of diagnostics
https://godbolt.org/z/17dTW4dEe

**Comment by thebrandre** [comment]
Thanks for the feedback @cor3ntin! 🙂

I will change the title of the PR and of the commit message to: 

> _[clang] Fix implicit integer conversion for opaque enum declarations in class templates_ 

adopting the terminology from [[dcl.enum]](https://wg21.link/dcl.enum) if that isn't too verbose?

The other potential issues you mentioned should actually conform to the specification in [[temp.spec.general]](https://wg21.link/temp.spec#temp.inst-3) if I understand it correctly.
See here on Compiler Explorer: [https://godbolt.org/z/GzYq9jzjo](https://godbolt.org/z/GzYq9jzjo).
This behavior is also consistent with GCC.

My changes should not affect the behavior if `ActOnEnumBody` is called. Admittedly, I was very conservative when changing behavior because I am not yet very familiar with the codebase.
Do you think, we should still pursue the idea of refactoring as you described if the current behavior of Clang turns out to be correct in the situations you brought up? I'd be happy to do so. But I am not sure if it belongs into this PR? It definitely makes sense to add regression tests for this scenario if they don't already exist.

In any case, I'll try if I can find any other related scenarios where the fix isn't sufficient!

**Comment by thebrandre** [comment]
I added regression tests for the scoped enumeration types to make sure that these are not affected.
And I also tried to improve the commit message and added comments with references to the relevant sections in the C++ standard.
But I still have to think about your refactoring/completeness suggestions.

**Comment by thebrandre** [comment]
@cor3ntin Good news! I figured it out on my own! And I now have a fix that I am confident in. 🙂
I analyzed the steps of the parser in **a lot**  of similar cases, for which I also added quite a few regression tests.

The attributes have already been handled correctly previously. But to make sure of it, I also added tests.

Putting the few lines for the fix there, seems fairly consistent to me. It repeats the logic in [`Sema::ActOnTag`](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.6/clang/lib/Sema/SemaDecl.cpp#L17152-L17154) and [`Sema::ActOnEnumBody`](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.6/clang/lib/Sema/SemaDecl.cpp#L19917-L19922) (exact lines of code are linked). We would now repeat them a third time but this is unavoidable because `Sema::ActOnEnumBody` is called again during instantiation but `Sema::ActOnTag` is not.
Refactoring this is would be hard because it's not really specified what exactly the individual functions are supposed to do. And the repetition doesn't seem too bad to me.

As you suggested, I stepped through the code to check if anything else from `Sema::ActOnTag` might be missing. But this doesn't seem to be the case.
Some things seemed odd but non-relevant. For example for `enum E : int {};`  `EnumDecl::NumPositiveBits` is set to 1, but it stays 0 for the opaque declaration `enum E : int;`. I also noticed that I can trigger a case where [a diagnostic gets reported twice](https://godbolt.org/z/473Eezhjn)). This, however, seems rather unrelated to me. I would rather open up a separate pull request for that.

Thanks again for your feedback @cor3ntin - it helped me to get a much cleaner solution and a better understanding of the issue even though my initial analysis might have been a little confusing ...
Well, I hope it's now ready for merging. 🙂

I rebased my branch on the current main and also "rebased away" my prior fix to make the diff more concise.

**Comment by cor3ntin** [comment]
> Thanks for the PR. Can you update the commit message to be more descriptive?
> 
> I'm not sure the fix is sufficient.
> I think most of the checks done in `ActOnEnumBody` should be (re) performed on instantiation.
> 
> Maybe we should instead
> 
> - Add a new `BuildEnumBody` function, move most (all?) the implementation of  `ActOnEnumBody` to that
> - call `BuildEnumBody` from both `ActOnEnumBody` and `RebuildEnumType`
> 
> That would not only fix the crash but also the fact that we are seemingly missing a lot of diagnostics
> https://godbolt.org/z/17dTW4dEe
> 

@erichkeane wdyt?

**Comment by thebrandre** [comment]
@cor3ntin I hope there is no misunderstanding here. If so, I apologize,

I strongly agree with you that some refactoring should be applied because, as I mentioned, the diagnostics get duplicated in certain cases as shown here on Compiler Explorer: [https://godbolt.org/z/473Eezhjn](https://godbolt.org/z/473Eezhjn).
But I would prefer opening another pull request for it keeping it separate from the fix making it easier to cherry-pick.
My understanding is that all commits get squashed before being applied to main?

If there is still something wrong with the commit message, I would gladly give it another try if you could be more specific.

**Comment by erichkeane** [comment]
> > Thanks for the PR. Can you update the commit message to be more descriptive?
> > I'm not sure the fix is sufficient.
> > I think most of the checks done in `ActOnEnumBody` should be (re) performed on instantiation.
> > Maybe we should instead
> > 
> > * Add a new `BuildEnumBody` function, move most (all?) the implementation of  `ActOnEnumBody` to that
> > * call `BuildEnumBody` from both `ActOnEnumBody` and `RebuildEnumType`
> > 
> > That would not only fix the crash but also the fact that we are seemingly missing a lot of diagnostics
> > https://godbolt.org/z/17dTW4dEe
> 
> @erichkeane wdyt?

I agree, it seems that the instantiation of the enum is missing quite a bit when it comes to diagnostics.  We should definitely do some sort of analysis to ensure that we're getting the same diagnostics at both points.

That said, I am ok with doing this NOW, as long as the author promises to do the rest in a followup patch ASAP.

**Comment by thebrandre** [comment]
@erichkeane I am not sure what you mean. As I pointed out earlier, the examples @cor3ntin brought up actually conform to the standard as in [[temp.spec.general]](https://wg21.link/temp.spec#temp.inst-3):

> The implicit instantiation of a class template specialization causes the implicit instantiation of the declarations, but not of the definitions of [...] scoped member enumerations, [...]

The issues are correctly diagnosed by clang if the struct is *explicitly instantiated* as demonstrated here in Compiler Explorer: [https://godbolt.org/z/GzYq9jzjo](https://godbolt.org/z/GzYq9jzjo).

Nevertheless, I investigated further and managed to discover some real bugs with diagnostics on template instantiation.
These affect not only enums but also nested classes. If you are interested, you can have a look: [https://godbolt.org/z/vKG6vqWhs](https://godbolt.org/z/vKG6vqWhs). I have already started working on these issues but so far they seem unrelated.

I plan to keep working on it but I can't promise much given the facts that I only have the weekends to spend time on it and my limited familiarity with the codebase (this would be my very first commit to LLVM). But, of course, I promise to try my best! 🙂

**Comment by erichkeane** [comment]
> @erichkeane I am not sure what you mean. As I pointed out earlier, the examples @cor3ntin brought up actually conform to the standard as in [[temp.spec.general]](https://wg21.link/temp.spec#temp.inst-3):
> 
> > The implicit instantiation of a class template specialization causes the implicit instantiation of the declarations, but not of the definitions of [...] scoped member enumerations, [...]
> 
> The issues are correctly diagnosed by clang if the struct is _explicitly instantiated_ as demonstrated here in Compiler Explorer: https://godbolt.org/z/GzYq9jzjo.

My quick look through the ActOnEnum and this function looked like it showed some misses.  If Corentin is comfortable with our checking here, then I'm happy too.

> 
> Nevertheless, I investigated further and managed to discover some real bugs with diagnostics on template instantiation. These affect not only enums but also nested classes. If you are interested, you can have a look: https://godbolt.org/z/vKG6vqWhs. I have already started working on these issues but so far they seem unrelated.

Thats great, thanks for finding that and working on it!  Those look like some pretty unfortunate misses.
> 
> I plan to keep working on it but I can't promise much given the facts that I only have the weekends to spend time on it and my limited familiarity with the codebase (this would be my very first commit to LLVM). But, of course, I promise to try my best! 🙂

Definitely appreciate it!

I'm happy when Corentin is here, I have no concerns.

**Comment by cor3ntin** [comment]
We usually try to diagnose issues as soon as possible, so i still believe there are improvements to be made here. That being said, I'm happy to approve the PR as it is now. 

That being said, it is missing a changelog entry in `clang/docs/ReleaseNotes.rst`, can you add one?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -1571,6 +1571,23 @@ Decl *TemplateDeclInstantiator::VisitEnumDecl(EnumDecl *D) {
...
+      // If users declare a full enum-specifier, the promotion type is reset
+      // again when parsing the (potentially empty) enumerator-list.
+      // We implement the same logic from C++11 [conv.prom] p4 here but only
+      // after template specialization [temp.spec.general] because it requires
+      // the concrete type.
+      // Note that (1) this also correctly handles the non-dependent case,
+      // (2) we set the promotion type for scoped enumerations to ensure
+      // consistency with declarations outside of templates, (3) we guarantee a
+      // valid promotion even if the user provided an invalid underlying type
+      // (fallback to "default int").
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:1585]:
```suggestion
      // C++23 [conv.prom]p4
      // if integral promotion can be applied to its underlying type, a prvalue of an unscoped enumeration type 
      // whose underlying type is fixed can also be converted to a prvalue of the promoted underlying type.
      // 
      // FIXME: that logic is already implemented in ActOnEnumBody, factor out into (Re)BuildEnumBody. 
```

**Comment by cor3ntin** [comment]
The issue number here seems wrong, can you update the description?
https://github.com/llvm/llvm-project/pull/121039#issue-2757453924

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -938,6 +938,9 @@ Miscellaneous Clang Crashes Fixed
 - Fixed internal assertion firing when a declaration in the implicit global
   module is found through ADL. (GH#109879)
 
+- Fixed a crash when an unscoped enumeration declared by an opaque-enum-declaration within a class template
+  with a dependent underlying type is subject to integral promotion. (GH#117960)
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:942]:
```suggestion
  with a dependent underlying type is subject to integral promotion. (#GH117960)
```

**Comment by thebrandre** [comment]
> The issue number here seems wrong, can you update the description? [#121039 (comment)](https://github.com/llvm/llvm-project/pull/121039#issue-2757453924) (#116525 is a completely unrelated issue)

Thanks for pointing that out @cor3ntin. I messed that up in my last edit.

> That being said, it is missing a changelog entry in clang/docs/ReleaseNotes.rst, can you add one?

Sure. You won't notice it but I literally spent half an hour thinking about this sentence. It's so difficult to be clear, technically correct, and concise at the same time.

> We usually try to diagnose issues as soon as possible, so i still believe there are improvements to be made here. 

I am still undecided here. As far as I understand the standard, this is valid code as long as the enum is not used. It says *The implicit instantiation of a class template specialization causes [...] the implicit instantiation of the definitions of unscoped member enumerations* [[temp.inst]](https://eel.is/c++draft/temp.inst). This feature extensively used for member functions. For example std::vector::resize is not valid for types that are not default-constructible but you can still use std::vector as long as you don't use the bad member functions. 
See here on Compiler Explorer [https://godbolt.org/z/Mn3Y1Ka14](https://godbolt.org/z/Mn3Y1Ka14).

Admittedly, I can't think of any sane use case for this feature on unscoped member enumerations ... but there are very creative people out there. 😉

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -938,6 +938,9 @@ Miscellaneous Clang Crashes Fixed
 - Fixed internal assertion firing when a declaration in the implicit global
   module is found through ADL. (GH#109879)
```
[the remark this answers is not in the document]
Comment (thebrandre) [reply clang/docs/ReleaseNotes.rst:939]: Oh thanks! I adopted the pattern used in the note before and didn't notice that it doesn't match the others.

**Review by thebrandre — COMMENTED** [review]
I am not sure why the jumbled letters in "GH#117960"  are still there and why I can't apply it (it says the change request is outdated). So I am going to fix that manually.

**Review by cor3ntin — APPROVED** [review]
Thanks!
Do you need me to merge that for you?

**Review by thebrandre — COMMENTED** [review]
And it's me again. I did review it before but didn't know I was supposed to explicitly mark each file. 🙈

**Comment by thebrandre** [comment]
> Thanks! Do you need me to merge that for you?

That would be great! 😊
