### PR TITLE
[Format] Fix detection of languages when reading from stdin

### LINKED ISSUE #79023: [Format] Regression in `clang-format - -dump_config < path/to/objc_file.m` (now outputs Language: Cpp)
`clang-format - -dump_config < path/to/objc_file.m` no longer works as of https://github.com/llvm/llvm-project/commit/3791b3fca6eac5e403b91550ed0f774866cf3ede (it now outputs `Language: Cpp` instead of `Language: ObjC`):

```
% cat /tmp/objc_file.m
#import <Foundation/Foundation.h>

@interface Foo : NSObject
- (void)doStuff;
@end;

@implementation Foo
@end

% ./build/bin/clang-format --version
clang-format version 18.0.0git (https://github.com/llvm/llvm-project.git 3791b3fca6eac5e403b91550ed0f774866cf3ede)

% ./build/bin/clang-format - -dump-config < /tmp/objc_file.m | grep -e '^Language'
Language:        Cpp
```

This should say `Language:        ObjC`.

The issue does not reproduce if I locally revert that change or go to its parent https://github.com/llvm/llvm-project/commit/9810fe1a91eb9ce18246fb1528232a539dbd37fc:

```
% ./build/bin/clang-format --version
clang-format version 18.0.0git (https://github.com/llvm/llvm-project.git 9810fe1a91eb9ce18246fb1528232a539dbd37fc)
% ./build/bin/clang-format - -dump-config < /tmp/objc_file.m | grep -e '^Language'
Language:        ObjC
```

### PR DESCRIPTION
**Pull request by bhamiltoncx**
The code cleanup in #74794 accidentally broke detection of languages by reading file content from stdin, e.g. via `clang-format -dump-config - < /path/to/filename`.

This PR adds unit and integration tests to reproduce the issue and adds a fix.

Fixes: #79023

### CODE REVIEW

File: clang/tools/clang-format/ClangFormat.cpp [hunk 1]
```diff
@@ -547,18 +547,20 @@ static void PrintVersion(raw_ostream &OS) {
...
-    // language.
-    ErrorOr<std::unique_ptr<MemoryBuffer>> CodeOrErr =
-        MemoryBuffer::getFileOrSTDIN(FileNames[0]);
-    if (std::error_code EC = CodeOrErr.getError()) {
-      llvm::errs() << EC.message() << "\n";
-      return 1;
-    }
-    Code = std::move(CodeOrErr.get());
+
+  // FileNames should have at least "-" in it even if no file was specified.
```
Comment (HazardyKnusperkeks) [inline clang/tools/clang-format/ClangFormat.cpp:551]: should? Then you can't assert but must check.
If the assert holds, I'd remove "should".

File: clang/test/Format/dump-config-objc-stdin.m [hunk 2]
```diff
@@ -0,0 +1,5 @@
+// RUN: clang-format -dump-config - < %s | FileCheck %s
```
Comment (HazardyKnusperkeks) [inline clang/test/Format/dump-config-objc-stdin.m:1]: I don't think you need this, right? The unit tests does the same, or not?

Comment (bhamiltoncx) [reply clang/test/Format/dump-config-objc-stdin.m:1]: In this case, we do want two tests (at least, we do need the integration test in `clang/test/Format/dump-config-objc-stdin.m` to reproduce the issue).

The reason is, the bug was introduced into `ClangFormat.cpp`, which is only linked into the `clang-format` binary executed by the integration test. The code which regressed is not actually part of the `Format` library which is executed via the unit tests.

The unit tests do not execute the `clang-format` binary; they directly execute the formatting / config dumping logic via the `Format` library. But they're much faster to build and run, and it's possible this might regress in the `Format` library in the future (I was just surprised there were no tests there).

File: clang/tools/clang-format/ClangFormat.cpp (hunk 1 above)
Comment (bhamiltoncx) [reply clang/tools/clang-format/ClangFormat.cpp]: OK, changed to "must".

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by owenca** [comment]
@bhamiltoncx Thanks for the fix! Nevertheless, it seems that this triggered a new regression. See #80621.

**Comment by bhamiltoncx** [comment]
Interesting! Might be because you changed the logic to always read from
stdin if no args are specified? I wasn't quite sure what that part of your
change was about.
