### PR TITLE
Match fixed width ISD::AVGFLOORS + ISD::AVGCEILS patterns

### LINKED ISSUE #85779: [DAG] Match fixed width ISD::AVGFLOORS + ISD::AVGCEILS  patterns
Followup to #84749 and #84753

We can match the signed AVG variants in a similar way:
```ll
define i4 @src_avgfloors(i4 %a0, i4 %a1)  {
  %and = and i4 %a0, %a1
  %xor = xor i4 %a0, %a1
  %srl = ashr i4 %xor, 1
  %res = add i4 %and, %srl
  ret i4 %res
}
define i4 @src_avgceils(i4 %a0, i4 %a1)  {
  %or = or i4 %a0, %a1
  %xor = xor i4 %a0, %a1
  %srl = ashr i4 %xor, 1
  %res = sub i4 %or, %srl
  ret i4 %res
}
```
Alive2: https://alive2.llvm.org/ce/z/L4yGAx

### PR DESCRIPTION
**Pull request by houndlord**
Fixes #85779

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -3867,6 +3905,10 @@ SDValue DAGCombiner::visitSUB(SDNode *N) {
   if (SDValue V = combineFixedwidthToAVGCEILU(N, DAG))
     return V;
 
+  // Try to match AVGCEILS fixedwidth pattern
+  if (SDValue V = combineFixedwidthToAVGCEILS(N, DAG))
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:3909]: Merge this into combineFixedwidthToAVGCEILU (rename to combineFixedwidthToAVGCEIL)

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 2]
```diff
@@ -2872,6 +2906,10 @@ SDValue DAGCombiner::visitADD(SDNode *N) {
   // Try to match AVGFLOORU fixedwidth pattern
   if (SDValue V = combineFixedwidthToAVGFLOORU(N, DAG))
     return V;
+  
+  // Try to match AVGFLOORU fixedwidth pattern
+  if (SDValue V = combineFixedwidthToAVGFLOORS(N, DAG))
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:2911]: Merge this into combineFixedwidthToAVGFLOORU (rename to combineFixedwidthToAVGFLOOR)

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 3]
```diff
@@ -2529,18 +2529,23 @@ static SDValue foldAddSubBoolOfMaskedVal(SDNode *N, SelectionDAG &DAG) {
...
-static SDValue combineFixedwidthToAVGCEILU(SDNode *N, SelectionDAG &DAG) {
+// Attempt to form avgceil(A, B) from (A | B) - ((A ^ B) >> 1)
+static SDValue combineFixedwidthToAVGCEIL(SDNode *N, SelectionDAG &DAG) {
   const TargetLowering &TLI = DAG.getTargetLoweringInfo();
   SDValue N0 = N->getOperand(0);
   EVT VT = N0.getValueType();
   SDLoc DL(N);
-  if (TLI.isOperationLegal(ISD::AVGCEILU, VT)) {
+  if (TLI.isOperationLegal(ISD::AVGCEILU, VT) ||
+      TLI.isOperationLegal(ISD::AVGCEILS, VT)) {
```
Comment (davemgreen) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:2539]: It might be best if this was two if's. AArch64 will have both ceil and floor, but some architectures will have only one and this could create nodes where they are not legal.

Comment (houndlord) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:2539]: Ah, ok, actually my intent was simply avoid duplication of code, but it seems to be necessary.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 4]
```diff
@@ -2529,18 +2529,29 @@ static SDValue foldAddSubBoolOfMaskedVal(SDNode *N, SelectionDAG &DAG) {
...
-static SDValue combineFixedwidthToAVGCEILU(SDNode *N, SelectionDAG &DAG) {
+// Attempt to form avgceil(A, B) from (A | B) - ((A ^ B) >> 1)
+static SDValue combineFixedwidthToAVGCEIL(SDNode *N, SelectionDAG &DAG) {
   const TargetLowering &TLI = DAG.getTargetLoweringInfo();
   SDValue N0 = N->getOperand(0);
   EVT VT = N0.getValueType();
   SDLoc DL(N);
-  if (TLI.isOperationLegal(ISD::AVGCEILU, VT)) {
+  bool IsAVGCEILULegal = TLI.isOperationLegal(ISD::AVGCEILU, VT);
+  bool IsAVGCEILSLegal = TLI.isOperationLegal(ISD::AVGCEILS, VT);
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:2539]: Don't bother doing this - just keep the ifs separate instead of nesting them - you're not gaining anything, Pull out the `SDValue A, B` line and you're done.

**Review by davemgreen — APPROVED** [review]
Looks good to me. Thanks

File: llvm/test/CodeGen/AArch64/hadd-combine.ll [hunk 5]
```diff
@@ -341,6 +341,18 @@ define <8 x i16> @sub_fixedwidth_v4i32(<8 x i16> %a0, <8 x i16> %a1)  {
   ret <8 x i16> %res
 }
 
+define <8 x i16> @shsub_fixedwidth_v4i32(<8 x i16> %a0, <8 x i16> %a1)  {
```
Comment (RKSimon) [inline llvm/test/CodeGen/AArch64/hadd-combine.ll:344]: shsub_fixedwidth_v4i32 -> srhadd_fixedwidth_v8i16 (its matching the shsub instruction for v8i16 types)

File: llvm/test/CodeGen/AArch64/hadd-combine.ll [hunk 6]
```diff
@@ -879,6 +891,18 @@ define <8 x i16> @uhadd_fixedwidth_v4i32(<8 x i16> %a0, <8 x i16> %a1)  {
   ret <8 x i16> %res
 }
 
+define <8 x i16> @shadd_fixedwidth_v4i32(<8 x i16> %a0, <8 x i16> %a1)  {
```
Comment (RKSimon) [inline llvm/test/CodeGen/AArch64/hadd-combine.ll:894]: shadd_fixedwidth_v4i32 -> shadd_fixedwidth_v8i16 (its matching the shsub instruction for v8i16 types)

**Review by RKSimon — CHANGES_REQUESTED** [review]
One minor thing I've just noticed

**Review by RKSimon — APPROVED** [review]
LGTM - thank you!
