### PR TITLE
[clang] Fix filler handling for new expression with unspecified bound.

### LINKED ISSUE #81157: Clang rejects valid program having new C[]{1}
The following valid program is rejected by clang. [Demo](https://godbolt.org/z/hzxfdnzod)

```
struct C{
   C(int);
};
int main() {
    C *ptr{new C[]{1}}; //clang rejects but gcc accepts
}
```

### PR DESCRIPTION
**Pull request by efriedma-quic**
Array new with a runtime bound requires an "array filler" to initialize elements which aren't explicitly initialized.  Array new with an unspecified bound doesn't need this; the array length is a compile-time constant.  Make sure SemaInit doesn't confuse the two cases.

Fixes #81157.

### CODE REVIEW

File: clang/include/clang/Sema/Initialization.h [hunk 1]
```diff
@@ -335,8 +340,10 @@ class alignas(8) InitializedEntity {
   }
 
   /// Create the initialization entity for an object allocated via new.
-  static InitializedEntity InitializeNew(SourceLocation NewLoc, QualType Type) {
-    return InitializedEntity(EK_New, NewLoc, Type);
+  static InitializedEntity InitializeNew(SourceLocation NewLoc, QualType Type,
```
Comment (ojhunt) [inline clang/include/clang/Sema/Initialization.h]: I'd rather an enum for this over a bool flag, but I realize the general style is bools so I'll just be sad instead :D

**Review by ojhunt — APPROVED** [review]
Release note and minor test change and lgtm.

I've also filed a general issue to cover fixing the fairly messy handling of array allocations in BuildCXXNew
