### PR TITLE
[HLSL] add extra scalar vector overloads for clamp

### LINKED ISSUE #128230: [HLSL] `clamp` overloads with mixed scalar vector operands
Presently Clang fails to resolve `clamp` overloads if the range values are scalars. We should support overloads where either or both values can be scalars:

```hlsl
export int4 call(int4 I, int Min, int Max) {
    return clamp(I, Min, Max); // calls clamp(int4, int4, int4)
}
```

### PR DESCRIPTION
**Pull request by spall**
Add additional vector scalar overloads for clamp using templates
Add Tests
fixup tests which have changed.
Closes #128230

### CODE REVIEW

File: clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h [hunk 1]
```diff
@@ -35,25 +35,48 @@ namespace hlsl {
...
+#define _HLSL_BOTH_OVERLOADS_3(NAME, BASE_T, VECTOR_T, AVAIL)                  \
+  _HLSL_CAT(_HLSL_IF_TRUE_, AVAIL)                                             \
+  (_HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)) constexpr VECTOR_T NAME(        \
+      VECTOR_T p0, VECTOR_T p1, BASE_T p2) {                                   \
+    return _HLSL_CAT(__builtin_hlsl_elementwise_, NAME)(p0, p1, (VECTOR_T)p2); \
+  }                                                                            \
+  _HLSL_CAT(_HLSL_IF_TRUE_, AVAIL)                                             \
+  (_HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)) constexpr VECTOR_T NAME(        \
+      VECTOR_T p0, BASE_T p1, VECTOR_T p2) {                                   \
+    return _HLSL_CAT(__builtin_hlsl_elementwise_, NAME)(p0, (VECTOR_T)p1, p2); \
```
[the remark this answers is not in the document]
Comment (bob80905) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: Also, a thought:
Would we also need to do further possibilities such as if arg 1 and 3 are the base type, or 2 and 3? Or do we only want overloads when exactly one argument is the base type?

[the remark this answers is not in the document]
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: > Wouldn't we need one more possibility here? _HLSL_CAT(_HLSL_IF_TRUE_, AVAIL) (_HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)) constexpr VECTOR_T NAME( BASE_T p0, VECTOR_T p1, VECTOR_T p2) { return _HLSL_CAT(__builtin_hlsl_elementwise_, NAME)((VECTOR_T)p0, p1, p2); }
> 
> A cast to the first argument is missing.

In this case, clamp expects the first argument to always be a vector. And since this macro was at this time written only to be used by clamp, we only need the 2 overloads.

[the remark this answers is not in the document]
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: > Also, a thought: Would we also need to do further possibilities such as if arg 1 and 3 are the base type, or 2 and 3? Or do we only want overloads when exactly one argument is the base type?

Yes to the last question. There should already be an overload, for clamp and min and max, where args 2 and 3 are the base type.

[the remark this answers is not in the document]
Comment (bob80905) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: For clamp, I looked through lines 596 - 698 and didn't find the overload for clamp where args 2 and 3 are the base type. Am I missing something?

[the remark this answers is not in the document]
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: > For clamp, I looked through lines 596 - 698 and didn't find the overload for clamp where args 2 and 3 are the base type. Am I missing something?

int16_t clamp(int16_t, int16_t, int16_t); 
Is this what you mean? This is what I was referring to at least.

[the remark this answers is not in the document]
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: Do you mean where 2 and 3 are the base type but the first is a vector? I'm not sure if that is meant to be allowed.

[the remark this answers is not in the document]
Comment (bob80905) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:71]: Yes, that's one example of what I meant, or any overload where two of the three parameters are the base type.

**Review by bob80905 — APPROVED** [review]
Ok, given the specific conditions that:
1. there are 3 parameters
2. the first parameter should always be the vector type
3. and there should be at most one base type among all the parameters

This macro should work for that specific case.
I think it may need to be adjusted / more parameters may need to be added to the macro if there are later intrinsics that don't satisfy these specific conditions (that is, if there are 2 base types in the parameters that need to be cast to vector types).
Might need to double check with someone whether the vector base base case is allowed or not. But otherwise LGTM.

File: clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h [hunk 2]
```diff
@@ -9,6 +9,8 @@
 #ifndef _HLSL_HLSL_ALIAS_INTRINSICS_H_
 #define _HLSL_HLSL_ALIAS_INTRINSICS_H_
 
+#include "hlsl_compat_overloads.h"
```
Comment (farzonl) [inline clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:12]: does it make more sense to add this to `hlsl.h` I don't think any of the alias intrinsics need this.

File: clang/test/SemaHLSL/BuiltIns/clamp-errors.hlsl [hunk 3]
```diff
@@ -1,4 +1,4 @@
-// RUN: %clang_cc1 -finclude-default-header -triple dxil-pc-shadermodel6.6-library %s -fnative-half-type -emit-llvm-only -disable-llvm-passes -verify -verify-ignore-unexpected
+// RUN: %clang_cc1 -finclude-default-header -triple dxil-pc-shadermodel6.6-library %s -fnative-half-type -emit-llvm-only -disable-llvm-passes -verify -verify-ignore-unexpected=note
```
Comment (farzonl) [inline clang/test/SemaHLSL/BuiltIns/clamp-errors.hlsl:1]: would it be ok if we removed the `-verify-ignore-unexpected=note` and just add  the notes?

File: clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h (hunk 2 above)
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_alias_intrinsics.h:12]: Yeah I guess I was thinking of this as an extension of the hlsl_alias_intrinsics.h file, so I included it there, but I can include it in hlsl.h if that is more appropriate.

File: clang/test/SemaHLSL/BuiltIns/clamp-errors.hlsl (hunk 3 above)
Comment (spall) [reply clang/test/SemaHLSL/BuiltIns/clamp-errors.hlsl:1]: There were a substatial number of notes; this file original had a -verify-ignore-unexpected, so this is no worse than before and I think is actual more accurate to what we don't care about; because no errors or warnings should be ignored.  There are 41 ignored notes, which are almost all
"candidate function not viable: requires 3 arguments, but 1 was provided".  I don't think including them in this test file would provide value.

**Comment by spall** [comment]
I need to add more tests for certain odd cases.

**Review by farzonl — APPROVED** [review]

File: clang/test/CodeGenHLSL/builtins/clamp.hlsl [hunk 4]
```diff
@@ -81,6 +93,9 @@ int64_t3 test_clamp_long3(int64_t3 p0, int64_t3 p1) { return clamp(p0, p1,p1); }
 // CHECK: define [[FNATTRS]] <4 x i64> @_Z16test_clamp_long4
 // CHECK: call <4 x i64> @llvm.[[TARGET]].sclamp.v4i64
 int64_t4 test_clamp_long4(int64_t4 p0, int64_t4 p1) { return clamp(p0, p1,p1); }
+// CHECK: define [[FNATTRS]] <4 x i64> {{.*}}test_clamp_long4_mismatch
+// CHECK: call <4 x i64> @llvm.[[TARGET]].sclamp.v4i64
+int64_t4 test_clamp_long4_mismatch(int64_t4 p0, int64_t4 p1) { return clamp(p0, p0,p1); }
```
Comment (bob80905) [inline clang/test/CodeGenHLSL/builtins/clamp.hlsl:98]: There is no mismatch here, did you mean `int64_t4 p0, int64_t p1` ?

File: clang/test/CodeGenHLSL/builtins/clamp.hlsl [hunk 5]
```diff
@@ -94,6 +109,9 @@ uint64_t3 test_clamp_ulong3(uint64_t3 p0, uint64_t3 p1) { return clamp(p0, p1,p1
 // CHECK: define [[FNATTRS]] <4 x i64> @_Z17test_clamp_ulong4
 // CHECK: call <4 x i64> @llvm.[[TARGET]].uclamp.v4i64
 uint64_t4 test_clamp_ulong4(uint64_t4 p0, uint64_t4 p1) { return clamp(p0, p1,p1); }
+// CHECK: define [[FNATTRS]] <4 x i64> {{.*}}test_clamp_ulong4_mismatch
+// CHECK: call <4 x i64> @llvm.[[TARGET]].uclamp.v4i64
+uint64_t4 test_clamp_ulong4_mismatch(uint64_t4 p0, uint64_t4 p1) { return clamp(p0, p0,p1); }
```
Comment (bob80905) [inline clang/test/CodeGenHLSL/builtins/clamp.hlsl:114]: Same as above

Comment (spall) [reply clang/test/CodeGenHLSL/builtins/clamp.hlsl:114]: copy paste strikes again. thanks ill fix these

**Review by bob80905 — APPROVED** [review]

File: clang/lib/Headers/hlsl/hlsl_compat_overloads.h [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+// Note: Functions in this file are sorted alphabetically, then grouped by base
+// element type, and the element types are sorted by size, then singed integer,
+// unsigned integer and floating point. Keeping this ordering consistent will
+// help keep this file manageable as it grows.
+
+//===----------------------------------------------------------------------===//
+// clamp builtins overloads
+//===----------------------------------------------------------------------===//
+
+template <typename T, typename R, typename U, uint N>
```
Comment (farzonl) [inline clang/lib/Headers/hlsl/hlsl_compat_overloads.h:24]: how are you applying `_HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)` for the uint16_t and  half cases of . Are we exposing these clamp overloads for all shadermodels?

Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_compat_overloads.h:24]: I can apply _HLSL_16BIT_AVAILABILITY(shadermodel, 6.2)  if I call clamp instead of __builtin_hlsl_elementwise_clamp in the templates.

File: clang/lib/Headers/hlsl/hlsl_compat_overloads.h [hunk 7]
```diff
@@ -0,0 +1,59 @@
+//===--- hlsl_compat_overloads.h - Additional HLSL overload definitions for
+// intrinsics --===//
```
Comment (llvm-beanz) [inline clang/lib/Headers/hlsl/hlsl_compat_overloads.h:2]: nit: shorten the summary so this fits on one line.

**Review by llvm-beanz — COMMENTED** [review]
One small nit on formatting, otherwise looks good.

File: clang/test/SemaHLSL/BuiltIns/clamp-errors-half.hlsl [hunk 8]
```diff
@@ -0,0 +1,7 @@
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s
+
+// check we error on 16 bit type if shader model is too old
+// CHECK: '-enable-16bit-types' option requires target HLSL Version >= 2018 and shader model >= 6.2, but HLSL Version is 'hlsl202x' and shader model is '6.0'
+half test_half_error(half p0, int p1) {
```
Comment (farzonl) [inline clang/test/SemaHLSL/BuiltIns/clamp-errors-half.hlsl:5]:
```suggestion
TEST_TYPE test_16bit_error(TEST_TYPE p0, int p1) {
```

File: clang/test/SemaHLSL/BuiltIns/clamp-errors-16bit.hlsl [hunk 9]
```diff
@@ -0,0 +1,12 @@
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=half
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=half3
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=int16_t
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=int16_t3
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=uint16_t
+// RUN: not %clang_dxc -enable-16bit-types -T cs_6_0 -HV 202x %s 2>&1  | FileCheck %s -DTEST_TYPE=uint16_t3
+
+// check we error on 16 bit type if shader model is too old
+// CHECK: '-enable-16bit-types' option requires target HLSL Version >= 2018 and shader model >= 6.2, but HLSL Version is 'hlsl202x' and shader model is '6.0'
+half test_half_error(TEST_TYPE p0, int p1) {
```
Comment (farzonl) [inline clang/test/SemaHLSL/BuiltIns/clamp-errors-16bit.hlsl:10]: Ah I didn't think about testing vectors. Is that why you left the return type as half because `int p1` makes the whole thing a scalar?

Comment (spall) [reply clang/test/SemaHLSL/BuiltIns/clamp-errors-16bit.hlsl:10]: No thats just a mistake I'll go fix it. the return type should be TEST_TYPE!
