### PR TITLE
[clang-format] Fix mismatched break in BlockIndent

### LINKED ISSUE #103306: [clang-format] Weird line breaks with `AlignAfterOpenBracket: BlockIndent`
Following example showcases weird line-breaking choices with `AlignAfterOpenBracket: BlockIndent`:

- Pure LLVM style:
  ```cpp
  auto result = std::optional<int>(123)
                  .transform([](int n) { return n + 100; })
                  .transform([](int n) {
                      // multiline lambda
                      return std::to_string(n);
                  });
  ```

- With `AlignAfterOpenBracket: BlockIndent` 💥:
  ```cpp
  auto result = std::optional<int>(123).transform([](int n) { return n + 100; }
  ).transform([](int n) {
      // multiline lambda
      return std::to_string(n);
  });
  ```

- Desired output:
  ```cpp
  auto result = std::optional<int>(123)
      .transform([](int n) { return n + 100; })
      .transform([](int n) {
          // multiline lambda
          return std::to_string(n);
      });
  ```

Any ideas how to fix this? Can it be done just via the config?

## `.clang-format`

```yaml
---
BasedOnStyle: LLVM
AlignAfterOpenBracket: BlockIndent
AlignOperands: DontAlign
```

### PR DESCRIPTION
**Pull request by gedare**
Near the ColumnLimit a break could be inserted before a right parens with BlockIndent without a break after the matching left parens. Avoid these hanging right parens by disallowing breaks before right parens unless there was a break after the left parens.

Fixes #103306

### CODE REVIEW

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 1]
```diff
@@ -349,6 +349,13 @@ bool ContinuationIndenter::canBreak(const LineState &State) {
     }
   }
 
+  // Allow breaking before the right parens with block indentation if there was
+  // a break after the left parens, which is tracked by BreakBeforeClosingParen
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:353]:
```suggestion
  // a break after the left parens, which is tracked by BreakBeforeClosingParen.
```

File: clang/unittests/Format/FormatTest.cpp [hunk 2]
```diff
@@ -9608,6 +9608,10 @@ TEST_F(FormatTest, AlignsAfterOpenBracket) {
       "    \"a aaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaa\"\n"
       ");",
       Style);
+  verifyFormat("aaaaaaaaaaaaaaaaaaaaaaa(\n"
+               "    &bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9612]:
```suggestion
               "    &bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n"
```
Better still, trim another 20 `b`s and move the test case to the end of the unit test.

**Review by owenca — APPROVED** [review]

File: clang/unittests/Format/FormatTest.cpp (hunk 2 above)
Comment (gedare) [reply clang/unittests/Format/FormatTest.cpp]: Relocated and trimmed.
