### PR TITLE
[flang] fix scoping of cray pointer declarations and add check for initialization

### LINKED ISSUE #135579: [Flang] Incorrect execution result when a pointer variable of the same name is defined for each cray pointer in two dependent modules, and a different array address is defined for each pointer variable
```
Version of flang : 21.0.0(9fe6f6a0d430b872750354c20f3e4a651bd1f135)/AArch64
```

In the attached program, a pointer variable of the same name is defined for each `cray pointer` in two dependent modules (1), and a different array address is defined for each pointer variable (2).  
The execution result of such a program is incorrect.  
The value of `v1` in the main program is expected to be 1.0.

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

sngg752d_2.f90:
```fortran
module m1
  implicit none
  real::v1
  pointer (ptr,v1)  ! (1)
  real::x(2)
contains
  subroutine s
    implicit none
    x=[1,2]
    ptr=loc(x)  ! (2)
  end subroutine s
end module m1

module m2
  use m1
  implicit none
  private ptr
contains
  subroutine ss
    real::v2,y(2)
    pointer (ptr,v2)  ! (1)
    dimension v2(2)
    y=[11,12]
    ptr=loc(y)  ! (2)  The address assigned to ptr changes from the address of x to the address of y.
    write(6,*) "ss : v1 = ", v1, " v2 = ", v2
  end subroutine ss
end module m2

program main
  use m2
  implicit none
  call s
  call ss
  write(6,*) "main : v1 = ", v1
  print *,'pass'
end program main
```

```
$ flang sngg752d_2.f90; ./a.out
 ss : v1 =  11.  v2 =  11. 12.
 main : v1 =  -118116.53
 pass
$
```

```
$ gfortran -fcray-pointer sngg752d_2.f90; ./a.out
 ss : v1 =    1.00000000      v2 =    11.0000000       12.0000000
 main : v1 =    1.00000000
 pass
$
```

```
$ ifx sngg752d_2.f90; ./a.out
 ss : v1 =    1.000000      v2 =    11.00000       12.00000
 main : v1 =    1.000000
 pass
$
```

### PR DESCRIPTION
**Pull request by akuhlens**
This PR:
- makes Cray pointer declarations shadow previous bindings instead of modifying them,
- errors when the pointee of a cray pointee has the SAVE attribute, and
- adds a missing newline after dumping the list of cray pointers in a scope.

Closes #135579

### CODE REVIEW

File: flang/lib/Semantics/check-declarations.cpp [hunk 1]
```diff
@@ -963,7 +963,17 @@ void CheckHelper::CheckObjectEntity(
...
         symbol.name());
   }
-
+  if (symbol.test(Symbol::Flag::CrayPointee)) {
+    // NB, IsSaved was too smart here.
+    if (details.init()) {
+      messages_.Say(
+          "Cray pointee '%s' may not be initialized"_err_en_US, symbol.name());
+    } else if (symbol.attrs().test(Attr::SAVE) ||
+        symbol.implicitAttrs().test(Attr::SAVE)) {
```
Comment (klausler) [inline flang/lib/Semantics/check-declarations.cpp:972]: `implicitAttrs()` is always a subset of `attrs()` so you don't need to redundantly check it.

File: flang/lib/Semantics/check-declarations.cpp [hunk 2]
```diff
@@ -963,7 +963,17 @@ void CheckHelper::CheckObjectEntity(
...
+      messages_.Say(
+          "Cray pointee '%s' may not be SAVE"_err_en_US, symbol.name());
```
Comment (klausler) [inline flang/lib/Semantics/check-declarations.cpp:974]: "may not have the SAVE attribute" would be better

File: flang/lib/Semantics/check-declarations.cpp [hunk 3]
```diff
@@ -963,7 +963,17 @@ void CheckHelper::CheckObjectEntity(
         "'%s' is a data object and may not be EXTERNAL"_err_en_US,
         symbol.name());
   }
-
+  if (symbol.test(Symbol::Flag::CrayPointee)) {
+    // NB, IsSaved was too smart here.
+    if (details.init()) {
+      messages_.Say(
+          "Cray pointee '%s' may not be initialized"_err_en_US, symbol.name());
+    } else if (symbol.attrs().test(Attr::SAVE)) {
```
Comment (klausler) [inline flang/lib/Semantics/check-declarations.cpp:971]: The `else` here means that at most one message will issue.  Can't both be useful?

File: flang/lib/Semantics/resolve-names.cpp [hunk 4]
```diff
@@ -6650,7 +6650,7 @@ bool DeclarationVisitor::Pre(const parser::BasedPointer &) {
 
 void DeclarationVisitor::Post(const parser::BasedPointer &bp) {
   const parser::ObjectName &pointerName{std::get<0>(bp.t)};
-  auto *pointer{FindSymbol(pointerName)};
+  auto *pointer{FindInScope(pointerName)};
```
Comment (klausler) [inline flang/lib/Semantics/resolve-names.cpp:6653]: Do you need a test that demonstrates that an attempt to host-associate a Cray pointer will now fail with `implicit none (type)`?

File: flang/lib/Semantics/check-declarations.cpp (hunk 3 above)
Comment (akuhlens) [reply flang/lib/Semantics/check-declarations.cpp:971]: You are correct, I was thinking that anytime the statement was initialize you would get an extra error message about having the save attribute, and that being distracting / misleading. Now that I think about it again and more generally, we would want to show both when the variable has an explicit save attribute and was initialized.

File: flang/lib/Semantics/resolve-names.cpp (hunk 4 above)
Comment (akuhlens) [reply flang/lib/Semantics/resolve-names.cpp:6653]: I think the newly added test (resolve125.f90) shows what you are looking for, but let me know if you where thinking of something else.

**Review by klausler — APPROVED** [review]
