### PR TITLE
[Clang][OpenCL][AMDGPU] Allow a kernel to call another kernel

### LINKED ISSUE #60313: Unsupported calling convention: AMDGPU_KERNEL encountered when codegen some amdgpu (opencl) bitcode
I'm not sure whether this is a bug or a missing feature, but please look at https://github.com/littlewu2508/LLVMAMDGPUcodegenbug, which is the reproducing method.

The issue is, during codegen phase, some simple opencl program meets "Unsupported calling convention: AMDGPU_KERNEL", while using the ROCm-forked llvm, the issue does not exists. Using gdb, I found that with vanilla llvm, one of the instructions `I` in https://github.com/llvm/llvm-project/blob/c12386ae247c0d46e1d513942e322e3a0510b126/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L1136 has `OpCode=56` and `SubclassData=365`, which leads to 91 (CallingConv::AMDGPU_KERNEL) in followed steps (`LowerCallTo`, `LowerCall`, `CCAssignFnForCall`, etc), and finally get Unsupported calling convention issue. Gdb trace: 
[llvm-14.0.5-dbg-cmdline.log.gz](https://github.com/llvm/llvm-project/files/10510584/llvm-14.0.5-dbg-cmdline.log.gz)

For [ROCm forked llvm](https://github.com/RadeonOpenCompute/llvm-project/), there's no issue. My guess is that `source1.cl` is calling amdgpu kernel functions, but somehow it no `I` with 91 (CallingConv::AMDGPU_KERNEL) appearing, only 0 (CallingConv::C) is seen, so no unsupported calling convention issues (gdb trace: 
[ROCm-llvm-5.1.3-dbg-cmdline.log.gz](https://github.com/llvm/llvm-project/files/10510588/ROCm-llvm-5.1.3-dbg-cmdline.log.gz)). But I failed to find out which change they use to get things worked, due to lack of compiler knowledge, and inability to bisect [ROCm forked llvm](https://github.com/RadeonOpenCompute/llvm-project/) (encountered many build issues when bisecting).

Forgive me of using llvm-14 because I built the debug version of llvm/clang to start investigating th issue half a year earlier (original issue: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/issues/45). I can confirm that this situation still remains now for both llvm-15.0.7 and llvm-16

### PR DESCRIPTION
**Pull request by lalaniket8**
This feature is currently not supported in the compiler.
To facilitate this we emit a stub version of each kernel
function body with different name mangling scheme, and
replaces the respective kernel call-sites appropriately.
    
Fixes https://github.com/llvm/llvm-project/issues/60313
    
D120566 was an earlier attempt made to upstream a solution
for this issue.

### CODE REVIEW

**Comment by lalaniket8** [comment]
* **#115821** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115821?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lalaniket8 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: clang/lib/CodeGen/CGOpenCLRuntime.cpp [hunk 1]
```diff
@@ -127,7 +127,10 @@ static const BlockExpr *getBlockExpr(const Expr *E) {
 void CGOpenCLRuntime::recordBlockInfo(const BlockExpr *E,
                                       llvm::Function *InvokeF,
                                       llvm::Value *Block, llvm::Type *BlockTy) {
-  assert(!EnqueuedBlockMap.contains(E) && "Block expression emitted twice");
+
+  // FIXME: Since OpenCL Kernels are emitted twice (kernel version and stub
+  // version), its constituent BlockExpr will also be emitted twice.
+  // assert(!EnqueuedBlockMap.contains(E) && "Block expression emitted twice");
```
Comment (lalaniket8) [inline clang/lib/CodeGen/CGOpenCLRuntime.cpp:133]: If Kernel function contains BlockExpr, the BlockExpr *E is emitted twice (once during emission of kernel function and other while emission of its device variant). This leads to a failing assert which finds BlockExpr pointer E stored in EnqueuedBlockMap.

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl [hunk 2]
```diff
@@ -0,0 +1,43 @@
+// RUN: %clang_cc1 -triple amdgcn-unknown-unknown -emit-llvm -o - %s | FileCheck %s
```
Comment (jhuber6) [inline clang/test/CodeGenOpenCL/opencl-kernel-call.cl:1]: Might be easier to autogenerate this with `update_cc_test_checks.py`.

File: clang/test/CodeGenOpenCL/visibility.cl [hunk 3]
```diff
@@ -126,3 +137,19 @@ void use() {
...
+// FVIS-PROTECTED: define protected void @__clang_ocl_kern_imp_kern_hidden()
+// FVIS-HIDDEN: define protected void @__clang_ocl_kern_imp_kern_hidden()
+
+// FVIS-DEFAULT: define protected void @__clang_ocl_kern_imp_kern_protected()
+// FVIS-PROTECTED: define protected void @__clang_ocl_kern_imp_kern_protected()
+// FVIS-HIDDEN: define protected void @__clang_ocl_kern_imp_kern_protected()
+
+// FVIS-DEFAULT: define{{.*}} void @__clang_ocl_kern_imp_kern_default()
+// FVIS-PROTECTED: define{{.*}} void @__clang_ocl_kern_imp_kern_default()
+// FVIS-HIDDEN: define{{.*}} void @__clang_ocl_kern_imp_kern_default()
```
Comment (jhuber6) [inline clang/test/CodeGenOpenCL/visibility.cl:155]: Fix

**Review by jhuber6 — COMMENTED** [review]
So, the kernel metadata has a lot of special codegen associated with it. It seems the approach here is to turn the kernels into thin wrappers that call an outlined function?

**Comment by shiltian** [comment]
Yes, that's the idea. In that way, we will not have any function call to a `amdgpu_kernel`.

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl (hunk 2 above)
Comment (shiltian) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl:1]: I think we really need to force auto generate to make (other's) future life much easier.

Comment (cdevadas) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl:1]: I believe this test makes more sense to have the handpicked patterns to specifically look for the kernel &stub pair generated for the definitions and the call-site replacement with the stub equivalents. In the auto-generated test check sequence it would be quite difficult to examine the real intention of the test. He used the **regex** in the check lines where future changes might occur.
But if everyone thinks having autogenerated check lines are preferable, go for it.

File: clang/test/CodeGenOpenCL/visibility.cl (hunk 3 above)
Comment (lalaniket8) [reply clang/test/CodeGenOpenCL/visibility.cl]: Fixed, added EOF.

File: clang/lib/CodeGen/CGOpenCLRuntime.cpp (hunk 1 above)
Comment (lalaniket8) [reply clang/lib/CodeGen/CGOpenCLRuntime.cpp]: Added support to distinguish between BlockExpr emitted from Kernel and its device variant by adding a relevant flag in EnqueuedBlockInfo. Updated assert to look at this flag.

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl (hunk 2 above)
Comment (shiltian) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl:1]: the pair can be "detected" or checked by the check lines and any minor change could lead to a test failure, thus makes it more robust.

File: clang/include/clang/AST/GlobalDecl.h [hunk 4]
```diff
@@ -196,13 +203,21 @@ class GlobalDecl {
...
     Result.Value.setInt(unsigned(Kind));
     return Result;
   }
+
+  bool isDeclOpenCLKernel() const {
+    auto FD = dyn_cast<FunctionDecl>(getDecl());
+    if (FD)
+      return FD->hasAttr<OpenCLKernelAttr>();
+    return FD;
+  }
```
Comment (shiltian) [inline clang/include/clang/AST/GlobalDecl.h:220]:
```suggestion
  bool isDeclOpenCLKernel() const {
    if (auto FD = dyn_cast<FunctionDecl>(getDecl()))
      return FD->hasAttr<OpenCLKernelAttr>();
    return false;
  }
```

File: clang/lib/AST/ItaniumMangle.cpp [hunk 5]
```diff
@@ -1780,6 +1786,15 @@ void CXXNameMangler::mangleDeviceStubName(const IdentifierInfo *II) {
       << II->getName();
 }
 
+void CXXNameMangler::mangleOCLDeviceStubName(const IdentifierInfo *II) {
+  // <source-name> ::= <positive length number> __clang_ocl_kern_imp_
+  // <identifier> <number> ::= [n] <non-negative decimal integer> <identifier>
+  // ::= <unqualified source code identifier>
+  StringRef OCLDeviceStubNamePrefix = "__clang_ocl_kern_imp_";
```
Comment (shiltian) [inline clang/lib/AST/ItaniumMangle.cpp:1793]: I'd suggest using some symbols that a regular user-defined function can't be named to avoid conflict.

File: clang/include/clang/AST/GlobalDecl.h (hunk 4 above)
Comment (lalaniket8) [reply clang/include/clang/AST/GlobalDecl.h]: Commited suggestion in 013801b1fc82ec6806b876d93da24d4f0f2ed098

>

File: clang/lib/AST/ItaniumMangle.cpp (hunk 5 above)
Comment (lalaniket8) [reply clang/lib/AST/ItaniumMangle.cpp:1793]: names starting with double underscore are reserved, and shouldn't conflict with user defined names

File: clang/lib/CodeGen/CGExpr.cpp [hunk 6]
```diff
@@ -5692,7 +5692,10 @@ CGCallee CodeGenFunction::EmitCallee(const Expr *E) {
   // Resolve direct calls.
   } else if (auto DRE = dyn_cast<DeclRefExpr>(E)) {
     if (auto FD = dyn_cast<FunctionDecl>(DRE->getDecl())) {
-      return EmitDirectCallee(*this, FD);
+      auto CalleeDecl = FD->hasAttr<OpenCLKernelAttr>()
+                            ? GlobalDecl(FD, KernelReferenceKind::Stub)
+                            : FD;
+      return EmitDirectCallee(*this, CalleeDecl);
```
Comment (rjmccall) [inline clang/lib/CodeGen/CGExpr.cpp:5698]: Hmm.  It looks like the CUDA folks had this same problem and came up with an awkward workaround for it in `EmitDirectCallee`. We should really just be requesting the right GD in the first place. Could you add a `getGlobalDeclForDirectCall` function that does the right thing for both modes?  If it ends up causing complicated behavior/test changes in CUDA mode, you can feel free to exclude CUDA for now and just leave a comment saying that the workaround should be removed in favor of doing the right thing in that function.

**Review by rjmccall — CHANGES_REQUESTED** [review]

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+// CHECK: define dso_local void @caller_func({{.*}})
+void caller_func(global int* A){
+  callee_kern(A);
+  // CHECK: tail call void @__clang_ocl_kern_imp_callee_kern({{.*}}) #7
+  ext_callee_kern(A);
+  // CHECK: tail call void @__clang_ocl_kern_imp_ext_callee_kern({{.*}}) #8
+  callee_func(A);
+  // CHECK: tail call void @callee_func({{.*}})
+}
+
```
Comment (arsenm) [inline clang/test/CodeGenOpenCL/opencl-kernel-call.cl:39]: I'd like to see more ABI attributes stressed, especially for aggregates. Test some structs of different sizes, and vectors. Also add another target runline to make sure we test both byref and byval

File: clang/lib/AST/ItaniumMangle.cpp (hunk 5 above)
Comment (rjmccall) [reply clang/lib/AST/ItaniumMangle.cpp:1793]: Well, it's undefined behavior if they do, the same that you can technically define a function in C called `_Z3foov` with a completely different signature from what C++ would expect.  This sort of thing is generally fine as long as we make some effort to avoid unintentional conflicts.

File: clang/lib/CodeGen/CGBlocks.cpp [hunk 8]
```diff
@@ -1085,8 +1085,10 @@ llvm::Value *CodeGenFunction::EmitBlockLiteral(const CGBlockInfo &blockInfo) {
       blockAddr.getPointer(), ConvertType(blockInfo.getBlockExpr()->getType()));
 
   if (IsOpenCL) {
-    CGM.getOpenCLRuntime().recordBlockInfo(blockInfo.BlockExpression, InvokeFn,
-                                           result, blockInfo.StructureType);
+    CGM.getOpenCLRuntime().recordBlockInfo(
+        blockInfo.BlockExpression, InvokeFn, result, blockInfo.StructureType,
+        CurGD && CurGD.isDeclOpenCLKernel() &&
+            (CurGD.getKernelReferenceKind() == KernelReferenceKind::Kernel));
```
[the remark this answers is not in the document]
Comment (lalaniket8) [reply clang/lib/CodeGen/CGBlocks.cpp:1091]: Does that mean we replace the function body of the stub with a call to the respective kernel?
This way we emit the function body only once.
So a kernel to kernel function call is replaced by a kernel to stub to kernel call?

For example, the following snippet:
```
kernel void callee_kern(){

}
kernel void caller_kern(){
	callee_kern();
}
```

should generate IR that looks like:

```
define dso_local amdgpu_kernel void @callee_kern({{.*}}){
 
}
define dso_local void @_clang_ocl_kern_imp_callee_kern({{.*}}){
	entry:
	tail call amdgpu void @callee_kern({{.*}})
}
define dso_local amdgpu_kernel void @caller_kern({{.*}}){
	tail call void @__clang_ocl_kern_imp_callee_kern();
}
define dso_local void @_clang_ocl_kern_imp_caller_kern({{.*}}){
	tail call void @__clang_ocl_kern_imp_callee_kern();
}
```

[the remark this answers is not in the document]
Comment (rjmccall) [reply clang/lib/CodeGen/CGBlocks.cpp:1091]: That's one of the options, yeah. You'd always emit stubs as directly calling their kernels (so `_clang_ocl_kern_imp_caller_kern` would actually just call `caller_kern`, at least coming out of IRGen), and then you'd let LLVM decide when and whether to inline. The main disadvantage is that there might not already be code to emit calls to kernels; I imagine that's normally only done by the OpenCL runtime, and the ABI is probably pretty different from the normal call ABI.  But maybe that's not a big deal.

The second option is that you could emit stubs by making sure the kernel is emitted first and then directly cloning the kernel body into the stub.  Whether this is materially different from just inlining, I don't know, but it's an option. We do have code for this sort of thing already — we need it for emitting virtual varargs thunks in C++.

The third option is that you could emit kernels as directly calling their stubs. The advantage here is that all the calls are just normal calls that you definitely already have code to handle. The disadvantage is that you'd always be forcing the stub to be emitted, even in the 99% case that there are no other uses of it. It'll probably get reliably inlined away, but still, it's burning some extra compile time.

The last option is that you could emit kernels by emitting the stub and then directly cloning the function body into the kernel.

Up to you; they all have trade-offs. But I do think you need to not double-emit the kernel body.

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+// CHECK: define dso_local void @__clang_ocl_kern_imp_caller_kern({{.*}}) 
+// CHECK: tail call void @__clang_ocl_kern_imp_callee_kern({{.*}}) 
+// CHECK: tail call void @__clang_ocl_kern_imp_ext_callee_kern({{.*}}) 
+// CHECK: tail call void @callee_func({{.*}})
```
Comment (arsenm) [inline clang/test/CodeGenOpenCL/opencl-kernel-call.cl:43]: Another case to check is with the indirect call extension enabled. I would assume the address of operator should yield the callable function

File: clang/lib/CodeGen/CGBlocks.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (lalaniket8) [reply clang/lib/CodeGen/CGBlocks.cpp:1091]: > a kernel to kernel function call is replaced by a kernel to stub to kernel call 

Calls to kernel (from device and kernel functions) is not supported during backend IselLowering : https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.cpp#L1127
So, we can't have a stub calling a kernel go into the backend.
In-lining the callee kernel body into the stub function might not be helpful in cases where callee kernel is just a function declaration.

> kernel is emitted first and then directly cloning the kernel body into the stub

> emit kernels by emitting the stub and then directly cloning the function body into the kernel

Some doubts on these points: Wouldn't this also result in having two copies of the kernel body ? Would this avoid the problems we see during double emission ?

[the remark this answers is not in the document]
Comment (rjmccall) [reply clang/lib/CodeGen/CGBlocks.cpp:1091]: > Calls to kernel (from device and kernel functions) is not supported during backend IselLowering :

That makes sense.  Okay, so you need to call the stub.  That's probably fine — LLVM should reliably clean it up regardless — but it'll cause a lot of test case churn unless you force inlining prior to LLVM.

> Some doubts on these points: Wouldn't this also result in having two copies of the kernel body ? Would this avoid the problems we see during double emission ?

Having two copies of a function body is not the problem.  This is essentially just inlining, so as long as the kernel body doesn't do something that's semantically incompatible with inlining (which mostly just means the address-of-label extension), it's fine to inline.

The problem is that the visitor for emitting the body does not expect to run twice on the same code, and so it will emit code incorrectly for structures that require supporting global variables and functions, such as blocks and static locals.  For example, patch contains code to work around the double-emission of a block.

File: clang/lib/AST/ItaniumMangle.cpp [hunk 10]
```diff
@@ -1780,6 +1786,15 @@ void CXXNameMangler::mangleDeviceStubName(const IdentifierInfo *II) {
...
+  Out << II->getLength() + OCLDeviceStubNamePrefix.size() - 1
```
[the remark this answers is not in the document]
Comment (lalaniket8) [reply clang/lib/AST/ItaniumMangle.cpp]: I incorrectly assumed that we need to account for a trailing null character, fixed the same.

File: clang/lib/CodeGen/CGCall.cpp [hunk 11]
```diff
@@ -2343,6 +2343,15 @@ void CodeGenModule::ConstructAttributeList(StringRef Name,
   // Collect function IR attributes from the CC lowering.
   // We'll collect the paramete and result attributes later.
   CallingConv = FI.getEffectiveCallingConvention();
+  GlobalDecl GD = CalleeInfo.getCalleeDecl();
+  const Decl *TargetDecl = CalleeInfo.getCalleeDecl().getDecl();
+  if (TargetDecl) {
+    if (auto FD = dyn_cast<FunctionDecl>(TargetDecl)) {
+      if (FD->hasAttr<OpenCLKernelAttr>() &&
+          GD.getKernelReferenceKind() == KernelReferenceKind::Stub)
+        CallingConv = llvm::CallingConv::C;
```
[the remark this answers is not in the document]
Comment (lalaniket8) [reply clang/lib/CodeGen/CGCall.cpp]: Moved change of calling convention to `CodeGenTypes::arrangeFunctionDeclaration()` so that we obtain the correct `CGFunctionInfo`.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 6 above)
Comment (lalaniket8) [reply clang/lib/CodeGen/CGExpr.cpp]: I have added `getGlobalDeclForDirectCall()` which returns the correct GD for OpenCL mode, however I am a bit unclear on what is required for CUDA mode. 

>  CUDA folks had this same problem and came up with an awkward workaround for it in EmitDirectCallee

Are you referring to the [reassignment of CalleePtr ](https://github.com/llvm/llvm-project/blob/12d17535057faf07b39fe2f59b3952f7b817b780/clang/lib/CodeGen/CGExpr.cpp#L5682-L5685) in `EmitDirectCallee()`?
Do we want to [pass a GD into EmitDirectCallee()](https://github.com/llvm/llvm-project/blob/12d17535057faf07b39fe2f59b3952f7b817b780/clang/lib/CodeGen/CGExpr.cpp#L5709) which already contains the correct CalleePtr for CUDA mode ?

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl (hunk 7 above)
Comment (lalaniket8) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl]: [addr-space-struct-arg.cl](https://github.com/llvm/llvm-project/blob/12d17535057faf07b39fe2f59b3952f7b817b780/clang/test/CodeGenOpenCL/addr-space-struct-arg.cl), [amdgpu-abi-struct-arg-byref.cl](https://github.com/llvm/llvm-project/blob/12d17535057faf07b39fe2f59b3952f7b817b780/clang/test/CodeGenOpenCL/amdgpu-abi-struct-arg-byref.cl) tests for different aggregates passed byref and byval.

Do let me know if we need to account for some other cases not in these littests.

Comment (arsenm) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl]: Those look like they are just updates of existing tests for incidental codegen changes. They do not demonstrate these cases when a kernel calls another kernel

File: clang/lib/CodeGen/CGExpr.cpp (hunk 6 above)
Comment (rjmccall) [reply clang/lib/CodeGen/CGExpr.cpp]: Yeah, that's what I meant, and yeah, I feel like we should just pass down the right GD.

Comment (lalaniket8) [reply clang/lib/CodeGen/CGExpr.cpp]: I see, I can get the correct CalleePtr which is of type `llvm::Constant`, but I am not able to figure out how to convert the same into a `GlobalDecl` object.

Comment (lalaniket8) [reply clang/lib/CodeGen/CGExpr.cpp]: I see, I can get the correct CalleePtr which is of type `llvm::Constant`, but I am not able to figure out how to convert the same into a `GlobalDecl` object.

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl (hunk 7 above)
Comment (lalaniket8) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl:120]: RIght, I have updated the test

File: clang/lib/CodeGen/CodeGenFunction.cpp [hunk 12]
```diff
@@ -1582,6 +1582,26 @@ void CodeGenFunction::GenerateCode(GlobalDecl GD, llvm::Function *Fn,
     // Implicit copy-assignment gets the same special treatment as implicit
     // copy-constructors.
     emitImplicitAssignmentOperatorBody(Args);
+  } else if (FD->hasAttr<OpenCLKernelAttr>() &&
+             GD.getKernelReferenceKind() == KernelReferenceKind::Kernel) {
+    CallArgList CallArgs;
+    for (unsigned i = 0; i < Args.size(); ++i) {
+      Address ArgAddr = GetAddrOfLocalVar(Args[i]);
+      QualType ArgQualType = Args[i]->getType();
+      RValue ArgRValue = convertTempToRValue(ArgAddr, ArgQualType, Loc);
```
Comment (lalaniket8) [inline clang/lib/CodeGen/CodeGenFunction.cpp:1591]: To emit call to device function, I need to pass the arguments of kernel function, which reside in `FunctionArgList Args` to `EmitCall()`. To do this I have used an object of `CallArgList` and passed the same to `EmitCall()` method. 

I iterate over each argument and construct `CallArgList` using `convertTempToRValue()`

Is this approach to construct `CallArgList` correct?

**Comment by arsenm** [comment]
reverse ping

**Comment by lalaniket8** [comment]
> reverse ping

I have gone through all the review comments and made required changes. Awaiting final review @yxsamliu @rjmccall @arsenm

File: clang/lib/CodeGen/CodeGenFunction.cpp (hunk 12 above)
Comment (yxsamliu) [reply clang/lib/CodeGen/CodeGenFunction.cpp:1591]: My only concern is struct type argument passed by value, currently, they seem to be handled specially

https://godbolt.org/z/bo9aveqn3

I am not sure your current approach will work for that, although it may. I think you may want to add a lit test for that. Also try compile to ISA and see how does it compare with passing it to a normal function.

Did your PR pass internal CI?

Comment (shiltian) [reply clang/lib/CodeGen/CodeGenFunction.cpp:1591]: We will switch to byref once this is fixed actually.

**Comment by arsenm** [comment]
tests need updating to current main

File: clang/lib/CodeGen/CodeGenFunction.cpp (hunk 12 above)
Comment (lalaniket8) [reply clang/lib/CodeGen/CodeGenFunction.cpp:1592]: > > Although we don't see the callsite in this littest since it gets inlined away.
> 
> We shouldn't be running these optimizations in a frontend test

If we want to stop inlining for this test, we can add `-disable-llvm-passes` to it's runlines

File: clang/lib/CodeGen/CGCall.cpp [hunk 13]
```diff
@@ -498,7 +498,9 @@ CodeGenTypes::arrangeCXXConstructorCall(const CallArgList &args,
 /// Arrange the argument and result information for the declaration or
 /// definition of the given function.
 const CGFunctionInfo &
-CodeGenTypes::arrangeFunctionDeclaration(const FunctionDecl *FD) {
+CodeGenTypes::arrangeFunctionDeclaration(const GlobalDecl GD) {
+  const FunctionDecl *FD = dyn_cast<FunctionDecl>(GD.getDecl());
+  assert(FD && "GD must contain FunctionDecl");
```
Comment (arsenm) [inline clang/lib/CodeGen/CGCall.cpp:503]: `cast<>` instead of dyn_cast + assert

Comment (lalaniket8) [reply clang/lib/CodeGen/CGCall.cpp]: Fixed in latest commit

File: clang/lib/AST/ItaniumMangle.cpp (hunk 5 above)
Comment (arsenm) [reply clang/lib/AST/ItaniumMangle.cpp:1794]: In terms of how the symbols should behave, this might be backwards. Alternatively we could preserve the as-is name as the callable implicit function, and add some mangling to the kernel entry point. However, I bet there's a lot more code expecting the current kernel name used directly as kernel symbol behavior though, so maybe changing that is best left for later

File: clang/lib/AST/MicrosoftMangle.cpp [hunk 14]
```diff
@@ -1162,9 +1162,15 @@ void MicrosoftCXXNameMangler::mangleUnqualifiedName(GlobalDecl GD,
                   ->getTemplatedDecl()
                   ->hasAttr<CUDAGlobalAttr>())) &&
             GD.getKernelReferenceKind() == KernelReferenceKind::Stub;
+        bool IsOCLDeviceStub =
+            ND && (isa<FunctionDecl>(ND) && ND->hasAttr<OpenCLKernelAttr>()) &&
```
Comment (arsenm) [inline clang/lib/AST/MicrosoftMangle.cpp:1166]:
```suggestion
            ND && isa<FunctionDecl>(ND) && ND->hasAttr<OpenCLKernelAttr>() &&
```

File: clang/lib/AST/MicrosoftMangle.cpp [hunk 15]
```diff
@@ -1162,9 +1162,15 @@ void MicrosoftCXXNameMangler::mangleUnqualifiedName(GlobalDecl GD,
...
+            GD.getKernelReferenceKind() == KernelReferenceKind::Stub;
         if (IsDeviceStub)
           mangleSourceName(
               (llvm::Twine("__device_stub__") + II->getName()).str());
+        else if (IsOCLDeviceStub)
+          mangleSourceName(
+              (llvm::Twine("__clang_ocl_kern_imp_") + II->getName()).str());
```
Comment (arsenm) [inline clang/lib/AST/MicrosoftMangle.cpp:1173]: I'm surprised mangleSourceName doesn't take a twine already. Probably should fix that later

File: clang/lib/CodeGen/CGExpr.cpp [hunk 16]
```diff
@@ -6127,6 +6133,12 @@ RValue CodeGenFunction::EmitCall(QualType CalleeType,
 
   const auto *FnType = cast<FunctionType>(PointeeType);
 
+  if (auto FD = dyn_cast_or_null<FunctionDecl>(TargetDecl)) {
+    if (FD->hasAttr<OpenCLKernelAttr>()) {
+      CGM.getTargetCodeGenInfo().setOCLKernelStubCallingConvention(FnType);
+    }
+  }
```
Comment (arsenm) [inline clang/lib/CodeGen/CGExpr.cpp:6140]:
```suggestion
  if (const auto *FD = dyn_cast_or_null<FunctionDecl>(TargetDecl);
       FD && FD->hasAttr<OpenCLKernelAttr>())
    CGM.getTargetCodeGenInfo().setOCLKernelStubCallingConvention(FnType);
```

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 17]
```diff
@@ -6138,6 +6150,17 @@ void CodeGenModule::EmitGlobalFunctionDefinition(GlobalDecl GD,
...
+
+  if (D->hasAttr<OpenCLKernelAttr>()) {
+    if (GD.getKernelReferenceKind() == KernelReferenceKind::Stub) {
+      if (Fn->hasFnAttribute(llvm::Attribute::NoInline))
+        Fn->removeFnAttr(llvm::Attribute::NoInline);
+      if (Fn->hasFnAttribute(llvm::Attribute::InlineHint))
+        Fn->removeFnAttr(llvm::Attribute::InlineHint);
+      Fn->addFnAttr(llvm::Attribute::AlwaysInline);
+    }
+  }
```
Comment (arsenm) [inline clang/lib/CodeGen/CodeGenModule.cpp:6162]: I don't see a reason to fiddle with the inline attributes. This is just going to cause trouble whenever optnone is used, just leave it alone

File: clang/test/CodeGenOpenCL/opencl-kernel-call.cl (hunk 2 above)
Comment (lalaniket8) [reply clang/test/CodeGenOpenCL/opencl-kernel-call.cl]: Changed test file to auto generate using update_cc_test_checks.py with --include-generated-funcs argument. This can detect and include stub variants.

File: clang/lib/AST/MicrosoftMangle.cpp (hunk 14 above)
Comment (lalaniket8) [reply clang/lib/AST/MicrosoftMangle.cpp]: Fixed

File: clang/lib/CodeGen/CGExpr.cpp (hunk 16 above)
Comment (lalaniket8) [reply clang/lib/CodeGen/CGExpr.cpp]: Fixed

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 17 above)
Comment (lalaniket8) [reply clang/lib/CodeGen/CodeGenModule.cpp]: I see, yes it seems that adding the alwaysinline attribute is not necessary. I have removed it in the latest commit and made required changes in the test files.

**Comment by lalaniket8** [comment]
pinging for review @arsenm @yxsamliu @rjmccall

**Review by arsenm — APPROVED** [review]
lgtm with nits

**Review by yxsamliu — APPROVED** [review]
LGTM. Thanks

**Review by arsenm — APPROVED** [review]

**Comment by MrSidims** [comment]
@lalaniket8 @arsenm I don't have a strong opinion, but shouldn't this transformation be done during lowering to the target? Current version of the patch brings odd behavior for LLVM IR to SPIR-V lowering for OpenCL kernels. SPIR-V don't allow one EntryPoint to refer another EntryPoint, so during such lowering the translator moves kernel's body to impl function (just like this patch does). Together it results in quite odd behavior: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/3115

**Comment by yxsamliu** [comment]
> @lalaniket8 @arsenm I don't have a strong opinion, but shouldn't this transformation be done during lowering to the target? Current version of the patch brings odd behavior for LLVM IR to SPIR-V lowering for OpenCL kernels. SPIR-V don't allow one EntryPoint to refer another EntryPoint, so during such lowering the translator moves kernel's body to impl function (just like this patch does). Together they result in quite odd behavior: [KhronosGroup/SPIRV-LLVM-Translator#3115](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/3115)

My understanding is that for most targets kernel and non-kernel functions have different calling conventions which affects how struct-type arguments are passed. Allowing kernel functions callable in IR could cause issues in mid-end, that is why for any kernel a non-kernel `__clang_ocl_kern_imp*` function is created and used where the kernel function is called. This is necessary to have the proper IR.

For LLVM/SPIRV translator, this change should be transparent. `__clang_ocl_kern_imp*` should behave like a common non-kernel function called by a kernel function.

@arsenm

**Comment by arsenm** [comment]
> @lalaniket8 @arsenm I don't have a strong opinion, but shouldn't this transformation be done during lowering to the target? 

This is the lowering to the target. 


> Current version of the patch brings odd behavior for LLVM IR to SPIR-V lowering for OpenCL kernels. SPIR-V don't allow one EntryPoint to refer another EntryPoint, 

Yes, that's the entire point of this change. We've avoided introducing the invalid situation of an entry calling another entry, which requires 2 IR function bodies with different calling conventions. The calling convention is getting set incorrectly on the implementation function if you see an entry calling another entry

**Comment by MrSidims** [comment]
> This is the lowering to the target.

My glossary might not be lacking some definitions, but what I really meant by lowering is: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU or https://github.com/llvm/llvm-project/tree/main/llvm/lib/Target/SPIRV .

I definitely see a value of having this resolved in one place instead of multiple places, and clang is a good candidate for it. On the other hand: a. some targets don't have such restriction; 2. clang is not a single frontend, especially now - in MLIR world, does it mean, what every frontend should make such adjustment when lowering to AMDGPU or SPIR-V?

Just a note/disclaimer, this change makes sense and it doesn't bring (known to me, the reason I'm here is a surprise to see [this](https://godbolt.org/z/zW84fdace) during my experiments) regressions in some downsteam and adjusting tests in the translator is totally fine for me. What I'm trying to understand if it's really should be done in clang for OpenCL for every target.

**Comment by bwyma** [comment]
@t-tye Would you mind reviewing this patch from a debug perspective?

Potentially multiple subprograms with the same source name, same source correlation in different routines, missing artificial or trampoline attributes, stepping between functions works as expected, etc. Your input would be appreciated.

**Comment by MrSidims** [comment]
> this change makes sense and it doesn't bring (known to me) regressions

Actually, there is an incorrect behavior in the following test case: https://godbolt.org/z/dc3T7Mo3G , note __clang_ocl_kern_imp_sample_kernel_float was generated, but was never called. @lalaniket8 can this be addressed?

**Comment by lalaniket8** [comment]
> > this change makes sense and it doesn't bring (known to me) regressions
> 
> Actually, there is an incorrect behavior in the following test case: https://godbolt.org/z/dc3T7Mo3G , note __clang_ocl_kern_imp_sample_kernel_float was generated, but was never called. @lalaniket8 can this be addressed?

The call was placed and inlined since -O2 optimization flag was passed. Default inlining happens with -O1 and  higher flags. 
You can change it to -O0 and see the call to `__clang_ocl_kern_imp_sample_kernel_float`.

**Comment by arsenm** [comment]
> My glossary might be lacking some definitions, but what I really meant by lowering is

The IR is not a direct vehicle for language semantics. This case should explicitly not be representable in the target IR, and the frontend needs to implement the calling convention in terms of valid IR for the target.

>  What I'm trying to understand if it's really should be done in clang for OpenCL for every target.

This is implementing a stupid OpenCL feature nobody asked for, so clang should deal with it. Every other language can happily ignore this. AMDGPU, NVPTX, and SPIRV all have the same behavior where kernels / entry points are a separate calling convention that cannot be called from device code. This call should be unrepresentable in the IR, and forcing it to be such just makes the backends worse. We cannot move the calling convention lowering forward without removing this artificial usage.

**Comment by BukeBeyond** [comment]
> Doesn't OpenCL have an extension system? You could make an extension to disable this feature instead of putting it in the compiler I'd think. I'm not sure how SPIR-V works, but normally we differentiate between globals needed for the user and internal globals by their visibility. Hidden visibility variables are internalized at link time / not emitted while others can be read by the user while loading the GPU blob, so they must stay.

You are right!
`#pragma OPENCL EXTENSION __cl_clang_kernel_stub : disable`
would be the better place for this switch, though it may be more difficult to implement than an experimental Clang flag.  It is possible the stub generation here or the global variable optimization may improve in the future, when the stub feature can be safely enabled for all cases.

Kernels have exclusive access to private (register) and local (core memory) objects, but we need to give access to these states from other functions and methods without explicit wiring.  Imagine a print() function that needs to be wired at every use, and the state passed everywhere would make for very ineloquent code!  

We lifted some artificial limits in Clang and OpenCL to allow a global pointer to a private object inside the kernel.  The optimization passes in LLVM do an excellent job eliminating everything, Methods, Lambdas to a flat stream of code in the kernel body.  All the struct definitions are also eliminated, which otherwise Clspv cannot handle.

**Comment by jhuber6** [comment]
Also, if you're compiling C++26, why is it enabling OpenCL language features? You can already do this pretty easily with `clang --target=spirv64` so long as you're okay with using vendor intrinsic extensions in SPIR-V. That's pretty much what the HIP support for SPIR-V does anyways.

**Comment by BukeBeyond** [comment]
> It's not actually clang's responsibility to not break your transformation. We don't want to break it gratuitously, but if clang is generating correct code, your transformation needs to be flexible enough to handle it. If there's something easy we can do to help your transformation continue to work while still compiling the source language properly, of course, we're absolutely open to requests.

Understandably, Nvidia, AMD, Apple, all have self interests to sabotage genuine interoperability through Vulkan Compute.  The short sightedness here is that, when you do that, you also slow down your own adaption of your own hardware.  Software developers want to build once and have it work everywhere, despite your pursuits to cage them.  Ultimately, this results in underutilization of your hardware.

Who knows what other optimizations this commit has broken.  We are fine to branch off of it as it is easy enough to disable.

**Comment by rjmccall** [comment]
I am not speaking for Apple, and nobody is trying to sabotage anything. If you are writing a transform that claims to work for arbitrary programs, it needs to handle a reasonable range of compiler output. The change introduced by this patch is that the kernel function turns around and calls another function; that is reasonable compiler output that could be produced by normal source. If you feel that there's a technical reason that the compiler output is no longer reasonable, you are welcome to bring it up as a technical argument.

**Comment by BukeBeyond** [comment]
You are speaking for Apple, you are not even involved in this AMD commit, and your Apple Swift is vastly inferior to Clang C++26 with your inferior hardware compared to AMD which is at least 4x performant. You certainly want these projects, OpenCL destroyed to appease your Apple CEOs and your Lawyers.  Try to be an Engineer oneday.

**Comment by BukeBeyond** [comment]
> @BukeBeyond -- please familiarize yourself with our community [Code of Conduct](https://llvm.org/docs/CodeOfConduct.html). Telling people who they are speaking for, accusing people of malicious intent, and demeaning people are not in line with our community standards. Editing your comments and/or adding a small apology would be appropriate.

You would not be as offended and censoring if what I said was not True.  A so called "engineer" who is primarily invested in Apple and Swift has no Genuine place in a Productive conversation about SPIRV and OpenCL.  These technologies are their mortal enemy, and this is simply Public Knowledge.

The optimization passes for SPIRV are Essential.  As you may know, if you do, that most of the ,current GPUs do not have a Stack, and cannot produce function calls.  While bypassing an optimization like Inlining code, may be fine, dandy and Correct for regular CPUs, it will break SPIRV.  So your argument here is Practically and Technically Ignorant.

Your gang has taken over the C++ project, and even rejecting the inventor of C++ Bjarne Stroustrup.  Here is his paper from 11 years ago that you keep on rejecting with your delusions of grandeur. 
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4174.pdf

Ban me all you want, I will tell the tale, and with you in it.
