### PR TITLE
[DXIL] Remove incompatible metadata types when preparing DXIL.

### LINKED ISSUE #134575: [DirectX] Strip loop metadata that will trip up the validator when generating DXIL
Compiling [particle_life](https://github.com/damyanp/dplife/blob/main/src/particle_life/particle_life.hlsl) with clang fails the validator with an error about `llvm.loop.mustprogress` being invalid. This particular metadata node is newer than the version of LLVM that DXIL is based off of, so it makes sense that it's a problem.

We need to strip metadata that the DXIL validator (and thus, potentially, DXIL drivers) isn't aware of. This may be as simple as the following:

```diff
--- a/llvm/lib/Target/DirectX/DXILPrepare.cpp
+++ b/llvm/lib/Target/DirectX/DXILPrepare.cpp
@@ -189,6 +189,26 @@ public:
       for (auto &BB : F) {
         IRBuilder<> Builder(&BB);
         for (auto &I : make_early_inc_range(BB)) {
+
+          // TODO: Audit this list - is it enough? Too much?
+          static unsigned DXILCompatibleMDs[] = {
+              LLVMContext::MD_dbg,
+              LLVMContext::MD_tbaa,
+              LLVMContext::MD_prof,
+              LLVMContext::MD_fpmath,
+              LLVMContext::MD_range,
+              LLVMContext::MD_tbaa_struct,
+              LLVMContext::MD_invariant_load,
+              LLVMContext::MD_alias_scope,
+              LLVMContext::MD_noalias,
+              LLVMContext::MD_nontemporal,
+              LLVMContext::MD_mem_parallel_loop_access,
+              LLVMContext::MD_nonnull,
+              LLVMContext::MD_dereferenceable,
+              LLVMContext::MD_dereferenceable_or_null,
+          };
+          I.dropUnknownNonDebugMetadata(DXILCompatibleMDs);
+
           if (I.getOpcode() == Instruction::FNeg) {
             Builder.SetInsertPoint(&I);
             Value *In = I.getOperand(0);
```

Here, we strip anything that isn't listed in DXC's set of pinned metadata names in `LLVMContext.h`. We need to determine if this is the right granularity.

### PR DESCRIPTION
**Pull request by bob80905**
This PR introduces a Metadata Node Kind allowlist. The purpose is to prevent newer Metadata Node Kinds to be used and inserted into the outputted DXIL module.  Only the metadata kinds that are accepted in the DXIL Validator are on the allowlist. The Github DXC validator doesn't support these newer Metadata Node Kinds, so we need to filter them out. 

We introduce this restrictive allowlist into LLVM and strip all metadata that isn't found in the list.

The accompanying test would add the `llvm.loop.mustprogress` metadata node kind, but thanks to the allowlist, filters it out, and so the whitelist is proven to work.
The test also has two separate metadata kinds that are on the allowlist, and remain after the DXIL Prepare pass.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILPrepare.cpp [hunk 1]
```diff
@@ -189,6 +189,26 @@ class DXILPrepareModule : public ModulePass {
...
+              LLVMContext::MD_invariant_load,
+              LLVMContext::MD_alias_scope,
+              LLVMContext::MD_noalias,
+              LLVMContext::MD_nontemporal,
+              LLVMContext::MD_mem_parallel_loop_access,
+              LLVMContext::MD_nonnull,
+              LLVMContext::MD_dereferenceable,
+              LLVMContext::MD_dereferenceable_or_null,
+          };
+          I.dropUnknownNonDebugMetadata(DXILCompatibleMDs);
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILPrepare.cpp:210]: I don't think this list is correct. Looking at what we have here and considering what the DXIL validator handles in [ValidateInstructionMetadata](https://github.com/microsoft/DirectXShaderCompiler/blob/8280d0fb4104ce9c67af3b9f4a1335760c7c5113/lib/DxilValidation/DxilValidation.cpp#L2606-L2633):
- `MD_dbg` probably doesn't do anything in this list, given the function is about "non-debug metadata"
- There are a couple of dxil-specific MD node types that we need to let through ("dx.controlflow.hints", "dx.precise", "dx.nonuniform")
- TBAA metadata is allowed but has further validations. We can probably just let it through for now though and file a follow up to make sure we're matching what the validator accepts.
- Loop metadata is allowed but has further validations. Unfortunately, we do need to do some work if we want to accept "llvm.loop.unroll.full" but not "llvm.loop.mustprogress"
- All other metadata types are rejected, except MD_range, MD_noalias, and MD_alias_scope

So I guess we want to break out a `getCompatibleInstructionMDs()` function that populates a list with the ones that are allowed (both simple enum ones like MD_noalias and ones we need to look up like `Ctx.getMDKindID("dx.nonuniform")`, and then call that outside of the loop and reuse it for the per-instruction calls to `dropUnknownNonDebugMetadata`

I think it makes sense to just do the above in this PR, and drop MD_tbaa and MD_loop for now, but file two issues to do the correct validation / downgrade for those two in particular.

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:1]: This test can be simplified a lot. We can probably drop everything DXIL specific and reduce this down to just a function with a couple of blocks that are mostly empty. Notably only the `br` instruction with the `!llvm.loop` metadata is really essential.

**Review by bogner — CHANGES_REQUESTED** [review]

File: llvm/lib/Target/DirectX/DXILPrepare.cpp (hunk 1 above)
Comment (bob80905) [reply llvm/lib/Target/DirectX/DXILPrepare.cpp]: https://github.com/llvm/llvm-project/issues/137386
https://github.com/llvm/llvm-project/issues/137387
Created

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+for.body.i:                                       ; preds = %entry
+  %cmp.i = icmp ult i32 1, 2
+  br i1 %cmp.i, label %for.body.i, label %_Z4mainDv3_j.exit, !llvm.loop !16
+
+_Z4mainDv3_j.exit:                                ; preds = %for.body.i, %entry
+  ret void
+
+; uselistorder directives
+  uselistorder label %for.body.i, { 1, 0 }
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:32]: The `uselistorder` shouldn't be necessary here

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+; Function Attrs: noinline nounwind memory(readwrite, inaccessiblemem: none)
+define void @main() local_unnamed_addr #0 {
+entry:  
+  %cmp.i1.not = icmp eq i32 1, 0
+  br i1 %cmp.i1.not, label %_Z4mainDv3_j.exit, label %for.body.i
+
+for.body.i:                                       ; preds = %entry
+  %cmp.i = icmp ult i32 1, 2
+  br i1 %cmp.i, label %for.body.i, label %_Z4mainDv3_j.exit, !llvm.loop !16
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:26]: It would be good to check that this `br` instruction is present, but doesn't have the `llvm.loop` metadata

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+attributes #1 = { memory(read) }
+attributes #2 = { memory(none) }
+
+!dx.valver = !{!0}
+!llvm.ident = !{!1}
+!dx.shaderModel = !{!2}
+!dx.version = !{!3}
+!dx.resources = !{!4}
+!dx.entryPoints = !{!11}
+!llvm.module.flags = !{!14, !15}
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:57]: All of this can be removed

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+!12 = !{i32 0, i64 16, i32 4, !13}
+!13 = !{i32 1, i32 1, i32 1}
+!14 = !{i32 1, !"wchar_size", i32 4}
+; CHECK: !15 = !{i32 2, !"frame-pointer", i32 2}
+; this next line checks that nothing comes after the above check line. 
+; No more metadata should be necessary after !15, the rest should be removed.
+; CHECK-NOT: .
+!15 = !{i32 2, !"frame-pointer", i32 2}
+!16 = distinct !{!16, !17}
+!17 = !{!"llvm.loop.mustprogress"}
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:80]: The only pieces of metadata we actually need here are these two, ie
```llvm
!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}
```

We should, however, specifically check that the llvm.loop.mustprogress node is removed, ie:
```llvm
; CHECK-NOT: !{!"llvm.loop.mustprogress"}
```

**Review by bogner — COMMENTED** [review]
This looks pretty good, but the test needs to also cover the positive cases. We should show that dx.nonuniform and MD_range, for example, are *not* removed. This can probably be done in the same test file unless you think it's worthwhile to split it up.

**Comment by bob80905** [comment]
Created a new issue to improve range metadata validation here:
https://github.com/llvm/llvm-project/issues/137407

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 6]
```diff
@@ -0,0 +1,39 @@
+; RUN: opt -S --dxil-prepare %s | FileCheck %s
+
+; This test tests the whitelist inside of DxilPrepare.cpp.
+; It ensures that certain metadata nodes are removed that aren't
+; in the whitelist, and that certain nodes may remain that
+; are on the whitelist.
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:6]: I think we prefer the term allowlist these days. Also this is a bit verbose, maybe just
```
; Test that only metadata nodes that are valid in DXIL are allowed through
```

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+
+target triple = "dxilv1.0-unknown-shadermodel6.0-compute"
+
+; Function Attrs: noinline nounwind memory(readwrite, inaccessiblemem: none)
+define void @main(i32* %ptr) {
+entry:  
+  ; metadata ID changes to 0 once the current !0 and !1 are removed
+  ; since they aren't in the whitelist. range needs a payload.
+  ; CHECK: %val = load i32, ptr %ptr, align 4, !range !0
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:15]: Better to pattern match the argument and check it later:
```
CHECK: %val = load i32, ptr %ptr, align 4, !range [[RANGEMD:![0-9]+]]
...
CHECK:  [RANGEMD] = !{i32 1, i32 5}
```

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+  %val = load i32, ptr %ptr, align 4, !range !2
+
+  ; dx.nonuniform is a valid metadata node kind on the whitelist,
+  ; so give it a bogus payload and ensure it sticks around
+  ; CHECK-next: %cmp.i1.not = icmp eq i32 1, 0, !dx.nonuniform !0
+  %cmp.i1.not = icmp eq i32 1, 0, !dx.nonuniform !2
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:21]: Probably better to either get an instruction with a valid payload here or omit this one - the check that `!range` gets through probably proves that we're hitting this codepath well enough

**Review by bogner — COMMENTED** [review]
Description / commit message needs to be updated to match how this ended up, but otherwise this is looking pretty good. A couple of minor comments inline.

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+  ; metadata ID changes to 0 once the current !0 and !1 are removed
+  ; since they aren't in the whitelist. range needs a payload.
+  ; CHECK: %val = load i32, ptr %ptr, align 4, !range [[RANGEMD:![0-9]+]]
+  %val = load i32, ptr %ptr, align 4, !range !2
+
+  %cmp.i = icmp ult i32 1, 2
+  br i1 %cmp.i, label %_Z4mainDv3_j.exit, label %_Z4mainDv3_j.exit, !llvm.loop !0
+
+_Z4mainDv3_j.exit:                                ; preds = %for.body.i, %entry
+  ret void
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:19]: You can check that the loop metadata is stripped here by using a regex for the end of the line:
```suggestion
  %cmp.i = icmp ult i32 1, 2
  ; CHECK: br i1 %cmp.i, label %exit, label %exit{{$}}
  br i1 %cmp.i, label %exit, label %exit, !llvm.loop !0

exit:
  ret void

```

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+}
+
+; CHECK: [[RANGEMD]] = !{i32 1, i32 5}
+; this next check line checks that nothing comes after the above check line. 
+; No more metadata should be necessary, the rest (the current 0 and 1)
+; should be removed.
+; CHECK-NOT: !{!"llvm.loop.mustprogress"}
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:26]: `CHECK-NOT` is finicky - if `!{!"llvm.loop.mustprogress"}` prints *before* the range MD this won't fire. We need to use two check-nots, like so
```suggestion
; CHECK-NOT: !{!"llvm.loop.mustprogress"}
; CHECK: [[RANGEMD]] = !{i32 1, i32 5}
; CHECK-NOT: !{!"llvm.loop.mustprogress"}
```

File: llvm/lib/Target/DirectX/DXILPrepare.cpp [hunk 11]
```diff
@@ -176,6 +185,9 @@ class DXILPrepareModule : public ModulePass {
     VersionTuple ValVer = MetadataInfo.ValidatorVersion;
     bool SkipValidation = ValVer.getMajor() == 0 && ValVer.getMinor() == 0;
 
+    // construct whitelist of valid metadata node kinds
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILPrepare.cpp:188]:
```suggestion
    // construct allowlist of valid metadata node kinds
```

File: llvm/test/CodeGen/DirectX/metadata-stripping.ll [hunk 12]
```diff
@@ -0,0 +1,29 @@
...
+
+; Test that only metadata nodes that are valid in DXIL are allowed through
+
+target triple = "dxilv1.0-unknown-shadermodel6.0-compute"
+
+; Function Attrs: noinline nounwind memory(readwrite, inaccessiblemem: none)
+define void @main(i32* %ptr) {
+entry:  
+  ; metadata ID changes to 0 once the current !0 and !1 are removed
+  ; since they aren't in the whitelist. range needs a payload.
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/metadata-stripping.ll:11]:
```suggestion
  ; since they aren't in the allowlist. range needs a payload.

```

**Review by bogner — APPROVED** [review]
Looks good

File: llvm/lib/Target/DirectX/DXILPrepare.cpp [hunk 13]
```diff
@@ -189,6 +201,9 @@ class DXILPrepareModule : public ModulePass {
       for (auto &BB : F) {
         IRBuilder<> Builder(&BB);
         for (auto &I : make_early_inc_range(BB)) {
+
+          I.dropUnknownNonDebugMetadata(DXILCompatibleMDs);
+
           if (I.getOpcode() == Instruction::FNeg) {
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILPrepare.cpp:207]: DXILPrepare has a bunch of overlap with the legalization pass. Seems like MetaData might not be able to move because legalization is a function level pass and this is a module level one, but at a minimum it seems like FNeg -> FSub should move.

Comment (bogner) [reply llvm/lib/Target/DirectX/DXILPrepare.cpp:207]: I agree. I think DXILPrepare should do things like translate attributes and metadata, insert no-op bitcasts to appease the bitcode writer, and that sort of thing. Replacing ops with their equivalents should squarely be a part of legalization, not here.

I've filed https://github.com/llvm/llvm-project/issues/137685

**Review by farzonl — APPROVED** [review]
