### PR TITLE
[InstCombine] Limit canonicalization of extractelement(cast) to constant index or same basic block.

### LINKED ISSUE #165793: [InstCombine] Vector fptosi moved inside loop and scalarized
For the following IR, where the fp-to-int conversion is a vector operation:

```llvm
%33 = call <4 x float> @llvm.x86.sse41.round.ps(<4 x float> %26, i32 9)
%34 = fptosi <4 x float> %33 to <4 x i32>
br label %35

35:
  %36 = phi i32 [0, %10], [ %59, %58]
  %37 = icmp samesign ult i32 %36, 4
  br i1 %37, label %38, label %60

38:
  %40 = extractelement <4 x i32> %34, i32 %36
```
After running the InstCombine pass, the conversion becomes scalarized and moved inside the loop:

```llvm
%30 = call <4 x float> @llvm.x86.sse41.round.ps(<4 x float> %26, i32 9)
br label %31

31:
  %32 = phi i32 [0, %10], [ %59, %58]
  %33 = icmp samesign ult i32 %32, 4
  br i1 %33, label %34, label %60

34:
  %37 = extractelement <4 x float> %30, i32 %32
  %38 = fptosi float %37 to i32
```
This transformation appears incorrect, since it changes a vector fp-to-int conversion into a scalar one and moves it inside the loop.

I will prepare a baseline test that reproduces the issue, along with a proposal for a bug fix.

### PR DESCRIPTION
**Pull request by azwolski**
The current canonicalization of extractelement(cast) requires that the CastInst has only one use. However, when that use occurs inside a loop, it still satisfies this condition, even though the cast is effectively used multiple times, once per iteration, rather than truly being used once.

```cpp
} else if (auto *CI = dyn_cast<CastInst>(I)) {
  // Canonicalize extractelement(cast) -> cast(extractelement).
  // Bitcasts can change the number of vector elements, and they cost
  // nothing.
  if (CI->hasOneUse() && (CI->getOpcode() != Instruction::BitCast)){
 ```
Before
```llvm
%34 = fptosi <4 x float> %33 to <4 x i32>
;/loop{
%40 = extractelement <4 x i32> %34, i32 %36
```
 
  After
 ```llvm
 ;/loop{
 %37 = extractelement <4 x float> %30, i32 %32
 %38 = fptosi float %37 to i32
  ```

After canonicalization, for this particular example, it no longer uses a single instruction to cast the entire vector at once, but instead performs the cast for every element separately, which is less performant.

Ideally, we would like to check if the cast instruction **has one use and that this use is not called inside a loop**. However, InstCombine/InstCombineVectorOps.cpp does not provide utilities like `LoopInfo` to check that. It might be possible to approximate this by analyzing basic block successors or by building a dominance tree, but that may be a costly solution.

A solution to prevent this optimization could be to check if the index is an immediate value and if the use is inside the same basic block as the cast instruction:
```cpp
if (CI->hasOneUse() && (CI->getOpcode() != Instruction::BitCast)) {
    Instruction *U = cast<Instruction>(*CI->user_begin());
    if (U->getParent() == CI->getParent() || isa<ConstantInt>(Index)){
```

Fix: https://github.com/llvm/llvm-project/issues/165793

### CODE REVIEW

**Comment by azwolski** [comment]
@nikic

**Review by RKSimon — APPROVED** [review]
LGTM - but I think we'd be better off looking at moving this to VectorCombine at some point soon to allow it be cost driven. Also, FTR bitcasts aren't always free - fp<->int bitcasts (fp bit twiddling etc.) in particular can be a major headache.

File: llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp [hunk 1]
```diff
@@ -588,7 +588,8 @@ Instruction *InstCombinerImpl::visitExtractElementInst(ExtractElementInst &EI) {
       // Canonicalize extractelement(cast) -> cast(extractelement).
       // Bitcasts can change the number of vector elements, and they cost
       // nothing.
-      if (CI->hasOneUse() && (CI->getOpcode() != Instruction::BitCast)) {
+      if (CI->hasOneUse() && (CI->getOpcode() != Instruction::BitCast) &&
+          (EI.getParent() == CI->getParent() || isa<ConstantInt>(Index))) {
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp]: Add a comment for why this limitation exists?

**Comment by nikic** [comment]
Usually the way we handle transforms that may be non-profitable due to code motion into loops is via an undo transform in LICM (which intentionally has a late, post-InstCombine run scheduled). We could add a "LICM with reassociation" transform that converts extractelement + fptosi to fptosi + extractelement if this allows the fptosi to be LICMed. With the usual benefit that it will also fix the problem if the IR was originally in this form, rather than introduced by InstCombine. However, as that creates a vector op from a scalar op that would probably need cost modelling as well, which we don't usually do in LICM.

I think overall this is fine for now, we can try to do better if this causes regressions or something.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by RKSimon** [comment]
> ping

@azwolski  are you waiting on a review or merge?

**Comment by aneshlya** [comment]
On merge
