### PR TITLE
[HLSL] Fix Root signature test error

### LINKED ISSUE #127260: [Bug] Investigate and fix error with multiple root signature test
Our CI tests fail on test `RootSignature-MultipleEntryFunctions.ll`, need to investigate and fix it.

### PR DESCRIPTION
**Pull request by joaosaffran**
Fixing error detected in build bot in file `RootSignature-MultipleEntryFunctions.ll`

closes: [127260](https://github.com/llvm/llvm-project/issues/127260)

### CODE REVIEW

**Comment by bogner** [comment]
I don't think this is correct. It looks to me like this is printing the root signature flags in a non-deterministic order.

 The problem is that we're iterating over a map in RootSignatureAnalysisPrinter - this isn't guaranteed any particular order. Instead, we should iterate over the functions in the module and look them up in the map.

File: llvm/lib/Target/DirectX/DXILRootSignature.cpp [hunk 1]
```diff
@@ -186,9 +186,9 @@ PreservedAnalyses RootSignatureAnalysisPrinter::run(Module &M,
   OS << "Root Signature Definitions"
      << "\n";
   uint8_t Space = 0;
-  for (const auto &P : RSDMap) {
-    const auto &[Function, RSD] = P;
-    OS << "Definition for '" << Function->getName() << "':\n";
+  for (const auto &F : M) {
+    const auto RSD = RSDMap.at(&F);
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILRootSignature.cpp:190]: This will crash if there are functions in the module without root signatures (ie, if the root signature metadata isn't present, or if there are helper functions without their own root signatures)

File: llvm/lib/Target/DirectX/DXILRootSignature.cpp [hunk 2]
```diff
@@ -155,6 +155,7 @@ analyzeModule(Module &M) {
 
     if (RootElementListNode == nullptr) {
       reportError(Ctx, "Missing Root Element List Metadata node.");
+      continue;
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILRootSignature.cpp:158]: Better to fix this in a separate PR (also are there any tests for this error? I'm surprised they don't crash or otherwise have issues)

File: llvm/lib/Target/DirectX/DXILRootSignature.cpp [hunk 3]
```diff
@@ -186,20 +187,23 @@ PreservedAnalyses RootSignatureAnalysisPrinter::run(Module &M,
   OS << "Root Signature Definitions"
      << "\n";
   uint8_t Space = 0;
-  for (const auto &P : RSDMap) {
-    const auto &[Function, RSD] = P;
-    OS << "Definition for '" << Function->getName() << "':\n";
+  for (const auto &F : M) {
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILRootSignature.cpp:190]: Better style to spell out the type if it doesn't show up elsewhere (such as in a cast).
```suggestion
  for (const Function &F : M) {
```

File: llvm/lib/Target/DirectX/DXILRootSignature.cpp [hunk 4]
```diff
@@ -186,20 +187,23 @@ PreservedAnalyses RootSignatureAnalysisPrinter::run(Module &M,
...
+    const auto &RSD = RSDMap.find(&F);
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILRootSignature.cpp:191]: The type here is `SmallDenseMap<const Function *, mcdxbc::RootSignatureDesc>::iterator` - since this is actually a copy we shouldn't use a const reference here.
```suggestion
    auto It = RSDMap.find(&F);
```

File: llvm/lib/Target/DirectX/DXILRootSignature.cpp (hunk 2 above)
Comment (joaosaffran) [reply llvm/lib/Target/DirectX/DXILRootSignature.cpp]: There was a test for this at some point in time, might get lost during one of the iterations from the original PR. Will make a new one with this fix, a test and I will double-check the current tests.

**Review by bogner — APPROVED** [review]
