### PR TITLE
[clang][analyzer] Fix crash in loop unrolling

### LINKED ISSUE #68819: [clang][StaticAnalyzer] Crash on loop unrolling mode
[godbolt](https://godbolt.org/z/vv7EfMsd1)
```c
// test.c
// unroll-loops=true

void test_escaping_on_var_before_switch_case_no_crash(int c) {
  switch (c) {
    int i;
  case 0: {
    for (i = 0; i < 16; i++) {}
    break;
  }
  }
}
```
crash dump:
```c
Reached root without finding the declaration of VD
UNREACHABLE executed at /home/xxxxx/Sources/llvm-project-main/clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:248!
```

### PR DESCRIPTION
**Pull request by huang-me**
StaticAnalyzer didn't check if the variable is declared in `CompoundStmt` under `SwitchStmt`, which make static analyzer reach root without finding the declaration.

Fixes #68819

### CODE REVIEW

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp [hunk 1]
```diff
@@ -226,6 +226,17 @@ static bool isPossiblyEscaped(ExplodedNode *N, const DeclRefExpr *DR) {
           return false;
       }
     }
+
+    if (const SwitchStmt *SS = dyn_cast<SwitchStmt>(S)) {
+      for (const Stmt *CB : dyn_cast<CompoundStmt>(SS->getBody())->body()) {
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:231]: Be careful, this may cause a crash in standard-compliant but unusual code where the body of a `switch` statement is *not* a compound statement.

For example code like
```
switch (get_value()) case 0: case 1: run_foobar();
```
is completely valid; and here the body of the switch statement is a `CaseStmt` (which has another case statement as a child).

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp [hunk 2]
```diff
@@ -226,6 +226,17 @@ static bool isPossiblyEscaped(ExplodedNode *N, const DeclRefExpr *DR) {
...
+        for (const Decl *D : dyn_cast<DeclStmt>(CB)->decls()) {
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:232]: And this will crash on all statements that are within a switch and not `DeclStmt`s (because the `dyn_cast` returns a nullpointer and you're calling a method on it).

**Review by NagyDonat — CHANGES_REQUESTED** [review]

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp (hunk 1 above)
Comment (huang-me) [reply clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:231]: I didn't think of this scenario, thanks for reminding me.

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp (hunk 2 above)
Comment (huang-me) [reply clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:232]: Oh, that's a stupid mistake. Thanks again.

**Comment by NagyDonat** [comment]
If I understand it correctly, your change doesn't handle declarations that are in inner statements, e.g. the variable "x" in the following code:
```cpp
switch (get_value()) {
case 42:
  do {
    int x;
    // ...
  } while (running);
//...
}
```
Is this compatible with the goals of your commit, or would the original crash remain in a situation like this?

**Comment by huang-me** [comment]
> If I understand it correctly, your change doesn't handle declarations that are in inner statements, e.g. the variable "x" in the following code:
> 
> ```c++
> switch (get_value()) {
> case 42:
>   do {
>     int x;
>     // ...
>   } while (running);
> //...
> }
> ```
> 
> Is this compatible with the goals of your commit, or would the original crash remain in a situation like this?

As far as I understand it, the declaration within the `CaseStmt` would be found before reaching `SwitchStmt` so I don't think we need to consider this situation.

**Comment by NagyDonat** [comment]
That sounds reasonable. Unfortunately I don't know much about the context of this change, so let's wait for a review from @danix800 (or somebody else who's knows enough) before merging this change.

Also, perhaps it would be a good idea to add a testcase (or a few of them) in the directory `clang/test/Analysis` to prevent regressions and illustrate the goals of this change. (As far as I know our test system is just a heap of random C/C++ files with a "how to compile/analyze this" header and "what warnings/errors should appear" markers in comments. I usually add testcases by following the example of older analogous cases.)

**Comment by huang-me** [comment]
I've added the test case to illustrate the goal of this change.

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp [hunk 3]
```diff
@@ -226,6 +226,21 @@ static bool isPossiblyEscaped(ExplodedNode *N, const DeclRefExpr *DR) {
...
+    if (const SwitchStmt *SS = dyn_cast<SwitchStmt>(S)) {
+      if (const CompoundStmt *CST = dyn_cast<CompoundStmt>(SS->getBody())) {
+        for (const Stmt *CB : CST->body()) {
+          if (const DeclStmt *DST = dyn_cast<DeclStmt>(CB)) {
+            for (const Decl *D : DST->decls()) {
+              // Once we reach the declaration of the VD we can return.
+              if (D->getCanonicalDecl() == VD)
+                return false;
+            }
+          }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:239]: This is duplicated from the previous check. Consider refactoring the code to hoist and name the common functionality.

File: clang/test/Analysis/test-escaping-on-var-before-switch-case.c [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+void test_escaping_on_var_before_switch_case_no_crash(int c) {
+  switch (c) {
+    int i; // expected error{{Reached root without finding the declaration of VD}}
+    case 0: {
+      for (i = 0; i < 16; i++) {}
+      break;
+    }
+  }
+}
```
Comment (steakhal) [inline clang/test/Analysis/test-escaping-on-var-before-switch-case.c:11]: It took me some time to realize that its not a verify expectation.
BTW in this shape, this test fails.

```suggestion
// RUN: %clang_analyze_cc1 -analyzer-checker=core -analyzer-config unroll-loops=true -verify %s
// expected-no-diagnostics

void test_escaping_on_var_before_switch_case_no_crash(int c) {
  // https://github.com/llvm/llvm-project/issues/68819
  switch (c) {
    int i; // no-crash: The declaration of `i` is found here.
    case 0: {
      for (i = 0; i < 16; i++) {}
      break;
    }
  }
}
```

I'd also suggest to rename the test file to highlight that this is only for loop unrolling. Or maybe even better, just append this to the end of `clang/test/Analysis/loop-unrolling.cpp`.

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp [hunk 5]
```diff
@@ -226,6 +226,21 @@ static bool isPossiblyEscaped(ExplodedNode *N, const DeclRefExpr *DR) {
           return false;
       }
     }
+
+    if (const SwitchStmt *SS = dyn_cast<SwitchStmt>(S)) {
+      if (const CompoundStmt *CST = dyn_cast<CompoundStmt>(SS->getBody())) {
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp:231]:
```suggestion
    if (const auto *SS = dyn_cast<SwitchStmt>(S)) {
      if (const auto *CST = dyn_cast<CompoundStmt>(SS->getBody())) {
```

The type is already mentioned on the line.

**Review by steakhal — CHANGES_REQUESTED** [review]
Thanks for working on this.
I think iterating the direct child nodes of the switch is fine. I can't think of a better way.

File: clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp (hunk 3 above)
Comment (huang-me) [reply clang/lib/StaticAnalyzer/Core/LoopUnrolling.cpp]: Sure, I can do that.

**Review by steakhal — APPROVED** [review]
LGTM

EDIT: Sorry for my late reply.

File: clang/test/Analysis/loop-unrolling.cpp [hunk 6]
```diff
@@ -1,5 +1,7 @@
 // RUN: %clang_analyze_cc1 -analyzer-checker=core,debug.ExprInspection -analyzer-config unroll-loops=true,cfg-loopexit=true -verify -std=c++14 -analyzer-config exploration_strategy=unexplored_first_queue %s
 // RUN: %clang_analyze_cc1 -analyzer-checker=core,debug.ExprInspection -analyzer-config unroll-loops=true,cfg-loopexit=true,exploration_strategy=dfs -verify -std=c++14 -DDFS=1 %s
+// RUN: %clang_analyze_cc1 -analyzer-checker=core -analyzer-config unroll-loops=true -verify %s
+// expected-no-diagnostics
```
Comment (steakhal) [inline clang/test/Analysis/loop-unrolling.cpp:4]:
```suggestion
```
