### PR TITLE
[analyzer] Fix StackAddrEscapeChecker crash on temporary object fields

### LINKED ISSUE #66221: [static analyser][StackAddrEscapeChecker] crash with std::function capturing a dangling reference
When trying to analyze the following code with clang-tidy, I get a crash:

```cpp
//minimal.cpp
#include <functional>

auto f() -> std::function<int()> {
  int v;
  auto c = [&v]() {
    return v;
  };
  return c;
}

auto main() -> int { return f()(); }
```

The function `f` returns a `std::function` wrapping a lambda with a dangling reference in its capture. The crash doesn't happen if I return a lambda instead of a `std::function`, nor if I capture by value.

Command
```bash
clang-tidy-16 minimal.cpp -- -std=c++20
```

Crash report:

```text
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-tidy-16 minimal.cpp -- -std=c++23
1.      <eof> parser at end of file
2.      While analyzing stack: 
        #0 Calling f() at line 12
        #1 Calling main()
#0 0x00007fd657365796 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfc9796)
#1 0x00007fd6573639e0 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfc79e0)
#2 0x00007fd657365f6b (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfc9f6b)
#3 0x00007fd655ed5fd0 (/lib/x86_64-linux-gnu/libc.so.6+0x3bfd0)
#4 0x00007fd656387c50 vtable for __cxxabiv1::__si_class_type_info (/lib/x86_64-linux-gnu/libstdc++.so.6+0x20bc50)
Segmentation fault (core dumped)
```

```bash
$ clang-tidy-16 --version
Debian LLVM version 16.0.6
  Optimized build.
```

But the crash happens with clang-tidy 16, 17, 18, as well as the system 14.0.6 (inside a debian:latest docker) and the system 15.0.7 (on a Ubuntu 23.04 machine).

### PR DESCRIPTION
**Pull request by steakhal**
Basically, the issue was that we should have unwrap the base region before we special handle temp object regions.

Fixes https://github.com/llvm/llvm-project/issues/66221

I also decided to add some extra range information to the diagnostics to make it consistent with the other reporting path.

### CODE REVIEW

File: clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp [hunk 1]
```diff
@@ -398,7 +400,7 @@ void StackAddrEscapeChecker::checkEndFunction(const ReturnStmt *RS,
     }(Referrer->getMemorySpace());
 
     // This cast supposed to succeed.
```
Comment (DonatNagyE) [inline clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp:402]: Perhaps explain why will the cast succeed (or, alternatively, just remove this meaningless comment).

**Review by NagyDonat — APPROVED** [review]
Nice bugfix; I have only one tangential remark.

File: clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp (hunk 1 above)
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp:402]: I was thinking about it once you raised this comment.
To me, to have a proper diagnostic we need something that we can name here; and they are usually variables.

Now, if we check and bail out if it's not a VarRegion, we would not get notified if we suddenly have some other value that we could cover but we don't. It took a long time to even hit this crash, so I don't think they are too frequent.

So the question is which we prefer:
 - Crash (possible in the long future) to get notified or
 - Silently ignore these unthought, interesting cases for which we didn't account for
 
 If this would be a mission-critical software I'd vote for (2), but now I'm a bit hesitant in between the two options.
 
 Maybe, given that this is a core checker, we should lean towards gracefully handling this. WDYT?

Comment (DonatNagyE) [reply clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp:402]: I think the best would be either a comment that explains _why_ we expect a `VarRegion` here (e.g. it's already checked in function `fooBar()` etc.) or if possible, then a crash-less logic (converting an earlier `isa`-like check + this `cast` into a single `getAs`).

I don't think that we should add defensive/paranoid checks; if this logic is broken by some change in the distant future, then a fixable crash is better than silent degradation.

Comment (steakhal) [reply clang/lib/StaticAnalyzer/Checkers/StackAddrEscapeChecker.cpp:402]: > I think the best would be either a comment that explains _why_ we expect a `VarRegion` here (e.g. it's already checked in function `fooBar()` etc.) or if possible, then a crash-less logic (converting an earlier `isa`-like check + this `cast` into a single `getAs`).

There is nothing that would directly imply this.
It's like, ATM I don't know of any other situations where it could be not a `VarRegion`, and so far it didn't appear in practice that would disprove this.

I'm not exactly sure if a comment like that would suffice. Would you accept it? And do you think it's necessary?

Another alternative could be a combination:

```c++
if (!isa<VarRegion>(Referrer)) {
  assert(false && "We should really only have VarRegions here");
  continue;
}
// ...
cast<VarRegion>(Referrer)...
```

**Review by Xazax-hun — APPROVED** [review]

**Comment by steakhal** [comment]
Let me know if you are still okay with the latest change. @DonatNagyE @Xazax-hun

**Comment by DonatNagyE** [comment]
LGTM.

**Review by Xazax-hun — APPROVED** [review]

**Comment by steakhal** [comment]
Fixed tests for Windows, to use `size_t` for operator new.
I'll land this if premerge-tests pass.
