### PR TITLE
[HLSL] implement elementwise firstbithigh hlsl builtin

### LINKED ISSUE #99115: Implement the `firstbithigh` HLSL Function
- [ ] Implement `firstbithigh` clang builtin,
- [ ] Link `firstbithigh` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `firstbithigh` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `firstbithigh` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/firstbithigh.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/firstbithigh-errors.hlsl`
- [ ] Create the `int_dx_firstbithigh` intrinsic in `IntrinsicsDirectX.td`
- [ ] Create the `DXILOpMapping` of `int_dx_firstbithigh` to  `34` in `DXIL.td`
- [ ] Create the  `firstbithigh.ll` and `firstbithigh_errors.ll` tests in `llvm/test/CodeGen/DirectX/`
- [ ] Create the `int_spv_firstbithigh` intrinsic in `IntrinsicsSPIRV.td`
- [ ] In SPIRVInstructionSelector.cpp create the `firstbithigh` lowering and map  it to `int_spv_firstbithigh` in `SPIRVInstructionSelector::selectIntrinsic`.
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll`

## DirectX

| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages |
| ----------- | ----------- | ------------ | ------------- |
| 34 | FirstbitSHi | 6.0 | () |

## SPIR-V

# FindSMsb:

## Description:
**FindSMsb**  
  
Signed-integer most-significant bit, with *Value* interpreted as a
signed integer.  
  
For positive numbers, the result will be the bit number of the most
significant 1-bit. For negative numbers, the result will be the bit
number of the most significant 0-bit. For a *Value* of 0 or -1, the
result is -1.  
  
*Result Type* and the type of *Value* must both be integer scalar or
integer vector types. *Result Type* and operand types must have the same
number of components with the same component width. Results are computed
per component.  
  
This instruction is currently limited to 32-bit width components.

<table>
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr>
<th>Number</th>
<th>Operand 1</th>
<th>Operand 2</th>
<th>Operand 3</th>
<th>Operand 4</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>74</p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Value</em></p></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc firstbithigh_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(int4 p1) {
    return firstbithigh(p1);
}
```
## HLSL:

Gets the location of the first set bit starting from the highest order bit and working downward, per component.

## Syntax

``` syntax
int firstbithigh(
  in int value
);
```

## Parameters

<dl> <dt>

*value* \[in\]
</dt> <dd>

Type: **[**int**](/windows/desktop/WinProg/windows-data-types)**

The input value.

</dd> </dl>

## Return value

Type: **[**int**](/windows/desktop/WinProg/windows-data-types)**

The location of the first set bit.

## Remarks

For a signed integer, the first significant bit is zero for a negative number.

The following overloaded versions are also available:

``` syntax
int2 firstbithigh(int2 value);
int3 firstbithigh(int3 value);
int4 firstbithigh(int4 value);
uint firstbithigh(uint value);
uint2 firstbithigh(uint2 value);
uint3 firstbithigh(uint3 value);
uint4 firstbithigh(uint4 value);
```

### Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                                | Supported |
|-----------------------------------------------------------------------------|-----------|
| [Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md) and higher shader models | yes       |

 

This function is supported in the following types of shaders:

| Vertex | Hull | Domain | Geometry | Pixel | Compute |
|--------|------|--------|----------|-------|---------|
| x      | x    | x      | x        | x     | x       |

 

## See also

<dl> <dt>

[Intrinsic Functions](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> <dt>

[Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md)
</dt> </dl>

### LINKED ISSUE #113486: [HLSL][SPIRV] Bug in SPIRVGlobalRegistry::getOrCreateCompositeOrNull
Register type of register created by 'SPIRVGlobalRegistry::getOrCreateCompositeOrNull' is hardcoded to be 'iID' which is wrong. It should use the register class of the spirv type it is creating a register for.

### PR DESCRIPTION
**Pull request by spall**
Implements elementwise firstbithigh hlsl builtin.
Implements firstbituhigh intrinsic for spirv and directx, which handles unsigned integers
Implements firstbitshigh intrinsic for spirv and directx, which handles signed integers.
Fixes #113486
Closes #99115

### CODE REVIEW

File: clang/lib/CodeGen/CGBuiltin.cpp [hunk 1]
```diff
@@ -18631,6 +18631,14 @@ static Intrinsic::ID getDotProductIntrinsic(CGHLSLRuntime &RT, QualType QT) {
   return RT.getUDotIntrinsic();
 }
 
+Intrinsic::ID getFirstBitHighIntrinsic(CGHLSLRuntime &RT, QualType QT) {
+  if (QT->hasSignedIntegerRepresentation()) {
+    return RT.getFirstBitSHighIntrinsic();
+  }
+
```
Comment (farzonl) [inline clang/lib/CodeGen/CGBuiltin.cpp:18638]:
```suggestion

  assert(QT->hasUnsignedIntegerRepresentation());
```

File: clang/lib/Headers/hlsl/hlsl_intrinsics.h [hunk 2]
```diff
@@ -928,6 +928,78 @@ float3 exp2(float3);
...
+// firstbithigh builtins
+//===----------------------------------------------------------------------===//
+
+/// \fn T firstbithigh(T Val)
+/// \brief Returns the location of the first set bit starting from the highest
+/// order bit and working downward, per component.
+/// \param Val the input value.
+
+#ifdef __HLSL_ENABLE_16_BIT
+_HLSL_AVAILABILITY(shadermodel, 6.2)
```
Comment (farzonl) [inline clang/lib/Headers/hlsl/hlsl_intrinsics.h:941]: I don't think the int16_t, uint16_t, int64_t, and uint64_t cases are correct.

File: clang/lib/Sema/SemaHLSL.cpp [hunk 3]
```diff
@@ -1874,6 +1874,24 @@ bool SemaHLSL::CheckBuiltinFunctionCall(unsigned BuiltinID, CallExpr *TheCall) {
...
+    QualType ArgTy = Arg->getType();
+    QualType EltTy = ArgTy;
+
+    if (auto *VecTy = EltTy->getAs<VectorType>())
+      EltTy = VecTy->getElementType();
+
+    if (!EltTy->isIntegerType()) {
+      Diag(Arg->getBeginLoc(), diag::err_builtin_invalid_arg_type)
+          << 1 << /* integer ty */ 6 << ArgTy;
+      return true;
```
Comment (farzonl) [inline clang/lib/Sema/SemaHLSL.cpp:1891]: You should set the call type.  If ArgTy is a 32 bit int then `TheCall->setType(ArgTy);`

File: llvm/include/llvm/IR/IntrinsicsDirectX.td [hunk 4]
```diff
@@ -86,4 +86,6 @@ def int_dx_rsqrt  : DefaultAttrsIntrinsic<[llvm_anyfloat_ty], [LLVMMatchType<0>]
 def int_dx_wave_is_first_lane : DefaultAttrsIntrinsic<[llvm_i1_ty], [], [IntrConvergent]>;
 def int_dx_sign : DefaultAttrsIntrinsic<[LLVMScalarOrSameVectorWidth<0, llvm_i32_ty>], [llvm_any_ty], [IntrNoMem]>;
 def int_dx_step : DefaultAttrsIntrinsic<[LLVMMatchType<0>], [llvm_anyfloat_ty, LLVMMatchType<0>], [IntrNoMem]>;
+def int_dx_firstbituhigh : DefaultAttrsIntrinsic<[llvm_anyint_ty], [LLVMMatchType<0>], [IntrNoMem]>;
```
Comment (farzonl) [inline llvm/include/llvm/IR/IntrinsicsDirectX.td:89]:
```suggestion
def int_dx_firstbituhigh : DefaultAttrsIntrinsic<[LLVMScalarOrSameVectorWidth<0, llvm_i32_ty>], [llvm_anyint_ty], [IntrNoMem]>;
```

File: llvm/include/llvm/IR/IntrinsicsSPIRV.td [hunk 5]
```diff
@@ -84,4 +84,6 @@ let TargetPrefix = "spv" in {
     [IntrNoMem, Commutative] >;
   def int_spv_wave_is_first_lane : DefaultAttrsIntrinsic<[llvm_i1_ty], [], [IntrConvergent]>;
   def int_spv_sign : DefaultAttrsIntrinsic<[LLVMScalarOrSameVectorWidth<0, llvm_i32_ty>], [llvm_any_ty], [IntrNoMem]>;
+  def int_spv_firstbituhigh : DefaultAttrsIntrinsic<[llvm_anyint_ty], [LLVMMatchType<0>], [IntrNoMem]>;
```
Comment (farzonl) [inline llvm/include/llvm/IR/IntrinsicsSPIRV.td:87]:
```suggestion
  def int_spv_firstbituhigh : DefaultAttrsIntrinsic<[LLVMScalarOrSameVectorWidth<0, llvm_i32_ty>], [llvm_anyint_ty], [IntrNoMem]>;
```

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 6]
```diff
@@ -2515,6 +2525,10 @@ bool SPIRVInstructionSelector::selectIntrinsic(Register ResVReg,
     return selectExtInst(ResVReg, ResType, I, CL::rsqrt, GL::InverseSqrt);
   case Intrinsic::spv_sign:
     return selectSign(ResVReg, ResType, I);
+  case Intrinsic::spv_firstbituhigh:
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2528]: Maybe add a comment saying we are only setting the GL extension because there is no CL equivalent.

File: llvm/test/CodeGen/DirectX/firstbithigh.ll [hunk 7]
```diff
@@ -0,0 +1,91 @@
+; RUN: opt -S -scalarizer -dxil-op-lower -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s
+
+; Make sure dxil operation function calls for firstbithigh are generated for all integer types.
+
+define noundef i16 @test_firstbithigh_ushort(i16 noundef %a) {
+entry:
+; CHECK: call i16 @dx.op.unary.i16(i32 33, i16 %{{.*}})
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/firstbithigh.ll:7]: In DXC the call return value is always i32. I don't know if this would pass the verifier and if it did, I don't know that it would run correctly in the DirectX runtime.

File: llvm/lib/Target/DirectX/DXIL.td [hunk 8]
```diff
@@ -564,6 +564,30 @@ def CBits :  DXILOp<31, unary> {
...
+  let Doc = "Returns the location of the first set bit from "
+            "the highest order bit based on the sign.";
+  let LLVMIntrinsic = int_dx_firstbitshigh;
+  let arguments = [OverloadTy];
+  let result = OverloadTy;
+  let overloads =
+      [Overloads<DXIL1_0, [Int16Ty, Int32Ty, Int64Ty]>];
+  let stages = [Stages<DXIL1_0, [all_stages]>];
+  let attributes = [Attributes<DXIL1_0, [ReadNone]>];
+}
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXIL.td:589]: A few things here:
1. Please name these with the full names of the dxil ops, `FirstbitHi` and `FirstbitSHi`
2. These need to use `unaryBits` for the `OpClass`, not `unary`
3. [The result type should be i32](https://github.com/microsoft/DirectXShaderCompiler/blob/release-1.8.2407/utils/hct/hctdb.py#L1410), not `OverloadTy`

I'll also that this overload set does match dxc, as indicated by ["wil"](https://github.com/microsoft/DirectXShaderCompiler/blob/release-1.8.2407/utils/hct/hctdb.py#L1407) in hctdb.py, but I'm not entirely convinced that dxc does the right thing for i16 or i64. For instance, in https://hlsl.godbolt.org/z/cE1sahjKa there's no way that could return a meaningful result. That said, it's probably fine to allow i16 and i64 match dxc, as least for now.

File: llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll [hunk 9]
```diff
@@ -0,0 +1,37 @@
+; RUN: llc -verify-machineinstrs -O0 -mtriple=spirv-unknown-unknown %s -o - | FileCheck %s
+; RUN: %if spirv-tools %{ llc -O0 -mtriple=spirv-unknown-unknown %s -o - -filetype=obj | spirv-val %}
```
Comment (farzonl) [inline llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:2]: Do you have spirv-tools installed?

There is an error in DXCs SPIRV backend
`error: firstbithigh is currently limited to 32-bit width components when targetting SPIR-V`

That makes me think there might be a problem with non 32 bit width values that you use in this test. short of running the shader I don't know how to confirm. Maybe someone with more knowledge could weigh in.

File: clang/lib/Headers/hlsl/hlsl_intrinsics.h (hunk 2 above)
Comment (bogner) [reply clang/lib/Headers/hlsl/hlsl_intrinsics.h]: To be clear, I believe we should *have* these cases, but the return types should always be `uint32_t` or vectors thereof

File: llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll (hunk 9 above)
Comment (spall) [reply llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:2]: I removed the non-32 bit tests, except error tests, since it only supports 32 bit integers.

Comment (farzonl) [reply llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:2]: I dunno if you have to remove the tests i think the return type of those tests were the problem.

Comment (s-perron) [reply llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:2]: If you look at FindSMsb and FindUMsb in https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html, it says:

> This instruction is currently limited to 32-bit width components.

For DXC, we opted to just not implement the 64-bit version. We can choose to do something different in Clang. See https://github.com/microsoft/DirectXShaderCompiler/issues/4702 for that discussion.

This is an issue for 16-bit values as well.

File: llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+entry:
+; CHECK: %[[#]] = OpExtInst %[[#]] %[[#]] FindUMsb %[[#]]
+  %elt.firstbituhigh = call i32 @llvm.spv.firstbituhigh.i32(i32 %a)
+  ret i32 %elt.firstbituhigh
+}
+
+define noundef i16 @firstbituhigh_i16(i16 noundef %a) {
+entry:
+; CHECK: %[[#]] = OpExtInst %[[#]] %[[#]] FindUMsb %[[#]]
+  %elt.firstbituhigh = call i16 @llvm.spv.firstbituhigh.i16(i16 %a)
```
Comment (s-perron) [inline llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll]: If this is just passing in `%a` direcectly, is not valid spir-v. If we want to implement this for 16-bit types, we will need to zero-extend the value to 32-bits, and then use FindUMsb. The same for all types smaller than 32-bit.

Comment (spall) [reply llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll]: this was removed since only 32 bit is supported.

**Comment by bogner** [comment]
It is not correct to limit firstbithigh to 32 bit integers. There are a couple of reasons that might make one think that it is, but we do in fact want/need to support int16 and int64 here.

1. The [HLSL docs](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh) only mention integer. Unfortunately that's true for most of these functions, as many of these docs were not updated as 64 and 16 bit types gained support in the language.
2. DXC's SPIR-V implementation doesn't handle 16- and 64-bit for these functions. As noted in microsoft/DirectXShaderCompiler#4702 we decided not to implement those overloads in DXC, but should reconsider this for clang.

Despite all of this, DXC does indeed support 16- and 64-bit overloads, as seen here: https://hlsl.godbolt.org/z/qbc17xz35

Note that the return type of the operation is not overloaded - all of the overloads of this function return uint.

**Comment by spall** [comment]
> It is not correct to limit firstbithigh to 32 bit integers. There are a couple of reasons that might make one think that it is, but we do in fact want/need to support int16 and int64 here.
> 
>     1. The [HLSL docs](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh) only mention integer. Unfortunately that's true for most of these functions, as many of these docs were not updated as 64 and 16 bit types gained support in the language.
> 
If you click through the definition of Int it defines it to be 32 bits.
>     2. DXC's SPIR-V implementation doesn't handle 16- and 64-bit for these functions. As noted in [Incorrect SPIR-V generated when `firstbithigh` is used on a `uint64_t` microsoft/DirectXShaderCompiler#4702](https://github.com/microsoft/DirectXShaderCompiler/issues/4702) we decided not to implement those overloads in DXC, but should reconsider this for clang.
> 
> 
> Despite all of this, DXC does indeed support 16- and 64-bit overloads, as seen here: https://hlsl.godbolt.org/z/qbc17xz35
> 
> Note that the return type of the operation is not overloaded - all of the overloads of this function return uint.

https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#firstbithi
FirstBitHi does explicitly mention only 32 bit integers.

File: clang/lib/Sema/SemaHLSL.cpp [hunk 11]
```diff
@@ -1874,6 +1874,26 @@ bool SemaHLSL::CheckBuiltinFunctionCall(unsigned BuiltinID, CallExpr *TheCall) {
...
+    if (auto *VecTy = EltTy->getAs<VectorType>())
+      EltTy = VecTy->getElementType();
+
+    if (!EltTy->isIntegerType() || getASTContext().getTypeSize(EltTy) != 32) {
+      Diag(Arg->getBeginLoc(), diag::err_builtin_invalid_arg_type)
+          << 1 << /* integer ty */ 6 << ArgTy;
+      return true;
+    }
+
+    TheCall->setType(ArgTy);
```
Comment (farzonl) [inline clang/lib/Sema/SemaHLSL.cpp:1894]: If @bogner is right  this line is a bit more complicated. We will have to construct the call type  as a scalar or vector of the same size as ArgTy but with the element type of int32.

**Comment by spall** [comment]
> It is not correct to limit firstbithigh to 32 bit integers. There are a couple of reasons that might make one think that it is, but we do in fact want/need to support int16 and int64 here.
> 
>     1. The [HLSL docs](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh) only mention integer. Unfortunately that's true for most of these functions, as many of these docs were not updated as 64 and 16 bit types gained support in the language.
> 
>     2. DXC's SPIR-V implementation doesn't handle 16- and 64-bit for these functions. As noted in [Incorrect SPIR-V generated when `firstbithigh` is used on a `uint64_t` microsoft/DirectXShaderCompiler#4702](https://github.com/microsoft/DirectXShaderCompiler/issues/4702) we decided not to implement those overloads in DXC, but should reconsider this for clang.
> 
> 
> Despite all of this, DXC does indeed support 16- and 64-bit overloads, as seen here: https://hlsl.godbolt.org/z/qbc17xz35
> 
> Note that the return type of the operation is not overloaded - all of the overloads of this function return uint.

Why is the return type not overloaded? It is overloaded for countbits which is a similar function.

**Comment by bogner** [comment]
> > Despite all of this, DXC does indeed support 16- and 64-bit overloads, as seen here: https://hlsl.godbolt.org/z/qbc17xz35
> > Note that the return type of the operation is not overloaded - all of the overloads of this function return uint.
> 
> Why is the return type not overloaded? Isn't it overloaded for countbits which is a similar function.

The return type for countbits is also not overloaded: https://hlsl.godbolt.org/z/oGYhsjEGc - in fact none of the operations that use the `unaryBits` operation class are overloaded on the return type.

The code we're generating with clang for countbits right now actually just looks like it's wrong. It doesn't match what DXC does at all: https://hlsl.godbolt.org/z/K8n3j5o3K

**Comment by spall** [comment]
> > > Despite all of this, DXC does indeed support 16- and 64-bit overloads, as seen here: https://hlsl.godbolt.org/z/qbc17xz35
> > > Note that the return type of the operation is not overloaded - all of the overloads of this function return uint.
> > 
> > 
> > Why is the return type not overloaded? Isn't it overloaded for countbits which is a similar function.
> 
> The return type for countbits is also not overloaded: https://hlsl.godbolt.org/z/oGYhsjEGc - in fact none of the operations that use the `unaryBits` operation class are overloaded on the return type.
> 
> The code we're generating with clang for countbits right now actually just looks like it's wrong. It doesn't match what DXC does at all: https://hlsl.godbolt.org/z/K8n3j5o3K
Addressed here:
https://github.com/llvm/llvm-project/pull/113189

File: clang/test/CodeGenHLSL/builtins/firstbithigh.hlsl [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+// CHECK: call <3 x i64> @llvm.[[TARGET]].firstbitshigh.v3i64
+int64_t3 test_firstbithigh_long3(int64_t3 p0) {
+  return firstbithigh(p0);
+}
+
+// CHECK-LABEL: test_firstbithigh_long4
+// CHECK: call <4 x i64> @llvm.[[TARGET]].firstbitshigh.v4i64
+int64_t4 test_firstbithigh_long4(int64_t4 p0) {
+  return firstbithigh(p0);
+}
```
[the remark this answers is not in the document]
Comment (farzonl) [reply clang/test/CodeGenHLSL/builtins/firstbithigh.hlsl:153]: You still need a new line here.

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp [hunk 13]
```diff
@@ -424,7 +424,7 @@ Register SPIRVGlobalRegistry::getOrCreateCompositeOrNull(
     LLT LLTy = LLT::scalar(64);
     Register SpvVecConst =
         CurMF->getRegInfo().createGenericVirtualRegister(LLTy);
-    CurMF->getRegInfo().setRegClass(SpvVecConst, &SPIRV::iIDRegClass);
+    CurMF->getRegInfo().setRegClass(SpvVecConst, getRegClass(SpvType));
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:427]: NIT: Since this was a bug fix. Would it have been better to do this as a seperate commit to capture why this was necessary?

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 14]
```diff
@@ -808,6 +835,20 @@ bool SPIRVInstructionSelector::selectExtInst(Register ResVReg,
...
+bool SPIRVInstructionSelector::selectNAryOpWithSrcs(Register ResVReg,
+                                                    const SPIRVType *ResType,
+                                                    MachineInstr &I,
+                                                    std::vector<Register> Srcs,
+                                                    unsigned Opcode) const {
+  auto MIB = BuildMI(*I.getParent(), I, I.getDebugLoc(), TII.get(Opcode))
+                 .addDef(ResVReg)
+                 .addUse(GR.getSPIRVTypeID(ResType));
+  for (Register SReg : Srcs) {
+    MIB.addUse(SReg);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:847]: I'm pretty sure this function could just replace `selectUnOpWithSrc` because unary wone just be one iteration of the loop. Maybe it would be better to do an NFC change that unifies to one function called `selectOpWithSrcs`?

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 15]
```diff
@@ -2547,6 +2588,10 @@ bool SPIRVInstructionSelector::selectIntrinsic(Register ResVReg,
     return selectExtInst(ResVReg, ResType, I, CL::rsqrt, GL::InverseSqrt);
   case Intrinsic::spv_sign:
     return selectSign(ResVReg, ResType, I);
+  case Intrinsic::spv_firstbituhigh: // There is no CL equivalent of FindUMsb
+    return selectFirstBitHigh(ResVReg, ResType, I, false);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2592]:
```suggestion
    return selectFirstBitHigh(ResVReg, ResType, I, /*IsSigned=*/false);
```

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 16]
```diff
@@ -2547,6 +2588,10 @@ bool SPIRVInstructionSelector::selectIntrinsic(Register ResVReg,
...
+  case Intrinsic::spv_firstbitshigh: // There is no CL equivalent of FindSMsb
+    return selectFirstBitHigh(ResVReg, ResType, I, true);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2594]:
```suggestion
    return selectFirstBitHigh(ResVReg, ResType, I, /*IsSigned=*/true);
```

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 17]
```diff
@@ -2626,6 +2671,148 @@ Register SPIRVInstructionSelector::buildPointerToResource(
...
+  bool ZeroAsNull = STI.isOpenCLEnv();
+  Register Reg32 = GR.getOrCreateConstVector(32, I, VResType, TII, ZeroAsNull);
+  Register Reg0 = GR.getOrCreateConstVector(0, I, VResType, TII, ZeroAsNull);
+  Result &= selectNAryOpWithSrcs(ValReg, VResType, I, {BReg, Reg0, Reg32},
+                                 SPIRV::OpSelectVIVCond);
+
+  Register AddReg = ResVReg;
+  if (isScalarRes)
+    AddReg = MRI->createVirtualRegister(GR.getRegClass(VResType));
+  Result &= selectNAryOpWithSrcs(AddReg, VResType, I, {ValReg, TmpReg},
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2786]: put a space here so it is clear  result update isn't mean to be  a part of the `if (isScalarRes)` block.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 18]
```diff
@@ -2626,6 +2671,148 @@ Register SPIRVInstructionSelector::buildPointerToResource(
...
+bool SPIRVInstructionSelector::selectFirstBitHigh(Register ResVReg,
+                                                  const SPIRVType *ResType,
+                                                  MachineInstr &I,
+                                                  bool IsSigned) const {
+  // FindUMsb intrinsic only supports 32 bit integers
+  Register OpReg = I.getOperand(2).getReg();
+  SPIRVType *OpType = GR.getSPIRVTypeForVReg(OpReg);
+  unsigned bitWidth = GR.getScalarOrVectorBitWidth(OpType);
+
+  if (bitWidth == 16)
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2808]: Maybe this would be better as a switch statement. Then we can be more explicit about checking the 64 bit check and if it isn't one of these three bitwidth we can throw an error.

File: llvm/lib/Target/DirectX/DirectXTargetTransformInfo.cpp [hunk 19]
```diff
@@ -28,6 +28,8 @@ bool DirectXTTIImpl::isTargetIntrinsicTriviallyScalarizable(
   switch (ID) {
   case Intrinsic::dx_frac:
   case Intrinsic::dx_rsqrt:
+  case Intrinsic::dx_firstbituhigh:
+  case Intrinsic::dx_firstbitshigh:
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DirectXTargetTransformInfo.cpp:32]: you will want to rebase, line ending change made it so a bunch of our prs are getting merge conflcts on this file.

**Comment by farzonl** [comment]
This looks really good. I hade a few minor things and questions about either pulling things out of this pr and putting them into their own changes or future clean up to consolidate things. One more iteration and I'll be happy to approve.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 20]
```diff
@@ -2626,6 +2671,148 @@ Register SPIRVInstructionSelector::buildPointerToResource(
...
+              TII.get(SPIRV::OpVectorShuffle))
+          .addDef(HighReg)
+          .addUse(GR.getSPIRVTypeID(VResType))
+          .addUse(FBHReg)
+          .addUse(
+              FBHReg); // this vector will not be selected from; could be empty
+  unsigned i;
+  for (i = 0; i < count * 2; i += 2) {
+    MIB.addImm(i);
+  }
```
Comment (bogner) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2743]: Better to declare the variable in the for-loop scope so it's clear we aren't planning on using it again later. Also it's a bit confusing to have two variables named `i` and `I` in scope here - might be best to rename the `MachineInstr` to `MI` and/or to use some other placeholder like `J` here.

**Review by bogner — APPROVED** [review]
Looks good to me once @farzonl's feedback is taken into account.

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp (hunk 13 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:427]: Happy to put it in its own PR if that is what people want. I just left it here since it is such a small change.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 14 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:847]: Should I do that as part of this PR?

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp (hunk 13 above)
Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:427]: I imagine there are other places in the SPIRV backend that might require a fix like this and want to give a future person a hint at how to fix it.

Alternatively create a second issue which refrences the problem you found. Add it to the pr description as fixed by this pr. drop a link to the issue in this comment section. That way if anyone searches github issues for something similar to this they will find your issue and see how you fixed it.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 14 above)
Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:847]: You can do it as a follow on.

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp (hunk 13 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:427]: I created issue #113486 and mentioned it in this PR.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 20 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2743]: It is actually re-used in the for-loop below this one. I will rename one of them.

**Review by farzonl — APPROVED** [review]

File: llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll [hunk 21]
```diff
@@ -0,0 +1,107 @@
+; RUN: llc -verify-machineinstrs -O0 -mtriple=spirv-unknown-unknown %s -o - | FileCheck %s
+; RUN: %if spirv-tools %{ llc -O0 -mtriple=spirv-unknown-unknown %s -o - -filetype=obj | spirv-val %}
+
+; CHECK: OpMemoryModel Logical GLSL450
+
+define noundef i32 @firstbituhigh_i32(i32 noundef %a) {
```
Comment (farzonl) [inline llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:6]: This file has a bug
project/llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll -o - -filetype=obj
error: line 54: Illegal number of components (1) for TypeVector
  %v1uint = OpTypeVector %uint 1

Comment (spall) [reply llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:6]: Yes I saw I am working on fixing it.

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp [hunk 22]
```diff
@@ -449,6 +449,15 @@ Register SPIRVGlobalRegistry::getOrCreateCompositeOrNull(
   return Res;
 }
 
+Register SPIRVGlobalRegistry::getOrCreateConstScalarOrVector(
+    uint64_t Val, MachineInstr &I, SPIRVType *SpvType,
+    const SPIRVInstrInfo &TII, bool ZeroAsNull) {
+  if (SpvType->getOpcode() == SPIRV::OpTypeVector)
+    return getOrCreateConstVector(Val, I, SpvType, TII, ZeroAsNull);
+  else
+    return getOrCreateConstInt(Val, I, SpvType, TII, ZeroAsNull);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:458]: Should we be checking `SpvType` if it is float or int like you did for vector before deciding to create a const int?

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 23]
```diff
@@ -2717,82 +2717,82 @@ bool SPIRVInstructionSelector::selectFirstBitHigh64(Register ResVReg,
...
-    MIB.addImm(j);
-  }
-  Result &= MIB.constrainAllUses(TII, TRI, RBI);
-
-  SPIRVType *BoolType = GR.getOrCreateSPIRVVectorType(
-      GR.getOrCreateSPIRVBoolType(I, TII), count, MIRBuilder);
   // check if the high bits are == -1;
-  Register NegOneReg = GR.getOrCreateConstVector(-1, I, VResType, TII);
+  Register NegOneReg =
+      GR.getOrCreateConstScalarOrVector(-1, I, ResType, TII, ZeroAsNull);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2771]: could we just have `NegOneReg` be determined by `isScalarRes` Seems like we keep having to check the type sprinkled throughout when it would make more sense to do the check once and have guarantees as what the type is for the entire block. Doing it the current way makes me think a future implementer could unintendedly add buggy behavior related to vector when it is scalar and vice versa.  Same for line 2779 ` isScalarRes ? SPIRV::OpSelectSISCond : SPIRV::OpSelectVIVCond;`.

File: llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll [hunk 24]
```diff
@@ -37,13 +39,12 @@ define noundef i32 @firstbituhigh_i64(i64 noundef %a) {
 entry:
 ; CHECK: [[O:%.*]] = OpBitcast %[[#]] %[[#]]
 ; CHECK: [[N:%.*]] = OpExtInst %[[#]] %[[#]] FindUMsb [[O]]
-; CHECK: [[M:%.*]] = OpVectorShuffle %[[#]] [[N]] [[N]] 0
-; CHECK: [[L:%.*]] = OpVectorShuffle %[[#]] [[N]] [[N]] 1
+; CHECK: [[M:%.*]] = OpVectorExtractDynamic %[[#]] [[N]] [[Z]]
+; CHECK: [[L:%.*]] = OpVectorExtractDynamic %[[#]] [[N]] [[X]]
```
Comment (farzonl) [inline llvm/test/CodeGen/SPIRV/hlsl-intrinsics/firstbithigh.ll:43]: This looks right. Could you document the reason for the `OpVectorShuffle` ti `OpVectorExtractDynamic`. As a response to this comment.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 23 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2771]: Sure If I do that I can probably delete the helper function I added in SPIRVGlobalRegistry. I thought this style would be less ugly than a big block.

File: llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp (hunk 22 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVGlobalRegistry.cpp:458]: No, because the Val is a uint64_t so its assumed to be an int. Following how 'getOrCreateConstVectr' is written, someone would write an overload of this that takes a float if they wanted it for floats.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 23 above)
Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2771]: I can see the potential readability benefits. That said so much of the spirv backend is splitting scalar vs vector behaviors into their own little playgrounds that it feels like we are going against the grain here.  Thats why we have `OpSelectSISCond` and `OpSelectVIVCond` when the SPIRV spec makes no function difference in the opcode.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 25]
```diff
@@ -2626,6 +2671,151 @@ Register SPIRVInstructionSelector::buildPointerToResource(
...
+  return Result & selectFirstBitHigh32(ResVReg, ResType, I, ExtReg, IsSigned);
+}
+
+bool SPIRVInstructionSelector::selectFirstBitHigh32(Register ResVReg,
+                                                    const SPIRVType *ResType,
+                                                    MachineInstr &I,
+                                                    Register SrcReg,
+                                                    bool IsSigned) const {
+  unsigned Opcode = IsSigned ? GL::FindSMsb : GL::FindUMsb;
+  return BuildMI(*I.getParent(), I, I.getDebugLoc(), TII.get(SPIRV::OpExtInst))
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: Seems like this could just be `selectExtInst`  instead of `BuildMI`.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 26]
```diff
@@ -2626,6 +2671,151 @@ Register SPIRVInstructionSelector::buildPointerToResource(
...
+bool SPIRVInstructionSelector::selectFirstBitHigh16(Register ResVReg,
+                                                    const SPIRVType *ResType,
+                                                    MachineInstr &I,
+                                                    bool IsSigned) const {
+  unsigned Opcode = IsSigned ? SPIRV::OpSConvert : SPIRV::OpUConvert;
+  // zero or sign extend
+  Register ExtReg = MRI->createVirtualRegister(GR.getRegClass(ResType));
+  bool Result =
+      selectUnOpWithSrc(ExtReg, ResType, I, I.getOperand(2).getReg(), Opcode);
+  return Result & selectFirstBitHigh32(ResVReg, ResType, I, ExtReg, IsSigned);
```
Comment (farzonl) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2683]: While this works, don't use a bit cast `&` with a bool do `&&`.

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp (hunk 25 above)
Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: If I used 'selectExtInst' it would only use the 2nd operand as the SrcReg, but the way this function is used by the 16bit and 64bit functions, it needs more freedom in what the SrcReg is.

Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: Fair enough. Alternatively, that sounds like the 2nd operand could be updated to the srcReg before calling `selectFirstBitHigh32` and then we don't pass a  srcRegister to `selectFirstBitHigh32`.

Comment (spall) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: It didn't occur to me to update the operand, so that is possible. I guess it depends on what will be more understandable.

Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: Unfortunately, there are no MIR tests in this backend for me to know if this is a problem or not, but I was curious if we don't update a stale the operand is that's essentially preserving it?

Comment (farzonl) [reply llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp:2692]: Nvmd upon looking only llvm IR has a `setOperand` I don't see one in MIR so this is fine.

**Comment by spall** [comment]
Waiting on #114482

**Review by VyacheslavLevytskyy — APPROVED** [review]
