### PR TITLE
[HLSL] Avoid putting the byval attribute on out and inout parameters

### LINKED ISSUE #148063: [DirectX] `inout` on arrays of vectors is not correctly handled
After fixing #147114 there are now 14 DML shaders failing to pass validation due to error `Instructions should not read uninitialized value`. 
While this validation error was encountered and fixed before (#139011), this appears to another unique case.

Reproduction: https://godbolt.org/z/vd1jWr79P

The following shader defines and uses a function `FillZero` with an inout parameter to fill an array of vectors with zeros.
Calling `FillZero` with `foo` does not correctly set `foo` to zeros.
```hlsl
// compile args: -T cs_6_7 -E CSMain
void FillZero(inout uint32_t2 v[2]) {
  v = { uint32_t2(0, 0), uint32_t2(0, 0) };
}
RWStructuredBuffer<uint32_t> output;
cbuffer Constants { uint32_t2 bar[2]; }
[numthreads(1, 1, 1)] void CSMain() {
  uint32_t2 foo[2];
  FillZero(foo);
  output[0] = dot(foo[0], bar[0]);
}
```

The resulting IR contains a `mul` instruction with one operand being `undef`, which is not valid and causes a validation error
```llvm
Function: CSMain: error: Instructions should not read uninitialized value.
note: at '%2 = mul i32 undef, %.extract' in block 'entry' of function 'CSMain'.
Validation failed.
```

One DML shader with this issue is `Cast_float16_native_accum32_uint8_packed32_256_Strided8D.dat`

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #148063 by preventing the ByVal attribute from being placed on out and inout function parameters which causes them to be eliminated by the Dead Store Elimination (DSE) pass.

### CODE REVIEW

**Comment by Icohedron** [comment]
Would it be a good idea to remove `-disable-llvm-passes` from the RUN line in the `clang/test/CodeGenHLSL/BasicFeatures/ArrayOutputArguments.hlsl` test to ensure that stores to out and inout parameters are not eliminated by DSE?

**Review by bob80905 — COMMENTED** [review]
Is it worth adding a test that would have added DeadOnReturn attribute, but now doesn't? Or is that covered by plenty of other tests currently?

**Comment by Icohedron** [comment]
> Is it worth adding a test that would have added DeadOnReturn attribute, but now doesn't? Or is that covered by plenty of other tests currently?

I don't know in what cases a DeadOnReturn attribute would be added in HLSL, so I'm not sure how to write a test for that.

**Review by farzonl — APPROVED** [review]
LGTM

**Review by bob80905 — APPROVED** [review]

File: clang/lib/CodeGen/CGCall.cpp [hunk 1]
```diff
@@ -2852,20 +2852,28 @@ void CodeGenModule::ConstructAttributeList(StringRef Name,
...
-        // Add dead_on_return when the object's lifetime ends in the callee.
-        // This includes trivially-destructible objects, as well as objects
-        // whose destruction / clean-up is carried out within the callee (e.g.,
-        // Obj-C ARC-managed structs, MSVC callee-destroyed objects).
-        if (!ParamType.isDestructedType() || !ParamType->isRecordType() ||
-            ParamType->castAs<RecordType>()
-                ->getDecl()
-                ->isParamDestroyedInCallee())
-          Attrs.addAttribute(llvm::Attribute::DeadOnReturn);
+      // HLSL out and inout parameters must not be marked with ByVal or
```
Comment (spall) [inline clang/lib/CodeGen/CGCall.cpp:2855]: Maybe expand this comment to explain why it isn't byval
"HLSL out/inout parameters are not ByVal because the caller is meant to see the callees changes"

**Review by spall — APPROVED** [review]
LGTM
