### PR TITLE
[clang] fix crash on qualified friend function definitions 

### LINKED ISSUE #185341: [clang] Crash when defining a previously declared function template as a non-template friend with global scope qualifier
```cpp
template<class>
struct D;

template<class T>
void foo(D<T>);

template<class T>
struct D {
    friend void ::foo(D) {}
};

int main() {
    foo( D<int>{} );
}
```

```
Compiler stderr
<source>:9:17: error: friend function definition cannot be qualified with '::'
    9 |     friend void ::foo(D) {}
Stack dump:
0.	Program arguments: /cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -dumpdir /app/output.s- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fdebug-compilation-dir=/app -fcoverage-compilation-dir=/app -resource-dir /cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/lib/clang/23 -internal-isystem /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.1/../../../../include/c++/16.0.1 -internal-isystem /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.1/../../../../include/c++/16.0.1/x86_64-linux-gnu -internal-isystem /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.1/../../../../include/c++/16.0.1/backward -internal-isystem /cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/lib/clang/23/include -internal-isystem /cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/../include/x86_64-unknown-linux-gnu -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.1/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++23 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -fdwarf2-cfi-asm -o /tmp/example-d10c73.o -x c++ <source>
1.	<eof> parser at end of file
2.	<source>:9:19: instantiating function definition 'foo<int>'
 #0 0x0000000003e59568 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x3e59568)
 #1 0x0000000003e566a4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x0000000003e56798 SignalHandlerTerminate(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x000077cda0242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000000c9cbca clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (.cold) SemaTemplateInstantiateDecl.cpp:0:0
 #5 0x000000000702ada8 clang::Sema::PerformPendingInstantiations(bool, bool) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x702ada8)
 #6 0x00000000065be469 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::TUFragmentKind) (.part.0) Sema.cpp:0:0
 #7 0x00000000065be744 clang::Sema::ActOnEndOfTranslationUnit() (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x65be744)
 #8 0x000000000641d53f clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x641d53f)
 #9 0x00000000063f623a clang::ParseAST(clang::Sema&, bool, bool) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x63f623a)
#10 0x00000000048394e5 clang::CodeGenAction::ExecuteAction() (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x48394e5)
#11 0x0000000004b5b5ca clang::FrontendAction::Execute() (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x4b5b5ca)
#12 0x0000000004ad84bb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x4ad84bb)
#13 0x0000000004c53e7b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0x4c53e7b)
#14 0x0000000000df8375 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0xdf8375)
#15 0x0000000000df003b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#16 0x0000000000df2fcf clang_main(int, char**, llvm::ToolContext const&) (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0xdf2fcf)
#17 0x0000000000ca51fa main (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0xca51fa)
#18 0x000077cda0229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#19 0x000077cda0229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#20 0x0000000000defad5 _start (/cefs/52/52629d580b115717d73c025b_clang-trunk-20260308/bin/clang-23+0xdefad5)
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: clang frontend command failed with exit code -2 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by Serosh-commits**
This patch fixes a crash caused by qualified friend function definitions and  We now recover early by diagnosing the invalid qualifier and clearing the scope 
fixes #185341

### CODE REVIEW

**Review by mizvekov — COMMENTED** [review]
I think the better approach would be for error recovery to proceed as if the user didn't write that extraneous qualification.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -18461,6 +18408,9 @@ NamedDecl *Sema::ActOnFriendFunctionDecl(Scope *S, Declarator &D,
                                           TemplateParams, AddToScope);
   if (!ND) return nullptr;
 
+  if (WasQualifiedFriendDef)
+    ND->setInvalidDecl();
```
Comment (mizvekov) [inline clang/lib/Sema/SemaDeclCXX.cpp]: We don't really need to set this, since there is nothing invalid about the declaration now, right?

**Review by mizvekov — APPROVED** [review]
Small nit, otherwise LGTM.

**Review by mizvekov — APPROVED** [review]
Ops, just a couple of tiny nits and you are good to go!

**Comment by Serosh-commits** [comment]
> > @mizvekov using SS.clear() and Previous.clear() stops the crash but it breaks some existing tests i think the reason is that it runs for all qualified friend definitions, including cases like friend void C::f() inside a class, which should produce a different diagnostic so i am kinda thinking maybe the recovery should run only when the qualifier refers to namespace/global scope, which we can check using computeDeclContext(SS) will that would be a good approach ? i think this should work
> 
> Ah yes, though that case is simpler to check, you don't need `computeDeclContext`, you can simply check for the right kinds of nested name specifier (namespace, namespace alias, and global).

@mizvekov 

> > @mizvekov using SS.clear() and Previous.clear() stops the crash but it breaks some existing tests i think the reason is that it runs for all qualified friend definitions, including cases like friend void C::f() inside a class, which should produce a different diagnostic so i am kinda thinking maybe the recovery should run only when the qualifier refers to namespace/global scope, which we can check using computeDeclContext(SS) will that would be a good approach ? i think this should work
> 
> Ah yes, though that case is simpler to check, you don't need `computeDeclContext`, you can simply check for the right kinds of nested name specifier (namespace, namespace alias, and global).

@mizvekov i think nestednamespacespecifier enum doesn't contain namespacealias that's why it is triggering  a lot yeah the namespace itself can cover it:/

**Comment by Serosh-commits** [comment]
> The problem here looks fairly simple to understand what goes wrong. Example:
> 
> ```c++
> struct X {
>   void f2();
> };
> struct Y {
>   friend void X::f2() {}
> };
> ```
> 
> Your logic for filtering the diagnostic based on the nested name specifier being of namespace / global kind only is not right, as this case otherwise does not get covered by any diagnostics later.

image
@mizvekov oh shoot  i actually thought that and asked u that previously the problem to make sure but yeah i didn't realised i didn't submitted it
yeah u are right let me refactor it 

Thanks for ur review and ur help means a lot

**Comment by Serosh-commits** [comment]
@mizvekov the tests passed !
let me know if u want any more nits 
Thanks

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 2]
```diff
@@ -18476,6 +18490,9 @@ NamedDecl *Sema::ActOnFriendFunctionDecl(Scope *S, Declarator &D,
     DCScope = &FakeDCScope;
   }
 
+  if (IsEarlyRecovered)
+    Previous.clear();
```
[the remark this answers is not in the document]
Comment (Serosh-commits) [reply clang/lib/Sema/SemaDeclCXX.cpp]: @mizvekov yeah removed it thanks for pointing it out

**Review by mizvekov — APPROVED** [review]
LGTM, but please also fix the PR description, as it doesn't reflect the patch anymore.
That's what will be used as the commit message.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 3]
```diff
@@ -18319,6 +18319,18 @@ NamedDecl *Sema::ActOnFriendFunctionDecl(Scope *S, Declarator &D,
...
+    auto Kind = SS.getScopeRep().getKind();
+    if (Kind == NestedNameSpecifier::Kind::Global ||
+        Kind == NestedNameSpecifier::Kind::Namespace) {
+      if (D.getName().getKind() != UnqualifiedIdKind::IK_TemplateId) {
+        Diag(SS.getRange().getBegin(), diag::err_qualified_friend_def)
+            << SS.getScopeRep() << FixItHint::CreateRemoval(SS.getRange());
+        SS.clear();
+      }
+    }
+  }
```
Comment (mizvekov) [inline clang/lib/Sema/SemaDeclCXX.cpp]: Nit: Can you reduce the level of nesting here? A bit excessive, you can certainly move the last condition into the first one.

Comment (erichkeane) [reply clang/lib/Sema/SemaDeclCXX.cpp]: I would suggest/request putting the condition into its own variable/function/etc.  It is REALLY hard to figure out what it is actually checking here, and adding some names will be helpful.

**Comment by Serosh-commits** [comment]
> LGTM, but please also fix the PR description, as it doesn't reflect the patch anymore.
> That's what will be used as the commit message.

Thanks yeah no problem I will update the old pr description to new one

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 3 above)
Comment (Serosh-commits) [reply clang/lib/Sema/SemaDeclCXX.cpp]: > Nit: Can you reduce the level of nesting here? A bit excessive, you can certainly move the last condition into the first one.

sure 😃

Comment (Serosh-commits) [reply clang/lib/Sema/SemaDeclCXX.cpp]: > I would suggest/request putting the condition into its own variable/function/etc.  It is REALLY hard to figure out what it is actually checking here, and adding some names will be helpful.

yeah no problem Thanks for the suggestion 😊 erich no need for requesting ur suggestions are always helpful to me thanks 😃

**Review by erichkeane — COMMENTED** [review]
looks like you accidentially clang-formatted the whole file!  Please undo that.

**Comment by Serosh-commits** [comment]
> looks like you accidentially clang-formatted the whole file! Please undo that.

yeah doing that sry y

**Review by erichkeane — APPROVED** [review]

**Comment by Serosh-commits** [comment]
Thanks @erichkeane 
Sorry for the small updates/nits! i am actually working on  'full NTTP blockpointer support' for Clang lately
so had to take out some time to fix this side prs

**Comment by Serosh-commits** [comment]
@erichkeane 
I think ci will pass i am  sure would you  please enable automerge will appreciate it :)
