### PR TITLE
[Clang] Fix immediate escalation of template function specializations.

### LINKED ISSUE #123405: [clang++] Functions aren't marked immediate-escalating
https://godbolt.org/z/rvMWrhhYs

It seems that `PopExpressionEvaluationContext`, which triggers the marking of expressions as immediate-escalating, is performed _after_ the check for whether the function body contains an immediate-escalating expression. Consequently, immediate-escalating functions (i.e., lambdas and constexpr function template specializations) that contain a reference to a consteval function are never marked as immediate.

The RAII object whose teardown invokes `PopExpressionEvaluationContext` is [here](https://github.com/llvm/llvm-project/blob/d6315afff078cb4309b5614562b32520f6e3a2eb/clang/lib/Sema/SemaDecl.cpp#L15992), whereas the call that checks whether the function body contains an immediate-escalating expression is [here](https://github.com/llvm/llvm-project/blob/d6315afff078cb4309b5614562b32520f6e3a2eb/clang/lib/Sema/SemaDecl.cpp#L16006) (a few lines later, but within scope of the RAII guard).

### PR DESCRIPTION
**Pull request by cor3ntin**
We record whether an expression is immediate escalating in the FunctionScope.
However, that only happen when parsing or transforming an expression. This might not happen when transforming a non dependent expression.

This patch fixes that by considering a function immediate when instantiated from an immediate function.

Fixes #123405

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]

**Comment by cor3ntin** [comment]
I'll push a fix for the build failure on arm shortly

File: clang/test/SemaCXX/cxx2b-consteval-propagate.cpp [hunk 1]
```diff
@@ -528,3 +528,21 @@ D d(0); // expected-note {{in implicit initialization for inherited constructor
...
 }
+
+namespace GH123405 {
+
+consteval void fn() {}
+
+template <typename>
+constexpr int tfn(int) {
+    auto p = &fn;  // expected-note {{'tfn<int>' is an immediate function because its body evaluates the address of a consteval function 'fn'}}
+    return int(p); // expected-error {{cast from pointer to smaller type 'int' loses information}}
```
Comment (shafik) [inline clang/test/SemaCXX/cxx2b-consteval-propagate.cpp:539]: Should we also have a success case as well for this particular scenario or is that covered by existing tests?

**Comment by nikic** [comment]
FYI this change has some measurable compile-time overhead (about 0.2% for debug builds): https://llvm-compile-time-tracker.com/compare.php?from=eaa5897534cbd263d0cdbf780f72133c2fe8d8d4&to=561132e71b29d9b747dfda1509f715847852f77b&stat=instructions:u

Not sure whether that's expected or not.

**Comment by Michael137** [comment]
FYI, this is causing the LLDB `image dump ast` command to infinitely recurse when we have template functions in the AST. Not really super urgent because it's not a command most people use, and the root cause is probably due to the way LLDB constructs its AST. But thought I'd flag it here in case someone runs into this too
