### PR TITLE
Reapply "[sanitizer_common] AND signals in BlockSignals instead of deleting (#113443)" for non-Android Linux only

### LINKED ISSUE #113385: Sanitizers unblock user blocked signals
Regression after #98200

### PR DESCRIPTION
**Pull request by thurstond**
The original patch (25fd366d6a7d40266ff27c134ed8beb0a90cc33b) was reverted in 083a5cdbeab09517d8345868970d4f41170d7ed2 because it broke some buildbots.

This revised patch makes two changes:
- Reverts to *pre-#98200* behavior for Android. This avoids a build breakage on Android.
- Only define KeepUnblocked if SANITIZER_LINUX: this avoids a build breakage on solaris, which does not support internal_sigdelset.
N.B. Other buildbot failures were non-sanitizer tests and are therefore unrelated.

Original commit message:
    My earlier patch https://github.com/llvm/llvm-project/pull/98200
    caused a regression because it unconditionally unblocked synchronous
    signals, even if the user program had deliberately blocked them.
    This patch fixes the issue by checking the current signal mask, as
    suggested by Vitaly. It also adds tests.
    Fixes #113385

### CODE REVIEW

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp [hunk 1]
```diff
@@ -164,33 +164,55 @@ void SetSigProcMask(__sanitizer_sigset_t *set, __sanitizer_sigset_t *oldset) {
...
-  internal_sigdelset(&set, SIGSEGV);
-  internal_sigdelset(&set, SIGBUS);
-  internal_sigdelset(&set, SIGILL);
-  internal_sigdelset(&set, SIGTRAP);
-  internal_sigdelset(&set, SIGABRT);
-  internal_sigdelset(&set, SIGFPE);
-  internal_sigdelset(&set, SIGPIPE);
+  // but also don't unblock signals that the user had deliberately blocked.
+  KeepUnblocked(newset, currentset, SIGSEGV);
+  KeepUnblocked(newset, currentset, SIGBUS);
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:207]: Do you know how long Android has https://github.com/llvm/llvm-project/pull/98200 ?
If Android has no #98200 maybe better to return to pre- #98200 behaviour?
CC @fmayer

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:207]: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r536225/clang_source_info.md says they used https://github.com/llvm/llvm-project/commits/fc57f88f007497a4ead0ec8607ac66e1847b02d6, which predates https://github.com/llvm/llvm-project/pull/98200

@fmayer: is this the right interpretation of the Android prebuilt metadata?

Comment (fmayer) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:207]: Yes, also that is the currently used version of clang in AOSP: https://cs.android.com/android/platform/superproject/main/+/main:build/soong/cc/config/global.go;l=389;drc=afd8aacf5850899cf7ae5bf8d7b88135d6e5fc6a

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:207]: Thanks for the confirmation! I will shortly update this patch to apply the pre-#98200 behavior for Android.

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp [hunk 2]
```diff
@@ -181,9 +178,7 @@ static void KeepUnblocked(__sanitizer_sigset_t &newset,
 void BlockSignals(__sanitizer_sigset_t *oldset) {
   __sanitizer_sigset_t currentset;
 #  if !SANITIZER_ANDROID
-  // FIXME: SetSigProcMask and pthread_sigmask cause mysterious failures
-  // See also: comment in KeepUnblocked().
-  // In the meantime, we prefer to sometimes incorrectly unblock signals.
+  // FIXME: SetSigProcMask cause mysterious failures on Android
```
Comment (fmayer) [inline compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:181]: can we create some reference? a bug in llvm or google/sanitizers repo that has the logs of the failing buildbot run?

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp]: Filed https://github.com/google/sanitizers/issues/1816 and updated the FIXMEs

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp [hunk 3]
```diff
@@ -164,33 +164,54 @@ void SetSigProcMask(__sanitizer_sigset_t *set, __sanitizer_sigset_t *oldset) {
...
+  if (SANITIZER_ANDROID || !internal_sigismember(&oldset, signum))
+    internal_sigdelset(&newset, signum);
+}
+#  endif
+
 // Block asynchronous signals
 void BlockSignals(__sanitizer_sigset_t *oldset) {
-  __sanitizer_sigset_t set;
-  internal_sigfillset(&set);
+  __sanitizer_sigset_t currentset;
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:180]: unused current set warning is possible on non-linux.

**Review by vitalybuka — APPROVED** [review]

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp (hunk 3 above)
Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:180]: Non-Linux will still call `SetSigProcMask(&newset, oldset);` on line 214 (though it's effectively a no-op)

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:180]: Thanks, will fix

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp [hunk 4]
```diff
@@ -164,33 +164,57 @@ void SetSigProcMask(__sanitizer_sigset_t *set, __sanitizer_sigset_t *oldset) {
...
+#  if SANITIZER_LINUX
+  __sanitizer_sigset_t currentset;
+
+#  if !SANITIZER_ANDROID
+  // FIXME: https://github.com/google/sanitizers/issues/1816
+  SetSigProcMask(NULL, &currentset);
+#    endif  // SANITIZER_ANDROID
+#  endif    // SANITIZER_LINUX
+
+  __sanitizer_sigset_t newset;
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:189]: Move this into the begining of the function, 

```
  __sanitizer_sigset_t newset;
  internal_sigfillset(&newset);
```

and we can have single `if SANITIZER_LINUX` for the whole function

**Review by vitalybuka — APPROVED** [review]

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp (hunk 4 above)
Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp]: Good idea! Done

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp (hunk 3 above)
Comment (vitalybuka) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:181]: we still need 
```
__sanitizer_sigset_t newset;
internal_sigfillset(&newset);

# if SANITIZER_LINUX
...
#endif

SetSigProcMask(&newset, oldset);
```

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:184]: Oops, thank you!

**Comment by thurstond** [comment]
For reference: this will be backported to LLVM 19.x (https://github.com/llvm/llvm-project/pull/116670)
