### PR TITLE
lldb-dap: Stop using replicated variable ids

### LINKED ISSUE #119784: [lldb-dap] Invalid variable reference ids
# Summary

It seems like lldb-dap reuses variable reference numbers across scopes during the same suspended state. For example, if a client sends two scope requests with different frame_ids, lldb-dap uses the same variable reference numbers for different variables across scopes. 

This goes against the DAP specifications in regard to the lifetime of object references and variableReference's definition, because references become invalid before the program exits its suspended state thus making `variables` request respond with invalid data. 

```javascript
   /**
   * If `variablesReference` is > 0, the variable is structured and its children
   * can be retrieved by passing `variablesReference` to the `variables` request
   * as long as execution remains suspended. See 'Lifetime of Object References'
   * in the Overview section for details.
   */
  variablesReference: number;
```

## Example 

```json
{
  "type": "request",
  "seq": 11,
  "command": "scopes",
  "arguments": {
    "frameId": 524289
  }
}
{
  "type": "request",
  "seq": 10,
  "command": "scopes",
  "arguments": {
    "frameId": 524290
  }
}
{
  "body": {
    "scopes": [
      {
        "expensive": false,
        "name": "Locals",
        "namedVariables": 1,
        "presentationHint": "locals",
        "variablesReference": 1
      },
      {
        "expensive": false,
        "name": "Globals",
        "namedVariables": 0,
        "variablesReference": 2
      },
      {
        "expensive": false,
        "name": "Registers",
        "namedVariables": 3,
        "presentationHint": "registers",
        "variablesReference": 3
      }
    ]
  },
  "command": "scopes",
  "request_seq": 9,
  "seq": 0,
  "success": true,
  "type": "response"
},
{
  "body": {
    "scopes": [
      {
        "expensive": false,
        "name": "Locals",
        "namedVariables": 0,
        "presentationHint": "locals",
        "variablesReference": 1
      },
      {
        "expensive": false,
        "name": "Globals",
        "namedVariables": 0,
        "variablesReference": 2
      },
      {
        "expensive": false,
        "name": "Registers",
        "namedVariables": 3,
        "presentationHint": "registers",
        "variablesReference": 3
      }
    ]
  },
  "command": "scopes",
  "request_seq": 12,
  "seq": 0,
  "success": true,
  "type": "response"
}
```

## Additional Information 

I’m one of the people working on creating a client-side debug adapter implementation for the Zed code editor and noticed this bug occurring when requesting variable information. This is preventing Zed from getting valid variable information during debugging. I used the below simple program to get the above log message

While we could fix the order of our requests to mimic VSCode or Neo Vim to fix this issue, it wouldn't solve this bug during Zed's collaborative debugging sessions where multiple users could be looking at different scopes at the same time. So changing the order of Zed's requests isn't an adequate solution.

compiled with `gcc -g3 -o main.out`

```c
int main() {

    int x = 1;

    return x; // Breakpoint on this line to trigger a stop event
}
```

I installed lldb-dap through Pacman on Arch Linux and am using lldb version 18.1.18. 

## Log files
[vscode-lldb-dap-logs.txt](https://github.com/user-attachments/files/18118198/vscode-lldb-dap-logs.txt)
[zed-lldb-dap-logs.txt](https://github.com/user-attachments/files/18118199/zed-lldb-dap-logs.txt)

Please let me know if there's additional information I could provide to help fix this. I'll also be willing to collaborate with someone to come up with a patch, but I don't have any exposure to the code base so I would really appreciate help.

### LINKED ISSUE #147105: [lldb-dap] Incorrect scopes processing in case of multiple frames
I found problem with `DataBreakpointInfo` request when user change selected frame a lot. VSCode doesn’t send repeated `Scopes` requests for a frame, so the frame from the last `Scopes` request is selected even after changing frames in the UI. This causes problems with `DataBreakpointInfo` requests because lldb-dap cannot find variables in this frame. I think the solution is to add frameId  to scope's variables reference, allowing scopes from different frames to be distinguished.

### PR DESCRIPTION
**Pull request by Anthony-Eid**
Closes #119784 

Probably closes #147105 as well, but I couldn't test due to #156473: 

This PR fixes two bugs:
1. It generates unique variable reference IDs per suspended debuggee state.
2. It stores all created variables in a stopped state instead of dropping variables in unselected scopes. So it can properly handle all scope/variable requests

It does this by storing all variables in their respective scopes and using that mapping in request handlers that relied on the old mapping. It dynamically creates new variable/scope IDs instead of resetting IDs whenever a new scope is created.

I also removed some unused code as well.

### CODE REVIEW

**Comment by medismailben** [comment]
@Anthony-Eid could you rebase this PR, that'd be better to look at it

**Comment by Anthony-Eid** [comment]
@medismailben I fixed most of extra lines being added in the PR, but it's not 100% working in the new version. I'll ping you when it's functional.

I believe I'm mainly going to need help rewriting the tests once I get this functionality and following any llvm standards that I'm unaware of.

**Comment by medismailben** [comment]
Sounds good, let me know when you're ready 🙂

**Comment by Anthony-Eid** [comment]
So I ran `/Users/anth/Library/Python/3.9/bin/darker -r HEAD~ ~/Developer/llvm-project/lldb` but it doesn't seem to be formatting the code correctly. What am I missing?

File: lldb/tools/lldb-dap/Handler/ScopesRequestHandler.cpp [hunk 1]
```diff
@@ -75,22 +75,31 @@ ScopesRequestHandler::Run(const ScopesArguments &args) const {
...
+  dap.variables.ReadyFrame(frame_id, frame);
+  dap.variables.SwitchFrame(frame_id);
+
+  std::vector<Scope> scopes = {};
+
+  int64_t variable_reference = dap.variables.GetNewVariableReference(false);
+  scopes.push_back(CreateScope("Locals", variable_reference,
+                               dap.variables.locals.GetSize(), false));
+
+  dap.variables.AddScopeKind(variable_reference, ScopeKind::Locals, frame_id);
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Handler/ScopesRequestHandler.cpp:90]: Should `AddScopeKind` make a new ref internally and return the ref?

Or when we ready a frame, should this be handled then?

File: lldb/tools/lldb-dap/Variables.cpp [hunk 2]
```diff
@@ -103,3 +119,55 @@ lldb::SBValue Variables::FindVariable(uint64_t variablesReference,
...
+                                      /*locals=*/false,
+                                      /*statics=*/true,
+                                      /*in_scope_only=*/true);
+
+    auto registers = frame.GetRegisters();
+
+    m_frames.insert(
+        std::make_pair(frame_id, std::make_tuple(locals, globals, registers)));
+  }
+}
```
[the remark this answers is not in the document]
Comment (da-viper) [reply lldb/tools/lldb-dap/Variables.cpp:167]: +1

[the remark this answers is not in the document]
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.cpp:167]: What exactly is an `SBValueList`?

Would doing something like this work (under m_frames.insert())?

```c
m_variables.insert(locals.var_ref, locals);
m_variables.insert(global.var_ref, global);
m_variables.insert(registers.var_ref, registers);
```

File: lldb/tools/lldb-dap/Handler/ScopesRequestHandler.cpp [hunk 3]
```diff
@@ -41,9 +41,9 @@ static Scope CreateScope(const llvm::StringRef name, int64_t variablesReference,
   // if we add the arguments above the local scope as the locals scope will not
   // be expanded if we enter a function with arguments. It becomes more
   // annoying when the scope has arguments, return_value and locals.
-  if (variablesReference == VARREF_LOCALS)
+  if (name == "Locals")
     scope.presentationHint = Scope::eScopePresentationHintLocals;
-  else if (variablesReference == VARREF_REGS)
+  else if (name == "Registers")
     scope.presentationHint = Scope::eScopePresentationHintRegisters;
```
[the remark this answers is not in the document]
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Handler/ScopesRequestHandler.cpp]: I passed ScopeKind in to the function instead of name now, and use ScopeKind variant to generate the correct presentation hint and name for the scope. Is that an adequate fix for this?

File: lldb/tools/lldb-dap/Variables.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ashgti) [reply lldb/tools/lldb-dap/Variables.cpp:189]: A `SBValueList` is the container for the variables, like the local or global or registers.

> Would doing something like this work (under m_frames.insert())?

Yea

File: lldb/tools/lldb-dap/Variables.cpp [hunk 4]
```diff
@@ -103,3 +120,76 @@ lldb::SBValue Variables::FindVariable(uint64_t variablesReference,
...
+
+void Variables::AddScopeKind(int64_t variable_reference, ScopeKind kind,
+                             uint32_t frame_id) {
+
+  m_scope_kinds[variable_reference] = std::make_pair(kind, frame_id);
+}
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Variables.cpp:195]: When we ReadyFrame we could go ahead and add the `m_scope_kinds[]` for the frame local/globals/registers. No need to separate those out.

File: lldb/tools/lldb-dap/Variables.cpp [hunk 5]
```diff
@@ -103,3 +120,76 @@ lldb::SBValue Variables::FindVariable(uint64_t variablesReference,
...
+  case ScopeKind::Globals:
+    return &std::get<1>(frame->second);
+  case ScopeKind::Registers:
+    return &std::get<2>(frame->second);
+  }
+
+  return nullptr;
+}
+
+void Variables::ReadyFrame(uint32_t frame_id, lldb::SBFrame &frame) {
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Variables.cpp:171]: We could have this return a `std::vector<Scope>` for the local/global/register scope.

File: lldb/tools/lldb-dap/JSONUtils.cpp [hunk 6]
```diff
@@ -11,6 +11,7 @@
 #include "ExceptionBreakpoint.h"
 #include "LLDBUtils.h"
 #include "ProtocolUtils.h"
+#include "Variables.h"
```
Comment (ashgti) [inline lldb/tools/lldb-dap/JSONUtils.cpp:14]: Is variables needed any here? I don't see any usage...

File: lldb/tools/lldb-dap/JSONUtils.h [hunk 7]
```diff
@@ -9,6 +9,7 @@
 #ifndef LLDB_TOOLS_LLDB_DAP_JSONUTILS_H
 #define LLDB_TOOLS_LLDB_DAP_JSONUTILS_H
 
+#include "DAP.h"
```
Comment (ashgti) [inline lldb/tools/lldb-dap/JSONUtils.h:12]: We have DAPForward on line 13, do we need the full DAP here?

Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/JSONUtils.h]: I removed it

File: lldb/tools/lldb-dap/Variables.cpp (hunk 5 above)
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.cpp]: Done

File: lldb/tools/lldb-dap/Variables.cpp (hunk 4 above)
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.cpp]: Done

File: lldb/tools/lldb-dap/Variables.h [hunk 8]
```diff
@@ -62,7 +97,11 @@ struct Variables {
   /// These are the variables evaluated from debug console REPL.
   llvm::DenseMap<int64_t, lldb::SBValue> m_referencedpermanent_variables;
 
-  int64_t m_next_temporary_var_ref{VARREF_FIRST_VAR_IDX};
+  /// Key = frame_id
+  /// Value = (locals, globals Registers) scopes
+  std::map<uint32_t,
+           std::tuple<lldb::SBValueList, lldb::SBValueList, lldb::SBValueList>>
+      m_frames;
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Variables.h:104]: I wonder if we could use a strategy like encoding the `(thread << 19) + (frame id << 2) + <scope offset>` where the scope offset is `locals = 0, globals = 1  registers = 2`.

That would effectively mean the scopes reference variable would always be formatted like:

```
[ -  variable reference bits - ]
[32 ---------- 16 ----------- 0]
TTTTTTTTTTTTTFFFFFFFFFFFFFFFFFSS
```

Where `T` is the thread id, `F` is the frame id and `S` is the scope id.

File: lldb/tools/lldb-dap/Variables.h [hunk 9]
```diff
@@ -62,7 +97,11 @@ struct Variables {
   /// These are the variables evaluated from debug console REPL.
   llvm::DenseMap<int64_t, lldb::SBValue> m_referencedpermanent_variables;
 
-  int64_t m_next_temporary_var_ref{VARREF_FIRST_VAR_IDX};
+  /// Key = frame_id
+  /// Value = (locals, globals Registers) scopes
+  std::map<uint32_t,
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Variables.h:102]: I just realized that the frame id isn't unique enough for a key here.

The frame_id is unique to the thread it comes from but not across threads, e.g. 
```
$ lldb -p 111111
(lldb) script
>>> lldb.process.threads[0].frames[0].GetFrameID()
0
>>> lldb.process.threads[1].frames[0].GetFrameID()
0
```

Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.h]: Sorry it took me so long to get back to this. I just fixed this by using the stack frame id field from the DAP representation. 

https://github.com/Anthony-Eid/llvm-project/blob/c4155cc279323f5014dba9e4495ec4bef71e0a31/lldb/tools/lldb-dap/Handler/ScopesRequestHandler.cpp#L39-L40

Please let me know if there's something I'm missing with this solution

File: lldb/tools/lldb-dap/Variables.h (hunk 8 above)
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.h]: Would you still want to do something similar here now that we're using the dap_frame_id as the key?

**Comment by Anthony-Eid** [comment]
@medismailben Sorry for the delay, this PR should be ready for review again!

File: lldb/tools/lldb-dap/Variables.h [hunk 10]
```diff
@@ -9,22 +9,43 @@
...
 #include "lldb/API/SBValueList.h"
 #include "llvm/ADT/DenseMap.h"
+#include <map>
+#include <utility>
 
-#define VARREF_FIRST_VAR_IDX (int64_t)4
-#define VARREF_LOCALS (int64_t)1
-#define VARREF_GLOBALS (int64_t)2
-#define VARREF_REGS (int64_t)3
+#define VARREF_FIRST_VAR_IDX (int64_t)1
```
[the remark this answers is not in the document]
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.h]: Moved this to a `constexpr` named `TemporaryVariableStartIndex`

File: lldb/tools/lldb-dap/Variables.h [hunk 11]
```diff
@@ -62,7 +95,11 @@ struct Variables {
   /// These are the variables evaluated from debug console REPL.
   llvm::DenseMap<int64_t, lldb::SBValue> m_referencedpermanent_variables;
 
-  int64_t m_next_temporary_var_ref{VARREF_FIRST_VAR_IDX};
+  /// Key = dap_frame_id (encodes both thread index ID and frame ID)
+  /// Value = (locals, globals, registers) scopes
+  std::map<uint64_t,
+           std::tuple<lldb::SBValueList, lldb::SBValueList, lldb::SBValueList>>
```
[the remark this answers is not in the document]
Comment (ashgti) [reply lldb/tools/lldb-dap/Variables.h]: You can add a `llvm_unreachable("unknown scope kind");` after the switch statement.

File: lldb/tools/lldb-dap/Variables.cpp [hunk 12]
```diff
@@ -8,27 +8,72 @@
...
 }
 
 void Variables::Clear() {
-  locals.Clear();
-  globals.Clear();
-  registers.Clear();
   m_referencedvariables.clear();
+  m_scope_kinds.clear();
+  m_frames.clear();
+  m_next_temporary_var_ref = TemporaryVariableStartIndex;
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Variables.cpp]: I think we shouldn't need to reset this value on clear, otherwise we'd end up reusing ids again.

**Review by JDevlieghere — COMMENTED** [review]
A few stylistic nits.

File: lldb/tools/lldb-dap/Variables.cpp (hunk 12 above)
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.cpp]: I can remove the reset, but it's valid to do whenever a stop state resumes execution which is when clear get's called to my knowledge.

File: lldb/tools/lldb-dap/Variables.h [hunk 13]
```diff
@@ -47,13 +91,27 @@ struct Variables {
 
   lldb::SBValue FindVariable(uint64_t variablesReference, llvm::StringRef name);
 
+  /// Initialize a frame if it hasn't been already, otherwise do nothing
+  std::vector<protocol::Scope> ReadyFrame(const uint64_t dap_frame_id,
```
[the remark this answers is not in the document]
Comment (Anthony-Eid) [reply lldb/tools/lldb-dap/Variables.h]: How do you feel about initialize Frame?

[the remark this answers is not in the document]
Comment (da-viper) [reply lldb/tools/lldb-dap/Variables.h]: CreateScopes or MakeScopes as that is what we are using the sbframe to do in the function.

File: lldb/tools/lldb-dap/Variables.cpp [hunk 14]
```diff
@@ -103,3 +146,89 @@ lldb::SBValue Variables::FindVariable(uint64_t variablesReference,
...
+      eScopeKind::Locals, locals_ref,
+      GetScope(dap_frame_id, eScopeKind::Locals)->GetSize(), false));
+
+  m_scope_kinds[locals_ref] = std::make_pair(eScopeKind::Locals, dap_frame_id);
+
+  int64_t globals_ref = GetNewVariableReference(false);
+  scopes.push_back(CreateScope(
+      eScopeKind::Globals, globals_ref,
+      GetScope(dap_frame_id, eScopeKind::Globals)->GetSize(), false));
+  m_scope_kinds[globals_ref] =
```
Comment (da-viper) [inline lldb/tools/lldb-dap/Variables.cpp]: Could we change how the `readyFrame` function works as we are always checking the map every time we need a `FrameScope` instead do it once and use that value. something like.

```cpp
std::vector<protocol::Scope> Variables::ReadyFrame(const uint64_t dap_frame_id,
                                                   lldb::SBFrame &frame) {
  auto iter = m_frames.find(dap_frame_id);
  if (iter == m_frames.end()) {
    auto locals = frame.GetVariables(/*arguments=*/true,
                                     /*locals=*/true,
                                     /*statics=*/false,
                                     /*in_scope_only=*/true);

    auto globals = frame.GetVariables(/*arguments=*/false,
                                      /*locals=*/false,
                                      /*statics=*/true,
                                      /*in_scope_only=*/true);

    auto registers = frame.GetRegisters();

    iter = m_frames.emplace(dap_frame_id, FrameScopes{locals, globals, registers})
            .first;
  }

  const FrameScopes &frame_scopes = iter->second;
  auto create_and_store_scope = [&](eScopeKind kind, uint32_t size) {
    const int64_t ref = GetNewVariableReference(false);
    m_scope_kinds.try_emplace(ref, kind, dap_frame_id);
    return CreateScope(kind, ref, size, false);
  };

  return {
      create_and_store_scope(eScopeKind::Locals, frame_scopes.locals.GetSize()),
      create_and_store_scope(eScopeKind::Globals,
                             frame_scopes.globals.GetSize()),
      create_and_store_scope(eScopeKind::Registers,
                             frame_scopes.registers.GetSize())};
}
```

**Comment by da-viper** [comment]
Hello @Anthony-Eid, It seems it's all complete except the last changes. You can ping me if there is an issue. To avoid rebasing as the code base is changing quite a lot.

**Review by da-viper — APPROVED** [review]

**Comment by Anthony-Eid** [comment]
> > we're so close
> 
> @Anthony-Eid You need a merge ?

Do you mean merging this PR? If so yes please!

I merged the PR with origin/main last night so I don't think that's needed

**Comment by medismailben** [comment]
@Anthony-Eid keep an eye on this PR and on the bots on https://lab.llvm.org/buildbot/#/builders since it tests more configuration that PR testing.
