### PR TITLE
[Clang] fix overload resolution for object parameters with top-level cv-qualifiers in member functions

### LINKED ISSUE #100394: Clang rejects valid program by not removing top-level cv-qualifier when overloading explicit object member function
The following [valid program](https://stackoverflow.com/questions/78758215/explicit-object-member-function-discrepancies-between-different-compilers) is rejected by clang but accepted by other three compilers. [Demo](https://godbolt.org/z/MGWbYdr8n)

```cpp
struct C {
    void j(this const C);
    void j() const ;             //#1: Clang:Nope while gcc and msvc:Ok 
};

```

As explained in [this thread](https://stackoverflow.com/questions/78758215/explicit-object-member-function-discrepancies-between-different-compilers) this is well-formed. Clang doesn't seem to remove the top-level `const` qualifier from the first overload.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #100394

### CODE REVIEW

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp [hunk 1]
```diff
@@ -1073,3 +1073,10 @@ int main() {
   return foo[]; // expected-error {{no viable overloaded operator[] for type 'Foo'}}
 }
 }
+
+namespace GH100394 {
+struct C {
+  void f(this const C);
+  void f() const ;      // ok
+};
```
Comment (cor3ntin) [inline clang/test/SemaCXX/cxx2b-deducing-this.cpp:1081]: Here is a fun test 
```
struct C {
  void f(this const C);
  void f(this volatile C) ;  
};

(deprecated but should be handled nevertheless)

File: clang/lib/Sema/SemaOverload.cpp [hunk 2]
```diff
@@ -1511,6 +1511,9 @@ static bool IsOverloadOrOverrideImpl(Sema &SemaRef, FunctionDecl *New,
       auto NewObjectType = New->getFunctionObjectParameterReferenceType();
       auto OldObjectType = Old->getFunctionObjectParameterReferenceType();
 
+      if (NewObjectType.isConstQualified() != OldObjectType.isConstQualified())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaOverload.cpp:1514]: This probably means all of the 3 qualfiers (or at least, volatile as well).

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/test/SemaCXX/cxx2b-deducing-this.cpp:1081]: @cor3ntin thanks for the additional case, I'll take a look., it seems the current implementation doesn't support it https://compiler-explorer.com/z/TYdvG1PsK

File: clang/lib/Sema/SemaOverload.cpp [hunk 3]
```diff
@@ -1511,8 +1511,11 @@ static bool IsOverloadOrOverrideImpl(Sema &SemaRef, FunctionDecl *New,
       auto NewObjectType = New->getFunctionObjectParameterReferenceType();
       auto OldObjectType = Old->getFunctionObjectParameterReferenceType();
 
-      if (NewObjectType.isConstQualified() != OldObjectType.isConstQualified())
-        return false;
+      if (Old->isExplicitObjectMemberFunction() &&
+          OldObjectType.getQualifiers() != NewObjectType.getQualifiers())
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaOverload.cpp:1515]: do we care about `__restrict` @AaronBallman ?

Comment (erichkeane) [reply clang/lib/Sema/SemaOverload.cpp:1515]: The always-early-return doesn't make sense here to me, as Corentin mentioned, because `__restrict` can't be overloaded on IIRC.

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/test/SemaCXX/cxx2b-deducing-this.cpp:1098]: @cor3ntin @erichkeane I've changed the normalization to omit early returns and covered this case and several others - https://compiler-explorer.com/z/TMTo5s998. Are there any additional cases that should be covered? Thanks

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaOverload.cpp [hunk 4]
```diff
@@ -1422,8 +1422,14 @@ static bool IsOverloadOrOverrideImpl(Sema &SemaRef, FunctionDecl *New,
   // the implicit object parameter are of the same type.
 
   auto NormalizeQualifiers = [&](const CXXMethodDecl *M, Qualifiers Q) {
-    if (M->isExplicitObjectMemberFunction())
+    if (M->isExplicitObjectMemberFunction()) {
+      if (M->getNumParams() > 0) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaOverload.cpp:1426]: This is always true

File: clang/lib/Sema/SemaOverload.cpp [hunk 5]
```diff
@@ -1422,8 +1422,14 @@ static bool IsOverloadOrOverrideImpl(Sema &SemaRef, FunctionDecl *New,
...
+        auto ThisType = M->getParamDecl(0)->getType().getCanonicalType();
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaOverload.cpp:1427]:
```suggestion
        auto ThisType = M->getFunctionObjectParameterReferenceType().getCanonicalType();
```

Do we actually need to call `getCanonicalType()`?

File: clang/lib/Sema/SemaOverload.cpp (hunk 4 above)
Comment (a-tarasyuk) [reply clang/lib/Sema/SemaOverload.cpp]: @cor3ntin Thanks for the feedback. I've added the requested changes.

**Review by cor3ntin — APPROVED** [review]
LGTM

**Comment by a-tarasyuk** [comment]
@cor3ntin @erichkeane If no further review is needed, could you merge the PR? I don’t have access. Thanks!
