### PR TITLE
[libc++][chrono] Fix streaming for unsigned durations.

### LINKED ISSUE #96820: Cannot format a duration with unsigned (or user-defined) representation
Testcase: https://godbolt.org/z/EM7WxfEfT

```
#include <chrono>
#include <format>

int main()
{
    (void)
        std::format("{}", std::chrono::duration<unsigned>{});
}
```

Does not build:

```
In file included from /opt/compiler-explorer/clang-trunk-20240626/bin/../include/c++/v1/chrono:952:
/opt/compiler-explorer/clang-trunk-20240626/bin/../include/c++/v1/__chrono/formatter.h:594:63: error: no matching function for call to 'abs'
  594 |       __formatter::__format_chrono_using_chrono_specs(__sstr, chrono::abs(__value), __chrono_specs);
      |                                                               ^~~~~~~~~~~
```

`chrono::abs` is constrained for durations whose representation type is signed. This excludes unsigned types as well as any user-defined representation type.

Matching bug in libstdc++: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115668

### PR DESCRIPTION
**Pull request by mordante**
This fixes formatting for durations using the unsigned types unsigned short, unsigned, unsigned long, and unsigned long long. It does not allow the unsigned char type. Since the formatting function uses ostream::operator<< this type probably does not do what it should do.

Note that based on the standard all arithmetic types are allowed, including bool, char, wchar_t. These types are not implemented either. Allowing them seems like a defect in the Standard.

No effort is done to support user-defined types; the wording in the Standard is unclear regarding the constrains for these types.

[LWG 4118](https://cplusplus.github.io/LWG/issue4118) discusses this issue further.

Fixes https://github.com/llvm/llvm-project/issues/96820

### CODE REVIEW

**Review by ldionne — APPROVED** [review]

File: libcxx/include/__chrono/formatter.h [hunk 1]
```diff
@@ -589,9 +590,14 @@ __format_chrono(const _Tp& __value,
     __sstr << __value;
   else {
     if constexpr (chrono::__is_duration<_Tp>::value) {
-      if (__value < __value.zero())
-        __sstr << _CharT('-');
-      __formatter::__format_chrono_using_chrono_specs(__sstr, chrono::abs(__value), __chrono_specs);
+      if constexpr (numeric_limits<typename _Tp::rep>::is_signed) {
```
Comment (ldionne) [inline libcxx/include/__chrono/formatter.h:593]: I would use `std::is_signed_v<typename _Tp::rep>` instead. It allows you to include only `<__type_traits/is_signed.h>`.

**Review by ldionne — APPROVED** [review]

File: libcxx/include/__chrono/formatter.h (hunk 1 above)
Comment (mordante) [reply libcxx/include/__chrono/formatter.h:595]: Actually there is a difference between the two. Users may specialize `numeric_limits`, but specializing `is_signed` is not allowed. Durations can use a user defined arithmetic type. So using  `numeric_limits` seems to be the better choice. I've added comment in the code.
