### PR TITLE
[clang] Implement StmtPrinter for EmbedExpr

### LINKED ISSUE #107869: [clangd] crash when using #embed
```c
static constexpr unsigned char data[] = {
#embed "data"
};
```
I use sublime text with the LSP plugin and clangd. hovering my mouse over `data` causes it to crash

### LINKED ISSUE #132641: clang++ C++26 feature bug
The compiler told me to submit this bug, here's the message:

[bug_report.txt](https://github.com/user-attachments/files/19411760/bug_report.txt)

```
 clang++ -std=c++2c renges_test.cpp -o tst
renges_test.cpp:42:4: warning: #embed is a Clang extension [-Wc23-extensions]
   42 |                 #embed "./.clangd" prefix(0x2c, 0x20, )limit(5)
      |                  ^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -cc1 -triple x86_64-pc-linux-gnu -emit-obj -dumpdir tst- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name renges_test.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava -fcoverage-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava -resource-dir /usr/lib/clang/19 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/backward -internal-isystem /usr/lib/clang/19/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2c -fdeprecated-macro -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/renges_test-dae414.o -x c++ renges_test.cpp
1.	renges_test.cpp:43:3: current parser token ';'
2.	renges_test.cpp:8:1: parsing function body 'main'
3.	renges_test.cpp:8:1: in compound statement ('{}')
 #0 0x000077bdc5a1a730 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /usr/src/debug/llvm/llvm-19.1.7.src/lib/Support/Unix/Signals.inc:723:22
 #1 0x000077bdc5a176bd llvm::sys::RunSignalHandlers() /usr/src/debug/llvm/llvm-19.1.7.src/lib/Support/Signals.cpp:105:20
 #2 0x000077bdc5a176bd SignalHandler /usr/src/debug/llvm/llvm-19.1.7.src/lib/Support/Unix/Signals.inc:403:31
 #3 0x000077bdc4c4bcd0 (/usr/lib/libc.so.6+0x3dcd0)
 #4 0x000077bdce31e210 clang::Stmt::getStmtClass() const /usr/src/debug/clang/clang-19.1.7.src/include/clang/AST/Stmt.h:1359:44
 #5 0x000077bdce31e210 clang::ImplicitValueInitExpr::classof(clang::Stmt const*) /usr/src/debug/clang/clang-19.1.7.src/include/clang/AST/Expr.h:5794:27
 #6 0x000077bdce31e210 llvm::isa_impl<clang::ImplicitValueInitExpr, clang::Expr, void>::doit(clang::Expr const&) /usr/include/llvm/Support/Casting.h:64:64
 #7 0x000077bdce31e210 llvm::isa_impl_cl<clang::ImplicitValueInitExpr, clang::Expr const*>::doit(clang::Expr const*) /usr/include/llvm/Support/Casting.h:110:36
 #8 0x000077bdce31e210 llvm::isa_impl_wrap<clang::ImplicitValueInitExpr, clang::Expr const*, clang::Expr const*>::doit(clang::Expr const* const&) /usr/include/llvm/Support/Casting.h:137:41
 #9 0x000077bdce31e210 llvm::isa_impl_wrap<clang::ImplicitValueInitExpr, clang::Expr const* const, clang::Expr const*>::doit(clang::Expr const* const&) /usr/include/llvm/Support/Casting.h:129:13
#10 0x000077bdce31e210 llvm::CastIsPossible<clang::ImplicitValueInitExpr, clang::Expr const*, void>::isPossible(clang::Expr const* const&) /usr/include/llvm/Support/Casting.h:257:62
#11 0x000077bdce31e210 llvm::CastInfo<clang::ImplicitValueInitExpr, clang::Expr const* const, void>::isPossible(clang::Expr const* const&) /usr/include/llvm/Support/Casting.h:509:38
#12 0x000077bdce31e210 bool llvm::isa<clang::ImplicitValueInitExpr, clang::Expr const*>(clang::Expr const* const&) /usr/include/llvm/Support/Casting.h:549:46
#13 0x000077bdce31e210 MaybeElementDependentArrayFiller /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:11214:33
#14 0x000077bdce33ef0c VisitCXXParenListOrInitListExpr /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:11276:0
#15 0x000077bdce3a07cb Visit /usr/src/debug/clang/clang-19.1.7.src/build/include/clang/AST/StmtNodes.inc:352:0
#16 0x000077bdd0546eaf EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) (.constprop.0) /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:15843:0
#17 0x000077bdce354e2b VisitMaterializeTemporaryExpr /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:8753:0
#18 0x000077bdce359a85 EvaluateLValue /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:8604:0
#19 0x000077bdce359a85 VisitCXXStdInitializerListExpr /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:10558:0
#20 0x000077bdce3a1e78 EvaluateInPlace /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:15833:0
#21 0x000077bdd0769075 EvaluateCallArg(clang::ParmVarDecl const*, clang::Expr const*, (anonymous namespace)::CallRef, (anonymous namespace)::EvalInfo&, bool) (.isra.0) /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:6244:23
#22 0x000077bdd07ed637 EvaluateArgs(llvm::ArrayRef<clang::Expr const*>, (anonymous namespace)::CallRef, (anonymous namespace)::EvalInfo&, clang::FunctionDecl const*, bool) (.isra.0) /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:6283:0
#23 0x000077bdce34c256 HandleConstructorCall /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:6591:0
#24 0x000077bdce34c533 VisitCXXConstructExpr /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:10527:0
#25 0x000077bdce3752c6 VisitExprWithCleanups /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:7791:50
#26 0x000077bdce3752c6 Visit /usr/src/debug/clang/clang-19.1.7.src/build/include/clang/AST/StmtNodes.inc:392:1
#27 0x000077bdce3a1e78 EvaluateInPlace /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:15833:0
#28 0x000077bdce3a2a4b clang::Expr::EvaluateAsInitializer(clang::APValue&, clang::ASTContext const&, clang::VarDecl const*, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&, bool) const /usr/src/debug/clang/clang-19.1.7.src/lib/AST/ExprConstant.cpp:16208:0
#29 0x000077bdce2ca248 clang::VarDecl::evaluateValueImpl(llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&, bool) const /usr/src/debug/clang/clang-19.1.7.src/lib/AST/Decl.cpp:2575:50
#30 0x000077bdce2ca465 llvm::SmallVectorBase<unsigned int>::size() const /usr/include/llvm/ADT/SmallVector.h:92:0
#31 0x000077bdce2ca465 llvm::SmallVectorTemplateCommon<std::pair<clang::SourceLocation, clang::PartialDiagnostic>, void>::end() /usr/include/llvm/ADT/SmallVector.h:283:0
#32 0x000077bdce2ca465 llvm::SmallVector<std::pair<clang::SourceLocation, clang::PartialDiagnostic>, 8u>::~SmallVector() /usr/include/llvm/ADT/SmallVector.h:1216:0
#33 0x000077bdce2ca465 clang::VarDecl::evaluateValue() const /usr/src/debug/clang/clang-19.1.7.src/lib/AST/Decl.cpp:2543:1
#34 0x000077bdceb6c341 clang::Sema::FinalizeVarWithDestructor(clang::VarDecl*, clang::RecordType const*) /usr/src/debug/clang/clang-19.1.7.src/lib/Sema/SemaDeclCXX.cpp:16043:0
#35 0x000077bdceac26c8 clang::Sema::CheckCompleteVariableDeclaration(clang::VarDecl*) /usr/src/debug/clang/clang-19.1.7.src/lib/Sema/SemaDecl.cpp:14473:32
#36 0x000077bdceae0ccb clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) /usr/src/debug/clang/clang-19.1.7.src/lib/Sema/SemaDecl.cpp:13761:0
#37 0x000077bdcdfeaf9c ~InitializerScopeRAII /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2676:0
#38 0x000077bdcdfeaf9c clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2898:0
#39 0x000077bdcdfee399 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2517:0
#40 0x000077bdcdffe4e6 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2135:0
#41 0x000077bdcdffe96a clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2059:0
#42 0x000077bdce092059 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseStmt.cpp:262:32
#43 0x000077bdce0922a7 clang::Parser::MaybeDestroyTemplateIds() /usr/src/debug/clang/clang-19.1.7.src/include/clang/Parse/Parser.h:328:5
#44 0x000077bdce0922a7 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseStmt.cpp:126:26
#45 0x000077bdce09a59a clang::Parser::ParseCompoundStatementBody(bool) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseStmt.cpp:1248:38
#46 0x000077bdce09ddac clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseStmt.cpp:2532:3
#47 0x000077bdce0bf6ef clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/Parser.cpp:1525:36
#48 0x000077bdcdfee83f clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseDecl.cpp:2427:0
#49 0x000077bdce0bc9d8 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/Parser.cpp:1249:73
#50 0x000077bdce0bd3ba clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/Parser.cpp:1271:42
#51 0x000077bdce0cd632 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/Parser.cpp:1074:50
#52 0x000077bdce0ce345 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/Parser.cpp:763:36
#53 0x000077bdcdfd9c18 clang::ParseAST(clang::Sema&, bool, bool) /usr/src/debug/clang/clang-19.1.7.src/lib/Parse/ParseAST.cpp:170:0
#54 0x000077bdcfcfa221 clang::FrontendAction::Execute() /usr/src/debug/clang/clang-19.1.7.src/lib/Frontend/FrontendAction.cpp:1078:21
#55 0x000077bdcfc9008f llvm::Error::getPtr() const /usr/include/llvm/Support/Error.h:282:12
#56 0x000077bdcfc9008f llvm::Error::operator bool() /usr/include/llvm/Support/Error.h:242:22
#57 0x000077bdcfc9008f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /usr/src/debug/clang/clang-19.1.7.src/lib/Frontend/CompilerInstance.cpp:1061:42
#58 0x000077bdcfd54ba5 std::__shared_ptr<clang::FrontendOptions, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/14.2.1/bits/shared_ptr_base.h:1667:0
#59 0x000077bdcfd54ba5 std::__shared_ptr_access<clang::FrontendOptions, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const /usr/include/c++/14.2.1/bits/shared_ptr_base.h:1364:0
#60 0x000077bdcfd54ba5 std::__shared_ptr_access<clang::FrontendOptions, (__gnu_cxx::_Lock_policy)2, false, false>::operator*() const /usr/include/c++/14.2.1/bits/shared_ptr_base.h:1350:0
#61 0x000077bdcfd54ba5 clang::CompilerInvocation::getFrontendOpts() /usr/src/debug/clang/clang-19.1.7.src/include/clang/Frontend/CompilerInvocation.h:259:0
#62 0x000077bdcfd54ba5 clang::CompilerInstance::getFrontendOpts() /usr/src/debug/clang/clang-19.1.7.src/include/clang/Frontend/CompilerInstance.h:312:0
#63 0x000077bdcfd54ba5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /usr/src/debug/clang/clang-19.1.7.src/lib/FrontendTool/ExecuteCompilerInvocation.cpp:281:0
#64 0x0000606d7f450832 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /usr/src/debug/clang/clang-19.1.7.src/tools/driver/cc1_main.cpp:284:40
#65 0x0000606d7f45504e ExecuteCC1Tool /usr/src/debug/clang/clang-19.1.7.src/tools/driver/driver.cpp:215:20
#66 0x0000606d7f455de3 clang_main(int, char**, llvm::ToolContext const&) /usr/src/debug/clang/clang-19.1.7.src/tools/driver/driver.cpp:256:26
#67 0x0000606d7f448f65 main /usr/src/debug/clang/clang-19.1.7.src/build/tools/driver/clang-driver.cpp:18:1
#68 0x000077bdc4c35488 __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#69 0x000077bdc4c3554c call_init /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:128:20
#70 0x000077bdc4c3554c __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:347:5
#71 0x0000606d7f448fc5 _start (/usr/bin/clang+++0xafc5)
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 19.1.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/renges_test-0b5e50.cpp
clang++: note: diagnostic msg: /tmp/renges_test-0b5e50.sh
clang++: note: diagnostic msg:

********************
```

And here's the rest of the files (with a '.txt' suffix, GitHub wouldn't let me upload them otherwise):

[renges_test-0b5e50.cpp.txt](https://github.com/user-attachments/files/19411764/renges_test-0b5e50.cpp.txt)

[renges_test-0b5e50.sh.txt](https://github.com/user-attachments/files/19411771/renges_test-0b5e50.sh.txt)

```
# Crash reproducer for clang version 19.1.7
# Driver args: "--driver-mode=g++" "-std=c++2c" "renges_test.cpp" "-o" "tst"
# Original command:  "/usr/bin/clang++" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-dumpdir" "tst-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "renges_test.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava" "-fcoverage-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava" "-resource-dir" "/usr/lib/clang/19" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/backward" "-internal-isystem" "/usr/lib/clang/19/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++2c" "-fdeprecated-macro" "-ferror-limit" "19" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/renges_test-dae414.o" "-x" "c++" "renges_test.cpp"
 "/usr/bin/clang++" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-dumpdir" "tst-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "renges_test.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava" "-fcoverage-compilation-dir=/home/uwu/Desktop/ccpp/algo2_test_priprava" "-std=c++2c" "-fdeprecated-macro" "-ferror-limit" "19" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "renges_test-0b5e50.cpp"
```

[renges_test.cpp.txt](https://github.com/user-attachments/files/19411772/renges_test.cpp.txt)

```C++
#include <iterator>
#include <ranges>
#include <vector>
#include <print>
#include <string>

int main(void)
{
	//toto je magicne :D
	namespace rv = std::ranges::views;
	std::vector<int> vec{1,2,3,10};
	auto even_nums = vec | 
		//VYJMI prvky, ktere podminku splnuji
		rv::filter([](const int& a) -> bool 
	     		{ 
	     			return !(a % 2); 
	     		})  
			| rv::reverse;

	//TODO: Najdi si, jak udelat tyto prikazy pro vypis kodove hezci
	auto size = std::ranges::distance(even_nums);
	auto count = 0;
	for(const auto& el : even_nums) 
	{	
		std::print("{}", el);
		if(++count < size)
			std::print(",");
	}
	std::println();
	//toto je hezci zpusob, jak takove vytisteni provest
	for(const int& i : vec | rv::take(vec.size()-1))
	{
		if(count)
		{
			std::print("{}", i);
		}
		std::println("{}", i);
	}

	std::string s
	{
		#embed "./.clangd" prefix(0x2c, 0x20, )limit(5)
	};
	std::println();
	//std::print("\b \n");
}
```

### PR DESCRIPTION
**Pull request by Fznamznon**
Tries to avoid memory leaks previously caused by saving filename by allocating memory in the preprocessor.

Fixes https://github.com/llvm/llvm-project/issues/132641
Fixes https://github.com/llvm/llvm-project/issues/107869

### CODE REVIEW

File: clang/test/Preprocessor/embed_weird.cpp [hunk 1]
```diff
@@ -136,3 +136,43 @@ constexpr struct HasChar c = {
...
+constexpr S2 s2 { // cxx-error {{must be initialized by a constant expression}}
+                  // cxx-note-re@-1 {{in call to 'S2{{.*}} #embed <jk.txt>}}
+#embed <jk.txt> prefix(0x2c, 0x20, )limit(5)
+};
+constexpr S2 s3 {1, // cxx-error {{must be initialized by a constant expression}}
+                    // cxx-note-re@-1 {{in call to 'S2{{.*}} #embed "jk.txt"}}
+#embed "jk.txt"
+};
+constexpr S2 s4 { // cxx-error {{must be initialized by a constant expression}}
+                  // cxx-note-re@-1 {{in call to 'S2{{.*}}"jk"}}
```
Comment (Fznamznon) [inline clang/test/Preprocessor/embed_weird.cpp:175]: Note, no #embed here because it falls into the fast path and we use a stringliteral directly to initialize.

**Comment by Fznamznon** [comment]
This might also fix https://github.com/llvm/llvm-project/issues/107869 since a similar fix was proposed earlier to fix it. I don't have any experience with clangd to verify though.

File: clang/lib/AST/StmtPrinter.cpp [hunk 2]
```diff
@@ -1284,7 +1284,11 @@ void StmtPrinter::VisitSourceLocExpr(SourceLocExpr *Node) {
 }
 
 void StmtPrinter::VisitEmbedExpr(EmbedExpr *Node) {
-  llvm::report_fatal_error("Not implemented");
+  // Embed parameters are not reflected in the AST, so there is no way to print
```
Comment (AaronBallman) [inline clang/lib/AST/StmtPrinter.cpp:1287]:
```suggestion
  // FIXME: Embed parameters are not reflected in the AST, so there is no way to print
```

File: clang/lib/Lex/PPDirectives.cpp [hunk 3]
```diff
@@ -4049,5 +4050,13 @@ void Preprocessor::HandleEmbedDirective(SourceLocation HashLoc, Token &EmbedTok,
   if (Callbacks)
     Callbacks->EmbedDirective(HashLoc, Filename, isAngled, MaybeFileRef,
                               *Params);
-  HandleEmbedDirectiveImpl(HashLoc, *Params, BinaryContents);
+  // getSpelling may return a string that is actually longer than
+  // FilenameTok.getLength(), so get the string of real length in
```
Comment (AaronBallman) [inline clang/lib/Lex/PPDirectives.cpp:4054]: Checking to see if I understand the comment (and if I do, maybe the comment can be updated to be more clear): the issue is that `getSpelling()` may return a buffer from the token itself or it may use the `SmallString` buffer we provided. If it uses the buffer, that buffer's lifetime ends at the end of this function, and we need the file name information to live far longer than that, which is why we effectively are doing a `strdup` here. Is that about right?

**Review by AaronBallman — COMMENTED** [review]
Can fix up the formatting issues found by precommit CI, and the change should also come with a release note.

File: clang/lib/Lex/PPDirectives.cpp (hunk 3 above)
Comment (Fznamznon) [reply clang/lib/Lex/PPDirectives.cpp]: Pls let me know if that is better now.

**Comment by circl-lastname** [comment]
LGTM

**Review by AaronBallman — APPROVED** [review]
LGTM! Precommit CI failures appear to be unrelated.

File: clang/lib/Parse/ParseInit.cpp [hunk 4]
```diff
@@ -435,6 +435,7 @@ ExprResult Parser::createEmbedExpr() {
   ExprResult Res;
   ASTContext &Context = Actions.getASTContext();
   SourceLocation StartLoc = ConsumeAnnotationToken();
+
```
Comment (Fznamznon) [inline clang/lib/Parse/ParseInit.cpp:438]:
```suggestion
```

**Comment by tstellar** [comment]
Was there a backport request created for this one?

**Comment by Fznamznon** [comment]
> Was there a backport request created for this one?

No, when I applied the patch locally to release20.x branch, one of the tests that this patch adds crashed, so probably additional fixes required to be backported.
