### PR TITLE
[clang] CTAD: use index and depth to retrieve template parameter for TemplateParamsReferencedInTemplateArgumentList

### LINKED ISSUE #90209: CTAD: parameter pack assertion crash when synthesizing deduction guides for alias
Example:

```
struct Key1 {}; 

template <int i>
struct Item {};

template <class... Ts>
struct List {};

template <class Key, class L>
struct TemplatedClass {
  template <class... Items>
  TemplatedClass(Key, Items...);
};

template <class Key, class...Items>
  requires(sizeof(Key) > 0 && (sizeof(Items) && ...))
TemplatedClass(Key, Items...) -> TemplatedClass<Key, List<Items...>>;

template <class T>
struct HasTemplateParam {
  template <class Key, class... Items>
  using Alias = TemplatedClass<Key, List<Items...>>;
};

struct Mod1 : HasTemplateParam<Mod1> {
  using Foo1 = decltype(Alias{Key1()});
};

```

https://godbolt.org/z/fssjafzYe.

### PR DESCRIPTION
**Pull request by hokein**
As described in https://github.com/llvm/llvm-project/issues/90209#issuecomment-2135972202, Clang may not preserve enough information during template argument deduction. This can result in a merely canonical `TemplateTypeParmType` with a null `Decl`, leading to an incomplete template parameter list for the synthesized deduction guide.

This patch addresses the issue by using the index and depth information to retrieve the corresponding template parameter, rather than relying on `TTP->getDecl()`.

Fixes #90209

### CODE REVIEW

File: clang/test/AST/ast-dump-ctad-alias.cpp [hunk 1]
```diff
@@ -99,3 +99,28 @@ BFoo b2(1.0, 2.0);
...
+template <class T2>
+using ATemplatedClass = TemplatedClass<List<T2>>;
+
+ATemplatedClass test(1);
+// Verify that we have a correct template parameter list for the deduction guide.
+//
+// CHECK:      FunctionTemplateDecl {{.*}} <deduction guide for ATemplatedClass>
+// CHECK-NEXT: |-TemplateTypeParmDecl {{.*}} class depth 0 index 0 T2
+// CHECK-NEXT: |-TypeTraitExpr {{.*}} 'bool' __is_deducible
+} // namespace GH90209
```
Comment (mizvekov) [inline clang/test/AST/ast-dump-ctad-alias.cpp:126]: Minor nit: there is now a missing newline at end of file

File: clang/lib/Sema/SemaTemplate.cpp [hunk 2]
```diff
@@ -2653,20 +2653,34 @@ struct ConvertConstructorToDeductionGuideTransform {
...
+          TemplateParams(TemplateParamList->begin(), TemplateParamList->end()) {
+    }
 
     bool VisitTemplateTypeParmType(TemplateTypeParmType *TTP) {
-      MarkAppeared(TTP->getDecl());
+      // We use the index and depth to retrieve the corresponding template
+      // parameter from the parameter list.
+      // Note that Clang may not preserve type sugar during template argument
+      // deduction. In such cases, the TTP is a canonical TemplateTypeParamType,
+      // which only retains its index and depth information.
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2675]: I would remove this section of the comment, as I think this sort of implies it would be ok to use the type sugar if it were available, but if we rely on this for correct compilation of the program, it doesn't make sense to call it type sugar anymore.
```suggestion
```

File: clang/lib/Sema/SemaTemplate.cpp [hunk 3]
```diff
@@ -2653,20 +2653,34 @@ struct ConvertConstructorToDeductionGuideTransform {
...
+      if (TTP->getDepth() == TemplateParamList->getDepth() &&
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2676]: Shouldn't this issue come up for the other kind of template parameters as well, besides type parameters?

File: clang/lib/Sema/SemaTemplate.cpp [hunk 4]
```diff
@@ -2653,20 +2653,34 @@ struct ConvertConstructorToDeductionGuideTransform {
 // Find all template parameters that appear in the given DeducedArgs.
 // Return the indices of the template parameters in the TemplateParams.
 SmallVector<unsigned> TemplateParamsReferencedInTemplateArgumentList(
-    ArrayRef<NamedDecl *> TemplateParams,
+    const TemplateParameterList* TemplateParamsList,
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2656]: The template parameters themselves should also have a depth, not just the index.
So you don't need to change everything to pass a TemplateParameterList instead of the array as before.

In fact, TemplateParameterList will just return the depth of its first parameter.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Done.

File: clang/test/AST/ast-dump-ctad-alias.cpp (hunk 1 above)
Comment (hokein) [reply clang/test/AST/ast-dump-ctad-alias.cpp:126]: Done.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 3 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: I'm not aware of any issues with non-type parameter cases, I think the AST preserves enough information.

However, for consistency, I have switched the implementation to always use depth and index to retrieve the template parameter declaration, which simplifies the code a bit. Please take a second look.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 4 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp:2778]: > In fact, TemplateParameterList will just return the depth of its first parameter.

I think it is fine, my understanding is that all parameters within a template parameter list should have the same depth,

**Review by hokein — COMMENTED** [review]
Thanks for the review.

File: clang/test/AST/ast-dump-ctad-alias.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/test/AST/ast-dump-ctad-alias.cpp:126]: The GitHub editor still shows the missing newline at end of file marker.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 3 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp]: The NTTP case is trickier to test, as we don't canonicalize expressions the same way we do types and templates,
but in some situations, you could have an NTTP which was uniqued pointing to a specific parameter, but this is misleading and you should disregard that and look at only the depth and index.

But I would expect template template parameters to behave similarly as type parameters here, and it should be just as straightforward to test, so I think it would b e worth a try.

**Review by mizvekov — APPROVED** [review]
LGTM, sans:
* missing newline at end of test file
* A similar test for template template parameter.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 3 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Thanks. Yeah, template template parameter has similar issues here, added one.
