### PR TITLE
[PAC] Fix address discrimination for type info vtable pointers

### LINKED ISSUE #101716: [PAC][clang] Fix address discrimination for type_info vtable pointers
In #99726, `-fptrauth-type-info-vtable-pointer-discrimination` was introduced, which is intended to enable type and address discrimination for type_info vtable pointers.

However, some codegen logic for actually enabling address discrimination is missing. Particularly, in `ItaniumRTTIBuilder::BuildVTablePointer` (clang/lib/CodeGen/ItaniumCXXABI.cpp), there is the following piece of code:

```
  if (auto &Schema = CGM.getCodeGenOpts().PointerAuth.CXXTypeInfoVTablePointer)
    VTable = CGM.getConstantSignedPointer(VTable, Schema, nullptr, GlobalDecl(),
                                          QualType(Ty, 0));
```

Here, `nullptr` is used as `StorageAddress` unconditionally, so, address discrimination is not actually enabled even if requested. It caused test-suite failures in several EH-related tests.

I was able to fix that locally by just using a dummy `ptr inttoptr (i64 1 to ptr)` value as `StorageAddress` (just like I did with init/fini, see https://github.com/llvm/llvm-project/pull/96478#issuecomment-2196819332), and tests became passing. I'm not sure how to get a proper `StorageAddress` here, so I've used that dummy placeholder which actually seems to do the job.

An existing test clang/test/CodeGenCXX/ptrauth-type-info-vtable.cpp shows such incorrect behavior. Particularly, in line 55, we have

```
ptr ptrauth (ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), i32 2, i64 [[STDTYPEINFO_DISC]])
```

This has constant discriminator, but does not have address discrimination, while it should be enabled with `-fptrauth-type-info-vtable-pointer-discrimination`. The correct output should be smth like (if we use a placeholder value `ptr inttoptr (i64 1 to ptr)` as storage address)

```
ptr ptrauth (ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), i32 2, i64 [[STDTYPEINFO_DISC]], ptr inttoptr (i64 1 to ptr))
```

### PR DESCRIPTION
**Pull request by kovdan01**
In #99726, `-fptrauth-type-info-vtable-pointer-discrimination` was introduced, which is intended to enable type and address discrimination for type_info vtable pointers. However, some codegen logic for actually enabling address discrimination was missing. This patch addresses the issue.

Fixes #101716

### CODE REVIEW

**Comment by kovdan01** [comment]
Also tagging @ojhunt (GitHub still does not let to add as a reviewer)

File: clang/lib/CodeGen/ItaniumCXXABI.cpp [hunk 1]
```diff
@@ -3955,9 +3955,23 @@ void ItaniumRTTIBuilder::BuildVTablePointer(const Type *Ty) {
...
 
-  if (auto &Schema = CGM.getCodeGenOpts().PointerAuth.CXXTypeInfoVTablePointer)
-    VTable = CGM.getConstantSignedPointer(VTable, Schema, nullptr, GlobalDecl(),
-                                          QualType(Ty, 0));
+  if (const auto &Schema =
+          CGM.getCodeGenOpts().PointerAuth.CXXTypeInfoVTablePointer) {
+    llvm::PointerType *PtrTy = llvm::PointerType::get(
+        CGM.getLLVMContext(),
+        CGM.getModule().getDataLayout().getProgramAddressSpace());
+    llvm::Constant *StorageAddress =
```
Comment (ojhunt) [inline clang/lib/CodeGen/ItaniumCXXABI.cpp:3963]: I'd prefer this be structured rather than using ?:

llvm::Constant *StorageAddress = nullptr;
if (Schema.isAddressDescriminated()) {
  StorageAddress = llvm::ConstantExpr::getIntToPtr(
                   llvm::ConstantInt::get(
                       CGM.IntPtrTy,
                       llvm::ConstantPtrAuth::
                           AddrDiscriminator_CXXTypeInfoVTablePointer),
                   PtrTy);
}

This bug does make me wonder if `getConstantSignedPointer(..)` etc should use a std::optional<&> rather than a pointer as that might have made it more obvious that the address was not being used in this code (obviously this is not a thing we should be changing in this PR)

**Comment by ojhunt** [comment]
Ok, it took me a moment to understand what was happening here - I had to talk to Ahmed because I didn't recognize the AddrDiscriminator_* enums and had assumed I'd forgotten them :D 

This needs to update `ItaniumRTTIBuilder::BuildVTablePointer` to take the storage address, and then use that provided address. Using any kind of signalling tags is too much of a footgun as you can easily end up accidentally (and silently) using a constant discriminator (as demonstrated by the existing code silently using no addr discriminator without being noticed :-O)

File: llvm/include/llvm/IR/Constants.h [hunk 2]
```diff
@@ -1056,12 +1056,18 @@ class ConstantPtrAuth final : public Constant {
...
-  /// expressions referencing these special arrays.
-  enum { AddrDiscriminator_CtorsDtors = 1 };
+  /// Constant values for the address discriminator which have special
+  /// significance to lowering in some contexts.
+  /// - For ctors/dtors, regular address discrimination can't
+  ///   be applied for them since uses of llvm.global_{c|d}tors are disallowed
+  ///   (see Verifier::visitGlobalVariable) and we can't emit getelementptr
+  ///   expressions referencing these special arrays.
+  /// - For vtable pointers of std::type_info and classes derived from it,
+  ///   we do not know the storage address when emitting ptrauth constant.
```
Comment (ahmedbougacha) [inline llvm/include/llvm/IR/Constants.h:1066]: Would it work to wire the storage address through `ItaniumRTTIBuilder::BuildVTablePointer` from `BuildTypeInfo` ?

Beyond that, for static ctors, as I mentioned before, I still don't think this should have ptrauth at the IR level, but rather should be a backend decision made when encoding the IR representation of "a list of static ctors/dtors" to some object file format encoding thereof.  That would avoid needing this address discriminator placeholder dance here.  But I suppose that's a separate problem.

Comment (kovdan01) [reply llvm/include/llvm/IR/Constants.h:1066]: > Would it work to wire the storage address through `ItaniumRTTIBuilder::BuildVTablePointer` from `BuildTypeInfo` ?

@ahmedbougacha I was unable to find a straight-forward way to do that, but I might be missing smth (and it might be even smth obvious). I would be glad to see more detailed suggestions if you have some better implementation in mind - I agree that having an actual address instead of a placeholder is much better.

> Beyond that, for static ctors, as I mentioned before, I still don't think this should have ptrauth at the IR level, but rather should be a backend decision made when encoding the IR representation of "a list of static ctors/dtors" to some object file format encoding thereof. That would avoid needing this address discriminator placeholder dance here. But I suppose that's a separate problem.

This sounds nice, it's an interesting suggestion. Anyway, init/fini stuff is out of scope of this PR

Comment (efriedma-quic) [reply llvm/include/llvm/IR/Constants.h:1066]: The only caller of BuildVTablePointer is BuildTypeInfo... and BuildTypeInfo itself creates the global variable in question.  So it shouldn't be that hard.  Just move the call to BuildVTablePointer after we construct the global.

Actually, that might be slightly trickier than I'm making it sound because we don't compute the type before we create the ConstantStruct, but it should be possible to separate computing the type from constructing the ConstantStruct.

**Comment by kovdan01** [comment]
@efriedma-quic @ahmedbougacha @ojhunt Would be glad to see your comments after the latest commit 0c20bcdf35f3c15024986da50cafb2a8c155e3cf which introduces using actual storage address instead of 'inttoptr 1' placeholder.

File: llvm/include/llvm/IR/Constants.h (hunk 2 above)
Comment (kovdan01) [reply llvm/include/llvm/IR/Constants.h]: @ahmedbougacha @efriedma-quic Should be fixed in 0c20bcdf35f3c15024986da50cafb2a8c155e3cf

**Review by efriedma-quic — COMMENTED** [review]
I think you should be able to avoid constructing the initializer twice if you restructure the code a bit to just construct the global before the call to BuildVTablePointer.  I added GlobalVariable::replaceInitializer because I was looking at this review: it lets you construct the global before the initializer, without having to do awkward things with RAUW.

**Comment by kovdan01** [comment]
> I think you should be able to avoid constructing the initializer twice if you restructure the code a bit to just construct the global before the call to BuildVTablePointer. I added GlobalVariable::replaceInitializer because I was looking at this review: it lets you construct the global before the initializer, without having to do awkward things with RAUW.

@efriedma-quic Sorry, I'm not sure if I got your point correctly.

The issue with enabling address discrimination for signed vtable pointers is that it requires self-references - see, for example, llvm/test/CodeGen/AArch64/ptrauth-type-info-vptr-discr.ll:

```
@_ZTI10TestStruct = constant { ptr, ptr } {
  ptr ptrauth (
    ptr getelementptr inbounds ( ; <== raw unsigned pointer
      ptr,
      ptr @_ZTVN10__cxxabiv117__class_type_infoE,
      i64 2),
    i32 2,                       ; <== key
    i64 [[STDTYPEINFO_DISC]],    ; <== constant discr
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ptr @_ZTI10TestStruct),      ; <== address discr
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ptr @_ZTS10TestStruct
}
```

As far as I understand, the correct way of creating such structures which contain self-references, is to use `ConstantInitBuilder` and `getAddrOfCurrentPosition`. As far as I see from its source code, it handles self-references specially. With `ConstantInitBuilder`, we'll not end up with a vector of elements to be passed as struct initializer (`Fields` in our case) - instead, we'll need to call `finishAndSetAsInitializer` on the builder object.

As for `replaceInitializer` - sure, we can use it in existing code below, where we have `if (OldGV) { /* ... */ }`. But I'm not sure how it this newly proposed function can help us in context of this particular patch.

Do I miss smth? Can we somehow differently handle self-references and avoid using `ConstantInitBuilder`? Thanks in advance!

**Comment by efriedma-quic** [comment]
getAddrOfCurrentPosition() is one way to do it... but it's not the only way to do it.  It was specifically designed to handle cases in CGExprConstant that would have been difficult to refactor otherwise.

Here, it's simple to compute the correct address beforehand, so you can just do that.

**Comment by kovdan01** [comment]
@efriedma-quic I've switched to `replaceInitializer`, thanks for suggestion! Now we construct `GV` with `nullptr` as initializer and `llvm::ConstantStruct::getTypeForElements(Fields)` as type, and then replace the initializer with `llvm::ConstantStruct::getAnon(Fields)`. See 55fc2c822f8f543d335e443a13860ae72fb5ce6d

File: clang/lib/CodeGen/ItaniumCXXABI.cpp [hunk 3]
```diff
@@ -4207,16 +4214,31 @@ llvm::Constant *ItaniumRTTIBuilder::BuildTypeInfo(
...
   SmallString<256> Name;
   llvm::raw_svector_ostream Out(Name);
   CGM.getCXXABI().getMangleContext().mangleCXXRTTI(Ty, Out);
   llvm::Module &M = CGM.getModule();
   llvm::GlobalVariable *OldGV = M.getNamedGlobal(Name);
-  llvm::GlobalVariable *GV =
-      new llvm::GlobalVariable(M, Init->getType(),
-                               /*isConstant=*/true, Linkage, Init, Name);
+  llvm::GlobalVariable *GV = new llvm::GlobalVariable(
+      M, llvm::ConstantStruct::getTypeForElements(Fields),
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/ItaniumCXXABI.cpp:4223]: Since you're going to replace the initializer anyway, you don't need to call ConstantStruct::getTypeForElements here; you can just use an arbitrary type, like i8.  That should allow you to pass the global into BuildVTablePointer(), instead of replacing it later.

Comment (kovdan01) [reply clang/lib/CodeGen/ItaniumCXXABI.cpp]: @efriedma-quic Thanks for suggestion! Followed this way in b08172fa576e5bb7849aa13d503180cfef5bcd0b. This actually changes order of globals definitions in output IR and requires changing related tests correspondingly (see c9d26dd6dd7648c25e44e576891e838a418eacae), but, as far as I understand, this should not cause any problems.

**Review by efriedma-quic — APPROVED** [review]
LGTM
