### PR TITLE
[DebugInfo][LoopLoadElim] Fix missing debug location updates

### LINKED ISSUE #91836: [DebugInfo][LoopLoadElim] Missing debug location updates
Missing debug location updates for new instructions at LoopLoadElimination[-L447](https://github.com/llvm/llvm-project/blob/e62ce1f8842cca36eb14126d79dcca0a85bf6d36/llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp#L447), [-L452](https://github.com/llvm/llvm-project/blob/e62ce1f8842cca36eb14126d79dcca0a85bf6d36/llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp#L452), [-L466](https://github.com/llvm/llvm-project/blob/e62ce1f8842cca36eb14126d79dcca0a85bf6d36/llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp#L466).

```cpp
->  Value *Initial =
        new LoadInst(Cand.Load->getType(), InitialPtr, "load_initial",
                     /* isVolatile */ false, Cand.Load->getAlign(),
                     PH->getTerminator()->getIterator());

->  PHINode *PHI = PHINode::Create(Initial->getType(), 2, "store_forwarded");
    PHI->insertBefore(L->getHeader()->begin());
    PHI->addIncoming(Initial, PH);

    ...

    Value *StoreValue = Cand.Store->getValueOperand();
    if (LoadType != StoreType)
->    StoreValue = CastInst::CreateBitOrPointerCast(StoreValue, LoadType,
                                                    "store_forward_cast",
                                                    Cand.Store->getIterator());

    PHI->addIncoming(StoreValue, L->getLoopLatch());

    Cand.Load->replaceAllUsesWith(PHI);
```

I'll give a patch for this later.

### PR DESCRIPTION
**Pull request by Apochens**
Fix #91836 .

For [LoopLoadElim-L447](https://github.com/llvm/llvm-project/blob/e62ce1f8842cca36eb14126d79dcca0a85bf6d36/llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp#L447) (`Initial`), its debug location should be dropped, because it is inserted in the loop's preheater, which is out of the loop. Since `Initial` has an empty debug location when being created, I just add a comment to explicitly point out this case and do nothing with its debug location.

All the three updates are checked in the new test.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp [hunk 1]
```diff
@@ -448,6 +448,10 @@ class LoadEliminationForLoop {
         new LoadInst(Cand.Load->getType(), InitialPtr, "load_initial",
                      /* isVolatile */ false, Cand.Load->getAlign(),
                      PH->getTerminator()->getIterator());
+    // We don't give any debug location to Initial, because it is inserted
+    // into the loop's preheader. A debug location inside the loop will cause
+    // a misleading stepping when debugging. The test preserving-debugloc-store
```
Comment (jryans) [inline llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:453]: Hmm, is this an existing test somewhere? Or maybe it's meant to be attached to this PR...? I don't see it in the file list currently.

Comment (Apochens) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:453]: Oh, I made a mistake here :(. I forgot to make the test name consistent after I renamed the attached test (I changed the name from "preserving-" to "update-", because there is a drop for the `Initial`). I'll fix it.

File: llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp [hunk 2]
```diff
@@ -462,14 +466,20 @@ class LoadEliminationForLoop {
...
+      // Because it casts the old `load` value and is used by the new `phi`
+      // which replaces the old `load`, we give the `load`'s debug location
+      // to it.
+      cast<Instruction>(StoreValue)->setDebugLoc(Cand.Load->getDebugLoc());
+    }
 
     PHI->addIncoming(StoreValue, L->getLoopLatch());
 
     Cand.Load->replaceAllUsesWith(PHI);
+    PHI->setDebugLoc(Cand.Load->getDebugLoc());
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: This is an interesting case. When promoting store/loads I think we usually give phis a debugloc from the store (or if it's from stores, plural, it's a merged location). At least that's what we do in mem2reg. I think in this case using the `load`'s DebugLoc makes intuitive sense - we're just eliminating the load here after all, but I'd be interested to hear what others think about this case too (cc @SLTozer , @adrian-prantl , @dwblaikie, @jryans - there's a comment at the top of the function that explains the transformation) and what you make of this @Apochens?

**Review by OCHyams — COMMENTED** [review]
Thanks for the patch!

Test LGTM. There are just a couple of minor nits and a question about the phi location to address.

File: llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp (hunk 2 above)
Comment (jryans) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: Using the load's location here does make intuitive sense to me as well. I'm less sure what we've done for such cases historically though, so I'm interested to hear what others think as well.

Comment (Apochens) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: > I think in this case using the load's DebugLoc makes intuitive sense - we're just eliminating the load here after all

That's what I agree with. 

> When promoting store/loads I think we usually give phis a debugloc from the store (or if it's from stores, plural, it's a merged location).

I'd like to know why give the store'd debug location to an instruction that replaces a load instruction. Are there some conventions or something?

Comment (Apochens) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: Hmm, should we ping other guys again? 🤔

Comment (jryans) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: Probably best to wait a few more days first, as people may be on holiday or have a long queue to work through.

Comment (jryans) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:482]: Seems like enough of us have appeared and all concluded the same thing here, so I think we can leave this part as it is.

**Comment by jryans** [comment]
Once the remaining review comments are addressed, I imagine this can be approved. 🙂

File: llvm/test/Transforms/LoopLoadElim/update_debugloc_store_forwarded.ll [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+;   }
+
+define void @f(ptr noalias %A, ptr noalias %B, ptr noalias %C, i64 %N) !dbg !5 {
+; CHECK-LABEL: define void @f(
+; CHECK-NEXT:  entry:
+; CHECK-NEXT:    [[LOAD_INITIAL:%.*]] = load float, ptr {{.*}}, align 4{{$}}
+; CHECK:       for.body:
+; CHECK-NEXT:    [[STORE_FORWARDED:%.*]] = phi float [ [[LOAD_INITIAL]], %entry ], [ [[STORE_FORWARD_CAST:%.*]], %for.body ], !dbg [[DBG9:![0-9]+]]
+; CHECK:         [[STORE_FORWARD_CAST]] = bitcast i32 {{.*}} to float, !dbg [[DBG9]]
+; CHECK:       [[DBG9]] = !DILocation(line: 11,
```
[the remark this answers is not in the document]
Comment (Apochens) [reply llvm/test/Transforms/LoopLoadElim/update_debugloc_store_forwarded.ll:31]: `DBG9` catches the "!" since `[[DBG9:![0-9]+]]` is used. 🤔

File: llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp [hunk 4]
```diff
@@ -448,6 +448,10 @@ class LoadEliminationForLoop {
         new LoadInst(Cand.Load->getType(), InitialPtr, "load_initial",
                      /* isVolatile */ false, Cand.Load->getAlign(),
                      PH->getTerminator()->getIterator());
+    // We don't give any debug location to Initial, because it is inserted
+    // into the loop's preheader. A debug location inside the loop will cause
+    // a misleading stepping when debugging. The test update-debugloc-store
+    // -forwarded.ll checks this.
```
[the remark this answers is not in the document]
Comment (Apochens) [reply llvm/lib/Transforms/Scalar/LoopLoadElimination.cpp:454]: I changed underscores in the test name to hyphens.

**Review by OCHyams — APPROVED** [review]
As @jryans mentions in the inline comments, it looks like we've reached a consensus that the eliminated `load`'s debug location is indeed suitable for the `phi`. If someone comes back to this and strongly disagrees we can look at it again and make adjustments as necessary.

LGTM, thanks!

**Review by jryans — APPROVED** [review]
Looks good to me as well! 😄 

As usual, I'll wait a day in case any last minute review comments might appear, and then assuming they do not, I'll merge this.
