### PR TITLE
[clang][AST] fix lack comparison of declRefExpr in ASTStructuralEquivalence

### LINKED ISSUE #66047: [clang][AST] fix lack comparison of declRefExpr in ASTStructuralEquivalence
fixed in #66041

Before fix,the following testcase expected true. While I think only comparison of declName is not sufficient.Thanks for giving suggestions.
```cpp
TEST_F(StructuralEquivalenceStmtTest, DeclRefENoEq) {
  std::string Prefix = "enum Test { AAA, BBB };";
  auto t = makeStmts(
      Prefix + "void foo(int i) {if (i > 0) {i = AAA;} else {i = BBB;}}",
      Prefix + "void foo(int i) {if (i > 0) {i = BBB;} else {i = AAA;}}",
      Lang_CXX03, ifStmt());
  EXPECT_FALSE(testStructuralMatch(t)); // EXPECT_TRUE
}
```

### PR DESCRIPTION
**Pull request by mzyKi**
Fixes #66047
Before fix,the following testcase expected true. While I think only comparison of declName is not sufficient.Thanks for giving suggestions.
```cpp
TEST_F(StructuralEquivalenceStmtTest, DeclRefENoEq) {
  std::string Prefix = "enum Test { AAA, BBB };";
  auto t = makeStmts(
      Prefix + "void foo(int i) {if (i > 0) {i = AAA;} else {i = BBB;}}",
      Prefix + "void foo(int i) {if (i > 0) {i = BBB;} else {i = AAA;}}",
      Lang_CXX03, ifStmt());
  EXPECT_FALSE(testStructuralMatch(t)); // EXPECT_TRUE
}
```

### CODE REVIEW

File: clang/lib/AST/ASTStructuralEquivalence.cpp [hunk 1]
```diff
@@ -214,6 +214,14 @@ class StmtComparer {
     return E1->size() == E2->size();
   }
 
+  bool IsStmtEquivalent(const DeclRefExpr *DRE1, const DeclRefExpr *DRE2) {
+    if (nullptr == DRE1->getDecl() || nullptr == DRE2->getDecl()) {
```
Comment (cor3ntin) [inline clang/lib/AST/ASTStructuralEquivalence.cpp:218]:
```suggestion
    if (!DRE1->getDecl() || !DRE2->getDecl()) {
```

File: clang/lib/AST/ASTStructuralEquivalence.cpp [hunk 2]
```diff
@@ -214,6 +214,14 @@ class StmtComparer {
...
+      return false;
+    }
+    return IsStructurallyEquivalent(Context, DRE1->getDecl()->getDeclName(),
```
Comment (cor3ntin) [inline clang/lib/AST/ASTStructuralEquivalence.cpp:221]: Shouldn't that simply be `IsStructurallyEquivalent(DRE1->getDecl(), DRE2->getDecl())` ?

**Review by cor3ntin — CHANGES_REQUESTED** [review]
Thanks for working on that!
Can you explain why you are comparing declaration only with their name? that seems suspicious to me. Otherwise, I think the intent of the change is correct

**Comment by cor3ntin** [comment]
You should edit `clang/docs/ReleaseNotes.rst`, indicating that https://github.com/llvm/llvm-project/issues/66047 was fixed, 
and edit the description of the PR with `Fixes #66047` so that it gets closed automatically.

Otherwise LGTM

File: clang/lib/AST/ASTStructuralEquivalence.cpp (hunk 2 above)
Comment (mzyKi) [reply clang/lib/AST/ASTStructuralEquivalence.cpp]: Thanks for review, now I have taken your suggestions.When I develop in llvm 13,```static bool IsStructurallyEquivalent(StructuralEquivalenceContext &Context,Decl *D1, Decl *D2)``` this function do not give me expected result. Maybe now this updated, I will find changes between two versions after

File: clang/lib/AST/ASTStructuralEquivalence.cpp [hunk 3]
```diff
@@ -214,6 +214,16 @@ class StmtComparer {
     return E1->size() == E2->size();
   }
 
+  bool IsStmtEquivalent(const DeclRefExpr *DRE1, const DeclRefExpr *DRE2) {
+    auto *Decl1 = DRE1->getDecl();
+    auto *Decl2 = DRE2->getDecl();
```
Comment (cor3ntin) [inline clang/lib/AST/ASTStructuralEquivalence.cpp:219]: actually you can make these `const`, and then you won't need the `const_cast`s

Comment (mzyKi) [reply clang/lib/AST/ASTStructuralEquivalence.cpp:219]:
```cpp
/// Determine structural equivalence of two declarations.
static bool IsStructurallyEquivalent(StructuralEquivalenceContext &Context,
                                     Decl *D1, Decl *D2) {
  // FIXME: Check for known structural equivalences via a callback of some sort.

  D1 = D1->getCanonicalDecl();
  D2 = D2->getCanonicalDecl();
  std::pair<Decl *, Decl *> P{D1, D2};
```
```IsStructurallyEquivalent``` only accept pointer without const qualifier.

File: clang/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -218,6 +218,8 @@ Bug Fixes in This Version
   (`#65156 <https://github.com/llvm/llvm-project/issues/65156>`_)
 - Clang no longer considers the loss of ``__unaligned`` qualifier from objects as
   an invalid conversion during method function overload resolution.
+- Fix lack of comparison of declRefExpr in ASTStructuralEquivalence
+  (`#66047 <https://github.com/llvm/llvm-project/issues/66047>`_`)
```
Comment (danix800) [inline clang/docs/ReleaseNotes.rst:222]:
```suggestion
  (`#66047 <https://github.com/llvm/llvm-project/issues/66047>`_)
```

File: clang/unittests/AST/StructuralEquivalenceTest.cpp [hunk 5]
```diff
@@ -2320,5 +2320,14 @@ TEST_F(StructuralEquivalenceStmtTest, UnresolvedLookup) {
   EXPECT_TRUE(testStructuralMatch(t));
 }
 
+TEST_F(StructuralEquivalenceStmtTest, DeclRefENoEq) {
```
Comment (danix800) [inline clang/unittests/AST/StructuralEquivalenceTest.cpp:2323]:
```suggestion
TEST_F(StructuralEquivalenceStmtTest, DeclRefExpr) {
```

**Comment by danix800** [comment]
LGTM! If no further comment I'll merge this in a day or two.
