### PR TITLE
[HLSL] Don't invoke `dxv` from `clang-dxc` for text output

### LINKED ISSUE #135874: [HLSL] clang-dxc emits dxv related warnings and errors when compiling to textual DXIL
Running something like `clang-dxc.exe -T cs_6_2 x.hlsl` does one of two silly things, depending on whether `dxv` is on your path:
- warning: dxv not found; resulting DXIL will not be validated
- error: dxv command failed with exit code 1

The former makes sense when generating a binary (ie, with `-Fo out.dxil`), but it doesn't really make sense when we're generating text since the validator needs a binary anyway. The latter is even sillier, and results in all compiles to textual IR to fail if `dxv` is on your path.

We should only attempt to run `dxv` from the driver when emitting an object.

### PR DESCRIPTION
**Pull request by bogner**
Running `clang-dxc` with textual output was emitting various spurious warnings (if `dxv` wasn't on your path) or errors (if it was). Avoid these by not attempting to run this tool when it doesn't make sense to do so.

Fixes #135874.

### CODE REVIEW

File: clang/lib/Driver/ToolChains/HLSL.cpp [hunk 1]
```diff
@@ -309,6 +309,9 @@ HLSLToolChain::TranslateArgs(const DerivedArgList &Args, StringRef BoundArch,
 }
 
 bool HLSLToolChain::requiresValidation(DerivedArgList &Args) const {
+  if (!Args.hasArg(options::OPT_dxc_Fo))
+    return false;
```
Comment (damyanp) [inline clang/lib/Driver/ToolChains/HLSL.cpp:313]: Doesn't this happen for most of our tests?  I thought we'd want validation to generally always be running?

Comment (bogner) [reply clang/lib/Driver/ToolChains/HLSL.cpp:313]: I'm not sure I understand what you mean. The validator runs on the binary dxil container - if we're just emitting textual dxil then there's nothing we can run the validator on. Currently what happens in that case is that we attempt to run the validator but it falls over because the input isn't something it understands.

that is,
```
$ ./bin/clang-dxc.exe -T cs_6_2 -Fc x.s e:/tmp/x.hlsl
shader: expected top-level entity
source_filename = "E:/tmp/x.hlsl"
^

clang-dxc: error: dxv command failed with exit code 1 (use -v to see invocation)
```

or if we just output to stdout:
```
$ ./bin/clang-dxc.exe -T cs_6_2 e:/tmp/x.hlsl  >/dev/null
...
The system cannot find the file specified. -
clang-dxc: error: dxv command failed with exit code 1 (use -v to see invocation)
```

Comment (damyanp) [reply clang/lib/Driver/ToolChains/HLSL.cpp:313]: Thanks for explaining!

**Review by damyanp — APPROVED** [review]

**Review by Icohedron — APPROVED** [review]
This is great! Now I don't have to specify `-Vd` when I run clang-dxc without `-Fo` :)

**Comment by mstorsjo** [comment]
These tests that run `env PATH="" %clang_dxc ...` are problematic for my setup for running tests on Windows.

In my builds, I'm building with a dynamically linked `libc++.dll` provided by my toolchain, which is available in `$PATH`, so the built `bin/clang.exe` requires finding this `libc++.dll` when executed. Normally this works fine, but when invoking tests that do `env PATH="" %clang ...` then `%clang` will run in an environment where it no longer finds its required `libc++.dll` in `$PATH`, and thus fails.

Previously, we've waived such issues by omitting that kind of tests on Windows (where setting `PATH` also affects where dependent libraries are found) by wrapping `%if !system-windows %{ ... %}` around those bits - see f5a93c5f2a4d0916c975bbf028768d58a29b6b73.

Would you find it ok to do the same here? As these tests relate to HLSL, they're a bit more relevant for running on Windows, but tests clearing `PATH` are problematic for builds with a dynamically linked dependency, unfortunately.

**Comment by mstorsjo** [comment]
I guess another way about it, is to require me to copy in all dependent DLLs into the built `bin` directory next to `clang.exe` etc. But that's an extra step that hasn't been needed so far...

**Comment by mstorsjo** [comment]
> These tests that run `env PATH="" %clang_dxc ...` are problematic for my setup for running tests on Windows.
> 
> In my builds, I'm building with a dynamically linked `libc++.dll` provided by my toolchain, which is available in `$PATH`, so the built `bin/clang.exe` requires finding this `libc++.dll` when executed. Normally this works fine, but when invoking tests that do `env PATH="" %clang ...` then `%clang` will run in an environment where it no longer finds its required `libc++.dll` in `$PATH`, and thus fails.
> 
> Previously, we've waived such issues by omitting that kind of tests on Windows (where setting `PATH` also affects where dependent libraries are found) by wrapping `%if !system-windows %{ ... %}` around those bits - see [f5a93c5](https://github.com/llvm/llvm-project/commit/f5a93c5f2a4d0916c975bbf028768d58a29b6b73).

Ping - any opinion on the above?

In theory, we'd have the same issue also for MSVC/clang-cl based builds with `/MD` (or `CMAKE_MSVC_RUNTIME_LIBRARY= MultiThreadedDLL`) - however there, the compiler support DLLs are found in systemwide default paths, so they're found even if running with a cleared `PATH` variable.

I've worked around this issue on my end for now by just manually copying in the host compiler DLL dependencies into the `bin` build directory before running tests. It works but it's not very pretty. (But if we deem this to be the way to go going forward, we should probably revert f5a93c5f2a4d0916c975bbf028768d58a29b6b73 as well.)
