### PR TITLE
[mlir][OpenMP] Fix teams reduction assert with sibling distributes

### LINKED ISSUE #191470: [mlir][OpenMP] Multiple distrubte region under teams reduction triggers "double mapValue assert"
```fortran
program repro_min_teams_reduction
  implicit none

  integer :: i
  real(8) :: total

  total = 0.0d0

  !$omp teams reduction(+:total)

  !$omp distribute parallel do
  do i = 1, 1
  end do

  !$omp distribute parallel do reduction(+:total)
  do i = 1, 1
    total = total + 1.0d0
  end do
  !$omp end teams
end program repro_min_teams_reduction
```

Error message:
```
flang -fopenmp -fopenmp-version=40 repro.f90
warning: OpenMP support for version 40 in flang is still incomplete
flang: /ptmp/cchen/chichun-llvm-project/mlir/include/mlir/Target/LLVMIR/ModuleTranslation.h:90: llvm::Value*& mlir::LLVM::ModuleTranslation::mapValue(mlir::Value): Assertion `llvm == nullptr && "attempting to map a value that is already mapped"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: /hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/bin/flang -fc1 -triple aarch64-suse-linux -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +outline-atomics -target-feature +v8a -ta
rget-feature +fp-armv8 -target-feature +neon -fopenmp -fopenmp-version=40 -resource-dir /hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/clang/23 -mframe-pointer=non-leaf-no-reserve -o /tmp/repro-189e57.o -x f95 repro.f90
 #0 0x0000ffffb8770e70 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libLLVMSupport.so.23.0git+0x1f0e70)
 #1 0x0000ffffb876e3d8 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x0000ffffba5d37c0 (linux-vdso.so.1+0x7c0)
 #3 0x0000ffffb80d89d8 __pthread_kill_implementation (/lib64/libc.so.6+0x889d8)
 #4 0x0000ffffb808f32c gsignal (/lib64/libc.so.6+0x3f32c)
 #5 0x0000ffffb807ad40 abort (/lib64/libc.so.6+0x2ad40)
 #6 0x0000ffffb8088a2c __assert_fail_base (/lib64/libc.so.6+0x38a2c)
 #7 0x0000ffffb8088a9c (/lib64/libc.so.6+0x38a9c)
 #8 0x0000ffffa22605e4 mlir::LLVM::ModuleTranslation::mapValue(mlir::Value) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIROpenMPToLLVMIRTranslation.so.23.0git+0x305e4)
 #9 0x0000ffffa22720b0 llvm::LogicalResult allocAndInitializeReductionVars<mlir::omp::TeamsOp>(mlir::omp::TeamsOp, llvm::ArrayRef<mlir::BlockArgument>, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&, llvm::IRBuilderBase::InsertPoint&, llvm::SmallVectorImpl<mlir::omp::DeclareReduc
tionOp>&, llvm::SmallVectorImpl<llvm::Value*>&, llvm::DenseMap<mlir::Value, llvm::Value*, llvm::DenseMapInfo<mlir::Value, void>, llvm::detail::DenseMapPair<mlir::Value, llvm::Value*>>&, llvm::ArrayRef<bool>) OpenMPToLLVMIRTranslation.cpp:0:0
#10 0x0000ffffa22869fc convertOmpDistribute(mlir::Operation&, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) OpenMPToLLVMIRTranslation.cpp:0:0
#11 0x0000ffffa2291ccc (anonymous namespace)::OpenMPDialectLLVMIRTranslationInterface::convertOperation(mlir::Operation*, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) const OpenMPToLLVMIRTranslation.cpp:0:0
#12 0x0000ffffad0f01a4 mlir::LLVM::ModuleTranslation::convertOperation(mlir::Operation&, llvm::IRBuilderBase&, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x301a4)
#13 0x0000ffffad0f233c mlir::LLVM::ModuleTranslation::convertBlockImpl(mlir::Block&, bool, llvm::IRBuilderBase&, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x3233c)
#14 0x0000ffffa226ee8c convertOmpOpRegions(mlir::Region&, llvm::StringRef, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&, llvm::SmallVectorImpl<llvm::PHINode*>*) OpenMPToLLVMIRTranslation.cpp:0:0
#15 0x0000ffffa228b5cc convertOmpParallel(mlir::omp::ParallelOp, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&)::'lambda'(llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint)::operator()(llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint) const (.i
sra.0) OpenMPToLLVMIRTranslation.cpp:0:0
#16 0x0000ffffa228d13c llvm::Error llvm::function_ref<llvm::Error (llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint)>::callback_fn<convertOmpParallel(mlir::omp::ParallelOp, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&)::'lambda'(llvm::IRBuilderBase::InsertPoin
t, llvm::IRBuilderBase::InsertPoint)>(long, llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint) OpenMPToLLVMIRTranslation.cpp:0:0
#17 0x0000ffffa8404784 llvm::OpenMPIRBuilder::createParallel(llvm::OpenMPIRBuilder::LocationDescription const&, llvm::IRBuilderBase::InsertPoint, llvm::function_ref<llvm::Error (llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint)>, llvm::function_ref<llvm::Expected<llvm
::IRBuilderBase::InsertPoint> (llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint, llvm::Value&, llvm::Value&, llvm::Value*&)>, std::function<llvm::Error (llvm::IRBuilderBase::InsertPoint)>, llvm::Value*, llvm::Value*, llvm::omp::ProcBindKind, bool) (/hpcdc/project/pe_u
sers/cchen/llvm-install/pe35hopper/release/lib/libLLVMFrontendOpenMP.so.23.0git+0x94784)
#18 0x0000ffffa227efe4 convertOmpParallel(mlir::omp::ParallelOp, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) OpenMPToLLVMIRTranslation.cpp:0:0
#19 0x0000ffffa2291000 (anonymous namespace)::OpenMPDialectLLVMIRTranslationInterface::convertOperation(mlir::Operation*, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) const OpenMPToLLVMIRTranslation.cpp:0:0
#20 0x0000ffffad0f01a4 mlir::LLVM::ModuleTranslation::convertOperation(mlir::Operation&, llvm::IRBuilderBase&, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x301a4)
#21 0x0000ffffad0f233c mlir::LLVM::ModuleTranslation::convertBlockImpl(mlir::Block&, bool, llvm::IRBuilderBase&, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x3233c)
#22 0x0000ffffa226ee8c convertOmpOpRegions(mlir::Region&, llvm::StringRef, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&, llvm::SmallVectorImpl<llvm::PHINode*>*) OpenMPToLLVMIRTranslation.cpp:0:0
#23 0x0000ffffa228e164 llvm::Error llvm::function_ref<llvm::Error (llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint)>::callback_fn<convertOmpTeams(mlir::omp::TeamsOp, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&)::'lambda'(llvm::IRBuilderBase::InsertPoint, llv
m::IRBuilderBase::InsertPoint)>(long, llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint) OpenMPToLLVMIRTranslation.cpp:0:0
#24 0x0000ffffa83f0864 llvm::OpenMPIRBuilder::createTeams(llvm::OpenMPIRBuilder::LocationDescription const&, llvm::function_ref<llvm::Error (llvm::IRBuilderBase::InsertPoint, llvm::IRBuilderBase::InsertPoint)>, llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*) (/hpcdc/project/pe_
users/cchen/llvm-install/pe35hopper/release/lib/libLLVMFrontendOpenMP.so.23.0git+0x80864)
#25 0x0000ffffa2286c78 convertOmpTeams(mlir::omp::TeamsOp, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) OpenMPToLLVMIRTranslation.cpp:0:0
#26 0x0000ffffa22919b8 (anonymous namespace)::OpenMPDialectLLVMIRTranslationInterface::convertOperation(mlir::Operation*, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) const OpenMPToLLVMIRTranslation.cpp:0:0
#27 0x0000ffffad0f01a4 mlir::LLVM::ModuleTranslation::convertOperation(mlir::Operation&, llvm::IRBuilderBase&, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x301a4)
#28 0x0000ffffad0fa9bc mlir::LLVM::ModuleTranslation::convertOneFunction(mlir::LLVM::LLVMFuncOp) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x3a9bc)
#29 0x0000ffffad0fc1a0 mlir::LLVM::ModuleTranslation::convertFunctions() (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x3c1a0)
#30 0x0000ffffad104d88 mlir::translateModuleToLLVMIR(mlir::Operation*, llvm::LLVMContext&, llvm::StringRef, bool) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libMLIRTargetLLVMIRExport.so.23.0git+0x44d88)
#31 0x0000ffffba14782c Fortran::frontend::CodeGenAction::generateLLVMIR() (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libflangFrontend.so.23.0git+0x10782c)
#32 0x0000ffffba14af98 Fortran::frontend::CodeGenAction::executeAction() (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libflangFrontend.so.23.0git+0x10af98)
#33 0x0000ffffba1355fc Fortran::frontend::FrontendAction::execute() (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libflangFrontend.so.23.0git+0xf55fc)
#34 0x0000ffffba065e88 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libflangFrontend.so.23.0git+0x25e88)
#35 0x0000ffffba51690c Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/lib/libflangFrontendTool.so.23.0git+0x690c)
#36 0x0000000000405640 fc1_main(llvm::ArrayRef<char const*>, char const*) (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/bin/flang+0x405640)
#37 0x0000000000403b64 main (/hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/bin/flang+0x403b64)
#38 0x0000ffffb807b404 __libc_start_call_main (/lib64/libc.so.6+0x2b404)
#39 0x0000ffffb807b4d8 __libc_start_main@GLIBC_2.17 (/lib64/libc.so.6+0x2b4d8)
#40 0x0000000000404570 _start /home/abuild/rpmbuild/BUILD/glibc-2.38/csu/../sysdeps/aarch64/start.S:101:0
flang-23: error: unable to execute command: Aborted (core dumped)
flang-23: error: flang frontend command failed with exit code -2 (use -v to see invocation)
flang version 23.0.0git (https://github.com/llvm/llvm-project.git 6fe792de2308be936beafd5688fdc6f634dd46f8)
Target: aarch64-suse-linux
Thread model: posix
InstalledDir: /hpcdc/project/pe_users/cchen/llvm-install/pe35hopper/release/bin
Build config: +assertions
flang-23: note: diagnostic msg:
********************
```

### PR DESCRIPTION
**Pull request by chichunchen**
Avoid double-mapping teams reduction block arguments when multiple sibling `omp.distribute` ops appear under the same `omp.teams`.

Replace `teamsReductionContainedInDistribute` with `getDistributeCapturingTeamsReduction`, which returns the unique `omp::DistributeOp` containing all non-debug uses of the teams reduction block arguments, or null if no such distribute exists. In that case, reduction setup falls back to the teams op.

This ensures only the owning distribute handles reduction setup and prevents `moduleTranslation.mapValue()` from being called multiple times for the same block arguments.

Fixes https://github.com/llvm/llvm-project/issues/191470

Assisted with Copilot and GPT-5.4

### CODE REVIEW

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 1]
```diff
@@ -1981,13 +1981,25 @@ convertOmpSingle(omp::SingleOp &singleOp, llvm::IRBuilderBase &builder,
...
+static omp::DistributeOp
+getDistributeCapturingTeamsReduction(omp::TeamsOp teamsOp) {
+  // Early return if we found more than one distribute op or if we can't find
+  // any distribute op in the teams region.
+  omp::DistributeOp distOp;
+  WalkResult walk = teamsOp.getRegion().walk([&](omp::DistributeOp op) {
+    if (distOp)
+      return WalkResult::interrupt();
+    distOp = op;
+    return WalkResult::advance();
```
Comment (skatrak) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]: I don't think there's a reason to go over the contents of an `omp.distribute` region here.
```suggestion
    return WalkResult::skip();
```

File: mlir/test/Target/LLVMIR/openmp-teams-distribute-reduction.mlir
Comment (skatrak) [inline mlir/test/Target/LLVMIR/openmp-teams-distribute-reduction.mlir:1]: The removed CHECK lines should be re-added, wherever the reduction function is expected to be found now (probably after `@teams_reduction_multiple_distribute_`).

**Review by skatrak — COMMENTED** [review]
Thank you for this work, just minor comments from me.

**Review by skatrak — APPROVED** [review]
LGTM, thank you!
