### PR TITLE
[ValueTracking] Improve `Bitcast` handling to match SDAG

### LINKED ISSUE #125228: [ValueTracking] computeKnownBitsFromOperator - improve Instruction::BitCast handling to match SelectionDAG
The middle end computeKnownBitsFromOperator can merge bitcasts from narrow vector elements to wider types, but fails to perform this in the reverse case:

https://github.com/llvm/llvm-project/blob/85d417564b5f959f7434f2657cc9e1ab3575311f/llvm/lib/Analysis/ValueTracking.cpp#L1328:L1361

The SelectionDAG implementation handles both so hopefully its just a case of reusing the additional code over and adding any missing test coverage:

https://github.com/llvm/llvm-project/blob/46befd720995647485c516ba94a49eee5548283a/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L3662:L3706

### PR DESCRIPTION
**Pull request by abhishek-kaushik22**
Closes #125228

### CODE REVIEW

**Comment by abhishek-kaushik22** [comment]
@RKSimon Can you please help me with some more tests? I only have this one from I got from the C code you provided in the issue (compiled with O0).

```llvm
define dso_local noundef <2 x i64> @shift64(<2 x i64> noundef %v, <2 x i64> noundef %s) {
entry:
  %__q1.addr.i = alloca i64, align 8
  %__q0.addr.i = alloca i64, align 8
  %.compoundliteral.i = alloca <2 x i64>, align 16
  %__a.addr.i13 = alloca <2 x i64>, align 16
  %__a.addr.i12 = alloca <2 x i64>, align 16
  %__a.addr.i11 = alloca <2 x double>, align 16
  %__a.addr.i9 = alloca <2 x i64>, align 16
  %__count.addr.i10 = alloca <2 x i64>, align 16
  %__a.addr.i8 = alloca <2 x i64>, align 16
  %__count.addr.i = alloca <2 x i64>, align 16
  %__q.addr.i = alloca i64, align 8
  %__a.addr.i = alloca <2 x i64>, align 16
  %__b.addr.i = alloca <2 x i64>, align 16
  %v.addr = alloca <2 x i64>, align 16
  %s.addr = alloca <2 x i64>, align 16
  %x_ = alloca <2 x i64>, align 16
  %_y = alloca <2 x i64>, align 16
  %xy = alloca <2 x i64>, align 16
  store <2 x i64> %v, ptr %v.addr, align 16
  store <2 x i64> %s, ptr %s.addr, align 16
  %0 = load <2 x i64>, ptr %s.addr, align 16
  store i64 63, ptr %__q.addr.i, align 8
  %1 = load i64, ptr %__q.addr.i, align 8
  %2 = load i64, ptr %__q.addr.i, align 8
  store i64 %1, ptr %__q1.addr.i, align 8
  store i64 %2, ptr %__q0.addr.i, align 8
  %3 = load i64, ptr %__q0.addr.i, align 8
  %vecinit.i = insertelement <2 x i64> poison, i64 %3, i32 0
  %4 = load i64, ptr %__q1.addr.i, align 8
  %vecinit1.i = insertelement <2 x i64> %vecinit.i, i64 %4, i32 1
  store <2 x i64> %vecinit1.i, ptr %.compoundliteral.i, align 16
  %5 = load <2 x i64>, ptr %.compoundliteral.i, align 16
  store <2 x i64> %0, ptr %__a.addr.i, align 16
  store <2 x i64> %5, ptr %__b.addr.i, align 16
  %6 = load <2 x i64>, ptr %__a.addr.i, align 16
  %7 = load <2 x i64>, ptr %__b.addr.i, align 16
  %and.i = and <2 x i64> %6, %7
  store <2 x i64> %and.i, ptr %s.addr, align 16
  %8 = load <2 x i64>, ptr %v.addr, align 16
  %9 = load <2 x i64>, ptr %s.addr, align 16
  store <2 x i64> %8, ptr %__a.addr.i9, align 16
  store <2 x i64> %9, ptr %__count.addr.i10, align 16
  %10 = load <2 x i64>, ptr %__a.addr.i9, align 16
  %11 = load <2 x i64>, ptr %__count.addr.i10, align 16
  %12 = call noundef <2 x i64> @llvm.x86.sse2.psll.q(<2 x i64> %10, <2 x i64> %11)
  store <2 x i64> %12, ptr %x_, align 16
  %13 = load <2 x i64>, ptr %v.addr, align 16
  %14 = load <2 x i64>, ptr %s.addr, align 16
  %cast = bitcast <2 x i64> %14 to <16 x i8>
  %psrldq = shufflevector <16 x i8> %cast, <16 x i8> zeroinitializer, <16 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %cast3 = bitcast <16 x i8> %psrldq to <2 x i64>
  store <2 x i64> %13, ptr %__a.addr.i8, align 16
  store <2 x i64> %cast3, ptr %__count.addr.i, align 16
  %15 = load <2 x i64>, ptr %__a.addr.i8, align 16
  %16 = load <2 x i64>, ptr %__count.addr.i, align 16
  %17 = call noundef <2 x i64> @llvm.x86.sse2.psll.q(<2 x i64> %15, <2 x i64> %16)
  store <2 x i64> %17, ptr %_y, align 16
  %18 = load <2 x i64>, ptr %x_, align 16
  store <2 x i64> %18, ptr %__a.addr.i13, align 16
  %19 = load <2 x i64>, ptr %__a.addr.i13, align 16
  %20 = bitcast <2 x i64> %19 to <2 x double>
  %21 = load <2 x i64>, ptr %_y, align 16
  store <2 x i64> %21, ptr %__a.addr.i12, align 16
  %22 = load <2 x i64>, ptr %__a.addr.i12, align 16
  %23 = bitcast <2 x i64> %22 to <2 x double>
  %shufp = shufflevector <2 x double> %20, <2 x double> %23, <2 x i32> <i32 0, i32 3>
  store <2 x double> %shufp, ptr %__a.addr.i11, align 16
  %24 = load <2 x double>, ptr %__a.addr.i11, align 16
  %25 = bitcast <2 x double> %24 to <2 x i64>
  store <2 x i64> %25, ptr %xy, align 16
  %26 = load <2 x i64>, ptr %xy, align 16
  ret <2 x i64> %26
}

declare <2 x i64> @llvm.x86.sse2.psll.q(<2 x i64>, <2 x i64>) #1

```

**Comment by RKSimon** [comment]
https://zig.godbolt.org/z/PWqzTGd31 - should be able to replace both psll intrinsics (currently only one)

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -1304,6 +1304,9 @@ static void computeKnownBitsFromOperator(const Operator *I,
     // Look through a cast from narrow vector elements to wider type.
     // Examples: v4i32 -> v2i64, v3i8 -> v24
     unsigned SubBitWidth = SrcVecTy->getScalarSizeInBits();
+    unsigned NumElts = DemandedElts.getBitWidth();
+    unsigned SubScale = BitWidth / SubBitWidth;
```
Comment (RKSimon) [inline llvm/lib/Analysis/ValueTracking.cpp:1308]: SubScale isn't the same for each path - the new path is `SubBitWidth / BitWidth`

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 2]
```diff
@@ -1331,10 +1332,31 @@ static void computeKnownBitsFromOperator(const Operator *I,
       for (unsigned i = 0; i != SubScale; ++i) {
         computeKnownBits(I->getOperand(0), SubDemandedElts.shl(i), KnownSrc,
                          Depth + 1, Q);
-        unsigned ShiftElt = Q.DL.isLittleEndian() ? i : SubScale - 1 - i;
+        unsigned ShiftElt = IsLE ? i : SubScale - 1 - i;
         Known.insertBits(KnownSrc, ShiftElt * SubBitWidth);
       }
     }
+
+    if (SubBitWidth % BitWidth == 0) {
```
Comment (RKSimon) [inline llvm/lib/Analysis/ValueTracking.cpp:1340]: Comments?

**Comment by RKSimon** [comment]
Please can you rebase - I've added the test to trunk so this patch can show the diff more easily.

The next step is add to add more test coverage - if you comment out the DAG equivalent code and see the test changes you might be able to adapt some of those tests to create new IR tests?

**Comment by RKSimon** [comment]
@abhishek-kaushik22 any luck with generating extra tests?

**Comment by RKSimon** [comment]
@abhishek-kaushik22 reverse-ping?

**Comment by abhishek-kaushik22** [comment]
Sorry about this, haven't had time recently :(
I'll try and finish it soon!

**Comment by abhishek-kaushik22** [comment]
@RKSimon I've added some tests for now but there are ~30 selection dag failures that I've yet to analyze. I'll add more tests later this week and fix the names of the tests (I just ran metarenamer on the tests for now). Please ignore.

**Comment by abhishek-kaushik22** [comment]
I was only able to find one more test in the rest of the failures.
Should I commit the tests first to show what's changed more clearly (I had chatgpt name the tests 😄)? @RKSimon

**Comment by RKSimon** [comment]
Sure - I'd probably recommend renaming `pr125228.ll` to `bitcast-known-bits.ll` and instead mention PR125228 in a comment at near the top of the file (after the RUN lines etc.)

**Comment by RKSimon** [comment]
You also need to investigate the CI failure as it seems relevant

**Comment by abhishek-kaushik22** [comment]
The failed test `LLVM.CodeGen/SPIRV/ExecutionMode_Fragment.ll` seems unrelated to this issue.

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 3]
```diff
@@ -1376,10 +1377,32 @@ static void computeKnownBitsFromOperator(const Operator *I,
...
         computeKnownBits(I->getOperand(0), SubDemandedElts.shl(i), KnownSrc, Q,
                          Depth + 1);
-        unsigned ShiftElt = Q.DL.isLittleEndian() ? i : SubScale - 1 - i;
+        unsigned ShiftElt = IsLE ? i : SubScale - 1 - i;
         Known.insertBits(KnownSrc, ShiftElt * SubBitWidth);
       }
     }
+    // Look through a cast from wider vector elements to narrow type.
+    // Examples: v2i64 -> v4i32
+    if (SubBitWidth % BitWidth == 0) {
```
Comment (dtcxzyw) [inline llvm/lib/Analysis/ValueTracking.cpp:1386]: I guess the missing case `v2i32 -> i64` can be handled here (as a follow-up): https://github.com/llvm/llvm-project/blob/07fa6d1d90c714fa269529c3e5004a063d814c4a/llvm/lib/Analysis/ValueTracking.cpp#L1295-L1301

**Review by dtcxzyw — APPROVED** [review]
LG. See also my comments on the pre-commit tests https://github.com/llvm/llvm-project/pull/144111.

**Review by RKSimon — CHANGES_REQUESTED** [review]
@abhishek-kaushik22 please can you merge against trunk?

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Comment by mstorsjo** [comment]
Headsup; I’ve bisected a miscompile in libvpx down to this commit. Will revert when I’ve made a reproducer.

**Comment by aeubanks** [comment]
Chromium is also seeing supposed miscompiles bisecting to this in https://github.com/google/highway

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 4]
```diff
@@ -1376,10 +1377,32 @@ static void computeKnownBitsFromOperator(const Operator *I,
...
+      unsigned SubScale = SubBitWidth / BitWidth;
+      KnownBits KnownSrc(SubBitWidth);
+      APInt SubDemandedElts =
+          APIntOps::ScaleBitMask(DemandedElts, NumElts / SubScale);
+      computeKnownBits(I->getOperand(0), SubDemandedElts, KnownSrc, Q,
+                       Depth + 1);
+
+      Known.Zero.setAllBits();
+      Known.One.setAllBits();
+      for (unsigned i = 0; i != SubScale; ++i) {
```
Comment (nikic) [inline llvm/lib/Analysis/ValueTracking.cpp:1396]: I think this was supposed to go up to NumElts, not SubScale. If one of the first SubScale elements are non-demanded but later ones are demanded this will miscompile.

**Comment by mstorsjo** [comment]
FWIW, the miscompile can be reproduced with https://martin.st/temp/loopfilter_sse2-preproc.c - compiled as `clang -target x86_64-linux-gnu -O3 -std=gnu99 loopfilter_sse2-preproc.c -c`.

**Comment by aeubanks** [comment]
Reverted in https://github.com/llvm/llvm-project/pull/145191

File: llvm/lib/Analysis/ValueTracking.cpp (hunk 4 above)
Comment (abhishek-kaushik22) [reply llvm/lib/Analysis/ValueTracking.cpp:1396]: Thanks! I've opened #145223 to reland this.
