### PR TITLE
Sanitizer/MIPS: Use $t9 for preemptible function call

### LINKED ISSUE #74047: compiler-rt fails to build on mips64el with "relocation truncated to fit: R_MIPS_PC16"
On mips64el, the compiler-rt build fails with:

```
[1517/1588] : && "/<<PKGBUILDDIR>>/build-llvm/./bin/clang++" --target=mips64el-linux-gnuabi64 -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -fdebug-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -ffile-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -Wall -Wno-unused-parameter -O3 -DNDEBUG  -Wl,-z,relro -Wl,--build-id -Wl,-z,defs -Wl,-z,nodelete   -nodefaultlibs -Wl,-z,text -nostdlib++ "-Wl,--version-script,/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins/compiler-rt/lib/asan/clang_rt.asan-dynamic-mips64el.vers" -shared -Wl,-soname,libclang_rt.asan-mips64el.so -o "/<<PKGBUILDDIR>>/build-llvm/lib/clang/18/lib/linux/libclang_rt.asan-mips64el.so" compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_linux.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_mac.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_win.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_type_test.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_allocator.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_common.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_deadlock_detector1.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_deadlock_detector2.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_errno.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_file.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_flags.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_flag_parser.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_libc.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_libignore.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_linux_s390.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_mutex.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_netbsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_freebsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_netbsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_posix.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_posix.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_printf.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_common.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_bsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_range.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_suppressions.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_tls_get_addr.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_thread_arg_retval.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_thread_registry.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_type_traits.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_termination.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_common_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_allocator_checks.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_mac_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_posix_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_stoptheworld_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_stoptheworld_netbsd_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sancov_flags.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_libcdep_new.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_win_sections.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_allocator_report.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_chained_origin_depot.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stack_store.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stackdepot.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_printer.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_sparc.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_libbacktrace.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_markup.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_posix_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_report.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_unwind_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_unwind_win.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_fuchsia.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_linux.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_mac.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_diag.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_init.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_flags.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_handlers.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_monitor.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_value.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_allocator.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_activation.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_debugging.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_descriptions.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_errors.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_fake_stack.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_flags.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_fuchsia.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_globals.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_globals_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors_memintrinsics.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_linux.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_mac.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_linux.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_mac.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_memory_profile.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_poisoning.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_posix.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_premap_shadow.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_report.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_rtl.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_shadow_setup.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_stack.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_stats.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_suppressions.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_thread.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors_vfork.S.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_new_delete.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic_version_script_dummy.mips64el.dir/dummy.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_handlers_cxx.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash_itanium.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash_win.cpp.o  -lstdc++  -lgcc_s  -lc  -ldl  -lrt  -lm  -lpthread && :
FAILED: /<<PKGBUILDDIR>>/build-llvm/lib/clang/18/lib/linux/libclang_rt.asan-mips64el.so 
: && "/<<PKGBUILDDIR>>/build-llvm/./bin/clang++" --target=mips64el-linux-gnuabi64 -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -fdebug-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -ffile-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -Wall -Wno-unused-parameter -O3 -DNDEBUG  -Wl,-z,relro -Wl,--build-id -Wl,-z,defs -Wl,-z,nodelete   -nodefaultlibs -Wl,-z,text -nostdlib++ "-Wl,--version-script,/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins/compiler-rt/lib/asan/clang_rt.asan-dynamic-mips64el.vers" -shared -Wl,-soname,libclang_rt.asan-mips64el.so -o "/<<PKGBUILDDIR>>/build-llvm/lib/clang/18/lib/linux/libclang_rt.asan-mips64el.so" compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_linux.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_mac.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_win.cpp.o compiler-rt/lib/interception/CMakeFiles/RTInterception.mips64el.dir/interception_type_test.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_allocator.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_common.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_deadlock_detector1.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_deadlock_detector2.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_errno.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_file.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_flags.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_flag_parser.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_libc.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_libignore.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_linux_s390.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_mutex.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_netbsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_freebsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_netbsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_posix.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_platform_limits_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_posix.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_printf.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_common.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_bsd.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_linux.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_procmaps_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_range.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_solaris.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_stoptheworld_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_suppressions.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_tls_get_addr.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_thread_arg_retval.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_thread_registry.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_type_traits.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mips64el.dir/sanitizer_termination.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_common_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_allocator_checks.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_mac_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_posix_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_stoptheworld_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.mips64el.dir/sanitizer_stoptheworld_netbsd_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sancov_flags.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_fuchsia.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_libcdep_new.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.mips64el.dir/sanitizer_coverage_win_sections.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_allocator_report.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_chained_origin_depot.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stack_store.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stackdepot.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_printer.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_stacktrace_sparc.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_libbacktrace.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_mac.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_markup.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_posix_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_report.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_symbolizer_win.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_unwind_linux_libcdep.cpp.o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.mips64el.dir/sanitizer_unwind_win.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_fuchsia.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_linux.cpp.o compiler-rt/lib/lsan/CMakeFiles/RTLSanCommon.mips64el.dir/lsan_common_mac.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_diag.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_init.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_flags.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_handlers.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_monitor.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan.mips64el.dir/ubsan_value.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_allocator.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_activation.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_debugging.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_descriptions.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_errors.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_fake_stack.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_flags.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_fuchsia.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_globals.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_globals_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors_memintrinsics.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_linux.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_mac.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_linux.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_mac.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_malloc_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_memory_profile.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_poisoning.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_posix.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_premap_shadow.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_report.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_rtl.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_shadow_setup.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_stack.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_stats.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_suppressions.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_thread.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_win.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors_vfork.S.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_new_delete.cpp.o compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic_version_script_dummy.mips64el.dir/dummy.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_handlers_cxx.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash_itanium.cpp.o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.mips64el.dir/ubsan_type_hash_win.cpp.o  -lstdc++  -lgcc_s  -lc  -ldl  -lrt  -lm  -lpthread && :
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `pthread_getschedparam':
asan_interceptors.cpp:(.text+0x460): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_pthread_getschedparam'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `getaddrinfo':
asan_interceptors.cpp:(.text+0x468): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_getaddrinfo'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `getnameinfo':
asan_interceptors.cpp:(.text+0x470): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_getnameinfo'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `getsockname':
asan_interceptors.cpp:(.text+0x478): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_getsockname'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostbyname':
asan_interceptors.cpp:(.text+0x480): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostbyname'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostbyaddr':
asan_interceptors.cpp:(.text+0x488): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostbyaddr'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostent':
asan_interceptors.cpp:(.text+0x490): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostent'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostbyname2':
asan_interceptors.cpp:(.text+0x498): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostbyname2'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostbyname_r':
asan_interceptors.cpp:(.text+0x4a0): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostbyname_r'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostent_r':
asan_interceptors.cpp:(.text+0x4a8): relocation truncated to fit: R_MIPS_PC16 against `__interceptor_gethostent_r'
compiler-rt/lib/asan/CMakeFiles/RTAsan_dynamic.mips64el.dir/asan_interceptors.cpp.o: in function `gethostbyaddr_r':
asan_interceptors.cpp:(.text+0x4b0): additional relocation overflows omitted from the output
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

This affects both LLVM 17 and 18.

Full log for LLVM 17: https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-17&arch=mips64el&ver=1%3A17.0.3-1%7Eexp1&stamp=1697551933&raw=0

Full log for LLVM 18: https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-snapshot&arch=mips64el&ver=1%3A18%7E%2B%2B20230910052457%2B7560356a832f-1%7Eexp1&stamp=1694380028&raw=0

### PR DESCRIPTION
**Pull request by wzssyqa**
Currently, almost all of the shared libraries of MIPS, rely on $t9
to get the address of current function, instead of PCREL instructions,
even on MIPSr6. So we have to set $t9 properly.

To get the address of preemptible function,  we need the help of GOT.
MIPS/O32 has .cpload, which can help to generate 3 instructions to get GOT.
For __mips64, we can get GOT by:

  lui $t8, %hi(%neg(%gp_rel(SANITIZER_STRINGIFY(TRAMPOLINE(func)))))
  daddu $t8, $t8, $t9
  daddiu $t8, $t8, %hi(%neg(%gp_rel(SANITIZER_STRINGIFY(TRAMPOLINE(func)))))

And then get the address of __interceptor_func, and jump to it

  ld $t9, %got_disp(__interceptor_" SANITIZER_STRINGIFY(func) ")($t8)
  jr $t9

Fixes #74047

### CODE REVIEW

**Comment by wzssyqa** [comment]
@brad0

**Comment by brad0** [comment]
This also has a Clang patch mixed in.

File: compiler-rt/lib/sanitizer_common/sanitizer_asm.h [hunk 1]
```diff
@@ -53,6 +55,29 @@
 # define ASM_TAIL_CALL tail
 #endif
 
+#if defined(__mips64) && __mips_isa_rev < 6
+#  define C_ASM_TAIL_CALL(tfunc, ifunc)       \
+    "lui $t8, %hi(%neg(%gp_rel(" tfunc        \
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/sanitizer_asm.h:60]: not sure that you need these lines breaks before )))

Comment (wzssyqa) [reply compiler-rt/lib/sanitizer_common/sanitizer_asm.h:60]: I think that we should ignore it.

**Comment by wzssyqa** [comment]
Change daddu to daddiu, since gas cannot use daddu for const value.

**Comment by wzssyqa** [comment]
@MaskRay

File: compiler-rt/lib/interception/interception.h [hunk 2]
```diff
@@ -191,12 +191,12 @@ const interpose_substitution substitution_##func_name[]             \
 #   define ASM_TYPE_FUNCTION_STR "@function"
 #  endif
 // Keep trampoline implementation in sync with sanitizer_common/sanitizer_asm.h
-#  define DECLARE_WRAPPER(ret_type, func, ...)                                 \
-     extern "C" ret_type func(__VA_ARGS__);                                    \
-     extern "C" ret_type TRAMPOLINE(func)(__VA_ARGS__);                        \
-     extern "C" ret_type __interceptor_##func(__VA_ARGS__)                     \
-       INTERCEPTOR_ATTRIBUTE __attribute__((weak)) ALIAS(WRAP(func));          \
-     asm(                                                                      \
+#    define DECLARE_WRAPPER(ret_type, func, ...)                         \
```
Comment (MaskRay) [inline compiler-rt/lib/interception/interception.h:194]: You can ignore clang-format error to reduce diff.

Does this patch address all comments I left on https://reviews.llvm.org/D158491 ?

**Comment by MaskRay** [comment]
> On MIPS pre-R6, instruction b can only work within 64KiB,

I left a comment on the Phabricator instance (which I cannot access now) that this is 128KiB.

**Comment by MaskRay** [comment]
I remember that I left a detailed alternative description on Phabricator but read-only mirror does not contain the latest comment...

The description should include some information about how the interceptor symbols work on mips. For example, on x86 it's:
```
malloc:
__interceptor_trampoline_malloc:
  jmp __interceptor_malloc

__interceptor_malloc:
___interceptor_malloc:
  // sanitizer interceptor implementation
```

https://maskray.me/blog/2023-01-08-all-about-sanitizer-interceptors contains some notes about the interceptor mechanism.

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

**Comment by wzssyqa** [comment]
@MaskRay Thanks for your note. I find a new problem: R6 also need t9 due to that the existing libraries depends on $t9.

**Comment by MaskRay** [comment]
The old comment is:

```
>>! In D158491#4658118, @MaskRay wrote:
> This seems to need a rebase.
> 

I will do so.

>> On MIPS pre-R6, instruction b can only work within 64KiB, which is not enough now.
> 
> I think this is wrong. The b instruction has a range of +-128KiB.
> 

Yes. It is +-128KiB.

> Is the range different on R6? If not, omit "On MIPS pre-R6".
> 

Yes, and No.
R6 introduces a new instruction: BC, its range is 2^28 Bytes.

Normally, If we just write `b XX` asm code, the r6 assembler will convert it to `bc YY`. 

>> which is not enough now.
> 
> which leads to relocation overflows for ... (ideally give an example error message).
> 

Thanks. I will add one.

> 
>> For __mips64, we can get GOT by:
> 
> For 64-bit,
> 
>> MIPSr6 has instruction bc, which can jump long enough.
> 
> The patch utilizes bc for r6 but the title implies that the change is a no-op for r6.

Putting `bc` here, can make things more clear.
In fact, no matter `b` or `bc` here, `BC` will be used eventually. 
```

**Review by MaskRay — APPROVED** [review]

**Comment by brad0** [comment]
@MaskRay From your last set of comments were you going to make some changes to this?

**Comment by wzssyqa** [comment]
> @MaskRay From your last set of comments were you going to make some changes to this?

This is the history in review.llvm.org.
