### PR TITLE
[clang-tidy] Fix a broken fix-it provided by `modernize-use-integer-sign-comparison`

### LINKED ISSUE #162981: [clang-tidy] `modernize-use-integer-sign-comparison` fix-it inserts unbalanced parenthesis
This:

```cpp
unsigned short u = 0;
short s = 0;
if (static_cast<unsigned int>(u) < static_cast<int>(s))
    return 0;
```
becomes
```cpp
unsigned short u = 0;
short s = 0;
if (std::cmp_less(u,s))) // <- Should only be 2 closing parentheses
    return 0;
```
[Godbolt](https://godbolt.org/z/oWsGb5eEz)

Found as part of #162851.

### PR DESCRIPTION
**Pull request by localspook**
Fixes #162981.

This is an issue with both named and functional casts, but this check doesn't have any existing tests for the latter, so I went and added those.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/modernize/UseIntegerSignComparisonCheck.cpp [hunk 1]
```diff
@@ -152,6 +152,8 @@ void UseIntegerSignComparisonCheck::check(
   if (const auto *RHSCast = llvm::dyn_cast<ExplicitCastExpr>(RHS)) {
     SubExprRHS = RHSCast->getSubExpr();
     R2.setEnd(SubExprRHS->getBeginLoc().getLocWithOffset(-1));
+    R3.setBegin(Lexer::getLocForEndOfToken(
+        SubExprRHS->getEndLoc(), 0, *Result.SourceManager, getLangOpts()));
```
Comment (localspook) [inline clang-tools-extra/clang-tidy/modernize/UseIntegerSignComparisonCheck.cpp]: Notice how (before this change) this `if` statement and the one before it were asymmetric: the previous one correctly adjusted two ranges (`R1` and `R2`), while this one incorrectly adjusted only one (`R2`).

Comment (vbvictor) [reply clang-tools-extra/clang-tidy/modernize/UseIntegerSignComparisonCheck.cpp]: Wish we had meaningful names for R1, R2, R3. Could be a later NFC patch

**Review by vbvictor — APPROVED** [review]
