### PR TITLE
[llvm-objdump] Support --mcpu=help/--mattr=help without -d

### LINKED ISSUE #150567: llvm-objdump --mcpu=help doesn't work without an input file
```
$ llvm-objdump --version
Fuchsia LLVM version 21.0.0git
...
```

`--help` indicates that `--mcpu=help` should provide details for the `--mcpu` option:
```
$ llvm-objdump --help
OVERVIEW: llvm object file dumper

USAGE: llvm-objdump [options] <input object files>

OPTIONS:
  ...
  --mcpu=cpu-name         Target a specific cpu type (--mcpu=help for details) 
  ...
```

If I do only that, it just outputs the normal help again:
```
$ llvm-objdump --mcpu=help
OVERVIEW: llvm object file dumper

...
```

But if I provide it an input file, then it provides the CPU help:
```
$ llvm-objdump --mcpu=help -d a.out >/dev/null
Available CPUs for this target:

  arm1020e       - Select the arm1020e processor.
  ...
```

It seems like `--mcpu=help` should bypass the rest of the argument checking.

### PR DESCRIPTION
**Pull request by cabbaken**
Currently `--mcpu=help` and `--mattr=help` only produce help out when disassembling. This patch specialises these cases to always print the requested help.

If `--triple` is specified, the help text will be derived from the specified target. Otherwise, it will be derived from the target of the first input file.

Fixes: #150567

### CODE REVIEW

**Comment by cabbaken** [comment]
It appears my local code is currently outdated. I will address this issue and push the fix later.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 1]
```diff
@@ -3826,6 +3841,10 @@ int llvm_objdump_main(int argc, char **argv, const llvm::ToolContext &) {
       !DisassembleSymbols.empty())
     Disassemble = true;
 
+  if (!Disassemble && MCPU == "help") {
+    return MCPUHelp();
+  }
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: [No braces for single-line conditionals](https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements).

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 2]
```diff
@@ -3533,6 +3533,21 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
 }
 
+static int MCPUHelp() {
+  if (!TripleName.empty()) {
+    std::string Error;
+    Triple DummyTriple(TripleName);
+    const Target *DummyTarget =
+        TargetRegistry::lookupTarget(DummyTriple, Error);
+    if (!DummyTarget) {
+      outs() << Error << '\n';
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: Why is this writing an error to `stdout` not `stderr`. In fact, why is it not simply using the existing mechanism for reporting errors from llvm-objdump?

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 3]
```diff
@@ -3533,6 +3533,21 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+      return 2;
+    }
+    DummyTarget->createMCSubtargetInfo(DummyTriple, MCPU, "");
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: It's probably worth a comment here about what is going on.

**Review by jh7370 — CHANGES_REQUESTED** [review]

**Review by jh7370 — COMMENTED** [review]
Sorry for the delayed follow-up, I've had a busy couple of weeks.

It occurs to me that the exact same principle for `--mcpu=help` should be followed for `--mcpu=attr` too. They probably belong in the same PR, because the changes will be near identical.

You should probably add a release note saying that `--mcpu=help` now prints the list help information, even if `--disassemble` et all haven't been specified.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 4]
```diff
@@ -3533,6 +3533,22 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
   return Values;
 }
 
+static int mcpuHelp() {
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: I apologize for this; I accidentally submitted my debug code.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 5]
```diff
@@ -14,3 +14,11 @@ FileHeader:
...
   Type:            ET_EXEC
   Machine:         EM_X86_64
+
+# RUN: llvm-objdump --triple=x86_64 --mcpu=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-WITHOUT-DISASSEMBLING
+
+# CHECK-WITHOUT-DISASSEMBLING: Available CPUs for this target:
+# CHECK-WITHOUT-DISASSEMBLING: Available features for this target:
+
+; XFAIL: *
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: > If we don't specify a filename, llvm-objdump reports an error due to the missing file.

It shouldn't be necessary to have a file if only requesting the CPU help text. You need to modify llvm-objdump to not emit an error in this case.

> The line ; XFAIL: * is used to ensure the test fails as expected.

1. That is not what `XFAIL` is for. `XFAIL` is intended for tests that should pass but currently don't due to either a bug or other unimplemented feature or similar. It is absolutely not for where the expected behaviour is that the tool exits with a non-zero exit code. That's what the `not` utility is for. Please see all the other examples of tests where llvm-objdump or other tools report an error.
2. `XFAIL` directives, like `REQUIRES` or `UNSUPPORTED` should be at the top of the file.

[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: > It shouldn't be necessary to have a file if only requesting the CPU help text. You need to modify llvm-objdump to not emit an error in this case.

Would it be acceptable if I simply return after outputting the help message?
This would disrupt the original behavior. For example, if we run `llvm-objdump --mcpu=help --section-headers a.out`, it should output section headers following the help message. 
However, the section headers won't be parsed if the execution returns early. A potential alternative is to consider whether we should allow a shared scope for `mcpuHelp()` and `T->printHelp()`.

> That is not what XFAIL is for. XFAIL is intended for tests that should pass but currently don't due to either a bug or other unimplemented feature or similar. It is absolutely not for where the expected behaviour is that the tool exits with a non-zero exit code. That's what the not utility is for. Please see all the other examples of tests where llvm-objdump or other tools report an error.

I apologize for the oversight. I mistakenly referred to a random "Expectedly Failed" file and encountered this issue.

[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: Should the behavior of `llvm-objdump --mcpu=help --triple=...` be unified with `llvm-objdump --help`, which directly outputs the help message and then returns normally?

**Review by jh7370 — COMMENTED** [review]
Let's take a step back and ignore the state of the current code, but consider what we'd ideally want to achieve. Here's the behaviour I think we want. Feel free to disagree, but please explain why:

1. --mcpu=help + --disassemble + objects specified + other dump options, no --triple:
   a. mcpu help should be printed for the targets specified (as current behaviour).
   b. Disassembly should be printed for specified objects (as current behaviour).
   c. Other dump options should be printed for specified objects.
2. --mcpu=help + --disassemble + no objects specified + other dump options, no --triple
   a. Same as 1. but with `a.out` treated as the object, if it exists.
   b. If `a.out` doesn't exist, we want some form of error, because we don't know which target to dump the mcpu help text for.
3. --mcpu=help + --disassemble + no objects specified + other dump options, --triple
   a. As 2. but target derived from `--triple` option value.
   b. If `a.out` doesn't exist, print MCPU help derived from `--triple` and don't emit an error.
4. --mcpu=help + no --disassemble
   a. Same as above cases, depending on other option values (`--disassemble` is not required to print MCPU help text).
   b. If no other dump options specified, exit success and no errors.

Does that make sense to you?

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 6]
```diff
@@ -14,3 +14,30 @@ FileHeader:
   Data:            ELFDATA2LSB
   Type:            ET_EXEC
   Machine:         EM_X86_64
+
+# RUN: cp %t a.out
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: These test cases would benefit from some comments to explain what each case is testing specifically. I also think a specific comment for the `rm` line would be appropriate saying why it is being done.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 7]
```diff
@@ -14,3 +14,30 @@ FileHeader:
...
+# RUN: llvm-objdump -d --mcpu=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-DEFAULT-FILE
+# RUN: rm a.out
+
+# CHECK-DEFAULT-FILE: Available CPUs for this target:
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: CHECK prefixes can be reused between FileCheck invocations. You can also combine multiple in a single FileCheck run, using --check-prefixes. I reckon in total, we could get away with the following between all test cases (including the existing one):

`CHECK-HELP` which checks the help titles are printed.
`CHECK-DISASM` which checks that x86-64 disassembly is printed (primarily for the original test case, but can (should?) also be used for the a.out case.
`CHECK-ARM` which checks that ARM help text is produced.
`NO-DISASM` which is the same as CHECK-DISASM, but you can add a `-NOT` suffix to the check pattern line to invert it and fail if disassembly is printed.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 8]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
   return Values;
 }
 
+static void mcpuHelp() {
+  std::string Error;
+  Triple DummyTriple;
+
+  if (!TripleName.empty())
+    DummyTriple.setTriple(TripleName);
+  else {
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: LLVM style guide says that if braces are required for one part of a conditional sequence, they should be used for all parts.
```suggestion
  if (!TripleName.empty()) {
    DummyTriple.setTriple(TripleName);
  } else {
```

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 9]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+    // If the target triple is derived from the files, we display help message
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: I'm not sure it should matter whether the triple is derived from the files or specified explicitly? If `Disassemble` is true, we should always defer to the existing printing point to print help. Otherwise, if I'm not mistaken, you'll print the help output twice, for this case.

**Review by jh7370 — COMMENTED** [review]
I think you could do with additional test cases to cover/better illustrate certain behaviours, as described in my previous review. Specifically:
- No -d, --triple, or input file (this should be a failure, but it might be clearer to explicitly report a dedicated error if --mcpu=help has been requested saying something about being unable to determine the triple to produce help for, rather than relying on "a.out not found" or similar error).
- --mcpu=help + some other dump option e.g. dump file headers, to show that other non-disassembly stuff is still done. This covers the inverse of point 4b from my previous review.
Additionally, tests should be amended to ensure the help is only printed once and not two or more times.

What do you think about extending this PR to cover `--mattr=help` too, rather than waiting for a separate PR?

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 10]
```diff
@@ -14,3 +14,30 @@ FileHeader:
...
+# CHECK-DEFAULT-FILE: Available features for this target:
+
+# RUN: llvm-objdump --triple=arm --mcpu=help %t 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-TRIPLE-PRIORITY
+
+# CHECK-TRIPLE-PRIORITY: Available CPUs for this target:
+# CHECK-TRIPLE-PRIORITY: Available features for this target:
+# CHECK-TRIPLE-PRIORITY: arm
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: Should I move only the ARM-related tests to the new file or move all new tests associated with this change?

[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: I'd move just enough to test the interaction of --mcpu=help and --triple. In other words, show that when --triple is specified with --mcpu=help:
1) If there are no input files, the triple is used.
2) If there are input files, the triple is used, even if it doesn't match the first object.

**Comment by cabbaken** [comment]
When I'm writing the test case accroding to
> 3. --mcpu=help + --disassemble + no objects specified + other dump options, --triple
a. As 2. but target derived from --triple option value.
b. If a.out doesn't exist, print MCPU help derived from --triple and don't emit an error.

Is it intended behavior that we don't emit an error if the user specifies -d but a.out doesn't exist?

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 11]
```diff
@@ -14,3 +14,30 @@ FileHeader:
...
+
+# RUN: not llvm-objdump --triple=x86_64 --mcpu=help 2>&1 \
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: I added `--section-headers` in latest commit.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test (hunk 6 above)
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: To test if the default filename (a.out) is handled correctly, we need to create an a.out file. Do you think this is necessary, or is the test redundant?

**Review by jh7370 — COMMENTED** [review]
I'm afraid your test cases have gone rather wide of what I was expecting - the previous version was much closer, if I'm honest.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+# RUN: not llvm-objdump -d --mattr=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-FILE-ISSUE
+
+## Check if we can handle the default filename.
+# RUN: cp %t a.out
+# RUN: llvm-objdump -d --mcpu=help --section-headers 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK-HELP,CHECK-ARM,CHECK-DISASM,CHECK-SECTION-HEADER
+# RUN: llvm-objdump -d --mattr=help --section-headers 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK-HELP,CHECK-ARM,CHECK-DISASM,CHECK-SECTION-HEADER
+# RUN: rm a.out
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test]: This PR should test the behaviour you are adding/changing. I believe that's "what does --triple do in conjunction with --mcpu=help and --mattr=help" and "what happens if we specify --mcpu=help if we don't specify a dumping option like -d". To further illustrate the first case, you should ensure there is test coverage for "what target does --mcpu=help print for when --triple is not specified" too. For the second case, we should ensure we don't break the behaviour for when we have specified other dumping options, by ensuring there is adequate test coverage of --mcpu=help + -d and --mcpu=help + --some-other-dump to show that we keep printing in these cases. Having thought more about it, I think it's important to ensure both these combinations exist separately, because of how we're special-casing requests for disassembly in this change.

[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test]: >  To further illustrate the first case, you should ensure there is test coverage for "what target does --mcpu=help print for when --triple is not specified" too.

The first test case(`llvm-objdump --mcpu=help %t`) I added already illustrate this.

>  For the second case, we should ensure we don't break the behaviour for when we have specified other dumping options, by ensuring there is adequate test coverage of --mcpu=help + -d and --mcpu=help + --some-other-dump to show that we keep printing in these cases.

The original test case (`llvm-objdump -d %t --mattr=help`) in mattr-mcpu-help.test covers the --mcpu=help + -d scenario. 
Would it be helpful if I add a case (`llvm-objdump --mcpu=help --section-headers %t`) to illustrate that we continue printing the output in these situations?

File: llvm/docs/ReleaseNotes.md [hunk 13]
```diff
@@ -200,6 +200,9 @@ Changes to the LLVM tools
   emitted on stdout, to account for spaces or other special characters in path.
   (`#97305 <https://github.com/llvm/llvm-project/pull/97305>`_).
 
+* `llvm-objdump` now supports using `--mcpu=help` with the `--triple` option
```
Comment (jh7370) [inline llvm/docs/ReleaseNotes.md]: Needs updating to mention `--mattr=help` too.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test [hunk 14]
```diff
@@ -0,0 +1,33 @@
+# RUN: yaml2obj %s -o %t
+# REQUIRES: arm-registered-target,x86-registered-target
+
+## Check if we can handle without -d
+# RUN: llvm-objdump --mcpu=help %t 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK-HELP,CHECK-ARM
+
+## Check if we can handle without file
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test]: I thought I was pretty clear about this before. There should be a test case that shows --mcpu=help when there is no input file and no --triple or other dump options that we report an error (input file is missing, so we can't infer the triple value for printing the help). This test case should be in the pre-existing test file that isn't about --triple.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 15]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+
+  if (!TripleName.empty()) {
+    TheTriple.setTriple(TripleName);
+  } else {
+    // If the target triple is derived from the files, we display help message
+    // when disassembling them.
+    if (Disassemble)
+      return;
+    if (InputFilenames.size() != 1)
+      reportWarning("When multiple files are specified, only the first file is "
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: Why have you introduced this warning?

**Review by jh7370 — COMMENTED** [review]
Please update your PR title and help text to better match what you are doing in the PR.

**Comment by cabbaken** [comment]
I think the test cases I wrote is like a pile of garbage.
I'm optimizing them and will push a commit soon. Should I convert this PR to a draft?
Additionally, do you think the PR title is suitable for this PR now?

**Comment by jh7370** [comment]
> I think the test cases I wrote is like a pile of garbage. I'm optimizing them and will push a commit soon. Should I convert this PR to a draft? Additionally, do you think the PR title is suitable for this PR now?

Up to you whether you convert it to a draft. I won't be reviewing it further until I see more commits. The PR title is mostly fine, but a bit long. How about "[llvm-objdump] Support --mcpu=help/--mattr=help without -d"? The description still needs updating, as that is used as the commit message for the final commit that gets landed.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp (hunk 9 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: I apologize if I wasn't clear; I think there might be a misunderstanding due to my poor English.

Try to reproduce the issue by the following steps:
```bash
# t.c can be an empty file, we just need an arm object.
touch t.c
clang t.c -c -o arm.o --target=arm

# It should output x86_64 help message if I'm not misunderstanding.
llvm-objdump -d --mcpu=help --triple=x86_64 arm.o
# If my code of main branch is not corrupted, this will output help 
# message of arm. That's why I think this is an unexpected behaviour.
```

**Comment by jh7370** [comment]
Taking the conversation out-of-line, due to the lengthy comment. It turns out we're both right, but mostly because the behaviour is inconsistent!

Take the following two simple assembly files for ARM and x86_64:
```
# arm.s
.text
.global foo
.type foo#function
foo:
    add r0, r0
```
```
.text
.global foo
.type foo,function
foo:
    nop
```
Then compile them as follows:
```
D:\Work> D:\llvm\build\Debug\bin\clang -c --target=arm-pc-linux arm.s
D:\Work> D:\llvm\build\Debug\bin\clang -c --target=x86_64-pc-linux x86_64.s
```
Then do disassembly and --mcpu=help, with and without --triple=<other-target>, i.e.:
```
D:\Work> D:\llvm\build\Debug\bin\llvm-objdump.exe -d --mcpu=help arm.o
D:\Work> D:\llvm\build\Debug\bin\llvm-objdump.exe -d --mcpu=help x86_64.o
D:\Work> D:\llvm\build\Debug\bin\llvm-objdump.exe -d --mcpu=help arm.o --triple=x86_64
D:\Work> D:\llvm\build\Debug\bin\llvm-objdump.exe -d --mcpu=help x86_64.o --triple=arm
```
For things to be consistent, you'd either expect the help to always match the target of the input file, or to always match that specified by the input file. However, what I actually see is:
| Command | Arm object | x86_64 object |
|---------|----------|----------|
| -d --mcpu=help | Arm disassembly, Arm mcpu help | x86_64 disassembly, x86_64 mcpu help |
| -d --mcpu=help --triple=arm | Arm disassembly, Arm mcpu help | Arm disassembly, Arm mcpu help |
| -d --mcpu=help --triple=x86_64 | ❗ Arm disassembly, Arm mcpu help | x86_64 disassembly, x86_64 mcpu help |

I experimented briefly with RISC-V inputs and triples too and that follows the same as x86_64. I've not dug into the code yet, but my suspicion is that this has to do with ARM's primary/secondary target functionality, because of how it handles Thumb code. I think it could probably be described as a bug, but one we don't really care about (it would be weird in practice to disassemble ARM code as x86_64 etc). Given this, I think we should use two targets that aren't ARM, e.g. RISCV and x86_64, and avoid ARM targets completely. The behaviour we mirror for --triple + --mcpu=help (without other dump options) should be the x86_64 behaviour. (This does mean that this specific case will behave differently for ARM with and without an input file, but I don't think that matters). Does that make sense?

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 16]
```diff
@@ -3533,6 +3533,33 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+
+  if (!TripleName.empty()) {
+    TheTriple.setTriple(TripleName);
+  } else {
+    // We can guarantee that InputFilenames won't be empty.
+    Expected<OwningBinary<Binary>> OBinary = createBinary(InputFilenames[0]);
+    // OwningBinary<Binary> OBinary =
+    if (!OBinary)
+      reportError(InputFilenames[0],
+                  "A target triple was not specified and could "
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: Please review the coding standards for warnings and error messages and fix.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 17]
```diff
@@ -1,12 +1,38 @@
...
+# RUN: llvm-objdump --mcpu=help --section-headers %t 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-SECTION-HEADERS
+
+## We report error when we can't infer triple.
+# RUN: not llvm-objdump --mattr=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-ERROR
+# RUN: not llvm-objdump --mcpu=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-ERROR
+
 # REQUIRES: x86-registered-target
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: Let's move this to the start of the file, as is traditional for `REQUIRES` statements.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test [hunk 18]
```diff
@@ -0,0 +1,25 @@
+# RUN: yaml2obj %s -o %t
+# REQUIRES: mips-registered-target,x86-registered-target
+
+## We shoule be able to retrieve help message by triple.
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-triple-help.test]:
```suggestion
## When specifying --triple, the help message should be printed for the specified target.
```

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 19]
```diff
@@ -3533,6 +3533,33 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+                  " not be inferred from the input file.");
+
+    Binary *Bin = OBinary->getBinary();
+    if (ObjectFile *Obj = dyn_cast<ObjectFile>(Bin))
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: Under what contexts can the `dyn_cast` fail? In other words, when could `Obj` be `nullptr`? If it never can, it should be `cast`, not `dyn_cast`, I believe.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp (hunk 16 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: Would this be better? 
```cpp
    Expected<OwningBinary<Binary>> OBinary = createBinary(InputFilenames[0]);
    if (auto E = OBinary.takeError()) {
      reportWarning("triple was not specified and could "
                    "not be inferred from the input file",
                    InputFilenames[0]);
      reportError(std::move(E), InputFilenames[0]);
    }
```
I haven't found a better way to incorporate the error text into this message.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 20]
```diff
@@ -1,12 +1,38 @@
 # RUN: yaml2obj %s -o %t
-# RUN: llvm-objdump -d %t --mattr=help 2>&1 | FileCheck %s
-# RUN: llvm-objdump -d %t --mcpu=help 2>&1 | FileCheck %s
+# RUN: llvm-objdump -d %t --mattr=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-DISASSEMBLE
+# RUN: llvm-objdump -d %t --mcpu=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-DISASSEMBLE
+
+## We should be able to retrieve help message without -d.
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: Apologies for that. I clicked the "Add suggestion to batch" and "Commit..." button in review page of github, but I didn't realize this would automatically resolve the comment threads. I will be sure to avoid doing this in the future.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp (hunk 19 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: If the file is an archive, it will fail with finally getting a empty triple. Perhaps we should include an error message here?

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 21]
```diff
@@ -3533,6 +3533,33 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
   return Values;
 }
 
+static void mcpuHelp() {
+  std::string Error;
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: Fixed.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 22]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
   return Values;
 }
 
+static void mcpuHelp() {
+  Triple TheTriple;
+
+  if (!TripleName.empty()) {
+    TheTriple.setTriple(TripleName);
+  } else {
+    assert(InputFilenames.size());
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]:
```suggestion
    assert(!InputFilenames.empty());
```
Much more readable.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 23]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+    Expected<OwningBinary<Binary>> OBinary = createBinary(InputFilenames[0]);
+    if (auto E = OBinary.takeError()) {
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: I apologize for this, I was following similar patterns found in other files. (I remember you previously reminded me not to abuse `auto` in other PR though)

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 24]
```diff
@@ -3533,6 +3533,35 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+      reportError(InputFilenames[0], "triple was not specified and could not "
+                                     "be inferred from the input file: " +
+                                         toString(std::move(E)));
+    }
+
+    Binary *Bin = OBinary->getBinary();
+    if (ObjectFile *Obj = dyn_cast<ObjectFile>(Bin))
+      TheTriple = Obj->makeTriple();
+    else
+      reportError(InputFilenames[0], "file format not recognized");
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: Regarding the test case, I believe a minidump file is the appropriate choice. However, it appears we cannot generate this binary via `yaml2obj`. I write a minidump file directly. This may be a little tricky, but I don't have a better solution at the moment.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 25]
```diff
@@ -1,12 +1,38 @@
...
 # REQUIRES: x86-registered-target
 
+# RUN: llvm-objdump -d %t --mattr=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-DISASSEMBLE
+# RUN: llvm-objdump -d %t --mcpu=help 2>&1 \
+# RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-DISASSEMBLE
+
+## The help message can be printed without -d.
+# RUN: llvm-objdump --mattr=help %t 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: Added.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: I apologize for not reading the document and tests.
I will fix the test later.

**Review by jh7370 — COMMENTED** [review]
You still need to update the PR description to reflect the final changes (in particular --mattr=help support).

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 26]
```diff
@@ -3533,6 +3533,51 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+
+    Binary *Bin = OBinary->getBinary();
+    if (ObjectFile *Obj = dyn_cast<ObjectFile>(Bin)) {
+      TheTriple = Obj->makeTriple();
+    } else if (Archive *A = dyn_cast<Archive>(Bin)) {
+      Error Err = Error::success();
+      for (auto &C : A->children(Err)) {
+        Expected<std::unique_ptr<Binary>> ChildOrErr = C.getAsBinary();
+        if (!ChildOrErr)
+          // We don't report error because we don't disassemble it here.
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: I'm not sure I follow why this case is different to the case earlier at https://github.com/llvm/llvm-project/blob/7904d355b34b8ae2a9ead825f7fe57f4c6eff803/llvm/tools/llvm-objdump/llvm-objdump.cpp#L3544? Why do we ignore the error in this case instead of reporting that we couldn't infer the triple from the object file?

I also note that this case doesn't have any test coverage.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 27]
```diff
@@ -44,6 +50,8 @@
 
 # CHECK-UNSUPPORTED-ERROR: llvm-objdump{{.*}}: error: '[[FILE]]': input file is not an object file
 
+# CHECK-ARCHIVE-ERROR-NOT: llvm-objdump{{.*}}: error: '[[FILE]]': input file is not an object file
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: There's no need to check that there is no error when llvm-objdump returns successfully, because the RUN line would fail if llvm-objdump returned with a failure.

File: llvm/test/tools/llvm-objdump/mattr-mcpu-help.test [hunk 28]
```diff
@@ -1,16 +1,66 @@
...
+
+# RUN: yaml2obj --docnum=2 %s -o %t.minidump
+## We report an error when the binary file isn't an object file format.
+# RUN: not llvm-objdump --mattr=help %t.minidump 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-UNSUPPORTED-ERROR --implicit-check-not=error: -DFILE=%t.minidump
+# RUN: not llvm-objdump --mcpu=help %t.minidump 2>&1 \
+# RUN:   | FileCheck %s --check-prefix=CHECK-UNSUPPORTED-ERROR --implicit-check-not=error: -DFILE=%t.minidump
+
+# RUN: llvm-ar rcs %t.a %t
+# RUN: llvm-objdump -d --mcpu=help %t.a 2>&1 \
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/mattr-mcpu-help.test]: I don't think there's any benefit from specifying `-d` in the archive tests? What behaviour are you hoping to demonstrate that is relevant to your changes?

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 29]
```diff
@@ -3533,6 +3533,51 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+          continue;
+        if (ObjectFile *Obj = dyn_cast<ObjectFile>(&*ChildOrErr.get())) {
+          TheTriple = Obj->makeTriple();
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/llvm-objdump.cpp]: I think we need a test case that shows what happens when the triple cannot be inferred from any archive member.

**Review by jh7370 — COMMENTED** [review]
PR description STILL doesn't mention --mattr=help (only the title does). There are also some grammar issues and generally I think it could be improved. How about:

> Currently `--mcpu=help` and `--mattr=help` only produce help out when disassembling. This patch specialises these cases to always print the requested help.
>
> If `--triple` is specified, the help text will be derived from the specified target. Otherwise, it will be derived from the target of the first input file.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp (hunk 29 above)
Comment (jh7370) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: Not really. The existing minidump case doesn't iterate over an archive's members. Both cases will of course hit the same error in the end, but the route to the error is very different and it would be easy enough to make a mistake.

Comment (cabbaken) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: I added the test case in the latest commit.

File: llvm/tools/llvm-objdump/llvm-objdump.cpp [hunk 30]
```diff
@@ -3533,6 +3533,57 @@ commaSeparatedValues(const llvm::opt::InputArgList &InputArgs, int ID) {
...
+      TheTriple = Obj->makeTriple();
+    } else if (Archive *A = dyn_cast<Archive>(Bin)) {
+      Error Err = Error::success();
+      unsigned I = -1;
+      for (auto &C : A->children(Err)) {
+        ++I;
+        Expected<std::unique_ptr<Binary>> ChildOrErr = C.getAsBinary();
+        if (!ChildOrErr) {
+          if (auto E = isNotObjectErrorInvalidFileType(ChildOrErr.takeError()))
+            reportError(std::move(E), getFileNameForError(C, I),
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/tools/llvm-objdump/llvm-objdump.cpp]: Fine by me.

**Review by jh7370 — APPROVED** [review]
Some comment change suggestions. LGTM once those have been made.

**Review by jh7370 — APPROVED** [review]
LGTM again. You can fix the comment in the other test in a separate PR.

Do you have commit access yet?

**Comment by qinkunbao** [comment]
Hi, can you take a look at the buildbot failure?

https://lab.llvm.org/buildbot/#/builders/24/builds/15720
https://lab.llvm.org/buildbot/#/builders/55/builds/21517

**Comment by qinkunbao** [comment]
> However, once the fix PR was there, I think the preferred course should have been to merge the fix.

I bisected a few PRs and confirmed that reverting this PR can fix buildbots.

I pinged in the thread and waited for a few hours before reverting the PR. 

On the other hand, I am not sure if the new PR can fix the issue. If the new PR did not fix the issue, the situation would be worse.

If the author mentioned that mentioned they have tested it on the local machine, I would have merged the PR. Reverting a PR is normal and is not an issue at all. 

Anyways, thanks for fixing it timely.
