### PR TITLE
[VectorCombine] vectorizeLoadInsert - only fold when inserting into a poison vector

### LINKED ISSUE #119900: [VectorCombine] vectorizeLoadInsert - incorrect shuffle when folding from inserting into undef vector
As mentioned here by @nunoplopes: https://discourse.llvm.org/t/please-dont-use-undef-in-tests-part-2/83388/17
```
; Transforms/VectorCombine/X86/load.ll

define <4 x float> @load_f32_insert_v4f32(ptr dereferenceable(16) align(16) %p) {
  %s = load float, ptr dereferenceable(16) align(16) %p, align 16
  %r = insertelement <4 x float> undef, float %s, i32 0
  ret <4 x float> %r
}
=>
define <4 x float> @load_f32_insert_v4f32(ptr dereferenceable(16) align(16) %p) {
  %#1 = load <4 x float>, ptr dereferenceable(16) align(16) %p, align 16
  %r = shufflevector <4 x float> %#1, <4 x float> poison, 0, 4294967295, 4294967295, 4294967295
  ret <4 x float> %r
}
Transformation doesn't verify! (unsound)
ERROR: Target is more poisonous than source

Source value: < poison, #x00000000 (+0.0), #x00000000 (+0.0), #x00000000 (+0.0) >
Target value: < poison, poison, poison, poison >
```

### PR DESCRIPTION
**Pull request by RKSimon**
We have corresponding poison tests in the "-inseltpoison.ll" sibling test files.

Fixes #119900

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 1]
```diff
@@ -286,7 +290,7 @@ bool VectorCombine::vectorizeLoadInsert(Instruction &I) {
   Value *CastedPtr =
       Builder.CreatePointerBitCastOrAddrSpaceCast(SrcPtr, Builder.getPtrTy(AS));
   Value *VecLd = Builder.CreateAlignedLoad(MinVecTy, CastedPtr, Alignment);
-  VecLd = Builder.CreateShuffleVector(VecLd, Mask);
+  VecLd = Builder.CreateShuffleVector(VecLd, PoisonValue::get(MinVecTy), Mask);
```
Comment (nikic) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:293]: Isn't that the default?

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 2]
```diff
@@ -179,7 +179,9 @@ bool VectorCombine::vectorizeLoadInsert(Instruction &I) {
   // Match insert into fixed vector of scalar value.
   // TODO: Handle non-zero insert index.
   Value *Scalar;
-  if (!match(&I, m_InsertElt(m_Undef(), m_Value(Scalar), m_ZeroInt())) ||
+  UndefValue *BaseVec;
+  if (!match(&I, m_InsertElt(m_UndefValue(BaseVec), m_Value(Scalar),
+                             m_ZeroInt())) ||
```
Comment (nikic) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:184]: Can we just match poison here? We shouldn't really be getting things like "insert into undef" or "shuffle with undef" anymore nowadays.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp (hunk 1 above)
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:293]: I'm trying to avoid creating shuffles that specify just one source vector but use a mask that reference both.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp (hunk 2 above)
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:184]: OK - I'll simplify the fold to just handle m_Poison

**Review by nunoplopes — APPROVED** [review]
LGTM, thank you!

**Review by nikic — APPROVED** [review]
LGTM
