### PR TITLE
[clang] Fix potential constant expression checking with constexpr-unknown.

### LINKED ISSUE #149041: [Clang] -Winvalid-constexpr misbehaves in C++23 mode
In C++23/26 mode, Clang rejects the following function definition with `-Winvalid-constexpr` used, saying "constexpr function never produces a constant expression". [Godbolt link](https://godbolt.org/z/WaKPMjorP).
```C++
constexpr bool fun(const bool& b) { return b; }
```

This seems related to [P2280R4](https://wg21.link/p2280r4), but the incorrect diagnostic occurs only since Clang 21.

### LINKED ISSUE #149188: [Clang] Error on an `enable_if` attribute in `ADT/StringRef.h` in C++23 mode
Attempting to create an `llvm::StringLiteral` in C++23 mode currently causes an error. Specifically, the code we complain about is this constructor in `ADT/StringRef.h`:
```c++
    template <size_t N>
    constexpr StringLiteral(const char (&Str)[N])
#if defined(__clang__) && __has_attribute(enable_if)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"
        __attribute((enable_if(__builtin_strlen(Str) == N - 1,
                               "invalid string literal")))
#pragma clang diagnostic pop
#endif
        : StringRef(Str, N - 1) {
    }
```
which can be reduced to (https://godbolt.org/z/xa3zs5qj6):
```c++
template <__SIZE_TYPE__ N>
constexpr void foo(const char (&Str)[N])
__attribute((enable_if(__builtin_strlen(Str), ""))) {}

void x() {
    foo("1234");
}
```
which causes the following error:
```console
<source>:3:14: error: 'enable_if' attribute expression never produces a constant expression
    3 | __attribute((enable_if(__builtin_strlen(Str), ""))) {}
      |              ^
<source>:6:5: note: in instantiation of function template specialization 'foo<5UL>' requested here
    6 |     foo("1234");
      |     ^
<source>:3:41: note: read of variable 'Str' whose value is not known
    3 | __attribute((enable_if(__builtin_strlen(Str), ""))) {}
      |                                         ^
<source>:2:33: note: declared here
    2 | constexpr void foo(const char (&Str)[N])
      |        
```

The `enable_if` attribute has been there since 2016. Interestingly, we compile this just fine in C++20 mode, and Clang 20 doesn’t complain about it at all even in C++23 mode.

### PR DESCRIPTION
**Pull request by efriedma-quic**
071765749a70b22fb62f2efc07a3f242ff5b4c52 improved constexpr-unkown diagnostics, but potential constant expression checking broke in the process: we produce diagnostics in more cases.  Supress the diagnostics as appropriate.

This fix affects -Winvalid-constexpr and the enable_if attribute.  (The -Winvalid-constexpr diagnostic isn't really important right now, but it will become important if we allow constexpr-unknown with pre-C++23 standards.)

Fixes #149041.  Fixes #149188.

### CODE REVIEW

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp [hunk 1]
```diff
@@ -357,3 +357,27 @@ namespace pointer_comparisons {
...
+  constexpr int foo()
+  __attribute((enable_if(__builtin_strlen(Str), "")))
+  {return __builtin_strlen(Str);}
+
+  constexpr const char (&f())[] {return "a";}
+  constexpr const char (&Str)[] = f();
+  void x() {
+      constexpr int x = foo();
+  }
+}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/constant-expression-p2280r4.cpp:383]: Can you reference the issue (either a comment or in the namespace name)?

File: clang/test/SemaCXX/constexpr-never-constant.cpp [hunk 2]
```diff
@@ -24,3 +24,8 @@ constexpr void other_func() {
 
   throw 12;
 }
+
+// Make sure these don't trigger the diagnostic.
+extern const bool& b;
+constexpr bool fun1() { return b; }
+constexpr bool fun2(const bool& b) { return b; }
```
Comment (cor3ntin) [inline clang/test/SemaCXX/constexpr-never-constant.cpp:31]: Can you reference the issue (either a comment or in the namespace name)?

**Review by cor3ntin — APPROVED** [review]
LGTM (presumably, we want to backport that)

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp (hunk 1 above)
Comment (shafik) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:384]: We normally use the namespace name, I think we should stick w/ that.

**Review by shafik — COMMENTED** [review]
Thank you!

**Comment by zwuis** [comment]
Can you manually backport this patch? See #150131.

**Comment by frederick-vs-ja** [comment]
> Can you manually backport this patch? See #150131.

This is being backported manually in #149402.
