### PR TITLE
[LLD][X86] Match delayLoad thunk with MSVC

### LINKED ISSUE #51941: lld-link /delayload - first call of a function with bad floating point parameter on x64
|  |  |
| --- | --- |
| Bugzilla Link | [52599](https://llvm.org/bz52599) |
| Version | 13.0 |
| OS | Windows NT |
| Attachments | [Source files to reproduce the bug](https://user-images.githubusercontent.com/95090372/143762741-762504a6-e254-42d4-a64d-113aedf8beb2.gz) |

## Extended Description 

When linking a program with a DLL using the /delayload switch, the first call to a function defined in the DLL will get bad value for (at least one of) the floating point parameters.

Attached are 2 sources file my_lib.cpp and my_exe.cpp to reproduce the bug. They should be built as folow:
 - "C:\Program Files\LLVM\bin\clang-cl.exe" my_lib.cpp /link /DLL /OUT:my_dll.dll
 - "C:\Program Files\LLVM\bin\clang-cl.exe" /c my_exe.cpp /OUT:my_exe.obj
 - "C:\Program Files\LLVM\bin\lld-link.exe" my_dll.lib Delayimp.lib /delayload:my_dll.dll my_exe.obj /OUT:my_exe.exe

When running my_exe.exe, the output will be "1 0 3" instead of the expected "1 2 3".

The last step can be replaced with
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\link.exe" my_dll.lib Delayimp.lib /delayload:my_dll.dll my_exe.obj /OUT:my_exe.exe
to use link.exe with the same options or with
"C:\Program Files\LLVM\bin\lld-link.exe" my_dll.lib my_exe.obj /OUT:my_exe.exe
to use lld with /delayload. In both of those cases the resulting executable will give the expected "1 2 3".

I believe the bug occurs because __delayLoadHelper2 (the function defined in delayimp.lib that actually loads the DLL and locate the function we want to call during the first usage) writes into the top of the stack space of its caller (I don't know why, is it a weird Windows caling convention?) but the thunk generated by lld doesn't that space.

Specifically, the thunk generated by lld (for x64) looks like this:
push        rcx  
push        rdx  
push        r8  
push        r9  
sub         rsp,48h  
movdqa      xmmword ptr [rsp],xmm0  
movdqa      xmmword ptr [rsp+10h],xmm1  
movdqa      xmmword ptr [rsp+20h],xmm2  
movdqa      xmmword ptr [rsp+30h],xmm3  
mov         rdx,rax  
lea         rcx,[__xt_z+28h (01401C9E88h)]  
call        __delayLoadHelper2 (01401A3464h)  
movdqa      xmm0,xmmword ptr [rsp]  
movdqa      xmm1,xmmword ptr [rsp+10h]  
movdqa      xmm2,xmmword ptr [rsp+20h]  
movdqa      xmm3,xmmword ptr [rsp+30h]  
add         rsp,48h  
pop         r9  
pop         r8  
pop         rdx  
pop         rcx  
jmp         rax

(it allocates space on the stack and uses it to save the register prior to calling __delayLoadHelper2 and restore them later)

Whereas the thunk generated by link.exe looked like that:
mov         qword ptr [rsp+8],rcx  
mov         qword ptr [rsp+10h],rdx  
mov         qword ptr [rsp+18h],r8  
mov         qword ptr [rsp+20h],r9  
sub         rsp,68h  
movdqa      xmmword ptr [rsp+20h],xmm0  
movdqa      xmmword ptr [rsp+30h],xmm1  
movdqa      xmmword ptr [rsp+40h],xmm2  
movdqa      xmmword ptr [rsp+50h],xmm3  
mov         rdx,rax  
lea         rcx,[__DELAY_IMPORT_DESCRIPTOR_my_dll (0140435020h)]  
call        __delayLoadHelper2 (01400089C2h)  
movdqa      xmm0,xmmword ptr [rsp+20h]  
movdqa      xmm1,xmmword ptr [rsp+30h]  
movdqa      xmm2,xmmword ptr [rsp+40h]  
movdqa      xmm3,xmmword ptr [rsp+50h]  
mov         rcx,qword ptr [rsp+70h]  
mov         rdx,qword ptr [rsp+78h]  
mov         r8,qword ptr [rsp+80h]  
mov         r9,qword ptr [rsp+88h]  
add         rsp,68h  
jmp         __tailMerge_my_dll+77h (01402237B8h)  
jmp         rax

It looks very similar but, for some reason, it doesn't save the xmmX register on the top of the stack like lld, it leave 32 bytes that __delayLoadHelper2 is free to mess with.

Indeed, (at least on my machine), the first 2 instruction of __delayLoadHelper2 are:
mov         qword ptr [rsp+10h],rbx  
mov         qword ptr [rsp+18h],rsi  

which, if I'm not mistaken are writting into the stack space where xmm0 and xmm1 were saved.

### PR DESCRIPTION
**Pull request by e-kud**
Previously we saved registers in the shadow space of callee before calling __delayLoadHelper2. Now we save arguments in the shadow space of the caller and allocate shadow space for the callee.

Fixes #51941

### CODE REVIEW

**Comment by e-kud** [comment]
Should there be any specific tests? I'm not very familiar with LLD.

CC @DeChambord

**Comment by DeChambord** [comment]
> Should there be any specific tests? I'm not very familiar with LLD.

Thank you for looking at it. I'm not familiar with the LLD project either, but in essence this issue shows we're missing converage on floating point arguments. Here we want to test that a delayload'ed function such as

```c++
__declspec(dllexport) void foo(double one, double two) {
    ASSERT_EQ(one, 1.0);
    ASSERT_EQ(two, 2.0);
}
```

called with :

```c++
__declspec(dllimport) void foo(double one, double two);
void main () {
    foo(1.0, 2.0);
}
```
Works on the target machine. On the current implementation, the 2nd equality assert would fail on windows.

**Comment by cjacek** [comment]
I think that `tailMergeUnwindInfoX64` should be adjusted to match the new code.

**Comment by e-kud** [comment]
> I think that `tailMergeUnwindInfoX64` should be adjusted to match the new code.

@cjacek thanks! Synced it with `link` as well. I've compared using `llvm-readobj`.

**Comment by e-kud** [comment]
@DeChambord thank you for the smallest reproducer. But I wasn't able to find any existing tests for `delayload` with execution. It looks like `lld` tests are built around gathering object info instead of execution. I've already updated these checks.

**Comment by e-kud** [comment]
@cjacek ping

File: lld/COFF/DLL.cpp [hunk 1]
```diff
@@ -244,40 +244,36 @@ static const uint8_t thunkX64[] = {
...
+    0x48, 0x8B, 0xD0,                         // mov     rdx, rax
+    0x48, 0x8D, 0x0D, 0, 0, 0, 0,             // lea     rcx, [___DELAY_IMPORT_...]
+    0xE8, 0, 0, 0, 0,                         // call    __delayLoadHelper2
+    0x66, 0x0F, 0x6F, 0x44, 0x24, 0x20,       // movdqa  xmm0, xmmword ptr [rsp+20h]
+    0x66, 0x0F, 0x6F, 0x4C, 0x24, 0x30,       // movdqa  xmm1, xmmword ptr [rsp+30h]
+    0x66, 0x0F, 0x6F, 0x54, 0x24, 0x40,       // movdqa  xmm2, xmmword ptr [rsp+40h]
+    0x66, 0x0F, 0x6F, 0x5C, 0x24, 0x50,       // movdqa  xmm3, xmmword ptr [rsp+50h]
+    0x48, 0x8B, 0x4C, 0x24, 0x70,             // mov     rcx, qword ptr [rsp+70h]
+    0x48, 0x8B, 0x54, 0x24, 0x78,             // mov     rdx, qword ptr [rsp+78h]
+    0x4C, 0x8B, 0x84, 0x24, 0x80, 00, 00, 00, // mov     r8, qword ptr [rsp+80h]
```
Comment (cjacek) [inline lld/COFF/DLL.cpp:265]: It's unfortunate that it doesn't pass clang-format, but the original code didn't either, and I don't see a good way to improve it. Please use 0 instead of 00 for those constants. It's more consistent and helps keep within the 80-column limit.

Other than that, looks good to me, thanks.

**Review by cjacek — APPROVED** [review]
LGTM, thanks.

**Comment by mstorsjo** [comment]
This looks like a fix that we should consider backporting to the 21.x release branch.
