### PR TITLE
[clang-doc] switched from using relative to absolute paths

### LINKED ISSUE #92867: Clang-Doc side bar not navigating correctly
Clang-doc doesn't produce the correct path for the side bar it generates for html output

as an example here is its output for zlib

clang-doc-sidebar

clicking the first link in the side bar leads to

zlib/docs/GlobalNamespace/GlobalNamespace/@nonymous_record_42DE8625D17BE7615605FD2BBF5D2761C23AE2E6.html

which is the incorrect path it should be 

zlib/docs/GlobalNamespace/@nonymous_record_42DE8625D17BE7615605FD2BBF5D2761C23AE2E6.html

### PR DESCRIPTION
**Pull request by PeterChou1**
fixes https://github.com/llvm/llvm-project/issues/92867

This patches changes the way clang-doc index navigation works, previously it was based a relative path approach, this approach is error prone and lead to wrong paths for the anchor tag. The new navigation way is based on absolute paths and should work and be less confusing codewise. 
Because the differences with serving over a http server and viewing via file system I also added export a RootPath variable to the index_json.js file

### CODE REVIEW

File: clang-tools-extra/clang-doc/assets/index.js [hunk 1]
```diff
@@ -1,48 +1,22 @@
...
-
-    ANode = document.createElement("a");
+  ANode = document.createElement("a");
   ANode.setAttribute("href", Path);
   var TextNode = document.createTextNode(Ref.Name);
   ANode.appendChild(TextNode);
   return ANode;
 }
 
+
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/assets/index.js:19]: nit: unrelated new line

**Review by ilovepi — CHANGES_REQUESTED** [review]
I'm not completely sure we want to use absolute paths, but since this mostly seems related to URLs and not file system paths, its probably fine.

Please add some tests for this. It's preferable if we can pre-commit tests with the existing behavior, and then can easily see how this patch modifies the old/undesirable behavior.

Lastly, please update the title:
```[clang-doc] Use absolute paths in URLs
```
and update the description to describe what this fixes and how, and links to the GitHub issue using `fixes` or something equivalent from https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

File: clang-tools-extra/clang-doc/assets/index.js [hunk 2]
```diff
@@ -1,48 +1,22 @@
...
-    Path = Path.substring(0, Path.lastIndexOf("/"));
+function genLink(Ref) {
+  var Path = `${window.location.protocol}//${window.location.host}/${Ref.Path}`;
+  if (Ref.RefType !== "namespace") {
+    if (Ref.Path === "") {
+      Path = `${Path}${Ref.Name}.html`;
+    }
+    else {
+      Path = `${Path}/${Ref.Name}.html`;
+    }
```
[the remark this answers is not in the document]
Comment (ilovepi) [reply clang-tools-extra/clang-doc/assets/index.js:9]: oh, the other path has a `/` ... I missed that. Its fine to ignore this comment.

[the remark this answers is not in the document]
Comment (ilovepi) [reply clang-tools-extra/clang-doc/assets/index.js:9]:
```suggestion
  if (Ref.RefType !== "namespace") {
    if (Ref.Path === "") {
      Path = `${Path}${Ref.Name}.html`;
    } else {
      Path = `${Path}/${Ref.Name}.html`;
    }
```
I would still probably format it slightly differently though.

File: clang-tools-extra/test/clang-doc/basic-project.test [hunk 3]
```diff
@@ -7,6 +7,7 @@
 // RUN: FileCheck %s -input-file=%t/docs/GlobalNamespace/Rectangle.html -check-prefix=HTML-RECTANGLE
 // RUN: FileCheck %s -input-file=%t/docs/GlobalNamespace/Circle.html -check-prefix=HTML-CIRCLE
 
+// JSON-INDEX: var RootPath = "{{.*}}";
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/basic-project.test:10]: This is a URL, right? if so, is there a reason it wouldn't match, regardless of platform? I'm a bit surprised this is the only change required to the tests, so I'm wondering if we're doing a good job checking things in our existing HTML tests.

File: clang-tools-extra/clang-doc/HTMLGenerator.cpp [hunk 4]
```diff
@@ -979,6 +980,17 @@ static llvm::Error serializeIndex(ClangDocContext &CDCtx) {
                                    "error creating index file: " +
                                        FileErr.message());
   }
+  llvm::SmallString<128> RootPath(CDCtx.OutDirectory);
+  if (llvm::sys::path::is_relative(RootPath)) {
+    llvm::sys::fs::make_absolute(RootPath);
+  }
+  // replace escape character with forward slash it shouldn't matter
+  // when viewing from the browser this helps with preventing javascript
+  // from escaping unwanted characters leading to bad paths
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/HTMLGenerator.cpp:989]: Can you use sentences and punctuation here?

Maybe something along these lines?
```suggestion
  // Replace the escaped characters with a forward slash. It shouldn't matter
  // when rendering the webpage in a web browser. This helps to prevent the
  // JavaScript from escaping characters incorrectly, and introducing  bad paths
  // in the URLs.
```

File: clang-tools-extra/clang-doc/assets/index.js [hunk 5]
```diff
@@ -1,12 +1,19 @@
 function genLink(Ref) {
   var Path = `${window.location.protocol}//${window.location.host}/${Ref.Path}`;
+  var isFileProtocol = window.location.protocol.startsWith("file");
+  // we treat the file paths different depending on if we're
+  // serving via a http server or viewing from a local
+  if (isFileProtocol) {
+    Path = `${window.location.protocol}//${RootPath}/${Ref.Path}`;
+  }
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/assets/index.js:8]: Maybe it makes sense to initialize `Path` w/ the ternary operator? Also, I'm now wondering if we really want `var` here or if this should be declared w/ `let`.  

This should improve the performance slightly, since `Path` is only initialized once, and saves at least 1 allocation on the JS heap. My JS is pretty weak though, so if I'm wrong on that, I'm happy to defer.

```suggestion
  let isFileProtocol = window.location.protocol.startsWith("file");
  // We treat the file paths different depending on if we're
  // serving via a http server or viewing from a local.
  var Path =  isFileProtocol ?  `${window.location.protocol}//${RootPath}/${Ref.Path}` :`${window.location.protocol}//${window.location.host}/${Ref.Path}`;
```

File: clang-tools-extra/clang-doc/assets/index.js [hunk 6]
```diff
@@ -1,12 +1,19 @@
...
     if (Ref.Path === "") {
       Path = `${Path}${Ref.Name}.html`;
-    }
-    else {
+    } else {
       Path = `${Path}/${Ref.Name}.html`;
     }
+  } else {
+    Path = `${Path}/index.html`
   }
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/assets/index.js:17]: I'm also wondering if we should reverse the logic here to be slightly easer to follow.
```
if(Ref.RefType === "namespace"){
  Path = `${Path}/index.html`
} else {
 //...
}
```
It's not really any functional change, though. IIRC in JS the ordering of statements has some performance impact, so I guess the ordering should be determined by which case we think is more common? Then again, you'd hope anything that affects performance would hit the JIT and get optimized nicely, so maybe this whole point is moot in practice.

I'll leave the final determination up to you, since you deal w/ JS and website performance more frequently than I do.

**Review by ilovepi — COMMENTED** [review]
This is almost there. I've left a few minor comments, but I'd like to see better testing here. I'm awfully surprised we don't need to update any test lines, other than the 1 JS check. It would really help to see how the output is changing, if that was captured in the tests.

File: clang-tools-extra/clang-doc/assets/index.js (hunk 6 above)
Comment (PeterChou1) [reply clang-tools-extra/clang-doc/assets/index.js]: I don't think this will make a meaningful performance difference either way. Although I agree for readability purposes this is much more concise I've updated the code to reflect this

File: clang-tools-extra/test/clang-doc/basic-project.test (hunk 3 above)
Comment (PeterChou1) [reply clang-tools-extra/test/clang-doc/basic-project.test]: This isn't a url, this variable is a path to the directory where clang-doc is built from. I wanted the html to still render properly when viewed via the local filesystem so I added this export variable.
Most the changes that is reflected in this patch can only be seen once the browser loads the page and javascript generates the sidebar with the indexes, I don't think its possible to see the changes reflected unless we incorporate some sort javascript test framework. We could also just generate the indexes via the c++ html generator than we be able to see the changes.
I've added some test that test the different behaviour when we generate clang-doc via a relative path or an absolute one, though

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 7]
```diff
@@ -0,0 +1,7 @@
+// RUN: rm -rf %t
+// RUN: mkdir %t
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:2]: nit: Can be one line w/ `&&`

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 8]
```diff
@@ -0,0 +1,7 @@
...
+// RUN: echo "CHECK: var RootPath = \"%t\";" > %t/check.txt
+// RUN: cp "%s" "%t/test.cpp"
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp]: what is this doing? `CHECK` lines belong in the test file, generally. If you need to split them up somehow, there is the `split-file` utility (https://llvm.org/docs/TestingGuide.html#extra-files). But in this case, you don't need that at all, since these lines can be in this file

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 9]
```diff
@@ -0,0 +1,7 @@
...
+// RUN: clang-doc --doxygen --executor=standalone -p %t %t/test.cpp -output=%t/docs
+// RUN: FileCheck %t/check.txt -input-file=%t/docs/index_json.js
+// RUN: rm -rf %t
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:7]: the `rm -rf` line should be first. It's very useful to be able to examine the test files you generate when they break. If you do it this way, its likely that they're deleted. Also, unless there's gong to be a need for multiple directories, I don't think you need anything but `%t`.

File: clang-tools-extra/test/clang-doc/test-path-relative.cpp [hunk 10]
```diff
@@ -0,0 +1,8 @@
+// RUN: rm -rf %t
+// RUN: mkdir %t
+// RUN: cp "%s" "%t/test.cpp"
+// RUN: clang-doc --doxygen --executor=standalone -p %t %t/test.cpp -output=../docs
+// RUN: FileCheck %s -input-file=%t/docs/index_json.js
+// RUN: rm -rf %t
+
+// CHECK: var RootPath = "{{.*}}../docs";
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-relative.cpp]: You don't need this file. All the checks can go in the other file. You can separate them w/ different identifiers w/ `--check-prefixes=FOO` in `FileCheck` commands. If you look at almost any test folder in LLVM you'll see examples. Also, https://llvm.org/docs/CommandGuide/FileCheck.html#cmdoption-FileCheck-check-prefix.

Also, don't copy files that aren't needed. `%s` is good enough for all the cases that I see.

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 11]
```diff
@@ -0,0 +1,7 @@
...
+// RUN: mkdir %t
+// RUN: echo "CHECK: var RootPath = \"%/t/docs\";" > %t/check.txt
+// RUN: cp "%s" "%t/test.cpp"
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:4]: I see you're trying to work around the path inconsistency issues, but that's just an end-around our testing practices, and we shouldn't be doing it. Tests server as documentation, and generating a test w/ `CHECK` lines undermines that pretty significantly. IMO if the test isn't useful w/ the regular expression, it isn't useful. As it stands I also can't reason about how the behavior here is changing as a result of this patch, so I don' think this is a particularly good/useful check.

If possible, it would be good to add these tests in another patch(e.g. pre-commit them testing the current behavior), and then update these to make them pass. That requires either stacking the PR using [spr](https://github.com/spacedentist/spr), or just managing the github PRs carefully yourself. Either is fine.

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 12]
```diff
@@ -0,0 +1,7 @@
...
+// RUN: clang-doc --format=html --executor=standalone -p %t %t/test.cpp --output=%t/docs
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:5]:
```suggestion
// RUN: clang-doc --format=html --executor=standalone  %s --output=%t
```
I don't think you need `-p`, and I don't see a good reason why you need a subdirectory for `docs`.

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 13]
```diff
@@ -0,0 +1,7 @@
...
+// RUN: FileCheck %t/check.txt -input-file=%t/docs/index_json.js
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:6]:
```suggestion
// RUN: FileCheck %s -input-file=%t/index_json.js --check-prefix=SOME_PREFIX
```

File: clang-tools-extra/test/clang-doc/basic-project.test (hunk 3 above)
Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/basic-project.test]: Oh, then I'm not 100% sure we want to replace all the `\` w/ `/`. I know you mentioned browser behavior, but I'm not 100% certain that's a great motivation. When I thought it was a URL, there's obviously no issue, but, for a file system path, I'm hesitant to say with confidence that there's no downside.

Also, given the test updates, IDK if this check is particularly useful. I don't see much difference in the check as is, and just 
```
// JSON-INDEX: var RootPath =
```

**Comment by ilovepi** [comment]
any progress here?

**Comment by PeterChou1** [comment]
> any progress here?

I wanted to merge the test cases prs so we could view the regressions from the tests

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 14]
```diff
@@ -0,0 +1,7 @@
+// RUN: rm -rf %t && mkdir %t
+// RUN: cp "%s" "%t/test.cpp"
+// RUN: clang-doc --format=html --executor=standalone -p %s --output=%t
+// RUN: FileCheck %s -input-file=%t/index_json.js  -check-prefix=JSON-INDEX
+// RUN: rm -rf %t
+
+// JSON-INDEX: var RootPath = "{{.*}}";
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:7]: Is there a way to make this check more meaningful? Can we match nothing in the path itself?

**Review by ilovepi — APPROVED** [review]
LGTM, but can we improve the check for RootPath somehow? I feel like there should be something we can match there.

**Comment by ilovepi** [comment]
Hmm, seems like tests are failing. PTAL.

File: clang-tools-extra/test/clang-doc/test-path-abs.cpp [hunk 15]
```diff
@@ -0,0 +1,7 @@
+// RUN: rm -rf %t && mkdir %t
+// RUN: cp "%s" "%t/test.cpp"
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/test-path-abs.cpp:2]: Looks like I missed this. Please don’t copy the test file around. To be blunt this pattern has been brought up in multiple PRs and even in previous incarnations of this one. Use the same conventions we’ve insisted on in other tests here.

Comment (PeterChou1) [reply clang-tools-extra/test/clang-doc/test-path-abs.cpp]: Sorry, the reason why I kept using this pattern is because I copied the same test setups in the original test for clang-doc [here](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/test/clang-doc/single-file.cpp#L4) and [here](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/test/clang-doc/single-file-public.cpp#L4)
