### PR TITLE
[C2y] Fix _Countof handling of VLAs

### LINKED ISSUE #141409: [Clang] C2Y `_Countof` weird sub-array count with multidimensional VLA
This snippet:
```
#include <stdio.h>
int main(int i, char**) {
    int arr[11][++i][33][++i];

    printf("%lu\t", _Countof arr);
    printf("%lu\t", _Countof *arr);
    printf("%lu\t", _Countof **arr);
    printf("%lu\t", _Countof ***arr);
    printf("\n");
    printf("%lu\t",  sizeof arr / sizeof *arr);
    printf("%lu\t",  sizeof *arr / sizeof **arr);
    printf("%lu\t",  sizeof **arr / sizeof ***arr);
    printf("%lu\t",  sizeof ***arr / sizeof ****arr);
    printf("\n\t^ here\n");
}
```
prints the following with current Godbolt trunk and clang-21 in LLVM Debian nightly:
```
11	198	33	3	
11	2	33	3	
	^ here
```
The second output looks funny, if I understand _Countof correctly it should be `2` instead of `2*33*3`.
Godbolt: https://godbolt.org/z/o1c6bWosM

### PR DESCRIPTION
**Pull request by AaronBallman**
It turns out that getVLASize() does not get you the size of a single dimension of the VLA, it gets you the full count of all elements. This caused _Countof to return invalid values on VLA ranks. Now switched to using getVLAElements1D() instead, which only gets a single dimension.

Fixes #141409

### CODE REVIEW

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 1]
```diff
@@ -3574,20 +3574,26 @@ ScalarExprEmitter::VisitUnaryExprOrTypeTraitExpr(
...
+        llvm::Value *Size;
         if (Kind != UETT_CountOf) {
+          auto VlaSize = CGF.getVLASize(VAT);
+          Size = VlaSize.NumElts;
+
           // Scale the number of non-VLA elements by the non-VLA element size.
           CharUnits eltSize = CGF.getContext().getTypeSizeInChars(VlaSize.Type);
           if (!eltSize.isOne())
-            size = CGF.Builder.CreateNUWMul(CGF.CGM.getSize(eltSize), size);
+            Size = CGF.Builder.CreateNUWMul(CGF.CGM.getSize(eltSize), Size);
```
Comment (erichkeane) [inline clang/lib/CodeGen/CGExprScalar.cpp:3588]: I find myself wondering whether 'early return 'would make this all easier.  Also, I would expect the builder's constant folder to make the `eltSize ==1` case a no-op anyway, so we might just be able to make this whole branch:

return CGF.Builder.CreateNUWMul(CGF.CGM.getSize(eltSize), VlaSize.NumElts).

Though, enough of this is pre-existing, *eh*.

**Review by erichkeane — APPROVED** [review]

**Review by efriedma-quic — APPROVED** [review]
LGTM
