### PR TITLE
[sanitizer_common] AND signals in BlockSignals instead of deleting

### LINKED ISSUE #113385: Sanitizers unblock user blocked signals
Regression after #98200

### PR DESCRIPTION
**Pull request by thurstond**
My earlier patch https://github.com/llvm/llvm-project/pull/98200 caused a regression because it unconditionally unblocked synchronous signals, even if the user program had deliberately blocked them. This patch fixes the issue by checking the current signal mask, as suggested by Vitaly.

Fixes #113385

### CODE REVIEW

File: compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp [hunk 1]
```diff
@@ -164,33 +164,45 @@ void SetSigProcMask(__sanitizer_sigset_t *set, __sanitizer_sigset_t *oldset) {
...
+  SetSigProcMask(NULL, &currentset);
+
+  __sanitizer_sigset_t newset;
+  internal_sigfillset(&newset);
 #  if SANITIZER_LINUX && !SANITIZER_ANDROID
   // Glibc uses SIGSETXID signal during setuid call. If this signal is blocked
   // on any thread, setuid call hangs.
   // See test/sanitizer_common/TestCases/Linux/setuid.c.
-  internal_sigdelset(&set, 33);
+  KeepUnblocked(&newset, &currentset, 33);
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:186]: It should apply to all of them

**Review by vitalybuka — APPROVED** [review]
It would be nice to test, but I guess it's hard with lit-test.
Maybe in common unit test.

**Comment by vitalybuka** [comment]
After the merge, we need to request cherry pick into 19

**Comment by thurstond** [comment]
> It would be nice to test, but I guess it's hard with lit-test. Maybe in common unit test.

I've added a test, please review.

File: compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+
+namespace __sanitizer {
+
+#if SANITIZER_LINUX
+volatile int received_sig = -1;
+
+void signal_handler(int signum) { received_sig = signum; }
+
+TEST(SanitizerCommon, BlockSignals) {
+  // No signals blocked
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp:26]: Instead of large test with 3 `{}`
please split into 3
```
TEST(SanitizerCommon, BlockSignal{Name1, Name2, Name3}) {
}
````

File: compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+  {
+    signal(SIGUSR1, signal_handler);
+    raise(SIGUSR1);
+    while (received_sig == -1) sleep(1);
+    EXPECT_EQ(received_sig, SIGUSR1);
+
+    received_sig = -1;
+    signal(SIGPIPE, signal_handler);
+    raise(SIGPIPE);
```
Comment (vitalybuka) [inline compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp:35]: do we need to sleep?

**Review by vitalybuka — APPROVED** [review]

File: compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp (hunk 2 above)
Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp:26]: Done

File: compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp (hunk 3 above)
Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/tests/sanitizer_block_signals.cpp]: Removed
