### PR TITLE
[Sema] Fix -Wunreachable-code false negative when operands differ only by implicit casts

### LINKED ISSUE #149967: Incorrect tautology diagnostic with native half‑precision
`-Wunreachable-code` is silent on targets with native FP16 support
----------------------------------------------------------------------------

### Problem
The tautology/contradiction check in **`CheckIncorrectLogicOperator`** fails on targets with **native scalar FP16** (e.g., AArch64 `+fullfp16`). It still works on x86‑64, so the lapse went unnoticed.

| Triple | FP16 handling | Warning? |
| ------ | ------------- | -------- |
| `x86_64-unknown-linux-gnu` | `__fp16` / `_Float16` are *promoted* to `float` (extra cast) | ✔️ emitted |
| `aarch64-unknown-linux-gnu +fullfp16` | no promotion for `_Float16`(native arithmetic) | ❌ **missing** |

---

### Why promotion hides the bug

```c
static void test(_Float16 x) {
  if (x != 0 || x != 1.0)   // should warn: always true
    x = 0.9;
  else
    x = 0.8;
}
```

#### x86‑64 AST — *warning appears*
```text
BinaryOperator 0x555564fcdfc0 '_Bool' '!='
|-ImplicitCastExpr 0x555564fcdf90 'float' **<FloatingCast>**
| -ImplicitCastExpr 0x555564fcdf78 '_Float16' <LValueToRValue>
|   -DeclRefExpr 0x555564fcdf38 '_Float16' lvalue ParmVar 0x555564fcdd78 'x' '__fp16 &'
-ImplicitCastExpr 0x555564fcdfa8 'float' <IntegralToFloating>
  -IntegerLiteral 0x555564fcdf58 'int' 0

BinaryOperator 0x555564fce050 '_Bool' '!='
|-ImplicitCastExpr 0x555564fce038 'double' **<FloatingCast>**
| -ImplicitCastExpr 0x555564fce020 '_Float16' <LValueToRValue>
|   -DeclRefExpr 0x555564fcdfe0 '_Float16' lvalue ParmVar 0x555564fcdd78 'x' '__fp16 &'
`-FloatingLiteral 0x555564fce000 'double' 1.000000e+00
```
AArch64 +fullfp16 AST — warning lost
```text
BinaryOperator 0x55556438dbe8 '_Bool' '!='
|-ImplicitCastExpr 0x55556438dbb8 '_Float16' **<LValueToRValue>**
| -DeclRefExpr 0x55556438db78 '_Float16' lvalue ParmVar 0x55556438d9b8 'x' '__fp16 &'
-ImplicitCastExpr 0x55556438dbd0 '_Float16' <IntegralToFloating>
  -IntegerLiteral 0x55556438db98 'int' 0

BinaryOperator 0x55556438dc78 '_Bool' '!='
|-ImplicitCastExpr 0x55556438dc60 'double' **<FloatingCast>**
| -ImplicitCastExpr 0x55556438dc48 '_Float16' <LValueToRValue>
|   -DeclRefExpr 0x55556438dc08 '_Float16' lvalue ParmVar 0x55556438d9b8 'x' '__fp16 &'
-FloatingLiteral 0x55556438dc28 'double' 1.000000e+00
```
No FloatingCast → operands’ cast chains differ →`Expr::isSameComparisonOperand()` returns false → diagnostic short‑circuits.

### PR DESCRIPTION
**Pull request by codemzs**
## Motivation  
`-Wunreachable-code` missed—or in rare cases crashed on—tautological comparisons such as

```cpp
x != 0 || x != 1.0   // always true
x == 0 && x == 1.0   // always false
```

when the *same* variable appears on both sides but one operand goes through a floating‑rank promotion that is target‑dependent.  On back‑ends with **native half‑precision** (`_Float16` / `__fp16`) such as AArch64 `+fullfp16`, no promotion occurs, so the cast stacks between the two operands differ and the existing heuristic bails out.

## Technical description 
* **Extends `Expr::isSameComparisonOperand()`** – the helper now ignores parentheses **and value‑preserving implicit casts** (`CK_LValueToRValue`, floating‑rank `CK_FloatingCast`) before comparing the underlying operands. This prevents floating‑rank promotions and lvalue‑to‑rvalue conversions from blocking the unreachable‑code diagnostic on targets with native FP16. 
*No change needed in `CheckIncorrectLogicOperator`; it simply benefits from the improved helper.*  
* **Regression test** – `warn-unreachable_crash.cpp` updated to cover both the promoted case (x86‑64) and the native‑half case (AArch64 `+fullfp16`).  
* **Docs** – release‑note bullet added under *Bug Fixes in This Version*.

@ziqingluo-90  @yronglin  Could you please review promptly? (feel free to also merge it on my behalf) Thanks!

Fixes #149967

### CODE REVIEW

**Comment by codemzs** [comment]
@gribozavr  @sgatev  @AaronBallman 

Could you please review when you have a moment?

File: clang/lib/Analysis/CFG.cpp [hunk 1]
```diff
@@ -1160,8 +1160,11 @@ class CFGBuilder {
       return {};
 
     // Check that it is the same variable on both sides.
-    if (!Expr::isSameComparisonOperand(DeclExpr1, DeclExpr2))
-      return {};
+    if (!Expr::isSameComparisonOperand(DeclExpr1, DeclExpr2)) {
+      if (!Expr::isSameComparisonOperand(DeclExpr1->IgnoreParenImpCasts(),
+                                         DeclExpr2->IgnoreParenImpCasts()))
+        return {};
```
Comment (AaronBallman) [inline clang/lib/Analysis/CFG.cpp:1166]: This doesn't seem correct to me; `isSameComparisonOperand` explicitly handles implicit cast expressions, so stripping them off here seems like the wrong place to handle this.

File: clang/test/Sema/warn-unreachable_crash.cpp [hunk 2]
```diff
@@ -1,16 +1,33 @@
-// RUN: %clang_cc1 -verify -Wunreachable-code %s
+// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -verify -Wunreachable-code %s
+// RUN: %clang_cc1 -triple aarch64-unknown-linux-gnu -target-feature +fullfp16 -verify -Wunreachable-code %s
+// REQUIRES: aarch64-registered-target
```
Comment (AaronBallman) [inline clang/test/Sema/warn-unreachable_crash.cpp:3]: Why does this require a specific target?

File: clang/test/Sema/warn-unreachable_crash.cpp [hunk 3]
```diff
@@ -1,16 +1,33 @@
...
+  } else
+    x = 0.8;                          // expected-warning{{code will never be executed}}
+}
+
+static void test_f16_b(_Float16 &x) {
+  if (x != 1 && x == 1.0) {           // expected-note {{}} no-crash
+    x = 0.9;                          // expected-warning{{code will never be executed}}
+  } else
+    x = 0.8;
+}
```
Comment (AaronBallman) [inline clang/test/Sema/warn-unreachable_crash.cpp:33]: Please add a newline to the end of the file.

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on a fix here! I'm not certain this is the right direction because `isSameComparisonOperand` expects to get implicit cast nodes and they're now being stripped. So I think some more investigation is needed on the solution.

File: clang/lib/Analysis/CFG.cpp (hunk 1 above)
Comment (codemzs) [reply clang/lib/Analysis/CFG.cpp:1166]: I call `isSameComparisonOperand` **twice** (with and without striping away explicit handles to implicit casts to preserve existing behavior), but let me explain why the extra `IgnoreParenImpCasts()` call is necessary:

`isSameComparisonOperand()` only recurses past an `ImplicitCastExpr` when the two cast nodes have the same CastKind (see the early‑exit check in the existing implementation).

In the motivating bug, the two operands differ in both the number and the kind of implicit casts:
```code
LHS: ImplicitCastExpr <LValueToRValue>
        DeclRefExpr ‘__fp16 &’  (lvalue)

RHS: ImplicitCastExpr <FloatingCast>
        ImplicitCastExpr <LValueToRValue>
            DeclRefExpr ‘__fp16 &’  (lvalue)
```

Because `FloatingCast` != `LValueToRValue` the first comparison fails on the CastKind test and the function bails out before it ever reaches the underlying `DeclRefExprs`.

Calling `IgnoreParenImpCasts()` on the first failure path in `CheckIncorrectLogicOperator`:

1. **Preserves the original fast‑path** (identical cast stacks are still handled without any extra work).

2. Avoids touching `isSameComparisonOperand()`, whose current behavior is relied upon by other clients in Sema and Analysis. Broadening it to ignore all cast‑kind differences would risk new false‑positives in those callers.

3. Targets only the problematic pattern: same variable, operands differ solely by implicit casts or parens.

Empirically, with this fallback in place we now diagnose the half‑precision tautology.

The local fallback in `CheckIncorrectLogicOperator` keeps the original fast path intact, touches only this diagnostic, and fixes the FP16 false‑negative (and the crash) without affecting other warnings.

Happy to add a code comment to spell this out if that helps.  Let me know whether that addresses the concern, or if you’d still prefer a different approach.

Comment (AaronBallman) [reply clang/lib/Analysis/CFG.cpp:1166]: Thank you for the explanation, that was helpful!

Perhaps dumb question: would it make more sense to have the cast checks in `isSameComparisonOperand()` single-step through the casts to find matching ones? Because it seems a bit odd that inserting a Noop cast in one node but not the other would mean they're automatically different comparison operands.

File: clang/test/Sema/warn-unreachable_crash.cpp (hunk 3 above)
Comment (codemzs) [reply clang/test/Sema/warn-unreachable_crash.cpp:33]: Done

File: clang/lib/Analysis/CFG.cpp (hunk 1 above)
Comment (codemzs) [reply clang/lib/Analysis/CFG.cpp]: Thanks, I have moved the check into `isSameComparisonOperand()`

**Comment by codemzs** [comment]
> Thank you for working on a fix here! I'm not certain this is the right direction because `isSameComparisonOperand` expects to get implicit cast nodes and they're now being stripped. So I think some more investigation is needed on the solution.

@AaronBallman I have updated the PR with what we discussed. Please let me know if you have any questions.

**Review by AaronBallman — COMMENTED** [review]
I think this looks correct to me now, but I'd like to leave the final sign-off to @yronglin because they did the original review on #142897

**Comment by yronglin** [comment]
LGTM! Could you add a release notes?

**Review by yronglin — APPROVED** [review]

**Comment by yronglin** [comment]
> @AaronBallman @yronglin Thank you for the review. I don't have write permissions, can one of you please sign-off and push the change for me? Thanks!

Sure!

**Comment by codemzs** [comment]
> > @AaronBallman @yronglin Thank you for the review. I don't have write permissions, can one of you please sign-off and push the change for me? Thanks!
> 
> Sure! Could you add a release notes(in clang/docs/ReleaseNotes.rst Bug Fixes in This Version section)? You can follow the style of previous items.

@yronglin Done.

**Review by yronglin — APPROVED** [review]
LGTM
