### PR TITLE
[CodeGen][i386] Move -mregparm storage earlier and fix Runtime calls

### LINKED ISSUE #89670: Sanitizer handler calls emitted without regard to `-mregparm`
When sanitizer calls are emitted, the `-mregparm=3` option used by the Linux kernel appears to be ignored. For example, here is a build where the argument are being pushed instead of placed in `%eax` and `%edx` (from `lkdtm_ARRAY_BOUNDS`):

```asm
   0xc18e3a5a <+202>:   push   %ebx
   0xc18e3a5b <+203>:   push   $0xc26001a0
   0xc18e3a60 <+208>:   call   0xc157d430 <__ubsan_handle_out_of_bounds>
```

The kernel's handler isn't expecting them on the stack. For example, this is setting a bit in the sanitizer's passed-in data structure (from `__ubsan_handle_out_of_bounds`):

```asm
   0xc157d491 <+97>:    btsl   $0x1f,%ds:0x4(%eax)
   0xc157d497 <+103>:   jae    0xc157d4a1 <__ubsan_handle_out_of_bounds+113>

```

https://github.com/KSPP/linux/issues/350

### PR DESCRIPTION
**Pull request by kees**
When building the Linux kernel for i386, the -mregparm=3 option is enabled. Crashes were observed in the sanitizer handler functions, and the problem was found to be mismatched calling convention.

As was fixed in commit c167c0a4dcdb ("[BuildLibCalls] infer inreg param attrs from NumRegisterParameters"), call arguments need to be marked as "in register" when -mregparm is set. Use the same helper developed there to update the function arguments.

Since CreateRuntimeFunction() is actually part of CodeGenModule, storage of the -mregparm value is also moved to the constructor, as doing this in Release() is too late.

Fixes: https://github.com/llvm/llvm-project/issues/89670

### CODE REVIEW

**Comment by kees** [comment]
This needs test cases, which I'll add tomorrow. I just wanted to get the core logic up for review before I hit EOD...

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 1]
```diff
@@ -4781,6 +4782,7 @@ CodeGenModule::CreateRuntimeFunction(llvm::FunctionType *FTy, StringRef Name,
         }
       }
       setDSOLocal(F);
+      markRegisterParameterAttributes(F);
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CodeGenModule.cpp:4785]: This really shouldn't work this way: we should go through CodeGenModule::SetLLVMFunctionAttributes to get all the correct attributes for a function.  Unfortunately, that's a bit complicated in this context because you need to construct a CGFunctionInfo, and none of the callers currently do that.  Which might be more work than you really want...  CC @JonPsson1 @jdoerfert @jhuber6

Comment (kees) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: I was trying to basically duplicate what was already done for the libcall functions. What is gained by using CGFunctionInfo? (Things already work as-is -- though generally it does looks like -mregparm support is kinda ad-hoc.)

Comment (kees) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: Oh, I think I see what you mean -- this is the common place where all functions should get their attributes set. Can the libcall code use this? (As in, can we remove `markRegisterParameterAttributes()` entirely and move the logic into `SetLLVMFunctionAttributes()` or is that just fantastic overkill?

Comment (efriedma-quic) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: Zero/sign-extend attributes are also missing, I think.  Which probably doesn't affect x86, but could have obscure effects on some targets.

Using SetLLVMFunctionAttributes here isn't really a problem, except that it takes a clang::Type, not an llvm::Type type, and we only have a conversion in the other direction.  So you'd need to modify the callers.  And there are a lot of callers.

Comment (efriedma-quic) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: To clarify, the code in llvm/ still needs to exist because we need some approximation of the calling convention even if we don't have access to the clang AST.  But clang shouldn't use it; clang's native representation of calling conventions is better.

(It's a long-standing request to try to give LLVM a representation of calling conventions that's closer to clang's representation, but it's a large problem, and nobody has really made any progress on it.)

Comment (kees) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: This seems like a large proposed change; is it worth it for this corner case? I think I would prefer to fix this as I have it now.

Comment (efriedma-quic) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: Sign/zero-extend attributes led to real issues on some targets in the past, so it's not unlikely someone will need to address it at some point.  But maybe it doesn't need to be here.  I guess leave a FIXME noting it as a known issue.

I'm not really happy with exposing this interface on BuildLibCalls.h, since it's really a pretty big footgun (due to the zero/sign-extension issue I mentioned).  But copy-pasting the code is worse, so... I guess leave a comment in the header.

Comment (kees) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: Comment added. Is this what you had in mind?

File: llvm/include/llvm/Transforms/Utils/BuildLibCalls.h [hunk 2]
```diff
@@ -62,6 +62,13 @@ namespace llvm {
                      LibFunc TheLibFunc, AttributeList AttributeList,
                      FunctionType *Invalid, ArgsTy... Args) = delete;
 
+  // Handle -mregparm for the given function.
+  // FIXME: This should likely be implemented in
+  // CodeGenModule::SetLLVMFunctionAttributes() since callers of
+  // markRegisterParameterAttributes() will not have gotten appropriate
+  // attributes for things like sign/zero-extension, etc.
```
Comment (efriedma-quic) [inline llvm/include/llvm/Transforms/Utils/BuildLibCalls.h:69]: This doesn't really properly capture the divide between clang, the frontend, and LLVM the optimizer.

What we want here is basically a warning: this interface shouldn't be used unless you know exactly what you're doing.  Then a FIXME on the clang side to indicate we plan to revise the CreateRuntimeFunction() interface at some point.

Suggested text on the LLVM API:

Note that this function is a rough approximation that only works for simple function signatures.  Note this does not apply other relevant attributes for function signatures, including sign/zero-extension for arguments and return values.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 1 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CodeGenModule.cpp:4785]: Suggested text on the clang change:

FIXME: We should use CodeGenModule::SetLLVMFunctionAttributes() instead of trying to approximate the attributes using the LLVM function signature.  This requires revising the API of CreateRuntimeFunction().

Comment (kees) [reply clang/lib/CodeGen/CodeGenModule.cpp:4788]: Ah-ha, thanks! Okay, I've updated the comments with just a minor tweak.

**Review by efriedma-quic — APPROVED** [review]
LGTM
