### PR TITLE
[lld][Hexagon] Support predicated-add GOT_16_X mask lookup

### LINKED ISSUE #111876: lld fails to handle predicated add instructions w/GOT_16_X relocation
```
$ echo 'if (p0) r0 = add(r0,##bar@GOT)' | llvm-mc -triple=hexagon -filetype=obj -o out.o
$ ld.lld -shared out.o -o out.so
ld.lld: error: unrecognized instruction for 16_X type: 0x7400C000

```

### PR DESCRIPTION
**Pull request by androm3da**
When encountering an instruction like `if (p0) r0 = add(r0,##bar@GOT)`, lld would fail with:
```
ld.lld: error: unrecognized instruction for 16_X type: 0x7400C000
```

This issue was encountered while building libreadline with clang 19.1.0.

Fixes: #111876

### CODE REVIEW

File: lld/ELF/Arch/Hexagon.cpp [hunk 1]
```diff
@@ -181,11 +181,12 @@ static const InstructionMask r6[] = {
     {0xd7000000, 0x006020e0}, {0xd8000000, 0x006020e0},
     {0xdb000000, 0x006020e0}, {0xdf000000, 0x006020e0}};
 
+static uint32_t INST_PARSE_PACKET_END = 0x0000c000;
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:184]: constexpr and don't use upper case . see PPC64.cpp

**Comment by MaskRay** [comment]
You could say `Support` instead of `Fix` as I assume that this was an unsupported case, instead of a bug.

**Comment by androm3da** [comment]
> You could say `Support` instead of `Fix` as I assume that this was an unsupported case, instead of a bug.

Hmm, I thought it was a bug because I figured we'd gotten all these relocations supported.  But okay sure.

File: lld/ELF/Arch/Hexagon.cpp [hunk 2]
```diff
@@ -216,6 +218,12 @@ static uint32_t findMaskR11(uint32_t insn) {
 }
 
 static uint32_t findMaskR16(uint32_t insn) {
+  if (isDuplex(insn))
+    return 0x03f00000;
+
+  // Clear the end-packet-parse bits:
+  insn = insn & ~instParsePacketEnd;
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:225]: `insn &= ...`

**Review by MaskRay — APPROVED** [review]

**Review by SidManning — APPROVED** [review]
