### PR TITLE
[BOLT] Ensure remember and restore CFIs are in the same list

### LINKED ISSUE #133501: [AArch64][BOLT] llvm-bolt annotateCFIState Assertion `!StateStack.empty() && "corrupt CFI stack"' failed.
BOLT version: af150272cff97c121ed4fdb76fce702fbe2f12a3 crashes on [MySQL binary](https://github.com/ilinpv/bolt-tests/raw/0403b9cfe9e9c150fb523122f9962daa1b2150f2/test/AArch64/Inputs/mysqld.zst):
`llvm-bolt mysqld -o mysqld-bolt -instrument --print-disasm -v 1 > mysqld.disasm`
```
...
BOLT-WARNING: failed to post-process indirect branches for _ZL13get_next_timePK9Time_zonePllli13interval_type/1(*2)
BOLT-WARNING: failed to post-process indirect branches for _ZN24Field_iterator_table_ref13end_of_fieldsEv/1(*2)
BOLT-WARNING: failed to post-process indirect branches for _ZN16Event_parse_data13init_intervalEP3THD
llvm-bolt: llvm-project/bolt/lib/Core/BinaryFunction.cpp:2652: void llvm::bolt::BinaryFunction::annotateCFIState(): Assertion `!StateStack.empty() && "corrupt CFI stack"' failed.
```
Presumably that was caused by incorrect remember-restore CFI sequences in the binary.

### PR DESCRIPTION
**Pull request by Asher8118**
In `addCFIInstruction`, we split the CFI information between `CFIInstrMapType CIEFrameInstructions` and `CFIInstrMapType FrameInstructions`. In some cases we can end up with the remember CFI in `CIEFrameInstructions` and the restore CFI in `FrameInstructions`. This patch adds a check to make sure we do not split remember and restore states and fixes https://github.com/llvm/llvm-project/issues/133501.

### CODE REVIEW

File: bolt/include/bolt/Core/BinaryFunction.h [hunk 1]
```diff
@@ -1663,7 +1663,8 @@ class BinaryFunction {
       Offset = I->first;
     }
     assert(I->first == Offset && "CFI pointing to unknown instruction");
-    if (I == Instructions.begin()) {
+    if (I == Instructions.begin() &&
```
Comment (paschalis-mpeis) [inline bolt/include/bolt/Core/BinaryFunction.h:1669]: nit: maybe worth adding a comment that we put this CFI in the `FrameInstructions` instead, so we can properly populate `StateStack` ?

File: bolt/test/AArch64/cfi-state-list.test [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+fmov	x8, d0
+mov	x9, #0x7ff0000000000000
+and	x8, x8, #0x7fffffffffffffff
+cmp	x8, x9
+b.lt main+0x5c
+fcmp	d0, #0.0
+mov	w8, #-0x1
+csinc	w0, w8, wzr, le
+ldr	x30, [sp], #0x10
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/cfi-state-list.test]: Thanks for the test! Can you please minimize it a bit more?

You can drop the majority of instructions that don't contribute to the test and keep only a few dummy ones like `mov, x0 xzr`. Some of the blocks could be dropped as well.

Once cleaned up, you can replace the hardcoded relative addresses to temp labels. Maybe `--asum-dump` could give you hints on where to place those labels, alternatively `objdump` would do.

**Review by paschalis-mpeis — APPROVED** [review]
Hey Ash,

Thanks for improving Bolt! Looks good with a couple of nits below.

Can you also give it a couple of days in case someone has further feedback?

File: bolt/include/bolt/Core/BinaryFunction.h (hunk 1 above)
Comment (Asher8118) [reply bolt/include/bolt/Core/BinaryFunction.h:1669]: Done

File: bolt/test/AArch64/cfi-state-list.test (hunk 2 above)
Comment (Asher8118) [reply bolt/test/AArch64/cfi-state-list.test]: Thanks for the feedback, test has been minimzed.

**Comment by Asher8118** [comment]
The patch should be ready to merge now. I'll give it another day or so before I merge it.
