### PR TITLE
Use the RHS of a pointer assignment inside of FORALL if it is already of `boxType` instead of `convertToBox` again.

### LINKED ISSUE #165055: [flang] Runtime error of `Invalid descriptor` when deallocate an allocated pointer.
Consider the following code:
```
module m
    type base
        integer :: id
    end type

    type container
        !class (base), pointer :: data => null()
        type(base), pointer :: data => null()
    end type

    contains

    pure function makeData (i)
        type (base), pointer :: makeData
        integer*4, intent(in) :: i

        allocate (makeData)

        makeData = base(i)
    end function


end module

program fpAssgn016
use m
    type (container) :: co1(10)

   forall (i=1:10)
!   do i = 1,10                           !! work around
        co1(i)%data => makeData (i)
!   end do
    end forall

    do i =1, 10
        deallocate (co1(i)%data)
    end do

end
```

Flang failed at the runtime as
```
> a.out

fatal Fortran runtime error(t.f:36): Invalid descriptor
Abort(coredump)
```

This failure seems a regression after the merge of PR #164279. However, if I changed the LHS to be NOT polymorphic, it still fails the same.

It seems the "allocatable" property got lost through the pointer assignment in FORALL.

### PR DESCRIPTION
**Pull request by DanielCChen**
Fixes #165055.

### CODE REVIEW

File: flang/lib/Optimizer/Builder/TemporaryStorage.cpp [hunk 1]
```diff
@@ -258,13 +258,19 @@ void fir::factory::AnyVariableStack::pushValue(mlir::Location loc,
...
                                                mlir::Value variable) {
   hlfir::Entity entity{variable};
-  mlir::Type storageElementType =
-      hlfir::getFortranElementType(retValueBox.getType());
-  auto [box, maybeCleanUp] =
-      hlfir::convertToBox(loc, builder, entity, storageElementType);
-  fir::runtime::genPushDescriptor(loc, builder, opaquePtr, fir::getBase(box));
-  if (maybeCleanUp)
-    (*maybeCleanUp)();
+  if (mlir::isa<fir::BaseBoxType>(entity.getType())) {
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/TemporaryStorage.cpp]: Would using `hlfir::genVariableBox` here instead of convertToBox solve the issue? (no need to provide a forceBoxType also slove the issue).

If so, that would simplify the code.

**Review by jeanPerier — APPROVED** [review]
LGTM
