### PR TITLE
[Sema] Handle AttributedType in template deduction with derived-to-base conversions

### LINKED ISSUE #134356: Adding _Nonnull attribute causes template deduction to fail
https://gcc.godbolt.org/z/MW94Ezd11

```cpp
template <class T> struct Base {};
template <class T> struct Derived : Base<T> {};

template <class T> void foo(Base<T> *_Nonnull);

template <class T> void bar(Base<T> *);


void test() {
    Derived<int> d;
    foo(&d); // fails.
    bar(&d); // okay.
}
```

### PR DESCRIPTION
**Pull request by ilya-biryukov**
Fix #134356.

We accidentally skipped checking derived-to-base conversions because deduction did not strip sugar in the relevant code. This caused deduction failures when a parameter type had an attribute.

### CODE REVIEW

**Review by gribozavr — APPROVED** [review]

**Review by shafik — COMMENTED** [review]
This should have had a release note.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -4446,7 +4446,7 @@ static bool AdjustFunctionParmAndArgTypesForDeduction(
   //       transformed A can be a pointer to a derived class pointed to by
   //       the deduced A.
   if (isSimpleTemplateIdType(ParamType) ||
-      (isa<PointerType>(ParamType) &&
+      (ParamType->getAs<PointerType>() &&
        isSimpleTemplateIdType(
            ParamType->castAs<PointerType>()->getPointeeType())))
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:4451]: This could avoid searching for the PointerType twice.
