### PR TITLE
[DirectX] Set whole-module flags prior to evaluating per-function flags

### LINKED ISSUE #139024: [DirectX] Max64UAVs shader flag analysis does not pass validation under all cases
error: Flags must match usage.
    66 cases

There are three cases:

1. Flags declared=524336, actual=557104
    32 cases
2. Flags declared=0, actual=32768 
    20 cases
3. Flags declared=48, actual=32816
    14 cases

All three cases are caused by bit 0x8000 not being set when it should be set.
This bit corresponds to the Max64UAVs (64 UAV slots) shader flag.

### LINKED ISSUE #139954: [DirectX] StructuredBuffers with 16 bit types are failing validation
Command: clang-dxc -enable-16bit-types -T cs_6_5 -Fo x.o code-provided.hlsl
```
RWStructuredBuffer<half> Out : register(u1);

[numthreads(1,1,4)]
void main() {
  Out[0] = (half)3.14159;
}
```
Fails validation with the error
```
error: structured buffer element size must be a multiple of 4 bytes (actual size 2 bytes). 'U0: StructuredBuffer (u1)'
Validation failed.
```

Working in dxc: https://godbolt.org/z/enrafEjvq

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #139024 and #139954

- Refactor DXILShaderFlags to compute the flags that apply to a whole module before computing flags that apply individually to each function
- Make DXILResourceMap const, since it is not modified in DXILShaderFlags
- Per-function shader flag analysis now initially starts with the set of flags that apply to the whole module instead of starting from no flags. This change fixes the above linked issues
- Fix shader flag tests affected by the above change

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp [hunk 1]
```diff
@@ -207,26 +207,69 @@ void ModuleShaderFlags::updateFunctionFlags(ComputedShaderFlags &CSF,
...
-      CanSetNativeLowPrecisionMode = NativeLowPrec->getValue().getBoolValue();
+      CSF.NativeLowPrecisionMode = NativeLowPrec->getValue().getBoolValue();
+
+  CanSetResMayNotAlias = MMDI.DXILVersion >= VersionTuple(1, 7);
+  // The command line option -res-may-alias will set the dx.resmayalias module
+  // flag to 1, thereby disabling the ability to set the ResMayNotAlias flag
+  if (auto *ResMayAlias = mdconst::extract_or_null<ConstantInt>(
+          M.getModuleFlag("dx.resmayalias")))
+    if (ResMayAlias->getValue().getBoolValue())
+      CanSetResMayNotAlias = false;
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILShaderFlags.cpp:258]: Computing and setting this member variable inside the function like this is a bit of a surprising side effect. I think we should hoist the calculation of `CanSetResMayNotAlias` to its own thing and do it explicitly in `ModuleShaderFlags::initialize`

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp [hunk 2]
```diff
@@ -207,26 +207,69 @@ void ModuleShaderFlags::updateFunctionFlags(ComputedShaderFlags &CSF,
...
 }
 
-/// Construct ModuleShaderFlags for module Module M
-void ModuleShaderFlags::initialize(Module &M, DXILResourceTypeMap &DRTM,
-                                   DXILResourceMap &DRM,
-                                   const ModuleMetadataInfo &MMDI) {
+/// Set shader flags that apply to all functions within the module
+void ModuleShaderFlags::gatherGlobalModuleFlags(
+    ComputedShaderFlags &CSF, const Module &M, const DXILResourceMap &DRM,
+    const ModuleMetadataInfo &MMDI) {
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILShaderFlags.cpp:213]: This API could return a `ComputedShaderFlags` instead of filling in the passed in one.

**Comment by farzonl** [comment]
I think the bugs you are fixing were mostly found because of the validator? Should we be doing some testing that invokes the validator something similaor to what `llvm/test/tools/dxil-dis/` tests do?

File: llvm/lib/Target/DirectX/DXILShaderFlags.cpp [hunk 3]
```diff
@@ -273,43 +320,6 @@ void ModuleShaderFlags::initialize(Module &M, DXILResourceTypeMap &DRTM,
       // Merge SCCSF with that of F
       FunctionFlags[F].merge(SCCSF);
   }
-
-  // Set DisableOptimizations flag based on the presence of OptimizeNone
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILShaderFlags.cpp:277]: I did not see anything in the description about why we are removing the `DisableOptimizations` block of code.

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILShaderFlags.cpp:277]: It's not removed; it has been relocated to the new `gatherGlobalModuleFlags` function

File: llvm/test/CodeGen/DirectX/ShaderFlags/disable-opt-cs.ll [hunk 4]
```diff
@@ -8,7 +8,7 @@
 ; CHECK-NEXT: ;       Disable shader optimizations
 
 ; CHECK: ; Shader Flags for Module Functions
-; CHECK: ; Function main : 0x00000000
+; CHECK: ; Function main : 0x00000001
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/ShaderFlags/disable-opt-cs.ll:11]: Do these disable-opt-*.ll tests make sense anymore? Now that that block of code is removed?

**Review by bogner — APPROVED** [review]

File: llvm/test/CodeGen/DirectX/ShaderFlags/disable-opt-cs.ll (hunk 4 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/ShaderFlags/disable-opt-cs.ll:11]: The Disable Optimizations flag still exists, so it does still need to be tested.
In this case, the flag is now set on each function instead of only for the whole module, so the tests have been modified to reflect that.

**Comment by Icohedron** [comment]
> I think the bugs you are fixing were mostly found because of the validator? Should we be doing some testing that invokes the validator something similaor to what `llvm/test/tools/dxil-dis/` tests do?

Yes, the bugs were found in the validator. 
Unlike dxil-dis, dxv (the validator) isn't included as a tool with LLVM. Perhaps dxv should be made available as llvm-dxv perhaps?

Or, the DirectX tests could have RUN lines conditioned on having dxv in the path, and runs the validator if it is in the path; similar to spirv-val I saw in SPIRV tests.

Either way, I think this topic should be relegated to a separate issue and PR.

**Comment by farzonl** [comment]
> > I think the bugs you are fixing were mostly found because of the validator? Should we be doing some testing that invokes the validator something similaor to what `llvm/test/tools/dxil-dis/` tests do?
> 
> Yes, the bugs were found in the validator. Unlike dxil-dis, dxv (the validator) isn't included as a tool with LLVM. Perhaps dxv should be made available as llvm-dxv perhaps?
> 
> Or, the DirectX tests could have RUN lines conditioned on having dxv in the path, and runs the validator if it is in the path; similar to spirv-val I saw in SPIRV tests.
> 
> Either way, I think this topic should be relegated to a separate issue and PR.

`dxil-dis` is built by checking out and building DXC via the `LLVM_INCLUDE_DXIL_TESTS` Cmake argument. That means `dxv` probably exists somewhere in the llvm tools DXIL bin directory.

**Review by farzonl — APPROVED** [review]
