### PR TITLE
[MLIR][Bufferization]: Handle invalid memref element types

### LINKED ISSUE #114730: static ConcreteT mlir::detail::StorageUserBase<mlir::MemRefType, mlir::BaseMemRefType, mlir::detail::MemRefTypeStorage, mlir::detail::TypeUniquer, mlir::ShapedType::Trait>::get(MLIRContext *, Args &&...) [ConcreteT = mlir::MemRefType, BaseT = mlir::BaseMemRefType, StorageT = mlir::detail::MemRefTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <mlir::ShapedType::Trait>, Args = <llvm::ArrayRef<long> &, mlir::Type &, mlir::MemRefLayoutAttrInterface &, mlir::Attribute &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
Test on commit:https://github.com/llvm/llvm-project/commit/efd8938d575d1f8058bfe220e4c672d969c82be0
steps to reproduce:
```
mlir-opt test.mlir --one-shot-bufferize="bufferize-function-boundaries=1 no-analysis-func-filter=contains_to_memref_op"
```
test case:
```
module {
  func.func @main(%arg4: tensor<513x!quant.uniform<i16:f32, 1.000000e+00>>) {
    return
  }
}
```
crash trace:
```
<unknown>:0: error: invalid memref element type
mlir-opt: /home/workdir/llvm-project-19/mlir/include/mlir/IR/StorageUniquerSupport.h:180: static ConcreteT mlir::detail::StorageUserBase<mlir::MemRefType, mlir::BaseMemRefType, mlir::detail::MemRefTypeStorage, mlir::detail::TypeUniquer, mlir::ShapedType::Trait>::get(MLIRContext *, Args &&...) [ConcreteT = mlir::MemRefType, BaseT = mlir::BaseMemRefType, StorageT = mlir::detail::MemRefTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <mlir::ShapedType::Trait>, Args = <llvm::ArrayRef<long> &, mlir::Type &, mlir::MemRefLayoutAttrInterface &, mlir::Attribute &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./mlir-opt /home/workdir/test2.mlir "--one-shot-bufferize=bufferize-function-boundaries=1 no-analysis-func-filter=contains_to_memref_op"
 #0 0x00005ba3fd6dd998 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./mlir-opt+0x105e998)
 #1 0x00005ba3fd6db4be llvm::sys::RunSignalHandlers() (./mlir-opt+0x105c4be)
 #2 0x00005ba3fd6de3a8 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007c2e90831520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007c2e908859fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007c2e90831476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007c2e908177f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007c2e9081771b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007c2e90828e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00005ba400a2dbb7 (./mlir-opt+0x43aebb7)
#10 0x00005ba400a2dabc mlir::MemRefType::get(llvm::ArrayRef<long>, mlir::Type, mlir::MemRefLayoutAttrInterface, mlir::Attribute) (./mlir-opt+0x43aeabc)
#11 0x00005ba3fdbc7d7d mlir::bufferization::getMemRefTypeWithFullyDynamicLayout(mlir::TensorType, mlir::Attribute) (./mlir-opt+0x1548d7d)
#12 0x00005ba3fdc372c9 mlir::bufferization::func_ext::getBufferizedFunctionArgType(mlir::func::FuncOp, long, mlir::bufferization::BufferizationOptions const&) FuncBufferizableOpInterfaceImpl.cpp:0:0
#13 0x00005ba3fdc367be mlir::bufferization::func_ext::FuncOpInterface::bufferize(mlir::Operation*, mlir::RewriterBase&, mlir::bufferization::BufferizationOptions const&) const (./mlir-opt+0x15b77be)
#14 0x00005ba3fdc119d0 mlir::bufferization::bufferizeOp(mlir::Operation*, mlir::bufferization::BufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x15929d0)
#15 0x00005ba3fdc4d232 mlir::bufferization::bufferizeModuleOp(mlir::ModuleOp, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x15ce232)
#16 0x00005ba3fdc4db3d mlir::bufferization::runOneShotModuleBufferize(mlir::ModuleOp, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x15ceb3d)
#17 0x00005ba3fdc1630f (anonymous namespace)::OneShotBufferizePass::runOnOperation() Bufferize.cpp:0:0
#18 0x00005ba4009028bf mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./mlir-opt+0x42838bf)
#19 0x00005ba4009030a2 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./mlir-opt+0x42840a2)
#20 0x00005ba40090584e mlir::PassManager::run(mlir::Operation*) (./mlir-opt+0x428684e)
#21 0x00005ba4008fe372 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#22 0x00005ba4008fdfdb llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#23 0x00005ba4009a79b5 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./mlir-opt+0x43289b5)
#24 0x00005ba4008f91d2 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./mlir-opt+0x427a1d2)
#25 0x00005ba4008f9483 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x427a483)
#26 0x00005ba4008f9692 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x427a692)
#27 0x00005ba3fd6bcb77 main (./mlir-opt+0x103db77)
#28 0x00007c2e90818d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#29 0x00007c2e90818e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#30 0x00005ba3fd6bc6f5 _start (./mlir-opt+0x103d6f5)
Aborted (core dumped)
```

### LINKED ISSUE #128329: [MLIR]`-sparsification-and-bufferization` triggers Assertion Failure `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))'
Test on commit: https://github.com/llvm/llvm-project/commit/dca2ed31278c444f839e3e04fde0c21b62451d4a
steps to reproduce:
```
mlir-opt test.mlir --sparsification-and-bufferization
```
test case:
```
module {
  func.func @main(%arg0 : tensor<16x1x1x8x!quant.uniform<u8<1:255>:f32, 0.015680249780416489:128>>) -> (){
    return
  }
}
```
crash trace:
```
<unknown>:0: error: invalid memref element type
mlir-opt: /home/workdir/llvm-project-19/mlir/include/mlir/IR/StorageUniquerSupport.h:180: static ConcreteT mlir::detail::StorageUserBase<mlir::MemRefType, mlir::BaseMemRefType, mlir::detail::MemRefTypeStorage, mlir::detail::TypeUniquer, mlir::ShapedType::Trait>::get(MLIRContext *, Args &&...) [ConcreteT = mlir::MemRefType, BaseT = mlir::BaseMemRefType, StorageT = mlir::detail::MemRefTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <mlir::ShapedType::Trait>, Args = <llvm::ArrayRef<long> &, mlir::Type &, mlir::MemRefLayoutAttrInterface &, mlir::Attribute &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./mlir-opt /home/workdir/test.mlir --sparsification-and-bufferization
 #0 0x00006041357b7258 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./mlir-opt+0x10b5258)
 #1 0x00006041357b4d7e llvm::sys::RunSignalHandlers() (./mlir-opt+0x10b2d7e)
 #2 0x00006041357b7c68 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007d081c283520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007d081c2d79fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007d081c283476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007d081c2697f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007d081c26971b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007d081c27ae96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000604138cd8497 (./mlir-opt+0x45d6497)
#10 0x0000604138cd839c mlir::MemRefType::get(llvm::ArrayRef<long>, mlir::Type, mlir::MemRefLayoutAttrInterface, mlir::Attribute) (./mlir-opt+0x45d639c)
#11 0x0000604135cbe78a mlir::bufferization::getMemRefTypeWithStaticIdentityLayout(mlir::TensorType, mlir::Attribute) (./mlir-opt+0x15bc78a)
#12 0x0000604135d2b179 mlir::bufferization::func_ext::getBufferizedFunctionArgType(mlir::func::FuncOp, long, mlir::bufferization::BufferizationOptions const&) FuncBufferizableOpInterfaceImpl.cpp:0:0
#13 0x0000604135d2a752 mlir::bufferization::func_ext::FuncOpInterface::bufferize(mlir::Operation*, mlir::RewriterBase&, mlir::bufferization::BufferizationOptions const&) const (./mlir-opt+0x1628752)
#14 0x0000604135d06d80 mlir::bufferization::bufferizeOp(mlir::Operation*, mlir::bufferization::BufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x1604d80)
#15 0x0000604135d41031 mlir::bufferization::bufferizeModuleOp(mlir::ModuleOp, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x163f031)
#16 0x00006041377a8c0f mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization() (./mlir-opt+0x30a6c0f)
#17 0x00006041377a86db mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation() (./mlir-opt+0x30a66db)
#18 0x0000604138bacbcf mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./mlir-opt+0x44aabcf)
#19 0x0000604138bad352 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./mlir-opt+0x44ab352)
#20 0x0000604138bafade mlir::PassManager::run(mlir::Operation*) (./mlir-opt+0x44adade)
#21 0x0000604138ba862b performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#22 0x0000604138ba8283 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#23 0x0000604138c519e5 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./mlir-opt+0x454f9e5)
#24 0x0000604138ba1ee2 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./mlir-opt+0x449fee2)
#25 0x0000604138ba2193 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x44a0193)
#26 0x0000604138ba23a2 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x44a03a2)
#27 0x0000604135796477 main (./mlir-opt+0x1094477)
#28 0x00007d081c26ad90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#29 0x00007d081c26ae40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#30 0x0000604135795fe5 _start (./mlir-opt+0x1093fe5)
Aborted (core dumped)
```

### LINKED ISSUE #128330: [MLIR]`-one-shot-bufferize=bufferize-function-boundaries` triggers Assertion Faiure `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))'
Test on commit: https://github.com/llvm/llvm-project/commit/dca2ed31278c444f839e3e04fde0c21b62451d4a
steps to reproduce:
```
mlir-opt test.mlir -one-shot-bufferize=bufferize-function-boundaries
```
test case:
```
module {
  func.func @combined_example(%arg1: tensor<16x1x1x8x!quant.uniform<i8<-127:127>:f32, 0.015680249780416489>>) -> () {
    return
  }
}
```
crash trace:
```
<unknown>:0: error: invalid memref element type
mlir-opt: /home/workdir/llvm-project-19/mlir/include/mlir/IR/StorageUniquerSupport.h:180: static ConcreteT mlir::detail::StorageUserBase<mlir::MemRefType, mlir::BaseMemRefType, mlir::detail::MemRefTypeStorage, mlir::detail::TypeUniquer, mlir::ShapedType::Trait>::get(MLIRContext *, Args &&...) [ConcreteT = mlir::MemRefType, BaseT = mlir::BaseMemRefType, StorageT = mlir::detail::MemRefTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <mlir::ShapedType::Trait>, Args = <llvm::ArrayRef<long> &, mlir::Type &, mlir::MemRefLayoutAttrInterface &, mlir::Attribute &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./mlir-opt /home/workdir/test.mlir -one-shot-bufferize=bufferize-function-boundaries
 #0 0x00005abb0f373258 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./mlir-opt+0x10b5258)
 #1 0x00005abb0f370d7e llvm::sys::RunSignalHandlers() (./mlir-opt+0x10b2d7e)
 #2 0x00005abb0f373c68 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007d22bf4a2520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007d22bf4f69fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007d22bf4a2476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007d22bf4887f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007d22bf48871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007d22bf499e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00005abb12894497 (./mlir-opt+0x45d6497)
#10 0x00005abb1289439c mlir::MemRefType::get(llvm::ArrayRef<long>, mlir::Type, mlir::MemRefLayoutAttrInterface, mlir::Attribute) (./mlir-opt+0x45d639c)
#11 0x00005abb0f87a66d mlir::bufferization::getMemRefTypeWithFullyDynamicLayout(mlir::TensorType, mlir::Attribute) (./mlir-opt+0x15bc66d)
#12 0x00005abb0f8e7179 mlir::bufferization::func_ext::getBufferizedFunctionArgType(mlir::func::FuncOp, long, mlir::bufferization::BufferizationOptions const&) FuncBufferizableOpInterfaceImpl.cpp:0:0
#13 0x00005abb0f8e6752 mlir::bufferization::func_ext::FuncOpInterface::bufferize(mlir::Operation*, mlir::RewriterBase&, mlir::bufferization::BufferizationOptions const&) const (./mlir-opt+0x1628752)
#14 0x00005abb0f8c2d80 mlir::bufferization::bufferizeOp(mlir::Operation*, mlir::bufferization::BufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x1604d80)
#15 0x00005abb0f8fd031 mlir::bufferization::bufferizeModuleOp(mlir::ModuleOp, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x163f031)
#16 0x00005abb0f8fde4d mlir::bufferization::runOneShotModuleBufferize(mlir::ModuleOp, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationStatistics*) (./mlir-opt+0x163fe4d)
#17 0x00005abb0f8c6015 (anonymous namespace)::OneShotBufferizePass::runOnOperation() Bufferize.cpp:0:0
#18 0x00005abb12768bcf mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./mlir-opt+0x44aabcf)
#19 0x00005abb12769352 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./mlir-opt+0x44ab352)
#20 0x00005abb1276bade mlir::PassManager::run(mlir::Operation*) (./mlir-opt+0x44adade)
#21 0x00005abb1276462b performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#22 0x00005abb12764283 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#23 0x00005abb1280d9e5 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./mlir-opt+0x454f9e5)
#24 0x00005abb1275dee2 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./mlir-opt+0x449fee2)
#25 0x00005abb1275e193 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x44a0193)
#26 0x00005abb1275e3a2 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x44a03a2)
#27 0x00005abb0f352477 main (./mlir-opt+0x1094477)
#28 0x00007d22bf489d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#29 0x00007d22bf489e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#30 0x00005abb0f351fe5 _start (./mlir-opt+0x1093fe5)
Aborted (core dumped)
```

### LINKED ISSUE #173565: mlir-opt crashes in mlir/IR/StorageUniquerSupport.h:180
When running opt on the following IR, mlir-opt crashes. 

version 2c02e4c7909a

test.mlir

```
func.func @quantized_read_and_store(%arg0: tensor<8x32x32x2x!quant.uniform<i8:f32, 0.00128>>, %arg1: tensor<i32>) -> () {

  %0 = "test.destination_slice_op"(%arg0, %arg1) : (tensor<8x32x32x2x!quant.uniform<i8:f32, 0.00128>>, tensor<i32>) -> tensor<?x?x?x?x f32>
  "test.destination_slice_op"(%0, %0) : (tensor<?x?x?x?x f32>, tensor<?x?x?x?x f32>) -> ()
  return
}
```

commads:

mlir-opt -sparsification-and-bufferization  test.mlir

stacktrace

```
mlir-opt: llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:180: static ConcreteT mlir::detail::StorageUserBase<mlir::MemRefType, mlir::BaseMemRefType, mlir::detail::MemRefTypeStorage, mlir::detail::TypeUniquer, mlir::PtrLikeTypeInterface::Trait, mlir::ShapedType::Trait>::get(MLIRContext *, Args &&...) [ConcreteT = mlir::MemRefType, BaseT = mlir::BaseMemRefType, StorageT = mlir::detail::MemRefTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <mlir::PtrLikeTypeInterface::Trait, mlir::ShapedType::Trait>, Args = <llvm::ArrayRef<long> &, mlir::Type &, mlir::MemRefLayoutAttrInterface &, mlir::Attribute &>]: Assertion `succeeded( ConcreteT::verifyInvariants(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: ./build/bin/mlir-opt -sparsification-and-bufferization test.mlir
 #0 0x00005636ee258358 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./build/bin/mlir-opt+0x1e97358)
 #1 0x00005636ee255a15 llvm::sys::RunSignalHandlers() (./build/bin/mlir-opt+0x1e94a15)
 #2 0x00005636ee259396 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007ff385f39420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007ff38559200b raise /build/glibc-B3wQXB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007ff385571859 abort /build/glibc-B3wQXB/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007ff385571729 get_sysdep_segment_value /build/glibc-B3wQXB/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007ff385571729 _nl_load_domain /build/glibc-B3wQXB/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007ff385582fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x00005636f6b80067 (./build/bin/mlir-opt+0xa7bf067)
#10 0x00005636f6b7ff6e mlir::MemRefType::get(llvm::ArrayRef<long>, mlir::Type, mlir::MemRefLayoutAttrInterface, mlir::Attribute) (./build/bin/mlir-opt+0xa7bef6e)
#11 0x00005636f542e1ea mlir::bufferization::getMemRefTypeWithStaticIdentityLayout(mlir::TensorType, mlir::Attribute) (./build/bin/mlir-opt+0x906d1ea)
#12 0x00005636f542fef2 std::_Function_handler<mlir::bufferization::BufferLikeType (mlir::bufferization::TensorLikeType, mlir::Attribute, mlir::func::FuncOp, mlir::bufferization::BufferizationOptions const&), mlir::bufferization::BufferizationOptions::setFunctionBoundaryTypeConversion(mlir::bufferization::LayoutMapOption)::$_0>::_M_invoke(std::_Any_data const&, mlir::bufferization::TensorLikeType&&, mlir::Attribute&&, mlir::func::FuncOp&&, mlir::bufferization::BufferizationOptions const&) BufferizableOpInterface.cpp:0:0
#13 0x00005636f5404af3 mlir::bufferization::func_ext::getBufferizedFunctionArgType(mlir::func::FuncOp, long, mlir::bufferization::BufferizationOptions const&) FuncBufferizableOpInterfaceImpl.cpp:0:0
#14 0x00005636f54040b0 mlir::bufferization::func_ext::FuncOpInterface::bufferize(mlir::Operation*, mlir::RewriterBase&, mlir::bufferization::BufferizationOptions const&, mlir::bufferization::BufferizationState&) const (./build/bin/mlir-opt+0x90430b0)
#15 0x00005636f53e564f mlir::bufferization::bufferizeOp(mlir::Operation*, mlir::bufferization::BufferizationOptions const&, mlir::bufferization::BufferizationState&, mlir::bufferization::BufferizationStatistics*) (./build/bin/mlir-opt+0x902464f)
#16 0x00005636f541ba14 mlir::bufferization::bufferizeModuleOp(mlir::Operation*, mlir::bufferization::OneShotBufferizationOptions const&, mlir::bufferization::BufferizationState&, mlir::bufferization::BufferizationStatistics*) (./build/bin/mlir-opt+0x905aa14)
#17 0x00005636eed5c4af mlir::sparse_tensor::SparsificationAndBufferizationPass::runDenseBufferization() (./build/bin/mlir-opt+0x299b4af)
#18 0x00005636eed5b40f mlir::sparse_tensor::SparsificationAndBufferizationPass::runOnOperation() (./build/bin/mlir-opt+0x299a40f)
#19 0x00005636f69127be mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./build/bin/mlir-opt+0xa5517be)
#20 0x00005636f6913617 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./build/bin/mlir-opt+0xa552617)
#21 0x00005636f691a9ca mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) (./build/bin/mlir-opt+0xa5599ca)
#22 0x00005636f691a01f mlir::PassManager::run(mlir::Operation*) (./build/bin/mlir-opt+0xa55901f)
#23 0x00005636ee2fc377 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#24 0x00005636ee2fb5a6 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#25 0x00005636f6c2d855 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./build/bin/mlir-opt+0xa86c855)
#26 0x00005636ee2f1166 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./build/bin/mlir-opt+0x1f30166)
#27 0x00005636ee2f14a2 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./build/bin/mlir-opt+0x1f304a2)
#28 0x00005636ee2f1805 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./build/bin/mlir-opt+0x1f30805)
#29 0x00005636ee23e9b3 main (./build/bin/mlir-opt+0x1e7d9b3)
#30 0x00007ff385573083 __libc_start_main /build/glibc-B3wQXB/glibc-2.31/csu/../csu/libc-start.c:342:3
#31 0x00005636ee23e4ee _start (./build/bin/mlir-opt+0x1e7d4ee)
```

### PR DESCRIPTION
**Pull request by sweiglbosker**
Fixes #128329, Fixes #128330, Fixes #173565, Fixes #114730

There is an assertion failure in `-one-shot-bufferize` when tensors that have an element type that can't be a memref element type are encountered. https://github.com/llvm/llvm-project/blob/f8d3f47e1fd09392aa30df83849b25acd8c59a25/mlir/include/mlir/IR/BuiltinTypes.h#L440

We can't emit a to_tensor for ops that do implement `BufferizableOpInterface`, and i don't think quantizing is the right move either, so erroring seemed like the best fit.

After some trial and error, `defaultGetBufferType` seems like the most functional and least invasive place to put this check.

### CODE REVIEW

File: mlir/lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp [hunk 1]
```diff
@@ -961,6 +961,16 @@ FailureOr<BufferLikeType> bufferization::detail::defaultGetBufferType(
   assert(llvm::isa<TensorType>(value.getType()) && "expected tensor type");
   auto tensorType = cast<TensorType>(value.getType());
 
+  auto elementType = tensorType.getElementType();
+
+  if (!BaseMemRefType::isValidElementType(elementType)) {
+    if (Operation *def = value.getDefiningOp())
```
Comment (matthias-springer) [inline mlir/lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp]: Use `getOwnerOfValue(value)->emitError()` to make sure that we print an error message even for block arguments.

**Review by matthias-springer — APPROVED** [review]

File: mlir/test/Dialect/Tensor/one-shot-bufferize-invalid.mlir [hunk 2]
```diff
@@ -0,0 +1,8 @@
+// RUN: not mlir-opt %s -one-shot-bufferize -verify-diagnostics
```
Comment (matthias-springer) [inline mlir/test/Dialect/Tensor/one-shot-bufferize-invalid.mlir]: Can you move this file to `mlir/test/Dialect/Bufferization/Transforms/`?

File: mlir/test/Dialect/Bufferization/Transforms/one-shot-bufferize-invalid-memref-element-type.mlir [hunk 3]
```diff
@@ -0,0 +1,8 @@
+// RUN: not mlir-opt %s -one-shot-bufferize -verify-diagnostics
```
Comment (sweiglbosker) [reply mlir/test/Dialect/Bufferization/Transforms/one-shot-bufferize-invalid-memref-element-type.mlir]: Done

Comment (linuxlonelyeagle) [reply mlir/test/Dialect/Bufferization/Transforms/one-shot-bufferize-invalid-memref-element-type.mlir]: You maybe can add the test in https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/Bufferization/Transforms/one-shot-module-bufferize-invalid.mlir.Rather than adding a new file.

**Review by linuxlonelyeagle — APPROVED** [review]
LGTM.
