### PR TITLE
[analyzer] Avoid unnecessary super region invalidation in `CStringChecker`

### LINKED ISSUE #143807: False positive in clang-analyzer-cplusplus.NewDeleteLeaks for std::unique_ptr
```
#include <memory>
#include <cstring>
#include <string>

struct Repro {
    std::unique_ptr<int> m_ptr;

    struct Other {
        char url[256];
    };
    char m_buff[1000];

    void CopyIn()
    {
        auto other = (Other *)m_buff;

        std::string local_url = "foo bar";
        strncpy(other->url, local_url.c_str(), sizeof(other->url) - 1);
    }
};

void
bug()
{
    Repro rep;
    rep.m_ptr = std::make_unique<int>();
    rep.CopyIn();
}
```

`clang-tidy` reports the following when building against the GCC-15's libstdc++:

```
repro.cpp:19:5: error: Potential leak of memory pointed to by field '_M_head_impl' [clang-analyzer-cplusplus.NewDeleteLeaks,-warnings-as-errors]
   19 |     }
      |     ^
repro.cpp:26:17: note: Calling 'make_unique<int, >'
   26 |     rep.m_ptr = std::make_unique<int>();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/opt/gcc-15/lib/gcc/x86_64-pc-linux-gnu/15.1.1/../../../../include/c++/15.1.1/bits/unique_ptr.h:1085:30: note: Memory is allocated
 1085 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repro.cpp:26:17: note: Returned allocated memory
   26 |     rep.m_ptr = std::make_unique<int>();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
repro.cpp:27:5: note: Calling 'Repro::CopyIn'
   27 |     rep.CopyIn();
      |     ^~~~~~~~~~~~
repro.cpp:19:5: note: Potential leak of memory pointed to by field '_M_head_impl'
   19 |     }
      |     ^
```

There is clearly no leak here and the warning goes away if the code is tweaked just a little bit... I cannot understand

### PR DESCRIPTION
**Pull request by flovent**
Bounded string functions takes smallest of two values as it's copy size (`amountCopied` variable in `evalStrcpyCommon`), and it's used to decided whether this operation will cause out-of-bound access and invalidate it's super region if it does.

for `strlcat`: `amountCopied = min (size - dstLen - 1 , srcLen)`
for others: `amountCopied = min (srcLen, size)`

Currently when one of two values is unknown or  `SValBuilder` can't decide which one is smaller, `amountCopied` will remain `UnknownVal`, which will invalidate copy destination's super region unconditionally. 

This patch add check to see if one of these two values is definitely in-bound, if so `amountCopied` has to be in-bound too, because it‘s less than or equal to them, we can avoid the invalidation of super region and some related false positives in this situation.

Note: This patch uses `size` as an approximation of `size - dstLen - 1` in `strlcat` case because currently analyzer doesn't handle complex expressions like this very well.

Closes #143807.

### CODE REVIEW

File: clang/test/Analysis/cstring-should-not-invalidate.cpp [hunk 1]
```diff
@@ -0,0 +1,107 @@
+// RUN: %clang_analyze_cc1 -analyzer-checker=core,debug.ExprInspection
+// -analyzer-config c++-inlining=constructors -verify %s
```
Comment (steakhal) [inline clang/test/Analysis/cstring-should-not-invalidate.cpp]: This line is definitely ineffective. To make it part of the previous RUN line you will need to end that RUN line with `\`.

File: clang/test/Analysis/cstring-should-not-invalidate.cpp [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+
+// expected-no-diagnostics
+
+typedef unsigned int size_t;
```
Comment (steakhal) [inline clang/test/Analysis/cstring-should-not-invalidate.cpp]: You can always define this as the result of `decltype(sizeof(int))`.

**Review by steakhal — COMMENTED** [review]
Thanks for the detailed PR summary. It makes sense. I had to think about it carefully but I agree with the motivation.
When I looked at the code it looked really complicated. Probably more than I expected it to be.

I think adding another bool parameter to the already crowded function is not ideal. We should look for some other way, maybe a different overload, or restructuring the code in other ways.

**Comment by flovent** [comment]
> Thanks for the detailed PR summary. It makes sense. I had to think about it carefully but I agree with the motivation. When I looked at the code it looked really complicated. Probably more than I expected it to be.

`CStringChecker` is a very complicated checker indeed, it may took me more time to decide how to change this file than finding the cause of this problem, finally i added this parameter with default value to reduce the modifications required because `invalidateDestinationBufferBySize` is used in model to other functions like `memset`, `memcpy` too.

> I think adding another bool parameter to the already crowded function is not ideal. We should look for some other way, maybe a different overload, or restructuring the code in other ways.

I just find out there are three member functions whose name start with `invalidateDestinationBuffer`, seems `invalidateDestinationBufferNeverOverflows` should be the right call when `CouldAccessOutOfBound == false`.

**Comment by flovent** [comment]
CI failures seem unlreated to the new change in this PR.

**Comment by steakhal** [comment]
I resign from review. I don't have time to review 100+ lines PRs right now.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 3]
```diff
@@ -2223,16 +2223,81 @@ void CStringChecker::evalStrcpyCommon(CheckerContext &C, const CallEvent &Call,
...
+    // for others:
+    // amountCopied = min (srcLen, size)
+    // So even if we don't know about amountCopied, as long as one of them will
+    // not cause an out-of-bound access, the whole function's operation will not
+    // too, that will avoid invalidating the superRegion of data member in that
+    // situation.
+    bool CouldAccessOutOfBound = true;
+    if (IsBounded && amountCopied.isUnknown()) {
+      // Get the max number of characters to copy.
+      SizeArgExpr lenExpr = {{Call.getArgExpr(2), 2}};
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: As far as I see you only use the `.Expression` member of this object -- just declare `const Expr *LenExpr = Call.getArgExpr(2)` instead of this.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 4]
```diff
@@ -2223,16 +2223,81 @@ void CStringChecker::evalStrcpyCommon(CheckerContext &C, const CallEvent &Call,
...
+      }
+
+      if (CouldAccessOutOfBound && lenValNL) {
+        switch (appendK) {
+        case ConcatFnKind::none:
+        case ConcatFnKind::strcat: {
+          CouldAccessOutOfBound = CouldAccessOutOfBoundForSVal(*lenValNL);
+          break;
+        }
+        case ConcatFnKind::strlcat: {
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: I strongly suspect that calculating `(size - dstLen - 1)` will help only if both `size` and `dstLen` are known concrete integers, because the analyzer cannot properly work with symbolical expressions with this sort of complexity. (E.g. if it knows that `a < b`, it cannot conclude that `a - 1 < b` -- partially because of "not yet implemented" limitations and partially because technically this conclusion isn't true when `a == INT_MIN`.)

I would suggest simplifying the code by using `size` as a rough over-approximation instead of `(size - dstLen - 1)` in this case because that _might_ be simple enough to be useful. (I can imagine that perhaps sometimes the analyzer could conclude that copying at most `size` bytes doesn't cause an overflow, this is more unlikely with the complicated exact upper bound.)

If you want, you can introduce a special case that uses  `(size - dstLen - 1)` if the values are known concrete integers -- but I feel that this may be "too special" to deserve custom logic.

**Review by NagyDonat — COMMENTED** [review]
Overall I like this change, but I added a few suggestions in inline comments.

Also please follow the [Coding Standard](https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly) and use `UpperCamelCase` variables for variables (including ones that store lambda functions), while `lowerCamelCase` is for methods. Of course, it is also right to follow the "local customs" of older code fragments, but I'd suggest gradually transitioning to the global standard by following the coding standard for the freshly added variables and perhaps transitioning the variables which are mostly used in the code that you edit.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp (hunk 3 above)
Comment (flovent) [reply clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: Done.

**Comment by flovent** [comment]
> Also please follow the [Coding Standard](https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly) and use `UpperCamelCase` variables for variables (including ones that store lambda functions), while `lowerCamelCase` is for methods. Of course, it is also right to follow the "local customs" of older code fragments, but I'd suggest gradually transitioning to the global standard by following the coding standard for the freshly added variables and perhaps transitioning the variables which are mostly used in the code that you edit.

I totally agree using new standard in new code, i think i didn't notice that because i  basiclly copy the orginal code to here because of the same logic and clangd doesn't give warning about clang-tidy's `readability-identifier-naming` check (just found out it's disabled in clang folder), will check that manually next time.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp (hunk 4 above)
Comment (flovent) [reply clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: I think that make sense, now it use `size` for all `ConcatFnKind`'s check.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 5]
```diff
@@ -2223,16 +2223,59 @@ void CStringChecker::evalStrcpyCommon(CheckerContext &C, const CallEvent &Call,
...
+    // amountCopied = min (size - dstLen - 1 , srcLen)
+    // for others:
+    // amountCopied = min (srcLen, size)
+    // So even if we don't know about amountCopied, as long as one of them will
+    // not cause an out-of-bound access, the whole function's operation will not
+    // too, that will avoid invalidating the superRegion of data member in that
+    // situation.
+    bool CouldAccessOutOfBound = true;
+    if (IsBounded && amountCopied.isUnknown()) {
+      auto CouldAccessOutOfBoundForSVal = [&](NonLoc Val) -> bool {
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: Currently both calls to this lambda are wrapped in `if (...NL)` blocks, so you could slightly simplify the code by bringing that repeated  check "into" the lambda.

File: clang/test/Analysis/cstring-should-not-invalidate.cpp [hunk 6]
```diff
@@ -0,0 +1,106 @@
+// RUN: %clang_analyze_cc1 -analyzer-checker=core -verify %s
```
Comment (NagyDonat) [inline clang/test/Analysis/cstring-should-not-invalidate.cpp]: Please ensure that (the relevant parts of) `CStringChecker` is actually enabled in this test file -- its sub-checkers are in the `unix.cstring` and `alpha.unix.cstring` packages, while this `RUN` line only enables `core`.

As a sanity check it would be nice to have a testcase that actually produces some diagnostics.

**Review by NagyDonat — COMMENTED** [review]
Thanks for the updates!

I added a few minor comments, but I hope that after those the PR could be merged.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp (hunk 5 above)
Comment (flovent) [reply clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp]: Done.

File: clang/test/Analysis/cstring-should-not-invalidate.cpp (hunk 6 above)
Comment (flovent) [reply clang/test/Analysis/cstring-should-not-invalidate.cpp]: Added `alpha.unix.cstring` and `unix.cstring` to testcase, `alpha.unix.cstring` makes a difference, in line 66, if `size` is equal to `dest`'s size, `alpha.unix.cstring.OutOfBounds` will be reported, that's before we check `size` or `srcLen`.

Comment (flovent) [reply clang/test/Analysis/cstring-should-not-invalidate.cpp]: > As a sanity check it would be nice to have a testcase that actually produces some diagnostics.

I add `debug.ExprInspection` to detect if a simple member(`int b`) has it original value after these str functions call, do you have other kind of testcases in mind? I can add it too.

Comment (NagyDonat) [reply clang/test/Analysis/cstring-should-not-invalidate.cpp]: > > As a sanity check it would be nice to have a testcase that actually produces some diagnostics.
> 
> I add `debug.ExprInspection` to detect if a simple member(`int b`) has it original value after these str functions call, do you have other kind of testcases in mind? I can add it too.

This is not what I meant -- sorry if my suggestion wasn't clear enough.

What I wanted to suggest is that it would be nice to have an extra testcase which is similar to the others but does produce an `alpha.unix.cstring.OutOfBounds` report (to demonstrate e.g. that the checker is active).

~~The `debug.ExprInspection` checks that you added are apparently disconnected from the main goal of this test (I can't imagine a situation where they would be valuable for diagnosing problems introduced by a plausible future code change), so I'd prefer reverting the commit which adds them.~~

EDIT: I realized the reason why you added the `debug.ExprInspection` checks and you're completely right that they are relevant and should be kept.

Comment (flovent) [reply clang/test/Analysis/cstring-should-not-invalidate.cpp]: > Added `alpha.unix.cstring` and `unix.cstring` to testcase, `alpha.unix.cstring` makes a difference, in line 66, if `size` is equal to `dest`'s size, `alpha.unix.cstring.OutOfBounds` will be reported, that's before we check `size` or `srcLen`.

I added the version before i changed in 02ad1b9a3356ccf3d2816a5087f905183a5e4668 back, make it produce `alpha.unix.cstring.OutOfBounds`.

**Review by NagyDonat — COMMENTED** [review]
According to the CI Checks, one of your testcases is failing:
https://github.com/llvm/llvm-project/actions/runs/16055061425?pr=146212
> error: 'expected-warning' diagnostics expected but not seen: 
  File /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/Analysis/cstring-should-not-invalidate.cpp Line 106: TRUE
1 error generated.

**Comment by flovent** [comment]
Oh, sorry about that. It seems an error node will be generated when emitting `alpha.unix.cstring.OutOfBounds` warning, so rest of code will not be analyzed.

**Review by NagyDonat — APPROVED** [review]
LGTM, thanks for the updates!

Before merging the commit consider adding a note to the PR description / commit message that in the case of `strlcat` you use `size` as an approximation of the exact `amountCopied`.

**Comment by flovent** [comment]
@NagyDonat, I add a note in the end of PR description and I don't have a merge access, if that looks good please help me merge it, thank you!
