### PR TITLE
[NVPTX] instcombine known pointer AS checks.

### LINKED ISSUE #112760: [CUDA, NVPTX] LLVM crash with "Cannot cast between two non-generic address spaces"
Valid CUDA code results in LLVM crash due to an attempt to generate an impossible addrspacecast in a known-false conditional branch.

Reproducer: https://godbolt.org/z/Yjjsdvj1r

Source:
```
#include <stdint.h>

// No crash if the function is not inlined, and thus does not know 
// at compile time which pointer it will be handling
//__device__ uintptr_t f(void *p) __noinline__;

__device__ uintptr_t f(void *p) {
   if (__isGlobal(p))
    return __cvta_generic_to_global(p);
   if (__isShared(p))
     return __cvta_generic_to_shared(p);
   return (uintptr_t)p;
}

__shared__ int shared_data;
__device__ int global_data;
__constant__ int const_data = 3;

__global__ void square(uintptr_t* out, int n) {
  out[0] = f(&shared_data);
  out[1] = f(&global_data);
}
```

IR:
```
define dso_local void @square(unsigned long*, int)(ptr nocapture noundef writeonly %out, i32 noundef %n) local_unnamed_addr #1 {
entry:
  %0 = tail call i1 @llvm.nvvm.isspacep.global(ptr addrspacecast (ptr addrspace(3) @shared_data to ptr))
  %1 = tail call i1 @llvm.nvvm.isspacep.shared(ptr addrspacecast (ptr addrspace(3) @shared_data to ptr))
  %. = select i1 %1, i64 ptrtoint (ptr addrspace(3) @shared_data to i64), i64 ptrtoint (ptr addrspacecast (ptr addrspace(3) @shared_data to ptr) to i64)
  %retval.0.i = select i1 %0, i64 ptrtoint (ptr addrspace(1) addrspacecast (ptr addrspace(3) @shared_data to ptr addrspace(1)) to i64), i64 %.
  store i64 %retval.0.i, ptr %out, align 8, !tbaa !8
  ret void
}
```

The culprit is `addrspacecast (ptr addrspace(3) @shared_data to ptr addrspace(1))` here:
```
  %retval.0.i = select i1 %0, i64 ptrtoint (ptr addrspace(1) addrspacecast (ptr addrspace(3) @shared_data to ptr addrspace(1)) to i64), 
```

To add insult to injury, the impossible cast is still going to be executed, and will likely result in a runtime error trying to convert the pointer in the wrong address space.

We need to make sure that `__cvta_generic_to_global()` is never executed if `__isGlobal()` is false. Same for the conversions from shared and constant AS.

### PR DESCRIPTION
**Pull request by Artem-B**
This avoids crashing on impossible address space casts guarded by `__isGlobal/__isShared`.

Partially fixes https://github.com/llvm/llvm-project/issues/112760

It's still possible to trigger the issue by using explicit AS casts w/o AS checks, but LLVM should no longer crash on valid code.

### CODE REVIEW

File: llvm/include/llvm/Support/NVPTXAddrSpace.h [hunk 1]
```diff
@@ -0,0 +1,33 @@
+//===---------------- AMDGPUAddrSpace.h -------------------------*- C++ -*-===//
```
Comment (AlexMaclean) [inline llvm/include/llvm/Support/NVPTXAddrSpace.h:1]: Looks like there are still some references to AMDGPU in here

Comment (Artem-B) [reply llvm/include/llvm/Support/NVPTXAddrSpace.h]: Good catch. Fixed.

File: llvm/lib/Analysis/InstructionSimplify.cpp [hunk 2]
```diff
@@ -6365,6 +6367,34 @@ static Value *simplifyUnaryIntrinsic(Function *F, Value *Op0,
...
     break;
   }
+  case Intrinsic::nvvm_isspacep_global:
+  case Intrinsic::nvvm_isspacep_local:
+  case Intrinsic::nvvm_isspacep_shared:
+  case Intrinsic::nvvm_isspacep_const: {
+    auto *Ty = F->getReturnType();
+    unsigned AS = Op0->getType()->getPointerAddressSpace();
+    if (AS == NVPTXAS::ADDRESS_SPACE_GENERIC) {
+      if (auto *ASC = dyn_cast<AddrSpaceCastInst>(Op0))
```
Comment (AlexMaclean) [inline llvm/lib/Analysis/InstructionSimplify.cpp:6377]: Can AddrSpaceCastOperator be used here?

Comment (Artem-B) [reply llvm/lib/Analysis/InstructionSimplify.cpp:6377]: Fixed.

**Comment by Artem-B** [comment]
@nikic Are you OK with these changes?

File: llvm/lib/Analysis/InstructionSimplify.cpp [hunk 3]
```diff
@@ -6365,6 +6367,32 @@ static Value *simplifyUnaryIntrinsic(Function *F, Value *Op0,
...
+        AS = ASC->getSrcAddressSpace();
+      else if (auto *ASCO = dyn_cast<AddrSpaceCastOperator>(Op0))
+        AS = ASCO->getOperand(0)->getType()->getPointerAddressSpace();
+    }
```
Comment (AlexMaclean) [inline llvm/lib/Analysis/InstructionSimplify.cpp:6381]:
```suggestion
    if (AS == NVPTXAS::ADDRESS_SPACE_GENERIC)
      if (auto *ASCO = dyn_cast<AddrSpaceCastOperator>(Op0))
        AS = ASCO->getSrcAddressSpace();
```

File: llvm/lib/Analysis/InstructionSimplify.cpp [hunk 4]
```diff
@@ -6365,6 +6367,32 @@ static Value *simplifyUnaryIntrinsic(Function *F, Value *Op0,
...
+    if (AS == NVPTXAS::ADDRESS_SPACE_GENERIC ||
+        AS == NVPTXAS::ADDRESS_SPACE_PARAM)
+      return nullptr; // Got to check at run-time.
+    bool ASMatches = (AS == NVPTXAS::ADDRESS_SPACE_GLOBAL &&
```
Comment (AlexMaclean) [inline llvm/lib/Analysis/InstructionSimplify.cpp:6385]: This seems correct, but I think we can also do some simplification for `nvvm_isspacep_shared_cluster`. If the ptr type is non shared we know this check will return false.

**Review by AlexMaclean — APPROVED** [review]
FWIW, this looks good to me baring some minor nits.

**Comment by goldsteinn** [comment]
AFAICT this is the only target specific handling in InstSimplify which, at least as i understand, we attempt to keep as target independent as possible in a similar way to InstCombine because its for generalized middle end canonicalization.

If there is a need for this sort of change, I think it should be done more similarly to how we do `targetInstCombineIntrinsic` with InstCombine instead ofadding all the target intrinsics directly to the InstructionSimplify file.

File: llvm/lib/Analysis/InstructionSimplify.cpp (hunk 3 above)
Comment (Artem-B) [reply llvm/lib/Analysis/InstructionSimplify.cpp:6381]: I believe we do want to handle ASC instruction, too, not just ASC operators. What am I missing here?

File: llvm/lib/Analysis/InstructionSimplify.cpp (hunk 4 above)
Comment (Artem-B) [reply llvm/lib/Analysis/InstructionSimplify.cpp:6385]: Will do.

File: llvm/lib/Analysis/InstructionSimplify.cpp (hunk 3 above)
Comment (AlexMaclean) [reply llvm/lib/Analysis/InstructionSimplify.cpp:6381]: https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/IR/Operator.h#L30-L31

ASC operators include ASC instructions I believe.

**Comment by Artem-B** [comment]
>  I think it should be done more similarly to how we do targetInstCombineIntrinsic

This, indeed, sounds like a better place to handle these intrinsics. Will do.

File: llvm/lib/Analysis/InstructionSimplify.cpp (hunk 3 above)
Comment (Artem-B) [reply llvm/lib/Analysis/InstructionSimplify.cpp:6381]: Ooh. This is convenient. Thanks for pointing it out. 

Coincidentally, the current tests in the patch didn't actually test handling of ASC instruction, as instcombine collapsed ASC(constant) into an ASC operator before we've got to handle the intrinsics. I'll update the code and the tests.

File: llvm/lib/Analysis/InstructionSimplify.cpp (hunk 4 above)
Comment (Artem-B) [reply llvm/lib/Analysis/InstructionSimplify.cpp]: Done.

**Comment by Artem-B** [comment]
> > I think it should be done more similarly to how we do targetInstCombineIntrinsic
> 
> This, indeed, sounds like a better place to handle these intrinsics. Will do.

Done.

File: llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp [hunk 5]
```diff
@@ -413,11 +416,65 @@ static Instruction *simplifyNvvmIntrinsic(IntrinsicInst *II, InstCombiner &IC) {
   llvm_unreachable("All SpecialCase enumerators should be handled in switch.");
 }
 
+// Returns an instruction pointer (may be nullptr if we do not know the answer).
+// Returns nullopt if `II` is not one of the `isspacep` intrinsics.
+static std::optional<Instruction *>
```
Comment (AlexMaclean) [inline llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:421]: Can we just return nullptr and avoid the need for the `std::optional`?

File: llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp [hunk 6]
```diff
@@ -413,11 +416,65 @@ static Instruction *simplifyNvvmIntrinsic(IntrinsicInst *II, InstCombiner &IC) {
...
+  switch (auto IID = II.getIntrinsicID()) {
+  case Intrinsic::nvvm_isspacep_global:
+  case Intrinsic::nvvm_isspacep_local:
+  case Intrinsic::nvvm_isspacep_shared:
+  case Intrinsic::nvvm_isspacep_shared_cluster:
+  case Intrinsic::nvvm_isspacep_const: {
+    auto *Ty = II.getType();
+    unsigned AS = Op0->getType()->getPointerAddressSpace();
+    // Peek through ASC to generic AS.
+    // TODO: we could dig deeper through both ASCs and GEPs.
```
Comment (AlexMaclean) [inline llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:457]: Perhaps we should add this to rewriteIntrinsicWithAddressSpace as well?

File: llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp (hunk 5 above)
Comment (Artem-B) [reply llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:421]: We have three outcomes here and the code is structured to convey that via the use of optional.
- not an isspacep intrinsic, and hence we have no answer -> nullopt. 
- if's an isspacep intrinsic, we do produce an answer, and it may be:
  - we've changed something, return non-null pointer
  - the answer is "we don't know", in which case we return nullptr

While we could return `nullptr` we'd continue checking for other intrinsics. It would happen to work, because nothing else handles the isspacep intrinsics, but I'd prefer the code to match the intent, and we do not intend to fall through into the code that deals with FP intrinsics.

File: llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp (hunk 6 above)
Comment (Artem-B) [reply llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:457]: Do you mean that we should fill in the implementation of `rewriteIntrinsicWithAddressSpace` in general? 
Probably, but that should probably be done in a separate patch.

Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:457]: I specifically mean that this same logic should also be happening in `rewriteIntrinsicWithAddressSpace` when we propagate a new AS into one of these isspacep intrinsics. I agree it can be in a separate patch though.

File: llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp (hunk 5 above)
Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp:421]: Fair enough.
