### PR TITLE
[DAG] SDPatternMatch m_Zero/m_One/m_AllOnes have inconsistent undef h…

### LINKED ISSUE #140745: [DAG] SDPatternMatch - m_Zero can't see through bitcasts
X86 uses ISD::isBuildVectorAllZeros to peek through bitcasts to match zero vectors in a large number of combines.

Ideally we'd use SDPatternMatch to match these combines and use m_Zero() instead, but regrettably this fails to match the zero vectors through bitcasts,

https://github.com/llvm/llvm-project/commit/84397c61f44e62231d1876a745a0c1f74ea8a5b8 shows an example of the regression

If we convert m_Zero() to something closer to m_AllOnes / AllOnes_match we might be able to make this work.

### LINKED ISSUE #146871: [DAG] SDPatternMatch m_Zero/m_One/m_AllOnes have inconsistent undef handling
m_Zero/m_One uses ISD::isConstantSplatVector which allows undefs in the BUILD_VECTOR node by default
m_AllOnes uses isAllOnesOrAllOnesSplat which doesn't allow undefs in the BUILD_VECTOR node by default

All of these need to be consistent with their default and with/without undefs handling to be configurable

This needs to be handled in conjunction with #140745 which will revise m_Zero handling to be closed to m_AllOnes

### PR DESCRIPTION
**Pull request by woruyu**
### Summary
This PR resolves https://github.com/llvm/llvm-project/issues/146871 
This PR resolves https://github.com/llvm/llvm-project/issues/140745

Refactor m_Zero/m_One/m_AllOnes all use struct template function to match and AllowUndefs=false as default.

### CODE REVIEW

**Comment by woruyu** [comment]
Hello, any suggestion for this PR, thank you! @RKSimon @mshockwave

**Review by arsenm — COMMENTED** [review]
Probably should get tests in unittests/CodeGen/SelectionDAGPatternMatchTest.cpp

**Comment by woruyu** [comment]
> Probably should get tests in unittests/CodeGen/SelectionDAGPatternMatchTest.cpp

That makes sense，I think adding test for m_Zero/m_One/m_AllOnes default behavior and supportting peekthrough bitcast is a better choice, I will add it!

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -4281,7 +4281,7 @@ SDValue DAGCombiner::visitSUB(SDNode *N) {
     return V;
 
   // (A - B) - 1  ->  add (xor B, -1), A
-  if (sd_match(N, m_Sub(m_OneUse(m_Sub(m_Value(A), m_Value(B))), m_One())))
+  if (sd_match(N, m_Sub(m_OneUse(m_Sub(m_Value(A), m_Value(B))), m_One(true))))
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:4284]: (style) `m_One(/*AllowUndefs=*/true)`

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 2]
```diff
@@ -12569,6 +12569,18 @@ bool llvm::isAllOnesOrAllOnesSplat(SDValue N, bool AllowUndefs) {
   return C && C->isAllOnes() && C->getValueSizeInBits(0) == BitWidth;
 }
 
+bool llvm::isOnesOrOnesSplat(SDValue N, bool AllowUndefs) {
+  N = peekThroughBitcasts(N);
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: you can't peek through bitcast for isOnesOrOnesSplat - e.g. otherwise you could match a v4i32 <1,1,1,1> to a v2i64 type (which wouldn't be <1,1>).

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 3]
```diff
@@ -57925,22 +57925,20 @@ static SDValue combineAdd(SDNode *N, SelectionDAG &DAG,
...
-      return DAG.getNode(X86ISD::PSADBW, DL, VT, Sum,
-                         getZeroVector(OpVT, Subtarget, DAG, DL));
-    }
+  if (sd_match(Op0, m_c_BinOp(X86ISD::PSADBW, m_Value(X), m_Zero())) &&
+      sd_match(Op1, m_c_BinOp(X86ISD::PSADBW, m_Value(Y), m_Zero())) &&
+      DAG.willNotOverflowAdd(/*IsSigned=*/false, X, Y)) {
+    MVT OpVT = X.getSimpleValueType();
+    SDValue Sum = DAG.getNode(ISD::ADD, DL, OpVT, X, Y);
+    return DAG.getNode(X86ISD::PSADBW, DL, VT, Sum,
+                       getZeroVector(OpVT, Subtarget, DAG, DL));
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp]: don't include this change in the patch - happy for you to handle it in your own follow PR though

File: llvm/include/llvm/CodeGen/SelectionDAGNodes.h [hunk 4]
```diff
@@ -1937,6 +1937,10 @@ LLVM_ABI bool isOneOrOneSplat(SDValue V, bool AllowUndefs = false);
 /// Does not permit build vector implicit truncation.
 LLVM_ABI bool isAllOnesOrAllOnesSplat(SDValue V, bool AllowUndefs = false);
 
+LLVM_ABI bool isOnesOrOnesSplat(SDValue N, bool AllowUndefs = false);
```
Comment (RKSimon) [inline llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1943]: add doxygen comment

File: llvm/include/llvm/CodeGen/SelectionDAGNodes.h [hunk 5]
```diff
@@ -1937,6 +1937,10 @@ LLVM_ABI bool isOneOrOneSplat(SDValue V, bool AllowUndefs = false);
...
+
+LLVM_ABI bool isZeroOrZeroSplat(SDValue N, bool AllowUndefs = false);
```
Comment (RKSimon) [inline llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1948]: add doxygen comment

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 1 above)
Comment (woruyu) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:4284]: Done!

File: llvm/lib/Target/X86/X86ISelLowering.cpp (hunk 3 above)
Comment (woruyu) [reply llvm/lib/Target/X86/X86ISelLowering.cpp]: Done!

File: llvm/include/llvm/CodeGen/SelectionDAGNodes.h (hunk 4 above)
Comment (woruyu) [reply llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1943]: Done!

File: llvm/include/llvm/CodeGen/SelectionDAGNodes.h (hunk 5 above)
Comment (woruyu) [reply llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1948]: Done!

Comment (RKSimon) [reply llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1948]: missing push?

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp (hunk 2 above)
Comment (woruyu) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Done! understand! And modify `C->getAPIntValue() == 1` to `APInt::isSameValue(C->getAPIntValue(), APInt(C->getAPIntValue().getBitWidth(), 1))` to avoid bit > 64 corner case

File: llvm/include/llvm/CodeGen/SelectionDAGNodes.h (hunk 5 above)
Comment (woruyu) [reply llvm/include/llvm/CodeGen/SelectionDAGNodes.h:1948]: I just pushed the changes. Thanks for the heads-up!

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp [hunk 6]
```diff
@@ -825,3 +825,89 @@ TEST_F(SelectionDAGPatternMatchTest, matchReassociatableOp) {
...
+
+TEST_F(SelectionDAGPatternMatchTest, MatchZeroOneAllOnes) {
+  using namespace SDPatternMatch;
+
+  SDLoc DL;
+  EVT VT = EVT::getIntegerVT(Context, 32);
+
+  // Scalar constant 0
+  SDValue Zero = DAG->getConstant(0, DL, VT);
+  EXPECT_TRUE(sd_match(Zero, DAG.get(), llvm::SDPatternMatch::m_Zero()));
```
Comment (mshockwave) [inline llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp:837]: I think you forgot to remove the extra `llvm::SDPatternMatch` prefix here

Comment (woruyu) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp:837]: Good catch — I missed that during cleanup. I’ll send a follow-up patch to remove the redundant prefix.

Comment (woruyu) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp:837]: The related PR is in https://github.com/llvm/llvm-project/pull/147443

**Comment by RKSimon** [comment]
@woruyu do you have the `add(psadbw(X,0),psadbw(Y,0)) -> psadbw(add(X,Y),0)` patch somewhere?

**Comment by woruyu** [comment]
> @woruyu do you have the `add(psadbw(X,0),psadbw(Y,0)) -> psadbw(add(X,Y),0)` patch somewhere?

I originally added the SDPattern for add(psadbw(X,0), psadbw(Y,0)) -> psadbw(add(X,Y),0) in commit [e71c622](https://github.com/llvm/llvm-project/commit/e71c622fa858f5562947774a4a5110ba48f03bf7), but removed it during a force-push in [229ec28](https://github.com/llvm/llvm-project/commit/229ec2822e5c5d959f287eb8f93fbce0007e3b13) based on review feedback. It’s not included in the final PR.

**Comment by RKSimon** [comment]
Sorry for the confusion - I meant that I asked you in the review to remove it from #147044 but then create a separate PR for it as a followup

**Comment by woruyu** [comment]
> Sorry for the confusion - I meant that I asked you in the review to remove it from #147044 but then create a separate PR for it as a followup

Thanks a lot for the clarification — understand, I’d be happy to submit it as a follow-up patch.

**Comment by woruyu** [comment]
> Sorry for the confusion - I meant that I asked you in the review to remove it from #147044 but then create a separate PR for it as a followup

The related PR is https://github.com/llvm/llvm-project/pull/147637
