### PR TITLE
[Clang] prevent recovery call expression from proceeding with explicit attributes and undeclared templates

### LINKED ISSUE #49093: [C++20] ICE on valid: (!KnownValid && "Explicit template arguments?") in AddOverloadedCallCandidate
|  |  |
| --- | --- |
| Bugzilla Link | [49749](https://llvm.org/bz49749) |
| Version | trunk |
| OS | All |
| CC | @AaronBallman,@zygoloid |

## Extended Description 
cat >test.cpp <<EOF
// https://godbolt.org/z/TqhebWG7f
struct A {
    static int a() { return 0; }
    decltype(a < 0 > (0)) b;
};

void test_is_bool(bool t) {}
void test_is_bool(int t) {}

int main() {
    A x;
    test_is_bool(x.b);
}
EOF
clang++ -std=c++20 -c test.cpp

The symptom is an assert-fail, so this reproduces only when Clang is built in debug mode.

Clang's treatment of `a < 0 > (0)` seems to have changed from C++17 mode to C++20 mode: Clang-built-without-assertions rejects this code in C++20 mode but accepts it in C++17 mode. GCC trunk rejects this code in ALL language modes. GCC 10.2, MSVC, ICC accept this code in ALL language modes.

Here's Clang's output for the above program (when built with assertions enabled).
============

test.cpp:4:14: error: member 'a' used before its declaration
    decltype(a < 0 > (0)) b;
             ^
test.cpp:3:16: note: member is declared here
    static int a() { return 0; }
               ^
Assertion failed: (!KnownValid && "Explicit template arguments?"), function AddOverloadedCallCandidate, file /Users/aodwyer/llvm-project/clang/lib/Sema/SemaOverload.cpp, line 12602.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /Users/aodwyer/llvm-project/build-debug/bin/clang++ -std=c++20 -c test.cpp
1.	test.cpp:4:24: current parser token ')'
2.	test.cpp:2:1: parsing struct/union/class body 'A'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  clang++                  0x0000000104edb63d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 61
1  clang++                  0x0000000104edbbbb PrintStackTraceSignalHandler(void*) + 27
2  clang++                  0x0000000104ed9b13 llvm::sys::RunSignalHandlers() + 115
3  clang++                  0x0000000104edaede llvm::sys::CleanupOnSignal(unsigned long) + 110
4  clang++                  0x0000000104d79b20 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) + 192
5  clang++                  0x0000000104d79e73 CrashRecoverySignalHandler(int) + 195
6  libsystem_platform.dylib 0x00007fff697a5b5d _sigtramp + 29
7  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603338746537152
8  libsystem_c.dylib        0x00007fff6965f6a6 abort + 127
9  libsystem_c.dylib        0x00007fff6962820d basename_r + 0
10 clang++                  0x00000001095c3653 AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool) + 243
11 clang++                  0x00000001095c346c clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) + 780
12 clang++                  0x00000001095c3c6a clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) + 826
13 clang++                  0x00000001095c4285 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 373
14 clang++                  0x0000000108f982e3 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 2467
15 clang++                  0x00000001095e6cf5 BuildRecoveryCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool, bool) + 1925
16 clang++                  0x00000001095c4816 FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) + 774
17 clang++                  0x00000001095c43c1 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 689
18 clang++                  0x0000000108f982e3 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 2467
19 clang++                  0x0000000108fb927f clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) + 143
20 clang++                  0x000000010878055e clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) + 5742
21 clang++                  0x0000000108787234 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) + 19844
22 clang++                  0x0000000108784416 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) + 8038
23 clang++                  0x000000010877ee09 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) + 89
24 clang++                  0x000000010877d298 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) + 280
25 clang++                  0x000000010877d14f clang::Parser::ParseExpression(clang::Parser::TypeCastState) + 31
26 clang++                  0x000000010875c874 clang::Parser::ParseDecltypeSpecifier(clang::DeclSpec&) + 836
27 clang++                  0x00000001087926df clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool, bool*, bool, clang::IdentifierInfo**, bool, bool) + 1295
28 clang++                  0x0000000108826160 clang::Parser::TryAnnotateCXXScopeToken(bool) + 304
29 clang++                  0x000000010873ca94 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 4596
30 clang++                  0x0000000108765d1d clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject*) + 2781
31 clang++                  0x00000001087687da clang::Parser::ParseCXXClassMemberDeclarationWithPragmas(clang::AccessSpecifier&, clang::Parser::ParsedAttributesWithRange&, clang::TypeSpecifierType, clang::Decl*) + 2122
32 clang++                  0x0000000108762c73 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) + 2963
33 clang++                  0x0000000108760b78 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) + 9720
34 clang++                  0x000000010873f4c3 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) + 15395
35 clang++                  0x00000001088209d8 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) + 136
36 clang++                  0x0000000108820522 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) + 194
37 clang++                  0x000000010881f61f clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) + 3551
38 clang++                  0x000000010881d6bb clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) + 1739
39 clang++                  0x000000010881cf63 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) + 51
40 clang++                  0x000000010872a53f clang::ParseAST(clang::Sema&, bool, bool) + 415
41 clang++                  0x0000000105f70e8c clang::ASTFrontendAction::ExecuteAction() + 300
42 clang++                  0x00000001058a955a clang::CodeGenAction::ExecuteAction() + 90
43 clang++                  0x0000000105f704bc clang::FrontendAction::Execute() + 124
44 clang++                  0x0000000105e8a2e8 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 920
45 clang++                  0x000000010607972e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1614
46 clang++                  0x000000010143363d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1501
47 clang++                  0x0000000101425e3b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 427
48 clang++                  0x0000000105c414c5 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const::$_1::operator()() const + 37
49 clang++                  0x0000000105c41495 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const::$_1>(long) + 21
50 clang++                  0x0000000104d799b9 llvm::function_ref<void ()>::operator()() const + 25
51 clang++                  0x0000000104d7995c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 236
52 clang++                  0x0000000105c3ff5c clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const + 524
53 clang++                  0x0000000105bea406 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const + 758
54 clang++                  0x0000000105bea6c8 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) const + 152
55 clang++                  0x0000000105c054f5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) + 325
56 clang++                  0x000000010142538b main + 3371
57 libdyld.dylib            0x00007fff695ba3d5 start + 1
clang-13: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 13.0.0 (git@github.com:Quuxplusone/llvm-project 4adea96d9486bb19440243420ba234c1916907c9)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Users/aodwyer/llvm-project/build-debug/bin
clang-13: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /var/folders/0l/9t0yv2890_g4wgmy53n_mg7w0000gy/T/test-a31910.cpp
clang-13: note: diagnostic msg: /var/folders/0l/9t0yv2890_g4wgmy53n_mg7w0000gy/T/test-a31910.sh
clang-13: note: diagnostic msg: Crash backtrace is located in
clang-13: note: diagnostic msg: /Users/aodwyer/Library/Logs/DiagnosticReports/clang-13_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-13: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-13: note: diagnostic msg: 

********************

### LINKED ISSUE #107047: Clang crashes on incorrect code with -std=c++20
Reproducer: https://godbolt.org/z/Merf3f3Ms
```
struct A {
    static constexpr auto as_tuple_helper() {
        return std::tuple_size<decltype(static_cast<Tuple&>(*this)._data)>;
    }
    static constexpr int data_size = as_tuple_helper<1>();
};
```
Command to compile:
```
clang++ --std=c++20 main.cpp
```
```
clang++: /root/llvm-project/clang/lib/Sema/SemaOverload.cpp:13530: void AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool): Assertion `!KnownValid && "Explicit template arguments?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:7:57: current parser token ')'
2.	<source>:1:1: parsing struct/union/class body 'A'
 #0 0x0000000003b1e5e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b1e5e8)
 #1 0x0000000003b1c2ac llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b1c2ac)
 #2 0x0000000003a64768 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000072e8a6042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000072e8a60969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000072e8a6042476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000072e8a60287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000072e8a602871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000072e8a6039e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006fd38b9 AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool) SemaOverload.cpp:0:0
#10 0x0000000006fd3ae9 clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fd3ae9)
#11 0x0000000006fd3dee clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fd3dee)
#12 0x0000000006fe0515 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fe0515)
#13 0x0000000006b86e18 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b86e18)
#14 0x0000000006fe0072 FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) SemaOverload.cpp:0:0
#15 0x0000000006fe0704 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fe0704)
#16 0x0000000006b86e18 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b86e18)
#17 0x0000000006b8937c clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b8937c)
#18 0x000000000660ccad clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x660ccad)
#19 0x0000000006605a31 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6605a31)
#20 0x0000000006605c9e clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6605c9e)
#21 0x0000000006607b8a clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6607b8a)
#22 0x0000000006607d29 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6607d29)
#23 0x00000000065e5e61 clang::Parser::ParseCXXMemberInitializer(clang::Decl*, bool, clang::SourceLocation&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65e5e61)
#24 0x00000000065f8d47 clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::ParsingDeclRAIIObject*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f8d47)
#25 0x00000000065f9e75 clang::Parser::ParseCXXClassMemberDeclarationWithPragmas(clang::AccessSpecifier&, clang::ParsedAttributes&, clang::TypeSpecifierType, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f9e75)
#26 0x00000000065fb9c7 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65fb9c7)
#27 0x00000000065fe170 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65fe170)
#28 0x00000000065d2a50 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65d2a50)
#29 0x000000000658f594 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x658f594)
#30 0x000000000658ffee clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x658ffee)
#31 0x0000000006596637 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6596637)
#32 0x000000000659750d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x659750d)
#33 0x00000000065979b0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65979b0)
#34 0x000000000658a9c2 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x658a9c2)
#35 0x0000000004469918 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4469918)
#36 0x00000000046f8ee9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x46f8ee9)
#37 0x000000000467c4de clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x467c4de)
#38 0x00000000047e2dce clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47e2dce)
#39 0x0000000000caa52f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcaa52f)
#40 0x0000000000ca377a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#41 0x00000000044acd09 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#42 0x0000000003a64c14 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a64c14)
#43 0x00000000044ad2ff clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#44 0x00000000044732a5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44732a5)
#45 0x0000000004473d0d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4473d0d)
#46 0x000000000447b955 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x447b955)
#47 0x0000000000ca7925 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca7925)
#48 0x0000000000b7b664 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb7b664)
#49 0x000072e8a6029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#50 0x000072e8a6029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#51 0x0000000000ca322e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca322e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #107047
Fixes #49093

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@AaronBallman could you please review this fix? thanks

**Comment by a-tarasyuk** [comment]
@AaronBallman could you please review these changes? thanks

File: clang/test/SemaTemplate/recovery-crash-cxx20.cpp [hunk 1]
```diff
@@ -0,0 +1,32 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++20 %s
+
+namespace GH49093 {
+  class B {
+  public:
+    static int a() { return 0; } // expected-note {{member is declared here}}
+    decltype(a< 0 >(0)) test;    // expected-error {{member 'a' used before its declaration}}
```
Comment (AaronBallman) [inline clang/test/SemaTemplate/recovery-crash-cxx20.cpp:7]: These diagnostics make me think there's a different bug that we're glossing over. 1) `a` is not being used before it's declaration; the declaration is right on line 6. 2) Why does this not get an "'a' is not a template" kind of diagnostic?

Comment (erichkeane) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp:7]: Yeah, doing any amount of diagnostics before forming the unresolved lookup seems wrong.  I suspect the approach here is trying to bail out too quickly.

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: @erichkeane @AaronBallman Thanks for the feedback. @AaronBallman The recovery checker attempts to diagnose an empty lookup and also tries to handle dependent member lookups, which detect them as being used before declarations

https://github.com/llvm/llvm-project/blob/df935ff4eca91013553edbf3ca1d45b568f6709f/clang/lib/Sema/SemaExpr.cpp#L2473-L2490

https://github.com/llvm/llvm-project/blob/df935ff4eca91013553edbf3ca1d45b568f6709f/clang/lib/Sema/SemaExpr.cpp#L2425

Is it acceptable to handle a lookup result that isn’t a template but uses explicit templated arguments at this stage?

Comment (erichkeane) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: I think it generally DOES make sense to try the lookup?  We shouldn't crash of course, but failing to do the lookup pretending it is NOT a template makes a lot of sense to me.

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: > I think it generally DOES make sense to try the lookup?

In the case of viable functions, the checker tries to recover even when the candidate list is empty. 

https://github.com/llvm/llvm-project/blob/416c3ce0138ff4039dab13ff634ee6392b9a3c7b/clang/lib/Sema/SemaOverload.cpp#L14056-L14059


https://github.com/llvm/llvm-project/blob/416c3ce0138ff4039dab13ff634ee6392b9a3c7b/clang/lib/Sema/SemaOverload.cpp#L13844-L13857

Once the lookup is complete

https://github.com/llvm/llvm-project/blob/df935ff4eca91013553edbf3ca1d45b568f6709f/clang/lib/Sema/SemaExpr.cpp#L2471

It identifies the expression as a dependent member

https://github.com/llvm/llvm-project/blob/df935ff4eca91013553edbf3ca1d45b568f6709f/clang/lib/Sema/SemaExpr.cpp#L2490

This is the entry point for these kinds of names, where we can try to stop the recovery process that causes the crash. Or should we skip building recovery call expression entirely for such cases?

Comment (erichkeane) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: It sounds like we just need to 'try harder' to recover.  A fallback that treats it as a 'non template' would probably be better.  As far as the 'dependent member lookup', perhaps that needs to check for a recoveryexpr better and come up with a better recovery.

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: I also thought skipping `DiagnoseDependentMemberLookup` and proceeding with the correction, as this seems to avoid those candidates and focus on the appropriate templated candidates

https://github.com/llvm/llvm-project/blob/3138eb500c9462bcb6899088d49644adb4d90f62/clang/lib/Sema/SemaExpr.cpp#L2500-L2612

since `DiagnoseDependentMemberLookup` treats these candidates as valid, it continues with recovery and constructs the call expression as entirely valid 

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L13899-L13901

https://github.com/llvm/llvm-project/blob/3138eb500c9462bcb6899088d49644adb4d90f62/clang/lib/Sema/SemaExpr.cpp#L6528-L6530

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L14145

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L13937

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: I also thought skipping `DiagnoseDependentMemberLookup` and proceeding with the correction, as this seems to avoid those candidates and focus on the appropriate templated candidates

https://github.com/llvm/llvm-project/blob/3138eb500c9462bcb6899088d49644adb4d90f62/clang/lib/Sema/SemaExpr.cpp#L2500-L2612

since `DiagnoseDependentMemberLookup` treats these candidates as valid, it continues with recovery and constructs the call expression as entirely valid 

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L13899-L13901

https://github.com/llvm/llvm-project/blob/3138eb500c9462bcb6899088d49644adb4d90f62/clang/lib/Sema/SemaExpr.cpp#L6528-L6530

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L14145

https://github.com/llvm/llvm-project/blob/9ac00b85e05d21be658d6aa0c91cbe05bb5dbde2/clang/lib/Sema/SemaOverload.cpp#L13937

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: > A fallback that treats it as a 'non template' would probably be better

@AaronBallman @erichkeane Do you mean that the checker can construct a recovery call expression by skipping the `ExplicitTemplateArgs` in such cases?

Comment (erichkeane) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: I'm not explicitly saying that (hah!).  But the behavior you have here is not correct.  First, I still don't see why it would say 'used before its declaration', when its declaration is right above it.  Second, SHOULD say something like, "non template used with template args, what are you doing?" sorta error.  

As far as recovery, it could/should probably treat it as if you HADN'T used the template arguments and continue, so any recovery (for the type reference?) should be based on the found-but-not-template type.

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: I added the changes and the [test](https://github.com/llvm/llvm-project/pull/107786/files#diff-035f4e94708ebca719a751e5e44a5a761610649239bc3cec2593a670929c8d01R27-R32) no longer throws the _`used before its declaration`_ error. From my understanding, if recovery detects explicit arguments, the checker should try looking up candidates with templates. If it finds a match, recovery can continue; if not, it should throw an error and attempt typo correction. Does that make sense?

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/recovery-crash-cxx20.cpp]: @AaronBallman @erichkeane could you kindly take a look at the latest changes?

**Review by erichkeane — APPROVED** [review]
Diag seems reasonable to me now.  I want Aaron to take another look (he's sadly out this week, so it'll have to be when he gets back), but I think this seems to make sense here.

**Comment by a-tarasyuk** [comment]
@erichkeane thanks for the feedback

**Comment by a-tarasyuk** [comment]
@AaronBallman could you review these changes? thanks

**Comment by a-tarasyuk** [comment]
@AaronBallman when you have a moment, could you review these changes? Thanks!

**Review by cor3ntin — APPROVED** [review]
LGTM. do you need me to merge it for you?

**Comment by a-tarasyuk** [comment]
@cor3ntin yes, I do. Thanks
