### PR TITLE
[clang] Allow parentheses around CTAD declarators

### LINKED ISSUE #39811: CTAD on variable with parenthesized initializer
|  |  |
| --- | --- |
| Bugzilla Link | [40465](https://llvm.org/bz40465) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
```cpp
template <typename = void>
struct Foo {};

int main() {
  Foo f; // everyone accepts
  Foo (g); // clang rejects
           // gcc accepts, edg accepts, msvc accepts
}
```
clang says:

error: cannot use parentheses when declaring variable with deduced class template specialization type

This seems to be a highly specific error message but I can't see why this would be disallowed. [dcl.type.class.deduct] seems to allow `g`, but again since the message is so specific, I don't know. The other three compilers accept the code.

### PR DESCRIPTION
**Pull request by offsetof**
Fixes #39811

### CODE REVIEW

**Review by Sirraide — COMMENTED** [review]
So the implementation of this seems fine, but looking at how other compilers handle this, GCC and MSVC accept this, whereas EDG rejects. I agree w/ the comment that that is a bit silly to reject this, but can you check what the standard has to say about this? If this is disallowed by the standard, we might want to issue an extension warning (disabled by default) here.

**Review by Sirraide — APPROVED** [review]
Actually, I just checked #39811, and apparently this was a CWG issue that has been resolved, so in that case this seems fine.

**Comment by Sirraide** [comment]
CC @Endilll Should this also add a test to [cwg23xx.cpp](https://github.com/llvm/llvm-project/blob/main/clang/test/CXX/drs/cwg23xx.cpp)?

**Comment by cor3ntin** [comment]
> CC @Endilll Should this also add a test to [cwg23xx.cpp](https://github.com/llvm/llvm-project/blob/main/clang/test/CXX/drs/cwg23xx.cpp)?

Yes, please!

File: clang/test/CXX/drs/cwg23xx.cpp [hunk 1]
```diff
@@ -379,6 +379,20 @@ class C {
 };
 } // namespace cwg2370
 
+namespace cwg2376 { // cwg2376: 21
+#if __cpp_deduction_guides >= 201703
```
Comment (zwuis) [inline clang/test/CXX/drs/cwg23xx.cpp:383]:
```suggestion
#if __cplusplus >= 201703L
```

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks. Will you need me to merge that for you?
