### PR TITLE
[flang] Fix for atand(Y,X), and implment atan2d(Y,X), atanpi(X), atanpi(Y,X), atan2pi(Y,X)

### LINKED ISSUE #78568: [Flang] ICE on `atand(x, y)`
Reproducer (use command line `flang-new atand.f90`)
```console
$ cat atand.f90
program p
   real x, y
   x = 1.
   y = x
   print *, atand(x, y)
end
```

Assertion failure:
```txt
flang-new: /tmp/llvm-project/flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2124: mlir::Value fir::IntrinsicLibrary::genAtand(mlir::Type, llvm::ArrayRef<mlir::Value>): Assertion `args.size() == 1' failed.
```

Stack dump:
```console
 #0 0x000055e0852b1e2f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) 
 #1 0x000055e0852b24b0 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f53036af520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007f5303703a7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #4 0x00007f5303703a7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #5 0x00007f5303703a7c pthread_kill ./nptl/pthread_kill.c:89:10
 #6 0x00007f53036af476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00007f53036957f3 abort ./stdlib/abort.c:81:7
 #8 0x00007f530369571b _nl_load_domain ./intl/loadmsgcat.c:1177:9
 #9 0x00007f53036a6e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x000055e086374b7d fir::IntrinsicLibrary::genAtand(mlir::Type, llvm::ArrayRef<mlir::Value>)
#11 0x000055e086392ff4 fir::ExtendedValue fir::IntrinsicLibrary::genElementalCall<mlir::Value (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<mlir::Value>)>(mlir::Value (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<mlir::Value>), llvm::StringRef, mlir::Type, llvm::ArrayRef<fir::ExtendedValue>, bool) 
#12 0x000055e086392ea2 fir::invokeHandler(mlir::Value (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<mlir::Value>), fir::IntrinsicHandler const&, std::optional<mlir::Type>, llvm::ArrayRef<fir::ExtendedValue>, bool, fir::IntrinsicLibrary&) IntrinsicCall.cpp:0:0
#13 0x000055e086392d7c std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<fir::ExtendedValue> (*)(fir::IntrinsicLibrary::genIntrinsicCall(llvm::StringRef, std::optional<mlir::Type>, llvm::ArrayRef<fir::ExtendedValue>)::$_1&&, std::variant<mlir::Value (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<mlir::Value>), fir::ExtendedValue (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<fir::ExtendedValue>), void (fir::IntrinsicLibrary::*)(llvm::ArrayRef<fir::ExtendedValue>)> const&)>, std::integer_sequence<unsigned long, 0ul>>::__visit_invoke(fir::IntrinsicLibrary::genIntrinsicCall(llvm::StringRef, std::optional<mlir::Type>, llvm::ArrayRef<fir::ExtendedValue>)::$_1&&, std::variant<mlir::Value (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<mlir::Value>), fir::ExtendedValue (fir::IntrinsicLibrary::*)(mlir::Type, llvm::ArrayRef<fir::ExtendedValue>), void (fir::IntrinsicLibrary::*)(llvm::ArrayRef<fir::ExtendedValue>)> const&) IntrinsicCall.cpp:0:0
#14 0x000055e0863723ce fir::IntrinsicLibrary::genIntrinsicCall(llvm::StringRef, std::optional<mlir::Type>, llvm::ArrayRef<fir::ExtendedValue>) 
#15 0x000055e08638c596 fir::genIntrinsicCall(fir::FirOpBuilder&, mlir::Location, llvm::StringRef, std::optional<mlir::Type>, llvm::ArrayRef<fir::ExtendedValue>, Fortran::lower::AbstractConverter*) 
#16 0x000055e0857d42c9 genIntrinsicRefCore(llvm::SmallVector<std::optional<Fortran::lower::PreparedActualArgument>, 1u>&, Fortran::evaluate::SpecificIntrinsic const*, fir::IntrinsicArgumentLoweringRules const*, (anonymous namespace)::CallContext&) ConvertCall.cpp:0:0
#17 0x000055e0857d1284 genHLFIRIntrinsicRefCore(llvm::SmallVector<std::optional<Fortran::lower::PreparedActualArgument>, 1u>&, Fortran::evaluate::SpecificIntrinsic const*, fir::IntrinsicArgumentLoweringRules const*, (anonymous namespace)::CallContext&) ConvertCall.cpp:0:0
#18 0x000055e0857d02c8 genIntrinsicRef(Fortran::evaluate::SpecificIntrinsic const*, (anonymous namespace)::CallContext&) ConvertCall.cpp:0:0
#19 0x000055e0857cc428 Fortran::lower::convertCallToHLFIR(mlir::Location, Fortran::lower::AbstractConverter&, Fortran::evaluate::ProcedureRef const&, std::optional<mlir::Type>, Fortran::lower::SymMap&, Fortran::lower::StatementContext&) 
#20 0x000055e085914c70 std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<hlfir::EntityWithAttributes> (*)(hlfir::EntityWithAttributes (anonymous namespace)::HlfirBuilder::gen<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>(Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>> const&)::'lambda'(Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4> const&)&&, std::variant<Fortran::evaluate::ComplexComponent<4>, Fortran::evaluate::Parentheses<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Negate<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Add<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Subtract<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Multiply<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Divide<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Power<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::RealToIntPower<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Extremum<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Convert<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, (Fortran::common::TypeCategory)0>, Fortran::evaluate::Convert<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, (Fortran::common::TypeCategory)1>, Fortran::evaluate::Constant<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::ArrayConstructor<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Designator<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::FunctionRef<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>> const&)>, std::integer_sequence<unsigned long, 15ul>>::__visit_invoke(hlfir::EntityWithAttributes (anonymous namespace)::HlfirBuilder::gen<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>(Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>> const&)::'lambda'(Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4> const&)&&, std::variant<Fortran::evaluate::ComplexComponent<4>, Fortran::evaluate::Parentheses<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Negate<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Add<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Subtract<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Multiply<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Divide<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Power<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::RealToIntPower<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Extremum<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Convert<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, (Fortran::common::TypeCategory)0>, Fortran::evaluate::Convert<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, (Fortran::common::TypeCategory)1>, Fortran::evaluate::Constant<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::ArrayConstructor<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::Designator<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>, Fortran::evaluate::FunctionRef<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>> const&) ConvertExprToHLFIR.cpp:0:0
#21 0x000055e085912d8b hlfir::EntityWithAttributes (anonymous namespace)::HlfirBuilder::gen<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>>(Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>> const&) ConvertExprToHLFIR.cpp:0:0
#22 0x000055e085904af7 hlfir::EntityWithAttributes (anonymous namespace)::HlfirBuilder::gen<Fortran::evaluate::SomeKind<(Fortran::common::TypeCategory)1>>(Fortran::evaluate::Expr<Fortran::evaluate::SomeKind<(Fortran::common::TypeCategory)1>> const&) ConvertExprToHLFIR.cpp:0:0
#23 0x000055e0858fb2e8 hlfir::EntityWithAttributes (anonymous namespace)::HlfirBuilder::gen<Fortran::evaluate::SomeType>(Fortran::evaluate::Expr<Fortran::evaluate::SomeType> const&) ConvertExprToHLFIR.cpp:0:0
#24 0x000055e0858fb7fd Fortran::lower::convertExprToValue(mlir::Location, Fortran::lower::AbstractConverter&, Fortran::evaluate::Expr<Fortran::evaluate::SomeType> const&, Fortran::lower::SymMap&, Fortran::lower::StatementContext&) 
#25 0x000055e08576acdb (anonymous namespace)::FirConverter::genExprValue(Fortran::evaluate::Expr<Fortran::evaluate::SomeType> const&, Fortran::lower::StatementContext&, mlir::Location*) Bridge.cpp:0:0
#26 0x000055e0859802cc genOutputItemList(Fortran::lower::AbstractConverter&, mlir::Value, std::__cxx11::list<Fortran::parser::OutputItem, std::allocator<Fortran::parser::OutputItem>> const&, bool, bool, mlir::Value&, bool) IO.cpp:0:0
#27 0x000055e08597d063 Fortran::lower::genPrintStatement(Fortran::lower::AbstractConverter&, Fortran::parser::PrintStmt const&) 
#28 0x000055e085786fe5 (anonymous namespace)::FirConverter::genFIR(Fortran::lower::pft::Evaluation&, bool) Bridge.cpp:0:0
#29 0x000055e0857b9db7 (anonymous namespace)::FirConverter::lowerFunc(Fortran::lower::pft::FunctionLikeUnit&) Bridge.cpp:0:0
#30 0x000055e0857690b3 Fortran::lower::LoweringBridge::lower(Fortran::parser::Program const&, Fortran::semantics::SemanticsContext const&) 
#31 0x000055e0856ceba3 Fortran::frontend::CodeGenAction::beginSourceFileAction() 
#32 0x000055e0852d47ef Fortran::frontend::FrontendAction::beginSourceFile(Fortran::frontend::CompilerInstance&, Fortran::frontend::FrontendInputFile const&) 
#33 0x000055e0852c98b9 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&)
#34 0x000055e0852d7a3e Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*)
#35 0x000055e084f9243d fc1_main(llvm::ArrayRef<char const*>, char const*)
#36 0x000055e084f91426 main 
#37 0x00007f5303696d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#38 0x00007f5303696e40 call_init ./csu/../csu/libc-start.c:128:20
#39 0x00007f5303696e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#40 0x000055e084f90985 _start 
flang-new: error: unable to execute command: Aborted
flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git 651a42ff65c3afc2a2ec6c7fc19009387757d686)
Target: x86_64-unknown-linux-gnu
```

### PR DESCRIPTION
**Pull request by yiwu0b11**
Both call the `mlir::math::Atan2op`, with the non zero check of: if Y is zeroX must not be 0.
Fix: https://github.com/llvm/llvm-project/issues/78568

### CODE REVIEW

**Comment by yi-wu-arm** [comment]
I didn't add the result check on both `atand(Y,X)` nor `atan2d(Y,X)`, doesn't seem possible for them to have a value that doesn't lie between -180 <-> 180

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 1]
```diff
@@ -2128,13 +2129,53 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
+                                        llvm::ArrayRef<mlir::Value> args) {
+  assert(args.size() == 2);
+
+  mlir::Value y = fir::getBase(args[0]);
+  mlir::Value x = fir::getBase(args[1]);
+
+  // When Y == 0 X must not be 0
+  mlir::Value zero = builder.createRealZeroConstant(loc, y.getType());
+  mlir::Value cmpYEq0 = builder.create<mlir::arith::CmpFOp>(
+      loc, mlir::arith::CmpFPredicate::UEQ, y, zero);
```
Comment (yi-wu-arm) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2143]: I can change the check logic
from 
```cpp
bool YEq0 = y==0;
bool XEq0 = x==0;
bool terminationCheck = YEq0==XEq0;
if(terminationCheck) termination;
```
to
```cpp
bool YEq0 = y==0;
if(YEq0){
  bool XEq0 = x==0;
  if(XEq0) termination;
}
```
but I don't know if thats worth it

File: flang/lib/Evaluate/intrinsics.cpp [hunk 2]
```diff
@@ -333,11 +333,15 @@ static const IntrinsicInterface genericIntrinsicFunction[]{
...
     {"atan", {{"x", SameFloating}}, SameFloating},
-    {"atand", {{"x", SameFloating}}, SameFloating},
     {"atan", {{"y", OperandReal}, {"x", OperandReal}}, OperandReal},
-    {"atand", {{"y", OperandReal}, {"x", OperandReal}}, OperandReal},
+    {"atand",
+        {{"y", SameReal, Rank::scalar, Optionality::required,
+             common::Intent::In},
+            {"x", SameReal, Rank::scalar, Optionality::optional,
+                common::Intent::In}},
+        SameReal, Rank::scalar, IntrinsicClass::inquiryFunction},
```
Comment (jeanPerier) [inline flang/lib/Evaluate/intrinsics.cpp:342]: For what where these semantics changes required?
This does not looks correct to me. There is a subtle by important difference between the standard writing `ATAND([Y], X)` and `ATAND(Y, X) or ATAND(X)`.

In the former, we would have to treat Y has having the OPTIONAL attribute, and need special handling when the actual argument is a pointer, allocatable or OPTIONAL dummy. See the little `(optional)` that the standard adds for such argument (e.g. STAT in ATOMIC_ADD).

In the later, there is no such semantics, and if Y is syntactically here, it cannot be a disassociated pointer or absent optional.

Thus, I think the new change is not correct.

I would also not update things from  `OperandReal` to `SameReal`, flang is relaxed with regard to the same kind rule and should upcast to the highest precision (because that is what some other compilers do with numerical intrinsics and may be expected). Was there a reason to differ from atan2 behavior here too?

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp (hunk 1 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2143]: I actually do not see why the check is done for atan2d but not atand. The standard also says _"If Y has the value zero, X shall not have the value zero"_ for ATAND in your quote.

Note that the same requirement exists for ATAN2/ATAN and is not enforced. I would advise not enforcing this user constraint without some error checking flag due to the potential performance cost inside numerical kernel.

So you can probably just set genAtand as the handler for genAtan2d and save the duplication.

Comment (yi-wu-arm) [reply flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2143]: Ahh yes, you are right, both of them should have the zero check. Sorry I get confused with gfortran docs.

File: flang/lib/Evaluate/intrinsics.cpp (hunk 2 above)
Comment (yi-wu-arm) [reply flang/lib/Evaluate/intrinsics.cpp:342]: It is possible to have intrinsics with the same name but different para list here, like how it was done before. Having an `atand(X)`, and `atand(Y,X)`. But in the `intrinsicCall.cpp`, they seem only different from each other by `args.size()`. I do have another implementation by have both `atand(X)` and `atand(Y,X)`, and treat them both in `genAtand` by using `args.size()` for each case. I'm not sure if using `args.size()` is the safe/correct way to do this. I can use `atand([Y],X)` if `args.size()` could not be used.

The reason for me to use `atand(Y,[X])` here is that if X is not present, it would be treated as `atand(X)`. This definitely does not make sense in terms of naming, because I am actually using Y as X for the one input version `atand(X)`.

I will change it back from `SameReal` to `OperandReal` regard to the relaxation of same kind rule, and also update all other `atan` with the zero check.

Comment (jeanPerier) [reply flang/lib/Evaluate/intrinsics.cpp:342]: Using args.size() to distinguish here is fine and done in other cases like bessel_jn here https://github.com/llvm/llvm-project/blob/0f4e9e718b4e79d3f760fd7ea399c23fc97a7716/flang/lib/Optimizer/Builder/IntrinsicCall.cpp#L2200.

File: flang/test/Lower/Intrinsics/atan2d.f90 [hunk 3]
```diff
@@ -0,0 +1,28 @@
+! RUN: bbc -emit-fir -hlfir=false %s -o - | FileCheck %s --check-prefixes="CHECK,CHECK-FAST"
+! RUN: %flang_fc1 -emit-fir -flang-deprecated-no-hlfir %s -o - | FileCheck %s --check-prefixes="CHECK,CHECK-FAST"
+
+
+function test_real4_all_args(y,x)
```
Comment (kkwli) [inline flang/test/Lower/Intrinsics/atan2d.f90:5]: Did you mean the name to be `test_real4` instead?

File: flang/test/Lower/Intrinsics/atan2d.f90 [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+! CHECK-LABEL: @_QPtest_real4_all_args
+! CHECK: %[[terminationCheck:.*]] = arith.andi %[[YEq0:.*]], %[[XEq0:.*]] : i1
+! CHECK: fir.if %[[terminationCheck]]
+! CHECK-FAST: %[[atan2:.*]] = math.atan2 %{{.*}}, %{{.*}}: f32
+! CHECK: %[[dfactor:.*]] = arith.constant 57.295779513082323 : f64
+! CHECK: %[[factor:.*]] = fir.convert %[[dfactor]] : (f64) -> f32
+! CHECK: %{{.*}} = arith.mulf %[[atan2]], %[[factor]] fastmath<contract> : f32
+
+function test_real8_all_args(y,x)
```
Comment (kkwli) [inline flang/test/Lower/Intrinsics/atan2d.f90:18]: `test_real8_all_args` → `test_real8`?

File: flang/test/Lower/Intrinsics/atan2d.f90 (hunk 3 above)
Comment (yi-wu-arm) [reply flang/test/Lower/Intrinsics/atan2d.f90:5]: Well spot! Yes, they should not have `_all_args`, same changes will be made on `atan2pi` as well.

File: flang/test/Lower/Intrinsics/atan2d.f90 (hunk 4 above)
Comment (yi-wu-arm) [reply flang/test/Lower/Intrinsics/atan2d.f90]: done

**Comment by yi-wu-arm** [comment]
> I should have pointed it out early. The same issue occurs in `atand.f90` and `atandpi.f90`.

Both `atand` and `atanpi` can have one input and have two, I think its fine for the two-input version to have the name "_all_args`. Although usually "all_input" was used for function/subroutine that has an optional argument.

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 5]
```diff
@@ -2128,20 +2131,78 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
-  mlir::FunctionType ftype =
-      mlir::FunctionType::get(context, {resultType}, {args[0].getType()});
-  mlir::Value atan = getRuntimeCallGenerator("atan", ftype)(builder, loc, args);
+  mlir::Value atan;
+
+  // atand(Y,X) atan2d(Y,X) == atan2(Y,X) * 180/pi
+  if (args.size() == 2) {
+    mlir::Value y = fir::getBase(args[0]);
+    mlir::Value x = fir::getBase(args[1]);
+    atanNoneZeroCheck(y, x, builder, loc);
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2165]: Thanks for refactoring the checks. I still think it should not be emitted at -O2 and above to avoid preventing mlir::math::Atan2Op optimizations/vectorizations.

Comment (yi-wu-arm) [reply flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2165]: Just checked in the math dialect:
https://github.com/llvm/llvm-project/blob/0217d2e089afba8ca33330713787521ba52a1056/mlir/lib/Dialect/Math/IR/MathOps.cpp#L159-L161
while in practice (when testing with both y and x equal to 0), it returns 0.
So its probably fine to remove the `atanNoneZeroCheck` here?

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 6]
```diff
@@ -2128,20 +2131,56 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
+  } else {
+    mlir::FunctionType ftype =
+        mlir::FunctionType::get(context, {resultType}, {args[0].getType()});
+    atan = getRuntimeCallGenerator("atan", ftype)(builder, loc, args);
+  }
+  llvm::APFloat pi = llvm::APFloat(llvm::numbers::pi);
+  mlir::Value dfactor =
+      builder.createRealConstant(loc, mlir::FloatType::getF64(context), pi);
+  mlir::Value factor = builder.createConvert(loc, resultType, dfactor);
+  return builder.create<mlir::arith::DivFOp>(loc, atan, factor);
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2181]: I think using  `llvm::numbers::inv_pi` and a `MulFOp` is likely faster than using a DivFOp.

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 7]
```diff
@@ -2128,20 +2131,56 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
+    atan = getRuntimeCallGenerator("atan", ftype)(builder, loc, args);
+  }
   llvm::APFloat pi = llvm::APFloat(llvm::numbers::pi);
   mlir::Value dfactor = builder.createRealConstant(
       loc, mlir::FloatType::getF64(context), llvm::APFloat(180.0) / pi);
   mlir::Value factor = builder.createConvert(loc, resultType, dfactor);
   return builder.create<mlir::arith::MulFOp>(loc, atan, factor);
 }
 
+// ATAN, ATAN2PI
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2159]:
```suggestion
// ATANPI, ATAN2PI
```

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 8]
```diff
@@ -2128,20 +2131,56 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
+  // assert for: atand(X), atand(Y,X), atan2d(Y,X)
+  assert(args.size() >= 1 && args.size() <= 2);
+
   mlir::MLIRContext *context = builder.getContext();
-  mlir::FunctionType ftype =
-      mlir::FunctionType::get(context, {resultType}, {args[0].getType()});
-  mlir::Value atan = getRuntimeCallGenerator("atan", ftype)(builder, loc, args);
+  mlir::Value atan;
+
+  // atand(Y,X) atan2d(Y,X) == atan2(Y,X) * 180/pi
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2143]:
```suggestion
  // atand = atan * 180/pi
```

Is clearer IMHO.

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp [hunk 9]
```diff
@@ -2128,20 +2131,56 @@ IntrinsicLibrary::genAny(mlir::Type resultType,
...
+// ATAN, ATAN2PI
+mlir::Value IntrinsicLibrary::genAtanpi(mlir::Type resultType,
+                                        llvm::ArrayRef<mlir::Value> args) {
+  // assert for: atanpi(X), atanpi(Y,X), atan2pi(Y,X)
+  assert(args.size() >= 1 && args.size() <= 2);
+
+  mlir::Value atan;
+  mlir::MLIRContext *context = builder.getContext();
+
+  // atanpi(Y,X) atan2pi(Y,X) == atan2(Y,X) / pi
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Builder/IntrinsicCall.cpp:2168]:
```suggestion
  // atanpi = atan2 / pi
```

**Review by jeanPerier — COMMENTED** [review]
Few new comments, LGTM otherwise.

File: flang/lib/Optimizer/Builder/IntrinsicCall.cpp (hunk 6 above)
Comment (yi-wu-arm) [reply flang/lib/Optimizer/Builder/IntrinsicCall.cpp]: Thanks for pointing this out! Replaced with `inv_pi` and `MulfOp`

**Comment by yi-wu-arm** [comment]
build and pass all tests on Windows MSVC

**Comment by yi-wu-arm** [comment]
Hi, @jeanPerier sorry for throwing a ping, do you mind have a quick look at the updated code? I've changed `DivOp` to an `InvPi` with `MulOp`, and some small comment fix with rebase on main to solve merge conflict.

**Review by jeanPerier — APPROVED** [review]
LGTM, thanks for addressing my comments.
