### PR TITLE
Assumed-size arrays are shared and cannot be privatized

### LINKED ISSUE #110442: [Flang][OpenMP] OpenMP directive DEFAULT (NONE) is set, but a compilation-time error occurs indicating that the variable does not specify data-sharing attribute.
```
Version of flang-new : 20.0.0(2603c8b23be06116bc61bda36fae05b81d906c3f)/AArch64
```

When building [CP2K](https://www.cp2k.org/), the following error is detected.  
`OpenMP` directive `DEFAULT (NONE)` is set, but a compilation-time error occurs indicating that the variable does not specify `data-sharing` attribute.

The following are a self-made reproducer, Flang-new compilation result.

z1.f90:
```fortran
subroutine sub( aaa)
  real,dimension(*),intent(in)::aaa
  integer::ip
  real::ccc
!$omp parallel do private(ip,ccc) default(none)
  do ip = 1, 10
     ccc= aaa(ip)
  end do
end subroutine sub

program main
  real::arg(10)
  arg=1.0
  print *,'pass'
end program main
```

```
$ flang-new -fopenmp z1.f90
error: Semantic errors in z1.f90
./z1.f90:7:11: error: The DEFAULT(NONE) clause requires that 'aaa' must be listed in a data-sharing attribute clause
       ccc= aaa(ip)
            ^^^
$
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Do not error out if default(none) is specified and the region has an assumed-size array.

Fixes #110442

### CODE REVIEW

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -2047,6 +2047,7 @@ void OmpAttributeVisitor::Post(const parser::OpenMPAllocatorsConstruct &x) {
 static bool IsPrivatizable(const Symbol *sym) {
   auto *misc{sym->detailsIf<MiscDetails>()};
   return !IsProcedure(*sym) && !IsNamedConstant(*sym) &&
+      !semantics::IsAssumedSizeArray(*sym) && /*Assumed-size arrays are shared*/
```
Comment (mjklemm) [inline flang/lib/Semantics/resolve-directives.cpp:2050]:
```suggestion
      !semantics::IsAssumedSizeArray(*sym) && /* OpenMP 5.2, 5.1.1: Assumed-size arrays are shared */
```

**Review by mjklemm — APPROVED** [review]
LGTM

**Review by tblah — APPROVED** [review]
LGTM with Michael's suggestion

File: flang/lib/Semantics/resolve-directives.cpp (hunk 1 above)
Comment (kiranchandramohan) [reply flang/lib/Semantics/resolve-directives.cpp]: Thanks. Done.
