### PR TITLE
[clang-format] Skip PP directives when determining brace kind

### LINKED ISSUE #68404: clang-format-18 `ColumnLimit: 0` breaks formatting when encountering empty `#if 0 ... #endif` section
Given following `.clang-format` file:
```
ColumnLimit: 0
```
And following `foo.cpp` source file:
```
struct Foo {
  Foo() : a(2) {
#if 0
    // comment
#endif
  }

  Foo &operator+=(const Foo &) {
    return *this;
  }

  int a = 0;
};
```
I expect that ```clang-format-18 foo.cpp``` will not perform formatting (or at least not in a broken way), however, it does:
```
$ clang-format-18 foo.cpp 
struct Foo {
  Foo() : a(2){
#if 0
    // comment
#endif
          }

          Foo
          & operator+=(const Foo &) {
    return *this;
  }

  int a = 0;
};
```
After changing the value of `ColumnLimit: 0` to something like 80, the issue is no more. We can also add some code into the `#if 0` part, and `clang-format` will not perform formatting in broken way anymore with `ColumnLimit: 0`. 
`clang-format-18` version:
```
$ clang-format-18 --version
Ubuntu clang-format version 18.0.0 (++20230929042255+ab472cd4ea12-1~exp1~20230929042400.1214)
```

### PR DESCRIPTION
**Pull request by rymiel**
Pull request #65409 changed the brace kind heuristic to not treat a preprocessor if directive as a in statement, however, this caused some regressions.

If the contents of a brace don't immediately determine the brace kind, the heuristic will look at the characters immediately before and after the closing brace to determine the brace type.

Unfortunately, if the closing brace was preceded by a preprocessor directive, for example `#endif`, the preceding token was `endif`, seen as just an identifier, so the braces were understood as a braced list.

This patch fixes this behaviour by skipping all preprocessor directives when calculating brace types. Comments were already being skipped, so now preprocessor lines are skipped alongside comments.

Fixes https://github.com/llvm/llvm-project/issues/68404

### CODE REVIEW

**Comment by rymiel** [comment]
Here's my solution to the regression I caused (https://github.com/llvm/llvm-project/issues/68404), but I don't think it's a particularly nice solution
let me know what I should change (there's some code duplication that should probably be extracted out)

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 1]
```diff
@@ -491,11 +491,19 @@ void UnwrappedLineParser::calculateBraceTypes(bool ExpectClassBody) {
...
+           (NextTok->is(tok::hash) && isOnNewLine(*NextTok))) {
+      while (NextTok->is(tok::comment))
+        NextTok = Tokens->getNextToken();
+      while (NextTok->is(tok::hash) && isOnNewLine(*NextTok)) {
+        ScopedMacroState MacroState(*Line, Tokens, NextTok);
+        do {
+          NextTok = Tokens->getNextToken();
+        } while (NextTok->isNot(tok::eof));
+      }
+    }
```
Comment (owenca) [inline clang/lib/Format/UnwrappedLineParser.cpp:506]:
```suggestion
    while (NextTok->is(tok::hash)) {
      NextTok = Tokens->getNextToken();
      do {
        NextTok = Tokens->getNextToken();
      } while (NextTok->is(tok::comment) || (NextTok->NewlinesBefore == 0 &&
                                             NextTok->isNot(tok::eof)));
    } while(NextTok->is(tok::hash));
```
And keep the deleted lines (494-498).

I don't think we need to (or should) use `isOnNewLine()` as it might miss PPDirective lines started with block comments.

**Comment by owenca** [comment]
> Here's my solution to one of the regressions I caused (#68404)

I don't think it's a regression. On the contrary, it actually exposed another bug. :)

File: clang/lib/Format/UnwrappedLineParser.cpp (hunk 1 above)
Comment (rymiel) [reply clang/lib/Format/UnwrappedLineParser.cpp:506]: removing isOnNewLine causes test failures containing macro stringizing operators (which also uses `#`)

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:506]: Can you give a valid C/C++ example? As far as I know, you can't have `#` after `{`.

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:506]: Tested on the following case without `isOnNewLine()`:
```
struct Foo {
  Foo() : a(2) {
#define FOO(foo) \
  /* foo */ #foo
  }

  Foo &operator+=(const Foo &) {
    return *this;
  }
};
```
Also works if the comment is deleted.

Comment (rymiel) [reply clang/lib/Format/UnwrappedLineParser.cpp:506]: Ah, sorry, I missed the fact that you gave `NewlinesBefore` as the replacement to `isOnNewLine`, yes, that works better, thank you

**Review by owenca — APPROVED** [review]

**Comment by owenca** [comment]
@rymiel, please remove me from the authorship. I suggested code in numerous reviews and never expected to get co-authorship just because the authors took my suggestions. 😄

**Comment by rymiel** [comment]
I didn't expect you to not want to be credited, but I'll respect your opinion! GitHub adds co-ownership automatically if using the web ui to commit a suggestion (which is what happened in that other PR you pinged me in), but in this case I did add it manually :)

**Comment by owenca** [comment]
> I didn't expect you to not want to be credited, but I'll respect your opinion!

I meant you didn't need to add me to the authorship. 🙂 Anyway, I do appreciate it and think you should be the only author.

> GitHub adds co-ownership automatically if using the web ui to commit a suggestion (which is what happened in that other PR you pinged me in), but in this case I did add it manually :)

Ah, I didn't know that. Thanks for letting me know!

**Comment by owenca** [comment]
@rymiel can we merge this?

**Comment by rymiel** [comment]
Thank you for reminding me, I may have forgotten this was here!
