### PR TITLE
[AMDGPU]Optimize SGPR spills

### LINKED ISSUE #96353: [AMDGPU] StackSlotColoring before LowerSGPRSpill causes memfault in Blender 4.1 on gfx908
https://github.com/llvm/llvm-project/pull/93668 caused a regression in Blender 4.1 on gfx908 for all scenes.

```
Fra:48 Mem:1531.14M (Peak 1531.14M) | Time:06:58.63 | Mem:2448.05M, Peak:2448.05M | Scene, View Layer | Sample 0/256
Warning: precise memory violation signal reporting is not enabled, reported
location may not be accurate.  See "show amdgpu precise-memory".

Thread 103 "blender" received signal SIGSEGV, Segmentation fault.
[Switching to thread 103, lane 9 (AMDGPU Lane 1:1:1:1/9 (0,0,0)[9,0,0])]
0x00007ffd7689a68c in integrator_intersect_shadow(KernelGlobalsGPU const*, int) () from memory://192866#offset=0x7ffd77f01240&size=4555968
```

### PR DESCRIPTION
**Pull request by vg0204**
This PR is dependent on [#93779](https://github.com/llvm/llvm-project/pull/93779).

As currently, each SGPR Spills are lowered to go into distinct stack slots in stack frame after SGPR allocation phase. Therefore, this patch utilizes the capability of StackSlotColoring to ensure the stack slot sharing if possible for stack frame index, where the SGPR spills are occuring in the non-interfering region.

StackSlotColoring is introduced immediately after SGPR register allocation, just to ensure that any further lowering happens on the optimally allocated stack slots, with certain flags to indicate the preservation of certain analysis result later to be used by RA of other register classes.

### CODE REVIEW

File: llvm/lib/CodeGen/StackSlotColoring.cpp [hunk 1]
```diff
@@ -67,6 +67,9 @@ namespace {
     const MachineBlockFrequencyInfo *MBFI = nullptr;
     SlotIndexes *Indexes = nullptr;
 
+    // - preserves Analysis passes in case RA may be called afterwards.
+    bool preserveRegAllocNeededAnalysis = false;
```
Comment (arsenm) [inline llvm/lib/CodeGen/StackSlotColoring.cpp:71]: There shouldn't be a reason to have a configuration flag for this. The pass can just unconditionally preserve the analyses.

This should also be a separate PR, not just a separate commit in this PR

File: llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-alloc-equal-size-stack-objects.mir [hunk 2]
```diff
@@ -0,0 +1,127 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
+# RUN: llc -mtriple=amdgcn-amd-amdhsa -verify-machineinstrs -stress-regalloc=3 -start-before=greedy -stop-before=prologepilog -o - %s | FileCheck -check-prefix=SHARE %s
```
Comment (cdevadas) [inline llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-alloc-equal-size-stack-objects.mir:2]: -mcpu missing. in all new tests.
Since the RUN lines are the same combine all 3 tests into a single .mir file.

**Review by cdevadas — COMMENTED** [review]
Yes, the generic changes should go in a separate patch.

File: llvm/lib/CodeGen/StackSlotColoring.cpp (hunk 1 above)
Comment (vg0204) [reply llvm/lib/CodeGen/StackSlotColoring.cpp:71]: > There shouldn't be a reason to have a configuration flag for this. The pass can just unconditionally preserve the analyses.
> 
> This should also be a separate PR, not just a separate commit in this PR

ok sure, I should put changes in generic pass as separate PR.

But, as the same stackSlotColoring pass exists in generic way(after RA) for other Target's pipeline where these analysis are not really required to be preserved. As in this case, it just got additionally called in between AMDGPU target pipeline(where addtional analysis needs to be preserved). Therefore, got suggested to introduce this flag to avoid avoid any changes for other architecture's pipeline( maybe caused due to additional pass preserving in stackSlotColoring).

File: llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-alloc-equal-size-stack-objects.mir (hunk 2 above)
Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-alloc-equal-size-stack-objects.mir:2]: > -mcpu missing. in all new tests. Since the RUN lines are the same combine all 3 tests into a single .mir file.

Can you enlighten me on what cpu to mention, as I am not sure exactly how to decide on.

Also, kindly comment on the configuration flag related changes.

File: llvm/lib/CodeGen/StackSlotColoring.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/CodeGen/StackSlotColoring.cpp:71]: Preserved does not mean required. Make them unconditionally preserved

**Comment by jayfoad** [comment]
> [AMDGPU] Implemented a patch to optimize SGPR spills

Please keep subject lines concise. "Implemented a patch" just wastes words. If you remove that part then you can explain a little bit more about the optimization.

**Comment by vg0204** [comment]
> > [AMDGPU] Implemented a patch to optimize SGPR spills
> 
> Please keep subject lines concise. "Implemented a patch" just wastes words. If you remove that part then you can explain a little bit more about the optimization.

Point Noted!

File: llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp [hunk 3]
```diff
@@ -1406,6 +1406,12 @@ bool GCNPassConfig::addRegAssignAndRewriteOptimized() {
   // since FastRegAlloc does the replacements itself.
   addPass(createVirtRegRewriter(false));
 
+  // As by this point SGPR's RA is done introducing SGPR spills to stack frame
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp:1409]:
```suggestion
  // As by this point SGPR's RA is done introducing SGPR spills to stack frame
  // through SGPRAllocPass. So, invoking StackSlotColoring here, may allow these
  // SGPR spills to re-use stack slots, before these spills is further lowered
  // down via SILowerSGPRSpills(i.e. equivalent of PEI for SGPRs).
```
 // At this point, the sgpr-regalloc has been done and it is good to have the stack
  // slot coloring to try to optimize the SGPR spill stack indices before attempting
  // the custom SGPR spill lowering.

File: llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp [hunk 4]
```diff
@@ -278,15 +278,16 @@ void SILowerSGPRSpills::extendWWMVirtRegLiveness(MachineFunction &MF,
   for (auto Reg : MFI->getSGPRSpillVGPRs()) {
     for (MachineBasicBlock *SaveBlock : SaveBlocks) {
       MachineBasicBlock::iterator InsertBefore = SaveBlock->begin();
+
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp:281]: Extra new line.

File: llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp [hunk 5]
```diff
@@ -278,15 +278,16 @@ void SILowerSGPRSpills::extendWWMVirtRegLiveness(MachineFunction &MF,
...
       DebugLoc DL = SaveBlock->findDebugLoc(InsertBefore);
       auto MIB = BuildMI(*SaveBlock, InsertBefore, DL,
                          TII->get(AMDGPU::IMPLICIT_DEF), Reg);
       MFI->setFlag(Reg, AMDGPU::VirtRegFlag::WWM_REG);
       // Set SGPR_SPILL asm printer flag
       MIB->setAsmPrinterFlag(AMDGPU::SGPR_SPILL);
-      if (LIS) {
+
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp:288]: Ditto.

File: llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp [hunk 6]
```diff
@@ -300,6 +301,7 @@ void SILowerSGPRSpills::extendWWMVirtRegLiveness(MachineFunction &MF,
       auto MIB = BuildMI(*RestoreBlock, InsertBefore, DL,
                          TII->get(TargetOpcode::KILL));
       MIB.addReg(Reg);
+
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SILowerSGPRSpills.cpp:304]: Ditto.

File: llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir [hunk 7]
```diff
@@ -0,0 +1,353 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
```
Comment (cdevadas) [inline llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir:1]: Should precommit the test. But I'm not sure this test currently does anything significant to the slot optimization.
Add another run line to show the output after stack-slot-coloring as well to see the effect of this pass.
Should add a short description at each test what it meant for?
I don't see the slot-indices being shared for the SGPR spills.

**Review by cdevadas — COMMENTED** [review]
This patch needs a pre-commit PSDB test.

File: llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll [hunk 8]
```diff
@@ -10098,7 +10098,7 @@ define amdgpu_kernel void @test_limited_sgpr(ptr addrspace(1) %out, ptr addrspac
 ; GFX6-NEXT:    s_mov_b64 s[4:5], s[2:3]
 ; GFX6-NEXT:    v_lshlrev_b32_e32 v5, 8, v0
 ; GFX6-NEXT:    buffer_load_dwordx4 v[0:3], v[5:6], s[4:7], 0 addr64 offset:240
-; GFX6-NEXT:    s_mov_b32 s2, 0x84400
+; GFX6-NEXT:    s_mov_b32 s2, 0x86a00
```
Comment (cdevadas) [inline llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll:10101]: Apart from the offset change, I don't see any difference in this test. Can you see why the offset is high?

File: llvm/include/llvm/CodeGen/Passes.h [hunk 9]
```diff
@@ -283,7 +283,7 @@ namespace llvm {
   /// critical-path and resource depth.
   extern char &MachineCombinerID;
 
-  /// StackSlotColoring - This pass performs stack coloring and merging.
+  /// StackColoring - This pass performs stack coloring and merging.
```
[the remark this answers is not in the document]
Comment (vg0204) [reply llvm/include/llvm/CodeGen/Passes.h:286]: > Why this change?

Need to get rid of it!

File: llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll (hunk 8 above)
Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll:10101]: I found it. As when you call StackSlotColoring pass eventhough no stack slot usage is done, it also effectively re-assigns the FI to allocated stack slot. As a result, during PEI when actual offset is assigned they also differ. In this patch, the additional invocation of StackSlotColoring pass before SILowerSGPRSpills is just doing re-assignment of FI (with no effective slot re-usage) resulting in different offset assignment. But in overall, no change in stack memory usage (as no scope found for this optimization in this example).

File: llvm/include/llvm/CodeGen/Passes.h [hunk 10]
```diff
@@ -283,7 +283,7 @@ namespace llvm {
   /// critical-path and resource depth.
   extern char &MachineCombinerID;
 
-  /// StackColoring - This pass performs stack coloring and merging.
+  /// StackSlotColoring - This pass performs stack coloring and merging.
```
Comment (jayfoad) [inline llvm/include/llvm/CodeGen/Passes.h:286]: Remove this. StackColoring and StackSlotColoring are two different passes.

Comment (jayfoad) [reply llvm/include/llvm/CodeGen/Passes.h:286]: Sorry I think I was commenting on an old version of your patch.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp [hunk 11]
```diff
@@ -1775,8 +1775,10 @@ bool SIRegisterInfo::spillSGPR(MachineBasicBlock::iterator MI, int Index,
 
   if (SpillToVGPR) {
 
-    assert(SB.NumSubRegs == VGPRSpills.size() &&
-           "Num of VGPR lanes should be equal to num of SGPRs spilled");
+    assert(SB.NumSubRegs <= VGPRSpills.size() &&
+           "Num of VGPR lanes should be greater or equal to num of SGPRs "
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp:1779]: Keep this string as concise as possible. Any extra details you want to add should be included in a comment statement before the assert. The original string looks good. You might want to change "should be equal to" -> "should be less or equal to".

File: llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll (hunk 8 above)
Comment (cdevadas) [reply llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll:10101]: I believe, there is only the offset difference. The final stack consumption remains the same as earlier for the function.

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/spill-scavenge-offset.ll:10101]: > I believe, there is only the offset difference. The final stack consumption remains the same as earlier for the function.

Yes

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp (hunk 11 above)
Comment (vg0204) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp:1779]: I think that number of VGPR lanes corresponds to spill slot size(equal to largest spill stack object residing in it) which should be equal to or greater than number of SGPR spills created which corresponds to the spill stack object size.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp [hunk 12]
```diff
@@ -1775,10 +1775,13 @@ bool SIRegisterInfo::spillSGPR(MachineBasicBlock::iterator MI, int Index,
 
   if (SpillToVGPR) {
 
+    // Since stack slot coloring pass is trying to optimize SGPR spills,
+    // VGPR lanes (mapped from spill stack slot) may be shared for unequal SGPR
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp:1779]: Change unequal SGPR spills into SGPR spills of different sizes.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp [hunk 13]
```diff
@@ -1775,10 +1775,13 @@ bool SIRegisterInfo::spillSGPR(MachineBasicBlock::iterator MI, int Index,
...
+    // spills. This accounts for number of VGPR lanes alloted equal to the
+    // largest SGPR being spilled in them.
     assert(SB.NumSubRegs <= VGPRSpills.size() &&
-           "Num of VGPR lanes should be greater or equal to num of SGPRs "
-           "spilled, as Stack Slot Coloring pass assigns different SGPR spills "
-           "into same stack slots");
+           "Num of VGPR lanes mapped should be greater or equal to num of "
```
Comment (cdevadas) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp:1783]: I guess it is more appropriate to use 'shouldn't be less than' instead of 'should be greater or equal'

**Review by cdevadas — COMMENTED** [review]
The new test llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir needs to be written precisely to show the stack indices being shared. See my previous comments.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp (hunk 13 above)
Comment (vg0204) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp:1783]: > I guess it is more appropriate to use 'shouldn't be less than' instead of 'should be greater or equal'

Then should I reverse the assert statement, so that 'shouldn't be less than' can be used?

**Comment by vg0204** [comment]
> The new test llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir needs to be written precisely to show the stack indices being shared. See my previous comments.

While going through it, I found a problem in test case output, need to reassess my changes in PR, currently working on it.

**Comment by vg0204** [comment]
> > The new test llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir needs to be written precisely to show the stack indices being shared. See my previous comments.
> 
> While going through it, I found a problem in test case output, need to reassess my changes in PR, currently working on it.

Everything is alright! no changes is needed

File: llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir (hunk 7 above)
Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/stack-slot-color-after-sgpr-regalloc.mir:1]: I believe I added the RUN command for both BEFORE & AFTER stack slot coloring pass (the one invoked just after sgpr regAlloc), & stack indices re-usage can be seen.

File: llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir [hunk 14]
```diff
@@ -0,0 +1,295 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
+# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -verify-machineinstrs -stress-regalloc=3 -start-before=greedy -stop-after=stack-slot-coloring -o - %s | FileCheck -check-prefix=CHECK %s
```
Comment (cdevadas) [inline llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir:2]: Should use a different check-prefix instead of the default CHECK. May be STACK-SLOT-OPT?

Comment (cdevadas) [reply llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir:2]: There are now two instances of stack-slot-coloring in our pipeline. You're interested in the first invocation.  Better specify it with the index too, like -stop-after=stack-slot-coloring,0. The index zero here is meant for stopping after the first instance.

File: llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir [hunk 15]
```diff
@@ -0,0 +1,295 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
```
Comment (cdevadas) [inline llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir:1]: Test filename can be optimize-vgpr-lanes-for-sgpr-spills.mir?

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/si-lower-sgpr-spills-vgpr-lanes-usage.mir:1]: But, I think this filename is as good after patch is included, here it is not done yet, right?

File: llvm/test/CodeGen/AMDGPU/llc-pipeline.ll [hunk 16]
```diff
@@ -362,10 +362,12 @@
 ; GCN-O1-NEXT:        Machine Optimization Remark Emitter
 ; GCN-O1-NEXT:        Greedy Register Allocator
 ; GCN-O1-NEXT:        Virtual Register Rewriter
+; GCN-O1-NEXT:        Stack Slot Coloring
 ; GCN-O1-NEXT:        SI lower SGPR spill instructions
 ; GCN-O1-NEXT:        Virtual Register Map
 ; GCN-O1-NEXT:        Live Register Matrix
 ; GCN-O1-NEXT:        SI Pre-allocate WWM Registers
+; GCN-O1-NEXT:        Live Stack Slot Analysis
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: Can we keep this preserved in the previous passes?

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: I tried this & found that as StackSlotColoring pass is not currently updating LiveStacks(LS) analysis, eventhough modifying the stack slots usage (as before it is being invoked only after complete RA when all spills happened just before PEI, so LS not needed anymore), so LS results are invalidated rather preserved. But, now LS is being needed by RA (for remaining register class) later, so LS analysis appears later as being re-calculated.

Comment (arsenm) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: Right, can the pass be updated so that it can be preserved?

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: Need to look into it, but I cannot say how much changes might it take. Also, as the same LiveStack(LS) would be propagated into RA pass later for entring additional entries, RA might have some side effects while working on presereved LS. Considering all this, this updates might take big significant effort, followed by rigourous tests, so nothing else breaks.

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: @arsenm, after spending some time & tinkering around, I figured it out! Let me know so the Stack Slot Coloring should preserve LiveStack analysis?

Comment (arsenm) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: Yes, open a follow up PR to do that

Comment (vg0204) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: As there already exists a PR #93779, which deals with preserving additional analysis to be later used by RA passes, can I incorporate these changes there OR open a new follow-up PR?

Comment (arsenm) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:370]: You should nearly always break it into the smallest possible separable pieces

**Review by arsenm — APPROVED** [review]

**Review by cdevadas — APPROVED** [review]
You don't have to wait for every reviewer to approve the patch unless one of the reviewers mentions it.

**Comment by jplehr** [comment]
Hi, I believe this turned one of our buildbots red: https://lab.llvm.org/buildbot/#/builders/123/builds/253
If you require assistance in reproducing, let me know and I'll see if I can be of help.

**Comment by vg0204** [comment]
> Hi, I believe this turned one of our buildbots red: https://lab.llvm.org/buildbot/#/builders/123/builds/253 If you require assistance in reproducing, let me know and I'll see if I can be of help.

Yeah, that would be great!

**Comment by yxsamliu** [comment]
> > Hi, I believe this turned one of our buildbots red: https://lab.llvm.org/buildbot/#/builders/123/builds/253 If you require assistance in reproducing, let me know and I'll see if I can be of help.
> 
> Yeah, that would be great!

I can confirm that this PR caused regression in blender test of buildbot:

```
Fra:48 Mem:1531.14M (Peak 1531.14M) | Time:06:58.63 | Mem:2448.05M, Peak:2448.05M | Scene, View Layer | Sample 0/256
Warning: precise memory violation signal reporting is not enabled, reported
location may not be accurate.  See "show amdgpu precise-memory".

Thread 103 "blender" received signal SIGSEGV, Segmentation fault.
[Switching to thread 103, lane 9 (AMDGPU Lane 1:1:1:1/9 (0,0,0)[9,0,0])]
0x00007ffd7689a68c in integrator_intersect_shadow(KernelGlobalsGPU const*, int) () from memory://192866#offset=0x7ffd77f01240&size=4555968
```

Currently the buildbot has disabled all Blender test scenes so it is apparently green, but we'd get this fixed ASAP since this commit may get to amd-staging branch and cause other regressions.

debugger shows memfault happens at the highlighted line:

Capture

the real instruction causing memfault is most likely the `buffer_load_dword` right above it, where `s[0:3]` contains unreasonably large values.

**Comment by yxsamliu** [comment]
[kernel-hip-amdgcn-amd-amdhsa-gfx908.zip](https://github.com/user-attachments/files/15905813/kernel-hip-amdgcn-amd-amdhsa-gfx908.zip)

To accurately reproduce the assembly file, use the following clang command:

```
clang -cc1 -mcode-object-version=4 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -S -disable-free -mrelocation-model pic -pic-level 2 -mframe-pointer=none -aux-target-cpu x86-64 -mllvm -amdgpu-internalize-symbols -target-cpu gfx908 -O3 -vectorize-loops -vectorize-slp -faddrsig -o tmp.s -x ir kernel-hip-amdgcn-amd-amdhsa-gfx908.bc
```

**Comment by vg0204** [comment]
> [kernel-hip-amdgcn-amd-amdhsa-gfx908.zip](https://github.com/user-attachments/files/15905813/kernel-hip-amdgcn-amd-amdhsa-gfx908.zip)
> 
> To accurately reproduce the assembly file, use the following clang command:
> 
> ```
> clang -cc1 -mcode-object-version=4 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -S -disable-free -mrelocation-model pic -pic-level 2 -mframe-pointer=none -aux-target-cpu x86-64 -mllvm -amdgpu-internalize-symbols -target-cpu gfx908 -O3 -vectorize-loops -vectorize-slp -faddrsig -o tmp.s -x ir kernel-hip-amdgcn-amd-amdhsa-gfx908.bc
> ```

Getting this while trying to reproduce.

dumpError

**Comment by arsenm** [comment]
> > [kernel-hip-amdgcn-amd-amdhsa-gfx908.zip](https://github.com/user-attachments/files/15905813/kernel-hip-amdgcn-amd-amdhsa-gfx908.zip)
> 
> > 
> 
> > To accurately reproduce the assembly file, use the following clang command:
> 
> > 
> 
> > ```
> 
> > clang -cc1 -mcode-object-version=4 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -S -disable-free -mrelocation-model pic -pic-level 2 -mframe-pointer=none -aux-target-cpu x86-64 -mllvm -amdgpu-internalize-symbols -target-cpu gfx908 -O3 -vectorize-loops -vectorize-slp -faddrsig -o tmp.s -x ir kernel-hip-amdgcn-amd-amdhsa-gfx908.bc
> 
> > ```
> 
> 
> 
> Getting this while trying to reproduce.
> 
> 
> 
> dumpError
> 
> 

This is due to mixing upstream and amd-staging with the different debug info

**Comment by arsenm** [comment]
> Can you please elaborate?


See https://github.com/llvm/llvm-project/issues/56194

**Comment by yxsamliu** [comment]
let me try getting a bitcode without debug info

**Comment by yxsamliu** [comment]
[res.new.zip](https://github.com/user-attachments/files/15914966/res.new.zip)
bc and assembly without debug info are attached. pls use 4b9112e88a998ce620e4683548f2afd17cc5fe95 clang and the above mentioned command to get assembly and compare with the attached one to make sure they are the same.

**Comment by vg0204** [comment]
Also, I do noat have any clue how to proceed with this bitcode & assembly files provided by you @yxsamliu , to help in fixing the blender test caused by the commit. So if you could help me out in that, it would be great!

**Comment by yxsamliu** [comment]
the idea is to locate the buffer_load_dword in  integrator_intersect_shadow which has invalid s[0:3] in the bad case and locate the counter part in the good case. By comparing the ISA, find the def of s[0:3] or chase further to find the instruction that causes invalid def of s[0:3]. Then find the invalid transformation that causes that instruction by focusing on how each pass transform that instruction.

If the ISA of integrator_intersect_shadow is too different in the bad/good cases we can force noinline for callees of integrator_intersect_shadow in the hope of narrow down the issue in its callees. We may also consider other ways to minimize the difference between the bad/good cases, e.g. adding some counter or threshold in the newly added pass to control the number of changes it makes to pinpoint the minimal change that causes pass/fail.

**Comment by yxsamliu** [comment]
Can we temporarily revert this patch while we investigate the regression? Thanks.

**Comment by cdevadas** [comment]
> Can we temporarily revert this patch while we investigate the regression? Thanks.

Yes, revert it to unblock the blender testing.

**Comment by vg0204** [comment]
> the idea is to locate the buffer_load_dword in integrator_intersect_shadow which has invalid s[0:3] in the bad case and locate the counter part in the good case. By comparing the ISA, find the def of s[0:3] or chase further to find the instruction that causes invalid def of s[0:3]. Then find the invalid transformation that causes that instruction by focusing on how each pass transform that instruction.
> 
> If the ISA of integrator_intersect_shadow is too different in the bad/good cases we can force noinline for callees of integrator_intersect_shadow in the hope of narrow down the issue in its callees. We may also consider other ways to minimize the difference between the bad/good cases, e.g. adding some counter or threshold in the newly added pass to control the number of changes it makes to pinpoint the minimal change that causes pass/fail.

Thank you Sam for this heads up!

File: llvm/test/CodeGen/AMDGPU/llc-pipeline.ll (hunk 16 above)
Comment (jayfoad) [reply llvm/test/CodeGen/AMDGPU/llc-pipeline.ll:374]: @vg0204 ping: are you planning to make StackSlotColoring preserve LiveStacks, or is there some reason it is hard to do?
