### PR TITLE
[PowerPC] fix lowering of SPILL_CRBIT on pwr9 and pwr10

### LINKED ISSUE #143989: powerpc64le: power9 codgen bug when generating setb instructions
The rust frontend ran into a bug when running tests on ppc64le with pgo enabled on [centos](https://kojihub.stream.centos.org/kojifiles/vol/koji02/packages/rust/1.86.0/1.el10/data/logs/ppc64le/build.log). The compilation of the compiler's `rustc_errors` crate with `-mcpu=power9` created a bug where a boolean value is clobbered, resulting in incorrect json values.

I was able to extract the llvm input from rust, and run `llvm-reduce` to produce a reasonably sized reproducer using the upstream llvm repo. 

The following codegen is suspect:
```
        andi. 3, 4, 1
        setb 3, 2
        cmpldi  4, 0
        std 28, 80(1)                           # 8-byte Folded Spill
        stw 3, 60(1)
```
Notably, `cr2` in the `setb` above has no live value (I am assuming this is following the ELFv2 ABI).

After the `machine-cp` pass, a copy from `cr0gt` to `cr2lt` goes missing. Likewise, the other bits of `cr2` appear to be undefined. Furthermore, `setb` potentially examines all bits of the input `cr`, so moving one bit is not sufficient for well-defined behavior.

Attached is the reduced llvm input [reduced.ll.txt](https://github.com/user-attachments/files/20717223/reduced.ll.txt). Likewise, I assembled it via:
```
llc -march=ppc64le -mcpu=pwr9 reduced.ll.txt
```

### PR DESCRIPTION
**Pull request by pmur**
If a copy exists between creation of a crbit and a spill, machine-cp
may delete the copy since it seems unaware of the relation between a cr
and crbit. A fix was previously made for the generic ppc64 lowering. It
should be applied to the pwr9 and pwr10 variants too.

Likewise, relax and extend the pwr8 test to verify pwr9 and pwr10
codegen too.

This fixes #143989.

### CODE REVIEW

**Comment by nikic** [comment]
For reference, the fix for the generic case was https://github.com/llvm/llvm-project/commit/3c7ac649ecc244a342c1374ff0d7931c6da54961.

**Review by lei137 — COMMENTED** [review]
Thank-you for the fix.  
To prevent the same mistake from happening again when new CRbit spilling is added in the future, please move the "general" statement for this behaviour documented on lines 1137-1141 to the top of this "default:" block so new code added will take this into account.

**Comment by pmur** [comment]
Ping

File: llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp [hunk 1]
```diff
@@ -1102,13 +1102,20 @@ void PPCRegisterInfo::lowerCRBitSpilling(MachineBasicBlock::iterator II,
     SpillsKnownBit = true;
     break;
   default:
+    // When spilling a CR bit, The super register may not be explicitly defined
```
Comment (amy-kwan) [inline llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp:1105]:
```suggestion
    // When spilling a CR bit, the super register may not be explicitly defined
```
Minor nit on the comment.

**Review by amy-kwan — APPROVED** [review]
Thank you for the fix. I think this LGTM.

File: llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp (hunk 1 above)
Comment (pmur) [reply llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp]: Fixed, thanks.
