### PR TITLE
[flang] add nsw to operations in subscripts

### LINKED ISSUE #78934: [Flang] TSVC s243: some `nsw` flags for address calculations will help vectorization
Flang can't vectorize the loop in `s243` of [TSVC](https://www.netlib.org/benchmark/vectors) while Clang can vectorize the loop written in C.

```fortran
! Fortran version
      module mod
      integer ld, nloops
      parameter (ld=1000,nloops=135)
      real a(ld), b(ld), c(ld), d(ld), e(ld)
      real aa(ld,ld), bb(ld,ld), cc(ld,ld)
      interface
      subroutine dummy(ld,n,a,b,c,d,e,aa,bb,cc,x)
         integer ld, n
         real a(ld), b(ld), c(ld), d(ld), e(ld)
         real aa(ld,ld), bb(ld,ld), cc(ld,ld)
         real, value :: x
      end subroutine
      end interface
      end module

      subroutine s243 (n)
      use mod
      integer n, i

      call init(ld,n,a,b,c,d,e,aa,bb,cc,'s243 ')
      do 10 i = 1,n-1
         a(i) = b(i) + c(i)   * d(i)
         b(i) = a(i) + d(i)   * e(i)
         a(i) = b(i) + a(i+1) * d(i)
  10  continue
      call dummy(ld,n,a,b,c,d,e,aa,bb,cc,1.)
      end
```

```c
// C version
#define LEN 32000
#define LEN2 256
float a[LEN], b[LEN], c[LEN], d[LEN], e[LEN];
float aa[LEN2][LEN2], bb[LEN2][LEN2], cc[LEN2][LEN2];

int s243() {
  init( "s243 ");
  for (int i = 0; i < LEN-1; i++) {
    a[i] = b[i] + c[i  ] * d[i];
    b[i] = a[i] + d[i  ] * e[i];
    a[i] = b[i] + a[i+1] * d[i];
  }
  dummy(a, b, c, d, e, aa, bb, cc, 0.);
  return 0;
}
```

```console
$ flang-new -v -Ofast s243.f -S -Rpass=vector
flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git 0e93d04001e45f39cabf0ffb5093512a7f622cc0)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
Found candidate GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Selected GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -S -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -ffast-math -target-cpu generic -target-feature +neon -target-feature +v8a -fstack-arrays -fversion-loops-for-stride -Rpass=vector -O3 -o s243.s -x f95-cpp-input s243.f
$ clang -Ofast s243.c -S -Rpass=vector
s243.c:15:3: remark: vectorized loop (vectorization width: 4, interleaved count: 1) [-Rpass=loop-vectorize]
   15 |                 for (int i = 0; i < LEN-1; i++) {
      |                 ^
```

The Fortran code isn't vectorized because DSE doesn't remove the first store to `a(i)`.
DSE uses BasicAA, and BasicAA can't say that `a(i)` and `a(i+1)` don't alias each other. So DSE doesn't work.

Actually, Flang generates LLVM IR like the following C code that makes alias analysis harder.
(FYI: BasicAA avoids complicated analyses which can affect the compilation time.)

```c
for (int i = 1; i <= n-1; i++) {
  a[i-1] = b[i-1] + c[i-1] * d[i-1];
  b[i-1] = a[i-1] + d[i-1] * e[i-1];
  a[i-1] = b[i-1] + a[i] * d[i-1];
}
```

Conversely, the following Fortran code is easy to be vectorized.

```fortran
      do 10 i = 0,n-2
         a(i+1) = b(i+1) + c(i+1) * d(i+1)
         b(i+1) = a(i+1) + d(i+1) * e(i+1)
         a(i+1) = b(i+1) + a(i+2) * d(i+1)
  10  continue
```

```console
$ flang-new -Ofast s243_2.f -S -Rpass=vector
path/to/s243_2.f:14:7: remark: vectorized loop (vectorization width: 4, interleaved count: 1) [-Rpass=loop-vectorize]
```

### PR DESCRIPTION
**Pull request by yus3710-fj**
This patch adds nsw to operations when lowering subscripts.

See also the discussion in the following discourse post.
https://discourse.llvm.org/t/rfc-add-nsw-flags-to-arithmetic-integer-operations-using-the-option-fno-wrapv/77584/9

### CODE REVIEW

File: flang/test/Lower/HLFIR/vector-subscript-as-value.f90 [hunk 1]
```diff
@@ -150,6 +151,45 @@ subroutine foo4(at1, vector, i, j, k, l, step)
 ! CHECK:    hlfir.yield_element %[[VAL_50]] : f32
 ! CHECK:  }
 
+subroutine foo5(x, y, z)
+  integer :: x(100)
+  integer(8) :: y(20), z(20)
+  call bar(x(y+z))
+end subroutine
+! CHECK-LABEL:   func.func @_QPfoo5(
```
Comment (jeanPerier) [inline flang/test/Lower/HLFIR/vector-subscript-as-value.f90:159]: If the goal of the test is to show that overflow<nsw> is no generated here, I think it is simpler and more expressive to just go for:

```
! Test that -fwrapv does not add <nsw> flag to arith ops on vector subscripts.
! CHECK-LABEL: func.func @_QPfoo5(
! CHECK-NOT: overflow<nsw>
! CHECK: return
```

File: flang/test/Lower/Intrinsics/bge.f90 [hunk 2]
```diff
@@ -156,3 +156,20 @@ subroutine bge_test11(c)
   ! CHECK: %[[V:.*]] = fir.convert %[[R]] : (i1) -> !fir.logical<4>
   ! CHECK: fir.store %[[V]] to %[[C]] : !fir.ref<!fir.logical<4>>
 end subroutine bge_test11
+
+! CHECK-LABEL: bge_test12
```
Comment (jeanPerier) [inline flang/test/Lower/Intrinsics/bge.f90:160]: Nit: don't you need to add the -fwrap flag to the RUN line for test to be relevant?

Also, to avoid updating the legacy lowering code just for the tests. I would advise adding all the new tests in a new `test/Lower/frwap-option.f90` file run with HFLIR.

I think you can use CHECK-NOT here to too make the tests smaller.

**Review by jeanPerier — COMMENTED** [review]
Thank you very much for taking the time to build this carefully crafted solution.

I am wondering if it would be OK to do like for the fastmath flags inside the builder directly [here](https://github.com/llvm/llvm-project/blob/57bed5cd63b5d23ca821be09b4e593646cd84146/flang/include/flang/Optimizer/Builder/FIRBuilder.h#L79) using the `ArithIntegerOverflowFlagsInterface` so that this solution would easily usable in other contexts in the future and better enclosed in the builder.

But it would add the flags on more arith ops generated by lowering outside of the contexts of evaluate::AddIOp, SubIOp, and MulIOp lowering. I would tend to say these compiler generated ops in lowering are not expected to overflow, but it is hard to audit,  so I understand why you took the current approach which is more conservative. I am mostly writing that here to double check with other reviewers and document the choice for git blamers like me.

File: flang/test/Lower/HLFIR/vector-subscript-as-value.f90 (hunk 1 above)
Comment (yus3710-fj) [reply flang/test/Lower/HLFIR/vector-subscript-as-value.f90:159]: Thank you for showing me a better way. I'll modify it.

File: flang/test/Lower/Intrinsics/bge.f90 (hunk 2 above)
Comment (yus3710-fj) [reply flang/test/Lower/Intrinsics/bge.f90:160]: Thank you for your advice. I'll create another test file and add `-fwrapv` to the `RUN` command.

File: flang/test/Lower/array.f90 [hunk 3]
```diff
@@ -1,4 +1,5 @@
 ! RUN: bbc -hlfir=false -o - %s | FileCheck %s
+! RUN: bbc -hlfir=false -fwrapv -o - %s | FileCheck %s --check-prefix=NO-NSW
```
[the remark this answers is not in the document]
Comment (yus3710-fj) [reply flang/test/Lower/array.f90:2]: I'd just like to confirm what you mean.
`nsw` is also added to operations when HLFIR lowering is disabled, and I added some tests for that. Do you mean only the tests are unnecessary, or the implementation for non HLFIR is also unnecessary?

[the remark this answers is not in the document]
Comment (yus3710-fj) [reply flang/test/Lower/array.f90]: Thank you for your reply. I fixed it.

**Review by jeanPerier — APPROVED** [review]
Thanks!

**Review by tblah — COMMENTED** [review]
The changes look good in themselves but I wonder if this would be better in `fir::FirOpBuilder::setCommonAttributes` so that it is done on all new eligible operations instead of only in lowering.

**Comment by yus3710-fj** [comment]
Thank you for pointing it out. I fixed it.

**Review by tblah — APPROVED** [review]
Thanks for the update. LGTM

**Comment by yus3710-fj** [comment]
Rebased.
