### PR TITLE
[clang-tidy] add default error message for performance-avoid-endl

### LINKED ISSUE #107859: [clang-tidy] Broken diagnostic for performance-avoid-endl
When I run `clang-tidy -checks='-*,performance-avoid-endl'` on the following code

```
#include <iostream>

#define COUT_ENDL std::cout << std::endl

void foo()
{
  COUT_ENDL;
}
```

I get the message

```
bug.cc:7:3: warning: do not use '' with streams; use '\n' instead [performance-avoid-endl]
   11 |   COUT_ENDL;
      |   ^
bug.cc:3:32: note: expanded from macro 'COUT_ENDL'
    7 | #define COUT_ENDL std::cout << std::endl
      |                                ^
```

which is slightly broken (note the empty `''` in the first line).

### PR DESCRIPTION
**Pull request by HerrCai0907**
use ::std::endl as default message when matched expr does not have valid source text

Fixes: #107859

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp [hunk 1]
```diff
@@ -225,3 +225,14 @@ void bad_custom_stream() {
   // CHECK-MESSAGES: :[[@LINE-1]]:13: warning: do not use 'std::endl' with streams; use '\n' instead [performance-avoid-endl]
   // CHECK-FIXES: logger << '\n';
 }
+
+namespace gh107859 {
+
+#define ENDL std::endl;
+
+void bad_macro() {
+  std::cout << ENDL;
```
Comment (SimplyDanny) [inline clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:234]: Is `CHECK-FIXES` intentionally not checked?

File: clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp [hunk 2]
```diff
@@ -225,3 +225,14 @@ void bad_custom_stream() {
...
+  // CHECK-MESSAGES: :[[@LINE-1]]:16: warning: do not use '::std::endl' with streams; use '\n' instead [performance-avoid-endl]
```
Comment (SimplyDanny) [inline clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:235]:
```suggestion
  // CHECK-MESSAGES: :[[@LINE-1]]:16: warning: do not use 'std::endl' with streams; use '\n' instead [performance-avoid-endl]
```

This'd be more in line with the reported name in case the source text is available.

File: clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp (hunk 1 above)
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:234]: it doesn't have auto fixes

File: clang-tools-extra/clang-tidy/performance/AvoidEndlCheck.cpp [hunk 3]
```diff
@@ -46,14 +46,13 @@ void AvoidEndlCheck::check(const MatchFinder::MatchResult &Result) {
...
+    StringRef SourceText = Lexer::getSourceText(
         TokenRange, *Result.SourceManager, Result.Context->getLangOpts());
-
-    auto Diag = diag(Expression->getBeginLoc(),
-                     "do not use '%0' with streams; use '\\n' instead")
-                << SourceText;
-
-    Diag << FixItHint::CreateReplacement(TokenRange, "'\\n'");
+    if (SourceText.empty())
+      SourceText = "::std::endl";
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/performance/AvoidEndlCheck.cpp:52]:
```suggestion
      SourceText = "std::endl";
```

File: clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp (hunk 2 above)
Comment (HerrCai0907) [inline clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:235]:
```suggestion
  // CHECK-MESSAGES: :[[@LINE-1]]:16: warning: do not use 'std::endl' with streams; use '\n' instead [performance-avoid-endl]
```

File: clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp (hunk 1 above)
Comment (SimplyDanny) [reply clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:234]: But a replacement is always added, isn't it? What am I missing?

Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:234]: I am also confused. since I don't find auto fixes even replacement is emitted.
Maybe it is due to invalid location.
Do you think we should explicit avoid this replacement?

Comment (SimplyDanny) [reply clang-tools-extra/test/clang-tidy/checkers/performance/avoid-endl.cpp:234]: Yes, for a macro, it's probably better to not suggest a replacement. It would contradict the user's original intention.

File: clang-tools-extra/clang-tidy/performance/AvoidEndlCheck.cpp [hunk 4]
```diff
@@ -46,14 +46,15 @@ void AvoidEndlCheck::check(const MatchFinder::MatchResult &Result) {
...
-                     "do not use '%0' with streams; use '\\n' instead")
-                << SourceText;
-
-    Diag << FixItHint::CreateReplacement(TokenRange, "'\\n'");
+    if (SourceText.empty())
+      SourceText = "std::endl";
+    auto Builder = diag(Expression->getBeginLoc(),
+                        "do not use '%0' with streams; use '\\n' instead");
+    if (TokenRange.isValid())
+      Builder << SourceText
```
Comment (SimplyDanny) [inline clang-tools-extra/clang-tidy/performance/AvoidEndlCheck.cpp:56]: The `<< SourceText` part should always be added, shouldn't it? The tests seem to be fine though. 🤔

**Review by SimplyDanny — APPROVED** [review]

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -120,6 +120,10 @@ Changes in existing checks
   <clang-tidy/checks/modernize/use-std-print>` check to support replacing
   member function calls too.
 
+- Improved :doc:`performance-avoid-endl
+  <clang-tidy/checks/performance/avoid-endl>` check by fixing incorrect
+  message.
+
```
Comment (5chmidti) [inline clang-tools-extra/docs/ReleaseNotes.rst:126]: This feels a bit terse to me. (possible change would depend on the resolution to the other comment)

**Review by 5chmidti — APPROVED** [review]
LGTM
