### PR TITLE
[AArch64] Implement INIT/ADJUST_TRAMPOLINE

### LINKED ISSUE #65573: [Flang][AArch64] Compilation error of a internal subroutine subprogram that use variables defined in the host program
This is an issue from Fujitsu testsuite.

Flang-new terminates abnormally when compiling a internal subroutine subprogram that use variables defined in the host program.
This issue isn't reproduced when the target is X86.

The following are the test program, Flang-new and gfortran compilation result.

```fortran
! test.f90
  integer i
  call sub(inn)
  contains
    subroutine inn
      i = 1
    end subroutine inn
end
```
```console
$ flang-new -v test.f90 -c
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 701e6f7630474b637e0bc45d009bf2ec47f2d3fd)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-redhat-linux/8
Selected GCC installation: /usr/lib/gcc/aarch64-redhat-linux/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +neon -target-feature +v8a -o test.o -x f95-cpp-input test.f90
unimplemented operand
UNREACHABLE executed at /path/to/llvm-project/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5872!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /path/to/install/bin/flang-new -fc1 -triple aarch64-unknown-linux-gnu -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +neon -target-feature +v8a -o test.o -x f95-cpp-input test.f90
1.      Running pass 'Function Pass Manager' on module 'FIRModule'.
2.      Running pass 'AArch64 Instruction Selection' on function '@_QQmain'
 #0 0x0000ffff81ee5f60 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/path/to/install/bin/../lib/libLLVMSupport.so.18git+0x1a5f60)
 #1 0x0000ffff81ee3b40 llvm::sys::RunSignalHandlers() (/path/to/install/bin/../lib/libLLVMSupport.so.18git+0x1a3b40)
 #2 0x0000ffff81ee3cb0 SignalHandler(int) Signals.cpp:0:0
 #3 0x0000ffff839c066c (linux-vdso.so.1+0x66c)
 #4 0x0000ffff818c2dbc raise (/lib64/libc.so.6+0x32dbc)
 #5 0x0000ffff818b0928 abort (/lib64/libc.so.6+0x20928)
 #6 0x0000ffff81e1895c (/path/to/install/bin/../lib/libLLVMSupport.so.18git+0xd895c)
 #7 0x0000ffff8350ffd0 llvm::AArch64TargetLowering::LowerOperation(llvm::SDValue, llvm::SelectionDAG&) const (/path/to/install/bin/../lib/libLLVMAArch64CodeGen.so.18git+0x26ffd0)
 #8 0x0000ffff8123d444 (anonymous namespace)::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*) LegalizeDAG.cpp:0:0
 #9 0x0000ffff81248e94 llvm::SelectionDAG::Legalize() (/path/to/install/bin/../lib/../lib/libLLVMSelectionDAG.so.18git+0x148e94)
#10 0x0000ffff813e8ff4 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/path/to/install/bin/../lib/../lib/libLLVMSelectionDAG.so.18git+0x2e8ff4)
#11 0x0000ffff813ec4dc llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/path/to/install/bin/../lib/../lib/libLLVMSelectionDAG.so.18git+0x2ec4dc)
#12 0x0000ffff813ede08 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) SelectionDAGISel.cpp:0:0
#13 0x0000ffff80aae570 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#14 0x0000ffff7f4404a4 llvm::FPPassManager::runOnFunction(llvm::Function&) (/path/to/install/bin/../lib/../lib/libLLVMCore.so.18git+0x2904a4)
#15 0x0000ffff7f4406e0 llvm::FPPassManager::runOnModule(llvm::Module&) (/path/to/install/bin/../lib/../lib/libLLVMCore.so.18git+0x2906e0)
#16 0x0000ffff7f440fe8 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/path/to/install/bin/../lib/../lib/libLLVMCore.so.18git+0x290fe8)
#17 0x0000ffff82bd0c6c Fortran::frontend::CodeGenAction::executeAction() (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x120c6c)
#18 0x0000ffff82b02b2c Fortran::frontend::FrontendAction::execute() (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x52b2c)
#19 0x0000ffff82af43c4 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x443c4)
#20 0x0000ffff83053bbc Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/path/to/install/bin/../lib/libflangFrontendTool.so.18git+0x3bbc)
#21 0x00000000004048dc fc1_main(llvm::ArrayRef<char const*>, char const*) (/path/to/install/bin/flang-new+0x4048dc)
#22 0x0000000000403108 main (/path/to/install/bin/flang-new+0x403108)
#23 0x0000ffff818b0d64 __libc_start_main (/lib64/libc.so.6+0x20d64)
#24 0x00000000004035d0 _start (/path/to/install/bin/flang-new+0x4035d0)
flang-new: error: unable to execute command: Aborted (core dumped)
flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 701e6f7630474b637e0bc45d009bf2ec47f2d3fd)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
flang-new: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
flang-new: note: diagnostic msg: /tmp/test-398d2a
flang-new: note: diagnostic msg: /tmp/test-398d2a.sh
flang-new: note: diagnostic msg: 

********************
```
```console
$ gfortran -v test.f90 -c
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-redhat-linux/8/lto-wrapper
Target: aarch64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-gnu-indirect-function --build=aarch64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC) 
 :
$
```

### LINKED ISSUE #76927: Flang crash upon running internal_dummy_2.f08 gfortran regression test
Flang crash on gfortran/regression internal_dummy_2.f08 test on various AArch64 machines. This test was enabled by recent commit 82c07c75. If the said feature is not implemented flang should report an appropriate message.

```
******************** TEST 'test-suite :: Fortran/gfortran/regression/gfortran-regression-compile-regression__internal_dummy_2_f08.test' FAILED ********************

/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/tools/timeit-target --limit-core 0 --limit-cpu 7200 --timeout 7200 --limit-file-size 209715200 --limit-rss-size 838860800 --redirect-input /dev/null --summary /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/Output/gfortran-regression-compile-regression__internal_dummy_2_f08.test.time /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/..//dummy
/usr/bin/diff /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/..//gfortran-compile-empty.reference.out /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/gfortran-regression-compile-regression__internal_dummy_2_f08.out
0a1,49
> flang-new: warning: -lpgmath: 'linker' input unused [-Wunused-command-line-argument]
> unimplemented operand
> UNREACHABLE executed at /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6102!
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
> Stack dump:
> 0.	Program arguments: /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new -fc1 -triple aarch64-unknown-linux-gnu -emit-obj -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +neon -target-feature +v8a -module-dir /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/gfortran-regression-compile-regression__internal_dummy_2_f08.wd -mframe-pointer=non-leaf -o internal_dummy_2.o -x f95-cpp-input /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/test-suite/Fortran/gfortran/regression/internal_dummy_2.f08
> 1.	Running pass 'Function Pass Manager' on module 'FIRModule'.
> 2.	Running pass 'AArch64 Instruction Selection' on function '@_QQmain'
>  #0 0x0000aaaad080a000 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x29b4000)
>  #1 0x0000aaaad0807d70 llvm::sys::RunSignalHandlers() (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x29b1d70)
>  #2 0x0000aaaad080a8f8 SignalHandler(int) Signals.cpp:0:0
>  #3 0x0000ffffa10d9598 (linux-vdso.so.1+0x598)
>  #4 0x0000ffffa0bf0d78 raise /build/glibc-Q8DG8B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
>  #5 0x0000ffffa0bddaac abort /build/glibc-Q8DG8B/glibc-2.31/stdlib/abort.c:81:7
>  #6 0x0000aaaad0784ec8 (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x292eec8)
>  #7 0x0000aaaacf528e38 llvm::AArch64TargetLowering::LowerOperation(llvm::SDValue, llvm::SelectionDAG&) const (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x16d2e38)
>  #8 0x0000aaaad270e160 (anonymous namespace)::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*) LegalizeDAG.cpp:0:0
>  #9 0x0000aaaad270d674 llvm::SelectionDAG::Legalize() (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x48b7674)
> #10 0x0000aaaad27d5af8 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x497faf8)
> #11 0x0000aaaad27d3a70 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x497da70)
> #12 0x0000aaaad27d0970 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x497a970)
> #13 0x0000aaaad2bc8bc0 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x4d72bc0)
> #14 0x0000aaaad4a348c8 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x6bde8c8)
> #15 0x0000aaaad4a3c634 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x6be6634)
> #16 0x0000aaaad4a35248 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x6bdf248)
> #17 0x0000aaaad0a11038 Fortran::frontend::CodeGenAction::executeAction() (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x2bbb038)
> #18 0x0000aaaad083e91c Fortran::frontend::FrontendAction::execute() (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x29e891c)
> #19 0x0000aaaad082d5f4 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x29d75f4)
> #20 0x0000aaaad08427f0 Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x29ec7f0)
> #21 0x0000aaaacf3a5530 fc1_main(llvm::ArrayRef<char const*>, char const*) (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x154f530)
> #22 0x0000aaaacf3a45a4 main (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x154e5a4)
> #23 0x0000ffffa0bdde10 __libc_start_main /build/glibc-Q8DG8B/glibc-2.31/csu/../csu/libc-start.c:342:3
> #24 0x0000aaaacf3a3918 _start (/home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin/flang-new+0x154d918)
> flang-new: error: unable to execute command: Aborted
> flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
> flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git fc0fdd1ae20062e4d77c1b7ffc5b06773c752815)
> Target: aarch64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/stage2.install/bin
> flang-new: note: diagnostic msg: 
> ********************
> 
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> flang-new: note: diagnostic msg: /tmp/internal_dummy_2-7c482f
> flang-new: note: diagnostic msg: /tmp/internal_dummy_2-7c482f.sh
> flang-new: note: diagnostic msg: 
> 
> ********************
\ No newline at end of file

+ /usr/bin/diff /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/..//gfortran-compile-empty.reference.out /home/tcwg-buildbot/worker/clang-aarch64-full-2stage/test/sandbox/build/Fortran/gfortran/regression/gfortran-regression-compile-regression__internal_dummy_2_f08.out

********************

```

### LINKED ISSUE #83555: [AArch64] UNREACHABLE executed at AArch64ISelLowering.cpp:6144
LLVM version: 199bbe2b380

Compiling https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/internal_dummy_3.f08 with llvm-flang leads to a crash from hitting UNREACHABLE at AArch64ISelLowering.cpp:6144.

LLVM IR generated by flang:
```
; ModuleID = 'internal_dummy_3.ll'
source_filename = "FIRModule"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_QMmEfirst = global ptr null
@_QQEnvironmentDefaults = constant ptr null

define void @_QMmPtest(ptr %0, ptr %1, ptr %2) #0 {
  %4 = alloca i32, i64 1, align 4
  %5 = alloca i32, i64 1, align 4
  %6 = alloca { ptr }, i64 1, align 8
  %7 = getelementptr { ptr }, ptr %6, i32 0, i32 0
  store ptr %0, ptr %7, align 8
  %8 = ptrtoint ptr %1 to i64
  %9 = icmp ne i64 %8, 0
  br i1 %9, label %10, label %17

10:                                               ; preds = %3
  %11 = call i32 %1()
  %12 = load i32, ptr %0, align 4
  %13 = sub i32 %12, 1
  %14 = icmp ne i32 %11, %13
  br i1 %14, label %15, label %17

15:                                               ; preds = %10
  %16 = call {} @_FortranAStopStatement(i32 1, i1 false, i1 false)
  unreachable

17:                                               ; preds = %10, %3
  %18 = ptrtoint ptr %2 to i64
  %19 = icmp ne i64 %18, 0
  br i1 %19, label %20, label %27

20:                                               ; preds = %17
  %21 = call i32 %2()
  %22 = load i32, ptr %0, align 4
  %23 = sub i32 %22, 2
  %24 = icmp ne i32 %21, %23
  br i1 %24, label %25, label %27

25:                                               ; preds = %20
  %26 = call {} @_FortranAStopStatement(i32 2, i1 false, i1 false)
  unreachable

27:                                               ; preds = %20, %17
  %28 = load i32, ptr %0, align 4
  %29 = icmp eq i32 %28, 1
  br i1 %29, label %30, label %33

30:                                               ; preds = %27
  %31 = alloca [32 x i8], i64 1, align 4
  call void @llvm.init.trampoline(ptr %31, ptr @_QMmFtestPmylevel, ptr %6)
  %32 = call ptr @llvm.adjust.trampoline(ptr %31)
  store ptr %32, ptr @_QMmEfirst, align 8
  br label %33

33:                                               ; preds = %30, %27
  %34 = load ptr, ptr @_QMmEfirst, align 8
  %35 = call i32 %34()
  %36 = icmp ne i32 %35, 1
  br i1 %36, label %37, label %39

37:                                               ; preds = %33
  %38 = call {} @_FortranAStopStatement(i32 3, i1 false, i1 false)
  unreachable

39:                                               ; preds = %33
  %40 = load i32, ptr %0, align 4
  %41 = icmp eq i32 %40, 10
  br i1 %41, label %53, label %42

42:                                               ; preds = %39
  br i1 %9, label %43, label %48

43:                                               ; preds = %42
  %44 = load i32, ptr %0, align 4
  %45 = add i32 %44, 1
  %46 = alloca [32 x i8], i64 1, align 4
  call void @llvm.init.trampoline(ptr %46, ptr @_QMmFtestPmylevel, ptr %6)
  %47 = call ptr @llvm.adjust.trampoline(ptr %46)
  store i32 %45, ptr %5, align 4
  call void @_QMmPtest(ptr %5, ptr %47, ptr %1)
  br label %53

48:                                               ; preds = %42
  %49 = load i32, ptr %0, align 4
  %50 = add i32 %49, 1
  %51 = alloca [32 x i8], i64 1, align 4
  call void @llvm.init.trampoline(ptr %51, ptr @_QMmFtestPmylevel, ptr %6)
  %52 = call ptr @llvm.adjust.trampoline(ptr %51)
  store i32 %50, ptr %4, align 4
  call void @_QMmPtest(ptr %4, ptr %52, ptr null)
  br label %53

53:                                               ; preds = %48, %43, %39
  ret void
}

define internal i32 @_QMmFtestPmylevel(ptr nest %0) #0 {
  %2 = getelementptr { ptr }, ptr %0, i32 0, i32 0
  %3 = load ptr, ptr %2, align 8
  %4 = alloca i32, i64 1, align 4
  %5 = load i32, ptr %3, align 4
  store i32 %5, ptr %4, align 4
  %6 = load i32, ptr %4, align 4
  ret i32 %6
}

define void @_QQmain() #0 {
  %1 = alloca i32, i64 1, align 4
  store i32 1, ptr %1, align 4
  call void @_QMmPtest(ptr %1, ptr null, ptr null)
  ret void
}

declare {} @_FortranAStopStatement(i32, i1 zeroext, i1 zeroext)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.init.trampoline(ptr nocapture writeonly, ptr readnone, ptr readnone) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare ptr @llvm.adjust.trampoline(ptr) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn
declare ptr @llvm.stacksave.p0() #3

; Function Attrs: nocallback nofree nosync nounwind willreturn
declare void @llvm.stackrestore.p0(ptr) #3

attributes #0 = { "frame-pointer"="non-leaf" "target-cpu"="generic" "target-features"="+outline-atomics,+v8a,+fp-armv8,+neon" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #3 = { nocallback nofree nosync nounwind willreturn }

!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
```

To reproduce, run `llc` on this IR.

### PR DESCRIPTION
**Pull request by ceseo**
Add support for llvm.init.trampoline and llvm.adjust.trampoline intrinsics for
AArch64.

Fixes https://github.com/llvm/llvm-project/issues/65573
Fixes https://github.com/llvm/llvm-project/issues/76927
Fixes https://github.com/llvm/llvm-project/issues/83555
Updates https://github.com/llvm/llvm-project/pull/66157

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
@ceseo Thanks for this patch.
Did you see the related patch in Phabricator? https://reviews.llvm.org/D149848

**Comment by ceseo** [comment]
> @ceseo Thanks for this patch. Did you see the related patch in Phabricator? https://reviews.llvm.org/D149848

I missed that one. Thanks for pointing that out.

So, I think I agree that it is better to do the same as gcc does. The code will probably be very untidy, since we have to write the actual instructions (like in the x86 implementation), but it should work too.

The only observation I have is that, whatever the approach is, we cannot use `x18` for the nest parameter outside Linux because both macOS and Windows ABIs already assign this register for something else.

If the submitter of that patch wants to do this, I'm OK with that since I'll be away for a month or so.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -5946,6 +5946,56 @@ static SDValue LowerFLDEXP(SDValue Op, SelectionDAG &DAG) {
...
+
+  return Op.getOperand(0);
+}
+
+SDValue AArch64TargetLowering::LowerINIT_TRAMPOLINE(SDValue Op,
+                                                    SelectionDAG &DAG) const {
+
+  // Note: x18 cannot be used for the Nest parameter on Windows and macOS.
+  if (Subtarget->isTargetDarwin() || Subtarget->isTargetWindows())
+    report_fatal_error("INIT_TRAMPOLINE operation is only supported on Linux.");
```
Comment (compnerd) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5964]: Windows ARM64 supports x16, x17 as intra-procedural scratch. AIUI, GCC does not have `__trampoline_setup` for ARM64, and so, I would say that we should try to adjust the ABI here to make this possible to use on Windows as well.  Is this currently defined in an accepted specification or is this an extension being added?

**Review by compnerd — CHANGES_REQUESTED** [review]

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp (hunk 1 above)
Comment (ceseo) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5964]: Per the Arm PCS:

"The role of register r18 is platform specific. If a platform ABI has need of a dedicated general purpose register to carry inter-procedural state (for example, the thread context) then it should use this register for that purpose. If the platform ABI has no such requirements, then it should use r18 as an additional temporary register. The platform ABI specification must document the usage for this register."

Both macOS and Windows use this as the Platform Register and LLVM documents this in `AArch64CallingConvention.td`.

File: compiler-rt/lib/builtins/README.txt [hunk 2]
```diff
@@ -272,6 +272,11 @@ switch32
 switch8
 switchu8
 
+// This function generates a custom trampoline function with the specific
+// realFunc and localsPtr values.
+void __trampoline_setup(uint32_t* trampOnStack, int trampSizeAllocated,
+                                const void* realFunc, void* localsPtr);
```
[the remark this answers is not in the document]
Comment (ceseo) [reply compiler-rt/lib/builtins/README.txt:278]: OK, will do. Strange that `git clang-format` didn't catch this for me.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp (hunk 1 above)
Comment (ceseo) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5964]: Also, something just came to my mind. This kind of trampoline for nested function calls requires executable stack. Doesn't DEP block that on Windows?

**Comment by giordano** [comment]
Probably fixes #56625 too?

**Comment by ceseo** [comment]
> Probably fixes #56625 too? _**Edit**_: not yet, if this is limited to Linux

Yes, we need to sort out the nest parameter register for Windows and macOS. Both use `x18` as the platform register. So this is Linux only for now.

**Comment by ceseo** [comment]
Any other comments on this?

**Comment by ceseo** [comment]
We will try another approach that avoids executable stack when procedure pointers support is fully implemented.

**Comment by vzakhari** [comment]
I think this change is useful on its own for aarch64 Linux, and I think it can be merged as is.

**Comment by kiranchandramohan** [comment]
@ceseo What is your plan here? Do you have a different patch?

**Comment by ceseo** [comment]
Not for now. I'm waiting until the support for procedure pointers is fully implemented and then I'll give it another shot to avoid executable stack.

If you think this is useful as is until then, please feel free to merge it.

**Comment by kiranchandramohan** [comment]
@ceseo Could you reopen the PR?

**Comment by MaskRay** [comment]
Description:

> Updates `https://github.com/llvm/llvm-project/issues/27174`

27174 is an AMDGPU issue. Is there a typo?

**Comment by ceseo** [comment]
> Description:
> 
> > Updates `https://github.com/llvm/llvm-project/issues/27174`
> 
> 27174 is an AMDGPU issue. Is there a typo?

Sorry, I had the number from an issue in the Julia repo in my mind. I'll fix that. This PR actually fixes other issues as well. I'll reference those.

File: compiler-rt/lib/builtins/trampoline_setup.c [hunk 3]
```diff
@@ -41,3 +41,30 @@ COMPILER_RT_ABI void __trampoline_setup(uint32_t *trampOnStack,
...
 }
 #endif // __powerpc__ && !defined(__powerpc64__)
+
+// The AArch64 compiler generates calls to __trampoline_setup() when creating
+// trampoline functions on the stack for use with nested functions.
+// This function creates a custom 20-byte trampoline function on the stack
+// which loads x18 with a pointer to the outer function's locals
+// and then jumps to the target nested function.
+
+#if __aarch64__
```
Comment (vzakhari) [inline compiler-rt/lib/builtins/trampoline_setup.c:51]: I would suggest adding `defined(__linux__)` guard as well.

File: compiler-rt/lib/builtins/trampoline_setup.c [hunk 4]
```diff
@@ -41,3 +41,30 @@ COMPILER_RT_ABI void __trampoline_setup(uint32_t *trampOnStack,
...
+
+  // create trampoline
+  trampOnStack[0] = 0x580000b1; // ldr x17, realFunc
+  trampOnStack[1] = 0x580000d2; // ldr x18, localsPtr
+  trampOnStack[2] = 0xd61f0220; // br x17
+  trampOnStack[3] = (uint32_t)realFunc;
+  trampOnStack[4] = (uint32_t)localsPtr;
+
+  // clear instruction cache
+  __clear_cache(trampOnStack, &trampOnStack[10]);
```
Comment (vzakhari) [inline compiler-rt/lib/builtins/trampoline_setup.c:68]:
```suggestion
  __clear_cache(trampOnStack, &trampOnStack[5]);
```

**Comment by ceseo** [comment]
The address loading is wrong as well. I'll fix that and resubmit.

File: compiler-rt/lib/builtins/trampoline_setup.c [hunk 5]
```diff
@@ -41,3 +41,30 @@ COMPILER_RT_ABI void __trampoline_setup(uint32_t *trampOnStack,
...
+  // should never happen, but if compiler did not allocate
+  // enough space on stack for the trampoline, abort
+  if (trampSizeAllocated < 20)
+    compilerrt_abort();
+
+  // create trampoline
+  trampOnStack[0] = 0x580000b1; // ldr x17, realFunc
+  trampOnStack[1] = 0x580000d2; // ldr x18, localsPtr
+  trampOnStack[2] = 0xd61f0220; // br x17
+  trampOnStack[3] = (uint32_t)realFunc;
```
Comment (vzakhari) [inline compiler-rt/lib/builtins/trampoline_setup.c:64]: The casts seem to be truncating.

**Comment by vzakhari** [comment]
It is also worth adding a LIT test for the ISEL.

File: compiler-rt/lib/builtins/trampoline_setup.c (hunk 3 above)
Comment (MaskRay) [reply compiler-rt/lib/builtins/trampoline_setup.c:51]: This can be `defined(__aarch64__) && defined(__ELF__)` since other ELF OSes likely need this as well.

Comment (ceseo) [reply compiler-rt/lib/builtins/trampoline_setup.c]: There is already an OS guard in the lowering code. Does it need to be done here as well? I don't think anything else call this code.

Comment (vzakhari) [reply compiler-rt/lib/builtins/trampoline_setup.c]: I prefer the library implementation being guarded as well, so that its limitations are clear in the library source code.

**Review by DavidTruby — COMMENTED** [review]
I had a go at trying this out for a case where we generate the trampoline in flang but we currently don't have the -rtlib=compiler-rt flag and it looks like this will require compiler-rt over libgcc_s? I'll try to quickly implement -rtlib so I can see if this works for our flang cases.

**Comment by ceseo** [comment]
> I had a go at trying this out for a case where we generate the trampoline in flang but we currently don't have the -rtlib=compiler-rt flag and it looks like this will require compiler-rt over libgcc_s? I'll try to quickly implement -rtlib so I can see if this works for our flang cases.

I noticed this today as well. It wasn't happening when I first submitted the patch a long time ago. Did something change in compiler-rt that may affect this?

**Comment by DavidTruby** [comment]
> I noticed this today as well. It wasn't happening when I first submitted the patch a long time ago. Did something change in compiler-rt that may affect this?

I don't think anything changed; we don't link to compiler-rt on Linux, instead we link to libgcc_s. Clang does this by default too but has a flag to choose compiler-rt instead. I don't have the __start_trampoline symbol in libgcc_s on my system so I guess we'll need to require compiler-rt for this.

I don't think that invalidates the patch, at least as a stopgap until we can get non-executable stack trampolines working. On x86 LLVM doesn't require an external function for this, it just does the code inline. I'm guessing that's quite difficult to do here?

**Comment by DavidTruby** [comment]
I've added the -rtlib flag in #99058. With that change and this one, I am able to build quantum-espresso with `-rtlib=compiler-rt` and have it pass tests, which previously failed due to the missing trampoline implementation.

File: compiler-rt/lib/builtins/README.txt [hunk 6]
```diff
@@ -272,6 +272,11 @@ switch32
 switch8
 switchu8
 
+// This function generates a custom trampoline function with the specific
+// realFunc and localsPtr values.
+void __trampoline_setup(uint32_t* trampOnStack, int trampSizeAllocated,
+                        const void* realFunc, void* localsPtr);
```
[the remark this answers is not in the document]
Comment (ceseo) [reply compiler-rt/lib/builtins/README.txt:278]: The latter.

**Comment by ceseo** [comment]
> > I noticed this today as well. It wasn't happening when I first submitted the patch a long time ago. Did something change in compiler-rt that may affect this?
> 
> I don't think anything changed; we don't link to compiler-rt on Linux, instead we link to libgcc_s. Clang does this by default too but has a flag to choose compiler-rt instead. I don't have the __start_trampoline symbol in libgcc_s on my system so I guess we'll need to require compiler-rt for this.
> 
> I don't think that invalidates the patch, at least as a stopgap until we can get non-executable stack trampolines working. On x86 LLVM doesn't require an external function for this, it just does the code inline. I'm guessing that's quite difficult to do here?

Correct.

**Review by vzakhari — APPROVED** [review]
Thank you! LGTM

File: llvm/test/CodeGen/AArch64/trampoline.ll [hunk 7]
```diff
@@ -0,0 +1,31 @@
+; RUN: llc -mtriple=aarch64-- < %s | FileCheck %s
+; UNSUPPORTED: darwin, system-windows
+
+declare void @llvm.init.trampoline(i8*, i8*, i8*);
+declare i8* @llvm.adjust.trampoline(i8*);
```
Comment (MaskRay) [inline llvm/test/CodeGen/AArch64/trampoline.ll:5]: Avoid typed pointers like `i8*`. Use opaque pointers `ptr`

File: llvm/test/CodeGen/AArch64/trampoline.ll [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+
+define i64 @func(i64* nest %ptr, i64 %val)
```
Comment (MaskRay) [inline llvm/test/CodeGen/AArch64/trampoline.ll:7]: The prevailing style is to place `{` at the end of the previous line

**Comment by MaskRay** [comment]
> Updates #27174

Can you change the description? It will be used as the default commit message when you click "Squash and merge".
git commit messages are completely ignored.

**Comment by ceseo** [comment]
> > Updates #27174
> 
> Can you change the description? It will be used as the default commit message when you click "Squash and merge". git commit messages are completely ignored.

OK. I'll fix the test and the description and resubmit.

**Comment by ceseo** [comment]
I also simplified the test.

**Review by DavidTruby — APPROVED** [review]
LGTM, but wait for @MaskRay to approve. 

Could you update the NOTE about aarch64 in https://github.com/llvm/llvm-project/blob/main/flang/docs/InternalProcedureTrampolines.md to note that this is implemented now, but requires compiler-rt (and -rtlib=compiler-rt)? That can be in a separate NFC patch without review after -rtlib=compiler-rt goes in, if you merge this first.

**Comment by ceseo** [comment]
Ping?

**Comment by ceseo** [comment]
@kiranchandramohan do you want this in for LLVM 19, or should we leave it for LLVM 20?

**Comment by kiranchandramohan** [comment]
> @kiranchandramohan do you want this in for LLVM 19, or should we leave it for LLVM 20?

Yes, it will be great to have this for LLVM 19 since this enables an important HPC application.

File: llvm/test/CodeGen/AArch64/trampoline.ll [hunk 9]
```diff
@@ -0,0 +1,20 @@
+; RUN: llc -mtriple=aarch64-- < %s | FileCheck %s
```
Comment (MaskRay) [inline llvm/test/CodeGen/AArch64/trampoline.ll:1]: `-mtriple=aarch64` specifies a generic ELF triple (yes, ELF is the default:) )

`; UNSUPPORTED: darwin, system-windows` should not be needed.

File: compiler-rt/lib/builtins/trampoline_setup.c [hunk 10]
```diff
@@ -41,3 +41,45 @@ COMPILER_RT_ABI void __trampoline_setup(uint32_t *trampOnStack,
...
 #endif // __powerpc__ && !defined(__powerpc64__)
+
+// The AArch64 compiler generates calls to __trampoline_setup() when creating
+// trampoline functions on the stack for use with nested functions.
+// This function creates a custom 36-byte trampoline function on the stack
+// which loads x18 with a pointer to the outer function's locals
+// and then jumps to the target nested function.
+// Note: x18 is a reserved platform register on Windows and macOS.
+
+#if defined(__aarch64__) && !defined(__APPLE__) && !defined(_WIN64)
```
Comment (MaskRay) [inline compiler-rt/lib/builtins/trampoline_setup.c:52]: Perhaps `defined(__ELF__)` is slightly better and clearly excludes Apple (Mach-O) and Windows (PE/COFF).

**Review by MaskRay — APPROVED** [review]
LGTM.

Ideally @compnerd could remove the "Request changes".

I agree that this will be nice to be merged into relase/19.x

File: compiler-rt/lib/builtins/trampoline_setup.c (hunk 10 above)
Comment (ceseo) [reply compiler-rt/lib/builtins/trampoline_setup.c:52]: OK, makes sense.

File: llvm/test/CodeGen/AArch64/trampoline.ll (hunk 9 above)
Comment (ceseo) [reply llvm/test/CodeGen/AArch64/trampoline.ll:1]: OK, I'll remove that.

**Comment by ceseo** [comment]
> Yes, it will be great to have this for LLVM 19 since this enables an important HPC application.

I'll just make the small changes requested by @MaskRay and resubmit the final version.

**Comment by ceseo** [comment]
@kiranchandramohan I'll commit this once all the checks pass.

**Comment by ceseo** [comment]
I will merge this PR. The Windows failure is due to something else and it was fixed by 7b619730d9e2bcc2ab1588574ed94ae19c4b8654

**Comment by eschnett** [comment]
It looks like LLVM 19 will support this.

**Comment by vchuravy** [comment]
As a note GCC v14 has implemented heap based trampolines (using x18 on Linux and x16 on Apple).

https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gcc/Code-Gen-Options.html#index-ftrampoline-impl

**Comment by vtjnash** [comment]
heap-based trampolines is a higher-level (clang or flang) concern, not llvm, since llvm's intrinsics just takes a pointer to some memory, but doesn't care where/how it got allocated
