### PR TITLE
[lld][WebAssembly] Fix spurious signature mismatch under LTO

### LINKED ISSUE #104497: Web Export fails with Basis Universal textures
### Tested versions

Reproducible in 4.4 stable and 4.5 dev1

### System information

Godot v4.5.dev1 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu, 13 Mar 2025 14:03:23 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 570.133.07) - AMD Ryzen 9 9900X 12-Core Processor (24 threads)

### Issue description

Tested on multiple devices, as soon as I have at least one texture with Basis Universal import settings, the web app fails to load with the following error

Image

### Steps to reproduce

Set a texture to use Basis Universal import and notice web exports are broken. 

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/19406478/test.zip)

### PR DESCRIPTION
**Pull request by BertalanD**
When generating C++ vtables, Clang declares virtual functions as `void(void)` when their signature is not known (e.g.parameter types are forward-declared). As WASM type checks imports, this would conflict with the real definition during linking. Commit 59f959ff introduced a workaround for this by deferring signature assignment until a definition or direct call is seen.

When performing LTO, LLD first scans the bitcode files and creates `DefinedFunction` symbol table entries for their contents. After LTO codegen, they are replaced with `UndefinedFunction`s (so that the definitions will be pulled in from the native LTO-d files when they are added). At this point, if a function is only referenced in bitcode, its signature remains `nullptr`.

From here, it should have behaved like in the non-LTO case: the first direct call sets the signature. However, as the `isCalledDirectly` flag was set to true, the missing signature was filled in by the type of the first reference to the function, which could be a `void(void)` vtable entry, which would then conflict with the real definition.

This commit sets `isCalledDirectly` to false so that the signature will only be populated when a direct call is found.

Potentially fixes godotengine/godot#104497 and emscripten-core/emscripten#10831

### CODE REVIEW

File: lld/wasm/LTO.cpp [hunk 1]
```diff
@@ -108,9 +108,10 @@ BitcodeCompiler::~BitcodeCompiler() = default;
 
 static void undefine(Symbol *s) {
   if (auto f = dyn_cast<DefinedFunction>(s))
+    // If the signature is null, there were no calls from non-bitcode objects.
     replaceSymbol<UndefinedFunction>(f, f->getName(), std::nullopt,
                                      std::nullopt, 0, f->getFile(),
-                                     f->signature);
+                                     f->signature, f->signature != nullptr);
```
Comment (sbc100) [inline lld/wasm/LTO.cpp:114]: I wonder if we should instead make SymbolTable.cpp assume that the null signature is a placeholder?  i.e. today we do `checkSig = ud->isCalledDirectly;` but we could do `checkSig = ud->isCalledDirectly && ud->signature;`?

I don't feel strongly though and this approach certainly works.

**Review by sbc100 — COMMENTED** [review]
Nice! Thanks for working on this.

**Review by sbc100 — APPROVED** [review]

File: lld/wasm/LTO.cpp (hunk 1 above)
Comment (BertalanD) [reply lld/wasm/LTO.cpp:114]: I don't think that would fix the issue: `signatureMatches()` returns `true` when either function has a null signature.

In the test case, after LTO, the `() -> void` reference from `a.ll` is added first. The existing undefined symbol has a null signature, but this one doesn't, so we set `existingFunction->signature` to `() -> void`:

https://github.com/llvm/llvm-project/blob/1db03cab70fd29fe13cb60cc102285d0d0f33957/lld/wasm/SymbolTable.cpp#L657-L658

 As `isCalledDirectly` is set to true, we'll report the signature mismatch when we try to add the `() -> i32` definition from `b.ll`.

I suppose an alternative would be to only set `existingFunction->signature` if  the undefined symbol we replace it with is called directly, but that would mean we never set the signature if the function has no call sites, only its address is taken. That might cause problems later on.

Comment (sbc100) [reply lld/wasm/LTO.cpp:114]: Sounds good.  LGTM as is.

Comment (BertalanD) [reply lld/wasm/LTO.cpp:114]: thanks!
