### PR TITLE
[clang] fix constexpr-unknown handling of self-references.

### LINKED ISSUE #131330: [Clang] Regression on not rejecting UB in constexpr reference initialization due to implementing P2280R4
Currently, Clang accepts the following code snippet since C++23 mode. [Godbolt link](https://godbolt.org/z/5cxGrq6Gb).

```C++
constexpr int& r = r;
```

[[dcl.ref]/6](https://eel.is/c++draft/dcl.ref#6) (as clarified by the resolution of [CWG453](https://cplusplus.github.io/CWG/issues/453.html)) indicates that such reference binding has UB, and thus needs to be rejected in constant evaluation.

Perhaps this is due to something missed in #95474.

Codegen change can be observed by dropping `constexpr` ([Godbolt link](https://godbolt.org/z/6vo8dqTP5)), but this is conforming as such initialization raises UB.

### PR DESCRIPTION
**Pull request by efriedma-quic**
Usually, in constant evaluation, references which are local to the evaluation have to be initialized before they're accessed.  However, there's one funny special case: the initializer of a reference can refer to itself.  This generally ends up being undefined behavior if it's used in an evaluated context, but it isn't otherwise forbidden.

In constant evaluation, this splits into two cases: global variables, and local variables in constexpr functions.  This patch handles both of those cases.  (Local variables tends to trip other errors in most cases, but if you try hard enough, you can get an accepts-invalid.)

Fixes #131330 .

### CODE REVIEW

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp [hunk 1]
```diff
@@ -177,3 +177,50 @@ namespace extern_reference_used_as_unknown {
...
+  }
+  constexpr uintptr_t gg4 = g4(); // expected-error {{must be initialized by a constant expression}} \
+  // interpreter-note {{in call to 'g4()'}}
+  constexpr int g5() {
+    int &x = x; // expected-warning {{reference 'x' is not yet bound to a value when used within its own initialization}} \
+    // interpreter-note {{read of uninitialized object is not allowed in a constant expression}}
+    return 3;
+  }
+  constexpr uintptr_t gg5 = g5(); // interpreter-error {{must be initialized by a constant expression}} \
+  // interpreter-note {{in call to 'g5()'}}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/constant-expression-p2280r4.cpp:224]: `g5()` looks valid to me  - in the initializer `x` refer to a reference whose lifetime has not yet started, and therefore it is constexpr-unknown and should not be an error
@t3nsor

File: clang/lib/AST/ExprConstant.cpp [hunk 2]
```diff
@@ -3629,17 +3644,17 @@ static bool evaluateVarDeclInit(EvalInfo &Info, const Expr *E,
 
   Result = VD->getEvaluatedValue();
 
-  // C++23 [expr.const]p8
-  // ... For such an object that is not usable in constant expressions, the
-  // dynamic type of the object is constexpr-unknown. For such a reference that
-  // is not usable in constant expressions, the reference is treated as binding
-  // to an unspecified object of the referenced type whose lifetime and that of
-  // all subobjects includes the entire constant evaluation and whose dynamic
-  // type is constexpr-unknown.
```
Comment (cor3ntin) [inline clang/lib/AST/ExprConstant.cpp:3638]: Why remove the comment?

**Review by cor3ntin — COMMENTED** [review]
Thanks. 
I think the direction makes sense

Do you intend to backport this change to 20?

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp (hunk 1 above)
Comment (efriedma-quic) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:224]: The relevant standard language is, I think, "all id-expressions and uses of *this that refer to an object or reference whose lifetime did not begin with the evaluation of E[...]".  For a local variable inside a constexpr function, I think it does "begin with the evaluation of E", even if its lifetime hasn't yet started, because it's part of the constexpr call frame.  Therefore it's not allowed. I might be missing something, though.

There's also a sort of practical argument: it's weird to say that `int &x = x;` in a constexpr function is well-defined during constant evaluation, but has undefined behavior at runtime.

That said, the compiler's state is internally consistent either way.

File: clang/lib/AST/ExprConstant.cpp (hunk 2 above)
Comment (efriedma-quic) [reply clang/lib/AST/ExprConstant.cpp:3638]: The comment didn't make sense at that location in the code, given the refactoring.  I could stick something into CheckUninitReference, I guess.

**Comment by efriedma-quic** [comment]
> Do you intend to backport this change to 20?

The weird behavior only shows up if you refer to a reference variable inside its own initializer, as far as I can tell.  Maybe not worth backporting, even if it is a regression, because people shouldn't be writing code like that in the first place.

**Comment by cor3ntin** [comment]
> > Do you intend to backport this change to 20?
> 
> The weird behavior only shows up if you refer to a reference variable inside its own initializer, as far as I can tell. Maybe not worth backporting, even if it is a regression, because people shouldn't be writing code like that in the first place.

Fair enough, in that case, can you add a changelog entry? Thanks!

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp (hunk 1 above)
Comment (t3nsor) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:224]: I think it would be extremely strange if the intent of the standard were to not allow this case to be diagnosed. Going by the literal wording, yes, you have an id-expression that refers to a reference whose lifetime didn't begin within the constant evaluation (because it hasn't begun at all), which makes it an unknown reference, but in reality we know exactly what's happening here. It seems like the standard may have a defect and the rule for references really should be that the reference is unknown only if its *initialization* didn't begin within the evaluation of E.

Comment (cor3ntin) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:224]: @zygoloid

Comment (shafik) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:224]: based on [cwg453](https://wg21.link/cwg453) this is UB and we should not accept it.

File: clang/lib/AST/ExprConstant.cpp (hunk 2 above)
Comment (shafik) [reply clang/lib/AST/ExprConstant.cpp:3638]: Please move this up to `CheckUninitReference`

**Review by efriedma-quic — COMMENTED** [review]
Addressed review comments.  We now reject g3() and g5(), the cases that involved using a local variable in a constexpr function in its own initializer.

**Review by shafik — APPROVED** [review]
LGTM any objections @cor3ntin @t3nsor?

**Comment by efriedma-quic** [comment]
Ping

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit
