### PR TITLE
[CUDA][HIP] capture possible ODR-used var

### LINKED ISSUE #132068: [Clang][CUDA][HIP] lambda capture of constexpr variable inconsistent between host and device
Consider the following bit of HIP code:

```c++
#include <algorithm>

using std::max;

template<typename F>
static void __global__
kernel(F f)
{
  f(1);
}

void test(float const * fl, float const * A, float * Vf)
{
  float constexpr small(1.0e-25);

  auto f = [=] __device__ __host__ (unsigned int n) {
    float const value = max(small, fl[0]);
    Vf[0] = value * A[0];
  };
  static_assert(sizeof(f) == sizeof(fl) + sizeof(A) + sizeof(Vf));
  kernel<<<1,1>>>(f);
}
```
The `static_assert` fails in the host-side compilation but succeeds in the device-side compilation. This means that the layout of the struct synthesized from the lambda is inconsistent between host and device, so if you use any of the captured variables on the device side, they will contain the data of some of the other variables. You can also use `-Xclang -fdump-record-layouts` to see that. Evidently the `constexpr` variable is part of the captured variables only on the host side, but not on the device side.
With `--cuda-host-only`:
```
*** Dumping AST Record Layout
         0 | class (lambda at <source>:23:12)
         0 |   const float * 
         8 |   const float 
        16 |   float * 
        24 |   const float * 
           | [sizeof=32, dsize=32, align=8,
           |  nvsize=32, nvalign=8]
```
With `--cuda-device-only`:
```
*** Dumping AST Record Layout
         0 | class (lambda at <source>:23:12)
         0 |   const float * 
         8 |   float * 
        16 |   const float * 
           | [sizeof=24, dsize=24, align=8,
           |  nvsize=24, nvalign=8]
```
Godbolt: https://cuda.godbolt.org/z/KE789sevs.

When you compile the exact same code for CUDA, this does not happen. However, if you add
```c++
template <typename T, std::enable_if_t<std::is_arithmetic<T>::value, int> = 0>
__host__ T max(const T a, const T b) {
    return std::max(a, b);
}
```
after line 3 of the code at the top, you get the exact same layout discrepancy as with HIP. See https://cuda.godbolt.org/z/e3Ybr4hK1.

I can replace the `[=]` with `[fl, A, Vf]` and if that `__host__ T max` overload is present, it tells me that _variable 'small' cannot be implicitly captured in a lambda with no capture-default specified_, but if I leave out that overload it does not show that error message.

The example code uses `std::max` (from the GNU libstdc++), but I have no doubt that the same issue can easily be demonstrated without making use of any library headers.

`nvcc`, for comparison, does not exhibit this issue (https://cuda.godbolt.org/z/33MvMc755). It has a consistent capture size between host and device. Judging by the size, the `constexpr` variable seems to be part of the capture, though in contrast to Clang, a lambda appears to always occupy 8 bytes more than required for its captured variables.

### PR DESCRIPTION
**Pull request by yxsamliu**
In a lambda function, a call of a function may
resolve to host and device functions with different
signatures. Especially, a constexpr local variable may
be passed by value by the device function and
passed by reference by the host function, which
will cause the constexpr variable captured by
the lambda function in host compilation but
not in the device compilation. The discrepancy
in the lambda captures will violate ODR and
causes UB for kernels using these lambdas.

This PR fixes the issue by identifying
discrepancy of ODR/non-ODR usages of constexpr
local variables passed to host/device functions
and conservatively capture them.

Fixes: https://github.com/llvm/llvm-project/issues/132068

### CODE REVIEW

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -14706,6 +14706,8 @@ ExprResult Sema::BuildOverloadedCallExpr(Scope *S, Expr *Fn,
   // the UnresolvedLookupExpr was type-dependent.
   if (OverloadResult == OR_Success) {
     const FunctionDecl *FDecl = Best->Function;
+    if (LangOpts.CUDA)
```
[the remark this answers is not in the document]
Comment (yxsamliu) [reply clang/lib/Sema/SemaOverload.cpp:14709]: LangOpts.CUDA is also true for HIP. same as below

File: clang/lib/Sema/SemaCUDA.cpp [hunk 2]
```diff
@@ -1100,3 +1101,49 @@ std::string SemaCUDA::getConfigureFuncName() const {
...
+  for (unsigned I = 0; I < Arguments.size(); ++I) {
+    auto *DeclRef = dyn_cast<DeclRefExpr>(Arguments[I]);
+    if (!DeclRef)
+      continue;
+    auto *Variable = dyn_cast<VarDecl>(DeclRef->getDecl());
+    if (!Variable || !Variable->isLocalVarDecl() || !Variable->isConstexpr())
+      continue;
+
+    bool HostByValue = false, HostByRef = false;
+    bool DeviceByValue = false, DeviceByRef = false;
```
Comment (Artem-B) [inline clang/lib/Sema/SemaCUDA.cpp:1122]: I'd move them do to where we use them.

File: clang/lib/Sema/SemaCUDA.cpp [hunk 3]
```diff
@@ -1100,3 +1101,49 @@ std::string SemaCUDA::getConfigureFuncName() const {
...
+      bool CoversHost = (Target == CUDAFunctionTarget::Host ||
+                         Target == CUDAFunctionTarget::HostDevice);
+      bool CoversDevice = (Target == CUDAFunctionTarget::Device ||
+                           Target == CUDAFunctionTarget::HostDevice);
+
+      bool IsRef = Callee->getParamDecl(I)->getType()->isReferenceType();
+      if (CoversHost)
+        IsRef ? HostByRef = true : HostByValue = true;
+      if (CoversDevice)
+        IsRef ? DeviceByRef = true : DeviceByValue = true;
```
Comment (Artem-B) [inline clang/lib/Sema/SemaCUDA.cpp:1143]: Can't say I'm a big fan of assignments inside of a ternary. 

In this case, i'd bypass all the conditionals altogether and just initialize all variables:
```
bool HostByValue = CoversHost && !IsRef, 
bool HostByRef = CoversHost && IsRef;
bool DeviceByValue = CoversDevice && !IsRef;
bool DeviceByRef = CoversDevice && IsRef;
```

**Review by Artem-B — APPROVED** [review]
LGTM w/ a nit.

File: clang/lib/Sema/SemaCUDA.cpp (hunk 3 above)
Comment (yxsamliu) [reply clang/lib/Sema/SemaCUDA.cpp:1143]: will do
