### PR TITLE
[clang-format] Fix crashes in AlignArrayOfStructures

### LINKED ISSUE #54815: `clang-format` crashes with combination of `AlignArrayOfStructures` and `ColumnLimit: 0`
clang-format crashes with next file:
```cpp
Test::Test() noexcept
    : a{}
    , b{
          {A::V, {B::V, C::V}},
      }
{}
```
clang-format config:
```
---
Language:        Cpp
AlignArrayOfStructures: Left
ColumnLimit: 0
...
```
crash message:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" test.cpp
 #0 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0xbe28f C:\Program Files\LLVM\bin\clang-format.exe 0xbcd39
 #1 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0xb9ef7 C:\Program Files\LLVM\bin\clang-format.exe 0x86397
 #2 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0xa2519 C:\Program Files\LLVM\bin\clang-format.exe 0x94664
 #3 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0x7dd6e C:\Program Files\LLVM\bin\clang-format.exe 0x7ec69
 #4 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0x545c C:\Program Files\LLVM\bin\clang-format.exe 0x36f6
 #5 0x00007ff720b6e28f C:\Program Files\LLVM\bin\clang-format.exe 0x1843e8 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe28f)
 #6 0x00007ff720b6e28f
 #7 0x00007ff720b6e28f (C:\Program Files\LLVM\bin\clang-format.exe+0xbe28f)
0x00007FF720B6E28F (0x0000006E2A18B3E8 0x0000000000000000 0x0000006E00000000 0x0000006E2A18CB10)
0x00007FF720B6CD39 (0x0000000000000000 0x0000006E00000000 0x0000006E2A18B028 0x00007FFA04ACF05B)
0x00007FF720B69EF7 (0x0000016FBA1E25E0 0x0000000000000000 0x0000000000000000 0x0000001000000000)
0x00007FF720B36397 (0x0000006E2A18BD90 0x00007FF720B5292E 0x0000000000000000 0x0000000000000000)
0x00007FF720B52519 (0x0000000000000000 0x0000006E2A18CB00 0x0000006E2A18CF80 0x0000000000000008)
0x00007FF720B44664 (0x0000000000000100 0x0000000000000000 0x0000016FBA1EAEF0 0x0000000000000003)
0x00007FF720B2DD6E (0x0000016FBA1D4FC0 0x00007FFA070547B1 0x0000000000000000 0x0000016FBA1C0000)
0x00007FF720B2EC69 (0x0000016FBA1D04A4 0x0072006700000000 0x0000016FBA1D0470 0x0000000000340032)
0x00007FF720AB545C (0x0000016FBA1CC300 0x000000000000000E 0x0000000000000000 0x0000016FBA1C6850)
0x00007FF720AB36F6 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF720C343E8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA06BE7034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA07082651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

clang-format version: 14.0.0

### LINKED ISSUE #55269: [clang-format] Crash with AlignArrayOfStructures
When running the following commands, I see a core-dump in clang-format:
```
git checkout https://github.com/nih-at/ckmame.git
cd ckmame/src
clang-format -i Configuration.cc
```
(try with commit 756223d3dd6c4f3d771454f84186c99c5a882b31 from the repository just to be sure you use the same version)
I've tried it with `clang-format version 13.0.1` but I'm told it also happens with clang 14.

The backtrace for clang 13.0.1 is:
```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-format -i Configuration.cc
 #0 0x00006f973977a994 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /scratch/lang/llvm/work/llvm-13.0.1.src/lib/Support/Unix/Signals.inc:565:11
 #1 0x00006f97397787ca llvm::sys::RunSignalHandlers() /scratch/lang/llvm/work/llvm-13.0.1.src/lib/Support/Signals.cpp:97:20
 #2 0x00006f97397789b1 SignalHandler(int) /scratch/lang/llvm/work/llvm-13.0.1.src/lib/Support/Unix/Signals.inc:407:1
 #3 0x00006f9737d9c800 __sigtramp_siginfo_2 (/usr/lib/libc.so.12+0x19c800)
 #4 0x00006f9741f41346 auto clang::format::WhitespaceManager::getNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int) const /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.h:267:36
 #5 0x00006f9741f41346 unsigned int clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int, unsigned int) const /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.h:305:44
 #6 0x00006f9741f41346 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.cpp:1075:42
 #7 0x00006f9741f4249c llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::CellDescription, void>::begin() /scratch/lang/clang/work/.buildlink/include/llvm/ADT/SmallVector.h:253:45
 #8 0x00006f9741f4249c llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::CellDescription, void>::end() /scratch/lang/clang/work/.buildlink/include/llvm/ADT/SmallVector.h:255:32
 #9 0x00006f9741f4249c llvm::SmallVector<clang::format::WhitespaceManager::CellDescription, 2u>::~SmallVector() /scratch/lang/clang/work/.buildlink/include/llvm/ADT/SmallVector.h:1175:24
#10 0x00006f9741f4249c clang::format::WhitespaceManager::CellDescriptions::~CellDescriptions() /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.h:194:10
#11 0x00006f9741f4249c clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.cpp:991:49
#12 0x00006f9741f42594 clang::format::WhitespaceManager::alignArrayInitializers() /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.cpp:974:33
#13 0x00006f9741f45239 clang::format::WhitespaceManager::generateReplacements() /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/WhitespaceManager.cpp:106:18
#14 0x00006f9741ee5ed4 std::_Rb_tree<clang::tooling::Replacement, clang::tooling::Replacement, std::_Identity<clang::tooling::Replacement>, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::begin() const /usr/include/g++/bits/stl_tree.h:1007:55
#15 0x00006f9741ee5ed4 std::set<clang::tooling::Replacement, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::begin() const /usr/include/g++/bits/stl_set.h:345:26
#16 0x00006f9741ee5ed4 clang::tooling::Replacements::begin() const /scratch/lang/clang/work/clang-13.0.1.src/include/clang/Tooling/Core/Replacement.h:278:56
#17 0x00006f9741ee5ed4 clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/Format.cpp:1706:59
#18 0x00006f9741f0ef99 llvm::SmallVectorBase<unsigned int>::size() const /scratch/lang/clang/work/.buildlink/include/llvm/ADT/SmallVector.h:70:32
#19 0x00006f9741f0ef99 clang::format::TokenAnalyzer::process() /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/TokenAnalyzer.cpp:101:49
#20 0x00006f9741ee581a clang::format::TokenAnalyzer::~TokenAnalyzer() /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/TokenAnalyzer.h:80:7
#21 0x00006f9741ee581a ~Formatter /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/Format.cpp:1668:7
#22 0x00006f9741ee581a clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda2'(clang::format::Environment const&)::operator()(clang::format::Environment const&) const (.isra.0) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/Format.cpp:2875:12
#23 0x00006f9741ee5941 std::_Function_handler<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&), clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda2'(clang::format::Environment const&)>::_M_invoke(std::_Any_data const&, clang::format::Environment const&) /usr/include/g++/bits/std_function.h:293:7
#24 0x00006f9741eec757 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/Format.cpp:2893:70
#25 0x00006f9741eed434 std::_Rb_tree<clang::tooling::Replacement, clang::tooling::Replacement, std::_Identity<clang::tooling::Replacement>, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::_Rb_tree_impl<std::less<clang::tooling::Replacement>, true>::_Rb_tree_impl(std::_Rb_tree<clang::tooling::Replacement, clang::tooling::Replacement, std::_Identity<clang::tooling::Replacement>, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::_Rb_tree_impl<std::less<clang::tooling::Replacement>, true>&&) /usr/include/g++/bits/stl_tree.h:701:4
#26 0x00006f9741eed434 std::_Rb_tree<clang::tooling::Replacement, clang::tooling::Replacement, std::_Identity<clang::tooling::Replacement>, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::_Rb_tree(std::_Rb_tree<clang::tooling::Replacement, clang::tooling::Replacement, std::_Identity<clang::tooling::Replacement>, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >&&) /usr/include/g++/bits/stl_tree.h:961:7
#27 0x00006f9741eed434 std::set<clang::tooling::Replacement, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >::set(std::set<clang::tooling::Replacement, std::less<clang::tooling::Replacement>, std::allocator<clang::tooling::Replacement> >&&) /usr/include/g++/bits/stl_set.h:231:7
#28 0x00006f9741eed434 clang::tooling::Replacements::Replacements(clang::tooling::Replacements&&) /scratch/lang/clang/work/clang-13.0.1.src/include/clang/Tooling/Core/Replacement.h:209:7
#29 0x00006f9741eed434 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) /scratch/lang/clang/work/clang-13.0.1.src/lib/Format/Format.cpp:2919:8
#30 0x00000001abe0f737  0xf737  0x8dc7
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-13.so      0x00006f973977a994 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 68
1  libLLVM-13.so      0x00006f97397787ca llvm::sys::RunSignalHandlers() + 81
2  libLLVM-13.so      0x00006f97397789b1 llvm::sys::unregisterHandlers() + 426
3  libc.so.12         0x00006f9737d9c800 __sigtramp_siginfo_2 + 0
4  libclang-cpp.so.13 0x00006f9741f41346 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) + 454
5  libclang-cpp.so.13 0x00006f9741f4249c clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) + 108
6  libclang-cpp.so.13 0x00006f9741f42594 clang::format::WhitespaceManager::alignArrayInitializers() + 174
7  libclang-cpp.so.13 0x00006f9741f45239 clang::format::WhitespaceManager::generateReplacements() + 441
8  libclang-cpp.so.13 0x00006f9741ee5ed4 std::_Rb_tree<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int>, std::pair<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int> const, unsigned int>, std::_Select1st<std::pair<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int> const, unsigned int> >, std::less<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int> >, std::allocator<std::pair<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int> const, unsigned int> > >::_M_erase(std::_Rb_tree_node<std::pair<std::pair<llvm::SmallVectorImpl<clang::format::AnnotatedLine*> const*, unsigned int> const, unsigned int> >*) + 1400
9  libclang-cpp.so.13 0x00006f9741f0ef99 clang::format::TokenAnalyzer::process() + 2105
10 libclang-cpp.so.13 0x00006f9741ee581a clang::format::cleanup(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef) + 5568
11 libclang-cpp.so.13 0x00006f9741ee5941 clang::format::cleanup(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef) + 5863
12 libclang-cpp.so.13 0x00006f9741eec757 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) + 748
13 libclang-cpp.so.13 0x00006f9741eed434 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) + 103
14 clang-format       0x00000001abe0f737 llvm::Error llvm::handleErrors<llvm::toString(llvm::Error)::'lambda'(llvm::ErrorInfoBase const&)>(llvm::Error, llvm::toString(llvm::Error)::'lambda'(llvm::ErrorInfoBase const&)&&) + 5775
15 clang-format       0x00000001abe08dc7 _init + 13799
```

### LINKED ISSUE #55493: [clang-format] `AlignArrayOfStructures` crashes with trailing comment
my clang-format file contains:

```yaml
AlignArrayOfStructures: Left
```

running clang-format crashes with:
```console
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x31)[0x7ff69a14af31]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0xee)[0x7ff69a148c6e]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(+0xe40466)[0x7ff69a14b466]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7ff698df2520]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(+0x2c74deb)[0x7ff6a2851deb]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format17WhitespaceManager35alignArrayInitializersLeftJustifiedEONS1_16CellDescriptionsE+0xe7)[0x7ff6a28517e7]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format17WhitespaceManager22alignArrayInitializersEjj+0x76)[0x7ff6a28502b6]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format17WhitespaceManager20generateReplacementsEv+0x176)[0x7ff6a284d246]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(+0x2c1dbad)[0x7ff6a27fabad]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format13TokenAnalyzer7processEv+0x376)[0x7ff6a2823246]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(+0x2c2aa71)[0x7ff6a2807a71]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format8internal8reformatERKNS0_11FormatStyleEN4llvm9StringRefENS5_8ArrayRefINS_7tooling5RangeEEEjjjS6_PNS0_23FormattingAttemptStatusE+0x8db)[0x7ff6a27f2aeb]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6format8reformatERKNS0_11FormatStyleEN4llvm9StringRefENS4_8ArrayRefINS_7tooling5RangeEEES5_PNS0_23FormattingAttemptStatusE+0x51)[0x7ff6a27f38c1]
clang-format-14[0x40b129]
clang-format-14[0x409335]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7ff698dd9d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7ff698dd9e40]
clang-format-14[0x406475]
```

the code in question is:
```c
std::array<pairs> foo()
{
    return { {
        { a, d },
        { b, e },
        { c, f }, // crash
    } };
}
```

removing the railing comment, the crash goes away:
```c
std::array<pairs> foo()
{
    return { {
        { a, d },
        { b, e },
        { c, f },
    } };
}
```

### LINKED ISSUE #68431: clang-format WhitespaceManager crash
Repro:

file:
```
static constexpr T v[] {
   { AAAAAAAAAAAAAAAAAAAAAAAAA::aaaaaaaaaaaaaaaaaaa, AAAAAAAAAAAAAAAAAAAAAAAAA::aaaaaaaaaaaaaaaaaaaaaaaa, 1, 0.000000000f, "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" },
};
```

.clang-format
```
AccessModifierOffset: -3
AlignAfterOpenBracket: Align
AlignArrayOfStructures: Left
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: true
AlignEscapedNewlinesLeft: false
AlignOperands: true
AlignTrailingComments:
  Kind: Always
  OverEmptyLines: 2
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: true
AlignConsecutiveShortCaseStatements:
  Enabled: true
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: false
BinPackArguments: true
BinPackParameters: true
BraceWrapping:
  AfterCaseLabel:         true
  AfterClass:             true
  AfterControlStatement:  true
  AfterEnum:              true
  AfterFunction:          true
  AfterNamespace:         true
  AfterObjCDeclaration:   true
  AfterStruct:            true
  AfterUnion:             false
  BeforeCatch:            true
  BeforeElse:             true
  BeforeLambdaBody:       true
  IndentBraces:           false
  SplitEmptyFunction:     false
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Custom
BreakBeforeTernaryOperators: true
BreakConstructorInitializers : BeforeColon
ColumnLimit: 120
CommentPragmas: '^ IWYU pragma:'
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 3
ContinuationIndentWidth: 3
Cpp11BracedListStyle: false
DerivePointerAlignment: false
DisableFormat: false
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: false
IndentCaseLabels: true
IndentWidth: 3
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: true
LambdaBodyIndentation: OuterScope
MacroBlockBegin: ''
MacroBlockEnd: ''
MaxEmptyLinesToKeep: 2
NamespaceIndentation: None
PackConstructorInitializers: Never
PenaltyBreakBeforeFirstCallParameter: 100
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyExcessCharacter: 10000
PointerAlignment: Left
ReflowComments: true
SortIncludes: false
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Never
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: true
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: true
SpacesInParentheses: true
SpacesInSquareBrackets: true
ObjCSpaceAfterProperty: true
ObjCSpaceBeforeProtocolList: true
Standard: Latest
TabWidth: 3
UseTab: Never

```

Callstack:
```
>	clang-format.exe!HandleAbort(int Sig) Line 419	C++
 	[External Code]	
 	clang-format.exe!llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::Change,void>::operator[](unsigned __int64 idx) Line 298	C++
 	clang-format.exe!clang::format::WhitespaceManager::getNetWidth<clang::format::WhitespaceManager::CellDescription *>(clang::format::WhitespaceManager::CellDescription * const & Start, clang::format::WhitespaceManager::CellDescription * const & End, unsigned int InitialSpaces) Line 285	C++
 	clang-format.exe!clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription *>(clang::format::WhitespaceManager::CellDescription * const & CellStart, clang::format::WhitespaceManager::CellDescription * const & CellStop, unsigned int InitialSpaces, unsigned int CellCount, unsigned int MaxRowCount) Line 324	C++
 	clang-format.exe!clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions && CellDescs) Line 1315	C++
 	clang-format.exe!clang::format::WhitespaceManager::alignArrayInitializers(unsigned int Start, unsigned int End) Line 1222	C++
 	clang-format.exe!clang::format::WhitespaceManager::alignArrayInitializers() Line 1206	C++
 	clang-format.exe!clang::format::WhitespaceManager::generateReplacements() Line 113	C++
 	clang-format.exe!clang::format::`anonymous namespace'::Formatter::analyze(clang::format::TokenAnnotator & Annotator, llvm::SmallVectorImpl<clang::format::AnnotatedLine *> & AnnotatedLines, clang::format::FormatTokenLexer & Tokens) Line 2391	C++
 	clang-format.exe!clang::format::TokenAnalyzer::process(bool SkipAnnotation) Line 132	C++
 	clang-format.exe!clang::format::internal::reformat::__l2::<lambda_10>::operator()(const clang::format::Environment & Env) Line 3673	C++
 	[External Code]	
 	clang-format.exe!clang::format::internal::reformat(const clang::format::FormatStyle & Style, llvm::StringRef Code, llvm::ArrayRef<clang::tooling::Range> Ranges, unsigned int FirstStartColumn, unsigned int NextStartColumn, unsigned int LastStartColumn, llvm::StringRef FileName, clang::format::FormattingAttemptStatus * Status) Line 3688	C++
 	clang-format.exe!clang::format::reformat(const clang::format::FormatStyle & Style, llvm::StringRef Code, llvm::ArrayRef<clang::tooling::Range> Ranges, llvm::StringRef FileName, clang::format::FormattingAttemptStatus * Status) Line 3731	C++
 	clang-format.exe!clang::format::format(llvm::StringRef FileName) Line 499	C++
 	clang-format.exe!main(int argc, const char * * argv) Line 631	C++
 	[External Code]	
```

### PR DESCRIPTION
**Pull request by owenca**
Fixed #54815.
Fixed #55269.
Fixed #55493.
Fixed #68431.

### CODE REVIEW

File: clang/lib/Format/WhitespaceManager.cpp [hunk 1]
```diff
@@ -1316,6 +1316,8 @@ void WhitespaceManager::alignArrayInitializersRightJustified(
         auto Offset = std::distance(Cells.begin(), CellIter);
         for (const auto *Next = CellIter->NextColumnElement; Next;
              Next = Next->NextColumnElement) {
+          if (RowCount >= CellDescs.CellCounts.size())
+            break;
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:1320]:
```suggestion
        for (const auto *Next = CellIter->NextColumnElement; Next && RowCount < CellDescs.CellCounts.size();
             Next = Next->NextColumnElement, ++RowCount) {
```
Maybe?

Then the `++RowCount` below must be removed.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/WhitespaceManager.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/WhitespaceManager.cpp:1320]: I intentionally made it the same as lines 1384-1385 below so that lines 1315-1323 would remain copy-pasted from lines 1380-1388. This will make future refactoring easier.

Comment (HazardyKnusperkeks) [reply clang/lib/Format/WhitespaceManager.cpp:1320]: I would change the other lines too. I think it's better to see the condition in the `for`, but it's your call.

Comment (owenca) [reply clang/lib/Format/WhitespaceManager.cpp:1320]: The same/similar code appeared twice in this file and once in the header file. If I were to refactor it, I might not use the same for-loop, so I'll leave it as is for now. (There are also much more cleanup that can be done with this option, but I don't know if it's worthwhile as it's so buggy even after @mydeveloperday limited it to matrices.)

**Comment by owenca** [comment]
We probably should backport it to 17.0.6. What do you all think? @tru

**Comment by tru** [comment]
> We probably should backport it to 17.0.6. What do you all think? @tru

Yep - seems like a good and small fix to have in 17.x

**Comment by tru** [comment]
@owenca I picked da1b1fba5cfd41521a840202d8cf4c3796c5e10b on top of the 17.x branch and my test case was not fixed, it still crashes in the same way as described in #72628

**Comment by owenca** [comment]
> @owenca I picked da1b1fba5cfd41521a840202d8cf4c3796c5e10b on top of the 17.x branch and my test case was not fixed, it still crashes in the same way as described in #72628

Thanks for trying it on 17.x. We can't backport it then.

**Comment by tru** [comment]
> Thanks for trying it on 17.x. We can't backport it then.

Any idea if there is another workaround or fix that we could do to target 17.x? 18 is still pretty far off and clang-format for 17 will soon be included in a lot of downstream tools. Happy to help out fixing it if you have any pointers.

**Review by rymiel — APPROVED** [review]
Thanks for doing this! There were probably dozens of duplicates of this same crash across multiple years, so this is great

**Comment by owenca** [comment]
> > Thanks for trying it on 17.x. We can't backport it then.
> 
> Any idea if there is another workaround or fix that we could do to target 17.x? 18 is still pretty far off and clang-format for 17 will soon be included in a lot of downstream tools. Happy to help out fixing it if you have any pointers.

My bad. #72628 was already "fixed" on 18 before this patch. Can you help bisect it?
