### PR TITLE
[CONCEPTS]Corrected comparison of constraints with out of line CTD

### LINKED ISSUE #61763: [clang-16 regression] Friend declaration of a constrained friend class inside of a class template causes compile error
```c++
#include <concepts>

template <class = void>
struct Foo {
    template <std::same_as<void> Param>
    friend struct Bar;
};

template struct Foo<>;

template <std::same_as<void> Param>
struct Bar {
};
```

Clang-16 and further reject this program with the following error message:
```c++
<source>:11:11: error: type constraint differs in template redeclaration
template <std::same_as<void> Param>
          ^
<source>:5:15: note: previous template declaration is here
    template <std::same_as<void> Param>
              ^
1 error generated.
Compiler returned: 1
```
Clang versions 11-15 work as expected, though.
Compiler Explorer link: https://godbolt.org/z/erGavP1za.

GCC also had a similar bug at some point: [93467](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93467).

### PR DESCRIPTION
**Pull request by erichkeane**
Out of line class template declaration specializations aren't created at the time they have their template arguments checked, so we previously weren't doing any amount of work to substitute the constraints before comparison. This resulted in the out of line definition's difference in 'depth' causing the constraints to compare differently.

This patch corrects that.  Additionally, it handles ClassTemplateDecl when collecting template arguments.

Fixes: #61763

### CODE REVIEW

**Comment by erichkeane** [comment]
I did a force-push with the hope that it'll get the code-formatter to start recognizing what is going on, it seems to be doing some wacky things?

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -346,6 +351,11 @@ MultiLevelTemplateArgumentList Sema::getTemplateInstantiationArgs(
     CurDecl = Response::UseNextDecl(ND).NextDecl;
   }
 
+  if (!ND) {
+    assert(DC);
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:355]: Does this assertion makes sense? If `ND` and `DC` both were null, the first assertion in this function would have failed already.

File: clang/include/clang/Sema/Sema.h [hunk 2]
```diff
@@ -8615,8 +8604,48 @@ class Sema final {
     TPL_TemplateParamsEquivalent,
   };
 
+  // A struct to represent the 'new' declaration, which is either itself just
+  // the named decl, or the important information we need about it in order to
+  // do constraint comparisions.
```
Comment (Fznamznon) [inline clang/include/clang/Sema/Sema.h:8609]:
```suggestion
  // do constraint comparisons.
```

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:355]: Probably not necessary, I'll remove it.  I think I added that top assert later on.

**Comment by erichkeane** [comment]
My main two reviewers are away this week, and the review I got caught the 'dumb' stuff I'm likely to miss anyway.  So I'm going to merge this to give it more time to bake, and count on RAC.
