### PR TITLE
[Clang] restrict use of attribute names reserved by the C++ standard

### LINKED ISSUE #92196: No diagnostic is reported for illegal macro definitions such as "noreturn" and "carries_dependency"
Consider the testcase like that:
```cpp
#define override 1 
#define noreturn 2
#define final 3 
#define carries_dependency 4

int foo(int a)
{
  return (a == override + noreturn + final + carries_dependency);
}
```

When compiling it with clang compiler, I see that the diagnostic is issued for 2 out 4 macros (override and final), which is inconsistent.
 
I could see the argument why no error should be reported. I could see an argument why all four errors should be reported. But not reporting diagnostic only for 2 out of 4 macros that falls into the same category is suprising.

(note: the same behavior happens with c++14, c++17, c++20 standard)

```
clang -c -Wpedantic -Wall -std=c++11 test.cpp
test.cpp:2:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
#define override 1
        ^
test.cpp:4:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
#define final 3
        ^
2 warnings generated.
=======================
```

On one hand, https://eel.is/c++draft/macro.names#2 says:
"A translation unit shall not #define or #undef names lexically identical to keywords, to the identifiers listed in Table 4, or to the attribute-tokens described in [dcl.attr], except that the names likely and unlikely may be defined as function-like macros ([cpp.replace]).
"Table 4" is: "final import module override".
Redefining attribute-tokens is also not allowed.
https://eel.is/c++draft/dcl.attr; "carries_dependency" and "noreturn" are both in there (attribute tokens).

The use of the language "shall not" means that the program is ill-formed and requires a diagnostic, according to cppreference.

On the other hand, it might be considered as and undefined bahavior.
There is a 10 years old thread on llvm.org explaining why error should not be reported.
[However, it doesn't address my inconsistency question]
https://lists.llvm.org/pipermail/cfe-dev/2013-June/030283.html

Summary:
If Clang diagnoses a redefinition some attribute names such as "final" and "override", then failing to do so for "carries_dependency" and "noreturn" seems like a Clang bug.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #92196

https://eel.is/c++draft/macro.names#2
> A translation unit shall not #define or #undef names lexically identical to keywords, to the identifiers listed in Table [4](https://eel.is/c++draft/lex.name#tab:lex.name.special), or to the [attribute-token](https://eel.is/c++draft/dcl.attr.grammar#nt:attribute-token)s described in [[dcl.attr]](https://eel.is/c++draft/dcl.attr), except that the names likely and unlikely may be defined as function-like macros ([[cpp.replace]](https://eel.is/c++draft/cpp.replace))[.](https://eel.is/c++draft/macro.names#2.sentence-1)

### CODE REVIEW

File: clang/lib/Lex/PPDirectives.cpp [hunk 1]
```diff
@@ -177,6 +177,26 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
   return false;
 }
 
+static bool isReservedAttrName(Preprocessor &PP, IdentifierInfo *II) {
```
Comment (zyn0217) [inline clang/lib/Lex/PPDirectives.cpp:180]: Can you reference some wording here?
Are those hardcoded names sufficient?

File: clang/lib/Lex/PPDirectives.cpp [hunk 2]
```diff
@@ -177,6 +177,26 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
...
+  const LangOptions &Lang = PP.getLangOpts();
+  const StringRef Name = II->getName();
+
+  if (Lang.CPlusPlus26)
+    return Name == "indeterminate";
+  if (Lang.CPlusPlus23)
+    return Name == "assume";
```
Comment (zwuis) [inline clang/lib/Lex/PPDirectives.cpp:187]: It seems that `#define assume` will not trigger diagnostic in C++26. Do I misunderstand this code?

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: From my, attribute names aren't typical language keywords, and only a specific set defined by the standard should be disallowed. For example, `likely` and `unlikely` should be permitted. Reusing attribute parsing doesn't seem appropriate here. I haven't found a predefined list of standard attributes; if there is one, I would appreciate it if you could direct me to it. Thanks

Comment (cor3ntin) [reply clang/lib/Lex/PPDirectives.cpp:180]: `likely` is reserved, `likely()` is not.
Also, as we support attributes in older language modes as extensions so we should take that into account.
Does C has similar restrictions?

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: > Can we tablegen that somehow?

@cor3ntin Oke, I'll check...

File: clang/lib/Lex/PPDirectives.cpp (hunk 2 above)
Comment (philnik777) [reply clang/lib/Lex/PPDirectives.cpp:187]: `Lang.CPlusPlus23` is set when the version is at least C++23.

Comment (zwuis) [reply clang/lib/Lex/PPDirectives.cpp:187]: > It seems that `#define assume` will not trigger diagnostic in C++26.

I mean, control flow will reach line 185 and check if the name is `"indeterminate"` only, not check `"assume"`.

I think it shoule be
```cpp
if (Lang.CPlusPlus26 && Name == "indeterminate")
  return true;
```

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:187]: I'll revise this and add a test to cover this case.

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: @cor3ntin  The [Attr.td](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/Attr.td) file contain some details about attributes. I'm uncertain whether this file is sufficient for our case or if we need to define a new one...

Comment (AaronBallman) [reply clang/lib/Lex/PPDirectives.cpp:180]: > Does C has similar restrictions?

No, C has no such restrictions.

File: clang/test/Preprocessor/macro-reserved-attrs.cpp [hunk 3]
```diff
@@ -0,0 +1,33 @@
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx11 -pedantic -std=c++11 %s
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx14 -pedantic -std=c++14 %s
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx17 -pedantic -std=c++17 %s
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx20 -pedantic -std=c++20 %s
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx23 -pedantic -std=c++23 %s
+// RUN: %clang_cc1 -fsyntax-only -verify=expected,cxx26 -pedantic -std=c++26 %s
+
+#define noreturn 1           // cxx11-warning {{keyword is hidden by macro definition}}
```
Comment (AaronBallman) [inline clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: Please also add test cases for `#undef` of the name when it's not currently defined as a macro, as that's also undefined behavior. (@ldionne @jwakely any interest in an LWG issue over this? It's harmless to do `#undef noreturn` or whatever because these identifiers aren't macros to begin with; and if they were, the user hit the UB already.)

File: clang/test/Preprocessor/macro-reserved-attrs.cpp [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+#undef noreturn
+
+#define carries_dependency 1 // cxx11-warning {{keyword is hidden by macro definition}}
```
Comment (AaronBallman) [inline clang/test/Preprocessor/macro-reserved-attrs.cpp:11]: You should also have a test case where the macro is defined without an expansion.

File: clang/test/Preprocessor/macro-reserved-attrs.cpp [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+#undef nodiscard
+
+#define no_unique_address 1  // cxx20-warning {{keyword is hidden by macro definition}}
+#undef no_unique_address
+
+#define assume 1             // cxx23-warning {{keyword is hidden by macro definition}}
+#undef assume
+
+#define indeterminate 1      // cxx26-warning {{keyword is hidden by macro definition}}
+#undef indeterminate
```
Comment (AaronBallman) [inline clang/test/Preprocessor/macro-reserved-attrs.cpp:33]: Please add test cases that show we diagnose `#define likely` but not `#define likely()` (and same for `unlikely`).

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (AaronBallman) [inline clang/lib/Lex/PPDirectives.cpp:180]: What should the behavior be with `-nostdlib`? Should these actually be reserved in this case (given that the restriction is under "library-wide requirements")?

**Review by AaronBallman — COMMENTED** [review]
I would expect these to be controlled by `-Wreserved-identifier` rather than keyword hiding (these are not keywords), probably in a new group like `-Wreserved-attribute-identifier`, WDYT?

SourceGraph's backend is currently falling over, so I don't have links to share, but I did see examples of `#define likely` in projects like MongoDB and `#define assume` in a fair number of projects. I'm slightly worried about the amount of noise this will generate in practice -- have you tried running these changes over a large corpus of C++ code?

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (Sirraide) [reply clang/lib/Lex/PPDirectives.cpp:180]: > The [Attr.td](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/Attr.td) file contain some details about attributes. I'm uncertain whether this file is sufficient for our case or if we need to define a new one...

From what I can tell, you’ll have to extend ClangAttrEmitter and introduce a new flag in `Attr.td` that is set for every standard C++ attribute (e.g. `CXX11NoReturn`, but not `C11NoReturn` or `NoReturn`).

File: clang/test/Preprocessor/macro-reserved-attrs.cpp (hunk 5 above)
Comment (Sirraide) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:33]: Test cases for some of the others defined as function-like macros would be nice too, which we should diagnose (except for `likely` and `unlikely` ofc).

File: clang/test/Preprocessor/macro-reserved-attrs.cpp (hunk 3 above)
Comment (jwakely) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: I think that rule is there so that implementations can do:

`#define noreturn _Some_unspecified_noreturn_feature`

Comment (philnik777) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: How would that work? `int noreturn = 1;` is valid code AFAICT.

Comment (jwakely) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: What benefit would there be in allowing users to undef them? Just reducing the amount of UB it's possible to have?

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (philnik777) [reply clang/lib/Lex/PPDirectives.cpp:180]: `-nostdlib` doesn't imply that you don't have a standard library, it just implies that you don't use the system-provided one, so I'd say it shouldn't influence the diagnostic. If you don't care you can just disable the diagnostic still, right?

File: clang/test/Preprocessor/macro-reserved-attrs.cpp (hunk 3 above)
Comment (jwakely) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: > How would that work? `int noreturn = 1;` is valid code AFAICT.

Yes, for attributes, that's true. For keywords it's not though.

The rule was changed between C++03 and C++11 to include #undef, I don't know why though.

I still don't see any advantage in allowing users to `#undef noreturn`.

Comment (jwakely) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: Yes, EB seems like a good choice here. It could be erroneously ignored, so if it's not diagnosed it has to be harmless.

File: clang/lib/Lex/PPDirectives.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: @Sirraide @AaronBallman In the context of avoiding hardcoded names., I noticed there's an existing emitter that allows getting `AttrKind` using a string name. Is it okay to use this in this case, or would it be better to add a new emitter that will emit attributes with the new _flag-controlling_ names from the C++ standard?

https://github.com/llvm/llvm-project/blob/9edd998e10fabfff067b9e6e5b044f85a24d0dd5/clang/utils/TableGen/ClangAttrEmitter.cpp#L4875

currenly, it's related to `Sema`, but it might need to be moved to `Basic`...

https://github.com/llvm/llvm-project/blob/9edd998e10fabfff067b9e6e5b044f85a24d0dd5/clang/include/clang/Sema/CMakeLists.txt#L11-L14

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: @Sirraide @AaronBallman @cor3ntin In the context of avoiding hardcoded names., I noticed there's an existing emitter that allows getting `AttrKind` using a string name. Is it okay to use this in this case, or would it be better to add a new emitter that will emit attributes with the new _flag-controlling_ names from the C++ standard?

https://github.com/llvm/llvm-project/blob/9edd998e10fabfff067b9e6e5b044f85a24d0dd5/clang/utils/TableGen/ClangAttrEmitter.cpp#L4875

currenly, it's related to `Sema`, but it might need to be moved to `Basic`...

https://github.com/llvm/llvm-project/blob/9edd998e10fabfff067b9e6e5b044f85a24d0dd5/clang/include/clang/Sema/CMakeLists.txt#L11-L14

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: @AaronBallman Thanks. Just to confirm, are future attribute names valid in previous versions? For instance, can `C++11` use the `deprecated` attribute from `C++14`?

Comment (philnik777) [reply clang/lib/Lex/PPDirectives.cpp:180]: Yes, that's a supported extension.

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: The reason I asked is that I recall clang has a predefined macro, `__has_cpp_attribute`, which relies on `hasAttribute`. This function uses a list of existing attributes generated from `Attr.td` for different _`Syntax`_. Should attributes currently defined in clang (for example, `indeterminate` isn’t defined yet) be disallowed, or should all cpp attribute names from the standard be considered?

--- 

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Lex/PPMacroExpansion.cpp#L1915-L1920

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L31

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L26

```
...
if (ScopeName == "") {
  return llvm::StringSwitch<int>(Name)
    .Case("noreturn", 200809)
    .Case("assume", 202207)
    .Case("carries_dependency", 200809)
    .Case("deprecated", 201309)
    .Case("fallthrough", 201603)
    .Case("likely", 201803)
    .Case("no_unique_address", true && ( Target.getCXXABI().isItaniumFamily() ) ? 201803 : 0)
    .Case("unlikely", 201803)
    .Case("maybe_unused", 201603)
    .Case("nodiscard", 201907)
    .Default(0);
...
```

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: The reason I asked is that I recall clang has a predefined macro, `__has_cpp_attribute`, which relies on `hasAttribute`. This function uses a list of existing attributes generated from `Attr.td` for different _`Syntax`_. Should attributes currently defined in clang (for example, `indeterminate` isn’t defined yet) be disallowed _(maybe `hasAttribute` could be reused)_, or should all cpp attribute names from the standard be considered _(even if Clang doesn’t fully support it)_?

--- 

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Lex/PPMacroExpansion.cpp#L1915-L1920

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L31

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L26

```
...
if (ScopeName == "") {
  return llvm::StringSwitch<int>(Name)
    .Case("noreturn", 200809)
    .Case("assume", 202207)
    .Case("carries_dependency", 200809)
    .Case("deprecated", 201309)
    .Case("fallthrough", 201603)
    .Case("likely", 201803)
    .Case("no_unique_address", true && ( Target.getCXXABI().isItaniumFamily() ) ? 201803 : 0)
    .Case("unlikely", 201803)
    .Case("maybe_unused", 201603)
    .Case("nodiscard", 201907)
    .Default(0);
...
```

--- 

Should this one handle the standard versions too?
https://github.com/llvm/llvm-project/blob/837ee5b46a5f7f898f0de7e46a19600b896a0a1f/clang/lib/Parse/ParseDeclCXX.cpp#L4689-L4708

Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:180]: @philnik777 @AaronBallman The reason I asked is that I recall clang has a predefined macro, `__has_cpp_attribute`, which relies on `hasAttribute`. This function uses a list of existing attributes generated from `Attr.td` for different _`Syntax`_. Should attributes currently defined in clang (for example, `indeterminate` isn’t defined yet) be disallowed _(maybe `hasAttribute` could be reused)_, or should all cpp attribute names from the standard be considered _(even if Clang doesn’t fully support it)_?

--- 

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Lex/PPMacroExpansion.cpp#L1915-L1920

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L31

https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Basic/Attributes.cpp#L26

```
...
if (ScopeName == "") {
  return llvm::StringSwitch<int>(Name)
    .Case("noreturn", 200809)
    .Case("assume", 202207)
    .Case("carries_dependency", 200809)
    .Case("deprecated", 201309)
    .Case("fallthrough", 201603)
    .Case("likely", 201803)
    .Case("no_unique_address", true && ( Target.getCXXABI().isItaniumFamily() ) ? 201803 : 0)
    .Case("unlikely", 201803)
    .Case("maybe_unused", 201603)
    .Case("nodiscard", 201907)
    .Default(0);
...
```

--- 

Should this one handle the standard versions too?
https://github.com/llvm/llvm-project/blob/837ee5b46a5f7f898f0de7e46a19600b896a0a1f/clang/lib/Parse/ParseDeclCXX.cpp#L4689-L4708

Sorry for all the questions., I just want to ensure the flow is clear and duplicates won't be added...

Comment (erichkeane) [reply clang/lib/Lex/PPDirectives.cpp:180]: I concur with Aaron.  The point of this restriction is to permit the library to use attributes without the risk of someone macroing them away.  

I ALSO think that macroing away non-standards attributes should be perfectly fine, so we should only have this diagnostic for standards attributes.  I THINK we have some infrastructure already to detect those (`__has_cpp_attribute` I think also returns non-zero for non standards attributes?  But perhaps we can re-use the fact that the standards ones use a date?)?

Comment (erichkeane) [reply clang/lib/Lex/PPDirectives.cpp:180]: > Because we don't support any non-standard attributes without a vendor namespace (e.g., we don't support `[[foo]]` as an extension, it needs to have some sort of prefix like `[[gnu::foo]]` or `[[clang::foo]]`), I was thinking we could rely on that.
> 
> However, it might also make sense to just add a bit to the `Spelling` in `Attr.td` to say "this is a standard spelling for the attribute" (which side-steps things like `nodiscard` vs `warn_unused_result`)?

Ah, yeah, we could just check if it has a non-namespaced standard spelling, thats probably more than enough.  An additional bit isn't really necessary at that point (since we effectively already have it).

Comment (AaronBallman) [reply clang/lib/Lex/PPDirectives.cpp:180]: Maybe? I think they absolutely should, but those names are not portable to other compilers.

(FWIW, I like what the C committee did:

6.7.13.1p4:
> In all aspects of the language, a standard attribute specified by this document as an identifier `attr`
and an identifier of the form `__attr__` shall behave the same when used as an attribute token,
except for the spelling.

so standard library vendors can reliably use the underscored names under an existing well-known identifier reservation rule without sacrificing portability.)

Comment (philnik777) [reply clang/lib/Lex/PPDirectives.cpp:180]: Would it make sense to split this into (1) a diagnostic about a name being reserved and (2) a diagnostic about a name being reserved in a future standard?

Comment (jwakely) [reply clang/lib/Lex/PPDirectives.cpp:180]: > I think they absolutely should, but those names are not portable to other compilers.

They _should_ be. GCC has always accepted `__attribute__((__foo__))` as well as the `foo` spelling, and uses the same rule for `[[...]]` attributes. I assume Intel compilers do the same for compatibility.

Maybe MSVC doesn't? Seems like something they might support if asked to though.

Comment (AaronBallman) [reply clang/lib/Lex/PPDirectives.cpp:180]: They don't support it: https://godbolt.org/z/9dxshKxj9

> Especially if that rule has been standardized by C.

Yeah, I should probably write a paper for WG21 proposing this.

Comment (erichkeane) [reply clang/lib/Lex/PPDirectives.cpp:180]: Hmm.... could any such paper remove the above text from `Macro.names`?  It would be nice to be able to abandon this patch as a result.  I could see if this is something we could get through EWG as a DR.

Comment (AaronBallman) [reply clang/lib/Lex/PPDirectives.cpp:180]: That's my intent; I'll send around the paper to you and @jwakely for opinions (I'm most of the way done drafting it). If we think this idea has legs in WG21, then I agree we should hold off on landing this patch as it may be unnecessary.

File: clang/test/Preprocessor/macro-reserved-attrs.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/test/Preprocessor/macro-reserved-attrs.cpp:8]: > Maybe this diagnostic should be a normal warning not an extension?

I agree -- I recommended we put this under `-Wreserved-identifier` (though probably in a new warning group) which is a `Warning` rather than under `-Wkeyword-macro` which is an `Extension`.

**Comment by AaronBallman** [comment]
FWIW, LWG is still discussing the issue while trying to prioritize it, and it's got a reasonable amount of discussion on it. I think we should hold off making any changes or landing this patch until we have a better sense of whether LWG is going to refine this restriction or not.

**Comment by a-tarasyuk** [comment]
@AaronBallman oke, thanks for the update.

File: clang/lib/Lex/PPDirectives.cpp [hunk 6]
```diff
@@ -177,6 +180,20 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
...
 }
 
+static bool isReservedCXXAttributeName(Preprocessor &PP, IdentifierInfo *II) {
+  const LangOptions &Lang = PP.getLangOpts();
+  if (Lang.CPlusPlus &&
+      hasAttribute(AttributeCommonInfo::Syntax::AS_CXX11, /*Scope*/ nullptr, II,
+                   PP.getTargetInfo(), Lang) > 0) {
+    AttributeCommonInfo::Kind AttrKind = AttributeCommonInfo::getParsedKind(
+        II, /*Scope*/ nullptr, AttributeCommonInfo::Syntax::AS_CXX11);
+    return !((AttrKind == AttributeCommonInfo::Kind::AT_Likely ||
```
Comment (erichkeane) [inline clang/lib/Lex/PPDirectives.cpp:190]: I'm kinda confused how this works, can you explain it here?  Why the likely/unlikely exception here?

**Review by erichkeane — COMMENTED** [review]
I think the patch itself is ready, but I want to see what LWG decides to do here.

File: clang/lib/Lex/PPDirectives.cpp (hunk 6 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:190]: The names `likely()` and `unlikely()` are not reserved, as noted [here](https://github.com/llvm/llvm-project/pull/106036#discussion_r1730709436). Therefore, using these names with `()` should not trigger a warning.

```cpp

#define likely 1 // expected-warning {{likely is a reserved attribute identifier}}
#undef likely    // expected-warning {{likely is a reserved attribute identifier}}

#define unlikely 1 // expected-warning {{unlikely is a reserved attribute identifier}}
#undef unlikely    // expected-warning {{unlikely is a reserved attribute identifier}}

#define likely()   // ok
#define unlikely() // ok
```

Comment (erichkeane) [reply clang/lib/Lex/PPDirectives.cpp:190]: Got it, thanks!  Forgot about that/didn't recall it.

**Comment by erichkeane** [comment]
I saw this got updates over break.  Did LWG make its decision already?  Are you expecting re-review? I didn't see anything go across my emails about LWG, but I could definitely have missed it.

**Comment by AaronBallman** [comment]
> I saw this got updates over break. Did LWG make its decision already? Are you expecting re-review? I didn't see anything go across my emails about LWG, but I could definitely have missed it.

The LWG issue is still open: https://cplusplus.github.io/LWG/issue4149 but doesn't seem to be under active discussion any longer. My reading of the reflector thread is that my suggested approach is not quite correct. Consider a case like:
```
#define maybe_unused 12

#include <algorithm>
```
where the namespace isn't going to be declared (aka header not included) at the time the `#define` happens. We could aim for a perfect analysis here, but it gets pretty complicated, so I am leaning towards always issuing a `-Wreserved-attribute-identifier` warning when we see the `#define` of a standard attribute name. It does mean false positives are possible, but the amount of C++ code that does not include a standard library header anywhere in the TU *and* defines standard attribute identifiers as macro names is hopefully quite small.

WDYT @erichkeane?

**Comment by erichkeane** [comment]
> > I saw this got updates over break. Did LWG make its decision already? Are you expecting re-review? I didn't see anything go across my emails about LWG, but I could definitely have missed it.
> 
> The LWG issue is still open: https://cplusplus.github.io/LWG/issue4149 but doesn't seem to be under active discussion any longer. My reading of the reflector thread is that my suggested approach is not quite correct. Consider a case like:
> 
> ```
> #define maybe_unused 12
> 
> #include <algorithm>
> ```
> 
> where the namespace isn't going to be declared (aka header not included) at the time the `#define` happens. We could aim for a perfect analysis here, but it gets pretty complicated, so I am leaning towards always issuing a `-Wreserved-attribute-identifier` warning when we see the `#define` of a standard attribute name. It does mean false positives are possible, but the amount of C++ code that does not include a standard library header anywhere in the TU _and_ defines standard attribute identifiers as macro names is hopefully quite small.
> 
> WDYT @erichkeane?

Right part of the point is that the rule is SUPPOSED to protect against that case, and frankly, doesn't give a rip about the alternative.  The standard doesn't REALLY care if you put that define AFTER all STL header includes, only if it is before, so trying to determine it at declaration time isn't really possible.

We discussed it offline: And I think making this diagnostic, "IF you use the STL and have this define, UB", with an  easy enough to disable warning flag is about as good as we can get here.  Trying to intuit whether the person is EVER going to use the STL in the TU is a fools errand.

File: clang/lib/Sema/Sema.cpp [hunk 7]
```diff
@@ -159,6 +159,22 @@ class SemaPPCallbacks : public PPCallbacks {
...
+  void DiagnoseReservedAttributeName(const Token &MacroNameTok,
+                                     const MacroInfo *MI) {
+    IdentifierInfo *II = MacroNameTok.getIdentifierInfo();
+    if (II == nullptr || MI == nullptr)
+      return;
+
+    if (S) {
+      SourceManager &SM = S->getSourceManager();
+      SourceLocation Loc = MacroNameTok.getLocation();
+      if (SM.isInSystemHeader(Loc) || SM.getBufferName(Loc) == "<built-in>")
```
Comment (zygoloid) [inline clang/lib/Sema/Sema.cpp:171]:
```suggestion
      if (SM.isInSystemHeader(Loc) || SM.isWrittenInBuiltinFile(Loc))
```

**Review by zygoloid — COMMENTED** [review]
> We discussed it offline: And I think making this diagnostic, "IF you use the STL and have this define, UB", with an easy enough to disable warning flag is about as good as we can get here. Trying to intuit whether the person is EVER going to use the STL in the TU is a fools errand.

Could we collect a list on `Sema` of the directives that we would have diagnosed if `std` were already declared, and then produce the diagnostics at the point where we see the first declaration of the `std` namespace? That seems like it could be relatively straightforward.

**Comment by erichkeane** [comment]
> > We discussed it offline: And I think making this diagnostic, "IF you use the STL and have this define, UB", with an easy enough to disable warning flag is about as good as we can get here. Trying to intuit whether the person is EVER going to use the STL in the TU is a fools errand.
> 
> Could we collect a list on `Sema` of the directives that we would have diagnosed if `std` were already declared, and then produce the diagnostics at the point where we see the first declaration of the `std` namespace? That seems like it could be relatively straightforward.

I had considered this, but frankly, I think that ends up with a bit of a chicken/egg problem, and quite a bit of extra work for something that affects basically no one.

Part of the problem is figuring out WHEN a library causes the restrictions in macro.names.  Paragraph 2 (via CWG issue, and, IMO, by the rights that the Library section of the wording have) states that a TU that includes a standard library header shall not #define/#undef/etc. 

SO at that point, you'd have to decide WHAT makes a standard library header sufficiently enough to opt its users into the `macro.names` restriction sufficiently.  OR more importantly, what sort of `not quite an Standard Library header, but made to look enough like it to be usable by my project` tests we could have to exclude this properly.  So things like, "has namespace std" or "has a name that matches one of the StdLib Headers" I think doesn't really qualify as a proper heuristic to the point where it would be correct-enough to be worth the effort.

The only one who knows whether their library _IS_ an Standard Library Header for this purpose, so the 'right' way to do this would be some sort of opt-in (via an attribute, config file, etc).  AND if they're doing that, perhaps the StdLib should be the one enforcing this rule in the first place, via #ifdefs and #warning.    However, this would be awful for various reasons.

We COULD assume that anything that declared a namespace `std` and came from system headers would be 'standard library enough' for our uses, but again, I find myself wondering "is the juice worth the squeeze" in figuring this out.

In the end, I came down on, "The one who best knows that they aren't using any headers from the standard library are the ones who wrote the code, so they should be the ones who assert one way or another via a flag".  And the -Wno flag seems to be as good as any.

I Strongly suspect that any effort to recognize an StdLib header is going to be fairly wasted, and likely not as accurate as "always assume they are going to use the Standard Library with this file... somewhere".

**Comment by zygoloid** [comment]
Oh, I see, you're suggesting we remove the `getStdNamespace` check from this PR. Yeah, I think that's reasonable.

But I'd somewhat question whether this PR and warning really has anything to do with the attribute names being "reserved" at that point -- we're not checking whether they're reserved or not, and it really doesn't matter. Warning on a `#define` that clobbers the name of a standard attribute is just generally a good thing to do, regardless of whether you're using the standard library.

**Comment by erichkeane** [comment]
> Oh, I see, you're suggesting we remove the `getStdNamespace` check from this PR. Yeah, I think that's reasonable.

Yep, that is my suggestion, sorry I was insufficiently clear.

> But I'd somewhat question whether this PR and warning really has anything to do with the attribute names being "reserved" at that point -- we're not checking whether they're reserved or not, and it really doesn't matter. Warning on a `#define` that clobbers the name of a standard attribute is just generally a good thing to do, regardless of whether you're using the standard library.

I agree with this 100%.  The link to the 'reserved by the standard' is I think a good additional justification.

I think the proposal, complaining about these as reserved, is a good idea/good patch.  BUT I think getting caught up in the "well, when is it technically NOT UB" is a waste of time, given that the warning is a good idea even without that justification.

**Comment by AaronBallman** [comment]
> > Oh, I see, you're suggesting we remove the `getStdNamespace` check from this PR. Yeah, I think that's reasonable.
> 
> Yep, that is my suggestion, sorry I was insufficiently clear.
> 
> > But I'd somewhat question whether this PR and warning really has anything to do with the attribute names being "reserved" at that point -- we're not checking whether they're reserved or not, and it really doesn't matter. Warning on a `#define` that clobbers the name of a standard attribute is just generally a good thing to do, regardless of whether you're using the standard library.
> 
> I agree with this 100%. The link to the 'reserved by the standard' is I think a good additional justification.
> 
> I think the proposal, complaining about these as reserved, is a good idea/good patch. BUT I think getting caught up in the "well, when is it technically NOT UB" is a waste of time, given that the warning is a good idea even without that justification.

I think the warning is justified even without a standard library header being included, but I also wonder if that means putting this under `-Wreserved-identifier` is the wrong home and maybe this is a `-Wattributes` warning group instead. We could reword the diagnostic to something along the lines of "macro name conflicts with the name of a %select{vendor attribute prefix|standard attribute|attribute name}0" and we warn on all three of these cases:
```
#define msvc 12 // conflicts with [[msvc::no_unique_address]]
#define annotate 12 // conflicts with [[clang::annotate]]
#define nodiscard 12 // conflicts with [[nodiscard]]
```
WDYT?

**Comment by erichkeane** [comment]
> > > Oh, I see, you're suggesting we remove the `getStdNamespace` check from this PR. Yeah, I think that's reasonable.
> > 
> > 
> > Yep, that is my suggestion, sorry I was insufficiently clear.
> > > But I'd somewhat question whether this PR and warning really has anything to do with the attribute names being "reserved" at that point -- we're not checking whether they're reserved or not, and it really doesn't matter. Warning on a `#define` that clobbers the name of a standard attribute is just generally a good thing to do, regardless of whether you're using the standard library.
> > 
> > 
> > I agree with this 100%. The link to the 'reserved by the standard' is I think a good additional justification.
> > I think the proposal, complaining about these as reserved, is a good idea/good patch. BUT I think getting caught up in the "well, when is it technically NOT UB" is a waste of time, given that the warning is a good idea even without that justification.
> 
> I think the warning is justified even without a standard library header being included, but I also wonder if that means putting this under `-Wreserved-identifier` is the wrong home and maybe this is a `-Wattributes` warning group instead. We could reword the diagnostic to something along the lines of "macro name conflicts with the name of a %select{vendor attribute prefix|standard attribute|attribute name}0" and we warn on all three of these cases:
> 
> ```
> #define msvc 12 // conflicts with [[msvc::no_unique_address]]
> #define annotate 12 // conflicts with [[clang::annotate]]
> #define nodiscard 12 // conflicts with [[nodiscard]]
> ```
> 
> WDYT?

First, I think this needs its OWN warning group, as I can see justification for disabling just this.

Second, I think that the 'standard' attribute interference is a level of severity HIGHER than the others thanks to being in the standard (and thus, perhaps, likely more to be used/interfered with).

Third: DOES annotate conflict with attribute annotate?  Isn't that a function/would have to be a function macro?

Fourth: I think the 'reserved name' has a level of gravitas/concreteness that makes the diagnostic more meaningful/immediately obvious to folks.  A diagnostic of, "This name you chose for your macro might make this attribute no workie" yields "Yeah, but i wont use that so I'm ok".  A diagnostic of, "This name is UB because the standard reserves it!" yields a level of pause/consideration that we otherwise wouldn't get.

SO I think the diagnostic being associated with it being reserved is COMPLETELY valid/justifiable.  I think "this is a bad idea, UB or not" is a reason to not try at all to suppress this if we think you're not ACTUALLY breaking the rule (by not including an StdLib header).

**Comment by AaronBallman** [comment]
> > > > Oh, I see, you're suggesting we remove the `getStdNamespace` check from this PR. Yeah, I think that's reasonable.
> > > 
> > > 
> > > Yep, that is my suggestion, sorry I was insufficiently clear.
> > > > But I'd somewhat question whether this PR and warning really has anything to do with the attribute names being "reserved" at that point -- we're not checking whether they're reserved or not, and it really doesn't matter. Warning on a `#define` that clobbers the name of a standard attribute is just generally a good thing to do, regardless of whether you're using the standard library.
> > > 
> > > 
> > > I agree with this 100%. The link to the 'reserved by the standard' is I think a good additional justification.
> > > I think the proposal, complaining about these as reserved, is a good idea/good patch. BUT I think getting caught up in the "well, when is it technically NOT UB" is a waste of time, given that the warning is a good idea even without that justification.
> > 
> > 
> > I think the warning is justified even without a standard library header being included, but I also wonder if that means putting this under `-Wreserved-identifier` is the wrong home and maybe this is a `-Wattributes` warning group instead. We could reword the diagnostic to something along the lines of "macro name conflicts with the name of a %select{vendor attribute prefix|standard attribute|attribute name}0" and we warn on all three of these cases:
> > ```
> > #define msvc 12 // conflicts with [[msvc::no_unique_address]]
> > #define annotate 12 // conflicts with [[clang::annotate]]
> > #define nodiscard 12 // conflicts with [[nodiscard]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > WDYT?
> 
> First, I think this needs its OWN warning group, as I can see justification for disabling just this.

Agreed, I didn't mean to imply otherwise, I was speaking about the top-level umbrella (sorry for the confusion).

> Second, I think that the 'standard' attribute interference is a level of severity HIGHER than the others thanks to being in the standard (and thus, perhaps, likely more to be used/interfered with).

I think the problem is the same regardless of whether the attribute is a standard attribute or a vendor attribute -- either way, redefining the meaning of something known to the implementation seems worth of letting the user know about.

> Third: DOES annotate conflict with attribute annotate? Isn't that a function/would have to be a function macro?

Ah, good point, but the basic premise still stands.

> Fourth: I think the 'reserved name' has a level of gravitas/concreteness that makes the diagnostic more meaningful/immediately obvious to folks. A diagnostic of, "This name you chose for your macro might make this attribute no workie" yields "Yeah, but i wont use that so I'm ok". A diagnostic of, "This name is UB because the standard reserves it!" yields a level of pause/consideration that we otherwise wouldn't get.

Yes, but the point is: these names aren't reserved but the pain can still happen. e.g., `cdecl` is not a reserved identifier, but re-defining its meaning can still break code in ways that could have better diagnostics: https://godbolt.org/z/vTfWPsYj9. Though, I suppose to reduce the chattiness, we could elect to diagnose when we see an attribute that is ill-formed due to the macro. e.g.,
```
#define cdecl 12
#define stdcall 100 // No warning, doesn't cause problems (yet)

void func() [[gnu::cdecl]]; // Expands to `[[gnu::12]] which is an error, so warn on the #define above
```
> SO I think the diagnostic being associated with it being reserved is COMPLETELY valid/justifiable. I think "this is a bad idea, UB or not" is a reason to not try at all to suppress this if we think you're not ACTUALLY breaking the rule (by not including an StdLib header).

If we're only going to diagnose conflicts with standard attribute names, then I can squint enough to agree. But I think that's an arbitrary limitation; we all just agreed that this isn't about using a reserved identifier so much as about writing a macro which will conflict with uses of attributes of the same name.

**Comment by erichkeane** [comment]
> Yes, but the point is: these names aren't reserved but the pain can still happen. e.g., `cdecl` is not a reserved identifier, but re-defining its meaning can still break code in ways that could have better diagnostics: https://godbolt.org/z/vTfWPsYj9. Though, I suppose to reduce the chattiness, we could elect to diagnose when we see an attribute that is ill-formed due to the macro. e.g.,

THIS is interesting, and I'd be much more agreeable with a patch for ALL attributes, though I think this patch stands on its own.  I agree the danger is equal for both.  

> If we're only going to diagnose conflicts with standard attribute names, then I can squint enough to agree. But I think that's an arbitrary limitation; we all just agreed that this isn't about using a reserved identifier so much as about writing a macro which will conflict with uses of attributes of the same name.

I think it is actually about BOTH.  We have diagnostics that say "you're using a reserved thing", and this is a time where you are using a reserved thing, which is independently valuable.  The REST (conflicting with an attribute name) is a different, yet perhaps equally/more useful (in a different way) diagnostic.

IN SUMMARY: I think this proposal minus the `std` check is acceptable.  I think the proposed-not-implemented warning of "you messed with an attribute name, and it is doing weird stuff" is also a very valuable, though different, check.

**Comment by AaronBallman** [comment]
> IN SUMMARY: I think this proposal minus the std check is acceptable.

+1

> I think the proposed-not-implemented warning of "you messed with an attribute name, and it is doing weird stuff" is also a very valuable, though different, check.

I don't see them as different checks when they warn about the same thing, but I agree they can be separate implementations. I don't have a super strong feeling though because I've not really seen this problem crop up in the wild before except in contrived cases.

**Comment by a-tarasyuk** [comment]
@AaronBallman @erichkeane I’ve switched back to the version without the std check. should the diagnostic group be changed?

**Comment by a-tarasyuk** [comment]
@AaronBallman @erichkeane I’ve switched back to the version without the std check. should the diagnostic group be changed?

File: clang/lib/Lex/PPDirectives.cpp [hunk 8]
```diff
@@ -173,6 +176,20 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
   return false;
 }
 
+static bool isReservedCXXAttributeName(Preprocessor &PP, IdentifierInfo *II) {
+  const LangOptions &Lang = PP.getLangOpts();
+  if (Lang.CPlusPlus &&
+      hasAttribute(AttributeCommonInfo::Syntax::AS_CXX11, /*Scope*/ nullptr, II,
```
Comment (erichkeane) [inline clang/lib/Lex/PPDirectives.cpp:182]: `hasAttribute` and `getParsedKind` have a lot of overlap in the work they do, and I THINK should work right here?  Could you just check the AttrKind against 'invalid' instead of doing the `hasAttribute` check first?

File: clang/lib/Lex/PPDirectives.cpp [hunk 9]
```diff
@@ -173,6 +176,20 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
...
+                   PP.getTargetInfo(), Lang) > 0) {
+    AttributeCommonInfo::Kind AttrKind = AttributeCommonInfo::getParsedKind(
+        II, /*Scope*/ nullptr, AttributeCommonInfo::Syntax::AS_CXX11);
+    return !((AttrKind == AttributeCommonInfo::Kind::AT_Likely ||
+              AttrKind == AttributeCommonInfo::Kind::AT_Unlikely) &&
+             PP.isNextPPTokenLParen());
```
Comment (erichkeane) [inline clang/lib/Lex/PPDirectives.cpp:188]: Github is making this not great here... but why is the check for the LParen here, and how is it working?  Some of the attributes I'd think we'd ONLY want to diagnose if it is a function type.  That is, a macro:

`#define assume baz`

Should be fine.

But
`#define assume() baz`

is not.

`deprecated` as well should warn either way (since it is allowed to have an argument), same with `no_discard`.

File: clang/include/clang/Basic/DiagnosticGroups.td [hunk 10]
```diff
@@ -760,6 +760,7 @@ def AmbiguousMacro : DiagGroup<"ambiguous-macro">;
 def KeywordAsMacro : DiagGroup<"keyword-macro">;
 def ReservedIdAsMacro : DiagGroup<"reserved-macro-identifier">;
 def ReservedIdAsMacroAlias : DiagGroup<"reserved-id-macro", [ReservedIdAsMacro]>;
+def ReservedAttributeIdentifier : DiagGroup<"reserved-attribute-identifier">;
```
Comment (AaronBallman) [inline clang/include/clang/Basic/DiagnosticGroups.td:763]: Should `ReservedIdentifier` be updated to include the new group?

**Comment by AaronBallman** [comment]
> @AaronBallman @erichkeane I’ve switched back to the version without the std check. should the diagnostic group be changed?

I think we're fine to leave it as-is.

File: clang/lib/Lex/PPDirectives.cpp (hunk 9 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp]: @erichkeane thanks for the feedback. `isNextPPTokenLParen` detects whether the definition is function-like, as complete macro information is unavailable at this stage.

https://github.com/llvm/llvm-project/blob/d49a2d2bc9c65c787bfa04ac8ece614da48a8cd5/clang/lib/Lex/PPDirectives.cpp#L2938-L2940

I’ve updated the handling of attribute names as follows: if an attribute has required parameters, a warning will be triggered only for _function-like_ definitions such as `#define assume()`. For attributes with optional parameters like `deprecated`, a warning will be issued for both `#define deprecated` and `#define deprecated()`. In all other cases, a warning will be triggered for _non-function-like_ definitions such as `#define noreturn`.

I decided against using `hasAttribute,` as it involves plugin instance checks that don't seem relevant here. I switched to check attribute implementation

https://github.com/llvm/llvm-project/blob/65dc0d44473481d67d34dcffd1037d2f9f0e574b/clang/lib/Basic/Attributes.cpp#L25-L32

 which in this case relies on a single StringSwitch/case with a set of defined attributes, and I believe it shouldn't cause performance regression.

I hope that makes sense., if you have any thoughts or suggestions, I’d be grateful to hear them. thanks

Comment (erichkeane) [reply clang/lib/Lex/PPDirectives.cpp]: I think all the behavior about the function-likeness is exactly what I was hoping for/asking for.  I don't LOVE using `hasAttributeImpl` for anything other than the implementation of `hasAttribute`?  But perhaps the perf is worth it

File: clang/lib/Basic/Attributes.cpp [hunk 11]
```diff
@@ -61,14 +62,23 @@ int clang::hasAttribute(AttributeCommonInfo::Syntax Syntax,
...
+  }
 
   return 0;
 }
 
+int clang::hasAttribute(AttributeCommonInfo::Syntax Syntax,
+                        const IdentifierInfo *Scope, const IdentifierInfo *Attr,
+                        const TargetInfo &Target, const LangOptions &LangOpts) {
+  return hasAttribute(Syntax, Scope, Attr, Target, LangOpts,
+                      /*CheckPlugins*/ true);
```
Comment (erichkeane) [inline clang/lib/Basic/Attributes.cpp:79]:
```suggestion
                      /*CheckPlugins=*/ true);
```

File: clang/lib/Lex/PPDirectives.cpp [hunk 12]
```diff
@@ -179,13 +179,15 @@ static bool isLanguageDefinedBuiltin(const SourceManager &SourceMgr,
...
-    AttributeCommonInfo::Kind AttrKind = AttributeCommonInfo::getParsedKind(
-        II, /*Scope*/ nullptr, AttributeCommonInfo::Syntax::AS_CXX11);
-    return !((AttrKind == AttributeCommonInfo::Kind::AT_Likely ||
-              AttrKind == AttributeCommonInfo::Kind::AT_Unlikely) &&
-             PP.isNextPPTokenLParen());
+      hasAttribute(AttributeCommonInfo::AS_CXX11, /* Scope*/ nullptr, II,
+                   PP.getTargetInfo(), Lang, /*CheckPlugins*/ false) > 0) {
+    AttributeCommonInfo::AttrArgsInfo AttrArgsInfo =
+        AttributeCommonInfo::getCXX11AttrArgsInfo(II);
+    if (AttrArgsInfo == AttributeCommonInfo::AttrArgsInfo::Required)
```
Comment (erichkeane) [inline clang/lib/Lex/PPDirectives.cpp:186]: Did the likely/unlikely stuff get lost?  Is that a problem?

File: clang/lib/Basic/Attributes.cpp (hunk 11 above)
Comment (a-tarasyuk) [reply clang/lib/Basic/Attributes.cpp]: changed

File: clang/lib/Lex/PPDirectives.cpp (hunk 12 above)
Comment (a-tarasyuk) [reply clang/lib/Lex/PPDirectives.cpp:186]: Yes. I added attribute arg information to eliminate the need for additional logic to define how certain attributes should behave. For the new attributes, everything will work based on the TG information, with no additional logic needed.

**Review by erichkeane — APPROVED** [review]

File: clang/test/Preprocessor/macro-reserved-attrs-cxx11.cpp [hunk 13]
```diff
@@ -0,0 +1,100 @@
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -std=c++11 -fsyntax-only -verify -pedantic %s -DTEST1
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -std=c++11 -fsyntax-only -verify -pedantic %s -DTEST2
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -std=c++11 -fsyntax-only -verify -pedantic %s -DTEST3
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -std=c++11 -fsyntax-only -verify -pedantic %s -DTEST4
```
Comment (AaronBallman) [inline clang/test/Preprocessor/macro-reserved-attrs-cxx11.cpp:4]: It's worth noting that this diagnostic is on by default for everyone (the `-pedantic` isn't needed to issue the warning). Are we sure this issue is worth warning about by default or do we think users may find it to be too chatty?

Comment (a-tarasyuk) [reply clang/test/Preprocessor/macro-reserved-attrs-cxx11.cpp]: I've added `DefaultIgnore` for this diagnostic, to follow the behavior like `macro name is a reserved identifier` does. Is it ok?

**Review by AaronBallman — APPROVED** [review]
LGTM!
