### PR TITLE
[libc++] Fix ability to explicitly instantiate std::midpoint

### LINKED ISSUE #67046: C++20 std::midpoint is non-conformant
The second (pointer) overload of `std::midpoint()` fails to compile when used explicitly. This is a failure to accept valid code according to ISO/IEC 14882:2020 25.10.16/4 [numeric.ops.midpoint].  See https://godbolt.org/z/MxdanhvEE

Example:
```
#include <numeric>

template<typename T>
  T* mp(T* b, T*e) {
    return std::midpoint<T>(b, e);
  }

int main() {
    char a[2];
    char* p = mp(a, a+2);
}
```
gives the following compilation errors.
```
<source>:5:12: error: no matching function for call to 'midpoint'
    5 |     return std::midpoint<T>(b, e);
      |            ^~~~~~~~~~~~~~~~
<source>:10:15: note: in instantiation of function template specialization 'mp<char>' requested here
   10 |     char* p = mp(a, a+2);
      |               ^
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:40:1: note: candidate function template not viable: no known conversion from 'char *' to 'char' for 1st argument; dereference the argument with *
   40 | midpoint(_Tp __a, _Tp __b) noexcept
      | ^        ~~~~~~~
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:61:1: note: candidate template ignored: requirement 'is_pointer_v<char>' was not satisfied [with _TPtr = char]
   61 | midpoint(_TPtr __a, _TPtr __b) noexcept
      | ^
/opt/compiler-explorer/clang-17.0.1/bin/../include/c++/v1/__numeric/midpoint.h:78:1: note: candidate template ignored: requirement 'is_floating_point_v<char>' was not satisfied [with _Fp = char]
   78 | midpoint(_Fp __a, _Fp __b) noexcept
      | ^
1 error generated.
Compiler returned: 1
```
The following patch resolves the error.
```
57c57,58
< enable_if_t<is_object_v<remove_pointer_t<_TPtr>>
---
> enable_if_t<is_pointer_v<_TPtr>
>              && is_object_v<remove_pointer_t<_TPtr>>
59,60c60,61
<              && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr*>
< midpoint(_TPtr* __a, _TPtr* __b) noexcept
---
>              && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr>
> midpoint(_TPtr __a, _TPtr __b) noexcept
```

### PR DESCRIPTION
**Pull request by SanjayMarreddi**
std::midpoint is specified by having a pointer overload in [numeric.ops.midpoint].
With the way the pointer overload is specified, users can expect that calling 
std::midpoint as `std::midpoint<T>(a, b)` should work, but it didn't in libc++ 
due to the way the pointer overload was specified.

Fixes #67046

### CODE REVIEW

File: libcxx/include/__numeric/midpoint.h [hunk 1]
```diff
@@ -51,19 +51,12 @@ _LIBCPP_DISABLE_UBSAN_UNSIGNED_INTEGER_CHECK
...
-             && is_object_v<remove_pointer_t<_TPtr>>
-             && ! is_void_v<remove_pointer_t<_TPtr>>
-             && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr>
-midpoint(_TPtr __a, _TPtr __b) noexcept
-{
-    return __a + _VSTD::midpoint(ptrdiff_t(0), __b - __a);
+_LIBCPP_INLINE_VISIBILITY constexpr enable_if_t<is_object_v<_TPtr> && !is_void_v<_TPtr> && (sizeof(_TPtr) > 0), _TPtr*>
+midpoint(_TPtr* __a, _TPtr* __b) noexcept {
+  return __a + _VSTD::midpoint(ptrdiff_t(0), __b - __a);
 }
```
Comment (mordante) [inline libcxx/include/__numeric/midpoint.h:58]: The original part of this code has changed, early next week I expect we reformat all code in `include` so it would be good to rebase the patch after that.

**Review by mordante — COMMENTED** [review]
Thanks for your patch!
In libc++ we tend to heavily test our code. Can you add tests of code that does not work now and starts to work after the patch. Best use the example of  #67046.

File: libcxx/include/__numeric/midpoint.h [hunk 2]
```diff
@@ -51,19 +51,12 @@ _LIBCPP_DISABLE_UBSAN_UNSIGNED_INTEGER_CHECK
...
 template <class _TPtr>
-_LIBCPP_HIDE_FROM_ABI constexpr
-enable_if_t<is_pointer_v<_TPtr>
-             && is_object_v<remove_pointer_t<_TPtr>>
-             && ! is_void_v<remove_pointer_t<_TPtr>>
-             && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr>
-midpoint(_TPtr __a, _TPtr __b) noexcept
-{
-    return __a + std::midpoint(ptrdiff_t(0), __b - __a);
+_LIBCPP_INLINE_VISIBILITY constexpr enable_if_t<is_object_v<_TPtr> && !is_void_v<_TPtr> && (sizeof(_TPtr) > 0), _TPtr*>
```
Comment (ldionne) [inline libcxx/include/__numeric/midpoint.h:55]: Please use `_LIBCPP_HIDE_FROM_ABI` instead of `_LIBCPP_INLINE_VISIBILITY` -- they are equivalent but `_LIBCPP_INLINE_VISIBILITY` is going away.

File: libcxx/include/__numeric/midpoint.h [hunk 3]
```diff
@@ -51,19 +51,12 @@ _LIBCPP_DISABLE_UBSAN_UNSIGNED_INTEGER_CHECK
     return __a + __half_diff;
 }
 
-
 template <class _TPtr>
```
Comment (ldionne) [inline libcxx/include/__numeric/midpoint.h:54]: I would suggest renaming this template parameter to `_Tp` since now this is just a normal type, not a pointer anymore.

File: libcxx/include/__numeric/midpoint.h [hunk 4]
```diff
@@ -51,19 +51,12 @@ _LIBCPP_DISABLE_UBSAN_UNSIGNED_INTEGER_CHECK
...
-enable_if_t<is_pointer_v<_TPtr>
-             && is_object_v<remove_pointer_t<_TPtr>>
-             && ! is_void_v<remove_pointer_t<_TPtr>>
-             && (sizeof(remove_pointer_t<_TPtr>) > 0), _TPtr>
-midpoint(_TPtr __a, _TPtr __b) noexcept
-{
-    return __a + std::midpoint(ptrdiff_t(0), __b - __a);
+_LIBCPP_INLINE_VISIBILITY constexpr enable_if_t<is_object_v<_TPtr> && !is_void_v<_TPtr> && (sizeof(_TPtr) > 0), _TPtr*>
+midpoint(_TPtr* __a, _TPtr* __b) noexcept {
+  return __a + _VSTD::midpoint(ptrdiff_t(0), __b - __a);
```
Comment (ldionne) [inline libcxx/include/__numeric/midpoint.h:57]: Please use `std::` instead of `_VSTD::`. I suspect those are incorrectly-resolved merge conflict artifacts.

**Review by ldionne — CHANGES_REQUESTED** [review]
Thanks for the patch! I have a few small comments but this is close.

File: libcxx/include/__numeric/midpoint.h (hunk 2 above)
Comment (philnik777) [inline libcxx/include/__numeric/midpoint.h:55]: While we're modifying this code anyways, let's also refactor the `enable_if_t` to the `enable_if_t<..., int> = 0` variant.

File: libcxx/include/__numeric/midpoint.h (hunk 4 above)
Comment (SanjayMarreddi) [reply libcxx/include/__numeric/midpoint.h]: Yeah true, updated it now.

File: libcxx/include/__numeric/midpoint.h (hunk 2 above)
Comment (SanjayMarreddi) [reply libcxx/include/__numeric/midpoint.h]: Sure, refactored it.

**Review by ldionne — APPROVED** [review]
Thanks, this LGTM. I edited your PR title and description since that is what the commit message is generated from. In the future, please try to make commit messages self-explanatory (within reason). I know GitHub PRs make it easier than ever to reference issues in commit messages, but it would be nice to keep the repository history somewhat decoupled from GitHub.

This can be merged once the CI is green, whoever sees it first.

**Comment by SanjayMarreddi** [comment]
Thanks for the review @ldionne. Sure, I will keep the suggestions in mind in my future PRs.

**Review by philnik777 — APPROVED** [review]

**Comment by philnik777** [comment]
@SanjayMarreddi It looks like you have enabled to hide your email on GitHub, which means that commits are authored as `57671048+SanjayMarreddi@users.noreply.github.com `. We're trying to avoid that to have proper attribution without relying on GitHub. Please disable the setting so we can merge the patch.

**Comment by SanjayMarreddi** [comment]
@philnik777 I have disabled the setting now. Please look into it now. Thanks!
