### PR TITLE
[clang] Add support for MSVC force inline attrs

### LINKED ISSUE #186539: Add support for `[[msvc::forceinline]]`
This code compiles well under C++23 mode MSVC (`/std:c++latest /Wall /WX`):

```cpp
int square(int x)
{
    const auto impl = [&] [[msvc::forceinline]] () { return x * x; };
    return impl();
}
```

But it fails under the latest Clang (`--std=c++23 -Wall -Werror -fms-extensions --target=aarch64-pc-windows-msvc`):

```
<source>:3:29: error: unknown attribute 'msvc::forceinline' ignored [-Werror,-Wunknown-attributes]
    3 |     const auto impl = [&] [[msvc::forceinline]] () { return x * x; };
      |                             ^~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

[Compiler Explorer Link](https://godbolt.org/z/j6Gv4zaae).

It would be nice to add support for this construct, since this is the [only way](https://developercommunity.visualstudio.com/t/support-forceinline-on-c-lambda-expressions/351580#T-N1092115) one can force a lambda to be inlined. [`__forceinline`](https://developercommunity.visualstudio.com/t/support-forceinline-on-c-lambda-expressions/351580) does not work on lambda expressions.

### PR DESCRIPTION
**Pull request by trungnt2910**
Add support for `[[msvc::forceinline]]` and `[[msvc::forceinline_calls]]`.

`[[msvc::forceinline]]` is equivalent to Microsoft's `__forceinline` when placed before a function declaration.
Unlike `__forceinline`, `[[msvc::forceinline]]` works with lambdas.

`[[msvc::forceinline_calls]]` is simliar to `[[clang::always_inline]]` but only works on statements.

Both are implemented as aliases of `[[clang::always_inline]]` with special checks.

Fixes #186539.

### CODE REVIEW

File: clang/test/Sema/attr-ms-forceinline.cpp [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %clang_cc1 -verify -fsyntax-only -std=c++23 -triple x86_64-windows %s
```
[the remark this answers is not in the document]
Comment (NeKon69) [reply clang/test/Sema/attr-ms-forceinline.cpp]: Thanks, I understand the difference now. Looks a bit messy though

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this! Please be sure to add a release note to `clang/docs/ReleaseNotes.rst` so users know about the new functionality too.

Are there plans to also handle `[[msvc::forceinline_calls]]` (https://learn.microsoft.com/en-us/cpp/cpp/attributes?view=msvc-170#msvcforceinline_calls) which sounds like our `[[clang::always_inline]]` behavior on statements?

**Review by AaronBallman — APPROVED** [review]
I think the behavior in the tests looks good to me, thank you! If Microsoft comes back and says they are doing something with `[[msvc::forceinline]]` on a statement, we can modify our diagnostic behavior once we have more understanding of what the construct means.

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 2]
```diff
@@ -5181,6 +5181,18 @@ OptimizeNoneAttr *Sema::mergeOptimizeNoneAttr(Decl *D,
 }
 
 static void handleAlwaysInlineAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
+  AlwaysInlineAttr AIA(S.Context, AL);
+  if (!S.getLangOpts().MicrosoftExt &&
```
Comment (chfast) [inline clang/lib/Sema/SemaDeclAttr.cpp:5185]: This is causing noise in portable code compiled with clang without msvc extensions enabled. E.g. I have something like this on linux: `[[gnu::always_inline, msvc::forceinline]]`. And I'm seeing this warning.

Comment (trungnt2910) [reply clang/lib/Sema/SemaDeclAttr.cpp:5185]: The restriction was not my idea: https://github.com/llvm/llvm-project/pull/185282#discussion_r3010879738

Comment (AaronBallman) [reply clang/lib/Sema/SemaDeclAttr.cpp:5185]: That's expected behavior -- we diagnose when attributes are ignored. You get the same behavior with other attributes: https://godbolt.org/z/sGn87r3o6

Comment (chfast) [reply clang/lib/Sema/SemaDeclAttr.cpp:5185]: This forces me to disable this warning because of the usage `[[gnu::always_inline, msvc::forceinline]]`.

Comment (trungnt2910) [reply clang/lib/Sema/SemaDeclAttr.cpp:5185]: > That's expected behavior -- we diagnose when attributes are ignored. You get the same behavior with other attributes: https://godbolt.org/z/sGn87r3o6

`[[msvc::constexpr]]` is a weird semi-undocumented attribute - it is not specified on the official Microsoft Docs and only explained on the [Visual Studio Feedback](https://developercommunity.visualstudio.com/t/10259132#T-N10259447) page when a LLVM contributor specifically asked them about it.

Some other less esoteric `[[msvc::` attributes are left unguarded, such as the opposite of the newly added attributes, `[[msvc::noinline]]`: https://godbolt.org/z/W8519n6d1

File: clang/include/clang/Basic/DiagnosticSemaKinds.td [hunk 3]
```diff
@@ -3277,6 +3277,11 @@ def warn_function_attribute_ignored_in_stmt : Warning<
   "use '%0' on statements">,
   InGroup<IgnoredAttributes>;
 
+def warn_stmt_attribute_ignored_in_function : Warning<
+  "attribute is ignored on this function as it only applies to statements; "
+  "use '%0' for functions">,
```
Comment (shafik) [inline clang/include/clang/Basic/DiagnosticSemaKinds.td:3282]: Why do we need an input here? It looks like there is only one possible value? Are we going to extend this diagnostic?

Comment (trungnt2910) [reply clang/include/clang/Basic/DiagnosticSemaKinds.td:3282]: It is meant to mirror the reverse function attribute ignored in statement warning.

File: clang/lib/Sema/SemaDeclAttr.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaDeclAttr.cpp:5185]: > This forces me to disable this warning because of the usage `[[gnu::always_inline, msvc::forceinline]]`.

The idiomatic approach is to put the attributes behind a macro, as in:
```
#if __has_cpp_attribute(msvc::forceinline)
#define MSVC_FORCEINLINE [[msvc::forceinline]]
#else
#define MSVC_FORCEINLINE
#endif

#if __has_cpp_attribute(gnu::always_inline)
#define GNU_ALWAYS_INLINE [[gnu::always_inline]]
#else
#define GNU_ALWAYS_INLINE
#endif
```
this way the macros only expand when the attribute is actually known.

> Some other less esoteric [[msvc:: attributes are left unguarded, such as the opposite of the newly added attributes, [[msvc::noinline]]: https://godbolt.org/z/W8519n6d1

That's a compiler bug; the attribute should be diagnosed.
