### PR TITLE
[lld-macho] Fix thunks for non-__text TEXT sections

### LINKED ISSUE #52767: ld64.lld: error: relocation BRANCH26 is out of range: -165194492 is not in [-134217728, 134217727]; references _calloc
Building Firefox for arm64 macos with disabled optimizations and with lld fails with:
```
ld64.lld: error: relocation BRANCH26 is out of range: -165194492 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196704 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196676 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196144 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196116 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165196088 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165195984 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165299108 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: relocation BRANCH26 is out of range: -165308144 is not in [-134217728, 134217727]; references _malloc
ld64.lld: error: relocation BRANCH26 is out of range: -165208212 is not in [-134217728, 134217727]; references _calloc
ld64.lld: error: relocation BRANCH26 is out of range: -165311620 is not in [-134217728, 134217727]; references _malloc
```

STR:
- download https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Fald_IyiRO-ljidFJwvZig/runs/0/artifacts/public/build/testcase.tar.zstd
- `tar --zstd -xf testcase.tar.zstd`
- `cd testcase/toolkit/library/build`
- `clang++ --sysroot /path/to/MacOSX11.0.sdk -F/path/to/MacOSX11.0.sdk/System/Library/PrivateFrameworks -mmacosx-version-min=11.0 -stdlib=libc++ --target=aarch64-apple-darwin -o XUL -Wl,-filelist,XUL.list   -fuse-ld=lld -framework Cocoa -lobjc -framework AudioToolbox -lresolv  ../../../security/nss/lib/crmf/crmf_crmf/libcrmf.a ../../../js/src/build/libjs_static.a ../../../aarch64-apple-darwin/debug/libgkrust.a ../../../security/libnss3.dylib ../../../config/external/lgpllibs/liblgpllibs.dylib ../../../mozglue/build/libmozglue.dylib -dynamiclib -lbsm -framework IOSurface -framework IOKit -framework AudioToolbox -framework CoreMedia -framework VideoToolbox -framework LocalAuthentication -framework Security -lm -framework OpenGL -framework SystemConfiguration -framework AVFoundation -framework CoreUI -framework CoreSymbolication -lcups -framework Foundation -framework CoreFoundation -framework CoreLocation -framework QuartzCore -framework Carbon -framework CoreAudio -framework CoreVideo -framework AudioToolbox -framework AudioUnit -framework AddressBook -framework OpenGL -framework Security -framework ServiceManagement -framework CoreServices -framework ApplicationServices -framework AppKit -weak_framework Metal -weak_framework MediaPlayer`

Cc: @nico @int3 @keith

### PR DESCRIPTION
**Pull request by speednoisemovement**
This supersedes https://github.com/llvm/llvm-project/pull/87818 and fixes https://github.com/llvm/llvm-project/issues/52767

When calculating arm64 thunks, we make a few assumptions that may not hold when considering code sections outside of `__text`:

1. That a section needs thunks only if its size is larger than the branch range.
2. That any calls into `__stubs` are necessarily forward jumps (that is, the section with the jump is ordered before `__stubs`)

Sections like this exist in the wild, most prominently the `__lcxx_overrides` section introduced in https://github.com/llvm/llvm-project/pull/69498

This change:
- Ensures that if one section in `__TEXT` gets thunks, all of them do.
- Makes all code sections in `__TEXT` contiguous (and guaranteed to be placed before `__stubs`)

### CODE REVIEW

File: lld/MachO/Sections.h [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+#ifndef LLD_MACHO_SECTIONS_H
+#define LLD_MACHO_SECTIONS_H
+
+#include "lld/Common/LLVM.h"
```
Comment (ellishg) [inline lld/MachO/Sections.h:12]:
```suggestion
#include "llvm/ADT/StringRef.h"
```

You might be able to forward declare `StringRef`, instead.

File: lld/MachO/Sections.cpp [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+  if (segName == segment_names::text)
+    return StringSwitch<bool>(name)
+        .Cases(section_names::textCoalNt, section_names::staticInit, true)
+        .Default(false);
+
+  return false;
+}
+
+} // namespace lld::macho::sections
```
Comment (ellishg) [inline lld/MachO/Sections.cpp:36]: NIT: There is now newline at the end of the file.

File: lld/MachO/Sections.h (hunk 1 above)
Comment (speednoisemovement) [reply lld/MachO/Sections.h]: Done. Forward declare is a little unergonomic in this case.

File: lld/MachO/Sections.cpp (hunk 2 above)
Comment (speednoisemovement) [reply lld/MachO/Sections.cpp]: Done

File: lld/test/MachO/section-order.s [hunk 3]
```diff
@@ -1,4 +1,3 @@
-# REQUIRES: x86
```
Comment (BertalanD) [inline lld/test/MachO/section-order.s:1]: Probably not intended?

File: lld/MachO/OutputSegment.cpp [hunk 4]
```diff
@@ -89,9 +90,17 @@ static int sectionOrder(OutputSection *osec) {
...
   if (segname == segment_names::text) {
+    if (osec->name == section_names::header)
+      return -7;
+    if (osec->name == section_names::text)
+      return -6;
+    // Ensure all code sections are contiguous with `__text` for thunk
+    // calculations.
+    if (sections::isCodeSection(osec->name, segment_names::text, osec->flags) &&
+        osec->name != section_names::stubHelper) {
+      return -5;
```
Comment (BertalanD) [inline lld/MachO/OutputSegment.cpp:101]: Super nit:

`isCodeSection` is supposed to return true for `__text`, too, right? Should these two be merged? Or does `__text` need to come first in all cases (in that case, we should clarify that with a comment).

File: lld/MachO/ConcatOutputSection.cpp [hunk 5]
```diff
@@ -127,10 +127,20 @@ bool TextOutputSection::needsThunks() const {
...
+  // rest.
+  bool needsThunks = parent && parent->needsThunks;
+  if (!needsThunks &&
+      isecAddr - addr + in.stubs->getSize() <=
+          std::min(target->backwardBranchRange, target->forwardBranchRange))
     return false;
   // Yes, this program is large enough to need thunks.
+  if (parent) {
+    parent->needsThunks = true;
+  }
```
Comment (BertalanD) [inline lld/MachO/ConcatOutputSection.cpp:143]: LG, but I'm wondering, when is `parent` null here?

File: lld/test/MachO/section-order.s (hunk 3 above)
Comment (speednoisemovement) [reply lld/test/MachO/section-order.s:1]: It is. I wanted to make sure it ran since I knew this change affected it, and since it works fine I figured we should remove it. I guess this is sort of by accident since it's just directives with no instructions?

File: lld/MachO/OutputSegment.cpp (hunk 4 above)
Comment (speednoisemovement) [reply lld/MachO/OutputSegment.cpp:101]: This is partly just to be closer to existing behavior, and partly for jankier reasons: we expect `__text` to be the biggest section, so we need it to go first so it can trip `needsThunks`.

I guess the options are:
- Keep it that way and put the above as a comment
- Not encode the assumption and sort code sections by size

WDYT?

File: lld/test/MachO/section-order.s (hunk 3 above)
Comment (BertalanD) [reply lld/test/MachO/section-order.s:1]: We're still passing an x86 triple to `mc`. Or is that fine?

File: lld/MachO/OutputSegment.cpp (hunk 4 above)
Comment (BertalanD) [reply lld/MachO/OutputSegment.cpp:101]: Comment + keeping the jank sounds okay to me, I don't think we'll hit the case when `__text` is not the largest.

Comment (speednoisemovement) [reply lld/MachO/OutputSegment.cpp:104]: Done

File: lld/MachO/ConcatOutputSection.cpp (hunk 5 above)
Comment (speednoisemovement) [reply lld/MachO/ConcatOutputSection.cpp]: I'm not sure it can be practically right now, just did it since it starts out as null. Happy to remove if you think it reads better

File: lld/test/MachO/section-order.s (hunk 3 above)
Comment (speednoisemovement) [reply lld/test/MachO/section-order.s]: I got turned around re: how "Requires" works. Reverted, thanks!

File: lld/MachO/ConcatOutputSection.cpp [hunk 6]
```diff
@@ -127,10 +127,20 @@ bool TextOutputSection::needsThunks() const {
   uint64_t isecAddr = addr;
   for (ConcatInputSection *isec : inputs)
     isecAddr = alignToPowerOf2(isecAddr, isec->align) + isec->getSize();
-  if (isecAddr - addr + in.stubs->getSize() <=
-      std::min(target->backwardBranchRange, target->forwardBranchRange))
+  // Other sections besides __text might be small enough to pass this
+  // test but nevertheless need thunks for calling into ohter sections.
```
Comment (BertalanD) [inline lld/MachO/ConcatOutputSection.cpp:131]:
```suggestion
  // test but nevertheless need thunks for calling into other sections.
```

File: lld/MachO/ConcatOutputSection.cpp (hunk 5 above)
Comment (BertalanD) [reply lld/MachO/ConcatOutputSection.cpp]: being cautious doesn't hurt us, so fine by me.

**Review by BertalanD — COMMENTED** [review]
LGTM modulo the typo

**Review by BertalanD — APPROVED** [review]

**Comment by vogelsgesang** [comment]
Can / should this be backported to 18.1.0?

**Comment by speednoisemovement** [comment]
Suspect it can, can't really say if it *should* or what's involved in doing that
