### PR TITLE
[Clang] treat fixed-underlying enum constants as the enumerated type in C23 to follow the spec

### LINKED ISSUE #172118: [C23] Type of enumeration constants having enumerated type wrong in C
Clang uses the wrong type for enumeration constants having enumerated type. It uses the underlying type instead.
This causes missing `-Wswitch` warnings (for example). https://godbolt.org/z/rKnndKdvo

### Source (`<stdin>`):
```c
typedef enum : long { E0 } E;
void f(bool b, E e) {
  auto v = E0;
  if (b) v = e;
  switch (v) {}  // expected-warning {{not handled in switch}}
}
```

### Compiler invocation:
```
clang -std=c23 -Wall -Wextra -pedantic -Xclang -verify -xc -
```

### Expected output:
(clean compile)

### Actual output:
```
error: 'expected-warning' diagnostics expected but not seen:
  File <stdin> Line 5: not handled in switch
1 error generated.
```

### Compiler version info (`clang -v`):
```
clang version 22.0.0git (https://github.com/llvm/llvm-project.git d8d87b594eb67c1f96cf59d645b660f8fd831bee)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/wandbox/clang-head/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #172118

--- 

This patch resolves an issue where C23 fixed-underlying enum constants were incorrectly treated as the underlying integer type instead of the enumeration type.

According to C23 `6.7.2.2p15`:

> The enumeration member type of an enumerated type with a fixed underlying type is the same as the type itself.

### CODE REVIEW

**Review by Fznamznon — COMMENTED** [review]
Hi, thanks for the patch, does that also fix https://github.com/llvm/llvm-project/issues/147370 ? I think we could reuse some test cases from there as well.

**Review by Fznamznon — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -20822,10 +20822,12 @@ void Sema::ActOnEnumBody(SourceLocation EnumLoc, SourceRange BraceRange,
       NewSign = true;
     } else if (ECD->getType() == BestType) {
       // Already the right type!
-      if (getLangOpts().CPlusPlus)
+      if (getLangOpts().CPlusPlus || (getLangOpts().C23 && Enum->isFixed()))
         // C++ [dcl.enum]p4: Following the closing brace of an
         // enum-specifier, each enumerator has the type of its
         // enumeration.
+        // C23 6.7.2.2p15: For an enumerated type with fixed underlying type,
+        // the enumeration member type is the enumerated type.
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDecl.cpp]:
```suggestion
        // C23 6.7.3.3p16: The enumeration member type for an enumerated type with fixed
        // underlying type is the enumerated type.
```

**Review by AaronBallman — APPROVED** [review]
LGTM!
