### PR TITLE
[MLIR][OpenMP][OMPIRBuilder] Add lowering support for omp.target_triples

### LINKED ISSUE #100209: [Flang] Linker error when ``--offload-arch`` not specified when compiling with `target` construct
When compiling even a simple program with the OpenMP `target` construct, we get the following linker error when `--offload-arch` is not specified.
```
flang-new -O2 -fopenmp target_no_arch.f90
ld.lld: error: undefined symbol: __tgt_target_kernel
>>> referenced by FIRModule
>>>               /tmp/target_no_arch-5b3141.o:(_QQmain)
```

test file ->
```
$> cat target_no_arch.f90
program main
  integer :: a = 0
  !$omp target
  print *, a
  !$omp end target
end program main
```

### PR DESCRIPTION
**Pull request by skatrak**
This patch modifies MLIR to LLVM IR lowering of the OpenMP dialect to take into consideration the contents of the `omp.target_triples` module attribute while generating code for `omp.target` operations.

It adds the `OpenMPIRBuilderConfig::TargetTriples` field and initializes it using the `amendOperation` flow of the `OpenMPToLLVMIRTranslation` pass. Some changes are introduced into the `OpenMPIRBuilder` to allow passing the information about whether a target region is intended to be offloaded from outside.

The result of this change is that offloading calls are only generated when the `--offload-arch` or `-fopenmp-targets` options are given to the compiler. Otherwise, only the host fallback code is generated. This fixes linker errors currently triggered by `flang-new` if a source file containing a `target` construct is compiled without any of the aforementioned options.

Several unit tests impacted by these changes, which are intended to check host code generated for `omp.target` operations, are updated to contain the new attribute. Without it, no calls to `__tgt_target_kernel` and associated control flow operations are generated.

### CODE REVIEW

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -7053,13 +7053,28 @@ OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::emitTargetTask(
...
 }
+
 static void emitTargetCall(
     OpenMPIRBuilder &OMPBuilder, IRBuilderBase &Builder,
     OpenMPIRBuilder::InsertPointTy AllocaIP, Function *OutlinedFn,
     Constant *OutlinedFnID, int32_t NumTeams, int32_t NumThreads,
     SmallVectorImpl<Value *> &Args,
     OpenMPIRBuilder::GenMapInfoCallbackTy GenMapInfoCB,
     SmallVector<llvm::OpenMPIRBuilder::DependData> Dependencies = {}) {
+  //  emitKernelLaunch
```
Comment (bhandarkar-pranav) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:7064]: Minor nit : Consider making it clear in the comment here that this is a host-to-host launch?

**Review by bhandarkar-pranav — APPROVED** [review]
Thank you, @skatrak  - Just a minor nit and and I opened a linked issue so that the exact linker error message is captured for posterity.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp (hunk 1 above)
Comment (skatrak) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp]: Done.

**Review by skatrak — COMMENTED** [review]
Thank you @bhandarkar-pranav for the review, you comment should be addressed now. I'll rebase the whole PR stack once I check that the buildbot issue caused by the first is resolved. Then, this one should be green too.

**Review by Meinersbur — APPROVED** [review]
LGTM

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 2]
```diff
@@ -7053,13 +7053,30 @@ OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::emitTargetTask(
...
     OpenMPIRBuilder &OMPBuilder, IRBuilderBase &Builder,
     OpenMPIRBuilder::InsertPointTy AllocaIP, Function *OutlinedFn,
     Constant *OutlinedFnID, int32_t NumTeams, int32_t NumThreads,
     SmallVectorImpl<Value *> &Args,
     OpenMPIRBuilder::GenMapInfoCallbackTy GenMapInfoCB,
     SmallVector<llvm::OpenMPIRBuilder::DependData> Dependencies = {}) {
+  // Generate a function call to the host fallback implementation of the target
+  // region. This is called by the host when no offload entry was generated for
+  // the target region and when the offloading call fails at runtime.
+  auto &&EmitTargetCallFallbackCB =
```
Comment (bhandarkar-pranav) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:7067]: Just a note here, that `if (!OutlinedFnID)`, then we cannot simply inline a call to `OutlinedFn`. We need to the following check 
```
if (!OutlinedFnID) {
   if(RequiresOuterTargetTask)
       Builder.restoreIP(emitTargetTask(...));
   else
       Builder.restoreIP(EmitTargetCallFallBackCB(Builder.saveIP()));
}
```
But dont change this PR because I'll fold that into my upcoming changes and more importantly, `emitTargetTask` ->`emitKernelLaunch`  assert on `OutlinedFnID` [here](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp#L1088)

Comment (skatrak) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:7070]: Thank you for pointing out this issue. I just pushed some changes to hopefully address it, though I think these should get a second review from you since you're more familiar with the handling of `target depend`.

**Review by bhandarkar-pranav — APPROVED** [review]
Thanks @skatrak. LGTM
