### PR TITLE
[MLIR][LLVM] Fix #llvm.constant_range parsing

### LINKED ISSUE #122996: [MLIR][LLVM] Incorrect #llvm.constant_range parse
See godbolt: https://godbolt.org/z/x34YarsrE

`range(i32 0, -2147483648)` is imported as `#llvm.constant_range<i32, 0, -2147483648>`, but `-2147483648` is internally stored as a 40-bit integer, causing the verifier to fail: https://github.com/llvm/llvm-project/blob/ebef44067bd0a2cd776b8baea39cffa7f602ce7b/mlir/lib/Dialect/LLVMIR/IR/LLVMAttrs.cpp#L290-L293

### PR DESCRIPTION
**Pull request by Kuree**
This should fix https://github.com/llvm/llvm-project/issues/122996.

When `APInt` parses negative numbers, it may extend the bit width. This patch ensures the bit width matches with the attribute.

### CODE REVIEW

**Review by CoTinker — APPROVED** [review]
LGTM

File: mlir/lib/Dialect/LLVMIR/IR/LLVMAttrs.cpp [hunk 1]
```diff
@@ -271,10 +271,9 @@ Attribute ConstantRangeAttr::parse(AsmParser &parser, Type odsType) {
       parser.parseInteger(upper) || parser.parseGreater())
     return Attribute{};
   // For some reason, 0 is always parsed as 64-bits, fix that if needed.
```
Comment (victor-eds) [inline mlir/lib/Dialect/LLVMIR/IR/LLVMAttrs.cpp:273]: Do we still need that comment now that we are always handling that case?

Comment (Kuree) [reply mlir/lib/Dialect/LLVMIR/IR/LLVMAttrs.cpp]: Good catch. Comment updated.

**Review by victor-eds — APPROVED** [review]

**Review by Dinistro — APPROVED** [review]
LGTM, thanks for the fix. Feel free to merge this 🙂

**Comment by Kuree** [comment]
I don't have merge rights. Please help me merge it in 🙂.
