### PR TITLE
[InterleavedAccessPass] Get round the unsupported large scalarize vectors

### LINKED ISSUE #88247: [AArch64] error in backend: Do not know how to split the result of this operator
* There's a compilation problem with **sve**, https://godbolt.org/z/MYKzeKx3Y
  > it reports **fatal error: error in backend: Do not know how to split the result of this operator!**

* related code https://github.com/llvm/llvm-project/blob/0d17e1f0e5d706ac288ac8a62db92b8df64faf4e/llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp#L673

### PR DESCRIPTION
**Pull request by vfdff**
When build with option -msve-vector-bits=512, the return vaule of Subtarget->getMinSVEVectorSizeInBits() is 512;
While the MinElts is still 4 for <vscale x 4 x double> in getNumInterleavedAccesses, so it creates invalid
llvm.aarch64.sve.ld2.sret.nxv4f64, which need be splited.
Unlikely, the related custom spilting is not supported now.

Fix https://github.com/llvm/llvm-project/issues/88247

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -16433,7 +16433,9 @@ bool AArch64TargetLowering::lowerDeinterleaveIntrinsicToLoad(
   if (UseScalable && !VTy->isScalableTy())
     return false;
 
-  unsigned NumLoads = getNumInterleavedAccesses(VTy, DL, UseScalable);
+  // Get around for the missing of split large size scalarize vectors.
+  // TODO: Support the custom split of large size scalarize vectors
+  unsigned NumLoads = getNumInterleavedAccesses(VTy, DL, false);
```
Comment (paulwalker-arm) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:16438]: This looks like it would break the SVE fixed length support.  Looking at the code I think changing:
```if (UseScalable)```
to
```if (UseScalable && isa<FixedVectorType>(VecTy)``` 
should do the trick given `getMinSVEVectorSizeInBits()` is not relevant for scalable vector types and the default `128` value should be maintained.

Comment (vfdff) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:16438]: Apply your comment, thanks @paulwalker-arm

Comment (paulwalker-arm) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:16438]: Sorry, I should have been clearer.  I meant the code within `getNumInterleavedAccesses()` needs to be changed because that is where the bug exists.

File: llvm/test/Transforms/InterleavedAccess/AArch64/sve-interleaved-accesses.ll [hunk 2]
```diff
@@ -491,6 +491,30 @@ define void @store_bfloat_factor2(ptr %ptr, <16 x bfloat> %v0, <16 x bfloat> %v1
   ret void
 }
 
+; Use 4 vliad llvm.vector.insert.nxv4f64.nxv2f64
```
Comment (paulwalker-arm) [inline llvm/test/Transforms/InterleavedAccess/AArch64/sve-interleaved-accesses.ll:494]: This is effectively a negative test so perhaps something like "Ensure vscale_range property does not affect scalable vector types."?

Comment (vfdff) [reply llvm/test/Transforms/InterleavedAccess/AArch64/sve-interleaved-accesses.ll]: Update the comment, thanks

**Review by paulwalker-arm — APPROVED** [review]
