### PR TITLE
[clang] Compute accurate begin location for CallExpr with explicit object parameter

### LINKED ISSUE #116335: [clangd] Incorrect navigation caused by deducing this
```c++
struct B
{
    template<typename Self>
    auto bar(this Self &&) 
    {
        return 0;
    }

    auto bar2(this B &&)
    {
        return 0;
    }
};

struct A
{
    auto foo()
    {
        return B{};
    }
};

auto baz(int n)
{
    return n;
}

int main()
{
    A a{};
    baz(a.foo().bar());

    A a2{};
    int n  = a2.foo().bar2();
}
```
incorrect navigation of a.foo and a to baz, a2.foo and a2 to n

### PR DESCRIPTION
**Pull request by HighCommander4**
The explicit object parameter is written before the callee expression, so the begin location should come from the explicit object parameter.

Fixes https://github.com/llvm/llvm-project/issues/116335

### CODE REVIEW

File: clang/lib/AST/Expr.cpp [hunk 1]
```diff
@@ -1639,6 +1639,13 @@ SourceLocation CallExpr::getBeginLoc() const {
   if (const auto *OCE = dyn_cast<CXXOperatorCallExpr>(this))
     return OCE->getBeginLoc();
 
+  if (const CXXMethodDecl *Method =
+          dyn_cast_or_null<const CXXMethodDecl>(getCalleeDecl());
```
Comment (zwuis) [inline clang/lib/AST/Expr.cpp:1643]:
```suggestion
          dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl());
```

**Review by zyn0217 — COMMENTED** [review]
I think this also needs a selection tree test to demonstrate the original case works with the current approach.

Besides, If we can't highlight the loci differences (compared to the behavior before the last PR) using simple `-ast-dump` flags, then perhaps we should reconsider the necessity of clang/test/AST/ast-dump-cxx2b-deducing-this.cpp - removing it might be a good option.

That said, I was still thinking if there's any possibility for us to find a better AST model for such use cases, rather than relying on special-casing it in `CallExpr::getBeginLoc`

**Comment by HighCommander4** [comment]
> That said, I was still thinking if there's any possibility for us to find a better AST model for such use cases, rather than relying on special-casing it in `CallExpr::getBeginLoc`

A more general implementation of `CallExpr::getBeginLoc` that occurs to me is: return the earlier of the callee's begin loc and the first argument's (if present) begin loc.

File: clang/lib/AST/Expr.cpp [hunk 2]
```diff
@@ -1639,6 +1639,13 @@ SourceLocation CallExpr::getBeginLoc() const {
   if (const auto *OCE = dyn_cast<CXXOperatorCallExpr>(this))
     return OCE->getBeginLoc();
 
+  if (const CXXMethodDecl *Method =
```
Comment (tbaederr) [inline clang/lib/AST/Expr.cpp:1642]:
```suggestion
  if (const auto *Method =
```

**Comment by HighCommander4** [comment]
Updated to add a clangd test that fails with the previous fix approach.

> A more general implementation of `CallExpr::getBeginLoc` that occurs to me is: return the earlier of the callee's begin loc and the first argument's (if present) begin loc.

I did not do this because accurately determining which of two `SourceLocation`s is earlier requires calling `SourceManager::isBeforeInTranslationUnit()`, and a `SourceManager` does not seem to be available in `CallExpr::getBeginLoc()`.

**Comment by HighCommander4** [comment]
(Removed extraneous formatting changes)

File: clang/lib/AST/Expr.cpp [hunk 3]
```diff
@@ -1639,11 +1639,19 @@ SourceLocation CallExpr::getBeginLoc() const {
   if (const auto *OCE = dyn_cast<CXXOperatorCallExpr>(this))
     return OCE->getBeginLoc();
 
+  if (const auto *Method =
+          dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl());
```
Comment (zyn0217) [inline clang/lib/AST/Expr.cpp:1643]: nit: I presume the `const` in `<const CXXMethodDecl>` isn't necessary, right?

**Review by zyn0217 — APPROVED** [review]
Thanks, while I haven’t come up with a better solution to model this situation, I think this looks good for now.

Please give @cor3ntin some time before merging, in case there are some better approaches that I might have overlooked.

File: clang/lib/AST/Expr.cpp (hunk 3 above)
Comment (cor3ntin) [reply clang/lib/AST/Expr.cpp:1643]: Maybe you could do something like

```
unsigned Offset = 0;
if(isExplicitObjectMemberFunction())
    Offset = 1;
```
To avoid some duplication

Comment (HighCommander4) [reply clang/lib/AST/Expr.cpp:1643]: Sorry, I'm not quite following this suggestion. What am I supposed to do with `Offset`?

Comment (cor3ntin) [reply clang/lib/AST/Expr.cpp:1643]: heh I think there is some opportunities to merge the slightly different if statements (for the explicit and not explicit cases) but it would be a minor improvement so I'll will approve that

**Review by cor3ntin — APPROVED** [review]

File: clang/lib/AST/Expr.cpp (hunk 3 above)
Comment (HighCommander4) [reply clang/lib/AST/Expr.cpp:1643]: > heh I think there is some opportunities to merge the slightly different if statements (for the explicit and not explicit cases) but it would be a minor improvement so I'll will approve that

Ah, I see.

I considered doing something like this:

```c++
bool UseFirstArgLoc = false;
if (/* is explicit object */)
  UseFirstArgLoc = true;

SourceLocation begin = getCallee()->getBeginLoc();
if ((begin.isInvalid() || UseFirstArgLoc) && getNumArgs() > 0 && getArg(0))
  begin = getArg(0)->getBeginLoc();
return begin;
```
  
But this needlessly evaluates `getCallee()->getBeginLoc()` in the explicit case, so I opted not to do this.

**Comment by nikic** [comment]
It looks like this causes a significant compile-time regression: https://llvm-compile-time-tracker.com/compare.php?from=2b855dd97092e2178ac5c470a804a17ec440d7e5&to=9ccde12f5eeb91152900082a2ae839e2a9702b31&stat=instructions:u (Maybe most clearly seen during clang bootstrap, where this adds 0.5% to many compilations: https://llvm-compile-time-tracker.com/compare_clang.php?from=2b855dd97092e2178ac5c470a804a17ec440d7e5&to=9ccde12f5eeb91152900082a2ae839e2a9702b31&stat=instructions%3Au&sortBy=interestingness)

Is that expected?

**Comment by HighCommander4** [comment]
> It looks like this causes a significant compile-time regression: https://llvm-compile-time-tracker.com/compare.php?from=2b855dd97092e2178ac5c470a804a17ec440d7e5&to=9ccde12f5eeb91152900082a2ae839e2a9702b31&stat=instructions:u (Maybe most clearly seen during clang bootstrap, where this adds 0.5% to many compilations: https://llvm-compile-time-tracker.com/compare_clang.php?from=2b855dd97092e2178ac5c470a804a17ec440d7e5&to=9ccde12f5eeb91152900082a2ae839e2a9702b31&stat=instructions%3Au&sortBy=interestingness)
> 
> Is that expected?

I think it's at least conceivable, as the patch adds an extra branch to `CallExpr::getBeginLoc()`, which is likely to be called pretty frequently.

The branch is **not** taken most of the time (it's only taken for calls to functions with an explicit object argument, which is a C++23 feature), so perhaps annotating the branch as "unlikely" is sufficient to avoid the performance regression?

**Comment by HighCommander4** [comment]
> The branch is **not** taken most of the time (it's only taken for calls to functions with an explicit object argument, which is a C++23 feature), so perhaps annotating the branch as "unlikely" is sufficient to avoid the performance regression?

Ah, no, that's not sufficient because it takes some work (a call to `getCalleeDecl()`) to compute the branch condition.

We could consider revising the implementation approach to optimize this better; for example, add a "uses explicit object argument" bit to `CallExprBits`?

**Comment by tbaederr** [comment]
I didn't check if any tests fail but here's a version where `CallExpr` saves its `BeginLoc` explicitly: http://llvm-compile-time-tracker.com/compare.php?from=416e4cd332c7421b187844ac9aaf6fe28b575a7d&to=0b6e36fe460409aa59958b79766b4f64a31c97e6&stat=instructions:u

**Comment by HighCommander4** [comment]
> I didn't check if any tests fail but here's a version where `CallExpr` saves its `BeginLoc` explicitly: http://llvm-compile-time-tracker.com/compare.php?from=416e4cd332c7421b187844ac9aaf6fe28b575a7d&to=0b6e36fe460409aa59958b79766b4f64a31c97e6&stat=instructions:u

Yeah, this is another alternative, though I wonder if the memory tradeoff it makes (increasing the size of `CallExpr` by 4 bytes) is worth it.

**Comment by shafik** [comment]
This PR was flagged as the cause of this crash: https://github.com/llvm/llvm-project/issues/130272
