### PR TITLE
[lldb][windows] add STDIN and STDOUT forwarding support

### LINKED ISSUE #175652: [LLDB] Prompt not shown after breakpoint is hit on Windows
When a breakpoint is hit, LLDB doesn't show the prompt if there was previous input on the console (previous LLDB commands have been executed).
You can reproduce this as follows:

Pick any executable you want to debug (with a `main` function).
Then, create a breakpoint at `main` and run the program with LLDB. Most importantly, the `r` must be typed in LLDB (not through `-o`):

```console
> lldb test.exe
(lldb) target create "test.exe"
Current executable set to 'F:\Dev\dump\test.exe' (x86_64).
(lldb) b main
Breakpoint 1: where = test.exe`main + 9 at test.cpp:2, address = 0x0000000140001009
(lldb) r
Process 23876 launched: 'F:\Dev\dump\test.exe' (x86_64)
Process 23876 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00007ff767231009 test.exe`main at test.cpp:2
   1    int main() {
-> 2      return 0;
   3    }
bt
(lldb) error: 'thread select' takes exactly one thread index argument, or a thread ID option:
Usage: thread select <thread-index> (or -t <thread-id>)
(lldb)
```

There are two issues here:

- There's no prompt after the breakpoint is hit
- The first character of the prompt is eaten (`t` was executed above)

Both have the same cause. When the process is running, we're forwarding the stdin of LLDB to the process. For Windows, this is done in [`IOHandlerProcessSTDIOWindows`](https://github.com/llvm/llvm-project/blob/5334c5148637dc58ae0e527b7b2c7c0569542271/lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp#L951). It reads from the stdin handle and writes to the ConPTY input. The stdin handle is a console handle.

If there was previous input on the console that was handled by other IOHandlers (namely `IOHandlerEditline`) and C functions like `fgets`, then the stdin handle still has pending console input (at least one key-up event). This causes the `WaitForMultipleObjects` [here](https://github.com/llvm/llvm-project/blob/5334c5148637dc58ae0e527b7b2c7c0569542271/lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp#L991) to return immediately with `WAIT_OBJECT_0`. We then do a `ReadFile` on the stdin handle [here](https://github.com/llvm/llvm-project/blob/5334c5148637dc58ae0e527b7b2c7c0569542271/lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp#L998). This will block, because there isn't any _text_ input.

In the above example, the `ReadFile` call will block the prompt from being shown, and it will eat the first character of the command.

I'm not sure what the proper way of forwarding the host stdin to the ConPTY is. [Microsoft's example uses `ReadFile` and `WriteFile` too](https://github.com/microsoft/terminal/blob/673d4eb4971f0d14d5c7470a828fa940cb192af4/samples/ConPTY/EchoCon/EchoCon/EchoCon.cpp#L167-L189). But they don't wait on the stdin handle. If I understand correctly, then we can't just use `WriteConsoleInput` on the ConPTY input (we'd also need to take out initial key-up events).

cc @charles-zablit

### PR DESCRIPTION
**Pull request by charles-zablit**
This patch enables standard input and standard output forwarding in lldb.

A debuggee using `std::cin` will currently hang because lldb does not forward stdin to it. Similarly, the output of a debuggee printing with `std::cout` will not appear either. This patch fixes both of those things using the ConPTY which was implemented in https://github.com/llvm/llvm-project/pull/168729.

This patch also fixes an infinite wait in `IOHandlerProcessSTDIOWindows`.

There were 2 issues:
1. `WaitForMultipleObjects` returns when a non text input is received. `ReadFile` however, does not, causing an infinite wait. This patch ensures that, if `hstdin` is a console handle, we don't try to call `ReadFile` on non text input (key up events for instance).
2. `IOHandlerProcessSTDIOWindows::Cancel()` writes to `m_pipe` but that does not cause `WaitForMultipleObjects` to return because it's waiting on the wrong handle.

Fixes:
1. `m_read_pipe` is consumed until a text character is reached (if any).
2. `IOHandlerProcessSTDIOWindows` does not use a pipe for inter thread communication anymore, but rather an overlapped event with an `std::atomic` representing the state.

I was not able to write a test for this. I have tried writing a shell test with `echo` piping commands to `lldb`, and also a custom Python script which sends the commands to `lldb` over stdin, but none of them work.

Related issues:
- fixes https://github.com/llvm/llvm-project/issues/175652

rdar://168587474

### CODE REVIEW

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp [hunk 1]
```diff
@@ -993,6 +996,20 @@ class IOHandlerProcessSTDIOWindows : public IOHandler {
...
+          DWORD numRead = 0;
+          if (!PeekConsoleInput(hStdin, &inputRecord, 1, &numRead) ||
+              numRead == 0)
+            goto exit_loop;
+          // We only care about text input. Ignore all non text input events and
+          // let other IOHandlers handle them.
+          if (inputRecord.EventType != KEY_EVENT ||
+              !inputRecord.Event.KeyEvent.bKeyDown ||
+              inputRecord.Event.KeyEvent.uChar.AsciiChar == 0)
+            break;
```
Comment (Nerixyz) [inline lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: When we discard these events, we never take them out of the queue, so `WaitForMultipleObjects` will still return immediately. We probably need to [`ReadConsoleInput`](https://learn.microsoft.com/en-us/windows/console/readconsoleinput) here.

**Review by Nerixyz — CHANGES_REQUESTED** [review]

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp (hunk 1 above)
Comment (charles-zablit) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: I initially tried the following at desk, but that does not fix the issue:
```cpp
if (isConsole) {
  INPUT_RECORD inputRecord;
  DWORD numRead = 0;
  if (!PeekConsoleInput(hStdin, &inputRecord, 1, &numRead) ||
      numRead == 0)
    goto exit_loop;
  if (!ReadConsoleInput(hStdin, &inputRecord, 1, &numRead))
    goto exit_loop;
  // We only care about text input. Ignore all non text input events and
  // let other IOHandlers handle them.
  if (inputRecord.EventType == KEY_EVENT && 
      inputRecord.Event.KeyEvent.bKeyDown &&
      inputRecord.Event.KeyEvent.uChar.AsciiChar != 0) {
    
    char ch = inputRecord.Event.KeyEvent.uChar.AsciiChar;
    DWORD written = 0;
    if (!WriteFile(m_write_file, &ch, 1, &written, nullptr) || written != 1)
      goto exit_loop;
  }
  break;
}
```

My understanding is that we don't want to consume the non text console events and let another `IOHandler` handle them.

Comment (charles-zablit) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: `Readfile` does not consume the non-text events, it does not "see" them at all, which is why we had the hang in the first place.

`ReadConsoleInput` does, consumes them, but then we don't handle them and since they are consumed, the other `IOHandler` does not see them.

Comment (Nerixyz) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: It does fix the issue, but LLDB is now in a busy-loop while the process is running and waiting for input (e.g. from `std::cin`). You can see this when inspecting LLDB in Task Manager or Process Explorer.

> I think that we should merge this and cherry-pick it to `22.0` and do some proper refactoring on main if need be.

Not sure if we should do it as-is because of the above. If this can be fixed, we should definitely cherry-pick it.

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp [hunk 2]
```diff
@@ -993,6 +996,27 @@ class IOHandlerProcessSTDIOWindows : public IOHandler {
       case WAIT_FAILED:
         goto exit_loop;
       case WAIT_OBJECT_0: {
+        if (isConsole) {
+          while (true) {
+            INPUT_RECORD inputRecord;
+            DWORD numRead = 0;
+            if (!PeekConsoleInput(hStdin, &inputRecord, 1, &numRead) ||
+                numRead == 0)
+              goto exit_loop;
```
Comment (Nerixyz) [inline lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: If `PeekConsoleInput` succeeds but `numRead` is 0, then we need to continue the outer loop instead of exiting.

I tested this with the following program:

```cpp
#include <iostream>

int main() {
    std::string s;
    std::cin >> s;
    return 0;
}
```
And running
```sh
b main
r
# *breakpoint hit*
b test.cpp:6 # at return 0;
c
# this should not show the lldb prompt until the breakpoint is hit
# *breakpoint hit*
c
```

**Review by Nerixyz — CHANGES_REQUESTED** [review]
Just the changed control flow, otherwise it works well.

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp [hunk 3]
```diff
@@ -993,6 +996,27 @@ class IOHandlerProcessSTDIOWindows : public IOHandler {
       case WAIT_FAILED:
         goto exit_loop;
       case WAIT_OBJECT_0: {
+        if (isConsole) {
+          while (true) {
+            INPUT_RECORD inputRecord;
+            DWORD numRead = 0;
```
[the remark this answers is not in the document]
Comment (charles-zablit) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: Let's make all of the class' variables snake case in a follow up patch.

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp (hunk 2 above)
Comment (Nerixyz) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: With [`4a6e017` (this PR)](https://github.com/llvm/llvm-project/pull/175812/commits/4a6e01771e9c7b3081dfa8f6d4b69e01e5397e98), we'd try to read one record afterward (would block, because zero are in there). I think you still need a `if (nRead == 0) goto outer_loop;` or similar before checking the `inputRecord`. 

We shouldn't continue with the current iteration of the outer loop (i.e. we shouldn't call `ReadFile`), because we know that the console doesn't have any pending events - we should wait for new ones.

Comment (charles-zablit) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: I added an additional `if (nRead == 0)`. I think this should never happen because `WaitForMultipleObjects` means there is data in the pipe right? I will take another look at this tomorrow with a fresh eye.

Comment (Nerixyz) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp]: > I think this should never happen because `WaitForMultipleObjects` means there is data in the pipe right?

If there's no data in the pipe, that's true. But if there are _only_ non-keyboard events in it, we'll read them out and discard them (in the inner loop). Once we drained the pipe, `PeekConsoleInput` will return `nRead = 0`.

**Review by Nerixyz — COMMENTED** [review]
I've been playing a bit around with this (with the event being created and the same program I mentioned above). Starting and breaking works.

However, when typing on the console, we get stuck in `ReadFile`, even though there are characters on the console. Maybe it _does_ need the events we filter? I also experimented with using [`ReadConsoleInputExW`](https://learn.microsoft.com/en-us/windows/console/readconsoleinputex) with `CONSOLE_READ_NOWAIT`. That had the same problem where it would get stuck in `ReadFile`.

Do we have to use overlapped IO here? We'd initiate a `ReadFile`, set the `hEvent` of `OVERLAPPED` to a new event (or even the one we created initially?), and then wait on the read and interrupts.

FWIW, I ran this from the integrated terminal in VS Code.

**Review by Nerixyz — COMMENTED** [review]
Tested with the same program and can confirm it working as well as the issue you mentioned in _Limitation_. 

I ran the shell tests and there's one test failing now: [`Settings/TestFrameFormatColor.test`](https://github.com/llvm/llvm-project/blob/8f58cfecae947da3ec7a3a08a1678bacc76e04ca/lldb/test/Shell/Settings/TestFrameFormatColor.test). It's only failing when I run all tests with `ninja check-lldb-shell`. When running the individual test with `llvm-lit.py` it's not failing.

I suspect the failure is due to the screen being flushed (the test only checks for `\x1b`). But looking at the output, there are no colors being added.

File: lldb/source/Host/windows/PseudoConsole.cpp [hunk 4]
```diff
@@ -133,3 +137,52 @@ void PseudoConsole::Close() {
...
+
+  auto attributelist_or_err = ProcThreadAttributeList::Create(startupinfoex);
+  if (!attributelist_or_err)
+    return llvm::errorCodeToError(attributelist_or_err.getError());
+  ProcThreadAttributeList attributelist = std::move(*attributelist_or_err);
+  if (auto error = attributelist.SetupPseudoConsole(m_conpty_handle))
+    return error;
+
+  PROCESS_INFORMATION pi = {};
+  wchar_t cmdline[] = L"cmd.exe /c 'echo foo && exit'";
```
Comment (Nerixyz) [inline lldb/source/Host/windows/PseudoConsole.cpp]: If we launch the windows command prompt, we should use the `COMSPEC` environment variable to look up the location. I think that's the most portable way.

File: lldb/source/Host/windows/PseudoConsole.cpp [hunk 5]
```diff
@@ -133,3 +137,52 @@ void PseudoConsole::Close() {
...
+    ReadFile(m_conpty_output, buf, sizeof(buf), &read, &ov);
+  }
+
+  CancelIo(m_conpty_output);
+  CloseHandle(ov.hEvent);
+  CloseHandle(pi.hProcess);
+  CloseHandle(pi.hThread);
+
+  return llvm::Error::success();
+}
```
Comment (Nerixyz) [inline lldb/source/Host/windows/PseudoConsole.cpp]:
```suggestion
}

```

**Review by Nerixyz — APPROVED** [review]
I'm guessing that launching a dummy process to clear the initialization is the most complete way.

Tested again and LLDB behaves as expected.

It would still be great if someone else could take a peek at this.

File: lldb/source/Host/windows/ProcessLauncherWindows.cpp [hunk 6]
```diff
@@ -137,15 +145,15 @@ ProcessLauncherWindows::LaunchProcess(const ProcessLaunchInfo &launch_info,
...
       [&] { DeleteProcThreadAttributeList(startupinfoex.lpAttributeList); });
 
   std::vector<HANDLE> inherited_handles;
   if (use_pty) {
-    if (!UpdateProcThreadAttribute(startupinfoex.lpAttributeList, 0,
-                                   PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE, hPC,
-                                   sizeof(hPC), NULL, NULL)) {
-      error = Status(::GetLastError(), eErrorTypeWin32);
+    if (auto err = attributelist.SetupPseudoConsole(hPC)) {
+      error = Status::FromError(std::move(err));
```
Comment (adrian-prantl) [inline lldb/source/Host/windows/ProcessLauncherWindows.cpp]: Would be nice to eventually refactor this method to return Error, too.

**Review by adrian-prantl — COMMENTED** [review]
LGTM with the change for LLDB_LOG_ERROR applied.
