### PR TITLE
[clang] Fix -Wdangling false negative regressions caused by 117315

### LINKED ISSUE #118064: [clang] No warning on dangling iterator of Set containers
All usages are dangling references below:
```cpp
#include <set>
#include <unordered_set>
#include <vector>

void sets() {
    auto x = std::set<int>{}.find(1);
    auto y = std::set<int>{}.begin();
    auto z = std::set<int>{}.end();
}
void sets2() {
    auto x = std::unordered_set<int>{}.find(1);
    auto y = std::unordered_set<int>{}.begin();
    auto z = std::unordered_set<int>{}.end();
}

void vector() {
    auto y2 = std::vector<int>{}.begin(); // Only warning here. Good!
}
```
https://godbolt.org/z/Mb4vr31P4

We might be missing `[[clang::lifetimebound]]` on these methods.

cc: @hokein

### PR DESCRIPTION
**Pull request by hokein**
A specialization declaration can have an attribute even if the primary template does not, particularly when the specialization is instantiated from an annotated using-alias declaration.

Fix #118064

### CODE REVIEW

**Review by usx95 — APPROVED** [review]
Thanks for quickly addressing this!

**Comment by hokein** [comment]
@usx95 Looks like I uploaded an incomplete version, please take another look.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 1]
```diff
@@ -258,9 +258,27 @@ template <typename T> static bool isRecordWithAttr(QualType Type) {
...
+  // cases where a full definition of the specialization is not required. In
+  // such cases, the specialization declaration remains incomplete and lacks the
+  // attribute. Therefore, we fall back to checking the primary template class.
+  //
+  // Note: it is possible for a specialization declaration to have an attribute
+  // even if the primary template does not.
+  //
+  // FIXME: What if the primary template and explicit specialization
+  // declarations have conflicting attributes? We should consider diagnosing
+  // this scenario.
```
Comment (usx95) [inline clang/lib/Sema/CheckExprLifetime.cpp:275]: I think this looks fine for now. Merging seems to be right thing for now.
Although merging Owner and Pointer seems problematic though which we should diagnose. Let's revisit if there is a need.

**Review by usx95 — APPROVED** [review]
