### PR TITLE
[TSan] Fix atomicrmw xchg with pointer and floats

### LINKED ISSUE #85226: [TSan] Invalid IR generated for atomicrmw with pointers
https://llvm.godbolt.org/z/o3nej9cKj
```llvm
; RUN: opt -S -passes=tsan
define void @atomic8_xchg_monotonic_ptr(ptr %a, ptr %b) {
entry:
  atomicrmw xchg ptr %a, ptr %b monotonic
  ret void
}
```

This produces:
```llvm
define void @atomic8_xchg_monotonic_ptr(ptr %a, ptr %b) {
entry:
  %0 = call ptr @llvm.returnaddress(i32 0)
  call void @__tsan_func_entry(ptr %0)
  %1 = zext ptr %b to i64
  %2 = call i64 @__tsan_atomic64_exchange(ptr %a, i64 %1, i32 0)
  call void @__tsan_func_exit()
  ret void
}
```

### PR DESCRIPTION
**Pull request by nikic**
atomicrmw xchg also accepts pointer and floating-point values. To handle those, insert a necessary casts to and from integer. This is what we do for cmpxchg as well.

Fixes https://github.com/llvm/llvm-project/issues/85226.

### CODE REVIEW

File: llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp [hunk 1]
```diff
@@ -752,11 +752,12 @@ bool ThreadSanitizer::instrumentAtomic(Instruction *I, const DataLayout &DL) {
...
     Type *Ty = Type::getIntNTy(IRB.getContext(), BitSize);
-    Value *Args[] = {Addr,
-                     IRB.CreateIntCast(RMWI->getValOperand(), Ty, false),
+    Value *Val = RMWI->getValOperand();
+    Value *Args[] = {Addr, IRB.CreateBitOrPointerCast(Val, Ty),
                      createOrdering(&IRB, RMWI->getOrdering())};
-    CallInst *C = CallInst::Create(F, Args);
-    ReplaceInstWithInst(I, C);
+    Value *C = IRB.CreateCall(F, Args);
+    I->replaceAllUsesWith(IRB.CreateBitOrPointerCast(C, Val->getType()));
```
Comment (vitalybuka) [inline llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp:759]: Looks like `replaceAllUsesWith/eraseFromParent` matches `ReplaceInstWithInst`
However, could we keep code consistent?
Replacing all places in a separate patch LGTM.

**Review by vitalybuka — APPROVED** [review]

File: llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp (hunk 1 above)
Comment (nikic) [reply llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp:759]: The reason I changed this is that we now go through IRBuilder, which will insert the instructions itself, so we can no longer use ReplaceInstWithInst. This is also why the cmpxchg code does the same.

Comment (nikic) [reply llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp:759]: Converted the remaining uses in https://github.com/llvm/llvm-project/commit/8a237ab7d9022d24441544ba25be480f0c944f5a.

Comment (vitalybuka) [reply llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp:759]: Thanks!
