### PR TITLE
[InstCombine] Simplify with.overflow intrinsics with assumption information

### LINKED ISSUE #509: LLVM failed to use the knowledge from a never-overflow assumption
Hi all, I am an LLVM developer working on the middle-end optimizations.

Recently I found an anti-pattern in some Rust applications from my [benchmark](https://github.com/dtcxzyw/llvm-opt-benchmark).  All of them come from `hashbrown::raw::RawTableInner::free_buckets`:
https://github.com/rust-lang/hashbrown/blob/274c7bbd79398881e0225c0133e423ce60d7a8f1/src/raw/mod.rs#L3290-L3294

LLVM IR:
```
define i32 @src(i32 %x, i32 %y) {
  %res = call { i32, i1 } @llvm.umul.with.overflow.i32(i32 %x, i32 %y)
  %ov = extractvalue { i32, i1 } %res, 1
  %nowrap = xor i1 %ov, true
  tail call void @llvm.assume(i1 %nowrap)
  %val = extractvalue { i32, i1 } %res, 0
  ret i32 %val
}
define i32 @tgt(i32 %x, i32 %y) {
  %res = mul nuw i32 %x, %y
  ret i32 %res
}
```
Alive2: https://alive2.llvm.org/ce/z/YBRjxc

Currently LLVM cannot use the knowledge from a never-overflow assumption. I have a draft patch for the fold and it enables more optimizations in downstream users of `hashbrown`.  But I am not willing to do an application-specific optimization in LLVM. So I file this issue to see whether we can fix it in `hashbrown`.

cc @nikic @DianQK

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch recognizes never-overflow assumptions generated by rustc to improve the codegen.
Please refer to https://github.com/rust-lang/hashbrown/issues/509 for more details.

Closes https://github.com/rust-lang/hashbrown/issues/509
Closes https://github.com/llvm/llvm-project/issues/80637

### CODE REVIEW

**Comment by dtcxzyw** [comment]
Closed in favor of https://github.com/rust-lang/rust/pull/122282.

**Comment by dtcxzyw** [comment]
@DianQK Should I close this PR since https://github.com/rust-lang/rust/pull/122975 landed?

**Comment by DianQK** [comment]
> @DianQK Should I close this PR since [rust-lang/rust#122975](https://github.com/rust-lang/rust/pull/122975) landed?

I believe it will take at least two more PRs to resolve this issue. The first one is https://github.com/rust-lang/rust/pull/123256#issuecomment-2029075872.

Given the differences in inlining rules between Rust and LLVM, there are likely some edge cases that still cannot be resolved.

**Comment by antoniofrighetto** [comment]
This looks ready and https://github.com/rust-lang/rust/pull/122975 looks orthogonal to me, should we undraft it?

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 1]
```diff
@@ -818,6 +818,33 @@ InstCombinerImpl::foldIntrinsicWithOverflowCommon(IntrinsicInst *II) {
...
+    if (!match(U, m_ExtractValue<1>(m_Value())))
+      continue;
+
+    for (auto &AssumeVH : AC.assumptionsFor(U)) {
+      if (!AssumeVH)
+        continue;
+      CallInst *I = cast<CallInst>(AssumeVH);
+      if (!match(I->getArgOperand(0), m_Not(m_Specific(U))))
+        continue;
+      if (!isValidAssumeForContext(I, II, &DT))
```
Comment (andjo403) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp:833]: is it not a waist to add the DT here as we know that the assume will always be after  the WithOverflow Instruction?
also shall the AllowEphemerals be set to true as we try to change the condition for the assume?
```
define i1 @ephemeral_call_assume_no_overflow(i8 noundef %a, i8 noundef %b) {
; CHECK-LABEL: @ephemeral_call_assume_no_overflow(
; CHECK-NEXT:    ret i1 true
;
  %call = call { i8, i1 } @llvm.smul.with.overflow.i8(i8 %a, i8 %b)
  %overflow = extractvalue { i8, i1 } %call, 1
  %not = xor i1 %overflow, true
  call void @llvm.assume(i1 %not)
  ret i1 %not
}
```

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 2]
```diff
@@ -818,6 +818,33 @@ InstCombinerImpl::foldIntrinsicWithOverflowCommon(IntrinsicInst *II) {
...
+        continue;
+      Value *Result =
+          Builder.CreateBinOp(WO->getBinaryOp(), WO->getLHS(), WO->getRHS());
```
Comment (andjo403) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp:836]: OptimizeOverflowCheck also take the name of the WO instruction shall it be done here also?

**Comment by andjo403** [comment]
Looks good to me

**Review by nikic — APPROVED** [review]
LGTM
