### PR TITLE
[NVPTX] Pull invariant load identification into IR pass

### LINKED ISSUE #138138: [NVPTX] Backend crash on byval reference to external constant
The following code was regressed since the LLVM 20 release and now crashes in the libc test suite. The reproducer is at https://godbolt.org/z/Pjc4nT88P. If you remove the `byval` it works, so I'm assuming that's where the error lies.

### PR DESCRIPTION
**Pull request by AlexMaclean**
Pull invariant load identification, which was previously part of DAGToDAG ISel, into a new IR pass NVPTXTagInvariantLoads. This makes it possible to disable this optimization at O0 and reduces the complexity of the SelectionDAG pass. Moving this logic to an IR pass also allows for implementing a more powerful traversal in the future.

Fixes https://github.com/llvm/llvm-project/issues/138138

### CODE REVIEW

File: llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp [hunk 1]
```diff
@@ -766,46 +766,12 @@ NVPTX::Scope NVPTXDAGToDAGISel::getOperationScope(MemSDNode *N,
   llvm_unreachable("unhandled ordering");
 }
 
-static bool canLowerToLDG(MemSDNode *N, const NVPTXSubtarget &Subtarget,
-                          unsigned CodeAddrSpace, MachineFunction *F) {
+static bool canLowerToLDG(const MemSDNode *N, const NVPTXSubtarget &Subtarget,
```
Comment (Artem-B) [inline llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp:769]: May as well make N a constref.

File: llvm/lib/Target/NVPTX/NVPTXTagInvariantLoads.cpp [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+//
+//===----------------------------------------------------------------------===//
+//
+// This file implements invaraint load tagging. It traverses load instructions
+// in a function, and determines if each load can be tagged as invariant.
+//
+// We currently infer invariance for loads from
+//  - constant global variables, and
+//  - kernel function pointer params that are noalias (i.e. __restrict) and
+//    never written to.
```
Comment (Artem-B) [inline llvm/lib/Target/NVPTX/NVPTXTagInvariantLoads.cpp:15]: We can also consider grid constant arguments.

**Review by Artem-B — APPROVED** [review]
LGTM

File: llvm/test/CodeGen/NVPTX/byval-const-global.ll [hunk 3]
```diff
@@ -0,0 +1,33 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
+; RUN: llc < %s -mcpu=sm_20 | FileCheck %s
```
Comment (jhuber6) [inline llvm/test/CodeGen/NVPTX/byval-const-global.ll:2]: FYI, the original issue only reproduced at higher `sm` values https://godbolt.org/z/654zYKo4o. So I'd recommend increasing this.

Comment (AlexMaclean) [reply llvm/test/CodeGen/NVPTX/byval-const-global.ll]: Fixed!

**Review by jhuber6 — APPROVED** [review]

**Comment by fmayer** [comment]
FYI this broke the GN build

```
ld.lld: error: undefined symbol: llvm::initializeNVPTXTagInvariantLoadLegacyPassPass(llvm::PassRegistry&)
>>> referenced by NVPTXTargetMachine.cpp
>>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:(LLVMInitializeNVPTXTarget) in archive lib/libLLVMNVPTXCod
eGen.a                      
                                                                       
ld.lld: error: undefined symbol: llvm::createNVPTXTagInvariantLoadsPass()
>>> referenced by NVPTXTargetMachine.cpp                                                                                                       
>>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:((anonymous namespace)::NVPTXPassConfig::addIRPasses()) in archive lib/libLLVMNVPTXCodeGen.a

ld.lld: error: undefined symbol: llvm::NVPTXTagInvariantLoadsPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)
>>> referenced by NVPTXTargetMachine.cpp
>>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:(llvm::detail::PassModel<llvm::Function, llvm::NVPTXTagInv
ariantLoadsPass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)) in archive lib/libLLVMNV
PTXCodeGen.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jhuber6** [comment]
> FYI this broke the GN build
> 
> ```
> ld.lld: error: undefined symbol: llvm::initializeNVPTXTagInvariantLoadLegacyPassPass(llvm::PassRegistry&)
> >>> referenced by NVPTXTargetMachine.cpp
> >>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:(LLVMInitializeNVPTXTarget) in archive lib/libLLVMNVPTXCod
> eGen.a                      
>                                                                        
> ld.lld: error: undefined symbol: llvm::createNVPTXTagInvariantLoadsPass()
> >>> referenced by NVPTXTargetMachine.cpp                                                                                                       
> >>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:((anonymous namespace)::NVPTXPassConfig::addIRPasses()) in archive lib/libLLVMNVPTXCodeGen.a
> 
> ld.lld: error: undefined symbol: llvm::NVPTXTagInvariantLoadsPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)
> >>> referenced by NVPTXTargetMachine.cpp
> >>>               ../obj/llvm/lib/Target/NVPTX/LLVMNVPTXCodeGen.NVPTXTargetMachine.o:(llvm::detail::PassModel<llvm::Function, llvm::NVPTXTagInv
> ariantLoadsPass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)) in archive lib/libLLVMNV
> PTXCodeGen.a
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Missing dependency for a static build maybe?

**Comment by AlexMaclean** [comment]
@fmayer sorry about that! I'm very unfamiliar with the GN build. I suppose that this file may need to be updated to add the new source file? It looks like a bot normally does this automatically? https://github.com/llvm/llvm-project/blob/b2e2ae8702e9fbbe0ef0eb5929aa2d5dc867b1c5/llvm/utils/gn/secondary/llvm/lib/Target/NVPTX/BUILD.gn#L30-L34
