### PR TITLE
[Clang] Fix various bugs in alias CTAD transform

### LINKED ISSUE #123591: Clang frontend command failed with exit code 139
Hi, 

I've been experimenting with ways to model an AST in modern C++. During one of these experiments, my compiler crashed on me. Per request of the compiler itself, I've attached the output and the associated culprit files below. 

The issue seems to arise from a leftover `template <typename T>`  declaration:
```
template <typename T>  // <<< right here, sorry!
using AstNode = std::variant<AstProgram, AstDecl, AstExpr, AstStmt>;
```
I accidentally left it in place when I was restructuring the program. Once I remove the declaration, the program still doesn't compile (that's correct), but the compiler doesn't crash anymore.

---

[main-8471ef.tar.gz](https://github.com/user-attachments/files/18476429/main-8471ef.tar.gz)

```
Stack dump:
0.	Program arguments: clang++ -std=c++20 -Wall -Wextra -Wconversion -Wpedantic -funsigned-char -fsanitize=address,undefined -fno-omit-frame-pointer -g3 -glldb -O0 -c -o target/main.o src/main.cc
1.	src/main.cc:69:112: current parser token ';'
2.	src/main.cc:68:1: parsing function body 'main'
3.	src/main.cc:68:1: in compound statement ('{}')
 #0 0x00007fd90b8b0a8a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xeb0a8a)
 #1 0x00007fd90b8ae634 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xeae634)
 #2 0x00007fd90b7f44f4 (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xdf44f4)
 #3 0x00007fd90a449da0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fda0)
 #4 0x00007fd913a850e4 clang::TemplateArgument::isPackExpansion() const (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x12850e4)
 #5 0x00007fd914631acb clang::Sema::getFullyPackExpandedSize(clang::TemplateArgument) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1e31acb)
 #6 0x00007fd9145bf020 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1dbf020)
 #7 0x00007fd9145c8bcb (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1dc8bcb)
 #8 0x00007fd91459a425 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1d9a425)
 #9 0x00007fd9145d2ab0 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1dd2ab0)
#10 0x00007fd9145d9867 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1dd9867)
#11 0x00007fd9145d6d6d (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1dd6d6d)
#12 0x00007fd91459348b (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1d9348b)
#13 0x00007fd91459a3a7 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1d9a3a7)
#14 0x00007fd91459a232 clang::Sema::SubstTemplateArgument(clang::TemplateArgumentLoc const&, clang::MultiLevelTemplateArgumentList const&, clang::TemplateArgumentLoc&, clang::SourceLocation, clang::DeclarationName const&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1d9a232)
#15 0x00007fd91445daab (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1c5daab)
#16 0x00007fd91445d57e clang::Sema::SubstDefaultTemplateArgumentIfAvailable(clang::TemplateDecl*, clang::SourceLocation, clang::SourceLocation, clang::Decl*, llvm::ArrayRef<clang::TemplateArgument>, llvm::ArrayRef<clang::TemplateArgument>, bool&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1c5d57e)
#17 0x00007fd9144e3c61 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1ce3c61)
#18 0x00007fd91454001b (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1d4001b)
#19 0x00007fd913d93671 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1593671)
#20 0x00007fd9144e5c1b clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1ce5c1b)
#21 0x00007fd9143cb434 clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1bcb434)
#22 0x00007fd9142a0847 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1aa0847)
#23 0x00007fd914293c39 (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1a93c39)
#24 0x00007fd9142930d9 clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1a930d9)
#25 0x00007fd913f4a1f2 clang::Sema::deduceVarTypeFromInitializer(clang::VarDecl*, clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::SourceRange, bool, clang::Expr*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x174a1f2)
#26 0x00007fd913f4a920 clang::Sema::DeduceVariableDeclarationType(clang::VarDecl*, bool, clang::Expr*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x174a920)
#27 0x00007fd913f4b03c clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x174b03c)
#28 0x00007fd91344e3c1 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc4e3c1)
#29 0x00007fd91344b0c9 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc4b0c9)
#30 0x00007fd91344a4f5 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc4a4f5)
#31 0x00007fd913449e79 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc49e79)
#32 0x00007fd9134e9779 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xce9779)
#33 0x00007fd9134e7a6a clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xce7a6a)
#34 0x00007fd9134f05b0 clang::Parser::ParseCompoundStatementBody(bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xcf05b0)
#35 0x00007fd9134f16f6 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xcf16f6)
#36 0x00007fd91350b8e3 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd0b8e3)
#37 0x00007fd91344c46d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc4c46d)
#38 0x00007fd91350a8be clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd0a8be)
#39 0x00007fd91350a25f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd0a25f)
#40 0x00007fd91350944c clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd0944c)
#41 0x00007fd9135078d7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd078d7)
#42 0x00007fd91343457e clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc3457e)
#43 0x00007fd915547379 clang::FrontendAction::Execute() (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2d47379)
#44 0x00007fd9154b5c74 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2cb5c74)
#45 0x00007fd9155c57fe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2dc57fe)
#46 0x000055891017bc61 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-19/bin/clang+0x11c61)
#47 0x0000558910178b35 (/usr/lib/llvm-19/bin/clang+0xeb35)
#48 0x00007fd91513509d (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x293509d)
#49 0x00007fd90b7f4290 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xdf4290)
#50 0x00007fd915134b31 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2934b31)
#51 0x00007fd9150f9ec8 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x28f9ec8)
#52 0x00007fd9150fa13e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x28fa13e)
#53 0x00007fd9151178fc clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x29178fc)
#54 0x0000558910178574 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm-19/bin/clang+0xe574)
#55 0x00005589101864ba main (/usr/lib/llvm-19/bin/clang+0x1c4ba)
#56 0x00007fd90a433d68 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#57 0x00007fd90a433e25 call_init ./csu/../csu/libc-start.c:128:20
#58 0x00007fd90a433e25 __libc_start_main ./csu/../csu/libc-start.c:347:5
#59 0x0000558910176731 _start (/usr/lib/llvm-19/bin/clang+0xc731)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Debian clang version 19.1.6 (1+b1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/main-8471ef.cpp
clang++: note: diagnostic msg: /tmp/main-8471ef.sh
clang++: note: diagnostic msg: 

********************
```

### LINKED ISSUE #127539: [Clang] Crash on CTAD for alias template involving variadics
```c++
template <class...>
struct A {
    template <class... ArgTs>
    A(ArgTs...) {}
};

template <class... ArgTs>
A(ArgTs...) -> A<typename ArgTs::value_type...>;

template <class... Ts>
using AA = A<Ts...>;

AA a{};
```

See https://compiler-explorer.com/z/3c8bYM5To.

Unreachable:
```console
Can't get a NULL template argument here
UNREACHABLE executed at /root/llvm-project/clang/lib/Sema/SemaTemplateDeduction.cpp:2894!
```

<details>

<summary>Stack dump</summary>

```console
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:13:7: current parser token ';'
 #0 0x0000000003e9bfd8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e9bfd8)
 #1 0x0000000003e99c94 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e99c94)
 #2 0x0000000003de6098 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000072f907a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000072f907a969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000072f907a42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000072f907a287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000000003df19fa (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3df19fa)
 #8 0x0000000006f33f4c clang::Sema::getTrivialTemplateArgumentLoc(clang::TemplateArgument const&, clang::QualType, clang::SourceLocation, clang::NamedDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f33f4c)
 #9 0x0000000007046a57 (anonymous namespace)::TemplateInstantiator::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) SemaTemplateInstantiate.cpp:0:0
#10 0x000000000704851e clang::Sema::SubstTemplateArgument(clang::TemplateArgumentLoc const&, clang::MultiLevelTemplateArgumentList const&, clang::TemplateArgumentLoc&, clang::SourceLocation, clang::DeclarationName const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x704851e)
#11 0x0000000006fa3827 (anonymous namespace)::BuildDeductionGuideForTypeAlias(clang::Sema&, clang::TypeAliasTemplateDecl*, clang::FunctionTemplateDecl*, clang::SourceLocation) SemaTemplateDeductionGuide.cpp:0:0
#12 0x0000000006fe8b75 clang::Sema::DeclareImplicitDeductionGuides(clang::TemplateDecl*, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fe8b75)
#13 0x0000000006bd4517 LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) SemaLookup.cpp:0:0
#14 0x0000000006bbf842 clang::Sema::LookupQualifiedName(clang::LookupResult&, clang::DeclContext*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bbf842)
#15 0x0000000006b9e2fe clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b9e2fe)
#16 0x0000000006825c1d clang::Sema::deduceVarTypeFromInitializer(clang::VarDecl*, clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::SourceRange, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6825c1d)
#17 0x000000000682a9e7 clang::Sema::DeduceVariableDeclarationType(clang::VarDecl*, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x682a9e7)
#18 0x0000000006849282 clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6849282)
#19 0x00000000064d89f5 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64d89f5)
#20 0x00000000064e7f19 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64e7f19)
#21 0x00000000064a791e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64a791e)
#22 0x00000000064a80d9 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64a80d9)
#23 0x00000000064af883 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64af883)
#24 0x00000000064b077d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64b077d)
#25 0x00000000064a2c1a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64a2c1a)
#26 0x000000000485dbb8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x485dbb8)
#27 0x0000000004b24a55 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b24a55)
#28 0x0000000004aa835e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4aa835e)
#29 0x0000000004c1324e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c1324e)
#30 0x0000000000d65b8f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd65b8f)
#31 0x0000000000d5d60a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#32 0x00000000048a41c9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#33 0x0000000003de6544 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3de6544)
#34 0x00000000048a47bf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#35 0x000000000486793d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x486793d)
#36 0x00000000048689be clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48689be)
#37 0x0000000004870975 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4870975)
#38 0x0000000000d62983 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd62983)
#39 0x0000000000c2b674 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc2b674)
#40 0x000072f907a29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#41 0x000072f907a29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#42 0x0000000000d5d0b5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd5d0b5)
```

</details>

### LINKED ISSUE #129077: [rejects valid] CTAD failing for alias template
i believe (and a few folks in CWG agree) that the following code should compile. GCC trunk accepts it.

```c++
using size_t = decltype(sizeof(0));

struct index_type
{
  size_t value{~0ull};
  index_type() = default;
  constexpr index_type(size_t i) noexcept : value(i) {}
};

template <index_type... Extents>
struct extents
{
  constexpr extents(decltype(Extents)...) noexcept {}
};

template <class... Extents>
extents(Extents...) -> extents<(requires { Extents::value; } ? Extents{} : ~0ull)...>;

template <index_type... Index>
using index = extents<Index...>;

int main()
{
  extents i{0,0};
  auto j = extents<64,{}>({}, 42);

  index k{0,0};
  auto l = index<64,{}>({}, 42);
}
```

<details>

<summary>Diagnostic:</summary>

```
<source>:27:9: error: no viable constructor or deduction guide for deduction of template arguments of 'index'
   27 |   index k{0,0};
      |         ^
<source>:20:1: note: candidate template ignored: substitution failure: deduced incomplete pack <(no value), (no value)> for template parameter 'Extents'
   10 | template <index_type... Extents>
      |                         ~~~~~~~
   11 | struct extents
   12 | {
   13 |   constexpr extents(decltype(Extents)...) noexcept {}
   14 | };
   15 | 
   16 | template <class... Extents>
   17 | extents(Extents...) -> extents<(requires { Extents::value; } ? Extents{} : ~0ull)...>;
   18 | 
   19 | template <index_type... Index>
   20 | using index = extents<Index...>;
      | ^
<source>:20:1: note: implicit deduction guide declared as 'template <index_type ...Extents> requires __is_deducible(index, extents<Extents...>) index(decltype(Extents) ...) -> extents<Extents...>'
<source>:20:1: note: candidate function template not viable: requires 1 argument, but 2 were provided
   11 | struct extents
      |        ~~~~~~~
   12 | {
   13 |   constexpr extents(decltype(Extents)...) noexcept {}
   14 | };
   15 | 
   16 | template <class... Extents>
   17 | extents(Extents...) -> extents<(requires { Extents::value; } ? Extents{} : ~0ull)...>;
   18 | 
   19 | template <index_type... Index>
   20 | using index = extents<Index...>;
      | ^
<source>:20:1: note: implicit deduction guide declared as 'template <index_type ...Extents> requires __is_deducible(index, extents<Extents...>) index(extents<Extents...>) -> extents<Extents...>'
<source>:20:1: note: candidate template ignored: constraints not satisfied
<source>:20:1: note: cannot deduce template arguments for 'index' from 'extents<(requires { Extents::value; } ? Extents{} : ~0ULL)...>'
<source>:20:1: note: implicit deduction guide declared as 'template <> requires __is_deducible(index, extents<(requires { Extents::value; } ? Extents{} : ~0ULL)...>) index(Extents ...) -> extents<(requires { Extents::value; } ? Extents{} : ~0ULL)...>'
```

</details>

See https://godbolt.org/z/qxsTWGsdx

Christof Meerwald (@cmeerw) of CWG explains it thusly:

> You try to deduce `extents<(requires { Extents::value; } ? Extents{} : ~0ull)...>` from `extents<Index...>` (but can't deduce anything). As you didn't deduce anything, substituting into the original deduction guide doesn't change anything. So your `f'` is the same as `f` (and as you haven't deduced anything, you only use the template parameters from the original deduction guide, but none from the alias template). After doing deduction for `f'`, the only thing left to do is the deducible check (which also succeeds).

this issue seems distinct from #111216.

### LINKED ISSUE #129620: [Clang] Crash on CTAD for alias template declared with respect to another alias template
```c++
template <class... Ts>
struct A {
    constexpr A(Ts...) {}
};

template <class... Ts>
using Foo = A<Ts...>;

template <class T>
using Bar = Foo<T, T>;

Bar a{0, 0};
```

See https://compiler-explorer.com/z/rzhxc7nPv.

Assertion:
```console
clang++: /root/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp:1474:
static clang::TemplateArgument {anonymous}::TemplateInstantiator::getTemplateArgumentPackPatternForRewrite(const clang::TemplateArgument&):
Assertion `TA.pack_size() == 1 && "unexpected pack arguments in template rewrite"' failed.
```

<details>

<summary>Stack dump</summary>

```console
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:12:12: current parser token ';'
 #0 0x0000000003e53898 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e53898)
 #1 0x0000000003e51554 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e51554)
 #2 0x0000000003d9de88 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007b90cb442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007b90cb4969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007b90cb442476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007b90cb4287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007b90cb42871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007b90cb439e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006f462e3 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f462e3)
#10 0x0000000006f4fa50 clang::declvisitor::Base<std::add_pointer, clang::TemplateDeclInstantiator, clang::Decl*>::Visit(clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f4fa50)
#11 0x0000000006f7f52d clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#12 0x0000000006f83baa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) SemaTemplateInstantiate.cpp:0:0
#13 0x0000000006f83ccc clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::QualType) SemaTemplateInstantiate.cpp:0:0
#14 0x0000000006f84840 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformSubstTemplateTypeParmType(clang::TypeLocBuilder&, clang::SubstTemplateTypeParmTypeLoc) SemaTemplateInstantiate.cpp:0:0
#15 0x0000000006f7f42d clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#16 0x0000000006f83baa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) SemaTemplateInstantiate.cpp:0:0
#17 0x0000000006fa0bbd (anonymous namespace)::TemplateInstantiator::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) SemaTemplateInstantiate.cpp:0:0
#18 0x0000000006fa294f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) SemaTemplateInstantiate.cpp:0:0
#19 0x0000000006f7ff36 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#20 0x0000000006f80781 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTypeTraitExpr(clang::TypeTraitExpr*) SemaTemplateInstantiate.cpp:0:0
#21 0x0000000006f880ff clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#22 0x0000000006fb23d2 clang::Sema::SubstExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fb23d2)
#23 0x0000000006efde0c (anonymous namespace)::buildAssociatedConstraints(clang::Sema&, clang::FunctionTemplateDecl*, clang::TypeAliasTemplateDecl*, llvm::ArrayRef<clang::DeducedTemplateArgument>, unsigned int, clang::Expr*) SemaTemplateDeductionGuide.cpp:0:0
#24 0x0000000006f018d8 (anonymous namespace)::BuildDeductionGuideForTypeAlias(clang::Sema&, clang::TypeAliasTemplateDecl*, clang::FunctionTemplateDecl*, clang::SourceLocation) SemaTemplateDeductionGuide.cpp:0:0
#25 0x0000000006f43cc5 clang::Sema::DeclareImplicitDeductionGuides(clang::TemplateDecl*, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f43cc5)
#26 0x0000000006b2fd17 LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) SemaLookup.cpp:0:0
#27 0x0000000006b1b012 clang::Sema::LookupQualifiedName(clang::LookupResult&, clang::DeclContext*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b1b012)
#28 0x0000000006af9c2e clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af9c2e)
#29 0x000000000677e43d clang::Sema::deduceVarTypeFromInitializer(clang::VarDecl*, clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::SourceRange, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x677e43d)
#30 0x0000000006783207 clang::Sema::DeduceVariableDeclarationType(clang::VarDecl*, bool, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6783207)
#31 0x00000000067a19a2 clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67a19a2)
#32 0x0000000006430345 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6430345)
#33 0x000000000643f8c9 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x643f8c9)
#34 0x00000000063ff73e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63ff73e)
#35 0x00000000063ffef9 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63ffef9)
#36 0x00000000064076d3 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64076d3)
#37 0x00000000064085ad clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64085ad)
#38 0x00000000063faa3a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63faa3a)
#39 0x0000000004812598 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4812598)
#40 0x0000000004ada245 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ada245)
#41 0x0000000004a5d92e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a5d92e)
#42 0x0000000004bc809e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4bc809e)
#43 0x0000000000d4ab2f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd4ab2f)
#44 0x0000000000d4244a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#45 0x000000000485a4c9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#46 0x0000000003d9e334 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d9e334)
#47 0x000000000485aabf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#48 0x000000000481d6dd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x481d6dd)
#49 0x000000000481e75e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x481e75e)
#50 0x00000000048266f5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48266f5)
#51 0x0000000000d47923 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd47923)
#52 0x0000000000c11464 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc11464)
#53 0x00007b90cb429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#54 0x00007b90cb429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#55 0x0000000000d41ef5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd41ef5)
```

</details>

### LINKED ISSUE #129998: [ICE-on-valid] CTAD through alias template causes crash in `TemplateArgument::getNonTypeTemplateArgumentType`
The following code, compiled with `-std=c++23` with the latest compiler from trunk, causes clang to ICE. I believe the code is conforming, and gcc trunk accepts it.

```c++
#include <concepts>
#include <cstdint>
#include <limits>
#include <span>
#include <type_traits>
#include <utility>

template <auto Nullopt>
struct inline_optional;

namespace detail
{
  template <auto Type>
  concept _integral_wrapper = std::integral<decltype(Type)>;

  template <class... Ts>
  consteval auto _dynamic_extent_of_helper(Ts...) noexcept
  {
    using integral_t = std::common_type_t<Ts...>;
    if constexpr (std::unsigned_integral<integral_t>)
    {
      return std::numeric_limits<integral_t>::max();
    }
    else
    {
      return std::numeric_limits<integral_t>::min();
    }
  }

  template <class... Ts>
  constexpr auto _dynamic_extent_of = detail::_dynamic_extent_of_helper(+Ts{}...);

  template <class Type, class... Ts>
  constexpr auto _tparam_for = (std::integral<Type> ? inline_optional<_dynamic_extent_of<Ts...>>{} : +Type{});
} // namespace detail

template <auto Value>
using constant = std::integral_constant<decltype(Value), Value>;

template <class Type>
concept integral_wrapper = detail::_integral_wrapper<Type::value> && requires {
  { auto(Type::value) } -> std::same_as<typename Type::value_type>;
};

template <class Type>
concept integral_like = std::integral<Type> || integral_wrapper<Type>;

template <auto Nullopt>
struct inline_optional
{
  using value_type  = decltype(Nullopt);

  inline_optional() = default;

  constexpr inline_optional(value_type v) noexcept
      : value_(v)
  {}

  template <auto OtherNullopt>
  constexpr inline_optional(inline_optional<OtherNullopt> other) noexcept
      : value_(other.has_value() ? static_cast<value_type>(other.value()) : Nullopt)
  {
  }

  constexpr auto operator*() const noexcept -> value_type
  {
    return value_;
  }

  constexpr auto value() const noexcept -> value_type
  {
    return value_;
  }

  constexpr auto has_value() const noexcept -> bool
  {
    return value_ != Nullopt;
  }

  auto operator==(inline_optional const& other) const noexcept -> bool = default;

  value_type value_{Nullopt};
  static constexpr value_type nullopt = Nullopt;
};

struct empty
{
  empty() = default;
  constexpr empty(integral_wrapper auto) noexcept {}
};

template <auto V>
using _typeof = decltype(auto(V));

template <class IndexType, IndexType Dyn>
struct _extents
{
  using index_type = IndexType;

  template <index_type... Extents>
  struct type;

  template <index_type A, index_type B>
  struct type<A, B>
  {
    static constexpr auto i = A.value();
    static constexpr auto j = B.value();
    empty _i, _j;
  };

  template <index_type A>
  struct type<A, Dyn>
  {
    static constexpr int i = A.value();
    empty _i;
    int j;
  };

  template <class... Extents>
  type(Extents...) -> type<(std::integral<Extents> ? Dyn : +Extents{})...>;
};

using extent64_t = inline_optional<detail::_dynamic_extent_of<std::uint64_t>>;

template <extent64_t... Extents>
using extents = _extents<extent64_t, {}>::type<Extents...>;

[[deprecated]] void print(auto) {}

int main()
{
  extents<0, {}> e{{}, 42};
  _extents<extent64_t, {}>::type t{constant<1>{},2};
  extents t2{constant<1>{},2};
}
```

The stack trace:

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<source>:134:30: current parser token ';'
2.	<source>:131:1: parsing function body 'main'
3.	<source>:131:1: in compound statement ('{}')
 #0 0x0000000003b4d588 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b4d588)
 #1 0x0000000003b4b6cc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b4b6cc)
 #2 0x0000000003a9aa78 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007e0449442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000000000759c68f clang::TemplateArgument::getNonTypeTemplateArgumentType() const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x759c68f)
 #5 0x0000000006b04c68 checkDeducedTemplateArguments(clang::ASTContext&, clang::DeducedTemplateArgument const&, clang::DeducedTemplateArgument const&, bool) (.part.0) SemaTemplateDeduction.cpp:0:0
 #6 0x0000000006b0e8a4 (anonymous namespace)::PackDeductionScope::finish() (.part.0) SemaTemplateDeduction.cpp:0:0
 #7 0x0000000006b5763f clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6b5763f)
 #8 0x000000000695cdc0 clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x695cdc0)
 #9 0x000000000674533a clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>)::'lambda0'(bool)::operator()(bool) const SemaInit.cpp:0:0
#10 0x0000000006745cb2 clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6745cb2)
#11 0x00000000063bba08 clang::Sema::deduceVarTypeFromInitializer(clang::VarDecl*, clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::SourceRange, bool, clang::Expr*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x63bba08)
#12 0x00000000063d84bb clang::Sema::DeduceVariableDeclarationType(clang::VarDecl*, bool, clang::Expr*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x63d84bb)
#13 0x0000000006400a8c clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6400a8c)
#14 0x0000000006079fee clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6079fee)
#15 0x000000000608f76c clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x608f76c)
#16 0x000000000609228a clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x609228a)
#17 0x000000000609278f clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x609278f)
#18 0x0000000006147ea4 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6147ea4)
#19 0x00000000061487fd clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61487fd)
#20 0x0000000006149b14 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6149b14)
#21 0x000000000614acca clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x614acca)
#22 0x0000000006045bf6 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6045bf6)
#23 0x000000000608fbcf clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x608fbcf)
#24 0x000000000603e1b7 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x603e1b7)
#25 0x000000000603efce clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x603efce)
#26 0x00000000060488d2 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x60488d2)
#27 0x000000000604a168 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x604a168)
#28 0x000000000603880a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x603880a)
#29 0x00000000044c8ff5 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44c8ff5)
#30 0x00000000047a3241 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x47a3241)
#31 0x0000000004723e7b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4723e7b)
#32 0x0000000004890233 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4890233)
#33 0x0000000000d63321 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd63321)
#34 0x0000000000d5bb2d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#35 0x0000000004515569 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#36 0x0000000003a9aea3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a9aea3)
#37 0x0000000004515789 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#38 0x00000000044d95ad clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44d95ad)
#39 0x00000000044da541 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44da541)
#40 0x00000000044e497c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44e497c)
#41 0x0000000000d5ffe1 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd5ffe1)
#42 0x0000000000c21914 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc21914)
#43 0x00007e0449429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#44 0x00007e0449429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#45 0x0000000000d5b5c5 _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd5b5c5)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

Demo:
https://godbolt.org/z/9WsPov173

EDIT: With assertions enabled, I get:

```
Can't get a NULL template argument here
UNREACHABLE executed at /root/llvm-project/clang/lib/Sema/SemaTemplateDeduction.cpp:2894!
```

https://github.com/llvm/llvm-project/blob/6e7e46cafeccab761d31e6404ceb0cdef4c18bd4/clang/lib/Sema/SemaTemplateDeduction.cpp#L2894

### PR DESCRIPTION
**Pull request by zyn0217**
This fixes the CTAD transform in two ways:

1. When the original deduction guide (i.e. the deduction guide against which we're building the alias CTAD) contains a default template parameter involving a `sizeof...` expression, we no longer compute the size heuristically. This is based on the fact that we're never going to create any `Subst*` nodes during CTAD rewrite, which makes that algorithm inapplicable. Instead, we fall through to ordinary template argument substitution wherein we'll try to expand the rewrite packs.

The bug has been facilitated by my previous patch fd4f94ddb before which we never correctly substituted these default arguments with the transformed template parameters.

2. We failed to handle cases where non-deduced template parameters involve packs. In some cases, the Deduced argument list is a pack containing a single null argument. These should be treated as non-deduced parameters, or we'll crash during transform.

Fixes #123591
Fixes #127539
Fixes #129077
Fixes #129620
Fixes #129998

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp [hunk 1]
```diff
@@ -1077,7 +1077,11 @@ BuildDeductionGuideForTypeAlias(Sema &SemaRef,
   // !!NOTE: DeduceResults respects the sequence of template parameters of
   // the deduction guide f.
   for (unsigned Index = 0; Index < DeduceResults.size(); ++Index) {
-    if (const auto &D = DeduceResults[Index]; !D.isNull()) // Deduced
+    const auto &D = DeduceResults[Index];
+    bool NonDeduced =
+        D.isNull() || (D.getKind() == TemplateArgument::Pack &&
+                       D.pack_size() == 1 && D.pack_begin()->isNull());
+    if (!NonDeduced)
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeductionGuide.cpp:1084]: Should that be a function? Should isNull be changed? When do we get in that situation?

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 2]
```diff
@@ -1467,10 +1477,16 @@ namespace {
       }
     }
 
-    static TemplateArgument
+    bool HeuristicallyComputeSizeOfPackExpr() const {
+      return !TemplateArgs.isRewrite();
+    }
+
+    TemplateArgument
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1484]: static is gone

File: clang/lib/Sema/TreeTransform.h [hunk 3]
```diff
@@ -3660,6 +3660,8 @@ class TreeTransform {
     return SemaRef.BuildCXXNoexceptExpr(Range.getBegin(), Arg, Range.getEnd());
   }
 
+  bool HeuristicallyComputeSizeOfPackExpr() const { return true; }
+
```
Comment (cor3ntin) [inline clang/lib/Sema/TreeTransform.h:3664]: This will need a comment

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 4]
```diff
@@ -1348,6 +1348,16 @@ std::optional<TemplateDeductionInfo *> Sema::isSFINAEContext() const {
   return std::nullopt;
 }
 
+static TemplateArgument
+getPackSubstitutedTemplateArgument(Sema &S, TemplateArgument Arg) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1352]: `getSubstitutedTemplateArgumentPattern`  would be a better name. Please add a comment too

File: clang/lib/Sema/TreeTransform.h (hunk 3 above)
Comment (cor3ntin) [reply clang/lib/Sema/TreeTransform.h:3664]: I think I would prefer to add a `TransformSizeOfPackExpr` override in TemplateInstantiator that calls
back to the base implementation with a bool parameter, or something like that

Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h]: I choose to extract a function `ComputeSizeOfPackExprWithoutSubstitution`, since there is some common logic for extracting the pack pattern beforehand. Thus overriding `TransformSizeOfPackExpr` might not be suitable due to duplication.

(We can't add boolean parameters to the function either, as it is expanded from macros.)

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: Added explanations.

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp [hunk 5]
```diff
@@ -1072,12 +1072,25 @@ BuildDeductionGuideForTypeAlias(Sema &SemaRef,
...
+  static auto IsNonDeducedArgument = [&](const DeducedTemplateArgument &TA) {
+    // The following cases indicate the template argument is non-deducible:
+    //   1. The result is null. E.g. When it comes from a default template
+    //   argument that doesn't appear in the alias declaration.
+    //   2. The template parameter is a pack and that cannot be deduced from
+    //   the arguments within the alias declaration.
+    // Non-deducible template parameters will persist in the transformed
+    // deduction guide.
+    return TA.isNull() || (TA.getKind() == TemplateArgument::Pack &&
+                           TA.pack_size() == 1 && TA.pack_begin()->isNull());
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeductionGuide.cpp:1084]: I find the special case here a bit odd.

We do have the concept of a partially deduced pack.
Why does that blow up here? Why doesn't that problem extend to wholly undeduced packs of size greater than one?

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 6]
```diff
@@ -1650,6 +1665,23 @@ namespace {
...
+      //   1) The heuristic needs the unpacked Subst* nodes to figure out the
+      //   expanded size, but this never applies since Subst* nodes are not
+      //   created in rewrite scenarios.
+      //
+      //   2) The heuristic substitutes into the pattern with pack expansion
+      //   suppressed, which does not meet the requirements for argument
+      //   rewriting when template arguments include a non-pack matching against
+      //   a pack, particularly when rewriting an alias CTAD.
+      if (TemplateArgs.isRewrite())
+        return std::nullopt;
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1680]: Instead of special casing this on rewrite, can we do that whenever we have dependent template arguments?

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp (hunk 5 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: (Oh silly me I thought I have asked myself the same question but I quickly forgot to get to it again...)

Yes you're right, we should traverse each element of the pack. I added a test case to reflect that: https://github.com/llvm/llvm-project/pull/132061/commits/74e4444c072d116b48147ba06fd45db57fbbcc03

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 6 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1680]: I'm not sure I understand what 'dependent template arguments' means here. Did you mean we should run the heuristic if any of the arguments is `TA->isDependent()`? Note that the rewrite template arguments are basically dependent, so I have no idea if that would work.

The underlying issue is that the heuristic doesn't expand the template arguments, so we end up without a valid index for rewrite substitution. It used to assume the packs in the rewrite arguments contained only a single PackExpansionType, but that no longer holds in this scenario because the template arguments we have now are deduced arguments - not those injected template parameters. So I’m a bit worried it might be overkill to skip the heuristic in any conditions other than rewrite - chances are that we'll have Subst* nodes otherwise, right?

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1680]: Yeah, I think the whole notion of the rewrite is a special case for substitution with dependent arguments, which don't happen in normal instantiation.

So if you changed that from 'isRewrite' to 'is any template argument dependent', this would still not trip for normal template instantiations.

But is it possible that we might see non-dependent arguments here on a rewrite, and can we do the normal thing in that case?

If so, this distinction would matter.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1680]: It's not that hard to contrive an example to demonstrate the difference (though invalid):

```cpp
template < typename... _Types >
struct variant {
  template <int N = sizeof...(_Types)>
  variant(_Types...);
};

template <class T>
using AstNode = variant<int, int, int>; // <-- Note here!

AstNode tree(42, 43, 44);

```

We still would end up here with a rewrite MLTAL = {int, int, int}, so we fall through to the normal way and crash because we don't have a valid SubstIndex for a pack

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks.

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp [hunk 7]
```diff
@@ -1072,12 +1072,27 @@ BuildDeductionGuideForTypeAlias(Sema &SemaRef,
       AliasRhsTemplateArgs, TDeduceInfo, DeduceResults,
       /*NumberOfArgumentsMustMatch=*/false);
 
+  static std::function<bool(const TemplateArgument &TA)> IsNonDeducedArgument =
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeductionGuide.cpp:1075]: I  meant a function in the file, not a std::function! (that would be...inefficient haha)

**Comment by zyn0217** [comment]
I'll merge without a release note, instead I plan to backport it to the 20 release along with a changelog.

**Comment by zyn0217** [comment]
The commit message is mysteriously gone when merging with the github app 🥲

File: clang/test/SemaCXX/ctad.cpp [hunk 8]
```diff
@@ -17,3 +16,134 @@ void k() {
...
+
+}
+
+namespace GH129077 {
+
+using size_t = decltype(sizeof(0));
+
+struct index_type
+{
+  size_t value{~0ull};
```
Comment (mizvekov) [inline clang/test/SemaCXX/ctad.cpp:82]: This looks to be breaking on a buildbot: https://lab.llvm.org/buildbot/#/builders/135/builds/1706

You need to either change the test here, or pin the test to a certain triple, in order to avoid differences in the type of size_t between machines.

Comment (mizvekov) [reply clang/test/SemaCXX/ctad.cpp:82]: Ops nevermind, I see you already fixed it.
