### PR TITLE
[AArch64][NEON] NEON intrinsic compilation error with -fno-lax-vector-conversion flag fix

### LINKED ISSUE #71362: [AArch64] NEON intrinsic compilation error occurs when using -fno-lax-vector-conversions
This appears to be the same issue as the previous one https://github.com/llvm/llvm-project/issues/42686.

I discovered that certain NEON intrinsics failed to compile with the `-fno-lax-vector-conversions` flag, a problem that did not occur in GCC.
- Reproduce error: https://godbolt.org/z/Mhxqj9151
- Compare with GCC: https://godbolt.org/z/qc31v3no8

The NEON intrinsics that have this issue are listed below:
- `vdupb_lane_p8`, `vdupb_laneq_p8`, `vdupbh_lane_p16`, `vduph_laneq_p16`
- `vset_lane_p8`, `vset_lane_p16`, `vset_lane_p64`, `vsetq_lane_p8`, `vsetq_lane_p16`, `vsetq_lane_p64`
- `vget_lane_p8`, `vget_lane_p16`, `vget_lane_p64`, `vgetq_lane_p8`, `vgetq_lane_p16`, `vgetq_lane_p64`
- `vcopy_lane_p8`, `vcopy_lane_p16`, `vcopy_lane_p64`, `vcopyq_lane_p8`, `vcopyq_lane_p16`, `vcopyq_lane_p64`, 
- `vcopy_laneq_p8`, `vcopy_laneq_p16`, `vcopy_laneq_p64`, `vcopyq_laneq_p8`, `vcopyq_laneq_p16`, `vcopyq_laneq_p64`

Thank you for your reading.

### PR DESCRIPTION
**Pull request by Amichaxx**
Issue originally raised in https://github.com/llvm/llvm-project/issues/71362#issuecomment-3028515618. Certain NEON intrinsics that operate on poly types (e.g. poly8x8_t) failed to compile with the -fno-lax-vector-conversions flag. This patch updates NeonEmitter.cpp to insert an explicit __builtin_bit_cast from poly types to the required signed integer vector types when generating lane-related intrinsics. A test 'neon-bitcast-poly.ll' is included.

### CODE REVIEW

File: clang/utils/TableGen/NeonEmitter.cpp [hunk 1]
```diff
@@ -1401,14 +1401,18 @@ void Intrinsic::emitBodyAsBuiltinCall() {
       if (LocalCK == ClassB || (T.isHalf() && !T.isScalarForMangling())) {
         CastToType.makeInteger(8, true);
         Arg = "__builtin_bit_cast(" + CastToType.str() + ", " + Arg + ")";
-      } else if (LocalCK == ClassI) {
-        if (CastToType.isInteger()) {
```
Comment (Lukacma) [inline clang/utils/TableGen/NeonEmitter.cpp:1405]: Is it not enough to amend the check here to this ?

`` if (CastToType.isInteger() && CastToType.isPoly())``

File: llvm/test/CodeGen/AArch64/neon-bitcast-poly.ll [hunk 2]
```diff
@@ -0,0 +1,51 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
+; RUN: llc -mtriple=aarch64-linux-gnu -o - %s | FileCheck %s
+
+; This test verifies that NEON intrinsics using polynomial types (poly8/16/64) emit correct AArch64 instructions
```
Comment (Lukacma) [inline llvm/test/CodeGen/AArch64/neon-bitcast-poly.ll:4]: I don't think this tests is useful. Polynomial type gets lowered to i8 in LLVM-IR so if you want to test it, you should write C-test and show that it compiles without errors with -fno-lax-vector-conversion flag .

**Review by Lukacma — COMMENTED** [review]
Thank you for the patch Amina ! Hopefully with this we will be ready for a switch to fno-lax-vector-conversion as a default

File: llvm/test/CodeGen/AArch64/neon-bitcast-poly.ll (hunk 2 above)
Comment (Amichaxx) [reply llvm/test/CodeGen/AArch64/neon-bitcast-poly.ll]: I've added a new c test that addresses every intrinsic in the issue, except for vdupbh_lane_p16. I couldn't find it mentioned in arm_neon.h or the [arm developer docs](https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=vdupbh_lane_p16).

File: clang/test/CodeGen/AArch64/neon-bitcast-poly.c [hunk 3]
```diff
@@ -0,0 +1,247 @@
+// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
```
[the remark this answers is not in the document]
Comment (Amichaxx) [reply clang/test/CodeGen/AArch64/neon-bitcast-poly.c]: I've added the flag to tests I've found to use the intrinsics and deleted my original c test.

**Review by Lukacma — APPROVED** [review]
LGTM. I assume you still don't have merge access, so let me know when this patch is ready to be merged and I will be happy to merge it for you.
