### PR TITLE
[SPIR-V] Make SPIRVModuleAnalysis::MAI a non static member

### LINKED ISSUE #160613: [SPIR-V] SPIR-V back-end is generating duplicate IDs
We're trying to switch the Mesa OpenCL infra over to using the SPIR-V back-end in LLVM and a bunch of OpenCL CTS tests are failing to validate with:
```
(file=input,line=0,column=0,index=494): Id 46 is defined more than once
```

### PR DESCRIPTION
**Pull request by karolherbst**
Otherwise multiple translation units in the same process could run into ID reuse collisions cause invalid SPIR-Vs to be generated due to having multiple definition for the same SPIR-V SSA value.

Closes: https://github.com/llvm/llvm-project/issues/160613

### CODE REVIEW

**Comment by karolherbst** [comment]
Not knowing LLVM well enough to deal with the test regressions. Something about the Analysis not available. Anyway, this PR demonstrates what's broken, so if anybody has a better idea to fix it, please let me know.

File: llvm/lib/Target/SPIRV/SPIRVModuleAnalysis.h [hunk 1]
```diff
@@ -227,7 +227,7 @@ struct SPIRVModuleAnalysis : public ModulePass {
 
   bool runOnModule(Module &M) override;
   void getAnalysisUsage(AnalysisUsage &AU) const override;
-  static struct SPIRV::ModuleAnalysisInfo MAI;
+  struct SPIRV::ModuleAnalysisInfo MAI;
```
Comment (jmmartinez) [inline llvm/lib/Target/SPIRV/SPIRVModuleAnalysis.h]:
```suggestion
  SPIRV::ModuleAnalysisInfo MAI;
```

**Review by jmmartinez — APPROVED** [review]
Everything else looks good to me.
