### PR TITLE
[mlir][tensor] Check the EmptyOp's dynamicSize to be non-negative

### LINKED ISSUE #64064: [mlir] Inline pass crashed with assertion failure "(succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...)))"
MLIR built at commit  585cbe3f
Reproduced with:  
` mlir-opt -inline temp.mlir`

This is an issue similar to [61056](https://github.com/llvm/llvm-project/issues/61056), where `tensor.empty` is initialized with a negative index `%133`.
 temp.mlir:
``` milr 
module {
  func.func @func1()  {
    %true_0 = arith.constant true
    %cst = arith.constant 6.483200e+04 : f16
    %true_2 = arith.constant true
    %c7 = arith.constant 7 : index
    %c12 = arith.constant 12 : index
    %c20 = arith.constant 20 : index
    %c28 = arith.constant 28 : index
    %38 = memref.alloca_scope  -> (tensor<?x?xf32>) {
      %133 = index.sub %c12, %c20
      %158 = tensor.empty(%c28, %133) : tensor<?x?xf32> // !!!!!!!!!!!
      memref.alloca_scope.return %158 : tensor<?x?xf32>
    }
    %91 = scf.index_switch %c7 -> vector<28x28xf16> 
    default {
      %146 = math.tanh %38 : tensor<?x?xf32>
      %149 = vector.broadcast %cst : f16 to vector<28x28xf16>
      scf.yield %149 : vector<28x28xf16>
    } 
    return 
  }
}

```
 
trace:
```console
<unknown>:0: error: invalid tensor dimension size
Assertion failed: (succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))), function get, file StorageUniquerSupport.h, line 180.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: mlir-opt -inline temp.mlir
 #0 0x0000000100d10f18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/workspace/build/bin/mlir-opt+0x1002f8f18)
 #1 0x0000000100d0f1b4 llvm::sys::RunSignalHandlers() (/workspace/build/bin/mlir-opt+0x1002f71b4)
 #2 0x0000000100d115c4 SignalHandler(int) (/workspace/build/bin/mlir-opt+0x1002f95c4)
 #3 0x00000001be7894c4 (/usr/lib/system/libsystem_platform.dylib+0x1803414c4)
 #4 0x00000001be771ee0 (/usr/lib/system/libsystem_pthread.dylib+0x180329ee0)
 #5 0x00000001be6ac340 (/usr/lib/system/libsystem_c.dylib+0x180264340)
 #6 0x00000001be6ab754 (/usr/lib/system/libsystem_c.dylib+0x180263754)
 #7 0x00000001052f8348 mlir::detail::skipDefaultMemorySpace(mlir::Attribute) (.cold.1) (/workspace/build/bin/mlir-opt+0x1048e0348)
 #8 0x0000000103452b04 mlir::RankedTensorType mlir::detail::StorageUserBase<mlir::RankedTensorType, mlir::TensorType, mlir::detail::RankedTensorTypeStorage, mlir::detail::TypeUniquer, mlir::ShapedType::Trait>::get<llvm::ArrayRef<long long>, mlir::Type, mlir::Attribute>(mlir::MLIRContext*, llvm::ArrayRef<long long>, mlir::Type, mlir::Attribute) (/workspace/build/bin/mlir-opt+0x102a3ab04)
 #9 0x00000001034529f0 mlir::RankedTensorType::get(llvm::ArrayRef<long long>, mlir::Type, mlir::Attribute) (/workspace/build/bin/mlir-opt+0x102a3a9f0)
#10 0x00000001027ad458 (anonymous namespace)::ReplaceEmptyTensorStaticShapeDims::matchAndRewrite(mlir::tensor::EmptyOp, mlir::PatternRewriter&) const (/workspace/build/bin/mlir-opt+0x101d95458)
#11 0x00000001049930f0 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>)::$_2::operator()() const (/workspace/build/bin/mlir-opt+0x103f7b0f0)
#12 0x00000001049903ec mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (/workspace/build/bin/mlir-opt+0x103f783ec)
#13 0x00000001033bf420 (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist() (/workspace/build/bin/mlir-opt+0x1029a7420)
#14 0x00000001033bcc50 mlir::applyPatternsAndFoldGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*) (/workspace/build/bin/mlir-opt+0x1029a4c50)
#15 0x0000000103376c5c (anonymous namespace)::Canonicalizer::runOnOperation() (/workspace/build/bin/mlir-opt+0x10295ec5c)
#16 0x00000001033602a8 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/workspace/build/bin/mlir-opt+0x1029482a8)
#17 0x0000000103360998 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/workspace/build/bin/mlir-opt+0x102948998)
#18 0x0000000103386418 (anonymous namespace)::InlinerPass::optimizeSCCAsync(llvm::MutableArrayRef<mlir::CallGraphNode*>, mlir::MLIRContext*)::$_0::operator()(mlir::CallGraphNode*) const (/workspace/build/bin/mlir-opt+0x10296e418)
#19 0x0000000103385f3c (anonymous namespace)::InlinerPass::inlineSCC((anonymous namespace)::Inliner&, (anonymous namespace)::CGUseList&, (anonymous namespace)::CallGraphSCC&, mlir::MLIRContext*) (/workspace/build/bin/mlir-opt+0x10296df3c)
#20 0x000000010337e1cc (anonymous namespace)::InlinerPass::runOnOperation() (/workspace/build/bin/mlir-opt+0x1029661cc)
#21 0x00000001033602a8 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/workspace/build/bin/mlir-opt+0x1029482a8)
#22 0x0000000103360998 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/workspace/build/bin/mlir-opt+0x102948998)
#23 0x000000010336282c mlir::PassManager::run(mlir::Operation*) (/workspace/build/bin/mlir-opt+0x10294a82c)
#24 0x000000010335ad14 performActions(llvm::raw_ostream&, std::__1::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) (/workspace/build/bin/mlir-opt+0x102942d14)
#25 0x000000010335a368 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_1>(long, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) (/workspace/build/bin/mlir-opt+0x102942368)
#26 0x00000001033d834c mlir::splitAndProcessBuffer(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/workspace/build/bin/mlir-opt+0x1029c034c)
#27 0x0000000103354d1c mlir::MlirOptMain(llvm::raw_ostream&, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/workspace/build/bin/mlir-opt+0x10293cd1c)
#28 0x000000010335518c mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/workspace/build/bin/mlir-opt+0x10293d18c)
#29 0x0000000100a1b510 main (/workspace/build/bin/mlir-opt+0x100003510)
#30 0x000000010c1d1088 

```

### PR DESCRIPTION
**Pull request by sott0n**
This patch addresses a crash that occurs when negative dynamic sizes are provided in tensor.emptyOp by adding a check to ensure that dynamic sizes are non-negative.

Fixes #64064

### CODE REVIEW

File: mlir/lib/Dialect/Tensor/IR/TensorOps.cpp [hunk 1]
```diff
@@ -621,6 +621,18 @@ LogicalResult EmptyOp::verify() {
     return emitOpError("incorrect number of dynamic sizes, has ")
            << getDynamicSizes().size() << ", expected "
            << getType().getNumDynamicDims();
+
+  if (getDynamicSizes().size() > 0) {
```
Comment (joker-eph) [inline mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:625]: This check does not seem needed?

File: mlir/lib/Dialect/Tensor/IR/TensorOps.cpp [hunk 2]
```diff
@@ -621,6 +621,18 @@ LogicalResult EmptyOp::verify() {
...
+    if (llvm::any_of(getDynamicSizes(), [](Value operand) {
+          APInt constSizeArg;
+          if (!matchPattern(operand, m_ConstantInt(&constSizeArg))) {
```
Comment (joker-eph) [inline mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:628]: This does not belong to the verifier, because: https://mlir.llvm.org/getting_started/DeveloperGuide/#ir-verifier

File: mlir/lib/Dialect/Tensor/IR/TensorOps.cpp [hunk 3]
```diff
@@ -691,6 +703,9 @@ struct ReplaceEmptyTensorStaticShapeDims : OpRewritePattern<EmptyOp> {
         Value dynamicSize = op.getDynamicSizes()[ctr++];
         std::optional<int64_t> cst = getConstantIntValue(dynamicSize);
         if (cst.has_value()) {
+          // dynamic size must be non-negative.
+          if (cst.value() < 0)
+            return failure();
```
Comment (joker-eph) [inline mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:708]: This should be enough without the verifier right?

File: mlir/lib/Dialect/Tensor/IR/TensorOps.cpp (hunk 2 above)
Comment (sott0n) [reply mlir/lib/Dialect/Tensor/IR/TensorOps.cpp:628]: Thank you for teaching me about IR's verifier.

> This is why the guidelines to write verifier is to stick to information local to an operation (think “what I see when I print this operation alone”). Looking through operands or results is extremely unusual and should be avoided.

I understand it, so i will remove this checker from verifier.

**Review by joker-eph — APPROVED** [review]

**Comment by sott0n** [comment]
@joker-eph Could you merge it?
