### PR TITLE
[HLSL] Fix casting asserts

### LINKED ISSUE #82826: [HLSL] vector float to int and vec int to float are asserting
```hlsl
void Fn( int64_t2 p0);

void Call1(half2 p0) {
  Fn3(p0);
}

void Call2(float2 p0) {
  Fn3(p0);
}
```
doing an int cast when we need to be doing sitofp
```
static CastInst *llvm::CastInst::Create(Instruction::CastOps, Value *, Type *, const Twine &, Instruction *): Assertion `castIsValid(op, S, Ty) && "Invalid cast!"' failed.
#10 0x000055690b7b06b1 llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&, llvm::Instruction*) /mnt/DevDrive/projects/llvm-project/llvm/lib/IR/Instructions.cpp:3331:11
#11 0x00005569085869fa llvm::IRBuilderBase::CreateCast(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&) /mnt/DevDrive/projects/llvm-project/llvm/include/llvm/IR/IRBuilder.h:2150:19
#12 0x0000556908589832 llvm::IRBuilderBase::CreateIntCast(llvm::Value*, llvm::Type*, bool, llvm::Twine const&) /mnt/DevDrive/projects/llvm-project/llvm/include/llvm/IR/IRBuilder.h:2185:5
```

```hlsl
void Fn4( float2 p0);

void Call5(int64_t2 p0) {
  Fn4(p0);
}
```
Need to be doing an int to float cast but we are doing a float to int
```
#10 0x0000563efc7c7fa1 llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&, llvm::Instruction*) /mnt/DevDrive/projects/llvm-project/llvm/lib/IR/Instructions.cpp:3331:11
#11 0x0000563ef958dfba llvm::IRBuilderBase::CreateCast(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&) /mnt/DevDrive/projects/llvm-project/llvm/include/llvm/IR/IRBuilder.h:2150:19
#12 0x0000563ef9866f2f llvm::IRBuilderBase::CreateFPToUI(llvm::Value*, llvm::Type*, llvm::Twine const&) /mnt/DevDrive/projects/llvm-project/llvm/include/llvm/IR/IRBuilder.h:2060:5
```

### PR DESCRIPTION
**Pull request by farzonl**
There are two issues here. first `ICK_Floating_Integral` were always defaulting to `CK_FloatingToIntegral` for vectors regardless of  direction of cast. Check was scalar only so added a vec float check to the conditional.

Second issue was float to int  casts were resolving to ICK_Integral_Promotion when they need to be resolving to CK_FloatingToIntegral. This was fixed by changing the ordering of conversion checks.

This fixes #82826

### CODE REVIEW

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 1]
```diff
@@ -4843,7 +4843,7 @@ Sema::PerformImplicitConversion(Expr *From, QualType ToType,
                  .get();
       break;
     case ICK_Floating_Integral:
-      if (ToType->isRealFloatingType())
+      if (ToType->isRealFloatingType() || ToType->hasFloatingRepresentation())
```
Comment (bogner) [inline clang/lib/Sema/SemaExprCXX.cpp:4846]: I think `isRealFloatingType` is redundant now. `hasFloatingRepresentation` will return true in all cases that it does. I guess this also means that complex types will go into this case now and they didn't before - does that matter?

Comment (farzonl) [reply clang/lib/Sema/SemaExprCXX.cpp:4846]: I can fix that up. 
For your second question line 4800  `assert(From->getType()->isVectorType() && ToType->isVectorType()`. It should just be vectors for now.

**Review by bogner — APPROVED** [review]

**Review by damyanp — APPROVED** [review]

File: clang/test/SemaHLSL/VectorOverloadResolution.hlsl [hunk 2]
```diff
@@ -1,4 +1,5 @@
 // RUN: %clang_cc1 -triple dxil-unknown-shadermodel6.6-library -S -fnative-half-type -finclude-default-header -o - -ast-dump %s | FileCheck %s
+// RUN: %clang_cc1 -std=hlsl2021 -finclude-default-header -x hlsl -triple dxil-pc-shadermodel6.6-library %s -fnative-half-type -emit-llvm -disable-llvm-passes -O3 -o - | FileCheck %s --check-prefixes=CHECKIR
```
Comment (llvm-beanz) [inline clang/test/SemaHLSL/VectorOverloadResolution.hlsl:2]: nit: simplifying the `RUN` line. HLSL 2021 is the default version, but ideally tests that don't depend on a specific language version shouldn't specify a version, also `-x hlsl` is inferred from the filename. Also you passed both `-disable-llvm-passes` and `-O3` which directly contradict each other.

```suggestion
// RUN: %clang_cc1 -finclude-default-header -triple dxil-pc-shadermodel6.6-library %s -fnative-half-type -emit-llvm -disable-llvm-passes -o - | FileCheck %s --check-prefixes=CHECKIR
```

File: clang/test/SemaHLSL/VectorOverloadResolution.hlsl [hunk 3]
```diff
@@ -28,3 +29,43 @@ void Fn2(int16_t2 S);
...
+void Fn4( float2 p0);
+
+// CHECK: FunctionDecl {{.*}} Call5 'void (int64_t2)'
+// CHECK: CallExpr {{.*}} 'void'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'void (*)(float2)' <FunctionToPointerDecay>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'void (float2)' lvalue Function {{.*}} 'Fn4' 'void (float2)'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'float2':'float __attribute__((ext_vector_type(2)))' <IntegralToFloating>
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'int64_t2':'long __attribute__((ext_vector_type(2)))' <LValueToRValue>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'int64_t2':'long __attribute__((ext_vector_type(2)))' lvalue ParmVar {{.*}} 'p0' 'int64_t2':'long __attribute__((ext_vector_type(2)))'
+// CHECKIR: %conv = sitofp <2 x i64> %0 to <2 x float>
```
Comment (llvm-beanz) [inline clang/test/SemaHLSL/VectorOverloadResolution.hlsl:68]: We should at least have label checks before each of the IR checks (i.e `// CHECKIR-LABEL: Call5`).

Also you'll want to use regex matches for the SSA value names otherwise the tests are likely to fail under different build configurations where the names aren't preserved.

File: clang/test/SemaHLSL/VectorOverloadResolution.hlsl [hunk 4]
```diff
@@ -28,3 +29,46 @@ void Fn2(int16_t2 S);
...
+
+// CHECK: FunctionDecl {{.*}} Call4 'void (float2)'
+// CHECK: CallExpr {{.*}} 'void'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'void (*)(int64_t2)' <FunctionToPointerDecay>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'void (int64_t2)' lvalue Function {{.*}} 'Fn3' 'void (int64_t2)'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'int64_t2':'long __attribute__((ext_vector_type(2)))' <FloatingToIntegral>
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'float2':'float __attribute__((ext_vector_type(2)))' <LValueToRValue>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'float2':'float __attribute__((ext_vector_type(2)))' lvalue ParmVar {{.*}} 'p0' 'float2':'float __attribute__((ext_vector_type(2)))'
+// CHECKIR-LABEL: Call4
+// CHECKIR: %conv = fptosi <2 x float> {{.*}} to <2 x i64>
```
Comment (llvm-beanz) [inline clang/test/SemaHLSL/VectorOverloadResolution.hlsl:56]:
```suggestion
// CHECKIR: {{.*}} = fptosi <2 x float> {{.*}} to <2 x i64>
```

File: clang/test/SemaHLSL/VectorOverloadResolution.hlsl [hunk 5]
```diff
@@ -28,3 +29,46 @@ void Fn2(int16_t2 S);
...
+
+// CHECK: FunctionDecl {{.*}} Call5 'void (int64_t2)'
+// CHECK: CallExpr {{.*}} 'void'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'void (*)(float2)' <FunctionToPointerDecay>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'void (float2)' lvalue Function {{.*}} 'Fn4' 'void (float2)'
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'float2':'float __attribute__((ext_vector_type(2)))' <IntegralToFloating>
+// CHECK-NEXT: ImplicitCastExpr {{.*}} 'int64_t2':'long __attribute__((ext_vector_type(2)))' <LValueToRValue>
+// CHECK-NEXT: DeclRefExpr {{.*}} 'int64_t2':'long __attribute__((ext_vector_type(2)))' lvalue ParmVar {{.*}} 'p0' 'int64_t2':'long __attribute__((ext_vector_type(2)))'
+// CHECKIR-LABEL: Call5
+// CHECKIR: %conv = sitofp <2 x i64> {{.*}} to <2 x float>
```
Comment (llvm-beanz) [inline clang/test/SemaHLSL/VectorOverloadResolution.hlsl:71]:
```suggestion
// CHECKIR: {{.*}} = sitofp <2 x i64> {{.*}} to <2 x float>
```

**Review by llvm-beanz — APPROVED** [review]
