### PR TITLE
[Tooling/Inclusion] Update std symbols mapping

### LINKED ISSUE #113494: [clang-include-cleaner] <expected> incorrectly diagnosed as unused when using libc++ because of outdated StdSymbolMap.inc
### The problem

```cpp
#include <expected>

std::expected<int, char> Foo() {
    return 123;
}
```

When using libc++, both clangd and `misc-include-cleaner` check in clang-tidy (trunk versions) diagnose `<expected>` as unused. 
Reproducer: https://godbolt.org/z/T4fesGThr
With libstdc++ the usage is detected correctly.

### The cause

In libc++ `std::expected` is actually defined in [__expected/expected.h](https://github.com/llvm/llvm-project/blob/main/libcxx/include/__expected/expected.h#L449).
Correct headers for std symbols are defined in [clang/lib/Tooling/Inclusions/Stdlib/StdSymbolMap.inc](https://github.com/llvm/llvm-project/blob/main/clang/lib/Tooling/Inclusions/Stdlib/StdSymbolMap.inc), which hasn't been updated since 2022-07-30 and currently doesn't contain an entry for `std::expected`.

I tried to run `gen_std.py` with [cppreference copy from 2023-08-10](https://github.com/PeterFeicht/cppreference-doc/releases/tag/v20230810), but it doesn't seem to work with newer archives.
1. Some symbols have become ambiguous and the generator does not include them in the mapping anymore (see [resulting diff](https://github.com/llvm/llvm-project/commit/f53bbb385658aa57c0a2c1f39d5f29a9b28f190a)). Some of these symbols should probably be moved into `StdSpecialSymbolMap.inc` (like `std::atomic_*`, because `std::atomic` is already there), but I'm not sure what to do with the others,
2. If I [manualliy restore deleted symbols](https://github.com/llvm/llvm-project/commit/d19c4aa7a6e58ef7870343f4f663417edf06189e) and try to build clangd with the new mapping, it crashes immediately when I try to open a file or run clangd with `--check`. 
   <details><summary>Crash backtrace (relwithdebinfo build, assertions are enabled)</summary>
   
    ```
    $ /opt/clangd-patched/19/bin/clangd --compile-commands-dir=$HOME/vsc/tasklet --check=.../main.cpp 
    I[23:44:22.985] clangd version 19.1.2 (https://github.com/llvm/llvm-project 7918ef84393878091346d79171da74a8427aa4ec)
    I[23:44:22.985] Features: linux
    I[23:44:22.985] PID: 3422246
    I[23:44:22.985] Working directory: /home/username
    I[23:44:22.985] argv[0]: /opt/clangd-patched/19/bin/clangd
    I[23:44:22.985] argv[1]: --compile-commands-dir=...
    I[23:44:22.985] argv[2]: --check=.../main.cpp
    I[23:44:22.986] Entering check mode (no LSP server)
    I[23:44:22.986] Testing on source file .../main.cpp
    I[23:44:22.988] Loading compilation database...
    I[23:44:23.183] Loaded compilation database from .../compile_commands.json
    I[23:44:23.188] Compile command from CDB is: ...
    I[23:44:23.189] Parsing command...
    I[23:44:23.191] internal (cc1) args are: ...
    I[23:44:23.192] Building preamble...
    PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
    Stack dump:
    0.      Program arguments: /opt/clangd-patched/19/bin/clangd --compile-commands-dir... --check=.../main.cpp
    1.      .../main.cpp:1:2: current parser token 'include'
    #0 0x0000562078ecc108 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /opt/clangd-patched/19/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:13
    #1 0x0000562078eca3b0 llvm::sys::RunSignalHandlers() /opt/clangd-patched/19/llvm-project/llvm/lib/Support/Signals.cpp:106:18
    #2 0x0000562078ecca98 SignalHandler(int) /opt/clangd-patched/19/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
    #3 0x00007f6e2a668520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
    #4 0x00007f6e2a6cb795 __libc_realloc ./malloc/./malloc/malloc.c:3428:35
    #5 0x0000562078e9aeb3 llvm::safe_realloc(void*, unsigned long) /opt/clangd-patched/19/llvm-project/llvm/include/llvm/Support/MemAlloc.h:53:18
    #6 0x0000562078e9aeb3 llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) /opt/clangd-patched/19/llvm-project/llvm/lib/Support/SmallVector.cpp:151:15
    #7 0x000056207bf0244f llvm::SmallVectorBase<unsigned int>::size() const /opt/clangd-patched/19/llvm-project/llvm/include/llvm/ADT/SmallVector.h:92:32
    #8 0x000056207bf0244f llvm::SmallVectorTemplateCommon<unsigned int, void>::end() /opt/clangd-patched/19/llvm-project/llvm/include/llvm/ADT/SmallVector.h:283:37
    #9 0x000056207bf0244f llvm::SmallVectorTemplateBase<unsigned int, true>::push_back(unsigned int) /opt/clangd-patched/19/llvm-project/llvm/include/llvm/ADT/SmallVector.h:577:43
    #10 0x000056207bf0244f clang::tooling::stdlib::initialize(clang::tooling::stdlib::Lang)::$_2::operator()(llvm::StringRef, unsigned int, llvm::StringRef) /opt/clangd-patched/18/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:134:43
    #11 0x000056207bf020f0 clang::tooling::stdlib::initialize(clang::tooling::stdlib::Lang) /opt/clangd-patched/18/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:164:26
    #12 0x000056207bf020f0 clang::tooling::stdlib::ensureInitialized()::$_0::operator()() const /opt/clangd-patched/18/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:181:7
    #13 0x000056207bf01439 clang::tooling::stdlib::ensureInitialized() /opt/clangd-patched/18/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:179:3
    #14 0x000056207bf01439 clang::tooling::stdlib::Header::named(llvm::StringRef, clang::tooling::stdlib::Lang) /opt/clangd-patched/18/llvm-project/clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:197:3
    #15 0x000056207bee061d clang::include_cleaner::PragmaIncludes::RecordPragma::InclusionDirective(clang::SourceLocation, clang::Token const&, llvm::StringRef, bool, clang::CharSourceRange, clang::CustomizableOptional<clang::FileEntryRef>, llvm::StringRef, llvm::StringRef, clang::Module const*, bool, clang::SrcMgr::CharacteristicKind) /opt/clangd-patched/18/llvm-project/clang-tools-extra/include-cleaner/lib/Record.cpp:229:15
    #16 0x000056207947acfc std::__uniq_ptr_impl<clang::PPCallbacks, std::default_delete<clang::PPCallbacks> >::_M_ptr() const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:173:42
    #17 0x000056207947acfc std::unique_ptr<clang::PPCallbacks, std::default_delete<clang::PPCallbacks> >::get() const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:422:21
    #18 0x000056207947acfc std::unique_ptr<clang::PPCallbacks, std::default_delete<clang::PPCallbacks> >::operator->() const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:416:9
    #19 0x000056207947acfc clang::PPChainedCallbacks::InclusionDirective(clang::SourceLocation, clang::Token const&, llvm::StringRef, bool, clang::CharSourceRange, clang::CustomizableOptional<clang::FileEntryRef>, llvm::StringRef, llvm::StringRef, clang::Module const*, bool, clang::SrcMgr::CharacteristicKind) /opt/clangd-patched/18/llvm-project/clang/include/clang/Lex/PPCallbacks.h:533:5
    #20 0x000056207942526c clang::FileEntryRef::hasOptionalValue() const /opt/clangd-patched/18/llvm-project/clang/include/clang/Basic/FileEntry.h:177:42
    #21 0x000056207942526c clang::FileMgr::MapEntryOptionalStorage<clang::FileEntryRef>::has_value() const /opt/clangd-patched/18/llvm-project/clang/include/clang/Basic/DirectoryEntry.h:133:44
    #22 0x000056207942526c clang::CustomizableOptional<clang::FileEntryRef>::has_value() const /opt/clangd-patched/18/llvm-project/clang/include/clang/Basic/CustomizableOptional.h:83:53
    #23 0x000056207942526c clang::CustomizableOptional<clang::FileEntryRef>::operator bool() const /opt/clangd-patched/18/llvm-project/clang/include/clang/Basic/CustomizableOptional.h:82:53
    #24 0x000056207942526c clang::Preprocessor::HandleHeaderIncludeOrImport(clang::SourceLocation, clang::Token&, clang::Token&, clang::SourceLocation, clang::detail::SearchDirIteratorImpl<true>, clang::FileEntry const*) /opt/clangd-patched/18/llvm-project/clang/lib/Lex/PPDirectives.cpp:2486:8
    #25 0x0000562079420978 clang::Preprocessor::HandleIncludeDirective(clang::SourceLocation, clang::Token&, clang::detail::SearchDirIteratorImpl<true>, clang::FileEntry const*) /opt/clangd-patched/18/llvm-project/clang/lib/Lex/PPDirectives.cpp:2069:3
    #26 0x0000562079421187 clang::Preprocessor::HandleDirective(clang::Token&) /opt/clangd-patched/18/llvm-project/clang/lib/Lex/PPDirectives.cpp:0:14
    #27 0x0000562079415dd4 clang::Lexer::LexTokenInternal(clang::Token&, bool) /opt/clangd-patched/18/llvm-project/clang/lib/Lex/Lexer.cpp:4490:7
    #28 0x000056207944ecfd clang::Preprocessor::Lex(clang::Token&) /opt/clangd-patched/18/llvm-project/clang/lib/Lex/Preprocessor.cpp:873:3
    #29 0x000056207c53a30b clang::OpaquePtr<clang::DeclGroupRef>::OpaquePtr(std::nullptr_t) /opt/clangd-patched/18/llvm-project/clang/include/clang/Sema/Ownership.h:51:11
    #30 0x000056207c53a30b clang::ParseAST(clang::Sema&, bool, bool) /opt/clangd-patched/18/llvm-project/clang/lib/Parse/ParseAST.cpp:165:28
    #31 0x000056207c3a0137 clang::FrontendAction::Execute() /opt/clangd-patched/18/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1082:10
    #32 0x000056207c3b68bf llvm::Error::getPtr() const /opt/clangd-patched/19/llvm-project/llvm/include/llvm/Support/Error.h:282:12
    #33 0x000056207c3b68bf llvm::Error::operator bool() /opt/clangd-patched/19/llvm-project/llvm/include/llvm/Support/Error.h:242:16
    #34 0x000056207c3b68bf clang::PrecompiledPreamble::Build(clang::CompilerInvocation const&, llvm::MemoryBuffer const*, clang::PreambleBounds, clang::DiagnosticsEngine&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::shared_ptr<clang::PCHContainerOperations>, bool, llvm::StringRef, clang::PreambleCallbacks&) /opt/clangd-patched/18/llvm-project/clang/lib/Frontend/PrecompiledPreamble.cpp:536:19
    #35 0x0000562079f4d973 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:704:6
    #36 0x0000562079f4d973 std::__shared_ptr<clang::PCHContainerOperations, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1154:31
    #37 0x0000562079f4d973 clang::clangd::buildPreamble(llvm::StringRef, clang::CompilerInvocation, clang::clangd::ParseInputs const&, bool, std::function<void (clang::clangd::CapturedASTCtx, std::shared_ptr<clang::include_cleaner::PragmaIncludes const>)>, clang::clangd::PreambleBuildStats*) /opt/clangd-patched/18/llvm-project/clang-tools-extra/clangd/Preamble.cpp:663:24
    #38 0x0000562079d84b6e std::__shared_ptr<clang::clangd::PreambleData const, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<clang::clangd::PreambleData const, (__gnu_cxx::_Lock_policy)2>&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1162:20
    #39 0x0000562079d84b6e std::__shared_ptr<clang::clangd::PreambleData const, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<clang::clangd::PreambleData const, (__gnu_cxx::_Lock_policy)2>&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1250:2
    #40 0x0000562079d84b6e std::shared_ptr<clang::clangd::PreambleData const>::operator=(std::shared_ptr<clang::clangd::PreambleData const>&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:385:27
    #41 0x0000562079d84b6e clang::clangd::(anonymous namespace)::Checker::buildAST() /opt/clangd-patched/18/llvm-project/clang-tools-extra/clangd/tool/Check.cpp:245:14
    #42 0x0000562079d84b6e clang::clangd::check(llvm::StringRef, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&) /opt/clangd-patched/18/llvm-project/clang-tools-extra/clangd/tool/Check.cpp:522:10
    #43 0x0000562079d7a957 clang::clangd::clangdMain(int, char**) /opt/clangd-patched/18/llvm-project/clang-tools-extra/clangd/tool/ClangdMain.cpp:982:12
    #44 0x00007f6e2a64fd90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #45 0x00007f6e2a64fe40 call_init ./csu/../csu/libc-start.c:128:20
    #46 0x00007f6e2a64fe40 __libc_start_main ./csu/../csu/libc-start.c:379:5
    #47 0x0000562078de0515 _start (/opt/clangd-patched/19/bin/clangd+0x822515)
    Segmentation fault
    ```
   </details>

    ~Currently I don't have a minimal reproducer for this crash, but will try to create one.~
    UPD: the crash is caused by duplicate mappings - for example, mapping for `any_cast` is already [defined](https://github.com/llvm/llvm-project/blob/76edf72501cd6f66788c631fada95972a797a4a6/clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc#L366) in `StdSpecialSymbolMap.inc`, Removing it fixes the crash. I'll try to create a PR with updated mappings.

### PR DESCRIPTION
**Pull request by vvd170501**
Fixes #113494

### CODE REVIEW

File: clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp [hunk 1]
```diff
@@ -115,15 +115,17 @@ static int initialize(Lang Language) {
       NSLen = 0;
     }
 
-    if (SymIndex >= 0 &&
-        Mapping->SymbolNames[SymIndex].qualifiedName() == QName) {
-      // Not a new symbol, use the same index.
+    if (SymIndex > 0) {
       assert(llvm::none_of(llvm::ArrayRef(Mapping->SymbolNames, SymIndex),
```
Comment (vvd170501) [inline clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:119]: This assertion could fail only if entries for a symbol were partially grouped, but it didn't fail if entries weren't grouped at all.
Example:
```cpp
// StdSpecialSymbolMap.inc
SYMBOL(any_cast, std::, <any>)
SYMBOL(div, std::, <cstdlib>)
// StdSymbolMap.inc
SYMBOL(any, std::, <any>)
SYMBOL(any_cast, std::, <any>)  // assertion doesn't fail because previous entry has a different name
...

```

File: clang/lib/Tooling/Inclusions/Stdlib/StdSymbolMap.inc [hunk 2]
```diff
@@ -598,7 +598,6 @@ SYMBOL(aligned_union_t, std::, <type_traits>)
 SYMBOL(alignment_of, std::, <type_traits>)
 SYMBOL(alignment_of_v, std::, <type_traits>)
 SYMBOL(all_of, std::, <algorithm>)
-SYMBOL(allocate_at_least, std::, <memory>)
```
Comment (vvd170501) [inline clang/lib/Tooling/Inclusions/Stdlib/StdSymbolMap.inc:601]: Was replaced with `std::allocator_traits<>::allocate_at_least` in [P2652R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2652r2.html)

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc [hunk 3]
```diff
@@ -232,6 +232,47 @@ SYMBOL(ssize, std::, <string_view>)
...
+SYMBOL(ceil, std::chrono::, <chrono>)
+SYMBOL(floor, std::chrono::, <chrono>)
+SYMBOL(from_stream, std::chrono::, <chrono>)
+SYMBOL(round, std::chrono::, <chrono>)
+SYMBOL(begin, std::filesystem::, <filesystem>)
+SYMBOL(end, std::filesystem::, <filesystem>)
+SYMBOL(get, std::ranges::, <ranges>)
+
+// Ignore specializations
+SYMBOL(hash, std::, <functional>)
```
Comment (vvd170501) [inline clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:275]: Not sure if it's better to keep `<functional>` or replace it with `/*no headers*/`

File: clang/tools/include-mapping/cppreference_parser.py [hunk 4]
```diff
@@ -143,32 +165,33 @@ def _GetSymbols(pool, root_dir, index_page_name, namespace, variants_to_accept):
     with open(index_page_path, "r") as f:
         # Read each symbol page in parallel.
         results = []  # (symbol_name, promise of [header...])
+        symbols_by_page = collections.defaultdict(list)
```
Comment (vvd170501) [inline clang/tools/include-mapping/cppreference_parser.py:168]: On my machine it took about 3 minutes for the generator to run, so I tried to optimize it by grouping symbols that are defined on the same page (now it takes 2 minutes).
If the diff is too large or complex, I can move the commit with optimizations to a separate PR.

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc [hunk 5]
```diff
@@ -352,20 +383,23 @@ SYMBOL(get, std::, /*no headers*/)
...
 // Symbols missing from the generated symbol map as reported by users.
 // Remove when the generator starts producing them.
-SYMBOL(make_any, std::, <any>)
-SYMBOL(any_cast, std::, <any>)
 SYMBOL(div, std::, <cstdlib>)
 SYMBOL(abort, std::, <cstdlib>)
+SYMBOL(atomic_wait, std::, <atomic>)
+SYMBOL(atomic_wait_explicit, std::, <atomic>)
+SYMBOL(move_backward, std::, <algorithm>)
+SYMBOL(month_weekday, std::chrono::, <chrono>)
```
Comment (vvd170501) [inline clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:402]: These symbols and `std::regular_invocable` were lost in newer edits, but should be back in the next release of offline archive

File: clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp (hunk 1 above)
Comment (kadircet) [reply clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:119]: this assertion is making sure we're inserting all the headers for a symbol consecutively. this is important for correctness as we want to know all the headers providing a symbol not a random set.

we should fix the mappings files instead to not split `any_cast` (and other symbols).

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc (hunk 3 above)
Comment (kadircet) [reply clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:265]: i think it's better to keep it as-is unless we have a reason.

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc (hunk 5 above)
Comment (kadircet) [reply clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:402]: i think it's totally fine as you're moving them around, so just OOC

> but should be back in the next release of offline archive

how do you know this?

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc [hunk 6]
```diff
@@ -232,6 +232,37 @@ SYMBOL(ssize, std::, <string_view>)
...
+SYMBOL(end, std::ranges::, <ranges>)
+SYMBOL(end, std::ranges::, <iterator>)
+SYMBOL(rbegin, std::ranges::, <ranges>)
+SYMBOL(rbegin, std::ranges::, <iterator>)
+SYMBOL(rend, std::ranges::, <ranges>)
+SYMBOL(rend, std::ranges::, <iterator>)
+SYMBOL(size, std::ranges::, <ranges>)
+SYMBOL(size, std::ranges::, <iterator>)
+SYMBOL(ssize, std::ranges::, <ranges>)
+SYMBOL(ssize, std::ranges::, <iterator>)
```
Comment (kadircet) [inline clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:262]: can you re-order these with the same order in https://eel.is/c++draft/range.access? that way it'll be easier to compare/update going forward.

also let's mention the link in comments as well, not everyone knows how to navigate c++draft

File: clang/tools/include-mapping/cppreference_parser.py
Comment (kadircet) [inline clang/tools/include-mapping/cppreference_parser.py:1]: can you send this in a separate PR ?

**Review by kadircet — CHANGES_REQUESTED** [review]
thanks a ton for the comprehensive change, i think this looks amazing!

can you just move the parser changes into a separate PR and revert changes in the assertion and rather delete the duplicates from stdspecialsymbolmap?

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc (hunk 5 above)
Comment (vvd170501) [reply clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc:402]: I've suggested fixes to the corresponding cppreference pages, the editors have added them.

File: clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp (hunk 1 above)
Comment (vvd170501) [reply clang/lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp:119]: I've already fixed the mappings, but I'd like to keep the changes in assertion to simplify debugging if someone makes the same mistake in the future.

When I first tried to run the generator and didn't remove the duplicate mappings like `any_cast` from `StdSpecialSymbolMap.inc` (d19c4aa7a6e58ef7870343f4f663417edf06189e), I got a segfault which was quite hard to debug (see description of #113494).

Rebuilding clangd with `-DLLVM_ENABLE_ASSERTIONS=ON` didn't help, because the assertion didn't check the second mapping for `any_cast` (because of `Mapping->SymbolNames[SymIndex].qualifiedName() == QName` condition).
This change makes the assertion fail for such unordered mappings.

File: clang/tools/include-mapping/cppreference_parser.py
Comment (vvd170501) [reply clang/tools/include-mapping/cppreference_parser.py:1]: I've reverted the optimizations, will create a new PR when this one is merged (the commit depends on other changes that I've left in this PR)

File: clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc (hunk 6 above)
Comment (vvd170501) [reply clang/lib/Tooling/Inclusions/Stdlib/StdSpecialSymbolMap.inc]: Done

File: clang/tools/include-mapping/cppreference_parser.py [hunk 7]
```diff
@@ -69,7 +69,9 @@ def _ParseSymbolPage(symbol_page_html, symbol_name):
                 was_decl = True
                 # Symbols are in the first cell.
                 found_symbols = row.find("td").stripped_strings
-                if not symbol_name in found_symbols:
+                if not any(
+                    sym == symbol_name or sym == qual_name for sym in found_symbols
+                ):
```
Comment (vvd170501) [inline clang/tools/include-mapping/cppreference_parser.py:74]: Cannot use `if not (symbol_name in found_symbols or qual_name in found_symbols)`, because `found_symbols)` is a generator, not a list.

**Comment by vvd170501** [comment]
I've kept parser changes (excluding optimizations) in this PR, because they are needed for correct parsing of newer cppreference archives.
Without these changes, 93 lines are lost from `StdSymbolMap.inc` and must be manually added to `StdSpecialSymbolMap.inc`, resulting in 186 additional lines of diff.

**Review by kadircet — APPROVED** [review]
thanks a lot, lgtm!

LMK if i should commit this for you

**Comment by vvd170501** [comment]
> thanks a lot, lgtm!
> 
> LMK if i should commit this for you

Yes, commit it please, I don't have the permissions.

**Comment by vvd170501** [comment]
@kadircet, ping. Could you commit these changes, please?

I've rebased to make sure that 68daf7d27ecc085fe7347552736197db6453f71c didn't cause any conflicts.
