### PR TITLE
[EarlyCSE,TTI] Don't create new, unused, instructions.

### LINKED ISSUE #145183: EarlyCSE leaves around unused insertvalues when handling @llvm.aarch64.neon.st4.v8i8
```
$ cat /tmp/a.ll
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx12.0.0"

define i32 @f() {
entry:
  br label %for.cond1

for.cond1:
  %vld4 = call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr null)
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> zeroinitializer, <8 x i8> %vld4.fca.1.extract, <8 x i8> zeroinitializer, <8 x i8> zeroinitializer, ptr null)
  br label %for.cond1
}

declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr)

declare void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, ptr captures(none))

$ opt -p early-cse /tmp/a.ll -S
...
define i32 @f() {
entry:
  br label %for.cond1

for.cond1:                                        ; preds = %for.cond1, %entry
  %vld4 = call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr null)
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %0 = insertvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } { <8 x i8> zeroinitializer, <8 x i8> poison, <8 x i8> poison, <8 x i8> poison }, <8 x i8> %vld4.fca.1.extract, 1
  %1 = insertvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %0, <8 x i8> zeroinitializer, 2
  %2 = insertvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %1, <8 x i8> zeroinitializer, 3
  call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> zeroinitializer, <8 x i8> %vld4.fca.1.extract, <8 x i8> zeroinitializer, <8 x i8> zeroinitializer, ptr null)
  br label %for.cond1
}
...

$ opt -p early-cse /tmp/a.ll -S -verify-analysis-invalidation
LLVM ERROR: Function @f changed by EarlyCSEPass without invalidating analyses
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

### PR DESCRIPTION
**Pull request by fhahn**
getOrCreateResultFromMemIntrinsic can modify the current function by inserting new instructions without EarlyCSE keeping track of the changes.

Introduce a new getResultFromMemIntrinsics that returns the result, if it does not require adding new instructions. Use it when appropriate.

Fixes https://github.com/llvm/llvm-project/issues/145183

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 1]
```diff
@@ -978,7 +981,8 @@ class EarlyCSE {
         V = II->getOperand(0);
         break;
       default:
-        return TTI.getOrCreateResultFromMemIntrinsic(II, ExpectedType);
+        return TTI.getOrCreateResultFromMemIntrinsic(II, ExpectedType,
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:984]: Can we use `TmpInstructions` directly?

**Review by dtcxzyw — APPROVED** [review]
LG

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 1 above)
Comment (fhahn) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp:984]: Yes, if we make the function non-const, but that would expose much more to be potentially modified, which is why I went with passing in the SmallVectorImpl. can change if preferred

**Review by nikic — COMMENTED** [review]
It would be preferable to not create the instructions in the first place if the transform cannot take place. Is that feasible?

**Comment by nikic** [comment]
As far as I can tell, getMatchingValue/getOrCreateResult can get used either unconditionally, or for comparison against an existing value. The comparison against an existing value is of course always going to fail if new instructions are created. So I think the right way to do this would be to pass an extra flag whether creating instructions is allowed or not.

**Review by fhahn — COMMENTED** [review]
> As far as I can tell, getMatchingValue/getOrCreateResult can get used either unconditionally, or for comparison against an existing value. The comparison against an existing value is of course always going to fail if new instructions are created. So I think the right way to do this would be to pass an extra flag whether creating instructions is allowed or not.

Yep, updated the patch.

**Review by fhahn — COMMENTED** [review]
ping :)

File: llvm/include/llvm/Analysis/TargetTransformInfo.h [hunk 2]
```diff
@@ -1690,9 +1690,16 @@ class TargetTransformInfo {
   /// unordered-atomic memory intrinsic.
   LLVM_ABI unsigned getAtomicMemIntrinsicMaxElementSize() const;
 
+  /// \returns A value which is the result of the given memory intrinsic.
+  /// Returns nullptr if the target cannot return a result from the given
+  /// intrinsic, e.g. because it would require creating new instructions. Use
+  /// getOrCreateResultFromMemIntrinsic to allow creating new instructions.
+  LLVM_ABI Value *getResultFromMemIntrinsic(IntrinsicInst *Inst,
```
Comment (arsenm) [inline llvm/include/llvm/Analysis/TargetTransformInfo.h]:
```suggestion
  LLVM_ABI Value *getResultFromMemIntrinsic(const IntrinsicInst *Inst,
```

Comment (arsenm) [inline llvm/include/llvm/Analysis/TargetTransformInfo.h]: Can we avoid having 2 nearly identical functions to implement

Comment (nikic) [reply llvm/include/llvm/Analysis/TargetTransformInfo.h]: Yeah, I think it would be cleaner with one method and a boolean flag instead of two methods.

Comment (fhahn) [reply llvm/include/llvm/Analysis/TargetTransformInfo.h]: Updated to just add an extra CanCreate arg, thanks

Comment (fhahn) [reply llvm/include/llvm/Analysis/TargetTransformInfo.h]: I left it as non-const for this PR, as the function returns `Inst` in some cases, so would need const cast or updating the return type as well. If desired, I could check that separately.

File: llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp [hunk 3]
```diff
@@ -4967,18 +4967,24 @@ void AArch64TTIImpl::getPeelingPreferences(Loop *L, ScalarEvolution &SE,
...
+                                                         bool CanCreate) const {
   switch (Inst->getIntrinsicID()) {
   default:
     return nullptr;
+  case Intrinsic::aarch64_neon_ld2:
+  case Intrinsic::aarch64_neon_ld3:
+  case Intrinsic::aarch64_neon_ld4:
+    if (Inst->getType() == ExpectedType)
+      return Inst;
+    return nullptr;
```
Comment (nikic) [inline llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp]: No need to reorder the switch anymore?

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 4]
```diff
@@ -1256,7 +1257,7 @@ Value *EarlyCSE::getMatchingValue(LoadValue &InVal, ParseMemoryInst &MemInst,
   // For stores check the result values before checking memory generation
   // (otherwise isSameMemGeneration may crash).
   Value *Result = MemInst.isStore()
-                      ? getOrCreateResult(Matching, Other->getType())
+                      ? getOrCreateResult(Matching, Other->getType(), false)
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp]:
```suggestion
                      ? getOrCreateResult(Matching, Other->getType(), /*CanCreate=*/false)
```

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 5]
```diff
@@ -1278,7 +1279,7 @@ Value *EarlyCSE::getMatchingValue(LoadValue &InVal, ParseMemoryInst &MemInst,
     return nullptr;
 
   if (!Result)
-    Result = getOrCreateResult(Matching, Other->getType());
+    Result = getOrCreateResult(Matching, Other->getType(), true);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp]:
```suggestion
    Result = getOrCreateResult(Matching, Other->getType(), /*CanCreate=*/true);
```

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 5 above)
Comment (fhahn) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp]: Done thanks

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 4 above)
Comment (fhahn) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp]: done thanks

File: llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp (hunk 3 above)
Comment (fhahn) [reply llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp]: yeah, restored the original order
