### PR TITLE
[Clang] Fix crash on malformed std::partial_ordering static members

### LINKED ISSUE #53493: clang-tidy crash, when writing a wrong std::strong_ordering struct
Calling 

```
python llvm-lit.py -v modernize-use-trailing-return-type-cxx20.cpp
```

<details> 
  <summary>with `modernize-use-trailing-return-type-cxx20.cpp`</summary> 

```
// RUN: %check_clang_tidy -std=c++20 %s modernize-use-trailing-return-type %t

namespace std {
template <typename T, typename U>
struct is_same { static constexpr auto value = false; };

template <typename T>
struct is_same<T, T> { static constexpr auto value = true; };

template <typename T>
concept floating_point = std::is_same<T, float>::value || std::is_same<T, double>::value || std::is_same<T, long double>::value;
}

//
// Concepts
//

std::floating_point auto con1();
// CHECK-MESSAGES: :[[@LINE-1]]:26: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto con1() -> std::floating_point auto;{{$}}

std::floating_point auto con1() { return 3.14f; }
// CHECK-MESSAGES: :[[@LINE-1]]:26: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto con1() -> std::floating_point auto { return 3.14f; }{{$}}

namespace a {
template <typename T>
concept Concept = true;

template <typename T, typename U>
concept BinaryConcept = true;
}

a::Concept decltype(auto) con2();
// CHECK-MESSAGES: :[[@LINE-1]]:27: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto con2() -> a::Concept decltype(auto);{{$}}

a::BinaryConcept<int> decltype(auto) con3();
// CHECK-MESSAGES: :[[@LINE-1]]:38: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto con3() -> a::BinaryConcept<int> decltype(auto);{{$}}

const std::floating_point auto* volatile con4();
// CHECK-MESSAGES: :[[@LINE-1]]:42: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto con4() -> const std::floating_point auto* volatile;{{$}}

template <typename T>
int req1(T t) requires std::floating_point<T>;
// CHECK-MESSAGES: :[[@LINE-1]]:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
// CHECK-FIXES: {{^}}auto req1(T t) -> int requires std::floating_point<T>;{{$}}

template <typename T>
T req2(T t) requires requires { t + t; };
  // CHECK-MESSAGES: :[[@LINE-1]]:3: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
  // CHECK-FIXES: {{^}}auto req2(T t) -> T requires requires { t + t; };{{$}}

//
// Operator c++20 defaulted comparison operators
//
// Requires <compare>

namespace std {
struct strong_ordering {
  enum class Val { less = -1,
                   equal = 0,
                   greater = 1,
  };
  static auto const less = Val::less;
  static auto const equal = Val::equal;
  static auto const equivalent = Val::equal;
  static auto const greater = Val::greater;
  constexpr operator==(Val const &val) const { return this->val == val; }
  constexpr operator!=(Val const &val) const { return this->val != val; }
  /*   template <typename T>
    friend constexpr auto operator==(strong_ordering v, T u) noexcept -> bool requires {
      T{0};
    }
    {
      return v.val == u;
    }
    friend constexpr auto operator==(strong_ordering v, strong_ordering w) noexcept -> bool = default; */
  Val val{};
};

} // namespace std

struct TestDefaultOperatorA {
  int a{};
  int b{};

  friend auto operator<=>(const TestDefaultOperatorA &, const TestDefaultOperatorA &) noexcept = default;
};

struct TestDefaultOperatorB {
  int a{};
  int b{};
  friend auto operator==(const TestDefaultOperatorB &, const TestDefaultOperatorB &) noexcept -> bool = default;
  friend bool operator<(const TestDefaultOperatorB &, const TestDefaultOperatorB &) noexcept = default;
  // CHECK-MESSAGES: :[[@LINE-1]]:15: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
  // CHECK-FIXES: {{^}}  friend auto operator<(const TestDefaultOperatorB &, const TestDefaultOperatorB &) noexcept -> bool = default;{{$}}
};

```

</details> 

Crashes with

```
PS D:\Febbe\workspace\llvm-project\build\bin> python llvm-lit.py -v d:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\checkers\modernize-use-trailing-return-type-cxx20.cpp
llvm-lit.py: D:\Febbe\workspace\llvm-project\llvm\utils\lit\lit\llvm\config.py:46: note: using lit tools: C:\Program Files\Git\usr\bin
-- Testing: 1 tests, 1 workers --
FAIL: Clang Tools :: clang-tidy/checkers/modernize-use-trailing-return-type-cxx20.cpp (1 of 1)
******************** TEST 'Clang Tools :: clang-tidy/checkers/modernize-use-trailing-return-type-cxx20.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   C:/Users/Febbe/AppData/Local/Programs/Python/Python39/python.exe D:/Febbe/workspace/llvm-project/clang-tools-extra/test/../test\clang-tidy\check_clang_tidy.py -std=c++20 D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\checkers\modernize-use-trailing-return-type-cxx20.cpp modernize-use-trailing-return-type D:\Febbe\workspace\llvm-project\build\tools\clang\tools\extra\test\clang-tidy\checkers\Output\modernize-use-trailing-return-type-cxx20.cpp.tmp
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "C:/Users/Febbe/AppData/Local/Programs/Python/Python39/python.exe" "D:/Febbe/workspace/llvm-project/clang-tools-extra/test/../test\clang-tidy\check_clang_tidy.py" "-std=c++20" "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\checkers\modernize-use-trailing-return-type-cxx20.cpp" "modernize-use-trailing-return-type" "D:\Febbe\workspace\llvm-project\build\tools\clang\tools\extra\test\clang-tidy\checkers\Output\modernize-use-trailing-return-type-cxx20.cpp.tmp"
# command output:
Running ['clang-tidy', 'D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp', '-fix', '--checks=-*,modernize-use-trailing-return-type', '-config={}', '--', '-std=c++20', '-nostdinc++']...
clang-tidy D:\Febbe\workspace\llvm-project\build\tools\clang\tools\extra\test\clang-tidy\checkers\Output\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp -fix --checks=-*,modernize-use-trailing-return-type -config={} -- -std=c++20 -nostdinc++ failed:
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-tidy D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp -fix --checks=-*,modernize-use-trailing-return-type -config={} -- -std=c++20 -nostdinc++
1.      D:\Febbe\workspace\llvm-project\build\tools\clang\tools\extra\test\clang-tidy\checkers\Output\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:91:2: current parser token ';'
2.      D:\Febbe\workspace\llvm-project\build\tools\clang\tools\extra\test\clang-tidy\checkers\Output\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:86:1: parsing struct/union/class body 'TestDefaultOperatorA'
 #0 0x00007ff7cfd06e20 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1296e20)
 #1 0x00007ff7cff46e7e (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x14d6e7e)
 #2 0x00007ff7cef82a56 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x512a56)
 #3 0x00007ff7cef8ba62 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x51ba62)
 #4 0x00007ff7cef8be3b (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x51be3b)
 #5 0x00007ff7cef846ff (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x5146ff)
 #6 0x00007ff7cef7190c (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x50190c)
 #7 0x00007ff7d091cbf4 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1eacbf4)
 #8 0x00007ff7d091e2f6 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1eae2f6)
 #9 0x00007ff7d08b2274 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1e42274)
#10 0x00007ff7d088ae97 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1e1ae97)
#11 0x00007ff7d088c259 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1e1c259)
#12 0x00007ff7d089076e (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1e2076e)
#13 0x00007ff7d08871f2 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1e171f2)
#14 0x00007ff7d070e805 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1c9e805)
#15 0x00007ff7d070e618 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1c9e618)
#16 0x00007ff7d06f5b5a (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1c85b5a)
#17 0x00007ff7d0164ed5 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x16f4ed5)
#18 0x00007ff7d0191b32 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x1721b32)
#19 0x00007ff7d01650c9 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x16f50c9)
#20 0x00007ff7d0164c04 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x16f4c04)
#21 0x00007ff7d0164160 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x16f4160)
#22 0x00007ff7d019198c (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x172198c)
#23 0x00007ff7ceaad3b0 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0x3d3b0)
#24 0x00007ff7cf8958a8 (D:\Febbe\workspace\llvm-project\build\bin\clang-tidy.exe+0xe258a8)
#25 0x00007ffcc70d7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#26 0x00007ffcc8202651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)


# command stderr:
Traceback (most recent call last):
  File "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\check_clang_tidy.py", line 260, in <module>
    main()
  File "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\check_clang_tidy.py", line 256, in main
    CheckRunner(args, extra_args).run()
  File "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\check_clang_tidy.py", line 207, in run
    clang_tidy_output = self.run_clang_tidy()
  File "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\check_clang_tidy.py", line 168, in run_clang_tidy
    clang_tidy_output = try_run(args)
  File "D:\Febbe\workspace\llvm-project\clang-tools-extra\test\clang-tidy\check_clang_tidy.py", line 45, in try_run
    subprocess.check_output(args, stderr=subprocess.STDOUT).decode(errors='ignore')
  File "c:\users\febbe\appdata\local\programs\python\python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\users\febbe\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['clang-tidy', 'D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp', '-fix', '--checks=-*,modernize-use-trailing-return-type', '-config={}', '--', '-std=c++20', '-nostdinc++']' returned non-zero exit status 3221225477.

error: command failed with exit status: 1

--

********************
********************
Failed Tests (1):
  Clang Tools :: clang-tidy/checkers/modernize-use-trailing-return-type-cxx20.cpp


Testing Time: 1.91s
  Failed: 1
```

### LINKED ISSUE #56571: Crash when compiling strong_ordering with int statics
clang crashes when compiling a `strong_ordering` class implementation
that does not contain `less/equal/greater` members of type `strong_ordering`.
I was trying to create something that would not require out-of-class inline
static variables, for which I get a warning when compiling with musl.

```c++
namespace std {
class strong_ordering {
    int _v;
public:
    constexpr strong_ordering (int v) :_v(v) {}
    constexpr operator int (void) const { return _v; }
    constexpr bool operator== (int v) const { return _v == v; }
    constexpr bool operator< (int v) const { return _v < v; }
    constexpr bool operator<= (int v) const { return _v <= v; }
    constexpr bool operator> (int v) const { return _v > v; }
    constexpr bool operator>= (int v) const { return _v >= v; }
    constexpr bool operator== (const strong_ordering& v) const { return _v == v._v; }
    constexpr bool operator< (const strong_ordering& v) const { return _v < v._v; }
    constexpr bool operator<= (const strong_ordering& v) const { return _v <= v._v; }
    constexpr bool operator> (const strong_ordering& v) const { return _v > v._v; }
    constexpr bool operator>= (const strong_ordering& v) const { return _v >= v._v; }
    static constexpr const int less = -1;
    static constexpr const int equal = 0;
    static constexpr const int greater = 1;
};
}

struct A {
    int v;
    auto operator<=> (const A& a) const = default;
};
```
Compiling with `clang --std=c++20 -c` produces:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang --std=c++20 -c tes.cc
1.	tes.cc:26:2: current parser token ';'
2.	tes.cc:23:1: parsing struct/union/class body 'A'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/usr/lib/libLLVM-14.so(+0xcd553a)[0x7fa0dc08c53a]
/usr/lib/libLLVM-14.so(_ZN4llvm3sys17RunSignalHandlersEv+0x2f)[0x7fa0dc089bcf]
/usr/lib/libLLVM-14.so(+0xbbfac9)[0x7fa0dbf76ac9]
/usr/lib/libc.so.6(+0x3e8e0)[0x7fa0dafb28e0]
/usr/lib/libclang-cpp.so.14(_ZNK5clang10RecordDecl11field_beginEv+0x8)[0x7fa0e2ea5088]
/usr/lib/libclang-cpp.so.14(_ZNK5clang22ComparisonCategoryInfo9ValueInfo16hasValidIntValueEv+0x5f)[0x7fa0e2ec98bf]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema27CheckComparisonCategoryTypeENS_22ComparisonCategoryTypeENS_14SourceLocationENS0_23ComparisonCategoryUsageE+0x630)[0x7fa0e34d0620]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema34CheckExplicitlyDefaultedComparisonEPNS_5ScopeEPNS_12FunctionDeclENS0_23DefaultedComparisonKindE+0xcd8)[0x7fa0e34e1b88]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema32CheckExplicitlyDefaultedFunctionEPNS_5ScopeEPNS_12FunctionDeclE+0x123)[0x7fa0e34e4f93]
/usr/lib/libclang-cpp.so.14(+0x1059ed2)[0x7fa0e34c3ed2]
/usr/lib/libclang-cpp.so.14(_ZN5clang4Sema22CheckCompletedCXXClassEPNS_5ScopeEPNS_13CXXRecordDeclE+0xb37)[0x7fa0e34ece67]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser27ParseCXXMemberSpecificationENS_14SourceLocationES1_RNS_25ParsedAttributesWithRangeEjPNS_4DeclE+0x4f5)[0x7fa0e2c84185]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser19ParseClassSpecifierENS_3tok9TokenKindENS_14SourceLocationERNS_8DeclSpecERKNS0_18ParsedTemplateInfoENS_15AccessSpecifierEbNS0_15DeclSpecContextERNS_25ParsedAttributesWithRangeE+0x1254)[0x7fa0e2c85ae4]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser26ParseDeclarationSpecifiersERNS_8DeclSpecERKNS0_18ParsedTemplateInfoENS_15AccessSpecifierENS0_15DeclSpecContextEPNS0_18LateParsedAttrListE+0x737)[0x7fa0e2c69627]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser30ParseDeclOrFunctionDefInternalERNS_25ParsedAttributesWithRangeERNS_15ParsingDeclSpecENS_15AccessSpecifierE+0x83)[0x7fa0e2ce3b73]
/usr/lib/libclang-cpp.so.14(+0x87a438)[0x7fa0e2ce4438]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser24ParseExternalDeclarationERNS_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0xa0e)[0x7fa0e2cf968e]
/usr/lib/libclang-cpp.so.14(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb+0x256)[0x7fa0e2cf9a16]
/usr/lib/libclang-cpp.so.14(_ZN5clang8ParseASTERNS_4SemaEbb+0x238)[0x7fa0e2c43e38]
/usr/lib/libclang-cpp.so.14(_ZN5clang14FrontendAction7ExecuteEv+0x189)[0x7fa0e421d929]
/usr/lib/libclang-cpp.so.14(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x187)[0x7fa0e41bcdf7]
/usr/lib/libclang-cpp.so.14(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x1ba)[0x7fa0e427478a]
clang(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x1131)[0x55aeefe8a6f1]
clang(+0x19337)[0x55aeefe8c337]
/usr/lib/libclang-cpp.so.14(+0x1aaa699)[0x7fa0e3f14699]
/usr/lib/libLLVM-14.so(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0x27)[0x7fa0dbf76b97]
/usr/lib/libclang-cpp.so.14(+0x1ab01ff)[0x7fa0e3f1a1ff]
/usr/lib/libclang-cpp.so.14(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x93)[0x7fa0e3f2f903]
/usr/lib/libclang-cpp.so.14(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xf9)[0x7fa0e3f2fcd9]
/usr/lib/libclang-cpp.so.14(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x122)[0x7fa0e3f38012]
clang(main+0x172a)[0x55aeefe8146a]
/usr/lib/libc.so.6(+0x29290)[0x7fa0daf9d290]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7fa0daf9d34a]
clang(_start+0x25)[0x55aeefe82655]
clang-14: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-14: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/me/tes-8c0234.cpp
clang-14: note: diagnostic msg: /tmp/me/tes-8c0234.sh
clang-14: note: diagnostic msg: 

********************
```
File /tmp/me/tes-8c0234.cpp contains the above source with additonal header:
```
# 1 "tes.cc"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 432 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "tes.cc" 2
```
File /tmp/me/tes-8c0234.sh contains:
```
# Crash reproducer for clang version 14.0.6
# Driver args: "--std=c++20" "-c" "tes.cc"
# Original command:  "/usr/bin/clang-14" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "tes.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/me/progs/tmp" "-resource-dir" "/usr/lib/clang/14.0.6" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/x86_64-pc-linux-gnu" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/backward" "-internal-isystem" "/usr/lib/clang/14.0.6/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "--std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir=/home/me/progs/tmp" "-ferror-limit" "19" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "tes.o" "-x" "c++" "tes.cc"
 "/usr/bin/clang-14" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "tes.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/me/progs/tmp" "--std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir=/home/me/progs/tmp" "-ferror-limit" "19" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "tes-8c0234.cpp"
```

### LINKED ISSUE #170015: [clang] Crash with spaceship operator and floating-point values
using the following code with Clang21.1.0 and the upcoming Clang22.0.0, with the flags `-std=c++23 -ffreestanding -nostdlib -fno-builtin -nostdinc -nostdinc++` causes the compiler to crash.

```cpp

namespace std {
    struct partial_ordering {
        signed char value;

        constexpr partial_ordering(signed char v) : value(v) {}

        // relational operators (minimal)
        constexpr bool operator==(partial_ordering other) const { return value == other.value; }
        constexpr bool operator!=(partial_ordering other) const { return value != other.value; }
        constexpr bool operator<(partial_ordering other) const { return value < other.value; }
        constexpr bool operator>(partial_ordering other) const { return value > other.value; }
        constexpr bool operator<=(partial_ordering other) const { return value <= other.value; }
        constexpr bool operator>=(partial_ordering other) const { return value >= other.value; }

        // static constants for convenience
        static constexpr signed char less = -1;
        static constexpr signed char equivalent = 0;
        static constexpr signed char greater = 1;
        static constexpr signed char unordered = 2;
    };
}

struct compare_result {
    signed char v; // -1, 0, 1, 2 for unordered

    template <typename T>
    constexpr compare_result(T r) {
        if (r < 0) v = -1;
        else if (r > 0) v = 1;
        else if (r == 0) v = 0;
        else v = 2; // unordered, e.g., NaN
    }

    constexpr bool operator==(const compare_result& o) const { return v == o.v; }
    constexpr bool operator<(const compare_result& o) const { return v < o.v; }
};

int main() {
    float a = 3.0f, b = 3.5f;
    compare_result r = a <=> b;
    int c = r.v;
}
````

the code compiles correctly using the same flags under GCC 15.2. I've used Compiler explorer to test it. adding the `-v` flags produce the following results

```
clang version 22.0.0git (https://github.com/llvm/llvm-project.git 9bae84b01718e53495abf50958abc86ea45f16bb)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /cefs/ee/eec5d4d1d46cbdcf81dd02c6_clang-trunk-20251129/bin
Found candidate GCC installation: /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.0
Selected GCC installation: /opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/16.0.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
 (in-process)
 "/cefs/ee/eec5d4d1d46cbdcf81dd02c6_clang-trunk-20251129/bin/clang-22" -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -ffreestanding -target-cpu x86-64 -tune-cpu generic -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fdebug-compilation-dir=/app -v -fcoverage-compilation-dir=/app -nostdsysteminc -nobuiltininc -resource-dir /cefs/ee/eec5d4d1d46cbdcf81dd02c6_clang-trunk-20251129/lib/clang/22 -std=c++23 -fdeprecated-macro -ferror-limit 19 -fno-builtin -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -fdwarf2-cfi-asm -o /app/output.s -x c++ <source>
clang -cc1 version 22.0.0git based upon LLVM 22.0.0git default target x86_64-unknown-linux-gnu
#include "..." search starts here:
End of search list.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -g -o /app/output.s -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 -ffreestanding -nostdlib -fno-builtin -nostdinc -nostdinc++ -v <source>
1.	<source>:41:31: current parser token ';'
2.	<source>:39:12: parsing function body 'main'
3.	<source>:39:12: in compound statement ('{}')
 #0 0x0000000003cd7358 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3cd7358)
 #1 0x0000000003cd4d2c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3cd4d2c)
 #2 0x0000000003c1ac38 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000786daa842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000007294195 clang::RecordDecl::field_begin() const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x7294195)
 #5 0x0000000007272aa2 clang::ComparisonCategoryInfo::ValueInfo::hasValidIntValue() const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x7272aa2)
 #6 0x000000000665f2e6 clang::Sema::CheckComparisonCategoryType(clang::ComparisonCategoryType, clang::SourceLocation, clang::Sema::ComparisonCategoryUsage) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x665f2e6)
 #7 0x0000000006768cb7 clang::Sema::CheckCompareOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, clang::BinaryOperatorKind) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6768cb7)
 #8 0x000000000676a294 clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x676a294)
 #9 0x000000000676b760 clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x676b760)
#10 0x000000000676bb3c clang::Sema::ActOnBinOp(clang::Scope*, clang::SourceLocation, clang::tok::TokenKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x676bb3c)
#11 0x0000000006265bfc clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6265bfc)
#12 0x0000000006290a70 clang::Parser::ParseInitializer(clang::Decl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6290a70)
#13 0x000000000621d855 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x621d855)
#14 0x0000000006231ffc clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6231ffc)
#15 0x0000000006234a0c clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6234a0c)
#16 0x0000000006234e5a clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6234e5a)
#17 0x00000000062f15df clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::LabelDecl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x62f15df)
#18 0x00000000062f1f26 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::LabelDecl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x62f1f26)
#19 0x00000000062fb419 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x62fb419)
#20 0x00000000062fbeba clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x62fbeba)
#21 0x00000000061e5b4b clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61e5b4b)
#22 0x000000000623245f clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x623245f)
#23 0x00000000061def8f clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61def8f)
#24 0x00000000061df6c7 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61df6c7)
#25 0x00000000061e809f clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61e809f)
#26 0x00000000061e98a7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61e98a7)
#27 0x00000000061c277a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x61c277a)
#28 0x0000000004595f65 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4595f65)
#29 0x000000000489760a clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x489760a)
#30 0x00000000048164eb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x48164eb)
#31 0x000000000498c14b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x498c14b)
#32 0x0000000000dce015 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xdce015)
#33 0x0000000000dc5ecb ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#34 0x0000000000dc5f6d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#35 0x0000000004603299 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#36 0x0000000003c1b053 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c1b053)
#37 0x00000000046034b9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#38 0x00000000045c5e42 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x45c5e42)
#39 0x00000000045c6d21 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x45c6d21)
#40 0x00000000045cf90c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x45cf90c)
#41 0x0000000000dca999 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xdca999)
#42 0x0000000000c74c84 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc74c84)
#43 0x0000786daa829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#44 0x0000786daa829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#45 0x0000000000dc5965 _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xdc5965)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
````

### PR DESCRIPTION
**Pull request by codepankajpy**
This fixes a crash (segmentation fault) when the standard library implementation of comparison categories (like `std::partial_ordering`) is malformed.

Specifically, if the static members (like `equivalent`) are defined as a primitive type (e.g., `int`) instead of the comparison category type itself, the compiler previously attempted to process them incorrectly, leading to a crash.

This adds strict type checking in `ComparisonCategoryInfo::lookupValueInfo`. If the found static member does not match the record type, it is rejected safely, triggering a diagnostic error instead of a crash.

Fixes #170015
Fixes #56571

### CODE REVIEW

**Comment by tbaederr** [comment]
1) Add "Fixes <link to issue>" to your PR description
2) You need to add a test as well.

File: clang/lib/AST/ComparisonCategories.cpp [hunk 1]
```diff
@@ -49,7 +49,7 @@ bool ComparisonCategoryInfo::ValueInfo::hasValidIntValue() const {
   // Before we attempt to get the value of the first field, ensure that we
   // actually have one (and only one) field.
   const auto *Record = VD->getType()->getAsCXXRecordDecl();
-  if (Record->getNumFields() != 1 ||
+  if (!Record || Record->getNumFields() != 1 ||
```
Comment (eoan-ermine) [inline clang/lib/AST/ComparisonCategories.cpp]: Shouldn't it be `!Record && (...)` instead of `!Record || ...`?

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -602,6 +602,7 @@ Bug Fixes to C++ Support
 - Fixed an issue where templates prevented nested anonymous records from checking the deletion of special members. (#GH167217)
 - Fixed spurious diagnoses of certain nested lambda expressions. (#GH149121) (#GH156579)
 - Fix the result of ``__is_pointer_interconvertible_base_of`` when arguments are qualified and passed via template parameters. (#GH135273)
+- - Fixed a crash when standard comparison categories (e.g. ``std::partial_ordering``) are defined with incorrect static member types. (#GH170015)
```
Comment (tbaederr) [inline clang/docs/ReleaseNotes.rst]:
```suggestion
- Fixed a crash when standard comparison categories (e.g. ``std::partial_ordering``) are defined with incorrect static member types. (#GH170015)
```

**Review by ojhunt — CHANGES_REQUESTED** [review]
LGTM, just some super minor nits on style, and I'd just like a few more tests - you've added logic to be safe against `using partial_ordering = int`, etc so we should make sure that's tested.

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit

**Review by zwuis — COMMENTED** [review]
Thanks!

Can you test if this patch fixes #56571?

**Comment by code-pankaj** [comment]
@cor3ntin @zwuis Thanks for the review!

I have renamed the variables as requested. I also verified that this PR fixes #56571 and added a specific test case to cover it.

I have updated the PR description accordingly. Please let me know if there is anything else I can help with.

**Review by cor3ntin — APPROVED** [review]
LGTM - Will you need us to merge that for you? Thanks!
