### PR TITLE
[flang][OpenMP] Initialize allocatable members of derived types

### LINKED ISSUE #114888: [Flang] [OpenMP] Execution error when derived type with nested definitions is specified in private clause of parallel construct
```
Version of flang-new : 20.0.0(5621929f7f4878c318deecb592cd03f5ecbb83ba)/AArch64
```

When `derived type` with nested definitions is specified in a `private` clause of `parallel` construct, segmentation fault (core dumped) occurs.  
The above statement is (2) in the program.  
Terminates normally if not nested.  
The above statement is (1) in the program.

The following are the test program, Flang-new, Gfortran and ifx compilation/execution result.

sngg188a_2.f90:
```fortran
module m1
  type y
     integer:: y1=2
  end type y
  type x
     integer:: x1=1
     type(y),allocatable:: x2(:)
  end type x
end module m1

subroutine s1
  use m1
  type(x):: v1
  allocate( v1%x2(2:3))
  v1%x2(2:3)%y1=[2,3]
!$omp parallel private( v1 )
  v1%x1=2          ! (1)
  v1%x2%y1=-1      ! (2)
!$omp end parallel
end subroutine s1

program main
  call s1
  print *,'pass'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang-new -fopenmp sngg188a_2.f90; ./a.out
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
Segmentation fault (core dumped)
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp sngg188a_2.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp sngg188a_2.f90; ./a.out
 pass
$
```

### LINKED ISSUE #114889: [Flang][OpenMP] Execution error when derived type is specified in lastprivate clause of sections construct
```
Version of flang-new : 20.0.0(5621929f7f4878c318deecb592cd03f5ecbb83ba)/AArch64
```

When `derived type` is specified in `lastprivate` clause of `sections` construct, segmentation fault (core dumped) occurs.

The following are the test program, Flang-new, Gfortran and ifx compilation/execution result.

FT_OMP_LastPrivate_009_2232.f90:
```fortran
program main
  type x
     integer::x2
     character(len=5)::c1
     integer,allocatable::x1(:,:)
  end type x
  type(x) :: v(2)
  allocate(v(1)%x1(2,2))
  v(1)%x1 = 11
!$omp parallel
!$omp sections lastprivate(v)
  if (any(v(1)%x1/=11)) print *,1201,v(1)%x1
  deallocate(v(1)%x1)
  allocate(v(1)%x1(4,6))
  v(1)%x1 = 21
!$omp end sections
!$omp end parallel
  print *,'PASS'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang-new -fopenmp FT_OMP_LastPrivate_009_2232.f90; ./a.out
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
Segmentation fault (core dumped)
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp FT_OMP_LastPrivate_009_2232.f90; ./a.out
        1201           0           0           0           0
 PASS
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp FT_OMP_LastPrivate_009_2232.f90; ./a.out
        1201           0           0           0           0
 PASS
$
```

### PR DESCRIPTION
**Pull request by luporl**
Allocatable members of privatized derived types must be allocated,
with the same bounds as the original object, whenever that member
is also allocated in it, but Flang was not performing such
initialization.

The `Initialize` runtime function can't perform this task unless
its signature is changed to receive an additional parameter, the
original object, that is needed to find out which allocatable
members, with their bounds, must also be allocated in the clone.
As `Initialize` is used not only for privatization, sometimes this
other object won't even exist, so this new parameter would need
to be optional.
Because of this, it seemed better to add a new runtime function:
`InitializeClone`.
To avoid unnecessary calls, lowering inserts a call to it only for
privatized items that are derived types with allocatable members.

Fixes https://github.com/llvm/llvm-project/issues/114888
Fixes https://github.com/llvm/llvm-project/issues/114889

### CODE REVIEW

**Comment by luporl** [comment]
Note: I couldn't find a way to write a unit test for `InitializeClone`.
The main issue is that it doesn't seem to be possible to create an instance of `typeInfo::DerivedType`.

**Comment by kiranchandramohan** [comment]
This is great.

> To handle this, a new runtime function was added: InitializeClone.

Could you also add some info on why the existing functions (like Initialize in runtime/derived.cpp) are not sufficient?

**Comment by luporl** [comment]
> Could you also add some info on why the existing functions (like Initialize in runtime/derived.cpp) are not sufficient?

Added to the PR description. Please let me know if it's not clear yet.

**Review by klausler — APPROVED** [review]
LGTM, good work.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 1]
```diff
@@ -116,6 +116,31 @@ void DataSharingProcessor::cloneSymbol(const semantics::Symbol *sym) {
...
+    assert(addr);
+    mlir::Type ty = addr.getType();
+
+    // Unwrap type
+    while (auto eleTy = fir::dyn_cast_ptrOrBoxEleTy(ty))
+      ty = eleTy;
+    // For arrays, use its element type
+    if (auto seqTy = mlir::dyn_cast<fir::SequenceType>(ty))
+      ty = seqTy.getEleTy();
+    return fir::isRecordWithAllocatableMember(ty);
```
[the remark this answers is not in the document]
Comment (jeanPerier) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:137]: Note that this will also flag polymorphic objects as potentially having allocatable components (the dynamic type extending the static type may have such components and is unknown).

**Review by jeanPerier — APPROVED** [review]
LGTM

**Review by kiranchandramohan — APPROVED** [review]
LG.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (luporl) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp]: Thanks for catching that.

**Comment by luporl** [comment]
Thanks everyone for the reviews.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 2]
```diff
@@ -165,8 +182,8 @@ bool DataSharingProcessor::needBarrier() {
   // variables.
   // Emit implicit barrier for linear clause. Maybe on somewhere else.
   for (const semantics::Symbol *sym : allPrivatizedSymbols) {
-    if (sym->test(semantics::Symbol::Flag::OmpFirstPrivate) &&
-        sym->test(semantics::Symbol::Flag::OmpLastPrivate))
+    if (sym->test(semantics::Symbol::Flag::OmpLastPrivate) &&
+        (sym->test(semantics::Symbol::Flag::OmpFirstPrivate) || callsInitClone))
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: Why don't we need this barrier in other cases, e.g. when `FortranAInitialize` (not the clone variant) is used?

Comment (luporl) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: Because `FortranAInitializeClone` receives an extra argument, that is the original variable.
When `lastprivate` is used, the original variable is modified by one of the running threads. Without the barrier, another thread may still be using it to initialize its copy.

Comment (tblah) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: The original variable is also used for other similar cases e.g. assumed shape arrays. Maybe for now we should always use the barrier?

Comment (luporl) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: This will likely affect performance, but it is certainly better than having hard-to-debug race conditions.
I'm OK with it as a temporary fix.

Later, we could rename `callsInitClone` to `needsBarrier` and set it whenever a given operation may modify a variable that is also read by other threads.

Comment (tblah) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: Do I understand correctly that the barrier here isn't strictly necessary because v and v2 are different symbols?
 https://github.com/llvm/llvm-project/pull/120295/files#diff-7f918db826ee2c02ce8eb509f6d8367ad741d2b1537396959d510b5fe6a29a37R52

I'm trying to add the extra barriers in my re-implementation of this patch in my changes for https://discourse.llvm.org/t/rfc-openmp-supporting-delayed-task-execution-with-firstprivate-variables/83084/7

Thanks for the help!

Comment (luporl) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: The barrier there is necessary. It prevents the original `v` variable from being updated by `lastprivate` before every thread has finished initializing its private copy of `v` (using the original variable `v`).

As `v2` doesn't have an allocatable member, `InitializeClone` doesn't need to be called for it.
If it was the only symbol, as it is just written by `lastprivate` but not read by other threads, no barrier would be needed.
And if both `v` and `v2` had allocatable members, a single barrier after the initialization of both would be enough, as their original variables are not read by any threads after that, but only written by `lastprivate` later.

Comment (tblah) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:186]: Thanks!
