### PR TITLE
[DAGCombiner][RISCV] Don't propagate the exact flag from udiv/sdiv to urem/srem.

### LINKED ISSUE #145360: rem/div-related miscompile from riscv64 and aarch64 backends
I believe we're lowering this incorrectly:
```llvm
define i32 @f(i32 %0, ptr %1) {
  %3 = srem i32 %0, 256
  store i32 %3, ptr %1, align 4
  %4 = sdiv exact i32 %0, 256
  ret i32 %4
}
```
let's invoke `f` with `%0=2` and `%1` being a valid pointer to 4 bytes. in this case we should store 2 into memory and then return poison.

however, from the riscv64+m backend we get:
```
f:
        sraiw   a0, a0, 8
        sw      zero, 0(a1)
        ret
```
the aarch64 output is functionally identical

### PR DESCRIPTION
**Pull request by topperc**
If we simplify a udiv/sdiv using the exact flag we shouldn't
propagate that simplifaction to any urem/srem that happens to
use the same operands. If the exact flag is wrong, the udiv/sdiv
will produce poison, but that doesn't mean we can make the urem/srem
simplify to 0.
    
Fixes #145360.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -4961,11 +4961,15 @@ SDValue DAGCombiner::visitSDIV(SDNode *N) {
     // (Dividend - (Quotient * Divisor).
     if (SDNode *RemNode = DAG.getNodeIfExists(ISD::SREM, N->getVTList(),
                                               { N0, N1 })) {
-      SDValue Mul = DAG.getNode(ISD::MUL, DL, VT, V, N1);
-      SDValue Sub = DAG.getNode(ISD::SUB, DL, VT, N0, Mul);
-      AddToWorklist(Mul.getNode());
-      AddToWorklist(Sub.getNode());
-      CombineTo(RemNode, Sub);
+      // If the udiv has the exact flag we shouldn't propagate it to the
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:4964]: sdiv?

**Review by RKSimon — APPROVED** [review]
LGTM with one minor

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 1 above)
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:4964]:
```suggestion
      // If the sdiv has the exact flag we shouldn't propagate it to the
```

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 2]
```diff
@@ -9403,6 +9403,8 @@ SDValue SelectionDAG::getLoad(ISD::MemIndexedMode AM, ISD::LoadExtType ExtType,
   void *IP = nullptr;
   if (SDNode *E = FindNodeOrInsertPos(ID, dl, IP)) {
     cast<LoadSDNode>(E)->refineAlignment(MMO);
+    if (cast<LoadSDNode>(E)->getMemOperand()->getRanges() && !MMO->getRanges())
+      cast<LoadSDNode>(E)->getMemOperand()->clearRanges();
```
Comment (nikic) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Unrelated change?

Comment (topperc) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Oops, yes.
