### PR TITLE
[Sema] Preserve ContainsUnexpandedParameterPack in TransformLambdaExpr

### LINKED ISSUE #56852: Clang crashes in TemplateArgument::isPackExpansion on current main.
The following snippet crashes: https://wandbox.org/permlink/ypCN8tQA9I26lW5L

### LINKED ISSUE #85667: ICE on fold expression in nested lambda with parameter pack in a templated entity
Problematic code (should be valid):
```cpp
template<int = 0>
void f() {
    []<int... Is>() {
        ([i = Is]{}, ...);
    }.template operator()<1,2,3>();
}

void f2() {
    f();
}
```
Flags: `-std=c++20`

Crash log:
```
clang++: /root/llvm-project/llvm/include/llvm/Support/Casting.h:109: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = clang::PackExpansionExpr; From = clang::Expr]: Assertion `Val && "isa<> used on a null pointer"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-18.1.0/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-13.2.0 -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<eof> parser at end of file
2.	<source>:2:6: instantiating function definition 'f<0>'
3.	<source>:3:5: instantiating function definition 'f()::(anonymous class)::operator()<1, 2, 3>'
 #0 0x00000000038d53d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x38d53d8)
 #1 0x00000000038d30bc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x38d30bc)
 #2 0x000000000381baa8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f6145242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f61452969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f6145242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f61452287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f614522871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f6145239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000007546433 (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x7546433)
#10 0x0000000007549c84 clang::TemplateArgument::isPackExpansion() const (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x7549c84)
#11 0x0000000006cda1a4 clang::Sema::collectUnexpandedParameterPacks(clang::TemplateArgument, llvm::SmallVectorImpl<std::pair<llvm::PointerUnion<clang::TemplateTypeParmType const*, clang::NamedDecl*>, clang::SourceLocation>>&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6cda1a4)
#12 0x0000000006c351c1 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCXXFoldExpr(clang::CXXFoldExpr*) SemaTemplateInstantiate.cpp:0:0
#13 0x0000000006c291d9 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#14 0x0000000006c5eedf clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
#15 0x0000000006c5fac4 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#16 0x0000000006c65f4a clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6c65f4a)
#17 0x0000000006cb6486 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6cb6486)
#18 0x0000000006251ba1 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6251ba1)
#19 0x0000000006b9ac42 clang::Sema::DeduceReturnType(clang::FunctionDecl*, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6b9ac42)
#20 0x0000000006641d3a clang::Sema::DiagnoseUseOfDecl(clang::NamedDecl*, llvm::ArrayRef<clang::SourceLocation>, clang::ObjCInterfaceDecl const*, bool, bool, clang::ObjCInterfaceDecl*, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6641d3a)
#21 0x0000000006a1694f clang::Sema::BuildCallToMemberFunction(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6a1694f)
#22 0x00000000066b42ae clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x66b42ae)
#23 0x00000000066b6f3c clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x66b6f3c)
#24 0x0000000006c34770 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
#25 0x0000000006c2929a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#26 0x0000000006c5eedf clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
#27 0x0000000006c5fac4 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#28 0x0000000006c65f4a clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6c65f4a)
#29 0x0000000006cb6486 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6cb6486)
#30 0x0000000006cb48bf clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6cb48bf)
#31 0x0000000006274989 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#32 0x0000000006275162 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x6275162)
#33 0x00000000060fd531 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x60fd531)
#34 0x00000000060f02ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x60f02ea)
#35 0x000000000415d928 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x415d928)
#36 0x00000000043cbfe9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x43cbfe9)
#37 0x000000000434ba9e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x434ba9e)
#38 0x00000000044ab01e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x44ab01e)
#39 0x0000000000c10cd6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0xc10cd6)
#40 0x0000000000c084fa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#41 0x000000000419ee49 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#42 0x000000000381bf54 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x381bf54)
#43 0x000000000419f43f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#44 0x00000000041671c5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x41671c5)
#45 0x0000000004167c2d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x4167c2d)
#46 0x000000000416fb65 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0x416fb65)
#47 0x0000000000c0e06c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0xc0e06c)
#48 0x0000000000b05134 main (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0xb05134)
#49 0x00007f6145229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#50 0x00007f6145229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#51 0x0000000000c07fde _start (/opt/compiler-explorer/clang-assertions-18.1.0/bin/clang+++0xc07fde)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```
Reproduction on godbolt: https://godbolt.org/z/EosG7Y6Ms

### PR DESCRIPTION
**Pull request by zyn0217**
The lambda `ContainsUnexpandedParameterPack` flag is used for the expressions' dependency computing and is therefore essential for pack expansion. We previously lost the flag's preservation during the lambda's transform, which caused some issues, e.g. a fold expression couldn't properly expand inside a template.

This patch alleviates the issue by retaining the flag in more scenarios. Note that we still have problems with constraints involving packs regarding lambdas, and dealing with that would take more effort, and we'd like to fix them in the future.

Fixes https://github.com/llvm/llvm-project/issues/56852
Fixes https://github.com/llvm/llvm-project/issues/85667
Mitigates https://github.com/llvm/llvm-project/issues/99877 because the attributes were not handled in this patch.

### CODE REVIEW

**Comment by cor3ntin** [comment]
What you have make sense i think. Let me know when you remove the draft status so i can start reviewing the details

**Comment by zyn0217** [comment]
I was waiting for the CI, but it seems Linux CI would take hours. However that shouldn't block the review I think, because Windows CI is green now.

File: clang/test/SemaTemplate/lambda-capture-pack.cpp [hunk 1]
```diff
@@ -23,3 +23,104 @@ namespace PR41576 {
...
+  }(2, 'b');
+
+#if 0
+  // https://github.com/llvm/llvm-project/issues/18873
+  [](auto ...x) { // #1
+    ([&](auto ...y) {  // #2
+      ([x, y] { }(), ...); // #3
+    })(1, 'a');  // #4
+  }(2, 'b');  // #5
+
```
Comment (zyn0217) [inline clang/test/SemaTemplate/lambda-capture-pack.cpp:96]: I'm unsure if it's feasible to sneak in these tests, though they still crash for a different reason after this patch. @cor3ntin lmk what you think.

File: clang/lib/Sema/TreeTransform.h [hunk 2]
```diff
@@ -14636,6 +14645,20 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
...
+  // flag from a Stmt, so we have to revisit the lambda.
+  if (!LSICopy.ContainsUnexpandedParameterPack) {
+    llvm::SmallVector<UnexpandedParameterPack> UnexpandedPacks;
+    getSema().collectUnexpandedParameterPacksFromLambda(NewCallOperator,
+                                                        UnexpandedPacks);
+    // FIXME: Should we call Sema::DiagnoseUnexpandedParameterPacks() instead?
+    // Unfortunately, that requires the LambdaScopeInfo to exist, which has been
+    // removed by ActOnFinishFunctionBody().
+    LSICopy.ContainsUnexpandedParameterPack = !UnexpandedPacks.empty();
+  }
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:14661]: We probably need a refactor here to teach `ActOnFinishFunctionBody()` not to pop the LSI eventually. How about leaving it as an NFC?

**Comment by Endilll** [comment]
> I was waiting for the CI, but it seems Linux CI would take hours. However that shouldn't block the review I think, because Windows CI is green now.

FWIW Linux CI is recovering as we speak. I expect full recovery over the weekend.

File: clang/lib/Sema/TreeTransform.h (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/TreeTransform.h:14661]: I am not sure I understand why we would need to call `Sema::DiagnoseUnexpandedParameterPacks` here.

I think we should be able to diagnose all unexpanded parameter packs during the initial lambda parsing, so what gives?

Also, I am not sure what you mean by leaving it as an NFC.

Regardless, you have a copy of the LSI here, so what would stop you from pushing a new Lambda Scope and copying this LSI back into it? Something like:

```C++
  LambdaScopeInfo *LSI = getSema().PushLambdaScope();
  *LSI = LSICopy;
  Sema::FunctionScopeRAII FuncScopeCleanup(getSema());
```

This is obviously an ugly hack, but I don't think the solution is to simply teach `ActOnFinishFunctionBody` not to pop the function scope.

See this FIXME for a potentially more comprehensive fix: https://github.com/llvm/llvm-project/blob/77ac07444d32668d5826ef27c24180fb10425213/clang/lib/Sema/TreeTransform.h#L14648

Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h:14661]: That function attracts me because we seem to 1. always call it after collecting unexpanded packs; 2. also set the `LSI->ContainsUnexpandedParameterPack` flag there. However, this would probably be unnecessary if we called it during parsing.

> Also, I am not sure what you mean by leaving it as an NFC.

I was wondering if we could add an additional flag to `ActOnFinishFunctionBody()` so that we remove the scope info on the caller's own. (e.g. we could do that at the end of `TransformLambdaExpr`.) This way, we could also avoid copying LSI around the lines above. (I had intended to call `ContainsUnexpandedParameterPack()` afterward; again, even if the call is unnecessary, we still could benefit from the refactoring because we don't need to copy LSI.)

> but I don't think the solution is to simply teach ActOnFinishFunctionBody not to pop the function scope.

Can you say more? I think the FIXME is suggesting another way to avoid copying LSI, but that doesn't necessarily mean tweaking `ActOnFinishFunctionBody` is impossible?

File: clang/test/SemaTemplate/lambda-capture-pack.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/test/SemaTemplate/lambda-capture-pack.cpp:96]: The FIXME was added to the lines below.

File: clang/lib/Sema/TreeTransform.h (hunk 2 above)
Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h:14661]: Despite these, I have another concern on performance issue after some deliberation. This is actually a workaround given that we don't have any flags on a `Stmt` to tell whether it contains unexpanded expressions - what we do now leads to visiting the lambda body twice, which might cause some impact in lambda instantiation, if the body is large enough.

A compromise is, we remove this traversal in this patch and *leave it for future fixes*. (Sigh!)

**Comment by ilya-biryukov** [comment]
Just FYI, I wasn't aware of this PR and have ended up with an alternative approach to tracking the unexpanded packs in #99882. (Thanks @cor3ntin for pointing this out)

I'll let the reviewers decide if we should go with this change or mine, also happy to have some combination of the two (e.g. rebase mine on top of this one and still implement some of the refactorings there).

**Comment by zyn0217** [comment]
I think somehow we still need an extra bit in `Stmt` to carry over the unexpanded info because a body could contain other statements e.g. `DeclStmt` other than full expressions that could propagate up the unexpanded flag through calls to `ContainsUnexpandedParameterPack()`. For example, in one of my test cases:

```cpp
template <class T>
struct identity {
  using type = T;
};


template <class = void> void f() {
  []<class... Is>(Is...) {
    ([] {
      using T = identity<Is>::type;
    }(), ...);
  }(1, 2);
}

template void f(); // #instantiate-f
```

This patch resolves it by visiting the body twice (of course, it's suboptimal), however patch #99882 still crashes because that relies on the mechanism above, I believe.

**Comment by ilya-biryukov** [comment]
> This patch resolves it by visiting the body twice (of course, it's suboptimal), however patch #99882 still crashes because that relies on the mechanism above, I believe.

I have also observed it crashes, but I still think that in principle we don't need to traverse the body twice. If `DeclStmt` calls `DiagnoseUnexpandedPacks`, it will set the correct flag on the inner `LambdaScopeInfo`, which should later be available in the `LambdaExpr` itself, and can either be "consumed" by `CXXFoldExpr` (as in the example test case) or propagated into the outer `LamdaScopeInfo` from another call to `DiagnoseUnexpandedPacks`.
I believe that's what's already happening during parsing, but we seem to somehow miss setting this flag during substitution.

Are we crashing because we are missing calls to `DiagnoseUnexpandedPacks` during substitution or because we don't set up the `LambdaScopeInfo` during substitution correctly?

**Comment by ilya-biryukov** [comment]
Looking at the code a bit deeper, I think (not 100% sure) we're not calling `DiagnoseUnexpandedPacks` during substitution.
And we probably don't want the logic that produces diagnostics (substitutions cannot create new unexpanded packs in bad places), but we do need the logic to update the `LambdaScopeInfo::ContainsUnexpandedPacks` so we can avoid this extra traversal.

We might want to extract the function that only does the `LambdaScopeInfo::ContainsUnexpandedPacks` and call it instead of the fully-fledged `DiagnoseUnexpandedPacks`, and call it at the right places during substitutions. Tracking down all of them might be tricky, though.

Another alternative is to add a `ContainsUnexpandedPacks` flag to statements, but that is probably even harder than the former suggestion.

The third alternative is to keep the extra traversal for now. It's probably the simplest option.

**Comment by zyn0217** [comment]
> And we probably don't want the logic that produces diagnostics (substitutions cannot create new unexpanded packs in bad places), but we do need the logic to update the LambdaScopeInfo::ContainsUnexpandedPacks so we can avoid this extra traversal.

Cheers. Thanks for the advice. I added logic to TransformDeclStmt so that we can extract such a flag from TypeDecls. (Did I miss anything else? If any, we can probably leave them in the future as problems come up.)

The other challenging part is dealing with constraints. We need somehow to teach TransformCXXFoldExpr to recover the template arguments relative to the primary template so it can properly expand the fold expression. Anyway, I have made it work, though the approach is a bit tricky.

I will add more explanation to the codes tomorrow.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 3]
```diff
@@ -1394,7 +1395,22 @@ namespace {
...
+        if (LSI) {
+          MultiLevelTemplateArgumentList MLTAL =
+              getSema().getTemplateInstantiationArgs(
+                  LSI->CallOperator, /*DC=*/nullptr, /*Final=*/false,
+                  /*Innermost=*/std::nullopt, /*RelativeToPrimary=*/true,
+                  /*Pattern=*/nullptr, /*ForConstraintInstantiation=*/true);
+          return getSema().CheckParameterPacksForExpansion(
+              EllipsisLoc, PatternRange, Unexpanded, MLTAL, ShouldExpand,
+              RetainExpansion, NumExpansions);
+        }
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1411]: This is the most convoluted part in this patch. Basically, this targets for a situation where unexpanded packs appear in a trailing constraint. On the basis of our evaluation strategy, we need the complete template arguments, (which are typically relative to the primary template, as opposed to other instantiation algorithm where we usually need the template arguments relative to the parent specializations.) whereas we don't always have them at the time expanding a CXXFoldExpr.

For example, suppose we have
```cpp
template <class = void> void foo() {
 []<class... Is>() {
    ([]()
       requires (!C<Is>)
     {}(),
     ...);
  }.template operator()<char, int, float>();
}
``` 

We would only have one level template arguments, which is `<char, int, float>` when the inner fold expression gets expanded. Since we always preserve the constraint expressions until we evaluate them, we would thereafter have the inner lambda being unexpanded, which is wrong because, later we need to evaluate an expanded constraint when forming CallExprs.

So, one way is to teach the transformation to handle the constraints separately:
If we have only a constraint that contains unexpanded packs, we need to *expand* the expression because we don't actually need to use the constraint immediately. (in other words, the untransformed constraint shouldn't impact the expansion)

And vice versa: if we have combined constraints and other unexpanded packs, we just do the usual: we could hold off on the expansion until we hit the point where only unexpanded constraints are left, which boils down to the above case.

File: clang/lib/Sema/TreeTransform.h (hunk 2 above)
Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h]: The double traversal has now been removed from the patch, so I'll mark this resolved.

File: clang/lib/Sema/TreeTransform.h [hunk 4]
```diff
@@ -4006,6 +4007,37 @@ class TreeTransform {
...
+    CallOperator->setLexicalDeclContext(Class);
+    Decl *TemplateOrNonTemplateCallOperatorDecl =
+        CallOperator->getDescribedFunctionTemplate()
+            ? CallOperator->getDescribedFunctionTemplate()
+            : cast<Decl>(CallOperator);
+    // FIXME: Is this really the best choice? Keeping the lexical decl context
+    // set as CurContext seems more faithful to the source.
+    TemplateOrNonTemplateCallOperatorDecl->setLexicalDeclContext(Class);
+
+    getDerived().RebuildLambdaExprImpl(StartLoc, EndLoc, LSI);
```
Comment (cor3ntin) [inline clang/lib/Sema/TreeTransform.h:4026]: We don't seem to do anything interesting there

File: clang/lib/Sema/TreeTransform.h [hunk 5]
```diff
@@ -4006,6 +4007,37 @@ class TreeTransform {
...
+    CXXRecordDecl *Class = LSI->Lambda;
+    CXXMethodDecl *CallOperator = LSI->CallOperator;
+    CallOperator->setLexicalDeclContext(Class);
+    Decl *TemplateOrNonTemplateCallOperatorDecl =
+        CallOperator->getDescribedFunctionTemplate()
+            ? CallOperator->getDescribedFunctionTemplate()
+            : cast<Decl>(CallOperator);
+    // FIXME: Is this really the best choice? Keeping the lexical decl context
+    // set as CurContext seems more faithful to the source.
+    TemplateOrNonTemplateCallOperatorDecl->setLexicalDeclContext(Class);
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/TreeTransform.h:4024]: Why not just calling BuildLambdaExpr first?

File: clang/lib/Sema/TreeTransform.h (hunk 4 above)
Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h:4026]: @cor3ntin We call into `TemplateInstantiator::RebuildLambdaExprImpl(),` which substitutes for default arguments. I intend to set the flag after the substitution, as it's likely we could lose the unexpanded pack afterward.

Re "Why not just calling BuildLambdaExpr first?":
`BuildLambdaExpr()` would consume the `ContainsUnexpandedParameterPack` flag and use it as part of the dependency of the `LambdaExpr`. And what we used to do was to substitute for default arguments after `BuildLambdaExpr()`, which makes us miss the chance of altering the flag.

As a result, we would have such a call chain:
```
RebuildLambdaExpr() -> BuildLambdaExprImpl() (which actually performs the default argument substitution) -> BuildLambdaExpr()
```

File: clang/include/clang/Sema/Sema.h [hunk 6]
```diff
@@ -14037,6 +14037,15 @@ class Sema final : public SemaBase {
...
 
+  /// Collect the set of unexpanded parameter packs within the given
+  /// template argument.
+  ///
+  /// \param Arg The template argument that will be traversed to find
+  /// unexpanded parameter packs.
+  void collectUnexpandedParameterPacksForFoldExprs(
+      Expr *E, SmallVectorImpl<UnexpandedParameterPack> &Unexpanded,
+      SmallVectorImpl<UnexpandedParameterPack> &UnexpandedFromConstraints);
+
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:14048]: I'm using a different API to collect *unexpanded constaints* - they have to be handled individually because we don't transform the constaint expressions like what we have done for other temploids, so typically we don't have sufficient template arguments for them during the transform of CXXFoldExprs. (See my comment https://github.com/llvm/llvm-project/pull/86265#discussion_r1693246465)

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 7]
```diff
@@ -1673,14 +1690,12 @@ namespace {
           // RecoveryExpr that wraps the uninstantiated default argument so
           // that downstream diagnostics are omitted.
           ExprResult ErrorResult = SemaRef.CreateRecoveryExpr(
-              UninstExpr->getBeginLoc(), UninstExpr->getEndLoc(),
-              { UninstExpr }, UninstExpr->getType());
+              UninstExpr->getBeginLoc(), UninstExpr->getEndLoc(), {UninstExpr},
+              UninstExpr->getType());
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1692]: Yeah, an overkill of clang-format..

File: clang/lib/Sema/SemaTemplateVariadic.cpp [hunk 8]
```diff
@@ -136,6 +155,11 @@ namespace {
     /// do not contain unexpanded parameter packs.
     bool TraverseStmt(Stmt *S) {
       Expr *E = dyn_cast_or_null<Expr>(S);
+
+      llvm::SaveAndRestore _(InConstraint);
+      if (CurrentFunction && CurrentFunction->getTrailingRequiresClause() == S)
+        InConstraint = true;
+
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateVariadic.cpp:162]: Not yet. I'll try to make up one (what a dreadful situation if it gets combined with fold expressions!)

File: clang/include/clang/Sema/Sema.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/Sema/Sema.h:14048]: What makes fold expressions different from any other pack expansion?
For example,

```cpp
void f(auto...)
template <class = void> void foo() {
 []<class... Is>() {
    f([]() requires (!C<Is>) {}()...);
  }.template operator()<char, int, float>();
}
```cpp

Isn't that the same scenario?

(and please check the comment, it does look like an incorrect copy paste!)

[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:14048]: > (and please check the comment, it does look like an incorrect copy paste!)
Of course, I'll clean up all the comments (some of them are pretty unclear) until we have an agreement :)

[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:14048]: > For example,
> ...
> Isn't that the same scenario?

(Funny enough, I tried locally and found that we'd never build up a CXXFoldExpr for your example and inevitably... we crash 😅)

Regardless, I'll use my example to demonstrate:

```cpp
template <class = void> void f() {
  []<class... Is>() {
    ([]<class = void>()
       requires (!C<Is>)
     {}(),
     ...);
  }.template operator()<char, int, float>();
}
```

The scenario here is a little subtle. So previously, our expansion for CXXFoldExpr was like:
```cpp
// 1. collect unexpanded parameter packs from the "pattern" so admittedly we would have an unexpanded pack for the constraint
getSema().collectUnexpandedParameterPacks();

// 2. Check whether we should expand with template arguments.
getDerived().TryExpandParameterPacks();

if (!Expand) {
   // 3. Hold off. Rebuild an unexpanded CXXFoldExpr
} else {
   // 4. Otherwise, go on and expand.
}
```

When we want to expand the expression, we're actually in the context of instantiating the body of `foo()`. So we're now given one level of template arguments which is `<void>`.

This is insufficient for the expansion of the inner lambda `[]() requires (!C<Is>) {}`, right? Therefore, we would rebuild the whole pattern, as part of the transform of a callee (`template operator()<char, int, float>()`). Then, we rebuild the call expression and evaluate the constraints there.

However, we would fail to evaluate the constraint because we haven't yet expand the inner pattern, because we don't have sufficient template arguments.

So I take an approach to figure out if we have only unexpanded constraint expressions left. If that is the case, we don't use the current template arguments; instead, we collect them like what we do for constraints: so here we want
two levels of template arguments: `<char, int, float>` and `<void>`.

Using a dedicated version of `collectUnexpandedParameterPacks` could make such this possible as we don't have a way to tell where the unexpanded pack comes from otherwise.

[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/Sema/Sema.h:14048]: Let me rephrase. What is the difference between a fold expression and the expansion of parameter pack in a function call or other sort of expressions that could try to expand an outer pack?
Doing something specific for fold expression sounds very wrong

So, I have a concrete suggestion here... can we deal with constraints in a separate PR?
It might help us make progress better.
WDYT?

[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:14048]: > So, I have a concrete suggestion here... can we deal with constraints in a separate PR?
> It might help us make progress better.
> WDYT?

Great. I find I'm getting stuck with it now. Some other cases show up as I'm trying to figure out another approach, so I probably need extra effort here.
Moving forward without the constraints sounds good to me.

File: clang/lib/Sema/TreeTransform.h (hunk 4 above)
Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h:4025]: @cor3ntin Aha, I've figured out a way to simplify this `RebuildLambdaExpr()` thing: I think it's unnecessary to change the new method decl's lexical context to CurContext (we do so in parsing because we want to align the Scope nesting with the lexical nesting; however this is just what needs to be respected in parsing) and this way, we could just get rid of these setter calls.

File: clang/lib/Sema/SemaLambda.cpp [hunk 9]
```diff
@@ -1105,6 +1107,8 @@ void Sema::ActOnLambdaExpressionAfterIntroducer(LambdaIntroducer &Intro,
 
   CXXMethodDecl *Method = CreateLambdaCallOperator(Intro.Range, Class);
   LSI->CallOperator = Method;
+  // Temporarily set the lexical declaration context to the current
+  // context, so that the Scope stack matches the lexical nesting.
   Method->setLexicalDeclContext(CurContext);
```
Comment (zyn0217) [inline clang/lib/Sema/SemaLambda.cpp:1112]: I recovered this comment from https://reviews.llvm.org/D124351 because at least it tries to explain something - better than nothing that just makes the lambda parsing dimmer.

**Comment by cor3ntin** [comment]
I might be stupid but i still do not get why fold expressions are special, they should not be.
Can you add tests for 

```cpp
void f(auto...);
template <class = void> void foo() {
 []<class... Is>() {
    f([]() requires (!C<Is>) {}()...);
  }.template operator()<char, int, float>();
}
```

other interesting expansions might be 

```cpp
f<[]() requires (!C<Is>) {}()...>();
//
f({+[]() requires (!C<Is>) {}()});
//
[ ...fs = +[]() requires (!C<Is>) {}()]() {
  (fs(),...);
}
}

**Comment by zyn0217** [comment]
> I might be stupid but i still do not get why fold expressions are special, they should not be.

Sorry I was inaccurate suggesting fold expressions are special, it's actually *constraints involving pack expansions* who are special. (I admit inventing another `collectUnexpandedParameterPacks` overload for `CXXFoldExpr` is odd, probably insufficent for the solution because we seem to have more problems - as I observed a similar issue from your first example as well - regarding pack expansion in terms of the constraints on lambdas.)

> 
> ```cpp
> void f(auto...);
> template <class = void> void foo() {
> []<class... Is>() {
>    f([]() requires (!C<Is>) {}()...);
>  }.template operator()<char, int, float>();
>}
> ```

This is awkward: no compiler currently compiles it. (https://gcc.godbolt.org/z/rce3rh7jK) And spuriously, both gcc and clang think that there are no unexpanded parameter packs for expansion. 

Regardless of whether this is conforming, the diagnostic here is simple to explain: we didn't preserve the `ContainsUnexpandedParameterPack` flag while transforming the LambdaExpr, so as an intuitive solution, we could just retain the flag from `TransformLambdaExpr`:

(Though I didn't add the following to the patch yet, it doesn't solve the problem and instead would cause a crash)

```cpp
Expr *TrailingRequires = E->getCallOperator()->getTrailingRequiresClause();
  if (TrailingRequires)
    LSI->ContainsUnexpandedParameterPack |=
        TrailingRequires->containsUnexpandedParameterPack();
```

We still fail to evaluate the constraint because it ends up being dependent even with proper template arguments. This is because the expression is not expanded anywhere before evaluating the constraint, which is one step when we forming up a CallExpr.

The situation could be slightly different (or rather, better?) if a fold expression gets involved. We would still have a chance to expand the fold expression into an expanded but unsubstituted state. So we can make them into the constraint evaluation and substitute arguments there, and get a correct result. So this is why it's convoluted: we probably miss out on some passes for constraint packs: Maybe we need to expand them somewhere before evaluation, but I'm not completely clear.

> ```cpp
> f<[]() requires (!C<Is>) {}()...>();
> //
> f({+[]() requires (!C<Is>) {}()...});
> // I am truly sorry.
> [ ...fs = +[]() requires (!C<Is>) {}()]() {
>  (fs(),...);
> }
> ```

(I promise I won't forget them but let's consider them when we get around to the constraints in the next patch. :)

**Comment by cor3ntin** [comment]
Okay so we seem to agree. Can you go over the pr and make sure "fold expression" says "pack expansion" everywhere that it should (release note, comments, function names) ? Thanks!

File: clang/test/SemaCXX/fold_lambda_with_variadics.cpp [hunk 10]
```diff
@@ -0,0 +1,181 @@
...
+  }();
+
+  [](auto ...x) {
+    ([&](auto ...y) {
+      ([x..., y] { }(), ...);
+    })(1);
+  }(2, 'b');
+
+#if 0
+  // https://github.com/llvm/llvm-project/issues/18873
```
Comment (cor3ntin) [inline clang/test/SemaCXX/fold_lambda_with_variadics.cpp:61]:
```suggestion
  // FIXME: https://github.com/llvm/llvm-project/issues/18873
```

**Review by cor3ntin — APPROVED** [review]
LGTM (modulo nit)
We should probably backport that

**Comment by zyn0217** [comment]
Thanks for the review! I've just merged it.

> We should probably backport that

SGTM but given that this bug persists in so many versions, I think it is also fine to leave the fix just on trunk - especially since this is actually a partial fix.

We could issue a backport to 19 after we have addressed remaining FIXMEs i.e. bugs on attributes/constraints/captures, if I can catch up the release schedule. WDYT?

**Comment by cor3ntin** [comment]
r3 is in 2 weeks and we have to be more conservatives in our backports, so it really depends on how long it took you and @ilya-biryukov to address these issues and the complexity of the patches.

In particular, I would be surprised if the attribute case impacts many people.

**Comment by ilya-biryukov** [comment]
> r3 is in 2 weeks and we have to be more conservatives in our backports, so it really depends on how long it took you and @ilya-biryukov to address these issues and the complexity of the patches.
> 
> In particular, I would be surprised if the attribute case impacts many people.

To be clear, I don't have a real-world use-case for attributes. The only reason I have added it in my patch is because there was a test in Clang that started failing with my approach (because it started looking at thing structurally even on the parsing path, as discussed earlier).
I suspect we could live with that for a long time, although fixing that eventually is a good idea. (And is still in my TODO list, just slipped a little)
