### PR TITLE
[clang] Implemeent consteval for captured structured bindings.

### LINKED ISSUE #134897: [clang++] Can not capture member of structured binding to lambda in constant evaluation.
Clang rejects following code while gcc compiles it.

https://godbolt.org/z/E3TcTq1hx

```cpp
struct bar {
    int x;
};

consteval int foo() {
    const auto [a] = bar{};

    return [=] {
        return a;
    }();
}

int main() {
    return foo();
}
```

Error message from clang:

```
<source>:14:12: error: call to consteval function 'foo' is not a constant expression
   14 |     return foo();
      |            ^
<source>:9:16: note: read of non-constexpr variable '[a]' is not allowed in a constant expression
    9 |         return a;
      |                ^
<source>:8:12: note: in call to '[=] {
    return a;
}.operator()()'
    8 |     return [=] {
      |            ^~~~~
    9 |         return a;
      |         ~~~~~~~~~
   10 |     }();
      |     ~~~
<source>:14:12: note: in call to 'foo()'
   14 |     return foo();
      |            ^~~~~
<source>:6:16: note: declared here
    6 |     const auto [a] = bar{};
      |                ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by efriedma-quic**
127bf44385424891eb04cff8e52d3f157fc2cb7c implemented most of the infrastructure for capturing structured bindings in lambdas, but missed one piece: constant evaluation of such lambdas. Refactor the code to handle this case.

Fixes #145956. Fixes #134897.

### CODE REVIEW

File: clang/lib/AST/ExprConstant.cpp [hunk 1]
```diff
@@ -8952,38 +8952,39 @@ static bool EvaluateLValue(const Expr *E, LValue &Result, EvalInfo &Info,
 
 bool LValueExprEvaluator::VisitDeclRefExpr(const DeclRefExpr *E) {
   const NamedDecl *D = E->getDecl();
```
Comment (cor3ntin) [inline clang/lib/AST/ExprConstant.cpp]:
```suggestion
  const ValueDecl *D = E->getDecl();
```

That way we can avoid casts further down

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks!
