### PR TITLE
[clang-tidy]fix incorrect fix-it for the string contains a user-defined suffix

### LINKED ISSUE #97243: clang-tidy: modernize-raw-string-literal wrongly removes suffix, e.g. `s` (`std::string_literals`)
Prepare `/tmp/a.cpp`:

```cpp
#include <string>
int main() {
  using namespace std::literals::string_literals;
  auto s = "id=\"0\""s;
}
```

and `/tmp/compile_commands.json`

```json
[ { "directory": "/tmp", "command": "clang++ -std=c++14 -c -o a.o a.cpp", "file": "a.cpp", "output": "a.o" } ]
```

```ShellSession
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 17.0.6
  Optimized build.
$ clang-tidy --checks=modernize-raw-string-literal --fix a.cpp
1 warning generated.
a.cpp:4:12: warning: escaped string literal can be written as a raw string literal [modernize-raw-string-literal]
    4 |   auto s = "id=\"0\""s;
      |            ^~~~~~~~~~~
      |            R"(id="0")"
a.cpp:4:12: note: FIX-IT applied suggested code changes
clang-tidy applied 1 of 1 suggested fixes.
```

gives

```cpp
  auto s = R"(id="0")";
```

which must be

```cpp
  auto s = R"(id="0")"s;
```

<https://godbolt.org/z/Pf41qKzYh>

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixed: #97243

### CODE REVIEW

File: clang-tools-extra/clang-tidy/modernize/RawStringLiteralCheck.cpp [hunk 1]
```diff
@@ -136,13 +137,26 @@ void RawStringLiteralCheck::check(const MatchFinder::MatchResult &Result) {
...
+  const SourceManager &SM = *Result.SourceManager;
+  const CharSourceRange TokenRange =
+      CharSourceRange::getTokenRange(Literal->getSourceRange());
+  Token T;
+  if (Lexer::getRawToken(Literal->getBeginLoc(), T, SM, getLangOpts()))
+    return;
+  const CharSourceRange CharRange =
+      Lexer::makeFileCharRange(TokenRange, SM, getLangOpts());
+  if (T.hasUDSuffix()) {
+    StringRef Text = Lexer::getSourceText(CharRange, SM, getLangOpts());
```
Comment (EugeneZelenko) [inline clang-tools-extra/clang-tidy/modernize/RawStringLiteralCheck.cpp:153]: Should be `const`.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -317,6 +317,10 @@ Changes in existing checks
   a false positive when only an implicit conversion happened inside an
   initializer list.
 
+- Improved :doc:`modernize-raw-string-literal
+  <clang-tidy/checks/modernize/raw-string-literal>` check to fix incorrect auto
+  fix when the string contains a user-defined suffix.
```
Comment (EugeneZelenko) [inline clang-tools-extra/docs/ReleaseNotes.rst:322]: `fix-it` instead of `auto fix`.

**Comment by HerrCai0907** [comment]
* **#122909** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/122909?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#122901** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/122901?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/122901?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
