### PR TITLE
[Flang][OpenMP] Consider renames when processing reduction intrinsics

### LINKED ISSUE #68654: [Flang][OpenMP] Compilation error when local-name of rename-list written in USE statement is specified as intrinsic_procedure_name in REDUCTION clause
```
Version of flang-new : 18.0.0(cc627828f5176c6d75a25f1756d387d18539c1fb)
```

If `local-name` (ren) of `rename-list` written in `USE` statement is specified as `intrinsic_procedure_name` in `REDUCTION` clause, a compilation error occurs.  
If `intrinsic_procedure_name` is changed to max instead of ren, a compilation terminates normally.

The following are the test program, Flang-new, Gfortran and ifort compilation result.

snggz888_.f90:
```fortran
module m1
  intrinsic max
end module m1
program main
  use m1, ren=>max
  n=0
!$omp parallel do reduction(ren:n)
  do i=1,100
     n=max(n,i)
  end do
  if (n/=100) print *,101
  print *,'pass'
end program main
```

```
$ flang-new snggz888_.f90 -fopenmp
error: Semantic errors in snggz888_.f90
./snggz888_.f90:7:19: error: Invalid reduction identifier in REDUCTION clause.
  !$omp parallel do reduction(ren:n)
                    ^^^^^^^^^^^^^^^^
$
```

```
$ gfortran snggz888_.f90 -fopenmp
$
```

```
$ ifort snggz888_.f90 -qopenmp
 pass
$
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Fixes #68654

Depends on https://github.com/llvm/llvm-project/pull/70790

### CODE REVIEW

**Comment by NimishMishra** [comment]
Similar issue? https://github.com/llvm/llvm-project/issues/67332

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -480,21 +480,28 @@ class OmpAttributeVisitor : DirectiveAttributeVisitor<llvm::omp::Directive> {
...
+      name->symbol = &newSymbol;
+    };
     if (const auto *procD{parser::Unwrap<parser::ProcedureDesignator>(opr.u)}) {
       if (const auto *name{parser::Unwrap<parser::Name>(procD->u)}) {
         if (!name->symbol) {
-          const auto namePair{currScope().try_emplace(
-              name->source, Attrs{}, ProcEntityDetails{})};
-          auto &symbol{*namePair.first->second};
-          name->symbol = &symbol;
-          name->symbol->set(Symbol::Flag::OmpReduction);
```
Comment (DavidTruby) [inline flang/lib/Semantics/resolve-directives.cpp:490]: Should the new symbol above also be set as an OmpReduction symbol? It doesn't look like this is getting set anymore

File: flang/lib/Semantics/resolve-directives.cpp [hunk 2]
```diff
@@ -480,21 +480,28 @@ class OmpAttributeVisitor : DirectiveAttributeVisitor<llvm::omp::Directive> {
   bool Pre(const parser::OmpClause::Reduction &x) {
     const parser::OmpReductionOperator &opr{
         std::get<parser::OmpReductionOperator>(x.v.t)};
+    auto createDummyProcSymbol = [&](const parser::Name *name) {
+      // If name resolution failed, create a dummy symbol
+      const auto namePair{
+          currScope().try_emplace(name->source, Attrs{}, ProcEntityDetails{})};
+      auto &newSymbol{*namePair.first->second};
+      name->symbol = &newSymbol;
```
Comment (DavidTruby) [inline flang/lib/Semantics/resolve-directives.cpp:488]: nit: either don't create a new variable here, or just leave it as a pointer rather than dereferencing and then referencing it?
E.g. 
```
auto *newSymbol{namePair.first->second};
name->symbol = newSymbol;
```
I was a little confused by it turning into a reference and then back into a pointer.

Comment (kiranchandramohan) [reply flang/lib/Semantics/resolve-directives.cpp:488]: The change here is only moving code. We can fix this in a follow-up patch if required.
Also, note that `namePair.first->second`  is of type `Fortran::common::Reference<Fortran::semantics::Symbol>` and hence the code you provided will not directly work.

File: flang/lib/Semantics/resolve-directives.cpp (hunk 1 above)
Comment (DavidTruby) [reply flang/lib/Semantics/resolve-directives.cpp:490]: Nit: would it be worth adding the OmpReduction flag on it anyway, since it _is_ a reduction variable and we might need it later? Just so we aren't confused later. It does look like it was getting set before this change?

**Review by DavidTruby — APPROVED** [review]
LGTM, you can decide about the OmpReduction flag!
