### PR TITLE
[clang-format] Correctly annotate user-defined conversion functions

### LINKED ISSUE #130894: [clang-format] `BreakAfterAttributes` doesn't work for user-defined conversion functions
https://godbolt.org/z/a5GGK51f9
```cpp
struct awoo {
    [[nodiscard]] operator bool();
    [[nodiscard]] bool f();
};
```
Given `-style="{BreakAfterAttributes: Always}"`, this code is formatted like:
```cpp
struct awoo {
  [[nodiscard]] operator bool();
  [[nodiscard]]
  bool f();
};
```

### PR DESCRIPTION
**Pull request by owenca**
Also fix/delete existing invalid/redundant test cases.

Fix #130894

### CODE REVIEW

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -1639,6 +1639,25 @@ class AnnotatingParser {
...
+        FormatToken *LParen;
+        if (CurrentToken->startsSequence(tok::kw_decltype, tok::l_paren,
+                                         tok::kw_auto, tok::r_paren)) {
+          LParen = CurrentToken->Next->Next->Next->Next;
+        } else {
+          for (LParen = CurrentToken->Next;
+               LParen && LParen->isNot(tok::l_paren); LParen = LParen->Next) {
+          }
+        }
+        if (LParen && LParen->startsSequence(tok::l_paren, tok::r_paren)) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/TokenAnnotator.cpp:1655]: This does not match on `operator Foo(void)`.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -3856,6 +3856,59 @@ TEST_F(TokenAnnotatorTest, AfterPPDirective) {
...
+  Tokens = annotate("operator decltype(auto)() const;");
+  ASSERT_EQ(Tokens.size(), 10u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_operator, TT_FunctionDeclarationName);
+  EXPECT_TOKEN(Tokens[2], tok::l_paren, TT_TypeDeclarationParen);
+  EXPECT_TOKEN(Tokens[4], tok::r_paren, TT_TypeDeclarationParen);
+  EXPECT_TOKEN(Tokens[5], tok::l_paren, TT_FunctionDeclarationLParen);
+  EXPECT_TOKEN(Tokens[7], tok::kw_const, TT_TrailingAnnotation);
+
+  auto Style = getLLVMStyle();
+  Style.TypeNames.push_back("Foo");
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:3893]: So the type for `operator Type()` needs to be in `TypeNames`? I think we can detect that without that constraint, and that would be much nicer.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/TokenAnnotator.cpp [hunk 3]
```diff
@@ -1639,6 +1639,31 @@ class AnnotatingParser {
     case tok::kw_operator:
       if (Style.isProto())
         break;
+      // Handle C++ user-defined conversion function.
+      if (IsCpp && CurrentToken) {
+        const auto *Info = CurrentToken->Tok.getIdentifierInfo();
+        // What follows Tok is an identifier or a non-operator keyword.
+        if (Info && !(Info->isCPlusPlusOperatorKeyword() ||
+                      CurrentToken->isPlacementOperator() ||
+                      CurrentToken->is(tok::kw_co_await))) {
```
Comment (owenca) [inline clang/lib/Format/TokenAnnotator.cpp:1648]:
```suggestion
        if (Info && !(CurrentToken->isPlacementOperator() ||
                      CurrentToken->is(tok::kw_co_await) ||
                      Info->isCPlusPlusOperatorKeyword())) {
```
