### PR TITLE
[analyzer] Fix FP for cplusplus.placement new #149240

### LINKED ISSUE #149240: possible false-positive clang-analyzer-cplusplus.PlacementNew
```c++
#include <new>

int main() {
    void *buf = ::operator new(sizeof(int)*2);
    int * placement_int = new (buf) int[2];
    placement_int[0] = 42;
    ::operator delete(buf);
}
```

clang-tidy produces

```
<source>:5:27: warning: Storage provided to placement new is only 8 bytes, whereas the allocated array type requires more space for internal needs [clang-analyzer-cplusplus.PlacementNew]
    5 |     int * placement_int = new (buf) int[2];
      |                           ^~~~~~~~~~~~~~~~
<source>:4:5: note: 'buf' initialized here
    4 |     void *buf = ::operator new(sizeof(int)*2);
      |     ^~~~~~~~~
<source>:5:27: note: Storage provided to placement new is only 8 bytes, whereas the allocated array type requires more space for internal needs
    5 |     int * placement_int = new (buf) int[2];
      |                           ^~~~~~~~~~~~~~~~
```

Reproduced in https://godbolt.org/z/MYGc5qfn6 using clang version 22.0.0git (https://github.com/llvm/llvm-project.git 82d7405b3bb911c86d0b07c8a6bec5044acbdf66)

I think this warning is incorrect, as described at https://stackoverflow.com/questions/8720425/array-placement-new-requires-unspecified-overhead-in-the-buffer and in https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2382 or https://cplusplus.github.io/CWG/issues/2382.html. This is a non-allocating placement new, in which case (per that defect resolution) no additional space may be requested.

So I think these "array overhead" warnings are *always* false-positives. However, they do seem to have been added in May 2020:
https://github.com/llvm/llvm-project/blame/1c541aa9f9a2453324724bfb9d661bc672778d10/clang/lib/StaticAnalyzer/Checkers/CheckPlacementNew.cpp#L120-L134 shows it came in with https://github.com/llvm/llvm-project/commit/7c3768495e8c1599dc30986f7bd47d5e91f303f2 and https://reviews.llvm.org/D76996
That dates this first being added to clang **after** that DR had been reported, voted on, and the resolution accepted into CD5. So I don't think they are simply outdated; maybe the author/reviewers were unaware of the defect report?

Or maybe I'm misunderstanding something and this really is buggy code - "I'm wrong" is certainly possible too :-)

### PR DESCRIPTION
**Pull request by Aethezz**
Fix false positive where warnings were asserted for placement new even when no additional space is requested

The PlacementNewChecker incorrectly triggered warnings when the storage provided matched or exceeded the allocated type size, causing false positives. Now the warning triggers only when the provided storage is strictly less than the required size.

Add test cases covering exact size, undersize, and oversize scenarios to validate the fix.

Fixes #149240

### CODE REVIEW

**Review by NagyDonat — COMMENTED** [review]
The code that you're removing is not an accidental bug, but an intentional (although perhaps overzealous) feature that tries to warn about the fact that placement new for an array type may allocate an unspecified amount of overhead (extra memory) for internal needs.

According to a quick search this was a significant issue especially in Visual Studio (where it could cause memory corruption), but very recent versions of the standard (C++20 and later) declare that _placement_ new of arrays must not introduce an overhead: https://stackoverflow.com/a/75418614

To improve the usefulness of this checker, I weakly support this change, but I would also like to see a second opinion from @steakhal @Xazax-hun @haoNoQ or other contributors.

**Comment by steakhal** [comment]
> The code that you're removing is not an accidental bug, but an intentional (although perhaps overzealous) feature that tries to warn about the fact that placement new for an array type may allocate an unspecified amount of overhead (extra memory) for internal needs.
> 
> According to a quick search this was a significant issue especially in Visual Studio (where it could cause memory corruption), but very recent versions of the standard (C++20 and later) declare that _placement_ new of arrays must not introduce an overhead: https://stackoverflow.com/a/75418614
> 
> To improve the usefulness of this checker, I weakly support this change, but I would also like to see a second opinion from @steakhal @Xazax-hun @haoNoQ or other contributors.

I never understood the reasons of having metadata for placement-new. Certainly on linux it was not the case, but I'm skeptical if it was on any other platforms such as Windows. (prove me wrong). But unless it's proved that such a platform exists under some configuration, I see no benefit of having this warning. And even then, we should at least make this diagnostic conditional to only have it for the platforms where it's actually a thing.

**Comment by NagyDonat** [comment]
> I never understood the reasons of having metadata for placement-new.

I don't think that there is any real reason for it, but I guess that some compilers reused code from the code of non-placement new.

> Certainly on linux it was not the case, but I'm skeptical if it was on any other platforms such as Windows. (prove me wrong).

This (admittedly 16 years old) stackoverflow post claims that (at that time) Visual Studio added four bytes of overhead to an array allocated with placement new:
https://stackoverflow.com/questions/15254/can-placement-new-for-arrays-be-used-in-a-portable-way/75418614#75418614

**Comment by steakhal** [comment]
> > I never understood the reasons of having metadata for placement-new.
> 
> I don't think that there is any real reason for it, but I guess that some compilers reused code from the code of non-placement new.
> 
> > Certainly on linux it was not the case, but I'm skeptical if it was on any other platforms such as Windows. (prove me wrong).
> 
> This (admittedly 16 years old) stackoverflow post claims that (at that time) Visual Studio added four bytes of overhead to an array allocated with placement new: https://stackoverflow.com/questions/15254/can-placement-new-for-arrays-be-used-in-a-portable-way/75418614#75418614

Now I see. The link is wrong. It does not link to what you think, but there was a comment that suggests what you said.

[Here](https://godbolt.org/z/8cWMMoWGr) is a slightly modified variant of that code, on some different msvc and clang 19.
I didn't check the standard, but as I recall, one is only allowed to use the pointer returned by the placement new to manipulate the object, but then when we call `delete[]` we must us the pointer we had from `operator new[]`.
Despite the pointers `pA` and `pBuffer` are equal, deleting the buffer using `pA` codegens to a segfault using clang, but when deleting via the `pBuffer` it works. Seeing this, we definitely have some UB in the example that clang sometimes exploits.
And if we have UB, of course MSVC have freedom to do whatever it wants.

**Comment by Aethezz** [comment]
Hello, this is my first contribution and I am unsure of the process. I have tried fixing the formatting issues and failing test case from other unit tests. However, after viewing your discussions, is this still a valid issue?

File: clang/test/SemaCXX/placement-new-bounds.cpp [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// RUN: %clang -fsyntax-only -Xclang -analyze -Xclang -analyzer-checker=cplusplus.PlacementNew -Xclang -verify -std=c++17 %s
+
+#include <new>
```
Comment (NagyDonat) [inline clang/test/SemaCXX/placement-new-bounds.cpp:3]: These tests do not include real system headers (if I understand correctly, this is because the exact content of the system header could vary between different environments). Tests that validate the analysis of language/library features that are declared in system headers usually include "system header simulator" header files that are known to be consistent between environments and declare the relevant parts of the STL.

For example `placement-new.cpp` (the other test file that you edit) uses `"Inputs/system-header-simulator-cxx.h"`, I'd guess that it would be the good choice for this file as well.

File: clang/test/SemaCXX/placement-new-bounds.cpp [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+    placement_int[0] = 42;
+    ::operator delete(buf);
+}
+
+void test_oversize() {
+    void *buf = ::operator new(sizeof(int)*4);
+    int *placement_int = new (buf) int[2]; // no-warning
+    placement_int[0] = 42;
+    ::operator delete(buf);
+}
```
Comment (NagyDonat) [inline clang/test/SemaCXX/placement-new-bounds.cpp:24]: What is the reason for adding these tests (in addition to the tests that already exist in `placement-new.cpp`)? As far as I see there is no significant difference between these and the tests that already exist in `placement-new.cpp`.

Also note that the tests of the static analyzer are always placed in the `clang/test/Analysis` directory and not the `clang/test/SemaCXX` directory.

**Review by NagyDonat — COMMENTED** [review]
I added some technical remarks in inline comments (including two comments that I accidentally posted separately, before this review).

If those are handled, I'm leaning towards merging this PR, because it I agree that these warnings (where the array would fit into the buffer where it's initialized, but the overhead of the array new can could technically cause issues) may be unwanted and confusing.

@steakhal What do you think, which would be the better: merging this PR or preserving the counter-intuitive bug reports that warn about potential unusual behavior of array placement new?

File: clang/lib/StaticAnalyzer/Checkers/CheckPlacementNew.cpp [hunk 3]
```diff
@@ -111,32 +111,14 @@ bool PlacementNewChecker::checkPlaceCapacityIsSufficient(
...
-            "Storage provided to placement new is only {0} bytes, "
-            "whereas the allocated array type requires more space for "
-            "internal needs",
-            SizeOfPlaceCI->getValue()));
-      else
-        Msg = std::string(llvm::formatv(
-            "Storage provided to placement new is only {0} bytes, "
-            "whereas the allocated type requires {1} bytes",
-            SizeOfPlaceCI->getValue(), SizeOfTargetCI->getValue()));
+      Msg = std::string(
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/CheckPlacementNew.cpp:118]: You could at this point just initialize `Msg` with this.
You also should not need to call the `std::string` explicit conversion operator.

File: clang/test/SemaCXX/placement-new-bounds.cpp [hunk 4]
```diff
@@ -0,0 +1,24 @@
+// RUN: %clang -fsyntax-only -Xclang -analyze -Xclang -analyzer-checker=cplusplus.PlacementNew -Xclang -verify -std=c++17 %s
```
Comment (steakhal) [inline clang/test/SemaCXX/placement-new-bounds.cpp:1]:
```suggestion
// RUN: %clang_analyze_cc1 -analyzer-checker=core,cplusplus.PlacementNew -verify -std=c++17 %s

```

File: clang/test/SemaCXX/placement-new-bounds.cpp (hunk 2 above)
Comment (steakhal) [reply clang/test/SemaCXX/placement-new-bounds.cpp:24]: Yes, we should just drop this.

**Review by steakhal — CHANGES_REQUESTED** [review]
> @steakhal What do you think, which would be the better: merging this PR or preserving the counter-intuitive bug reports that warn about potential unusual behavior of array placement new?

The PR looks good. I don't think we would ever want the diagnostics we are about to drop in this PR.

**Review by steakhal — CHANGES_REQUESTED** [review]
I looked at the content of the PR now, and I suggested a couple of places to improve.
Overall, I'm very happy with this change.
Thank you everyone for sticking around and putting the energy into thins one.

**Review by steakhal — APPROVED** [review]
