### PR TITLE
[Clang] Correct the DeclRefExpr's Type after the initializer gets instantiated

### LINKED ISSUE #79750: Arrays of variable templates cannot deduce their lengths from pack expansion in the initializer
```cpp
#include <iostream>
#include <type_traits>

template<std::size_t...values>
constexpr std::size_t array[]{ values... };

int main() {
    std::cout << std::is_same_v<decltype(::array<1, 2, 3, 4, 5>),  const std::size_t[]>;
}
```

[Output](https://godbolt.org/z/E8jTW1GsW):

```
1
```
Both gcc and clang have this result, but this is obviously not true, msvc outputs **0**.

gcc and clang consider `array<1, 2, 3, 4, 5>` to be the same type as `const std::size_t[]`.

---

msvc will only output 1 when faced with the following code.

```cpp
#include <iostream>
#include <type_traits>

template<std::size_t...values>
constexpr std::size_t array[]{ values... };

int main() {
    std::cout << std::is_same_v<decltype(::array<1, 2, 3, 4, 5>), const std::size_t[5]>;
}
```

msvc considers `array<1, 2, 3, 4, 5>` and `const std::size_t[5]` to be of the same type.

- ***I think msvc is right***.

### LINKED ISSUE #113936: C++ compile-time array bounds unsuccessfully inferred from template expansions
https://godbolt.org
```cpp
template <int... VALUES>
struct C {
    static constexpr int VALUEARRAY[] = {VALUES...};
};

static_assert(C<0,1,2,3,4>::VALUEARRAY[4] == 4);
```
clang needs the hint of `sizeof...(VALUES)` to build correctly, while GCC and MSVC compile without error.

### LINKED ISSUE #133047: [Clang] template with NTTP param is static array element failed to compile
it's code from CV-cuda, migrate to clang

```c++
#include <cstddef>
#include <stdint.h>
#include <utility>
#include <tuple>
template<bool Active = true, typename T>
constexpr inline bool IsOutside(T c, T s)
{
    if constexpr (Active)
    {
        return (c < 0) || (c >= s);
    }
    return false;
}


template<bool... ActiveDimensions>
class BoolDimension
{
public:
    static constexpr int  kNumDimensions = sizeof...(ActiveDimensions);
    struct ActiveMap
    {
        bool from[kNumDimensions];

        constexpr ActiveMap()
            : from()
        {
            int j = 0;
            for (int i = 0; i < kNumDimensions; ++i)
            {
                if (kActiveDimensions[i])
                {
                    from[i] = j++;
                }
            }
        }
    };

    static constexpr ActiveMap kMap{};
    static constexpr bool kActiveDimensions[]  = {ActiveDimensions...};
    static constexpr int  kNumActiveDimensions = ((ActiveDimensions ? 1 : 0) + ...);
    int64_t          m_tensorShape[kNumActiveDimensions] = {0};

    template<typename... Args, std::size_t... Is>
    inline  bool check(std::index_sequence<Is...>, Args... c) const
    {
        //static constexpr const  auto kDimensions = std::make_tuple(ActiveDimensions...);
        //if ((IsOutside<std::get<Is>(kDimensions)>(c,false) || ...))
        if ((IsOutside<kActiveDimensions[Is]>(c,false) || ...))
        {
            return true;
        }
        return false;
    }
};

int main() {
    BoolDimension<true, true, false, false> d;
    constexpr auto Is = std::make_index_sequence<1>{};
    return d.check(Is, false);
}
```

in check function, IsOutside not accept array element, change to tuple with get is ok

https://godbolt.org/z/n1K5vGcrE

### PR DESCRIPTION
**Pull request by zyn0217**
The instantiation of a VarDecl's initializer might be deferred until the variable is actually used. However, we were still building the DeclRefExpr with a type that could later be changed by the initializer's instantiation, which is incorrect when incomplete arrays are involved.

Fixes #79750
Fixes #113936
Fixes #133047

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -19849,11 +19849,14 @@ static void DoMarkVarDeclReferenced(
...
-        if (auto *DRE = dyn_cast_or_null<DeclRefExpr>(E))
+        if (auto *DRE = dyn_cast_or_null<DeclRefExpr>(E)) {
+          // Re-set the member to trigger a recomputation of the dependence bits
+          // for the expression.
           DRE->setDecl(DRE->getDecl());
-        else if (auto *ME = dyn_cast_or_null<MemberExpr>(E))
+          if (SemaRef.Context.getAsIncompleteArrayType(DRE->getType()) &&
+              !SemaRef.Context.getAsIncompleteArrayType(Var->getType()))
+            DRE->setType(Var->getType());
+        } else if (auto *ME = dyn_cast_or_null<MemberExpr>(E))
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExpr.cpp:19859]: Should we do it unconditionally? are there other cases?

Comment (zyn0217) [reply clang/lib/Sema/SemaExpr.cpp:19859]: There are examples where the type of Var is a reference type that couldn't get bound to an expression

```cpp
template<decltype(auto) v> void f() {
}

struct X {};

template<auto x> auto &TempParamObject = x;
template void f<TempParamObject<X{}>>();
```

The original type of DeclRefExpr is calculated by `BuildDeclarationNameExpr`, which is handled by a large switch-cases that I don't think it's reasonable to recompute the type through that logic at this point - It's rare (in fact, the IncompleteArray case is the only one I could think of) that substituting the initializer could change the type of the VarDecl - otherwise, we would have the type of Decl completed before the call to BuildDeclarationNameExpr(), which ensures the correctness of the DeclRefExpr.

Comment (cor3ntin) [reply clang/lib/Sema/SemaExpr.cpp:19859]: Let's just add a comment. I suspect this is not the right place for this code (it feels too late), but i do not have a better suggestion.

Comment (zyn0217) [reply clang/lib/Sema/SemaExpr.cpp:19859]: > it feels too late

Hmm. This is the last place where we know the DeclRefExpr that needs an update, (The instantiation doesn't care the DeclRefExpr) and the instantiation happens right before these lines

Comment (cor3ntin) [reply clang/lib/Sema/SemaExpr.cpp:19865]: So, I was looking at where `InstantiateVariableDefinition` is used.
And I found out we have a `completeExprArrayBound` function - I suspect we might want to use that. Can you look into it?

Comment (zyn0217) [reply clang/lib/Sema/SemaExpr.cpp]: > And I found out we have a completeExprArrayBound function - I suspect we might want to use that. Can you look into it?

I'm surprised we have such a function, thanks! I made it call `getCompletedType()` which seems to target to the IncompleteArrayTypes and calls `completeExprArrayBound()` if possible

**Review by cor3ntin — APPROVED** [review]
Thanks

File: clang/test/SemaCXX/cxx1y-variable-templates_top_level.cpp [hunk 2]
```diff
@@ -467,3 +467,29 @@ namespace VexingParse {
   template <typename> int var; // expected-note {{declared here}}
   int x(var); // expected-error {{use of variable template 'var' requires template arguments}}
 }
+
+#ifndef PRECXX11
+
+namespace GH79750 {
```
Comment (shafik) [inline clang/test/SemaCXX/cxx1y-variable-templates_top_level.cpp:473]: I am assuming you checked by hand that https://github.com/llvm/llvm-project/issues/133047 passes now? It might have been helpful to ask for a reduction to ensure we had fuller test coverage.

Comment (zyn0217) [reply clang/test/SemaCXX/cxx1y-variable-templates_top_level.cpp:473]: I did test it locally :) The reduced version of it (I didn't post it) is similar to #113936 so I don't add it to the test coverage.
