### PR TITLE
[X86_64] Fix empty field error in vaarg of C++.

### LINKED ISSUE #79790: [x86_64] va_arg will get wrong result in c++
demo.cpp
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

struct S271 { struct{}a; long long b; } ;
struct S271 s271;

void check271va (int z, ...) {
    struct S271 arg, *p;
    va_list ap;
    __builtin_va_start(ap, z);
    p = &s271;
    arg = __builtin_va_arg(ap, struct S271);
    if (p->b != arg.b) {
        printf("Fail!\n");
        printf("p->b:%lld , arg.b:%lld\n", p->b, arg.b);
    }
    __builtin_va_end(ap);
}

int main (void) {
    s271.b = 1;
    check271va (1, s271);
}
```
wrong output (clang) :
```
% clang++ demo.cpp
% ./a.out
Fail!
p->b:1 , arg.b:140726027523432
```
https://godbolt.org/z/7v6KEWGWT

### LINKED ISSUE #86371: [X86_64] va_arg with SSE type get error
demo.c
```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

struct S271 { union{}a; double b;} ;
struct S271 s271;
void check271va (int z, ...) {
    struct S271 arg;
    va_list ap;
    __builtin_va_start(ap, z);
    arg = __builtin_va_arg(ap, struct S271);
    long double a = __builtin_va_arg(ap, long double);
    printf("%Lf\n", a);
    if (a != 2.0L)
       printf("Fail\n");
    __builtin_va_end(ap);
}
int main (void) {
    printf("%lu\n", sizeof(s271));
    check271va (2, s271, 2.0L);
}
```
clang
```
16
0.000000
Fail
```
gcc
```
16
2.000000
```
https://godbolt.org/z/o6v318vWM

### PR DESCRIPTION
**Pull request by CoTinker**
Such struct types:
```
struct {
  struct{} a;
  long long b;
};

stuct {
  struct{} a;
  double b;
};
```
For such structures, Lo is NoClass and Hi is Integer/SSE. And when this structure argument is passed, the high part is passed at offset 8 in memory. So we should do special handling for these types in EmitVAArg.Fix https://github.com/llvm/llvm-project/issues/79790 and fix https://github.com/llvm/llvm-project/issues/86371.

### CODE REVIEW

**Comment by CoTinker** [comment]
Ping~

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 1]
```diff
@@ -3124,26 +3124,40 @@ RValue X86_64ABIInfo::EmitVAArg(CodeGenFunction &CGF, Address VAListAddr,
...
+    } else {
+      RegAddr =
+          Address(CGF.Builder.CreateGEP(CGF.Int8Ty, RegSaveArea, GpOrFpOffset),
+                  LTy, CharUnits::fromQuantity(Alignment));
+    }
+
     // Copy into a temporary if the type is more aligned than the
     // register save area.
-    if (TyAlign.getQuantity() > 8) {
+    if (neededInt && TyAlign.getQuantity() > 8) {
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/Targets/X86.cpp:3155]: Can we refactor the code so it's clear we never create two temporaries for the same va_arg?  Use an else-if instead of a separate if.

It looks it's possible that we end up reading past the end of the register save area for something like:

```
struct {
  long long b;
  struct{} a;
};
```

Can you also fix that while you're here?  (Not sure that actually has any visible effect, but better to be on the safe side.)

Comment (CoTinker) [reply clang/lib/CodeGen/Targets/X86.cpp]: I am glad to fix it.

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 2]
```diff
@@ -3124,26 +3124,76 @@ RValue X86_64ABIInfo::EmitVAArg(CodeGenFunction &CGF, Address VAListAddr,
...
+    //      int b;
+    //    };
+    //    ```
+    //    The lower 8 bytes of the structure are not stored,
+    //    so an 8-byte offset is needed when accessing the structure.
+    // 2)
+    //   ```
+    //   struct {
+    //     long long a;
+    //     int b;
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/Targets/X86.cpp:3166]: This example doesn't seem right; the size of the register save area has to be a multiple of 8.

Given that, we can simplify the "RegSize" to just `neededInt ? neededInt * 8 : 16`, I think?

Comment (CoTinker) [reply clang/lib/CodeGen/Targets/X86.cpp]: Yeah, you're right.

Comment (CoTinker) [reply clang/lib/CodeGen/Targets/X86.cpp]: SSE size is 16?
Consider such structure：
```
struct {
  double a;
  struct {} b;
}
```
Maybe `RegSize = neededInt ? neededInt * 8 : 8`, I think?

Comment (efriedma-quic) [reply clang/lib/CodeGen/Targets/X86.cpp]: The relevant "size" here is the size of the slots in the register save area.  Which is 16 bytes for fp registers.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by CoTinker** [comment]
Thanks.
