### PR TITLE
[clang][AArch64] Avoid a crash when a non-reserved register is used

### LINKED ISSUE #76426: [AArch64] Crash when compiling global register variable __asm__("x15") without -ffixed-x15
clang in AArch64 environment, fatal error at compile time.
If a global register variable associated with the register x15 is defined in the program and referenced in the program, a fatal error occurs at compile time when -ffixed-x15 is not specified.
When -ffixed-x15 is specified, it can be compiled.
Though failing to compile without -ffixed-x15 may be intentional, it should not be a fatal error.
Here is the program and compilation log:

[program]
```c
register int i1 __asm__("x15");

int foo(int i) {
  return i1;
}
int main() {
  return 0;
}
```

[compile log]
```
$ clang test_x15.c
fatal error: error in backend: Invalid register name "x15".
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 18.0.0 (https://github.com/llvm/llvm-project.git fe846bc9bd164ed89cef1caefb681e0aee3d4dec)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /work/home/marakawa/bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/test_x15-659ab1.c
clang: note: diagnostic msg: /tmp/test_x15-659ab1.sh
clang: note: diagnostic msg:

********************
$
```

[test_x15-659ab1.c]
```
# 1 "<built-in>"
# 1 "test_x15.c"
register int i1 __asm__("x15");

int foo(int i) {
  return i1;
}
int main() {
  return 0;
}
```

[test_x15-659ab1.sh]
```
# Crash reproducer for clang version 18.0.0 (https://github.com/llvm/llvm-project.git fe846bc9bd164ed89cef1caefb681e0aee3d4dec)
# Driver args: "test_x15.c"
# Original command:  "/work/home/marakawa/LLVM/llvm-project/installs/release/bin/clang-18" "-cc1" "-triple" "aarch64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-dumpdir" "a-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test_x15.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=non-leaf" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "generic" "-target-feature" "+neon" "-target-feature" "+v8a" "-target-abi" "aapcs" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/work/home/marakawa/test/local_test/1179_fatal" "-fcoverage-compilation-dir=/work/home/marakawa/test/local_test/1179_fatal" "-resource-dir" "/work/home/marakawa/LLVM/llvm-project/installs/release/lib/clang/18" "-internal-isystem" "/work/home/marakawa/LLVM/llvm-project/installs/release/lib/clang/18/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/opt/rh/gcc-toolset-12/root/usr/lib/gcc/aarch64-redhat-linux/12/../../../../aarch64-redhat-linux/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-ferror-limit" "19" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-target-feature" "+outline-atomics" "-target-feature" "-fmv" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/test_x15-518c67.o" "-x" "c" "test_x15.c"
 "/work/home/marakawa/LLVM/llvm-project/installs/release/bin/clang-18" "-cc1" "-triple" "aarch64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-dumpdir" "a-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test_x15.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=non-leaf" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "generic" "-target-feature" "+neon" "-target-feature" "+v8a" "-target-abi" "aapcs" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/work/home/marakawa/test/local_test/1179_fatal" "-fcoverage-compilation-dir=/work/home/marakawa/test/local_test/1179_fatal" "-ferror-limit" "19" "-fno-signed-char" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-target-feature" "+outline-atomics" "-target-feature" "-fmv" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c" "test_x15-659ab1.c"
```

### PR DESCRIPTION
**Pull request by igorkudrin**
Fixes #76426, #109778 (for AArch64)

The previous patch for this issue, #94271, generated an error message if a register and a global variable did not have the same size. This patch checks if the register is reserved.

### CODE REVIEW

File: clang/lib/Basic/Targets/AArch64.cpp [hunk 1]
```diff
@@ -232,13 +232,23 @@ bool AArch64TargetInfo::validateTarget(DiagnosticsEngine &Diags) const {
...
   }
+  if (RegName == "sp") {
+    HasSizeMismatch = RegSize != 64;
+    return true;
+  }
+  if (RegName.starts_with("x")) {
+    HasSizeMismatch = RegSize != 64;
+    // Check if the register is reserved. See also
+    // AArch64TargetLowering::getRegisterByName().
+    return RegName == "x0" ||
```
Comment (DanielKristofKiss) [inline clang/lib/Basic/Targets/AArch64.cpp:247]: maybe add a test case for x0 too?

Comment (igorkudrin) [reply clang/lib/Basic/Targets/AArch64.cpp:247]: Done

**Comment by igorkudrin** [comment]
> Please check if this fixes #109778 too. Seems very similar.

This patch fixes #109778, but only for AArch64.

**Comment by DavidSpickett** [comment]
Thanks, I'll leave it open then, this PR is a welcome improvement regardless.

File: clang/lib/Basic/Targets/AArch64.cpp [hunk 2]
```diff
@@ -232,13 +232,23 @@ bool AArch64TargetInfo::validateTarget(DiagnosticsEngine &Diags) const {
...
+           (RegName == "x18" &&
+            llvm::AArch64::isX18ReservedByDefault(getTriple())) ||
+           getTargetOpts().FeatureMap.lookup(("reserve-" + RegName).str());
```
Comment (kawashima-fj) [inline clang/lib/Basic/Targets/AArch64.cpp:250]: To avoid the `fatal error: error in backend: Invalid register name "x??"` error in #109778, this check is sufficient.

I think the original purpose of rejecting a global register variable associated with a non-reserved register is to avoid unintended register use. `w??` registers are lower half bits of the corresponding `x??` registers. So when `x??` register is not reserved, should we reject a global register variable associated with the corresponding `w??`?

For this purpose, maybe [the backend](https://github.com/llvm/llvm-project/blob/bc28260/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L11611) should also check `w??` registers. Actually, [old backend code checked `w??` regsters](https://github.com/llvm/llvm-project/commit/fcbec02ea6fb2a76352b64790cd9ae300f6a9943#diff-6291e4657dea1f4fecdcb9dc96bfb014f79d4c617f080b2f033943e52732cf69).

Comment (igorkudrin) [reply clang/lib/Basic/Targets/AArch64.cpp]: Thanks! Since this patch is focused on fixing the crash, it doesn't seem appropriate to make `AArch64TargetLowering::getRegisterByName()` more restrictive here. However, I added checks for `w??` registers in `AArch64TargetInfo::validateGlobalRegisterVariable()` and corresponding tests.

**Review by kawashima-fj — APPROVED** [review]
LGTM. Thanks!
