### PR TITLE
[OMPIRBuilder] - Fix emitTargetTaskProxyFunc to not generate empty functions

### LINKED ISSUE #126949: [OMPIRBuilder] - Empty target task proxy function generated by OMPIRBuilder (`emitTargetTaskProxyFunction`)
Reproducer: 

```
$> mlir-translate -mlir-to-llvmir ${LLVM_PROJECT_DIR}/mlir/test/Target/LLVMIR/omptarget-depend-host-only
$> cat ${LLVM_PROJECT_DIR}/mlir/test/Target/LLVMIR/omptarget-depend-host-only.mlir
// RUN: mlir-translate -mlir-to-llvmir %s | FileCheck %s

module attributes {omp.is_target_device = false} {
  llvm.func @omp_target_depend_() {
    %0 = llvm.mlir.constant(39 : index) : i64
    %1 = llvm.mlir.constant(1 : index) : i64
    %2 = llvm.mlir.constant(40 : index) : i64
    %3 = omp.map.bounds lower_bound(%1 : i64) upper_bound(%0 : i64) extent(%2 : i64) stride(%1 : i64) start_idx(%1 : i64)
    %4 = llvm.mlir.addressof @_QFEa : !llvm.ptr
    %5 = omp.map.info var_ptr(%4 : !llvm.ptr, !llvm.array<40 x i32>) map_clauses(from) capture(ByRef) bounds(%3) -> !llvm.ptr {name = "a"}
    omp.target depend(taskdependin -> %4 : !llvm.ptr) map_entries(%5 -> %arg0 : !llvm.ptr) {
      %6 = llvm.mlir.constant(100 : index) : i32
      llvm.store %6, %arg0 : i32, !llvm.ptr
      omp.terminator
    }
    llvm.return
  }

  llvm.mlir.global internal @_QFEa() {addr_space = 0 : i32} : !llvm.array<40 x i32> {
    %0 = llvm.mlir.zero : !llvm.array<40 x i32>
    llvm.return %0 : !llvm.array<40 x i32>
  }
}

// CHECK: define void @omp_target_depend_()
// CHECK-NOT: define {{.*}} @
// CHECK-NOT: call i32 @__tgt_target_kernel({{.*}})
// CHECK: call void @__omp_offloading_[[DEV:.*]]_[[FIL:.*]]_omp_target_depend__l[[LINE:.*]](ptr {{.*}})
// CHECK-NEXT: ret void

// CHECK: define internal void @__omp_offloading_[[DEV]]_[[FIL]]_omp_target_depend__l[[LINE]](ptr %[[ADDR_A:.*]])
// CHECK: store i32 100, ptr %[[ADDR_A]], align 4
```
Two problems in the output

1. Empty target task proxy function `@.omp_target_task_proxy_func`
```
define internal void @.omp_target_task_proxy_func(i32 %thread.id, ptr %task) {
entry:
  ret void
}

```
2. After 1 is fixed, we'll end up with dual execution of the kernel because we hit a corner case (single basic block task bodies) in `OpenMPIRBuilder::OutlineInfo::collectBlocks` such that the entire task body is not outlined in the target task.
```
codeRepl:                                         ; preds = %entry
  %omp_global_thread_num = call i32 @__kmpc_global_thread_num(ptr @2)
  %5 = call ptr @__kmpc_omp_task_alloc(ptr @2, i32 %omp_global_thread_num, i32 0, i64 40, i64 0, ptr @.omp_target_task_proxy_func)
  call void @__kmpc_omp_wait_deps(ptr @2, i32 %omp_global_thread_num, i32 1, ptr %.dep.arr.addr, i32 0, ptr null)
  call void @__kmpc_omp_task_begin_if0(ptr @2, i32 %omp_global_thread_num, ptr %5)
  call void @.omp_target_task_proxy_func(i32 %omp_global_thread_num, ptr %5)  ;;;  first execution of the kernel once problem 1 is fixed.
  call void @__kmpc_omp_task_complete_if0(ptr @2, i32 %omp_global_thread_num, ptr %5)
  br label %target.task.body

target.task.body:                                 ; preds = %codeRepl
  call void @__omp_offloading_10307_a581555_omp_target_depend__l11(ptr @_QFEa) ;;;; Second execution of the kernel when problem 1 is fixed
  ret void
}

```

### PR DESCRIPTION
**Pull request by bhandarkar-pranav**
This is a fix for https://github.com/llvm/llvm-project/issues/126949 There are two issues being fixed here. First, in some cases, OMPIRBuilder generates empty target task proxy functions. This happens when the target kernel doesn't use any stack-allocated data (either no data or only globals). The second problem is encountered when the target task i.e the code that makes the target call spans a single basic block. This usually happens when we do not generate a target or device kernel launch and instead fall back to the host. In such cases, we end up not outlining the target task entirely. This can cause us to call target kernel twice - once via the target task proxy function and a second time via the host fallback

This PR fixes both of these problems and updates some tests to catch these problems should this patch fail.

### CODE REVIEW

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -7229,11 +7233,28 @@ OpenMPIRBuilder::InsertPointOrErrorTy OpenMPIRBuilder::emitTargetTask(
...
+  // the outlining process. So, simply create a new empty block to which we
+  // uncoditionally branch from where TaskBodyCB left off
+  BasicBlock *TargetTaskContBlock =
+      BasicBlock::Create(Builder.getContext(), "target.task.cont");
+
+  auto *CurFn = Builder.GetInsertBlock()->getParent();
+  emitBranch(TargetTaskContBlock);
+  emitBlock(TargetTaskContBlock, CurFn, /*IsFinished=*/true);
+
+  OI.ExitBB = TargetTaskContBlock;
```
Comment (ergawy) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:7256]: I think we can use `splitBB` here.

```suggestion
  OI.ExitBB = splitBB(Builder, /*CreateBranch=*/true, "target.task.cont");
  emitBlock(OI.ExitBB, OI.ExitBB->getParent(), /*IsFinished=*/true);
```

File: mlir/test/Target/LLVMIR/omptarget-nowait-host-only.mlir [hunk 2]
```diff
@@ -20,10 +20,30 @@ module attributes {omp.is_target_device = false} {
 // CHECK: define void @omp_target_nowait_()
 // CHECK-NOT: define {{.*}} @
 // CHECK-NOT: call ptr @__kmpc_omp_target_task_alloc({{.*}})
+// CHECK:  call void @__kmpc_omp_task_begin_if0
+// CHECK-NEXT: call void @.omp_target_task_proxy_func
```
Comment (ergawy) [inline mlir/test/Target/LLVMIR/omptarget-nowait-host-only.mlir:24]: nit: can we check that the body of `omp_target_task_proxy_func` is not empty anymore?

**Review by ergawy — APPROVED** [review]
LGTM! Thanks Pranav. Just one suggestion to extend testing.

**Review by skatrak — APPROVED** [review]
LGTM, just minor nits from me. I also agree with @ergawy about using `splitBB` to simplify the implementation.

File: mlir/test/Target/LLVMIR/omptarget-nowait-host-only.mlir (hunk 2 above)
Comment (bhandarkar-pranav) [reply mlir/test/Target/LLVMIR/omptarget-nowait-host-only.mlir:24]: That is checked on line 49 below.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp (hunk 1 above)
Comment (bhandarkar-pranav) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp]: `emitBlock` isn't needed as `splitBB` calls `BasicBlock::create` with a `Function *`. This results in the block being inserted into the function. Calling `emitBlock` aftriggers asserts.
