### PR TITLE
[CIR] Cleanup support for C functions

### LINKED ISSUE #130200: [CIR] Cleanup support for C functions
The initial function support is working for C++ functions, but C functions trigger the following error:

`error: ClangIR code gen Not Yet Implemented: non-prototype function type`

Some additional handling needs to be added so that this diagnostic isn't generated and C test cases can be created.

### PR DESCRIPTION
**Pull request by el-ev**
Closes #130200.

### CODE REVIEW

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 1]
```diff
@@ -13,20 +13,76 @@
...
+  SmallVector<mlir::Type, 8> argTypes;
+  unsigned argNo = 0;
+  CIRGenFunctionInfo::const_arg_iterator it = fi.arg_begin(),
+                                         ie = it + fi.getNumRequiredArgs();
+  for (; it != ie; ++it, ++argNo) {
+    const auto &argInfo = it->info;
+
+    switch (argInfo.getKind()) {
+    default:
+      llvm_unreachable("NYI");
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:70]:
```suggestion
          cgm.errorNYI("getFunctionType: unhandled argument kind");
```

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 2]
```diff
@@ -13,20 +13,76 @@
...
+    case cir::ABIArgInfo::Direct:
+      mlir::Type argType = argInfo.getCoerceToType();
+      argTypes.push_back(argType);
+      break;
+    }
+  }
+
+  bool erased = functionsBeingProcessed.erase(&fi);
+  assert(erased && "Not in set?");
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:79]: You need to add `(void)erased;' above this to avoid unused variable warnings in non-debug builds.

File: clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h [hunk 3]
```diff
@@ -47,18 +98,51 @@ class CIRGenFunctionInfo final
 
   // This function has to be CamelCase because llvm::FoldingSet requires so.
   // NOLINTNEXTLINE(readability-identifier-naming)
-  static void Profile(llvm::FoldingSetNodeID &id, CanQualType resultType) {
+  static void Profile(llvm::FoldingSetNodeID &id, RequiredArgs required,
+                      CanQualType resultType,
+                      llvm::ArrayRef<CanQualType> argTypes) {
+    id.AddBoolean(required.getOpaqueData());
     resultType.Profile(id);
+    for (const auto &arg : argTypes)
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h:106]:
```suggestion
    for (const CanQualType &type : argTypes)
```

File: clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h [hunk 4]
```diff
@@ -47,18 +98,51 @@ class CIRGenFunctionInfo final
...
+      arg.Profile(id);
   }
 
-  void Profile(llvm::FoldingSetNodeID &id) { getReturnType().Profile(id); }
+  // NOLINTNEXTLINE(readability-identifier-naming)
+  void Profile(llvm::FoldingSetNodeID &id) {
+    id.AddBoolean(required.getOpaqueData());
+    getReturnType().Profile(id);
+    for (const auto &i : arguments())
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h:114]: Don't use auto here. Is this ArgInfo?

File: clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h [hunk 5]
```diff
@@ -47,18 +98,51 @@ class CIRGenFunctionInfo final
...
+  using arg_iterator = ArgInfo *;
+
+  const_arg_iterator arg_begin() const { return getArgsBuffer() + 1; }
+  const_arg_iterator arg_end() const { return getArgsBuffer() + 1 + numArgs; }
+  arg_iterator arg_begin() { return getArgsBuffer() + 1; }
+  arg_iterator arg_end() { return getArgsBuffer() + 1 + numArgs; }
+
+  unsigned arg_size() const { return numArgs; }
+
+  llvm::MutableArrayRef<ArgInfo> arguments() {
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h:134]: This doesn't seem like the right name here. It's return info about the arguments, not the actual arguments, right? Similarly for the arg_begin and arg_end functions.

File: clang/lib/CIR/CodeGen/CIRGenModule.cpp [hunk 6]
```diff
@@ -212,8 +212,21 @@ void CIRGenModule::emitGlobalFunctionDefinition(clang::GlobalDecl gd,
...
+  cir::FuncType funcType;
+  // TODO: Move this to arrangeFunctionDeclaration when it is
+  // implemented.
+  // When declaring a function without a prototype, always use a
+  // non-variadic type.
+  if (CanQual<FunctionNoProtoType> noProto =
+          funcDecl->getType()
+              ->getCanonicalTypeUnqualified()
+              .getAs<FunctionNoProtoType>()) {
+    auto &fi = getTypes().arrangeCIRFunctionInfo(noProto->getReturnType(), {},
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenModule.cpp:225]: Don't use auto here.

File: clang/lib/CIR/CodeGen/CIRGenTypes.cpp [hunk 7]
```diff
@@ -524,7 +523,9 @@ CIRGenTypes::arrangeCIRFunctionInfo(CanQualType returnType) {
   if (retInfo.canHaveCoerceToType() && retInfo.getCoerceToType() == nullptr)
     retInfo.setCoerceToType(convertType(fi->getReturnType()));
 
-  assert(!cir::MissingFeatures::opCallArgs());
+  for (auto &i : fi->arguments())
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenTypes.cpp:526]: Don't use auto here.

File: clang/lib/CIR/CodeGen/TargetInfo.cpp [hunk 8]
```diff
@@ -32,8 +32,14 @@ void X8664ABIInfo::computeInfo(CIRGenFunctionInfo &funcInfo) const {
   // Top level CIR has unlimited arguments and return types. Lowering for ABI
   // specific concerns should happen during a lowering phase. Assume everything
   // is direct for now.
-  assert(!cir::MissingFeatures::opCallArgs());
-
+  for (CIRGenFunctionInfo::arg_iterator it = funcInfo.arg_begin(),
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/TargetInfo.cpp:35]: Can you use a range-based for loop here?

File: clang/test/CIR/CodeGen/basic.c [hunk 9]
```diff
@@ -233,6 +233,19 @@ int f8(int *p) {
 // OGCG:   %[[P2:.*]] = load ptr, ptr %[[P_PTR]], align 8
 // OGCG:   %[[STAR_P:.*]] = load i32, ptr %[[P2]], align 4
 
+
+void f9() {}
```
Comment (andykaylor) [inline clang/test/CIR/CodeGen/basic.c:237]: It seems like a lot of code was added compared to what is covered by this test. Do we have tests for any of the additional functionality?

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 10]
```diff
@@ -71,6 +130,23 @@ static cir::CIRCallOpInterface emitCallLikeOp(CIRGenFunction &cgf,
   return builder.createCallOp(callLoc, directFuncOp);
 }
 
+const CIRGenFunctionInfo &
+CIRGenTypes::arrangeFreeFunctionType(CanQual<FunctionProtoType> fpt) {
+  SmallVector<CanQualType, 16> argTypes;
+  for (unsigned i = 0, e = fpt->getNumParams(); i != e; ++i)
```
Comment (erichkeane) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:136]: Is this not just a `llvm::copy(fpt->param_types(), std::back_inserter(argTypes))` ?

**Review by erichkeane — COMMENTED** [review]
Andy is on teh right rack here, only one comment on a quick look thru.

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 11]
```diff
@@ -13,20 +13,76 @@
...
+#include "CIRGenFunctionInfo.h"
 #include "clang/CIR/MissingFeatures.h"
 
 using namespace clang;
 using namespace clang::CIRGen;
 
-CIRGenFunctionInfo *CIRGenFunctionInfo::create(CanQualType resultType) {
-  void *buffer = operator new(totalSizeToAlloc<ArgInfo>(1));
+CIRGenFunctionInfo *
+CIRGenFunctionInfo::create(CanQualType resultType,
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:23]: This same change is being made in https://github.com/llvm/llvm-project/pull/136810. See my comment there about coordinating the two.

File: clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h (hunk 4 above)
Comment (el-ev) [reply clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h:114]: Yes.

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp (hunk 2 above)
Comment (el-ev) [reply clang/lib/CIR/CodeGen/CIRGenCall.cpp:93]: Thank you! I wasn't aware of the purpose of that line before, and I understand its purpose now.

File: clang/test/CIR/CodeGen/basic.c (hunk 9 above)
Comment (el-ev) [reply clang/test/CIR/CodeGen/basic.c:237]: I'm actually unsure what kind of new tests would be appropriate. Do you have any suggestions on what I should add?

**Review by bcardosolopes — APPROVED** [review]
I don't have anything to say that wasn't covered, LGTM once Andy is happy!

**Comment by andykaylor** [comment]
@el-ev Can you rebase this now that the call args change has landed? Thanks!

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 12]
```diff
@@ -119,6 +128,63 @@ class ClangToCIRArgMapping {
 
 } // namespace
 
+cir::FuncType CIRGenTypes::getFunctionType(const CIRGenFunctionInfo &fi) {
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:131]: This should be refactored to reflect the changes in https://github.com/llvm/clangir/pull/1604. I apologize for the extra work this causes you. I didn't realize the extent of the changes that I was going to make there.

File: clang/lib/CIR/CodeGen/CIRGenCall.cpp [hunk 13]
```diff
@@ -177,16 +263,16 @@ RValue CIRGenFunction::emitCall(const CIRGenFunctionInfo &funcInfo,
   QualType retTy = funcInfo.getReturnType();
   const cir::ABIArgInfo &retInfo = funcInfo.getReturnInfo();
 
-  ClangToCIRArgMapping cirFuncArgs(cgm.getASTContext(), funcInfo);
+  ClangToCIRArgMapping cirFuncArgs(cgm.getASTContext(), funcInfo, false);
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenCall.cpp:266]: I'm changing this function in https://github.com/llvm/llvm-project/pull/139159 to remove the ABI-specific handling.

**Review by andykaylor — COMMENTED** [review]
This change looks good. Unfortunately it's colliding with my work to remove the argument ABI handling from CIRGen. I don't think it will require much more work after https://github.com/llvm/llvm-project/pull/139159 is merged. I'd like to continue holding this until that is done, but this will be very helpful after that.

Sorry about the overlap in these changes.

**Comment by andykaylor** [comment]
I've just merged my change to remove the ABI handling code. Feel free to proceed with this change now.

**Review by Lancern — APPROVED** [review]
LGTM

File: clang/lib/CIR/CodeGen/CIRGenModule.cpp [hunk 14]
```diff
@@ -247,8 +248,21 @@ void CIRGenModule::emitGlobalFunctionDefinition(clang::GlobalDecl gd,
...
+  // When declaring a function without a prototype, always use a
+  // non-variadic type.
+  if (CanQual<FunctionNoProtoType> noProto =
+          funcDecl->getType()
+              ->getCanonicalTypeUnqualified()
+              .getAs<FunctionNoProtoType>()) {
+    const CIRGenFunctionInfo &fi = getTypes().arrangeCIRFunctionInfo(
+        noProto->getReturnType(), {}, RequiredArgs::All);
+    funcType = getTypes().getFunctionType(fi);
+  } else
```
Comment (andykaylor) [inline clang/lib/CIR/CodeGen/CIRGenModule.cpp:264]: LLVM Coding Standards require braces for the `else` if they are required for the `if`.

https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

File: clang/test/CIR/CodeGen/basic.c (hunk 9 above)
Comment (andykaylor) [inline clang/test/CIR/CodeGen/basic.c:237]: Since you added handling for required arguments, can you add a test that has a declaration with optional arguments and calls to that function with optional arguments emitted? I'd suggest a function with one required argument and two optional arguments and calls to that function with one, two, and three arguments provided. Perhaps also a test with zero required arguments and two optional arguments, called with zero, one, and two arguments.

**Review by andykaylor — COMMENTED** [review]
This looks good. I just have one nit and a request for additional tests.

File: clang/test/CIR/CodeGen/basic.c (hunk 9 above)
Comment (el-ev) [reply clang/test/CIR/CodeGen/basic.c:237]: call to variadic function is NYI

File: clang/lib/CIR/CodeGen/CIRGenModule.cpp (hunk 14 above)
Comment (el-ev) [reply clang/lib/CIR/CodeGen/CIRGenModule.cpp]: Fixed, thanks.

File: clang/test/CIR/CodeGen/basic.c (hunk 9 above)
Comment (andykaylor) [reply clang/test/CIR/CodeGen/basic.c:237]: I was talking about C++ functions with default arguments, but I see now that the AST provides those arguments and that you are correct about the required args here being connected to variadic functions.

**Review by andykaylor — APPROVED** [review]
lgtm

**Comment by andykaylor** [comment]
@el-ev I merged this because I'm working on another change that's dependent on this.
