### PR TITLE
[Flang][OpenMP] Fix crash when loop index var is pointer or allocatable

### LINKED ISSUE #121290: [Flang][OpenMP] verification of lowering to FIR failed with "'fir.store' op store value type must match memory reference type"
Reproducible on Godbolt:
https://godbolt.org/z/j6o13x97x

Reproducer:
```f90
integer, pointer :: a
integer :: arr(20,10)
integer :: i

!$omp simd lastprivate(i)
do a = 1, 10
  do i = a, 20
    arr(i, a) = i + a
  end do
end do

end
```

Compilation error:
```console
$ flang-new -fopenmp test.f90
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
warning: loc("/tmp/test.f90":1:1): OpenMP loop iteration variable cannot have more than 64 bits size and will be narrowed into 64 bits.
warning: loc("/tmp/test.f90":1:1): OpenMP loop iteration variable cannot have more than 64 bits size and will be narrowed into 64 bits.
error: loc("/tmp/test.f90":5:7): 'fir.store' op store value type must match memory reference type
error: verification of lowering to FIR failed
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Use hlfir dereferencing for pointers and allocatables and use hlfir assign. Also, change the code updating IV in lastprivate.

Note: This is a small change. Modifications in existing tests are changes from fir.store to hlfir.assign.

Fixes #121290

### CODE REVIEW

**Review by tblah — APPROVED** [review]
The approach looks sensible to me. What is needed to bring this out of draft?

**Comment by kiranchandramohan** [comment]
> The approach looks sensible to me. What is needed to bring this out of draft?

There is one fix required for the lastprivate case. I will add that and remove it out of draft.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 1]
```diff
@@ -308,7 +308,10 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
     firOpBuilder.setInsertionPointToStart(&ifOp.getThenRegion().front());
     for (auto [v, loopIV] : llvm::zip_equal(vs, loopIVs)) {
       assert(loopIV && "loopIV was not set");
-      firOpBuilder.createStoreWithConvert(loc, v, loopIV);
+      hlfir::Entity loopIVEntity{loopIV};
+      loopIVEntity =
+          hlfir::derefPointersAndAllocatables(loc, firOpBuilder, loopIVEntity);
+      firOpBuilder.create<hlfir::AssignOp>(loc, v, loopIVEntity);
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:314]: The lowering code for hlfir:Assign to fir::store seems to insert the convert, hence skipping that here.

File: flang/test/Lower/OpenMP/lastprivate-iv.f90 [hunk 2]
```diff
@@ -78,13 +79,48 @@ subroutine lastprivate_iv_i1
...
+!CHECK:    }
+
+!CHECK-FIR:    omp.wsloop private(@_QFlastprivate_iv_pointerEi_private_box_ptr_i32 %{{.*}} -> %[[PRIVATE_IV:.*]] : !fir.ref<!fir.box<!fir.ptr<i32>>>) {
+!CHECK-FIR:      omp.loop_nest (%[[LOOP_INDEX:.*]]) : i64
+!CHECK-FIR:        %[[PRIVATE_IV_DECL:.*]] = fir.declare %[[PRIVATE_IV]] {fortran_attrs = #fir.var_attrs<pointer>, uniq_name = "_QFlastprivate_iv_pointerEi"} : (!fir.ref<!fir.box<!fir.ptr<i32>>>) -> !fir.ref<!fir.box<!fir.ptr<i32>>>
+!CHECK-FIR:        %[[LOOP_INDEX_INCR:.*]] = arith.addi %[[LOOP_INDEX]], %{{.*}} : i64
+!CHECK-FIR:        fir.if %{{.*}} {
+!CHECK-FIR:          %[[PRIVATE_IV_BOX:.*]] = fir.load %[[PRIVATE_IV_DECL]] : !fir.ref<!fir.box<!fir.ptr<i32>>>
+!CHECK-FIR:          %[[PRIVATE_IV_ADDR:.*]] = fir.box_addr %[[PRIVATE_IV_BOX]] : (!fir.box<!fir.ptr<i32>>) -> !fir.ptr<i32>
+!CHECK-FIR:          %[[LOOP_INDEX_CVT:.*]] = fir.convert %[[LOOP_INDEX_INCR]] : (i64) -> i32
```
Comment (kiranchandramohan) [inline flang/test/Lower/OpenMP/lastprivate-iv.f90:114]: Test for convert insertion.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 3]
```diff
@@ -308,7 +308,10 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
     firOpBuilder.setInsertionPointToStart(&ifOp.getThenRegion().front());
     for (auto [v, loopIV] : llvm::zip_equal(vs, loopIVs)) {
       assert(loopIV && "loopIV was not set");
```
Comment (luporl) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:310]: Since you are changing this part, this assert can be removed. It was added when there was a single `loopIV`, that was a pointer.

**Review by luporl — APPROVED** [review]
LGTM
