### PR TITLE
[clang-format] Align within the level with Cpp11BracedListStyle disabled

### LINKED ISSUE #53699: [clang-format] Unrelated declarations are aligned with Cpp11BracedListStyle: false
Found when fixing #44292.

Given config:
```
BasedOnStyle: LLVM
AlignConsecutiveDeclarations: true
Cpp11BracedListStyle: false
```

this already formatted code:
```
const volatile auto result{ []() {
  const auto something = 1;
  return 2;
} };
```

gets incorrectly formatted to:
```
const volatile auto result{ []() {
  const auto        something = 1;
  return 2;
} };
```

That seems to be cause by the fact that with `Cpp11BracedListStyle: false`, we do not add an indent level, and so the declarations of `result` and `something` are considered to be at the same level and hence aligned.

### PR DESCRIPTION
**Pull request by sstwcw**
When the style is
`{AlignConsecutiveDeclarations: true, Cpp11BracedListStyle: false}`, the program would sometimes align the lambda body with the outside. Like this.

```C++
const volatile auto result{ []() {
  const auto        something = 1;
  return 2;
} };
```

This patch stops it.  Now the output looks like this.

```C++
const volatile auto result{ []() {
  const auto something = 1;
  return 2;
} };
```

Fixes #53699.

The problem was with how the `AlignTokenSequence` function tracked levels.  The stack was pushed once when a token was more nested than the previous one.  It was popped once when a token was less nested than the previous one.  With the option `Cpp11BracedListStyle` disabled, the `[` token was deeper than the previous token by 2 levels.  Both its indentation level and nesting level were more than that of the previous one.  But the stack was only pushed once.  The following tokens popped the 2 levels separately.  The function treated the body of the lambda expression as on the same level as the outside.

The problem is fixed this way.  The function `AlignTokens` which calls the function `AlignTokenSequence` already uses a simpler and more robust way to track levels.  It remembers the outermost level it should align. It compares the token's level with the outermost level.  It does not need a stack.  So it is immune to the problem.  This patch makes the function `AlignTokenSequence` take as a parameter the indices of the tokens matched by the function `AlignTokens`.  This way it does not have to contain the logic again.

Now the function `AlignTokenSequence` only aligns tokens already matched by the function `AlignTokens`.  It is easy to see that the assertion on line 453 holds.  The workaround on line 354 is not needed any more.  The test on line 20310 added at the same time as the assertion ensures that the assertion hold.

The stack in the function `AlignTokenSequence` is kept for now.  It is still used to figure out when things inside a level should move along with the outer level.  Since the stack has the problem, the developer plans to move the logic into token annotator.  It already uses a stack.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]
LGTM, please wait a day or two before the merge.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 1]
```diff
@@ -12,6 +12,7 @@
 //===----------------------------------------------------------------------===//
 
 #include "WhitespaceManager.h"
+#include "llvm/ADT/ArrayRef.h"
```
Comment (owenca) [inline clang/lib/Format/WhitespaceManager.cpp:15]: Delete.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 2]
```diff
@@ -279,20 +280,19 @@ void WhitespaceManager::calculateLineBreakInformation() {
...
-// Column - The token for which Matches returns true is moved to this column.
+// Column - The tokens indexed in Matches are moved to this column.
 // RightJustify - Whether it is the token's right end or left end that gets
 // moved to that column.
-template <typename F>
 static void
 AlignTokenSequence(const FormatStyle &Style, unsigned Start, unsigned End,
-                   unsigned Column, bool RightJustify, F &&Matches,
+                   unsigned Column, bool RightJustify,
+                   ArrayRef<const unsigned> Matches,
```
Comment (owenca) [inline clang/lib/Format/WhitespaceManager.cpp:289]: Is the `const` redundant?

**Review by owenca — APPROVED** [review]

File: clang/lib/Format/WhitespaceManager.cpp (hunk 2 above)
Comment (sstwcw) [reply clang/lib/Format/WhitespaceManager.cpp]: Seems so.  I removed it.  I thought the array ref type allowed changing the data just like the span type.  By the way, why is there an array ref type when there is already the span type?
