### PR TITLE
[Clang] Do not create dependent CallExpr having UnresolvedLookupExpr inside non-dependent context

### LINKED ISSUE #122892: Clang 18 regression on C++20 mode: `Unexpected placeholder builtin type!` crash
```
clang++ -v
clang version 20.0.0git (https://github.com/llvm/llvm-project c047a5b3f6e2295dd74f1e8f17f1a023150b246c)
Target: x86_64-pc-windows-msvc
Thread model: posix
```

`clang++ main.cpp -std=c++20`

```
struct A {
    void f() {
        l(r);
    }
    static void r() {}
    static auto l(auto &&f) {}    // error
  //static void l(auto &&f) {}    // ok
};

int main() {
    A k;
    k.f();
}
```

### PR DESCRIPTION
**Pull request by TilakChad**
The `UnresolvedLookupExpr` doesn't get looked up and resolved again while it is inside the non-dependent context. It propagates into the codegen phase, causing the assertion failure.

We attempt to determine if the current context is dependent before moving on with the substitution introduced in the https://github.com/llvm/llvm-project/commit/20a05677f9394d4bc9467fe7bc93a4ebd3aeda61. 

This fixes https://github.com/llvm/llvm-project/issues/122892.

### CODE REVIEW

**Comment by erichkeane** [comment]
This doesn't quite seem right to me... First, I would expect us to check the declaration context here rather than whether it is in a function template.  

Second, I find myself thinking the `UnresolvedLookupExpr` in a non-dependent context is the actual problem, and we need to figure out how we got there, as that is the big problem.

**Comment by TilakChad** [comment]
Yeah, it seems more appropriate to check for the dependence of current DeclContext. 

As for the second part, it seems to happen only when a non-dependent function calls the later defined overloaded member function.

 Should it compile (I guess not) or be diagnosed  before reaching that point?

**Comment by TilakChad** [comment]
Hi @erichkeane

**Comment by erichkeane** [comment]
> Hi @erichkeane Is this resolution still not good enough? I should probably close the PR if thats the case.

I apparently didn't see your last change since your last comment.  Looking now.

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -14228,9 +14228,15 @@ ExprResult Sema::BuildOverloadedCallExpr(Scope *S, Expr *Fn,
     const FunctionDecl *FDecl = Best->Function;
     if (FDecl && FDecl->isTemplateInstantiation() &&
         FDecl->getReturnType()->isUndeducedType()) {
+
+      // As there'll be no attempt to resolve UnresolvedLookupExpr again inside
+      // non-dependent context, skip considering it as type-dependent.
+      const DeclContext *DC = CurContext;
+      const bool Resolvable = DC && DC->isDependentContext();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaOverload.cpp:14235]: `Resolvable` isn't a good name here, it sorta implies the opposite of what we mean, but not to the point of `NotResolvable` being a good idea.  I think just putting `&& CurContext->isDependentContext()` below is actually more readable.  Also, you don't really have to check the `DeclContext`, having a null one I think requires that you be outside of a `TranslationUnitDecl`, which isn't possible. 

I see that we are just going through `FinishOverloadedCallExpr` in the event that we are going to instantiate this again, which I guess makes sense, since this is creating a call with a `DependentTy`, but this comment doesn't make it clear what i   I think I'd be happy with a better commit message explaining the whole situation and why this works.  I've debugged a while and think I have a good hold on it though, so just a better description I think would help

**Review by erichkeane — COMMENTED** [review]
I have minor suggestions, and am not quite comfortable with this yet, so please improve the commit message and make the change I requested (re `Resolvable`), and I'll revisit this afterwards.

File: clang/test/SemaCXX/deduced-return-type-cxx14.cpp [hunk 2]
```diff
@@ -703,6 +703,48 @@ auto f(auto x) { // cxx14-error {{'auto' not allowed in function prototype}}
   return f(1) + 1;
 }
 
+namespace GH122892 {
```
Comment (zyn0217) [inline clang/test/SemaCXX/deduced-return-type-cxx14.cpp:706]: I think the test should live in CodeGen/ rather than SemaCXX/, which mostly contains '-fsyntax-only' tests, while the issue arises in the codegen stage?

Comment (erichkeane) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:706]: I don't think so?  Since this is replacing the condition that previously crashed in codegen with a sema-error, right?

Comment (zyn0217) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:706]: I don't know, but the original issue doesn't manifest with `-fsyntax-only` https://godbolt.org/z/MdMzjEd5q

So if this patch changed the behavior in that mode (e.g. diagnose out errors earlier) then it probably makes sense to have the test live in SemaCXX, just my thoughts :P

Comment (erichkeane) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:706]: Yeah, so this patch now prevents an `UnresolvedLookupExpr` from being put into the AST for a non-dependent function.  The symptom of that (besides the AST-dump) was that CodeGen didn't know how to handle that for obvious reasons.

This patch is now preventing that `UnresolvedLookupExpr` from being put into the AST for non-dependent functions, and falls-thru to emitting an error.

I Think.

Comment (zyn0217) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:706]: Oh so it is the case - looks like we now have errors for the case in question.

**Comment by TilakChad** [comment]
I've incorporated your feedback and updated the PR. 

Let me know if I have to change anything. 
Thanks for taking your time to review this PR.

**Review by erichkeane — APPROVED** [review]
I'm going to give a conditional approval.  My comfort level is reasonable right now, but I want time to think about it.  So if I haven't responded by ~EOD Monday (or if no one else did other comments), feel free to merge.

**Comment by Sirraide** [comment]
This is still missing a release note, but I can merge it for you once you add one.

**Comment by TilakChad** [comment]
> This is still missing a release note, but I can merge it for you once you add one.

@Sirraide 
I've updated the release notes. 
Please merge it on my behalf. And thanks.

**Comment by Sirraide** [comment]
I’ll do that once CI is done

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -337,6 +337,7 @@ Bug Fixes to C++ Support
 - Fixed an assertion failure affecting code that uses C++23 "deducing this". (#GH130272)
 - Clang now properly instantiates destructors for initialized members within non-delegating constructors. (#GH93251)
 - Correctly diagnoses if unresolved using declarations shadows template paramters (#GH129411)
+- Fixed a clang regression on c++20 mode where unresolved dependent call expressions were created inside non-dependent context (#GH122892)
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:340]:
```suggestion
- Fixed a Clang regression in C++20 mode where unresolved dependent call expressions were created inside non-dependent contexts (#GH122892)
```

**Review by Sirraide — COMMENTED** [review]
Just some minor fixes

**Comment by Sirraide** [comment]
Huh, I wonder why CI’s upset all of a sudden

**Review by mizvekov — APPROVED** [review]

**Review by shafik — COMMENTED** [review]
I have a few concerns w/ this PR.

Number one we do not cover the original test case which crashes, as far as I can tell none of the tests crash before this fix. This is large oversight.

It looks like currently gcc is the only one that rejects this code as we will now do as well: https://godbolt.org/z/Pqnb4eq6K

I don't see anyone justifying this change in behavior w/ wording from the standard. I would have expected to see such wording references in the summary and also added to a comment in the code itself to document the justification for this change in behavior for future readers of the code.

CC @erichkeane @mizvekov @AaronBallman

**Comment by mizvekov** [comment]
Clang does crash with one of the included test cases, if you try to actually use the function: https://godbolt.org/z/e6e6Ehjoj

My reading is that using a static function with placeholder type before it has been deduced is ill-formed, per https://eel.is/c++draft/dcl.spec.auto#general-13
