### PR TITLE
[SPIR-V]: Add SPIR-V extension: SPV_KHR_cooperative_matrix

### LINKED ISSUE #96170: [SPIR-V] Address space casting via a Generic pointer as an intermediary creates a wrong Generic pointer type
When creating a Generic pointer type as an intermediary for address space casting (https://github.com/llvm/llvm-project/blob/b18bf8faaef952323c96e4c6b82f25623073fb1c/llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp#L1061) a wrong type is generated. Namely, the source ptr is treated as if it's a pointee type. We must fetch a pointee type instead first, and use it as a base for creation of a new Generic pointer type.

The next is a reproducer:

```
define spir_kernel void @foo(ptr addrspace(1) %arg) {
entry:
  %p = addrspacecast ptr addrspace(1) %arg to ptr addrspace(3)
  ret void
}
```

spirv-val complain looks like 

```
error: line 28: Expected input and Result Type to point to the same type: PtrCastToGeneric
  %13 = OpPtrCastToGeneric %_ptr_Generic__ptr_CrossWorkgroup_uchar %12
```

As we see a new Generic pointer type points to a pointer and that's wrong.

### PR DESCRIPTION
**Pull request by VyacheslavLevytskyy**
This PR adds SPIR-V extension SPV_KHR_cooperative_matrix that "adds a new set of types known as "cooperative matrix" types, where the storage for and computations performed on the matrix are spread across a set of invocations such as a subgroup" (see https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_cooperative_matrix.asciidoc).

This PR also fixes https://github.com/llvm/llvm-project/issues/96170, a new test cases is attached (llvm/test/CodeGen/SPIRV/transcoding/OpPtrCastToGeneric.ll).

### CODE REVIEW

File: llvm/lib/Target/SPIRV/SPIRVCommandLine.cpp [hunk 1]
```diff
@@ -66,6 +66,8 @@ static const std::map<std::string, SPIRV::Extension::Extension>
          SPIRV::Extension::Extension::SPV_INTEL_function_pointers},
         {"SPV_KHR_shader_clock",
          SPIRV::Extension::Extension::SPV_KHR_shader_clock},
+        {"SPV_KHR_cooperative_matrix",
```
Comment (michalpaszkowski) [inline llvm/lib/Target/SPIRV/SPIRVCommandLine.cpp:69]: SPIRVUsage doc file will also need to be updated

**Review by michalpaszkowski — APPROVED** [review]
