### PR TITLE
[clang][driver] Fix -print-target-triple OS version for apple targets

### LINKED ISSUE #61762: [clang] -print-target-triple doesn't work properly on Apple platforms
```console
$ echo | clang -xc - -###
[...]/bin/clang" "-cc1" "-triple" "arm64-apple-macosx11.0.0" [...]

$ clang -print-target-triple
arm64-apple-darwin22.4.0
```

So we can see that the compiler knows (at some point) that it should be compiling for macosx11.0.0, but `-print-target-triple` doesn't know that yet. That's because `-print-target-triple` is implemented in `HandleImmediateArgs` which is run before the `toolchains::Darwin` object is initialized.

### PR DESCRIPTION
**Pull request by Xazax-hun**
The target needs to be initialized in order to compute the correct target triple from the command line. Without initialized targets the OS component of the triple might not reflect what would be computed by the driver for an actual compiler invocation.

Fixes https://github.com/llvm/llvm-project/issues/61762

### CODE REVIEW

File: clang/test/Driver/darwin-print-target-triple.c [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+// RUN:     --target=arm64-apple-ios -mios-version-min=9 \
+// RUN:     -resource-dir=%S/Inputs/resource_dir 2>&1 \
+// RUN:   | FileCheck --check-prefix=CHECK-CLANGRT-IOS %s
+// CHECK-CLANGRT-IOS: arm64-apple-ios9.0.0
+
+// RUN: %clang -print-target-triple \
+// RUN:     --target=arm64-apple-watchos -mwatchos-version-min=3 \
+// RUN:     -resource-dir=%S/Inputs/resource_dir 2>&1 \
+// RUN:   | FileCheck --check-prefix=CHECK-CLANGRT-WATCHOS %s
+// CHECK-CLANGRT-WATCHOS: arm64-apple-watchos3.0.0
```
Comment (ldionne) [inline clang/test/Driver/darwin-print-target-triple.c:23]: I'm curious to know how this behaves for architectures like `armv7k`. Maybe add this?

```c++
// RUN: %clang -print-target-triple \
// RUN:     --target=armv7k-apple-watchos -mwatchos-version-min=3 \
// RUN:     -resource-dir=%S/Inputs/resource_dir 2>&1 \
// RUN:   | FileCheck --check-prefix=CHECK-CLANGRT-WATCHOS-ARMV7K %s
// CHECK-CLANGRT-WATCHOS-ARMV7K: armv7k-apple-watchos3.0.0
```

That's because I have seen weird behavior with armv7k on watchOS being translated to thumbv7k and causing issues in the past.

**Review by ldionne — APPROVED** [review]
This seems really nice! Again, I don't own the driver but IMO this seems fine to me.

**Review by MaskRay — APPROVED** [review]

**Comment by mstorsjo** [comment]
This broke things for non-darwin targets.

`clang --print-target-triple` is used to evaluate the arch to use for e.g. compiler-rt builtins, and for getting the right subdirectory for per-target runtime directories.

Previously, `clang -target armv7-windows-gnu --print-target-triple` used to output `armv7-unknown-windows-gnu`, while it now outputs `thumbv7-unknown-windows-gnu`. (The `--print-effective-triple` option has printed `thumbv7-unknown-windows-gnu` consistently all the time though.) Making `--print-target-triple` print a `thumbv7` triple makes compiler-rt not build any builtins/runtimes for that, since that arch name is unrecognized there. (I also remember looking into making compiler-rt support `thumbv7` as architecture name, when some normalization attempted to use `--print-effective-triple` at some point, but iirc it wasn't a clear cut thing to do.)

Additionally, having `--print-target-triple` output `thumbv7-unknown-windows-gnu` is wrong when the driver in fact will look for per-target runtimes in a subdirectory named `armv7-unknown-windows-gnu` (this is what the driver printed as path when it failed to find runtimes after this change).

Darwin targets don't use the per-target runtime directory, but if they would do, I doubt that having the OS version appended on those directories would be the right thing to do...

---

Thus, I request we revert this (and will push a revert later today unless we agree on something else) - this breaks things way outside of what was intended in the change itself.

(I don't have a strong opinion on whether the initialization should be kept only for darwin targets, or if a different option than `--print-target-triple` should be used for conveying such things. In one sense, `--print-effective-triple` maybe would be more appropriate? For the arm vs thumb case, that does print the actual `thumbv7` arch already, but for the darwin targets, it doesn't include the OS version right now.)

**Comment by Xazax-hun** [comment]
Hey, thanks for letting me know. Feel free to revert this for now!

**Comment by ldionne** [comment]
@mstorsjo I think you put the finger on something I don't really understand at the moment. What is the relationship between `armv7` and `thumbv7` as a target triple? Is there any documentation on what an "effective triple" is in comparison to a "non-effective triple"?

Separately from this, we noticed that `clang -target armv7k-apple-watchos` would pass `-target thumbv7-apple-watchos` to the frontend, but using `clang -target thumbv7-apple-watchos` directly in the driver doesn't work. Is `thumbv7-apple-watchos` the "effective" triple of `armv7k-apple-watchos`? Why do both spellings exist, and what is each spelling used for?

I know that's a lot of questions, but if you know the answer to any of them, it would shed a lot of light over here :)

**Comment by zmodem** [comment]
I have no idea what's going on here, but we also bisected test failures to this patch: https://crbug.com/360066428

**Comment by mstorsjo** [comment]
> @mstorsjo I think you put the finger on something I don't really understand at the moment. What is the relationship between `armv7` and `thumbv7` as a target triple? Is there any documentation on what an "effective triple" is in comparison to a "non-effective triple"?

Sorry, I'm not sure if there's any formal definition of what Clang considers `--print-effective-triple` vs `--print-target-triple`, neither is exactly what is input. So far, the output of `--print-target-triple` used to be _exactly_ the directory name used for per-target runtime subdirectories, but with this change, it no longer was that.

> Separately from this, we noticed that `clang -target armv7k-apple-watchos` would pass `-target thumbv7-apple-watchos` to the frontend, but using `clang -target thumbv7-apple-watchos` directly in the driver doesn't work. Is `thumbv7-apple-watchos` the "effective" triple of `armv7k-apple-watchos`? Why do both spellings exist, and what is each spelling used for?

I think `thumbv7-apple-watchos` may be the effective triple of `armv7k-apple-watchos` yes - whatever that means.

As a brief background: For the 32 bit ARM execution mode, you can have instructions in two different forms - "ARM" mode, where each instruction is 32 bit, and Thumb mode, where each instruction is 16 bit. Some ARM environments can only execute ARM mode code, some environments can mix both, and some can only have Thumb. Those that can mix, can essentially do this on a per-function basis (so in a single assembly file, you could have some functions be ARM and some be Thumb).

Then, I guess the situation is, when generating code, we output only one or another - and in the lower level LLVM layers, I guess the switch between the two is done by using either an `arm*` or `thumb*` triple. But on the higher levels, things mostly expect to work with triples in the form `arm*` and aren't really expecting to see the `thumb*` triples.

(FWIW, on the topic of whether lower level triples can be fed back to clang as the `-target` argument - Darwin is kinda special in that regard for other architectures as well. E.g. for aarch64, the effective/internal triple is `aarch64-*`, but on the Clang driver level, you're mostly supposed to call it `arm64-*`.)

**Comment by ldionne** [comment]
Thanks for the writeup, this is useful. This leaves me wondering if `arm64-apple-darwin22.4.0` might be the right target triple then, but the effective triple would be e.g. `arm64-apple-macos12.0.0`?
