### PR TITLE
[LLD][ELF] Support OVERLAY NOCROSSREFS

### LINKED ISSUE #128790: [LLD] Implement NOCROSREFS support for overlays in linker script handling of LLD
Consider the following incomplete linker script snippet:

```
OVERLAY <START_ADDRESS>: NOCROSSREFS {
    .overlay.ob1 {*ob1*.o (.text*)}
    .overlay.ob2 {*ob2*.o (.text*)}
 } >SOME_MEMORY

```
LLD fails with `{ expected, but got NOCROSSREFS` while processing this.

Ideally, we would like to match the BFD linker behavior for NOCROSSREFS in this case.

### PR DESCRIPTION
**Pull request by mysterymath**
This allows NOCROSSREFS to be specified in OVERLAY linker script descriptions. This is a particularly useful part of the OVERLAY syntax, since it's very rarely possible for one overlay section to sensibly reference another.

Closes #128790

### CODE REVIEW

File: lld/ELF/ScriptParser.cpp [hunk 1]
```diff
@@ -565,8 +565,17 @@ SmallVector<SectionCommand *, 0> ScriptParser::readOverlay() {
     addrExpr = readExpr();
     expect(":");
   }
-  Expr lmaExpr = consume("AT") ? readParenExpr() : Expr{};
-  expect("{");
+
+  Expr lmaExpr;
+  bool noCrossRefs = false;
+  while (auto tok = till("{")) {
```
Comment (smithp35) [inline lld/ELF/ScriptParser.cpp:571]: Would this permit AT to be used before NOCROSSREFS?

GNU ld documentation https://sourceware.org/binutils/docs/ld.html#Overlay-Description implies that it doesn't.
OVERLAY [start] : [NOCROSSREFS] [AT ( ldaddr )]

Empirically GNU ld accepts:
```
SECTIONS {
  OVERLAY : NOCROSSREFS AT(0x8000)  {
    .text { *(.text*) }
    .data { *(.data*) }
    .rodata { *(.rodata*) }
  }
}
```
But it won't accept
```
SECTIONS {
  OVERLAY : AT(0x8000) NOCROSSREFS   {
    .text { *(.text*) }
    .data { *(.data*) }
    .rodata { *(.rodata*) }
  }
}
```
aarch64-none-elf-ld:overlay.ld:2: syntax error

If I'm right about lld not caring about the order, then we'll accept scripts that GNU ld won't. May be worth sticking to what GNU ld accepts to help portability between toolchains.

File: lld/test/ELF/linkerscript/nocrossrefs.test [hunk 2]
```diff
@@ -50,6 +54,17 @@ NOCROSSREFS(.text .text1 .text2 .data .rodata .data .nonalloc)
 abs = 42;
 NOCROSSREFS_TO(.text .text .text1 .text2 .data .nonalloc)
 
+#--- overlay.t
```
Comment (smithp35) [inline lld/test/ELF/linkerscript/nocrossrefs.test:57]: Could be worth adding : NOCROSSREFS AT(<addr>) as a regression test.

**Review by smithp35 — COMMENTED** [review]
Thanks for adding, looks like a useful addition. Other than a question about order of AT and CROSSREFS this looks good to me.

File: lld/ELF/ScriptParser.cpp (hunk 1 above)
Comment (mysterymath) [reply lld/ELF/ScriptParser.cpp]: Good catch: I "zigged" when I should have "zagged". (Mistook the GNU LD grammar syntax.) Done.

File: lld/test/ELF/linkerscript/nocrossrefs.test (hunk 2 above)
Comment (mysterymath) [reply lld/test/ELF/linkerscript/nocrossrefs.test:57]: I think you meant `AT() NOCROSSREFS`? Done, but in `overlay.test`, since it's more of an overlay parse error than a test of `NOCROSSREFS` functionality.

**Review by MaskRay — APPROVED** [review]
