### PR TITLE
[Clang][Sema] fix crash of attribute transform

### LINKED ISSUE #73619: Clang crash when using lifetimebound attribute
The following code makes clang 17.0 crashes when adding the `[[clang::lifetimebound]]` attribute.

```c++
template<typename T>
struct Bar {
    int* data;

    auto operator[](const int index) const [[clang::lifetimebound]] -> decltype(data[index]) {
        return data[index];
    }
};

int main() {
    Bar<int> b;
}
```

Godbolt link: https://godbolt.org/z/jsaxvKsas

<details><summary>Stack dump</summary>

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-17.0.1/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-13.2.0 -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:12:15: current parser token ';'
2.	<source>:11:12: parsing function body 'main'
3.	<source>:11:12: in compound statement ('{}')
4.	<source>:3:8: instantiating class definition 'Bar<int>'
 #0 0x0000000003349f18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3349f18)
 #1 0x0000000003348044 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3348044)
 #2 0x000000000329c028 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f25e6e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00000000068874ee clang::computeDependence(clang::CXXThisExpr*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x68874ee)
 #5 0x0000000005f45260 clang::Sema::BuildCXXThisExpr(clang::SourceLocation, clang::QualType, bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x5f45260)
 #6 0x000000000639169c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCXXThisExpr(clang::CXXThisExpr*) SemaTemplateInstantiate.cpp:0:0
 #7 0x00000000063a9da7 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
 #8 0x00000000063d42a0 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformMemberExpr(clang::MemberExpr*) SemaTemplateInstantiate.cpp:0:0
 #9 0x00000000063a9977 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#10 0x00000000063a9fc5 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#11 0x00000000063aaaf9 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformArraySubscriptExpr(clang::ArraySubscriptExpr*) SemaTemplateInstantiate.cpp:0:0
#12 0x00000000063a9ed2 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#13 0x00000000063b5bef clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#14 0x00000000063d1275 clang::QualType clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformFunctionProtoType<clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformFunctionProtoType(clang::TypeLocBuilder&, clang::FunctionProtoTypeLoc)::'lambda'(clang::FunctionProtoType::ExceptionSpecInfo&, bool&)>(clang::TypeLocBuilder&, clang::FunctionProtoTypeLoc, clang::CXXRecordDecl*, clang::Qualifiers, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformFunctionProtoType(clang::TypeLocBuilder&, clang::FunctionProtoTypeLoc)::'lambda'(clang::FunctionProtoType::ExceptionSpecInfo&, bool&)) (.constprop.0) SemaTemplateInstantiate.cpp:0:0
#15 0x00000000063b549f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#16 0x00000000063ca95c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformAttributedType(clang::TypeLocBuilder&, clang::AttributedTypeLoc) SemaTemplateInstantiate.cpp:0:0
#17 0x00000000063b5bc7 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) SemaTemplateInstantiate.cpp:0:0
#18 0x00000000063d0307 clang::Sema::SubstFunctionDeclType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, clang::CXXRecordDecl*, clang::Qualifiers, bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x63d0307)
#19 0x00000000063e4d9e clang::TemplateDeclInstantiator::SubstFunctionType(clang::FunctionDecl*, llvm::SmallVectorImpl<clang::ParmVarDecl*>&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x63e4d9e)
#20 0x00000000064304d0 clang::TemplateDeclInstantiator::VisitCXXMethodDecl(clang::CXXMethodDecl*, clang::TemplateParameterList*, std::optional<clang::ASTTemplateArgumentListInfo const*>, clang::TemplateDeclInstantiator::RewriteKind) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x64304d0)
#21 0x00000000063c3405 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x63c3405)
#22 0x00000000063df2e5 clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x63df2e5)
#23 0x000000000645ad1f void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::'lambda'()>(long) SemaType.cpp:0:0
#24 0x0000000005a14cc1 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x5a14cc1)
#25 0x000000000645fa3d clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x645fa3d)
#26 0x000000000645fac5 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x645fac5)
#27 0x000000000645fb90 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, unsigned int) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x645fb90)
#28 0x0000000005c24b96 clang::Sema::ActOnUninitializedDecl(clang::Decl*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x5c24b96)
#29 0x00000000058e86d3 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58e86d3)
#30 0x00000000058fca30 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58fca30)
#31 0x00000000058fddfd clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58fddfd)
#32 0x00000000058fe2df clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58fe2df)
#33 0x00000000059a9a32 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x59a9a32)
#34 0x00000000059aa342 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x59aa342)
#35 0x00000000059ab149 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x59ab149)
#36 0x00000000059ac40a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x59ac40a)
#37 0x00000000058cabc8 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58cabc8)
#38 0x00000000058fcb79 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58fcb79)
#39 0x00000000058c5212 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58c5212)
#40 0x00000000058c632f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#41 0x00000000058cda8f clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58cda8f)
#42 0x00000000058cef0a clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58cef0a)
#43 0x00000000058be95a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x58be95a)
#44 0x00000000044f8b05 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x44f8b05)
#45 0x0000000003dd5f21 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3dd5f21)
#46 0x0000000003d5b9fb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3d5b9fb)
#47 0x0000000003eb5c23 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3eb5c23)
#48 0x0000000000bd50c5 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0xbd50c5)
#49 0x0000000000bce42d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#50 0x0000000003ba7489 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#51 0x000000000329c453 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x329c453)
#52 0x0000000003ba76a9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#53 0x0000000003b6f477 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3b6f477)
#54 0x0000000003b6fe2d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3b6fe2d)
#55 0x0000000003b79d0c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0x3b79d0c)
#56 0x0000000000bd2d31 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0xbd2d31)
#57 0x0000000000acf511 main (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0xacf511)
#58 0x00007f25e6e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#59 0x00007f25e6e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#60 0x0000000000bcdc2e _start (/opt/compiler-explorer/clang-17.0.1/bin/clang+++0xbcdc2e)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

</details>

### PR DESCRIPTION
**Pull request by jcsxky**
Try to fix [issue](https://github.com/llvm/llvm-project/issues/73619)

1. During transforming `FunctionProtoType`, if `ThisContext` is `nullptr` and `CurrentContext` is `ClassTemplateSpecializationDecl`, Constructor of `CXXThisScopeRAII` and `Sema::getCurrentThisType` won't set `CXXThisTypeOverride` of Sema. This will lead to building `this` in `RebuildCXXThisExpr` with a invalid type(NULL type) and cause crash.
2. During transforming attribute type, if `modifiedType` of attribute type is changed, `EquivalentType` need to be transformed. If `EquivalentType` is `FunctionProtoType`, its `ParamVarDecl` will not be copyed(but parameter num does) and will not be instanced in `TransformFunctionTypeParams` since `ParamVarDecl` is `nullptr`. This will lead to crash in `findInstantiationOf`(can't find the instance of `ParamVarDecl`).

This patch tries to fix these issues above.

1. If `CurrentContext` is `ClassTemplateSpecializationDecl`, Use it.
2. Use `EquivalentTypeLoc` instead of `EquivalentType` since it has parameter info. But, if use current `TypeLocBuilder`, it will crash in `TypeLocBuilder::push` since `LastType` is mismatch. Use an auxiliary `TypeLocBuilder` instead and get transformed `EquivalentType`.

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -7083,8 +7087,9 @@ QualType TreeTransform<Derived>::TransformAttributedType(
       modifiedType != oldType->getModifiedType()) {
     // TODO: this is really lame; we should really be rebuilding the
     // equivalent type from first principles.
```
Comment (cor3ntin) [inline clang/lib/Sema/TreeTransform.h:7089]: This comment would no longer apply, would it?

File: clang/test/Sema/attr-lifetimebound-no-crash.cpp [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+    auto operator[](const int index) const [[clang::lifetimebound]] -> decltype(data[index]) {
+        return data[index];
+    }
+};
+
+int main() {
+    Bar<int> b;
+    (void)b[2];
+}
```
Comment (cor3ntin) [inline clang/test/Sema/attr-lifetimebound-no-crash.cpp:17]: Missing new line

File: clang/lib/Sema/TreeTransform.h (hunk 1 above)
Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h:7089]: Indeed, it has been rebuilt using `TypeLoc` like `ModifiedType`.

File: clang/test/Sema/attr-lifetimebound-no-crash.cpp (hunk 2 above)
Comment (jcsxky) [reply clang/test/Sema/attr-lifetimebound-no-crash.cpp]: Done

File: clang/lib/Sema/TreeTransform.h [hunk 3]
```diff
@@ -7081,10 +7085,10 @@ QualType TreeTransform<Derived>::TransformAttributedType(
   // FIXME: dependent operand expressions?
   if (getDerived().AlwaysRebuild() ||
       modifiedType != oldType->getModifiedType()) {
-    // TODO: this is really lame; we should really be rebuilding the
-    // equivalent type from first principles.
-    QualType equivalentType
-      = getDerived().TransformType(oldType->getEquivalentType());
+    TypeLocBuilder AuxiliaryTLB;
+    AuxiliaryTLB.reserve(TL.getFullDataSize());
```
Comment (cor3ntin) [inline clang/lib/Sema/TreeTransform.h:7089]: an alternative might be to call 
`TLB.TypeWasModifiedSafely(result)` (after the call to `getAttributedType` below).
I wonder if @AaronBallman  has a better alternative

Comment (erichkeane) [reply clang/lib/Sema/TreeTransform.h:7089]: Right, yeah, the location shouldn't have changed, just the type itself.  I think the suggestions above are the way to go.

Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h:7089]: Thanks for your remind! Fixed.

Comment (AaronBallman) [reply clang/lib/Sema/TreeTransform.h:7089]: I don't think we need to use `AuxiliaryTLB` any longer, do we?

Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h:7089]: I‘m afraid not. It will crash on `TypeLocBuilder::pushImpl` with the new added test case since `TLast == LastTy` assert failed if we reuse `TLB`. Because current `FunctionProtoType` can't be child of other type node.

Comment (AaronBallman) [reply clang/lib/Sema/TreeTransform.h:7089]: Ah, you're right, we do still need to do that dance it seems.

**Review by AaronBallman — APPROVED** [review]
LGTM but please wait in case @erichkeane has final thoughts.

File: clang/lib/Sema/TreeTransform.h (hunk 3 above)
Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h:7089]: @cor3ntin @AaronBallman @erichkeane The test on windows platform failed with `TLB.TypeWasModifiedSafely(result);`. Maybe we shouldn't change `LastTy` of `TLB` since we just transform `EquivalentType` using `AuxiliaryTLB` and haven't touched `TLB`.

Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h:7089]: I tested `address-spaces.cpp` on linux and `TLast == LastTy` assert also failed. Don't know why the test on linux platform passed.

Comment (AaronBallman) [reply clang/lib/Sema/TreeTransform.h:7089]: Yeah, I was thinking we didn't need to use `AuxiliaryTLB` and could instead call `TypeWasModifiedSafely` but it seems like we need the code as you originally had it (using `AuxiliaryTLB` but not calling `TypeWasModifiedSafely`). Sorry for the run-around!

File: clang/lib/Sema/TreeTransform.h [hunk 4]
```diff
@@ -6124,7 +6124,11 @@ QualType TreeTransform<Derived>::TransformFunctionProtoType(
       //   "pointer to cv-qualifier-seq X" between the optional cv-qualifer-seq
       //   and the end of the function-definition, member-declarator, or
       //   declarator.
-      Sema::CXXThisScopeRAII ThisScope(SemaRef, ThisContext, ThisTypeQuals);
+      auto *RD =
+          dyn_cast_or_null<CXXRecordDecl>(SemaRef.getCurLexicalContext());
+      Sema::CXXThisScopeRAII ThisScope(
+          SemaRef, ThisContext == nullptr && nullptr != RD ? RD : ThisContext,
+          ThisTypeQuals);
```
Comment (AaronBallman) [inline clang/lib/Sema/TreeTransform.h:6131]:
```suggestion
      auto *RD =
          dyn_cast<CXXRecordDecl>(SemaRef.getCurLexicalContext());
      Sema::CXXThisScopeRAII ThisScope(
          SemaRef, !ThisContext && RD ? RD : ThisContext,
          ThisTypeQuals);
```

**Review by AaronBallman — COMMENTED** [review]
Please be sure to add a release note about the fix to clang/docs/ReleaseNotes.rst.

File: clang/lib/Sema/TreeTransform.h (hunk 4 above)
Comment (jcsxky) [reply clang/lib/Sema/TreeTransform.h]: Code Fixed and release note has been added.

**Comment by cor3ntin** [comment]
There seems to be an issue with the rebasing of the PR.
As we branch clang 18, the new changelog (for 19) being empty is expected

**Comment by jcsxky** [comment]
> There seems to be an issue with the rebasing of the PR. As we branch clang 18, the new changelog (for 19) being empty is expected

I try to merge this PR and found `ReleaseNotes.rst` is changed because of clang-19 initialize. I don't know where should I add the release note.

**Comment by shafik** [comment]
It looks like this commit is responsible for https://github.com/llvm/llvm-project/issues/148325

**Comment by aaronpuchert** [comment]
Interestingly this also fixes compilation errors, not just crashes. Clang 18 rejects some code in libstdc++ 16 that Clang 19 and GCC accept:

```
/usr/lib64/gcc/x86_64-suse-linux/16/../../../../include/c++/16/bits/stl_iterator.h:1337:19: error: member access into incomplete type 'const __normal_iterator<const char *, basic_string<char>>'
 1337 |         -> decltype(__lhs.base() - __rhs.base())
      |                          ^
/usr/lib64/gcc/x86_64-suse-linux/16/../../../../include/c++/16/bits/basic_string.h:4018:37: note: in instantiation of template class '__gnu_cxx::__normal_iterator<const char *, std::basic_string<char>>' requested here
 4018 |     { return std::move(__rhs.insert(0, __lhs)); }
      |                                     ^
/usr/lib64/gcc/x86_64-suse-linux/16/../../../../include/c++/16/system_error:568:36: note: in instantiation of function template specialization 'std::operator+<char, std::char_traits<char>, std::allocator<char>>' requested here
  568 |     : runtime_error(__what + (": " + __ec.message())), _M_code(__ec) { }
      |                                    ^
/usr/lib64/gcc/x86_64-suse-linux/16/../../../../include/c++/16/bits/stl_iterator.h:1026:11: note: definition of '__gnu_cxx::__normal_iterator<const char *, std::basic_string<char>>' is not complete until the closing '}'
 1026 |     class __normal_iterator
      |           ^
```

The error disappears with this commit.
