### PR TITLE
[clang] Fix a crash when default argument is passed to an explicit object parameter

### LINKED ISSUE #176639: [clang] still crashes in CheckArityMismatch since clang-19
Related issue (already fixed): https://github.com/llvm/llvm-project/issues/173943

Reproducer:
https://godbolt.org/z/YxGaG49E8
```cpp
struct S {
  void operator()(this S =)
};

void foo() {
  S s{};
  s(0);
}
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/Sema/SemaOverload.cpp:12125: bool CheckArityMismatch(clang::Sema&, clang::OverloadCandidate*, unsigned int, bool): Assertion `(Cand->FailureKind == ovl_fail_too_few_arguments) || (Cand->FailureKind == ovl_fail_bad_deduction && Cand->DeductionFailure.getResult() == TemplateDeductionResult::TooFewArguments)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:7:6: current parser token ')'
2.	<source>:5:12: parsing function body 'foo'
3.	<source>:5:12: in compound statement ('{}')
 #0 0x000000000430d598 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x430d598)
 #1 0x000000000430a9f4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x430a9f4)
 #2 0x000000000424ccc8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fe796c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007fe796c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007fe796c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007fe796c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007fe796c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007fe796c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000000000733a0c8 CheckArityMismatch(clang::Sema&, clang::OverloadCandidate*, unsigned int, bool) (.constprop.0) SemaOverload.cpp:0:0
#10 0x00000000073812d3 clang::OverloadCandidateSet::NoteCandidates(clang::Sema&, llvm::ArrayRef<clang::Expr*>, llvm::ArrayRef<clang::OverloadCandidate*>, llvm::StringRef, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x73812d3)
#11 0x0000000007382581 clang::OverloadCandidateSet::NoteCandidates(std::pair<clang::SourceLocation, clang::PartialDiagnostic>, clang::Sema&, clang::OverloadCandidateDisplayKind, llvm::ArrayRef<clang::Expr*>, llvm::StringRef, clang::SourceLocation, llvm::function_ref<bool (clang::OverloadCandidate&)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7382581)
#12 0x000000000738e37b clang::Sema::BuildCallToObjectOfClassType(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x738e37b)
#13 0x0000000006fe6154 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fe6154)
#14 0x0000000006feb0ac clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6feb0ac)
#15 0x0000000006ae9a27 clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae9a27)
#16 0x0000000006ae293a clang::Parser::ParseCastExpression(clang::CastParseKind, bool, bool&, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae293a)
#17 0x0000000006ae4b97 clang::Parser::ParseCastExpression(clang::CastParseKind, bool, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae4b97)
#18 0x0000000006ae4c29 clang::Parser::ParseAssignmentExpression(clang::TypoCorrectionTypeBehavior) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae4c29)
#19 0x0000000006ae9209 clang::Parser::ParseExpression(clang::TypoCorrectionTypeBehavior) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ae9209)
#20 0x0000000006b6ed59 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b6ed59)
#21 0x0000000006b66204 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b66204)
#22 0x0000000006b66be6 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b66be6)
#23 0x0000000006b6f52e clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b6f52e)
#24 0x0000000006b6fd7a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b6fd7a)
#25 0x0000000006a75f4b clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a75f4b)
#26 0x0000000006aac3bd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6aac3bd)
#27 0x0000000006a690ab clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a690ab)
#28 0x0000000006a6989f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a6989f)
#29 0x0000000006a716ca clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a716ca)
#30 0x0000000006a72665 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a72665)
#31 0x0000000006a536ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a536ea)
#32 0x0000000004c75558 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c75558)
#33 0x0000000004f6f965 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f6f965)
#34 0x0000000004eef33e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4eef33e)
#35 0x000000000506a5dd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x506a5dd)
#36 0x0000000000ddd1de cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xddd1de)
#37 0x0000000000dd3baa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#38 0x0000000000dd3d2d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#39 0x0000000004ce8a99 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#40 0x000000000424d164 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x424d164)
#41 0x0000000004ce90af clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#42 0x0000000004ca9a82 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ca9a82)
#43 0x0000000004caaa2e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4caaa2e)
#44 0x0000000004cb1e75 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4cb1e75)
#45 0x0000000000dd9551 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd9551)
#46 0x0000000000c96bf4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc96bf4)
#47 0x00007fe796c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#48 0x00007fe796c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#49 0x0000000000dd3645 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd3645)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

Goes back to clang-19:
https://godbolt.org/z/MGzzh4qqE

### PR DESCRIPTION
**Pull request by hax0kartik**
This is an invalid usecase and we should mark it as such after emitting a Diagnostic. Fixes #176639.

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
LGTM but please give @Fznamznon time to re-review too

**Review by Fznamznon — APPROVED** [review]
Thanks!

**Comment by cor3ntin** [comment]
There seems to be test failures 

```
T06:40:53.4093969Z /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/23/include -nostdsysteminc -fsyntax-only -std=c++2b -Woverloaded-virtual /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/SemaCXX/cxx2b-deducing-this.cpp -verify
2026-01-31T06:40:53.4099000Z # executed command: /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/23/include -nostdsysteminc -fsyntax-only -std=c++2b -Woverloaded-virtual /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/SemaCXX/cxx2b-deducing-this.cpp -verify
2026-01-31T06:40:53.4101633Z # .---command stderr------------
2026-01-31T06:40:53.4102374Z # | error: 'expected-error' diagnostics seen but not expected: 
2026-01-31T06:40:53.4104074Z # |   File /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/SemaCXX/cxx2b-deducing-this.cpp Line 1470: expected '}'
2026-01-31T06:40:53.4105378Z # | error: 'expected-note' diagnostics seen but not expected: 
2026-01-31T06:40:53.4106730Z # |   File /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/SemaCXX/cxx2b-deducing-this.cpp Line 1434: to match this '{'
2026-01-31T06:40:53.4107879Z # | 2 errors generated.
2026-01-31T06:40:53.4108277Z # `-----------------------------
2026-01-31T06:40:53.4108713Z # error: command failed with exit status: 1
2026-01-31T06:40:53.4109058Z 
2026-01-31T06:40:53.4109459Z --

```

**Comment by hax0kartik** [comment]
Hi, fixed now!

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp [hunk 1]
```diff
@@ -1431,6 +1431,30 @@ namespace ConstexprBacktrace {
...
+          // expected-error@-2 {{expected expression}}
+};
+
+void foo() {
+  S s{};
+  s(0); // expected-error {{no matching function for call to object of type 'S'}}
+}
+
+struct S2 {
+  void operator()(this S2 = S2 {}){} // expected-error {{the explicit object parameter cannot have a default argument}}
```
Comment (shafik) [inline clang/test/SemaCXX/cxx2b-deducing-this.cpp]: I think another useful test would have been `{}` alone as well.

**Review by shafik — COMMENTED** [review]
Thank you for the quick test
