### PR TITLE
[LTO] Fix a crash with thin LTO caching and asm output

### LINKED ISSUE #138194: Crash in lld with thin LTO cache and assembly output
After #136121 is merged, thin LTO with assembly output with cache crashes lld. A test case is basic:

`int main() { return 0; }`

```
clang -c main.c -O2 -flto=thin -o main.o
ld.lld --thinlto-cache-dir=. --lto-emit-asm -e main main.o
```
The cache directory should not have cached output files.

The output stream in `LTOBackend: codegen()` is of type `CacheStream`, defined in Caching.cpp. The commit function of this class deletes the underlying `raw_pwrite_stream` (OS).  With LTO and assembly output, MCAsmStreamer is created as an output streamer and it also holds a raw pointer to `raw_pwrite_stream` indirectly through a `formatted_raw_output` wrapper. In the `MCAsmStreamer` destructor, `formatted_raw_ostream` calls `flush()` on a deleted object.

A simple fix would be to delete the LTO pipeline before the stream commit function is called in LTOBackend.cpp: codegen().

### PR DESCRIPTION
**Pull request by quic-akaryaki**
The commit function of CacheFile deletes the underlying raw stream. Some output streamers may hold a pointer to it, which in this case will outlive the stream object. In particular, MCAsmStreamer keeps the pointer to the raw stream though formatted_raw_stream, which calls flush() in its destructor. If commit is called before MCAsmStreamer destruction, it will access freed memory.

Fixes: #138194.

### CODE REVIEW

**Review by nikic — APPROVED** [review]

**Review by nikic — COMMENTED** [review]
Is it possible to add a test for this? (At least one that would fail in an asan build?)

**Comment by teresajohnson** [comment]
Is this fall out of https://github.com/llvm/llvm-project/pull/136121? If so, I wonder if that PR should be reverted instead - it turns out that went in without a full review / approval, and if it is causing subtle bugs I would prefer to revert that one.

**Comment by quic-akaryaki** [comment]
> Is it possible to add a test for this? (At least one that would fail in an asan build?)

I have added a test.

**Comment by quic-akaryaki** [comment]
> Is this fall out of #136121? If so, I wonder if that PR should be reverted instead - it turns out that went in without a full review / approval, and if it is causing subtle bugs I would prefer to revert that one.

I don't have a strong opinion, someone has to make a decision. If #136121 is reverted, I would like to keep the test.

**Comment by teresajohnson** [comment]
> > Is this fall out of #136121? If so, I wonder if that PR should be reverted instead - it turns out that went in without a full review / approval, and if it is causing subtle bugs I would prefer to revert that one.
> 
> I don't have a strong opinion, someone has to make a decision. If #136121 is reverted, I would like to keep the test.

Keeping the test is good. What is the failure mode of the test without your fix? I've asked for a revert of PR136121 as it was supposed to make error handling easier, but here it sounds like there was a much more subtle issue produced by that change.

**Comment by quic-akaryaki** [comment]
> > > Is this fall out of #136121? If so, I wonder if that PR should be reverted instead - it turns out that went in without a full review / approval, and if it is causing subtle bugs I would prefer to revert that one.
> > 
> > 
> > I don't have a strong opinion, someone has to make a decision. If #136121 is reverted, I would like to keep the test.
> 
> Keeping the test is good. What is the failure mode of the test without your fix? I've asked for a revert of PR136121 as it was supposed to make error handling easier, but here it sounds like there was a much more subtle issue produced by that change.

Without the "fix", the test crashes.

**Review by anjenner — APPROVED** [review]

File: llvm/lib/LTO/LTOBackend.cpp [hunk 1]
```diff
@@ -439,27 +439,33 @@ static void codegen(const Config &Conf, TargetMachine *TM,
...
-    Conf.PreCodeGenPassesHook(CodeGenPasses);
-  if (TM->addPassesToEmitFile(CodeGenPasses, *Stream->OS,
-                              DwoOut ? &DwoOut->os() : nullptr,
-                              Conf.CGFileType))
-    report_fatal_error("Failed to setup codegen");
-  CodeGenPasses.run(Mod);
-
-  if (DwoOut)
-    DwoOut->keep();
+  // Create the LTO pipeline in its own scope so it gets deleted before
```
Comment (teresajohnson) [inline llvm/lib/LTO/LTOBackend.cpp:442]: s/LTO/CodeGen/

File: llvm/lib/LTO/LTOBackend.cpp [hunk 2]
```diff
@@ -439,27 +439,33 @@ static void codegen(const Config &Conf, TargetMachine *TM,
...
+  // Stream->commit() is called. The commit function of CacheFile deletes
```
Comment (teresajohnson) [inline llvm/lib/LTO/LTOBackend.cpp:443]: s/CacheFile/CachedFileStream/

However, can you clarify the sequence of events causing the crash? Looking at PR136121 and CachedFileStream::commit, that function doesn't actually delete anything. I'm also unclear on how deleting the codegen pass manager early prevents use after the call to commit() further below.

**Review by teresajohnson — CHANGES_REQUESTED** [review]
Looking at this again and at the commit function, I'm not really sure how they are related. Can you clarify (see questions below)?

File: llvm/lib/LTO/LTOBackend.cpp (hunk 2 above)
Comment (anjenner) [reply llvm/lib/LTO/LTOBackend.cpp:443]: CachedFileStream::commit calls OS.reset() which deletes the underlying raw stream. A pointer to this stream is kept by the formatted_raw_ostream created by CodeGenTargetMachineImpl::createMCStreamer(). This is then kept by the MCAsmStreamer object. https://github.com/llvm/llvm-project/pull/136121 does change the point at which the deletion of the stream happens since the legacy::PassManager object is destructed before the std::unique_ptr<CachedFileStream> (since the constructor of the former happens later). With https://github.com/llvm/llvm-project/pull/136121 the commit happens before the legacy::PassManager destructor (and hence the MCAsmStreamer destructor, and hence the formatted_raw_stream destructor, and hence the flush() call). This PR causes the legacy::PassManager destructor to be called before the commit operation.

I have checked the other uses of CachedFileStream::commit() for similar lifetime issues, and did not find any.

Comment (teresajohnson) [reply llvm/lib/LTO/LTOBackend.cpp:443]: > CachedFileStream::commit calls OS.reset() which deletes the underlying raw stream

I don't see this?

Ah - the OS.reset() call is in derived class CacheStream::commit, so I missed this earlier (not in the base CachedFileStream nor "CacheFile" noted in the comments of this PR).

The ownership issue and fix seem fragile to me - how do other users of CacheStream avoid this lifetime issue?

Comment (anjenner) [reply llvm/lib/LTO/LTOBackend.cpp:443]: This kind of ownership issue is unfortunately a common pitfall of C++ - short of rewriting the entire compiler in Rust, there isn't really a general way for object A to protect itself against object B taking a pointer to one of A's sub-objects C that outlasts the lifetime that A expected. However, it's no more fragile than it was before https://github.com/llvm/llvm-project/pull/136121 - if the legacy::PassManager constructor had been moved to before the std::unique_ptr&lt;CachedFileStream&gt; constructor, this problem would have been seen even without https://github.com/llvm/llvm-project/pull/136121 .

As for the other users of CacheStream, I just checked that there was no object constructed after the std::unique_ptr&lt;CachedFileStream&gt; constructor which could outlast the commit() call.

Comment (teresajohnson) [reply llvm/lib/LTO/LTOBackend.cpp:443]: > However, it's no more fragile than it was before https://github.com/llvm/llvm-project/pull/136121 - if the legacy::PassManager constructor had been moved to before the std::unique_ptr<CachedFileStream> constructor, this problem would have been seen even without https://github.com/llvm/llvm-project/pull/136121 .

This isn't really the case the way the APIs are set up, however, because the MCAsmStreamer constructor takes an existing raw_pwrite_stream passed down via addPassesToEmitFile(). CacheFileStream is the owner of that raw_pwrite_stream, and which is created at the same time as CacheStream in the caching code at https://github.com/llvm/llvm-project/blob/f4853d7a25e093ac1b69959264a90f6a2326aefe/llvm/lib/Support/Caching.cpp#L169-L170.

With the change to add the destruction in CacheStream::commit, the lifetime of the underlying raw_pwrite_stream has been somewhat artificially shortened, leading to the non-overlapping lifetimes. Ideally MCAsmStreamer would not become the owner of an object that depends on the lifetime of an object it doesn't own, but that would require quite a bit of change to the interfaces of those functions, which have presumably existed that way for a long time.

Could the original issue be addressed by calling flush() on the owned raw_pwrite_stream in CacheStream::commit() instead of destructing it? If you look at the construction of the raw_fd_ostream object in the code I linked above, it's specifying that the file shouldn't even be closed on destruction, so all it is doing is the flush() afaict.

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp:443]: > s/CacheFile/CachedFileStream/
> 
> However, can you clarify the sequence of events causing the crash? Looking at PR136121 and CachedFileStream::commit, that function doesn't actually delete anything. I'm also unclear on how deleting the codegen pass manager early prevents use after the call to commit() further below.

Sorry it should have been CacheStream. I tried to describe the crash (briefly) in the associated bug #138194. I don't know why handling the stream is done this way. Closing the stream in the commit function seems the most suspicious to me, But I don't know what depends on the current behavior.

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp:443]: It seems to me that MCAsmStreamer should not call flush() on the stream because it's only given a pointer to a base class created by someone else and it does not know the semantics of the actual concrete object. It should be safe to assume that MCAsmStreamer only writes to the stream and the actual owner closes the stream when appropriate and makes sure that the writes make it to the underlying file. I'm not sure if CacheStream should close the stream or just flush it but closing it may be a protection against accidental writing after commit(). I will experiment with this.

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp:443]: My analysis above is incorrect. The problem is not because of calling flush() on the raw_ostream but on formatted_raw_ostream, which is legally owned by MCAsmStreamer. There is pending data in the formatted_raw_ostream at the time of MCAsmStreamer destruction and the destructor of formatted_raw_ostream tries to write this data to raw_ostream (TheStream).
So the problem is that MCAsmStreamer writes to the stream during its destruction but by this time, the cached stream has been committed. Regardless of lifetime issues this can't work. It seems #136121 requires more extensive changes from the API users, in particular, to make sure that the stream is not written after explicitly calling commit().

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp:443]: I think the primary question is if we are ok with the API change in #136121. Not only it requires the user to explicitly call commit() but also make sure to write all data before calling commit. There requirements are reasonable but require more explicit work, which previously was hidden in destructors. If that is fine, there is no way around other than flushing data from MCAsmStreamer either by destroying it before commit() (how I did here) or by adding another API. In that case we can keep #136121 and add this one on top because this seems to me like the easiest fix. If we want to revert and reimplement #136121, please integrate my changes from this PR along with the test.

**Comment by quic-akaryaki** [comment]
The forced push is just to edit the comment as requested by @teresajohnson

File: llvm/lib/LTO/LTOBackend.cpp (hunk 2 above)
Comment (teresajohnson) [reply llvm/lib/LTO/LTOBackend.cpp]: My suggestion above was to change CacheStream::commit() to call flush() instead of resetting/destructing the owned raw_pwrite_stream. Does that not fix the issue?

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp]: CacheStream::commit() cannot call flush() because the object that's being flushed is not accessible from CacheStream. There are two stream objects here.
MCAsmStreamer owns a pointer to `formatted_raw_ostream` (OS). The `formatted_raw_ostream` instance internally has a pointer to a non-owned object of type `raw_ostream`. The latter object is created before the codegen pipeline is created and is passed to MCAsmStreamer which in turn, passes it to the owned `formatted_raw_ostream` object.
So it looks like this:
CachedFileStream -> raw_ostream
PassManager -> ... -> MCAsmStreamer -> formatted_raw_ostream -> raw_ostream (same object as above)
The flush() method is in formatted_raw_ostream.
It may be possible to call flush() through the PassManager, but we have traverse the chain of pointers reaching MCAsmStreamer, but not sure if this is practical. Now, this is achieved through destructors.

Comment (teresajohnson) [reply llvm/lib/LTO/LTOBackend.cpp]: But formatted_raw_ostream doesn't define its own flush(). Its destructor calls flush() which is the base raw_ostream::flush().

Comment (quic-akaryaki) [reply llvm/lib/LTO/LTOBackend.cpp]: > But formatted_raw_ostream doesn't define its own flush(). Its destructor calls flush() which is the base raw_ostream::flush().

Yes, buffering is implemented in the base class (raw_ostream) but it's used by the formatted_raw_ostream object (outer stream). What happens when the buffer is not empty is raw_ostream calls virtual write_imp() which is (re?)defined in formatted_raw_ostream to write pending data to the other (inner) stream. 
Sorry it's so complicated.

Comment (anjenner) [reply llvm/lib/LTO/LTOBackend.cpp]: I would like to strongly advocate for leaving PR136121 in place and for merging this PR. My reasoning is as follows:
1. There is a general principle in C++ that destructors should never do anything except release resources - if they perform operations that can fail then those errors cannot be handled except out-of-band (tearing down the process). PR136121 improves the localCache API in this respect. While doing so has uncovered other instances of destructors doing non-release operations, that in itself is not a reason to abandon this engineering principle.
2. While most of the callers of the new commit() function currently still call report_fatal_error on the result (as I wanted to keep PR136121 as unimpactful as possible), they may wish to improve their error-handling in the future and PR136121 is a necessary component of that. The motivating case is an out-of-tree use https://github.com/ROCm/llvm-project/blob/amd-staging/amd/comgr/src/comgr-cache.cpp for which tearing down the process would be highly undesirable - if that was an unavoidable aspect of the localCache API then ROCm would need to have its own fork of the localCache API (that didn't do the commit in the destructor) with the maintenance headaches that would incur. It seems likely to me that other users of localCache will in the future realise that they have similar requirements.
3. Reverting PR136121 now would also mean that the other pieces of code that have had to be changed in response to PR136121 would have to be changed back - it would be more churn.
4. I stand by what I said about there being latent fragility in the codegen() function in llvm/lib/LTO/LTOBackend.cpp . The MCAsmStreamer object is destroyed (and hence the formatted_raw_ostream object) when CodeGenPasses is destroyed. If the CodeGenPasses constructor were in the future to be moved above the Stream constructor then it would be destroyed after the CachedFileStream (the order in which these destructors are run is the reverse of the order in which the corresponding constructors are run - the position of the addPassesToEmitFile() call is not relevant as the end of the lifetime of the MCAsmStreamer object is tied to the end of the lifetime of the legacy::PassManager object and hence the time when that object was constructed). So reverting PR136121 wouldn't actually solve the latent fragility that is the purported reason for reverting it.

Comment (teresajohnson) [reply llvm/lib/LTO/LTOBackend.cpp]: I'll go ahead and approve this PR to address the crash, because I think the underlying issue lies in the asm printing passes and their setup.

Specifically, createMCStreamer creates the formatted_raw_ostream, which stores a pointer to the provided raw_ostream reference that it doesn't own, and addAsmPrinter which in turn stores that in the pass manager. All clients of addPassesToEmitFile, which takes the raw_ostream and pass manager references and invokes these APIs, currently have to ensure that the lifetime of the provided raw_ostream object outlasts the lifetime of the pass manager.

> I stand by what I said about there being latent fragility in the codegen() function in llvm/lib/LTO/LTOBackend.cpp . The MCAsmStreamer object is destroyed (and hence the formatted_raw_ostream object) when CodeGenPasses is destroyed. If the CodeGenPasses constructor were in the future to be moved above the Stream constructor then it would be destroyed after the CachedFileStream
> the position of the addPassesToEmitFile() call is not relevant

Yes, I see what you mean. It is relevant to the problem as it takes both the raw_ostream and the pass manager, and it is down in its handling where the latter takes a pointer to the former, but not to the relative ordering of their construction/destruction. As noted earlier, this issue is not specific to the LTOBackend codegen(), the potential for a problem exists in any client of this code gen pass setup.

**Review by teresajohnson — APPROVED** [review]
