### PR TITLE
[clang] Fix the local parameter of void type inside the `Requires` expression.

### LINKED ISSUE #109538: Requires expression with local parameter of void type
This program is accepted by Clang (`requires` is evaluated as `true`):
```
static_assert( requires(void t) {t;} );
```
but rejected by GCC and MSVC with hard error: https://gcc.godbolt.org/z/W7f3zqbMb

If it were evaluated as `false`, it would be more understandable.

### PR DESCRIPTION
**Pull request by c8ef**
Fixes #109538.

In this patch, we introduce diagnostic for required expression parameters in the same way as function parameters, fix the issue of handling void type parameters, and align the behavior with GCC and other compilers.

### CODE REVIEW

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 1]
```diff
@@ -9509,6 +9509,19 @@ Sema::ActOnStartRequiresExpr(SourceLocation RequiresKWLoc,
...
+        Diag(Param->getBeginLoc(), diag::err_void_only_param);
+        Body->setInvalidDecl();
+      } else if (Param->getIdentifier()) {
+        Diag(Param->getBeginLoc(), diag::err_param_with_void_type);
+        Body->setInvalidDecl();
+      } else if (Param->getType().hasQualifiers()) {
+        Diag(Param->getBeginLoc(), diag::err_void_param_qualified);
+        Body->setInvalidDecl();
+      }
+    }
```
Comment (mizvekov) [inline clang/lib/Sema/SemaExprCXX.cpp:9523]: Can we unify these with the parameter type checks in SemaType?

Also, it would make sense to perform the same error recovery here, which is to just adjust these parameter types
to `int`, or perhaps some other error recovery, but consistently between requires local parameters and function parameters.

I don't think it's helpful to mark the requires body as invalid, but in some scenarios we can mark the parameter itself as invalid, if needed.

Comment (zyn0217) [reply clang/lib/Sema/SemaExprCXX.cpp:9523]: I think the invalidity of the Decl should be used to indicate the "unsatisfied" flag such that the constant expression would result in a false value. That said, marking the parameters as invalid should also work.

Note that we don't seem ever to use the invalid flag. I think you need to examine that flag in `RequiresExpr`'s constructor.

File: clang/test/SemaCXX/invalid-requirement-requires-parameter.cpp [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// RUN: %clang -fsyntax-only -std=c++2a -Xclang -verify %s
```
Comment (zyn0217) [inline clang/test/SemaCXX/invalid-requirement-requires-parameter.cpp:1]: Can you move the test to `clang/test/CXX/expr/expr.prim/expr.prim.req/requires-expr.cpp`? I don't think this issue merits a new one

**Review by zyn0217 — COMMENTED** [review]
There should be a release note :)

I think I agree with @mizvekov's idea of merging the parameter checks into SemaType; we can probably in part reuse GetTypeForDeclarator. I would appreciate it if we can see some exploration here.

Another thing is that we need to make sure the values of such require expressions are false, aligning with other compilers.

**Comment by mizvekov** [comment]
> I'm wondering what level of granularity we should aim for when reusing the current implementation in `GetTypeForDeclarator`?

You can perhaps extract just the parts that are common between both use cases into a separate function, or another possible approach would be to reuse the whole thing, but then add an extra mode parameter which turns off some checks for the requires local parameters.

**Comment by zyn0217** [comment]
> Therefore, I recommend adding the void parameter check directly into SemaExprCXX for an immediate fix. If there's a future need to consolidate the checks, we can consider refactoring later.

That works for me if it turns out to take much more effort than our anticipation,  although it's really a shame for us to end up strewing the check three times.

**Comment by mizvekov** [comment]
Same then, go ahead, but please make sure the error handling strategies don't diverge unnecessarily.

**Comment by zyn0217** [comment]
> ```
> static_assert(requires(this int) { true; });
> ```

The grammar doesn't appear to disallow the explicit object parameter in a requires expression, see https://eel.is/c++draft/expr.prim.req#nt:requirement-parameter-list.

But the usage is indeed suspicious to me. We probably need a CWG issue? @cor3ntin @mizvekov

**Review by zyn0217 — APPROVED** [review]
Makes sense to me. Thanks

Please wait for other folks a day or two in case they have different opinions.

**Review by erichkeane — APPROVED** [review]

File: clang/lib/AST/ExprConcepts.cpp [hunk 3]
```diff
@@ -153,6 +153,10 @@ RequiresExpr::RequiresExpr(ASTContext &C, SourceLocation RequiresKWLoc,
   std::copy(Requirements.begin(), Requirements.end(),
             getTrailingObjects<concepts::Requirement *>());
   RequiresExprBits.IsSatisfied |= Dependent;
+  RequiresExprBits.IsSatisfied &=
+      llvm::none_of(LocalParameters, [](const ParmVarDecl *Param) {
+        return Param->isInvalidDecl();
+      });
```
Comment (mizvekov) [inline clang/lib/AST/ExprConcepts.cpp:159]: I don't understand why we need to say the requires expression is not satisfied if any of the parameters are invalid. This is the consequence of an error, which was already emitted.

This does not seem to lead to better error recovery.

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 4]
```diff
@@ -9509,6 +9509,19 @@ Sema::ActOnStartRequiresExpr(SourceLocation RequiresKWLoc,
...
+    if (Param->getType()->isVoidType()) {
+      if (LocalParameters.size() > 1) {
+        Diag(Param->getBeginLoc(), diag::err_void_only_param);
+        Param->setInvalidDecl();
+      } else if (Param->getIdentifier()) {
+        Diag(Param->getBeginLoc(), diag::err_param_with_void_type);
+        Param->setInvalidDecl();
+      } else if (Param->getType().hasQualifiers()) {
+        Diag(Param->getBeginLoc(), diag::err_void_param_qualified);
+        Param->setInvalidDecl();
```
Comment (mizvekov) [inline clang/lib/Sema/SemaExprCXX.cpp:9521]: The error recovery which we apply for function parameters in these cases is to proceed with `int` as the parameter type, and not mark the parameters as invalid.
Why are we doing different here?

File: clang/lib/AST/ExprConcepts.cpp (hunk 3 above)
Comment (zyn0217) [reply clang/lib/AST/ExprConcepts.cpp:159]: I asked author to add it because I saw GCC evaluating such expressions as false.

https://gcc.godbolt.org/z/MYz1oa1TT

This is seemingly more of an open question IMO, given that msvc & edg don't agree with gcc.

File: clang/lib/Sema/SemaExprCXX.cpp (hunk 4 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaExprCXX.cpp:9521]: Indeed performing a recovery would benefit source tools like clangd.

Probably, we can continue as if it were an int and give up evaluating the whole expression to false - again, this is an open question, and I have no answer :D

File: clang/lib/AST/ExprConcepts.cpp (hunk 3 above)
Comment (mizvekov) [reply clang/lib/AST/ExprConcepts.cpp:159]: Yeah sure GCC does it, but IMO it looks worse as it results in a double error.

File: clang/lib/Sema/SemaExprCXX.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaExprCXX.cpp:9521]: The point of recovering to int would be to not give up, just assume the user intended to write int and proceed.

File: clang/lib/AST/ExprConcepts.cpp (hunk 3 above)
Comment (zyn0217) [reply clang/lib/AST/ExprConcepts.cpp:159]: OK I'm sold - now I lean towards your idea of not marking them invalid :)

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks!
