### PR TITLE
[Clang] Normalize constraints before checking for satisfaction

### LINKED ISSUE #61811: Clang type substitution for concepts is too eager
GCC test `concepts4.C` fails when it should pass. Apparently this part of [temp.constr](http://eel.is/c++draft/temp.constr#normal-1.4) points out that the type substitution happens later than when we're applying it (cc @zygoloid in case I botched the explanation).
```cpp
template <class T> struct A { static const int x = 42; };

template <class Ta> concept A42 = A<Ta>::x == 42;
template <class Tv> concept Void = __is_same_as(Tv, void);
template <class Tb, class Ub> concept A42b = Void<Tb> || A42<Ub>;
template <class Tc> concept R42c = A42b<Tc, Tc&>;

static_assert (R42c<void>);
```

### PR DESCRIPTION
**Pull request by cor3ntin**
In the standard, constraint satisfaction checking is done on the normalized form of a constraint.

Clang instead substitutes on the non-normalized form, which causes us to report substitution failures in template arguments or concept ids, which is non-conforming but unavoidable without a parameter mapping

This patch normalizes before satisfaction checking. However, we preserve concept-id nodes in the normalized form, solely for diagnostics purposes.

This addresses #61811 and related concepts conformance bugs, ideally to make the remaining implementation of concept template parameters easier

Fixes #135190
Fixes  #61811

Co-authored-by: Younan Zhang <zyn7109@gmail.com>

### CODE REVIEW

File: clang/include/clang/AST/ASTConcept.h [hunk 1]
```diff
@@ -27,13 +27,23 @@
...
+class ConceptReference;
 class Expr;
 class NamedDecl;
 struct PrintingPolicy;
 
+/// Pairs of unsatisfied atomic constraint expressions along with the
+/// substituted constraint expr, if the template arguments could be
+/// substituted into them, or a diagnostic if substitution resulted in
+/// an invalid expression.
+using UnsatisfiedConstraintRecord =
```
Comment (shafik) [inline clang/include/clang/AST/ASTConcept.h:41]: `Record` is such an overloaded term, can we find a better term? I feel like `UnsatisfiedConstraintUnion` would almost be better here, maybe?

File: clang/include/clang/AST/ASTConcept.h [hunk 2]
```diff
@@ -100,6 +102,10 @@ struct ASTConstraintSatisfaction final :
     return getTrailingObjects() + NumRecords;
   }
 
+  ArrayRef<UnsatisfiedConstraintRecord> records() const {
```
Comment (shafik) [inline clang/include/clang/AST/ASTConcept.h:104]: Please, can we get a more descriptive name for this member function. Especially because searching for this name will hit so many other things on a naive search.

File: clang/include/clang/Sema/SemaConcept.h [hunk 3]
```diff
@@ -16,130 +16,362 @@
...
+                              const MultiLevelTemplateArgumentList &MLTAL,
+                              const ASTTemplateArgumentListInfo *ArgsAsWritten,
+                              TemplateParameterList *TemplateParams,
+                              const NamedDecl *D);
+
+protected:
+  using ExprOrConcept =
+      llvm::PointerUnion<const Expr *, const ConceptReference *>;
+
+  struct AtomicBits {
```
Comment (shafik) [inline clang/include/clang/Sema/SemaConcept.h]:
```suggestion
  struct AtomicContraintBits {
```
Same for other `Bits` structs.

File: clang/include/clang/Sema/SemaConcept.h [hunk 4]
```diff
@@ -16,130 +16,362 @@
...
+    LLVM_PREFERRED_TYPE(ConstraintKind)
+    unsigned Kind : 5;
+    LLVM_PREFERRED_TYPE(CompoundConstraintKind)
+    unsigned CCK : 1;
+    NormalizedConstraint *LHS;
+    NormalizedConstraint *RHS;
+  };
+
+  union {
+    AtomicBits Atomic;
```
Comment (shafik) [inline clang/include/clang/Sema/SemaConcept.h]:
```suggestion
    AtomicConstraintBits AtomicBits;
```

Same for the rest of the names. Again very overloaded terms, more specific names are better and will then make searching a much better experience for future devs.

File: clang/include/clang/Sema/SemaConcept.h [hunk 5]
```diff
@@ -16,130 +16,362 @@
...
     }
     return true;
   }
-};
 
-struct alignas(ConstraintAlignment) NormalizedConstraintPair;
-struct alignas(ConstraintAlignment) FoldExpandedConstraint;
+public:
+  ConstraintKind getKind() const {
+    return static_cast<ConstraintKind>(Atomic.Kind);
```
Comment (shafik) [inline clang/include/clang/Sema/SemaConcept.h:245]: Maybe worth commenting this is only valid due to initial common sequence.

File: clang/include/clang/Sema/SemaConcept.h [hunk 6]
```diff
@@ -16,130 +16,362 @@
...
+                   ConstraintDecl},
+                  SubConstraint} {}
+
+  NormalizedConstraint(NormalizedConstraint *LHS, CompoundConstraintKind CCK,
+                       NormalizedConstraint *RHS)
+      : Compound{llvm::to_underlying(ConstraintKind::Compound), CCK, LHS, RHS} {
+  }
+
+  bool hasParameterMapping() const {
+    assert(getKind() != ConstraintKind::Compound);
```
Comment (shafik) [inline clang/include/clang/Sema/SemaConcept.h]: I am curious why you only assert against `ConstraintLind::Compound`

**Review by shafik — COMMENTED** [review]
I need to make another pass later.

**Comment by cor3ntin** [comment]
There are still a few test failures, including in libc++, but I think we are are at the stage where this could benefit from more eyes

File: clang/lib/Sema/SemaConcept.cpp [hunk 7]
```diff
@@ -543,30 +672,330 @@ static ExprResult calculateConstraintSatisfaction(
...
+  if (!SubstitutedArgs) {
+    Satisfaction.IsSatisfied = false;
+    return ExprError();
+  }
+
+  ExprResult Out;
+  UnsignedOrNone NumExpansions =
+      EvaluateFoldExpandedConstraintSize(Constraint, *SubstitutedArgs);
+  if (!NumExpansions)
+    return ExprEmpty();
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:787]: This includes a parameter mapping substitution which is expensive, so let's add a TODO of adding cache on it.

File: clang/lib/Sema/SemaConcept.cpp [hunk 8]
```diff
@@ -543,30 +672,330 @@ static ExprResult calculateConstraintSatisfaction(
...
+
+  llvm::SmallVector<TemplateArgument> SubstitutedOuterMost;
+  std::optional<MultiLevelTemplateArgumentList> SubstitutedArgs =
+      SubstitutionInTemplateArguments(Constraint, MLTAL, SubstitutedOuterMost);
+
+  if (!SubstitutedArgs) {
+    Satisfaction.IsSatisfied = false;
+    // FIXME: diagnostics?
+    return ExprError();
+  }
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:859]: This is also expensive, caching it might benefit the SFINAE path.

File: clang/lib/Sema/SemaConcept.cpp [hunk 9]
```diff
@@ -543,30 +672,330 @@ static ExprResult calculateConstraintSatisfaction(
...
+            SubstDiag.first, StringRef(Mem, MessageSize)});
+    return ExprError();
+  }
+
+  CXXScopeSpec SS;
+  SS.Adopt(Constraint.getConceptId()->getNestedNameSpecifierLoc());
 
-  return SubstitutedAtomicExpr;
+  ExprResult SubstitutedConceptId = S.CheckConceptTemplateId(
+      SS, Constraint.getConceptId()->getTemplateKWLoc(),
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:907]: Maybe we don't need to rebuild a ConceptSpecializationDecl - again I forgot to clean it up

File: clang/include/clang/AST/ASTContext.h [hunk 10]
```diff
@@ -51,6 +51,27 @@ class FixedPointSemantics;
 struct fltSemantics;
 template <typename T, unsigned N> class SmallPtrSet;
 
+template <> struct DenseMapInfo<llvm::FoldingSetNodeID> {
```
Comment (zyn0217) [inline clang/include/clang/AST/ASTContext.h:54]: Maybe split it into an NFC PR? I'm not sure if downstream users want it

File: clang/lib/Sema/TreeTransform.h [hunk 11]
```diff
@@ -352,6 +356,8 @@ class TreeTransform {
   /// being expanded.
   void ExpandingFunctionParameterPack(ParmVarDecl *Pack) { }
 
+  bool ShouldPreserveTemplateArgumentsPacks() const { return false; }
+
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:360]: This is no longer needed afaik :)

**Review by zyn0217 — COMMENTED** [review]
Thank you very much for putting it up and the incredible work!

I left some notes, mostly are those that I didn't get around to yet (and I think they should be useful); so maybe we want to resolve them before we move forward.

Also let's not forget the release note :)

**Comment by cor3ntin** [comment]
Update: still needs cleaning but the test pass

File: clang/include/clang/AST/ASTConcept.h (hunk 1 above)
Comment (cor3ntin) [reply clang/include/clang/AST/ASTConcept.h:40]: The name is pre-existing, we could change it afterwards

File: clang/lib/Sema/SemaConcept.cpp (hunk 9 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaConcept.cpp:907]: We do, because we need to have the right expression to display in diagnostics

File: clang/lib/Sema/SemaConcept.cpp [hunk 12]
```diff
@@ -543,30 +672,330 @@ static ExprResult calculateConstraintSatisfaction(
...
+  if (auto Iter = S.ConceptIdSatisfactionCache.find(ID);
+      Iter != S.ConceptIdSatisfactionCache.end()) {
+
+    auto &Cached = Iter->second.Satisfaction;
+    Satisfaction.ContainsErrors = Cached.ContainsErrors;
+    Satisfaction.IsSatisfied = Cached.IsSatisfied;
+    Satisfaction.Details.insert(Satisfaction.Details.begin() + Size,
+                                Cached.Details.begin(), Cached.Details.end());
+    return Iter->second.SubstExpr;
+  }
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/SemaConcept.cpp:699]: I don;t think we want to upstream that, it was just too slow to be practical, even as a debug tool

File: clang/lib/Sema/SemaConcept.cpp (hunk 8 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaConcept.cpp:846]: I added a fixme above

**Review by zyn0217 — APPROVED** [review]
A few more comments, and it would be great if we could tidy up our header includes.

Please wait for some time before others want to speak something. Otherwise this LGTM assuming CI is happy with our approach. 😄

File: clang/lib/Sema/SemaConcept.cpp [hunk 13]
```diff
@@ -543,30 +661,328 @@ static ExprResult calculateConstraintSatisfaction(
...
+
+    PartialDiagnosticAt SubstDiag{SourceLocation(),
+                                  PartialDiagnostic::NullDiagnostic()};
+    Info.takeSFINAEDiagnostic(SubstDiag);
+    // FIXME: Concepts: This is an unfortunate consequence of there
+    //  being no serialization code for PartialDiagnostics and the fact
+    //  that serializing them would likely take a lot more storage than
+    //  just storing them as strings. We would still like, in the
+    //  future, to serialize the proper PartialDiagnostic as serializing
+    //  it as a string defeats the purpose of the diagnostic mechanism.
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/SemaConcept.cpp:876]: Ideally we would never store diags in the ast that way!

File: clang/lib/Sema/SemaConcept.cpp [hunk 14]
```diff
@@ -543,30 +661,328 @@ static ExprResult calculateConstraintSatisfaction(
...
+    memcpy(Mem, DiagString.c_str(), MessageSize);
+    Satisfaction.Details.insert(
+        Satisfaction.Details.begin() + Size,
+        new (S.Context) ConstraintSatisfaction::SubstitutionDiagnostic{
+            SubstDiag.first, StringRef(Mem, MessageSize)});
+    return ExprError();
+  }
+
+  CXXScopeSpec SS;
+  SS.Adopt(Constraint.getConceptId()->getNestedNameSpecifierLoc());
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:938]: Looking at it again I feel that we are repeating `Constraint.getConceptId()`.

Can we have a handy variable of it at the start of the function?

File: clang/lib/Sema/SemaConcept.cpp [hunk 15]
```diff
@@ -10,19 +10,68 @@
...
+ *
+ * template <typename T>
+ * concept A = __is_same(T, int);
+ *
+ * template <typename U>
+ * concept B = A<U> && __is_same(U, int);
+ *
+ * The  normal form is `__is_same(T, int) /T->U, inner most level/
+ *                   && __is_same(U, int) {U->U} /T->U, outermost most level/
+ *                   `
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:50]: The normal form of B<U> is ...

File: clang/lib/Sema/SemaConcept.cpp [hunk 16]
```diff
@@ -10,19 +10,68 @@
 //
 //===----------------------------------------------------------------------===//
 
+/*
+ * A note on implementation:
+ *
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:15]: thanks, the documentation is great

File: clang/lib/Sema/SemaConcept.cpp [hunk 17]
```diff
@@ -822,14 +866,17 @@ ExprResult CalculateConstraintSatisfaction::Calculate(
...
 
   if (!E.isUsable()) {
     Satisfaction.Details.insert(Satisfaction.Details.begin() + Size,
                                 Constraint.getConceptId());
     return E;
   }
 
+  // ConceptIdConstraint is only relevant for diagnostics,
+  // so if the normalized constraint is satisfied, we should not
+  // substiture into the constraint.
```
Comment (zyn0217) [inline clang/lib/Sema/SemaConcept.cpp:879]:
```suggestion
  // substitute into the constraint.
```

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 18]
```diff
@@ -1405,7 +1405,8 @@ class TemplateInstantiator : public TreeTransform<TemplateInstantiator> {
   // Whether an incomplete substituion should be treated as an error.
   bool BailOutOnIncomplete;
 
-  bool PreserveArgumentPacks = false;
+  // Whether to rebuild pack expansion types; We don't do that when
+  // rebuilding a fold expression appearing in a constraint expression.
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1409]: when building parameter mappings for a fold expression appearing in a constraint expression.

(Let's be specific)

**Review by mizvekov — COMMENTED** [review]
Just a first pass, I'll try to get some time to fully review later.

File: clang/test/SemaTemplate/concepts.cpp [hunk 19]
```diff
@@ -1257,4 +1256,35 @@ template <typename T> concept PerfectSquare = [](){} // expected-note 2{{here}}
...
+template <class...> struct __mdefer_;
+template <class _Fn, class... _Args>
+  requires __minvocable<_Fn>
+struct __mdefer_<_Fn, _Args...> {};
+template <class = __q> struct __mtransform {
+  template <class> using __f = int;
+};
+struct __completion_domain_or_none_ : __mdefer_<__mtransform<>> {};
+
+}
```
Comment (zyn0217) [inline clang/test/SemaTemplate/concepts.cpp:1288]: @mizvekov Here is the regression why I removed that assert in TemplateArgumentLoc.

So basically we want to build the parameter mapping of __minvocable<Fn> from line 1281. We use template rewrite mechanism, and we end up substituting `_Fn::template __f` into template template parameter on line 1275.

I noticed your last removal of DTST patch and I tried with it locally, but unfortunately it doesn't fix that assertion failure where that template template parameter doesn't have the same NNS with the rewritten template argument.

The rewritten template argument comes from CheckTemplateArguments, which is necessary to correctly preserve packs in other cases.

We chose to use rewritten mode in very early developing stage because we had trouble with Subst nodes and lambdas, and it was impossible to fix that without rewriting half of clang.

I tried rebuilding that TemplateName with its NNS cleared, but it turned out I have to handle so many types in Instantiator which is a bit clumsy. (And I failed some regressions too!)

Maybe we are having the same problem with CTAD guides, but I didn't come up with a case so far.

Do you have any suggestions for such a case?

File: clang/lib/AST/TemplateBase.cpp [hunk 20]
```diff
@@ -606,8 +606,11 @@ TemplateArgumentLoc::TemplateArgumentLoc(ASTContext &Ctx,
       LocInfo(Ctx, TemplateKWLoc, QualifierLoc, TemplateNameLoc, EllipsisLoc) {
   assert(Argument.getKind() == TemplateArgument::Template ||
          Argument.getKind() == TemplateArgument::TemplateExpansion);
-  assert(QualifierLoc.getNestedNameSpecifier() ==
-         Argument.getAsTemplateOrTemplatePattern().getQualifier());
+  // We can't assume QualifierLoc.getNestedNameSpecifier() ==
+  // Argument.getAsTemplateOrTemplatePattern().getQualifier() at this point,
+  // because in template rewriting, we may substitute a DependentTemplateName
+  // (which has a NNSLoc) into a template template parameter (which
+  // doesn't have a NNSLoc).
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/AST/TemplateBase.cpp:613]: I explained why under the corresponding regression case. Let's move our conversation there

File: clang/docs/ReleaseNotes.rst [hunk 21]
```diff
@@ -126,6 +126,10 @@ C++23 Feature Support
 C++20 Feature Support
 ^^^^^^^^^^^^^^^^^^^^^
 
+- Clang now normalizes constraints before checking their satisfaction, as mandated by the standard.
+  As a result, Clang no longer incorrectly diagnose subsdtitution failures in template arguments only
+  used in concept-ids, and produce better diagnostics for satisfaction failure. (#G61811) (#GH135190)
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/docs/ReleaseNotes.rst:131]:
```suggestion
- Clang now normalizes constraints before checking their satisfaction, as mandated by the standard.
  As a result, Clang no longer incorrectly diagnose subsdtitution failures in template arguments only
  used in concept-ids, and produce better diagnostics for satisfaction failure. (#GH61811) (#GH135190)
```

File: clang/lib/Sema/SemaConcept.cpp [hunk 22]
```diff
@@ -1379,216 +1890,327 @@ static void diagnoseWellFormedUnsatisfiedConstraintExpr(Sema &S,
...
+    MultiLevelTemplateArgumentList MLTAL = SemaRef.getTemplateInstantiationArgs(
+        Concept, Concept->getLexicalDeclContext(),
+        /*Final=*/true, CSE->getTemplateArguments(),
+        /*RelativeToPrimary=*/true,
+        /*Pattern=*/nullptr,
+        /*ForConstraintInstantiation=*/true);
+
+    // Don't build Subst* nodes to model lambda expressions.
+    // The transform of Subst* is oblivious to the lambda type.
+    MLTAL.setKind(TemplateSubstitutionKind::Rewrite);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaConcept.cpp:2178]: @zyn0217 moving the discussion here.

I think this is incorrect, this substitution is not a rewrite, as this can basically transform a reference to template parameter into an arbitrary template argument of the corresponding kind.

A rewrite should transform a template parameter into another template parameter of the same kind, otherwise the source location kinds will be incompatible.

For example, in a non-rewrite substitution, the source location for a template parameter is compatible with the source location for its corresponding Subst* AST node kind. This makes sense, as the Subst node is a stand-in for the template parameter, and whatever it was substituted for is not part of the source location data, as it was not written.

For a rewrite, if we stick to the rule of substituting template parameters for template parameters, the source locations obviously stay compatible as they are of the same kind.
But if you allow arbitrary substitutions outside of those rules, then that doesn't work anymore.

We should add some asserts to verify this isn't happening anywhere else and doesn't happen again.

If you add back the assert in the TemplateArgumentLoc constructor, and remove this line, that should make it work.

In fact, the otherwise failing test case can be simplified to just:
```C++
template <template <class> class TT> concept C1 = sizeof(TT<int>) >= 0;
template <class T> concept C2 = C1<T::template X>;
static_assert(C2<int>);
```

I am not sure why this line is needed in the first place, that looks like a workaround.

File: clang/test/SemaTemplate/concepts.cpp (hunk 19 above)
Comment (mizvekov) [reply clang/test/SemaTemplate/concepts.cpp:1288]: Moving the discussion to the offending line.

File: clang/lib/Sema/SemaConcept.cpp (hunk 22 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:2178]: We avoided Subst* nodes because we encountered the following case:

```cpp
template<auto Q> concept C = requires { Q.template operator()<float>(); };
template<class> concept D = false;
template<class> concept E = C<[]<D Ty>{}>;
static_assert(E<int>);
```

For Q, we build a SubstNTTPExpr with a dependent lambda `[]<D Ty>{}`. And since we still lack the parameter mapping inside a requirement expression (https://eel.is/c++draft/temp.constr.normal#1.6) so the lambda will remain dependent after we substitute <int> into the mapping, and therefore evaluating it would be UB.

I am still not very clear if we need a parameter mapping inside C. @cor3ntin

Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:2178]: Actually it can be even simplified to

```cpp
template<auto Q> concept C = Q.template operator()<float>();
template<class> concept E = C<[]<class Ty>{ return false; }>;
static_assert(E<int>);
```

And we cannot perform a qualified name lookup on a subst* node.

File: clang/lib/AST/ASTConcept.cpp [hunk 23]
```diff
@@ -116,6 +122,19 @@ void ConceptReference::print(llvm::raw_ostream &OS,
   }
 }
 
+const StreamingDiagnostic &clang::operator<<(const StreamingDiagnostic &DB,
+                                             const ConceptReference *C) {
+  std::string NameStr;
+  llvm::raw_string_ostream OS(NameStr);
+  LangOptions LO;
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/AST/ASTConcept.cpp:129]: Yeah, we do that in a couple of places to avoid that dependence - I agree about it being gnarly.

File: clang/include/clang/Sema/SemaConcept.h [hunk 24]
```diff
@@ -16,130 +16,385 @@
...
+    return getKind() != ConstraintKind::Compound && Atomic.Args != nullptr;
+  }
 
-struct alignas(ConstraintAlignment) AtomicConstraint {
-  const Expr *ConstraintExpr;
-  const NamedDecl *ConstraintDecl;
-  std::optional<ArrayRef<TemplateArgumentLoc>> ParameterMapping;
+  const OccurenceList &mappingOccurenceList() const {
+    assert(hasParameterMapping() && "This constraint has no parameter mapping");
+    return Atomic.Indexes;
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/Sema/SemaConcept.h:173]: It's copied entirely in in `SubstituteParameterMappings::substitute`, so it needs to be exposed

File: clang/docs/InternalsManual.rst [hunk 25]
```diff
@@ -2859,6 +2859,65 @@ This library is called by the :ref:`Parser library <Parser>` during parsing to
...
+
+The normal form of the associated constraints of a declaration is cached in
+Sema::NormalizationCache such that it is only computed once.
+
+a ``NormalizedConstraint`` is a recursive data structure, where each node
+contains a parameter mapping, represented by the indexes of all parameter
+being used.
+
+Checking satisfaction is done by ConstraintSatisfactionChecker, recursively
+walking NormalizedConstraint. At each level, we substitute the outermost
```
Comment (zyn0217) [inline clang/docs/InternalsManual.rst:2889]:
```suggestion
Checking satisfaction is done by ``ConstraintSatisfactionChecker``, recursively
walking ``NormalizedConstraint``. At each level, we substitute the outermost
```

File: clang/docs/InternalsManual.rst [hunk 26]
```diff
@@ -2859,6 +2859,65 @@ This library is called by the :ref:`Parser library <Parser>` during parsing to
...
+level of the template arguments referenced in the parameter mapping of a
+normalized expression (``MultiLevelTemplateArgumentList``).
+
+.. code-block:: c++
```
Comment (zyn0217) [inline clang/docs/InternalsManual.rst:2893]:
```suggestion
normalized expression (``MultiLevelTemplateArgumentList``).

For the following example,

.. code-block:: c++
```

File: clang/docs/InternalsManual.rst [hunk 27]
```diff
@@ -2859,6 +2859,65 @@ This library is called by the :ref:`Parser library <Parser>` during parsing to
...
+  concept B = A<U> && __is_same(U, int);
+
+The normal form of B is
+
+.. code-block:: c++
+    __is_same(T, int) /*T->U, innermost level*/
+ && __is_same(U, int) {U->U} /*T->U, outermost most level*/
+
+After substitution in the mapping, we substitute in the constraint expression
+using that copy of the MultiLevelTemplateArgumentList, and then evaluate it.
```
Comment (zyn0217) [inline clang/docs/InternalsManual.rst:2908]:
```suggestion
using that copy of the ``MultiLevelTemplateArgumentList``, and then evaluate it.
```

**Review by zyn0217 — COMMENTED** [review]
I added some comments for document formats

File: clang/include/clang/AST/ASTConcept.h [hunk 28]
```diff
@@ -28,10 +28,19 @@ namespace clang {
...
 class NamedDecl;
 struct PrintingPolicy;
 
+/// Pairs of unsatisfied atomic constraint expressions along with the
+/// substituted constraint expr, if the template arguments could be
+/// substituted into them, or a diagnostic if substitution resulted in
+/// an invalid expression.
+using UnsatisfiedConstraintRecord =
+    llvm::PointerUnion<const Expr *, const ConceptReference *,
+                       std::pair<SourceLocation, StringRef> *>;
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/AST/ASTConcept.h]: I cleaned that up to hopefully make it more obvious what is going on - it is a union of 3 pointers - the pair is pre-existing though

File: clang/include/clang/Sema/SemaConcept.h [hunk 29]
```diff
@@ -16,130 +16,385 @@
...
+    ConceptId,
+    FoldExpanded,
+    Compound,
+  };
+
+  enum CompoundConstraintKind : unsigned char {
+    CCK_Conjunction,
+    CCK_Disjunction
+  };
+  enum class FoldOperatorKind : unsigned char { And, Or };
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/Sema/SemaConcept.h:49]: They all are different things. I would prefer they remain separate to match the wording

A constraint can be either a Compound constraint, or a FoldExpanded constraint.
a Compound constraint can be either a conjunction or a disjunction.

a FoldExpanded has an operator. the reason we have an enum for that instead of reusing `BinaryOperatorKind` is that we don't need/want to use more than one bits (and none of the operator produce a fold expanded constraint)

File: clang/include/clang/AST/ASTConcept.h (hunk 28 above)
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/include/clang/AST/ASTConcept.h]: None that i would like to get rid of that whole thing entirely and not store diags in the AST but I have not explored how viable this would be

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 30]
```diff
@@ -1625,6 +1647,13 @@ namespace {
                           NamedDecl *FirstQualifierInScope = nullptr,
                           bool AllowInjectedClassName = false);
 
+    /// Check for tag mismatches when instantiating an
+    /// elaborated type.
+    QualType RebuildElaboratedType(SourceLocation KeywordLoc,
+                                   ElaboratedTypeKeyword Keyword,
+                                   NestedNameSpecifierLoc QualifierLoc,
+                                   QualType T);
+
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp]: This is not used anywhere

File: clang/include/clang/Sema/SemaConcept.h [hunk 31]
```diff
@@ -16,130 +16,385 @@
...
+
+  using OccurenceList = llvm::SmallBitVector;
+
+  friend bool
+  substituteParameterMappings(Sema &S, NormalizedConstraint &N,
+                              const MultiLevelTemplateArgumentList &MLTAL,
+                              const ASTTemplateArgumentListInfo *ArgsAsWritten,
+                              TemplateParameterList *TemplateParams,
+                              const NamedDecl *D);
```
Comment (zyn0217) [inline clang/include/clang/Sema/SemaConcept.h:58]: I think this is unused

**Comment by kstoimenov** [comment]
Looks like it has a memory leak: https://lab.llvm.org/buildbot/#/builders/169/builds/15562. @cor3ntin please take a look.
