### PR TITLE
[Clang][Sema] Fix a bug on template partial specialization with issue on deduction of nontype template parameter

### LINKED ISSUE #68885: NTTP references in requires clauses
Clang rejects this code

```cpp
#include <concepts> 
template <decltype(auto) a>
struct S {
    static constexpr int i = 42;
};

template <decltype(auto) a>
requires true
struct S<a> {
    static constexpr int i = 0;
};

static constexpr int a = 0;

void test() {
    static_assert(S<a>::i == 0);  // Ok
    static_assert(S<(a)>::i == 0); // Fails
}

```

https://godbolt.org/z/hsb4c5WE3 

Clang picks the primary template when a NTTP is a reference type, even if there is a more constrained specialization.
Other compiler accept this code.

### PR DESCRIPTION
**Pull request by jcsxky**
Fix https://github.com/llvm/llvm-project/issues/68885
When build expression from a deduced argument whose kind is `Declaration` and `NTTPType`(which declared as `decltype(auto)`) is deduced as a reference type, `BuildExpressionFromDeclTemplateArgument` just create a `DeclRef`. This is incorrect while we get type from the expression since we can't get the original reference type from `DeclRef`. Creating a `SubstNonTypeTemplateParmExpr` expression and make the deduction correct. `Replacement` expression of `SubstNonTypeTemplateParmExpr` just helps the deduction and may not be same with the original expression.

### CODE REVIEW

**Review by Endilll — COMMENTED** [review]
`Sema.h` changes look good to me.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -8508,6 +8507,16 @@ Sema::BuildExpressionFromDeclTemplateArgument(const TemplateArgument &Arg,
...
     assert(ParamType->isReferenceType() &&
            "unexpected type for decl template argument");
+    if (ParamType->isLValueReferenceType())
+      if (NonTypeTemplateParmDecl *NTTP =
+              dyn_cast_if_present<NonTypeTemplateParmDecl>(TemplateParam)) {
+        QualType TemplateParamType = NTTP->getType();
+        const AutoType *AT = TemplateParamType->getAs<AutoType>();
+        if (AT && AT->isDecltypeAuto())
+          RefExpr = new (getASTContext())
+              ParenExpr(RefExpr.get()->getBeginLoc(),
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:8517]: Did you try to preserve the references using `SubstNonTypeTemplateParmExpr`s just like what @cor3ntin said? This looks a bit odd to me...

Comment (jcsxky) [reply clang/lib/Sema/SemaTemplate.cpp:8517]: Ah, thanks for your remind! `SubstNonTypeTemplateParmExpr` is more suitable here.

**Comment by jcsxky** [comment]
Windows CI failed with an unrelated file.

**Review by cor3ntin — APPROVED** [review]
