### PR TITLE
[clang] Fixed Constant Evaluation don't Call Destructor

### LINKED ISSUE #139818: [clang] constant evaluation of `for` loop does not run destructor for condition variable
If a condition variable is declared in the second clause of a three-clause `for` loop, clang doesn't destroy it when constant-evaluating the loop. For example:
```c++
struct X {
  constexpr ~X() noexcept(false) { throw "oops"; }
  constexpr operator bool() {
    return b;
  }
  bool b;
};
constexpr bool f() {
  for (bool b = false; X x = {b}; b = true) {}
  return true;
}
static_assert(f());
```
Clang treats this as constant, but the destructor for `x` throws an exception.

It looks like the problem is that we fail to call `IterScope.destroy()` [here](https://github.com/llvm/llvm-project/blob/5f41928689125667cf645835fa9fefee97511d8a/clang/lib/AST/ExprConstant.cpp#L5742), when terminating a loop iteration because the condition evaluated to `false`.

### PR DESCRIPTION
**Pull request by Mr-Anyone**
Within the condition statement of the for block, the destructor doesn't get when evaluating compile time constants. 

resolves #139818

### CODE REVIEW

File: clang/test/SemaCXX/static-assert-cxx26.cpp [hunk 1]
```diff
@@ -416,3 +416,38 @@ static_assert(
       // expected-note@-1 {{read of dereferenced one-past-the-end pointer is not allowed in a constant expression}}
 );
 }
+
+// taken from: https://github.com/llvm/llvm-project/issues/139818
+namespace GH139818{
```
Comment (Sirraide) [inline clang/test/SemaCXX/static-assert-cxx26.cpp:421]: Er, there’s no reason for these tests to be in this file; maybe try and find a file containing tests around destructors during constant evaluation (in either `test/AST` or `test/SemaCXX`); if you can’t find one, then just make a new file and call it `gh139818.cpp`.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -623,6 +623,7 @@ Bug Fixes in This Version
 - Fix crash due to unknown references and pointer implementation and handling of
   base classes. (GH139452)
 - Fixed an assertion failure in serialization of constexpr structs containing unions. (#GH140130)
+- Fix constant evaluation in for loop not calling destructor (#GH139818)
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:626]:
```suggestion
- Constant evaluation now correctly runs the destructor of a variable declared in 
  the second clause of a C-style ``for`` loop. (#GH139818)
```

File: clang/test/SemaCXX/static-assert-cxx26.cpp (hunk 1 above)
Comment (Mr-Anyone) [reply clang/test/SemaCXX/static-assert-cxx26.cpp]: I have moved the test to `cxx2a-consteval.cpp` is that ok? Also, thanks for reviewing.

Comment (Sirraide) [reply clang/test/SemaCXX/static-assert-cxx26.cpp]: No, that’s for the `consteval` keyword. Maybe just make a new file for this then.

And in that case, can you also check if this works with the new constant interpreter by adding a second `RUN` line with `-fexperimental-new-constant-interpreter`. If that also passes then that’s great, if not, then just remove it again (you don’t have to update the new interpreter as well as part of this pr), but it’d be nice to check whether this is also a bug in the new interpreter if we’re already adding tests for this.

File: clang/test/SemaCXX/cxx2a-consteval.cpp [hunk 3]
```diff
@@ -1321,4 +1321,39 @@ namespace GH139160{
                                                 // expected-note@-2  {{non-constexpr function 'make_struct' cannot be used in a constant expression}}
 };
 
+// taken from: https://github.com/llvm/llvm-project/issues/139818
+namespace GH139818{
```
Comment (zyn0217) [inline clang/test/SemaCXX/cxx2a-consteval.cpp:1325]: GH139818 already reflects the source.

```suggestion
namespace GH139818 {
```

File: clang/test/SemaCXX/static-assert-cxx26.cpp (hunk 1 above)
Comment (Mr-Anyone) [reply clang/test/SemaCXX/static-assert-cxx26.cpp]: I just moved it to `gh139818.cpp` in `test/SemaCXX`

**Comment by Mr-Anyone** [comment]
ping

**Comment by Mr-Anyone** [comment]
Documentation fail seems to be fixed by #142387

File: clang/test/SemaCXX/gh139818.cpp [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    constexpr bool f1() {
+      bool ret = true;
+      for (bool b = false; A x{b, ret}; b = true) {}
+      return ret;
+    }
+
+    static_assert(!f1());
+
+    struct Y {
+      constexpr ~Y() noexcept(false) { throw "oops"; }  // expected-error {{cannot use 'throw' with exceptions disabled}}
```
Comment (Sirraide) [inline clang/test/SemaCXX/gh139818.cpp]: Can you add `-fcxx-exceptions` (I think that was the flag at least) to the `RUN` lines so we don’t get this error.

**Review by Sirraide — APPROVED** [review]
One comment but otherwise this LGTM.

**Comment by Sirraide** [comment]
> Documentation fail seems to be fixed by #142387

Yeah, the changes to the release notes look fine, so if CI is unhappy about them then that’s for some other reason.

File: clang/test/SemaCXX/gh139818.cpp (hunk 4 above)
Comment (Mr-Anyone) [reply clang/test/SemaCXX/gh139818.cpp]: I think I have updated it, thanks.

**Review by Sirraide — APPROVED** [review]

**Comment by Mr-Anyone** [comment]
@Sirraide I don't have merge access. Could you please merge? Thanks.
