### PR TITLE
[clang-tidy] Improve `bugprone-infinite-loop` check by adding handing for structured bindings

### LINKED ISSUE #138842: [clang-tidy] bugprone-infinite-loop false positive with structured binding
clang-tidy's `bugprone-infinite-loop` check incorrectly flags a valid loop as infinite when using a structured binding declaration in the loop condition.

Code example:

```cpp
#include <iostream>

int main()
{
    int x = 10;
    auto [y, _] = std::pair<int, int> {1, 2};

    while (y < x) {
        y++;
    }

    return 0;
}
```

Command:

```bash
./build/bin/clang-tidy temp.cpp -check=-*,bugprone-infinite-loop
```

Output:

```bash
temp.cpp:8:5: warning: this loop is infinite; none of its condition variables (x) are updated in the loop body [bugprone-infinite-loop]
    8 |     while (y < x) {
      |     ^
```

### PR DESCRIPTION
**Pull request by flovent**
Before this patch, this check only handles `VarDecl` as varaibles' declaration in statement, but this will ignore variables in structured bindings (`BindingDecl` in AST), which leads to false positives.

Closes #138842.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp [hunk 1]
```diff
@@ -83,6 +83,23 @@ static bool isVarThatIsPossiblyChanged(const Decl *Func, const Stmt *LoopStmt,
              isChanged(LoopStmt, Var, Context);
       // FIXME: Track references.
     }
+
+    if (const auto *BD = dyn_cast<BindingDecl>(DRE->getDecl())) {
+      if (const auto *DD =
+              dyn_cast_if_present<DecompositionDecl>(BD->getDecomposedDecl())) {
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp]: What is the profit of using `dyn_cast_if_present` here?
`DecompositionDecl` may or may not be there, but the same rules apply to previous cast: `BindingDecl` also may or not be there.

File: clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp [hunk 2]
```diff
@@ -215,10 +236,18 @@ static bool overlap(ArrayRef<CallGraphNode *> SCC,
...
 static bool hasStaticLocalVariable(const Stmt *Cond) {
-  if (const auto *DRE = dyn_cast<DeclRefExpr>(Cond))
+  if (const auto *DRE = dyn_cast<DeclRefExpr>(Cond)) {
     if (const auto *VD = dyn_cast<VarDecl>(DRE->getDecl()))
       if (VD->isStaticLocal())
         return true;
+
+    if (const auto *BD = dyn_cast<BindingDecl>(DRE->getDecl()))
+      if (const auto *DD =
+              dyn_cast_if_present<DecompositionDecl>(BD->getDecomposedDecl()))
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp]: same with `dyn_cast_if_present` here

File: clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp (hunk 1 above)
Comment (flovent) [reply clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp]: You are right, null check should not be necessary here, updated.

**Comment by flovent** [comment]
New CI failure seems unrelated to the new commit.

**Comment by flovent** [comment]
ping.

**Review by vbvictor — COMMENTED** [review]
Could we add tests with:

- structured binding coming from type-dependent template struct, like
```cpp
template <typename T, typename U>
void foo(T a, U b) {
    auto [c, d] = std::pair<T, U>(a,b);
}
```
- `auto&` and `auto&&`

**Review by vbvictor — APPROVED** [review]
LGTM, but I'd like to wait for a second reviewer for some time to double-check if some tests are missing

File: clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp [hunk 3]
```diff
@@ -83,6 +83,23 @@ static bool isVarThatIsPossiblyChanged(const Decl *Func, const Stmt *LoopStmt,
...
+          return true;
+
+        if (DD->getType().isVolatileQualified())
+          return true;
+
+        if (!BD->getType().getTypePtr()->isIntegerType())
+          return true;
+
+        return hasPtrOrReferenceInFunc(Func, BD) ||
+               isChanged(LoopStmt, BD, Context);
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/bugprone/InfiniteLoopCheck.cpp]: avoid duplicated code with `VarDecl` part. extract them to separated function

**Review by HerrCai0907 — APPROVED** [review]
LGTM except nit

**Review by carlosgalvezp — APPROVED** [review]
LGTM, but please rebase onto latest trunk and address/resolve pending comments.

**Comment by aviralg** [comment]
LGTM. I tried to address the specific case of tuple structured bindings in my PR: https://github.com/llvm/llvm-project/pull/147410. Your PR handles the case for all structured bindings. It may be a good idea to add tests for tuple (you can lift from my PR) and array structured bindings too.

**Comment by flovent** [comment]
> LGTM. I tried to address the specific case of tuple structured bindings in my PR: #147410. Your PR handles the case for all structured bindings. It may be a good idea to add tests for tuple (you can lift from my PR) and array structured bindings too.

Thanks for the review and advice, these testcases have now been added.
