### PR TITLE
[clang] Fix false positive regression for lifetime analysis warning.

### LINKED ISSUE #127195: -Wreturn-stack-address false positive
https://godbolt.org/z/YW8eeWG1x

```
namespace std {
template <typename T>
struct basic_string_view {
  const T* data() const;
};
using string_view = basic_string_view<char>;
}  // namespace std

template <typename T>
struct StatusOr {
  T* operator->() [[clang::lifetimebound]];
};

const char* s() {
  StatusOr<std::string_view> s;

  return s->data(); // bogus -Wreturn-stack-adddress diagnostic.
}
```

### PR DESCRIPTION
**Pull request by hokein**
This fixes a false positive caused by #114044.

For `GSLPointer*` types, it's less clear whether the lifetime issue is about the GSLPointer object itself or the owner it points to. To avoid false positives, we take a conservative approach in our heuristic.

Fixes #127195

(This will be backported to release 20).

### CODE REVIEW

**Review by Xazax-hun — APPROVED** [review]

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 1]
```diff
@@ -1239,11 +1239,12 @@ static AnalysisResult analyzePathForGSLPointer(const IndirectLocalPath &Path,
...
     // Check the return type, e.g.
     //   const GSLOwner& func(const Foo& foo [[clang::lifetimebound]])
+    //   GSLOwner* func(cosnt Foo& foo [[clang::lifetimebound]])
     //   GSLPointer func(const Foo& foo [[clang::lifetimebound]])
     if (FD &&
-        ((FD->getReturnType()->isReferenceType() &&
+        ((FD->getReturnType()->isPointerOrReferenceType() &&
           isRecordWithAttr<OwnerAttr>(FD->getReturnType()->getPointeeType())) ||
-         isPointerLikeType(FD->getReturnType())))
+          isGLSPointerType(FD->getReturnType())))
```
Comment (usx95) [inline clang/lib/Sema/CheckExprLifetime.cpp:1247]: Does it mean that only `gsl::Pointer` return types are supported ?

For example `std::unique_ptr` in `int* x = make_unique<int>(1).get();`
https://godbolt.org/z/73bTWd48b
I think this would stop working ?

Comment (usx95) [reply clang/lib/Sema/CheckExprLifetime.cpp:1247]: Since this is on GSL init path, the case mentioned should not be affected.

I also there are related tests already present:
```
std::unique_ptr<int> getUniquePtr();
int *danglingUniquePtrFromTemp() {
  return getUniquePtr().get(); // expected-warning {{returning address of local temporary object}}
}
int *danglingUniquePtrFromTemp2() {
  return std::unique_ptr<int>().get(); // expected-warning {{returning address of local temporary object}}
}
```
So this should be good to go.

**Review by usx95 — APPROVED** [review]
LGTM. Thanks.

File: clang/test/Sema/warn-lifetime-analysis-nocfg.cpp [hunk 2]
```diff
@@ -852,3 +852,27 @@ struct Test {
...
+  return s->data(); // expected-warning {{address of stack memory associated with local variable}}
+  
+  StatusOr<std::string_view> s2;
+  return s2->data();
+
+  StatusOr<StatusOr<std::string_view>> s3;
+  return s3.value()->value()->data();
+
+  // would be nice to support the nested cases.
+  StatusOr<StatusOr<std::string>> s4;
```
[the remark this answers is not in the document]
Comment (hokein) [reply clang/test/Sema/warn-lifetime-analysis-nocfg.cpp:874]: Done.

**Comment by hokein** [comment]
/ cherry-pick 9c49b188b8e1434eb774ee8422124ad3e8870dce

**Comment by hokein** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/9c49b188b8e1434eb774ee8422124ad3e8870dce
