### PR TITLE
[clang-tidy]bugprone-unused-return-value ignore `++` and `--` operator overloading

### LINKED ISSUE #84705: `bugprone-unused-return-value` reported on iterator increment
With `bugprone-unused-return-value.CheckFunctions` set to `::.*`.

```cpp
#include <string>

void f()
{
    std::string s;
    for (std::string::const_iterator it = s.cbegin(); it != s.cend(); ++it) {}
    for (std::string::const_iterator it = s.cbegin(); it != s.cend(); it++) {}
}
```

```
test.cpp:6:71: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
    6 |     for (std::string::const_iterator it = s.cbegin(); it != s.cend(); ++it) {}
      |                                                                       ^~~~
test.cpp:6:71: note: cast the expression to void to silence this warning
test.cpp:7:71: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
    7 |     for (std::string::const_iterator it = s.cbegin(); it != s.cend(); it++) {}
      |                                                                       ^~~~
test.cpp:7:71: note: cast the expression to void to silence this warning
```

The result is actually used by the loop condition.

Some context on why I am trying to match all functions which might seem excessive.
This is actually something I wanted for quite a while. The idea was a bit more limited in that I wanted to find functions within test code which do not check the results. But simply enabling it in the context of the test folder actually has the same effect and actually goes a bit further.

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #84705
Further fix for #84489

### CODE REVIEW

**Comment by EugeneZelenko** [comment]
Please mention changes in Release Notes.

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp [hunk 1]
```diff
@@ -165,20 +165,20 @@ void UnusedReturnValueCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
...
-              anyOf(
-                  isInstantiatedFrom(
-                      matchers::matchesAnyListedName(CheckedFunctions)),
-                  returns(hasCanonicalType(hasDeclaration(namedDecl(
-                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))))
+      callExpr(callee(functionDecl(
+                   // Don't match void overloads of checked functions.
+                   unless(returns(voidType())),
+                   // Don't match copy or move assignment operator.
+                   unless(cxxMethodDecl(isOperatorOverloading(
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp:172]: Just curios, what about operators outside class, like:
```
struct S {
  S(){};
  S(S const &);
  S(S &&);
};

  S &operator+=(S& s, S s2);

void test()
{
    S s;
    S s2;

    s += s2;

    operator+=(s, s2);
}
```

in AST those are functions, not methods:
```
-FunctionDecl <line:7:3, col:27> col:6 used operator+= 'S &(S &, S)'
| |-ParmVarDecl <col:17, col:20> col:20 s 'S &'
| `-ParmVarDecl <col:23, col:25> col:25 s2 'S':'S'
```

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp [hunk 2]
```diff
@@ -165,20 +165,20 @@ void UnusedReturnValueCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
...
-              unless(cxxMethodDecl(isOperatorOverloading(
-                  {OO_Equal, OO_PlusEqual, OO_MinusEqual, OO_StarEqual,
-                   OO_SlashEqual, OO_PercentEqual, OO_CaretEqual, OO_AmpEqual,
-                   OO_PipeEqual, OO_LessLessEqual, OO_GreaterGreaterEqual}))),
-              anyOf(
-                  isInstantiatedFrom(
-                      matchers::matchesAnyListedName(CheckedFunctions)),
-                  returns(hasCanonicalType(hasDeclaration(namedDecl(
-                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))))
+      callExpr(callee(functionDecl(
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp:168]: woudn't `unless(cxxOperatorCallExpr(isAssignmentOperator()))` help here ?

**Review by PiotrZSL — APPROVED** [review]
Overall change is fine.
There is only one usage of isOperatorOverloading, so you could consider changing this into:
isOverloadAssigmentOperator and put all those operator kinds in a matcher instead of messing with SmallVector.

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp (hunk 2 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp]: I refactor it via `cxxOperatorCallExpr`.

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp [hunk 3]
```diff
@@ -31,9 +31,20 @@ AST_MATCHER_P(FunctionDecl, isInstantiatedFrom, Matcher<FunctionDecl>,
...
+        OO_SlashEqual, OO_PercentEqual,  OO_CaretEqual,          OO_AmpEqual,
+        OO_PipeEqual,  OO_LessLessEqual, OO_GreaterGreaterEqual, OO_PlusPlus,
+        OO_MinusMinus};
+
+AST_MATCHER(CXXOperatorCallExpr, isAssignmentOverloadedOperatorCall) {
+  return llvm::is_contained(AssignmentOverloadedOperatorKinds,
+                            Node.getOperator());
+}
+AST_MATCHER(CXXMethodDecl, isAssignmentOverloadedOperatorMethod) {
+  return llvm::is_contained(AssignmentOverloadedOperatorKinds,
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp:46]: getOverloadedOperator belongs to FunctionDecl, change this from Method to Function, and same in calee, in such case you will also cover calls to free standing operators called directly.

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp [hunk 4]
```diff
@@ -169,16 +180,14 @@ void UnusedReturnValueCheck::registerMatchers(MatchFinder *Finder) {
...
-                   OO_PipeEqual, OO_LessLessEqual, OO_GreaterGreaterEqual}))),
               anyOf(
                   isInstantiatedFrom(
                       matchers::matchesAnyListedName(CheckedFunctions)),
                   returns(hasCanonicalType(hasDeclaration(namedDecl(
-                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))))
+                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))),
+          // Don't match copy or move assignment operator.
+          unless(cxxOperatorCallExpr(isAssignmentOverloadedOperatorCall())),
+          unless(callee(cxxMethodDecl(isAssignmentOverloadedOperatorMethod()))))
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp:190]: try changing this code in a way so callee woudn't be checked if cxxOperatorCallExpr were already checked.
you could do it like this:
```
anyOf(cxxOperatorCallExpr(unless(isAssignmentOverloadedOperatorCall()),
           unless(callee(functionDecl(isAssignmentOverloadedOperatorFunction()))))
```

You may also consider moving this before all those matchers::matchesAnyListedName, so names woudn't be checked for operators at all.

**Review by PiotrZSL — COMMENTED** [review]
Few more tests would be also nice, with free standing operators.

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp [hunk 5]
```diff
@@ -169,16 +176,13 @@ void UnusedReturnValueCheck::registerMatchers(MatchFinder *Finder) {
...
-                   OO_SlashEqual, OO_PercentEqual, OO_CaretEqual, OO_AmpEqual,
-                   OO_PipeEqual, OO_LessLessEqual, OO_GreaterGreaterEqual}))),
               anyOf(
                   isInstantiatedFrom(
                       matchers::matchesAnyListedName(CheckedFunctions)),
                   returns(hasCanonicalType(hasDeclaration(namedDecl(
-                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))))
+                      matchers::matchesAnyListedName(CheckedReturnTypes)))))))),
+          // Don't match copy or move assignment operator.
+          unless(callee(functionDecl(isAssignmentOverloadedOperatorMethod()))))
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp:185]: Why did you move this down here? This can be written as `unless(isAssignmentOverloadedOperatorMethod())` under the void check, like before.

**Review by 5chmidti — COMMENTED** [review]
Should this check really ignore postfix increment/decrement? Or maybe this check ignores it and a new check diagnoses `it++` vs `++it` (where possible). What are your thoughts on this?

File: clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp (hunk 5 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/UnusedReturnValueCheck.cpp]: Fixed. I refactor it several times and forget to move it back.

**Comment by HerrCai0907** [comment]
> Should this check really ignore postfix increment/decrement? Or maybe this check ignores it and a new check diagnoses `it++` vs `++it` (where possible). What are your thoughts on this?

@5chmidti  What does `a new check diagnoses `it++` vs `++it` (where possible)` mean?

**Comment by 5chmidti** [comment]
> @5chmidti What does `a new check diagnoses `it++`vs`++it` (where possible)` mean?

I mean this pattern:

```c++
void foo(std::string str) {
  auto iter = str.begin();
  iter++; // prefer ++iter;
  ++iter;

  sink(iter++);
  sink(++iter);

  for (auto i = str.begin(); i != str.end(); ++i) {}
  for (auto i = str.begin(); i != str.end(); i++) {} // prefer ++i
}
```

Where people write `i++` but they really mean `++i`. My question is if this check should ignore both of these cases, or if another check should detect this.

**Comment by HerrCai0907** [comment]
It should be another check in maybe performance, since this check wants to detect unused return instead of iterator.

**Review by 5chmidti — APPROVED** [review]
LGTM from my side, please wait for @PiotrZSL to reconfirm approval/finish review
