### PR TITLE
[HLSL] Disallow writing to readonly resources

### LINKED ISSUE #141842: [HLSL] Read Only Resources incorrectly allow writing
Resources like `Buffer` and `StructuredBuffer` are supposed to be read only but this is not currently enforced.

Ex: https://hlsl.godbolt.org/z/sqMMffh6K fails under DXC but compiles under clang.

This is a bug that should be fixed.

### PR DESCRIPTION
**Pull request by V-FEXrt**
Fixes #141842 

Only add the non-const subscript operator to write resources

### CODE REVIEW

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h [hunk 1]
```diff
@@ -52,6 +52,7 @@ class BuiltinTypeDeclBuilder {
   ClassTemplateDecl *PrevTemplate = nullptr;
   NamespaceDecl *HLSLNamespace = nullptr;
   llvm::StringMap<FieldDecl *> Fields;
+  bool IsConstResourceClass = false;
```
Comment (V-FEXrt) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h]: We don't seem to keep the resource class around in the Builder, so I added this value to track it.

If there is a better way to derive the value/access the resource class please lmk!

**Review by spall — APPROVED** [review]
lgtm from my understanding

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h (hunk 1 above)
Comment (damyanp) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h]: My 2c: It is surprising to me that the RC isn't stored.  It may almost make sense to store it, since I'd be surprised if we don't end up with more things needing stuff inferred from the RC.

Then you can change `if (!IsConstResourceClass)` to `if (RC == llvm::dxil::ResourceClass::UAV)` which IMO is a little bit more direct about what we're doing here.

Comment (bogner) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h]: The other option would be to add a parameter to `addArraySubscriptOperators()` to say whether or not we only want the `const` ones. Personally I think that approach is a little more explicit, but either approach is probably defensible.

Comment (V-FEXrt) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h]: > to add a parameter to

Yeah I thought about that, but then I remembered a conversation we had some time back about how the resource class always implies read/writeness and I didn't want to add another parameter that was always implied by a previous parameter.
More than happy to go that route or the "store the RC" route as they all seem reasonable to me

Comment (bogner) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.h]: Let's go with storing the RC, that seems sensible to me.

**Review by llvm-beanz — APPROVED** [review]

**Review by s-perron — APPROVED** [review]

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp [hunk 2]
```diff
@@ -697,7 +699,9 @@ BuiltinTypeDeclBuilder &BuiltinTypeDeclBuilder::addArraySubscriptOperators() {
       AST.DeclarationNames.getCXXOperatorName(OO_Subscript);
 
   addHandleAccessFunction(Subscript, /*IsConst=*/true, /*IsRef=*/true);
-  addHandleAccessFunction(Subscript, /*IsConst=*/false, /*IsRef=*/true);
+  if (ResClass == llvm::dxil::ResourceClass::UAV)
+    addHandleAccessFunction(Subscript, /*IsConst=*/false, /*IsRef=*/true);
```
Comment (bogner) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp]: I just realized that we can actually simplify this - while we don't store the resource information directly, we do have access to the `handle` member that does keep track of this information at this point via `getResourceHandleField()`. So we could do something like this:
```c++
HLSLAttributedResourceType::Attributes
BuiltinTypeDeclBuilder::getResourceAttrs() const {
  QualType HandleType = getResourceHandleField()->getType();
  return cast<HLSLAttributedResourceType>(HandleType)->getAttrs();
}
```

and then all we need to do is check `getResourceAttrs().ResourceClass` here.

Comment (V-FEXrt) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp]: had to drop the `const` since `getResourceHandleField` isn't `const` but otherwise done!

Comment (V-FEXrt) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp]: nvm going to do it the other way and add `const` to `getResourceHandleField`

**Review by bogner — APPROVED** [review]
