### PR TITLE
[clang-tidy] fix false positives for the functions with the same name as standard library functions in misc-include-cleaner

### LINKED ISSUE #93335: [clang-tidy] misc-include-cleaner false positives
Take the following example code that implements the `log2` function with a custom implementation:

```cpp
constexpr int log2()
{
    int output = 0;
    return output;
}

```

clang-tidy trunk gives:

```
[<[source>:1:15: warning: no header providing "log2" is directly included [misc-include-cleaner]]
    1 | constexpr int log2()
      |               ^
[<source>:3:9: warning: no header providing "output" is directly included [misc-include-cleaner]]
    3 |     int output = 0;
      |         ^
2 warnings generated.
```

Which seems incorrect. Repro: https://godbolt.org/z/roM8E34ce

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #93335
For decl with body, we should provide physical locations also. Because it may be the function which have the same name as std library.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/misc/include-cleaner.cpp [hunk 1]
```diff
@@ -15,3 +15,5 @@ std::string HelloString;
 // CHECK-MESSAGES: :[[@LINE-1]]:6: warning: no header providing "std::string" is directly included [misc-include-cleaner]
 int FooBarResult = foobar();
 // CHECK-MESSAGES: :[[@LINE-1]]:20: warning: no header providing "foobar" is directly included [misc-include-cleaner]
+
+void log2() {}
```
Comment (carlosgalvezp) [inline clang-tools-extra/test/clang-tidy/checkers/misc/include-cleaner.cpp:19]: Maybe write a small comment stating it shouldn't warn, or add a reference to the issue number? That would make it easier to understand why this is here

**Review by PiotrZSL — APPROVED** [review]
LGTM.

File: clang-tools-extra/test/clang-tidy/checkers/misc/include-cleaner.cpp (hunk 1 above)
Comment (HerrCai0907) [inline clang-tools-extra/test/clang-tidy/checkers/misc/include-cleaner.cpp:19]:
```suggestion
namespace gh93335 {
void log2() {}
}
```
