### PR TITLE
[clang][Sema] Fix crash on atomic builtins with incomplete type args

### LINKED ISSUE #96289: Clang-19 crashed: Assertion `D && "Cannot get layout of forward declarations!"' failed.
Compiler explorer(assertion trunck): https://godbolt.org/z/dbE3sr1dh
```
$cat mutant.c
struct S s, t, u;

void a (void)
{
  __atomic_exchange (&s, &t, &u, 0);
}

$clang-19 mutant.c
clang: /root/llvm-project/clang/lib/AST/RecordLayoutBuilder.cpp:3347: const clang::ASTRecordLayout& clang::ASTContext::getASTRecordLayout(const clang::RecordDecl*) const: Assertion `D && "Cannot get layout of forward declarations!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:5:35: current parser token ')'
2.	<source>:4:1: parsing function body 'a'
3.	<source>:4:1: in compound statement ('{}')
 #0 0x0000000003a15b08 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3a15b08)
 #1 0x0000000003a137ec llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3a137ec)
 #2 0x00000000039592e8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007c6d2ac42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007c6d2ac969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007c6d2ac42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007c6d2ac287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007c6d2ac2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007c6d2ac39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000000000797a928 clang::ASTContext::getASTRecordLayout(clang::RecordDecl const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x797a928)
#10 0x0000000007480a14 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7480a14)
#11 0x0000000007468967 clang::ASTContext::getTypeInfo(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7468967)
#12 0x000000000747fb7b clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x747fb7b)
#13 0x0000000007468967 clang::ASTContext::getTypeInfo(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7468967)
#14 0x0000000007480f2b clang::ASTContext::getTypeInfoInChars(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7480f2b)
#15 0x0000000007481013 clang::ASTContext::getTypeInfoInChars(clang::QualType) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7481013)
#16 0x00000000065b4784 clang::Sema::BuildAtomicExpr(clang::SourceRange, clang::SourceRange, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::AtomicExpr::AtomicOp, clang::Sema::AtomicArgumentOrder) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x65b4784)
#17 0x00000000065b6118 clang::Sema::AtomicOpsOverloaded(clang::ActionResult<clang::Expr*, true>, clang::AtomicExpr::AtomicOp) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x65b6118)
#18 0x00000000065debe1 clang::Sema::CheckBuiltinFunctionCall(clang::FunctionDecl*, unsigned int, clang::CallExpr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x65debe1)
#19 0x00000000069765b2 clang::Sema::BuildResolvedCallExpr(clang::Expr*, clang::NamedDecl*, clang::SourceLocation, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, clang::CallExpr::ADLCallKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x69765b2)
#20 0x000000000697743d clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x697743d)
#21 0x000000000697a50c clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x697a50c)
#22 0x000000000640823d clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x640823d)
#23 0x00000000063ff891 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63ff891)
#24 0x0000000006402c6a clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6402c6a)
#25 0x0000000006402e09 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6402e09)
#26 0x00000000064077d9 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x64077d9)
#27 0x0000000006488169 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6488169)
#28 0x000000000647ed35 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x647ed35)
#29 0x000000000647fb97 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x647fb97)
#30 0x00000000064809a5 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x64809a5)
#31 0x000000000648220a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x648220a)
#32 0x0000000006397b03 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6397b03)
#33 0x00000000063cd6ec clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63cd6ec)
#34 0x000000000638b53e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x638b53e)
#35 0x000000000638bd9e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x638bd9e)
#36 0x00000000063924a7 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63924a7)
#37 0x00000000063933af clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63933af)
#38 0x0000000006386baa clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6386baa)
#39 0x0000000004300f28 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4300f28)
#40 0x0000000004587299 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4587299)
#41 0x000000000450cfde clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x450cfde)
#42 0x000000000466f8ae clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x466f8ae)
#43 0x0000000000c6675c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xc6675c)
#44 0x0000000000c5faba ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#45 0x0000000004344209 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#46 0x0000000003959794 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3959794)
#47 0x00000000043447ff clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#48 0x000000000430a6a5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x430a6a5)
#49 0x000000000430b10d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x430b10d)
#50 0x0000000004312e05 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4312e05)
#51 0x0000000000c63c65 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xc63c65)
#52 0x0000000000b3d3d4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xb3d3d4)
#53 0x00007c6d2ac29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#54 0x00007c6d2ac29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#55 0x0000000000c5f56e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xc5f56e)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by hazohelet**
This patch fixes the crash when pointers to incomplete type are passed to atomic builtins such as `__atomic_load`.
`ASTContext::getTypeInfoInChars` assumes that the argument type is a complete type, so I added a check to eliminate cases where incomplete types gets passed to this function

Relevant PR: https://github.com/llvm/llvm-project/pull/91057
Fixes https://github.com/llvm/llvm-project/issues/96289

### CODE REVIEW

**Comment by MitalAshok** [comment]
Could you knock out a related bug at the same time:

```c++
template<typename>
struct X {
  char arr[1];
};

extern X<void>* p, *q;
//X<void> inst;

void f() {
  __atomic_exchange(p, p, q, __ATOMIC_RELAXED);
}
```

With the line commented out, currently this crashes, but in Clang 18 and with your patch, it fails as `X<void>` hasn't been instantiated yet and `isTriviallyCopyableType` is false for incomplete types:

```
test:10:3: error: address argument to atomic operation must be a pointer to a trivially-copyable type ('X<void> *' invalid)
   10 |   __atomic_exchange(p, p, q, __ATOMIC_RELAXED);
      |   ^                 ~
```

`->isIncompleteType()` is true for uninstantiated templates too, so just a `RequireCompleteType` should stop the crash and instantiate templates as needed.

**Comment by Sirraide** [comment]
`RequireCompleteType` seems like the way to go here, yeah.

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -4570,7 +4570,8 @@ ExprResult Sema::BuildAtomicExpr(SourceRange CallRange, SourceRange ExprRange,
   }
 
   // Pointer to object of size zero is not allowed.
-  if (Context.getTypeInfoInChars(AtomTy).Width.isZero()) {
+  if (!AtomTy->isIncompleteType() &&
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaChecking.cpp:4573]: If you call `RequireCompleteType()` before this `if` instead of checking for an incomplete type, do you get better diagnostic behavior?

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! The changes should also come with a release note in `clang/docs/ReleaseNotes.rst` so users know about the improvement.

File: clang/lib/Sema/SemaChecking.cpp (hunk 1 above)
Comment (hazohelet) [reply clang/lib/Sema/SemaChecking.cpp:4573]: The current diagnostic message only says we need trivially-copyable type here, and the `RequireCompleteType` version would say we need complete type here and it sounds more understandable to me.

**Comment by hazohelet** [comment]
Thanks for the feedback. `RequireCompleteType` seems like the right direction.
I'm not writing about the crash fix to the release note because this crash was introduced AFTER clang 18 was released.

**Review by AaronBallman — APPROVED** [review]
LGTM!
