### PR TITLE
[LLD] [COFF] Handle manually defined __imp_ pointers in LTO

### LINKED ISSUE #57982: COFF LTO fails to map locally defined __imp_name symbols
In some cases, it's useful to provide a local definition of a function that was originally declared and referred to as dllimported. In these cases, one can provide a pointer named `__imp_<symbolname>` which points towards the function or variable that provides the definition.

This normally works fine, when not using LTO, and also works fine when either the object file referencing it or providing the definition are compiled with LTO. But when both object files are built with LTO, it fails to resolve the dllimported symbol.

An example of the setup:

```console
$ cat lto-dllimp1.c 
void __declspec(dllimport) importedFunc(void);
void other(void);

void entry(void) {
    importedFunc();
    other();
}
$ cat lto-dllimp2.c 
static void importedFuncReplacement(void) {
}
void (*__imp_importedFunc)(void) = importedFuncReplacement;

void other(void) {
}
```

Building and linking without LTO succeeds:

```console
$ clang -target x86_64-windows-msvc -c lto-dllimp1.c 
$ clang -target x86_64-windows-msvc -c lto-dllimp2.c 
$ llvm-nm lto-dllimp1.o lto-dllimp2.o

lto-dllimp1.o:
00000000 a @feat.00
         U __imp_importedFunc
00000000 T entry
         U other
 
lto-dllimp2.o:
00000000 a @feat.00 
00000000 D __imp_importedFunc 
00000000 t importedFuncReplacement 
00000010 T other

$ lld-link lto-dllimp1.o lto-dllimp2.o -out:lto-dllimp.dll -dll -entry:entry
```

Building and linking with LTO fails:
```console
$ clang -target x86_64-windows-msvc -c lto-dllimp1.c -flto 
$ clang -target x86_64-windows-msvc -c lto-dllimp2.c -flto 
$ llvm-nm lto-dllimp1.o lto-dllimp2.o 

lto-dllimp1.o:
                 U __imp_importedFunc
---------------- T entry
                 U other

lto-dllimp2.o:
---------------- D __imp_importedFunc
---------------- t importedFuncReplacement
---------------- T other

$ lld-link lto-dllimp1.o lto-dllimp2.o -out:lto-dllimp.dll -dll -entry:entry -demangle:no
lld-link: error: undefined symbol: __imp_importedFunc
>>> referenced by lto-dllimp.dll.lto.obj:(entry)
```

I'm not quite familiar with the LTO internals myself to know where to start looking at this; CC @MaskRay who might have some experience in the area?

### PR DESCRIPTION
**Pull request by mstorsjo**
Such pointers are often used by the core parts of mingw-w64, to locally define a function that might have been referred to with dllimport.

(MSVC style linkers can automatically provide such pointers, if there are undefined references to `__imp_<func>` left but a definition of `<func>` is available - although this prints the warning LNK4217. GNU ld doesn't do this, so in mingw-w64, such things are generally handled by manually providing the relevant `__imp_` pointers.)

Make sure that a full LTO build, that does LTO of both the `__imp_` pointer and the object file referencing it, successfully resolves such symbols.

This solution admittedly probably reduces the effect of the LTO compilation if there would happen to be `__imp_` prefixed symbols included, in LTO objects, that aren't actually used. Such symbols are mostly used in the base toolchain, not often in user code, and usually only the relevant object files are linked in anyway.

This fixes https://github.com/llvm/llvm-project/issues/57982.

### CODE REVIEW

File: lld/COFF/InputFiles.cpp [hunk 1]
```diff
@@ -1061,6 +1061,11 @@ void BitcodeFile::parse() {
     } else {
       sym = ctx.symtab.addRegular(this, symName, nullptr, fakeSC, 0,
                                   objSym.isWeak());
+      // If one LTO object defines a __imp_<foo> symbol, and another LTO
```
Comment (rnk) [inline lld/COFF/InputFiles.cpp:1064]: The use case you've described is very specific, can you please lead with a higher-level comment about what this code does? As a suggestion, you can start with:
// Model all symbols with the `__imp_` prefix as having external references. If one LTO object ...

**Review by rnk — APPROVED** [review]

File: lld/COFF/InputFiles.cpp (hunk 1 above)
Comment (mstorsjo) [reply lld/COFF/InputFiles.cpp]: Sure, done - thanks!

**Comment by MaskRay** [comment]
This patch forces `__imp_sym` to be retained in the output. Am I right that this could be relaxed to when `sym` is referenced? But that would introduce some complexity as `__imp_sym` `sym->isUsedInRegularObj = true;` needs to be done after all input files are parsed.

**Comment by mstorsjo** [comment]
> This patch forces `__imp_sym` to be retained in the output. Am I right that this could be relaxed to when `sym` is referenced?

Yes, that's correct.

> But that would introduce some complexity as `__imp_sym` `sym->isUsedInRegularObj = true;` needs to be done after all input files are parsed.

Indeed - something like what I do in #71376 could perhaps help here as well - but this case is a bit trickier. When LLD looks at the bitcode object files, it sees one with an undefined `__imp_sym` and one with a defined `__imp_sym` - i.e. a perfectly normal situation, nothing to do about that. But when the LTO engine compiles it, it sees one defined `__imp_sym` with no references within the set of bitcode files, and one undefined `sym` with a dllimport attribute.

In practice I don't think this affects the overall end result much, because this kind of trickery with manually defined `__imp_` symbols is very rare in normal code; it's used a bunch within mingw-w64-crt, but also there, the link would mostly include those object files that actually are needed. But perhaps it does end up retaining a handful of `__imp_` pointers that might not be needed. I would think that MSVC like environments almost never use this construct.

Ideally, the optimal condition would be to only mark `isUsedInRegularObj` on any defined bitcode symbol with an `__imp_` prefix, if any other of the bitcode input files has an undefined `__imp_sym` symbol. I'll see if I get time to take another shot at this.
