### PR TITLE
[Clang][analyzer] replace Stmt* with ConstCFGElement in SymbolConjured (reland)

### LINKED ISSUE #57270: [analyzer] Crash using `clang_analyzer_explain()` in the `debug.ExprInspection` checker
The following snippet causes the Static Analyzer to fail an assertion in debug mode, or crash in release mode.

```c++
struct S {
    static int a;
    ~S(){};
};
int S::a = 0;

void foo() {
    S::a = 0;

    int x = 3;
    memset(&x, 1, sizeof(x));

    S *arr = new S[x];
    delete[] arr;

    clang_analyzer_explain(S::a);
}
```

`memset` sets the value of `S::a` to `derived_$12{conj_$8{int, LC1, no stmt, #1},a}`, and later when `clang_analyzer_explain()` tries to explain the value, it encounters a `nullptr` which it dereferences.

`conj_$8{int, LC1, no stmt, #1}` doesn't contain any statement, so when `SValExplainer::VisitSymbolConjured()` calls `SValExplainer::printStmt(const Stmt *S)` it passes a `nullptr` to it as an argument. The called function assumes it always receives a valid pointer, and it simply calls `S->printPretty()` without any validation, and this is when the crash happens.

For more information please see [godbolt](https://godbolt.org/z/hMYcs8f8z).

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Closes #57270.

This PR changes the `Stmt *` field in `SymbolConjured` with
`CFGBlock::ConstCFGElementRef`. The motivation is that, when conjuring a
symbol, there might not always be a statement available, causing
information to be lost for conjured symbols, whereas the CFGElementRef
can always be provided at the callsite.

Following the idea, this PR changes callsites of functions to create
conjured symbols, and replaces them with appropriate `CFGElementRef`s.

There is a caveat at loop widening, where the correct location is the
CFG terminator (which is not an element and does not have a ref). In
this case, the first element in the block is passed as a location.

Previous PR #128251, Reverted at #137304.

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
Range diff against previous PR: https://gist.github.com/fangyi-zhou/7d3a73a9b95f93755af3e823228c7a0d

**Comment by fangyi-zhou** [comment]
@steakhal

**Comment by fangyi-zhou** [comment]
gentle ping

**Comment by steakhal** [comment]
Sorry about my availability. I barely have any focus time these days.
Could you please split your commit into: 1) the original commit we had to later revert, 2) the changes to fix it that would make it on par with what you have here now

This would allow me to review the affected parts, saving me precious time. I know you did a diff of the diffs, but that's not really helpful.

**Comment by fangyi-zhou** [comment]
Hi @steakhal 

Sorry to hear that you're busy. The main change wrt the previous commits are
(1) Rebase past the refactor in #137182
(2) Fix the bug that caused the ASan failure (when we visit a CFG block entrance)

I try to split the commit into two, but I'll mark the change in (2) in the meantime

File: clang/lib/StaticAnalyzer/Core/ExprEngine.cpp [hunk 1]
```diff
@@ -2556,10 +2556,19 @@ void ExprEngine::processCFGBlockEntrance(const BlockEdge &L,
...
+    // FIXME:
+    // We cannot use the CFG element from the via `ExprEngine::getCFGElementRef`
+    // since we are currently at the block entrance and the current reference
+    // would be stale.  Ideally, we should pass on the terminator of the CFG
+    // block, but the terminator cannot be referred as a CFG element.
+    // Here we just pass the the first CFG element in the block.
     ProgramStateRef WidenedState =
-        getWidenedLoopState(Pred->getState(), LCtx, BlockCount, Term);
+        getWidenedLoopState(Pred->getState(), LCtx, BlockCount,
+                            *nodeBuilder.getContext().getBlock()->ref_begin());
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2571]: Main change here: instead of passing the current CFG element in engine state, we use the first element in the current block.

**Comment by fangyi-zhou** [comment]
Gentle ping

**Review by steakhal — APPROVED** [review]
LGTM. Thanks for the ping.

**Comment by gregbedwell** [comment]
We've observed a crash in clang since this commit when using `--analyze` in conjunction with `-ftime-trace`.  I've put the details in #139779.  Please could you take a look?
