### PR TITLE
[lldb] Support stepping through C++ thunks

### LINKED ISSUE #43413: LLDB Not Stepping into Multiple Inheritance Virtual Functions
|  |  |
| --- | --- |
| Bugzilla Link | [44068](https://llvm.org/bz44068) |
| Version | 9.0 |
| OS | Linux |
| Attachments | [Reproducer program.](https://user-images.githubusercontent.com/93435986/143760089-c9cc6894-c09b-489e-a8c4-a764429952ee.gz) |
| CC | @rdtscp,@JDevlieghere,@jimingham |

## Extended Description 

Overview:

Using LLDB to debug polymorphic objects that have multiple inheritance will not step into virtual functions.

Steps to Reproduce:
```
$ clang++ -std=c++11 -g -O0 reproducer.cpp -o clang.out
$ lldb clang.out
(lldb) target create "clang.out"
Current executable set to 'clang.out' (x86_64).
(lldb) b 36                                                                                                                                                                       Breakpoint 1: where = clang.out`main + 103 at reproducer.cpp:36:16, address = 0x0000000000400d67
(lldb) r
Process 2764 launched: '/home/rdtscp/Documents/lldb_reproducer/clang.out' (x86_64)
Process 2764 stopped
* thread #&#8203;1, name = 'clang.out', stop reason = breakpoint 1.1
    frame #&#8203;0: 0x0000000000400d67 clang.out`main(argc=1, argv=0x00007fffffffe808) at reproducer.cpp:36:16
   33  	int main(int argc, char **argv) {
   34  	  using namespace Test;
   35  	  std::shared_ptr<Interface> object = std::shared_ptr<Concrete>(new Concrete());
-> 36  	  int output = object->vFun();
   37  	  std::cout << output << std::endl;
   38  	  return output;
   39  	}
(lldb) s
Process 2764 stopped
* thread #&#8203;1, name = 'clang.out', stop reason = step in
    frame #&#8203;0: 0x0000000000400d86 clang.out`main(argc=1, argv=0x00007fffffffe808) at reproducer.cpp:37:16
   34  	  using namespace Test;
   35  	  std::shared_ptr<Interface> object = std::shared_ptr<Concrete>(new Concrete());
   36  	  int output = object->vFun();
-> 37  	  std::cout << output << std::endl;
   38  	  return output;
   39  	}
(lldb)
```

Altering the `Concrete` class to be:
```
class Concrete : // public Base,
		 public Interface {
public:
  virtual int vFun() override {
    volatile int x = rand();
    if (x > 0)
      return x;
    else
      return 0;
  }
};
```

Will result in:
```
$ clang++ -std=c++11 -g -O0 reproducer.cpp -o clang.out
$ lldb clang.out
(lldb) target create "clang.out"
Current executable set to 'clang.out' (x86_64).
(lldb) b 36
Breakpoint 1: where = clang.out`main + 104 at reproducer.cpp:36:16, address = 0x0000000000400cf8
(lldb) r
Process 2869 launched: '/home/rdtscp/Documents/lldb_reproducer/clang.out' (x86_64)
Process 2869 stopped
* thread #&#8203;1, name = 'clang.out', stop reason = breakpoint 1.1
    frame #&#8203;0: 0x0000000000400cf8 clang.out`main(argc=1, argv=0x00007fffffffe808) at reproducer.cpp:36:16
   33  	int main(int argc, char **argv) {
   34  	  using namespace Test;
   35  	  std::shared_ptr<Interface> object = std::shared_ptr<Concrete>(new Concrete());
-> 36  	  int output = object->vFun();
   37  	  std::cout << output << std::endl;
   38  	  return output;
   39  	}
(lldb) s
Process 2869 stopped
* thread #&#8203;1, name = 'clang.out', stop reason = step in
    frame #&#8203;0: 0x0000000000400fec clang.out`Test::Concrete::vFun(this=0x0000000000615c20) at reproducer.cpp:23:24
   20  			   public Interface {
   21  	  public:
   22  	    virtual int vFun() override {
-> 23  	      volatile int x = rand();
   24  	      if (x > 0)
   25  		return x;
   26  	      else
(lldb)
```

The above shows that making the `Concrete` class inherit from the `Base` class prevents us from stepping into `vFun()`.

System Settings:
```
OS: Debian GNU/Linux 9.11 (stretch) x86_64
Model: VirtualBox 1.2
Kernel: 4.9.0-11-amd64
Uptime: 1 hour, 3 minutes
Packages: 1722
Shell: zsh 5.3.1
CPU: Intel i5-7360U (1) @ 2.3GHz
GPU: VMware SVGA II Adapter
Memory: 219MB / 996MB
```

```
$ clang++ --version
clang version 9.0.0-svn364966-1~exp1+0~20190702204433.1332~1.gbpb44072 (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ lldb --version
lldb version 9.0.0
```

Additional Information:
I tried using:
```
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
```

To see if my code was incorrect, but g++ and gdb were able to step into "vFun()" fun.

### PR DESCRIPTION
**Pull request by JDevlieghere**
This PR fixes LLDB stepping out, rather than stepping through a C++ thunk. The implementation is based on, and upstreams, the support for runtime thunks in the Swift fork.

Fixes #43413

### CODE REVIEW

File: lldb/source/Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.cpp [hunk 1]
```diff
@@ -476,3 +476,9 @@ CPPLanguageRuntime::GetStepThroughTrampolinePlan(Thread &thread,
 
   return ret_plan_sp;
 }
+
+bool CPPLanguageRuntime::IsSymbolARuntimeThunk(const Symbol &symbol) {
+  llvm::outs() << symbol.GetMangled().GetMangledName().GetStringRef() << '\n';
```
Comment (Michael137) [inline lldb/source/Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.cpp:481]:
```suggestion
  llvm::outs() << symbol.GetMangled().GetMangledName().GetStringRef() << '\n';
```
leftover debug?

**Comment by levy** [comment]
I'm the one who recently added an example reproducing the #43413 issue. I compiled this PR version of lldb and related tools and tested it against the simple reproduction I added to the issue, and also with our complex project where I first faced this issue. In both cases lldb works as expected with this patch.

Thank you very much!

**Comment by tedwoodward** [comment]
@JDevlieghere would you mind getting rid of the nullptr in the testcase, main.cpp line 13?
Base2 *b = nullptr;

*b is set to nullptr per language standard, and those of use stuck in c++03 on embedded targets would appreciate it!

File: lldb/source/Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.cpp [hunk 2]
```diff
@@ -476,3 +476,12 @@ CPPLanguageRuntime::GetStepThroughTrampolinePlan(Thread &thread,
 
   return ret_plan_sp;
 }
+
+bool CPPLanguageRuntime::IsSymbolARuntimeThunk(const Symbol &symbol) {
+  // Virtual function override thunks come in two forms. Those overriding from a
+  // non-virtual base, with fixed this adjustments, use a "Th" prefix and encode
+  // the required adjustment offset, probably negative, indicated by a 'n'
+  // prefix, and the encoding of the target function.
+  return symbol.GetMangled().GetMangledName().GetStringRef().starts_with(
```
Comment (Michael137) [inline lldb/source/Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.cpp:485]: Hmm i think we also want to check `Tc` and `Tv`?

`Tv` you can test by inheriting one of the bases virtually. And here's an example of a `Tc` encoding:
```
struct V1 { };                 
struct V2 : virtual V1 { };    
                               
struct A {                     
  virtual V1 *f();             
};                             
                               
struct B : A {                 
  virtual void b();            
                               
  virtual V2 *f();             
};                             
                               
V2 *B::f() { return 0; }       
                              
```

```
$ c++filt -n _ZTch0_v0_n24_N1B1fEv
covariant return thunk to B::f()

```

Comment (JDevlieghere) [reply lldb/source/Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.cpp]: I should've read the whole paragraph :-)

File: lldb/source/Target/ThreadPlanShouldStopHere.cpp [hunk 3]
```diff
@@ -76,6 +77,18 @@ bool ThreadPlanShouldStopHere::DefaultShouldStopHereCallback(
     }
   }
 
+  // Check whether the frame we are in is a language runtime thunk, only for
+  // step out:
+  if (operation == eFrameCompareOlder) {
+    Symbol *symbol = frame->GetSymbolContext(eSymbolContextSymbol).symbol;
+    if (symbol) {
```
Comment (medismailben) [inline lldb/source/Target/ThreadPlanShouldStopHere.cpp:84]: nit:

```suggestion
    if (Symbol *symbol = frame->GetSymbolContext(eSymbolContextSymbol).symbol) {
```

**Review by medismailben — APPROVED** [review]
Nice! LGTM with comment.

**Review by jimingham — APPROVED** [review]
LGTM
