### PR TITLE
[clang] Fix possible nullptr deref in BuildCXXNestedNameSpecifier

### LINKED ISSUE #166843: [clangd] Assertion failure in clangd: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
We're seeing an assertion fire in clangd
```
clangd: llvm/include/llvm/Support/Casting.h:656: decltype(auto) llvm::dyn_cast(From *) [To = clang::UsingShadowDecl, From = const clang::NamedDecl]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
```

I'm working on getting code and logs I can share, since we're seeing this in internal code. This may take me a bit but I wanted to report this as early as possible. The code base triggering this had a pretty massive upgrade from 03b0f55d9c6319a851a60bb084faca0e32a38f2b to 62adc83c918b1b55f70e4ee33c727b040da2a9ed, but I'm still able to trigger the assertions as of this morning.

I'm aware of https://clangd.llvm.org/troubleshooting, so I'll try to get logs, a simplified command, and a credeuced/sanitized source file, but some of these steps can take a bit to complete.

### PR DESCRIPTION
**Pull request by ilovepi**
There is a possible nullptr deref in BuildCXXNestedNameSpecifier when calling ExtendNestedNameSpecifier or using isa<>. This initially showed up as a crash in clangd, that didn't manifest in when compiling w/ clang. The reduced test case added in this patch, however does expose the issue in clang. Testing locally shows that both this test case and the original clangd issue are fixed by checking the validity of the pointer before trying to dispatch. Since all code paths require the pointer to be valid (usually by virtue of a dyn_cast or isa<> check), there should be no functional difference.

Fixes #166843

### CODE REVIEW

File: clang/lib/Sema/SemaCXXScopeSpec.cpp [hunk 1]
```diff
@@ -779,25 +779,26 @@ bool Sema::BuildCXXNestedNameSpecifier(Scope *S, NestedNameSpecInfo &IdInfo,
...
-      ParsedType SuggestedType;
-      DiagnoseUnknownTypeName(IdInfo.Identifier, IdInfo.IdentifierLoc, S, &SS,
-                              SuggestedType);
-    } else {
-      Diag(IdInfo.IdentifierLoc, diag::err_expected_class_or_namespace)
-          << IdInfo.Identifier << getLangOpts().CPlusPlus;
-      if (NamedDecl *ND = Found.getAsSingle<NamedDecl>())
-        Diag(ND->getLocation(), diag::note_entity_declared_at)
-            << IdInfo.Identifier;
+    if (const auto *ND = Found.getAsSingle<NamedDecl>()) {
```
Comment (mizvekov) [inline clang/lib/Sema/SemaCXXScopeSpec.cpp]: Please bail out early to reduce the diff.

**Review by mizvekov — CHANGES_REQUESTED** [review]
Thanks for working on this.

Please include test case.

**Comment by ilovepi** [comment]
> Thanks for working on this.
> 
> Please include test case.

Thanks for pointing that out. I forgot to add it to git 🤦

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks.

File: clang/test/Sema/PR166843.cpp [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// RUN: %clang_cc1 -fsyntax-only %s -verify
+namespace a {
+template <class b>
+void c() {
+  ((::c::)); // expected-error {{expected unqualified-id}}
```
Comment (efriedma-quic) [inline clang/test/Sema/PR166843.cpp]: This looks like we aren't actually diagnosing the error?  I'd expect something like `error: 'c' is not a class, namespace, or enumeration`, which is what we generate in the non-template case.

What happens if you instead write the following?

```
  ((::c::x));
```

Comment (ilovepi) [reply clang/test/Sema/PR166843.cpp]: i've updated the early exit by duplicating the diagnostic. I didn't see an obvious way to avoid doing that. Happy to amend if this still isn't quite right.

**Review by efriedma-quic — APPROVED** [review]
LGTM
