### PR TITLE
[clang] require template arg list after template kw

### LINKED ISSUE #53095: `.template` not followed by template arguments is incorrectly accepted
Consider this example:
```cpp
#include <iostream>

struct A
{
    void foo() {std::cout << "1\n";}
    
    template <typename T = int>
    void foo() {std::cout << "2\n";}
};

int main()
{
    A x;
    x.template foo();
}
```
Clang prints `2`. But the code shouldn't be accepted at all, since [`[temp.names]/5`](https://timsong-cpp.github.io/cppwp/n3337/temp.names#5) says that the name after `.template`/`->template` must be a *template-id*, aka must have explicitly specified template arguments. [Here's a stackoverflow thread](https://stackoverflow.com/q/70635683/2752075).

**Note**: this doesn't apply to `foo::template MyClassTemplate`, which is legal, but seems to be made optional (and deprecated at the same time) in C++2b.

### PR DESCRIPTION
**Pull request by evelez7**
Require a template argument list after an identifier prefixed by the template keyword. Introduced by [CWG 96](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#96), but the current wording of [[temp.names]p5](https://eel.is/c++draft/temp.names#6) was introduced in [P1787R6](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html), and became [temp.names]p6 somewhere else.

Fixes #53095

### CODE REVIEW

File: clang/test/CXX/drs/dr0xx.cpp [hunk 1]
```diff
@@ -1414,7 +1414,7 @@ namespace dr96 { // dr96: no
     // FIXME: This is ill-formed, because 'f' is not a template-id and does not
```
Comment (Endilll) [inline clang/test/CXX/drs/dr0xx.cpp:1414]: I guess this FIXME is superseded by P1787R6, the same way 2010 resolution is.

File: clang/test/CXX/drs/dr0xx.cpp [hunk 2]
```diff
@@ -1414,7 +1414,7 @@ namespace dr96 { // dr96: no
...
     // name a class template.
     // FIXME: What about alias templates?
```
Comment (Endilll) [inline clang/test/CXX/drs/dr0xx.cpp:1416]: Indeed, what about alias templates? My guess is that new rules work for them as well: no template argument list — no `template`.

File: clang/test/CXX/drs/dr0xx.cpp [hunk 3]
```diff
@@ -1414,7 +1414,7 @@ namespace dr96 { // dr96: no
...
-    int k2 = a.template f(1);
+    int k2 = a.template f(1); // expected-error {{a template argument list is expected after a name prefixed by the template keyword}}
```
Comment (Endilll) [inline clang/test/CXX/drs/dr0xx.cpp:1417]: Can you use `// expected-error@-1` style, like the rest of the file?

**Review by Endilll — CHANGES_REQUESTED** [review]
Thank you picking this up!

Since this patch seems to implement current take of the Standard on CWG96, you should change `// dr96: no` to `// dr96: sup P1787` at `dr0xx.cpp:1403`, and then run `clang/www/make_cxx_dr_status` script to regenerate `cxx_dr_status.html`. While this status is not officially recognized (at least yet), it's the only one that makes sense for CWG96 now.

You should also mention in the description that CWG96 resolution from Feb 2010 is superseded by changes to [temp.names]/5 introduced by P1787R6, to make it easier for people to find exact wording in that gigantic paper.

File: clang/include/clang/Basic/DiagnosticParseKinds.td [hunk 4]
```diff
@@ -868,6 +868,9 @@ def err_requires_expr_in_simple_requirement : Error<
   "requires expression in requirement body; did "
   "you intend to place it in a nested requirement? (add another 'requires' "
   "before the expression)">;
+def err_missing_template_arg_list_after_template_kw : Error<
+  "a template argument list is expected after a name prefixed by the template "
+  "keyword">;
```
Comment (cor3ntin) [inline clang/include/clang/Basic/DiagnosticParseKinds.td:873]: This should be a pedantic warning (maybe defaulting to an error)
Otherwise we might break existing (non conforming) code

https://github.com/search?q=%2Fs%5C.template+%5Ba-zA_Z_%5D%2B%5B%28%5D%2F+language%3AC%2B%2B&type=code

File: clang/test/CXX/drs/dr0xx.cpp (hunk 2 above)
Comment (evelez7) [reply clang/test/CXX/drs/dr0xx.cpp:1416]: The use of 'template' before an alias template is [deprecated](https://eel.is/c++draft/depr.template.template), along with before a class template. I wasn't sure how to interpret this for clang, they aren't errors yet?

Comment (opensdh) [reply clang/test/CXX/drs/dr0xx.cpp:1416]: The alias template case was aligned with the class-template case as part of [CWG1710](https://cplusplus.github.io/CWG/issues/1710.html).

File: clang/test/CXX/drs/dr0xx.cpp (hunk 1 above)
Comment (opensdh) [reply clang/test/CXX/drs/dr0xx.cpp:1414]: I'm not sure what direction of "superseded" you mean here, but (except for the separable alias-template bit) the comment is simply correct (since CWG96; before that any template would do).  All that P1787R6 did here was correct the strange use of "name" to refer to (among other things) a *template-id* and deprecate the `T::template NestedTypeTemplate` case.

Comment (Endilll) [reply clang/test/CXX/drs/dr0xx.cpp:1414]: @opensdh Thank you for the clarification. I guess I read [N1528](https://wg21.link/n1528)
Would it be a correct statement to make that you deprecated the following case described in that paper?
> Consequently, the recommendation of this paper is: If the template keyword is followed by a name that does not have a template-argument-list, the name must refer to a class template and be used in a context in which a class template is valid, otherwise the program is ill-formed.

File: clang/include/clang/Basic/DiagnosticParseKinds.td (hunk 4 above)
Comment (evelez7) [reply clang/include/clang/Basic/DiagnosticParseKinds.td:873]: > This should be a pedantic warning (maybe defaulting to an error) Otherwise we might break existing (non conforming) code

I've done this by adding this as a warning to the Pedantic diagnostic group, but I've had to increment the number in `test/Misc/warning-flags.c:91`, and there's a rather stern warning about not adding to `-Wpedantic`. Would this be ok?

File: clang/test/CXX/drs/dr0xx.cpp (hunk 1 above)
Comment (opensdh) [reply clang/test/CXX/drs/dr0xx.cpp:1414]: Yes, P1787R6 deprecated that use case; you're supposed to just not use `template` there.  This is consistent with the _recommendation_ in N1528, but of course we now reject the premise that `template` is _needed_ for a template template argument.  The reasoning, if it helps, is that compilers already have to deal with ambiguity there:
```cpp
template<auto> void f();                                // #1
template<class> void f(int=0);                          // #2
template<template<class> class> void f(void*=nullptr);  // #3

template<class T> void g() {
  // in C++20, [temp.res]/6 and [temp.arg.template]/1 contradict each other here:
  f<T::Q>();             // could be #1 or #3
}
template<class T> struct X {
  // OK per [temp.local]/1
  void h() {f<X>(T());}  // could be #2 or #3
  void i() {T::template R<X>();}  // could be anything
}
```
Accordingly, [CWG1478](https://cplusplus.github.io/CWG/issues/1478.html)'s question was answered in the negative, and `template` (is to be) restricted to the case where it influences the interpretation of a `<`.

**Comment by evelez7** [comment]
I was wondering why the Windows CI was failing but seems to be bugged according to Discourse. Newest commit changes the error to a pedantic warning that defaults to an error.

**Comment by evelez7** [comment]
ping

**Comment by evelez7** [comment]
ping @Endilll

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 5]
```diff
@@ -2995,13 +2996,23 @@ bool Parser::ParseUnqualifiedId(CXXScopeSpec &SS, ParsedType ObjectType,
...
+          Actions.ActOnTemplateName(getCurScope(), SS, *TemplateKWLoc, Result,
+                                    ObjectType, EnteringContext, Template,
+                                    /*AllowInjectedClassName*/ true);
+      if (TNK == TNK_Non_template)
+        return true;
+
+      // C++ [template.names]p6
+      // A name prefixed by the keyword template shall be followed by a template
+      // argument list or refer to a class template or an alias template.
+      if ((TNK == TNK_Function_template || TNK == TNK_Dependent_template_name ||
```
Comment (AaronBallman) [inline clang/lib/Parse/ParseExprCXX.cpp:3011]: What about type templates: https://godbolt.org/z/1coGTT38P (hmm we may have a wider issue there, from looking at Clang's current behavior, so a FIXME would be reasonable too).

**Review by AaronBallman — COMMENTED** [review]
Thank you for this! The changes should also come with a release note in clang/docs/ReleaseNotes.rst so users know about the change.

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 6]
```diff
@@ -2995,13 +2996,23 @@ bool Parser::ParseUnqualifiedId(CXXScopeSpec &SS, ParsedType ObjectType,
...
-                 getCurScope(), SS, *TemplateKWLoc, Result, ObjectType,
-                 EnteringContext, Template,
-                 /*AllowInjectedClassName*/ true) == TNK_Non_template)
-      return true;
 
+    if (TemplateSpecified) {
+      TemplateNameKind TNK =
+          Actions.ActOnTemplateName(getCurScope(), SS, *TemplateKWLoc, Result,
+                                    ObjectType, EnteringContext, Template,
+                                    /*AllowInjectedClassName*/ true);
```
Comment (shafik) [inline clang/lib/Parse/ParseExprCXX.cpp:3004]:
```suggestion
                                    /*AllowInjectedClassName=*/true);
```
nitpick

File: clang/lib/Parse/ParseExprCXX.cpp (hunk 5 above)
Comment (evelez7) [reply clang/lib/Parse/ParseExprCXX.cpp:3042]: Yeah this case isn't covered here. The error fires before reaching this method. I can try to diagnose it for this patch if needed, or I can do a followup patch.

File: clang/test/CXX/drs/cwg0xx.cpp [hunk 7]
```diff
@@ -1404,7 +1404,11 @@ namespace cwg95 { // cwg95: 3.3
   //   expected-note@#cwg95-C-f {{implicitly declared private here}}
 }
 
+<<<<<<< HEAD:clang/test/CXX/drs/cwg0xx.cpp
 namespace cwg96 { // cwg96: no
+=======
+namespace dr96 { // dr96: sup P1787
+>>>>>>> c639768eef90 (change error to pedenatic warn, regen DR html):clang/test/CXX/drs/dr0xx.cpp
```
Comment (cor3ntin) [inline clang/test/CXX/drs/cwg0xx.cpp:1411]: There are conflicts markers left here

File: clang/docs/ReleaseNotes.rst [hunk 8]
```diff
@@ -251,6 +251,9 @@ Resolutions to C++ Defect Reports
 - P0522 implementation is enabled by default in all language versions, and
   provisional wording for CWG2398 is implemented.
 
+- Require a template argument list after a template keyword.
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:254]:
```suggestion
- Clang now requires a template argument list after a template keyword.
```

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 9]
```diff
@@ -3026,13 +3027,23 @@ bool Parser::ParseUnqualifiedId(CXXScopeSpec &SS, ParsedType ObjectType,
...
 
+    if (TemplateSpecified) {
+      TemplateNameKind TNK =
+          Actions.ActOnTemplateName(getCurScope(), SS, *TemplateKWLoc, Result,
+                                    ObjectType, EnteringContext, Template,
+                                    /*AllowInjectedClassName=*/true);
+      if (TNK == TNK_Non_template)
+        return true;
+
+      // C++ [template.names]p6
```
Comment (cor3ntin) [inline clang/lib/Parse/ParseExprCXX.cpp:3039]:
```suggestion
      // C++2c [tem.names]p6
```

File: clang/lib/Parse/ParseExprCXX.cpp (hunk 5 above)
Comment (AaronBallman) [reply clang/lib/Parse/ParseExprCXX.cpp:3042]: I think it's reasonable to handle in a follow-up, thanks!

**Review by AaronBallman — APPROVED** [review]
I think the changes are reasonable, but I'd like to wait a bit before landing to give @erichkeane a chance to review as templates code owner.

**Review by erichkeane — APPROVED** [review]
