### PR TITLE
[clang-format] Fix a regression on annotating template angles

### LINKED ISSUE #132248: [clang-format] incorrect formatting of type trait in assigment
$ cat bug.cpp
```
#include <cstdint>
#include <type_traits>

namespace foo
{

enum class TypeKind : std::uint8_t
{
    KindA = 0,
    KindB
};

constexpr auto kTypeKind =
#ifdef TYPE_KIND_A
    TypeKind::KindA;
#else
    TypeKind::KindB;
#endif

namespace detail
{
constexpr auto kBpfMtu = 1512;
constexpr auto kIoSockMtu = 1518;

constexpr std::uint16_t kMTU = std::conditional<kTypeKind == TypeKind::KindA,
                                                std::integral_constant<std::uint16_t, kBpfMtu>,
                                                std::integral_constant<std::uint16_t, kIoSockMtu>>::type::value;
}  // namespace detail

}  // namespace foo
```

run: `clang-format bug.cpp`

expected would be something like:
```
constexpr std::uint16_t kMTU = std::conditional<kTypeKind == TypeKind::KindA,
                                                std::integral_constant<std::uint16_t, kBpfMtu>,
                                                std::integral_constant<std::uint16_t, kIoSockMtu>>::type::value;
```

actual formatting:
```
constexpr std::uint16_t kMTU = std::conditional < kTypeKind == TypeKind::KindA,
                        std::integral_constant<std::uint16_t, kBpfMtu>,
                        std::integral_constant < std::uint16_t,
                        kIoSockMtu >> ::type::value;
```

Worked fine with clang-format-18.
Occurs for clang-format-19 and 20.

### PR DESCRIPTION
**Pull request by owenca**
Annotate the angles in `A<B != A>B` as template opener/closer as it's unlikely that they are less/greater-than operators in this context.

Fix #132248

### CODE REVIEW

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -720,8 +720,9 @@ TEST_F(TokenAnnotatorTest, UnderstandsNonTemplateAngleBrackets) {
 
   Tokens = annotate("return A < B != A > B;");
   ASSERT_EQ(Tokens.size(), 10u) << Tokens;
-  EXPECT_TOKEN(Tokens[2], tok::less, TT_BinaryOperator);
-  EXPECT_TOKEN(Tokens[6], tok::greater, TT_BinaryOperator);
+  // FIXME:
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:723]: Just a thought, could we check the token after `greater`? If it is an identifier it can never be a template.

**Review by mydeveloperday — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:723]: It can be a template closer e.g. in declarations with implicit instantiated template types? IMO we should rework `parseAngle()` instead of adding more heuristics for special cases such as `A<B != C> D` that must be an expression if preceded by `return`.
