### PR TITLE
[Clang] Stop changing DC when instantiating dependent friend specializations

### LINKED ISSUE #139052: Clang Crash When Defining operator<< as a Friend Template Function of a Class Template since clang 20
Clang crashes during instantiation of a friend function template declared outside the class when used with BinaryTree<T>. The crash occurs in the function InstantiateFunctionDefinition in clang 20. **Haven´t been able to reduce code more**

## Assertion 

```
clang++: /root/llvm-project/llvm/tools/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5767: void clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool): Assertion `It != Primary->redecls().end() && "Should't get here without a definition"' failed.`
```

## Stack dump

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -x c++ <source>
1.	<eof> parser at end of file
2.	<source>:19:26: instantiating function definition 'operator<<<int>'
 #0 0x0000000003f7c0a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f7c0a8)
 #1 0x0000000003f79d34 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f79d34)
 #2 0x0000000003ebebf8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000790a8e642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000790a8e6969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000790a8e642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000790a8e6287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000790a8e62871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000790a8e639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000007244186 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7244186)
#10 0x0000000007241b46 clang::Sema::PerformPendingInstantiations(bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7241b46)
#11 0x0000000006790242 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::TUFragmentKind) (.part.0) Sema.cpp:0:0
#12 0x0000000006790ae2 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6790ae2)
#13 0x00000000065fe6eb clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65fe6eb)
#14 0x00000000065f09ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f09ea)
#15 0x000000000491ebe8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x491ebe8)
#16 0x0000000004c11f15 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c11f15)
#17 0x0000000004b9131e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b9131e)
#18 0x0000000004d05d39 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4d05d39)
#19 0x0000000000da788f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda788f)
#20 0x0000000000d9da5a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#21 0x00000000049854a9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#22 0x0000000003ebf094 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ebf094)
#23 0x0000000004985abf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#24 0x0000000004947f0d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4947f0d)
#25 0x0000000004948f9e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4948f9e)
#26 0x0000000004950df5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4950df5)
#27 0x0000000000da37f8 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda37f8)
#28 0x0000000000c28b74 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc28b74)
#29 0x0000790a8e629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#30 0x0000790a8e629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#31 0x0000000000d9d505 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd9d505)
```

## Program 

```
#include <iostream>
#include <memory>
template <typename T>
class BinaryTree;
template <typename T>
std::ostream& operator<<(std::ostream& os, BinaryTree<T>& b);
template <typename T>
struct Node {
    Node(T data) : data(data) {}
    T data;
};
template <typename T>
struct BinaryTree {
    std::unique_ptr<Node<T>> root;
    BinaryTree() = default;
    BinaryTree(T data) {
        root = std::make_unique<Node<T>>(data);
    }
    friend std::ostream& operator<< <T>(std::ostream& os, BinaryTree& b) {
        return (b.root)? os << b.root->data : os << "<empty tree>";
    }
};
int main() {
    BinaryTree<int> a(1);
    std::cout << a << std::endl;
}
```

## To quickly reproduce

it happens since clang 20

https://gcc.godbolt.org/z/WWWqdcbjj

### PR DESCRIPTION
**Pull request by zyn0217**
Since 346077aa, we began using the primary template's lexical DeclContext for template arguments in order to properly instantiate a friend definition.

There is a missed peculiar case, as in a friend template is specialized within a dependent context. In this scenario, the primary template is not a definition, whereas the specialization is. So the primary template's DeclContext doesn't provide any meaningful for instantiation.

Fixes https://github.com/llvm/llvm-project/issues/139052

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -5751,14 +5751,16 @@ void Sema::InstantiateFunctionDefinition(SourceLocation PointOfInstantiation,
...
-        Primary &&
+    bool NeedDCFromPrimaryTemplate =
         !isGenericLambdaCallOperatorOrStaticInvokerSpecialization(Function) &&
         Function->getTemplateSpecializationKind() !=
-            TSK_ExplicitSpecialization) {
+            TSK_ExplicitSpecialization &&
+        !PatternDecl->getDependentSpecializationInfo();
+
+    if (auto *Primary = Function->getPrimaryTemplate();
+        Primary && NeedDCFromPrimaryTemplate) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5763]: Can you add a comment? It is sufficiently subtle

**Review by cor3ntin — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 2]
```diff
@@ -5751,14 +5751,16 @@ void Sema::InstantiateFunctionDefinition(SourceLocation PointOfInstantiation,
...
+    DeclContext *DC = Function->getLexicalDeclContext();
     std::optional<ArrayRef<TemplateArgument>> Innermost;
-    if (auto *Primary = Function->getPrimaryTemplate();
-        Primary &&
+    bool NeedDCFromPrimaryTemplate =
         !isGenericLambdaCallOperatorOrStaticInvokerSpecialization(Function) &&
         Function->getTemplateSpecializationKind() !=
-            TSK_ExplicitSpecialization) {
+            TSK_ExplicitSpecialization &&
+        !PatternDecl->getDependentSpecializationInfo();
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5760]: Aren't we simply returning the wrong info above in `Function->getTemplateSpecializationKind()`?
Did you look into fixing that?

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5760]: That's the first approach I've tried :)

There are some challenges stopping us from treating it as a TSK_ExplicitSpecialization. And it comes from the discrepancy between the parser and instantiator.

When parsing the friend specialization within a class context, we treat it as an explicit specialization, and we diagnose it very early, in ActOnFriendFunctionDecl.

When instantiating, we consider *all* instantiated friend declarations as implicit instantiations, and we hold this assumption all the way down to the definition instantiation.

https://github.com/llvm/llvm-project/blob/4b893398990c8966402d1469c927415f5489a9c8/clang/lib/Sema/SemaTemplate.cpp#L9356-L9358

So we ended up with an awkward situation:

1. The definition is written in explicit specialization form, but gets implicitly instantiated within the class.
2. The instantiator attaches the implicit instantiation to the first template declaration as its primary template, which doesn't have a definition, nor any other instantiations have the IsInstantiatedFromMemberTemplate bit (because they're basically instantiated from a non-template!)

Combined, we violate the assertion in instantiating the definition.

Teaching the instantiator to treat it them as explicit instantiations would break many existing assumptions, as in ExplicitSpecializationVisibilityChecker.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5760]: I am also considering to have these instantiations 1) never track the primary template in these cases 2) or track the invalid explicit specialization as its primary template (this likely isn't doable because the specialization is not a template).

Neither option seems ideal to me

**Comment by zyn0217** [comment]
@mizvekov It's not a big deal to turn them into explicit specializations after all... I pushed a commit

**Review by mizvekov — APPROVED** [review]
Perfect, thanks!
