### PR TITLE
[Clang][ExprConstant] fix constant expression did not evaluate to integer

### LINKED ISSUE #96670: template parameter comparison against default value doesn't handle LValue
An assertion is thrown here for this code. APValue is an LValue, not an Int.
This is against release/18.x

```
inline constexpr long ullNil = -1;

template<typename T = long, const T &Nil = ullNil>
struct Test {};

inline constexpr long lNil = -1;
Test<long, lNil> c;
```

```
 #6 0x00007ff608f49f7c clang::APValue::isInt Z:\repos\llvm\clang\include\clang\AST\APValue.h:401:0
 #7 0x00007ff608f49f7c clang::APValue::getInt Z:\repos\llvm\clang\include\clang\AST\APValue.h:424:0
 #8 0x00007ff608f49f7c clang::Expr::EvaluateKnownConstInt(class clang::ASTContext const &, class llvm::SmallVectorImpl<struct std::pair<class clang::SourceLocation, class clang::PartialDiagnostic>> *) const Z:\repos\llvm\clang\lib\AST\ExprConstant.cpp:15862:0
 #9 0x00007ff608e0e3d7 llvm::APSInt::isSameValue Z:\repos\llvm\llvm\include\llvm\ADT\APSInt.h:320:0
#10 0x00007ff608e0e3d7 templateArgumentExpressionsEqual Z:\repos\llvm\clang\lib\AST\TypePrinter.cpp:2135:0
#11 0x00007ff608e021d8 isSubstitutedTemplateArgument Z:\repos\llvm\clang\lib\AST\TypePrinter.cpp:2160:0
#12 0x00007ff608e01fec clang::isSubstitutedDefaultArgument(class clang::ASTContext &, class clang::TemplateArgument, class clang::NamedDecl const *, class llvm::ArrayRef<class clang::TemplateArgument>, unsigned int) Z:\repos\llvm\clang\lib\AST\TypePrinter.cpp:2199:0
#13 0x00007ff60824dbb3 clang::TemplateArgument::setIsDefaulted Z:\repos\llvm\clang\include\clang\AST\TemplateBase.h:389:0
```

### PR DESCRIPTION
**Pull request by Backl1ght**
fixes https://github.com/llvm/llvm-project/issues/96670

The cause is that we might return a lvalue here at

https://github.com/llvm/llvm-project/blob/3e53c97d33210db68188e731e93ee48dbaeeae32/clang/lib/AST/ExprConstant.cpp#L15861-L15865

This PR will make sure we return a rvalue in `FastEvaluateAsRValue`.

### CODE REVIEW

File: clang/lib/AST/ExprConstant.cpp [hunk 1]
```diff
@@ -15858,7 +15858,7 @@ static bool FastEvaluateAsRValue(const Expr *Exp, Expr::EvalResult &Result,
   }
 
   if (const auto *CE = dyn_cast<ConstantExpr>(Exp)) {
-    if (CE->hasAPValueResult()) {
+    if (CE->hasAPValueResult() && !CE->getAPValueResult().isLValue()) {
```
Comment (tbaederr) [inline clang/lib/AST/ExprConstant.cpp:15861]: It looks like `ConstantExpr::getAPValueResult()` will sometimes create a new APValue, so we should try ti call `getAPValueResult()` only once.

**Review by Sirraide — APPROVED** [review]
LGTM after rewording the release note a bit and addressing @tbaederr’s comment.

**Comment by efriedma-quic** [comment]
I'm concerned that we're calling EvaluateKnownConstInt on an lvalue; that might indicate there's something wrong with the AST.  Usually there should be an lvalue-to-rvalue cast somewhere.

**Comment by Backl1ght** [comment]
> I'm concerned that we're calling EvaluateKnownConstInt on an lvalue; that might indicate there's something wrong with the AST. Usually there should be an lvalue-to-rvalue cast somewhere.

@efriedma-quic lvalue-to-rvalue cast is done here at https://github.com/llvm/llvm-project/blob/aec7670b5d6354b63b011c9ed0632b70983b0328/clang/lib/AST/ExprConstant.cpp#L15829-L15835

**Comment by Sirraide** [comment]
> I'm concerned that we're calling EvaluateKnownConstInt on an lvalue; that might indicate there's something wrong with the AST. Usually there should be an lvalue-to-rvalue cast somewhere.

Yeah, I also remember finding that strange, but after looking into it I figured it made sense, but I don’t remmeber why exactly...

**Comment by Sirraide** [comment]
Actually, where are we calling `EvaluateKnownConstInt` here; am I missing something obvious?

**Comment by Sirraide** [comment]
Ah, that was in the original stack trace, I see. The fix here makes sense to me because it’s in `FastEvaluateAsRValue`, so it makes sense that that can fail since it’s just supposed to be a fast path.

**Comment by efriedma-quic** [comment]
To the extent that EvaluateAsRValue handles LValues, FastEvaluateAsRValue should also handle them, sure.  I'm suspicious of the fact that EvaluateAsRValue is doing this conversion in the first place, but I guess this pull request isn't the place to address that.

Given that, this patch LGTM
