### PR TITLE
[MLIR][Arith] SelectOp fix invalid folding

### LINKED ISSUE #117554: [MLIR][Arith] Invalid SelectOp folding
In CIRCT, we have a dialect named `hwarith` to represent arithmetics that persist signedness information and prevent unintentional under- and overflows.
Using this dialect in combination with `arith.select` revealed an issue. Take the following example code:
```
func.func @test(%sel : i1) -> ui1 {
  %trueVal = hwarith.constant 1 : ui1
  %falseVal = hwarith.constant 0 : ui1
  %res = arith.select %sel, %trueVal, %falseVal : ui1
  func.return %res : ui1
}
```
The SelectOp's folder tries to replace the SelectOp directly with `%sel`. However, `%sel` is of type `i1` whereas the true- and falseVal values are of type `ui1`. Consequently, the following crash is caused: `error: 'arith.select' op folder produced a value of incorrect type: 'i1', expected: 'ui1'`.

The corresponding pattern matching code has a bit-width check for the return type but lacks a signedness check and thus implicitly assumes that the return type is signless (i1):
https://github.com/llvm/llvm-project/blob/612f8ec7ac5dcddd16fb027aad64e2e353faa528/mlir/lib/Dialect/Arith/IR/ArithOps.cpp#L2317-L2319

### PR DESCRIPTION
**Pull request by 7FM**
The pattern `select %x, true, false => %x` is only valid in case that the return type is identical to the type of `%x` (i.e., i1). Hence, the check `isInteger(1)` was replaced with `isSignlessInteger(1)`.

Fixes: https://github.com/llvm/llvm-project/issues/117554

### CODE REVIEW

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 1]
```diff
@@ -2314,7 +2314,8 @@ OpFoldResult arith::SelectOp::fold(FoldAdaptor adaptor) {
     return trueVal;
 
   // select %x, true, false => %x
-  if (getType().isInteger(1) && matchPattern(adaptor.getTrueValue(), m_One()) &&
+  if (getType().isSignlessInteger(1) &&
+      matchPattern(adaptor.getTrueValue(), m_One()) &&
       matchPattern(adaptor.getFalseValue(), m_Zero()))
     return condition;
```
Comment (kuhar) [inline mlir/lib/Dialect/Arith/IR/ArithOps.cpp:2320]: I think we could also have a canon pattern that can broadcast the condition in the vector case, but that's probably better for a separate PR.

**Review by kuhar — COMMENTED** [review]
We should add a LIT test for the case that used to fail.

**Comment by joker-eph** [comment]
> The pattern select %x, true, false => %x is only valid in case that the return type is identical to the type of %x (i.e., i1). Hence, the check isInteger(1) was replaced with isSignlessInteger(1).


Can we still replace by a bitcast when the types are different?

**Comment by 7FM** [comment]
> We should add a LIT test for the case that used to fail.

I agree, but at first glance, I couldn't find an upstream MLIR dialect that supports unsigned/signed constants to trigger this bug. But I might have missed a suitable dialect.

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 2]
```diff
@@ -2314,7 +2314,8 @@ OpFoldResult arith::SelectOp::fold(FoldAdaptor adaptor) {
     return trueVal;
 
   // select %x, true, false => %x
-  if (getType().isInteger(1) && matchPattern(adaptor.getTrueValue(), m_One()) &&
+  if (getType().isSignlessInteger(1) &&
```
[the remark this answers is not in the document]
Comment (7FM) [reply mlir/lib/Dialect/Arith/IR/ArithOps.cpp:2317]: AFAIK, `arith.select` does only allow signless types for the condition type. At least simply changing `%sel` from `i1` to `ui1` throws the following `error: use of value '%sel' expects different type than prior uses: 'i1' vs 'ui1'`.
But I agree, in case that this limitation will be lifted at some day, comparing the type directly would be better.

**Comment by 7FM** [comment]
> > The pattern select %x, true, false => %x is only valid in case that the return type is identical to the type of %x (i.e., i1). Hence, the check isInteger(1) was replaced with isSignlessInteger(1).
> 
> Can we still replace by a bitcast when the types are different?

`error: 'arith.bitcast' op result #0 must be signless-integer-or-float-like or memref of signless-integer or float, but got 'ui1'`
I don't think so, at least not without further modifications.

**Comment by kuhar** [comment]
> > We should add a LIT test for the case that used to fail.
> 
> I agree, but at first glance, I couldn't find an upstream MLIR dialect that supports unsigned/signed constants to trigger this bug. But I might have missed a suitable dialect.

I don't think the condition has to be a constant, can we use a signed function argument instead or a result of an unregistered op?

**Comment by kuhar** [comment]
> > We should add a LIT test for the case that used to fail.
> 
> I agree, but at first glance, I couldn't find an upstream MLIR dialect that supports unsigned/signed constants to trigger this bug. But I might have missed a suitable dialect.

How about adding a new test op to the test dialect?

**Comment by 7FM** [comment]
> > > We should add a LIT test for the case that used to fail.
> > 
> > 
> > I agree, but at first glance, I couldn't find an upstream MLIR dialect that supports unsigned/signed constants to trigger this bug. But I might have missed a suitable dialect.
> 
> How about adding a new test op to the test dialect? We already use `test.with_bounds` in arith tests.

Thanks for the hint! I didn't know that such a dialect existed.

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp (hunk 1 above)
Comment (7FM) [reply mlir/lib/Dialect/Arith/IR/ArithOps.cpp:2320]: Since I am not familiar with the Arith + vector use case, I would prefer a separate PR for this.

**Review by kuhar — APPROVED** [review]
LGTM

**Review by joker-eph — APPROVED** [review]
