### PR TITLE
[Clang] Reject __annotation on unsupported targets

### LINKED ISSUE #184318: crashes when compiling __annotation(L"...") with -fms-extensions
Reproducer:
https://godbolt.org/z/37Wc9MP8v
```cpp
void foo() {
  __annotation(L"a1");
}
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/CodeGen/CGBuiltin.cpp:5373: clang::CodeGen::RValue clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(clang::GlobalDecl, unsigned int, const clang::CallExpr*, clang::CodeGen::ReturnValueSlot): Assertion `Str->getCharByteWidth() == 2' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -fms-extensions <source>
1.	<eof> parser at end of file
2.	<source>:1:6: LLVM IR generation of declaration 'foo'
3.	<source>:1:6: Generating code for declaration 'foo'
 #0 0x000000000440a568 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x440a568)
 #1 0x00000000044079b4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44079b4)
 #2 0x00000000043477b8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000077e392242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000077e3922969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000077e392242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000077e3922287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000077e39222871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000077e392239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000004db7fa6 clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(clang::GlobalDecl, unsigned int, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4db7fa6)
#10 0x00000000048d29de clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot, llvm::CallBase**) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48d29de)
#11 0x0000000004957b64 (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) CGExprScalar.cpp:0:0
#12 0x000000000494d2f0 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#13 0x0000000004952d0c clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4952d0c)
#14 0x00000000048b262e clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48b262e)
#15 0x00000000048cb59d clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48cb59d)
#16 0x0000000004a7b507 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a7b507)
#17 0x0000000004a83e6b clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a83e6b)
#18 0x0000000004aecf66 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4aecf66)
#19 0x0000000004afeda4 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4afeda4)
#20 0x0000000004b6daf0 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b6daf0)
#21 0x0000000004b687c4 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b687c4)
#22 0x0000000004b68fa3 clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b68fa3)
#23 0x0000000004b74693 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#24 0x0000000004ee6a39 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#25 0x0000000004ed7e44 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ed7e44)
#26 0x0000000006bcf6c4 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bcf6c4)
#27 0x0000000004ee47d8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ee47d8)
#28 0x00000000051eb175 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51eb175)
#29 0x00000000051693ce clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51693ce)
#30 0x00000000052e6e2d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52e6e2d)
#31 0x0000000000df0afe cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdf0afe)
#32 0x0000000000de746a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#33 0x0000000000de75ed int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#34 0x0000000004f58f39 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#35 0x0000000004347bf4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4347bf4)
#36 0x0000000004f5954f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#37 0x0000000004f19232 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f19232)
#38 0x0000000004f1a1de clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f1a1de)
#39 0x0000000004f21f25 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f21f25)
#40 0x0000000000dece6e clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdece6e)
#41 0x0000000000ca503a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca503a)
#42 0x000077e392229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#43 0x000077e392229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#44 0x0000000000de6f05 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde6f05)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by kjedruczyk**
__annotation emits llvm.codeview.annotation intrinsics, which are only consumed by CodeViewDebug
on Windows and UEFI targets. On other targets the intrinsic is silently dropped, and codegen
hits an assertion due to wchar_t being 4 bytes (UTF-32) instead of the expected 2 bytes
(UTF-16).

Fixes #184318

### CODE REVIEW

**Review by efriedma-quic — COMMENTED** [review]
Doing codegen for the annotation doesn't really get you anywhere.  It's technically not crashing anymore, but the annotation doesn't actually work: the underlying infrastructure for consuming the annotation doesn't exist on non-Microsoft targets.

If you don't actually have any use-case for this, please just add an error check to SemaChecking.cpp (BuiltinMSVCAnnotation).

(Also; missing regression test.)

**Comment by kjedruczyk** [comment]
Fair point about this being MS-only annotation, but I assumed the use case would be cross-compiling for Win32 targets on non MS hosts.

**Comment by kjedruczyk** [comment]
Actually, it seems I was wrong, just tried selecting `x86_64-pc-windows-msvc` and looks like the frontend will create the string with target's wchar width, so your suggestion of just not allowing this annotation makes sense.

**Comment by kjedruczyk** [comment]
I added the platform check. From what I understand the platforms where CodeView could be used are Windows and UEFI, but I'm unsure if this maybe should be gated on COFF binary format instead, so that some niche platforms I am unaware of are allowed?

**Review by cor3ntin — COMMENTED** [review]
This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

(LGTM otherwise)

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -3263,10 +3263,17 @@ Sema::CheckBuiltinFunctionCall(FunctionDecl *FDecl, unsigned BuiltinID,
   case Builtin::BI##ID:                                                        \
     return AtomicOpsOverloaded(TheCallResult, AtomicExpr::AO##ID);
 #include "clang/Basic/Builtins.inc"
-  case Builtin::BI__annotation:
+  case Builtin::BI__annotation: {
+    const llvm::Triple &TT = Context.getTargetInfo().getTriple();
+    if (!TT.isOSWindows() && !TT.isUEFI()) {
+      Diag(TheCall->getBeginLoc(), diag::err_builtin_target_unsupported)
+          << SourceRange(TheCall->getBeginLoc(), TheCall->getEndLoc());
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaChecking.cpp]:
```suggestion
          << TheCall->getSourceRange();
```

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit

**Comment by cor3ntin** [comment]
Thanks. 
Will you need us to merge that for you?

**Comment by kjedruczyk** [comment]
Yes, I can't merge it myself.Thank you!

**Comment by kjedruczyk** [comment]
I just realised - I think I don't have access to trigger the CI runs. @cor3ntin - could you please trigger the workflows for me and merge this on my behalf if they pass and there, and are no other concerns?

**Comment by kjedruczyk** [comment]
Thanks, @cor3ntin - all checks are green now. I imagine I don't need to rebase the branch on the current main as there are no conflicts that I can see, and rebasing would probably clear the CI checks.

If the workflow allows it, please merge it at your convenience!

**Comment by cor3ntin** [comment]
I will if @efriedma-quic has no more feedback :)

File: clang/lib/Sema/SemaChecking.cpp [hunk 2]
```diff
@@ -3263,10 +3263,17 @@ Sema::CheckBuiltinFunctionCall(FunctionDecl *FDecl, unsigned BuiltinID,
   case Builtin::BI##ID:                                                        \
     return AtomicOpsOverloaded(TheCallResult, AtomicExpr::AO##ID);
 #include "clang/Basic/Builtins.inc"
-  case Builtin::BI__annotation:
+  case Builtin::BI__annotation: {
+    const llvm::Triple &TT = Context.getTargetInfo().getTriple();
+    if (!TT.isOSWindows() && !TT.isUEFI()) {
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaChecking.cpp:3268]: Do we also need to check the wchar width?  -fno-short-wchar is technically allowed on Windows, although I expect it sees very little usage.

Comment (kjedruczyk) [reply clang/lib/Sema/SemaChecking.cpp:3268]: Now that's an interesting observation - you're right that clang allows it even on UEFI, where as far as I can tell it goes against the standard: https://godbolt.org/z/jP137Wdqx

I am not sure why this is allowed, but since it is: I wouldn't think that rejecting the CodeView annotations based on wchar width is the right thing. As long as there is a reason to support `-fno-short-wchar` on these targets, the annotation should probably be supported too, especially since it's normalized to UTF8 after all.

My suggestion would be to bring back 9f4a8007ac96ee96e15da962e0bc51c9429c5761 on top of platform checks, so we get both rejection of CodeView annotations on non Windows/UEFI COFF targets and avoid assertion triggering when the `wchar` width assumption doesn't hold.

FWIW, maybe it would be worthwhile to add a wchar-width agnostic version of the UTF8 conversion, instead of awkwardly dispatching on wchar width when UTF8 form is needed (I'm surprised such conversion doesn't seem to exist but maybe I'm missing something)?

Comment (kjedruczyk) [reply clang/lib/Sema/SemaChecking.cpp:3268]: I've added the wchar with check back, and added the test for it now. 

FWIW, I did verify the test caught this issue:

```
 % ../dbg/build/bin/llvm-lit -v ../../llvm-project/clang/test/CodeGen/ms-annotation.c
llvm-lit: llvm-project/llvm/utils/lit/lit/llvm/config.py:569: note: using clang: llvm-workspace/dbg/build/bin/clang
llvm-lit: llvm-project/llvm/utils/lit/lit/llvm/subst.py:130: note: Did not find cir-opt in llvm-workspace/dbg/build/bin:llvm-workspace/dbg/build/bin
llvm-lit: llvm-project/llvm/utils/lit/lit/util.py:363: note: using SDKROOT: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.4.sdk'
-- Testing: 1 tests, 1 workers --
FAIL: Clang :: CodeGen/ms-annotation.c (1 of 1)
******************** TEST 'Clang :: CodeGen/ms-annotation.c' FAILED ********************
Exit Code: 2

Command Output (stdout):
--
# RUN: at line 1
llvm-workspace/dbg/build/bin/clang -cc1 -internal-isystem llvm-workspace/dbg/build/lib/clang/23/include -nostdsysteminc -triple i686-windows llvm-project/
clang/test/CodeGen/ms-annotation.c -fms-extensions -emit-llvm -o - | llvm-workspace/dbg/build/bin/FileCheck llvm-project/clang/test/CodeGen/ms-annotation.c
# executed command: llvm-workspace/dbg/build/bin/clang -cc1 -internal-isystem llvm-workspace/dbg/build/lib/clang/23/include -nostdsysteminc -triple i686-windows llvm-project/clang/test/CodeGen/ms-annotation.c -fms-extensions -emit-llvm -o -
# executed command: llvm-workspace/dbg/build/bin/FileCheck llvm-project/clang/test/CodeGen/ms-annotation.c
# RUN: at line 2
llvm-workspace/dbg/build/bin/clang -cc1 -internal-isystem llvm-workspace/dbg/build/lib/clang/23/include -nostdsysteminc -triple i686-windows llvm-project/
clang/test/CodeGen/ms-annotation.c -fms-extensions -fwchar-type=int -fsigned-wchar -emit-llvm -o - | llvm-workspace/dbg/build/bin/FileCheck llvm-project/clang/test/CodeGen/ms-annota
tion.c
# executed command: llvm-workspace/dbg/build/bin/clang -cc1 -internal-isystem llvm-workspace/dbg/build/lib/clang/23/include -nostdsysteminc -triple i686-windows llvm-project/clang/test/CodeGen/ms-annotation.c -fms-extensions -fwchar-type=int -fsigned-wchar -emit-llvm -o -
# .---command stderr------------
# | Assertion failed: (Str->getCharByteWidth() == 2), function EmitBuiltinExpr, file CGBuiltin.cpp, line 5600.
...
```

Comment (kjedruczyk) [reply clang/lib/Sema/SemaChecking.cpp:3268]: @efriedma-quic - if that works for you, could you, please, trigger the CI?

**Comment by kjedruczyk** [comment]
Hmm, looks like an msan test failed on AArch64:

```
  FAIL: SanitizerCommon-msan-aarch64-Linux :: Linux/pthread_join.cpp (3425 of 5175)
  ******************** TEST 'SanitizerCommon-msan-aarch64-Linux :: Linux/pthread_join.cpp' FAILED ********************
  Exit Code: 1
```

Doesn't strike me as related to my change - are, by any chance, any of these tests known to be unreliable?

**Comment by efriedma-quic** [comment]
It looks like those tests were recently modified by #194100?  CC @vitalybuka .  In any case, probably not related to your patch; tests for runtimes and lldb sometimes fail for weird reasons.

**Comment by vitalybuka** [comment]
> It looks like those tests were recently modified by #194100? CC @vitalybuka . In any case, probably not related to your patch; tests for runtimes and lldb sometimes fail for weird reasons.

How often?

I changed only assert(err == ESRCH) -> assert(err == ESRCH || err == 0) because glibc changed behaviour.

Still sanitizer_common/TestCases/Linux/pthread_join.cpp:72:17 relies n UB. If it happens frequently, we need to de-flake it.

**Comment by efriedma-quic** [comment]
I don't think I've seen that particular test fail before, and I can't find any record of such a failure.

I do see random failures of various sorts, mostly lldb, a couple times a week.

**Comment by kjedruczyk** [comment]
@efriedma-quic  - should we retry the run? If it helps I can rebase the branch on top of main, but AFAIK the CI runs on merged commit anyway.

> Still sanitizer_common/TestCases/Linux/pthread_join.cpp:72:17 relies n UB. If it happens frequently, we need to de-flake it.

If that helps, I can try to reproduce it on some arm64 SOC I have laying around, but I'm not sure I can reproduce exact environment the CI workflow uses.

**Review by efriedma-quic — APPROVED** [review]
LGTM

I don't think we need to rerun the build.

**Comment by kjedruczyk** [comment]
Thank you all for the reviews!
