### PR TITLE
[libc] Special case PPC double double for print

### LINKED ISSUE #136596: ppc64le offload build broken by 8437b7f5584765ad4f7885500647657714930fbb
@jhuber6 This commit 8437b7f5584765ad4f7885500647657714930fbb ( https://github.com/llvm/llvm-project/pull/131205) broke the build on ppc64le.  You can reproduce by configuring with:
```
cmake -G Ninja -B build -S llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=Native -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_RUNTIMES="offload;openmp;compiler-rt" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
```

And running:

```
ninja -C build runtimes
```
See attached build logs for details.  Note we aren't seeing the same failures on configurations where llvm is built with `-DPPC_LINUX_DEFAULT_IEEELONGDOUBLE:BOOL=ON`.

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
We use the storage class for `long double` in the printing
implementations. We don't fully support the PPC double double type,
which that maps to, but we can stub out just the support needed for the
print interface to works. This required using the internal interface for
storage type, but it should be good enough.

Fixes: https://github.com/llvm/llvm-project/issues/136596

### CODE REVIEW

File: libc/src/stdio/printf_core/core_structs.h [hunk 1]
```diff
@@ -56,7 +56,8 @@ struct FormatSection {
   int precision = -1;
 
   // Needs to be large enough to hold a long double.
-  fputil::FPBits<long double>::StorageType conv_val_raw;
+  fputil::internal::FPLayout<fputil::get_fp_type<long double>()>::StorageType
```
Comment (michaelrj-google) [inline libc/src/stdio/printf_core/core_structs.h:59]: this change shouldn't be necessary, we should probably make sure the template gets pulled all the way through instead.

**Review by michaelrj-google — CHANGES_REQUESTED** [review]

File: libc/src/stdio/printf_core/core_structs.h (hunk 1 above)
Comment (jhuber6) [reply libc/src/stdio/printf_core/core_structs.h:59]: It's necessary because otherwise we need to define everything in the FPRem interface, since that's the adapter that goes from FPLayout to FPBits.

Comment (jhuber6) [reply libc/src/stdio/printf_core/core_structs.h]: Okay, I got what you meant and it seems to work now. I don't get any errors when I compile a test program with `--target=powerpc64le`.

File: libc/src/__support/FPUtil/FPBits.h [hunk 2]
```diff
@@ -818,7 +830,8 @@ struct FPBits final : public internal::FPRepImpl<get_fp_type<T>(), FPBits<T>> {
   static_assert(cpp::is_floating_point_v<T>,
                 "FPBits instantiated with invalid type.");
   using UP = internal::FPRepImpl<get_fp_type<T>(), FPBits<T>>;
-  using StorageType = typename UP::StorageType;
+  using StorageType =
+      typename internal::FPLayout<get_fp_type<T>()>::StorageType;
```
Comment (michaelrj-google) [inline libc/src/__support/FPUtil/FPBits.h:834]: This feels like a bit of a hack. Is there a reason we can't add the `FPRepSem` and leave this as-is?

Comment (jhuber6) [reply libc/src/__support/FPUtil/FPBits.h:834]: Conceptually no, but there's no user of those functions yet and it is non-trivial. I'm not a floating point expert and didn't want to spend a few days double checking the binary format of PPC's double just to close this bug report.

Comment (michaelrj-google) [reply libc/src/__support/FPUtil/FPBits.h:834]: That's fair. In that case, I'd say file a bug, add a TODO, and I'll approve this so we can move on.

Comment (jhuber6) [reply libc/src/__support/FPUtil/FPBits.h:834]: There's already a TODO to add the full FPRepSem interface, but I don't think it's too bad to remove one layer of indirection for this.

Comment (michaelrj-google) [reply libc/src/__support/FPUtil/FPBits.h:834]: it's not one layer of indirection though, it's four. I don't feel comfortable saying this is definitely safe, especially given this is an interface we're exporting. This is a very bad place for technical debt.

**Review by tuliom — APPROVED** [review]
I don't feel confident reviewing the libc details on this PR, but as someone that has experience with PPC floating point, I reviewed the numbers and they LGTM.

**Review by lntue — APPROVED** [review]

**Review by michaelrj-google — COMMENTED** [review]
Patch LGTM as landed.
