### PR TITLE
[clang-tidy] Fix false positive in readability-convert-member-functions-to-static for const overloads

### LINKED ISSUE #149152: clang-tidy: false positive readability-convert-member-functions-to-static to overloaded method
Prepare `/tmp/a.cpp`:

```cpp
struct S {
  void f();
  void f() const;

  int i = 0;
};

void S::f() { this->i++; }
void S::f() const { ; }
```

and `/tmp/compile_commands.json`:

```json
[{
  "directory": "/tmp",
  "command": "clang++ -c -o a.o a.cpp",
  "file": "a.cpp",
  "output": "a.o"
}]
```

```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 20.1.7
  Optimized build.
```

```console
$ clang-tidy --checks=readability-convert-member-functions-to-static --fix a.cpp
1 warning generated.
a.cpp:9:9: warning: method 'f' can be made static [readability-convert-member-functions-to-static]
    3 |   void f() const;
      |            ~~~~~
      |   static
    4 |
    5 |   int i = 0;
    6 | };
    7 |
    8 | void S::f() { this->i++; }
    9 | void S::f() const { ; }
      |         ^   ~~~~~
a.cpp:3:3: note: FIX-IT applied suggested code changes
    3 |   void f() const;
      |   ^
a.cpp:3:12: note: FIX-IT applied suggested code changes
    3 |   void f() const;
      |            ^
a.cpp:9:13: note: FIX-IT applied suggested code changes
    9 | void S::f() const { ; }
      |             ^
clang-tidy applied 3 of 3 suggested fixes.
```

gives the following invalid code

```cpp
struct S {
  void f();
  static void f() ;

  int i = 0;
};

void S::f() { this->i++; }
void S::f() { ; }
```

```console
$ clang++ -c -o a.o a.cpp
a.cpp:3:15: error: static and non-static member functions with the same parameter types cannot be overloaded
    3 |   static void f() ;
      |               ^
a.cpp:2:8: note: previous declaration is here
    2 |   void f();
      |        ^
a.cpp:9:9: error: redefinition of 'f'
    9 | void S::f() { ; }
      |         ^
a.cpp:8:9: note: previous definition is here
    8 | void S::f() { this->i++; }
      |         ^
2 errors generated.
```

<https://godbolt.org/z/aaYq98GMT>

### PR DESCRIPTION
**Pull request by gxyd**
Don't suggest conversion of overloaded + same signature methods
differing in `const`ness to replace the `const` method with `static`.
    
E.g.;
```
void S::f();         // method1
void S::f() const;   // method2
```
    
method2 can't have it's `const` replaced with `static`.
    
Fixes #149152

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp [hunk 1]
```diff
@@ -235,3 +235,38 @@ struct NoFixitInMacro {
...
+    // CHECK-FIXES: static void h(float) {
+    ;
+  };
+
+  void j() {
+    this->i++;
+  }
+  int j() const {
+    ;
+  }
```
Comment (gxyd) [inline clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp]: This example currently on `main` (does Godbolt uses `main` of LLVM?) raises an incorrect warning: https://godbolt.org/z/eM6acb3zh , which I confirmed isn't a valid `-fix`.

**Comment by gxyd** [comment]
How do I actually run the `Code lint` CI job's equivalent locally on my machine?

I've tried:
```bash
(llvm-dev) [overloaded_member_function_to_static][~/OpenSource/llvm-project]$ python3 clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py   -path build -p1 -quiet
```

I waited for a long time for the above command to finish, but I didn't get any output, and I eventually interrupted it. 🤷

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp [hunk 2]
```diff
@@ -76,6 +76,35 @@ AST_MATCHER(CXXMethodDecl, usesThis) {
...
+  if (LookupResult.isSingleResult())
+    return false;
+
+  for (const Decl *D : LookupResult) {
+    if (const auto *Overload = dyn_cast<CXXMethodDecl>(D)) {
+      if (Overload != Method && !Overload->isConst() &&
+          hasSameParameterTypes(*Method, *Overload)) {
+        return true;
+      }
+    }
```
Comment (unterumarmung) [inline clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: this can be one `if` and `{` `}` are not needed

**Review by unterumarmung — COMMENTED** [review]
If you use AI, please state it as required by https://llvm.org/docs/AIToolPolicy.html

**Comment by gxyd** [comment]
> If you use AI, please state it as required by https://llvm.org/docs/AIToolPolicy.html

Hi @unterumarmung , thanks for the review.

Regarding your note, no I haven't used any AI generate code at all here. I usually use AI in a very generic way, e.g. let's say I want to know to print a variable in debug console when debgging LLVM code or how to obtain more information about a certain variable type (e.g. `Node` in this PR) etc.

But there is no usage of LLM generate code at all in this PR or any of the other PR's that I've submitted till now.

**Comment by zeyi2** [comment]
> How do I actually run the `Code lint` CI job's equivalent locally on my machine?

Inside the CI comment there is a command that you can run:

```
git diff -U0 origin/main...HEAD -- clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp |
python3 clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py   -path build -p1 -quiet`
```

**Comment by vbvictor** [comment]
> I waited for a long time for the above command to finish, but I didn't get any output, and I eventually interrupted it. 🤷

Check processes if it is actually running. If so - should be finished eventually. Debug builds of clang-tidy can be pretty slow, make sure you use release build

**Comment by gxyd** [comment]
I got it working locally, first I had to disable precompiled headers (I did it using `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON`, as you mentioned on discord channel). Still, it took almost 5 minutes on my machine and I've debug build of clang-tidy, and it doesn't make sense for me to keep switching between debug build and release build just to be able to run this command. I guess, I'll have to bear the pain of longer time (~5 minutes) though.

**Comment by vbvictor** [comment]
> Still, it took almost 5 minutes on my machine and I've debug build of clang-tidy, and it doesn't make sense for me to keep switching between debug build and release build just to be able to run this command. I guess, I'll have to bear the pain of longer time (~5 minutes) though.

You don't have to use built-from-main clang-tidy for analysis. Currenly in CI we use latest release which is clang-tidy-22. You can install it and use for analysis with `--clang-tidy-binary=clang-tidy-22` or create a symlink `clang-tidy-22 -> clang-tidy`

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp [hunk 3]
```diff
@@ -235,3 +235,38 @@ struct NoFixitInMacro {
...
   }
 };
+
+
+struct OverloadedMethods {
+  void f() {
+    this->i++;
+  }
+  void f() const {
+    ;
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp]: Omit this, it doesn't add value to function

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -449,6 +412,11 @@ Changes in existing checks
   - Reduce verbosity by removing the note indicating source location of the
     ``empty`` function.
 
+- Improved :doc:`readability-convert-member-functions-to-static
+  <clang-tidy/checks/readability/convert-member-functions-to-static>` check by
+  avoiding false positive on ``const`` member functions to static when they are
+  a part of const/non-const overload pair with same signature.
```
Comment (vbvictor) [inline clang-tools-extra/docs/ReleaseNotes.rst]: if it is overload, it must have same signature
```suggestion
  a part of const/non-const overload pair.
```

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp (hunk 3 above)
Comment (gxyd) [reply clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp]: I think we do actually need the `;`, because in it's absence the function will be declared as having a trivial body. That would mean the matcher (under consideration): https://github.com/llvm/llvm-project/blob/d9c02ffa4d519245903ba8d168b3bafeb1a396af/clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp#L83-L99

would never match. Hence, we'll never be actually testing the `hasNonConstOverload` (the utility I just added).

Let me know if you still think otherwise.

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (gxyd) [reply clang-tools-extra/docs/ReleaseNotes.rst]: Even though I've already made the change. I want to clarify one thing:

> if it is overload, it must have same signature

By the above statement, which one of the below do you mean?
1. Overload in C++ actually means - same signature, hence writing "same signature" is redundant
2. Since I've already written "a part of const/non-const overload pair" - this means everything between methods is same, except their `const`ness or absence of it. Hence writing "same signature" is redundant

If you can you please help clarify this for me. I've already made the change though.

**Comment by gxyd** [comment]
Hi @vbvictor , I've addressed all of your comments (I didn't resolve them, so you can take a look and decide if things look good).

Gentle ping @zeyi2  for the review here.

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp [hunk 5]
```diff
@@ -235,3 +235,24 @@ struct NoFixitInMacro {
     return;
   }
 };
+
+
+struct OverloadedMethods {
+  void f() { this->i++; }
+  void f() const { ; };   // `;` is necessary to ensure non trivial body
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp:242]: Please add test when method is defined out of class

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp [hunk 6]
```diff
@@ -135,6 +159,9 @@ void ConvertMemberFunctionsToStaticCheck::check(
     const MatchFinder::MatchResult &Result) {
   const auto *Definition = Result.Nodes.getNodeAs<CXXMethodDecl>("x");
 
+  if (Definition->isConst() && hasNonConstOverload(*Definition))
+    return;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: This should be part of the mather
write: `unless(allOf(IsConst(), HasNonConstOverload()))` and convert `hasNonConstOverload` to custom matcher.

**Review by vbvictor — COMMENTED** [review]
Overall looks good, a couple of suggestions and LGTM

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (vbvictor) [reply clang-tools-extra/docs/ReleaseNotes.rst]: I meant the second one.
Speaking about the first, "overload" usually when function have same name and different parameters, like `g(int), g(int, int)` but if we are speaking about const/non-const pair then all parameters should be the same already.

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp (hunk 3 above)
Comment (vbvictor) [reply clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp]: Thanks for the info. I see it now

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp (hunk 6 above)
Comment (gxyd) [reply clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: Makes sense, we actually had `hasNonConstOverload` as a Matcher earlier, but then I noticed the CI giving `llvm-prefer-static-over-anonymous-namespace` errors, so I converted `hasNonConstOverload` to a function.

I've reverted to `hasNonConstOverload` as a Matcher now, and fixed the warning by converting `hasSameParameterTypes` to a lambda within the Matcher (which should fix the warning).

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp (hunk 5 above)
Comment (gxyd) [reply clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static.cpp:242]: Yes, I've more tests in the latest commit(s), that should make the tests more robust.

**Comment by gxyd** [comment]
I've addressed all of your comments @vbvictor . Enjoy your vacation!

**Review by vbvictor — APPROVED** [review]
lgtm

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp (hunk 6 above)
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: As of

```
clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp:79:13: warning: place static function 'hasSameParameterTypes' outside of an anonymous namespace [llvm-prefer-static-over-anonymous-namespace]
   79 | static bool hasSameParameterTypes(const CXXMethodDecl &MD1,
      |             ^
```

You should have placed the function in the beginning of the file, above matchers (and made it static)

**Review by zeyi2 — APPROVED** [review]

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp (hunk 6 above)
Comment (gxyd) [reply clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: You are right, either that or lambda are both good approaches. I did think about this later, but I preferred using lambda at the moment, considering it's currently very much tied to the added Matcher (i.e. `hasNonConstOverload`), so I thought to stick with that.

Do you think I should've gone the other way and put it as a static function outside the anonymous scope over the use of lambda?

**Comment by gxyd** [comment]
Thanks for your reviews and time @zeyi2 and @vbvictor 😃 .

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp (hunk 6 above)
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: Lambda is better solution to me in current context. We can refactor it into separate function later if ever needed

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (gxyd) [reply clang-tools-extra/docs/ReleaseNotes.rst]: Marking the conversation as resolved.

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp (hunk 6 above)
Comment (gxyd) [reply clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStaticCheck.cpp]: Makes sense. I'll resolve this conversation then.
