### PR TITLE
[Clang][Sema] Use the correct lookup context when building overloaded 'operator->' in the current instantiation

### LINKED ISSUE #104268: clang fails to find operator `->`
```cpp
struct D {
  template <typename T> void m() {}
};

template <typename T> struct S {
  void init() { (*this)->template m<T>(); };

  D *operator->();
};
```

clang rejects the code with the following error message:
```
<source>:6:35: error: no member named 'm' in 'S<T>'
    6 |   void init() { (*this)->template m<T>(); };
```
It looks like clang's behavior changed after [1595988ee6f9732e7ea79928af8a470ad5ef7dbe](https://github.com/llvm/llvm-project/pull/92283).

### PR DESCRIPTION
**Pull request by sdkrystian**
Currently, clang erroneously rejects the following:
```cpp
struct A
{
    template<typename T>
    void f();
};

template<typename T>
struct B
{
    void g()
    {
        (*this)->template f<int>(); // error: no member named 'f' in 'B<T>'
    }

    A* operator->();
};
```

This happens because `Sema::ActOnStartCXXMemberReference` does not adjust the `ObjectType` parameter when `ObjectType` is a dependent type (except when the type is a `PointerType` and the class member access is the `->` form). Since the (possibly adjusted) `ObjectType` parameter (`B<T>` in the above example) is passed to `Parser::ParseOptionalCXXScopeSpecifier`, we end up looking up `f` in `B` rather than `A`. 

This patch fixes the issue by identifying cases where the type of the object expression `T` is a dependent, non-pointer type and:
- `T` is the current instantiation and lookup for `operator->` finds a member of the current instantiation, or
- `T` has at least one dependent base case, and `operator->` is not found in the current instantiation

and using `ASTContext::DependentTy` as the type of the object expression when the optional _nested-name-specifier_ is parsed.

Fixes #104268.

### CODE REVIEW

**Comment by shafik** [comment]
Can you please add more details in your summary about the problem and how the PR will fix the problem.

Having detailed summaries for got log is important. Also for the code reviewer as well, I should get a good snapshot of the problem and fix from the summary.

**Comment by cor3ntin** [comment]
@sdkrystian do you plan to add more tests?

**Comment by sdkrystian** [comment]
> Can you please add more details in your summary about the problem and how the PR will fix the problem.
@shafik I will once I get back to this PR.

> @sdkrystian do you plan to add more tests?
@cor3ntin I do, I just haven't gotten around to it yet :)

**Comment by cor3ntin** [comment]
thanks! 
the window for a back port to 19 is closing fast fyi!

**Comment by sdkrystian** [comment]
@cor3ntin What's the deadline?

**Comment by cor3ntin** [comment]
I think there won't be a rc4 so it's actually probably too late (@tobias) - but presumably there will be a `19.0.2` version a couple of weeks after release. So ~2 or 3 weeks?

**Comment by h-vetinari** [comment]
> I think there won't be a rc4 so it's actually probably too late

You have the wrong handle, on github it's @tru. 😉 Also, RC4 is being [considered](https://discourse.llvm.org/t/llvm-19-1-0-final-update-and-possible-rc4/81010).

**Comment by cor3ntin** [comment]
> > I think there won't be a rc4 so it's actually probably too late
> 
> You have the wrong handle, on github it's @tru. 😉 Also, RC4 is being [considered](https://discourse.llvm.org/t/llvm-19-1-0-final-update-and-possible-rc4/81010).

Thanks! However we can't consider a backport until we have something to backport!

**Comment by sdkrystian** [comment]
@cor3ntin After giving it another look, I think the existing tests are sufficient (the tests updated by this PR were written by me to test this exact scenario). WDYT?

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 1]
```diff
@@ -7939,7 +7927,14 @@ ExprResult Sema::ActOnStartCXXMemberReference(Scope *S, Expr *Base,
           }
         }
         return ExprError();
+      } else if (Result.isUnset()) {
+        // BuildOverloadedArrowExpr returns an empty expression to indicate
+        // that we need to build a dependent overloaded arrow expression.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExprCXX.cpp:7932]: I have 2 concerns with that
 1/ It's a bit too clever of an interface
 2/ We should make sure this can only happens in Sema, right? I wonder if we need an ActOnOverloadedArrowExpr to wrap that logic such that (it would duplicate the lookup code but i think that's a better outcome)

WDYT?

**Comment by sdkrystian** [comment]
@cor3ntin Excellent, then I think this is good to go

File: clang/lib/Sema/SemaExprCXX.cpp (hunk 1 above)
Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp:7932]: > I have 2 concerns with that 
> 1/ It's a bit too clever of an interface

Although I agree it's an imperfect interface, this is more of a "transitional" fix. Ideally we will build the full AST for calls to members of the current instantiation in the future. For now, the usage of `ExprEmpty` in this patch isn't unfounded so I think it's "good enough". Alternatively I can add a `bool& IsDependent` out parameter to implement this functionality. 

> 2/ We should make sure this can only happens in Sema, right? I wonder if we need an ActOnOverloadedArrowExpr to wrap that logic such that (it would duplicate the lookup code but i think that's a better outcome)

I'm not entirely sure what this means. Are you saying that we should expect the result to _not_ be `ExprEmpty` during instantiation?

Comment (cor3ntin) [reply clang/lib/Sema/SemaExprCXX.cpp:7932]: I'm not sure RebuildCXXOperatorCallExpr and its caller would deal with an ExprEmpty when calling  
ActOnOverloadedArrowExpr

So yeah, maybe output parameter + assert in treetransform would be better?

**Comment by cor3ntin** [comment]
Can you update the description too?
No changelog needed, I assume we want to backport that @AaronBallman

File: clang/lib/Sema/SemaExprCXX.cpp (hunk 1 above)
Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp:7932]: @cor3ntin Pushed changes that do what you described

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks (Please update the description before merging)

**Comment by AaronBallman** [comment]
> Can you update the description too? No changelog needed, I assume we want to backport that @AaronBallman

If we can backport it, it seems like a reasonable one to backport; the biggest question I have is whether we have any concerns about the changes being risky or not.

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 2]
```diff
@@ -7981,7 +7969,7 @@ ExprResult Sema::ActOnStartCXXMemberReference(Scope *S, Expr *Base,
     SmallVector<FunctionDecl*, 8> OperatorArrows;
     CTypes.insert(Context.getCanonicalType(BaseType));
 
-    while (BaseType->isRecordType()) {
+    while (BaseType->getAsRecordDecl()) {
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExprCXX.cpp:7972]: This is a bit odd -- we're getting it as a record declaration and ignoring the result. Why is this change needed?

Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp:7972]: It's essentially a shortcut for `BaseType->isRecordType() || isa<InjectedClassNameType>(BaseType->getCanonicalTypeInternal())`

Comment (AaronBallman) [reply clang/lib/Sema/SemaExprCXX.cpp:7972]: `isa<InjectedClassNameType, RecordType>(BaseType)` seems more clear, WDYT?

Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp:7972]: It would have to be spelled `isa<InjectedClassNameType, RecordType>(BaseType.getCanonicalType())`... but that's unnecessarily verbose IMO (especially since we need this check in multiple places). WDYT?

Comment (AaronBallman) [reply clang/lib/Sema/SemaExprCXX.cpp:7972]: I don't insist on a change, but I also don't think that's needlessly verbose. You can put the canonical type in a local variable to shorten it again.

Generally speaking, calling `getXXX()` and not actually caring about the return value aside from whether it's null or not is a bit of a code smell. We ask folks to replace `foo->getAs<Blah>()` and replace it with `isa<Blah>(foo);` quite often and this is just more of the same.

Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp:7972]: Ah, I see. I'll use `isa<InjectedClassNameType, RecordType>(BaseType.getCanonicalType())` then.

Comment (sdkrystian) [reply clang/lib/Sema/SemaExprCXX.cpp]: Perhaps it would be worth introducing `Type::isCXXRecord` for this check. We do it quite often... @cor3ntin WDYT?

Comment (cor3ntin) [reply clang/lib/Sema/SemaExprCXX.cpp]: Sure, that probably make sense. NOT in this pr though, we want to keep to a minimum what we backport

**Comment by cor3ntin** [comment]
@sdkrystian can you merge soon so that we can cherry pick in 19? thanks!

**Comment by nikic** [comment]
It looks like this breaks the clang stage 2 build: https://llvm-compile-time-tracker.com/show_error.php?commit=3cdb30ebbc18fa894d3bd67aebcff76ce7c741ac

**Comment by sdkrystian** [comment]
I have a fix, so I'll reapply this sometime today.

**Comment by porglezomp** [comment]
@sdkrystian sorry to bother, do you have that change to re-land it?

**Comment by sdkrystian** [comment]
@porglezomp Sorry, I'm currently at cppcon but I'll try reland it when I have a moment.
