### PR TITLE
[InstCombine][X86] Fold blendv(x,y,shuffle(bitcast(sext(m)))) -> select(shuffle(m),x,y)

### LINKED ISSUE #58895: [X86] InstCombine fails to replace shuffled _mm_blendv_epi8+icmp with select+icmp
InstCombine has x86 folds that can recognise when a `_mm_blendv_epi8` intrinsic mask comes from a comparison and converts it to a select, even through all the bitcasts due to the `__m128i` type:
```c
#include <x86intrin.h>

__m128i select_m128i(__m128i a, __m128i b, __m128i c, __m128i d)
{
    __m128i mask = (__m128i)((__v16qi)c < (__v16qi)d);
  return _mm_blendv_epi8( a, b, mask );
}
```
```ll
define <2 x i64> @select_m128i(<2 x i64> %a, <2 x i64> %b, <2 x i64> %c, <2 x i64> %d) {
entry:
  %0 = bitcast <2 x i64> %c to <16 x i8>
  %1 = bitcast <2 x i64> %d to <16 x i8>
  %cmp = icmp slt <16 x i8> %0, %1
  %2 = bitcast <2 x i64> %a to <16 x i8>
  %3 = bitcast <2 x i64> %b to <16 x i8>
  %4 = select <16 x i1> %cmp, <16 x i8> %3, <16 x i8> %2
  %5 = bitcast <16 x i8> %4 to <2 x i64>
  ret <2 x i64> %5
}
```
But this fails entirely for AVX1 targets that try to emulate the 256-bit equivalent by splitting/concatenation:
```c
__m256i select_m256i(__m256i a, __m256i b, __m256i c, __m256i d)
{
    __m256i mask = (__m256i)((__v32qi)c < (__v32qi)d);
  __m128i lo = _mm_blendv_epi8( _mm256_extractf128_si256( a, 0 ), _mm256_extractf128_si256( b, 0 ), _mm256_extractf128_si256( mask, 0 ) );
  __m128i hi = _mm_blendv_epi8( _mm256_extractf128_si256( a, 1 ), _mm256_extractf128_si256( b, 1 ), _mm256_extractf128_si256( mask, 1 ) );

#ifdef ALT
    return _mm256_setr_m128i( lo, hi );
#else
  return _mm256_insertf128_si256( _mm256_castsi128_si256( lo ), hi, 1 );
#endif
}
```
```ll
define <4 x i64> @select_m256i(<4 x i64> %a, <4 x i64> %b, <4 x i64> %c, <4 x i64> %d) {
entry:
  %0 = bitcast <4 x i64> %c to <32 x i8>
  %1 = bitcast <4 x i64> %d to <32 x i8>
  %cmp = icmp slt <32 x i8> %0, %1
  %sext = sext <32 x i1> %cmp to <32 x i8>
  %2 = bitcast <4 x i64> %a to <8 x i32>
  %extract = shufflevector <8 x i32> %2, <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %3 = bitcast <4 x i64> %b to <8 x i32>
  %extract1 = shufflevector <8 x i32> %3, <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %4 = bitcast <32 x i8> %sext to <8 x i32>
  %extract2 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %5 = bitcast <4 x i32> %extract to <16 x i8>
  %6 = bitcast <4 x i32> %extract1 to <16 x i8>
  %7 = bitcast <4 x i32> %extract2 to <16 x i8>
  %8 = tail call <16 x i8> @llvm.x86.sse41.pblendvb(<16 x i8> %5, <16 x i8> %6, <16 x i8> %7)
  %9 = bitcast <16 x i8> %8 to <2 x i64>
  %extract3 = shufflevector <8 x i32> %2, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %extract4 = shufflevector <8 x i32> %3, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %extract5 = shufflevector <8 x i32> %4, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %10 = bitcast <4 x i32> %extract3 to <16 x i8>
  %11 = bitcast <4 x i32> %extract4 to <16 x i8>
  %12 = bitcast <4 x i32> %extract5 to <16 x i8>
  %13 = tail call <16 x i8> @llvm.x86.sse41.pblendvb(<16 x i8> %10, <16 x i8> %11, <16 x i8> %12)
  %shuffle.i = shufflevector <2 x i64> %9, <2 x i64> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %14 = bitcast <4 x i64> %shuffle.i to <8 x i32>
  %15 = bitcast <16 x i8> %13 to <4 x i32>
  %widen = shufflevector <4 x i32> %15, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef>
  %insert = shufflevector <8 x i32> %14, <8 x i32> %widen, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
  %16 = bitcast <8 x i32> %insert to <4 x i64>
  ret <4 x i64> %16
}
declare <16 x i8> @llvm.x86.sse41.pblendvb(<16 x i8>, <16 x i8>, <16 x i8>)
```

Goldbolt: https://godbolt.org/z/r61dhrqYM

### PR DESCRIPTION
**Pull request by RKSimon**
We already handle blendv(x,y,bitcast(sext(m))) -> select(m,x,y) cases, but this adds support for peeking through one-use shuffles as well. VectorCombine should already have canonicalized the IR to shuffle(bitcast(...)) for us.

The particular use case is where we have split generic 256/512-bit code to use target-specific blendv intrinsics (e.g. AVX1 spoofing AVX2 256-bit ops).

Fixes #58895

### CODE REVIEW

**Review by KanRobert — APPROVED** [review]
LGTM

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp [hunk 1]
```diff
@@ -2800,6 +2800,23 @@ X86TTIImpl::instCombineIntrinsic(InstCombiner &IC, IntrinsicInst &II) const {
...
     }
 
+    // Peek through a one-use shuffle - VectorCombine should have simplified
+    // this for cases where we're splitting wider vectors to use blendv
+    // intrinsics.
+    Value *MaskSrc = nullptr;
+    ArrayRef<int> ShuffleMask;
+    if (match(Mask, PatternMatch::m_OneUse(PatternMatch::m_Shuffle(
+                        PatternMatch::m_Value(MaskSrc), PatternMatch::m_Undef(),
+                        PatternMatch::m_Mask(ShuffleMask))))) {
```
Comment (goldsteinn) [inline llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2810]: nit: We should probably just start using `PatternMatch` namespace at the top of the function. That can be a later NFC though.

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp [hunk 2]
```diff
@@ -2800,6 +2800,23 @@ X86TTIImpl::instCombineIntrinsic(InstCombiner &IC, IntrinsicInst &II) const {
       return SelectInst::Create(NewSelector, Op1, Op0, "blendv");
     }
 
+    // Peek through a one-use shuffle - VectorCombine should have simplified
+    // this for cases where we're splitting wider vectors to use blendv
+    // intrinsics.
+    Value *MaskSrc = nullptr;
```
Comment (goldsteinn) [inline llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2806]: Should we `peekThroughBitcast` on `Mask` here?

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp [hunk 3]
```diff
@@ -2809,11 +2826,26 @@ X86TTIImpl::instCombineIntrinsic(InstCombiner &IC, IntrinsicInst &II) const {
...
       auto *MaskTy = cast<FixedVectorType>(Mask->getType());
       auto *OpTy = cast<FixedVectorType>(II.getType());
+      unsigned NumMaskElts = MaskTy->getNumElements();
+      unsigned NumOperandElts = OpTy->getNumElements();
+
+      // If we peeked through a shuffle, reapply the shuffle to the bool vector.
+      if (MaskSrc) {
+        unsigned NumMaskSrcElts =
+            cast<FixedVectorType>(MaskSrc->getType())->getNumElements();
+        NumMaskElts = (ShuffleMask.size() * NumMaskElts) / NumMaskSrcElts;
```
Comment (goldsteinn) [inline llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2836]: Isn't `ShuffleMask.size()` equal to `NumMaskSrcElts`?

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp [hunk 4]
```diff
@@ -2809,11 +2826,26 @@ X86TTIImpl::instCombineIntrinsic(InstCombiner &IC, IntrinsicInst &II) const {
...
+        // Multiple mask bits maps to the same operand element - bail out.
+        if (NumMaskElts > NumOperandElts)
```
Comment (goldsteinn) [inline llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2838]: isn't the `scaleShuffleMaskElts` check sufficient? If the shuffle is only smaller type but keep all `OpTy` elements together isn't that fine?

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp (hunk 2 above)
Comment (RKSimon) [reply llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2806]: I'll investigate this as a followup, but I've already tried very hard on VectorCombine to make sure we simplify bitcast(shuffle(bitcast(shuffle()))) chains that we would have to peek through

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp (hunk 3 above)
Comment (RKSimon) [reply llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2836]: IR can have different result and argument vector widths (this patch is mainly to help extract subvector style shuffles after all) - only DAG is fixed

File: llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp (hunk 4 above)
Comment (RKSimon) [reply llvm/lib/Target/X86/X86InstCombineIntrinsic.cpp:2838]: we don't handle NumMaskElts > NumOperandElts (IIRC due to endianess issues) - this is an early out so we don't bother creating an unused shuffle instruction
