### PR TITLE
[lldb][lldb-dap] fix repeating commands in repl mode

### LINKED ISSUE #131589: [lldb][lldb-dap] DAP REPL always repeats the command before returning an output
This only happens when using lldb-dap  example

```
frame variable
(lldb) frame variable
(int) argc = 1
(char **) argv = 0x00007fffffffdd28
(int) var = 32767
(int) var22 = -134593480
```
```
image list
(lldb) image list
[  0] FDDDE44E-8552-60E6-478E-B68FF5C3939D-45C754CE 0x0000000000400000 /home/user/projects/test_lldb/a.out 
[  1] 2A596041-86D5-FBEC-715F-683557FD6907-7886233A 0x00007ffff7fc6000 /usr/lib64/ld-linux-x86-64.so.2 
[  2] F255D04A-D684-1164-6FC3-23289003F1AF-BB5AF13F 0x00007ffff7fc4000 [vdso] (0x00007ffff7fc4000)
[  3] B4F86E51-E7F4-E804-22DC-844C58B6803D-8E7D8CAA 0x00007ffff7ea2000 /lib64/libc++.so.1 
[  4] 5DCBA125-379D-AA92-5E47-F41226E98AA9-159034FD 0x00007ffff7e6d000 /lib64/libc++abi.so.1 
[  5] 3B93904E-3533-B830-5FF0-48A024E213F6-F89C9F48 0x00007ffff7d87000 /lib64/libm.so.6 
[  6] 859E77BB-6C60-4864-70A0-9FAF25A28A6E-716F7DCB 0x00007ffff7d58000 /lib64/libgcc_s.so.1 
[  7] F83D43B9-B4B0-ED5C-2BD0-A1613BF33E08-EE054C93 0x00007ffff7b65000 /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by da-viper**
Fixes #131589
Add a new option to the RunCommands  functions to control the echoing of commands

### CODE REVIEW

File: lldb/tools/lldb-dap/DAP.h [hunk 1]
```diff
@@ -290,7 +290,8 @@ struct DAP {
   ///   \b false if a fatal error was found while executing these commands,
   ///   according to the rules of \a LLDBUtils::RunLLDBCommands.
   bool RunLLDBCommands(llvm::StringRef prefix,
-                       llvm::ArrayRef<std::string> commands);
+                       llvm::ArrayRef<std::string> commands,
+                       bool echo_commands = true);
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/DAP.h:294]: Should we make the default false? 
```suggestion
                       bool echo_commands = false);
```

File: lldb/tools/lldb-dap/LLDBUtils.cpp [hunk 2]
```diff
@@ -17,12 +17,24 @@ namespace lldb_dap {
...
+  // Get the default prompt from settings.
+  std::string prompt_string = "(lldb) ";
+  if (const lldb::SBStructuredData prompt = debugger.GetSetting("prompt")) {
+    const size_t prompt_length = prompt.GetStringValue(nullptr, 0);
+
+    if (prompt_length != 0) {
+      prompt_string.resize(prompt_length + 1);
+      prompt.GetStringValue(prompt_string.data(), prompt_string.length());
+    }
+  }
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/LLDBUtils.cpp:36]: Let's avoid computing this if we don't need it. 
```suggestion
  // We only need the prompt when echoing commands.
  std::string prompt_string;
  if (echo_commands) {
    prompt_string = "(lldb) ";

    // Get the current prompt from settings.
    if (const lldb::SBStructuredData prompt = debugger.GetSetting("prompt")) {
      const size_t prompt_length = prompt.GetStringValue(nullptr, 0);

      if (prompt_length != 0) {
        prompt_string.resize(prompt_length + 1);
        prompt.GetStringValue(prompt_string.data(), prompt_string.length());
      }
    }
  }
```

**Review by JDevlieghere — COMMENTED** [review]
With this patch, is there anything that turns on echoing of commands? Do we think that's a useful feature to support and expose to users (my gut says: probably not). In that case, should we just drop the old code and avoid adding the boolean altogether?

**Comment by da-viper** [comment]
> With this patch, is there anything that turns on echoing of commands? 

Yeah, the launch options 

InitCommands, PreCommands and ***Commands.

File: lldb/tools/lldb-dap/Handler/EvaluateRequestHandler.cpp [hunk 3]
```diff
@@ -164,7 +164,8 @@ void EvaluateRequestHandler::operator()(
       dap.focus_tid = frame.GetThread().GetThreadID();
     }
     auto result = RunLLDBCommandsVerbatim(dap.debugger, llvm::StringRef(),
-                                          {std::string(expression)});
+                                          {std::string(expression)},
+                                          /*echo_commands*/ false);
```
Comment (walter-erquinigo) [inline lldb/tools/lldb-dap/Handler/EvaluateRequestHandler.cpp:168]:
```suggestion
                                          /*echo_commands=*/ false);
```

**Review by walter-erquinigo — APPROVED** [review]
LGTM. Let's see if Jonas has more comments

File: lldb/test/API/tools/lldb-dap/repl-mode/TestDAP_repl_mode_detection.py [hunk 4]
```diff
@@ -28,15 +28,12 @@ def test_completions(self):
 
         self.set_source_breakpoints(source, [breakpoint1_line, breakpoint2_line])
 
-        self.assertEvaluate(
-            "`command regex user_command s/^$/platform/", r"\(lldb\) command regex"
-        )
-        self.assertEvaluate(
-            "`command alias alias_command platform", r"\(lldb\) command alias"
-        )
+        # the result of the commands should return the empty string.
```
Comment (walter-erquinigo) [inline lldb/test/API/tools/lldb-dap/repl-mode/TestDAP_repl_mode_detection.py:31]:
```suggestion
        # The result of the commands should return the empty string.
```

**Review by JDevlieghere — APPROVED** [review]
LGTM modulo `RunLLDBCommandsVerbatim`.
