### PR TITLE
Revert "[Clang] Instantiate local constexpr functions eagerly (#95660)"

### LINKED ISSUE #98526: Clang 19 regression: "error: function 'operator()' with deduced return type cannot be used before it is defined"
The following code, based on Barry Revzin's recursive lambda recommendations and reduced from some actual software, compiles with Clang 18.1 but fails with Clang 19.

- ❌ Clang (trunk): https://godbolt.org/z/79hKhaKx3 (Using `14f745074d05fb42f5c8a625c79bf557bb980ebb`)
- ✅ Clang 18.1: https://godbolt.org/z/cvEWEsEd8

```cpp
#include <utility>

template <typename F> struct recursive_lambda {
    template <typename... Args> auto operator()(Args&&... args) const { return fn(*this, std::forward<Args>(args)...); }
    F fn;
};

template <typename F> recursive_lambda(F) -> recursive_lambda<F>;

struct Tree { Tree *left, *right; };

int sumSize(Tree *tree) {
    auto accumulate = recursive_lambda {
        [&](auto& self_fn, Tree *element_node) -> int {
	    if (!tree) return 0;
	    return 1 + self_fn(tree->left) + self_fn(tree->right);
        }
    };

    return accumulate(tree);
}
```
Fails with:
```
<source>:19:17: error: function 'operator()<Tree *&>' with deduced return type cannot be used before it is defined
   19 |             return 1 + self_fn(tree->left) + self_fn(tree->right);
      |                        ^
<source>:4:80: note: in instantiation of function template specialization 'sumSize(Tree *)::(anonymous class)::operator()<const recursive_lambda<(lambda at <source>:17:9)>>' requested here
    4 |     template <typename... Args> auto operator()(Args&&... args) const { return fn(*this, std::forward<Args>(args)...); }
      |                                                                                ^
<source>:23:22: note: in instantiation of function template specialization 'recursive_lambda<(lambda at <source>:17:9)>::operator()<Tree *&>' requested here
   23 |     return accumulate(tree);
      |                      ^
<source>:4:38: note: 'operator()<Tree *&>' declared here
    4 |     template <typename... Args> auto operator()(Args&&... args) const { return fn(*this, std::forward<Args>(args)...); }
      |                                      ^
```

### PR DESCRIPTION
**Pull request by zyn0217**
Unfortunately, #95660 has caused a regression in DeduceReturnType(), which is a problem in that some of the local recursive lambdas are getting incorrectly rejected.

This reverts commit 5548ea34341e9d0ae645719c34b466ca3b9eaa5a. Also, this adds an offending case to the test.

Closes #98526

### CODE REVIEW

File: clang/test/SemaTemplate/instantiate-local-class.cpp [hunk 1]
```diff
@@ -512,24 +512,31 @@ namespace LambdaInDefaultMemberInitializer {
...
+        return 1 + self_fn(tree->left) + self_fn(tree->right);
+      }};
 
-  static_assert(predicate(1));
-  return func(predicate);
+  return accumulate(tree);
 }
 
-} // namespace GH35052
+} // namespace local_recursive_lambda
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/instantiate-local-class.cpp:540]: Can we leave a reference to the issue here? (also that test can be simplified)

**Review by cor3ntin — APPROVED** [review]
This seems like the best course of action for now... sorry!
Thanks for the PR and the work on these issues
