### PR TITLE
[clang][analyzer] Fix a nullptr dereference when -ftime-trace is used (Reland)

### LINKED ISSUE #139779: New --analyze crash with -ftime-trace
This is a new clang crash, bisected to 6078f5eb214d4cbb74ca9b024b88ff88d963ffd2

Reproducer:

```
// ===================
struct {} a;
// -------------------
```

Use ```clang++ --analyze -ftime-trace foo.cpp``` to observe the crash.

Error output from compiler explorer:  https://godbolt.org/z/WPW3revnG

```
clang++: warning: argument unused during compilation: '-S' [-Wunused-command-line-argument]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics --analyze -ftime-trace <source>
1.	<eof> parser at end of file
 #0 0x0000000003f91538 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f91538)
 #1 0x0000000003f8f1c4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f8f1c4)
 #2 0x0000000003ed3df8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007acec9442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00000000065bc7c4 clang::ento::SymbolConjured::getStmt() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65bc7c4)
 #5 0x00000000065bc89c clang::ento::SymbolConjured::dumpToStream(llvm::raw_ostream&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65bc89c)
 #6 0x000000000651ff97 clang::ento::SymbolicRegion::dumpToStream(llvm::raw_ostream&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x651ff97)
 #7 0x000000000651f538 clang::ento::ElementRegion::dumpToStream(llvm::raw_ostream&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x651f538)
 #8 0x000000000652068c clang::ento::MemRegion::getString[abi:cxx11]() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x652068c)
 #9 0x00000000065b9aee clang::ento::Loc::dumpToStream(llvm::raw_ostream&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b9aee)
#10 0x000000000657771f std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> llvm::function_ref<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ()>::callback_fn<(anonymous namespace)::RegionStoreManager::bind(LimitedRegionBindingsRef const&, clang::ento::Loc, clang::ento::SVal)::'lambda'()>(long) RegionStore.cpp:0:0
#11 0x0000000003f23363 llvm::TimeTraceProfiler::begin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, llvm::function_ref<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ()>, llvm::TimeTraceEventType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f23363)
#12 0x0000000003f24934 llvm::timeTraceProfilerBegin(llvm::StringRef, llvm::function_ref<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f24934)
#13 0x000000000657de5b (anonymous namespace)::RegionStoreManager::bind(LimitedRegionBindingsRef const&, clang::ento::Loc, clang::ento::SVal) RegionStore.cpp:0:0
#14 0x000000000657e67a (anonymous namespace)::RegionStoreManager::Bind(void const*, clang::ento::Loc, clang::ento::SVal) RegionStore.cpp:0:0
#15 0x00000000065454ca clang::ento::ProgramState::bindLoc(clang::ento::Loc, clang::ento::SVal, clang::LocationContext const*, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65454ca)
#16 0x0000000006125943 clang::ento::errno_modeling::setErrnoValue(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::ento::CheckerContext&, unsigned long, clang::ento::errno_modeling::ErrnoCheckState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6125943)
#17 0x0000000006126aa4 void clang::ento::check::BeginFunction::_checkBeginFunction<(anonymous namespace)::ErrnoModeling>(void*, clang::ento::CheckerContext&) ErrnoModeling.cpp:0:0
#18 0x000000000647f6ba clang::ento::CheckerManager::runCheckersForBeginFunction(clang::ento::ExplodedNodeSet&, clang::BlockEdge const&, clang::ento::ExplodedNode*, clang::ento::ExprEngine&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x647f6ba)
#19 0x00000000064bdac9 clang::ento::ExprEngine::processBeginOfFunction(clang::ento::NodeBuilderContext&, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&, clang::BlockEdge const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64bdac9)
#20 0x000000000648c38c clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x648c38c)
#21 0x0000000006048ea7 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*, void>>*) AnalysisConsumer.cpp:0:0
#22 0x000000000604ac3e (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph(unsigned int) AnalysisConsumer.cpp:0:0
#23 0x000000000604c4f3 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) AnalysisConsumer.cpp:0:0
#24 0x00000000066145ec clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66145ec)
#25 0x0000000004c2ce05 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c2ce05)
#26 0x0000000004baba3e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4baba3e)
#27 0x0000000004d209a9 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4d209a9)
#28 0x0000000000daacdf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdaacdf)
#29 0x0000000000da0eaa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#30 0x000000000499d9e9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#31 0x0000000003ed4294 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ed4294)
#32 0x000000000499dfff clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#33 0x000000000495fdcd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x495fdcd)
#34 0x0000000004960e5e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4960e5e)
#35 0x0000000004969145 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4969145)
#36 0x0000000000da6c48 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda6c48)
#37 0x0000000000c2c554 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc2c554)
#38 0x00007acec9429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#39 0x00007acec9429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#40 0x0000000000da0955 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda0955)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Fixes #139779.

The bug was introduced in #137355 in `SymbolConjured::getStmt`, when
trying to obtain a statement for a CFG initializer without an
initializer.  This commit adds a null check before access.

Previous PR #139820, Revert #139936

Additional notes since previous PR:

When conjuring a symbol, sometimes there is no valid CFG element, e.g. in the file causing the crash, there is no element at all in the CFG. In these cases, the CFG element reference in the expression engine will be invalid. As a consequence, there needs to be extra checks to ensure the validity of the CFG element reference.

### CODE REVIEW

**Comment by steakhal** [comment]
I think this would still trip on the same memory issue.
The problem to me is that we read uninitialized memory. So even if you limit the bounds of the result of the read of such uninitialized memory, it would only mask and limit the effect of such read.
Have you tried running the failing case via valgrind? That's usually great for catching uninitialized reads.
msan is also great, but that needs an instrumented standard library which may be tough to set up.

**Review by steakhal — CHANGES_REQUESTED** [review]
.

**Comment by fangyi-zhou** [comment]
> I think this would still trip on the same memory issue. The problem to me is that we read uninitialized memory. So even if you limit the bounds of the result of the read of such uninitialized memory, it would only mask and limit the effect of such read. Have you tried running the failing case via valgrind? That's usually great for catching uninitialized reads. msan is also great, but that needs an instrumented standard library which may be tough to set up.

I don't think so. I have an asan build locally and it worked.

The methods `getParent()` and `getIndexInBlock()` in CFGElementRef does not access memory, since they only return the value from the ref. The actual dereference happens in `->` operator, which is gated after the newly added `if` condition.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 1]
```diff
@@ -101,9 +101,17 @@ class SymbolConjured : public SymbolData {
 
   // It might return null.
   const Stmt *getStmt() const {
+    if (const auto *Parent = Elem.getParent()) {
+      // Sometimes the CFG element is invalid, avoid dereferencing it.
+      if (Elem.getIndexInBlock() >= Parent->size())
+        return nullptr;
```
Comment (steakhal) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: WHen can  the CFG element invalid? Where is it coming from?
My argument is that the CFG element should be always valid, and if it's not then my gut feeling is that that is because the CFG element is uninitialized. And I'm dreading uninitialized values because they are really hard to track down, and this is why I'm pushing back against this change to much just to be on the safe side.

**Review by steakhal — COMMENTED** [review]
> > I think this would still trip on the same memory issue. The problem to me is that we read uninitialized memory. So even if you limit the bounds of the result of the read of such uninitialized memory, it would only mask and limit the effect of such read. Have you tried running the failing case via valgrind? That's usually great for catching uninitialized reads. msan is also great, but that needs an instrumented standard library which may be tough to set up.
> 
> I don't think so. I have an asan build locally and it worked.
> 
> The methods `getParent()` and `getIndexInBlock()` in CFGElementRef does not access memory, since they only return the value from the ref. The actual dereference happens in `->` operator, which is gated after the newly added `if` condition.

My understanding is that asan will not check if a memory is initialized or not. It checks if the access is valid - but since you guard the access we would brush this under the carpet now.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h (hunk 1 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: > My argument is that the CFG element should be always valid

Unfortunately I don't think this is true. As I mentioned, the CFG contains no elements, therefore, when a value needs to be conjured, an invalid CFG element ref is passed on from the expression engine. I didn't have a way to track down which call is causing the problem, and I agree with you that I don't like this change --- it's a band-aid instead of a proper fix.

The invalid CFG ref likely comes from the fact that https://github.com/llvm/llvm-project/blob/4ba8f4e213c97733e3b61e5856b0e85e3d7d6a7f/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h#L229-L232 will use the current statement index. In a case at initialisation, the value is initialised at 0.

Afaik, the errno checking will try to conjure a symbol, which uses the initial invalid CFG element. I can't immediately pinpoint where that happens or if there are better ways to fix. Let me know what you think.

**Comment by fangyi-zhou** [comment]
valgrind result:

```
$ valgrind ./bin/clang -cc1 -analyze -analyzer-checker=apiModeling -ftime-trace=test.json ../clang/test/Analysis/ftime-trace-no-init.cpp
==825619== Memcheck, a memory error detector
==825619== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==825619== Using Valgrind-3.25.0 and LibVEX; rerun with -h for copyright info
==825619== Command: ./bin/clang -cc1 -analyze -analyzer-checker=apiModeling -ftime-trace=test.json ../clang/test/Analysis/ftime-trace-no-init.cpp
==825619== 
==825619== 
==825619== HEAP SUMMARY:
==825619==     in use at exit: 73,728 bytes in 1 blocks
==825619==   total heap usage: 7,012 allocs, 7,011 frees, 2,733,844 bytes allocated
==825619== 
==825619== LEAK SUMMARY:
==825619==    definitely lost: 0 bytes in 0 blocks
==825619==    indirectly lost: 0 bytes in 0 blocks
==825619==      possibly lost: 0 bytes in 0 blocks
==825619==    still reachable: 73,728 bytes in 1 blocks
==825619==         suppressed: 0 bytes in 0 blocks
==825619== Rerun with --leak-check=full to see details of leaked memory
==825619== 
==825619== For lists of detected and suppressed errors, rerun with: -s
==825619== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h (hunk 1 above)
Comment (steakhal) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: It's `ErrnoModeling::checkBeginFunction()` that conjures for the value of errno at the very beginning of the analysis, at when we enter the top level function. That calls ExprEngine::getCFGElementRef, and that is where we get a nullptr block ptr and also the place when we take the now _stale_ `currStmtIdx` value.

Now that I grepped for, it seems like we set `currStmtIdx` only at a single place: `ExprEngine::processCFGElement`. This also makes sense.

It seems like `processCFGElement` is called from `CoreEngine::HandleBlockEntrance` from `CoreEngine::dispatchWorkItem`.

The hunk you linked with the definition of `getCFGElementRef` makes me think that the invalid CFGElement is denoted by the NULL blockPtr. Consequently, what we should do in our dump function to first check if this CFG element is valid by checking the blockPtr against null - and not looking at the `getIndexInBlock`.

Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: I'm getting a bit confused here. The issue at hand is that we have a valid `blockPtr` and an invalid index (`ptr` points to the correct CFG block, but the block has no elements, and the index is set to the default value of 0). Are you suggesting that we should check both the pointer and the index?

Comment (steakhal) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: Alright, I get it now - I think. Thanks for summing it up btw.
So if I understand you correctly, you say that empty basic blocks are valid, thus we should account for the valid cases when a basic block doesnt have any elements. Right?

If this would be the case, then I think the PR looks good.

Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:107]: Yes, that's consistent with the ASan reports (reading uninit memory). I used the phrase "invalid CFG element" which probably caused some confusion --- the element ref is invalid in the sense that it points to nowhere.

I'll add a null check just in case, better safe than sorry.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 2]
```diff
@@ -100,41 +100,7 @@ class SymbolConjured : public SymbolData {
   ConstCFGElementRef getCFGElementRef() const { return Elem; }
 
   // It might return null.
-  const Stmt *getStmt() const {
```
Comment (fangyi-zhou) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:103]: moved this out of the header file because I feel like this is getting too big to be included in the header, let me know if you agree

Comment (steakhal) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:103]: It must have been painful to iterate on this code :D
I agree, it should be in a cpp file.

**Review by steakhal — APPROVED** [review]
LGTM. Thanks for the nice discussion.

**Comment by steakhal** [comment]
I'll wait for the premerge checks to show green to avoid more reverts.
