### PR TITLE
[clang][CodeGen] Promote point of GRO(CWG2563)

### LINKED ISSUE #120200: [clang] [coroutine] Possible over optimization of co_return
Hi, clang community

I want to discuss an unusual usage of coroutine and CRTP. The following code gives the expected result using MSVC, but a unpredictable result using GCC and clang. Intert a printf into final_suspend helps clang give the expected result.

A similar discussion is on [GCC Bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=118074).

https://godbolt.org/z/5rGjKPhW1

clang version: 16.0.0 ~ trunk
Build option: -std=c++20 -O2
```
#include <cstdio>
#include <utility>
#include <coroutine>

template<class T>
struct CRCoro { // Curiously Recurring Coroutine
    struct RValueWrapper {
        T* p;

        operator T&&() const noexcept { return std::move(*p); }
    };

    using promise_type = T;

    T& getDerived() noexcept { return *static_cast<T*>(this); }

    auto get_return_object() noexcept { return RValueWrapper(&getDerived()); }
    std::suspend_never initial_suspend() noexcept { return {}; }
    std::suspend_never final_suspend() noexcept {
        //printf("final_suspend\n");
        return {};
    }
    void return_value(T&& x) noexcept { getDerived() = std::move(x); }
    void unhandled_exception() {}
};

struct A : public CRCoro<A> {
    int a;
};

A func() {
    A aa{};
    aa.a = 5;
    co_return std::move(aa);
}

int main() {
    printf("%d\n", func().a);
    return 0;
}
```
Expected result(MSVC): 5
Possible result of clang: -387938488

### PR DESCRIPTION
**Pull request by NewSigma**
This patch attempts to implement piece of the proposed solution to [CWG2563](https://cplusplus.github.io/CWG/issues/2563.html):

> [9.6.4 dcl.fct.def.coroutine.p8] This return exits the scope of gro. It exits the scope of promise only if the coroutine completed without suspending.

If a coroutine completes without suspending, it does not exit the scope of the promise until GRO conversion is done, because GRO conversion is considered part of the coroutine execution. The current behavior performs conversion after coroutine state cleanup, which does not conform to the standard:

``` LLVM
before.cleanup:
  ; ...
  br label %coro.cleanup

coro.cleanup:
  ; cleanup logics
  br %coro.end

coro.end:
  call void @llvm.coro.end(ptr null, i1 false, token none)
  ; GRO conversion
  ; ret GRO or void
```
This patch proposes the following codegen:
``` LLVM
any.suspend:
  %suspend = call i8 @llvm.coro.suspend(token %8, i1 true)
  switch i8 %suspend, label %pre.gro.conv [
    i8 0, label %ready
    i8 1, label %coro.cleanup
  ]

ready:
  ; ...

pre.gro.conv:
  %body.done = phi i1 [ false, %any.suspend ], [ true, %any.ready ]
  %InRamp = call i1 @llvm.coro.is_in_ramp()
  br i1 %InRamp, label %gro.conv, label %after.gro.conv

gro.conv:
  ; GRO conversion
  br label %after.gro.conv

after.gro.conv:
  br i1 %body.done, label %coro.cleanup, label %coro.ret

coro.cleanup:
  ; cleanup logics
  br %coro.ret

coro.ret:
  call void @llvm.coro.end(ptr null, i1 false, token none)
  ; ret GRO or void
```

I'm not quite sure I understood the wording correctly. Feel free to correct me.

Close #120200

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
I don't understand this: 

> Do not lower coro.end to ret void if its return value will be used. This allows front end separate coro start section and resume section without early return from resume function.

Could elaborate it? Especially why it is safe to not lower  `coro.end` to `ret void`?

**Comment by NewSigma** [comment]
> Could elaborate it? Especially why it is safe to not lower coro.end to ret void?

The idea is: if we lower `coro.end` to `ret void`, users of `coro.end` will become unreachable. Thus, I assume that if the frontend uses the return value of `coro.end`, the intention is to determine whether we are in the start or resume part.

Personally, I think the problem is that `coro.end` mixes two functionalities: querying where we are and lowering to some code. I think it might be reasonable to introduce a new intrinsic, `llvm.coro.where`, and drop the return value of `coro.end`. However, I’d prefer to hear others’ thoughts before actually doing it.

File: llvm/lib/Transforms/Coroutines/Coroutines.cpp [hunk 1]
```diff
@@ -259,18 +259,6 @@ void coro::Shape::analyze(Function &F,
...
           HasUnwindCoroEnd = true;
-
-        if (CoroEnds.back()->isFallthrough() && isa<CoroEndInst>(II)) {
-          // Make sure that the fallthrough coro.end is the first element in the
-          // CoroEnds vector.
-          // Note: I don't think this is neccessary anymore.
-          if (CoroEnds.size() > 1) {
-            if (CoroEnds.front()->isFallthrough())
-              report_fatal_error(
-                  "Only one coro.end can be marked as fallthrough");
```
Comment (NewSigma) [inline llvm/lib/Transforms/Coroutines/Coroutines.cpp:270]: Noting that `simplifycfg` might duplicate `coro.end` in some cases, I suggest relaxing this restriction.

**Comment by ChuanqiXu9** [comment]
> > Could elaborate it? Especially why it is safe to not lower coro.end to ret void?
> 
> The idea is: if we lower `coro.end` to `ret void`, users of `coro.end` will become unreachable. Thus, I assume that if the frontend uses the return value of `coro.end`, the intention is to determine whether we are in the start or resume part instead of returning.
> 
> Personally, I think the problem is that `coro.end` mixes two functionalities: querying where we are and lowering to some code. I think it might be reasonable to introduce a new intrinsic, `llvm.coro.where`, and drop the return value of `coro.end`. However, I’d prefer to hear others’ thoughts before actually doing it.

Since I didn't have time to look into details, the instinct reaction to my mind is, then why do we change the lowering of `coro.end` **conditionally**? I mean, if it is good, it will be better and simpler to do it unconditionally.

**Comment by NewSigma** [comment]
> then why do we change the lowering of coro.end conditionally? I mean, if it is good, it will be better and simpler to do it unconditionally.

It is reasonable. I will use a new intrinsic instead of lower `coro.end` conditionally.

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 2]
```diff
@@ -642,6 +650,37 @@ struct CallCoroDelete final : public EHScopeStack::Cleanup {
...
+        cast<llvm::BranchInst>(PreConvBB->getTerminator())->getSuccessor(1);
+    BasicBlock *CleanupBB = AfterConvBB->getSingleSuccessor();
+    BasicBlock *PreCleanupBB = CleanupBB->splitBasicBlock(
+        CleanupBB->getFirstNonPHIIt(), "pre.coro.cleanup", true);
+    Builder.SetInsertPoint(PreCleanupBB);
+    PreCleanupBB->getTerminator()->eraseFromParent();
+
+    auto *NeedCleanup = Builder.CreatePHI(
+        Builder.getInt1Ty(), llvm::pred_size(PreCleanupBB), "is.completed");
+    for (auto *Pred : llvm::predecessors(PreCleanupBB)) {
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: I didn't get this. The size of pred of PreCleanupBB shouldn't always be 1. And what's the intention of `EmitPreCleanupBB`. I didn't understand it.

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 3]
```diff
@@ -691,7 +730,7 @@ struct GetReturnObjectManager {
   // split its emission in two parts. EmitGroAlloca emits an alloca and sets up
   // cleanups. Later when coroutine promise is available we initialize the gro
   // and sets the flag that the cleanup is now active.
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: We need to update the comments too.

File: clang/lib/CodeGen/CGCoroutine.cpp (hunk 2 above)
Comment (NewSigma) [reply clang/lib/CodeGen/CGCoroutine.cpp]: > The size of pred of PreCleanupBB shouldn't always be 1?

I missed that. Thanks.

> And what's the intention of EmitPreCleanupBB. I didn't understand it.

Since `SuspendBB` is now `pre.gro.conv`, we need a branching so that suspending does not destroy the coroutine.

File: clang/lib/CodeGen/CGCoroutine.cpp (hunk 3 above)
Comment (NewSigma) [reply clang/lib/CodeGen/CGCoroutine.cpp]: Done, thanks.

**Review by ChuanqiXu9 — COMMENTED** [review]
The conversion related part looks slightly anti-pattern and slightly smells dangerous. Can we try to avoid emitting the conversion part if conversion won't happen and only emit if the conversion will happen?

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 4]
```diff
@@ -768,6 +779,41 @@ struct GetReturnObjectManager {
...
+    Builder.CreateBr(AfterConvBB);
+
+    CGF.EmitBlock(PreConvBB);
+    PreConvBB->moveBefore(ConvBB);
+    auto *BodyDone =
+        Builder.CreatePHI(Builder.getInt1Ty(), llvm::pred_size(PreConvBB));
+    for (auto *Pred : llvm::predecessors(PreConvBB)) {
+      auto *V = (Pred == AfterFinalBB) ? Builder.getTrue() : Builder.getFalse();
+      BodyDone->addIncoming(V, Pred);
+    }
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: Add a comment to explain the intention of BodyDone. And similarly add it to CurCoroData.

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 5]
```diff
@@ -973,8 +1028,27 @@ void CodeGenFunction::EmitCoroutineBody(const CoroutineBodyStmt &S) {
...
+          cast<llvm::BranchInst>(PreConvBB->getTerminator())->getSuccessor(0);
+      auto FromIt = ++RetBB->getFirstInsertionPt();
+      auto ToIt = RetBB->getTerminator()->getIterator();
+      ConvBB->splice(ConvBB->getFirstNonPHIIt(), RetBB, FromIt, ToIt);
+
+      // After gro conversion, destroy the coroutine if it finishes execution.
+      BasicBlock *AfterConvBB =
+          cast<llvm::BranchInst>(PreConvBB->getTerminator())->getSuccessor(1);
+      BasicBlock *CleanupBB = AfterConvBB->getSingleSuccessor();
+      auto *BodyDone = &*PreConvBB->phis().begin();
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: Similarly, let's record it.

File: clang/lib/CodeGen/CGCoroutine.cpp (hunk 4 above)
Comment (NewSigma) [reply clang/lib/CodeGen/CGCoroutine.cpp]: Done. I renamed it to `IsFinalExit` and made it local, so that we do not have to record it.

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 6]
```diff
@@ -973,8 +1063,18 @@ void CodeGenFunction::EmitCoroutineBody(const CoroutineBodyStmt &S) {
...
+    if (!GroManager.DirectEmit) {
+      EndCall->moveBefore(RetBB->getTerminator()->getIterator());
+      // Send GRO conversion to ConvBB
+      BasicBlock *ConvBB = GroManager.ConvBB;
+      auto *GroConv = RetBB->splitBasicBlockBefore(EndCall);
+      GroConv->replaceAllUsesWith(RetBB);
+      GroConv->getTerminator()->eraseFromParent();
+      ConvBB->splice(ConvBB->begin(), GroConv);
+      GroConv->eraseFromParent();
+    }
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: The dance here seems slightly not straighforward. Is it possible to directly emit in ConvBB if we need Conv?

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 7]
```diff
@@ -768,6 +781,76 @@ struct GetReturnObjectManager {
...
+  // without ever being suspended. The EmitGroConv function evaluates these
+  // conditions and executes the conversion if true.
+  //
+  // Before EmitGroConv():
+  //   final.exit:
+  //     switch i32 %cleanup.dest, label %destroy [
+  //        i32 0, label %InsertPt
+  //     ]
+  //
+  //   InsertPt:
```
Comment (ChuanqiXu9) [inline clang/lib/CodeGen/CGCoroutine.cpp]: InsertPt is not a meaningful name. Let's change it to the real name.

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. Thanks.
