### PR TITLE
[ELF] -r/--emit-relocs: Fix crash when processing .rela.text before .text

### LINKED ISSUE #156417: [LLD] Crash when relocations proceed relocated section in Orphan Sections Initialization
When the relocation section is placed before the relocated section and the relocated section is not defined in the linker script, an error will occur during the linking process.

**Issue Cause:**  
In a.ro, `.rela.text` precedes its relocated `InputSection` `.text`. `addOrphanSections` doesn't handle this scenario. 
When it processes `.rela.text`, in the called `getOutputSectionName`, `rel->getOutputSection()` is nullptr (input `.text` doesn't yet have a parent output section), leading to an assertion failure.

### PR DESCRIPTION
**Pull request by mykouHW**
fixes #156417 

When the relocation section is placed before the relocated section and the relocated section is not defined in the linker script, an error will occur during the linking process.

**Issue Cause:**  
In a.ro, `.rela.text` precedes its relocated `InputSection` `.text`. `addOrphanSections` doesn't handle this scenario. 
When it processes `.rela.text`, in the called `getOutputSectionName`, `rel->getOutputSection()` is nullptr (input `.text` doesn't yet have a parent output section), leading to an assertion failure.

**Solution:**  
For --emit-relocs and -r, ensure the output section for `.text.foo` is created before the output section for `.rela.text.foo`.

### CODE REVIEW

File: lld/ELF/LinkerScript.cpp [hunk 1]
```diff
@@ -1037,10 +1037,14 @@ void LinkerScript::addOrphanSections() {
     if (ctx.arg.relocatable && (isec->flags & SHF_LINK_ORDER))
       continue;
 
-    if (auto *sec = dyn_cast<InputSection>(isec))
-      if (InputSectionBase *rel = sec->getRelocatedSection())
+    if (auto *sec = dyn_cast<InputSection>(isec)){
```
Comment (smithp35) [inline lld/ELF/LinkerScript.cpp:1040]: Can you git clang-format the patch? I would expect a space between `){` i.e. `(isec)) {`

File: lld/ELF/LinkerScript.cpp [hunk 2]
```diff
@@ -1037,10 +1037,14 @@ void LinkerScript::addOrphanSections() {
...
+      if (InputSectionBase *rel = sec->getRelocatedSection()){
+        if (auto *relIS = dyn_cast_or_null<InputSectionBase>(rel))
```
Comment (smithp35) [inline lld/ELF/LinkerScript.cpp:1042]: Could we add a comment before the if statement like
// Ensure creation of OutputSection for relocated section before relocation section.

File: lld/test/ELF/linkerscript/orphan-sections-init.s [hunk 3]
```diff
@@ -0,0 +1,30 @@
+# REQUIRES: x86
+# RUN: rm -rf %t && mkdir -p %t
+# RUN: split-file %s %t && cd %t
+
+# RUN: llvm-mc -filetype=obj -triple=x86_64 foo.s -o foo.o
+
+# RUN: ld.lld -r  foo.o -T script.ld -o foo_mc.o
+
+# RUN: llvm-objcopy --rename-section .text=.com.text foo_mc.o foo_mc.o
```
Comment (smithp35) [inline lld/test/ELF/linkerscript/orphan-sections-init.s:9]: You can merge do both -rename-section commands with a single instance of llvm-objcopy.

File: lld/test/ELF/linkerscript/orphan-sections-init.s [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+#--- foo.s
+  .text
+  .globl	foo
+  .p2align	4
+  .type	foo,@function
+foo:
+  mov $bar, %rax
+
+
```
Comment (smithp35) [inline lld/test/ELF/linkerscript/orphan-sections-init.s:22]: I recommend a CHECK of the llvm-readelf --sections output to make sure lld has created the link from the relocations correctly.

I've seen some scripts been run to find tests with no FileCheck output before so it is worth putting at least one in.

File: lld/test/ELF/linkerscript/orphan-sections-init.s [hunk 5]
```diff
@@ -0,0 +1,30 @@
+# REQUIRES: x86
+# RUN: rm -rf %t && mkdir -p %t
+# RUN: split-file %s %t && cd %t
+
```
Comment (smithp35) [inline lld/test/ELF/linkerscript/orphan-sections-init.s:4]: Could you add a comment to explain the test. Without context the steps look strange. LLD uses an additional comment character to distinguish comments from lit commands, so comment lines would start `##`

For example:
```
Test that lld's orphan section placement can handle a relocatable link where the relocation section is seen before the relocated section. To create a test case we need to first need to create a relocatable object with
the relocations before the relocated section. Then we rename these to make these orphans.
```

I tried to see if I could create the test case without llvm-objcopy but it seemed like I needed the linker script to have .rela.text as the pattern to get it to place first.

**Review by smithp35 — COMMENTED** [review]
I recommend not using the word `vulnerability` in titles and description as this is usually reserved for security bugs.

I suggest something like `[lld][ELF] Fix crash when relocations proceed relocated section.

I also recommend putting the analysis in the linked issue into the description as this will form the commit message. It is much easier to find and search for changes with `git log` when the commit message has all the details.

**Review by smithp35 — COMMENTED** [review]
Thanks for the update. I've enabled the CI. Assuming that goes well then this looks good to me.

I've added the maintainer @MaskRay to see if he has any opinions.

**Comment by mykouHW** [comment]
@MaskRay Hello, do you have any suggestions regarding this PR?  :)

**Comment by MaskRay** [comment]
I think the description needs to be clarified. My comment at 156417 could be used. I'll push the change like 
https://github.com/MaskRay/llvm-project/tree/lld-156354 and merge this for you.

**Comment by mykouHW** [comment]
> I think the description needs to be clarified. My comment at 156417 could be used. I'll push the change like https://github.com/MaskRay/llvm-project/tree/lld-156354 and merge this for you.

That's great, thank you for your revisions and assistance!

**Review by MaskRay — APPROVED** [review]
