### PR TITLE
[DirectX] add support for i64 buffer load/stores

### LINKED ISSUE #140321: [DirectX] DXILBitcodeWriter is trying to encode unsupported TargetExtTyID
## repro
```bash
lldb -- clang-dxc DirectML/Product/Shaders/Generated/Cast_float16_native_accum32_uint64_emulated_256_Strided4D.hlsl -E CSMain -T cs_6_2  -enable-16bit-types  -O3 -D DXC_COMPILER=1 -D __SHADER_TARGET_MAJOR=6 -D __SHADER_TARGET_MINOR=2 -I DirectML/Product/Shaders/ -Fo /validation/Cast_float16_native_accum32_uint64_emulated_256_Strided4D.dat
```
## fatal error location
https://github.com/llvm/llvm-project/blob/286ab11dc65de8175e2bce69fd7e36acd3be7ce0/llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp#L1024-L1026

```gdb
(lldb) expr T->dump()
target("dx.RawBuffer", %struct.uint64_emulated, 1, 0)

(lldb) expr *T
(llvm::Type) $1 = {
  Context = 0x000000011f00b010
  ID = TargetExtTyID
  SubclassData = 2
  NumContainedTys = 1
  ContainedTys = 0x000000011f977570
```
## crash stack
```bash
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000102027e68 clang-dxc`llvm::dxil::DXILBitcodeWriter::writeTypeTable(this=0x000000016fdf5708) at DXILBitcodeWriter.cpp:1025:7 [opt]
    frame #1: 0x0000000102025580 clang-dxc`llvm::dxil::DXILBitcodeWriter::write(this=0x000000016fdf5708) at DXILBitcodeWriter.cpp:2888:3 [opt]
    frame #2: 0x00000001020252c0 clang-dxc`llvm::dxil::BitcodeWriter::writeModule(this=0x000000016fdf5a40, M=0x000000011f006c50) at DXILBitcodeWriter.cpp:436:16 [opt]
    frame #3: 0x0000000102025098 clang-dxc`llvm::dxil::WriteDXILToFile(M=0x000000011f006c50, Out=0x000000016fdf5be0) at DXILBitcodeWriter.cpp:406:10 [opt]
    frame #4: 0x0000000102041724 clang-dxc`(anonymous namespace)::EmbedDXILPass::runOnModule(this=<unavailable>, M=0x000000011f006c50) at DXILWriterPass.cpp:73:5 [opt]
    frame #5: 0x0000000100c103fc clang-dxc`llvm::legacy::PassManagerImpl::run(llvm::Module&) at LegacyPassManager.cpp:1521:27 [opt]
    frame #6: 0x0000000100c101c4 clang-dxc`llvm::legacy::PassManagerImpl::run(this=<unavailable>, M=0x000000011f006c50) at LegacyPassManager.cpp:539:44 [opt]
    frame #7: 0x00000001017f8fb0 clang-dxc`clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) at BackendUtil.cpp:1262:19 [opt]
    frame #8: 0x00000001017f8d18 clang-dxc`clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) [inlined] (anonymous namespace)::EmitAssemblyHelper::emitAssembly(this=0x000000016fdf5f50, Action=<unavailable>, OS=llvm::raw_pwrite_stream @ 0x000000011f008bf0, BC=<unavailable>) at BackendUtil.cpp:1286:3 [opt]
    frame #9: 0x00000001017f89d4 clang-dxc`clang::emitBackendOutput(CI=0x000000011f00a6a0, CGOpts=<unavailable>, TDesc=(Data = "e-m:e-p:32:32-i1:32-i8:8-i16:16-i32:32-i64:64-f16:16-f32:32-f64:64-n8:16:32:64", Length = 78), M=<unavailable>, Action=<unavailable>, VFS=<unavailable>, OS=<unavailable>, BC=0x000000011f006a20) at BackendUtil.cpp:1451:13 [opt]
    frame #10: 0x0000000101a5a6ac clang-dxc`clang::BackendConsumer::HandleTranslationUnit(this=0x000000011f006a20, C=0x000000011e839200) at CodeGenAction.cpp:316:3 [opt]
    frame #11: 0x0000000102925f94 clang-dxc`clang::ParseAST(S=0x000000011f82a600, PrintStats=<unavailable>, SkipFunctionBodies=<unavailable>) at ParseAST.cpp:184:13 [opt]
    frame #12: 0x0000000101e800fc clang-dxc`clang::FrontendAction::Execute(this=<unavailable>) at FrontendAction.cpp:1221:3 [opt]
    frame #13: 0x0000000101e1c7e8 clang-dxc`clang::CompilerInstance::ExecuteAction(this=0x000000011f00a6a0, Act=0x000000011f00c5c0) at CompilerInstance.cpp:1057:33 [opt]
    frame #14: 0x0000000101ef8b64 clang-dxc`clang::ExecuteCompilerInvocation(Clang=0x000000011f00a6a0) at ExecuteCompilerInvocation.cpp:300:25 [opt]
    frame #15: 0x0000000100009c50 clang-dxc`cc1_main(Argv=<unavailable>, Argv0=<unavailable>, MainAddr=0x00000001000054d4) at cc1_main.cpp:297:15 [opt]
    frame #16: 0x0000000100007424 clang-dxc`ExecuteCC1Tool(ArgV=<unavailable>, ToolContext=0x000000016fdfe8c8) at driver.cpp:223:12 [opt]
    frame #17: 0x0000000101ca719c clang-dxc`void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(long) [inlined] llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::operator()(this=<unavailable>, params=<unavailable>) const at STLFunctionalExtras.h:69:12 [opt]
    frame #18: 0x0000000101ca7190 clang-dxc`void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(long) [inlined] clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0::operator()(this=0x000000016fdfa0d0) const at Job.cpp:436:34 [opt]
    frame #19: 0x0000000101ca718c clang-dxc`void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(callable=6171893968) at STLFunctionalExtras.h:46:12 [opt]
    frame #20: 0x000000010136ee10 clang-dxc`llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) [inlined] llvm::function_ref<void ()>::operator()(this=<unavailable>) const at STLFunctionalExtras.h:69:12 [opt]
    frame #21: 0x000000010136ee08 clang-dxc`llvm::CrashRecoveryContext::RunSafely(this=<unavailable>, Fn=function_ref<void ()> @ 0x000000055b5e8d90) at CrashRecoveryContext.cpp:427:3 [opt]
    frame #22: 0x0000000101ca6c24 clang-dxc`clang::driver::CC1Command::Execute(this=0x000000011f005350, Redirects=<unavailable>, ErrMsg=<unavailable>, ExecutionFailed=<unavailable>) const at Job.cpp:436:12 [opt]
    frame #23: 0x0000000101c7997c clang-dxc`clang::driver::Compilation::ExecuteCommand(this=0x000000011df22a40, C=0x000000011f005350, FailingCommand=0x000000016fdfa618, LogOnly=false) const at Compilation.cpp:196:15 [opt]
    frame #24: 0x0000000101c79b44 clang-dxc`clang::driver::Compilation::ExecuteJobs(this=0x000000011df22a40, Jobs=<unavailable>, FailingCommands=0x000000016fdfa810, LogOnly=false) const at Compilation.cpp:251:19 [opt]
    frame #25: 0x0000000101c8fb28 clang-dxc`clang::driver::Driver::ExecuteCompilation(this=0x000000016fdfa860, C=0x000000011df22a40, FailingCommands=0x000000016fdfa810) at Driver.cpp:2226:5 [opt]
    frame #26: 0x00000001000069b0 clang-dxc`clang_main(Argc=<unavailable>, Argv=<unavailable>, ToolContext=0x000000016fdfe8c8) at driver.cpp:407:21 [opt]
    frame #27: 0x000000010001200c clang-dxc`main(argc=<unavailable>, argv=<unavailable>) at clang-driver.cpp:17:10 [opt]
    frame #28: 0x0000000183f4eb4c dyld`start + 6000
```

### PR DESCRIPTION
**Pull request by farzonl**
fixes llvm/llvm-project#140321

Specifically it fixes ` error: Cannot create BufferLoad operation: Invalid overload type` 
https://hlsl.godbolt.org/z/dTq4q7o58
but no new DML shaders are building. This change now exposes llvm/llvm-project#144747.

The change does two things it adds i64 support for intrinsic expansion for the `dx_resource_load_typedbuffer`, and `dx_resource_store_typedbuffer` intrinsics.

It also lets loaded typedbuffers crash more gracefully  because of ` auto *EVI = cast<ExtractValueInst>(U);` is now a `dyn_cast` and `llvm_unreachable`.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 1]
```diff
@@ -570,22 +575,54 @@ static bool expandTypedBufferLoadIntrinsic(CallInst *Orig) {
...
   Value *CheckBit = nullptr;
   for (User *U : make_early_inc_range(Orig->users())) {
-    auto *EVI = cast<ExtractValueInst>(U);
+    if (auto *Ret = dyn_cast<ReturnInst>(U)) {
+      // For return instructions, we need to handle the case where the function
+      // is directly returning the result of the call
+      Type *RetTy = Ret->getFunction()->getReturnType();
+      Value *StructRet = PoisonValue::get(RetTy);
+      StructRet = Builder.CreateInsertValue(StructRet, Result, {0});
+      Value *CheckBitForRet = Builder.CreateExtractValue(Load, {1});
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: I don't think you can do this. My understanding is this will fail the validator because you have unconditionally  accessed the check bit.
https://github.com/llvm/llvm-project/pull/139996#discussion_r2110225269
Also see the other note on anonymous struct types.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 2]
```diff
@@ -570,22 +575,54 @@ static bool expandTypedBufferLoadIntrinsic(CallInst *Orig) {
...
+      // For int64, manually combine two int32s
+      // First, zero-extend both values to i64
+      Value *Lo = Builder.CreateZExt(ExtractElements[I], Builder.getInt64Ty());
+      Value *Hi =
+          Builder.CreateZExt(ExtractElements[I + 1], Builder.getInt64Ty());
+      // Shift the high bits left by 32 bits
+      Value *ShiftedHi = Builder.CreateShl(Hi, Builder.getInt64(32));
+      // OR the high and low bits together
+      Combined = Builder.CreateOr(Lo, ShiftedHi);
+    }
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: Might be worth pulling this out into a function? `createCombined64Bit(IRBuilder, Value *, Value *)` or something like that.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp (hunk 1 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: I removed the return handling. it isn't required for this pr.

Comment (bogner) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: Yeah, it's kind of a moot point because this is entirely unreachable from HLSL (or C++) source:
1. There is no `i1` type - bool in HLSL is 32 bits and in C++ it's 8, so the struct we would return from a function is `{i64, i32}`, not `{i64, i1}`
2. Because of struct return ABI stuff in clang, the signature we actually get from such functions is `define void @loadi64({i64, i1} *)` (see https://hlsl.godbolt.org/z/nEeeM933K)
3. On top of all of that, the way we get here from HLSL is [T Buffer<T>::Load(int, out uint)](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-buffer-load), so we wouldn't be using the result or the intrinsic directly even if we did manage to pack it back into the right shape

I think it makes sense to leave the return handling out.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 3]
```diff
@@ -609,38 +634,82 @@ static bool expandTypedBufferStoreIntrinsic(CallInst *Orig) {
...
+        Val =
+            Builder.CreateInsertElement(Val, LowBits, Builder.getInt32(I * 2));
+        Val = Builder.CreateInsertElement(Val, HighBits,
+                                          Builder.getInt32(I * 2 + 1));
+      }
+    } else {
+      // Handle scalar int64
+      Value *LowBits = Builder.CreateTrunc(InputVal, Int32Ty);
+      Value *ShiftedVal = Builder.CreateLShr(InputVal, Builder.getInt64(32));
+      Value *HighBits = Builder.CreateTrunc(ShiftedVal, Int32Ty);
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: I think you can combine the scalar and vector logic if you avoid scalarizing this by hand. Ie, you could do something like:
```c++
    Constant *ShiftAmt = Builder.getInt64(32);
    if (IsVector)
      ShiftAmt = ConstantVector::getSplat(ElementCount::getFixed(2), ShiftAmt);

    // Split into low and high 32-bit parts
    Value *LowBits = Builder.CreateTrunc(InputVal, SplitElementTy);
    Value *ShiftedVal = Builder.CreateLShr(InputVal, ShiftAmt);
    Value *HighBits = Builder.CreateTrunc(ShiftedVal, SplitElementTy);
```

Then I think this fits nicely with the logic for doubles above where we're just changing the conversion operation itself and the surrounding IR is unchanged.

**Comment by spall** [comment]
This also closes llvm/offload-test-suite#275  ?

**Comment by farzonl** [comment]
> This also closes llvm/offload-test-suite#275 ?

i'm going to convert that into a test ticket for the offload test suite

**Comment by spall** [comment]
> > This also closes llvm/offload-test-suite#275 ?
> 
> i'm going to convert that into a test ticket for the offload test suite

I don't follow?

**Review by spall — APPROVED** [review]
lgtm

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 4]
```diff
@@ -570,22 +588,34 @@ static bool expandTypedBufferLoadIntrinsic(CallInst *Orig) {
...
-                                {ExtractElements[I], ExtractElements[I + 1]});
+    Value *Combined = nullptr;
+    if (IsDouble)
+      // For doubles, use dx_asdouble intrinsic
+      Combined =
+          Builder.CreateIntrinsic(Builder.getDoubleTy(), Intrinsic::dx_asdouble,
+                                  {ExtractElements[I], ExtractElements[I + 1]});
+    else
+      Combined = createCombinedi32toi64Expansion(Builder, ExtractElements[I],
+                                                 ExtractElements[I + 1]);
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: I think you misunderstood my suggestion, or at least I don't think it really improves things much to do it as written here. I was thinking we'd put the logic for combining i32s into *either* a double or an int64 into a function, so here we have a simple:
```c++
  Value *Combined = combineI32s(Builder, ExtractElements[I], ExtractElements[I + 1], /*ToDouble=*/IsDouble);
```
This makes it so that the surrounding logic is all clearly about handling the shared logic, and the small difference in what we emit for the conversion itself is what's abstracted into the function.

This would also apply to `expandTypedBufferStoreIntrinsic`, where we could have some kind of `splitToI32s` along the lines of:
```c++
static std::pair<Value *, Value *> splitToI32s(IRBuilder<> &Builder,
                                               Value *InputVal, bool FromVector,
                                               bool FromDouble);
```

The downside is of course the awkward boolean parameters, but I think the way it breaks the code up simplifies things enough to justify it. If you disagree it's probably okay to just do the expansions inline as you have in the store case.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 5]
```diff
@@ -609,38 +639,64 @@ static bool expandTypedBufferStoreIntrinsic(CallInst *Orig) {
...
   }
 
-  Type *SplitElementTy = Builder.getInt32Ty();
-  if (ExtractNum == 4)
+  // Create the appropriate vector type for the result
+  Type *Int32Ty = Builder.getInt32Ty();
+  Type *ResultTy = VectorType::get(Int32Ty, IsVector ? 4 : 2, false);
+  Value *Val = PoisonValue::get(ResultTy);
+
+  // Handle double type(s)
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: comment out of date - this is also in the i64 path.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 6]
```diff
@@ -609,38 +639,64 @@ static bool expandTypedBufferStoreIntrinsic(CallInst *Orig) {
...
+    LowBits = Builder.CreateTrunc(InputVal, SplitElementTy);
+    Value *ShiftedVal = Builder.CreateLShr(InputVal, ShiftAmt);
+    HighBits = Builder.CreateTrunc(ShiftedVal, SplitElementTy);
+  }
+
+  if (IsVector) {
+    // For vector doubles, use shuffle to create the final vector
+    Val = Builder.CreateShuffleVector(LowBits, HighBits, {0, 2, 1, 3});
+  } else {
+    // For scalar doubles, insert the elements
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: Same here - these comments should just mention vector/scalar, not doubles.

**Review by bogner — APPROVED** [review]
A follow up to one of my previous suggestions and a few notes on misleading comments, but once those are taken care of this looks good.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp (hunk 6 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: those comments were originally there before my pr and I don't actually think they add any value so I'm just going to remove them.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp (hunk 5 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: just going to remove it.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp (hunk 4 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: I don't agree, I prefer if helper functions have as little branching behavior as possible. For me personally it makes it easier when I'm debugging and expansion like this one if I can assume  one block of code gets generated and I don't have to step into a helper to know which branch is taken. I also like to keep intrinsic creation for dx_asdouble in the `expandTypedBufferLoadIntrinsic.` Because thats kind of the whole point of this expansion for the double case and abstracting the logic out to a helper makes  the code harder to read  because its not linear. So when you are trying to understand whats going on you have to context switch to a new function. I think the current helper is a good compromise you can see the double logic and understand that the i64 case performs a similar function.

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp]: we reached a compromise to go back to the old behavior.
