### PR TITLE
[VectorCombine] Fold reduce(trunc(x)) -> trunc(reduce(x)) iff cost effective

### LINKED ISSUE #81469: [X86] Prefer trunc(reduce(x)) over reduce(trunc(x))
Reported here: https://discourse.llvm.org/t/avx2-popcount-regression/76926

```cpp
int popcount8(uint64_t data[8]) {
  int count = 0;
  for (int i = 0; i < 8; ++i)
    count += __builtin_popcountll(data[i]);
  return count;
}
```
```ll
define i32 @popcount8(ptr %data)  {
entry:
  %0 = load <8 x i64>, ptr %data, align 8
  %1 = tail call <8 x i64> @llvm.ctpop.v8i64(<8 x i64> %0)
  %2 = trunc <8 x i64> %1 to <8 x i32>
  %3 = tail call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %2)
  ret i32 %3
}
declare <8 x i64> @llvm.ctpop.v8i64(<8 x i64>)
declare i32 @llvm.vector.reduce.add.v8i32(<8 x i32>)
```

We can avoid the vector truncation replacing with a free scalar truncation if we perform the reduction on the v8i64:
```ll
define i32 @popcount8(ptr %data)  {
entry:
  %0 = load <8 x i64>, ptr %data, align 8
  %1 = tail call <8 x i64> @llvm.ctpop.v8i64(<8 x i64> %0)
  %2 = tail call i64 @llvm.vector.reduce.add.v8i64 (<8 x i64 > %1)
  %3 = trunc i64 %2 to i32
  ret i32 %3
}
declare <8 x i64> @llvm.ctpop.v8i64(<8 x i64>) #1
declare i64 @llvm.vector.reduce.add.v8i64(<8 x i64>)
```
Godbolt: https://simd.godbolt.org/z/ooK497x7s

We might be best off attempting this in vector-combine

### PR DESCRIPTION
**Pull request by RKSimon**
Vector truncations can be pretty expensive, especially on X86, whilst scalar truncations are often free.

If the cost of performing the add/mul/and/or/xor reduction is cheap enough on the pre-truncated type, then avoid the vector truncation entirely.

Fixes https://github.com/llvm/llvm-project/issues/81469

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 1]
```diff
@@ -1526,6 +1527,67 @@ bool VectorCombine::foldShuffleFromReductions(Instruction &I) {
...
+    break;
+  case Intrinsic::vector_reduce_or:
+    ReductionOpc = Instruction::Or;
+    break;
+  case Intrinsic::vector_reduce_xor:
+    ReductionOpc = Instruction::Xor;
+    break;
+  default:
+    return false;
+  }
```
Comment (nikic) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1556]: Surely this switch already exists somewhere?

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 2]
```diff
@@ -1526,6 +1527,67 @@ bool VectorCombine::foldShuffleFromReductions(Instruction &I) {
...
+  Value *ReductionSrc = I.getOperand(0);
+
+  Value *TruncSrc;
+  if (!match(ReductionSrc, m_Trunc(m_OneUse(m_Value(TruncSrc)))))
```
Comment (nikic) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1560]: Why is there a one-use requirement on the trunc *source*, rather than the trunc? Please add a multi-use test.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 3]
```diff
@@ -1526,6 +1527,67 @@ bool VectorCombine::foldShuffleFromReductions(Instruction &I) {
...
+    return false;
+
+  auto *Trunc = cast<CastInst>(ReductionSrc);
+  auto *TruncTy = cast<VectorType>(TruncSrc->getType());
```
Comment (nikic) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1564]:
```suggestion
  auto *TruncSrcTy = cast<VectorType>(TruncSrc->getType());
```
Or `SrcTy`. As is that sounds like the trunc result type.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp (hunk 1 above)
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1556]: Amazingly no, I'll do a cleanup

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp (hunk 2 above)
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp]: My mistake - tests added to check for this

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 4]
```diff
@@ -29,6 +29,7 @@
 #include "llvm/IR/PatternMatch.h"
 #include "llvm/Support/CommandLine.h"
 #include "llvm/Transforms/Utils/Local.h"
+#include "llvm/Transforms/Utils/LoopUtils.h"
```
Comment (phoebewang) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:32]: Is this required? I don't find anything related to LoopUtils.

Comment (nikic) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:32]: getArithmeticReductionInstruction() is defined there.

**Review by nikic — APPROVED** [review]
LG

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 5]
```diff
@@ -1526,6 +1528,60 @@ bool VectorCombine::foldShuffleFromReductions(Instruction &I) {
...
+      TTI.getArithmeticReductionCost(ReductionOpc, ReductionSrcTy, std::nullopt,
+                                     CostKind);
+  InstructionCost NewCost =
+      TTI.getArithmeticReductionCost(ReductionOpc, TruncSrcTy, std::nullopt,
+                                     CostKind) +
+      TTI.getCastInstrCost(Instruction::Trunc, ResultTy,
+                           ReductionSrcTy->getScalarType(),
+                           TTI::CastContextHint::None, CostKind);
+
+  if (OldCost < NewCost || !NewCost.isValid())
```
[the remark this answers is not in the document]
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp]: Nice catch - fixed.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp (hunk 4 above)
Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:32]: Yes, the reduction intrinsics mapping helpers are all defined in LoopUtils.h
