### PR TITLE
[flang][openmp]Add UserReductionDetails and use in DECLARE REDUCTION

### LINKED ISSUE #66453: [Flang][OpenMP] Compilation error of `declare reduction` directive
This is an issue from Fujitsu testsuite.

Flang-new terminates abnormally when compiling `declare reduction` directive.
(Probably it has not been implemented yet.)

The following are the test program, Flang-new and gfortran compilation result.

```fortran
! test.f90
!$omp declare reduction(ior:real(4):omp_out=omp_in+omp_out)
end
```
```console
$ flang-new -v test.f90 -fopenmp
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 444abb396c340e52a8a4db5778b7d6b3b6195070)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-redhat-linux/8
Selected GCC installation: /usr/lib/gcc/aarch64-redhat-linux/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -emit-obj -fopenmp -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +neon -target-feature +v8a -o /tmp/test-fdc0ba.o -x f95-cpp-input test.f90
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /path/to/install/bin/flang-new -fc1 -triple aarch64-unknown-linux-gnu -emit-obj -fopenmp -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +neon -target-feature +v8a -o /tmp/test-fdc0ba.o -x f95-cpp-input test.f90
 #0 0x0000ffffa6975f60 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/path/to/install/bin/../lib/libLLVMSupport.so.18git+0x1a5f60)
 #1 0x0000ffffa6973b40 llvm::sys::RunSignalHandlers() (/path/to/install/bin/../lib/libLLVMSupport.so.18git+0x1a3b40)
 #2 0x0000ffffa6973cb0 SignalHandler(int) Signals.cpp:0:0
 #3 0x0000ffffa845066c (linux-vdso.so.1+0x66c)
 #4 0x0000ffffa6352dbc raise (/lib64/libc.so.6+0x32dbc)
 #5 0x0000ffffa6340928 abort (/lib64/libc.so.6+0x20928)
 #6 0x0000ffffa28395d0 Fortran::evaluate::ExpressionAnalyzer::IntegerTypeSpecKind(Fortran::parser::IntegerTypeSpec const&) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x4295d0)
 #7 0x0000ffffa28f59c4 Fortran::semantics::ScopeHandler::MakeNumericType(Fortran::common::TypeCategory, std::optional<Fortran::parser::KindSelector> const&) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x4e59c4)
 #8 0x0000ffffa291ba64 void Fortran::parser::Walk<Fortran::semantics::ResolveNamesVisitor>(Fortran::parser::IntrinsicTypeSpec::Real const&, Fortran::semantics::ResolveNamesVisitor&) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x50ba64)
 #9 0x0000ffffa2927e5c void Fortran::parser::ForEachInTuple<1ul, void Fortran::parser::Walk<Fortran::semantics::ResolveNamesVisitor, Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>>(std::tuple<Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>> const&, Fortran::semantics::ResolveNamesVisitor&)::'lambda'(Fortran::semantics::ResolveNamesVisitor const&), std::tuple<Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>>>(std::tuple<Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>> const&, void Fortran::parser::Walk<Fortran::semantics::ResolveNamesVisitor, Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>>(std::tuple<Fortran::parser::Verbatim, Fortran::parser::OmpReductionOperator, std::__cxx11::list<Fortran::parser::DeclarationTypeSpec, std::allocator<Fortran::parser::DeclarationTypeSpec>>, Fortran::parser::OmpReductionCombiner, std::optional<Fortran::parser::OmpReductionInitializerClause>> const&, Fortran::semantics::ResolveNamesVisitor&)::'lambda'(Fortran::semantics::ResolveNamesVisitor const&)) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x517e5c)
#10 0x0000ffffa2933a7c Fortran::semantics::ResolveNamesVisitor::Pre(Fortran::parser::SpecificationPart const&) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x523a7c)
#11 0x0000ffffa2953e4c Fortran::semantics::ResolveNamesVisitor::ResolveSpecificationParts(Fortran::semantics::ProgramTree&) (.part.0) resolve-names.cpp:0:0
#12 0x0000ffffa29543b0 Fortran::semantics::ResolveNamesVisitor::Pre(Fortran::parser::ProgramUnit const&) (.part.0) resolve-names.cpp:0:0
#13 0x0000ffffa2955398 Fortran::semantics::ResolveNames(Fortran::semantics::SemanticsContext&, Fortran::parser::Program const&, Fortran::semantics::Scope&) (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x545398)
#14 0x0000ffffa29c7b64 Fortran::semantics::Semantics::Perform() (/path/to/install/bin/../lib/../lib/libFortranSemantics.so.18git+0x5b7b64)
#15 0x0000ffffa7593314 Fortran::frontend::FrontendAction::runSemanticChecks() (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x53314)
#16 0x0000ffffa765d2d0 Fortran::frontend::CodeGenAction::beginSourceFileAction() (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x11d2d0)
#17 0x0000ffffa7594e30 Fortran::frontend::FrontendAction::beginSourceFile(Fortran::frontend::CompilerInstance&, Fortran::frontend::FrontendInputFile const&) (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x54e30)
#18 0x0000ffffa75841f0 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/path/to/install/bin/../lib/libflangFrontend.so.18git+0x441f0)
#19 0x0000ffffa7ae3bbc Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/path/to/install/bin/../lib/libflangFrontendTool.so.18git+0x3bbc)
#20 0x00000000004048dc fc1_main(llvm::ArrayRef<char const*>, char const*) (/path/to/install/bin/flang-new+0x4048dc)
#21 0x0000000000403108 main (/path/to/install/bin/flang-new+0x403108)
#22 0x0000ffffa6340d64 __libc_start_main (/lib64/libc.so.6+0x20d64)
#23 0x00000000004035d0 _start (/path/to/install/bin/flang-new+0x4035d0)
flang-new: error: unable to execute command: Aborted (core dumped)
flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git 444abb396c340e52a8a4db5778b7d6b3b6195070)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
flang-new: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
flang-new: note: diagnostic msg: /tmp/test-239fff
flang-new: note: diagnostic msg: /tmp/test-239fff.sh
flang-new: note: diagnostic msg: 

********************
```
```console
$ gfortran -v test.f90 -fopenmp
Driving: gfortran -v test.f90 -fopenmp -l gfortran -l m -shared-libgcc
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-redhat-linux/8/lto-wrapper
Target: aarch64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-gnu-indirect-function --build=aarch64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC) 
 :
$
```

### LINKED ISSUE #92832: [Flang][OpenMP] Compilation error when type-list in declare reduction construct is a derived type
```
Version of flang-new : 19.0.0(1a498103ee5c4d101e70dc49db11938d8b87b518)/AArch64
```
When `type-list` in `declare reduction` construct is a `derived type`, a compilation-time error occurs.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

udr_arr_init_struct_.f90:
```fortran
subroutine s1
  type t1
     integer(8):: a,b,c,d,e
  end type t1
!$omp declare reduction (a:t1:omp_out%c=omp_out%c+omp_in%c) &
!$omp         initializer(omp_priv%c=10)
  type(t1)::k1(2)
  integer::omp_get_num_threads, tn
  k1%c=0
!$omp parallel
!$omp master
  tn = omp_get_num_threads()
!$omp end master
!$omp end parallel
!$omp parallel reduction(a:k1)
  k1%c=k1%c+1
!$omp end parallel
  if (all(k1%c==11*tn)) then
     print *, 'ok'
  else
     print *, 'ng'
     print *, k1%c
  endif
end subroutine s1

program main
  call s1
end program main
```

```
$ flang-new -fopenmp udr_arr_init_struct_.f90
error: Could not parse udr_arr_init_struct_.f90
./udr_arr_init_struct_.f90:5:28: error: expected 'TYPE'
  !$omp declare reduction (a:t1:omp_out%c=omp_out%c+omp_in%c) &
                             ^
./udr_arr_init_struct_.f90:5:28: in the context: declaration type spec
  !$omp declare reduction (a:t1:omp_out%c=omp_out%c+omp_in%c) &
                             ^
./udr_arr_init_struct_.f90:5:1: in the context: specification construct
  !$omp declare reduction (a:t1:omp_out%c=omp_out%c+omp_in%c) &
  ^
./udr_arr_init_struct_.f90:5:1: in the context: declaration construct
  !$omp declare reduction (a:t1:omp_out%c=omp_out%c+omp_in%c) &
  ^
./udr_arr_init_struct_.f90:2:3: in the context: specification part
    type t1
    ^
./udr_arr_init_struct_.f90:1:1: in the context: SUBROUTINE subprogram
  subroutine s1
  ^
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp udr_arr_init_struct_.f90; ./a.out
 ok
$
```

```
$ export OMP_NUM_THREADS=2; ifort -qopenmp -diag-disable=10448 udr_arr_init_struct_.f90; ./a.out
 ok
$
```

### LINKED ISSUE #97241: [Flang][OpenMP] Compilation error when initializer-clause is specified as declare reduction directive
```
Version of flang-new : 19.0.0(1f98ac095e35f12a85d71101269df00279faa55c)/AArch64
```

When `initializer-clause` is specified as `declare reduction` directive, a compilation error occurs.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

simd9_UDR_0005_22.f90:
```fortran
subroutine initn(x,n)
  integer x,n
  x=n
end subroutine initn

function foo0(x, n, init)
  integer foo0
  integer x(n)
  integer tmp
  tmp=init
  do i=1,n
     tmp=tmp+x(i)
  enddo
  foo0=tmp
end function foo0

function foo(x, n, init)
  integer foo
  integer x(n)
  integer tmp
  interface
     subroutine initn(x,n)
       integer x,n
     end subroutine initn
  end interface
!$omp declare reduction(udr_add:integer(4):omp_out=omp_out+omp_in) initializer(initn(omp_priv,0))
  tmp=init
!$omp simd reduction(udr_add:tmp)
  do i=1,n
     tmp=tmp+x(i)
  enddo
  foo=tmp
end function foo

program main
  integer,parameter::N=10
  integer x(N)/1,2,3,4,5,6,7,8,9,10/
  integer ret0,ret
  interface
     function foo0(x,n,init)
       integer foo0,x(n),init
     end function foo0
     function foo(x,n,init)
       integer foo,x(n),init
     end function foo
  end interface
  ret0 = foo0(x,N,10)
  ret = foo(x,N,10);
  if (ret0.ne.ret) then
     print*,"NG:",ret0,ret
  endif
  print*,ret0,ret
  print*,"OK"
end program main
```

```
$ flang-new -fopenmp simd9_UDR_0005_2.f90
error: Could not parse simd9_UDR_0005_22.f90
./simd9_UDR_0005_22.f90:26:68: error: expected end of line
  !$omp declare reduction(udr_add:integer(4):omp_out=omp_out+omp_in) initializer(initn(omp_priv,0))
                                                                     ^
./simd9_UDR_0005_22.f90:26:1: in the context: specification construct
  !$omp declare reduction(udr_add:integer(4):omp_out=omp_out+omp_in) initializer(initn(omp_priv,0))
  ^
./simd9_UDR_0005_22.f90:26:1: in the context: declaration construct
  !$omp declare reduction(udr_add:integer(4):omp_out=omp_out+omp_in) initializer(initn(omp_priv,0))
  ^
./simd9_UDR_0005_22.f90:18:3: in the context: specification part
    integer foo
    ^
./simd9_UDR_0005_22.f90:17:1: in the context: FUNCTION subprogram
  function foo(x, n, init)
  ^
$
```

```
$ gfortran -fopenmp simd9_UDR_0005_22.f90; ./a.out
          65          65
 OK
$
```

```
$ ifort -qopenmp -diag-disable=10448 simd9_UDR_0005_22.f90; ./a.out
          65          65
 OK
$
```

### PR DESCRIPTION
**Pull request by tblah**
This adds another puzzle piece for the support of OpenMP DECLARE REDUCTION functionality.

This adds support for operators with derived types, as well as declaring multiple different types with the same name or operator.

A new detail class for UserReductionDetials is introduced to hold the list of types supported for a given reduction declaration.

Tests for parsing and symbol generation added.

Declare reduction is still not supported to lowering, it will generate a "Not yet implemented" fatal error.

Fixes #141306
Fixes #97241
Fixes #92832
Fixes #66453

### CODE REVIEW

**Comment by tblah** [comment]
This is a continuation of @Leporacanthicus's work in https://github.com/llvm/llvm-project/pull/131628.

**Comment by tblah** [comment]
ping for review

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 1]
```diff
@@ -3508,6 +3509,17 @@ bool OmpStructureChecker::CheckReductionOperator(
         break;
       }
     }
+    // User-defined operators are OK if there has been a declared reduction
+    // for that. We mangle those names to store the user details.
+    if (const auto *definedOp{std::get_if<parser::DefinedOpName>(&dOpr.u)}) {
+      std::string mangled = MangleDefinedOperator(definedOp->v.symbol->name());
+      const Scope &scope = definedOp->v.symbol->owner();
+      if (const Symbol *symbol = scope.FindSymbol(mangled)) {
```
[the remark this answers is not in the document]
Comment (tblah) [reply flang/lib/Semantics/check-omp-structure.cpp]: https://github.com/llvm/llvm-project/pull/140066/commits/693112efb87380439f2ac8a6e6e0e230136d9a54

File: flang/lib/Semantics/resolve-names.cpp [hunk 2]
```diff
@@ -1785,14 +1794,91 @@ void OmpVisitor::ProcessMapperSpecifier(const parser::OmpMapperSpecifier &spec,
...
+std::string MangleDefinedOperator(const parser::CharBlock &name) {
+  CHECK(name[0] == '.' && name[name.size() - 1] == '.');
+  return "op" + name.ToString();
+}
+
+template <typename T>
 void OmpVisitor::ProcessReductionSpecifier(
     const parser::OmpReductionSpecifier &spec,
-    const std::optional<parser::OmpClauseList> &clauses) {
+    const std::optional<parser::OmpClauseList> &clauses,
```
[the remark this answers is not in the document]
Comment (tblah) [reply flang/lib/Semantics/resolve-names.cpp:1857]: https://github.com/llvm/llvm-project/pull/140066/commits/83e8fb1852fff31072b586d6667978d84b4a5c4f

File: flang/include/flang/Semantics/semantics.h [hunk 3]
```diff
@@ -290,6 +290,10 @@ class SemanticsContext {
   // Top-level ProgramTrees are owned by the SemanticsContext for persistence.
   ProgramTree &SaveProgramTree(ProgramTree &&);
 
+  // Store (and get a reference to the stored string) for mangled names
+  // used for OpenMP DECLARE REDUCTION.
+  std::string &StoreUserReductionName(const std::string &name);
```
[the remark this answers is not in the document]
Comment (tblah) [reply flang/include/flang/Semantics/semantics.h]: https://github.com/llvm/llvm-project/pull/140066/commits/9a7d1ab21ddf3d08e6dce851b1f2fab1ceef502a

[the remark this answers is not in the document]
Comment (tblah) [reply flang/include/flang/Semantics/semantics.h]: SaveTempName is used elsewhere for saving mangled names so I'm not adding any new confusion here. There's currently no code removing any strings that are added via that helper so the lifetime should be okay.

File: flang/include/flang/Semantics/symbol.h [hunk 4]
```diff
@@ -728,14 +730,48 @@ class GenericDetails {
...
+class UserReductionDetails {
+public:
+  using TypeVector = std::vector<const DeclTypeSpec *>;
+  using DeclInfo = std::variant<const parser::OpenMPDeclareReductionConstruct *,
+      const parser::OmpMetadirectiveDirective *>;
+  using DeclVector = std::vector<DeclInfo>;
+
+  UserReductionDetails() = default;
+
+  void AddType(const DeclTypeSpec &type) { typeList_.push_back(&type); }
```
Comment (NimishMishra) [inline flang/include/flang/Semantics/symbol.h:745]: Nit (feel free to ignore): `emplace_back` may be preferable for non-trivial types in std::vector

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 5]
```diff
@@ -3623,27 +3646,39 @@ static bool IsReductionAllowedForType(
...
-    }
-    return true;
+      parser::CharBlock name{MakeNameFromOperator(*intrinsicOp, context)};
+      return CheckSymbolSupportsType(scope, name, type);
+    } else if (const auto *definedOp{
+                   std::get_if<parser::DefinedOpName>(&dOpr.u)}) {
+      return CheckSymbolSupportsType(
+          scope, MangleDefinedOperator(definedOp->v.symbol->name()), type);
+    }
+    DIE("Intrinsic Operator not found - parsing gone wrong?");
```
Comment (NimishMishra) [inline flang/lib/Semantics/check-omp-structure.cpp]: Nit: Should this be `DIE` or a semantic error that sources the offending source?

**Review by NimishMishra — APPROVED** [review]
LGTM overall. But please wait for another approval

File: flang/lib/Semantics/check-omp-structure.cpp (hunk 5 above)
Comment (tblah) [reply flang/lib/Semantics/check-omp-structure.cpp]: I'll replace this with unreachable to make it clearer

File: flang/include/flang/Semantics/symbol.h (hunk 4 above)
Comment (tblah) [reply flang/include/flang/Semantics/symbol.h:745]: I ignored here (because it is just adding a pointer). But the other one does benefit from emplace_back to construct the variant in place. Thanks

**Comment by kiranchandramohan** [comment]
Could you check the format complaints again?

File: flang/lib/Semantics/mod-file.cpp [hunk 6]
```diff
@@ -1043,6 +1044,28 @@ void ModFileWriter::PutTypeParam(llvm::raw_ostream &os, const Symbol &symbol) {
   os << '\n';
 }
 
+void ModFileWriter::PutUserReduction(
+    llvm::raw_ostream &os, const Symbol &symbol) {
+  const auto &details{symbol.get<UserReductionDetails>()};
+  // The module content for a OpenMP Declare Reduction is the OpenMP
+  // declaration. There may be multiple declarations.
+  // Decls are pointers, so do not use a referene.
```
Comment (kiranchandramohan) [inline flang/lib/Semantics/mod-file.cpp]:
```suggestion
  // Decls are pointers, so do not use a reference.
```

File: flang/lib/Semantics/resolve-names.cpp [hunk 7]
```diff
@@ -1801,14 +1810,92 @@ void OmpVisitor::ProcessMapperSpecifier(const parser::OmpMapperSpecifier &spec,
...
   const auto &id{std::get<parser::OmpReductionIdentifier>(spec.t)};
-  if (auto procDes{std::get_if<parser::ProcedureDesignator>(&id.u)}) {
-    if (auto *name{std::get_if<parser::Name>(&procDes->u)}) {
-      name->symbol =
-          &MakeSymbol(*name, MiscDetails{MiscDetails::Kind::ConstructName});
+  if (auto *procDes{std::get_if<parser::ProcedureDesignator>(&id.u)}) {
+    name = std::get_if<parser::Name>(&procDes->u);
+    // This shouldn't be a procedure component: this is the name of the
+    // reduction being declared.
+    assert(name && "ProcedureDesignator contained ProcComponentRef");
```
Comment (kiranchandramohan) [inline flang/lib/Semantics/resolve-names.cpp]: Could you use the `CHECK` macro?

**Review by kiranchandramohan — APPROVED** [review]
We will probably have to revisit when we implement the lowering.

Please check whether the reported issues error out properly now.
https://github.com/llvm/llvm-project/issues/141306
https://github.com/llvm/llvm-project/issues/119960
https://github.com/llvm/llvm-project/issues/97241
https://github.com/llvm/llvm-project/issues/92832
https://github.com/llvm/llvm-project/issues/66453
https://github.com/llvm/llvm-project/issues/57219

LG.

**Comment by tblah** [comment]
#119960 is written in C

#57219 does parse correctly but I don't think it is correct to error about a - reduction operator deprecation if the user defined reduction is being referenced.

The others all produce NYI errors.

**Comment by tblah** [comment]
I'm going to merge this as it is and fix the - reduction operator deprecation warning in a follow-up patch. This patch is already too big.
