### PR TITLE
[clang-tidy]Fix PreferMemberInitializer false positive for reassignment

### LINKED ISSUE #70192: cppcoreguidelines-prefer-member-initializer should not touch assignments to references
clang-tidy check cppcoreguidelines-prefer-member-initializer (tested with LLVM 17.0.1) overwrites reference member initialization by assignment value found in the constructor body.

Before
```
class Lock
{
public:
    Lock(bool& lock) : m_lock(lock)
    {
        m_lock = true;
    }
private:
    bool& m_lock;
};
```

After
```
class Lock
{
public:
    Lock(bool& lock) : m_lock(true)
    {
        
    }
    
private:
    bool& m_lock;
};
```
Since m_lock is a reference to bool and already initialized in the member initializer list the assignment to m_lock should be left as it is.

### PR DESCRIPTION
**Pull request by HerrCai0907**
- assignment twice cannot be simplified to once when assigning to reference type
- safe assignment cannot be advanced before unsafe assignment

### CODE REVIEW

File: clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp [hunk 1]
```diff
@@ -54,31 +56,43 @@ static bool shouldBeDefaultMemberInitializer(const Expr *Value) {
...
 // effects or if they do reference another field that's initialized before this
 // field, but is modified before the assignment.
-static bool isSafeAssignment(const FieldDecl *Field, const Expr *Init,
-                             const CXXConstructorDecl *Context) {
+static AssignedLevel isSafeAssignment(const FieldDecl *Field, const Expr *Init,
+                                      const CXXConstructorDecl *Context,
+                                      AssignedLevel HistoryLevel) {
+  if (HistoryLevel == AssignedLevel::UnsafetyAssigned)
+    return AssignedLevel::UnsafetyAssigned;
+  if (Field->getType()->isReferenceType() &&
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp:78]: Read a CanonicalType here,  teference could be from template, or from a typedef.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -250,7 +250,8 @@ Changes in existing checks
 
 - Improved :doc:`cppcoreguidelines-prefer-member-initializer
   <clang-tidy/checks/cppcoreguidelines/prefer-member-initializer>` check to
-  ignore delegate constructors.
+  ignore delegate constructors and ignore re-assignment for reference or after
+  unsafety assignment.
```
Comment (PiotrZSL) [inline clang-tools-extra/docs/ReleaseNotes.rst:254]: would be good to clarify what unsafety means here, maybe "ignore re-assignment for reference or when initialization depend on field that is initialized before."

**Review by PiotrZSL — CHANGES_REQUESTED** [review]
Just few nits, mainly naming.

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/prefer-member-initializer.cpp [hunk 3]
```diff
@@ -570,3 +570,19 @@ struct PR52818  {
...
+};
+
+struct ReassignmentAfterUnsafetyAssignment {
+  ReassignmentAfterUnsafetyAssignment() {
+    int a = 10;
+    m_i = a;
+    m_i = 1;
+  }
+  int m_i;
+};
```
[the remark this answers is not in the document]
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/prefer-member-initializer.cpp:588]: positive tests still have some issue. It will report for each assignments. But I don't find a good solution to handle this case. It's already marked in `isSafeAssignment`.
```c++
// TODO: Probably should guard against function calls that could have side
// effects or if they do reference another field that's initialized before this
// field, but is modified before the assignment.
```

File: clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp [hunk 4]
```diff
@@ -156,6 +153,49 @@ void PreferMemberInitializerCheck::check(
   const CXXRecordDecl *Class = Ctor->getParent();
   bool FirstToCtorInits = true;
 
+  std::map<const FieldDecl *, AssignedLevel> AssignedFields{};
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp:156]: Consider something like llvm::SmallDenceMap or llvm::SmallMapVector or something....

**Review by PiotrZSL — APPROVED** [review]
Overall looks fine.
