### PR TITLE
[clang-format] Fix an off-by-1 bug with -length option

### LINKED ISSUE #56245: clang-format --length behavior
From the documentation:

`--length=<uint>                - Format a range of this length (in bytes).`

The way I read this is that a piece of text that is equal to the number of bytes will be formatted.

I've counted the number of bytes for the first 2 lines (I know there is a `--lines` option, it's just an example):

- with `microsoft` style, only those 2 lines are formatted;
- with `gnu` and `mozilla` styles the whole function is formatted.

I can't figure it out. Styles have the same options, but use different values. 

Is this specific to the formatting options, or a `--length` behavior I don't fully understand?

```c
int get_number(
	int x, int y, int z)
{
	if (x > y) { return x + y + z; }
	else
	{
		return x - y - z;
	}
}

int main(void){
	return 0;
}
```

```bash
clang-format --version
# clang-format version 14.0.0

# Show the number of bytes for the first 2 lines
head -n 2 example.c | wc -c
# 38

# Microsoft style
clang-format --style=microsoft --length=38 example.c

# int get_number(int x, int y, int z)
# {
#    if (x > y) { return x + y + z; }
#	else
# 	{
# 		return x - y - z;
# 	}
# }

# int main(void){
# 	return 0;
# }

# GNU style
clang-format --style=gnu --length=38 example.c

# int
# get_number (int x, int y, int z)
# {
#   if (x > y)
#     {
#       return x + y + z;
#     }
#   else
#     {
#       return x - y - z;
#     }
# }

# int main(void){
# 	return 0;
# }

# Mozilla style
clang-format --style=mozilla --length=38 example.c

# int
# get_number(int x, int y, int z)
# {
#   if (x > y) {
#     return x + y + z;
#   } else {
#     return x - y - z;
#   }
# }

# int main(void){
# 	return 0;
# }
```

### PR DESCRIPTION
**Pull request by owenca**
Also validate the argument value.

Fixes #56245

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/tools/clang-format/ClangFormat.cpp [hunk 1]
```diff
@@ -296,12 +296,16 @@ static bool fillRanges(MemoryBuffer *Code,
...
+      return true;
+    }
     if (Offset + Length > CodeSize) {
       errs() << "error: invalid length " << Length << ", offset + length ("
-             << Offset + Length << ") is outside the file.\n";
+             << Offset + Length << ") is outside the file\n";
       return true;
     }
-    Ranges.push_back(tooling::Range(Offset, Length));
+    Ranges.push_back(tooling::Range(Offset, Length - 1));
```
Comment (kadircet) [inline clang/tools/clang-format/ClangFormat.cpp:308]: hi folks, we're seeing some regressions that's possibly related to this change (working on a repro right now). I am having a hard time following why this is the right thing to do. `tooling::Range` and command line flags are both (offset, length) pairs. `offset` is 0-based for both, and `length` is again coming from the same domain for both representations (in bytes).

moreover, we're only performing this mapping here, and not just couple of lines above (when we convert `--lines` to ranges.

I do agree that there's an off by one somewhere, but I think it's more likely to be in https://github.com/llvm/llvm-project/blob/main/clang/lib/Format/AffectedRangeManager.cpp#L61-L71.
Logic in there accepts two ranges `[B1, E1)` and `[B2, E2)` as intersecting when `E1==B2`, but those ranges are half open (as they're constructed from `offset + length` pairs).

Comment (owenca) [reply clang/tools/clang-format/ClangFormat.cpp:308]: > I do agree that there's an off by one somewhere, but I think it's more likely to be in https://github.com/llvm/llvm-project/blob/main/clang/lib/Format/AffectedRangeManager.cpp#L61-L71. Logic in there accepts two ranges `[B1, E1)` and `[B2, E2)` as intersecting when `E1==B2`, but those ranges are half open (as they're constructed from `offset + length` pairs).

I didn't fix it there because we would have to change all unit tests involving range formatting.

Comment (kadircet) [reply clang/tools/clang-format/ClangFormat.cpp:308]: > I didn't fix it there because we would have to change all unit tests involving range formatting.

sorry I am not sure how to respond to that. Can you elaborate why updating unittests, when we're supposed to be fixing a bug in a library used by many applications was deemed undesired?

IIUC, what you're saying is, you also think the actual issue is in the `Format` library, which is used by many other tools (clang-format, clangd, clang-tidy, include-cleaner, and many many more). All of which use `Ranges` as format library's contract declares, a 0-based offset and a length for number of bytes starting from that offset, possibly `0`. clang-format tool used to accept command line arguments exactly with the same contract, and now we're changing semantics here, at the cost of breaking existing workflows, and diverging from rest of the tools.

This discrepancy now requires ecosystem to use tools that embed format differently (e.g. when an editor is making a range-formatting request, it needs to provide different ranges if formatter is clangd vs clang-format ?). Moreover all the tests in [clang/unittests/Format/FormatTestSelective.cpp](https://github.com/llvm/llvm-project/blob/main/clang/unittests/Format/FormatTestSelective.cpp) are telling a similar story (`length=0` is heavily used, hence I am not sure why this is something we should `ban` with clang-format-21).

I don't understand how all of this is justified in order to not update some unittests. Maybe we can figure out a way to make this change less intrusive for unittests? There's a good chance we can both fix the issue, and keep the CLI interface the same by defining some semantics around ranges with `length=0`.

Comment (owenca) [reply clang/tools/clang-format/ClangFormat.cpp:308]: I really don't understand the rant. I didn't touch the off-by-1 bug (if it's indeed a bug) in `AffectedRangeManager.cpp` precisely because it would impact libFormat, which has been like this since its inception (f79351157959adde9a65d99075590a9db613a77b) 12+ years ago, and all range tests in FormatTests have been based on this semantics. If you (or anyone else) want to address it now, please open an issue and submit a pull request.

> hi folks, we're seeing some regressions that's possibly related to this change (working on a repro right now).

I'll look into this as soon as you have a repro.

Comment (kadircet) [reply clang/tools/clang-format/ClangFormat.cpp:308]: > I really don't understand the rant

Sorry for my tone, I didn't mean to create frustration. I was having a hard time understanding why updating unittests was deemed undesired but updating the driver to do the same, while still updating its tests that passed `-length=0`, was OK.

> I'll look into this as soon as you have a repro.

Unfortunately it's hard to describe a repro. Because the off-by-one issue underneath is hiding the `Length - 1` transformation here, especially when the final offset corresponds to `\n`. My real concern is about clang-format accepting and defining some behavior for `-length=0` before this patch and now rejecting such inputs with an hard error (rather than just ignoring such ranges).

I tried to summarize my concerns in https://github.com/llvm/llvm-project/issues/146036. Let's continue the discussion there, it isn't urgent though if you have other topics. I am happy to workaround on our side in the meanwhile.

---

All of this aside, I don't think I've mentioned this in our past encounters but I really appreciate all the work you're putting into clang-format and a huge thanks for being responsive&involved in these discussions.
