### PR TITLE
[lldb][LoongArch] Fix expression function call failure

### LINKED ISSUE #136561: [lldb][LoongArch] expression command cannot call the function
test commit: be48727b95bf9075e4290cc8938ab87db8b7410c
```
user@Debian-Sid:~/llvm-project/github-main/_build_lldb$ ./bin/lldb ./a.out 
(lldb) target create "./a.out"
Current executable set to '/home/user/llvm-project/github-main/_build_lldb/a.out' (loongarch64).
(lldb) b main
Breakpoint 1: where = a.out`main + 12 at test.c:6:10, address = 0x000000000000078c
(lldb) r
Process 430727 launched: '/home/user/llvm-project/github-main/_build_lldb/a.out' (loongarch64)
Process 430727 stopped
* thread #1, name = 'a.out', stop reason = breakpoint 1.1
    frame #0: 0x000055555555078c a.out`main at test.c:6:10
   3    }
   4   
   5    int main() {
-> 6      return 0;
   7    }
   8   
(lldb) list 1
   1    int add(int a, int b) {
   2      return a+b;
   3    }
   4   
   5    int main() {
   6      return 0;
   7    }
   8   
(lldb) expression add(2,3)
                  
error: Expression execution was interrupted: signal SIGBUS: illegal address.
The process has been returned to the state before expression evaluation.
(lldb)
```

### PR DESCRIPTION
**Pull request by wangleiat**
After upgrading the default code model from small to medium on
LoongArch, function calls using expression may fail. This is because the
function call instruction has changed from `bl` to `pcalau18i + jirl`,
but `RuntimeDyld` does not handle out-of-range jumps for this
instruction sequence.

This patch fixes: #136561

### CODE REVIEW

File: llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp [hunk 1]
```diff
@@ -662,7 +662,16 @@ bool RuntimeDyldELF::resolveLoongArch64ShortBranch(
...
+  // Normal call
+  if (RelI->getType() == ELF::R_LARCH_B26) {
+    if (!isInt<28>(Address + Value.Addend - SourceAddress))
+      return false;
+    resolveRelocation(Sections[SectionID], Offset, Address, RelI->getType(),
+                      Value.Addend);
+    return true;
+  }
+  // Medium call: R_LARCH_CALL36
+  if (!isInt<38>(Address + Value.Addend - SourceAddress))
```
Comment (SixWeining) [inline llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp:674]: The exact range should be `[PC-128GiB-0x20000, PC+128GiB-0x20000-4]`.

Comment (wangleiat) [reply llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp]: Thanks, done.

**Review by SixWeining — APPROVED** [review]
LGTM
