### PR TITLE
[Clang] fix false-positive lambda shadow diagnostics in explicit object member functions

### LINKED ISSUE #163731: [Clang] Lambda parameter shadowing a field while using explicit object parameter
```c++
struct Foo {
    int bar;

    void func(this Foo &self) {
        auto lambda = [](int bar) {
            return bar;
        };
    }
};
```
```c++
<source>:5:30: warning: declaration shadows a field of 'Foo' [-Wshadow-uncaptured-local]
    5 |         auto lambda = [](int bar) {
      |                              ^
<source>:2:9: note: previous declaration is here
    2 |     int bar;
      |         ^
```
https://godbolt.org/z/d7vjvP79q

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #163731

---

This PR addresses false-positive shadow diagnostics for lambdas inside explicit object member functions

```cpp
struct S {
  int x;
  void m(this S &self) {
    auto lambda = [](int x) { return x; }; // ok
  }
};
```

### CODE REVIEW

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -8640,6 +8640,11 @@ void Sema::DiagnoseShadowingLambdaDecls(const LambdaScopeInfo *LSI) {
             << Shadow.VD->getDeclName() << /*explicitly*/ 0;
       Diag(ShadowedDecl->getLocation(), diag::note_previous_declaration);
     } else if (isa<FieldDecl>(ShadowedDecl)) {
+      if (CXXMethodDecl *MD =
+              dyn_cast<CXXMethodDecl>(getFunctionLevelDeclContext()))
+        if (MD->isExplicitObjectMemberFunction())
+          continue;
```
Comment (zwuis) [inline clang/lib/Sema/SemaDecl.cpp]:
```cpp
if (auto *MD = dyn_cast<CXXMethodDecl>(getFunctionLevelDeclContext());
    MD && MD->isExplicitObjectMemberFunction())
  continue;
```

Can we check this earlier, before line 8558?

**Review by cor3ntin — APPROVED** [review]

**Review by zwuis — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM aside from a nit
