### PR TITLE
[clang][Sema] Add checks for validity of default ctor's class

### LINKED ISSUE #10518: clang++ segfaults on (incorrect) template code
|  |  |
| --- | --- |
| Bugzilla Link | [10146](https://llvm.org/bz10146) |
| Version | 2.9 |
| OS | Linux |
| Attachments | [Template classes causing clang++ segfault](https://user-images.githubusercontent.com/60944935/143743317-6ad14ed6-e91b-46d3-95b1-7b2cc7c764f5.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@DougGregor |

## Extended Description 

When compiling the attached code, by invoking:
```shell
clang++ test.cc
```
causes a segmentation fault in both version 2.8 as included with Ubuntu x86_64, as well as with the LLVM supplied 2.9 x86_64 and i686 versions.
```
Stack dump:
0.      Program arguments: /home/gertjan/tmp/clang/clang+llvm-2.9-x86_64-linux.tar/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test.cc -mrelocation-model static -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-linker-version 2.21.0.20110327 -momit-leaf-frame-pointer -resource-dir /home/gertjan/tmp/clang/clang+llvm-2.9-x86_64-linux.tar/bin/../lib/clang/2.9 -ferror-limit 19 -fmessage-length 80 -fcxx-exceptions -fexceptions -fgnu-runtime -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/cc-hc4Fnt.o -x c++ test.cc 
1.      test.cc:11:10: current parser token '{'
2.      test.cc:10:1: parsing struct/union/class body 'B'
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal 1 (use -v to see invocation)
```

### LINKED ISSUE #67914: Assertion in `clang::InitializationSequence::Perform`
The following crash is a byproduct of reduction of #45566 (https://godbolt.org/z/xKTYT1vxd):
```cpp
template < typename, int >
struct Mask;

template < int, class >
struct conditional {
  using type = Mask< int, 16 >;
};

template < class _Then >
struct conditional< 0, _Then > {
  using type = _Then;
};

template < int _Bp, class, class _Then >
using conditional_t = typename conditional< _Bp, _Then >::type;

template < typename, int >
struct Array;

template < typename, int, bool, typename >
struct StaticArrayImpl;

template < typename Value_, int Size_ >
struct Mask : StaticArrayImpl< Value_, Size_, 1, Mask< Value_, Size_ > > {
  template < typename T1 >
  Mask(T1) {}
};

template < typename T >
void load(typename T::MaskType mask) {
  T::load_(mask);
}

template < typename Value_, int IsMask_, typename Derived_ >
struct StaticArrayImpl< Value_, 32, IsMask_, Derived_ > {
  using Array1 = conditional_t< IsMask_, void, Array< Value_, 16 > >;
  
  template < typename Mask >
  static Derived_ load_(Mask mask) {
    return Derived_{load< Array1 >(mask.a1), Mask{}};
  }

  Array1 a1;
};

template < typename Derived_ >
struct KMaskBase;

template < typename Derived_ >
struct StaticArrayImpl< float, 16, 0, Derived_ > {
  template < typename Mask >
  static Derived_ load_(Mask mask);
};

template < typename Derived_ >
struct StaticArrayImpl< float, 16, 1, Mask< float, 16 > > : KMaskBase< Derived_ > {};

template < typename Derived_ >
struct StaticArrayImpl< int, 16, 1, Derived_ > {};

template < typename Value_, int Size_ >
struct Array : StaticArrayImpl< Value_, Size_, 0, Array< Value_, Size_ > > {
  using MaskType = Mask< Value_, Size_ >;
};

void test11_load_masked() {
  load< Array< float, 32 > >{} == 0;
}
```
Post-17 trunk crash:
```
<source>:56:8: error: partial specialization of 'StaticArrayImpl' does not use any of its template parameters
   56 | struct StaticArrayImpl< float, 16, 1, Mask< float, 16 > > : KMaskBase< Derived_ > {};
      |        ^
<source>:67:29: error: expected ';' after expression
   67 |   load< Array< float, 32 > >{} == 0;
      |                             ^
      |                             ;
<source>:67:32: error: expected expression
   67 |   load< Array< float, 32 > >{} == 0;
      |                                ^
<source>:67:3: warning: expression result unused [-Wunused-value]
   67 |   load< Array< float, 32 > >{} == 0;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:40:46: error: no matching constructor for initialization of 'Mask<float, 32>'
   40 |     return Derived_{load< Array1 >(mask.a1), Mask{}};
      |                                              ^   ~~
<source>:31:6: note: in instantiation of function template specialization 'StaticArrayImpl<float, 32, false, Array<float, 32>>::load_<Mask<float, 32>>' requested here
   31 |   T::load_(mask);
      |      ^
<source>:67:3: note: in instantiation of function template specialization 'load<Array<float, 32>>' requested here
   67 |   load< Array< float, 32 > >{} == 0;
      |   ^
<source>:26:3: note: candidate constructor template not viable: requires 1 argument, but 0 were provided
   26 |   Mask(T1) {}
      |   ^    ~~
<source>:24:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
   24 | struct Mask : StaticArrayImpl< Value_, Size_, 1, Mask< Value_, Size_ > > {
      |        ^~~~
<source>:24:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
   24 | struct Mask : StaticArrayImpl< Value_, Size_, 1, Mask< Value_, Size_ > > {
      |        ^~~~

clang++: /root/llvm-project/clang/lib/Sema/SemaInit.cpp:8617:
clang::ExprResult clang::InitializationSequence::Perform(clang::Sema&, const clang::InitializedEntity&, const clang::InitializationKind&, clang::MultiExprArg, clang::QualType*):
Assertion `Kind.getKind() == InitializationKind::IK_Copy || Kind.isExplicitCast() || Kind.getKind() == InitializationKind::IK_DirectList' failed.

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<eof> parser at end of file
2.	<source>:30:6: instantiating function definition 'load<Array<float, 32>>'
3.	<source>:39:19: instantiating function definition 'StaticArrayImpl<float, 32, false, Array<float, 32>>::load_<Mask<float, 32>>'
4.	<source>:26:3: instantiating function definition 'Mask<float, 16>::Mask<Mask<int, 16>>'
 #0 0x000000000370a448 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x370a448)
 #1 0x000000000370810c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x370810c)
 #2 0x0000000003650d78 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f6a4322d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f6a42cf000b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f6a42ccf859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f6a42ccf729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f6a42ce0fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00000000065b43d2 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b43d2)
 #9 0x00000000062527c4 BuildImplicitBaseInitializer(clang::Sema&, clang::CXXConstructorDecl*, ImplicitInitializerKind, clang::CXXBaseSpecifier*, bool, clang::CXXCtorInitializer*&) SemaDeclCXX.cpp:0:0
#10 0x000000000629fe84 clang::Sema::SetCtorInitializers(clang::CXXConstructorDecl*, bool, llvm::ArrayRef<clang::CXXCtorInitializer*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x629fe84)
#11 0x00000000062f06f7 clang::Sema::DefineImplicitDefaultConstructor(clang::SourceLocation, clang::CXXConstructorDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x62f06f7)
#12 0x0000000005fb30a1 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5fb30a1)
#13 0x000000000659f845 PerformConstructorInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::InitializationSequence::Step const&, bool&, bool, bool, clang::SourceLocation, clang::SourceLocation) SemaInit.cpp:0:0
#14 0x00000000065b344c clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b344c)
#15 0x00000000062527c4 BuildImplicitBaseInitializer(clang::Sema&, clang::CXXConstructorDecl*, ImplicitInitializerKind, clang::CXXBaseSpecifier*, bool, clang::CXXCtorInitializer*&) SemaDeclCXX.cpp:0:0
#16 0x000000000629fe84 clang::Sema::SetCtorInitializers(clang::CXXConstructorDecl*, bool, llvm::ArrayRef<clang::CXXCtorInitializer*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x629fe84)
#17 0x00000000062a65ce clang::Sema::ActOnMemInitializers(clang::Decl*, clang::SourceLocation, llvm::ArrayRef<clang::CXXCtorInitializer*>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x62a65ce)
#18 0x00000000069f7792 clang::Sema::InstantiateMemInitializers(clang::CXXConstructorDecl*, clang::CXXConstructorDecl const*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69f7792)
#19 0x00000000069fd8de clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fd8de)
#20 0x00000000069fbd4f clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fbd4f)
#21 0x00000000069fdbce clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fdbce)
#22 0x00000000069fbd4f clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fbd4f)
#23 0x00000000069fdbce clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fdbce)
#24 0x00000000069fbd4f clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69fbd4f)
#25 0x0000000005fd6b69 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#26 0x0000000005fd7342 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5fd7342)
#27 0x0000000005e6dae3 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e6dae3)
#28 0x0000000005e61cca clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e61cca)
#29 0x0000000004964be8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4964be8)
#30 0x00000000041ca839 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41ca839)
#31 0x000000000414be7e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x414be7e)
#32 0x00000000042a97ce clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42a97ce)
#33 0x0000000000bde956 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbde956)
#34 0x0000000000bd621a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#35 0x0000000003fa9a49 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#36 0x0000000003651224 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3651224)
#37 0x0000000003faa03f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#38 0x0000000003f72385 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f72385)
#39 0x0000000003f72ded clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f72ded)
#40 0x0000000003f7ad15 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f7ad15)
#41 0x0000000000bdbdfc clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbdbdfc)
#42 0x0000000000ad6491 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xad6491)
#43 0x00007f6a42cd1083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#44 0x0000000000bd5cfe _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbd5cfe)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

### LINKED ISSUE #78388: [Clang] crashes on invalid code
Input:
```
typedef mbstate_t;
  template < typename , typename , typename >
  class a
  class b {
    namespace {
    template < typename c > b::operator=() {
      struct :a< c, char, stdmbstate_t > d
```

Crashes when compiled with clang-trunk.

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<eof> parser at end of file
2.	<source>:5:5: parsing namespace '(anonymous)'
3.	<source>:6:44: parsing function body
4.	<source>:6:44: in compound statement ('{}')
 #0 0x0000000003563048 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3563048)
 #1 0x0000000003561194 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3561194)
 #2 0x00000000034af278 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f5cfba42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000000000635e3c1 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x635e3c1)
 #5 0x00000000060095f4 BuildImplicitBaseInitializer(clang::Sema&, clang::CXXConstructorDecl*, ImplicitInitializerKind, clang::CXXBaseSpecifier*, bool, clang::CXXCtorInitializer*&) SemaDeclCXX.cpp:0:0
 #6 0x000000000605016e clang::Sema::SetCtorInitializers(clang::CXXConstructorDecl*, bool, llvm::ArrayRef<clang::CXXCtorInitializer*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x605016e)
 #7 0x00000000060990fd clang::Sema::DefineImplicitDefaultConstructor(clang::SourceLocation, clang::CXXConstructorDecl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x60990fd)
 #8 0x0000000005d5b991 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5d5b991)
 #9 0x00000000063405ff PerformConstructorInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::InitializationSequence::Step const&, bool&, bool, bool, clang::SourceLocation, clang::SourceLocation) SemaInit.cpp:0:0
#10 0x000000000635fce0 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x635fce0)
#11 0x0000000005f71444 clang::Sema::ActOnUninitializedDecl(clang::Decl*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5f71444)
#12 0x0000000005c2a245 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c2a245)
#13 0x0000000005c3eff0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c3eff0)
#14 0x0000000005c403d2 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c403d2)
#15 0x0000000005c408df clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c408df)
#16 0x0000000005cee384 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5cee384)
#17 0x0000000005cef0f8 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5cef0f8)
#18 0x0000000005cefef9 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5cefef9)
#19 0x0000000005cf0a6a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5cf0a6a)
#20 0x0000000005c05d48 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c05d48)
#21 0x0000000005d0cb07 clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5d0cb07)
#22 0x0000000005d1453a clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5d1453a)
#23 0x0000000005d147e3 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5d147e3)
#24 0x0000000005c40a60 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c40a60)
#25 0x0000000005c08297 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c08297)
#26 0x0000000005c57324 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c57324)
#27 0x0000000005c5c3d9 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c5c3d9)
#28 0x0000000005c40ab2 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c40ab2)
#29 0x0000000005c08297 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c08297)
#30 0x0000000005c09de7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c09de7)
#31 0x0000000005bf93ca clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5bf93ca)
#32 0x0000000003d9e2e5 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3d9e2e5)
#33 0x0000000004024e21 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4024e21)
#34 0x0000000003fa218b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3fa218b)
#35 0x00000000041046f3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x41046f3)
#36 0x0000000000c192c6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc192c6)
#37 0x0000000000c11cdd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#38 0x0000000003de52b9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#39 0x00000000034af6a3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x34af6a3)
#40 0x0000000003de54d9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#41 0x0000000003dad8d7 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dad8d7)
#42 0x0000000003dae28d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dae28d)
#43 0x0000000003db7fdc clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3db7fdc)
#44 0x0000000000c16601 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc16601)
#45 0x0000000000b0f494 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xb0f494)
#46 0x00007f5cfba29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#47 0x00007f5cfba29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#48 0x0000000000c114de _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc114de)
```
godbolt: https://godbolt.org/z/K9jMo3c3x

### PR DESCRIPTION
**Pull request by Endilll**
Fixes #10518
Fixes #67914
Fixes #78388
Also addresses the second example in #49103

This patch is based on suggestion from @cor3ntin in https://github.com/llvm/llvm-project/issues/67914#issuecomment-1896011898

### CODE REVIEW

**Comment by Endilll** [comment]
I decided to not include tests, because our testing infrastructure is not ready to test that Clang doesn't crash without overspecifying the tests using `-verify` mode.

**Comment by Fznamznon** [comment]
> I decided to not include tests, because our testing infrastructure is not ready to test that Clang doesn't crash without overspecifying the tests using `-verify` mode.

Could you elaborate a bit more on that? What is the exact problem with the testing infrastructure? Can we just add a separate test with the cases from the issues, perhaps without `-verify` at all?

**Comment by Endilll** [comment]
> Could you elaborate a bit more on that? What is the exact problem with the testing infrastructure? Can we just add a separate test with the cases from the issues, perhaps without -verify at all?

1) I think that the most reliable way to detect a crash would be to leverage our existing machinery for that inside Clang and its driver. Result this machinery produces is exit code.
2) We should keep in mind that on top of assertion failures, we also have segmentation faults.
3) Stack traces are also not a given, as can be seen in https://godbolt.org/z/cf7ovjrq3 (#31936)

4) Unfortunately, our exit code in case of crash is not consistent. On Linux, both driver and frontend return `143`. On Windows, frontend returns `-1073741819` (which is `0xc0000005`), which is converted to `1` by driver. The same `1` is used for regular failures due to errors.

5) From what I was able to find, `lit` can only check whether exit code is zero or non-zero (via `not`). `not` has `not --crash` mode that can also be leveraged.
6) This is not helped by the fact that by default piping (to e.g. `FileCheck`) ignores crashes. `lit` is following shell behavior here, but thankfully has `pipefail` option in `lit.cfg` that can help.

While I think it's possible to craft a general solution out of what we have today, it seems too brittle and intricate. It's also possible to use a simpler solution that works only for e.g. assertion failures. I don't think either of the above are good options, especially when considered at scale. While it's a discussion for another day, we have hundreds (of not thousands) of regression test cases in our bug tracker labeled `crash`, `crash-on-valid`, and `crash-on-invalid`. Some of them have been long gone, but resurfaced during the last 2 years. So I'm not interested in a limited one-off solution just for this PR.

Ideal solution seems to be along the following lines:
1) Make frontend consistently return e.g. `143` on all platforms in case of crash.
2) Make `lit` capable of checking specific exit code.

**Comment by Fznamznon** [comment]
So, there is no way to consistently check on all platforms that we didn't crash when an error diagnostic was issued (does clang return non-zero when there is error diagnostic?), is that a right understanding?
Still, if the tests won't be "pretty" that is not an excuse to not add tests, IMO.

**Comment by Endilll** [comment]
> So, there is no way to consistently check on all platforms that we didn't crash when an error diagnostic was issued (does clang return non-zero when there is error diagnostic?), is that a right understanding?

Yes. On Linux and Windows `1` is returned if error diagnostic was issued.

> Still, if the tests won't be "pretty" that is not an excuse to not add tests, IMO.

I tried my best to explain that it's not an issues of prettiness. Complicated solution that _seems_ to be possible to craft today feels too brittle, requiring reader to understand how various parts are fit together, not to say I'm not sure myself if something won't slip between piping behavior, `not`, `not --crash`, `FileCheck`, and varied platforms.

If you can point me to existing corpus of crash tests that are done correctly, I'll be happy to follow. So far I saw handful of crash tests here and there across out test suite of various quality: from tests that do not account for segmentation faults (https://github.com/llvm/llvm-project/blob/88d1de5ec64210686d93a90529583505635d257d/clang/test/Parser/objc-diag-width.mm is going to fire in this case even though it's not intended to) to borderline useless tests (https://github.com/llvm/llvm-project/blob/60963272c5c83890910fd97f8d941180b6006fca/clang/test/Sema/crash-deduction-guide-access.cpp is going to pass if clang crashes or error diagnostic is produced, because in both cases exit code is not zero).

**Comment by Fznamznon** [comment]
> I tried my best to explain that it's not an issues of prettiness.

Well, ok, perhaps checking that there is actually no crash in clang can be tricky. But what I meant is, since there is no good way to check exit code, why can't we add `-verify` test? Yes, it will be checking errors that the patch didn't touch, but it is what mostly people do when adding clang tests and it will be +N test cases in a regular test base which not only ensure your change is correct, but the future ones too.

**Comment by Endilll** [comment]
> why can't we add -verify test? Yes, it will be checking errors that the patch didn't touch, but it is what mostly people do when adding clang tests and it will be +N test cases in a regular test base which not only ensure your change is correct, but the future ones too.

Because we [have](https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted+label%3Acrash%2Ccrash-on-valid%2Ccrash-on-invalid+label%3Aclang%3Afrontend%2Cclang%3Acodegen%2Cclang%3Adiagnostics%2Cclang%3APCH%2Cclang%3Aheaders+-label%3Aduplicate%2Cinvalid%2Cincomplete%2Cwontfix%2Cworksforme) more than a couple of tests that should ensure we don't crash. Many of them don't make much sense, e.g. automatically reduced ones (even if identifiers are kept intact; #67914 is not a bad example). Which makes it harder for people altering diagnostic behavior to reason about such tests when they fail to pass CI. It also makes contributors to have more "fun" like @AaronBallman [had](https://github.com/llvm/llvm-project/commit/84a3aadf0f2483dde0acfc4e79f2a075a5f35bd1) no so long ago, updating tons of tests because of his VLA-related change.

Overspecifying a significant corpus of hard-to-reason-about tests leads us to a slippery slope of a applying changes blindly and developing scripts akin to `update_cc_test_checks.py`. I see a significant amount of harm in this direction.

**Comment by Fznamznon** [comment]
> Because we [have](https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted+label%3Acrash%2Ccrash-on-valid%2Ccrash-on-invalid+label%3Aclang%3Afrontend%2Cclang%3Acodegen%2Cclang%3Adiagnostics%2Cclang%3APCH%2Cclang%3Aheaders+-label%3Aduplicate%2Cinvalid%2Cincomplete%2Cwontfix%2Cworksforme) more than a couple of tests that should ensure we don't crash.

Now imagine all these come in without tests because there is no good way to add a test.

Again, not having a good way to make a test shouldn't free people from adding tests.

> It also makes contributors to have more "fun" like @AaronBallman [had](https://github.com/llvm/llvm-project/commit/84a3aadf0f2483dde0acfc4e79f2a075a5f35bd1) no so long ago, updating tons of tests because of his VLA-related change.

I would rather say it is a specific example. VLAs are an extension in C++ for which we choose how to deal with it. Most of the incoming changes are supported by the standards, so we shouldn't ideally expect many drastic changes in diagnostics like this one.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -5990,6 +5990,10 @@ void Sema::ActOnDefaultCtorInitializers(Decl *CDtorDecl) {
 
   if (CXXConstructorDecl *Constructor
       = dyn_cast<CXXConstructorDecl>(CDtorDecl)) {
+    if (CXXRecordDecl *ClassDecl = Constructor->getParent();
+        !ClassDecl || ClassDecl->isInvalidDecl()) {
+      return;
+    }
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5996]:
```suggestion
    if (CXXRecordDecl *ClassDecl = Constructor->getParent();
        !ClassDecl || ClassDecl->isInvalidDecl())
      return;
```

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 2]
```diff
@@ -14030,6 +14034,9 @@ void Sema::DefineImplicitDefaultConstructor(SourceLocation CurrentLocation,
 
   CXXRecordDecl *ClassDecl = Constructor->getParent();
   assert(ClassDecl && "DefineImplicitDefaultConstructor - invalid constructor");
+  if (ClassDecl->isInvalidDecl()) {
+    return;
+  }
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:14039]:
```suggestion
  if (ClassDecl->isInvalidDecl())
    return;
```

**Review by AaronBallman — COMMENTED** [review]
Yeah, these changes really need to come with test coverage. We allow landing changes with no test coverage when it's an NFC change or when the testing would require heroic efforts. Otherwise, we expect tests that are as good as you can reasonably make them (sometimes that means going with a unit test instead of a lit test, sometimes it requires creativity in lit, etc). You don't have to fix the testing system first, it's okay to land tests in an unideal state with a FIXME comment, for example.

In terms of the code changes, they look mostly reasonable (some minor nits for coding style conformance) and should be something we can test. We used to crash, so the test is demonstrating that we no longer crash (and that means verifying some particular set of diagnostics are now generated instead or that some IR is now generated, etc). Such a test would be good to have a comment explaining that the code used to crash with a mention or link to the github issue(s).

**Comment by Endilll** [comment]
So my takeaways here are:
1. Tests that ensure we don't crash anymore are important for us.
2. `-verify` is an acceptable way to write such tests.

Is this correct?

**Comment by AaronBallman** [comment]
> So my takeaways here are:
> 
>     1. Tests that ensure we don't crash anymore are important for us.
> 
>     2. `-verify` is an acceptable way to write such tests.
> 
> 
> Is this correct?

Yup, that's it exactly!

**Review by cor3ntin — APPROVED** [review]

File: clang/test/SemaCXX/crash-GH10518.cpp [hunk 3]
```diff
@@ -0,0 +1,22 @@
+// RUN: %clang_cc1 -verify -std=c++98 %s
+// RUN: %clang_cc1 -verify -std=c++11 %s
+// RUN: %clang_cc1 -verify -std=c++14 %s
+// RUN: %clang_cc1 -verify -std=c++17 %s
+// RUN: %clang_cc1 -verify -std=c++20 %s
+// RUN: %clang_cc1 -verify -std=c++23 %s
+// RUN: %clang_cc1 -verify -std=c++2c %s
```
[the remark this answers is not in the document]
Comment (Endilll) [reply clang/test/SemaCXX/crash-GH10518.cpp:7]: Since newer language modes do not necessarily subsume older ones (think dynamic exception specification), and have disabled code paths, I'm not sure we want to be smart about which language modes to test. If we're going to be smart, then yes, 98, 11, and 2c sounds like a good compromise.

**Review by philnik777 — APPROVED** [review]
The libc++ changes LGTM.
