### PR TITLE
[clang][diagnostics] Fix fix-it hint parenthesis placement for fold expressions

### LINKED ISSUE #151787: [clang] Hints for `fold_expression_bad_operand` insert parentheses at incorrect location
```cpp
template<int... args>
int foo() {
    return (args + 1 + ...);
}

```

### Actual behaviour:
The right parenthesis is inserted before `1`
```
/tmp/test.cpp:3:18: error: expression not permitted as operand
      of fold expression
    3 |     return (args + 1 + ...);
      |             ~~~~~^~~
      |             (      )
1 error generated.

-->
return ((args + )1 + ...);
```

### Expected behaviour:
The right parenthesis should be inserted after `1`
```
/tmp/test.cpp:3:18: error: expression not permitted as operand
      of fold expression
    3 |     return (args + 1 + ...);
      |             ~~~~~^~~
      |             (       )
1 error generated.

-->
return ((args + 1) + ...);
```

### PR DESCRIPTION
**Pull request by el-ev**
- Closes #151787

Insert the right parenthesis one token later to correctly enclose the expression.

### CODE REVIEW

File: clang/test/FixIt/fixit-c++17.cpp [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// RUN: %clang_cc1 -verify -std=c++17 -pedantic-errors %s
+// RUN: cp %s %t
+// RUN: not %clang_cc1 -x c++ -std=c++17 -fixit %t
+// RUN: %clang_cc1 -Wall -pedantic-errors -x c++ -std=c++17 %t
+
+/* This is a test of the various code modification hints that only
+   apply in C++17. */
+template<int... args>
+int foo() {
+    return (args + 1 + ...); // expected-error {{expression not permitted as operand of fold expression}}
```
Comment (zwuis) [inline clang/test/FixIt/fixit-c++17.cpp:10]: Can you add these test cases?
```cpp
(args + 123 + ...); // long number
(... + args + 1); // left fold
```

Comment (el-ev) [reply clang/test/FixIt/fixit-c++17.cpp]: Thank you, the patch indeed did not work correctly for the long number. I've updated the code and included test cases for other kinds of fold expressions.

**Review by zwuis — COMMENTED** [review]
LGTM but please let other people take a look.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -123,6 +123,8 @@ Improvements to Clang's diagnostics
   Moved the warning for a missing (though implied) attribute on a redeclaration into this group.
   Added a new warning in this group for the case where the attribute is missing/implicit on
   an override of a virtual method.
+- Fixed fix-it hint for fold expressions. Clang now correctly places the suggested right 
+  parenthesis when diagnosing malformed fold expressions.
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:127]:
```suggestion
- Fixed fix-it hint for fold expressions. Clang now correctly places the suggested right 
  parenthesis when diagnosing malformed fold expressions. (#GH151787)
```

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit
