### PR TITLE
[analyzer] Fix false positive for stack-addr leak on simple param ptr

### LINKED ISSUE #106834: `clang-analyzer-core.StackAddressEscape` false-positive
https://godbolt.org/z/Yqr53rz4s

```cpp
extern void copy(char *output, const char *input, unsigned size);
extern bool foo(const char *input);
extern void bar(char *output, unsigned count);
extern bool baz(char *output, const char *input);

void repo(const char *input, char *output) {
    char temp[64];
    copy(temp, input, sizeof(temp));

    char result[64];
    input = temp;
    if (foo(temp)) {
        bar(result, sizeof(result));
        input = result;
    }
    if (!baz(output, input)) {
        copy(output, input, sizeof(result));
    }
}
```

```
<source>:16:5: warning: Address of stack memory associated with local variable 'temp' is still referred to by the caller variable 'input' upon returning to the caller.  This will be a dangling reference [clang-analyzer-core.StackAddressEscape]
    7 |     char temp[64];
      |     ~~~~~~~~~~~~~
    8 |     copy(temp, input, sizeof(temp));
    9 | 
   10 |     char result[64];
   11 |     input = temp;
   12 |     if (foo(temp)) {
   13 |         bar(result, sizeof(result));
   14 |         input = result;
   15 |     }
   16 |     if (!baz(output, input)) {
      |     ^
[<source>:12:9: note: Assuming the condition is false](javascript:;)
   12 |     if (foo(temp)) {
      |         ^~~~~~~~~
[<source>:12:5: note: Taking false branch](javascript:;)
   12 |     if (foo(temp)) {
      |     ^
[<source>:16:9: note: Assuming the condition is false](javascript:;)
   16 |     if (!baz(output, input)) {
      |         ^~~~~~~~~~~~~~~~~~~
[<source>:16:5: note: Taking false branch](javascript:;)
   16 |     if (!baz(output, input)) {
      |     ^
<source>:16:5: note: Address of stack memory associated with local variable 'temp' is still referred to by the caller variable 'input' upon returning to the caller.  This will be a dangling reference
    7 |     char temp[64];
      |     ~~~~~~~~~~~~~
    8 |     copy(temp, input, sizeof(temp));
    9 | 
   10 |     char result[64];
   11 |     input = temp;
   12 |     if (foo(temp)) {
   13 |         bar(result, sizeof(result));
   14 |         input = result;
   15 |     }
   16 |     if (!baz(output, input)) {
      |     ^
1 warning generated.
```

### PR DESCRIPTION
**Pull request by necto**
Assigning to a pointer parameter does not leak the stack address because it stays within the function and is not shared with the caller.

Previous implementation reported any association of a pointer parameter with a local address, which is too broad.

This fix enforces that the pointer to a stack variable is related by at least one level of indirection.

CPP-5642

Fixes #106834

### CODE REVIEW

File: clang/test/Analysis/stack-addr-ps.cpp [hunk 1]
```diff
@@ -791,3 +791,30 @@ void global_ptr_to_ptr() {
   *global_pp = nullptr;
 }
 } // namespace leaking_via_indirect_global_invalidated
+
+namespace not_leaking_via_simple_ptr {
+void top(const char *p) {
```
Comment (steakhal) [inline clang/test/Analysis/stack-addr-ps.cpp:796]: Please add a ref case too.
And also one for taking a struct by value and having this pointer as a member, and a similar with ref.

**Review by steakhal — CHANGES_REQUESTED** [review]

File: clang/test/Analysis/stack-addr-ps.cpp (hunk 1 above)
Comment (necto) [reply clang/test/Analysis/stack-addr-ps.cpp]: I am not sure what you are referring to by the "ref case". There is already `param_ref_to_struct_with_ptr_top` and `param_ref_to_ptr_top`.
I added other cases in 8a9a76a3d1b1

File: clang/test/Analysis/stack-addr-ps.cpp [hunk 2]
```diff
@@ -791,3 +791,58 @@ void global_ptr_to_ptr() {
...
+  p = &tmp; // no-warning
+}
+
+void ref_ptr(const char *&p) {
+  char tmp;
+  p = &tmp; // expected-warning{{variable 'tmp' is still referred to by the caller variable 'p'}}
+}
+
+struct S {
+  const char *p;
```
Comment (steakhal) [inline clang/test/Analysis/stack-addr-ps.cpp:807]: How about taking one struct by value holding encapsulating a reference member refering to a stack variable?

**Review by steakhal — APPROVED** [review]
You nailed the tests. You inspired one more test, and that's it I think.

Once you added that, lets merge this.

File: clang/test/Analysis/stack-addr-ps.cpp (hunk 2 above)
Comment (necto) [reply clang/test/Analysis/stack-addr-ps.cpp:807]: I do not understand what you mean.

My best interpretation
```C++
struct Ref {
  char &p;
};
void struct_ref(Ref s) {
  char tmp;
  s = {tmp}; // no-warning
}
```
does not compile

Comment (steakhal) [reply clang/test/Analysis/stack-addr-ps.cpp:807]: Ah, yes. Makes sense! All good then.
