### PR TITLE
[clang-doc] fix flaky test in clang-doc

### LINKED ISSUE #97507: Test clang-tools-extra/test/clang-doc/basic-project.test failing when built using non-ninja generator
We have an internal job which attempts to build the LLVM tree using the Visual Studio 2019 builder configuration (non-ninja) and it recently started hitting a test failure of clang-tools-extra/test/clang-doc/basic-project.test which I bisected back to when f14ad74478494cbd9d23af841d6f6b2808afda71 (#96358) was committed. The problem is that the change hard-codes how to find the dependent assets as `../share/clang-doc`. This is fine in ninja builds, but fails with the Visual Studio generator because the configuration name is part of the path.

For example, in a ninja build, the value of AssetsPath is (correctly) `C:\Dev\git\merge\build\bin\..\share\clang-doc\index.js`. But when using a Visual Studio generator, the value of AssetsPath is now `C:\Dev\git\merge\build\Debug\bin\..\share\clang-doc\index.js` which refers to a non-existent directory. In this particular case, it requires an extra `..` in the path to find the expected directory.

Lit test output:
```
FAIL: Clang Tools :: clang-doc/basic-project.test (1 of 1)
******************** TEST 'Clang Tools :: clang-doc/basic-project.test' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 1
rm -rf C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp && mkdir -p C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/docs C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/build
# executed command: rm -rf 'C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp'
# executed command: mkdir -p 'C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/docs' 'C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/build'
# RUN: at line 2
sed 's|$test_dir|C:/Dev/git/merge/clang-tools-extra/test/clang-doc|g' C:\Dev\git\merge\clang-tools-extra\test\clang-doc/Inputs/basic-project/database_template.json > C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/build/compile_commands.json
# executed command: sed 's|$test_dir|C:/Dev/git/merge/clang-tools-extra/test/clang-doc|g' 'C:\Dev\git\merge\clang-tools-extra\test\clang-doc/Inputs/basic-project/database_template.json'
# RUN: at line 3
clang-doc --format=html --output=C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/docs --executor=all-TUs C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/build/compile_commands.json
# executed command: clang-doc --format=html '--output=C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/docs' --executor=all-TUs 'C:\Dev\git\merge\build\tools\clang\tools\extra\test\clang-doc\Output\basic-project.test.tmp/build/compile_commands.json'
# .---command stdout------------
# | Emiting docs in html format.
# `-----------------------------
# .---command stderr------------
# | default index.js file missing at C:\Dev\git\merge\build\Debug\bin\..\share\clang-doc\index.js
# |
# `-----------------------------
# error: command failed with exit status: 1
```

### PR DESCRIPTION
**Pull request by PeterChou1**
Fixes https://github.com/llvm/llvm-project/issues/97507

#96809 introduce non-determinstic behaviour in clang-doc which caused the output to be randomly ordered which lead to randomly failing test. This patch modify clang-doc to behave deterministically again by sorting the output by location or USR.

### CODE REVIEW

**Comment by ilovepi** [comment]
This isn't fixing anything. Its re-enabling it. I'd also suggest adding people from that bug as reviewers to help you get this re-enabled.

**Comment by PeterChou1** [comment]
> This isn't fixing anything. Its re-enabling it. I'd also suggest adding people from that bug as reviewers to help you get this re-enabled.

This was just meant as an experiment to check what was failing in the CI pipeline

File: clang-tools-extra/clang-doc/Representation.cpp [hunk 1]
```diff
@@ -384,5 +384,12 @@ ClangDocContext::ClangDocContext(tooling::ExecutionContext *ECtx,
   }
 }
 
+void ScopeChildren::sort() {
+  std::sort(Namespaces.begin(), Namespaces.end());
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/Representation.cpp:388]: Prefer llvm::sort. https://llvm.org/docs/CodingStandards.html#beware-of-non-deterministic-sorting-order-of-equal-elements

File: clang-tools-extra/clang-doc/Representation.h [hunk 2]
```diff
@@ -104,6 +104,9 @@ struct Reference {
 
   bool mergeable(const Reference &Other);
   void merge(Reference &&I);
+  bool operator<(const Reference &Other) const {
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/Representation.h:107]: How stable are usrs? Perhaps we should be sorting on another property?

Comment (ilovepi) [reply clang-tools-extra/clang-doc/Representation.h:107]: My concern here is that we probably want clang-doc to output to be ordered consistently. While sorting by USRs may make it deterministic, it’s also likely that they won’t be ordered similarly run to run. For instance, I’d expect public class fields to be sorted by name.

Comment (PeterChou1) [reply clang-tools-extra/clang-doc/Representation.h:107]: the main reason I used USR was because it was unique to every declaration std sort wouldn't deal with equal elements, but it seems from the doc llvm:;sort already deterministically sort equal elements So I changed it to sort by name

**Comment by ilovepi** [comment]
In the description, its probably better to use the `#<PR number>` notation than linkify `PR`. Most of us will only see the raw text in the commit message, and while a full link is appreciated, it would be good to know the PR number at a glance.

File: clang-tools-extra/clang-doc/Representation.h [hunk 3]
```diff
@@ -312,6 +317,16 @@ struct SymbolInfo : public Info {
...
   llvm::SmallVector<Location, 2> Loc; // Locations where this decl is declared.
+
+  bool operator<(const SymbolInfo &Other) const {
+    if (DefLoc && Other.DefLoc) {
+      return *DefLoc < *Other.DefLoc;
+    }
+    if (Loc.size() > 0 && Other.Loc.size() > 0) {
+      return Loc[0] < Other.Loc[0];
+    }
+    return extractName() < Other.extractName();
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/Representation.h:328]: Looking at the overall comparison, you could probably use `std::tuple` to make the logic simpler. The optional value may make that harder though, as I don't recall offhand how that's normally handled.

File: clang-tools-extra/clang-doc/Representation.h [hunk 4]
```diff
@@ -270,10 +273,12 @@ struct Info {
 
   virtual ~Info() = default;
 
+  Info &operator=(Info &&Other) = default;
+
   SymbolID USR =
       SymbolID(); // Unique identifier for the decl described by this Info.
-  const InfoType IT = InfoType::IT_default; // InfoType of this particular Info.
```
[the remark this answers is not in the document]
Comment (PeterChou1) [reply clang-tools-extra/clang-doc/Representation.h:275]: The const implicitly deleted the move assignment operator which I need to sort Info vectors so I had to remove it

File: clang-tools-extra/clang-doc/tool/ClangDocMain.cpp [hunk 5]
```diff
@@ -205,6 +205,22 @@ llvm::Error getHtmlAssetFiles(const char *Argv0,
   return getDefaultAssetFiles(Argv0, CDCtx);
 }
 
+/// Make the output of clang-doc deterministic by sorting the children of
+/// namespaces and records.
+void sortUsrToInfo(llvm::StringMap<std::unique_ptr<doc::Info>> &USRToInfo) {
+  for (auto &I : USRToInfo) {
```
[the remark this answers is not in the document]
Comment (PeterChou1) [reply clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:211]: No since we only USRToInfo is generated on a per file basis so there's no need to sort it

[the remark this answers is not in the document]
Comment (ilovepi) [reply clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:211]: That doesn't necessarily rule out its own iteration order affecting the output.

File: clang-tools-extra/clang-doc/Representation.h [hunk 6]
```diff
@@ -312,6 +317,16 @@ struct SymbolInfo : public Info {
 
   std::optional<Location> DefLoc;     // Location where this decl is defined.
   llvm::SmallVector<Location, 2> Loc; // Locations where this decl is declared.
+
+  bool operator<(const SymbolInfo &Other) const {
+    if (DefLoc && Other.DefLoc) {
+      return *DefLoc < *Other.DefLoc;
```
[the remark this answers is not in the document]
Comment (PeterChou1) [reply clang-tools-extra/clang-doc/Representation.h]: I've updated the code so that if they are equal we just fallback to comparing names

File: clang-tools-extra/clang-doc/Representation.h (hunk 3 above)
Comment (ilovepi) [reply clang-tools-extra/clang-doc/Representation.h:337]: https://en.cppreference.com/w/cpp/utility/tuple/operator_cmp

File: clang-tools-extra/clang-doc/tool/ClangDocMain.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (PeterChou1) [reply clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:211]: How so? StringMap iteration order is not guaranteed to be deterministic and I don't think it was affecting the test before

**Review by ilovepi — APPROVED** [review]
LGTM, but test locally w/ LLVM_ENABLE_EXPENSIVE_CHECKS=On https://llvm.org/docs/CMake.html. If that passes, then go ahead and land this, since I think the nondeterminism in output order will be accounted for.
