### PR TITLE
[LV] Simplify and unify resume value handling for epilogue vec.

### LINKED ISSUE #179407: Assertion `Val && "isa<> used on a null pointer"' failed.
To reproduce run opt with the test below (-passes=loop-vectorize):
```
; ModuleID = './reduced.ll'
source_filename = "./reduced.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128-ni:1-p2:32:8:8:32-ni:2"
target triple = "x86_64-unknown-linux-gnu"

define void @wombat(i64 %arg) #0 gc "statepoint-example" {
bb:
  br label %bb1

bb1:                                              ; preds = %bb1, %bb
  %phi = phi i64 [ 0, %bb ], [ %add, %bb1 ]
  %phi2 = phi i32 [ 0, %bb ], [ %or, %bb1 ]
  %phi3 = phi i32 [ 0, %bb ], [ %select, %bb1 ]
  %icmp = icmp eq i32 0, 0
  %select = select i1 %icmp, i32 0, i32 %phi3
  %or = or i32 %phi2, 0
  %add = add i64 %phi, 1
  %icmp4 = icmp ult i64 %phi, %arg
  br i1 %icmp4, label %bb1, label %bb5

bb5:                                              ; preds = %bb1
  %phi6 = phi i32 [ %select, %bb1 ]
  %phi7 = phi i32 [ %or, %bb1 ]
  ret void
}

attributes #0 = { "target-features"="+prfchw,-cldemote,+avx,+aes,+sahf,+pclmul,-xop,+crc32,-amx-fp8,+xsaves,-avx512fp16,-usermsr,-sm4,-egpr,+sse4.1,-avx10.1,-avx512ifma,+xsave,+sse4.2,-tsxldtrk,-sm3,-ptwrite,-widekl,-movrs,+invpcid,+64bit,+xsavec,-avx512vpopcntdq,+cmov,-avx512vp2intersect,+avx512cd,+movbe,-avxvnniint8,-ccmp,-amx-int8,-kl,-sha512,-avxvnni,+rtm,+adx,+avx2,-hreset,-movdiri,-serialize,-vpclmulqdq,+avx512vl,-uintr,-cf,+clflushopt,-raoint,-cmpccxadd,+bmi,-amx-tile,+sse,-gfni,-avxvnniint16,-amx-fp16,-zu,-ndd,+xsaveopt,+rdrnd,+avx512f,-amx-bf16,-avx512bf16,-avx512vnni,-push2pop2,+cx8,+avx512bw,+sse3,+pku,-nf,-amx-tf32,-amx-avx512,+fsgsbase,-clzero,-mwaitx,-lwp,+lzcnt,-sha,-movdir64b,-ppx,-wbnoinvd,-enqcmd,-avxneconvert,-tbm,-pconfig,-amx-complex,+ssse3,+cx16,-avx10.2,+bmi2,+fma,+popcnt,-avxifma,+f16c,-avx512bitalg,-rdpru,+clwb,+mmx,+sse2,+rdseed,-avx512vbmi2,-prefetchi,-amx-movrs,-rdpid,-fma4,-avx512vbmi,-shstk,-vaes,-waitpkg,-sgx,+fxsr,+avx512dq,-sse4a,-avx512f" }
```
Reproducer: https://godbolt.org/z/Tq93jjPdz

Stack dump:
```
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -passes=loop-vectorize <source>
1.	Running pass "function(loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>)" on module "<source>"
2.	Running pass "loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>" on function "wombat"
 #0 0x0000000005ae1818 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x5ae1818)
 #1 0x0000000005ade6f4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000074f27e242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000074f27e2969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x000074f27e242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x000074f27e2287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x000074f27e22871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x000074f27e239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x0000000003721ac3 (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x3721ac3)
 #9 0x0000000003770db6 connectEpilogueVectorLoop(llvm::VPlan&, llvm::Loop*, llvm::EpilogueLoopVectorizationInfo&, llvm::DominatorTree*, llvm::LoopVectorizationLegality&, llvm::DenseMap<llvm::SCEV const*, llvm::Value*, llvm::DenseMapInfo<llvm::SCEV const*, void>, llvm::detail::DenseMapPair<llvm::SCEV const*, llvm::Value*>>&, (anonymous namespace)::GeneratedRTChecks&, llvm::ArrayRef<llvm::Instruction*>) LoopVectorize.cpp:0:0
#10 0x000000000377c300 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x377c300)
#11 0x000000000377d1e0 llvm::LoopVectorizePass::runImpl(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x377d1e0)
#12 0x000000000377d96d llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x377d96d)
#13 0x000000000305170e llvm::detail::PassModel<llvm::Function, llvm::LoopVectorizePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x305170e)
#14 0x00000000058521d1 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x58521d1)
#15 0x0000000000f0be3e llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xf0be3e)
#16 0x000000000585078a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x585078a)
#17 0x000000000096703e llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x96703e)
#18 0x0000000005850141 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x5850141)
#19 0x00000000009711fa llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x9711fa)
#20 0x00000000009652a8 optMain (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x9652a8)
#21 0x000074f27e229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#22 0x000074f27e229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#23 0x000000000095bf25 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x95bf25)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by fhahn**
This patch tries to drastically simplify resume value handling for the scalar loop when vectorizing the epilogue.

It uses a simpler, uniform approach for updating all resume values in the scalar loop:

1. Create ResumeForEpilogue recipes for all scalar resume phis in the main loop (the epilogue plan will have exactly the same scalar resume phis, in exactly the same order)
2. Update ::execute for ResumeForEpilogue to set the underlying value when executing. This is not super clean, but allows easy lookup of the generated IR value when we update the resume phis in the epilogue. Once we connect the 2 plans together explicitly, this can be removed.
3. Use the list of ResumeForEpilogue VPInstructions from the main loop to update the resume/bypass values from the epilogue.

This simplifies the code quite a bit, makes it more robust (should fix https://github.com/llvm/llvm-project/issues/179407) and also fixes a mis-compile in the existing tests (see change in llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce-sub-epilogue-vec.ll, where previously we would incorrectly resume using the start value when the epilogue iteration check failed)

In some cases, we get simpler code, due to additional CSE, in some cases the induction end value computations get moved from the epilogue iteration check to the vector preheader. We could try to sink the instructions as cleanup, but it is probably not worth the trouble.

Fixes https://github.com/llvm/llvm-project/issues/179407.

### CODE REVIEW

**Review by artagnon — COMMENTED** [review]
Hm, forgot to commit some changes?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 1]
```diff
@@ -9076,14 +8969,25 @@ static void preparePlanForMainVectorLoop(VPlan &MainPlan, VPlan &EpiPlan) {
...
       ResumePhi->moveBefore(*MainScalarPH, MainScalarPH->begin());
   }
-  // Add a user to to make sure the resume phi won't get removed.
-  VPBuilder(MainScalarPH)
-      .createNaryOp(VPInstruction::ResumeForEpilogue, ResumePhi);
+
+  // Create a ResumeForEpilogue for the canonical IV resume as the
+  // first non-phi, to keep it alive for the epilogue.
+  VPBuilder ResumeBuilder(MainScalarPH);
+  ResumeBuilder.createNaryOp(VPInstruction::ResumeForEpilogue, ResumePhi);
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Why not add this to the return value? Wouldn't it simplify things?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Damn, this is bad! Is the scalar TC really not kept anywhere? vec.epilog.resume.val is merely VectorTC, and ResumePhi is merely a phi from that start value up to ScalarTC, no?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 2]
```diff
@@ -9334,40 +9210,13 @@ static void fixScalarResumeValuesFromBypass(BasicBlock *BypassBlock, Loop *L,
...
-      }
-      IVPhi->setIncomingValueForBlock(PH, NewPhi);
+    // Fix resume values for inductions and reductions from the additional
+    // bypass block using the incoming values from the main loop's resume phis.
+    for (auto [ResumeV, IRPhi] :
+         zip(ResumeValues, ScalarPH->getIRBasicBlock()->phis())) {
+      auto *MainResumePhi = cast<PHINode>(ResumeV->getUnderlyingValue());
+      IRPhi.setIncomingValueForBlock(
+          BypassBlock, MainResumePhi->getIncomingValueForBlock(BypassBlock));
     }
```
Comment (artagnon) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Seems like this is the main simplification: can we not return the resume values directly from the incoming-values-for-block, in that return map_range and use them here?

**Review by artagnon — APPROVED** [review]
Thanks for all the explanations! I think that I understand this well enough to approve, but note that all this code is new to me, and I've not played with it: I'm worried that this might cause miscompiles and crashes due to some context that we didn't think of, but that's why we have version control. I _think_ further simplifications are possible, but let's not worry about that for now. LGTM, thanks!

**Comment by fhahn** [comment]
@stuij it looks like `TuneA320` limits the interleave count to 2 in this case. Does increasing the max interleave count resolve the regression? (I *think* the regression started in 92e44b247fd6 AFAICT)

**Comment by stuij** [comment]
@fhahn yes! I accidentally took the wrong function from the daily regression list to look at regressions caused by this patch. Sorry! I bisected it, and it was indeed https://github.com/llvm/llvm-project/commit/92e44b247fd6973615c7506e5ac92f1b13a80463. We've seen regressions caused by related patches and we've got a ticket for this. We did actually try to tweak max interleave count (to 4) but it did more harm than good for the CMSIS-DSP tests. It's ongoing. Thanks for having a think on it.

However, the list and amount of regressions that I quoted earlier in this thread does seem to be caused by this change. The numbers ebb and flow with this commit being applied and reverted (and it is pointed to by our automated bisecting). Examples of actual impacted tests are: [arm_fill_f16](https://github.com/ARM-software/CMSIS-DSP/blob/main/Source/BasicMathFunctions/arm_fill_f16.c), [arm_q7_to_q15](https://github.com/ARM-software/CMSIS-DSP/blob/main/Source/SupportFunctions/arm_q7_to_q15.c), [arm_mat_add_f16](https://github.com/ARM-software/CMSIS-DSP/blob/main/Source/MatrixFunctions/arm_mat_add_f16.c).

Looking at `arm_mat_add_f16.c` I can see 4 extra movs towards the start of the fn to keep values alive and in the NEON header 5 extra instructions that we now always execute to do checks that we would previously do afterwards, but only if we have resume values. So in the case of our test with multiples of 16, where we don't need the epilogue, this would be a function call overhead of 9 instructions, which I guess we do start to feel on an embedded core like the A320. Does that sound sane?
