### PR TITLE
[clang][Sema] Bad register variable type error should point to the type

### LINKED ISSUE #109776: clang's bad register type error points to register keyword instead of type name
Reported / discovered by https://discourse.llvm.org/t/frontend-how-to-use-register-union-or-struct-in-c/81392.

https://godbolt.org/z/fx6M7KrW9

```
typedef union Test {
    int i;
} Test;

register Test t asm ("x21");
```
Errors with:
```
<source>:5:22: error: size of register 'x21' does not match variable size
    5 | register Test t asm ("x21");
      |                      ^
<source>:5:1: error: bad type for named register variable
    5 | register Test t asm ("x21");
      | ^
2 errors generated.
Compiler returned: 1
```
The second error:
```
<source>:5:1: error: bad type for named register variable
    5 | register Test t asm ("x21");
      | ^
```
Points to the storage specifier not to the type name, which is confusing if you are not laser focused on the exact meaning of "type" here.

It should be:
```
<source>:5:1: error: bad type for named register variable
    5 | register Test t asm ("x21");
      |          ^
```

### PR DESCRIPTION
**Pull request by DavidSpickett**
...not the register keyword. Fixes #109776.

Until now the error was only tested in clang/test/Sema/asm.c, where you can't check for the "^" character. I've added a new caret test file as I see has been done for other error types.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
I also think that "bad" is a confusing word to use here, "unsupported" would be better but I will address that in a follow up PR.

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -7949,7 +7949,8 @@ NamedDecl *Sema::ActOnVariableDeclarator(
       }
 
       if (!R->isIntegralType(Context) && !R->isPointerType()) {
-        Diag(D.getBeginLoc(), diag::err_asm_bad_register_type);
+        Diag(TInfo->getTypeLoc().getBeginLoc(),
+             diag::err_asm_bad_register_type);
```
Comment (Sirraide) [inline clang/lib/Sema/SemaDecl.cpp:7953]: Maybe also add `<< TInfo->getTypeLoc().getSourceRange()`

**Review by Sirraide — COMMENTED** [review]
This is still missing a release note, and adding the source range too would be nice.

**Comment by Sirraide** [comment]
> I also think that "bad" is a confusing word to use here, "unsupported" would be better but I will address that in a follow up PR.

I don’t have a problem w/ ‘bad’, but ‘unsupported’ is clearer, yeah

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (DavidSpickett) [reply clang/lib/Sema/SemaDecl.cpp]: Done, thanks!

**Comment by DavidSpickett** [comment]
> This is still missing a release note, and adding the source range too would be nice.

Both done.

**Review by Sirraide — APPROVED** [review]
Looks like CI is still mad at you for some reason so that still needs to be looked into, but other than that this lgtm.
