### PR TITLE
[ARM][Codegen] Fix vector data miscompilation in  arm32be

### LINKED ISSUE #102418: [llvm] Deal vector data failed when using option Os、-mfloat-abi=softfp、--target=armebv7-linux
I find results in armebv7-linux  are different from armv7. 
code
```
#include <stdio.h> 
volatile int one = 1;

int main (int argc, char *argv[]) {
    __attribute__((vector_size((8)*sizeof(short)))) short v0 = {one, 1, 2, 3, 4, 5, 6, 7};
    __attribute__((vector_size((8)*sizeof(short)))) short v1;
    v1 = v0 % 2; 
    for (int __i = 0; __i < 8; __i++) { 
        printf("v1: %d\n", (*((short *) &(v1) + __i))); 
    }
    return 0;
}
```

When __i is 4, the result is different. I think this Instruction: **vrev32.16       d17, d18** is wrong,  and I try to modify it is **vmov.16 d17, d18**, the result is right. However I don't know how to fix this bug.

https://godbolt.org/z/EqYebY73z

### PR DESCRIPTION
**Pull request by Zhenhang1213**
Fix #102418， resolved the issue of generating incorrect vrev during vectorization in big-endian scenarios

### CODE REVIEW

File: llvm/lib/Target/ARM/ARMISelLowering.cpp [hunk 1]
```diff
@@ -7966,7 +7953,7 @@ SDValue ARMTargetLowering::LowerBUILD_VECTOR(SDValue Op, SelectionDAG &DAG,
 
       if (Val.getNode()) {
         SDValue Vmov = DAG.getNode(ARMISD::VMOVIMM, dl, VmovVT, Val);
-        return DAG.getNode(ISD::BITCAST, dl, VT, Vmov);
+        return DAG.getNode(ARMISD::VECTOR_REG_CAST, dl, VT, Vmov);
       }
 
       // Try an immediate VMVN.
```
Comment (davemgreen) [inline llvm/lib/Target/ARM/ARMISelLowering.cpp:7959]: Can you change the MVN below too (and maybe make sure there are tests to ensure it is correct).

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll [hunk 2]
```diff
@@ -10,7 +10,7 @@ define arm_aapcs_vfpcc <8 x i8> @vmov_i8() {
 ;
 ; CHECK-BE-LABEL: vmov_i8:
 ; CHECK-BE:       @ %bb.0:
-; CHECK-BE-NEXT:    vmov.i64 d0, #0xff
+; CHECK-BE-NEXT:    vmov.i64 d0, #0xff00000000000000Î
```
Comment (davemgreen) [inline llvm/test/CodeGen/ARM/big-endian-vmov.ll:13]: I believe these ones were correct before, and either need a `vmov 0xff`  or `vmov 0xff00000000000000 + vrev`

File: llvm/lib/Target/ARM/ARMISelLowering.cpp [hunk 3]
```diff
@@ -18601,7 +18588,6 @@ static SDValue PerformBITCASTCombine(SDNode *N,
   if ((Src.getOpcode() == ARMISD::VMOVIMM ||
        Src.getOpcode() == ARMISD::VMVNIMM ||
        Src.getOpcode() == ARMISD::VMOVFPIMM) &&
-      SrcVT.getScalarSizeInBits() <= DstVT.getScalarSizeInBits() &&
```
Comment (davemgreen) [inline llvm/lib/Target/ARM/ARMISelLowering.cpp:18604]: I think this needs to be more restictive, not less restrictive. There are cases where it will convert `bitcast+vector_reg_cast+vmovimm` incorrectly as the bitcast needs to remain to keep the lane shuffling that is required.

**Review by davemgreen — COMMENTED** [review]
Thanks for putting this up.

File: llvm/lib/Target/ARM/ARMISelLowering.cpp (hunk 1 above)
Comment (Zhenhang1213) [reply llvm/lib/Target/ARM/ARMISelLowering.cpp:7959]: done

**Comment by Zhenhang1213** [comment]
@davemgreen

**Comment by hstk30-hw** [comment]
Split to two commit, then we can see which code impact which testcases.

File: llvm/lib/Target/ARM/ARMISelLowering.cpp (hunk 1 above)
Comment (Zhenhang1213) [reply llvm/lib/Target/ARM/ARMISelLowering.cpp:7972]: > Can you change the MVN below too (and maybe make sure there are tests to ensure it is correct).

only change MVN, and all tests pass, [https://github.com/llvm/llvm-project/pull/105913](url)

**Comment by Zhenhang1213** [comment]
> Split to two commit, then we can see which code impact which testcases.

OK,  split it,  can see in this pr [Link](https://github.com/llvm/llvm-project/pull/105913)

File: llvm/test/CodeGen/Thumb2/mve-vmovimm.ll [hunk 4]
```diff
@@ -414,9 +414,8 @@ define arm_aapcs_vfpcc <16 x i8> @test(<16 x i8> %i) {
 ; CHECKBE-LABEL: test:
 ; CHECKBE:       @ %bb.0: @ %entry
 ; CHECKBE-NEXT:    vmov.i64 q1, #0xff00ff000000ff00
-; CHECKBE-NEXT:    vrev64.8 q2, q1
-; CHECKBE-NEXT:    vrev64.8 q1, q0
-; CHECKBE-NEXT:    vorr q1, q1, q2
+; CHECKBE-NEXT:    vrev64.8 q2, q0
+; CHECKBE-NEXT:    vorr q1, q2, q1
```
Comment (davemgreen) [inline llvm/test/CodeGen/Thumb2/mve-vmovimm.ll:418]: I'm pretty sure this one was correct before considering the constant. It should have a ff in the bottom lanes, either generated directly in the constant or from a vrev. I've added a few more tests, can you rebase over them. As mentioned in the other ticket I think more than one change is needed in order for all the tests to be correct.

Comment (Zhenhang1213) [reply llvm/test/CodeGen/Thumb2/mve-vmovimm.ll:1193]: After rebasing, I have merged two PRs and made all the tests pass, are
 any changes  needed next?

Comment (davemgreen) [reply llvm/test/CodeGen/Thumb2/mve-vmovimm.ll:1193]: Thanks. The intent we are aiming for is that vmovimm are always generated in "natural vector" lane order, where the lower values are in the lower lanes (same as little endian). Hence we don't pass IsBigEndian to isConstantSplat and use VECTOR_REG_CAST as opposed to BITCAST.

That means this linked bit of code should not be needed and can be removed, as the values from i64 vectors do not need to be rearranged: https://github.com/llvm/llvm-project/blob/178fc4779ece31392a2cd01472b0279e50b3a199/llvm/lib/Target/ARM/ARMISelLowering.cpp#L7124

I think that should clear up a lot of the cases that are not `bitcast(reg_cast(vmovimm))` (as happens when returning immediates from functions). Those I think are going wrong because of the code in PerformBITCASTCombine, that is mis-compiling that particular case.

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll [hunk 5]
```diff
@@ -227,7 +226,6 @@ define arm_aapcs_vfpcc <8 x i16> @xor_v8i16_m1(<8 x i16> %a) {
 ; CHECK-BE:       @ %bb.0:
 ; CHECK-BE-NEXT:    vmvn.i32 q8, #0x10000
 ; CHECK-BE-NEXT:    vrev64.16 q9, q0
-; CHECK-BE-NEXT:    vrev32.16 q8, q8
 ; CHECK-BE-NEXT:    veor q8, q9, q8
```
[the remark this answers is not in the document]
Comment (Zhenhang1213) [reply llvm/test/CodeGen/ARM/big-endian-vmov.ll:228]: ok, I removed those FIXME

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll [hunk 6]
```diff
@@ -177,7 +177,6 @@ define arm_aapcs_vfpcc <4 x i32> @and_v4i32_b(<4 x i32> %a) {
 ; CHECK-BE:       @ %bb.0:
 ; CHECK-BE-NEXT:    vmov.i64 q8, #0xffff00ff0000ff
 ; CHECK-BE-NEXT:    vrev64.32 q9, q0
-; CHECK-BE-NEXT:    vrev64.32 q8, q8
 ; CHECK-BE-NEXT:    vand q8, q9, q8
```
[the remark this answers is not in the document]
Comment (Zhenhang1213) [reply llvm/test/CodeGen/ARM/big-endian-vmov.ll:191]: > After removing rearranged i64 vectors in PerformBITCASTCombine, all tests update. could you review it again? Thinks.



> This one was correct before I believe, and is now incorrect.

After removing rearranged i64 vectors in PerformBITCASTCombine, all tests update. could you review it again? Thanks.

**Comment by davemgreen** [comment]
Did you manage to look into fixing PerformBITCASTCombine yet?

**Comment by Zhenhang1213** [comment]
> Did you manage to look into fixing PerformBITCASTCombine yet?

Logically, I understand that this change does not involve PerformBITCASTCombine function, right?

**Comment by Zhenhang1213** [comment]
> Did you manage to look into fixing PerformBITCASTCombine yet?

And I think if we don't fix by change ISD::BITCAST to ARMISD::VECTOR_REG_CAST,  could I Identify the failure scenario of this test case, and in PerformBITCASTCombine  function,  call ARMISD::VECTOR_REG_CAST?

**Comment by Zhenhang1213** [comment]
> > Did you manage to look into fixing PerformBITCASTCombine yet?
> 
> And I think if we don't fix by change ISD::BITCAST to ARMISD::VECTOR_REG_CAST, could I Identify the failure scenario of this test case, and in PerformBITCASTCombine function, call ARMISD::VECTOR_REG_CAST?

I looked at this question again and did I have a chance to flip it when concat_vectors in PerformBITCASTCombine ?

**Comment by davemgreen** [comment]
Hi - I think all the changes you have so far are good, but some of the tests are still wrong and it would be good to fix PerformBITCASTCombine too.

If you consider the xor_int64_ff0000ff0000ffff case:
```
define arm_aapcs_vfpcc <2 x i64> @xor_int64_ff0000ff0000ffff(<2 x i64> %a) {
entry:
  %b = xor <2 x i64> %a, <i64 -72056498821201921, i64 -72056498821201921>
  ret <2 x i64> %b
}
```
A series of transforms, which I believe are all OK, lead to:
```
    t3: v2i64 = bitcast t2
        t16: v2i64 = ARMISD::VMOVIMM TargetConstant:i32<7737>
      t17: v4i32 = ARMISD::VECTOR_REG_CAST t16
    t14: v2i64 = bitcast t17
  t6: v2i64 = xor t3, t14
t7: v2f64 = bitcast t6
```
The `bitcast ( VECTOR_REG_CAST ( VMOVIMM ))` is converted to `VECTOR_REG_CAST ( VMOVIMM )` as it is believed that the bitcast does not matter as each lane of the input will be identical. It only looks at the bitcast dst type and the vmovimm type, ignoring that the VECTOR_REG_CAST makes the bitcast important.

It ends up with this, that has the top/bottom half of each i64 in the wrong order.
```
   t16: v2i64 = ARMISD::VMOVIMM TargetConstant:i32<7737>
 t6: v2i64 = xor t3, t16

  vmov.i64        q8, #0xffffff0000ff
  veor    q0, q0, q8
```

File: llvm/lib/Target/ARM/ARMISelLowering.cpp (hunk 3 above)
Comment (Zhenhang1213) [reply llvm/lib/Target/ARM/ARMISelLowering.cpp:18607]: > I think this needs to be more restictive, not less restrictive. There are cases where it will convert `bitcast+vector_reg_cast+vmovimm` incorrectly as the bitcast needs to remain to keep the lane shuffling that is required.

so could I change
```
SrcVT.getScalarSizeInBits() <= DstVT.getScalarSizeInBits()
```
to 
```
SrcVT.getScalarSizeInBits() < DstVT.getScalarSizeInBits()
```

**Comment by Zhenhang1213** [comment]
> Sorry I haven't had a chance to look into this in detail yet. I wasn't really sure when I last looked what the best fix for that part was - I was thinking it might be worth just removing the `while (Src.getOpcode() == ARMISD::VECTOR_REG_CAST) Src = Src.getOperand(0);` if there isn't a better idea. As far as I understand the part for bitcasts is always correct (as the vmov element size is smaller than swapping around each lanes in the larger size doesn't alter the result).
> 
> If we want to keep that optimization, then IMO it might be good the have a combine that works a little differently - that looks through `bitcast(vector_reg_cast(vmovimm))`, reconstructs the constant as it should be and generates a new vmovimm with the correct value. It should handle more cases. In the meantime, so long as everyone is happy enough with the code being a bit slower we can just drop the while loop.

Hi, yesterday I try to make it more restictive 


```
SrcVT.getScalarSizeInBits() <= DstVT.getScalarSizeInBits()
```

to 
```
SrcVT.getScalarSizeInBits() < DstVT.getScalarSizeInBits()
```
and the case  xor_int64_ff0000ff0000ffff is satisfiying, right？


```
 CHECKBE-LABEL: xor_int64_ff0000ff0000ffff:
; CHECKBE:       @ %bb.0: @ %entry
; CHECKBE-NEXT:    vmov.i64 q1, #0xffffff0000ff
; CHECKBE-NEXT:    vrev64.32 q2, q1
; CHECKBE-NEXT:    veor q0, q0, q2
; CHECKBE-NEXT:    bx lr
```

**Comment by davemgreen** [comment]
I do believe xor_int64_ff0000ff0000ffff is correct now. My worry is that that might mean that cases that are legal to fold would not any more, and possibly not fix cases that should be blocked. Something like `(v4i32 bitcast (v16i8 regcast (v8i16 vmovimm)))`.

Can you either remove that while loop, or maybe change it to something like:
```
  // We may have a bitcast of something that has already had this bitcast
  // combine performed on it, so skip past any VECTOR_REG_CASTs.
  if (Src.getOpcode() == ARMISD::VECTOR_REG_CAST &&
      Src.getOperand(0).getValueType().getScalarSizeInBits() <=
          Src.getValueType().getScalarSizeInBits())
    Src = Src.getOperand(0);
```

File: llvm/lib/Target/ARM/ARMISelLowering.cpp (hunk 3 above)
Comment (davemgreen) [reply llvm/lib/Target/ARM/ARMISelLowering.cpp:18607]: Change this back to <= too, it should be OK now I think

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll (hunk 5 above)
[the remark this answers is not in the document]
Comment (davemgreen) [reply llvm/test/CodeGen/ARM/big-endian-vmov.ll:250]: I think you removed the wrong FIXME. IIRC and_v8i16_m1 is still not working correctly, but that is a separate issue. The one on this function can be removed.

**Review by davemgreen — COMMENTED** [review]
Thanks, this is looking good to me now with a couple of adjustments.

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll [hunk 7]
```diff
@@ -227,7 +248,6 @@ define arm_aapcs_vfpcc <8 x i16> @xor_v8i16_m1(<8 x i16> %a) {
 ; CHECK-BE:       @ %bb.0:
```
Comment (davemgreen) [inline llvm/test/CodeGen/ARM/big-endian-vmov.ll:248]: Remove the FIXME on this function.

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM

File: llvm/test/CodeGen/ARM/big-endian-vmov.ll (hunk 7 above)
Comment (Zhenhang1213) [reply llvm/test/CodeGen/ARM/big-endian-vmov.ll:247]: ok
