### PR TITLE
[clang-tidy] Avoid overflow when dumping unsigned integer values

### LINKED ISSUE #60217: `misc-throw-by-value-catch-by-reference.MaxSize: '-1'` generated by `clang-tidy-16 --dump-config` crashes it when it parses the config again
```bash
apt list clang-tidy-16
```

```
clang-tidy-16/unknown,now 1:16~++20230117111205+2156d33b49b8-1~exp1~20230117111257.1042 amd64 [installed]
```

```yaml
---
Checks:          'misc-*'
CheckOptions:
  misc-throw-by-value-catch-by-reference.MaxSize: '-1'
...

```

```console
0.      Program arguments: clang-tidy-16 --dump-config
 #0 0x00007f1223bbffa6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfbffa6)
 #1 0x00007f1223bbe190 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfbe190)
 #2 0x00007f1223bc077b (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfc077b)
 #3 0x00007f1222655f90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #4 0x000055e9a1462a4c clang::tidy::ClangTidyContext::diag(llvm::StringRef, llvm::StringRef, clang::DiagnosticIDs::Level) (/usr/lib/llvm-16/bin/clang-tidy+0x14a4a4c)
 #5 0x000055e9a1462dc6 clang::tidy::ClangTidyContext::configurationDiag(llvm::StringRef, clang::DiagnosticIDs::Level) (/usr/lib/llvm-16/bin/clang-tidy+0x14a4dc6)
 #6 0x000055e9a1461854 clang::tidy::ClangTidyCheck::OptionsView::diagnoseBadIntegerOption(llvm::Twine const&, llvm::StringRef) const (/usr/lib/llvm-16/bin/clang-tidy+0x14a3854)
 #7 0x000055e9a0a5b274 clang::tidy::misc::ThrowByValueCatchByReferenceCheck::ThrowByValueCatchByReferenceCheck(llvm::StringRef, clang::tidy::ClangTidyContext*) (/usr/lib/llvm-16/bin/clang-tidy+0xa9d274)
 #8 0x000055e9a09bda24 (/usr/lib/llvm-16/bin/clang-tidy+0x9ffa24)
 #9 0x000055e9a1461c6b clang::tidy::ClangTidyCheckFactories::createChecks(clang::tidy::ClangTidyContext*) const (/usr/lib/llvm-16/bin/clang-tidy+0x14a3c6b)
#10 0x000055e9a14555ff clang::tidy::getCheckOptions(clang::tidy::ClangTidyOptions const&, bool) (/usr/lib/llvm-16/bin/clang-tidy+0x14975ff)
#11 0x000055e9a07e3fbd clang::tidy::clangTidyMain(int, char const**) (/usr/lib/llvm-16/bin/clang-tidy+0x825fbd)
#12 0x00007f122264118a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#13 0x00007f1222641245 call_init ./csu/../csu/libc-start.c:128:20
#14 0x00007f1222641245 __libc_start_main ./csu/../csu/libc-start.c:368:5
#15 0x000055e9a07e0751 _start (/usr/lib/llvm-16/bin/clang-tidy+0x822751)
```

### PR DESCRIPTION
**Pull request by ealcdan**
Some options take the maximum unsigned integer value as default, but they are being dumped to a string as integers. This makes -dump-config write invalid '-1' values for these options. This change fixes this issue by using utostr if the option is unsigned.

Fixes #60217

### CODE REVIEW

**Comment by ealcdan** [comment]
This PR attempts to fix #60217

File: clang-tools-extra/clang-tidy/ClangTidyCheck.h [hunk 1]
```diff
@@ -408,17 +408,26 @@ class ClangTidyCheck : public ast_matchers::MatchFinder::MatchCallback {
...
+          T Value) const {
+      storeUnsigned(Options, LocalName, Value);
+    }
+
     /// Stores an option with the check-local name \p LocalName with
     /// integer value \p Value to \p Options. If the value is empty
     /// stores ``
     template <typename T>
-    std::enable_if_t<std::is_integral_v<T>>
+    std::enable_if_t<std::is_integral_v<T> && std::is_signed<T>::value>
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/ClangTidyCheck.h:430]: instead of adding new version for optional, just call in this method `store` instead of storeInt,

File: clang-tools-extra/clang-tidy/ClangTidyCheck.h [hunk 2]
```diff
@@ -408,17 +408,26 @@ class ClangTidyCheck : public ast_matchers::MatchFinder::MatchCallback {
     /// Stores an option with the check-local name \p LocalName with
     /// integer value \p Value to \p Options.
     template <typename T>
-    std::enable_if_t<std::is_integral_v<T>>
+    std::enable_if_t<std::is_integral_v<T> && std::is_signed<T>::value>
     store(ClangTidyOptions::OptionMap &Options, StringRef LocalName,
           T Value) const {
       storeInt(Options, LocalName, Value);
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/ClangTidyCheck.h:414]: jinstead of using std::is_signed just use:
```
if constexpr(std::is_signed_v<T>)
   storeInt(Options, LocalName, Value);
else
  storeUnsigned(Options, LocalName, Value);
```

File: clang-tools-extra/clang-tidy/ClangTidyCheck.h [hunk 3]
```diff
@@ -470,6 +491,8 @@ class ClangTidyCheck : public ast_matchers::MatchFinder::MatchCallback {
     void storeInt(ClangTidyOptions::OptionMap &Options, StringRef LocalName,
                   int64_t Value) const;
 
+    void storeUnsigned(ClangTidyOptions::OptionMap &Options,
+                       StringRef LocalName, int64_t Value) const;
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/ClangTidyCheck.h:495]: value should be uint64_t

**Review by PiotrZSL — COMMENTED** [review]
Missing test (based on some check).

**Comment by PiotrZSL** [comment]
And just one comment, when this check uses max value as "limit", this behavior is also a reason why support for optional values were added. For me in this case check & description should be updated to handle this config as an optional, instead of mentioning max u64 in documentation. As for support for unsigned values, that's welcome too regardless.

**Comment by ealcdan** [comment]
Thanks for the review. I'm adding a test that checks that no '-1' is returned for misc-throw-by-value-catch-by-reference.MaxSize, that should pass even when no value is dumped for the option by default. I also added a test that sets 2⁶⁰ as a value for that option, and checks that the dumped value is 2⁶⁰ too.

**Comment by ealcdan** [comment]
ping :)

**Review by PiotrZSL — APPROVED** [review]
- One code duplication that could be avoided.
- Add entry in release notes, about fixing issue with big unsigned config option values printed as negative numbers in --dump-config

Overall, fine.
As for misc-throw-by-value-catch-by-reference check, we may need to use optional in future for this and fix documentation.

**Comment by ealcdan** [comment]
Great, both points have been addressed in the new patches, hope the release notes entry is clear enough.

**Review by PiotrZSL — APPROVED** [review]

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -251,6 +251,9 @@ Miscellaneous
   option is specified. Now ``clang-apply-replacements`` applies formatting only with
   the option.
 
+- Fixed bug where big values for unsigned check options overflowed into negative values
+  when being printed with ``--dump-config``.
```
[the remark this answers is not in the document]
Comment (ealcdan) [reply clang-tools-extra/docs/ReleaseNotes.rst]: I moved it there and rebased the commit

**Comment by PiotrZSL** [comment]
Unless you want this to be merged as 115098653+ealcdan@users.noreply.github.com, change your email privacy settings.

**Comment by ealcdan** [comment]
Sure, I just updated my settings, thanks for the suggestion.
