### PR TITLE
MIPS: Use pcrel|sdata4 for eh_frame

### LINKED ISSUE #58377: ld.lld: error: relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC
t.cpp

```
#include <stdio.h>

#include "t.h"

TT::TT(const int a)
    : n(a)
{
    printf("{%s}[%s](%d) : %d\n", __FILE__, __func__, __LINE__, n); 
}
```

m.cpp
```
#include <stdio.h>

#include "t.h"

int main()
{
    int c = 100;
    printf("{%s}[%s](%d) : %d\n", __FILE__, __func__, __LINE__, c); 
    TT *a = new TT(c);
    printf("{%s}[%s](%d) : %p\n", __FILE__, __func__, __LINE__, a); 
    return 0;
}
```

t.h
```
class TT {
public:
    //explicit TT(const int a);
    TT(const int a);
    ~TT() {};
private:
    int n {};
};
```

```
$ ../build/bin/clang++ -fPIC -mabi=32 -fuse-ld=lld -O3 -o a.out t.cpp m.cpp
ld.lld: error: relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC
>>> defined in /tmp/m-dc13fe.o
>>> referenced by m.cpp
>>>               /tmp/m-dc13fe.o:(.eh_frame+0x2D)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
$ ../build/bin/clang++ -fPIC -L/lib64 -mabi=64 -fuse-ld=lld -O3 -o a.out t.cpp m.cpp 
ld.lld: error: relocation R_MIPS_64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /tmp/m-627e22.o
>>> referenced by m.cpp
>>>               /tmp/m-627e22.o:(.eh_frame+0x31)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by wzssyqa**
Gas uses encoding DW_EH_PE_absptr for PIC, and gnu ld converts it to DW_EH_PE_sdata4|DW_EH_PE_pcrel.
LLD doesn't have this workarounding, thus complains
```
  relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC
  relocation R_MIPS_64 cannot be used against local symbol; recompile with -fPIC
```

So, let's generates asm/obj files with `DW_EH_PE_sdata4|DW_EH_PE_pcrel` encoding. In fact, GNU ld supports such OBJs well.

For N64, maybe we should use sdata8, while GNU ld doesn't support it well, and in fact sdata4 is enough now. So we just ignore the `Large` for `MCObjectFileInfo::initELFMCObjectFileInfo`. Maybe we should switch back to sdata8 once GNU LD supports it well.

Fixes: #58377.

### CODE REVIEW

File: llvm/lib/MC/MCObjectFileInfo.cpp [hunk 1]
```diff
@@ -343,7 +343,7 @@ void MCObjectFileInfo::initELFMCObjectFileInfo(const Triple &T, bool Large) {
   case Triple::mips64el:
     // We cannot use DW_EH_PE_sdata8 for the large PositionIndependent case
     // since there is no R_MIPS_PC64 relocation (only a 32-bit version).
-    if (PositionIndependent && !Large)
+    if (PositionIndependent)
```
Comment (jrtc27) [inline llvm/lib/MC/MCObjectFileInfo.cpp:346]: This just ignores the justification above?

File: llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp [hunk 2]
```diff
@@ -212,13 +212,8 @@ void TargetLoweringObjectFileELF::Initialize(MCContext &Ctx,
     //        identify N64 from just a triple.
     TTypeEncoding = dwarf::DW_EH_PE_indirect | dwarf::DW_EH_PE_pcrel |
                     dwarf::DW_EH_PE_sdata4;
-    // We don't support PC-relative LSDA references in GAS so we use the default
-    // DW_EH_PE_absptr for those.
 
-    // FreeBSD must be explicit about the data size and using pcrel since it's
-    // assembler/linker won't do the automatic conversion that the Linux tools
-    // do.
```
Comment (jrtc27) [inline llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp:220]: What's changed to make neither of these comments correct?

**Review by jrtc27 — COMMENTED** [review]
Maybe I'm being stupid but I don't understand how your PR body relates to the code you're deleting

File: llvm/lib/MC/MCObjectFileInfo.cpp (hunk 1 above)
Comment (wzssyqa) [reply llvm/lib/MC/MCObjectFileInfo.cpp:346]: Yes. even with `Large` we still use sdata4, instead of sdata8.

```
For N64, maybe we should use sdata8, while GNU ld doesn't support it well, and in fact sdata4 is enough now.
```
Maybe, I will need to make it more clear.

File: llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp (hunk 2 above)
Comment (wzssyqa) [reply llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp:220]: You are right. We should be careful. Let's keep the OSFreebsd here.

**Comment by MaskRay** [comment]
Using DW_EH_PE_sdata4 is a step forward but I was confused by the description as well.

> Maybe we should switch back to sdata8 once GNU LD supports it well.

Looks good. I suspect that the number of MIPS users is small enough that we can require compilers to have a higher version.

**Comment by alexrp** [comment]
I don't suppose it would be possible to get this fix into an LLVM 18.1.8 release? (Not sure what the policy is here in general.) This issue is blocking me from compiling libffi for MIPS with Zig.
