### PR TITLE
[clang] Do not diagnose unused deleted operator delete[]

### LINKED ISSUE #134265: Incorrect error reported for deleted function
Some time since 0454dd8c48cd771478f1ae53330ba78e71bcd7c clang has started emitting an error for using a deleted function, except that function is not used. 

```
struct Foo {
  virtual ~Foo() {}
  static void operator delete[](void* ptr) = delete;
};
```
```
<source>:2:11: error: attempt to use a deleted function
    2 |   virtual ~Foo() {}
      |           ^
<source>:3:15: note: 'operator delete[]' has been explicitly marked deleted here
    3 |   static void operator delete[](void* ptr) = delete;
      |               ^
1 error generated.
Compiler returned: 1
```

Godbolt: https://godbolt.org/z/aW31816h4

Surprisingly, this doesn't appear to manifest on godbolt w/ the assertions enabled, but in my local build (RelWithDebInfo + assertions) they do.

I'm bisecting now, but #133451 and #128866 seem like they could be related. 

cc: @momo5502 @Fznamznon

### PR DESCRIPTION
**Pull request by Fznamznon**
For vector deleting dtors support we now also search and save operator delete[]. Avoid diagnosing deleted operator delete[] when doing that because vector deleting dtors are only called when delete[] is present and whenever delete[] is present in the TU it will be diagnosed correctly.

Fixes https://github.com/llvm/llvm-project/issues/134265

### CODE REVIEW

File: clang/include/clang/AST/DeclCXX.h [hunk 1]
```diff
@@ -2878,7 +2878,7 @@ class CXXDestructorDecl : public CXXMethodDecl {
   static CXXDestructorDecl *CreateDeserialized(ASTContext &C, GlobalDeclID ID);
 
   void setOperatorDelete(FunctionDecl *OD, Expr *ThisArg);
-  void setOperatorArrayDelete(FunctionDecl *OD, Expr *ThisArg);
+  void setOperatorArrayDelete(FunctionDecl *OD);
```
Comment (AaronBallman) [inline clang/include/clang/AST/DeclCXX.h:2881]: This looks like unrelated changes, but the changes themselves are correct.

**Review by AaronBallman — APPROVED** [review]
LGTM but do we need a release note?

File: clang/include/clang/AST/DeclCXX.h (hunk 1 above)
Comment (Fznamznon) [reply clang/include/clang/AST/DeclCXX.h:2881]: Yeah, this is a drive-by removal of unused argument added by a patch that caused the bug this patch is fixing.

**Comment by Fznamznon** [comment]
> LGTM but do we need a release note?

No, it is a regression caused by a patch committed a couple of days ago.

File: clang/include/clang/AST/DeclCXX.h (hunk 1 above)
Comment (Fznamznon) [reply clang/include/clang/AST/DeclCXX.h:2881]: Should I do that in a separate commit?

Comment (AaronBallman) [reply clang/include/clang/AST/DeclCXX.h:2881]: No, I think it's related enough as a drive-by it's fine.

**Comment by AaronBallman** [comment]
> > LGTM but do we need a release note?
> 
> No, it is a fix for a regression caused by a patch committed a couple of days ago.

Excellent, thank you for confirming! LG as-is

**Comment by zmodem** [comment]
We're seeing crashes that bisect to this change. Here is a reproducer: https://crbug.com/410001969#comment3

I'll see if I can get something more reduced as well.
