### PR TITLE
[MLIR][Affine] Fix memref replacement in affine-data-copy-generate

### LINKED ISSUE #130257: [mlir] Inconsistent output when executing MLIR program with `--affine-data-copy-generate="generate-dma=false fast-mem-space=0 skip-non-unit-stride-loops"`
git version: d6c0839c9c823

system: `Ubuntu 18.04.6 LTS`

## Description:
I am experiencing an inconsistent result when executing the same MLIR program with and without `--affine-data-copy-generate="generate-dma=false fast-mem-space=0 skip-non-unit-stride-loops"`. 

### 1. **MLIR Program (a.mlir)**:
a.mlir: 
``` 
module {
  func.func private @printMemrefI32(tensor<*xi32>)
  func.func private @printMemrefF32(tensor<*xf32>)
  func.func @entry(%arg0: index) -> ( tensor<1x3x5xi32>) {
    %37 = "tosa.const"() <{value = dense<0> : tensor<1x3x5xi32>}> : () -> tensor<1x3x5xi32>
    %38 = tosa.while_loop (%arg1 = %37) : (tensor<1x3x5xi32>) -> tensor<1x3x5xi32> {
      %96 = "tosa.const"() <{value = dense<3> : tensor<1x3x5xi32>}> : () -> tensor<1x3x5xi32>
      %97 = tosa.greater %96, %arg1 : (tensor<1x3x5xi32>, tensor<1x3x5xi32>) -> tensor<1x3x5xi1>
      %extracted_8 = tensor.extract %97[%arg0, %arg0, %arg0] : tensor<1x3x5xi1>
      %from_elements_9 = tensor.from_elements %extracted_8 : tensor<i1>
      tosa.yield %from_elements_9 : tensor<i1>
    } do {
    ^bb0(%arg1: tensor<1x3x5xi32>):
      %101 = "tosa.const"() <{value = dense<1> : tensor<1x3x5xi32>}> : () -> tensor<1x3x5xi32>
      %102 = tosa.add %arg1, %101 : (tensor<1x3x5xi32>, tensor<1x3x5xi32>) -> tensor<1x3x5xi32>
      tosa.yield %102 : tensor<1x3x5xi32>
    }
    return  %38 :  tensor<1x3x5xi32>
  }
  func.func @main() {
    %idx0 = index.constant 0
    %0 = call @entry(%idx0) : (index) -> ( tensor<1x3x5xi32>)
    %cast_0 = tensor.cast %0 : tensor<1x3x5xi32> to tensor<*xi32>
    call @printMemrefI32(%cast_0) : (tensor<*xi32>) -> ()
    return
  }
}


``` 

 ### 2. **Command to Run without  `--affine-data-copy-generate` :**

``` 
/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt /data/szy/workspace/mlir-inconsistent/a.mlir   -tosa-to-scf  \
| /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -pass-pipeline="builtin.module(func.func(tosa-to-linalg))"  \
| /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -tosa-to-arith  -tosa-to-tensor   -convert-scf-to-cf   --test-math-to-vcix    \
-one-shot-bufferize="bufferize-function-boundaries"    --expand-strided-metadata  -convert-linalg-to-affine-loops    -lower-affine  \
-convert-scf-to-cf   -finalize-memref-to-llvm  -convert-arith-to-llvm   -convert-func-to-llvm -convert-cf-to-llvm  -convert-index-to-llvm  \
-reconcile-unrealized-casts | timeout 100 /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-cpu-runner -e main \
-entry-point-result=void --shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_c_runner_utils.so \
--shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_runner_utils.so \
--shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_async_runtime.so
``` 

### 3. **Output  without   `--affine-data-copy-generate` :**:

``` 
[[[3],
  [3]]]
``` 

### 4. **Command to Run with  `--affine-data-copy-generate`  :**

``` 
/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt /data/szy/workspace/mlir-inconsistent/a.mlir   -tosa-to-scf  \
| /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -pass-pipeline="builtin.module(func.func(tosa-to-linalg))"  \
| /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -tosa-to-arith  -tosa-to-tensor   -convert-scf-to-cf   --test-math-to-vcix    \
-one-shot-bufferize="bufferize-function-boundaries"    --expand-strided-metadata  -convert-linalg-to-affine-loops    \
--affine-data-copy-generate="generate-dma=false fast-mem-space=0 skip-non-unit-stride-loops"  -lower-affine  -convert-scf-to-cf   \
-finalize-memref-to-llvm  -convert-arith-to-llvm   -convert-func-to-llvm -convert-cf-to-llvm  -convert-index-to-llvm  \
-reconcile-unrealized-casts | timeout 100 /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-cpu-runner -e main \
-entry-point-result=void --shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_c_runner_utils.so \
--shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_runner_utils.so \
--shared-libs=/data/szy/MLIR/llvm-release/llvm-project/build/lib/libmlir_async_runtime.so
``` 

### 5. **Output with  `--affine-data-copy-generate` :**

``` 
[[[109110929],
  [21903]]]
``` 

### 6. **Analysis for this case :**

This MLIR program is expected to correctly output` [[3],[3]]` because the loop terminates when the condition greater than 3 is no longer met. The loop variable `%arg1` is initialized to 0 and incremented by 1 in each iteration, ensuring that it reaches 3 before exiting. However, after applying ` --affine-data-copy-generate`, the program incorrectly outputs a random value instead. 

I debug this issue and find the faulty pass is `--affine-data-copy-generate `pass
**The input IR** (ir before running the` --affine-data-copy-generate` pass) can be found in  [input.txt](https://github.com/user-attachments/files/19122238/input.txt)
**The output IR** (ir after running the --affine-data-copy-generate pass) can be found in [output.txt](https://github.com/user-attachments/files/19122240/output.txt)
Please change file from .txt to .mlir

As shown in the first image, the loop variable %1 is incremented by 1 in line 32-33. However, after running `--affine-data-copy-generate`, as shown in the second image, it mistakenly load %alloc_16 (in line 60) that has been deallocated in line 53, leading to a random value result.
`%alloc_16` should be %1.

Image

Image

### PR DESCRIPTION
**Pull request by bondhugula**
Fixes: https://github.com/llvm/llvm-project/issues/130257

Fix affine-data-copy-generate in certain cases that involved users in multiple blocks. Perform the memref replacement correctly during copy generation.

Improve/clean up memref affine use replacement API. Instead of supporting dominance and post dominance filters (which aren't adequate in most cases) and computing dominance info expensively each time in RAMUW, provide a user filter callback, i.e., force users to compute dominance if needed.

### CODE REVIEW

File: mlir/lib/Dialect/Affine/Transforms/PipelineDataTransfer.cpp [hunk 1]
```diff
@@ -115,13 +115,16 @@ static bool doubleBuffer(Value oldMemRef, AffineForOp forOp) {
...
   // replaceAllMemRefUsesWith will succeed unless the forOp body has
   // non-dereferencing uses of the memref (dealloc's are fine though).
-  if (failed(replaceAllMemRefUsesWith(
-          oldMemRef, newMemRef,
-          /*extraIndices=*/{ivModTwoOp},
-          /*indexRemap=*/AffineMap(),
-          /*extraOperands=*/{},
-          /*symbolOperands=*/{},
-          /*domOpFilter=*/&*forOp.getBody()->begin()))) {
+  auto userFilterFn = [&](Operation *user) {
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Transforms/PipelineDataTransfer.cpp:118]: Should we compute dominance info inside a static utility? It is expensive, and I thought the convention is to compute it once in the entry function of a pass, and pass it around.

File: mlir/test/Dialect/Affine/affine-data-copy.mlir [hunk 2]
```diff
@@ -447,3 +447,51 @@ func.func @memref_def_inside(%arg0: index) {
...
+  %c1_i32 = arith.constant 1 : i32
+  %c3_i32 = arith.constant 3 : i32
+  %0 = memref.get_global @__constant_1x2x1xi32_1 : memref<1x2x1xi32>
+  %alloc = memref.alloc() {alignment = 64 : i64} : memref<1x2x1xi32>
+  memref.copy %0, %alloc : memref<1x2x1xi32> to memref<1x2x1xi32>
+  cf.br ^bb1(%alloc : memref<1x2x1xi32>)
+^bb1(%1: memref<1x2x1xi32>):  // 2 preds: ^bb0, ^bb2
+// CHECK: ^bb1(%[[MEM:.*]]: memref<1x2x1xi32>):
+  %alloc_0 = memref.alloc() {alignment = 64 : i64} : memref<1x2x1xi1>
+  // CHECK: %[[BUF:.*]] = memref.alloc() : memref<1x2x1xi32>
```
Comment (arnab-polymage) [inline mlir/test/Dialect/Affine/affine-data-copy.mlir:466]: A question for my understanding -- Why is the fast buffer not allocated in shared memory space?
?

Comment (bondhugula) [reply mlir/test/Dialect/Affine/affine-data-copy.mlir:466]: The RUN command above specifies '0' as the memory space for the fast buffer as well - for e.g. for the typical case of CPUs where the buffer is expected to live in cache.

**Review by arnab-polymage — APPROVED** [review]
LGTM
