### PR TITLE
Fix crash with align_value diagnostic reporting

### LINKED ISSUE #26612: Clang fails with "UNREACHABLE executed" with __attribute__((align_value( ))) in a template
|  |  |
| --- | --- |
| Bugzilla Link | [26238](https://llvm.org/bz26238) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@hfinkel,@zygoloid |

## Extended Description 
==========Environment================
OS: Linux
version: trunk
Lang: C++

=========How to reproduce============
template <class T>
void f(T __attribute__((align_value(4))) x) {}

int main() {
  f<int>(0);
  return 0;
}

$ clang -c test.cpp

=========Error======================
Unexpected attribute kind!
UNREACHABLE executed at ***/llvm/tools/clang/include/clang/AST/AttrImpl.inc:6785!

=========Note=======================
Everything is OK if attribute is applied to a pointer type (with T * __attribute__ or f<int *>(0))

===================
Intel Compiler Engineer 
Andrey Kuleshov

### PR DESCRIPTION
**Pull request by AaronBallman**
We were passing the address of a local variable to a call to Diag() which then tried to use the object after its lifetime ended, resulting in crashes. We no longer pass the temporary object any longer.

Fixes #26612

### CODE REVIEW

**Comment by AaronBallman** [comment]
Note, I filed an issue about the duplicate diagnostics at https://github.com/llvm/llvm-project/issues/135012

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 1]
```diff
@@ -4383,7 +4383,6 @@ static void handleAlignValueAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
 }
 
 void Sema::AddAlignValueAttr(Decl *D, const AttributeCommonInfo &CI, Expr *E) {
-  AlignValueAttr TmpAttr(Context, CI, E);
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclAttr.cpp:4386]: This attribute created on the stack is a smell.

I note a few have the same problem:
The following 5 functions (via manual search :/) have an attribute created on the stack:
`Sema::AddAssumeAlignedAttr`
`Sema::AddAllocAlignAttr`
`Sema::AddAlignedAttr` x2 (1 type and 1 expr implementation)
`Sema::CreateLaunchBoundsAttr`

Of these:
`Sema::AddAssumeAlignedAttr`  Has the EXACT same problem (using it in a diag).  So a repro should be the same
`Sema::AddAllocAlignAttr` << Same problem with diag again
`Sema::AddAlignedAttr` x2 (1 type and 1 expr implementation) << Neither seem to have this problem
`Sema::CreateLaunchBoundsAttr` << All diagnostics are in a separate file at least, so the attribute isn't out of scope immediately after `makeLaunchBoundsExpr`


I would love to have the others cleaned up, but only the 1st 2 actually have this exact issue, and should probably be cleaned up here.

Comment (AaronBallman) [reply clang/lib/Sema/SemaDeclAttr.cpp:4386]: I can fix those other ones up, but I can't seem to induce the same problems for them so the test coverage will be pro forma rather than showing a behavioral difference.

Comment (erichkeane) [reply clang/lib/Sema/SemaDeclAttr.cpp:4386]: I think that is acceptable.  This one sort of reproduces because of 'luck' as well.

**Review by erichkeane — APPROVED** [review]
