### PR TITLE
[SLPVectorizer] Check std::optional coming out of getPointersDiff

### LINKED ISSUE #175768: SLP vectorizer crashes with assertions on
This is the repro in godbold
https://godbolt.org/z/c3nzMcrGs

```llvm
target triple = "x86_64-unknown-linux-gnu"

define void @test(i64 %arg0, i64 %arg1) {
entry:
  %init = add i64 %arg0, 1
  br label %loop

loop:
  %iv = phi i64 [ %init, %entry ], [ %iv.next, %reduce ]
  %counter = phi i64 [ 1, %entry ], [ %counter.next, %reduce ]
  %off0 = add i64 %iv, -4
  %off1 = add i64 %iv, -3
  %off2 = add i64 %iv, -2
  %off3 = add i64 %iv, -1
  %ptr = call ptr null(ptr null, ptr null)
  %idx0 = add i64 %arg1, %off0
  %idx0.scaled = shl i64 %idx0, 3
  %gep0 = getelementptr i8, ptr %ptr, i64 %idx0.scaled
  %gep0.off = getelementptr i8, ptr %gep0, i64 -8
  %load0 = load double, ptr %gep0.off, align 8
  %idx1 = add i64 %arg1, %off1
  %idx1.scaled = shl i64 %idx1, 3
  %gep1 = getelementptr i8, ptr %ptr, i64 %idx1.scaled
  %gep1.off = getelementptr i8, ptr %gep1, i64 -8
  %load1 = load double, ptr %gep1.off, align 8
  %idx2 = add i64 %arg1, %off2
  %idx2.scaled = shl i64 %idx2, 3
  %gep2 = getelementptr i8, ptr %ptr, i64 %idx2.scaled
  %gep2.off = getelementptr i8, ptr %gep2, i64 -8
  %load2 = load double, ptr %gep2.off, align 8
  %idx3 = add i64 %arg1, %off3
  %idx3.scaled = shl i64 %idx3, 3
  %gep3 = getelementptr i8, ptr %ptr, i64 %idx3.scaled
  %gep3.off = getelementptr i8, ptr %gep3, i64 -8
  %load3 = load double, ptr %gep3.off, align 8
  %idx4 = add i64 %arg1, %iv
  %idx4.scaled = shl i64 %idx4, 3
  %gep4 = getelementptr i8, ptr %ptr, i64 %idx4.scaled
  %gep4.off = getelementptr i8, ptr %gep4, i64 -8
  %load4 = load double, ptr %gep4.off, align 8
  %load5 = load double, ptr %gep4, align 8
  br label %reduce

dead:
  br label %reduce

reduce:
  %phi0 = phi double [ %load0, %loop ], [ 0.000000e+00, %dead ]
  %phi1 = phi double [ %load1, %loop ], [ 0.000000e+00, %dead ]
  %phi2 = phi double [ %load2, %loop ], [ 0.000000e+00, %dead ]
  %phi3 = phi double [ %load3, %loop ], [ 0.000000e+00, %dead ]
  %phi4 = phi double [ %load4, %loop ], [ 0.000000e+00, %dead ]
  %phi5 = phi double [ %load5, %loop ], [ 0.000000e+00, %dead ]
  %min0 = call double @llvm.minimum.f64(double 0.000000e+00, double %phi0)
  %min1 = call double @llvm.minimum.f64(double %min0, double %phi1)
  %min2 = call double @llvm.minimum.f64(double %min1, double %phi2)
  %min3 = call double @llvm.minimum.f64(double %min2, double %phi3)
  %min4 = call double @llvm.minimum.f64(double %min3, double %phi4)
  %min5 = call double @llvm.minimum.f64(double %min4, double %phi5)
  %min6 = call double @llvm.minimum.f64(double %min5, double 0.000000e+00)
  %counter.next = add i64 %counter, 1
  %iv.next = add i64 %counter, %init
  br label %loop
}

declare double @llvm.minimum.f64(double, double)

```

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/llvm/llvm-project/issues/175768 
There are other unchecked uses std::optional in this pass but I couldn't figure out a test that triggers them

### CODE REVIEW

**Comment by gbaraldi** [comment]
I asked claude to help me a bit and it suggested 
```diff
diff --git a/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp b/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp
index d30d92e38d60..f59427bce9e6 100644
--- a/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp
+++ b/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp
@@ -7082,12 +7082,18 @@ bool BoUpSLP::analyzeConstantStrideCandidate(
     Value *Ptr0, Value *PtrN, StridedPtrInfo &SPtrInfo) const {
   const size_t Sz = PointerOps.size();
   SmallVector<int64_t> SortedOffsetsFromBase(Sz);
-  // Go through `PointerOps` in sorted order and record offsets from `Ptr0`.
+  // Go through `PointerOps` in sorted order and record offsets from
+  // PointerOps[0]. We use PointerOps[0] rather than Ptr0 because
+  // sortPtrAccesses only validates getPointersDiff for pairs relative to
+  // PointerOps[0]. This is safe since only offset differences are used below.
   for (unsigned I : seq<unsigned>(Sz)) {
     Value *Ptr =
         SortedIndices.empty() ? PointerOps[I] : PointerOps[SortedIndices[I]];
-    SortedOffsetsFromBase[I] =
-        *getPointersDiff(ScalarTy, Ptr0, ScalarTy, Ptr, *DL, *SE);
+    std::optional<int64_t> Offset =
+        getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, Ptr, *DL, *SE);
+    if (!Offset)
+      return false;
+    SortedOffsetsFromBase[I] = *Offset;
   }
 
   // The code below checks that `SortedOffsetsFromBase` looks as follows:
@@ -7436,11 +7442,22 @@ BoUpSLP::LoadsState BoUpSLP::canVectorizeLoads(
       Ptr0 = PointerOps[Order.front()];
       PtrN = PointerOps[Order.back()];
     }
-    std::optional<int64_t> Diff =
-        getPointersDiff(ScalarTy, Ptr0, ScalarTy, PtrN, *DL, *SE);
-    // Check that the sorted loads are consecutive.
+    // sortPtrAccesses validates getPointersDiff only for pairs relative to
+    // PointerOps[0]. When Order is non-empty, Ptr0 may differ from
+    // PointerOps[0], so we compute the span transitively:
+    //   Diff = offset(PtrN) - offset(Ptr0) relative to PointerOps[0]
+    std::optional<int64_t> Diff;
+    if (Order.empty()) {
+      Diff = getPointersDiff(ScalarTy, Ptr0, ScalarTy, PtrN, *DL, *SE);
+    } else {
+      auto Diff0 = getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, Ptr0, *DL, *SE);
+      auto DiffN = getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, PtrN, *DL, *SE);
+      if (Diff0 && DiffN)
+        Diff = *DiffN - *Diff0;
+    }
     if (!Diff)
       return LoadsState::Gather;
+    // Check that the sorted loads are consecutive.
     if (static_cast<uint64_t>(*Diff) == Sz - 1)
       return LoadsState::Vectorize;
     if (isMaskedLoadCompress(VL, PointerOps, Order, *TTI, *DL, *SE, *AC, *DT,
```

File: llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp [hunk 1]
```diff
@@ -7436,10 +7442,18 @@ BoUpSLP::LoadsState BoUpSLP::canVectorizeLoads(
...
-        getPointersDiff(ScalarTy, Ptr0, ScalarTy, PtrN, *DL, *SE);
+    // sortPtrAccesses validates getPointersDiff only for pairs relative to
+    // PointerOps[0]. Compute the span using PointerOps[0] as intermediate:
+    //   Diff = offset(PtrN) - offset(Ptr0) relative to PointerOps[0]
+    std::optional<int64_t> Diff0 =
+        getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, Ptr0, *DL, *SE);
+    std::optional<int64_t> DiffN =
+        getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, PtrN, *DL, *SE);
+    if (!Diff0 || !DiffN)
+      return LoadsState::Gather;
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp]: Why do we need this check if sortPtrAccesses already did this check?

File: llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp [hunk 2]
```diff
@@ -7436,10 +7442,16 @@ BoUpSLP::LoadsState BoUpSLP::canVectorizeLoads(
...
-    std::optional<int64_t> Diff =
-        getPointersDiff(ScalarTy, Ptr0, ScalarTy, PtrN, *DL, *SE);
+    // sortPtrAccesses validates getPointersDiff for all pointers relative to
+    // PointerOps[0], so compute the span using PointerOps[0] as intermediate:
+    //   Diff = offset(PtrN) - offset(Ptr0) relative to PointerOps[0]
+    std::optional<int64_t> Diff0 =
+        getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, Ptr0, *DL, *SE);
+    std::optional<int64_t> DiffN =
+        getPointersDiff(ScalarTy, PointerOps[0], ScalarTy, PtrN, *DL, *SE);
+    int64_t Diff = *DiffN - *Diff0;
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp]: I would add the assertion here that checks that DifN and Diff0 are set.

**Review by alexey-bataev — APPROVED** [review]
LG, thanks!
