### PR TITLE
[C23] Select the correct promoted type for a bit-field

### LINKED ISSUE #87641: Incorrect behavior when promoting bit-field of bit-precise type
Clang promotes to the incorrect type when applying integer promotions to bit-fields of bit-precise type, for example:
```c
#include<stdio.h>
int main(void){
	puts(_Generic(
		+(struct{unsigned _BitInt(7)x:2;}){}.x,
	 	unsigned _BitInt(2):"A",unsigned _BitInt(7):"B",int:"C"
	));
}
```
This program should output "B", but clang outputs "C".
> The value from a bit-field of a bit-precise integer type is converted to the corresponding bit-precise
integer type. If the original type is not a bit-precise integer type (6.2.5): if an int can represent all
values of the original type (as restricted by the width, for a bit-field), the value is converted to an
int; otherwise, it is converted to an unsigned int. These are called the integer promotions. All
other types are unchanged by the integer promotions
>
> (footnote) E.g. unsigned _BitInt(7): 2 is a bit-field that can hold the values 0, 1, 2, 3, and converts to unsigned _BitInt(7).

The promoted type of `unsigned _BitInt(7)x:2` isn't `int`, it should be `unsigned _BitInt(7)` as the footnote says.

### PR DESCRIPTION
**Pull request by AaronBallman**
Bit-fields of bit-precise integer type do not promote to int, but instead promote to the type of the field.

Fixes #87641

### CODE REVIEW

**Comment by AaronBallman** [comment]
@tbaederr -- this triggers an assertion with the new constexpr interpreter in `clang/test/AST/Interp/intap.cpp` but I'm not certain I understand why. Can you help me figure out how to fix that?

**Comment by tbaederr** [comment]
> @tbaederr -- this triggers an assertion with the new constexpr interpreter in `clang/test/AST/Interp/intap.cpp` but I'm not certain I understand why. Can you help me figure out how to fix that?
> 
> https://buildkite.com/llvm-project/github-pull-requests/builds/56785#018ef1ee-1e9c-48be-8944-0bce2c6f441d/6-1940

In `IntegralAP::truncate()` (which we call when getting the `3` and setting it as the value of the bitfield), we actually truncate the bitwith of the underlying `IntAP`, not just the _value_.

This fixes things for me:
```diff
diff --git a/clang/lib/AST/Interp/IntegralAP.h b/clang/lib/AST/Interp/IntegralAP.h
index bab9774288bf..fb7ee1451571 100644
--- a/clang/lib/AST/Interp/IntegralAP.h
+++ b/clang/lib/AST/Interp/IntegralAP.h
@@ -154,7 +154,10 @@ public:
   }

   IntegralAP truncate(unsigned BitWidth) const {
-    return IntegralAP(V.trunc(BitWidth));
+    if constexpr (Signed)
+      return IntegralAP(V.trunc(BitWidth).sextOrTrunc(this->bitWidth()));
+    else
+      return IntegralAP(V.trunc(BitWidth).zextOrTrunc(this->bitWidth()));
   }

   IntegralAP<false> toUnsigned() const {
```
I'd push this (it doesn't break any existing tests), but I'm not 100% sure if this is the right way to do that. Also, I should follow up with a `truncate` -> `truncateValue` rename.

**Comment by AaronBallman** [comment]
> > @tbaederr -- this triggers an assertion with the new constexpr interpreter in `clang/test/AST/Interp/intap.cpp` but I'm not certain I understand why. Can you help me figure out how to fix that?
> > https://buildkite.com/llvm-project/github-pull-requests/builds/56785#018ef1ee-1e9c-48be-8944-0bce2c6f441d/6-1940
> 
> In `IntegralAP::truncate()` (which we call when getting the `3` and setting it as the value of the bitfield), we actually truncate the bitwith of the underlying `IntAP`, not just the _value_.
> 
> This fixes things for me:
> 
> ```diff
> diff --git a/clang/lib/AST/Interp/IntegralAP.h b/clang/lib/AST/Interp/IntegralAP.h
> index bab9774288bf..fb7ee1451571 100644
> --- a/clang/lib/AST/Interp/IntegralAP.h
> +++ b/clang/lib/AST/Interp/IntegralAP.h
> @@ -154,7 +154,10 @@ public:
>    }
> 
>    IntegralAP truncate(unsigned BitWidth) const {
> -    return IntegralAP(V.trunc(BitWidth));
> +    if constexpr (Signed)
> +      return IntegralAP(V.trunc(BitWidth).sextOrTrunc(this->bitWidth()));
> +    else
> +      return IntegralAP(V.trunc(BitWidth).zextOrTrunc(this->bitWidth()));
>    }
> 
>    IntegralAP<false> toUnsigned() const {
> ```
> 
> I'd push this (it doesn't break any existing tests), but I'm not 100% sure if this is the right way to do that. Also, I should follow up with a `truncate` -> `truncateValue` rename.

Thank you for the help, that does pass all the tests, so I've added a commit for it.

File: clang/test/Sema/bitint-bitfield-promote.c [hunk 1]
```diff
@@ -0,0 +1,38 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c23 %s
+
+// GH87641 noticed that integer promotion of a bit-field of bit-precise integer
+// type was promoting to int rather than the type of the bit-field.
+struct S {
+  unsigned _BitInt(7) x : 2;
+  unsigned _BitInt(2) y : 2;
+  unsigned _BitInt(72) z : 28;
```
Comment (Sirraide) [inline clang/test/Sema/bitint-bitfield-promote.c:8]: Is there a reason all of these are unsigned? Maybe adding some tests for signed `_BitInt`s as well might be a good idea—or do we have those already?

**Review by Sirraide — APPROVED** [review]
Just one comment but LGTM otherwise.

File: clang/test/Sema/bitint-bitfield-promote.c (hunk 1 above)
Comment (erichkeane) [reply clang/test/Sema/bitint-bitfield-promote.c:8]: Wouldn't mind a 31 and a 33 as well.

**Review by erichkeane — APPROVED** [review]
This change looks right to me!   I don't know if there is value in a signed-test instead of unsigned, but a couple more tests might be nice anyway.

File: clang/test/Sema/bitint-bitfield-promote.c (hunk 1 above)
Comment (AaronBallman) [reply clang/test/Sema/bitint-bitfield-promote.c:8]: Sure, I can add some signed tests with different boundaries!
