### PR TITLE
[RISCV] Explicitly set FRM defs as non-dead to prevent their reordering with instructions that may use it

### LINKED ISSUE #135172: [RISC-V] MachineLICM incorrectly hoists fsrmi out of loop
**Godbolt example:** https://godbolt.org/z/h9rc5xrMj

Here we have two fsrmi instructions setting different dynamic rounding modes that are used in subsequent fadd operations. However, MachineLICM hoists them out of loop, leading to an incorrect result. After some investigation, looks like it's caused by implicit-def $frm in WriteFRMImm marked as dead (despite of its use in next FADD_D). so MachineLICM treats WriteFRMImm as a valid candidate. This IR inconsistency happens due to the fact that `RISCVTargetLowering::AdjustInstrPostInstrSelection` hook (which adds implicit frm uses) is called after instruction emission, so EmitNode correctly sets $frm def as dead (because at this stage there are no $frm uses), but after AdjustInstrPostInstrSelection "dead" flag is not updated.

### PR DESCRIPTION
**Pull request by skachkov-llvm**
Fixes #135172. The proposed solution is to conservatively reset dead flag from all $frm defs in AdjustInstrPostInstrSelection (this is probably a bit hacky, so I'm open to the better ideas)

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -20926,6 +20926,15 @@ RISCVTargetLowering::EmitInstrWithCustomInserter(MachineInstr &MI,
 
 void RISCVTargetLowering::AdjustInstrPostInstrSelection(MachineInstr &MI,
                                                         SDNode *Node) const {
+  // If instruction defines FRM operand, conservatively set it as non-dead to
+  // express data dependency with FRM users and prevent incorrect instruction
+  // reordering (these defs are marked as dead because at the moment of
+  // instruction emission they actually don't have any uses - they are added
+  // later in this hook).
```
Comment (topperc) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:20933]: I don't think the code in InstrEmitter that controls the setting of the dead flag would see them even if they were done earlier. It only checks glued nodes or explicit data dependencies. Neither apply to the input case.

**Comment by topperc** [comment]
I think we might need a bigger hammer. This case also hoists but we don't need if @foo uses FRM or changes FRM.

```
define double @bar(double %0, double %1, i64 %n) strictfp {                      
entry:                                                                           
    br label %loop                                                               
loop:                                                                            
    %cnt = phi i64 [0, %entry], [%cnt_inc, %loop]                                
    %acc = phi double [0.0, %entry], [%f2, %loop]                                
    call void @llvm.set.rounding(i32 2) strictfp                                 
    %f1 = call double @foo(double %acc, double %0) strictfp                      
    call void @llvm.set.rounding(i32 1) strictfp                                 
    %f2 = call double @foo(double %f1, double %1) strictfp                       
    %cnt_inc = add i64 %cnt, 1                                                   
    %cond = icmp eq i64 %cnt_inc, %n                                             
    br i1 %cond, label %loop, label %exit                                        
exit:                                                                            
    ret double %f2                                                               
}                                                                                
                                                                                 
declare double @foo(double, double)
```

**Comment by topperc** [comment]
> I think we might need a bigger hammer. This case also hoists but we don't need if @foo uses FRM or changes FRM.
> 
> ```
> define double @bar(double %0, double %1, i64 %n) strictfp {                      
> entry:                                                                           
>     br label %loop                                                               
> loop:                                                                            
>     %cnt = phi i64 [0, %entry], [%cnt_inc, %loop]                                
>     %acc = phi double [0.0, %entry], [%f2, %loop]                                
>     call void @llvm.set.rounding(i32 2) strictfp                                 
>     %f1 = call double @foo(double %acc, double %0) strictfp                      
>     call void @llvm.set.rounding(i32 1) strictfp                                 
>     %f2 = call double @foo(double %f1, double %1) strictfp                       
>     %cnt_inc = add i64 %cnt, 1                                                   
>     %cond = icmp eq i64 %cnt_inc, %n                                             
>     br i1 %cond, label %loop, label %exit                                        
> exit:                                                                            
>     ret double %f2                                                               
> }                                                                                
>                                                                                  
> declare double @foo(double, double)
> ```

Looks like this patch fixes this test case too.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by skachkov-sc** [comment]
> I think we might need a bigger hammer. This case also hoists but we don't need if @foo uses FRM or changes FRM.
> 
> ```
> define double @bar(double %0, double %1, i64 %n) strictfp {                      
> entry:                                                                           
>     br label %loop                                                               
> loop:                                                                            
>     %cnt = phi i64 [0, %entry], [%cnt_inc, %loop]                                
>     %acc = phi double [0.0, %entry], [%f2, %loop]                                
>     call void @llvm.set.rounding(i32 2) strictfp                                 
>     %f1 = call double @foo(double %acc, double %0) strictfp                      
>     call void @llvm.set.rounding(i32 1) strictfp                                 
>     %f2 = call double @foo(double %f1, double %1) strictfp                       
>     %cnt_inc = add i64 %cnt, 1                                                   
>     %cond = icmp eq i64 %cnt_inc, %n                                             
>     br i1 %cond, label %loop, label %exit                                        
> exit:                                                                            
>     ret double %f2                                                               
> }                                                                                
>                                                                                  
> declare double @foo(double, double)
> ```

Also added this test case
