### PR TITLE
[flang] Fold x + 0, 0 + x and x - 0 for INTEGER and UNSIGNED

### LINKED ISSUE #191928: [Flang][OpenMP] Flang does not accept `x = x + 0` as an update-statement in atomic capture constructs
## Summary

According to the OpenMP 6.0 specification, `x = x + 0` seems to be a valid *update-statement*. However, Flang rejects it within atomic capture constructs.

* 6.3.3 OpenMP Atomic Structured Blocks
> An update structured block is *update-statement*, an update statement that has one of the following forms:
>> x = x operator expr
>> x = expr operator x
>> x = intrinsic-procedure-name (x)
>> x = intrinsic-procedure-name (x, expr-list)
>> x = intrinsic-procedure-name (expr-list, x)

> A capture structured block has one of the following forms:
>> statement
>> capture-statement
>
> or
>> capture-statement
>> statement
>
> where *capture-statement* has either of the following forms:
>> v = x
>> v => x

### Reproducer

* test.f90

```fortran
k = 1
!$omp atomic capture
k = k + 0
n = k
!$omp end atomic
if (n /= 1) print *, 'err'
print *,'pass'
end
```

* commands

```console
$ flang --version
flang version 23.0.0git (https://github.com/llvm/llvm-project.git 5347264191e74840adc740db1aa41b7a9d33670a)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/llvm/build/bin
Build config: +assertions
$ flang test.f90 -fopenmp && ./a.out 
loc("/path/to/test.f90":2:7): error: expected three operations in atomic.capture region (one terminator, and two atomic ops)
error: Lowering to LLVM IR failed
loc("/path/to/test.f90":1:1): error: cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: func.func
error: failed to create the LLVM module
```

## Non-problematic Conditions

The issue does not occur under the following conditions:
* Replacing `capture` with `update`:
  ```fortran
  k = 1
  !$omp atomic update
  k = k + 0
  !$omp end atomic
  if (k /= 1) print *, 'err'
  print *,'pass'
  end
  ```

## Other Compilers

* GFortran
  ```console
  $ gfortran --version
  GNU Fortran (GCC) 15.2.0
  Copyright (C) 2025 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
  $ gfortran test.f90 -fopenmp && ./a.out
   pass
  ```

* Intel Fortran
  ```console
  $ ifx --version
  ifx (IFX) 2025.3.2 20260112
  Copyright (C) 1985-2026 Intel Corporation. All rights reserved.
  
  $ ifx -O0 test.f90 -qopenmp && ./a.out
   pass
  ```

### PR DESCRIPTION
**Pull request by kparzysz**
This fixes https://github.com/llvm/llvm-project/issues/191928.

### CODE REVIEW

**Review by eugeneepshteyn — APPROVED** [review]
LGTM.

@jeanPerier , do you happen to know why the zero additions weren't folded in the first place?

File: flang/lib/Evaluate/fold-implementation.h [hunk 1]
```diff
@@ -2018,6 +2018,25 @@ Expr<T> FoldOperation(FoldingContext &context, Add<T> &&x) {
       }
       return Expr<T>{Constant<T>{sum.value}};
     }
+  } else if constexpr (T::category == TypeCategory::Integer ||
+      T::category == TypeCategory::Unsigned) {
+    if (auto c{GetScalarConstantValue<T>(x.right())}) {
+      if (c->IsZero() && x.left().Rank() == 0) {
+        if (IsVariable(x.left())) {
+          return FoldOperation(context, Parentheses<T>{std::move(x.left())});
+        } else {
```
Comment (lakechd) [inline flang/lib/Evaluate/fold-implementation.h:2027]: else if  !IsVariable(x.right())

Comment (clementval) [reply flang/lib/Evaluate/fold-implementation.h:2027]: This look like a bot account that comment on many pull request.

Comment (kparzysz) [reply flang/lib/Evaluate/fold-implementation.h:2027]: I reported it.  I'm not sure if anything will come of it.
