### PR TITLE
[Clang][AST] Fix MS Mangle concept uneval context template instantiation crash

### LINKED ISSUE #115990: clang-19 cannot mangle what clang-17 mangles
I updated the clang version from 17 to 19 on windows and now i get error:
```
error: cannot mangle this template type parameter type yet
```
(no additional info provided)

### PR DESCRIPTION
**Pull request by MaxEW707**
Fixes https://github.com/llvm/llvm-project/issues/115990.

MSVC mangling got inadvertently broken here, https://github.com/llvm/llvm-project/pull/83997, when it was fixed what decl context a lambda is apart of for uneval contexts.

https://godbolt.org/z/K6jb5v145 for reference.

Given the following code snippet
```
template <typename T>
concept C = requires(const T& t)
{
    { T::test([](){}) };
};

template<typename T, typename = void>
struct Widget;

template <C T>
struct Widget<T> {};

struct Baz
{
    template<typename F>
    static constexpr decltype(auto) test(F&& f) {}
};

void test()
{
    Widget<Baz> w;
}
```
`Baz::test` has a deduced return type which means we must instantiate that template even in an unevaluated context.
The lambda inside the concept is within the decl context of `struct Widget<T> {};`. So we end up needing to mangle a name of `Baz::test<Widget<template-type-0-0>::lambda()>>()` since the lambda isn't apart of an instantiated substituted class `Widget` yet at the point the lambda is instantiated.

Upon template instantation of `test` we end up asking for the mangled name so we can add this instantiation to `CodeGenModule::DefferredDecls` since `test` is now referenced but not yet used.

I think the longer term more correct solution is to key `DefferedDecls` off of something else than the mangled name to avoid having to mangle names for instantations that are referenced but will never be used since they are only instantiated from an unevaluated context.

As a fix for the regression I just created a custom mangling scheme for this case since MSVC has no comparable naming scheme as such a template will never be emitted into the resulting obj as it will never be used.

Similarly the following case is also broken for our msvc compat, https://godbolt.org/z/evPo6KTfE, since we do not mangle `decltype(Expr)`. The Itanium ABI gets away with this as the entire `decltype(Expr)` expression must be mangled as is for that ABI.The MSVC ABI never mangles a decltype. Only the final canonical deduced type is mangled into the name so we never need to worry about mangling `decltype` except in the uneval context edge case.
I want to hold off fixing this case until I can see if I can come up with a better more holistic solution around `DefferedDecls` first. I'll get a github tracking issue created for it however.

If anyone has a better alternative to solve this let me know. I couldn't come up with one since the template instantation code path for uneval contexts takes the same code path as any template instantation and thus requires the ability to get back a mangled name for said template instantation.

### CODE REVIEW

File: clang/test/AST/ms-uneval-context-crash.cpp [hunk 1]
```diff
@@ -0,0 +1,25 @@
+// RUN: %clang_cc1 -std=c++20 -fms-compatibility -fms-compatibility-version=19.33 -emit-llvm %s -o - -triple=x86_64-windows-msvc | FileCheck %s
```
Comment (zmodem) [inline clang/test/AST/ms-uneval-context-crash.cpp:1]: I think doing codegen (-emit-llvm) in clang/test/AST/ is unusual, those tests normally just look at the AST (though there are exceptions). Maybe there is a better place for this?

File: clang/test/AST/ms-uneval-context-crash.cpp [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+{
+    template<typename F>
+    static constexpr decltype(auto) test(F&&) {}
+};
+
+void test()
+{
+    Widget<Baz> w;
+}
+// CHECK: @"?test@@YAXXZ"
```
Comment (zmodem) [inline clang/test/AST/ms-uneval-context-crash.cpp:25]: I suppose the mangling you're adding doesn't actually show up anywhere since it's only used for a concept? But then why do we need to mangle it in the first place?

Comment (efriedma-quic) [reply clang/test/AST/ms-uneval-context-crash.cpp:25]: Once we get to CodeGen, the method looks like a regular method, except for the fact that one of the template arguments is a class defined inside a concept instantiation.  And CodeGen doesn't have any way to check for "is a template argument a class defined inside a concept".  So, like all other methods, we stick it into DeferredDecls. And the key for the DeferredDecls map is the mangled name.

We end up trying to mangle a TemplateTypeParmType because we stick the instantiated class into the scope of an uninstantiated class template.

So no, we don't actually need to mangle it, but there's currently no way for CodeGen to check for this situation.

**Review by zmodem — APPROVED** [review]
The fix LGTM. I do wonder if the test should live in CodeGen/ instead, but I don't have a strong feeling about this (AST/ already seems to have some codegen tests).

File: clang/test/AST/ms-uneval-context-crash.cpp (hunk 2 above)
Comment (efriedma-quic) [reply clang/test/AST/ms-uneval-context-crash.cpp]: (If we wanted to, we could maybe encode this as a kind of linkage in clang/include/clang/Basic/Linkage.h .  It's sort of a variation of UniqueExternal: we have an entity with external linkage, but there are restrictions on which generated code can actually refer to it.  And the restriction propagates exactly the same way.)

Comment (MaxEW707) [reply clang/test/AST/ms-uneval-context-crash.cpp]: > (If we wanted to, we could maybe encode this as a kind of linkage in clang/include/clang/Basic/Linkage.h . It's sort of a variation of UniqueExternal: we have an entity with external linkage, but there are restrictions on which generated code can actually refer to it. And the restriction propagates exactly the same way.)

That is a neat idea from looking at `Linkage.h` and how it is used.
I am going to merge this PR for now if that is ok to fix the regression and then look at this alternative for a future PR. That area of the codebase is still new to me so I am going to take a bit of time to spelunk and better understand it.
