### PR TITLE
[LLVM][DAGCombiner] Fix size calculations in calculateByteProvider.

### LINKED ISSUE #148387: [AArch64] Invalid size request on a scalable vector
Compile this:

```
#include <algorithm>
int a;
extern short b[][1][1];
void c(int d[][1][1], short e[][1][1]) {
  for (int f;;)
    for (int g;; g += 3LL)
      if (d)
        for (int h; h < 2036854775797ULL; h += 4ULL)
          for (int i(-49); i < 10; i++) {
            b[h][g][g] = d[f][g][g] | std::min(0, d[0][f][g]);
            a = std::max((unsigned long long)e[0][1][1],
                         (unsigned long long)401598999);
          }
}
```

with `-Ofast -mcpu=grace` to get this error:

```
fatal error: error in backend: Invalid size request on a scalable vector.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -fno-verbose-asm -S -target aarch64-linux-gnu --gcc-toolchain=/opt/compiler-explorer/arm64/gcc-12.2.0/aarch64-unknown-linux-gnu --sysroot=/opt/compiler-explorer/arm64/gcc-12.2.0/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot -fcolor-diagnostics -fno-crash-diagnostics -Ofast -mcpu=grace <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'AArch64 Instruction Selection' on function '@_Z1cPA1_A1_iPA1_A1_s'
 #0 0x0000000003c7a1b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c7a1b8)
 #1 0x0000000003c77b8c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c77b8c)
 #2 0x0000000003bc83d3 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3bc83d3)
 #3 0x0000000003c6f3de llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c6f3de)
 #4 0x0000000000da499b LLVMErrorHandler(void*, char const*, bool) cc1_main.cpp:0:0
 #5 0x0000000003bd2303 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3bd2303)
 #6 0x0000000003bd2468 (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3bd2468)
 #7 0x0000000003c1f0cd (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c1f0cd)
 #8 0x0000000003c1f0ec llvm::TypeSize::operator unsigned long() const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c1f0ec)
 #9 0x000000000507170b calculateByteProvider(llvm::SDValue, unsigned int, unsigned int, std::optional<unsigned long>, unsigned int) DAGCombiner.cpp:0:0
#10 0x00000000050719c2 calculateByteProvider(llvm::SDValue, unsigned int, unsigned int, std::optional<unsigned long>, unsigned int) DAGCombiner.cpp:0:0
#11 0x0000000005071b25 calculateByteProvider(llvm::SDValue, unsigned int, unsigned int, std::optional<unsigned long>, unsigned int) DAGCombiner.cpp:0:0
#12 0x00000000050fb205 (anonymous namespace)::DAGCombiner::visitOR(llvm::SDNode*) DAGCombiner.cpp:0:0
#13 0x000000000511dc69 (anonymous namespace)::DAGCombiner::visit(llvm::SDNode*) DAGCombiner.cpp:0:0
#14 0x0000000005120825 (anonymous namespace)::DAGCombiner::combine(llvm::SDNode*) DAGCombiner.cpp:0:0
```

See also: https://godbolt.org/z/qTx87jfde

### PR DESCRIPTION
**Pull request by paulwalker-arm**
calculateByteProvider only cares about scalars or a single element within a vector. For the later there is the VectorIndex parameter to identify the element. All other properties, and specificially Index, are related to the underyling scalar type and thus when taking the size of a type it's the scalar size that matters.

Fixes https://github.com/llvm/llvm-project/issues/148387

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -9248,20 +9249,23 @@ calculateByteProvider(SDValue Op, unsigned Index, unsigned Depth,
     if (!L->isSimple() || L->isIndexed())
       return std::nullopt;
 
-    unsigned NarrowBitWidth = L->getMemoryVT().getSizeInBits();
-    if (NarrowBitWidth % 8 != 0)
+    TypeSize NarrowBitWidth = L->getMemoryVT().getSizeInBits();
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:9252]: Should this be getScalarSizeInBits? The code on line 9260 is trying to figure out if it is in the zero extended part of the load. That should be based on the scalar size not the full vector size.

Comment (paulwalker-arm) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:9252]: Yes, I guess I've taken the code too literally.  As long as `Index` is the byte index within a scalar, which looks to be the code based on the existing call sites, then I agree this should be using the MemoryVT's scalar size.

Comment (paulwalker-arm) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:9252]: Fixed.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 2]
```diff
@@ -9149,11 +9149,12 @@ calculateByteProvider(SDValue Op, unsigned Index, unsigned Depth,
...
-  unsigned BitWidth = Op.getValueSizeInBits();
-  if (BitWidth % 8 != 0)
+  TypeSize BitWidth = Op.getValueSizeInBits();
+  if (!BitWidth.isKnownMultipleOf(8))
     return std::nullopt;
-  unsigned ByteWidth = BitWidth / 8;
-  assert(Index < ByteWidth && "invalid index requested");
+  TypeSize ByteWidth = BitWidth.divideCoefficientBy(8);
+  assert(TypeSize::isKnownLT(TypeSize::getFixed(Index), ByteWidth) &&
+         "invalid index requested");
```
Comment (rj-jesus) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: Apologies if this is obvious, but is there a benefit to using TypeSize here rather than taking `BitWidth`'s `getKnownMinValue()`? (In case it isn't intentional, it also seems that `ByteWidth` may be implicitly converted to unsigned a few lines below in `case ISD::BSWAP`. Once again, I'm sorry if this is obvious and intentional.)

Comment (paulwalker-arm) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: In general `TypeSize` and `ElementCount` are the types to use when writing code that's portable across fixed and scalable types. `getKnownMinValue()` exists for those places where the preferred types cannot be used, which is often due to interfacing with existing code.

That said, after more investigation I believe `calculateByteProvider` doesn't really care about the size of the type but instead always wants the size of the scalar type because that is what `Index` will be used to index into. I've updated the PR accordingly.

Comment (rj-jesus) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: Thanks, that makes sense. I (incorrectly) assumed that `Index` was used to index into the vector, but it makes a lot more sense that the function actually only cares about the size of the scalar type. Thanks very much for the explanation! :)

**Comment by paulwalker-arm** [comment]
@arsenm - The PR has change direction, it's now much simpler, after you accepted it.  Do you mind taking another look to make sure you're still happy with it?

**Review by topperc — APPROVED** [review]
LGTM

**Review by arsenm — APPROVED** [review]
