### PR TITLE
[clang-format] Fix crash in TokenAnnotator

### LINKED ISSUE #82328: Crash when clang-format is used for incomplete file
The way to reproduce:
1) create a file test.cpp with the content
```
struct X{
    operator iunt(
};
```
2) run `clang-format-17 test.cpp` against it.
3) get a crash

Stack trace:
tack dump:
0.	Program arguments: clang-format-17 test_clang_format.cpp
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-17.so.1    0x00007f39f98cc406 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 54
1  libLLVM-17.so.1    0x00007f39f98ca5b0 llvm::sys::RunSignalHandlers() + 80
2  libLLVM-17.so.1    0x00007f39f98cca9b
3  libc.so.6          0x00007f39f8442520
4  libclang-cpp.so.17 0x00007f3a03308d03 clang::format::TokenAnnotator::calculateFormattingInformation(clang::format::AnnotatedLine&) const + 1411
5  libclang-cpp.so.17 0x00007f3a032d0bed
6  libclang-cpp.so.17 0x00007f3a03305366 clang::format::TokenAnalyzer::process(bool) + 1142
7  libclang-cpp.so.17 0x00007f3a032e0efd
8  libclang-cpp.so.17 0x00007f3a032c910a clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) + 2298
9  libclang-cpp.so.17 0x00007f3a032ca571 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) + 81
10 clang-format-17    0x0000559e7653e0d5
11 clang-format-17    0x0000559e7653cb54
12 libc.so.6          0x00007f39f8429d90
13 libc.so.6          0x00007f39f8429e40 __libc_start_main + 128
14 clang-format-17    0x0000559e76539d25
Segmentation fault (core dumped)

### PR DESCRIPTION
**Pull request by rymiel**
The while loop on line 3814 can cause a segmentation fault getting the Next field on a nullptr. This is because further down, on line 3823, there is another for loop, which assigns Tok to Tok->Next in its initializer. This for loop has a condition to check if the result of that isn't null. If it is, the loop is skipped and we drop back out to the outer loop, except, now Tok is null, and we try to dereference it without checking first.

This patch adds a defensive check that returns if Tok->Next is null before we make it to the second for loop.

Fixes https://github.com/llvm/llvm-project/issues/82328

### CODE REVIEW

**Review by mydeveloperday — APPROVED** [review]
LGTM

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -3817,7 +3817,7 @@ void TokenAnnotator::calculateFormattingInformation(AnnotatedLine &Line) const {
         do {
           Tok = Tok->Next;
         } while (Tok && Tok->isNot(TT_OverloadedOperatorLParen));
-        if (!Tok)
+        if (!Tok || !Tok->Next)
```
Comment (owenca) [inline clang/lib/Format/TokenAnnotator.cpp:3820]:
```suggestion
        if (!Tok || !Tok->MatchingParen)
```
Otherwise, it would still crash if the unmatched `l_paren` is not the last token on the line, e.g.:
```
struct Foo {
  operator foo(bar
};

File: clang/unittests/Format/FormatTest.cpp [hunk 2]
```diff
@@ -13503,6 +13503,9 @@ TEST_F(FormatTest, IncorrectCodeUnbalancedBraces) {
   verifyFormat("{");
   verifyFormat("#})");
   verifyNoCrash("(/**/[:!] ?[).");
+  verifyNoCrash("struct X{"
+                "  operator iunt("
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:13507]:
```suggestion
  verifyNoCrash("struct X {\n"
                "  operator iunt(\n"
```

**Review by owenca — APPROVED** [review]
