### PR TITLE
[clang analysis] ExprMutationAnalyzer avoid infinite recursion for recursive forwarding reference

### LINKED ISSUE #60895: [Clang-Tidy] `misc-const-correctness` crash due to seemingly infinite recursion
When trying to run our CI pipeline with Clang-Tidy 15, it segfaults.
Clang-Tidy 14 works fine.

```console
root@89c0c24c7e49:/# clang-tidy --version
Ubuntu LLVM version 15.0.6
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell
```

On Ubuntu 22.04.

```console
root@89c0c24c7e49:/# clang-tidy --extra-arg-before=--driver-mode=g++ /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx -- /usr/bin/clang++ -DBOOST_THREAD_VERSION=5 -DHYRISE_DEBUG=1 -DHYRISE_NUMA_SUPPORT=1 -DHYRISE_WITH_JEMALLOC -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -Dhyrise_impl_EXPORTS -I/hyrise/src/benchmarklib -I/hyrise/src/lib -I/hyrise/src/plugins -I/hyrise/clang-debug-tidy -I/hyrise/third_party/compact_vector/include -I/hyrise/third_party/lz4/lib -I/hyrise/third_party/magic_enum/include -I/hyrise/third_party/sql-parser/src -I/hyrise/third_party/uninitialized_vector -I/hyrise/third_party/zstd/lib -isystem /hyrise/clang-debug-tidy/src/lib/../../third_party/jemalloc/include -isystem /hyrise/third_party/cpp-btree/include/btree -isystem /hyrise/third_party/cxxopts/include -isystem /hyrise/third_party/flat_hash_map -isystem /hyrise/third_party/nlohmann_json/single_include -isystem /hyrise/third_party/robin-map/include -isystem /hyrise/third_party/sparse-map/include -g -fopenmp-simd -O0 -fPIC -DBOOST_ASIO_DISABLE_CONCEPTS -pthread -Wno-unknown-warning-option -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -Wno-dollar-in-identifier-extension -Wno-unknown-pragmas -Wno-subobject-linkage -Wno-deprecated-dynamic-exception-spec -Weverything -Wshadow-all -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-documentation -Wno-padded -Wno-global-constructors -Wno-sign-conversion -Wno-exit-time-destructors -Wno-switch-enum -Wno-weak-vtables -Wno-double-promotion -Wno-covered-switch-default -Wno-unused-macros -Wno-newline-eof -Wno-missing-variable-declarations -Wno-weak-template-vtables -Wno-missing-prototypes -Wno-float-equal -Wno-return-std-move-in-c++11 -Wno-unreachable-code-break -Wno-undefined-func-template -Wno-pass-failed -Wno-ctad-maybe-unsupported -Wno-header-hygiene -Wno-poison-system-directories -Wno-zero-as-null-pointer-constant -Xclang -fno-pch-timestamp -fPIC -Wno-cast-qual -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-shadow -Wno-reserved-id-macro -Wno-atomic-implicit-seq-cst -std=gnu++20 -Winvalid-pch -Xclang -include-pch -Xclang /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/cmake_pch.hxx -MD -MT src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o -MF CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o.d -o CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o -c /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-tidy --extra-arg-before=--driver-mode=g++ /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx -- /usr/bin/clang++ -DBOOST_THREAD_VERSION=5 -DHYRISE_DEBUG=1 -DHYRISE_NUMA_SUPPORT=1 -DHYRISE_WITH_JEMALLOC -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -Dhyrise_impl_EXPORTS -I/hyrise/src/benchmarklib -I/hyrise/src/lib -I/hyrise/src/plugins -I/hyrise/clang-debug-tidy -I/hyrise/third_party/compact_vector/include -I/hyrise/third_party/lz4/lib -I/hyrise/third_party/magic_enum/include -I/hyrise/third_party/sql-parser/src -I/hyrise/third_party/uninitialized_vector -I/hyrise/third_party/zstd/lib -isystem /hyrise/clang-debug-tidy/src/lib/../../third_party/jemalloc/include -isystem /hyrise/third_party/cpp-btree/include/btree -isystem /hyrise/third_party/cxxopts/include -isystem /hyrise/third_party/flat_hash_map -isystem /hyrise/third_party/nlohmann_json/single_include -isystem /hyrise/third_party/robin-map/include -isystem /hyrise/third_party/sparse-map/include -g -fopenmp-simd -O0 -fPIC -DBOOST_ASIO_DISABLE_CONCEPTS -pthread -Wno-unknown-warning-option -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -Wno-dollar-in-identifier-extension -Wno-unknown-pragmas -Wno-subobject-linkage -Wno-deprecated-dynamic-exception-spec -Weverything -Wshadow-all -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-documentation -Wno-padded -Wno-global-constructors -Wno-sign-conversion -Wno-exit-time-destructors -Wno-switch-enum -Wno-weak-vtables -Wno-double-promotion -Wno-covered-switch-default -Wno-unused-macros -Wno-newline-eof -Wno-missing-variable-declarations -Wno-weak-template-vtables -Wno-missing-prototypes -Wno-float-equal -Wno-return-std-move-in-c++11 -Wno-unreachable-code-break -Wno-undefined-func-template -Wno-pass-failed -Wno-ctad-maybe-unsupported -Wno-header-hygiene -Wno-poison-system-directories -Wno-zero-as-null-pointer-constant -Xclang -fno-pch-timestamp -fPIC -Wno-cast-qual -Wno-old-style-cast -Wno-shorten-64-to-32 -Wno-shadow -Wno-reserved-id-macro -Wno-atomic-implicit-seq-cst -std=gnu++20 -Winvalid-pch -Xclang -include-pch -Xclang /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/cmake_pch.hxx -MD -MT src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o -MF CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o.d -o CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx.o -c /hyrise/clang-debug-tidy/src/lib/CMakeFiles/hyrise_impl.dir/Unity/unity_10_cxx.cxx
1.	<eof> parser at end of file
2.	ASTMatcher: Processing 'misc-const-correctness' against:
	CXXMethodDecl ska::detailv8::sherwood_v8_table<std::pair<unsigned long, unsigned long>, unsigned long, std::hash<unsigned long>, ska::detailv3::KeyOrValueHasher<unsigned long, std::pair<unsigned long, unsigned long>, std::hash<unsigned long>>, std::equal_to<unsigned long>, ska::detailv3::KeyOrValueEquality<unsigned long, std::pair<unsigned long, unsigned long>, std::equal_to<unsigned long>>, boost::container::pmr::polymorphic_allocator<std::pair<const unsigned long, unsigned long>>, boost::container::pmr::polymorphic_allocator<unsigned char>, '\b'>::emplace_direct_hit : </hyrise/third_party/flat_hash_map/bytell_hash_map.hpp:861:5 <Spelling=col:18>, line:914:5>
--- Bound Nodes Begin ---
    decl-stmt - { DeclStmt : </hyrise/third_party/flat_hash_map/bytell_hash_map.hpp:885:13, col:62> }
    function-decl - { CXXMethodDecl ska::detailv8::sherwood_v8_table<std::pair<unsigned long, unsigned long>, unsigned long, std::hash<unsigned long>, ska::detailv3::KeyOrValueHasher<unsigned long, std::pair<unsigned long, unsigned long>, std::hash<unsigned long>>, std::equal_to<unsigned long>, ska::detailv3::KeyOrValueEquality<unsigned long, std::pair<unsigned long, unsigned long>, std::equal_to<unsigned long>>, boost::container::pmr::polymorphic_allocator<std::pair<const unsigned long, unsigned long>>, boost::container::pmr::polymorphic_allocator<unsigned char>, '\b'>::emplace_direct_hit : </hyrise/third_party/flat_hash_map/bytell_hash_map.hpp:861:5 <Spelling=col:18>, line:914:5> }
    local-value - { VarDecl new_value : </hyrise/third_party/flat_hash_map/bytell_hash_map.hpp:885:13, col:61> }
    scope - { CompoundStmt : </hyrise/third_party/flat_hash_map/bytell_hash_map.hpp:862:5, line:914:5> }
--- Bound Nodes End ---
  #0 0x00007f044af433b1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xf043b1)
  #1 0x00007f044af410fe llvm::sys::RunSignalHandlers() (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xf020fe)
  #2 0x00007f044af438d6 (/usr/lib/llvm-15/bin/../lib/libLLVM-15.so.1+0xf048d6)
  #3 0x00007f0449b1c520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
  #4 0x0000560ad7e72311 clang::ast_matchers::internal::BindableMatcher<clang::ImplicitCastExpr> clang::ast_matchers::internal::makeAllOfComposite<clang::ImplicitCastExpr>(llvm::ArrayRef<clang::ast_matchers::internal::Matcher<clang::ImplicitCastExpr> const*>) (/usr/lib/llvm-15/bin/clang-tidy+0x79c311)
  #5 0x0000560ad7f847a0 (/usr/lib/llvm-15/bin/clang-tidy+0x8ae7a0)
  #6 0x0000560ad848100c (/usr/lib/llvm-15/bin/clang-tidy+0xdab00c)
  #7 0x0000560ad848081b (/usr/lib/llvm-15/bin/clang-tidy+0xdaa81b)
  #8 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
  #9 0x0000560ad84ec4db (/usr/lib/llvm-15/bin/clang-tidy+0xe164db)
 #10 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #11 0x0000560ad82f82a2 clang::ast_matchers::internal::matcher_forEachArgumentWithParamType0Matcher<clang::CallExpr, clang::ast_matchers::internal::Matcher<clang::Expr>, clang::ast_matchers::internal::Matcher<clang::QualType> >::matches(clang::CallExpr const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xc222a2)
 #12 0x0000560ad84e920a clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1320a)
 #13 0x0000560ad84ec305 (/usr/lib/llvm-15/bin/clang-tidy+0xe16305)
 #14 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #15 0x0000560ad84ec4db (/usr/lib/llvm-15/bin/clang-tidy+0xe164db)
 #16 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #17 0x0000560ad84ec4db (/usr/lib/llvm-15/bin/clang-tidy+0xe164db)
 #18 0x0000560ad84ebaab (/usr/lib/llvm-15/bin/clang-tidy+0xe15aab)
 #19 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #20 0x0000560ad8492955 (/usr/lib/llvm-15/bin/clang-tidy+0xdbc955)
 #21 0x0000560ad8491fa6 (/usr/lib/llvm-15/bin/clang-tidy+0xdbbfa6)
 #22 0x0000560ad849cbab (/usr/lib/llvm-15/bin/clang-tidy+0xdc6bab)
 #23 0x0000560ad8493f5b (/usr/lib/llvm-15/bin/clang-tidy+0xdbdf5b)
 #24 0x0000560ad8491fb8 (/usr/lib/llvm-15/bin/clang-tidy+0xdbbfb8)
 #25 0x0000560ad8494dbb (/usr/lib/llvm-15/bin/clang-tidy+0xdbedbb)
 #26 0x0000560ad8492be4 (/usr/lib/llvm-15/bin/clang-tidy+0xdbcbe4)
 #27 0x0000560ad8489739 (/usr/lib/llvm-15/bin/clang-tidy+0xdb3739)
 #28 0x0000560ad84892bf (/usr/lib/llvm-15/bin/clang-tidy+0xdb32bf)
 #29 0x0000560ad8487f06 (/usr/lib/llvm-15/bin/clang-tidy+0xdb1f06)
 #30 0x0000560ad7ea9cde (/usr/lib/llvm-15/bin/clang-tidy+0x7d3cde)
 #31 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #32 0x0000560ad84ec787 (/usr/lib/llvm-15/bin/clang-tidy+0xe16787)
 #33 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #34 0x0000560ad7e7278d (/usr/lib/llvm-15/bin/clang-tidy+0x79c78d)
 #35 0x0000560ad84e909e clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/usr/lib/llvm-15/bin/clang-tidy+0xe1309e)
 #36 0x0000560ad84b49c5 (/usr/lib/llvm-15/bin/clang-tidy+0xdde9c5)
 #37 0x0000560ad8486ce6 clang::ast_matchers::MatchFinder::match(clang::DynTypedNode const&, clang::ASTContext&) (/usr/lib/llvm-15/bin/clang-tidy+0xdb0ce6)
 #38 0x0000560ad7e7c879 llvm::SmallVector<clang::ast_matchers::BoundNodes, 1u> clang::ast_matchers::match<clang::ast_matchers::internal::Matcher<clang::Stmt> >(clang::ast_matchers::internal::Matcher<clang::Stmt>, clang::DynTypedNode const&, clang::ASTContext&) (/usr/lib/llvm-15/bin/clang-tidy+0x7a6879)
 #39 0x0000560ad8472ddd clang::ExprMutationAnalyzer::findDirectMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9cddd)
 #40 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #41 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #42 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #43 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #44 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #45 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #46 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #47 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #48 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #49 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #50 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #51 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #52 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #53 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #54 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #55 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #56 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #57 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #58 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #59 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #60 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #61 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #62 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #63 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #64 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #65 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #66 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #67 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #68 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #69 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #70 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #71 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #72 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #73 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #74 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #75 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #76 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #77 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #78 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #79 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #80 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #81 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #82 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #83 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #84 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #85 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #86 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #87 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #88 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #89 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #90 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #91 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #92 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
 #93 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
 #94 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #95 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
 #96 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
 #97 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
 #98 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
 #99 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#100 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#101 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#102 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#103 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#104 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#105 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#106 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#107 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#108 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#109 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#110 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#111 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#112 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#113 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#114 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#115 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#116 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#117 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#118 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#119 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#120 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#121 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#122 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#123 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#124 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#125 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#126 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#127 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#128 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#129 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#130 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#131 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#132 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#133 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#134 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#135 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#136 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#137 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#138 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#139 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#140 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#141 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#142 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#143 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#144 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#145 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#146 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#147 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#148 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#149 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#150 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#151 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#152 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#153 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#154 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#155 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#156 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#157 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#158 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#159 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#160 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#161 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#162 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#163 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#164 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#165 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#166 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#167 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#168 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#169 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#170 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#171 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#172 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#173 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#174 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#175 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#176 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#177 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#178 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#179 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#180 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#181 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#182 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#183 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#184 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#185 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#186 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#187 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#188 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#189 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#190 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#191 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#192 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#193 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#194 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#195 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#196 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#197 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#198 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#199 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#200 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#201 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#202 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#203 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#204 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#205 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#206 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#207 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#208 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#209 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#210 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#211 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#212 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#213 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#214 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#215 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#216 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#217 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#218 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#219 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#220 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#221 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#222 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#223 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#224 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#225 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#226 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#227 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#228 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#229 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#230 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#231 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#232 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#233 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#234 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#235 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#236 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#237 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#238 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#239 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#240 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#241 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#242 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#243 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#244 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#245 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#246 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#247 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#248 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#249 0x0000560ad8475b01 clang::ExprMutationAnalyzer::findCastMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd9fb01)
#250 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
#251 0x0000560ad846dff6 clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xd97ff6)
#252 0x0000560ad847b79c clang::ExprMutationAnalyzer::tryEachDeclRef(clang::Decl const*, clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)) (/usr/lib/llvm-15/bin/clang-tidy+0xda579c)
#253 0x0000560ad847f99e clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda999e)
#254 0x0000560ad847b2a4 clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) (/usr/lib/llvm-15/bin/clang-tidy+0xda52a4)
#255 0x0000560ad846e17d clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*> >&) (/usr/lib/llvm-15/bin/clang-tidy+0xd9817d)
Segmentation fault (core dumped)
root@89c0c24c7e49:/#
```

### PR DESCRIPTION
**Pull request by HerrCai0907**
Partialy fixes: #60895

### CODE REVIEW

File: clang/include/clang/Analysis/Analyses/ExprMutationAnalyzer.h [hunk 1]
```diff
@@ -22,8 +21,15 @@ class FunctionParmMutationAnalyzer;
 /// a given statement.
 class ExprMutationAnalyzer {
 public:
+  friend class FunctionParmMutationAnalyzer;
+  struct Cache {
+    llvm::DenseMap<const FunctionDecl *,
```
Comment (PiotrZSL) [inline clang/include/clang/Analysis/Analyses/ExprMutationAnalyzer.h:26]: Note: consider using llvm::SmallDenseMap, to reduce amount of memory allocations.

**Review by PiotrZSL — APPROVED** [review]
LGTM

**Comment by fmayer** [comment]
This broke the sanitizer bots, e.g. https://lab.llvm.org/buildbot/#/builders/239/builds/6587/steps/10/logs/stdio

```
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ExprMutationAnalyzerTest
[ RUN      ] ExprMutationAnalyzerTest.UnresolvedOperator
[       OK ] ExprMutationAnalyzerTest.UnresolvedOperator (59 ms)
[ RUN      ] ExprMutationAnalyzerTest.ReproduceFailureMinimal
input.cc:1:166: warning: unqualified call to 'std::forward' [-Wunqualified-std-cast-call]
    1 | namespace std {template <class T> T &forward(T &A) { return static_cast<T&&>(A); }template <class T> struct __bind {  T f;  template <class V> __bind(T v, V &&) : f(forward(v)) {}};}void f() {  int x = 42;  auto Lambda = [] {};  std::__bind<decltype(Lambda)>(Lambda, x);}
      |                                                                                                                                                                      ^
      |                                                                                                                                                                      std::
input.cc:1:230: note: in instantiation of function template specialization 'std::__bind<(lambda at input.cc:1:222)>::__bind<int &>' requested here
    1 | namespace std {template <class T> T &forward(T &A) { return static_cast<T&&>(A); }template <class T> struct __bind {  T f;  template <class V> __bind(T v, V &&) : f(forward(v)) {}};}void f() {  int x = 42;  auto Lambda = [] {};  std::__bind<decltype(Lambda)>(Lambda, x);}
      |                                                                                                                                                                                                                                      ^
[       OK ] ExprMutationAnalyzerTest.ReproduceFailureMinimal (46 ms)
[----------] 2 tests from ExprMutationAnalyzerTest (106 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (107 ms total)
[  PASSED  ] 2 tests.
=================================================================
==946027==ERROR: LeakSanitizer: detected memory leaks
Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0xaaaac90ddce4 in operator new(unsigned long, std::align_val_t) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #1 0xaaaaca15f590 in allocateBuckets /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:899:9
    #2 0xaaaaca15f590 in llvm::DenseMap<clang::ParmVarDecl const*, clang::Stmt const*, llvm::DenseMapInfo<clang::ParmVarDecl const*, void>, llvm::detail::DenseMapPair<clang::ParmVarDecl const*, clang::Stmt const*>>::grow(unsigned int) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:833:5
    #3 0xaaaaca15f428 in grow /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:564:36
    #4 0xaaaaca15f428 in InsertIntoBucketImpl<const clang::ParmVarDecl *> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h
    #5 0xaaaaca15f428 in llvm::detail::DenseMapPair<clang::ParmVarDecl const*, clang::Stmt const*>* llvm::DenseMapBase<llvm::DenseMap<clang::ParmVarDecl const*, clang::Stmt const*, llvm::DenseMapInfo<clang::ParmVarDecl const*, void>, llvm::detail::DenseMapPair<clang::ParmVarDecl const*, clang::Stmt const*>>, clang::ParmVarDecl const*, clang::Stmt const*, llvm::DenseMapInfo<clang::ParmVarDecl const*, void>, llvm::detail::DenseMapPair<clang::ParmVarDecl const*, clang::Stmt const*>>::InsertIntoBucket<clang::ParmVarDecl const* const&>(llvm::detail::DenseMapPair<clang::ParmVarDecl const*, clang::Stmt const*>*, clang::ParmVarDecl const* const&) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:574:17
    #6 0xaaaaca104ee8 in FindAndConstruct /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:353:13
    #7 0xaaaaca104ee8 in operator[] /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/DenseMap.h:357:12
    #8 0xaaaaca104ee8 in clang::FunctionParmMutationAnalyzer::findMutation(clang::ParmVarDecl const*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:685:3
    #9 0xaaaaca0f64d4 in clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:645:23
    #10 0xaaaaca0d5b30 in clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*>>&) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:237:25
    #11 0xaaaaca0d5864 in clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:203:10
    #12 0xaaaac9176f08 in isMutated /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/include/clang/Analysis/Analyses/ExprMutationAnalyzer.h:34:44
    #13 0xaaaac9176f08 in clang::(anonymous namespace)::isMutated(llvm::SmallVectorImpl<clang::ast_matchers::BoundNodes> const&, clang::ASTUnit*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:57:57
    #14 0xaaaac91c2980 in clang::ExprMutationAnalyzerTest_ReproduceFailureMinimal_Test::TestBody() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:1588:3
    #15 0xaaaac93abff8 in HandleExceptionsInMethodIfSupported<testing::Test, void> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #16 0xaaaac93abff8 in testing::Test::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2687:5
    #17 0xaaaac93ae3b8 in testing::TestInfo::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2836:11
    #18 0xaaaac93afc88 in testing::TestSuite::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:3015:30
    #19 0xaaaac93d0038 in testing::internal::UnitTestImpl::RunAllTests() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5920:44
    #20 0xaaaac93ce870 in HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #21 0xaaaac93ce870 in testing::UnitTest::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5484:10
    #22 0xaaaac938e498 in RUN_ALL_TESTS /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/include/gtest/gtest.h:2317:73
    #23 0xaaaac938e498 in main /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/UnitTestMain/TestMain.cpp:55:10
    #24 0xffff96327580  (/lib/aarch64-linux-gnu/libc.so.6+0x27580) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #25 0xffff96327654 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x27654) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #26 0xaaaac900b6ac in _start (/b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm_build_asan/tools/clang/unittests/Analysis/ClangAnalysisTests+0x240b6ac)
Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0xaaaac90dd8c4 in operator new(unsigned long) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
    #1 0xaaaaca0f64f8 in clang::ExprMutationAnalyzer::findFunctionArgMutation(clang::Expr const*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:643:26
    #2 0xaaaaca0d5b30 in clang::ExprMutationAnalyzer::findMutationMemoized(clang::Expr const*, llvm::ArrayRef<clang::Stmt const* (clang::ExprMutationAnalyzer::*)(clang::Expr const*)>, llvm::DenseMap<clang::Expr const*, clang::Stmt const*, llvm::DenseMapInfo<clang::Expr const*, void>, llvm::detail::DenseMapPair<clang::Expr const*, clang::Stmt const*>>&) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:237:25
    #3 0xaaaaca0d5864 in clang::ExprMutationAnalyzer::findMutation(clang::Expr const*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/lib/Analysis/ExprMutationAnalyzer.cpp:203:10
    #4 0xaaaac9176f08 in isMutated /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/include/clang/Analysis/Analyses/ExprMutationAnalyzer.h:34:44
    #5 0xaaaac9176f08 in clang::(anonymous namespace)::isMutated(llvm::SmallVectorImpl<clang::ast_matchers::BoundNodes> const&, clang::ASTUnit*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:57:57
    #6 0xaaaac91c2980 in clang::ExprMutationAnalyzerTest_ReproduceFailureMinimal_Test::TestBody() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:1588:3
    #7 0xaaaac93abff8 in HandleExceptionsInMethodIfSupported<testing::Test, void> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #8 0xaaaac93abff8 in testing::Test::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2687:5
    #9 0xaaaac93ae3b8 in testing::TestInfo::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2836:11
    #10 0xaaaac93afc88 in testing::TestSuite::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:3015:30
    #11 0xaaaac93d0038 in testing::internal::UnitTestImpl::RunAllTests() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5920:44
    #12 0xaaaac93ce870 in HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #13 0xaaaac93ce870 in testing::UnitTest::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5484:10
    #14 0xaaaac938e498 in RUN_ALL_TESTS /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/include/gtest/gtest.h:2317:73
    #15 0xaaaac938e498 in main /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/UnitTestMain/TestMain.cpp:55:10
    #16 0xffff96327580  (/lib/aarch64-linux-gnu/libc.so.6+0x27580) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #17 0xffff96327654 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x27654) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #18 0xaaaac900b6ac in _start (/b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm_build_asan/tools/clang/unittests/Analysis/ClangAnalysisTests+0x240b6ac)
Indirect leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0xaaaac90dd8c4 in operator new(unsigned long) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
    #1 0xaaaac9176e10 in __libcpp_operator_new<unsigned long> /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/new:270:10
    #2 0xaaaac9176e10 in __libcpp_allocate /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/new:294:10
    #3 0xaaaac9176e10 in allocate /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator.h:119:32
    #4 0xaaaac9176e10 in allocate /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator_traits.h:280:16
    #5 0xaaaac9176e10 in __allocation_guard<std::__1::allocator<clang::ExprMutationAnalyzer::Cache> > /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocation_guard.h:56:16
    #6 0xaaaac9176e10 in allocate_shared<clang::ExprMutationAnalyzer::Cache, std::__1::allocator<clang::ExprMutationAnalyzer::Cache>, 0> /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/shared_ptr.h:824:46
    #7 0xaaaac9176e10 in make_shared<clang::ExprMutationAnalyzer::Cache, 0> /b/sanitizer-aarch64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/shared_ptr.h:833:10
    #8 0xaaaac9176e10 in ExprMutationAnalyzer /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/include/clang/Analysis/Analyses/ExprMutationAnalyzer.h:32:44
    #9 0xaaaac9176e10 in clang::(anonymous namespace)::isMutated(llvm::SmallVectorImpl<clang::ast_matchers::BoundNodes> const&, clang::ASTUnit*) /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:57:10
    #10 0xaaaac91c2980 in clang::ExprMutationAnalyzerTest_ReproduceFailureMinimal_Test::TestBody() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/clang/unittests/Analysis/ExprMutationAnalyzerTest.cpp:1588:3
    #11 0xaaaac93abff8 in HandleExceptionsInMethodIfSupported<testing::Test, void> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #12 0xaaaac93abff8 in testing::Test::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2687:5
    #13 0xaaaac93ae3b8 in testing::TestInfo::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:2836:11
    #14 0xaaaac93afc88 in testing::TestSuite::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:3015:30
    #15 0xaaaac93d0038 in testing::internal::UnitTestImpl::RunAllTests() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5920:44
    #16 0xaaaac93ce870 in HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc
    #17 0xaaaac93ce870 in testing::UnitTest::Run() /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/src/gtest.cc:5484:10
    #18 0xaaaac938e498 in RUN_ALL_TESTS /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/googletest/include/gtest/gtest.h:2317:73
    #19 0xaaaac938e498 in main /b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm-project/third-party/unittest/UnitTestMain/TestMain.cpp:55:10
    #20 0xffff96327580  (/lib/aarch64-linux-gnu/libc.so.6+0x27580) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #21 0xffff96327654 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x27654) (BuildId: b9b95c4f6e0feae95b758633cb6a2881fa8eac30)
    #22 0xaaaac900b6ac in _start (/b/sanitizer-aarch64-linux-bootstrap-asan/build/llvm_build_asan/tools/clang/unittests/Analysis/ClangAnalysisTests+0x240b6ac)
SUMMARY: AddressSanitizer: 1256 byte(s) leaked in 3 allocation(s).
--
exit: 1
--

```
