### PR TITLE
[Clang] Bugfixes and improved support for `AttributedType`s in lambdas

### LINKED ISSUE #85120: [Clang] `AttributedType`s are stripped from lambda function types
Consider
```c++
struct S {
  void g() const [[clang::annotate_type("foo", "bar", 1)]] {}
};

void f() {
  auto l = [] () [[clang::annotate_type("foo", "bar", 1)]] {};
}
```

AST dump prints `'void () const [[clang::annotate_type(...)]]':'void () const'` for the type of `S::g()`, but `void () const` for the type of `l`, which is problematic if someone actually wants to use this information for something (#84983). We should fix this unless there’s a good reason why we’re desugaring the function type here.

### LINKED ISSUE #85154: [Clang] Crash instantiating a dependent lambda annotated with `annotate_type`
This crashes when we try to instantiate the lambda:
```c++
template <typename T>
void h() {
  (void) [] (T) [[clang::annotate_type("foo")]] { };
}

void f() {
  h<int>();
}
```

### PR DESCRIPTION
**Pull request by Sirraide**
## Summary
This pr fixes a crash when we attempt to instantiate a lambda with an `AnnotatedType`, refactors the code that handles transforming the function type of a lambda, and improves source fidelity for lambda function types.

The background for this is that, while working on #84983, the author observed that `AnnotatedType`s were not being propagated correctly when instantiating lambdas, which is a problem for anyone who actually wants to use this information for anything.

## Crash
The cause of the crash was the following: When instantiating the `FunctionProtoTypeLoc` of a lambda, we were calling `TransformAttributedType`; however, an `AttributedType` stores two `QualType`s: a `ModifiedType` and an `EquivalentType`, both of which were being transformed in that function. The problem is that instantiating a `FunctionProtoTypeLoc` also instantiates the `ParmVarDecl`s associated with that type loc, which causes a link to be established between the original, dependent `ParmVarDecl`s and their instantiations in the current `LocalInstantiationScope`. If there already is a link (which was the case when instantiating the `EquivalentType` after instantiating the `ModifiedType`, if they were the same type), we assert.

As a fix, we now only instantiate the `EquivalentType` iff it is not equal to the `ModifiedType`. Unfortunately, this doesn’t solve everything, as there is another problem here: the code that instantiates the function type of a lambda *did* account for the case of it being an `AttributedTypeLoc`, but it was also bending over backwards to avoid calling `getDerived().TransformFunctionProtoType` (which ends up being `TemplateInstantiator`’s override) and instead call `TreeTransform`’s `TransformFunctionProtoType`.

The reason for this is that the former creates a new `LocalInstantiationScope`, whereas the latter does not—but when we begin instantiating a lambda (in `TemplateInstantiator::TransformLambdaExpr`), we already push a `LocalInstantiationScope` for the lambda, and having two scopes for the same lambda would cause things to go horribly wrong, which is why `TreeTransform`’s `TransformLambdaExpr` ends up being horribly messy because it has to somehow avoid calling into `TemplateInstantiator` (and `TransformAttributedType` likewise suffered from this since it *also* had to transform the `FunctionProtoType` in question).

Instead of doing any of that, `TemplateInstantiator` now indicates that the first `LocalInstantiationScope` it creates is meant for instantiating a lambda (this is tracked in the `LocalInstantiationScope`), and its `TransformFunctionProtoType` only creates a new scope, iff the current scope is not a lambda. As a result, a lot of the tree transform code for this is now a lot simpler.

Note: There already is a pr (#78801) that makes changes similar to the ones in this pr wrt refactoring tree transform only, but that pr hasn’t received any updates for over a month, and though the author has reached out to me saying that they’d be happy to help (which I definitely appreciate), I’ve still opted to instead add (some of) their changes to this pr instead—simply because this pr also does more than just address this issue, and trying to split the fixes up into separate prs doesn’t really work too well imo (for instance, there is no testing if `AttributedType`s are being propagated correctly if we crash trying to instantiate them), and I found it easier to just combine everything into one pr. I’ve added @yuxuanchen1997 as a co-author to the commit that deals with the tree transform refactor. I hope they’re fine with my doing so.

## Source Fidelity
When rebuilding function types in `adjustDeducedFunctionResultType`, we now also rebuild `AttributedType`s and `MacroQualfiedType`s. This means that it should now be possible to access any type attributes attached to a lambda’s function type. This code was largely taken from #85147; I’ve also added @dougsonos as a co-author to the relevant commit.

Side note: I know this doesn’t really belong in this pr, but I’ve also added a `dump()` function to `Attr` since it was lacking one, which was a bit annoying when I was debugging this earlier; I can open a separate pr for that if it’s too unrelated to the other changes here.

This fixes #85120 and fixes #85154.

### CODE REVIEW

**Comment by Sirraide** [comment]
I’ll add a release note once I’ve figured out how long this bug has been in Clang.

**Comment by yuxuanchen1997** [comment]
Great. Thanks!

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -13830,62 +13820,40 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
...
-    }
+  auto OldCallOpTypeLoc =
+      E->getCallOperator()->getTypeSourceInfo()->getTypeLoc();
 
-    if (NewCallOpType.isNull())
-      return ExprError();
-    NewCallOpTSI =
-        NewCallOpTLBuilder.getTypeSourceInfo(getSema().Context, NewCallOpType);
-  }
+  QualType NewCallOpType;
```
Comment (yuxuanchen1997) [inline clang/lib/Sema/TreeTransform.h:13827]: ditto.

File: clang/lib/AST/ASTContext.cpp [hunk 2]
```diff
@@ -3140,13 +3140,35 @@ const FunctionType *ASTContext::adjustFunctionType(const FunctionType *T,
...
+  // Might have a calling-convention attribute.
+  if (const auto *AT = dyn_cast<AttributedType>(FunctionType)) {
+    return getAttributedType(
+        AT->getAttrKind(),
+        adjustFunctionResultType(AT->getModifiedType(), ResultType),
+        adjustFunctionResultType(AT->getEquivalentType(), ResultType));
+  }
+
+  // Anything else must be a function type. Rebuild it with the new return
+  // value.
```
Comment (yuxuanchen1997) [inline clang/lib/AST/ASTContext.cpp:3161]: Is this assumption true? I added the two to my original PR because that's the two I have seen but no confidence.

File: clang/lib/Sema/TreeTransform.h [hunk 3]
```diff
@@ -13830,62 +13820,40 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
     getSema().AddTemplateParametersToLambdaCallOperator(NewCallOperator, Class,
                                                         TPL);
 
-  // Transform the type of the original lambda's call operator.
-  // The transformation MUST be done in the CurrentInstantiationScope since
-  // it introduces a mapping of the original to the newly created
-  // transformed parameters.
   TypeSourceInfo *NewCallOpTSI = nullptr;
```
Comment (yuxuanchen1997) [inline clang/lib/Sema/TreeTransform.h:13823]: Branches don't exist anymore, inline this decl to where it's assigned?

Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h:13823]: Oh yeah, that makes sense; I didn’t even realise that somehow.

File: clang/lib/AST/ASTContext.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: There is at least one other case that we might want to handle (`BTFTagAttributedType`), but I have so far been unsuccessful in trying to actually create a declaration that has this attribute; I also have no idea what that attribute is for.

Comment (yuxuanchen1997) [reply clang/lib/AST/ASTContext.cpp:3161]: I think what would be required for this type of work is to have the general ability to traverse `Type`s and `TypeLoc`s. Implementation like this + the one I provided in `TreeTransform::TransformLambdaExpr` is error prone and wouldn't scale.

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: I’ve been thinking about this too; something like that or some way to strip `TypeLoc`s that count as ‘sugar’; we’re doing similar things all over the place, but from what I can tell, what is or isn’t stripped is highly dependent on context.

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: There’s `TypeLoc::getAsAdjusted()`; that might work for at least the `TransformLambdaExpr` case.

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: Yup, that works in tree transform, so that we shouldn’t have to worry about that part anymore.

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: Also, I just noticed, `RecursiveASTVisitor` *does* seem to support `Type`s and `TypeLoc`s? I’ll take another look at that.

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: The thing is, I’m not sure how well an AST visitor would work for this specific use case (rebuilding a function type with a different result type).

Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3161]: Also, I just noticed, this code seems to be modelled after `getFunctionTypeWithExceptionSpec()`, which is like two functions down in the same file and which does pretty much the same thing that this is doing here. It might make sense to merge the two.

Comment (dougsonos) [reply clang/lib/AST/ASTContext.cpp:3161]: > Also, I just noticed, this code seems to be modelled after `getFunctionTypeWithExceptionSpec()`, which is like two functions down in the same file and which does pretty much the same thing that this is doing here. It might make sense to merge the two.

I was hacking just enough to make it work, apologies.

**Comment by Sirraide** [comment]
Seeing as there are now two places where we want to adjust function types but also preserve sugar, I’ve gone ahead and added a generic `adjustType()` function that handles all of the sugar and takes a `function_ref` to perform the actual adjustment. 

The intent here is that, in the future, functions like `getFunctionTypeWithExceptionSpec()` should be able to delegate most of the work to that function instead.

File: clang/lib/AST/ASTContext.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp]: Just refactored this and extracted the code that handles the sugar into a separate function (see the latest commit).

**Comment by Sirraide** [comment]
ping

**Comment by Sirraide** [comment]
ping

File: clang/lib/AST/ASTDumper.cpp [hunk 4]
```diff
@@ -361,3 +361,11 @@ LLVM_DUMP_METHOD void ConceptReference::dump(raw_ostream &OS) const {
   ASTDumper P(OS, Ctx, Ctx.getDiagnostics().getShowColors());
   P.Visit(this);
 }
+
+//===----------------------------------------------------------------------===//
+// Attr method implementations
+//===----------------------------------------------------------------------===//
+LLVM_DUMP_METHOD void Attr::dump() const {
+  ASTDumper P(llvm::errs(), /*ShowColors=*/false);
```
Comment (zyn0217) [inline clang/lib/AST/ASTDumper.cpp:369]: Small nit: do we need an overload taking an `ASTContext` parameter to dump colors? Just like that on line 361.

File: clang/lib/Sema/TreeTransform.h [hunk 5]
```diff
@@ -13830,61 +13820,27 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
     getSema().AddTemplateParametersToLambdaCallOperator(NewCallOperator, Class,
                                                         TPL);
 
-  // Transform the type of the original lambda's call operator.
-  // The transformation MUST be done in the CurrentInstantiationScope since
-  // it introduces a mapping of the original to the newly created
-  // transformed parameters.
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:13836]: I presume this still applies, right? Could we preserve the comment?

File: clang/lib/Sema/TreeTransform.h [hunk 6]
```diff
@@ -13830,61 +13820,27 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
...
-    QualType NewCallOpType;
-    TypeLocBuilder NewCallOpTLBuilder;
-
-    if (auto ATL = OldCallOpTypeLoc.getAs<AttributedTypeLoc>()) {
-      NewCallOpType = this->TransformAttributedType(
-          NewCallOpTLBuilder, ATL,
-          [&](TypeLocBuilder &TLB, TypeLoc TL) -> QualType {
-            return TransformFunctionProtoTypeLoc(
-                TLB, TL.castAs<FunctionProtoTypeLoc>());
-          });
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:13862]: Sorry for being dense, but I just wonder why we used to need a different callback for lambda's attribute transformation; wouldn't `TransformType` take us to the same place?

Comment (zyn0217) [reply clang/lib/Sema/TreeTransform.h:13862]: Oh I see the explanation from the commit: it manages to avoid calling into TemplateInstantiator's `TransformFunctionProtoType()`, which isn't possible if it just delegates to `TransformType()`. Terrible.

**Review by zyn0217 — COMMENTED** [review]
Thanks for the patch. IIUC this patch does 2~3 things:

- Add a `dump()` method to `Attr`
- Refactor the pertaining transformation logic of `TransformLambdaExpr()`
- Refactor some other logic in `ASTContext::AdjustType()`

They're really great works, but I suggest we split up the patch to make the code review easier, WDYT?

**Comment by Sirraide** [comment]
> They're really great works, but I suggest we split up the patch to make the code review easier, WDYT?

The NFC change for adding `Attr::dump()` can definitely be factored out. I don’t know about the other two because `adjustType()` handles some cases that `adjustFunctionProtoType()` doesn’t, so splitting this up would entail adding code to the latter, only to then remove it again in a follow-up patch and move it to a separate function. I personally think it’s easier to just do this in one go.

File: clang/lib/Sema/TreeTransform.h (hunk 6 above)
Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h:13862]: > Terrible

Yup.

**Comment by Sirraide** [comment]
> so splitting this up would entail adding code to the latter, only to then remove it again in a follow-up patch and move it to a separate function

Though actually, I suppose it would be possible do add `adjustType()` *first* and make the rest of this pr depend on that.

File: clang/lib/AST/ASTDumper.cpp (hunk 4 above)
Comment (Sirraide) [reply clang/lib/AST/ASTDumper.cpp:369]: I think we normally just have a separate `dumpColor()` overload irrc, but I can add that yeah.

File: clang/lib/Sema/TreeTransform.h (hunk 5 above)
Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h:13836]: I think we could yeah, but it should probably be moved somewhere else (probably into `TemplateInstantiator::TransformFunctionProtoType`) because this code here doesn’t have to care about that anymore after this refactor.

File: clang/lib/AST/ASTContext.cpp [hunk 7]
```diff
@@ -3140,13 +3184,20 @@ const FunctionType *ASTContext::adjustFunctionType(const FunctionType *T,
   return cast<FunctionType>(Result.getTypePtr());
 }
 
+QualType ASTContext::adjustFunctionResultType(QualType FunctionType,
+                                              QualType ResultType) {
+  return adjustType(FunctionType, [&](QualType Orig) {
+    const auto *FPT = Orig->castAs<FunctionProtoType>();
```
Comment (AaronBallman) [inline clang/lib/AST/ASTContext.cpp:3190]: There's a bit of a gotcha here -- functions without prototypes have a result type that could be adjusted, so this will cause an assertion that the caller is unlikely to expect. Can we have a fallback for functions without prototypes and some test coverage for those?

File: clang/lib/AST/ASTContext.cpp [hunk 8]
```diff
@@ -3162,30 +3213,11 @@ void ASTContext::adjustDeducedFunctionResultType(FunctionDecl *FD,
...
-        getFunctionTypeWithExceptionSpec(AT->getEquivalentType(), ESI));
-
-  // Anything else must be a function type. Rebuild it with the new exception
-  // specification.
-  const auto *Proto = Orig->castAs<FunctionProtoType>();
-  return getFunctionType(
-      Proto->getReturnType(), Proto->getParamTypes(),
-      Proto->getExtProtoInfo().withExceptionSpec(ESI));
+  return adjustType(Orig, [&](QualType Ty) {
+    const auto *Proto = Ty->castAs<FunctionProtoType>();
```
Comment (AaronBallman) [inline clang/lib/AST/ASTContext.cpp:3217]: This one is fine because an exception specification means we're not in C and so the function always has a prototype.

File: clang/lib/Sema/TreeTransform.h [hunk 9]
```diff
@@ -7231,12 +7226,16 @@ QualType TreeTransform<Derived>::TransformAttributedType(
   // FIXME: dependent operand expressions?
   if (getDerived().AlwaysRebuild() ||
       modifiedType != oldType->getModifiedType()) {
-    TypeLocBuilder AuxiliaryTLB;
-    AuxiliaryTLB.reserve(TL.getFullDataSize());
-    QualType equivalentType =
-        getDerived().TransformType(AuxiliaryTLB, TL.getEquivalentTypeLoc());
-    if (equivalentType.isNull())
-      return QualType();
+    // Do not transform the equivalent type if it is equal to the modified type.
```
Comment (AaronBallman) [inline clang/lib/Sema/TreeTransform.h:7229]: It'd be better to explain *why* we don't want to transform (that we don't transform can be gleaned from reading the code).

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this!

File: clang/lib/AST/ASTContext.cpp (hunk 7 above)
Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3190]: Ah, good point. I forgot that prototypeless functions can still have result types.

(Side note: I also just somehow managed to edit your comment instead of posting this one...)

File: clang/lib/Sema/TreeTransform.h (hunk 9 above)
Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h:7229]: Yeah, that’s a pretty bad comment, I agree...

File: clang/lib/Sema/TreeTransform.h (hunk 5 above)
Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h:14733]: Done

File: clang/lib/AST/ASTDumper.cpp (hunk 4 above)
Comment (Sirraide) [reply clang/lib/AST/ASTDumper.cpp]: I’ve removed this from this pr.

File: clang/lib/AST/ASTContext.cpp (hunk 7 above)
Comment (Sirraide) [reply clang/lib/AST/ASTContext.cpp:3582]: This now handles `FunctionNoProtoType`s as well.

File: clang/lib/Sema/TreeTransform.h (hunk 9 above)
Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h]: I’ve expanded the comment a bit to make this a bit more informative (hopefully).

**Comment by Sirraide** [comment]
ping

**Review by erichkeane — APPROVED** [review]
I don't see any reason to hold this up, and its waited long enough.  So I'm going to consider this 'baked' enough in review.

**Comment by Sirraide** [comment]
Alright, I’ll merge main and then merge this once CI is done.

**Comment by Sirraide** [comment]
Forgot to set the target again it seems; will be fixing that in a moment
