### PR TITLE
[HLSL] make semantic matching case insensitive

### LINKED ISSUE #128063: [HLSL] Semantic matching not case insensitive
The HLSL semantic parsing for system values seems to not be correctly case insensitive. The following code fails to compile with Clang, but compiles fine with DXC.

```hlsl
[numthreads(1,1,1)]
void main(uint I : SV_DispatchThreadId) {}
```
[CE](https://godbolt.org/z/sjKGf8sKr)

### PR DESCRIPTION
**Pull request by spall**
Make semantic matching case insensitive
update tests to reflect semantic printed as all lower case in error messages
add new tests to show case insensitivity
Closes #128063

### CODE REVIEW

File: clang/lib/Parse/ParseHLSL.cpp [hunk 1]
```diff
@@ -141,6 +141,8 @@ void Parser::ParseHLSLAnnotations(ParsedAttributes &Attrs,
     return;
   }
 
+  II = PP.getIdentifierInfo(II->getName().lower());
```
Comment (bob80905) [inline clang/lib/Parse/ParseHLSL.cpp:144]: Is this used?

Comment (spall) [reply clang/lib/Parse/ParseHLSL.cpp:144]: Yes, II is passed two places.

**Review by bob80905 — APPROVED** [review]

**Review by joaosaffran — APPROVED** [review]
LGTM

File: clang/lib/Parse/ParseHLSL.cpp (hunk 1 above)
Comment (llvm-beanz) [reply clang/lib/Parse/ParseHLSL.cpp:144]: Can we keep the original identifier around and use that for the diagnostics so that the diagnostic text matches the capitalization in the source?

I often find myself copy and pasting error message text to then grep codebases, so it would be nice if we preserved the spelling.

Comment (spall) [reply clang/lib/Parse/ParseHLSL.cpp:144]: Okay that might requirement a significant change. I'll look into it

File: clang/include/clang/Basic/Attr.td [hunk 2]
```diff
@@ -4790,7 +4790,7 @@ def HLSLPackOffset: HLSLAnnotationAttr {
 }
 
 def HLSLSV_DispatchThreadID: HLSLAnnotationAttr {
-  let Spellings = [HLSLAnnotation<"SV_DispatchThreadID">];
+  let Spellings = [HLSLAnnotation<"sv_dispatchthreadid">];
```
Comment (llvm-beanz) [inline clang/include/clang/Basic/Attr.td:4793]: Can we add a check in the tablegen code to error if the HLSLAnnotation attributes ever have a spelling with a capital letter?

I just don't want us to screw this up accidentally and break some new attribute.

**Review by joaosaffran — COMMENTED** [review]
nit: is there a way to check that the spelling is consistent in the error messages? Asking since I am no familiar with this part of the code.

**Review by llvm-beanz — APPROVED** [review]

**Comment by llvm-beanz** [comment]
> > nit: is there a way to check that the spelling is consistent in the error messages? Asking since I am no familiar with this part of the code.
> 
> I'm not sure I understand what you mean.

I think the point (and my earlier comment) is to use the spelling as it is written in the source so that the user can grep their code for the string that occurs in the error message rather than providing consistent capitalization in the error messages.
