### PR TITLE
[lldb][Android] Fix platform process list regression

### LINKED ISSUE #164192: [LLDB/Android] Cannot list processes
After #160931, when debugging Android remotely, `platform process list` command cannot find any processes,

* After the change:
```
(lldb) platform process list
error: no processes were found on the "remote-android" platform

(lldb) platform process list -n com.example.hellojni
1 matching process was found on "remote-android"
 whose name matched "com.example.hellojni"
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192                                   com.example.hellojni

(lldb) platform process list -p 5276
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192    x86_64-unknown-linux-android   app_process64
```

* Before the change:
```
(lldb) platform process list
5 matching processes were found on "remote-android"

PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192    x86_64-unknown-linux-android   app_process64
5357   5355   u0_a192    x86_64-unknown-linux-android   sh
5370   5357   u0_a192    x86_64-unknown-linux-android   sh
5377   5370   u0_a192    x86_64-unknown-linux-android   lldb-server
5510   5394   u0_a192    x86_64-unknown-linux-android   sh

(lldb) platform process list -n com.example.hellojni
error: no processes were found that matched "com.example.hellojni" on the "remote-android" platform

(lldb) platform process list -p 5276
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192    x86_64-unknown-linux-android   app_process64
```

Note also that the results returned by `platform process list -n` are inconsistent with `platform process list -p` (and inconsistent with the results of `platform process list` before the change). With `-n`, it returns no triple and a different process name.  LLDB used to return `app_process64` (zygote). This may be the root cause.

---

* Repro instructions

On the Android side:
```
$ adb shell
adb$ run-as com.example.hellojni
adb|com.example.hellojni$ /data/data/com.example.hellojni/lldb/bin/lldb-server platform --server --listen unix-abstract:///com.example.hellojni-0/platform-156393867851.sock --log-file /data/data/com.example.hellojni/lldb/log/platform.log --log-channels 'lldb process:gdb-remote packets'
```

On the host side:
```
(lldb) platform select remote-android
(lldb) platform connect unix-abstract-connect://[emulator-5554]/com.example.hellojni-0/platform-156393867851.sock
(lldb) platform process list
```

### PR DESCRIPTION
**Pull request by cs01**
## Summary

Fix `FindProcesses` to respect Android's `hidepid=2` security model and enable name matching for Android apps.

## Problem

1. Called `adb shell pidof` or `adb shell ps` directly, bypassing Android's process visibility restrictions
2. Name matching failed for Android apps - searched for `com.example.myapp` but GDB Remote Protocol reports `app_process64`

Android apps fork from Zygote, so `/proc/PID/exe` points to `app_process64` for all apps. The actual package name is only in `/proc/PID/cmdline`. The previous implementation applied name filters without supplementing with cmdline, so searches failed.

## Fix

- Delegate to lldb-server via GDB Remote Protocol (respects `hidepid=2`)
- Get all visible processes, supplement zygote/app_process entries with cmdline, then apply name matching
- Only fetch cmdline for zygote apps (performance), parallelize with `xargs -P 8`
- Remove redundant code (GDB Remote Protocol already provides GID/arch)

### Before this fix:

```
(lldb) platform process list
error: no processes were found on the "remote-android" platform

(lldb) platform process list -n com.example.hellojni
1 matching process was found on "remote-android"
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192                                   com.example.hellojni
                         ^^^^^^^^ Missing triple!
```

### After this fix:

```
(lldb) platform process list
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
1      0      root       aarch64-unknown-linux-android  init
2      0      root                                      [kthreadd]
359    1      system     aarch64-unknown-linux-android  app_process64
5276   359    u0_a192    aarch64-unknown-linux-android  com.example.hellojni
5357   5355   u0_a192    aarch64-unknown-linux-android  sh
5377   5370   u0_a192    aarch64-unknown-linux-android  lldb-server
                          ^^^^^^^^ User-space processes now have triples!

(lldb) platform process list -n com.example.hellojni
1 matching process was found on "remote-android"
PID    PARENT USER       TRIPLE                         NAME
====== ====== ========== ============================== ============================
5276   359    u0_a192    aarch64-unknown-linux-android  com.example.hellojni


(lldb) process attach -n com.example.hellojni
Process 5276 stopped
* thread #1, name = 'example.hellojni', stop reason = signal SIGSTOP
```

## Test Plan

With an Android device/emulator connected:

1. Start lldb-server on device:
```bash
adb push lldb-server /data/local/tmp/
adb shell chmod +x /data/local/tmp/lldb-server
adb shell /data/local/tmp/lldb-server platform  --listen 127.0.0.1:9500 --server
```

2. Connect from LLDB:
```
(lldb) platform select remote-android
(lldb) platform connect connect://127.0.0.1:9500
(lldb) platform process list
```

3. Verify:
   - `platform process list` returns all processes with triple information
   - `platform process list -n com.example.app` finds Android apps by package name
   - `process attach -n com.example.app` successfully attaches to Android apps

## Impact

Restores `platform process list` on Android with architecture information and package name lookup. All name matching modes now work correctly.

Fixes https://github.com/llvm/llvm-project/issues/164192

### CODE REVIEW

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 1]
```diff
@@ -652,75 +709,169 @@ PlatformAndroid::FindProcesses(const ProcessInstanceInfoMatch &match_info,
...
   }
 
-  // Use 'pidof' command to get PIDs for the process name.
-  // Quote the process name to handle special characters (spaces, etc.)
-  std::string pidof_output;
-  StreamString command;
-  command.Printf("pidof '%s'", process_name.c_str());
-  error = adb->Shell(command.GetData(), seconds(5), &pidof_output);
+  std::string ps_output;
+  error = adb->Shell("ps -A -o PID,ARGS", seconds(5), &ps_output);
```
Comment (emrekultursay) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: I don't see the point of querying all processes, when the Android security model only allows attaching to the processes running as the same user as `lldb-server`.  Shouldn't we list only those processes that we can debug?

Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: I believe the full list of potentially non-debuggable processes is shown on non-Android platforms too. I can check tomorrow. I would prefer to follow whatever convention lldb has for this in general.

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 2]
```diff
@@ -652,75 +709,169 @@ PlatformAndroid::FindProcesses(const ProcessInstanceInfoMatch &match_info,
...
 
-    // Populate additional process information
+    // Set the executable name from cmdline (first token, typically)
+    llvm::StringRef exe_name = cmdline;
+    auto first_space = cmdline.find(' ');
+    if (first_space != llvm::StringRef::npos)
+      exe_name = cmdline.substr(0, first_space);
+
+    process_info.GetExecutableFile().SetFile(exe_name, FileSpec::Style::posix);
+
```
[the remark this answers is not in the document]
Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: I noticed it was slow too. However it did not seem slower than before. But I like the idea of batching the calls. I can do that tomorrow.

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp (hunk 1 above)
Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: >  It's also just useful when you are debugging a remote system to be able to see what's going on there, even if you can't attach to everything you see.

Agreed. It would be surprising to me if I ran `platform process list` and it applied some kind of extra filtering.

**Comment by cs01** [comment]
This is ready for another review

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 3]
```diff
@@ -479,246 +479,128 @@ std::string PlatformAndroid::GetRunAs() {
...
-    arch.SetTriple("aarch64-unknown-linux-android");
-  } else if (exe_output.find("x86_64") != std::string::npos) {
-    arch.SetTriple("x86_64-unknown-linux-android");
-  } else if (exe_output.find("x86") != std::string::npos ||
-             exe_output.find("i686") != std::string::npos) {
-    arch.SetTriple("i686-unknown-linux-android");
-  } else {
-    // Default to armv7 for 32-bit ARM (most common on Android)
-    arch.SetTriple("armv7-unknown-linux-android");
+    for (auto &proc_info : proc_infos) {
```
Comment (emrekultursay) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: This is making a lot of redundant iterations (it's not even iterating over filtered list).  Maybe we can create a map<pid, proc_info> around 501-503, and then look it up here.

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 4]
```diff
@@ -479,246 +479,128 @@ std::string PlatformAndroid::GetRunAs() {
...
+  cmd.Printf(
+      "echo '%s' | xargs -n 1 -P 8 sh -c "
+      "'echo \"$1:$(cat /proc/$1/cmdline 2>/dev/null | tr \"\\0\" \" \")\"' sh",
+      pid_list.c_str());
 
-  cmdline_output = llvm::StringRef(cmdline_output).trim().str();
-  if (cmdline_output.empty())
-    return;
+  std::string cmdline_output;
+  Status error = adb->Shell(cmd.GetData(), seconds(5), &cmdline_output);
```
Comment (emrekultursay) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: This looks OK for now. But, if Android moves to use pid namespaces in the future, this will stop working.

**Review by emrekultursay — APPROVED** [review]

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp (hunk 3 above)
Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: updated in latest commit

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 5]
```diff
@@ -479,246 +481,131 @@ std::string PlatformAndroid::GetRunAs() {
...
-      llvm::SmallVector<llvm::StringRef, 4> gid_parts;
-      line.substr(4).trim().split(gid_parts, '\t', -1, false);
-      if (gid_parts.size() >= 2) {
-        uint32_t gid, egid;
-        if (llvm::to_integer(gid_parts[0].trim(), gid))
-          process_info.SetGroupID(gid);
-        if (llvm::to_integer(gid_parts[1].trim(), egid))
-          process_info.SetEffectiveGroupID(egid);
-      }
+  std::unordered_map<lldb::pid_t, ProcessInstanceInfo *> pid_map;
```
Comment (JDevlieghere) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: Any reason to prefer this over DenseMap?

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 6]
```diff
@@ -479,246 +481,131 @@ std::string PlatformAndroid::GetRunAs() {
...
+  llvm::SmallVector<llvm::StringRef, 256> lines;
+  llvm::StringRef(cmdline_output).split(lines, '\n', -1, false);
 
-  llvm::SmallVector<llvm::StringRef, 16> args;
-  llvm::StringRef(cmdline_output).split(args, ' ', -1, false);
-  if (args.empty())
-    return;
+  for (llvm::StringRef line : lines) {
+    line = line.trim();
+    auto colon_pos = line.find(':');
```
Comment (JDevlieghere) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: This looks like a good candidate for using StringRef::split.

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp (hunk 5 above)
Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: thanks, fixed

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 7]
```diff
@@ -479,246 +481,131 @@ std::string PlatformAndroid::GetRunAs() {
...
+  ProcessInstanceInfoList all_procs;
+  uint32_t count =
+      m_remote_platform_sp->FindProcesses(broad_match_info, all_procs);
+
+  if (count > 0) {
+    Status error;
+    AdbClientUP adb(GetAdbClient(error));
+    if (error.Success()) {
+      Log *log = GetLog(LLDBLog::Platform);
+      SupplementWithCmdlineInfo(all_procs, adb.get(), log);
```
[the remark this answers is not in the document]
Comment (cs01) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: no, will change, thanks

**Review by JDevlieghere — APPROVED** [review]

**Comment by cs01** [comment]
I think this should be good to merge since it has two approvals
