### PR TITLE
[DirectX] Legalize lifetime intrinsics for DXIL

### LINKED ISSUE #147395: [DirectX] `llvm.lifetime.start/.end` non-`i8*` pointers causing `Invalid record` validation error
## The problem

DXIL bitcode containing `llvm.lifetime.start/end` intrinsics emitted by Clang can fail to validate under the DXIL validator (dxv) due to error `Invalid record` located here: https://github.com/microsoft/DirectXShaderCompiler/blob/main/lib/Bitcode/Reader/BitcodeReader.cpp#L4722

Debugging the cause of the error with lldb, I have found that nullptr is being returned here:
https://github.com/microsoft/DirectXShaderCompiler/blob/a11702ef0a393a9e0b78f982f9f0fa66d919c867/lib/Bitcode/Reader/BitcodeReader.cpp#L836-L837
```c
    if (Ty && Ty != V->getType())
      return nullptr;
```
because `Ty` is `i8*` and `V->getType()` is not equal to `Ty`.

## Reproducing the problem

Sample shader that reproduces the problem:
```hlsl
// compile args: -E CSMain -T cs_6_6
uint2 Foo(uint2 a[2], uint i) {
  return a[i];
}
cbuffer Constants {
  uint2 arr[2];
}
RWStructuredBuffer<uint> output;
[numthreads(1, 1, 1)]
void CSMain(uint3 Tid : SV_DispatchThreadID) {
  output[0] = Foo(arr, Tid.x).x;
}
```

https://godbolt.org/z/haz47M8fz

Validation error:
```
Invalid record
Validation failed.
```

due to the lifetime intrinsic:
```llvm
 %1 = alloca [4 x i32], align 8
 call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %1), !dbg !100
```

The BitcodeReader expects `V->getType()` to be an `i8*`, but it is currently a `[4 x i32]*`.

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #147395

This PR legalizes lifetime intrinsics for DXIL by
- Adding a bitcast for the lifetime intrinsics' pointer operand in dxil-prepare to ensure it gets cast to an `i8*` when written to DXIL
- Removing the memory attribute from lifetime intrinsics in dxil-prepare to match DXIL
- Making the DXIL bitcode writer write the base/demangled name of lifetime intrinsics to the symbol table
- Making lifetime intrinsics an exception to Int64Ops shader flag analysis (otherwise we get `error: Flags must match usage.` from the validator)

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILPrepare.cpp [hunk 1]
```diff
@@ -239,6 +240,13 @@ class DXILPrepareModule : public ModulePass {
       for (size_t Idx = 0, End = F.arg_size(); Idx < End; ++Idx)
         F.removeParamAttrs(Idx, AttrMask);
 
+      // Match FnAttrs of lifetime intrinsics in LLVM 3.7
+      if (F.isIntrinsic())
+        switch (F.getIntrinsicID())
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILPrepare.cpp]: Does this not cause a build warning for missing cases? If it does, I suspect it will cause some build failures that set warning to error

File: llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll [hunk 2]
```diff
@@ -15,6 +16,14 @@
 ; CHECK-SM66-NEXT:    store i32 0, ptr [[GEP]], align 4
 ; CHECK-SM66-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[ACCUM_I_FLAT]])
 ; 
+; CHECK-PREPARE-NEXT:    [[ACCUM_I_FLAT:%.*]] = alloca [1 x i32], align 4
+; CHECK-PREPARE-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[ACCUM_I_FLAT]], i32 0
+; CHECK-PREPARE-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[ACCUM_I_FLAT]] to ptr
+; CHECK-PREPARE-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[BITCAST]])
+; CHECK-PREPARE-NEXT:    store i32 0, ptr [[GEP]], align 4
+; CHECK-PREPARE-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[ACCUM_I_FLAT]] to ptr
```
Comment (inbelic) [inline llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll:24]: Without adding too much complexity to the code, is it possible to re-use this for both lifetimes?

You might be able to just iterate the users of `PtrOperand` and detect a bitcast to set as the operand.

Happy to just be told no. But wanted to make we thought of it

File: llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp [hunk 3]
```diff
@@ -2559,8 +2559,22 @@ void DXILBitcodeWriter::writeFunctionLevelValueSymbolTable(
...
   for (auto &VI : VST) {
-    SortedTable.push_back(VI.second->getValueName());
+    ValueName *VN = VI.second->getValueName();
+    // Clang mangles lifetime intrinsic names by appending '.p0' to the end,
+    // making them invalid lifetime intrinsics in LLVM 3.7. We can't
+    // demangle in dxil-prepare because it would result in invalid IR.
+    // Therefore we have to do this in the bitcode writer while writing its
+    // name to the symbol table.
+    if (const Function *Fn = dyn_cast<Function>(VI.getValue());
+        Fn && Fn->isIntrinsic()) {
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp:2591]: TIL: you can use this syntax. Cool

File: llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp [hunk 4]
```diff
@@ -2559,8 +2559,22 @@ void DXILBitcodeWriter::writeFunctionLevelValueSymbolTable(
   // to ensure the binary is the same no matter what values ever existed.
   SmallVector<const ValueName *, 16> SortedTable;
 
+  MallocAllocator Allocator;
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp]: Does DXILBitcodeWriter or any parent class have an allocater as a member to use here instead?

**Review by inbelic — APPROVED** [review]
LGTM implementation wise. Would like a second reviewer based on how this fits into the bigger picture.

File: llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll (hunk 2 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll:24]: I tried but different CHECK prefixes have their own scopes for variables. 
For example if I do
```
; CHECK: [[ACCUM_I_FLAT:%.*]] = alloca [1 x i32], align 4
```
Then these lines will all fail FileCheck due to undefined variable `[[ACCUM_I_FLAT]]`
```
; CHECK-SM63-NEXT:    store [1 x i32] undef, ptr [[ACCUM_I_FLAT]], align 4

; CHECK-SM66-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[ACCUM_I_FLAT]])

; CHECK-PREPARE-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[ACCUM_I_FLAT]] to ptr
```

File: llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp (hunk 3 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp:2591]: Yea Farzon showed me it

File: llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp (hunk 4 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp]: Not that I'm aware of. 
I see Value.cpp use the same pattern here of creating MallocAllocator on the fly to make a ValueName
https://github.com/llvm/llvm-project/blob/535d6917ec3308ade866f205644b740666312342/llvm/lib/IR/Value.cpp#L367-L368

File: llvm/lib/Target/DirectX/DXILPrepare.cpp (hunk 1 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILPrepare.cpp]: I'll just change this to an if statement.

File: llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll (hunk 2 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll:24]: dxil-prepare inserts bitcasts for other instructions too, so I think this should be a suggestion for dxil-prepare as a whole and not just bitcasts for lifetimes intrinsics only.

File: llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp (hunk 4 above)
Comment (inbelic) [reply llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp]: Do we want to make it and `LifetimeValueNames` and then put the destruction of the names in the destructor?

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp]: I moved the allocator and smallvector to its own struct and clean them up in the struct's destructor

File: llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll (hunk 2 above)
Comment (llvm-beanz) [reply llvm/test/CodeGen/DirectX/legalize-lifetimes-valver-1.6.ll:24]: generally bitcasts are "free" in that they don't have any runtime implementation cost, and for lifetime markers which also have no runtime implementation cost, they're usually not a big deal. They do have some tiny cost on binary size, but I'd say this probably isn't worth fixing.

**Review by llvm-beanz — APPROVED** [review]
