### PR TITLE
[WebAssembly] Fix null Subtarget crash for addrspace(1) globals

### LINKED ISSUE #181527: [WebAssembly] Crash in emitGlobalVariable with addrspace(1) globals due to missing Subtarget during doFinalization
Summary

When compiling a WebAssembly module containing a global variable in addrspace(1) (Wasm Global), llc crashes with LLVM ERROR: Aggregate globals not yet implemented.

The error message is misleading. The crash occurs because emitGlobalVariable is called during doFinalization, where the Subtarget member is nullptr. This causes computeLegalValueVTs to be skipped, leaving the VTs vector empty, which triggers the assertion failure in wasmSymbolSetType.

Reproduction

1. Case where it fails (Bug):
Using addrspace(1) triggers the Wasm-specific global handling path.
```wasm

; crash.ll
target triple = "wasm32-unknown-unknown"

; A scalar global in Wasm global space (addrspace 1)
@wasm_val = addrspace(1) global i32 123
```

```Bash
llc -mtriple=wasm32-unknown-unknown crash.ll -o -
```
Output: LLVM ERROR: Aggregate globals not yet implemented

2. Case where it works (Normal):
Standard globals (addrspace 0) work fine because they are handled by the base AsmPrinter class and return early before reaching the buggy code.
```wasm

; works.ll
target triple = "wasm32-unknown-unknown"
@std_val = global i32 123
```
Root Cause Analysis 

The crash happens in WebAssemblyAsmPrinter::emitGlobalVariable. This function is called during doFinalization. At this stage, the AsmPrinter::Subtarget member is nullptr because there is no active MachineFunction.

The code checks if (Subtarget) to compute value types:
```cpp
    if (Subtarget) {
       // ... calls computeLegalValueVTs ...
    }
```

Since Subtarget is null, computeLegalValueVTs is skipped, and VTs remains empty (size 0).

WebAssembly::wasmSymbolSetType is called with an empty VTs.

Inside wasmSymbolSetType, it checks if (VTs.size() == 1). Since size is 0, it falls through to the else block and calls report_fatal_error("Aggregate globals not yet implemented").

Proposed Solution

If Subtarget is null (which is expected during doFinalization), we should retrieve the default subtarget from the TargetMachine (TM).

### PR DESCRIPTION
**Pull request by ParkHanbum**
If Subtarget is null during global emission, it is now retrieved
from TargetMachine to prevent crashes caused by empty VTs in
wasmSymbolSetType.

Fixed: https://github.com/llvm/llvm-project/issues/181527

### CODE REVIEW

File: llvm/lib/Target/WebAssembly/WebAssemblyAsmPrinter.cpp [hunk 1]
```diff
@@ -198,13 +198,12 @@ void WebAssemblyAsmPrinter::emitGlobalVariable(const GlobalVariable *GV) {
...
-      // to calculate the legal VTs.
+      // Subtarget is typically set when a function is processed. In modules
+      // with only global variables (no functions), Subtarget remains null.
+      // Unlike architectures that support per-function subtargets (e.g., ARM
+      // vs Thumb), WebAssembly features are coalesced module-wide before ISel.
+      // Therefore, if Subtarget is null, it is safe to retrieve the default
+      // Subtarget from TargetMachine to calculate legal VTs.
       auto &WasmTM = static_cast<const WebAssemblyTargetMachine &>(TM);
       Subtarget = WasmTM.getSubtargetImpl();
     }
```
Comment (aheejin) [inline llvm/lib/Target/WebAssembly/WebAssemblyAsmPrinter.cpp]: I think we can just remove this `if (!Subtarget)` and unconditionally run
```cpp
      auto &WasmTM = static_cast<const WebAssemblyTargetMachine &>(TM);
      Subtarget = WasmTM.getSubtargetImpl();
```
because we coalesce features anyway. Also when there is no function, we get it from the target CPU anyway:
https://github.com/llvm/llvm-project/blob/55b271ddc1fd9684b9b0a955e70cb4dafc2bc782/llvm/lib/Target/WebAssembly/WebAssemblyTargetMachine.cpp#L317-L325

So let's bring this code out of `if`, fix the comments accordingly, and land it.

**Review by aheejin — APPROVED** [review]

**Comment by pmatos** [comment]
> ping @pmatos

Sorry for the delay - I will take a look now as well.

**Review by pmatos — CHANGES_REQUESTED** [review]
Besides the `CHECK` issue, LGTM. Thanks and apologies for the review delay.

**Review by pmatos — APPROVED** [review]
