### PR TITLE
[lldb] Fixed PlatformPOSIX::DoLoadImage() in case of the Windows host

### LINKED ISSUE #93092: [lldb] PlatformPOSIX::DoLoadImage() failed on the remote target AArch64 during the TestCompletion test
The TestCompletion test failed in case of the remote target Linux AArch64 (Jetson AGX/Cortex a78 board with Ubuntu 22.04, the host is Windows). LoadImage() installs the .so image to the remote target with correct permissions. But PlatformPOSIX::DoLoadImage() reports the following error:
```
dlopen error: untu\tests\functionalities\completion\1\TestCompletion.test_process_unload\libshared.so: cannot open shared object file: No such file or directory
```
Note 1: The path separator is `\` in the error message, but `lldb.SBFileSpec(remote_path, False)` is used with the correct remote_path and the file `libshared.so` is correctly installed to the remote target. I have no idea where `/` has been converted to `\`.

Note 2: The tests directory is `/home/ubuntu/tests`. The path in the error message is cropped at the beginning (exactly 8 chars `/home/ub`) and probably some useful info in the error message is cropped too.

Note 3: All `dlopen error` messages contain a hardcoded description except the last one where `token == 0` in lldb/source/Plugins/Platform/POSIX/PlatformPOSIX.cpp, line 903:
```
lldb::addr_t token = process->ReadPointerFromMemory(return_addr, utility_error);
```
So, most probably this error is caused here.

### PR DESCRIPTION
**Pull request by slydiman**
Do not denormalize the path. This patch fixes #93092.

BTW, it would be great to be able to pass the style or triple to SBFileSpec. Currently it is impossible to create a posix SBFileSpec on the Windows host.

### CODE REVIEW

File: lldb/source/Plugins/Platform/POSIX/PlatformPOSIX.cpp [hunk 1]
```diff
@@ -678,8 +678,8 @@ uint32_t PlatformPOSIX::DoLoadImage(lldb_private::Process *process,
     loaded_image->Clear();
 
   std::string path;
```
Comment (labath) [inline lldb/source/Plugins/Platform/POSIX/PlatformPOSIX.cpp:680]:
```suggestion
  std::string path = remote_file.GetPath(false);
```
Might as well fold the assignment into the declaration.

**Review by labath — APPROVED** [review]
> BTW, it would be great to be able to pass the style or triple to SBFileSpec. Currently it is impossible to create a posix SBFileSpec on the Windows host.

This is definitely not intentional. Feel free to create a PR to add it.
