### PR TITLE
[DirectX] Legalize memcpy

### LINKED ISSUE #137188: [DirectX] Legalize memcpy
## Problem 
Currently we are emitting memcpys both 64bit and 32bit versions
The DML shaders will have errors like so:

`error: Unsupported intrinsic llvm.memcpy.p3.p3.i32 for DXIL lowering`

We emit this error because the memcpy intrinsic is not valid DXIL.

These memcpys tend to be in the `hlsl_groupshared` ie `addressspace(3)`. This might make the memcpy more involved to serialize into a set of store calls.

## Example

```llvm
tail call void @llvm.memcpy.p3.p3.i32(ptr addrspace(3) align 4 %scevgep, ptr addrspace(3) align 4 %scevgep19, i32 %38, i1 false)
```

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #137188 

This PR legalizes memcpy for DXIL in cases where:
- the src and dst arguments are from Alloca or a GlobalVariable,
- the src and dst are pointers to an ArrayType,
- the array element types of src and dst must be equivalent, and
- the len param is a ConstantInt

These assumptions simplify the legalization and, with the addition of #138991, covers the currently-known cases of memcpy that appear when compiling DML shaders.

This PR may be unnecessary if #138788 determines that memset and memcpy can be eliminated entirely.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 1]
```diff
@@ -15,6 +15,7 @@
 #include "llvm/IR/Instructions.h"
 #include "llvm/IR/Module.h"
 #include "llvm/Pass.h"
+#include "llvm/Support/ErrorHandling.h"
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:18]: nit: verify that this is used

edit: oh maybe this is for assert/unreachable?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 2]
```diff
@@ -246,6 +247,59 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+                                ConstantInt *Length) {
+
+  uint64_t ByteLength = Length->getZExtValue();
+  if (ByteLength == 0)
+    return;
+
+  LLVMContext &Ctx = Builder.getContext();
+  const DataLayout &DL = Builder.GetInsertBlock()->getModule()->getDataLayout();
+
+  auto GetArrTyFromVal = [](Value *Val) {
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:260]: nit:
```suggestion
  auto GetArrTyFromVal = [](Value *Val) -> ArrayType * {
```

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 3]
```diff
@@ -246,6 +247,59 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+    if (auto *Alloca = dyn_cast<AllocaInst>(Val))
+      return dyn_cast<ArrayType>(Alloca->getAllocatedType());
+    if (auto *GlobalVar = dyn_cast<GlobalVariable>(Val))
+      return dyn_cast<ArrayType>(GlobalVar->getValueType());
+    llvm_unreachable(
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:265]: nit: Maybe an assert is better? This code path will be triggered if say `Val` is a ptr from, say, the function args or a gep. So I do think it is reachable, just never expected to.

**Review by inbelic — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 1 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:18]: Yea it is for the unreachable

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 3 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:265]: The [documentation](https://github.com/llvm/llvm-project/blob/f4853d7a25e093ac1b69959264a90f6a2326aefe/llvm/include/llvm/Support/ErrorHandling.h#L160) for llvm_unreachable says it should be used instead of an assert(0)

Comment (inbelic) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:265]: I suppose, although in this case we are essentially asserting that it is one of the two types. Maybe an assert before the conditions then?

`assert((isa<AllocaInst>(Val) || isa<GlobalVariable>(Val)) && "Expected ...)`

Anyways, I shall not block any further

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 4]
```diff
@@ -246,6 +246,61 @@ downcastI64toI32InsertExtractElements(Instruction &I,
   }
 }
 
+static void emitMemcpyExpansion(IRBuilder<> &Builder, Value *Dst, Value *Src,
+                                ConstantInt *Length) {
+
+  uint64_t ByteLength = Length->getZExtValue();
+  if (ByteLength == 0)
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:253]: should we error here?  Returning here lets the memcpy  live on past legalization. Feels weird that we would just let a memcpy live on if its malformed.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 5]
```diff
@@ -246,6 +246,61 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+  const DataLayout &DL = Builder.GetInsertBlock()->getModule()->getDataLayout();
+
+  auto GetArrTyFromVal = [](Value *Val) -> ArrayType * {
+    assert(isa<AllocaInst>(Val) ||
+           isa<GlobalVariable>(Val) &&
+               "Expected Val to be an Alloca or Global Variable");
+    if (auto *Alloca = dyn_cast<AllocaInst>(Val))
+      return dyn_cast<ArrayType>(Alloca->getAllocatedType());
+    if (auto *GlobalVar = dyn_cast<GlobalVariable>(Val))
+      return dyn_cast<ArrayType>(GlobalVar->getValueType());
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:266]: If legalization moves before  data scalarization do we need to handle memcpys for vectors?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 4 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:253]: The memcpy gets removed by the `ToRemove.push_back(CI);` after this function returns, no?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 6]
```diff
@@ -246,6 +246,61 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+  [[maybe_unused]] uint64_t Size = ArrTy->getArrayNumElements();
+  assert(ElemSize * Size >= ByteLength &&
+         "Array size must be at least as large as the memcpy length");
+
+  uint64_t NumElemsToCopy = ByteLength / ElemSize;
+  assert(ByteLength % ElemSize == 0 &&
+         "memcpy length must be divisible by array element type");
+  for (uint64_t I = 0; I < NumElemsToCopy; ++I) {
+    Value *Offset = ConstantInt::get(Type::getInt32Ty(Ctx), I);
+    Value *SrcPtr = Builder.CreateGEP(ElemTy, Src, Offset, "gep");
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:297]: I'm not sure this is enough, should we be looking to use a GEP creator that sets `GEP.isInBounds()`?

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+; CHECK-NEXT:    [[GEP:%.*]] = getelementptr <4 x i32>, ptr [[TMP1]], i32 0
+; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[GEP]], align 16
+; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr addrspace(2) getelementptr (<4 x i32>, ptr addrspace(2) @outputStrides, i32 1), align 16
+; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr <4 x i32>, ptr [[TMP1]], i32 1
+; CHECK-NEXT:    store <4 x i32> [[TMP3]], ptr [[GEP1]], align 16
+; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[TMP1]])
+; CHECK-NEXT:    ret void
+;
+  %1 = alloca [2 x <4 x i32>], align 16
+  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %1)
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/legalize-memcpy.ll:21]: Do we need the life times for the global scope memory? I know they are always there for allocas, was not sure if they impacted global memory.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 4 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:253]: But its not valid to just remove it, we should error. Your Destination Ptr would be unintialized.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 8]
```diff
@@ -296,6 +351,30 @@ static void emitMemsetExpansion(IRBuilder<> &Builder, Value *Dst, Value *Val,
...
+    return;
+
+  Intrinsic::ID ID = CI->getIntrinsicID();
+  if (ID != Intrinsic::memcpy)
+    return;
+
+  IRBuilder<> Builder(&I);
+  Value *Dst = CI->getArgOperand(0);
+  Value *Src = CI->getArgOperand(1);
+  ConstantInt *Length = dyn_cast<ConstantInt>(CI->getArgOperand(2));
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:369]: Are we sure memcpy will always be a ConstantInt for length? I'm leaning yes because you check the globals are constants?

**Review by farzonl — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 4 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:253]: Never mind I suppose if that's what the implementer wants then we should honor it.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 5 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:266]: I don't think vectors are an issue; memcpy doesn't accept vector args.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 8 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:369]: I recall @tex3d mentioning that the length should always be constant. There was a case of it not being constant, but that has been eliminated by #138991

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 9]
```diff
@@ -246,6 +246,61 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+  assert(ArrTy == SrcArrTy &&
+         "Array Types of Src and Dst in memcpy must match");
+
+  Type *ElemTy = ArrTy->getElementType();
+  uint64_t ElemSize = DL.getTypeStoreSize(ElemTy);
+  assert(ElemSize > 0 && "Size must be set");
+
+  [[maybe_unused]] uint64_t Size = ArrTy->getArrayNumElements();
+  assert(ElemSize * Size >= ByteLength &&
+         "Array size must be at least as large as the memcpy length");
```
Comment (pow2clk) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:290]: Should we also assert that Length is not longer than the `dst` array?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 10]
```diff
@@ -296,6 +351,30 @@ static void emitMemsetExpansion(IRBuilder<> &Builder, Value *Dst, Value *Val,
   }
 }
 
+static void removeMemCpy(Instruction &I,
```
Comment (pow2clk) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:354]:
```suggestion
// Expands the instruction `I` into corresponding loads and stores if it is a memcpy call.
// In that case, the call instruction is added to the `ToRemove` vector.
// `ReplacedValues` is unused.
static void legalizeMemCpy(Instruction &I,
```

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 7 above)
Comment (pow2clk) [inline llvm/test/CodeGen/DirectX/legalize-memcpy.ll:21]: I don't know the tendencies for testing here, but I've taken to removing lifetime markers when I'm not testing them directly. That would simplify some of you CHECK walls of text somewhat.

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll [hunk 11]
```diff
@@ -0,0 +1,174 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -S -dxil-legalize -dxil-finalize-linkage -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s
+
+@outputStrides = external local_unnamed_addr addrspace(2) global [2 x <4 x i32>], align 4
```
Comment (pow2clk) [inline llvm/test/CodeGen/DirectX/legalize-memcpy.ll:4]: Does this pass come before scalarization? I ask because the native vectors won't be present in final DXIL until 6.9 and would make an odd choice if this came after scalarization.

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll [hunk 12]
```diff
@@ -0,0 +1,174 @@
...
+;
+  %1 = alloca [2 x half], align 2
+  %2 = alloca [2 x half], align 2
+  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %1)
+  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %2)
+  call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 2 dereferenceable(4) %2, ptr align 2 dereferenceable(4) %1, i32 4, i1 false)
+  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %2)
+  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %1)
+  ret void
+}
```
Comment (pow2clk) [inline llvm/test/CodeGen/DirectX/legalize-memcpy.ll:166]: It might be interesting to test memcpy from and to arrays of different sizes and perhaps just a bit longer than 2.

**Review by pow2clk — COMMENTED** [review]
Looks good! I really don't have any issues with the functionality, just some commenting, naming, testing suggestions and a question about when this pass is run.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 13]
```diff
@@ -246,6 +246,61 @@ downcastI64toI32InsertExtractElements(Instruction &I,
...
+                                ConstantInt *Length) {
+
+  uint64_t ByteLength = Length->getZExtValue();
+  if (ByteLength == 0)
+    return;
+
+  LLVMContext &Ctx = Builder.getContext();
+  const DataLayout &DL = Builder.GetInsertBlock()->getModule()->getDataLayout();
+
+  auto GetArrTyFromVal = [](Value *Val) -> ArrayType * {
```
[the remark this answers is not in the document]
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:259]: If you are talking about the type of `GetArrTyFromVal`, it is a lambda function so I think it has to be an `auto`.
If you are talking about the return type of the lambda function (`-> Array Type *`), the return statements all explicitly return a `dyn_cast<ArrayType>` and all its uses expect an `ArrayType *`, so `ArrayType *` is the most appropriate.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 6 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:297]: The asserts do ensure that the GEP is inbounds, so I think it should be fine to set `GEP.isInBounds()` which by definition also implies no unsigned signed wrapping (nusw)

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 7 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-memcpy.ll:21]: @pow2clk just suggested not having lifetime markers at all because they're not explicitly being tested here, and I do agree. So I will be removing all the lifetime markers from the test.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 14]
```diff
@@ -348,6 +427,7 @@ class DXILLegalizationPipeline {
     LegalizationPipeline.push_back(fixI8UseChain);
     LegalizationPipeline.push_back(downcastI64toI32InsertExtractElements);
     LegalizationPipeline.push_back(legalizeFreeze);
+    LegalizationPipeline.push_back(removeMemCpy);
```
[the remark this answers is not in the document]
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:430]: I don't think there is a good reason not to call it "legalizeMemCpy". I just followed what @farzonl did for memset.
I think "legalizeMemCpy" is a better name, so I will make a commit to change it to that.

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 11 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-memcpy.ll:4]: According to [DirectXTargetMachine.cpp:L110-L116](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/DirectX/DirectXTargetMachine.cpp#L110-L116) this legalize pass comes after scalarization.
The test `replace_2x4xint_global_memcpy_test` reflects that of LLVM IR I saw when compiling DML shaders, which use shader model 6.6, yet the alloca and the global variable clearly contain vector types.
If native vectors aren't supposed to be present in the final DXIL until 6.9, then I suppose something is going very wrong here?

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 12 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-memcpy.ll:166]: This implementation of memcpy asserts that the `src` and `dst` arrays are equivalent (both in element type and the number of elements). It would be straightforward to allow cases where the `src` and `dst` have equivalent element types but differing number of elements, however I didn't see this necessary to allow because the memcpys that we encounter so far (in DML) don't have such cases. This memcpy legalization may also not be needed anymore if #138788 determines that memcpy (and memset) can be prevented them from appearing in DXIL in the first place.

For sure I can add tests for array longer than 2 elements.

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 11 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-memcpy.ll:4]: I filed an issue regarding these vectors appearing in the IR after data scalarization and array flattening:
https://github.com/llvm/llvm-project/issues/140143

File: llvm/test/CodeGen/DirectX/legalize-memcpy.ll (hunk 12 above)
Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-memcpy.ll:149]: I added support for mismatched number of elements in the array types, and added a test for memcpy from and to arrays of different sizes.
