### PR TITLE
[clang] Enforce 1-based indexing for command line source locations

### LINKED ISSUE #139375: crashed in clang::Preprocessor::EnterMainSourceFile()
Stack trace
```
 #0 0x00000001050c55e4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1028515e4)
 #1 0x00000001050c36ac llvm::sys::RunSignalHandlers() (/Users/cheese/git/llvm-project/build/bin/clang-21+0x10284f6ac)
 #2 0x00000001050c4bb8 llvm::sys::CleanupOnSignal(unsigned long) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x102850bb8)
 #3 0x000000010501dc34 CrashRecoverySignalHandler(int) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1027a9c34)
 #4 0x000000019ab57624 (/usr/lib/system/libsystem_platform.dylib+0x1804ab624)
 #5 0x000000019ab1d88c (/usr/lib/system/libsystem_pthread.dylib+0x18047188c)
 #6 0x000000019aa26c60 (/usr/lib/system/libsystem_c.dylib+0x18037ac60)
 #7 0x000000019aa25eec (/usr/lib/system/libsystem_c.dylib+0x180379eec)
 #8 0x0000000107d268c0 clang::Preprocessor::EnterMainSourceFile() (.cold.1) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1054b28c0)
 #9 0x00000001077ef608 clang::Preprocessor::SetCodeCompletionPoint(clang::FileEntryRef, unsigned int, unsigned int) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x104f7b608)
#10 0x0000000105b5ab88 EnableCodeCompletion(clang::Preprocessor&, llvm::StringRef, unsigned int, unsigned int) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1032e6b88)
#11 0x0000000105b5a978 clang::CompilerInstance::createCodeCompletionConsumer() (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1032e6978)
#12 0x0000000105bcaea0 clang::ASTFrontendAction::ExecuteAction() (/Users/cheese/git/llvm-project/build/bin/clang-21+0x103356ea0)
#13 0x0000000105bca8f4 clang::FrontendAction::Execute() (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1033568f4)
#14 0x0000000105b5c78c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1032e878c)
#15 0x0000000105c44b78 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1033d0b78)
#16 0x0000000102879dec cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x100005dec)
#17 0x0000000102877ddc ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x100003ddc)
#18 0x00000001059bedf8 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(long) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x10314adf8)
#19 0x000000010501d8ec llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x1027a98ec)
#20 0x00000001059be86c clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const (/Users/cheese/git/llvm-project/build/bin/clang-21+0x10314a86c)
#21 0x0000000105989dac clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/Users/cheese/git/llvm-project/build/bin/clang-21+0x103115dac)
#22 0x0000000105989fb4 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const (/Users/cheese/git/llvm-project/build/bin/clang-21+0x103115fb4)
#23 0x00000001059a4970 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x103130970)
#24 0x0000000102876ea0 clang_main(int, char**, llvm::ToolContext const&) (/Users/cheese/git/llvm-project/build/bin/clang-21+0x100002ea0)
#25 0x00000001028839dc main (/Users/cheese/git/llvm-project/build/bin/clang-21+0x10000f9dc)
#26 0x000000019a77eb4c
```

input.cpp
```
int main() {
    std::cout;
    std::c
}
```

Command for reproduce
` ./bin/clang++ -fsyntax-only -Xclang -code-completion-at=input.cpp:5:0 input.cpp --target=x86_64-apple-macos11 --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

[input-55332e.cpp.txt](https://github.com/user-attachments/files/20139199/input-55332e.cpp.txt)
[input-55332e.sh.txt](https://github.com/user-attachments/files/20139198/input-55332e.sh.txt)

### PR DESCRIPTION
**Pull request by naveen-seth**
Fixes #139375

Clang expects command line source locations to be provided using 1-based indexing.
Currently, Clang does not reject zero as invalid argument for column or line number, which can cause Clang to crash.

This commit extends validation in `ParsedSourceLocation::FromString` to only accept (unsinged) non-zero integers.

### CODE REVIEW

File: clang/test/CodeCompletion/crash-if-zero-index.cpp [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// RUN: not %clang_cc1 -fsyntax-only -code-completion-at=%s:0:1 %s -o -
+// RUN: not %clang_cc1 -fsyntax-only -code-completion-at=%s:1:0 %s -o -
+
+// Related to #139375
+// Clang uses 1-based indexing for source locations given from the command-line.
+// Verify Clang doesn’t crash when 0 is given as line or column number.
```
Comment (cor3ntin) [inline clang/test/CodeCompletion/crash-if-zero-index.cpp:6]: Can you add a test using FileCheck that we produce a diagnostic?

**Comment by cor3ntin** [comment]
Thanks for working on that.
I think it might better to do that check where `ParsedSourceLocation::FromString` is called, so that we can have a proper
front-end diagnostics for it (search for `err_fe_invalid_code_complete_file` and `OPT_code_completion_at`)

**Comment by naveen-seth** [comment]
> Thanks for working on that. I think it might better to do that check where `ParsedSourceLocation::FromString` is called, so that we can have a proper front-end diagnostics for it (search for `err_fe_invalid_code_complete_file` and `OPT_code_completion_at`)

Thank you for the quick review! :)

I added the check in `ParsedSourceLocation::FromString` because it also helps catch the same crash for callers of `ParsedSourceRange::FromString`, which also uses `ParsedSourceLocation::FromString`.

For example, the following would also crash (hitting the same assert as the one this PR fixes)

```bash
touch empty.cpp
clang-refactor local-rename -selection=input.cpp:1:1-1:0 -new-name=test -v input.cpp 
```
<details>
<summary> Full crash log</summary>

```
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "input.cpp"
No compilation database found in /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-debug-env/debugging-139375 or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
clang-refactor: /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Basic/SourceManager.cpp:1666: SourceLocation clang::SourceManager::translateLineCol(FileID, unsigned int, unsigned int) const: Assertion `Line && Col && "Line and column should start from 1!"' failed.
 #0 0x0000562e7ef658cd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/llvm/lib/Support/Unix/Signals.inc:804:11
 #1 0x0000562e7ef65e0b PrintStackTraceSignalHandler(void*) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/llvm/lib/Support/Unix/Signals.inc:888:1
 #2 0x0000562e7ef63f2f llvm::sys::RunSignalHandlers() /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/llvm/lib/Support/Signals.cpp:105:5
 #3 0x0000562e7ef664e9 SignalHandler(int, siginfo_t*, void*) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/llvm/lib/Support/Unix/Signals.inc:418:7
 #4 0x00007f6311a5e250 (/lib/x86_64-linux-gnu/libc.so.6+0x45250)
 #5 0x00007f6311abcf1c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0xa3f1c)
 #6 0x00007f6311a5e19e raise (/lib/x86_64-linux-gnu/libc.so.6+0x4519e)
 #7 0x00007f6311a41902 abort (/lib/x86_64-linux-gnu/libc.so.6+0x28902)
 #8 0x00007f6311a4181e (/lib/x86_64-linux-gnu/libc.so.6+0x2881e)
 #9 0x00007f6311a547c7 (/lib/x86_64-linux-gnu/libc.so.6+0x3b7c7)
#10 0x0000562e7fbee816 clang::SourceManager::translateLineCol(clang::FileID, unsigned int, unsigned int) const /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Basic/SourceManager.cpp:1668:11
#11 0x0000562e7ed5dc34 (anonymous namespace)::SourceRangeSelectionArgument::forAllRanges(clang::SourceManager const&, llvm::function_ref<void (clang::SourceRange)>) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/tools/clang-refactor/ClangRefactor.cpp:131:12
#12 0x0000562e7ed5eb2b (anonymous namespace)::ClangRefactorTool::callback(clang::ASTContext&) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/tools/clang-refactor/ClangRefactor.cpp:418:11
#13 0x0000562e7ed5e840 (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)::operator()(clang::ASTContext&) const /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/tools/clang-refactor/ClangRefactor.cpp:475:35
#14 0x0000562e7ed5e80d void std::__invoke_impl<void, (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)&, clang::ASTContext&>(std::__invoke_other, (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)&, clang::ASTContext&) /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/invoke.h:61:7
#15 0x0000562e7ed5e7ad std::enable_if<is_invocable_r_v<void, (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)&, clang::ASTContext&>, void>::type std::__invoke_r<void, (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)&, clang::ASTContext&>((anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)&, clang::ASTContext&) /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/invoke.h:117:5
#16 0x0000562e7ed5e6f5 std::_Function_handler<void (clang::ASTContext&), (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::'lambda'(clang::ASTContext&)>::_M_invoke(std::_Any_data const&, clang::ASTContext&) /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/std_function.h:290:2
#17 0x0000562e7ed774c6 std::function<void (clang::ASTContext&)>::operator()(clang::ASTContext&) const /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/std_function.h:591:2
#18 0x0000562e7ed5f3b1 (anonymous namespace)::ClangRefactorTool::getFrontendActionFactory()::ToolASTConsumer::HandleTranslationUnit(clang::ASTContext&) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/tools/clang-refactor/ClangRefactor.cpp:441:7
#19 0x0000562e80984ffb clang::ParseAST(clang::Sema&, bool, bool) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Parse/ParseAST.cpp:191:12
#20 0x0000562e800193d9 clang::ASTFrontendAction::ExecuteAction() /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Frontend/FrontendAction.cpp:1345:1
#21 0x0000562e80018e26 clang::FrontendAction::Execute() /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Frontend/FrontendAction.cpp:1229:7
#22 0x0000562e7ff2f0b3 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Frontend/CompilerInstance.cpp:1057:23
#23 0x0000562e8044f193 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Tooling/Tooling.cpp:466:14
#24 0x0000562e8044f05b clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Tooling/Tooling.cpp:441:18
#25 0x0000562e8044e217 clang::tooling::ToolInvocation::run() /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Tooling/Tooling.cpp:426:3
#26 0x0000562e80450382 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/lib/Tooling/Tooling.cpp:624:11
#27 0x0000562e7ed595ea main /home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/clang/tools/clang-refactor/ClangRefactor.cpp:636:38
#28 0x00007f6311a433b8 (/lib/x86_64-linux-gnu/libc.so.6+0x2a3b8)
#29 0x00007f6311a4347b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a47b)
#30 0x0000562e7ed591e5 _start (/home/nav/.distrobox/ubuntu-24-10-compiler-dev/llvm-project-dev/build/bin/clang-refactor+0x23741e5)
Aborted (core dumped)
```

</details>

(And similar invalid inputs like `<file>:<line>:-1` are caught in `ParsedSourceLocation::FromString`)


I could move the check up to the locations where `ParsedSourceLocation::FromString` and `ParsedSourceRange::FromString` are called, but I believe it should be possible to provide a proper front-end diagnostic without moving the check.
For context, this PR currently changes the behavior of the crash in #139375 to also omit the `diag::err_drv_invalid_value` diagnostic, but I could adjust it to hint at the right format.

What do you think is best here?

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! The change should come with a release note in `clang/docs/ReleaseNotes.rst` so users know about the improvement.

Otherwise, I think this is going in a reasonable direction.

File: clang/include/clang/Frontend/CommandLineSourceLoc.h [hunk 2]
```diff
@@ -89,8 +92,13 @@ struct ParsedSourceRange {
         // probably belongs to the filename which menas the whole
         // string should be parsed.
         RangeSplit.first = Str;
-      } else
+      } else {
+        // Column and line numbers are 1-based
```
Comment (MaskRay) [inline clang/include/clang/Frontend/CommandLineSourceLoc.h:96]: Ensure that full sentences in commends end with `.`

Remove brace for this single-line-simple-body case per https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

File: clang/test/CodeCompletion/crash-command-line-source-loc-zero.cpp [hunk 3]
```diff
@@ -0,0 +1,12 @@
+// Related to #139375
```
Comment (MaskRay) [inline clang/test/CodeCompletion/crash-command-line-source-loc-zero.cpp:1]: I don't why some regression tests are named `crash-*`, but I would not name this `crash-*`.

I'd just name this source-loc-zero.cpp and change this comment to `// Regression test for #139375`

File: clang/test/Refactor/crash-command-line-source-loc-zero.cpp [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+// RUN: not clang-refactor local-rename -selection=%s:1:0-1:1 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+
+// For range end:
+// RUN: not clang-refactor local-rename -selection=%s:1:1-0:1 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+// RUN: not clang-refactor local-rename -selection=%s:1:1-1:0 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+
+// CHECK-DIAG: error: '-selection' option must be specified using <file>:<line>:<column>
```
Comment (MaskRay) [inline clang/test/Refactor/crash-command-line-source-loc-zero.cpp:17]: If the diagnostic is on one line, use a single CHECK.

Multiple CHECK accepts output that we don't expect.

We don't rigidly require line wrapping for tests.

**Review by MaskRay — APPROVED** [review]
LGTM with a few nits. Please give other reviewers some time to chime in. Click the "Re-request review" circle icon beside reviewer usernames after you make an update.

File: clang/test/Refactor/source-loc-zero.cpp [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+// RUN: not clang-refactor local-rename -selection=%s:1:0-1:1 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+
+// For range end:
+// RUN: not clang-refactor local-rename -selection=%s:1:1-0:1 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+// RUN: not clang-refactor local-rename -selection=%s:1:1-1:0 -new-name=test %s 2>&1 \
+// RUN:     | FileCheck -check-prefix=CHECK-DIAG %s
+
+// CHECK-DIAG: error: '-selection' option must be specified using <file>:<line>:<column> or <file>:<line>:<column>-<line>:<column> format, where <line> and <column> are integers greater than zero.
```
Comment (AaronBallman) [inline clang/test/Refactor/source-loc-zero.cpp:17]: Can you add a newline to the end of the file?

**Review by AaronBallman — APPROVED** [review]
Other than a nit, LGTM!

**Comment by naveen-seth** [comment]
Thank you for reviewing!
(And apologies for the formatting and coding-standard issues on my end!)

**Comment by AaronBallman** [comment]
> Thank you for reviewing! (And apologies for the formatting and coding-standard issues on my end.)

No need to apologize, that sort of thing comes up! :-)

Do you need one of us to merge the changes on your behalf?
