### PR TITLE
[clangd] Guard against trivial FunctionProtoTypeLoc when creating inlay hints

### LINKED ISSUE #142608: [clangd] crash in InlayHints.cpp on trivial FunctionProtoTypeLoc
The `usage.c` in the `git` project will result in this.

This is a minimal reproduce:

``` c
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>

#define NORETURN __attribute__((__noreturn__))
#define NORETURN_PTR __attribute__((__noreturn__))
typedef void (*report_fn)(const char *, va_list params);

static void NORETURN die_builtin(const char *err, va_list params)
{
	exit(128);
}

static NORETURN_PTR report_fn die_routine = die_builtin;

void NORETURN die(const char *err, ...)
{
	va_list params;

	va_start(params, err);
	die_routine(err, params);
	va_end(params);
}
```

The code itself is valid. But the clangd crash:

``` text
I[22:05:07.654] clangd version 19.1.2 (https://github.com/llvm/llvm-project 7ba7d8e2f7b6445b60679da826210cdde29eaf8b)
I[22:05:07.654] Features: linux+grpc
I[22:05:07.654] PID: 734406
I[22:05:07.654] Working directory: /home/npc1054657282/my_projects/clangd-crash-minimal
I[22:05:07.654] argv[0]: /home/npc1054657282/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/19.1.2/clangd_19.1.2/bin/clangd
I[22:05:07.654] argv[1]: --compile-commands-dir=.vscode
E[22:05:07.654] Path specified by --compile-commands-dir does not exist. The argument will be ignored.
I[22:05:07.654] Starting LSP over stdin/stdout
I[22:05:07.655] <-- initialize(0)
I[22:05:07.657] --> reply:initialize(0) 1 ms
I[22:05:07.683] <-- initialized
I[22:05:07.686] <-- textDocument/didOpen
I[22:05:07.688] Failed to find compilation database for /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c
I[22:05:07.688] ASTWorker building file /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c version 464 with command clangd fallback
[/home/npc1054657282/my_projects/clangd-crash-minimal]
/usr/bin/clang -resource-dir=/home/npc1054657282/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/19.1.2/clangd_19.1.2/lib/clang/19 -- /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c
I[22:05:07.691] --> textDocument/clangd.fileStatus
I[22:05:07.728] Built preamble of size 398024 for file /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c version 464 in 0.04 seconds
I[22:05:07.730] Indexing c17 standard library in the context of /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c
I[22:05:07.730] --> textDocument/clangd.fileStatus
I[22:05:07.730] --> textDocument/clangd.fileStatus
I[22:05:07.730] --> workspace/semanticTokens/refresh(0)
I[22:05:07.740] <-- reply(0)
I[22:05:07.752] --> textDocument/publishDiagnostics
I[22:05:07.752] --> textDocument/inactiveRegions
I[22:05:07.752] --> textDocument/clangd.fileStatus
I[22:05:07.859] <-- textDocument/documentSymbol(1)
I[22:05:07.859] <-- textDocument/documentLink(2)
I[22:05:07.859] <-- textDocument/inlayHint(3)
I[22:05:07.859] <-- textDocument/semanticTokens/full(4)
I[22:05:07.859] <-- textDocument/codeAction(5)
I[22:05:07.860] --> reply:textDocument/documentSymbol(1) 1 ms
I[22:05:07.860] --> reply:textDocument/documentLink(2) 1 ms
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  clangd          0x000000000055715b
1  clangd          0x0000000000554fbe
2  clangd          0x0000000000557af6
3  libpthread.so.0 0x00007f15ee7ed1d0
4  clangd          0x00000000016e51ba
5  clangd          0x00000000016e2d2c
6  clangd          0x00000000016dcf39
7  clangd          0x00000000016d1bef
8  clangd          0x00000000016e80aa
9  clangd          0x00000000016cd610
10 clangd          0x00000000016cf545
11 clangd          0x00000000016cad1e
12 clangd          0x00000000015f573f
13 clangd          0x000000000179856c
14 clangd          0x000000000178fa0b
15 clangd          0x000000000178e460
16 clangd          0x000000000190f7c1
17 libpthread.so.0 0x00007f15ee7e23fb
18 libc.so.6       0x00007f15ee4e2e83 clone + 67
Signalled during AST worker action: InlayHints
  Filename: usage.c
  Directory: /home/npc1054657282/my_projects/clangd-crash-minimal
  Command Line: /usr/bin/clang -resource-dir=/home/npc1054657282/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/19.1.2/clangd_19.1.2/lib/clang/19 -- /home/npc1054657282/my_projects/clangd-crash-minimal/usage.c
  Version: 464
[Error - 10:05:08 PM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:05:08 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 10:05:08 PM] Request textDocument/semanticTokens/full failed.
[object Object]
[Error - 10:05:08 PM] Request textDocument/codeAction failed.
[object Object]
```

### PR DESCRIPTION
**Pull request by HighCommander4**
Fixes https://github.com/llvm/llvm-project/issues/142608

### CODE REVIEW

File: clang-tools-extra/clangd/InlayHints.cpp [hunk 1]
```diff
@@ -368,6 +368,14 @@ static FunctionProtoTypeLoc getPrototypeLoc(Expr *Fn) {
   }
 
   if (auto F = Target.getAs<FunctionProtoTypeLoc>()) {
+    // In some edge cases the AST can contain a "trivial" FunctionProtoTypeLoc
+    // which has null parameters. Avoid these as they don't contain useful
+    // information.
+    for (const auto *Param : F.getParams()) {
+      if (!Param)
+        return {};
+    }
```
Comment (zyn0217) [inline clang-tools-extra/clangd/InlayHints.cpp]:
```suggestion
if (llvm::all_of(F.getParams(), llvm::identity<ParmVarDecl*>()))
  return F;
```

**Review by zyn0217 — APPROVED** [review]
LGTM as a workaround

Though I'm still wondering if there's an underlying bug in Parser

File: clang-tools-extra/clangd/InlayHints.cpp [hunk 2]
```diff
@@ -368,6 +368,14 @@ static FunctionProtoTypeLoc getPrototypeLoc(Expr *Fn) {
   }
 
   if (auto F = Target.getAs<FunctionProtoTypeLoc>()) {
+    // In some edge cases the AST can contain a "trivial" FunctionProtoTypeLoc
```
Comment (hokein) [inline clang-tools-extra/clangd/InlayHints.cpp:372]: nit: We have a duplicated one in ` SemaCodeComplete.cpp`, see the `FIXME` on line 337. I guess the same issue  should happen there as well (signaturehelp?). I see options 1) duplicate the workaround 2) unify these two implementations. Either works for me.

File: clang-tools-extra/clangd/InlayHints.cpp [hunk 3]
```diff
@@ -368,6 +368,14 @@ static FunctionProtoTypeLoc getPrototypeLoc(Expr *Fn) {
...
+    // which has null parameters. Avoid these as they don't contain useful
+    // information.
+    for (const auto *Param : F.getParams()) {
```
Comment (hokein) [inline clang-tools-extra/clangd/InlayHints.cpp]: This smells like a clang bug — having a nullptr parameter shouldn’t happen. That said, I’m not objecting to the change here; it makes the tool more robust.

**Review by hokein — APPROVED** [review]

File: clang-tools-extra/clangd/InlayHints.cpp (hunk 2 above)
Comment (HighCommander4) [reply clang-tools-extra/clangd/InlayHints.cpp:372]: Thanks for the reminder about this. Now that we've upstreamed `HeuristicResolver`, it's a good place for a unified implementation of this sort of thing. I'll do that in https://github.com/llvm/llvm-project/issues/143240.

File: clang-tools-extra/clangd/InlayHints.cpp (hunk 3 above)
Comment (HighCommander4) [reply clang-tools-extra/clangd/InlayHints.cpp]: My impression from having read some of the related code is that it's a known deficiency that having null parameters can sometimes happen.

`TypeLoc` has a method named [`initialize()`](https://searchfox.org/llvm/rev/269c29ae67e54bd3243535a7c58d0f30d1eb9036/clang/include/clang/AST/TypeLoc.h#201), which is described as follows:

```c++
  /// Initializes this to state that every location in this
  /// type is the given location.
  ///
  /// This method exists to provide a simple transition for code that
  /// relies on location-less types.
  void initialize(ASTContext &Context, SourceLocation Loc) const {
```

The implementation of `initialize` for `FunctionTypeLoc` [does set the parameters to null](https://searchfox.org/llvm/rev/269c29ae67e54bd3243535a7c58d0f30d1eb9036/clang/include/clang/AST/TypeLoc.h#1579).

And there are various places in the code where we call `initialize`. In addition to the `noreturn` scenario exercised in this patch's testcase, which will be improved in https://github.com/llvm/llvm-project/pull/143143, another notable call site is [`ASTContext::getTrivialTypeSourceInfo`](https://searchfox.org/llvm/rev/269c29ae67e54bd3243535a7c58d0f30d1eb9036/clang/lib/AST/ASTContext.cpp#3132). That in turn has [many callers](https://searchfox.org/llvm/search?q=symbol:_ZNK5clang10ASTContext24getTrivialTypeSourceInfoENS_8QualTypeENS_14SourceLocationE&redirect=false), including [this one](https://searchfox.org/llvm/rev/269c29ae67e54bd3243535a7c58d0f30d1eb9036/clang/lib/Sema/SemaType.cpp#5679) used to handle an invalid declarator.

File: clang-tools-extra/clangd/InlayHints.cpp (hunk 2 above)
Comment (HighCommander4) [reply clang-tools-extra/clangd/InlayHints.cpp:372]: Posted https://github.com/llvm/llvm-project/pull/143345 for this.
