### PR TITLE
Reapply "[coro][CoroSplit] Use `llvm.lifetime.end` to compute putting objects on the frame vs the stack (#90265)

### LINKED ISSUE #86580: [coroutines] LLVM incorrectly allocates variables on the coroutine stack
Example:

```cpp
struct StubbyMessageBuffer {
  StubbyMessageBuffer();
  ~StubbyMessageBuffer();
};

// Reduced version of absl::cleanup
class Cleanup  {
 public:
  Cleanup(void (*cleanup)()) : cleanup_(cleanup){}

  ~Cleanup() {
    cleanup_();
  }

 private:
  // Strangely enough this doesn't work if cleanup_ is a std::function
  void (*cleanup_)();
};

MyTask FooBar() {
  StubbyMessageBuffer smb;
  #ifdef DO_CLEANUP
  // This is produced by a LOG(FATAL) or a LOG(QFATAL)
  Cleanup cu([]{abort();});
  #endif
  co_await 1;
  co_return;
}
```

When compiled with `-O1` and `DO_CLEANUP` undefined, `smb` is constructed and stored in the coroutine frame:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %ref.tmp3.reload.addr = getelementptr inbounds i8, ptr %0, i64 24
  %smb.reload.addr = getelementptr inbounds i8, ptr %0, i64 18
```

However, if `DO_CLEANUP` *is* defined, `smb` is no longer stored on the frame; instead, it is constructed and allocated in the coroutine resume function:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %smb = alloca %struct.StubbyMessageBuffer, align 1
```

This behavior is wrong; the constructor for `StubbyMessageBuffer` may have side effects, and if `FooBar()` calls a function that takes a reference / pointer to `smb`, `smb` still does not get created on the coroutine frame object, and we get a segfault.

godbolt: https://godbolt.org/z/oMfKqExMK

### PR DESCRIPTION
**Pull request by alanzhao1**
This reverts commit 924384161ffceda08099536dd07a953299a69b53.

This reland addresses the performance regressions seen in #90265 by retaining the original definition of `isPotentiallyReachableFromMany(...)` instead of reimplementing it with `isManyPotentiallyReachableFromMany(...)`.

Fixes #86580

### CODE REVIEW

File: llvm/lib/Analysis/CFG.cpp [hunk 1]
```diff
@@ -158,7 +158,7 @@ bool llvm::isPotentiallyReachableFromMany(
   const Loop *StopLoop = LI ? getOutermostLoop(LI, StopBB) : nullptr;
 
   unsigned Limit = DefaultMaxBBsToExplore;
-  SmallPtrSet<const BasicBlock*, 32> Visited;
+  SmallPtrSet<const BasicBlock *, 32> Visited;
```
Comment (ChuanqiXu9) [inline llvm/lib/Analysis/CFG.cpp:161]: Unnecessary change.

**Review by ChuanqiXu9 — COMMENTED** [review]
The code duplication is slightly not good. Can we try to mitigate such problems by some template techniques?

For example, (may be):

```
if constexpr (isMany) {
    if (StopSet.contains(BB))
      return true;
} else {
    if (BB == StopBB) // or BB == *StopSet.begin()
      return true;
}
```

**Comment by nikic** [comment]
I was curious if just the SmallPtrSet change would be enough for the original implementation, but apparently not: https://llvm-compile-time-tracker.com/index.php?branch=nikic/perf/reachable It is a significant improvement, but not enough.

File: llvm/lib/Analysis/CFG.cpp [hunk 2]
```diff
@@ -204,6 +204,91 @@ bool llvm::isPotentiallyReachableFromMany(
...
+  if (LI && ExclusionSet) {
+    for (auto *BB : *ExclusionSet) {
+      if (const Loop *L = getOutermostLoop(LI, BB))
+        LoopsWithHoles.insert(L);
+    }
+  }
+
+  llvm::DenseMap<const BasicBlock *, const Loop *> StopLoops;
+  for (auto *StopBB : StopSet)
+    StopLoops[StopBB] = LI ? getOutermostLoop(LI, StopBB) : nullptr;
```
Comment (nikic) [inline llvm/lib/Analysis/CFG.cpp:238]: Why do we need this to be a map? Shouldn't this also be a set of StopLoops and then just check contains below?

Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp:238]: We need the corresponding `Loop *` for each `StopBB`.

Calling `getOutermostLoop(...)` isn't cheaper - we perform a map lookup and repeatedly call `Loop::getParent(...)` until we get the outermost loop.

Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp:238]: Fixed.

Comment (nikic) [reply llvm/lib/Analysis/CFG.cpp:238]: I don't get it -- why can't we do something like this? https://github.com/llvm/llvm-project/commit/1c48a3a138c4e0126abf4cc255c56fd5b65129d5

Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp]: Sorry, I misread your comment. Yeah, that would work. Thanks for the suggestion!

**Comment by alanzhao1** [comment]
> The code duplication is slightly not good. Can we try to mitigate such problems by some template techniques?
> 
> For example, (may be):
> 
> ```
> if constexpr (isMany) {
>     if (StopSet.contains(BB))
>       return true;
> } else {
>     if (BB == StopBB) // or BB == *StopSet.begin()
>       return true;
> }
> ```

Hmm...would making `StopBB`/`StopSet` a `std::variant<const BasicBlock *,  const SmallPtrSetImpl<const BasicBlock *> &>` work?

**Comment by ChuanqiXu9** [comment]
> > The code duplication is slightly not good. Can we try to mitigate such problems by some template techniques?
> > For example, (may be):
> > ```
> > if constexpr (isMany) {
> >     if (StopSet.contains(BB))
> >       return true;
> > } else {
> >     if (BB == StopBB) // or BB == *StopSet.begin()
> >       return true;
> > }
> > ```
> 
> Hmm...would making `StopBB`/`StopSet` a `std::variant<const BasicBlock *, const SmallPtrSetImpl<const BasicBlock *> *>` work?
> 
> EDIT: changed the second `std::variant` template parameter to a pointer as its template parameters can't be reference types.

Maybe it can be slightly better to  have a isReachableImpl template function, where the type of `stop` can be a template, then we can judge the type directly in the `Impl` function. WDYT?

**Comment by alanzhao1** [comment]
> > > The code duplication is slightly not good. Can we try to mitigate such problems by some template techniques?
> > > For example, (may be):
> > > ```
> > > if constexpr (isMany) {
> > >     if (StopSet.contains(BB))
> > >       return true;
> > > } else {
> > >     if (BB == StopBB) // or BB == *StopSet.begin()
> > >       return true;
> > > }
> > > ```
> > 
> > 
> > Hmm...would making `StopBB`/`StopSet` a `std::variant<const BasicBlock *, const SmallPtrSetImpl<const BasicBlock *> *>` work?
> > EDIT: changed the second `std::variant` template parameter to a pointer as its template parameters can't be reference types.
> 
> Maybe it can be slightly better to have a isReachableImpl template function, where the type of `stop` can be a template, then we can judge the type directly in the `Impl` function. WDYT?

Personally, I'm leaning towards using `std::variant` because template type parameters don't have any information about the underlying type (LLVM hasn't migrated to C++20 yet, so we don't have concepts), so the only feedback we have is that the code doesn't compile because a type doesn't have a method. A variant parameter however does retain type information, and the code would be virtually identical to what you propose - e.g.

```cpp
const auto StopBB** = std::get_if<const BasicBlock *>(StopBBOrSet);
const auto StopSet** = std::get_if<const SmallPtrSetImpl<const BasicBlock *> *>(StopBBOrSet);
if (StopSet) {
    if ((*StopSet)->contains(BB))
      return true;
} else {
    if (BB == *StopBB)
      return true;
}
```

**Comment by nikic** [comment]
@alanzhao1 std::variant is inefficient on multiple levels. It is very unlikely to be suitable in cases where the whole point is to have efficient code.

**Comment by alanzhao1** [comment]
Code for `isPotentiallyReachableFromMany(...)` and `isManyPotentiallyReachableFromMany(...)` has been deduplicated using templates.

File: llvm/lib/Analysis/CFG.cpp [hunk 3]
```diff
@@ -130,14 +130,35 @@ static const Loop *getOutermostLoop(const LoopInfo *LI, const BasicBlock *BB) {
   return L ? L->getOutermostLoop() : nullptr;
 }
 
-bool llvm::isPotentiallyReachableFromMany(
-    SmallVectorImpl<BasicBlock *> &Worklist, const BasicBlock *StopBB,
-    const SmallPtrSetImpl<BasicBlock *> *ExclusionSet, const DominatorTree *DT,
-    const LoopInfo *LI) {
-  // When the stop block is unreachable, it's dominated from everywhere,
+template <class T, bool IsMany>
```
Comment (ChuanqiXu9) [inline llvm/lib/Analysis/CFG.cpp:133]:
```suggestion
template <class StopT, bool IsManyStop>
```

nit

File: llvm/lib/Analysis/CFG.cpp [hunk 4]
```diff
@@ -130,14 +130,35 @@ static const Loop *getOutermostLoop(const LoopInfo *LI, const BasicBlock *BB) {
...
+static bool isReachableImpl(SmallVectorImpl<BasicBlock *> &Worklist,
+                            const T *StopBBOrSet,
+                            const SmallPtrSetImpl<BasicBlock *> *ExclusionSet,
+                            const DominatorTree *DT, const LoopInfo *LI) {
+  const BasicBlock *StopBB;
+  const SmallPtrSetImpl<const BasicBlock *> *StopSet;
```
Comment (ChuanqiXu9) [inline llvm/lib/Analysis/CFG.cpp:139]: Why `SmallPtrSetImpl`?

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. Maybe @nikic wants to have perf test.

File: llvm/lib/Analysis/CFG.cpp [hunk 5]
```diff
@@ -130,14 +130,35 @@ static const Loop *getOutermostLoop(const LoopInfo *LI, const BasicBlock *BB) {
...
+
+  // SmallPtrSetImpl is incompatible with LLVM's casting functions.
+  if constexpr (IsMany)
+    StopSet =
+        static_cast<const SmallPtrSetImpl<const BasicBlock *> *>(StopBBOrSet);
+  else
+    StopBB = static_cast<const BasicBlock *>(StopBBOrSet);
```
Comment (nikic) [inline llvm/lib/Analysis/CFG.cpp:146]: This is all pretty ugly ... could the code be simplified by using something like this maybe?
```
class SingleEntrySet {
  T Elem;
  SingleEntrySet(T Elem) : Elem(Elem) {}
  bool contains(T Other) const { return Elem == Other; }
}
```

File: llvm/lib/Analysis/CFG.cpp (hunk 4 above)
Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp:139]: The class naming is kinda backwards and confusing - `SmallPtrSet` inherts **from** `SmallPtrSetImpl`, not the other way around.

`SmallPtrSet` has an `int SmallSize` template parameter, so by using the base class, we don't restrict the size of the passed `SmallPtrSet`.

**Comment by nikic** [comment]
> LGTM. Maybe @nikic wants to have perf test.

I don't see any compile-time impact with this version anymore.

File: llvm/lib/Analysis/CFG.cpp (hunk 5 above)
Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp:146]: If I understand your comment correctly, you're suggesting that I pass a `SingleEntrySet<const BasicBlock *>` to `isReachableImpl(...)` when implementing `isPotentiallyReachableFromMany(...)` in order to remove all the `if` statements. This would require `SingleEntrySet` to be iterable (since we iterate through the elements of `StopSet`), which drives up the complexity of the class further.

(We could do something like

```cpp
template <class T>
class SingleEntrySet {
  using iterator = T*;
  T Elem;  
  iterator begin() { return &Elem; }
  iterator end() { return &Elem + 1; }
};
```

but this is UB)

Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp:146]: Friendly ping @nikic - any comments?

Comment (nikic) [reply llvm/lib/Analysis/CFG.cpp:146]: > but this is UB

Why would that be UB?

Comment (nikic) [reply llvm/lib/Analysis/CFG.cpp:146]: Something like https://github.com/nikic/llvm-project/commit/932822472eeba688e5bfcb6a3ffc6c0f79f69dd4, though it would be nice to also avoid the StopLoops conditional...

I don't think we need StopBBReachable -- setting DT to nullptr if any one is unreachable is fine here (DT is only an optimization, and unreachable block is an unlikely edge case).

**Comment by alanzhao1** [comment]
@nikic do you want to rerun the compile time tests again to see if using `SingleEntrySet` causes any compile-time regressions?

**Comment by nikic** [comment]
@alanzhao1 This still causes a regression, but it's possible to avoid it by removing the StopBBReachable set: https://github.com/llvm/llvm-project/commit/bfc261b1c061b952992957e8892ce851afd6f84f We don't really need this set, it's okay to set DT to nullptr if any of the stop BBs is not reachable.

File: llvm/lib/Analysis/CFG.cpp [hunk 6]
```diff
@@ -130,14 +130,20 @@ static const Loop *getOutermostLoop(const LoopInfo *LI, const BasicBlock *BB) {
   return L ? L->getOutermostLoop() : nullptr;
 }
 
-bool llvm::isPotentiallyReachableFromMany(
-    SmallVectorImpl<BasicBlock *> &Worklist, const BasicBlock *StopBB,
-    const SmallPtrSetImpl<BasicBlock *> *ExclusionSet, const DominatorTree *DT,
-    const LoopInfo *LI) {
-  // When the stop block is unreachable, it's dominated from everywhere,
+template <class StopSetT, bool IsManyStop>
```
Comment (nikic) [inline llvm/lib/Analysis/CFG.cpp:133]: You no longer need IsManyStop.

File: llvm/lib/Analysis/CFG.cpp [hunk 7]
```diff
@@ -204,6 +221,43 @@ bool llvm::isPotentiallyReachableFromMany(
...
+public:
+  using iterator = T *;
+  using const_iterator = const T *;
+
+  SingleEntrySet(T Elem) : Elem(Elem) {}
+
+  bool contains(T Other) const { return Elem == Other; }
+
+  iterator begin() { return &Elem; }
+  iterator end() { return &Elem + 1; }
```
Comment (nikic) [inline llvm/lib/Analysis/CFG.cpp:234]: I don't think the non-const methods are necessary.

Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp]: Done.

File: llvm/lib/Analysis/CFG.cpp (hunk 6 above)
Comment (alanzhao1) [reply llvm/lib/Analysis/CFG.cpp]: Done.

**Comment by alanzhao1** [comment]
Ping. Any more comments?

**Comment by nikic** [comment]
> @alanzhao1 This still causes a regression, but it's possible to avoid it by removing the StopBBReachable set: [bfc261b](https://github.com/llvm/llvm-project/commit/bfc261b1c061b952992957e8892ce851afd6f84f) We don't really need this set, it's okay to set DT to nullptr if any of the stop BBs is not reachable.

This comment is still open.

**Comment by alanzhao1** [comment]
> > @alanzhao1 This still causes a regression, but it's possible to avoid it by removing the StopBBReachable set: [bfc261b](https://github.com/llvm/llvm-project/commit/bfc261b1c061b952992957e8892ce851afd6f84f) We don't really need this set, it's okay to set DT to nullptr if any of the stop BBs is not reachable.
> 
> This comment is still open.

Sorry I missed this! Done

File: llvm/lib/Analysis/CFG.cpp [hunk 8]
```diff
@@ -155,20 +162,31 @@ bool llvm::isPotentiallyReachableFromMany(
     }
   }
 
-  const Loop *StopLoop = LI ? getOutermostLoop(LI, StopBB) : nullptr;
+  SmallPtrSet<const Loop *, 2> StopLoops;
+
```
Comment (nikic) [inline llvm/lib/Analysis/CFG.cpp:166]: Nit: Drop this empty line.

**Review by nikic — APPROVED** [review]
The CFG changes LGTM. I assume the coroutine changes have already been previously reviewed.
