### PR TITLE
[clang-format] Fix AllowShortLambdasOnASingleLine interfering with lambda brace wrapping.

### LINKED ISSUE #81845: [clang-format] BraceWrapping.BeforeLambdaBody can fail to apply when AllowShortLambdasOnASingleLine is enabled
With the following style:

```
ColumnLimit: 30
BreakBeforeBraces: Allman
AllowShortLambdasOnASingleLine: All
```

The following code can be misformatted with the lambda body brace not being wrapped.
(This doesn't occur when `AllowShortLambdasOnASingleLine` is `None`)

Input:

```cpp
void f()
{
  std::for_each(
      c.begin(), c.end(),
      [](const auto &Item)
      {
        LongFunctionName(
            Item);
      });
}
```

Output:

```cpp
void f()
{
  std::for_each(
      c.begin(), c.end(),
      [](const auto &Item) {
        LongFunctionName(
            Item);
      });
}
```

### PR DESCRIPTION
**Pull request by rmarker**
Fix an issue where the lambda body left brace could sometimes fail to be wrapped when AllowShortLambdasOnASingleLine is enabled.

Now, when BraceWrapping.BeforeLambdaBody is enabled, if the brace is not wrapped, we prevent breaks in the lambda body.

Resolves #81845

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -22893,6 +22893,19 @@ TEST_F(FormatTest, FormatsLambdas) {
                LLVMWithBeforeLambdaBody);
   verifyFormat("FctWithTwoParams_SLS_All([]() { return 43; }, 87);",
                LLVMWithBeforeLambdaBody);
+  verifyFormat(
+      "FctWithTwoParams_SLS_All(\n"
+      "    87, []() { return LongLineThatWillForceBothParamsToNewLine(); });\n",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:22898]:
```suggestion
      "    87, []() { return LongLineThatWillForceBothParamsToNewLine(); });",
```

**Review by owenca — APPROVED** [review]
