### PR TITLE
[Clang] [CodeGen] Perform derived-to-base conversion on explicit object parameter in lambda

### LINKED ISSUE #87210: [Clang] Crash when taking the address of a capture in a lambda with an explicit object parameter in overload pattern
Just documenting this here in case anyone else runs into this; from what I can tell, ~~#84473 already fixes this. I haven’t really looked into this case in particular, but presumably, it’s broken because we currently erroneously treat by-reference captures as dependent in deducing-`this` lambdas even though they shouldn’t be.~~ It was broken because of that, but the underlying problem is a different one. See below.

This asserts in codegen (https://godbolt.org/z/1czjnznMK):
```C++
template <typename... Ts>
struct Overloaded : Ts... {
    using Ts::operator()...;
};

template <typename... Ts>
Overloaded(Ts...) -> Overloaded<Ts...>;

void f() {
    int x;
    Overloaded o {
        [&](this auto& self) {
            (void) &x;
        }
    };
    o();
}
```

Assertion:
```
clang++: /root/llvm-project/clang/lib/CodeGen/CGValue.h:277: 
void clang::CodeGen::LValue::initializeSimpleLValue(clang::CodeGen::Address, clang::QualType, clang::CodeGen::LValueBaseInfo, clang::CodeGen::TBAAAccessInfo, clang::ASTContext&): 
Assertion `Addr.getBasePointer()->getType()->isPointerTy()' failed.
```

Stack trace:
```
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++2c <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	<source>:12:9: Generating code for declaration 'f()::(anonymous class)::operator()'
 #0 0x0000000003928918 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3928918)
 #1 0x00000000039265fc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39265fc)
 #2 0x000000000386cba8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f2d0a042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f2d0a0969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f2d0a042476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f2d0a0287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f2d0a02871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f2d0a039e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000003c3e46c clang::CodeGen::LValue::MakeAddr(clang::CodeGen::Address, clang::QualType, clang::ASTContext&, clang::CodeGen::LValueBaseInfo, clang::CodeGen::TBAAAccessInfo) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c3e46c)
#10 0x000000000404970f clang::CodeGen::CodeGenFunction::EmitLValueForField(clang::CodeGen::LValue, clang::FieldDecl const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x404970f)
#11 0x000000000404afdd clang::CodeGen::CodeGenFunction::EmitLValueForLambdaField(clang::FieldDecl const*, llvm::Value*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x404afdd)
#12 0x0000000004057af5 clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(clang::DeclRefExpr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4057af5)
#13 0x00000000040549d2 clang::CodeGen::CodeGenFunction::EmitLValueHelper(clang::Expr const*, clang::CodeGen::KnownNonNull_t) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40549d2)
#14 0x0000000004054d11 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*, clang::CodeGen::KnownNonNull_t) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4054d11)
#15 0x00000000040a94ff clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#16 0x00000000040ae26c clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40ae26c)
#17 0x000000000403f14e clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x403f14e)
#18 0x0000000004060dc1 clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4060dc1)
#19 0x00000000040b0437 (anonymous namespace)::ScalarExprEmitter::VisitCastExpr(clang::CastExpr*) CGExprScalar.cpp:0:0
#20 0x00000000040a7a53 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#21 0x00000000040ae26c clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40ae26c)
#22 0x000000000403f14e clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x403f14e)
#23 0x0000000004060dc1 clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4060dc1)
#24 0x0000000003c4f155 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c4f155)
#25 0x0000000003c559ec clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c559ec)
#26 0x0000000003cb79b1 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cb79b1)
#27 0x0000000003ccb2ca clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ccb2ca)
#28 0x0000000003d2a8d2 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d2a8d2)
#29 0x0000000003d25195 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d25195)
#30 0x0000000003d3123d clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d3123d)
#31 0x0000000003d33ae3 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d33ae3)
#32 0x00000000041d538e (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#33 0x00000000041d3ea5 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41d3ea5)
#34 0x00000000061d59bc clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x61d59bc)
#35 0x00000000041d3768 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41d3768)
#36 0x0000000004453779 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4453779)
#37 0x00000000043dd09e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43dd09e)
#38 0x00000000045364ee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45364ee)
#39 0x0000000000c3e6ec cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc3e6ec)
#40 0x0000000000c3797a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#41 0x00000000042166e9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#42 0x000000000386d054 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x386d054)
#43 0x0000000004216cdf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#44 0x00000000041dd075 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41dd075)
#45 0x00000000041ddadd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41ddadd)
#46 0x00000000041e5845 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41e5845)
#47 0x0000000000c3bb85 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc3bb85)
#48 0x0000000000b1ed54 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb1ed54)
#49 0x00007f2d0a029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#50 0x00007f2d0a029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#51 0x0000000000c3746e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc3746e)
```

### LINKED ISSUE #89541: Crash with reference captures in inherited lambda with explicit parameters
The following valid code crashes

```cpp
int one = 1;
auto factory(int& x = one) {
    return [&](this auto self) {
      x;
    };
};

using Base = decltype(factory());
struct Derived : Base {
  Derived() : Base(factory()) {}
};

int main() {
  Derived d;
  d();
}
```

https://godbolt.org/z/PGW7s531a

```
clang++: /root/llvm-project/clang/lib/CodeGen/CGValue.h:277: void clang::CodeGen::LValue::initializeSimpleLValue(clang::CodeGen::Address, clang::QualType, clang::CodeGen::LValueBaseInfo, clang::CodeGen::TBAAAccessInfo, clang::ASTContext&): Assertion `Addr.getBasePointer()->getType()->isPointerTy()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	<source>:3:12: Generating code for declaration 'factory(int &)::(anonymous class)::operator()'
 #0 0x0000000003945d28 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3945d28)
 #1 0x0000000003943a0c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3943a0c)
 #2 0x0000000003889f78 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f6c4c242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f6c4c2969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f6c4c242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f6c4c2287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f6c4c22871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f6c4c239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000003c5e24c clang::CodeGen::LValue::MakeAddr(clang::CodeGen::Address, clang::QualType, clang::ASTContext&, clang::CodeGen::LValueBaseInfo, clang::CodeGen::TBAAAccessInfo) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c5e24c)
#10 0x000000000406b34f clang::CodeGen::CodeGenFunction::EmitLValueForField(clang::CodeGen::LValue, clang::FieldDecl const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x406b34f)
#11 0x000000000406cc1d clang::CodeGen::CodeGenFunction::EmitLValueForLambdaField(clang::FieldDecl const*, llvm::Value*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x406cc1d)
#12 0x0000000004079515 clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(clang::DeclRefExpr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4079515)
#13 0x0000000004076402 clang::CodeGen::CodeGenFunction::EmitLValueHelper(clang::Expr const*, clang::CodeGen::KnownNonNull_t) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4076402)
#14 0x0000000004082845 clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4082845)
#15 0x0000000003c6f195 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c6f195)
#16 0x0000000003c75a5c clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c75a5c)
#17 0x0000000003cd8405 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cd8405)
#18 0x0000000003cebddc clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cebddc)
#19 0x0000000003d4b442 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d4b442)
#20 0x0000000003d45d05 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d45d05)
#21 0x0000000003d51dad clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d51dad)
#22 0x0000000003d54653 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d
```

### PR DESCRIPTION
**Pull request by Sirraide**
Consider this code:
```c++
template <typename... Ts>
struct Overloaded : Ts... { using Ts::operator()...; };

template <typename... Ts>
Overloaded(Ts...) -> Overloaded<Ts...>;

void f() {
  int x;
  Overloaded o {
    [&](this auto& self) {
      return &x;
    }
  };
  o();
}
```

To access `x` in the lambda, we need to perform derived-to-base conversion on `self` (since the type of `self` is not the lambda type, but rather `Overloaded<(lambda type)>`). We were previously missing this step, causing us to attempt to load the entire lambda (as the base class, it would end up being the ‘field’ with index `0` here), which would then assert later on in codegen.

This fixes #87210 and fixes #89541.

### CODE REVIEW

File: clang/lib/CodeGen/CGExpr.cpp [hunk 1]
```diff
@@ -4684,6 +4684,29 @@ LValue CodeGenFunction::EmitLValueForLambdaField(const FieldDecl *Field,
...
+
+    // Make sure we have an lvalue to the lambda itself and not a derived class.
+    auto *ThisTy = D->getType().getNonReferenceType()->getAsCXXRecordDecl();
+    auto *LambdaTy = cast<CXXRecordDecl>(Field->getParent());
+    if (ThisTy != LambdaTy) {
+      CXXBasePaths Paths(/*FindAmbiguities=*/false, /*RecordPaths=*/true,
+                         /*DetectVirtual=*/false);
+
+      [[maybe_unused]] bool Derived = ThisTy->isDerivedFrom(LambdaTy, Paths);
+      assert(Derived && "Type not derived from lambda type?");
```
Comment (rjmccall) [inline clang/lib/CodeGen/CGExpr.cpp:4696]: Is there a reason there has to be a unique base subobject of the lambda type?

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: That’s something I’m not entirely sure about, but I couldn’t come up with a way to actually end up with more than one path from a derived class to the lambda’s type such that both would still be accessible.

Comment (rjmccall) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: We can manually resolve between the `operator()`s at the call site with a qualified member name, and the `operator()` should still get called with the original `Overloaded` without any hint about which subobject it was called on.

We could also have `Overloaded` just pick one of its bases to `using` the `operator()` from, but then I suppose someone might argue that the operator ought to pick up on that to decide the base path.  (That would be absurd, IMO.)

Example of the first: https://godbolt.org/z/rqvKGfevY

I think you need to open a DR with the committee.  It just needs to be ill-formed for a lambda call operator with an explicit `this` parameter to be instantiated such that the `this` parameter has a type with multiple base subobjects of the lambda type.  I can't imagine any other resolution short of something absurd like adding an implicit offset parameter, which would then be breaking in other ways.

Please go ahead and diagnose that condition in Sema.

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: > We can manually resolve between the `operator()`s at the call site with a qualified member name

Ah, that’s what I was missing.

> I think you need to open a DR with the committee.

That sounds reasonable, but I candidly have no idea how to do that.

> Please go ahead and diagnose that condition in Sema.

Will do.

Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: https://isocpp.org/std/submit-issue for defect reports

Also, maybe we should record the correct path in the AST somewhere?

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: > Also, maybe we should record the correct path in the AST somewhere?

That would probably be less of a hack than doing this here, but the main problem I see is that all we have here is a DRE; it just seems a bit strange to store cast paths in one—at least to me.

Comment (cor3ntin) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: Richard got you beat by a few days https://cplusplus.github.io/CWG/issues/2881.html

Comment (rjmccall) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: If we were going to put it in the AST, the right place would be on the call operator FD rather than in every DRE for a capture.  We'd presumably store it with a side-table in the ASTContext, which we'd only populate for lambdas with a derived object parameter.  It's probably not an actual problem to repeatedly recompute it as long as we have that restriction, though.

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: > We'd presumably store it with a side-table in the ASTContext, which we'd only populate for lambdas with a derived object parameter.

I was just thinking about storing it in the call operator but I wasn’t sure where, but this makes sense.

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: On that note, as for actually emitting the cast, is it worth it doing that once when we start emitting the lambda and then just reusing the computed lvalue instead of emitting the cast every time we need to access a capture? Or do we just let the optimiser clean that up? Asking because I’m not too familiar w/ how situations like these are typically handled in codegen.

Comment (rjmccall) [reply clang/lib/CodeGen/CGExpr.cpp:4696]: We could do either.  Doing it once in the prologue makes some sense to me; in the (very unlikely) case that it's not just a static offset, that would probably lead to better code.

**Comment by Sirraide** [comment]
Ok, I’ve added a check for CWG 2881 to sema, but there’s at least 2 things I still want to take a look at:
- [ ] Consider emitting the upcast once in the function prologue instead of every time a variable is accessed.
- [ ] Check for invalid explicit object parameters when the lambda is instantiated rather than when it is called.

**Comment by Sirraide** [comment]
I’m also not sure if the `dr28xx.cpp` file is meant for open issues, but I’ve put the tests for this there for now.

**Comment by Endilll** [comment]
@Sirraide See example of https://github.com/llvm/llvm-project/blob/662ef8604268b207910225ecca90daf30a46720b/clang/test/CXX/drs/dr25xx.cpp#L148
In this case, the date should be 2024-04-19.

**Comment by Sirraide** [comment]
> @Sirraide See example of
> 
> https://github.com/llvm/llvm-project/blob/662ef8604268b207910225ecca90daf30a46720b/clang/test/CXX/drs/dr25xx.cpp#L148
> 
> 
> In this case, the date should be 2024-04-19.

Ah, thanks.

**Comment by Sirraide** [comment]
@cor3ntin There already was a FIXME to consider moving this check to where the call operator is first instantiated; should I look into that as well or is it fine to leave this here? Asking because I’m assuming there’s a reason why it wasn’t done that way.

**Comment by cor3ntin** [comment]
> @cor3ntin There already was a FIXME to consider moving this check to where the call operator is first instantiated; should I look into that as well or is it fine to leave this here? Asking because I’m assuming there’s a reason why it wasn’t done that way.

If you can do it easily, you should!
I don't remember the details sadly, It's been over a year!

**Comment by Sirraide** [comment]
Ok, I’ve looked into this a bit more, and it seems that checking for this at instantiation time ends up being more complicated and produces more diagnostics than just checking it at the call site; I’ve added a comment about that.

Other than that, is there anything else that we should look into here?

**Comment by cor3ntin** [comment]
You should run make_cxx_drs, otherwise I think this looks in good shape.

I think we should diag earlier (because if the lambda is not use we should still signal it's broken) but doing that as a follow up PR seems reasonable.

Less redundant diags is better but if we can't avoid it, i think it's a reasonable compromise

**Comment by Sirraide** [comment]
> You should run make_cxx_drs, otherwise I think this looks in good shape.

Will do.
> I think we should diag earlier (because if the lambda is not use we should still signal it's broken) but doing that as a follow up PR seems reasonable.
> 
> Less redundant diags is better but if we can't avoid it, i think it's a reasonable compromise

Alright; I’ll leave it as-is for this pr then.

**Review by cor3ntin — APPROVED** [review]
I think this makes sense. Thanks!

@Endilll just updated the list of DRs to avoid unrelated changes, so by fixing the conflict, only changes to cwg2881 should be in your PR

**Comment by Sirraide** [comment]
> Endilll just updated the list of DRs to avoid unrelated changes, so by fixing the conflict, only changes to cwg2881 should be in your PR

Should I just run `make_cxx_dr_status` again then and commit the result?

**Comment by Sirraide** [comment]
> Should I just run make_cxx_dr_status again then and commit the result?

I ended up figuring it out after talking to @Endilll about it. 

Also, the only CI failure earlier was something unrelated (CoverageMapping/mcdc-system-headers.cpp).

File: clang/lib/CodeGen/CGExpr.cpp [hunk 2]
```diff
@@ -4693,6 +4694,17 @@ LValue CodeGenFunction::EmitLValueForLambdaField(const FieldDecl *Field,
...
                                 D->getType().getNonReferenceType());
+
+    // Make sure we have an lvalue to the lambda itself and not a derived class.
+    auto *ThisTy = D->getType().getNonReferenceType()->getAsCXXRecordDecl();
+    auto *LambdaTy = cast<CXXRecordDecl>(Field->getParent());
+    if (ThisTy != LambdaTy) {
+      const CXXCastPath &BasePathArray = getContext().LambdaCastPaths.at(MD);
+      Address Base = GetAddressOfBaseClass(
+          LambdaLV.getAddress(*this), ThisTy, BasePathArray.begin(),
+          BasePathArray.end(), /*NullCheckValue=*/false, SourceLocation());
```
Comment (nickdesaulniers) [inline clang/lib/CodeGen/CGExpr.cpp:4705]: error: too many arguments to function call, expected 0, have 1
          LambdaLV.getAddress(*this), ThisTy, BasePathArray.begin(),
          ~~~~~~~~~~~~~~~~~~~ ^~~~~

https://lab.llvm.org/buildbot/#/builders/225/builds/36615/steps/6/logs/stdio

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4705]: Already on it

Comment (Sirraide) [reply clang/lib/CodeGen/CGExpr.cpp:4705]: Fixed

Comment (nickdesaulniers) [reply clang/lib/CodeGen/CGExpr.cpp:4705]: https://github.com/llvm/llvm-project/commit/da88e7fbd74cef33411bb5115f20e4b474d2d8b1

**Comment by Sirraide** [comment]
It seems that a parameter to `getAddress()` that wasn’t being used has been removed, which caused builds to break after I merged this. My bad; I’ve already pushed a fix for this: #93086. I didn’t wait for CI this time because it was passing before (except for an unrelated issue), and I figured it wouldn’t be a problem because that was 2 days ago (it usually isn’t a problem in my experience at least), but the timing here was a bit unfortunate this time...
