### PR TITLE
[clang] The ms-extension __noop should return zero in a constexpr context.

### LINKED ISSUE #106713: `__noop` should return 0
The new constexpr implementation is wrong.

https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/builtin-ms-noop.cpp shows that `__noop` should return `0` and not nothing.

### PR DESCRIPTION
**Pull request by c8ef**
Fixes #106713.

### CODE REVIEW

**Comment by MitalAshok** [comment]
Could you also add tests that calling it returns zero and doesn't evaluate its arguments:

```c++
static_assert([]{ return __noop(4); }() == 0);
extern int not_accessed;
void not_called();
static_assert([]{ return __noop(not_accessed *= 6); }() == 0);
static_assert([]{ return __noop(not_called()); }() == 0);
static_assert([]{ return __noop(throw ""); }() == 0);
static_assert([]{ return __noop(throw "", throw ""); }() == 0);
static_assert([]{ int a = 5; __noop(++a); return a; }() == 5);
```

This passes on MSVC (<https://godbolt.org/z/nvxr3GxT4>) but currently crashes Clang.

File: clang/lib/AST/ExprConstant.cpp [hunk 1]
```diff
@@ -12720,8 +12720,8 @@ bool IntExprEvaluator::VisitBuiltinCallExpr(const CallExpr *E,
   }
 
   case Builtin::BI__noop:
-  // __noop always evaluates successfully
-    return true;
+    // __noop always evaluates successfully
+    return ZeroInitialization(E);
```
Comment (tbaederr) [inline clang/lib/AST/ExprConstant.cpp:12724]:
```suggestion
    // __noop always evaluates successfully and returns 0.
    return Success(0, E);
```

**Review by cor3ntin — APPROVED** [review]
LGTM
