### PR TITLE
[clangd] Track IWYU pragmas for non-preamble includes

### LINKED ISSUE #1571: include-cleaner: `ParsedAST::getPragmaIncludes()` only contains information for preamble.
The `PragmaInclude` structure in clangd only contains the information for the preamble, this means the non-preamble IWYU pragmas are not respected in clangd, see the following example:

```
int abc;
// we still get an unused-include diagnostic.
#include "unused.h" // IWYU pragma: keep
```

One solution is to build a `PragmaInclude` when building the main AST and merge it with the one for preamble.

### LINKED ISSUE #1843: Regression with "IWYU pragma: keep" in headers
We have a convention to split implementations of inline functions into their own header files; this file is then included at the end of the header that has the declarations, so that clients don't have to know about this. This include at the end of the main header is marked with `// IWYU pragma: keep` to stop clangd from flagging it as unused.

This used to work with clangd 16, but has stopped working with clangd 17. It now reports the include of the impl header as unused even though it is marked with `// IWYU pragma: keep`.

Reproduction:
```
foo.hpp:
#pragma once

template <typename T> void someFunction();

#include "foo-impl.hpp" // IWYU pragma: keep

---

foo-impl.hpp:
#pragma once

template <typename T> void someFunction() {
  // do some work
}

---
main.cpp:
#include "foo.hpp"

int main(void) {
  someFunction<int>();
  return 0;
}
```

image

**Log**

[clangd-log.txt](https://github.com/clangd/clangd/files/13501486/clangd-log.txt)

**System information**

Output of `clangd --version`:
```
clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
Features: mac+grpc+xpc
Platform: arm64-apple-darwin23.1.0; target=x86_64-apple-darwin23.1.0
```
Editor/LSP plugin: VS Code 1.85.0-insider (Universal), Commit: 2e721b6ec7

Operating system: MacOS 14.1.1

### PR DESCRIPTION
**Pull request by kadircet**
This makes PragmaIncldues copyable, and copies it from preamble when building a
new AST.

Fixes https://github.com/clangd/clangd/issues/1843
Fixes https://github.com/clangd/clangd/issues/1571

### CODE REVIEW

File: clang-tools-extra/include-cleaner/include/clang-include-cleaner/Record.h [hunk 1]
```diff
@@ -113,7 +113,7 @@ class PragmaIncludes {
   llvm::DenseSet<llvm::sys::fs::UniqueID> ShouldKeep;
 
   /// Owns the strings.
-  llvm::BumpPtrAllocator Arena;
+  std::shared_ptr<llvm::BumpPtrAllocator> Arena;
```
Comment (sam-mccall) [inline clang-tools-extra/include-cleaner/include/clang-include-cleaner/Record.h:116]: This doesn't look threadsafe. Two PIs associated with parallel ParsedAST builds will write into the same arena.

You could do some trick with shared_ptr<void> to keep all needed arenas alive, and a raw pointer to the current, I guess?

Comment (kadircet) [reply clang-tools-extra/include-cleaner/include/clang-include-cleaner/Record.h]: you're right in theory, but in practice we actually never build ASTs concurrently from a preamble in clangd (we've a single ASTWorker peer per preamble). Moreover mutating the same arena bit is actually never the case, but quite subtle. We build the arena specifically in PPCallbacks and just move it to PI at the end. Hence in practice we have 2 separate PIs, one inside preamble, whose arena is never mutated. Another in ParsedAST, which can refer to strings both inside its own Arena, but also to the arena "kept" alive by the preamble. so I think this was safe for clangd, but too subtle to keep working in the long run I guess.

storing a vector of const arenas in PI instead, and changing the `record` to just push each arena to the end, rather than overwriting the existing Arena (while extending all other structures).

**Review by hokein — APPROVED** [review]
thanks, looks good.
