### PR TITLE
[clang-tidy] 'modernize-use-starts-ends-with': fixed false positives on `find` and `rfind`

### LINKED ISSUE #129498: Clang tidy modernize-use-starts-ends-with suggest incorrect fixit if additional count argument is passed to rfind/find
Code sample:

```
 const std::string testString = "testString";

 static constexpr std::array<char, 2> testCharArray = {static_cast<char>(0xBD),
                                                          static_cast<char>(0x92)}; // Array is not null terminated

 bool found = testString.rfind(testCharArray.data(), 0, testCharArray.size()) == 0;
```

Clang tidy suggests to change string with rfind to 
```
bool found = testString.starts_with(testCharArray.data()); // This is UB since testCharArray is not null terminated
```
But it is not valid since count argument of rfind is ignored.

It looks like it should be either no fix at all in case that  count if passed to rfind/find, or fix should take into account count's value:
```
testString.starts_with({testCharArray.data(), testCharArray.size()});
```
This code will created string_view with correct size of array and code should work correctly.

### PR DESCRIPTION
**Pull request by vbvictor**
1. Fixed false positives where check would match 3-argument calls e.g. `s.rfind(v, 0, 3)` as if it had only 2 arguments.
2. Enhanced docs to show that check also matches `u.find(v, 0) == 0` case.

Closes https://github.com/llvm/llvm-project/issues/129498.

P.S. In the issue one of the proposed fix to the problem was to transform `s.find(v, 0, 3)` into `s.starts_with({v, 3})`. But for me creating a `string_view` "on the go" is confusing since we create another object, what do others think?
FYI @nicovank

I can implement creation of `string_view` but for now I ignore those cases.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-starts-ends-with.cpp [hunk 1]
```diff
@@ -261,6 +273,9 @@ void test(std::string s, std::string_view sv, sub_string ss, sub_sub_string sss,
 
   #define STRING s
   if (0 == STRING.find("ala")) { /* do something */}
+
+  s.find("aaa", 0, 3) == 0;
+  s.rfind("aaa", std::string::npos, 3) == 0;
```
Comment (nicovank) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-starts-ends-with.cpp:278]: These two are actually TPs, becoming FNs. I think the test should have FPs that turns into TNs instead, such as:
```cpp
s.find("aaa", 0, 2) == 0;
s.rfind("aaa", 0, 2) == 0;
```

**Review by nicovank — COMMENTED** [review]
Thanks!! I think something could also be done incorporating `lengthExprForStringNode`, with this patch some TPs will be ignored. `lengthExprForStringNode` will ignore `char*` unless `strlen` is used in which case the string has to be null-terminated anyway. What do you think? EDIT: or a char* literal, in which case it's also null terminated.

I'm also okay with landing this ignore now, those FPs are probably exceedingly rare.

Creating string views is more involved and I also think not needed for this change.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -137,6 +137,10 @@ Changes in existing checks
   <clang-tidy/checks/performance/move-const-arg>` check by fixing false negatives
   on ternary operators calling ``std::move``.
 
+- Improved :doc:`modernize-use-starts-ends-with
+  <clang-tidy/checks/modernize/use-starts-ends-with>` check by fixing false
+  positives on methods ``find`` and ``rfind`` called with three arguments.
+
```
[the remark this answers is not in the document]
Comment (vbvictor) [reply clang-tools-extra/docs/ReleaseNotes.rst:143]: Yes, it should. I'll fix that, forgot to place appropriately.

[the remark this answers is not in the document]
Comment (EugeneZelenko) [reply clang-tools-extra/docs/ReleaseNotes.rst:143]: Obviously, it's easier to read and find something particular in long list when it's sorted.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -128,6 +128,10 @@ Changes in existing checks
   <clang-tidy/checks/misc/redundant-expression>` check by providing additional
   examples and fixing some macro related false positives.
 
+- Improved :doc:`modernize-use-starts-ends-with
+  <clang-tidy/checks/modernize/use-starts-ends-with>` check by fixing false
+  positives on methods ``find`` and ``rfind`` called with three arguments.
+
 - Improved :doc:`performance/unnecessary-value-param
```
Comment (EugeneZelenko) [inline clang-tools-extra/docs/ReleaseNotes.rst:135]:
```suggestion
- Improved :doc:`performance-unnecessary-value-param
```

Please also fix this.

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-starts-ends-with.cpp (hunk 1 above)
Comment (vbvictor) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-starts-ends-with.cpp]: I added matching of cases where `strlen("aaa") == 3rd_arg`, that now only by design TN are not being matched.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -128,7 +128,12 @@ Changes in existing checks
   <clang-tidy/checks/misc/redundant-expression>` check by providing additional
   examples and fixing some macro related false positives.
 
-- Improved :doc:`performance/unnecessary-value-param
+- Improved :doc:`modernize-use-starts-ends-with
+  <clang-tidy/checks/modernize/use-starts-ends-with>` check by adding more
+  matched scenarios of ``find`` and ``rfind`` methods and fixing false
+  positives when those methods were called with 3 arguments.
+
+- Improved :doc:`performance-unnecessary-value-param
```
Comment (nicovank) [inline clang-tools-extra/docs/ReleaseNotes.rst:136]: While you're at it, place below `performance-move-const-arg` for ordering.

**Review by nicovank — APPROVED** [review]
LGTM, thanks!!

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (vbvictor) [reply clang-tools-extra/docs/ReleaseNotes.rst:140]: Done

**Comment by vbvictor** [comment]
Reverted style changes in `ReleaseNotes.rst`, created new PR for cleanup: https://github.com/llvm/llvm-project/pull/130626.

**Review by nicovank — APPROVED** [review]
I saw you have a pending commit access request -- I'll just let you merge this when you are able to.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -136,6 +136,11 @@ Changes in existing checks
...
   warnings logic for ``nullptr`` in ``std::find``.
 
+- Improved :doc:`modernize-use-starts-ends-with
+  <clang-tidy/checks/modernize/use-starts-ends-with>` check by adding more
+  matched scenarios of ``find`` and ``rfind`` methods and fixing false
+  positives when those methods were called with 3 arguments.
+
 - Improved :doc:`misc-use-internal-linkage
   <clang-tidy/checks/misc/use-internal-linkage>` check by fix false positives
   for function or variable in header file which contains macro expansion.
```
Comment (nicovank) [inline clang-tools-extra/docs/ReleaseNotes.rst:146]: I think this just got lost in the split.

```suggestion
- Improved :doc:`misc-use-internal-linkage
  <clang-tidy/checks/misc/use-internal-linkage>` check by fix false positives
  for function or variable in header file which contains macro expansion.

- Improved :doc:`modernize-use-starts-ends-with
  <clang-tidy/checks/modernize/use-starts-ends-with>` check by adding more
  matched scenarios of ``find`` and ``rfind`` methods and fixing false
  positives when those methods were called with 3 arguments.
```

**Comment by nicovank** [comment]
Actually, with the other one merged I feel like there'll be a conflict with GitHub trying to auto-merge. Can you rebase on main? Then I'll click the button.

**Comment by vbvictor** [comment]
Rebase and PR-checks are done, ready to merge

**Comment by nicovank** [comment]
Thanks!
