### PR TITLE
[X86] Fix shuffle comment decoding for vinsertps immediate operand

### LINKED ISSUE #117141: [X86] Incorrect shuffle comment decoding for `vinsertps`
### Reproducer
```asm
; input.s
.intel_syntax
vinsertps xmm2,xmm2,dword ptr [r14+rdi*8+0x4C],0x0B0
```
### Current behaviour
``` bash
> llvm-mc -triple x86_64-unknown-unknown input.s

.text
vinsertps       $176, 76(%r14,%rdi,8), %xmm2, %xmm2 # xmm2 = xmm2[0,1,2],mem[2]
```

Note that shuffle comment says `mem[2]`. The part describing vinsertps operation in the Intel SDM says the following:
```
IF (SRC = REG) THEN COUNT_S := imm8[7:6] ELSE COUNT_S := 0
```
In input.s the source for the vinsertps is not a register therefore the source index in the comment should be 0 (`mem[0]`).

### PR DESCRIPTION
**Pull request by omern1**
The relevant bit from the Intel SDM for vinsertps semantics:
```
IF (SRC = REG) THEN COUNT_S := imm8[7:6] ELSE COUNT_S := 0
```

This is now taken into account.

### CODE REVIEW

File: llvm/lib/Target/X86/MCTargetDesc/X86InstComments.cpp [hunk 1]
```diff
@@ -1122,15 +1122,21 @@ bool llvm::EmitAnyX86InstComments(const MCInst *MI, raw_ostream &OS,
   case X86::VINSERTPSrri:
   case X86::VINSERTPSZrri:
     Src2Name = getRegName(MI->getOperand(2).getReg());
-    [[fallthrough]];
+    DestName = getRegName(MI->getOperand(0).getReg());
+    Src1Name = getRegName(MI->getOperand(1).getReg());
+    if (MI->getOperand(NumOperands - 1).isImm())
+      DecodeINSERTPSMask(MI->getOperand(NumOperands - 1).getImm(),
+                         ShuffleMask, false);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86InstComments.cpp:1129]: `/*SrcIsMem=*/false`

File: llvm/lib/Target/X86/MCTargetDesc/X86InstComments.cpp [hunk 2]
```diff
@@ -1122,15 +1122,21 @@ bool llvm::EmitAnyX86InstComments(const MCInst *MI, raw_ostream &OS,
...
+
   case X86::INSERTPSrmi:
   case X86::VINSERTPSrmi:
   case X86::VINSERTPSZrmi:
     DestName = getRegName(MI->getOperand(0).getReg());
     Src1Name = getRegName(MI->getOperand(1).getReg());
     if (MI->getOperand(NumOperands - 1).isImm())
       DecodeINSERTPSMask(MI->getOperand(NumOperands - 1).getImm(),
-                         ShuffleMask);
+                         ShuffleMask, true);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86InstComments.cpp:1139]: `/*SrcIsMem=*/true`

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 3]
```diff
@@ -5362,7 +5362,7 @@ static bool getTargetShuffleMask(SDValue N, bool AllowSentinelZero,
     assert(N.getOperand(0).getValueType() == VT && "Unexpected value type");
     assert(N.getOperand(1).getValueType() == VT && "Unexpected value type");
     ImmN = N.getConstantOperandVal(N.getNumOperands() - 1);
-    DecodeINSERTPSMask(ImmN, Mask);
+    DecodeINSERTPSMask(ImmN, Mask, false);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:5365]: `/*SrcIsMem=*/false`

File: llvm/test/MC/X86/vinsertps_decode.s [hunk 4]
```diff
@@ -0,0 +1,7 @@
+# RUN: llvm-mc -triple x86_64-unknown-unknown %s | FileCheck %s
```
Comment (RKSimon) [inline llvm/test/MC/X86/vinsertps_decode.s:1]: Add --no_x86_scrub_mem_shuffle arg to check full line

File: llvm/lib/Target/X86/MCTargetDesc/X86ShuffleDecode.cpp [hunk 5]
```diff
@@ -23,7 +23,7 @@
 
 namespace llvm {
 
-void DecodeINSERTPSMask(unsigned Imm, SmallVectorImpl<int> &ShuffleMask) {
+void DecodeINSERTPSMask(unsigned Imm, SmallVectorImpl<int> &ShuffleMask, bool SrcIsMem) {
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86ShuffleDecode.cpp:26]: clang-format

File: llvm/lib/Target/X86/MCTargetDesc/X86ShuffleDecode.h [hunk 6]
```diff
@@ -28,7 +28,7 @@ template <typename T> class SmallVectorImpl;
 enum { SM_SentinelUndef = -1, SM_SentinelZero = -2 };
 
 /// Decode a 128-bit INSERTPS instruction as a v4f32 shuffle mask.
-void DecodeINSERTPSMask(unsigned Imm, SmallVectorImpl<int> &ShuffleMask);
+void DecodeINSERTPSMask(unsigned Imm, SmallVectorImpl<int> &ShuffleMask, bool SrcIsMem);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86ShuffleDecode.h:31]: clang-format

**Review by RKSimon — COMMENTED** [review]
Is there a reported issue for this?

File: llvm/test/MC/X86/vinsertps_decode.s (hunk 4 above)
Comment (omern1) [reply llvm/test/MC/X86/vinsertps_decode.s:1]: I've manually updated the line for now. I did not generate the test with `update_llc_test_checks.py` because I don't think it works with llvm-mc?

**Comment by omern1** [comment]
> Is there a reported issue for this?

No there isn't, I'll create one now.

File: llvm/test/MC/X86/vinsertps_decode.s [hunk 7]
```diff
@@ -0,0 +1,7 @@
...
+
+.intel_syntax
+
+# CHECK: vinsertps $176, 76(%r14,%rdi,8), %xmm2, %xmm2 # xmm2 = xmm2[0,1,2],mem[0]
+
+vinsertps xmm2,xmm2,dword ptr [r14+rdi*8+0x4C],0x0B0
```
Comment (RKSimon) [inline llvm/test/MC/X86/vinsertps_decode.s:7]: test `insertps` and `{evex} vinsertps` variants as well?

Comment (adibiagio) [reply llvm/test/MC/X86/vinsertps_decode.s:7]: minor: you can simplify the address computation. For the purpose of this test, you don't need index/scale/offset. It is all about testing that you still get mem[0] even if some of the top bits of the immediate are set.

**Review by RKSimon — APPROVED** [review]
LGTM
