### PR TITLE
[X86] Use 32-bit jump table entries on Windows

### LINKED ISSUE #95622: [Windows][Intel x64] Jump table entries seems not valid while targeting MSVC 2022
In your project we use LLVM-powered part which compiled with embedded LLVM to an .obj file then gets linked into our main binary. Other parts are in C or C++ and compiled with clang-cl.exe supplied by MSVC 2022 as a ClangCl toolset (at the moment the latest is 17.0.3).
After updating our embedded LLVM from version 16 to 18.1.7 we can see our application crashing. 

Investigations indicate that the crash happened after calculating a jump target from jump table - the resulting jump target value is not correct.
In version 16 a jump table entry was 32-bit, and the result jump target has been calculated by sign-extending jump table entry value, like this:
```
	movabs	r10, offset .LJTI536_0
	movsxd	r9, dword ptr [r10 + 4*r9]
	add	r9, r10
	jmp	r9
```
In version 18 jump table entries are now 64-bit, so the accessing code now doesn't sign-extend entry value
```
	movabs	r10, offset .LJTI536_0
	add	r10, qword ptr [r10 + 8*r9]
	jmp	r10
```

I'm not sure why, but I can see that jump table entry values are still 32-bit. Thus, if values are negative and they don't get sign-extended, then the result jump target becomes invalid. See the screenshot attached.

Is this a bug in LLVM 18? Or some incompatibility issue, for example with MS linker or clang-cl version 17.0.3 which we use for C parts?
Obviously, disabling jump tables fixes the issue for us, but we want them to be enabled.
LMK if you need more info or any other help for this issue.

jump tables

### PR DESCRIPTION
**Pull request by aeubanks**
Windows doesn't support relative 64-bit relocations.

Fixes #95622

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 1]
```diff
@@ -417,7 +417,8 @@ unsigned X86TargetLowering::getJumpTableEncoding() const {
   if (isPositionIndependent() && Subtarget.isPICStyleGOT())
     return MachineJumpTableInfo::EK_Custom32;
   if (isPositionIndependent() &&
-      getTargetMachine().getCodeModel() == CodeModel::Large)
+      getTargetMachine().getCodeModel() == CodeModel::Large &&
+      !Subtarget.isOSWindows())
```
Comment (efriedma-quic) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp:421]: Maybe isTargetCOFF(), to better match what we actually care about here.

**Review by efriedma-quic — APPROVED** [review]
LGTM with one minor comment.
