### PR TITLE
[clang][AST] Invalidate DecompositionDecl if it has invalid initializer.

### LINKED ISSUE #67495: Clang: Crash on capturing invalid structured binding declaration in lambda expression (regression from 44f2baa3804a62)
The following code ICE's (crash on invalid) on trunk, and going back to at least clang 16.0.6

```c++
struct Point {
   int x;
   int y;
};

Point get_point() { return { 1, 2 }; }

int main() {
    auto& [x, y] = get_point();

    bool b = [x, y] {
        return true;
    }();

    return b;
}
```

Godbolt link: https://godbolt.org/z/bvEbbc6hj

The compiler correctly diagnoses that we need to use `auto&&` for these variables if we want to use them in a structured binding declaration of an rvalue.... and then crashes.

 I ran into this refactoring some code that manually extracted these members (that were already captured in a lambda expression) to use a structured binding. This made clangd crash outright instead of letting me know that I had an error.

### PR DESCRIPTION
**Pull request by hokein**
Fix #67495, #72198

We build ill-formed AST nodes for invalid structured binding. For case `int [_, b] = {0, 0};`, the `DecompositionDecl` is valid, and its children `BindingDecl`s are valid but with a NULL type, this breaks clang invariants in many places, and using these `BindingDecl`s can lead to crashes. This patch fixes them by marking the DecompositionDecl and its children invalid.

CC @ADKaster, @ecnelises

### CODE REVIEW

**Comment by hnrklssn** [comment]
What differentiates the DecompositionDecl such that we need to mark the decl invalid when there's an error in the RHS, while for other decls we don't? It seems inconsistent.

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -13540,6 +13540,15 @@ void Sema::AddInitializerToDecl(Decl *RealDecl, Expr *Init, bool DirectInit) {
...
         VDecl->setInit(RecoveryExpr.get());
+      // In general, for error recovery purposes, the initalizer doesn't play
+      // part in the valid bit of the declaration. There are a few exceptions:
+      //  1) if the var decl has a deduced auto type, and the type cannot be
+      //     deduced by an invalid initializer;
+      //  2) if the var decl is decompsition decl with a concrete type (e.g.
+      //    `int [a, b] = 1;`), and the initializer is invalid;
+      // Case 1) is already handled earlier in this function.
+      if (llvm::isa<DecompositionDecl>(VDecl)) // Case 2)
+        VDecl->setInvalidDecl();
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaDecl.cpp:13551]: Maybe we should move the `1)` part of the comment line 13496, or just remove it entirely.

File: clang/test/AST/ast-dump-invalid-initialized.cpp [hunk 2]
```diff
@@ -24,4 +24,17 @@ void test() {
   auto b4 = A(1);
   // CHECK: `-VarDecl {{.*}} invalid b5 'auto'
   auto b5 = A{1};
-}
\ No newline at end of file
+}
+
+void pr72198() {
```
Comment (cor3ntin) [inline clang/test/AST/ast-dump-invalid-initialized.cpp:29]:
```suggestion
void GH72198() {
```

File: clang/test/AST/ast-dump-invalid-initialized.cpp [hunk 3]
```diff
@@ -24,4 +24,17 @@ void test() {
...
+  int [_, b] = {0, 0};
+  [b]{};
+}
+
+int get_point();
+void pr67495() {
+  // CHECK: DecompositionDecl {{.*}} invalid 'int &'
+  auto& [x, y] = get_point();
+  [x, y] {};
+}
```
Comment (cor3ntin) [inline clang/test/AST/ast-dump-invalid-initialized.cpp:40]:
```suggestion
namespace GH67495 {
int get_point();
void f() {
  // CHECK: DecompositionDecl {{.*}} invalid 'int &'
  auto& [x, y] = get_point();
  [x, y] {};
}
}
```

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (shafik) [reply clang/lib/Sema/SemaDecl.cpp:13551]: We should have the comment in both places. This is very helpful to understanding the code.

I agree that having the comment far away from the code that it is commenting on is less useful. The code could easily be moved in a refactor or in other ways and become completely disconnected.

Comment (hokein) [reply clang/lib/Sema/SemaDecl.cpp:13551]: I think this comment is helpful (especially the context is not obvious here). I'd like to keep it.

The code handling the case `1)` is https://github.com/llvm/llvm-project/blob/1c05fe350064aa3a1784bb09829a07d501842d97/clang/lib/Sema/SemaDecl.cpp#L13363C3-L13384, and it is easier to understand the purpose by reading the code. I'd avoid having two similar comments in the codebase.

**Comment by hnrklssn** [comment]
> > What differentiates the DecompositionDecl such that we need to mark the decl invalid when there's an error in the RHS, while for other decls we don't? It seems inconsistent.
> 
> 
> 
> DecompositionDecl (aka structure binding) is special here, a legal DecompositionDecl must be declared with a deduced `auto` type, so the its initializer should play part of the decl's invalid bit. For the error case where a DecompositionDecl with a non-deduced type, clang still builds the Decl AST node (with invalid bit) for better recovery. There are some oversight cases. This patch is fixing those.

Ah that makes sense then. I didn't realise it had to be `auto`.

**Comment by hokein** [comment]
Friendly ping.

**Review by shafik — COMMENTED** [review]
We need a release note and please add a more detailed summary. A description of the problem being solved and the solution to the fix provides.

**Comment by hokein** [comment]
> We need a release note and please add a more detailed summary. A description of the problem being solved and the solution to the fix provides.

Done.

**Comment by hokein** [comment]
Friendly ping.

File: clang/lib/Sema/SemaDecl.cpp [hunk 4]
```diff
@@ -13570,6 +13570,15 @@ void Sema::AddInitializerToDecl(Decl *RealDecl, Expr *Init, bool DirectInit) {
...
       if (RecoveryExpr.get())
         VDecl->setInit(RecoveryExpr.get());
+      // In general, for error recovery purposes, the initalizer doesn't play
+      // part in the valid bit of the declaration. There are a few exceptions:
+      //  1) if the var decl has a deduced auto type, and the type cannot be
+      //     deduced by an invalid initializer;
+      //  2) if the var decl is decompsition decl with a non-deduced type, and
+      //     the initialization fails (e.g. `int [a] = {1, 2};`);
+      // Case 1) was already handled elsewhere.
+      if (llvm::isa<DecompositionDecl>(VDecl)) // Case 2)
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDecl.cpp:13580]:
```suggestion
      if (isa<DecompositionDecl>(VDecl)) // Case 2)
```

**Review by AaronBallman — APPROVED** [review]
LGTM with a tiny nit.

File: clang/lib/Sema/SemaDecl.cpp (hunk 4 above)
Comment (hokein) [reply clang/lib/Sema/SemaDecl.cpp]: Done
