### PR TITLE
[Clang][Sema] fix a bug on template partial specialization

### LINKED ISSUE #68885: NTTP references in requires clauses
Clang rejects this code

```cpp
#include <concepts> 
template <decltype(auto) a>
struct S {
    static constexpr int i = 42;
};

template <decltype(auto) a>
requires true
struct S<a> {
    static constexpr int i = 0;
};

static constexpr int a = 0;

void test() {
    static_assert(S<a>::i == 0);  // Ok
    static_assert(S<(a)>::i == 0); // Fails
}

```

https://godbolt.org/z/hsb4c5WE3 

Clang picks the primary template when a NTTP is a reference type, even if there is a more constrained specialization.
Other compiler accept this code.

### PR DESCRIPTION
**Pull request by jcsxky**
attempt to fix https://github.com/llvm/llvm-project/issues/68885#issuecomment-1764201896
Deduction of NTTP whose type is `decltype(auto)` would create an implicit cast expression to dependent type and makes the type of primary template definition (`InjectedClassNameSpecialization`) and its partial specialization different. Prevent emitting cast expression to make clang knows their types are identical by removing `CTAK == CTAK_Deduced` when the type is `decltype(auto)`.

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -7706,7 +7706,7 @@ ExprResult Sema::CheckTemplateArgument(NonTypeTemplateParmDecl *Param,
     // FIXME: The language rules don't say what happens in this case.
     // FIXME: We get an opaque dependent type out of decltype(auto) if the
     // expression is merely instantiation-dependent; is this enough?
-    if (CTAK == CTAK_Deduced && Arg->isTypeDependent()) {
+    if (Arg->isTypeDependent()) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:7709]: I think this makes reasonable sense, I note that this covers the  CTAK==CTAK_Specified case, but I would like a test where it is an array-bound so that we can ensure we're getting that right as well.

Comment (jcsxky) [reply clang/lib/Sema/SemaTemplate.cpp:7709]: After looking into the code a bit more, I think this won't happen since the type of `Arg` can't be dependent if the condition `CTAK == CTAK_DeducedFromArrayBound` holds. Because it has been deduced as a certain expression at the moment.

**Review by erichkeane — APPROVED** [review]
