### PR TITLE
[clang-format] Improve annotating star and amp

### LINKED ISSUE #193255: [clang-format] Reference qualifier & after template instantiation in generic lambda parameter list is formatted as binary operator
`clang-format` produces incorrect spacing around `&` when it appears after a
template instantiation inside a generic lambda parameter list.

**Repro (`repro.cpp`):**
```cpp
template <auto...> struct S {};
template <typename T> concept C = requires(T& t) { []<auto... A>(S<A...>& c) {}(t); };
```

**Config (`.clang-format`):**
```yaml
BasedOnStyle: LLVM
PointerAlignment: Left
```

**Command:**
```
clang-format repro.cpp
```

**Expected:**
```cpp
template <typename T>
concept C = requires(T& t) { []<auto... A>(S<A...>& c) {}(t); };
```

**Actual:**
```cpp
template <typename T>
concept C = requires(T& t) { []<auto... A>(S<A...> & c) {}(t); };
```

It looks like the `&` token is being classified as `TT_BinaryOperator` instead of `TT_PointerOrReference`, so `PointerAlignment` / `ReferenceAlignment` have no effect. Removing either the requires-expression wrapper or the concept declaration makes the bug disappear and the & is annotated as `PointerOrReference` correctly.

Workaround: `// clang-format off` around the affected line.

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Use the context better.

Fixes #193255

### CODE REVIEW

**Comment by owenca** [comment]
Can we do the following instead?
```diff
--- a/clang/lib/Format/UnwrappedLineParser.cpp
+++ b/clang/lib/Format/UnwrappedLineParser.cpp
@@ -2741,6 +2741,7 @@ bool UnwrappedLineParser::parseParens(TokenType AmpAmpTokenType,
     case tok::kw_requires:
       parseRequiresExpression();
       break;
+    case tok::amp:
     case tok::ampamp:
       if (AmpAmpTokenType != TT_Unknown)
         FormatTok->setFinalizedType(AmpAmpTokenType);
```

**Comment by HazardyKnusperkeks** [comment]
> Can we do the following instead?
> 
> ```diff
> --- a/clang/lib/Format/UnwrappedLineParser.cpp
> +++ b/clang/lib/Format/UnwrappedLineParser.cpp
> @@ -2741,6 +2741,7 @@ bool UnwrappedLineParser::parseParens(TokenType AmpAmpTokenType,
>      case tok::kw_requires:
>        parseRequiresExpression();
>        break;
> +    case tok::amp:
>      case tok::ampamp:
>        if (AmpAmpTokenType != TT_Unknown)
>          FormatTok->setFinalizedType(AmpAmpTokenType);
> ```

We can, but we also need it for `tok::star` and I don't know which way is better.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -433,6 +433,11 @@ TEST_F(TokenAnnotatorTest, UnderstandsUsesOfStarAndAmp) {
   EXPECT_TOKEN(Tokens[7], tok::r_paren, TT_Unknown); // Not TT_CastRParen
   EXPECT_TOKEN(Tokens[10], tok::amp, TT_PointerOrReference);
   EXPECT_TOKEN(Tokens[11], tok::identifier, TT_StartOfName);
+
+  Tokens = annotate("template<typename T>\n"
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp]:
```suggestion
  Tokens = annotate("template <typename T>\n"
```

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -433,6 +433,11 @@ TEST_F(TokenAnnotatorTest, UnderstandsUsesOfStarAndAmp) {
...
+                    "concept C = requires(T t) { [](auto &c) {}(t); };");
+  ASSERT_EQ(Tokens.size(), 30u) << Tokens;
+  EXPECT_TOKEN(Tokens[18], tok::amp, TT_PointerOrReference);
 }
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:448]:
```suggestion
  EXPECT_TOKEN(Tokens[19], tok::identifier, TT_StartOfName);
}
```

**Comment by owenca** [comment]
> We can, but we also need it for `tok::star` and I don't know which way is better.

Then add the `tok::star` case too:
```diff
--- a/clang/lib/Format/UnwrappedLineParser.cpp
+++ b/clang/lib/Format/UnwrappedLineParser.cpp
@@ -2741,6 +2741,8 @@ bool UnwrappedLineParser::parseParens(TokenType AmpAmpTokenType,
     case tok::kw_requires:
       parseRequiresExpression();
       break;
+    case tok::star:
+    case tok::amp:
     case tok::ampamp:
       if (AmpAmpTokenType != TT_Unknown)
         FormatTok->setFinalizedType(AmpAmpTokenType);
```
I prefer plugging the hole above because that's the direct cause that unlike `&&`, `*` and `&` are not annotated as `TT_PointerOrReference`.

**Comment by HazardyKnusperkeks** [comment]
Made the adaptions, kept the local reference to context.

**Comment by HazardyKnusperkeks** [comment]
> Made the adaptions, kept the local reference to context.

Reverted the local reference, that isn't stable and should not be cached...

**Review by owenca — APPROVED** [review]
