### PR TITLE
[HLSL][Matrix] Add OR and AND logical operator support for matrix

### LINKED ISSUE #172341: Add boolean comparison operator support for HLSL Matrix
## Support these:
https://hlsl.godbolt.org/z/7MsKo1ooj
```hlsl
export bool4x4 AndOp(bool4x4 a, bool4x4 b) {
  return and(a,b);
}

export bool3x3 OrOp(bool3x3 a, bool3x3 b) {
  return or(a,b);
}

```

Error on these:
https://hlsl.godbolt.org/z/Y73hG34Kq
```hlsl
export bool4x4 AndOp(bool4x4 a, bool4x4 b) {
  return a && b;
}

export bool3x3 OrOp(bool3x3 a, bool3x3 b) {
  return a || b;
}

```
```bash

export bool4x4 AndOp(bool4x4 a, bool4x4 b) {
  return a && b;
}

export bool3x3 OrOp(bool3x3 a, bool3x3 b) {
  return a || b;
}
```
```
<source>:2:12: error: operands for short-circuiting logical binary operator must be scalar, for non-scalar types use 'and'
  return a && b;
         ~~^~~~
         and(a, b)
<source>:6:12: error: operands for short-circuiting logical binary operator must be scalar, for non-scalar types use 'or'
  return a || b;
         ~~^~~~
         or(a, b)
```

### PR DESCRIPTION
**Pull request by farzonl**
fixes #172341

This change adds the `or` and `and` HLSL builtins with overloads for the matrix types.

It also disables the logical operators from being used for HLSL 2021. To keep this code from getting too complicated HLSL 2018 and lower logical operator support was not added.

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -13389,6 +13389,25 @@ QualType Sema::CheckVectorLogicalOperands(ExprResult &LHS, ExprResult &RHS,
...
 }
 
+QualType Sema::CheckMatrixLogicalOperands(ExprResult &LHS, ExprResult &RHS,
+                                          SourceLocation Loc,
+                                          BinaryOperatorKind Opc) {
+
+  if (!getLangOpts().HLSL) {
+    assert(false && "Logical operands are not support in C\\C++");
+    return QualType();
+  }
```
Comment (farzonl) [inline clang/lib/Sema/SemaExpr.cpp]: This case is an assert where as the 2018 HLSL case is a Sema diagnostic error because its impossible today for C\C++ code to get into this function without explicit support for logical operators. The HLSL code really only exists to  disable logical operators for the 2021 language mode. The 2018 language mode is suppose to support them but thats not our default language mode right now so that work will be punted on for now.

File: clang/test/SemaHLSL/BuiltIns/logical-mat-operator-errors.hlsl [hunk 2]
```diff
@@ -0,0 +1,33 @@
+
+// RUN: %clang_cc1 -finclude-default-header -triple dxil-pc-shadermodel6.6-library %s -verify -DTEST_FUNC=or
```
Comment (Icohedron) [inline clang/test/SemaHLSL/BuiltIns/logical-mat-operator-errors.hlsl]: nit: there is an empty line at the start of this file
```suggestion
// RUN: %clang_cc1 -finclude-default-header -triple dxil-pc-shadermodel6.6-library %s -verify -DTEST_FUNC=or
```

**Review by Icohedron — APPROVED** [review]
Looks fine to me. Just some whitespace nits.

**Review by bob80905 — APPROVED** [review]
LGTM
