### PR TITLE
[MLIR][Affine] Fix private memref creation bug in affine fusion

### LINKED ISSUE #48703: Incorrect loop fusion in case of a producer with self-dependence
|  |  |
| --- | --- |
| Bugzilla Link | [49359](https://llvm.org/bz49359) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @joker-eph,@bondhugula |

## Extended Description 
Incorrect affine loop fusion occurs in case of a producer that has a self-dependence. As consumer only consumes a part of the memref produced, producer(source) cannot be deleted after the fusion.

Example below:
```
func @&#8203;trial(%producer : memref<32xf32>, %consumer: memref<16xf32>){
  %cst = constant 2.000000e+00 : f32
  affine.for %arg3 = 0 to 32 {
    %0 = affine.load %producer[%arg3] : memref<32xf32>
    %2 = mulf %0, %cst : f32
    affine.store %2, %producer[%arg3] : memref<32xf32>
  }
  affine.for %arg3 = 0 to 16 {
    %0 = affine.load %producer[%arg3] : memref<32xf32>
    %2 = addf %0, %cst : f32
    affine.store %2, %consumer[%arg3] : memref<16xf32>
  }
  return
}
```

`-affine-loop-fusion` results in the following result:
```
module  {
  func @&#8203;trial(%arg0: memref<16xf32>, %arg1: memref<32xf32>) {
    %cst = constant 2.000000e+00 : f32
    affine.for %arg2 = 0 to 32 {
      %0 = affine.load %arg1[%arg2] : memref<32xf32>
      %1 = mulf %0, %cst : f32
      affine.store %1, %arg1[%arg2] : memref<32xf32>
    }
    affine.for %arg2 = 0 to 16 {
      %0 = affine.load %arg1[%arg2] : memref<32xf32>
      %1 = mulf %0, %cst : f32
      affine.store %1, %arg1[%arg2] : memref<32xf32>
      %2 = affine.load %arg1[%arg2] : memref<32xf32>
      %3 = addf %2, %cst : f32
      affine.store %3, %arg0[%arg2] : memref<16xf32>
    }
    return
  }
}
```

### PR DESCRIPTION
**Pull request by bondhugula**
Fix private memref creation bug in affine fusion exposed in the case of
the same memref being loaded from/stored to in producer nest. Make the
private memref replacement sound.

Change affine fusion debug string to affine-fusion - more compact.

Fixes: https://github.com/llvm/llvm-project/issues/48703

### CODE REVIEW

File: mlir/include/mlir/Dialect/Affine/Analysis/Utils.h [hunk 1]
```diff
@@ -610,6 +610,14 @@ FailureOr<AffineValueMap>
 simplifyConstrainedMinMaxOp(Operation *op,
                             FlatAffineValueConstraints constraints);
 
+/// Find the innermost common `Block` of `a` and `b` in the affine scope
+/// that `a` and `b` are part of. Return nullptr if they belong to different
+/// affine scopes. Also, return null if they do not have a common `Block`
```
Comment (arnab-polymage) [inline mlir/include/mlir/Dialect/Affine/Analysis/Utils.h:615]: Nit: null -> nullptr

Comment (arnab-polymage) [reply mlir/include/mlir/Dialect/Affine/Analysis/Utils.h:615]: Nit: Should `Block`, `then` and `else` be inside backticks? They are not function arguments.

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp [hunk 2]
```diff
@@ -12,6 +12,7 @@
 //===----------------------------------------------------------------------===//
 
 #include "mlir/Dialect/Affine/Analysis/Utils.h"
+
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Analysis/Utils.cpp:15]: Please remove this new line

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp [hunk 3]
```diff
@@ -2297,3 +2298,40 @@ FailureOr<AffineValueMap> mlir::affine::simplifyConstrainedMinMaxOp(
...
 }
+
+Block *mlir::affine::findInnermostCommonBlockInScope(Operation *a,
+                                                     Operation *b) {
+  Region *aScope = mlir::affine::getAffineScope(a);
+  Region *bScope = mlir::affine::getAffineScope(b);
+  if (aScope != bScope)
+    return nullptr;
+
+  // Get the block ancestry of `a` while stopping at the affine scope.
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2309]: Nit: `a` -> `op`

Comment (arnab-polymage) [reply mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2309]: Do mention that you are storing the block ancestors in `ancestory`.

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp [hunk 4]
```diff
@@ -2297,3 +2298,40 @@ FailureOr<AffineValueMap> mlir::affine::simplifyConstrainedMinMaxOp(
...
+  auto getBlockAncestry = [&](Operation *op,
+                              SmallVectorImpl<Block *> &ancestry) {
+    Operation *curOp = op;
+    do {
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2313]: Should you do an assert that curOp is not null before the do-while loop as it will execute the body atleast once irrespective of whether the while condition holds? Or else you can use a regular while loop

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp [hunk 5]
```diff
@@ -2297,3 +2298,40 @@ FailureOr<AffineValueMap> mlir::affine::simplifyConstrainedMinMaxOp(
...
+      ancestry.push_back(curOp->getBlock());
+      if (curOp->getParentRegion() == aScope)
+        break;
+      curOp = curOp->getParentOp();
+    } while (curOp);
+    assert(curOp && "can't reach root op without passing through affine scope");
+    std::reverse(ancestry.begin(), ancestry.end());
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2320]: llvm::reverse?

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp [hunk 6]
```diff
@@ -237,29 +237,71 @@ static void sinkSequentialLoops(MemRefDependenceGraph::Node *node) {
...
+  assert(!producerStores.empty() && "expected producer store");
+
+  // We first find the common block that contains the producer stores and
+  // the slice computation. The first ancestor among the ancestors of the
+  // producer stores in that common block is the dominance filter to use for
+  // replacement.
+  Block *commonBlock = nullptr;
+  // Find the common block of all relevant operations.
+  for (Operation *store : producerStores) {
+    if (!commonBlock)
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:256]: You can use a ternary operator here. Will save line and the loop braces

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp [hunk 7]
```diff
@@ -237,29 +237,71 @@ static void sinkSequentialLoops(MemRefDependenceGraph::Node *node) {
...
+  return firstAncestor;
+}
+
 // Creates and returns a private (single-user) memref for fused loop rooted
 // at 'forOp', with (potentially reduced) memref size based on the
 // MemRefRegion written to by 'srcStoreOpInst' at depth 'dstLoopDepth'.
 // TODO: consider refactoring the common code from generateDma and
 // this one.
-static Value createPrivateMemRef(AffineForOp forOp, Operation *srcStoreOpInst,
+static Value createPrivateMemRef(AffineForOp forOp,
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:284]: Document the new function arguments and remove the old ones.

File: mlir/test/Dialect/Affine/loop-fusion-4.mlir [hunk 8]
```diff
@@ -285,3 +285,32 @@ module {
     spirv.ReturnValue %3 : !spirv.array<8192 x f32>
   }
 }
+
+// -----
+
+// PRODUCER-CONSUMER-LABEL: func @same_memref_load_store
+func.func @same_memref_load_store(%producer : memref<32xf32>, %consumer: memref<16xf32>){
```
Comment (arnab-polymage) [inline mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Should we have a test with multiple stores inside consumer nest?

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp (hunk 2 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Analysis/Utils.cpp:15]: This new line should be there per style - to separate the main header for this file from the group of other includes.

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp (hunk 5 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2320]: llvm::reverse reverses an iteration range - not the elements of a container! Common source of bugs/confusion!

File: mlir/include/mlir/Dialect/Affine/Analysis/Utils.h (hunk 1 above)
Comment (bondhugula) [reply mlir/include/mlir/Dialect/Affine/Analysis/Utils.h:615]: It's not for just function arguments, but I use it for other proper MLIR notation that would otherwise make the sentence broken.

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp (hunk 4 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2313]: This is meant to be executed at least once - so a do-while loop. `curOp` is initialized with a function argument. The caller is expected to pass a non-null operation. We don't assert for such bugs.

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp (hunk 6 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:256]: Thanks, improved it further in fact.

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp (hunk 7 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:280]: Done.

File: mlir/test/Dialect/Affine/loop-fusion-4.mlir (hunk 8 above)
Comment (bondhugula) [reply mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Consumer nests stores aren't relevant to this change/testing. The dependence is between the producer store and consumer load. The consumer stores could be to different memrefs, and that's unrelated to this fix.

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp [hunk 9]
```diff
@@ -237,29 +237,67 @@ static void sinkSequentialLoops(MemRefDependenceGraph::Node *node) {
...
+                                       ArrayRef<Operation *> producerStores) {
+  assert(!producerStores.empty() && "expected producer store");
+
+  // We first find the common block that contains the producer stores and
+  // the slice computation. The first ancestor among the ancestors of the
+  // producer stores in that common block is the dominance filter to use for
+  // replacement.
+  Block *commonBlock = nullptr;
+  // Find the common block of all relevant operations.
+  for (Operation *store : producerStores) {
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:255]: You can further inline the ternary expression for otherOp in `findInnermostCommonBlockInScope` function call and remove the l;oop braces.

File: mlir/lib/Dialect/Affine/Analysis/Utils.cpp [hunk 10]
```diff
@@ -2297,3 +2298,41 @@ FailureOr<AffineValueMap> mlir::affine::simplifyConstrainedMinMaxOp(
...
 }
+
+Block *mlir::affine::findInnermostCommonBlockInScope(Operation *a,
+                                                     Operation *b) {
+  Region *aScope = mlir::affine::getAffineScope(a);
+  Region *bScope = mlir::affine::getAffineScope(b);
+  if (aScope != bScope)
+    return nullptr;
+
+  // Get the block ancestry of `op` while stopping at the affine scope and store
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Analysis/Utils.cpp:2309]: Mention that `aScope` is the affine scope you are referring to here

File: mlir/test/Dialect/Affine/loop-fusion-4.mlir (hunk 8 above)
Comment (arnab-polymage) [reply mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Can you add an example with multiple producer stores then? You have replaced `scrStoreOpInst` with `storeOps`  in argument list of `createPrivateMemRef` function. A unit test reflecting this change will be helpful.

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp [hunk 11]
```diff
@@ -332,11 +370,12 @@ static Value createPrivateMemRef(AffineForOp forOp, Operation *srcStoreOpInst,
       AffineMap::get(outerIVs.size() + rank, 0, remapExprs, forOp.getContext());
 
   // Replace all users of 'oldMemRef' with 'newMemRef'.
+  Operation *domFilter =
+      getDominanceFilterForPrivateMemRefRepl(sliceInsertionBlock, storeOps);
   LogicalResult res =
       replaceAllMemRefUsesWith(oldMemRef, newMemRef, {}, indexRemap,
```
Comment (arnab-polymage) [inline mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:376]: /*argumentName=*/{} for 3rd argument passed in `replaceAllMemRefUsesWith`

**Review by arnab-polymage — APPROVED** [review]
LGTM

File: mlir/include/mlir/Dialect/Affine/Analysis/Utils.h (hunk 1 above)
Comment (arnab-polymage) [reply mlir/include/mlir/Dialect/Affine/Analysis/Utils.h]: nIT: Also, return **`nullptr`** if they do not have a common `Block`

**Review by arnab-polymage — APPROVED** [review]

File: mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp (hunk 9 above)
Comment (bondhugula) [reply mlir/lib/Dialect/Affine/Transforms/LoopFusion.cpp:255]: This doesn't help with compactness (still an additional line) and less readable without `otherOp`.

File: mlir/test/Dialect/Affine/loop-fusion-4.mlir (hunk 8 above)
Comment (bondhugula) [reply mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Good point, but multiple producer stores (to the same memref) aren't supported for fusion. However, this utility still supports that handling. To exercise it, we'll have to add that support in fusion.

Comment (bondhugula) [reply mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Actually, multiple producer stores (to different memrefs) are supported. I'll find a test case to add here.

Comment (bondhugula) [reply mlir/test/Dialect/Affine/loop-fusion-4.mlir:292]: Done, thanks.
