### PR TITLE
[X86] Fix overflow with large stack probes on x86-64

### LINKED ISSUE #113218: [X86] Large stack frames are miscompiled with -fstack-clash-protection
On x86-64 with `-fstack-clash-protection`, the following code compiles to an infinite loop that consumes all physical memory:

    void foo() {
        char x[0xa0000000];
    }

It works fine on other architectures (including 32-bit x86), and it works without `-fstack-clash-protection`.

Here's the incorrect stack probe loop it produces:

            mov     r11, rsp
            sub     r11, -1610616832
    .LBB0_1:
            sub     rsp, 4096
            mov     qword ptr [rsp], 0
            cmp     rsp, r11
            jne     .LBB0_1

(Note that if you look at LLVM's assembly output, it displays the second instruction misleadingly as `sub r11, 2684350464`, which makes it look correct.  But in fact that's not a valid instruction; both llvm-mc and GNU as correctly refuse to assemble it.  64-bit SUB takes a 32-bit *sign-extended* immediate, so it's not possible to encode 2684350464.)

I've got a fix, which I'll submit shortly.

### PR DESCRIPTION
**Pull request by mconst**
When emitting an inline stack probe loop, we can't use SUBri to calculate the loop bound if it doesn't fit in a 32-bit (possibly sign-extended) immediate.

Fixes #113218.

### CODE REVIEW

File: llvm/lib/Target/X86/X86FrameLowering.cpp [hunk 1]
```diff
@@ -798,18 +798,43 @@ void X86FrameLowering::emitStackProbeInlineGenericLoop(
...
+      BuildMI(MBB, MBBI, DL, TII.get(X86::MOV64ri), FinalStackProbed)
+          .addImm(-BoundOffset)
+          .setMIFlag(MachineInstr::FrameSetup);
+      BuildMI(MBB, MBBI, DL, TII.get(X86::ADD64rr), FinalStackProbed)
+          .addReg(FinalStackProbed)
+          .addReg(StackPtr)
+          .setMIFlag(MachineInstr::FrameSetup);
+    } else {
+      // We're being asked to probe a stack frame that's 4 GiB or larger,
+      // but our stack pointer is only 32 bits.
```
Comment (efriedma-quic) [inline llvm/lib/Target/X86/X86FrameLowering.cpp:831]: I'm a little concerned about printing an error for valid code... maybe less of an issue here than in other contexts, but generally, stack overflows should be a runtime error.

Maybe we can just set the size of the allocation to 2^32-1, and just let the OS generate a stack overflow trap?

Comment (mconst) [reply llvm/lib/Target/X86/X86FrameLowering.cpp:831]: Thanks for looking at this!

Sure, trapping at runtime sounds fine, although I'd kind of like to make it an unconditional trap rather than allocating less than the user requested and relying on it to fail.  (It's not likely, but you could imagine a situation where the user's code is elsewhere in the address space and the entire lower 4 GiB is available for the stack.  The stack pointer would also have to be unaligned.)

Would you replace the error with a warning, or just skip it entirely and rely on the existing `-Wframe-larger-than` warning?

Comment (efriedma-quic) [reply llvm/lib/Target/X86/X86FrameLowering.cpp:831]: I don't think it's realistic to worry about an 32-bit x86 application with an address-space larger than 4GB; I don't think it's actually possible to setup a configuration like that.  But an explicit trap is probably okay too.

A warning has basically the same issues as an error: optimizations can cause it to trigger in dynamically unreachable code, and the user is left with a nonsense diagnostic that can only be fixed by blindly refactoring their code until the compiler stops complaining.  So general policy is that we don't emit warnings from the backend for runtime issues.

Comment (mconst) [reply llvm/lib/Target/X86/X86FrameLowering.cpp]: Sounds good!  I've updated the code.

**Comment by efriedma-quic** [comment]
Ping.  (Current version looks okay to me, but I want a second opinion from an x86 backend expert.)

File: llvm/test/CodeGen/X86/stack-clash-huge.ll [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+; CHECK-X32-NEXT:    jne .LBB0_1
+; CHECK-X32-NEXT:  # %bb.2:
+; CHECK-X32-NEXT:    subl $1928, %esp # imm = 0x788
+; CHECK-X32-NEXT:    .cfi_def_cfa_register %rsp
+; CHECK-X32-NEXT:    .cfi_def_cfa_offset 2399999888
+; CHECK-X32-NEXT:    movl $1, 264(%esp)
+; CHECK-X32-NEXT:    movl $1, 28664(%esp)
+; CHECK-X32-NEXT:    movl -128(%esp), %eax
+; CHECK-X32-NEXT:    movl $2399999880, %ecx # imm = 0x8F0D1788
+; CHECK-X32-NEXT:    addq %rcx, %esp
```
Comment (phoebewang) [inline llvm/test/CodeGen/X86/stack-clash-huge.ll:72]: Bad instruction.

File: llvm/lib/Target/X86/X86FrameLowering.cpp [hunk 3]
```diff
@@ -798,18 +798,40 @@ void X86FrameLowering::emitStackProbeInlineGenericLoop(
...
+          .setMIFlag(MachineInstr::FrameSetup);
+      BuildMI(MBB, MBBI, DL, TII.get(X86::ADD64rr), FinalStackProbed)
+          .addReg(FinalStackProbed)
+          .addReg(StackPtr)
+          .setMIFlag(MachineInstr::FrameSetup);
+    } else {
+      // We're being asked to probe a stack frame that's 4 GiB or larger,
+      // but our stack pointer is only 32 bits.  This might be unreachable
+      // code, so don't complain now; just trap if it's reached at runtime.
+      BuildMI(MBB, MBBI, DL, TII.get(X86::TRAP));
```
Comment (phoebewang) [inline llvm/lib/Target/X86/X86FrameLowering.cpp:833]: Should add a test case for it if don't complain.

File: llvm/test/CodeGen/X86/stack-clash-huge.ll (hunk 2 above)
Comment (mconst) [reply llvm/test/CodeGen/X86/stack-clash-huge.ll:72]: Thanks for looking at this!

I think this is an unrelated bug.  LLVM generates the same invalid instruction even without my changes -- you can reproduce it by compiling the following code with `-mx32 -fomit-frame-pointer`:

```c
void foo() {
    char x[0xa0000000];
}
```

https://godbolt.org/z/E41ecqPna

If you want, I can try to fix this, but maybe it might make more sense to do that as a separate PR?

File: llvm/lib/Target/X86/X86FrameLowering.cpp (hunk 3 above)
Comment (mconst) [reply llvm/lib/Target/X86/X86FrameLowering.cpp:833]: Done!

**Review by phoebewang — APPROVED** [review]
LGTM.

**Comment by efriedma-quic** [comment]
Ping

**Comment by phoebewang** [comment]
@mconst do you have any update? Otherwise, I can help merge it.

**Comment by mconst** [comment]
Nope, I think this is ready to merge!

**Comment by mconst** [comment]
The buildbot failure looks like it's from the bad instruction you pointed out earlier (which actually gets detected automatically when expensive checks are enabled).  I think the fix should be pretty simple -- I'll try writing up a PR for it soon.

**Comment by RKSimon** [comment]
@mconst is the fix imminent? currently the expensive checks bots are failing due to this.

I'd also suggest you add `-verify-machineinstrs ` to the RUN commands in the stack-clash test files to better expose this.

**Comment by mconst** [comment]
I should have the PR ready within a couple of hours at the latest, although it'll probably still take time for it to be reviewed and merged.  If that's too long, feel free to revert this for now!

Sure, I'll add `-verify-machineinstrs` to the test files.

**Comment by mconst** [comment]
Okay, I've submitted the fix as #124041.
