### PR TITLE
[Sema] Enforce parameter match for ownership_returns attribute

### LINKED ISSUE #188733: [clang] crashes when multiple ownership_returns attributes are applied to a function
Reproducer:
https://godbolt.org/z/9qW6b3re8
```cpp
void *f(int, int)
  __attribute__((ownership_returns(used)))
  __attribute__((ownership_returns(foo, 2)));
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/include/clang/AST/Attr.h:350: unsigned int clang::ParamIdx::getSourceIndex() const: Assertion `isValid() && "ParamIdx must be valid"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:3:45: current parser token ';'
 #0 0x00000000044ee5a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44ee5a8)
 #1 0x00000000044eb3d4 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44eb3d4)
 #2 0x00000000044eb9f4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44eb9f4)
 #3 0x000000000442ac98 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x0000724373e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x0000724373e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x0000724373e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x0000724373e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x0000724373e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x0000724373e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x00000000071b8a41 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71b8a41)
#11 0x00000000071e3bac handleOwnershipAttr(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) SemaDeclAttr.cpp:0:0
#12 0x00000000071f7633 ProcessDeclAttribute(clang::Sema&, clang::Scope*, clang::Decl*, clang::ParsedAttr const&, clang::Sema::ProcessDeclAttributeOptions const&) (.isra.0) SemaDeclAttr.cpp:0:0
#13 0x00000000071fa79b clang::Sema::ProcessDeclAttributes(clang::Scope*, clang::Decl*, clang::Declarator const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71fa79b)
#14 0x00000000071a84e3 clang::Sema::ActOnFunctionDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71a84e3)
#15 0x00000000071aed9b clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71aed9b)
#16 0x00000000071afbb4 clang::Sema::ActOnDeclarator(clang::Scope*, clang::Declarator&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71afbb4)
#17 0x0000000006dddac3 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dddac3)
#18 0x0000000006deb2ea clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6deb2ea)
#19 0x0000000006da899b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6da899b)
#20 0x0000000006da919f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6da919f)
#21 0x0000000006db0bd1 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db0bd1)
#22 0x0000000006db1ae5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db1ae5)
#23 0x0000000006db1ed0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db1ed0)
#24 0x0000000006d92a63 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d92a63)
#25 0x0000000004fef9d8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4fef9d8)
#26 0x00000000053092c5 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x53092c5)
#27 0x0000000005288e0e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5288e0e)
#28 0x0000000005405b2d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5405b2d)
#29 0x0000000000de5fc2 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde5fc2)
#30 0x0000000000ddc8fa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#31 0x0000000000ddca7d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#32 0x0000000005058e89 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#33 0x000000000442b0d4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x442b0d4)
#34 0x00000000050594b6 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#35 0x0000000005018592 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5018592)
#36 0x000000000501953e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x501953e)
#37 0x00000000050210f5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x50210f5)
#38 0x0000000000de2324 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde2324)
#39 0x0000000000c9954a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc9954a)
#40 0x0000724373e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#41 0x0000724373e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#42 0x0000000000ddc395 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xddc395)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by davidmenggx**
Previously parsing multiple ownership_returns attributes with different arguments could lead to a crash. The documentation states that if forward declarations have ownership_returns, they must have the same arguments, and it may appear at most once per declaration.

This patch ensures that if multiple ownership_returns attributes are present, their arguments (identifier and the optional index) must exactly match. The diagonstic err_ownership_param_mismatch is introduced for clarity.

Test cases for f15, C::f, and the newly added f22 were also updated to match the requirement that all declarations of ownership_returns have the same arguments, using the err_ownership_param_mismatch diagonstic.

Fixes #188733

### CODE REVIEW

**Comment by davidmenggx** [comment]
@Sirraide could you please take a look at this?

For clarity, should a note diagnostic be added to the first declaration of ownership_returns on the error case?

File: clang/test/Sema/attr-ownership.c [hunk 1]
```diff
@@ -19,8 +19,8 @@ void f13(int *i, int *j) __attribute__((ownership_holds(foo, 1))) __attribute__(
 void f14(int i, int j, int *k) __attribute__((ownership_holds(foo, 3))) __attribute__((ownership_takes(foo, 3)));  // expected-error {{'ownership_takes' and 'ownership_holds' attributes are not compatible}}
 
 void *f15(int, int)
-  __attribute__((ownership_returns(foo, 1)))  // expected-error {{'ownership_returns' attribute index does not match; here it is 1}}
-  __attribute__((ownership_returns(foo, 2))); // expected-note {{declared with index 2 here}}
+  __attribute__((ownership_returns(foo, 1)))
+  __attribute__((ownership_returns(foo, 2))); // expected-error {{'ownership_returns' attribute arguments do not match the previous declaration}}
```
Comment (AaronBallman) [inline clang/test/Sema/attr-ownership.c]: I think the previous diagnostic behavior was better because it shows how they don't match and where the previous declaration was declared.

File: clang/include/clang/Basic/DiagnosticSemaKinds.td [hunk 2]
```diff
@@ -3522,6 +3516,8 @@ def err_ownership_returns_index_mismatch : Error<
   "'ownership_returns' attribute index does not match; here it is %0">;
 def note_ownership_returns_index_mismatch : Note<
   "declared with index %0 here">;
+def err_ownership_param_mismatch : Error<
```
Comment (AaronBallman) [inline clang/include/clang/Basic/DiagnosticSemaKinds.td]: I don't think we should need a new diagnostic for this, `err_ownership_returns_index_mismatch` seems to suffice. I think we can modify those diagnostics to be more like:
```
def err_ownership_returns_index_mismatch : Error<
  "'ownership_returns' attribute index does not match; here it is %select{%0|omitted}1">;
def note_ownership_returns_index_mismatch : Note<
  "declared %select{with index %0|without an index}1 here">;
```

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 3]
```diff
@@ -1558,38 +1558,40 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
...
+            << AL << I
+            << (AL.isRegularKeywordAttribute() ||
+                I->isRegularKeywordAttribute());
+        return;
       }
     }
     OwnershipArgs.push_back(Idx);
   }
 
+  for (const auto *I : D->specific_attrs<OwnershipAttr>()) {
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclAttr.cpp]: Can we handle this from the existing loop instead of walking the attributes twice?

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this!

Please be sure to also add a release note to `clang/docs/ReleaseNotes.rst` so users know about the fix.

**Comment by davidmenggx** [comment]
@AaronBallman Thank you for the feedback! 

I've reverted back to the original loop structure, matching the (updated) previous diagnostic

But I believe that we need to check for the case where the current ownership_returns attribute does not contain an index, but previous declarations do. The current loop structure would miss this, so I've added it before the loop

File: clang/test/Sema/attr-ownership.cpp [hunk 4]
```diff
@@ -1,7 +1,7 @@
...
-       __attribute__((ownership_returns(foo, 2)))  // expected-error {{'ownership_returns' attribute index does not match; here it is 2}}
-       __attribute__((ownership_returns(foo, 3))); // expected-note {{declared with index 3 here}}
-};
+// RUN: %clang_cc1 %s -verify -fsyntax-only
+
+class C {
+  void *f(int, int)
+       __attribute__((ownership_returns(foo, 2)))  // expected-error {{'ownership_returns' attribute index does not match; here it is 2}}
+       __attribute__((ownership_returns(foo, 3))); // expected-note {{declared with index 3 here}}
+};
```
Comment (steakhal) [inline clang/test/Sema/attr-ownership.cpp]: Interesting. Why does this diff show up? These look pretty much the same to me, so what's going on? Some line ending change?

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 5]
```diff
@@ -1558,21 +1572,23 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
...
-              << AL << I
-              << (AL.isRegularKeywordAttribute() ||
-                  I->isRegularKeywordAttribute());
-          return;
+        S.Diag(AL.getLoc(), diag::err_attributes_are_not_compatible)
+            << AL << I
+            << (AL.isRegularKeywordAttribute() ||
+                I->isRegularKeywordAttribute());
+        return;
       } else if (K == OwnershipAttr::Returns &&
```
Comment (steakhal) [inline clang/lib/Sema/SemaDeclAttr.cpp]: I think we should honour the [else-after-return](https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html) rule.

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 6]
```diff
@@ -1558,21 +1572,23 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
...
           S.Diag(I->getLocation(), diag::err_ownership_returns_index_mismatch)
-              << I->args_begin()->getSourceIndex();
-          if (I->args_size())
-            S.Diag(AL.getLoc(), diag::note_ownership_returns_index_mismatch)
-                << Idx.getSourceIndex() << Ex->getSourceRange();
+              << IIdx << (IHasArgs ? 0 : 1);
+
+          S.Diag(AL.getLoc(), diag::note_ownership_returns_index_mismatch)
+              << Idx.getSourceIndex() << 0 << Ex->getSourceRange();
           return;
```
Comment (steakhal) [inline clang/lib/Sema/SemaDeclAttr.cpp:1594]: I'm going to be honest with you, I'm genuinely nervous that this function is 137 lines long. No surprise it had a bug.
No actions expected.

**Review by steakhal — COMMENTED** [review]
Hey, I'm glad you are working on this. I tried my best to look at the correctness of the patch and to me it looks plausible - but I'd like to highlight that I'm not a SAT solver and the number of `if` blocks and compound conditions have surpassed the time I can spare for upstream reviews - so I could have missed something.

Looking at the code, I get the impression that you carefully studied the code and that you are familiar with the LLVM coding style which made me a bit more relaxed.

File: clang/test/Sema/attr-ownership.cpp (hunk 4 above)
Comment (davidmenggx) [reply clang/test/Sema/attr-ownership.cpp]: I previously used another diagnostic, and reverted it back in the latest commit

Comment (steakhal) [reply clang/test/Sema/attr-ownership.cpp]: I'm looking at the "Files Changed" tab, with "All commits" - yet this diff shows up. This means, that if you were to merge this to llvm/main, we should change this file.
My question is, what changes here? Why does it appear in the diff?

My theory is that it has something to do with line-endings because if I take the "removed lines" and diff it with the "added lines" it appears to be identical.
Nevertheless, it's very suspicious, and if nothing changes, just call `git checkout llvm/main -- clang/test/Sema/attr-ownership.cpp` to restore it.

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 7]
```diff
@@ -1558,24 +1572,30 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
...
         }
-      } else if (K == OwnershipAttr::Takes &&
+      }
+      
+      if (K == OwnershipAttr::Takes &&
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclAttr.cpp]: I think this one is still an `else if` situation because there's not an unconditional return before it.

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 8]
```diff
@@ -1526,6 +1526,20 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
     Module = &S.PP.getIdentifierTable().get(ModuleName);
   }
 
+  // Check if the new ownership_returns attribute does not contain 
+  // an index, but previous attributes do
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclAttr.cpp]:
```suggestion
  // an index, but previous attributes do.
```

**Review by AaronBallman — COMMENTED** [review]
Only a few minor nits from me, otherwise I think this LG. Thank you!

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by AaronBallman** [comment]
Oops, release notes are in a conflicting state; once that's fixed up, I'll press the auto-merge button. However, it wants to use:

> 159511732+davidmenggx@users.noreply.github.com

for your email; our developer policy requires a public email address in GitHub (https://llvm.org/docs/DeveloperPolicy.html#email-addresses) so that also needs to be updated before I can merge.

**Comment by davidmenggx** [comment]
@AaronBallman Just added the email, thank you!
