### PR TITLE
[SelectionDAG][RISCV] Use VP_LOAD to widen MLOAD in type legalization when possible.

### LINKED ISSUE #140198: [RISCV] <vscale x 1 x *> masked.load crashes with Zve32
`<vscale x 1 x *>` types aren't legal with Zve32*. The type legalizer is unable to widen non-VP masked load. It currently asserts on a call getVectorNumElements which isn't valid for scalable vectors. Replacing that with getVectorElementCount crashes in legalizing concat_vectors due to the padding of the mask with 0 elements.

I don't think we can do the 0 element padding for scalable vectors. Probably the best thing to do is to widen using VP_LOAD and limit the VL instead of padding the mask.

CC: @preames @lukel97 @wangpc-pp

### PR DESCRIPTION
**Pull request by topperc**
Padding the mask using 0 elements doesn't work for scalable vectors. Use VP_LOAD and change the VL instead.

This fixes crash for Zve32x. Test file was split since i64 isn't a valid element type for Zve32x.

Fixes #140198.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp [hunk 1]
```diff
@@ -6111,18 +6111,37 @@ SDValue DAGTypeLegalizer::WidenVecRes_VECTOR_COMPRESS(SDNode *N) {
...
   ISD::LoadExtType ExtType = N->getExtensionType();
   SDLoc dl(N);
 
+  EVT WideMaskVT =
+      EVT::getVectorVT(*DAG.getContext(), MaskVT.getVectorElementType(),
+                       WidenVT.getVectorElementCount());
+
+  if (ExtType == ISD::NON_EXTLOAD &&
+      TLI.isOperationLegalOrCustom(ISD::VP_LOAD, WidenVT) &&
+      TLI.isTypeLegal(WideMaskVT)) {
```
Comment (lukel97) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp:6128]: Does this need to be limited to scalable vectors only? If the existing widening already worked for fixed vectors

Comment (topperc) [reply llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp:6128]: Using VL should be a more efficient widening for fixed vectors, but I guess we don't have any tests to show that.

File: llvm/test/CodeGen/RISCV/rvv/masked-load-int-e64.ll [hunk 2]
```diff
@@ -0,0 +1,47 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
+; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s | FileCheck %s
+; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs < %s | FileCheck %s
+
+define <vscale x 1 x i64> @masked_load_nxv1i64(ptr %a, <vscale x 1 x i1> %mask) nounwind {
```
Comment (preames) [inline llvm/test/CodeGen/RISCV/rvv/masked-load-int-e64.ll:5]: Are these crash tests?  Or can they be pre-commited so the change is visible?

File: llvm/test/CodeGen/RISCV/rvv/masked-load-int.ll [hunk 3]
```diff
@@ -1,51 +1,66 @@
...
+; ZVE32-NEXT:    vsetvli zero, a1, e32, m1, ta, ma
+; ZVE32-NEXT:    vle32.v v8, (a0), v0.t
+; ZVE32-NEXT:    ret
   %load = call <vscale x 1 x i32> @llvm.masked.load.nxv1i32(ptr %a, i32 4, <vscale x 1 x i1> %mask, <vscale x 1 x i32> undef)
   ret <vscale x 1 x i32> %load
 }
 declare <vscale x 1 x i32> @llvm.masked.load.nxv1i32(ptr, i32, <vscale x 1 x i1>, <vscale x 1 x i32>)
 
-define <vscale x 1 x i64> @masked_load_nxv1i64(ptr %a, <vscale x 1 x i1> %mask) nounwind {
-; CHECK-LABEL: masked_load_nxv1i64:
```
Comment (preames) [inline llvm/test/CodeGen/RISCV/rvv/masked-load-int.ll:39]: Bad test updates.

File: llvm/test/CodeGen/RISCV/rvv/masked-load-int-e64.ll (hunk 2 above)
Comment (topperc) [reply llvm/test/CodeGen/RISCV/rvv/masked-load-int-e64.ll:5]: This file doesn't crash, but the new <vscale 1 x 1 x *> tests in the other file are crashes with the new command line.

File: llvm/test/CodeGen/RISCV/rvv/masked-load-int.ll (hunk 3 above)
Comment (topperc) [reply llvm/test/CodeGen/RISCV/rvv/masked-load-int.ll:39]: I had to split the test file since i64 isn't a legal element type for masked load under Zve32.

**Review by lukel97 — APPROVED** [review]
LGTM
