### PR TITLE
[MLIR][GPU] Fix async.yield gpu.async.token lowering race

### LINKED ISSUE #170833: [mlir] `Integration/GPU/CUDA/async.mlir` is very unstable
This test fails regularly. A quick search shows this has occurred on around 200+ unrelated PRs. 

https://github.com/llvm/llvm-project/pulls?q=is%3Apr+Integration%2FGPU%2FCUDA%2Fasync.mlir+is%3Aclosed

This test should be disabled (or corrected to handle the failing case).

### PR DESCRIPTION
**Pull request by jaredhoberock**
Root cause of #170833 (flakiness of `Integration/GPU/CUDA/async.mlir` on the Tesla T4 mlir-nvidia buildbot).

In `gpu-to-llvm`, two patterns matched `async.yield` with the same benefit: the structural `ConvertYieldOpTypes` from `populateAsyncStructuralTypeConversionsAndLegality` (which just retypes operands), and `ConvertAsyncYieldToGpuRuntimeCallPattern` (which also creates and records an event on the stream backing each `gpu.async.token` operand). When the IR contained `gpu.launch_func`, the dialect-conversion framework picked the structural pattern, silently dropping the event record. The `async.execute` then yielded a stream pointer where its consumers expected an event, and the host await ended up calling `cuEventSynchronize` on a stream pointer. That call returns an error without waiting, so the host raced against the GPU.

This change implements a fix which registers `ConvertAsyncYieldToGpuRuntimeCallPattern` with pattern benefit 2 so it wins on yields carrying `gpu.async.token` operands. The structural rewriter still handles yields without token operands.

Also adds a new test `lower-async-to-gpu-runtime-calls.mlir` to check the correct IR shape of `async.yield` after a `gpu.launch_func`.

Assisted-by: Claude

Fixes #170833

### CODE REVIEW

File: mlir/include/mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h [hunk 1]
```diff
@@ -30,9 +30,15 @@ class RewritePatternSet;
 /// the corresponding async.yield ops need to update their types accordingly to
 /// the TypeConverter, but otherwise don't care what type conversions are
 /// happening.
+///
+/// `addStructuralYieldPattern` controls whether the structural pattern for
+/// `async.yield` is registered. Callers that install their own (more
+/// specialized) `async.yield` rewriter should pass `false` to avoid pattern
+/// competition with that rewriter. The dynamic legality marker for
```
Comment (joker-eph) [inline mlir/include/mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h]: Why wouldn't instead the callers install their own pattern with a higher benefit?

**Comment by jaredhoberock** [comment]
@joker-eph Switched to bumping the benefit of the pattern per your suggestion & reverted the other changes which changed the API involved.

**Review by joker-eph — APPROVED** [review]
