### PR TITLE
[clang] Concepts: support pack expansions for type constraints

### LINKED ISSUE #131798: [Clang] Crash involving use of NTTP pack in type constraint for lambda parameter
```c++
template <class T0>
struct tuple { T0 elem0; };

template <class, class>
concept C = true;

template <int>
struct Foo {};

template <int... Vals>
constexpr tuple fs{[] (C<Foo<Vals>> auto) {}...};

int main() {
    fs<0>.elem0(1);
}
```

See https://compiler-explorer.com/z/WEYanzYx8.

Assertion:
```console
clang++: /root/llvm-project/clang/lib/AST/ExprConstant.cpp:16904:
bool clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, const clang::ASTContext&, clang::Expr::ConstantExprKind) const:
Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.
```

<details>

<summary>Stack dump</summary>

```console
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:14:18: current parser token ')'
2.	<source>:13:12: parsing function body 'main'
3.	<source>:13:12: in compound statement ('{}')
 #0 0x0000000003e87c38 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e87c38)
 #1 0x0000000003e858c4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e858c4)
 #2 0x0000000003dca758 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000799d78642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000799d786969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000799d78642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000799d786287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000799d7862871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000799d78639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00000000077918ba clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, clang::ASTContext const&, clang::Expr::ConstantExprKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x77918ba)
#10 0x000000000679da46 clang::ActionResult<clang::Expr*, true> calculateConstraintSatisfaction<calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::ConstraintEvaluator>(clang::Sema&, clang::Expr const*, clang::ConstraintSatisfaction&, calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::ConstraintEvaluator const&) SemaConcept.cpp:0:0
#11 0x000000000679f17e CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) SemaConcept.cpp:0:0
#12 0x000000000679f7dd clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x679f7dd)
#13 0x00000000067a0828 clang::Sema::CheckInstantiatedFunctionTemplateConstraints(clang::SourceLocation, clang::FunctionDecl*, llvm::ArrayRef<clang::TemplateArgument>, clang::ConstraintSatisfaction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67a0828)
#14 0x0000000006fbff55 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, bool, llvm::function_ref<bool ()>) (.constprop.0) SemaTemplateDeduction.cpp:0:0
#15 0x0000000006fc0397 void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::'lambda1'()>(long) SemaTemplateDeduction.cpp:0:0
#16 0x0000000007d8dcb1 clang::StackExhaustionHandler::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7d8dcb1)
#17 0x0000000006f98475 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f98475)
#18 0x0000000006dd96e1 clang::Sema::AddMethodTemplateCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::TemplateArgumentListInfo*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, clang::OverloadCandidateParamOrder) (.constprop.0) SemaOverload.cpp:0:0
#19 0x0000000006dda031 clang::Sema::AddMethodCandidate(clang::DeclAccessPair, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, clang::OverloadCandidateParamOrder) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dda031)
#20 0x0000000006dea682 clang::Sema::BuildCallToObjectOfClassType(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dea682)
#21 0x00000000069f6ca3 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69f6ca3)
#22 0x00000000069f758c clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x69f758c)
#23 0x0000000006531a92 clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6531a92)
#24 0x000000000652a281 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x652a281)
#25 0x000000000652c3e7 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x652c3e7)
#26 0x000000000652c479 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x652c479)
#27 0x0000000006530fd9 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6530fd9)
#28 0x00000000065b5289 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b5289)
#29 0x00000000065ab434 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65ab434)
#30 0x00000000065ac3c0 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65ac3c0)
#31 0x00000000065ad2c1 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65ad2c1)
#32 0x00000000065aea5a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65aea5a)
#33 0x00000000064bf923 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64bf923)
#34 0x00000000064f485d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64f485d)
#35 0x00000000064b357e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64b357e)
#36 0x00000000064b3d39 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64b3d39)
#37 0x00000000064bb603 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64bb603)
#38 0x00000000064bc4dd clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64bc4dd)
#39 0x00000000064aea8a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64aea8a)
#40 0x0000000004842da8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4842da8)
#41 0x0000000004b127f5 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b127f5)
#42 0x0000000004a94a2e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a94a2e)
#43 0x0000000004c024fe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c024fe)
#44 0x0000000000d50baf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd50baf)
#45 0x0000000000d4836a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#46 0x000000000488b309 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#47 0x0000000003dcabf4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dcabf4)
#48 0x000000000488b91f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#49 0x000000000484e38d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x484e38d)
#50 0x000000000484f41e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x484f41e)
#51 0x0000000004856af5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4856af5)
#52 0x0000000000d4d9a8 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd4d9a8)
#53 0x0000000000c146c4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc146c4)
#54 0x0000799d78629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#55 0x0000799d78629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#56 0x0000000000d47e15 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd47e15)
```

</details>

### PR DESCRIPTION
**Pull request by mizvekov**
This reverts an earlier attempt (adb0d8ddceb143749c519d14b8b31b481071da77 and 50e5411e4247421fd606f0a206682fcdf0303ae3) to support these expansions,
which was limited to type arguments and which subverted the purpose
of SubstTemplateTypeParmType.

This propagates the ArgumentPackSubstitutionIndex along with the
AssociatedConstraint, so that the pack expansion works, without
needing any new transforms or otherwise any changes to the template
instantiation process.

This keeps the tests from the reverted commits, and adds a few more
showing the new solution also works for NTTPs.

Fixes https://github.com/llvm/llvm-project/issues/131798

### CODE REVIEW

**Review by cor3ntin — CHANGES_REQUESTED** [review]
I like the simplification but the changes to subsumption do not look correct to me

I also want to make sure @zyn0217 sees this

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -3239,61 +3162,11 @@ bool Sema::SubstTypeConstraint(
...
-          /*FoundDecl=*/TC->getConceptReference()->getFoundDecl(), &InstArgs,
-          Inst, ConstrainedType,
-          Inst->isParameterPack()
-              ? cast<CXXFoldExpr>(TC->getImmediatelyDeclaredConstraint())
-                    ->getEllipsisLoc()
-              : SourceLocation());
-    }
+    auto Index = TC->getArgumentPackSubstitutionIndex();
+    if (Index == -1)
+      Index = SemaRef.ArgumentPackSubstitutionIndex;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:3167]:
```suggestion
    int Index = TC->getArgumentPackSubstitutionIndex();
    if (Index == -1)
      Index = SemaRef.ArgumentPackSubstitutionIndex;
```

Would we run into an index mismatch here? i.e. `Index != -1 && SemaRef.ArgumentPackSubstitutionIndex != -1 && Index != SemaRef.ArgumentPackSubstitutionIndex`

**Review by zyn0217 — COMMENTED** [review]
Thanks for working on it.

The patch looks good overall, but as you've suggested that this is incomplete, I think we want to go over it again after the cache part gets adapted.

I left a question, for which we probably want an assertion there.

**Review by zyn0217 — COMMENTED** [review]
And, I think this also merits a compile-time regression test - we now hold more bytes when instantiating the constraint

**Comment by mizvekov** [comment]
This is a compile-time improvement overall.

The reverted patch adds a 0.07 cost to stage2-clang, which we avoid with the new approach:
Commit	stage1-O3	stage1-ReleaseThinLTO	stage1-ReleaseLTO-g	stage1-O0-g	stage2-O3	stage2-O0-g	stage2-clang
[9a089c5fbb](https://github.com/llvm/llvm-project/commit/9a089c5fbb4f84da58bca7559f15149b4d3b83d6)	60976M (+0.00%)	77222M (-0.00%)	89531M (-0.01%)	18999M (+0.01%)	53187M (+0.01%)	16612M (-0.02%)	34778529M (+0.01%)
[C](https://llvm-compile-time-tracker.com/compare.php?from=17bbac4d1f447a448168de629f44d8c227d468e5&to=e7ecd60e5fb7a9a14f7d85ab23587faadb543819&stat=instructions:u)		[e7ecd60e5f](https://github.com/llvm/llvm-project/commit/e7ecd60e5fb7a9a14f7d85ab23587faadb543819)	60974M (-0.00%)	77223M (+0.01%)	89537M (+0.01%)	18998M (-0.01%)	53181M (-0.00%)	16615M (+0.01%)	34773327M (-0.07%)
[C](https://llvm-compile-time-tracker.com/compare.php?from=fb44c54d656135a306e403083b5c1eaae9078757&to=17bbac4d1f447a448168de629f44d8c227d468e5&stat=instructions:u)		[17bbac4d1f](https://github.com/llvm/llvm-project/commit/17bbac4d1f447a448168de629f44d8c227d468e5)	60975M (-0.01%)	77211M (-0.01%)	89525M (-0.01%)	19000M (-0.01%)	53184M (-0.03%)	16614M (-0.04%)	34798333M (-0.01%)

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3167]: I am not sure what you mean to see an index mismatch.

If on a first transform pass this is not expanded and we see `ArgumentPackSubstitutionIndex != -1`, then it becomes expanded.

On subsequent patches if we are already expanded, then nothing changes. This works the same way in normal instantiation.

**Comment by mizvekov** [comment]
> The patch looks good overall, but as you've suggested that this is incomplete, I think we want to go over it again after the cache part gets adapted.

My intention is to leave the main branch in a better state, not necessarily to finish everything here in one go.
I think as far as the scope of the changes, this looks good.

File: clang/include/clang/Sema/SemaConcept.h [hunk 2]
```diff
@@ -70,7 +70,14 @@ struct alignas(ConstraintAlignment) AtomicConstraint {
...
     // the originals, and comparing them will suffice.
-    if (ConstraintExpr != Other.ConstraintExpr)
+    if (AC.ConstraintExpr != Other.AC.ConstraintExpr)
+      return false;
+
+    // FIXME: As the normalization cache doesn't take
+    // ArgumentPackSubstitutionIndex into account,
+    // this won't have an effect.
+    if (AC.ArgumentPackSubstitutionIndex !=
+        Other.AC.ArgumentPackSubstitutionIndex)
```
Comment (cor3ntin) [inline clang/include/clang/Sema/SemaConcept.h:80]: Github ate my comment.
This looks wrong. 

An atomic constraint should be considered equivalent to another for the purpose of subsumption if the (transformed) expression is the same, even if it is expanded from a different pack, or not expanded at all.

The only thing we should compare is
 - are they the same expression
 - do they have the same mapping

If the mapping has packs of different sizes etc _that_ should be what makes subsumption fail.

So I would expect `AtomicConstraint` not to change.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3167]: If we see a different value of `ArgumentPackSubstitutionIndex` in a later transform pass, this must be expanding something else, and it doesn't necessarily need to be the same index.

File: clang/include/clang/Sema/SemaConcept.h (hunk 2 above)
Comment (mizvekov) [reply clang/include/clang/Sema/SemaConcept.h:80]: I think in this case the constraint was expanded, the pack index should be part of the mapping.

A different pack index is notionally a different template parameter, or at least another slot where a different template argument could be located, so the different treatment wrt to non-pack parameters doesn't seem consistent to me. 

Though it's possible this doesn't make a difference in practice.
I failed to come up with an example where this would really matter, ie make something ill-formed where it's not, or vice-versa.

**Review by zyn0217 — APPROVED** [review]
LGTM after @cor3ntin 's concerns are resolved

File: clang/include/clang/Sema/SemaConcept.h (hunk 2 above)
Comment (mizvekov) [reply clang/include/clang/Sema/SemaConcept.h:80]: Following the discussion in the reflector: http://lists.isocpp.org/core/2025/03/17677.php
There is agreement, so far, that ignoring the expansion here is wrong.

Comment (cor3ntin) [reply clang/include/clang/Sema/SemaConcept.h:80]: please give me some time to think about it!

Comment (mizvekov) [reply clang/include/clang/Sema/SemaConcept.h:80]: No problem.

Since this patch fixes additional test cases, and it blocks one existing, and one soon to be posted PR, I will back-off this change and leave it for later.

Comment (mizvekov) [reply clang/include/clang/Sema/SemaConcept.h]: Done, this change is backed off for a future PR.

**Comment by mizvekov** [comment]
I have also pushed a follow up to this patch, which extends the same fix for trailing requires clauses.

**Review by erichkeane — COMMENTED** [review]
Ah, looks like thanks to a troublesome github review-nonsense, I already reviewed this.  No real new comments here, so make corentin happy + the few suggestions I made there (re-how they get constructed/etc), and I'm happy here too.

**Comment by mizvekov** [comment]
FYI the part of the PR @cor3ntin had concerns about is not part of this PR anymore.

So after addressing Eric's concerns on this patch I will go ahead and merge.

**Comment by erichkeane** [comment]
> FYI the part of the PR @cor3ntin had concerns about is not part of this PR anymore.
> 
> So after addressing Eric's concerns on this patch I will go ahead and merge.

s/Eric/Erich, else SGTM.

**Review by cor3ntin — APPROVED** [review]
LGTM, Thanks!
