### PR TITLE
[MemCpyOpt] Use `dyn_cast` to fix assertion failure in `processMemCpyMemCpyDependence`

### LINKED ISSUE #935: Update diff July 12th 2024, 3:35:37 pm
from: https://github.com/llvm/llvm-project/commit/7a935089d4593de6767901810594058904412106
to: https://github.com/llvm/llvm-project/commit/216db5e051733cf1c6250310392cbbe9cafce1b5
commit: 78047cfb151fde34c1c6b16074bcae6b2df8f5dd

eastl/TestString.cpp.ll fail
## Change Logs
from 7a935089d4593de6767901810594058904412106 to 216db5e051733cf1c6250310392cbbe9cafce1b5

[216db5e051733cf1c6250310392cbbe9cafce1b5](https://github.com/llvm/llvm-project/commit/216db5e051733cf1c6250310392cbbe9cafce1b5) Fix Findzstd.cmake for compiler-rt with MSVC (#98645)
[da1f491a9d37f549159657ddaba799a7fb39e84a](https://github.com/llvm/llvm-project/commit/da1f491a9d37f549159657ddaba799a7fb39e84a) [LLVM][runtimes] Prepopulate `LLVM_BUILTIN_TARGETS` with runtimes values (#95554)
[fa2421392802025e842454a31ed50dbfab643130](https://github.com/llvm/llvm-project/commit/fa2421392802025e842454a31ed50dbfab643130)  [MemCpyOpt] Forward `memcpy` based on the actual copy memory location. (#87190)
[840e857a1969927f513a17e46445bf9a56cf81ba](https://github.com/llvm/llvm-project/commit/840e857a1969927f513a17e46445bf9a56cf81ba) [libc++] Fix sporadic test failure in condition_variable notify_all test (#97622)
[d873630fda191c327c2762c42186fa142c45934a](https://github.com/llvm/llvm-project/commit/d873630fda191c327c2762c42186fa142c45934a) Revert &quot;[InstCombine] Generalize ptrtoint(gep) fold (NFC)&quot;
[b94c2488f06a5f7692d552e8a5fb85ea0c920a02](https://github.com/llvm/llvm-project/commit/b94c2488f06a5f7692d552e8a5fb85ea0c920a02) [AArch64] Make user-visible Arm architecture version strings consistent (#98550)
[ac2426e08e6f7c1eb97725f1d6cc35a8a6ddc5ef](https://github.com/llvm/llvm-project/commit/ac2426e08e6f7c1eb97725f1d6cc35a8a6ddc5ef) [C2y] Claim conformance to WG14 N3232
[007e32d024f31ef157e3e16117a6c000bfaa2754](https://github.com/llvm/llvm-project/commit/007e32d024f31ef157e3e16117a6c000bfaa2754) [clang][Interp][NFC] Simplify record creation
[01ceb9840a5b768232961444e3606a303ed4beed](https://github.com/llvm/llvm-project/commit/01ceb9840a5b768232961444e3606a303ed4beed) [InstCombine] Fold (zext (X +nuw C)) + -C --&gt; zext(X) when zext has additional use. (#98533)
[98edc0cb1f4ca53bd2d490916566ff7d217110f8](https://github.com/llvm/llvm-project/commit/98edc0cb1f4ca53bd2d490916566ff7d217110f8) [clang][Interp] Fix member pointer temporaries
[c45f939e34dafaf0f57fd1d93df7df5cc89f1dec](https://github.com/llvm/llvm-project/commit/c45f939e34dafaf0f57fd1d93df7df5cc89f1dec) [InstCombine] Generalize ptrtoint(gep) fold (NFC)
[09b1cfceb62332ebf8e5d319ee048492a709995d](https://github.com/llvm/llvm-project/commit/09b1cfceb62332ebf8e5d319ee048492a709995d) [InstCombine] Add additional test case for (add (zext (add nuw X, C2), C1). NFC
[05f987743170cbd9fc97699c7a9b352055de7300](https://github.com/llvm/llvm-project/commit/05f987743170cbd9fc97699c7a9b352055de7300) [X86] Add handling for shift_logical(select(icmp_uge(amt,BW),0,x),amt) -&gt; avx2 shift(x,amt)
[7918e624add98b409332c6996c89a70c74126994](https://github.com/llvm/llvm-project/commit/7918e624add98b409332c6996c89a70c74126994) [libc++] Test suite portability improvements (#98527)
[dd4658f660ad6a9876df1ba375b5d2af5d07b0ad](https://github.com/llvm/llvm-project/commit/dd4658f660ad6a9876df1ba375b5d2af5d07b0ad) [AArch64] Add a few more umull / umaddl test case. NFC
[424ad163c715e478d37cfd1efaae148cdd6aa815](https://github.com/llvm/llvm-project/commit/424ad163c715e478d37cfd1efaae148cdd6aa815) [flang] Simplify LIBTYPE logic (#98072)
[77fd30f7ce0795b4bbc22e65b3ff42856839d708](https://github.com/llvm/llvm-project/commit/77fd30f7ce0795b4bbc22e65b3ff42856839d708) [CUDA][HIP] Fix template static member (#98580)
[e616fa5bc0c628962afec7ee51288b442fbb09d6](https://github.com/llvm/llvm-project/commit/e616fa5bc0c628962afec7ee51288b442fbb09d6) [bazel] Add missing dep for vfprintf_internal

### LINKED ISSUE #98675: [MemCpyOpt] Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Detected by https://github.com/dtcxzyw/llvm-opt-benchmark/issues/935.

Reproducer: 
```
; bin/opt -passes=memcpyopt -S test.ll
@b = external global [32 x i8]

define void @_Z15TestBasicStringIN5eastl12basic_stringIc17CountingAllocatorEEEiv(ptr %call.i.i.i12866) {
  %a = alloca [32 x i8], align 1
  call void @llvm.memcpy.p0.p0.i64(ptr %call.i.i.i12866, ptr @b, i64 26, i1 false)
  %.sroa.gep22184 = getelementptr i8, ptr %call.i.i.i12866, i64 10
  call void @llvm.memmove.p0.p0.i64(ptr %a, ptr %.sroa.gep22184, i64 1, i1 false)
  ret void
}
```
```
opt: /home/dtcxzyw/WorkSpace/Projects/compilers/llvm-project/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From*) [with To = Instruction; From = Value]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bin/opt -passes=memcpyopt reduced.ll
1.      Running pass "function(memcpyopt)" on module "reduced.ll"
2.      Running pass "memcpyopt" on function "_Z15TestBasicStringIN5eastl12basic_stringIc17CountingAllocatorEEEiv"
 #0 0x00007e04ebe0c9c2 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.19.0git+0x20c9c2)
 #1 0x00007e04ebe0988f llvm::sys::RunSignalHandlers() (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.19.0git+0x20988f)
 #2 0x00007e04ebe099d5 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007e04eb842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007e04eb8969fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007e04eb8969fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x00007e04eb8969fc pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x00007e04eb842476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007e04eb8287f3 abort ./stdlib/abort.c:81:7
 #9 0x00007e04eb82871b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x00007e04eb839e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x00007e04e5ab5dfa llvm::MemCpyOptPass::processMemCpyMemCpyDependence(llvm::MemCpyInst*, llvm::MemCpyInst*, llvm::BatchAAResults&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMScalarOpts.so.19.0git+0x2b5dfa)
#12 0x00007e04e5abd2aa llvm::MemCpyOptPass::processMemCpy(llvm::MemCpyInst*, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, false>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMScalarOpts.so.19.0git+0x2bd2aa)
#13 0x00007e04e5abd9c4 llvm::MemCpyOptPass::iterateOnFunction(llvm::Function&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMScalarOpts.so.19.0git+0x2bd9c4)
#14 0x00007e04e5abdcce llvm::MemCpyOptPass::runImpl(llvm::Function&, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::AssumptionCache*, llvm::DominatorTree*, llvm::PostDominatorTree*, llvm::MemorySSA*) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMScalarOpts.so.19.0git+0x2bdcce)
#15 0x00007e04e5abe15c llvm::MemCpyOptPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMScalarOpts.so.19.0git+0x2be15c)
#16 0x00007e04e74cde55 llvm::detail::PassModel<llvm::Function, llvm::MemCpyOptPass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMPasses.so.19.0git+0xcde55)
#17 0x00007e04e474b7b2 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMCore.so.19.0git+0x34b7b2)
#18 0x00007e04eaad5065 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMX86CodeGen.so.19.0git+0xd5065)
#19 0x00007e04e474a40e llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMCore.so.19.0git+0x34a40e)
#20 0x00007e04eaad5985 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMX86CodeGen.so.19.0git+0xd5985)
#21 0x00007e04e47483da llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMCore.so.19.0git+0x3483da)
#22 0x00007e04ec103267 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMOptDriver.so.19.0git+0x2d267)
#23 0x00007e04ec10f212 optMain (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMOptDriver.so.19.0git+0x39212)
#24 0x00007e04eb829d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#25 0x00007e04eb829e40 call_init ./csu/../csu/libc-start.c:128:20
#26 0x00007e04eb829e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#27 0x00005df852081095 _start (bin/opt+0x1095)
Aborted (core dumped)
```

This issue is caused by https://github.com/llvm/llvm-project/commit/fa2421392802025e842454a31ed50dbfab643130.
https://github.com/llvm/llvm-project/blob/d1dc5047f1127d64eb82eec976fabaa2d9d20c11/llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp#L1191-L1192
`Builder.CreateInBoundsPtrAdd` may return `GetElementPtrConstantExpr`.

cc @nikic @DianQK

### PR DESCRIPTION
**Pull request by dtcxzyw**
Fixes https://github.com/llvm/llvm-project/issues/98675.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp [hunk 1]
```diff
@@ -1188,8 +1188,9 @@ bool MemCpyOptPass::processMemCpyMemCpyDependence(MemCpyInst *M,
     if (MDestOffset == MForwardOffset)
       CopySource = M->getDest();
     else {
-      NewCopySource = cast<Instruction>(Builder.CreateInBoundsPtrAdd(
-          CopySource, Builder.getInt64(MForwardOffset)));
+      NewCopySource = GetElementPtrInst::CreateInBounds(
+          Builder.getInt8Ty(), CopySource, Builder.getInt64(MForwardOffset), "",
+          Builder.GetInsertPoint());
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp:1193]: This is going to miss the debug location. I'd prefer to keep IRBuilder and use a dyn_cast. If it's a constant, then there is no need to clean up.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by DianQK** [comment]
Thanks!
