### PR TITLE
[clang][CodeView] Prevent the input name from appearing in LF_BUILDINFO

### LINKED ISSUE #193900: LF_BUILDINFO embeds the source file as a positional cc1 arg when the input path is absolute
Since clang 20, the `LF_BUILDINFO` `CommandLine` field embedded in CodeView debug info contains the source file as a trailing positional `-cc1` argument whenever the source is passed to the driver via an absolute path. Prior to clang 20 the source filename was stripped, regardless of whether the input path was relative or absolute.

This breaks downstream tooling that expects the embedded command to be the cc1 invocation minus the source. Live++ depends on this for its "unity splitting" feature, where it separates out the combined cpp files in a unity/jumbo/amalgamated bucket and compiles each separately. Because of this issue, each split compilation builds both the split cpp file and the entire unity bucket file.

### Cause

https://github.com/llvm/llvm-project/pull/106369 moved the cmd-line flattening for `LF_BUILDINFO` from the LLVM backend into the clang frontend:

* Old, `llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp::flattenCommandLine`:
    ```cpp
    flattenCommandLine(Args, MainSourceFile->getFilename())
    ```
    where `MainSourceFile = CU->getFile()` — the IR `DICompileUnit`'s `DIFile`, which holds the absolute source path that clang resolved.

* New, `clang/lib/CodeGen/BackendUtil.cpp::flattenClangCommandLine`:
    ```cpp
    flattenClangCommandLine(CodeGenOpts.CommandLineArgs, CodeGenOpts.MainFileName)
    ```
    where `CodeGenOpts.MainFileName` comes from the `-main-file-name` flag, which the clang driver sets to the file name without path of the input.

An `if (Arg == MainFilename)` determines whether the argument will be stripped. Because `MainFilename` is now a file name without the path, it doesn't match `Arg` when `Arg` is an absolute path.

### Repro

```cmd
:: clang 22.1.3 (also reproduces on clang 20.x)
> clang-cl /c /Z7 hello.cpp /Fo:rel.obj
> clang-cl /c /Z7 D:\path\to\hello.cpp /Fo:abs.obj
> llvm-readobj --codeview rel.obj | findstr /C:"\"-x\""
> llvm-readobj --codeview abs.obj | findstr /C:"\"-x\""
```

Trailing args of the embedded `LF_BUILDINFO` cmd:
* `rel.obj`: `... "-x" "c++"` -- source stripped (correct)
* `abs.obj`: `... "-x" "c++" "D:\\path\\to\\hello.cpp"`  -- source embedded (regression)

### PR DESCRIPTION
**Pull request by aganea**
The implicit contract of an `LF_BUILDINFO` record (represented in LLVM by [`BuildInfoRecord`](https://github.com/llvm/llvm-project/blob/6f0b55ec55f3e5e1ccc0d6b0d04a307479218768/llvm/include/llvm/DebugInfo/CodeView/TypeRecord.h#L667)) is that its `CommandLine` field should not contain the input source file — a separate `SourceFile` field is reserved for that.

When the command-line flattening was moved from `llvm/` to `clang/` in #106369, the comparison value used to identify and strip the source positional was switched from `MainSourceFile->getFilename()` (the full input path resolved by clang) to `CodeGenOpts.MainFileName` (just the basename, set via `-main-file-name`). As a result, when the driver is invoked with an absolute source path the cc1 positional is that absolute path and no longer matches `MainFileName`, so the source filename leaks into `CommandLine` as a trailing positional cc1 argument.

This is a regression in Clang 20. It breaks downstream tooling such as Live++, whose unity-splitting feature relies on the embedded command line being the cc1 invocation minus the source. Reported in #193900.

This PR restores the previous behavior by passing the resolved frontend input path(s) to `flattenClangCommandLine` and including them in the equality check that strips the source positional. The basename match against `MainFileName` is kept for the relative-input case. A regression test (and a symmetric relative-path test) is added to `clang/test/DebugInfo/Generic/codeview-buildinfo.c`.

Should fix #193900.

### CODE REVIEW

File: clang/test/DebugInfo/Generic/codeview-buildinfo.c [hunk 1]
```diff
@@ -45,3 +57,14 @@ int main(void) { return 42; }
 // MESSAGELEN: ============================================================
 // MESSAGELEN: 0x{{.+}} | LF_BUILDINFO [size = {{.+}}]
 // MESSAGELEN-NOT: -fmessage-length
+
+// The cmdline LF_STRING_ID quotes each cc1 arg, so a leaked source
+// positional appears as a quoted token. The FILEPATH LF_STRING_ID prints
+// the path without surrounding quotes, so it won't trigger the negative.
+// ABSPATH:     0x{{.+}} | LF_STRING_ID [size = {{.+}}] ID: <no type>, String: "-cc1
+// ABSPATH-NOT: "{{[^"]*[\\/]codeview-buildinfo\.c}}"
+// ABSPATH:     0x{{.+}} | LF_BUILDINFO [size = {{.+}}]
```
Comment (Nerixyz) [inline clang/test/DebugInfo/Generic/codeview-buildinfo.c]: Since the command line is always the fifth argument, you should be able to check the command line of `LF_BUILDINFO` too. Something like
```cpp
// ABSPATH:     0x{{.+}} | LF_BUILDINFO [size = {{.+}}]
// ABSPATH-NEXT:          0x{{.*}}: `{{.*}}`
// ABSPATH-NEXT:          0x{{.*}}: `{{.*}}`
// ABSPATH-NEXT:          0x{{.*}}: `{{.*}}`
// ABSPATH-NEXT:          0x{{.*}}: ``
// ABSPATH-NEXT:          0x{{.*}}: `
// ABSPATH-NOT: {{[^"]*[\\/]codeview-buildinfo\.c}}
// ABSPATH-SAME: `
```

Comment (aganea) [reply clang/test/DebugInfo/Generic/codeview-buildinfo.c]: As suggested.

**Review by zmodem — APPROVED** [review]
lgtm

**Review by Nerixyz — APPROVED** [review]
