### PR TITLE
[clang] Consistently handle consteval constructors for variables.

### LINKED ISSUE #135281: `consteval` constructor cannot store `this` inside object
Unlike GCC & MSVC, Clang refuses to compile this https://godbolt.org/z/WYr58Ge9s --

```cpp
struct B {
  const void* immortal_;
  consteval B() : immortal_{this} {}
};
constexpr static B b;
```

The error suggests that the frontend wrongly thinks that `this` is a pointer to a temporary:

```
<source>:6:20: error: call to consteval function 'B::B' is not a constant expression
    6 | constexpr static B b;
      |                    ^
<source>:6:20: note: pointer to temporary is not a constant expression
<source>:6:20: note: temporary created here
```

### PR DESCRIPTION
**Pull request by efriedma-quic**
443377a9d1a8d4a69a317a1a892184c59dd0aec6 handled simple variable definitions, but it didn't handle uninitialized variables with a consteval constructor, and it didn't handle template instantiation.

Fixes #135281 .

### CODE REVIEW

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -14423,6 +14423,9 @@ void Sema::ActOnUninitializedDecl(Decl *RealDecl) {
         Var->getType().getAddressSpace() == LangAS::hlsl_input)
       return;
 
+    if (getLangOpts().CPlusPlus)
+      ActOnCXXEnterDeclInitializer(nullptr, Var);
```
Comment (vgvassilev) [inline clang/lib/Sema/SemaDecl.cpp]:
```suggestion
      ActOnCXXEnterDeclInitializer(/*Scope=*/nullptr, Var);
```

File: clang/lib/Sema/SemaDecl.cpp [hunk 2]
```diff
@@ -14458,6 +14461,9 @@ void Sema::ActOnUninitializedDecl(Decl *RealDecl) {
     }
 
     CheckCompleteVariableDeclaration(Var);
+
+    if (getLangOpts().CPlusPlus)
+      ActOnCXXExitDeclInitializer(nullptr, Var);
```
Comment (vgvassilev) [inline clang/lib/Sema/SemaDecl.cpp]:
```suggestion
      ActOnCXXExitDeclInitializer(/*Scope=*/nullptr, Var);
```

**Review by vgvassilev — COMMENTED** [review]
LGTM!

**Review by shafik — COMMENTED** [review]
I am a little suspicious of this change because right now we are only calling `ActOnCXXExitDeclInitializer` in `~InitializerScopeRAII()` and now it seems like we need to sprinkle it in other places.

**Comment by efriedma-quic** [comment]
ActOnCXXExitDeclInitializer does three things:

- Some scope handling which isn't relevant in this context.
- Does some special handling for variables, to compute whether the variable's initializer is manifestly constant-evaluated.
- Calls PopExpressionEvaluationContext

The special handling for variables is specifically relevant for variables... I don't see why we'd need it anywhere else? Except, hmm... I guess we need the same handling if we're instantiating a template, like:

```
struct B {
  const void* p;
  consteval B() : p{this} {}
};
template<typename T> T x{};
B* y = &x<B>;
```

But I can't think of anything else.

Any suggestions for how to refactor?

**Comment by efriedma-quic** [comment]
Came up with a different approach: I moved the check to PopExpressionEvaluationContext().  This required annotating the ExpressionEvaluationContextRecord to indicate we're handling a variable initializer.

**Review by cor3ntin — APPROVED** [review]
Can you add a changelog entry? LGTM otherwiswe
