### PR TITLE
[lldb-dap] Add 'source' references to stack frames without source files.

### LINKED ISSUE #128260: [lldb-dap] Stepping into a frame without sources can be frustrating
When debugging with `lldb-dap` if you have a stack frame without a source reference we currently do not provide a 'source' for the frame. This makes selecting the frame a bit awkward. If you right click on the frame and select 'Open Disassembly View' you do get the VS Code built-in disassembly viewer and then when you select a frame things start to work as you might to expect. 

However, VS Code will not automatically open the disassembly view, which can lead to some unexpected behaviors when you try to step or navigate the stack frames.

I think it would be worth while to bring back the old behavior of returning a disassembly view of those frames again.

### PR DESCRIPTION
**Pull request by ashgti**
This adds 'source' references to all stack frames. When opening a stack frame users will see the disassembly of the frame if the source is not available.

This works around the odd behavior of navigating frames without the VSCode disassembly view open, which causes 'step' to step in the first frame with a source instead of the active frame.

This fixes #128260

Old behavior:
https://github.com/user-attachments/assets/3f40582d-ac96-451a-a5ae-498a323bf30e

New behavior:
https://github.com/user-attachments/assets/3a3f9ac6-3e6c-4795-9bb2-1132b3916b6f

### CODE REVIEW

File: lldb/tools/lldb-dap/JSONUtils.cpp [hunk 1]
```diff
@@ -799,21 +806,22 @@ llvm::json::Value CreateStackFrame(lldb::SBFrame &frame,
...
     auto column = line_entry.GetColumn();
     object.try_emplace("column", column);
   } else {
-    object.try_emplace("line", 0);
-    object.try_emplace("column", 0);
+    lldb::addr_t inst_offset = frame.GetPCAddress().GetOffset() -
+                               frame.GetSymbol().GetStartAddress().GetOffset();
+    lldb::addr_t inst_line =
+        inst_offset / (frame.GetThread().GetProcess().GetAddressByteSize() / 2);
+    // lines are base-1 indexed
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/JSONUtils.cpp:822]:
```suggestion
    // Line numbers are 1-based. 
```

File: lldb/tools/lldb-dap/JSONUtils.cpp [hunk 2]
```diff
@@ -698,14 +697,22 @@ llvm::json::Value CreateSource(llvm::StringRef source_path) {
   return llvm::json::Value(std::move(source));
 }
 
-static std::optional<llvm::json::Value> CreateSource(lldb::SBFrame &frame) {
+static llvm::json::Value CreateSource(lldb::SBFrame &frame,
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/JSONUtils.cpp:700]: I assume this function is used elsewhere? The line number and column have a different meaning based on whether we have source info and having the logic spread across this function and `CreateStackFrame` seems like a pretty big foot gun. Any chance we can localize this logic?

**Review by JDevlieghere — COMMENTED** [review]
This will need a test.

File: lldb/tools/lldb-dap/JSONUtils.cpp (hunk 2 above)
Comment (ashgti) [reply lldb/tools/lldb-dap/JSONUtils.cpp]: Merged this into the only place that called the helper (`CreateStackFrame`) to make sure its more clear.

**Comment by labath** [comment]
Could we make the test self contained (i.e. without the qsort reference)? If all you need is a function without debug info, then `__attribute__((nodebug))` should suffice.

**Comment by ashgti** [comment]
> Could we make the test self contained (i.e. without the qsort reference)? If all you need is a function without debug info, then `__attribute__((nodebug))` should suffice.

Thanks for the suggestion! That works a lot more consistently than depending on the implementation details of libc's qsort.

File: lldb/tools/lldb-dap/JSONUtils.cpp [hunk 3]
```diff
@@ -799,21 +788,40 @@ llvm::json::Value CreateStackFrame(lldb::SBFrame &frame,
...
+    // the 'source' and generate assembly.
+    llvm::json::Object source;
+    EmplaceSafeString(source, "name", frame_name);
+    char buf[PATH_MAX] = {0};
+    size_t size = frame.GetModule().GetFileSpec().GetPath(buf, PATH_MAX);
+    EmplaceSafeString(source, "path",
+                      std::string(buf, size) + '`' + frame_name);
+    source.try_emplace("sourceReference", MakeDAPFrameID(frame));
+    // Markthe source as deemphasized since users will only be able to view
+    // assembly for these frames.
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/JSONUtils.cpp:812]:
```suggestion
    // Mark the source as deemphasized since users will only be able to view
    // assembly for these frames.
```

**Review by JDevlieghere — APPROVED** [review]
LGTM!

**Comment by ashgti** [comment]
Pulled and rebased my changes on the request handler refactor.

**Comment by JDevlieghere** [comment]
Totally optional & I didn't think about it earlier, but this seems like something you might want to advertise through a release note.
