### PR TITLE
[Clang][Sema] Skip checking anonymous enum in using enum declaration

### LINKED ISSUE #86790: using enum declaration with anonymous enum crashes clang frontend
Minimal example:
```
enum {A, S, D, F}; // the enum is in an outer scope to avoid name collisions. This seems unrelated to the bug.
// enum Asdf {A, S, D, F}; // naming the enum prevents the crash
int main()
{
    using asdf = decltype(A);
    using enum asdf; // this line causes the crash
    return 0;
}
```
Needs additional clang command line argument "-std=c++20" (or later) to support using-enum-declarations.
The gcc compiler compiles this code without any problems.
Downloaded compilers from https://winlibs.com/
exact file download link: https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-ucrt-r5/winlibs-x86_64-posix-seh-gcc-13.1.0-llvm-16.0.5-mingw-w64ucrt-11.0.0-r5.zip
OS: Windows

Expected behavior: the code should compile.

Observed behavior: clang frontend crashes with the following error message:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:/Users/svetlin.totev/libs/mingw64/bin/clang.exe -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=C:/Users/svetlin.totev/Documents/test -resource-dir C:/Users/svetlin.totev/libs/mingw64/lib/clang/16 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++ -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++ -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13/x86_64-w64-mingw32 -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13/backward -internal-isystem C:/Users/svetlin.totev/libs/mingw64/lib/clang/16/include -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include -internal-isystem C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/usr/include -internal-isystem C:/Users/svetlin.totev/libs/mingw64/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=C:/Users/svetlin.totev/Documents/test -ferror-limit 19 -fmessage-length=208 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -exception-model=seh -fcolor-diagnostics -faddrsig -o C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-6235c7.o -x c++ test.cpp
1.      test.cpp:6:20: current parser token ';'
2.      test.cpp:4:1: parsing function body 'main'
3.      test.cpp:4:1: in compound statement ('{}')
Exception Code: 0xC0000005
 #0 0x00007ffc8f81c940 clang::DeclarationName::getFETokenInfo() const (C:\Users\svetlin.totev\libs\mingw64\bin\libclangSema.dll+0x55c940)
 #1 0x00007ffc8f5921ae clang::IdentifierResolver::begin(clang::DeclarationName) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangSema.dll+0x2d21ae)
 #2 0x00007ffc8f68d0e4 clang::Sema::PushOnScopeChains(clang::NamedDecl*, clang::Scope*, bool) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangSema.dll+0x3cd0e4)
 #3 0x00007ffc8f739dd8 clang::Sema::ActOnUsingEnumDeclaration(clang::Scope*, clang::AccessSpecifier, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo&, clang::CXXScopeSpec*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangSema.dll+0x479dd8)
 #4 0x00007ffce334d0af clang::Parser::ParseUsingDeclaration(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::SourceLocation, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x3d0af)
 #5 0x00007ffce338040d clang::Parser::ParseUsingDirectiveOrDeclaration(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::SourceLocation&, clang::ParsedAttributes&) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x7040d)
 #6 0x00007ffce332ce33 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x1ce33)
 #7 0x00007ffce338ea4e clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x7ea4e)
 #8 0x00007ffce3370d8c clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x60d8c)
 #9 0x00007ffce3362e8e clang::Parser::ParseCompoundStatementBody(bool) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x52e8e)
#10 0x00007ffce3366709 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x56709)
#11 0x00007ffce3354dd9 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x44dd9)
#12 0x00007ffce3328f35 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x18f35)
#13 0x00007ffce3378243 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x68243)
#14 0x00007ffce33861a2 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x761a2)
#15 0x00007ffce3359d76 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x49d76) 
#16 0x00007ffce3332963 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x22963)
#17 0x00007ffce33934b0 clang::ParseAST(clang::Sema&, bool, bool) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangParse.dll+0x834b0)
#18 0x00007ffce46caa52 clang::FrontendAction::Execute() (C:\Users\svetlin.totev\libs\mingw64\bin\libclangFrontend.dll+0x4aa52)
#19 0x00007ffce46d051c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangFrontend.dll+0x5051c)
#20 0x00007ffd25b739dd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (C:\Users\svetlin.totev\libs\mingw64\bin\libclangFrontendTool.dll+0x39dd)
#21 0x00007ff74529ac56 (C:\Users\svetlin.totev\libs\mingw64\bin\clang.exe+0xac56)
#22 0x00007ff74529b385 (C:\Users\svetlin.totev\libs\mingw64\bin\clang.exe+0xb385)
#23 0x00007ff745296db6 (C:\Users\svetlin.totev\libs\mingw64\bin\clang.exe+0x6db6)
#24 0x00007ff7452912ee (C:\Users\svetlin.totev\libs\mingw64\bin\clang.exe+0x12ee)
#25 0x00007ff745291406 (C:\Users\svetlin.totev\libs\mingw64\bin\clang.exe+0x1406)
#26 0x00007ffd2d1d257d (C:\Windows\System32\KERNEL32.DLL+0x1257d)
#27 0x00007ffd2dbeaa58 (C:\Windows\SYSTEM32\ntdll.dll+0x5aa58)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
(built by Brecht Sanders) clang version 16.0.5
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/Users/svetlin.totev/libs/mingw64/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-0047ff.cpp
clang: note: diagnostic msg: C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-0047ff.sh
clang: note: diagnostic msg:

********************
```
The files mentioned in the error message:
C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-0047ff.cpp:
```
# 1 "test.cpp"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 459 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "test.cpp" 2
enum {A, S, D, F};

int main()
{
    using asdf = decltype(A);
    using enum asdf;
    return 0;
}

```
C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-0047ff.sh:
```
# Crash reproducer for (built by Brecht Sanders) clang version 16.0.5
# Driver args: "test.cpp" "-o" "text.exe" "-std=c++20"
# Original command:  "C:/Users/svetlin.totev/libs/mingw64/bin/clang.exe" "-cc1" "-triple" "x86_64-w64-windows-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-mms-bitfields" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=C:/Users/svetlin.totev/Documents/test" "-resource-dir" "C:/Users/svetlin.totev/libs/mingw64/lib/clang/16" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include/c++/13.1.0/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/include/c++/13.1.0/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1.0/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13.1/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13/x86_64-w64-mingw32" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/g++-v13/backward" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/lib/clang/16/include" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/include" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/x86_64-w64-mingw32/usr/include" "-internal-isystem" "C:/Users/svetlin.totev/libs/mingw64/include" "-std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir=C:/Users/svetlin.totev/Documents/test" "-ferror-limit" "19" "-fmessage-length=208" "-fno-use-cxa-atexit" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-exception-model=seh" "-fcolor-diagnostics" "-faddrsig" "-o" "C:/Users/SVETLI~1.TOT/AppData/Local/Temp/test-6235c7.o" "-x" "c++" "test.cpp"
 "C:/Users/svetlin.totev/libs/mingw64/bin/clang.exe" "-cc1" "-triple" "x86_64-w64-windows-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-mms-bitfields" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=C:/Users/svetlin.totev/Documents/test" "-std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir=C:/Users/svetlin.totev/Documents/test" "-ferror-limit" "19" "-fmessage-length=208" "-fno-use-cxa-atexit" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-exception-model=seh" "-fcolor-diagnostics" "-faddrsig" "-x" "c++" "test-0047ff.cpp"

```

### PR DESCRIPTION
**Pull request by jcsxky**
Try to fix https://github.com/llvm/llvm-project/issues/86790
`getFETokenInfo` requires `DeclarationName` shouldn't be empty and this will produce crash when checking name conflict of an anonymous `NamedDecl` in `Sema::PushOnScopeChains` and whether it's a reserved identifier or not. These wouldn't happen when it's a anonymous enum and we can skip the checking and just add the declaration to current scope.

### CODE REVIEW

File: clang/test/SemaCXX/PR86790.cpp [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %clang_cc1 -verify -std=c++20 -fsyntax-only %s
+// expected-no-diagnostics
+
+enum {A, S, D, F};
+int main() {
+    using asdf = decltype(A);
+    using enum asdf; // this line causes the crash
+    return 0;
+}
```
Comment (AaronBallman) [inline clang/test/SemaCXX/PR86790.cpp:9]: I'd like to see an additional test case demonstrating that we correctly added the enumerators to the correct scope:
```
enum {A, S, D, F};
constexpr struct T {
  using asdf = decltype(A);
  using enum asdf;
} t;

static_assert(t.D == D);
static_assert(T::S == S);
```
and
```
enum {A, S, D, F};
constexpr struct T {
  struct {
    using asdf = decltype(A);
    using enum asdf;
  } inner;
} t;

static_assert(t.inner.D == D);
static_assert(t.D == D); // expected-error
```

**Review by AaronBallman — APPROVED** [review]
Thank you! LGTM aside from expanding the testing a bit.

**Review by shafik — COMMENTED** [review]
LGTM after addressing Aaron's comments.

Can you elaborate more on the details of the bug in the summary. This goes into the git log and we want folks to be able to understand the problem well from the summary w/o having to do additional checks.

Thank you

**Comment by jcsxky** [comment]
> LGTM after addressing Aaron's comments.
> 
> Can you elaborate more on the details of the bug in the summary. This goes into the git log and we want folks to be able to understand the problem well from the summary w/o having to do additional checks.
> 
> Thank you

Added.

File: clang/test/SemaCXX/PR86790.cpp (hunk 1 above)
Comment (jcsxky) [reply clang/test/SemaCXX/PR86790.cpp:8]: Thanks for your review and testcase. This makes the fix complete. Code has been updated with the new added testcase.

File: clang/lib/Sema/SemaDecl.cpp [hunk 2]
```diff
@@ -1537,6 +1537,10 @@ void Sema::PushOnScopeChains(NamedDecl *D, Scope *S, bool AddToContext) {
       cast<FunctionDecl>(D)->isFunctionTemplateSpecialization())
     return;
 
+  if (isa<UsingEnumDecl>(D) && D->getDeclName().isEmpty()) {
```
Comment (zygoloid) [inline clang/lib/Sema/SemaDecl.cpp:1540]: Why do we push a `UsingEnumDecl` into the scope at all? Would it make sense for the caller to just add the declaration to the `DeclContext` instead of calling `PushOnScopeChains`?

Comment (jcsxky) [reply clang/lib/Sema/SemaDecl.cpp:1540]: `Sema::ActOnUsingEnumDeclaration` invoke `PushOnScopeChains` when `D` is a `UsingEnumDecl` (anonymous or not) and do some extra works.  Just add the declaration would skip checking even it's not anonymous.

Comment (zygoloid) [reply clang/lib/Sema/SemaDecl.cpp:1540]: Are those useful checks? It seems surprising to me that we'd push a `using enum` declaration into scope given that it never introduces any name of its own (the enumerators are handled separately). Are we really performing checks here that we need for a named enum but that are wrong pr unnecessary for an anonymous enum?

Comment (jcsxky) [reply clang/lib/Sema/SemaDecl.cpp:1540]: These checks include name conflict and reserved identifier or not. From this perspective I think it's required here. It will take some time to attempt to skip calling `PushOnScopeChains` and run unittest to find failed cases.

Comment (zygoloid) [reply clang/lib/Sema/SemaDecl.cpp:1540]: For what name? The `using enum` declaration doesn't introduce the name of the enum.

Comment (jcsxky) [reply clang/lib/Sema/SemaDecl.cpp:1540]: Ah, I see. I skip those checking when `D` is `using enum`(`UsingEnumDecl`) by adding
```cpp
if (isa<UsingEnumDecl>(D))
    return;
```
at https://github.com/llvm/llvm-project/blob/cebf77fb936a7270c7e3fa5c4a7e76216321d385/clang/lib/Sema/SemaDecl.cpp#L1529 and it makes sense after runing unit test on `check-clang` locally. Then I think you are right.

**Comment by vabridgers** [comment]
This change has caused a regression in one of our systems integration tests that test static analysis for the bstring lib project (https://github.com/websnarf/bstrlib) with cross translation unit analysis enabled. Unfortunately I do not have a simple reproducer that stands alone just using clang, but I do have a reproducer that uses CodeChecker and can paste in the crash signature here. Please consider reverting the change until a proper fix can be made and this issue is addressed. 

bstrwrap.cpp
  1 #include "bstrwrap.h"
  2 #include <iostream>
  3
  4 Bstrlib::CBString::CBString () {
  5 } 

bstrwrap.h
  1 #include <string>
  2
  3 namespace Bstrlib {
  4 struct CBString {  
  5    CBString ();
  6 };
  7
  8 extern std::istream& getline (std::istream& sin, CBString& b, char terminator='\n');
  9
 10 } // namespace Bstrlib


test.cpp
  1 #include "bstrwrap.h"
  2
  3 int test0 (void) {
  4   Bstrlib::CBString c0;
  5   return 0;
  6 }

Using CodeChecker from https://github.com/Ericsson/codechecker, Log the build

``CodeChecker log -b "g++ -c test.cpp bstrwrap.cpp" -o comp.json``

Repro step

``env PATH=<UpstreamCompilerPath>:$PATH CC_ANALYZERS_FROM_PATH=1 CodeChecker analyze comp.json  --clean  --ctu -o report --analyzers clangsa``

The crash signature, appears to be crashing in AST Import. 
1.      <eof> parser at end of file
2.      While analyzing stack:
        #0 Calling test0()
3.      test.cpp:4:21: Error evaluating statement
4.      test.cpp:4:21: Error evaluating statement
 #0 0x0000000003cb7248 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (clang-19+0x3cb7248)
 #1 0x0000000003cb4f2c llvm::sys::CleanupOnSignal(unsigned long) (clang-19+0x3cb4f2c)
 #2 0x0000000003bfd308 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f9e5d53d630 __restore_rt sigaction.c:0:0
 #4 0x00007f9e5af39387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f9e5af3aa78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f9e5af321a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f9e5af32252 (/lib64/libc.so.6+0x2f252)
 #8 0x00000000072ada26 clang::FunctionDecl::setDescribedFunctionTemplate(clang::FunctionTemplateDecl*) (clang-19+0x72ada26)
 #9 0x0000000007190a56 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) (clang-19+0x7190a56)
#10 0x000000000716e998 clang::declvisitor::Base<std::add_pointer, clang::ASTNodeImporter, llvm::Expected<clang::Decl*>>::Visit(clang::Decl*) crtstuff.c:0:0
#11 0x000000000716eedb clang::ASTImporter::Import(clang::Decl*) (clang-19+0x716eedb)
#12 0x0000000007172108 std::conditional<is_base_of_v<clang::Type, clang::Decl>, llvm::Expected<clang::Decl const*>, llvm::Expected<clang::Decl*>>::type clang::ASTNodeImporter::import<clang::Decl>(clang::Decl*) crtstuff.c:0:0
#13 0x000000000717d072 clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool) (clang-19+0x717d072)
#14 0x000000000718677b clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) (clang-19+0x718677b)
#15 0x000000000716ea38 clang::declvisitor::Base<std::add_pointer, clang::ASTNodeImporter, llvm::Expected<clang::Decl*>>::Visit(clang::Decl*) crtstuff.c:0:0
#16 0x000000000716eedb clang::ASTImporter::Import(clang::Decl*) (clang-19+0x716eedb)
#17 0x0000000007175146 clang::ASTImporter::Import(clang::NestedNameSpecifier*) (clang-19+0x7175146)
#18 0x000000000717a0bb clang::ASTNodeImporter::VisitElaboratedType(clang::ElaboratedType const*) (clang-19+0x717a0bb)
#19 0x0000000007174945 clang::TypeVisitor<clang::ASTNodeImporter, llvm::Expected<clang::QualType>>::Visit(clang::Type const*) crtstuff.c:0:0
#20 0x0000000007174c07 clang::ASTImporter::Import(clang::Type const*) (clang-19+0x7174c07)
#21 0x0000000007175bd7 clang::ASTImporter::Import(clang::QualType) (clang-19+0x7175bd7)
#22 0x0000000007177e20 clang::ASTNodeImporter::VisitLValueReferenceType(clang::LValueReferenceType const*) (clang-19+0x7177e20)

**Comment by vabridgers** [comment]
@dkrupp , @balazske

**Comment by jcsxky** [comment]
> This change has caused a regression in one of our systems integration tests that test static analysis for the bstring lib project (https://github.com/websnarf/bstrlib) with cross translation unit analysis enabled. Unfortunately I do not have a simple reproducer that stands alone just using clang, but I do have a reproducer that uses CodeChecker and can paste in the crash signature here. Please consider reverting the change until a proper fix can be made and this issue is addressed.
> 
> ```
> bstrwrap.cpp
>   1 #include "bstrwrap.h"
>   2 #include <iostream>
>   3
>   4 Bstrlib::CBString::CBString () {
>   5 } 
> 
> bstrwrap.h
>   1 #include <string>
>   2
>   3 namespace Bstrlib {
>   4 struct CBString {  
>   5    CBString ();
>   6 };
>   7
>   8 extern std::istream& getline (std::istream& sin, CBString& b, char terminator='\n');
>   9
>  10 } // namespace Bstrlib
> 
> 
> test.cpp
>   1 #include "bstrwrap.h"
>   2
>   3 int test0 (void) {
>   4   Bstrlib::CBString c0;
>   5   return 0;
>   6 }
> ```
> 
> Using CodeChecker from https://github.com/Ericsson/codechecker, Log the build
> 
> `CodeChecker log -b "g++ -c test.cpp bstrwrap.cpp" -o comp.json`
> 
> Repro step
> 
> ```
> ``env PATH=<UpstreamCompilerPath>:$PATH CC_ANALYZERS_FROM_PATH=1 CodeChecker analyze comp.json  --clean  --ctu -o report --analyzers clangsa``
> ```
> 
> The crash signature, appears to be crashing in AST Import.
> 
> ```
> 1.      <eof> parser at end of file
> 2.      While analyzing stack:
>         #0 Calling test0()
> 3.      test.cpp:4:21: Error evaluating statement
> 4.      test.cpp:4:21: Error evaluating statement
>  #0 0x0000000003cb7248 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (clang-19+0x3cb7248)
>  #1 0x0000000003cb4f2c llvm::sys::CleanupOnSignal(unsigned long) (clang-19+0x3cb4f2c)
>  #2 0x0000000003bfd308 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
>  #3 0x00007f9e5d53d630 __restore_rt sigaction.c:0:0
>  #4 0x00007f9e5af39387 raise (/lib64/libc.so.6+0x36387)
>  #5 0x00007f9e5af3aa78 abort (/lib64/libc.so.6+0x37a78)
>  #6 0x00007f9e5af321a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
>  #7 0x00007f9e5af32252 (/lib64/libc.so.6+0x2f252)
>  #8 0x00000000072ada26 clang::FunctionDecl::setDescribedFunctionTemplate(clang::FunctionTemplateDecl*) (clang-19+0x72ada26)
>  #9 0x0000000007190a56 clang::ASTNodeImporter::VisitFunctionTemplateDecl(clang::FunctionTemplateDecl*) (clang-19+0x7190a56)
> #10 0x000000000716e998 clang::declvisitor::Base<std::add_pointer, clang::ASTNodeImporter, llvm::Expected<clang::Decl*>>::Visit(clang::Decl*) crtstuff.c:0:0
> #11 0x000000000716eedb clang::ASTImporter::Import(clang::Decl*) (clang-19+0x716eedb)
> #12 0x0000000007172108 std::conditional<is_base_of_v<clang::Type, clang::Decl>, llvm::Expected<clang::Decl const*>, llvm::Expected<clang::Decl*>>::type clang::ASTNodeImporter::import<clang::Decl>(clang::Decl*) crtstuff.c:0:0
> #13 0x000000000717d072 clang::ASTNodeImporter::ImportDeclContext(clang::DeclContext*, bool) (clang-19+0x717d072)
> #14 0x000000000718677b clang::ASTNodeImporter::VisitNamespaceDecl(clang::NamespaceDecl*) (clang-19+0x718677b)
> #15 0x000000000716ea38 clang::declvisitor::Base<std::add_pointer, clang::ASTNodeImporter, llvm::Expected<clang::Decl*>>::Visit(clang::Decl*) crtstuff.c:0:0
> #16 0x000000000716eedb clang::ASTImporter::Import(clang::Decl*) (clang-19+0x716eedb)
> #17 0x0000000007175146 clang::ASTImporter::Import(clang::NestedNameSpecifier*) (clang-19+0x7175146)
> #18 0x000000000717a0bb clang::ASTNodeImporter::VisitElaboratedType(clang::ElaboratedType const*) (clang-19+0x717a0bb)
> #19 0x0000000007174945 clang::TypeVisitor<clang::ASTNodeImporter, llvm::Expected<clang::QualType>>::Visit(clang::Type const*) crtstuff.c:0:0
> #20 0x0000000007174c07 clang::ASTImporter::Import(clang::Type const*) (clang-19+0x7174c07)
> #21 0x0000000007175bd7 clang::ASTImporter::Import(clang::QualType) (clang-19+0x7175bd7)
> #22 0x0000000007177e20 clang::ASTNodeImporter::VisitLValueReferenceType(clang::LValueReferenceType const*) (clang-19+0x7177e20)
> ```

Looks like ASTImporter issue. Could you please provider a reproducer using clang only? That would be better to catch the issue. Just reverting this patch may not crash any more, but it would lead to incorrect AST be imported and influenced the accuracy of static analysis.

**Comment by vabridgers** [comment]
Hello @jcsxky , here's a simplified reproducer that drives the crash from a shell script. All you need to do is make sure your clang build is in the path. I repro'd this on a RHEL7 host, just in case that details matters (but I don't think it will). 

This script echos the simplified source files and the accompanying externalDefMap.txt needed to drive a CTU analysis. 

# remove, regen the ctu directory and externalDefMap.txt file. This file corresponds to 
# to the subsequently generated header and source files and is provided for simplicity of crash repro
rm -rf ctudir
mkdir ctudir
touch ctudir/externalDefMap.txt
echo '11:c:@F@test0# test.cpp.ast' >> ctudir/externalDefMap.txt
echo '35:c:@N@Bstrlib@S@CBString@F@CBString# bstrwrap.cpp.ast' >> ctudir/externalDefMap.txt

# remove, regen the cpp file
rm -rf test.cpp
echo '#include "bstrwrap.h"' >> test.cpp
echo 'int test0 (void) {' >> test.cpp
echo '  Bstrlib::CBString c0;' >> test.cpp
echo '  return 0;' >> test.cpp
echo '}' >> test.cpp

# remove, regen the cpp file
rm -rf bstrwrap.cpp
echo '#include "bstrwrap.h"' >> bstrwrap.cpp
echo '#include <iostream>' >> bstrwrap.cpp
echo 'Bstrlib::CBString::CBString () {' >> bstrwrap.cpp
echo '}' >> bstrwrap.cpp

# remove, regen the header file
rm -rf bstrwrap.h
echo '#include <string>' >> bstrwrap.h
echo 'namespace Bstrlib {' >> bstrwrap.h
echo 'struct CBString  {' >> bstrwrap.h
echo '  CBString ();' >> bstrwrap.h
echo '};' >> bstrwrap.h
echo 'extern std::istream& getline (void);' >> bstrwrap.h
echo '}' >> bstrwrap.h

# generate the ASTs
clang bstrwrap.cpp -emit-ast -D__clang_analyzer__ -w -o ctudir/bstrwrap.cpp.ast
clang test.cpp -emit-ast -D__clang_analyzer__ -w -o ctudir/test.cpp.ast
# drive the analysis exposing the AST import crash
#clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir -Xclang -analyzer-config -Xclang display-ctu-progress=true test.cpp
clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir test.cpp

**Comment by jcsxky** [comment]
```cpp
ls
bstrwrap.cpp  bstrwrap.h  ctudir  test.cpp  test.plist  test.sh

cat bstrwrap.cpp
#include "bstrwrap.h"
#include <iostream>
Bstrlib::CBString::CBString () {
}

cat bstrwrap.h
#include <string>
namespace Bstrlib {
struct CBString {
 CBString ();
};
extern std::istream& getline (void);
}

cat test.cpp
#include "bstrwrap.h"
int test0 (void) {
 Bstrlib::CBString c0;
 return 0;
}

cat ctudir/externalDefMap.txt 
11:c:@f@test0# test.cpp.ast
35:c:@n@Bstrlib@S@CBString@F@CBString# bstrwrap.cpp.ast

~/llvm-project/build/bin/clang test.cpp -emit-ast -D__clang_analyzer__ -w -o ctudir/test.cpp.ast
~/llvm-project/build/bin/clang bstrwrap.cpp -emit-ast -D__clang_analyzer__ -w -o ctudir/bstrwrap.cpp.ast
~/llvm-project/build/bin/clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir -Xclang -analyzer-config -Xclang display-ctu-progress=true test.cpp
```
I have tested locally using main branch with clang and it has no crash. Maybe I missed something? Could you please take a second look? @vabridgers

**Comment by vabridgers** [comment]
Hi @jcsxky , I fetched and rebased to origin/main just now (6/16/2024 at 4:30pm Central US time), and rebuilt - and I see the crash. Did you try rebasing to latest source and rebuilding?

`$ clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir -Xclang -analyzer-config -Xclang display-ctu-progress=true test.cpp`
`CTU loaded AST file: bstrwrap.cpp.ast`
`clang: clang/lib/AST/Decl.cpp:4045: void clang::FunctionDecl::setDescribedFunctionTemplate(clang::FunctionTemplateDecl*): Assertion `TemplateOrSpecialization.isNull() && "Member function is already a specialization"' failed.`
`PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.`
`Stack dump:`
`0.      Program arguments: clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir -Xclang -analyzer-config -Xclang display-ctu-progress=true test.cpp`
`1.      <eof> parser at end of file`
`2.      While analyzing stack:`
`        #0 Calling test0()`
`3.      test.cpp:3:21: Error evaluating statement`
`4.      test.cpp:3:21: Error evaluating statement`
`  #0 0x000000000683ef4a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm/lib/Support/Unix/Signals.inc:723:22`
`  #1 0x000000000683f384 PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:798:1`
`  #2 0x000000000683cc9d llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:105:20`
`  #3 0x000000000683e84b llvm::sys::CleanupOnSignal(unsgned long) llvm/lib/Support/Unix/Signals.inc:367:31`
`  #4 0x000000000677a190 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) llvm/lib/Support/CrashRecoveryContext.cpp:73:5`
`  #5 0x000000000677a623 CrashRecoverySignalHandler(int) llvm/lib/Support/CrashRecoveryContext.cpp:391:1`
`  #6 0x00007fbb10acd630 __restore_rt sigaction.c:0:0`
`  #7 0x00007fbb0f80b387 raise (/lib64/libc.so.6+0x36387)`
`  #8 0x00007fbb0f80ca78 abort (/lib64/libc.so.6+0x37a78)`
`  #9 0x00007fbb0f8041a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)`
` #10 0x00007fbb0f804252 (/lib64/libc.so.6+0x2f252)`
` #11 0x000000000c2b9f73 clang::FunctionDecl::setDescribedFunctionTemplate(clang::FunctionTemplateDecl*) clang/lib/AST/Decl.cpp:4045:3`

**Comment by jcsxky** [comment]
> Hi @jcsxky , I fetched and rebased to origin/main just now (6/16/2024 at 4:30pm Central US time), and rebuilt - and I see the crash. Did you try rebasing to latest source and rebuilding?
> 
> `$ clang --analyze -Xclang -analyzer-config -Xclang experimental-enable-naive-ctu-analysis=true -Xclang -analyzer-config -Xclang ctu-dir=ctudir -Xclang -analyzer-config -Xclang display-ctu-progress=true test.cpp` `CTU loaded AST file: bstrwrap.cpp.ast` `clang: clang/lib/AST/Decl.cpp:4045: void clang::FunctionDecl::setDescribedFunctionTemplate(clang::FunctionTemplateDecl*): Assertion "TemplateOrSpecialization.isNull() && "Member function is already a specialization" failed.` `PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.`
> 
> ...

Yes, I have tried the latest source, but it still looks good. Also, I didn't see the output `CTU loaded AST file: bstrwrap.cpp.ast`. I tried this command `clang-extdef-mapping test.cpp` and output is `11:c:@F@test0#` which is different from yours(`f` and `F`, output of the other file is identical). This time I see `CTU loaded AST file: bstrwrap.cpp.ast` but still has no crash. @vabridgers Can you check your output with command `clang-extdef-mapping test.cpp`?

**Comment by balazske** [comment]
I did not get crash with this script and latest clang. Probably there is a difference in the used system headers (`iostream` and `string` is included)?
