### PR TITLE
[Clang-Tidy] Fixed `cppcoreguidelines-init-variables` to handle ObjC for-in loops.

### LINKED ISSUE #62106: [clang-tidy] False positive for cppcoreguidelines-init-variables in Objective-C for-in loop
test.m:
```
#include <Foundation/Foundation.h>
void foo() {
    NSArray<NSString *> *values = @[ ];
    for (NSString *value in values) {
    }
}
```

Running:
`clang-tidy --checks=cppcoreguidelines-init-variables test.m`

```
test.m:4:20: warning: variable 'value' is not initialized [cppcoreguidelines-init-variables]
    for (NSString *value in values) {
                   ^
                         = NULL

```

### PR DESCRIPTION
**Pull request by sstepashka**
The check used to report false positive in case of for-in loop in Objective-C[++]:
```
for (NSString *value in values) {
   ...
}
```
With the report message:
```
...: warning: variable 'value' is not initialized [cppcoreguidelines-init-variables]
for (NSString *value in values) {
               ^
                     = NULL
```

This PR exclude the for-in loop from the the matcher in order to avoid the false-positive.

Fixes #62106

### CODE REVIEW

**Review by unterumarmung — COMMENTED** [review]
Please add an entry to the release notes.

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+// by the loop itself. Previously, the check would incorrectly try to insert
+// '= nullptr' at the wrong source location, corrupting the following statement.
+void objc_for_in_no_false_positive(NSArray *urls) {
+  for (NSURL *url in urls) {
+    // 'url' should NOT be flagged - it is a for-in loop variable.
+    NSString *urlString = [url absoluteString];
+    // 'urlString' should NOT be flagged - it has an initializer.
+    (void)urlString;
+  }
+}
```
[the remark this answers is not in the document]
Comment (sstepashka) [reply clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm]: PTAL.

**Comment by vbvictor** [comment]
Does it make sense to run this check on OBJ-C code?
Can we just turn-off it for OBJ-C, since cppcoreguidelines are specifically designed for C++

**Comment by unterumarmung** [comment]
I think it makes sense to check C++ Core Guidelines on Objective-C++ code.

**Comment by vbvictor** [comment]
> I think it makes sense to check C++ Core Guidelines on Objective-C++ code.

We had discussion before about similar thing https://discourse.llvm.org/t/rfc-clang-tidy-which-language-should-be-supported-by-default/88424.
So for now it may be reasonable to allow core guidelines on OBJ-C as long as we don't have big influx of issues involving OBJ-C. I think we have 0 tests convering cppcoreguidelines with obj-c.

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+@end
+
+@interface NSArray : NSObject
+@end
+
+void objc_for_in_no_false_positive(NSArray *urls) {
+  for (NSURL *url in urls) {
+    // 'url' should NOT be flagged - it is a for-in loop variable.
+    NSString *urlString = [url absoluteString];
+  }
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm:22]: can we add nested stmts:
```cpp
for (NSURL *url in urls) {
  {
    // 'url' should NOT be flagged - it is a for-in loop variable.
    NSString *urlString = [url absoluteString];
  }
}
```

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+}
+
+void objc_for_in_body_uninit(NSArray *urls) {
+  for (NSURL *url in urls) {
+    (void)url;
+
+    // CHECK-FIXES: NSString *str = nullptr;
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm:30]: Add check-messages

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm (hunk 2 above)
Comment (sstepashka) [reply clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm:22]: Sure, it's done, can you please elaborate the reason so I can to it right next time?

**Comment by sstepashka** [comment]
@vbvictor I am not sure if this PR should be blocked by the discussion. This PR doesn't change the existing status quo and only slightly improves the existing check the way it works right now.

Even if the project decided that ObjC is out-of-scope for the check and we'd like to disable it completely for ObjC, I'm also cool with that.

Is there anything specific what blocking the current PR I need to address?

**Comment by sstepashka** [comment]
@unterumarmung @vbvictor is there anything else required to be done to get this PR checked in? Or, if I have to close the PR and it's not going to be accepted? I am open to the possibilities.

**Comment by localspook** [comment]
I’m a bit confused about what we’re discussing: is the question whether we want to 
1. disable this check in Obj-C-not-++, but leave it enabled in Obj-C++; or
2. disable it in both?

**Comment by sstepashka** [comment]
> I’m a bit confused about what we’re discussing: is the question whether we want to
> 
> 1. disable this check in Obj-C-not-++, but leave it enabled in Obj-C++; or
> 2. disable it in both?

Should the decision be made in the context of the existing PR? I am not sure how any bigger decisions are made in LLVM. Let me know if I have to do anything with the given PR, even if it's just abandon it. I'm cool with any.

**Comment by localspook** [comment]
>  Should the decision be made in the context of the existing PR? I am not sure how any bigger decisions are made in LLVM. 

Right now I'm just trying to better understand what decision we're even considering.

> Let me know if I have to do anything with the given PR, even if it's just abandon it. I'm cool with any.

I want to hear from others first, so you don't need to do anything yet. Don't abandon it, unless we reach agreement that Obj-C is something we don't want to support.

**Comment by sstepashka** [comment]
Just for the context: In our project (due to legacy reasons) much of the code is compiled as Objective-C++ because it includes Cocoa headers. Even if most of the code is strictly speaking C++ and some of the headers are shared with C++ and Objective-C[++] we would extremely value the check to be enabled for `.mm` and `-x objective-c++` cases.

It wasn't the best idea to include Cocoa headers in C++, but it is what it is now.

**Comment by vbvictor** [comment]
Thanks everyone for discussion.
First of, sorry for absences. LLVM has loose time constraints and typical "ping" period is one week.

> I’m a bit confused about what we’re discussing: is the question whether we want to

I originally had a thought that we should just disable CPP-CORE checks from being run on non-C++ code since CPP-CORE are specifically targeting C++ code, but this statement:

> Just for the context: In our project (due to legacy reasons) much of the code is compiled as Objective-C++ because it includes Cocoa headers. Even if most of the code is strictly speaking C++ and some of the headers are shared with C++ and Objective-C[++] we would extremely value the check to be enabled for .mm and -x objective-c++ cases.

Gives picture that people are still using those check on C++ code inside obj-C.
So I think we should not immediately turn-off those checks for obj-c but in the long term it may bring several pitfalls: more churn to maintainers to triage (and probably fix) bugs involving obj-C with checks that weren't designed to run on obj-C.

**Review by vbvictor — APPROVED** [review]

**Comment by unterumarmung** [comment]
Well, Objective-C++ is still C++, so I think `cppcoreguidelines` checks should work on the Objective-C++ code to a certain degree

**Review by unterumarmung — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm (hunk 2 above)
Comment (vbvictor) [reply clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/init-variables-objcxx.mm:22]: Sorry, I forgot to mention that it should be separate test. It indeed sounded like this should be corrected here.

My initial impression was for these braces to add test-case for catching a FP if somehow `url absoluteString` was treated as declaration and we walked up AST-tree to ObjCForLoopStmt from there.
But that was not the case anyway.

The previous example that you wrote was fine, I'm just not familiar with OBJ-C and misunderstood how it works

**Comment by vbvictor** [comment]
localspook, If you don't have anything to add to this thread and fine with changes/proposal please merge.
I will wait a couple of days and merge if don't see any more activity here

**Comment by localspook** [comment]
"No uninitialized variables" seems like a reasonable rule to want to enforce even in Objective-C++, so I don't think this particular check should be disabled there. Maybe some individual cppcoreguidelines checks wouldn't apply, but I think we should decide that on a check-by-check basis.

**Review by localspook — APPROVED** [review]
