### PR TITLE
[clang] Forbid reinterpret_cast of function pointers in constexpr.

### LINKED ISSUE #150340: clang incorrectly allows converting function pointers to and from void* in constant expressions
Consider:

```
void f();
constexpr auto p1 = (void*)f;
constexpr auto p2 = (void(*)())p1;
```

clang currently accepts, but these should be rejected.  [expr.const] says an expression is not a constant expression if it contains a reinterpret_cast ... and converting a function pointer to an object pointer requires a reinterpret_cast.

gcc rejects, MSVC accepts p1.

### PR DESCRIPTION
**Pull request by efriedma-quic**
This has been explicitly forbidden since C++11, but somehow the edge case of converting a function pointer to void* using a cast like `(void*)f` wasn't handled.

Fixes #150340 .

### CODE REVIEW

File: clang/test/Sema/constexpr-void-cast.c [hunk 1]
```diff
@@ -3,8 +3,8 @@
 // RUN: %clang_cc1 -x c -fsyntax-only %s -verify=c -std=c11 -fexperimental-new-constant-interpreter
 // RUN: %clang_cc1 -x c -fsyntax-only %s -pedantic -verify=c-pedantic -std=c11 -fexperimental-new-constant-interpreter
 //
-// RUN: %clang_cc1 -x c++ -fsyntax-only %s -verify=cxx
-// RUN: %clang_cc1 -x c++ -fsyntax-only %s -pedantic -verify=cxx-pedantic
+// RUN: %clang_cc1 -x c++ -fsyntax-only %s -verify=cxx-nointerpreter
+// RUN: %clang_cc1 -x c++ -fsyntax-only %s -pedantic -verify=cxx-pedantic,cxx-nointerpreter
```
Comment (tbaederr) [inline clang/test/Sema/constexpr-void-cast.c:7]: The point of adding the RUN lines for the bytecode interpreter was to encourage people to fix changes in both interpreters, not add different verify prefixes.

Comment (efriedma-quic) [reply clang/test/Sema/constexpr-void-cast.c]: Attempted to add bytecode interpreter support.  Not sure I did it right, since the code is structured very differently from what I'm used to.

Comment (efriedma-quic) [reply clang/test/Sema/constexpr-void-cast.c]: Your suggestion is subtly different from my patch in one way; consider:

```
#define fold(x) (__builtin_constant_p(x) ? (x) : (x))
constexpr double f() { return 1; }
typedef double (*DoubleFn)();
constexpr DoubleFn x = (DoubleFn)fold((void*)f);
```

if you write something like `constexpr fnptr x = (fnptr)fold(void*)f));`, my patch gives a warning, and yours doesn't.  I should probably add a testcase for this.  Granted, I'm not sure this matters a lot, since there's no way to get a function pointer into a void* without resorting to extensions.

----

The additional diagnostic in functions.cpp is because traditional consteval produces a diagnostic note_invalid_subexpr_in_const_expr if a pointer is called where the type of the function doesn't match the function pointer type.  CallPtr doesn't produce a diagnostic if it finds a mismatch, so we return a "stale" diagnostic.

It also has a much looser interpretation of what counts as "matching".  For example, it's happy if you call a function that returns "long" with a function pointer that returns "long long".

**Review by tbaederr — APPROVED** [review]
