### PR TITLE
[clang][Sema] Bugfix for choosing the more specialized overload

### LINKED ISSUE #74494: incorrect overload resolution with deducing this
Hey,
@Waffl3x mentioned a possible bug in clang earlier and asked me to report it. 

```cpp
template<typename T>
concept AlwaysTrue = true;

struct S {
  int f(AlwaysTrue auto) { return 1; }; // f1
  int f(this S&&, auto) { return 2; };  // f2
};

int main() {
  return S{}.f(0);
}
```
https://clang.godbolt.org/z/x516PWsvd

According to [[basic.scope.scope]/3](https://eel.is/c++draft/basic.scope.scope#3) `f1` and `f2` should have corresponding signatures. Considering [[over.match.funcs.general]/5](https://eel.is/c++draft/over.match.funcs.general#5.sentence-3) I believe `f1` should be called here since it is more constrained. Clang however calls `f2`.

### LINKED ISSUE #82509: [Clang][Sema][Concepts] Clang can't choose from a member and a non member operator
Consider the following code:

```
struct s{
    template<class T>
    int operator+(const T&)const{return 0;}
};

template<class T>
concept AlwaysTrue=true;

template<AlwaysTrue T>
int operator+(const s&,const T&){return 1;}

int main(){
    return s{}+1;
}
```
godbolt example:  https://godbolt.org/z/vG31vjxbn
Since the 2nd `operator+` is more constrained clang should choose that. However clang reports an ambiguity. (GCC chooses the 2nd one as expected)   
Note that the ambiguity remains if the only 1st, or both declaration have a concept, (even if one of them is more constrained).
If we define both operators inside the class or both operators outside the class clang chooses the correct overload.

### PR DESCRIPTION
**Pull request by HoBoIs**
There was a bug in Clang where it couldn't choose which overload candidate was more specialized if it was comparing a member-function to a non-member function. Previously, this was detected as an ambiguity, now Clang chooses correctly.

This patch fixes the bug by fully implementing CWG2445 and moving the template transformation described in `[temp.func.order]` paragraph 3 from `isAtLeastAsSpecializedAs()` to `Sema::getMoreSpecializedTemplate()` so we have the transformed parameter list during the whole comparison. Also, to be able to add the correct type for the implicit object parameter `Sema::getMoreSpecializedTemplate()` has new parameters for the object type.

Fixes #74494, fixes #82509

### CODE REVIEW

**Comment by HoBoIs** [comment]
@zygoloid @erichkeane Could you take a look?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -5333,11 +5333,31 @@ bool Sema::CheckIfFunctionSpecializationIsImmediate(FunctionDecl *FD,
   return false;
 }
 
+static QualType GetImplicitObjectParameterTypeCXX20(ASTContext &Context,
+                                                    const CXXMethodDecl *Method,
+                                                    QualType rawType,
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5338]: Coding standard says parms are capital first letter.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 2]
```diff
@@ -5333,11 +5333,31 @@ bool Sema::CheckIfFunctionSpecializationIsImmediate(FunctionDecl *FD,
   return false;
 }
 
+static QualType GetImplicitObjectParameterTypeCXX20(ASTContext &Context,
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5336]: I don't think splitting this method up into 2 like this is necessary, I think these two should be the same function with the language-based split for the condition of the 'if' statement.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 3]
```diff
@@ -5548,13 +5514,113 @@ static bool isAtLeastAsSpecializedAs(Sema &S,
...
-  bool Better1 = isAtLeastAsSpecializedAs(*this, Loc, FT1, FT2, TPOC,
-                                          NumCallArguments1, Reversed);
-  bool Better2 = isAtLeastAsSpecializedAs(*this, Loc, FT2, FT1, TPOC,
-                                          NumCallArguments2, Reversed);
+    //   - In the context of a function call, the function parameter types are
+    //     used.
+    const CXXMethodDecl *Method1 = dyn_cast<CXXMethodDecl>(FD1);
+    const CXXMethodDecl *Method2 = dyn_cast<CXXMethodDecl>(FD2);
+
+    if (getLangOpts().CPlusPlus20) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5538]: Same here, these two branches are REALLY similar and should probably be combined.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 4]
```diff
@@ -5548,13 +5514,113 @@ static bool isAtLeastAsSpecializedAs(Sema &S,
...
+      //
+      // Note that we interpret "that is a member function" as
+      // "that is a member function with no expicit object argument".
+      // Otherwise the ordering rules for methods with expicit objet arguments
+      // against anything else make no sense.
+      shouldConvert1 = Method1 && !Method1->isExplicitObjectMemberFunction();
+      shouldConvert2 = Method2 && !Method2->isExplicitObjectMemberFunction();
+      if (shouldConvert1) {
+        bool isR2 =
+            Method2 && !Method2->isExplicitObjectMemberFunction()
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5552]: This whole line is `shouldConvert2`.

**Review by erichkeane — COMMENTED** [review]
This needs tests plus a release note.  

Also, there is a lot of repeated code between the pre-c++20 and c++20 versions that will make this really hard to maintain, particularly with core issues, that I'd like to see merged better.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 5]
```diff
@@ -5548,13 +5504,100 @@ static bool isAtLeastAsSpecializedAs(Sema &S,
...
+      // it as wording was broken prior to it.
+      shouldConvert1 =
+          !Method2 && Method1 && Method1->isImplicitObjectMemberFunction();
+      shouldConvert2 =
+          !Method1 && Method2 && Method2->isImplicitObjectMemberFunction();
+    }
+    if (shouldConvert1) {
+      bool isR2 =
+          getLangOpts().CPlusPlus20 &&
+          (shouldConvert1
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5561]: Think this line is a copy/paste error?  We already know the value of shouldConvert1 (and 2 below).

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 6]
```diff
@@ -5548,13 +5504,100 @@ static bool isAtLeastAsSpecializedAs(Sema &S,
...
-                                          NumCallArguments2, Reversed);
+    Args1.insert(Args1.end(), Proto1->param_type_begin(),
+                 Proto1->param_type_end());
+    Args2.insert(Args2.end(), Proto2->param_type_begin(),
+                 Proto2->param_type_end());
 
+    // C++ [temp.func.order]p5:
+    //   The presence of unused ellipsis and default arguments has no effect on
+    //   the partial ordering of function templates.
+    if (Args1.size() > NumComparedArguments)
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5590]:
```suggestion
    Args1.resize(std::max(Args1.size(), NumComparedArguments));
    Args2.resize(std::max(Args2.size(), NumComparedArguments));
```

**Review by erichkeane — COMMENTED** [review]
This is close I think, just needs tests + ReleaseNotes.rst entry.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
Comment (HoBoIs) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5590]: `Args1.resize(std::max(Args1.size(), NumComparedArguments));` is not functionally equivalent to what I wrote, and will not work as intended. I need to drop elements, not to add new default constructed ones. I think you meant to write `min` instead of `max`. 
 Still I don't see why `Args1.resize(min(Args1.size(), NumComparedArguments));` is preferable to the original.

Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5590]: Seemingly the original is more confusing as to what it is doing than I thought :)    I thought that the 'if' statements were overly verbose for something pretty trivial and the 1 liners made this less distracting along with reading the rest of the function.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 5 above)
Comment (HoBoIs) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5561]: Actually I just mixed up `shouldConvert1` and `shouldConvert2`

Comment (HoBoIs) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: fixed

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
Comment (HoBoIs) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5590]: How can I make it less confusing? Should I put in a comment explaining that in `Args1` and `Args2` after the first `NumComparedArguments` elements there can only be unused ellipsis and default arguments? (It already states that  unused ellipsis and default arguments has no effect on the partial ordering of function templates. Just above the if)

File: clang/www/cxx_dr_status.html [hunk 7]
```diff
@@ -14478,7 +14478,7 @@ <h2 id="cxxdr">C++ defect report implementation status</h2>
     <td><a href="https://cplusplus.github.io/CWG/issues/2445.html">2445</a></td>
     <td>C++20</td>
     <td>Partial ordering with rewritten candidates</td>
-    <td class="unknown" align="center">Unknown</td>
+    <td class="unreleased" align="center">Clang 18</td>
```
Comment (Endilll) [inline clang/www/cxx_dr_status.html:14481]: You shouldn't edit this file by hand. Instead, you should place a test in `/clang/test/CXX/drs/24xx.cpp` with a `// dr2445: 18` status, then run `/clang/www/make_cxx_dr_status` script. Follow the example of other tests in `24xx.cpp` while doing that.

**Review by Endilll — CHANGES_REQUESTED** [review]

File: clang/www/cxx_dr_status.html (hunk 7 above)
Comment (HoBoIs) [reply clang/www/cxx_dr_status.html:14481]: I'm on it. While we are at here: should it be `18` or `19` ? As I can see 18 is almost out.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5590]: I thought the `resize` model was pretty clear, but that is a pattern I use frequently so I thought it read easily.

File: clang/www/cxx_dr_status.html (hunk 7 above)
Comment (Endilll) [reply clang/www/cxx_dr_status.html:14481]: `19`, unless you're planning to cherry-pick this into 18 branch (I don't advise to do that this late into pre-release phase).

Comment (HoBoIs) [reply clang/www/cxx_dr_status.html]: done

File: clang/test/CXX/drs/dr24xx.cpp [hunk 8]
```diff
@@ -68,3 +68,35 @@ template<A> struct X {};
 X<1> x;
 #endif
 }
+namespace dr2445 { // dr2445: 19
```
Comment (Endilll) [inline clang/test/CXX/drs/dr24xx.cpp:71]: It would be nice to have an empty line before the new namespace.

**Review by Endilll — APPROVED** [review]
DR changes looks good now, save for a nitpick.
However, I'm leaving it to other reviewers to check contents of the test. It looks like an example from the DR, but I don't feel qualified to say whether this test has sufficient coverage.

**Comment by HoBoIs** [comment]
> DR changes looks good now, save for a nitpick. However, I'm leaving it to other reviewers to check contents of the test. It looks like an example from the DR, but I don't feel qualified to say whether this test has sufficient coverage.

I have added tests to other files what are relevant for the DR too. Should I move them here?

**Comment by Endilll** [comment]
> I have added tests to other files what are relevant for the DR too. Should I move them here?

I trust your judgement here. Your PR touches a topic complicated enough that I don't feel qualified to make the judgement myself.

My stance is that DR should be considered narrow in scope. So if you think that your additional tests are directly related to what the DR is about, go ahead. For instance, when DR is about cv-qualifiers in variable declarations, but the provided examples only cover `const`, I consider additional test for `volatile` to be directly related. On the other hand, if during implementation you realize that something is going on with cv-qualifiers on non-static member functions, and you want to test that, then it's a related issue, but not a part of the DR.

In my view, DR test suite prioritizes being on spot more than just containing sheer volume of tests.

**Comment by HoBoIs** [comment]
I have added tests for rvalref-s and `volatile`-s.

**Comment by HoBoIs** [comment]
@erichkeane a question: this PR is partly a fix for a DR for c++20. Right now I only apply the fix for C++20 and newer. Is there a reason for not applying this fix for older standards? I don't see how it would break any existing code, and making the fix retroactive doesn't make any test fail.

**Comment by HoBoIs** [comment]
> I don't think checking for c++20 is useful because rewritten candidates are a c++20- feature anyway

Yes, but the resolution of the DR also talks about the reference type of the object parameter. (If I apply the patch retroactively the code will get simpler.)

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
Comment (HoBoIs) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: Done

**Comment by HoBoIs** [comment]
@erichkeane Thank you for the suggestions, I have removed the checking for C++20 and I also changed to the `Args.resize(std::min(...))` based on what you suggested. Is there anything else to be done?

**Review by erichkeane — APPROVED** [review]
Only some minor things left, so approving.  Mostly, for the 'type' and 'context', just do them the way they would read:
So "Object One Type" (plus we use Ty to mean type).  Same with Context.

Finally, `SmallVector` doesn't need a size set, so just using the 'default' value (which it calculates for you!)  is sufficient here.

Feel free to merge when CI agrees with you on the above/below changes.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 9]
```diff
@@ -5333,38 +5333,37 @@ bool Sema::CheckIfFunctionSpecializationIsImmediate(FunctionDecl *FD,
...
+                                               const CXXMethodDecl *Method,
+                                               QualType RawType,
+                                               bool IsOtherRvr) {
+  // C++20 [temp.func.order]p3.1, p3.2:
+  //- The type X(M ) is “rvalue reference to cv A” if the optional ref-qualifier
+  //  of M is && or if M has no ref-qualifier and the positionally-corresponding
+  //  parameter of the other transformed template has rvalue reference type;
+  //  if this determination depends recursively upon whether X(M ) is an rvalue
+  //  reference type, it is not considered to have rvalue reference type.
+  //- Otherwise, X(M ) is “lvalue reference to cv A”.
```
Comment (whisperity) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5346]:
```suggestion
  // C++20 [temp.func.order]p3.1, p3.2:
  //  - The type X(M) is "rvalue reference to cv A" if the optional
  //    ref-qualifier of M is && or if M has no ref-qualifier and the
  //    positionally-corresponding parameter of the other transformed
  //    template has rvalue reference type; if this determination depends
  //    recursively upon whether X(M) is an rvalue reference type, it
  //    is not considered to have rvalue reference type.
  //
  //  - Otherwise, X(M) is "lvalue reference to cv A".
```

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 10]
```diff
@@ -5548,13 +5493,76 @@ static bool isAtLeastAsSpecializedAs(Sema &S,
...
+    //   [...] Each function template M that is a member function is
+    //   considered to have a new first parameter of type
+    //   X(M), described below, inserted in its function parameter list.
+    //
+    // Note that we interpret "that is a member function" as
+    // "that is a member function with no expicit object argument".
+    // Otherwise the ordering rules for methods with expicit objet arguments
+    // against anything else make no sense.
+    shouldConvert1 = Method1 && !Method1->isExplicitObjectMemberFunction();
+    shouldConvert2 = Method2 && !Method2->isExplicitObjectMemberFunction();
```
Comment (whisperity) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5525]:
```suggestion
    ShouldConvert1 = Method1 && !Method1->isExplicitObjectMemberFunction();
    ShouldConvert2 = Method2 && !Method2->isExplicitObjectMemberFunction();
```

Style nit formatting, if we're changing the code even though it might largely be a move/refactor, you can fix the formatting now!

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 11]
```diff
@@ -5568,12 +5576,28 @@ FunctionTemplateDecl *Sema::getMoreSpecializedTemplate(
...
   //   have a corresponding parameter, and if F does not have a trailing
   //   function parameter pack, then F is more specialized than G.
-  FunctionDecl *FD1 = FT1->getTemplatedDecl();
-  FunctionDecl *FD2 = FT2->getTemplatedDecl();
-  unsigned NumParams1 = FD1->getNumParams();
-  unsigned NumParams2 = FD2->getNumParams();
-  bool Variadic1 = NumParams1 && FD1->parameters().back()->isParameterPack();
-  bool Variadic2 = NumParams2 && FD2->parameters().back()->isParameterPack();
+
+  SmallVector<QualType> param1;
```
Comment (whisperity) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5580]:
```suggestion
  SmallVector<QualType> Param1;
```

Ditto, everywhere!

**Review by whisperity — CHANGES_REQUESTED** [review]
(Only style nits!)

**Review by whisperity — APPROVED** [review]
LGTM.
