### PR TITLE
[VPlan] Add transformation to narrow interleave groups.

### LINKED ISSUE #82936: simd vectorization regression starting with clang 14
A simple loop multiplying two arrays, with different multiplicity fails to vectorize efficiently on clang 14+, while it worked with clang 13.0.1
The loop is the following, where 4 consecutive values in data are multiplied by the same factor :

```C
    for (int i=0; i<n; i++) {
     for (int k=0; k<4; k++) data[4*i+k] *= factor[i];
    }
```
See on godbolt to see the crazy code generated by clang 14+, while clang 13.0.1 correctly uses `vbroadcastsd` :
https://godbolt.org/z/desh4E49o

### PR DESCRIPTION
**Pull request by fhahn**
This patch adds a new narrowInterleaveGroups transfrom, which tries
convert a plan with interleave groups with VF elements to a plan that
instead replaces the interleave groups with wide loads and stores
processing VF elements.

This effectively is a very simple form of loop-aware SLP, where we
use interleave groups to identify candidates.

This initial version is quite restricted and hopefully serves as a
starting point for how to best model those kinds of transforms.

Depends on https://github.com/llvm/llvm-project/pull/106431.

Fixes https://github.com/llvm/llvm-project/issues/82936

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 1]
```diff
@@ -8993,8 +8996,8 @@ LoopVectorizationPlanner::tryToBuildVPlanWithVPRecipes(VFRange &Range) {
   // Interleave memory: for each Interleave Group we marked earlier as relevant
   // for this VPlan, replace the Recipes widening its memory instructions with a
   // single VPInterleaveRecipe at its insertion point.
-  VPlanTransforms::createInterleaveGroups(InterleaveGroups, RecipeBuilder,
-                                          CM.isScalarEpilogueAllowed());
+  VPlanTransforms::createInterleaveGroups(
+      *Plan, InterleaveGroups, RecipeBuilder, CM.isScalarEpilogueAllowed());
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:9000]: nit: RecipeBuilder already holds Plan.

File: llvm/lib/Transforms/Vectorize/VPlan.h [hunk 2]
```diff
@@ -1330,6 +1330,13 @@ class VPInstruction : public VPRecipeWithIRFlags {
     assert(Opcode == Instruction::Or && "only OR opcodes can be disjoint");
   }
 
+  VPInstruction(VPValue *Ptr, VPValue *Offset, bool InBounds, DebugLoc DL = {},
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlan.h:1333]: Seems a bit odd for a constructor of VPInstruction(VPValue*, VPValue*, bool) to create a PtrAdd. Perhaps having GEPFlagsTy as 3rd parameter instead of bool would be clearer. Should be documented.

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp [hunk 3]
```diff
@@ -646,7 +650,9 @@ Value *VPInstruction::generatePerPart(VPTransformState &State, unsigned Part) {
            "can only generate first lane for PtrAdd");
     Value *Ptr = State.get(getOperand(0), Part, /* IsScalar */ true);
     Value *Addend = State.get(getOperand(1), Part, /* IsScalar */ true);
-    return Builder.CreatePtrAdd(Ptr, Addend, Name);
+    return Builder.CreatePtrAdd(Ptr, Addend, Name,
+                                isInBounds() ? GEPNoWrapFlags::inBounds()
+                                             : GEPNoWrapFlags::none());
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:655]: Independent of this patch?

Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:655]: Have 
```
GEPNoWrapFlags VPRecipeWithIRFlags::getGEPNoWrapFlags() const;
```
similar to
```
FastMathFlags VPRecipeWithIRFlags::getFastMathFlags() const
```
and then
```suggestion
    return Builder.CreatePtrAdd(Ptr, Addend, Name, getGEPNoWrapFlags());
```
?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 4]
```diff
@@ -673,6 +672,7 @@ static void recursivelyDeleteDeadRecipes(VPValue *V) {
 void VPlanTransforms::optimizeForVFAndUF(VPlan &Plan, ElementCount BestVF,
                                          unsigned BestUF,
                                          PredicatedScalarEvolution &PSE) {
+
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:675]:
```suggestion
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 5]
```diff
@@ -714,6 +714,7 @@ void VPlanTransforms::optimizeForVFAndUF(VPlan &Plan, ElementCount BestVF,
   // TODO: Further simplifications are possible
   //      1. Replace inductions with constants.
   //      2. Replace vector loop region with VPBasicBlock.
+  //
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:717]:
```suggestion
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 6]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+           *Plan.getVectorLoopRegion()->getEntryBasicBlock())) {
+    if (match(&R, m_BranchOnCount(m_VPValue(), m_VPValue())) ||
+        isa<VPCanonicalIVPHIRecipe>(&R))
+      continue;
+
+    // Bail out on recipes not supported at the moment:
+    //  * phi recipes other than the canonical induction
+    //  * recipes writing to memory except interleave groups
+    // Only support plans with a canonical induction phi.
+    if ((R.isPhi() && !isa<VPCanonicalIVPHIRecipe>(&R)) ||
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1637]: CanonicalIVPhi early continued above?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 7]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+        (R.mayWriteToMemory() && !isa<VPInterleaveRecipe>(&R)))
+      return false;
+
+    auto *IR = dyn_cast<VPInterleaveRecipe>(&R);
+    if (!IR)
+      continue;
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1643]:
```suggestion
    if (R.isPhi())
      return false;

    auto *IR = dyn_cast<VPInterleaveRecipe>(&R);
    if (R.mayWriteToMemory() && !IR)
      return false;

    if (!IR)
      continue;
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 8]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+}
+
+bool VPlanTransforms::narrowInterleaveGroups(VPlan &Plan, ElementCount VF) {
+  using namespace llvm::VPlanPatternMatch;
+  if (VF.isScalable())
+    return false;
+
+  bool Changed = false;
+  SmallVector<VPInterleaveRecipe *> StoreGroups;
+  for (auto &R : make_early_inc_range(
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1627]: Why make_early_inc_range if StoreGroups is filled to be operated on later?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 9]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+
+  if (auto *IR = dyn_cast_or_null<VPInterleaveRecipe>(V->getDefiningRecipe())) {
+    return IR->getInterleaveGroup()->getFactor() ==
+               IR->getInterleaveGroup()->getNumMembers() &&
+           IR->getVPValue(Idx) == V;
+  }
+  return false;
+}
+
+/// Returns true of \p IR is a consecutive interleave group with \p VF members.
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1610]:
```suggestion
/// Returns true of \p IR is a full interleave group with factor and number of members both equal to \p VF.
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 10]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+static bool isConsecutiveInterleaveGroup(VPInterleaveRecipe *IR,
+                                         ElementCount VF) {
+  if (!IR)
+    return false;
+  auto IG = IR->getInterleaveGroup();
+  return IG->getFactor() == IG->getNumMembers() &&
+         IG->getNumMembers() == VF.getKnownMinValue();
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1617]:
```suggestion
         IG->getNumMembers() == VF.getFixedValue();
```
?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 11]
```diff
@@ -1555,3 +1591,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+    Lane0->setOperand(LoadGroupIdx, L);
+    Lane0->setOperand(WideLoadIdx, N);
+
+    auto *S = new VPWidenStoreRecipe(
+        *cast<StoreInst>(StoreGroup->getInterleaveGroup()->getInsertPos()),
+        StoreGroup->getAddr(), Lane0, nullptr, true, false,
+        StoreGroup->getDebugLoc());
+    S->insertBefore(StoreGroup);
+    StoreGroup->eraseFromParent();
+    Changed = true;
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1705]: Early exit above if StoredGroups.empty() returning false?

**Review by ayalz — COMMENTED** [review]
First set of minor comments.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 9 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Updated thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 10 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Adjusted, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 8 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: This was a left-over from earlier versions, removed, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 6 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Removed, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 7 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Simplified, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 11 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Updated, thanks!

File: llvm/lib/Transforms/Vectorize/VPlan.h (hunk 2 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlan.h]: This is part of  #10643

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 1 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:9010]: This is part of #10643

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 12]
```diff
@@ -7487,6 +7487,9 @@ LoopVectorizationPlanner::executePlan(
 
   VPlanTransforms::optimizeForVFAndUF(BestVPlan, BestVF, BestUF, PSE);
 
+  if (VPlanTransforms::narrowInterleaveGroups(BestVPlan, BestVF)) {
+    LLVM_DEBUG(dbgs() << "Narrowed interleave\n");
+  }
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Moved, thanks!

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 13]
```diff
@@ -7487,6 +7487,9 @@ LoopVectorizationPlanner::executePlan(
 
   VPlanTransforms::optimizeForVFAndUF(BestVPlan, BestVF, BestUF, PSE);
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:7510]: Sounds good! There are no other simplifications there so far

File: llvm/lib/Transforms/Vectorize/VPlan.cpp [hunk 14]
```diff
@@ -954,7 +954,6 @@ void VPlan::prepareToExecute(Value *TripCountV, Value *VectorTripCountV,
 
   IRBuilder<> Builder(State.CFG.PrevBB->getTerminator());
   // FIXME: Model VF * UF computation completely in VPlan.
-  assert(VFxUF.getNumUsers() && "VFxUF expected to always have users");
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlan.cpp:957]: Why dropping this check? If this check is dropped, shall it early exit if VFxUF.getNumUsers() == 0?

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp [hunk 15]
```diff
@@ -48,6 +48,9 @@ extern cl::opt<unsigned> ForceTargetInstructionCost;
 
 bool VPRecipeBase::mayWriteToMemory() const {
   switch (getVPDefID()) {
+  case VPInstructionSC: {
+    return !Instruction::isBinaryOp(cast<VPInstruction>(this)->getOpcode());
+  }
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:53]: What about cast or select or other instructions here? Is this still correct for them?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 16]
```diff
@@ -29,6 +29,9 @@
 #include "llvm/IR/Intrinsics.h"
 #include "llvm/IR/PatternMatch.h"
 
+#define LV_NAME "loop-vectorize"
+#define DEBUG_TYPE LV_NAME
+
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:34]: Why do you need this?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 17]
```diff
@@ -1623,3 +1661,129 @@ void VPlanTransforms::createInterleaveGroups(
       }
   }
 }
+
+static bool supportedLoad(VPWidenRecipe *R0, VPValue *V, unsigned Idx) {
+  if (auto *W = dyn_cast_or_null<VPWidenLoadRecipe>(V->getDefiningRecipe())) {
+    if (W->getMask())
+      return false;
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1668]:
```suggestion
    return !W->getMask();
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 18]
```diff
@@ -1623,3 +1661,129 @@ void VPlanTransforms::createInterleaveGroups(
...
+        IR->getStoredValues()[0]->getDefiningRecipe());
+    if (!Lane0)
+      return;
+    for (const auto &[I, V] : enumerate(IR->getStoredValues())) {
+      auto *R = dyn_cast<VPWidenRecipe>(V->getDefiningRecipe());
+      if (!R || R->getOpcode() != Lane0->getOpcode())
+        return;
+      // Work around captured structured bindings being a C++20 extension.
+      auto Idx = I;
+      if (any_of(R->operands(), [Lane0, Idx](VPValue *V) {
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1731]:
```suggestion
      if (any_of(R->operands(), [Lane0, Idx=I](VPValue *V) {
```

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp (hunk 15 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp]: Yep, unified the logic separately (68ed1728bf45162187a2b54eed226097b8fc0a12) and remove the change here

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 17 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Dropped the check and return as it is subsumed by the check below, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 18 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Done, I think originally Clang complained about this being an extension. Looks fine now, thanks!

File: llvm/lib/Transforms/Vectorize/VPlan.cpp (hunk 14 above)
Comment (alexey-bataev) [reply llvm/lib/Transforms/Vectorize/VPlan.cpp:965]: Shall it early exit then if VFxUF.getNumUsers() == 0?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 19]
```diff
@@ -1663,3 +1666,125 @@ void VPlanTransforms::createInterleaveGroups(
       }
   }
 }
+
+static bool supportedLoad(VPWidenRecipe *R0, VPValue *V, unsigned Idx) {
+  if (auto *W = dyn_cast_or_null<VPWidenLoadRecipe>(V->getDefiningRecipe())) {
+    return !W->getMask() && (R0->getOperand(0) == V || R0->getOperand(1) == V);
+  }
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1673]: Drop braces?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 20]
```diff
@@ -1663,3 +1666,125 @@ void VPlanTransforms::createInterleaveGroups(
...
+
+  if (auto *IR = dyn_cast_or_null<VPInterleaveRecipe>(V->getDefiningRecipe())) {
+    return IR->getInterleaveGroup()->getFactor() ==
+               IR->getInterleaveGroup()->getNumMembers() &&
+           IR->getVPValue(Idx) == V;
+  }
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1679]: Drop braces?

File: llvm/lib/Transforms/Vectorize/VPlan.cpp (hunk 14 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlan.cpp:942]: Done, thanks!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 19 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Done, thanks

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 20 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Done thanks

**Review by fhahn — COMMENTED** [review]
Updated the current main and comments addressed.

Ping :)

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 21]
```diff
@@ -1921,3 +1924,123 @@ void VPlanTransforms::handleUncountableEarlyExit(
...
+
+    // Narrow wide load to uniform scalar load, as transformed VPlan will only
+    // process one original iteration.
+    auto *N = new VPReplicateRecipe(&WideLoad->getIngredient(),
+                                    WideLoad->operands(), true);
+    // Narrow interleave group to wide load, as transformed VPlan will only
+    // process one original iteration.
+    auto *L = new VPWidenLoadRecipe(
+        *cast<LoadInst>(LoadGroup->getInterleaveGroup()->getInsertPos()),
+        LoadGroup->getAddr(), LoadGroup->getMask(), true, false,
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:2023]: Comments for true and false arguments

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 22]
```diff
@@ -1921,3 +1924,123 @@ void VPlanTransforms::handleUncountableEarlyExit(
...
+        LoadGroup->getDebugLoc());
+    L->insertBefore(LoadGroup);
+    N->insertBefore(LoadGroup);
+    Lane0->setOperand(LoadGroupIdx, L);
+    Lane0->setOperand(WideLoadIdx, N);
+
+    auto *S = new VPWidenStoreRecipe(
+        *cast<StoreInst>(StoreGroup->getInterleaveGroup()->getInsertPos()),
+        StoreGroup->getAddr(), Lane0, nullptr, true, false,
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:2032]: Comments for true and false arguments

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 23]
```diff
@@ -1921,3 +1924,123 @@ void VPlanTransforms::handleUncountableEarlyExit(
...
+        StoreGroup->getDebugLoc());
+    S->insertBefore(StoreGroup);
+    StoreGroup->eraseFromParent();
+  }
+
+  // Adjust induction to reflect that the transformed plan only processes one
+  // original iteration.
+  auto *CanIV = Plan.getCanonicalIV();
+  VPInstruction *Inc = cast<VPInstruction>(CanIV->getBackedgeValue());
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:2041]:
```suggestion
  auto *Inc = cast<VPInstruction>(CanIV->getBackedgeValue());
```

Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Done thanks!

**Review by fhahn — COMMENTED** [review]
ping :)

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.h [hunk 24]
```diff
@@ -137,6 +137,13 @@ struct VPlanTransforms {
 
   /// Lower abstract recipes to concrete ones, that can be codegen'd.
   static void convertToConcreteRecipes(VPlan &Plan);
+
+  /// Try to convert a plan with interleave groups with VF elements to a plan
+  /// with the
+  /// the interleave groups replaced by wide loads and stores processing VF
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.h:143]: Formatting?

Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.h]: Reflowed comment and dropped duplicated `the`, thanks!

**Review by alexey-bataev — APPROVED** [review]
LG

**Review by ayalz — COMMENTED** [review]
Post-approval review.

This patch does more than "narrow interleave groups" - it narrows the entire vector loop, including all its interleave groups.

The pattern handled is that of the reported
```
  for (int i=0; i<n; i++) {
    for (int k=0; k<4; k++) data[4*i+k] *= factor[i];
  }
```
where * can be any binary operation. I.e., a full consecutive interleaved stored fed by a matching interleaved load (not necessarily from same base address) multiplied by a common consecutive factor.

The only cross-iteration dependence allowed, and required, is a canonical IV; should live-outs also be forbidden?

A more basic pattern to start with may be  `data_out[4*i+k] = data_in[4*i+k]`. I.e., matching pairs of IG's. Every such pair can be optimized standalone by removing the shuffles of both IG's, leaving a wide load feeding a wide store. Then, if all IG's in the loop have been thus transformed, plus other conditions, the loop itself can be considered for narrowing. Makes sense?

File: llvm/test/Transforms/LoopVectorize/X86/transform-narrow-interleave-to-widen-memory.ll
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/test/Transforms/LoopVectorize/X86/transform-narrow-interleave-to-widen-memory.ll:1]: Done, thanks!

**Review by fhahn — COMMENTED** [review]
I landed the load->store group only transform separately as c73ad7ba204fa05b074c1316b2244063aa10410f as suggested.

Will land the changes in the PR soon as well

**Comment by mstorsjo** [comment]
This change caused a miscompile in ffmpeg, on aarch64 (on both Linux and Windows), causing ffmpeg to crash. The issue is reproducible both with ffmpeg compiled via llvm-test-suite, and compiled standalone (clone https://github.com/ffmpeg/ffmpeg, `./configure --cc=clang && make -j$(nproc)`).

To reproduce the crash, build ffmpeg in either way and run:
```
$ ./External/ffmpeg/ffmpeg -s 352x288 -i http://martin.st/temp/vsynth1.yuv -c ffv1 -coder range_tab -pass 1 -y vsynth1-ffv1-2pass.avi
```
(This uses an input file hosted by me, for repeated use it may be easier to download it and reference it with a local file name.)

The miscompiled source file is `libavcodec/ffv1enc.c`.

**Comment by mstorsjo** [comment]
> This change caused a miscompile in ffmpeg, on aarch64 (on both Linux and Windows), causing ffmpeg to crash. The issue is reproducible both with ffmpeg compiled via llvm-test-suite, and compiled standalone (clone https://github.com/ffmpeg/ffmpeg, `./configure --cc=clang && make -j$(nproc)`).
> 
> To reproduce the crash, build ffmpeg in either way and run:
> 
> ```
> $ ./External/ffmpeg/ffmpeg -s 352x288 -i http://martin.st/temp/vsynth1.yuv -c ffv1 -coder range_tab -pass 1 -y vsynth1-ffv1-2pass.avi
> ```
> 
> (This uses an input file hosted by me, for repeated use it may be easier to download it and reference it with a local file name.)
> 
> The miscompiled source file is `libavcodec/ffv1enc.c`.

I pushed a revert for this change now.

**Comment by fhahn** [comment]
@mstorsjo thanks, I recommitted with a fix, limiting this to loops w/o interleaving for now: 577631f0a52884384786bf899951e3094ad7f69c

I ran the ffmpeg tests from the test-suite, but it sounds like the test-suite coverage could be improved by running various encoders with different inputs and checking the output? Would the input files you are using for your testing be suitable for adding to the test-suite and define tests using them?
