### PR TITLE
[X86] Attempt to fold extract_vector_elt(logicop(x,y),i) -> extract_vector_elt(x,i)

### LINKED ISSUE #193700: [X86] i128 mask/update regression after wide integer bitlogic is lowered through XMM
Rust bumped LLVM from v21 to v22 (https://github.com/rust-lang/rust/pull/150722).

This caused a nasty performance regression (https://github.com/oxc-project/oxc/pull/21509#issuecomment-4263094649).

In oxc, the `Token` is heavely optimised, the updates to the token are in a very hot path. This regression only appears on x86-64.

 reduced it to LLVM IR where an `i128` value is loaded, part of the low 64 bits is masked out, a new `i32` field is inserted, the `i128` is stored back, and the new value is returned.

It can be reduced to the following LLVM IR:

```mlir
define noundef i128 @hot_end_mask(ptr noalias noundef align 16 captures(none) dereferenceable(16) %token, i32 noundef %end) unnamed_addr {
start:
  %0 = load i128, ptr %token, align 16
  %1 = and i128 %0, -18446744069414584321
  %_4 = zext i32 %end to i128
  %_3 = shl nuw nsw i128 %_4, 32
  %2 = or disjoint i128 %1, %_3
  store i128 %2, ptr %token, align 16
  ret i128 %2
}

define noundef i128 @hot_start_mask(ptr noalias noundef align 16 captures(none) dereferenceable(16) %token, i32 noundef %start1) unnamed_addr {
start:
  %0 = load i128, ptr %token, align 16
  %1 = and i128 %0, -4294967296
  %_3 = zext i32 %start1 to i128
  %2 = or disjoint i128 %1, %_3
  store i128 %2, ptr %token, align 16
  ret i128 %2
}
```

on v21, the following is emitted:

```asm
hot_end_mask:                           # @hot_end_mask
        mov     rdx, qword ptr [rdi + 8]
        mov     eax, dword ptr [rdi]
        shl     rsi, 32
        or      rax, rsi
        mov     qword ptr [rdi], rax
        ret
hot_start_mask:                         # @hot_start_mask
        mov     rdx, qword ptr [rdi + 8]
        mov     ecx, dword ptr [rdi + 4]
        shl     rcx, 32
        mov     eax, esi
        or      rax, rcx
        mov     qword ptr [rdi], rax
        ret
```

on v22:

```asm
hot_end_mask:                           # @hot_end_mask
        mov     eax, dword ptr [rdi]
        pshufd  xmm0, xmmword ptr [rdi], 238    # xmm0 = mem[2,3,2,3]
        movq    rdx, xmm0
        shl     rsi, 32
        or      rax, rsi
        movq    qword ptr [rdi + 8], xmm0
        mov     qword ptr [rdi], rax
        ret
.LCPI1_0:
        .long   0                               # 0x0
        .long   4294967295                      # 0xffffffff
        .long   4294967295                      # 0xffffffff
        .long   4294967295                      # 0xffffffff
hot_start_mask:                         # @hot_start_mask
        movdqa  xmm0, xmmword ptr [rdi]
        pshufd  xmm1, xmm0, 238                 # xmm1 = xmm0[2,3,2,3]
        movq    rdx, xmm1
        pand    xmm0, xmmword ptr [rip + .LCPI1_0]
        movq    rcx, xmm0
        mov     eax, esi
        or      rax, rcx
        movq    qword ptr [rdi + 8], xmm1
        mov     qword ptr [rdi], rax
        ret
```

---

The following is heavly AI assisted, as I'm not an LLVM expert, so feel free to ignore.

I bisected, using LLVM, and the regression appears to start at #171616.

Prior to this commit, the parent emits scalar code with only the necessary low-half store, while the next commit the `i128` bitlogic through XMM registers and stores the high half back unnecessarily.

I'm happy to attempt to look at a fix for this, but direction is appreciated - thanks!

### PR DESCRIPTION
**Pull request by RKSimon**
When extracting from logicops, we often don't need to extract the result if one of the element sources is identity (and(x,-1) -> x, or/xor(x,0) -> x etc.), so this patch uses SimplifyMultipleUseDemandedVectorElts to peek through to an underlying build_vector.

I had hoped to make this generic, but there's still a lot of yak shaving to deal with first, as usual - I've included the minimal x86-specific fixes:
 * missing constant folding of (vXi1 logicop(bitcast(c1),bitcast(c2)))
 * fold kshiftr(concat_vectors(x,y,z,w),c) -> concat_vectors(z,w,0,0)

Fixes #193700

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 1]
```diff
@@ -7767,6 +7767,13 @@ SDValue SelectionDAG::FoldConstantArithmetic(unsigned Opcode, const SDLoc &DL,
         }
       }
     }
+    // Logic ops can be folded from raw integer bits - mainly for AVX512 masks.
+    if (ISD::isBitwiseLogicOp(Opcode) && isa<ConstantSDNode>(N1) &&
+        isa<ConstantSDNode>(N2)) {
+      if (SDValue Res = FoldConstantArithmetic(Opcode, DL, N1.getValueType(),
```
Comment (phoebewang) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:7781]: Why we fold it here? I think the general DAGCombiner would do it already.

Comment (RKSimon) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:7781]: I was surprised as well - FoldConstantArithmetic currently can't fold data that is hidden by a bitcast from scalar integer to vector - this has to manually peek through and reattempt with the underlying scalar integers, which means we can only do this for logic ops.

**Review by phoebewang — APPROVED** [review]
LGTM.
