### PR TITLE
[Flang][OpenMp] Fix to threadprivate not working with host-association.

### LINKED ISSUE #60763: [flang][OpenMP] Threadprivate variable in host-association
https://github.com/flang-compiler/f18-llvm-project/issues/1136 has the detailed info about the support status of Threadprivate directive.
## Test case
```console
$ cat hostassoc1.f90 
program main
  use omp_lib
  integer, save :: a
  !$omp threadprivate(a)
  call sub()
contains
  subroutine sub()
    a = 2
    !$omp parallel num_threads(4)
      a = omp_get_thread_num()
      print *, a, omp_get_thread_num()
    !$omp end parallel
    !$omp parallel num_threads(4)
      print *, a, omp_get_thread_num()
    !$omp end parallel
  end
end
$ cat hostassoc2.f90 
program main
  use omp_lib
  integer :: a
  !$omp threadprivate(a)
  call sub()
contains
  subroutine sub()
    a = 2
    !$omp parallel num_threads(4)
      a = omp_get_thread_num()
      print *, a, omp_get_thread_num()
    !$omp end parallel
    !$omp parallel num_threads(4)
      print *, a, omp_get_thread_num()
    !$omp end parallel
  end
end
```
## Expected results:
```console
           0           0
           2           2
           3           3
           1           1
           2           2
           3           3
           1           1
           0           0
```
GFortran 12 and ifort 2021 support `hostassoc1.f90`, but do not support `hostassoc2.f90`. For `hostassoc2.f90`, GFortran 12 gives wrong running results, while ifort reports the semantic error.

### PR DESCRIPTION
**Pull request by harishch4**
This patch considers host-associated variables to generate threadprivate Ops.

Fixes: #60763

### CODE REVIEW

File: flang/lib/Lower/OpenMP.cpp [hunk 1]
```diff
@@ -1996,9 +1996,11 @@ static void threadPrivatizeVars(Fortran::lower::AbstractConverter &converter,
   };
 
   llvm::SetVector<const Fortran::semantics::Symbol *> threadprivateSyms;
-  converter.collectSymbolSet(
-      eval, threadprivateSyms,
-      Fortran::semantics::Symbol::Flag::OmpThreadprivate);
+  // Considering Host associated symbols as well.
+  converter.collectSymbolSet(eval, threadprivateSyms,
```
Comment (NimishMishra) [inline flang/lib/Lower/OpenMP.cpp:2000]: Could you once check how does this patch behave once https://github.com/llvm/llvm-project/pull/72510 is merged? If there are some discrepancies, one of these patches would need modifications. Reason being, so far, only default clause lowering was using the two boolean parameters in `collectSymbolSet`. Now we are extending that to threadprivate, so I am curious how that turns out.

File: flang/lib/Lower/OpenMP.cpp [hunk 2]
```diff
@@ -3528,8 +3530,16 @@ void Fortran::lower::genThreadprivateOp(
     // variable in main program, and it has implicit SAVE attribute. Take it as
     // with SAVE attribute, so to create GlobalOp for it to simplify the
     // translation to LLVM IR.
-    fir::GlobalOp global = globalInitialization(converter, firOpBuilder, sym,
-                                                var, currentLocation);
+    fir::GlobalOp global;
+    // Avoids performing multiple globalInitializations.
+    auto module = converter.getModuleOp();
+    std::string globalName = converter.mangleName(sym);
+    if (module.lookupSymbol<fir::GlobalOp>(globalName)) {
```
Comment (NimishMishra) [inline flang/lib/Lower/OpenMP.cpp:3537]: Can drop enclosing curly braces?

**Comment by harishch4** [comment]
@kiranchandramohan @NimishMishra Requesting for review.

File: flang/lib/Lower/HostAssociations.cpp [hunk 3]
```diff
@@ -508,7 +509,10 @@ void Fortran::lower::HostAssociations::addSymbolsToBind(
          "must be initially empty");
   this->hostScope = &hostScope;
   for (const auto *s : symbols)
-    if (Fortran::lower::symbolIsGlobal(*s)) {
+    // GlobalOp are created for non-global threadprivate variable,
```
Comment (NimishMishra) [inline flang/lib/Lower/HostAssociations.cpp:512]: Might be better to bring in the discussion on implicit SAVE here as well: https://github.com/llvm/llvm-project/blob/dea855de46bd4d3e103646a7f459856d88dd7488/flang/lib/Lower/OpenMP.cpp#L3940. Technically, an implicit SAVE attribute is what we consider, thereby requiring GlobalOp for non-global threadprivate vars.

**Review by NimishMishra — APPROVED** [review]
LGTM. It might be good to add details to the patch summary on the exact approach we took here. Mainly that (1) non-global threadprivate vars are added to `globalSymbols` (since they have implicit SAVE attribute on them), and that (2) during lowering, we skip globalOp creation if there already exists one (this happens in the change you have in OpenMP.cpp).

Currently, we are explicitly creating a threadprivate op in HostAssociations.cpp, and I am not the best person to say whether we are intermixing the two things more than we would like to. Please wait for @kiranchandramohan or someone else to comment on this before merging.

File: flang/lib/Lower/OpenMP.cpp (hunk 1 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:2000]: Thanks!

**Comment by harishch4** [comment]
@kiranchandramohan Requesting for review.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

Thanks for the fix. In future we should move this generation of `omp.threadprivate` as a pass in MLIR. May be mark the global threadprivate variables with another OpenMP dialect operation and then go through all the places where the global variable is used and generate `omp.threadprivate` operation.

**Comment by harishch4** [comment]
@kiranchandramohan @NimishMishra Thank you for reviewing and providing valuable suggestions.
