### PR TITLE
[RISCV][TTI] Avoid an infinite recursion issue in getCastInstrCost

### LINKED ISSUE #108708: [RISC-V][LoopUnroll] Segfault in `llvm::TargetLoweringBase::getTypeConversion`
Testcase:
```llvm ir
; ModuleID = 'reduced.bc'
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @d() #0 {
entry:
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %0 = bitcast <24 x i8> zeroinitializer to <192 x i1>
  br label %vector.body
}

attributes #0 = { "target-features"="+64bit,+a,+c,+d,+f,+m,+relax,+v,+zicsr,+zifencei,+zmmul,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvl128b,+zvl32b,+zvl64b,-b,-e,-experimental-smctr,-experimental-smmpm,-experimental-smnpm,-experimental-ssctr,-experimental-ssnpm,-experimental-sspm,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-h,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl4096b,-zvl512b,-zvl65536b,-zvl8192b" }
```
https://godbolt.org/z/xP4zEn74b

Command/backtrace:
```
> /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt --passes loop-unroll reduced.ll -S
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt --passes loop-unroll reduced.ll -S
1.	Running pass "function(loop-unroll<O2>)" on module "reduced.ll"
2.	Running pass "loop-unroll<O2>" on function "d"
  #0 0x0000650871b79db0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x307ddb0)
  #1 0x0000650871b771bf llvm::sys::RunSignalHandlers() (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x307b1bf)
  #2 0x0000650871b77315 SignalHandler(int) Signals.cpp:0:0
  #3 0x00007a405d442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
  #4 0x000065086fe4889e llvm::TargetLoweringBase::getTypeConversion(llvm::LLVMContext&, llvm::EVT) const (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x134c89e)
  #5 0x000065086f201618 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getTypeLegalizationCost(llvm::Type*) const (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705618)
  #6 0x000065086f202dfd llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
  #7 0x000065086f20580e llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
  #8 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
  #9 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
 #10 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
<...TRIMMED FOR GITHUB...>
#207 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#208 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#209 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#210 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#211 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#212 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#213 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#214 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#215 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#216 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#217 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#218 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#219 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#220 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#221 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#222 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#223 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#224 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#225 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#226 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#227 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#228 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#229 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#230 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#231 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#232 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#233 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#234 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#235 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#236 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#237 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#238 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#239 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#240 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#241 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#242 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#243 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#244 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#245 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#246 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#247 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#248 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#249 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#250 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
#251 0x000065086f202e57 llvm::RISCVTTIImpl::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#252 0x000065086f20586f llvm::RISCVTTIImpl::getVectorInstrCost(unsigned int, llvm::Type*, llvm::TargetTransformInfo::TargetCostKind, unsigned int, llvm::Value*, llvm::Value*) (.part.0) RISCVTargetTransformInfo.cpp:0:0
#253 0x000065086f206545 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, llvm::APInt const&, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70a545)
#254 0x000065086f201c08 llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getScalarizationOverhead(llvm::VectorType*, bool, bool, llvm::TargetTransformInfo::TargetCostKind) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x705c08)
#255 0x000065086f20218a llvm::BasicTTIImplBase<llvm::RISCVTTIImpl>::getCastInstrCost(unsigned int, llvm::Type*, llvm::Type*, llvm::TargetTransformInfo::CastContextHint, llvm::TargetTransformInfo::TargetCostKind, llvm::Instruction const*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt+0x70618a)
zsh: segmentation fault (core dumped)  /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/opt
```

Found via fuzzer

### PR DESCRIPTION
**Pull request by preames**
Calling into BasicTTI is not always safe.  In particular, BasicTTI does not have a full legalization implementation (vector widening is missing), and falls back on scalarization.  The problem is that scalarization for <N x i1> vectors is cost in terms of the cast API and we can end up in an infinite recursive cycle.

The "right" fix for this would be teach BasicTTI how to model the full legalization state machine, but several attempts at doing so have resulted in dead ends or undesirable cost changes for targets I don't understand.

This patch instead papers over the issue by avoiding the call to the base class when dealing with an i1 source or dest.  This doesn't necessarily produce correct costs, but it should at least return something semi-sensible and not crash.

Fixes https://github.com/llvm/llvm-project/issues/108708

### CODE REVIEW

**Comment by preames** [comment]
Note for reviewers - most of the cost changes are minor, and shouldn't actually matter.  The key test is the newly added @legalization_crash test.  As it's name implies, that exercises the infinite recursion bug.

**Review by arcbbb — APPROVED** [review]
LGTM. Thanks for this  patch!

File: llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp [hunk 1]
```diff
@@ -1163,9 +1163,47 @@ InstructionCost RISCVTTIImpl::getCastInstrCost(unsigned Opcode, Type *Dst,
...
+  case ISD::ZERO_EXTEND:
+    if (Src->getScalarSizeInBits() == 1) {
+      // We do not use vsext/vzext to extend from mask vector.
+      // Instead we use the following instructions to extend from mask vector:
+      // vmv.v.i v8, 0
+      // vmerge.vim v8, v8, -1, v0
+      return DstLT.first *
+                 getRISCVInstructionCost({RISCV::VMV_V_I, RISCV::VMERGE_VIM},
+                                         DstLT.second, CostKind) +
+             DstLT.first - 1;
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1189]: Is this DstLT.first - 1 the cost of gluing together two or more split ops?

Also a minor observations with this example I tried out, not related to this PR, we only need to cost 1 vmv.v.i

```llvm
define <256 x i8> @f(<256 x i1> %v) {
  %g = sext <256 x i1> %v to <256 x i8>
  ret <256 x i8> %g
}
```

```asm
f:
	vmv1r.v	v16, v8
	li	a0, 128
	vsetvli	zero, a0, e8, m8, ta, ma
	vmv.v.i	v24, 0
	vmerge.vim	v8, v24, -1, v0
	vmv1r.v	v0, v16
	vmerge.vim	v16, v24, -1, v0
        ret
```

**Review by lukel97 — APPROVED** [review]

File: llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp (hunk 1 above)
Comment (preames) [reply llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1189]: > Is this DstLT.first - 1 the cost of gluing together two or more split ops?
Yes, but specifically the case where you're splitting the i1 mask because you're splitting the other type.  You then need to slide together the masks. 

> Also a minor observations with this example I tried out, not related to this PR, we only need to cost 1 vmv.v.i
Good observation, will follow up!

Comment (preames) [reply llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1189]: Follow up posted here: https://github.com/llvm/llvm-project/pull/110282
