### PR TITLE
[win][aarch64] Place catch objects in the fixed object area

### LINKED ISSUE #146973: [aarch64][win] Applying alignment to a stack object causes a mis-compilation when using exception on Arm64 Windows
Given the following code:

```cpp
// Large object: alignment seems to be important?
struct alignas(128) BigObj {
    int value;
    // Destructor so it's kept alive.
    ~BigObj() { }
};

// Exception type need to be large enough to not fit in a register.
struct Error {
    int value;
    int padding[3];
};

int main() {
    BigObj bo{};

    try {
        throw Error { 42, {0, 0, 0} };
    } catch (const Error& e) {
        return e.value;
    }
    return 0;
}
```

This program crashes when built and run on Arm64 Windows:
```pwsh
> & 'C:\Program Files\LLVM\bin\clang.exe' .\test.cpp
> .\a.exe
> $LASTEXITCODE
-1073741819
```

The `alignas` seems to be important: if I remove that and replace it with a very large array within `BigObj` then the issue no longer reproduces.

When debugging, the slot for the exception in the catch is still null and nothing writes to it. In the VC Runtime during unwind, it writes the pointer to the exception to a completely different location.

I'm guessing that asjusting for the alignment may happen after calculating the `CatchObjOffset` in the exception data?

### PR DESCRIPTION
**Pull request by dpaoliello**
Fixes #146973

When an object with alignment requirements is placed on the stack, this causes a stack realignment which causes AArch64 to use x19 to refer to objects on the stack as there may be a gap between local variables and the Stack Pointer. This causes issues with the MSVC C++ exception personality as the offset to the catch object recorded in the handler table no longer matches the object being used in the catch block itself.

The fix for this is to place catch objects into the fixed object area.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64FrameLowering.cpp [hunk 1]
```diff
@@ -435,19 +435,38 @@ AArch64FrameLowering::getStackIDForScalableVectors() const {
...
-           alignTo(VarArgsArea + UnwindHelpObject, 16);
+    FixedObjectSize += AFI->getVarArgsGPRSize();
+
+    if (MF.hasEHFunclets()) {
+      // Catch objects are stored here in the primary function.
+      const MachineFrameInfo &MFI = MF.getFrameInfo();
+      const WinEHFuncInfo &EHInfo = *MF.getWinEHFuncInfo();
+      for (const WinEHTryBlockMapEntry &TBME : EHInfo.TryBlockMap) {
+        for (const WinEHHandlerType &H : TBME.HandlerArray) {
+          int FrameIndex = H.CatchObj.FrameIndex;
```
Comment (efriedma-quic) [inline llvm/lib/Target/AArch64/AArch64FrameLowering.cpp:459]: This looks like it can allocate space for the same FrameIndex multiple times?  I think a given FrameIndex can show up multple times in the TryBlockMap.  (See FunctionLoweringInfo::set)

Comment (dpaoliello) [reply llvm/lib/Target/AArch64/AArch64FrameLowering.cpp:459]: Good catch: yes, if the catchpads reuse the same alloca then we'd allocate too many fixed objects. I've fixed it for AArch64 and added a test, I'll create a followup PR to fix x64.

I couldn't figure out a way to make Clang generate this IR, so that could be a potential optimization (i.e., only emit one alloca for all by-reference and by-pointer catch blocks).

**Review by efriedma-quic — APPROVED** [review]
LGTM
