### PR TITLE
[clang-tidy] Fix false positive in bugprone-dynamic-static-initializers

### LINKED ISSUE #145680: [clang-tidy] False positives bugprone-dynamic-static-initializers
I believe the check warns incorrectly in the following cases:

```cpp
#include <limits>

template <typename T>
constexpr T kMin{std::numeric_limits<T>::min()};

template <int n>
struct X
{
  static constexpr int xn{n};
};
```

```bash
$ clang-tidy --checks=-*,bugprone-dynamic-static-initializers foo.hpp -- -fno-threadsafe-statics
589 warnings generated.
/tmp/foo.hpp:4:13: warning: static variable 'kMin' may be dynamically initialized in this header file [bugprone-dynamic-static-initializers]
    4 | constexpr T kMin{std::numeric_limits<T>::min()};
      |             ^
/tmp/foo.hpp:9:24: warning: static variable 'xn' may be dynamically initialized in this header file [bugprone-dynamic-static-initializers]
    9 |   static constexpr int xn{n};
      |                        ^

```

### PR DESCRIPTION
**Pull request by zeyi2**
Closes #145680

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/DynamicStaticInitializersCheck.cpp [hunk 1]
```diff
@@ -18,12 +18,11 @@ namespace clang::tidy::bugprone {
 namespace {
 
 AST_MATCHER(clang::VarDecl, hasConstantDeclaration) {
+  if (Node.isConstexpr())
+    return true;
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/bugprone/DynamicStaticInitializersCheck.cpp]: [[dcl.constexpr]](https://eel.is/c++draft/dcl.constexpr): "A constexpr variable shall be constant-initializable", so I think it is safe to early return it and would not introduce FPs/FNs. (If a variable is marked `constexpr` but fails to be constant-initializable, the code is ill-formed and compilation will fail, so clang will report error.)

Comment (zeyi2) [reply clang-tools-extra/clang-tidy/bugprone/DynamicStaticInitializersCheck.cpp]: A follow up TODO could be: add `constinit` support (>= C++20) for this check.

**Review by localspook — APPROVED** [review]

**Review by vbvictor — APPROVED** [review]
lgtm
