### PR TITLE
[Sema][CTAD] Allow user defined conversion for copy-list-initialization

### LINKED ISSUE #62925: Clang issue in CTAD
Clang fails to compile [cppreference example code](https://en.cppreference.com/w/cpp/container/map/deduction_guides). See [Compiler Explorer](https://godbolt.org/z/vYG5PxE5T).

### PR DESCRIPTION
**Pull request by spaits**
Fixes #62925.

The following code:
```cpp
#include <map>

int main() {
   std::map m1 = {std::pair{"foo", 2}, {"bar", 3}}; // guide #2
   std::map m2(m1.begin(), m1.end()); // guide #1
}
```
Is rejected by clang, but accepted by both gcc and msvc: https://godbolt.org/z/6v4fvabb5 .

So basically CTAD with copy-list-initialization is rejected.

Note that this exact code is also used in a cppreference article: https://en.cppreference.com/w/cpp/container/map/deduction_guides

I did some debugging and found out, that the reason why this does not work in clang is that, in the function `Sema::DeduceTemplateSpecializationFromInitializer` we explicitly suppress user conversion, if the initialization type is a copy initialization.

I checked the C++11 and C++20 standard drafts to see whether suppressing user conversion is the correct thing to do for user conversions. Based on the standard I don't think that it is correct.

```
13.3.1.4 Copy-initialization of class by user-defined conversion [over.match.copy]
Under the conditions specified in 8.5, as part of a copy-initialization of an object of class type, a user-defined
conversion can be invoked to convert an initializer expression to the type of the object being initialized.
Overload resolution is used to select the user-defined conversion to be invoked
```
So we could use user defined conversions according to the standard.

```
If a narrowing conversion is required to initialize any of the elements, the
program is ill-formed.
```
We should not do narrowing.

```
In copy-list-initialization, if an explicit constructor is chosen, the initialization is ill-formed.
```
We should not use explicit constructors.

Also a note:
In `InitializationKind::InitKind` there is no init kind called `IK_CopyList` but there is `IK_DirectList`, should we add `IK_CopyList`? Or it is unnecessary for now?

### CODE REVIEW

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+};
+
+template<class T, class Y>
+class A {
+  public:
+  A(std::initializer_list<Contained<T, Y> >, int) {}
+};
+
+int main() {
+    map mOk ={pair{5, 'a'}, {6, 'b'}, {7, 'c'}};
```
Comment (zyn0217) [inline clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:84]: Could you try to simplify the test case a bit? There is so much boilerplate that it's hard to understand the issue.

**Review by zyn0217 — COMMENTED** [review]
Thanks for working on this. While I didn't dig into the details in `DeduceTemplateSpecializationFromInitializer()`, I think the test could be improved before proceeding. I also wish @erichkeane and @hokein could take a look at this because they have more expertise in CTAD. :)

**Comment by spaits** [comment]
@zyn0217 Thank you for checking my PR. I was able to simplify the `std::initializer_list` definition. I have also created two different "categories" for the test. One test contains almost the exact code as the one in the reported issue with the same class names. The other one is there to test whether we can handle conversions correctly on multiple levels of nesting (one level deep and top level, I have added this since in the code in the issue everything interesting happens on the first level).

**Comment by spaits** [comment]
@zyn0217 @cor3ntin Sorry to ping you. Could you please take another look at this PR? Are my assumptions about the standard correct? Are the tests good now or I should make other changes?

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+  template <typename E>
+  struct initializer_list
+  {
+    const E *p;
+    size_t n;
+    initializer_list(const E *p, size_t n) : p(p), n(n) {}
+  };
+
+  struct string {
```
Comment (hokein) [inline clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:14]: nit: this is not used.

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+  // Verify that narrowing conversion is disabled in the first level of nesting.
+  std::map mNarrow = {std::pair{5, 'a'}, {6.0f, 'b'}, {7, 'c'}}; // expected-error {{type 'float' cannot be narrowed to 'int' in initializer list}} // expected-note {{insert an explicit cast to silence this issue}}
+}
+
+void testMultipleLevelNesting() {
+  A aOk = {{Contained{5, 'c'}, {5, 'c'}}, 5};
+
+  // Verify that narrowing conversion is disabled when it is not in a nested
+  // in another std::initializer_list, but it happens in the most outer one.
+  A aNarrowNested = {{Contained{5, 'c'}, {5.0f, 'c'}}, 5}; // expected-error {{type 'float' cannot be narrowed to 'int' in initializer list}} // expected-note {{insert an explicit cast to silence this issue}}
```
Comment (hokein) [inline clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:61]: Class `Contained` and `pair` look the same (also for `A` and `map`).

Can we reuse the `pair` and `map` to test the "mutiple level nesting" case?  e.g. `std::map mNaarowNested = {{Contained{5, 'c'}, {5.0f, 'c'}}, 5}};` (you probably need to add a constructor `map(std::initializer_list<pair<T, Y>>, int)`).

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp [hunk 4]
```diff
@@ -0,0 +1,65 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -Wno-unused-value -std=c++20 %s
```
Comment (hokein) [inline clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:1]: nit: please format the test file.

**Review by hokein — COMMENTED** [review]
The change looks good to me. Please add a note in `llvm-project/clang/docs/ReleaseNotes.rst`.

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp (hunk 3 above)
Comment (spaits) [reply clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp]: Removed `Contained` and `A`, now we only use `map` and `pair`.

File: clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp (hunk 4 above)
Comment (spaits) [reply clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:1]: Applied clang format, nothing has really changed. I have changed the formatting by hand at some places.

Comment (hokein) [reply clang/test/SemaCXX/ctad-copy-init-list-narrowing.cpp:1]: yeah, that's expected, we disable the clang-format for all lit test files (see the `clang/test/.clang-format`).

**Review by hokein — APPROVED** [review]
thanks, looks good.

**Comment by spaits** [comment]
> thanks, looks good.

Thank you for reviewing. When the CI run finishes and it is successful I will merge this PR.

File: clang/lib/Sema/SemaInit.cpp [hunk 5]
```diff
@@ -10892,8 +10892,6 @@ QualType Sema::DeduceTemplateSpecializationFromInitializer(
     // FIXME: The "second phase of [over.match.list] case can also
     // theoretically happen here, but it's not clear whether we can
     // ever have a parameter of the right type.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaInit.cpp:10894]: Is that comment still useful?

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -199,6 +199,12 @@ C++20 Feature Support
   to update the ``__cpp_concepts`` macro to `202002L`. This enables
   ``<expected>`` from libstdc++ to work correctly with Clang.
 
+- User defined constructors are allowed for copy-list-initialization with CTAD.
+  The example code for deduction guides for std::map in
+  (`cppreference <https://en.cppreference.com/w/cpp/container/map/deduction_guides>`_)
+  will now work.
+  (#GH62925).
+
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:207]: Not sure the link adds useful information. If you think the example is useful, feel free to add the examples in the release note directly (but the issue link is enough)

File: clang/lib/Sema/SemaInit.cpp (hunk 5 above)
Comment (spaits) [reply clang/lib/Sema/SemaInit.cpp:10894]: It wasn't useful (or at least I could definitely not understand why it was there) even when I was debugging to find the solution. Since I did not understand it I did not touch it.

What do you think could we remove it?

File: clang/docs/ReleaseNotes.rst (hunk 6 above)
Comment (spaits) [reply clang/docs/ReleaseNotes.rst:207]: I will change it so only the issue link is there.
