### PR TITLE
[flang][OpenMP] Fix crash when a sliced array is specified in a forall within a workshare construct

### LINKED ISSUE #143330: [Flang][OpenMP] Execution error when array assignment statement for an array containing ":" is specified in forall construct within workshare construct
```
Version of flang : 21.0.0(b68565b8c70fc590f8e59799996f450b1072b532)/AArch64
```

In the attached program (`snggw638_220.f90`), when `array assignment statement` for an array containing `":"` is specified in `forall construct` within `workshare construct`, the execution terminates abnormally.

Execution ends normally in the following cases:
- No compilation option (`-fopenmp`)
- Change the value specified for `OMP_NUM_THREAD` from `2` to `1`
- Change `":"` to array subscripts (`1` and `2`)
  see `snggw638_221.f90` below.
- Change `":"` to loop variable (`n0`) and add loop (`forall(n0=1:2) / end forall`)
  see `snggw638_222.f90` below.

The combination of `OpenMP workshare construct` and `array assignment statement` for an array containing  `":"` in `forall construct` does not appear to work correctly.

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

snggw638_220.f90:
```fortran
program main
  integer a1(2,1,3)
  a1 = 0
!$omp parallel
!$omp workshare
  forall (n1=1:1)
     forall (n2=1:3)
        a1(:,n1,n2) = a1(:,n1,n2)+1
     end forall
  end forall
!$omp end workshare
!$omp end parallel
  print *,'pass'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang -fopenmp snggw638_220.f90; ./a.out
Segmentation fault (core dumped)
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp snggw638_220.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp snggw638_220.f90; ./a.out
 pass
$
```

snggw638_221.f90:
```fortran
program main
  integer a1(2,1,3)
  a1 = 0
!$omp parallel
!$omp workshare
  forall (n1=1:1)
     forall (n2=1:3)
!        a1(:,n1,n2) = a1(:,n1,n2)+1
        a1(1,n1,n2) = a1(1,n1,n2)+1
        a1(2,n1,n2) = a1(2,n1,n2)+1
     end forall
  end forall
!$omp end workshare
!$omp end parallel
  print *,'pass'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang -fopenmp snggw638_221.f90; ./a.out
 pass
$
```

snggw638_222.f90:
```fortran
program main
  integer a1(2,1,3)
  a1 = 0
!$omp parallel
!$omp workshare
  forall (n0=1:2)
     forall (n1=1:1)
        forall (n2=1:3)
!           a1(:,n1,n2) = a1(:,n1,n2)+1
           a1(n0,n1,n2) = a1(n0,n1,n2)+1
        end forall
     end forall
  end forall
!$omp end workshare
!$omp end parallel
  print *,'pass'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang -fopenmp snggw638_222.f90; ./a.out
 pass
$
```

### PR DESCRIPTION
**Pull request by ceseo**
This is a fix for two problems that caused a crash:

1. Thread-local variables sometimes are required to be parallelized. Added a special case to handle this in `LowerWorkshare.cpp:isSafeToParallelize`.
2. Race condition caused by a `nowait` added to the `omp.workshare` if it is the last operation in a block. This allowed multiple threads to execute the `omp.workshare` region concurrently. Since _FortranAPushValue modifies a shared stack, this concurrent access causes a crash. Disable the addition of `nowait` and rely on the implicit barrier at the the of the `omp.workshare` region.

Fixes #143330

### CODE REVIEW

File: flang/lib/Optimizer/OpenMP/LowerWorkshare.cpp [hunk 1]
```diff
@@ -335,6 +375,11 @@ static void parallelizeRegion(Region &sourceRegion, Region &targetRegion,
 
     for (auto [i, opOrSingle] : llvm::enumerate(regions)) {
       bool isLast = i + 1 == regions.size();
+      // Make sure shared runtime calls are synchronized: disable `nowait`
+      // insertion, and rely on the implicit barrier at the end of the
+      // omp.workshare block.
+      if (isa<fir::DoLoopOp>(block.getParentOp()))
```
Comment (tblah) [inline flang/lib/Optimizer/OpenMP/LowerWorkshare.cpp]: Why should this only apply for do-loops?

**Review by tblah — COMMENTED** [review]
Thank you for the bug fix, but I'm not sure this is right yet.

The problem you describe seems to indicate that it is not safe to parallelise when forall/where need to use the runtime stack (for example the call you mentioned). I'm not sure if removing nowait is the right fix.

Please could you add lit tests demonstrating the changes (perhaps based on the issue). Perhaps with some IR it would be clearer why nowait helps (and regression tests are good in themselves).

**Comment by ceseo** [comment]
> Please could you add lit tests demonstrating the changes (perhaps based on the issue). Perhaps with some IR it would be clearer why nowait helps (and regression tests are good in themselves).

The problem is that the issue is intermittent (you make it happen almost all the time if you increase OMP_NUM_THREADS to very large number, but not guaranteed to fail). If it happens, I can see the problematic IR.

If you have any suggestions on how to test it (or, even better, make the problem consistently happen), I'm open to suggestions.

**Comment by ceseo** [comment]
Ah, now I understand what you meant. Sorry, I misread that. 

I'll add a new test.

**Review by tblah — COMMENTED** [review]
Thanks for adding the tests. These make a lot more sense to me now.

Trying some trivial fortran examples don't work so well as the tests given. For example
```
subroutine demo
  integer :: x
  x = 0
  !$omp parallel private(x)
    !$omp workshare
      x = 1 ! omp.single is generated for this
    !$omp end workshare
  !$omp end parallel
end subroutine
```

**Comment by ceseo** [comment]
> Thanks for adding the tests. These make a lot more sense to me now.
> 
> Trying some trivial fortran examples don't work so well as the tests given. For example
> 
> ```
> subroutine demo
>   integer :: x
>   x = 0
>   !$omp parallel private(x)
>     !$omp workshare
>       x = 1 ! omp.single is generated for this
>     !$omp end workshare
>   !$omp end parallel
> end subroutine
> ```

Thanks! Let me check this.

**Review by tblah — APPROVED** [review]
LGTM. Thank you for sticking with the fix.
