### PR TITLE
[clang-format] Propagate `LeadingEmptyLinesAffected` when joining lines

### LINKED ISSUE #138942: [clang-format] unexpected formatting on empty lines
command `clang-format --lines=2:2 a.cc`

actual formatting:
```cpp
void f() {
  
}
```

expected formatting:
```cpp
void f() {}
```

this seems to be WAI if there are tokens on line 2, e.g:
```cpp
void f() {
  return;
}
```

gets formatted as `void f() { return; }`.

### PR DESCRIPTION
**Pull request by tJener**
Before this commit, when `LineJoiner` joins a line with affected leading whitespace, it would drop the knowledge of this entirely. However, when the `AffectedRangeManager` is computing the affected lines, the leading empty whitespace lines are potentially considered for non-first tokens in the `AnnotatedLine`. This causes a discrepancy in behavior when an `AnnotatedLine` is put together from joining multiple lines versus when it is not.

We change `LineJoiner::join` to follow `AffectedRangeManager`'s logic, considering the leading whitespace when determining `Affected` for a token if the previous token did not have children.

https://github.com/llvm/llvm-project/blob/a63f57262898588b576d66e5fd79c0aa64b35f2d/clang/lib/Format/AffectedRangeManager.cpp#L111-L130

Fixes #138942.

### CODE REVIEW

File: clang/lib/Format/UnwrappedLineFormatter.cpp [hunk 1]
```diff
@@ -988,6 +988,8 @@ class LineJoiner {
     assert(!B.First->Previous);
     if (B.Affected)
       A.Affected = true;
+    else if (B.LeadingEmptyLinesAffected && A.Last->Children.empty())
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/UnwrappedLineFormatter.cpp]:
```suggestion
    if (B.Affected || (B.LeadingEmptyLinesAffected && A.Last->Children.empty()))
```

Comment (tJener) [reply clang/lib/Format/UnwrappedLineFormatter.cpp]: Done.

**Review by HazardyKnusperkeks — APPROVED** [review]
Please wait a few days, or until another approval.

File: clang/unittests/Format/FormatTestSelective.cpp [hunk 2]
```diff
@@ -41,6 +41,8 @@ TEST_F(FormatTestSelective, RemovesTrailingWhitespaceOfFormattedLine) {
   EXPECT_EQ("int a;", format("int a;         ", 0, 0));
   EXPECT_EQ("int a;\n", format("int a;  \n   \n   \n ", 0, 0));
   EXPECT_EQ("int a;\nint b;    ", format("int a;  \nint b;    ", 0, 0));
+
+  EXPECT_EQ("void f() {}\n", format("void f() {\n  \n}\n", 11, 0));
```
Comment (owenca) [inline clang/unittests/Format/FormatTestSelective.cpp]:
```suggestion
  EXPECT_EQ("void f() {}", format("void f() {\n"
                                  "  \n"
                                  "}",
                                  11, 0));
```

File: clang/lib/Format/UnwrappedLineFormatter.cpp [hunk 3]
```diff
@@ -986,7 +986,7 @@ class LineJoiner {
   void join(AnnotatedLine &A, const AnnotatedLine &B) {
     assert(!A.Last->Next);
     assert(!B.First->Previous);
-    if (B.Affected)
+    if (B.Affected || (B.LeadingEmptyLinesAffected && A.Last->Children.empty()))
```
Comment (owenca) [inline clang/lib/Format/UnwrappedLineFormatter.cpp]: Can you add a test case for `A.Last->Children.empty()` being false?

Comment (tJener) [reply clang/lib/Format/UnwrappedLineFormatter.cpp]: I'm not familiar with when the current implementation would merge two lines where `!A.Last->Children.empty()`. Do you have any suggestions?

Comment (owenca) [inline clang/lib/Format/UnwrappedLineFormatter.cpp]:
```suggestion
    if (B.Affected || B.LeadingEmptyLinesAffected)
```
Would that be enough?

Comment (tJener) [reply clang/lib/Format/UnwrappedLineFormatter.cpp]: I suppose it depends. It's unclear to me what the contract of `join` is supposed to be. If it is supposed to merge two arbitrary `AnnotatedLine`s, then it seems like we should keep the check for `Children.empty()` in order to be consistent with `AffectedRangeManager`. If instead one of the preconditions for `join` is that `A.Last->Children.empty()`, then I'd rather assert on that instead of only dropping the condition on the `if`.

That said, I'm just trying to fix a bug that's blocking progress on other stuff, so I'll just do whatever you want me to do here.

Comment (owenca) [reply clang/lib/Format/UnwrappedLineFormatter.cpp]: Either dropping the condition with a comment, or adding an assertion would be fine by me. For example,
```cc
    if (B.Affected || B.LeadingEmptyLinesAffected) {
      assert(B.Affected || A.Last->Children.empty());
```

Comment (tJener) [reply clang/lib/Format/UnwrappedLineFormatter.cpp]: Done.

**Review by owenca — APPROVED** [review]
