### PR TITLE
[clang][aarch64] Add support for the MSVC qualifiers __ptr32, __ptr64, __sptr, __uptr for AArch64

### LINKED ISSUE #62536: [clang] 32bit pointer (-fms-extensions __ptr32 __uptr) has no effect in ARM64
### Problem
The 32-bit pointer does not work on platforms other than x64, such as Arm64. See the [Godbolt listing](https://godbolt.org/z/55h65crqj).

### Sample
```cpp
#include <cstdint>

int param_std(int* foo) {
    int temp = *foo;
    *foo = 1;
    return temp + sizeof(foo);
}

int param_ptr32(int* __ptr32 __uptr bar) {
    int temp = *bar;
    *bar = 2;
    return temp + sizeof(bar);
}

int emulate_ptr32(uint32_t baz) {
    uint64_t baz64 = baz;
    int* bazptr = (int*)baz64;
    int temp = *bazptr;
    *bazptr = 3;
    return temp + sizeof(baz);
}
```

### Conclusions
The `param_ptr32` disassembler must be equal to `emulate_ptr32`, and different from `param_std`. Based on the [Godbolt listing](https://godbolt.org/z/55h65crqj), the MSVC compiler does just that. But Clang does not take into account the 32-bit pointer under Arm64 (and most likely under other than x64). Its size is 8 bytes, disassembler `param_std` and `param_ptr32` are the same.

### PR DESCRIPTION
**Pull request by dpaoliello**
MSVC has a set of qualifiers to allow using 32-bit signed/unsigned pointers when building 64-bit targets. This is useful for WoW code (i.e., the part of Windows that handles running 32-bit application on a 64-bit OS). Currently this is supported on x64 using the 270, 271 and 272 address spaces, but does not work for AArch64 at all.

This change adds the same 270, 271 and 272 address spaces to AArch64 and adjusts the data layout string accordingly. Clang will generate the correct address space casts, but these will currently be ignored until the AArch64 backend is updated to handle them.

Partially fixes #62536

This is a resurrected version of <https://reviews.llvm.org/D158857> (originally created by @a_vorobev) - I've cleaned it up a little, fixed the rest of the tests and added to auto-upgrade for the data layout.

### CODE REVIEW

File: llvm/lib/IR/AutoUpgrade.cpp [hunk 1]
```diff
@@ -5570,15 +5583,7 @@ std::string llvm::UpgradeDataLayoutString(StringRef DL, StringRef TT) {
...
-  // If the datalayout matches the expected format, add pointer size address
-  // spaces to the datalayout.
-  std::string AddrSpaces = "-p270:32:32-p271:32:32-p272:64:64";
-  if (StringRef Ref = Res; !Ref.contains(AddrSpaces)) {
-    SmallVector<StringRef, 4> Groups;
-    Regex R("(e-m:[a-z](-p:32:32)?)(-[if]64:.*$)");
-    if (R.match(Res, &Groups))
-      Res = (Groups[1] + AddrSpaces + Groups[3]).str();
-  }
+  AddPtr32Ptr64AddrSpaces();
```
Comment (rnk) [inline llvm/lib/IR/AutoUpgrade.cpp:5586]: I vaguely recall that the autoupgrade was somewhat painful for x86 usage, but I don't have anything specific, and we're just doing exactly the same stuff. @efriedma-quic are there any lessons learned there that we should keep in mind?

File: clang/lib/Basic/Targets/AArch64.h [hunk 2]
```diff
@@ -32,6 +58,8 @@ class LLVM_LIBRARY_VISIBILITY AArch64TargetInfo : public TargetInfo {
     SveMode = (1 << 2),
   };
 
+  enum AddrSpace { ptr32_sptr = 270, ptr32_uptr = 271, ptr64 = 272 };
```
Comment (rnk) [inline clang/lib/Basic/Targets/AArch64.h:61]: This is kind of nitty, but if you move this up to global scope and give it an AArch64-prefixed name you can use `static_cast<unsigned>(AArch64::ptr32_sptr)` in place for 270 etc above.

**Review by rnk — COMMENTED** [review]
Makes sense to me. 

cc @amykhuang

File: clang/lib/Basic/Targets/AArch64.h (hunk 2 above)
Comment (dpaoliello) [reply clang/lib/Basic/Targets/AArch64.h]: Definitely prefer that - this whole thing has **way** too many magic numbers for my liking...

File: llvm/lib/IR/AutoUpgrade.cpp (hunk 1 above)
Comment (efriedma-quic) [reply llvm/lib/IR/AutoUpgrade.cpp:5604]: If there isn't any existing code using the new address-spaces, autoupgrading like this should work smoothly, I think?  Need to make sure the autoupgraded string matches the new string, but otherwise should be fine.  (I remember last time we made major changes for x86, the 128-bit integer alignment change, it was sort of tricky, but the issue mostly wasn't the layout string itself.)

--------

Having a dedicated address-space for __ptr64 is a little strange, but I guess if that's what we did on x86, there isn't really a reason to deviate.

File: clang/test/CodeGen/ms-mixed-ptr-sizes.c [hunk 3]
```diff
@@ -1,5 +1,6 @@
 // RUN: %clang_cc1 -triple x86_64-windows-msvc -fms-extensions -emit-llvm -O2 < %s | FileCheck %s --check-prefixes=X64,ALL
 // RUN: %clang_cc1 -triple i386-pc-win32 -fms-extensions -emit-llvm -O2 < %s | FileCheck %s --check-prefixes=X86,ALL
+// RUN: %clang_cc1 -triple aarch64-windows-msvc -fms-extensions -emit-llvm -O2 < %s | FileCheck %s --check-prefixes=AARCH64,ALL
```
Comment (efriedma-quic) [inline clang/test/CodeGen/ms-mixed-ptr-sizes.c:3]: Do we also need some tests in the backend?  I guess most things likely work because we already did most of the work for the aarch64_32 ABI, but I'd like to see some tests that the basics work (load/store/arguments/return values).

Comment (dpaoliello) [reply clang/test/CodeGen/ms-mixed-ptr-sizes.c:3]: Backend hasn't been implemented yet - I'll have a follow up PR with the changes and tests.

**Comment by dpaoliello** [comment]
> Need to make sure the autoupgraded string matches the new string, but otherwise should be fine. (I remember last time we made major changes for x86, the 128-bit integer alignment change, it was sort of tricky, but the issue mostly wasn't the layout string itself.)

There are tests for this - I also hit an issue with an unrelated test due to data layout upgrading not working correctly, so I added this to the auto-upgrade tests as well.

**Review by efriedma-quic — APPROVED** [review]
LGTM
