### PR TITLE
[clang-tidy][misc-const-correctness] fix fp when using const array type.

### LINKED ISSUE #132931: clang-tidy suggests adding const to arrays that are already const
Given the C++ code
```c++
int foo(int i) {
    const int array[] = {1, 2, 3};
    return array[i];
}
```
The clang-tidy `misc-const-correctness` check reports:
```
$ clang-tidy-21 --checks=misc-const-correctness test.cc
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "test.cc"
No compilation database found in /home/harald or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
1 warning generated.
/home/harald/test.cc:2:5: warning: variable 'array' of type 'const int[3]' can be declared 'const' [misc-const-correctness]
    2 |     const int array[] = {1, 2, 3};
      |     ^
      |               const
$ dpkg -l clang-tidy-21
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                                                      Architecture Description
+++-==============-============================================================-============-=================================
ii  clang-tidy-21  1:21~++20250324083552+ec9546d16994-1~exp1~20250324083607.329 amd64        clang-based C++ linter tool
```
Or see it online at https://godbolt.org/z/f6c8E8eeE

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixed: #132931
const array is immutable in C/C++ language design, we don't need to
check constness for it.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp [hunk 1]
```diff
@@ -161,6 +163,7 @@ void ConstCorrectnessCheck::check(const MatchFinder::MatchResult &Result) {
 
   VariableCategory VC = VariableCategory::Value;
   const QualType VT = Variable->getType();
+  VT->dump();
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:166]: Is this left unintentionally?

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp [hunk 2]
```diff
@@ -169,6 +172,7 @@ void ConstCorrectnessCheck::check(const MatchFinder::MatchResult &Result) {
     if (ArrayT->getElementType()->isPointerType())
       VC = VariableCategory::Pointer;
   }
+  llvm::errs() << (int)VC << "\n";
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:175]: This also unintentionally?

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp (hunk 1 above)
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:166]:
```suggestion
```

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp (hunk 2 above)
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:175]:
```suggestion
```

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp [hunk 3]
```diff
@@ -89,6 +89,8 @@ void ConstCorrectnessCheck::registerMatchers(MatchFinder *Finder) {
   const auto ConstReference = hasType(references(isConstQualified()));
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:89]: On line 86 it appears the author intended to handle "const arrays" in the "pointee check". They are indeed handled correctly if one of the options is true (I don't recall which one). Is there a bug in that check that we should fix instead?

Comment (carlosgalvezp) [reply clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:89]: Alternatively we might want to correct/remove the comment

**Review by carlosgalvezp — COMMENTED** [review]
LGTM, minor comment/question!

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp (hunk 3 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:89]: I think the comment means check the constness of pointer and array instead of const pointer and const array

File: clang-tools-extra/test/clang-tidy/checkers/misc/const-correctness-values.cpp [hunk 4]
```diff
@@ -1007,3 +1007,11 @@ template <typename T> void f() {
   x[T{}] = 3;
 }
 } // namespace gh127776_false_positive
+
+namespace gh132931_false_positive {
+using T = const int;
+void valid(int i) {
+  const int arr0[] = {1, 2, 3};
+  T arr1[] = {1, 2, 3};
```
Comment (carlosgalvezp) [inline clang-tools-extra/test/clang-tidy/checkers/misc/const-correctness-values.cpp:1015]: Shouldn't we get a warning here, since `arr1` is not used and can therefore be const?

Comment (carlosgalvezp) [reply clang-tools-extra/test/clang-tidy/checkers/misc/const-correctness-values.cpp:1015]: Ah sorry I see now `T` is `const int` :man_facepalming:

File: clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp (hunk 3 above)
Comment (carlosgalvezp) [reply clang-tools-extra/clang-tidy/misc/ConstCorrectnessCheck.cpp:89]: All the tests (including the FP at hand) pass if you remove `unless(arrayType()` from line 87 (as well as the part of the comment), so I think it would be preferable to do that instead of creating a `ConstArrayType`.

**Review by carlosgalvezp — APPROVED** [review]
LGTM!
