### PR TITLE
[Clang] Preserve CXXParenListInitExpr in TreeTransform.

### LINKED ISSUE #72880: Clang crashes while compiling my project
CLang version: 16.0.5, using MSVC-like command line. This project compiles ok using MSVC compiler, with the same arguments.

[SourcesAndTrace.zip](https://github.com/llvm/llvm-project/files/13498012/SourcesAndTrace.zip)

### PR DESCRIPTION
**Pull request by cor3ntin**
We were converting a CXXParenListInitExpr to a ParenListExpr in TreeTransform.

However, ParenListExpr is typeless, so Clang could not rebuild the correct initialization sequence in some contexts.

Fixes #72880

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -16487,12 +16501,22 @@ ExprResult
 TreeTransform<Derived>::TransformCXXParenListInitExpr(CXXParenListInitExpr *E) {
   SmallVector<Expr *, 4> TransformedInits;
   ArrayRef<Expr *> InitExprs = E->getInitExprs();
-  if (TransformExprs(InitExprs.data(), InitExprs.size(), true,
-                     TransformedInits))
+
+  QualType T = getDerived().TransformType(E->getType());
+
+  bool ArgChanged = false;
+  ;
```
Comment (erichkeane) [inline clang/lib/Sema/TreeTransform.h:16508]: extra semicolon for no reason?

**Review by erichkeane — APPROVED** [review]
Please change the commit message to do Fixes #<whatever> instead of the reverse, so this actually closes the bug :)

File: clang/lib/Sema/TreeTransform.h [hunk 2]
```diff
@@ -16487,12 +16501,22 @@ ExprResult
...
+
+  if (getDerived().TransformExprs(InitExprs.data(), InitExprs.size(), true,
+                                  TransformedInits, &ArgChanged))
     return ExprError();
 
-  return getDerived().RebuildParenListExpr(E->getBeginLoc(), TransformedInits,
-                                           E->getEndLoc());
+  if (!ArgChanged && T == E->getType())
+    return E;
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:16515]: Do we want to handle AlwaysRebuild?

**Review by zyn0217 — APPROVED** [review]

**Comment by alexfh** [comment]
@cor3ntin this commit causes an assertion failure: https://gcc.godbolt.org/z/7hW4ssrfq
```
$ cat test.cc
struct E {
  virtual void f();
};
struct G {
  E e;
};
template <typename>
struct Test {
  virtual void f() {
    E e;
    G g(e);
  }
};
auto *t = new Test<int>;

$ ./clang-bad -c -o /dev/null -std=c++20 test.cc
assertion failed at clang/lib/CodeGen/CGExprAgg.cpp:2303 in void clang::CodeGen::CodeGenFunction::EmitAggregateCopy(LValue, LValue, QualType, AggValueSlot::Overlap_t, bool): (Record->hasTrivialCopyConstructor() || Record->hasTrivialCopyAssignment() || Record->hasTrivialMoveConstructor() || Record->hasTrivialMoveAssignment() || Record->hasAttr<TrivialABIAttr>() || Record->isUnion()) && "Trying to aggregate-copy a type without a trivial copy/move " "constructor or assignment operator"
    @     0x55e4e4e3cfe4  __assert_fail
    @     0x55e4df16f247  clang::CodeGen::CodeGenFunction::EmitAggregateCopy()
    @     0x55e4df175f3e  (anonymous namespace)::AggExprEmitter::EmitCopy()
    @     0x55e4df16e4b6  (anonymous namespace)::AggExprEmitter::EmitFinalDestCopy()
    @     0x55e4df1762dc  (anonymous namespace)::AggExprEmitter::EmitAggLoadOfLValue()
    @     0x55e4df16de02  clang::CodeGen::CodeGenFunction::EmitAggExpr()
    @     0x55e4df00e593  clang::CodeGen::CodeGenFunction::EmitInitializationToLValue()
    @     0x55e4df177fea  (anonymous namespace)::AggExprEmitter::VisitCXXParenListOrInitListExpr()
    @     0x55e4df16de02  clang::CodeGen::CodeGenFunction::EmitAggExpr()
    @     0x55e4df08640c  clang::CodeGen::CodeGenFunction::EmitExprAsInit()
    @     0x55e4df08314b  clang::CodeGen::CodeGenFunction::EmitAutoVarInit()
    @     0x55e4df07bfe7  clang::CodeGen::CodeGenFunction::EmitVarDecl()
    @     0x55e4df07ba62  clang::CodeGen::CodeGenFunction::EmitDecl()
    @     0x55e4df115940  clang::CodeGen::CodeGenFunction::EmitDeclStmt()
    @     0x55e4df10a5de  clang::CodeGen::CodeGenFunction::EmitSimpleStmt()
    @     0x55e4df10983f  clang::CodeGen::CodeGenFunction::EmitStmt()
    @     0x55e4df116d61  clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope()
    @     0x55e4df2725f4  clang::CodeGen::CodeGenFunction::GenerateCode()
    @     0x55e4df29cd88  clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition()
    @     0x55e4df293f22  clang::CodeGen::CodeGenModule::EmitGlobalDefinition()
    @     0x55e4df284de2  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x55e4df284dfe  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x55e4df284dfe  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x55e4df281a2d  clang::CodeGen::CodeGenModule::Release()
    @     0x55e4df3c750e  (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit()
    @     0x55e4def2ef1a  clang::BackendConsumer::HandleTranslationUnit()
    @     0x55e4dfe45d68  clang::ParseAST()
    @     0x55e4dfb7e7aa  clang::FrontendAction::Execute()
    @     0x55e4dfaf319d  clang::CompilerInstance::ExecuteAction()
    @     0x55e4def2e4ab  clang::ExecuteCompilerInvocation()
    @     0x55e4def21f17  cc1_main()
```

Actually, I can reproduce the assertion failure in Clang before this commit using a different example, but I haven't yet reduced it. It might be a distinct problem though despite the same assertion failure.

**Comment by alexfh** [comment]
@cor3ntin yep, the second test case I have doesn't seem to be directly related. It causes crashes to Clang since version 7: https://gcc.godbolt.org/z/6M13c4q3T

**Comment by alexfh** [comment]
I've filed https://github.com/llvm/llvm-project/issues/141242 for the second report. However https://github.com/llvm/llvm-project/pull/138518#issuecomment-2903017423 is new and still needs to be addressed.

**Comment by alexfh** [comment]
Apart from the assertion failure in CodeGen, we have two distinct test cases that started failing after this commit. The code in both cases is sanitizer-clean and looks valid. The failures reproduce with -O0, so it's not about optimizations. Looks like Clang codegen is broken for these cases. Reducing the test cases is not as easy as with Clang assertion failures, but I'll try to produce a test case early next week. So far I just managed to compare x86 assembly produced by clang -O0 without this commit and with it. The diff boils down to a few instances of
```
-       movq    $0, (%rsi)
+       movl    $0, (%rsi)
```

**Comment by alexfh** [comment]
@cor3ntin ^^

**Comment by alexfh** [comment]
@cor3ntin friendly ping. Please take a look at the remaining issue here. Thanks!

**Comment by cor3ntin** [comment]
@alexfh I don't have the resources to look into this issue. Please revert if you need to.

**Comment by erichkeane** [comment]
> @alexfh I don't have the resources to look into this issue. Please revert if you need to.

This has been in trunk for a long time, a revert here would be HIGHLY unfortunate.  I would vastly prefer someone spend time trying to figure out why we are confused with the variable init here instead.  So:

`q.Push(new Node(0));`

Seems to be the line that isn't producing the same value.  We're initializing it with an int instead of a 64-bit-`long`.  I see here:
https://godbolt.org/z/KofsM8hdj

```
|               `-CXXMemberCallExpr <line:47:5, col:23> 'void'
|                 |-MemberExpr <col:5, col:7> '<bound member function type>' .Push 0x28726e38
|                 | `-DeclRefExpr <col:5> 'IntrusiveMPSCQueue' lvalue Var 0x28735d18 'q' 'IntrusiveMPSCQueue' refers_to_enclosing_variable_or_capture
|                 `-CXXNewExpr <col:12, col:22> 'Node *' Function 0x28731c68 'operator new' 'void *(unsigned long)'
|                   `-CXXParenListInitExpr <col:20, col:22> 'Node'
|                     |-IntegerLiteral <col:21> 'int' 0
```

IN a non-template version (i removed the template head itself), we get:
```
|               `-CXXNewExpr <col:12, col:22> 'Node *' Function 0x22566848 'operator new' 'void *(unsigned long)'
|                 `-CXXParenListInitExpr <col:20, col:22> 'Node'
|                   |-ImplicitCastExpr <col:21> 'long' <IntegralCast>
|                   | `-IntegerLiteral <col:21> 'int' 0
|                   `-ImplicitValueInitExpr 'Node *'
```

In the primary template we have:

```
| |       |       `-CXXNewExpr <col:12, col:22> 'Node *' Function 0x22566848 'operator new' 'void *(unsigned long)'
| |       |         `-CXXParenListInitExpr <col:20, col:22> 'Node'
| |       |           |-ImplicitCastExpr <col:21> 'long' <IntegralCast>
| |       |           | `-IntegerLiteral <col:21> 'int' 0
```

SO something about instantiating the expressions lost their cast?  I'm not sure how that happens?

**Comment by alexfh** [comment]
> > @alexfh I don't have the resources to look into this issue. Please revert if you need to.
> 
> This has been in trunk for a long time, a revert here would be HIGHLY unfortunate. I would vastly prefer someone spend time trying to figure out why we are confused with the variable init here instead.

It would be really unfortunate indeed, if we have to revert this. But that's a clearly incorrect codegen, so the only alternative is to get a fix.

I looked a bit into this and came up with a slightly more compact test case: https://gcc.godbolt.org/z/Pcj8954Ye
```
struct Node {
  long val;
};
void Push(Node *);
template <bool>
void BatchPull() {
    Push(new Node(0));
}
void TestBody() {
    (void)BatchPull<true>; 
}
```
Similarly to https://github.com/llvm/llvm-project/pull/138518#issuecomment-2930816205, AST dump already shows the problem (https://godbolt.org/z/PYeG1v5Yz) - `ImplicitCastExpr` to `long` is dropped from the template instantiation:
```
|-FunctionTemplateDecl <line:5:1, line:8:1> line:6:6 BatchPull
| |-NonTypeTemplateParmDecl <line:5:11> col:15 'bool' depth 0 index 0
| |-FunctionDecl <line:6:1, line:8:1> line:6:6 BatchPull 'void ()'
| | `-CompoundStmt <col:18, line:8:1>
| |   `-CallExpr <line:7:5, col:21> 'void'
| |     |-ImplicitCastExpr <col:5> 'void (*)(Node *)' <FunctionToPointerDecay>
| |     | `-DeclRefExpr <col:5> 'void (Node *)' lvalue Function 0x389dae98 'Push' 'void (Node *)'
| |     `-CXXNewExpr <col:10, col:20> 'Node *' Function 0x389db540 'operator new' 'void *(unsigned long)'
| |       `-CXXParenListInitExpr <col:18, col:20> 'Node'
| |         `-ImplicitCastExpr <col:19> 'long' <IntegralCast>
| |           `-IntegerLiteral <col:19> 'int' 0
| `-FunctionDecl <line:6:1, line:8:1> line:6:6 used BatchPull 'void ()' implicit_instantiation
|   |-TemplateArgument integral 'true'
|   `-CompoundStmt <col:18, line:8:1>
|     `-CallExpr <line:7:5, col:21> 'void'
|       |-ImplicitCastExpr <col:5> 'void (*)(Node *)' <FunctionToPointerDecay>
|       | `-DeclRefExpr <col:5> 'void (Node *)' lvalue Function 0x389dae98 'Push' 'void (Node *)'
|       `-CXXNewExpr <col:10, col:20> 'Node *' Function 0x389db540 'operator new' 'void *(unsigned long)'
|         `-CXXParenListInitExpr <col:18, col:20> 'Node'
|           `-IntegerLiteral <col:19> 'int' 0
```

I'm trying to figure out how this commit affects the relevant template instantiation logic, but no ideas so far.

**Comment by alexfh** [comment]
Before this change the cast used to be added here:
```
* thread #1, name = 'clang', stop reason = step over
    frame #0: 0x00005555667e8ff2 clang`clang::Sema::BuildCXXNew(this=0x00005092ffd24000, Range=SourceRange @ 0x00007ffffffef4f8, UseGlobal=false, PlacementLParen=(ID = 94), PlacementArgs=clang::MultiExprArg @ 0x00007ffffffef4e0, PlacementRParen=(ID = 94), TypeIdParens=SourceRange @ 0x00007ffffffef548, AllocType=QualType @ 0x00007ffffffef4d0, AllocTypeInfo=0x00005092ffd23a28, ArraySize= Has Value=false , DirectInitRange=SourceRange @ 0x00007ffffffef570, Initializer=0x00005092ffd66230) at SemaExprCXX.cpp:2591:18
   2588       = InitializedEntity::InitializeNew(StartLoc, InitType);
   2589     InitializationSequence InitSeq(*this, Entity, Kind, Exprs);
   2590     ExprResult FullInit = InitSeq.Perform(*this, Entity, Kind, Exprs);
-> 2591     if (FullInit.isInvalid())
   2592       return ExprError();
   2593
   2594     // FullInit is our initializer; strip off CXXBindTemporaryExprs, because
(lldb) p Exprs[0]->dump()
IntegerLiteral 0x5092ffd239e8 'int' 0
(lldb) p FullInit.get()->dump()
CXXParenListInitExpr 0x5092ffd66268 'Node':'struct Node'
`-ImplicitCastExpr 0x5092ffd66250 'long' <IntegralCast>
  `-IntegerLiteral 0x5092ffd239e8 'int' 0
```
Now this doesn't happen:
```
* thread #1, name = 'clang', stop reason = step over
    frame #0: 0x0000555566a23c92 clang`clang::Sema::BuildCXXNew(this=0x00005092ffd26000, Range=SourceRange @ 0x00007ffffffef458, UseGlobal=false, PlacementLParen=(ID = 94), PlacementArgs=clang::MultiExprArg @ 0x00007ffffffef440, PlacementRParen=(ID = 94), TypeIdParens=SourceRange @ 0x00007ffffffef4a8, AllocType=QualType @ 0x00007ffffffef430, AllocTypeInfo=0x00005092ffd25a28, ArraySize= Has Value=false , DirectInitRange=SourceRange @ 0x00007ffffffef4d0, Initializer=0x00005092ffd6b230) at SemaExprCXX.cpp:2584:18
   2581       = InitializedEntity::InitializeNew(StartLoc, InitType);
   2582     InitializationSequence InitSeq(*this, Entity, Kind, Exprs);
   2583     ExprResult FullInit = InitSeq.Perform(*this, Entity, Kind, Exprs);
-> 2584     if (FullInit.isInvalid())
   2585       return ExprError();
   2586
   2587     // FullInit is our initializer; strip off CXXBindTemporaryExprs, because
(lldb) p Exprs.size()
(size_t) 1
(lldb) p Exprs[0]->dump()
CXXParenListInitExpr 0x5092ffd6b230 'Node':'struct Node'
`-IntegerLiteral 0x5092ffd259e8 'int' 0
(lldb) p FullInit.get()->dump()
CXXParenListInitExpr 0x5092ffd6b230 'Node':'struct Node'
`-IntegerLiteral 0x5092ffd259e8 'int' 0
```
(probably because the argument of a `new` is a `CXXParenListInitExpr` rather than an `IntegerLiteral`).

In both cases this is happening here:
```
(lldb) bt
* thread #1, name = 'clang', stop reason = step over
  * frame #0: 0x00005555667e8ff2 clang`clang::Sema::BuildCXXNew(this=0x00005092ffd24000, Range=SourceRange @ 0x00007ffffffef4f8, UseGlobal=false, PlacementLParen=(ID = 94), PlacementArgs=clang::MultiExprArg @ 0x00007ffffffef4e0, PlacementRParen=(ID = 94), TypeIdParens=SourceRange @ 0x00007ffffffef548, AllocType=QualType @ 0x00007ffffffef4d0, AllocTypeInfo=0x00005092ffd23a28, ArraySize= Has Value=false , DirectInitRange=SourceRange @ 0x00007ffffffef570, Initializer=0x00005092ffd66230) at SemaExprCXX.cpp:2591:18
frame #1: 0x000055556756d373 clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::RebuildCXXNewExpr(this=0x00007fffffff1640, StartLoc=(ID = 94), UseGlobal=false, PlacementLParen=(ID = 94), PlacementArgs=clang::MultiExprArg @ 0x00007ffffffef610, PlacementRParen=(ID = 94), TypeIdParens=SourceRange @ 0x00007ffffffef668, AllocatedType=QualType @ 0x00007ffffffef600, AllocatedTypeInfo=0x00005092ffd23a28, ArraySize= Has Value=false , DirectInitRange=SourceRange @ 0x00007ffffffef690, Initializer=0x00005092ffd66230) at TreeTransform.h:3442:22
    frame #2: 0x000055556754f773 clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCXXNewExpr(this=0x00007fffffff1640, E=0x00005092ffd64cf8) at TreeTransform.h:14541:23
    frame #3: 0x0000555567530256 clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(this=0x00007fffffff1640, E=0x00005092ffd64cf8) at StmtNodes.inc:718:1
    frame #4: 0x0000555567530f17 clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformInitializer(this=0x00007fffffff1640, Init=0x00005092ffd64cf8, NotCopyInit=false) at TreeTransform.h:4375:25
    frame #5: 0x000055556753212c clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExprs(this=0x00007fffffff1640, Inputs=0x00005092ffd64df8, NumInputs=1, IsCall=true, Outputs=0x00007fffffff0628, ArgChanged=0x00007fffffff067f) at TreeTransform.h:4531:29
    frame #6: 0x000055556754ae51 clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(this=0x00007fffffff1640, E=0x00005092ffd64dd8) at TreeTransform.h:13380:20
    frame #7: 0x000055556752fe5a clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(this=0x00007fffffff1640, E=0x00005092ffd64dd8) at StmtNodes.inc:614:1
    frame #8: 0x000055556752d68f clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(this=0x00007fffffff1640, S=0x00005092ffd64dd8, SDK=Discarded) at TreeTransform.h:4294:35
    frame #9: 0x00005555675572bd clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(this=0x00007fffffff1640, S=0x00005092ffd64e00, IsStmtExpr=false) at TreeTransform.h:8088:38
    frame #10: 0x00005555675a5a9a clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(this=0x00007fffffff1640, S=0x00005092ffd64e00) at TreeTransform.h:8070:23
    frame #11: 0x000055556752d4af clang`clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(this=0x00007fffffff1640, S=0x00005092ffd64e00, SDK=Discarded) at StmtNodes.inc:1652:1
    frame #12: 0x000055556752b78e clang`clang::Sema::SubstStmt(this=0x00005092ffd24000, S=0x00005092ffd64e00, TemplateArgs=0x00007fffffff1b68) at SemaTemplateInstantiate.cpp:4357:23
    frame #13: 0x0000555567633a63 clang`clang::Sema::InstantiateFunctionDefinition(this=0x00005092ffd24000, PointOfInstantiation=(ID = 138), Function=0x00005092ffd66088, Recursive=true, DefinitionRequired=false, AtEndOfTU=true) at SemaTemplateInstantiateDecl.cpp:5819:14
    frame #14: 0x0000555567637ae3 clang`clang::Sema::PerformPendingInstantiations(this=0x00005092ffd24000, LocalOnly=false, AtEndOfTU=true) at SemaTemplateInstantiateDecl.cpp:7061:9
    frame #15: 0x0000555565e12515 clang`clang::Sema::ActOnEndOfTranslationUnitFragment(this=0x00005092ffd24000, Kind=Normal) at Sema.cpp:1197:5
    frame #16: 0x0000555565e12c1b clang`clang::Sema::ActOnEndOfTranslationUnit(this=0x00005092ffd24000) at Sema.cpp:1230:5
    frame #17: 0x00005555656a82d2 clang`clang::Parser::ParseTopLevelDecl(this=0x00005092ffc06000, Result=0x00007fffffff4288, ImportState=0x00007fffffff4284) at Parser.cpp:749:13
    frame #18: 0x00005555656a0bc6 clang`clang::ParseAST(S=0x00005092ffd24000, PrintStats=false, SkipFunctionBodies=false) at ParseAST.cpp:171:20
    frame #19: 0x0000555565043c85 clang`clang::ASTFrontendAction::ExecuteAction(this=0x00005092ffe0daa0) at FrontendAction.cpp:1343:3
    frame #20: 0x000055556504323b clang`clang::FrontendAction::Execute(this=0x00005092ffe0daa0) at FrontendAction.cpp:1225:3
    frame #21: 0x0000555564ef050d clang`clang::CompilerInstance::ExecuteAction(this=0x00005092ffe0e6e0, Act=0x00005092ffe0daa0) at CompilerInstance.cpp:1056:33
    frame #22: 0x0000555562960225 clang`clang::ExecuteCompilerInvocation(Clang=0x00005092ffe0e6e0) at ExecuteCompilerInvocation.cpp:300:25
    frame #23: 0x000055556292d9d8 clang`cc1_main(Argv=ArrayRef @ 0x00007fffffff8028, Argv0="clang", MainAddr=0x0000555562919430) at cc1_main.cpp:297:15
```

**Comment by alexfh** [comment]
Okay, I think, I have a fix.
