### PR TITLE
[clang-tidy] fix false negatives for performance-inefficient-vector-operation

### LINKED ISSUE #95596: [clang-tidy] performance-inefficient-vector-operation doesn't warn if loop has unsigned index
https://godbolt.org/z/EWo1cTYGK

```c++
#include <vector>

void f(std::vector<int>& r) {
    std::vector<int> v;
    for (std::size_t i = 0; i < r.size(); ++i) {
        v.push_back(r[i]);
    }
}

void g(std::vector<int>& r) {
    std::vector<int> v;
    for (int i = 0; i < r.size(); ++i) {
        v.push_back(r[i]);
    }
}
```

The only difference is the loop variable `i`'s type being `std::size_t` or `int`, but the check only warns to reserve for `int i` in `g`

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #95596
Avoid false negatives caused by different variable definition type and variable initial value type in loop initialization expression.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/performance/inefficient-vector-operation.cpp [hunk 1]
```diff
@@ -387,3 +387,38 @@ void foo(const StructWithFieldContainer &Src) {
...
+  {
+    std::vector<int> gh95596_3;
+    // CHECK-FIXES: gh95596_3.reserve(10U);
+    for (int i = 0; i < 10U; ++i)
+      gh95596_3.push_back(i);
+      // CHECK-MESSAGES: :[[@LINE-1]]:7: warning: 'push_back' is called inside a loop; consider pre-allocating the container capacity before the loop
+  }
+}
+
+} // namespace gh95596
```
Comment (5chmidti) [inline clang-tools-extra/test/clang-tidy/checkers/performance/inefficient-vector-operation.cpp:424]: missing newline

**Review by 5chmidti — APPROVED** [review]
LGTM

**Review by PiotrZSL — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/performance/inefficient-vector-operation.cpp (hunk 1 above)
Comment (HerrCai0907) [inline clang-tools-extra/test/clang-tidy/checkers/performance/inefficient-vector-operation.cpp:424]:
```suggestion
} // namespace gh95596

```
