### PR TITLE
[libc][POSIX][unistd] Implement gethostname

### LINKED ISSUE #126602: [libc][POSIX][unistd] implement gethostname
Building llvm against llvm-libc fails with:
```
llvm-project/llvm/lib/Support/LockFileManager.cpp:101:3: error: use of undeclared identifier 'gethostname'
```
Looks like this is provided by unistd.h on POSIX systems.

### PR DESCRIPTION
**Pull request by ZakyHermawan**
The implementation is based on the specifications from: https://man7.org/linux/man-pages/man2/gethostname.2.html

Closes https://github.com/llvm/llvm-project/issues/126602

### CODE REVIEW

File: libc/src/unistd/linux/gethostname.cpp [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    return -1;
+  }
+
+  struct utsname unameData;
+  int ret = LIBC_NAMESPACE::syscall_impl<int>(SYS_uname, &unameData);
+
+  // Checks if the length of the nodename was greater than or equal to len, and
+  // if it is, then the function returns -1 with errno set to ENAMETOOLONG. In
+  // this case, a terminating null byte is not included in the returned name.
+  if (strlen(unameData.nodename) >= len) {
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/gethostname.cpp:40]: LLVM-libc doesn't allow to calling other libc functions within libc functions so that each entrypoint is independent of all the others. The intended way to use these specific functions is to call their internal implementations from `/src/string/string_utils.h`.

File: libc/src/unistd/linux/gethostname.cpp [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+#include "src/string/strlen.h"
+#include "src/string/strncpy.h"
+
+#include <sys/syscall.h> // For syscall numbers.
+#include <sys/utsname.h>
+
+namespace LIBC_NAMESPACE_DECL {
+
+// Matching the behavior of glibc version 2.2 and later.
+// Copies up to len bytes from the returned nodename field into name.
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/gethostname.cpp:26]: we don't actually want to mimic glibc exactly. It's more important to match the standard, and make reasonable choices.

File: libc/src/unistd/linux/gethostname.cpp [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+  }
+
+  struct utsname unameData;
+  int ret = LIBC_NAMESPACE::syscall_impl<int>(SYS_uname, &unameData);
+
+  // Checks if the length of the nodename was greater than or equal to len, and
+  // if it is, then the function returns -1 with errno set to ENAMETOOLONG. In
+  // this case, a terminating null byte is not included in the returned name.
+  if (strlen(unameData.nodename) >= len) {
+    strncpy(name, unameData.nodename, len);
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/gethostname.cpp:41]: you're doing the same copy in both branches, you can move it up before the `if`. Also the [posix standard](https://pubs.opengroup.org/onlinepubs/9799919799/functions/gethostname.html) says that if the name is too long "it is unspecified whether the returned name is null-terminated". I think guaranteeing that the name will be null terminated would be a good idea, could you add code to do that?

File: libc/src/unistd/linux/gethostname.cpp [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+  // If the size of the array name is not large enough (less than the size of
+  // nodename with null termination), then anything might happen. In this case,
+  // what happens to the array name will be determined by the implementation of
+  // LIBC_NAMESPACE_DECL::strncpy
+  strncpy(name, unameData.nodename, len);
+
+  if (ret < 0) {
+    libc_errno = static_cast<int>(-ret);
+    return -1;
+  }
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/gethostname.cpp:55]: this check should probably be right after the syscall and before we start trying to read from the struct. If the syscall returns an error then the struct may not be initialized.

File: libc/src/unistd/linux/gethostname.cpp [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+// Copies up to len bytes from the returned nodename field into name.
+LLVM_LIBC_FUNCTION(int, gethostname, (char *name, size_t len)) {
+  // Check for invalid pointer
+  if (name == nullptr) {
+    libc_errno = EFAULT;
+    return -1;
+  }
+
+  struct utsname unameData;
+  int ret = LIBC_NAMESPACE::syscall_impl<int>(SYS_uname, &unameData);
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/gethostname.cpp:35]: would it make sense to use the `SYS_gethostname` syscall instead?

Comment (ZakyHermawan) [reply libc/src/unistd/linux/gethostname.cpp:35]: there is no SYS_gethostname in x86_64.
GNU C library also implement gethostname as a library that calls uname

**Comment by ZakyHermawan** [comment]
@michaelrj-google can you please take a look at this PR ? thanks

File: libc/src/unistd/gethostname.h [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+#ifndef LLVM_LIBC_SRC_UNISTD_GETHOSTNAME_H
+#define LLVM_LIBC_SRC_UNISTD_GETHOSTNAME_H
+
+#include "hdr/types/size_t.h"
+#include "hdr/unistd_macros.h"
```
Comment (lntue) [inline libc/src/unistd/gethostname.h:13]: `hdr/unistd_macros.h` is not needed in this header.

File: libc/src/unistd/linux/gethostname.cpp [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+LLVM_LIBC_FUNCTION(int, gethostname, (char *name, size_t size)) {
+  // Check for invalid pointer
+  if (name == nullptr) {
+    libc_errno = EFAULT;
+    return -1;
+  }
+
+  // Because there is no SYS_gethostname syscall, we use uname to get the
+  // hostname.
+  struct utsname unameData;
```
Comment (lntue) [inline libc/src/unistd/linux/gethostname.cpp:32]: is `struct` needed?

**Review by lntue — APPROVED** [review]
