### PR TITLE
[Clang] emit -Wunused-variable warning for unused structured bindings without the [[maybe_unused]] attribute

### LINKED ISSUE #125810: [Clang] `-Wunused-variable` false negative when not all structured bindings are marked `maybe_unused`
Clang doesn't emit warning when all structured bindings are unused but not all structured bindings are marked `maybe_unused`.

```cpp
struct S {
  int a, b;
};

void test(S s) {
  auto &[a1, _] = s; // "unused variable" warning emitted expectedly
  auto &[a2, b2 [[maybe_unused]]] = s; // no warning emitted unexpectedly
  auto &[_, b3 [[maybe_unused]]] = s; // no warning emitted expectedly
}
```

Compiler Explorer: <https://godbolt.org/z/vnf9Ma3nb>

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #125810 

---

This patch resolves an issue in Clang where the `-Wunused-variable` warning was suppressed for structured bindings with elements marked `[[maybe_unused]]`, causing the entire declaration to be treated as used and preventing the warning from being emitted.

### CODE REVIEW

File: clang/test/SemaCXX/unused-bindings.cpp [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++2c -Wunused %s
+
+namespace GH125810 {
+struct S {
+  int a, b;
+};
+
+void t(S s) {
+  auto &[_, _] = s;
+  auto &[a1, _] = s; // expected-warning {{unused variable '[a1, _]'}}
```
Comment (a-tarasyuk) [inline clang/test/SemaCXX/unused-bindings.cpp:10]: @cor3ntin @AaronBallman Currently, https://godbolt.org/z/911KjMjPY the entire binding declaration is used as the diagnostic location, including all binding elements, even when only some of them are actually unused. Is this the expected behavior?

File: clang/test/SemaCXX/unused-bindings.cpp [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -std=c++2c -Wunused %s
```
Comment (Fznamznon) [inline clang/test/SemaCXX/unused-bindings.cpp:1]: NIT: why not c++26?
```suggestion
// RUN: %clang_cc1 -fsyntax-only -verify -std=c++26 -Wunused %s
```

Comment (a-tarasyuk) [reply clang/test/SemaCXX/unused-bindings.cpp]: @Fznamznon I've updated. thanks

File: clang/test/SemaCXX/unused-bindings.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/test/SemaCXX/unused-bindings.cpp:10]: @cor3ntin @AaronBallman could you review these changes? thanks

Comment (AaronBallman) [reply clang/test/SemaCXX/unused-bindings.cpp:10]: > the entire binding declaration is used as the diagnostic location, including all binding elements, even when only some of them are actually unused. Is this the expected behavior?

It's the current behavior but I think we could improve it. For example, it would be much better in this case to point to each binding declaration that's unused as opposed to the whole structured binding. But the behavior for now is okay.

**Review by AaronBallman — APPROVED** [review]
LGTM

File: clang/test/SemaCXX/unused-bindings.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/test/SemaCXX/unused-bindings.cpp:10]: @cor3ntin @Fznamznon could you review these changes? thanks

Comment (a-tarasyuk) [reply clang/test/SemaCXX/unused-bindings.cpp:10]: @cor3ntin @Fznamznon could you review these changes? thanks

**Review by Fznamznon — APPROVED** [review]
