### PR TITLE
[Clang] Fix a crash when incorrectly calling an explicit object member function template

### LINKED ISSUE #75732: clang - current trunk crashed when compiling the following code
Code snippet in compiler explorer: https://gcc.godbolt.org/z/8MdcGjGoz

A few stack frames:

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<source>:84:9: at annotation token
2.	<source>:78:1: parsing struct/union/class body 'D'
3.	<source>:83:5: parsing function body 'D::serialize'
4.	<source>:83:5: in compound statement ('{}')
 #0 0x0000000003527708 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3527708)
 #1 0x0000000003525854 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3525854)
 #2 0x0000000003472698 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f2a0d642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000006c12e51 clang::CXXMethodDecl::isExplicitObjectMemberFunction() const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x6c12e51)
 #5 0x00000000062af6da diagnoseInstanceReference(clang::Sema&, clang::CXXScopeSpec const&, clang::NamedDecl*, clang::DeclarationNameInfo const&) SemaExprMember.cpp:0:0
 #6 0x00000000062b90fd clang::Sema::BuildPossibleImplicitMemberExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, clang::TemplateArgumentListInfo const*, clang::Scope const*, clang::UnresolvedLookupExpr*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x62b90fd)
 #7 0x0000000005eadb7c clang::Sema::ActOnNameClassifiedAsOverloadSet(clang::Scope*, clang::Expr*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5eadb7c)
 #8 0x0000000005c08f1c clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c08f1c)
 #9 0x0000000005c0a4aa clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5c0a4aa)
```

### PR DESCRIPTION
**Pull request by cor3ntin**
Fixes #75732

### CODE REVIEW

File: clang/lib/Sema/SemaExprMember.cpp [hunk 1]
```diff
@@ -253,6 +253,8 @@ static void diagnoseInstanceReference(Sema &SemaRef,
     SemaRef.Diag(Loc, diag::err_member_call_without_object)
         << Range << /*static*/ 0;
   else {
+    if (auto *Tpl = dyn_cast<FunctionTemplateDecl>(Rep))
+      Rep = Tpl->getTemplatedDecl();
     const auto *Callee = dyn_cast<CXXMethodDecl>(Rep);
```
Comment (tbaederr) [inline clang/lib/Sema/SemaExprMember.cpp:258]: Since `Callee` must be non-null after the cast, shouldn't we use `cast<>` instead of `dyn_cast` here?

File: clang/lib/Sema/SemaExprMember.cpp [hunk 2]
```diff
@@ -253,7 +253,9 @@ static void diagnoseInstanceReference(Sema &SemaRef,
     SemaRef.Diag(Loc, diag::err_member_call_without_object)
         << Range << /*static*/ 0;
   else {
-    const auto *Callee = dyn_cast<CXXMethodDecl>(Rep);
+    if (auto *Tpl = dyn_cast<FunctionTemplateDecl>(Rep))
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaExprMember.cpp:256]: Perhaps a const can be added here.

**Review by Fznamznon — APPROVED** [review]
LGTM with a little NIT
