### PR TITLE
[Clang] Fix the lambda context for constraint evaluation

### LINKED ISSUE #184047: Clang 22.1.0 crash when evaluating nested requires-clause using concept inside requires-expression
Clang 22.1.0 crashes (segmentation fault, exit code 139) while evaluating a concept used inside a nested requires expression.

The crash occurs when a concept is referenced inside a requires { requires ...; } construct, while the same concept works correctly when used directly or aliased through another concept.

Clang 21 compiles this code correctly.
The code also compiles successfully with GCC and MSVC.

Godbolt link: https://godbolt.org/z/GPKW5jcz3
Example:

```cpp
template <typename T, int N>
concept decomposable = requires {
    []<template <typename...> class U, typename... Args>
        requires(sizeof...(Args) >= N)
    (U<Args...>*) {}(static_cast<T*>(nullptr));
};

template<typename T>
struct foo {};

static_assert(decomposable<int, 1> == false);
static_assert(decomposable<foo<int>, 1> == true);

template<typename T>
concept decomposable_works = decomposable<T, 1>;
static_assert(decomposable_works<foo<double>>); // if changed to foo<int>, no crash

template<typename T>
concept decomposable_fails = requires {
    requires decomposable<T, 1>;
};

static_assert(decomposable_fails<foo<int>>); // crash here
```

Additionally, the crash is sensitive to instantiation order:

If this line `static_assert(decomposable_works<foo<double>>);` is changed to `static_assert(decomposable_works<foo<int>>);` then the program compiles successfully even with Clang 22.1.0.

### PR DESCRIPTION
**Pull request by zyn0217**
Constraint lambdas in the requires body need complete template arguments before they can be evaluated. That was connected by ImplicitConceptSpecializationDecl which is no longer created naturally after the normalization patch.

This patch fixes the bug by creating a temporary decl for that purpose. Though the temporary object should go away once we have the evaluation context track template arguments.

No release note for being a regression fix.

Fixes #184047

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nits (it is very unfortunate indeed...)

File: clang/lib/Sema/SemaConcept.cpp [hunk 1]
```diff
@@ -477,6 +477,11 @@ class ConstraintSatisfactionChecker {
   ConstraintSatisfaction &Satisfaction;
   bool BuildExpression;
 
+  // The most closest concept declaration when evaluating atomic constriants.
+  // This is to make sure that lambdas in the atomic expression live in the
+  // right context.
+  ConceptDecl *ParentConcept = nullptr;
```
Comment (shafik) [inline clang/lib/Sema/SemaConcept.cpp]: How is this set?
