### PR TITLE
[AMDGPU][Attributor] Rework update of `AAAMDWavesPerEU`

### LINKED ISSUE #123092: [AMDGPU][Attributor] OpenMC Performance Regression on AMD GPU
I have observed a performance regression in the OpenMC scientific simulation application (which uses OpenMP target offloading) on the AMD MI250 due to commit https://github.com/llvm/llvm-project/commit/7dbd6cd2946ec3a9b4ad2dfd7ead177baac15bd7, which is part of PR #114357. The regression is not observed on NVIDIA GPUs.

This commit causes OpenMC to be 20% slower overall on a typical benchmark problem, with the most expensive kernel in the simulation being about 2x slower.

OpenMC can be installed and its performance benchmark run using the following script: https://github.com/jtramm/openmc_offloading_builder/tree/main

FOM before this commit (higher is better):
```
Calculation Rate (inactive)       = 239870.0 particles/second
```

FOM after this commit:

```
 Calculation Rate (inactive)       = 192707.0 particles/second
```

Main kernel timing before this commit: 
```
     XS lookups (Fuel)             = 1.8720e+01 seconds
```

Main kernel after this commit:
```
     XS lookups (Fuel)             = 3.5231e+01 seconds
```

Rocprof shows similar slowdown for this kernel, which it lists as:

```
__omp_offloading_25_7c638f81__ZN6openmc32process_calculate_xs_events_fuelEv_l256.kd
```

### PR DESCRIPTION
**Pull request by shiltian**
Currently, we use `AAAMDWavesPerEU` to iteratively update values based on attributes from the associated function, potentially propagating user-annotated values, along with `AAAMDFlatWorkGroupSize`. Similarly, we have `AAAMDFlatWorkGroupSize`. However, since the value calculated through the flat workgroup size always dominates the user annotation (i.e., the attribute), running `AAAMDWavesPerEU` iteratively is unnecessary if no user-annotated value exists.

This PR completely rewrites how the `amdgpu-waves-per-eu` attribute is handled in `AMDGPUAttributor`. The key changes are as follows:

- `AAAMDFlatWorkGroupSize` remains unchanged.
- `AAAMDWavesPerEU` now only propagates user-annotated values.
- A new function is added to check and update `amdgpu-waves-per-eu` based on the following rules:
    - No waves per eu, no flat workgroup size: Assume a flat workgroup size of `1,1024` and compute waves per eu based on this.
    - No waves per eu, flat workgroup size exists: Use the provided flat workgroup size to compute waves-per-eu.
    - Waves per eu exists, no flat workgroup size: This is a tricky case. In this PR, we assume a flat workgroup size of `1,1024`, but this can be adjusted if a different approach is preferred. Alternatively, we could directly use the user-annotated value.
    - Both waves per eu and flat workgroup size exist: If there’s a conflict, the value derived from the flat workgroup size takes precedence over waves per eu.

This PR also updates the logic for merging two waves per eu pairs. The current implementation, which uses `clampStateAndIndicateChange` to compute a union, might not be ideal. If we think from ensure proper resource allocation perspective, for instance, if one pair specifies a minimum of 2 waves per eu, and another specifies a minimum of 4, we should guarantee that 4 waves per eu can be supported, as failing to do so could result in excessive resource allocation per wave. A similar principle applies to the upper bound. Thus, the PR uses the following approach for merging two pairs, `lo_a,up_a` and `lo_b,up_b`: `max(lo_a, lo_b), max(up_a, up_b)`. This ensures that resource allocation adheres to the stricter constraints from both inputs.

Fix #123092.

### CODE REVIEW

**Comment by shiltian** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/123995?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#123995** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/123995?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/123995?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#123994** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/123994?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 1]
```diff
@@ -1109,74 +1109,38 @@ struct AAAMDWavesPerEU : public AAAMDSizeRangeAttribute {
...
-          {CallerInfo->getAssumed().getLower().getZExtValue(),
-           CallerInfo->getAssumed().getUpper().getZExtValue() - 1},
-          {AssumedGroupSize->getAssumed().getLower().getZExtValue(),
-           AssumedGroupSize->getAssumed().getUpper().getZExtValue() - 1});
-      ConstantRange CallerRange(APInt(32, Min), APInt(32, Max + 1));
+      unsigned Min = CallerInfo->getAssumed().getLower().getZExtValue();
+      unsigned Max = CallerInfo->getAssumed().getUpper().getZExtValue();
+      ConstantRange CallerRange(APInt(32, Min), APInt(32, Max));
       IntegerRangeState CallerRangeState(CallerRange);
       Change |= clampStateAndIndicateChange(this->getState(), CallerRangeState);
```
Comment (shiltian) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1143]: I think I will still need to change this as well, because the update the range should not be a simple union. I think it should be like what I use in `checkWavesPerEU` in this PR. For example, if one caller has `2,8`, and another has `3,9`, we have to make it `3,9` instead of `2,9` (union) or `3,8` (intersection).

**Comment by shiltian** [comment]
I'll also make more tests if the code changes look reasonable.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 1 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1143]: @arsenm did I get this part correctly?

**Comment by shiltian** [comment]
This stack is supposed to be on top of https://github.com/llvm/llvm-project/pull/125889 but for unknown reason graphite is unable to do that...

**Comment by shiltian** [comment]
ping

@arsenm @jdoerfert

**Comment by jplehr** [comment]
Out of curiosity: I believe this is case three, why would we not want to use the user-provided values?

**Comment by arsenm** [comment]
> Out of curiosity: I believe this is case three, why would we not want to use the user-provided values?

A library use does not have the usage context. It may have specified a bounds to avoid negatively impacting occupancy of some unknown calling kernel. If we know the bounds of the concrete calling kernels, the function should specialize for its bound

File: clang/test/CodeGenOpenCL/builtins-amdgcn.cl [hunk 2]
```diff
@@ -899,4 +899,5 @@ void test_set_fpenv(unsigned long env) {
 
 // CHECK-DAG: [[$GRID_RANGE]] = !{i32 1, i32 0}
 // CHECK-DAG: [[$WS_RANGE]] = !{i16 1, i16 1025}
-// CHECK-DAG: attributes #[[$NOUNWIND_READONLY]] = { convergent mustprogress nocallback nofree nounwind willreturn memory(none) }
+// CHECK-SPIRV-DAG: attributes #[[$NOUNWIND_READONLY]] = { convergent mustprogress nocallback nofree nounwind willreturn memory(none) }
+// CHECK-AMDGCN-DAG: attributes #[[$NOUNWIND_READONLY]] = { convergent mustprogress nocallback nofree nounwind willreturn memory(none) "amdgpu-waves-per-eu"="4,10" }
```
Comment (arsenm) [inline clang/test/CodeGenOpenCL/builtins-amdgcn.cl:903]: Clang test shouldn't have changed?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 3]
```diff
@@ -1160,24 +1138,21 @@ struct AAAMDWavesPerEU : public AAAMDSizeRangeAttribute {
...
-      std::tie(Min, Max) = InfoCache.getEffectiveWavesPerEU(
-          *Caller,
-          {CallerInfo->getAssumed().getLower().getZExtValue(),
-           CallerInfo->getAssumed().getUpper().getZExtValue() - 1},
-          {AssumedGroupSize->getAssumed().getLower().getZExtValue(),
-           AssumedGroupSize->getAssumed().getUpper().getZExtValue() - 1});
-      ConstantRange CallerRange(APInt(32, Min), APInt(32, Max + 1));
-      IntegerRangeState CallerRangeState(CallerRange);
-      Change |= clampStateAndIndicateChange(this->getState(), CallerRangeState);
+      auto Assumed = this->getAssumed();
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1146]: No auto

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 4]
```diff
@@ -1336,6 +1311,59 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
+    auto FlatWgrpSizeAttr =
+        AMDGPU::getIntegerPairAttribute(F, "amdgpu-flat-work-group-size");
+    auto WavesPerEUAttr = AMDGPU::getIntegerPairAttribute(
+        F, "amdgpu-waves-per-eu", /*OnlyFirstRequired=*/true);
+
+    unsigned MinWavesPerEU = ST.getMinWavesPerEU();
+    unsigned MaxWavesPerEU = ST.getMaxWavesPerEU();
+
+    unsigned MinFlatWgrpSize = 1U;
+    unsigned MaxFlatWgrpSize = 1024U;
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1327]: I thought we had a not-hardcoded way to get this already

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 5]
```diff
@@ -1336,6 +1311,59 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
+    if (FlatWgrpSizeAttr.has_value()) {
+      MinFlatWgrpSize = FlatWgrpSizeAttr->first;
+      MaxFlatWgrpSize = *(FlatWgrpSizeAttr->second);
+    }
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1331]:
```suggestion
    if (FlatWgrpSizeAttr)
      std::tie(MinFlatWgrpSize, MaxFlatWgrpSize) = *FlatWgrpSizeAttr;
```

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 6]
```diff
@@ -1336,6 +1311,59 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
+    // Start with the max range.
+    unsigned Min = MinWavesPerEU;
+    unsigned Max = MaxWavesPerEU;
+
+    // If the attribute exists, set them to the value from the attribute.
+    if (WavesPerEUAttr.has_value()) {
+      Min = WavesPerEUAttr->first;
+      if (WavesPerEUAttr->second.has_value())
+        Max = *(WavesPerEUAttr->second);
+    }
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1342]: Does this really need another variant of the parsing logic in GCNSubtarget?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 7]
```diff
@@ -1425,8 +1453,14 @@ static bool runImpl(Module &M, AnalysisGetter &AG, TargetMachine &TM,
...
   }
 
-  ChangeStatus Change = A.run();
-  return Change == ChangeStatus::CHANGED;
+  bool Changed = A.run() == ChangeStatus::CHANGED;
+
+  if (Changed && (LTOPhase == ThinOrFullLTOPhase::None ||
+                  LTOPhase == ThinOrFullLTOPhase::FullLTOPostLink ||
+                  LTOPhase == ThinOrFullLTOPhase::ThinLTOPostLink))
+    checkWavesPerEU(M, TM);
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1461]: This isn't running as part of the attribute run? Why isn't this part of manifest? 

Changed is also really course, you only can care about specific attributes changing

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 8]
```diff
@@ -1336,6 +1311,59 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
   }
 }
 
+static void checkWavesPerEU(Module &M, TargetMachine &TM) {
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1314]: Missing comment, and "check"? This modifies attributes

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 5 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1331]: `FlatWgrpSizeAttr->second` is `std::optional`.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 7 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp]: > This isn't running as part of the attribute run? Why isn't this part of manifest?

So first, the manifest of the two AAs might not run. Second, there is a dependency between the two AAs and the order of the manifest call is undetermined.

Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp]: gentle ping

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 9]
```diff
@@ -1108,47 +1108,25 @@ struct AAAMDWavesPerEU : public AAAMDSizeRangeAttribute {
...
     if (auto Attr = InfoCache.getWavesPerEUAttr(*F)) {
+      std::pair<unsigned, unsigned> MaxWavesPerEURange{
+          1U, InfoCache.getMaxWavesPerEU(*F)};
       if (*Attr != MaxWavesPerEURange) {
-        TakeRange(*Attr);
+        auto [Min, Max] = *Attr;
+        ConstantRange Range(APInt(32, Min), APInt(32, Max + 1));
+        IntegerRangeState RangeState(Range);
+        this->getState() = RangeState;
+        indicateOptimisticFixpoint();
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1120]: Won't this prevent further refining of the callee's bounds?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 10]
```diff
@@ -1333,6 +1308,56 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
 }
 
+/// The final check and update of the attribute 'amdgpu-waves-per-eu' based on
+/// the determined 'amdgpu-flat-work-group-size' attribute. We can't do this
+/// during attributor run because the two attributes grow in opposite direction,
+/// we should not use any intermediate value to calculate waves per eu until we
+/// have a determined flat workgroup size.
+static void updateWavesPerEU(Module &M, TargetMachine &TM) {
+  for (Function &F : M) {
+    const GCNSubtarget &ST = TM.getSubtarget<GCNSubtarget>(F);
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1318]: Skip declarations

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 11]
```diff
@@ -1333,6 +1308,56 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
+    }
+
+    // Start with the max range.
+    unsigned Min = MinWavesPerEU;
+    unsigned Max = MinWavesPerEU;
+
+    // Compute the range from flat workgroup size. `getWavesPerEU` will also
+    // account for the 'amdgpu-waves-er-eu' attribute.
+    auto [MinFromFlatWgrpSize, MaxFromFlatWgrpSize] =
+        ST.getWavesPerEU(F, std::make_pair(MinFlatWgrpSize, MaxFlatWgrpSize));
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1340]:
```suggestion
        ST.getWavesPerEU(F, {MinFlatWgrpSize, MaxFlatWgrpSize});
```

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 12]
```diff
@@ -1333,6 +1308,56 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
   }
 }
 
+/// The final check and update of the attribute 'amdgpu-waves-per-eu' based on
+/// the determined 'amdgpu-flat-work-group-size' attribute. We can't do this
+/// during attributor run because the two attributes grow in opposite direction,
+/// we should not use any intermediate value to calculate waves per eu until we
+/// have a determined flat workgroup size.
+static void updateWavesPerEU(Module &M, TargetMachine &TM) {
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1316]: It just occurred to me that AMDGPUAttributor is only a Module pass. Should we add or replace it with a CGSCC pass?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 13]
```diff
@@ -1333,6 +1308,56 @@ static void addPreloadKernArgHint(Function &F, TargetMachine &TM) {
...
+  for (Function &F : M) {
+    const GCNSubtarget &ST = TM.getSubtarget<GCNSubtarget>(F);
+
+    auto FlatWgrpSizeAttr =
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1320]: no auto

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 14]
```diff
@@ -1408,8 +1433,14 @@ static bool runImpl(Module &M, AnalysisGetter &AG, TargetMachine &TM,
     }
   }
 
-  ChangeStatus Change = A.run();
-  return Change == ChangeStatus::CHANGED;
+  bool Changed = A.run() == ChangeStatus::CHANGED;
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1436]: Can this be more refined on waves per eu or flat workgroup size changing?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 15]
```diff
@@ -1408,8 +1433,14 @@ static bool runImpl(Module &M, AnalysisGetter &AG, TargetMachine &TM,
...
+
+  if (Changed && (LTOPhase == ThinOrFullLTOPhase::None ||
+                  LTOPhase == ThinOrFullLTOPhase::FullLTOPostLink ||
+                  LTOPhase == ThinOrFullLTOPhase::ThinLTOPostLink))
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1440]: Comment why this is skipping the prelink cases?

File: llvm/test/CodeGen/AMDGPU/addrspacecast-constantexpr.ll [hunk 16]
```diff
@@ -4,17 +4,17 @@
 
 declare void @llvm.memcpy.p1.p4.i32(ptr addrspace(1) nocapture, ptr addrspace(4) nocapture, i32, i1) #0
 
-@lds.i32 = unnamed_addr addrspace(3) global i32 poison, align 4
-@lds.arr = unnamed_addr addrspace(3) global [256 x i32] poison, align 4
+@lds.i32 = unnamed_addr addrspace(3) global i32 undef, align 4
+@lds.arr = unnamed_addr addrspace(3) global [256 x i32] undef, align 4
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/addrspacecast-constantexpr.ll:8]: These are unnecessarily regressing from poison to undef

File: llvm/test/CodeGen/AMDGPU/amdgpu-attributor-no-agpr.ll [hunk 17]
```diff
@@ -252,13 +252,13 @@ define amdgpu_kernel void @indirect_calls_none_agpr(i1 %cond) {
 }
 
 
-attributes #0 = { "amdgpu-agpr-alloc"="0" }
+attributes #0 = { "amdgpu-no-agpr" }
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/amdgpu-attributor-no-agpr.ll:255]: Broken revert to old attribute

**Review by arsenm — COMMENTED** [review]
Tests look like they were reverted to some old revision and lost updates

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 9 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1120]: It will not because we will not run attributor more than once thus there is no intermediate values added. If a function has the attribute, it means it has to be a kernel function (at least for now since we only allow the attribute on kernel functions) and the value is chosen by users so we will honor it.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 12 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1325]: We should probably add a CGSCC pass.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 9 above)
Comment (arsenm) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1129]: I don't want to bake in the assumption it's only set on kernels. This is an artificial restriction we shouldn't really have. Everywhere else properly handles waves per eu on functions

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 14 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1449]: I didn't follow your question. Can you expatiate it?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 9 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1129]: At the moment it doesn't have that assumption though. If there is an attribute it has be from users. That part still holds.

**Comment by shiltian** [comment]
ping

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 18]
```diff
@@ -1162,24 +1140,21 @@ struct AAAMDWavesPerEU : public AAAMDSizeRangeAttribute {
...
+      ConstantRange Assumed = this->getAssumed();
+      unsigned Min = std::max(Assumed.getLower().getZExtValue(),
+                              CallerAA->getAssumed().getLower().getZExtValue());
+      unsigned Max = std::max(Assumed.getUpper().getZExtValue(),
+                              CallerAA->getAssumed().getUpper().getZExtValue());
+      ConstantRange Range(APInt(32, Min), APInt(32, Max));
+      IntegerRangeState RangeState(Range);
+      this->getState() = RangeState;
+      Change |= this->getState() == Assumed ? ChangeStatus::UNCHANGED
+                                            : ChangeStatus::CHANGED;
```
Comment (jdoerfert) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1157]: Nit: Do we really need the `this->` uses above?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 19]
```diff
@@ -1323,6 +1298,60 @@ struct AAAMDGPUNoAGPR
 
 const char AAAMDGPUNoAGPR::ID = 0;
 
+/// The final check and update of the attribute 'amdgpu-waves-per-eu' based on
+/// the determined 'amdgpu-flat-work-group-size' attribute. We can't do this
+/// during attributor run because the two attributes grow in opposite direction,
+/// we should not use any intermediate value to calculate waves per eu until we
+/// have a determined flat workgroup size.
```
Comment (jdoerfert) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1305]: I still believe the wording here is misleading. In our last (long) discussion, I tried to propose a different view on the same issue, as "grows in the opposite direction" is not a conceptual problem. I would recommend looking back at that conversation, maybe you can expand on the above a bit to help people understand the conceptual issue.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 20]
```diff
@@ -1323,6 +1298,60 @@ struct AAAMDGPUNoAGPR
...
+    unsigned MaxWavesPerEU = ST.getMaxWavesPerEU();
+
+    unsigned MinFlatWgrpSize = ST.getMinFlatWorkGroupSize();
+    unsigned MaxFlatWgrpSize = ST.getMaxFlatWorkGroupSize();
+    if (FlatWgrpSizeAttr.has_value()) {
+      MinFlatWgrpSize = FlatWgrpSizeAttr->first;
+      MaxFlatWgrpSize = *(FlatWgrpSizeAttr->second);
+    }
+
+    // Start with the max range.
```
Comment (jdoerfert) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1327]: "best range", not "max"

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 21]
```diff
@@ -1396,8 +1425,16 @@ static bool runImpl(Module &M, AnalysisGetter &AG, TargetMachine &TM,
...
 
-  ChangeStatus Change = A.run();
-  return Change == ChangeStatus::CHANGED;
+  bool Changed = A.run() == ChangeStatus::CHANGED;
+
+  // We only update the waves-per-eu attribute at the final stage to avoid
+  // setting it with intermediate values.
+  if (Changed && (LTOPhase == ThinOrFullLTOPhase::None ||
+                  LTOPhase == ThinOrFullLTOPhase::FullLTOPostLink ||
+                  LTOPhase == ThinOrFullLTOPhase::ThinLTOPostLink))
```
Comment (jdoerfert) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1434]: This doesn't work. You can't not set it as later Changed might be false, and you never validate/fixup the result. I would suggest to ignore Changed and simply update the WavesPerEu.

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp (hunk 19 above)
Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp]: How do you like the new version?

File: llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp [hunk 22]
```diff
@@ -1323,6 +1298,73 @@ struct AAAMDGPUNoAGPR
 
 const char AAAMDGPUNoAGPR::ID = 0;
 
+/// Performs the final check and updates the 'amdgpu-waves-per-eu' attribute
+/// based on the finalized 'amdgpu-flat-work-group-size' attribute.
+/// Both attributes start with narrow ranges that expand during iteration.
+/// However, a narrower flat-workgroup-size leads to a wider waves-per-eu range,
+/// preventing optimal updates later. Therefore, waves-per-eu can't be updated
+/// with intermediate values during the attributor run. We defer the calculation
```
Comment (jdoerfert) [inline llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp:1306]:
```suggestion
/// with intermediate values during the attributor run. We defer the finalization
```

**Review by jdoerfert — APPROVED** [review]
One nit, feel free to ignore.
