### PR TITLE
[clang-tidy] Fix misc-unused-parameters on params with attrs

### LINKED ISSUE #122191: clang-tidy misc-unused-parameters breaks attributes on parameters
If a parameter has an attribute spelled after it, then after `misc-unused-parameters` comments out the parameter name the attribute becomes wrongly applied to the type instead.

For example:

```c++
// before:
int& f(int& x [[clang::lifetimebound]]) {
}

// after clang-tidy:
int& f(int& /*x*/ [[clang::lifetimebound]]) {
}
```

The grammar works in a way that the attribute becomes attached to the type, which changes the semantics (e.g., `[[clang::lifetimebound]]` is silently ignored currently when applied to types, but #96034 will change this to a compilation error).

### PR DESCRIPTION
**Pull request by emaxx-google**
Don't suggest to comment-out the parameter name if the parameter has an attribute that's spelled after the parameter name.

This prevents the parameter's attributes from being wrongly applied to the parameter's type.

This fixes #122191.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/misc/UnusedParametersCheck.cpp [hunk 1]
```diff
@@ -26,6 +29,17 @@ bool isOverrideMethod(const FunctionDecl *Function) {
...
+bool hasAttrAfterParam(const SourceManager *SourceManager,
+                       const ParmVarDecl *Param) {
+  for (const auto *Attr : Param->attrs()) {
+    if (SourceManager->isBeforeInTranslationUnit(Param->getLocation(),
+                                                 Attr->getLocation())) {
+      return true;
+    }
+  }
+  return false;
+}
```
Comment (usx95) [inline clang-tools-extra/clang-tidy/misc/UnusedParametersCheck.cpp:42]: It is unfortunate that for declaration attributes we do not have the information that attr appeared before or after the decl.
I would argue, for simplicity, we filter out all annotated params irrespective of the position of attribute.

Dealing with raw source locations can quickly become problematic. For example with expanded locations:
```cpp
#define ANNOTATE_BEFORE(x) [[clang::lifetimebound]] x
#define ANNOTATE_AFTER(x) x [[clang::lifetimebound]]

int* foo(ANNOTATE_BEFORE(int* x)) {}
int* bar(ANNOTATE_AFTER(int* x)) {}
```
https://godbolt.org/z/brYMKfcxf
It is possible to make it work but I don't see the point of this complexity when we can have a simpler filter without much fallout

Comment (emaxx-google) [reply clang-tools-extra/clang-tidy/misc/UnusedParametersCheck.cpp:42]: I've run this example, and with my CL clang-tidy comments out the argument in the `ANNOTATE_BEFORE` case, while leaving the `ANNOTATE_AFTER` case as-is. Is that incorrect? In the former case, the grammar makes the attribute apply to the (unnamed) parameter. I've also verified the clang built with #118501 doesn't complain on this.

But maybe I'm missing some other problem?..

Comment (usx95) [reply clang-tools-extra/clang-tidy/misc/UnusedParametersCheck.cpp:42]: The behaviour seems correct then. Please add this test case in the tests.
`isBeforeInTranslationUnit` seems to be the correct function here.

Comment (emaxx-google) [reply clang-tools-extra/clang-tidy/misc/UnusedParametersCheck.cpp:42]: Done. Thanks for the great test!

**Review by usx95 — APPROVED** [review]
Thanks. LGTM.
