### PR TITLE
[mlir][vector] Fix invalid `LoadOp` indices being created

### LINKED ISSUE #71326: Possible bug in `convert-vector-to-scf`
There appears to be a bug in the `convert-vector-to-scf` where converting certain `vector.transfer_read` ops causes an invalid `memref.load` op to be created.  Maybe the input IR that causes this is incompatible with the pass, but I think a proper error check should be done rather than let the implementation create an invalid op.

Example IR:

```
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, 0, 0, d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0, 0, 0, d3)>
func.func @main(%subview:  memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %c0 : index, %c0_i32 : i32, %2: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
}
```

Applying `mlir-opt --convert-vector-to-scf` to this IR yields the following error
```
transfer-read.mlir:4:10: error: 'memref.load' op incorrect number of indices for load
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
         ^
transfer-read.mlir:4:10: note: see current operation: %8 = "memref.load"(%4, %0, %0) <{nontemporal = false}> : (memref<1xvector<32xi1>>, index, index) -> vector<32xi1>
```

Note that the IR gets successfully transformed with the `full-unroll` option turned on.  Applying `mlir-opt ---convert-vector-to-scf=full-unroll` yields

```
  func.func @main(%arg0: memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %arg1: index, %arg2: i32, %arg3: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %0 = vector.splat %arg2 : vector<1x1x1x32xi32>
    %1 = vector.extract %arg3[0] : vector<1x32xi1>
    %2 = vector.transfer_read %arg0[%arg1, %arg1, %arg1, %arg1], %arg2, %1 {in_bounds = [true]} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<32xi32>
    %3 = vector.insert %2, %0 [0, 0, 0] : vector<32xi32> into vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
  }
  ```
  
  This makes me believe that it should also work without the option, since in this case all the leading dims are size `1` and thus any loops that get generated would be trivial single iteration loops that would canonicalize away.  Which, as far as I can tell, would  be exactly what the unrolled version would generate.

### PR DESCRIPTION
**Pull request by rikhuijzer**
Fixes https://github.com/llvm/llvm-project/issues/71326.

This is the second PR. The first PR at https://github.com/llvm/llvm-project/pull/75519 was reverted because an integration test failed. The failed integration test was simplified and added to the core MLIR tests. Compared to the first PR, the current PR uses a more reliable approach. In summary, the current PR determines the mask indices by looking up the _mask_ buffer load indices from the previous iteration, whereas `main` looks up the indices for the _data_ buffer. The mask and data indices can differ when using a `permutation_map`.

The cause of the issue was that a new `LoadOp` was created which looked something like:
```mlir
func.func main(%arg1 : index, %arg2 : index) {
  %alloca_0 = memref.alloca() : memref<vector<1x32xi1>>
  %1 = vector.type_cast %alloca_0 : memref<vector<1x32xi1>> to memref<1xvector<32xi1>>
  %2 = memref.load %1[%arg1, %arg2] : memref<1xvector<32xi1>>
  return
}
```
which crashed inside the `LoadOp::verify`. Note here that `%alloca_0` is the mask as can be seen from the `i1` element type and note it is 0 dimensional. Next, `%1` has one dimension, but `memref.load` tries to index it with two indices.

This issue occured in the following code (a simplified version of the bug report):
```mlir
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, 0, 0, d3)>
func.func @main(%subview:  memref<1x1x1x1xi32>, %mask: vector<1x1xi1>) -> vector<1x1x1x1xi32> {
  %c0 = arith.constant 0 : index
  %c0_i32 = arith.constant 0 : i32
  %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %mask {permutation_map = #map1}
          : memref<1x1x1x1xi32>, vector<1x1x1x1xi32>
  return %3 : vector<1x1x1x1xi32>
}
```
After this patch, it is lowered to the following by `-convert-vector-to-scf`:
```mlir
func.func @main(%arg0: memref<1x1x1x1xi32>, %arg1: vector<1x1xi1>) -> vector<1x1x1x1xi32> {
  %c0_i32 = arith.constant 0 : i32
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %alloca = memref.alloca() : memref<vector<1x1x1x1xi32>>
  %alloca_0 = memref.alloca() : memref<vector<1x1xi1>>
  memref.store %arg1, %alloca_0[] : memref<vector<1x1xi1>>
  %0 = vector.type_cast %alloca : memref<vector<1x1x1x1xi32>> to memref<1xvector<1x1x1xi32>>
  %1 = vector.type_cast %alloca_0 : memref<vector<1x1xi1>> to memref<1xvector<1xi1>>
  scf.for %arg2 = %c0 to %c1 step %c1 {
    %3 = vector.type_cast %0 : memref<1xvector<1x1x1xi32>> to memref<1x1xvector<1x1xi32>>
    scf.for %arg3 = %c0 to %c1 step %c1 {
      %4 = vector.type_cast %3 : memref<1x1xvector<1x1xi32>> to memref<1x1x1xvector<1xi32>>
      scf.for %arg4 = %c0 to %c1 step %c1 {
        %5 = memref.load %1[%arg2] : memref<1xvector<1xi1>>
        %6 = vector.transfer_read %arg0[%arg2, %c0, %c0, %c0], %c0_i32, %5 {in_bounds = [true]} : memref<1x1x1x1xi32>, vector<1xi32>
        memref.store %6, %4[%arg2, %arg3, %arg4] : memref<1x1x1xvector<1xi32>>
      }
    }
  }
  %2 = memref.load %alloca[] : memref<vector<1x1x1x1xi32>>
  return %2 : vector<1x1x1x1xi32>
}
```
What was causing the problems is that one dimension of the data buffer `%alloca` (eltype `i32`) is unpacked (`vector.type_cast`) inside the outmost loop (loop with index variable `%arg2`) and the nested loop (loop with index variable `%arg3`), whereas the mask buffer `%alloca_0` (eltype `i1`) is not unpacked in these loops.

Before this patch, the load indices would be determined by looking up the load indices for the *data* buffer load op. However, as shown in the specific example, when a permutation map is specified then the load indices from the data buffer load op start to differ from the indices for the mask op. To fix this, this patch ensures that the load indices for the *mask* buffer are used instead.

### CODE REVIEW

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp [hunk 1]
```diff
@@ -897,7 +921,8 @@ struct TransferOpConversion : public VectorToSCFPattern<OpTy> {
       } else {
         // It's safe to assume the mask buffer can be unpacked if the data
         // buffer was unpacked.
-        auto castedMaskType = *unpackOneDim(maskBufferType);
+        auto maskBufferType = dyn_cast<MemRefType>(maskBuffer.getType());
```
Comment (joker-eph) [inline mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:924]: Why are you introducing a `dyn_cast` here?

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp [hunk 2]
```diff
@@ -866,16 +866,41 @@ struct TransferOpConversion : public VectorToSCFPattern<OpTy> {
...
+    assert(xferOp.getMask() && "Expected transfer op to have mask");
+
+    // Add load indices from the previous iteration.
+    // The mask buffer depends on the permutation map, which makes determining
+    // the indices quite complex, so this is why we need to "look back" to the
+    // previous iteration to find the right indices.
+    Value maskBuffer = getMaskBuffer(xferOp);
+    for (OpOperand &use : maskBuffer.getUses()) {
+      // If there is no previous load op, then the indices are empty.
+      if (auto loadOp = dyn_cast<memref::LoadOp>(use.getOwner())) {
```
Comment (joker-eph) [inline mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:881]:
```suggestion
    for (Operation *user : maskBuffer.getUsers()) {
      // If there is no previous load op, then the indices are empty.
      if (auto loadOp = dyn_cast<memref::LoadOp>(user)) {
```

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp [hunk 3]
```diff
@@ -866,16 +866,41 @@ struct TransferOpConversion : public VectorToSCFPattern<OpTy> {
     this->setHasBoundedRewriteRecursion();
   }
 
+  static void getMaskBufferLoadIndices(OpTy xferOp, Value castedMaskBuffer,
+                                       SmallVector<Value, 8> &loadIndices,
```
Comment (joker-eph) [inline mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:870]:
```suggestion
                                       SmallVectorImpl<Value> &loadIndices,
```

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp (hunk 1 above)
Comment (rikhuijzer) [reply mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:924]: That's caused by git diff being confusing. The `maskBufferType` was defined before the `if-else`, but only used inside the `else`, so I moved it inside the `else`.

Comment (joker-eph) [reply mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:924]: OK, but we're not checking the result: if this can't fail here by construction it should be a cast instead.

Comment (rikhuijzer) [reply mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp]: Ah yes. You're right. Done in [ec9d8d7](https://github.com/llvm/llvm-project/pull/76292/commits/ec9d8d75077b26c2efa92063ec659ba2dd89d8b7).

**Review by joker-eph — APPROVED** [review]

**Comment by rikhuijzer** [comment]
@joker-eph, thanks again for the review!
