### PR TITLE
[LV] Don't mark ptrs as safe to speculate if fed by UB/poison op.

### LINKED ISSUE #142957: loop-vectorize miscompile
llvm commit: 6955a7d134e7
Reproduce with:
```
opt -passes="loop-vectorize" bbi-107525_lv.ll -S -o - -mtriple=aarch64-none-linux-gnu --data-layout="p:16:16"
```
The loop-vectorize output contains
```
pred.sdiv.continue:                               ; preds = %pred.sdiv.if, %vector.body
  %3 = phi i16 [ poison, %vector.body ], [ %2, %pred.sdiv.if ]
  [...]

pred.sdiv.continue2:                              ; preds = %pred.sdiv.if1, %pred.sdiv.continue
  [...]
  %7 = shl i16 %3, 14
  %8 = sub i16 %6, %7
  %9 = getelementptr [16 x i64], ptr @g_855, i16 0, i16 %8
  %10 = getelementptr i64, ptr %9, i32 0
  %wide.load = load <2 x i64>, ptr %10, align 1
```

and the problem here is that we will get to the %3 phi from %vector.body and then continue to pred.sdiv.continue2 where the %3 poison value will make %7, %8, %9 and %10 poison, and then we will do a load from %10 which is instant UB.

The input program has no UB.

Before 0d61ffd350
```
[Loads] Support SCEVAddExpr as start for pointer AddRec.
```
the result is ok. Then with 0d61ffd350 it crashes with
```
opt: ../include/llvm/Support/Casting.h:109: static bool llvm::isa_impl_cl<llvm::Instruction, const llvm::Value *>::doit(const From *) [To = llvm::Instruction, From = const llvm::Value *]: Assertion `Val && "isa<> used on a null pointer"' failed.
```
and that crash goes away with fd82b5b287
```
[LV] Support recieps without underlying instr in collectPoisonGenRec.

Support recipes without underlying instruction in
collectPoisonGeneratingRecipes by directly trying to dyn_cast_or_null
the underlying value.

Fixes https://github.com/llvm/llvm-project/issues/70590.
```
but then we get the miscompile instead.

I also tested to cherry-pick the fd82b5b287 to directly after 0d61ffd350 and we get the miscompile then too, so it doesn't seem to be some other patch between them that causes the miscompile.

[bbi-107525_lv.ll.gz](https://github.com/user-attachments/files/20610502/bbi-107525_lv.ll.gz)

### PR DESCRIPTION
**Pull request by fhahn**
Add additional checks before marking pointers safe to load speculatively. If some computations feeding the pointer may trigger UB, we cannot load the pointer speculatively, because we cannot compute the address speculatively. The UB triggering instructions will be predicated, but if the predicated block does not execute the result is poison.

Similarly, we also cannot load the pointer speculatively if it may be poison. The patch also checks if any of the operands defined outside the loop may be poison when entering the loop. We *don't* need to check if any operation inside the loop may produce poison due to flags, as those will be dropped if needed.

There are some types of instructions inside the loop that can produce poison independent of flags. Currently loads are also checked, not sure if there's a convenient API to check for all such operands.

Fixes https://github.com/llvm/llvm-project/issues/142957.

### CODE REVIEW

**Comment by mikaelholmen** [comment]
As far as I can see this fixes the problem I reported. Thanks!

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp [hunk 1]
```diff
@@ -1493,10 +1493,51 @@ bool LoopVectorizationLegality::canVectorizeWithIfConvert() {
...
       LoadInst *LI = dyn_cast<LoadInst>(&I);
+
+      // Make sure we can execute all computations feeding into Ptr in the loop
+      // w/o triggering UB and that none of the out-of-loop operands are poison.
+      // We do not need to check if operations inside the loop can produce
+      // poison due to flags (e.g. due to an inbounds GEP going out of bounds),
+      // because flags will be dropped when executing them unconditionally.
+      // TODO: Results could be improved by considering poison-propagation
+      // properties of visited ops.
+      auto CanSpeculateOp = [this](Value *Ptr) {
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp]: This function is specifically related to UB, so perhaps worth making it a bit clearer by adding it to the name, i.e. `PtrWillNotTriggerUB`?

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp [hunk 2]
```diff
@@ -1493,10 +1493,51 @@ bool LoopVectorizationLegality::canVectorizeWithIfConvert() {
     SmallVector<const SCEVPredicate *, 4> Predicates;
     for (Instruction &I : *BB) {
       LoadInst *LI = dyn_cast<LoadInst>(&I);
+
+      // Make sure we can execute all computations feeding into Ptr in the loop
+      // w/o triggering UB and that none of the out-of-loop operands are poison.
+      // We do not need to check if operations inside the loop can produce
+      // poison due to flags (e.g. due to an inbounds GEP going out of bounds),
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp:1498]: Does include things like nsw, nuw for sub/add operations? I'm just thinking of a scalar loop that has something like:

```
  %index = phi i64 ...
  %index_plus_offset = add nuw nsw i64 %index, 12345678
  %gep = getelementptr inbounds i64, ptr %ptr, i64 %index_plus_offset
```

where the `%index_plus_offset` could be poison-generating. Are you saying that after vectorisation any such flags on adds or subs that feed into the GEP cannot survive?

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp (hunk 1 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp]: It checks both for instructions that trigger immediate UB when computing the pointer and cases where the pointer itself may be poison, thus triggering UB if dereferenced, which is why I tried to keep the name generic, but it's not 100% clear at the moment.

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp (hunk 2 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp:1498]: Yes it includes all relevant flags, including `nuw`, `nsw`, `inbounds`. The flags are only dropped for any op that computes a pointer for loads that are executed conditionally in the original loop but executed unconditionally in the vector loop.

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp (hunk 1 above)
Comment (david-arm) [reply llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp]: OK, maybe something more specific to pointers then as it gives the impression this is about any operation. Perhaps `CanSpeculatePointerOp`?

**Review by david-arm — APPROVED** [review]
LGTM.

**Comment by mikaelholmen** [comment]
The patch is approved, anything left or can this be submitted? @fhahn ?

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp (hunk 1 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp]: Hmm, it checks not only checks pointers, it checks any operation in the loop feeding a pointer, including any non-pointer operations, but it is only used for pointers. Updated the name for now, thanks

Comment (david-arm) [reply llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp]: OK thanks! The patch looks good to me. Feel free to merge when ready!

File: llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp [hunk 3]
```diff
@@ -1491,10 +1491,51 @@ bool LoopVectorizationLegality::canVectorizeWithIfConvert() {
...
+      // because flags will be dropped when executing them unconditionally.
+      // TODO: Results could be improved by considering poison-propagation
+      // properties of visited ops.
```
Comment (ayalz) [inline llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp:1501]: Post-commit nit: another TODO is to potentially save compile time by computing all SpeculatablePointers defined in the loop together, instead of analyzing the expression of each pointer independently, as some pointers may be used to define others?

**Comment by mikaelholmen** [comment]
Thanks!
