### PR TITLE
[flang][OpenMP] fix predetermined privatization inside section

### LINKED ISSUE #135108: [Flang][OpenMP] Assertion `success && "Privatization failed due to existing binding"' failed. (parallel sections directive)
Reproducer:
```f90
!$omp parallel sections
!$omp section
    do i = 1, 2
    end do
!$omp section
    do i = 1, 2
    end do
!$omp end parallel sections
end
```

With assertion-disabled flang, the following output is obtained:
https://godbolt.org/z/GbfW7vYKj
```txt
flang-21: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: loc("/app/example.f90":6:5): operand #1 does not dominate this use
error: verification of lowering to FIR failed
Compiler returned: 1
```

With assertion-enabled flang, the reproducer hits the following assertion:
```txt
flang: /path_to_project/llvm-project/flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:152: void Fortran::lower::omp::DataSharingProcessor::cloneSymbol(const semantics::Symbol *): Assertion `success && "Privatization failed due to existing binding"' failed.
```

### PR DESCRIPTION
**Pull request by tblah**
This now produces code equivalent to if there was an explicit private clause on the SECTIONS construct.

The problem was that each SECTION construct got its own DSP, which tried to privatize the same symbol for that SECTION. Privatization for SECTION(S) happens on the outer SECTION construct and so the outer construct's DSP should be shared.

Fixes #135108

### CODE REVIEW

File: flang/lib/Lower/OpenMP/OpenMP.cpp [hunk 1]
```diff
@@ -1240,7 +1247,7 @@ static void createBodyOfOp(mlir::Operation &op, const OpWithBodyGenInfo &info,
     // loop (this may not make sense in production code, but a user could
     // write that and we should handle it).
     firOpBuilder.setInsertionPoint(term);
-    if (privatize) {
+    if (privatize && !info.skipDspStep2) {
```
Comment (skatrak) [inline flang/lib/Lower/OpenMP/OpenMP.cpp:1250]: We already have a special case in `DataSharingProcessor::processStep2()` to skip last-privatization when called for an `omp.sections` op. Wouldn't it make sense to return early for `omp.section` there, so the logic for handling the `section(s)` special case is spread across just two functions?

Comment (tblah) [reply flang/lib/Lower/OpenMP/OpenMP.cpp]: Thanks that was a good idea.

**Review by skatrak — APPROVED** [review]
Thank you, LGTM!
