### PR TITLE
[clang-tidy][NFC] Fix a couple of suspicious StringRef::data() usages

### LINKED ISSUE #156150: [clang-tidy] Enable 'bugprone-suspicious-stringview-data-usage' check in clang-tidy config.
The check could be enabled in [.clang-tidy](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/.clang-tidy) or given reason why it shouldn't

All the violations in `clang-tools-extra/clang-tidy` directory should be fixed.

### PR DESCRIPTION
**Pull request by capitan-davide**
Closes https://github.com/llvm/llvm-project/issues/156150

Updates a couple of clang-tidy checks to use C++17 `std::string` member functions that accepts a `StringViewLike` template parameter.

### CODE REVIEW

**Review by vbvictor — APPROVED** [review]
LGTM
But there are still some violations left?

File: clang-tools-extra/clang-tidy/ClangTidyOptions.cpp [hunk 1]
```diff
@@ -99,7 +99,10 @@ void yamlize(IO &IO, ClangTidyOptions::OptionMap &Val, bool,
     for (auto &Option : SortedOptions) {
       bool UseDefault = false;
       void *SaveInfo = nullptr;
+      // NOLINTBEGIN(bugprone-suspicious-stringview-data-usage): Requires
+      // 'llvm::yaml::IO' to accept 'StringRef'
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/ClangTidyOptions.cpp:103]: It's better to write:
```cpp
// Requires 'llvm::yaml::IO' to accept 'StringRef'
// NOLINTNEXTLINE(bugprone-suspicious-stringview-data-usage)
```
without trailing `// NOLINTEND`

Same for other place.
