### PR TITLE
[lldb] Updated lldb-server to spawn the child process and share socket

### LINKED ISSUE #56346: lldb-server crashes on Windows when debugger disconnects
lldb-server appears to crash on Windows as the remote debugger disconnects, causing me to have to restart it each time I run debug.

```console
> .\lldb-server.exe platform --listen "*:1234" --server
Connection established.
error: lost connection
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\Users\\WDKRemoteUser\\lldb-server.exe platform --listen *:1234 --server
1.      Program arguments: C:\\Users\\WDKRemoteUser\\lldb-server.exe platform --listen *:1234 --server
0x00007FF6415C1100 (0x000001B6A5F5BDA0 0x000000A4AF38FD28 0x0000000000000000 0x00007FFA66AF131E)
0x00007FF6415C71D3 (0x00007FF642638080 0x000000A4AF38FE40 0x000000A4AF38FE40 0x00007FFA71C912B0)
0x00007FF6415C8F84 (0x0000000000000000 0x00007FF64245EBED 0x0000000000000000 0x0000000000000000)
0x00007FF64245EB74 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA737154E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x10 bytes(s)
0x00007FFA7468485B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x2B bytes(s)
```

### LINKED ISSUE #90923: lldb-server on Windows in platform mode does not reuse ports correctly
On both Linux and Windows, when lldb-server is in platform mode, the first connection gets handed the portmap defined by `--min-gdb-serverport` and `--max-gdb-serverport`. Subsequent connections don't receive this portmap because it has been `std::move`'d for the fork'ed child process to handle.

https://github.com/llvm/llvm-project/pull/88845/ will fix this for Linux, but on Windows, the problem will only be partially fixed by the PR.
After the PR lands, Window's lldb-server will be able to use the port map for multiple connections but will fail to reclaim ports as they are given out to each connection. After enough connections, there won't be any more ports for server to give out.

### LINKED ISSUE #97537: lldb-server's GDB port map (--min/max-gdbserver-port) has a race condition when killing the debugee on a slow remote system
To reproduce, the remote needs to be something relatively slow. In my case QEMU.

Start an lldb-server on the remote in platform mode with some restricted ports:
```
$ ./lldb-server plaform --server --listen 0.0.0.0:54321 --min-gdbserver-port 49140 --max-gdbserver-port 49150
```
Then connect lldb and run a program:
```
$ ./bin/lldb
(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) platform connect connect://127.0.0.1:54321
  Platform: remote-linux
    Triple: aarch64-unknown-linux-gnu
OS Version: 6.10.0 (6.10.0-rc4-g14d7c92f8df9)
  Hostname: e125016
 Connected: yes
WorkingDir: /home/davspi01
    Kernel: #1 SMP PREEMPT Tue Jun 18 15:14:36 BST 2024
(lldb) target create /tmp/test.o
Current executable set to '/tmp/test.o' (aarch64).
(lldb) b main
Breakpoint 1: where = test.o`main at test.c:1:21, address = 0x0000000000400574
(lldb) run
Process 263 launched: '/tmp/test.o' (aarch64)
Process 263 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x0000000000400574 test.o`main at test.c:1:21
-> 1   	int main() { return 0; }
```
At this point lldb-server has started a new process to handle this client's connection and given it a port map that has one open port, that it has used to start a gdb-server process.

From here, if you finish the program then run it again, everything is fine. The gdbserver is torn down and the port is freed, then reused for the new gdbserver.

However, if you run before the program finishes there is a race between the platform killing the gdbserver process and the platform handling the launch gdb server request packet:
```
$ ./bin/lldb
(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) platform connect connect://127.0.0.1:54321
  Platform: remote-linux
    Triple: aarch64-unknown-linux-gnu
OS Version: 6.10.0 (6.10.0-rc4-g14d7c92f8df9)
  Hostname: e125016
 Connected: yes
WorkingDir: /home/davspi01
    Kernel: #1 SMP PREEMPT Tue Jun 18 15:14:36 BST 2024
(lldb) target create /tmp/test.o
Current executable set to '/tmp/test.o' (aarch64).
(lldb) b main
Breakpoint 1: where = test.o`main at test.c:1:21, address = 0x0000000000400574
(lldb) run
Process 263 launched: '/tmp/test.o' (aarch64)
Process 263 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x0000000000400574 test.o`main at test.c:1:21
-> 1   	int main() { return 0; }
(lldb) run
There is a running process, kill it and restart?: [Y/n] y
Process 263 exited with status = 9 (0x00000009) killed
error: unable to launch a GDB server on 'e125016'
```
We can see that the packets are sent in the right order:
```
lldb             <   5> send packet: $k#6b
lldb             <  19> read packet: $X09;process:115#cc
Process 277 exited with status = 9 (0x00000009) killed
<...>
lldb             <  34> send packet: $qLaunchGDBServer;host:e125016;#12
lldb             <   7> read packet: $E09#ae
error: unable to launch a GDB server on 'e125016'
```
On the server side it uses `kill()` to kill the process and it should then free the port here:
https://github.com/llvm/llvm-project/blob/76c84e702bd9af7db2bb9373ba6de0508f1e57a9/lldb/tools/lldb-server/lldb-platform.cpp#L300

(introduced by https://github.com/llvm/llvm-project/pull/88845, which I think made the feature overall better, but in doing so exposed this issue)

If the remote is slow enough that the kill doesn't actually finish before we get back there, then it won't and it'll try to find a free port, find none, and fail to launch the gdb server. Some ad-hoc logging shows this on the server side:
```
265: port map begins --------------------   <<< 256 is the main process
first: 49140 second: 0
first: 49141 second: 0
first: 49142 second: 0
first: 49143 second: 0
first: 49144 second: 0
first: 49145 second: 0
first: 49146 second: 0
first: 49147 second: 0
first: 49148 second: 0
first: 49149 second: 0
265: port map ends--------------------
266: port map begins -------------------- <<< 266 is created to handle the connection to lldb
first: 49140 second: 0
266: port map ends--------------------   <<< the first gdbserver is launched on the only unallocated port, 49140
266: port map begins --------------------
first: 49140 second: 271
266: port map ends-------------------- <<< looks for a free port, but the 1 port is allocated to pid 271 still
266: No free port found in map!  <<< error returned to lldb
266: FreePortForProcess 271 49140 <<< it finally notices that kill() has happened
```
This does not happen debugging locally on real hardware.

I discovered this running some of the SVE tests again. They run the debugee once to discover the supported vector lengths and then again to run the actual test case. Adding a `sleep(5)` in the test cases between those 2 runs also "fixes" the issue.

The workaround is to not use a port map at all, but often giving full network access to a VM is difficult. So I'd like to find a way to make this work, or at least work around it in the tests most likely to be run this way.

### PR DESCRIPTION
**Pull request by slydiman**
`lldb-server platform --server` works on Windows now w/o multithreading. The rest functionality remains unchanged.

Fixes #90923, fixes #56346.

This is the part 1 of the replacement of #100670.

In the part 2 I plan to switch `lldb-server gdbserver` to use `--fd` and listen a common gdb port for all gdbserver connections. Then we can remove gdb port mapping to fiх #97537.

### CODE REVIEW

**Comment by slydiman** [comment]
Note GDBRemoteCommunicationServerPlatform::DebugserverProcessReaped() may cause a crash if this callback will be called from the child monitor thread after destroing the instance of GDBRemoteCommunicationServerPlatform. It is impossible to control this thread anyway.
Hope I will fix it in the part 2 removing m_port_map. m_spawned_pids may be static since we have one GDBRemoteCommunicationServerPlatform instance per process.

File: lldb/source/Host/windows/PipeWindows.cpp [hunk 1]
```diff
@@ -283,54 +293,94 @@ Status PipeWindows::ReadWithTimeout(void *buf, size_t size,
...
-    bool failed = true;
-    DWORD failure_error = ::GetLastError();
-    if (wait_result == WAIT_TIMEOUT) {
-      BOOL cancel_result = CancelIoEx(m_read, &m_read_overlapped);
-      if (!cancel_result && GetLastError() == ERROR_NOT_FOUND)
-        failed = false;
+  if (!result) {
+    if (GetLastError() != ERROR_IO_PENDING)
+      return Status(::GetLastError(), eErrorTypeWin32);
+    else {
```
Comment (DavidSpickett) [inline lldb/source/Host/windows/PipeWindows.cpp:299]: Don't need the else given that the line above is a return.

File: lldb/source/Host/windows/PipeWindows.cpp [hunk 2]
```diff
@@ -283,54 +293,94 @@ Status PipeWindows::ReadWithTimeout(void *buf, size_t size,
...
-    // hapens, CancelIoEx will fail and return ERROR_NOT_FOUND. If that
-    // happens, the original operation should be considered to have been
-    // successful.
-    bool failed = true;
-    DWORD failure_error = ::GetLastError();
-    if (wait_result == WAIT_TIMEOUT) {
-      BOOL cancel_result = CancelIoEx(m_read, &m_read_overlapped);
-      if (!cancel_result && GetLastError() == ERROR_NOT_FOUND)
-        failed = false;
+  if (!result) {
```
Comment (DavidSpickett) [inline lldb/source/Host/windows/PipeWindows.cpp:296]: Could do an early return here `if (result) {`. You'll have 2 copies of:
```
bytes_read = sys_bytes_read;
return Status();
```
But it could be easier to read.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 3]
```diff
@@ -159,6 +159,40 @@ GDBRemoteCommunicationServerPlatform::GDBRemoteCommunicationServerPlatform(
...
+
+  if (args.GetArgumentCount() > 0) {
+    lldb::pid_t pid = LLDB_INVALID_PROCESS_ID;
+    std::optional<uint16_t> port;
+    std::string socket_name;
+    Status error = LaunchGDBServer(args,
+                                   "", // hostname
+                                   pid, port, socket_name);
+    if (error.Success())
+      SetPendingGdbServer(pid, *port, socket_name);
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:175]: What happens with the implicit `else` part of this, does `GetPacketAndSendResponse` somehow fail immediately?

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 4]
```diff
@@ -159,6 +159,40 @@ GDBRemoteCommunicationServerPlatform::GDBRemoteCommunicationServerPlatform(
...
+        GDBRemoteCommunication::PacketResult::Success)
+      break;
+  }
+
+  if (error.Fail()) {
+    Log *log = GetLog(LLDBLog::Platform);
+    LLDB_LOGF(log,
+              "GDBRemoteCommunicationServerPlatform::%s() "
+              "GetPacketAndSendResponse: %s",
+              __FUNCTION__, error.AsCString());
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:192]: I would've thought that `__FUNCTION__` gave you the function name here but maybe not. Can you just try making it `if (true)` and confirm what it prints?

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 5]
```diff
@@ -159,6 +159,40 @@ GDBRemoteCommunicationServerPlatform::GDBRemoteCommunicationServerPlatform(
 GDBRemoteCommunicationServerPlatform::~GDBRemoteCommunicationServerPlatform() =
     default;
 
+void GDBRemoteCommunicationServerPlatform::Proc(
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:162]: If we're changing the name could we have a better name than `Proc`, or if `Proc` is just a term I am unfamiliar with, a comment in the header to explain what this function does?

File: lldb/tools/lldb-server/LLDBServerUtilities.cpp [hunk 6]
```diff
@@ -27,11 +27,13 @@ class TestLogHandler : public LogHandler {
       : m_stream_sp(stream_sp) {}
 
   void Emit(llvm::StringRef message) override {
+    std::lock_guard<std::mutex> guard(m_mutex);
```
Comment (DavidSpickett) [inline lldb/tools/lldb-server/LLDBServerUtilities.cpp:30]: A mutex is now required because of the sharing of the socket I assume?

Could you add a comment on the member variable to say that as well.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 7]
```diff
@@ -114,6 +120,218 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+    LLDB_LOGF(log,
+              "lldb-platform child: "
+              "socket_pipe(0x%x).ReadWithTimeout(WSAPROTOCOL_INFO) failed: %s",
+              accept_fd, error.AsCString());
+    exit(SOCKET_ERROR);
+  }
+  if (num_bytes != sizeof(protocol_info)) {
+    LLDB_LOGF(log,
+              "lldb-platform child: "
+              "socket_pipe(0x%x).ReadWithTimeout(WSAPROTOCOL_INFO) failed: "
```
Comment (DavidSpickett) [inline lldb/tools/lldb-server/lldb-platform.cpp:307]: This is missing accept_fd for the first %x I think.

**Review by DavidSpickett — COMMENTED** [review]
What, if any, are the changes to how you would run lldb-server on Windows? I see a new argument here but not sure if that's only meant for lldb-server to pass to itself when it starts a child process.

**Comment by DavidSpickett** [comment]
What exactly does `lldb-server --server` mean? Because at least on Linux I see:
```
$ ./bin/lldb-server
Usage:
  ./bin/lldb-server v[ersion]
  ./bin/lldb-server g[dbserver] [options]
  ./bin/lldb-server p[latform] [options]
Invoke subcommand for additional help
```
Maybe you just have a typo or `--server` is a shortcut for one of those.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 8]
```diff
@@ -114,6 +120,218 @@ static Status save_socket_id_to_file(const std::string &socket_id,
   return status;
 }
 
+static GDBRemoteCommunicationServerPlatform::PortMap gdbserver_portmap;
+static std::mutex gdbserver_portmap_mutex;
+
+#if defined(_WIN32)
```
Comment (DavidSpickett) [inline lldb/tools/lldb-server/lldb-platform.cpp:126]: Do you think we will always have these large __WIN32 blocks, or if we go forward with your plan, will some of that become generic code once again?

**Review by labath — COMMENTED** [review]
I think we should slow down a bit.

For consistency, and to minimize the number of ifdefs, I believe windows and non-windows paths should use as similar approaches as possible. That means I think the end state should be that the posix path also uses a fork+exec approach.

For me, it also seems natural that this should be the first step. While doing that, we can make sure to create abstractions that can be used to implement the windows behavior as well. I'm imagining some sort of a function or a class, which takes the target binary, its arguments, and a socket, and launches that binary with that socket. (we'll probably also need a similar function/class on the other end to receive that socket).

The function doesn't have to be terribly generic, but it ideally should encompass all of platform specific behavior, so that the surrounding code does not need to use ifdefs. (But, ideally, it should at least be slightly generic, so that one can write a unit test for this functionality).

(BTW, I'm OOO for the rest of the week, so I won't be able to review this in detail. Upon cursory inspection, the general idea makes sense, but we really need to figure out how to encapsulate this. I'm not sure if we really need the WriteWithTimeout functionality. The reason we don't have it so far is that pipes have a buffer, and unless we're writing a huge chunk of data, the write will never block anyway. There's nothing wrong with it in principle though, and if you do want to have it, it'd be best if it comes with in its own patch and with a test.)

**Comment by slydiman** [comment]
> What exactly does `lldb-server --server` mean?

Sorry. I have updated the description with  `lldb-server platform --server`.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 8 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp:126]: We can move this code to some windows specific directory. But it is windows specific anyway. Note it contains a lot of `lldb-server platform` specific parameters. We can just pass the socket FD via the command line on non-Windows OS. `lldb-server gdbserver` already supports it with the parameter `--fd`. But it does not work on Windows. acceprt_fd here is a pipe FD which is used to transfer the structure WSAPROTOCOL_INFO. We need to know the child pid to initialize WSAPROTOCOL_INFO. Finally the child process is able to initialize the accepted socket FROM_PROTOCOL_INFO.

File: lldb/tools/lldb-server/LLDBServerUtilities.cpp (hunk 6 above)
Comment (slydiman) [reply lldb/tools/lldb-server/LLDBServerUtilities.cpp:30]: Probably I can separate this change to another patch. It is not related to the socket sharing. It is the fix of an old bug. 
Host::LaunchProcess() requires to SetMonitorProcessCallback. This callback is called from the child process monitor thread. We cannot control this thread. lldb-server may crash if there is a logging around this callback because TestLogHandler is not thread safe.
I've kept this code here for now because I faced this issue only debugging this patch with 100 simultaneous child processes. It is hard to reproduce it other way. Note also [this comment](https://github.com/llvm/llvm-project/pull/101283#issuecomment-2259628620).

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 5 above)
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:162]: Note `void SetInferiorArguments(const lldb_private::Args &args);` is a missing function. It is a bug. I have just removed it and added Proc(). There is no any connection between these functions. I have just moved a common code from lldb-platform to GDBRemoteCommunicationServerPlatform::Proc(). We can rename it to ClientHandle() or such and even kept inside lldb-platform.cpp

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 3 above)
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:175]: This code is just moved from lldb-platform.cpp 
GetPacketAndSendResponse() ignores `error` value. GetPacketAndSendResponse() must set the flag `quit` or `interrupt` and update `error`.

File: lldb/source/Host/windows/PipeWindows.cpp (hunk 1 above)
Comment (slydiman) [reply lldb/source/Host/windows/PipeWindows.cpp]: Thanks. Updated.

File: lldb/source/Host/windows/PipeWindows.cpp (hunk 2 above)
Comment (slydiman) [reply lldb/source/Host/windows/PipeWindows.cpp]: Thanks. Updated.

**Comment by slydiman** [comment]
> What, if any, are the changes to how you would run lldb-server on Windows? I see a new argument here but not sure if that's only meant for lldb-server to pass to itself when it starts a child process.

The explanation [is here](https://github.com/llvm/llvm-project/pull/101283#discussion_r1698289698). This new argument is the fork() workaround for Windows. We can keep this new argument for non-Windows OS, but it is redundant because fork() is enough.

**Comment by slydiman** [comment]
@labath 

> For consistency, and to minimize the number of ifdefs, I believe windows and non-windows paths should use as similar approaches as possible. That means I think the end state should be that the posix path also uses a fork+exec approach.

fork+exec on non-Windows OS is redundant. It simply does not make sence. We can use multithreading or CreateProcess on Windows. It seems [the multithreading solution](https://github.com/llvm/llvm-project/pull/100670) faced a lot of issues and system's bugs on Linux. So CreateProcess is the only way. But it is the fork() workaround for Windows.

> For me, it also seems natural that this should be the first step. While doing that, we can make sure to create abstractions that can be used to implement the windows behavior as well. I'm imagining some sort of a function or a class, which takes the target binary, its arguments, and a socket, and launches that binary with that socket. (we'll probably also need a similar function/class on the other end to receive that socket).

Look at GDBRemoteCommunication::StartDebugserverProcess(). I planed to extend it to use `pass_comm_fd` of Windows in the part 2. It is hard to create abstractions because of a lot of parameters. We can move most of SpawnProcessChild() code to `ConnectionFileDescriptor::ConnectFD` in ConnectionFileDescriptorPosix.cpp BTW, I don't like #ifdef _WIN32 in *Posix.cpp files. But currently the common ConnectionFileDescriptor.h contains `#include "lldb/Host/posix/ConnectionFileDescriptorPosix.h"`

> I'm not sure if we really need the WriteWithTimeout functionality. The reason we don't have it so far is that pipes have a buffer, and unless we're writing a huge chunk of data, the write will never block anyway. There's nothing wrong with it in principle though, and if you do want to have it, it'd be best if it comes with in its own patch and with a test.)

Before this patch the pipe read/write 1 byte in ConnectionFileDescriptor::CommandPipe. The maximal size was 6 bytes (the port value) in GDBRemoteCommunication::StartDebugserverProcess() and it is only the place where ReadWithTimeout() is used. But WSAPROTOCOL_INFO is big enough (628 bytes). Usually the pipe buffer is 4K. But we need an ability to avoid hangs anyway.
I agree that all pipe related changes may be moved to another patch. And we need to add WriteWithTimeout() to PipePosix too. Note there is not any test for Pipe now. And I have no idea how to test it, especially async version. Running `lldb-server platform --server` on Windows is the best test. It must be tested with a high load with multiple connections. Otherwise any pipe tests are useles.

**Comment by labath** [comment]
> @labath
> 
> > For consistency, and to minimize the number of ifdefs, I believe windows and non-windows paths should use as similar approaches as possible. That means I think the end state should be that the posix path also uses a fork+exec approach.
> 
> fork+exec on non-Windows OS is redundant. It simply does not make sence. We can use multithreading or CreateProcess on Windows. It seems [the multithreading solution](https://github.com/llvm/llvm-project/pull/100670) faced a lot of issues and system's bugs on Linux. So CreateProcess is the only way. But it is the fork() workaround for Windows.

This is where I'll have to disagree with you. The exec following the fork is not "redundant" on linux. A naked fork is an extremely dangerous thing in todays (multithreaded) applications. I'm absolutely certain that the improper use of fork with threads (and the FD leaks that go along with it) is the cause of at least one of the issues (ETXTBSY) you refer to as "system bugs", and fairly sure it's also the cause of the other one (the pipe workaround) as well. In a multithreaded application (which lldb-platform isn't right now, but more of an accident than design, and which you've tried to make extremely multithreaded) the only safe use of fork is if it is immediately followed by an exec, and this has to be done in an extremely careful way (we try to do that, and we still failed).

But even if it weren't for all of this, I'd still think it makes sense to start a new process, just for symmetry with windows. That's the nature of portable programming.

> 
> > For me, it also seems natural that this should be the first step. While doing that, we can make sure to create abstractions that can be used to implement the windows behavior as well. I'm imagining some sort of a function or a class, which takes the target binary, its arguments, and a socket, and launches that binary with that socket. (we'll probably also need a similar function/class on the other end to receive that socket).
> 
> Look at GDBRemoteCommunication::StartDebugserverProcess(). I planed to extend it to use `pass_comm_fd` of Windows in the part 2. It is hard to create abstractions because of a lot of parameters. We can move most of SpawnProcessChild() code to `ConnectionFileDescriptor::ConnectFD` in ConnectionFileDescriptorPosix.cpp BTW, I don't like #ifdef _WIN32 in *Posix.cpp files. But currently the common ConnectionFileDescriptor.h contains just `#include "lldb/Host/posix/ConnectionFileDescriptorPosix.h"`

I didn't say it was going to be easy. :) I can look at this closer when I get back next week, but I definitely think we can and should come up with a solution involving less ifdefs.

> 
> > I'm not sure if we really need the WriteWithTimeout functionality. The reason we don't have it so far is that pipes have a buffer, and unless we're writing a huge chunk of data, the write will never block anyway. There's nothing wrong with it in principle though, and if you do want to have it, it'd be best if it comes with in its own patch and with a test.)
> 
> Before this patch the pipe read/write 1 byte in ConnectionFileDescriptor::CommandPipe. The maximal size was 6 bytes (the port value) in GDBRemoteCommunication::StartDebugserverProcess() and it is only the place where ReadWithTimeout() is used. But WSAPROTOCOL_INFO is big enough (628 bytes). Usually the pipe buffer is 4K. 

628 is still less that 4k. Can the buffer be smaller than that?

> But we need an ability to avoid hangs anyway. I agree that all pipe related changes may be moved to another patch. And we need to add WriteWithTimeout() to PipePosix too. Note there is no any test for Pipe now. And I have no idea how to test it, especially async version. Running `lldb-server platform --server` on Windows is the best test. It must be tested with a high load with multiple connections. Otherwise any pipe tests are useles.

We have one and a half pipe tests (one of them claims to be broken on windows). I wrote them when fixing some Pipe bugs. We should definitely have more.

I wholeheartedly disagree with the assertion that the test is useless unless it uses multiple threads and high load. Even the most simple test serves as documents the correct/expected API usage and proves that the functionality works at least in the simple cases. For something like `WriteWithTimeout` I'd probably create single threaded test which does something like this:
- write to the pipe until it is full
- try to write with a larger timeout and check that it actually times out
- read from the pipe and check that you got back what was written

That will cover most of the codepaths and obvious ways it can go wrong (e.g. during refactoring). Then, if you wanted to be fancy, you could do things like start a write with a long timeout and then try to read from the pipe, and see that causes the write to complete, etc.; but I wouldn't expect everyone to write those all the time.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 7 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Thanks. Updated.

**Comment by slydiman** [comment]
@labath 
> one of the issues (ETXTBSY) you refer to as "system bugs"

I meant https://bugzilla.kernel.org/show_bug.cgi?id=546 and [this discussion](https://github.com/llvm/llvm-project/pull/100670/files#r1693201568). I'm sad that you don't believe. I concluded that no one uses the real multithreading on Linux. Someone tried and faced unsolvable problems. Therefore, #100670 is doomed.

**Comment by slydiman** [comment]
I have moved all Pipe related changes to #101383.

**Comment by labath** [comment]
> @labath
> 
> > This is where I'll have to disagree with you. The exec following the fork is not "redundant" on linux. A naked fork is an extremely dangerous thing in todays (multithreaded) applications. I'm absolutely certain that the improper use of fork with threads (and the FD leaks that go along with it) is the cause of at least one of the issues (ETXTBSY) you refer to as "system bugs", and fairly sure it's also the cause of the other one (the pipe workaround) as well. In a multithreaded application (which lldb-platform isn't right now, but more of an accident than design, and which you've tried to make extremely multithreaded) the only safe use of fork is if it is immediately followed by an exec, and this has to be done in an extremely careful way (we try to do that, and we still failed).
> 
> I meant https://bugzilla.kernel.org/show_bug.cgi?id=546 and [this discussion](https://github.com/llvm/llvm-project/pull/100670/files#r1693201568). I'm sad that you don't believe.

I know what you're referring to. However, that's a statement that comes with a very heavy burden of proof, one that you simply have not provided. The number of users of linux kernel exceeds the users of lldb by many orders of magnitude, so it's very unlikely that the problem is on their side. It's not that it's impossible -- I personally have tracked down lldb problems down to bugs in our dependencies -- from the libstdc++ to the kernel. However, this just doesn't look like one of those cases.

> I concluded that no one uses the real multithreading on Linux.

That's another very bold statement. I am not sure what you meant by "real multithreading", but I know for a fact that some Linux applications run thousands of threads in one process without any issues. All of them are very careful about how they use fork though.

> Someone tried and faced unsolvable problems. Therefore, #100670 is doomed.
> 
> > But even if it weren't for all of this, I'd still think it makes sense to start a new process, just for symmetry with windows. That's the nature of portable programming.
> 
> Not all code may be portable. It is better to use threads on Windows, but not on Posix. fork() is missing on Windows and starting a new process is a workaround. When we have the accepted socket and everything is ready to just handle the connection on Posix (after fork), you suggest to drop all initialized parameters, start a new process, pass all necessary parameters via the command line, initialize all parameters again, go to the same point and finally handle the connection. What is the reason? To be similar how it will work on Windows.

That is exactly what I'm suggesting.

> No, I don't agree.

Well, at least we can agree to disagree. ;)

> You are worried about some FD. But the main process `lldb-server platform` does not launch anything. There are no any FDs which may leak.

It forks. Forking duplicates any FD opened into the parent into the child. Even those marked with CLOEXEC, which is the usual way to guard against FD leakage. If you're single-threaded than this is manageable, but as soon as you have multiple threads (believe it or not, many applications on linux use multiple threads, and a lot of code creates background threads; lldb-server platform code executed here is pretty small, but it still calls into a lot of code that could create those), fork() becomes a ticking time bomb. In a multithreaded application, the only code that can be safely run after a fork, is that which can run in a signal handler. You can't write a server like that.

Using fork to serve multiple connections is a pattern from the seventies. Modern applications don't do it this way. As far as I'm concerned, this code should not have been written this way (and if the author cared about windows, they would have never done it), and I'd support removing this pattern even if it weren't for windows.

> We can't unify socket sharing nicely for Windows and Posix. We can try to combine the common code in the part 2 of this patch when the socket sharing will be added to GDBRemoteCommunication::StartDebugserverProcess() too.

That's nice, but I think we should figure out how to reduce the number of ifdefs in this patch. Porting linux away from fork may not be your concern, but figuring out how to make the code less branchy is. If you can do that without removing forks, I can take it upon myself to handle the rest. I just think it would be easier to do it both together...

**Comment by slydiman** [comment]
@labath 
>That's nice, but I think we should figure out how to reduce the number of ifdefs in this patch. Porting linux away from fork may not be your concern, but figuring out how to make the code less branchy is. If you can do that without removing forks, I can take it upon myself to handle the rest. I just think it would be easier to do it both together...

`#ifdef _WIN32` is used here for the following
- declare and initialize the parameter --accept (accept_fd)
- call spawn_process_child() and exit if accept_fd is defined
- call spawn_process_parent() instead of fork()

We can unify spawn_process_child() moving it to ConnectionFileDescriptor::ConnectFD() in ConnectionFileDescriptorPosix.cpp with `#ifdef _WIN32`.

Note I will remove `#ifndef _WIN32` around ::waitpid() in lldb-platform.cpp in the part 2 of this patch.
We still need spawn_process_reaped() here but I will remove it in part 2 too. Any static dummy will be enough.
For now we need spawn_process_reaped() here for `gdbserver_portmap.FreePortForProcess(pid);`.

We can try to move spawn_process_parent() to `lldb/source/Host/windows/` and probably a part to `lldb/source/Host/posix/`.
Where is the best place? HostProcess*.cpp, ProcessLauncher*.cpp?
It is necessary to implement some callback for spawn_process_reaped(), which will be removed in part 2.
It looks like a redundant work now.

Probably it is necessary to define a new type and an invalid value for accept_fd. It is int (socket fd) on Posix and pipe_t (HANDLE) on Windows.
What is the best type name and what is the best place to define it?

I would be happy to keep it as is till part 2 of this patch to minimize a redundant work.

**Comment by slydiman** [comment]
I have updated the patch to spawn the child process on non-Windows too and minimized the number of `#ifdef _WIN32`.

**Comment by labath** [comment]
I would start looking at this from the other end. Let's identify logical pieces of functionality that can be shared between the various modes of operation (fork/exec/singleserver), and try to refactor to code to fit that. While doing that, I think an important criteria should be whether some of the code is platform-specific. If it is, the function containing that should be as small as possible so that the ifdef doesn't occur in a deeply nested code (deeply nested ifdefs are much harder to reason about than one that occurs at the top level.

The first obvious piece of functionality I see is the one which serves a single connection. This is something we need to execute in all three code paths. It should definitely be a function of its own (I'm going to call it `ServeSingleConnection` here, but there may be a name that better fits local conventions), so that we can just call it, instead of reaching it through a web of compile and runtime conditionals.

The second one is the piece that serves multiple connections (let's call it `ServeManyConnections`) and handles handing them off to subprocesses. This one is tricky because it going to be platform specific. I'm not clear on whether it should be a single function with embedded ifdefs or two implementations of a single function, but I think it should be as small as possible so that the platform specificities really stand out.

I would try to implement it as something like this (where the two functions in the while loop are platform-specific code):
```
void ServeManyConnections(...) {
  while (conn = AcceptNewConnection()) {
    ServeInSubprocess(conn);
    ReapSubprocessesIfNeeded();
  }
}
```

... but I can also image other schemes. (BTW, I don't think you can get rid of the waitpid calls completely, as you need to reap the zombies even if you're not going to do anything with them).

Then I think we can structure the main (or something main-like) function as something like:
```
int main() {
  ...

  if (getting_connection_from_parent)
    return AcceptConnectionFromParent(...); // retrieves the connection and calls ServeSingleConnection

  if (!server_mode) // no --server flag
    return ServeSingleConnection(...)

  return ServeManyConnections(...);
}
```

I know this is handwavy, but that's sort of the goal I think we should aim for. It will get messier once all of the arguments (which I've conveniently ignored here) get added, but feel free to add structs or classes to group things as they make sense. Once we have this, I think it will also be clearer which code (if any) we want to put in some common libraries. Doing everything at once also may not be the best idea -- I can totally see how a preparatory patch which just refactors things without adding windows support would make sense here.

(Also @DavidSpickett, feel free to chime in, I shouldn't be the only one dictating conditions here.:)

**Comment by labath** [comment]
We raced updating the PR, so I didn't see the new version. I think the new version is looking better. I'm going to comment in more detail soon.

**Comment by slydiman** [comment]
@labath Please look at the updated patch.
ServeSingleConnection() = client_handle()
AcceptConnectionFromParent() = some code + client_handle()
ServeInSubprocess() = spawn_process()

lldb-platform.cpp is simple. Currently we don't see the whole picture before the part 2 of this patch. The socket sharing for `lldb-server gdbserver` from GDBRemoteCommunication::StartDebugserverProcess() is much more complicated. And we need to update the acceptor to listen 2 ports in the same thread. I think we should implement the new functionality first and then we can optimize it.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 9]
```diff
@@ -44,6 +47,14 @@ using namespace llvm;
 
 // option descriptors for getopt_long_only()
 
+#ifdef _WIN32
+typedef pipe_t fd_t;
+#define kInvalidFD (LLDB_INVALID_PIPE)
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:52]: Lets make this a real constant (not a macro).

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 10]
```diff
@@ -60,6 +71,7 @@ static struct option g_long_options[] = {
     {"max-gdbserver-port", required_argument, nullptr, 'M'},
     {"socket-file", required_argument, nullptr, 'f'},
     {"server", no_argument, &g_server, 1},
+    {"fd", required_argument, nullptr, 'd'},
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:74]: We don't expect this option to be used by the end user (at least not on windows, where the passing algorithm is quite complex), right?

If so, then I think we should drop the short option (the field is `int`, so I believe you can just use number not corresponding to a printable char), and use something longer for the long option -- to reduce the likelyhood of someone using this by mistake. I'd go with something like `--child-platform-fd`..

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 11]
```diff
@@ -114,6 +126,175 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+}
+
+static Status spawn_process(const char *progname, Connection *conn,
+                            uint16_t gdb_port, uint16_t port_offset,
+                            const lldb_private::Args &args,
+                            const std::string &log_file,
+                            const StringRef log_channels) {
+  Status error;
+  const TCPSocket &tcpSocket =
+      static_cast<const TCPSocket &>(*conn->GetReadObject());
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:175]: Other types of connections can be used here (at least on unixen, anyway). The cast should only be necessary on windows (and even there, the code should probably check the type first).

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 12]
```diff
@@ -114,6 +126,175 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+  {
+    std::lock_guard<std::mutex> guard(gdbserver_portmap_mutex);
+    gdbserver_portmap.AssociatePortWithProcess(gdb_port, child_pid);
+  }
+
+#ifdef _WIN32
+  // Transfer WSAPROTOCOL_INFO to the child process.
+  if (socket_pipe.CanRead())
+    socket_pipe.CloseReadFileDescriptor();
+  if (!socket_pipe.CanWrite()) {
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:268]: When can these fail? I would expect these to always hold and not even be worthy of an assert..

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 13]
```diff
@@ -114,6 +126,175 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+                            const StringRef log_channels) {
+  Status error;
+  const TCPSocket &tcpSocket =
+      static_cast<const TCPSocket &>(*conn->GetReadObject());
+  NativeSocket socket = tcpSocket.GetNativeSocket();
+
+  ProcessLaunchInfo launch_info;
+
+  fd_t fd;
+#ifdef _WIN32
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:181]: I think these two ifdefs in this function could be extracted to a separate class. I'm imagining something with a constructor which takes the `Connection` object (maybe also the ProcessLaunchInfo), and two methods that:
- return the number that should be passed to the subprocess via arguments (the unix version will just pass the connection fd). `GetSendableFD` ?
- finish the sending after the new process is started (unix version would be a noop). `CompleteSending` ?

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 14]
```diff
@@ -114,6 +126,175 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+  WSAPROTOCOL_INFO protocol_info;
+  if (::WSADuplicateSocket(socket, child_pid, &protocol_info) == SOCKET_ERROR) {
+    int last_error = ::WSAGetLastError();
+    Host::Kill(child_pid, SIGTERM);
+    return Status("WSADuplicateSocket() failed, error: %d", last_error);
+  }
+
+  size_t num_bytes;
+  error = socket_pipe.WriteWithTimeout(&protocol_info, sizeof(protocol_info),
+                                       std::chrono::seconds(2), num_bytes);
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:282]: 2 seconds seems a bit on the low side. Since this fits in the pipe buffer, I guess it will never block in practice , but if it did, 2 seconds might not be enough on a loaded machine. I'd put 10s, just to prevent anyone from guessing if this is the source of the flakyness.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 15]
```diff
@@ -254,6 +445,65 @@ int main_platform(int argc, char *argv[]) {
...
+    // Child process will handle the connection and exit.
+    Log *log = GetLog(LLDBLog::Platform);
+    if (!listen_host_port.empty()) {
+      LLDB_LOGF(log, "lldb-platform child: "
+                     "ambiguous parameters --listen and --fd");
+      return socket_error;
+    }
+
+    NativeSocket socket;
+#ifdef _WIN32
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:458]: And I think this could be a static method on the class I described above. `CompleteReceiving` ?

**Review by labath — COMMENTED** [review]
I actually quite like this. I think we should further merge the platform specific code into one place (which, among other things, will reduce the total number of ifdefs to ~one, and put all of the socket handling code next to each other), but apart from that, I think this is great (all things considered, etc).

**Comment by labath** [comment]
Also, if any of this code is not tested (outside of running the entire test suite in the remote mode) we should add a dedicated test for it. A quick search found at least one (test/API/tools/lldb-server/TestGdbRemoteCompletion.py) test which would appear to exercise this, but maybe there's room for more.

**Comment by slydiman** [comment]
@labath I have added the class SharedSocket. I have implemented all the recommendations.
Note we have the buildbot for cross tests (Windows x64/Linux x64 host and Linux Aarch64 target).
So everything is tested. Hope 1191 API tests run with this lldb-server are enough.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 16]
```diff
@@ -44,6 +47,112 @@ using namespace llvm;
...
+    if (error.Fail())
+      return error;
+    if (num_bytes != sizeof(protocol_info))
+      return Status("WriteWithTimeout(WSAPROTOCOL_INFO) failed: %d bytes",
+                    num_bytes);
+#endif
+    return Status();
+  }
+
+  Status GetNativeSocket(NativeSocket &socket) {
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:116]: I think this would be better off as a static function -- it's not using any of the members except m_fd, which could just as easily be a function argument, and it's duplicating the Pipe and NativeSocket members as local vars.

I can also imagine with a proper member function version of it, but then I think should reuse the members in the class. For example, by putting most of this work into the constructor, where it will initialize the m_pipe member and use it to receive the NativeSocket. `GetNativeSocket` could then be a plain getter (?)

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 17]
```diff
@@ -114,6 +224,133 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+    self_args.AppendArguments(args);
+  }
+
+  launch_info.SetLaunchInSeparateProcessGroup(false);
+  launch_info.SetMonitorProcessCallback(&spawn_process_reaped);
+
+  // Copy the current environment.
+  // WSASocket(FROM_PROTOCOL_INFO) will fail in the child process
+  // with the error WSAEPROVIDERFAILEDINIT if the SystemRoot is missing
+  // in the environment.
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:311]: FWIW, I don't think this requires any special justification. Environment inheritance is the default behavior when launching processes. I'd just delete this comment.

**Review by labath — COMMENTED** [review]
> @labath I have added the class SharedSocket. I have implemented all the recommendations.

Looks mostly fine. Just a couple of notes. David, what do you think?


> Note we have the buildbot for cross tests (Windows x64/Linux x64 host and Linux Aarch64 target).
> So everything is tested. Hope 1191 API tests run with this lldb-server are enough.

That's great, but I don't think this should be the only way this code is tested, as most of it can be tested perfectly well locally. Most of the devs will not be running this bot configuration before they push their patches, and they will not know how to set it up when they get the breakage email, so it's always better to have a first line of defense that everyone can use, and leave the cross testing for catching subtle integration details.

That said, we do have that one test which should exercise most of this code, so I'm sort of fine with this for now, but I still may ask for more tests in the future, for example, when we librarize this code.

**Review by labath — APPROVED** [review]
This looks good. Thanks for your patience.
