### PR TITLE
[clang-format] Fix qualifier ordering for lines after PP directives

### LINKED ISSUE #160487: [clang-format] Bug `QualifierOrder` option doesn't work
`.clang-format`:
```yaml
QualifierAlignment: Custom
QualifierOrder: [static, inline, const, type]
```

```c
#if 1
void foo(int const par);
int const var1;
#endif

int const var2;
```
Get formatted into:
```c
#if 1
void foo(const int par);
const int var1;
#endif

int const var2;
```

As you can see `const` has been moved to the left, but for some reason `int const var2;` did not change.

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Lines appearing after preprocessor conditional blocks (like `#endif`) were not having their qualifiers reordered by `QualifierOrder`, while lines inside the conditional blocks were processed correctly.

The issue was that tokens on lines following preprocessor directives have `MustBreakBefore` = `true`. The qualifier alignment logic was breaking immediately upon encountering any token with `MustBreakBefore` = `true`, preventing analysis of the entire line.

The fix allows processing to continue when `MustBreakBefore` = `true` on the first token of a line, since this is expected behavior (the token legitimately starts a new line). Only tokens with `MustBreakBefore` = `true` that appear mid-line will cause the analysis loop to break.

Fixes https://github.com/llvm/llvm-project/issues/160487.

CC @owenca.

### CODE REVIEW

File: clang/unittests/Format/QualifierFixerTest.cpp [hunk 1]
```diff
@@ -1195,6 +1195,41 @@ TEST_F(QualifierFixerTest, QualifiersBrokenUpByPPDirectives) {
...
+               "\n"
+               "const int var2;\n"
+               "const int var3;\n",
+               "#if 1\n"
+               "void foo(int const par);\n"
+               "int const var1;\n"
+               "#endif\n"
+               "\n"
+               "int const var2;\n"
+               "int const var3;\n",
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/QualifierFixerTest.cpp:1216]:
```suggestion
               "const int var3;",
               "#if 1\n"
               "void foo(int const par);\n"
               "int const var1;\n"
               "#endif\n"
               "\n"
               "int const var2;\n"
               "int const var3;",
```

**Review by owenca — APPROVED** [review]
