### PR TITLE
[clang-format] Fix operator overload inconsistency in `BreakAfterAttributes: Always`

### LINKED ISSUE #74901: [clang-format] `BreakAfterAttributes: Always` Inconsistency with operator overload
With `BreakAfterAttributes: Always` the following code:
```cpp
class Test {
    [[nodiscard]] Test& operator+(const Test&);
    [[nodiscard]] Test& test(const Test&);
};
[[nodiscard]] Test& operator-(const Test&);
```
gets formated to this:
```cpp
class Test {
    [[nodiscard]]
    Test&
    operator+(const Test&);
    [[nodiscard]]
    Test& test(const Test&);
};
[[nodiscard]] 
Test& 
operator-(const Test&);
```
This option formats a member function correctly, but it forces a operator overload to break after the return type.

If `PointerAlignment: Left` or `ReferenceAlignment: Left` is used together, the non-member operator overloaded is completely ignored and is not formated like this:
```cpp
class Test {
  [[nodiscard]]
  Test&
  operator+(const Test&);
  [[nodiscard]]
  Test& test(const Test&);
};
[[nodiscard]] Test& operator-(const Test&);

```
Using `clang-format version 18.0.0 (https://github.com/llvm/llvm-project.git a6c02edd6eac476523b5c73f29619a7a9e054872)`

### PR DESCRIPTION
**Pull request by XDeme1**
Fixes llvm/llvm-project#74901

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -26417,6 +26417,20 @@ TEST_F(FormatTest, BreakAfterAttributes) {
                "void g() {}",
                CtorDtorCode, Style);
 
+  Style.ReferenceAlignment = FormatStyle::ReferenceAlignmentStyle::RAS_Left;
+  constexpr StringRef OperatorOverloadCode(
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp:26421]: Don't put the code into a variable, you are only using it once.

File: clang/unittests/Format/FormatTest.cpp [hunk 2]
```diff
@@ -26417,6 +26417,20 @@ TEST_F(FormatTest, BreakAfterAttributes) {
                "void g() {}",
                CtorDtorCode, Style);
 
+  Style.ReferenceAlignment = FormatStyle::ReferenceAlignmentStyle::RAS_Left;
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp:26420]: You are changing the style for all following tests. (Although it may not have an effect on them.) I don't think you should do that.

Put your test at the bottom, or restore the value.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 3]
```diff
@@ -593,7 +593,8 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
         // name.
         !Style.isJavaScript()) ||
        (Current.is(tok::kw_operator) && Previous.isNot(tok::coloncolon))) &&
-      Previous.isNot(tok::kw_template) && CurrentState.BreakBeforeParameter) {
+      Previous.isNot(tok::kw_template) && CurrentState.BreakBeforeParameter &&
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:596]: Not your fault, but I'm not trying to read this condition. Can you make it more readable? We typically use a lambda and early `return false`.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 4]
```diff
@@ -593,7 +593,8 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
...
+      (Style.isCpp() && Current.Tok.isNot(tok::kw_operator))) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:597]: Two things, you don't need the parenthesis, you are already in a conjunction.
Does it affect the other languages, that you now add a check for `isCpp()`?

Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp:597]: I am not sure if affects other languages, so put it there. I will remove it

File: clang/unittests/Format/FormatTest.cpp (hunk 2 above)
Comment (XDeme) [reply clang/unittests/Format/FormatTest.cpp:26420]: To restore the value, is it ok if I do it like this: `Style.ReferenceAlignment = getLLVMStyle().ReferenceAlignment;`?

Comment (XDeme) [reply clang/unittests/Format/FormatTest.cpp:26420]: Changed verifyFormat -> verifyNoChange, to place the expected output only.
Restored value with `getLLVMStyle().ReferenceAlignment`, if this is not ok, I can substitute with `FormatStyle::ReferenceAlignmentStyle::RAS_Pointer`

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 4 above)
Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp]: Fixed

File: clang/unittests/Format/FormatTest.cpp (hunk 1 above)
Comment (XDeme) [reply clang/unittests/Format/FormatTest.cpp]: Fixed

File: clang/unittests/Format/FormatTest.cpp (hunk 2 above)
Comment (XDeme) [reply clang/unittests/Format/FormatTest.cpp]: Fixed, Moved test to the bottom

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 3 above)
Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp]: I tried to simplify the checks.

File: clang/unittests/Format/FormatTest.cpp [hunk 5]
```diff
@@ -26465,6 +26451,21 @@ TEST_F(FormatTest, BreakAfterAttributes) {
...
+
+  Style.BreakBeforeBraces = FormatStyle::BS_Attach;
+  Style.ReferenceAlignment = FormatStyle::ReferenceAlignmentStyle::RAS_Left;
+  verifyFormat("struct Foo {\n"
+                 "  [[maybe_unused]]\n"
+                 "  void operator+();\n"
+                 "};\n"
+                 "[[nodiscard]]\n"
+                 "Foo& operator-(Foo&);",
+
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp:26463]: Remove the blank line.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 6]
```diff
@@ -583,21 +583,31 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
...
+    // If the return type spans multiple lines, wrap before the function name.
+    if (Current.isNot(TT_FunctionDeclarationName) ||
+        State.Line->ReturnTypeWrapped) {
+      return false;
+    }
+    if (Previous.is(tok::kw_template) || Current.is(tok::kw_operator))
+      return false;
+    if (!CurrentState.BreakBeforeParameter)
+      return false;
+    return true;
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:596]:
```suggestion
    // Don't break before a C# function when no break after return type.
    return (!Style.isCSharp() ||
         Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
        // Don't always break between a JavaScript `function` and the function
        // name.
        !Style.isJavaScript();
```

Don't call the lambda twice.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 7]
```diff
@@ -583,20 +583,31 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
...
-        !State.Line->ReturnTypeWrapped &&
-        // Don't break before a C# function when no break after return type.
-        (!Style.isCSharp() ||
-         Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
-        // Don't always break between a JavaScript `function` and the function
-        // name.
-        !Style.isJavaScript()) ||
-       (Current.is(tok::kw_operator) && Previous.isNot(tok::coloncolon))) &&
-      Previous.isNot(tok::kw_template) && CurrentState.BreakBeforeParameter) {
+  const auto WrapBeforeName = [&]() {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:586]:
```suggestion
  const auto WrapBeforeName = [&] {
```
I think LLVM style is to omit the empty parenthesis.

Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:586]: Okay as far as I can see the conditions are transformed correctly, thanks for that.

But there is no addition from you, or am I missing something? Is the problem already fixed?

Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp:586]: The original condition could be rewritten like this:
```cpp
  const auto WrapBeforeName = [&] {
    if(Previous.is(tok::kw_template) || !CurrentState.BreakBeforeParameter)
      return false;
    if((Current.isNot(tok::kw_operator) || Previous.is(tok::coloncolon)) && (Current.isNot(TT_FunctionDeclarationName) || State.Line->ReturnTypeWrapped))
      return false;
    // Don't break before a C# function when no break after return type.
    return (!Style.isCSharp() ||
            Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
           // Don't always break between a JavaScript `function` and the
           // function name.
           !Style.isJavaScript();
  };
```

The problem is that `Current.isNot(tok::kw_operator)` is returning false and then the last check will return true, forcing the return type of a operator overload to wrap.
We could fix this by adding a `Curret.is(tok::kw_operator) return false` before that line like this:
```cpp
  const auto WrapBeforeName = [&] {
    if(Previous.is(tok::kw_template) || !CurrentState.BreakBeforeParameter)
      return false;
    if(Current.is(tok::kw_operator))
      return false;
    if((Current.isNot(tok::kw_operator) || Previous.is(tok::coloncolon)) && (Current.isNot(TT_FunctionDeclarationName) || State.Line->ReturnTypeWrapped))
      return false;
    return (!Style.isCSharp() ||
            Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
           // Don't always break between a JavaScript `function` and the
           // function name.
           !Style.isJavaScript();
  };
```

I am not sure what the original conditional was exactly checking for, but my change didn't break any test.

And for the `ReferenceAlignment: Left` with `BreakAfterAttributes: Always` not working on non-member operator overload, it fixed by just changing this condition.

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 6 above)
Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp]: Fixed

File: clang/unittests/Format/FormatTest.cpp (hunk 5 above)
Comment (XDeme) [reply clang/unittests/Format/FormatTest.cpp]: Fixed

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 7 above)
Comment (XDeme) [reply clang/lib/Format/ContinuationIndenter.cpp]: Fixed

**Comment by XDeme** [comment]
One thing that I checked only now, is that with clang-format 16.0.6 and 17.0.6, it formats correctly.
But with `clang-format version 18.0.0 (https://github.com/llvm/llvm-project.git a6c02edd6eac476523b5c73f29619a7a9e054872)` is doens't anymore, so this is a regression introduced recently.

**Comment by HazardyKnusperkeks** [comment]
I got a mail, but it seems you have deleted the comment? Is it a regression? Could you bisect it?

And you don't need (for me) to comment, when you addressed a comment, just click on resolved. Would reduce the amount of mails in my inbox. ;)

**Comment by XDeme** [comment]
Is it not a regression, I didn't verify the path of clang-format correctly, I thought I was using clang 16.0.6, but it was using the one I built

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 8]
```diff
@@ -583,20 +583,26 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
...
-  // If the return type spans multiple lines, wrap before the function name.
-  if (((Current.is(TT_FunctionDeclarationName) &&
-        !State.Line->ReturnTypeWrapped &&
-        // Don't break before a C# function when no break after return type.
-        (!Style.isCSharp() ||
-         Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
-        // Don't always break between a JavaScript `function` and the function
-        // name.
-        !Style.isJavaScript()) ||
-       (Current.is(tok::kw_operator) && Previous.isNot(tok::coloncolon))) &&
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:595]: Simply removing line 595 above seems to work:
```
  if (Current.is(TT_FunctionDeclarationName) &&
      !State.Line->ReturnTypeWrapped &&
      // Don't break before a C# function when no break after return type.
      (!Style.isCSharp() ||
       Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
      // Don't always break between a JavaScript `function` and the function
      // name.
      !Style.isJavaScript() && Previous.isNot(tok::kw_template) &&
      CurrentState.BreakBeforeParameter) {
    return true;
  }
```

File: clang/unittests/Format/FormatTest.cpp [hunk 9]
```diff
@@ -26451,6 +26451,20 @@ TEST_F(FormatTest, BreakAfterAttributes) {
...
+  verifyFormat("struct Foo {\n"
+               "  [[maybe_unused]]\n"
+               "  void operator+();\n"
+               "};\n"
+               "[[nodiscard]]\n"
+               "Foo& operator-(Foo&);",
+               "struct Foo {\n"
+               "[[maybe_unused]] void operator+();\n"
+               "};\n"
+               "[[nodiscard]] Foo &operator-(Foo&);",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:26466]: Please split the test cases and use the single argument version of `verifyFormat`, e.g.:
```suggestion
  verifyFormat("struct Foo {\n"
               "  [[maybe_unused]]\n"
               "  void operator+();\n"
               "};\n"
               "[[nodiscard]]\n"
               "Foo &operator-(Foo &);",
               Style);

  Style.ReferenceAlignment = FormatStyle::ReferenceAlignmentStyle::RAS_Left;
  verifyFormat("[[nodiscard]]\n"
               "Foo& operator-(Foo&);",
```

**Review by owenca — APPROVED** [review]
