### PR TITLE
[LoopInterchange] Fix handling of PHI which refers to another PHI

### LINKED ISSUE #193733: [LoopInterchange] Infinite loop when a PHI refers to another PHI
Reproducer ([godbolt](https://godbolt.org/z/Y5v4dj7Ye)):

```llvm
define void @f() {
entry:
  br label %outer.header

outer.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %outer.latch ]
  br label %inner

inner:
  %j = phi i64 [ 0, %outer.header ], [ %j.inc, %inner ]
  %k = phi i64 [ -1, %outer.header ], [ %j, %inner ]
  %j.inc = add i64 %j, 1
  %ec.j = icmp eq i64 %j.inc, 10
  br i1 %ec.j, label %outer.latch, label %inner

outer.latch:
  %i.inc = add i64 %i, 1
  %ec.i = icmp eq i64 %i.inc, 10
  br i1 %ec.i, label %exit, label %outer.header

exit:
  ret void
}
```

It seems that [this loop](https://github.com/llvm/llvm-project/blob/5a9d0cf7190f80096da0ef1f3c45b5ae0cd7f0d1/llvm/lib/Transforms/Scalar/LoopInterchange.cpp#L1967) never terminates.

### PR DESCRIPTION
**Pull request by kasuga-fj**
In the transformation phase, at first LoopInterchange moves several instructions in the inner loop into the new latch block. The instructions used as incoming values to the induction variables from the latch block are the targets of this movement. Previously, this process could result in an infinite loop when a PHI node refers to another PHI node, as in the following example:

```
%i = phi i64 [ 0, %entry ], [ %i.inc, %latch ]
%j = phi i64 [ 0, %entry ], [ %i, %latch ]
```

The root cause was that `%i` enqueued for processing because it is used by `%j`.
This patch fixes the issue by preventing induction variables from being enqueued into the movement list.
Fix #193733

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/LoopInterchange.cpp [hunk 1]
```diff
@@ -1945,12 +1944,13 @@ bool LoopInterchangeTransform::transform(
...
-            dyn_cast<Instruction>(CurInductionPHI->getIncomingValue(1)));
-      else
-        InnerIndexVarList.push_back(
-            dyn_cast<Instruction>(CurInductionPHI->getIncomingValue(0)));
+      Instruction *IncomingValue = dyn_cast<Instruction>(
+          CurInductionPHI->getIncomingValueForBlock(InnerLoop->getLoopLatch()));
+      if (any_of(InductionPHIs, [IncomingValue](PHINode *InductionPHI) {
+            return IncomingValue == InductionPHI;
+          }))
+        continue;
```
Comment (sjoerdmeijer) [inline llvm/lib/Transforms/Scalar/LoopInterchange.cpp:1952]: A couple of nits here:

A little comment here what we are trying to do is probably in order, so saying something along the lines of "skip IncomingValue if it is one of the induction Phis" will probably help. But thinking about it, maybe this becomes all trivial and unnecessary if we simplify this to:

```
   if (llvm::is_contained(InductionPHIs, IncomingValue))
       continue;
```

File: llvm/lib/Transforms/Scalar/LoopInterchange.cpp [hunk 2]
```diff
@@ -1945,12 +1944,13 @@ bool LoopInterchangeTransform::transform(
 
     SmallVector<Instruction *, 8> InnerIndexVarList;
     for (PHINode *CurInductionPHI : InductionPHIs) {
-      if (CurInductionPHI->getIncomingBlock(0) == InnerLoopPreHeader)
-        InnerIndexVarList.push_back(
-            dyn_cast<Instruction>(CurInductionPHI->getIncomingValue(1)));
-      else
-        InnerIndexVarList.push_back(
-            dyn_cast<Instruction>(CurInductionPHI->getIncomingValue(0)));
+      Instruction *IncomingValue = dyn_cast<Instruction>(
```
Comment (sjoerdmeijer) [inline llvm/lib/Transforms/Scalar/LoopInterchange.cpp:1947]: This was already present, but do we need an assert here in case the incoming value is not an instruction? Not sure if this can occur.

File: llvm/lib/Transforms/Scalar/LoopInterchange.cpp (hunk 1 above)
Comment (kasuga-fj) [reply llvm/lib/Transforms/Scalar/LoopInterchange.cpp:1952]: > maybe this becomes all trivial and unnecessary if we simplify this to:

Sounds good, replaced with that, thanks.

File: llvm/lib/Transforms/Scalar/LoopInterchange.cpp (hunk 2 above)
Comment (kasuga-fj) [reply llvm/lib/Transforms/Scalar/LoopInterchange.cpp:1947]: I'm also not sure if it can happen, but added an assert just in case.

**Review by sjoerdmeijer — APPROVED** [review]
LGTM.

Maybe wait a day in case @Meinersbur want to have a look too.

**Comment by kasuga-fj** [comment]
Looks like there are no further comments, so let me go ahead and merge.
@sjoerdmeijer Just for your information, I'll be away from my keyboard for about a week, so I won't be able to respond for a while.

**Comment by sjoerdmeijer** [comment]
Yeah, please go ahead with this, this should be a good and straightforward fix.

Thanks for letting know. I will go through your other outstanding merge request in the meantime, and now know when to expect a reply, cheers.
