### PR TITLE
[Clang] Support MSPropertyRefExpr as placement arg to new-expression

### LINKED ISSUE #65053: [clang] Overload resolution fails for `__declspec(property)` access in expression-list of new-placement
The following code (also on [godbolt](https://godbolt.org/z/nnMhb3MzM)) using the MS `__declspec(property)` extension fails to compile due to overload resolution failure

```c++
#include <new>

struct S {
   int get_value() { return 42; }
   __declspec(property(get = get_value)) int i;
   void* operator new(std::size_t, int);
};

void foo(int);

int main() {
    S s;
    foo(s.i);    // ok
    new (s.i) S; // error: no matching function for call to 'operator new'
}
```

with the following error message:

```
<source>:14:5: error: no matching function for call to 'operator new'
   14 |     new (s.i) S; // error: no matching function for call to 'operator new'
      |     ^   ~~~~~
<source>:6:10: note: candidate function not viable: no known conversion from '<pseudo-object type>' to 'int' for 2nd argument
    6 |    void* operator new(std::size_t, int);
      |          ^     
```

### PR DESCRIPTION
**Pull request by Sirraide**
It seems we were forgetting to call `checkArgsForPlaceholders` on the placement arguments of new-expressions in Sema. I don't think that was intended—at least doing so doesn't seem to break anything—so this pr adds that.

This also fixes #65053

### CODE REVIEW

**Comment by Sirraide** [comment]
CC @AaronBallman

File: clang/test/CodeGenCXX/ms-property-new.cpp [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  // CHECK-NEXT: call noundef ptr @"??2S@@SAPEAX_KH@Z"(i64 noundef 1, i32 noundef [[TI]])
+  new (ts->t) S;
+
+  // CHECK: [[R:%.+]] = call noundef double @"?GetR@?$TS@N@@QEAANNN@Z"(ptr {{[^,]*}} %{{.+}}, double {{[^,]*}}, double {{[^,]*}})
+  // CHECK-NEXT: [[RI:%.+]] = fptosi double [[R]] to i32
+  // CHECK-NEXT: call noundef ptr @"??2S@@SAPEAX_KH@Z"(i64 noundef 1, i32 noundef [[RI]])
+  new ((ts->r)[1][2]) S;
+}
+
+#endif
```
Comment (erichkeane) [inline clang/test/CodeGenCXX/ms-property-new.cpp:52]: need newlines at the end of the tests

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 2]
```diff
@@ -2286,6 +2286,9 @@ ExprResult Sema::BuildCXXNew(SourceRange Range, bool UseGlobal,
   bool PassAlignment = getLangOpts().AlignedAllocation &&
                        Alignment > NewAlignment;
 
+  if (CheckArgsForPlaceholders(PlacementArgs))
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExprCXX.cpp:2289]: This likely needs a good collection of tests to show what it changes for NON-property related 'new' operators.

File: clang/test/CodeGenCXX/ms-property-new.cpp (hunk 1 above)
Comment (Sirraide) [reply clang/test/CodeGenCXX/ms-property-new.cpp:52]: Ah yes, I always forget about that

File: clang/lib/Sema/SemaExprCXX.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: I’ll take a look at what other expressions are actually affected by this other than `MSPropertyRefExpr`s. (or do you mean we should just add more placement-new tests in general? Because I would assume we already have a bunch of those, but I haven’t checked to be fair?)

Comment (erichkeane) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: A bit of both, this should check the behavior of other expression types.  This changes general 'placement new' behaviors, so it looks like it changes existing placement new behaviors that are seemingly untested, so should be showing off  THOSE as well.

Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: Makes sense. It seems like this affects only a small number of builtin types, so in theory, adding tests for every expression that could possibly have those types ought to do (if we don’t already have tests for those); I’m currently collecting a list of everything that could be affected by this.

Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: The only expressions that this seems to affect is expressions for which `isPlaceholderToRemoveAsArg` returns `true` by passing them to `CheckPlaceholderExpr`; this only affects a handful of types:

- `BuiltinType::PseudoObject`: MSProperty (subscript) properties and ObjC (subscript) properties; the latter are only relevant for Objective-C++ in this case. I’ll add tests for the latter as well (to the best of my abilities as I have never written a line of Objective-C or Objective-C++ before in my life). The comment in `BuiltinTypes.def` also mentions ‘VS.NET's `__property` declarations’, but I couldn’t find anything about `__property` in the rest of the codebase, and I’m candidly not entirely sure what this is in reference to, so I’m only adding tests for Objective-C++ for now.
    
- `BuiltinType::UnknownAny`: For this, `CheckPlaceholderExpr` just emits an error, and I personally don’t see a way in which this would ever be valid as a placement-arg to a new expression, but I could be wrong here. Should we add tests for this case?

- `BuiltinType::BoundMember`: `s.foo` and friends, where `foo` is a non-static member function; these are already invalid in placement-args, and `CheckPlaceholderExpr` similarly issues what looks to be the exact same error; we don’t seem to have any tests that check for this error, however, so I’ll add some for this as well.

- `BuiltinType::BuiltinFn`: Only `DeclRefExpr`s are affected here as this simply issues an error otherwise (which should be fine because passing a builtin function as a function argument doesn’t make sense anyway); if it is a builtin such as `__builtin_memset`, then this pr also ends up improving the error message from ‘no known conversion from '<builtin fn type>'’ to ‘builtin functions must be directly called’.

    If it is a `DeclRefExpr`, there are two cases to consider: the first is the MS `__noop` builtin, which w/o this pr simply errors, but now, it is implicitly converted to a `CallExpr` that returns an `int` (which emits 0 in CG); this matches MSVCs behaviour, but I doubt we have a test for that, so I’ll add one as well.

    The only other case that is affected here is if we have a standard-namespace builtin (e.g. `std::move`, `std::forward_like`, which before C++20 resulted in a warning, since C++ in an error; this behaviour is unaffected by this change, but I’ll some tests for this as well because from what I can tell, there currently are no tests for this diagnostic at all.


- `BuiltinType::IncompleteMatrixIdx`: From what I can tell, this is used for [matrix types](https://clang.llvm.org/docs/MatrixTypes.html), specifically, for the type of an expression such as `a[1]` where `a` is a matrix type because matrix types always require two subscripts; since an expression of this type as a placement-arg is thus always invalid, this should error, but previously, we were emitting a less-than-ideal error (e.g. ‘no known conversion from '<incomplete matrix index type>' to 'int'’), whereas with this pr, we now get the error ‘single subscript expressions are not allowed for matrix values’. There does not seem to be a test for this that involves placement-new, so I’ll add a few as well.

- `BuiltinType::OMPArraySection`, `BuiltinType::OMPArrayShaping`, and `BuiltinType::OMPIterator`: To my understanding, these cannot occur outside of OMP `#pragma`s, so they’re not relevant here.

Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: tl;dr Overall, it seems like this pr also improves some error messages as well as support for MSVC’s `__noop` builtin. I’ll add some tests for the cases above (though again, for some of them, (e.g. the UnknownAny case), I’m not sure whether that’s necessary, so please let me know whether I should add some for those as well).

Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: Oh, and Objective-C++ properties were suffering from the same problem, so this now also fixes those in new-expressions.

Comment (Sirraide) [reply clang/lib/Sema/SemaExprCXX.cpp:2289]: Alright, just got done adding some tests. Just let me know if there are more things that we should consider testing. 

Also, regarding Objective-C++ properties: I tried following the examples in `clang/test/AST/ast-dump-expr-json.m`, but it didn’t seem to want to treat the subscripts as anything other than pointer arithmetic. It also doesn’t help that I’m not familiar w/ Objective-C/Objective-C++ at all. Could it be that Objective-C subscript properties are disabled in Objective-C++ mode?

File: clang/test/SemaCXX/builtin-std-move.cpp [hunk 3]
```diff
@@ -163,6 +170,40 @@ void attribute_const() {
   std::as_const(n); // expected-warning {{ignoring return value}}
 }
 
+struct D {
+  void* operator new(__SIZE_TYPE__, D&&(*)(D&));
+  void* operator new(__SIZE_TYPE__, D*(*)(D&));
+  void* operator new(__SIZE_TYPE__, const D&(*)(D&));
+};
+
+#if __cplusplus <= 201703L
```
Comment (erichkeane) [inline clang/test/SemaCXX/builtin-std-move.cpp:179]: I realize elsewhere does this... but please use `-verify=cpp20,expected` and `-verify=cpp17,expected`, then make these `cpp17-warning` and `cpp20-error`.

An NFC followup to clean up the other uses here would also be appreciated, but not necessary.  @Endilll has been doing similar cleanups elsewhere.

**Review by erichkeane — COMMENTED** [review]
1 issue with the test, else LGTM.

File: clang/test/SemaCXX/builtin-std-move.cpp (hunk 3 above)
Comment (Endilll) [reply clang/test/SemaCXX/builtin-std-move.cpp:179]: Here's a good example of every kind of `verify` prefixes I've been using in C++ DR tests:
https://github.com/llvm/llvm-project/blob/569ec185f5dc4a9e4a239948191977ecc2b2b475/clang/test/CXX/drs/dr6xx.cpp#L1-L6

Comment (Sirraide) [reply clang/test/SemaCXX/builtin-std-move.cpp]: Alright, done

File: clang/test/SemaCXX/builtin-std-move.cpp [hunk 4]
```diff
@@ -130,27 +137,24 @@ C &&(&rMove)(C&) = std::move; // #8 expected-note {{instantiation of}}
...
-// expected-error@#2 {{non-addressable}}
-// expected-error@#3 {{non-addressable}}
-// expected-error@#4 {{non-addressable}}
-// expected-error@#5 {{non-addressable}}
-// expected-error@#6 {{non-addressable}}
-// expected-error@#7 {{non-addressable}}
-// expected-error@#8 {{non-addressable}}
-// expected-error@#9 {{non-addressable}}
-#endif
+// cxx17-warning@#1 {{non-addressable}}
```
Comment (erichkeane) [inline clang/test/SemaCXX/builtin-std-move.cpp:140]: I might suggest 'collating' these a bit, that is, put all of the ones for the same line number 'next' to eachother, rather than by language mode.  But I don't feel too strongly.

**Review by erichkeane — APPROVED** [review]

File: clang/test/SemaCXX/builtin-std-move.cpp (hunk 4 above)
Comment (Endilll) [reply clang/test/SemaCXX/builtin-std-move.cpp:140]: I'd put them directly after the lines they are issues for, instead of gathering them in one place and asking readers to follow the markers. Then they will be naturally collated by line instead of language mode.

Comment (erichkeane) [reply clang/test/SemaCXX/builtin-std-move.cpp:140]: Even better!

**Review by erichkeane — APPROVED** [review]

File: clang/test/SemaCXX/builtin-std-move.cpp (hunk 4 above)
Comment (Sirraide) [reply clang/test/SemaCXX/builtin-std-move.cpp]: I’ve put them on the lines that cause the diagnostics and also aligned them because I found it to be too unreadable otherwise.

**Comment by Sirraide** [comment]
Just did a rebase and also updated the release notes to mention these changes

**Review by erichkeane — APPROVED** [review]

**Comment by Sirraide** [comment]
Just did another rebase to update the release notes. 

Is there anything else that needs to be done for this pr?

**Comment by erichkeane** [comment]
> Just did another rebase to update the release notes.
> 
> Is there anything else that needs to be done for this pr?

Nope!  Once the CI is done, feel free to Squash & Merge.

**Comment by Sirraide** [comment]
> Nope! Once the CI is done, feel free to Squash & Merge.

I would but I don’t have commit access, so someone else would have to do that for me. (Also, I do fear that in the time it takes for the CI jobs to complete, we’ll have another merge conflict w/ the release notes because they’re updated constantly.)

**Comment by erichkeane** [comment]
> > Nope! Once the CI is done, feel free to Squash & Merge.
> 
> I would but I don’t have commit access, so someone else would have to do that for me. (Also, I do fear that in the time it takes for the CI jobs to complete, we’ll have another merge conflict w/ the release notes because they’re updated constantly.)

I'll commit it when I see the CI done, and can do the release notes conflict.  I wont bother re-running after conflict resolution.

**Comment by Sirraide** [comment]
> I'll commit it when I see the CI done, and can do the release notes conflict. I wont bother re-running after conflict resolution.

Alright, thanks!

**Comment by Sirraide** [comment]
I’m curious, because I legitimately don’t know, is it common for CI on windows to take 9 hours?

image

**Comment by erichkeane** [comment]
> I’m curious, because I legitimately don’t know, is it common for CI on windows to take 9 hours?
> 
> image

It is unfortunately becoming more and more common.  The bot infrastructure is having trouble keeping up these days during the day.
