### PR TITLE
[flang] Don't associate pointers with zero sized storage targets

### LINKED ISSUE #155481: [flang] Incorrect result of `ASSOCIATED` when the pointer is associated with zero sized storage sequence
Consider the following code:
```
    type base
    end type

    type, extends (base) :: child
        integer(8) :: something
    end type

    class (*), pointer :: x, x1(:)

    type (child), target :: c1, c2(10)

    x => c1%base
    x1 => c2%base

    print*, associated (x, c1%base)
    print*, associated (x1, c2%base)
end
```

Flang outputs `T T`, but the expected output should be `F F` as the standard requires none zero sized storage sequence for intrinsic `ASSOCIATED` to return true.
```
Case (v): If TARGET is present and is a scalar target, the result is true if and only if TARGET is not a zero-sized storage sequence and POINTER is associated with a target that occupies the same storage units as TARGET.

Case (vi): If TARGET is present and is an array target, the result is true if and only if POINTER is associated with a target that has the same shape as TARGET, is neither of size zero nor an arraywhose elements are zero-sized storage sequences, and occupies the same storage units as TARGET in array element order.
```

### PR DESCRIPTION
**Pull request by eugeneepshteyn**
Fixes #155481

### CODE REVIEW

**Review by DanielCChen — APPROVED** [review]
LGTM.
It fixed all the test cases marked against this issue.
Thanks!

**Review by klausler — COMMENTED** [review]
Please run the llvm-test-suite before merging; I think that GNU handles this case incorrectly and probably confirms it with a test; if so, it'll need to be disabled.

**Comment by eugeneepshteyn** [comment]
> Please run the llvm-test-suite before merging; I think that GNU handles this case incorrectly and probably confirms it with a test; if so, it'll need to be disabled.

I did. These failures happen for me even without my change:
```
Failed Tests (2):
  test-suite :: Fortran/gfortran/regression/gfortran-regression-execute-regression__eoshift_bounds_1_f90.test
  test-suite :: Fortran/gfortran/regression/goacc/gfortran-regression-compile-regression__goacc__routine-3_f90.test
```
I think eoshift need to run at `-O0` and ACC test has issue generating LLVM module.

File: flang-rt/lib/runtime/pointer.cpp [hunk 1]
```diff
@@ -267,8 +267,8 @@ bool RTDEF(PointerIsAssociatedWith)(
   if (!target) {
     return pointer.raw().base_addr != nullptr;
   }
-  if (!target->raw().base_addr || target->ElementBytes() == 0
-      || target->Elements() == 0) {
```
Comment (akuhlens) [inline flang-rt/lib/runtime/pointer.cpp]: Is this invalid C++ code that was excepted by the compiler? It is weird to me that the compiler didn't reject this or treat it the same as the changed code.

**Review by akuhlens — APPROVED** [review]

File: flang-rt/lib/runtime/pointer.cpp (hunk 1 above)
Comment (akuhlens) [reply flang-rt/lib/runtime/pointer.cpp]: Never mind, I see what happened here.

**Comment by eugeneepshteyn** [comment]
PR for llvm-test-suite: https://github.com/llvm/llvm-test-suite/pull/279
