### PR TITLE
[PowerPC][CodeGen] Expand ISD::AssertNoFPClass for ppc_fp128

### LINKED ISSUE #151375: LLVM 21.1.0: Unable to expand result for ppcf128 with ISD::AssertNoFPClass
I've encountered the following issue on LLVM 21.1.0 rc1 as a result of https://github.com/llvm/llvm-project/pull/138839#issuecomment-3137287195 on PPC64LE, with the ppc_fp128 type.

```
$ cat t.ll
target datalayout = "e-m:e-Fn32-i64:64-i128:128-n32:64-S128-v256:256:256-v512:512:512"
target triple = "powerpc64le-unknown-linux-gnu"

define ppc_fp128 @test(ppc_fp128 nofpclass(nan) %s) {
entry:
  ret ppc_fp128 %s
}

$ llc < t.ll
	.abiversion 2
	.file	"<stdin>"
ExpandFloatResult #0: t7: ppcf128 = AssertNoFPClass t5, TargetConstant:i32<3>

LLVM ERROR: Do not know how to expand the result of this operator!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: llc
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'PowerPC DAG->DAG Pattern Instruction Selection' on function '@test'
 #0 0x0000071c5b0bb42c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) 
 #1 0x0000071c5b0bbbd4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #2 0x0000071c5b0b7fac llvm::sys::RunSignalHandlers()  
 #3 0x0000071c5b0bc83c SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #4 0x00006b262e170444 (linux-vdso64.so.1+0x444)
 #5 0x00006b262d8f55fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x00006b262d8f55fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #7 0x00006b262d8f55fc pthread_kill ./nptl/pthread_kill.c:89:10
 #8 0x00006b262d88bd5c raise ./signal/../sysdeps/posix/raise.c:26:13
 #9 0x00006b262d86645c abort ./stdlib/abort.c:79:7
#10 0x0000071c5aff42fc llvm::report_fatal_error(llvm::Twine const&, bool)
#11 0x0000071c5aff402c llvm::report_fatal_error(char const*, bool)
#12 0x0000071c5aec252c llvm::DAGTypeLegalizer::ExpandFloatResult(llvm::SDNode*, unsigned int) LegalizeFloatTypes.cpp:0:0
#13 0x0000071c5ae5bbcc llvm::DAGTypeLegalizer::run() LegalizeTypes.cpp:0:0
. . .
```

The `ISD::AssertNoFPClass` presumably needs to know how to expand float results.

### PR DESCRIPTION
**Pull request by amy-kwan**
780054d3ff18075a6bc433029f336931792b1d2d added support for `ISD::AssertNoFPClass`.

This ISD node can be used with the `ppc_fp128` type, which is really just two `f64s` and requires expanding when used with `ISD::AssertNoFPClass`. Without the support for expanding the result, we get an assertion because the legalizer does not know how to expand the results of `ppc_fp128` with `ISD::AssertNoFPClass`.
```
ExpandFloatResult #0: t7: ppcf128 = AssertNoFPClass t5, TargetConstant:i32<3>

LLVM ERROR: Do not know how to expand the result of this operator!
```
Thus, this patch aims to add support for the expand so we no longer assert.

This fixes #151375.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp [hunk 1]
```diff
@@ -1966,6 +1967,14 @@ void DAGTypeLegalizer::ExpandFloatRes_FNEG(SDNode *N, SDValue &Lo,
   Hi = DAG.getNode(ISD::FNEG, dl, Hi.getValueType(), Hi);
 }
 
+void DAGTypeLegalizer::ExpandFloatRes_AssertNoFPClass(SDNode *N, SDValue &Lo,
+                                                      SDValue &Hi) {
+  SDLoc dl(N);
+  GetExpandedFloat(N->getOperand(0), Lo, Hi);
+  Lo = DAG.getNode(ISD::AssertNoFPClass, dl, Lo.getValueType(), Lo);
+  Hi = DAG.getNode(ISD::AssertNoFPClass, dl, Hi.getValueType(), Hi);
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1975]: I'm not sure it's safe to directly take the value for both halves, and if it is it's only in double double cases like ppcf128. For ppcf128, it might not even apply to both halves. The safest option to get the compilation to stop failing is to drop the operation altogether and revisit the details of when it's preservable later

File: llvm/test/CodeGen/PowerPC/nofpclass.ll [hunk 2]
```diff
@@ -0,0 +1,13 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
+; RUN: llc -verify-machineinstrs  -mtriple=powerpc64le-unknown-linux-gnu < %s \
+; RUN:   | FileCheck %s
+; RUN: llc -verify-machineinstrs  -mtriple=powerpc64-ibm-aix-xcoff < %s \
+; RUN:   | FileCheck %s
```
Comment (arsenm) [inline llvm/test/CodeGen/PowerPC/nofpclass.ll:5]:
```suggestion
; RUN: llc -mtriple=powerpc64le-unknown-linux-gnu < %s | FileCheck %s
; RUN: llc -mtriple=powerpc64-ibm-aix-xcoff < %s | FileCheck %s
```

File: llvm/test/CodeGen/PowerPC/nofpclass.ll [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+
+define ppc_fp128 @f(ppc_fp128 nofpclass(nan) %s) {
+; CHECK-LABEL: f:
+; CHECK:       # %bb.0: # %entry
+; CHECK-NEXT:    blr
+entry:
+  ret ppc_fp128 %s
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/PowerPC/nofpclass.ll:13]: Ideally would test with more masks, and some cases that demonstrate downstream effects of preserving it after legalization. That's best left to a follow up that tries to preserve it though

File: llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp (hunk 1 above)
Comment (RolandF77) [reply llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1975]: Looking at PPCTargetLowering::LowerIS_FPCLASS, it appears that for ppcf128 the class is determined by element 1. So I think propagating the info for element 1 is correct. I don't have any evidence about element 0, so I think it should not be propagated there. I am okay with not propagating the assert for both elements for now. I don't see any type tests or asserts so it's hard to be confident that only ppcf128 reaches here, so I think ppcf128 specific stuff like element 1 is class should be if protected and there be a general clear both path.

Comment (amy-kwan) [reply llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1975]: Ah, yeah, I noticed I have a typo here.

As Roland mentioned, the class comes from the first element, which is what I meant:
```
SDValue PPCTargetLowering::LowerIS_FPCLASS(SDValue Op,
                                           SelectionDAG &DAG) const {
  assert(Subtarget.hasP9Vector() && "Test data class requires Power9");
  SDValue LHS = Op.getOperand(0);
  uint64_t RHSC = Op.getConstantOperandVal(1);
  SDLoc Dl(Op);
  FPClassTest Category = static_cast<FPClassTest>(RHSC);
  if (LHS.getValueType() == MVT::ppcf128) {
    // The higher part determines the value class.
    LHS = DAG.getNode(ISD::EXTRACT_ELEMENT, Dl, MVT::f64, LHS,
                      DAG.getConstant(1, Dl, MVT::i32));
  }

  return getDataClassTest(LHS, Category, Dl, DAG, Subtarget);
}
```

Unless I am misunderstanding, based on the two comments, propagating the information from element 1 is correct but it sounds like should just drop the operation for now.

@arsenm Dumb question, sorry - but what exactly does dropping the operation look like in this case? I assume the Hi and Lo would not be set then?

Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1975]: Passing through the results of GetExpandedFloat directly to the final results, without constructing a new AssertNoFPClass

File: llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp [hunk 4]
```diff
@@ -1966,6 +1967,14 @@ void DAGTypeLegalizer::ExpandFloatRes_FNEG(SDNode *N, SDValue &Lo,
   Hi = DAG.getNode(ISD::FNEG, dl, Hi.getValueType(), Hi);
 }
 
+void DAGTypeLegalizer::ExpandFloatRes_AssertNoFPClass(SDNode *N, SDValue &Lo,
+                                                      SDValue &Hi) {
+  SDLoc dl(N);
+  GetExpandedFloat(N->getOperand(0), Lo, Hi);
+  Lo = DAG.getNode(ISD::AssertNoFPClass, dl, Lo.getValueType(), Lo);
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1974]:
```suggestion
```

File: llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp [hunk 5]
```diff
@@ -1966,6 +1967,12 @@ void DAGTypeLegalizer::ExpandFloatRes_FNEG(SDNode *N, SDValue &Lo,
   Hi = DAG.getNode(ISD::FNEG, dl, Hi.getValueType(), Hi);
 }
 
+void DAGTypeLegalizer::ExpandFloatRes_AssertNoFPClass(SDNode *N, SDValue &Lo,
+                                                      SDValue &Hi) {
+  SDLoc dl(N);
+  GetExpandedFloat(N->getOperand(0), Lo, Hi);
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:1973]: Add todo to preserve it for the half for ppcf128 if you aren't going to immediately follow up with that

File: llvm/test/CodeGen/PowerPC/nofpclass.ll (hunk 3 above)
Comment (arsenm) [reply llvm/test/CodeGen/PowerPC/nofpclass.ll:11]: Yes, a later patch which doesn't drop the assert would need more tests.

This is the minimal test which shows the legalization doesn't crash, but this doesn't show it's being preserved. You'd need some optimization that triggers on the type legalized dag, not sure what that would look like in the ppc case

**Review by arsenm — APPROVED** [review]

**Comment by amy-kwan** [comment]
> LLVM Buildbot has detected a new failure on builder `ml-opt-dev-x86-64` running on `ml-opt-dev-x86-64-b1` while building `llvm` at step 6 "test-build-unified-tree-check-all".
> 
> Full details are available at: https://lab.llvm.org/buildbot/#/builders/137/builds/23502
> 
> Here is the relevant piece of the build log for the reference

I've reverted my change locally. This failure doesn't appear to be due to my change.
