### PR TITLE
[sanitizer] Use close_range on Linux to close FDs in StartSubprocess

### LINKED ISSUE #63297: `StartSubprocess` gets stuck when opfile limit is large.
As described in https://github.com/google/sanitizers/issues/1662

https://github.com/llvm/llvm-project/blob/f9d0bf06319203a8cbb47d89c2f39d2c782f3887/compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp#L465 

`compiler-rt` uses a crude approach to close file descripters, which causes child processes to get stuck and fill up the CPU when the maximum file descriptor limit is too large. 

It is better to close only the actual open file descriptors rather than traversing the entire potential range. I'm not sure if the following code is generic.

```c
void close_file_descriptors() {
    DIR *dir;
    struct dirent *entry;
    int fd;

    dir = opendir("/proc/self/fd/");
    if (dir == NULL) {
        perror("opendir failed");
        return;
    }

    while ((entry = readdir(dir)) != NULL) {
        fd = atoi(entry->d_name);

        if (fd >= 3) {
            close(fd);
        }
    }

    closedir(dir);
}
```

### LINKED ISSUE #152459: Very slow symbolizer invocation in libfuzzer with Go c-archive library
I have a relatively simple fuzzing tool using libfuzzer. It is fuzzing C++ and Go code. The Go code is built to the "c-archive" with `go build -buildmode=c-archive -tags=libfuzzer -gcflags=-d=libfuzzer`. All seems to work correctly, except the moment the libfuzzer needs the function names (e.g. to print a stack trace or to focus a function or to report new functions covered) there is a big minutes long pause.

My investigation lead me to the `llvm-symbolizer` subprocess invocation. The below is libfuzzer output with UBSAN verbosity increased. The second module with 2 PCs seems to be the Go code.

```
export UBSAN_OPTIONS=verbosity=4
fuzz ../corpus -use_value_profile=1 -focus_function=FUNC -runs=0                                                        
==145033==Using llvm-symbolizer found at: /usr/bin/llvm-symbolizer-21
==145033==Installed the sigaction for signal 11
==145033==Installed the sigaction for signal 7
==145033==Installed the sigaction for signal 8
INFO: Seed: 32135115
INFO: Loaded 2 modules   (11211 inline 8-bit counters): 11209 [0x5f4829450bf2, 0x5f48294537bb), 2 [0x5f4829e18e00, 0x5f4829e18e02), 
INFO: Loaded 2 PC tables (11211 PCs): 11209 [0x5f48294537c0,0x5f482947f450), 2 [0xc00001a120,0xc00001a140), 
INFO:      224 files found in ../corpus
==145033==Launching Symbolizer process: /usr/bin/llvm-symbolizer-21 --demangle --inlines --default-arch=x86_64
(PAUSE)
ERROR: Failed to set focus function. Make sure the function name is valid (FUNC) and symbolization is enabled.
```

However, I'm not sure the `llvm-symbolizer` is slow. Some perf tracing suggest this is the subprocess management. According to `perf record` mostly of the time is spent on closing file descriptors.

```
    94.97%    19.76%  fuzz             fuzz                  [.] __sanitizer::internal_close(int)
            |          
            |--89.99%--__sanitizer::internal_close(int)
            |          |          
            |          |--32.39%--entry_SYSCALL_64_after_hwframe
            |          |          |          
            |          |          |--26.76%--do_syscall_64
            |          |          |          |          
            |          |          |          |--12.98%--x64_sys_call
            |          |          |          |          |          
            |          |          |          |          |--10.60%--__x64_sys_close
            |          |          |          |          |          |          
            |          |          |          |          |          |--6.06%--_raw_spin_lock
            |          |          |          |          |          |          
            |          |          |          |          |          |--2.44%--file_close_fd
            |          |          |          |          |          |          |          
            |          |          |          |          |          |           --0.52%--file_close_fd_locked
            |          |          |          |          |          |          
            |          |          |          |          |          |--0.90%--file_close_fd_locked
            |          |          |          |          |          |          
            |          |          |          |          |           --0.58%--_raw_spin_unlock
            |          |          |          |          |          
            |          |          |          |           --0.53%--file_close_fd
            |          |          |          |          
            |          |          |          |--7.25%--syscall_exit_to_user_mode
            |          |          |          |          |          
            |          |          |          |          |--3.34%--arch_exit_to_user_mode_prepare.isra.0
            |          |          |          |          |          |          
            |          |          |          |          |           --0.66%--fpregs_assert_state_consistent
            |          |          |          |          |          
            |          |          |          |          |--1.26%--syscall_exit_to_user_mode_prepare
            |          |          |          |          |          
            |          |          |          |           --0.65%--fpregs_assert_state_consistent
            |          |          |          |          
            |          |          |          |--1.16%--arch_exit_to_user_mode_prepare.isra.0
            |          |          |          |          
            |          |          |           --0.58%--syscall_exit_to_user_mode_prepare
            |          |          |          
            |          |           --0.71%--syscall_exit_to_user_mode
            |          |          
            |          |--28.62%--entry_SYSCALL_64
            |          |          
            |          |--5.53%--entry_SYSRETQ_unsafe_stack
            |          |          
            |          |--1.71%--syscall_return_via_sysret
            |          |          
            |          |--1.36%--entry_SYSCALL_64_safe_stack
            |          |          
            |           --0.68%--do_syscall_64
            |          
             --4.99%--__sanitizer::StartSubprocess(char const*, char const* const*, char const* const*, int, int, int)
```

The `llvm-symbolizer` run is only 2% if I interpret the perf report correctly.

```
     1.97%     0.00%  llvm-symbolizer  llvm-symbolizer       [.] 0x0000564172f90db5
            |
            ---0x564172f90db5
               __libc_start_main@@GLIBC_2.34
               __libc_start_call_main
               0x564172f977c3
               |          
                --1.86%--0x564172f927e6
                          0x564172f941a6
                          0x564172f95622
                          llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode(llvm::StringRef, llvm::object::SectionedAddress)
                          llvm::Expected<llvm::DIInliningInfo> llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCodeCommon<llvm::StringRef>(llvm::StringRef const&, llvm::object::SectionedAddress)
                          |          
                           --1.82%--llvm::symbolize::SymbolizableObjectFile::symbolizeInlinedCode(llvm::object::SectionedAddress, llvm::DILineInfoSpecifier, bool) const
                                     llvm::DWARFContext::getInliningInfoForAddress(llvm::object::SectionedAddress, llvm::DILineInfoSpecifier)
                                     |          
                                      --1.61%--llvm::DWARFUnit::getInlinedChainForAddress(unsigned long, llvm::SmallVectorImpl<llvm::DWARFDie>&)
                                                llvm::DWARFUnit::getSubroutineForAddress(unsigned long)
                                                |          
                                                |--1.03%--llvm::DWARFUnit::tryExtractDIEsIfNeeded(bool)
                                                |          |          
                                                |           --1.01%--llvm::DWARFUnit::extractDIEsToVector(bool, bool, std::vector<llvm::DWARFDebugInfoEntry, std::allocator<llvm::DWARFDebugInfoEntry> >&) const
                                                |          
                                                 --0.58%--llvm::DWARFUnit::updateAddressDieMap(llvm::DWARFDie)
                                                           llvm::DWARFUnit::updateAddressDieMap(llvm::DWARFDie)
                                                           |          
                                                            --0.51%--llvm::DWARFUnit::updateAddressDieMap(llvm::DWARFDie)
```

### PR DESCRIPTION
**Pull request by chfast**
Enable the close_range syscall on Linux when __NR_close_range is
available in kernel headers (Linux 5.9+). On older kernels, the
syscall returns ENOSYS and callers fall back gracefully.

This fixes the slow FD closing loop in StartSubprocess when
RLIMIT_NOFILE is high (e.g. 1B in Docker environments).

Fixes https://github.com/llvm/llvm-project/issues/63297.
Fixes https://github.com/llvm/llvm-project/issues/152459.

### CODE REVIEW

**Review by chfast — COMMENTED** [review]
This is implementation where we explicitly guard all usage of `internal_close_range` with macros like `SANITIZER_LINUX` or `SANITIZER_USE_CLOSE_RANGE`.

I think much cleaner implementation is to implement the fallback inside the `internal_close_range`. I didn't do it because I wasn't sure if this not against established practice.

File: compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp [hunk 1]
```diff
@@ -562,11 +562,15 @@ pid_t StartSubprocess(const char *program, const char *const argv[],
...
 
-#  if SANITIZER_FREEBSD
-    internal_close_range(3, ~static_cast<fd_t>(0), 0);
-#  else
-    for (int fd = sysconf(_SC_OPEN_MAX); fd > 2; fd--) internal_close(fd);
+#  if SANITIZER_FREEBSD || SANITIZER_LINUX
+    // Use close_range (FreeBSD 13+, Linux 5.9+) to avoid a slow loop
+    // when RLIMIT_NOFILE is high (e.g. 1B in Docker environments).
+    // Falls back to the loop if the syscall is not available.
+    if (internal_close_range(3, ~static_cast<fd_t>(0), 0) != 0)
```
Comment (ndrewh) [inline compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp:567]: I don't love breaking up the if body here, but I should let someone else weigh in.

Comment (thurstond) [reply compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp:567]: If `internal_close_range` was defined on all POSIX sanitizer platforms (including as stubs that return -1 if not applicable), instead of only in sanitizer_linux.cpp, it would be possible to remove the '#if ' here.

Comment (chfast) [reply compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp:567]: Done in https://github.com/llvm/llvm-project/pull/191971.

**Comment by chfast** [comment]
Waits for https://github.com/llvm/llvm-project/pull/192114.

**Comment by mysterymath** [comment]
This is a shot in the dark, but we're seeing an odd HWAsan test failure on the Fuchsia clang bots, and AFAICT, this is the only sanitizer-related change in the blamelist. Does it seem possible that this could cause this error?

https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-arm64/b8684518250515764433/overview

```
# RUN: at line 3
env HWASAN_OPTIONS=disable_allocator_tagging=1:random_tags=0:fail_without_syscall_abi=0:symbolize=0 not  /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/hwasan_symbolize_stack_overflow.cpp.tmp/hwasan_overflow 16 2>&1 | /b/s/w/ir/x/w/llvm_build/bin/hwasan_symbolize --symbols /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/hwasan_symbolize_stack_overflow.cpp.tmp --index | FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp --check-prefixes=CHECK,AFTER0
# executed command: env HWASAN_OPTIONS=disable_allocator_tagging=1:random_tags=0:fail_without_syscall_abi=0:symbolize=0 not /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/hwasan_symbolize_stack_overflow.cpp.tmp/hwasan_overflow 16
# executed command: /b/s/w/ir/x/w/llvm_build/bin/hwasan_symbolize --symbols /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/hwasan_symbolize_stack_overflow.cpp.tmp --index
# .---command stderr------------
# | Could not find symbols for lib/aarch64-linux-gnu/libc.so.6 (Build ID: 45918bc10b33fd96afc550c98de062dccdf44328)
# `-----------------------------
# executed command: FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp --check-prefixes=CHECK,AFTER0
# RUN: at line 4

...

# executed command: FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp --check-prefixes=CHECK,AFTER1000
# .---command stderr------------
# | /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp:21:12: error: CHECK: expected string not found in input
# |  // CHECK: Potentially referenced stack object:
# |            ^
# | <stdin>:1:1: note: scanning from here
# | ==1736234==ERROR: HWAddressSanitizer: tag-mismatch on address 0xffffe2500218 at pc 0xaaaad678f124
# | ^
# | <stdin>:10:12: note: possible intended match here
# | Address 0xffffe2500218 is located in stack of thread T0
# |            ^
# | 
# | Input file: <stdin>
# | Check file: /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp
# | 
# | -dump-input=help explains the following input dump.
# | 
# | Input was:
# | <<<<<<
# |             1: ==1736234==ERROR: HWAddressSanitizer: tag-mismatch on address 0xffffe2500218 at pc 0xaaaad678f124 
# | check:21'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
# |             2: READ of size 1 at 0xffffe2500218 tags: 01/00 (ptr/mem) in thread T0 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             3:  #0 main in /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/hwasan/TestCases/hwasan_symbolize_stack_overflow.cpp:19:10 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             4:  #1 0xffff8dac2258 (/lib/aarch64-linux-gnu/libc.so.6+0x22258) (BuildId: 45918bc10b33fd96afc550c98de062dccdf44328) 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             5:  #2 0xffff8dac2338 (/lib/aarch64-linux-gnu/libc.so.6+0x22338) (BuildId: 45918bc10b33fd96afc550c98de062dccdf44328) 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             6:  #3 _start in ??:0:0 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~
# |             7:  
# | check:21'0     ~
# |             8:  
# | check:21'0     ~
# |             9: Cause: stack tag-mismatch 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            10: Address 0xffffe2500218 is located in stack of thread T0 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# | check:21'1                ?                                             possible intended match
# |            11: Thread: T0 0xeffe00002000 stack: [0xffffe1d01000,0xffffe2501000) sz: 8388608 tls: [0xffff8dd644c0,0xffff8dd65360) 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            12:  
# | check:21'0     ~
# |            13:  
# | check:21'0     ~
# |            14: Memory tags around the buggy address (one tag corresponds to 16 bytes): 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            15: Tags for short granules around the buggy address (one tag corresponds to 16 bytes): 
# | check:21'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             .
# |             .
# |             .
# | >>>>>>
# `-----------------------------
# error: command failed with exit status: 1

```

**Comment by chfast** [comment]
@mysterymath do you mean https://github.com/llvm/llvm-project/pull/191971?

**Comment by thurstond** [comment]
> This is a shot in the dark, but we're seeing an odd HWAsan test failure on the Fuchsia clang bots, and AFAICT, this is the only sanitizer-related change in the blamelist. Does it seem possible that this could cause this error?
>
> https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-arm64/b8684518250515764433/overview

#191971 only adds function definitions to sanitizer_{haiku,linux,mac_netbsd,solaris}.cpp (with nothing added to sanitizer_fuchsia.*).

**Comment by mysterymath** [comment]
> @mysterymath do you mean #191971?

Yeah, I do, sorry.

> #191971 only adds function definitions to sanitizer_{haiku,linux,mac_netbsd,solaris}.cpp (with nothing added to sanitizer_fuchsia.*).

 Also to clarify, this failure is on the Linux test suite. We maintain a toolchain that targets Linux, macOS, and Fuchsia.

**Comment by thurstond** [comment]
> Also to clarify, this failure is on the Linux test suite. We maintain a toolchain that targets Linux, macOS, and Fuchsia.

Ah, I see.

FWIW the sanitizers' team Arm HWASan Linux bot was green after #191971 landed: https://lab.llvm.org/buildbot/#/builders/55/builds/26733

**Comment by mysterymath** [comment]
> @mysterymath do you mean #191971?



> > Also to clarify, this failure is on the Linux test suite. We maintain a toolchain that targets Linux, macOS, and Fuchsia.
> 
> Ah, I see.
> 
> FWIW the sanitizers' team Arm HWASan Linux bot was green after #191971 landed: https://lab.llvm.org/buildbot/#/builders/55/builds/26733

Yep, seems that way. No worries!

**Comment by thurstond** [comment]
Looks like turned green in the latest build: https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-arm64/b8684512453652649249/overview

I assume it was test flake?

**Comment by mysterymath** [comment]
> Looks like turned green in the latest build: https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-arm64/b8684512453652649249/overview
> 
> I assume it was test flake?

Yeah, I think so. Sorry for bothering.

**Comment by thurstond** [comment]
No problem :-)

**Review by thurstond — APPROVED** [review]
Thanks!
