### PR TITLE
[X86][WinEH] Insert nop after unwinding inline assembly

### LINKED ISSUE #157073: Rust's tests/ui/asm/x86_64/may_unwind.rs fails on Windows after b933f0c376c983614a0701f3bfd4054cf8fe4386
As mentioned in https://github.com/llvm/llvm-project/pull/144745#issuecomment-3212031633, Rust's `tests/ui/asm/x86_64/may_unwind.rs` started failing on Windows after b933f0c376c983614a0701f3bfd4054cf8fe4386

On the PR, there seemed to be rough consensus around the proposed fix of

> Maybe we should make the compiler insert a nop after inline asm blocks marked "unwind"?

### PR DESCRIPTION
**Pull request by nikic**
As discussed on https://github.com/llvm/llvm-project/pull/144745, insert a nop after unwinding inline assembly, as it may end on a call.

While the change itself is trivial, I ended up having to do two infrastructure changes:
 * The unwind flag needs to be propagated to ExtraInfo of the MachineInstr.
 * The MachineInstr needs to be passed through to emitInlineAsmEnd(), and the method needs to be non-const.

Fixes https://github.com/llvm/llvm-project/issues/157073.

### CODE REVIEW

**Review by dpaoliello — APPROVED** [review]

**Review by efriedma-quic — APPROVED** [review]
LGTM

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp [hunk 1]
```diff
@@ -73,7 +73,8 @@ unsigned AsmPrinter::addInlineAsmDiagBuffer(StringRef AsmStr,
 void AsmPrinter::emitInlineAsm(StringRef Str, const MCSubtargetInfo &STI,
                                const MCTargetOptions &MCOptions,
                                const MDNode *LocMDNode,
-                               InlineAsm::AsmDialect Dialect) const {
+                               InlineAsm::AsmDialect Dialect,
```
Comment (rnk) [inline llvm/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp]:
```suggestion
```

File: llvm/include/llvm/CodeGen/AsmPrinter.h [hunk 2]
```diff
@@ -942,15 +943,15 @@ class LLVM_ABI AsmPrinter : public MachineFunctionPass {
...
   /// Emit a blob of inline asm to the output streamer.
-  void
-  emitInlineAsm(StringRef Str, const MCSubtargetInfo &STI,
-                const MCTargetOptions &MCOptions,
-                const MDNode *LocMDNode = nullptr,
-                InlineAsm::AsmDialect AsmDialect = InlineAsm::AD_ATT) const;
+  void emitInlineAsm(StringRef Str, const MCSubtargetInfo &STI,
+                     const MCTargetOptions &MCOptions,
+                     const MDNode *LocMDNode = nullptr,
+                     InlineAsm::AsmDialect AsmDialect = InlineAsm::AD_ATT,
```
Comment (rnk) [inline llvm/include/llvm/CodeGen/AsmPrinter.h]:
```suggestion
```

File: llvm/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp
Comment (rnk) [inline llvm/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp]:
```suggestion
    Parser->setAssemblerDialect(MI->getInlineAsmDialect());
```

**Review by rnk — APPROVED** [review]
Thanks, I made some suggested edits, hopefully they compile.
