### PR TITLE
[profile] Add `%b` `LLVM_PROFILE_FILE` option for binary ID

### LINKED ISSUE #51560: Binary signature collision for different modules when collecting instrumentation profile
|  |  |
| --- | --- |
| Bugzilla Link | [52218](https://llvm.org/bz52218) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Below is a minimal example crafted based on a usage of trying to get coverage data for postgresql.

$ cat src1.c
int main(void) { return 0; }
void www1(void) { }

$ cat src2.c
int main(void) { return 0; }
void www2(int *a) { *a+=10; }

dir=/tmp/profile-test

clang -O0 -g -fprofile-instr-generate -fcoverage-mapping src1.c -o src1
clang -O0 -g -fprofile-instr-generate -fcoverage-mapping src2.c -o src2

export LLVM_PROFILE_FILE="$dir/code-%m.profraw"
./src1
./src2

LLVM Profile Warning: Unable to merge profile data: source profile file is not compatible.
LLVM Profile Error: Profile Merging of file /tmp/profile-test/code-15822683945683506682_0.profraw failed: File exists
LLVM Profile Error: Failed to write file "/tmp/profile-test/code-15822683945683506682_0.profraw": File exists

What happens here is the hash [1] turns out too weak. The two modules end up having the same hash and therefore the corresponding binaries have the same signature. This leads to the profiling library trying to merge the profile from the second program into the one obtained from running the first one.  

This is using a recent commit 1c1406f24d8b1c8ebec76c516ea969072d24cc75 (post llvmorg-13-init tag). Also got the same result with clang 12.0.1.

The original problem was a bit more involved: utf8_and_euc_kr.so and utf8_and_euc_tw.so libraries get loaded from the main binary. They have the following lists of functions defined in them.

Pg_magic_func
pg_finfo_euc_kr_to_utf8
pg_finfo_utf8_to_euc_kr
euc_kr_to_utf8
utf8_to_euc_kr

Pg_magic_func
pg_finfo_euc_tw_to_utf8
pg_finfo_utf8_to_euc_tw
euc_tw_to_utf8
utf8_to_euc_tw

[1]: https://github.com/llvm/llvm-project/blob/1c1406f24d8b1c8ebec76c516ea969072d24cc75/compiler-rt/lib/profile/InstrProfilingMerge.c#L23-L37

### PR DESCRIPTION
**Pull request by ArtSin**
Add support for expanding `%b` in `LLVM_PROFILE_FILE` to the binary ID (build ID). It can be used with `%m` to avoid its signature collisions.

This is supported on all platforms where writing binary IDs into profiles is implemented, as the `__llvm_write_binary_ids` function is used.

Fixes #51560.

### CODE REVIEW

**Comment by ArtSin** [comment]
PTAL @ZequanWu @david-xl

File: compiler-rt/lib/profile/InstrProfilingFile.c [hunk 1]
```diff
@@ -855,6 +856,15 @@ static int parseFilenamePattern(const char *FilenamePat,
                     FilenamePat);
           return -1;
         }
+      } else if (FilenamePat[I] == 'b') {
+        if (!NumBinaryIds++) {
+          if (__llvm_write_binary_ids(NULL) <= 0) {
```
Comment (david-xl) [inline compiler-rt/lib/profile/InstrProfilingFile.c:861]: Add a code comment to indicate it reads the size of the binary ids.

File: compiler-rt/test/profile/Linux/binary-id-path.c [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+// RUN: rm -rf %t.profdir
+// RUN: env LLVM_PROFILE_FILE=%t.profdir/%m.profraw %run %t.dir/foo
+// RUN: env LLVM_PROFILE_FILE=%t.profdir/%m.profraw %run %t.dir/bar 2>&1 | FileCheck %s --check-prefix=MERGE-ERROR
+
+// Check that foo and bar have different binary IDs.
+// RUN: rm -rf %t.profdir %t.profdata
+// RUN: env LLVM_PROFILE_FILE=%t.profdir/%b.profraw %run %t.dir/foo
+// RUN: env LLVM_PROFILE_FILE=%t.profdir/%b.profraw %run %t.dir/bar
+// RUN: llvm-profdata merge -o %t.profdata %t.profdir
+// RUN: llvm-profdata show %t.profdata | FileCheck %s --check-prefix=BINARY-ID
```
Comment (david-xl) [inline compiler-rt/test/profile/Linux/binary-id-path.c:16]: check the binary ids after merging?

File: compiler-rt/lib/profile/InstrProfilingFile.c (hunk 1 above)
Comment (ArtSin) [reply compiler-rt/lib/profile/InstrProfilingFile.c:862]: Done

File: compiler-rt/test/profile/Linux/binary-id-path.c (hunk 2 above)
Comment (ArtSin) [reply compiler-rt/test/profile/Linux/binary-id-path.c]: Added check for 2 binary IDs in merged profdata

File: clang/docs/UsersManual.rst [hunk 3]
```diff
@@ -2917,7 +2918,7 @@ instrumentation:
      $ LLVM_PROFILE_FILE="code-%m.profraw" ./code
 
    See `this <SourceBasedCodeCoverage.html#running-the-instrumented-program>`_ section
-   about the ``%t``, and ``%c`` modifiers.
+   about the ``%b``, ``%t``, and ``%c`` modifiers.
```
Comment (david-xl) [inline clang/docs/UsersManual.rst:2921]: better add an %b use example here  too.

Comment (ArtSin) [reply clang/docs/UsersManual.rst]: Done

**Review by david-xl — APPROVED** [review]

File: clang/docs/UsersManual.rst [hunk 4]
```diff
@@ -2916,6 +2917,12 @@ instrumentation:
 
      $ LLVM_PROFILE_FILE="code-%m.profraw" ./code
 
+   Although rare, binary signatures used by the ``%m`` specifier can have
+   collisions. In this case, the ``%b`` specifier, which expands to the binary
+   ID (build ID), can be added. To use it, the program should be compiled with
```
Comment (petrhosek) [inline clang/docs/UsersManual.rst:2922]:
```suggestion
   ID (build ID in ELF and COFF), can be added. To use it, the program should be compiled with
```

**Review by petrhosek — APPROVED** [review]

File: clang/docs/UsersManual.rst (hunk 4 above)
Comment (ArtSin) [reply clang/docs/UsersManual.rst]: Done

File: clang/docs/UsersManual.rst [hunk 5]
```diff
@@ -2916,6 +2917,12 @@ instrumentation:
 
      $ LLVM_PROFILE_FILE="code-%m.profraw" ./code
 
+   Although rare, binary signatures used by the ``%m`` specifier can have
+   collisions. In this case, the ``%b`` specifier, which expands to the binary
+   ID (build ID in ELF and COFF), can be added. To use it, the program should be
+   compiled with the build ID linker option (``--build-id`` for GNU ld or LLD).
```
[the remark this answers is not in the document]
Comment (ArtSin) [reply clang/docs/UsersManual.rst]: Added

**Review by ZequanWu — APPROVED** [review]

**Comment by ArtSin** [comment]
@ZequanWu can you please merge this?

**Comment by dyung** [comment]
@ArtSin the test you added seems to be failing on at least one build bot https://lab.llvm.org/buildbot/#/builders/174/builds/12664.

Can you take a look and revert if you need time to investigate?

**Comment by ZequanWu** [comment]
That should be fixed by https://github.com/llvm/llvm-project/commit/8d925a1c72600807199894b5852bd8a032eca795.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Hi! I see this patch is already merged, but sine the most testing work is already done, I will still write my report here.

I am original reporter of #51560.
@ArtSin asked me to test the patch. 

TL;TR: `%b` solves my problem, but `%p` still breaks everything, and I guess that is another bug.

I met problem with coverage while building coverage while running PostgreSQL tests. Tried `%p` and `%m` in all combinations in  `LLVM_PROFILE_FILE` and it failed for me with various errors.

How dif I test: I built two branches of llvm: `main` from https://github.com/llvm/llvm-project.git (f3c4b58f4b0d98c8de29dd235a34e512be71ab3f) and `add-binary-id-llvm_profile_file` from https://github.com/ArtSin/llvm-project.git (will refer is as `fixed`)

I've configured them with command

```
cmake -S llvm -B build -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_RUNTIMES="compiler-rt"  -DLLVM_RUNTIME_TARGETS="x86_64-unknown-linux-gnu"  -DLLVM_BUILTIN_TARGETS="x86_64-unknown-linux-gnu"
``` 

and then `make -j10` and `sudo make install`.

Then I've cloned PostgreSQL `git clone git://git.postgresql.org/git/postgresql.git -b REL_17_STABLE`, configured them with
```
CC=/usr/local/bin/clang LD=/usr/local/bin/clang CXX=/usr/local/bin/clang++ CFLAGS="-fprofile-instr-generate -fcoverage-mapping -Wl,--build-id " ./configure --enable-debug --enable-cassert --enable-tap-tests
```
Using `main` and `fiexd` clangs. And build them using `make -j10 world-bin`

Then I tried running tests for both builds using `make check-world` command with various  `LLVM_PROFILE_FILE` values

### `main` branch

* running tests with only `%m` in `LLVM_PROFILE_FILE` ends with a lot of errors while running tests like :

```
LLVM Profile Warning: Unable to merge profile data: source profile file is not compatible.                                                                                                                       
LLVM Profile Error: Profile Merging of file /home/nataraj/dev/clang/postgres-clang-main/../profile-clang-main-no-p/15781143787294967941_0.profraw failed: File exists                                            
LLVM Profile Error: Failed to write file "/home/nataraj/dev/clang/postgres-clang-main/../profile-clang-main-no-p/15781143787294967941_0.profraw": File exists
```

this tests fails.

* running with both `%m` and `%p`  in `LLVM_PROFILE_FILE` creates a lot of files in profile directory (9Gb) and when you try to merge them, you will get: 

```
warning: ../profile-clang-main/167104_786791946722153948_0_.profraw: invalid instrumentation profile data (file header is corrupt)                                                                                
warning: ../profile-clang-main/147831_786791946722153948_0_.profraw: invalid instrumentation profile data (file header is corrupt)                                                                                
warning: ../profile-clang-main/147887_786791946722153948_0_.profraw: invalid instrumentation profile data (file header is corrupt)                                                                                
error: no profile can be merged  
```

### fixed branch

* If you run tests with `%m` and `%b`  in `LLVM_PROFILE_FILE` you will get quite small profile dir (7Mb), this raw profile files will be successfully merged, and you will be able to create html-coverage files from it, with coverage that looks like it was really created while running tests. So the patch works. Hooray!!!!

* But if have `%p` to the  in `LLVM_PROFILE_FILE` (with `%m` and `%b` or without them) in fixed branch you will still get 9Gb profile directory that can't be merged:

```
/usr/local/bin/llvm-profdata merge -output=../merged-clang-fix-p-4-cpu.profdata --input-files=`pwd`/../profile-clang-fix-p-4-cpu.list
warning: /home/nataraj/dev/clang/postgres-clang-fix/../profile-clang-fix-p-4-cpu/15196_786791946722153948_0_43a62d1842c2c30141d2cd5140b00e7064205c3d.profraw: invalid instrumentation profile data (file header is corrupt)
warning: /home/nataraj/dev/clang/postgres-clang-fix/../profile-clang-fix-p-4-cpu/34197_786791946722153948_0_43a62d1842c2c30141d2cd5140b00e7064205c3d.profraw: invalid instrumentation profile data (file header is corrupt)
warning: /home/nataraj/dev/clang/postgres-clang-fix/../profile-clang-fix-p-4-cpu/15252_786791946722153948_0_43a62d1842c2c30141d2cd5140b00e7064205c3d.profraw: invalid instrumentation profile data (file header is corrupt)
error: no profile can be merged
```

Tested it on VMs with (10,4,2 and 1 CPUs) So I can guess problems with `%p` is not caused by a collision, and should be solved later I guess.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Reported `%p` problem in https://github.com/llvm/llvm-project/issues/126242 issue. In order it will not be lost and forgotten...
