### PR TITLE
[LifetimeSafety] Implement multi-level origins

### LINKED ISSUE #162834: [LifetimeSafety] False-positive for lifetimebound functions returning a reference to a pointer/view
This came up while running the new lifetime analysis in Google. We have many false-positives involving `absl::StatusOr` accessor methods which mark the implicit this object parameter as `lifetimebound`. This gives false-positives in cases where the `StatusOr` doesn't own the underlying data (that is when the type is a pointer or view type).

Reproducer: https://godbolt.org/z/oMhdTTv78

```cpp
#include <iostream>
#include <string>
#include <string_view>

template <class T>
struct StatusOr {
    ~StatusOr() {}
    const T& value() const& [[clang::lifetimebound]] { return data; }

   private:
    T data;
};

StatusOr<std::string_view> getViewOr();
StatusOr<std::string> getStringOr();
StatusOr<std::string*> getPointerOr();

void foo() {
    std::string_view view;
    {
        StatusOr<std::string_view> view_or = getViewOr();
        view = view_or.value();
    }
    std::cout << view;  // error: a use-after-free. Bad!
}

void bar() {
    std::string* pointer;
    {
        StatusOr<std::string*> pointer_or = getPointerOr();
        pointer = pointer_or.value();
    }
    std::cout << *pointer;  // error: a use-after-free. Bad!
}

void foobar() {
    std::string_view view;
    {
        StatusOr<std::string> string_or = getStringOr();
        view = string_or.value();
    }
    std::cout << view;  // error: a use-after-free. Good!
}
```

See https://godbolt.org/z/EvdTjoq38 for original issue with `absl::StatusOr`  [src](https://github.com/abseil/abseil-cpp/blob/6ae6cc6fde4bbee167e2617f89ea5da491b00c8e/absl/status/internal/statusor_internal.h#L460).

### LINKED ISSUE #169758: [LifetimeSafety] False-positive for aliases to reference variable
https://godbolt.org/z/cGxozPYWj

```cpp
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

void foo() {
    std::vector<std::string> v;
    std::string_view view;
    for (const auto& s : v) {
        view = s; // warning: 's' does not live long enough.
    }
    (void)view; // note: later used here.
}

void bar(const std::string& s) {
    std::string_view view;
    {
        const std::string& ref = s; // 's' does not live long enough.
        view = ref;
    }
    (void)view; // later used here.
}

```

### LINKED ISSUE #169940: Suggest [[clang::lifetimebound]] for function parameters of reference type
```cpp
const int& Identity(const int& a) {
  return a;
}
```
Suggest 'a' to be marked lifetimebound.

### PR DESCRIPTION
**Pull request by usx95**
This PR implements a **multi-level origin model** for the lifetime safety analysis, replacing the previous single-origin-per-variable approach with an `OriginList` that captures multiple levels of indirection.

### KeyChanges

1. **OriginList Structure**: Each origin now represents a single level of indirection, organized into Lists:
    - `int* p` → length 2 (pointer variable + pointee)
    - `int** pp` → length 3 (variable + first pointee + second pointee)
    - `std::string_view&` → length 2 (reference + view object)
2. **Reference Type Understanding**: The analysis now properly distinguishes:
    - Pointer types vs references-to-pointer types (`string_view` vs `string_view&`)
    - References as aliases: `int a; int& b = a; int& c = b;` correctly recognizes both `b` and `c` alias `a`
    - References don't add storage and they reuse the underlying declaration's origins.
3. **Type-Driven Origin Creation**: Origins are created based on type structure via `buildListForType`, ensuring origins match the type's indirection levels.
4. **Multi-Level Flow Propagation**: The `flow` function propagates origins through all depths of the lists with a critical assertion:  
`assert(Dst->getDepth() == Src->getDepth() && "Lists must have the same length");` This ensures type safety in origin propagation during expression handling. (Rant with relief: This `assert`​ was quite hard to get right but it helped make the right changes).
5. `Lifetimebound`​ **Semantics**: For reference return types, `lifetimebound`​ now propagates only the outermost origin, not inner pointee origins.

We are also deleting many tests in lifetime-safety-dataflow.cpp related to control flow which are better tested in unit tests and the other lit test.

Fixes: https://github.com/llvm/llvm-project/issues/169758
Fixes: https://github.com/llvm/llvm-project/issues/162834  
Fixes: https://github.com/llvm/llvm-project/issues/169940

### CODE REVIEW

**Comment by usx95** [comment]
* **#168344** <a href="https://app.graphite.com/github/pr/llvm/llvm-project/168344?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/llvm/llvm-project/168344?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 1]
```diff
@@ -64,29 +93,48 @@ void FactsGenerator::run() {
...
+          flow(VDTree->Pointee, InitTree->Pointee, /*Kill=*/true);
+          continue;
+        }
+        flow(VDTree, InitTree, /*Kill=*/true);
+      }
 }
 
 void FactsGenerator::VisitDeclRefExpr(const DeclRefExpr *DRE) {
+  // Skip function references and PR values.
+  if (DRE->getFoundDecl()->isFunctionOrFunctionTemplate() || !DRE->isGLValue())
```
Comment (Xazax-hun) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: What is the motivation of skipping functions? Is there some handling we are missing or are these always safe?

Can you give me an example where a DRE is a PRValue?

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 2]
```diff
@@ -210,11 +317,24 @@ void FactsGenerator::VisitInitListExpr(const InitListExpr *ILE) {
...
+  if (!MTETree)
     return;
-  // A temporary object's origin is the same as the origin of the
-  // expression that initializes it.
-  killAndFlowOrigin(*MTE, *MTE->getSubExpr());
+  if (MTE->isGLValue()) {
+    assert(!SubExprTree ||
+           MTETree->getDepth() == SubExprTree->getDepth() + 1 && "todo doc.");
+    // Issue a loan to the MTE.
+    // const Loan *L = createLoan(FactMgr, MTE);
```
Comment (Xazax-hun) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Nit: commented out code.

**Review by Xazax-hun — COMMENTED** [review]
I just did a very rough first pass, will need to take a second look. I wonder if it is a good idea to call it an `OriginTree` when it is actually a list. I understand that it might become a tree later once/if we have named lifetimes, but I wonder if it is a bit confusing to call it a tree in the interim period.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp (hunk 2 above)
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Done. Added a TODO instead.

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h [hunk 3]
```diff
@@ -28,21 +29,30 @@ inline llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, OriginID ID) {
...
-  Origin(OriginID ID, const clang::ValueDecl *D) : ID(ID), Ptr(D) {}
-  Origin(OriginID ID, const clang::Expr *E) : ID(ID), Ptr(E) {}
+  /// The type at this indirection level.
+  ///
+  /// For `int** pp`:
+  ///   Root origin: QT = `int**` (what pp points to)
+  ///   Pointee origin: QT = `int*` (what *pp points to)
+  ///
+  /// Null for synthetic lvalue origins (e.g., outer origin of DeclRefExpr).
+  QualType QT;
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h]: Done.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 4]
```diff
@@ -127,24 +177,46 @@ void FactsGenerator::VisitCXXNullPtrLiteralExpr(
...
+
+  if (ICE->getCastKind() == CK_LValueToRValue) {
+    // TODO: Decide what to do for x-values here.
+    if (!ICE->getSubExpr()->isLValue())
+      return;
+
+    assert(SrcTree && "LValue being cast to RValue has no origin tree");
+    // The result of an LValue-to-RValue cast on a reference-to-pointer like
+    // has the inner origin. Get rid of the outer origin.
+    flow(getTree(*ICE), SrcTree->Pointee, /*Kill=*/true);
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Added `getOuterOriginID`​ and `peelOuterOrigin`​members

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 5]
```diff
@@ -237,13 +357,24 @@ void FactsGenerator::handleGSLPointerConstruction(const CXXConstructExpr *CCE) {
...
-  else
+
+  if (isGslPointerType(CCE->getArg(0)->getType())) {
+    OriginTree *ArgTree = getTree(*CCE->getArg(0));
+    assert(ArgTree && "GSL pointer argument should have an origin tree");
+    // GSL pointer is constructed from another gsl pointer.
+    // Example:
+    //  View(View v);
+    //  View(const View &v);
+    if (ArgTree->getDepth() == 2)
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Makes sense. Changed to 

```
if (Arg->isGLValue())

```

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Facts.h [hunk 6]
```diff
@@ -155,18 +155,19 @@ class OriginEscapesFact : public Fact {
 
 class UseFact : public Fact {
   const Expr *UseExpr;
-  OriginID OID;
+  // The origins of the expression being used.
```
Comment (ymand) [inline clang/include/clang/Analysis/Analyses/LifetimeSafety/Facts.h]: super nit: maybe explain the choice of 1 as the default length.

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Facts.h [hunk 7]
```diff
@@ -155,18 +155,19 @@ class OriginEscapesFact : public Fact {
...
   // True if this use is a write operation (e.g., left-hand side of assignment).
   // Write operations are exempted from use-after-free checks.
   bool IsWritten = false;
 
 public:
   static bool classof(const Fact *F) { return F->getKind() == Kind::Use; }
 
-  UseFact(const Expr *UseExpr, OriginManager &OM)
-      : Fact(Kind::Use), UseExpr(UseExpr), OID(OM.get(*UseExpr)) {}
+  UseFact(const Expr *UseExpr, llvm::ArrayRef<OriginID> OIDs)
```
Comment (ymand) [inline clang/include/clang/Analysis/Analyses/LifetimeSafety/Facts.h]: Use of ArrayRef forces a copy. But, I would imagine at construction time its common that the caller has constructed the list specificaly for this fact (like line 472 of FactsGenerator.cpp below). At least, provide an overload that allows passing a constructed object by value (to passing by move)?

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h [hunk 8]
```diff
@@ -52,41 +62,118 @@ struct Origin {
...
+  OriginList *peelOuterOrigin() { return InnerList; }
+  OriginID getOuterOriginID() const { return OuterOID; }
 
-  Origin &addOrigin(OriginID ID, const clang::ValueDecl &D);
-  Origin &addOrigin(OriginID ID, const clang::Expr &E);
+  void setInnerOriginList(OriginList *Inner) { InnerList = Inner; }
 
-  // TODO: Mark this method as const once we remove the call to getOrCreate.
-  OriginID get(const Expr &E);
+  size_t getLength() const {
```
Comment (ymand) [inline clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h]: might this be worth tracking eagerly so it doesn't need to be (frequently?) recomputed?

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h [hunk 9]
```diff
@@ -52,41 +62,118 @@ struct Origin {
...
+    OriginID NewID = getNextOriginID();
+    AllOrigins.emplace_back(NewID, D, QT.getTypePtrOrNull());
+    return new (ListAllocator.Allocate<OriginList>()) OriginList(NewID);
+  }
+
+  OriginList *createNode(const Expr *E, QualType QT) {
+    OriginID NewID = getNextOriginID();
+    AllOrigins.emplace_back(NewID, E, QT.getTypePtrOrNull());
+    return new (ListAllocator.Allocate<OriginList>()) OriginList(NewID);
+  }
```
Comment (ymand) [inline clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h]: why define these in the header (given that they are private)?

**Review by ymand — COMMENTED** [review]
Partial review. Looks good so far!

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 10]
```diff
@@ -161,21 +242,38 @@ void FactsGenerator::VisitUnaryOperator(const UnaryOperator *UO) {
 
 void FactsGenerator::VisitReturnStmt(const ReturnStmt *RS) {
   if (const Expr *RetExpr = RS->getRetValue()) {
-    if (hasOrigin(RetExpr)) {
-      OriginID OID = FactMgr.getOriginMgr().getOrCreate(*RetExpr);
-      EscapesInCurrentBlock.push_back(
-          FactMgr.createFact<OriginEscapesFact>(OID, RetExpr));
-    }
+    if (OriginList *List = getOriginsList(*RetExpr))
+      for (OriginList *L = List; L; L = L->peelOuterOrigin())
```
Comment (ymand) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: nit: I think this would be more readable with an explicit `L != nullptr`.

File: clang/lib/Analysis/LifetimeSafety/Origins.cpp [hunk 11]
```diff
@@ -7,85 +7,152 @@
...
+    // for the lvalue itself, with the pointee being the declaration's list.
+    // This models taking the address: `&p` borrows the storage of `p`, not what
+    // `p` points to.
+    if (doesDeclHaveStorage(DRE->getDecl())) {
+      Root = createNode(DRE, QualType{});
+      // This ensures origin sharing: multiple DeclRefExprs to the same
+      // declaration share the same underlying origins.
+      Root->setInnerOriginList(getOrCreateList(DRE->getDecl()));
+    } else {
+      // For reference-typed declarations (e.g., `int& r = p`) which no storage,
```
Comment (ymand) [inline clang/lib/Analysis/LifetimeSafety/Origins.cpp]:
```suggestion
      // For reference-typed declarations (e.g., `int& r = p`) which have no storage,
```

File: clang/test/Sema/warn-lifetime-safety.cpp [hunk 12]
```diff
@@ -943,3 +1065,235 @@ void parentheses(bool cond) {
   }  // expected-note 4 {{destroyed here}}
   (void)*p;  // expected-note 4 {{later used here}}
 }
+
+namespace GH162834 {
```
Comment (ymand) [inline clang/test/Sema/warn-lifetime-safety.cpp]: Why this name? Is this a reference to known issue?

**Review by ymand — COMMENTED** [review]
Reviewed all but FactsGenerator.cpp

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 13]
```diff
@@ -186,8 +284,28 @@ void FactsGenerator::VisitConditionalOperator(const ConditionalOperator *CO) {
...
-  if (OCE->isAssignmentOp() && OCE->getNumArgs() == 2) {
-    handleAssignment(OCE->getArg(0), OCE->getArg(1));
+  if (OCE->getOperator() == OO_Equal && OCE->getNumArgs() == 2) {
+
+    const Expr *LHSExpr = OCE->getArg(0);
+    const Expr *RHSExpr = OCE->getArg(1);
+
+    if (const auto *DRE_LHS =
+            dyn_cast<DeclRefExpr>(LHSExpr->IgnoreParenImpCasts())) {
+      OriginList *LHSList = getOriginsList(*DRE_LHS);
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Good point. I missed this. Added a precheck of hasOrigins.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 14]
```diff
@@ -133,24 +191,47 @@ void FactsGenerator::VisitCXXNullPtrLiteralExpr(
...
+    flow(Dest, SrcList, /*Kill=*/true);
+  if (ICE->getCastKind() == CK_FunctionToPointerDecay ||
+      ICE->getCastKind() == CK_BuiltinFnToFnPtr ||
+      ICE->getCastKind() == CK_ArrayToPointerDecay) {
+    // Ignore function-to-pointer decays.
     return;
-  // An ImplicitCastExpr node itself gets an origin, which flows from the
-  // origin of its sub-expression (after stripping its own parens/casts).
-  killAndFlowOrigin(*ICE, *ICE->getSubExpr());
+  }
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Done

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h [hunk 15]
```diff
@@ -52,41 +62,118 @@ struct Origin {
   }
 };
 
-/// Manages the creation, storage, and retrieval of origins for pointer-like
-/// variables and expressions.
-class OriginManager {
+/// A list of origins representing levels of indirection for pointer-like types.
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h]: Aah I see what you were referring to.

Yes, my idea is to move from an `OriginList` to `OriginTree` to support multiple inner pointers like `std::pair<int*, int*>` . This could be represented as a pre-order array but my initial preference is to have a Tree representation for better understanding.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 16]
```diff
@@ -358,13 +513,13 @@ llvm::SmallVector<Fact *> FactsGenerator::issuePlaceholderLoans() {
...
-      OriginID OID = FactMgr.getOriginMgr().getOrCreate(*PVD);
-      PlaceholderLoanFacts.push_back(
-          FactMgr.createFact<IssueFact>(L->getID(), OID));
-    }
+    OriginList *List = getOriginsList(*PVD);
+    if (!List)
+      continue;
+    const PlaceholderLoan *L =
+        FactMgr.getLoanMgr().createLoan<PlaceholderLoan>(PVD);
+    PlaceholderLoanFacts.push_back(
```
Comment (Xazax-hun) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: What is the main reason to not create placeholder loans for the nested origins?

**Review by Xazax-hun — APPROVED** [review]
I have some questions inline but overall looks good to me.

File: clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h (hunk 15 above)
[the remark this answers is not in the document]
Comment (ymand) [reply clang/include/clang/Analysis/Analyses/LifetimeSafety/Origins.h]: Great. We can discuss further, but I suspect you won't get anything additional from a tree -- I don't believe that's come up in Nullability.

**Review by ymand — APPROVED** [review]

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 17]
```diff
@@ -275,22 +416,41 @@ void FactsGenerator::handleFunctionCall(const Expr *Call,
...
+        ArgList = getRValueOrigins(Args[I], ArgList);
+      }
+      if (isGslOwnerType(Args[I]->getType())) {
+        // GSL construction creates a view that borrows from arguments.
+        // This implies flowing origins through the list structure.
+        flow(CallList, ArgList, KillSrc);
+        KillSrc = false;
+      }
+    } else if (IsArgLifetimeBound(I)) {
+      // Lifetimebound on a non-GSL-ctor function means the returned
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Interesting. I didn't know about this for Rust. For C++, doing this many false positives on the usage of lifetimebound.

For example, consider this https://github.com/llvm/llvm-project/issues/162834 which will be closed by this PR.

```cpp
template <class T>
struct StatusOr {
    ~StatusOr() {}
    const T& value() const& [[clang::lifetimebound]] { return data; }

   private:
    T data;
};
void foo() {
    std::string_view view;
    {
        StatusOr<std::string_view> view_or = getViewOr();
        view = view_or.value();
    }
    std::cout << view;  // error: a use-after-free. Bad!
}
```

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp (hunk 16 above)
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: This directly effects annotation suggestions. We could do that but we would need to silence the annotation suggestions for inner origins because lifetimebound cannot express those.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 18]
```diff
@@ -180,8 +260,29 @@ void FactsGenerator::VisitConditionalOperator(const ConditionalOperator *CO) {
...
   // Assignment operators have special "kill-then-propagate" semantics
   // and are handled separately.
-  if (OCE->isAssignmentOp() && OCE->getNumArgs() == 2) {
-    handleAssignment(OCE->getArg(0), OCE->getArg(1));
+  if (OCE->getOperator() == OO_Equal && OCE->getNumArgs() == 2) {
+
+    const Expr *LHSExpr = OCE->getArg(0);
+    const Expr *RHSExpr = OCE->getArg(1);
+
+    if (const auto *DRE_LHS =
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Done.

File: clang/lib/Analysis/LifetimeSafety/LifetimeSafety.cpp [hunk 19]
```diff
@@ -31,6 +31,19 @@
 namespace clang::lifetimes {
 namespace internal {
 
+static void DebugOnlyFunction(AnalysisDeclContext &AC, const CFG &Cfg,
```
Comment (mikaelholmen) [inline clang/lib/Analysis/LifetimeSafety/LifetimeSafety.cpp]: Hi @usx95 

If building without asserts this function is unused and we get
```
../../clang/lib/Analysis/LifetimeSafety/LifetimeSafety.cpp:34:13: error: unused function 'DebugOnlyFunction' [-Werror,-Wunused-function]
   34 | static void DebugOnlyFunction(AnalysisDeclContext &AC, const CFG &Cfg,
      |             ^~~~~~~~~~~~~~~~~
1 error generated.
``

Comment (mikaelholmen) [reply clang/lib/Analysis/LifetimeSafety/LifetimeSafety.cpp]: Yep, thanks!
