### PR TITLE
[Clang] Fix dependent local class instantiation bugs

### LINKED ISSUE #59734: `inline function ... is not defined` points to the definition, then get 'undefined reference'
This is a regression introduced in Clang 15.

```cpp
template <typename F>
void foo()
{
    [&](auto)
    {
        struct Guard { ~Guard() {} };
        Guard guard;
    }(42);
}

int main()
{
    foo<int>();
}
```
[Godbolt link](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:14,positionColumn:2,positionLineNumber:14,selectionStartColumn:2,selectionStartLineNumber:14,startColumn:2,startLineNumber:14),source:'template+%3Ctypename+F%3E%0Avoid+foo()%0A%7B%0A++++%5B%26%5D(auto)%0A++++%7B%0A++++++++struct+Guard+%7B+~Guard()+%7B%7D+%7D%3B%0A++++++++Guard+guard%3B%0A++++%7D(42)%3B%0A%7D%0A%0Aint+main()%0A%7B%0A++++foo%3Cint%3E()%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:54.67015022860875,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang_trunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:c%2B%2B,libs:!(),options:'',paneName:Clang,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:Clang,t:'0')),header:(),l:'4',m:46.40234948604993,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+15.0.0',editorid:1,fontScale:13,fontUsePx:'0',j:2,paneName:'Clang+output',wrap:'0'),l:'5',n:'0',o:'Clang+output',t:'0')),header:(),l:'4',m:53.59765051395007,n:'0',o:'',s:0,t:'0')),k:45.32984977139125,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

Clang says:
```none
<source>:6:24: warning: inline function 'foo()::(anonymous class)::operator()(int)::Guard::~Guard' is not defined [-Wundefined-inline]
        struct Guard { ~Guard() {} };
                       ^
<source>:7:15: note: used here
        Guard guard;
              ^
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-a1895d.o: in function `operator()<int>':
<source>:8: undefined reference to `foo<int>()::{lambda(auto:1)#1}::operator()<int>(int) const::Guard::~Guard()'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
While GCC and MSVC accept this code.

Tested on Clang 15, and on trunk commit `a564048899a1a1de526a02cfd1a5d691ec31bafd`.

### LINKED ISSUE #132208: [Clang] Destructor definition is not compiled for local class in generic lambda initializing a variable template
```c++
template <class>
constexpr auto f{[] (auto) {
    struct OnScopeExit { ~OnScopeExit() {} }
    pending;
}};

int main() {
    f<int>(0);
}
```

See https://compiler-explorer.com/z/6vneqf93z.

Warning and linker error since Clang 15:
```console
<source>:3:26: warning: inline function '(anonymous class)::operator()(int)::OnScopeExit::~OnScopeExit' is not defined [-Wundefined-inline]
    3 |     struct OnScopeExit { ~OnScopeExit() {} }
      |                          ^
<source>:4:5: note: used here
    4 |     pending;
      |     ^
1 warning generated.
ASM generation compiler returned: 0
<source>:3:26: warning: inline function '(anonymous class)::operator()(int)::OnScopeExit::~OnScopeExit' is not defined [-Wundefined-inline]
    3 |     struct OnScopeExit { ~OnScopeExit() {} }
      |                          ^
<source>:4:5: note: used here
    4 |     pending;
      |     ^
1 warning generated.
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.1/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-eeceaa.o: in function `auto f<int>::{lambda(auto:1)#1}::operator()<int>(int) const':
<source>:5:(.text._ZNK1fIiEMUlT_E_clIiEEDaS1_[_ZNK1fIiEMUlT_E_clIiEEDaS1_]+0x14): undefined reference to `f<int>::{lambda(auto:1)#1}::operator()<int>(int) const::OnScopeExit::~OnScopeExit()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by zyn0217**
This patch fixes two long-standing bugs that prevent Clang from instantiating local class members inside a dependent context. These bugs were introduced in commits 21eb1af469c3 and 919df9d75a.

21eb1af469c3 introduced a concept called eligible methods such that it did an attempt to skip past ineligible method instantiation when instantiating class members. Unfortunately, this broke the instantiation chain for local classes - getTemplateInstantiationPattern() would fail to find the correct definition pattern if the class was defined within a partially transformed dependent context.

919df9d75a introduced a separate issue by incorrectly copying the DeclarationNameInfo during function definition instantiation from the template pattern, even though that DNI might contain a transformed TypeSourceInfo. Since that TSI was already updated when the declaration was instantiated, this led to inconsistencies. As a result, the final instantiated function could lose track of the transformed declarations, hence we crash: https://compiler-explorer.com/z/vjvoG76Tf.

This PR corrects them by

1. Removing the bypass logic for method instantiation. The eligible flag is independent of instantiation and can be updated properly afterward, so skipping instantiation is unnecessary.

2. Carefully handling TypeSourceInfo by creating a new instance that preserves the pattern's source location while using the already transformed type.

Fixes https://github.com/llvm/llvm-project/issues/59734
Fixes https://github.com/llvm/llvm-project/issues/132208

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -4264,7 +4264,8 @@ Sema::InstantiateClassMembers(SourceLocation PointOfInstantiation,
       if (FunctionDecl *Pattern =
               Function->getInstantiatedFromMemberFunction()) {
 
-        if (Function->isIneligibleOrNotSelected())
+        if (!Instantiation->getDeclContext()->isDependentContext() &&
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:4267]: Hmm... I don't think we want to go this far, right?    We still would like to aggressively instantiate these so we get diagnostics/etc, even if it is in a dependent context.

**Review by erichkeane — COMMENTED** [review]
This once again looks like an attempt at hacking around our lack of delayed lambda body instantiation... And this one has some pretty sizable negatives as far as I can see.  I'm not sure I really like this direction.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:4267]: It does instantiate the function declarations in the dependent context. In fact this fixes a bug introduced in clang 15: we skipped the instantiation of local classes here because they're not correctly marked "eligible" because the context the class lives in is dependent.

On the other hand I'm not quite clear if it is suitable to jump past any instantiations at all. it might be an incorrect optimization, but again I'm not quite familiar with the proposal that introduced this line.

**Comment by zyn0217** [comment]
> This once again looks like an attempt at hacking around our lack of delayed lambda body instantiation... And this one has some pretty sizable negatives as far as I can see.  I'm not sure I really like this direction.

Yeah, admittedly this is another workaround of not having that mechanism. But the bug was a 15 regression, and due to some historic incorrect patches (which I'm fixing here) it ends up becoming hard to get the behavior correct as 14.

**Comment by zyn0217** [comment]
> I wouldn't be able to convince you to start work on the delayed lambda body instantiation instead, would I ? :-P

AFAIK @LYP951018 is already working on this region. Though I haven't test that patch with it yet 🥲

**Comment by zyn0217** [comment]
I talked to @erichkeane and updated the approach to make it feel less like a workaround and independent of lambda instantiation.

As noted, both cases worked prior to clang 15, which means they didn’t rely on deferred lambda body instantiation to compile correctly.

Regarding the lambda side of things - since @mizvekov is already working on a major ContextDecl refactoring in that area, I don’t think it's appropriate to initiate another large-scale change simultaneously. That would result in a lot of conflicts, as I can expect. It's also expected that much of the present issues will be alleviated once that gets landed and it's not too late for us to start working on the lambda deferral afterwards.

That said, this patch is aimed at fixing a regression and doesn't actually touch the lambda code itself (even though the bug involves lambdas), so it shouldn't become a burden that complicates future work on deferred lambda body instantiation. In fact, I think this should actually improve our test coverage overall.

File: clang/test/SemaTemplate/instantiate-local-class.cpp [hunk 2]
```diff
@@ -1,6 +1,9 @@
 // RUN: %clang_cc1 -verify -std=c++11 %s
 // RUN: %clang_cc1 -verify -std=c++11 -fdelayed-template-parsing %s
 // RUN: %clang_cc1 -verify -std=c++20 -fsyntax-only %s
+// RUN: %clang_cc1 -std=c++17 %s -DCodeGen -emit-llvm -triple %itanium_abi_triple -o - | FileCheck %s -dump-input=always
+
+#ifndef CodeGen
```
Comment (erichkeane) [inline clang/test/SemaTemplate/instantiate-local-class.cpp:6]: Please don't do this.  Just add a separate test to the CodeGen directory.

**Comment by zyn0217** [comment]
Review ping

**Review by erichkeane — APPROVED** [review]
Woops!  Sorry, I thought I had already approved this with teh nit about the tests.  Sorry about that!

**Review by mizvekov — APPROVED** [review]
LGTM as well.

**Comment by mizvekov** [comment]
Can you send reproducer and / or stack trace?

FYI you can use `CLANG_CRASH_DIAGNOSTICS_DIR` environment variable to make clang put these automatically generated reproducers up in a directory which will have its contents exported as artifacts.

**Comment by mysterymath** [comment]
Here's a link to a reproducer tar; I was able to verify that this reproduces locally using our toolchain prebuilt from CI:

https://storage.googleapis.com/fuchsia-artifacts/builds/8717549930672410881/build-debug/clang-crashreports/map_setting_store-0b592c.tar

**Comment by mizvekov** [comment]
Yeah, I confirm this crashes clang, and reverting this commit does fix the crash.

For reference, this is the stack trace:
```
1.	<eof> parser at end of file
2.	../../src/lib/fxl/observer_list.h:193:54: instantiating function definition 'fxl::ObserverListBase<zxdb::SettingStoreObserver>::Iter<const fxl::ObserverListBase<zxdb::SettingStoreObserver>>::~Iter'
 #0 0x0000000104d687b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x104a787b8)
 #1 0x0000000104d68cdc PrintStackTraceSignalHandler(void*) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x104a78cdc)
 #2 0x0000000104d66b9c llvm::sys::RunSignalHandlers() (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x104a76b9c)
 #3 0x0000000104d695a8 SignalHandler(int, __siginfo*, void*) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x104a795a8)
 #4 0x0000000184d77624 (/usr/lib/system/libsystem_platform.dylib+0x1804ab624)
 #5 0x0000000109f3dcac clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool)::$_4::operator()() const (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x109c4dcac)
 #6 0x0000000109f3dcac clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool)::$_4::operator()() const (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x109c4dcac)
 #7 0x0000000109f3d3d4 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x109c4d3d4)
 #8 0x0000000109f407a0 clang::Sema::PerformPendingInstantiations(bool, bool) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x109c507a0)
 #9 0x0000000108f23178 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x108c33178)
#10 0x0000000108f23788 clang::Sema::ActOnEndOfTranslationUnit() (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x108c33788)
#11 0x0000000108e236e0 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x108b336e0)
#12 0x0000000108cfb610 clang::ParseAST(clang::Sema&, bool, bool) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x108a0b610)
#13 0x00000001066eeb34 clang::ASTFrontendAction::ExecuteAction() (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x1063feb34)
#14 0x0000000105bf3564 clang::CodeGenAction::ExecuteAction() (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x105903564)
#15 0x00000001066ee358 clang::FrontendAction::Execute() (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x1063fe358)
#16 0x00000001065cdb8c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x1062ddb8c)
#17 0x0000000106960d30 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x106670d30)
#18 0x0000000100301a40 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x100011a40)
#19 0x00000001002f36e0 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x1000036e0)
#20 0x00000001002f2404 clang_main(int, char**, llvm::ToolContext const&) (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x100002404)
#21 0x000000010032bb48 main (/Users/mizvekov/Repos/llvm/6/build/dbg/llvm/bin/clang-21+0x10003bb48)
#22 0x000000018499eb4c
```

@zyn0217 FYI

**Comment by zyn0217** [comment]
Thanks for the revert.

I added an assertion to `NameLocPointsToPattern` after line 5637 and it fired because `PatternName.getNamedTypeInfo` is null. This is strange because the instantiated function does have a TypeSourceInfo, which is guarded by line 5630.

I need a reduced version to figure out what happened.
