### PR TITLE
[libc++][ranges][abi-break] Fix `movable_box` overwriting memory of data that lives in the tail padding

### LINKED ISSUE #70506: [libc++] `std::ranges::__movable_box` can overwrite data that comes after it
`std::ranges::__movable_box` can overwrite data that comes after it
this is similar to #68552

This example shows how user would hit this bug
```cpp
int main() {
    auto f = [l = 0.0L, b = false](int i) { return i; };

    auto v1 = std::vector{1, 2, 3, 4, 5} | std::views::transform(f);
    auto v2 = std::vector{1, 2, 3, 4, 5} | std::views::transform(f);

    v1 = std::move(v2);

    for (auto x : v1) {  // SEGV here
        std::cout << x;
    }
}
```

This example explains why it happens
```cpp
struct A {
    A() {}

    double x{};
    bool y{};

    A(const A&) = default;
    A& operator=(const A&) = delete;
};

struct Test {
    Test() {}

    [[no_unique_address]] std::ranges::__movable_box<A> a;
    bool b = true;
};


int main(){
    static_assert(std::ranges::__doesnt_need_empty_state<A>);
    Test test;
    assert(test.b);
    test.a = std::ranges::__movable_box<A>{};
    assert(test.b);  // boom
}

```

movable boxes are widely used in ranges.

It uses `[[no_unique_address]]` in its data member. But on `operator=`, it calls `destroy_at` followed by `construct_at`. If the data member has tail padding, the tail padding would be zeroed out. If the user put the next data in the tail padding, this would overwrite the next data member. We have done this by ourselves, e.g. in `transform_view`, the next data member is the underlying view and the first example shows that the underlying view's memory was zeroed out, causing it to crash

https://godbolt.org/z/GcYoer4W4
https://godbolt.org/z/hvh4v1EWK

### PR DESCRIPTION
**Pull request by huixie90**
fixes #70506 

The detailed problem description is in #70506 

The original proposed fix was to remove `[[no_unique_address]]` except when `_Tp` is empty.

Edit:
After the discussion in the comments below, the new fix here is to remove the `[[no_unique_address]]` from `movable_box` in the cases where we need to add our own assignment operator, which has contains the problematic `construct_at`

### CODE REVIEW

**Comment by philnik777** [comment]
Is an empty object allowed to access it's padding? If yes, we have to remove `[[no_unique_address]]` in all cases.

**Comment by huixie90** [comment]
> Is an empty object allowed to access it's padding? If yes, we have to remove `[[no_unique_address]]` in all cases.

I don't know the answer, and if the following code is valid, then yes we cannot use EBO or `no_unqiue_address`

```
struct e {
    e(){
        std::memset(this, 0x00, sizeof(e));
    }
};

struct x :e {
    bool b = true;

    void foo() {
        std::destroy_at(std::addressof(static_cast<e&>(*this)));
        std::construct_at(std::addressof(static_cast<e&>(*this)));
    }
};

struct y {
    [[no_unique_address]] e e1;
    bool b= true;

    void foo() {
        std::destroy_at(std::addressof(e1));
        std::construct_at(std::addressof(e1));
    }
};

static_assert(sizeof(x) == sizeof(bool));
static_assert(sizeof(y) == sizeof(bool));

int main(){
    x x1;
    assert(x1.b);
    x1.foo();
    assert(x1.b); // boom

    y y1;
    assert(y1.b);
    y1.foo();
    assert(y1.b); // boom
}
```

**Comment by timsong-cpp** [comment]
You don't need the `memset` for the assert to fail - since `construct_at` performs value-initialization in that case, the memset will fail as long as value-initialization for the class performs zero-initialization (i.e., if the class has a non-user-provided default constructor).

**Comment by timsong-cpp** [comment]
That said, you should be able to keep using `no_unique_address` if the destroy-and-reconstruct path is not actually engaged (i.e., the type is natively assignable)?

**Comment by huixie90** [comment]
> That said, you should be able to keep using `no_unique_address` if the destroy-and-reconstruct path is not actually engaged (i.e., the type is natively assignable)?

I applied your suggestion.

File: libcxx/include/__ranges/movable_box.h [hunk 1]
```diff
@@ -134,6 +134,13 @@ concept __doesnt_need_empty_state =
          // 2. Otherwise, movable-box<T> should store only a T if either T models movable or
          //    is_nothrow_move_constructible_v<T> is true.
          : movable<_Tp> || is_nothrow_move_constructible_v<_Tp>);
+
+// we can only use no_unique_address if _Tp has assignment operators,
+// so that we don't need to add our own assignment operator, which
+// contains problematic construct_at
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:140]:
```
When _Tp doesn't have an assignment operator, we must implement __movable_box's assignment operator
by doing destroy_at followed by construct_at. However, that implementation strategy leads to UB if the nested
_Tp is potentially overlapping [HERE EXPLAIN THE SITUATION SUMMARIZED IN https://github.com/llvm/llvm-project/issues/70494#issuecomment-1845646490].

Hence, when the _Tp doesn't have an assignment operator, we can't risk making it a potentially-overlapping
subobject because of the above, and we don't use [[no_unique_address]] in that case.
```

File: libcxx/include/__ranges/movable_box.h [hunk 2]
```diff
@@ -144,23 +151,47 @@ concept __doesnt_need_empty_state_for_move = movable<_Tp> || is_nothrow_move_con
...
+template <class _Tp>
+concept __can_use_no_unique_address = copyable<_Tp>;
 #  endif
 
+template <class _Tp>
+struct __movable_box_base {
+  _Tp __val_;
+
+  template <class... _Args>
+    requires is_constructible_v<_Tp, _Args&&...>
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:164]: I would suggest dropping these `requires` inside `__movable_box_base`, since they're already checked in `__movable_box`. It makes the code just a bit simpler and makes it clearer that requirement-checking in this helper class is not necessary.

However, you can add `in_place_t` to disambiguate with any copy constructor, and it's also consistent with the constructor for `__movable_box` itself.

File: libcxx/include/__ranges/movable_box.h [hunk 3]
```diff
@@ -144,23 +151,47 @@ concept __doesnt_need_empty_state_for_move = movable<_Tp> || is_nothrow_move_con
...
+  _LIBCPP_HIDE_FROM_ABI constexpr explicit __movable_box_base(_Args&&... __args)
+      : __val_(std::forward<_Args>(__args)...) {}
+};
+
 template <__movable_box_object _Tp>
   requires __doesnt_need_empty_state<_Tp>
-class __movable_box<_Tp> {
-  _LIBCPP_NO_UNIQUE_ADDRESS _Tp __val_;
+class __movable_box<_Tp> : private __movable_box_base<_Tp> {
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:182]: Can you make this a member with `[[no_unique_address]]` instead of a base class? This would remove the possibility of constructor inheritance messing stuff up. In that case maybe rename to `__movable_box_holder` or something.

File: libcxx/test/std/ranges/range.adaptors/range.transform/general.pass.cpp [hunk 4]
```diff
@@ -108,5 +108,22 @@ int main(int, char**) {
   }
 #endif
 
+  // GH issue #70506
```
Comment (ldionne) [inline libcxx/test/std/ranges/range.adaptors/range.transform/general.pass.cpp:111]: It looks like the following views have the same problem at a high level, because they use `__movable_box` as well:

```
take_while_view
filter_view
single_view
drop_while_view
repeat_view
transform_view
chunk_by_view
```

I think it would be worthwhile to add a regression test for each of them. Maybe a single test that checks all of them is the best approach.

File: libcxx/include/__ranges/movable_box.h [hunk 5]
```diff
@@ -134,6 +134,13 @@ concept __doesnt_need_empty_state =
          // 2. Otherwise, movable-box<T> should store only a T if either T models movable or
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:134]: Not attached to this line: We need to add a release note in the ABI Changes section. You can add something as you think and I can help with the wording if you're unsure how much detail we want to include.

File: libcxx/include/__ranges/movable_box.h [hunk 6]
```diff
@@ -134,6 +134,13 @@ concept __doesnt_need_empty_state =
...
          //    is_nothrow_move_constructible_v<T> is true.
          : movable<_Tp> || is_nothrow_move_constructible_v<_Tp>);
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:136]: Also not attached to this line: We need to introduce an ABI tag for everything that is impacted by this change. For now, I think this should be:

```
take_while_view
filter_view
single_view
drop_while_view
repeat_view
transform_view
chunk_by_view
__movable_box
```

I suggest doing something along those lines:

```
diff --git a/libcxx/include/__config b/libcxx/include/__config
index 7f66042f9025..1a06070ce3bf 100644
--- a/libcxx/include/__config
+++ b/libcxx/include/__config
@@ -193,6 +193,9 @@
 #    endif
 #  endif
 
+// TODO: Comprehensive explanation of what this is.
+#  define _LIBCPP_ABI_2023_OVERLAPPING_SUBOBJECT_FIX_TAG __attribute__((__abi_tag__("whatever")))
+
 #  if defined(_LIBCPP_BUILDING_LIBRARY) || _LIBCPP_ABI_VERSION >= 2
 // Define a key function for `bad_function_call` in the library, to centralize
 // its vtable and typeinfo to libc++ rather than having all other libraries
diff --git a/libcxx/include/__ranges/filter_view.h b/libcxx/include/__ranges/filter_view.h
index 1cef94ca6744..7647790aeed2 100644
--- a/libcxx/include/__ranges/filter_view.h
+++ b/libcxx/include/__ranges/filter_view.h
@@ -51,6 +51,7 @@ _LIBCPP_BEGIN_NAMESPACE_STD
 namespace ranges {
   template<input_range _View, indirect_unary_predicate<iterator_t<_View>> _Pred>
     requires view<_View> && is_object_v<_Pred>
+  _LIBCPP_ABI_2023_OVERLAPPING_SUBOBJECT_FIX_TAG
   class filter_view : public view_interface<filter_view<_View, _Pred>> {
     _LIBCPP_NO_UNIQUE_ADDRESS _View __base_ = _View();
     _LIBCPP_NO_UNIQUE_ADDRESS __movable_box<_Pred> __pred_;
diff --git a/libcxx/include/__ranges/movable_box.h b/libcxx/include/__ranges/movable_box.h
index 6615533d3743..eddc1fb27739 100644
--- a/libcxx/include/__ranges/movable_box.h
+++ b/libcxx/include/__ranges/movable_box.h
@@ -55,6 +55,7 @@ concept __movable_box_object =
 namespace ranges {
 // Primary template - uses std::optional and introduces an empty state in case assignment fails.
 template <__movable_box_object _Tp>
+_LIBCPP_ABI_2023_OVERLAPPING_SUBOBJECT_FIX_TAG
 class __movable_box {
   _LIBCPP_NO_UNIQUE_ADDRESS optional<_Tp> __val_;
 
diff --git a/libcxx/include/__ranges/transform_view.h b/libcxx/include/__ranges/transform_view.h
index 3678f9d64f7b..3c49ac09fc94 100644
--- a/libcxx/include/__ranges/transform_view.h
+++ b/libcxx/include/__ranges/transform_view.h
@@ -69,6 +69,7 @@ template <input_range _View, move_constructible _Fn>
 template <input_range _View, copy_constructible _Fn>
 #  endif
   requires __transform_view_constraints<_View, _Fn>
+_LIBCPP_ABI_2023_OVERLAPPING_SUBOBJECT_FIX_TAG
 class transform_view : public view_interface<transform_view<_View, _Fn>> {
   template<bool> class __iterator;
   template<bool> class __sentinel;

```

So basically we add an ABI tag in `__config`, we document it there, and then we apply that ABI tag to `__movable_box` itself but also all the public types that use it, which fortunately doesn't seem to be too many types.

File: libcxx/include/__ranges/movable_box.h [hunk 7]
```diff
@@ -176,27 +207,29 @@ class __movable_box<_Tp> {
...
+  _LIBCPP_HIDE_FROM_ABI constexpr _Tp const& operator*() const noexcept { return this->__val_; }
+  _LIBCPP_HIDE_FROM_ABI constexpr _Tp& operator*() noexcept { return this->__val_; }
 
-  _LIBCPP_HIDE_FROM_ABI constexpr const _Tp* operator->() const noexcept { return std::addressof(__val_); }
-  _LIBCPP_HIDE_FROM_ABI constexpr _Tp* operator->() noexcept { return std::addressof(__val_); }
+  _LIBCPP_HIDE_FROM_ABI constexpr const _Tp* operator->() const noexcept { return std::addressof(this->__val_); }
+  _LIBCPP_HIDE_FROM_ABI constexpr _Tp* operator->() noexcept { return std::addressof(this->__val_); }
 
   _LIBCPP_HIDE_FROM_ABI constexpr bool __has_value() const noexcept { return true; }
 };
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:235]: Not attached to this line

The following types use `__movable_box`, but they do not actually apply `[[no_unique_address]]` to it (or they have a following member that is not `[[no_unique_address]]`), which means that they don't technically have a bug right now:

```
single_view
repeat_view
chunk_by_view
```

We should take the opportunity of this ABI break to make them take advantage of the optimization, with a test.

**Review by ldionne — CHANGES_REQUESTED** [review]
Thank you so much for the patch, I think it's looking really good but I have some comments. I think this should be good once my comments are applied.

File: libcxx/include/__ranges/movable_box.h (hunk 6 above)
Comment (ldionne) [reply libcxx/include/__ranges/movable_box.h:136]: @huixie90 We actually discussed this in the libc++ monthly meeting today and @philnik777 made a really good observation. This change is only an ABI break for types that *contain* a `__movable_box` object, since it can change the layout of the outer type. But the layout of `__movable_box` itself never changes (when it's not a member of something else). This is not so relevant for `__movable_box`, but it's extremely relevant for `std::expected`. This basically means that adding an ABI tag to `__movable_box` itself isn't useful, instead we should add an ABI tag to the types whose layout may change, which are types that use `__movable_box` in their implementation.

If we added an ABI tag, we'd essentially create a lot of linker failures (due to the mangling changes) for cases where there is no actual ABI concern, such as passing such an object as an argument or else. And the cases where this is *actually* an ABI break (when it appears as a member of something else) are exactly the cases where an ABI tag is not going to help, since ABI tags don't propagate.

CC @jiixyj since this will apply to `std::expected` as well. But for `std::expected`, I don't think we have any type that holds an `expected` as an implementation detail, which would mean that we don't need to ABI tag anything.

File: libcxx/include/__config [hunk 8]
```diff
@@ -200,6 +200,18 @@
...
 
+#  ifndef _LIBCPP_NO_ABI_TAG
+// We had some bugs where we use [[no_unique_address]] together with construct_at,
+// which causes UB as the call on construct_at could write to overlapping subobjects
+//
+// https://github.com/llvm/llvm-project/issues/70506
+// https://github.com/llvm/llvm-project/issues/70494
+//
+// To fix the bug we had to change the ABI of some classes to remove [[no_unique_address]] under certain conditions.
+// The below macro is used for all classes that have ABI changed as part of the bug fix
```
Comment (ldionne) [inline libcxx/include/__config:211]:
```suggestion
// The below macro is used for all classes whose ABI has changed as part of the fixing these bugs.
```

File: libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp [hunk 9]
```diff
@@ -0,0 +1,64 @@
+//===----------------------------------------------------------------------===//
```
Comment (ldionne) [inline libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp:1]: Nitpick about the test name, let's say `ranges_robust_against_...` instead of `range_robust_against_...`, for consistency!

File: libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+//
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+// UNSUPPORTED: c++03, c++11, c++14, c++17
+
+// Test that views that use __movable_box do not overwrite overlapping subobjects.
```
Comment (ldionne) [inline libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp:11]: Let's add a link to the bug here.

File: libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+  constexpr int* end() const { return nullptr; }
+};
+
+template <class T>
+struct S {
+  [[no_unique_address]] T t{};
+  char c = 42;
+};
+
+template <class T>
```
Comment (ldionne) [inline libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp:40]:
```suggestion
template <class View>
```

File: libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+};
+
+struct View : std::ranges::view_base {
+  constexpr int* begin() const { return nullptr; }
+  constexpr int* end() const { return nullptr; }
+};
+
+template <class T>
+struct S {
+  [[no_unique_address]] T t{};
```
Comment (ldionne) [inline libcxx/test/std/ranges/range_robust_against_no_unique_address.pass.cpp:36]:
```suggestion
  [[no_unique_address]] View view{};
```

File: libcxx/include/__ranges/chunk_by_view.h [hunk 13]
```diff
@@ -54,7 +54,8 @@ namespace ranges {
 
 template <forward_range _View, indirect_binary_predicate<iterator_t<_View>, iterator_t<_View>> _Pred>
   requires view<_View> && is_object_v<_Pred>
-class chunk_by_view : public view_interface<chunk_by_view<_View, _Pred>> {
+class _LIBCPP_ABI_2023_OVERLAPPING_SUBOBJECT_FIX_TAG chunk_by_view
+    : public view_interface<chunk_by_view<_View, _Pred>> {
   _LIBCPP_NO_UNIQUE_ADDRESS _View __base_ = _View();
   _LIBCPP_NO_UNIQUE_ADDRESS __movable_box<_Pred> __pred_;
```
Comment (ldionne) [inline libcxx/include/__ranges/chunk_by_view.h:61]: I think we should mark `__cached_begin_` with `NO_UNIQUE_ADDRESS` so that we can reuse the padding of the non-propagating-cache in some cases. We should add a simple test that this works.

File: libcxx/test/libcxx/ranges/range.adaptors/range.move.wrap/no_unique_address.pass.cpp [hunk 14]
```diff
@@ -8,49 +8,73 @@
```
Comment (ldionne) [inline libcxx/test/libcxx/ranges/range.adaptors/range.move.wrap/no_unique_address.pass.cpp:8]: I might suggest keeping the old test around, but renaming it to something like `empty_object.pass.cpp`, since it seems to have been written specifically to test something about empty objects. I don't remember why I wrote it that way anymore, and https://reviews.llvm.org/D102135 is not responsive right now but I suspect there might be a rationale.

I would also rename copyable-box to movable-box as a drive-by in that test file, since it was forgotten when we renamed the type.

File: libcxx/test/libcxx/ranges/range.factories/range.repeat.view/no_unique_address.compile.pass.cpp [hunk 15]
```diff
@@ -0,0 +1,21 @@
+//===----------------------------------------------------------------------===//
+//
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+// UNSUPPORTED: c++03, c++11, c++14, c++17
+// XFAIL: msvc
```
Comment (ldionne) [inline libcxx/test/libcxx/ranges/range.factories/range.repeat.view/no_unique_address.compile.pass.cpp:10]: Let's add a comment saying 

```
// This test ensures that we use `[[no_unique_address]]` in `repeat_view`.
```

File: libcxx/include/__ranges/movable_box.h [hunk 16]
```diff
@@ -134,6 +134,20 @@ concept __doesnt_need_empty_state =
          // 2. Otherwise, movable-box<T> should store only a T if either T models movable or
          //    is_nothrow_move_constructible_v<T> is true.
          : movable<_Tp> || is_nothrow_move_constructible_v<_Tp>);
+
+// When _Tp doesn't have an assignment operator, we must implement __movable_box's assignment operator
+// by doing destroy_at followed by construct_at. However, that implementation strategy leads to UB if the nested
+// _Tp is potentially overlapping. As it is doing a non-transparent replacement of the sub-object, which means that
```
Comment (ldionne) [inline libcxx/include/__ranges/movable_box.h:140]:
```suggestion
// _Tp is potentially overlapping, as it is doing a non-transparent replacement of the sub-object, which means that
```

**Review by ldionne — COMMENTED** [review]
This is *almost* good to go, thanks!

File: libcxx/include/__ranges/chunk_by_view.h (hunk 13 above)
Comment (huixie90) [reply libcxx/include/__ranges/chunk_by_view.h:61]: Have tried but it doe not work as expected. This is because `__non_propagating_cache` has a member `optional`, which is not marked as `no_unique_address`.

**Review by ldionne — APPROVED** [review]
Huge thanks for all the work you've put on this patch, this is a small one but I know how much work went into it due to how tricky it is. This looks good to me now. Please merge as soon as you're ready.
