### PR TITLE
[Clang][Sema] Disallow applying `onwership_returns` to functions that return non-pointers

### LINKED ISSUE #99501: [Clang][Frontend] Clang allows wrong usage of `ownership_returns`.
Clang does not report an error for obviously wrong usage of `ownership_returns`  attribute. 

`void foo(void) __attribute__((ownership_returns(foo)));`

In above example, function returns nothing, so `ownership_returns` does not make any sense.

Example on godbolt (trunk): https://godbolt.org/z/xsGaE6e8r

### PR DESCRIPTION
**Pull request by pskrgag**
`onwership_returns`  works only with pointers, since it models user-defined memory allocation functions. Make semantics more clear and report an error if attribute is attached to wrong function.

Closes #99501

### CODE REVIEW

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 1]
```diff
@@ -1481,6 +1481,17 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
     break;
   }
 
+  // Allow only pointers to be return type for functions with ownership_takes
+  // attribute. This matches with current OwnershipAttr::Takes semantics
+  if (K == OwnershipAttr::Returns) {
```
Comment (Sirraide) [inline clang/lib/Sema/SemaDeclAttr.cpp:1486]: This comment seems to be talking about `ownership_takes`, and not `ownership_returns`?

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -1308,6 +1308,10 @@ Crash and bug fixes
 Improvements
 ^^^^^^^^^^^^
 
+- Improved handling of ``__attribute__((ownership_returns(class, idx)))``. Now clang
+  reports an error if attribute is attached to a function that returns non-pointer
+  value
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:1313]:
```suggestion
- Improved the handling of the `ownership_returns` attribute. Now, Clang reports an 
  error if the attribute is attached to a function that returns a non-pointer value. 
  Fixes (#GH99501)
```

**Review by Sirraide — COMMENTED** [review]
The implementation in and of itself lgtm, except for two minor comments.

That said, I have never heard of this attribute before, and our documentation seems to be rather lacking in this respect. Maybe @AaronBallman has an idea as to who might know more about this...

**Comment by AaronBallman** [comment]
Adding the static analysis code owners for input.

Also, precommit CI found a valid failure:
```
FAIL: Clang :: AST/attr-print-emit.cpp (400 of 20466)
******************** TEST 'Clang :: AST/attr-print-emit.cpp' FAILED ********************
Exit Code: 1
Command Output (stdout):
--
# RUN: at line 1
c:\ws\src\build\bin\clang.exe -cc1 -internal-isystem C:\ws\src\build\lib\clang\19\include -nostdsysteminc C:\ws\src\clang\test\AST\attr-print-emit.cpp -ast-print | c:\ws\src\build\bin\filecheck.exe C:\ws\src\clang\test\AST\attr-print-emit.cpp
# executed command: 'c:\ws\src\build\bin\clang.exe' -cc1 -internal-isystem 'C:\ws\src\build\lib\clang\19\include' -nostdsysteminc 'C:\ws\src\clang\test\AST\attr-print-emit.cpp' -ast-print
# note: command had no output on stdout or stderr
# executed command: 'c:\ws\src\build\bin\filecheck.exe' 'C:\ws\src\clang\test\AST\attr-print-emit.cpp'
# .---command stderr------------
# | C:\ws\src\clang\test\AST\attr-print-emit.cpp:35:11: error: CHECK: expected string not found in input
# | // CHECK: void ownr(int) __attribute__((ownership_returns(foo, 1)));
# |           ^
# | <stdin>:11:69: note: scanning from here
# | void ownh(int *, int *) __attribute__((ownership_holds(foo, 1, 2)));
# |                                                                     ^
# | <stdin>:12:1: note: possible intended match here
# | void *ownr(int) __attribute__((ownership_returns(foo, 1)));
# | ^
# |
# | Input file: <stdin>
# | Check file: C:\ws\src\clang\test\AST\attr-print-emit.cpp
# |
# | -dump-input=help explains the following input dump.
# |
# | Input was:
# | <<<<<<
# |             .
# |             .
# |             .
# |             6: void fmt(int, const char *, ...) __attribute__((format(printf, 2, 3)));
# |             7: char *fmta(int, const char *) __attribute__((format_arg(2)));
# |             8: void nn(int *, int *) __attribute__((nonnull(1, 2)));
# |             9: int *aa(int i) __attribute__((alloc_align(1)));
# |            10: void ownt(int *, int *) __attribute__((ownership_takes(foo, 1, 2)));
# |            11: void ownh(int *, int *) __attribute__((ownership_holds(foo, 1, 2)));
# | check:35'0                                                                         X error: no match found
# |            12: void *ownr(int) __attribute__((ownership_returns(foo, 1)));
# | check:35'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# | check:35'1     ?                                                            possible intended match
# |            13: void awtt(int, int, ...) __attribute__((argument_with_type_tag(foo, 3, 2)));
# | check:35'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            14: void pwtt(void *, int) __attribute__((pointer_with_type_tag(foo, 1, 2)));
# | check:35'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            15: class C {
# | check:35'0     ~~~~~~~~~~
# |            16:  void xla(int a) __attribute__((xray_log_args(2)));
# | check:35'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |            17:  void *as2(int, int) __attribute__((alloc_size(2, 3)));
# | check:35'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# |             .
# |             .
# |             .
# | >>>>>>
# `-----------------------------
# error: command failed with exit status: 1
--
********************
```

**Comment by pskrgag** [comment]
Fixed test and applied suggestions. Thank you for review!

**Comment by Xazax-hun** [comment]
This looks good to me as far as the current use/behavior is concerned. That being said, I think these annotations make sense to some non-pointer types as well, e.g., integer handles to other system resources. I did not find any test/functionality for this scenario, so I am OK with this change for now, but this is something that we want to refine if new functionality is introduced in the future.

**Comment by pskrgag** [comment]
I think, it would be even better to drop second argument for `ownership_returns`, since it mirrors the behavior of `alloc_size`. And also allow any return type.

But I am not sure if it's possible to make such change directly. Maybe we should start with deprecation for couple of releases and eventually come to scheme where `ownership_*` annotates classes of resources, while `alloc_size` annotates only memory allocations. And users will be able to combine them as they like.

If this sounds sane, I will fill up an issue.

**Comment by pskrgag** [comment]
Rebased on top of 2ce865d4905970c07477a9c4e37159664a785c81

**Review by steakhal — APPROVED** [review]
LGTM, thanks.

**Comment by pskrgag** [comment]
@AaronBallman sorry for Saturday ping, but could you, please, take a look?

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -231,6 +231,10 @@ Crash and bug fixes
 Improvements
 ^^^^^^^^^^^^
 
+- Improved the handling of the `ownership_returns` attribute. Now, Clang reports an
+  error if the attribute is attached to a function that returns a non-pointer value.
```
Comment (AaronBallman) [inline clang/docs/ReleaseNotes.rst:235]:
```suggestion
- Improved the handling of the ``ownership_returns`` attribute. Now, Clang reports an
  error if the attribute is attached to a function that returns a non-pointer value.
```

File: clang/include/clang/Basic/DiagnosticSemaKinds.td [hunk 4]
```diff
@@ -3330,6 +3330,8 @@ def err_attribute_invalid_implicit_this_argument : Error<
   "%0 attribute is invalid for the implicit this argument">;
 def err_ownership_type : Error<
   "%0 attribute only applies to %select{pointer|integer}1 arguments">;
+def err_ownership_takes_return_type : Error<
+  "'ownership_returns' attribute only applies to functions that return pointers">;
```
Comment (AaronBallman) [inline clang/include/clang/Basic/DiagnosticSemaKinds.td:3334]:
```suggestion
  "'ownership_returns' attribute only applies to functions that return a pointer">;
```

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 5]
```diff
@@ -1481,6 +1481,15 @@ static void handleOwnershipAttr(Sema &S, Decl *D, const ParsedAttr &AL) {
...
   }
 
+  // Allow only pointers to be return type for functions with ownership_returns
+  // attribute. This matches with current OwnershipAttr::Takes semantics
+  if (K == OwnershipAttr::Returns) {
+    if (!getFunctionOrMethodResultType(D)->isPointerType()) {
+      S.Diag(AL.getLoc(), diag::err_ownership_takes_return_type) << AL;
+      return;
+    }
+  }
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclAttr.cpp:1491]:
```suggestion
  if (K == OwnershipAttr::Returns && 
     !getFunctionOrMethodResultType(D)->isPointerType()) {
    S.Diag(AL.getLoc(), diag::err_ownership_takes_return_type) << AL;
    return;
  }
```
(combining the two predicates, may need reformatting.)

**Review by AaronBallman — COMMENTED** [review]
Just a few minor nits, otherwise LGTM

**Comment by pskrgag** [comment]
Applied style and spelling fixes, thank you for review!

**Review by Sirraide — APPROVED** [review]
