### PR TITLE
[X86] Elect to tail call when `sret` ptr is passed to the callee

### LINKED ISSUE #146303: missing tail call optimization on RVO
```c++
struct Slice {
    const char* data;
    unsigned long size;
    ~Slice();
};
Slice get_s_impl();
Slice get_s() { return get_s_impl(); }
```
clang produces:
```asm
get_s():
        push    rbx
        mov     rbx, rdi
        call    get_s_impl()
        mov     rax, rbx
        pop     rbx
        ret
```
icc recognized tail call and produces:
```asm
get_s():
..B1.1:                         # Preds ..B1.0
        jmp       get_s_impl()                               #7.24
```
g++ also missed such tail call optimization.

If delete `~Slice;`, g++ & clang recognize the tail call, but icc fails.

### PR DESCRIPTION
**Pull request by antoniofrighetto**
We may be able to allow the callee to be tail-called when the caller expects a `sret` pointer argument, as long as this pointer is forwarded to the callee.

Fixes: https://github.com/llvm/llvm-project/issues/146303.

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 1]
```diff
@@ -2824,14 +2825,33 @@ bool X86TargetLowering::IsEligibleForTailCallOptimization(
...
-  // insufficient.
-  if (MF.getInfo<X86MachineFunctionInfo>()->getSRetReturnReg()) {
+  // Avoid sibcall optimization if we are an sret return function and the callee
+  // is incompatible, unless these premises are proven wrong.
+  if (Register SRetReg = FuncInfo->getSRetReturnReg()) {
     // For a compatible tail call the callee must return our sret pointer. So it
     // needs to be (a) an sret function itself and (b) we pass our sret as its
-    // sret. Condition #b is harder to determine.
-    return false;
+    // sret. We know the caller has a sret ptr argument (SRetReg). Now locate
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: Please move this logic to a helper function and keep the comment as it was so that the TCO eligibility check remains easy to read. The original comment captures the properties we're looking for well.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 2]
```diff
@@ -2824,14 +2825,33 @@ bool X86TargetLowering::IsEligibleForTailCallOptimization(
...
+    // the operand index within the callee which has a sret ptr as well.
+    auto It = find_if(Outs, [](const auto &OA) { return OA.Flags.isSRet(); });
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: Given the need for an index from `distance`, I would just use the indexed for loop search to make this more readable.

File: llvm/test/CodeGen/X86/sibcall.ll [hunk 3]
```diff
@@ -725,27 +662,17 @@ define fastcc void @t21_sret_to_sret_more_args2(ptr noalias sret(%struct.foo) %a
...
-; X32-NEXT:    pushq %rbx
 ; X32-NEXT:    movl %esi, %eax
-; X32-NEXT:    movq %rdi, %rbx
 ; X32-NEXT:    movl %edx, %esi
 ; X32-NEXT:    movl %eax, %edx
-; X32-NEXT:    callq f_sret@PLT
-; X32-NEXT:    movl %ebx, %eax
-; X32-NEXT:    popq %rbx
-; X32-NEXT:    retq
+; X32-NEXT:    jmp f_sret@PLT # TAILCALL
```
Comment (rnk) [inline llvm/test/CodeGen/X86/sibcall.ll:675]: Please add new whitebox test cases that try to fool your heuristic. The C code that comes to mind for me looks like:
```
typedef struct SRet {
  long x, y, z;
} SRet;
SRet foo();
SRet bar(SRet *p) {
  SRet r = {0, 0, 0};
  *p = foo();
  return r;
}
```

The call to `foo` could end up in the tail position, but the implicit sret arg is not forwarded to `foo` here.

**Review by rnk — CHANGES_REQUESTED** [review]
Thanks, the test cases suggest that this would be a major improvement.

File: llvm/test/CodeGen/X86/sibcall.ll (hunk 3 above)
Comment (antoniofrighetto) [reply llvm/test/CodeGen/X86/sibcall.ll:675]: Added this one, and variants thereof, thanks (this was one above was already restrained by these lines:
https://github.com/llvm/llvm-project/blob/220a00239696257a02fe625a4819fcd038e9dd07/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L8905-L8909
).

**Review by rnk — APPROVED** [review]
Looks good! Sorry for the delay, I went on summer vacation.
