### PR TITLE
[LV] Remove assertions in IV overflow check

### LINKED ISSUE #115755: [RISCV][LV] LoopVectorize crashed with assertion failure when enabling EVL vectorization
The EVL LoopVectorizer currently crashes on multiple SPEC2006INT benchmarks with the same assertion failures:
```
lib/Transforms/Vectorize/LoopVectorize.cpp:2501: void llvm::InnerLoopVectorizer::emitIterationCountCheck(BasicBlock *): Assertion `!isIndvarOverflowCheckKnownFalse(Cost, VF * UF) && !SE.isKnownPredicate(CmpInst::getInversePredicate(ICmpInst::ICMP_ULT), TC2OverflowSCEV, SE.getSCEV(Step)) && "unexpectedly proved overflow check to be known"' failed.
```

Here is a reproducer from 401.bzip2:
``` llvm
; ModuleID = 'reduced.bc'
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

; Function Attrs: vscale_range(2,2)
define i32 @BZ2_decompress(ptr %s, i32 %0) #0 {
entry:
  br label %for.cond1443

for.cond1443:                                     ; preds = %for.body1447, %entry
  %v1442.08 = phi i8 [ %inc1451, %for.body1447 ], [ 0, %entry ]
  %conv1444 = zext i8 %v1442.08 to i32
  %cmp1445 = icmp sgt i32 %0, %conv1444
  br i1 %cmp1445, label %for.body1447, label %while.cond1462

for.body1447:                                     ; preds = %for.cond1443
  store i8 0, ptr %s, align 1
  %inc1451 = add i8 %v1442.08, 1
  br label %for.cond1443

while.cond1462:                                   ; preds = %while.cond1462, %for.cond1443
  br label %while.cond1462
}

attributes #0 = { vscale_range(2,2) }
```
And here is the reproducing command:
```
opt -mcpu=sifive-p670 -O3 -prefer-predicate-over-epilogue=predicate-dont-vectorize input.ll
```

### PR DESCRIPTION
**Pull request by lukel97**
In #111310 an assert was added that for the IV overflow check used with tail folding, the overflow check is never known.

However when applying the loop guards, it looks like it's possible that we might actually know the IV won't overflow: this occurs in 500.perlbench_r from SPEC CPU 2017 and triggers the assertion:

    Assertion failed: (!isIndvarOverflowCheckKnownFalse(Cost, VF * UF) && !SE.isKnownPredicate(CmpInst::getInversePredicate(ICmpInst::ICMP_ULT), TC2OverflowSCEV, SE.getSCEV(Step)) && "unexpectedly proved overflow check to be known"), function emitIterationCountCheck, file LoopVectorize.cpp, line 2501.

There is a discrepancy between `isIndvarOverflowCheckKnownFalse` and the ICMP_ULT check, because the former uses `getSmallConstantMaxTripCount` which only takes into trip counts that fit into 32 bits. There doesn't seem to be an easy way to make the assertion aware of this, so this PR just removes it for now.

There are two potential follow up things from this PR:

1. We miss calculating the max trip count in `@trip_count_max_1024`, it looks like we might need to apply loop guards somewhere in `ScalarEvolution::computeExitLimitFromICmp`
2. In `@overflow_at_0`, if `%tc == 0` then we the overflow check will always return false, even though it will overflow

Fixes https://github.com/llvm/llvm-project/issues/115755

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 1]
```diff
@@ -2491,17 +2491,19 @@ void InnerLoopVectorizer::emitIterationCountCheck(BasicBlock *Bypass) {
...
-        !SE.isKnownPredicate(CmpInst::getInversePredicate(ICmpInst::ICMP_ULT),
-                             TC2OverflowSCEV, SE.getSCEV(Step)) &&
-        "unexpectedly proved overflow check to be known");
-#endif
-    // Don't execute the vector loop if (UMax - n) < (VF * UF).
-    CheckMinIters = Builder.CreateICmp(ICmpInst::ICMP_ULT, LHS, Step);
+    const SCEV *StepSCEV = SE.getSCEV(Step);
+
+    // Check if (UMax - n) < (VF * UF).
+    if (SE.isKnownPredicate(ICmpInst::ICMP_ULT, TC2OverflowSCEV, StepSCEV)) {
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2499]: The patch to add the NDEBUG code landed only recently - https://github.com/llvm/llvm-project/pull/111310 by @fhahn. It looks like this assert was added for a reason - is it possible that `isIndvarOverflowCheckKnownFalse` is returning the incorrect answer for the EVL case?

File: llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-known-no-overflow.ll [hunk 2]
```diff
@@ -0,0 +1,85 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -passes=loop-vectorize \
+; RUN: -force-tail-folding-style=data-with-evl \
+; RUN: -prefer-predicate-over-epilogue=predicate-dont-vectorize \
+; RUN: -mtriple=riscv64 -mattr=+v -S < %s | FileCheck %s
+
+; If we know the IV will never overflow then we can skip the IV overflow check
+
+define void @f(ptr %p, i64 %tc) vscale_range(2, 1024) {
```
Comment (david-arm) [inline llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-known-no-overflow.ll:9]: I think it would be helpful if the test was added in a different commit so we can see the changes.

Comment (lukel97) [reply llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-known-no-overflow.ll:9]: This crashes without the assertion removed unfortunately. I could split this into two patches to remove the assert first, and then a second one that shows the change in the overflow check?

Comment (fhahn) [reply llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-known-no-overflow.ll:9]: It should be possible to prefix the run line with ` not --crash `, the test would also need to require asserts.

Comment (david-arm) [reply llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-known-no-overflow.ll:9]: Ah sorry, I was being silly and forgetting that the test crashed before! I was thinking it would be nice to see the effect of the code change, but that's not possible. In that case I personally don't need to see the test before because it won't be very interesting!

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 1 above)
Comment (david-arm) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2499]: Ah this is interesting and thanks for explaining and putting up a fix! So the test you've added shows `isIndvarOverflowCheckKnownFalse` is returning the wrong answer, or at least an answer that's inconsistent with the `SE.isKnownPredicate` call. Once we've applied the loop guards we know that the check is false. So it looks like there are a few choices:

1. In the assert above we could avoid applying the loop guards and then `isIndvarOverflowCheckKnownFalse` will be consistent with the call to `SE.isKnownPredicate`. That might be a much smaller change than this patch I think? Or,
2. Teach `isIndvarOverflowCheckKnownFalse` to apply loop guards, which I think would require changing ScalarEvolution::getSmallConstantMaxTripCount to apply loop guards. It looks like `ScalarEvolution::getSmallConstantTripMultiple` already does something similar. Or,
3. Use the current version of your patch.

The only problem with 3 is that the code is now more complex and it doesn't look like there are any tests for the `CheckMinIters = Builder.getTrue();` case you've added.

I personally feel like 2 is the most powerful change because you've highlighted a problem in how we estimate the small constant max trip count. If the vectoriser is always going to apply loop guards anyway, then we should do the same when estimating the trip count. However, I realise it would expand the scope of this patch quite a bit and I perfectly understand if you don't have time to do this right now! What do you think?

Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2499]: This is an interesting case. For the loop in the test case, the induction can  overflow if `%tc == 0` I think, so `isIndvarOverflowCheckKnownFalse` should return false in general?

I think `getSmallConstantMaxTripCount` already should make use of loop guards in this case, but we cannot compute a tighter maximum because `%tc` may be 0, in which case we would wrap.

Comment (lukel97) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2499]: Thanks for the review and pointers! 2 seems good to me too, I'm happy to give it a stab.

> This is an interesting case. For the loop in the test case, the induction can overflow if `%tc == 0` I think, so `isIndvarOverflowCheckKnownFalse` should return false in general?

Oh woops, I think the exit condition in the test case should have been `icmp uge`. 

But if we did emit the overflow check would it even have caught it at runtime? If `%tc == 0` then I think `(UMax - %tc) < (VF * UF)` will always return false.

**Comment by lukel97** [comment]
As a side note, on RISC-V vscale always has to be a power of 2 so I think we might always be able to elide the overflow check. But I'm not sure if we have any way of expressing that constraint on vscale currently.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 1 above)
Comment (lukel97) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: I took a look at teaching `isIndvarOverflowCheckKnownFalse` but as @fhahn said I think it's already doing the correct thing. `getConstantMaxBackedgeTakenCount` was returning 0xFFFFFFFFFFFFFFFF due to the overflow case at `%tc == 0`. But `getConstantTripCount` throws it away because it only considers trip counts that fit into 32 bits. 

The SCEV assertion uses the full 64 bits of the TC type though, and in combination with what I think is a separate coincidental issue that `(UMax - %tc) < (VF * UF)` when `%tc == 0` means, it means that the predicate is always true.

I couldn't think of an easy way of updating the assertion, so I've reworked this PR to just remove the assert and nothing else for now.

I've added some new cases to show things that I think could be split off from this PR:

- `@overflow_at_0` shows how the overflow check seems to let `%tc == 0` slip through, which maybe is something that needs fixed in a separate PR?
- `@no_overflow_at_0` shows a case where `isIndvarOverflowCheckKnownFalse` works and knows that the maximum trip count is 1025, so nothing needs to be done here
- `@trip_count_max_1024` shows a case where we currently can't calculate the max trip count, i.e. the debug output doesn't contain:`LV: Found maximum trip count: N`, and so `isIndvarOverflowCheckKnownFalse` also returns false. I think in a separate PR we can teach `computeMaxBECountForLT` to apply the loop guards, which seems to fix this.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 3]
```diff
@@ -2491,15 +2491,6 @@ void InnerLoopVectorizer::emitIterationCountCheck(BasicBlock *Bypass) {
...
-    ScalarEvolution &SE = *PSE.getSE();
-    const SCEV *TC2OverflowSCEV = SE.applyLoopGuards(SE.getSCEV(LHS), OrigLoop);
-    assert(
-        !isIndvarOverflowCheckKnownFalse(Cost, VF * UF) &&
-        !SE.isKnownPredicate(CmpInst::getInversePredicate(ICmpInst::ICMP_ULT),
-                             TC2OverflowSCEV, SE.getSCEV(Step)) &&
-        "unexpectedly proved overflow check to be known");
-#endif
     // Don't execute the vector loop if (UMax - n) < (VF * UF).
     CheckMinIters = Builder.CreateICmp(ICmpInst::ICMP_ULT, LHS, Step);
```
Comment (fhahn) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2495]:
```suggestion
    CheckMinIters = Builder.CreateICmp(ICmpInst::ICMP_ULT, LHS, CreateStep());
```

**Review by fhahn — APPROVED** [review]
LGTM, IIUC this is genuine case where isIndvarOverflowCheckKnownFalse has to return false, but we can get better results after committing to a concrete tail-folding decisions.

Could you check if this fixes https://github.com/llvm/llvm-project/issues/115755 and add `Fixes https://github.com/llvm/llvm-project/issues/115755` to the PR description?

**Comment by lukel97** [comment]
> Could you check if this fixes #115755 and add `Fixes https://github.com/llvm/llvm-project/issues/115755` to the PR description?

It indeed fixes it, I've updated the PR description
