### PR TITLE
[libc++] Fix assignment in insertion into `vector`

### LINKED ISSUE #47963: Allow std::vector::insert to compile when elements have a deleted copy assignment operator
|  |  |
| --- | --- |
| Bugzilla Link | [48619](https://llvm.org/bz48619) |
| Version | unspecified |
| OS | All |
| CC | @iboB,@dwblaikie,@mclow |

## Extended Description 
Create a class `X` which is copy-constructible but not copy-assignable

```cpp
struct X {
    X();
    X(const X&);
    X& operator=(const X&) = delete; // !!
    X(X&&) noexcept;
    X& operator=(X&&) noexcept;
    int data = 54;
};
```

Have vectors of `X` `a` and `b`. Try to add all elements of `b` at the front of `a`:

```cpp
void add_to_front(std::vector<X>& a, const std::vector<X>& b) {
    a.insert(a.begin(), b.begin(), b.end());
}
```

Live demo: https://godbolt.org/z/K1WT8n

It doesn't compile. My guess is that code which will never get invoked, still needs to compile (or, worse yet, copy assignment does get invoked?!)

The only way to achieve the desired behavior efficiently is to use a custom vector implementation. There is a stackoverflow question which has some *worse* workarounds: https://stackoverflow.com/questions/65489039/how-to-efficiently-insert-multiple-copy-constructible-but-not-copy-assignable-el

This does compile and work on msvc, so a compile-time check for the copy-assignment code is possible.

### LINKED ISSUE #115727: [libcxx]: `__uninitialized_allocator_copy` misses `std::move` before calling `__unwrap_range`
https://github.com/llvm/llvm-project/blob/4c4db3c943d686ff7c1fcf2dbc975e8462497efe/libcxx/include/__memory/uninitialized_algorithms.h#L585-L592

testcase:
```cpp
#include <sstream>
#include <vector>
#include <ranges>
 
int main() {
  auto is = std::istringstream{"1 2 3 4"};
  auto ints = std::views::istream<int>(is);
  std::vector v(std::from_range, std::views::counted(ints.begin(), 3));
}
```
https://godbolt.org/z/rjWeqdPj1

### LINKED ISSUE #115801: [libc++] `vector::insert_range` should not use `std::copy`
https://github.com/llvm/llvm-project/blob/de2fad32513f7420988df1cf99aff90e0a067469/libcxx/include/__vector/vector.h#L1317

Unlike `assign_range` which requires `assignable_from<T&, ranges​::​range_reference_t<R>>` , this means that `std::copy` is not necessarily well-formed for `insert_range`:

```cpp
#include <vector>

struct Int {
  void operator=(int) = delete;
  Int(int);
};

int main() {
  std::vector<Int> v;
  v.insert_range(v.begin(), std::vector{42});
}
```

https://godbolt.org/z/jo3vjjo5b

Additionally, range-version APIs should not dispatch to the `std::moew` algorithm which only works with C++98 iterators.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Changes:
- Avoid direct assignment in iterator-pair `insert` overload and `insert_range`, except when the assignment is move assignment.

Fixes #47963. Fixes #115801.

### CODE REVIEW

**Comment by philnik777** [comment]
Please split adding `std::move` from any algorithm changes.

**Comment by frederick-vs-ja** [comment]
> Please split adding `std::move` from any algorithm changes.

I think I should split out the handling for input-only iterators, which is more than adding `std::move`.

**Comment by philnik777** [comment]
> > Please split adding `std::move` from any algorithm changes.
> 
> I think I should split out the handling for input-only iterators, which is more than adding `std::move`.

Sure. Which way you split is up to you. I only care that it is split.

**Comment by frederick-vs-ja** [comment]
> > > Please split adding `std::move` from any algorithm changes.
> > 
> > 
> > I think I should split out the handling for input-only iterators, which is more than adding `std::move`.
> 
> Sure. Which way you split is up to you. I only care that it is split.

Split to #116157. I sadly realized why I placed the changes in one PR - `__insert_with_size` needs to be fixed in both directions, and the changes are far from orthogonal.

**Comment by winner245** [comment]
Could you please rebase this PR onto main? Since the split part (#116157) has already been merged, combining them now would ease the review process for this one. Thank you!

File: libcxx/include/__vector/vector.h [hunk 1]
```diff
@@ -594,6 +598,30 @@ class _LIBCPP_TEMPLATE_VIS vector {
   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void
   __assign_with_size(_ForwardIterator __first, _Sentinel __last, difference_type __n);
 
+  template <class _Iterator,
+            __enable_if_t<!is_same<decltype(*std::declval<_Iterator&>())&&, value_type&&>::value, int> = 0>
+  _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void
+  __insert_assign_n_unchecked(_Iterator __first, difference_type __n, pointer __position) {
+    for (pointer __end_position = __position + __n; __position != __end_position; (void)++__position, ++__first) {
```
Comment (winner245) [inline libcxx/include/__vector/vector.h:605]:
```suggestion
    for (pointer __end_position = __position + __n; __position != __end_position; ++__position, (void)++__first) {
```

I think it is more appropriate to guard against `operator,` here.

Comment (frederick-vs-ja) [reply libcxx/include/__vector/vector.h]: Thanks! Although I believe the effects are exactly same.

It's conventional to `void`-cast the first operand in the standard wording. But in libc++ `void`-casting the second one seems conventional. What an unfortunate style mismatch.

File: libcxx/include/__vector/vector.h [hunk 2]
```diff
@@ -602,6 +603,30 @@ class _LIBCPP_TEMPLATE_VIS vector {
...
+      *__position = std::move(__tmp.get());
+    }
+  }
+
+  template <class _Iterator,
+            __enable_if_t<is_same<decltype(*std::declval<_Iterator&>())&&, value_type&&>::value, int> = 0>
+  _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void
+  __insert_assign_n_unchecked(_Iterator __first, difference_type __n, pointer __position) {
+#if _LIBCPP_STD_VER >= 23
+    if constexpr (!forward_iterator<_Iterator>) {
```
Comment (winner245) [inline libcxx/include/__vector/vector.h:621]:
```suggestion
    if constexpr (!forward_iterator<_Iterator>) { // Handles input-only sized ranges for insert_range
```

File: libcxx/test/std/containers/sequences/vector/vector.modifiers/insert_iter_iter_iter.pass.cpp [hunk 3]
```diff
@@ -161,6 +163,24 @@ TEST_CONSTEXPR_CXX20 bool tests() {
     for (; j < 105; ++j)
       assert(v[j] == 0);
   }
+  {
```
Comment (winner245) [inline libcxx/test/std/containers/sequences/vector/vector.modifiers/insert_iter_iter_iter.pass.cpp:166]:
```suggestion
  { // Ensure that iterator-pair insert() doesn't use unexpected assignment.
```

**Review by winner245 — APPROVED** [review]
LGTM. Thanks for the patch. It ensures that our `insert_range` function, as well as the iterator-pair `insert` function, will not accidentally use copy-assignment. I only have a few minor comments to improve readability.

File: libcxx/include/__vector/vector.h (hunk 2 above)
Comment (frederick-vs-ja) [reply libcxx/include/__vector/vector.h]: Added.
