### PR TITLE
[X86] LowerMINMAX - use valuetracking to attempt to find a smaller type that can efficiently lower min/max ops

### LINKED ISSUE #174169: LLVM fails to optimize out i32/i64 smin/smax down to PMINSW/PMAXSW on x86 with SSE2 when values are known to be within i16 range
`@llvm.smin.v4i32(%a, %b)` and `@llvm.smin.v2i64(%a, %b)` can both be optimized to PMINSW (or `@llvm.smin.v8i16`) on x86 with SSE2 if the values in each lane of both `%a` and `%b` are known to be either in the [-32768, 32767] range, undef, or poison.

Likewise, `@llvm.smax.v4i32(%a, %b)` and `@llvm.smax.v2i64(%a, %b)` can both be optimized to PMAXSW (or `@llvm.smax.v8i16`) on x86 with SSE2 if the values in each lane of both `%a` and `%b` are known to be either in the [-32768, 32767] range, undef, or poison.

Here is a link to a snippet that demonstrates the validity of this transformation to PMINSW/PMAXSW if the values of each lane of `%a` and `%b` are known to be either in the [-32768, 32767] range, undef, or poison:
https://alive2.llvm.org/ce/z/py_J9L

The failure to vectorize int16_t[8] min to pminsw pattern was reported in issue #48223 raised back in 2021.

### PR DESCRIPTION
**Pull request by RKSimon**
We currently use the generic expansions to custom lower integer min/max instructions, but if we have sufficient leading bits, SSE/AVX is always better off handling it directly with smaller types.

vXi64 cmp/min/max is particularly weak, and as we narrow the types the better legality we have - this approach seems to work well for x86, but I'm not sure if its valid enough to try generically in this manner.

However, I added the signed/unsigned generic flip fold to expandIntMINMAX to further improve SSE2 codegen, similar to what we already attempt in DAGCombiner (which with a bit more work we might be able to remove now).

All thats missing is better ComputeNumSignBits handling for vXi64 ashr expansion, which still misses a lot of cases when split across vXi32 types and shuffles.

Fixes #174169

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 1]
```diff
@@ -10799,6 +10799,28 @@ SDValue TargetLowering::expandIntMINMAX(SDNode *Node, SelectionDAG &DAG) const {
   unsigned Opcode = Node->getOpcode();
   SDLoc DL(Node);
 
+  // If both sign bits are zero, flip UMIN/UMAX <-> SMIN/SMAX if legal.
```
Comment (phoebewang) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: It seems it also applies to both sign bits are 1?

**Review by phoebewang — APPROVED** [review]
LGTM.
