### PR TITLE
[C23] Fix typeof handling in enum declarations

### LINKED ISSUE #146351: [c23] `typeof(type-name)` in enumeration fixed underlying type is broken
Setting  a `typeof(type-name)` in an enumeration fixed underlying type is broken: an error is raised explaining that the identifiers are not declared, but we're in the process of declaring them. The bug is present in clang 20.1.0. GCC 15.1 doesn't have this bug.

See C23 6.7.3.6.p4 Typeof specifiers

> If the `typeof` operators are applied to an expression, they yield the type of their operand. Otherwise, they designate the same type as the type name with any nested `typeof` specifier evaluated.

Interestingly, `typeof(expression)` isn't broken!

https://gcc.godbolt.org/z/TGWYdhndo

```c
enum e : int {
    E = 0,
};

enum f : typeof(int) {
    F = 0, /* error: use of undeclared identifier 'F' */
};

int g = 0;

enum g : typeof(g) {
    G = 0,
};

int main() {}

```

```
<source>:6:5: error: use of undeclared identifier 'F'
    6 |     F = 0,
      |     ^
1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by AaronBallman**
We have a parsing helper function which parses either a parenthesized expression or a parenthesized type name. This is used when parsing a unary operator such as sizeof, for example.

The problem this solves is when that construct is ambiguous. Consider:

	enum E : typeof(int) { F };

After we've parsed the 'typeof', what ParseParenExpression() is responsible for is '(int) { F }' which looks like a compound literal expression when it's actually the parens and operand for 'typeof' followed by the enumerator list for the enumeration declaration. Then consider:

	sizeof (int){ 0 };

After we've parsed 'sizeof', ParseParenExpression is responsible for parsing something grammatically similar to the problematic case.

The solution is to recognize that the expression form of 'typeof' is required to have parentheses. So we know the open and close parens that ParseParenExpression handles must be part of the grammar production for the operator, not part of the operand expression itself.

Fixes #146351

### CODE REVIEW

File: clang/include/clang/Parse/Parser.h [hunk 1]
```diff
@@ -4210,6 +4215,7 @@ class Parser : public CodeCompletionHandler {
   /// \endverbatim
   ExprResult ParseParenExpression(ParenParseOption &ExprType,
                                   bool stopIfCastExpr, bool isTypeCast,
+                                  bool ParenKnownToBeNonCast,
```
Comment (Sirraide) [inline clang/include/clang/Parse/Parser.h]: I feel like it might be semantically simpler to invert the value of this and call it just `MightBeCast`? Reasoning about the fact that passing `false` here means that ‘it’s *not* known to be a *non*-cast’ is a bit headache-inducing at least for me...

Actually on that note, `TypeCastState` is a thing. Can we just merge this parameter with the `isTypeCast` one and make it a `TypeCastState`?

Comment (yronglin) [reply clang/include/clang/Parse/Parser.h]: How about introducing a new enumeration here?

Comment (AaronBallman) [reply clang/include/clang/Parse/Parser.h]: > Actually on that note, TypeCastState is a thing. Can we just merge this parameter with the isTypeCast one and make it a TypeCastState?

`TypeCastState` is cursed in that it doesn't mean what you might think it means: https://github.com/llvm/llvm-project/commit/77e21fca3cd1a9db882ac13ac5ddef3f278dfff2

So it doesn't mean "this is, is not, or maybe a cast expression", it means "if there's a typo, should we allow type names or not?" I verified this is not vestigial code after delayed typo correction was removed; it's still used for typo correction today. We probably should rename some stuff to make this far more clear though, because your suggestion is what I initially tried to implement and broke approximately every test in the suite.

> How about introducing a new enumeration here?

Given that there's three bools in a row, yeah, that's not a bad idea.

How about this for a solution:

1) Rename `TypeCastState` to `TypoCorrectionTypeBehavior`
2) Rename `NotTypeCast`, `IsTypeCast`, and `MaybeTypeCast` to `AllowNonTypes, `AllowTypes`, and `AllowBoth`
3) Add a new enumeration `TypeCastState` with members `IsTypeCast`, `IsNotTypeCast`, and `Unknown`
4) Change `ParseParenExpression` to take both a `TypoCorrectionTypeBehavior` and a `TypeCastState`.

WDYT?

Comment (yronglin) [reply clang/include/clang/Parse/Parser.h]: This solution looks good!

Comment (Sirraide) [reply clang/include/clang/Parse/Parser.h]: > So it doesn't mean "this is, is not, or maybe a cast expression", it means "if there's a typo, should we allow type names or not?"

Ok, I like to say I’m bad at naming, but that is actually awful. ;Þ

> How about this for a solution:
> 
> 1. Rename `TypeCastState` to `TypoCorrectionTypeBehavior`
> 2. Rename `NotTypeCast`, `IsTypeCast`, and `MaybeTypeCast` to `AllowNonTypes, `AllowTypes`, and `AllowBoth`
> 3. Add a new enumeration `TypeCastState` with members `IsTypeCast`, `IsNotTypeCast`, and `Unknown`
> 4. Change `ParseParenExpression` to take both a `TypoCorrectionTypeBehavior` and a `TypeCastState`.

I was about to suggest this so sgtm

Comment (AaronBallman) [reply clang/include/clang/Parse/Parser.h]: I ended up picking different names for `TypeCastState` because that was still confusing.

File: clang/lib/Parse/ParseExpr.cpp [hunk 2]
```diff
@@ -2850,7 +2870,8 @@ Parser::ParseParenExpression(ParenParseOption &ExprType, bool stopIfCastExpr,
              isFoldOperator(NextToken().getKind())) {
     ExprType = ParenParseOption::FoldExpr;
     return ParseFoldExpression(ExprResult(), T);
-  } else if (isTypeCast) {
+  } else if (CorrectionBehavior == TypoCorrectionTypeBehavior::AllowTypes) {
+    // FIXME: This should not be predicated on typo correction behavior.
```
Comment (AaronBallman) [inline clang/lib/Parse/ParseExpr.cpp:2873]: This is worth noting!

This was an unfortunate surprise. However, it's a preexisting defect that I don't have the bandwidth to correct right now.

The old `TypeCastState` enumeration was introduced to help with typo correction (https://github.com/llvm/llvm-project/commit/77e21fca3cd1a9db882ac13ac5ddef3f278dfff2) and we accidentally ended up using it for parsing decisions: https://github.com/llvm/llvm-project/blob/a63f57262898588b576d66e5fd79c0aa64b35f2d/clang/lib/Parse/ParseExpr.cpp#L761

File: clang/lib/Parse/ParseExpr.cpp [hunk 3]
```diff
@@ -1000,8 +1001,10 @@ ExprResult Parser::ParseCastExpression(CastParseKind ParseKind,
     Token Replacement;
     CastExpressionIdValidator Validator(
         /*Next=*/Tok,
-        /*AllowTypes=*/isTypeCast != TypeCastState::NotTypeCast,
-        /*AllowNonTypes=*/isTypeCast != TypeCastState::IsTypeCast);
+        /*AllowTypes=*/CorrectionBehavior !=
+            TypoCorrectionTypeBehavior::AllowNonTypes,
+        /*AllowNonTypes=*/CorrectionBehavior !=
+            TypoCorrectionTypeBehavior::AllowTypes);
     Validator.IsAddressOfOperand = isAddressOfOperand;
```
Comment (Sirraide) [inline clang/lib/Parse/ParseExpr.cpp:1007]: I feel like at this point the `CastExpressionIdValidator` should just store the `TypoCorrectionTypeBehavior` instead of splitting it into two flags—or am I missing something here?

File: clang/lib/Parse/ParseExpr.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/Parse/ParseExpr.cpp:2873]: Not surprised that that happened given the name of the enum...

**Review by Sirraide — COMMENTED** [review]
One more thing I thought of: What about C++ edge cases, e.g. both Clang and GCC accept this... which doesn’t quite seem right to me (https://godbolt.org/z/K58eEvG9P):
```c++
typeof(int){} x; // Probably parsed as typeof(int{})
```

**Comment by Sirraide** [comment]
> ```c++
> typeof(int){} x; // Probably parsed as typeof(int{})
> ```

Actually, I’m not sure what we think this is supposed to be; I haven’t checked.

**Comment by Sirraide** [comment]
> > ```c++
> > typeof(int){} x; // Probably parsed as typeof(int{})
> > ```
> 
> Actually, I’m not sure what we think this is supposed to be; I haven’t checked.

Actually, that’s just a compound literal; I forgot we supported those in C++.

**Comment by AaronBallman** [comment]
> > > ```c++
> > > typeof(int){} x; // Probably parsed as typeof(int{})
> > > ```
> > 
> > 
> > Actually, I’m not sure what we think this is supposed to be; I haven’t checked.
> 
> Actually, that’s just a compound literal; I forgot we supported those in C++.

It's a reallllly funky compound literal though, so worth explaining for others:

That's `(int){}` as a compound literal expression, which is the expression operand to an unparenthesized `typeof` operator, which yields the type `int` for the declaration of `x`.

**Review by yronglin — APPROVED** [review]
Thanks, LGTM!

**Comment by AaronBallman** [comment]
Windows failures are unrelated, they're a CI issue tracked by https://github.com/llvm/llvm-project/issues/145703

**Comment by AaronBallman** [comment]
> > > > ```c++
> > > > typeof(int){} x; // Probably parsed as typeof(int{})
> > > > ```
> > > 
> > > 
> > > Actually, I’m not sure what we think this is supposed to be; I haven’t checked.
> > 
> > 
> > Actually, that’s just a compound literal; I forgot we supported those in C++.
> 
> It's a reallllly funky compound literal though, so worth explaining for others:
> 
> That's `(int){}` as a compound literal expression, which is the expression operand to an unparenthesized `typeof` operator, which yields the type `int` for the declaration of `x`.

Nope, I'm wrong.

`typeof` requires the parens. That should be ill-formed.

I'll investigate.

**Comment by yronglin** [comment]
> ```c++
> typeof(int){} x; // Probably parsed as typeof(int{})
> ```

GCC reject this https://godbolt.org/z/YEdnGh8T5

**Comment by Sirraide** [comment]
> > ```c++
> > typeof(int){} x; // Probably parsed as typeof(int{})
> > ```
> 
> GCC reject this https://godbolt.org/z/YEdnGh8T5

GCC rejects it in C mode; it accepts it in C++ mode.

**Comment by AaronBallman** [comment]
> > ```c++
> > typeof(int){} x; // Probably parsed as typeof(int{})
> > ```
> 
> GCC reject this https://godbolt.org/z/YEdnGh8T5

Yeah, I think there are a few different issues. 1) we should not accept in C. 2) C++ has its own issue in that we accept `typeof` there despite that not being conforming: https://godbolt.org/z/9s7r67zvT

**Comment by Sirraide** [comment]
Since we’re on to C++ support now, here’s one more fun case:
```c++
class A {}; A a;
class B : typeof(A) {};
class C : typeof(a) {};
```

**Comment by AaronBallman** [comment]
> > > ```c++
> > > typeof(int){} x; // Probably parsed as typeof(int{})
> > > ```
> > 
> > 
> > GCC reject this https://godbolt.org/z/YEdnGh8T5
> 
> Yeah, I think there are a few different issues. 1) we should not accept in C. 2) C++ has its own issue in that we accept `typeof` there despite that not being conforming: https://godbolt.org/z/9s7r67zvT

Oh, derp, and we don't accept in C *because of this PR*, I have a test case for that. :-D

**Comment by AaronBallman** [comment]
> Since we’re on to C++ support now, here’s one more fun case:
> 
> ```c++
> class A {}; A a;
> class B : typeof(A) {};
> class C : typeof(a) {};
> ```

Good test cases, but let's handle C++ separately to keep the patch reasonable?

**Comment by Sirraide** [comment]
> let's handle C++ separately to keep the patch reasonable?

~~What about Objective-C then?~~

```c
void f() {
    ^ typeof((void)0) {}; // Ok
    ^ typeof(void) {};    // Error but should probably be ok
}
```

But yeah, doing all of that in this pr might be too much—unless the changes you’ve already made happen to already fix these cases.

**Comment by AaronBallman** [comment]
> > let's handle C++ separately to keep the patch reasonable?
> 
> ~What about Objective-C then?~
> 
> ```c
> void f() {
>     ^ typeof((void)0) {}; // Ok
>     ^ typeof(void) {};    // Error but should probably be ok
> }
> ```
> 
> But yeah, doing all of that in this pr might be too much—unless the changes you’ve already made happen to already fix these cases.

C++ cases are not changed by this patch, but the Objective-C ones are:
```
F:\source\llvm-project>llvm\out\build\x64-Debug\bin\clang.exe -cc1 -fsyntax-only -fblocks -x objective-c "C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp"
C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp:2:5: warning: expression result unused [-Wunused-value]
    2 |     ^ typeof((void)0) {}; // Ok
      |     ^~~~~~~~~~~~~~~~~~~~
C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp:3:5: warning: expression result unused [-Wunused-value]
    3 |     ^ typeof(void) {};    // Error but should probably be ok
      |     ^~~~~~~~~~~~~~~~~
2 warnings generated.
```
So good call on adding test coverage there.

**Review by Sirraide — APPROVED** [review]
LGTM

**Review by yronglin — APPROVED** [review]
LGTM!
