### PR TITLE
[clang-tidy] Add new check bugprone-capture-this-by-field

### LINKED ISSUE #120863: [clang-tidy] Check request: don't capture `this` by a field of default copyable class
Assume the user defined class:
```
struct A {
   std::string content;
   std::function<void()> captured;
   
   A() {
    captured = 
        [this]() { // INCORRECT
            perform();
        };
   }

   void perform() { std::cout << content << std::endl; }
};
```

Since it's copy constructor was generated by the compiler, it's behaviour might be unexpected for some user and even can produce a crash with SIGSEGV:
```
A a;
a.content = "Hello world";
a.captured();

A a1 = a;
a1.content = "Test";
a1.captured(); // will print "Hello world" which might be unexpected
```
```
auto a = std::make_unique<A>();
a->content = "Hello world";
a->captured();

auto b = std::make_unique<A>(*a);
a.reset();
b->content = "Ooooups!";
b->captured(); // UB
```

The way to fix it is to provide manually written copy constructor and assignment operator:
```
A(const A& oth)
    : content(oth.content)
    , captured([this](){perform();}) {}
A& operator=(const A& oth) {
    if (this != &oth) {
        content = oth.content;
        captured = [this](){perform();};
    }
}
```
Making you class noncopyable also protect you from the bug:
```
A(const A& oth) = delete;
A& operator=(const A& oth) = delete;
```

But before you fix it you must discover it in the code, so the clang-tidy check in bugprone section would be nice addition.

### PR DESCRIPTION
**Pull request by HerrCai0907**
Finds lambda captures that capture the ``this`` pointer and store it as class
members without handle the copy and move constructors and the assignments.

Capture this in a lambda and store it as a class member is dangerous because the
lambda can outlive the object it captures. Especially when the object is copied
or moved, the captured ``this`` pointer will be implicitly propagated to the
new object. Most of the time, people will believe that the captured ``this``
pointer points to the new object, which will lead to bugs.

Fixes: #120863

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/BugproneTidyModule.cpp [hunk 1]
```diff
@@ -118,6 +119,8 @@ class BugproneModule : public ClangTidyModule {
     CheckFactories.registerCheck<BoolPointerImplicitConversionCheck>(
         "bugprone-bool-pointer-implicit-conversion");
     CheckFactories.registerCheck<BranchCloneCheck>("bugprone-branch-clone");
+    CheckFactories.registerCheck<CaptureThisByFieldCheck>(
+        "bugprone-capture-this-by-field");
```
Comment (denzor200) [inline clang-tools-extra/clang-tidy/bugprone/BugproneTidyModule.cpp:123]: `bugprone-capturing-this-by-field` ?

File: clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  }
+  // FIXME: find ways to identifier correct handle capture this lambda
+  return true;
+}
+
+} // namespace
+
+void CaptureThisByFieldCheck::registerMatchers(MatchFinder *Finder) {
+  auto IsStdFunctionField =
+      fieldDecl(hasType(cxxRecordDecl(hasName("::std::function"))))
```
Comment (denzor200) [inline clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp:63]: Needs an option to add a custom function class, `boost::function` for example

**Review by denzor200 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+          unless(correctHandleCaptureThisLambda())),
+      this);
+}
+
+void CaptureThisByFieldCheck::check(const MatchFinder::MatchResult &Result) {
+  const auto *Capture = Result.Nodes.getNodeAs<LambdaCapture>("capture");
+  const auto *Lambda = Result.Nodes.getNodeAs<LambdaExpr>("lambda");
+  const auto *Field = Result.Nodes.getNodeAs<FieldDecl>("field");
+  diag(Lambda->getBeginLoc(),
+       "using lambda expressions to capture this and storing it in class "
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp:89]:
```suggestion
       "using lambda expressions to capture 'this' and storing it in class "
```
Consider using ticks for language constructs

File: clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+       "member will cause potential variable lifetime issue when the class "
+       "instance is moved or copied")
+      << Capture->getLocation();
+  diag(Field->getLocation(),
+       "'std::function' that stores captured this and becomes invalid during "
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/CaptureThisByFieldCheck.cpp:94]:
```suggestion
       "'std::function' that stores captured 'this' and becomes invalid during "
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+.. code-block:: c++
+
+  struct C {
+    C() : Captured([this]() -> C const * { return this; }) {}
+    std::function<C const *()> Captured;
+  };
+
+  void foo() {
+    C v1{};
+    C v2 = v1; // v2.Captured capture v1's this pointer
```
Comment (PiotrZSL) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst:25]: Then shouldn't this check be somehow limited only to classes that got move/copy construction enabled ?
And in such case name maybe could be different, like something with dangling this.

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+      this);
+}
+
+void CapturingThisByFieldCheck::check(const MatchFinder::MatchResult &Result) {
+  const auto *Capture = Result.Nodes.getNodeAs<LambdaCapture>("capture");
+  const auto *Lambda = Result.Nodes.getNodeAs<LambdaExpr>("lambda");
+  const auto *Field = Result.Nodes.getNodeAs<FieldDecl>("field");
+  diag(Lambda->getBeginLoc(),
+       "using lambda expressions to capture 'this' and storing it in class "
+       "member will cause potential variable lifetime issue when the class "
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp:104]: if using 'member' here, then maybe better also use 'member' in check name

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+          unless(correctHandleCaptureThisLambda())),
+      this);
+}
+
+void CapturingThisByFieldCheck::check(const MatchFinder::MatchResult &Result) {
+  const auto *Capture = Result.Nodes.getNodeAs<LambdaCapture>("capture");
+  const auto *Lambda = Result.Nodes.getNodeAs<LambdaExpr>("lambda");
+  const auto *Field = Result.Nodes.getNodeAs<FieldDecl>("field");
+  diag(Lambda->getBeginLoc(),
+       "using lambda expressions to capture 'this' and storing it in class "
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp:103]: maybe more like:
`'this' captured by a lambda and stored in a class member; disable implicit class copying/moving to prevent potential use-after-free`

**Review by PiotrZSL — COMMENTED** [review]
Idea is nice.
From functional point of view is ok but check may still require some work to clarify some stuff.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+  DeleteMoveAndCopy(DeleteMoveAndCopy &&) = delete;
+  DeleteMoveAndCopy& operator=(DeleteMoveAndCopy const&) = delete;
+  DeleteMoveAndCopy& operator=(DeleteMoveAndCopy &&) = delete;
+  std::function<void()> Captured;
+};
+
+struct DeleteCopyImplicitDisabledMove {
+  DeleteCopyImplicitDisabledMove() : Captured([this]() { static_cast<void>(this); }) {}
+  DeleteCopyImplicitDisabledMove(DeleteCopyImplicitDisabledMove const&) = delete;
+  DeleteCopyImplicitDisabledMove& operator=(DeleteCopyImplicitDisabledMove const&) = delete;
```
Comment (denzor200) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:47]: this is the C++11 way to make a class noncopyable. Please, provide a test with C++03 way to do it - with usage of "boost::noncopyable"

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+/// For the user-facing documentation see:
+/// http://clang.llvm.org/extra/clang-tidy/checks/bugprone/capturing-this-by-field.html
+class CapturingThisByFieldCheck : public ClangTidyCheck {
+public:
+  CapturingThisByFieldCheck(StringRef Name, ClangTidyContext *Context);
+  void storeOptions(ClangTidyOptions::OptionMap &Opts) override;
+  void registerMatchers(ast_matchers::MatchFinder *Finder) override;
+  void check(const ast_matchers::MatchFinder::MatchResult &Result) override;
+  bool isLanguageVersionSupported(const LangOptions &LangOpts) const override {
+    return LangOpts.CPlusPlus11;
```
Comment (denzor200) [inline clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h:31]: `return LangOpts.CPlusPlus;`

Thats because you registered `boost::function` (which works in earlier C++ standards) as a default function wrapper.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp [hunk 10]
```diff
@@ -0,0 +1,144 @@
+// RUN: %check_clang_tidy -std=c++11-or-later %s bugprone-capturing-this-by-field %t -- -config="{CheckOptions: {bugprone-capturing-this-by-field.FunctionWrapperTypes: '::std::function;::Fn'}}" --
```
Comment (denzor200) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: Could you please provide all the same tests, but for `std::bind` instead of lambda?

Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: something like this:
```
struct Basic {
  Basic() : Captured(std::bind(&Basic::perform, this)) {}
  // CHECK-MESSAGES: :[[@LINE-1]]:22: warning: using bind expressions to capture 'this' and storing it in class member
  void perform() { static_cast<void>(this); }
  std::function<void()> Captured;
  // CHECK-MESSAGES: :[[@LINE-1]]:25: note: 'std::function<void (void)>' that stores captured 'this'
};
```
Bear in mind that there is a lot variants for default bind calls - `std::bind`, `boost::bind`, `std::bind_front`, `std::bind_back`, ...

**Review by denzor200 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst [hunk 11]
```diff
@@ -0,0 +1,37 @@
+.. title:: clang-tidy - bugprone-capturing-this-by-field
+
+bugprone-capturing-this-by-field
```
[the remark this answers is not in the document]
Comment (denzor200) [reply clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst:3]: I'm voting for the first "bugprone-capturing-this-in-field" because we forgot about `std::bind` which is not a C++11 lambda, but has the same problem as lambda

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp [hunk 12]
```diff
@@ -0,0 +1,144 @@
...
+};
+
+} // namespace std
+
+struct Fn {
+  template<class F> Fn(F &&);
+};
+
+struct Basic {
+  Basic() : Captured([this]() { static_cast<void>(this); }) {}
```
Comment (denzor200) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:22]: `[&]` and `[=]` also captures "this", not only `[this]`

**Review by denzor200 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp [hunk 13]
```diff
@@ -0,0 +1,144 @@
+// RUN: %check_clang_tidy -std=c++11-or-later %s bugprone-capturing-this-by-field %t -- -config="{CheckOptions: {bugprone-capturing-this-by-field.FunctionWrapperTypes: '::std::function;::Fn'}}" --
+
```
Comment (denzor200) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:2]: Please add test with a lambda that doen's capture `this`. In order to make sure that no warning will be fired

**Review by denzor200 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 10 above)
Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: Besides C++11 lambda and `std::bind`, there also well-known library [Boost Lambda 2](https://www.boost.org/doc/libs/1_84_0/libs/lambda2/doc/html/lambda2.html). It's also able to capture `this` and then store it inside `std::function`:
```
struct test
{
    int x = 0;
    std::function<bool(int)> fun = x==_1;
};
```
See the full snippet here: https://godbolt.org/z/8W4rrqh1s

Besides Boost Lambda 2 there also [Boost Lambda](https://www.boost.org/doc/libs/1_84_0/doc/html/lambda.html) and [Boost Phoenix](https://www.boost.org/doc/libs/1_84_0/libs/phoenix/doc/html/index.html) and ??? but I never used them and can't say anythind about them.

Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: @PiotrZSL @5chmidti @EugeneZelenko @vbvictor what do you think about lambdas from Boost library? Does it worth to handle in this check, or that lambdas deserve a separate check(maybe even in "boost" module)?

**Review by denzor200 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp (hunk 6 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.cpp:104]: Let us align with field. IMO member also includes member functions. clang's type also use field e.g. `FieldDecl`

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h (hunk 9 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h:31]: lambda expr is introduced in c++11.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst (hunk 11 above)
[the remark this answers is not in the document]
Comment (HerrCai0907) [reply clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst:3]: what do you think `bugprone-capturing-this-in-member-variable`. It is longer then field but IMO may be clearer.
I don't like `bugprone-lambda-capturing-this-to-member` because it put lambda capturing and member on the same level of importance. But here we want to highlight the member variable holding `this` is dangerous.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 10 above)
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: Unfortunately, I am not familiar with boost library and `std::bind`. Maybe I can place FIXME and create new issue to track it.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp [hunk 14]
```diff
@@ -0,0 +1,144 @@
...
+namespace std {
+
+template<class Fn>
+class function;
```
[the remark this answers is not in the document]
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:6]: I think boost::function is already included in self-defined `Fn`.
It should be the same thing.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 8 above)
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:47]: It is impossible to add boost header in lit test. I will add more test about `Inherit`

Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:52]: We don't really need to add boost headers at all, since noncopyable is simplest and tidy to implement by ourself:
```
namespace boost {
  class noncopyable
  {
  protected:
      noncopyable() {}
      ~noncopyable() {}
  private:
      noncopyable( const noncopyable& );
      noncopyable& operator=( const noncopyable& );
  };
}
```

Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:52]: That was C++03 way to implement `boost::noncopyable`, I think we should provide another test(possible in separate .cpp) with C++11 version of `boost::noncopyable`:
```
namespace boost {
  class noncopyable
  {
  protected:
      constexpr noncopyable() = default;
      ~noncopyable() = default;
      noncopyable( const noncopyable& ) = delete;
      noncopyable& operator=( const noncopyable& ) = delete;
  };
}
```

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 10 above)
Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: Oke, don't worry about bind and Boost's lambdas. I will create issues about all of them later.

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h (hunk 9 above)
Comment (denzor200) [reply clang-tools-extra/clang-tidy/bugprone/CapturingThisByFieldCheck.h:31]: Since this check doesn't cove binds, let's stay it as it is.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst (hunk 5 above)
Comment (HerrCai0907) [reply clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-by-field.rst:24]: I don't understand it well. Do you mean we need more document about how to limit it? And mention  dangling this in docs also?

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 12 above)
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp]: add test

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp (hunk 10 above)
Comment (denzor200) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/capturing-this-by-field.cpp:1]: Created issues about bind and Boost's lambdas:
https://github.com/llvm/llvm-project/issues/131220
https://github.com/llvm/llvm-project/issues/131231

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst [hunk 15]
```diff
@@ -0,0 +1,36 @@
...
+.. code-block:: c++
+
+  struct C {
+    C() : Captured([this]() -> C const * { return this; }) {}
+    std::function<C const *()> Captured;
+  };
+
+  void foo() {
+    C v1{};
+    C v2 = v1; // v2.Captured capture v1's this pointer
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst:24]:
```suggestion
    C v2 = v1; // v2.Captured capture v1's 'this' pointer
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst [hunk 16]
```diff
@@ -0,0 +1,36 @@
...
+    assert(v2.Captured() == v1.Captured()); // v2.Captured capture v1's this pointer
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst:25]:
```suggestion
    assert(v2.Captured() == v1.Captured()); // v2.Captured capture v1's 'this' pointer
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst [hunk 17]
```diff
@@ -0,0 +1,36 @@
...
+    assert(v2.Captured() == &v2); // assertion failed.
+  }
+
+Possible fixes include refactoring the function object into a class member
+method or passing the this pointer as a parameter.
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst:30]:
```suggestion
method or passing the ``this`` pointer as a parameter.
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst [hunk 18]
```diff
@@ -0,0 +1,36 @@
...
+
+.. option:: FunctionWrapperTypes
+
+  A semicolon-separated list of names of types. Used to specify function
+  wrapper that can hold lambda expressions.
+  Default is ``::std::function;::std::move_only_function;::boost::function``.
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/capturing-this-in-member-variable.rst:36]:
```suggestion
  Default is `::std::function;::std::move_only_function;::boost::function`.
```
Single tics for option values

File: clang-tools-extra/clang-tidy/bugprone/CapturingThisInMemberVariableCheck.cpp [hunk 19]
```diff
@@ -0,0 +1,124 @@
...
+  const auto *Capture = Result.Nodes.getNodeAs<LambdaCapture>("capture");
+  const auto *Lambda = Result.Nodes.getNodeAs<LambdaExpr>("lambda");
+  const auto *Field = Result.Nodes.getNodeAs<FieldDecl>("field");
+  diag(Lambda->getBeginLoc(),
+       "'this' captured by a lambda and stored in a class member variable; "
+       "disable implicit class copying/moving to prevent potential "
+       "use-after-free")
+      << Capture->getLocation();
+  diag(Field->getLocation(),
+       "'%0' that stores captured 'this' and becomes invalid during "
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/CapturingThisInMemberVariableCheck.cpp:118]: nit: Maybe make this wording a bit more verbose if you wish
"class member of type '%0' that stores captured 'this' ..."

There is a chance that current wording can be hard to understand for some users with big classes.

**Review by vbvictor — APPROVED** [review]
LGTM, but please wait for others to review

**Review by denzor200 — APPROVED** [review]

**Comment by denzor200** [comment]
LGTM, please provide the change for one comment I left
