### PR TITLE
[Sema] Fix type mismatch error when arguments to elementwise math builtin have different qualifiers, which should be well-formed

### LINKED ISSUE #141397: __builtin_elementwise_pow breaks with .yyy swizzle from const pointer
couldn't really think of a better way to describe the bug. here's the repro code:
```c
typedef float vec3 __attribute__((ext_vector_type(3)));

typedef struct {
    vec3 b;
} struc;

vec3 foo(vec3 a, const struc* hi) { // <- remove const and it'll compile

    vec3 b = __builtin_elementwise_max((vec3)(0.0f), a);
    
    return __builtin_elementwise_pow(b, hi->b.yyy);
}
```

### PR DESCRIPTION
**Pull request by actinks**
Fixes #141397
Element-wise math builtins (e.g. __builtin_elementwise_max/__builtin_elementwise_pow etc.) fail when their arguments have different qualifications, but should be well-formed. The fix is ​​to use hasSameUnqualifiedType to check if the arguments match.

### CODE REVIEW

File: clang/test/SemaCXX/bug141397.cpp [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+typedef float vec3 __attribute__((ext_vector_type(3)));
+
+typedef struct {
+  vec3 b;
+} struc;
+
+vec3 foo(vec3 a,const struc* hi) {
+  vec3 b = __builtin_elementwise_max((vec3)(0.0f), a);
+  return __builtin_elementwise_pow(b, hi->b.yyy);
+}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/bug141397.cpp:16]: Can you move that to test/Sema/builtins-elementwise-math.c, leaving a comment referencing the github issue?

**Review by cor3ntin — COMMENTED** [review]
This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

File: clang/test/SemaCXX/bug141397.cpp [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// using ASTContext::hasSameUnqualifiedType().
+
+typedef float vec3 __attribute__((ext_vector_type(3)));
+
+typedef struct {
+  vec3 b;
+} struc;
+
+vec3 foo(vec3 a,const struc* hi) {
+  vec3 b = __builtin_elementwise_max((vec3)(0.0f), a);
```
Comment (shafik) [inline clang/test/SemaCXX/bug141397.cpp:14]: I see four functions have been changed but I only see two different tests here. Can we please fully cover all the changes? If you feel that there are already tests covering the other changes, please point them out.

**Review by shafik — COMMENTED** [review]
Thank you for the fix.

Please put more details in your summary. Something along the lines of "builtin functions such as __builtin_elementwise_max .... fail when their arguments have different qualifications but this should be well-formed ... the fix involves using hasSameUnqualifiedType to check..." 

It is important to have detailed summaries for the reviewers so they have more context without having to leave the code review and for folks using git log to debug issues when their downstream fork has issues.

File: clang/test/SemaCXX/bug141397.cpp (hunk 1 above)
Comment (QiYueFeiXue) [reply clang/test/SemaCXX/bug141397.cpp:16]: done

**Comment by zyn0217** [comment]
@QiYueFeiXue I don't think @shafik means to directly copy his words to the PR body/title. Please at least flesh out these dotted parts and make the sentences complete, thanks.

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -669,6 +669,7 @@ Bug Fixes in This Version
   base classes. (GH139452)
 - Fixed an assertion failure in serialization of constexpr structs containing unions. (#GH140130)
 - Fixed duplicate entries in TableGen that caused the wrong attribute to be selected. (GH#140701)
+- Fixed type missmach error when 'builtin-elementwise-math' arguments have different qualifiers, this should be a well-formed. (#GH141397)
```
Comment (zyn0217) [inline clang/docs/ReleaseNotes.rst:672]: Missmach -> mismatch (and same in the test!)

A well-formed -> well-formed

**Review by zyn0217 — APPROVED** [review]

File: clang/test/SemaCXX/bug141397.cpp (hunk 2 above)
Comment (shafik) [reply clang/test/SemaCXX/bug141397.cpp]: It may be worth exploring further after you land this change. Thank you for following up and do more checking to verify.

**Comment by shafik** [comment]
> @QiYueFeiXue I don't think @shafik means to directly copy his words to the PR body/title. Please at least flesh out these dotted parts and make the sentences complete, thanks.

Yes, that is what I meant, thank you for clarifying my intent.

**Comment by shafik** [comment]
@Acthink-Yang Do you have commit access? If not then let us know and one of us can merge for you.

**Comment by Acthink-Yang** [comment]
Hi @shafik 

Thanks for checking! I don't have commit access yet. 
Could you please help merge my changes?
