### PR TITLE
[SystemZ] Eliminate call sequence instructions early.

### LINKED ISSUE #76618: Select128 problem
cat crash2.i
```
short a, c;
long b, d;
__int128 e;
int f;
static unsigned __int128 g(unsigned, unsigned __int128, __int128, unsigned,
                           unsigned char);
void h() { g(e, c != 0, e, b, a); }
unsigned __int128 g(unsigned i, unsigned __int128 j, __int128 k, unsigned l,
                    unsigned char m) {
  d = i;
  f = j;
  if (l | m)
    for (;;)
      ;
  return k;
}
void main() {}
```

/home/ijonpan/llvm-project/install/bin/clang -O3 -march=arch13 crash2.i -o a.out -w -fno-inline -mllvm -pre-RA-sched=list-ilp -mllvm -verify-misched
*** Bad machine code: Call frame size on entry does not match value computed from predecessor ***

Looks like there is a Select128 inside the call frame setup (below ADJCALLSTACKDOWN), which makes the verifier complain when new blocks are created there.

### PR DESCRIPTION
**Pull request by JonPsson1**
On SystemZ, the outgoing argument area which is big enough for all calls in the function is created once during the prolog, as opposed to adjusting the stack around each call. The call-sequence instructions are therefore not really useful any more than to compute the maximum call frame size, which has so far been done by PEI, but can just as well be done at an earlier point.

This patch removes the mapping of the CallFrameSetupOpcode and CallFrameDestroyOpcode and instead computes the MaxCallFrameSize directly after instruction selection and then removes the ADJCALLSTACK pseudos. This removes the confusing pseudos and also avoids the problem of having to keep the call frame size accurate when creating new MBBs.

This fixes #76618 which exposed the need to maintain the call frame size when splitting blocks (which was not done).

### CODE REVIEW

**Comment by JonPsson1** [comment]
Do we need to support the inline-asm alignstack attribute? In that case we need to do a similar handling of INLINEASM[_BR] instructions to set the adjustsStack flag. My understanding is however that the stack is always aligned at 8 bytes and therefore this is not needed...?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 1]
```diff
@@ -8096,6 +8096,24 @@ static void createPHIsForSelects(SmallVector<MachineInstr*, 8> &Selects,
...
 }
 
+MachineBasicBlock *
+SystemZTargetLowering::emitAdjCallStack(MachineInstr &MI,
+                                        MachineBasicBlock *BB) const {
+  // Do the work of MachineFrameInfo::computeMaxCallFrameSize() early and
+  // remove these nodes. Given that these nodes start out as a glued sequence
+  // it seems best to remove them here after instruction selection and
+  // scheduling.  NB: MIR testing does not work (yet) for call frames with
+  // this.
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:8106]: Can you elaborate what that problem with MIR testing is, and whether we need to fix it before landing this upstream?

File: llvm/test/CodeGen/SystemZ/call-zos-vararg.ll [hunk 2]
```diff
@@ -88,13 +88,16 @@ entry:
   ret i64 %retval
 }
 
+; TODO: Unfortunately the lgdr is scheduled below the COPY from $r1d, causing
+; an overlap and thus an extra copy.
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/call-zos-vararg.ll:92]: Does the presence of these pseudos help with scheduling around calls in general?  If yes, maybe we can leave them in, and just set the stack size argument always to zero?

**Comment by uweigand** [comment]
> Do we need to support the inline-asm alignstack attribute? In that case we need to do a similar handling of INLINEASM[_BR] instructions to set the adjustsStack flag. My understanding is however that the stack is always aligned at 8 bytes and therefore this is not needed...?

I don't think this flag currently causes any special action on Z.   (But it would be good to try a few test cases to verify that!)   However, if and when that might change in the future, it wouldn't be good if the generic infrastructure around the flag is somehow broken ...

As a more general question, would we be the first platform to not use the adjuststack pseudos, or is there precedent?  If the latter, how are they handling this issue?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 1 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:8106]: wow - now that I checked it turns out that MIR actually *does* save this info as part of the .mir file. So this 'NB' should just be removed. Sorry - I thought I was in new territory here...

File: llvm/test/CodeGen/SystemZ/call-zos-vararg.ll (hunk 2 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/call-zos-vararg.ll:92]: There seems to be a slight help over SPEC:
```
                         2017_A_main/                   2017
Spill|Reload   :               609379               609657     +278
Copies         :              1017860              1018237     +377
```
That's a bit unfortunate as there are supposed to be handling for physreg copies in the machinescheduler. 

I did some experiments per your suggestion by keeping them but setting the value to zero. As they have the side-effects flag, they do affect other optimizers. If I remove those pseudos in ExpandPostRAPseudos, they live past the PEI pass and then the CFG optimizations are hindred (less dublicated return blocks ets).

I think it would be nice to take these out of the equation by simply not using them as they do not make much sense on our target. In theory it should actually be better to not have them around as they model false side-effects. If MachineScheduler could be fixed to not make more COPYs and if the AdjustsStack flag was set early in SelectionDAGISel, I think it would be nice to just remove them. Unfortunately we can't keep them "anonymously" without being mapped as frame instructions, as they do not get removed in time (unless we would insert a new "process" hook in PEI to do that). 

So maybe for now we could just keep them as before and set them to 0. However, unfortunately that doesn't quite work either as PEI for some reason resets this value to 0 as it seems to want to recompute it even though it is set per isMaxCallFrameSizeComputed() ... :-/

**Comment by JonPsson1** [comment]
Patch updated with a version that gives zero change on SPEC and in tests:
- remove the frame instruction mapping of these pseudos so that they are not recognized and thereby avoid the re-computation of MaxCallFrameSize in PEI.
- Set them all to 0 instead of removing them during isel and instead remove them in processFunctionBeforeFrameFinalized(), during PEI.

**Comment by JonPsson1** [comment]
@jayfoad @topperc @MatzeB Does this approach seem right for a target that never needs the call sequence instructions around the calls in the first place?

**Comment by arsenm** [comment]
This seems like an extreme measure to fix the reported issue. We're just missing a helper function to preserve the frame size attributes during a block size split? Seems easier to keep the call frame handling in line with other targets instead of doing something different

**Comment by jayfoad** [comment]
> @jayfoad @topperc @MatzeB @arsenm Does this approach seem right for a target that never needs the call sequence instructions around the calls in the first place?

No objection from me.

**Comment by JonPsson1** [comment]
> This seems like an extreme measure to fix the reported issue. We're just missing a helper function to preserve the frame size attributes during a block size split? Seems easier to keep the call frame handling in line with other targets instead of doing something different

I agree it would solve the current issue fairly well to add a helper function in MachineBasicBlock that would do this. But on the other hand, I wonder if it's only x86 primarily that needs the CALLSEQ pseudos around to do SP adjustments around each call. If that's the case, maybe the default should actually be to compute the MaxCallFrameSize during instruction selection? One step in that direction then, would be to eliminate them during finalize-isel for SystemZ.

I have found myself the Frame Lowering to be quite complex to work with and it doesn't help to have those pseudos around. It's confusing that they are emitted and then used not until PEI to compute this value looking at all the calls, when in fact that is something known already during isel. And adding to this by worrying about preserving this value across MBBs is making things even worse...

So this is not only to fix the issue, but also a nice cleanup of the SystemZ backend, I think. Does this make sense?

**Comment by arsenm** [comment]
> I agree it would solve the current issue fairly well to add a helper function in MachineBasicBlock that would do this. But on the other hand, I wonder if it's only x86 primarily that needs the CALLSEQ pseudos around to do SP adjustments around each call. If that's the case, maybe the default should actually be to compute the MaxCallFrameSize during instruction selection? One step in that direction then, would be to eliminate them during finalize-isel for SystemZ.
> 

Is it only x86? That would be useful to know

> So this is not only to fix the issue, but also a nice cleanup of the SystemZ backend, I think. Does this make sense?

I think so, but it would help to better understand exactly if/why this is the way it is only for x86

**Comment by jayfoad** [comment]
> I agree it would solve the current issue fairly well to add a helper function in MachineBasicBlock that would do this. But on the other hand, I wonder if it's only x86 primarily that needs the CALLSEQ pseudos around to do SP adjustments around each call. If that's the case, maybe the default should actually be to compute the MaxCallFrameSize during instruction selection? One step in that direction then, would be to eliminate them during finalize-isel for SystemZ.

I don't know if this is relevant, but: the reason I introduced `MachineBasicBlock::CallFrameSize` was for ARM, which can create a call sequence with a non-zero frame size and then later split the block in the middle of the call sequence in `ARMTargetLowering::EmitStructByval`.

**Comment by uweigand** [comment]
> I think so, but it would help to better understand exactly if/why this is the way it is only for x86

I've had a bit of a closer look, and it turns out it is more targets than just x86.   In general, the callseq pseudos seem to have to main functions:
- They act as (pre-RA) scheduling barriers to attempt to keep call setup sequences closer together.   This is done on all platforms; I'm not sure if this is required for correctness anywhere, but it does appear to have performance benefits on SystemZ at least.
- They carry a "frame size" value, which is used on *some* targets to modify frame index elimination (i.e. the distance between SP and the frame varies from its default value while within a call sequence).  Where required, this is of course needed for functional correctness.

This second aspect is only used on some platforms, however.   This depends on how the stack space needed to hold outgoing function arguments is allocated: some some platforms, this happens during the call sequence (e.g. via "push" instructions on x86), in others (like SystemZ), the function prolog always allocates enough space for all calls in the function ahead of time, and on yet others this decision is made on a per-function basis (e.g. depending on whether the function also contains dynamic stack allocation).

Platforms where `canSimplifyCallFramePseudos` returns true do not need (or use) that frame size value.  This is the case on SystemZ for all functions, in particular.  However, even on those platforms the machine verifier requires that this value is maintained correctly whenever a basic block is split - although all those correctly maintained values will just be ignored in the end.

The default definition of `canSimplifyCallFramePseudos` is always true.  However, that can change if the platform overrides either `canSimplifyCallFramePseudos` or `hasReservedCallFrame`.   Looking at all platforms that do so, it seems the following platforms actually require the frame size: X86, AArch64/ARM, M86K, Mips, and WebAssembly.

All other platforms either always reserve the call frame in the prolog, or else always use an FP whenever the call frame is not reserved in the prolog.  In both cases, frame index eliminiation does not require the call frame size.

**Comment by JonPsson1** [comment]
Patch rebased with some reworded comments, otherwise same as before: Compute the MaxCallFrameSize during custom insertion (isel) and then set all values to 0. The pseudos are not mapped as frame instructions anymore, so they are only left as scheduling boundaries.

It may be that even though there seem to be some slight advantage for the phys-reg arguments (spilling/copys), perhaps that doesn't matter. If benchmarks show no actual difference, maybe they could just be removed during isel regardless. Alternatively, as stated in the comment, maybe the MIScheduler could be improved here.

We could keep them as pseudos, but then PEI will recompute them and if they are 0 that will not work without first fixing PEI somehow. Unfortunately it seems like other targets want to recompute it for some reason, so not sure how to handle without adding yet another special casing... It is however better to not have this in the sense that they do not serve any purpose.

**Comment by uweigand** [comment]
> It may be that even though there seem to be some slight advantage for the phys-reg arguments (spilling/copys), perhaps that doesn't matter. If benchmarks show no actual difference, maybe they could just be removed during isel regardless.

Do you have any numbers how benchmarks would be affected by just removing the instructions early?

> Alternatively, as stated in the comment, maybe the MIScheduler could be improved here.

Do we know what specifically could be improved?  (I guess we'd have to identify some actual regression first ...)

**Comment by JonPsson1** [comment]
> Do you have any numbers how benchmarks would be affected by just removing the instructions early?

See above: https://github.com/llvm/llvm-project/pull/77812#discussion_r1450911878

> Do we know what specifically could be improved? (I guess we'd have to identify some actual regression first ...)

I can give it a try and see...

**Comment by uweigand** [comment]
> > Do you have any numbers how benchmarks would be affected by just removing the instructions early?
> 
> See above: [#77812 (comment)](https://github.com/llvm/llvm-project/pull/77812#discussion_r1450911878)

Right - I meant do we know whether these few extra instructions actually cause any visible difference in the results anywhere?
 
> > Do we know what specifically could be improved? (I guess we'd have to identify some actual regression first ...)
> 
> I can give it a try and see...

Thanks!

**Comment by JonPsson1** [comment]
I rebuilt everything, and to my surprise I now saw different numbers than before:

main/nfc patch <-> patch but erasing MI
```
Spill|Reload   :               608814               608692     -122
Copies         :              1021002              1020968      -34
```
So at this moment it looks like that small variation can go either way depending on the shape of the compiler on the given day.

I also ran spec. With all benchmarks, ("mini"):

```
Improvements "eraseMI":
0.981: i541.leela_r 
0.990: f538.imagick_r 
0.996: i525.x264_r 

Regressions "eraseMI":
1.013: i505.mcf_r 
1.011: i523.xalancbmk_r 
1.010: i520.omnetpp_r 
1.009: i502.gcc_r 
1.007: f544.nab_r 
1.006: i557.xz_r 

```
That looked like a slight general regression. However, I also ran a few select benchmarks in parallel with the "full" run:

```
Improvements "eraseMI":
0.987: i523.xalancbmk_r 
0.991: f544.nab_r 
0.996: i541.leela_r 

Regressions "eraseMI":
1.013: i520.omnetpp_r 
1.006: i505.mcf_r 
1.004: i531.deepsjeng_r 
1.002: i502.gcc_r 
1.001: i557.xz_r 
```
With these runs it was a general tie on those select benchmarks. 

Given that the spilling has varied a bit both ways, I don't see much point in looking at the MI scheduler. There is already a phys-reg heuristic there, so it should work well in general.

All the benchmarks have not been run fully, but it looks to me that it should be ok to simply remove the MIs and trust that the mi-scheduler will handle it without the scheduling barriers.

**Comment by uweigand** [comment]
OK, this looks really like more in the noise to me.  In that case I agree we should prefer to keep the code as simple as possible, and just remove the MIs early.

**Comment by JonPsson1** [comment]
ok - patch updated to remove the MI pseudo early. Some test changes where one was a bit of an example of where the mi-scheduler actually does mess things up a bit:
```

0B      bb.0 (%ir-block.0):
          liveins: $r1d, $f0d, $r5d
16B       %2:addr64bit = COPY $r5d
32B       %1:fp64bit = COPY $f0d
48B       %0:gr64bit = COPY $r1d
64B       %3:gr64bit = LGDR %1:fp64bit
80B       %4:gr64bit = ADA_ENTRY_VALUE target-flags(<unknown>) @pass_vararg3, %2:addr64bit, 8, implicit-def dead $cc :: (dereferenceable invariant load (s64))
96B       %6:gr64bit = ADA_ENTRY_VALUE target-flags(<unknown>) @pass_vararg3, %2:addr64bit, 0, implicit-def dead $cc :: (dereferenceable invariant load (s64))
112B      $r6d = COPY %4:gr64bit
128B      $r1d = COPY %3:gr64bit
144B      $r2d = COPY %0:gr64bit
160B      $r5d = COPY %6:gr64bit
176B      CallBASR_XPLINK64 killed $r6d, $r1d, killed $r2d, $r5d, <regmask $f8d $f9d $f10d $f11d $f12d $f13d $f14d $f15d $f8q $f9q $f12q $f13q $f8s $f9s $f10s $f11s $f12s $f13s $f14s $f15s $r8d $r9d $r10d $r11d 
$r12d $r13d $r14d $r15d $r8h $r9h $r10h $r11h $r12h and 15 more...>, implicit-def dead $r7d, implicit-def dead $cc, implicit $fpc, implicit-def $r3d
192B      %8:gr64bit = COPY killed $r3d
208B      $r3d = COPY %8:gr64bit
224B      Return_XPLINK implicit killed $r3d

# End machine code for function call_vararg_both0.

# *** IR Dump After Machine Instruction Scheduler (machine-scheduler) ***:
# Machine code for function call_vararg_both0: NoPHIs, TracksLiveness, TiedOpsRewritten
Function Live Ins: $r1d in %0, $f0d in %1, $r5d in %2

0B      bb.0 (%ir-block.0):
          liveins: $r1d, $f0d, $r5d
16B       %2:addr64bit = COPY $r5d
80B       %4:gr64bit = ADA_ENTRY_VALUE target-flags(<unknown>) @pass_vararg3, %2:addr64bit, 8, implicit-def dead $cc :: (dereferenceable invariant load (s64))
96B       %6:gr64bit = ADA_ENTRY_VALUE target-flags(<unknown>) @pass_vararg3, %2:addr64bit, 0, implicit-def dead $cc :: (dereferenceable invariant load (s64))
104B      %1:fp64bit = COPY $f0d
112B      %3:gr64bit = LGDR %1:fp64bit
120B      %0:gr64bit = COPY $r1d
128B      $r6d = COPY %4:gr64bit
136B      $r1d = COPY %3:gr64bit
144B      $r2d = COPY %0:gr64bit
160B      $r5d = COPY %6:gr64bit
176B      CallBASR_XPLINK64 killed $r6d, $r1d, killed $r2d, $r5d, <regmask $f8d $f9d $f10d $f11d $f12d $f13d $f14d $f15d $f8q $f9q $f12q $f13q $f8s $f9s $f10s $f11s $f12s $f13s $f14s $f15s $r8d $r9d $r10d $r11d 
```

The LGDR was in the presence of ADJCALLSTACKDOWN below it, and is moved just above it by the mi-scheduler. For some reason, here without the ADJCALLSTACKDOWN, it is also moved above the COPY from $r1d, which is unfortunate as that causes an overlap of %3 which is to be COPY:ed to the same register.

I don't think there is any "tracking" of which vreg ranges go to/from which physreg and with that avoid unnecessary overlaps like this. Maybe this is rare so it's not worth the effort? Probably not a quick thing to fix, but this is a good example of this problem. Maybe mark the test with a TODO if this is acceptable for now?

**Comment by uweigand** [comment]
Yes, I think this is really something that should be fixed in the register allocate (looks like a parallel-copy problem).  But for now I think this patch is fine as is.  Feel free to add a TODO to the test case, otherwise this LGTM.

**Review by uweigand — APPROVED** [review]
