### PR TITLE
MIPS: fix emitDirectiveCpsetup on N32

### LINKED ISSUE #52785: MIPS: .cpsetup broken for n32
MIPS n32 ABI requires '.cpsetup <r>, <off | reg>, <label>' to generate the following sequence:

```
sd $gp, off ($sp)
lui $gp, label    // top half
addiu $gp, label  // bottom half
addu $gp, $gp, r
```

The MIPS code generator currently does not include the final `addu`, leading to crashes in n32 ABI position independent code.

### PR DESCRIPTION
**Pull request by wzssyqa**
In the current code, we don't support -mno-shared yet, and for N32, .cpsetup is expand as the style -f -mno-shared.

It will generate bad code for PIC binaries like:
```
00000000 <t1>:
   0:   ffbc0008        sd      gp,8(sp)
   4:   3c1c0000        lui     gp,0x0
                        4: R_MIPS_HI16  __gnu_local_gp
   8:   279c0000        addiu   gp,gp,0
                        8: R_MIPS_LO16  __gnu_local_gp
```
In fact which style of .cpsetup is used should be determined by -m(no-)shared option instead of -mabi=n32 option.

Fixes: #52785

### CODE REVIEW

**Comment by wzssyqa** [comment]
@MaskRay

File: llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp [hunk 1]
```diff
@@ -1288,8 +1291,11 @@ void MipsTargetELFStreamer::emitDirectiveCpsetup(unsigned RegNo,
   emitRRX(Mips::ADDiu, GPReg, GPReg, MCOperand::createExpr(LoExpr), SMLoc(),
           &STI);
 
-  // daddu  $gp, $gp, $funcreg
-  emitRRR(Mips::DADDu, GPReg, GPReg, RegNo, SMLoc(), &STI);
+  // (d)addu  $gp, $gp, $funcreg
+  if (getABI().IsN32())
+    emitRRR(Mips::ADDu, GPReg, GPReg, RegNo, SMLoc(), &STI);
```
Comment (MaskRay) [inline llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp:1296]: Confirmed that this is correct.

File: llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp [hunk 2]
```diff
@@ -1255,7 +1255,9 @@ void MipsTargetELFStreamer::emitDirectiveCpsetup(unsigned RegNo,
     emitRRI(Mips::SD, GPReg, Mips::SP, RegOrOffset, SMLoc(), &STI);
   }
 
-  if (getABI().IsN32()) {
+#if 0
+  // We haven't support -mabicalls -mno-shared yet.
+  if (-mno-shared) {
```
Comment (MaskRay) [inline llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp:1260]: IIUC -mno-shared only makes sense for -fno-pic. Modern executables use PIE and cannot use -mno-shared.

**Comment by MaskRay** [comment]
```
#if 0
```
is not recommended. Just remove the code.

Please clarify the comment. Consider the following:

In gas, .cpsetup may expand to one of two code sequences (one is related to `__gnu_local_gp`), depending on -mno-shared and -msym32.
Since Clang doesn't support -mno-shared or -msym32, .cpsetup expands to one code sequence.
The N32 condition incorrectly leads to the incorrect `__gnu_local_gp` code sequence.

**Review by MaskRay — APPROVED** [review]
