### PR TITLE
[Sema] Instantiate destructors for initialized members

### LINKED ISSUE #93251: `clang-cl /EHa` with MSVC `std::variant` emits linker error LNK2019: unresolved external symbol
Repros with Clang 17.0.3 and VS 2022 17.11 Preview 1. MSVC accepts, but Clang rejects.

```
C:\Temp>"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvarsall.bat" x64
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.0-pre.1.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Temp>clang-cl -v
clang version 17.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\Llvm\x64\bin

C:\Temp>type meow.cpp
```
```cpp
#include <variant>
using namespace std;

struct UDT {
    UDT() {}
    ~UDT() {}
};

int main() {
    using V = variant<int, double, UDT>;
    [[maybe_unused]] V a{1729};
    [[maybe_unused]] V b{3.14};
    [[maybe_unused]] V c{UDT{}};
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++17 /MTd /Od meow.cpp
meow.cpp

C:\Temp>cl /EHa /nologo /W4 /std:c++17 /MTd /Od meow.cpp
meow.cpp

C:\Temp>clang-cl /EHsc /nologo /W4 /std:c++17 /MTd /Od meow.cpp

C:\Temp>clang-cl /EHa /nologo /W4 /std:c++17 /MTd /Od meow.cpp
meow-aeb2d1.obj : error LNK2019: unresolved external symbol "public: __cdecl std::_Variant_storage_<0,double,struct UDT>::~_Variant_storage_<0,double,struct UDT>(void)" (??1?$_Variant_storage_@$0A@NUUDT@@@std@@QEAA@XZ) referenced in function "int `public: __cdecl std::_Variant_storage_<0,int,double,struct UDT>::_Variant_storage_<0,int,double,struct UDT><1,double,0>(struct _Variant_storage_<0,int,double,struct UDT>::integral_constant<unsigned __int64,1>,double &&)'::`1'::dtor$3" (?dtor$3@?0???$?0$00N$0A@@?$_Variant_storage_@$0A@HNUUDT@@@std@@QEAA@U?$integral_constant@_K$00@1@$$QEAN@Z@4HA)
meow-aeb2d1.obj : error LNK2019: unresolved external symbol "public: __cdecl std::_Variant_storage_<0,struct UDT>::~_Variant_storage_<0,struct UDT>(void)" (??1?$_Variant_storage_@$0A@UUDT@@@std@@QEAA@XZ) referenced in function "int `public: __cdecl std::_Variant_storage_<0,double,struct UDT>::_Variant_storage_<0,double,struct UDT><1,struct UDT,0>(struct _Variant_storage_<0,double,struct UDT>::integral_constant<unsigned __int64,1>,struct UDT &&)'::`1'::dtor$3" (?dtor$3@?0???$?0$00UUDT@@$0A@@?$_Variant_storage_@$0A@NUUDT@@@std@@QEAA@U?$integral_constant@_K$00@1@$$QEAUUDT@@@Z@4HA)
meow.exe : fatal error LNK1120: 2 unresolved externals
clang-cl: error: linker command failed with exit code 1120 (use -v to see invocation)
```

Reduced from the original user report [DevCom-10647850](https://developercommunity.visualstudio.com/t/Linking-bug-of-std::unordered_map-with-s/10647850) "Linking bug of `std::unordered_map` with `std::variant` Value Type with latest MS Visual Studio Community 2022".

### PR DESCRIPTION
**Pull request by momo5502**
Initializing fields in a constructor that are part of an anonymous union requires their destructors to be instantiated.

In general, initialized members within non-delegating constructors need their destructor instantiated.

This fixes #93251

### CODE REVIEW

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -5451,10 +5451,23 @@ bool Sema::SetCtorInitializers(CXXConstructorDecl *Constructor, bool AnyErrors,
...
 
+    SourceLocation Location = Constructor->getLocation();
+
+    for (CXXCtorInitializer *Initializer : Info.AllToInit) {
+      FieldDecl *Field = Initializer->getAnyMember();
+      if (!Field)
+        continue;
+
+      RecordDecl *FieldRecordDecl = Field->getParent();
+      if (!FieldRecordDecl->isUnion() ||
```
[the remark this answers is not in the document]
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: Both examples should work now. Let's hope all other tests still pass :D

The first example throws an additional error in gcc:

```
member 'VSX<int> VS::<unnamed union>::<unnamed struct>::_Tail' with destructor not allowed in anonymous aggregate
```

this error is not thrown by clang. should it though? If so, I don't think implementing that makes sense within the scope of this PR.
However, is it ok that I still added the sample as a test case, even though technically the behaviour clang yields for this test is not 100% correct?

[the remark this answers is not in the document]
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: One test failed, but it seems that it now behaves identical to gcc ( https://godbolt.org/z/fbxT8xnY9 ), so I fixed the test.

File: clang/test/SemaCXX/union-member-destructor.cpp [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+  ~VSX() { static_assert(sizeof(T) != 4, ""); } // expected-error {{static assertion failed due to requirement 'sizeof(int) != 4':}} \
+                                                // expected-note {{expression evaluates to '4 != 4'}}
+};
+union VS {
+  VSX<int> _Tail;
+  ~VS() { }
+  VS(short);
+};
+VS::VS(short) : _Tail() { } // expected-note {{in instantiation of member function 't3::VSX<int>::~VSX' requested here}}
+}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/union-member-destructor.cpp:48]: Missing newline?

File: clang/test/SemaCXX/cxx0x-nontrivial-union.cpp [hunk 3]
```diff
@@ -51,18 +51,18 @@ namespace disabled_dtor {
   union disable_dtor {
     T val;
     template<typename...U>
-    disable_dtor(U &&...u) : val(forward<U>(u)...) {}
+    disable_dtor(U &&...u) : val(forward<U>(u)...) {} // expected-error {{attempt to use a deleted function}}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/cxx0x-nontrivial-union.cpp:54]: I think this error is correct: if the body of the constructor throws, we call the destructor for val.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 4]
```diff
@@ -5451,10 +5451,31 @@ bool Sema::SetCtorInitializers(CXXConstructorDecl *Constructor, bool AnyErrors,
            NumInitializers * sizeof(CXXCtorInitializer*));
     Constructor->setCtorInitializers(baseOrMemberInitializers);
 
+    SourceLocation Location = Constructor->getLocation();
+
+    for (CXXCtorInitializer *Initializer : Info.AllToInit) {
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaDeclCXX.cpp:5456]: Instead of trying to detect the specific fields not handled by MarkBaseAndMemberDestructorsReferenced, I think it would be more straightforward to split MarkBaseDestructorsReferenced and MarkMemberDestructorsReferenced into separate functions, and just don't call MarkMemberDestructorsReferenced from here.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/lib/Sema/SemaDeclCXX.cpp]: The `member with destructor not allowed in anonymous aggregate` error is separate from what we're trying to do here; I'd say don't worry about it.

File: clang/test/SemaCXX/union-member-destructor.cpp (hunk 2 above)
Comment (momo5502) [reply clang/test/SemaCXX/union-member-destructor.cpp]: fixed

File: clang/test/SemaCXX/cxx0x-nontrivial-union.cpp (hunk 3 above)
Comment (momo5502) [reply clang/test/SemaCXX/cxx0x-nontrivial-union.cpp:54]: nice

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: great

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 5]
```diff
@@ -5759,55 +5768,48 @@ void Sema::ActOnMemInitializers(Decl *ConstructorDecl,
...
+  DiagnoseUseOfDecl(Dtor, Location);
+}
 
-    MarkFunctionReferenced(Location, Dtor);
-    DiagnoseUseOfDecl(Dtor, Location);
-  }
+void Sema::MarkBaseDestructorReferenced(SourceLocation Location,
+                                        CXXRecordDecl *ClassDecl) {
+  // Ignore dependent contexts. Also ignore unions, since their members never
+  // have destructors implicitly called.
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaDeclCXX.cpp:5810]: Drop the comment about unions.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 6]
```diff
@@ -5759,55 +5768,48 @@ void Sema::ActOnMemInitializers(Decl *ConstructorDecl,
...
-                            << Field->getDeclName()
-                            << FieldType);
+  MarkFunctionReferenced(Location, Dtor);
+  DiagnoseUseOfDecl(Dtor, Location);
+}
 
-    MarkFunctionReferenced(Location, Dtor);
-    DiagnoseUseOfDecl(Dtor, Location);
-  }
+void Sema::MarkBaseDestructorReferenced(SourceLocation Location,
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaDeclCXX.cpp:5807]: `MarkBaseDestructorsReferenced`?

**Review by efriedma-quic — APPROVED** [review]
LGTM with a couple minor comments

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 6 above)
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: done

**Comment by momo5502** [comment]
@efriedma-quic thank you for your help and the review. I have no merge rights, would you mind merging this for me?

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 7]
```diff
@@ -5450,10 +5450,20 @@ bool Sema::SetCtorInitializers(CXXConstructorDecl *Constructor, bool AnyErrors,
...
     // destructors.
-    MarkBaseAndMemberDestructorsReferenced(Constructor->getLocation(),
-                                           Constructor->getParent());
+
+    for (CXXCtorInitializer *Initializer : Info.AllToInit) {
+      FieldDecl *Field = Initializer->getAnyMember();
+      if (!Field)
+        continue;
+
+      MarkFieldDestructorReferenced(Location, Field);
```
Comment (shafik) [inline clang/lib/Sema/SemaDeclCXX.cpp:5463]: We should include a standard reference here, I believe the correct reference would be: https://eel.is/c++draft/class.base.init#12

File: clang/test/SemaCXX/union-member-destructor.cpp [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+                                                // expected-note {{expression evaluates to '4 != 4'}}
+};
+struct VS {
+  union {
+    VSX<int> _Tail;
+  };
+  ~VS() { }
+  VS(short);
+};
+VS::VS(short) : _Tail() { } // expected-note {{in instantiation of member function 't1::VSX<int>::~VSX' requested here}}
```
Comment (shafik) [inline clang/test/SemaCXX/union-member-destructor.cpp:15]: Based on https://eel.is/c++draft/class.base.init#12 this should not apply to delegating constructors, can we add a test if once does not exist that verifies this.

**Review by shafik — COMMENTED** [review]
This requires a release note, especially b/c this is a conformance fix.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 7 above)
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp:5468]: done

File: clang/test/SemaCXX/union-member-destructor.cpp (hunk 8 above)
Comment (momo5502) [reply clang/test/SemaCXX/union-member-destructor.cpp:17]: I added a delegating constructor to the test. As the delegating constructor invokes the one that triggers the assertion, the assertion has to come either way. Therefore, I assume the test should assert that the note does not appear at the delegating constructor.

File: clang/include/clang/Sema/Sema.h [hunk 9]
```diff
@@ -5432,6 +5432,9 @@ class Sema final : public SemaBase {
   void MarkBaseAndMemberDestructorsReferenced(SourceLocation Loc,
                                               CXXRecordDecl *Record);
 
+  void MarkBaseDestructorsReferenced(SourceLocation Loc, CXXRecordDecl *Record);
+  void MarkFieldDestructorReferenced(SourceLocation Loc, FieldDecl *Field);
```
Comment (cor3ntin) [inline clang/include/clang/Sema/Sema.h:5436]: I feel these should just be static functions in the cpp file

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 10]
```diff
@@ -5863,6 +5869,26 @@ Sema::MarkBaseAndMemberDestructorsReferenced(SourceLocation Location,
...
+                                                  CXXRecordDecl *ClassDecl) {
+  // Ignore dependent contexts. Also ignore unions, since their members never
+  // have destructors implicitly called.
+  if (ClassDecl->isDependentContext() || ClassDecl->isUnion())
+    return;
+
+  // FIXME: all the access-control diagnostics are positioned on the
+  // field/base declaration.  That's probably good; that said, the
+  // user might reasonably want to know why the destructor is being
+  // emitted, and we currently don't say.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaDeclCXX.cpp:5882]: I'm not sure that this fix me is actually useful

Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp:5882]: Hard for me to judge. It was added 15 years ago: https://github.com/llvm/llvm-project/commit/1064d7ef2992225ddbd792d1b54d144b809b5b39
I can remove it, if desired.

File: clang/include/clang/Sema/Sema.h (hunk 9 above)
Comment (momo5502) [reply clang/include/clang/Sema/Sema.h]: done

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 11]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+  if (Field->isInvalidDecl())
+    return;
+
+  // Don't destroy incomplete or zero-length arrays.
+  if (isIncompleteOrZeroLengthArrayType(S.Context, Field->getType()))
+    return;
+
+  QualType FieldType = S.Context.getBaseElementType(Field->getType());
+
+  const RecordType *RT = FieldType->getAs<RecordType>();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5297]:
```suggestion
  const auto *RT = FieldType->getAs<RecordType>();
```

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 12]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+  if (!RT)
+    return;
+
+  CXXRecordDecl *FieldClassDecl = cast<CXXRecordDecl>(RT->getDecl());
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5301]:
```suggestion
  auto *FieldClassDecl = cast<CXXRecordDecl>(RT->getDecl());
```

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 13]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+    CXXDestructorDecl *Dtor = ClassDecl->getDestructor();
+    if (Dtor && Dtor->isUsed())
+      VisitVirtualBases = false;
+  }
+
+  llvm::SmallPtrSet<const RecordType *, 8> DirectVirtualBases;
+
+  // Bases.
+  for (const auto &Base : ClassDecl->bases()) {
+    const RecordType *RT = Base.getType()->getAs<RecordType>();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5344]:
```suggestion
    const auto *RT = Base.getType()->getAs<RecordType>();
```

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 14]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+      continue;
+
+    // Remember direct virtual bases.
+    if (Base.isVirtual()) {
+      if (!VisitVirtualBases)
+        continue;
+      DirectVirtualBases.insert(RT);
+    }
+
+    CXXRecordDecl *BaseClassDecl = cast<CXXRecordDecl>(RT->getDecl());
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5355]:
```suggestion
    auto *BaseClassDecl = cast<CXXRecordDecl>(RT->getDecl());
```

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 15]
```diff
@@ -5450,10 +5546,25 @@ bool Sema::SetCtorInitializers(CXXConstructorDecl *Constructor, bool AnyErrors,
...
+    for (CXXCtorInitializer *Initializer : Info.AllToInit) {
+      FieldDecl *Field = Initializer->getAnyMember();
+      if (!Field)
+        continue;
+
+      // C++ [class.base.init]p12:
+      //   In a non-delegating constructor, the destructor for each
+      //   potentially constructed subobject of class type is potentially
+      //   invoked
+      //   ([class.dtor]).
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:5563]:
```suggestion
      //   invoked.
```

**Review by AaronBallman — APPROVED** [review]
Only nits from me, but I think this LG otherwise.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 12 above)
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclCXX.cpp:5301]: Instead of the `getAsRecordType` and down, we have a function for all of that.  `auto *FieldType->getAsCXXRecordDecl();`

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 16]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+  // If the destructor exists and has already been marked used in the MS ABI,
+  // then virtual base destructors have already been checked and marked used.
+  // Skip checking them again to avoid duplicate diagnostics.
+  if (S.Context.getTargetInfo().getCXXABI().isMicrosoft()) {
+    CXXDestructorDecl *Dtor = ClassDecl->getDestructor();
+    if (Dtor && Dtor->isUsed())
+      VisitVirtualBases = false;
+  }
+
+  llvm::SmallPtrSet<const RecordType *, 8> DirectVirtualBases;
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclCXX.cpp:5340]: Same 'trick' as above to go from `type`->`CXXRecordDecl`.  I might suggest making this pointer-set store `CXXRecordDecl`.  WDYT?

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 17]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+    // Remember direct virtual bases.
+    if (Base.isVirtual()) {
+      if (!VisitVirtualBases)
+        continue;
+      DirectVirtualBases.insert(RT);
+    }
+
+    CXXRecordDecl *BaseClassDecl = cast<CXXRecordDecl>(RT->getDecl());
+    // If our base class is invalid, we probably can't get its dtor anyway.
+    if (BaseClassDecl->isInvalidDecl())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclCXX.cpp:5357]: Everything from type->`DiagnoseUseofDecl` seems to be the same as in the function above.  I'd prefer we extract THAT into at least a static function and just call it from the other two.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 16 above)
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: Yep, makes sense. I changed it.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 17 above)
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: I extracted everything up to the destructor lookup. 
The `CheckDestructorAccess` call afterwards seems to differ slightly, so I left the rest as it is.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 18]
```diff
@@ -5283,6 +5283,102 @@ Sema::SetDelegatingInitializer(CXXConstructorDecl *Constructor,
...
+
+  llvm::SmallPtrSet<const CXXRecordDecl *, 8> DirectVirtualBases;
+
+  // Bases.
+  for (const auto &Base : ClassDecl->bases()) {
+    const auto *RT = Base.getType()->getAs<RecordType>();
+    if (!RT)
+      continue;
+
+    auto *BaseClassDecl = cast<CXXRecordDecl>(RT->getDecl());
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclCXX.cpp:5354]:
```suggestion
    auto *BaseClassDecl = Base.getType()->getAsCXXRecordDecl();```

Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: oops 😂

**Review by erichkeane — APPROVED** [review]
there was a lot of conversation, so give others a day or two before committing this.

**Comment by momo5502** [comment]
> there was a lot of conversation, so give others a day or two before committing this.

yeah, no worries :D thank you for your review

File: clang/test/SemaCXX/union-member-destructor.cpp (hunk 8 above)
Comment (shafik) [reply clang/test/SemaCXX/union-member-destructor.cpp:17]: Makes sense, that might be a bit subtle for folks running into the test, so it is worth it to add a comment noting that.

**Review by shafik — APPROVED** [review]
LGTM besides the last comment I made on adding a comment to the test.

File: clang/test/SemaCXX/union-member-destructor.cpp (hunk 8 above)
Comment (momo5502) [reply clang/test/SemaCXX/union-member-destructor.cpp:17]: alright, done.

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 10 above)
Comment (momo5502) [reply clang/lib/Sema/SemaDeclCXX.cpp]: @cor3ntin shall I remove it or keep it?

**Comment by cor3ntin** [comment]
@shafik can you merge once you are happy?

**Comment by momo5502** [comment]
> @shafik can you merge once you are happy?

@shafik has already approved. the only open comment was from you @cor3ntin. judging from your comment here, I assume Iit's ok to keep the fixme and resolve the comment (if not, feel free to reopen it).
