### PR TITLE
Fix double-quotes in diagnostic when attempting to access a ext_vector of bools

### LINKED ISSUE #116932: Double single-quotes in "illegal vector component name" diagnostic
See this test case:
https://github.com/llvm/llvm-project/blob/565a9ac7df3815ed038938942be4cf1471de4755/clang/test/SemaCXX/vector-bool.cpp#L88-L91

The double single-quotes are incorrect and usually coming from the diagnostic text containing the quotes directly, while passing a `NamedDecl` to the diagnostics engine adds single-quotes again.

### PR DESCRIPTION
**Pull request by smallp-o-p**
Fixes #116932 

- Remove the quotation marks in the diagnostic message for err_ext_vector_component_name_illegal
- Pass in the quotation marks directly when reporting an illegal vector component name inside `CheckExtVectorComponent`
- Add an offset to the `OpLoc` passed into `S.Diag` so the error message arrow points directly to the offending illegal component rather than to the '.' at the start of the component identifier. 
- Modify the `vector-bool.cpp` element-wise access test case so it (correctly) now only expects a single set of quotes.

### CODE REVIEW

File: clang/lib/Sema/SemaExprMember.cpp [hunk 1]
```diff
@@ -1655,8 +1655,10 @@ static ExprResult LookupMemberExpr(Sema &S, LookupResult &R,
     // We disallow element access for ext_vector_type bool.  There is no way to
     // materialize a reference to a vector element as a pointer (each element is
     // one bit in the vector).
+    assert(MemberName.isIdentifier() &&
+           "Ext vector component name not an identifier!");
     S.Diag(R.getNameLoc(), diag::err_ext_vector_component_name_illegal)
-        << MemberName
+        << MemberName.getAsIdentifierInfo()->getName()
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExprMember.cpp:1661]: Did you try to remove the quotes in DiagnositicSemaKind.td instead?

Comment (smallp-o-p) [reply clang/lib/Sema/SemaExprMember.cpp:1661]: The reason I did this instead of that was cause in `CheckExtVectorComponent`, a `StringRef` is passed to the diagnostics handler, which doesn't add quotes around the name, hence why the quotes are in the error message in the first place.   

Removing the quotes in `DiagnosticsSemaKind.td` causes the tests in `/Sema/ext_vector_components.c` to fail.

The real todo would be to implement modifications for `ak_std_string`. 

Let me know what you think, also thank you for taking the time to look at this.

Comment (erichkeane) [reply clang/lib/Sema/SemaExprMember.cpp:1661]: I would rather we remove the quotes from the diagnostic, and re-add them in the string-ref being passed (OR, better, refactor that part to actually send the component rather than the string ref).  Having to do this work to get the identifier that should be handled by the diagnostics engine isn't correct IMO.

That is, remove the quotes from the diag, and fix `CheckExtVectorComponent`, not make this site worse.

Comment (smallp-o-p) [reply clang/lib/Sema/SemaExprMember.cpp:1661]: Fair enough. I'll put this back into draft and get to work on that.

Thanks!

**Review by shafik — COMMENTED** [review]
Thank you for your contribution, please add a more detailed summary to your PR. Your summary should if your title describes the problem sufficiently describe how you will fix the problem.

**Review by cor3ntin — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaExprMember.cpp [hunk 2]
```diff
@@ -434,8 +434,11 @@ CheckExtVectorComponent(Sema &S, QualType baseType, ExprValueKind &VK,
   if (!HalvingSwizzle && *compStr) {
     // We didn't get to the end of the string. This means the component names
     // didn't come from the same set *or* we encountered an illegal name.
-    S.Diag(OpLoc, diag::err_ext_vector_component_name_illegal)
-      << StringRef(compStr, 1) << SourceRange(CompLoc);
+    size_t Offset = compStr - CompName->getNameStart() + 1;
+    char Fmt[3] = {'\'', *compStr, '\''};
+    S.Diag(OpLoc.getLocWithOffset(Offset),
+           diag::err_ext_vector_component_name_illegal)
+        << StringRef(Fmt, 3) << SourceRange(CompLoc);
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExprMember.cpp:441]: Can someone explain how this works?  It looks like (both before and after) that we're treating the name length as being only 1 (and in this case, 3 after we're adding the single quote on both sides).  

BUT it seems in test 91 below that the 'wyx' works, but is 3 characters long.  Why can't we just print the entirety of the `IdentifierInfo` above?

Comment (erichkeane) [reply clang/lib/Sema/SemaExprMember.cpp:441]: A quick debug shows the below test changes are a little confusing, as the 'bool' vectors dont' actually allow anything, so this just ends up diagnosing elsewhere.  So this change _IS_ just diagnosing a single letter.

For some reason that I don't quite understand, the access is allowed to be any combo of `x`,`y`, `z`, `w`, `r`, `g`,` b`, and `a`, with some attempt to be able to 'set' them.  So it seems we're trying to diagnose the first one that isn't one of those above letters, so the single letter thing seems fine, just confusing for obvious reasons :)

Comment (smallp-o-p) [reply clang/lib/Sema/SemaExprMember.cpp:441]: This is the error path for when you try to mix different accessor types on openCL vector types, which allows you to access them [with this syntax](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#vector-components) but disallows mixing the different styles.

For example, trying to do something like `.rgbz` where `z` is the bad accessor--here we're mixing the `xyzw` access style with the `rgba` access style. This should result in an error, as evidenced by the [test(s) here](https://github.com/llvm/llvm-project/blob/d866005f6928a2a97e67866bedb26139d8cc27d9/clang/test/Sema/ext_vector_components.c#L46)

**Comment by tbaederr** [comment]
Do you need someone to push this?

**Comment by smallp-o-p** [comment]
Yes please.
