### PR TITLE
[clang][CodeComplete] Use HeuristicResolver in getAsRecordDecl()

### LINKED ISSUE #130468: Code completion does not work for member of alias template with dependent argument
In the following testcase:

```c++
template <typename T>
struct S {
  int a;
};

template <typename T> using Alias = S<T>;

template <typename T>
void f(Alias<T> s) {
  s.^
}
```

Code completion at the `^` does not offer the member `a` but should.

(I noticed this while writing [this testcase](https://searchfox.org/llvm/rev/73e14de207a3aa0fa071fa56756e8e316edf5227/clang/test/CodeCompletion/member-access.cpp#421-437). The seemingly more complicated member-of-a-member scenario works, but this simpler scenario does not.)

### PR DESCRIPTION
**Pull request by HighCommander4**
Fixes https://github.com/llvm/llvm-project/issues/130468

### CODE REVIEW

**Comment by HighCommander4** [comment]
I split the PR up into a few commits for easier reviewing.

The high-level idea here is that the helper function `getAsRecordDecl()` in SemaCodeComplete.cpp is doing similar things to HeuristicResolver (specifically, `simplifyType` and `resolveTypeToRecordDecl`), but HeuristicResolver is handling a few more cases, and to get code completion to benefit from those cases the patch gets the helper function to use HeuristicResolver.

There was one case, `TSK_Undeclared`, that `getAsRecordDecl()` handled but HeuristicResolver didn't. I contemplated adding a standalone test case for that to HeuristicResolverTests but it's not easy because the situation only arises during code completion when the AST is not fully built. The case does have test coverage, in `clang/test/CodeCompletion/desig-init.cpp` (this test fails without the `TSK_Undeclared` handling).

**Comment by HighCommander4** [comment]
(I messed things up a bit here by merging a PR that was stacked on top of this into this one. Marking as Draft until I sort that out.)

**Comment by HighCommander4** [comment]
Fixed now. Resubmitting for review.

**Comment by HighCommander4** [comment]
(Rebased)

File: clang/lib/Sema/SemaCodeComplete.cpp [hunk 1]
```diff
@@ -5346,27 +5348,11 @@ AddRecordMembersCompletionResults(Sema &SemaRef, ResultBuilder &Results,
...
-    }
-    return RD;
-  }
-
-  if (const auto *TST = BaseType->getAs<TemplateSpecializationType>()) {
-    if (const auto *TD = dyn_cast_or_null<ClassTemplateDecl>(
-            TST->getTemplateName().getAsTemplateDecl())) {
-      return TD->getTemplatedDecl();
-    }
-  }
```
Comment (zyn0217) [inline clang/lib/Sema/SemaCodeComplete.cpp:5367]: I might be missing something, do we now call `resolveTemplateSpecializationType` somewhere?

**Review by zyn0217 — COMMENTED** [review]
Thanks for consistently working on this!

File: clang/lib/Sema/SemaCodeComplete.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaCodeComplete.cpp:5367]: Oh nevermind it's inside resolveTypeToTagDecl

**Review by zyn0217 — APPROVED** [review]

File: clang/lib/Parse/Parser.cpp [hunk 2]
```diff
@@ -54,8 +54,9 @@ IdentifierInfo *Parser::getSEHExceptKeyword() {
 }
 
 Parser::Parser(Preprocessor &pp, Sema &actions, bool skipFunctionBodies)
-    : PP(pp), PreferredType(pp.isCodeCompletionEnabled()), Actions(actions),
-      Diags(PP.getDiagnostics()), StackHandler(Diags),
+    : PP(pp),
+      PreferredType(&actions.getASTContext(), pp.isCodeCompletionEnabled()),
```
[the remark this answers is not in the document]
Comment (HighCommander4) [reply clang/lib/Parse/Parser.cpp:58]: I actually tried this initially, but `PreferredTypeBuilder` has its assignment operator called [here](https://searchfox.org/llvm/rev/71f629fc2a93e41577c09bdd782b2ba524ed5fea/clang/include/clang/Parse/Parser.h#1061), and that does not compile if it has a member of reference type.

**Comment by HighCommander4** [comment]
(Rebased)
