### PR TITLE
[mlir][llvm][OpenMP] Hoist __atomic_load alloca

### LINKED ISSUE #120724: [flang][openmp] crash in complex atomic
```
  complex c
  integer :: i
  c=(1.0,1.0)
  call omp_set_num_threads(4)
  !$omp parallel do
     do i = 1, 100000000
     !$omp atomic
     c = c + (1.0,1.0)
  end do
  print *, c
end
```

Segfaults in __atomic_compare_exchange 

```
#0  0x00007ffff7fa46c7 in __atomic_compare_exchange () from /lib/x86_64-linux-gnu/libatomic.so.1
#1  0x0000555555555418 in _QQmain..omp_par () at repro.f90:7
#2  0x00007ffff62c3239 in __kmp_invoke_microtask () from lib/libomp.so
#3  0x00007ffff624041f in __kmp_invoke_task_func () from lib/libomp.so
#4  0x00007ffff623f07e in __kmp_launch_thread () from lib/libomp.so
#5  0x00007ffff62a2f18 in __kmp_launch_worker(void*) () from lib/libomp.so
#6  0x00007ffff5e94ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#7  0x00007ffff5f26660 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
````

If I lower the loop iteration from 100000000 to 1000000, I do not see such crash and the expected number is printed.

### PR DESCRIPTION
**Pull request by NimishMishra**
Current implementation of `__atomic_compare_exchange` uses an alloca for `__atomic_load`, leading to issues like https://github.com/llvm/llvm-project/issues/120724. This PR hoists this alloca to `AllocaIP`. 

Fixes: https://github.com/llvm/llvm-project/issues/120724

### CODE REVIEW

**Review by kiranchandramohan — APPROVED** [review]
LG.

Please wait for @Meinersbur or @tblah.

File: llvm/lib/Frontend/Atomic/Atomic.cpp [hunk 1]
```diff
@@ -118,8 +118,14 @@ AtomicInfo::EmitAtomicLoadLibcall(AtomicOrdering AO) {
   Value *PtrVal = getAtomicPointer();
   PtrVal = Builder->CreateAddrSpaceCast(PtrVal, PointerType::getUnqual(Ctx));
   Args.push_back(PtrVal);
+
+  auto CurrentIP = Builder->saveIP();
+  BasicBlock &InsertBB =
+      Builder->GetInsertBlock()->getParent()->getEntryBlock();
```
Comment (tblah) [inline llvm/lib/Frontend/Atomic/Atomic.cpp:124]: This will put the alloca too far out if this is used in the presence of openmp constructs which are put into outlined functions (e.g. parallel, task, target). The rough order of events is

1. All code is generated inside of the same function (this is where EmitAtomicLoadLibcall runs)
2. Each outlined region is moved to its own function

This means that the entry block here is the original entry block of the function that contains the outlined operation not the entry block of the final outlined function.

For example, see the code generated for https://github.com/llvm/llvm-project/issues/120724 before and after this patch. The alloca is moved to the entry block of `_QQmain` and then this is passed into the parallel region like a shared variable (which could produce incorrect results if multiple threads try to use the shared alloca at the same time).

There are a few possible solutions here

1. Keep the alloca in the same place as before this patch but add stack save/restore operations so that the stack usage remains constant no matter how many times this is executed
2. OpenMPIRBuilder usually has a variable describing the correct insertion point for allocas, that could be passed to here
3. Have some pass that runs after all of the functions have been outlined by OpenMPIRBuilder which tries to move allocas to the entry blocks of those functions

Of these, I think (1) would be easiest to implement. It will have some overhead but personally I would be happy to come back to that and try a more complex solution only if that overhead turns out to be a problem in practice.

**Review by tblah — CHANGES_REQUESTED** [review]
Requesting changes because I don't think this alloca placement is safe in the presence of outlined openmp constructs.

File: llvm/lib/Frontend/Atomic/Atomic.cpp (hunk 1 above)
Comment (tblah) [reply llvm/lib/Frontend/Atomic/Atomic.cpp:124]: Posting the diff for #120724 to make the above explanation clearer:
```diff
--- /tmp/old.ll	2025-03-26 11:04:27.390461691 +0000
+++ /tmp/new.ll	2025-03-26 11:36:09.594270400 +0000
@@ -13,7 +13,8 @@
 @2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 66, i32 0, i32 22, ptr @0 }, align 8
 
 define void @_QQmain() {
-  %structArg = alloca { ptr }, align 8
+  %structArg = alloca { ptr, ptr }, align 8
+  %atomic.temp.load = alloca { float, float }, align 8
   %1 = alloca i32, i64 1, align 4
   %2 = alloca { float, float }, i64 1, align 8
   %3 = alloca i32, i64 1, align 4
@@ -27,8 +28,10 @@
   br label %omp_parallel
 
 omp_parallel:                                     ; preds = %entry
-  %gep_ = getelementptr { ptr }, ptr %structArg, i32 0, i32 0
+  %gep_ = getelementptr { ptr, ptr }, ptr %structArg, i32 0, i32 0
   store ptr %2, ptr %gep_, align 8
+  %gep_atomic.temp.load = getelementptr { ptr, ptr }, ptr %structArg, i32 0, i32 1
+  store ptr %atomic.temp.load, ptr %gep_atomic.temp.load, align 8
   call void (ptr, i32, ptr, ...) @__kmpc_fork_call(ptr @1, i32 1, ptr @_QQmain..omp_par, ptr %structArg)
   br label %omp.par.exit
 
@@ -45,8 +48,10 @@
 ; Function Attrs: nounwind
 define internal void @_QQmain..omp_par(ptr noalias %tid.addr, ptr noalias %zero.addr, ptr %0) #0 {
 omp.par.entry:
-  %gep_ = getelementptr { ptr }, ptr %0, i32 0, i32 0
+  %gep_ = getelementptr { ptr, ptr }, ptr %0, i32 0, i32 0
   %loadgep_ = load ptr, ptr %gep_, align 8
+  %gep_atomic.temp.load = getelementptr { ptr, ptr }, ptr %0, i32 0, i32 1
+  %loadgep_atomic.temp.load = load ptr, ptr %gep_atomic.temp.load, align 8
   %p.lastiter = alloca i32, align 4
   %p.lowerbound = alloca i32, align 4
   %p.upperbound = alloca i32, align 4
@@ -123,9 +128,8 @@
 
 omp.loop_nest.region:                             ; preds = %omp_loop.body
   store i32 %8, ptr %omp.private.alloc, align 4
-  %atomic.temp.load = alloca { float, float }, align 8
-  call void @__atomic_load(i64 8, ptr %loadgep_, ptr %atomic.temp.load, i32 0)
-  %9 = load { float, float }, ptr %atomic.temp.load, align 8
+  call void @__atomic_load(i64 8, ptr %loadgep_, ptr %loadgep_atomic.temp.load, i32 0)
+  %9 = load { float, float }, ptr %loadgep_atomic.temp.load, align 8
   br label %.atomic.cont
 
 .atomic.cont:                                     ; preds = %.atomic.cont, %omp.loop_nest.region
@@ -137,8 +141,8 @@
   %15 = insertvalue { float, float } undef, float %13, 0
   %16 = insertvalue { float, float } %15, float %14, 1
   store { float, float } %16, ptr %x.new.val, align 4
-  %17 = call i1 @__atomic_compare_exchange(i64 8, ptr %loadgep_, ptr %atomic.temp.load, ptr %x.new.val, i32 2, i32 2)
-  %18 = load { float, float }, ptr %atomic.temp.load, align 4
+  %17 = call i1 @__atomic_compare_exchange(i64 8, ptr %loadgep_, ptr %loadgep_atomic.temp.load, ptr %x.new.val, i32 2, i32 2)
+  %18 = load { float, float }, ptr %loadgep_atomic.temp.load, align 4
   br i1 %17, label %.atomic.exit, label %.atomic.cont
 
 .atomic.exit:                                     ; preds = %.atomic.cont
@@ -203,6 +207,6 @@
 
 !0 = !{i32 7, !"openmp", i32 11}
 !1 = !{i32 2, !"Debug Info Version", i32 3}
-!2 = !{!"flang version 21.0.0 (git@github.com:llvm/llvm-project.git 7967a6c7792af8fb7b8fe8957235e517839c4a96)"}
+!2 = !{!"flang version 21.0.0 (git@github.com:NimishMishra/f18-llvm-project.git 5753d49b7b989b0079b321c38576a1fc98ac6cbe)"}
 !3 = !{!4}
 !4 = !{i64 2, i64 -1, i64 -1, i1 true}

```

Comment (NimishMishra) [reply llvm/lib/Frontend/Atomic/Atomic.cpp:124]: > This means that the entry block here is the original entry block of the function that contains the outlined operation not the entry block of the final outlined function.

Is that so? Thanks for pointing out. I thought the function outlining occurred before the codegen inside the function.

I'll then implement the stack save/restore solution.

Comment (NimishMishra) [reply llvm/lib/Frontend/Atomic/Atomic.cpp]: Hi @tblah, 

I have enclosed the offending compare-exchange loop with a stack save/restore, and the SEGFAULT is resolved now in my testing.

Do you think we need the stack save/restore for atomic reads too (where we would not have any updates)? I could not reproduce a problem as such, so have not added the save/restore as of now. Do let me know if they are needed for atomic reads too.

**Review by Meinersbur — CHANGES_REQUESTED** [review]
stacksave/stackrestore is for dynamically-sized allocas[^1]. If you don't have dynamically-sized allocas, don't use them. Normal allocas **must** be emitted into the AllocaInsertPt (as done in #101966).

[^1]: And `__builtin_alloca` in a loop to build stack-based linked lists. Never seen this in the wild.

File: llvm/lib/Frontend/Atomic/Atomic.cpp (hunk 1 above)
Comment (tblah) [reply llvm/lib/Frontend/Atomic/Atomic.cpp]: See Michael's comment.

I think this potentially needs fixing anywhere we are generating an alloca which we don't know for sure will end up in an entry block or otherwise outside of a long loop.

**Comment by NimishMishra** [comment]
> stacksave/stackrestore is for dynamically-sized allocas[1](#user-content-fn-1-c2e54219bfae97730cb05f87a9346239). If you don't have dynamically-sized allocas, don't use them. Normal allocas **must** be emitted into the AllocaInsertPt (as done in #101966).

Oh. Okay, understood. I'll revert the changes to the PR then. 

Again, this is new info to me; could you tell why is it that stack save/restore is not for allocas of known size at compile time? I am assuming performance reasons, but is there something else too?

File: llvm/lib/Frontend/Atomic/Atomic.cpp (hunk 1 above)
Comment (NimishMishra) [reply llvm/lib/Frontend/Atomic/Atomic.cpp]: I will make the changes Michael requested. Thanks.

**Comment by tblah** [comment]
> Again, this is new info to me; could you tell why is it that stack save/restore is not for allocas of known size at compile time? I am assuming performance reasons, but is there something else too?

New to me too. I think this is done in other places in flang where there is no way to put allocas in the entry block.

**Comment by Meinersbur** [comment]
> > Again, this is new info to me; could you tell why is it that stack save/restore is not for allocas of known size at compile time? I am assuming performance reasons, but is there something else too?
> 
> New to me too. I think this is done in other places in flang where there is no way to put allocas in the entry block.

[Mem2Reg](https://github.com/llvm/llvm-project/blob/191e0622e84a215c1d632412561c2fe6ccd86170/llvm/lib/Transforms/Utils/Mem2Reg.cpp#L44-L46) and SROA only ever consider allocas in the entry block. Other allocas will not be promoted to registers, resulting in a heavy performance penalty. For this reason the [inliner will also move allocas from the callee into the caller's entry block](https://github.com/llvm/llvm-project/blob/290d7b82cb5d3fd9fb433ede0eef7f3a524d89cd/llvm/lib/Transforms/Utils/InlineFunction.cpp#L2813-L2816). This only impossible if the allocated size depends on computations in the caller (i.e. a variable-sized array), in which case the scope of the callee is surrounded by stacksave/stackrestore so the stack does not grow whenever the callee would have been called, as apparently happens in #120724. There must be no unbounded stack growth within a function unless the user calls `__builtin_alloca` manually.

You could technically have a statically sized alloca not in the entry-block if it is either surrounded by stacksave/stackrestore or guaranteed to be not in a loop, but optimization passes don't handle it well. When inserting stacksave/stackrestore ensuring (post-)dominance is also difficult (StackColoring may complain or just miscompile your code). This was e.g. a bug in Polly and I strongly suggest to stay away from it if not necessary.

See also the discussion here: https://discourse.llvm.org/t/why-is-llvm-stacksave-necessary/45724/7

**Comment by tblah** [comment]
Thank you for the detailed explanation Michael, that's very helpful for me.

**Comment by NimishMishra** [comment]
Thanks @Meinersbur for the detailed explanation. It really helps.

The latest commit uses AllocaIP to hoist the __atomic_load alloca out of the compare exchange loop. I checked the IR in presence of enclosing constructs like parallel, and no longer observe the issue (i.e. the alloca being hoisted to the entry block of main() function) which @tblah pointed out. Hope this is fine.

**Review by tblah — APPROVED** [review]
LGTM. Thank you for all of the updates. Wait for approval from Michael before merging.

@Meinersbur the alloca still doesn't make it into the entry block when generating LLVMIR for the example in https://github.com/llvm/llvm-project/issues/120724, but I think that's a separate bug in OpenMPToLLVMIRTranslation.cpp beyond the scope of this PR. If I run the IR through `opt -O3` the alloca is hoisted into the entry block. Is this okay with you?

**Review by Meinersbur — APPROVED** [review]
LGTM
