### PR TITLE
Minor unused variable error for sanitizer builds

### LINKED ISSUE #132371: Sanitizer Build : ASTReader.cpp error: unused variable 'I' [-Werror,-Wunused-variable]
```
sanitizer-aarch64-linux/build/llvm-project/clang/lib/Serialization/ASTReader.cpp:11764:17: error: unused variable 'I' [-Werror,-Wunused-variable]
 11764 |   for (unsigned I : llvm::seq<unsigned>(NumFlags))
```
Error in Sanitizer builds

### PR DESCRIPTION
**Pull request by chandraghale**
Fix #132371
Minor error ,  sanitizer builds are failing for unused variable.  
sanitizer-aarch64-linux/build/llvm-project/clang/lib/Serialization/ASTReader.cpp:11764:17: error: unused variable 'I' [-Werror,-Wunused-variable]
 11764 |   for (unsigned I : llvm::seq<unsigned>(NumFlags))

This was modified as part of [https://github.com/llvm/llvm-project/pull/129938](https://github.com/llvm/llvm-project/pull/129938) , which got missed.

### CODE REVIEW

**Review by frederick-vs-ja — APPROVED** [review]
Thanks! I modified the PR description so GitHub can automatically associate this PR with the issue.

File: clang/lib/Serialization/ASTReader.cpp [hunk 1]
```diff
@@ -11761,7 +11761,7 @@ void OMPClauseReader::VisitOMPReductionClause(OMPReductionClause *C) {
   unsigned NumFlags = Record.readInt();
   SmallVector<bool, 16> Flags;
   Flags.reserve(NumFlags);
-  for (unsigned I : llvm::seq<unsigned>(NumFlags))
+  for ([[maybe_unused]] unsigned I : llvm::seq<unsigned>(NumFlags))
```
Comment (zyn0217) [inline clang/lib/Serialization/ASTReader.cpp:11764]: Why don't turn to the very basic for-loop?
```cpp
for (unsigned I = 0; I < NumFlags; ++I)
```

Comment (chandraghale) [reply clang/lib/Serialization/ASTReader.cpp:11764]: @zyn0217 , well it was basic loop before :/  , based on alexey-bataev comment i changed it. basically i understand  it helps maintain consistency with other parts of the code .

Comment (zyn0217) [reply clang/lib/Serialization/ASTReader.cpp:11764]: Hum yeah, does it warn for  `for (auto _ : llvm::seq<unsigned>(NumFlags))` as well?

(Honestly I hate adding the `unused` attribute everywhere, it adds noise to the code)

Comment (chandraghale) [reply clang/lib/Serialization/ASTReader.cpp:11764]: it does

Comment (zyn0217) [reply clang/lib/Serialization/ASTReader.cpp:11764]: Well, let's go ahead as is.

**Review by zyn0217 — APPROVED** [review]
