### PR TITLE
[FunctionAttrs] Bail if initializes range overflows 64-bit signed int

### LINKED ISSUE #134115: FunctionAttrs: Assertion `isOrder edRanges(RangesRef)' failed.
```
$ cat /tmp/f.ll
define i32 @f(ptr %arg, ptr %arg2) {
  store ptr %arg, ptr %arg2
  %getelementptr = getelementptr float, ptr %arg, i64 2305843009213693951
  %load = load i32, ptr %getelementptr, align 4
  ret i32 %load
}
$ opt -p function-attrs /tmp/f.ll -disable-output
opt: ../../llvm/include/llvm/IR/ConstantRangeList.h:36: llvm::ConstantRangeList::ConstantRangeList(ArrayRef<ConstantRange>): Assertion `isOrder
edRanges(RangesRef)' failed.
```

### PR DESCRIPTION
**Pull request by aeubanks**
Otherwise the range doesn't make sense since we interpret it as signed.

Fixes #134115

### CODE REVIEW

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 1]
```diff
@@ -661,8 +661,12 @@ ArgumentAccessInfo getArgumentAccessInfo(const Instruction *I,
...
     if (!TypeSize.isScalable() && Offset) {
       int64_t Size = TypeSize.getFixedValue();
-      return ConstantRange(APInt(64, *Offset, true),
-                           APInt(64, *Offset + Size, true));
+      APInt Low(64, *Offset, true);
+      APInt High(64, *Offset + Size, true);
+      // Bail if the range overflows signed 64-bit int.
+      if (Low.sge(High))
+        return std::nullopt;
+      return ConstantRange(Low, High);
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp:669]: Check isSignWrappedSet() on the result instead?

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 2]
```diff
@@ -661,8 +661,12 @@ ArgumentAccessInfo getArgumentAccessInfo(const Instruction *I,
     auto TypeSize = DL.getTypeStoreSize(Ty);
     if (!TypeSize.isScalable() && Offset) {
       int64_t Size = TypeSize.getFixedValue();
-      return ConstantRange(APInt(64, *Offset, true),
-                           APInt(64, *Offset + Size, true));
+      APInt Low(64, *Offset, true);
+      APInt High(64, *Offset + Size, true);
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp:665]: This will probably still make ubsan unhappy for your test case?

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp (hunk 1 above)
Comment (aeubanks) [reply llvm/lib/Transforms/IPO/FunctionAttrs.cpp:670]: I didn't see this, thanks for pointing it out. Although I ended up just using `APInt::sadd_ov`

**Review by nikic — APPROVED** [review]
LGTM
