### PR TITLE
[clang-format] Revert "[clang-format][NFC] Delete TT_LambdaArrow (#70…

### LINKED ISSUE #105480: Clang-format: Trailing return type formatting regression starting from v18
I get a formatting "regression" starting from clang-format v18

```cpp
-    auto on_deactivate(rclcpp_lifecycle::State const & previous_state)
-        -> hardware_interface::CallbackReturn override;
+    auto on_deactivate(rclcpp_lifecycle::State const & previous_state
+    ) -> hardware_interface::CallbackReturn override;

-    auto register_group_bulk_write(Motor & m, std::vector<Motor *> & motor_write_list) const
-        -> bool;
+    auto
+    register_group_bulk_write(Motor & m, std::vector<Motor *> & motor_write_list) const -> +bool;
```

This is with `IndentBlock` on `AlignAfterOpenBracket` and I can't seem to be able to reproduce the previous formatting.

Config:

```
---
Language: Cpp
BasedOnStyle: LLVM

AccessModifierOffset: -4
AlignAfterOpenBracket: BlockIndent
AlignConsecutiveMacros: Consecutive
AlignEscapedNewlines: Left
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: true
AllowShortFunctionsOnASingleLine: None
AllowShortLambdasOnASingleLine: None
AlwaysBreakTemplateDeclarations: Yes
BinPackArguments: false
BinPackParameters: false
BraceWrapping:
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterExternBlock: false
  AfterFunction: true
  AfterNamespace: false
  AfterStruct: true
  AfterUnion: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: false
  BeforeWhile: true
  IndentBraces: false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: BeforeComma
BreakStringLiterals: false
ColumnLimit: 100
CompactNamespaces: true
IncludeBlocks: Regroup
IndentCaseLabels: true
IndentPPDirectives: BeforeHash
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: false
PackConstructorInitializers: CurrentLine
PenaltyBreakAssignment: 10
PenaltyBreakComment: 10
PointerAlignment: Middle
QualifierAlignment: Right
ReferenceAlignment: Middle
SeparateDefinitionBlocks: Always
SpacesInContainerLiterals: false
Standard: c++17
TabWidth: 4
...
```

### PR DESCRIPTION
**Pull request by owenca**
…519)"

This reverts commit e00d32afb9d33a1eca48e2b041c9688436706c5b and adds a test for lambda arrow SplitPenalty.

Fixes #105480.

### CODE REVIEW

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -3369,6 +3371,20 @@ TEST_F(TokenAnnotatorTest, GNULanguageStandard) {
...
+TEST_F(TokenAnnotatorTest, SplitPenalty) {
+  auto Style = getLLVMStyle();
+  Style.ColumnLimit = 20;
+
+  auto Tokens = annotate("class foo {\n"
+                         "  auto bar()\n"
+                         "      -> bool;\n"
+                         "};",
+                         Style);
+  ASSERT_EQ(Tokens.size(), 13u);
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:3383]:
```suggestion
  ASSERT_EQ(Tokens.size(), 13u) << Tokens;
```

**Review by HazardyKnusperkeks — APPROVED** [review]
