### PR TITLE
[OpenMP] Fix atomic compare handling with overloaded operators

### LINKED ISSUE #141085: [OpenMP] OpenMP atomic compare fails when including <array> with `using namespace std;`
The following code causes a compilation failure only when `using namespace std;`. https://godbolt.org/z/adKe7x84c.

```c++
using namespace std;

#include <array>

template<typename T>
T atomicMin(T* acc, T value)
{
  T old;
#pragma omp atomic capture compare
  {
    old = *acc;
    if (value < *acc)
    {
      *acc = value;
    }
  }
  return old;
}
```
```console
$ clang++ main.cpp -fopenmp
main.cpp:1:17: warning: using directive refers to implicitly-defined namespace 'std'
    1 | using namespace std;
      |                 ^
main.cpp:12:15: error: the statement for 'atomic compare capture' must be a compound statement of form '{v = x; cond-up-stmt}', ''{cond-up-stmt v = x;}', '{if(x == e) {x = d;} else {v = x;}}', '{r = x == e; if(r) {x = d;}}', or '{r = x == e; if(r) {x = d;} else {v = x;}}', where 'cond-update-stmt' can have one of the following forms: 'if(expr ordop x) {x = expr;}', 'if(x ordop expr) {x = expr;}', 'if(x == e) {x = d;}', or 'if(e == x) {x = d;}' where 'x', 'r', and 'v' are lvalue expressions with scalar type, 'expr', 'e', and 'd' are expressions with scalar type, and 'ordop' is one of '<' or '>'
   12 |     if (value < *acc)
      |         ~~~~~~^~~~~~
main.cpp:12:15: note: expect binary operator in conditional expression
   12 |     if (value < *acc)
      |         ~~~~~~^~~~~~
```

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
When there are overloaded C++ operators in the global namespace the AST
node for these is not a `BinaryExpr` but a `CXXOperatorCallExpr`. Modify
the uses to handle this case, basically just treating it as a binary
expression with two arguments.

Fixes https://github.com/llvm/llvm-project/issues/141085

### CODE REVIEW

File: clang/lib/Sema/SemaOpenMP.cpp [hunk 1]
```diff
@@ -11762,52 +11762,98 @@ bool OpenMPAtomicCompareChecker::checkCondUpdateStmt(IfStmt *S,
...
-      C = Cond;
-    } else if (checkIfTwoExprsAreSame(ContextRef, E, Cond->getLHS()) &&
-               checkIfTwoExprsAreSame(ContextRef, X, Cond->getRHS())) {
-      C = Cond;
-      IsXBinopExpr = false;
-    } else {
-      ErrorInfo.Error = ErrorTy::InvalidComparison;
-      ErrorInfo.ErrorLoc = ErrorInfo.NoteLoc = Cond->getExprLoc();
-      ErrorInfo.ErrorRange = ErrorInfo.NoteRange = Cond->getSourceRange();
+  } else if (auto *Call = dyn_cast<CXXOperatorCallExpr>(S->getCond())) {
```
Comment (shiltian) [inline clang/lib/Sema/SemaOpenMP.cpp:11806]: I don't think we should support this. We can't reliably lower non-trivial type at the moment.

Comment (jhuber6) [reply clang/lib/Sema/SemaOpenMP.cpp:11806]: We don't, this will get rejected later when the type is actually instantiated. This just prevents it from rejecting the format outright when it isn't even used, like in the associated test.

Comment (shiltian) [reply clang/lib/Sema/SemaOpenMP.cpp:11806]: but you can just check whether they are dependent type and call it a day?

Comment (jhuber6) [reply clang/lib/Sema/SemaOpenMP.cpp:11806]: Then these fields will be null and we'll trigger an assertion and we won't get any semantic checks.

Comment (shiltian) [reply clang/lib/Sema/SemaOpenMP.cpp:11806]: Okay, yeah, I'll need some input from @alexey-bataev since I'm not a front end expert.

File: clang/lib/Sema/SemaOpenMP.cpp [hunk 2]
```diff
@@ -12062,32 +12154,56 @@ bool OpenMPAtomicCompareCaptureChecker::checkForm3(IfStmt *S,
...
+    if (checkIfTwoExprsAreSame(ContextRef, X, Call->getArg(0))) {
+      E = Call->getArg(1);
+    } else if (checkIfTwoExprsAreSame(ContextRef, X, Call->getArg(1))) {
+      E = Call->getArg(0);
+    } else {
+      ErrorInfo.Error = ErrorTy::InvalidComparison;
+      ErrorInfo.ErrorLoc = ErrorInfo.NoteLoc = Call->getExprLoc();
+      ErrorInfo.ErrorRange = ErrorInfo.NoteRange = Call->getSourceRange();
+      return false;
+    }
```
Comment (jdoerfert) [inline clang/lib/Sema/SemaOpenMP.cpp:12200]: Here and above, I think we can reasonably make helpers. It can take things like
```
bool IsEqual, bool IsLT, ..., auto *LHS, auto *RHS
```
and check the conditions.

File: clang/test/OpenMP/atomic_messages.cpp [hunk 3]
```diff
@@ -991,3 +991,34 @@ int mixed() {
...
+  }
+#pragma omp atomic compare capture
+  {
+    cv = cx;
+    if (cx < ce) {
+      cx = ce;
+    }
+  }
+}
+#endif
```
Comment (jdoerfert) [inline clang/test/OpenMP/atomic_messages.cpp:1024]: We need a similar test as a codegen test as well.

File: clang/lib/Sema/SemaOpenMP.cpp (hunk 2 above)
Comment (jhuber6) [reply clang/lib/Sema/SemaOpenMP.cpp:12200]: I tried that but the switch statements required some kind of helper to abstract over the differing enum values. I could potentially just replace those with `if` and `else` that just did short circuiting or something I guess.

Comment (jhuber6) [reply clang/lib/Sema/SemaOpenMP.cpp]: Done

**Review by jdoerfert — APPROVED** [review]
LG
