### PR TITLE
fix: Target Process may crash or freezes on detaching process on windows

### LINKED ISSUE #67825: LLDB: Windows: attach them detach leaves the process in a suspended state
Hello

lldb version 17.0.1

Steps:
1. run any application, for example, lldb, and get pid of it
2. run lldb and attach by pid
3. detach (with parameter -s or without it)
4. try doing something in the application from the first step

Expected:
The application is functioning normally

Actual:
Application in a suspended state
image

### LINKED ISSUE #89077: TestDetachResumes fails on windows (arm?)
The test (added in #88494) fails precisely in the way it would fail if the inferior was *not* resumed after detaching. We don't have a x86-64 lldb bot right now, but it's a safe bet the issue is not architecture-specific.

### PR DESCRIPTION
**Pull request by anatawa12**
~~I hope this fixes~~ ~~#67825~~ ~~Actually a another issue, see [comment below](https://github.com/llvm/llvm-project/pull/115712#issuecomment-2470966129)~~

Fixes #67825 Fixes #89077

Fixes [RIDER-99436](https://youtrack.jetbrains.com/issue/RIDER-99436/Unity-Editor-will-be-crashed-when-detaching-LLDB-debugger-in-Rider), which is upstream issue of #67825.

This PR changes the timing of calling `DebugActiveProcessStop` to after calling `ContinueDebugEvent` for last debugger exception.

I confirmed the crashing behavior is because we call `DebugActiveProcessStop` before `ContinueDebugEvent` for last debugger exception with https://github.com/anatawa12/debug-api-test.

I have no idea how should I test this so I did not add tests. Could you let me know how should I test for this chages?

### CODE REVIEW

**Comment by labath** [comment]
So, it sounds like this is fixing test/API/commands/process/detach-resumes/TestDetachResumes.py (which is linked to #89077, which may be a dupe of the bug you're referencing), so the first step would be to figure out whether this test actually passes with your patch. Note that the test was never successfully run on windows, so you may need to tweak it a bit to make it windows compatible (I don't see anything that should be a problem for windows, but it's very easy for os assumptions to sneak in).

I'm not really familiar with windows APIs, but the change doesn't seem particularly controversial.

**Comment by anatawa12** [comment]
I tried to run `TestDetachResumes` but it fails (still in suspended state) so I may need some other work to them work correctly. I'll investigate more tomorrow.

**Comment by anatawa12** [comment]
After I changed debug-api-test, I found that calling DebugActiveProcessStop before ContinueDebugEvent will follow behavior specified by DebugSetProcessKillOnExit for some cases.

This PR only fixes this behavior, which is reported on Rider issue tracker as [RIDER-99436](https://youtrack.jetbrains.com/issue/RIDER-99436/Unity-Editor-will-be-crashed-when-detaching-LLDB-debugger-in-Rider).

It looks freezing in Suspended state, which are reported as #67825 and #89077, are completely different issue and not fixed with this PR.

**Comment by anatawa12** [comment]
I looked the process in suspended state with sysinternal process explorer and I found all threads have exactly one suspend count.
Therefore, I added logs to calling [SuspendThread] and [ResumeThread] and I found those calls are unbalanced exactly one for each thread so I think #67825 and #89077 are about calling [ResumeThread] and completely different problem.
I'm interested in #67825 but this is completely different bug so I'm going to create another Pull Request when I reached to fix.

**Comment by anatawa12** [comment]
I have implemented fix for #89077 and I checked test works on windows.

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp [hunk 1]
```diff
@@ -169,6 +169,38 @@ Status ProcessWindows::DoDetach(bool keep_stopped) {
...
+                 GetPrivateState());
+
+        LLDB_LOG(log, "resuming {0} threads for detach.",
+                 m_thread_list.GetSize());
+
+        bool failed = false;
+        for (uint32_t i = 0; i < m_thread_list.GetSize(); ++i) {
+          auto thread = std::static_pointer_cast<TargetThreadWindows>(
+              m_thread_list.GetThreadAtIndex(i));
+          Status result = thread->DoResume();
```
Comment (labath) [inline lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp:188]: Does this mean that if the thread/process gets another exception before we manage to detach from it, it will remain suspended? I'm not familiar with windows debugging API, so I don't know if there's a way to handle this, but I believe this is the reason why linux (and others) have a PTRACE_DETACH call which (atomically) detaches from a process/thread *and* resumes it.

**Review by labath — COMMENTED** [review]
Thank you for looking into this. So, from what I was able to gather, there are two issues/bugs here, but I'm having trouble figuring out what they are. Can you explain what's the difference between them? I'm trying to figure out if we can/should have a separate test case for the other bug.

**Comment by anatawa12** [comment]
> Can you explain what's the difference between them?

Sorry for confusion. I'll explain two bugs cleanly.

First of all, both bug must be fixed to pass `TestDetachResumes` test.

The first bug is the process may freeze in Suspended state on detaching process.
This bug is tracked as #67825.
It looks this only happens when we detached process without resuming process (continue command).

The second bug is the process may crash (killed)on detaching process.
It looks this bug is not tracked in llvm-project repository but I think [RIDER-99436] is experiencing this bug.
It looks this bug will always happen on detaching process.

Both bug will make the attached process unusable on detaching process, but the difference between two bug is what happens on detaching process.
The first bug make the process frozen in Suspended state, the later bug crashes the process.

[RIDER-99436]: https://youtrack.jetbrains.com/issue/RIDER-99436/Unity-Editor-will-be-crashed-when-detaching-LLDB-debugger-in-Rider

File: lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp (hunk 1 above)
Comment (anatawa12) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp:188]: > Does this mean that if the thread/process gets another exception before we manage to detach from it, it will remain suspended?

No, the process will not suspend.
The process will receive the exception and the process handles it instead.
For simple programs, it will crash the process but some process may handle in their way.
We can see this behavior with TestDetachResumes by reverting 5ad1a98a8b07e1d75829870995fbf36fb8cb99ed.

> I'm not familiar with windows debugging API, so I don't know if there's a way to handle this, but I believe this is the reason why linux (and others) have a PTRACE_DETACH call which (atomically) detaches from a process/thread _and_ resumes it.

I agree with that but as far as I researched I could not figure out the API to detach and resume thread simultaneously.

Comment (anatawa12) [reply lldb/source/Plugins/Process/Windows/Common/ProcessWindows.cpp:188]: It's True, (as far as I know)

**Comment by labath** [comment]
Just one more clarification. I'm sorry for this takes so long, but I'm not familiar with the windows debugging API, which means that I might not be getting some of the things that are obvious. I just want to make sure I understand what's happening here.

> The first bug is the process may freeze in Suspended state on detaching process.

Okay, I think I understand this part. The process is "suspended" by the breakpoint and detaching from it does not automatically resume it.

> The second bug is the process may crash (killed)on detaching process.

I'm less sure about this one. Is that due to the breakpoint exception somehow remaining "pending" and that we need to clear/ignore/suppress it before detaching?

**Comment by anatawa12** [comment]
> I'm less sure about this one. Is that due to the breakpoint exception somehow remaining "pending" and that we need to clear/ignore/suppress it before detaching?

Sorry I don't know the reason of this behavior, but not calling corresponding ContinueDebugEvent for WaitForDebugEvent may cause crash is what I know.

It looks leaving some "pending" events / exceptions in queue doesn't trigger problem, but leaving "processing" events / exceptions would cause this problem.

---

I misunderstand the behavior a little. 

Sorry for confusion again.
In my previous comment, I said "It think this bug will always happen on detaching process" for second bug but I found that this bug depends on the implementation of target process and a.out from TestDetachResumes would not have this problem.
I fixed the previous comment.

**Review by labath — APPROVED** [review]
Okay, I think I'm satisfied by the explanation. Thanks for your patience. Do you need me to push the "merge" button?

**Comment by anatawa12** [comment]
> Do you need me to push the "merge" button?

Yes please. I don't have merge button.
