### PR TITLE
[libc][i386] FPBit support for 96b long double

### LINKED ISSUE #110894: [llvm-libc] support for 96b long double (i386)
building llvm-libc for i386 fails to build in the printf code; it seems that `sizeof(long double)` on i386 is `12`.  example:
```
In file included from /android0/llvm-project/libc/src/stdio/printf_core/converter.cpp:9:
In file included from /android0/llvm-project/libc/src/stdio/printf_core/converter.h:13:
In file included from /android0/llvm-project/libc/src/stdio/printf_core/core_structs.h:16:
/android0/llvm-project/libc/src/__support/FPUtil/FPBits.h:824:52: error: no matching function for call to 'bit_cast'
  824 |   LIBC_INLINE constexpr T get_val() const { return cpp::bit_cast<T>(UP::bits); }
      |                                                    ^~~~~~~~~~~~~~~~
/android0/llvm-project/libc/src/stdio/printf_core/float_dec_converter.h:502:47: note: in instantiation of member function '__llvm_libc_19_0_0_git::fputil::FPBits<long double>::get_val' requested here
  502 |   FloatToString<T> float_converter(float_bits.get_val());
      |                                               ^
/android0/llvm-project/libc/src/stdio/printf_core/float_dec_converter.h:1116:14: note: in instantiation of function template specialization '__llvm_libc_19_0_0_git::printf_core::convert_float_decimal_typed<long double, 0>' requested here
 1116 |       return convert_float_decimal_typed<long double>(writer, to_conv,
      |              ^
/android0/llvm-project/libc/src/__support/CPP/bit.h:38:1: note: candidate template ignored: substitution failure [with To = long double, From = StorageType]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
   38 | bit_cast(const From &from) {
      | ^
/android0/llvm-project/libc/src/__support/big_int.h:1099:1: note: candidate template ignored: substitution failure [with To = long double, From = StorageType]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
 1099 | bit_cast(const From &from) {
      | ^
/android0/llvm-project/libc/src/__support/big_int.h:1114:1: note: candidate template ignored: substitution failure [with To = long double, Bits = 128]: implicit instantiation of undefined template '__llvm_libc_19_0_0_git::cpp::enable_if<false, long double>'
 1114 | bit_cast(const UInt<Bits> &from) {
      | ^
```

perhaps the `StorageType` for `FPLayout<FPType::X86_Binary80>` should be a 96b `UInt` for i386, but that leads to other errors?

Filing a bug to track this, as it's a blocker for i386 support.

cc @michaelrj-google

### PR DESCRIPTION
**Pull request by nickdesaulniers**
`long double` is haunted on most architectures, but it is especially so on
i386-linux-gnu. While have 80b of significant data, on i386-linux-gnu this type
has 96b of storage.

Fixes for supporting printf family of conversions for `long double` on
i386-linux-gnu. This allows the libc-stdlib-tests and libc_stdio_unittests
ninja target tests to pass on i386-linux-gnu.

Fixes: #110894
Link: #93709
Link: https://developer.android.com/ndk/guides/abis
Co-authored-by: Michael Jones <michaelrj@google.com>

### CODE REVIEW

File: libc/src/__support/FPUtil/FPBits.h [hunk 1]
```diff
@@ -127,7 +127,11 @@ template <> struct FPLayout<FPType::IEEE754_Binary128> {
 };
 
 template <> struct FPLayout<FPType::X86_Binary80> {
+#if __SIZEOF_LONG_DOUBLE__ == 16
   using StorageType = UInt128;
+#else
```
Comment (nickdesaulniers) [inline libc/src/__support/FPUtil/FPBits.h:132]: Thinking ahead to android support, if android uses `long double == double` (https://developer.android.com/ndk/guides/abis#x86) https://godbolt.org/z/e35cEK4fM, then perhaps this aught to be an explicit check for `__SIZEOF_LONG_DOUBLE__ == 12` with an `#else` clause that errors explicitly so that we get a nice build failure if we tried to build llvm-libc using the android triple, and we could investigate proper `long double == double` support.

File: libc/src/__support/big_int.h [hunk 2]
```diff
@@ -469,7 +469,7 @@ struct BigInt {
                                                     !cpp::is_same_v<T, bool>>>
   LIBC_INLINE constexpr BigInt(T v) {
     constexpr size_t T_SIZE = sizeof(T) * CHAR_BIT;
-    const bool is_neg = Signed && (v < 0);
+    const bool is_neg = v < 0;
```
Comment (nickdesaulniers) [inline libc/src/__support/big_int.h:472]: I should add a test case to libc/test/src/__support/big_int_test.cpp that demonstrates _why_ this change is necessary.

Comment (nickdesaulniers) [reply libc/src/__support/big_int.h:472]: https://github.com/llvm/llvm-project/pull/115084/commits/be223620e9c8466ca88e4b4f3cf06ce92cfe329f

File: libc/src/__support/FPUtil/FPBits.h (hunk 1 above)
Comment (nickdesaulniers) [reply libc/src/__support/FPUtil/FPBits.h]: https://github.com/llvm/llvm-project/pull/115084/commits/474aad73d1213340663ceb631ba2c78ef774b9ca

**Comment by nickdesaulniers** [comment]
In attempting to add some math.h entrypoints, I'm hitting other compilation failures related to FPBits. Let me see if I can get those sorted, and add them to this PR.

File: libc/src/__support/FPUtil/FPBits.h [hunk 3]
```diff
@@ -127,7 +127,18 @@ template <> struct FPLayout<FPType::IEEE754_Binary128> {
...
 template <> struct FPLayout<FPType::X86_Binary80> {
+// x86_64
+#if __SIZEOF_LONG_DOUBLE__ == 16
   using StorageType = UInt128;
+// i386-linux-gnu
+#elif __SIZEOF_LONG_DOUBLE__ == 12
+  using StorageType = UInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT>;
+#else
+# TODO: https://github.com/llvm/llvm-project/issues/115184
+# Android i386 uses `long double == double` i.e. `sizeof(long double) == 8`
```
Comment (lntue) [inline libc/src/__support/FPUtil/FPBits.h:138]: I think you should add extra android i386 condition to https://github.com/llvm/llvm-project/blob/main/libc/src/__support/macros/properties/types.h#L24

Comment (nickdesaulniers) [reply libc/src/__support/FPUtil/FPBits.h:138]: For android, `#define __LDBL_MANT_DIG__ 53`: https://godbolt.org/z/M61Edn5c4, which falls into the first existing case.

**Comment by nickdesaulniers** [comment]
I'm hitting an issue with 2 math tests failing at runtime (libc.src.math.ddivl, libc.src.math.fdivl). I'm not sure yet if it's a bug in this PR, or another I'm working on for saving/restoring the fpenv_t.  Will diagnose more tomorrow.

**Comment by nickdesaulniers** [comment]
Strange, I've pushed to my branch, but this PR hasn't updated. At the top, there's a spinner I've never seen before that says "Processing Updates" which onhover says "Recent push is still being processed, and will show up in a bit".  Perhaps a rebase + force push to "unstick it?"

image

**Comment by nickdesaulniers** [comment]
force push seemed to have cleared the issue. Ready for rereview

File: libc/src/__support/FPUtil/FPBits.h [hunk 4]
```diff
@@ -127,7 +127,18 @@ template <> struct FPLayout<FPType::IEEE754_Binary128> {
...
+// x86_64
+#if __SIZEOF_LONG_DOUBLE__ == 16
   using StorageType = UInt128;
+// i386-linux-gnu
+#elif __SIZEOF_LONG_DOUBLE__ == 12
+  using StorageType = UInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT>;
+#else
+// TODO: https://github.com/llvm/llvm-project/issues/115184
+// Android i386 uses `long double == double` i.e. `sizeof(long double) == 8`
+// https://developer.android.com/ndk/guides/abis#x86
```
Comment (lntue) [inline libc/src/__support/FPUtil/FPBits.h:139]: Now that thinking more about it, I would like to dictate using `UInt128` for 80-bit floating point whenever `__SIZEOF_LONG_DOUBLE__ != 12`.  So that when we emulate 80-bit floating points on targets other than i386, we will always use 128-bit.  For Android, Windows, and MacOS where long double is double, it will be taken care of by `LIBC_TYPES_LONG_DOUBLE_IS_DOUBLE`, and so this specialization is not used for `FPBits<long double>`.

Comment (nickdesaulniers) [reply libc/src/__support/FPUtil/FPBits.h:139]: As in:
```diff
diff --git a/libc/src/__support/FPUtil/FPBits.h b/libc/src/__support/FPUtil/FPBits.h
index 2994febff2f8..98e7eef90d43 100644
--- a/libc/src/__support/FPUtil/FPBits.h
+++ b/libc/src/__support/FPUtil/FPBits.h
@@ -127,7 +127,7 @@ template <> struct FPLayout<FPType::IEEE754_Binary128> {
 };
 
 template <> struct FPLayout<FPType::X86_Binary80> {
-#if __SIZEOF_LONG_DOUBLE__ == 16
+#if __SIZEOF_LONG_DOUBLE__ == 16 || __SIZEOF_LONG_DOUBLE__ == 8
   using StorageType = UInt128;
 #else
   using StorageType = UInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT>;
```
I can build android (`-DLIBC_TARGET_TRIPLE=i386-linux-android`) fine with that change.

Comment (lntue) [reply libc/src/__support/FPUtil/FPBits.h:139]: as:
```
#if __SIZEOF_LONG_DOUBLE__ == 12
  using StorageType = UInt<__SIZEOF_LONG_DOUBLE__ * CHAR_BIT>;
#else
  using StorageType = UInt128;
#endif
```

Comment (nickdesaulniers) [reply libc/src/__support/FPUtil/FPBits.h]: done in ab6deee4f4e1 PTAL

**Review by lntue — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]
