### PR TITLE
[clang-include-cleaner] Fix incorrect directory issue for writing files

### LINKED ISSUE #110843: clang-include-cleaner: Failed to apply edits ... No such file or directory
intput: ./include-cleaner -p out/Default --edit myfolder/myfile.cc
output: Failed to apply edits to ../../myfolder/myfile.cc: '../../myfolder/myfile.cc': No such file or directory

This was working well in August.
Note that using '--print=changes' instead of '--edit' works well.

### PR DESCRIPTION
**Pull request by bc-lee**
If the current working directory of `clang-include-cleaner` differs from the directory of the input files specified in the compilation database, it doesn't adjust the input file paths properly. As a result, `clang-include-cleaner` either writes files to the wrong directory or fails to write files altogether.

This pull request fixes the issue by adjusting the input file paths based on the directory specified in the compilation database. If that directory is not writable, `clang-include-cleaner` will write the output relative to the current working directory.

Fixes #110843.

### CODE REVIEW

**Comment by bc-lee** [comment]
@kadircet @hokein Could you please review this PR? It is related to #102615. More details are provided in the related issue. Thanks!

**Review by kadircet — CHANGES_REQUESTED** [review]
thanks a lot for the patch, and sorry for regressing this.

I think this is also going to regress behavior in some cases (e.g. working directory in compile commands might be virtual for some build systems like bazel).

When include-cleaner is invoked as `clang-include-cleaner foo.cc` the user is definitely trying to run this on a file relative to directory in which we invoked include-cleaner, hence we should make sure it's adressed through that path going forward.

Can we instead update logic near the following in `main`:
```cpp
 clang::tooling::ClangTool Tool(OptionsParser->getCompilations(),
                                 OptionsParser->getSourcePathList());
```

instead of passing `OptionsParser->getSourcePathList())`, we can turn all of these source paths into absolue paths, using the current-working-dir of the process, and then we don't need to worry about how they make their way into our ast-consumer.

**Comment by bc-lee** [comment]
Could you provide a minimal reproducer for this case if possible? Ideally, it should not depend on Google's internal Bazel setup or tools. From what I understand, Bazel itself doesn’t generate compilation databases, and third-party tools adjust the paths of raw compiler invocations to the correct ones. I tested two methods for generating compilation databases for Bazel projects in my demo repository (https://github.com/bc-lee/test-compilation-database), and both methods correctly generated the compilation databases, with no issues traversing over the Bazel build directory.

For instance, when I ran [kiron1/bazel-compile-commands](https://github.com/kiron1/bazel-compile-commands) in my demo repository, it generated the following `compile_commands.json`:

<details>
<summary>Click to toggle</summary>

```json
[
  {
    "directory": "/home/leebc/.cache/bazel/_bazel_leebc/5ea2deb937e75f0bf29ba4c49931e67d/execroot/_main",
    "command": "/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++14 -MD -MF bazel-out/k8-fastbuild/bin/api/_objs/main/main.pic.d -frandom-seed=bazel-out/k8-fastbuild/bin/api/_objs/main/main.pic.o -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -std=c++17 -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -c api/main.cc -o bazel-out/k8-fastbuild/bin/api/_objs/main/main.pic.o",
    "file": "api/main.cc",
    "output": "bazel-out/k8-fastbuild/bin/api/_objs/main/main.pic.o"
  }
]
```

</details>

And `clang-include-cleaner` ran correctly. The file path was `api/main.cc`, and the compiler invocation’s working directory was `/home/leebc/.cache/bazel/_bazel_leebc/5ea2deb937e75f0bf29ba4c49931e67d/execroot/_main`, so `clang-include-cleaner` correctly adjusted the path to `/home/leebc/.cache/bazel/_bazel_leebc/5ea2deb937e75f0bf29ba4c49931e67d/execroot/_main/api/main.cc`, which was correctly symlinked.

If there are any other cases that I missed, please let me know. I’ll try to reproduce the issue and fix it.

**Comment by kadircet** [comment]
> so clang-include-cleaner correctly adjusted the path to /home/leebc/.cache/bazel/_bazel_leebc/5ea2deb937e75f0bf29ba4c49931e67d/execroot/_main/api/main.cc, which was correctly symlinked.

in our case this is symlinked to an immutable copy of the source file (to make sure builds don't act weird if you edit some sources while the build is running). hence it'll be a regression.

What's the concern about not performing this directly as relative to the process' working directory? That approach doesn't rely on any assumptions about the build system, or filesystem layout hence feels much more robust.

**Comment by bc-lee** [comment]
> in our case this is symlinked to an immutable copy of the source file (to make sure builds don't act weird if you edit some sources while the build is running). hence it'll be a regression.
> 
> What's the concern about not performing this directly as relative to the process' working directory? That approach doesn't rely on any assumptions about the build system, or filesystem layout hence feels much more robust.

It’s unfortunate that we can't apply unified logic for determining the actual output file. It's especially disappointing given that I’m using GN and you’re using Bazel, both of which are build systems from Google.

I’ve adjusted the logic to find the correct output directory before the compiler invocation starts. Please take another look and let me know if there's anything else I should consider.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 1]
```diff
@@ -305,7 +342,32 @@ int main(int argc, const char **argv) {
     }
   }
 
-  clang::tooling::ClangTool Tool(OptionsParser->getCompilations(),
+  auto &CompilationDatabase = OptionsParser->getCompilations();
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:345]: i think this can be simplified with something like:
```
auto VFS = llvm::vfs::getRealFileSystem();
auto &CDB = OptionsParser->getCompilations();
std::map<std::string, std::string> CDBToAbsPaths;
for (auto &Source : OptionsParser->getSourcePathList()) {
  llvm::SmallString<256> AbsPath(Source);
  if (auto Err = VFS.makeAbsolute(AbsPath)) {
      llvm::errs() << "Failed to get absolute path for " << Source << " : " <<  Err.message() << '\n';
      return 1;
  }
  for(auto Cmd : CDB.getCompilecommands(AbsPath)) {
    llvm::SmallString<256> CDBPath(Cmd.Filename);
    llvm::sys::fs::make_absolute(Cmd.Directory, CDBPath);
    CDBToAbsPaths[CDBPath] = AbsPath;
  }
}
....
if (Edit) {
  for (const auto &NameAndContent : Factory.editedFiles()) {
     llvm::StringRef FileName = NameAndContent.first();
     if (auto It = CDBToAbsPaths.find(FileName); It != CDBToAbsPaths.end())
         FileName = It->second;
     ...
  }
}
```

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 2]
```diff
@@ -173,6 +173,7 @@ class Action : public clang::ASTFrontendAction {
     if (!HTMLReportPath.empty())
       writeHTML();
 
+    // Source File's path relative to compilation database.
     llvm::StringRef Path =
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:177]: can we keep reporting with abs-paths here, i.e:
```
llvm::SmallString<256> AbsPath(SM.getFileEntryRefForID(SM.getMainFileID())->getName());
SM.getFileManager().makeAbsolutePath(AbsPath);
...
```

This way we can recognize these paths in main and perform the mapping accordingly.

**Review by kadircet — COMMENTED** [review]
thanks a lot for the revision!

One concern is, we can't really use `getAllCompileCommands()` reliably either, not all compilation databases implement that, and even if they do this is gonna be an overkill. For example for chromium we'll iterate over tens of thousands of compile flags, just to modify a handful of files. I've made some suggestions in line.

Also I think it's easier if we put absolute-paths from CDB into the `EditedFiles` and just remap them to absolute paths per tools working directory afterwards when we can.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp (hunk 1 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: I didn't simplify it much, but I tried to explain my intent as clearly as possible. However, I feel the code is somewhat verbose.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 3]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
+            llvm::errs() << "Failed to find a writable path for " << Source
+                         << '\n';
+            return 1;
+          }
+        }
+        CDBToAbsPaths[static_cast<std::string>(CDBPath)] =
+            static_cast<std::string>(FilePath);
+      }
+    }
+  }
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:385]: `llvm::sys::fs::make_absolute(Cmd.Directory, CDBPath);` already performs concatenation only if `CDBPath` is not an absolute path, you don't re-implement all of this.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 4]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
+      }
+      // We only need the first command to get the directory.
+      auto Cmd = Cmds[0];
+      llvm::SmallString<256> CDBPath(Cmd.Filename);
+      std::string Directory(Cmd.Directory);
+
+      if (llvm::sys::path::is_absolute(CDBPath)) {
+        // If the path in the compilation database is already absolute, we don't
+        // need to do anything.
+        CDBToAbsPaths[static_cast<std::string>(CDBPath)] =
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:352]: we prefer `std::string(CDBPath)` or `CDBPath.str().str()` to `static_cast`. (also for other occurences of `static_cast`)

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 5]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
+            static_cast<std::string>(AbsPath);
+      } else {
+        auto Sept = llvm::sys::path::get_separator();
+        // First, try to find the file based on the compilation database.
+        llvm::Twine FilePathTwine = Directory + Sept + CDBPath;
+        llvm::SmallString<256> FilePath;
+        FilePathTwine.toVector(FilePath);
+        // Check if it is writable.
+        if (llvm::sys::fs::access(FilePath, llvm::sys::fs::AccessMode::Write) !=
+            std::error_code()) {
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:362]: i don't see why we need to complicate the logic by checking for this. is there any reasons to not always map to file-path relative to current process?

i am pretty convinced that the user intention is to almost always edit the file path as referred to during invocation, e.g. `cd /foo && clang-include-cleaner path/to/foo.cc` is always meant to edit `/foo/path/to/foo.cc` no matter what file path we get from CDB.

i can see how this might also work, but I prefer to maintain code that has as few special cases as possible. so unless something is indeed breaking with this simplification, can you please get rid of this case?

File: clang-tools-extra/include-cleaner/test/tool.cpp [hunk 6]
```diff
@@ -48,3 +48,13 @@ int x = foo();
 //        RUN: clang-include-cleaner -edit --ignore-headers="foobar\.h,foo\.h" %t.cpp -- -I%S/Inputs/ 
 //        RUN: FileCheck --match-full-lines --check-prefix=EDIT2 %s < %t.cpp
 //  EDIT2-NOT: {{^}}#include "foo.h"{{$}}
+
+//        RUN: mkdir -p $(dirname %t)/out
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/test/tool.cpp:55]: you can use `%T` instead of `dirname %t`, you can find full list in https://llvm.org/docs/CommandGuide/lit.html#substitutions, same below.

also it's safer to run a `rm -rf %T` beforehand to make sure we're starting clean

File: clang-tools-extra/include-cleaner/test/tool.cpp [hunk 7]
```diff
@@ -49,12 +49,15 @@ int x = foo();
 //        RUN: FileCheck --match-full-lines --check-prefix=EDIT2 %s < %t.cpp
 //  EDIT2-NOT: {{^}}#include "foo.h"{{$}}
 
+// This test has commands that rely on shell capabilities that won't execute
+// correctly on Windows e.g. subshell execution
+//   REQUIRES: shell
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/test/tool.cpp:54]: this doesn't just affect that particular run, affects the whole, can you move the test into its own file ?

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 8]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
   }
 
-  clang::tooling::ClangTool Tool(OptionsParser->getCompilations(),
-                                 OptionsParser->getSourcePathList());
+  auto VFS = llvm::vfs::getRealFileSystem();
+  auto &CDB = OptionsParser->getCompilations();
+  // CDBToAbsPaths is a map from the path in the compilation database to the
+  // writable absolute path of the file.
+  std::map<std::string, std::string> CDBToAbsPaths;
+  if (Edit) {
```
[the remark this answers is not in the document]
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: Done. Removed the check for Edit mode.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 9]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
+      }
+      std::vector<clang::tooling::CompileCommand> Cmds =
+          CDB.getCompileCommands(AbsPath);
+      if (Cmds.empty()) {
+        // Try with the original path.
+        Cmds = CDB.getCompileCommands(Source);
+        if (Cmds.empty()) {
+          continue;
+        }
+      }
```
[the remark this answers is not in the document]
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: Done. I checked, and even if we don't specify a compilation database, clang will create one using the `FixedCompilationDatabase` class. So, I added an error and return early if the compilation database can't be found.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 10]
```diff
@@ -305,8 +307,84 @@ int main(int argc, const char **argv) {
...
+      // We only need the first command to get the directory.
+      auto Cmd = Cmds[0];
```
[the remark this answers is not in the document]
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: Done.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp (hunk 3 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: Done.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp (hunk 4 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: Done.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp (hunk 5 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp]: It turns out we don't need to check for this. I removed those checks.

File: clang-tools-extra/include-cleaner/test/tool.cpp (hunk 6 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/test/tool.cpp]: It turns out `%T` is also deprecated. I replaced my shell invocation with `%t.dir`, as this is the recommended method, as described in [https://reviews.llvm.org/D69572](https://reviews.llvm.org/D69572). I also slightly modified the test invocation so that it works on Windows as well. (Tested on a local Windows machine.)

File: clang-tools-extra/include-cleaner/test/tool.cpp (hunk 7 above)
Comment (bc-lee) [reply clang-tools-extra/include-cleaner/test/tool.cpp]: This was explained in the previous comment. It now works on Windows as well.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 11]
```diff
@@ -305,8 +307,46 @@ int main(int argc, const char **argv) {
...
   }
 
-  clang::tooling::ClangTool Tool(OptionsParser->getCompilations(),
-                                 OptionsParser->getSourcePathList());
+  auto VFS = llvm::vfs::getRealFileSystem();
+  auto &CDB = OptionsParser->getCompilations();
+  // CDBToAbsPaths is a map from the path in the compilation database to the
+  // writable absolute path of the file.
+  std::map<std::string, std::string> CDBToAbsPaths;
+  // if Edit is enabled, `Factory.editedFiles()` will contain the final code,
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:315]: can you also drop the mention of `Edit` from the comment?

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 12]
```diff
@@ -305,8 +307,46 @@ int main(int argc, const char **argv) {
...
+    if (auto Err = VFS->makeAbsolute(AbsPath)) {
+      llvm::errs() << "Failed to get absolute path for " << Source << " : "
+                   << Err.message() << '\n';
+      return 1;
+    }
+    std::vector<clang::tooling::CompileCommand> Cmds =
+        CDB.getCompileCommands(AbsPath);
+    if (Cmds.empty()) {
+      // Try with the original path.
+      Cmds = CDB.getCompileCommands(Source);
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:331]: this fallback is still not needed. if we can't find the flags with absolute path, it's fine to bail out.

File: clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp [hunk 13]
```diff
@@ -305,8 +307,46 @@ int main(int argc, const char **argv) {
...
+        return 1;
+      }
+    }
+    for (const auto &Cmd : Cmds) {
+      llvm::SmallString<256> CDBPath(Cmd.Filename);
+      std::string Directory(Cmd.Directory);
+      llvm::sys::fs::make_absolute(Cmd.Directory, CDBPath);
+      CDBToAbsPaths[std::string(CDBPath)] = std::string(AbsPath);
+    }
+  }
```
Comment (kadircet) [inline clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:347]: nit: you can extract all of this logic to a helper function:
```cpp
llvm::Expected<std::map<...>> mapInputsToAbsPaths(...);
...
int main(...) {
  ...
  auto CDBToAbsPaths = mapInputsToAbsPaths(CDB, Opts->OptionsParser->getSourcePathList());
  if (!CDBToAbsPaths) {
    return 1;
  }
  ...
}

**Review by kadircet — APPROVED** [review]
thanks for bearing with me, LGTM!

**Comment by bc-lee** [comment]
Thanks for the review!

**Comment by kadircet** [comment]
btw, LMK if you don't have commit access and I should merge this for you

**Comment by bc-lee** [comment]
I don't have commit access to LLVM. Please merge this PR. Thanks!

**Comment by bc-lee** [comment]
I will fix the following error within an hour (currently away from keyboard).

```
FAILED: tools/clang/tools/extra/include-cleaner/tool/CMakeFiles/clang-include-cleaner.dir/IncludeCleaner.cpp.o 
ccache /home/docker/llvm-external-buildbots/clang.17.0.6/bin/clang++ --gcc-toolchain=/gcc-toolchain/usr -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_STATIC -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/build/tools/clang/tools/extra/include-cleaner/tool -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/tool -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang/include -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/build/tools/clang/include -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/build/include -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/llvm/include -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/include -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/tool/../lib -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/clang/tools/extra/include-cleaner/tool/CMakeFiles/clang-include-cleaner.dir/IncludeCleaner.cpp.o -MF tools/clang/tools/extra/include-cleaner/tool/CMakeFiles/clang-include-cleaner.dir/IncludeCleaner.cpp.o.d -o tools/clang/tools/extra/include-cleaner/tool/CMakeFiles/clang-include-cleaner.dir/IncludeCleaner.cpp.o -c /home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp
/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:302:14: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
  302 |       return std::move(llvm::errorCodeToError(Err));
      |              ^
/home/buildbots/llvm-external-buildbots/workers/ppc64le-clang-rhel-test/clang-ppc64le-rhel/llvm-project/clang-tools-extra/include-cleaner/tool/IncludeCleaner.cpp:302:14: note: remove std::move call here
  302 |       return std::move(llvm::errorCodeToError(Err));
      |              ^~~~~~~~~~                           ~
1 error generated.
```
