### PR TITLE
[libc] Added support for fixed-points in ``is_signed`` and ``is_unsigned``.

### LINKED ISSUE #133365: [libc] ``std::is_signed_v<T>`` for any fixed-point always returns ``false``
``std::is_signed_v<T>`` always returns ``false`` for any fixed-point, irrespective whether the fixed-point is signed or unsigned.

### PR DESCRIPTION
**Pull request by kr-2003**
Fixes #133365

## Changes Done
- Changed the signed checking to 
```cpp
struct is_signed : bool_constant<((is_fixed_point<T> || is_arithmetic_v<T>) && (T(-1) < T(0)))>
```
in ``/libc/src/__support/CPP/type_traits/is_signed.h``. Added check for fixed-points.
- But, got to know that this will fail for ``unsigned _Fract`` or any unsigned fixed-point because ``unsigned _Fract`` can’t represent -1 in T(-1), while ``unsigned int`` can handle it via wrapping.
- That's why I explicity added ``is_signed`` check for ``unsigned`` fixed-points.
- Same changes to ``/libc/src/__support/CPP/type_traits/is_unsigned.h``.
- Added tests for ``is_signed`` and ``is_unsigned``.

### CODE REVIEW

File: libc/src/__support/CPP/type_traits/is_signed.h [hunk 1]
```diff
@@ -10,18 +10,73 @@
...
 #include "src/__support/macros/config.h"
 
 namespace LIBC_NAMESPACE_DECL {
 namespace cpp {
 
-// is_signed
+// Primary template: handles arithmetic and signed fixed-point types
 template <typename T>
-struct is_signed : bool_constant<(is_arithmetic_v<T> && (T(-1) < T(0)))> {
+struct is_signed : bool_constant<((is_fixed_point_v<T> || is_arithmetic_v<T>) &&
```
Comment (lntue) [inline libc/src/__support/CPP/type_traits/is_signed.h:22]: probably you could change it to:
```
(is_fixed_point_v<T> && T(-0.5) < T(0)) || (is_arithmetic_v<T> && T(-1) < T(0))
```
and remove all the fixed point specializations.

Comment (kr-2003) [reply libc/src/__support/CPP/type_traits/is_signed.h:22]: it won't work. even if the value is just less than 0, it will try to wrap around in unsigned type(and its not possible in fixed-points). I have tried it out.

File: libc/src/__support/CPP/type_traits/is_signed.h [hunk 2]
```diff
@@ -8,20 +8,98 @@
...
 namespace LIBC_NAMESPACE_DECL {
 namespace cpp {
 
-// is_signed
+// Primary template: handles arithmetic and signed fixed-point types
 template <typename T>
 struct is_signed : bool_constant<(is_arithmetic_v<T> && (T(-1) < T(0)))> {
   LIBC_INLINE constexpr operator bool() const { return is_signed::value; }
   LIBC_INLINE constexpr bool operator()() const { return is_signed::value; }
 };
```
Comment (lntue) [inline libc/src/__support/CPP/type_traits/is_signed.h:26]: So I just tested locally, and the following seems to work without all the specializations:
```
struct is_signed : bool_constant<
    (is_fixed_point_v<T> && T(-0.5) < T(0)) ||
    (is_arithmetic_v<T> && (T(-1) < T(0)))> {
    ...
};
```

**Comment by PiJoules** [comment]
I think we'll want the saturated version of each of these also

File: libc/src/__support/CPP/type_traits/is_signed.h (hunk 2 above)
Comment (kr-2003) [reply libc/src/__support/CPP/type_traits/is_signed.h:26]: really? i think i am missing out on something, because this is what i get when i try this on my machine:
```bash
/Users/abhinavkumar/Desktop/Coding/CERN_HSF_COMPILER_RESEARCH/llvm-project/libc/src/__support/CPP/type_traits/is_signed.h:23:34: error: non-type template argument is not a constant expression
   23 | struct is_signed : bool_constant<(is_fixed_point_v<T> && T(-0.5) < T(0)) ||
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   24 |                                  (is_arithmetic_v<T> && (T(-1) < T(0)))> {
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/abhinavkumar/Desktop/Coding/CERN_HSF_COMPILER_RESEARCH/llvm-project/libc/src/__support/CPP/type_traits/is_signed.h:105:46: note: in instantiation of template class '__llvm_libc_21_0_0_git::cpp::is_signed<unsigned _Fract>' requested here
  105 | LIBC_INLINE_VAR constexpr bool is_signed_v = is_signed<T>::value;
      |                                              ^
/Users/abhinavkumar/Desktop/Coding/CERN_HSF_COMPILER_RESEARCH/llvm-project/libc/test/src/__support/CPP/type_traits_test.cpp:427:17: note: in instantiation of variable template specialization '__llvm_libc_21_0_0_git::cpp::is_signed_v<unsigned _Fract>' requested here
  427 |   EXPECT_FALSE((is_signed_v<unsigned fract>));
/Users/abhinavkumar/Desktop/Coding/CERN_HSF_COMPILER_RESEARCH/llvm-project/libc/src/__support/CPP/type_traits/is_signed.h:23:60: note: value 0.0 is outside the range of representable values of type 'unsigned _Fract'
   23 | struct is_signed : bool_constant<(is_fixed_point_v<T> && T(-0.5) < T(0)) ||
  ```

File: libc/src/__support/CPP/type_traits/is_signed.h (hunk 1 above)
Comment (lntue) [reply libc/src/__support/CPP/type_traits/is_signed.h]: @PiJoules is there problem with constexpr for fixed point type in clang?

File: libc/src/__support/CPP/type_traits/is_signed.h (hunk 2 above)
Comment (lntue) [reply libc/src/__support/CPP/type_traits/is_signed.h:26]: So it looks like `static_assert` with that works fine, but not with `EXPECT_EQ` in the tests that you added.  Probably something is missing for fixed point support in constexpr context.

**Review by lntue — APPROVED** [review]
LGTM.  Let's wait for @PiJoules comments.

File: libc/src/__support/CPP/type_traits/is_signed.h (hunk 2 above)
Comment (kr-2003) [reply libc/src/__support/CPP/type_traits/is_signed.h:27]: > So it looks like `static_assert` with that works fine, but not with `EXPECT_EQ` in the tests that you added. Probably something is missing for fixed point support in constexpr context.

opened issue at #133680

File: libc/src/__support/CPP/type_traits/is_signed.h (hunk 1 above)
Comment (PiJoules) [reply libc/src/__support/CPP/type_traits/is_signed.h]: What's the failure mode? Is it a compilation error or failure in one of the tests?

Comment (kr-2003) [reply libc/src/__support/CPP/type_traits/is_signed.h]: > What's the failure mode? Is it a compilation error or failure in one of the tests?

i have explained here https://github.com/llvm/llvm-project/issues/133680

Comment (PiJoules) [reply libc/src/__support/CPP/type_traits/is_signed.h]: Replied to the issue.

tl;dr overflow for non-saturating types isn't defined, so `unsigned _Fract(-1)` can't be constant evaluated. If you want to check if a type is signed, I think you can do `FXRep<T>::MIN() < FXRep::ZERO()`. I also need to update the diagnostic since it's misleading.

**Review by PiJoules — APPROVED** [review]
LGTM assuming you're not blocked on that compilation issue anymore
