### PR TITLE
[C23] Allow casting from a null pointer constant to nullptr_t

### LINKED ISSUE #133644: Cast from null pointer constant to nullptr is failing.
```c
int main(void)
{
  typeof(nullptr) a;
  a = (typeof(nullptr)) 0;  
}
```
Standard:
"If the target type is nullptr_t, the cast expression shall be a null pointer constant or have type nullptr_t."

### PR DESCRIPTION
**Pull request by AaronBallman**
C23 allows a cast of a null pointer constant to nullptr_t. e.g., (nullptr_t)0 or (nullptr_t)(void *)0.

Fixes #133644

### CODE REVIEW

File: clang/lib/Sema/SemaCast.cpp [hunk 1]
```diff
@@ -3115,11 +3115,24 @@ void CastOperation::CheckCStyleCast() {
...
     }
   }
-  if (DestType->isNullPtrType() && !SrcType->isNullPtrType()) {
-    Self.Diag(SrcExpr.get()->getExprLoc(), diag::err_nullptr_cast)
-        << /*type to nullptr*/ 1 << SrcType;
-    SrcExpr = ExprError();
-    return;
+  // C23 6.3.2.4p2: a null pointer constant or value of type nullptr_t may be
+  // converted to nullptr_t.
+  if (DestType->isNullPtrType()) {
```
Comment (jyknight) [inline clang/lib/Sema/SemaCast.cpp:3120]: Can make the first line `if (DestType->isNullPtrType() && !SrcType->isNullPtrType()) {`, to simplify.

File: clang/test/C/C23/n3042.c [hunk 2]
```diff
@@ -93,6 +91,9 @@ void test() {
   (int *)null_val;    // ok
   (int *)nullptr;     // ok
   (nullptr_t)nullptr; // ok
+  (nullptr_t)0;       // ok
+  (nullptr_t)(void *)0; // ok
+  (nullptr_t)null_val;  // ok
```
Comment (Sirraide) [inline clang/test/C/C23/n3042.c:96]: What about `(nullptr_t)__null`

File: clang/lib/Sema/SemaCast.cpp [hunk 3]
```diff
@@ -3115,11 +3115,24 @@ void CastOperation::CheckCStyleCast() {
                                          Self.CurFPFeatureOverrides());
     }
   }
-  if (DestType->isNullPtrType() && !SrcType->isNullPtrType()) {
-    Self.Diag(SrcExpr.get()->getExprLoc(), diag::err_nullptr_cast)
-        << /*type to nullptr*/ 1 << SrcType;
-    SrcExpr = ExprError();
-    return;
+  // C23 6.3.2.4p2: a null pointer constant or value of type nullptr_t may be
```
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/lib/Sema/SemaCast.cpp:3118]: Good catch, I've updated.

File: clang/lib/Sema/SemaCast.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaCast.cpp:3120]: Good call!

File: clang/test/C/C23/n3042.c (hunk 2 above)
Comment (AaronBallman) [reply clang/test/C/C23/n3042.c:96]: I've added a test for that.

Comment (AaronBallman) [reply clang/test/C/C23/n3042.c:96]: Oops, I take that back, C doesn't have `__null`, that's a C++ism: https://godbolt.org/z/1sKsEM6dY

> `KEYWORD(__null                      , KEYCXX)`

Comment (Sirraide) [reply clang/test/C/C23/n3042.c:96]: Oh interesting; my bad, I thought it was an extension for both C and C++.

Comment (AaronBallman) [reply clang/test/C/C23/n3042.c:96]: I thought that as well!

**Review by jyknight — APPROVED** [review]

File: clang/test/C/C23/n3042.c [hunk 4]
```diff
@@ -93,6 +91,9 @@ void test() {
   (int *)null_val;    // ok
   (int *)nullptr;     // ok
   (nullptr_t)nullptr; // ok
+  (nullptr_t)0;       // ok
```
Comment (shafik) [inline clang/test/C/C23/n3042.c:94]: Maybe worth checking other literals as well, like floating point, char and string literals?

Comment (AaronBallman) [reply clang/test/C/C23/n3042.c:94]: I added that test coverage in fb9deab74e5dc9a9227732fcd95c1aadacf86d44, thanks for the suggestion!
