### PR TITLE
[lldb-dap] Support StackFrameFormat

### LINKED ISSUE #137057: Support StackFrameFormat
The debug adapter protocol supports an option to provide formatting information for a stack frames as part of the StackTrace request. We should support this in lldb-dap.

https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrameFormat
https://github.com/microsoft/VSDebugAdapterHost/wiki/Stack-Trace-and-Value-Formatting

### PR DESCRIPTION
**Pull request by JDevlieghere**
The debug adapter protocol supports an option to provide formatting information for a stack frames as part of the StackTrace request. lldb-dap incorrectly advertises it supports this, but until this PR that support wasn't actually implemented.

Fixes #137057

### CODE REVIEW

File: lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp [hunk 1]
```diff
@@ -178,14 +179,45 @@ void StackTraceRequestHandler::operator()(
...
+
+  if (const auto *format = arguments->getObject("format")) {
+    const bool parameters = GetBoolean(format, "parameters").value_or(false);
+    const bool parameter_names =
+        GetBoolean(format, "parameterNames").value_or(false);
+    const bool parameter_values =
+        GetBoolean(format, "parameterValues").value_or(false);
+    const bool line = GetBoolean(format, "line").value_or(false);
+    const bool module = GetBoolean(format, "module").value_or(false);
+    const bool include_all = GetBoolean(format, "includeAll").value_or(false);
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp:192]: I think this is maybe a different meaning than the spec meant for `includeAll`.

It says:

> Includes all stack frames, including those the debug adapter might otherwise hide.

Which to me, sounds like its about hiding frames that we might not find interesting (e.g. frames from system libraries).

I think if this is `false` you could skip showing the extended backtraces.

Comment (JDevlieghere) [reply lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp:192]: Great observation, you're right.

Comment (ashgti) [reply lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp:192]: Its worth noting that today I don't think we skip any frames, however we do use the 'presentationHint' to tweak the frames a little.

* `deemphasize` is used when we don't have the source info for a frame https://github.com/llvm/llvm-project/blob/feaa5aa840dcda69bd4133536142be882f696114/lldb/tools/lldb-dap/JSONUtils.cpp#L774
* `subtle` is used if the frame is artificial or hidden https://github.com/llvm/llvm-project/blob/feaa5aa840dcda69bd4133536142be882f696114/lldb/tools/lldb-dap/JSONUtils.cpp#L795

File: lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp [hunk 2]
```diff
@@ -178,14 +179,45 @@ void StackTraceRequestHandler::operator()(
   llvm::json::Array stack_frames;
   llvm::json::Object body;
 
+  lldb::SBFormat frame_format = dap.frame_format;
+
+  if (const auto *format = arguments->getObject("format")) {
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp:184]: Another thing I notice is the `StackFrameFormat` inherits from `ValueFormat` and thus includes the `hex?: boolean;` field as well.

I'm not sure what that would mean in terms of a stack frame however, just thought I would note that for completeness.

File: lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp [hunk 3]
```diff
@@ -180,44 +184,53 @@ void StackTraceRequestHandler::operator()(
   llvm::json::Object body;
 
   lldb::SBFormat frame_format = dap.frame_format;
+  bool include_all = false;
```
Comment (ashgti) [inline lldb/tools/lldb-dap/Handler/StackTraceRequestHandler.cpp:187]: Should this default to `dap.configuration.displayExtendedBacktrace` and then it simplifies line 75-77.

**Review by ashgti — APPROVED** [review]

**Review by da-viper — APPROVED** [review]

File: lldb/test/API/tools/lldb-dap/stackTrace/TestDAP_stackTrace.py [hunk 4]
```diff
@@ -217,3 +216,30 @@ def test_functionNameWithArgs(self):
         self.continue_to_next_stop()
         frame = self.get_stackFrames()[0]
         self.assertEqual(frame["name"], "recurse(x=1)")
+
+    @skipIfWindows
```
[the remark this answers is not in the document]
Comment (JDevlieghere) [reply lldb/test/API/tools/lldb-dap/stackTrace/TestDAP_stackTrace.py:220]: Fair enough. All the tests in this file are skipped on Windows for as far as the history goes back. I can try removing all of them in a followup and see what the Windows bot say.
