### PR TITLE
[clang] Compound Literal Statement Constant Expression Assertion Fix

### LINKED ISSUE #139160: "Assertion `!isa<ConstantExpr>(E)' failed." with compound literal
Testcase:

```
struct A {int x[1]; };
A f();
typedef int *t[];
consteval int* f(int* x) { return x; }
int ** x = (t){f(f().x)};
```

Crashes with:

```
clang: clang/lib/AST/Expr.cpp:339: static clang::ConstantExpr *clang::ConstantExpr::Create(const clang::ASTContext &, clang::Expr *, clang::ConstantResultStorageKind, bool): Assertion `!isa<ConstantExpr>(E)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -x c++ - -o - -S -std=c++20
1.      <stdin>:5:25: current parser token ';'
```

### PR DESCRIPTION
**Pull request by Mr-Anyone**
Compound literals initializer-list should be a constant expression if it is defined outside the body of a function.

Emit error instead of falling through tripping assertion error.

fixes #139160

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -7220,6 +7220,17 @@ Sema::BuildCompoundLiteralExpr(SourceLocation LParenLoc, TypeSourceInfo *TInfo,
     if (auto ILE = dyn_cast<InitListExpr>(LiteralExpr))
       for (unsigned i = 0, j = ILE->getNumInits(); i != j; i++) {
         Expr *Init = ILE->getInit(i);
+        // C99 6.5.2.5
+        //  "If the compound literal occurs outside the body of a function, the
+        //  initializer list shall consist of constant expressions."
+        if (!Init->isTypeDependent() && !Init->isValueDependent() &&
+            !Init->getType()->isDependentType())
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExpr.cpp:7227]: This is not checking for "outside of the function".
Note that GCC errors on these cases too https://compiler-explorer.com/z/TaqzEdnbe
I think you need to update the comment to better describe the check

**Review by cor3ntin — COMMENTED** [review]
This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

File: clang/lib/Sema/SemaExpr.cpp (hunk 1 above)
Comment (Mr-Anyone) [reply clang/lib/Sema/SemaExpr.cpp:7227]: I have moved the comment to the `if (IsFileScope)`, is that alright?

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -7241,10 +7241,21 @@ Sema::BuildCompoundLiteralExpr(SourceLocation LParenLoc, TypeSourceInfo *TInfo,
...
 
+  // C99 6.5.2.5
+  //  "If the compound literal occurs outside the body of a function, the
+  //  initializer list shall consist of constant expressions."
   if (IsFileScope)
     if (auto ILE = dyn_cast<InitListExpr>(LiteralExpr))
       for (unsigned i = 0, j = ILE->getNumInits(); i != j; i++) {
         Expr *Init = ILE->getInit(i);
+        if (!Init->isTypeDependent() && !Init->isValueDependent() &&
+            !Init->getType()->isDependentType())
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp:7252]: I don't think you need the check for `!Init->getType()->isDependentType()` because `computeDependence()` on the expression should already account for that, shouldn't it?

Comment (Mr-Anyone) [reply clang/lib/Sema/SemaExpr.cpp]: > I don't think you need the check for `!Init->getType()->isDependentType()` because `computeDependence()` on the expression should already account for that, shouldn't it?

You're absolutely right—I just removed that check. Thanks!

File: clang/lib/Sema/SemaExpr.cpp [hunk 3]
```diff
@@ -7241,10 +7241,20 @@ Sema::BuildCompoundLiteralExpr(SourceLocation LParenLoc, TypeSourceInfo *TInfo,
...
   if (IsFileScope)
     if (auto ILE = dyn_cast<InitListExpr>(LiteralExpr))
       for (unsigned i = 0, j = ILE->getNumInits(); i != j; i++) {
         Expr *Init = ILE->getInit(i);
+        if (!Init->isTypeDependent() && !Init->isValueDependent())
+          if (!Init->isConstantInitializer(Context, /*IsForRef=*/false)) {
+            Diag(Init->getExprLoc(), diag::err_init_element_not_constant)
+                << Init->getSourceBitField();
+            return ExprError();
+          }
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp:7256]:
```suggestion
        if (!Init->isTypeDependent() && !Init->isValueDependent() &&
            !Init->isConstantInitializer(Context, /*IsForRef=*/false)) {
          Diag(Init->getExprLoc(), diag::err_init_element_not_constant)
              << Init->getSourceBitField();
          return ExprError();
        }
```
Can combine these into a single `if`

**Review by AaronBallman — APPROVED** [review]
Just a minor nit from me, otherwise LG!
