### PR TITLE
[InstCombine] fold icmp of select with invertible shl

### LINKED ISSUE #146642: [InstCombine] Missed optimization for icmp of select with constants and invertible binop
We currently fail to fold variations of this pattern:

https://alive2.llvm.org/ce/z/tT3yNU
```llvm
define i1 @src(i64 %a, i1 %c) {
  %idx = shl nsw i64 %a, 3
  %sel = select i1 %c, i64 8, i64 0
  %cmp = icmp eq i64 %idx, %sel
  ret i1 %cmp
}

define i1 @tgt(i64 %a, i1 %c) {
  %sel = select i1 %c, i64 1, i64 0
  %cmp = icmp eq i64 %a, %sel
  ret i1 %cmp
}
```

The underlying pattern here is something like `f(x) == y` converted to `x == f^-1(y)` where f invertible and `f^-1(y)` folds because the shift arms are constant.

From https://github.com/dtcxzyw/llvm-opt-benchmark/pull/2524/files/9ca17b717ceea34b52263bf8b20cf12ad02cd4fd#r2179220735.

### PR DESCRIPTION
**Pull request by actinks**
Proof: https://alive2.llvm.org/ce/z/a5fzlJ
Closes https://github.com/llvm/llvm-project/issues/146642

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 1]
```diff
@@ -4391,6 +4483,24 @@ Instruction *InstCombinerImpl::foldSelectICmp(CmpPredicate Pred, SelectInst *SI,
...
+  auto *RHSOp = dyn_cast<Operator>(RHS);
+  if (RHSOp &&
+      match(SI, m_OneUse(m_Select(m_Value(Cond), m_APInt(C1), m_APInt(C2))))) {
+    if (auto Values0 = getInvertibleOperandsWithPredicte(RHSOp, *C1, Pred)) {
+      if (auto Values1 = getInvertibleOperandsWithPredicte(RHSOp, *C2, Pred)) {
+        assert(Values0->first == Values1->first &&
+               "Invertible Operand0 mismatch");
+        auto *NewSI = Builder.CreateSelect(Cond, Values0->second,
+                                           Values1->second, SI->getName());
+        return ICmpInst::Create(Instruction::ICmp, I.getPredicate(), NewSI,
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]:
```suggestion
        return ICmpInst::Create(Instruction::ICmp, Pred, NewSI,
```
Miscompilation reproducer: https://alive2.llvm.org/ce/z/RBpncq
```
define i1 @src(i8 %a, i1 %cond) {
  %a_shl1 = lshr exact i8 %a, 1
  %sel = select i1 %cond, i8 12, i8 4
  %cmp = icmp uge i8 %a_shl1, %sel
  ret i1 %cmp
}

define i1 @tgt(i8 %a, i1 %cond) {
  %sel1 = select i1 %cond, i8 24, i8 8
  %cmp = icmp uge i8 %sel1, %a
  ret i1 %cmp
}
```

**Review by dtcxzyw — CHANGES_REQUESTED** [review]
We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.

**Comment by actinks** [comment]
> We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.

Do we need to keep the optimization for ucmp/scmp？

**Comment by nikic** [comment]
> > We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.
> 
> Do we need to keep the optimization for ucmp/scmp？

I think it should be possible to generalize that fold to handle unsigned/signed predicate as well (just changes which ops can be applied).

But probably it makes sense to start with just the equality case.

**Comment by nikic** [comment]
On the other hand, things like the sext/zext handling wouldn't really fit into how foldICmpEqualityWithOffset works, so maybe there is value in the separate handling...

**Comment by actinks** [comment]
> We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.

It seems that we cannot simply extend foldICmpEqualityWithOffset to handle shift operations and bit operations that require Op0 and Op1 to satisfy certain properties at the same time. For example, Shl nsw/nuw, AShr exact. The proof is given below:
https://alive2.llvm.org/ce/z/NKvGtR

```
define i1 @src_shl_nsw_eq(i8 %a, i1 %cond) {
  %a_shl = shl nsw i8 %a, 3
  %sel = select i1 %cond, i8 4, i8 16
  %cmp = icmp eq i8 %a_shl, %sel
  ret i1 %cmp
}

define i1 @tgt_shl_nsw_eq(i8 %a, i1 %cond) {
  %1 = select i1 %cond, i8 0, i8 2
  %cmp = icmp eq i8 %a, %1
  ret i1 %cmp
}
```

In the actual processing flow of instcombine, it is captured by foldSelectICmp in advance, so the above code will not be optimized out, but this seems unsafe. Actual optimization results:

```
define i1 @shl_nsw_eq(i8 %a, i1 %cond) {
  %cmp1 = icmp eq i8 %a, 2
  %not.cond = xor i1 %cond, true
  %cmp = select i1 %not.cond, i1 %cmp1, i1 false
  ret i1 %cmp
}

```

@dtcxzyw @nikic

**Comment by dtcxzyw** [comment]
> > We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.
> 
> It seems that we cannot simply extend foldICmpEqualityWithOffset to handle shift operations and bit operations that require Op0 and Op1 to satisfy certain properties at the same time. For example, Shl nsw/nuw, AShr exact. The proof is given below: https://alive2.llvm.org/ce/z/NKvGtR
> 
> ```
> define i1 @src_shl_nsw_eq(i8 %a, i1 %cond) {
>   %a_shl = shl nsw i8 %a, 3
>   %sel = select i1 %cond, i8 4, i8 16
>   %cmp = icmp eq i8 %a_shl, %sel
>   ret i1 %cmp
> }
> 
> define i1 @tgt_shl_nsw_eq(i8 %a, i1 %cond) {
>   %1 = select i1 %cond, i8 0, i8 2
>   %cmp = icmp eq i8 %a, %1
>   ret i1 %cmp
> }
> ```
> 
> In the actual processing flow of instcombine, it is captured by foldSelectICmp in advance, so the above code will not be optimized out, but this seems unsafe. Actual optimization results:
> 
> ```
> define i1 @shl_nsw_eq(i8 %a, i1 %cond) {
>   %cmp1 = icmp eq i8 %a, 2
>   %not.cond = xor i1 %cond, true
>   %cmp = select i1 %not.cond, i1 %cmp1, i1 false
>   ret i1 %cmp
> }
> ```
> 

Yeah, we need an extra check for right shifts with the `exact` flag. Can we start with handling constant shamts and checking if the right shift doesn't produce poison?

**Comment by actinks** [comment]
> > > We can simply extend `foldICmpEqualityWithOffset` to handle the motivating case.
> > 
> > 
> > It seems that we cannot simply extend foldICmpEqualityWithOffset to handle shift operations and bit operations that require Op0 and Op1 to satisfy certain properties at the same time. For example, Shl nsw/nuw, AShr exact. The proof is given below: https://alive2.llvm.org/ce/z/NKvGtR
> > ```
> > define i1 @src_shl_nsw_eq(i8 %a, i1 %cond) {
> >   %a_shl = shl nsw i8 %a, 3
> >   %sel = select i1 %cond, i8 4, i8 16
> >   %cmp = icmp eq i8 %a_shl, %sel
> >   ret i1 %cmp
> > }
> > 
> > define i1 @tgt_shl_nsw_eq(i8 %a, i1 %cond) {
> >   %1 = select i1 %cond, i8 0, i8 2
> >   %cmp = icmp eq i8 %a, %1
> >   ret i1 %cmp
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the actual processing flow of instcombine, it is captured by foldSelectICmp in advance, so the above code will not be optimized out, but this seems unsafe. Actual optimization results:
> > ```
> > define i1 @shl_nsw_eq(i8 %a, i1 %cond) {
> >   %cmp1 = icmp eq i8 %a, 2
> >   %not.cond = xor i1 %cond, true
> >   %cmp = select i1 %not.cond, i1 %cmp1, i1 false
> >   ret i1 %cmp
> > }
> > ```
> 
> Yeah, we need an extra check for right shifts with the `exact` flag. Can we start with handling constant shamts and checking if the right shift doesn't produce poison?

I haven't found a suitable implementation based on foldICmpEqualityWithOffset. A lot of judgment logic needs to be added to the shift class, and the original op and flag need to be kept to determine whether the simplifyBinOp result is available. Is this in line with expectations?

**Comment by dtcxzyw** [comment]
> I haven't found a suitable implementation based on foldICmpEqualityWithOffset. A lot of judgment logic needs to be added to the shift class, and the original op and flag need to be kept to determine whether the simplifyBinOp result is available. Is this in line with expectations?

Sounds reasonable.

**Review by dtcxzyw — APPROVED** [review]
LGTM. If we need to catch more complicated patterns, we can use MaskedValueIsZero/ComputeNumSignBits in the future.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 2]
```diff
@@ -5892,6 +5892,12 @@ static void collectOffsetOp(Value *V, SmallVectorImpl<OffsetOp> &Offsets,
     Offsets.emplace_back(Instruction::Xor, Inst->getOperand(1));
     Offsets.emplace_back(Instruction::Xor, Inst->getOperand(0));
     break;
+  case Instruction::Shl:
+    if (match(Inst, m_NSWShl(m_Value(), m_Value())))
+      Offsets.emplace_back(Instruction::AShr, Inst->getOperand(1));
+    if (match(Inst, m_NUWShl(m_Value(), m_Value())))
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]:
```suggestion
    if (Inst->hasNoUnsignedWrap())
```

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 3]
```diff
@@ -5948,6 +5954,29 @@ static Instruction *foldICmpEqualityWithOffset(ICmpInst &I,
...
+      const APInt *CV, *CRHS;
+      if (!(match(V, m_APInt(CV)) && match(RHS, m_APInt(CRHS)) &&
+            CV->lshr(*CRHS).shl(*CRHS) == *CV) &&
+          !match(V, m_NUWShl(m_Value(), m_Specific(RHS))))
+        return nullptr;
+      break;
+    }
+    default:
+      break;
+    }
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]: Looks like there is no test coverage for these checks. Is that because any IR failing the precondition would already get folded in a different way?

File: llvm/test/Transforms/InstCombine/icmp-select.ll [hunk 4]
```diff
@@ -835,3 +835,41 @@ define i1 @discr_eq_constantexpr(ptr %p) {
...
+; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND:%.*]], i8 [[B:%.*]], i8 4
+; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i8 [[TMP1]], [[A:%.*]]
+; CHECK-NEXT:    ret i1 [[CMP]]
+;
+  %shl_a = shl nuw i8 %a, 3
+  %shl_b = shl nuw i8 %b, 3
+  %sel = select i1 %cond, i8 %shl_b, i8 32
+  %cmp = icmp ne i8 %sel, %shl_a
+  ret i1 %cmp
+}
```
Comment (nikic) [inline llvm/test/Transforms/InstCombine/icmp-select.ll]: Should at least check that the fold doesn't occur without flags or an incorrect nuw/nsw mix.

File: llvm/test/Transforms/InstCombine/icmp-select.ll [hunk 5]
```diff
@@ -835,3 +835,41 @@ define i1 @discr_eq_constantexpr(ptr %p) {
...
+
+define i1 @shl_nsw_eq(i8 %a, i1 %cond) {
+; CHECK-LABEL: @shl_nsw_eq(
+; CHECK-NEXT:    [[A:%.*]] = shl nsw i8 [[A1:%.*]], 3
+; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND:%.*]], i8 8, i8 0
+; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[A]], [[TMP1]]
+; CHECK-NEXT:    ret i1 [[CMP]]
+;
+  %shl = shl nsw i8 %a, 3
+  %sel = select i1 %cond, i8 8, i8 0
```
Comment (nikic) [inline llvm/test/Transforms/InstCombine/icmp-select.ll]: Should also test this with constants that show the lshr / ashr difference (negative number).

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 6]
```diff
@@ -5948,9 +5954,29 @@ static Instruction *foldICmpEqualityWithOffset(ICmpInst &I,
...
+
     Value *Simplified = simplifyBinOp(BinOpc, V, RHS, SQ);
-    // Avoid infinite loops by checking if RHS is an identity for the BinOp.
-    if (!Simplified || Simplified == V)
```
Comment (actinks) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]: @dtcxzyw del `|| Simplified == V` since  `0 >> 3` simplifie to `0`
```
  %shl = shl nsw i8 %a, 3
  %sel = select i1 %cond, i8 8, i8 0
  %cmp = icmp eq i8 %shl, %sel
  ret i1 %cmp
```

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]: It was intended to bail out on something like `X +/-/>> 0 -> 0` or more complicated patterns. It is ok to drop this for now. If we hit an infinite loop in the future, we can defer the check into `ApplyOffset`.

**Review by dtcxzyw — CHANGES_REQUESTED** [review]
Miscompilation reproducer: https://alive2.llvm.org/ce/z/-TagCh
```
define i1 @src(i64 %indvars.iv.i, i32 %conv161.i.i.i) {
entry:
  %cmp104.i.i.i = icmp slt i64 %indvars.iv.i, 1
  br i1 %cmp104.i.i.i, label %lor.end157.i.i.i, label %lor.rhs106.i.i.i

lor.rhs106.i.i.i:
  br label %lor.end157.i.i.i

lor.end157.i.i.i:
  %conv159.i.i.i = zext i1 %cmp104.i.i.i to i16
  %sub.i122.i.i.i = sub i16 0, %conv159.i.i.i
  %conv161.i.i.i2 = zext i16 %sub.i122.i.i.i to i32
  %shl.i.i.i.i = shl nuw i32 %conv161.i.i.i, 31
  %cond.i124.i.i.i = select i1 %cmp104.i.i.i, i32 %conv161.i.i.i2, i32 %shl.i.i.i.i
  %conv163.i.i.i = zext i32 %cond.i124.i.i.i to i64
  %tobool166.not.i.i.i = icmp eq i64 %conv163.i.i.i, 0
  ret i1 %tobool166.not.i.i.i
}

define i1 @tgt(i64 %indvars.iv.i, i32 %conv161.i.i.i) {
entry:
  %cmp104.i.i.i = icmp slt i64 %indvars.iv.i, 1
  br i1 %cmp104.i.i.i, label %lor.end157.i.i.i, label %lor.rhs106.i.i.i

lor.rhs106.i.i.i:                                 ; preds = %entry
  %0 = icmp eq i32 %conv161.i.i.i, 0
  br label %lor.end157.i.i.i

lor.end157.i.i.i:                                 ; preds = %lor.rhs106.i.i.i, %entry
  %tobool166.not.i.i.i = phi i1 [ %0, %lor.rhs106.i.i.i ], [ true, %entry ]
  ret i1 %tobool166.not.i.i.i
}
```

**Comment by actinks** [comment]
> Miscompilation reproducer: https://alive2.llvm.org/ce/z/-TagCh
> 
Is this patch causing this error? My compilation result is  https://alive2.llvm.org/ce/z/enaJTE  @dtcxzyw 

```
define i1 @src(i64 %indvars.iv.i, i32 %conv161.i.i.i) {
entry:
  %cmp104.i.i.i = icmp slt i64 %indvars.iv.i, 1
  br i1 %cmp104.i.i.i, label %lor.end157.i.i.i, label %lor.rhs106.i.i.i

lor.rhs106.i.i.i:
  br label %lor.end157.i.i.i

lor.end157.i.i.i:
  %conv159.i.i.i = zext i1 %cmp104.i.i.i to i16
  %sub.i122.i.i.i = sub i16 0, %conv159.i.i.i
  %conv161.i.i.i2 = zext i16 %sub.i122.i.i.i to i32
  %shl.i.i.i.i = shl nuw i32 %conv161.i.i.i, 31
  %cond.i124.i.i.i = select i1 %cmp104.i.i.i, i32 %conv161.i.i.i2, i32 %shl.i.i.i.i
  %conv163.i.i.i = zext i32 %cond.i124.i.i.i to i64
  %tobool166.not.i.i.i = icmp eq i64 %conv163.i.i.i, 0
  ret i1 %tobool166.not.i.i.i
}

define i1 @tgt(i64 %indvars.iv.i, i32 %conv161.i.i.i) {
entry:
  %cmp104.i.i.i = icmp sgt i64 %indvars.iv.i, 0
  br i1 %cmp104.i.i.i, label %lor.rhs106.i.i.i, label %lor.end157.i.i.i

lor.rhs106.i.i.i:                                 ; preds = %entry
  br label %lor.end157.i.i.i

lor.end157.i.i.i:                                 ; preds = %lor.rhs106.i.i.i, %entry
  %tobool166.not.i.i.i1 = icmp eq i32 %conv161.i.i.i, 0
  %tobool166.not.i.i.i = select i1 %cmp104.i.i.i, i1 %tobool166.not.i.i.i1, i1 false
  ret i1 %tobool166.not.i.i.i
}
```

File: llvm/test/Transforms/InstCombine/icmp-select.ll [hunk 7]
```diff
@@ -930,10 +930,12 @@ define i1 @shl_const_phi_failed_to_simplify(i64 %indvars, i32 %conv) {
 ; CHECK-NEXT:    [[CMP_SLT:%.*]] = icmp slt i64 [[INDVARS:%.*]], 1
 ; CHECK-NEXT:    br i1 [[CMP_SLT]], label [[END:%.*]], label [[THEN:%.*]]
```
Comment (actinks) [inline llvm/test/Transforms/InstCombine/icmp-select.ll]: Thanks @dtcxzyw . The issue, caused by the "right-shift mode" only intercepting constants and failing to intercept phi nodes with two constant incoming values, has been temporarily resolved by reverting to a previous version.

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Comment by actinks** [comment]
> I think you have met the requirements to request commit access. See https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access

Oh, thank you so much @dtcxzyw
