### PR TITLE
[clang] Make sure EvalInfo pointer isn't null

### LINKED ISSUE #155507: [clangd] Crash
CFLAGS = -std=c23
Version = Ubuntu 22.0.0 (++20250812082130+296e057d0bf2-1\~exp1\~20250812082146.1091)

```c
#include <stdint.h>

typedef bool __vbool2  __attribute__((ext_vector_type(2)));
typedef bool __vbool4  __attribute__((ext_vector_type(4)));
typedef bool __vbool8  __attribute__((ext_vector_type(8)));
typedef bool __vbool16 __attribute__((ext_vector_type(16)));
typedef bool __vbool32 __attribute__((ext_vector_type(32)));
typedef bool __vbool64 __attribute__((ext_vector_type(64)));

#define __vbit_cast2  uint8_t
#define __vbit_cast4  uint8_t
#define __vbit_cast8  uint8_t
#define __vbit_cast16 uint16_t
#define __vbit_cast32 uint32_t
#define __vbit_cast64 uint64_t

#define VMASK(bits, x) __builtin_bit_cast(__vbit_cast##bits, __builtin_convertvector(x, __vbool##bits))

typedef int16_t v2int16_t __attribute__((ext_vector_type(2)));

bool v2int16_eq(v2int16_t a, v2int16_t b) {
    return VMASK(2, a == b) == 0b11;
}
```

### PR DESCRIPTION
**Pull request by tbaederr**
It can be null, when called via CheckICE().
Accidentally introduced via #119366

Fixes #155507

### CODE REVIEW

File: clang/test/Sema/constexpr.c [hunk 1]
```diff
@@ -391,3 +391,10 @@ void ghissue109095() {
   _Static_assert(i == c[0]); // expected-error {{static assertion expression is not an integral constant expression}}\
                              // expected-note {{initializer of 'i' is not a constant expression}}
 }
+
+typedef bool __vbool2  __attribute__((ext_vector_type(2)));
+typedef short v2int16_t __attribute__((ext_vector_type(2)));
+
+bool issue155507(v2int16_t a, v2int16_t b) {
```
Comment (Fznamznon) [inline clang/test/Sema/constexpr.c:398]: This test file was intended for exercising c23 constexpr specifier. The new case doesn't seem to be using it, maybe there is another test that is better for the new case?

**Review by Fznamznon — APPROVED** [review]

File: clang/test/Sema/constexpr.c (hunk 1 above)
Comment (Fznamznon) [reply clang/test/Sema/constexpr.c:398]: ok, no problem

**Review by shafik — COMMENTED** [review]
Thank you for the quick fix!
