### PR TITLE
Avoid indirect branches from cold sections when BTI is enabled

### LINKED ISSUE #194489: AArch64: BTI exception after AutoFDO-induced function splitting due to missing landing pads in branch relaxation
**Description:**

We are observing kernel panics on AArch64 Android devices when the kernel is built with Clang, AutoFDO, and Branch Target Identification (BTI) enabled. The issue stems from incorrect code generation during machine function splitting and subsequent branch relaxation.

**Symptoms:**

The system crashes with a BTI exception, indicating an attempt to indirectly branch to an instruction that is not a valid BTI landing pad. For example:
Internal error: Oops - BTI: 0000000036000003

The crash often occurs in functions that have been split into hot and cold sections based on profile data.

**Analysis:**

1. Profile-guided optimizations, such as those driven by AutoFDO, can split functions into a primary (hot) section and one or more outlined (cold) sections. This is often done by the Machine Function Splitting pass.
2. The branch-relaxation pass in [llvm/lib/CodeGen/BranchRelaxation.cpp](https://github.com/llvm/llvm-project/blob/b862554a70eeb9a8315f45406a7e13c771af1eb7/llvm/lib/CodeGen/BranchRelaxation.cpp#L576) is responsible for handling branches that might exceed the range, particularly between these different sections. It calls [AArch64InstrInfo::insertIndirectBranch](https://github.com/llvm/llvm-project/blob/b862554a70eeb9a8315f45406a7e13c771af1eb7/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp#L365C6-L365C44) to generate these branch instructions.
3. Within [AArch64InstrInfo::insertIndirectBranch](https://github.com/llvm/llvm-project/blob/b862554a70eeb9a8315f45406a7e13c771af1eb7/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp#L409), if the standard veneer register (X16) is already in use, the pass may choose to use another available general-purpose register to perform an indirect branch.
4. The core problem is that when this specific relaxation strategy is chosen (using a free register for an indirect jump from cold to hot), there's no mechanism ensuring that the target basic block in the hot section starts with a BTI landing pad instruction (e.g., BTI j).
5. The AArch64BranchTargets pass, which inserts BTI instructions, runs before branch relaxation. At that stage, it would not identify the target block as needing a BTI instruction because the indirect branch does not yet exist. The Machine Function Splitting pass also does not appear to flag the entry point of the hot section as an indirect target in a way that guarantees the AArch64BranchTargets pass will protect it.

**Relevant LLVM Commits:**

The branch relaxation logic was introduced/modified in commits such as:

d7bca8e4942b97a6442425d5f741cb4665582446 ("[AArch64] Relax cross-section branches")
866ae69cfa73ce224944c64965d0426637e31517 ("[AArch64] [BranchRelaxation] Optimize for hot code size in AArch64 branch relaxation")

**Impact:**

This bug prevents the use of AutoFDO with BTI enabled in the Android kernel, blocking potential performance optimizations.

**Suggested Solution:**

To ensure BTI compliance, when BTI is enabled, the AArch64BranchRelaxation pass should avoid the strategy of using an arbitrary free register for an indirect branch from a cold section to a hot section. Instead, it should fall back to other mechanisms, such as:

- Using a sequence that saves and restores X16, allowing the linker to handle the long branch and BTI veneer insertion.
- Always emitting a thunk in the cold section for such cross-section branches when BTI is active.

The original motivation for using an arbitrary available register was to minimize code size impact. However, BTI correctness is paramount. Relying on linker-generated veneers for out-of-range branches is a safer approach as the linker is equipped to insert BTI instructions.

**Reproducer:**

We are currently observing this in the Android kernel codebase. We will work on creating a smaller, self-contained reproducer. The issue manifests when building kernel/common branch android17-6.18 with AutoFDO profiles and BTI enabled for AArch64.

### PR DESCRIPTION
**Pull request by yabinc**
Fixes #194489

Profile-guided optimizations such as AutoFDO can split functions into hot and cold sections. During the branch relaxation pass, cross-section branches that are out-of-range may be relaxed.

If X16 is in use at the branch site, the AArch64InstrInfo::insertIndirectBranch pass may scavenge a free register to perform the indirect branch. However, because the AArch64BranchTargets pass runs before branch relaxation, the target block in the hot section is not guaranteed to start with a BTI landing pad instruction.

To avoid this BTI exception, avoid using the scavenged register optimization when BTI is active (i.e., branchTargetEnforcement() is true). This makes the compiler fall back to spilling X16, allowing the linker to handle the long branch and insert the necessary BTI-compliant veneer.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 1]
```diff
@@ -401,19 +401,21 @@ void AArch64InstrInfo::insertIndirectBranch(MachineBasicBlock &MBB,
...
-      MBB.getSectionID() == MBBSectionID::ColdSectionID) {
-    buildIndirectBranch(Scavenged, NewDestBB);
-    RS->setRegUsed(Scavenged);
-    return;
+  AArch64FunctionInfo *AFI = MBB.getParent()->getInfo<AArch64FunctionInfo>();
+  bool HasBTI = AFI && AFI->branchTargetEnforcement();
+  if (MBB.getSectionID() == MBBSectionID::ColdSectionID && !HasBTI) {
+    Register Scavenged = RS->FindUnusedReg(&AArch64::GPR64RegClass);
+    if (Scavenged != AArch64::NoRegister) {
+      buildIndirectBranch(Scavenged, NewDestBB);
```
Comment (nickdesaulniers) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:412]: > However, because the AArch64BranchTargets pass runs before branch relaxation, the target block in the hot section is not guaranteed to start with a BTI landing pad instruction.

Should `buildIndirectBranch` itself check if `branchTargetEnforcement` is enabled, and if so, insert the landing pad, rather than skip this transform?  Or will that mess up branch relaxation?

**Review by nickdesaulniers — COMMENTED** [review]
Thanks for the patch!

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp (hunk 1 above)
Comment (nickdesaulniers) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:412]: Also, I wonder why `buildIndirectBranch` is a lambda; seems like it only has 1 use.

Comment (nickdesaulniers) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:412]: @dhoekwater left some feedback on the internal bug about regressing hot code size.  If that's the preference here, we should make the super explicit in the comments.

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 2]
```diff
@@ -401,19 +401,21 @@ void AArch64InstrInfo::insertIndirectBranch(MachineBasicBlock &MBB,
     return;
   }
 
-  // If there's a free register and it's worth inflating the code size,
+  // If we are in a cold block, BTI is not enabled, and there's a free register,
```
Comment (dhoekwater) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp]: nit: The reason we're skipping indirect branch instruction here is to avoid inserting a BTI instruction at the (maybe hot) branch target. Can you update the comment to reflect this?

The motivation behind this logic is clear now, but documenting it in the code may provide valuable context to the reader e.g. a year from now.

https://llvm.org/docs/CodingStandards.html#commenting

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp (hunk 1 above)
Comment (dhoekwater) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:412]: Is there a benefit to moving the `BTI` check to `buildIndirectBranch`? Doing so would make this callsite a little hairier since we want the "did not actually insert an indirect branch" path to fall through to the X16 spilling code below.

**Review by dhoekwater — APPROVED** [review]

**Comment by ilinpv** [comment]
Thanks @yabinc for addressing the issue with missing BTI landing pads, this workaround looks good. For a longer-term fix, would it be feasible, when BTI is active, to make AArch64InstrInfo::insertIndirectBranch BTI-aware by checking whether NewDestBB has a valid BTI landing pad and insert one as needed when emitting an indirect branch or marking it as requiring a BTI landing pad and adding it in a later pass?

**Comment by smithp35** [comment]
I don't think I can add anything to what's already been said. If I've read the original code in the BranchRelaxation pass correctly, all inter-section branches are assumed to be out of range. For AArch64 the direct branch range is 128 MiB so I'd expect most programs to have the hot and cold function to be within direct branch range and not need range-extending (or a BTI as direct branches don't need them). I think the way the patch does it now, with an extra spill + direct branch would be comparable in performance and code-size to an indirect branch via a register. Obviously if the program is > 128 MiB then the range extension thunks and extra BTI thunk will add some overhead.

**Review by nickdesaulniers — APPROVED** [review]
