### PR TITLE
[RISCV] Fix incorrect slide offset when using vnsrl to de-interleave

### LINKED ISSUE #132071: [RISC-V] Miscompile on rv64gcv with -O[23]
Testcase:
```c
short a[12];
short b[12];
long long al;
int f;
short m = 31554;
long long q[12];
int main() {
  for (int i = 0; i < 2; ++i)
    q[i] = 6;
  for (short i = 0; i < 12; i += m - 31553) {
    a[i] = q[i];
    b[i] = f > q[i];
  }
  for (int i = 0; i < 12; ++i)
    al += a[i];
  for (int i = 0; i < 2; ++i)
    al += b[i];
  __builtin_printf("%llu\n", al);
}
```

Commands:
```
# riscv
$ ./bin/clang -march=rv64gcv_zvl256b -flto -O2 red.c -o user-config.out
$ QEMU_CPU=rv64,vlen=256,rvv_ta_all_1s=true,rvv_ma_all_1s=true,v=true,vext_spec=v1.0,zve32f=true,zve64f=true timeout --verbose -k 0.1 4 ./bin/qemu-riscv64 user-config.out 1
10

$ ./bin/clang -march=rv64gcv_zvl256b -flto -O3 red.c -o user-config.out
$ QEMU_CPU=rv64,vlen=256,rvv_ta_all_1s=true,rvv_ma_all_1s=true,v=true,vext_spec=v1.0,zve32f=true,zve64f=true timeout --verbose -k 0.1 4 ./bin/qemu-riscv64 user-config.out 1
10

# x86
$ ./native.out 1
12
```

Godbolt: https://godbolt.org/z/7hMW6eerT

Tried changing `m - 31553` to `1` and the error disappears

Bisected to 9b7282e545d5e47315e3ffb9e5e00d0fb547c8e3 as the first bad commit

Found via fuzzer

### PR DESCRIPTION
**Pull request by mshockwave**
Given this shuffle:
```
shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 4, i32 8, i32 12, i32 undef, i32 undef, i32 undef, i32 undef>
```
#127272  lowers it with a bunch of vnsrl. If we describe the result in terms of the shuffle mask, we expect:
```
<0, 4, 8, 12, u, u, u, u>
```
but we actually got:
```
<0, 4, u, u, 8, 12, u, u>
```
for factor larger than 2. This is caused by `CONCAT_VECTORS` on incorrect (sub) vector types. This patch fixes the said issue by building an aggregate vector with the correct sub vector types.

Fix #132071

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -5545,12 +5545,25 @@ static SDValue lowerVECTOR_SHUFFLE(SDValue Op, SelectionDAG &DAG,
...
-              getDeinterleaveShiftAndTrunc(DL, HalfVT, V2, Factor, Index, DAG);
-          return DAG.getNode(ISD::CONCAT_VECTORS, DL, VT, Lo, Hi);
+              getDeinterleaveShiftAndTrunc(DL, SubVT, V2, Factor, Index, DAG);
+
+          MVT NewVT = SubVT.getDoubleNumVectorElementsVT();
+          SDValue Concat = DAG.getNode(ISD::CONCAT_VECTORS, DL, NewVT, Lo, Hi);
+          for (unsigned F = Factor; F > 2; F >>= 1) {
+            SDValue Undef = DAG.getUNDEF(NewVT);
+            NewVT = NewVT.getDoubleNumVectorElementsVT();
+            Concat = DAG.getNode(ISD::CONCAT_VECTORS, DL, NewVT, Concat, Undef);
```
Comment (topperc) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:5563]: Are we just slowly building an INSERT_SUBVECTOR?

Comment (mshockwave) [reply llvm/lib/Target/RISCV/RISCVISelLowering.cpp:5563]: > Are we just slowly building an INSERT_SUBVECTOR?

The CONCAT_VECTORS lowering code does a similar thing which turns CONCAT_VECTORS with more than 2 operand into a tree of CONCAT_VECTORS. But I don't think this tree of CONCAT_VECTORS will become a single INSERT_SUBVECTOR.

File: llvm/test/CodeGen/RISCV/rvv/fixed-vectors-shuffle-deinterleave.ll [hunk 2]
```diff
@@ -378,7 +378,7 @@ define void @deinterleave4_0_i8_two_source(ptr %in0, ptr %in1, ptr %out) {
 ; CHECK-NEXT:    vsetvli zero, zero, e8, mf8, ta, ma
 ; CHECK-NEXT:    vnsrl.wi v8, v8, 0
 ; CHECK-NEXT:    vnsrl.wi v9, v9, 0
-; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
+; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, tu, ma
```
Comment (topperc) [inline llvm/test/CodeGen/RISCV/rvv/fixed-vectors-shuffle-deinterleave.ll:381]: Would it be better to CONCAT_VECTORS the Lo and Hi using a 2x type, then widen the rest of the way with INSERT_SUBVECTOR?

Comment (mshockwave) [reply llvm/test/CodeGen/RISCV/rvv/fixed-vectors-shuffle-deinterleave.ll]: Yes it's better (no tu). It's fixed now.

**Review by topperc — APPROVED** [review]
LGTM

**Review by preames — APPROVED** [review]
LGTM
