### PR TITLE
[mlir][Linalg] Refine how broadcast dims are treated

### LINKED ISSUE #97247: [MLIR][Linalg] Vectorization Fail with reduction
Such linalg.generic can not be vetorized:
```
// mlir-opt test.mlir -transform-interpreter
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>
module {
  func.func @generic_1_12_197_197_1_12_197_1_f32_547(%arg0: memref<1x12x197x197xf32>, %arg1: memref<1x12x197x1xf32>) attributes {global_kernel = ""} {
    linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%arg0 : memref<1x12x197x197xf32>) outs(%arg1 : memref<1x12x197x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %0 = arith.addf %in, %out : f32
      linalg.yield %0 : f32
    }
    return
  }
  module attributes {transform.with_named_sequence} {
    transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.readonly}) {
      %0 = transform.structured.match ops{["linalg.generic"]} in %arg0 : (!transform.any_op) -> !transform.any_op
      %1 = transform.get_parent_op %0 {isolated_from_above} : (!transform.any_op) -> !transform.any_op
      %2 = transform.structured.vectorize_children_and_apply_patterns %1 : (!transform.any_op) -> !transform.any_op
      transform.yield
    }
  }
}
```
It’s report:
```
mlir-opt: llvm-project/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:475: mlir::AffineMap reindexIndexingMap(mlir::AffineMap): Assertion `res.getNumDims() == res.getNumResults() && "expected reindexed map with same number of dims and results"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ../compiler/bin/mlir-opt --transform-interpreter test.mlir
 #0 0x0000559a97de75e4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/mls/community/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:22
 #1 0x0000559a97de7a05 PrintStackTraceSignalHandler(void*) /home/mls/community/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x0000559a97de4e55 llvm::sys::RunSignalHandlers() /home/mls/community/llvm-project/llvm/lib/Support/Signals.cpp:105:20
 #3 0x0000559a97de6e7c SignalHandler(int) /home/mls/community/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f87452ad520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f87453019fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x00007f87453019fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #7 0x00007f87453019fc pthread_kill ./nptl/pthread_kill.c:89:10
 #8 0x00007f87452ad476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x00007f87452937f3 abort ./stdlib/abort.c:81:7
#10 0x00007f874529371b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#11 0x00007f87452a4e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#12 0x0000559a998ef6ea reindexIndexingMap(mlir::AffineMap) /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:477:10
#13 0x0000559a998f3eb1 vectorizeAsLinalgGeneric(mlir::RewriterBase&, VectorizationState&, mlir::linalg::LinalgOp, llvm::SmallVectorImpl<mlir::Value>&) /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:1334:35
#14 0x0000559a99901c59 auto mlir::linalg::vectorize(mlir::RewriterBase&, mlir::Operation*, llvm::ArrayRef<long>, llvm::ArrayRef<bool>, bool, bool)::'lambda'(auto)::operator()<mlir::linalg::LinalgOp>(auto) const /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:2064:79
#15 0x0000559a99901ced llvm::TypeSwitch<mlir::Operation*, mlir::LogicalResult>& llvm::TypeSwitch<mlir::Operation*, mlir::LogicalResult>::Case<mlir::linalg::LinalgOp, mlir::linalg::vectorize(mlir::RewriterBase&, mlir::Operation*, llvm::ArrayRef<long>, llvm::ArrayRef<bool>, bool, bool)::'lambda'(auto)>(mlir::linalg::vectorize(mlir::RewriterBase&, mlir::Operation*, llvm::ArrayRef<long>, llvm::ArrayRef<bool>, bool, bool)::'lambda'(auto)&&) /home/mls/community/llvm-project/llvm/include/llvm/ADT/TypeSwitch.h:102:28
#16 0x0000559a998f8a38 mlir::linalg::vectorize(mlir::RewriterBase&, mlir::Operation*, llvm::ArrayRef<long>, llvm::ArrayRef<bool>, bool, bool) /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:2036:34
#17 0x0000559a99346b2a (anonymous namespace)::VectorizationPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp:3309:21
#18 0x0000559aa1b2686a mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>)::'lambda'()::operator()() const /home/mls/community/llvm-project/mlir/lib/Rewrite/PatternApplicator.cpp:212:46
#19 0x0000559aa1b2722f void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>)::'lambda'()>(long) /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:40
#20 0x0000559a97e0a872 llvm::function_ref<void ()>::operator()() const /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:62
#21 0x0000559aa1b2a63f void mlir::MLIRContext::executeAction<mlir::ApplyPatternAction, mlir::Pattern const&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pattern const&) /home/mls/community/llvm-project/mlir/include/mlir/IR/MLIRContext.h:276:3
#22 0x0000559aa1b26fdc mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) /home/mls/community/llvm-project/mlir/lib/Rewrite/PatternApplicator.cpp:233:5
#23 0x0000559a9d57d0ae (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist() /home/mls/community/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:615:32
#24 0x0000559a9d57e252 (anonymous namespace)::RegionPatternRewriteDriver::simplify(bool*) &&::'lambda2'()::operator()() const /home/mls/community/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:874:28
#25 0x0000559a9d57f4a6 void llvm::function_ref<void ()>::callback_fn<(anonymous namespace)::RegionPatternRewriteDriver::simplify(bool*) &&::'lambda2'()>(long) /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:40
#26 0x0000559a97e0a872 llvm::function_ref<void ()>::operator()() const /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:62
#27 0x0000559a9d57f1ef void mlir::MLIRContext::executeAction<(anonymous namespace)::GreedyPatternRewriteIteration, long&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, long&) /home/mls/community/llvm-project/mlir/include/mlir/IR/MLIRContext.h:276:3
#28 0x0000559a9d57e545 (anonymous namespace)::RegionPatternRewriteDriver::simplify(bool*) && /home/mls/community/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:887:3
#29 0x0000559a9d57e69a mlir::applyPatternsAndFoldGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*) /home/mls/community/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:919:55
#30 0x0000559a97fe66b6 mlir::applyPatternsAndFoldGreedily(mlir::Operation*, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*) /home/mls/community/llvm-project/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h:159:37
#31 0x0000559a99346ffb mlir::transform::VectorizeChildrenAndApplyPatternsOp::applyToOne(mlir::transform::TransformRewriter&, mlir::Operation*, mlir::transform::ApplyToEachResultList&, mlir::transform::TransformState&) /home/mls/community/llvm-project/mlir/lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp:3364:13
#32 0x0000559a9929d4a2 mlir::DiagnosedSilenceableFailure mlir::transform::detail::applyTransformToEach<mlir::transform::VectorizeChildrenAndApplyPatternsOp, llvm::iterator_range<llvm::filter_iterator_impl<mlir::Operation* const*, mlir::transform::TransformState::getPayloadOps(mlir::Value) const::'lambda'(mlir::Operation*), std::bidirectional_iterator_tag>>&>(mlir::transform::VectorizeChildrenAndApplyPatternsOp, mlir::transform::TransformRewriter&, llvm::iterator_range<llvm::filter_iterator_impl<mlir::Operation* const*, mlir::transform::TransformState::getPayloadOps(mlir::Value) const::'lambda'(mlir::Operation*), std::bidirectional_iterator_tag>>&, llvm::SmallVectorImpl<mlir::transform::ApplyToEachResultList>&, mlir::transform::TransformState&) /home/mls/community/llvm-project/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h:1510:30
#33 0x0000559a992928d3 mlir::transform::TransformEachOpTrait<mlir::transform::VectorizeChildrenAndApplyPatternsOp>::apply(mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/llvm-project/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h:1584:31
#34 0x0000559a992862f8 mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Model<mlir::transform::VectorizeChildrenAndApplyPatternsOp>::apply(mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/build-llvm/tools/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h.inc:478:1
#35 0x0000559aa1ad648c mlir::transform::TransformOpInterface::apply(mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/build-llvm/tools/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.cpp.inc:62:3
#36 0x0000559aa1acf020 mlir::transform::TransformState::applyTransform(mlir::transform::TransformOpInterface) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/Interfaces/TransformInterfaces.cpp:955:19
#37 0x0000559a9bd3cc10 applySequenceBlock(mlir::Block&, mlir::transform::FailurePropagationMode, mlir::transform::TransformState&, mlir::transform::TransformResults&) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/IR/TransformOps.cpp:1789:33
#38 0x0000559a9bd3f77a mlir::transform::NamedSequenceOp::apply(mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/IR/TransformOps.cpp:2157:1
#39 0x0000559a9bca69c0 mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Model<mlir::transform::NamedSequenceOp>::apply(mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/build-llvm/tools/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h.inc:478:1
#40 0x0000559aa1ad648c mlir::transform::TransformOpInterface::apply(mlir::transform::TransformRewriter&, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/mls/community/build-llvm/tools/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.cpp.inc:62:3
#41 0x0000559aa1acf020 mlir::transform::TransformState::applyTransform(mlir::transform::TransformOpInterface) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/Interfaces/TransformInterfaces.cpp:955:19
#42 0x0000559aa1ad60b5 mlir::transform::applyTransforms(mlir::Operation*, mlir::transform::TransformOpInterface, mlir::RaggedArray<llvm::PointerUnion<mlir::Operation*, mlir::Attribute, mlir::Value>> const&, mlir::transform::TransformOptions const&, bool) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/Interfaces/TransformInterfaces.cpp:2017:56
#43 0x0000559a9bdc2ba8 mlir::transform::applyTransformNamedSequence(mlir::RaggedArray<llvm::PointerUnion<mlir::Operation*, mlir::Attribute, mlir::Value>>, mlir::transform::TransformOpInterface, mlir::ModuleOp, mlir::transform::TransformOptions const&) /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/Transforms/TransformInterpreterUtils.cpp:234:25
#44 0x0000559a9bdb9c6f (anonymous namespace)::InterpreterPass::runOnOperation() /home/mls/community/llvm-project/mlir/lib/Dialect/Transform/Transforms/InterpreterPass.cpp:147:15
#45 0x0000559a9d459d19 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::'lambda0'()::operator()() const /home/mls/community/llvm-project/mlir/lib/Pass/Pass.cpp:524:57
#46 0x0000559a9d45d9fc void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::'lambda0'()>(long) /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:40
#47 0x0000559a97e0a872 llvm::function_ref<void ()>::operator()() const /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:62
#48 0x0000559a9d464f57 void mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) /home/mls/community/llvm-project/mlir/include/mlir/IR/MLIRContext.h:276:3
#49 0x0000559a9d45a13b mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /home/mls/community/llvm-project/mlir/lib/Pass/Pass.cpp:533:23
#50 0x0000559a9d45a416 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) /home/mls/community/llvm-project/mlir/lib/Pass/Pass.cpp:593:15
#51 0x0000559a9d45c342 mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) /home/mls/community/llvm-project/mlir/lib/Pass/Pass.cpp:904:40
#52 0x0000559a9d45c19a mlir::PassManager::run(mlir::Operation*) /home/mls/community/llvm-project/mlir/lib/Pass/Pass.cpp:884:69
#53 0x0000559a9d44c9c8 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:409:13
#54 0x0000559a9d44d0ae processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPoolInterface*) /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:474:26
#55 0x0000559a9d44d673 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) const /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:549:25
#56 0x0000559a9d44e7b7 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:52
#57 0x0000559a9d5e9351 llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) const /home/mls/community/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
#58 0x0000559a9d5e8be2 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) /home/mls/community/llvm-project/mlir/lib/Support/ToolUtilities.cpp:28:30
#59 0x0000559a9d44d7ed mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:552:31
#60 0x0000559a9d44dac7 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:590:13
#61 0x0000559a9d44dcbe mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) /home/mls/community/llvm-project/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:606:21
#62 0x0000559a97d44a27 main /home/mls/community/llvm-project/mlir/tools/mlir-opt/mlir-opt.cpp:311:0
#63 0x00007f8745294d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#64 0x00007f8745294e40 call_init ./csu/../csu/libc-start.c:128:20
#65 0x00007f8745294e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#66 0x0000559a97d444e5 _start (../compiler/bin/mlir-opt+0x1da74e5)
Aborted (core dumped)
```
I know the error is because the compressed dimension is not equal to the result dimension, but I don’t know how to fix it.
https://github.com/llvm/llvm-project/blob/bf536cc7db1b1e683af34f363f62fa2b655262cf/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L471-L478

### PR DESCRIPTION
**Pull request by banach-space**
This PR fixes how broadcast dims (identified as "zero" results in
permutation maps) corresponding to a reduction iterator are vectorised
in the case of generic Ops. Here's an example:

```mlir
  #map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
  #map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>

  func.func @generic_with_reduction_and_broadcast(%arg0: tensor<1x12x197x197xf32>) -> (tensor<1x12x197x1xf32>) {
    %0 = tensor.empty() : tensor<1x12x197x1xf32>

    %1 = linalg.generic {indexing_maps = [#map, #map1],
                        iterator_types = ["parallel", "parallel", "parallel", "reduction"]}
      ins(%arg0 : tensor<1x12x197x197xf32>)
      outs(%0 : tensor<1x12x197x1xf32>) {

    ^bb0(%in: f32, %out: f32):
      %818 = arith.addf %in, %out : f32
      linalg.yield %818 : f32
    } -> tensor<1x12x197x1xf32>
    return %1 : tensor<1x12x197x1xf32>
  }
```

This is a perfectly valid Generic Op, but currently triggers two issues
in the vectoriser. The root cause is this map:

```mlir
  #map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>
```

This map triggers an assert in `reindexIndexingMap` -  this hook
incorrectly assumes that every result in the input map is a `dim`
expression and that there are no constants. That's not the case in this
example. `reindexIndexingMap` is extended to allow maps like the one
above. For now, only constant "zero" results are allowed. This can be
extended in the future once a good motivating example is available.

Separately, the permutation map highlighted above "breaks" mask
calculation (ATM masks are always computed, even in the presence of
static shapes). When applying the following permutation:
```mlir
  (d0, d1, d2, d3) -> (d0, d1, d2, 0)
```

to these canonical shapes (corresponding to the example above):
```
  (1, 12, 197, 197)
```
we end up with the following error:
```bash
error: vector types must have positive constant sizes but got 1, 12, 197, 0
```

The error makes sense and indicates that we should update the
permutation map above to:
```
  (d0, d1, d2, d3) -> (d0, d1, d2)
```

This would correctly give the following vector type:
```
  vector<1x12x197xi1>
```

Fixes #97247

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
I have not looked into details of this PR, and there is value in having the lower levels of the stack being robust, but 
```
 #map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>
```
is not the canonical representation of broadcast IMO. This is.

```
 #map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>
```

So just signalling that here.

File: mlir/include/mlir/IR/AffineMap.h [hunk 1]
```diff
@@ -346,6 +346,10 @@ class AffineMap {
   /// returns the resulting values. `this` must be symbol-less.
   SmallVector<int64_t, 4> compose(ArrayRef<int64_t> values) const;
 
+  size_t numOfZeroResults() const;
+
+  AffineMap dropZeros();
```
Comment (MacDue) [inline mlir/include/mlir/IR/AffineMap.h:351]: Missing doc comments

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp [hunk 2]
```diff
@@ -629,7 +629,21 @@ static Value buildVectorWrite(RewriterBase &rewriter, Value value,
...
+  //    (1, 16, 16, 4)
+  // we would get:
+  //    (1, 16, 16, 0)
+  // Instead, we should extract the following map:
+  //    (d0, d1, d2, d3) -> (d0, d1, d2)
+  // This way, the corresponding vector/mask type will be:
+  //    vector<1x16x16xty>
+  // rather than:
+  //    vector<1x16x16x0xty>
+  auto opOperantMapWithoutZeros = opOperandMap.dropZeros();
```
Comment (ftynse) [inline mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:644]: Nit: expand auto plz.

File: mlir/lib/IR/AffineMap.cpp [hunk 3]
```diff
@@ -540,6 +540,18 @@ AffineMap AffineMap::dropResults(const llvm::SmallBitVector &positions) const {
   return AffineMap::get(getNumDims(), getNumSymbols(), exprs, getContext());
 }
 
+AffineMap AffineMap::dropZeros() {
+  auto exprs = llvm::to_vector<4>(getResults());
+  SmallVector<AffineExpr, 8> newExprs;
```
Comment (ftynse) [inline mlir/lib/IR/AffineMap.cpp:545]:
```suggestion
  auto exprs = llvm::to_vector(getResults());
  SmallVector<AffineExpr> newExprs;
```

File: mlir/lib/IR/AffineMap.cpp [hunk 4]
```diff
@@ -540,6 +540,18 @@ AffineMap AffineMap::dropResults(const llvm::SmallBitVector &positions) const {
...
+
+  for (auto expr : getResults()) {
+    auto constExpr = dyn_cast<AffineConstantExpr>(expr);
+    if (!constExpr)
```
Comment (ftynse) [inline mlir/lib/IR/AffineMap.cpp:549]: This will ignore _any_ constant, not just zero as the name implies.

File: mlir/include/mlir/IR/AffineMap.h (hunk 1 above)
Comment (dcaballe) [reply mlir/include/mlir/IR/AffineMap.h:351]: Could you please check if we have a utility for this already? As I mentioned in another PR, we have so many AffineMap utilities that sometimes it's not easy to find what we need :)

File: mlir/lib/IR/AffineMap.cpp [hunk 5]
```diff
@@ -579,6 +591,17 @@ SmallVector<int64_t, 4> AffineMap::compose(ArrayRef<int64_t> values) const {
   return res;
 }
 
+size_t AffineMap::numOfZeroResults() const {
```
Comment (dcaballe) [inline mlir/lib/IR/AffineMap.cpp:594]: nit: `getNum...`

File: mlir/lib/IR/AffineMap.cpp [hunk 6]
```diff
@@ -540,6 +540,18 @@ AffineMap AffineMap::dropResults(const llvm::SmallBitVector &positions) const {
   return AffineMap::get(getNumDims(), getNumSymbols(), exprs, getContext());
 }
 
+AffineMap AffineMap::dropZeros() {
```
Comment (dcaballe) [inline mlir/lib/IR/AffineMap.cpp:543]: nit: `dropZeroResults`?

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp [hunk 7]
```diff
@@ -629,7 +629,21 @@ static Value buildVectorWrite(RewriterBase &rewriter, Value value,
...
+  write =
+      state.maskOperation(rewriter, write, linalgOp, opOperantMapWithoutZeros);
```
Comment (dcaballe) [inline mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:646]: What happens with the xfer read counterpart? Should we move this logic into `maskOperation`?

**Review by dcaballe — COMMENTED** [review]
Thanks for fixing this! Left a few comments.

I would also revisit the commit description as this seems to be a reduction problem, not a broadcast problem? Or maybe both broadcast and reduction?

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp (hunk 2 above)
Comment (banach-space) [reply mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:644]: Done

File: mlir/lib/IR/AffineMap.cpp (hunk 4 above)
Comment (banach-space) [reply mlir/lib/IR/AffineMap.cpp:549]: Fixed, thanks!

File: mlir/include/mlir/IR/AffineMap.h (hunk 1 above)
Comment (banach-space) [reply mlir/include/mlir/IR/AffineMap.h:351]: I saw your comment on the other PR and that immediately made me think about this :)

I couldn't find anything that would help for these specific case. However, we do have:
* [getBroadcastDims()](https://github.com/llvm/llvm-project/blob/867ff2d4268ca7eed89a24f100b67b68f5329439/mlir/include/mlir/IR/AffineMap.h#L149-L155)
  * NOTE: to be removed in https://github.com/llvm/llvm-project/pull/99341/,
* [isMinorIdentityWithBroadcasting()](https://github.com/llvm/llvm-project/blob/867ff2d4268ca7eed89a24f100b67b68f5329439/mlir/include/mlir/IR/AffineMap.h#L157-L164),
* [dropResults()](https://github.com/llvm/llvm-project/blob/867ff2d4268ca7eed89a24f100b67b68f5329439/mlir/include/mlir/IR/AffineMap.h#L297-L307).

So, there's scope for re-use. 

Here's what I suggest:
*  Introduce `SmallVector<unsigned> getZeroResults()`
   * It would return the positions of **zero**/**bcast** results.
* Simplify `isMinorIdentityWithBroadcasting()`
  * It would use the newly introduced `getZeroResults()`.
* Replace `dropZeros()` (proposed in this PR) with a call to `dropResults(getZeroResults())`.

I would still have to introduce `getZeroResults()` (i.e. yet another hook in this file), but would avoid introducing `dropZeros()` :) WDYT?

Comment (dcaballe) [reply mlir/include/mlir/IR/AffineMap.h]: If there is nothing that provides what you need I would just introduce what you need and try to reuse/refactor at implementation level.

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp (hunk 7 above)
Comment (banach-space) [reply mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:647]: > What happens with the xfer read counterpart? 

It turns out you've already implemented that :) 

https://github.com/llvm/llvm-project/blob/2ba3fe7356f065757a2279f65e4ef5c8f1476293/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L1327-L1335

> Should we move this logic into maskOperation?

Yes! Sending an update shortly.

**Comment by banach-space** [comment]
Ping :)

**Comment by banach-space** [comment]
@dcaballe , could you take another look?

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp [hunk 8]
```diff
@@ -224,10 +224,10 @@ struct VectorizationState {
   /// Masks an operation with the canonical vector mask if the operation needs
   /// masking. Returns the masked operation or the original operation if masking
   /// is not needed. If provided, the canonical mask for this operation is
-  /// permuted using `maybeMaskingMap`.
+  /// permuted using `maybeIndexingMap`.
   Operation *
   maskOperation(RewriterBase &rewriter, Operation *opToMask, LinalgOp linalgOp,
-                std::optional<AffineMap> maybeMaskingMap = std::nullopt);
+                std::optional<AffineMap> maybeIndexingMap = std::nullopt);
```
Comment (dcaballe) [inline mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:230]: I think indexing map would be misleading here as it's a term very tight to linalg ops and here we may apply it to arbitrary ops. Both will evolve in different ways for more complex vectorization scenarios, like those with control flow.

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp [hunk 9]
```diff
@@ -1317,16 +1330,6 @@ vectorizeAsLinalgGeneric(RewriterBase &rewriter, VectorizationState &state,
...
-    // Remove zeros from indexing map to use it as masking map.
-    SmallVector<int64_t> zeroPos;
-    auto results = indexingMap.getResults();
-    for (const auto &result : llvm::enumerate(results)) {
-      if (isa<AffineConstantExpr>(result.value())) {
-        zeroPos.push_back(result.index());
-      }
-    }
-    AffineMap maskingMap = indexingMap.dropResults(zeroPos);
-
```
Comment (dcaballe) [inline mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:1329]: Oh, ok, we are just moving this into `maskOperation` because we have other entry points where this was not executed... Got it.

**Review by dcaballe — APPROVED** [review]

File: mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp (hunk 8 above)
Comment (banach-space) [reply mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:230]: Thanks for reminding me about this!

Right now we are actually passing the indexing map whenever this hook is used - this is just to documenting the state today. So let me leave it as is.

I will send a follow-on PR in which I'll try to clarify the difference between the two maps.
