### PR TITLE
[MachineLICM] Fix incorrect CSE on hoisted const load

### LINKED ISSUE #72855: Wrong code at -O1 on x86_64-linux_gnu(recent regression)
Clang at -O1 produces the wrong code.

Bisected to 63917e1975bd69ef4084f02d378b0b920046be3a, which was committed by @igogo-x86 

Compiler explorer: https://godbolt.org/z/jdPPzP3P6

```console
% cat a.c
int printf(const char *, ...);
int a;
int *g = &a, *m = &a, *n = &a;
short o;
int p(char *b, long c, long *d) {
  char *e = b;
  long f = *d;
  for (; c && f; --c, ++f, ++e)
    ;
  return e - b;
}
int t(long h, long i) {
  char j;
  long k[] = {i};
  int l = p(&j, h, k);
  return l;
}
long q(int *r) {
  *m = 4;
  for (;;)
    for (; *r >= 0;) {
      *g = *n % 5 == 1;
      for (;;)
        for (; t(*n + 5, 3124342948) <= 5;)
          return 0;
    }
}
int main() {
  int s = a;
  q(&s);
  printf("%d\n", o);
}
%
% clang -O0 -fsanitize=address,undefined a.c && ./a.out
0
% clang -O1 a.c && ./a.out
Timeout
%
```

### PR DESCRIPTION
**Pull request by igogo-x86**
When hoisting an invariant load, we should not combine it with an existing load through common subexpression elimination (CSE). This is because there might be memory-changing instructions between the existing load and the end of the block entering the loop.

Fixes https://github.com/llvm/llvm-project/issues/72855

### CODE REVIEW

**Review by davemgreen — APPROVED** [review]
This sounds OK to me. LGTM

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 1]
```diff
@@ -1422,6 +1422,11 @@ bool MachineLICMBase::EliminateCSE(
   if (MI->isImplicitDef())
     return false;
 
+  // Do not CSE normal loads because between them could be store instructions
+  // that change the loaded value
+  if (MI->mayLoad() && !MI->isDereferenceableInvariantLoad())
```
Comment (david-arm) [inline llvm/lib/CodeGen/MachineLICM.cpp:1427]: Is this still guaranteed to be safe for dereferenceable invariant loads? Could we have a situation where we hoist these memory accesses from a loop because they appear invariant:

  load a
  store b
  load a

where store b could alias with load a? In this case we will hoist all three to the preheader - do we also CSE the two loads? If so, that's unsafe too.

Comment (david-arm) [reply llvm/lib/CodeGen/MachineLICM.cpp:1427]: Sorry, just ignore me. I think I probably misunderstood the problem you're trying to solve. I guess I'm just trying to understand why we don't just always return false for all loads.

Comment (igogo-x86) [reply llvm/lib/CodeGen/MachineLICM.cpp:1427]: That's a particular case where we load constant from memory like this:
```
fadd float %tmp3.i, 1.000000e+10
```

Also, if at least one store is in the loop, we don't hoist loads.
