### PR TITLE
[AArch64][SVE] Allow basic use of `target("aarch64.svcount")` with +sve 

### LINKED ISSUE #167462: [AArch64] Assertion `DAG.getTargetLoweringInfo().isTypeLegal(PartVT) && "Copying to an illegal type!"' failed.
Reproducer:
https://godbolt.org/z/EeTvsdW5h

Backtrace:
```console
llc: /root/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:520: void getCopyToParts(llvm::SelectionDAG&, const llvm::SDLoc&, llvm::SDValue, llvm::SDValue*, unsigned int, llvm::MVT, const llvm::Value*, std::optional<unsigned int>, llvm::ISD::NodeType): Assertion `DAG.getTargetLoweringInfo().isTypeLegal(PartVT) && "Copying to an illegal type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'AArch64 Instruction Selection' on function '@_Z3foov'
 #0 0x00000000041b1ab8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x41b1ab8)
 #1 0x00000000041ae964 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000079ba03e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000079ba03e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x000079ba03e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x000079ba03e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x000079ba03e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x000079ba03e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x0000000003e56147 getCopyToParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue*, unsigned int, llvm::MVT, llvm::Value const*, std::optional<unsigned int>, llvm::ISD::NodeType) SelectionDAGBuilder.cpp:0:0
 #9 0x0000000003e5d6eb llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e5d6eb)
#10 0x0000000003e67dd4 llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e67dd4)
#11 0x0000000003e84fc5 llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*, llvm::TargetLowering::PtrAuthInfo const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e84fc5)
#12 0x0000000003e9b2cc llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e9b2cc)
#13 0x0000000003eafa02 llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3eafa02)
#14 0x0000000003f4290d llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, bool&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f4290d)
#15 0x0000000003f433d8 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f433d8)
#16 0x0000000003f44e55 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f44e55)
#17 0x0000000003f3059f llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f3059f)
#18 0x0000000003090fc9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#19 0x00000000036e16a6 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x36e16a6)
#20 0x00000000036e1a51 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x36e1a51)
#21 0x00000000036e22bf llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x36e22bf)
#22 0x00000000008fe402 compileModule(char**, llvm::LLVMContext&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) llc.cpp:0:0
#23 0x00000000007c9cb9 main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x7c9cb9)
#24 0x000079ba03e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#25 0x000079ba03e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#26 0x00000000008f2c35 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x8f2c35)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

Comes from the following program:
```cpp
void f(__SVCount_t, __SVCount_t);

void foo() { f(__SVCount_t(), __SVCount_t()); }
```

This crashes with `clang++ -c -mcpu=neoverse-v1 bug.cpp`.

### PR DESCRIPTION
**Pull request by MacDue**
This prevents the backend from crashing for basic uses of __SVCount_t type (e.g., as function arguments), without +sve2p1 or +sme2.
    
Fixes #167462

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -473,14 +475,11 @@ AArch64TargetLowering::AArch64TargetLowering(const TargetMachine &TM,
...
-    setOperationPromotedToType(ISD::LOAD, MVT::aarch64svcount, MVT::nxv16i1);
-    setOperationPromotedToType(ISD::STORE, MVT::aarch64svcount, MVT::nxv16i1);
+  setOperationPromotedToType(ISD::LOAD, MVT::aarch64svcount, MVT::nxv16i1);
+  setOperationPromotedToType(ISD::STORE, MVT::aarch64svcount, MVT::nxv16i1);
 
-    setOperationAction(ISD::SELECT, MVT::aarch64svcount, Custom);
-    setOperationAction(ISD::SELECT_CC, MVT::aarch64svcount, Expand);
-  }
+  setOperationAction(ISD::SELECT, MVT::aarch64svcount, Custom);
+  setOperationAction(ISD::SELECT_CC, MVT::aarch64svcount, Expand);
```
Comment (paulwalker-arm) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp]: Can you move these into an existing `isSVEorStreamingSVEAvailable` setOperationAction block?

Comment (MacDue) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp]: I've moved these close to where actions for other predicate types are set, if that's what you meant.

File: llvm/test/CodeGen/AArch64/aarch64-svcount-basic.ll [hunk 2]
```diff
@@ -0,0 +1,51 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
+; RUN: llc < %s -mtriple=aarch64-linux-gnu -mattr=+sve | FileCheck %s
+
+;; This file tests basic use of `target("aarch64.svcount")` works with only +sve.
```
Comment (paulwalker-arm) [inline llvm/test/CodeGen/AArch64/aarch64-svcount-basic.ll]: I think basic testing for svcount type is already covered by llvm/test/CodeGen/AArch64/sme-aarch64-svcount.ll, so perhaps you can downgrade its -mattr option instead?

**Review by paulwalker-arm — APPROVED** [review]
I'm not sure we need a new test file but otherwise this looks good to me.
