### PR TITLE
[clangd] Don't collect templated decls for builtin templates

### LINKED ISSUE #1906: Address boundary error for __make_integer_seq example
I was playing with *integer sequences* in cpp and came to the implementation of bits/utility.h header where I found the following minimal example:

```cpp
#include <cstddef>

template <typename _Tp, _Tp... _Idx> struct integer_sequence {
  typedef _Tp value_type;
  static constexpr size_t size() noexcept { return sizeof...(_Idx); }
};

/// Alias template make_integer_sequence
template <typename _Tp, _Tp _Num>
using make_integer_sequence
#if __has_builtin(__make_integer_seq)
    = __make_integer_seq<integer_sequence, _Tp, _Num>;
#else
    = integer_sequence<_Tp, __integer_pack(_Tp(_Num))...>;
#endif

int main(int argc, char *argv[]) { return 0; }
```

When running clangd --check=test.cpp (this is the file where i copy paste this) I get the following:

```shell
 #0 0x00007fd8984c350a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM-16.so+0xcc350a)
 #1 0x00007fd8984c0e66 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-16.so+0xcc0e66)
 #2 0x00007fd8984c40bb (/lib64/libLLVM-16.so+0xcc40bb)
 #3 0x00007fd89725fbb0 __restore_rt (/lib64/libc.so.6+0x3dbb0)
 #4 0x000000000094c3ce (/usr/bin/clangd+0x94c3ce)
 #5 0x000000000094a3a3 (/usr/bin/clangd+0x94a3a3)
 #6 0x0000000000676bb3 (/usr/bin/clangd+0x676bb3)
 #7 0x000000000066a22d (/usr/bin/clangd+0x66a22d)
 #8 0x00007fd897249b8a __libc_start_call_main (/lib64/libc.so.6+0x27b8a)
 #9 0x00007fd897249c4b __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c4b)
#10 0x000000000057bcd5 (/usr/bin/clangd+0x57bcd5)
fish: Job 1, 'clangd --check=test.cpp' terminated by signal SIGSEGV (Address boundary error)
```

### PR DESCRIPTION
**Pull request by zyn0217**
Builtin templates e.g. `__make_integer_seq`, `__type_pack_element` are such that they don't have alias *Decls*. [D133262](https://reviews.llvm.org/D133262) marked these as alias templates, resulting in an attempt to collect their null "using" Decls within our `TargetFinder`.

This fixes https://github.com/clangd/clangd/issues/1906.

### CODE REVIEW

**Review by HighCommander4 — APPROVED** [review]
Thanks!

File: clang-tools-extra/clangd/FindTarget.cpp [hunk 1]
```diff
@@ -443,9 +443,15 @@ struct TargetFinder {
...
           // template of the underlying type.
-          Outer.report(
-              TST->getTemplateName().getAsTemplateDecl()->getTemplatedDecl(),
-              Flags | Rel::Alias | Rel::TemplatePattern);
+
+          // Builtin templates e.g. __make_integer_seq, __type_pack_element
+          // are such that they don't have alias *decls*. Even then, we still
+          // traverse their desugared *types* so that instantiated decls are
+          // collected.
+          if (NamedDecl *D = TST->getTemplateName()
```
Comment (hokein) [inline clang-tools-extra/clangd/FindTarget.cpp:451]: nit: maybe write the code like below, being explicit about the builtin template cases.
```
const TemplateDecl *TD = TST->getTemplateName().getAsTemplateDecl();
if (isa<BuiltinTemplateDecl>(TD))
    return;
...
```

**Review by hokein — APPROVED** [review]
