### PR TITLE
[llvm-ml] Remove unsafe getCurrentSegmentOnly() call

### LINKED ISSUE #123189: [ms] [llvm-ml] SIGSEGV in `checkForValidSection` in MasmParser
I'm trying to cross-compile the OCaml compiler with a Debian host, targeting `x86_64-pc-windows` with `clang-cl`. I'm running into a segfault from `llvm-ml` (the MASM assembler), a drop-in replacement for Microsoft's `ml64`. I hit the issue with LLVM 18 and LLVM 20 (ea14bdb0356cdda727ac032470f6a0a2102d1281 as the time of writing). Here is a reproducer, as a Dockerfile (build with `docker build --platform linux/amd64 .`), and the backtrace. I'm also attaching the offending asm file as a text file.

[amd64nt.txt](https://github.com/user-attachments/files/18439069/amd64nt.txt)

```Dockerfile
# syntax=docker/dockerfile:1
FROM debian:experimental
ARG LLVM_VERSION=20

ENV DEBUGINFOD_URLS="https://debuginfod.debian.net"
COPY <<EOF /etc/apt/sources.list.d/debug.list
deb http://deb.debian.org/debian-debug/ experimental-debug main
EOF

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && DEBIAN_FRONTEND=noninteractive apt upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y \
    clang-$LLVM_VERSION clang-$LLVM_VERSION-dbgsym \
    clang-tools-$LLVM_VERSION clang-tools-$LLVM_VERSION-dbgsym \
    lld-$LLVM_VERSION lld-$LLVM_VERSION-dbgsym \
    llvm-$LLVM_VERSION llvm-$LLVM_VERSION-dbgsym \
    lldb-$LLVM_VERSION lldb-$LLVM_VERSION-dbgsym \
    make gdb
ADD --keep-git-dir --link https://github.com/ocaml/ocaml.git /root/ocaml
WORKDIR /root/ocaml

ENV LLVM_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-$LLVM_VERSION

RUN clang-cl-20 -nologo -EP -TC runtime/caml/domain_state.tbl > runtime/domain_state.inc

# llvm-ml-20 -m64 dislikes parentheses on macro calls
RUN sed -e 's/(//g' -e 's/)//g' -i runtime/domain_state.inc

# llvm-ml-20 doesn't understand NEAR
RUN sed -E -e 's/(EXTRN.*):.*NEAR/\1:PROC/g' -i runtime/amd64nt.asm

RUN llvm-ml-20 -m64 -nologo -Iruntime -c -Foruntime/amd64nt.obj runtime/amd64nt.asm
```

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-ml-20 -m64 -nologo -Iruntime -c -Foruntime/amd64nt.obj runtime/amd64nt.asm
 #0 0x00007ffff7fa117a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x00007ffff7f9ed14 llvm::sys::RunSignalHandlers() build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Signals.cpp:106:18
 #2 0x00007ffff7fa182b SignalHandler build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007ffff6ac0da0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fda0)
 #4 0x00007ffff98923a2 checkForValidSection build-llvm/tools/clang/stage2-bins/llvm/lib/MC/MCParser/MasmParser.cpp:1457:31
 #5 0x00007ffff9895133 parseStatement build-llvm/tools/clang/stage2-bins/llvm/lib/MC/MCParser/MasmParser.cpp:0:7
 #6 0x00007ffff988d2a5 Run build-llvm/tools/clang/stage2-bins/llvm/lib/MC/MCParser/MasmParser.cpp:0:0
 #7 0x000055555555d0f0 AssembleInput build-llvm/tools/clang/stage2-bins/llvm/tools/llvm-ml/llvm-ml.cpp:186:13
 #8 0x000055555555bc9a llvm_ml_main build-llvm/tools/clang/stage2-bins/llvm/tools/llvm-ml/llvm-ml.cpp:0:11
 #9 0x000055555555e45a main build-llvm/tools/clang/stage2-bins/build-llvm/tools/clang/stage2-bins/tools/llvm-ml/llvm-ml-driver.cpp:17:10
#10 0x00007ffff6aaad68 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#11 0x00007ffff6aaae25 call_init ./csu/../csu/libc-start.c:128:20
#12 0x00007ffff6aaae25 __libc_start_main ./csu/../csu/libc-start.c:347:5
#13 0x0000555555559d71 (/usr/lib/llvm-20/bin/llvm-ml+0x5d71)
Segmentation fault
```

https://github.com/llvm/llvm-project/blob/628976c8345e235d4f71a0715f1990ad8b5bbcf7/llvm/lib/MC/MCParser/MasmParser.cpp#L1456-L1463

Presumably `getStreamer()` returns a `nullptr`.

It's possibly similar to #97635, I'll ping the participants: @sivan-shani @MaskRay.
Thanks for any help!

### PR DESCRIPTION
**Pull request by ericastor**
This call was made unsafe recently, but was not fixed in db48f1a1764023f8efeb055e343b967d1eb37d19 (the commit that fixed the parallel code in AsmParser.cpp).

Fixes #123189

### CODE REVIEW

**Comment by MaskRay** [comment]
Could you add a test?

**Comment by ericastor** [comment]
I can try to minimize the issue & convert it into a test, but I'm not quite clear on what circumstances actually provoke it. For example, neither db48f1a1764023f8efeb055e343b967d1eb37d19 nor 626eef5ecf92e98cbfccfa6134e0a760e7592813 seemed to include a test to verify that their changes were separately safe?

**Comment by ericastor** [comment]
Added tests as requested.

**Comment by MaskRay** [comment]
The two commits intended to simplify MC internals.
For the gas compatible AsmParser.cpp, we have comprehensive tests and passing the testsuite gives contributors very high confidence in the patches.
I apologize if the simplification actually caused regression to MasmParser.cpp. That was not my intention.

That said, I should be honest. I am deeply concerned with the state of MasmParser.cpp.
When MasmParser.cpp was forked from AsmParser.cpp, it copied a lot of code from AsmParser.
A lot of pieces are unreachable or untested for llvm-ml.

I don't think it is reasonable to require contributors that refactor MC to understand
llvm-ml internals and make perfect judgement on whether a refactoring will regress llvm-ml or not. 
You have to write tests to guard against regressions.

File: llvm/lib/MC/MCParser/COFFMasmParser.cpp [hunk 1]
```diff
@@ -441,6 +441,11 @@ bool COFFMasmParser::parseDirectiveOption(StringRef Directive, SMLoc Loc) {
 ///          statements
 ///      label "endproc"
 bool COFFMasmParser::parseDirectiveProc(StringRef Directive, SMLoc Loc) {
+  if (!getStreamer().getCurrentFragment()) {
+    return Error(getTok().getLoc(), "expected section directive before '" +
```
Comment (MaskRay) [inline llvm/lib/MC/MCParser/COFFMasmParser.cpp:445]: The convention is to just state `expected something` and omit `before directive ...`. The `before directive` information is obvious from the source line that is printed

**Comment by ericastor** [comment]
> The two commits intended to simplify MC internals. For the gas compatible AsmParser.cpp, we have comprehensive tests and passing the testsuite gives contributors very high confidence in the patches. I apologize if the simplification actually caused regression to MasmParser.cpp. That was not my intention.
> 
> That said, I should be honest. I am deeply concerned with the state of MasmParser.cpp. When MasmParser.cpp was forked from AsmParser.cpp, it copied a lot of code from AsmParser. A lot of pieces are unreachable or untested for llvm-ml.
> 
> I don't think it is reasonable to require contributors that refactor MC to understand llvm-ml internals and make perfect judgement on whether a refactoring will regress llvm-ml or not. You have to write tests to guard against regressions.

I agree. To be honest, I was surprised the test suite *didn't* already cover this case, so this was definitely a mistake on my part. I'm just interested which tests were broken with this refactor of MC, but I'm pleased to hear that they *were* broken and detected the issue.

In terms of reducing MasmParser.cpp... I agree that it could use a lot of cleanup. I would very much like to work on improving the test case coverage. Is there an easy way to get coverage reporting out of the LLVM test suite? I'm apparently not familiar with it, and since it's very much designed as more of an integration-test framework, I don't know any obvious tricks.

File: llvm/lib/MC/MCParser/COFFMasmParser.cpp (hunk 1 above)
Comment (ericastor) [reply llvm/lib/MC/MCParser/COFFMasmParser.cpp]: Revised accordingly.

File: llvm/lib/MC/MCParser/COFFMasmParser.cpp [hunk 2]
```diff
@@ -441,6 +441,10 @@ bool COFFMasmParser::parseDirectiveOption(StringRef Directive, SMLoc Loc) {
 ///          statements
 ///      label "endproc"
 bool COFFMasmParser::parseDirectiveProc(StringRef Directive, SMLoc Loc) {
+  if (!getStreamer().getCurrentFragment()) {
+    return Error(getTok().getLoc(), "expected section directive");
```
Comment (MaskRay) [inline llvm/lib/MC/MCParser/COFFMasmParser.cpp:445]: omit braces for the single line simple statement

**Review by MaskRay — APPROVED** [review]

File: llvm/test/tools/llvm-ml/bare_proc_error.asm [hunk 3]
```diff
@@ -0,0 +1,7 @@
+; RUN: not llvm-ml -filetype=s %s /Fo /dev/null 2>&1 | FileCheck %s
+
+; CHECK: :[[# @LINE + 1]]:1: error: expected section directive before 'PROC' directive
```
Comment (MaskRay) [inline llvm/test/tools/llvm-ml/bare_proc_error.asm:3]: This is ok, but in most cases we omit spaces beside `+`: `LINE+1`
