### PR TITLE
[clang] check deduction consistency when partial ordering function templates

### LINKED ISSUE #18291: missing check that deduction actually succeeded when partially ordering function templates
|  |  |
| --- | --- |
| Bugzilla Link | [17917](https://llvm.org/bz17917) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Consider:
```c++
template<bool> struct enable_if { typedef void type; };
template <class T> class Foo {};
template <class X> constexpr bool check() { return true; }
template <class X, class Enable = void> struct Bar {};

#ifdef FUNCTION_ORDERING

template<class X> void func(Bar<X, typename enable_if<check<X>()>::type>) { }
template<class T> int func(Bar<Foo<T>>) {  return 0; }
int (*p)(Bar<Foo<int>>) = func;

#else

template<typename X> struct Bar<X, typename enable_if<check<X>()>::type> {};
template<typename X> struct Bar<Foo<X>> { typedef int type; };
Bar<Foo<int>>::type bar;

#endif
```
Per 14.5.5.2/1, the class template partial specialization partial ordering and the function template partial ordering above should behave exactly the same. But they don't: for clang, gcc, and edg, the `FUNCTION_ORDERING` case is accepted and the other (class ordering) case is rejected.

Morally, both cases should be rejected; this is ambiguous because the first template has the constraint that `enable_if<check<X>()>::type == void`, and the second template has the constraint that `X == Foo<T>` for some `T`. Clearly, neither of these implies the other.

Practically, we're missing a call to something like `FinishTemplateArgumentDeduction` in the `FunctionTemplateDecl` form of `isAtLeastAsSpecializedAs`: we fail to check that the deduction produces template arguments that make the deduced `A` compatible with the original `A` (as required by [temp.deduct.type]p1).

### PR DESCRIPTION
**Pull request by mizvekov**
This makes partial ordering of function templates consistent with other entities, by implementing [temp.deduct.type]p1 in that case.

Fixes #18291

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -859,8 +861,10 @@ class PackDeductionScope {
     // by this pack expansion, then clear out the deduction.
     DeducedFromEarlierParameter = !Deduced[Index].isNull();
     DeducedPack Pack(Index);
-    Pack.Saved = Deduced[Index];
-    Deduced[Index] = TemplateArgument();
+    if (!FinishingDeduction) {
+      Pack.Saved = Deduced[Index];
+      Deduced[Index] = TemplateArgument();
+    }
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:867]: A comment describing what `FinishingDeducing` is for would be useful. It looks like the intent is that in this mode we just gather information and don't update `Deduced` at all; if so, there's an update to `Deduced` in `finishConstruction` that you might have missed.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 2]
```diff
@@ -5399,11 +5434,85 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+      return TemplateDeductionResult::SubstitutionFailure;
+  }
+
+  if (auto *PA = dyn_cast<PackExpansionType>(A);
+      PA && !isa<PackExpansionType>(InstP))
+    A = PA->getPattern();
+  if (!S.Context.hasSameType(
+          S.Context.getUnqualifiedArrayType(InstP.getNonReferenceType()),
+          S.Context.getUnqualifiedArrayType(A.getNonReferenceType())))
+    return TemplateDeductionResult::NonDeducedMismatch;
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5494]: A cross-reference to [temp.deduct.call]/4 might be useful here. Do we need to handle the other differences allowed there? I'm thinking of cases like:

```c++
template<typename T> struct A {};
struct B : A<int> {};
template<typename U, typename V> void f(U, A<V>&); // #1
template<typename W> void f(W, B&); // #2
```

Is #2 more specialized than #1, by deducing V = int? (Maybe this doesn't matter because they'll never be equally good candidates in overload resolution, so we'll never try to partially order them?)

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 3]
```diff
@@ -5399,11 +5434,85 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+      Result != TemplateDeductionResult::Success)
+    return Result;
+
+  // Form the template argument list from the deduced template arguments.
+  TemplateArgumentList *SugaredDeducedArgumentList =
+      TemplateArgumentList::CreateCopy(S.Context, SugaredBuilder);
+  TemplateArgumentList *CanonicalDeducedArgumentList =
+      TemplateArgumentList::CreateCopy(S.Context, CanonicalBuilder);
+
+  Info.reset(SugaredDeducedArgumentList, CanonicalDeducedArgumentList);
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5466]: Doing this work for each parameter in turn seems unnecessarily expensive; can we do the setup steps once, and then for each parameter just do the subst and check?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 4]
```diff
@@ -5399,11 +5434,85 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+    return TemplateDeductionResult::NonDeducedMismatch;
+
+  // C++20 [temp.deduct]p5 - Only check constraints when all parameters have
+  // been deduced.
+  if (!IsIncomplete) {
+    if (auto Result = CheckDeducedArgumentConstraints(S, FTD, SugaredBuilder,
+                                                      CanonicalBuilder, Info);
+        Result != TemplateDeductionResult::Success)
+      return Result;
+  }
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5503]: Is this the right moment to do this? I would have expected we'd check constraints after we form the final template argument list and before we substitute into any parameter types.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 5]
```diff
@@ -5425,34 +5534,112 @@ static bool isAtLeastAsSpecializedAs(Sema &S, SourceLocation Loc,
...
+                /*PartialOrdering=*/true, /*FinishingDeduction=*/true,
+                [&FT2](Sema &S, TemplateParameterList *, int ArgIdx, QualType P,
+                       QualType A, TemplateDeductionInfo &Info,
+                       SmallVectorImpl<DeducedTemplateArgument> &Deduced,
+                       bool PartialOrdering) {
+                  return ::FinishTemplateArgumentDeduction(S, FT2, ArgIdx, P, A,
+                                                           Deduced, Info);
+                }) == TemplateDeductionResult::Success;
+      });
+    });
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5639]: Do we need to separately check the return type and the parameter types here, rather than checking the entire function type as a whole? (This is not quite the same: for example, checking the whole function type would also consider the exception specification.)

**Review by zygoloid — COMMENTED** [review]
Thanks!

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/stringview-nullptr.cpp [hunk 6]
```diff
@@ -30,98 +30,27 @@ class basic_string_view {
...
-template <typename CharT>
-constexpr bool operator<(type_identity_t<basic_string_view<CharT>>,
-                         basic_string_view<CharT>) {
-  return {};
-}
-template <typename CharT>
-constexpr bool operator<(basic_string_view<CharT>,
-                         type_identity_t<basic_string_view<CharT>>) {
-  return {};
-}
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/stringview-nullptr.cpp:46]: Yeah, I removed this before realizing this was implementing string_view overloads per wording.

I have created a new thread on the core reflector about this.

File: clang/lib/AST/ExprConstant.cpp [hunk 7]
```diff
@@ -5346,7 +5346,6 @@ static EvalStmtResult EvaluateStmt(StmtResult &Result, EvalInfo &Info,
     const Expr *RetExpr = cast<ReturnStmt>(S)->getRetValue();
     FullExpressionRAII Scope(Info);
     if (RetExpr && RetExpr->isValueDependent()) {
-      EvaluateDependentExpr(RetExpr, Info);
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/AST/ExprConstant.cpp:5349]: This is a pure function that's supposed to be called only for its return value, which is being discarded here.

That function has an assert internally that is firing when we transform a declrefexpr referencing a lambda.
This happens on a transform with an incomplete template argument list. Empty even, all template arguments being null.

I can double check for more details, but a transform pass without any actual transformation shouldn't produce errors.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:867]: Will do.

Yeah that's exactly it. The idea is to reuse the parts of the PackScope which help iterating a pack, but in a context where we are not producing a deduction, just checking a previous deduction.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 3 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5466]: Yeah, I thought about this as well, but forgot to follow up.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5503]: We seem to consistently follow the order I implemented here.

One reason I can think of, is that it would probably be too confusing to produce constraints check failure diagnostics before checking one thing even implies the other.

But doing it before would certainly simplify the implementation when we change the implementation to check only once.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 5 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5639]: Since the deduction itself ignores the exception specification (`TDF_AllowCompatibleFunctionType`), it would seem strange to check exception spec compatibility now, when we could have done that during deduction.

Otherwise, this would fail the first example in `ExplicitArgs` from `CXX/temp/temp.fct.spec/temp.deduct/temp.deduct.partial/p3.cpp`:
```C++
namespace ExplicitArgs {
  template<typename T, typename U>
  constexpr int f(U) noexcept(noexcept(T())) {
    return 0;
  }

  template<typename T>
  constexpr int f(T*) noexcept {
    return 1;
  }

  template<>
  constexpr int f<int>(int*) noexcept {
    return 2;
  }

  static_assert(f<int>(1) == 0);
  static_assert(f<short>(y) == 1);
  static_assert(f<int>(x) == 2);
```

But also otherwise, we would not handle packs correctly.
See temp_deduct_type_example3 in `CXX/CXX/drs/cwg6xx.cpp`

```C++
   template<class T, class... U> void f(T*, U...){}
    template<class T> void f(T){}
    template void f(int*);
```
We would fail the consistency check as we would get A = `void (T)`, InstP = `void (T, U...)` if I remember right.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5494]: We could consider both candidates for that example.
```C++
void g() {
  B b;
  f(0, b);
}
```

But in this case, we order the function template specializations, instead of the function templates, which this patch does not change.

I am not sure what is the rule for that, if we are even being compliant here. I will try to dig this up later.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5494]: One thing I have been worried about this check, is that since we need to allow incomplete deductions, it
seems to me that we can have cases where the type we are transforming depends on template parameters we have not deduced at all.

I don't think this check would be guaranteed to fail in that case, as we would be comparing completely unrelated types that could match by happenstance.

So it seems we do need to check all the template parameters the type references are actually deduced.

One way I have been thinking, is that we could extend the transform with an additional boolean result, that would be set in case we tried to use any template arguments which were null.

**Comment by MaskRay** [comment]
Building abseil-cpp with the new Clang runs into errors. Are they expected?

```sh
git clone https://github.com/abseil/abseil-cpp/
cd abseil-cpp
cmake -GNinja -S. -Bout/release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/tmp/Rel/bin/clang++ -DCMAKE_C_COMPILER=/tmp/Rel/bin/clang
ninja -C out/release
```

```
In file included from /tmp/p/abseil-cpp/absl/flags/parse.cc:16:
In file included from /tmp/p/abseil-cpp/absl/flags/parse.h:26:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/string:67:
In file included from /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/memory_resource.h:47:
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/tuple:2590:14: error: call to constructor of 'tuple<basic_string_view<char, char_traits<char>> &, basic_string_view<char, char_traits<char>> &, bool &>' is ambiguous
 2590 |     { return tuple<_Elements&...>(__args...); }
      |              ^                    ~~~~~~
/tmp/p/abseil-cpp/absl/flags/parse.cc:820:10: note: in instantiation of function template specialization 'std::tie<std::basic_string_view<char>, std::basic_string_view<char>, bool>' requested here
  820 |     std::tie(flag_name, value, is_empty_value) =
      |          ^
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/tuple:1334:2: note: candidate constructor [with _NotEmpty = true, $1 = true]
 1334 |         tuple(const _Elements&... __elements)
      |         ^
/usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/tuple:1349:2: note: candidate constructor [with _UElements = <std::basic_string_view<char> &, std::basic_string_view<char> &, bool &>, _Valid = true, $2 = true]
 1349 |         tuple(_UElements&&... __elements)
      |         ^
```

**Comment by mizvekov** [comment]
> Building abseil-cpp with the new Clang runs into errors. Are they expected?

Did you test the version I just pushed 25 minutes ago? I believe these particular breakages should be fixed there.

We just implemented a rule change to account for the string_view failures, but in any case I see this patch still fails libc++ tests, so we might be missing more stuff.

**Comment by mizvekov** [comment]
> Building abseil-cpp with the new Clang runs into errors. Are they expected?

Nevermind, that's a different failure. Still investigating.

**Comment by mizvekov** [comment]
@MaskRay the latest version fixes libc++ regressions.
Also abseil-cpp builds correctly on MacOS, according to those instructions.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5607]: According to our side discussions, you think `[temp.deduct]p5` should not apply during partial ordering in any case.

But clang follows the opposite consistently.

I think we should leave this as is, and then make a separate patch to fix everywhere at the same time.

Please let me know if you would prefer to remove on this patch.

File: clang/lib/AST/ExprConstant.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/AST/ExprConstant.cpp:5349]: Looking at this again, leaving this line would break this test case:

```C++
template<int N> void g(const char (*)[([]{ return N; })()]) {}
template<int N> void g(const char (*)[([]{ return N; })()]) {}
void use_g() { g<6>(&"hello"); }
```

On the partial ordering case, N stays dependent, so we hit here.
This function assumes that, in certain evaluation modes, this expression has to contain an error.
But I don't see how that assumption holds true from the surrounding code.

CC @hokein since he implemented this originally, and was the last one to touch this code.

**Comment by mizvekov** [comment]
@zygoloid ping, this is ready for another round of review.

**Comment by mizvekov** [comment]
@zygoloid ping, this is ready for another look.

File: clang/test/SemaTemplate/GH18291.cpp [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+template <class X, class Enable = void> struct Bar {};
+
+template<class X> void func(Bar<X, typename enable_if<check<X>()>::type>) {}
+// expected-note@-1 {{candidate function}}
+
+template<class T> void func(Bar<Foo<T>>) {}
+// expected-note@-1 {{candidate function}}
+
+void g() {
+  func(Bar<Foo<int>>()); // expected-error {{call to 'func' is ambiguous}}
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/GH18291.cpp:16]: Interestingly everyone accepts that https://godbolt.org/z/KG9cx4c6f
I think that this is the expected behavior as I am not aware of a disambiguation rule but it's worth double checking @AaronBallman @zygoloid

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5604]: Yes, there are orthogonal bugs with when we check constraints, not doing that here is reasonable

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 9]
```diff
@@ -5421,34 +5635,139 @@ static bool isAtLeastAsSpecializedAs(Sema &S, SourceLocation Loc,
...
+                    /*PartialOrdering=*/true, /*FinishingDeduction=*/true,
+                    [&](Sema &S, TemplateParameterList *, int ParamIdx,
+                        int ArgIdx, QualType P, QualType A,
+                        TemplateDeductionInfo &Info,
+                        SmallVectorImpl<DeducedTemplateArgument> &Deduced,
+                        bool) {
+                      // As a provisional fix for a core issue that does not
+                      // exist yet, only check the consistency of parameters
+                      // which participated in deduction. We still try to
+                      // substitute them though.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5674]: Did you submit it?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 10]
```diff
@@ -1307,6 +1304,62 @@ DeduceTemplateArguments(Sema &S, TemplateParameterList *TemplateParams,
...
+/// \returns the result of template argument deduction so far. Note that a
+/// "success" result means that template argument deduction has not yet failed,
+/// but it may still fail, later, for other reasons.
+static TemplateDeductionResult DeduceTemplateArguments(
+    Sema &S, TemplateParameterList *TemplateParams, const QualType *Params,
+    unsigned NumParams, const QualType *Args, unsigned NumArgs,
+    TemplateDeductionInfo &Info,
+    SmallVectorImpl<DeducedTemplateArgument> &Deduced, unsigned TDF,
+    bool PartialOrdering, bool *HasDeducedAnyParam,
+    llvm::SmallBitVector *HasDeducedParam) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:1343]: The new params are not documented. Can we avoid having 2 parameters for what look like the same thing?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 11]
```diff
@@ -5395,11 +5520,100 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+    return TemplateDeductionResult::NonDeducedMismatch;
+  return TemplateDeductionResult::Success;
+}
+
+template <class T>
+static TemplateDeductionResult FinishTemplateArgumentDeduction(
+    Sema &S, FunctionTemplateDecl *FTD,
+    SmallVectorImpl<DeducedTemplateArgument> &Deduced,
+    TemplateDeductionInfo &Info, T &&CheckDeductionConsistency) {
+  // Unevaluated SFINAE context.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5561]: As is the comment adds nothing

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 12]
```diff
@@ -5395,11 +5520,100 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+  EnterExpressionEvaluationContext Unevaluated(
+      S, Sema::ExpressionEvaluationContext::Unevaluated);
+  Sema::SFINAETrap Trap(S);
+
+  Sema::ContextRAII SavedContext(S, getAsDeclContextOrEnclosing(FTD));
+
+  // C++ [temp.deduct.type]p2:
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5568]:
```suggestion
  // C++26 [temp.deduct.type]p2:
```

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 13]
```diff
@@ -5395,11 +5520,100 @@ static QualType GetImplicitObjectParameterType(ASTContext &Context,
...
+  // and equivalent to the parameter.
+  LocalInstantiationScope InstScope(S);
+
+  if (auto TDR = CheckDeductionConsistency(S, FTD, SugaredBuilder);
+      TDR != TemplateDeductionResult::Success)
+    return TDR;
+
+  // C++20 [temp.deduct]p5 - Only check constraints when all parameters have
+  // been deduced.
+  if (!IsIncomplete) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5599]:
```
if (IsIncomplete)
  return TemplateDeductionResult::Success;
```

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 14]
```diff
@@ -1343,6 +1343,9 @@ namespace {
     DeclarationName Entity;
     // Whether to evaluate the C++20 constraints or simply substitute into them.
     bool EvaluateConstraints = true;
+    // Whether Substitution was Incomplete, that is, we tried to substitute in
+    // any template arguments which were null.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:1347]: Beecause they were not yet provided, presumably?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 15]
```diff
@@ -1427,7 +1481,7 @@ DeduceTemplateBases(Sema &S, const CXXRecordDecl *RD,
   // We iterate over this later, so we have to use MapVector to ensure
   // determinism.
   llvm::MapVector<const CXXRecordDecl *,
-                  SmallVector<DeducedTemplateArgument, 8>>
+                  std::tuple<SmallVector<DeducedTemplateArgument, 8>, bool>>
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:1484]: Can you document the bool?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 16]
```diff
@@ -5421,34 +5635,139 @@ static bool isAtLeastAsSpecializedAs(Sema &S, SourceLocation Loc,
...
+                        bool) {
+                      return ::CheckDeductionConsistency(
+                          S, FTD, ArgIdx, P, A, DeducedArgs,
+                          /*CheckConsistency=*/true);
+                    });
+              }) == TemplateDeductionResult::Success;
+    });
+    if (!AtLeastAsSpecialized)
+      return false;
+  } break;
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5770]: Look quite similar to the code above, any chance we can refactor?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 17]
```diff
@@ -5554,38 +5869,50 @@ FunctionTemplateDecl *Sema::getMoreSpecializedTemplate(
...
+        Args2.push_back(Obj2Ty);
+      }
+    } else {
+      if (NonStaticMethod1 && Method1->hasCXXExplicitFunctionObjectParameter())
+        Params1Begin += 1;
+      if (NonStaticMethod2 && Method2->hasCXXExplicitFunctionObjectParameter())
+        Params2Begin += 1;
+    }
+    Args1.insert(Args1.end(), Params1Begin, Proto1->param_type_end());
+    Args2.insert(Args2.end(), Params2Begin, Proto2->param_type_end());
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5915]: We probably need some tests for explicit object member functions

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:883]: Can we add pack-related tests?

**Review by cor3ntin — COMMENTED** [review]
Sorry for the late review!
I think the change make sense but needs more tests. Thanks!

After we land that, could you spend some time trying to cleanup some of these functions?

- maybe pass an enum instead of a myriad of bool parameters
- maybe return a struct with the output parameters instead of just TemplateDeductionResult ?

File: clang/test/SemaTemplate/GH18291.cpp (hunk 8 above)
Comment (cor3ntin) [reply clang/test/SemaTemplate/GH18291.cpp:16]: can you add a similar tests where the overload are constrained (both with subsumption, and with either one having a constraint nit satisfied)

Comment (AaronBallman) [reply clang/test/SemaTemplate/GH18291.cpp:16]: I am not seeing wording that would allow us to accept this, but it is interesting that we all consistently implement the same rules and accept anyway. Should this be a Core issue in order to avoid breaking working code?

Comment (cor3ntin) [reply clang/test/SemaTemplate/GH18291.cpp:16]: Nah, I think this is contrived enough that it's unlikely to affect users.
And if it does we probably want to break them anyway... I'm not even sure what the exact behavior that determines the order is here: Which do you think should be more specialized? 
Breaking code seems like a least worst options that making arbitrary ordering decisions.
In general there are tons of bugs pertaining to default arguments and ordering and we should fix them.
Adding more special cases to partial ordering seem like a bad idea.

If users find issues with the direction we can reconsider or divide a transition strategy (like we did with template template parameter ordering)


And as explain in https://github.com/llvm/llvm-project/issues/18291 - we are not self consistent

Comment (AaronBallman) [reply clang/test/SemaTemplate/GH18291.cpp:16]: I don't have a strong opinion, but when 100% of implementations all do the same thing (which we do), it seems rather silly to expect implementations and users to change instead of asking whether the standard should reflect reality.

https://godbolt.org/z/johT7fva8

I don't see a reason to break user code except for conformance, but *nobody conforms* so...

Comment (cor3ntin) [reply clang/test/SemaTemplate/GH18291.cpp:16]: Related core issue CWG2160

Comment (AaronBallman) [reply clang/test/SemaTemplate/GH18291.cpp:16]: Okay, after playing around a bit more... I don't think I can explain what our behavior is in practice, so maybe this is the correct approach. Certainly the code *seems* ambiguous to me, so I think the changes are defensible. I'm curious if @zygoloid has opinions here, but if not, I think it's fine to move forward.

File: clang/lib/AST/ExprConstant.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/AST/ExprConstant.cpp:5402]: I can't answer that question as I am not even sure what it's supposed to do here.
I can't prove it doesn't do anything at all without spending some time into it, which hopefully we could avoid if @hokein would shed some light :)

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 17 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5915]: Most of my time implementing this patch was spent redoing this argument accounting logic, as it had pre-existing issues which nonetheless passed existing tests. Most of my time inside of that was fixing explicit object member function test breakages individually.

So I think we are fairly well covered by `SemaCXX/cxx2b-deducing-this.cpp`, but I can try to think if there are any interesting test cases which could do with a explicit object version.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 14 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:1347]: Yes, if the user passes any null template arguments, and we try to use any of these arguments during substitution, then this flag will be set, which will help determine that the result of this substitution is invalid and should not be looked at.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 13 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5599]: This would miss checking if the SFINAE trap captured any errors.
Doing things in this order avoids having to check the trap twice.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 9 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5674]: Yes, this was submitted to the core reflector on Jul 31, 2024, 11:32 AM, the last message on a thread titled `Application of [temp.deduct.type]p1 to function template partial ordering`. The thread was acknowledged by Jens, but he did not follow up with either a new core issue, or an amendment to an existing one.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 16 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5770]: Yeah I was going to, but I was waiting on @zygoloid 's opinion wether we should revert to just comparing function types as before, but this would break a couple of test cases we currently accept, which look reasonable.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:883]: Note we aren't doing any pack specific changes here, this is just for better code reuse.

We have tons of tests in the test suite with partial ordering of function templates which involve packs.

One example I can give offhand (because I mentioned to @zygoloid on another thread) is 'temp_deduct_type_example3' in `CXX/CXX/drs/cwg6xx.cpp`:
```C++
   template<class T, class... U> void f(T*, U...){}
    template<class T> void f(T){}
    template void f(int*);
```
Do you have something in mind which might be missing?

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 10 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:1343]: HasDeducedAnyParam is the disjunction of HasDeducedParam over all parameters. Both parameters are not needed everywhere, so they are made optional, so I can't think of a simpler alternative which would not severely enlarge the scope of this patch.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5604]: I presume this happens before substituting into the function declaration, right?

I have a concern about `CheckDeducedArgumentConstraints()` that it would check the function's associated constraints that might refer to uninstantiated function parameters. We didn't set up a scope for that because this function was just used for class/variable templates, which wasn't necessary previously.

File: clang/test/SemaTemplate/GH18291.cpp (hunk 8 above)
Comment (mizvekov) [reply clang/test/SemaTemplate/GH18291.cpp:16]: > can you add a similar tests where the overload are constrained (both with subsumption, and with either one having a constraint nit satisfied)

Subsumption is not checked on deduction, that's only used later during overload resolution, which we are not changing, so I am not sure that test would be relevant to this change.

Relatedly, in a callback to another discussion with @zygoloid , we currently check if deduction would produce arguments which would not satisfy the constraints, but according to the specification this should not apply to partial ordering, which we fail to do so before this patch, and this patch introduces another case where we fail to follow the rules.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5604]: Here on partial ordering of function templates, most of the times we are going to be deducing dependent arguments anyway, so in very few cases we would actually even try to check the constraints.

Since [temp.deduct]p5 does not apply to partial ordering, maybe that's an argument to not do this here anyway.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 17 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: `SemaCXX/cxx2b-deducing-this.cpp` was missing test cases for static call and subscript operators. Added and fixed, as they are special cases that behave like regular methods.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 9 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:5681]: I think it's fine to reference https://cplusplus.github.io/CWG/issues/2160.html

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 10 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:1349]: I would suggest always passing a `SmallBitVector`
in most cases checking its size is going to boil down to a popcount instruction anyway.
I am happy for you to do that in a follow up, but I really would like to see it happen, these interfaces are becoming too unwieldy

**Comment by cor3ntin** [comment]
@mizvekov please avoid force pushing (prefer merging from main and push new commits) - otherwise github sometimes
eat comments which makes review difficult.

I previously mentioned that your changes to `getMoreSpecializedTemplate` probably needed explicit object parameters tests. I then realized that this was https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2834. Can you check what we do in this case? Thanks

File: clang/lib/AST/ExprConstant.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (hokein) [reply clang/lib/AST/ExprConstant.cpp:5402]: If I recall correctly, historically (before the introduction of RecoveryExpr), we assumed that a non-template function never contained any value-dependent expressions. The constant expression evaluator relied on this assumption. However, with the introduction of RecoveryExpr (which is always value-dependent), we started encountering value-dependent expressions outside of dependent contexts.

We enhanced the constant evaluator to handle these value-dependent cases, but only specifically for RecoveryExpr. This code path should now only be triggered by RecoveryExpr, which is why we expect the containErrors bit in EvaluateDependentExpr.

The removal of EvaluateDependentExpr seems a bit suspicious to me, as we still call EvaluateDependentExpr in several other places.

With this change, are we starting to see value-dependent expressions that are not RecoveryExpr in the constant expression evaluator?

[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/AST/ExprConstant.cpp:5402]: I see. The problem is that in this case we can have incomplete substitutions. For most of the template instantiator, this is not a problem since rebuilding into any dependent stuff just suppresses further analysis, and we just discard the result of the substitution since it was incomplete anyway.

This breaks down here because of the lambda, since a call to an incompletely substituted lambda can come off as non-dependent, even though you would find dependent stuff if you tried to evaluate it.

If the constant expression evaluator would treat finding any dependent stuff as an error, this would come off ok. But since you pointed out there would need to be more places to fix, I think what we could do instead is just bail out immediately when  we know we have an incomplete substitution.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 17 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: > @mizvekov please avoid force pushing (prefer merging from main and push new commits) - otherwise github sometimes
eat comments which makes review difficult.

@cor3ntin  The comment didn't disappear by the way, it's right here.

> I previously mentioned that your changes to getMoreSpecializedTemplate probably needed explicit object parameters tests. I then realized that this was https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2834. Can you check what we do in this case? Thanks

Yeah for that case, no changes here, we are still behaving as proposed in the core issue, which is picking #2, the same as before this patch.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: The test case in cwg2834 is functionally the same as test case `GH92188::A::f3` in `SemaCXX/cxx2b-deducing-this.cpp`, so I am not adding it at this point.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 10 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:1349]: Yeah, let's do in a follow up patch since otherwise this would make conflicting changes with another PR.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 18]
```diff
@@ -2976,6 +3091,18 @@ static TemplateDeductionResult ConvertDeducedTemplateArguments(
       continue;
     }
 
+    // [temp.deduct.partial]p12 - When partial ordering, it's ok for template
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3094]:
```suggestion
    // [C++26][temp.deduct.partial]p12 - When partial ordering, it's ok for template
```

**Review by cor3ntin — APPROVED** [review]
Please wait until tomorrow in case @zygoloid @hokein @zyn0217 have further comments but I think this is in good shape, thanks

I would like to see simplifications of the APIs in subsequent PRs (too many bools, out pointers, and duplication)

Also, can you make sure that libc++ tests pass before merging?
This is technically a breaking change.

**Comment by jeanPerier** [comment]
HI @mizvekov, after your patch, some llvm build broke because a piece of code in flang does not compile anymore with tip of the tree clang:

See: https://lab.llvm.org/buildbot/#/builders/4/builds/1670

Here is a reproducer:

```
#include<complex>
std::complex<float> test(std::complex<float> z1) {
  using F0 = std::complex<float> (*)(const std::complex<float> &, const std::complex<float> &);
  F0  ptr{std::pow};
  return ptr(z1, z1);
}
```

The new error is:
```
repro.cpp:5:11: error: address of overloaded function 'pow' is ambiguous
    5 |   F0  ptr{std::pow};
      |           ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex:1062:5: note: candidate function [with _Tp = float]
 1062 |     pow(const complex<_Tp>& __x, const complex<_Tp>& __y)
      |     ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex:1899:5: note: candidate function [with _Tp = float, _Up = float]
 1899 |     pow(const std::complex<_Tp>& __x, const std::complex<_Up>& __y)
```

Other g++ (and previously clang) compile without warning here. Is this new error justified?

The piece of code with this pattern in flang is here, and is building a table of host math functions to use when folding: https://github.com/llvm/llvm-project/blob/a919588df4f108cef5829363a9ec6a1968dbb03a/flang/lib/Evaluate/intrinsics-library.cpp#L278

I have a workaround for it (#106718) but I do not understand if raising such C++ error is intentional with your patch.

**Comment by DavidTruby** [comment]
For what it's worth, MSVC and icc/icx also build @jeanPerier's example without complaint, so I think it should probably be accepted by clang as well even if it is ambiguous per the standard.

**Comment by DavidSpickett** [comment]
The flang failure also came up on Linaro's 2 stage bots: https://lab.llvm.org/buildbot/#/builders/4/builds/1670

**Comment by mizvekov** [comment]
Reduction:

```
template <class> struct __promote {
  using type = float;
};
template <class> class complex {};

template <class _Tp>
complex<_Tp> pow(const complex<_Tp> &) {};

template <class _Tp>
complex<typename __promote<_Tp>::type> pow(_Tp) = delete;

using F0 = complex<float> (*)(const complex<float> &);
F0 ptr{pow};
```

This is the same as the enable_if consistency check problem, only applied to the return type of a function pointer.
We only so far applied this fix for function calls, but it would be easy to extend this to cover return type and function parameters in the other deduction contexts: In this example, since we haven't deduced any template parameters from the return type, we shouldn't perform consistency check on it.

**Comment by mizvekov** [comment]
@DavidTruby @DavidSpickett A fix for this issue is up at https://github.com/llvm/llvm-project/pull/106829

**Comment by lukel97** [comment]
Hi, I'm no longer able to compile SPEC CPU 2017 after this due to an error in 510.parest_r:

```
/cpu2017/benchspec/CPU/510.parest_r/src/source/fe/fe_tools.cc:2020:15: error: partial ordering for explicit instantiation of 'back_interpolate' is ambiguous
 2020 | void FETools::back_interpolate<3>
      |               ^
/cpu2017/benchspec/CPU/510.parest_r/src/source/fe/fe_tools.cc:1167:10: note: explicit instantiation candidate function 'dealii::FETools::back_interpolate<3, dealii::Vector<double>, dealii::Vector<double>, 3>' template here [with dim = 3, InVector = dealii::Vector<double>, OutVector = dealii::Vector<double>, spacedim = 3]
 1167 | FETools::back_interpolate(const DoFHandler<dim,spacedim> &dof1,
      |          ^
/cpu2017/benchspec/CPU/510.parest_r/src/source/fe/fe_tools.cc:1219:10: note: explicit instantiation candidate function 'dealii::FETools::back_interpolate<3, dealii::DoFHandler, dealii::Vector<double>, dealii::Vector<double>, 3>' template here [with dim = 3, DH = dealii::DoFHandler, InVector = dealii::Vector<double>, OutVector = dealii::Vector<double>, spacedim = 3]
 1219 | FETools::back_interpolate(const DH<dim> &dof1,
      |          ^
```

I think it's based off this https://github.com/dealii/dealii/blob/master/source/fe/fe_tools.cc, but unfortunately what SPEC is using seems to be quite out of date. I can try plugging this into creduce and see if it gives a reproducer. 

I'm not a C++ expert by any means so maybe this error is correct. Is there a flag that could be used to workaround this?

**Comment by mizvekov** [comment]
@lukel97 

If you can reduce, I would appreciate it.

You can also post here an unreduced pre-processed unit which compiles fine with clang before this patch.

**Comment by lukel97** [comment]
@mizvekov 

I'm not sure if it's possible to share SPEC sources due to the license, but creduce was able to get it down to this which passed with -fsyntax-only before aa7497a.

```c++
template <int, int> class a;
template <int, int> class b;
class c {
  template <int d, class e, class f, int g>
  void h(const a<d, g> &, const e &, const b<d, g> &, f &);
  template <int d, template <int> class i, class e, class f, int g>
  void h(const i<d> &, e, const b<d, g> &, f);
};
template <int d, int = d> class a;
template <int d, int = d> class b;
template <int d, class e, class f, int g>
void c::h(const a<d, g> &, const e &, const b<d, g> &, f &) {}
template void c::h(const a<3> &, const float &, const b<3> &, float &);

```

**Comment by yashssh** [comment]
We at grace cpu are also facing same crashes on SPEC FP

**Comment by mizvekov** [comment]
Thanks for the reduction.

I can work with this reduction, but keep in mind that it's better to disable the c-reduce pass which renames things.

The reason is that if this is a problem in SPEC that needs to be fixed, then having the names preserved would help locate which part of SPEC has the problem.

I don't remember what is the pass name you have to disabled, as I don't use c-reduce myself. But if you try c-vise instead of c-reduce, then there the renaming pass is disabled by default.

**Comment by madhur13490** [comment]
@mizvekov Is it possible to revert this until you work on the solution? SPEC is failing since this patch is landed.

**Comment by mizvekov** [comment]
The problem is that I am not sure yet whether this is a breakage that is intended by this patch, and so SPEC should be fixed, or if that is otherwise something that could be fixed in this patch.

It's bedtime now, my shift for today is over, so I'll only be able to take a look at this tomorrow.

If you can get someone else in the meantime to confirm wether a revert is in order, feel free to do so.

**Comment by cor3ntin** [comment]
Reduced further

```cpp
template <int dim, int = dim> class DoFHandler;
template <int dim, int = dim> class FiniteElement;

template <int dim, class InVector, class OutVector, int spacedim>
void back_interpolate(const DoFHandler<dim, spacedim> &, const InVector &,
                     const FiniteElement<dim, spacedim> &, OutVector &){};

template <int dim, template <int> class DH, 
          class InVector, class OutVector,
          int spacedim>
void back_interpolate(const DH<dim> &, InVector,
                      const FiniteElement<dim, spacedim> &, OutVector){};
 

template void back_interpolate(const DoFHandler<3> &, const double &,
                               const FiniteElement<3> &, double &);
```

https://compiler-explorer.com/z/5az5s8jMh
Both GCC and Clang trunk reject that code and i believe this is the conforming behavior.

@zygoloid Do you think we should explore some sort of mitigation strategy here? (a flag to restore the old behavior?)
Looking at that code, it's unclear how either is considered a better specialization by clang 18

**Comment by mizvekov** [comment]
Oh cool, this is CWG2398 TTP-on-Class, this is fixed by https://github.com/llvm/llvm-project/pull/94981 :)

On the SPEC source code side, this is probably similar to the xtensor breakage we got a while ago, there is probably a macro guard somewhere that should be expanded to cover clang.

**Comment by lukel97** [comment]
I just checked and gcc-13 is able to build that SPEC benchmark fine, so I think you're right there's probably some macro somewhere. I'll go digging for around for it.

**Comment by lukel97** [comment]
I did a bit of grepping but I couldn't find any obvious macro. But I realised that gcc actually does accept the reproducer, when compiled with `-std=gnu++98`: https://compiler-explorer.com/z/zsGY6xbh5

This flag is set when compiling SPEC, and seems to be where clang differs.

**Comment by mizvekov** [comment]
Yep, GCC gates __cpp_template_template_args on C++17 and above.

We went with unrestricted enablement on clang, mainly because we thought we would have a full backwards compatibility solution by now.

As I said, this is fixed by https://github.com/llvm/llvm-project/pull/94981, but review is taking a while.
I tried that on your reduced example.
If you can try that patch and verify it does fix everything on SPEC 2017, I would appreciate it, as I don't have access to it's source code.

**Comment by mizvekov** [comment]
By the way, just realized I should mention this, but we still support '-fno-relaxed-template-template-args', if anything, you could compile SPEC with that flag in order to workaround this breakage meanwhile, until the above patch is merged.

**Comment by lukel97** [comment]
I tried out #94981 and -fno-relaxed-template-template-args and can confirm both fix it. I'm now running into a separate LoopVectorizer crash, but I made it out of the frontend :)

Using -fno-relaxed-template-template-args should be fine, in llvm-test-suite we already do something similar for another benchmark by passing -fdelayed-template-parsing, so I'll go ahead and open up a pull request there to add the flag.

Thanks for all your help so far in finding a way around this!

**Comment by alexfh** [comment]
What about this case: https://godbolt.org/z/1TsK96ao8 ? It's a reduction of one of a large number of broken builds we see after this patch.

**Comment by mizvekov** [comment]
@alexfh That's a bug in the patch, thanks for reporting.

This patch fixes it: https://github.com/llvm/llvm-project/pull/107972

**Comment by cor3ntin** [comment]
> I tried out #94981 and -fno-relaxed-template-template-args and can confirm both fix it. I'm now running into a separate LoopVectorizer crash, but I made it out of the frontend :)
> 
> Using -fno-relaxed-template-template-args should be fine, in llvm-test-suite we already do something similar for another benchmark by passing -fdelayed-template-parsing, so I'll go ahead and open up a pull request there to add the flag.
> 
> Thanks for all your help so far in finding a way around this!

It should work without any flags now, can you confirm?

**Comment by lukel97** [comment]
> > I tried out #94981 and -fno-relaxed-template-template-args and can confirm both fix it. I'm now running into a separate LoopVectorizer crash, but I made it out of the frontend :)
> > Using -fno-relaxed-template-template-args should be fine, in llvm-test-suite we already do something similar for another benchmark by passing -fdelayed-template-parsing, so I'll go ahead and open up a pull request there to add the flag.
> > Thanks for all your help so far in finding a way around this!
> 
> It should work without any flags now, can you confirm?

I can confirm I'm able to build SPEC without the flag now.

**Comment by alexfh** [comment]
@mizvekov another distinct compilation error after this commit (and not fixed by https://github.com/llvm/llvm-project/pull/107972 and other follow-up commits): https://gcc.godbolt.org/z/zMG5nsda3 (reduced from https://github.com/hlslibs/ac_math/blob/20bbf040834c5815b01a9ed8e523e4b0dabecf23/tests/rtest_ac_matrixmul.cpp)

We have a few more cases that still generate this compilation error (`call to X is ambiguous`). I'm trying to reduce those as well.

**Comment by alexfh** [comment]
@mizvekov any news here? I think, I'll come up with two more reduced tests later today.

**Comment by mizvekov** [comment]
> Now I think these should cover all remaining issues we see after this commit (and up to the current ToT):
> 
> 
> 
> * Test case 1: https://gcc.godbolt.org/z/zMG5nsda3
> 
> * Test case 2: https://gcc.godbolt.org/z/YbTKzao7d
> 
> * Test case 3: https://gcc.godbolt.org/z/89Yn3d33G
> 
> 
> 
> 

Thanks. I am looking into it.

**Comment by mizvekov** [comment]
@alexfh https://github.com/llvm/llvm-project/pull/109065 Fixes test case 1.

**Comment by alexfh** [comment]
> @alexfh #109065 Fixes test case 1.

I can confirm that it also fixes the compilation error in the original code.

**Comment by mizvekov** [comment]
Regarding test case 2, that further reduces to:
```C++
template <class, int Rows_, int = (Rows_)> class Q {};

template <int rows> void F(Q<double, rows, rows>);
template <class Scalar, int Rows> void F(Q<Scalar, Rows>) = delete;

void test() {
  F(Q<double, 1>());
}
```

The problem is that we consider the parenthesized expression significant in terms of forming a distinct type.
You can see the problem goes away if you remove that parenthesis in the default argument for Q.

I believe the parenthesis should not be significant in this case, and there is also some divergence between GCC and Clang in this area.
I am asking the core reflector for clarification here.

**Comment by alexfh** [comment]
I looked at the original code and found a much more involved expression there (https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/util/ForwardDeclarations.h?ref_type=heads#L66), so the parenthesized expression is merely an artifact of reduction and there doesn't seem to be an easy workaround, IIUC.

**Comment by alexfh** [comment]
An example, which is a bit closer to the original: https://gcc.godbolt.org/z/5WMb78434.

**Comment by alexfh** [comment]
Our internal releases have been blocked on this issue, since even a local revert is not an option at the moment due to the number of dependent commits and problems in other parts of LLVM. We would appreciate if we could get a resolution in the next day or two. If there's no clear path forward yet or more delays are expected, should we consider reverting this temporarily and relanding with the necessary adjustments? I must say I appreciate the overall responsiveness and readiness to resolve the issues. I just see that there seem to be objective complexities here which may require a bit more time to figure out.

**Comment by cor3ntin** [comment]
I think that if we don't have a fix in the next 24-48 hours, and no clarity on the issue - a revert should be considered (note that I think it will be disruptive for llvm too as we are, I think, 3 patches deep, but i agree that keeping a regression on trunk for too long is undesirable)

**Comment by mizvekov** [comment]
It's one thing that we might tweak the rules to account for redundant parenthesis.
But the more complete example shows there is no way to order these unrelated things.

Note that we hadn't so far implemented these rules for partial ordering of function templates, but the same issue should already exist for all implementations when you convert this example to class templates partial specializations, so the approach Eigen is taking here is not standing on solid ground.

**Comment by alexfh** [comment]
Thanks for the clarification! The fact that there's code around that isn't quite following the standard, is not news, but the regular way to approach tightening the compiler is to  provide an opt-out mechanism for some time (one release cycle?) in the shape of a flag or otherwise. Do you think it could be a good option here? Alternatively, do you see a standard-compliant way to rewrite this code?

And did you have a chance to look at the third test case? It would be nice to know if Clang is acting according to the standard there.

**Comment by alexfh** [comment]
> However, I suspect that the parentheses reduction and the one with a ternary are actually the same issue - The code is IFNDR per https://eel.is/c++draft/temp.over.link#5
> 
> In you last example, M*2 and the conditional with M+N after the substitution of the default argument aren't equivalent despite having the same value after instantiation.

Actually, I'm not sure the code I provided as "a bit closer to the original" is actually close enough to retain the relevant properties. I'll try to look at the original code to see if it actually is IFNDR according to https://eel.is/c++draft/temp.over.link#5. It's going to take some time though.

**Comment by alexfh** [comment]
It was faster than I thought. The original code for case 2 is indeed invalid. Having looked carefully at the two definitions of PrintTo, I clearly see they are violating ODR. And both are originating in the internal code, so nothing specific to Eigen. Thanks again for the good explanation!

**Comment by mizvekov** [comment]
@alexfh Your third test case reduces to:

```C++
template <unsigned> struct InlinedVector {};

template <int TotalNumArgs>
void PackArgsHelper(InlinedVector<TotalNumArgs>, unsigned char);

template <int TotalNumArgs, typename T0, typename... TRest>
void PackArgsHelper(InlinedVector<TotalNumArgs> packed_args, T0,
                    TRest... args_rest) {
  PackArgsHelper<TotalNumArgs>(packed_args, args_rest...);
}

template void PackArgsHelper<2>(InlinedVector<2>, int, unsigned char);
```

The problem here is the mismatch between `int` and `unsigned int` for TotalNumArgs.

If you replace `template <unsigned> struct InlinedVector {};` with `template <int> struct InlinedVector {};` that works.
Or you can replace the other way around.

Does that solution translate to the unreduced problem? Does that come from Eigen, or is that internal to google?

It's a shame that we produce these diagnostics internally, but we don't have them wired to show up when these happen in partial ordering.

**Comment by alexfh** [comment]
Wow, I would never have thought it was a problem. Making these the same type removes the compilation error. Can you explain why this is a problem from the C++ standard PoV?

**Comment by mizvekov** [comment]
> Wow, I would never have thought it was a problem. Making these the same type removes the compilation error. Can you explain why this is a problem from the C++ standard PoV?

That's https://eel.is/c++draft/temp.deduct.type#20

In deduced contexts for an NTTP, the type of the argument and the parameter must match exactly.

**Comment by alexfh** [comment]
I see. A clear diagnostic wouldn't hurt indeed. Thanks a lot for the analysis! No more concerns from our side at this point.

**Comment by kongy** [comment]
There is a case that becomes invalid with this patch, is it expected behaviour?

```
template <char> struct Traits {
  using Type = Traits;
};
template <char... ArgType>
void bar(typename Traits<ArgType>::Type... args) {
  FillVRegs<ArgType...>(args...);
}
template <char... ArgType> void FillVRegs(typename Traits<ArgType>::Type...);
template <char FirstArgType, char SecondArgType>
void FillVRegs(typename Traits<FirstArgType>::Type,
               typename Traits<SecondArgType>::Type);
void foo() { bar<'A', 'A'>; }
```

**Comment by kongy** [comment]
@mizvekov Gentle ping...

**Comment by mizvekov** [comment]
Hello, sorry I missed your earlier notification.

Your test case further reduces to: https://godbolt.org/z/q6ndebaeW
```C++
template <char> struct Traits { using Type = Traits; };

template <char... ArgType> void FillVRegs(typename Traits<ArgType>::Type...);
template <char FirstArgType> void FillVRegs(typename Traits<FirstArgType>::Type);

void foo() { FillVRegs<'A'>(Traits<'A'>()); }
```

I believe Clang and GCC are correct to reject this, we can't partial order `FillVRegs` because we can't deduce anything from the function arguments.

**Comment by kongy** [comment]
Thanks for the clarification!
