### PR TITLE
[libc] implement recursive mutex and fix wrong initializer

### LINKED ISSUE #193892: [libc] mutex type is wrongly implemented
```c
typedef struct {
  unsigned char __timed;
  unsigned char __recursive;
  unsigned char __robust;

  void *__owner;
  unsigned long long __lock_count;

#ifdef __linux__
  __futex_word __ftxw;
#else
#error "Mutex type not defined for the target platform."
#endif
} __mutex_type;
```

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Fix #193892.

This is found during libc++ bringing up process. This patch:
- implement recursive mutex support for real.
- fix the issue that pthread mutex initializer and public mutex interface misalign with internal representation. this  was the root cause that hangs the libc++ test as padding bytes effectively pollute the futex state if default initializer was used. 
- additionally, we changed the field to bitfield to allow encoding more data. (e.g. the error checking flag that is not yet added). timed bit is removed as we always support it anyway. PI bit is added instead.

### CODE REVIEW

File: libc/src/__support/threads/unix_mutex.h [hunk 1]
```diff
@@ -10,47 +10,58 @@
...
 
 // TODO: support shared/recursive/robust mutexes.
 class Mutex final : private RawMutex {
-  // reserved timed, may be useful when combined with other flags.
-  unsigned char timed;
-  unsigned char recursive;
-  unsigned char robust;
-  unsigned char pshared;
+  // Use bitfields to allow encoding more attributes.
+  // TODO: also track errorchecking mutex type explicitly?
```
Comment (kaladron) [inline libc/src/__support/threads/unix_mutex.h]: Can you expand more on why you would track this explcitly, and then perhaps file it as an issue?  I worry about TODOs in the codebase that only get noticed a decade late =)

**Comment by SchrodingerZhu** [comment]
Done. Please take a look. I also filed https://github.com/llvm/llvm-project/issues/194396 to track this.

File: libc/src/__support/threads/unix_mutex.h [hunk 2]
```diff
@@ -60,37 +71,54 @@ class Mutex final : private RawMutex {
 
   // TODO: record owner and lock count.
```
Comment (kaladron) [inline libc/src/__support/threads/unix_mutex.h]: This TODO seems fixed by the code, isn't it?  (Here and below)

Comment (SchrodingerZhu) [reply libc/src/__support/threads/unix_mutex.h]: indeed.

File: libc/src/pthread/pthread_mutex_init.cpp [hunk 3]
```diff
@@ -17,20 +18,41 @@
...
-  return err == MutexError::NONE ? 0 : EAGAIN;
+  bool is_recursive = false;
+  switch (get_mutexattr_type(mutexattr)) {
+  case PTHREAD_MUTEX_NORMAL:
+  case PTHREAD_MUTEX_ERRORCHECK:
+    break;
+  case PTHREAD_MUTEX_RECURSIVE:
+    is_recursive = true;
+    break;
+  }
```
Comment (kaladron) [inline libc/src/pthread/pthread_mutex_init.cpp:38]: Is it worth having a default return with EINVAL?

**Review by kaladron — COMMENTED** [review]
One comment.  I'd like @michaelrj-google to weigh in since he knows this code better, but it otherwise looks correct to me.

File: libc/include/llvm-libc-types/__mutex_type.h [hunk 4]
```diff
@@ -10,20 +10,23 @@
 #define LLVM_LIBC_TYPES___MUTEX_TYPE_H
 
 #include "__futex_word.h"
+#include "pid_t.h"
+#include "size_t.h"
 
 typedef struct {
```
Comment (michaelrj-google) [inline libc/include/llvm-libc-types/__mutex_type.h:16]: I'm not clear on why this needs to be reordered. Is something depending on the specific memory layout of mutex?

File: libc/include/llvm-libc-types/__mutex_type.h [hunk 5]
```diff
@@ -10,20 +10,23 @@
...
 #ifdef __linux__
   __futex_word __ftxw;
 #else
 #error "Mutex type not defined for the target platform."
 #endif
+
+  unsigned int __priority_inherit : 1;
+  unsigned int __recursive : 1;
+  unsigned int __robust : 1;
+  unsigned int __pshared : 1;
```
Comment (michaelrj-google) [inline libc/include/llvm-libc-types/__mutex_type.h:26]: We can't assume that the user is compiling our headers targetting the latest C standard version. I don't think this syntax was available in C99.

File: libc/src/pthread/pthread_mutex_init.cpp [hunk 6]
```diff
@@ -17,20 +18,41 @@
...
+    is_robust = true;
+
+  bool is_pshared = false;
+  switch (get_mutexattr_pshared(mutexattr)) {
+  case PTHREAD_PROCESS_PRIVATE:
+    break;
+  case PTHREAD_PROCESS_SHARED:
+    is_pshared = true;
+    break;
+  }
```
Comment (michaelrj-google) [inline libc/src/pthread/pthread_mutex_init.cpp]: are there more process states than `SHARED` and `PRIVATE`? If not this could be simplified to `bool ispshared = get_mutexattr_pshared(mutexattr) == PTHREAD_PROCESS_SHARED;`

File: libc/test/integration/src/pthread/pthread_mutex_test.cpp [hunk 7]
```diff
@@ -199,14 +285,12 @@ void multiple_waiters() {
   LIBC_NAMESPACE::pthread_mutex_destroy(&counter_lock);
 }
 
-// Test the initializer
-[[maybe_unused]]
-static pthread_mutex_t test_initializer = PTHREAD_MUTEX_INITIALIZER;
```
Comment (michaelrj-google) [inline libc/test/integration/src/pthread/pthread_mutex_test.cpp:204]: having a test of the static initializer may still be helpful

File: libc/test/integration/src/pthread/pthread_mutex_test.cpp [hunk 8]
```diff
@@ -143,6 +156,79 @@ void trylock_test() {
...
+  pthread_mutex_t mutex_from_init_snapshot = snapshot_mutex(&mutex_from_init);
+  ASSERT_EQ(mutex_snapshot.__ftxw.__word,
+            mutex_from_init_snapshot.__ftxw.__word);
+  ASSERT_EQ(mutex_snapshot.__priority_inherit,
+            mutex_from_init_snapshot.__priority_inherit);
+  ASSERT_EQ(mutex_snapshot.__recursive, mutex_from_init_snapshot.__recursive);
+  ASSERT_EQ(mutex_snapshot.__robust, mutex_from_init_snapshot.__robust);
+  ASSERT_EQ(mutex_snapshot.__pshared, mutex_from_init_snapshot.__pshared);
+  ASSERT_EQ(mutex_snapshot.__owner, mutex_from_init_snapshot.__owner);
+  ASSERT_EQ(mutex_snapshot.__lock_count, mutex_from_init_snapshot.__lock_count);
```
Comment (michaelrj-google) [inline libc/test/integration/src/pthread/pthread_mutex_test.cpp:226]: this part feels like it's testing the specific implementation instead of the interface. Are these specific struct member names defined in the standard?

File: libc/include/llvm-libc-types/__mutex_type.h (hunk 4 above)
Comment (SchrodingerZhu) [reply libc/include/llvm-libc-types/__mutex_type.h:16]: yes, because of the initializer constant. The ordering made libc++ mutex test hang.

File: libc/include/llvm-libc-types/__mutex_type.h (hunk 5 above)
Comment (SchrodingerZhu) [reply libc/include/llvm-libc-types/__mutex_type.h:26]: I thought bitfields are in C89? 

https://en.cppreference.com/c/language/bit_field

File: libc/test/integration/src/pthread/pthread_mutex_test.cpp (hunk 8 above)
Comment (SchrodingerZhu) [reply libc/test/integration/src/pthread/pthread_mutex_test.cpp:226]: This is to test that INITIALIZER is the same as null attribute initialization, which is in the spec. 

May be I should change this to bytewise memcmp.

File: libc/test/integration/src/pthread/pthread_mutex_test.cpp (hunk 7 above)
Comment (SchrodingerZhu) [reply libc/test/integration/src/pthread/pthread_mutex_test.cpp:204]: Indeed. I will add it back.

File: libc/include/llvm-libc-types/__mutex_type.h (hunk 5 above)
Comment (michaelrj-google) [reply libc/include/llvm-libc-types/__mutex_type.h:26]: right, I confused them with bitints which are newer.

**Review by michaelrj-google — APPROVED** [review]
LGTM
