### PR TITLE
[NFC][clang] Fix CodeGenSYCL::unique_stable_name_windows_diff test

### LINKED ISSUE #146566: Target assert fails downstream for unique_stable_name_windows_diff.cpp test with device target -triple x86_64-pc-windows-msvc
https://github.com/llvm/llvm-project/pull/140282/files#diff-56f9373c26f0ad1f09dd4c561b7fe44dc9cfd6d363c54be44816fbc2a9f8a43e

This test has been failing [this assert](url) added by https://github.com/llvm/llvm-project/pull/137882

FAIL: Clang :: CodeGenSYCL/unique_stable_name_windows_diff.cpp (11004 of 21742)
******************** TEST 'Clang :: CodeGenSYCL/unique_stable_name_windows_diff.cpp' FAILED ********************
Exit Code: 2
 
Command Output (stderr):
--
/home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -triple spir64-unknown-unknown -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -o - | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/FileCheck /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp '-D$ADDRSPACE=addrspace(1) ' # RUN: at line 1
+ /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -triple spir64-unknown-unknown -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -o -
+ /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/FileCheck /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp '-D$ADDRSPACE=addrspace(1) '
/home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -o - | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/FileCheck /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp '-D$ADDRSPACE=' # RUN: at line 2
+ /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -o -
+ /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/FileCheck /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp '-D$ADDRSPACE='
Unknown kernel calling convention
UNREACHABLE executed at /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/TargetInfo.cpp:120!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -o -
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
#0 0x000057d360a2cb08 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/lib/Support/Unix/Signals.inc:804:13
#1 0x000057d360a2a5f5 llvm::sys::RunSignalHandlers() /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/lib/Support/Signals.cpp:106:18
#2 0x000057d360a2d1e1 SignalHandler(int, siginfo_t*, void*) /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
#3 0x00007a0ec4f18330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
#4 0x00007a0ec4f71b2c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x9eb2c)
#5 0x00007a0ec4f1827e raise (/lib/x86_64-linux-gnu/libc.so.6+0x4527e)
#6 0x00007a0ec4efb8ff abort (/lib/x86_64-linux-gnu/libc.so.6+0x288ff)
#7 0x000057d360999cdf (/home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang+0x86c5cdf)
#8 0x000057d36149297a (/home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang+0x91be97a)
#9 0x000057d360cd7903 ClangCallConvToLLVMCallConv /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CGCall.cpp:0:39
#10 0x000057d360cd7903 clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(clang::CanQual<clang::Type>, clang::CodeGen::FnInfoOpts, llvm::ArrayRef<clang::CanQual<clang::Type>>, clang::FunctionType::ExtInfo, llvm::ArrayRef<clang::FunctionType::ExtParameterInfo>, clang::CodeGen::RequiredArgs) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CGCall.cpp:855:17
#11 0x000057d360cdbb28 begin /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include/llvm/ADT/SmallVector.h:268:45
#12 0x000057d360cdbb28 end /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include/llvm/ADT/SmallVector.h:270:27
#13 0x000057d360cdbb28 ~SmallVector /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include/llvm/ADT/SmallVector.h:1203:46
#14 0x000057d360cdbb28 clang::CodeGen::CodeGenTypes::arrangeSYCLKernelCallerDeclaration(clang::QualType, clang::CodeGen::FunctionArgList const&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CGCall.cpp:764:1
#15 0x000057d36135b7ef _M_ptr /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:199:51
#16 0x000057d36135b7ef get /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:470:21
#17 0x000057d36135b7ef operator* /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:453:2
#18 0x000057d36135b7ef getTypes /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CodeGenModule.h:848:37
#19 0x000057d36135b7ef clang::CodeGen::CodeGenModule::EmitSYCLKernelCaller(clang::FunctionDecl const*, clang::ASTContext&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CodeGenSYCL.cpp:53:30
#20 0x000057d360c61baf clang::CodeGen::CodeGenModule::EmitDeferred() /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:3382:11
#21 0x000057d360c5e43a clang::CodeGen::CodeGenModule::Release() /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:891:3
#22 0x000057d3611a9dab (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/ModuleBuilder.cpp:291:11
#23 0x000057d3611a1b0e clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:243:24
#24 0x000057d362bcf2a9 __normal_iterator /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_iterator.h:1077:20
#25 0x000057d362bcf2a9 begin /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:874:16
#26 0x000057d362bcf2a9 finalize<std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback> >, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback> > > > > /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/include/clang/Sema/TemplateInstCallback.h:54:16
#27 0x000057d362bcf2a9 clang::ParseAST(clang::Sema&, bool, bool) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Parse/ParseAST.cpp:190:3
#28 0x000057d361733d76 clang::FrontendAction::Execute() /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1225:10
#29 0x000057d3616a240d getPtr /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include/llvm/Support/Error.h:278:42
#30 0x000057d3616a240d operator bool /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include/llvm/Support/Error.h:241:16
#31 0x000057d3616a240d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1055:23
#32 0x000057d36181b0b2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:300:25
#33 0x000057d35df13edd cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/tools/driver/cc1_main.cpp:297:15
#34 0x000057d35df0feff ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/tools/driver/driver.cpp:223:12
#35 0x000057d35df0ef9a clang_main(int, char**, llvm::ToolContext const&) /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/tools/driver/driver.cpp:264:12
#36 0x000057d35df1fbc7 main /home/gha/actions-runner/_work/llvm-project/llvm-project/build/tools/clang/tools/driver/clang-driver.cpp:17:10
#37 0x00007a0ec4efd1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
#38 0x00007a0ec4efd28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
#39 0x000057d35df0d965 _start (/home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/clang+0x5c39965)
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/gha/actions-runner/_work/llvm-project/llvm-project/build/bin/FileCheck /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp -D$ADDRSPACE=

### PR DESCRIPTION
**Pull request by Fznamznon**
The test checks x86 target in fsycl-is-device mode. x86 is not a valid offloading target and IMO test meant to check fsycl-is-host mode to make sure host invocations of __builtin_sycl_unique_stable_name work correctly. This also switches the test to use sycl_entry_point attribute instead of sycl_kernel because the intention for the future SYCL changes is to use sycl_entry_point and eventually remove sycl_kernel attribute when sycl_entry_point supports enough SYCL cases.

Fixes https://github.com/llvm/llvm-project/issues/146566

### CODE REVIEW

File: clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp [hunk 1]
```diff
@@ -1,19 +1,19 @@
 // RUN: %clang_cc1 -triple spir64-unknown-unknown-sycldevice -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
-// RUN: %clang_cc1 -triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE='
+// RUN: %clang_cc1 -triple x86_64-pc-windows-msvc -fsycl-is-host -disable-llvm-passes -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE='
 
 
 template<typename KN, typename Func>
-__attribute__((sycl_kernel)) void kernel(Func F){
+[[clang::sycl_entry_point]] void kernel(Func F){
```
Comment (tahonermann) [inline clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp]:
```suggestion
[[clang::sycl_kernel_entry_point(KN)]] void kernel(Func F){
```

File: clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp [hunk 2]
```diff
@@ -1,19 +1,19 @@
...
   F();
 }
 
 template<typename KN, typename Func>
-__attribute__((sycl_kernel)) void kernel2(Func F){
+[[clang::sycl_entry_point]] void kernel2(Func F){
```
Comment (tahonermann) [inline clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp]:
```suggestion
[[clang::sycl_kernel_entry_point(KN)]] void kernel2(Func F){
```

File: clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp [hunk 3]
```diff
@@ -1,19 +1,19 @@
...
   F(1);
 }
 
 template<typename KN, typename Func>
-__attribute__((sycl_kernel)) void kernel3(Func F){
+[[clang::sycl_entry_point]] void kernel3(Func F){
```
Comment (tahonermann) [inline clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp]:
```suggestion
[[clang::sycl_kernel_entry_point(KN)]] void kernel3(Func F){
```

File: clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp [hunk 4]
```diff
@@ -1,19 +1,19 @@
 // RUN: %clang_cc1 -triple spir64-unknown-unknown-sycldevice -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
```
Comment (tahonermann) [inline clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp]: The redundant `-fsycl-is-device` option can be removed.
```suggestion
// RUN: %clang_cc1 -triple spir64-unknown-unknown-sycldevice -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
```

**Review by tahonermann — CHANGES_REQUESTED** [review]

**Review by sarnex — APPROVED** [review]
Thanks Mariya!

**Comment by Fznamznon** [comment]
I noticed there is a problem with __builtin_sycl_unique_stable_name and sycl_kernel_etnry_point attribute. If I add this wrapping of __builtin_sycl_unique_stable_name calls AND sycl_kernel_entry_point attribute, the strings disappear from the IR. They are in here https://godbolt.org/z/KnPffTMYq , they disappear in https://godbolt.org/z/6jdvYEhK7 . Makes sense to fix it first instead of merging this.

**Comment by Fznamznon** [comment]
> I noticed there is a problem with __builtin_sycl_unique_stable_name and sycl_kernel_etnry_point attribute. If I add this wrapping of __builtin_sycl_unique_stable_name calls AND sycl_kernel_entry_point attribute, the strings disappear from the IR. They are in here https://godbolt.org/z/KnPffTMYq , they disappear in https://godbolt.org/z/6jdvYEhK7 . Makes sense to fix it first instead of merging this.

Ah, according to https://github.com/llvm/llvm-project/issues/146566#issuecomment-3036813047 that was just my ignorance. I corrected the test so it tests correct targets and should be passing with https://github.com/llvm/llvm-project/pull/140282/files too. @tahonermann @schittir , could you please review?

File: clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp [hunk 5]
```diff
@@ -1,19 +1,19 @@
-// RUN: %clang_cc1 -triple spir64-unknown-unknown-sycldevice -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
-// RUN: %clang_cc1 -triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -fsycl-is-device -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE='
+// RUN: %clang_cc1 -triple spir64-unknown-unknown-sycldevice -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
```
Comment (Naghasan) [inline clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp]: nit, unless we want to it bring back

```suggestion
// RUN: %clang_cc1 -triple spir64-unknown-unknown -aux-triple x86_64-pc-windows-msvc -fsycl-is-device -disable-llvm-passes -emit-llvm %s -o - | FileCheck %s '-D$ADDRSPACE=addrspace(1) '
```

**Review by Naghasan — APPROVED** [review]

**Review by tahonermann — APPROVED** [review]
This looks good to me. I agree that the original intent of the test was probably not to exercise `x86_64-pc-windows-msvc` as a device target.
