### PR TITLE
[C11] Implement WG14 N1285 (temporary lifetimes)

### LINKED ISSUE #96486: [C11] Properly handle materializing temporaries
While investigating whether Clang properly implements [WG14 N1285](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1285.htm) (the factored approach), I found that Clang does not correctly materialize a temporary for the code that changed behavior:
```
struct X { int a[5]; } f();
int *p = f().a;
printf("%p\n", p);
```
https://godbolt.org/z/6q6bsabsj

In C11, that is an invalid use of a materialized temporary; in C99 it was required to work. Clang does not attempt to form a materialized temporary because of the language version check in: https://github.com/llvm/llvm-project/blob/c1bde0a2cb640b3607e9568b9a57b292e1f82666/clang/lib/Sema/SemaInit.cpp#L8667

Changing this to also materialize the temporary in C11 and later causes failed assertions in CodeGen:
```
# RUN: at line 1
f:\source\llvm-project\llvm\out\build\x64-debug\bin\clang.exe -cc1 -internal-isystem F:\source\llvm-project\llvm\out\build\x64-Debug\lib\clang\19\include -nostdsysteminc -triple aarch64_be-linux-gnu -ffreestanding -emit-llvm -O0 -o - F:\source\llvm-project\clang\test\CodeGen\arm64-be-hfa-vararg.c | f:\source\llvm-project\llvm\out\build\x64-debug\bin\filecheck.exe F:\source\llvm-project\clang\test\CodeGen\arm64-be-hfa-vararg.c
# executed command: 'f:\source\llvm-project\llvm\out\build\x64-debug\bin\clang.exe' -cc1 -internal-isystem 'F:\source\llvm-project\llvm\out\build\x64-Debug\lib\clang\19\include' -nostdsysteminc -triple aarch64_be-linux-gnu -ffreestanding -emit-llvm -O0 -o - 'F:\source\llvm-project\clang\test\CodeGen\arm64-be-hfa-vararg.c'
# .---command stderr------------
# | Assertion failed: isa<To>(Val) && "cast<Ty>() argument of incompatible type!", file F:\source\llvm-project\llvm\include\llvm/Support/Casting.h, line 578
# | PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
# | Stack dump:
# | 0.  Program arguments: f:\\source\\llvm-project\\llvm\\out\\build\\x64-debug\\bin\\clang.exe -cc1 -internal-isystem F:\\source\\llvm-project\\llvm\\out\\build\\x64-Debug\\lib\\clang\\19\\include -nostdsysteminc -triple aarch64_be-linux-gnu -ffreestanding -emit-llvm -O0 -o - F:\\source\\llvm-project\\clang\\test\\CodeGen\\arm64-be-hfa-vararg.c
# | 1.  <eof> parser at end of file
# | 2.  F:\source\llvm-project\clang\test\CodeGen\arm64-be-hfa-vararg.c:6:8: LLVM IR generation of declaration 'callee'
# | 3.  F:\source\llvm-project\clang\test\CodeGen\arm64-be-hfa-vararg.c:6:8: Generating code for declaration 'callee'
# | Exception Code: 0x80000003
# |  #0 0x00007ff7124ddebc HandleAbort F:\source\llvm-project\llvm\lib\Support\Windows\Signals.inc:425:0
# |  #1 0x00007ffc2945bc31 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x6bc31)
# |  #2 0x00007ffc2945d889 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x6d889)
# |  #3 0x00007ffc294630bf (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x730bf)
# |  #4 0x00007ffc29461091 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x71091)
# |  #5 0x00007ffc29463a1f (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0x73a1f)
# |  #6 0x00007ff712628691 F:\source\llvm-project\llvm\include\llvm\Support\Casting.h:578:0
# |  #7 0x00007ff716019f2c pushTemporaryCleanup F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:352:0
# |  #8 0x00007ff71600c8d8 clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(class clang::MaterializeTemporaryExpr const *) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:588:0
# |  #9 0x00007ff715ff8f7c clang::CodeGen::CodeGenFunction::EmitLValueHelper(class clang::Expr const *, enum clang::CodeGen::KnownNonNull_t) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1654:0
# | #10 0x00007ff715ff7e2c clang::CodeGen::CodeGenFunction::EmitLValue(class clang::Expr const *, enum clang::CodeGen::KnownNonNull_t) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1495:0
# | #11 0x00007ff715ff92e4 clang::CodeGen::CodeGenFunction::EmitCheckedLValue(class clang::Expr const *, enum clang::CodeGen::CodeGenFunction::TypeCheckKind) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1463:0
# | #12 0x00007ff71600896a clang::CodeGen::CodeGenFunction::EmitMemberExpr(class clang::MemberExpr const *) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:4654:0
# | #13 0x00007ff715ff8d7c clang::CodeGen::CodeGenFunction::EmitLValueHelper(class clang::Expr const *, enum clang::CodeGen::KnownNonNull_t) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1628:0
# | #14 0x00007ff715ff7e2c clang::CodeGen::CodeGenFunction::EmitLValue(class clang::Expr const *, enum clang::CodeGen::KnownNonNull_t) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1495:0
# | #15 0x00007ff715ff92e4 clang::CodeGen::CodeGenFunction::EmitCheckedLValue(class clang::Expr const *, enum clang::CodeGen::CodeGenFunction::TypeCheckKind) F:\source\llvm-project\clang\lib\CodeGen\CGExpr.cpp:1463:0
# | #16 0x00007ff71920de7f `anonymous namespace'::ScalarExprEmitter::EmitCheckedLValue F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:255:0
# | #17 0x00007ff71920e880 `anonymous namespace'::ScalarExprEmitter::EmitLoadOfLValue F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:303:0
# | #18 0x00007ff719216202 `anonymous namespace'::ScalarExprEmitter::VisitMemberExpr F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:1947:0
# | #19 0x00007ff71920a31d clang::StmtVisitorBase<std::add_pointer,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit F:\source\llvm-project\llvm\out\build\x64-Debug\tools\clang\include\clang\AST\StmtNodes.inc:310:0
# | #20 0x00007ff719212a6c `anonymous namespace'::ScalarExprEmitter::Visit F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:422:0
# | #21 0x00007ff719219a1a `anonymous namespace'::ScalarExprEmitter::VisitCastExpr F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:2505:0
# | #22 0x00007ff71920c0de clang::StmtVisitorBase<std::add_pointer,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::VisitImplicitCastExpr F:\source\llvm-project\llvm\out\build\x64-Debug\tools\clang\include\clang\AST\StmtNodes.inc:522:0
# | #23 0x00007ff71920a65d clang::StmtVisitorBase<std::add_pointer,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit F:\source\llvm-project\llvm\out\build\x64-Debug\tools\clang\include\clang\AST\StmtNodes.inc:522:0
# | #24 0x00007ff719212a6c `anonymous namespace'::ScalarExprEmitter::Visit F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:422:0
# | #25 0x00007ff7192226de `anonymous namespace'::ScalarExprEmitter::VisitExprWithCleanups F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:2716:0
# | #26 0x00007ff71920a46f clang::StmtVisitorBase<std::add_pointer,`anonymous namespace'::ScalarExprEmitter,llvm::Value *>::Visit F:\source\llvm-project\llvm\out\build\x64-Debug\tools\clang\include\clang\AST\StmtNodes.inc:392:0
# | #27 0x00007ff719212a6c `anonymous namespace'::ScalarExprEmitter::Visit F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:422:0
# | #28 0x00007ff719207a4d clang::CodeGen::CodeGenFunction::EmitScalarExpr(class clang::Expr const *, bool) F:\source\llvm-project\clang\lib\CodeGen\CGExprScalar.cpp:5492:0
# | #29 0x00007ff715e7de2c clang::CodeGen::CodeGenFunction::EmitScalarInit(class clang::Expr const *, class clang::ValueDecl const *, class clang::CodeGen::LValue, bool) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:797:0
# | #30 0x00007ff715e7ce3f clang::CodeGen::CodeGenFunction::EmitExprAsInit(class clang::Expr const *, class clang::ValueDecl const *, class clang::CodeGen::LValue, bool) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:2016:0
# | #31 0x00007ff715e804c9 clang::CodeGen::CodeGenFunction::EmitAutoVarInit(class clang::CodeGen::CodeGenFunction::AutoVarEmission const &) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:1978:0
# | #32 0x00007ff715e7e869 clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(class clang::VarDecl const &) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:1350:0
# | #33 0x00007ff715e7dd91 clang::CodeGen::CodeGenFunction::EmitVarDecl(class clang::VarDecl const &) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:219:0
# | #34 0x00007ff715e7d8a3 clang::CodeGen::CodeGenFunction::EmitDecl(class clang::Decl const &) F:\source\llvm-project\clang\lib\CodeGen\CGDecl.cpp:164:0
# | #35 0x00007ff715fd2bf7 clang::CodeGen::CodeGenFunction::EmitDeclStmt(class clang::DeclStmt const &) F:\source\llvm-project\clang\lib\CodeGen\CGStmt.cpp:1573:0
# | #36 0x00007ff715fce329 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(class clang::Stmt const *, class llvm::ArrayRef<class clang::Attr const *>) F:\source\llvm-project\clang\lib\CodeGen\CGStmt.cpp:463:0
# | #37 0x00007ff715fccd6e clang::CodeGen::CodeGenFunction::EmitStmt(class clang::Stmt const *, class llvm::ArrayRef<class clang::Attr const *>) F:\source\llvm-project\clang\lib\CodeGen\CGStmt.cpp:65:0
# | #38 0x00007ff715fceb96 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(class clang::CompoundStmt const &, bool, class clang::CodeGen::AggValueSlot) F:\source\llvm-project\clang\lib\CodeGen\CGStmt.cpp:553:0
# | #39 0x00007ff715fb4a5b clang::CodeGen::CodeGenFunction::EmitFunctionBody(class clang::Stmt const *) F:\source\llvm-project\clang\lib\CodeGen\CodeGenFunction.cpp:1307:0
# | #40 0x00007ff715fab1d9 clang::CodeGen::CodeGenFunction::GenerateCode(class clang::GlobalDecl, class llvm::Function *, class clang::CodeGen::CGFunctionInfo const &) F:\source\llvm-project\clang\lib\CodeGen\CodeGenFunction.cpp:1533:0
# | #41 0x00007ff713ea5b71 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(class clang::GlobalDecl, class llvm::GlobalValue *) F:\source\llvm-project\clang\lib\CodeGen\CodeGenModule.cpp:5939:0
# | #42 0x00007ff713ea581f clang::CodeGen::CodeGenModule::EmitGlobalDefinition(class clang::GlobalDecl, class llvm::GlobalValue *) F:\source\llvm-project\clang\lib\CodeGen\CodeGenModule.cpp:4117:0
# | #43 0x00007ff713e9c3a4 clang::CodeGen::CodeGenModule::EmitGlobal(class clang::GlobalDecl) F:\source\llvm-project\clang\lib\CodeGen\CodeGenModule.cpp:3829:0
# | #44 0x00007ff713e9402c clang::CodeGen::CodeGenModule::EmitTopLevelDecl(class clang::Decl *) F:\source\llvm-project\clang\lib\CodeGen\CodeGenModule.cpp:6824:0
# | #45 0x00007ff718351012 `anonymous namespace'::CodeGeneratorImpl::HandleTopLevelDecl F:\source\llvm-project\clang\lib\CodeGen\ModuleBuilder.cpp:190:0
# | #46 0x00007ff7147495d4 clang::BackendConsumer::HandleTopLevelDecl(class clang::DeclGroupRef) F:\source\llvm-project\clang\lib\CodeGen\CodeGenAction.cpp:199:0
# | #47 0x00007ff716a377c9 clang::ParseAST(class clang::Sema &, bool, bool) F:\source\llvm-project\clang\lib\Parse\ParseAST.cpp:167:0
# | #48 0x00007ff71433b522 clang::ASTFrontendAction::ExecuteAction(void) F:\source\llvm-project\clang\lib\Frontend\FrontendAction.cpp:1192:0
# | #49 0x00007ff714747927 clang::CodeGenAction::ExecuteAction(void) F:\source\llvm-project\clang\lib\CodeGen\CodeGenAction.cpp:1146:0
# | #50 0x00007ff71433ae0f clang::FrontendAction::Execute(void) F:\source\llvm-project\clang\lib\Frontend\FrontendAction.cpp:1078:0
# | #51 0x00007ff7127924a6 clang::CompilerInstance::ExecuteAction(class clang::FrontendAction &) F:\source\llvm-project\clang\lib\Frontend\CompilerInstance.cpp:1061:0
# | #52 0x00007ff712911ea5 clang::ExecuteCompilerInvocation(class clang::CompilerInstance *) F:\source\llvm-project\clang\lib\FrontendTool\ExecuteCompilerInvocation.cpp:280:0
# | #53 0x00007ff711c94b3f cc1_main(class llvm::ArrayRef<char const *>, char const *, void *) F:\source\llvm-project\clang\tools\driver\cc1_main.cpp:232:0
# | #54 0x00007ff711c8310e ExecuteCC1Tool F:\source\llvm-project\clang\tools\driver\driver.cpp:215:0
# | #55 0x00007ff711c83923 clang_main(int, char **, struct llvm::ToolContext const &) F:\source\llvm-project\clang\tools\driver\driver.cpp:256:0
# | #56 0x00007ff711cbebf6 main F:\source\llvm-project\llvm\out\build\x64-Debug\tools\clang\tools\driver\clang-driver.cpp:17:0
# | #57 0x00007ff71d3c0fb9 invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79:0
# | #58 0x00007ff71d3c10f2 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
# | #59 0x00007ff71d3c117e __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331:0
# | #60 0x00007ff71d3c119e mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17:0
# | #61 0x00007ffcc2ea7344 (C:\WINDOWS\System32\KERNEL32.DLL+0x17344)
# | #62 0x00007ffcc4a5cc91 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4cc91)
# `-----------------------------
```
so additional work is required to teach CodeGen how to handle the AST pattern. Alternatively, if this is undefined behavior we wish to define for our implementation, we should document it in the language extensions manual explicitly.

### PR DESCRIPTION
**Pull request by AaronBallman**
This feature largely models the same behavior as in C++11. It is technically a breaking change between C99 and C11, so the paper is not being backported to older language modes.

One difference between C++ and C is that things which are rvalues in C are often lvalues in C++ (such as the result of a ternary operator or a comma operator).

Fixes #96486

### CODE REVIEW

**Comment by AaronBallman** [comment]
Note, this will fail in precommit CI due to `test/CodeGenObjC/strong-in-c-struct.c`. I am posting this PR to see if there are other failures on Linux platforms that I'm missing locally, and to get an idea whether folks agree that this is heading in the right direction. I'm leaning very heavily on the C++ implementation.

File: clang/lib/Sema/Sema.cpp [hunk 1]
```diff
@@ -741,10 +741,11 @@ ExprResult Sema::ImpCastExprToType(Expr *E, QualType Ty,
   if (Kind == CK_ArrayToPointerDecay) {
     // C++1z [conv.array]: The temporary materialization conversion is applied.
     // We also use this to fuel C++ DR1213, which applies to C++11 onwards.
-    if (getLangOpts().CPlusPlus && E->isPRValue()) {
+    if ((getLangOpts().C11 || getLangOpts().CPlusPlus) && E->isPRValue()) {
```
Comment (efriedma-quic) [inline clang/lib/Sema/Sema.cpp:744]: Does this change actually do anything?  I can't come up with any way to produce a prvalue array in C.

File: clang/test/C/C11/n1285_1.c [hunk 2]
```diff
@@ -0,0 +1,212 @@
+// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
+// RUN: %clang_cc1 -std=c99 -Wno-dangling -emit-llvm -o - %s | FileCheck %s --check-prefix=C99
+// RUN: %clang_cc1 -std=c11 -Wno-dangling -emit-llvm -o - %s | FileCheck %s --check-prefix=C11
```
Comment (efriedma-quic) [inline clang/test/C/C11/n1285_1.c:3]: We probably want some tests with optimization enabled, to show the lifetime markers.

File: clang/lib/Sema/Sema.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/Sema/Sema.cpp:744]: I thought the change was necessary but you're right, later changes made this dead code.

File: clang/test/C/C11/n1285_1.c (hunk 2 above)
Comment (AaronBallman) [reply clang/test/C/C11/n1285_1.c:3]: I've added those tests now.

Comment (efriedma-quic) [reply clang/test/C/C11/n1285_1.c:3]: `-disable-llvm-passes`?

File: clang/test/CodeGen/xcore-abi.c [hunk 3]
```diff
@@ -27,7 +27,7 @@ void testva (int n, ...) {
   va_start(ap,n);
   // CHECK: [[AP:%[a-z0-9]+]] = alloca ptr, align 4
   // CHECK: [[V5:%[a-z0-9]+]] = alloca %struct.x, align 4
-  // CHECK: [[TMP:%[a-z0-9]+]] = alloca [4 x i32], align 4
+  // CHECK: [[TMP:%[a-z0-9\.]+]] = alloca [4 x i32], align 4
```
Comment (efriedma-quic) [inline clang/test/CodeGen/xcore-abi.c:30]: I don't think you need to escape a "." in that position.

Comment (AaronBallman) [reply clang/test/CodeGen/xcore-abi.c:30]: Without it, it was failing because `%tmp` became `%ref.tmp` in the IR output and we were no longer matching due to the period.

File: clang/test/C/C11/n1285_1.c (hunk 2 above)
Comment (AaronBallman) [reply clang/test/C/C11/n1285_1.c:3]: I added that to the line setting an optimization level; or should I be setting that always for codegen tests regardless of passing `-On`?

File: clang/test/CodeGen/xcore-abi.c (hunk 3 above)
Comment (efriedma-quic) [reply clang/test/CodeGen/xcore-abi.c:30]: I meant just `[[TMP:%[a-z0-9.]+]]`, as opposed to `\.`

**Review by efriedma-quic — APPROVED** [review]
LGTM

File: clang/test/CodeGen/xcore-abi.c (hunk 3 above)
Comment (AaronBallman) [reply clang/test/CodeGen/xcore-abi.c]: Ah! I've removed the escape. :-)

**Comment by jyknight** [comment]
- In C89: it's impossible to get the address of a temporary struct, so the lifetime is irrelevant.
- In C99: you now can get the address (from an array subobject), but the lifetime was defined as "until the next sequence point". This made it technically illegal to access even non-array subobjects from a temporary struct in many cases where it seems like it should be fine and was in C89.
- In C11, the lifetime was _extended_ to be the containing full expression.

(LMK if I've got that wrong!) Given that, how is the C11 change a breaking change? It seems like the C99 rule was just bogus, and we should forget it ever existed?

**Comment by frederick-vs-ja** [comment]
> (LMK if I've got that wrong!) Given that, how is the C11 change a breaking change? It seems like the C99 rule was just bogus, and we should forget it ever existed?

IIUC, the "breaking change" is that in C99 a pointer value to a temporary array element never becomes indeterminate (despite access through it raising UB), but in C11 it does.

E.g.
```C
struct S { int a[1]; };
struct S fun(void) {
  return (struct S){0};
}

int main(void) {
  int* p = fun().a;
  int m = *p; // UB in C99 and C11
  *p += 42;   // UB in C99 and C11

  *p;         // UB in C11, but OK in C99?
  int* q = p; // q is more indeterminate in C11?
}
```

**Comment by AaronBallman** [comment]
> > (LMK if I've got that wrong!) Given that, how is the C11 change a breaking change? It seems like the C99 rule was just bogus, and we should forget it ever existed?
> 
> IIUC, the "breaking change" is that in C99 a pointer value to a temporary array element never becomes indeterminate (despite access through it raising UB), but in C11 it does.
> 
> E.g.
> 
> ```c
> struct S { int a[1]; };
> struct S fun(void) {
>   return (struct S){0};
> }
> 
> int main(void) {
>   int* p = fun().a;
>   int m = *p; // UB in C99 and C11
>   *p += 42;   // UB in C99 and C11
> 
>   *p;         // UB in C11, but OK in C99?
>   int* q = p; // q is more indeterminate in C11?
> }
> ```

From the original paper:

> Please note that this approach additionally declares an example like this, which was conforming under C99, to be non-conforming:
> ```
>     struct X { int a[5]; } f();
>     int *p = f().a;
>     printf("%p\n", p);
> ```
> Because it uses the (indeterminate) value of a pointer to a temporary object. Personally, I think this is a good thing, but I wanted to be very clear and up front about this change.

**Comment by efriedma-quic** [comment]
In practice, when you're using LLVM, pointers never become indeterminate.  So I don't think that "breakage" can actually break anything.

**Comment by AaronBallman** [comment]
So is the request to remove the checks for C11 and just treat C as being this way always? (If so, does anyone want to see extension/compatibility warnings in C99 mode?) Or are we fine as-is without backporting it?

File: clang/test/C/C11/n1285_1.c (hunk 2 above)
Comment (efriedma-quic) [reply clang/test/C/C11/n1285_1.c:3]: It doesn't really do anything at -O0.  I mean, technically, yes, we run a few passes at -O0, but it's handling for specific constructs like always_inline and coroutines.

**Comment by rjmccall** [comment]
I mean, let's be clear here: the old C rule is broken. The standard failed to understand that the memory could be addressed, so it failed to give rules about the lifetime of addresses within it; as a result, it is formally well-defined to have pointers perpetually referring to it. That is unimplementable without dynamically allocating and leaking memory, which we certainly should not do and which nobody would thank us for doing. Given that, I think we have to understand the wording change here as fully retroactive.

**Comment by AaronBallman** [comment]
Okay, I'll change this so it's not specific to C11. Is anyone going to be upset if I don't implement "is a C11 extension" diagnostics, or should I take care of that too?

**Comment by jyknight** [comment]
I was trying to figure out what Clang previously, in practice, thought the lifetime of this C99 temporary-which-isn't-a-temporary was.

AFAICT, it's treating it a bit inconsistently as either the full expression (where is where we emit e.g. objc-arc cleanups for the reference-counted values), or else the entire-function scope -- since we didn't emit any `llvm.lifetime` instrinsics for the object, the alloca lives until the end of the function.

So, _in practice_ this PR reduces reduce the observed lifetime. E.g. 
```
void test2(int a, int b);
void test() {
  struct X { int a[5]; } f(void);
  int *g = f().a;
  int *g2 = f().a;
  test2(g[0], g2[0]);
}
```
would've previously worked in practice (though UB per the standard), but now is broken in practice. It also observerably-works in GCC.

I don't know if any code actually does this, but it's maybe something to consider for the decision on whether to backport to C99.

**Comment by frederick-vs-ja** [comment]
> That is unimplementable without dynamically allocating and leaking memory, which we certainly should not do and which nobody would thank us for doing.

Ah, I think [DR452](https://www.open-std.org/jtc1/sc22/wg14/issues/c11c17/issue0452.html) (adding "Such an object need not have a unique address.") also addressed this.

And then the patched C99 rule would be - the storage of the temporary object can be deallocated or reused later, but a pointer to it never becomes indeterminate. This is implementable but extremely weird, since it would indicate that some aspect of temporary objects is more persistent than that of other objects.

**Comment by AaronBallman** [comment]
Ping

File: clang/lib/Sema/SemaInit.cpp [hunk 4]
```diff
@@ -7653,8 +7653,11 @@ ExprResult Sema::TemporaryMaterializationConversion(Expr *E) {
   // In C++98, we don't want to implicitly create an xvalue.
   // FIXME: This means that AST consumers need to deal with "prvalues" that
   // denote materialized temporaries. Maybe we should add another ValueKind
-  // for "xvalue pretending to be a prvalue" for C++98 support.
-  if (!E->isPRValue() || !getLangOpts().CPlusPlus11)
+  // for "xvalue pretending to be a prvalue" for C++98 support. C11 added the
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaInit.cpp:7656]: Maybe reorganize this comment so the description of C11 rules isn't part of the "FIXME"?

**Review by efriedma-quic — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaInit.cpp (hunk 4 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaInit.cpp]: Good call, done

**Comment by nico** [comment]
Looks like this breaks tests on macOS: http://45.33.8.238/macm1/104220/step_6.txt

Please take a look and revert for now if it takes a while to fix.

**Comment by AaronBallman** [comment]
> Looks like this breaks tests on macOS: http://45.33.8.238/macm1/104220/step_6.txt
> 
> Please take a look and revert for now if it takes a while to fix.

This should already be addressed by 5a1b4ec6f4b773f191e98183ae4628785729daa1, I'm watching the bots to make sure they go back to green.
