### PR TITLE
[LV][EVL] Support fixed-order recurrence idiom with EVL tail folding.

### LINKED ISSUE #122461: [LV][EVL] Incorrect behavior of fixed-order recurrence idiom with EVL tail folding
When enabling EVL tail folding, the llvm.splice operation may encounter errors in the final iteration because the EVL in the second-to-last iteration might not equal VF * UF. 
This could result in unexpected behavior, such as:
```
llvm.splice([A, B, C, poison], [D, E, poison, poison], -1) ==> [poison, D, E, poison]  
```
This issue was identified by the LLVM test-suite in `SingleSource/UnitTests/Vectorizer/recurrences.test`.
```
Checking first_order_recurrence
Checking second_order_recurrence
Checking third_order_recurrence
Miscompare
```
Currently, we have temporarily disabled this feature using https://github.com/llvm/llvm-project/pull/122458. It will be re-enabled after implementing the following fixes.
```
vector.ph:                                        ; preds = %for.body.preheader.i.i.i
  ...
  %max.vf.1 = tail call i32 @llvm.vscale.i32()
  %max.vf = shl nuw nsw i32 %max.vf.1, 2 
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %evl.based.iv = phi i64 [ 0, %vector.ph ], [ %index.evl.next, %vector.body ]

 ### Record the evl of previous iteration. Initialized by VF ###
  %prev.evl = phi i32 [ %max.vf, %vector.ph ], [ %17, %vector.body ]    

  %vector.recur = phi <vscale x 4 x i32> [ %vector.recur.init, %vector.ph ], [ %vp.op.load, %vector.body ]
  %vector.recur8 = phi <vscale x 4 x i32> [ %vector.recur.init7, %vector.ph ], [ %19, %vector.body ]
  %vector.recur10 = phi <vscale x 4 x i32> [ %vector.recur.init9, %vector.ph ], [ %20, %vector.body ]
  %avl = sub i64 %wide.trip.count.i.i.i, %evl.based.iv
  %17 = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %avl, i32 4, i1 true)
  %18 = getelementptr inbounds nuw i32, ptr %__args.val, i64 %evl.based.iv
  %vp.op.load = tail call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr align 4 %18, <vscale x 4 x i1> splat (i1 true), i32 %17), !tbaa !6

### Replace llvm.splice with llvm.experimental.vp.splice. ###
  %19 = tail call <vscale x 4 x i32> @llvm.experimental.vp.splice.nxv4i32(<vscale x 4 x i32> %vector.recur, <vscale x 4 x i32> %vp.op.load, i32 -1, <vscale x 4 x i1> splat (i1 true), i32 %prev.evl, i32 %17)
  %20 = tail call <vscale x 4 x i32> @llvm.experimental.vp.splice.nxv4i32(<vscale x 4 x i32> %vector.recur8, <vscale x 4 x i32> %19, i32 -1, <vscale x 4 x i1> splat (i1 true), i32 %prev.evl, i32 %17)
  %21 = tail call <vscale x 4 x i32> @llvm.experimental.vp.splice.nxv4i32(<vscale x 4 x i32> %vector.recur10, <vscale x 4 x i32> %20, i32 -1, <vscale x 4 x i1> splat (i1 true), i32 %prev.evl, i32 %17)

  %vp.op = tail call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %20, <vscale x 4 x i32> %19, <vscale x 4 x i1> splat (i1 true), i32 %17)
  %vp.op11 = tail call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %vp.op, <vscale x 4 x i32> %21, <vscale x 4 x i1> splat (i1 true), i32 %17)
  %22 = getelementptr inbounds nuw i32, ptr %__args1.val, i64 %evl.based.iv
  tail call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> %vp.op11, ptr align 4 %22, <vscale x 4 x i1> splat (i1 true), i32 %17), !tbaa !6
  %23 = zext i32 %17 to i64
  %index.evl.next = add nuw i64 %evl.based.iv, %23
  %index.next = add nuw i64 %index, %7
  %24 = icmp eq i64 %index.next, %n.vec
  br i1 %24, label %"_ZSt10__invoke_rIvRZ4mainE3$_1JPjS2_jEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES4_E4typeEOS5_DpOS6_.exit", label %vector.body, !llvm.loop !39
```

### PR DESCRIPTION
**Pull request by Mel-Chen**
This patch converts the llvm.vector.splice intrinsic to llvm.experimental.vp.splice, ensuring that fixed-order recurrences execute correctly when tail folding by EVL is enable.
Due to the non-VFxUF penultimate EVL issue, the EVL from the previous iteration will be preserved and used in llvm.experimental.vp.splice.

Fixes https://github.com/llvm/llvm-project/issues/122461

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp [hunk 1]
```diff
@@ -1235,6 +1235,8 @@ RISCVTTIImpl::getIntrinsicInstrCost(const IntrinsicCostAttributes &ICA,
                                                   : RISCV::VMV_V_X,
                                               LT.second, CostKind);
   }
+  case Intrinsic::experimental_vp_splice:
+    return 1;
```
Comment (Mel-Chen) [inline llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1239]: @ElvisWang123 
Could you please support the cost model of vp.splice?

Comment (ElvisWang123) [reply llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1239]: Sure.

Comment (ElvisWang123) [reply llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp:1239]: PR opened. https://github.com/llvm/llvm-project/pull/124221

File: llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-fixed-order-recurrence.ll [hunk 2]
```diff
@@ -31,41 +27,37 @@ define void @first_order_recurrence(ptr noalias %A, ptr noalias %B, i64 %TC) {
...
+; IF-EVL-NEXT:    [[INDEX_EVL_NEXT]] = add i64 [[TMP19]], [[EVL_BASED_IV]]
+; IF-EVL-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP8]]
 ; IF-EVL-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
 ; IF-EVL-NEXT:    br i1 [[TMP20]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
 ; IF-EVL:       [[MIDDLE_BLOCK]]:
-; IF-EVL-NEXT:    [[TMP21:%.*]] = call i32 @llvm.vscale.i32()
-; IF-EVL-NEXT:    [[TMP22:%.*]] = mul i32 [[TMP21]], 4
-; IF-EVL-NEXT:    [[TMP23:%.*]] = sub i32 [[TMP22]], 1
+; IF-EVL-NEXT:    [[TMP23:%.*]] = sub i32 [[TMP12]], 1
 ; IF-EVL-NEXT:    [[VECTOR_RECUR_EXTRACT:%.*]] = extractelement <vscale x 4 x i32> [[VP_OP_LOAD]], i32 [[TMP23]]
```
Comment (Mel-Chen) [inline llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-fixed-order-recurrence.ll:61]: @fhahn For tail folding, the scalar epilogue should currently be dead code. The ExtractFromEnd transformation might be unnecessary at this stage.
If you think this transformation can be deferred until it's needed, please let me know. I will move it to another branch and archive it.

**Comment by Mel-Chen** [comment]
This patch is ready for reviewing. Please take a look, thanks.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 3]
```diff
@@ -1635,18 +1635,62 @@ void VPlanTransforms::addActiveLaneMask(
...
 /// \p EVL         The explicit vector length parameter of vector-predication
-/// intrinsics.
+///                intrinsics.
+/// \p PrevEVL     The explicit vector length of the previous iteration.
 static VPRecipeBase *createEVLRecipe(VPValue *HeaderMask,
                                      VPRecipeBase &CurRecipe,
                                      VPTypeAnalysis &TypeInfo,
-                                     VPValue &AllOneMask, VPValue &EVL) {
+                                     VPValue &AllOneMask, VPValue &EVL,
+                                     VPValue *PrevEVL) {
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1693]:
```suggestion
                                     VPValue &PrevEVL) {
```
?

Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1693]: The previous EVL is not always required. 
Therefore, I only created previous EVL if there is a `VPFirstOrderRecurrencePHIRecipe` in the plan.
```
  VPScalarPHIRecipe *PrevEVL = nullptr;
  bool ContainsFORs =
      any_of(Header->phis(), IsaPred<VPFirstOrderRecurrencePHIRecipe>);
```
And there is an assertion to check the previous EVL is not a nullptr in  case  `VPInstruction::FirstOrderRecurrenceSplice`.
```
          assert(PrevEVL && "Fixed-order recurrences require previous EVL");
```

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 4]
```diff
@@ -1727,6 +1783,30 @@ static void transformRecipestoEVLRecipes(VPlan &Plan, VPValue &EVL) {
...
+  VPBasicBlock *Header = LoopRegion->getEntryBasicBlock();
+
+  // Create a scalar phi to track the previous EVL if fixed-order recurrence is
+  // contained.
+  VPScalarPHIRecipe *PrevEVL = nullptr;
+  bool ContainsFORs =
+      any_of(Header->phis(), IsaPred<VPFirstOrderRecurrencePHIRecipe>);
+  if (ContainsFORs) {
+    // TODO: Use VPInstruction::ExplicitVectorLength to get maximum EVL.
+    VPValue *MaxEVL = &Plan.getVF();
```
Comment (lukel97) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1796]: Just a note, I think Plan.getVF() is an empty value at this point so its inferred type will be the CanonicalIV type.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 5]
```diff
@@ -1727,6 +1783,30 @@ static void transformRecipestoEVLRecipes(VPlan &Plan, VPValue &EVL) {
...
+  VPRegionBlock *LoopRegion = Plan.getVectorLoopRegion();
+  VPBasicBlock *Header = LoopRegion->getEntryBasicBlock();
+
+  // Create a scalar phi to track the previous EVL if fixed-order recurrence is
+  // contained.
+  VPScalarPHIRecipe *PrevEVL = nullptr;
+  bool ContainsFORs =
+      any_of(Header->phis(), IsaPred<VPFirstOrderRecurrencePHIRecipe>);
+  if (ContainsFORs) {
+    // TODO: Use VPInstruction::ExplicitVectorLength to get maximum EVL.
```
Comment (lukel97) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1795]: Would `VPInstruction::ExplicitVectorLength` be correct here? I would have thought we would always need the full VF for the initial EVL1 in the splice

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 6]
```diff
@@ -1727,6 +1783,30 @@ static void transformRecipestoEVLRecipes(VPlan &Plan, VPValue &EVL) {
...
+    VPValue *MaxEVL = &Plan.getVF();
+    // Emit VPScalarCastRecipe in preheader if VF is not a 32 bits integer.
+    if (unsigned VFSize =
+            TypeInfo.inferScalarType(MaxEVL)->getScalarSizeInBits();
+        VFSize != 32) {
+      MaxEVL = new VPScalarCastRecipe(
+          VFSize > 32 ? Instruction::Trunc : Instruction::ZExt, MaxEVL,
+          Type::getInt32Ty(Ctx), DebugLoc());
```
Comment (lukel97) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1803]: Not for this PR, we should probably add another VPScalarCastRecipe constructor that calls IRBuilder::createZExtOrTrunc and share it with the OpVPEVL cast in tryAddExplicitVectorLength

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 7]
```diff
@@ -1635,18 +1635,62 @@ void VPlanTransforms::addActiveLaneMask(
...
 /// Try to convert \p CurRecipe to a corresponding EVL-based recipe. Returns
 /// nullptr if no EVL-based recipe could be created.
 /// \p HeaderMask  Header Mask.
 /// \p CurRecipe   Recipe to be transform.
 /// \p TypeInfo    VPlan-based type analysis.
 /// \p AllOneMask  The vector mask parameter of vector-predication intrinsics.
 /// \p EVL         The explicit vector length parameter of vector-predication
-/// intrinsics.
+///                intrinsics.
+/// \p PrevEVL     The explicit vector length of the previous iteration.
```
Comment (lukel97) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1688]: Mention it's only needed if there is a VPFirstOrderRecurrencePHIRecipe?

**Review by lukel97 — COMMENTED** [review]
Thanks, this looks sensible and correct to me! I only have some small suggestions and questions, e.g. do we need to fix all ExtractFromEnd instructions

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 8]
```diff
@@ -1635,18 +1635,62 @@ void VPlanTransforms::addActiveLaneMask(
...
 }
 
+/// Adjust the way the resume value is obtained when using tail folding by EVL.
+/// Expanding ExtractFromEnd since the penultimate EVL could not equals to
+/// VFxUF. Expand
+///   %resume = ExtractFromEnd %vec, 1
+/// to
+///   %last.active.idx = sub %EVL, 1
+///   %resume = extractelement %vec, %last.active.idx
+static void adjustResumePhisForEVL(VPlan &Plan, VPValue &EVL) {
```
[the remark this answers is not in the document]
Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1645]: > Do we need to adjust all ExtractFromEnd instructions, not just the ones that use ResumePhi and where the index is zero?
> 
> E.g. it looks like `addExitUsersForFirstOrderRecurrences` also creates an ExtractFromEnd with an index of 2. I think that should probably also be adjusted for EVL.
>

Currently, whether it is `ExtractFromEnd %vec, 1` or `ExtractFromEnd %vec, 2`, neither produces useful IR when tail folding is enabled—be it tail folding by mask or tail folding by EVL.

For `ExtractFromEnd %vec, 1`, it is used for the resume phi. The incoming edge 0 connects to the vector loop, and the value comes from the vector loop. However, the final resume phi node IR will always be removed because the purpose of tail folding is to eliminate the need for a scalar epilogue.

For `ExtractFromEnd %vec, 2`, it is used to extract the reduction result of fixed-order recurrences. `ExtractFromEnd %vec, 2` is only generated when there are external users. However, the current tail folding do not allow fixed-order recurrences to have external users, include tail folding by EVL. Therefore, when tail folding by EVL is enabled, VPlan should not contain `ExtractFromEnd %vec, 2` (see test case `define i32 @FOR_reduction(ptr noalias %A, ptr noalias %B, i64 %TC)`).

In conclusion, whether or not ExtractFromEnd is transformed does not affect the correctness of the final IR. This is because `ExtractFromEnd %vec, 1` is dead code and will eventually be eliminated, while `ExtractFromEnd %vec, 2` should not appear in the VPlan when tail folding is enabled.

> Would it also maybe be simpler if we added a runtime VF operand to `ExtractFromEnd`, similar to `VPReverseVectorPointerRecipe`? Users would pass in Plan.getVF() when building it and VPInstruction::generate would generate the sub (if needed). Then the EVL transform just becomes a matter of replacing the runtime VF operand with EVL.

My thought is that Folding by EVL might not be well-suited for using ExtractFromEnd to compute with reverse indices. It would be simpler and more intuitive to use a regular forward-indexed extractelement instead.

By the way, in folding by EVL, only `ExtractFromEnd %vec, 1` is safe, since we can only guarantee that EVL is greater than 1, regardless of the VF.

I'm considering whether ExtractFromEnd should still be transformed in this patch if it has no substantial impact.
https://github.com/llvm/llvm-project/pull/124093#discussion_r1954563972

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 4 above)
Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1797]: Thanks for providing this information.:)

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 5 above)
Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1796]: It is correct, if we adjust `VPFirstOrderRecurrencePHIRecipe::execute()` for folding by EVL. However, since the performance impact of this change is still uncertain, I prefer to prioritize correctness for this patch as an initial patch for fixed-order recurrence.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 6 above)
Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1804]: Hmm...perhaps it would be simpler to extract this into a utils function?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (lukel97) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1645]: Thanks for the explanation, that makes sense to me. From the sounds of things if the ExtractFromEnd is going to be binned anyway I don't see the need to include this transform. Archiving it in another branch sounds good to me, in case we ever do want to return to it!

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 5 above)
Comment (lukel97) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1796]: Oh ok I see how that would work if we change `VPFirstOrderRecurrencePHIRecipe` too to not use getRuntimeVF. 

I think what the current PR has is good so I'll mark this as resolved. I'm not sure about what you mean about the performance though. Would using ExplicitVectorLength instead of VF help performance?

**Review by lukel97 — APPROVED** [review]
LGTM

Not related to this PR but I'll keep an eye out for this on the codegen side: ~On RISC-V for a splice of -1, we should be able to do this as a single vslidedown I think?~ We need two slides

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 5 above)
Comment (alexey-bataev) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1796]: I think Mel means the case, where VF is larger than the total trip count. In this case we can precalculate Explicit VL and use it instead of RuntimeVF. It may help the performance

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (Mel-Chen) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Archive ExtractFromEnd transformation to [another branch](https://github.com/Mel-Chen/llvm-project/tree/evl-extract-for-resumephi).

**Review by alexey-bataev — APPROVED** [review]

**Comment by Mel-Chen** [comment]
Rebase, and ping @fhahn.

**Review by fhahn — APPROVED** [review]
LGTM, thanjs
