### PR TITLE
[clang] Allow pack expansions when partial ordering against template template parameters

### LINKED ISSUE #62529: -frelaxed-template-template-args: "error: pack expansion used as argument for non-pack parameter of alias template" with constrained alias template
Motivation:
```c++
#include <boost/hana/type.hpp>
template<class> requires(true) using U = int;
auto t = boost::hana::template_<U>(boost::hana::type_c<char>);
```
Reduced:
```c++
template<class> requires(true) using U = int;
template<template<typename ...> class, class> struct S {};
template<class T> S<U, T> f();
auto t = f<int>();
```
compiled with `-frelaxed-template-template-args` gives:
```console
<source>:2:31: error: pack expansion used as argument for non-pack parameter of alias template
template<template<typename ...> class, class> struct S {};
```
(we need `-frelaxed-template-template-args` for other reasons)
Workaround: use `std::enable_if_t` to constrain alias template instead.

### LINKED ISSUE #91787: [clang][regression][rejects-valid] clang trunk rejecting valid pack expansion
I believe the following C++20 code should compile:

```c++
template <class...>
concept True = true;

template <bool>
struct I {
  template <template <class...> class F, class... As>
  using f = F<As...>;
};

template <template <class...> class F, class... As>
using meval = I<True<As...>>::template f<F, As...>;

template <class F, class... As>
concept P = true;

template <class F, class... As>
  requires P<F, As...>
using V = void;

template <class...Ts>
auto f() -> meval<V, int, Ts...> {
}

int main() {
  f();
}
```

Clang 18 and earlier accepts it, as does gcc. With clang-trunk, I get:

```
<source>:10:29: error: pack expansion used as argument for non-pack parameter of alias template
   10 | template <template <class...> class F, class... As>
      |                             ^
1 error generated.
Compiler returned: 1
```

See repro here: https://godbolt.org/z/c1dG74EPd

### PR DESCRIPTION
**Pull request by mizvekov**
When partial ordering alias templates against template template parameters, allow pack expansions when the alias has a fixed-size parameter list.

These expansions were generally disallowed by proposed resolution for CWG1430.

By previously diagnosing these when checking template template parameters, we would be too strict in trying to prevent any potential invalid use.

This flows against the more general idea that template template parameters are weakly typed, that we would rather allow an argument that might be possibly misused, and only diagnose the actual misuses during instantiation.

Since this interaction between P0522R0 and CWG1430 is also a backwards-compat breaking change, we implement provisional wording to allow these.

Fixes https://github.com/llvm/llvm-project/issues/62529
Fixes #91787

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -6507,8 +6508,13 @@ bool Sema::CheckTemplateArgumentList(
       bool PackExpansionIntoNonPack =
           NewArgs[ArgIdx].getArgument().isPackExpansion() &&
           (!(*Param)->isTemplateParameterPack() || getExpandedPackSize(*Param));
-      if (PackExpansionIntoNonPack && (isa<TypeAliasTemplateDecl>(Template) ||
-                                       isa<ConceptDecl>(Template))) {
+      // Core issue 1430: Don't diagnose this pack expansion when partial
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:6511]:
```suggestion
      // Core issue CWG1430: Don't diagnose this pack expansion when partial
```

(makes it easier to grep for)

**Review by erichkeane — APPROVED** [review]

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -707,6 +707,7 @@ Bug Fixes to C++ Support
   initialized, rather than evaluating them as a part of the larger manifestly constant evaluated
   expression.
 - Fix a bug in access control checking due to dealyed checking of friend declaration. Fixes (#GH12361).
+- When partial ordering alias templates against template template parameters, allow pack expansions when the alias has a fixed-size parameter list. Fixes (#GH62529).
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:710]:
```suggestion
- When partial ordering alias templates against template template parameters, 
   allow pack expansions when the alias has a fixed-size parameter list. Fixes (#GH62529).
```

File: clang/include/clang/Sema/Sema.h [hunk 3]
```diff
@@ -9216,14 +9216,20 @@ class Sema final : public SemaBase {
   /// receive true if the cause for the error is the associated constraints of
   /// the template not being satisfied by the template arguments.
   ///
+  /// \param PartialOrderTTP If true, assume these template arguments are
+  /// the injected template arguments for a template template parameter.
+  /// This will relax the requirement that all it's possible uses are valid.
```
Comment (cor3ntin) [inline clang/include/clang/Sema/Sema.h:9221]:
```suggestion
  /// This will relax the requirement that all its possible uses are valid:
```

File: clang/lib/Sema/SemaTemplate.cpp [hunk 4]
```diff
@@ -6436,7 +6436,8 @@ bool Sema::CheckTemplateArgumentList(
     TemplateArgumentListInfo &TemplateArgs, bool PartialTemplateArgs,
     SmallVectorImpl<TemplateArgument> &SugaredConverted,
     SmallVectorImpl<TemplateArgument> &CanonicalConverted,
-    bool UpdateArgsWithConversions, bool *ConstraintsNotSatisfied) {
+    bool UpdateArgsWithConversions, bool *ConstraintsNotSatisfied,
+    bool PartialOrderTTP) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplate.cpp:6440]:
```suggestion
    bool PartialOrderingTTP) {
```

**Review by cor3ntin — COMMENTED** [review]
Looks sensible to me but let's wait a bit (I'll try to run tests on stdexec with that change)

**Comment by cor3ntin** [comment]
I have confirmed that with this change, `stdexec` compiles successfully, addressing both #89807 and #91787

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks!
