### PR TITLE
[InstCombine] Do not perform binop-of-shuffle when mask is poison

### LINKED ISSUE #82052: [InstCombine] Replacement of binop with binop-of-shuffle incorrectly adds extra poison value
The following IR is a minimal repro when run with `opt -passes=instcombine`:
```llvm
define i8 @src(<2 x i8> %x, <2 x i8> %y) {
  %xsplat = shufflevector <2 x i8> %x, <2 x i8> poison, <2 x i32> <i32 1, i32 0>
  %vv = mul <2 x i8> %xsplat, %y
  %m = mul <2 x i8> %x, %y   ;  <<<< Note that %m is later replaced with %vv in the output
  %msplat = shufflevector <2 x i8> %m, <2 x i8> poison, <2 x i32> <i32 0, i32 0>
  %res = add <2 x i8> %vv, %msplat
  %vget_lane = extractelement <2 x i8> %res, i64 1
  ret i8 %vget_lane
}
```
Which on 17.x or trunk will give:
```llvm
define i8 @src(<2 x i8> %x, <2 x i8> %y) {
  %xsplat = shufflevector <2 x i8> %x, <2 x i8> poison, <2 x i32> <i32 poison, i32 0>
  %vv = mul <2 x i8> %xsplat, %y
  %msplat = shufflevector <2 x i8> %vv, <2 x i8> poison, <2 x i32> <i32 poison, i32 0>
  %res = add <2 x i8> %vv, %msplat
  %vget_lane = extractelement <2 x i8> %res, i64 1
  ret i8 %vget_lane
}
```
However, this is not correct, because the added poisoned values end up observed in the final output. First, in InstCombine, the first element in each mask for the shuffles are first replaced with `poison` due to not being observed in the final `extractelement`. After that we run into this code  in `InstCombineSimplifyDemanded.cpp`:
https://github.com/llvm/llvm-project/blob/d8278b682386f51dfba204849c624672a3df40c7/llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp#L1866-L1880

This is what replaces the `mul <2 x i8> %x, %y` with `mul <2 x i8> %xsplat, %y` (`m_ZeroMask` also matches poison). However in doing so, it introduces the extra poison from `%xsplat`, meaning that `%msplat` has both its elements poisoned, which ends up propagating to `%vget_lane`.

Here is a Godbolt link showing the test case on 16.x, 17.x, and trunk:
https://godbolt.org/z/5eeT7x4s3

And also an Alive2 example showing the bad transformation with a counter-example:
https://alive2.llvm.org/ce/z/RpBJEN

The code was first introduced in 3b090ff2bdb2828b53d6fec9c06b9d52fed09f42, which a bisect shows is when this first started repro'ing

I have verified that this still repros on latest trunk, 2de269a641e4ffbb7a44e559c4c0a91bb66df823

For priority/triage: this bug was found by a fuzzer meant to test SIMD codegen. It was not from manually written code

### PR DESCRIPTION
**Pull request by antoniofrighetto**
Shuffle masks operand may be turn into `poison` if this does not lead to observable changes. This however may not guarantee binop to binop-of-shuffle replacement to be sound anymore. IIUC the transformation, we shouldn't need to check for all the mask operands being poisoned.

Fixes: https://github.com/llvm/llvm-project/issues/82052.

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp [hunk 1]
```diff
@@ -1870,14 +1870,16 @@ Value *InstCombinerImpl::SimplifyDemandedVectorElts(Value *V,
...
+          ArrayRef<int> Mask;
+          auto Shuf = m_Shuffle(m_Specific(ShufOp), m_Value(), m_Mask(Mask));
           if (BO->isCommutative()
                   ? match(U, m_c_BinOp(Opcode, Shuf, m_Specific(OtherOp)))
                   : MatchShufAsOp0
                         ? match(U, m_BinOp(Opcode, Shuf, m_Specific(OtherOp)))
                         : match(U, m_BinOp(Opcode, m_Specific(OtherOp), Shuf)))
-            if (DT.dominates(U, I))
-              return U;
+            if (match(Mask, m_ZeroMask()) && Mask[0] != PoisonMaskElem)
```
Comment (goldsteinn) [inline llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp:1880]: Why do you only check the first element?

**Comment by goldsteinn** [comment]
It looks like only your third test is problematic: https://alive2.llvm.org/ce/z/WrH49f
can the fix be made more precise?

File: llvm/test/Transforms/InstCombine/vec_demanded_elts.ll [hunk 2]
```diff
@@ -1159,3 +1159,53 @@ define i4 @common_binop_demand_via_extelt_op0_mismatch_elt1(<2 x i4> %x, <2 x i4
...
+  %ysplat = shufflevector <2 x i8> %y, <2 x i8> poison, <2 x i32> <i32 poison, i32 0>
+  %vv = add <2 x i8> %x, %ysplat
+  %m = add <2 x i8> %x, %y
+  %msplat = shufflevector <2 x i8> %m, <2 x i8> %y, <2 x i32> <i32 0, i32 2>           ; LeftDemanded = 1, RightDemanded = 1
+  %res = add <2 x i8> %vv, %msplat
+  ret <2 x i8> %res
+}
+
+define <2 x i8> @common_binop_demand_via_splat_mask_poison_3(<2 x i8> %x, <2 x i8> %y, <2 x i8> %z) {
+; CHECK-LABEL: @common_binop_demand_via_splat_mask_poison_3(
```
Comment (goldsteinn) [inline llvm/test/Transforms/InstCombine/vec_demanded_elts.ll:1197]: %z unused?

File: llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp (hunk 1 above)
Comment (antoniofrighetto) [reply llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp:1880]: I might be wrong, but I was not able to get a miscompiled example when the other elements are poisoned, due to the way the transformation works on the demanded elements.

**Comment by antoniofrighetto** [comment]
> It looks like only your third test is problematic: https://alive2.llvm.org/ce/z/WrH49f
can the fix be made more precise?

Wouldn't that require to know right / left demanded of the mask of the use of the operand passed to `SimplifyDemandedVectorElts` (`%msplat`)? Not sure if there's a better / worth way to do this.

**Comment by goldsteinn** [comment]
> > It looks like only your third test is problematic: https://alive2.llvm.org/ce/z/WrH49f
> > can the fix be made more precise?
> 
> Wouldn't that require to know right / left demanded of the mask of the use of the operand passed to `SimplifyDemandedVectorElts` (`%msplat`)? Not sure if there's a better / worth way to do this.

+ 1

**Comment by antoniofrighetto** [comment]
@goldsteinn, don't have a strong opinion, but considering this looks quite of a corner case and it is fuzzer-generated, I'd rather favour readability / not make the code uglier, and rather being more conservative (the input space looks already quite small anyways).

File: llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp (hunk 1 above)
Comment (nikic) [reply llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp:1880]: There is a `DemandedElts == 1` check above, which guarantees only lane 0 is demanded.

**Review by nikic — APPROVED** [review]
LGTM
