### PR TITLE
[SPIR-V] Prevent adding duplicate binding instructions for implicit binding

### LINKED ISSUE #160716: [SPIRV][HLSL] Incorrect binding attributes on resource arrays
See https://godbolt.org/z/eWWaoT9bq. Note that `%21`  (the variable named "b") has two binding attributes:

```
        OpDecorate %21 DescriptorSet 0
        OpDecorate %21 Binding 0
        OpDecorate %21 Binding 1
```

It should only have the binding 0.

```
RWStructuredBuffer<float> b[4];

[numthreads(1,1,1)]
void main() {
  b[0][0] = b[1][0];
}
```

### PR DESCRIPTION
**Pull request by luciechoi**
Prevent adding duplicate instructions for implicit bindings when they are from the same resource. The fix is to store and check if the binding number is already assigned for each `OrderId`.

Resolves https://github.com/llvm/llvm-project/issues/160716

### CODE REVIEW

File: llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp [hunk 1]
```diff
@@ -112,11 +112,22 @@ uint32_t SPIRVLegalizeImplicitBinding::getAndReserveFirstUnusedBinding(
...
         cast<ConstantInt>(OldCI->getArgOperand(1))->getZExtValue();
-    const uint32_t NewBinding = getAndReserveFirstUnusedBinding(DescSet);
+
+    // Reuse an existing binding for this order ID, if one was already assigned.
+    // Otherwise, assign a new binding.
+    const uint32_t NewBinding =
+        (OrderIdToBinding.find(OrderId) != OrderIdToBinding.end())
+            ? OrderIdToBinding[OrderId]
+            : getAndReserveFirstUnusedBinding(DescSet);
+    OrderIdToBinding[OrderId] = NewBinding;
```
Comment (s-perron) [inline llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp:130]: I'm not sure this is well specified, but I think we should make this more robust. What should we do if we have the same orderid, but for different descriptor sets? I'm thinking we assign it a new binding number.

File: llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp [hunk 2]
```diff
@@ -112,11 +112,22 @@ uint32_t SPIRVLegalizeImplicitBinding::getAndReserveFirstUnusedBinding(
 }
 
 void SPIRVLegalizeImplicitBinding::replaceImplicitBindingCalls(Module &M) {
+  std::unordered_map<uint32_t, uint32_t> OrderIdToBinding;
```
Comment (s-perron) [inline llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp:115]: I don't think we need the hash table. The ImplicitBindingCalls should be sorted by the order id. You should have to only keep track of the last binding that you used.

Also, `std::unordered_map` is generally not used. In this case, where the orderIDs are dense, https://llvm.org/doxygen/classllvm_1_1DenseMap.html is probably the best option.

File: llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll [hunk 3]
```diff
@@ -44,30 +44,34 @@ entry:
   %3 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefrombinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 0, i32 2, i32 1, i32 0, ptr nonnull @.str.6)
   %4 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefrombinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 10, i32 1, i32 1, i32 0, ptr nonnull @.str.8)
   %5 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefromimplicitbinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 2, i32 10, i32 1, i32 0, ptr nonnull @.str.10)
-  %6 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefromimplicitbinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 3, i32 10, i32 1, i32 0, ptr nonnull @.str.12)
+  %6 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefromimplicitbinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 3, i32 10, i32 2, i32 0, ptr nonnull @.str.12)
   %7 = tail call target("spirv.SignedImage", i32, 5, 2, 0, 0, 2, 0) @llvm.spv.resource.handlefrombinding.tspirv.SignedImage_i32_5_2_0_0_2_0t(i32 10, i32 2, i32 1, i32 0, ptr nonnull @.str.14)
```
Comment (s-perron) [inline llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll:48]: Are the check above robust enough to catch an error for this? Without your change there would have been extra binding decorations, but the CHECK do nothing to make sure the extra bindings are not used.

What you could do is add a new resource with orderid 4, and make sure it gets binding 4. That is, the array takes up only a single binding.

**Review by s-perron — COMMENTED** [review]
Thanks for the quick turnaround on this. You found the right place in the code. This looks good, but it could be make a little more robust.

File: llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp (hunk 1 above)
Comment (luciechoi) [reply llvm/lib/Target/SPIRV/SPIRVLegalizeImplicitBinding.cpp]: I see, thanks for the clarification. I added a check above in `collectBindingInfo()` to reject such cases and added a unit test.

File: llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll (hunk 3 above)
Comment (luciechoi) [reply llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll]: 1. The changes here were to increase the size of `@.str.10` and have variables access different index:
```
%6 = h[0]
...
%8 = h[1]
``` 
I believe we have to use the same `OrderId` to test the change. In our case, we are reusing the OrderId `3`.

I swapped the order of `%7` and `%8` for readability as well as add `CHECK-NOT`. Without the code change, this unit test is correctly failing.

2. I'm curious about the convention around adding/modifying the llvm ir tests here, I feel it might help if we can add the original hlsl scripts (e.g. as comments), but this could be due to my lack of familiarity!

File: llvm/test/CodeGen/SPIRV/hlsl-resources/UniqueImplicitBindingNumber.ll [hunk 4]
```diff
@@ -0,0 +1,20 @@
+; RUN: llc -O0 -verify-machineinstrs -mtriple=spirv1.6-vulkan1.3-library %s -o -
```
Comment (s-perron) [inline llvm/test/CodeGen/SPIRV/hlsl-resources/UniqueImplicitBindingNumber.ll:1]: If you expect this to have an error. You can do

```suggestion
; RUN: not llc -O0 -verify-machineinstrs -mtriple=spirv1.6-vulkan1.3-library %s -o - 
```

Then you can add `FileCheck` to look for the error message you expect.

File: llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll (hunk 3 above)
Comment (s-perron) [reply llvm/test/CodeGen/SPIRV/hlsl-resources/ImplicitBinding.ll]: > 2\. I'm curious about the convention around adding/modifying the llvm ir tests here, I feel it might help if we can add the original hlsl scripts (e.g. as comments), but this could be due to my lack of familiarity!

Generally you modify them by hand. We don't usually keep the original generators around. some of these may not have had an original HLSL.

**Review by s-perron — APPROVED** [review]
