### PR TITLE
[InstCombine] simplify average of lsb

### LINKED ISSUE #94737: [InstCombine] Failure to simplify average of lsb
Noticed while investigating avgfloor codegen as part of #53648:
```c
unsigned src(unsigned a, unsigned b) {
  return ((a % 2) + (b % 2)) / 2;
}
unsigned tgt(unsigned a, unsigned b) {
    return (a & b & 1);
}
```
We fail to recognize that this can be treated as a basic logic op:
```ll
define i32 @src(i32 %a, i32 %b) {
  %rem = and i32 %a, 1
  %rem1 = and i32 %b, 1
  %add = add nuw nsw i32 %rem1, %rem
  %div2 = lshr i32 %add, 1
  ret i32 %div2
}
define i32 @tgt(i32 %a, i32 %b) {
  %and = and i32 %a, 1
  %and1 = and i32 %and, %b
  ret i32 %and1
}
```
Alive2: https://alive2.llvm.org/ce/z/XtJ4Rs

### PR DESCRIPTION
**Pull request by c8ef**
close: #94737
alive2: ~~https://alive2.llvm.org/ce/z/TtauVq~~ https://alive2.llvm.org/ce/z/WF_7mX

In this patch, we combine `(X + Y) / 2` into `(X & Y)` only when both X and Y are less than or equal to 1.

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp [hunk 1]
```diff
@@ -1284,6 +1284,14 @@ Instruction *InstCombinerImpl::visitLShr(BinaryOperator &I) {
     return NewSub;
   }
 
+  // ((X % 2) + (Y % 2)) / 2 --> (X & Y & 1)
+  if (match(Op0,
+            m_Add(m_And(m_Value(X), m_One()), m_And(m_Value(Y), m_One()))) &&
```
Comment (goldsteinn) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]: Think this can be generalized as just `(X + Y)/2` -> `(X & Y & 1)` where we can prove `X u<= 1` and `Y u<= 1`.

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]: No. Please use `computeKnownBits(...).countMaxActiveBits() <= 1`.

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp [hunk 2]
```diff
@@ -1284,6 +1284,14 @@ Instruction *InstCombinerImpl::visitLShr(BinaryOperator &I) {
     return NewSub;
   }
 
+  // Fold (X + Y) / 2 --> (X & Y & 1) iff (X u<= 1) && (Y u<= 1)
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1287]:
```suggestion
  // Fold (X + Y) / 2 --> (X & Y) iff (X u<= 1) && (Y u<= 1)
```

https://alive2.llvm.org/ce/z/WF_7mX

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp [hunk 3]
```diff
@@ -1284,6 +1284,13 @@ Instruction *InstCombinerImpl::visitLShr(BinaryOperator &I) {
     return NewSub;
   }
 
+  // Fold (X + Y) / 2 --> (X & Y) iff (X u<= 1) && (Y u<= 1)
+  if (match(Op0, m_Add(m_Value(X), m_Value(Y))) && match(Op1, m_One()) &&
+      computeKnownBits(X, 0, &I).countMaxActiveBits() <= 1 &&
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]: @nikic Can you check compile-time impact of this change? If it is high, I suggest to revert the generalization.

Comment (nikic) [reply llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]: No compile-time impact.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by goldsteinn** [comment]
LGTM

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp (hunk 3 above)
Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]: http://llvm-compile-time-tracker.com/compare.php?from=d442bf043537fd4bc0c2fc5a4d77337b0d482ea9&to=8fda4ae9c656cec3a12a04a0a218149aac28eddf&stat=instructions:u

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp (hunk 2 above)
Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp]: It looks unrelated. Don't worry :)

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp [hunk 4]
```diff
@@ -1284,6 +1284,13 @@ Instruction *InstCombinerImpl::visitLShr(BinaryOperator &I) {
...
+      computeKnownBits(Y, 0, &I).countMaxActiveBits() <= 1) {
+    return BinaryOperator::CreateAnd(X, Y);
+  }
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1292]: Drop braces here. See https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements.

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp (hunk 3 above)
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1289]:
```suggestion
      computeKnownBits(X, /*Depth=*/0, &I).countMaxActiveBits() <= 1 &&
```

File: llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp [hunk 5]
```diff
@@ -1284,6 +1284,13 @@ Instruction *InstCombinerImpl::visitLShr(BinaryOperator &I) {
     return NewSub;
   }
 
+  // Fold (X + Y) / 2 --> (X & Y) iff (X u<= 1) && (Y u<= 1)
+  if (match(Op0, m_Add(m_Value(X), m_Value(Y))) && match(Op1, m_One()) &&
+      computeKnownBits(X, 0, &I).countMaxActiveBits() <= 1 &&
+      computeKnownBits(Y, 0, &I).countMaxActiveBits() <= 1) {
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp:1290]:
```suggestion
      computeKnownBits(Y, /*Depth=*/0, &I).countMaxActiveBits() <= 1) {
```

**Review by dtcxzyw — APPROVED** [review]
LGTM. Thank you!

**Comment by HendrikHuebner** [comment]
@c8ef I was already assigned to this and still planning to work on it. Please ask first before you take issues that are already assigned to someone else.
