### PR TITLE
[ConstraintElim] Do not allow overflows in `Decomposition`

### LINKED ISSUE #140481: wrong code at -O{s,2,3} on x86_64-linux-gnu
Compiler Explorer: https://godbolt.org/z/KGW6a53xf

It appears to be a regression from 16.0.0, and affects 17.0.1 and later. 

```
[590] % clangtk -v
clang version 21.0.0git (https://github.com/llvm/llvm-project.git fb86b3d96b73f4e628288b180ef4e038da8b7bc1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/home/suz/suz-local/software/local/clang-trunk/bin
Build config: +assertions
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 12.1
[591] % 
[591] % clangtk -O1 small.c; ./a.out
[592] % 
[592] % clangtk -O3 small.c
[593] % ./a.out
Aborted
[594] % 
[594] % cat small.c
int a = 1, b, c;
int main() {
  b = -5001001 * a + 5001000;
  while (b >= 5001001)
    b = a + 5001000;
  c = -5001000 * b - 5001001;
  if (5001000 * c >= b)
    __builtin_abort();
  return 0;
}
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Consider the following case:
```
define i1 @pr140481(i32 %x) {
  %cond = icmp slt i32 %x, 0
  call void @llvm.assume(i1 %cond)
  %add = add nsw i32 %x, 5001000
  %mul1 = mul nsw i32 %add, -5001000
  %mul2 = mul nsw i32 %mul1, 5001000
  %cmp2 = icmp sgt i32 %mul2, 0
  ret i1 %cmp2
}
```
Before this patch, `decompose(%mul2)` returns `-25010001000000 * %x + 4052193514966861312`.
Therefore, `%cmp2` will be simplified into true because `%x s< 0 && -25010001000000 * %x + 4052193514966861312 s<= 0` is unsat.

It is incorrect since the offset `-25010001000000 * 5001000 -> 4052193514966861312` signed wraps.
This patch treats a decomposition as invalid if overflows occur when computing coefficients.

Closes https://github.com/llvm/llvm-project/issues/140481.

### CODE REVIEW

**Comment by dtcxzyw** [comment]
No real-world impact.

**Comment by dtcxzyw** [comment]
Compile-time impact: https://llvm-compile-time-tracker.com/compare.php?from=7e14161f49b32387988cf9d937bbfaa27d0fbdd5&to=854df22efb6c18b88e29f23def8c3b3643083ba7&stat=instructions:u

**Review by antoniofrighetto — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp [hunk 1]
```diff
@@ -366,26 +352,38 @@ struct Decomposition {
   Decomposition(int64_t Offset, ArrayRef<DecompEntry> Vars)
       : Offset(Offset), Vars(Vars) {}
 
-  void add(int64_t OtherOffset) {
-    Offset = addWithOverflow(Offset, OtherOffset);
+  // Return true if the new decomposition is invalid.
```
Comment (fhahn) [inline llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:355]:
```suggestion
  /// Add \p OtherOffset and return true if the operation overflows, i.e. the new decomposition is invalid.
```

would be good to turn them all into doc-dcomments

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp [hunk 2]
```diff
@@ -534,20 +536,21 @@ static Decomposition decompose(Value *V,
...
+      if (auto Decomp = MergeResults(Op0, Op1, IsSigned))
+        return *Decomp;
 
     if (match(V, m_NSWSub(m_Value(Op0), m_Value(Op1)))) {
       auto ResA = decompose(Op0, Preconditions, IsSigned, DL);
       auto ResB = decompose(Op1, Preconditions, IsSigned, DL);
-      ResA.sub(ResB);
-      return ResA;
+      if (!ResA.sub(ResB))
+        return ResA;
```
Comment (fhahn) [inline llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:546]: Does it make sense to continue below after overflow? Should we just return std::nullopt?

Same for the others

**Review by fhahn — COMMENTED** [review]
Thanks for updating the code to consistently check for overlfow!

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp (hunk 2 above)
Comment (dtcxzyw) [reply llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:552]: Done.
BTW, it is worth noting that `Preconditions` is not correctly maintained. Do you think it is valuable to fix this problem?

Comment (fhahn) [reply llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:552]: Not correctly maintained as in contains preconditions that may not be needed as we faild with the decomposition?

**Review by fhahn — APPROVED** [review]
LGTM, thanks!

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp (hunk 2 above)
Comment (dtcxzyw) [reply llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:552]: Yes. It may miss some optimizations. But it looks unlikely to happen in real-world cases.

**Comment by AZero13** [comment]
If it isn't too late.c should we backport this to 20.x?

**Comment by AZero13** [comment]
If it isn't too late.c should we backport this to 20.x?
