### PR TITLE
[DirectX] Fix order of `v2::DescriptorRange`

### LINKED ISSUE #145438: [DirectX] RootSignature's `v2::DescriptorRange` is misordered
We currently have the `v2::DescriptorRange` inherit from the `v1::DescriptorRange` and add a `Flags` field, but this is incorrect. In both the 1.0 and 1.1 root signature formats, the `OffsetInDescriptorsFromTableStart` comes last. That is, `v1::DescriptorRange` is laid out as follows:
```c++
struct DescriptorRange {
  uint32_t RangeType;
  uint32_t NumDescriptors;
  uint32_t BaseShaderRegister;
  uint32_t RegisterSpace;
  uint32_t OffsetInDescriptorsFromTableStart;
};
```

This matches what we have today, but `v2::DescriptorRange` is laid out like so:
```c++
struct DescriptorRange {
  uint32_t RangeType;
  uint32_t NumDescriptors;
  uint32_t BaseShaderRegister;
  uint32_t RegisterSpace;
  uint32_t Flags;
  uint32_t OffsetInDescriptorsFromTableStart;
};
```

This *does not* match what we have today, as we have the `OffsetInDescriptorsFromTableStart` and `Flags` fields reversed. This causes obvious issues when we feed shaders that have root signatures with descriptor ranges into any driver.

### LINKED ISSUE #145439: [DirectX] Root signature's `DescriptorTableView` has undefined behaviour for version 1.0 root signatures.
We currently have the "DescriptorTableView" load a `DirectX::DescriptorTable` with a type like so:
```c++
struct DescriptorTable {
  uint32_t NumRanges;
  uint32_t RangesOffset;
  ViewArray<dxbc::RTS0::v2::DescriptorRange> Ranges;
};
```

However, we set up the ranges view like so:
```c++
    size_t RangeSize = sizeof(dxbc::RTS0::v1::DescriptorRange);
    if (Version > 1)
      RangeSize = sizeof(dxbc::RTS0::v2::DescriptorRange);

    Table.Ranges.Stride = RangeSize;
    Table.Ranges.Data =
        ParamData.substr(2 * sizeof(uint32_t), Table.NumRanges * RangeSize);
```

This invokes undefined behaviour. It is not legal to store a `dxbc::RTS0::v1::DescriptorRange` in an object of type `dxbc::RTS0::v2::DescriptorRange` (the inheritance is in the other direction. Furthermore, `dxbc::RTS0::v2::DescriptorRange` will not fit in `sizeof(dxbc::RTS0::v1::DescriptorRange)`, and the last field (currently `Flags`) will overlap with the next object.

Note: this may become moot depending on the fix to #145438, as that issue implies that we won't be able to have an inheritance relationship between the versions of DescriptorRange at all.

### PR DESCRIPTION
**Pull request by joaosaffran**
As pointed in #145438, the order of elements in `v2::DescriptorRange` is wrong according to the root signature file format. This changes the order and updates the code and test to continue to pass. 

Closes: #145438

### CODE REVIEW

File: llvm/include/llvm/Object/DXContainer.h [hunk 1]
```diff
@@ -212,9 +207,7 @@ struct DescriptorTableView : RootParameterView {
         support::endian::read<uint32_t, llvm::endianness::little>(Current);
     Current += sizeof(uint32_t);
 
-    size_t RangeSize = sizeof(dxbc::RTS0::v1::DescriptorRange);
-    if (Version > 1)
-      RangeSize = sizeof(dxbc::RTS0::v2::DescriptorRange);
+    size_t RangeSize = sizeof(T);
 
     Table.Ranges.Stride = RangeSize;
```
Comment (bogner) [inline llvm/include/llvm/Object/DXContainer.h]: This shouldn't be necessary any more - I believe `ViewArray` sets the Stride correctly

File: llvm/lib/ObjectYAML/DXContainerYAML.cpp [hunk 2]
```diff
@@ -107,35 +140,23 @@ DXContainerYAML::RootSignatureYamlDesc::create(
...
-        }
-        TableYaml.Ranges.push_back(NewR);
+      if (Version == 1) {
+        llvm::Expected<
+            object::DirectX::DescriptorTable<dxbc::RTS0::v1::DescriptorRange>>
+            TableOrErr = DTV->read<dxbc::RTS0::v1::DescriptorRange>();
+        if (Error E = TableOrErr.takeError())
+          return std::move(E);
+        auto Table = *TableOrErr;
+        addDescriptorRanges(Header, RootSigDesc, Table);
```
Comment (bogner) [inline llvm/lib/ObjectYAML/DXContainerYAML.cpp]: It would simplify things a bit to move the call to `read` into the templated function. That is,
```c++
template <typename T>
static llvm::Error
readDescriptorRanges(DXContainerYAML::RootParameterHeaderYaml &Header,
                     DXContainerYAML::RootSignatureYamlDesc &RootSigDesc,
                     object::DirectX::DescriptorTableView *DTV) {
  llvm::Expected<object::DirectX::DescriptorTable<T>> Table = DTV->read<T>();
  if (Error E = Table.takeError())
    return std::move(E);
  // Use Table->NumRanges, Table->Ranges, etc.
  return Error::success();
```

File: llvm/lib/ObjectYAML/DXContainerYAML.cpp [hunk 3]
```diff
@@ -107,35 +140,23 @@ DXContainerYAML::RootSignatureYamlDesc::create(
...
+      } else {
```
Comment (bogner) [inline llvm/lib/ObjectYAML/DXContainerYAML.cpp]: Might be better to explicitly not handle versions other than 1 or 2 so that if we add versions in the future and forget to update this it's very obvious. At this point we've validated that the version is something we expect, right? In that case, we can just throw an unreachable here.
```c++
      if (Version == 1) {
        if (Error E = readDescriptorRanges<dxbc::RTS0::v1::DescriptorRange>(
                Header, RootSigDesc, DTV))
          return std::move(E);
      } else if (Version == 2) {
        if (Error E = readDescriptorRanges<dxbc::RTS0::v2::DescriptorRange>(
                Header, RootSigDesc, DTV))
          return std::move(E);
      } else
        llvm_unreachable("Unknown version for DescriptorRanges");
```

File: llvm/include/llvm/Object/DXContainer.h [hunk 4]
```diff
@@ -207,11 +207,8 @@ struct DescriptorTableView : RootParameterView {
         support::endian::read<uint32_t, llvm::endianness::little>(Current);
     Current += sizeof(uint32_t);
 
-    size_t RangeSize = sizeof(T);
-
-    Table.Ranges.Stride = RangeSize;
     Table.Ranges.Data =
-        ParamData.substr(2 * sizeof(uint32_t), Table.NumRanges * RangeSize);
+        ParamData.substr(2 * sizeof(uint32_t), Table.NumRanges * sizeof(T));
```
Comment (bogner) [inline llvm/include/llvm/Object/DXContainer.h]: Would it be clearer to use `Table.NumRanges * Tabled.Ranges.Stride` here?

**Review by bogner — APPROVED** [review]

File: llvm/lib/ObjectYAML/DXContainerYAML.cpp [hunk 5]
```diff
@@ -107,36 +148,16 @@ DXContainerYAML::RootSignatureYamlDesc::create(
...
+      if (Version == 1) {
+        if (Error E = readDescriptorRanges<dxbc::RTS0::v1::DescriptorRange>(
+                Header, RootSigDesc, DTV))
+          return std::move(E);
+      } else if (Version == 2) {
+        if (Error E = readDescriptorRanges<dxbc::RTS0::v2::DescriptorRange>(
+                Header, RootSigDesc, DTV))
+          return std::move(E);
+      } else
+        llvm_unreachable("Unknown version for DescriptorRanges");
```
Comment (inbelic) [inline llvm/lib/ObjectYAML/DXContainerYAML.cpp:160]: Not a change, but maybe such cases will be a nice reason to use the explicitly defined root signature enum when it is merged in.

File: llvm/include/llvm/BinaryFormat/DXContainer.h [hunk 6]
```diff
@@ -740,10 +740,19 @@ struct RootDescriptor : public v1::RootDescriptor {
   }
 };
 
-struct DescriptorRange : public v1::DescriptorRange {
+struct DescriptorRange {
```
Comment (inbelic) [inline llvm/include/llvm/BinaryFormat/DXContainer.h:743]: Ah I see now. The old struct is still defined in the v1 namespace and this is defined in the v2 namespace.

**Review by inbelic — APPROVED** [review]
