### PR TITLE
[mlir][vector] Fix invalid `LoadOp` indices being created

### LINKED ISSUE #71326: Possible bug in `convert-vector-to-scf`
There appears to be a bug in the `convert-vector-to-scf` where converting certain `vector.transfer_read` ops causes an invalid `memref.load` op to be created.  Maybe the input IR that causes this is incompatible with the pass, but I think a proper error check should be done rather than let the implementation create an invalid op.

Example IR:

```
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, 0, 0, d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0, 0, 0, d3)>
func.func @main(%subview:  memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %c0 : index, %c0_i32 : i32, %2: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
}
```

Applying `mlir-opt --convert-vector-to-scf` to this IR yields the following error
```
transfer-read.mlir:4:10: error: 'memref.load' op incorrect number of indices for load
    %3 = vector.transfer_read %subview[%c0, %c0, %c0, %c0], %c0_i32, %2 {in_bounds = [true, true, true, true], permutation_map = #map1} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<1x1x1x32xi32>
         ^
transfer-read.mlir:4:10: note: see current operation: %8 = "memref.load"(%4, %0, %0) <{nontemporal = false}> : (memref<1xvector<32xi1>>, index, index) -> vector<32xi1>
```

Note that the IR gets successfully transformed with the `full-unroll` option turned on.  Applying `mlir-opt ---convert-vector-to-scf=full-unroll` yields

```
  func.func @main(%arg0: memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, %arg1: index, %arg2: i32, %arg3: vector<1x32xi1>) -> vector<1x1x1x32xi32> {
    %0 = vector.splat %arg2 : vector<1x1x1x32xi32>
    %1 = vector.extract %arg3[0] : vector<1x32xi1>
    %2 = vector.transfer_read %arg0[%arg1, %arg1, %arg1, %arg1], %arg2, %1 {in_bounds = [true]} : memref<1x1x1x?xi32, strided<[17, 17, 17, 1], offset: ?>>, vector<32xi32>
    %3 = vector.insert %2, %0 [0, 0, 0] : vector<32xi32> into vector<1x1x1x32xi32>
    return %3 : vector<1x1x1x32xi32>
  }
  ```
  
  This makes me believe that it should also work without the option, since in this case all the leading dims are size `1` and thus any loops that get generated would be trivial single iteration loops that would canonicalize away.  Which, as far as I can tell, would  be exactly what the unrolled version would generate.

### PR DESCRIPTION
**Pull request by rikhuijzer**
Fixes https://github.com/llvm/llvm-project/issues/71326.

The cause of the issue was that a new `LoadOp` was created which looked something like:
```mlir
%arg4 = 
func.func main(%arg1 : index, %arg2 : index) {
  %alloca_0 = memref.alloca() : memref<vector<1x32xi1>>
  %1 = vector.type_cast %alloca_0 : memref<vector<1x32xi1>> to memref<1xvector<32xi1>>
  %2 = memref.load %1[%arg1, %arg2] : memref<1xvector<32xi1>>
  return
}
```
which crashed inside the `LoadOp::verify`. Note here that `%alloca_0` is 0 dimensional, `%1` has one dimension, but `memref.load` tries to index `%1` with two indices.

This is now fixed by using the fact that `unpackOneDim` always unpacks one dim 

https://github.com/llvm/llvm-project/blob/1bce61e6b01b38e04260be4f422bbae59c34c766/mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp#L897-L903

and so the `loadOp` should just index only one dimension.

### CODE REVIEW

File: mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp [hunk 1]
```diff
@@ -1615,8 +1615,10 @@ GetGlobalOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
 //===----------------------------------------------------------------------===//
 
 LogicalResult LoadOp::verify() {
-  if (getNumOperands() != 1 + getMemRefType().getRank())
-    return emitOpError("incorrect number of indices for load");
+  if (getNumOperands() - 1 != getMemRefType().getRank()) {
+    return emitOpError("incorrect number of indices for load, expected ")
+           << getMemRefType().getRank() << " but got " << getNumOperands() - 1;
+  }
```
Comment (rikhuijzer) [inline mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp:1621]: I moved the `+ 1` to the other side because, for example, `memref.load %1[%arg4]` has `%1` as its first operand and `%arg4` as it's second operand. So the number of indices for `memref.load` is `getNumOperands() - 1`.

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp [hunk 2]
```diff
@@ -897,7 +896,8 @@ struct TransferOpConversion : public VectorToSCFPattern<OpTy> {
       } else {
         // It's safe to assume the mask buffer can be unpacked if the data
         // buffer was unpacked.
-        auto castedMaskType = *unpackOneDim(maskBufferType);
+        auto maskBufferType = dyn_cast<MemRefType>(maskBuffer.getType());
```
Comment (Lewuathe) [inline mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:899]: We may want to be explicit of the type here.

```suggestion
        MemRefType maskBufferType = dyn_cast<MemRefType>(maskBuffer.getType());
```

Comment (rikhuijzer) [reply mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:899]: As far as I understood, we should use `auto` when the type is obvious (https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable).

File: mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp (hunk 1 above)
Comment (MacDue) [reply mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp:1621]: I may be missing something obvious :sweat_smile:, but is there a reason why this is not just:
 ```suggestion
  if (getIndices().size() != getMemRefType().getRank()) {
    return emitOpError("incorrect number of indices for load, expected ")
           << getMemRefType().getRank() << " but got " <<getIndices().size();
  }
```

Comment (rikhuijzer) [reply mlir/lib/Dialect/MemRef/IR/MemRefOps.cpp]: Thanks 👍 Nice suggestion!

File: mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp (hunk 2 above)
Comment (Lewuathe) [reply mlir/lib/Conversion/VectorToSCF/VectorToSCF.cpp:899]: Thanks for the pointer. That makes sense.

**Review by Lewuathe — APPROVED** [review]
This looks good to me!

**Comment by rikhuijzer** [comment]
I'm working on reverting this PR. It crashes on the clang-aarch64-sve-vls builder:
```
******************** TEST 'MLIR :: Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir' FAILED ********************
Exit Code: 2
Command Output (stdout):
--
# RUN: at line 1
/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/bin/mlir-opt /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir -convert-vector-to-scf -arm-sve-legalize-vector-storage -convert-vector-to-llvm="enable-arm-sve" -test-lower-to-llvm |  mlir-cpu-runner -e=entry -entry-point-result=void --march=aarch64 --mattr="+sve" -shared-libs=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/./lib/libmlir_c_runner_utils.so |  /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/bin/FileCheck /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir
# executed command: /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/bin/mlir-opt /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir -convert-vector-to-scf -arm-sve-legalize-vector-storage -convert-vector-to-llvm=enable-arm-sve -test-lower-to-llvm
# .---command stderr------------
# | /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir:66:15: error: 'memref.load' op incorrect number of indices for load, expected 2 but got 1
# |   %vector_a = vector.transfer_read %a[%c0, %c0, %c0], %cst, %mask_a {in_bounds = [true, true, true]} : memref<1x2x?xf32>, vector<1x2x[4]xf32>
# |               ^
# | /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir:66:15: note: see current operation: %21 = "memref.load"(%20, %arg3) <{nontemporal = false}> : (memref<1x2xvector<[4]xi1>>, index) -> vector<[4]xi1>
# `-----------------------------
# error: command failed with exit status: 1
# executed command: mlir-cpu-runner -e=entry -entry-point-result=void --march=aarch64 --mattr=+sve -shared-libs=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/./lib/libmlir_c_runner_utils.so
# .---command stderr------------
# | Error: entry point not found
# `-----------------------------
# error: command failed with exit status: 1
# executed command: /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/bin/FileCheck /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir
# .---command stderr------------
# | FileCheck error: '<stdin>' is empty.
# | FileCheck command line:  /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/stage1/bin/FileCheck /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/llvm/mlir/test/Integration/Dialect/Vector/CPU/ArmSVE/arrays-of-scalable-vectors.mlir
# `-----------------------------
# error: command failed with exit status: 2
--
********************
```
