### PR TITLE
[clang-format] Align trailing comments for function parameters

### LINKED ISSUE #85123: [clang-format] Incorrect indentation after a closing paren with Align ConsecutiveDeclarations + TrailingComments
In a scenario such as this:
```c++
void foo(
    int name, // name
    float name, // name
    int name) // name
{
}
```
The final trailing comment is incorrectly formatted when both `AlignConsecutiveDeclarations` and `AlignTrailingComments` are enabled.
The formatted output:
```c++
void foo(int   name, // name
         float name, // name
         int   name)   // name
{}

// EXPECTED
void foo(int   name, // name
         float name, // name
         int   name) // name
{}
```

It seems to be that the trailing comment's doesn't gets its `StartOfTokenColumn` value properly updated by the time `WhitespaceManager::alignTrailingComments` is invoked:
https://github.com/llvm/llvm-project/blob/0b4688403672264ab451992a3461a0df113c3bd7/clang/lib/Format/WhitespaceManager.cpp#L1111

### PR DESCRIPTION
**Pull request by sstwcw**
before

```C++
void foo(int   name, // name
         float name, // name
         int   name)   // name
{}
```

after

```C++
void foo(int   name, // name
         float name, // name
         int   name) // name
{}
```

Fixes #85123.

As the bug report explained, the procedure for aligning the function parameters previously failed to update `StartOfTokenColumn`.

### CODE REVIEW

File: clang/lib/Format/WhitespaceManager.cpp [hunk 1]
```diff
@@ -399,6 +399,15 @@ AlignTokenSequence(const FormatStyle &Style, unsigned Start, unsigned End,
       }
     }
   }
+
+  // The scope to be aligned may not occupy entire lines. The rest of the line
+  // needs some book-keeping.
+  for (unsigned i = End; i < Changes.size() && Changes[i].NewlinesBefore == 0;
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp]:
```suggestion
  for (unsigned I = End; i < Changes.size() && Changes[i].NewlinesBefore == 0;
```

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/WhitespaceManager.cpp [hunk 2]
```diff
@@ -650,8 +650,16 @@ static unsigned AlignTokens(const FormatStyle &Style, F &&Matches,
     MatchedIndices.push_back(I);
   }
 
+  // Pass to the function entire lines, so it can update the state of all tokens
+  // that move.
   EndOfSequence = I;
+  while (EndOfSequence < Changes.size() &&
+         Changes[EndOfSequence].NewlinesBefore == 0) {
+    ++EndOfSequence;
```
[the remark this answers is not in the document]
Comment (owenca) [reply clang/lib/Format/WhitespaceManager.cpp]: Sorry about that. Yeah, we can move it (in line 510?) out of the loop.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 3]
```diff
@@ -507,7 +507,7 @@ static unsigned AlignTokens(const FormatStyle &Style, F &&Matches,
   };
 
   unsigned I = StartAt;
-  unsigned E = Changes.size();
+  auto E = Changes.size();
```
Comment (owenca) [inline clang/lib/Format/WhitespaceManager.cpp]: `const auto` as suggested?

**Review by owenca — APPROVED** [review]
