### PR TITLE
Reapply "[Clang] Profile singly-resolved UnresolvedLookupExpr with the declaration"

### LINKED ISSUE #139476: out-of-line definition of constrained members is not accepted (new failing example of closed bug)
[currently closed bug here](https://github.com/llvm/llvm-project/issues/49620) (maybe reopen that and close this one)

```
namespace moo
	{
		template <typename T>
		constexpr bool baa = true;
		
		template <typename T> requires baa<T>
		void caw();
	}

template <typename T> requires moo::baa<T>
void moo::caw() {}
```
[compiler-explorer](https://godbolt.org/z/vGoavxf7M)

(using -std=c++26)
clang (trunk): error: out-of-line definition of 'caw' does not match any declaration in namespace 'moo'
gcc: compiles successfully

### PR DESCRIPTION
**Pull request by zyn0217**
For a dependent variable template specialization, we don't build a dependent Decl node or a DeclRefExpr to represent it. Instead, we preserve the UnresolvedLookupExpr until instantiation.

However, this approach isn't ideal for constraint normalization. We consider the qualifier during profiling, but since that's based on the written code, it can introduce confusing differences, even when the expressions resolve to the same declaration.

This change profiles the underlying VarTemplateDecl if UnresolvedLookupExpr is used to model a dependent use of it.

Fixes https://github.com/llvm/llvm-project/issues/139476

### CODE REVIEW

File: clang/lib/AST/StmtProfile.cpp [hunk 1]
```diff
@@ -2189,8 +2189,14 @@ StmtProfiler::VisitCXXPseudoDestructorExpr(const CXXPseudoDestructorExpr *S) {
 
 void StmtProfiler::VisitOverloadExpr(const OverloadExpr *S) {
   VisitExpr(S);
-  VisitNestedNameSpecifier(S->getQualifier());
-  VisitName(S->getName(), /*TreatAsDecl*/ true);
+  bool DescribingDependentVarTemplate =
+      S->getNumDecls() == 1 && isa<VarTemplateDecl>(*S->decls_begin());
```
Comment (zyn0217) [inline clang/lib/AST/StmtProfile.cpp:2193]: Instead of OverloadExpr, I'm thinking if it would be better to invent a new Expr node to describe dependent cases (we use DeclRefExpr for non-dependent uses), just like ConceptSpecializationExpr.

**Review by cor3ntin — APPROVED** [review]
we could merge that now to fix the bug, and introduce a new node later
