### PR TITLE
[RISC-V] Fix incorrect epilogue_begin

### LINKED ISSUE #120553: [RISC-V] epilogue_begin is set incorrectly
For the following test,
```
int main(int argc, char **argv)
{
  int foo = 1;

  return 0;
}
```
GCC (riscv32) generates (https://godbolt.org/z/Wqze6n8Gs):
```
main:
.LFB0:
        .file 1 "/app/example.c"
        .loc 1 2 1
        .cfi_startproc
        addi    sp,sp,-48
        .cfi_def_cfa_offset 48
        sw      ra,44(sp)
        sw      s0,40(sp)
        .cfi_offset 1, -4
        .cfi_offset 8, -8
        addi    s0,sp,48
        .cfi_def_cfa 8, 0
        sw      a0,-36(s0)
        sw      a1,-40(s0)
        .loc 1 3 7
        li      a5,1
        sw      a5,-20(s0)
        .loc 1 5 10
        li      a5,0
        .loc 1 6 1
        mv      a0,a5
        lw      ra,44(sp)
        .cfi_restore 1
        lw      s0,40(sp)
        .cfi_restore 8
        .cfi_def_cfa 2, 48
        addi    sp,sp,48
        .cfi_def_cfa_offset 0
        jr      ra
        .cfi_endproc
.LFE0:
        .size   main, .-main
```
and Clang riscv32 generates (https://godbolt.org/z/TMGPsr44s):
```
main:
.Lfunc_begin0:
        .file   0 "/app" "/app/example.c" md5 0x8aa04db627be45b3215ab92eac2e23c5
        .file   1 "example.c" md5 0x8aa04db627be45b3215ab92eac2e23c5
        .loc    1 2 0
        .cfi_sections .debug_frame
        .cfi_startproc
        addi    sp, sp, -32
        .cfi_def_cfa_offset 32
        sw      ra, 28(sp)
        sw      s0, 24(sp)
        .cfi_offset ra, -4
        .cfi_offset s0, -8
        addi    s0, sp, 32
        .cfi_def_cfa s0, 0
        mv      a2, a0
        li      a0, 0
        sw      a0, -12(s0)
        sw      a2, -16(s0)
        sw      a1, -20(s0)
        li      a1, 1
.Ltmp0:
        .loc    1 3 7 prologue_end
        sw      a1, -24(s0)
        .cfi_def_cfa sp, 32
        lw      ra, 28(sp)                                        <<<<<<<<<<
        lw      s0, 24(sp)
        .cfi_restore ra
        .cfi_restore s0
        .loc    1 5 3 epilogue_begin                               <<<<<<<<<<
        addi    sp, sp, 32
        .cfi_def_cfa_offset 0
        ret
.Ltmp1:
.Lfunc_end0:
        .size   main, .Lfunc_end0-main
```
As can be seen from the Clang's output, the _epilogue_begin_ is set after the epilogue has actually begun. This creates a problem if we single step from line 3, or set a breakpoint on line 5, the FP has been restored to the parent frame's FP, and accessing variables goes to the wrong place.

$ gdb main.gcc
```
(gdb) b main
Breakpoint 1 at 0x10444: file main.c, line 3.
(gdb) c
Continuing.

Breakpoint 1, main (argc=1, argv=0x40800004) at main.c:3
3                 int foo = 1;
(gdb) si
0x00010446      3                 int foo = 1;
(gdb) p foo
$1 = 0
(gdb) si
5                   return 0;
(gdb) p foo
$2 = 1
(gdb) s
6       }
(gdb) p foo
$3 = 1
(gdb)

```
$ gdb main.llvm
```
(gdb) b main
Breakpoint 1 at 0x10496: file main.c, line 3.
(gdb) c
Continuing.

Breakpoint 1, main (argc=1, argv=0x407ffff4) at main.c:3
3                 int foo = 1;
(gdb) si
0x0001049a      3                 int foo = 1;
(gdb) p foo
$1 = 1
(gdb) si
0x0001049c      3                 int foo = 1;
(gdb) p foo
$2 = 1
(gdb) s
5                   return 0;
(gdb) p foo
$3 = -1242739775
(gdb)
```

### PR DESCRIPTION
**Pull request by RamNalamothu**
This patch resolves #120553

### CODE REVIEW

**Comment by topperc** [comment]
CC: @enoskova-sc does this interact with your shrinking wrapping patch?

**Comment by enoskova-sc** [comment]
@topperc, this patch interacts with my shrink wrapping, but it addresses independent problem.

**Comment by RamNalamothu** [comment]
Ping

**Comment by RamNalamothu** [comment]
Ping

**Comment by topperc** [comment]
Can you split the interface change that affects every target into a separate from the RISCV specific change?

**Comment by RamNalamothu** [comment]
> Can you split the interface change that affects every target into a separate from the RISCV specific change?

It is already separate. This PR has two commits, one which makes the interface change and the other which uses the revised interface to fix RISC-V specific issue.

Or are you suggesting making two PRs, one for the interface change and one for RISC-V specific fix?

**Comment by topperc** [comment]
> > Can you split the interface change that affects every target into a separate from the RISCV specific change?
> 
> It is already separate. This PR has two commits, one which makes the interface change and the other which uses the revised interface to fix RISC-V specific issue.
> 
> Or are you suggesting making two PRs, one for the interface change and one for RISC-V specific fix?

Make a separate PR. The github web interface won't let you push a PR as two separate commits.

**Comment by RamNalamothu** [comment]
> Make a separate PR. The github web interface won't let you push a PR as two separate commits.

#120622 for the interface change.

**Comment by mgudim** [comment]
It seems like in general we cannot guarantee that prolog / epilog code is a contiguous region since instructions can be moved by optimisation. What is the solution in that case?

Not saying we should address this in the PR, just wondering.

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp [hunk 1]
```diff
@@ -1000,20 +1005,20 @@ void RISCVFrameLowering::emitEpilogue(MachineFunction &MF,
     // If RestoreSPFromFP the stack pointer will be restored using the frame
     // pointer value.
     if (!RestoreSPFromFP)
-      RI->adjustReg(MBB, LastFrameDestroy, DL, SPReg, SPReg,
+      RI->adjustReg(MBB, LastScalarFrameDestroy, DL, SPReg, SPReg,
```
Comment (mgudim) [inline llvm/lib/Target/RISCV/RISCVFrameLowering.cpp:1008]: What is the point of  "Scalar" here?

File: llvm/test/CodeGen/RISCV/debug-line.ll [hunk 2]
```diff
@@ -0,0 +1,50 @@
+; RUN: llc -mtriple=riscv64 < %s | FileCheck %s
```
Comment (mgudim) [inline llvm/test/CodeGen/RISCV/debug-line.ll:1]: can you generate the checks with "update_llc_test_checks.py"?

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp (hunk 1 above)
Comment (RamNalamothu) [reply llvm/lib/Target/RISCV/RISCVFrameLowering.cpp:1008]: The logic here is trying to find the first scalar callee-saved register restore instruction using _FrameDestroy_ flag.

Before this patch, the _FrameDestroy_ flag was being added only to _CM.POP/libcall restore instruction_ and the _LastFrameDestroy_ would always end up with those, the only callee-saved register restore instructions with _FrameDestroy_ flag.

But this patch adds _FrameDestroy_ to all callee saved register restore instructions and hence I thought changing the name to what it represents might make sense. However, the name should have been _FirstScalarFrameDestroy_ and not _LastScalarFrameDestroy_. I will fix that.

File: llvm/test/CodeGen/RISCV/debug-line.ll (hunk 2 above)
Comment (RamNalamothu) [reply llvm/test/CodeGen/RISCV/debug-line.ll:1]: I have tried but somehow the checks weren't getting generated and hence I added the checks manually. This is happening probably due to the presence of debug information.

File: llvm/test/CodeGen/RISCV/debug-line.ll [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
+target triple = "riscv64-unknown-linux-gnu"
```
Comment (topperc) [inline llvm/test/CodeGen/RISCV/debug-line.ll:4]: Triple is already on the RUN line. And datalayout can be inferred from it.

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp (hunk 1 above)
Comment (RamNalamothu) [reply llvm/lib/Target/RISCV/RISCVFrameLowering.cpp:1008]: Thinking about it again, _FirstScalarCSRRestoreInsn_ made sense for the variable in question.

File: llvm/test/CodeGen/RISCV/debug-line.ll (hunk 3 above)
Comment (RamNalamothu) [reply llvm/test/CodeGen/RISCV/debug-line.ll:4]: Will remove those lines, thanks.

**Comment by topperc** [comment]
> It seems like in general we cannot guarantee that prolog / epilog code is a contiguous region since instructions can be moved by optimisation. What is the solution in that case?
> 
> Not saying we should address this in the PR, just wondering.

I know the MachineScheduler excludes CFI_INSTRUCTION from its scheduling regions which prevents it moving instructions in the prolog/epilog.

**Comment by RamNalamothu** [comment]
> It seems like in general we cannot guarantee that prolog / epilog code is a contiguous region since instructions can be moved by optimisation. What is the solution in that case?

All the code here that assumes prolog / epilog code i.e. CSR save / restore instructions is a contiguous region is part of the _prologepilog_ pass alone. So, I think, we are good here.

If we have to assume prolog / epilog code is not a contiguous region outside the _prologepilog_ pass, then it's a concern for all the targets, not just for RISC-V / this patch, on how _AsmPrinter_ is going to handle that while emitting _prologue_end / epilogue_begin_ which, I think, can be discussed as a separate topic (?).

**Comment by mgudim** [comment]
can you please rebase on the latest main so we see this on top of https://github.com/llvm/llvm-project/pull/120622

**Comment by mgudim** [comment]
> This patch resolves https://github.com/llvm/llvm-project/issues/120553

Please add a commit message describing the problem and solution

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp [hunk 4]
```diff
@@ -1088,7 +1092,8 @@ void RISCVFrameLowering::emitEpilogue(MachineFunction &MF,
   // Skip to before the restores of scalar callee-saved registers
   // FIXME: assumes exactly one instruction is used to restore each
   // callee-saved register.
-  auto LastFrameDestroy = std::prev(MBBI, getUnmanagedCSI(MF, CSI).size());
+  auto FirstScalarCSRRestoreInsn =
```
Comment (mgudim) [inline llvm/lib/Target/RISCV/RISCVFrameLowering.cpp:1095]: I still don't understand why you need "Scalar" in the variable name. What if we're restoring a vector register first? Is it different somehow?

**Comment by RamNalamothu** [comment]
> can you please rebase on the latest main so we see this on top of #120622

It's already rebased on to tip of main branch.

> > This patch resolves #120553
> 
> Please add a commit message describing the problem and solution

The commit message has the description 23768d5b9. I just didn't replicate that here on PR page and instead pointed to the issue #120553.

File: llvm/test/CodeGen/RISCV/debug-line.ll (hunk 2 above)
Comment (mgudim) [reply llvm/test/CodeGen/RISCV/debug-line.ll:1]: can you make your test the same as RISCV/rvv/get-vlen-debugloc.mir

I think we should avoid updating the checks manually whenever possible

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp (hunk 1 above)
Comment (RamNalamothu) [reply llvm/lib/Target/RISCV/RISCVFrameLowering.cpp]: > I still don't understand why you need "Scalar" in the variable name. What if we're restoring a vector register first? Is it different somehow?

After this patch, _LastFrameDestroy_ name doesn't make sense anymore because the reference point instruction we picked here is neither the last instruction in the frame nor the only instruction with the _FrameDestroy_ flag and, with new name, I tried to appropriately tag the particular instruction that the existing logic here was using as a reference point instruction to move around within the _MBB_ (we could choose a different reference point instruction and achieve the same result, of course, with all the relevant changes wherever needed in the existing logic).

If the new name doesn't make sense, please feel free to suggest one.

File: llvm/test/CodeGen/RISCV/debug-line.ll (hunk 2 above)
Comment (RamNalamothu) [reply llvm/test/CodeGen/RISCV/debug-line.ll:1]: I am running into different unrelated issues while trying to add a testcase with automated checks, with both LLVM IR and MIR.

And, even if I could achieve that, the assembly is going to be big due to the presence of debug info which I think is not desirable. Probably that's the reason there are no existing codegen tests, e.g. in AArch64 and RISC-V, having debug info meta data along with automated checks.

Is resolving this comment a blocker for this patch?

File: llvm/lib/Target/RISCV/RISCVFrameLowering.cpp [hunk 5]
```diff
@@ -1088,7 +1092,8 @@ void RISCVFrameLowering::emitEpilogue(MachineFunction &MF,
...
+      std::next(MBBI, getRVVCalleeSavedInfo(MF, CSI).size());
```
[the remark this answers is not in the document]
Comment (RamNalamothu) [reply llvm/lib/Target/RISCV/RISCVFrameLowering.cpp:1096]: If we observe _RISCVFrameLowering::spillCalleeSavedRegisters_ and _RISCVFrameLowering::restoreCalleeSavedRegisters_, the frame layout is as follows:

```
spilling CSR regs:
               CM.PUSH/CSRSaveLibCall           ----- A
               ScalarCSRSaves                   ----- B
               VectorCSRSaves                   ----- C
restoring CSR regs:
               VectorCSRRestores                   ----- C
               ScalarCSRRestores                   ----- B
               CM.POP/CSRRestoreLibCall            ----- A

```
The _RISCVFrameLowering::emitPrologue_ and _RISCVFrameLowering::emitEpilogue_ need a reliable mechanism, because the CSR list is specific to each function and is not fixed, to identify beginning of **B** as per the below comment. The mechanism used is start at beginning (in emitPrologue) / ending (in emitEpilogue) of **MBB** and then try to find beginning of **B** using _FrameSetup/FrameDestroy_ flag and _getRVVCalleeSavedInfo(MF, CSI).size()_,                              _getUnmanagedCSI(MF, CSI).size()_.

   _// The frame pointer is callee-saved, and code has been generated for us to
  // save it to the stack. We need to skip over the storing of callee-saved
  // registers as the frame pointer must be modified after it has been saved
  // to the stack, not before_

Before my patch, we only generate _FrameSetup/FrameDestroy_ flag for **A** but now this patch generates those flags for all of **A**, **B** and **C** as that is needed to fix the _epilogue_begin_ identification. And this obviously requires adjusting the existing logic here which is trying to identify **B** based on _FrameSetup/FrameDestroy_ flags.

I just picked one way of doing it and if that's not the better one, I will give it a try to improve it.

Hope that gives more clarity and answers all the concerns raised.

**Review by lenary — APPROVED** [review]
LGTM. Thanks for the explanations

**Comment by RamNalamothu** [comment]
I will wait till end of the day for others who have commented and then merge, if I don't hear anything, so that the patch can go into the 20.x release branch.

**Comment by efriedma-quic** [comment]
FYI, it's not really helpful to wait from midnight US time until early morning US time; probably nobody saw your first message before you merged.  If you actually want to give people time to comment, please give at least 24 hours.  (In this case, I don't think you needed to wait anyway, so it's fine.)

**Comment by RamNalamothu** [comment]
> FYI, it's not really helpful to wait from midnight US time until early morning US time; probably nobody saw your first message before you merged. If you actually want to give people time to comment, please give at least 24 hours. (In this case, I don't think you needed to wait anyway, so it's fine.)

Thanks for the comments, @efriedma-quic. However, others who have commented on this patch, based on their comments' time, seems to be working in the closer time zone to mine and not in US time zone.

**Comment by RamNalamothu** [comment]
The PR https://github.com/llvm/llvm-project/pull/120623 is a RISC-V target specific LLVM backend patch and is not related to Aarch64 / or any header file. So, this failure is not due to my patch.
