### PR TITLE
[LoopVersioning] Add a check to see if the input loop is in LCSSA form

### LINKED ISSUE #36998: "Instruction does not dominate all uses" with opt -disable-basicaa -loop-versioning
|  |  |
| --- | --- |
| Bugzilla Link | [37650](https://llvm.org/bz37650) |
| Version | unspecified |
| OS | Linux |
| Attachments | [reproducer](https://user-images.githubusercontent.com/55733087/143757583-daba1cab-fdab-4d25-9ab1-724068c68938.gz) |

## Extended Description 

opt -S -o - bbi-14805.ll -disable-basicaa -loop-versioning

gives

Instruction does not dominate all uses!
  %inc = add nsw i16 undef, 1
  store i16 %inc, i16* @&#8203;c, align 1
LLVM ERROR: Broken function found, compilation aborted!

Found when running random passes/flags on random input. We don't normally use -disable-basicaa -loop-versioning.

This happens also with some old opt binary built in Nov 2016.

### PR DESCRIPTION
**Pull request by VedantParanjape**
Loop Optimizations expect the input loop to be in LCSSA form. But it seems that LoopVersioning doesn't have any check to see if the loop is actually in LCSSA form. As a result, if we give it a loop which is not in LCSSA form but still correct semantically, the resulting transformation fails to pass through verifier pass with the following error.

Instruction does not dominate all uses!
%inc = add nsw i16 undef, 1
store i16 %inc, ptr @c, align 1

As the loop is not in LCSSA form, LoopVersioning's transformations leads to invalid IR! As some instructions do not dominate all their uses.

This patch checks if a loop is in LCSSA form, if not it will call formLCSSARecursively on the loop before passing it to LoopVersioning.

Fixes: #36998

### CODE REVIEW

**Review by aeubanks — COMMENTED** [review]
I'm not familiar with the pass and will let @fhahn take a look, but does it need to be a function pass as opposed to a loop pass?

**Comment by VedantParanjape** [comment]
> I'm familiar with the pass and will let @fhahn take a look, but does it need to be a function pass as opposed to a loop pass?

do you mean to say not familiar?

I am not super familiar with this pass as well, but I think because it uses LoopAccessInfo and LoopInfo and they cannot be queried per Loop? so it's a function pass.

**Comment by aeubanks** [comment]
sorry yeah, "not familiar"

**Comment by VedantParanjape** [comment]
ping! @fhahn

**Comment by VedantParanjape** [comment]
ping !

**Review by aeubanks — APPROVED** [review]
seems reasonable

File: llvm/lib/Transforms/Utils/LoopVersioning.cpp [hunk 1]
```diff
@@ -278,6 +279,9 @@ bool runImpl(LoopInfo *LI, LoopAccessInfoManager &LAIs, DominatorTree *DT,
     if (!LAI.hasConvergentOp() &&
         (LAI.getNumRuntimePointerChecks() ||
          !LAI.getPSE().getPredicate().isAlwaysTrue())) {
+      if (!L->isLCSSAForm(*DT))
+        llvm::formLCSSARecursively(*L, *DT, LI, SE);
```
Comment (fhahn) [inline llvm/lib/Transforms/Utils/LoopVersioning.cpp:283]:
```suggestion
       formLCSSARecursively(*L, *DT, LI, SE);
```

File: llvm/test/Transforms/LoopVersioning/crash-36998.ll [hunk 2]
```diff
@@ -0,0 +1,57 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -passes=loop-versioning -aa-pipeline='' -S < %s | FileCheck %s
+target triple = "x86_64-unknown-linux-gnu"
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVersioning/crash-36998.ll:3]: Does this depend on the X86 triple? if so, it needs to be marked as requiring the X86 backend, otherwise the test will fail when the backend is not built

File: llvm/test/Transforms/LoopVersioning/crash-36998.ll [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+for.body:                                         ; preds = %for.body, %entry
+  %0 = load i16, ptr @a, align 1
+  store i16 %0, ptr @b, align 1
+  %inc = add nsw i16 undef, 1
+  br i1 false, label %for.body, label %for.cond.for.end_crit_edge
+
+for.cond.for.end_crit_edge:                       ; preds = %for.body
+  %split2 = phi i16 [ %inc, %for.body ]
+  store i16 %inc, ptr @c, align 1
+  ret void
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVersioning/crash-36998.ll:56]:
```suggestion
  %split2 = phi i16 [ %inc, %for.body ]
  ret i16 %split2
```
