### PR TITLE
[LoongArch] Custom lowering for vector logical right shifts of integers

### LINKED ISSUE #170976: [LoongArch] Assertion `(TLI.getTypeAction(*DAG.getContext(), Op.getValueType()) == TargetLowering::TypeLegal || Op.getOpcode() == ISD::TargetConstant || Op.getOpcode() == ISD::Register) && "Unexpected illegal type!"' failed.
Reproducer: https://godbolt.org/z/Px5q639q7
Testcase:
```llvm
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "loongarch64-unknown-linux-musl"

define <16 x i16> @func_1(<16 x i16> %shuffle) {
entry:
  %div = udiv <16 x i16> %shuffle, splat (i16 3)
  ret <16 x i16> %div
}
```

Dump:
```
llc: /root/llvm-project/llvm/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp:985: void {anonymous}::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*): Assertion `(TLI.getTypeAction(*DAG.getContext(), Op.getValueType()) == TargetLowering::TypeLegal || Op.getOpcode() == ISD::TargetConstant || Op.getOpcode() == ISD::Register) && "Unexpected illegal type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'LoongArch DAG->DAG Pattern Instruction Selection' on function '@func_1'
 #0 0x0000000004207428 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x4207428)
 #1 0x00000000042042d4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x00007e67dae42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007e67dae969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x00007e67dae42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x00007e67dae287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x00007e67dae2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x00007e67dae39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x0000000003e7a3f1 (anonymous namespace)::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*) (.part.0) LegalizeDAG.cpp:0:0
 #9 0x0000000003e7c7de llvm::SelectionDAG::Legalize() (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e7c7de)
#10 0x0000000003f9cb32 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f9cb32)
#11 0x0000000003f9fe88 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f9fe88)
#12 0x0000000003fa190c llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3fa190c)
#13 0x0000000003f8d10f llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3f8d10f)
#14 0x00000000030ef499 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#15 0x00000000037408e6 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x37408e6)
#16 0x0000000003740c91 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3740c91)
#17 0x00000000037414ff llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x37414ff)
#18 0x00000000008fd1f4 compileModule(char**, llvm::LLVMContext&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) llc.cpp:0:0
#19 0x00000000007c73d9 main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x7c73d9)
#20 0x00007e67dae29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#21 0x00007e67dae29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#22 0x00000000008f23f5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x8f23f5)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by heiher**
After PR #169491, the DAG combiner can still recreate vector UDIV in an illegal type even after type legalization, which is the root cause of issue #170976.

The optimization introduced in PR #169491 is still desirable, so this patch adds custom lowering for vector integer logical right shifts to prevent the DAG from producing nodes with illegal types.

Fixes #170976

### CODE REVIEW

File: llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp [hunk 1]
```diff
@@ -338,7 +338,7 @@ LoongArchTargetLowering::LoongArchTargetLowering(const TargetMachine &TM,
       setOperationAction({ISD::MUL, ISD::SDIV, ISD::SREM, ISD::UDIV, ISD::UREM},
                          VT, Legal);
       setOperationAction({ISD::AND, ISD::OR, ISD::XOR}, VT, Legal);
-      setOperationAction({ISD::SHL, ISD::SRA, ISD::SRL}, VT, Legal);
+      setOperationAction({ISD::SHL, ISD::SRA, ISD::SRL}, VT, Custom);
```
Comment (zhaoqi5) [inline llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp]: Seems that `udiv` combination after https://github.com/llvm/llvm-project/pull/169491 will only generate `srl`? I am not sure if it is necessary to set `custom` for `shl` and `sra`.

... Anyway, it does not matter.

**Comment by heiher** [comment]
> Should it also be addressed in this commit?

All done. Thanks!

File: llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp [hunk 2]
```diff
@@ -618,10 +620,55 @@ SDValue LoongArchTargetLowering::LowerOperation(SDValue Op,
...
+  if (Op.getOpcode() == ISD::SRL) {
+    if (getVShiftAmt(Op.getOperand(1), EltSize, Amt) && Amt >= 0 &&
+        Amt < EltSize)
+      return DAG.getNode(LoongArchISD::VSRLI, DL, VT, Op.getOperand(0),
+                         DAG.getConstant(Amt, DL, GRLenVT));
+    return DAG.getNode(LoongArchISD::VSRL, DL, VT, Op.getOperand(0),
+                       Op.getOperand(1));
+  }
+
+  llvm_unreachable("unexpected shift opcode");
```
Comment (SixWeining) [inline llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp]:
```suggestion
  assert (Op.getOpcode() == ISD::SRL && "unexpected shift opcode");
  if (getVShiftAmt(Op.getOperand(1), EltSize, Amt) && Amt >= 0 &&
      Amt < EltSize)
    return DAG.getNode(LoongArchISD::VSRLI, DL, VT, Op.getOperand(0),
                       DAG.getConstant(Amt, DL, GRLenVT));
  return DAG.getNode(LoongArchISD::VSRL, DL, VT, Op.getOperand(0),
                     Op.getOperand(1));
```

**Review by SixWeining — APPROVED** [review]
LGTM

**Review by zhaoqi5 — APPROVED** [review]
