### PR TITLE
[flang] fix early free of allocatable function result in WHERE mask

### LINKED ISSUE #168561: [flang] invalid code for where
I've encountered an issue with Flang 21.1.5 which generates invalid code for `where`. I could reproduce something similar with the following snippet. It should print the sequence of numbers from 1 to 33 but it prints `33 33 33 33 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33`. Note that I've disabled use of the random number generator because it always gives `2.2470951E-05`.

The same behavior is seen on [compiler explorer](https://godbolt.org/z/9Mnqfzf7s) which uses Flang trunk (commit cce852ff03be5da56a9dc3d102a142812b2008d1)

```fortran
program test

  implicit none
  integer, dimension(:), allocatable :: v
  real :: r
  integer :: i

  call random_number(r) ! does not work

  print*, 'r',r
  r = 0.32
  allocate(v(1+int(r*100.0)),source=0)

  print*, 'size(v)',size(v)

  do i = 1, size(v)
    where(x(size(v),i)) v=i
  end do

  print*, v
  contains

  function x(n,i)
    integer, intent(in) :: n,i
    logical, dimension(:), allocatable :: x

    allocate(x(n),source=.false.)
    x(i) = .true.

  end function x

end program test
```

Note: Also reported on [LLVM Discourse](https://discourse.llvm.org/t/invalid-code-for-where/88881)

### PR DESCRIPTION
**Pull request by jeanPerier**
Fix https://github.com/llvm/llvm-project/issues/168561.

The issue was that the allocatable function result used as WHERE mask was freed too early.

This happened because lowering was moving the result via as_expr but was still inserting the deallocation directly on the storage instead of passing that responsibility to the moved value (hlfir.expr). Later, the pass optimizing WHERE is extending the expr lifetime usage passed the deallocation of the storage because it (rightfully) assumes it can extent lifetime of hlfir.expr as long as it moves the related destroy.

Fix lowering to pass the storage ownership to the expression after the call instead.

### CODE REVIEW

**Review by clementval — APPROVED** [review]
LGTM

File: flang/lib/Lower/ConvertCall.cpp [hunk 1]
```diff
@@ -1973,17 +1983,25 @@ genUserCall(Fortran::lower::PreparedActualArguments &loweredActuals,
...
     if (resultEntity.isVariable()) {
       // If the result has no finalization, it can be moved into an expression.
-      // In such case, the expression should not be freed after its use since
-      // the result is stack allocated or deallocation (for allocatable results)
-      // was already inserted in genCallOpAndResult.
-      auto asExpr =
-          hlfir::AsExprOp::create(builder, loc, resultEntity,
-                                  /*mustFree=*/builder.createBool(loc, false));
-      return hlfir::EntityWithAttributes{asExpr.getResult()};
+      // In such case, the expression.
```
Comment (vzakhari) [inline flang/lib/Lower/ConvertCall.cpp]: Comment is cut short.

**Review by vzakhari — APPROVED** [review]
Thank you, Jean! Just one minor comment.

**Review by eugeneepshteyn — APPROVED** [review]
LGTM, with one super minor note
