### PR TITLE
[flang][OpenMP] Fix copyprivate semantic checks

### LINKED ISSUE #87214: [Flang][OpenMP] Compilation error when end single construct has a copyprivate clause
```
Version of flang-new : 19.0.0(cbcdf126ccc774c063b5d5140c1393ff5305dded)/AArch64
```

Compilation error occurs when `end single` construct has a `copyprivate`  clause.

Compilation terminates normally in the following cases:
- Delete the `COPYPRIVATE` clause, or                    (omp30_example_a_37_01_222.f90)
- Add the following before the assignments A and B, or   (omp30_example_a_37_01_223.f90)
```
  !$OMP THREADPRIVATE(A,B)
```
- Add `PARALLEL` construct                               (omp30_example_a_37_01_224.f90)

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

omp30_example_a_37_01_22.f90:
```fortran
program main
  REAL A, B
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE COPYPRIVATE (A,B)
  print *,'pass'
end program main
```

```
$ flang-new -fopenmp omp30_example_a_37_01_22.f90
error: Semantic errors in omp30_example_a_37_01_22.f90
./omp30_example_a_37_01_22.f90:7:31: error: COPYPRIVATE variable 'a' is not PRIVATE or THREADPRIVATE in outer context
  !$OMP END SINGLE COPYPRIVATE (A,B)
                                ^
./omp30_example_a_37_01_22.f90:7:33: error: COPYPRIVATE variable 'b' is not PRIVATE or THREADPRIVATE in outer context
  !$OMP END SINGLE COPYPRIVATE (A,B)
                                  ^
$
```

```
$ export OMP_NUM_THREADS=1; gfortran -fopenmp omp30_example_a_37_01_22.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=1; ifort -qopenmp -diag-disable=10448 omp30_example_a_37_01_22.f90; ./a.out
 pass
$
```

omp30_example_a_37_01_222.f90:
```fortran
program main
  REAL A, B
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE  ! COPYPRIVATE(A,B)
  print *,'pass'
end program main
```

omp30_example_a_37_01_223.f90:
```fortran
program main
  REAL A, B
!$OMP THREADPRIVATE(A,B)
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE COPYPRIVATE(A,B)
  print *,'pass'
end program main
```

omp30_example_a_37_01_224.f90:
```fortran
program main
  REAL A, B
!$OMP PARALLEL
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE  COPYPRIVATE(A,B)
!$OMP END PARALLEL
  print *,'pass'
end program main
```

### PR DESCRIPTION
**Pull request by luporl**
There are some cases in which variables used in OpenMP constructs
are predetermined as private. The semantic checks for copyprivate
were not handling those cases.

Besides that, shared symbols were not being properly represented
in some cases. When there was no previously declared private
(implicit) symbol, no new association symbols, representing
shared ones, were being created.

These symbols must always be inserted in constructs that may
privatize the original symbol: parallel, teams and task
generating constructs.

Fixes #87214 and #86907

### CODE REVIEW

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -2540,6 +2541,32 @@ void ResolveOmpTopLevelParts(
...
+  // common block.
+  for (const auto &cb : symbol.owner().commonBlocks()) {
+    if (IsCommonBlockContaining(cb.second.get(), symbol)) {
+      return true;
+    }
+  }
+  return false;
+}
+
+static bool IsSymbolPredeterminedAsPrivate(const Symbol &symbol) {
```
Comment (tblah) [inline flang/lib/Semantics/resolve-directives.cpp:2557]: What about loop indices?

Comment (luporl) [reply flang/lib/Semantics/resolve-directives.cpp:2557]: Loop indices are handled by other parts of the OmpAttributeVisitor, that should run before this check and set the OmpPrivate flag in the corresponding symbols. However, I'm seeing some strange behaviors with the copyprivate check in some cases. I'll investigate it further and add some more tests.

**Comment by luporl** [comment]
The copyprivate checks should behave correctly now, in all cases that I'm aware of.
Some symbols that represent variables with shared DSA were missing too. These were added, which required the update of some tests. I also did a slight code refactoring.

**Review by tblah — COMMENTED** [review]
LGTM, but please wait for review from somebody else.

**Comment by luporl** [comment]
Thanks for the review @tblah.

Ping for other reviews.

**Comment by NimishMishra** [comment]
> Ping for other reviews.

Sorry for the delay. I'll a look and revert, latest by tomorrow.

File: flang/lib/Semantics/resolve-directives.cpp [hunk 2]
```diff
@@ -2540,20 +2554,58 @@ void ResolveOmpTopLevelParts(
   });
 }
 
-void OmpAttributeVisitor::CheckDataCopyingClause(
-    const parser::Name &name, const Symbol &symbol, Symbol::Flag ompFlag) {
-  const auto *checkSymbol{&symbol};
+static bool IsSymbolInCommonBlock(const Symbol &symbol) {
+  // If there are many symbols in common blocks, going through them all can be
```
Comment (NimishMishra) [inline flang/lib/Semantics/resolve-directives.cpp:2558]: Would you like this to be a TODO, instead of a comment, depending on how impactful we expect this to be?

**Review by NimishMishra — APPROVED** [review]
Thanks for the patch. LGTM overall

File: flang/lib/Semantics/resolve-directives.cpp (hunk 2 above)
Comment (luporl) [reply flang/lib/Semantics/resolve-directives.cpp]: Thanks for the review!

Comment changed to a TODO.

For now I don't expect the current implementation of `IsSymbolInCommonBlock` to have a big impact on performance, since it's used only when checking symbols in `copyprivate` clauses. But on programs with an unusually high number of symbols in common blocks and `copyprivate` clauses, or if this predicate function starts to be used within other checks, then it could be a problem.

**Comment by psteinfeld** [comment]
@luporl, after this change, I'm seeing errors in our internal test suites.  Here's a program that produces similar errors:
```
[pete@rome3 install]$cat bug.f90
program bug
  use omp_lib
  implicit none
  integer i1,i2,i3,m
  type derived
    integer field(2,3)
  end type
  type(derived) y(5)
  integer,parameter :: nt = 2
  integer field(nt)
  field = 0
  m = 1
  !$OMP PARALLEL DO NUM_THREADS(nt) PRIVATE(m) DEFAULT(NONE) SHARED(y,field) &
  !$OMP COLLAPSE(2) SCHEDULE(STATIC)
  do i1=1,size(y,1)
    do i3=1,3
      do i2=1,2
        y(i1)%field(i2,i3) = 1
        !$omp atomic
        field(m) = field(m) + 1 !error here
      end do
    end do
  end do
  !$OMP END PARALLEL DO
end program

flang-new -fopenmp -fopenmp-version=31 bug.f90 
error: Semantic errors in bug.f90
./bug.f90:20:9: error: Reference to rank-2 object 'field' has 1 subscripts
          field(m) = field(m) + 1 !error here
          ^^^^^^^^
./bug.f90:20:20: error: Reference to rank-2 object 'field' has 1 subscripts
          field(m) = field(m) + 1 !error here
                     ^^^^^^^^
```

Before you merged this change, this program compiled cleanly.  Can you please either revert or fix this?

**Comment by luporl** [comment]
@psteinfeld Reverted. I'll need some time to investigate this error.

**Comment by tblah** [comment]
A minimised test of ours which failed too (posting in addition in case it helps the investigation):

```
program omp_associate_min
  integer, parameter :: l = 42
  integer :: a(l)
  integer :: i
  a = 1

  !$omp parallel do
  do i = 1,l
    associate (b=>a)
      b(i) = b(i) * 2
    end associate
  enddo
  !$omp end parallel do
end program
```

Thanks for the quick revert and cherry-pick to the release branch.

**Comment by luporl** [comment]
Thanks for the feedback @psteinfeld and @tblah.
The regressions should be fixed in https://github.com/llvm/llvm-project/pull/101009.
Please check if it fixes your tests.
