### PR TITLE
[clang] Don't lose track of explicit specializations of member functi…

### LINKED ISSUE #111266: [clang] crashes and misbehavior with member function template explicit specialization
Clang crashes compiling the following valid example: https://godbolt.org/z/Kx916caT7
```C++
template<class T> struct S {
  template<int> auto foo();
  template<> auto foo<1>() {
    return [](auto x) { return x; };
  }
};
template struct S<void>;
```

What happens is that when instantiating the members of S<int>, we lose track of the specialization kind of `foo<1>`, leading to us using the explicit specialization argument when instantiating the function definition.

The behavior for explicit instantiation doesn't match MSVC and EDG as well: https://godbolt.org/z/ejehb88zc
```C++
template<class T> struct A {
  int x;
  template<class U = void> static void f();
  template<> void f<int>() { (void)this->x; }
};
template struct A<int>;
```
Here clang eagerly instantiates `f<int>` and complains about usage of `this` in static function, while MSVC / EDG only do so when the definition is actually used.

### PR DESCRIPTION
**Pull request by mizvekov**
…on templates

When instantiating a class template, we would lose track of function template explicit specializations, marking them with the wrong specialization kind.

This would lead to improperly using the explcit specialization arguments to instantiate the function body.

This also better matches MSVC on the behaviour of explicitly vs implicitly instantiating these.

Fixes #111266

### CODE REVIEW

File: clang/test/SemaTemplate/ms-function-specialization-class-scope.cpp [hunk 1]
```diff
@@ -156,7 +156,13 @@ namespace UsesThis {
...
   };
 
-  template struct A<int>; // expected-note 3{{in instantiation of}}
+  template struct A<int>; // expected-note {{in instantiation of}}
+  template<> template<> void A<int>::f<int>();
+  template<> template<> void A<int>::g<int>();
+  void test1() {
+    A<int>().f<int>(); // expected-note {{in instantiation of}}
+    A<int>().g<int>(); // expected-note {{in instantiation of}}
+  }
```
Comment (zyn0217) [inline clang/test/SemaTemplate/ms-function-specialization-class-scope.cpp:165]: There weren't test failures here, right?
(Changes here are hopefully not hiding the failures)

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 2]
```diff
@@ -4206,18 +4206,14 @@ Sema::InstantiateClassMembers(SourceLocation PointOfInstantiation,
...
 
-        MemberSpecializationInfo *MSInfo =
-            Function->getMemberSpecializationInfo();
-        assert(MSInfo && "No member specialization information?");
-        if (MSInfo->getTemplateSpecializationKind()
-                                                 == TSK_ExplicitSpecialization)
+        TemplateSpecializationKind PrevTSK =
+            Function->getTemplateSpecializationKind();
+        if (PrevTSK == TSK_ExplicitSpecialization)
           continue;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:4212]: IIUC the new behavior handles `DependentFunctionTemplateSpecializationInfo` as well, right?

**Review by zyn0217 — APPROVED** [review]
Makes sense to me, but I'd like to @erichkeane to have a look as well.

File: clang/test/SemaTemplate/ms-function-specialization-class-scope.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/test/SemaTemplate/ms-function-specialization-class-scope.cpp:165]: No, we are still producing the same bunch of diagnostics, except now only when we use the function, instead of when instantiating the enclosing class.
This matches the behavior of MSVC.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:4212]: I don't think that would matter, unless the assert above was wrong, as the `DependentFunctionTemplateSpecializationInfo` case is handled in the fallback path, when `MSInfo` is null.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:4212]: Yeah, I thought the bug was that somewhere we failed to handle `DependentFunctionTemplateSpecializationInfo`s, but after stepping into the codes, I realized that it is due to the latest TSK stored in `FunctionTemplateSpecializationInfo` rather than in the MSInfo. (We didn't update the TSK in MSInfo in CheckFunctionTemplateSpecialization)

**Review by erichkeane — APPROVED** [review]
