### PR TITLE
[lldb] Improving synchronization of MainLoopWindows.

### LINKED ISSUE #147291: [lldb] Something wrong with new MainLoopWindows for pipe support
The PR #145621 added the new class PipeEvent and the test NoSpuriousPipeReads.
This test is flaky:

https://lab.llvm.org/buildbot/#/builders/211/builds/231
https://lab.llvm.org/buildbot/#/builders/211/builds/274
https://lab.llvm.org/buildbot/#/builders/211/builds/284

https://lab.llvm.org/buildbot/#/builders/197/builds/6659
https://lab.llvm.org/buildbot/#/builders/197/builds/6690
https://lab.llvm.org/buildbot/#/builders/197/builds/6701
https://lab.llvm.org/buildbot/#/builders/197/builds/6735
https://lab.llvm.org/buildbot/#/builders/197/builds/6737

It causes problems with production buildbots and must be fixed ASAP.
I'm not sure disabling this test is a good solution.

### PR DESCRIPTION
**Pull request by ashgti**
This should improve synchronizing the MainLoopWindows monitor thread with the main loop state.

This uses the `m_ready` and `m_event` event handles to manage when the Monitor thread continues and adds new tests to cover additional use cases.

I believe this should fix #147291 but it is hard to ensure a race condition is fixed without running the CI on multiple machines/configurations.

### CODE REVIEW

File: lldb/source/Host/windows/MainLoopWindows.cpp [hunk 1]
```diff
@@ -110,6 +117,7 @@ class PipeEvent : public MainLoopWindows::IOEvent {
         continue;
       }
 
+      ResetEvent(m_ready);
       SetEvent(m_event);
```
Comment (labath) [inline lldb/source/Host/windows/MainLoopWindows.cpp]: I think there's still a race here where if `WillPoll` runs between these two calls, it will observe both of them as unset, and trigger another iteration of the loop, even though we haven't consumed the previous event.  That next iteration could race with the consumption of that event.

I *think* that reversing the order is enough to avoid this.

```suggestion
      // Notify that data is available on the pipe. It's important to set this before clearing m_ready to avoid a race with WillPoll.
      SetEvent(m_event);
      // Stop polling until we're told to resume.
      ResetEvent(m_ready);
```

File: lldb/source/Host/windows/MainLoopWindows.cpp [hunk 2]
```diff
@@ -65,15 +66,21 @@ class PipeEvent : public MainLoopWindows::IOEvent {
   }
 
   void WillPoll() override {
-    if (!m_monitor_thread.joinable())
-      m_monitor_thread = std::thread(&PipeEvent::Monitor, this);
+    // If the m_event is signaled, wait until it is consumed before telling the
+    // monitor thread to continue.
+    if (WaitForSingleObject(m_event, /*dwMilliseconds=*/0) == WAIT_TIMEOUT &&
+        WaitForSingleObject(m_ready, /*dwMilliseconds=*/0) == WAIT_TIMEOUT)
+      SetEvent(m_ready);
```
Comment (labath) [inline lldb/source/Host/windows/MainLoopWindows.cpp]: This is equivalent. I'm just adding some comments to explain why it is correct.
```suggestion
    if (WaitForSingleObject(m_event, /*dwMilliseconds=*/0) != WAIT_TIMEOUT) {
      // The thread has already signalled that the data is available. No need for further polling until we consume that event.
      return;
    }
    if (WaitForSingleObject(m_ready, /*dwMilliseconds=*/0) != WAIT_TIMEOUT) {
      // The thread is already waiting for data to become available.
      return;
    }
    // Start waiting.
    SetEvent(m_ready);
```

**Review by labath — APPROVED** [review]
Thanks. I like how this means we no longer create the thread lazily.

I think I see one more race, see inline comment. LGTM assuming you agree with my analysis.

**Review by slydiman — APPROVED** [review]
LGTM. 
But I agree that
> it is hard to ensure a race condition is fixed without running the CI on multiple machines/configurations.

**Comment by ashgti** [comment]
I kicked off a build on lldb-x86_64-win, once that passes I'll submit and we can see if there are any failures in the CI jobs.

**Comment by ashgti** [comment]
Hmm I think I didn't specify the commit correctly for the CI job.

I'll merge this and we can revert it if needed later.

**Comment by slydiman** [comment]
So far everything looks good. Thanks.
