### PR TITLE
[CUDA/HIP] Do not ignore complete destructors in abstract classes

### LINKED ISSUE #184856: Use of host function 'deallocate' in a host/device function error in c++20 code built for AMD GPU
We have an error building a Kokkos-based app for AMD MI300A GPUs. We've reduced the code to a few lines while still getting the same error message. The following code produces an error when using the AMD gfx942 target.

```c++
#include <string> 
class LabeledObject 
{ std::string label; public: LabeledObject(); virtual ~LabeledObject(); } 
; 
class Describable : virtual public LabeledObject 
{ public: virtual ~Describable(); virtual std::string describe() = 0; } 
; 
template <class Scalar> 
class ScalarProdBase : virtual public Describable 
{ 
public: 
std::string describe() 
{ return "foo"; } 
protected: 
virtual bool bar() = 0; 
}; 
template class ScalarProdBase<double>;
```

I'm using the following command to build:

`clang++ --std=c++20 -xhip -o repro.o -c repro.cpp --offload-arch=gfx942`

Notably, the error does not happen when using --std=c++17, but the code need c++20 for other parts.

This is the error output I see:

```
In file included from <built-in>:1:
In file included from /llvm-dir/lib/clang/23/include/__clang_hip_runtime_wrapper.h:151:
In file included from /llvm-dir/lib/clang/23/include/cuda_wrappers/complex:35:
In file included from /opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/stdexcept:39:
In file included from /opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/string:43:
/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/allocator.h:210:25: error: 
      reference to __host__ function 'deallocate' in __host__ __device__
      function
  210 |         __allocator_base<_Tp>::deallocate(__p, __n);
      |
```

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
The complete destructor destroys virtual base subobjects even for
abstract classes, so target inference must consider vbases when
analyzing destructors.

This was motivated by behavior observed from a bug where a constexpr
function that calls a non-constexpr function. I believe this error is
secondary, but can be fixed by this observation. The issue was the
switch to C++20 allowing allocator destructors to be constexpr began
opting the function into `__host__ __device__` contexts. This function
then called a non-constexpr function through a type-trait interface
which lead to that only having `__host__` which is illegal.

The fix offered here is to check the bases of this function and
correctly derive that it is `__host__` and not `__host__ __device__` as
was previously inferred. This should only affect cases where the *only*
member is an inherited virtual destructor. Previously we found no bases
and thus made no judgement.

Fixes: https://github.com/llvm/llvm-project/issues/184856

### CODE REVIEW

File: clang/lib/Sema/SemaCUDA.cpp [hunk 1]
```diff
@@ -496,17 +496,18 @@ bool SemaCUDA::inferTargetForImplicitSpecialMember(CXXRecordDecl *ClassDecl,
...
+  // regardless of whether the class is abstract.
   llvm::SmallVector<const CXXBaseSpecifier *, 16> Bases;
   for (const auto &B : ClassDecl->bases()) {
     if (!B.isVirtual()) {
       Bases.push_back(&B);
     }
   }
 
-  if (!ClassDecl->isAbstract()) {
+  if (!ClassDecl->isAbstract() || CSM == CXXSpecialMemberKind::Destructor)
```
Comment (Artem-B) [inline clang/lib/Sema/SemaCUDA.cpp]: I wonder what was the reason we're not appending abstract classes to the base list?

If we do append some of them now, then:
- will it trigger the problem the check was intended to guard against.
- if adding abstract classes is safe, should we add all of them, instead of only those that are "connected" via a destructor?

It looks like this base tracking logic is very old: https://github.com/llvm/llvm-project/commit/9a220fca4a6f01f1d3363b3cb53f4f2fa77851c4 

A few lines above we skip considering virtual bases, too, which seems relevant to the problem at hand. Not ignoring a virtual base would probably avoid the diagnostics, too.
https://github.com/llvm/llvm-project/blob/e87d34255382d8a8dc8dba13dbbeec3f0f634839/clang/lib/Sema/SemaCUDA.cpp#L501-L505

I'm reluctant to add a special case just for the destructor of an abstract virtual base. It's a suspiciously specific exception for the code where we are ignoring *kinds* of base classes. 

For me this could be justified, provided that:
-  we can prove that it's the only such corner case (maybe? I didn't manage to find other ways to trigger the misdiagnostics so far), and
- including previously excluded abstract virtual base class has no unintended consequences. This is hard to prove. We'll need to test it.

@yxsamliu WDYT?

Comment (jhuber6) [reply clang/lib/Sema/SemaCUDA.cpp]: As far as I can tell, we shouldn't be ignoring abstract destructors as they have different semantics to the other special functions. The destructor of a class needs to destroy a virtual bases even if the class is abstract. This seems to indirectly fix the issue.

Basically
1: member function with abstract destructor -> no bases -> implicit host/device
2: C++20 made destructors constexpr capable -> stdlib is constexpr -> calls host function on fallback.

This change makes us instantiate a base on the abstract destructor, so it's now `__host__` which avoids the problem. That's my understanding.

Comment (Artem-B) [reply clang/lib/Sema/SemaCUDA.cpp]: > This change makes us instantiate a base on the abstract destructor

Will instantiating that base, and everything it needs, do something we would not have done otherwise? E.g. run into a failure to instantiate something that we would not try to instantiate before?

Comment (jhuber6) [reply clang/lib/Sema/SemaCUDA.cpp]: This would just trigger the same behavior that we already have for virtual bases of non-abstract methods and non-virtual bases of abstract classes AFAIK. I can't think of any cases but this is really the first time I've had to read this handling.

**Review by Artem-B — APPROVED** [review]
LGTM, but please wait a bit to check if @yxsamliu has any input.

**Review by yxsamliu — APPROVED** [review]
LGTM. Thanks
