### PR TITLE
[flang][OpenMP] Skip invalid conditional compilation sentinels

### LINKED ISSUE #89560: [Flang][OpenMP] Compilation error of Fixed Source Form Conditional Compilation Sentinels
```
Version of flang-new : 19.0.0(4f19f15a601a5761b12c9c66d99d97dbc89ef90d)/AArch64
```

The third line of the following program does not meet the criteria of the following standard,
so this line should remain unchanged and be considered a comment line.
- OpenMP 5.2 / 3.3.1 Fixed Source Form Conditional Compilation Sentinels

However, this line results in a compilation error.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

sngg075g_2.f:
```fortran
      program main
      k01=-1
c$ x
      print *,'pass'
      end

```

```
$ flang-new -fopenmp sngg075g_2.f
error: Could not parse sngg075g_2.f
./sngg075g_2.f:4:1: warning: Character in fixed-form label field must be a digit
        print *,'pass'
  ^
./sngg075g_2.f:3:5: error: expected '=>'
  c$ x
      ^
./sngg075g_2.f:3:4: in the context: pointer assignment statement
  c$ x
     ^
./sngg075g_2.f:3:3: in the context: execution part construct
  c$ x
    ^
./sngg075g_2.f:2:7: in the context: execution part
        k01=-1
        ^
./sngg075g_2.f:1:7: in the context: main program
        program main
        ^
./sngg075g_2.f:3:5: error: expected '('
  c$ x
      ^
./sngg075g_2.f:3:4: in the context: pointer assignment statement
  c$ x
     ^
./sngg075g_2.f:3:3: in the context: execution part construct
  c$ x
    ^
./sngg075g_2.f:2:7: in the context: execution part
        k01=-1
        ^
./sngg075g_2.f:1:7: in the context: main program
        program main
        ^
./sngg075g_2.f:3:5: error: expected '='
  c$ x
      ^
./sngg075g_2.f:3:4: in the context: assignment statement
  c$ x
     ^
./sngg075g_2.f:3:3: in the context: execution part construct
  c$ x
    ^
./sngg075g_2.f:2:7: in the context: execution part
        k01=-1
        ^
./sngg075g_2.f:1:7: in the context: main program
        program main
        ^
./sngg075g_2.f:3:5: error: expected ':'
  c$ x
      ^
./sngg075g_2.f:3:4: in the context: nonlabel DO statement
  c$ x
     ^
./sngg075g_2.f:3:3: in the context: DO construct
  c$ x
    ^
./sngg075g_2.f:3:3: in the context: execution part construct
  c$ x
    ^
./sngg075g_2.f:2:7: in the context: execution part
        k01=-1
        ^
./sngg075g_2.f:1:7: in the context: main program
        program main
        ^
$
```

```
$ gfortran -fopenmp sngg075g_2.f; ./a.out
 pass
$
```

```
$ ifort -qopenmp -diag-disable=10448 sngg075g_2.f; ./a.out
 pass
$
```

### PR DESCRIPTION
**Pull request by luporl**
In fixed form, an initial line can have an OpenMP conditional
compilation sentinel only if columns 3 through 5 have only
white space or numbers.

Fixes https://github.com/llvm/llvm-project/issues/89560

### CODE REVIEW

File: flang/lib/Parser/prescan.cpp [hunk 1]
```diff
@@ -1432,6 +1432,21 @@ Prescanner::IsFixedFormCompilerDirectiveLine(const char *start) const {
     }
     *sp++ = ToLowerCaseLetter(*p);
   }
+  // A fixed form OpenMP conditional compilation sentinel must satisfy the
+  // following criteria, for initial lines:
+  // - Columns 3 through 5 must have only white space or numbers.
+  // - Column 6 must be space or zero.
+  if (column == 3 && sentinel[0] == '$') {
```
Comment (kiranchandramohan) [inline flang/lib/Parser/prescan.cpp:1439]: Is something like `c$1x` handled?
Should we check if it is column 3, 4, 5 as well?

**Review by kiranchandramohan — COMMENTED** [review]
Thanks for the patch. A. couple of questions.

File: flang/lib/Parser/prescan.cpp [hunk 2]
```diff
@@ -1432,6 +1432,21 @@ Prescanner::IsFixedFormCompilerDirectiveLine(const char *start) const {
...
+    const char *q{p};
+    for (int col{3}; col < 6; ++col, ++q) {
+      if (!IsSpaceOrTab(q) && !IsDecimalDigit(*q)) {
+        return std::nullopt;
+      }
+    }
+    if (*q != ' ' && *q != '0') {
+      return std::nullopt;
+    }
```
[the remark this answers is not in the document]
Comment (luporl) [reply flang/lib/Parser/prescan.cpp:1448]: I'm not sure. The spec says it must be a space or zero in column 6 and white space and numbers in columns 1 through 5:

> After the sentinel is replaced with two spaces, initial lines must have a space or zero in column 6 and only white space and numbers in columns 1 through 5;
(OpenMP 5.2 3.3.1)

My interpretation is that space is only `' '` while white space includes tab too.

File: flang/lib/Parser/prescan.cpp (hunk 1 above)
Comment (luporl) [reply flang/lib/Parser/prescan.cpp:1439]: Yes, `c$` is not considered a sentinel in `c$1x`.

If the loop above found a conditional compilation sentinel, it will always break on column 3, when it finds either a white space or digit.

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Comment by luporl** [comment]
Thanks for the review @kiranchandramohan.
