### PR TITLE
[Clang] Improve Sema diagnostic performance for __builtin_counted_by_ref

### LINKED ISSUE #115520: compile time regression introduced by Sema checking for __builtin_counted_by_ref
As reported by @nikic 
https://github.com/llvm/llvm-project/pull/114495#issuecomment-2464318302

This is likely because the checks are currently implemented to walk through the whole child nodes for every single assignments. We may be able to remove the overhead by rolling up the information about usage of `counted_by` or `__builtin_counted_by_ref` to the assignment, instead of re-visiting child nodes.

### PR DESCRIPTION
**Pull request by bwendling**
Implement the sema checks with a placeholder. We then check for that placeholder in all of the places we care to emit a diagnostic.

Fixes: #115520

### CODE REVIEW

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -755,6 +755,7 @@ static ExprResult BuiltinDumpStruct(Sema &S, CallExpr *TheCall) {
     case BuiltinType::PseudoObject:
     case BuiltinType::UnknownAny:
     case BuiltinType::BuiltinFn:
+    case BuiltinType::BuiltinCountedByRef:
```
Comment (Sirraide) [inline clang/lib/Sema/SemaChecking.cpp:758]:
```suggestion
```
`__builtin_counted_by_ref` isn’t a valid argument for `__builtin_dump_struct`, so this should fall under the default case below.

File: clang/lib/Sema/SemaDecl.cpp [hunk 2]
```diff
@@ -14690,6 +14690,17 @@ void Sema::FinalizeDeclaration(Decl *ThisDecl) {
...
+  // The result of __builtin_counted_by_ref cannot be assigned to a variable.
+  // It allows leaking and modification of bounds safety information.
+  if (const auto *CE = dyn_cast_if_present<CallExpr>(VD->getInit())) {
+    const Expr *E = CE->getCallee()->IgnoreParenImpCasts();
+    if (const BuiltinType *PTy = E->getType()->getAsPlaceholderType();
+        PTy && PTy->getKind() == BuiltinType::BuiltinCountedByRef)
+      Diag(E->getExprLoc(),
+           diag::err_builtin_counted_by_ref_cannot_leak_reference)
+          << E->getSourceRange();
+  }
```
Comment (Sirraide) [inline clang/lib/Sema/SemaDecl.cpp:14702]:
```suggestion
  if (const BuiltinType *PTy = E->getType()->getAsPlaceholderType();
      PTy && PTy->getKind() == BuiltinType::BuiltinCountedByRef) {
    Diag(E->getExprLoc(),
         diag::err_builtin_counted_by_ref_cannot_leak_reference)
        << E->getSourceRange();
  }
```
I think we should just check for the placeholder type instead of for a call expression here. 

Also, even though I’m someone who generally prefers not to use braces around the body of an `if` when possible, I think a 5-line `if` statement w/o braces is beyond the limits of what I’d consider to be legible. ;Þ

One more thing, I feel like `AddInitializerToDecl` might be a better place to put this (maybe right before the `if (VDecl->getType()->isUndeducedType())` part?).

File: clang/lib/Sema/SemaExpr.cpp [hunk 3]
```diff
@@ -3382,7 +3382,9 @@ ExprResult Sema::BuildDeclarationNameExpr(
   case Decl::Function: {
     if (unsigned BID = cast<FunctionDecl>(VD)->getBuiltinID()) {
       if (!Context.BuiltinInfo.isDirectlyAddressable(BID)) {
-        type = Context.BuiltinFnTy;
+        type = (BID == Builtin::BI__builtin_counted_by_ref)
+                   ? Context.BuiltinCountedByRefTy
+                   : Context.BuiltinFnTy;
```
Comment (Sirraide) [inline clang/lib/Sema/SemaExpr.cpp:3387]: I feel like we should keep this as-is and only set the type to `BuiltinCountedByRefTy` when we build the call expression. Any use of a builtin outside a call expression is already rejected by existing code, so you don’t have to worry about that if you do it that way.

File: clang/lib/Sema/SemaExpr.cpp [hunk 4]
```diff
@@ -4894,6 +4896,18 @@ ExprResult Sema::ActOnArraySubscriptExpr(Scope *S, Expr *base,
...
+  Expr *E = base->IgnoreParenImpCasts();
+  if (auto *CE = dyn_cast<CallExpr>(E)) {
+    E = CE->getCallee()->IgnoreParenImpCasts();
+    if (const BuiltinType *PTy = E->getType()->getAsPlaceholderType();
+        PTy && PTy->getKind() == BuiltinType::BuiltinCountedByRef) {
+      Diag(E->getExprLoc(), diag::err_builtin_counted_by_ref_invalid_use)
+          << 0 << E->getSourceRange();
+    }
+  }
+
```
Comment (Sirraide) [inline clang/lib/Sema/SemaExpr.cpp:4910]: I don’t think this any of this should have to be here? `ActOnArraySubscriptExpr` already calls `CheckPlaceholderExpr`

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/Sema/SemaDecl.cpp:14702]: Also, I find it a bit weird that we never check for placeholders here—weird but possible, that is, because initialisers are generally also a bit weird... can you try removing this check entirely?

File: clang/lib/Sema/SemaExpr.cpp [hunk 5]
```diff
@@ -6770,7 +6802,9 @@ ExprResult Sema::BuildResolvedCallExpr(Expr *Fn, NamedDecl *NDecl,
   ExprResult Result;
   QualType ResultTy;
   if (BuiltinID &&
-      Fn->getType()->isSpecificBuiltinType(BuiltinType::BuiltinFn)) {
+      (Fn->getType()->isSpecificBuiltinType(BuiltinType::BuiltinFn) ||
+       Fn->getType()->isSpecificBuiltinType(
+           BuiltinType::BuiltinCountedByRef))) {
```
Comment (Sirraide) [inline clang/lib/Sema/SemaExpr.cpp:6807]: Should no longer be necessary if we revert `__builtin_counted_by_ref` on its own to still have `BuiltinFn` type.

**Review by Sirraide — CHANGES_REQUESTED** [review]
Hmm, I don’t think this is the right way of going about it—copy-pasting the check across 6 or so different places seems like it’s missing the point of using a placeholder in the first place.

Maybe I didn’t describe this accurately enough, but the idea was that the *call* to the builtin, not the builtin itself, should get placeholder type. Then, you need to update `CheckPlaceholderExpr` *only* (and maybe the initialisation code if it’s required there; I don’t remember if that ever checks for placeholders off the top of my head because initialisers are weird, but I hope it does), and then update any places where you want to *allow* this as a subexpression to check for an expression w/ that placeholder type (and change the placeholder type to be whatever the actual type of the expression is supposed to be) before it calls `CheckPlaceholderExpr`/`CheckArgsForPlaceholders`.

... that said, that was my (and I *think* Aaron’s) idea—if you’ve discovered a reason why that doesn’t work, then please let us know so we can think of a way around that. ;Þ

**Comment by bwendling** [comment]
> Hmm, I don’t think this is the right way of going about it—copy-pasting the check across 6 or so different places seems like it’s missing the point of using a placeholder in the first place.

Could you point to a place in the code where it creates a placeholder? I'm unable to find any others that what I modified in SemaExpr.cpp. Many of the uses you mentioned would be invalid to perform on other `__builtin` functions didn't produce an error when I tried them out (except for using the `AddrOf` operator).

> Maybe I didn’t describe this accurately enough, but the idea was that the _call_ to the builtin, not the builtin itself, should get placeholder type. Then, you need to update `CheckPlaceholderExpr` _only_ (and maybe the initialisation code if it’s required there; I don’t remember if that ever checks for placeholders off the top of my head because initialisers are weird, but I hope it does), and then update any places where you want to _allow_ this as a subexpression to check for an expression w/ that placeholder type (and change the placeholder type to be whatever the actual type of the expression is supposed to be) before it calls `CheckPlaceholderExpr`/`CheckArgsForPlaceholders`.

Given that I did this by checking the `CallExpr`, perhaps we should just abandon using the placeholder scheme and go with what I have here, but without the placeholder stuff.

File: clang/lib/Sema/SemaChecking.cpp (hunk 1 above)
Comment (bwendling) [reply clang/lib/Sema/SemaChecking.cpp:758]: Then shouldn't *all* builtin functions be marked as "invalid?"

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (bwendling) [reply clang/lib/Sema/SemaDecl.cpp:14702]: If I remove the check then it won't trigger an error. Initialization and assignment are two completely different paths.

**Comment by bwendling** [comment]
I removed the Placeholder code. It's a much smaller patch and has the better timing profile. PTAL.

**Review by Sirraide — COMMENTED** [review]
The main thing I’m concerned about here is that I feel like there ought to be a better way of doing this than checking for and disallowing it in every place where we can have a subexpression in C.

CC @AaronBallman for opinions on this.

Also, if we’re doing it this way, then the check should definitely be factored out into a function in `Sema`.

**Comment by Sirraide** [comment]
> Could you point to a place in the code where it creates a placeholder?

I mean, e.g. `CheckPointerToMemberOperands()` can return `BoundMemberTy` as the type of a `.*` expression, and `CreateBuiltinMatrixSubscriptExpr()` creates a `MatrixSubscriptExpr` with type `IncompleteMatrixIdxTy` if that’s what you’re asking.

**Comment by bwendling** [comment]
> The main thing I’m concerned about here is that I feel like there ought to be a better way of doing this than checking for and disallowing it in every place where we can have a subexpression in C.

Yeah, but we don't have such a method, partially due to the languages Clang supports. How is this any different from the vast array of other features that are checked in Sema?

> Also, if we’re doing it this way, then the check should definitely be factored out into a function in `Sema`.

Okay.

**Comment by bwendling** [comment]
> > Could you point to a place in the code where it creates a placeholder?
> 
> I mean, e.g. `CheckPointerToMemberOperands()` can return `BoundMemberTy` as the type of a `.*` expression, and `CreateBuiltinMatrixSubscriptExpr()` creates a `MatrixSubscriptExpr` with type `IncompleteMatrixIdxTy` if that’s what you’re asking.

`CheckPointerToMemberOperands` only returns the placeholder type. The matrix one isn't a `CallExpr`, so it doesn't help me much. Anyway, this is irrelevant now as I'm going another way.

**Review by Sirraide — COMMENTED** [review]
I think this might honestly be fine the way it is now, but I’d like for e.g. @AaronBallman to take a look at this too before approving it since he’s more familiar w/ C than me.

File: clang/lib/Sema/SemaDecl.cpp [hunk 6]
```diff
@@ -14690,6 +14690,14 @@ void Sema::FinalizeDeclaration(Decl *ThisDecl) {
     }
   }
 
+  // The result of __builtin_counted_by_ref cannot be assigned to a variable.
+  // It allows leaking and modification of bounds safety information.
+  if (const auto *CE = dyn_cast_if_present<CallExpr>(VD->getInit());
+      CE && CE->getBuiltinCallee() == Builtin::BI__builtin_counted_by_ref)
```
Comment (tbaederr) [inline clang/lib/Sema/SemaDecl.cpp:14696]: Can you not use `IsBuiltinCountedByRef()` here?

Comment (bwendling) [reply clang/lib/Sema/SemaDecl.cpp]: Done.

**Comment by bwendling** [comment]
> I think this might honestly be fine the way it is now

Yeah. It's going kind of the opposite way from what you suggested with the placeholder, just instead of allowing for different uses at various places in Sema we disallow without using the placeholder.

**Comment by bwendling** [comment]
I image @AaronBallman is on vacation this week. @Sirraide would you be willing to LGTM this so that I can move it along? It's certainly better than what we have and I can address any concerns Aaron has afterwards.

**Comment by Sirraide** [comment]
> I image @AaronBallman is on vacation this week. @Sirraide would you be willing to LGTM this so that I can move it along?

I mean, this is stricly a performance issue, so I’m not sure why we’d want to merge it this urgently...

**Comment by bwendling** [comment]
Yeah, but I'd like to get this off my plate. :-)

**Review by Sirraide — APPROVED** [review]
The changes seem fine to me now; not sure we’re handling this in all places where it needs to be handled though. I’d say maybe wait a day or two before merging in case anyone else wants to comment on that.

**Comment by Endilll** [comment]
For the record, Aaron is not on vacation. So if you need his sign-off, you should wait.

**Comment by bwendling** [comment]
Ah, okay. Thanks.

File: clang/lib/Sema/SemaDecl.cpp [hunk 7]
```diff
@@ -14690,6 +14690,13 @@ void Sema::FinalizeDeclaration(Decl *ThisDecl) {
     }
   }
 
+  // The result of __builtin_counted_by_ref cannot be assigned to a variable.
+  // It allows leaking and modification of bounds safety information.
+  if (IsBuiltinCountedByRef(VD->getInit()))
+    Diag(VD->getInit()->getExprLoc(),
+         diag::err_builtin_counted_by_ref_cannot_leak_reference)
+        << VD->getInit()->getSourceRange();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDecl.cpp:14698]: Should we split this off into a helper function like `bool CheckInvalidBuiltinCountedByRef(const Expr *E);` ?

**Review by AaronBallman — COMMENTED** [review]
Is there a branch up for this on https://llvm-compile-time-tracker.com/ so that we've verified that this actually improves performance?

File: clang/lib/Sema/SemaDecl.cpp (hunk 7 above)
Comment (Sirraide) [reply clang/lib/Sema/SemaDecl.cpp:14698]: I was going to comment on that too, but ended up forgetting about it; it’s used in like 3–4 places, so I personally would prefer making this a helper function.

**Comment by nikic** [comment]
> Is there a branch up for this on https://llvm-compile-time-tracker.com/ so that we've verified that this actually improves performance?

Compile-time: https://llvm-compile-time-tracker.com/compare.php?from=105b7803ea22823a2fca2a82ee843d0884e9cbf3&to=dcb3e2b6b4333556fbfa3d7a5a45c145972b466f&stat=instructions:u Yes, this does recover the regression.

File: clang/lib/Sema/SemaDecl.cpp (hunk 7 above)
Comment (bwendling) [reply clang/lib/Sema/SemaDecl.cpp:14698]: I'm not sure I agree. The diagnostic isn't the same in all places. And one of them takes arguments not available from the `Expr`. I would say that if we were adding several more diagnostics then a separate function would make sense. But for four, it's probably a bit more trouble than it's worth.

**Review by AaronBallman — APPROVED** [review]
LGTM modulo the request for a helper function (that two reviewers asked for the same thing is a pretty reasonable indication that we should probably have the helper, but if you feel strongly about it, I won't block the PR over it).

**Comment by bwendling** [comment]
Fine.
