### PR TITLE
[clangd] Fix RawStringLiteral being available to C and C++ versions prior to C++11

### LINKED ISSUE #1795: RawStringLiteral code action is available for pure C code
It seems that implementation of RawStringLiteral (`clang-tools-extra/clangd/refactor/tweaks/RawStringLiteral.cpp`) doesn't check for the source language. As a result, `Convert to raw string` code action is available for pure C code, which doesn't have raw strings.

I've put together a very simple test to demonstrate this behaviour: https://github.com/vnfedotov/ls-interact/blob/master/test_clangd_code_actions.py

**Logs**

[log_verbose.txt](https://github.com/clangd/clangd/files/13025805/log_verbose.txt)

**System information**

Output of `clangd --version`: 17.0.3

Editor/LSP plugin: https://github.com/simark/ls-interact

Operating system: MacOS Ventura 13.4.1

### PR DESCRIPTION
**Pull request by robozati**
The `RawStringLiteral` code action runs both on C and C++ versions prior to C++11, where this feature is unavailable.

This patch adds a condition to check if the context is running a version equal or greater than C++11 and adds tests for failing in the wrong versions.

Fixes https://github.com/clangd/clangd/issues/1795.

### CODE REVIEW

**Comment by robozati** [comment]
Tests are randomly failing, let me get what is wrong.

**Comment by robozati** [comment]
@sam-mccall @kadircet Hello! I mentioned this PR in discord, but no one assigned themselves to review so I am pinging you.

File: clang-tools-extra/clangd/refactor/tweaks/RawStringLiteral.cpp [hunk 1]
```diff
@@ -76,7 +82,7 @@ bool RawStringLiteral::prepare(const Selection &Inputs) {
   if (!N)
     return false;
   Str = dyn_cast_or_null<StringLiteral>(N->ASTNode.get<Stmt>());
-  return Str &&
+  return Str && isFeatureAvailable(Inputs) &&
```
Comment (HighCommander4) [inline clang-tools-extra/clangd/refactor/tweaks/RawStringLiteral.cpp:85]: I would move this language mode check to the very top of `prepare()` (e.g. there is no point doing the work of `commonAncestor()` if this check fails).

**Comment by vit9696** [comment]
Confirmed working as it should. Thank you.

**Review by HighCommander4 — APPROVED** [review]
LGTM, thanks!
