### PR TITLE
[MLIR] Fix VectorEmulateNarrowType constant op mask bug

### LINKED ISSUE #115742: Bug in the VectorEmulateNarrowType logic
**Reproducer** 

```mlir
func.func @vector_maskedload_i4_constant_mask(%passthru: vector<8xi4>) -> vector<8xi4> {
  %0 = memref.alloc() : memref<3x8xi4>
  %cst = arith.constant dense<0> : vector<8xi4>
  %mask = arith.constant dense<[false, true, true, true, true, false, false, false]> : vector<8xi1>
  %c0 = arith.constant 0 : index
  %1 = vector.maskedload %0[%c0, %c0], %mask, %passthru :
    memref<3x8xi4>, vector<8xi1>, vector<8xi4> into vector<8xi4>
  return %1 : vector<8xi4>
}
```

**To run**
```bash
mlir-opt --test-emulate-narrow-int="arith-compute-bitwidth=1 memref-load-bitwidth=8" --cse --split-input-file
```

**Error**

ATM, this example will trigger an infinite loop due to this [while cond](url) not supporting `arith.constant`. Once that's fixed, I get this error:

```bash
file.mlir:1 offset :8:8: error: failed to legalize operation 'vector.maskedload' that was explicitly marked illegal
  %1 = vector.maskedload %0[%c0, %c0], %mask, %passthru :
       ^
```

CC @lialan

### PR DESCRIPTION
**Pull request by lialan**
This commit adds support for handling mask constants generated by the `arith.constant` op in the `VectorEmulateNarrowType` pattern. Previously, this pattern would not match due to the lack of mask constant handling in `getCompressedMaskOp`.

The changes include:

1. Updating `getCompressedMaskOp` to recognize and handle `arith.constant` ops as mask value sources.

2. Handling cases where the mask is not aligned with the emulated load width. The compressed mask is adjusted to account for the offset.

Limitations:
- The arith.constant op can only have 1-dimensional constant values.

Resolves: #115742

### CODE REVIEW

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 1]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
       auto denseAttr = DenseElementsAttr::get(newMaskType, newMaskValues);
       newMask = rewriter.create<arith::ConstantOp>(loc, newMaskType, denseAttr);
     }
+  } else if (constantOp) {
+    assert(shape.size() == 1 && "expected 1-D mask");
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:136]: Why do we have the assertion in this branch, but not others?

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 2]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+    // Rearrange the original mask values to cover the whole potential loading
+    // region. For example, in the case of using byte-size for emulation, given
+    // the following mask:
+    //
+    //   %mask = vector.constant_mask [0, 1, 0, 1, 0, 0] : vector<6xi2>
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:141]: I'm confused about `vector.constant_mask` here. The comment looks off to me because of the definition of the vector.constant_mask op: https://github.com/llvm/llvm-project/blob/00f2989f98520c401f0ab544a3dc766ed83785c0/mlir/include/mlir/Dialect/Vector/IR/VectorOps.td#L2347-L2383

Do you mean `arith.constant`? Also, should the type be i1? To simplify the comment, we can omit the op name and types, which looks cleaner to me. The idea of having the comment is to help people understand the logic. IMO, we don't need the concrete ops at this scope. So it could be something like `%mask = [1, 1, 0, 0, 0, 0]` (and it is how we document in the above function comment).

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 3]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+    // back so that its length is multiple of `scale` (and the total coverage
+    // size is mulitiple of bytes):
+    //   %new_mask = vector.constant_mask [0, 0, 1, 0, 1, 0, 0, 0] :
+    //   vector<8xi2>
+    //
+    // The %new_mask is now aligned with the effective loading area and can now
+    // be compressed.
+    SmallVector<bool> maskValues(intraDataOffset, false);
+    if (auto denseAttr =
+            mlir::dyn_cast<DenseIntElementsAttr>(constantOp.getValue())) {
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:153]: nit: drop `mlir::`
style nit: prefer using early-exit to simplify the code, so it can be something like:

```cpp
auto denseAttr = dyn_cast...
if (!denseAttr)
  return failure();
// The rest code in the if branch..
``` 

https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 4]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+      for (auto value : denseAttr.getValues<bool>()) {
+        maskValues.push_back(value);
+      }
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:156]: I'm not sure if it works or not -- can we use the append method, like `maskValues.append(denseAttr.getValues<bool>())`?

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 5]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+      while (maskValues.size() < numElements * scale) {
+        maskValues.push_back(false);
+      }
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:159]: I think the size of maskValues should always be less than or equal to `numElements * scale`? If so, perhaps we can have an assertion and write `maskValues.resize(numElements * scale, false)`.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir [hunk 6]
```diff
@@ -624,3 +624,28 @@ func.func @vector_maskedstore_i4_constant_mask(
...
+  %cst = arith.constant dense<0> : vector<8xi4>
+  %mask = arith.constant dense<[false, true, true, true, true, false, false, false]> : vector<8xi1>
+  %c0 = arith.constant 0 : index
+  %1 = vector.maskedload %0[%c0, %c0], %mask, %passthru :
+    memref<3x8xi4>, vector<8xi1>, vector<8xi4> into vector<8xi4>
+  return %1 : vector<8xi4>
+}
+
+// CHECK: func @vector_maskedload_i4_arith_constant(
+// CHECK-SAME:   %[[PASSTHRU:[a-zA-Z0-9]+]]: vector<8xi4>) -> vector<8xi4> {
```
Comment (hanhanW) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir:641]: You don't need to capture the types (and the rest of function) because we have regular expression in the matching (i.e., [a-zA-Z0-9]+`). The trick allow us to omit the type when we don't care about it in the lit test.

```suggestion
// CHECK-SAME:   %[[PASSTHRU:[a-zA-Z0-9]+]]
```

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 7]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+    } else {
+      return failure();
+    }
+    // Compressing by combining every `scale` elements:
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:163]: I'd suggest to have a blank line right before this comment. Because it is clearer that the code is not part of the above big chunk of comment. The above comment does not explain any compression. IMO, we should either expand the comment or just make a clear line between the codes. The latter one looks okay to me because this is what the method aims to do (and it's already documented in function comments).

**Review by hanhanW — COMMENTED** [review]
Overall looks good to me, just some nits about style/comments/tests.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 2 above)
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:141]: This should be
```mlir
    //   %mask = vector.constant_mask [0, 1, 0, 1, 0, 0] : vector<6xi1>
```
right? (`i1` instead of `i2`).

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 8]
```diff
@@ -129,6 +132,45 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+    // region. For example, in the case of using byte-size for emulation, given
+    // the following mask:
+    //
+    //   %mask = vector.constant_mask [0, 1, 0, 1, 0, 0] : vector<6xi2>
+    //
+    // with front offset of 1, the mask will be padded zeros in the front and
+    // back so that its length is multiple of `scale` (and the total coverage
+    // size is mulitiple of bytes):
+    //   %new_mask = vector.constant_mask [0, 0, 1, 0, 1, 0, 0, 0] :
+    //   vector<8xi2>
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:147]: This should be `vector<8xi1` rather than `vector<8xi2>`, right? Also, don't we need two `i8` elements to load 6 x `i2`?

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir [hunk 9]
```diff
@@ -624,3 +624,28 @@ func.func @vector_maskedstore_i4_constant_mask(
...
+// CHECK: %[[ALLOC:.+]] = memref.alloc() : memref<12xi8>
+// CHECK: %[[MASK:.+]] = arith.constant dense<[false, true, true, true, true, false, false, false]> : vector<8xi1>
+// CHECK: %[[MASK2:.+]] = arith.constant dense<[true, true, true, false]> : vector<4xi1>
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir:644]:
```suggestion
// CHECK: %[[MASK_COMPRESSED:.+]] = arith.constant dense<[true, true, true, false]> : vector<4xi1>
```
?

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir [hunk 10]
```diff
@@ -624,3 +624,28 @@ func.func @vector_maskedstore_i4_constant_mask(
...
+// CHECK: %[[BITCAST:.+]] = vector.bitcast %[[PASSTHRU]] : vector<8xi4> to vector<4xi8>
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir:645]:
```suggestion
// CHECK: %[[PTHRU_UPCAST:.+]] = vector.bitcast %[[PASSTHRU]] : vector<8xi4> to vector<4xi8>
```
?

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir [hunk 11]
```diff
@@ -624,3 +624,28 @@ func.func @vector_maskedstore_i4_constant_mask(
...
+// CHECK: %[[C0:.+]] = arith.constant 0 : index
+// CHECK: %[[LOAD:.+]] = vector.maskedload %[[ALLOC]][%[[C0]]], %[[MASK2]], %[[BITCAST]]
+// CHECK-SAME : memref<12xi8>, vector<4xi1>, vector<4xi8> into vector<4xi8>
+// CHECK: %[[BITCAST2:.+]] = vector.bitcast %[[LOAD]] : vector<4xi8> to vector<8xi4>
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir:649]:
```suggestion
// CHECK: %[[LOAD_DOWNCAST:.+]] = vector.bitcast %[[LOAD]] : vector<4xi8> to vector<8xi4>
```

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir [hunk 12]
```diff
@@ -249,3 +249,41 @@ func.func @vector_maskedload_i2_dynamic_indexing_mixed(%passthru: vector<3xi2>,
 // CHECK: %[[IN8:.+]] = vector.insert %[[EX8]], %[[IN7]] [1] : i2 into vector<3xi2>
 // CHECK: %[[EX9:.+]] = vector.extract %[[SELECT]][%[[INCIDX2]]] : i2 from vector<8xi2>
 // CHECK: %[[IN9:.+]] = vector.insert %[[EX9]], %[[IN8]] [2] : i2 into vector<3xi2>
+
+// -----
+
+func.func @vector_maskedload_i4_constant_mask_unaligned(%passthru: vector<5xi2>) -> vector<5xi2> {
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:255]: How is this actually different to `@vector_maskedload_i4_arith_constant` from the other file?

**Review by banach-space — COMMENTED** [review]
Thanks for the fix!

I think that the logic in `getCompressedMaskOp` could benefit from a high level refactor. In particular, why not replace:
```cpp
f (createMaskOp) {
} else if (constantMaskOp) {
} else if (constantOp) {
}
```

with (pseudo syntax):
```cpp
TypeSwitch<Operation *op>(maskOp).
Case<CreateMaskOp>[&](){}
Case<ConstantMaskOp>[&](){}
Case<ConstantOp>[&](){}
```

and then every case should be implemented in a dedicated hook.

More comments inline.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 1 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:136]: @hanhanW Because it other branch it can handle multiple dimensional masks.

But should we simply only deal with 1d vectors in this pass?

Comment (hanhanW) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:136]: In this case, we can `return failure()` and add a TODO comment saying that it is not yet implemented. We should not crash in debug build and I believe the patterns can recover the state for this case.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir (hunk 12 above)
Comment (lialan) [reply mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:255]: Oh it is different in that the `numFrontPadElems` in the calculation is non zero in this case, so we check the affine map generation is correct.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 13]
```diff
@@ -75,83 +77,137 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
                                                   int numSrcElemsPerDest,
                                                   int numFrontPadElems = 0) {
 
-  assert(numFrontPadElems < numSrcElemsPerDest && "intraDataOffset must be less than scale");
+  assert(numFrontPadElems < numSrcElemsPerDest &&
+         "intraDataOffset must be less than scale");
```
Comment (dcaballe) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:81]: %s/intraDataOffset/numFrontPadElem/

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 14]
```diff
@@ -75,83 +77,137 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+                if (numFrontPadElems != 0 && maskDimSizes.size() > 1)
+                  return std::nullopt;
+
+                SmallVector<int64_t> newMaskDimSizes(maskDimSizes.drop_back());
+                newMaskDimSizes.push_back(maskIndex);
+
+                if (numFrontPadElems == 0) {
+                  return rewriter.create<vector::ConstantMaskOp>(
+                      loc, newMaskType, newMaskDimSizes);
+                } else {
```
Comment (dcaballe) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:149]: nit: no else after return

**Review by dcaballe — COMMENTED** [review]
Doing a first pass for now. Thanks!

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir (hunk 10 above)
Comment (lialan) [reply mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir]: Nice! I am bad at naming as you can see.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 5 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: Good suggestion!

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 3 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: ahh something I missed

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 4 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: we could, just that it does not take `range` type, but iterators works!

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 2 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: You are right, and I am embarrassed by missing this part while doing self proof reading. Thanks!

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: updated `shape` to `maskShape` to better represent the meaning.

Currently limiting it to only 1 d because the `arith.constant` op needs different treatment from the other two ops.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 2 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: yeah, my mistake, and I updated them.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 8 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: same as above.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir [hunk 15]
```diff
@@ -249,3 +249,41 @@ func.func @vector_maskedload_i2_dynamic_indexing_mixed(%passthru: vector<3xi2>,
...
+
+// CHECK: func @vector_maskedload_i4_constant_mask_unaligned(
+// CHECK-SAME: %[[PTH:.+]]: vector<5xi2>) -> vector<5xi2>
+// CHECK: %[[ALLOC:.+]] = memref.alloc() : memref<4xi8>
+// CHECK: %[[MASK:.+]] = arith.constant dense<[false, true, true, true, false]> : vector<5xi1>
+
+// CHECK: %[[CST0:.+]] = arith.constant dense<true> : vector<2xi1>
+// CHECK: %[[CST1:.+]] = arith.constant dense<0> : vector<8xi2>
+// CHECK: %[[INSERT:.+]] = vector.insert_strided_slice %[[PTH]], %[[CST1]]
+// CHECK-SAME: {offsets = [1], strides = [1]} : vector<5xi2> into vector<8xi2>
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:273]: Isn't `INSERT` basically a "padded" version of `PTH`? Where the pad value is 0? Would you mind using more descriptive names? For example:

* `INSERT` -> `PTH_PADDED`
* `BCAST` -> `PTH_PADDED_UPCAST`
* `MASKLOAD` -> `LOAD` (IMO, this can be short)
* `BCAST2` -> `LOAD_DOWNCAST`
* `INSERT2` -> `MASK_PADDED`
* `EXTRACT` -> `RESULT`

These are just suggestions, feel free to re-use or propose sth else. Either way, it would be nice to make this self-documenting, similarly to `vector_maskedload_i4_arith_constant`.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir [hunk 16]
```diff
@@ -249,3 +249,41 @@ func.func @vector_maskedload_i2_dynamic_indexing_mixed(%passthru: vector<3xi2>,
...
 // CHECK: %[[IN9:.+]] = vector.insert %[[EX9]], %[[IN8]] [2] : i2 into vector<3xi2>
+
+// -----
+
+func.func @vector_maskedload_i4_constant_mask_unaligned(%passthru: vector<5xi2>) -> vector<5xi2> {
+  %0 = memref.alloc() : memref<3x5xi2>
+  %mask = arith.constant dense<[false, true, true, true, false]> : vector<5xi1>
+  %c0 = arith.constant 0 : index
+  %c1 = arith.constant 1 : index
+  %1 = vector.maskedload %0[%c1, %c0], %mask, %passthru :
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:260]: IIUC, the key element of this example is the offset in the `vector.maskedload` operation? If that's the case, then it would be good to highlight the corresponding offset in the expected output. Either with a comment or clear LIT variable name. Also, using a higher value (e.g. "3", as a prime number, is nice) might be easier to illustrate what's happening here. "1" and "0" are super common and therefore it's hard to see them being propagated in tests.

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 17]
```diff
@@ -75,83 +77,134 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            //
+            // With front offset of 1, the mask will be padded 0s in the front
+            // and back so that:
+            // 1. It is aligned with the effective loading bits
+            // 2. Its length is multiple of `numSrcElemPerDest` (and the total
+            // coverage size is mulitiple of bytes). The new mask will be like
+            // this before compressing:
+            //
+            // %new_mask = [false, false, true, false, true, false, false,
+            // false]
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:175]: [nit]
```suggestion
            // %new_mask = 
            //   [false, false, true, false, true, false, false, false]
```

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 18]
```diff
@@ -75,83 +77,134 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            auto denseAttr =
+                dyn_cast<DenseIntElementsAttr>(constantOp.getValue());
+            if (!denseAttr)
+              return std::nullopt;
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:179]: Hm, is this case possible?

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 19]
```diff
@@ -75,83 +77,134 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            SmallVector<bool> maskValues(numFrontPadElems, false);
+            maskValues.append(denseAttr.template value_begin<bool>(),
+                              denseAttr.template value_end<bool>());
+            maskValues.resize(numElements * numSrcElemsPerDest, false);
+
+            // Compressing by combining every `numSrcElemsPerDest` elements:
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:185]:
```suggestion
            // Compressing by combining every block of `numSrcElemsPerDest` elements togehter:
```
?

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 20]
```diff
@@ -75,83 +77,134 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            // %new_mask = [false, false, true, false, true, false, false,
+            // false]
+            auto denseAttr =
+                dyn_cast<DenseIntElementsAttr>(constantOp.getValue());
+            if (!denseAttr)
+              return std::nullopt;
+            SmallVector<bool> maskValues(numFrontPadElems, false);
+            maskValues.append(denseAttr.template value_begin<bool>(),
+                              denseAttr.template value_end<bool>());
+            maskValues.resize(numElements * numSrcElemsPerDest, false);
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:183]: `numElements` -> `numDestElements`

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 21]
```diff
@@ -75,83 +77,134 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            //
+            // %new_mask = [false, false, true, false, true, false, false,
+            // false]
+            auto denseAttr =
+                dyn_cast<DenseIntElementsAttr>(constantOp.getValue());
+            if (!denseAttr)
+              return std::nullopt;
+            SmallVector<bool> maskValues(numFrontPadElems, false);
+            maskValues.append(denseAttr.template value_begin<bool>(),
+                              denseAttr.template value_end<bool>());
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:182]: What's this meant to do?

**Review by banach-space — COMMENTED** [review]
Thanks for the updates!

I only see tests for `maskedload` - how about `maskedstore`?

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 21 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:182]: it is inserting the original mask values to the vector to form a zero-padded in the front and back mask value vector, which is used to form the new compressed make vector.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir [hunk 22]
```diff
@@ -249,3 +249,41 @@ func.func @vector_maskedload_i2_dynamic_indexing_mixed(%passthru: vector<3xi2>,
...
+    memref<3x5xi2>, vector<5xi1>, vector<5xi2> into vector<5xi2>
+  return %1 : vector<5xi2>
+}
+
+// CHECK: func @vector_maskedload_i4_constant_mask_unaligned(
```
[the remark this answers is not in the document]
Comment (lialan) [reply mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:265]: Well, let me do that in another PR then!

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 18 above)
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:179]: ahh, I now use a `cast` to avoid such issue.

**Comment by lialan** [comment]
@banach-space Thanks for the review! I've updated according to your suggestions. I also added a masked store test case to illustrate the effect. Given that `maskedstore` does not support unaligned emulation yet (which is on my todo list), I only added 1 of it (the aligned case). 

I think what really helps is to use more meaningful names in the test, it is quite self-explanatory!

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: I honestly don't know if there is any > 1-d masks being generated, but `arith.constant` does allow arbitrary dimension constants being generated in this way. Is there any mechanism guarding it off from any such cases before this pass?

cc @hanhanW @dcaballe

[the remark this answers is not in the document]
Comment (hanhanW) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: I don't really know the answer.. My intuition is no in IREE project. My understanding is that all the n-D vector.transfer_read/write ops are unrolled to 1-D vector loads/stores on CPU path before we reach out to the emulation. GPU side, we don't use masking in IREE now.

However, I remember that @dcaballe added some n-D emulation support few months ago, so I'm not sure now.

I'd suggest to move this check before "TypeSwitch" and see what's happening. If it does not break anything, we don't need to make `arith.constant` case special. Otherwise, we leave it to where it is and add a TODO.

What do you think?

**Review by hanhanW — APPROVED** [review]
LGTM, just a couple comments about comments. I'll help land the PR once we get an approval from @banach-space

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir [hunk 23]
```diff
@@ -624,3 +648,29 @@ func.func @vector_maskedstore_i4_constant_mask(
...
+  vector.maskedstore %0[%c3, %c0], %mask, %val_to_store :
+      memref<5x8xi4>, vector<8xi1>, vector<8xi4>
+  return
+}
+
+// CHECK-LABEL: func @vector_maskedstore_i4_arith_constant
+// CHECK-SAME: %[[VAL_TO_STORE:[a-zA-Z0-9]+]]:
+// CHECK: %[[ALLOC:.+]] = memref.alloc() : memref<20xi8>
+// CHECK: %[[MASK:.+]] = arith.constant dense<[false, true, true, true, true, true, false, false]> : vector<8xi1>
+// CHECK: %[[C12:.+]] = arith.constant 12 : index
```
Comment (banach-space) [inline mlir/test/Dialect/Vector/vector-emulate-narrow-type.mlir:669]: [nit] 
```suggestion
// %c3 * 4 bits = 12
// CHECK: %[[IDX_FLATTENED:.+]] = arith.constant 12 : index
```

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: > I'd suggest to move this check before "TypeSwitch" and see what's happening. If it does not break anything, we don't need to make arith.constant case special. 

+1

No need to handle complexities that are not required. And if they do become required then at least we'll have a good motivating example to inform the design :)

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp [hunk 24]
```diff
@@ -75,83 +75,133 @@ static FailureOr<Operation *> getCompressedMaskOp(OpBuilder &rewriter,
...
+            // 1. It is aligned with the effective loading bits
+            // 2. Its length is multiple of `numSrcElemPerDest` (and the total
+            // coverage size is mulitiple of bytes). The new mask will be like
+            // this before compressing:
+            //
+            // %new_mask = [0, 0, 1, 0, 1, 0, 0, 0]
+            auto denseAttr = cast<DenseIntElementsAttr>(constantOp.getValue());
+            SmallVector<bool> paddedMaskValues(numFrontPadElems, false);
+            paddedMaskValues.append(denseAttr.template value_begin<bool>(),
+                                    denseAttr.template value_end<bool>());
```
Comment (banach-space) [inline mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp:178]: Oh, now I see why I got confused 😅 `denseAttr` - > `originalMask` 🙏🏻 (I thought that `denseAttr` was referring to some abstract type)

**Comment by banach-space** [comment]
> I think what really helps is to use more meaningful names in the test, it is quite self-explanatory!

Thank you for this comment and for updating the tests 🙏🏻. This makes reviewing and maintenance so much easier - our future selves will be very grateful! 😊

I’ve left a few small suggestions, but otherwise, this looks good to me (LGTM).

--- 
Given the growing complexity of this logic, I have a couple of high-level observations:

1. Should _"vector-emulate-narrow-type.mlir"_ be renamed to _"vector-emulate-narrow-type-aligned.mlir"_? Should the cases in _"vector-emulate-narrow-type-unaligned.mlir"_ essentially be variations of the cases in _"vector-emulate-narrow-type-aligned.mlir"_?

2. All the existing cases in "vector-emulate-narrow-type-unaligned.mlir" test `i2`, while the new cases test `i4`. In a PR like this, where the key "novelty" is support for `arith.constant` (i.e. a new Op), I’d normally expect the data types to remain consistent with the other tests. This way, it’s easier to isolate and understand the differences introduced by the new changes.

I’m not suggesting any additional large changes or refactors in this PR - @lialan has already done a great job! But I think the patterns/trends highlighted above emerge naturally and could serve as a helpful guiding principle for future PRs. If others agree, of course. 😊

**Review by banach-space — APPROVED** [review]
LGTM % some final nits

File: mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (lialan) [reply mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp]: Turns out it breaks things as some masks indeed created by other kinds of ops do have multiple dimensions. I am leaving it as is with a TODO for now. I will come back later.

File: mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir (hunk 12 above)
[the remark this answers is not in the document]
Comment (lialan) [reply mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir:255]: @hanhanW copy/paste mis match, I should have double checked it. I will update it later in a batch refactoring.
