### PR TITLE
[Clang] prevent incorrect rejection of auto with reordered declaration specifiers in C23

### LINKED ISSUE #164121: Auto is incorrectly rejected in C23 when it occurs after the type specifiers in a declaration
The following program demonstrates the issue:
```c
int main(){
    auto long long d1;
    long auto long d2;
    long long auto d3;
}
```
The order of declaration specifiers in a declaration shouldn't matter, so all 3 declarations should be accepted. However, Clang specifically rejects the third declaration of `d3` and only in C23 mode. GCC and Clang in a pre-C23 mode will accept this code.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #164121

---

This patch addresses the issue where `auto` was incorrectly rejected with reordered declaration specifiers in C23.

### CODE REVIEW

**Review by cor3ntin — COMMENTED** [review]
I am not sure this is the right approach.

- There are many more qualifiers (`_Atomic` for example, but look at `isTypeSpecifierQualifier` for more of the complexity)

I would like @AaronBallman to help us clarify the C23 rules. In particular as @Fznamznon mention, it is odd that `long auto long` would be allowed, although GCC accepts it. Is that a defect?

The tests should probably check if the behavior is consistent with static/extern

File: clang/test/Parser/c2x-auto.c [hunk 1]
```diff
@@ -137,23 +137,74 @@ constexpr auto int a1 = 0; // c23-error {{illegal storage class on file-scoped v
                               c17-error {{illegal storage class on file-scoped variable}} \
                               c17-error {{unknown type name 'constexpr'}}
 
-constexpr int auto a2 = 0; // c23-error {{cannot combine with previous 'int' declaration specifier}} \
+constexpr int auto a2 = 0; // c23-error {{cannot combine with previous 'auto' declaration specifier}} \
```
Comment (AaronBallman) [inline clang/test/Parser/c2x-auto.c]: The "cannot combine" diagnostic here is harder to understand because there's no "previous" auto specifier.

File: clang/lib/Parse/ParseDecl.cpp [hunk 2]
```diff
@@ -4093,7 +4093,30 @@ void Parser::ParseDeclarationSpecifiers(
...
+          unsigned I = 1;
+          while (true) {
+            const Token &T = GetLookAheadToken(I);
+            if (isKnownToBeTypeSpecifier(T))
+              return true;
+
+            if (T.isOneOf(tok::kw_typeof, tok::kw_typeof_unqual,
+                          tok::kw__Atomic) &&
+                GetLookAheadToken(I + 1).is(tok::l_paren))
+              return true;
```
Comment (AaronBallman) [inline clang/lib/Parse/ParseDecl.cpp]: What happens with code like:
```
void func() {
  signed int _Atomic auto i = 12; // Accept due to valid but useless storage class specifier
}
signed int _Atomic auto j = 12; // Reject due to invalid storage class specifier
```

**Review by AaronBallman — COMMENTED** [review]
Based on the diagnostic behavior, I'm not certain this is quite right still. I think the previous diagnostic behavior was generally better in a number of places. WDYT?

File: clang/lib/Parse/ParseDecl.cpp [hunk 3]
```diff
@@ -4093,7 +4093,26 @@ void Parser::ParseDeclarationSpecifiers(
       break;
     case tok::kw_auto:
       if (getLangOpts().CPlusPlus11 || getLangOpts().C23) {
-        if (isKnownToBeTypeSpecifier(GetLookAheadToken(1))) {
+        auto MayBeTypeSpecifier = [&]() {
+          if (getLangOpts().C23 && DS.hasTypeSpecifier() &&
+              DS.getTypeSpecType() != DeclSpec::TST_auto &&
+              DS.getConstexprSpecifier() == ConstexprSpecKind::Unspecified)
```
Comment (AaronBallman) [inline clang/lib/Parse/ParseDecl.cpp]: Can you help me understand why we need to check for `constexpr` explicitly?

**Review by AaronBallman — COMMENTED** [review]
The test behavior now looks correct to me, though I had some questions

File: clang/lib/Parse/ParseDecl.cpp [hunk 4]
```diff
@@ -4093,7 +4093,26 @@ void Parser::ParseDeclarationSpecifiers(
...
+            return true;
+
+          unsigned I = 1;
+          while (true) {
```
[the remark this answers is not in the document]
Comment (a-tarasyuk) [reply clang/lib/Parse/ParseDecl.cpp]: @AaronBallman, when you have a moment, could you please take a look at the latest changes?

**Review by AaronBallman — APPROVED** [review]
LGTM modulo a comment request (no need for additional review unless you'd like it)

**Review by Fznamznon — APPROVED** [review]
Sorry, for delay. I don't have any concerns anymore.
