### PR TITLE
[SDAG] Add freeze when simplifying select with undef arms

### LINKED ISSUE #175018: [clang] Miscompilation at -O1 with std::optional return value comparison
**Description:** Function that returns `std::nullopt` based on a range check is miscompiled with clang-21 at `-O1` and above, causing the function to incorrectly return a value instead of `std::nullopt`

**Reproducer:**
```c++
#include <iostream>
#include <cstring>
#include <optional>
#include <array>
#include <stdint.h>

using s64 = int64_t;
using u8 = uint8_t;

constexpr static s64 convert(s64 in) {
    return in / 10000;
}

std::optional<std::array<u8, 6>> __attribute__((noinline)) f(s64 x) {
    if (x < 0) {
        return std::nullopt;
    }

    if (x % 10000 != 0) {
       return std::nullopt;
    }

    auto y = convert(x);
    if (y > 0xFFFFFFFFFFFF) {
        return std::nullopt;
    }

    std::array<u8, 6> z{};
    std::memcpy(z.data(), &y, 6);
    return z;
}

int main() {
    auto res = f((0xFFFFFFFFFFFF + 1) * 10000);
    std::cerr << &res << " " << res.has_value() << std::endl;
}
```

`res.has_value()` returns `1` even though the input value should fail the `y > 0xFFFFFFFFFFFF` check.
```
$ clang++-21 -Wall -Wextra -std=c++20 -O1 -g3 test.cpp -o test21 && ./test21
0x7fffa7869d10 1
``` 

**Environment:**
- Ubuntu 22.04.5 LTS, x86_64
- Ubuntu clang version 21.1.0 (++20250811123346+6f5c887e557f-1~exp1~20250811123522.21)
- fetched from http://apt.llvm.org/jammy/
- Also reproduces on clang-20 (20.1.8); works correctly on clang-15 through clang-19

**Additional information:**
Bisecting with `-mllvm -opt-bisect-limit=N` points to SimplifyCFGPass:
```
$ clang++-21 -mllvm -opt-bisect-limit=1132 -Wall -Wextra -std=c++20 -O1 -g3 test.cpp -o test21 2> /tmp/o0_1132 && ./test21
0x7ffd0b9affb1 0

$ clang++-21 -mllvm -opt-bisect-limit=1133 -Wall -Wextra -std=c++20 -O1 -g3 test.cpp -o test21 2> /tmp/o0_1133 && ./test21
0x7fff07badad1 1

$ grep 'running pass \(1133\)' /tmp/o0_1133
1133:BISECT: running pass (1133) SimplifyCFGPass on _Z1fl
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Consider the following pattern:
```
%trunc = trunc nuw i64 %x to i48
%sel = select i1 %cmp, i48 %trunc, i48 undef
```
We cannot simplify `%sel` to `%trunc` as `%trunc` may be poison, which cannot be refined into undef.

This patch checks whether the replacement may be poison. If so, it will insert a freeze.
We may need SDAG's version of `impliesPoison` if it causes significant regressions.
Compile-time impact: https://llvm-compile-time-tracker.com/compare.php?from=ded109c0cff41714ebf9bd60b073aaab07fa4ca8&to=103e605ce6b33bc9145526faf805ee38b972c215&stat=instructions%3Au

Closes https://github.com/llvm/llvm-project/issues/175018.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Change itself looks fine.

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 1]
```diff
@@ -10820,9 +10820,9 @@ SDValue SelectionDAG::simplifySelect(SDValue Cond, SDValue T, SDValue F) {
   if (Cond.isUndef())
     return isConstantValueOfAnyType(T) ? T : F;
   if (T.isUndef())
-    return F;
+    return isGuaranteedNotToBePoison(F) ? F : getFreeze(F);
   if (F.isUndef())
-    return T;
+    return isGuaranteedNotToBePoison(T) ? T : getFreeze(T);
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: getFreeze will call getNode which will call isGuaranteedNotToBePoison- so reduces compute time to just call getFreeze directly.

Comment (dtcxzyw) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: The downside is that getFreeze->getNode calls `isGuaranteedNotToBeUndefOrPoison(/*PoisonOnly=*/false)`.

Comment (RKSimon) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: OK - sorry for the noise

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 2]
```diff
@@ -10815,14 +10815,14 @@ SDValue SelectionDAG::getSetFPEnv(SDValue Chain, const SDLoc &dl, SDValue Ptr,
 
 SDValue SelectionDAG::simplifySelect(SDValue Cond, SDValue T, SDValue F) {
   // select undef, T, F --> T (if T is a constant), otherwise F
-  // select, ?, undef, F --> F
-  // select, ?, T, undef --> T
+  // select, ?, undef, F --> freeze(F)
+  // select, ?, T, undef --> freeze(T)
```
[the remark this answers is not in the document]
Comment (dtcxzyw) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Yes. I'd leave it as a follow-up.

**Review by nikic — APPROVED** [review]
LGTM

**Review by RKSimon — APPROVED** [review]

**Review by topperc — APPROVED** [review]
LGTM
