### PR TITLE
 [AArch64] ORRWrs is copy instruction when there's no implicit def of the X register

### LINKED ISSUE #74680: Wrong register used on apple-m1
I tried this IR/MIR:

```llvm
; ModuleID = 'repro_117902.54923e0577e9cdaf-cgu.0'
source_filename = "repro_117902.54923e0577e9cdaf-cgu.0"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx11.0.0"

define i1 @foo(i32 %self.0.val, i8 %self.4.val) #1 {
start:
  switch i32 %self.0.val, label %bb2 [
    i32 0, label %bb9
    i32 1, label %bb4
    i32 2, label %bb5
    i32 3, label %bb1
  ]

bb2:                                              ; preds = %start
  unreachable

bb4:                                              ; preds = %start
  br label %bb9

bb5:                                              ; preds = %start
  br label %bb9

bb1:                                              ; preds = %start
  %trunc.not = icmp eq i8 %self.4.val, 0
  br label %bb9

bb9:                                              ; preds = %bb1, %start, %bb5, %bb4
  %r = phi i1 [ true, %bb5 ], [ true, %bb4 ], [ false, %start ], [ %trunc.not, %bb1 ]
  ret i1 %r
}

attributes #1 = { "frame-pointer"="non-leaf" "target-cpu"="apple-m1" }
```

I got:

```
_foo:                                   ; @foo
        mov     x8, x0
        mov     w0, #0                          ; =0x0
        adrp    x9, LJTI0_0@PAGE
        add     x9, x9, LJTI0_0@PAGEOFF
        adr     x10, LBB0_1
        ldrb    w11, [x9, x8]
        add     x10, x10, x11, lsl #2
        br      x10
...
```

If I run with `-O1`:

```
_foo:                                   ; @foo
        mov     x8, x0
        mov     w8, w0
        mov     w0, #0                          ; =0x0
        adrp    x9, LJTI0_0@PAGE
        add     x9, x9, LJTI0_0@PAGEOFF
        adr     x10, LBB0_1
        ldrb    w11, [x9, x8]
        add     x10, x10, x11, lsl #2
        br      x10
```

I think the first instruction should be `mov w8, w0`.

I'm not familiar with the MIR. But it looks like postrapseudos created `mov x8, x0` in lowercopy.
Then machine-cp removes late `mov w8, w0`.

godbolt: https://llvm.godbolt.org/z/1hfYvrGPG
from: https://github.com/rust-lang/rust/issues/117902

### PR DESCRIPTION
**Pull request by dianqk**
Follows https://github.com/llvm/llvm-project/pull/74682#issuecomment-1850268782.
Fixes #74680.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 1]
```diff
@@ -9180,24 +9180,46 @@ void AArch64InstrInfo::buildClearRegister(Register Reg, MachineBasicBlock &MBB,
...
+          return std::nullopt;
+        }
+    }
     return DestSourcePair{MI.getOperand(0), MI.getOperand(2)};
   }
 
-  if (MI.getOpcode() == AArch64::ORRXrs &&
-      MI.getOperand(1).getReg() == AArch64::XZR &&
-      MI.getOperand(3).getImm() == 0x0) {
+  if (OpIsORRXrs && Reg1 == AArch64::XZR) {
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:9207]: It think the ORRXrs can stay as it was before.

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp [hunk 2]
```diff
@@ -9180,24 +9180,46 @@ void AArch64InstrInfo::buildClearRegister(Register Reg, MachineBasicBlock &MBB,
...
+  bool OpIsORRXrs = MI.getOpcode() == AArch64::ORRXrs;
+  if (!(OpIsORRWrs || OpIsORRXrs) || MI.getOperand(3).getImm() != 0x0)
+    return std::nullopt;
+  Register Reg1 = MI.getOperand(1).getReg();
+
+  if (OpIsORRWrs && Reg1 == AArch64::WZR) {
+    Register Reg0 = MI.getOperand(0).getReg();
+    // ORRWrs is copy instruction when there's no implicit def of the X
+    // register.
+    if (Reg0.isPhysical()) {
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64InstrInfo.cpp:9195]: I think this might be able to use MI.findRegisterDefOperandIdx with the Z register.
Something like this, maybe:
```
  if (MI.getOpcode() == AArch64::ORRWrs &&                                   
      MI.getOperand(1).getReg() == AArch64::WZR &&                           
      MI.getOperand(3).getImm() == 0x0 &&                                    
      // Check that the w->w move is not a zero-extending w->x mov.          
      (!MI.getOperand(0).getReg().isVirtual() ||                             
       !MI.getOperand(0).getSubReg() != 0) &&                                
      (!MI.getOperand(0).getReg().isPhysical() ||                            
       MI.findRegisterDefOperandIdx(MI.getOperand(0).getReg() - AArch64::W0 +
                                    AArch64::X0) == -1)) {                   
    return DestSourcePair{MI.getOperand(0), MI.getOperand(2)};               
```

File: llvm/test/CodeGen/AArch64/machine-cp-sub-reg.mir [hunk 3]
```diff
@@ -0,0 +1,33 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
+# RUN: llc -o - %s -O3 --run-pass=machine-cp -mcp-use-is-copy-instr -mtriple=arm64-apple-macos -mcpu=apple-m1 --verify-machineinstrs | FileCheck %s
```
Comment (davemgreen) [inline llvm/test/CodeGen/AArch64/machine-cp-sub-reg.mir:2]: Can you remove `-O3` and maybe the -mcpu?

**Review by davemgreen — COMMENTED** [review]
Thank for doing this, it looks like good stuff to me.

File: llvm/test/CodeGen/AArch64/machine-cp-sub-reg.mir (hunk 3 above)
Comment (DianQK) [reply llvm/test/CodeGen/AArch64/machine-cp-sub-reg.mir]: Yes. I can delete them all.

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp (hunk 2 above)
Comment (DianQK) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp]: Thanks. Updated.

File: llvm/lib/Target/AArch64/AArch64InstrInfo.cpp (hunk 1 above)
Comment (DianQK) [reply llvm/lib/Target/AArch64/AArch64InstrInfo.cpp]: Done.

**Review by davemgreen — APPROVED** [review]
Thanks. This LGTM

**Comment by DianQK** [comment]
Thanks for your help. I've learned a lot.
