### PR TITLE
[clang][modules] Guard against bad -fmodule-file mappings (#132059)

### LINKED ISSUE #132059: small mistake in -fmodule-file description breaks clang++-19 frontend with -fstack-protector
I was experimenting CXX Modules with Clang 19 on Ubuntu, and it suddently broke when I passed wrong parameters on -fmodule-file, but strangely this only occurred when -fstack-protector was enabled... I have no idea why.

This is the clang version:
```
$ clang++-19 --version
Ubuntu clang version 19.1.1 (1ubuntu1~24.04.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
```

The files are:
```
// main.cc
import hello;

// import <string_view>;
import std;

int main() {
  do_hello("world");
  return 0;
}
```

```
// hello.cppm
export module hello;
import std;

export inline void do_hello(std::string_view const &name)
{
  std::cout << "Hello " << name << "!\n";
}
```

First I compile both .pcm files:
```
clang++-19 -std=c++23 -stdlib=libc++ -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++23' -fPIC -Wno-reserved-identifier -Wno-reserved-module-identifier --precompile -o std.pcm /usr/lib/llvm-19/share/libc++/v1/std.cppm

clang++-19 -std=c++23 -stdlib=libc++ -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++23' -fPIC -fmodule-file=std=std.pcm -Wno-reserved-identifier -Wno-reserved-module-identifier --precompile -o hello.pcm hello.cppm std.pcm
```

The bug appears when I mistakenly pass 'std' twice:

```
clang++-19 -fstack-protector  -fmodule-file=std=example/hello-world/std.pcm -fmodule-file=std=example/hello-world/hello.pcm -stdlib=libc++ -std=c++23 example/hello-world/main.cc -o main.pic.o 
```

```
$ clang++-19 -fstack-protector  -fmodule-file=std=example/hello-world/std.pcm -fmodule-file=std=example/hello-world/hello.pcm -stdlib=libc++ -std=c++23 example/hello-world/main.cc -o main.pic.o 
example/hello-world/main.cc:2:8: fatal error: module 'hello' not found
    2 | import hello;
      | ~~~~~~~^~~~~
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/lib/llvm-19/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -dumpdir main.pic.o- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/imcoelho/git-reps/rules_cc_module -fcoverage-compilation-dir=/home/imcoelho/git-reps/rules_cc_module -resource-dir /usr/lib/llvm-19/lib/clang/19 -internal-isystem /usr/lib/llvm-19/bin/../include/c++/v1 -internal-isystem /usr/lib/llvm-19/lib/clang/19/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/15/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++23 -fdeprecated-macro -ferror-limit 19 -stack-protector 1 -fgnuc-version=4.2.1 -fno-implicit-modules -fmodule-file=std=example/hello-world/std.pcm -fmodule-file=std=example/hello-world/hello.pcm -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/main-be446a.o -x c++ example/hello-world/main.cc
1.      example/hello-world/main.cc:5:11: current parser token ';'
 #0 0x000078607d8bd0af llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xebd0af)
 #1 0x000078607d8badb9 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xebadb9)
 #2 0x000078607d8bd800 (/usr/lib/llvm-19/bin/../lib/libLLVM.so.19.1+0xebd800)
 #3 0x000078607c245330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #4 0x000078608711d3d1 clang::ASTReader::ReadASTBlock(clang::serialization::ModuleFile&, unsigned int) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2b1d3d1)
 #5 0x0000786087124c75 clang::ASTReader::ReadAST(llvm::StringRef, clang::serialization::ModuleKind, clang::SourceLocation, unsigned int, clang::serialization::ModuleFile**) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2b24c75)
 #6 0x00007860872f0029 clang::CompilerInstance::findOrCompileModuleAndReadAST(llvm::StringRef, clang::SourceLocation, clang::SourceLocation, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2cf0029)
 #7 0x00007860872f1e94 clang::CompilerInstance::loadModule(clang::SourceLocation, llvm::ArrayRef<std::pair<clang::IdentifierInfo*, clang::SourceLocation>>, clang::Module::NameVisibilityKind, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2cf1e94)
 #8 0x000078608610f1c1 clang::Sema::ActOnModuleImport(clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, llvm::ArrayRef<std::pair<clang::IdentifierInfo*, clang::SourceLocation>>, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x1b0f1c1)
 #9 0x00007860853200b9 clang::Parser::ParseModuleImport(clang::SourceLocation, clang::Sema::ModuleImportState&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd200b9)
#10 0x000078608531ece7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xd1ece7)
#11 0x000078608524b44e clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0xc4b44e)
#12 0x000078608737a68c clang::FrontendAction::Execute() (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2d7a68c)
#13 0x00007860872eda04 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2ceda04)
#14 0x00007860873f9d2c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-19/bin/../lib/libclang-cpp.so.19.1+0x2df9d2c)
#15 0x000061625d4a71f2 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-19/bin/clang+0x131f2)
#16 0x000061625d4a41c4 (/usr/lib/llvm-19/bin/clang+0x101c4)
#17 0x000061625d4a3362 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm-19/bin/clang+0xf362)
#18 0x000061625d4b1723 main (/usr/lib/llvm-19/bin/clang+0x1d723)
#19 0x000078607c22a1ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#20 0x000078607c22a28b call_init ./csu/../csu/libc-start.c:128:20
#21 0x000078607c22a28b __libc_start_main ./csu/../csu/libc-start.c:347:5
#22 0x000061625d4a1dc5 _start (/usr/lib/llvm-19/bin/clang+0xddc5)
clang++-19: error: unable to execute command: Segmentation fault (core dumped)
clang++-19: error: clang frontend command failed due to signal (use -v to see invocation)
Ubuntu clang version 19.1.1 (1ubuntu1~24.04.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
clang++-19: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++-19: note: diagnostic msg: /tmp/main-95dd6a.cpp
clang++-19: note: diagnostic msg: /tmp/main-95dd6a.sh
clang++-19: note: diagnostic msg: 

********************
```

```
$ cat /tmp/main-95dd6a.sh 
# Crash reproducer for Ubuntu clang version 19.1.1 (1ubuntu1~24.04.2)
# Driver args: "--driver-mode=g++" "-fstack-protector" "-fmodule-file=std=example/hello-world/std.pcm" "-fmodule-file=std=example/hello-world/hello.pcm" "-stdlib=libc++" "-std=c++23" "example/hello-world/main.cc" "-o" "main.pic.o"
# Original command:  "/usr/lib/llvm-19/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-dumpdir" "main.pic.o-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "main.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/imcoelho/git-reps/rules_cc_module" "-fcoverage-compilation-dir=/home/imcoelho/git-reps/rules_cc_module" "-resource-dir" "/usr/lib/llvm-19/lib/clang/19" "-internal-isystem" "/usr/lib/llvm-19/bin/../include/c++/v1" "-internal-isystem" "/usr/lib/llvm-19/lib/clang/19/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/15/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++23" "-fdeprecated-macro" "-ferror-limit" "19" "-stack-protector" "1" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fmodule-file=std=example/hello-world/std.pcm" "-fmodule-file=std=example/hello-world/hello.pcm" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/main-be446a.o" "-x" "c++" "example/hello-world/main.cc"
 "/usr/lib/llvm-19/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-dumpdir" "main.pic.o-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "main.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/imcoelho/git-reps/rules_cc_module" "-fcoverage-compilation-dir=/home/imcoelho/git-reps/rules_cc_module" "-std=c++23" "-fdeprecated-macro" "-ferror-limit" "19" "-stack-protector" "1" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fmodule-file=std=example/hello-world/std.pcm" "-fmodule-file=std=example/hello-world/hello.pcm" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "main-95dd6a.cpp"
```

```
$ cat /tmp/main-95dd6a.cpp
# 1 "example/hello-world/main.cc"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 484 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "example/hello-world/main.cc" 2

import hello;


import std;

int main() {
  do_hello("world");
  return 0;
}
```

It breaks with `1.      example/hello-world/main.cc:5:11: current parser token ';'`
But it seems to occur only if I enable -fstack-protector ... if I remove it, the bug is gone (but error correctly remains):

```
$ clang++-19  -fmodule-file=std=example/hello-world/std.pcm -fmodule-file=std=example/hello-world
/hello.pcm -stdlib=libc++ -std=c++23 example/hello-world/main.cc -o main.pic.o 
example/hello-world/main.cc:2:8: fatal error: module 'hello' not found
    2 | import hello;
      | ~~~~~~~^~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by naveen-seth**
Fix https://github.com/llvm/llvm-project/issues/132059.

Providing incorrect mappings via `-fmodule-file=<name>=<path/to/bmi>`
can crash the compiler when loading a module that imports an
incorrectly mapped module.

The crash occurs during AST body deserialization, when the compiler
attempts to resolve remappings using the `ModuleFile` from the
incorrectly mapped module's BMI file.
The cause is an invalid access into an incorrectly loaded
`ModuleFile`.

This commit fixes the issue by verifying the identity of the imported
module.

### CODE REVIEW

**Review by ChuanqiXu9 — COMMENTED** [review]
The size of the patch is slightly more than what I thought. I thought this may be a simple change. Could you describe the crash point and the crash reason (from code's perspective)

**Comment by naveen-seth** [comment]
At first I thought the issue could be fixed by just checking for duplicates
while parsing the command-line arguments.

I will try to explain the crash point and reason with an example:

```cpp
//--- a.cppm
export module A;

export int a() {
  return 41;
}
```

```cpp
//--- b.cppm
export module B;
import A;

export int b() {
  return a() + 1;
}
```

```cpp
//--- main.cpp
import A;

int main() {
  return a();
}
```

```bash
# Correctly precompile the modules
clang++ -std=c++20 --precompile a.cppm -o a.pcm
clang++ -std=c++20 --precompile b.cppm -fmodule-file=A=a.pcm -o b.pcm
# Bad use of -fmodule-file=...
clang++ -std=c++20 main.cpp -fmodule-file=A=a.pcm -fmodule-file=A=b.pcm
```


Looking at how the arguments are parsed [(here)](https://github.com/llvm/llvm-project/blob/191e0622e84a215c1d632412561c2fe6ccd86170/clang/lib/Frontend/CompilerInvocation.cpp#L3388C16-L3388C23), the mapping `A=a.pcm` is overridden by `A=b.pcm`.
Therefore, it is no different than:

```bash
clang++ -std=c++20 main.cpp -fmodule-file=A=b.pcm
```

The mismatch here can't be detected by validating the command-line arguments.
Clang can only detect the mismatch once it has read the module name in `b.pcm`.

Let's now look at how the error occurs:

(from top to bottom)

`Sema::ActOnModuleImport`
`CompilerInstance::loadModule`

`b.pcm` is found as the BMI to load the module from.

`CompilerInstance::findOrCompileModuleAndReadAST`
`ASTReader::ReadAST`
`ASTReader::ReadASTCore`

Module `A` is added to `ModuleMgr` and the AST for `b.pcm` is read because `ModuleMgr` reports it as newly loaded.

`ASTReader::ReadControlBlock`

Currently (prior to this PR), there is no validation to ensure the BMI file actually contains the module it is trying to load after having read the module name in `ASTReader::ReadControlBlock`.
The control block continues to be read.
When the import of `A` in the control block of `b.pcm` is reached, clang
attempts to load again.
The `ModuleMgr` will report the AST of `b.pcm` as already loaded and no error is generated at this point either.

We now effectively have a recursive import.

The crash then occurs when reading the AST blocks and trying to resolve the module file remappings (DeclID, SubmoduleID, ...), because of invalid access into members of the invalid `ModuleFile` for module `A`.

**Comment by ChuanqiXu9** [comment]
I received a mail but not see it in the web page. Is something going wrong.

**Comment by naveen-seth** [comment]
Hi, sorry! I left a comment earlier but noticed that a large part of the explanation was incorrect and deleted it. Here is the fixed comment:

At first I thought that the issue can be fixed by just checking for duplicates while parsing the command-line arguments, but that doesn't seem to be the case.

I will try to describe the crash point and the crash reason with this example (without duplicate arguments):

```cpp
//--- a.cppm
export module A;

export int a() {
  return 41;
}
```

```cpp
//--- b.cppm
export module B;
import A;

export int b() {
  return a() + 1;
}
```

```cpp
//--- c.cppm
export module C;

export int c() {
  return 42;
}
```

```cpp
//--- main.cpp
import B;

int main() {
  return b();
}
```

```
# Correctly precompile the modules
clang++ -std=c++20 --precompile a.cppm -o a.pcm
clang++ -std=c++20 --precompile b.cppm -fmodule-file=A=a.pcm -o b.pcm
clang++ -std=c++20 --precompile c.cppm -o c.pcm

# Bad use of -fmodule-file=...
clang++ -std=c++20 main.cpp -std=c++20 main.cpp -fmodule-file=B=b.pcm -fmodule-file=A=c.pcm
```

After `import B;` is parsed from `main.cpp`, the following sequence of function calls occurs (from top to bottom): 

…
`Sema::ActOnModuleImport`
`CompilerInstance::loadModule`
`CompilerInstance::findOrCompileModuleAndReadAST`
`ASTReader::ReadAST`
`ASTReader::ReadASTCore`
`ASTReader::ReadControlBlock`

When reading a modules control block in `ASTReader::ReadControlBlock`, Clang also attempts to get the `ModuleFile` for each of its imports ([see here](https://github.com/llvm/llvm-project/blob/943a70717c629f43b309ab56e8141ffb131871a6/clang/lib/Serialization/ASTReader.cpp#L3024)).
First, the matching BMI file for an imported module is looked up, then Clang calls back to `ASTReader::ReadASTCore` to ensure the BMI files `ModuleFile`.

Currently (prior to this PR), there is no validation to ensure that the BMI file actually contains the module clang is trying to load after having read the module name in `ReadControlBlock`.

Because of the faulty `-fmodule-file=` mapping, the `ModuleFile` of the import will refer to a BMI built for a different module than the one clang is trying to load.
Here, the import of `A` in `b.cppm` will result in loading the `ModuleFile` corresponding to `c.pcm` while deserializing `b.pcm`. 

The crash occurs because Clang, assuming it has the correct `ModuleFile`s, continues reading AST blocks and attempts to resolve `ModuleFile` remappings (any of the mappings mentioned [here](https://github.com/llvm/llvm-project/blob/74ace4fd3c71ff59f2d89680c0f1382d0f9933f4/clang/lib/Serialization/ASTReader.cpp#L8765)). This results in invalid access into members of the invalid `ModuleFile`s and finally the crash.

(Depending on the specific example, the exact location of the crash will be different, but it will always happen while trying to resolve the remappings.)

While writing this comment, I noticed that my commit and PR message describe the cause of the crash incorrectly and have edited both.

**Review by ChuanqiXu9 — COMMENTED** [review]
Thanks. What I feel not good is passing `ExpectedName` and `ModuleMismatch` all around. I am wondering if we can check it by inserting a check in `ASTReader::ReadControlBlock` in `case IMPORT:` where we can check the `ImportedName` and the name stored in loaded module.

**Comment by naveen-seth** [comment]
Updated! That really makes does make it a lot simpler.

I was a bit unsure regarding the following lines:

https://github.com/llvm/llvm-project/blob/b98d66f394cc2e25ea0873cfda79704e10795c7b/clang/lib/Serialization/ASTReader.cpp#L3342-L3346 

Is it acceptable to also return `OutOfDate` for this error case?
(We don´t return immediately to also include the backtrace.)

Thank you for the review and my apologies for the delay!

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM

File: clang/lib/Serialization/ASTReader.cpp [hunk 1]
```diff
@@ -3318,6 +3318,14 @@ ASTReader::ReadControlBlock(ModuleFile &F,
                                 Loaded, StoredSize, StoredModTime,
                                 StoredSignature, Capabilities);
 
+      // Check the AST we just read from ImportedFile contains a different
+      // module than we expected (ImportedName).
+      if (auto *Imported = getModuleManager().lookupByFileName(ImportedFile);
+          Imported != nullptr && Imported->ModuleName != ImportedName) {
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTReader.cpp:3324]: To make it more controllable, let's add a check for `IsImportingStdCXXModule`

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. Thanks.

File: clang/lib/Serialization/ASTReader.cpp (hunk 1 above)
Comment (naveen-seth) [reply clang/lib/Serialization/ASTReader.cpp]: Added.
Theoretically also only applies to `MK_PrebuiltModule`. 
Should I also add it to the check?
