### PR TITLE
[C++20] [Modules] Instantiate pending instantiations when GMF ends

### LINKED ISSUE #125999: Templated static member variables are initialized in the including module instead of the global module
When I include a header that contains a templated class with static member variables (and those variables are initialized outside the class) in the global module fragment of my module class, Clang determines that the initialization is in **my** module (not the GMF). See the following example: https://gcc.godbolt.org/z/ej6K4h6ds. Also pasting below for convenience.

`bar.h`:
```
template <typename T>
struct Singleton {
    static T* instance_;
    static T* get() {
        static bool init = false;
        if (!init) {
            init = true;
            instance_ = ::new T();
        }
        return instance_;
    }
};

template <typename T>
T* Singleton<T>::instance_ = nullptr;

struct s{};
inline void* foo() {
    return Singleton<s>::get();
}
```

`foo.ixx`:
```
module;
#include "bar.h"
export module foo;
```

This fails to compile because `declaration of 'instance_' in module foo follows declaration in the global module`, but the include is in the global module fragment so shouldn't the declaration also be there (not in `Foo`)? This compiles successfully on GCC.
```
bar.h:20:18: error: declaration of 'instance_' in module foo follows declaration in the global module
   20 | T* Singleton<T>::instance_ = nullptr;
      |                  ^
bar.h:13:13: note: in instantiation of static data member 'Singleton<s>::instance_' requested here
   13 |             instance_ = ::new T();
      |             ^
bar.h:25:26: note: in instantiation of member function 'Singleton<s>::get' requested here
   25 |     return Singleton<s>::get();
      |                          ^
bar.h:8:15: note: previous declaration is here
    8 |     static T* instance_;
```

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Close https://github.com/llvm/llvm-project/issues/125999

The cause of the problem is, when we instantiate the pending instantiation, the owning module of the TU gets into 'foo' instead of the GMF.

The concern of the patch is, I am not sure the point of 'pending' instantiations. I mean, if there is a reason we **must** pending the intantiations to the end of the TU.

### CODE REVIEW

File: clang/lib/Sema/Sema.cpp [hunk 1]
```diff
@@ -1104,9 +1104,13 @@ void Sema::ActOnStartOfTranslationUnit() {
 }
 
 void Sema::ActOnEndOfTranslationUnitFragment(TUFragmentKind Kind) {
-  // No explicit actions are required at the end of the global module fragment.
-  if (Kind == TUFragmentKind::Global)
+  if (Kind == TUFragmentKind::Global) {
+    // Perform Pending Instantiations at the end of global module fragment so
+    // that the module ownership of TU-level decls won't get messed.
+    llvm::TimeTraceScope TimeScope("PerformPendingInstantiations");
+    PerformPendingInstantiations();
```
Comment (zyn0217) [inline clang/lib/Sema/Sema.cpp:1111]: Why did it say `No explicit actions are required at the end of the global module fragment?`

Can we just exercise the rest logic for `TUFragmentKind::Global`?

**Review by zyn0217 — COMMENTED** [review]
Thanks for looking into that. This needs a release note

File: clang/lib/Sema/Sema.cpp (hunk 1 above)
Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: > Why did it say No explicit actions are required at the end of the global module fragment?

Maybe literally we didn't find anything need to done.

> Can we just exercise the rest logic for TUFragmentKind::Global?

I don't feel it is a good idea. The GMF is not a TU. We shouldn't do what's needed for a TU for a GMF. Let's make them when needed.

**Comment by ChuanqiXu9** [comment]
> This needs a release note

The release note makes backporting harder. I generally summarize the release notes for modules when clang is going to be released.

File: clang/lib/Sema/Sema.cpp (hunk 1 above)
Comment (mizvekov) [inline clang/lib/Sema/Sema.cpp:1111]: I find problematic the existing model of template instantiation module ownership.

Surely a template may need a certain instantiation for multiple uses, possibly in different modules.
If a template has been instantiated, we don't need to instantiate it again. It looks accidental that these declarations
end up being owned by the module which first instantiated it.

The instantiations should either have no ownership, perhaps homed to the owner of the pattern, or maybe be multiply owned.

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: I feel it is less concerning to me.

> If a template has been instantiated, we don't need to instantiate it again.

It is already the case. When we want to instantiate a template instantiation, we will lookup if we've already instantiated it. And when we lookup if we instantiated an instantiation, we will lookup it in the external source. See `findSpecializationImpl` in DeclTemplate.cpp for details.

> The instantiations should either have no ownership, perhaps homed to the owner of the pattern, or maybe be multiply owned.

On the other hand, if we don't find an instantiation in the external source, we will instantiate it. Then the **same**(?) instantiation may be instantiated to different modules. e.g.,

```
export module a;
export template <class T>
class Templ { ... };

export module b;
import a;
Templ<int> ...; // instantiation attached to module b

export module c;
import a;
Templ<int> ...; // instantiation attached to module c

export module d;
import b;
import c;
Templ<int> ...
```

in the above example, the instantiation of `Templ<int>` may be attached to module b and c in different TUs. And in module d, the instantiation of `Templ<int>` from different modules will be redecls to each other. And these redeclarations may have different modules ownership. So it is already multiply owned.

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: @mizvekov ping~

Comment (mizvekov) [reply clang/lib/Sema/Sema.cpp:1111]: I didn't state my point clearly enough, sorry about that.

What I mean is, we can for example always set instantiation ownership to the same as the pattern, and that is just
as consistent and correct, but should be a simpler change and have higher performance, as we will still batch up pending instantiations the same as before, correct?

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: Got it. But maybe not so simple since we will change the module owner ship when setting the decl context. And this is the reason why the modules ownership is incorrect in this example.

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: Oh, sorry, I didn't make it clear. We won't set the module ownership when we set the semantical DeclContext but set it when we set the Lexical DeclContext. It may not be super straightforward but it works "fine" over years. I prefer to keep as is to fix the current "small" problems  now.

Comment (mizvekov) [reply clang/lib/Sema/Sema.cpp:1111]: The distinction lexical vs semantic context does not matter here, they are both properties of the pattern and of the instantiation, and they do not depend on the template parameters, so we shouldn't change them when instantiating.

Well you say it works fine, but surely it does not work fine in this case. And I remember someone on discord was recently complaining about our inconsistencies in this area.

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: Are you saying the lexical decl context of an instantiation should be the same with the template? If yes, I feel it is incorrect. I think the lexical decl context should show the lexical context of a decl literally.

---

BTW, I do think the modules ownership and decl context ownership are two distinct problems. And if you can solve two of them in a consistent manner, it is good. But it is good too to solve one standalone.

My attitude to such "fundamental" problems is: yes, it is always good to fix them fundamentally. But it is also good to do some adhoc mix to stop bleeding first. So the ordering in my mind can be:

landing this patch as a fix -> fix the fundamental problems you described -> revert this patch

I don't feel it will be problematic.

Comment (ChuanqiXu9) [reply clang/lib/Sema/Sema.cpp:1111]: BTW, I just tried a trivial example:
```
export module a;
export template <typename T>
void func() {}
```

```
export module b;
import a;
void b() {
   func<int>();
}
template void func<double>();

class B {};
void b2() {
    func<B>();
}
```

And the generated symbols in b.cppm for instantiations of A is:

```
_ZW1a4funcIiEvv
_ZW1a4funcIW1b1BEvv
_ZW1a4funcIdEvv
```

it shows all these instantiations are attached to the a module, at least from the linker's perspective, which is expected by us.

**Comment by ChuanqiXu9** [comment]
I'd like to land this in next week if no objection come in. As @mizvekov said, there is space to improve the overall design. But given the patch itself is simple and not hurting. I do feel we should stop bleeding.

**Review by mizvekov — APPROVED** [review]
LGTM

I can't follow up on this with a better suggestion right now, and I don't want to make the perfect the enemy of the good.
