### PR TITLE
[clang-format] Fix crash involving array designators

### LINKED ISSUE #76716: clang-format fails with assertion "`idx < size()' failed"
The archive [files.tar.gz](https://github.com/llvm/llvm-project/files/13810489/files.tar.gz) contains a "_clang-format" configuration file as well as a minimal example C file "crash-example.c". The provided C file compiles with recent gcc and clang, although both submit some warnings (depending on options). The problem is reproducible with several recent versions of clang-format as well as with a build from latest main branch.

How to reproduce:

Unpack the archive  [files.tar.gz](https://github.com/llvm/llvm-project/files/13810489/files.tar.gz) and run:

```
$ tar xzf files.tar.gz
$ clang-format --version
clang-format version 18.0.0git (https://github.com/llvm/llvm-project.git 2eb0ac0b3e3c74875e9b376239a27b8eb389189c)
$ clang-format files/crash-example.c
clang-format: /home/foo/llvm/include/llvm/ADT/SmallVector.h:298: const T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) const [with T = clang::format::WhitespaceManager::Change; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::const_reference = const clang::format::WhitespaceManager::Change&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-format files/crash-example.c
 #0 0x000055accecb5bfe llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/foo/llvm/lib/Support/Unix/Signals.inc:723:22
 #1 0x000055accecb600f PrintStackTraceSignalHandler(void*) /home/foo/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x000055accecb359a llvm::sys::RunSignalHandlers() /home/foo/llvm/lib/Support/Signals.cpp:105:20
 #3 0x000055accecb54b8 SignalHandler(int) /home/foo/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f0cbce16420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007f0cbc8cf00b raise /build/glibc-wuryBv/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007f0cbc8ae859 abort /build/glibc-wuryBv/glibc-2.31/stdlib/abort.c:81:7
 #7 0x00007f0cbc8ae729 get_sysdep_segment_value /build/glibc-wuryBv/glibc-2.31/intl/loadmsgcat.c:509:8
 #8 0x00007f0cbc8ae729 _nl_load_domain /build/glibc-wuryBv/glibc-2.31/intl/loadmsgcat.c:970:34
 #9 0x00007f0cbc8bffd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#10 0x000055accee397f9 llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::Change, void>::operator[](unsigned long) const /home/foo/llvm/include/llvm/ADT/SmallVector.h:299:19
#11 0x000055accee39020 auto clang::format::WhitespaceManager::getNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int) const /home/foo/clang/lib/Format/WhitespaceManager.h:285:36
#12 0x000055accee39a59 unsigned int clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int, unsigned int, unsigned int) const /home/foo/clang/lib/Format/WhitespaceManager.h:325:19
#13 0x000055accee2d617 clang::format::WhitespaceManager::alignArrayInitializersRightJustified(clang::format::WhitespaceManager::CellDescriptions&&) /home/foo/clang/lib/Format/WhitespaceManager.cpp:1310:46
#14 0x000055accee2d2a6 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) /home/foo/clang/lib/Format/WhitespaceManager.cpp:1272:50
#15 0x000055accee2d1f2 clang::format::WhitespaceManager::alignArrayInitializers() /home/foo/clang/lib/Format/WhitespaceManager.cpp:1258:23
#16 0x000055accee2ac51 clang::format::WhitespaceManager::generateReplacements() /home/foo/clang/lib/Format/WhitespaceManager.cpp:118:18
#17 0x000055acced6db4b clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) /home/foo/clang/lib/Format/Format.cpp:2441:59
#18 0x000055accedcb2b6 clang::format::TokenAnalyzer::process(bool) /home/foo/clang/lib/Format/TokenAnalyzer.cpp:132:5
#19 0x000055acced7383f clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda9'(clang::format::Environment const&)::operator()(clang::format::Environment const&) const /home/foo/clang/lib/Format/Format.cpp:3730:12
#20 0x000055acced7ca16 std::_Function_handler<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&), clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda9'(clang::format::Environment const&)>::_M_invoke(std::_Any_data const&, clang::format::Environment const&) /usr/include/c++/9/bits/std_function.h:287:7
#21 0x000055acced943da std::function<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&)>::operator()(clang::format::Environment const&) const /usr/include/c++/9/bits/std_function.h:689:5
#22 0x000055acced7456d clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) /home/foo/clang/lib/Format/Format.cpp:3746:49
#23 0x000055acced74b46 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) /home/foo/clang/lib/Format/Format.cpp:3788:28
#24 0x000055accebbcbfd clang::format::format(llvm::StringRef, bool) /home/foo/clang/tools/clang-format/ClangFormat.cpp:499:76
#25 0x000055accebbe24d main /home/foo/clang/tools/clang-format/ClangFormat.cpp:692:11
#26 0x00007f0cbc8b0083 __libc_start_main /build/glibc-wuryBv/glibc-2.31/csu/../csu/libc-start.c:342:3
#27 0x000055accebbaa4e _start (/home/foo/build/bin/clang-format+0x349a4e)
```

### PR DESCRIPTION
**Pull request by XDeme1**
Fixes llvm/llvm-project#76716
Fixes parsing of `[0]{}`. Before this patch it was begin parsed as a lambda, now it is correctly parsed as a designator initializer.

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -21084,6 +21084,12 @@ TEST_F(FormatTest, CatchAlignArrayOfStructuresLeftAlignment) {
       "};",
       Style);
 
+  verifyNoCrash("Foo f[] = {\n"
+                "    [0] = { 1, },\n"
+                "    [1] { 1, },\n"
+                "};",
+                Style);
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:21091]: We should also add it to `CatchAlignArrayOfStructuresRightAlignment`.

**Comment by XDeme** [comment]
While I was trying to find a minimal reproducer to the bug, I accidentally found that this patch fix another crash, and doesn't fix the linked issue.
What should be done here?

**Comment by XDeme** [comment]
I think with this the issue might be solved.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 2]
```diff
@@ -1444,16 +1444,22 @@ WhitespaceManager::CellDescriptions WhitespaceManager::getCells(unsigned Start,
...
     } else if (Depth == 1) {
       if (C.Tok == MatchingParen) {
         if (!Cells.empty())
           Cells.back().EndIndex = i;
         Cells.push_back(CellDescription{i, ++Cell, i + 1, false, nullptr});
-        CellCounts.push_back(C.Tok->Previous->isNot(tok::comma) ? Cell + 1
-                                                                : Cell);
+        CellCounts.push_back(
+            C.Tok->Previous->isNot(tok::comma) &&
+                    !MatchingParen->MatchingParen->Previous->is(tok::equal)
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:1460]:
```suggestion
                    MatchingParen->MatchingParen->Previous->isNot(tok::equal)
```
`MatchingParen->MatchingParen` shouldn't we be back where we started? Whatever is going on here, I think a comment would be helpful.

Comment (XDeme) [reply clang/lib/Format/WhitespaceManager.cpp]: I hope the comment is helpful.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 3]
```diff
@@ -1444,16 +1444,26 @@ WhitespaceManager::CellDescriptions WhitespaceManager::getCells(unsigned Start,
...
         if (!Cells.empty())
           Cells.back().EndIndex = i;
         Cells.push_back(CellDescription{i, ++Cell, i + 1, false, nullptr});
-        CellCounts.push_back(C.Tok->Previous->isNot(tok::comma) ? Cell + 1
-                                                                : Cell);
+        CellCounts.push_back(
+            C.Tok->Previous->isNot(tok::comma) &&
+                    // When dealing with C array designators. There is a
+                    // possibility of some nested array not having an `=`.
+                    // When this happens we make the cells non retangular,
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:1462]:
```suggestion
                    // When this happens we make the cells non rectangular,
```

File: clang/lib/Format/WhitespaceManager.cpp [hunk 4]
```diff
@@ -1444,16 +1444,26 @@ WhitespaceManager::CellDescriptions WhitespaceManager::getCells(unsigned Start,
       } else if (C.Tok->is(tok::comma)) {
         if (!Cells.empty())
           Cells.back().EndIndex = i;
-        if (C.Tok->getNextNonComment()->isNot(tok::r_brace)) // dangling comma
+
+        if (const auto *Next = C.Tok->getNextNonComment();
+            Next && Next->isNot(tok::r_brace)) { // dangling comma
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:1449]:
```suggestion
            Next && Next->isNot(tok::r_brace)) { // Dangling comma.
```

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/WhitespaceManager.cpp [hunk 5]
```diff
@@ -1444,16 +1444,26 @@ WhitespaceManager::CellDescriptions WhitespaceManager::getCells(unsigned Start,
...
         Cells.push_back(CellDescription{i, ++Cell, i + 1, false, nullptr});
-        CellCounts.push_back(C.Tok->Previous->isNot(tok::comma) ? Cell + 1
-                                                                : Cell);
+        CellCounts.push_back(
+            C.Tok->Previous->isNot(tok::comma) &&
+                    // When dealing with C array designators. There is a
+                    // possibility of some nested array not having an `=`.
+                    // When this happens we make the cells non rectangular,
+                    // avoiding an access out of bound later on.
+                    MatchingParen->MatchingParen->Previous->isNot(tok::equal)
```
Comment (owenca) [inline clang/lib/Format/WhitespaceManager.cpp:1464]: This seems a little hacky. We should probably investigate a bit more to find the root cause.

Comment (XDeme) [reply clang/lib/Format/WhitespaceManager.cpp]: I've investigated a bit more, and I found that we were actually parsing
`[0] {};` as a lambda, instead of a designated initializer

Comment (owenca) [reply clang/lib/Format/WhitespaceManager.cpp]: Yep, so we should fix that instead. :)

File: clang/lib/Format/WhitespaceManager.cpp [hunk 6]
```diff
@@ -1444,6 +1444,7 @@ WhitespaceManager::CellDescriptions WhitespaceManager::getCells(unsigned Start,
       } else if (C.Tok->is(tok::comma)) {
         if (!Cells.empty())
           Cells.back().EndIndex = i;
+
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:1447]: Unrelated (and unwanted?)

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 7]
```diff
@@ -2315,6 +2315,10 @@ bool UnwrappedLineParser::tryToParseLambdaIntroducer() {
     if (Next->is(tok::greater))
       return false;
   }
+  if (const auto Kind = FormatTok->Tok.getKind();
+      tok::isLiteral(Kind) && !tok::isStringLiteral(Kind)) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/UnwrappedLineParser.cpp:2319]: Why ignore the string literal? `["Foo"` is also no lambda.

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 8]
```diff
@@ -2315,6 +2315,8 @@ bool UnwrappedLineParser::tryToParseLambdaIntroducer() {
     if (Next->is(tok::greater))
       return false;
   }
+  if (tok::isLiteral(FormatTok->Tok.getKind()))
+    return false;
```
Comment (owenca) [inline clang/lib/Format/UnwrappedLineParser.cpp:2319]:
```suggestion
```
Instead, I would change line 2311 to:
```
  if (FormatTok->isOneOf(tok::l_square, tok::numeric_constant))
```

**Comment by owenca** [comment]
Please add an assertion in `WhitespaceManager.h`:
```
--- a/clang/lib/Format/WhitespaceManager.h
+++ b/clang/lib/Format/WhitespaceManager.h
@@ -282,6 +282,7 @@ private:
     for (auto PrevIter = Start; PrevIter != End; ++PrevIter) {
       // If we broke the line the initial spaces are already
       // accounted for.
+      assert(PrevIter->Index) < Changes.size();
       if (Changes[PrevIter->Index].NewlinesBefore > 0)
         NetWidth = 0;
       NetWidth +=
```

File: clang/lib/Format/UnwrappedLineParser.cpp (hunk 8 above)
Comment (XDeme) [reply clang/lib/Format/UnwrappedLineParser.cpp:2319]: With this change this code will crash:
```cpp
Foo foo[] = {
    [0]{1,  1},
    ['a'] { 1, 1 },
    ['a']{1, 1},
};
```

Comment (XDeme) [reply clang/lib/Format/UnwrappedLineParser.cpp:2319]: With this change, a code like this will crash:
```cpp
Foo foo[] = {
    [0] = {1, 1},
    ['a']{1, 1},
    ['a']{1, 1},
};
```

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:2319]: You are right! Then how about the following?
```
  if (FormatTok->is(tok::l_square) || tok::isLiteral(FormatTok->Tok.getKind()))
```
The main point is to return as early as possible.

**Review by rymiel — APPROVED** [review]

**Review by owenca — APPROVED** [review]

**Comment by owenca** [comment]
> While I was trying to find a minimal reproducer to the bug, I accidentally found that this patch fix another crash, and doesn't fix the linked issue.

Can you open another pull request to [fix](https://github.com/llvm/llvm-project/pull/77045#discussion_r1442578220) the other crash?
```
```

**Comment by XDeme** [comment]
> > While I was trying to find a minimal reproducer to the bug, I accidentally found that this patch fix another crash, and doesn't fix the linked issue.
> 
> Can you open another pull request to [fix](https://github.com/llvm/llvm-project/pull/77045#discussion_r1442578220) the other crash?

@owenca Just created #77723
