### PR TITLE
[clang] assume_aligned incorrectly diagnoses a dependent return type

### LINKED ISSUE #111563: assume_aligned incorrectly diagnoses a dependent return type
Consider:
```
template<typename T>
__attribute__((assume_aligned(2)))
T my_alloc(int);
```
(https://godbolt.org/z/EGebP7o8n)

Clang issues a diagnostic about the return type not being a pointer type despite there being no instantiations. It seems we need to add `if T->isDependentType() return true;` to `isValidPointerAttrType()`, possibly.

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Fix `assume_aligned` incorrectly diagnoses a dependent return type

Fixes: #111563

### CODE REVIEW

File: clang/test/SemaCXX/builtin-assume-aligned-tmpl.cpp [hunk 1]
```diff
@@ -52,6 +52,9 @@ T *atest3() __attribute__((assume_aligned(31, o))); // expected-error {{requeste
 template <typename T, int o>
 T *atest4() __attribute__((assume_aligned(32, o)));
 
+template<typename T>
+T atest5(int) __attribute__((assume_aligned(2)));
```
Comment (erichkeane) [inline clang/test/SemaCXX/builtin-assume-aligned-tmpl.cpp:56]: This change causes a number of attributes to change their behavior (see all uses of `isValidPointerAttrType`), so we should test each of those.

Additionally, we should separately check (via a different declaration) that the diagnostic fires when instantiated.

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 2]
```diff
@@ -1217,6 +1217,8 @@ static void handlePreferredName(Sema &S, Decl *D, const ParsedAttr &AL) {
 
 bool Sema::isValidPointerAttrType(QualType T, bool RefOkay) {
   if (RefOkay) {
+    if (T->isDependentType())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclAttr.cpp:1220]: This doesn't seem like the right place for this, we should be skipping ANY time the type is dependent, not only when a ref argument is acceptable.

**Review by erichkeane — CHANGES_REQUESTED** [review]

File: clang/lib/Sema/SemaDeclAttr.cpp (hunk 2 above)
Comment (AmrDeveloper) [reply clang/lib/Sema/SemaDeclAttr.cpp]: Think you, updated

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 3]
```diff
@@ -1216,6 +1216,8 @@ static void handlePreferredName(Sema &S, Decl *D, const ParsedAttr &AL) {
 }
 
 bool Sema::isValidPointerAttrType(QualType T, bool RefOkay) {
+  if (T->isDependentType())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDeclAttr.cpp:1219]: Probably valuable to audit the other uses of this function well, and remove checks for dependence there as redundant.  And probably ensure the documentation of this function mentions that it skips on dependence.

Comment (AmrDeveloper) [reply clang/lib/Sema/SemaDeclAttr.cpp:1219]: Done, please check the updated documentation of the function

File: clang/include/clang/Sema/Sema.h [hunk 4]
```diff
@@ -4453,9 +4453,9 @@ class Sema final : public SemaBase {
                                       SourceLocation *ArgLocation = nullptr);
 
   /// Determine if type T is a valid subject for a nonnull and similar
-  /// attributes. By default, we look through references (the behavior used by
-  /// nonnull), but if the second parameter is true, then we treat a reference
-  /// type as valid.
+  /// attributes. By default, we skip dependence and look through references
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:4456]: `by default` implies that the dependence check can bie disabled, but it very much cannot.

Comment (AmrDeveloper) [reply clang/include/clang/Sema/Sema.h]: Thank you, all comments addressed

**Comment by AmrDeveloper** [comment]
This part in ObjectiveC tests conflict with the current solution, any suggestion how we can go around it right now until to be handled later

https://github.com/llvm/llvm-project/blob/18952bdcd6f987620e6396261c2bb444e428e07e/clang/test/SemaObjCXX/noescape.mm#L202-L205

@erichkeane @AaronBallman

File: clang/include/clang/Sema/Sema.h [hunk 5]
```diff
@@ -4453,9 +4453,9 @@ class Sema final : public SemaBase {
                                       SourceLocation *ArgLocation = nullptr);
 
   /// Determine if type T is a valid subject for a nonnull and similar
-  /// attributes. By default, we look through references (the behavior used by
-  /// nonnull), but if the second parameter is true, then we treat a reference
-  /// type as valid.
+  /// attributes. We skip dependence By default, we look through references
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:4456]: again, we're not skipping dependence by default, we're ALWAYS skipping dependence.  We skip references (presumably by default).  I think the dependence behavior just needs its own sentence here.

**Comment by erichkeane** [comment]
> This part in ObjectiveC tests conflict with the current solution, any suggestion how we can go around it right now until to be handled later
> 
> https://github.com/llvm/llvm-project/blob/18952bdcd6f987620e6396261c2bb444e428e07e/clang/test/SemaObjCXX/noescape.mm#L202-L205
> 
> @erichkeane @AaronBallman

Doesn't the fixme above that say it was diagnosing unintentionally?  If so, that fixme likely needs to be removed, and this is 'correct' now.

File: clang/include/clang/Sema/Sema.h (hunk 5 above)
Comment (AmrDeveloper) [reply clang/include/clang/Sema/Sema.h:4456]: Yes, i think i was planning to make it like `We skip dependence and By default,`

**Comment by AmrDeveloper** [comment]
> > This part in ObjectiveC tests conflict with the current solution, any suggestion how we can go around it right now until to be handled later
> > https://github.com/llvm/llvm-project/blob/18952bdcd6f987620e6396261c2bb444e428e07e/clang/test/SemaObjCXX/noescape.mm#L202-L205
> > 
> > @erichkeane @AaronBallman
> 
> Doesn't the fixme above that say it was diagnosing unintentionally? If so, that fixme likely needs to be removed, and this is 'correct' now.

Yes but still got `call to deleted constructor of 'S6'` and `'S6' has been explicitly marked deleted here` errors on CI and local

**Comment by AmrDeveloper** [comment]
> > This part in ObjectiveC tests conflict with the current solution, any suggestion how we can go around it right now until to be handled later
> > https://github.com/llvm/llvm-project/blob/18952bdcd6f987620e6396261c2bb444e428e07e/clang/test/SemaObjCXX/noescape.mm#L202-L205
> > 
> > @erichkeane @AaronBallman
> 
> Doesn't the fixme above that say it was diagnosing unintentionally? If so, that fixme likely needs to be removed, and this is 'correct' now.

I handled it, i didn't know that `// expected-note n` is the number of expected notes, 

Thank you

File: clang/include/clang/Sema/Sema.h [hunk 6]
```diff
@@ -4453,9 +4453,9 @@ class Sema final : public SemaBase {
                                       SourceLocation *ArgLocation = nullptr);
 
   /// Determine if type T is a valid subject for a nonnull and similar
-  /// attributes. By default, we look through references (the behavior used by
-  /// nonnull), but if the second parameter is true, then we treat a reference
-  /// type as valid.
+  /// attributes. We skip dependence then By default, we look through references
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:4456]:
```suggestion
  /// attributes. Dependent types are considered valid, so they can be checked during instantiation time. By default, we look through references
```

^^ make sure to clang-format.

**Review by erichkeane — APPROVED** [review]

File: clang/include/clang/Sema/Sema.h [hunk 7]
```diff
@@ -4453,9 +4453,10 @@ class Sema final : public SemaBase {
                                       SourceLocation *ArgLocation = nullptr);
 
   /// Determine if type T is a valid subject for a nonnull and similar
-  /// attributes. By default, we look through references (the behavior used by
-  /// nonnull), but if the second parameter is true, then we treat a reference
-  /// type as valid.
+  /// attributes. Dependent types are considered valid, so they can be checked
+  /// during instantiation time. By default, we look through references (the
+  /// behavior used by nonnull), but if the second parameter is true, then we
+  /// treat a reference type as valid..
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:4459]:
```suggestion
  /// treat a reference type as valid.
```
Missed this!

File: clang/include/clang/Sema/Sema.h [hunk 8]
```diff
@@ -4453,9 +4453,10 @@ class Sema final : public SemaBase {
                                       SourceLocation *ArgLocation = nullptr);
 
   /// Determine if type T is a valid subject for a nonnull and similar
-  /// attributes. By default, we look through references (the behavior used by
-  /// nonnull), but if the second parameter is true, then we treat a reference
-  /// type as valid.
+  /// attributes. Dependent types are considered valid, so they can be checked
```
Comment (erichkeane) [inline clang/include/clang/Sema/Sema.h:4456]:
```suggestion
  /// attributes. Dependent types are considered valid so they can be checked
```

**Review by erichkeane — CHANGES_REQUESTED** [review]

**Review by erichkeane — APPROVED** [review]
