### PR TITLE
[VPlan] Fix mutating whilst iterating over users in EVL transform

### LINKED ISSUE #122681: RISC-V EVL tail folding failure on SPEC CPU 2017 525.x264_r
Split out from the discussion here: https://github.com/llvm/llvm-project/pull/122458#issuecomment-2585713670 

On RISC-V with `-march=rva22u64_v -O3 -flto -mllvm -force-tail-folding-style=data-with-evl -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue`, the SPEC CPU 2017 525.x264_r benchmark fails in the train dataset, likely due to a miscompile.

It's been failing since at least 6ad0dcf67f5dccdf8506ce5f51d793062a1c6879, detected from this LNT run: https://lnt.lukelau.me/db_default/v4/nts/89

### LINKED ISSUE #122682: RISC-V EVL tail folding failure on SPEC CPU 2017 502.gcc_r
Split out from the discussion here: https://github.com/llvm/llvm-project/pull/122458#issuecomment-2585713670 

On RISC-V with `-march=rva22u64_v -O3 -flto -mllvm -force-tail-folding-style=data-with-evl -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue`, the SPEC CPU 2017 502.gcc_r benchmark fails in the train dataset, likely due to a miscompile.

It's been failing since at least 6ad0dcf67f5dccdf8506ce5f51d793062a1c6879, detected from this LNT run: https://lnt.lukelau.me/db_default/v4/nts/89

### PR DESCRIPTION
**Pull request by lukel97**
This fixes a miscompilation extracted from 525.x264_r, where we were failing to update the runtime VF of a VPReverseVectorPointerRecipe.

We were removing a use of VF whilst iterating over the users() iterator, which messed up the iterator in-flight and caused us to miss some recipes. This fixes it by copying the users into a SmallVector first. (make_early_inc_range doesn't work here either)

Fixes #122681
Fixes #122682

### CODE REVIEW

**Comment by lukel97** [comment]
I think this should be enough to fix #122681, confirming now.

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 1]
```diff
@@ -1603,7 +1603,7 @@ static void transformRecipestoEVLRecipes(VPlan &Plan, VPValue &EVL) {
   LLVMContext &Ctx = CanonicalIVType->getContext();
   VPValue *AllOneMask = Plan.getOrAddLiveIn(ConstantInt::getTrue(Ctx));
 
-  for (VPUser *U : Plan.getVF().users()) {
+  for (VPUser *U : SmallVector<VPUser *>(Plan.getVF().users())) {
```
Comment (fhahn) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp:1606]:
```suggestion
  for (VPUser *U : to_vector(Plan.getVF().users())) {
```

Should be possible to use `to_vector` I think

File: llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-reverse-load-store.ll [hunk 2]
```diff
@@ -249,3 +249,121 @@ loopend:
   ret void
 }
 
+define void @multiple_reverse_vector_pointer(ptr noalias %a, ptr noalias %b, ptr noalias %c, ptr noalias %d) {
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/RISCV/vectorize-force-tail-with-evl-reverse-load-store.ll:252]: might be good to add a link to the GH issue as well here

**Review by fhahn — APPROVED** [review]
LGTM, thanks!

**Comment by Mel-Chen** [comment]
Thanks!:)
I will try this patch tomorrow to see if it fixes the remaining fails in llvm test-suite.

**Comment by LiqinWeng** [comment]
I'm more curious about how you extracted miscompilation extracted from 525.x264_r,. Can you teach me?:)（
I ran the spec2017 of llvm-test-suit but there was no prompt information

**Comment by LiqinWeng** [comment]
LGTM

**Comment by lukel97** [comment]
> I'm more curious about how you extracted miscompilation extracted from 525.x264_r

I first started with 502.gcc_r because it exits much more quickly when there's a miscompile. Then I used `llvm/utils/rsp_bisect.py` comparing a non-EVL build and an EVL build:

```bash
#!/bin/bash

./build/bin/clang --target=riscv64-linux-gnu -march=rva22u64_v -O3 -fuse-ld=lld  -o 502.gcc_r @502.gcc_r.rsp

# hacky: a good build will timeout, a miscompile will exit within 15 seconds
timeout 15 qemu-riscv64 -cpu rv64,v=on,vext_spec=v1.0 ./502.gcc_r 200.c -O3 -finline-limit=50000 -o /tmp/200.c.o

if [ $? -eq 124 ]
then
        exit 0
else
        exit 1
fi

# bisect with ./llvm/utils/rsp_bisect.py --test=502.gcc_r-rsp-bisect.sh --rsp=502.gcc_r.rsp --other-rel-path=../build.rva22u64_v-evl-O3
```

This reduced the miscompile down to the changes in one file, reload1.c.

From there I diffed the output assembly and noticed that there were some loops with what looked like to be reversed pointer vectors, so I changed `VPlanTransforms::tryAddExplicitVectorLength` to bail if it encountered any recipes with VPReverseVectorPointerRecipe.

Removing VPReverseVectorPointerRecipe support fixed 502.gcc_r, so I knew it lied somewhere there.

But the diff was still quite big in 502.gcc_r, so I diffed 525.x264_r with and without VPReverseVectorPointerRecipes, which was much easier to follow. There was only one diff and it was in a loop in the function `quant_trellis_cabac`. 

There I was able to extract the bit of C from the sources that generated that loop, and after staring at the output for a while I noticed the error.

It took me a while to find this, but I hope that helps! It's much easier to debug miscompiles if they can be git-bisected back, but this wasn't the case unfortunately :)

**Comment by Mel-Chen** [comment]
> Thanks!:) I will try this patch tomorrow to see if it fixes the remaining fails in llvm test-suite.

I confirmed the remaining 4 fails in llvm test-suite are fixed by this patch.
