### PR TITLE
[lldb] Fix redundant condition in Target.cpp

### LINKED ISSUE #87244: lldb/source/Target/Target.cpp:844: function only ever returns true ?
Static analyser cppcheck says:

lldb/source/Target/Target.cpp:844:42: warning: Identical condition '!num_supported_hardware_watchpoints', second condition is always false [identicalConditionAfterEarlyExit]
  if (num_supported_hardware_watchpoints == 0) {
                                         ^

Source code is

 // If unable to determine the # of watchpoints available,
  // assume they are supported.
  if (!num_supported_hardware_watchpoints)
    return true;

  if (num_supported_hardware_watchpoints == 0) {
    error.SetErrorStringWithFormat(
        "Target supports (%u) hardware watchpoint slots.\n",
        *num_supported_hardware_watchpoints);
    return false;
  }
  return true;

The second if can never be true, so the function only ever returns true.
Suggest code rework.

### PR DESCRIPTION
**Pull request by aabhinavg**
This commit addresses issue #87244, where a redundant condition was found in the Target.cpp file. Static analyzer cppcheck flagged the issue in the Target.cpp file
fix #87244

### CODE REVIEW

File: lldb/source/Target/Target.cpp [hunk 1]
```diff
@@ -841,12 +841,14 @@ static bool CheckIfWatchpointsSupported(Target *target, Status &error) {
...
     return true;
 
-  if (num_supported_hardware_watchpoints == 0) {
-    error.SetErrorStringWithFormat(
-        "Target supports (%u) hardware watchpoint slots.\n",
-        *num_supported_hardware_watchpoints);
-    return false;
-  }
+  // If num_supported_hardware_watchpoints is zero, set an 
+  //error message and return false.
```
Comment (DavidSpickett) [inline lldb/source/Target/Target.cpp:845]: I think this function can go one of three ways:
* We can't detect h/w watch, so we assume they are supported.
* We can detect them and there are > 0, return true.
* We can detect them but there are 0 of them, set error message and return false.

The code as you've got it here will set the error message if either of the final 2 are true.

What you could do to keep the intended behaviour is simply change the if to:
```
if (*num_supported_hardware_watchpoints == 0)
```
Then there is no redundant conditon, the first if checks whether the optional is valid, the second one checks the value contained in it.

**Review by DavidSpickett — CHANGES_REQUESTED** [review]
I think this function got a bit confused when we changed the return type to an optional, thanks for taking a look at it.

**Review by DavidSpickett — APPROVED** [review]
Thanks!
