### PR TITLE
[clang] Propagate definition data to all redecls

### LINKED ISSUE #170084: [clang][modules] Cannot get layout of forward declarations with type in template scope
In https://github.com/llvm/llvm-project/pull/133057#issuecomment-3590912856, @alexfh helpfully reduced internal code which triggers a crash with the proposed changes in that PR. However, I noticed that the reduced example already fails on current `main`, which likely means that the changes expose a pre-existing bug. Converted to lit, the reproducer is the following (simplified even some more):
```c++
// RUN: rm -rf %t
// RUN: mkdir -p %t
// RUN: split-file %s %t
// RUN: cd %t

// RUN: %clang_cc1 -fmodule-name=stl -fno-cxx-modules -emit-module -fmodules -xc++ stl.cppmap -o stl.pcm
// RUN: %clang_cc1 -fmodule-name=d -fno-cxx-modules -emit-module -fmodules -fmodule-file=stl.pcm -xc++ d.cppmap -o d.pcm
// RUN: %clang_cc1 -fmodule-name=b -fno-cxx-modules -emit-module -fmodules -fmodule-file=stl.pcm -xc++ b.cppmap -o b.pcm
// RUN: %clang_cc1 -fmodule-name=a -fno-cxx-modules -emit-module -fmodules -fmodule-file=stl.pcm -fmodule-file=d.pcm -fmodule-file=b.pcm -xc++ a.cppmap -o a.pcm
// RUN: %clang_cc1 -fno-cxx-modules -fmodules -fmodule-file=a.pcm -emit-llvm -o /dev/null main.cpp

//--- a.cppmap
module "a" {
header "a.h"
}

//--- a.h
#include "b.h"
namespace {
void a(absl::set<char> c) {
  absl::set<int> b;
  c.end();
  c.contains();
}
}  // namespace

//--- b.cppmap
module "b" {
header "b.h"
}

//--- b.h
#include "c.h"
void b() { absl::set<char> x; }

//--- c.h
#include "stl.h"
namespace absl {
template <typename>
class set {
 public:
  struct iterator {
    void u() const;
  };
  iterator end() const { return {}; }
  void contains() const { end().u(); }
  pair<iterator> e();
};
}  // namespace absl

//--- d.cppmap
module "d" {
header "d.h"
}

//--- d.h
#include "c.h"
void d() { absl::set<char> x; }

//--- stl.cppmap
module "stl" {
header "stl.h"
}

//--- stl.h
#ifndef _STL_H_
#define _STL_H_
template <class>
struct pair;
#endif

//--- main.cpp
// expected-no-diagnostics
#include "c.h"
void f(absl::set<char> o) { o.contains(); }
```

git-bisect points to 91cdd35008e9ab32dffb7e401cdd7313b3461892 after which there had already been #154840, but this issue seems different. @mizvekov 

FYI @ChuanqiXu9 @vgvassilev this blocks #133057 for the moment.

### PR DESCRIPTION
**Pull request by hahnjo**
Fix the propagation added in commit 0d490ae55f to include all redecls, not only previous ones. This fixes another instance of the assertion "Cannot get layout of forward declarations" in `getASTRecordLayout()`.

Kudos to Alexander Kornienko for providing an initial version of the reproducer that I further simplified.

Fixes #170084

### CODE REVIEW

**Review by ChuanqiXu9 — APPROVED** [review]

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 1]
```diff
@@ -2107,8 +2107,8 @@ void ASTDeclMerger::MergeDefinitionData(
     auto *Def = DD.Definition;
     DD = std::move(MergeDD);
     DD.Definition = Def;
-    while ((Def = Def->getPreviousDecl()))
-      cast<CXXRecordDecl>(Def)->DefinitionData = &DD;
+    for (auto *D : Def->redecls())
+      cast<CXXRecordDecl>(D)->DefinitionData = &DD;
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTReaderDecl.cpp]: BTW, if we can have noload_redecls()? redecls() may trigger loading of all redeclarations for the RD. 

This sounds very bad. But it may not be so bad as there are already many such code right now...  so I don't block this. And I'd like to promote my post here: https://discourse.llvm.org/t/request-for-discussion-clang-a-bidirectional-decl-query-system/88945

Comment (hahnjo) [reply clang/lib/Serialization/ASTReaderDecl.cpp]: Yes, that may be a valid future development :+1:

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Review by mizvekov — APPROVED** [review]
LGTM

**Comment by alexfh** [comment]
> Thank you for the fix! I'll test this internally and will come back with the results.

I tested this patch internally and haven't found any issues.

**Comment by hahnjo** [comment]
> @hahnjo could you revert this change and reland it together with the fix?

@alexfh to be honest, I would prefer to fix the code for good, also to make progress. https://github.com/llvm/llvm-project/pull/172559 is the proposed fix preferred by me and Vassil (if I understood https://github.com/llvm/llvm-project/pull/133057#issuecomment-3617424132 correctly)
