### PR TITLE
[OpenMP][OMPT] Add OMPT callback for device data exchange 'Device-to-Device'

### LINKED ISSUE #66478: [OMPT] `data_op[_emi]` callback is not or incorrectly dispatched on device to device operations depending on vendor
## Description

Recently, LLVM has added support for parts of the OMPT interface for OpenMP target directives and functions. While testing, I noticed that there is an issue with `ompt_callback_target_data_op` and the external monitoring interface variant on NVIDIA GPUs specifically. On AMD GPUs, the dispatched callbacks are correct, but seem confusing when compared to the output of `LIBOMPTARGET_DEBUG=-1`

On NVIDIA GPUs, the callback is only dispatched when allocating / freeing memory and for operations between host and device. Device to device operations do not dispatch a callback.

On AMD GPUs, everything seems fine. However, the runtime dispatches two callbacks ( device->host, host->device ) even though the runtime reports a direct transfer between both devices.

## Reproducer

The reproducer is attached down below. In general, it uses the OMPT interface used in the LLVM tests, with slight modifications to not crash on `omp_target_[...]` function calls since they do not set `target_task_data` with a pointer. In addition, I have removed the condition that transfers from a device to the same device are invalid, since it is possible from the runtime side. 

Here's the output of the reproducer for both on a system with four NVIDIA GPUs and a system with a single AMD GPU. Unfortunately, I don't have access to a system with more than one AMD GPU right now, since ours is currently broken. For the tests with AMD GPUs, I used the recently released AOMP 18.0-0. 

**NVIDIA GPUs:**
```console
$ clang --version
clang version 18.0.0 (https://github.com/llvm/llvm-project.git 0a692b6b9632e1460f9e0e983196f2be5879acd1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ clang -fopenmp --offload-arch=sm_75 reproducer.c
$ ./a.out
Allocating memory on device
Callback Init: device_num=0 type=sm_75 device=0x55781eadec00 lookup=0x152c1dc97ca0 doc=(nil)
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000001) src=(nil) src_device_num=2 dest=(nil) dest_device_num=0 bytes=4 code=0x152c1dbb7140
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000001) src=(nil) src_device_num=2 dest=0x152bed200000 dest_device_num=0 bytes=4 code=0x152c1dbb7140
Callback Init: device_num=1 type=sm_75 device=0x55781ea47090 lookup=0x152c1dc97ca0 doc=(nil)
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000002) src=(nil) src_device_num=2 dest=(nil) dest_device_num=1 bytes=4 code=0x152c1dbb7140
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000002) src=(nil) src_device_num=2 dest=0x152bdd200000 dest_device_num=1 bytes=4 code=0x152c1dbb7140
Testing host to device
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000003) src=0x55781fe69320 src_device_num=2 dest=0x152bed200000 dest_device_num=0 bytes=4 code=0x152c1dba6305
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000003) src=0x55781fe69320 src_device_num=2 dest=0x152bed200000 dest_device_num=0 bytes=4 code=0x152c1dba6305
Testing device to device
Testing device to host
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000004) src=0x152bdd200000 src_device_num=1 dest=0x55781fe69320 dest_device_num=2 bytes=4 code=0x152c1dba64a5
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000004) src=0x152bdd200000 src_device_num=1 dest=0x55781fe69320 dest_device_num=2 bytes=4 code=0x152c1dba64a5
Checking correctness
Freeing memory on device
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000005) src=0x152bed200000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x152c1dbb753e
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000005) src=0x152bed200000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x152c1dbb753e
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000006) src=0x152bdd200000 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x152c1dbb753e
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x152c16ca67a8 (0x0) host_op_id=0x152c16ca67c0 (0x8000000000000006) src=0x152bdd200000 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x152c1dbb753e
Callback Fini: device_num=0
Callback Fini: device_num=1
```

Output with `LIBOMPTARGET_DEBUG=-1`

<details>
<summary>Click to expand</summary>

```console
$ LIBOMPTARGET_DEBUG=-1 ./a.out
Libomptarget --> Init target library!
OMPT --> Entering connectLibrary (libomp)
OMPT --> OMPT: Trying to load library libomp.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomp_connect
OMPT --> OMPT: Library connection handle = 0x14d4056b5be0
Libomptarget --> Call to omp_get_num_devices returning 0
OMPT --> Executing initializeLibrary (libomp)
OMPT --> initializeLibrary (libomp) bound lookupCallbackByCode=0x14d4056b6870
OMPT --> initializeLibrary (libomp) bound ompt_get_task_data_fn=0x14d4056b71a0
OMPT --> initializeLibrary (libomp) bound ompt_get_target_task_data_fn=0x14d4056b71e0
OMPT --> Exiting connectLibrary (libomp)
Libomptarget --> Loading RTLs...
Libomptarget --> Loading library 'libomptarget.rtl.ppc64.so'...
Libomptarget --> Unable to load library 'libomptarget.rtl.ppc64.so': libomptarget.rtl.ppc64.so: cannot open shared object file: No such file or directory!
Libomptarget --> Loading library 'libomptarget.rtl.x86_64.so'...
Libomptarget --> Unable to load library 'libomptarget.rtl.x86_64.so': libomptarget.rtl.x86_64.so: cannot open shared object file: No such file or directory!
Libomptarget --> Loading library 'libomptarget.rtl.cuda.so'...
Libomptarget --> Successfully loaded library 'libomptarget.rtl.cuda.so'!
OMPT --> OMPT: Entering connectLibrary (libomptarget)
OMPT --> OMPT: Trying to load library libomptarget.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomptarget_connect
OMPT --> OMPT: Library connection handle = 0x14d4055e1190
OMPT --> Enter ompt_libomptarget_connect
OMPT --> OMPT: Executing initializeLibrary (libomptarget)
OMPT --> OMPT: initializeLibrary (libomptarget) bound lookupCallbackByCode=0x14d4056b6870
OMPT --> Leave ompt_libomptarget_connect
OMPT --> OMPT: Exiting connectLibrary (libomptarget)
Libomptarget --> Registering RTL libomptarget.rtl.cuda.so supporting 2 devices!
Libomptarget --> Loading library 'libomptarget.rtl.aarch64.so'...
Libomptarget --> Unable to load library 'libomptarget.rtl.aarch64.so': libomptarget.rtl.aarch64.so: cannot open shared object file: No such file or directory!
Libomptarget --> Loading library 'libomptarget.rtl.amdgpu.so'...
Libomptarget --> Successfully loaded library 'libomptarget.rtl.amdgpu.so'!
TARGET AMDGPU RTL --> Unable to load library 'libhsa-runtime64.so': libhsa-runtime64.so: cannot open shared object file: No such file or directory!
TARGET AMDGPU RTL --> Failed to initialize AMDGPU's HSA library
Libomptarget --> No devices supported in this RTL
Libomptarget --> RTLs loaded!
PluginInterface --> Image is compatible with current environment: sm_75
Libomptarget --> Image 0x00005594bc4066e8 is compatible with RTL libomptarget.rtl.cuda.so!
Libomptarget --> RTL 0x00005594bdf1a530 has index 0!
Libomptarget --> Registering image 0x00005594bc4066e8 with RTL libomptarget.rtl.cuda.so!
Libomptarget --> Done registering entries!
Libomptarget --> Call to omp_get_num_devices returning 2
Allocating memory on device
Libomptarget --> Call to omp_target_alloc for device 0 requesting 4 bytes
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 0
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x5594bc4053d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x5594bc405420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x5594bc405450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
TARGET CUDA RTL --> The primary context is inactive, set its flags to CU_CTX_SCHED_BLOCKING_SYNC
Callback Init: device_num=0 type=sm_75 device=0x5594bdf8abf0 lookup=0x14d4056b5ca0 doc=(nil)
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000001) src=(nil) src_device_num=2 dest=(nil) dest_device_num=0 bytes=4 code=0x14d4055d5140
PluginInterface --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Cannot find a node in the FreeLists. Allocate on device.
PluginInterface --> Node address 0x00005594bea7a260, target pointer 0x000014d3d5200000, size 4
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000001) src=(nil) src_device_num=2 dest=0x14d3d5200000 dest_device_num=0 bytes=4 code=0x14d4055d5140
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_alloc returns device ptr 0x000014d3d5200000
Libomptarget --> Call to omp_target_alloc for device 1 requesting 4 bytes
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 1 is ready.
Libomptarget --> Is the device 1 (local ID 1) initialized? 0
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x5594bc4053d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x5594bc405420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x5594bc405450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
TARGET CUDA RTL --> The primary context is inactive, set its flags to CU_CTX_SCHED_BLOCKING_SYNC
Callback Init: device_num=1 type=sm_75 device=0x5594bdef3090 lookup=0x14d4056b5ca0 doc=(nil)
Libomptarget --> Device 1 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000002) src=(nil) src_device_num=2 dest=(nil) dest_device_num=1 bytes=4 code=0x14d4055d5140
PluginInterface --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Cannot find a node in the FreeLists. Allocate on device.
PluginInterface --> Node address 0x00005594bf393d00, target pointer 0x000014d3c5200000, size 4
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000002) src=(nil) src_device_num=2 dest=0x14d3c5200000 dest_device_num=1 bytes=4 code=0x14d4055d5140
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_alloc returns device ptr 0x000014d3c5200000
Testing host to device
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_target_memcpy, dst device 0, src device 2, dst addr 0x000014d3d5200000, src addr 0x00005594bf3152e0, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> copy from host to device
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000003) src=0x5594bf3152e0 src_device_num=2 dest=0x14d3d5200000 dest_device_num=0 bytes=4 code=0x14d4055c4305
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000003) src=0x5594bf3152e0 src_device_num=2 dest=0x14d3d5200000 dest_device_num=0 bytes=4 code=0x14d4055c4305
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_memcpy returns 0
Testing device to device
Libomptarget --> Call to omp_target_memcpy, dst device 1, src device 0, dst addr 0x000014d3c5200000, src addr 0x000014d3d5200000, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 1 is ready.
Libomptarget --> Is the device 1 (local ID 1) initialized? 1
Libomptarget --> Device 1 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> copy from device to device
Testing device to host
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_target_memcpy, dst device 2, src device 1, dst addr 0x00005594bf3152e0, src addr 0x000014d3c5200000, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 1 is ready.
Libomptarget --> Is the device 1 (local ID 1) initialized? 1
Libomptarget --> Device 1 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> copy from device to host
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000004) src=0x14d3c5200000 src_device_num=1 dest=0x5594bf3152e0 dest_device_num=2 bytes=4 code=0x14d4055c44a5
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000004) src=0x14d3c5200000 src_device_num=1 dest=0x5594bf3152e0 dest_device_num=2 bytes=4 code=0x14d4055c44a5
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_memcpy returns 0
Checking correctness
Freeing memory on device
Libomptarget --> Call to omp_target_free for device 0 and address 0x000014d3d5200000
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000005) src=0x14d3d5200000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x14d4055d553e
PluginInterface --> MemoryManagerTy::free: target memory 0x000014d3d5200000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Found its node 0x00005594bea7a260. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000005) src=0x14d3d5200000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x14d4055d553e
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_free deallocated device ptr
Libomptarget --> Call to omp_target_free for device 1 and address 0x000014d3c5200000
Libomptarget --> Call to omp_get_num_devices returning 2
Libomptarget --> Call to omp_get_initial_device returning 2
Libomptarget --> Checking whether device 1 is ready.
Libomptarget --> Is the device 1 (local ID 1) initialized? 1
Libomptarget --> Device 1 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000006) src=0x14d3c5200000 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x14d4055d553e
PluginInterface --> MemoryManagerTy::free: target memory 0x000014d3c5200000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Found its node 0x00005594bf393d00. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x14d3fe6c47a8 (0x0) host_op_id=0x14d3fe6c47c0 (0x8000000000000006) src=0x14d3c5200000 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x14d4055d553e
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_free deallocated device ptr
Libomptarget --> Unloading target library!
Libomptarget --> Unregistered image 0x00005594bc4066e8 from RTL 0x00005594bdf1a530!
Libomptarget --> Done unregistering images!
Libomptarget --> Removing translation table for descriptor 0x00005594bc406658
Libomptarget --> Done unregistering library!
Libomptarget --> Deinit target library!
OMPT --> Executing finalizeLibrary (libomp)
OMPT --> OMPT: Executing finalizeLibrary (libomptarget)
Callback Fini: device_num=0
Callback Fini: device_num=1
```
    
</details>

As shown in the output, transfers between devices do not dispatch a callback. The debug flags show that there's a data transfer happening. 

---

**AMD GPUs:**

```console
$ amdclang --version
AOMP_STANDALONE_18.0-0 clang version 18.0.0 (https://github.com/radeonopencompute/llvm-project def7057717b5098f6a9f773fc6e7b2a7f59cdd50)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/aomp_18.0-0/bin
$ amdclang -fopenmp --offload-arch=gfx908 reproducer.c
$ ./a.out
Allocating memory on device
Callback Init: device_num=0 type=gfx908 device=0x149e260 lookup=0x7f0e69d241c0 doc=(nil)
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000001) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x7f0e6cc62dde
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000001) src=(nil) src_device_num=1 dest=0x7f0d67020000 dest_device_num=0 bytes=4 code=0x7f0e6cc62dde
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000002) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x7f0e6cc62dde
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000002) src=(nil) src_device_num=1 dest=0x7f0d67021000 dest_device_num=0 bytes=4 code=0x7f0e6cc62dde
Testing host to device
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000003) src=0x7f0d67020000 src_device_num=1 dest=0x14a59e0 dest_device_num=0 bytes=4 code=0x7f0e6cc5872c
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000003) src=0x7f0d67020000 src_device_num=1 dest=0x14a59e0 dest_device_num=0 bytes=4 code=0x7f0e6cc5872c
Testing device to device
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000004) src=0x7f0d67020000 src_device_num=0 dest=0x15a6130 dest_device_num=1 bytes=4 code=0x7f0e6cc59cd0
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000004) src=0x7f0d67020000 src_device_num=0 dest=0x15a6130 dest_device_num=1 bytes=4 code=0x7f0e6cc59cd0
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000005) src=0x7f0d67021000 src_device_num=1 dest=0x15a6130 dest_device_num=0 bytes=4 code=0x7f0e6cc5872c
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000005) src=0x7f0d67021000 src_device_num=1 dest=0x15a6130 dest_device_num=0 bytes=4 code=0x7f0e6cc5872c
Testing device to host
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000006) src=0x7f0d67021000 src_device_num=0 dest=0x14a59e0 dest_device_num=1 bytes=4 code=0x7f0e6cc59cd0
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000006) src=0x7f0d67021000 src_device_num=0 dest=0x14a59e0 dest_device_num=1 bytes=4 code=0x7f0e6cc59cd0
Checking correctness
Freeing memory on device
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000007) src=0x7f0d67020000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f0e6cc59482
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000007) src=0x7f0d67020000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f0e6cc59482
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000008) src=0x7f0d67021000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f0e6cc59482
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7f0e6ca9dcf8 (0x0) host_op_id=0x7f0e6ca9dd10 (0x8000000000000008) src=0x7f0d67021000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f0e6cc59482
Callback Fini: device_num=0
```

Output with `LIBOMPTARGET_DEBUG=-1`

<details>
<summary>Click to expand</summary>

```console
$ LIBOMPTARGET_DEBUG=-1 ./a.out
Libomptarget --> Init target library!
OMPT --> OMPT: Entering connectLibrary (libomp)
OMPT --> OMPT: Trying to load library libomp.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomp_connect
OMPT --> OMPT: Library connection handle = 0x7f582ce6eda0
Libomptarget --> Call to omp_get_num_devices returning 0
OMPT --> OMPT: Executing initializeLibrary (libomp)
OMPT --> OMPT: initializeLibrary (libomp) bound lookupCallbackByCode=0x7f582ce6fa50
OMPT --> OMPT: initializeLibrary (libomp) bound ompt_get_task_data_fn=0x7f582ce70380
OMPT --> OMPT: initializeLibrary (libomp) bound ompt_get_target_task_data_fn=0x7f582ce703c0
OMPT --> OMPT: initializeLibrary (libomp) bound ompt_set_frame_enter_fn=0x7f582ce703e0
OMPT --> OMPT: Exiting connectLibrary (libomp)
Libomptarget --> Loading RTLs...
Libomptarget --> Loading library 'libomptarget.rtl.amdgpu.so'...
Libomptarget --> Successfully loaded library 'libomptarget.rtl.amdgpu.so'!
OMPT --> OMPT: Entering connectLibrary (libomptarget)
OMPT --> OMPT: Trying to load library libomptarget.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomptarget_connect
OMPT --> OMPT: Library connection handle = 0x7f582cd2f340
OMPT --> OMPT: Enter ompt_libomptarget_connect
OMPT --> OMPT: Executing initializeLibrary (libomptarget)
OMPT --> OMPT: libomptarget_get_target_info = (nil)
OMPT --> OMPT: initializeLibrary (libomptarget) bound lookupCallbackByCode=0x7f582ce6fa50
OMPT --> OMPT: Leave ompt_libomptarget_connect
OMPT --> OMPT: Exiting connectLibrary (libomptarget)
Libomptarget --> Registering RTL libomptarget.rtl.amdgpu.so supporting 1 devices!
Libomptarget --> Loading library 'libomptarget.rtl.cuda.so'...
Libomptarget --> Successfully loaded library 'libomptarget.rtl.cuda.so'!
TARGET CUDA RTL --> Unable to load library 'libcuda.so': libcuda.so: cannot open shared object file: No such file or directory!
TARGET CUDA RTL --> Failed to load CUDA shared library
Libomptarget --> No devices supported in this RTL
Libomptarget --> Loading library 'libomptarget.rtl.x86_64.so'...
Libomptarget --> Successfully loaded library 'libomptarget.rtl.x86_64.so'!
OMPT --> OMPT: Entering connectLibrary (libomptarget)
OMPT --> OMPT: Trying to load library libomptarget.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomptarget_connect
OMPT --> OMPT: Library connection handle = 0x7f582cd2f340
OMPT --> OMPT: Enter ompt_libomptarget_connect
OMPT --> OMPT: Executing initializeLibrary (libomptarget)
OMPT --> OMPT: libomptarget_get_target_info = (nil)
OMPT --> OMPT: initializeLibrary (libomptarget) bound lookupCallbackByCode=0x7f582ce6fa50
OMPT --> OMPT: Leave ompt_libomptarget_connect
OMPT --> OMPT: Exiting connectLibrary (libomptarget)
Libomptarget --> Registering RTL libomptarget.rtl.x86_64.so supporting 4 devices!
Libomptarget --> Loading library 'libomptarget.rtl.ppc64.so'...
Libomptarget --> Unable to load library 'libomptarget.rtl.ppc64.so': libomptarget.rtl.ppc64.so: cannot open shared object file: No such file or directory!
Libomptarget --> Loading library 'libomptarget.rtl.aarch64.so'...
Libomptarget --> Unable to load library 'libomptarget.rtl.aarch64.so': libomptarget.rtl.aarch64.so: cannot open shared object file: No such file or directory!
Libomptarget --> RTLs loaded!
TARGET AMDGPU RTL --> Compatible: Target IDs are compatible 	[Image: gfx908]	:	[Env: gfx908:sramecc+:xnack-]
PluginInterface --> Image is compatible with current environment: gfx908
Libomptarget --> Image 0x0000000000200378 is compatible with RTL libomptarget.rtl.amdgpu.so!
Libomptarget --> RTL 0x00000000013c0bc0 has index 0!
Libomptarget --> Registering image 0x0000000000200378 with RTL libomptarget.rtl.amdgpu.so!
Libomptarget --> Done registering entries!
Libomptarget --> Call to omp_get_num_devices returning 1
Allocating memory on device
Libomptarget --> Call to omp_target_alloc for device 0 requesting 4 bytes
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 0
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x203200
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x203250
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x203280
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
PluginInterface --> OMPT: device tracing fn bound ompt_set_trace_ompt=0x7f5829f242e0
PluginInterface --> OMPT: device tracing fn bound ompt_start_trace=0x7f5829f24480
PluginInterface --> OMPT: device tracing fn bound ompt_flush_trace=0x7f5829f24640
PluginInterface --> OMPT: device tracing fn bound ompt_stop_trace=0x7f5829f247d0
PluginInterface --> OMPT: device tracing fn bound ompt_advance_buffer_cursor=0x7f5829f24970
PluginInterface --> OMPT: device tracing fn bound ompt_get_record_ompt=0x7f5829f24a60
PluginInterface --> OMPT: device tracing fn bound ompt_get_device_time=0x7f5829f24a70
PluginInterface --> OMPT: device tracing fn bound ompt_get_record_type=0x7f5829f24b40
PluginInterface --> OMPT: device tracing fn bound ompt_translate_time=0x7f5829f24c10
TARGET AMDGPU RTL --> Using a maximum of 4 HSA queues
TARGET AMDGPU RTL --> OMPT: Translate time Slope: 0.000000 Offset: 1692458767.777029
Callback Init: device_num=0 type=gfx908 device=0x15fc270 lookup=0x7f5829f241c0 doc=(nil)
Libomptarget --> Initialization returned 0
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000001) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x7f582cd23dde
TARGET AMDGPU RTL --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
TARGET AMDGPU RTL --> findBucket: Size 4 is floored to 4.
TARGET AMDGPU RTL --> findBucket: Size 4 goes to bucket 0
TARGET AMDGPU RTL --> Cannot find a node in the FreeLists. Allocate on device.
TARGET AMDGPU RTL --> Node address 0x00000000016038f0, target pointer 0x00007f5727220000, size 4
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000001) src=(nil) src_device_num=1 dest=0x7f5727220000 dest_device_num=0 bytes=4 code=0x7f582cd23dde
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_alloc returns device ptr 0x00007f5727220000
Libomptarget --> Call to omp_target_alloc for device 0 requesting 4 bytes
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000002) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x7f582cd23dde
TARGET AMDGPU RTL --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
TARGET AMDGPU RTL --> findBucket: Size 4 is floored to 4.
TARGET AMDGPU RTL --> findBucket: Size 4 goes to bucket 0
TARGET AMDGPU RTL --> Cannot find a node in the FreeLists. Allocate on device.
TARGET AMDGPU RTL --> Node address 0x0000000001603920, target pointer 0x00007f5727221000, size 4
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000002) src=(nil) src_device_num=1 dest=0x7f5727221000 dest_device_num=0 bytes=4 code=0x7f582cd23dde
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_alloc returns device ptr 0x00007f5727221000
Testing host to device
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_target_memcpy, dst device 0, src device 1, dst addr 0x00007f5727220000, src addr 0x00000000016039f0, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> copy from host to device
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000003) src=0x7f5727220000 src_device_num=1 dest=0x16039f0 dest_device_num=0 bytes=4 code=0x7f582cd1972c
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000003) src=0x7f5727220000 src_device_num=1 dest=0x16039f0 dest_device_num=0 bytes=4 code=0x7f582cd1972c
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_memcpy returns 0
Testing device to device
Libomptarget --> Call to omp_target_memcpy, dst device 0, src device 0, dst addr 0x00007f5727221000, src addr 0x00007f5727220000, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> copy from device to device
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000004) src=0x7f5727220000 src_device_num=0 dest=0x1704140 dest_device_num=1 bytes=4 code=0x7f582cd1acd0
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000004) src=0x7f5727220000 src_device_num=0 dest=0x1704140 dest_device_num=1 bytes=4 code=0x7f582cd1acd0
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000005) src=0x7f5727221000 src_device_num=1 dest=0x1704140 dest_device_num=0 bytes=4 code=0x7f582cd1972c
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000005) src=0x7f5727221000 src_device_num=1 dest=0x1704140 dest_device_num=0 bytes=4 code=0x7f582cd1972c
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_memcpy returns 0
Testing device to host
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_target_memcpy, dst device 1, src device 0, dst addr 0x00000000016039f0, src addr 0x00007f5727221000, dst offset 0, src offset 0, length 4
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> copy from device to host
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000006) src=0x7f5727221000 src_device_num=0 dest=0x16039f0 dest_device_num=1 bytes=4 code=0x7f582cd1acd0
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000006) src=0x7f5727221000 src_device_num=0 dest=0x16039f0 dest_device_num=1 bytes=4 code=0x7f582cd1acd0
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_memcpy returns 0
Checking correctness
Freeing memory on device
Libomptarget --> Call to omp_target_free for device 0 and address 0x00007f5727220000
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000007) src=0x7f5727220000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f582cd1a482
TARGET AMDGPU RTL --> MemoryManagerTy::free: target memory 0x00007f5727220000.
TARGET AMDGPU RTL --> findBucket: Size 4 is floored to 4.
TARGET AMDGPU RTL --> findBucket: Size 4 goes to bucket 0
TARGET AMDGPU RTL --> Found its node 0x00000000016038f0. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000007) src=0x7f5727220000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f582cd1a482
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_free deallocated device ptr
Libomptarget --> Call to omp_target_free for device 0 and address 0x00007f5727221000
Libomptarget --> Call to omp_get_num_devices returning 1
Libomptarget --> Call to omp_get_initial_device returning 1
Libomptarget --> Checking whether device 0 is ready.
Libomptarget --> Is the device 0 (local ID 0) initialized? 1
Libomptarget --> Device 0 is ready to use.
OMPT --> in ompt_target_region_begin (TargetRegionOpId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000008) src=0x7f5727221000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f582cd1a482
TARGET AMDGPU RTL --> MemoryManagerTy::free: target memory 0x00007f5727221000.
TARGET AMDGPU RTL --> findBucket: Size 4 is floored to 4.
TARGET AMDGPU RTL --> findBucket: Size 4 goes to bucket 0
TARGET AMDGPU RTL --> Found its node 0x0000000001603920. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7f582cc45cf8 (0x0) host_op_id=0x7f582cc45d10 (0x8000000000000008) src=0x7f5727221000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x7f582cd1a482
OMPT --> in ompt_target_region_end (TargetRegionOpId = 0)
Libomptarget --> omp_target_free deallocated device ptr
Libomptarget --> Unloading target library!
Libomptarget --> Unregistered image 0x0000000000200378 from RTL 0x00000000013c0bc0!
Libomptarget --> Done unregistering images!
Libomptarget --> Removing translation table for descriptor 0x0000000000201cc0
Libomptarget --> Done unregistering library!
Libomptarget --> Deinit target library!
OMPT --> OMPT: Executing finalizeLibrary (libomp)
OMPT --> OMPT: Executing finalizeLibrary (libomptarget)
OMPT --> OMPT: Executing finalizeLibrary (libomptarget)
Callback Fini: device_num=0
```
    
</details>

The interesting thing here is the line `Libomptarget --> copy from device to device` which suggests a direct transfer between devices. This is not visible in the OMPT callbacks.

## What would I expect?

For NVIDIA GPUs, we should see the same results as for the AMD GPUs. Regarding the AMD GPUs, I would expect to see a direct transfer between GPUs reported by the OMPT interface. However, this assumes that this is in fact the case. `LIBOMPTARGET_DEBUG` seems to indicate that, but I'm not able to verify it right now. 

As for AOMP 18.0-0, this probably also affects the device tracing interface as well since the trace records are based on the dispatched callbacks.

## Attachements
- Reproducer code: [reproducer.zip](https://github.com/llvm/llvm-project/files/12618521/reproducer.zip)

### PR DESCRIPTION
**Pull request by mhalk**
Since there's no `ompt_target_data_transfer_tofrom_device` (within ompt_target_data_op_t enum) or something other that conveys the meaning of inter-device data exchange we decided to indicate a Device-to-Device transfer by using: optype == ompt_target_data_transfer_from_device (=3)

Hence, a device transfer may be identified e.g. by checking for: (optype == 3) &&
(src_device_num < omp_get_num_devices()) &&
(dest_device_num < omp_get_num_devices())

Fixes: #66478

### CODE REVIEW

**Comment by mhalk** [comment]
Removed assertions w.r.t. `target_task_data` as well as `src_addr` & `dest_addr` as these may have various values depending on the usage. For example `omp_target_memcpy` will cause `target_task_data=(nil)` as well as both addresses to be `(nil)`, this makes checking cumbersome and the tests brittle.
Hence, in coordination with @dhruvachak, we decided to remove the corresponding assertion.

**Comment by jplehr** [comment]
> Since there's no `ompt_target_data_transfer_tofrom_device` (within ompt_target_data_op_t enum) or something other that conveys the meaning of inter-device data exchange we decided to indicate a Device-to-Device transfer by using: optype == ompt_target_data_transfer_from_device (=3)
> 
> Hence, a device transfer may be identified e.g. by checking for: (optype == 3) && (src_device_num < omp_get_num_devices()) && (dest_device_num < omp_get_num_devices())
> 
> Fixes: #66478

Do we have a place to document this decision other than this PR / commit message?

**Comment by Thyre** [comment]
Can confirm that this pull request also works for NVIDIA GPUs, though I weren't able to test it with multiple accelerators due to build issues on our HPC machines. 

```console
$ clang --version
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 5fd8e50feff94dac7e741b07c956622b7c25bc6a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jreuter/Projects/Compilers/llvm-project/_build/_install/bin
$ clang -fopenmp --offload-arch=native reproducer.c
$ ./a.out
Callback Init: device_num=0 type=sm_75 device=0x55d75ee03a40 lookup=0x7fb3518ebb50 doc=(nil)
Allocating memory on device
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000001) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x55d75ce76853
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000001) src=(nil) src_device_num=1 dest=0x7fb325a00000 dest_device_num=0 bytes=4 code=0x55d75ce76853
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000002) src=(nil) src_device_num=1 dest=(nil) dest_device_num=0 bytes=4 code=0x55d75ce76864
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000002) src=(nil) src_device_num=1 dest=0x7fb325a00200 dest_device_num=0 bytes=4 code=0x55d75ce76864
Testing host to device
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000003) src=0x55d75f66b200 src_device_num=1 dest=0x7fb325a00000 dest_device_num=0 bytes=4 code=0x55d75ce768ca
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000003) src=0x55d75f66b200 src_device_num=1 dest=0x7fb325a00000 dest_device_num=0 bytes=4 code=0x55d75ce768ca
Testing device to device
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000004) src=0x7fb325a00000 src_device_num=0 dest=0x7fb325a00200 dest_device_num=0 bytes=4 code=0x55d75ce768fc
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000004) src=0x7fb325a00000 src_device_num=0 dest=0x7fb325a00200 dest_device_num=0 bytes=4 code=0x55d75ce768fc
Testing device to host
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000005) src=0x7fb325a00200 src_device_num=0 dest=0x55d75f66b200 dest_device_num=1 bytes=4 code=0x55d75ce76942
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000005) src=0x7fb325a00200 src_device_num=0 dest=0x55d75f66b200 dest_device_num=1 bytes=4 code=0x55d75ce76942
Checking correctness
Freeing memory on device
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000006) src=0x7fb325a00000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55d75ce769a4
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000006) src=0x7fb325a00000 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55d75ce769a4
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000007) src=0x7fb325a00200 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55d75ce769b0
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3516787d0 (0x0) host_op_id=0x7fb3516787c8 (0x8000000000000007) src=0x7fb325a00200 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55d75ce769b0
Callback Fini: device_num=0
```

x86_64 still reports two transfers even though `LIBOMPTARGET_DEBUG` shows `omptarget --> copy from device to device`.

```console
$ clang --version
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 5fd8e50feff94dac7e741b07c956622b7c25bc6a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jreuter/Projects/Compilers/llvm-project/_build/_install/bin
$ clang -fopenmp -fopenmp-targets=x86_64 reproducer.c
$ ./a.out
Callback Init: device_num=0 type=generic-64bit device=0x5644e0820950 lookup=0x7fb3d245bb50 doc=(nil)
Callback Init: device_num=1 type=generic-64bit device=0x5644e0821380 lookup=0x7fb3d245bb50 doc=(nil)
Callback Init: device_num=2 type=generic-64bit device=0x5644e08219a0 lookup=0x7fb3d245bb50 doc=(nil)
Callback Init: device_num=3 type=generic-64bit device=0x5644e08221d0 lookup=0x7fb3d245bb50 doc=(nil)
Allocating memory on device
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000001) src=(nil) src_device_num=4 dest=(nil) dest_device_num=0 bytes=4 code=0x5644dee0c853
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000001) src=(nil) src_device_num=4 dest=0x5644e0820790 dest_device_num=0 bytes=4 code=0x5644dee0c853
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000002) src=(nil) src_device_num=4 dest=(nil) dest_device_num=1 bytes=4 code=0x5644dee0c864
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000002) src=(nil) src_device_num=4 dest=0x5644e07fafb0 dest_device_num=1 bytes=4 code=0x5644dee0c864
Testing host to device
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000003) src=0x5644e081b990 src_device_num=4 dest=0x5644e0820790 dest_device_num=0 bytes=4 code=0x5644dee0c8ca
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000003) src=0x5644e081b990 src_device_num=4 dest=0x5644e0820790 dest_device_num=0 bytes=4 code=0x5644dee0c8ca
Testing device to device
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000004) src=0x5644e0820790 src_device_num=0 dest=0x5644e0820880 dest_device_num=4 bytes=4 code=0x5644dee0c8fc
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000004) src=0x5644e0820790 src_device_num=0 dest=0x5644e0820880 dest_device_num=4 bytes=4 code=0x5644dee0c8fc
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000005) src=0x5644e0820880 src_device_num=4 dest=0x5644e07fafb0 dest_device_num=1 bytes=4 code=0x5644dee0c8fc
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000005) src=0x5644e0820880 src_device_num=4 dest=0x5644e07fafb0 dest_device_num=1 bytes=4 code=0x5644dee0c8fc
Testing device to host
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000006) src=0x5644e07fafb0 src_device_num=1 dest=0x5644e081b990 dest_device_num=4 bytes=4 code=0x5644dee0c942
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000006) src=0x5644e07fafb0 src_device_num=1 dest=0x5644e081b990 dest_device_num=4 bytes=4 code=0x5644dee0c942
Checking correctness
Freeing memory on device
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000007) src=0x5644e0820790 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x5644dee0c9a4
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000007) src=0x5644e0820790 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x5644dee0c9a4
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000008) src=0x5644e07fafb0 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x5644dee0c9b0
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7fb3d22367d0 (0x0) host_op_id=0x7fb3d22367c8 (0x8000000000000008) src=0x5644e07fafb0 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x5644dee0c9b0
Callback Fini: device_num=0
Callback Fini: device_num=1
Callback Fini: device_num=2
Callback Fini: device_num=3
```

<details>
<summary>Click to expand output with LIBOMPTARGET_DEBUG</summary>

```
omptarget --> Init offload library!
OMPT --> Entering connectLibrary (libomp)
OMPT --> OMPT: Trying to load library libomp.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomp_connect
OMPT --> OMPT: Library connection handle = 0x7efc564dca90
omptarget --> Call to omp_get_num_devices returning 0
OMPT --> Executing initializeLibrary (libomp)
OMPT --> initializeLibrary (libomp) bound lookupCallbackByCode=0x7efc564dd710
OMPT --> initializeLibrary (libomp) bound ompt_get_task_data_fn=0x7efc564de020
OMPT --> initializeLibrary (libomp) bound ompt_get_target_task_data_fn=0x7efc564de060
OMPT --> Exiting connectLibrary (libomp)
omptarget --> Loading RTLs...
omptarget --> Attempting to load library 'libomptarget.rtl.x86_64.so'...
omptarget --> Successfully loaded library 'libomptarget.rtl.x86_64.so'!
OMPT --> OMPT: Entering connectLibrary (libomptarget)
OMPT --> OMPT: Trying to load library libomptarget.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomptarget_connect
OMPT --> OMPT: Library connection handle = 0x7efc5640cac0
OMPT --> Enter ompt_libomptarget_connect
OMPT --> OMPT: Executing initializeLibrary (libomptarget)
OMPT --> OMPT: initializeLibrary (libomptarget) bound lookupCallbackByCode=0x7efc564dd710
OMPT --> Leave ompt_libomptarget_connect
OMPT --> OMPT: Exiting connectLibrary (libomptarget)
omptarget --> Registered 'libomptarget.rtl.x86_64.so' with 4 plugin visible devices!
omptarget --> Attempting to load library 'libomptarget.rtl.cuda.so'...
omptarget --> Successfully loaded library 'libomptarget.rtl.cuda.so'!
TARGET CUDA RTL --> Implementing cuInit with dlsym(cuInit) -> 0x7efc4e8c1ec0
TARGET CUDA RTL --> Implementing cuCtxGetDevice with dlsym(cuCtxGetDevice) -> 0x7efc4e8c9b50
TARGET CUDA RTL --> Implementing cuDeviceGet with dlsym(cuDeviceGet) -> 0x7efc4e8c1f00
TARGET CUDA RTL --> Implementing cuDeviceGetAttribute with dlsym(cuDeviceGetAttribute) -> 0x7efc4e8c2000
TARGET CUDA RTL --> Implementing cuDeviceGetCount with dlsym(cuDeviceGetCount) -> 0x7efc4e8c1f20
TARGET CUDA RTL --> Implementing cuFuncGetAttribute with dlsym(cuFuncGetAttribute) -> 0x7efc4e8f6f90
TARGET CUDA RTL --> Implementing cuDeviceGetName with dlsym(cuDeviceGetName) -> 0x7efc4e8c1f40
TARGET CUDA RTL --> Implementing cuDeviceTotalMem with dlsym(cuDeviceTotalMem) -> 0x7efc4e918b80
TARGET CUDA RTL --> Implementing cuDriverGetVersion with dlsym(cuDriverGetVersion) -> 0x7efc4e8c1ee0
TARGET CUDA RTL --> Implementing cuGetErrorString with dlsym(cuGetErrorString) -> 0x7efc4e8c1e80
TARGET CUDA RTL --> Implementing cuLaunchKernel with dlsym(cuLaunchKernel) -> 0x7efc4e92f100
TARGET CUDA RTL --> Implementing cuMemAlloc with dlsym(cuMemAlloc_v2) -> 0x7efc4e8d4f80
TARGET CUDA RTL --> Implementing cuMemAllocHost with dlsym(cuMemAllocHost) -> 0x7efc4e918c80
TARGET CUDA RTL --> Implementing cuMemAllocManaged with dlsym(cuMemAllocManaged) -> 0x7efc4e8d50a0
TARGET CUDA RTL --> Implementing cuMemAllocAsync with dlsym(cuMemAllocAsync) -> 0x7efc4e93a9c0
TARGET CUDA RTL --> Implementing cuMemcpyDtoDAsync with dlsym(cuMemcpyDtoDAsync_v2) -> 0x7efc4e9241c0
TARGET CUDA RTL --> Implementing cuMemcpyDtoH with dlsym(cuMemcpyDtoH_v2) -> 0x7efc4e924000
TARGET CUDA RTL --> Implementing cuMemcpyDtoHAsync with dlsym(cuMemcpyDtoHAsync_v2) -> 0x7efc4e9241a0
TARGET CUDA RTL --> Implementing cuMemcpyHtoD with dlsym(cuMemcpyHtoD_v2) -> 0x7efc4e923fe0
TARGET CUDA RTL --> Implementing cuMemcpyHtoDAsync with dlsym(cuMemcpyHtoDAsync_v2) -> 0x7efc4e924180
TARGET CUDA RTL --> Implementing cuMemFree with dlsym(cuMemFree_v2) -> 0x7efc4e8d4fc0
TARGET CUDA RTL --> Implementing cuMemFreeHost with dlsym(cuMemFreeHost) -> 0x7efc4e8d5020
TARGET CUDA RTL --> Implementing cuMemFreeAsync with dlsym(cuMemFreeAsync) -> 0x7efc4e93a9a0
TARGET CUDA RTL --> Implementing cuModuleGetFunction with dlsym(cuModuleGetFunction) -> 0x7efc4e8c9e30
TARGET CUDA RTL --> Implementing cuModuleGetGlobal with dlsym(cuModuleGetGlobal_v2) -> 0x7efc4e8c9e50
TARGET CUDA RTL --> Implementing cuModuleUnload with dlsym(cuModuleUnload) -> 0x7efc4e8c9df0
TARGET CUDA RTL --> Implementing cuStreamCreate with dlsym(cuStreamCreate) -> 0x7efc4e8ebc60
TARGET CUDA RTL --> Implementing cuStreamDestroy with dlsym(cuStreamDestroy_v2) -> 0x7efc4e8ebe80
TARGET CUDA RTL --> Implementing cuStreamSynchronize with dlsym(cuStreamSynchronize) -> 0x7efc4e92f0a0
TARGET CUDA RTL --> Implementing cuStreamQuery with dlsym(cuStreamQuery) -> 0x7efc4e924560
TARGET CUDA RTL --> Implementing cuCtxSetCurrent with dlsym(cuCtxSetCurrent) -> 0x7efc4e8c9b10
TARGET CUDA RTL --> Implementing cuDevicePrimaryCtxRelease with dlsym(cuDevicePrimaryCtxRelease_v2) -> 0x7efc4e8c99f0
TARGET CUDA RTL --> Implementing cuDevicePrimaryCtxGetState with dlsym(cuDevicePrimaryCtxGetState) -> 0x7efc4e8c9a30
TARGET CUDA RTL --> Implementing cuDevicePrimaryCtxSetFlags with dlsym(cuDevicePrimaryCtxSetFlags_v2) -> 0x7efc4e8c9a10
TARGET CUDA RTL --> Implementing cuDevicePrimaryCtxRetain with dlsym(cuDevicePrimaryCtxRetain) -> 0x7efc4e8c99d0
TARGET CUDA RTL --> Implementing cuModuleLoadDataEx with dlsym(cuModuleLoadDataEx) -> 0x7efc4e8c9db0
TARGET CUDA RTL --> Implementing cuDeviceCanAccessPeer with dlsym(cuDeviceCanAccessPeer) -> 0x7efc4e90d8c0
TARGET CUDA RTL --> Implementing cuCtxEnablePeerAccess with dlsym(cuCtxEnablePeerAccess) -> 0x7efc4e90d8e0
TARGET CUDA RTL --> Implementing cuMemcpyPeerAsync with dlsym(cuMemcpyPeerAsync) -> 0x7efc4e924350
TARGET CUDA RTL --> Implementing cuCtxGetLimit with dlsym(cuCtxGetLimit) -> 0x7efc4e8c9c10
TARGET CUDA RTL --> Implementing cuCtxSetLimit with dlsym(cuCtxSetLimit) -> 0x7efc4e8c9bf0
TARGET CUDA RTL --> Implementing cuEventCreate with dlsym(cuEventCreate) -> 0x7efc4e8ebf00
TARGET CUDA RTL --> Implementing cuEventRecord with dlsym(cuEventRecord) -> 0x7efc4e92f0c0
TARGET CUDA RTL --> Implementing cuStreamWaitEvent with dlsym(cuStreamWaitEvent) -> 0x7efc4e924500
TARGET CUDA RTL --> Implementing cuEventSynchronize with dlsym(cuEventSynchronize) -> 0x7efc4e8ebf80
TARGET CUDA RTL --> Implementing cuEventDestroy with dlsym(cuEventDestroy) -> 0x7efc4e923f60
OMPT --> OMPT: Entering connectLibrary (libomptarget)
OMPT --> OMPT: Trying to load library libomptarget.so
OMPT --> OMPT: Trying to get address of connection routine ompt_libomptarget_connect
OMPT --> OMPT: Library connection handle = 0x7efc5640cac0
OMPT --> Enter ompt_libomptarget_connect
OMPT --> OMPT: Executing initializeLibrary (libomptarget)
OMPT --> OMPT: initializeLibrary (libomptarget) bound lookupCallbackByCode=0x7efc564dd710
OMPT --> Leave ompt_libomptarget_connect
OMPT --> OMPT: Exiting connectLibrary (libomptarget)
omptarget --> Registered 'libomptarget.rtl.cuda.so' with 1 plugin visible devices!
omptarget --> Attempting to load library 'libomptarget.rtl.amdgpu.so'...
omptarget --> Successfully loaded library 'libomptarget.rtl.amdgpu.so'!
TARGET AMDGPU RTL --> Unable to load library 'libhsa-runtime64.so': libhsa-runtime64.so: cannot open shared object file: No such file or directory!
TARGET AMDGPU RTL --> Failed to initialize AMDGPU's HSA library
omptarget --> No devices supported in this RTL
omptarget --> RTLs loaded!
omptarget --> Image 0x000055c1f4f146e0 is compatible with RTL libomptarget.rtl.x86_64.so!
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x55c1f4f133d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x55c1f4f13420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x55c1f4f13450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
Callback Init: device_num=0 type=generic-64bit device=0x55c1f5997a30 lookup=0x7efc564dcb50 doc=(nil)
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x55c1f4f133d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x55c1f4f13420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x55c1f4f13450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
Callback Init: device_num=1 type=generic-64bit device=0x55c1f5998460 lookup=0x7efc564dcb50 doc=(nil)
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x55c1f4f133d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x55c1f4f13420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x55c1f4f13450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
Callback Init: device_num=2 type=generic-64bit device=0x55c1f5998a80 lookup=0x7efc564dcb50 doc=(nil)
PluginInterface --> OMPT: class bound ompt_callback_device_initialize=0x55c1f4f133d0
PluginInterface --> OMPT: class bound ompt_callback_device_finalize=0x55c1f4f13420
PluginInterface --> OMPT: class bound ompt_callback_device_load=0x55c1f4f13450
PluginInterface --> OMPT: class bound ompt_callback_device_unload=(nil)
Callback Init: device_num=3 type=generic-64bit device=0x55c1f59992b0 lookup=0x7efc564dcb50 doc=(nil)
omptarget --> Plugin adaptor 0x000055c1f59720d0 has index 0, exposes 4 out of 4 devices!
omptarget --> Registering image 0x000055c1f4f146e0 with RTL libomptarget.rtl.x86_64.so!
omptarget --> Done registering entries!
omptarget --> Call to omp_get_num_devices returning 4
Allocating memory on device
omptarget --> Call to omp_target_alloc for device 0 requesting 4 bytes
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000001) src=(nil) src_device_num=4 dest=(nil) dest_device_num=0 bytes=4 code=0x55c1f4f13853
PluginInterface --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Cannot find a node in the FreeLists. Allocate on device.
PluginInterface --> Node address 0x000055c1f5997910, target pointer 0x000055c1f59977a0, size 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000001) src=(nil) src_device_num=4 dest=0x55c1f59977a0 dest_device_num=0 bytes=4 code=0x55c1f4f13853
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_alloc returns device ptr 0x000055c1f59977a0
omptarget --> Call to omp_target_alloc for device 1 requesting 4 bytes
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
  Callback DataOp EMI: endpoint=1 optype=1 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000002) src=(nil) src_device_num=4 dest=(nil) dest_device_num=1 bytes=4 code=0x55c1f4f13864
PluginInterface --> MemoryManagerTy::allocate: size 4 with host pointer 0x0000000000000000.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Cannot find a node in the FreeLists. Allocate on device.
PluginInterface --> Node address 0x000055c1f5997940, target pointer 0x000055c1f5971fb0, size 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
  Callback DataOp EMI: endpoint=2 optype=1 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000002) src=(nil) src_device_num=4 dest=0x55c1f5971fb0 dest_device_num=1 bytes=4 code=0x55c1f4f13864
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_alloc returns device ptr 0x000055c1f5971fb0
Testing host to device
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_target_memcpy, dst device 0, src device 4, dst addr 0x000055c1f59977a0, src addr 0x000055c1f5992980, dst offset 0, src offset 0, length 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> copy from host to device
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000003) src=0x55c1f5992980 src_device_num=4 dest=0x55c1f59977a0 dest_device_num=0 bytes=4 code=0x55c1f4f138ca
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000003) src=0x55c1f5992980 src_device_num=4 dest=0x55c1f59977a0 dest_device_num=0 bytes=4 code=0x55c1f4f138ca
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_memcpy returns 0
Testing device to device
omptarget --> Call to omp_target_memcpy, dst device 1, src device 0, dst addr 0x000055c1f5971fb0, src addr 0x000055c1f59977a0, dst offset 0, src offset 0, length 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> copy from device to device
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000004) src=0x55c1f59977a0 src_device_num=0 dest=0x55c1f5997890 dest_device_num=4 bytes=4 code=0x55c1f4f138fc
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000004) src=0x55c1f59977a0 src_device_num=0 dest=0x55c1f5997890 dest_device_num=4 bytes=4 code=0x55c1f4f138fc
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=2 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000005) src=0x55c1f5997890 src_device_num=4 dest=0x55c1f5971fb0 dest_device_num=1 bytes=4 code=0x55c1f4f138fc
  Callback DataOp EMI: endpoint=2 optype=2 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000005) src=0x55c1f5997890 src_device_num=4 dest=0x55c1f5971fb0 dest_device_num=1 bytes=4 code=0x55c1f4f138fc
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_memcpy returns 0
Testing device to host
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_target_memcpy, dst device 4, src device 1, dst addr 0x000055c1f5992980, src addr 0x000055c1f5971fb0, dst offset 0, src offset 0, length 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
omptarget --> copy from device to host
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=3 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000006) src=0x55c1f5971fb0 src_device_num=1 dest=0x55c1f5992980 dest_device_num=4 bytes=4 code=0x55c1f4f13942
  Callback DataOp EMI: endpoint=2 optype=3 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000006) src=0x55c1f5971fb0 src_device_num=1 dest=0x55c1f5992980 dest_device_num=4 bytes=4 code=0x55c1f4f13942
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_memcpy returns 0
Checking correctness
Freeing memory on device
omptarget --> Call to omp_target_free for device 0 and address 0x000055c1f59977a0
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000007) src=0x55c1f59977a0 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55c1f4f139a4
PluginInterface --> MemoryManagerTy::free: target memory 0x000055c1f59977a0.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Found its node 0x000055c1f5997910. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000007) src=0x55c1f59977a0 src_device_num=0 dest=(nil) dest_device_num=-1 bytes=0 code=0x55c1f4f139a4
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_free deallocated device ptr
omptarget --> Call to omp_target_free for device 1 and address 0x000055c1f5971fb0
omptarget --> Call to omp_get_num_devices returning 4
omptarget --> Call to omp_get_initial_device returning 4
OMPT --> in ompt_target_region_begin (TargetRegionId = 0)
  Callback DataOp EMI: endpoint=1 optype=4 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000008) src=0x55c1f5971fb0 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x55c1f4f139b0
PluginInterface --> MemoryManagerTy::free: target memory 0x000055c1f5971fb0.
PluginInterface --> findBucket: Size 4 is floored to 4.
PluginInterface --> findBucket: Size 4 goes to bucket 0
PluginInterface --> Found its node 0x000055c1f5997940. Insert it to bucket 0.
  Callback DataOp EMI: endpoint=2 optype=4 target_task_data=(nil) (0x0) target_data=0x7efc562697d0 (0x0) host_op_id=0x7efc562697c8 (0x8000000000000008) src=0x55c1f5971fb0 src_device_num=1 dest=(nil) dest_device_num=-1 bytes=0 code=0x55c1f4f139b0
OMPT --> in ompt_target_region_end (TargetRegionId = 0)
omptarget --> omp_target_free deallocated device ptr
omptarget --> Unloading target library!
omptarget --> Unregistered image 0x000055c1f4f146e0 from RTL 0x000055c1f59720d0!
omptarget --> Done unregistering images!
omptarget --> Removing translation table for descriptor 0x000055c1f4f14660
omptarget --> Done unregistering library!
omptarget --> Deinit offload library!
OMPT --> Executing finalizeLibrary (libomp)
OMPT --> OMPT: Executing finalizeLibrary (libomptarget)
OMPT --> OMPT: Executing finalizeLibrary (libomptarget)
Callback Fini: device_num=0
Callback Fini: device_num=1
Callback Fini: device_num=2
Callback Fini: device_num=3
```

</details>

**Comment by mhalk** [comment]
> Do we have a place to document this decision other than this PR / commit message?

No, currently not. (But now that I think of it we should add another easily accessible doc.)
The first place that comes to my mind is the `(TargetDataExchange)RAII` instantiation: [Here.](https://github.com/llvm/llvm-project/commit/5fd8e50feff94dac7e741b07c956622b7c25bc6a#diff-49a42308a730c00ab9aa18dd4283c6c4f4decce37d1923bf5a570421e12b1cbaR188)

**Comment by Thyre** [comment]
> > x86_64 still reports two transfers even though `LIBOMPTARGET_DEBUG` shows `omptarget --> copy from device to device`.
> 
> Just reproduced this behavior within the testcase and I'll discuss this shortly but my guess is that the `x86_64` plugin is simply handling the 'data exhange' differently (chopping it into a pair of retrieve+submit via the initial device). My take is: changing that particular behavior is beyond the scope of this PR and should be discussed beforehand.
> 
> Observing `x86_64` callbacks seems like a very peculiar use-case to me TBH, especially since there is no accurate representation of the actually present / 'real' devices AFAIK. My _assumption_ is, that the latter is also the reason why we take the route 'retrieve+submit' via the 'real' (initial) device.

Just wanted to bring it up, so that it is known 😄 
I also agree that changing the behavior is outside of the PR scope and probably also doesn't have a high priority. I mean, if the runtime is splitting the transfer into two transfers, than its correct that we see that with OMPT. 

I also agree that observing `x86_64` callbacks for target callbacks is only somewhat useful. We will see that there are events, but why there are four devices for example may confuse people. In addition, we will see the actual host computation via other callbacks anyway.

File: openmp/libomptarget/src/OpenMP/OMPT/Callback.cpp [hunk 1]
```diff
@@ -193,41 +190,38 @@ void Interface::endTargetDataDelete(int64_t DeviceId, void *TgtPtrBegin,
...
+        DstPtrBegin, DstDeviceId, Size, Code);
   } else if (ompt_callback_target_data_op_fn) {
     // HostOpId is set by the runtime
     HostOpId = createOpId();
     // Invoke the tool supplied data op callback
     ompt_callback_target_data_op_fn(
         TargetData.value, HostOpId, ompt_target_data_transfer_from_device,
-        TgtPtrBegin, DeviceId, HstPtrBegin,
-        /*TgtDeviceNum=*/omp_get_initial_device(), Size, Code);
+        DstPtrBegin, DstDeviceId, SrcPtrBegin, SrcDeviceId, Size, Code);
```
Comment (dhruvachak) [inline openmp/libomptarget/src/OpenMP/OMPT/Callback.cpp:210]: This seems reversed. Shouldn't it be
SrcPtrBegin, SrcDeviceId, DstPtrBegin, DstDeviceId
?

File: openmp/libomptarget/src/device.cpp [hunk 2]
```diff
@@ -185,6 +185,17 @@ int32_t DeviceTy::retrieveData(void *HstPtrBegin, void *TgtPtrBegin,
...
+  /// RAII to establish tool anchors before and after data exchange
+  /// Note: Despite the fact that this is a data exchange, we use 'from_device'
+  ///       operation enum (w.r.t. ompt_target_data_op_t) as there is currently
+  ///       no better alternative. It is still possible to distinguish this
+  ///       scenario from a real data retrieve by checking if both involved
+  ///       device numbers are less than omp_get_num_devices().
+  OMPT_IF_BUILT(
+      InterfaceRAII TargetDataExchangeRAII(
+          RegionInterface.getCallbacks<ompt_target_data_transfer_from_device>(),
+          DeviceID, SrcPtr, DstDev.RTLDeviceID, DstPtr, Size,
```
Comment (dhruvachak) [inline openmp/libomptarget/src/device.cpp:197]: Use RTLDeviceID instead of DeviceID in the callback since that's what is used in the actual RTL->data_exchange invocation?

**Review by jplehr — COMMENTED** [review]
No more comments from my side on this one. I'll let @dhruvachak accept once he is happy with it.

File: openmp/libomptarget/test/ompt/target_memcpy_emi.c [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+#include "register_emi.h"
+
+int main(void) {
+  int NumDevices = omp_get_num_devices();
+  assert(NumDevices > 0);
+  int Device = 0;
+  int Host = omp_get_initial_device();
+
+  printf("Allocating Memory on Device\n");
+  int *DevPtr = (int *)omp_target_alloc(sizeof(int), Device);
```
Comment (dhruvachak) [inline openmp/libomptarget/test/ompt/target_memcpy_emi.c:26]: Check that DevPtr is not null.

File: openmp/libomptarget/test/ompt/target_memcpy_emi.c [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+  int *HstPtr = (int *)malloc(sizeof(int));
+  *HstPtr = 42;
+
+  printf("Testing: Host to Device\n");
+  omp_target_memcpy(DevPtr, HstPtr, sizeof(int), 0, 0, Device, Host);
```
Comment (dhruvachak) [inline openmp/libomptarget/test/ompt/target_memcpy_emi.c:31]: Check the return value of all calls to omp_target_memcpy. Otherwise, if it fails, the host value could remain 42 but the program still failed.

File: openmp/libomptarget/src/device.cpp (hunk 2 above)
Comment (mhalk) [reply openmp/libomptarget/src/device.cpp:197]: Sure, might be less confusing.

File: openmp/libomptarget/test/ompt/target_memcpy_emi.c (hunk 3 above)
Comment (mhalk) [reply openmp/libomptarget/test/ompt/target_memcpy_emi.c:26]: Done. Will add an `assert()`.

**Review by dhruvachak — APPROVED** [review]
LGTM.
