### PR TITLE
[LLD] [ELF] Add support for linker script unary plus operator

### LINKED ISSUE #118047: [LLD] Unary '+' operator is not supported in linker script
LLD does not support unary '+' operator in linker scripts. We should perhaps support this for compatibility with GNU linker.

Reproducible example:

```bash
#!/usr/bin/env bash

cat >1.c <<\EOF
int foo() { return 1; }
int bar() { return 3; }
EOF

cat >script.t <<\EOF
val = +0x1;
EOF

clang-18 -o 1.o 1.c -c -ffunction-sections
ld.bfd -o 1.bdf.out 1.o -T script.t
ld.lld -o 1.lld.out 1.o -T script.t
```

GNU LD produces no error, whereas LLD reports:

```
ld.lld: error: script.t:1: malformed number: +
>>> val = +0x1;
```

### PR DESCRIPTION
**Pull request by partaror**
This commit adds support for linker script unary plus ('+') operator. It is helpful for improving compatibility between LLD and GNU LD.

Closes #118047

### CODE REVIEW

**Review by lenary — APPROVED** [review]
LGTM

File: lld/ELF/ScriptParser.cpp [hunk 1]
```diff
@@ -1489,6 +1489,9 @@ Expr ScriptParser::readPrimary() {
     Expr e = readPrimary();
     return [=] { return -e().getValue(); };
   }
+  if (consume("+")) {
+    return readPrimary();
+  }
```
Comment (MaskRay) [inline lld/ELF/ScriptParser.cpp:1494]: drop braces

**Comment by MaskRay** [comment]
`> Fixes 118047`

I'd prefer "Close" since this is a new minor feature instead of a bugfix.

File: lld/ELF/ScriptParser.cpp (hunk 1 above)
Comment (partaror) [reply lld/ELF/ScriptParser.cpp]: Done.

**Comment by partaror** [comment]
> I'd prefer "Close" since this is a new minor feature instead of a bugfix.

Agreed. I have replaced `Fixes` with `Closes` in both the PR description and the commit message.

File: lld/test/ELF/linkerscript/operators.test [hunk 2]
```diff
@@ -73,6 +73,7 @@ SECTIONS {
   log2ceil100000000 = LOG2CEIL(0x100000000);
   log2ceil100000001 = LOG2CEIL(0x100000001);
   log2ceilmax = LOG2CEIL(0xffffffffffffffff);
+  unaryadd = +3 + ++5;
 }
```
Comment (MaskRay) [inline lld/test/ELF/linkerscript/operators.test:77]: perhaps also add ` -+5` while here...

**Review by MaskRay — APPROVED** [review]

File: lld/test/ELF/linkerscript/operators.test (hunk 2 above)
Comment (partaror) [reply lld/test/ELF/linkerscript/operators.test:78]: Done. I have added another symbol that uses both `+-` and `-+`.

**Review by MaskRay — APPROVED** [review]

**Comment by partaror** [comment]
Gentle ping for review @smithp35

**Review by smithp35 — APPROVED** [review]
Apologies, I didn't think you were waiting on me. I think an approval from MaskRay is sufficient.

LGTM too.

**Comment by partaror** [comment]
@MaskRay Can you please let me know if it is okay if I merge the pull-request myself?

File: lld/test/ELF/linkerscript/operators.test [hunk 3]
```diff
@@ -126,6 +128,9 @@ SECTIONS {
 # CHECK-NEXT: 0000000000000020 A log2ceil100000000
 # CHECK-NEXT: 0000000000000021 A log2ceil100000001
 # CHECK-NEXT: 0000000000000040 A log2ceilmax
+# CHECK-NEXT: 0000000000000008 A unaryadd
+# CHECK-NEXT: 0000000000000003 A unaryadd_and_unaryminus
+
```
Comment (MaskRay) [inline lld/test/ELF/linkerscript/operators.test:133]: Delete the extra blank line

We don't use double-blank line as separator.

**Review by MaskRay — APPROVED** [review]
LGTM

File: lld/test/ELF/linkerscript/operators.test (hunk 3 above)
Comment (partaror) [reply lld/test/ELF/linkerscript/operators.test:133]: Done.
