### PR TITLE
[llvm-objdump][ELF]Fix crash when reading strings from .dynstr

### LINKED ISSUE #86612: llvm-objdump: printDynamicSection() out-of-bounds read
Reported against FreeBSD at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277885, with attached ELF reproducer.

```
# llvm-objdump --version
LLVM (http://llvm.org/):
  LLVM version 17.0.6
  Optimized build with assertions.
...
# llvm-objdump -x objdump10a.exe
...
Dynamic Section:
  NEEDED       PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-objdump -x objdump10a.exe
 #0 0x0000000001230c41 PrintStackTrace /usr/src/contrib/llvm-project/llvm/lib/Support/Unix/Signals.inc:602:13
 #1 0x000000000122f0b5 RunSignalHandlers /usr/src/contrib/llvm-project/llvm/lib/Support/Signals.cpp:105:18
 #2 0x0000000001231365 SignalHandler /usr/src/contrib/llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #3 0x00000008267d55ff handle_signal /usr/src/lib/libthr/thread/thr_sig.c:0:3
 #4 0x00000008267d4bbb thr_sighandler /usr/src/lib/libthr/thread/thr_sig.c:244:1
 #5 0x0000000822def2d3 ([vdso]+0x2d3)
 #6 0x0000000828b3a7eb /usr/src/lib/libc/amd64/string/strlen.S:95:0
 #7 0x0000000000df28c9 __constexpr_strlen /usr/obj/usr/src/amd64.amd64/tmp/usr/include/c++/v1/__string/constexpr_c_functions.h:49:10
 #8 0x0000000000df28c9 length /usr/obj/usr/src/amd64.amd64/tmp/usr/include/c++/v1/__string/char_traits.h:222:14
 #9 0x0000000000df28c9 StringRef /usr/src/contrib/llvm-project/llvm/include/llvm/ADT/StringRef.h:90:33
#10 0x0000000000df28c9 operator<< /usr/src/contrib/llvm-project/llvm/include/llvm/Support/raw_ostream.h:244:29
#11 0x0000000000df28c9 printDynamicSection /usr/src/contrib/llvm-project/llvm/tools/llvm-objdump/ELFDump.cpp:233:16
#12 0x0000000000df28c9 printPrivateHeaders /usr/src/contrib/llvm-project/llvm/tools/llvm-objdump/ELFDump.cpp:431:3
#13 0x0000000000e6a13c dumpObject /usr/src/contrib/llvm-project/llvm/tools/llvm-objdump/llvm-objdump.cpp:2815:7
#14 0x0000000000e654b0 dumpInput /usr/src/contrib/llvm-project/llvm/tools/llvm-objdump/llvm-objdump.cpp:0:5
#15 0x0000000000e654b0 for_each<std::__1::__wrap_iter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > *>, void (*)(llvm::StringRef)> /usr/obj/usr/src/amd64.amd64/tmp/usr/include/c++/v1/__algorithm/for_each.h:26:5
#16 0x0000000000e654b0 for_each<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > &, void (*)(llvm::StringRef)> /usr/src/contrib/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1731:10
#17 0x0000000000e654b0 main /usr/src/contrib/llvm-project/llvm/tools/llvm-objdump/llvm-objdump.cpp:3248:3
#18 0x0000000828a660aa __libc_start1 /usr/src/lib/libc/csu/libc_start1.c:157:2
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by cabbaken**
This change introduces a check for the strtab offset to prevent llvm-objdump from crashing when processing malformed ELF files.
It provide a minimal reproduce test for https://github.com/llvm/llvm-project/issues/86612#issuecomment-2035694455.
Additionally, it modifies how llvm-objdump handles and outputs malformed ELF files with invalid string offsets.(More info: https://discourse.llvm.org/t/should-llvm-objdump-objdump-display-actual-corrupted-values-in-malformed-elf-files/84391)

Fixes: #86612

### CODE REVIEW

**Comment by cabbaken** [comment]
I'm not sure why the tests failed. It doesn't seem related to this patch.
Do these tests use llvm-objdump? Could someone help troubleshoot this?😭

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 1]
```diff
@@ -235,6 +252,12 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
       Expected<StringRef> StrTabOrErr = getDynamicStrTab(Elf);
       if (StrTabOrErr) {
         const char *Data = StrTabOrErr->data();
+        if (Dyn.getVal() > StringTableSize) {
+          reportWarning("Invalid string table offset", Obj.getFileName());
```
Comment (MaskRay) [inline llvm/tools/llvm-objdump/ELFDump.cpp:256]: do not capitalize the message. llvm-objdump follows this documented convention https://llvm.org/docs/CodingStandards.html#error-and-warning-messages

`>` => `>=`

**Review by MaskRay — COMMENTED** [review]
In general llvm-readobj's error handling is better than llvm-objdump. You could look at its code for inspiration. The relevant patch might be https://reviews.llvm.org/D77216

Instead of a general title "Enhancing llvm-objdump stability and error handling", a specific one like "Fix ... when reading strings from .dynstr" or the like would be better and help future readers that find your patch.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 1 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:256]: Thanks, I will fix it soon.

**Comment by cabbaken** [comment]
> > I'm not sure why the tests failed. It doesn't seem related to this patch. Do these tests use llvm-objdump? Could someone help troubleshoot this?😭
> 
> It's not uncommon for tests to fail for reasons unrelated to your PR. Typically this is because there's a bug at the point of main that you branched off of. Looking at the failures suggests that this is the case here. You can ignore them.

Got it, thanks for your kindly response~

**Comment by jh7370** [comment]
> The new version of patch modified commit title ...

The default behaviour for merging is to use the PR title and description, not the commit message (although the initial default of the PR title and description is taken from the commit message). If you need to update these, you should edit the PR, not the commit message.

Also, please avoid force pushing after updating, as it makes it harder to see what has changed between versions of the PR.

Finally, please add "Fixes: #86612" to the PR description. In that way, when the PR is merged, the issue should auto-close, I believe.

**Comment by cabbaken** [comment]
> > The new version of patch modified commit title ...
> 
> The default behaviour for merging is to use the PR title and description, not the commit message (although the initial default of the PR title and description is taken from the commit message). If you need to update these, you should edit the PR, not the commit message.
> 
> Also, please avoid force pushing after updating, as it makes it harder to see what has changed between versions of the PR.
> 
> Finally, please add "Fixes: #86612" to the PR description. In that way, when the PR is merged, the issue should auto-close, I believe.

I've made the changes about the title and description of PR and will follow these guidelines in future work.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 2]
```diff
@@ -470,3 +473,34 @@ Sections:
...
+       Value: 0x0
+ProgramHeaders:
+  - Type:     PT_LOAD
+    VAddr:    0x1000
+    FirstSec: .dynstr
+    LastSec:  .dynamic
+  - Type:     PT_DYNAMIC
+    VAddr:    0x101D
+    FirstSec: .dynamic
+    LastSec:  .dynamic
```
Comment (MaskRay) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:506]: The icon shows that there is no EOL at the end of the test. Please fix it.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 3]
```diff
@@ -438,6 +438,9 @@ ProgramHeaders:
 # RUN: yaml2obj --docnum=4 %s -o %t4
 # RUN: llvm-objdump -p %t4 | FileCheck %s --strict-whitespace --check-prefix=INDENT
 
+# RUN: yaml2obj --docnum=5 %s -o %t5
+# RUN: llvm-objdump -p %t5 | FileCheck %s --strict-whitespace --check-prefix=INDENT
```
Comment (MaskRay) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:442]: `2>&1 | FileCheck ...` 

Test both the warning `invalid string table offset` and the output. The output describes how  llvm-objdump handles input input, and is useful as a change detector.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 4]
```diff
@@ -221,6 +224,20 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
...
 
   outs() << "\nDynamic Section:\n";
+  auto StringTableSize = (typename ELFT::Xword)0;
+  for (const auto &Sec : cantFail(Elf.sections())) {
+    if (Sec.sh_type == ELF::SHT_STRTAB)
+      StringTableSize =
+          StringTableSize < Sec.sh_size ? Sec.sh_size : StringTableSize;
+  }
+  for (const typename ELFT::Dyn &Dyn : DynamicEntries) {
+    if (Dyn.d_tag == ELF::DT_STRSZ) {
```
Comment (MaskRay) [inline llvm/tools/llvm-objdump/ELFDump.cpp:234]: The section header table is optional in loadable units (executables, shared objects). Dynamic loaders only read dynamic tags, not the section header table. The dynamic tags are source of truths for the dynamic symbol table size. You can keep just the DT_STRSZ code and ignore `SHT_STRTAB`. 

We could emit a warning when the two values mismatch, but llvm-readobj doesn't do it. For the purpose of fixing just this crash it may not be necessary to add the warning.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test (hunk 2 above)
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:506]: Does that mean I need to insert new line in the end of the test?

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test (hunk 3 above)
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:442]: Got it, I will fix it soon. This is my first time using the llvm-test-suite, and I'm sorry for being unfamiliar with it.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 4 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:234]: I check `SHT_STRTAB` because, in `getDynamicStrTab(Elf)`, I noticed that both dynamic entries and sections are checked. Therefore, I believe checking the sections is necessary.
The test(`tools/llvm-objdump/ELF/private-headers.test`) will fail without this check.

Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:234]: Please let me know if you have any ideas about this😊~

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 5]
```diff
@@ -470,3 +470,47 @@ Sections:
...
+# RUN: yaml2obj --docnum=5 %s -o %t5
+# RUN: llvm-objdump -p %t5 2>&1 | FileCheck %s --strict-whitespace -DFILE=%t5 --check-prefix=WARN
+
+# WARN: Program Header:
+# WARN:     LOAD off    0x00000000000000b0 vaddr 0x0000000000001000 paddr 0x0000000000001000 align 2**0
+# WARN:          filesz 0x0000000000000040 memsz 0x0000000000000040 flags ---
+# WARN:  DYNAMIC off    0x00000000000000c0 vaddr 0x000000000000101d paddr 0x000000000000101d align 2**0
+# WARN:          filesz 0x0000000000000030 memsz 0x0000000000000030 flags ---
+# WARN: Dynamic Section:
+# WARN: : warning: '[[FILE]]': invalid string table offset
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:483]:
```suggestion
# WARN: warning: '[[FILE]]': invalid string table offset
```

**Review by jh7370 — COMMENTED** [review]
Sorry for the delayed comments - I had them pending, but forgot to submit!

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 6]
```diff
@@ -221,6 +224,20 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
   std::string TagFmt = "  %-" + std::to_string(MaxLen) + "s ";
 
   outs() << "\nDynamic Section:\n";
+  auto StringTableSize = (typename ELFT::Xword)0;
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:227]: I didn't notice that. This piece of code is for test originally. I will fix it.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 7]
```diff
@@ -470,3 +473,34 @@ Sections:
...
+  - Name:    .dynstr
+    Type:    SHT_STRTAB
+    Address: 0x1000
+    Size:    0x10
+    Content: "004400550066007700"
+  - Name: .dynamic
+    Type: SHT_DYNAMIC
+    Entries:
+     - Tag:   DT_NEEDED
+       Value: 0x1245657656
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:503]: The check used is `Dyn.getVal() >= StringTableSize`, so the edge I'm referring to is the `StringTableSize`, i.e. an address at exactly `StringTableSize` produces a warning, whereas one that is one before this value does.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:227]: `0` needs to be explicitly convert to `typename ELFT::Xword` to be assigned to `StringTableSize`, and the expression will be `typename ELFT::Xword StringTableSize = (typename ELFT::Xword)0` which is unnecessarily redundant.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test (hunk 7 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:503]: Oh, I know what you mean. I will fix it in the next commit.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 8]
```diff
@@ -235,6 +252,12 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
       Expected<StringRef> StrTabOrErr = getDynamicStrTab(Elf);
       if (StrTabOrErr) {
         const char *Data = StrTabOrErr->data();
+        if (Dyn.getVal() >= StringTableSize) {
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:255]: Get it, I will check it later.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 9]
```diff
@@ -221,6 +224,20 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
...
+  auto StringTableSize = (typename ELFT::Xword)0;
+  for (const auto &Sec : cantFail(Elf.sections())) {
+    if (Sec.sh_type == ELF::SHT_STRTAB)
+      StringTableSize =
+          StringTableSize < Sec.sh_size ? Sec.sh_size : StringTableSize;
+  }
+  for (const typename ELFT::Dyn &Dyn : DynamicEntries) {
+    if (Dyn.d_tag == ELF::DT_STRSZ) {
+      StringTableSize =
+          StringTableSize < Dyn.getVal() ? Dyn.getVal() : StringTableSize;
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:236]: You're right, I will check later.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 10]
```diff
@@ -14,8 +14,11 @@
 #include "ELFDump.h"
 
 #include "llvm-objdump.h"
+#include "llvm/BinaryFormat/ELF.h"
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:17]: Do you need these extra includes?

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 11]
```diff
@@ -221,6 +224,20 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
   std::string TagFmt = "  %-" + std::to_string(MaxLen) + "s ";
 
   outs() << "\nDynamic Section:\n";
+  auto StringTableSize = (typename ELFT::Xword)0;
+  for (const auto &Sec : cantFail(Elf.sections())) {
+    if (Sec.sh_type == ELF::SHT_STRTAB)
+      StringTableSize =
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:230]: 1) If I'm not mistaken, this assignment could easily pick up the wrong string table section, e.g. the .strtab section containing symbol and section names, and not the dynamic string table, rendering the subsequent usage incorrect.
2) I don't follow what the point of the subsequent ternary is; presumably it's related to point 1 above.

I think you need to look for the dynamic string table referenced by the dynamic section (it's the section with index matching the sh_link field of the dynamic section).

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 12]
```diff
@@ -235,6 +252,12 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
       Expected<StringRef> StrTabOrErr = getDynamicStrTab(Elf);
       if (StrTabOrErr) {
         const char *Data = StrTabOrErr->data();
+        if (Dyn.getVal() >= StringTableSize) {
+          reportWarning("invalid string table offset", Obj.getFileName());
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:256]: Normally, we like newer warnings to include additional context about what was invalid. In this case, it's debatable about whether it's needed, because the value is printed immediately afterwards. However, the message doesn't say anything about the string table size and therefore what a valid offset would actually be.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:227]: Thanks, I will try it later~

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 13]
```diff
@@ -221,6 +224,20 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
   std::string TagFmt = "  %-" + std::to_string(MaxLen) + "s ";
 
   outs() << "\nDynamic Section:\n";
+  auto StringTableSize = (typename ELFT::Xword)0;
+  for (const auto &Sec : cantFail(Elf.sections())) {
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:228]: Thanks, I will fix it soon!

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 10 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:17]: I will remove the unneeded headers. Clangd add the headers automatically and I'm sorry for didn't notice that.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 12 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:256]: I will add some additional context. 
The string table size is ideal here, right?

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 10 above)
Comment (MaskRay) [reply llvm/tools/llvm-objdump/ELFDump.cpp:17]: "Resolve conversation" button is for the reviewers to click. https://discourse.llvm.org/t/rfc-github-pr-resolve-conversation-button/73178

(Alt + Click on a resolved inline comment expands all resolved inline comments.
Another Alt + Click will hide all inline comments.)

Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:17]: I'm sorry about that, I thought that reminds you to check.
I'm sorry for such a mistake.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 12 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:256]: I am curious about the way to output a variable in `reportWarning()`. it seems that there is not a simple way to make a formatted string to `reportWarning()` or I must make a formatted string with `std::format` or `std::snprintf`?

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 11 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:230]: Thanks for the correction. I’ll fix this in the next commit!
I misunderstood the meaning of `ELF::SHT_STRTAB`, which led to this mistake.

Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: I’ve fixed it in the latest commit. 
Let me know if you have any suggestions.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: I’ve fixed it in the latest commit. Let me know if you have any suggestions.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: Fixed

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test (hunk 7 above)
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:503]: You shouldn't be reading memory outside the file image, or you could end up trying to read memory belonging e.g. to another a process entirely (depending on how memory safety works on your particular OS). A crash is just one of possible behaviours. For example, it's not impossible you'd print something that appears meaningful but is actually completely bogus.

As a valid virtual address will depend on the host OS, that isn't something that is worth targeting. Instead, the thing you should be targeting is where the behaviour changes - namely when the address points at or past the end of the string table. In that way, you can show you get the warning when the value reaches the bad point, but not when it is just before. We don't need to trigger a crash, showing that we don't read bogus data is good enough, since it's the same problem.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 14]
```diff
@@ -221,6 +221,28 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
   std::string TagFmt = "  %-" + std::to_string(MaxLen) + "s ";
 
   outs() << "\nDynamic Section:\n";
+  typename ELFT::Xword StringTableSize{0};
+  for (const typename ELFT::Shdr &Sec : cantFail(Elf.sections())) {
+    if (Sec.sh_type == ELF::SHT_DYNSYM) {
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:226]: This will work because it happens to be the same section in pretty much any normal ELF, but is not technically correct. You should check `SHT_DYNAMIC`, since the strings referenced by the dynamic section are the ones you need (not the dynamic symbol names).

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 15]
```diff
@@ -221,6 +221,28 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
...
+      Expected<const typename ELFT::Shdr *> StringTableSecOrError =
+          getSection<ELFT>(cantFail(Elf.sections()), Sec.sh_link);
+      if (!StringTableSecOrError) {
+        consumeError(StringTableSecOrError.takeError());
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:230]: You probably shouldn't be throwing away this error and instead should report it and bail out of the loop.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 16]
```diff
@@ -221,6 +221,28 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
...
+        break;
+      }
+      StringTableSize = StringTableSize < (*StringTableSecOrError)->sh_size
+                            ? (*StringTableSecOrError)->sh_size
+                            : StringTableSize;
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:235]: The ternary isn't necessary. The dynamic section will only reference one string table, so you'll only have one size by this point.

In fact, once you find the dynamic section and have read the string size from it, you can bail out of the loop.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 17]
```diff
@@ -221,6 +221,28 @@ template <class ELFT> void ELFDumper<ELFT>::printDynamicSection() {
...
+    }
+  }
+  for (const typename ELFT::Dyn &Dyn : DynamicEntries) {
+    if (Dyn.d_tag == ELF::DT_STRSZ) {
+      StringTableSize =
+          StringTableSize < Dyn.getVal() ? Dyn.getVal() : StringTableSize;
```
Comment (jh7370) [inline llvm/tools/llvm-objdump/ELFDump.cpp:241]: I'm not convinced we should be picking the larger of the two sizes, assuming a section one is found. It would be safer to pick the smaller one. That being said, if this matches llvm-readobj, I'm okay with it.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 12 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:261]: Oh, that's a helpful suggestion, I should learn further about the `Twine`.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 16 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:235]: Yes, I will fix it.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 14 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:226]: > This will work because it happens to be the same section in pretty much any normal ELF, but is not technically correct. You should check `SHT_DYNAMIC`, since the strings referenced by the dynamic section are the ones you need (not the dynamic symbol names).

That’s true, but `private-headers.test` will fail if `SHT_DYNAMIC` is used since there’s no `Link` to `.dynstr` in this test. I chose `SHT_DYNSYM` to align with `llvm/llvm/tools/llvm-objdump/ELFDump.cpp:61: getDynamicStrTab()`, as they function similarly.
In fact, I'm curious why using `SHT_DYNSYM` allows the test to pass. It seems that `yaml2obj` add the `SHT_DYNSYM` to the generated ELF.
Maybe I should use
```
    if (Sec.sh_type == ELF::SHT_DYNSYM||Sec.sh_type == ELF::SHT_DYNAMIC)
```
here?

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 17 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:241]: `llvm-readobj` use `ELF::DT_STRSZ` to check string table size here: `llvm/tools/llvm-readobj/ELFDumper.cpp:2007: parseDynamicTable()`.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 15 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:230]: You're right, I will fix it in next commit.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test (hunk 7 above)
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:503]: I understand now! 
I will fix it in next commit.

**Comment by jh7370** [comment]
FYI, it'll be next week before I come back to this.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 14 above)
Comment (jh7370) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: > That’s true, but `private-headers.test` will fail if `SHT_DYNAMIC` is used since there’s no `Link` to `.dynstr` in this test

That's a bug in the test (and arguably yaml2obj, since really yaml2obj should auto-link to a generated .dynstr, in the ideal world - if you fancy getting stuck into that, I'm not going to object).

That being said, your comment raises an interesting point, and I keep coming back to this: why aren't we simply using the `getDynamicStrTab` function's returned `StringRef::size` to make sure we aren't reading past the end of the data? Looking at the code, the problem is that in its current form, you can't: when `getDynamicStrTab`  finds the string table from the dynamic tags (i.e. find `DT_STRTAB`), it looks up the data using the specified address, but then simply returns:
```
      return StringRef(reinterpret_cast<const char *>(*MappedAddrOrError));
```
This overload of the `StringRef` constructor is similar to the equivalent `std::string` constructor which just looks for the first null byte and terminates the string there. However, for an ELF spec-conforming string table, this will be the very first byte in the table, since the table is lead with a null terminator (and even if it didn't have the leading terminator, every string in the table will have one, so only the first string will be included within the size). The code should instead use `DT_STRSZ` to identify the dynamic string table size in this context. If it's missing, it should probably just refuse to use the string table specified by the dynamic tags (printing a warning as it does so, since `DT_STRSZ` is listed as mandatory in the ELF spec). Arguably, this would be a regression in behaviour (previously, it was possible to use llvm-objdump to get the strings and now it wouldn't be, if the DT_STRSZ is missing and there are no sections), but as the file doesn't conform to the ELF spec, I don't think that's an issue per se. We could look at using the end of the object file as a value for the size in this case, as an alternative.

Once we have the size, you can use the `StringRef` constructor in `getDynamicStrTab` that takes the size of data as a parameter. Then, when dumping the dynamic table, you can check the tag values against the size of the returned data, to make sure you're not reading past the end.

Regarding why `getDynamicStrTab` is using `SHT_DYNSYM`, I don't know. I actually reviewed the original implementation of this (7 years ago - I didn't realise I'd been involved with LLVM for so long!), but must have missed that it was using `SHT_DYNSYM`. I did comment on something possibly related, but I suspect over the course of the review things changed in a way that I didn't notice it. Either way, since `getDynamicStrTab` is only used by the dynamic entry dumping code, I think it would be reasonable to change that to finding it via `SHT_DYNAIMC` only. If tests fail as a result of that change, let me know and we can take a look at them to see if there's some case I've missed or if the test just needs updating.

And yes, yaml2obj does (sometimes) add a SHT_DYNSYM to an ELF. I believe `DynamicSymbols` has to be specified in the ELF, but I haven't checked that one.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 16 above)
Comment (jh7370) [reply llvm/tools/llvm-objdump/ELFDump.cpp:236]: This point is probably moot, if we switch to simply relying on the size returned by `getDynamicStrTab` (after fixing `getDynamicStrTab` as I've described, because this code should disappear.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 14 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: So, in conclusion, the root cause is the implementation of `getDynamicStrTab`, right?
Would it be better to fix `getDynamicStrTab` in this PR, or should it be addressed in the next one?
Also, using `SHT_DYNSYM` in `getDynamicStrTab` seems like a poor choice and should be corrected.

Should I just fix the test and replace `SHT_DYNSYM` with `SHT_DYNAMIC` here?

Comment (jh7370) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: Yeah, exactly. I think the core of this PR is to fix that function and add a simple check against the size of the returned `StringRef` when determining what to print for `DT_NEEDED` etc.

To minimise changes, I think I'd switch from `SHT_DYNSYM` to `SHT_DYNAMIC` in a separate PR that immediately follows this one. You might need to change the test after that change, but that's okay.

You should use `DT_STRSZ` to specify the size ONLY when the string table is found via `DT_STRTAB`. You should use the section size ONLY when the string table is found via the sections. These should only be used within `getDynamicStrTab` and then the code that calls it simply uses the returned `StringRef::size` to check the section offsets. Within `getDynamicStrTab`, you can sanity check that the `DT_STRSZ`/section `sh_size` fields (as appropriate) make sense (point within the range of the file) and return an Error from the function if they don't. That check could be a separate change, with additional testing. This PR should be about checking that the DT_* offsets are sensible.

File: llvm/tools/llvm-objdump/ELFDump.cpp [hunk 18]
```diff
@@ -63,14 +63,22 @@ static Expected<StringRef> getDynamicStrTab(const ELFFile<ELFT> &Elf) {
   if (!DynamicEntriesOrError)
     return DynamicEntriesOrError.takeError();
 
+  typename ELFT::Xword StringTableSize{0};
```
Comment (MaskRay) [inline llvm/tools/llvm-objdump/ELFDump.cpp:66]: llvm style prefers `= 0` to `{0}`

Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:66]: > Ah, the constructor is marked as `explicit`. Try this:
> 
> ```
> typename ELFT::Xword StringTableSize{0};
> ```
> 
> This worked locally for me with a Visual Studio build at least.

I followed this. Do you have any suggestions on which style is the correct one to use here?

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 14 above)
Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp]: I have fixed that in the latest commit. 
And I replaced `SHT_DYNSYM` with `SHT_DYNAMIC` in this [PR](https://github.com/llvm/llvm-project/pull/127975) to fix `getDynamicStrTab`.

File: llvm/tools/llvm-objdump/ELFDump.cpp (hunk 18 above)
Comment (MaskRay) [reply llvm/tools/llvm-objdump/ELFDump.cpp:66]: `typename ELFT::Xword StringTableSize = 0;`

Comment (cabbaken) [reply llvm/tools/llvm-objdump/ELFDump.cpp:66]: > `typename ELFT::Xword StringTableSize = 0;`

I got error with this code.
```
No viable conversion from 'int' to 'typename ELFType<llvm::endianness::little, false>::Xword' (aka 'packed_endian_specific_integral<unsigned long, (llvm::endianness)1, 1>')
```

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 19]
```diff
@@ -470,3 +470,50 @@ Sections:
        Value: 0x1
      - Tag:   DT_NULL
        Value: 0x0
+
+# RUN: yaml2obj --docnum=5 %s -o %t5
+# RUN: llvm-objdump -p %t5 2>&1 | FileCheck %s --strict-whitespace -DFILE=%t5 --check-prefix=WARN
+
+# WARN: Program Header:
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:477]: I don't think checking the contents of the program header table is needed for verifying the behaviour in this case. You can just omit those lines.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 20]
```diff
@@ -470,3 +470,50 @@ Sections:
...
+  Class:   ELFCLASS64
+  Data:    ELFDATA2LSB
+  Type:    ET_EXEC
+  Machine: EM_X86_64
+Sections:
+  - Name:    .dynstr
+    Type:    SHT_STRTAB
+    Address: 0x1000
+    Size:    0x10
+    Content: "004400550066007700"
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:499]: I don't think you need both `Size` and `Content`. Just stick with `Size`, since we don't need real content to display.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 21]
```diff
@@ -470,3 +470,50 @@ Sections:
...
+  - Name: .dynamic
+    Type: SHT_DYNAMIC
+    Entries:
+     - Tag:   DT_NEEDED
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:503]: I think it would be worth adding another DT_NEEDED or equivalent tag, with a value of exactly one before the end of the string table (0xF in this case), showing that the warning isn't printed in this case.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 22]
```diff
@@ -470,3 +470,50 @@ Sections:
...
+       Value: 0x11
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:504]: The size is `0x10`, so Value should be `0x10` too, to show that an entry pointing immediately after the table results in an error.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 23]
```diff
@@ -470,3 +470,50 @@ Sections:
...
+       Value: 0x10
+     - Tag:   DT_NULL
+       Value: 0x0
+ProgramHeaders:
+  - Type:     PT_LOAD
+    VAddr:    0x1000
+    FirstSec: .dynstr
+    LastSec:  .dynamic
+  - Type:     PT_DYNAMIC
+    VAddr:    0x101D
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/dynamic-section.test:517]: I don't think the address value of the PT_DYNAMIC is actually important to this test. However, if you want to keep it, it should be the address of PT_LOAD + size of the .dysntr, since that's where it'll be placed.

**Comment by cabbaken** [comment]
I have fixed it in the latest commit.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 24]
```diff
@@ -474,14 +474,10 @@ Sections:
 # RUN: yaml2obj --docnum=5 %s -o %t5
 # RUN: llvm-objdump -p %t5 2>&1 | FileCheck %s --strict-whitespace -DFILE=%t5 --check-prefix=WARN
 
-# WARN: Program Header:
-# WARN:    LOAD off    0x00000000000000b0 vaddr 0x0000000000001000 paddr 0x0000000000001000 align 2**0
-# WARN:         filesz 0x0000000000000050 memsz 0x0000000000000050 flags ---
-# WARN: DYNAMIC off    0x00000000000000c0 vaddr 0x000000000000101d paddr 0x000000000000101d align 2**0
-# WARN:         filesz 0x0000000000000040 memsz 0x0000000000000040 flags ---
 # WARN: Dynamic Section:
 # WARN: warning: '[[FILE]]': invalid string table offset
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test]: I have fixed it in the latest commit.

File: llvm/test/tools/llvm-objdump/ELF/dynamic-section.test [hunk 25]
```diff
@@ -474,14 +474,10 @@ Sections:
...
-# WARN:  NEEDED 0x0000000000000011
+# WARN:  NEEDED 0x0000000000000010
+# WARN:  NEEDED
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/dynamic-section.test]: fixed now.

**Review by jh7370 — APPROVED** [review]
LGTM. @MaskRay, any final thoughts before this gets merged? @cabbaken, do you need me to merge this for you?

**Comment by cabbaken** [comment]
Thanks.
Yes, I want to merge this.

**Review by MaskRay — APPROVED** [review]

**Comment by cabbaken** [comment]
❤️❤️❤️❤️
