### PR TITLE
[AArch64][SME] Use reportFatalUsageError rather than assert (NFC)

### LINKED ISSUE #144351: "Expected SME to be available" assert fails on memcpy
Trying to produce the simplest possible testcase that emits __arm_sc_memcpy hits an assertion: https://godbolt.org/z/89GTdMYf5

```
; RUN: llc -mtriple=arm64-apple-darwin < %s | FileCheck %s

@dst = global [512 x i8] zeroinitializer, align 1
@src = global [512 x i8] zeroinitializer, align 1

define void @se_memcpy(i64 noundef %n) "aarch64_pstate_sm_enabled" nounwind {
entry:
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 @dst, ptr nonnull align 1 @src, i64 %n, i1 false)
  ret void
}
```

```
Assertion failed: ((!IsStreaming || I->hasSME()) && "Expected SME to be available"), function getSubtargetImpl, file AArch64TargetMachine.cpp, line 482.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: llc -o - /tmp/assert-aarch64.ll
1.	Running pass 'Pre-ISel Intrinsic Lowering' on module '/tmp/assert-aarch64.ll'.
 #0 0x00000001072fcf04 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/llc+0x1024dcf04)
 #1 0x00000001072fb430 llvm::sys::RunSignalHandlers() (/usr/local/bin/llc+0x1024db430)
 #2 0x00000001072fd598 SignalHandler(int, __siginfo*, void*) (/usr/local/bin/llc+0x1024dd598)
 #3 0x0000000198f4ade4 (/usr/lib/system/libsystem_platform.dylib+0x180482de4)
 #4 0x0000000198f13f70 (/usr/lib/system/libsystem_pthread.dylib+0x18044bf70)
 #5 0x0000000198e20908 (/usr/lib/system/libsystem_c.dylib+0x180358908)
 #6 0x0000000198e1fc1c (/usr/lib/system/libsystem_c.dylib+0x180357c1c)
 #7 0x0000000107f1048c llvm::AArch64TargetMachine::getSubtargetImpl(llvm::Function const&) const (.cold.3) (/usr/local/bin/llc+0x1030f048c)
 #8 0x00000001051d1088 llvm::AArch64TargetMachine::getSubtargetImpl(llvm::Function const&) const (/usr/local/bin/llc+0x1003b1088)
 #9 0x00000001051d1690 llvm::AArch64TargetMachine::getTargetTransformInfo(llvm::Function const&) const (/usr/local/bin/llc+0x1003b1690)
#10 0x0000000106577ab0 llvm::TargetTransformInfoWrapperPass::getTTI(llvm::Function const&) (/usr/local/bin/llc+0x101757ab0)
#11 0x000000010690f2ac (anonymous namespace)::PreISelIntrinsicLowering::lowerIntrinsics(llvm::Module&) const (/usr/local/bin/llc+0x101aef2ac)
#12 0x0000000106910720 (anonymous namespace)::PreISelIntrinsicLoweringLegacyPass::runOnModule(llvm::Module&) (/usr/local/bin/llc+0x101af0720)
```

### PR DESCRIPTION
**Pull request by MacDue**
Fixes #144351

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64TargetMachine.cpp [hunk 1]
```diff
@@ -481,7 +481,8 @@ AArch64TargetMachine::getSubtargetImpl(const Function &F) const {
         MaxSVEVectorSize, IsStreaming, IsStreamingCompatible, HasMinSize);
   }
 
-  assert((!IsStreaming || I->hasSME()) && "Expected SME to be available");
+  if (IsStreaming && !I->hasSME())
+    reportFatalUsageError("Streaming SVE functions require SME");
```
Comment (arsenm) [inline llvm/lib/Target/AArch64/AArch64TargetMachine.cpp]:
```suggestion
    reportFatalUsageError("streaming SVE functions require SME");
```

**Review by arsenm — COMMENTED** [review]
Needs test

File: llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll [hunk 2]
```diff
@@ -0,0 +1,7 @@
+; RUN: not llc -mtriple aarch64-none-linux-gnu %s 2>&1 | FileCheck %s
+
+; CHECK: LLVM ERROR: streaming SVE functions require SME
+define void @streaming(i64 noundef %n) "aarch64_pstate_sm_enabled" nounwind {
+entry:
+  ret void
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll]:
```suggestion
}

```

**Review by arsenm — APPROVED** [review]

File: llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll (hunk 2 above)
Comment (arsenm) [reply llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll]: could also probably turn this into a proper LLVMContext error

Comment (MacDue) [reply llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll]: I think this works for now (this case should be checked in the frontend too).

File: llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll [hunk 3]
```diff
@@ -0,0 +1,7 @@
+; RUN: not llc -mtriple aarch64-none-linux-gnu %s 2>&1 | FileCheck %s
```
Comment (mikaelholmen) [inline llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll:1]: Can we add "-o /dev/null" or something here to avoid opening an output file in the local directory, since it may be write protected?

Comment (arsenm) [reply llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll:1]: Should use -filetype=null

Comment (MacDue) [reply llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll:1]: Updated this to use `-filetype=null` https://github.com/llvm/llvm-project/commit/9fde72e729874450563eab8f2b0454cfeac57a48 :+1:

Comment (mikaelholmen) [reply llvm/test/CodeGen/AArch64/streaming-func-no-sme.ll:1]: Thanks!
