### PR TITLE
[AMDGPU] Fix moveToValue for copy to phys SGPR

### LINKED ISSUE #76031: [AMDGPU] SIFixSGPRCopies breaks functions with VALU copy to SGPR
```
# RUN: llc -march=amdgcn -mcpu=tonga -run-pass=si-fix-sgpr-copies -o - %s | FileCheck %s

# Copy to $sgpr0 is disconnected and becomes an IMPLICIT_DEF
# Inserted V_AND_B32 defines virtual register after use.

---
name:            si_fix_sgpr_copies_breaks_function
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
body:             |
  bb.0:
    liveins: $sgpr0

    %0:sgpr_32 = COPY $sgpr0
    %2:sreg_32 = S_MOV_B32 16
    %3:sreg_32 = S_LSHR_B32 %0, killed %2, implicit-def dead $scc
    %4:sreg_32 = COPY killed %3
    %5:sreg_32 = S_MOV_B32 -32768
    %7:vgpr_32 = COPY killed %5
    %6:vgpr_32 = V_XOR_B32_e64 killed %4, %7, implicit $exec
    %8:sreg_32 = S_MOV_B32 65535
    %10:sreg_32 = COPY %6
    %9:sreg_32 = S_AND_B32 killed %8, killed %10, implicit-def dead $scc
    $sgpr0 = COPY %9
    SI_RETURN_TO_EPILOG $sgpr0

...

```

### PR DESCRIPTION
**Pull request by Pierre-vh**
Fixes #76031

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 1]
```diff
@@ -7198,6 +7198,17 @@ void SIInstrInfo::moveToVALUImpl(SIInstrWorklist &Worklist,
     Register DstReg = Inst.getOperand(0).getReg();
     const TargetRegisterClass *NewDstRC = getDestEquivalentVGPRClass(Inst);
 
+    // If it's a copy of a VGPR to a physical SGPR, insert a V_READFIRSTLANE and
+    // hope for the best.
+    if (Inst.isCopy() && DstReg.isPhysical() &&
+        RI.isVGPR(MRI, Inst.getOperand(1).getReg())) {
+      BuildMI(*Inst.getParent(), &Inst, Inst.getDebugLoc(),
+              get(AMDGPU::V_READFIRSTLANE_B32), Inst.getOperand(0).getReg())
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:7206]: This is only going to work for 32-bit registers but still an improvement

File: llvm/test/CodeGen/AMDGPU/bug-cselect-b64.ll [hunk 2]
```diff
@@ -4,19 +4,20 @@
...
 ; CHECK-NEXT:    s_waitcnt vmcnt(0)
-; CHECK-NEXT:    v_cmp_ne_u64_e32 vcc_lo, s[4:5], v[0:1]
-; CHECK-NEXT:    v_mov_b32_e32 v0, 0
-; CHECK-NEXT:    v_cndmask_b32_e64 v1, 0, 1, vcc_lo
-; CHECK-NEXT:    buffer_store_dwordx2 v[1:2], off, s[0:3], 0
+; CHECK-NEXT:    v_cmp_ne_u64_e32 vcc_lo, s[0:1], v[0:1]
+; CHECK-NEXT:    v_mov_b32_e32 v1, s4
+; CHECK-NEXT:    s_mov_b32 s1, 0
+; CHECK-NEXT:    v_cndmask_b32_e64 v0, 0, 1, vcc_lo
+; CHECK-NEXT:    v_readfirstlane_b32 s0, v0
```
Comment (Pierre-vh) [inline llvm/test/CodeGen/AMDGPU/bug-cselect-b64.ll:19]: This looks odd, not sure it actually works. `s0` isn't guaranteed to be `v0`, is it? What if the first active lane gets the `1` from `cndmask` ?

**Review by arsenm — APPROVED** [review]

File: llvm/test/CodeGen/AMDGPU/bug-cselect-b64.ll (hunk 2 above)
Comment (arsenm) [reply llvm/test/CodeGen/AMDGPU/bug-cselect-b64.ll:19]: The whole function looks trivially uniform to me, so it doesn't matter. However in a more realistic example, you have a return to epilog of a divergent value which you can't really do anything with
