### PR TITLE
[clang-tidy] Add recursion protection in ExceptionSpecAnalyzer

### LINKED ISSUE #111436: [clang-tidy] Segfault with performance-noexcept-move-constructor
This looks like an infinite recursion leading to stack overflow.

```
[...]clang_tidy: Segmentation fault      (core dumped)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.  Program arguments: clang-tidy --checks=-clang-diagnostic-builtin-macro-redefined --warnings-as-errors=-clang-diagnostic-builtin-macro-redefined --export-fixes [...].clang-tidy.yaml [file].cpp -- -U_FORTIFY_SOURCE -I. -Wall -Wextra -Wpedantic -Wno-sign-compare -Wno-gcc-compat -Wno-pragma-once-outside-header -Wno-c99-extensions -Werror -Wno-error=unused-result -Wno-error=gnu-statement-expression -Wno-error=unused-command-line-argument -Wno-error=unused-but-set-variable -Wno-error=unused-parameter -Wno-error=unused-variable -Wno-error=pedantic -Wno-error=unknown-warning-option -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -no-canonical-prefixes -Xclang -fno-cxx-modules --target=x86_64-unknown-linux-gnu -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -std=c++20 -stdlib=libstdc++ -march=x86-64-v3 -g --std=c++20 --sysroot=[sysroot] -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fdebug-prefix-map=external/llvm_toolchain_llvm/=__bazel_toolchain_llvm_repo__/ -xc++ [...defines...] [...iquote...] [...isystem...]
1.  <eof> parser at end of file
2.  ASTMatcher: Processing 'performance-noexcept-move-constructor' against:
  CXXConstructorDecl [redacted]
--- Bound Nodes Begin ---
    FuncDecl - { CXXConstructorDecl [redacted] }
--- Bound Nodes End ---
  #0 0x00005575a76ac648 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (external/llvm_toolchain_llvm/bin/clang-tidy+0x37e6648)
  #1 0x00005575a76aa5fe llvm::sys::RunSignalHandlers() (external/llvm_toolchain_llvm/bin/clang-tidy+0x37e45fe)
  #2 0x00005575a76acde8 SignalHandler(int) Signals.cpp:0:0
  #3 0x00007f40d18e6520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
  #4 0x00005575a6a438b0 clang::Decl::getASTContext() const (external/llvm_toolchain_llvm/bin/clang-tidy+0x2b7d8b0)
  #5 0x00005575a6a5e8b1 clang::CXXConstructorDecl::isCopyOrMoveConstructor(unsigned int&) const (external/llvm_toolchain_llvm/bin/clang-tidy+0x2b988b1)
  #6 0x00005575a6a59779 clang::CXXConstructorDecl::isCopyConstructor(unsigned int&) const (external/llvm_toolchain_llvm/bin/clang-tidy+0x2b93779)
  #7 0x00005575a538d3c3 clang::tidy::utils::ExceptionSpecAnalyzer::getDefaultableMemberKind(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c73c3)
  #8 0x00005575a538d711 clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7711)
  #9 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #10 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #11 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #12 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #13 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #14 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #15 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #16 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #17 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #18 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #19 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #20 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #21 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #22 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #23 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #24 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #25 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #26 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #27 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #28 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #29 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #30 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #31 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #32 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #33 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #34 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #35 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #36 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #37 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #38 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #39 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #40 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #41 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #42 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #43 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #44 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #45 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #46 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #47 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #48 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #49 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #50 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #51 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #52 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #53 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #54 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #55 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #56 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #57 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #58 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #59 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #60 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #61 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #62 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #63 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #64 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #65 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #66 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #67 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #68 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #69 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #70 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #71 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #72 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #73 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #74 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #75 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #76 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #77 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #78 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #79 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #80 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #81 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #82 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #83 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #84 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #85 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #86 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #87 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #88 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #89 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #90 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #91 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #92 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #93 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #94 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #95 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #96 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #97 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
 #98 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
 #99 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#100 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#101 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#102 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#103 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#104 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#105 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#106 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#107 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#108 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#109 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#110 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#111 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#112 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#113 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#114 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#115 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#116 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#117 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#118 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#119 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#120 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#121 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#122 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#123 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#124 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#125 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#126 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#127 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#128 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#129 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#130 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#131 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#132 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#133 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#134 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#135 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#136 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#137 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#138 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#139 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#140 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#141 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#142 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#143 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#144 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#145 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#146 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#147 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#148 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#149 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#150 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#151 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#152 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#153 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#154 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#155 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#156 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#157 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#158 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#159 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#160 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#161 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#162 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#163 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#164 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#165 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#166 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#167 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#168 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#169 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#170 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#171 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#172 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#173 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#174 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#175 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#176 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#177 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#178 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#179 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#180 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#181 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#182 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#183 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#184 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#185 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#186 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#187 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#188 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#189 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#190 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#191 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#192 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#193 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#194 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#195 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#196 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#197 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#198 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#199 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#200 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#201 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#202 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#203 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#204 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#205 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#206 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#207 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#208 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#209 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#210 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#211 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#212 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#213 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#214 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#215 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#216 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#217 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#218 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#219 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#220 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#221 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#222 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#223 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#224 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#225 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#226 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#227 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#228 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#229 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#230 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#231 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#232 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#233 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#234 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#235 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#236 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#237 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#238 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#239 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#240 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#241 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#242 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#243 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#244 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#245 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#246 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#247 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#248 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#249 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#250 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#251 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#252 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#253 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
#254 0x00005575a538d199 clang::tidy::utils::ExceptionSpecAnalyzer::analyze(clang::FunctionDecl const*) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c7199)
#255 0x00005575a538d68e clang::tidy::utils::ExceptionSpecAnalyzer::analyzeRecord(clang::CXXRecordDecl const*, clang::tidy::utils::ExceptionSpecAnalyzer::DefaultableMemberKind, clang::tidy::utils::ExceptionSpecAnalyzer::SkipMethods) (external/llvm_toolchain_llvm/bin/clang-tidy+0x14c768e)
```

### PR DESCRIPTION
**Pull request by PiotrZSL**
Normally endless recursion should not happen in ExceptionSpecAnalyzer, but if AST would be malformed (missing include), this could cause crash.

I run into this issue when due to missing include constructor argument were parsed as FieldDecl.
As checking for recursion cost nothing, why not to do this in check just in case.

Fixes #111436

### CODE REVIEW

**Comment by carlosgalvezp** [comment]
Being totally unfamiliar with the code, I have a feeling that we shouldn't be fixing in the `analyze` function. `analyze` has 1 single responsibility: wrap `analyzeImpl` in order to add cacheability for performance reasons, and it does so simply and well, and it does exactly what one would expect - no more no less.

However, the real problem is that `analyzeImpl` ultimately might end up calling itself, via `analyzeUnresolvedOrDefaulted -> analyzeRecord -> analyze -> analyzeImpl` (IIRC). This is not obvious due to how the code is written, and this patch would make it even less obvious IMO. 

In that sense I believe it would make sense to ensure no recursion happens somewhere in the chain I described above, not in `analyze`. WDYT?

**Comment by PiotrZSL** [comment]
I put it into `analyze` because when running this locally I seen that `analyze` show up repeatedly in stacktrace. Even in chain that you showed we still got `analyze` in this chain. And adding protection there is cheap, as we can easily utilize cached map to do that, instead of adding more maps. Also this issue isn't something that should happen often, I run into it only because I got malformed AST in first place. This is other reason why I would prefer to fix it in current way.

**Comment by carlosgalvezp** [comment]
To clarify, I'm not concerned about performance, but with code readability and maintainability. 

I realize the chain that I wrote above should not lead to recursion due to `SkipMethods::Yes` in the relevant call. I'd like to take a closer look at the problem, would you be able to share some of the stacktrace that shows how the recursion is happening?

**Comment by AMS21** [comment]
I think this is a very reasonable change and something I didn't think about when implementing it originally.
LGTM :+1:

**Comment by 5chmidti** [comment]
There is a minimal repro in #111436 available

**Comment by layus** [comment]
@PiotrZSL What are the chances of landing this as-is ? Does this require the changes mentioned by @carlosgalvezp ?

**Comment by PiotrZSL** [comment]
Actually only thing that were missing were example.
Added test. I'm not adding release notes as this is crash on invalid anyway, and I don't want to add multiple entrys, as this impact multiple checks.

**Review by 5chmidti — COMMENTED** [review]
> Being totally unfamiliar with the code, I have a feeling that we shouldn't be fixing in the analyze function. analyze has 1 single responsibility: wrap `analyzeImpl` in order to add cacheability for performance reasons, it does so simply and well, and it does exactly what one would expect - no more no less.

This class could maintain a stack-like `SmallVector` to check for an infinite recursion., so instead of checking the function cache (which might be large), only a few functions have to be compared this way.

**Comment by PiotrZSL** [comment]
> This class could maintain a stack-like `SmallVector` to check for an infinite recursion., so instead of checking the function cache (which might be large), only a few functions have to be compared this way.

Actually this change does not impact performance. Before we had 2 lookups, and now we still got 2 lookups.

**Review by 5chmidti — APPROVED** [review]
LGTM, but please add a release note about fixing the infinite recursion

**Comment by 5chmidti** [comment]
And maybe @carlosgalvezp wants to comment

File: clang-tools-extra/test/clang-tidy/checkers/performance/noexcept-move-constructor-crash.cpp [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// RUN: %check_clang_tidy -std=c++17 -expect-clang-tidy-error  %s performance-noexcept-move-constructor %t
```
Comment (carlosgalvezp) [inline clang-tools-extra/test/clang-tidy/checkers/performance/noexcept-move-constructor-crash.cpp:1]: Does this need to be a separate file? Can't we just have it in an existing test, inside `namespace PRXXXXX`?

**Comment by carlosgalvezp** [comment]
LGTM, had a small comment. Not sure it's worth mentioning this in the releases notes, it's just a crash fix. But it doesn't hurt I guess.
