### PR TITLE
[Clang] Fix cleanup attribute by delaying type checks after the type is deduced

### LINKED ISSUE #129631: [clang] the "cleanup" attribute prevents type deduction
```cpp
/* a.cpp */
int open() { return 0; }
void close(decltype(open()) *) {}
int main() {
  auto fd [[gnu::cleanup(close)]] = open();
}
```

```bash
$ clang-21 a.cpp
a.cpp:4:26: error: 'cleanup' function 'close' parameter has type 'decltype(open()) *' (aka 'int *') which is incompatible with type 'auto *'
    4 |   auto fd [[gnu::cleanup(close)]] = open();
      |                          ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by to268**
Previously, the handling of the `cleanup` attribute had some checks based on the type, but we were deducing the type after handling the attribute.
This PR fixes the way the are dealing with type checks for the `cleanup` attribute by delaying these checks after we are deducing the type.

It is also fixed in a way that the solution can be adapted for other attributes that does some type based checks.
This is the list of C/C++ attributes that are doing type based checks and will need to be fixed in additional PRs:
- CUDAShared
- MutualExclusions
- PassObjectSize
- InitPriority
- Sentinel
- AcquireCapability
- RequiresCapability
- LocksExcluded
- AcquireHandle

NB: Some attributes could have been missed in my shallow search.

Fixes #129631

### CODE REVIEW

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -4765,6 +4769,8 @@ class Sema final : public SemaBase {
   // linkage or not.
   static bool mightHaveNonExternalLinkage(const DeclaratorDecl *FD);
 
+  #include "clang/Sema/AttrIsTypeDependent.inc"
```
Comment (to268) [inline clang/include/clang/Sema/Sema.h]: I would guess this is the most compelling place to import the new TableGen function.

**Review by erichkeane — APPROVED** [review]
1 suggestion on how to improve tablegen, else LGTM.

File: clang/include/clang/Basic/Attr.td [hunk 2]
```diff
@@ -737,6 +737,9 @@ class Attr {
   // our existing general parsing we need to have a separate flag that
   // opts an attribute into strict parsing of attribute parameters
   bit StrictEnumParameters = 0;
+  // Set to true for attributes which have Sema checks which requires the type
+  // to be deduced.
```
Comment (AaronBallman) [inline clang/include/clang/Basic/Attr.td]: Might be worth adding a code example of when this would be set to true?

**Review by AaronBallman — APPROVED** [review]
LGTM aside from a comment request, feel free to keep or ignore the suggestion.

**Comment by to268** [comment]
As found by Aaron, there is an additional bug with templated types that will need to be fixed before landing this PR.
See: https://godbolt.org/z/8E83bx7jK
I am currently getting the same diagnostic emitted in the `test2()` function.

**Comment by to268** [comment]
Basically, it is about the way template type parameters are deduced.
The `Ty` template type parameter should be referring to the `int` type in the following example:
```cpp
int open() { return 0; }
void close(decltype(open()) *) {}

template <typename Ty>
void test() {
  Ty fd [[gnu::cleanup(close)]] = open(); // error: 'cleanup' function 'close' parameter has type 'decltype(open()) *' (aka 'int *') which is incompatible with type 'Ty *'
}

int main() {
  test<int>();
}
```
The fix would be to trigger the deduction of the template parameter, which should transform the `Ty *` to a `int *` type, which would be a compatible type.
I have heard that the deducing logic is triggered based on a TableGen file, but I do not find where would it be.

**Comment by erichkeane** [comment]
> > Basically, it is about the way template type parameters are deduced. The `Ty` template type parameter should be referring to the `int` type in the following example:
> > ```c++
> > int open() { return 0; }
> > void close(decltype(open()) *) {}
> > 
> > template <typename Ty>
> > void test() {
> >   Ty fd [[gnu::cleanup(close)]] = open(); // error: 'cleanup' function 'close' parameter has type 'decltype(open()) *' (aka 'int *') which is incompatible with type 'Ty *'
> > }
> > 
> > int main() {
> >   test<int>();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The fix would be to trigger the deduction of the template parameter, which should transform the `Ty *` to a `int *` type, which would be a compatible type. I have heard that the deducing logic is triggered based on a TableGen file, but I do not find where would it be.
> 
> Ah, hmm... This seems more to me that the VarDecl has yet to be instantiated at the point of checking (this isn't really deduction at that point?). So I suspect we're checking the 'type' for the purpose of the attribute too soon. I'll have to build locally, but I'll see if I can figure out where we decide on that. But basically, we need to make sure the type is completely instantiated before we check.
> 
> I would presume this is either a case of passing the wrong type to the attribute checking/wrong declaration, or doing the attribute checking too early.
```
diff --git a/clang/lib/Sema/SemaDeclAttr.cpp b/clang/lib/Sema/SemaDeclAttr.cpp
index 2afe50614cd7..30b71e1fc2a5 100644
--- a/clang/lib/Sema/SemaDeclAttr.cpp
+++ b/clang/lib/Sema/SemaDeclAttr.cpp
@@ -8308,10 +8308,13 @@ void Sema::ActOnCleanupAttr(Decl *D, const Attr *A) {
   CleanupAttr *Attr = D->getAttr<CleanupAttr>();
   FunctionDecl *FD = Attr->getFunctionDecl();
   DeclarationNameInfo NI = FD->getNameInfo();
+  VarDecl *VD = cast<VarDecl>(D);
+  if (VD->getType()->isDependentType())
+    return;
 
   // We're currently more strict than GCC about what function types we accept.
   // If this ever proves to be a problem it should be easy to fix.
-  QualType Ty = this->Context.getPointerType(cast<VarDecl>(D)->getType());
+  QualType Ty = this->Context.getPointerType(VD->getType());
   QualType ParamTy = FD->getParamDecl(0)->getType();
   if (!this->IsAssignConvertCompatible(this->CheckAssignmentConstraints(
           FD->getParamDecl(0)->getLocation(), ParamTy, Ty))) {

```

^^ Something like that.  Please make sure you have tests for the mismatch happening AFTER template instantiation however.

File: clang/lib/Sema/SemaDecl.cpp [hunk 3]
```diff
@@ -3355,6 +3355,15 @@ void Sema::mergeDeclAttributes(NamedDecl *New, Decl *Old,
   if (!foundAny) New->dropAttrs();
 }
 
+void Sema::CheckAttributesOnDeducedType(Decl *D) {
+  if (!D->hasAttrs())
```
[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp]: OH! I meant the call to `hasAttrs`/early exit, since the loop does this kinda automagically.

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp]: OH!  Just use `.attrs` instead of `getAttrs` then.

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp]: The fucntion is probably worth it, just from an expressiveness perspective, so I wouldn't bother.  it also gives us a place to customize it in the future if we ever need to extend this.

**Review by erichkeane — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
Aside from a few nits, I'm happy if @erichkeane is happy

File: clang/lib/Sema/SemaDeclAttr.cpp [hunk 4]
```diff
@@ -8311,3 +8301,28 @@ void Sema::redelayDiagnostics(DelayedDiagnosticPool &pool) {
   assert(curPool && "re-emitting in undelayed context not supported");
   curPool->steal(pool);
 }
+
+void Sema::ActOnCleanupAttr(Decl *D, const Attr *A) {
+  VarDecl *VD = cast<VarDecl>(D);
+  if (VD->getType()->isDependentType())
```
Comment (shafik) [inline clang/lib/Sema/SemaDeclAttr.cpp]: Based on my reading of the documentation in Attr.td this seems like it should be an assert on `!VD->getType()->isDependentType()` right?

Comment (to268) [reply clang/lib/Sema/SemaDeclAttr.cpp]: Well no, if `isDependentType()` is true we would delay (by exiting the function early) till the template has been instantiated before trying to do type checks. After template instantiation, this function is called again and would perform type checks as usual.

**Comment by to268** [comment]
Can you give me a godbolt link, so I can investigate?

**Comment by to268** [comment]
> oh I mean the error that is produced now is correct, the lack of an error previously was absolutely correct as failing to produce an error means we end up leaking objects. So there isn't a follow up here, just fixing projects that are now hitting this error.

I see, it's better that this bug fix creates a positive ripple effect that also fixes that bug that was also existing in objc. This PR and the following PRs that will land (hopefully soon) for all attributes listed above are mainly C/C++ related. I think that I've seen some type dependant attributes that are specific to objc but I haven't added them to this list, as I've done a rough search of potentially affected attributes.
