### PR TITLE
[flang][driver] Improve diagnostic for assembly inputs

### LINKED ISSUE #173528: [flang][Driver] The driver emits an abstruse message when assembly code is passed to it
When assembly code is passed to the Flang driver, it emits the following message:

```console
$ flang test.s
error: unknown integrated tool '-cc1as'. Valid tools include '-fc1'.
```

The driver currently does not accept assembly code. Clang should be invoked instead, but this is not indicated. Therefore, the message should be improved as follows:

```console
$ flang test.s
error: Currently, the driver does not accept assembly code. Use clang instead. Note that '-lflang_rt.runtime -lm' is required for linking.
```

Moreover, it would be better for the driver to accept assembly code, as other Fortran compilers do.

### PR DESCRIPTION
**Pull request by soumikiith**
When an assembly file is passed to the Flang driver, it currently fails with a confusing internal error mentioning the unsupported `-cc1as` tool.

This update detects assembly inputs early in the driver and emits a clear, user-facing diagnostic explaining that Flang does not support assembly files as input. The logic is implemented in a small helper function and is intentionally temporary, so it can be removed once Flang gains support for assembling inputs.

Fixes: #173528

### CODE REVIEW

**Review by tarunprabhu — CHANGES_REQUESTED** [review]
There are a number of failing tests. Are these related to your changes? If so, please fix these before we can proceed.

File: flang/tools/flang-driver/driver.cpp [hunk 1]
```diff
@@ -147,6 +147,31 @@ int main(int argc, const char **argv) {
   llvm::SmallVector<std::pair<int, const clang::driver::Command *>, 4>
       failingCommands;
 
+  // Reject assembly files as flang does not support assembling
+  if (c) {
+    for (const llvm::opt::Arg *arg : c->getInputArgs()) {
+      if (arg->getOption().getKind() != llvm::opt::Option::InputClass)
```
Comment (tarunprabhu) [inline flang/tools/flang-driver/driver.cpp]: Is this check necessary? Can `getInputArgs()` return arg's where `kind != Option::InputClass`? It feels odd to me. Do you mind checking what `getInputArgs()` does?

**Review by tarunprabhu — CHANGES_REQUESTED** [review]
Thanks for the update. This is looking quite a bit better. I am still not convinced that this is the best place to check for input assembly files, but a better one does not immediately come to mind, so let's leave it here for the time being.

In that case, could you move your code into a separate function? This code is inherently "temporary" since we would like to have flang handle assembly files eventually (particularly since clang can already do so).  In that case, moving this code to a separate function will keep the original logic relatively clean, and also provide a self-contained unit that can be easily removed when this support is added. 

What do you think?

**Review by tarunprabhu — COMMENTED** [review]
Thanks for the changes and for looking into the behavior of `getInputArgs()` and `BuildCompilation`.

**Review by tarunprabhu — APPROVED** [review]
We're almost done! :-) Thanks for all the changes.

Do you have commit access? If you do, please check that the commit message accurately reflects what this PR does.

If not, please see the last part of the section on [commit messages in the developer policy](https://llvm.org/docs/DeveloperPolicy.html#commit-messages), particularly the part about updating the PR description. This will ensure that whoever merges this does not have to edit the commit message.

[EDIT: Remove redundant sentence]

**Comment by eugeneepshteyn** [comment]
@soumikiith , you don't need to repeat "[flang][driver] Improve diagnostic for assembly input files" in PR description, it'll be taken from the title.

**Comment by soumikiith** [comment]
> I think this can be committed. It is better not to do this over the weekend on the off chance that something breaks. If you don't have commit access, we'll merge it early next week.

I do not have commit access.

**Comment by eugeneepshteyn** [comment]
@soumikiith to double-check, did you run (1) `ninja check-flang` and (2) llvm-test-suite Fortran tests with this change?

**Review by yus3710-fj — COMMENTED** [review]
Thank you for your great work, and I apologize for the delayed comment.
I'm not familiar with the implementation of the driver, but I'm wondering if you can implement this in `Driver::BuildInputs`. It seems to have a mechanism similar to your implementation.

NOTE: This is not a strong opinion. The current implementation still looks good to me.

**Comment by soumikiith** [comment]
@yus3710-fj sure i will look into the test and as well as whether the implementation can be put into the BuildInputs. 

@eugeneepshteyn I have run make check-flang, which did not give any wrong outputs. Perhaps , that is same as ninja check-flang? Please provide feedback regarding that.

**Comment by yus3710-fj** [comment]
@tarunprabhu Thank you for your comment on my suggestion. That's a good point.
I understand that this is a temporary fix, and our goal is to make Flang accept assembly files. So, it would be okay to keep the implementation within Flang's codebase.

> The caveat here is that I am not sure how much effort would be needed to build an assembler for flang (`fc1as` analogous to `cc1as`) - so it may well be that we don't support assembling for some time.

That is exactly what I'm concerned about. If @soumikiith already has a plan to fix the issue, then my worry is needless.
(IMHO, there would be several approaches, each with its own pros and cons. We might need a discussion about that, but it's outside the scope of this PR.)

**Review by yus3710-fj — APPROVED** [review]
LGTM. Thank you for the fix!

**Review by tarunprabhu — APPROVED** [review]
Thanks for all the changes and for seeing it through. If you don't have merge permissions, I can do that in the next day or so.
