### PR TITLE
[clang-format] Make bitwise and imply requires clause

### LINKED ISSUE #110485: clang-format breaks for a member function with both a reference qualifier and a trailing requires clause
From clang-format 19, member functions containing *both* a reference qualifier and a trailing requires clause, results in broken formatting until the closing brace of the following member function.
> cat test.cpp
```
template <int n> struct S
{
  void f() & requires(n == 1) {}

  // some comment
  void g() {}
};
```
> clang-format-19 test.cpp
```
template <int n> struct S
{
  void f() & requires(n == 1) {}

      // some comment
      void g()
  {
  }
};
```
Note the indentation of the `// some comment` and `void g()`, which is obviously incorrect. (Additional custom brace wrapping options are also ignored after the definition of `f`, but the above is just a simplified example without a custom .clang-format).

The expected output is what clang-format 18 gives:
> clang-format-18 test.cpp
```
template <int n> struct S
{
  void f() &
  requires(n == 1)
  {
  }

  // some comment
  void g() {}
};
```
This bug doesn't manifest when using explicit object parameters, so there *is* a workaround for now, but it would nice to avoid that change.

### PR DESCRIPTION
**Pull request by rymiel**
This patch adjusts the requires clause/expression parser to imply a requires clause if it is preceded by a bitwise and operator `&`, and assume it is a reference qualifier. The justification is that bitwise operations should not be used for requires expressions.

This is a band-aid fix. The real problems lie in the lookahead heuristic in the same method. It may be worth it to rewrite that whole heuristic to track more state in the future, instead of just blindly marching forward across multiple unrelated definitions, since right now, the definition following the one with the requires clause can influence whether the heuristic chooses clause or expression.

Fixes https://github.com/llvm/llvm-project/issues/110485

### CODE REVIEW

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 1]
```diff
@@ -3528,6 +3528,17 @@ bool UnwrappedLineParser::parseRequires() {
...
+    case tok::greaterequal:
+    case tok::lessequal:
+    case tok::r_paren:
+    case tok::pipepipe:
+      if (OpenAngles == 0) {
+        FormatTok = Tokens->setPosition(StoredPosition);
+        parseRequiresClause(RequiresToken);
+        return true;
+      }
+      break;
```
Comment (owenca) [inline clang/lib/Format/UnwrappedLineParser.cpp:3541]: Instead, how about just moving `case tok::amp:` up?
```
--- a/clang/lib/Format/UnwrappedLineParser.cpp
+++ b/clang/lib/Format/UnwrappedLineParser.cpp
@@ -3474,10 +3474,10 @@ bool UnwrappedLineParser::parseRequires() {
   case tok::r_paren:
   case tok::kw_noexcept:
   case tok::kw_const:
+  case tok::amp:
     // This is a requires clause.
     parseRequiresClause(RequiresToken);
     return true;
-  case tok::amp:
   case tok::ampamp: {
     // This can be either:
     // if (... && requires (T t) ...)
```
The rationale is that it doesn't make sense to bitwise-and another expression with a `requires` expression.

Comment (rymiel) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: Then wouldn't r-value reference methods still be broken? Those still exist even if they're rare. I mean, we can do both

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: My suggested change (in place of yours) passes all the existing tests and the new tests you add here. Can you give a counterexample?

Comment (rymiel) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: What about the original issue but with an r-value ref-qualifier instead of an l-value one:
```c++
template <int n> struct S
{
  void f() && requires(n == 1) {}

  // some comment
  void g() {}
};
```

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: Nvm. This would fail:
```
template <int n> struct S
{
  void f() &&
  requires(n == 1)
  {
  }

  // some comment
  void g() {}
};
```

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: What about `<` and `>`?
```
template <int n> struct S {
  void f() &
    requires(n < 1)
  {}

  // some comment
  void g() {}
};
```

Comment (rymiel) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: It gets complicated with template parameters :(
Like I said in the pr description, it's probably a better idea to redo that whole lookahead thing to be a little more smart. But I also don't have the energy for that so I just offered this bandaid fix

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:3541]: If we are doing a limited fix now, maybe just move the `case tok::amp:` up as suggested above? It would cover patterns similar to that in #110485 no matter what operator is used in the parenthesized expression after `& requires`.

**Review by owenca — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -1296,6 +1296,15 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
   Tokens = annotate("bool x = t && requires(Foo<C1 || C2> x) { x.foo(); };");
   ASSERT_EQ(Tokens.size(), 25u) << Tokens;
   EXPECT_TOKEN(Tokens[5], tok::kw_requires, TT_RequiresExpression);
+
+  // Second function definition is required due to lookahead
+  Tokens = annotate("void f() &\n"
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1301]: I'm not against rewriting the heuristic, if you know a better one. But for this example could one not extent the look behind? Than it would also work for r-value references.

Or try to annotate the reference marker and match on that?

Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1301]: > I'm not against rewriting the heuristic, if you know a better one. But for this example could one not extent the look behind? Than it would also work for r-value references.

No, because we can't tell if the r_paren before `&& requires` is a function decl r_paren?

> Or try to annotate the reference marker and match on that?

No, because we're in `UnwrappedLineParser`?
