### PR TITLE
[lldb] Analyze enum promotion type during parsing

### LINKED ISSUE #86989: [LLDB] Incorrect type promotion of an unscoped enum with the default type in arithmetic operations
When using an enum value in an arithmetic operation LLDB promotes the resulting type to `unsigned int`, and not to the default underlying type `int`.

Source code with 2 variables with the results from a compiler:
```
enum UnscopedEnum { Zero, One };

int main() {
  auto enum_one = UnscopedEnum::One;
  auto negated = -enum_one;
  auto added = enum_one + 1;
  return 0;
}
```

LLDB log:
```
(lldb) expr negated
(int) $0 = -1
(lldb) expr added
(int) $1 = 2

(lldb) expr -enum_one
(unsigned int) $2 = 4294967295
(lldb) expr enum_one + 1
(unsigned int) $3 = 2
```

If the enum type is explicitly specified `enum UnscopedEnum : int`, then the promotion works correctly.

### PR DESCRIPTION
**Pull request by kuilpd**
The information about an enum's best promotion type is discarded after compilation and is not present in debug info. This patch repeats the same analysis of each enum value as in the front-end to determine the best promotion type during DWARF info parsing.

Fixes #86989

### CODE REVIEW

**Comment by kuilpd** [comment]
My thought process for this patch: https://github.com/llvm/llvm-project/issues/86989#issuecomment-2438116468

**Comment by Michael137** [comment]
I haven't done an in-depth review of the patch yet but my first instinct here is that this looks like a lot of work for LLDB which the compiler has already done, so we ideally don't want to repeat. Where is this actually an issue from a user perspective? In the example you gave one could just cast to the appropriate enum type and get the bit-mask style presentation:
```
(lldb) expr (UnscopedEnum) (-enum_one)
(UnscopedEnum) $0 = One | 0xfffffffe
```
Not that this shouldn't be fixed, just weighing of the amount of complexity added here versus the benefit.

Also, is this promotion-type something that can be encoded in DWARF? GCC generates the same DWARF as Clang here. What happens if we make the type of the `DW_TAG_variable`s be `UnscopedEnum` instead of `int`? I guess that wouldn't help with
```
(lldb) expr UnscopedEnum::One + 1
```

**Comment by labath** [comment]
I'm worried about the same thing as Michael. My question is: if the promotion type can be computed from the information in dwarf (can it always?), and clang already has code to compute it (not from DWARF, but from.. clang AST I guess), can we refactor that code somehow so that it is usable from lldb as well?

**Comment by kuilpd** [comment]
> Not that this shouldn't be fixed, just weighing of the amount of complexity added here versus the benefit.

I don't really know how useful it is in general to know the actual promotion type of the enum, I guess only for using enum values in expressions without explicit casting.

> Also, is this promotion-type something that can be encoded in DWARF? GCC generates the same DWARF as Clang here. 

From what I could tell there is nothing in the DWARF spec that allows to hold a promotion type of an enum. We could just use some undocumented field, but then it wouldn't work with GCC binaries.

> My question is: if the promotion type can be computed from the information in dwarf (can it always?), and clang already has code to compute it (not from DWARF, but from.. clang AST I guess), can we refactor that code somehow so that it is usable from lldb as well?

It can be computed if all the enum values are present in DWARF. I thought about reusing the code from Sema as well, but it uses different interface to iterate through every value, and does other analysis along the way which is not needed during debugging anymore. Plus the patch allows to remove some of the erroneous analysis in [TypeSystemClang.cpp](https://github.com/llvm/llvm-project/pull/115005/files#diff-3a759ae917207e962f79e48fa280277099a587c11bc1f1385e64000c03d6b6a2)

**Comment by kuilpd** [comment]
Ping

**Comment by kuilpd** [comment]
So, is this patch worth pursuing or is it too much code for a too specific use case?

**Comment by Michael137** [comment]
> So, is this patch worth pursuing or is it too much code for a too specific use case?

Sorry I was out for a few weeks when you pinged. I'll have another pass/think about it early next week (if nobody else gets to it before me).

File: lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp [hunk 1]
```diff
@@ -8544,7 +8524,8 @@ clang::EnumConstantDecl *TypeSystemClang::AddEnumerationValueToEnumerationType(
   bool is_signed = false;
   underlying_type.IsIntegerType(is_signed);
 
-  llvm::APSInt value(enum_value_bit_size, is_signed);
+  // APSInt constructor's sign argument is isUnsigned
+  llvm::APSInt value(enum_value_bit_size, !is_signed);
```
Comment (Michael137) [inline lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp:8528]: Good catch, how about we split this out into a separate PR?

Comment (Michael137) [reply lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp:8528]: Also, no need for the comment

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 2]
```diff
@@ -2299,11 +2301,103 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
...
+  auto &Context = m_ast.getASTContext();
+  unsigned LongWidth = Context.getTargetInfo().getLongWidth();
+  unsigned IntWidth = Context.getTargetInfo().getIntWidth();
+  unsigned CharWidth = Context.getTargetInfo().getCharWidth();
+  unsigned ShortWidth = Context.getTargetInfo().getShortWidth();
+
+  bool is_cpp = Language::LanguageIsCPlusPlus(
+      SymbolFileDWARF::GetLanguage(*parent_die.GetCU()));
+
+  if (NumNegativeBits) {
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2357]: My preference would be to factor out these two if blocks from Sema into one (or two) helpers. It could look like:
```
std::pair</*BestWidth=*/unsigned, /*BestPromotionType=*/clang::QualType>
ComputeBestEnumProperties(unsigned NumNegativeBits, unsigned NumPositiveBits, bool IsPacked) {
  if (NumNegativeBits) {
    ...
  } else {
    ...
  }
}
```

Then LLDB would always pass `IsPacked=false` for now (we don't encode it in DWARF, but *maybe* could derive it? we have this problem already with packed structures anyway).

With this in place i think this patch seems very reasonable!

Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: If I understood you correctly, I created this separate function in clang's SemaDecl.cpp, and then called it from both LLDB and Sema itself. Seems to be working, but it needed a lot of arguments, since when called from LLDB Sema doesn't have any information stored at all, so ASTContext, EnumDecl and other arguments have to come from LLDB, and it also returns 3 values.
This looks clunky because of it, any suggestions how to make it better?

File: lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp (hunk 1 above)
Comment (kuilpd) [reply lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp]: Made a PR #120794, once it's merged I will rebase this branch on main and run tests again.

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 2 above)
Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Thanks for trying this out! It doesn't look *aweful* in my opinion (considering the code duplication that it prevents). I think the best thing to do here is to split the Clang changes out into a separate PR. That would also give you more visibility from the Clang maintainers. If you didn't want to have all those output parameters you could return a tuple or maybe even a helper structure that encapsulates all those arguments. Either way, I'm sure they'll be some useful feedback on the Clang PR

**Comment by kuilpd** [comment]
@Michael137 
Reused the code I merged in #120965 to get the best promotion type.

File: clang/include/clang/AST/Decl.h [hunk 3]
```diff
@@ -3903,6 +3903,7 @@ class EnumDecl : public TagDecl {
   void setInstantiationOfMemberEnum(ASTContext &C, EnumDecl *ED,
                                     TemplateSpecializationKind TSK);
 
+public:
```
Comment (Michael137) [inline clang/include/clang/AST/Decl.h:3906]: Don't need this change anymore

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 4]
```diff
@@ -2367,11 +2369,38 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
...
+        NumPositiveBits = std::max({NumPositiveBits, ActiveBits, 1u});
+      } else {
+        NumNegativeBits =
+            std::max(NumNegativeBits, (unsigned)InitVal.getSignificantBits());
+      }
     }
   }
+
+  if (!NumPositiveBits && !NumNegativeBits)
+    NumPositiveBits = 1;
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2391]: Could you leave a comment on why we do this?

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 5]
```diff
@@ -2367,11 +2369,38 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
...
           clang_type, decl, name, enum_value, enumerator_byte_size * 8);
       ++enumerators_added;
+
+      llvm::APSInt InitVal = ECD->getInitVal();
+      // Keep track of the size of positive and negative values.
+      if (InitVal.isUnsigned() || InitVal.isNonNegative()) {
+        // If the enumerator is zero that should still be counted as a positive
+        // bit since we need a bit to store the value zero.
+        unsigned ActiveBits = InitVal.getActiveBits();
+        NumPositiveBits = std::max({NumPositiveBits, ActiveBits, 1u});
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2382]:
```suggestion
        NumPositiveBits = std::max(InitVal.getActiveBits(), 1u);
```

`NumPositiveBits` is 0 at this point anyway right?

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 6]
```diff
@@ -2367,11 +2369,38 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
...
+
+  clang::EnumDecl *enum_decl =
+      ClangUtil::GetQualType(clang_type)->getAs<clang::EnumType>()->getDecl();
+  enum_decl->setNumPositiveBits(NumPositiveBits);
+  enum_decl->setNumNegativeBits(NumNegativeBits);
+
+  clang::QualType BestPromotionType;
+  clang::QualType BestType;
+  m_ast.getASTContext().computeBestEnumTypes(
+      false, NumNegativeBits, NumPositiveBits, BestType, BestPromotionType);
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2401]:
```suggestion
      /*IsPacked=*/false, NumNegativeBits, NumPositiveBits, BestType, BestPromotionType);
```

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 7]
```diff
@@ -2367,11 +2369,38 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
...
+      llvm::APSInt InitVal = ECD->getInitVal();
+      // Keep track of the size of positive and negative values.
+      if (InitVal.isUnsigned() || InitVal.isNonNegative()) {
+        // If the enumerator is zero that should still be counted as a positive
+        // bit since we need a bit to store the value zero.
+        unsigned ActiveBits = InitVal.getActiveBits();
+        NumPositiveBits = std::max({NumPositiveBits, ActiveBits, 1u});
+      } else {
+        NumNegativeBits =
+            std::max(NumNegativeBits, (unsigned)InitVal.getSignificantBits());
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2385]: Isn't `NumNegativeBits == 0` at this point anyway? Can we just unconditionally assign `getSignificantBits`?

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2385]: Also, no need to cast to `unsigned` here I think

**Review by Michael137 — COMMENTED** [review]
Looks much better

Left some more clarification comments

File: clang/include/clang/AST/Decl.h (hunk 3 above)
Comment (kuilpd) [reply clang/include/clang/AST/Decl.h:3906]: I left this in so that that I could simply do `enum_decl->setNumPositiveBits` in `DWARFASTParserClang.cpp` and then retrieve it via `enum_decl->getNumPositiveBits` in `TypeSystemClang.cpp`.

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 5 above)
Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2382]: The condition checks that the value is just non negative unsigned, so I think the comment means that it could be zero, in which case the max function would prefer `1u` over it.

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 7 above)
Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2385]: This one is for when the value is just signed negative, can be anything, accumulates over all enum values.
This if/else is from [SemaDecl.cpp:L20084](https://github.com/llvm/llvm-project/blob/5d6d982df61d16b6d498e6d59dd91c059679d3d8/clang/lib/Sema/SemaDecl.cpp#L20084), but I don't think this few lines are worth putting into a separate function as well.

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2385]: Can we not just leave this whole block in TypeSystemClang::CompleteTagDeclarationDefinition? That way you can just pass the `NumNegativeBits`/`NumPositiveBits` to `EnumDecl::completeDefinition`. Why do we need to move it over here?

File: clang/include/clang/AST/Decl.h (hunk 3 above)
Comment (Michael137) [reply clang/include/clang/AST/Decl.h:3906]: Can we not just leave this whole block in `TypeSystemClang::CompleteTagDeclarationDefinition`? That way you can just pass the `NumNegativeBits`/`NumPositiveBits` to `EnumDecl::completeDefinition` like we used to. Why do we need to move it over here?

Comment (Michael137) [reply clang/include/clang/AST/Decl.h:3906]: I see why you moved it. It's because we're iterating over the enumerator values there. But i think it's still possible to do it from TypeSystemClang (see my other comment: https://github.com/llvm/llvm-project/pull/115005/files#r1931986605)

File: lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+"""
+
+import lldb
+from lldbsuite.test.decorators import *
+from lldbsuite.test.lldbtest import *
+from lldbsuite.test import lldbutil
+
+
+class TestCPPEnumPromotion(TestBase):
+    @skipIf(debug_info=no_match(["dwarf", "dwo"]))
```
Comment (Michael137) [inline lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py:12]: Any reason we're skipping this for `dSYM`s?

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 5 above)
Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: I don't think I can move the entire loop into a separate function, the way `DWARFASTParserClang` and `SemaDecl` iterate over enum values is completely different, so for now I just moved these few lines that determine the updated `NumPositiveBits` `NumNegativeBits`.

File: lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+"""
+
+import lldb
+from lldbsuite.test.decorators import *
+from lldbsuite.test.lldbtest import *
+from lldbsuite.test import lldbutil
+
+
+class TestCPPEnumPromotion(TestBase):
+    @skipIf(debug_info=no_match(["dwarf", "dwo", "dsym"]))
```
Comment (Michael137) [inline lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py:12]:
```suggestion

```

Comment (Michael137) [reply lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py:12]: No need to specify this at all

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp [hunk 10]
```diff
@@ -2367,11 +2369,36 @@ size_t DWARFASTParserClang::ParseChildEnumerators(
     }
 
     if (name && name[0] && got_value) {
-      m_ast.AddEnumerationValueToEnumerationType(
+      auto ECD = m_ast.AddEnumerationValueToEnumerationType(
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2372]: I do think you can move the iteration into a helper function on clang ASTContext. It would look something like this:
```
// In ASTContext class
template<typename RangeT>                                                  
bool computeEnumBits(unsigned &NumNegativeBits, unsigned &NumPositiveBits, 
                     RangeT Elements);
```
Then in `SemaDecl.cpp` you would call it as follows:
```
unsigned NumNegativeBits;                                                                            
unsigned NumPositiveBits;                                                                            
bool MembersRepresentableByInt =
    Context.computeEnumBits(NumNegativeBits, NumPositiveBits, Elements);
```
And in LLDB in `CompleteTagDeclarationDefinition`, you would call it like so:
```
ast.computeEnumBits(NumNegativeBits, NumPositiveBits, enum_decl->enumerators());
                                                                                
enum_decl->completeDefinition(enum_decl->getIntegerType(),                      
                              promotion_qual_type, NumPositiveBits,             
                              NumNegativeBits);                                 
```

Wdyt? And please do the Clang-side changes in a separate NFC PR

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 5 above)
Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: I left a comment on my latest review on how you might be able to do that. Once we did that I think we're good to land this! Thanks for the patience

File: lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp (hunk 10 above)
Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:2372]: Well... I tried this, it works, but I encountered some problems:
1. `computeEnumBits` definition has to be in the header file, otherwise template instantiation doesn't work. I tried making the elements argument an `ArrayRef`, but it's also not working well with `enum_decl->enumerators()` returning `llvm::iterator_range<specific_decl_iterator<EnumConstantDecl>>`
2. Iteration over elements in `SemaDecl.cpp` checks for the element is a `EnumConstantDecl`, otherwise it's skipped, so I had to create a separate collection in case something is removed, and then pass that one to `computeEnumBits`
3. `isRepresentableIntegerValue` is a static function in `SemaDecl.cpp`, I'd rather not move somewhere else as well, since it's not needed on LLDB side anyway

Mostly I'm just not sure if it's a problem or not that `ASTContext.h` contains a definition of a function.

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: > Mostly I'm just not sure if it's a problem or not that ASTContext.h contains a definition of a function.

Well if it's a template that has to be where it lives. Unless the Clang maintainers find a way to pass the iterator/arrayref as a non-template parameter I think this is fine

> isRepresentableIntegerValue is a static function in SemaDecl.cpp, I'd rather not move somewhere else as well, since it's not needed on LLDB side anyway

Yea I think that's also fine. If it's a private helper on `ASTContext`, I don't see that being a big deal. Especially because that doesn't need to be defined in the header.

> Iteration over elements in SemaDecl.cpp checks for the element is a EnumConstantDecl, otherwise it's skipped, so I had to create a separate collection in case something is removed, and then pass that one to computeEnumBits

Could you elaborate on this? LLDB only ever puts `EnumConstantDecl`s there right?

Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: > > Iteration over elements in SemaDecl.cpp checks for the element is a EnumConstantDecl, otherwise it's skipped, so I had to create a separate collection in case something is removed, and then pass that one to computeEnumBits
> 
> Could you elaborate on this? LLDB only ever puts `EnumConstantDecl`s there right?

This line: [SemaDecl.cpp:20070](https://github.com/llvm/llvm-project/blob/1141fd0bf847b54d9b12c3a0aff093c02792e4de/clang/lib/Sema/SemaDecl.cpp#L20070), if it discards something, I cannot pass the original `Elements` to `computeEnumBits`.

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Apologies I still don't follow. Why can't `computeEnumBits` just be:
```
  template <typename RangeT>
  bool computeEnumBits(RangeT EnumConstants, unsigned &NumNegativeBits,
                       unsigned &NumPositiveBits) {
    unsigned NumNegativeBits = 0;
    unsigned NumPositiveBits = 0;
    bool MembersRepresentableByInt = true;
    for (auto * Elem : EnumConstants) {
    EnumConstantDecl *ECD =
      cast_or_null<EnumConstantDecl>(Elem);
    if (!ECD) continue;  // Already issued a diagnostic.

      llvm::APSInt InitVal = ECD->getInitVal();
      if (InitVal.isUnsigned() || InitVal.isNonNegative()) {
        // If the enumerator is zero that should still be counted as a positive
        // bit since we need a bit to store the value zero.
        unsigned ActiveBits = InitVal.getActiveBits();
        NumPositiveBits = std::max({NumPositiveBits, ActiveBits, 1u});
      } else {
        NumNegativeBits =
            std::max(NumNegativeBits, (unsigned)InitVal.getSignificantBits());
      }

      MembersRepresentableByInt &=
          isRepresentableIntegerValue(InitVal, IntTy);
    }

    // If we have an empty set of enumerators we still need one bit.
    // From [dcl.enum]p8
    // If the enumerator-list is empty, the values of the enumeration are as if
    // the enumeration had a single enumerator with value 0
    if (!NumPositiveBits && !NumNegativeBits)
      NumPositiveBits = 1;

    return MembersRepresentableByInt;
  }
```

And `SemaDecl.cpp` just does:
```
  unsigned NumNegativeBits;
  unsigned NumPositiveBits;
  bool MembersRepresentableByInt = Context.computeEnumBits(Elements, NumNegativeBits, NumPositiveBits);
```
?

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Unless I'm missing something this should be identical behaviour.

Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Yes, but I didn't want to move `isRepresentableIntegerValue` outside of `SemaDecl.cpp`, so I moved only the part that checks the bits. Seemed unnecessary to both move the static function and also use call it from LLDB where the result wouldn't be used anyway.

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: That's totally fine (in my opinion). Just make it a private member of `ASTContext` and it won't bother anyone. Could you prepare such a patch in a separate PR and see what the Clang maintainers say?

Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: It's used in 5 other places in `SemaDecl.cpp`, unfortunately, so it will have to be yet another `ASTContext` function.

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Ah true, I still think it's worth doing. Worst case they recommend a different place to put these APIs. If anyone is strongly against this we can resort to your previous version I suppose

Comment (Michael137) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Feel free to link to this thread in that PR so they have context

Comment (kuilpd) [reply lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp]: Alright, will do, thank you!

**Comment by kuilpd** [comment]
@Michael137 
Changed the first argument of `computeEnumBits` to an `ArrayRef` to avoid the template and so it can be still seamlessly used from Sema.
On LLDB side, I had to create a `SmallVector` and put enum constants there at the point of their creation (`AddEnumerationValueToEnumerationType` returns a pointer anyway) so that it can be passed to `computeEnumBits` as is. It's only a vector of pointers, and it's discarded after, so if it's not a problem here, I'll make the same changes in the Sema PR.

**Comment by Michael137** [comment]
> @Michael137 Changed the first argument of `computeEnumBits` to an `ArrayRef` to avoid the template and so it can be still seamlessly used from Sema. On LLDB side, I had to create a `SmallVector` and put enum constants there at the point of their creation (`AddEnumerationValueToEnumerationType` returns a pointer anyway) so that it can be passed to `computeEnumBits` as is. It's only a vector of pointers, and it's discarded after, so if it's not a problem here, I'll make the same changes in the Sema PR.

I don't think they necessarily had an issue with the template. It'd be silly for us to pay for the cost of constructing an intermediate vector if we're in control of the API and could avoid the work altogether. I'll comment on the other PR but I'd rather not construct this temporary just so we can pass it as an `ArrayRef`

File: lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp [hunk 11]
```diff
@@ -8476,27 +8476,20 @@ bool TypeSystemClang::CompleteTagDeclarationDefinition(
 
   clang::ASTContext &ast = lldb_ast->getASTContext();
 
-  /// TODO This really needs to be fixed.
+  unsigned NumNegativeBits = 0;
```
Comment (Michael137) [inline lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp:8479]: Can we move this block back into the `if (!integer_type.isNull()) {` condition below?

**Review by Michael137 — APPROVED** [review]
Looks great! Thank you for moving all this functionality into Clang

LGTM (just one minor comment left)

**Comment by kuilpd** [comment]
@Michael137 
Thank you for seeing this through!

**Comment by Michael137** [comment]
let me know if you need me to merge this for you

**Comment by Michael137** [comment]
FYI on macOS CI this is failing with:
```
FAIL: test_dsym (TestCPPEnumPromotion.TestCPPEnumPromotion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1784, in test_method
    return attrvalue(self)
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/lldb/test/API/lang/cpp/enum_promotion/TestCPPEnumPromotion.py", line 28, in test
    self.expect_expr("+EnumUChar::UChar", result_type=UChar_promoted.type.name)
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2540, in expect_expr
    value_check.check_value(self, eval_result, str(eval_result))
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 299, in check_value
    test_base.assertSuccess(val.GetError())
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2575, in assertSuccess
    self.fail(self._formatMessage(msg, "'{}' is not success".format(error)))
AssertionError: 'error: <user expression 0>:1:2: use of undeclared identifier 'EnumUChar'
    1 | +EnumUChar::UChar
      |  ^
' is not success
```

But only for dSYMs. Looking at the `dSYM`, none of the enums are actually preserved in the debug-info. You have to actually use the enum types in source to get dsymutil to preserve them. I'll fix it

**Comment by kuilpd** [comment]
> But only for dSYMs. Looking at the `dSYM`, none of the enums are actually preserved in the debug-info. You have to actually use the enum types in source to get dsymutil to preserve them. I'll fix it

Ah, I see. Thank you for handling this!

**Comment by Michael137** [comment]
Fixed in `0feb00f17cbaac7428dcb7aed13d903b65974978`
