### PR TITLE
LSV: forbid load-cycles when vectorizing; fix bug

### LINKED ISSUE #37865: opt hangs in LoadStoreVectorizer
|  |  |
| --- | --- |
| Bugzilla Link | [38517](https://llvm.org/bz38517) |
| Version | trunk |
| OS | Linux |
| Attachments | [reproducer with nested load](https://user-images.githubusercontent.com/55792694/143757896-f45b726b-451d-4c56-9ef0-394fbdad3791.gz) |
| CC | @bevin-hansson,@mikaelholmen |

## Extended Description 

Running 
  opt -load-store-vectorizer -o tmp.opt.ll tmp.ll
with the attached reproducer, the LoadStoreVectorizer hangs in an endless loop.

The originating src program consists of a nested load, where the inner load's result is used for indexing the outer load.

A somewhat shallow analysis by me indicates that the areConsecutivePointers() function do some SCEV magic to find that the pointers for these loads are consecutive, but it doesn't seem to me that they are. Then when vectorization has been performed, the IR references has a loop, and when the reorder() function is applied to it, it follows that loop endlessly.

This is the original c-program for reference:

 #include <stdint.h>
 
 uint32_t a = 0;
 uint32_t b[1][3] = { { 0, 0, 0 } };
 const uint16_t c = 1;
 
 int main() { 
   b[(2u & b[a % 1][2u % 3]) % 1][c % 3]; 
 }

### PR DESCRIPTION
**Pull request by artagnon**
Forbid load-load cycles which would crash LoadStoreVectorizer when reordering instructions.

Fixes #37865.

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 1]
```diff
@@ -1499,6 +1499,12 @@ std::optional<APInt> Vectorizer::getConstantOffset(Value *PtrA, Value *PtrB,
 
   // Try to compute B - A.
   const SCEV *DistScev = SE.getMinusSCEV(SE.getSCEV(PtrB), SE.getSCEV(PtrA));
+  if (DistScev->isZero()) {
+    // A load in the chain is dependent on another load in the chain, and
+    // attempting to vectorize this chain would create a cycle.
+    LLVM_DEBUG(dbgs() << "LSV: SCEV diff is zero; not vectorizing\n");
+    return std::nullopt;
+  }
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1507]: blank line after

File: llvm/test/Transforms/LoadStoreVectorizer/AArch64/pr37865.ll [hunk 2]
```diff
@@ -1,9 +1,18 @@
-; REQUIRES: asserts
-; RUN: not --crash opt -mtriple=aarch64 -passes=load-store-vectorizer \
-; RUN:   -disable-output %s 2>&1 | FileCheck %s
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -mtriple=aarch64 -passes=load-store-vectorizer -S %s | FileCheck %s
 
 define i32 @load_cycle(ptr %x) {
-; CHECK: Unexpected cycle while re-ordering instructions
+; CHECK-LABEL: define i32 @load_cycle(
```
Comment (arsenm) [inline llvm/test/Transforms/LoadStoreVectorizer/AArch64/pr37865.ll:5]: Add a comment explaining the issue?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 3]
```diff
@@ -1499,6 +1499,12 @@ std::optional<APInt> Vectorizer::getConstantOffset(Value *PtrA, Value *PtrB,
 
   // Try to compute B - A.
   const SCEV *DistScev = SE.getMinusSCEV(SE.getSCEV(PtrB), SE.getSCEV(PtrA));
+  if (DistScev->isZero()) {
+    // A load in the chain is dependent on another load in the chain, and
+    // attempting to vectorize this chain would create a cycle.
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1504]: I'm surprised the result in this situation is a 0. In the test case, how is %gep.x.2 - %gep.x.1 0?

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1504]: The SCEV expression corresponding to `%gep.x.2` is computed as the SCEVUnknown `%x`, which I think is correct. Did you expect an AddExpr?

It took me some time to figure out the fix, although it's quite a simple one in its final form: I think the patch correctly identifies the root cause.

Comment (arsenm) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1504]: So the expression is unknown - unknown = 0? That is surprising behavior. I would expect to filter out either half being unknown

Comment (arsenm) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1504]: that is, I would expect to bail on getSCEV(ptrB) == unknown and if getSCEV(ptrB) == unknown

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1504]: Difference between the _same_ two SCEVUnknowns is zero, and I've seen several instances of this in the tree. Not different SCEVUnknowns. In the case of different SCEVUnknowns, the difference wouldn't have a constant value anyway. No, I don't think we should bail on two unknowns.

**Review by arsenm — APPROVED** [review]

**Comment by bjope** [comment]
I suggest adding at least one of the extra reproducers from the comment here: https://github.com/llvm/llvm-project/issues/37865#issuecomment-981000940

IIRC the earlier proposed fix in https://reviews.llvm.org/D54468 wasn't considered as valid since it only solved the simpler test case impacted by this patch, while not solving those extra reproducers. It would be nice to see that this solution is more complete, also fixing some of the other reproducers.

**Comment by artagnon** [comment]
Thanks @bjope. I re-verified, and found that one of the test cases is still not fixed. Investigating.

**Comment by artagnon** [comment]
Update: the patch is incorrect; the condition is strictly weaker than the correct fix.

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 4]
```diff
@@ -996,10 +996,32 @@ bool Vectorizer::isSafeToMove(
...
+    // If ChainElem depends on ChainBegin, they're not safe to reorder.
+    SmallVector<Instruction *, 8> Worklist;
+    Worklist.emplace_back(ChainElem);
+    while (!Worklist.empty()) {
+      Instruction *I = Worklist.pop_back_val();
+      for (Use &O : I->operands()) {
+        if (isa<PHINode>(O))
+          continue;
+        if (auto *J = dyn_cast<Instruction>(O)) {
+          if (J == ChainBegin) {
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1015]: Wouldn't this be an issue if this were any of the instructions in the chain, not just the beginning?

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 5]
```diff
@@ -996,10 +996,32 @@ bool Vectorizer::isSafeToMove(
...
                     << *ChainBegin << ")\n");
 
-  assert(isa<LoadInst>(ChainElem) == IsLoadChain);
+  assert(isa<LoadInst>(ChainElem) == IsLoadChain &&
+         isa<LoadInst>(ChainBegin) == IsLoadChain);
+
   if (ChainElem == ChainBegin)
     return true;
 
+  if constexpr (IsLoadChain) {
```
Comment (arsenm) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1005]: Would the previous SCEV check prevent reaching here in some subset of situations?

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1005]: Yes. However, it's hard to reason about, and I'm starting to think that there may be false positives with that SCEV patch.

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp (hunk 4 above)
Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1015]: Hm, I originally had this code in the loop below, but had to move it here due to the `std::next` in `BBIt`. Will think about how we can check everything in the chain in elegantly: unfortunately, the function is just passed two `Instruction *`, instead of a first-class chain.

Comment (arsenm) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1015]: How do the other vectorizers, particularly SLP deal with this?

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1015]: I've barely looked at SLP myself, but I think it works with a first-class tree. I think the relevant function to look at is `canReorderOperands`.

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1015]: Actually, the code is correct, because `isSafeToMove` gets called in a loop from `std::next(ChainBegin)` to `ChainEnd`, so we are indeed checking all elements of the chain. I was wondering why we didn't pass a first-class chain, and found the answer.

**Review by arsenm — APPROVED** [review]

File: llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp [hunk 6]
```diff
@@ -996,10 +996,32 @@ bool Vectorizer::isSafeToMove(
...
+      Instruction *I = Worklist.pop_back_val();
+      for (Use &O : I->operands()) {
+        if (isa<PHINode>(O))
+          continue;
+        if (auto *J = dyn_cast<Instruction>(O)) {
+          if (J == ChainBegin) {
+            LLVM_DEBUG(dbgs() << "LSV: dependent loads; not safe to reorder\n");
+            return false;
+          }
+          Worklist.emplace_back(J);
```
Comment (madhur13490) [inline llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1019]: I think this can be written using early returns. What about this?

```
while (!Worklist.empty()) {
    Instruction *I = Worklist.pop_back_val();
    for (Use &O: I->operands()) {
        if (isa<PHINode>(O)) continue;
        auto CurrentUse = dyn_cast<Instruction>(O);
        if (!CurrentUse) continue;
        if (CurrentUse == ChainBegin) {
            LLVM_DEBUG ..
            return false;
        }
        Worklist.emplace_back(CurrentUse);
     }
}
```

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1019]: I think it's more idiomatic to scope `CurrentUse` within an `if`, as I've done.

Comment (arsenm) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1019]: Those aren't mutually exclusive, early return is generally preferable

Comment (artagnon) [reply llvm/lib/Transforms/Vectorize/LoadStoreVectorizer.cpp:1019]: Thanks, will keep in mind for future patches.
