### PR TITLE
[clang] Fix crash in concept deprecation

### LINKED ISSUE #98164: crash on invalid involving concepts
foo.cc:
```cpp
template <a> auto b() = delete;
decltype(b<0>()) x;
```

```
$ clang -xc++ -fsyntax-only -std=c++20 foo.cc
foo.cc:1:11: error: unknown type name 'a'
    1 | template <a> auto b() = delete;
      |           ^
foo.cc:2:10: error: call to deleted function 'b'
    2 | decltype(b<0>()) x;
      |          ^~~~
foo.cc:1:19: note: candidate function [with $0 = 0] has been explicitly deleted
    1 | template <a> auto b() = delete;
      |                   ^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ../../llvm/build/bin/clang -xc++ -fsyntax-only -std=c++20 foo.cc
1.      foo.cc:2:19: current parser token ';'
 #0 0x000055655bc57b08 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /usr/local/google/home/kadircet/repos/llvm/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x000055655bc556ce llvm::sys::RunSignalHandlers() /usr/local/google/home/kadircet/repos/llvm/llvm/lib/Support/Signals.cpp:106:18
 #2 0x000055655bbc67d6 HandleCrash /usr/local/google/home/kadircet/repos/llvm/llvm/lib/Support/CrashRecoveryContext.cpp:73:5
 #3 0x000055655bbc67d6 CrashRecoverySignalHandler(int) /usr/local/google/home/kadircet/repos/llvm/llvm/lib/Support/CrashRecoveryContext.cpp:390:51
 #4 0x00007fca1305a510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #5 0x000055655e4c9101 getConceptReference /usr/local/google/home/kadircet/repos/llvm/clang/include/clang/AST/TypeLoc.h:2203:74
 #6 0x000055655e4c9101 getConceptNameLoc /usr/local/google/home/kadircet/repos/llvm/clang/include/clang/AST/TypeLoc.h:2220:26
 #7 0x000055655e4c9101 clang::Sema::ActOnVariableDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&, llvm::ArrayRef<clang::BindingDecl*>) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Sema/SemaDecl.cpp:7579:55
 #8 0x000055655e4c0b84 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Sema/SemaDecl.cpp:0:11
 #9 0x000055655e4c015a clang::Sema::ActOnDeclarator(clang::Scope*, clang::Declarator&) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Sema/SemaDecl.cpp:6145:15
#10 0x000055655e208c4c clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/ParseDecl.cpp:0:0
#11 0x000055655e206c2e clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/ParseDecl.cpp:2448:7
#12 0x000055655e191f29 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/Parser.cpp:0:10
#13 0x000055655e191782 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/Parser.cpp:1269:12
#14 0x000055655e1905e9 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/Parser.cpp:0:14
#15 0x000055655e18e616 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/Parser.cpp:762:10
#16 0x000055655e189c8e clang::ParseAST(clang::Sema&, bool, bool) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Parse/ParseAST.cpp:162:5
#17 0x000055655c8c38df clang::FrontendAction::Execute() /usr/local/google/home/kadircet/repos/llvm/clang/lib/Frontend/FrontendAction.cpp:1082:10
#18 0x000055655c830ced getPtr /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/Support/Error.h:276:42
#19 0x000055655c830ced operator bool /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/Support/Error.h:239:16
#20 0x000055655c830ced clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Frontend/CompilerInstance.cpp:1062:23
#21 0x000055655c9a7e3e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /usr/local/google/home/kadircet/repos/llvm/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:280:25
#22 0x000055655955dcaf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /usr/local/google/home/kadircet/repos/llvm/clang/tools/driver/cc1_main.cpp:232:15
#23 0x000055655955a58d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) /usr/local/google/home/kadircet/repos/llvm/clang/tools/driver/driver.cpp:215:12
#24 0x000055655c670399 operator() /usr/local/google/home/kadircet/repos/llvm/clang/lib/Driver/Job.cpp:440:30
#25 0x000055655c670399 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
#26 0x000055655bbc6516 operator() /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#27 0x000055655bbc6516 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /usr/local/google/home/kadircet/repos/llvm/llvm/lib/Support/CrashRecoveryContext.cpp:426:3
#28 0x000055655c66fc22 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const /usr/local/google/home/kadircet/repos/llvm/clang/lib/Driver/Job.cpp:440:7
#29 0x000055655c62a017 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const /usr/local/google/home/kadircet/repos/llvm/clang/lib/Driver/Compilation.cpp:199:15
#30 0x000055655c62a557 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const /usr/local/google/home/kadircet/repos/llvm/clang/lib/Driver/Compilation.cpp:253:13
#31 0x000055655c64bbb9 empty /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/ADT/SmallVector.h:94:46
#32 0x000055655c64bbb9 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) /usr/local/google/home/kadircet/repos/llvm/clang/lib/Driver/Driver.cpp:1942:23
#33 0x0000556559559a8d clang_main(int, char**, llvm::ToolContext const&) /usr/local/google/home/kadircet/repos/llvm/clang/tools/driver/driver.cpp:391:21
#34 0x000055655956a587 main /usr/local/google/home/kadircet/repos/llvm/build/tools/clang/tools/driver/clang-driver.cpp:17:10
#35 0x00007fca130456ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#36 0x00007fca13045785 call_init ./csu/../csu/libc-start.c:128:20
#37 0x00007fca13045785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#38 0x0000556559557ee1 _start (../../llvm/build/bin/clang+0x543fee1)
clang: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 19.0.0git (git@github.com:llvm/llvm-project.git a68d20e986053ec571223a9f3ead3e146a27dc82)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/kadircet/repos/llvm/build/bin
Build config: +assertions
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/preprocessed-8dbb7a.cpp
clang: note: diagnostic msg: /tmp/preprocessed-8dbb7a.sh
clang: note: diagnostic msg:

********************
```

### PR DESCRIPTION
**Pull request by Endilll**
There is a gap between `getAs<AutoType>()` and `getConstrainedAutoType()` that the original patch #92295 was not aware of.

Fixes #98164

### CODE REVIEW

**Review by AaronBallman — COMMENTED** [review]
Do you have an idea as to why the type location is invalid in the first place?

**Comment by Endilll** [comment]
> Do you have an idea as to why the type location is invalid in the first place?

Looking at the new test, my guess is that `auto` remains undeduced, so it has nowhere to point out to.

**Review by cor3ntin — APPROVED** [review]
LGTM but I agree with Aaron that tracking exactly where we create an invalid Loc would be interesting.

**Comment by AaronBallman** [comment]
> > Do you have an idea as to why the type location is invalid in the first place?
> 
> Looking at the new test, my guess is that `auto` remains undeduced, so it has nowhere to point out to.

Even when it's undeduced, we should still have a source location for it because the user wrote `auto` somewhere.

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -7416,10 +7416,11 @@ NamedDecl *Sema::ActOnVariableDeclarator(
     tryToFixVariablyModifiedVarType(TInfo, R, D.getIdentifierLoc(),
                                     /*DiagID=*/0);
 
-  if (const AutoType *AutoT = R->getAs<AutoType>())
-    CheckConstrainedAuto(
-        AutoT,
-        TInfo->getTypeLoc().getContainedAutoTypeLoc().getConceptNameLoc());
+  if (const AutoType *AutoT = R->getAs<AutoType>()) {
+    AutoTypeLoc Loc = TInfo->getTypeLoc().getContainedAutoTypeLoc();
```
Comment (mizvekov) [inline clang/lib/Sema/SemaDecl.cpp:7420]: These two lines are analyzing the type in very different ways, so there seems to be further bugs here.

`Type::getAs<AutoType>` will simply desugar a type until it finds a node with type 'AutoType'.

`getContainedAutoTypeLoc()` will dig through a certain list of type nodes until it finds an 'AutoType'.
This list includes non-sugar nodes as well.

Let's assume for now we really want `R->getAs<AutoType>()` in the if condition here, which would not find the AutoType in `auto *`. This seems wrong, as these can be constrained as well. But we can handle that as a separate issue.

So to hit your bug, you are finding an AutoType through getAs, but not finding it through getContainedAutoTypeLoc().

My first suspicion would be that the type contains a sugar node not handled by `GetContainedAutoTypeLocVisitor`, in `AST/TypeLoc.cpp`.

Can you check that?

Comment (mizvekov) [reply clang/lib/Sema/SemaDecl.cpp:7420]: Oh, looking at the reproducer, I see the problem:

Our variable is getting the type of an undeduced AutoType through that decltype calling a deleted function with auto type.

This is confusing our semantic analysis for the variable, as now we think the variable was declared as auto, as getAs will look through all sugar nodes, 'decltype' included.

Since `getContainedAutoTypeLoc()` doesn't look through decltype, you get a crash.

But we shouldn't be getting an 'auto' here in the first place.

The correct fix would be to make that decltype have some error type, for error recovery purposes.

Since we don't implement a generic unknown error type, 'int' would still be better.

**Review by mizvekov — CHANGES_REQUESTED** [review]
See previous comments, I think this is primarily an error recovery issue on the decltype, we shouldn't let it escape an undeduced auto, as that would confuse further analysis.

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (Endilll) [reply clang/lib/Sema/SemaDecl.cpp:7420]: Thank you for the analysis!

> The correct fix would be to make that decltype have some error type, for error recovery purposes.

Can you point me out to the place in our source where this change should be made?

Comment (mizvekov) [reply clang/lib/Sema/SemaDecl.cpp:7420]: Sure, but let me get back first to the other problem in this area:

I think that assumption I pointed out is wrong, we should not be using `getAs<AutoType>` here, as that will not dig through ReferenceType and PointerType, and the following example will not be diagnosed: https://godbolt.org/z/jzEaYPq4r

The `getContainedAutoTypeLoc` is what is a good fit for that, and what we should be using throughout. It will dig through the things needed for finding the AutoType, like pointers, references, and some of the necessary type sugar which can appear in source code when writing a deduced type. It does not dig through the things it doesn't need to, like `decltype`, because you can't write a deduced type with that.

So something like:
```suggestion
  if (AutoTypeLoc TL = TInfo->getTypeLoc().getContainedAutoTypeLoc()) {
    const AutoType *AT = TL.getTypePtr();
```

Should work, and it will not get confused by the error recovery issue, which can be addressed separately.

Nit: We conventionally use `TL` abbreviation for TypeLoc, and `Loc` is conventional for SourceLocation.

Comment (mizvekov) [reply clang/lib/Sema/SemaDecl.cpp:7420]: Regarding the error recovery issue, in `SemaOverload.cpp`:

In `FixOverloadedFunctionReference`, for both `UnresolvedLookupExpr` and `UnresolvedMemberExpr`, we must avoid building a `DeclRefExpr` which has a function type returning undeduced auto.

Presently this should only happen for calls to deleted functions returning a deduced type, so should only happen when it's called from `FinishOverloadedCallExpr`, in the `OR_Deleted` case.

You can replace just the `auto` in the return type with `int`, keeping pointers and references in case of `auto *` or `auto &`. That can be done using `Sema::SubstAutoType`.

Eventually when we implement some kind of `ErrorTy`, for improving error recovery, we can change all such uses of 'int', using that instead.

Comment (Endilll) [reply clang/lib/Sema/SemaDecl.cpp]: I applied your suggestion, leaving error recovery issue for later, and also added tests for pointer and reference types. Thank you again for your excellent analysis.

If that's how it should be fixed today, I'm fine proceeding this way. That said, I find the approach somewhat backwards: morally I'm interested whether there's a constrained auto that might be using a concept, but we implement it asking for _location_ of constrained auto, and get the AST node for constrained auto from it.

Comment (mizvekov) [reply clang/lib/Sema/SemaDecl.cpp]: But here we are not just asking for the location of constrained auto.

A TypeLoc is not just a SourceLocation, it's a QualType *with* source locations.

The reason you are starting with a TypeLoc is that you are also interested in the source location.

This is a bit confusing because in a lot of places we pass both a QualType and a TypeLoc, which is mostly redundant. That might induce folks into thinking that a TypeLoc is just source locations on the side, which is not true.

But presently, they are not always redundant though. There are some cases we store both separately, and apply some transformations, like type deduction, only to the QualType, and leave the TypeLoc alone.
I think this is not ideal though, and seems to be mostly due to tech debt.

As an aside, if all you need to do is mark the concepts as used, you might as well do that earlier when the AutoType is formed, for example around the calls to `ASTContext::getAutoType` in `SemaType.cpp` / `ConvertDeclSpecToType`.

File: clang/lib/Sema/SemaType.cpp [hunk 2]
```diff
@@ -6308,11 +6308,11 @@ TypeResult Sema::ActOnTypeName(Declarator &D) {
...
-  if (const AutoType *AutoT = T->getAs<AutoType>())
-    CheckConstrainedAuto(
-        AutoT,
-        TInfo->getTypeLoc().getContainedAutoTypeLoc().getConceptNameLoc());
-
+  if (const AutoType *AutoT = T->getAs<AutoType>()) {
+    AutoTypeLoc Loc = TInfo->getTypeLoc().getContainedAutoTypeLoc();
+    CheckConstrainedAuto(AutoT,
+                         Loc ? Loc.getConceptNameLoc() : SourceLocation());
+  }
```
Comment (mizvekov) [inline clang/lib/Sema/SemaType.cpp:6315]: These still have the same issue, but I don't understand why we need this check here.

We obviously can't write stuff like
```C++
using X = auto;
```

So I am missing in what case undeduced auto can appear here, except the weird deleted function error recovery issue.

Comment (mizvekov) [reply clang/lib/Sema/SemaType.cpp:6315]: Ah, is this purely for the error cases?

Ie in my example above, you will still get the error, but is that for suppressing the deprecated warning in case that auto was constrained and happened to be the only use of that concept?

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (Endilll) [reply clang/lib/Sema/SemaDecl.cpp]: This makes more sense now.

> A TypeLoc is not just a SourceLocation, it's a QualType with source locations.

I though that `QualType` with source locations is `TypeSourceInfo`. If I correctly understand description of `TypeLoc` correctly, `TypeLoc` is trailing data of `TypeSourceInfo`. Is that correct?

> As an aside, if all you need to do is mark the concepts as used, you might as well do that earlier when the AutoType is formed, for example around the calls to ASTContext::getAutoType in SemaType.cpp / ConvertDeclSpecToType.

Calling `DiagnoseUseOfDecl` there seems too early. It triggers on _declaration_ of deprecated concept.

File: clang/lib/Sema/SemaType.cpp (hunk 2 above)
Comment (Endilll) [reply clang/lib/Sema/SemaType.cpp]: I did this for consistency, and now updated to use the same approach as in the other place.

**Review by cor3ntin — APPROVED** [review]
I think this makes sense but please give @mizvekov  the day to review before landing

Thank you both for working on this

File: clang/test/SemaCXX/cxx-deprecated.cpp [hunk 3]
```diff
@@ -36,4 +36,11 @@ template <C T>
 // expected-warning@-1 {{'C' is deprecated}}
 //   expected-note@#C {{'C' has been explicitly marked deprecated here}}
 void f();
+
+template <int>
+auto b() = delete; // #b
+
+decltype(b<0>()) x;
+// expected-error@-1 {{call to deleted function 'b'}}
+//   expected-note@#b {{candidate function [with $0 = 0] has been explicitly deleted}}
```
[the remark this answers is not in the document]
Comment (Endilll) [reply clang/test/SemaCXX/cxx-deprecated.cpp]: Fixed

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaDecl.cpp]: Yeah, we don't need to have both TypeSourceInfo and TypeLoc in clang. I am not sure the history of how the situation arose, but we can pretty much consolidate on TypeLoc at some point.

**Review by mizvekov — APPROVED** [review]

**Comment by mizvekov** [comment]
LGTM, Thanks!

File: clang/lib/Sema/SemaType.cpp (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaType.cpp]: But my question was, what cases are we handling with this check in `ActOnTypeName`?
I thought 'auto' couldn't appear here.

Comment (Endilll) [reply clang/lib/Sema/SemaType.cpp]: Test with constrained auto in trailing return type doesn't pass otherwise:
https://github.com/llvm/llvm-project/blob/2bdcfbe62cb9a08df4b58a17d44be0a3082df053/clang/test/CXX/drs/cwg24xx.cpp#L78-L81
