### PR TITLE
[LLD][COFF] Don't dllimport from static libraries

### LINKED ISSUE #131807: lld-link Crash
Using LLVM-20.1.0 release build from https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.0/LLVM-20.1.0-Linux-X64.tar.xz

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
 #0 0x0000575a1a2bb007 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/mnt/centshare/vfurnace/git/toolchain/ort-toolchain-msvc-clang/msvc-clang/LLVM-20.1.0-Linux-X64/bin/lld-link+0x4b8e007)
 #1 0x0000575a1a2bb63f SignalHandler(int) Signals.cpp:0:0
 #2 0x00007d867d550cd0 (/usr/lib/libc.so.6+0x3dcd0)
 #3 0x0000575a1a3c7aee lld::coff::(anonymous namespace)::AddressTableChunk::writeTo(unsigned char*) const DLL.cpp:0:0
 #4 0x0000575a1a31dc72 std::__1::__function::__func<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0, std::__1::allocator<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0>, void ()>::operator()() (.llvm.17606889172608314556) Parallel.cpp:0:0
 #5 0x0000575a1a31db9a std::__1::__function::__func<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>)::$_0, std::__1::allocator<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>)::$_0>, void ()>::operator()() Parallel.cpp:0:0
 #6 0x0000575a1a31d8d7 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) Parallel.cpp:0:0
 #7 0x0000575a1a31d969 void* std::__1::__thread_proxy[abi:nn200100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>(void*) Parallel.cpp:0:0
 #8 0x00007d867d5a870a (/usr/lib/libc.so.6+0x9570a)
 #9 0x00007d867d62caac (/usr/lib/libc.so.6+0x119aac)
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: linker command failed due to signal (use -v to see invocation)
clang++: error: invalid linker name in argument '-fuse-ld=lld-link'

```

### PR DESCRIPTION
**Pull request by aganea**
This reverts commit 6a1bdd9 and re-instate behavior that matches what MSVC link.exe does, that is, error out when trying to dllimport a symbol from a static library.

We also now hint in stdout that we should rather dllimport the symbol from a import library.

Fixes https://github.com/llvm/llvm-project/issues/131807

### CODE REVIEW

File: lld/COFF/SymbolTable.cpp [hunk 1]
```diff
@@ -231,6 +231,17 @@ void SymbolTable::reportUndefinedSymbol(const UndefinedDiag &undefDiag) {
...
     diag << "\n>>> referenced " << numRefs - numDisplayedRefs << " more times";
+
+  // Hints
+  StringRef name = undefDiag.sym->getName();
+  if (name.starts_with("__imp_")) {
+    Symbol *imp = find(name.substr(strlen("__imp_")));
+    if (imp && imp->isLazy()) {
+      diag << "\nNOTE: a relevant symbol '" << imp->getName()
+           << "' is available in " << toString(imp->getFile())
+           << " but cannot be used because it is not a import library.";
```
Comment (mstorsjo) [inline lld/COFF/SymbolTable.cpp:242]: Nit: **an** import library

Initially I felt confused by this message, but I think it may be the best way to phrase it. The other angle at this is, that if this wasn't a static library but object files, or members in a static library that we've already pulled in, then we'd actually link it successfully. But it's hard to suggest that in the diagnostic, and we probably don't want to push users that way anyway. So I guess this wording is fine.

I don't see this diagnostic tested though - I think it would be good to check that we do hit it.

**Review by mstorsjo — COMMENTED** [review]
I think this looks reasonable, thanks!

IIRC #109082 wasn't for a concrete issue after all (the case where we found this was messed up in other ways anywya), but I'd wait for @glandium to confirm that too.

File: lld/COFF/SymbolTable.cpp (hunk 1 above)
Comment (aganea) [reply lld/COFF/SymbolTable.cpp]: Please see updated version. I've added another testcase to also validate your test case in https://github.com/llvm/llvm-project/issues/131807#issuecomment-2760632883 -- which happens to only generate a warning.

**Review by mstorsjo — COMMENTED** [review]
Looking good from my point of view now, thanks! But please wait for @glandium to reconfirm before landing. (I'm holding off of the approve-button until then.)

**Comment by glandium** [comment]
I /think/ this is fine. I'll look out for the fallout after it lands.

**Review by mstorsjo — APPROVED** [review]

**Comment by mstorsjo** [comment]
As this is a crash fix for a regression in 20.x, we should probably consider backporting this to 20.x (especially as this doesn't seem to be the only case that hits this bug, see #134843), but we probably also first should give it a couple of days so that @glandium may pick it up and do some building with it.

**Comment by tstellar** [comment]
@aganea Were you able to manually backport this?

**Comment by aganea** [comment]
Ah I see, there's an ambiguity:
```
C:\git\llvm-project>git cherry-pick c75eac7
error: short object ID c75eac7 is ambiguous
hint: The candidates are:
hint:   c75eac7c0347 commit 2025-04-07 - [LLD][COFF] Don't dllimport from static libraries (#134443)
hint:   c75eac723654 tree
fatal: bad revision 'c75eac7'
```
I'll try again with the longer ID.

**Comment by aganea** [comment]
[Don't seem to be working](https://github.com/llvm/llvm-project/actions/runs/14804027981/job/41568972276). I'll send a PR.
