### PR TITLE
[InstCombine] Handle trunc i1 pattern in eq-of-parts fold

### LINKED ISSUE #110919: [InstCombine] Regression in and of masked comparison fold
From https://github.com/rust-lang/rust/issues/131162:
```rust
const MASK: u8 = 1;

#[no_mangle]
pub fn test1(a1: u8, a2: u8) -> bool {
    (a1 & !MASK) == (a2 & !MASK) && (a1 & MASK) == (a2 & MASK)
}
```

https://llvm.godbolt.org/z/Pasonhe9d:
```llvm
define i1 @test(i8 %a1, i8 %a2) {
  %xor = xor i8 %a1, %a2
  %cmp = icmp ult i8 %xor, 2
  %lobit = trunc i8 %xor to i1
  %lobit.inv = xor i1 %lobit, true
  %and = and i1 %cmp, %lobit.inv
  ret i1 %and
}
```

LLVM 18:
```llvm
define i1 @test(i8 %a1, i8 %a2) {
  %and = icmp eq i8 %a1, %a2
  ret i1 %and
}
```

LLVM 19:
```llvm
define i1 @test(i8 %a1, i8 %a2) {
  %xor = xor i8 %a1, %a2
  %cmp = icmp ult i8 %xor, 2
  %lobit = trunc i8 %xor to i1
  %lobit.inv = xor i1 %lobit, true
  %and = and i1 %cmp, %lobit.inv
  ret i1 %and
}
```

I believe this is fallout from removal of the trunc i1 canonicalization in https://github.com/llvm/llvm-project/pull/84628.

### PR DESCRIPTION
**Pull request by nikic**
Equality/inequality of the low bit can be represented by `(trunc (xor x, y) to i1)`, possibly with an extra not. We have to handle this in the eq-of-parts fold now that we no longer canonicalize this to a masked icmp.

Proofs: https://alive2.llvm.org/ce/z/qidkzq

Fixes https://github.com/llvm/llvm-project/issues/110919.

### CODE REVIEW

**Review by goldsteinn — APPROVED** [review]

File: llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp [hunk 1]
```diff
@@ -3538,6 +3546,9 @@ Value *InstCombinerImpl::foldBooleanAndOr(Value *LHS, Value *RHS,
       if (Value *Res = foldLogicOfFCmps(LHSCmp, RHSCmp, IsAnd, IsLogical))
         return Res;
 
+  if (Value *Res = foldEqOfParts(LHS, RHS, IsAnd))
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:3549]: Regression:
```
define i1 @jv_identical(i64 %0, i64 %2) {
   %.sroa.08.0.extract.trunc = trunc i64 %0 to i8
   %.sroa.311.0.extract.shift = lshr i64 %0, 16
   %.sroa.311.0.extract.trunc = trunc i64 %.sroa.311.0.extract.shift to i16
   %.sroa.0.0.extract.trunc = trunc i64 %2 to i8
   %.sroa.37.0.extract.shift = lshr i64 %2, 16
   %.sroa.37.0.extract.trunc = trunc i64 %.sroa.37.0.extract.shift to i16
   %.not = icmp eq i8 %.sroa.08.0.extract.trunc, %.sroa.0.0.extract.trunc
   %.not2 = icmp eq i16 %.sroa.311.0.extract.trunc, %.sroa.37.0.extract.trunc
   %or.cond = and i1 %.not, %.not2
   %.not3.unshifted = xor i64 %2, %0
   %.not3 = icmp ult i64 %.not3.unshifted, 4294967296
   %or.cond15 = and i1 %.not3, %or.cond
   ret i1 %or.cond15
}
```
Before:
```
define i1 @jv_identical(i64 %0, i64 %1) {
  %.sroa.08.0.extract.trunc = trunc i64 %0 to i8
  %.sroa.311.0.extract.shift = lshr i64 %0, 16
  %.sroa.311.0.extract.trunc = trunc i64 %.sroa.311.0.extract.shift to i16
  %.sroa.0.0.extract.trunc = trunc i64 %1 to i8
  %.sroa.37.0.extract.shift = lshr i64 %1, 16
  %.sroa.37.0.extract.trunc = trunc i64 %.sroa.37.0.extract.shift to i16
  %.not = icmp eq i8 %.sroa.08.0.extract.trunc, %.sroa.0.0.extract.trunc
  %.not2 = icmp eq i16 %.sroa.311.0.extract.trunc, %.sroa.37.0.extract.trunc
  %or.cond = and i1 %.not, %.not2
  %.not3.unshifted = xor i64 %1, %0
  %.not3 = icmp ult i64 %.not3.unshifted, 4294967296
  %or.cond15 = and i1 %.not3, %or.cond
  ret i1 %or.cond15
}
```
After:
```
define i1 @jv_identical(i64 %0, i64 %1) {
  %.sroa.08.0.extract.trunc = trunc i64 %0 to i8
  %.sroa.0.0.extract.trunc = trunc i64 %1 to i8
  %.not = icmp eq i8 %.sroa.08.0.extract.trunc, %.sroa.0.0.extract.trunc
  %.unshifted = xor i64 %1, %0
  %3 = icmp ult i64 %.unshifted, 65536
  %or.cond15 = and i1 %.not, %3
  ret i1 %or.cond15
}
```

I think this fold should be moved before https://github.com/llvm/llvm-project/blob/e9eec14bb3566f6578950797559de98678f16985/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp#L3446-L3448

Comment (goldsteinn) [reply llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:3549]: If it works sure, but don't think we should make it a practice to try to maintain an ordering for the many many many different InstCombine folds. It will quickly become unmanagable.

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:3549]: Agree that we shouldn't maintain an ordering of folds. But it is ok to move folds between these early exit points.
Currently we place the fold after this early exit point, causing `trunc(lshr Y, Shift)` pattern on RHS of icmp cannot be captured by `matchIntPart`.

Comment (nikic) [reply llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:3549]: This will be fixed by https://github.com/llvm/llvm-project/pull/116065.

File: llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp [hunk 2]
```diff
@@ -1185,14 +1185,25 @@ static Value *extractIntPart(const IntPart &P, IRBuilderBase &Builder) {
...
 
   CmpInst::Predicate Pred = IsAnd ? CmpInst::ICMP_EQ : CmpInst::ICMP_NE;
-  auto GetMatchPart = [&](ICmpInst *Cmp,
+  auto GetMatchPart = [&](Value *CmpV,
                           unsigned OpNo) -> std::optional<IntPart> {
+    Value *X, *Y;
+    // icmp ne (and x, 1), (and y, 1) <=> trunc (xor x, y) to i1
+    // icmp eq (and x, 1), (and y, 1) <=> not (trunc (xor x, y) to i1)
+    if (Pred == CmpInst::ICMP_NE
+            ? match(CmpV, m_Trunc(m_Xor(m_Value(X), m_Value(Y))))
```
Comment (andjo403) [inline llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp:1199]: maybe nice to have a assert that the trunc is to i1 near here. I thought it was missing before finding the check first  in foldBooleanAndOr.
