### PR TITLE
[clang][Driver][AVR] Reject c/c++ compilation for avr1 devices

### LINKED ISSUE #96881: Compiler crash when compiling for AVR with -mmcu=avr1
```
int gl_a;

int fn()
{
  return gl_a;
}
```
```
$ ./bin/clang --target=avr -S /tmp/test_add.c -o - -mmcu=avr1
```
```
        .text
.set __tmp_reg__, 0
.set __zero_reg__, 1
.set __SREG__, 63
.set __SP_H__, 62
.set __SP_L__, 61
        .file   "test_add.c"
fatal error: error in backend: Cannot select: t4: i16,ch = load<(dereferenceable load (s16) from @gl_a, align 1)> t0, t10, undef:i16
  t10: i16 = WRAPPER TargetGlobalAddress:i16<ptr @gl_a> 0
    t9: i16 = TargetGlobalAddress<ptr @gl_a> 0
  t3: i16 = undef
In function: fn
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ./bin/clang --target=avr -S /tmp/test_add.c -o - -mmcu=avr1
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module '/tmp/test_add.c'.
4.      Running pass 'AVR DAG->DAG Instruction Selection' on function '@fn'
 #0 0x0000aaaabdaacbb4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./bin/clang+0x3715bb4)
 #1 0x0000aaaabdaaa9b0 llvm::sys::RunSignalHandlers() (./bin/clang+0x37139b0)
 #2 0x0000aaaabdaabf10 llvm::sys::CleanupOnSignal(unsigned long) (./bin/clang+0x3714f10)
 #3 0x0000aaaabda1fd54 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x0000aaaabda1fce4 llvm::CrashRecoveryContext::HandleExit(int) (./bin/clang+0x3688ce4)
 #5 0x0000aaaabdaa72f0 llvm::sys::Process::Exit(int, bool) (./bin/clang+0x37102f0)
 #6 0x0000aaaabb5fee18 llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>::~IntrusiveRefCntPtr() (./bin/clang+0x1267e18)
 #7 0x0000aaaabda28140 llvm::report_fatal_error(llvm::Twine const&, bool) (./bin/clang+0x3691140)
 #8 0x0000aaaabe92cb20 llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (./bin/clang+0x4595b20)
 #9 0x0000aaaabe92bb88 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (./bin/clang+0x4594b88)
#10 0x0000aaaabbfec7bc (anonymous namespace)::AVRDAGToDAGISel::Select(llvm::SDNode*) AVRISelDAGToDAG.cpp:0:0
#11 0x0000aaaabe9224bc llvm::SelectionDAGISel::DoInstructionSelection() (./bin/clang+0x458b4bc)
#12 0x0000aaaabe921570 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (./bin/clang+0x458a570)
#13 0x0000aaaabe91f22c llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (./bin/clang+0x458822c)
#14 0x0000aaaabe91ca84 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (./bin/clang+0x4585a84)
#15 0x0000aaaabe91a4f8 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (./bin/clang+0x45834f8)
#16 0x0000aaaabcfde6ec llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (./bin/clang+0x2c476ec)
<...>
```
Compiler Explorer: https://godbolt.org/z/ePa98xGe1

I see that GCC only supports assembly for this CPU, perhaps that is a sign that codegen here is very difficult?

### PR DESCRIPTION
**Pull request by benshi001**
avr-gcc also rejects since these devices has no SRAM.

Fixes https://github.com/llvm/llvm-project/issues/96881

### CODE REVIEW

File: clang/lib/Driver/ToolChains/AVR.cpp [hunk 1]
```diff
@@ -400,6 +400,14 @@ void AVRToolChain::AddClangSystemIncludeArgs(const ArgList &DriverArgs,
 void AVRToolChain::addClangTargetOptions(
     const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args,
     Action::OffloadKind DeviceOffloadKind) const {
+  // Reject C/C++ compilation for avr1 devices.
+  const Driver &D = getDriver();
+  std::string CPU = getCPUName(D, DriverArgs, getTriple());
+  std::optional<StringRef> FamilyName = GetMCUFamilyName(CPU);
+  if (CPU == "avr1" || (FamilyName && FamilyName->compare("avr1") == 0))
+    D.Diag(diag::err_drv_opt_unsupported_input_type) << "avr1"
+                                                     << "c/c++";
```
Comment (DavidSpickett) [inline clang/lib/Driver/ToolChains/AVR.cpp:409]: The error is certainly the right category, but it's a shame you can't have it say "device family 'avr1'" (replace "device family" with whatever the correct term is).

I looked around and I don't see a way to use an existing error but prepend to the text. Only other way is to make a whole new error type which seems a shame when this is so close. Not that big of a deal, but it would help new users I think.

@Sirraide you helped me on diagnostics before, is it plausible to do that or is a new error type the only way?

Comment (DavidSpickett) [reply clang/lib/Driver/ToolChains/AVR.cpp:409]: You could instead put `-mmcu=attiny11` as the value, then users know what part of the command triggered the issue, though they may not be aware that this whole category is the same. In practice I wonder if that would be more useful for most people.

Also what does gcc say in this situation?

**Review by DavidSpickett — COMMENTED** [review]
Thanks for getting to this I had forgotten I raised that issue.

You should move your commit's message into the PR description, as the PR description is what's used for the final commit when we merge this.

File: clang/lib/Driver/ToolChains/AVR.cpp (hunk 1 above)
Comment (DavidSpickett) [reply clang/lib/Driver/ToolChains/AVR.cpp:409]: > You could instead put -mmcu=attiny11 as the value

Assuming that you know that `-mmcu` is the only way to hit this code path.

**Comment by DavidSpickett** [comment]
```
_bk;t=1728546187607Failed Tests (1):
_bk;t=1728546187607  Clang :: Driver/hip-partial-link.hip
```
And the CI test failure is this, the reporting is not great because we run check- targets one after another. This test was already failing on main.

If it fails again download the logs and search for "Failed<2-3 spaces>" and you'll see any results summaries where something failed. I plan to work on combining the results so this isn't a problem in the future.

**Comment by benshi001** [comment]
> Thanks for getting to this I had forgotten I raised that issue.
> 
> You should move your commit's message into the PR description, as the PR description is what's used for the final commit when we merge this.

Thanks. I have update my PR description according to my commit message.

File: clang/lib/Driver/ToolChains/AVR.cpp [hunk 2]
```diff
@@ -400,6 +400,14 @@ void AVRToolChain::AddClangSystemIncludeArgs(const ArgList &DriverArgs,
 void AVRToolChain::addClangTargetOptions(
     const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args,
     Action::OffloadKind DeviceOffloadKind) const {
+  // Reject C/C++ compilation for avr1 devices.
```
[the remark this answers is not in the document]
Comment (benshi001) [reply clang/lib/Driver/ToolChains/AVR.cpp]: I have updated my comments to "Reject C/C++ compilation for avr1 devices since they have no SRAM."

File: clang/lib/Driver/ToolChains/AVR.cpp [hunk 3]
```diff
@@ -400,6 +400,14 @@ void AVRToolChain::AddClangSystemIncludeArgs(const ArgList &DriverArgs,
...
+  const Driver &D = getDriver();
+  std::string CPU = getCPUName(D, DriverArgs, getTriple());
+  std::optional<StringRef> FamilyName = GetMCUFamilyName(CPU);
+  if (CPU == "avr1" || (FamilyName && FamilyName->compare("avr1") == 0))
```
[the remark this answers is not in the document]
Comment (benshi001) [reply clang/lib/Driver/ToolChains/AVR.cpp]: Fixed. Thanks.

File: clang/lib/Driver/ToolChains/AVR.cpp (hunk 1 above)
Comment (benshi001) [reply clang/lib/Driver/ToolChains/AVR.cpp]: Since `-mmcu` is the only way to trigger this issue, I have updated my error message to `'-mmcu=attiny11' invalid for input of type c/c++`

File: clang/lib/Driver/ToolChains/AVR.cpp [hunk 4]
```diff
@@ -400,6 +400,14 @@ void AVRToolChain::AddClangSystemIncludeArgs(const ArgList &DriverArgs,
 void AVRToolChain::addClangTargetOptions(
     const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args,
     Action::OffloadKind DeviceOffloadKind) const {
+  // Reject C/C++ compilation for avr1 devices.
+  const Driver &D = getDriver();
+  std::string CPU = getCPUName(D, DriverArgs, getTriple());
```
[the remark this answers is not in the document]
Comment (benshi001) [reply clang/lib/Driver/ToolChains/AVR.cpp:405]: I think `const Driver &D = getDriver();` at line 404 is necessary, since I have to use  `D.Diag(..)`, it would not be better to call `getDriver()` twice.

**Comment by benshi001** [comment]
> ```
> �_bk;t=1728546187607�Failed Tests (1):
> �_bk;t=1728546187607�  Clang :: Driver/hip-partial-link.hip
> ```
> 
> And the CI test failure is this, the reporting is not great because we run check- targets one after another. This test was already failing on main.
> 
> If it fails again download the logs and search for "Failed<2-3 spaces>" and you'll see any results summaries where something failed. I plan to work on combining the results so this isn't a problem in the future.

Thanks. I am also thinking the failure is not related to my clang-driver-AVR work.

**Review by jacquesguan — APPROVED** [review]

**Comment by DavidSpickett** [comment]
Please add a release note in https://clang.llvm.org/docs/ReleaseNotes.html#avr-support (`clang/docs/ReleaseNotes.rst`).

Otherwise, this looks good to me.

**Comment by benshi001** [comment]
> Please add a release note in https://clang.llvm.org/docs/ReleaseNotes.html#avr-support (`clang/docs/ReleaseNotes.rst`).
> 
> Otherwise, this looks good to me.

The note is added. Thanks!

File: clang/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -598,6 +598,8 @@ WebAssembly Support
 AVR Support
 ^^^^^^^^^^^
 
+- Reject C/C++ compilation for avr1 devices which has no SRAM.
```
Comment (DavidSpickett) [inline clang/docs/ReleaseNotes.rst:601]: "which have no", since devices is plural.

**Review by DavidSpickett — APPROVED** [review]
LGTM with the wording fixed.
