### PR TITLE
[Instrumentation] Fix EdgeCounts vector size in SetBranchWeights

### LINKED ISSUE #97962: llvm/clang crash in cspgo build
```
FAILED: CMakeFiles/seastar.dir/src/rpc/rpc.cc.o 
/usr/lib64/ccache/clang++ -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_PTHREAD_ATTR_SETAFFINITY_NP -DSEASTAR_SCHEDULING_GROUPS_COUNT=18 -DSEASTAR_SSTRING -DSEASTAR_STRERROR_R_CHAR_P -I/home/avi/scylla-maint/seastar/include -I/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto/gen/include -I/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto/gen/src -I/home/avi/scylla-maint/seastar/src -O2 -g -DNDEBUG -std=gnu++23 -U_FORTIFY_SOURCE -Werror=unused-result "-Wno-error=#warnings" -UNDEBUG -Wall -Werror -Wimplicit-fallthrough -Wdeprecated -Wno-error=deprecated -fvisibility=hidden -gz -flto=thin -ffile-prefix-map=/home/avi/scylla-maint=. -march=westmere -Wno-backend-plugin -fprofile-use=/home/avi/scylla-maint/build/release-pgo/profiles/merged.profdata -fcs-profile-generate=/home/avi/scylla-maint/build/release-cs-pgo -mllvm -pgso=false -mllvm -enable-value-profiling=false -MD -MT CMakeFiles/seastar.dir/src/rpc/rpc.cc.o -MF CMakeFiles/seastar.dir/src/rpc/rpc.cc.o.d -o CMakeFiles/seastar.dir/src/rpc/rpc.cc.o -c /home/avi/scylla-maint/seastar/src/rpc/rpc.cc
*** stack smashing detected ***: terminated
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -O2 -g -std=gnu++23 -Werror=unused-result -Wno-error=#warnings -Wall -Wimplicit-fallthrough -Wdeprecated -Wno-error=deprecated -fvisibility=hidden -gz -flto=thin -ffile-prefix-map=/home/avi/scylla-maint=. -march=westmere -Wno-backend-plugin -fprofile-use=/home/avi/scylla-maint/build/release-pgo/profiles/merged.profdata -fcs-profile-generate=/home/avi/scylla-maint/build/release-cs-pgo -mllvm -pgso=false -mllvm -enable-value-profiling=false -Werror -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_PTHREAD_ATTR_SETAFFINITY_NP -DSEASTAR_SCHEDULING_GROUPS_COUNT=18 -DSEASTAR_SSTRING -DSEASTAR_STRERROR_R_CHAR_P -I/home/avi/scylla-maint/seastar/include -I/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto/gen/include -I/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto/gen/src -I/home/avi/scylla-maint/seastar/src -DNDEBUG -U_FORTIFY_SOURCE -UNDEBUG -c -MD -MT CMakeFiles/seastar.dir/src/rpc/rpc.cc.o -MF CMakeFiles/seastar.dir/src/rpc/rpc.cc.o.d -fcolor-diagnostics -o CMakeFiles/seastar.dir/src/rpc/rpc.cc.o /home/avi/scylla-maint/seastar/src/rpc/rpc.cc
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x00007f9d0d8044fa llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.18.1+0x6044fa)
 #1 0x00007f9d0d801ce4 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.18.1+0x601ce4)
 #2 0x00007f9d0d736004 (/lib64/libLLVM.so.18.1+0x536004)
 #3 0x00007f9d0cc4fd00 __restore_rt (/lib64/libc.so.6+0x40d00)
 #4 0x00007f9d0cca84a4 __pthread_kill_implementation (/lib64/libc.so.6+0x994a4)
 #5 0x00007f9d0cc4fc4e gsignal (/lib64/libc.so.6+0x40c4e)
 #6 0x00007f9d0cc37902 abort (/lib64/libc.so.6+0x28902)
 #7 0x00007f9d0cc38767 _IO_peekc_locked.cold (/lib64/libc.so.6+0x29767)
 #8 0x00007f9d0cd36769 (/lib64/libc.so.6+0x127769)
 #9 0x00007f9d0cd379e4 (/lib64/libc.so.6+0x1289e4)
#10 0x00007f9d0e7746a1 (/lib64/libLLVM.so.18.1+0x15746a1)
#11 0x00007f9d0e766f53 (/lib64/libLLVM.so.18.1+0x1566f53)
#12 0x00007f9d0e76545b llvm::PGOInstrumentationUse::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/lib64/libLLVM.so.18.1+0x156545b)
#13 0x00007f9d10ff4bf1 (/lib64/libLLVM.so.18.1+0x3df4bf1)
#14 0x00007f9d0d9c8e5d llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/lib64/libLLVM.so.18.1+0x7c8e5d)
#15 0x00007f9d15c65092 (/lib64/libclang-cpp.so.18.1+0x1865092)
#16 0x00007f9d15c5c17e clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/lib64/libclang-cpp.so.18.1+0x185c17e)
#17 0x00007f9d1605a2a0 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.18.1+0x1c5a2a0)
#18 0x00007f9d14974436 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.18.1+0x574436)
#19 0x00007f9d16c1c9f6 clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.18.1+0x281c9f6)
#20 0x00007f9d16b94700 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.18.1+0x2794700)
#21 0x00007f9d16c99f65 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.18.1+0x2899f65)
#22 0x00000000004144c6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /usr/src/debug/clang-18.1.6-3.fc40.x86_64/tools/driver/cc1_main.cpp:294:15
#23 0x0000000000411164 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) /usr/src/debug/clang-18.1.6-3.fc40.x86_64/tools/driver/driver.cpp:365:12
#24 0x00007f9d167c5acd (/lib64/libclang-cpp.so.18.1+0x23c5acd)
#25 0x00007f9d0d735d44 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.18.1+0x535d44)
#26 0x00007f9d167c5537 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.18.1+0x23c5537)
#27 0x00007f9d1678b297 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.18.1+0x238b297)
#28 0x00007f9d1678b4f7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.18.1+0x238b4f7)
#29 0x00007f9d167a995e clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.18.1+0x23a995e)
#30 0x00000000004109bf clang_main(int, char**, llvm::ToolContext const&) /usr/src/debug/clang-18.1.6-3.fc40.x86_64/tools/driver/driver.cpp:540:21
#31 0x000000000041dcca main tools/driver/clang-driver.cpp:17:10
#32 0x00007f9d0cc39088 __libc_start_call_main (/lib64/libc.so.6+0x2a088)
#33 0x00007f9d0cc3914b __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14b)
#34 0x000000000040d8a5 _start (/usr/bin/clang+++0x40d8a5)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 18.1.6 (Fedora 18.1.6-3.fc40)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang++.cfg
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/rpc-195796.cpp
clang++: note: diagnostic msg: /tmp/rpc-195796.sh
clang++: note: diagnostic msg: 

********************
[89/90] Building CXX object CMakeFiles/seastar.dir/src/core/reactor.cc.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by avikivity**
SetBranchWeights() calculates the size of the EdgeCounts vector
using OutEdges.Size(), but this is an under-estimate with coroutines.

Use the number of successors, as the vector will be indexed by
the result of the GetSuccessorNumber() function.

Rename the Size local, to make it clear what it refers to.

A unit test, provided by @ellishg, is included.

Fixes #97962

(regression from ffd337b995658266d83e15630d656e57882bcf0d)

### CODE REVIEW

**Comment by avikivity** [comment]
Requesting review from @xur-llvm as author of this function.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp [hunk 1]
```diff
@@ -1624,7 +1624,9 @@ void PGOUseFunc::setBranchWeights() {
 
     // We have a non-zero Branch BB.
     unsigned Size = BBCountInfo.OutEdges.size();
```
Comment (ellishg) [inline llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1626]: Could you also rename `Size` so it is more clear how it is different from `SuccessorCount`?

Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp]: Done.

**Comment by avikivity** [comment]
Updated: renamed Size to OutEdgesCount to make it clear what it refers to.

**Comment by ellishg** [comment]
Seems ok, but I'd like to see a test so we don't break this in the future.

**Comment by avikivity** [comment]
> Seems ok, but I'd like to see a test so we don't break this in the future.

I'm not an llvm developer, so any tips about reducing my C++ reproducer to a minimal llvm reproducer would be appreciated.

**Comment by ellishg** [comment]
> > Seems ok, but I'd like to see a test so we don't break this in the future.
> 
> I'm not an llvm developer, so any tips about reducing my C++ reproducer to a minimal llvm reproducer would be appreciated.

There are a few ways to get a minimal reproducer depending on your setup. https://llvm.org/docs/HowToSubmitABug.html

I would first try to get a reproducer with unoptimized IR by invoking clang with `-emit-llvm -S -Xclang -disable-llvm-optzns -o a.ll`. Then you can use `llvm-reduce` to further reduce the IR to a small test case. https://llvm.org/docs/CommandGuide/llvm-reduce.html#example

**Comment by avikivity** [comment]
Tacking on those flags to the command line (without -Xclang which was rejected) I get an error.

command:

```sh
 "/usr/bin/clang++" "-cc1" "-triple" "x86_64-redhat-linux-gnu" "-emit-llvm-bc" "-flto=thin" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "rpc.cc" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "westmere" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "--compress-debug-sections=zlib" "-fdebug-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-fdebug-prefix-map=/home/avi/scylla-maint=." "-fprofile-instrument=csllvm" "-fprofile-instrument-path=/home/avi/scylla-maint/build/release-cs-pgo/default_%m.profraw" "-fprofile-instrument-use-path=merged.profdata" "-fcoverage-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-sys-header-deps" "-D" "FMT_SHARED" "-D" "SEASTAR_API_LEVEL=7" "-D" "SEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT" "-D" "SEASTAR_HAS_MEMBARRIER" "-D" "SEASTAR_HAVE_ASAN_FIBER_SUPPORT" "-D" "SEASTAR_HAVE_HWLOC" "-D" "SEASTAR_HAVE_NUMA" "-D" "SEASTAR_HAVE_SYSTEMTAP_SDT" "-D" "SEASTAR_LOGGER_COMPILE_TIME_FMT" "-D" "SEASTAR_LOGGER_TYPE_STDOUT" "-D" "SEASTAR_PTHREAD_ATTR_SETAFFINITY_NP" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=18" "-D" "SEASTAR_SSTRING" "-D" "SEASTAR_STRERROR_R_CHAR_P" "-D" "NDEBUG" "-U" "_FORTIFY_SOURCE" "-U" "NDEBUG" "-fmacro-prefix-map=/home/avi/scylla-maint=." "-fcoverage-prefix-map=/home/avi/scylla-maint=." "-O2" "-Werror=unused-result" "-Wno-error=#warnings" "-Wall" "-Wimplicit-fallthrough" "-Wdeprecated" "-Wno-error=deprecated" "-Wno-backend-plugin" "-Werror" "-std=gnu++23" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-pgso=false" "-mllvm" "-enable-value-profiling=false" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "rpc-195796.cpp"  -emit-llvm -S  -disable-llvm-optzns -o a.ll
```

error:

```
fatal error: error in backend: Do not know how to promote this operator!
```

**Comment by avikivity** [comment]
I'm guessing some internal pass related to coroutines cannot be skipped.

**Comment by ellishg** [comment]
Do you have the build command?

**Comment by avikivity** [comment]
```
 "/usr/bin/clang++" "-cc1" "-triple" "x86_64-redhat-linux-gnu" "-emit-llvm-bc" "-flto=thin" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "rpc.cc" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "westmere" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "--compress-debug-sections=zlib" "-fdebug-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-fdebug-prefix-map=/home/avi/scylla-maint=." "-fprofile-instrument=csllvm" "-fprofile-instrument-path=/home/avi/scylla-maint/build/release-cs-pgo/default_%m.profraw" "-fprofile-instrument-use-path=merged.profdata" "-fcoverage-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-sys-header-deps" "-D" "FMT_SHARED" "-D" "SEASTAR_API_LEVEL=7" "-D" "SEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT" "-D" "SEASTAR_HAS_MEMBARRIER" "-D" "SEASTAR_HAVE_ASAN_FIBER_SUPPORT" "-D" "SEASTAR_HAVE_HWLOC" "-D" "SEASTAR_HAVE_NUMA" "-D" "SEASTAR_HAVE_SYSTEMTAP_SDT" "-D" "SEASTAR_LOGGER_COMPILE_TIME_FMT" "-D" "SEASTAR_LOGGER_TYPE_STDOUT" "-D" "SEASTAR_PTHREAD_ATTR_SETAFFINITY_NP" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=18" "-D" "SEASTAR_SSTRING" "-D" "SEASTAR_STRERROR_R_CHAR_P" "-D" "NDEBUG" "-U" "_FORTIFY_SOURCE" "-U" "NDEBUG" "-fmacro-prefix-map=/home/avi/scylla-maint=." "-fcoverage-prefix-map=/home/avi/scylla-maint=." "-O2"  "-Wno-error=#warnings" "-Wall" "-Wimplicit-fallthrough" "-Wdeprecated" "-Wno-error=deprecated" "-Wno-backend-plugin" "-std=gnu++23" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-pgso=false" "-mllvm" "-enable-value-profiling=false" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "rpc-195796.cpp" -Wfatal-errors
```

This requires both rpc-195796.cpp and merged.profdata. 


[rpc-195796.cpp.gz](https://github.com/user-attachments/files/16380740/rpc-195796.cpp.gz)
[merged.profdata.gz](https://github.com/user-attachments/files/16380746/merged.profdata.gz)

**Comment by avikivity** [comment]
btw, to reproduce the crash, build clang 18.1.6 with asan or stack protector. Without them, there's a buffer overflow that isn't detected. The reason I saw the problem is that Fedora's clang 18.1.6 is build with -fstack-protector-all.

**Comment by avikivity** [comment]
@ellishg how can we make progress with this?

**Comment by ellishg** [comment]
@avikivity I'm not able to reproduce the error. It seems strange that you are getting the error "Do not know how to promote this operator!" since I think that might be during lowing to assembly, which should not happen with `-emit-llvm`.

**Comment by avikivity** [comment]
Did you build clang with asan or -fstack-protector-all? without them the rogue write isn't caught.

This snippet reproduces it with Fedora 40's build (which has -fstack-protector-all enabled). Replace podman with docker if needed. You'll need rpc-195796.cpp and merged.profdata in the same directory.

```sh
podman run -i -v $PWD:$PWD -w $PWD docker.io/fedora:40 <<EOF
dnf -y install clang
 "/usr/bin/clang++" "-cc1" "-triple" "x86_64-redhat-linux-gnu" "-emit-llvm-bc" "-flto=thin" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "rpc.cc" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "westmere" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "--compress-debug-sections=zlib" "-fdebug-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-fdebug-prefix-map=/home/avi/scylla-maint=." "-fprofile-instrument=csllvm" "-fprofile-instrument-path=/home/avi/scylla-maint/build/release-cs-pgo/default_%m.profraw" "-fprofile-instrument-use-path=merged.profdata" "-fcoverage-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-sys-header-deps" "-D" "FMT_SHARED" "-D" "SEASTAR_API_LEVEL=7" "-D" "SEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT" "-D" "SEASTAR_HAS_MEMBARRIER" "-D" "SEASTAR_HAVE_ASAN_FIBER_SUPPORT" "-D" "SEASTAR_HAVE_HWLOC" "-D" "SEASTAR_HAVE_NUMA" "-D" "SEASTAR_HAVE_SYSTEMTAP_SDT" "-D" "SEASTAR_LOGGER_COMPILE_TIME_FMT" "-D" "SEASTAR_LOGGER_TYPE_STDOUT" "-D" "SEASTAR_PTHREAD_ATTR_SETAFFINITY_NP" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=18" "-D" "SEASTAR_SSTRING" "-D" "SEASTAR_STRERROR_R_CHAR_P" "-D" "NDEBUG" "-U" "_FORTIFY_SOURCE" "-U" "NDEBUG" "-fmacro-prefix-map=/home/avi/scylla-maint=." "-fcoverage-prefix-map=/home/avi/scylla-maint=." "-O2"  "-Wno-backend-plugin"  "-std=gnu++23" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-pgso=false" "-mllvm" "-enable-value-profiling=false" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "rpc-195796.cpp"
EOF
```

**Comment by avikivity** [comment]
Here's my "Don't know how to promote this operator" run:

```console
$  "/usr/bin/clang++" "-cc1" "-triple" "x86_64-redhat-linux-gnu" "-emit-llvm-bc" "-flto=thin" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "rpc.cc" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "westmere" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "--compress-debug-sections=zlib" "-fdebug-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-fdebug-prefix-map=/home/avi/scylla-maint=." "-fprofile-instrument=csllvm" "-fprofile-instrument-path=/home/avi/scylla-maint/build/release-cs-pgo/default_%m.profraw" "-fprofile-instrument-use-path=merged.profdata" "-fcoverage-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-sys-header-deps" "-D" "FMT_SHARED" "-D" "SEASTAR_API_LEVEL=7" "-D" "SEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT" "-D" "SEASTAR_HAS_MEMBARRIER" "-D" "SEASTAR_HAVE_ASAN_FIBER_SUPPORT" "-D" "SEASTAR_HAVE_HWLOC" "-D" "SEASTAR_HAVE_NUMA" "-D" "SEASTAR_HAVE_SYSTEMTAP_SDT" "-D" "SEASTAR_LOGGER_COMPILE_TIME_FMT" "-D" "SEASTAR_LOGGER_TYPE_STDOUT" "-D" "SEASTAR_PTHREAD_ATTR_SETAFFINITY_NP" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=18" "-D" "SEASTAR_SSTRING" "-D" "SEASTAR_STRERROR_R_CHAR_P" "-D" "NDEBUG" "-U" "_FORTIFY_SOURCE" "-U" "NDEBUG" "-fmacro-prefix-map=/home/avi/scylla-maint=." "-fcoverage-prefix-map=/home/avi/scylla-maint=." "-O2"  "-Wno-backend-plugin"  "-std=gnu++23" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-pgso=false" "-mllvm" "-enable-value-profiling=false" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "rpc-195796.cpp" -emit-llvm -S  -disable-llvm-optzns -o a.ll  -Wno-all -Wno-writable-strings
fatal error: error in backend: Do not know how to promote this operator!
```

Again with clang 18.1.6. I'll try with trunk.

**Comment by avikivity** [comment]
trunk is able to generate llvm, but that doesn't help in reduction.

**Comment by tchaikov** [comment]
> ```
> "/usr/bin/clang++" "-cc1" "-triple" "x86_64-redhat-linux-gnu" "-emit-llvm-bc" "-flto=thin" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "rpc.cc" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "westmere" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "--compress-debug-sections=zlib" "-fdebug-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-fdebug-prefix-map=/home/avi/scylla-maint=." "-fprofile-instrument=csllvm" "-fprofile-instrument-path=/home/avi/scylla-maint/build/release-cs-pgo/default_%m.profraw" "-fprofile-instrument-use-path=merged.profdata" "-fcoverage-compilation-dir=/home/avi/scylla-maint/build/release-cs-pgo/seastar.lto" "-sys-header-deps" "-D" "FMT_SHARED" "-D" "SEASTAR_API_LEVEL=7" "-D" "SEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT" "-D" "SEASTAR_HAS_MEMBARRIER" "-D" "SEASTAR_HAVE_ASAN_FIBER_SUPPORT" "-D" "SEASTAR_HAVE_HWLOC" "-D" "SEASTAR_HAVE_NUMA" "-D" "SEASTAR_HAVE_SYSTEMTAP_SDT" "-D" "SEASTAR_LOGGER_COMPILE_TIME_FMT" "-D" "SEASTAR_LOGGER_TYPE_STDOUT" "-D" "SEASTAR_PTHREAD_ATTR_SETAFFINITY_NP" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=18" "-D" "SEASTAR_SSTRING" "-D" "SEASTAR_STRERROR_R_CHAR_P" "-D" "NDEBUG" "-U" "_FORTIFY_SOURCE" "-U" "NDEBUG" "-fmacro-prefix-map=/home/avi/scylla-maint=." "-fcoverage-prefix-map=/home/avi/scylla-maint=." "-O2"  "-Wno-backend-plugin"  "-std=gnu++23" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-pgso=false" "-mllvm" "-enable-value-profiling=false" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "rpc-195796.cpp" -emit-llvm -S  -disable-llvm-optzns -o a.ll  -Wno-all -Wno-writable-strings
> ```

FWIW, i am able to reproduce this issue with the attached source file and profile data, and the clang compiler packaged in 18.1.6-3.fc40 on fedora 40.

**Comment by avikivity** [comment]
@ellishg looks like we are stalled again. I don't believe it's possible to reduce the reproducer, as HEAD probably rejects the provided profile measurements, and 18.1.6 isn't able to emit llvm without applying some coroutine related passes first.

**Comment by avikivity** [comment]
@ellishg what can I do next? look for another reviewer? close the pull request?

**Comment by snehasish** [comment]
cc: @mtrofin who has looked into profile related co-routine issues before.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp [hunk 2]
```diff
@@ -1623,10 +1623,12 @@ void PGOUseFunc::setBranchWeights() {
...
     // We have a non-zero Branch BB.
-    unsigned Size = BBCountInfo.OutEdges.size();
-    SmallVector<uint64_t, 2> EdgeCounts(Size, 0);
+    unsigned OutEdgesCount = BBCountInfo.OutEdges.size();
+    unsigned SuccessorCount = BB.getTerminator()->getNumSuccessors();
+
+    SmallVector<uint64_t, 2> EdgeCounts(SuccessorCount, 0);
     uint64_t MaxCount = 0;
-    for (unsigned s = 0; s < Size; s++) {
+    for (unsigned s = 0; s < OutEdgesCount; s++) {
```
Comment (mtrofin) [inline llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1631]: nit: while at it, can you please change `s` to `S` or `It` or something conforming to the coding style? thanks.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp [hunk 3]
```diff
@@ -1623,10 +1623,12 @@ void PGOUseFunc::setBranchWeights() {
       continue;
 
     // We have a non-zero Branch BB.
-    unsigned Size = BBCountInfo.OutEdges.size();
-    SmallVector<uint64_t, 2> EdgeCounts(Size, 0);
+    unsigned OutEdgesCount = BBCountInfo.OutEdges.size();
+    unsigned SuccessorCount = BB.getTerminator()->getNumSuccessors();
+
+    SmallVector<uint64_t, 2> EdgeCounts(SuccessorCount, 0);
```
Comment (mtrofin) [inline llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: Can you explain why coroutines would produce a BB with a successor with an ID outside BBCountInfo.OutEdges?

From there we can figure out a small test case, too.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp (hunk 2 above)
Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1631]: Sure.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp (hunk 3 above)
Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: I'm not an LLVM developer. I don't even know what a successor is in this context.  I observed a crash, and following the source I saw the EdgeCounts vector was sized differently than the range of the index. So I changed the vector size to match the range of the index.

Since I don't observe the crash in llvm main, it could be that it changed so that the range of the index now matches the size of the vector. It could also be (and I think this is likely) that the pgo machinery changed enough that the 18.1.6 based profile no longer triggers the bug. I don't have any way to tell. I believe the change improves the code either way (though only cosmetically in one case).

I'm willing to follow guidance in order to generate a test case, but my knowledge here is almost nil.

**Comment by avikivity** [comment]
Update: renamed local `s` to `It` to conform with coding style.

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp (hunk 3 above)
Comment (mtrofin) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: (sorry for the delay, somehow I missed / got no notifications)

If the source you're observing the crash in is something you share (IIUC it is - earlier paste), could you do this, while in a debugger (assuming the unchanged, buggy code):

- get to the place where you observe the crash
- `p BB.getParent()->dump()`
- also `p BB.dump()`
- also `p Size` and `p s` for the failing `s`

Can you share those in a gist (less inlined stuff in the comments, easier to parse)? (Thanks!)

The first dumps the IR (intermediate representation) of the function that causes the problem. The latter, just the [basic block](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/IR/BasicBlock.h#L47). A function's instructions are organized in a [control flow graph (CFG)](https://en.wikipedia.org/wiki/Control-flow_graph) where the nodes are basic blocks. The CFG is directed, and "successor" of a node X is a node Y for which there is an edge X->Y.

Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: https://gist.github.com/avikivity/ee2e860be4dd5179b9f8ee70a2e9f487

Comment (mtrofin) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: oh - what's `SuccNum`?

Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]:
```
(gdb) p SuccNum
$5 = 2
```

I can provide a docker image that will drop you into gdb at the crash point, if you want.

Comment (mtrofin) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: Depends - if you are interested in digging more into llvm, happy to help along. If not, rather than a docker, you can just give me the module: add `-mllvm -print-before=pgo-instr-use` to your compiler invocation, and paste that output to a gist.

Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: This is probably too deep for me to learn much. I don't mind following instructions to deliver new data, I'm just concerned that with multi-hour round-trip times, this can take several weeks to resolve.

Anyway here's the -print-before=pgo-instr-use output: https://gist.github.com/avikivity/f47fa3765bd49e05524578d62c118cfd

Comment (ellishg) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1629]: Ah, I didn't know you were able to run `-print-before=pgo-instr-use`!  I now able to reproduce and I think I can get a reasonable test case.

**Comment by ellishg** [comment]
And here is a nice reproducer!

```llvm
; RUN: rm -rf %t && split-file %s %t

; RUN: llvm-profdata merge %t/a.proftext -o %t/a.profdata
; RUN: opt < %t/a.ll --passes=pgo-instr-use -pgo-test-profile-file=%t/a.profdata

;--- a.ll
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-redhat-linux-gnu"

define void @_bar() presplitcoroutine personality ptr null {
  %1 = call token @llvm.coro.save(ptr null)
  %2 = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %2, label %5 [
    i8 0, label %3
    i8 1, label %4
  ]

3:                                                ; preds = %0
  ret void

4:                                                ; preds = %0
  ret void

5:                                                ; preds = %0
  ret void
}

declare token @llvm.coro.save(ptr)

declare i8 @llvm.coro.suspend(token, i1)

;--- a.proftext
# IR level Instrumentation Flag
:ir

_bar
# Func Hash:
1063705160175073211
# Num Counters:
2
1
0
```

It seems that the `switch` is causing a mismatch between the number of out edges, but I'm not sure how this is related to `coro`. Anyway, I suspect it might be better to fix `OutEdges` in `PGOUseBBInfo` rather than using a different value in this one location.

**Comment by avikivity** [comment]
> Anyway, I suspect it might be better to fix OutEdges in PGOUseBBInfo rather than using a different value in this one location.

If you want me to do that, you'll have to provide (unfortunately detailed) guidance, because I don't know how.

**Comment by mtrofin** [comment]
> > Anyway, I suspect it might be better to fix OutEdges in PGOUseBBInfo rather than using a different value in this one location.
> 
> If you want me to do that, you'll have to provide (unfortunately detailed) guidance, because I don't know how.

Looking.

**Comment by mtrofin** [comment]
> > > Anyway, I suspect it might be better to fix OutEdges in PGOUseBBInfo rather than using a different value in this one location.
> > 
> > 
> > If you want me to do that, you'll have to provide (unfortunately detailed) guidance, because I don't know how.
> 
> Looking.

OK, here's what happens:
refer to https://github.com/llvm/llvm-project/pull/71262. We have a reason to mark certain edges like in this case as "removed". If they are, they don't get added to a node's out edges (see `PGOInstrumentation.cpp`, `setupBBInfoEdges`). The code @avikivity fixed works if the numbering of the removed edges is such that they end up at the end of the successors list.

I think we have 2 alternatives: add `Removed` edges; or @avikivity's fix. I like the latter because the former would require going over a lot of places and checking `if (E->Removed) continue;`, and missing some spots would lead to :shrug: - basically quiet/action at a distance failures, likely; vs keeping the status quo (i.e. skipping over `Removed` edges) which at least leads to prompt failures.

WDYT? @xur-llvm also.

@avikivity so all you'd need (pending other folks' feedback on the above) is to add the file @ellishg pasted above - probably place it in `llvm/test/Transforms/Coroutines` or something like that - and I'd add a comment where you get the various Sizes as to why this way (the explanation above).

Thanks for the fix, too!

**Comment by avikivity** [comment]
Interesting,  in https://github.com/llvm/llvm-project/issues/97962#issuecomment-2213712656 I bisected the bug to that very commit. I'll try to add the reproducer tomorrow.

**Comment by avikivity** [comment]
Update:
 - rebased
 - added test case

File: llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp (hunk 3 above)
Comment (mtrofin) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1634]: Can you add a comment as to why we need to dimension EdgeCounts like that? (basically "`Removed` edges don't appear in `OutEdges`). Also I'd add an `assert(OutEdgesCount <= SuccessorCount)

otherwise LGTM, but wait also for @ellishg and/or @xur-llvm

Comment (avikivity) [reply llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp:1638]: Done

**Comment by avikivity** [comment]
Update:
 - added a (hopefully helpful) comment to explain why EdgeCounts is sizes differently than BBCountInfo.OutEdges()
 - added an assertion about the two sizes.

**Comment by avikivity** [comment]
I believe the test failure is unrelated (somewhere in lldb) so I rebased to re-trigger the tests.

**Review by mtrofin — APPROVED** [review]
LGTM

**Comment by avikivity** [comment]
@xur-llvm I believe this bugfix is waiting only for your approval, kindly review

**Comment by avikivity** [comment]
@mtrofin a week has passed, can we perhaps enlist a different reviewer?

**Comment by mtrofin** [comment]
> @mtrofin a week has passed, can we perhaps enlist a different reviewer?

Let's merge it at this point. Do you have commit rights?

**Comment by mtrofin** [comment]
### Merge activity

* **Aug 26, 10:47 AM EDT**: @mtrofin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/99064).

**Comment by mtrofin** [comment]
> > > @mtrofin a week has passed, can we perhaps enlist a different reviewer?
> 
> > 
> 
> > Let's merge it at this point. Do you have commit rights?
> 
> 
> 
> I do not. I'm not an LLVM developer, just a random person on the internet.

Taking care of it.

**Comment by avikivity** [comment]
> > > > @mtrofin a week has passed, can we perhaps enlist a different reviewer?
> > 
> > 
> > > 
> > 
> > 
> > > Let's merge it at this point. Do you have commit rights?
> > 
> > 
> > I do not. I'm not an LLVM developer, just a random person on the internet.
> 
> Taking care of it.

Thanks!

**Comment by avikivity** [comment]
Thanks a lot @ellishg and @mtrofin for your help and guidance.

Can this please be backported to release/19.x?

**Comment by tchaikov** [comment]
this is the failed test:

```
[830/1003] Running unit test libc.test.src.stdio.fscanf_test.__unit__
FAILED: projects/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fscanf_test.__unit__ /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fscanf_test.__unit__ 
cd /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio && /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio/libc.test.src.stdio.fscanf_test.__unit__.__build__
[==========] Running 1 test from 1 test suite.
[ RUN      ] LlvmLibcFScanfTest.WriteToFile
Segmentation fault
```

not sure if it is relevant.

**Comment by mtrofin** [comment]
> this is the failed test:
> 
> ```
> [830/1003] Running unit test libc.test.src.stdio.fscanf_test.__unit__
> FAILED: projects/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fscanf_test.__unit__ /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fscanf_test.__unit__ 
> cd /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio && /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian/libc-x86_64-debian-dbg/build/projects/libc/test/src/stdio/libc.test.src.stdio.fscanf_test.__unit__.__build__
> [==========] Running 1 test from 1 test suite.
> [ RUN      ] LlvmLibcFScanfTest.WriteToFile
> Segmentation fault
> ```
> 
> not sure if it is relevant.

Seems like it's a transient issue on that bot. (Also, a change in instrumentation shouldn't affect a libc test... normally. But the status of the subsequent build, https://lab.llvm.org/buildbot/#/builders/93/builds/4910,  is a stronger signal.)

**Comment by mtrofin** [comment]
> Thanks a lot @ellishg and @mtrofin for your help and guidance.
> 
> Can this please be backported to release/19.x?

@tstellar for the release bit. @tstellar happy to help, is this more than cherrypicking to a particular branch?

**Comment by avikivity** [comment]
> > Thanks a lot @ellishg and @mtrofin for your help and guidance.
> > 
> > Can this please be backported to release/19.x?
> 
> @tstellar for the release bit. @tstellar happy to help, is this more than cherrypicking to a particular branch?

It's just cherrypicking. I already know it backports directly to 18.x, so 19.x should work too.
