### PR TITLE
[LifetimeSafety] Fix crash on ternary operator when one of the expressions is `throw`

### LINKED ISSUE #183895: [LifetimeSafety] Assertion `Src && "Dst is non-null but Src is null. List must have the same length"' failed.
Reproducer:
https://godbolt.org/z/TWzrqW1rh
```cpp
int val = 42;

int foo() {
  return val ? throw val : val;
}
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp:54: void clang::lifetimes::internal::FactsGenerator::flow(clang::lifetimes::internal::OriginList*, clang::lifetimes::internal::OriginList*, bool): Assertion `Src && "Dst is non-null but Src is null. List must have the same length"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -Werror=lifetime-safety <source>
1.	<eof> parser at end of file
2.	<source>:3:11: parsing function body 'foo'
 #0 0x000000000440ac38 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x440ac38)
 #1 0x0000000004408084 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4408084)
 #2 0x0000000004347e88 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000787235c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000787235c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000787235c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000787235c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000787235c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000787235c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x00000000079cbedd clang::lifetimes::internal::FactsGenerator::flow(clang::lifetimes::internal::OriginList*, clang::lifetimes::internal::OriginList*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x79cbedd)
#10 0x00000000079cc129 clang::lifetimes::internal::FactsGenerator::VisitConditionalOperator(clang::ConditionalOperator const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x79cc129)
#11 0x00000000079d04bf clang::lifetimes::internal::FactsGenerator::run() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x79d04bf)
#12 0x000000000797a496 clang::lifetimes::internal::LifetimeSafetyAnalysis::run() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x797a496)
#13 0x000000000797b405 clang::lifetimes::runLifetimeSafetyAnalysis(clang::AnalysisDeclContext&, clang::lifetimes::LifetimeSafetySemaHelper*, clang::lifetimes::LifetimeSafetyStats&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x797b405)
#14 0x00000000078b4a4b clang::sema::AnalysisBasedWarnings::IssueWarnings(clang::sema::AnalysisBasedWarnings::Policy, clang::sema::FunctionScopeInfo*, clang::Decl const*, clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78b4a4b)
#15 0x0000000006d71692 clang::Sema::PopFunctionScopeInfo(clang::sema::AnalysisBasedWarnings::Policy const*, clang::Decl*, clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d71692)
#16 0x0000000006fd2384 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fd2384)
#17 0x0000000006cebb94 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cebb94)
#18 0x0000000006bf11c3 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bf11c3)
#19 0x0000000006c2785d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c2785d)
#20 0x0000000006be4bbb clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6be4bbb)
#21 0x0000000006be53bf clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6be53bf)
#22 0x0000000006bec9c1 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bec9c1)
#23 0x0000000006bed8f5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bed8f5)
#24 0x0000000006bcefda clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6bcefda)
#25 0x0000000004ee4ef8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ee4ef8)
#26 0x00000000051eb615 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51eb615)
#27 0x00000000051698fe clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51698fe)
#28 0x00000000052e72dd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52e72dd)
#29 0x0000000000df063e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdf063e)
#30 0x0000000000de6faa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#31 0x0000000000de712d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#32 0x0000000004f59659 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#33 0x00000000043482c4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43482c4)
#34 0x0000000004f59c6f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#35 0x0000000004f19952 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f19952)
#36 0x0000000004f1a8fe clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f1a8fe)
#37 0x0000000004f22645 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f22645)
#38 0x0000000000dec9ae clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdec9ae)
#39 0x0000000000ca4d0a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca4d0a)
#40 0x0000787235c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#41 0x0000787235c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#42 0x0000000000de6a45 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde6a45)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by NeKon69**
Ternary operator now doesn't flow origins from `[[noreturn]]` arms, including `throw` statements.

Closes #183895

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Oh interesting. There is an API called `hasNoReturnElement` on the CfgBlock, so we could alternatively use that one.

That being said, it does not solve the `throw` case. It would definitely be great if the CFG was more faithful for exceptions but I am not sure how big of a project would it be to fix this aspect of our CFG. So I am fine with the original approach and maybe we can add a comment to rely more on the shape of the CFG once this is fixed.

If you feel adventurous, you could give the CFG changes a try in a separate PR.

**Comment by NeKon69** [comment]
Oh yeah this actually worked. I had no idea this API already existed

**Comment by NeKon69** [comment]
I implemented something like this. I would be happy to hear any suggestions!

**Comment by NeKon69** [comment]
Oh we want to avoid AST matching, okay got it. Will push a commit in a bit

**Comment by usx95** [comment]
> We should not have flow from r to p but we do. Why? Because r is a subexpression of the ternary and the fact generation will only look at the subexpressions of the ternary without consulting the CFG whether we actually have an edge between those AST nodes in the control flow.

Thanks for clarification. Sounds good to me then.

> I'm wondering if the cleanest solution would be something like:
> 
> * Get the Cfg node corresponding to evaluating the condition. The successors of this node are the branches.
> * Check if those branches are sink nodes, as in they never reach the end of the function call. You could use `isInevitablySinking` and do the flow only if this API returns false.
> 
> I think this might handle all of the complex cases more robustly.
> 
> That being said, `isInevitablySinking` looks like a relatively expensive API to call and calling it on multiple disparate CFGNodes seem to do some redundant work as the subtasks for the commonly reachable nodes are not cached. So I am not 100% sure if we actually need this precision at the cost of too much computation.

> The best solution might be to make `isInevitablySinking` a bit cheaper and use it for the flow but that might be a bit more work.

I really like this. While we are at it, I think it might be worth pursuing. It looks like that it would be relatively simpler to introduce a cache for the DFS in `isInevitablySinking`, e.g. a 2-bit `SinkingCache` in `CFGBlock` to memoize the reachability results (uncomputed, sinking, or not sinking). If there is any successor which is not-sinking, then current block is not sinking.

**Comment by NeKon69** [comment]
Ok well I tried what I wanted to try but it doesn't seem to work for some reason. It still says there is an edge for this example
```cpp
int foo() {
  int val = 0;
  return val ? throw 1 : val;
}
```

Here's the code I wrote to detect whether there is an edge (if it will help I can push it to github):
```cpp
  const auto *TI = COBlock->succ_begin();
  const auto *FI = TI + 1;

  bool TBHasEdge = TI->getReachableBlock() != nullptr; // <-- ends up as true
  bool FBHasEdge = FI->getReachableBlock() != nullptr; // <-- ends up as true
```

**Comment by NeKon69** [comment]
What I’m thinking is maybe we can store the current processed block inside `FactsGenerator`. We can update it right before we call `Visit` in `FactsGenerator::run`. I’m worried about whether it is okay to modify `FactsGenerator`’s size. What do you think?

**Comment by NeKon69** [comment]
So my code crashes on

```cpp
[[noreturn]] int *noret_f(int *p);

int *noreturn_dead_false(bool cond, int *num) {
  int local = 0;
  return cond ? num : noret_f(&local);
}
```

with `Assertion 'Dst->getLength() == Src->getLength() && "Lists must have the same length"'`. I ran this example through a debugger, and it looks like it goes through exactly the path it’s supposed to take: it flows through the `true` branch and ignores the `false`(`noreturn`) branch. But the interesting part is that it crashes when we flow through the `true` branch. I assume I missed something obvious in the code..

**Review by Xazax-hun — COMMENTED** [review]
This looks great! This is very close to what I had in mind. I added one inline comment, I wonder if you can simplify the implementation a bit based on that.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 1]
```diff
@@ -400,12 +401,58 @@ void FactsGenerator::VisitBinaryOperator(const BinaryOperator *BO) {
...
+    FBHasEdge = !TBHasEdge;
+    break;
+  case 2: {
+    const auto *It = Preds.begin();
+    TBHasEdge = It->isReachable();
+    FBHasEdge = (++It)->isReachable();
+    break;
+  }
+  default:
+    llvm_unreachable("expected at most 2 successors");
```
Comment (NeKon69) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Oh, this message is incorrect, it's actually predecessors now

**Review by Xazax-hun — APPROVED** [review]
Overall, looks good to me. I think the case where we actually need to do the search in the CFG block supposed to be relatively rare so I don't think it is a performance concern.

File: clang/test/Sema/warn-lifetime-safety.cpp [hunk 2]
```diff
@@ -2418,3 +2418,58 @@ void owner_outlives_lifetimebound_source() {
...
+
+int *constexpr_dead_false(int *num) {
+  int local = 0;
+  return kTrue ? num : f(&local);
+}
+
+int *constexpr_dead_nested(int *num) {
+  int local = 0;
+  return kTrue ? (kTrue ? num : f(&local)) : num; 
+}
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/test/Sema/warn-lifetime-safety.cpp:2455]: Yes. I think that should make it work.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 3]
```diff
@@ -401,12 +402,57 @@ void FactsGenerator::VisitBinaryOperator(const BinaryOperator *BO) {
...
+
+  // Skip origin flow from conditional operator arms that cannot produce the
+  // result value: throw arms and calls to noreturn functions.
+  bool TBHasEdge = true;
+  bool FBHasEdge = true;
+
+  switch (CurrentBlock->pred_size()) {
+  case 0:
+    return;
+  case 1:
```
Comment (usx95) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: nit: enclose in braces as in `case 2`.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 4]
```diff
@@ -401,12 +402,57 @@ void FactsGenerator::VisitBinaryOperator(const BinaryOperator *BO) {
...
+    TBHasEdge = PredHasStmt(*Preds.begin(), TrueExpr->IgnoreParenImpCasts());
```
Comment (usx95) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Consider inlining `PredHasStmt` as it is not used only once.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 5]
```diff
@@ -401,12 +402,57 @@ void FactsGenerator::VisitBinaryOperator(const BinaryOperator *BO) {
...
+    return;
+  }
+
+  bool FirstFlow = true;
+  auto HandleFlow = [&](const Expr *E) {
+    if (FirstFlow) {
+      killAndFlowOrigin(*CO, *E);
+      FirstFlow = false;
+    } else
+      flowOrigin(*CO, *E);
```
Comment (usx95) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp:449]: nit: add braces.   
LLVM coding standards:  
https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements  
// Use braces for the `else if` and `else` block to keep it uniform with the
// `if` block.

File: clang/test/Sema/warn-lifetime-safety.cpp [hunk 6]
```diff
@@ -1,5 +1,6 @@
 // RUN: %clang_cc1 -fsyntax-only -Wlifetime-safety -Wno-dangling -verify=expected,function %s
 // RUN: %clang_cc1 -fsyntax-only -flifetime-safety-inference -fexperimental-lifetime-safety-tu-analysis -Wlifetime-safety -Wno-dangling -verify=expected,tu %s
+// RUN: %clang_cc1 -fsyntax-only -Wlifetime-safety -Wno-dangling -fcxx-exceptions -verify=expected,function,exception %s
```
Comment (usx95) [inline clang/test/Sema/warn-lifetime-safety.cpp]: IIUC `-verify=exception` is not used. Please remove it is so.

**Review by usx95 — APPROVED** [review]
Looks really good. Last few nits. Happy to land adter these are addressed.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp (hunk 3 above)
Comment (NeKon69) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp]: Only for `case 1` I assume?

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 7]
```diff
@@ -401,12 +402,58 @@ void FactsGenerator::VisitBinaryOperator(const BinaryOperator *BO) {
...
+  case 0:
+    return;
+  case 1: {
+    TBHasEdge = llvm::any_of(**Preds.begin(),
+                             [ExpectedStmt = TrueExpr->IgnoreParenImpCasts()](
+                                 const CFGElement &Elt) {
+                               if (auto CS = Elt.getAs<CFGStmt>())
+                                 return CS->getStmt() == ExpectedStmt;
+                               return false;
+                             });
```
Comment (NeKon69) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp:428]: Formatting is a bit weird after I inlined the lambda, but it's fine, I guess?
