### PR TITLE
[llvm-exegesis] Set stack pointer register after starting perf counter

### LINKED ISSUE #72193: llvm-exegesis does not work for one snippet with RSP defined
```
# LLVM-EXEGESIS-MEM-DEF test1 4096 2147483647
# LLVM-EXEGESIS-MEM-MAP test1 1048576
# LLVM-EXEGESIS-DEFREG RAX 100000
# LLVM-EXEGESIS-DEFREG RBX 100000
# LLVM-EXEGESIS-DEFREG RCX 100000
# LLVM-EXEGESIS-DEFREG RDX 100000
# LLVM-EXEGESIS-DEFREG RSI 100000
# LLVM-EXEGESIS-DEFREG RDI 100000
# LLVM-EXEGESIS-DEFREG RBP 100000
# LLVM-EXEGESIS-DEFREG RSP 100000
# LLVM-EXEGESIS-DEFREG R8 100000
# LLVM-EXEGESIS-DEFREG R9 100000
# LLVM-EXEGESIS-DEFREG R10 100000
# LLVM-EXEGESIS-DEFREG R11 100000
# LLVM-EXEGESIS-DEFREG R12 100000
# LLVM-EXEGESIS-DEFREG R13 100000
# LLVM-EXEGESIS-DEFREG R14 100000

movq %r14, (%rax)
```
This code snippet is tested by the following command
```
llvm-exegesis --mode=inverse_throughput -execution-mode=subprocess  --snippets-file=llvm-exe-test/1.test
```
Version of llvm-exegsis is based on SHA https://github.com/llvm/llvm-project/commit/2a1f1b5fde0a2e03f94fa2cb5c7765d405fda0de

Output is
```
---
mode:            inverse_throughput
key:
  instructions:
    - 'MOVDQUrm XMM1 RDI i_0x1 %noreg i_0x0 %noreg'
    - 'MOVDQUrm XMM0 RSI i_0x1 %noreg i_0x0 %noreg'
    - 'PCMPEQBrr XMM0 XMM0 XMM1'
    - 'PMINUBrr XMM0 XMM0 XMM1'
    - 'PXORrr XMM1 XMM1 XMM1'
    - 'PCMPEQBrr XMM0 XMM0 XMM1'
    - 'PMOVMSKBrr EAX XMM0'
    - 'TEST64rr RAX RAX'
  config:          ''
  register_initial_values:
    - 'RAX=0x10000'
    - 'RBX=0x10000'
    - 'RCX=0x10000'
    - 'RDX=0x10000'
    - 'RSI=0x10000'
    - 'RDI=0x10000'
    - 'RBP=0x10000'
    - 'RSP=0x10000'
    - 'R8=0x10000'
    - 'R9=0x10000'
    - 'R10=0x10000'
    - 'R11=0x10000'
    - 'R12=0x10000'
    - 'R13=0x10000'
    - 'R14=0x10000'
    - 'R15=0x10000'
    - 'XMM0=0x10000'
    - 'XMM1=0x10000'
    - 'XMM2=0x10000'
    - 'XMM3=0x10000'
    - 'XMM4=0x10000'
    - 'XMM5=0x10000'
    - 'XMM6=0x10000'
    - 'XMM7=0x10000'
    - 'XMM8=0x10000'
    - 'XMM9=0x10000'
    - 'XMM10=0x10000'
    - 'XMM11=0x10000'
    - 'XMM12=0x10000'
    - 'XMM13=0x10000'
    - 'XMM14=0x10000'
    - 'XMM15=0x10000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-unknown-linux-gnu
num_repetitions: 10000
measurements:    []
error:           'The benchmarking subprocess sent unexpected signal: Segmentation fault'
info:            ''
assembled_snippet: 554157415641554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA01001000000000004D89E849B9000000000000000048B809000000000000000F0548BF000001000000000048BE001000000000000048BA030000000000000049BA010010000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F000048B8000001000000000048BB000001000000000048B9000001000000000048BA000001000000000048BE000001000000000048BF000001000000000048BD000001000000000048BC000001000000000049B8000001000000000049B9000001000000000049BA000001000000000049BB000001000000000049BC000001000000000049BD000001000000000049BE000001000000000049BF00000100000000004883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F04244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F0C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F14244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F1C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F24244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F2C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F34244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F3C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F04244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F0C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F14244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F1C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F24244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F2C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F34244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F3C244883C41050575648BF00E0FFFFFF7F00008B3F48BE032400000000000048B810000000000000000F055E5858F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C048BF00E0FFFFFF7F00008B3F48BE012400000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415D415E415F5DC3
...
```

Interestingly, if you remove the line `# LLVM-EXEGESIS-DEFREG RSP 100000`, `llvm-exegesis` works correctly on my machine, generated the output
```
---
mode:            inverse_throughput
key:
  instructions:
    - 'MOV64mr RAX i_0x1 %noreg i_0x0 %noreg R14'
  config:          ''
  register_initial_values:
    - 'RAX=0x100000'
    - 'RBX=0x100000'
    - 'RCX=0x100000'
    - 'RDX=0x100000'
    - 'RSI=0x100000'
    - 'RDI=0x100000'
    - 'RBP=0x100000'
    - 'R8=0x100000'
    - 'R9=0x100000'
    - 'R10=0x100000'
    - 'R11=0x100000'
    - 'R12=0x100000'
    - 'R13=0x100000'
    - 'R14=0x100000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-unknown-linux-gnu
num_repetitions: 10000
measurements:
  - { key: inverse_throughput, value: 1.1839, per_snippet_value: 1.1839 }
error:           ''
info:            ''
assembled_snippet: 55415641554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA01001000000000004D89E849B9000000000000000048B809000000000000000F0548BF000010000000000048BE001000000000000048BA030000000000000049BA010010000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F000048B8000010000000000048BB000010000000000048B9000010000000000048BA000010000000000048BE000010000000000048BF000010000000000048BD000010000000000049B8000010000000000049B9000010000000000049BA000010000000000049BB000010000000000049BC000010000000000049BD000010000000000049BE000010000000000050575648BF00E0FFFFFF7F00008B3F48BE032400000000000048B810000000000000000F055E58584C89304C89304C89304C893048BF00E0FFFFFF7F00008B3F48BE012400000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415D415E5DC3
...
```

### PR DESCRIPTION
**Pull request by boomanaiden154**
Before this patch, in subprocess mode, llvm-exegesis setup the stack pointer register with the rest of the registers when it was requested by the user. This would cause a segfault when the instructions to start the perf counter ran as they use the stack to preserve the three registers needed to make the syscall. This patch moves the setup of the stack register to after the configuration of the perf counter to fix this issue so that we have a valid stack pointer for all the preceeding operations.

Regression test added.

This fixes #72193.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
@ondrasej 

This probably isn't the cleanest way to do this. Very open to suggestions in that regard. It would probably be cleaner to not use the stack and move values directly between registers and memory, but that requires clobbering at least one register to hold a memory address as there is no move instruction that takes a 64 bit immediate as an address, so that isn't a viable solution. Maybe there's a solution that I'm missing though.

Ready for reviewer comments either way though.

**Comment by legrosbuffle** [comment]
I'm wondering whether we even want to support user-defined values for the stack pointer anyway. Is there a use case for this ?

**Comment by boomanaiden154** [comment]
> I'm wondering whether we even want to support user-defined values for the stack pointer anyway. Is there a use case for this ?

Yes. For the execution of arbitrary basic blocks with memory annotations for the construction of a datasets of BBs, there will definitely be BBs using the `%rsp` register (which is what we originally intended memory annotations to be used for). Not supporting this also prevents the use of instructions like `pushq` and `popq` in snippets which are bound to come up at some point in a microbenchmarking situation.

**Comment by boomanaiden154** [comment]
@legrosbuffle Can you take another look at this? It should be ready and I think there's a compelling case for supporting user-set stack pointer registers.

File: llvm/tools/llvm-exegesis/lib/Target.h [hunk 1]
```diff
@@ -170,6 +170,12 @@ class ExegesisTarget {
         "configurePerfCounter is not implemented on the current architecture");
   }
 
+  // Returns the stack register for the platform.
+  virtual unsigned getStackRegister() const {
+    report_fatal_error(
+        "getStackRegister is not implemented on the current architecture");
+  }
```
Comment (legrosbuffle) [inline llvm/tools/llvm-exegesis/lib/Target.h:177]: We can probably avoid introducing a new virtual call by using `TargetLowering` in `LLVMState`.

The stack pointer is `state.getSubtargetInfo().getTargetLowering()->getStackPointerRegisterToSaveRestore();`

This would avoid having to reimplement that in `ExegesisTarget` for every architecture.

**Review by legrosbuffle — APPROVED** [review]
