### PR TITLE
[FLANG] Correctly handle bad AT descriptors in FORMAT statements

### LINKED ISSUE #194237: [flang] Incorrect error handling of bad AT descriptors in FORMAT statement
Consider this good test with AT descriptors:
```
print '(AT,A)', "  string   ", "|"
print 42, "  string   ", "|"
42 format (AT,A)
end 
```
It produces correct output:
```
$ flang trim-good.f90 && ./a.out
  string|
  string|
```
Let's use invalid `AT10` descriptor in the first `print` statement:
```
print '(AT10,A)', "  string   ", "|"
print 42, "  string   ", "|"
42 format (AT,A)
end 
```
This produces expected error message:
```
$ flang trim-fail-1.f90 && ./a.out
error: Semantic errors in trim-fail-1.f90
trim-fail-1.f90:1:11: error: 'AT' edit descriptor does not accept a width value
  print '(AT10,A)', "  string   ", "|"
            ^^
```
Let's then add `AT10` to `format` statement:
```
print '(AT10,A)', "  string   ", "|"
print 42, "  string   ", "|"
42 format (AT10,A)
end 
```
This produces unexpected errors:
```
$ flang trim-fail-2.f90 && ./a.out
error: Could not parse trim-fail-2.f90
trim-fail-2.f90:3:19: error: expected '=>'
  42 format (AT10,A)
                    ^
trim-fail-2.f90:3:4: in the context: pointer assignment statement
  42 format (AT10,A)
     ^
trim-fail-2.f90:3:1: in the context: execution part construct
  42 format (AT10,A)
  ^
trim-fail-2.f90:3:19: error: expected '('
  42 format (AT10,A)
                    ^
trim-fail-2.f90:3:4: in the context: pointer assignment statement
  42 format (AT10,A)
     ^
trim-fail-2.f90:3:1: in the context: execution part construct
  42 format (AT10,A)
  ^
trim-fail-2.f90:3:19: error: expected '='
  42 format (AT10,A)
                    ^
trim-fail-2.f90:3:4: in the context: assignment statement
  42 format (AT10,A)
     ^
trim-fail-2.f90:3:1: in the context: execution part construct
  42 format (AT10,A)
  ^
```
Not only the errors are wrong for the second `print` statement, even the error for the first `print` statement is missing.

flang revision:
```
flang version 23.0.0git (https://github.com/llvm/llvm-project a75e6a59ede46e838e9a02bafe59aa9eb4c1ac60)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

### PR DESCRIPTION
**Pull request by laoshd**
Also update tests to cover more situations.

This PR will fix #194237.

### CODE REVIEW

File: flang/include/flang/Common/format.h [hunk 1]
```diff
@@ -735,6 +735,8 @@ template <typename CHAR> bool FormatValidator<CHAR>::Check() {
       }
       if (stmt_ == IoStmtKind::Read) {
         ReportError("'AT' edit descriptor must not be used for input");
+        suppressMessageCascade_ =
```
Comment (eugeneepshteyn) [inline flang/include/flang/Common/format.h]: Could you please do me a favor and move the comment on its own line, so that assignment could be on the same line?

**Review by eugeneepshteyn — APPROVED** [review]
LGTM, with request for slight reformatting.

File: flang/include/flang/Common/format.h (hunk 1 above)
Comment (laoshd) [reply flang/include/flang/Common/format.h]: The comments are moved to separate lines.

**Review by eugeneepshteyn — APPROVED** [review]

**Comment by laoshd** [comment]
@eugeneepshteyn would you help to merge it please? I don't have write access. Thanks.
