### PR TITLE
[Legalizer] Expand fmaximum and fminimum

### LINKED ISSUE #64209: [PowerPC] Cannot select llvm.{min,max}imum.{f32,f64}
It seems that none of these intrinsics are currently working on PowerPC:

- llvm.minimum.f32
- llvm.minimum.f64
- llvm.maximum.f32
- llvm.maximum.f64

Error output [\[godbolt\]](https://godbolt.org/z/cMzhbYKjG):
```
LLVM ERROR: Cannot select: 0x71ba4c0: f32 = fmaximum 0x71ba370, 0x71ba450
  0x71ba370: f32,ch = CopyFromReg 0x714d030, Register:f32 %0
    0x71ba300: f32 = Register %0
  0x71ba450: f32,ch = CopyFromReg 0x714d030, Register:f32 %1
    0x71ba3e0: f32 = Register %1
In function: _ZN1a4test17hb60f9f6975710eeaE
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'PowerPC DAG->DAG Pattern Instruction Selection' on function '@_ZN1a4test17hb60f9f6975710eeaE'
 #0 0x0000000003066278 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3066278)
 #1 0x0000000003063e3c SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fda056b9420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007fda0517c00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007fda0515b859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x000000000069cfa2 llvm::RISCVISAInfo::updateImplication() (.cold) RISCVISAInfo.cpp:0:0
 #6 0x0000000002e4f044 llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2e4f044)
 #7 0x0000000002e546d5 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2e546d5)
 #8 0x0000000001558153 (anonymous namespace)::PPCDAGToDAGISel::Select(llvm::SDNode*) PPCISelDAGToDAG.cpp:0:0
 #9 0x0000000002e4c6a7 llvm::SelectionDAGISel::DoInstructionSelection() (/opt/compiler-explorer/clang-trunk/bin/llc+0x2e4c6a7)
#10 0x0000000002e58f65 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-trunk/bin/llc+0x2e58f65)
#11 0x0000000002e5b9b9 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2e5b9b9)
#12 0x0000000002e5e086 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) SelectionDAGISel.cpp:0:0
#13 0x000000000155ebf7 (anonymous namespace)::PPCDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) PPCISelDAGToDAG.cpp:0:0
#14 0x0000000002443820 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#15 0x00000000029263f2 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x29263f2)
#16 0x0000000002926571 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2926571)
#17 0x00000000029280e0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x29280e0)
#18 0x0000000000766170 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#19 0x00000000006a7ce2 main (/opt/compiler-explorer/clang-trunk/bin/llc+0x6a7ce2)
#20 0x00007fda0515d083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#21 0x000000000075e0be _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x75e0be)
```

Similar to https://github.com/llvm/llvm-project/issues/53353 which was for x86_64

### PR DESCRIPTION
**Pull request by ecnelises**
According to langref, llvm.maximum/minimum has -0.0 < +0.0 semantics and propagates NaN.

Expand the nodes on targets not supporting the operation, by adding extra check for NaN and using is_fpclass to check zero signs.

Migrated from https://reviews.llvm.org/D158053

Fixes #64209

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 1]
```diff
@@ -8177,6 +8177,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
   return SDValue();
 }
 
+SDValue TargetLowering::expandFMINIMUM_FMAXIMUM(SDNode *N,
```
Comment (jayfoad) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8180]: Could you please add one or both of:
- some comments here showing what MIR is generated, and/or
- some MIR tests with -run-pass=legalizer showing the expansion with various combinations of fast math flags.

Comment (ecnelises) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8204]: Can MIR be valid input for legalizers? I see MIR outputs are all legalized.

Comment (jayfoad) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8204]: > Can MIR be valid input for legalizers?

No, sorry, please ignore that part. I was thinking about GlobalISel not SelectionDAG.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 2]
```diff
@@ -8201,6 +8201,66 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+  SDValue LHS = N->getOperand(0);
+  SDValue RHS = N->getOperand(1);
+  unsigned Opc = N->getOpcode();
+  EVT VT = N->getValueType(0);
+  EVT CCVT = getSetCCResultType(DAG.getDataLayout(), *DAG.getContext(), VT);
+  bool NoNaN = (N->getFlags().hasNoNaNs() ||
+                (DAG.isKnownNeverNaN(LHS) && DAG.isKnownNeverNaN(RHS)));
+  bool NoZeroSign =
+      (N->getFlags().hasNoSignedZeros() || DAG.isKnownNeverZeroFloat(LHS) ||
+       DAG.isKnownNeverZeroFloat(RHS));
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8216]: Can you defer these checks as late as possible?

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 3]
```diff
@@ -8201,6 +8201,66 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+  // First, implement comparison not propagating NaN. If no native fmin or fmax
+  // available, use plain select with setcc instead.
+  SDValue MinMax;
+  if (isOperationLegalOrCustom(IsMax ? ISD::FMAXNUM_IEEE : ISD::FMINNUM_IEEE,
+                               VT))
+    MinMax = DAG.getNode(IsMax ? ISD::FMAXNUM_IEEE : ISD::FMINNUM_IEEE, DL, VT,
+                         LHS, RHS);
+  else if (isOperationLegalOrCustom(IsMax ? ISD::FMAXNUM : ISD::FMINNUM, VT))
+    MinMax = DAG.getNode(IsMax ? ISD::FMAXNUM : ISD::FMINNUM, DL, VT, LHS, RHS);
+  else
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8232]: Braces

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 4]
```diff
@@ -8201,6 +8201,66 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+    MinMax = DAG.getSelect(
+        DL, VT,
+        DAG.getSetCC(DL, CCVT, LHS, RHS, IsMax ? ISD::SETGT : ISD::SETLT), LHS,
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8235]: Intermediate variable wouldn't hurt. Alternatively could use getSelectCC

**Comment by Artem-B** [comment]
What are the next steps needed to move this patch forward? 

It would be great if we could land it, as we already have real-world need for lowering fminimum/fmaximum on targets that do not have native support for it.

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 5]
```diff
@@ -523,9 +523,10 @@ RISCVTargetLowering::RISCVTargetLowering(const TargetMachine &TM,
     setOperationAction(ISD::FP_TO_FP16, MVT::f32, Custom);
     setOperationAction(ISD::FP16_TO_FP, MVT::f32, Custom);
 
-    if (Subtarget.hasStdExtZfa())
+    if (Subtarget.hasStdExtZfa()) {
       setOperationAction(ISD::FNEARBYINT, MVT::f32, Legal);
-    else
+      setOperationAction({ISD::FMAXIMUM, ISD::FMINIMUM}, MVT::f32, Legal);
+    } else
```
Comment (mshockwave) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:529]: style: please add curly braces here as well to match the if branch

**Review by mshockwave — APPROVED** [review]
LGTM. It will be great if you could add RISCV test too, but please don't let this block you.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 6]
```diff
@@ -8262,6 +8262,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+  if (isOperationLegalOrCustom(IsMax ? ISD::FMAXNUM_IEEE : ISD::FMINNUM_IEEE,
+                               VT)) {
+    MinMax = DAG.getNode(IsMax ? ISD::FMAXNUM_IEEE : ISD::FMINNUM_IEEE, DL, VT,
+                         LHS, RHS);
+  } else if (isOperationLegalOrCustom(IsMax ? ISD::FMAXNUM : ISD::FMINNUM,
+                                      VT)) {
+    MinMax = DAG.getNode(IsMax ? ISD::FMAXNUM : ISD::FMINNUM, DL, VT, LHS, RHS);
+  } else {
+    SDValue Compare =
+        DAG.getSetCC(DL, CCVT, LHS, RHS, IsMax ? ISD::SETGT : ISD::SETLT);
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8291]: SETGT/SETLT leave it up to the target whether it returns true or false for NaN. Is that intentional? If so it's probably worth a comment.

**Comment by topperc** [comment]
> LGTM. It will be great if you could add RISCV test too, but please don't let this block you.

RISC-V uses custom lowering. We should already have tests.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 7]
```diff
@@ -8262,6 +8262,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+  bool IsMax = Opc == ISD::FMAXIMUM;
+
+  if (VT.isVector() &&
+      isOperationLegalOrCustomOrPromote(Opc, VT.getScalarType()))
+    return SDValue();
+
+  // First, implement comparison not propagating NaN. If no native fmin or fmax
+  // available, use plain select with setcc instead.
+  SDValue MinMax;
+  if (isOperationLegalOrCustom(IsMax ? ISD::FMAXNUM_IEEE : ISD::FMINNUM_IEEE,
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8282]: (style) Pull out the IsMax? opcodes into separate lines to reduce duplication and line width

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 8]
```diff
@@ -8262,6 +8262,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+                                  DAG.getConstantFP(0.0, DL, VT), ISD::SETEQ);
+    SDValue TestZero =
+        DAG.getTargetConstant(IsMax ? fcPosZero : fcNegZero, DL, MVT::i32);
+    SDValue LCmp = DAG.getSelect(
+        DL, VT, DAG.getNode(ISD::IS_FPCLASS, DL, CCVT, LHS, TestZero), LHS,
+        MinMax);
+    SDValue RCmp = DAG.getSelect(
+        DL, VT, DAG.getNode(ISD::IS_FPCLASS, DL, CCVT, RHS, TestZero), RHS,
+        LCmp);
+    MinMax = DAG.getSelect(DL, VT, IsZero, RCmp, MinMax);
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8317]: random thought - can this be done better with FCOPYSIGN?

**Review by RKSimon — COMMENTED** [review]
Is there any existing vector test coverage? There don't seem to be any test changes for them.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 8 above)
Comment (ecnelises) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8365]: We still need isfpclass to know which is negative/positive zero and whether both are zeros, I think.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 6 above)
Comment (ecnelises) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8339]: Yes here it assumes no NaN exists (if either operand is NaN, it will be propagated in following code)

**Comment by ecnelises** [comment]
> Is there any existing vector test coverage?

Yes, there are vector tests in PowerPC's fminimum-fmaximum.ll.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 9]
```diff
@@ -8310,6 +8310,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+  } else {
+    // NaN (if exists) will be propagated later, so orderness doesn't matter.
+    SDValue Compare =
+        DAG.getSetCC(DL, CCVT, LHS, RHS, IsMax ? ISD::SETGT : ISD::SETLT);
+    MinMax = DAG.getSelect(DL, VT, Compare, LHS, RHS);
+  }
+
+  // Propagate any NaN of both operands
+  if (!N->getFlags().hasNoNaNs() &&
+      (!DAG.isKnownNeverNaN(LHS) || !DAG.isKnownNeverNaN(RHS))) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8345]: Should invert the order of these checks. RHS is canonically simpler / cheaper to inspect

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 10]
```diff
@@ -8310,6 +8310,64 @@ SDValue TargetLowering::expandFMINNUM_FMAXNUM(SDNode *Node,
...
+    ConstantFP *FPNaN = ConstantFP::get(
+        *DAG.getContext(), APFloat::getNaN(DAG.EVTToAPFloatSemantics(VT)));
+    MinMax = DAG.getSelect(DL, VT, DAG.getSetCC(DL, CCVT, LHS, RHS, ISD::SETUO),
+                           DAG.getConstantFP(*FPNaN, DL, VT), MinMax);
+  }
+
+  // fminimum/fmaximum requires -0.0 less than +0.0
+  if (!N->getFlags().hasNoSignedZeros() && !DAG.isKnownNeverZeroFloat(LHS) &&
+      !DAG.isKnownNeverZeroFloat(RHS)) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8354]: Ditto, check RHS first

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 8 above)
Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8365]: I think we should try to avoid using is_fpclass here. Additionally, I think we have under-defined the internally used IEEE nodes. As currently defined, minnum_ieee/maxnum_ieee have unspecified signed 0 order. However for AMDGPU at least, the actual hardware instructions have always appropriately ordered 0s. We could either refine the _IEEE node definitions to be IEEE -2019 and require ordered 0 behavior which doesn't require this fixup.

Comment (ecnelises) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8365]: PowerPC implements `fmaxnum_ieee` into `xsmaxdp` which repsects zero signs. I did not see AMDGPU backend implements it.

While LoongArch (using `fmax.d`) ISA just says _following the specification of maxNum(x,y) operation in the IEEE 754-2008 standard_. I think it's unspecified. (maybe @llvm/pr-subscribers-loongarch )

**Comment by jayfoad** [comment]
Reverse ping! Are you still working on this?

**Comment by ecnelises** [comment]
> Reverse ping! Are you still working on this?

Sure! Any comments I missed?

**Comment by krzysz00** [comment]
Ping (as someone who's been carrying around a backport of this patch for a few months now)

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 8 above)
Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8378]: I opened #85195 to just fix the definitions here. If LoongArch doesn't behave correctly, we can lower it to preserve the sign there

**Comment by arsenm** [comment]
> > Reverse ping! Are you still working on this?
> 
> Sure! Any comments I missed?

I still think we should avoid using is_fpclass here

**Comment by ecnelises** [comment]
> I still think we should avoid using is_fpclass here

`fgetsign` is not legal or expanded in every targets. To support comparison of signed zeros, should we duplicate similar logic of is_fpclass expansion? (bitcast them to int and do int comparison)

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 8 above)
Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:8421]: #85195 is landed, so we should just assume the _IEEE flavors preserve the sign

**Review by arsenm — APPROVED** [review]
I will need this shortly, so will be adding AMDGPU tests and will investigate avoiding is_fpclass
