### PR TITLE
Suppress printing lambda body for constexpr diagnostics

### LINKED ISSUE #125914: Entire lambda body is printed in a note
Consider the following example (https://godbolt.org/z/P7dqa81bG):
```cpp
class S {
  class Incomplete;

  struct Inner {
    consteval void fn() {
      Incomplete i;
    }
  };

  static constexpr int r = [] {
    Inner{}.fn();
    return 0;
  }();

  class Incomplete {};
};
```
We issue the following diagnostics for it:
```
<source>:10:28: error: call to immediate function 'S::(anonymous class)::operator()' is not a constant expression
   10 |   static constexpr int r = [] {
      |                            ^
<source>:11:13: note: undefined function 'fn' cannot be used in a constant expression
   11 |     Inner{}.fn();
      |             ^
<source>:10:28: note: in call to '[] {
    Inner{}.fn();
    return 0;
}.operator()()'
   10 |   static constexpr int r = [] {
      |                            ^~~~
   11 |     Inner{}.fn();
      |     ~~~~~~~~~~~~~
   12 |     return 0;
      |     ~~~~~~~~~
   13 |   }();
      |   ~~~
<source>:5:20: note: declared here
    5 |     consteval void fn() {
      |                    ^
<source>:10:24: error: constexpr variable 'r' must be initialized by a constant expression
   10 |   static constexpr int r = [] {
      |                        ^   ~~~~
   11 |     Inner{}.fn();
      |     ~~~~~~~~~~~~~
   12 |     return 0;
      |     ~~~~~~~~~
   13 |   }();
      |   ~~~
<source>:11:13: note: undefined function 'fn' cannot be used in a constant expression
   11 |     Inner{}.fn();
      |             ^
<source>:10:28: note: in call to '[] {
    Inner{}.fn();
    return 0;
}.operator()()'
   10 |   static constexpr int r = [] {
      |                            ^~~~
   11 |     Inner{}.fn();
      |     ~~~~~~~~~~~~~
   12 |     return 0;
      |     ~~~~~~~~~
   13 |   }();
      |   ~~~
<source>:5:20: note: declared here
    5 |     consteval void fn() {
      |                    ^
2 errors generated.
```
It seems unfortunate that multi-line lambda body gets printed in the `in call to` note.

### PR DESCRIPTION
**Pull request by shermpay**
closes #125914

Introduce `SupressLambdaBody` `PrintingPolicy` that is used only for constexpr diagnostics. This ensures `--print-ast` still works the same. I also considered other approaches such as modifying the `PrintingPolicy` in the current `AstContext`, but that might cause unexpected changes. 

Add two tests:
1. To ast-printer-lambda to ensure `--print-ast` works the same.
2. Ensure lambda body is not printed for constexpr diagnostics.

### CODE REVIEW

File: clang/test/AST/constexpr-lambda-diagnostic.cpp [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -fsyntax-only -std=c++17 -verify=expected %s
```
Comment (Fznamznon) [inline clang/test/AST/constexpr-lambda-diagnostic.cpp]: Can we also test the new constexpr interpreter, i.e
```suggestion
// RUN: %clang_cc1 -triple x86_64-linux-gnu -fsyntax-only -std=c++17 -verify=expected %s 
// RUN: %clang_cc1 -triple x86_64-linux-gnu -fsyntax-only -std=c++17 -verify=expected %s -fexperimental-new-constant-interpreter
```

**Review by Fznamznon — COMMENTED** [review]
This is neat, but I'm not sure about an additional printing policy flag just for one case.
We also need to fix the new constant interpreter if it doesn't share the affected code with the old one.
Also, maybe a release note makes sense

File: clang/test/AST/constexpr-lambda-diagnostic.cpp (hunk 1 above)
Comment (shermpay) [reply clang/test/AST/constexpr-lambda-diagnostic.cpp]: Thanks for pointing this out! I updated the code to support the new constexpr interpreter and included this as a test case.

**Review by cor3ntin — APPROVED** [review]
LGTM - but more tests would be useful. Thanks

**Comment by shermpay** [comment]
I have squashed the commits into a single commit via fixups. I think this is ready for submission. PTAL.

Thanks all!

**Comment by cor3ntin** [comment]
> I have squashed the commits into a single commit via fixups. I think this is ready for submission. PTAL.

For future reference, this is actually undesirable as it messes up with Github. Once a PR lands, we merge with squash 
(and the pr description becomes the commit message)

**Review by cor3ntin — APPROVED** [review]
LGTM - Do you need us to merge that for you? Thanks

**Comment by shermpay** [comment]
> > I have squashed the commits into a single commit via fixups. I think this is ready for submission. PTAL.
> 
> For future reference, this is actually undesirable as it messes up with Github. Once a PR lands, we merge with squash (and the pr description becomes the commit message)

I see. I got the impression that was the preferred method from https://llvm.org/docs/GitHub.html#landing-your-change

> [Interactive rebase](https://git-scm.com/docs/git-rebase#_interactive_mode) with fixups. This is the recommended method since you can control the final commit message and check that the final commit looks as you expect. When your local state is correct, remember to force-push to your branch and press the merge button in GitHub’s web interface afterwards.

Maybe the documentation is outdated? Anyways, I'll keep this in mind for future PRs, thanks!

**Comment by shermpay** [comment]
> LGTM - Do you need us to merge that for you? Thanks

Yes please, thanks in advance!
