### PR TITLE
[lld][WebAssembly] Avoid emitting empty __wasm_apply_data_relocs function

### LINKED ISSUE #107387: [WebAssembly] non-pie dynamic-linking executable seems broken (LLVM 19 regression)
build the following test code as a non-pie dynamically-linked executable.
llvm 19 produces non-working binary.
llvm 18 worked fine.
you can find the full test code and compiler/linker options in https://github.com/yamt/garbage/tree/master/c/shlib_2

```c
void f(void);
void (*f_p)(void) = f;

void
_start(void)
{
                f_p();
}
```

```shell
spacetanuki% toywasm --dyld main
Error: [trap] uninitialized element (8): call_indirect (null funcref) 0
current pc 0000fd
frame[  0] funcpc 0000e2 (main:_start)
2024-09-05 20:43:42 (1725536622.157386000): [10fb06600] instance_execute_func failed with -1
2024-09-05 20:43:42 (1725536622.157883000): [10fb06600] invoke failed with -1
spacetanuki% 
```

note that llvm 19's __wasm_apply_data_relocs is empty.

llvm 19.1.0-rc4
```
(module $main
  (type (;0;) (func))
  (import "env" "f" (func $f (type 0)))
  (func $__wasm_apply_data_relocs (type 0))
  (func $_start (type 0)
    global.get $GOT.data.internal.__memory_base
    i32.const 1024
    i32.add
    i32.load
    call_indirect (type 0))
  (table (;0;) 1 funcref)
  (memory (;0;) 2)
  (global $__stack_pointer (mut i32) (i32.const 66576))
  (global $GOT.data.internal.__memory_base i32 (i32.const 0))
  (global (;2;) i32 (i32.const 66576))
  (global (;3;) i32 (i32.const 131072))
  (export "memory" (memory 0))
  (export "__stack_pointer" (global $__stack_pointer))
  (export "__wasm_apply_data_relocs" (func $__wasm_apply_data_relocs))
  (export "_start" (func $_start))
  (export "__indirect_function_table" (table 0))
  (export "__heap_base" (global 2))
  (export "__heap_end" (global 3))
  (data $.data (i32.const 1024) "\00\00\00\00"))
```

llvm 18.1.2
```
(module $main
  (type (;0;) (func))
  (import "env" "f" (func $f (type 0)))
  (import "GOT.func" "f" (global $f (mut i32)))
  (func $__wasm_apply_data_relocs (type 0)
    i32.const 1024
    global.get $f
    i32.store)
  (func $_start (type 0)
    global.get $GOT.data.internal.__memory_base
    i32.const 1024
    i32.add
    i32.load
    call_indirect (type 0))
  (table (;0;) 1 funcref)
  (memory (;0;) 2)
  (global $__stack_pointer (mut i32) (i32.const 66576))
  (global $GOT.data.internal.__memory_base i32 (i32.const 0))
  (global (;3;) i32 (i32.const 66576))
  (global (;4;) i32 (i32.const 131072))
  (export "memory" (memory 0))
  (export "__stack_pointer" (global $__stack_pointer))
  (export "__wasm_apply_data_relocs" (func $__wasm_apply_data_relocs))
  (export "_start" (func $_start))
  (export "__indirect_function_table" (table 0))
  (export "__heap_base" (global 3))
  (export "__heap_end" (global 4))
  (data $.data (i32.const 1024) "\00\00\00\00"))
```

### PR DESCRIPTION
**Pull request by yamt**
Instead of always generating __wasm_apply_data_relocs when relevant options like -pie and -shared are specified, generate it only when the relevant relocations are actually necessary.

Note: omitting empty __wasm_apply_data_relocs is not a problem because the export is optional in the spec (DynamicLinking.md) and all runtime linker implementations I'm aware of implement it that way.  (emscripten, toywasm, wasm-tools)

Motivations:

* This possibly reduces the module size

* This is also a preparation to fix https://github.com/llvm/llvm-project/issues/107387, for which it isn't obvious if we need these relocations at the time of createSyntheticSymbols. (unless we introduce a new explicit option like --non-pie-dynamic-link.)

### CODE REVIEW

File: lld/wasm/InputChunks.cpp [hunk 1]
```diff
@@ -378,7 +378,7 @@ void InputChunk::generateRelocationCode(raw_ostream &os) const {
     uint64_t offset = getVA(rel.Offset) - getInputSectionOffset();
 
     Symbol *sym = file->getSymbol(rel);
-    if (!ctx.isPic && sym->isDefined())
+    if (!ctx.isPic && !sym->hasGOTIndex())
```
Comment (sbc100) [inline lld/wasm/InputChunks.cpp:381]: Is this change needed as part of this change?   I think this line could probably use a comment.   i.e. Why are we skipping these relocations?

File: lld/wasm/Writer.cpp [hunk 2]
```diff
@@ -1467,15 +1469,29 @@ void Writer::createApplyDataRelocationsFunction() {
   {
     raw_string_ostream os(bodyContent);
     writeUleb128(os, 0, "num locals");
+    uint64_t off = os.tell();
     for (const OutputSegment *seg : segments)
       if (!config->sharedMemory || !seg->isTLS())
         for (const InputChunk *inSeg : seg->inputSegments)
           inSeg->generateRelocationCode(os);
```
Comment (sbc100) [inline lld/wasm/Writer.cpp:1476]: Would it be cleaner to return a boolean from `generateRelocationCode`? 

i.e.

```
wroteRelocations |= inSeg->generateRelocationCode(os);
...
if (!wroteRelocations) {
  return;
}
```

Not a big deal but it seems more explictly/obvious.

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
How about making the title `[lld]WebAssembly] Avoid emitting empty __wasm_apply_data_relocs function`?

**Comment by sbc100** [comment]
I'm still not clear about the second motivation.  i.e. I'm not clear on why this is needed for the followup change.  But I'll see if I can figure it out.

File: lld/wasm/InputChunks.cpp (hunk 1 above)
Comment (sbc100) [reply lld/wasm/InputChunks.cpp:381]: Should this change be differed to #108146 since it seems like a separate semantic change perhaps?

Comment (yamt) [reply lld/wasm/InputChunks.cpp:382]: this change is necessary because this function is now called regardless of unresolved policy.

File: lld/wasm/Writer.cpp (hunk 2 above)
Comment (yamt) [reply lld/wasm/Writer.cpp]: done

**Comment by yamt** [comment]
> How about making the title `[lld]WebAssembly] Avoid emitting empty __wasm_apply_data_relocs function`?

done

File: lld/wasm/InputChunks.cpp (hunk 1 above)
Comment (sbc100) [reply lld/wasm/InputChunks.cpp:382]: I'm finding this clauses a little hard to grok without a lot of introspection.

Maybe we could add a comment here?  Something like:

`// Runtime relocations are needed when we don't know the address of a symbol statically.`

Or better still, we could add a variable to make it more clear what is going on:

```
bool requiresRuntimeReloc = ctx.isPic || sym->hasGOTIndex();
if (!requiresRuntimeReloc)
   continue;
```

Comment (yamt) [reply lld/wasm/InputChunks.cpp]: > I'm finding this clauses a little hard to grok without a lot of introspection.

i agree!

> Maybe we could add a comment here? Something like:
> 
> `// Runtime relocations are needed when we don't know the address of a symbol statically.`
> 
> Or better still, we could add a variable to make it more clear what is going on:
> 
> ```
> bool requiresRuntimeReloc = ctx.isPic || sym->hasGOTIndex();
> if (!requiresRuntimeReloc)
>    continue;
> ```

applied. thank you.

**Review by sbc100 — APPROVED** [review]

**Comment by yamt** [comment]
can this land?
