### PR TITLE
[analyzer] Do list initialization for CXXNewExpr with initializer list arg

### LINKED ISSUE #116444: clang-static-analyzer: Aggregate-initialized struct field incorrectly marked undefined
This code:

```cpp
#include <iostream>
#include <string>

struct Structy {
  std::string foo;
  int bar;
};

int main() {
  auto *s = new Structy{
      .foo = "foo",
      .bar = 1,
  };
  std::cout << s->foo << s->bar;
  delete s;
}
```

produces the following static analyzer warning:

```
$ clang-tidy -p . qq.cpp 
1 warning generated.
/home/rojer/allterco/shelly-ng3/qq.cpp:14:3: error: 1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage,-warnings-as-errors]
   14 |   std::cout << s->foo << s->bar;
      |   ^                      ~~~~~~
/home/rojer/allterco/shelly-ng3/qq.cpp:10:13: note: Uninitialized value stored to field 'bar'
   10 |   auto *s = new Structy{
      |             ^~~~~~~~~~~~
   11 |       .foo = "foo",
      |       ~~~~~~~~~~~~~
   12 |       .bar = 1,
      |       ~~~~~~~~~
   13 |   };
      |   ~
/home/rojer/allterco/shelly-ng3/qq.cpp:14:3: note: 1st function call argument is an uninitialized value
   14 |   std::cout << s->foo << s->bar;
      |   ^                      ~~~~~~
1 warning treated as error
```

`s->bar` is of course explicitly initialized to 1, so the generated warning is a false-positive.

swapping field order to bar, foo makes it go away.

tested with latest main (20.0.0git ec353b7418e272e96cd63cc61bec586ab49da92f).

### PR DESCRIPTION
**Pull request by ashfordium**
Fixes #116444.

Closed #127700 because I accidentally updated it in github UI.

### Current vs expected behavior

Previously, the result of a `CXXNewExpr` was not always list initialized when using an initializer list. 

In this example:
```
struct S { int x; };
void F() {
  S *s = new S{1};
  delete s;
}
```
there would be a binding of `s` to `compoundVal{1}`, but this isn't used during later field binding lookup. After this PR, there is instead a binding of `s->x` to `1`. This is the cause of #116444 since the field binding lookup returns undefined in some cases currently.

### Changes

This PR swaps around the handling of typed value regions (seems to be the usual region type when doing non-CXX-new-expr list initialization) and symbolic regions (the result of the CXX new expr), so that symbolic regions also get list initialized. In the below snippet, it swaps the order of the two conditionals.
https://github.com/llvm/llvm-project/blob/8529bd7b964cc9fafe8fece84f7bd12dacb09560/clang/lib/StaticAnalyzer/Core/RegionStore.cpp#L2426-L2448

### Followup work

This PR only makes CSA do list init for `CXXNewExpr`s. After this, I would like to make some changes to `RegionStoreMananger::bind` in how it handles list initialization generally.

I've added some straightforward test cases here for the `new` expr with a list initializer. I started adding some more before realizing that the current general (not just `new` expr) list initialization could be changed to handle more cases like list initialization of unions and arrays (like https://github.com/llvm/llvm-project/issues/54910). Lmk if it is preferred to then leave these test cases out for now.

### CODE REVIEW

**Review by Xazax-hun — APPROVED** [review]
This change looks good to me but the code makes me wonder if we correctly handle placement new.

What about cases like doing placement new into a non-zero'th element of a region like:
```
void f(S *a[]) {
  s[1] = new (S[1]) S{1, 2};
}
```

If this works as expected, that is great! If it does not, I am OK doing something about it in a follow-up PR.

**Review by steakhal — APPROVED** [review]
I checked the meat of this PR, and spot checked the tests. Everything looked excellent so far.

Many thanks for the PR!

File: clang/test/Analysis/initializer.cpp [hunk 1]
```diff
@@ -254,6 +254,200 @@ void foo() {
...
+}
+
+enum Enum : int {
+};
+// FIXME: uncomment when CSA supports list init of enums
+void list_init_enum() {
+  // Enum *E = new Enum{53};
+  // clang_analyzer_eval(53 == *E); // should be TRUE
+  // delete E;
+}
```
Comment (steakhal) [inline clang/test/Analysis/initializer.cpp:340]: What do you mean by "CSA supports list inits of enums"?
When I checked, it reports TRUE: https://compiler-explorer.com/z/f5G18jbv4

File: clang/test/Analysis/new-user-defined.cpp [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+// RUN:   -analyzer-checker=core\
+// RUN:   -analyzer-checker=debug.ExprInspection -std=c++17
+// RUN: %clang_analyze_cc1 -w -verify %s\
+// RUN:   -analyzer-checker=core\
+// RUN:   -analyzer-checker=debug.ExprInspection -std=c++11\
+// RUN:   -DTEST_INLINABLE_ALLOCATORS
+// RUN: %clang_analyze_cc1 -w -verify %s\
+// RUN:   -analyzer-checker=core\
+// RUN:   -analyzer-checker=debug.ExprInspection -std=c++17\
+// RUN:   -DTEST_INLINABLE_ALLOCATORS
```
Comment (steakhal) [inline clang/test/Analysis/new-user-defined.cpp:11]: In the RUN lines you sometimes define the `TEST_INLINABLE_ALLOCATORS` macro, but that is never spelled elsewhere, nor we include a header that would use it.

Are you sure all these RUN lines are necessary? Is it leftover from some copy-paste?

File: clang/test/Analysis/new-user-defined.cpp [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+
+  S *s2 = new S{};
+  clang_analyzer_eval(0 == s2->x); // expected-warning{{TRUE}}
+
+  S *s3 = new S{1};
+  clang_analyzer_eval(1 == s3->x); // expected-warning{{TRUE}}
+}
+
+struct WithPlacementNew {
+};
```
Comment (steakhal) [inline clang/test/Analysis/new-user-defined.cpp:36]: What is the purpose of this unused struct?

File: clang/test/Analysis/new-user-defined.cpp [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+// RUN:   -analyzer-checker=debug.ExprInspection -std=c++11\
+// RUN:   -DTEST_INLINABLE_ALLOCATORS
+// RUN: %clang_analyze_cc1 -w -verify %s\
+// RUN:   -analyzer-checker=core\
+// RUN:   -analyzer-checker=debug.ExprInspection -std=c++17\
+// RUN:   -DTEST_INLINABLE_ALLOCATORS
+
+void clang_analyzer_eval(bool);
+
+typedef __typeof(sizeof(int)) size_t;
```
Comment (steakhal) [inline clang/test/Analysis/new-user-defined.cpp:15]: In C++, you can use decltype and using aliases.
```suggestion
using size_t = decltype(sizeof(int));
```

File: clang/test/Analysis/initializer.cpp [hunk 5]
```diff
@@ -254,6 +254,200 @@ void foo() {
...
+  clang_analyzer_eval(3 == N7->baz); // expected-warning{{TRUE}}
+
+  delete N;
+  delete N1;
+  delete N2;
+  delete N3;
+  delete N4;
+  delete N5;
+  delete N6;
+  delete N7;
```
Comment (steakhal) [inline clang/test/Analysis/initializer.cpp:447]: If you are bored of spelling all the deletes, you could declare a `void escape(...);` function and just pass these pointers to a call to it here. That would suppress the leak diags because the addresses would escape.

**Review by steakhal — CHANGES_REQUESTED** [review]
I was about to merge this, and I as usual, had a quick sweep before pushing the button.
Unfortunately, I found some subjects to discuss inline.

File: clang/test/Analysis/initializer.cpp [hunk 6]
```diff
@@ -254,6 +254,198 @@ void foo() {
...
+  clang_analyzer_eval(1 == S->i); // expected-warning{{TRUE}}
+  clang_analyzer_eval(2 == S->j); // expected-warning{{TRUE}}
+  clang_analyzer_eval(3 == S->k); // expected-warning{{TRUE}}
+  delete S;
+}
+
+#if __cplusplus >= 201703L
+enum Enum : int {
+};
+// FIXME: uncomment when CSA supports list init of enums
```
Comment (steakhal) [inline clang/test/Analysis/initializer.cpp:339]: Isn't this FIXME stale now?

**Review by steakhal — COMMENTED** [review]
Can we merge this now?

**Review by steakhal — COMMENTED** [review]
Technically, shouldn't one only use the return value of the placement new? Using the original object is technically UB (I know we accept it, and do the right thing, but anyways) maybe we should have a test demonstrating theat it would work with the ret val of placement new too.

File: clang/test/Analysis/new-user-defined.cpp [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+namespace CustomClassType {
+struct S {
+  int x;
+  static void* operator new(size_t size) {
+    return ::operator new(size);
+  }
+};
+void F() {
+  S *s = new S;
+  clang_analyzer_eval(s->x); // expected-warning{{UNKNOWN}} FIXME: should be an undefined warning
```
Comment (steakhal) [inline clang/test/Analysis/new-user-defined.cpp:20]: Why is this Undef? Do you plan to look into it?

File: clang/test/Analysis/initializer.cpp [hunk 8]
```diff
@@ -254,6 +254,224 @@ void foo() {
 }
 } // namespace CXX17_aggregate_construction
 
+namespace newexpr_init_list_initialization {
```
Comment (steakhal) [inline clang/test/Analysis/initializer.cpp:257]: btw why do we need NewExprs for these? Would the same initialization rules apply for regular variables with automatic storage-duration?

**Review by steakhal — APPROVED** [review]
I left a couple comments to discuss after I merge this PR.
It's good enough to be closed.

**Comment by steakhal** [comment]
Can I merge this @Flandini now?

File: clang/test/Analysis/new-user-defined.cpp (hunk 7 above)
Comment (steakhal) [reply clang/test/Analysis/new-user-defined.cpp:20]: Ah, yes. You are right. All good.
