### PR TITLE
[lldb] Restore register state if PrepareTrivialCall fails

### LINKED ISSUE #124269: lldb - Registers are not restored if PrepareTrivialCall fails
In this example I have bodged the function to return false after writing the argument registers all to `99`:
```
(lldb) run
Process 3666152 launched: '/tmp/test.o' (aarch64)
Process 3666152 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x0000aaaaaaaaa72c test.o`main at test.c:4:10
   1    int bar(int a) { return a*2; }
   2
   3    int main() {
-> 4      return 0;
   5    }
(lldb) register read --all
General Purpose Registers:
        x0 = 0x0000000000000001
        x1 = 0x0000fffffffff3a8
        x2 = 0x0000fffffffff3b8
        x3 = 0x0000aaaaaaaaa72c  test.o`main at test.c:4:10
        x4 = 0x0000000000000000
        x5 = 0x209f561e2fa866d7
        x6 = 0x0000fffff7facc90  libc.so.6`initial
        x7 = 0x0000004554415649

(lldb) p bar(1)

error: Can't evaluate the expression without a running target due to: Interpreter doesn't handle one of the expression's opcodes
```
Here we should have restored the original values, but:
```
(lldb) register read --all
General Purpose Registers:
        x0 = 0x0000000000000063
        x1 = 0x0000000000000063
        x2 = 0x0000000000000063
        x3 = 0x0000000000000063
        x4 = 0x0000000000000063
        x5 = 0x0000000000000063
```
We did not.

This is 99.9% of the time not a problem as preparing a trivial call does trivial things, but in adding Arm GCS support I had to handle the failure path and found this.

For that, I'm going to handle the one case I need, but I will come back and try to make LLDB restore everything properly.

### PR DESCRIPTION
**Pull request by DavidSpickett**
Fixes #124269

PrepareTrivalCall always had the possibility of failing, but given that it only wrote to general purpose registers, if it did, you had bigger problems.

When it failed, we did not mark the thread plan valid and when it was torn down we didn't try to restore the register state. This meant that if you tried to continue, the program was unlikely to work.

When I added AArch64 GCS support, I needed to handle the situation where the GCS pointer points to unmapped memory and we fail to write the extra entry we need. So I added code to restore the gcspr_el0 register specifically if this happened, and ordered the operations so that we tried this first.

In this change I've made the teardown of an invalid thread plan restore the register state if one was saved. It may be there isn't one if ConstructorSetup fails, but this is ok because that function does not modify anything.

Now that we're doing that, I don't need the GCS specific code anymore, and all thread plans are protected from this in the rare event something does fail.

Testing is done by the existing GCS test case that points the gcspr into unmapped memory which causes PrepareTrivialCall to fail. I tried adding a simulated test using a mock gdb server. This was not possible because they all use DynamicLoaderStatic which disables all JIT features.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Existing GCS test case is here - https://github.com/llvm/llvm-project/blob/f6262fa035d8b942bf76e084fa875409bc8ff83a/lldb/test/API/linux/aarch64/gcs/TestAArch64LinuxGCS.py#L286

These don't run on bots yet, only Arm's simulator.

**Comment by DavidSpickett** [comment]
Our policy for the GCS registers is documented here - https://lldb.llvm.org/use/aarch64-linux.html#id3 - but for the GCS enable bit, we restore all of them after an expression.

File: lldb/source/Plugins/ABI/AArch64/ABISysV_arm64.cpp [hunk 1]
```diff
@@ -102,12 +102,7 @@ static Status PushToLinuxGuardedControlStack(addr_t return_addr,
   size_t wrote = thread.GetProcess()->WriteMemory(gcspr_el0, &return_addr,
                                                   sizeof(return_addr), error);
   if ((wrote != sizeof(return_addr) || error.Fail())) {
-    // When PrepareTrivialCall fails, the register context is not restored,
-    // unlike when an expression fails to execute. This is arguably a bug,
-    // see https://github.com/llvm/llvm-project/issues/124269.
-    // For now we are handling this here specifically. We can assume this
-    // write will work as the one to decrement the register did.
-    reg_ctx->WriteRegisterFromUnsigned(gcspr_el0_info, gcspr_el0 + 8);
+    // gcspr_el0 will be restored when the ThreadPlan is destroyed.
```
Comment (jimingham) [inline lldb/source/Plugins/ABI/AArch64/ABISysV_arm64.cpp:105]: Not terribly important, but DoTakedown often gets called before the ThreadPlan is actually destroyed, and that's what does this job.

**Review by jimingham — APPROVED** [review]
LGTM

File: lldb/source/Plugins/ABI/AArch64/ABISysV_arm64.cpp (hunk 1 above)
Comment (DavidSpickett) [reply lldb/source/Plugins/ABI/AArch64/ABISysV_arm64.cpp]: Fixed.
