### PR TITLE
[Clang] Correctly initialize placeholder fields from their initializers

### LINKED ISSUE #114069: [clang] Class fields with placeholder names cause incorrect instantiation of in-class initializers
MRE : 

https://godbolt.org/z/Mjdnz8G31

```cpp
#include <cassert>

template <class T>
struct A {
    T _ = 5;
    T _ = 4;
};

int main() {
    A<int> a;
    auto [x, y] = a;
    assert( y == 4 );
}
```

`assert( y == 4 )` fails because Clang finds the in-class init pattern like this (in Sema::BuildCXXDefaultInitExpr) : 

```cpp
CXXRecordDecl *ClassPattern = ParentRD->getTemplateInstantiationPattern();
DeclContext::lookup_result Lookup = ClassPattern->lookup(Field->getDeclName());

FieldDecl *Pattern = nullptr;
for (auto *L : Lookup) {
  if ((Pattern = dyn_cast<FieldDecl>(L)))
    break;
}
```

Obviously this cannot works with `_`. I think to remedy this imply keeping track of the pattern of an instantiated field with a placeholder name in some auxiliary structure? The entry would only need to be temporary until its consumed by Sema::BuildCXXDefaultInitExpr. 

Also I think a warning should be emitted that we're using a C++26 feature before its time?

### PR DESCRIPTION
**Pull request by cor3ntin**
We made the incorrect assumption that names of fields are unique when creating their default initializers.

We fix that by keeping track of the instantiaation pattern for field decls that are placeholder vars,
like we already do for unamed fields.

Fixes #114069

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -5560,6 +5560,27 @@ ExprResult Sema::BuildCXXDefaultArgExpr(SourceLocation CallLoc,
...
+  if (FieldDecl *Pattern = Ctx.getInstantiatedFromUnnamedFieldDecl(Field))
+    return Pattern;
+  auto *ParentRD = cast<CXXRecordDecl>(Field->getParent());
+  CXXRecordDecl *ClassPattern = ParentRD->getTemplateInstantiationPattern();
+  DeclContext::lookup_result Lookup =
+      ClassPattern->lookup(Field->getDeclName());
+  FieldDecl *Found = nullptr;
+  for (auto *L : Lookup) {
+    if (FieldDecl *Pattern = dyn_cast<FieldDecl>(L)) {
+      assert(!Found && "Duplicated instantiation pattern for field decl");
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp:5574]: This is probably better as a `llvm::make_filter_range`, or a llvm::find_if, either with `llvm::IsaPred<FieldDecl>`.

Also makes your "ensure we only find one" a little less odd looking, since you could do something like:
`assert(++Itr == range.end())` kinda thing.

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -5560,6 +5560,25 @@ ExprResult Sema::BuildCXXDefaultArgExpr(SourceLocation CallLoc,
...
 
+static FieldDecl *FindFieldDeclInstantiationPattern(const ASTContext &Ctx,
+                                                    FieldDecl *Field) {
+  if (FieldDecl *Pattern = Ctx.getInstantiatedFromUnnamedFieldDecl(Field))
+    return Pattern;
+  auto *ParentRD = cast<CXXRecordDecl>(Field->getParent());
+  CXXRecordDecl *ClassPattern = ParentRD->getTemplateInstantiationPattern();
+  DeclContext::lookup_result Lookup =
+      ClassPattern->lookup(Field->getDeclName());
+  auto Rng = llvm::make_filter_range(Lookup, [] (auto && L) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp:5571]:
```suggestion
  auto Rng = llvm::make_filter_range(Lookup, llvm::IsaPred<FieldDecl>);
```

File: clang/lib/Sema/SemaExpr.cpp [hunk 3]
```diff
@@ -5560,6 +5560,25 @@ ExprResult Sema::BuildCXXDefaultArgExpr(SourceLocation CallLoc,
...
+      return isa<FieldDecl>(*L);
+  });
+  // FIXME: this breaks clang/test/Modules/pr28812.cpp
+  // assert(std::distance(Rng.begin(), Rng.end()) <= 1
+  //       && "Duplicated instantiation pattern for field decl");
+  if(Rng.empty())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp:5577]: As a nit, the assert/fixme probably should go above the `empty` check.

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaExpr.cpp (hunk 3 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaExpr.cpp:5577]: I don't understand, can you clarify?

Comment (erichkeane) [reply clang/lib/Sema/SemaExpr.cpp:5577]: woops, I meant 'below'.  Basically, just move 5577 to above 5574.  Sorry about that :/

Basically, doing the `std::distance` check (when we re-enable it) before checking for `empty` seems silly.
