### PR TITLE
[WebAssembly] Handle block and polymorphic stack in AsmTypeCheck

### LINKED ISSUE #107524: [WebAssembly] AsmTypeCheck does not handle block return values of unreachable block end
`AsmTypeCheck` does not handle block/loop's concrete return values when their end is not reachable, for example,
```s
block i32
i32.const 0
br 0
end
```
This is a valid wasm program but does not pass `AsmTypeCheck`.

Currently Wasm backend does not generate `block`/`loop` return types, but one exception is, the ones generated by `WebAssemblyCFGStackify::fixEndsAtEndOfFunction`:
https://github.com/llvm/llvm-project/blob/093b8bfe6b64c916647ae64af8066df22bb6ea65/llvm/lib/Target/WebAssembly/WebAssemblyCFGStackify.cpp#L1460-L1520

An example program that would generate this case is
```ll
;; test.ll
target triple = "wasm32-unknown-unknown"

define i32 @loop_i32() {
entry:
  br label %header
header:
  br label %header
}
```
which generates
```s
loop i32
br 0
end
```

The reproducing commands:
```console
$ llc test.ll
$ llvm-mc -triple=wasm32-unknown-unknown test.s
```

The error will be
```s
...
        loop            i32                             # label0:
        br              0                               # 0: up to label0
.LBB0_2:
b.s:15:2: error: end: insufficient values on the type stack
        end_loop
        ^
        end_function
...
```

### PR DESCRIPTION
**Pull request by aheejin**
This makes the type checker handle blocks with input parameters and return types, branches, and polymorphic stacks correctly.

We maintain the stack of "block info", which contains its input parameter type, return type, and whether it is a loop or not. And this is used when checking the validity of the value stack at the `end` marker and all branches targeting the block.

`StackType` now supports a new variant `Polymorphic`, which indicates the stack is in the polymorphic state. `Polymorphic`s are not popped even when `popType` is executed; they are only popped when the current block ends.

When popping from the value stack, we ensure we don't pop more than we are allowed to at the given block level and print appropriate error messages instead. Also after a block ends, the value stack is guaranteed to have the right types based on the block return type. For example,
```wast
block i32
  unreachable
end_block
;; You can expect to have an i32 on the stack here
```

This also adds handling for `br_if`. Previously only `br`s were checked.

`checkEnd` and `checkBr` were removed and their contents have been inlined to the main `typeCheck` function, because they are called only from a single callsite.

This also fixes two existing bugs in AsmParser, which were required to make the tests passing. I added Github comments about them inline.

This modifies several existing invalid tests, those that passed (incorrectly) before but do not pass with the new type checker anymore.

Fixes #107524.

### CODE REVIEW

File: llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp [hunk 1]
```diff
@@ -498,7 +498,9 @@ class WebAssemblyAsmParser final : public MCTargetAsmParser {
 
   void addBlockTypeOperand(OperandVector &Operands, SMLoc NameLoc,
                            WebAssembly::BlockType BT) {
-    if (BT != WebAssembly::BlockType::Void) {
+    if (BT == WebAssembly::BlockType::Void) {
+      TC.setLastSig(wasm::WasmSignature{});
+    } else {
```
Comment (aheejin) [inline llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp:503]: Before, when we have a non-void block we set the signature in the type checker, but not when we have a void block. So if we have a non-void block and then a void block, the type checker incorrectly thought void block's signature was the same as the previous (non-void ) one.

File: llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp [hunk 2]
```diff
@@ -1002,7 +1004,8 @@ class WebAssemblyAsmParser final : public MCTargetAsmParser {
       auto *Signature = Ctx.createWasmSignature();
       if (parseSignature(Signature))
         return ParseStatus::Failure;
-      TC.funcDecl(*Signature);
+      if (CurrentState == FunctionStart)
+        TC.funcDecl(*Signature);
```
Comment (aheejin) [inline llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp:1008]: `.functype` directive does not only happen at the start of a function but also just to declare a function type that does not have a definition associated with it. But we used to set the current function's signature whenever we parsed a `.functype`. This resulted (incorrectly) in calling `funcDecl` twice, and pushing to `BlockInfoStack` twice.

File: llvm/test/MC/WebAssembly/block-assembly.s [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+    br_if 0
+    block (f32, f64) -> (f32, f64)
+      i32.const 1
+      br_if 0
+    end_block
+  end_block
+  drop
+  drop
+
+  # Withina loop, branches target the start of the loop
```
Comment (dschuff) [inline llvm/test/MC/WebAssembly/block-assembly.s:90]:
```suggestion
  # Within a loop, branches target the start of the loop
```

**Review by dschuff — APPROVED** [review]
