### PR TITLE
[clang-tidy] fix `bugprone-narrowing-conversions` false positive for conditional expression

### LINKED ISSUE #139467: bugprone-narrowing-conversions false positive for contional expression (in C)
```c
char test(int cond, char c) {
	char ret = cond > 0 ? ':' : c; // warning: narrowing conversion from 'int' to signed type 'char' is implementation-defined
	return ret;
}
```
https://godbolt.org/z/6P8Yaqn4o

### PR DESCRIPTION
**Pull request by AndreyG**
Let's consider the following code from the issue #139467:
```c
void test(int cond, char c) {
    char ret = cond > 0 ? ':' : c;
}
```
Initializer of `ret` looks the following:
```
-ImplicitCastExpr 'char' <IntegralCast>
 `-ConditionalOperator 'int'
   |-BinaryOperator 'int' '>'
   | |-ImplicitCastExpr 'int' <LValueToRValue>
   | | `-DeclRefExpr 'int' lvalue ParmVar 'cond' 'int'
   | `-IntegerLiteral 'int' 0
   |-CharacterLiteral 'int' 58
   `-ImplicitCastExpr 'int' <IntegralCast>
     `-ImplicitCastExpr 'char' <LValueToRValue>
       `-DeclRefExpr 'char' lvalue ParmVar 'c' 'char'
```
So it could be seen that `RHS` of the conditional operator is `DeclRefExpr 'c'` which is casted to `int` and then the whole conditional expression is casted to 'char'. But this last conversion is not narrowing, because `RHS` was `char` _initially_. We should just remove the cast from `char` to `int` before the narrowing conversion check.

Fixes #139467

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp [hunk 1]
```diff
@@ -554,15 +554,23 @@ bool NarrowingConversionsCheck::handleConditionalOperator(
...
   return false;
 }
 
+void NarrowingConversionsCheck::handleConditionalOperatorArgument(
+    const ASTContext &Context, const Expr &Lhs, const Expr *Arg) {
+  if (const auto *ICE = llvm::dyn_cast<ImplicitCastExpr>(Arg)) {
+    if (!Arg->getIntegerConstantExpr(Context)) {
+      Arg = ICE->getSubExpr();
+    }
+  }
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp:570]: As per LLVM coding-style, there shouldn't be any braces for single-stmt ifs.
```cpp
if (const auto *ICE = llvm::dyn_cast<ImplicitCastExpr>(Arg))
    if (!Arg->getIntegerConstantExpr(Context))
      Arg = ICE->getSubExpr();
```

**Comment by AndreyG** [comment]
> Please mention changes in Release Notes.

Done: https://github.com/llvm/llvm-project/pull/139474/files#diff-1c1f5fd4fa3f177899b71a6bf4582a6277de0df37dae33a9c670c73f28cc1ce6R145-R148

File: clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp (hunk 1 above)
Comment (AndreyG) [reply clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: Fixed: https://github.com/llvm/llvm-project/pull/139474/files#diff-25d304d497ff4aad5697d817f123266e1e78ee7c7e727e6ad9381e1d7fcdcac4R566-R568

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.c
Comment (5chmidti) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.c:1]: Please add more tests:

- one of the args being, e.g., `int`, since there should still be a warning
- also add those same tests to the C++ tests to cover that they are being handled correctly in both languages

Comment (AndreyG) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.c:1]: Done. I've added tests for `short` and `int` and the same for C++. Also I noticed that in `trunk` there is the same issue in C++ for `short` (but not for `char`): https://github.com/llvm/llvm-project/issues/139467#issuecomment-3068027828. In my branch it's fixed.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.c [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+int test_int(int cond, int i) {
+	int ret = cond > 0 ? ':' : i;
+	return ret;
+}
+
+void test(int cond, int i) {
+  char x = cond > 0 ? ':' : i;
+  // CHECK-MESSAGES: :[[@LINE-1]]:29: warning: narrowing conversion from 'int' to signed type 'char' is implementation-defined [bugprone-narrowing-conversions]
+}
+
```
Comment (EugeneZelenko) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.c]:
```suggestion
```

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.cpp [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+int test_int(int cond, int i) {
+	int ret = cond > 0 ? ':' : i;
+	return ret;
+}
+
+void test(int cond, int i) {
+  char x = cond > 0 ? ':' : i;
+  // CHECK-MESSAGES: :[[@LINE-1]]:29: warning: narrowing conversion from 'int' to signed type 'char' is implementation-defined [bugprone-narrowing-conversions]
+}
+
```
Comment (EugeneZelenko) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions-conditional-expressions.cpp]:
```suggestion
```

File: clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp (hunk 1 above)
Comment (5chmidti) [reply clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: this was not fixed

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -182,6 +182,10 @@ New check aliases
 Changes in existing checks
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 
+- Improved :doc:`bugprone-narrowing-conversions
```
Comment (5chmidti) [inline clang-tools-extra/docs/ReleaseNotes.rst:137]: Please sort this in alphabetically

**Review by 5chmidti — APPROVED** [review]
Except for these minor open issues, this looks good, thanks.

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (vbvictor) [reply clang-tools-extra/docs/ReleaseNotes.rst:137]: Also, please rebase on fresh main because there would be new `bugprone` entry in docs

Comment (AndreyG) [reply clang-tools-extra/docs/ReleaseNotes.rst:137]: Done (https://github.com/llvm/llvm-project/pull/139474/commits/0ac1db21da725020e16bd3cb487ed097be64046a)

File: clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp (hunk 1 above)
Comment (AndreyG) [reply clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: Sorry, I've lost the change during rebase. Fixed this again (https://github.com/llvm/llvm-project/pull/139474/commits/f350b58372461d14186b8e1430d6c0ab1e5a9351).

**Review by vbvictor — APPROVED** [review]
LGTM, please rebase on latest main, ReleaseNotes were cleared after 21th release. After that, could be merged.

**Comment by vbvictor** [comment]
It seems we are having issues on arm platforms, I need to revert this patch.

**Comment by vbvictor** [comment]
Please, investigate this issue and when re-applying the reverted patch, commit message should be updated to indicate the problem that was addressed and how it was addressed.

https://llvm.org/docs/DeveloperPolicy.html#patch-reversion-policy

**Comment by AndreyG** [comment]
@vbvictor I've found out that unlike other narrowing-conversion tests, I didn't set explicitly target for the test run.
I've fixed it and created another PR #151874. Please, take a look and sorry for the inconvenience.
