### PR TITLE
[DirectX] Add a GEP to loads and stores on array allocas

### LINKED ISSUE #147114: [DirectX] Direct stores to array allocas cause validation error: Explicit load/store type does not match pointee type of pointer operand
## The Problem
69 DML shaders are failing to validate due to validation error: `Explicit load/store type does not match pointee type of pointer operand`

## Reproducing the problem
```
dxv workspace/ClangDML/tools/shader_builder_clang/validation/NonzeroCoordinatesSingleLevel_256_16_Strided_int_8.dat
```

Minimal reproduction shader:
```hlsl
uint2 Foo(uint2 a[2], uint i) {
  return a[i];
}
RWStructuredBuffer<uint2> output;
[numthreads(1, 1, 1)]
void CSMain(uint3 Tid : SV_DispatchThreadID) {
  uint2 arr[2] = {Tid.xy, Tid.yx};
  output[0] = Foo(arr, Tid.z);
}
```
https://godbolt.org/z/PdW9d7brE

Using lldb, I have found that the validation error is due to direct scalar stores into array allocas:
```llvm
  %1 = alloca [4 x i32], align 8
  %4 = call i32 @dx.op.threadId.i32(i32 93, i32 0) #3, !dbg !86
  store i32 %4, ptr %1, align 8, !dbg !105
```
returning this error https://github.com/microsoft/DirectXShaderCompiler/blob/4fcf67f78f7d6ffd286316112694a3ae000860e2/lib/Bitcode/Reader/BitcodeReader.cpp#L3693

## Solution

The dxil-legalize pass `DXILLegalizePass.cpp` should insert a GEP for store and load instructions on array allocas.

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #147114 by inserting a GEP between any direct loads and stores on an alloca.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 1]
```diff
@@ -605,6 +649,7 @@ class DXILLegalizationPipeline {
     LegalizationPipeline[Stage1].push_back(legalizeMemCpy);
     LegalizationPipeline[Stage1].push_back(removeMemSet);
     LegalizationPipeline[Stage1].push_back(updateFnegToFsub);
+    LegalizationPipeline[Stage1].push_back(legalizeLoadStoreOnArrayAllocas);
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: Are you sure its ok to put this in stage 1? We already do IR replacement for loads and stores in this stage just want to be cautions about adding the same instruction twice to `ToRemove`.

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: To be clear I think if you have a load\store with an i8. this could crash because `fixI8UseChain` will also add the load\store to `ToRemove`.

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: Good catch. It does error when there is an i8 load/store directly on an alloca.
I should move this to stage 2 then?

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: That would be the easiest. I have thought about changing this to a set, but while i think that would fix the crashing I dunno if that would result in correct transformation because we would be making assumptions on stale IR.

File: llvm/test/CodeGen/DirectX/legalize-i8.ll [hunk 2]
```diff
@@ -127,10 +127,9 @@ define i32 @i8_geps_index0() {
   ; CHECK:         [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
   ; CHECK-NEXT:    ret i32 [[LOAD]]
   %1 = alloca [2 x i32], align 8
-  %2 = getelementptr inbounds nuw i8, ptr %1, i32 0
-  %3 = load i8, ptr %2
-  %4 = sext i8 %3 to i32
-  ret i32 %4
+  %2 = load i8, ptr %1
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/legalize-i8.ll:130]: Why did this test need to change? Shouldn’t we check that if a gep already exists we don’t do your pass?

Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:130]: It didn't need to change, but there is already another i8 load test that has a GEP to access index 1 (i8_geps_index1), so I just rewrote the index 0 test (i8_geps_index0) to omit the GEP.

Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:130]: I can instead restore the original test and add a completely new test if you prefer.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 3]
```diff
@@ -562,6 +562,51 @@ legalizeGetHighLowi64Bytes(Instruction &I,
   }
 }
 
+static void
+legalizeLoadStoreOnArrayAllocas(Instruction &I,
+                                SmallVectorImpl<Instruction *> &ToRemove,
+                                DenseMap<Value *, Value *> &) {
+
+  Value *PtrOp;
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:570]: nit:
```suggestion
  Value *PtrOp = nullptr;
```

Just to be consistent with the pattern below for `NewLoadStore`

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 4]
```diff
@@ -562,6 +562,51 @@ legalizeGetHighLowi64Bytes(Instruction &I,
...
+         "Expected allocated type of AllocaInst to be a flat ArrayType");
+
+  IRBuilder<> Builder(&I);
+  Value *Zero = Builder.getInt32(0);
+  Value *GEP = Builder.CreateGEP(Ty, AllocaPtrOp, {Zero, Zero}, "",
+                                 GEPNoWrapFlags::all());
+
+  Value *NewLoadStore = nullptr;
+  if (auto *LI = dyn_cast<LoadInst>(&I))
+    NewLoadStore = Builder.CreateLoad(LI->getType(), GEP, LI->getName());
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: nit:
```suggestion
    NewLoadStore = Builder.CreateLoad(LoadStoreTy, GEP, LI->getName());
```

Can we re-use this and remove the [[maybe_unused]]?

**Review by inbelic — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 3 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:570]: Only `NewLoadStore = nullptr` because otherwise the compiler complains that NewLoadStore could be used without being initialized.
