### PR TITLE
[DebugInfo][ConstraintElimination] Fix debug value loss in replacing comparisons with the speculated constants

### LINKED ISSUE #135736: [DebugInfo][ConstraintElimination] Potential debug value loss in replacing comparisons with the speculated constants
In ConstraintElimination, the pass first collects instructions that could be replaced with a speculated constant in function [`checkAndReplaceCondition()`](https://github.com/llvm/llvm-project/blob/fe54d1afcca055f464840654dd2ec3fd83aea688/llvm/lib/Transforms/Scalar/ConstraintElimination.cpp#L1431), and then it removes the collected instruction in [ConstraintElimination-L1964](https://github.com/llvm/llvm-project/blob/fe54d1afcca055f464840654dd2ec3fd83aea688/llvm/lib/Transforms/Scalar/ConstraintElimination.cpp#L1964).
```c++
1963  for (Instruction *I : ToRemove)
1964    I->eraseFromParent();
```

However, I found that this process leads to _**poison debug values**_ in the optimzied IR. [Here](https://godbolt.org/z/78aMxx6En) is an example where the ConstraintElimination is performed on an LLVM IR function in the regression test (and.ll) of the pass. The debug information is obtained by `opt -passes=debugify`. Poison debug values are produced in the basic block `bb1`:
```llvm ir
; Before the optimization
bb1:                                              ; preds = %entry
  %t.1 = icmp ule i4 %x, %z, !dbg !31
    #dbg_value(i1 %t.1, !13, !DIExpression(), !31)
  %t.2 = icmp ule i4 %x, %y, !dbg !32
    #dbg_value(i1 %t.2, !14, !DIExpression(), !32)
  %r.1 = xor i1 %t.1, %t.2, !dbg !33
```

```llvm ir
; After the optimization
bb1:                                              ; preds = %entry
    #dbg_value(i1 poison, !13, !DIExpression(), !31)
    #dbg_value(i1 poison, !14, !DIExpression(), !32)
  %r.1 = xor i1 true, true, !dbg !33
```

I think these poison debug values, which corresponds to the erased `icmp` instructions, **_could be prevented_** according to [rules-for-updating-debug-values](https://llvm.org/docs/HowToUpdateDebugInfo.html#rules-for-updating-debug-values). Specifically, we can use either `salvageDebugInfo()` (i.e., using the DIExpression) or `replaceAllDbgUsesWith()` (i.e., refering the debug value to the speculated constrant) to save the debug value information for the erased `imp` instructions.

Moreover, could this issue be caused by the missed debug information salvage in `Value::replaceUsesWithIf()` used in `checkAndReplaceCondition()`? (`Value::replaceAllUsesWith` handles the debug value information for the replaced instruction.)

### PR DESCRIPTION
**Pull request by Apochens**
Fix #135736

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp [hunk 1]
```diff
@@ -1454,8 +1455,20 @@ static bool checkAndReplaceCondition(
...
+    if (Cmp->use_empty()) {
+      SmallVector<DbgVariableIntrinsic *> DbgUsers;
+      SmallVector<DbgVariableRecord *> DVRUsers;
+      findDbgUsers(DbgUsers, Cmp, &DVRUsers);
+
+      for (auto *DVR : DVRUsers) {
+        auto *DTN = DT.getNode(DVR->getParent());
+        if (!DTN || DTN->getDFSNumIn() < NumIn || DTN->getDFSNumOut() > NumOut)
+          continue;
+        DVR->replaceVariableLocationOp(Cmp, ConstantC);
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:1467]: The non-debug code also has a check that if the user comes before the ContextInst it's skipped. I think we probably need to copy that too?
```
; ModuleID = '/app/example.ll'
source_filename = "/app/example.ll"

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #0

declare void @may_unwind()

declare void @use(i1)

define i1 @assume_single_bb_conditions_after_assume(i8 %a, i8 %b, i1 %c) !dbg !5 {
  %add.1 = add nuw nsw i8 %a, 1, !dbg !11
  %cmp.1 = icmp ule i8 %add.1, %b, !dbg !12
  %c.1 = icmp ule i8 %add.1, %b, !dbg !13
    #dbg_value(i1 %c.1, !9, !DIExpression(), !14)
  call void @use(i1 %c.1), !dbg !15
    #dbg_value(i1 %c.1, !9, !DIExpression(), !14)
  call void @may_unwind(), !dbg !16
    #dbg_value(i1 %c.1, !9, !DIExpression(), !14)
  call void @llvm.assume(i1 %cmp.1), !dbg !17
    #dbg_value(i1 %c.1, !9, !DIExpression(), !14)
  %t.2 = icmp ule i8 %a, %b, !dbg !14
    #dbg_value(i1 %c.1, !9, !DIExpression(), !14)
  %res.1 = xor i1 %c.1, %t.2, !dbg !18
  %add.2 = add nuw nsw i8 %a, 2, !dbg !19
  %c.2 = icmp ule i8 %add.2, %b, !dbg !20
  %res.2 = xor i1 %res.1, %c.2, !dbg !21
  ret i1 %res.2, !dbg !22
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }

!llvm.dbg.cu = !{!0}
!llvm.debugify = !{!2, !3}
!llvm.module.flags = !{!4}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "/app/example.ll", directory: "/")
!2 = !{i32 12}
!3 = !{i32 8}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = distinct !DISubprogram(name: "assume_single_bb_conditions_after_assume", linkageName: "assume_single_bb_conditions_after_assume", scope: null, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
!6 = !DISubroutineType(types: !7)
!7 = !{}
!8 = !{!9}
!9 = !DILocalVariable(name: "4", scope: !5, file: !1, line: 7, type: !10)
!10 = !DIBasicType(name: "ty8", size: 8, encoding: DW_ATE_unsigned)
!11 = !DILocation(line: 1, column: 1, scope: !5)
!12 = !DILocation(line: 2, column: 1, scope: !5)
!13 = !DILocation(line: 3, column: 1, scope: !5)
!14 = !DILocation(line: 7, column: 1, scope: !5)
!15 = !DILocation(line: 4, column: 1, scope: !5)
!16 = !DILocation(line: 5, column: 1, scope: !5)
!17 = !DILocation(line: 6, column: 1, scope: !5)
!18 = !DILocation(line: 8, column: 1, scope: !5)
!19 = !DILocation(line: 9, column: 1, scope: !5)
!20 = !DILocation(line: 10, column: 1, scope: !5)
!21 = !DILocation(line: 11, column: 1, scope: !5)
!22 = !DILocation(line: 12, column: 1, scope: !5)
```

I think it's probably incorrect for the dbg_values to have their use replaced with `true` before the `assume`. Annoyingly, it looks like we won't be able to catch all dbg_values though (the 3rd one doesn't get updated because it comes before the ContextInst in that case... not sure there's much we can do about that?). IMO adding a comment with a FIXME noting the shortcoming is good enough here, if we can't think of something better.

(Can you add this as another regression test please?)

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp [hunk 2]
```diff
@@ -1454,8 +1455,20 @@ static bool checkAndReplaceCondition(
       return ShouldReplace;
     });
     NumCondsRemoved++;
-    if (Cmp->use_empty())
+    if (Cmp->use_empty()) {
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:1458]: Hmmm.. .I think we probably want to do the debug update outside of the `if (Cmp->use_empty())` block (unconditionally)? Otherwise we're only updating debug info if there are no other non-dbg uses. But IMO we should update the debug info regardless, because we know the value on this code path. 

(I'm not sure there's a clear correct answer, happy to discuss further).

**Review by OCHyams — COMMENTED** [review]
Thanks for the PR, I've got couple of questions inline

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp (hunk 1 above)
Comment (Apochens) [reply llvm/lib/Transforms/Scalar/ConstraintElimination.cpp]: I have added this as another regression test `salvage-dbg-values-replaced-by-constant-2.ll`. However, the optimized IR shows that the forth `dbg_value` cannot be updated as well, because the `ContextInst` is `%t.2`.

File: llvm/test/Transforms/ConstraintElimination/salvage-dbg-values-replaced-by-constant.ll [hunk 3]
```diff
@@ -0,0 +1,80 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
```
[the remark this answers is not in the document]
Comment (Apochens) [reply llvm/test/Transforms/ConstraintElimination/salvage-dbg-values-replaced-by-constant.ll]: Thanks for the reminder. In the latest commit, I have made the test checks more concise.

File: llvm/lib/Transforms/Scalar/ConstraintElimination.cpp [hunk 4]
```diff
@@ -1454,8 +1455,29 @@ static bool checkAndReplaceCondition(
...
+
+    for (auto *DVR : DVRUsers) {
+      auto *DTN = DT.getNode(DVR->getParent());
+      if (!DTN || DTN->getDFSNumIn() < NumIn || DTN->getDFSNumOut() > NumOut)
+        continue;
+
+      auto *MarkedI = DVR->getInstruction();
+      if (MarkedI->getParent() == ContextInst->getParent() &&
+          MarkedI->comesBefore(ContextInst))
+        continue;
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/ConstraintElimination.cpp:1473]: Hmm, part of me wants to reduce code duplication by introducing a lambda that is used by this code and the checks in `replaceUsesWithIf` above. That gives an added benefit of naming what it's doing. On the other hand, that might be more boilerplate than is needed here, so I'm happy for it to stay as it is too.

**Review by OCHyams — APPROVED** [review]
LGTM after a couple of final nits (inline), thanks

**Review by OCHyams — COMMENTED** [review]
(Still LGTM - I think this is good to merge now)
