### PR TITLE
[clang-tidy] Fix false positive in readability-redundant-preprocessor for builtin checks

### LINKED ISSUE #64825: [clang-tidy] readability-redundant-preprocessor false positive on builtin preprocessor checks
```c++
#if __has_builtin(__remove_cvref)
#  if __has_cpp_attribute(no_unique_address)
#  endif
#endif
```
([Godbolt](https://godbolt.org/z/sEs3P3Yz6)) generates
```c++
1 warning generated.
<source>:2:4: warning: nested redundant #if; consider removing it [readability-redundant-preprocessor]
    2 | #  if __has_cpp_attribute(no_unique_address)
      |    ^
<source>:1:2: note: previous #if was here
    1 | #if __has_builtin(__remove_cvref)
      |  ^
1 warning generated.
```
which is obviously wrong.

### PR DESCRIPTION
**Pull request by Aditya26189**
Different `__has_builtin()` checks were incorrectly flagged as redundant because ConditionRange collapsed after macro expansion. It now reads condition text directly from source to fix this.

Assisted-by: Claude
Fixes #64825

### CODE REVIEW

File: clang-tools-extra/clang-tidy/readability/RedundantPreprocessorCheck.cpp [hunk 1]
```diff
@@ -69,6 +72,44 @@ class RedundantPreprocessorCallbacks : public PPCallbacks {
...
+    if (AfterIf.isInvalid())
+      return {};
+
+    bool Invalid = false;
+    auto [FID, Offset] = SM.getDecomposedLoc(AfterIf);
+    const StringRef Buffer = SM.getBufferData(FID, &Invalid);
+    if (Invalid || Offset >= Buffer.size())
+      return {};
+
+    // Read to end-of-line, handling backslash line continuations.
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/readability/RedundantPreprocessorCheck.cpp]: Could we use `Lexer::getRawToken` for this?

File: clang-tools-extra/test/clang-tidy/checkers/readability/redundant-preprocessor.cpp [hunk 2]
```diff
@@ -82,3 +82,116 @@ void k();
 void k();
 #endif
 #endif
+
```
Comment (zeyi2) [inline clang-tools-extra/test/clang-tidy/checkers/readability/redundant-preprocessor.cpp]: Could we add testcases for inline and multiline comments?

**Comment by Aditya26189** [comment]
Ping. @EugeneZelenko I have added the Release Notes entry. @zeyi2 let me know if the getRawToken explanation makes sense.

**Review by zeyi2 — APPROVED** [review]
Overall LGTM, but please wait for other reviewers :)
