### PR TITLE
[lld][MachO] Fix symbol insertion in `transplantSymbolsAtOffset`

### LINKED ISSUE #120559: [lld][MachO] llvm::upper_bound called on not correctly sorted input
When building llvm-project with -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON with a recent libstdc++ (e.g. from gcc 13.3.0) the testcases:
```
  lld :: MachO/local-alias-to-weak.s
  lld :: MachO/symtab.s
  lld :: MachO/weak-definition-gc.s
```
fail with the message:

```
.../include/c++/13.3.0/bits/stl_algo.h:2100:
In function:
    _ForwardIterator std::upper_bound(_ForwardIterator, _ForwardIterator, 
    const _Tp &, _Compare) [_ForwardIterator = lld::macho::Defined **, _Tp = 
    unsigned long, _Compare = (lambda at 
    ../../lld/MachO/SymbolTable.cpp:77:15)]

Error: elements in iterator range [first, last) are not partitioned by the 
predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7ffc2bfd9af8 {
    }
    iterator "last" @ 0x7ffc2bfd9af0 {
    }
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /repo/llvm-project/llvm/build/bin/ld64.lld -arch x86_64 -platform_version macos 11.0 11.0 -syslibroot /repo/llvm-project/lld/test/MachO/Inputs/MacOSX.sdk -lSystem -fatal_warnings -lSystem -dylib /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/no-subsections.o /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/local-then-weak.o -o /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/nosub-sub
 #0 0x000055af1d9c8706 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d89706)
 #1 0x000055af1d9c60ce llvm::sys::RunSignalHandlers() (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d870ce)
 #2 0x000055af1d9c8f79 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007efebf8c7cf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00007efebe980acf raise (/lib64/libc.so.6+0x4eacf)
 #5 0x00007efebe953ea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x000055af223cfa43 (/repo/llvm-project/llvm/build/bin/ld64.lld+0x9790a43)
 #7 0x000055af1df2aab1 transplantSymbolsAtOffset(lld::macho::InputSection*, lld::macho::InputSection*, lld::macho::Defined*, unsigned long, unsigned long) SymbolTable.cpp:0:0
 #8 0x000055af1df29519 lld::macho::SymbolTable::addDefined(llvm::StringRef, lld::macho::InputFile*, lld::macho::InputSection*, unsigned long, unsigned long, bool, bool, bool, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x52ea519)
 #9 0x000055af1de8a33e void lld::macho::ObjFile::parseSymbols<lld::macho::LP64>(llvm::ArrayRef<lld::macho::LP64::section>, llvm::ArrayRef<lld::macho::LP64::nlist>, char const*, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x524b33e)
#10 0x000055af1de78214 void lld::macho::ObjFile::parse<lld::macho::LP64>() (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5239214)
#11 0x000055af1de77cc8 lld::macho::ObjFile::ObjFile(llvm::MemoryBufferRef, unsigned int, llvm::StringRef, bool, bool, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5238cc8)
#12 0x000055af1de492dc lld::macho::ObjFile* lld::make<lld::macho::ObjFile, llvm::MemoryBufferRef&, unsigned int, char const (&) [1], bool&>(llvm::MemoryBufferRef&, unsigned int&&, char const (&) [1], bool&) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x520a2dc)
#13 0x000055af1de43090 addFile(llvm::StringRef, LoadType, bool, bool, bool, bool) Driver.cpp:0:0
#14 0x000055af1de40cdd lld::macho::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5201cdd)
#15 0x000055af1d9cafbe lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d8bfbe)
#16 0x000055af1d8f6f1b lld_main(int, char**, llvm::ToolContext const&) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb7f1b)
#17 0x000055af1d8f76a6 main (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb86a6)
#18 0x00007efebe96cd85 __libc_start_main (/lib64/libc.so.6+0x3ad85)
#19 0x000055af1d8f6cae _start (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb7cae)
Aborted (core dumped)
```

The reason for this is that the requirement for calling llvm::upper_bound (std::upper_bound) in function transplantSymbolsAtOffset() in file lld/MachO/SymbolTable.cpp is not fulfilled. The input to std::upper_bound needs sorted vector because it implements binary search to find the value.

### PR DESCRIPTION
**Pull request by carlocab**
The existing comparison does not insert symbols in the intended place.

Closes #120559.

### CODE REVIEW

**Comment by carlocab** [comment]
These comments probably best describe the problem and why this is the correct fix: https://github.com/llvm/llvm-project/issues/120559#issuecomment-2554622746, https://github.com/llvm/llvm-project/issues/120559#issuecomment-2556635641

**Comment by alx32** [comment]
About adding a test for this - `lld/test/MachO/alias-symbols.s` triggers the insert. Currently all the offsets are 0's so the position doesn't matter.
I think we should be able to slightly tweak `alias-symbols.s` to insert a symbol with a non-zero offset and then add an `assert(std::is_sorted)` at the end of `transplantSymbolsAtOffset` and that will be our test. Have you looked into weather this is possible ?

**Comment by carlocab** [comment]
I hadn't looked at `alias-symbols.s` since that wasn't one of the failing tests flagged at #120559, but the approach you suggest sounds promising.

I'll give it a try, but would appreciate as many hints as possible. Not really familiar with how symbols are laid out in x86 assembly.

**Comment by bjope** [comment]
Nice idea with the assert. Adding
`assert(llvm::is_sorted(toIsec->symbols) && "Symbols should still be sorted at exit.");
`
at end of transplantSymbolsAtOffset seem to result in assertion failure for the `lld/test/MachO/symtab.s`.

So that might be enough, considering that there already is a test case that would trigger such an assert.

**Comment by bjope** [comment]
> Nice idea with the assert. Adding `assert(llvm::is_sorted(toIsec->symbols) && "Symbols should still be sorted at exit."); ` at end of transplantSymbolsAtOffset seem to result in assertion failure for the `lld/test/MachO/symtab.s`.
> 
> So that might be enough, considering that there already is a test case that would trigger such an assert.

Ooops, was a bit fast. That is_sorted call needs to supply the comparison function.
Guess the problem is to understand which comparison function to provide given that the fault is in the comparison function :-)

**Comment by carlocab** [comment]
> Guess the problem is to understand which comparison function to provide given that the fault is in the comparison function :-)

This comment notwithstanding, I added an assertion anyway since it seems like an improvement. Interestingly, the assertion I just added does _not_ fire with Apple Clang/libc++ even if I drop the `s/</>/` change from the first commit here.

**Comment by alx32** [comment]
> the assertion I just added does _not_ fire with Apple Clang/libc++ even if I drop the `s/</>/` change from the first commit here.

Does it fire with any other build config when run against the current test set ? 
BTW the suggestion about modifying `lld/test/MachO/alias-symbols.s` was to have it trigger the assert with `Clang/libc++` with the current test set.

**Comment by carlocab** [comment]
> Does it fire with any other build config when run against the current test set ?

It should fire with GCC, except GCC crashes before the `assert` is reached.

> BTW the suggestion about modifying `lld/test/MachO/alias-symbols.s` was to have it trigger the assert with `Clang/libc++` with the current test set.

Yes, understood, but I'm still looking into the right way to modify `alias-symbols.s`. As mentioned [above](https://github.com/llvm/llvm-project/pull/120737#issuecomment-2557400163), tips appreciated!

**Comment by alx32** [comment]
> It should fire with GCC, except GCC crashes before the `assert` is reached.

GCC doesn't crash without `-DLLVM_ENABLE_EXPENSIVE_CHECKS=ON` - right ? 
Does the assert fire with GCC without the `-DLLVM_ENABLE_EXPENSIVE_CHECKS=ON` flag ? 

> Yes, understood, but I'm still looking into the right way to modify alias-symbols.s. As mentioned https://github.com/llvm/llvm-project/pull/120737#issuecomment-2557400163, tips appreciated!

Currently I think `_weak_2` symbol is the one being inserted. I would either:
- Modify the `_weak_2` symbol to have a `value` of 1.
- Add another `_weak_3` that has the `value` of 1. 

Given the tests have `.subsections_via_symbols` this will be a bit tricky - would need to play around with multiple options to get this to happen. It's not obvious what would work here.

**Comment by carlocab** [comment]
> GCC doesn't crash without `-DLLVM_ENABLE_EXPENSIVE_CHECKS=ON` - right ?

Right.

> Does the assert fire with GCC without the `-DLLVM_ENABLE_EXPENSIVE_CHECKS=ON` flag ?

No, weirdly.

However, it seems we can assert on `std::is_partitioned` instead. This fires both with Clang and GCC before fixing the comparison lambda.

> Currently I think `_weak_2` symbol is the one being inserted. I would either:
> 
> * Modify the `_weak_2` symbol to have a `value` of 1.
> * Add another `_weak_3` that has the `value` of 1.
> 
> Given the tests have `.subsections_via_symbols` this will be a bit tricky - would need to play around with multiple options to get this to happen. It's not obvious right away what would work here.

Thanks; I'll give this a try after the weekend.

File: lld/MachO/SymbolTable.cpp [hunk 1]
```diff
@@ -91,6 +97,11 @@ static void transplantSymbolsAtOffset(InputSection *fromIsec,
     }
     return true;
   });
+  assert(llvm::is_sorted(toIsec->symbols,
+                         [](const Defined *s, const Defined *t) {
+                           return s->value < t->value;
+                         }) &&
+         "Symbols should still be sorted at exit.");
```
Comment (carlocab) [inline lld/MachO/SymbolTable.cpp:104]: I'll probably get rid of this one, since I can't get it to fire. My theory is that the failure of this assertion can only be a consequence of UB, so the compiler just optimises this away. (No real evidence to support this though, so could be wrong!)

Comment (alx32) [reply lld/MachO/SymbolTable.cpp:104]: Does `is_partitioned` trigger without expensive checks ? On which tests does it trigger ?

Comment (carlocab) [reply lld/MachO/SymbolTable.cpp:104]: I've verified that `is_partitioned` triggers _with_ expensive checks with Clang, and _without_ expensive checks with GCC.

The failing tests (for both) are
```
Failed Tests (3):
  lld :: MachO/local-alias-to-weak.s
  lld :: MachO/symtab.s
  lld :: MachO/weak-definition-gc.s
```

I haven't yet verified the assertion failure for Clang without expensive checks. The build is running now; I'll report back soon.

Comment (carlocab) [reply lld/MachO/SymbolTable.cpp:104]: Verified with Clang _without_ expensive checks and the comparison in `symSucceedsOff` reversed:
```
Failed Tests (3):
  lld :: MachO/local-alias-to-weak.s
  lld :: MachO/symtab.s
  lld :: MachO/weak-definition-gc.s
```
To be sure, all errors are of the form
```
Assertion failed: (std::is_partitioned(toIsec->symbols.begin(), toIsec->symbols.end(), [toOff, symSucceedsOff](const Symbol *s) { return !symSucceedsOff(toOff, s); }) && "Symbols in toIsec must be partitioned by toOff."), function transplantSymbolsAtOffset, file SymbolTable.cpp, line 78.
```

**Comment by carlocab** [comment]
Tried this:
```diff
diff --git a/lld/MachO/SymbolTable.cpp b/lld/MachO/SymbolTable.cpp
index a61e60a944fb..4b6e462f6bdd 100644
--- a/lld/MachO/SymbolTable.cpp
+++ b/lld/MachO/SymbolTable.cpp
@@ -68,7 +68,7 @@ static void transplantSymbolsAtOffset(InputSection *fromIsec,
                                       uint64_t fromOff, uint64_t toOff) {
   // Ensure the symbols will still be in address order after our insertions.
   auto symSucceedsOff = [](uint64_t off, const Symbol *s) {
-    return cast<Defined>(s)->value > off;
+    return cast<Defined>(s)->value < off;
   };
   assert(std::is_partitioned(toIsec->symbols.begin(), toIsec->symbols.end(),
                              [symSucceedsOff, toOff](const Symbol *s) {
@@ -96,6 +96,11 @@ static void transplantSymbolsAtOffset(InputSection *fromIsec,
     }
     return true;
   });
+  assert(llvm::is_sorted(toIsec->symbols,
+                         [](const Defined *s, const Defined *t) {
+                           return s->value < t->value;
+                         }) &&
+         "Symbols should still be sorted at exit.");
 }
 
 Defined *SymbolTable::addDefined(StringRef name, InputFile *file,
diff --git a/lld/test/MachO/alias-symbols.s b/lld/test/MachO/alias-symbols.s
index 44a388c35722..231ada5aa4c8 100644
--- a/lld/test/MachO/alias-symbols.s
+++ b/lld/test/MachO/alias-symbols.s
@@ -124,7 +124,9 @@ _strong:
 _weak_1:
   .space 1
 _weak_2:
-  .space 1
+  .long 1
+_weak_3:
+  .long 1
 _dead:
   .space 1
 _pext:
```
Still no failure from `lld/test/MachO/alias-symbols.s`. Given that the `is_partitioned` assertion isn't even firing here, I wonder if trying to modify `alias-symbols.s` is going to be a lot more complicated than working with the other tests that are failing.

File: lld/MachO/SymbolTable.cpp (hunk 1 above)
Comment (alx32) [reply lld/MachO/SymbolTable.cpp]: Great, thanks for checking this.

**Review by alx32 — APPROVED** [review]
LGTM

**Comment by carlocab** [comment]
To be sure that we're not in a "works on my machine" situation, I pushed 0db5264e5918221edec3dacd2e8c0c6328769517 to ensure that the `is_partitioned` assertion triggers in CI. Sure enough, it does: https://buildkite.com/llvm-project/github-pull-requests/builds/131531

Going to revert that commit then merge.
