### PR TITLE
[clang-format] Fix a crash in formatting unbalanced angle brackets

### LINKED ISSUE #173382: clang-format crashes while trying to format file
[to_string_helper.h.txt](https://github.com/user-attachments/files/24312300/to_string_helper.h.txt)

When I try to format the attached file with clang-format (21.1.7) clang-format will crash:
```
clang-format -i -Werror to_string_helper.h
```

### PR DESCRIPTION
**Pull request by owenca**
Fixes #173382

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -29053,6 +29053,11 @@ TEST_F(FormatTest, KeywordedFunctionLikeMacros) {
                Style);
 }
 
+TEST_F(FormatTest, UnbalancedAngleBrackets) {
+  verifyNoCrash("typename foo<bar>::value, const String &>::type f();",
+                getLLVMStyleWithColumns(50));
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp]: Do we need the column limit?

File: clang/unittests/Format/FormatTest.cpp [hunk 2]
```diff
@@ -29053,6 +29053,11 @@ TEST_F(FormatTest, KeywordedFunctionLikeMacros) {
                Style);
 }
 
+TEST_F(FormatTest, UnbalancedAngleBrackets) {
+  verifyNoCrash("typename foo<bar>::value, const String &>::type f();",
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp]: For me you said, I should use `verifyFormat`, why not here?

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/unittests/Format/FormatTest.cpp (hunk 2 above)
Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp]: Because it's invalid code here, not just incomplete code.

File: clang/unittests/Format/FormatTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp]: Yep! Otherwise, the assertion in `ContinuationIndenter::mustBreak` wouldn't fire.
