### PR TITLE
[lld] Add thunks for hexagon

### LINKED ISSUE #149689: lld gets "relocation R_HEX_B22_PCREL out of range"
When building zig test cases for `hexagon` with `lld`, we encounter range limitations in the relocations, see below for errors.  The limited range of these relocations is expected behavior, but for users making large programs it's undesirable.  `lld` can make extensions using thunks/trampolines, but those aren't yet supported.

Note also that #116798 improved `lld` by correcting the range calculation - it was previously too small.  But that fix alone is not effective for very large programs.

Thanks @alexrp for the bug report.

```
error: ld.lld: /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o:(function os.linux.test.test.user and group ids: .text+0x138d57c): relocation R_HEX_B22_PCREL out of range: -11927916 is not in [-8388608, 8388607]; references 'getauxval'
    note: referenced by test.zig:107 (/home/alexrp/Source/ziglang/zig/lib/std/os/linux/test.zig:107)
    note: defined in /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o
error: ld.lld: /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o:(function os.linux.test.test.user and group ids: .text+0x138d5ec): relocation R_HEX_B22_PCREL out of range: -11928028 is not in [-8388608, 8388607]; references 'getauxval'
    note: referenced by test.zig:108 (/home/alexrp/Source/ziglang/zig/lib/std/os/linux/test.zig:108)
    note: defined in /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o
error: ld.lld: /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o:(function os.linux.test.test.user and group ids: .text+0x138d65c): relocation R_HEX_B22_PCREL out of range: -11928140 is not in [-8388608, 8388607]; references 'getauxval'
    note: referenced by test.zig:109 (/home/alexrp/Source/ziglang/zig/lib/std/os/linux/test.zig:109)
    note: defined in /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o
error: ld.lld: /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o:(function os.linux.test.test.user and group ids: .text+0x138d6cc): relocation R_HEX_B22_PCREL out of range: -11928252 is not in [-8388608, 8388607]; references 'getauxval'
    note: referenced by test.zig:110 (/home/alexrp/Source/ziglang/zig/lib/std/os/linux/test.zig:110)
    note: defined in /home/alexrp/Source/ziglang/zig/.zig-cache/o/ef6d73811ed43e51b7ff5085bd10310c/test.o
```

### PR DESCRIPTION
**Pull request by androm3da**
Without thunks, programs will encounter link errors complaining that the branch target is out of range.  Thunks will extend the range of branch targets, which is a critical need for large programs.  Thunks provide this flexibility at a cost of some modest code size increase.

When configured with the maximal feature set, the hexagon port of the linux kernel would often encounter these limitations when linking with `lld`.

The relocations which will be extended by thunks are:

* R_HEX_B22_PCREL, R_HEX_{G,L}D_PLT_B22_PCREL, R_HEX_PLT_B22_PCREL relocations have a range of ± 8MiB on the baseline
* R_HEX_B15_PCREL: ±65,532 bytes
* R_HEX_B13_PCREL: ±16,380 bytes
* R_HEX_B9_PCREL: ±1,020 bytes

Fixes #149689 

Co-authored-by: Alexey Karyakin <akaryaki@quicinc.com>

### CODE REVIEW

**Comment by androm3da** [comment]
For reference, here's how the Hexagon SDK's `hexagon-link` handles this interesting test case:

```
$ /local/mnt/workspace/Qualcomm/Hexagon_SDK/5.4.1.1/tools/HEXAGON_Tools/8.7.06/Tools/bin/hexagon-llvm-mc -filetype=obj -triple=hexagon-unknown-linux-musl ../llvm-project/lld/test/ELF/hexagon-thunks-packets.s -o hexagon-thunks-packets.s.tmp.o && /local/mnt/workspace/Qualcomm/Hexagon_SDK/5.4.1.1/tools/HEXAGON_Tools/8.7.06/Tools/bin/hexagon-link -o hexagon-thunks-packets.s.tmp hexagon-thunks-packets.s.tmp.o && /local/mnt/workspace/Qualcomm/Hexagon_SDK/5.4.1.1/tools/HEXAGON_Tools/8.7.06/Tools/bin/hexagon-llvm-objdump -d --print-imm-hex hexagon-thunks-packets.s.tmp

hexagon-thunks-packets.s.tmp:	file format elf32-hexagon

Disassembly of section .text:

00000000 <myfn_b>:
       0:	00 c0 9f 52	529fc000 { 	jumpr r31 } 

00000004 <main>:
       4:	28 40 00 5a	5a004028 { 	call 0x54 <trampoline_1_for_myfn_a>
       8:	00 c0 00 78	7800c000   	r0 = #0x0 } 
       c:	24 c0 00 5a	5a00c024 { 	call 0x54 <trampoline_1_for_myfn_a> } 
      10:	f8 ff ff 5b	5bfffff8 { 	call 0x0 <myfn_b> } 
      14:	f6 60 df 5d	5ddf60f6 { 	if (p0) call 0x0 <myfn_b>
      18:	20 40 20 5d	5d204020   	if (!p0) call 0x54 <trampoline_1_for_myfn_a>
      1c:	02 c1 00 f3	f300c102   	r2 = add(r0,r1) } 
      20:	1a 40 00 5d	5d00401a { 	if (p0) call 0x54 <trampoline_1_for_myfn_a>
      24:	1a 40 20 5d	5d20401a   	if (!p0) call 0x54 <trampoline_1_for_myfn_a>
      28:	02 c1 00 f3	f300c102   	r2 = add(r0,r1) } 
      2c:	14 50 80 61	61805014 { 	if (r0==#0) jump:t 0x54
      30:	02 41 00 f3	f3004102   	r2 = add(r0,r1)
      34:	54 30 41 30	30413054   	r1 = r4; 	r4 = r5 } 
      38:	0e 50 c0 61	61c0500e { 	if (r0<=#0) jump:t 0x54
      3c:	0e 40 00 12	1200400e   	p1 = cmp.eq(r0,#0x0); if (p1.new) jump:nt 0x54 <trampoline_1_for_myfn_a>
      40:	02 41 00 f3	f3004102   	r2 = add(r0,r1)
      44:	04 c0 65 70	7065c004   	r4 = r5 } 
      48:	06 c0 00 16	1600c006 { 	r0 = #0x0 ; jump 0x54 <trampoline_1_for_myfn_a> } 
      4c:	da c0 30 16	1630c0da { 	r0 = #0x0 ; jump 0x0 <myfn_b> } 
      50:	00 c0 9f 52	529fc000 { 	jumpr r31 } 

00000054 <trampoline_1_for_myfn_a>:
      54:	00 40 08 00	00084000 { 	immext(#0x800000)
      58:	10 c0 00 58	5800c010   	jump 0x80005c <myfn_a> } 
		...

0080005c <myfn_a>:
  80005c:	04 c0 00 16	1600c004 { 	r0 = #0x0 ; jump 0x800064 <trampoline_2_for_myfn_b> } 
  800060:	00 c0 9f 52	529fc000 { 	jumpr r31 } 

00800064 <trampoline_2_for_myfn_b>:
  800064:	fe 7f f7 0f	0ff77ffe { 	immext(#0xff7fff80)
  800068:	38 c0 00 58	5800c038   	jump 0x0 <myfn_b> } 
```

**Comment by androm3da** [comment]
@quic-akaryaki has fixed the remaining test failures with this patch.  Thanks Alexey!

I'll audit it later this week and probably mark it ready for review then.

File: lld/ELF/Arch/Hexagon.cpp [hunk 1]
```diff
@@ -253,6 +260,35 @@ static uint32_t findMaskR16(uint32_t insn) {
...
+    break;
+  case llvm::ELF::R_HEX_B13_PCREL:
+    return llvm::isInt<13>(offset >> 2);
+    break;
+  case llvm::ELF::R_HEX_B9_PCREL:
+    return llvm::isInt<9>(offset >> 2);
+  default:
+    return true;
+  }
+  llvm::report_fatal_error(StringRef(
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:282]: This is not right. `needsThunk` should reject non-branch relocations and  unknown relocations are llvm_unreachable here.

Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp]: This is inconsistent, yes.  Maybe this should be `unreachable` instead?  The default case above should handle the unknown relocations and there should be no way to execute this code.

File: lld/ELF/Relocations.cpp [hunk 2]
```diff
@@ -2054,18 +2054,46 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
+    case R_ARM_THM_JUMP19:
+    case R_ARM_THM_JUMP24:
+    case R_ARM_THM_CALL:
+      return 4;
+    default:
+      return 8;
+    }
+  }
+  if (ctx.arg.emachine == EM_HEXAGON) {
+    return -getHexagonPacketOffset(isec, rel);
```
[the remark this answers is not in the document]
Comment (androm3da) [reply lld/ELF/Relocations.cpp:2093]: fixed, thank you.

File: lld/ELF/Thunks.cpp [hunk 3]
```diff
@@ -351,6 +351,21 @@ class AVRThunk : public Thunk {
...
+// Hexagon CPUs need thunks for <<FIXME TBD>>
+// when their destination is out of range [0, 0x_?].
+class HexagonThunk : public Thunk {
+public:
+  HexagonThunk(Ctx &ctx, const InputSection &isec, Relocation &rel,
+               Symbol &dest)
+      : Thunk(ctx, dest, 0), RelOffset(rel.offset) {
+    alignment = 4;
+  }
+  uint32_t RelOffset;
```
[the remark this answers is not in the document]
Comment (androm3da) [reply lld/ELF/Thunks.cpp]: fixed.

File: lld/ELF/Thunks.cpp [hunk 4]
```diff
@@ -1365,6 +1380,39 @@ bool PPC64LongBranchThunk::isCompatibleWith(const InputSection &isec,
...
+    ctx.target->relocateNoSym(buf, R_HEX_B32_PCREL_X, s - p);
+    write32(ctx, buf + 4, 0x5800c000); //    jump <> }
+    ctx.target->relocateNoSym(buf + 4, R_HEX_B22_PCREL_X, s - p);
+  }
+}
+void HexagonThunk::addSymbols(ThunkSection &isec) {
+  Symbol *enclosing = isec.getEnclosingSymbol(RelOffset);
+  StringRef src = enclosing ? enclosing->getName() : isec.name;
+
+  addSymbol(saver().save("__trampoline_for_" + destination.getName() +
```
[the remark this answers is not in the document]
Comment (androm3da) [reply lld/ELF/Thunks.cpp:1411]: I thought that it might make sense to preserve the symbol name generated by `hexagon-link` - but I don't think anything should depend on it?  In which case, I'm happy to change it.

How about  `__hexagon_trampoline_for_ ...` instead?

File: lld/ELF/Thunks.cpp [hunk 5]
```diff
@@ -1531,6 +1579,21 @@ static Thunk *addThunkAVR(Ctx &ctx, RelType type, Symbol &s, int64_t a) {
...
+  switch (rel.type) {
+  case R_HEX_B9_PCREL:
+  case R_HEX_B13_PCREL:
+  case R_HEX_B15_PCREL:
+  case R_HEX_B22_PCREL:
+  case R_HEX_PLT_B22_PCREL:
+  case R_HEX_GD_PLT_B22_PCREL:
+    return make<HexagonThunk>(ctx, isec, rel, s);
+  default:
+    fatal("unrecognized relocation type " + toString(rel.type));
```
[the remark this answers is not in the document]
Comment (androm3da) [reply lld/ELF/Thunks.cpp]: This has been changed to follow the pattern used by other architectures, hopefully it's satisfactory.

> ensure this indeed unreachable

Sorry, I'm not sure I understand what would be sufficient.  Ensure it by reviewing the set of relocations for which we could add a thunk?  Or by increasing test coverage here?  Or ... ?

File: lld/test/ELF/hexagon-thunks.s [hunk 6]
```diff
@@ -0,0 +1,44 @@
+# REQUIRES: hexagon
+# RUN: llvm-mc -filetype=obj -triple=hexagon-unknown-elf %s -o %t.o
+# RUN: ld.lld %t.o -o %t
+# RUN: llvm-objdump -d %t 2>&1 | FileCheck --check-prefix=CHECK-NONPIC %s
+# RUN: llvm-mc -filetype=obj --position-independent \
```
[the remark this answers is not in the document]
Comment (androm3da) [reply lld/test/ELF/hexagon-thunks.s]: fixed, thanks.

**Comment by androm3da** [comment]
This PR will need to be rebased after #115925 lands.

**Comment by androm3da** [comment]
> This PR will need to be rebased after #115925 lands.

Done.

File: lld/ELF/Relocations.cpp [hunk 7]
```diff
@@ -2031,17 +2031,44 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
-  if (ctx.arg.emachine != EM_ARM)
-    return 0;
-  switch (type) {
-  case R_ARM_THM_JUMP19:
-  case R_ARM_THM_JUMP24:
-  case R_ARM_THM_CALL:
-    return 4;
-  default:
-    return 8;
+static const uint32_t HEXAGON_MASK_END_PACKET = 3 << 14;
```
Comment (MaskRay) [inline lld/ELF/Relocations.cpp:2034]: constexpr

namespace-scope const variables are of inline linkage by default, so you can omit `static`

File: lld/ELF/Thunks.cpp [hunk 8]
```diff
@@ -402,6 +402,21 @@ class AVRThunk : public Thunk {
   void addSymbols(ThunkSection &isec) override;
 };
 
+// Hexagon CPUs need thunks for <<FIXME TBD>>
```
Comment (MaskRay) [inline lld/ELF/Thunks.cpp:405]: Please fix FIXME

File: lld/ELF/Thunks.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (MaskRay) [reply lld/ELF/Thunks.cpp:1514]: Perhaps `__hexagon_thunk_` that is shorter? The symbol name should not be depended by tools, i.e. it's the tool's responsibility to adapt linker changes.

File: lld/ELF/Relocations.cpp (hunk 7 above)
Comment (androm3da) [reply lld/ELF/Relocations.cpp]: fixed, thank you

File: lld/ELF/Thunks.cpp (hunk 8 above)
Comment (androm3da) [reply lld/ELF/Thunks.cpp]: Ok, fixed.  Is it useful/expected to describe the range of the relocations without the thunks here like `AVRThunk` does?  If so, I'll add that here.

File: lld/test/ELF/hexagon-thunks.s [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+# RUN: llvm-objdump -d %t 2>&1 | FileCheck --check-prefix=CHECK-PIC %s
+
+    .globl main
+    .type  main, @function
+main:
+    call myfn
+    jumpr r31
+    .size   main, .-main
+
+    .org 0x1000000
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunks.s:18]: This creates a large output at 16MiB, which is discourated. Use a linker script like aarch64-thunk-reuse.s to assign a high address

File: lld/test/ELF/hexagon-thunks-packets.s [hunk 10]
```diff
@@ -0,0 +1,119 @@
+# REQUIRES: hexagon
+# RUN: llvm-mc -filetype=obj -triple=hexagon-unknown-linux-musl %s -o %t.o
+# RUN: ld.lld %t.o -o %t
+# RUN: llvm-objdump -d %t 2>&1 | FileCheck --check-prefix=CHECK-NONPIC %s
+# RUN: llvm-mc -filetype=obj --position-independent \
+# RUN:         -triple=hexagon-unknown-linux-musl %s -o %t.o
+# RUN: ld.lld --pie %t.o -o %t
+# RUN: llvm-objdump -d %t 2>&1 | FileCheck --check-prefix=CHECK-PIC %s
+
+# Packets with pc-relative relocations are more interesting because
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunks-packets.s:10]: `## ` for non-RUN non-CHECK lines.

What is 'Packets'?

File: lld/test/ELF/hexagon-thunks-packets.s [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+# the offset must be relative to the start of the source, destination
+# packets and not necessarily the instruction word containing the jump/call.
+
+# CHECK:  Disassembly of section .text:
+
+# CHECK-NONPIC: 000200b4 <__hexagon_thunk_myfn_a_from_.text.thunk>:
+# CHECK-NONPIC: { immext(#0x1000040)
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunks-packets.s:17]: Use -NEXT: whenever applicable to make FileCheck errors better when things go off

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

File: lld/ELF/Arch/Hexagon.cpp [hunk 12]
```diff
@@ -252,6 +259,34 @@ static uint32_t findMaskR16(Ctx &ctx, uint32_t insn) {
...
 static void or32le(uint8_t *p, int32_t v) { write32le(p, read32le(p) | v); }
 
+bool Hexagon::inBranchRange(RelType type, uint64_t src, uint64_t dst) const {
+  int64_t offset = dst - src;
+  switch (type) {
+  case llvm::ELF::R_HEX_B22_PCREL:
+  case llvm::ELF::R_HEX_PLT_B22_PCREL:
+  case llvm::ELF::R_HEX_GD_PLT_B22_PCREL:
+  case llvm::ELF::R_HEX_LD_PLT_B22_PCREL:
+    return llvm::isInt<22>(offset >> 2);
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:269]: We need tests to test the thunk range. aarch64-thunk-pi.s ppc64-long-branch.s are examples to test the exact range.

File: lld/ELF/Arch/Hexagon.cpp [hunk 13]
```diff
@@ -252,6 +259,34 @@ static uint32_t findMaskR16(Ctx &ctx, uint32_t insn) {
...
+  default:
+    return true;
+  }
+  llvm_unreachable("unsupported relocation");
+}
+
+bool Hexagon::needsThunk(RelExpr expr, RelType type, const InputFile *file,
+                         uint64_t branchAddr, const Symbol &s,
+                         int64_t a) const {
+  return !ctx.target->inBranchRange(type, branchAddr, s.getVA(ctx, a));
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:287]: if type is unexpected, needsThunk should return false to avoid a unreachable failure in inBranchRange.

File: lld/test/ELF/hexagon-thunks-packets.s (hunk 10 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunks-packets.s]: > `## ` for non-RUN non-CHECK lines.

Fixed.  Is this an `lld`-ism or should I be doing the same in other llvm-project lit test cases?

> What is 'Packets'?

In hexagon, bundles of opcodes spanning multiple instruction words are dispatched together as one.  The braces in the assembly / disassembly syntax delimit the instructions in a packet.

Would it be helpful to add this context to this test case? or somewhere else in `lld`?

File: lld/test/ELF/hexagon-thunks.s (hunk 9 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunks.s]: Fixed, thanks.

File: lld/test/ELF/hexagon-thunks-packets.s (hunk 11 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunks-packets.s:19]: fixed, thanks.

File: lld/ELF/Arch/Hexagon.cpp (hunk 12 above)
Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp:269]: I will add the necessary tests.

File: lld/ELF/Arch/Hexagon.cpp (hunk 13 above)
Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp:287]: I will investigate a resolution to this issue.

File: lld/test/ELF/hexagon-thunks-packets.s (hunk 10 above)
Comment (nickdesaulniers) [reply lld/test/ELF/hexagon-thunks-packets.s]: > In hexagon, bundles of opcodes spanning multiple instruction words are dispatched together as one. 

VLIW bundles?

Comment (androm3da) [reply lld/test/ELF/hexagon-thunks-packets.s]: Yes, that's right - the packets that are bundled are VLIW instructions.

I used the term "bundle" in the hopes it might be a familiar one for folks who have seen the `BUNDLE` pseudo-instruction in the LLVM compiler.

File: lld/ELF/Arch/Hexagon.cpp (hunk 12 above)
Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp:275]: range test cases added

File: lld/ELF/Arch/Hexagon.cpp (hunk 13 above)
Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp]: fixed

**Comment by androm3da** [comment]
ping @MaskRay

**Review by quic-akaryaki — APPROVED** [review]

**Comment by androm3da** [comment]
@MaskRay any concerns if this gets merged?  It'd be nice if we could get this in before the upcoming 21.x branch for the sake of zig & kernel.

File: lld/ELF/Relocations.cpp [hunk 14]
```diff
@@ -2129,17 +2129,44 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
-    return 8;
+constexpr uint32_t HEXAGON_MASK_END_PACKET = 3 << 14;
+constexpr uint32_t HEXAGON_END_OF_PACKET = 3 << 14;
+constexpr uint32_t HEXAGON_END_OF_DUPLEX = 0 << 14;
+
+// Return the distance between the packet start and the instruction in the
+// relocation.
+static int getHexagonPacketOffset(const InputSection &isec,
+                                  const Relocation &rel) {
+  const ArrayRef<uint8_t> SectContents = isec.content();
```
Comment (MaskRay) [inline lld/ELF/Relocations.cpp]: lld uses the `variableName` naming convention.

The most common convention uses `data` for section content.

File: lld/ELF/Relocations.cpp [hunk 15]
```diff
@@ -2129,17 +2129,44 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
+    uint32_t instWord = 0;
+    const ArrayRef<uint8_t> InstWordContents =
+        SectContents.drop_front(rel.offset - (i + 1) * 4);
+    ::memcpy(&instWord, InstWordContents.data(), sizeof(instWord));
+    if (((instWord & HEXAGON_MASK_END_PACKET) == HEXAGON_END_OF_PACKET) ||
+        ((instWord & HEXAGON_MASK_END_PACKET) == HEXAGON_END_OF_DUPLEX))
+      return i * 4;
+  }
+}
+static int64_t getPCBias(Ctx &ctx, const InputSection &isec,
```
Comment (MaskRay) [inline lld/ELF/Relocations.cpp:2166]: blank line between functions

File: lld/ELF/Thunks.cpp [hunk 16]
```diff
@@ -1692,6 +1741,24 @@ static std::unique_ptr<Thunk> addThunkAVR(Ctx &ctx, RelType type, Symbol &s,
   }
 }
 
+static std::unique_ptr<Thunk> addThunkHexagon(Ctx &ctx,
+                                              const InputSection &isec,
+                                              Relocation &rel, Symbol &s) {
+  switch (rel.type) {
+  case R_HEX_B9_PCREL:
```
Comment (MaskRay) [inline lld/ELF/Thunks.cpp:1748]: In `needsThunk` you list 7 relocation types

  case R_HEX_B22_PCREL:
  case R_HEX_PLT_B22_PCREL:
  case R_HEX_GD_PLT_B22_PCREL:
  case R_HEX_LD_PLT_B22_PCREL:
  case R_HEX_B15_PCREL:
  case R_HEX_B13_PCREL:
  case R_HEX_B9_PCREL:

Here are only 6. Please fix it and don't add `Fatal`. It should just be unreachable. ARM has Fatal because it has complex microarch thunk logic, so some erroneous code paths are technically reachable.

File: lld/test/ELF/hexagon-thunk-range-b22rel.s [hunk 17]
```diff
@@ -0,0 +1,115 @@
...
+.skip 0X7ffff4
+
+## Target beyond maximum negative range (needs thunk)
+.globl target_beyond_range_min
+.type target_beyond_range_min, %function
+target_beyond_range_min:
+  jumpr r31
+
+## Verify thunk generation for targets beyond B22_PCREL range
+# CHECK: 000200b4 <__hexagon_thunk_target_within_range_min_from_.text.thunk>:
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunk-range-b22rel.s]: Omit the address for the `<label>:` line and keep the address for the next instruction, but not subsequent instructions.

This ensures that we will get good FileCheck errors when things go wrong. And we do not need to change too many lines when changing an address.

Indent the `CHECK:` lines with more spaces like
```
# CHECK:      <target_within_range_max>:
# CHECK-NEXT:   200ac: { jumpr r31 }
```

File: lld/test/ELF/hexagon-thunk-range-gdplt.s [hunk 18]
```diff
@@ -0,0 +1,95 @@
+# REQUIRES: hexagon
+# RUN: rm -rf %t && split-file %s %t && cd %t
+# RUN: llvm-mc -filetype=obj -triple=hexagon-unknown-elf main.s -o main.o
+# RUN: ld.lld -shared main.o -o test.so
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunk-range-gdplt.s:4]: `a.s -o a.o`; `ld.lld -shared a.o -o a.so` (or out.so)

File: lld/ELF/Thunks.cpp [hunk 19]
```diff
@@ -1519,6 +1535,39 @@ bool PPC64LongBranchThunk::isCompatibleWith(const InputSection &isec,
   return rel.type == R_PPC64_REL24 || rel.type == R_PPC64_REL14;
 }
 
+// Hexagon Target Thunks
+static uint64_t getHexagonThunkDestVA(Ctx &ctx, const Symbol &s, int64_t a) {
+  uint64_t v = s.isInPlt(ctx) ? s.getPltVA(ctx) : s.getVA(ctx, a);
+  return SignExtend64<32>(v); // FIXME: sign extend to 64-bit?
```
Comment (MaskRay) [inline lld/ELF/Thunks.cpp]: Why is there a FIXME?

File: lld/ELF/Relocations.cpp (hunk 15 above)
Comment (androm3da) [reply lld/ELF/Relocations.cpp:2166]: fixed

File: lld/ELF/Relocations.cpp (hunk 14 above)
Comment (androm3da) [reply lld/ELF/Relocations.cpp]: fixed

File: lld/ELF/Thunks.cpp (hunk 16 above)
Comment (androm3da) [reply lld/ELF/Thunks.cpp:1748]: fixed

File: lld/test/ELF/hexagon-thunk-range-b22rel.s (hunk 17 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunk-range-b22rel.s]: I've made the change but perhaps the subsequent CHECK-NEXT lines should also be indented?  Or does it look okay as-is?

File: lld/test/ELF/hexagon-thunk-range-gdplt.s (hunk 18 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunk-range-gdplt.s:4]: fixed

File: lld/ELF/Thunks.cpp (hunk 19 above)
Comment (androm3da) [reply lld/ELF/Thunks.cpp]: it was addressed and not removed.  Fixed now (by removing it)

File: lld/ELF/Relocations.cpp (hunk 14 above)
Comment (MaskRay) [reply lld/ELF/Relocations.cpp]: still named `SectContents`?

File: lld/ELF/Relocations.cpp [hunk 20]
```diff
@@ -2139,17 +2139,44 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
+static int getHexagonPacketOffset(const InputSection &isec,
+                                  const Relocation &rel) {
+  const ArrayRef<uint8_t> SectContents = isec.content();
+
+  // Search back as many as 3 instructions.
+  for (unsigned i = 0;; i++) {
+    if (i == 3 || rel.offset < (i + 1) * 4)
+      return i * 4;
+    uint32_t instWord = 0;
+    const ArrayRef<uint8_t> InstWordContents =
```
Comment (MaskRay) [inline lld/ELF/Relocations.cpp]: `InstWordContents` fix naming

File: lld/ELF/Relocations.cpp [hunk 21]
```diff
@@ -2139,17 +2139,44 @@ void ThunkCreator::mergeThunks(ArrayRef<OutputSection *> outputSections) {
...
+        SectContents.drop_front(rel.offset - (i + 1) * 4);
+    ::memcpy(&instWord, InstWordContents.data(), sizeof(instWord));
```
Comment (MaskRay) [inline lld/ELF/Relocations.cpp]: `::memcpy` => `memcpy`

File: lld/ELF/Relocations.cpp (hunk 20 above)
Comment (androm3da) [reply lld/ELF/Relocations.cpp]: ok - will do.   And s/SectContents/data/

**Comment by MaskRay** [comment]
I expect some explanation in the description, about why thunks are needed and what relocations trigger thunks.

File: lld/test/ELF/hexagon-thunk-range-plt.s [hunk 22]
```diff
@@ -0,0 +1,75 @@
...
+# CHECK-NEXT:    { immext(#0x20080)
+# CHECK-NEXT:      r28 = add(pc,##0x200b8) }
+# CHECK-NEXT:    { r14 -= add(r28,#0x10)
+# CHECK-NEXT:      r15 = memw(r28+#0x8)
+# CHECK-NEXT:      r28 = memw(r28+#0x4) }
+# CHECK-NEXT:    { r14 = asr(r14,#0x2)
+# CHECK-NEXT:      jumpr r28 }
+# CHECK-NEXT:    { trap0(#0xdb) }
+
+# CHECK: 00220250 <extern_within_range@plt>:
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunk-range-plt.s]: As mentioned in another review, prefer omitting the address for the `<...>:` line and checking the address for the next line. This ensure good FileCheck diagnostics when things go off.

I had to adjust many tests when I made generic layout changes in the past, and testing not adopting this convention took me a lot of time to update.

File: lld/ELF/Relocations.cpp (hunk 21 above)
Comment (androm3da) [reply lld/ELF/Relocations.cpp]: fixed

File: lld/test/ELF/hexagon-thunk-range-plt.s (hunk 22 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunk-range-plt.s]: fixed

**Comment by androm3da** [comment]
@MaskRay if this makes sense to land on `main`, I'd like to see if I can cherry-pick it to `release/21.x` afterwards.

File: lld/ELF/Arch/Hexagon.cpp [hunk 23]
```diff
@@ -258,6 +265,47 @@ static uint32_t findMaskR16(Ctx &ctx, uint32_t insn) {
...
+  case R_HEX_B22_PCREL:
+  case R_HEX_PLT_B22_PCREL:
+  case R_HEX_GD_PLT_B22_PCREL:
+  case R_HEX_LD_PLT_B22_PCREL:
+  case R_HEX_B15_PCREL:
+  case R_HEX_B13_PCREL:
+  case R_HEX_B9_PCREL:
+    return !ctx.target->inBranchRange(type, branchAddr, s.getVA(ctx, a));
+  default:
+    // For unsupported relocation types, no thunk is needed
```
Comment (MaskRay) [inline lld/ELF/Arch/Hexagon.cpp:304]: Delete this comment. It doesn't convey additional meaning beside the previous comment.

File: lld/test/ELF/hexagon-thunks.s [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+.section .text_high, "ax", %progbits
+    .globl myfn
+    .type  myfn, @function
+myfn:
+    jumpr r31
+    .size  myfn, .-myfn
+
+# CHECK:  Disassembly of section .text_low:
+
+# CHECK:  000200b4 <__hexagon_thunk_myfn_from_.text.thunk>:
```
Comment (MaskRay) [inline lld/test/ELF/hexagon-thunks.s:32]: Move the address from the `<...>:` line to the next line

File: lld/ELF/Thunks.cpp (hunk 19 above)
Comment (androm3da) [reply lld/ELF/Thunks.cpp]: It was...sorry!  Removed for real now in 44bfa0463657b0abf34190eb491cdbf41b3bf50d

File: lld/ELF/Arch/Hexagon.cpp (hunk 23 above)
Comment (androm3da) [reply lld/ELF/Arch/Hexagon.cpp]: Deleted in 44bfa0463657b0abf34190eb491cdbf41b3bf50d

File: lld/test/ELF/hexagon-thunks.s (hunk 24 above)
Comment (androm3da) [reply lld/test/ELF/hexagon-thunks.s:32]: Somehow I encountered some puzzling-to-me failures when I made this change.  I'll sort it out and push an update when I have it addressed.

**Comment by androm3da** [comment]
Unfortunately I had to rebase this PR in order to effectively test it after ac7ceb3dabfa landed.  I've made the changes to the test cases to handle the new output from `llvm-objdump`.

**Review by MaskRay — APPROVED** [review]

**Comment by alexrp** [comment]
Nice! Thanks for getting this done. I'll resume the Hexagon port of Zig once we land the LLVM 21 upgrade.
