### PR TITLE
Reapply "[X86] Correct 32-bit immediate assertion and fix 64-bit lowering for huge frame offsets"

### LINKED ISSUE #69365: clang++ crash: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed
When compiling the following program with `clang++ test.cpp -o exe`

```cpp
#include <iostream>

void may_throw() {
  while(true) {
    throw std::out_of_range("test");
  }
}

int main() { 
  try {
    may_throw();
    volatile int a[1000000000] = {};
    return 1/ (a[500000000] & 1);
  } catch (...) {
    return -1;
  }
}
```

I encountered the following crash

```
clang-18: /llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:900: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineBasicBlock::iterator, int, unsigned int, llvm::RegScavenger*) const: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
```

### LINKED ISSUE #106352: `llvm-clang-x86_64-expensive-checks-win` test fails in CI
https://lab.llvm.org/buildbot/#/builders/14/builds/1208

Now that #106290 has been resolved and the build is performed again it revealed a test failure:

```
******************** TEST 'LLVM :: CodeGen/X86/avx512f-large-stack.ll' FAILED ********************
Exit Code: 2
Command Output (stdout):
--
# RUN: at line 2
c:\a\llvm-clang-x86_64-expensive-checks-win\build\bin\llc.exe -O0 -mtriple=x86_64 -mattr=+avx512f -verify-machineinstrs < C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\test\CodeGen\X86\avx512f-large-stack.ll | c:\a\llvm-clang-x86_64-expensive-checks-win\build\bin\filecheck.exe C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\test\CodeGen\X86\avx512f-large-stack.ll --check-prefix=CHECK
# executed command: 'c:\a\llvm-clang-x86_64-expensive-checks-win\build\bin\llc.exe' -O0 -mtriple=x86_64 -mattr=+avx512f -verify-machineinstrs
# .---command stderr------------
# | Assertion failed: (!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!", file C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\Target\X86\X86RegisterInfo.cpp, line 963
# | PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
# | Stack dump:
# | 0.	Program arguments: c:\\a\\llvm-clang-x86_64-expensive-checks-win\\build\\bin\\llc.exe -O0 -mtriple=x86_64 -mattr=+avx512f -verify-machineinstrs
# | 1.	Running pass 'Function Pass Manager' on module '<stdin>'.
# | 2.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@f'
# | Exception Code: 0x80000003
# |  #0 0x00007ff7b9a39e2c HandleAbort C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\Support\Windows\Signals.inc:429:0
# |  #1 0x00007ffdd9c490ed (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xa90ed)
# |  #2 0x00007ffdd9c4ae49 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xaae49)
# |  #3 0x00007ffdd9c50c6f (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xb0c6f)
# |  #4 0x00007ffdd9c4eba1 (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xaeba1)
# |  #5 0x00007ffdd9c518af (C:\WINDOWS\SYSTEM32\ucrtbased.dll+0xb18af)
# |  #6 0x00007ff7b5eb7fb8 llvm::X86RegisterInfo::eliminateFrameIndex(class llvm::MachineInstrBundleIterator<class llvm::MachineInstr, 0>, int, unsigned int, class llvm::RegScavenger *) const C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\Target\X86\X86RegisterInfo.cpp:962:0
# |  #7 0x00007ff7b7d73bc0 `anonymous namespace'::PEI::replaceFrameIndices C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\CodeGen\PrologEpilogInserter.cpp:1559:0
# |  #8 0x00007ff7b7d73734 `anonymous namespace'::PEI::replaceFrameIndices C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\CodeGen\PrologEpilogInserter.cpp:1384:0
# |  #9 0x00007ff7b7d70d3e `anonymous namespace'::PEI::runOnMachineFunction C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\CodeGen\PrologEpilogInserter.cpp:293:0
# | #10 0x00007ff7b78eb41d llvm::MachineFunctionPass::runOnFunction(class llvm::Function &) C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\CodeGen\MachineFunctionPass.cpp:94:0
# | #11 0x00007ff7b81a3ab7 llvm::FPPassManager::runOnFunction(class llvm::Function &) C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1408:0
# | #12 0x00007ff7b81a3fc0 llvm::FPPassManager::runOnModule(class llvm::Module &) C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1454:0
# | #13 0x00007ff7b81a6e02 `anonymous namespace'::MPPassManager::runOnModule C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1523:0
# | #14 0x00007ff7b81a7d57 llvm::legacy::PassManagerImpl::run(class llvm::Module &) C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:541:0
# | #15 0x00007ff7b819cf2c llvm::legacy::PassManager::run(class llvm::Module &) C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1651:0
# | #16 0x00007ff7b3058ca5 compileModule C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\tools\llc\llc.cpp:742:0
# | #17 0x00007ff7b305a5e7 main C:\a\llvm-clang-x86_64-expensive-checks-win\llvm-project\llvm\tools\llc\llc.cpp:409:0
# | #18 0x00007ff7bbaae5e9 invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79:0
# | #19 0x00007ff7bbaae4ce __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
# | #20 0x00007ff7bbaae38e __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331:0
# | #21 0x00007ff7bbaae67e mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17:0
# | #22 0x00007ffdf2347374 (C:\WINDOWS\System32\KERNEL32.DLL+0x17374)
# | #23 0x00007ffdf275cc91 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4cc91)
```

This appears to be related to the existing issues #69365, #31315 , #25051 and #10860.

### LINKED ISSUE #113856: [FastISel]  "Requesting 64-bit offset in 32-bit immediate! failed."
# Description
The following code crashes X86 backend with "Requesting 64-bit offset in 32-bit immediate! failed."

# Minimal Reproduction
https://godbolt.org/z/KET7GezGa

## Code
```
; llc  -mtriple=x86_64 -O=0
@G = global i8 0

define dso_local i32 @main() #0 {
  %1 = alloca i32, align 4
  %G = getelementptr i8, ptr %1, i32 -2147483648
  store i32 0, ptr %G, align 4
  ret i32 0
}

```

## Stack Trace
```
llc: /root/llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:962: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineBasicBlock::iterator, int, unsigned int, llvm::RegScavenger*) const: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel -mtriple=x86_64 -O=0 <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@main'
 #0 0x0000000003ba5b58 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3ba5b58)
 #1 0x0000000003ba354c SignalHandler(int) Signals.cpp:0:0
 #2 0x00007c1c21642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007c1c216969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x00007c1c21642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x00007c1c216287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x00007c1c2162871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x00007c1c21639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x0000000001e7ecb2 llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>, int, unsigned int, llvm::RegScavenger*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x1e7ecb2)
 #9 0x0000000002cca2b0 (anonymous namespace)::PEI::runOnMachineFunction(llvm::MachineFunction&) PrologEpilogInserter.cpp:0:0
#10 0x0000000002b23cc9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#11 0x000000000311e950 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x311e950)
#12 0x000000000311ed01 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x311ed01)
#13 0x000000000311f5b7 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x311f5b7)
#14 0x000000000086ad7c compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#15 0x0000000000756966 main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x756966)
#16 0x00007c1c21629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#17 0x00007c1c21629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#18 0x0000000000861a8e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x861a8e)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### LINKED ISSUE #121932: [clang] Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed
code:
```c
static int i = 0;
int main(void) {
  char s[] = "t";
  extern int putchar(int);
  putchar(s[-2147483648]);
  return 0;
}
```
just crash on trunk with assertion enabled.
https://godbolt.org/z/YPhYYYTjz
Generated by fuzzing
I didn't find any similar issues.

<details><summary><strong>Backtrace</strong></summary>
<p>

```
clang: /root/llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:971: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineBasicBlock::iterator, int, unsigned int, llvm::RegScavenger*) const: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -x c -std=c2x -c <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@main'
 #0 0x0000000003c71738 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3c71738)
 #1 0x0000000003c6f444 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3c6f444)
 #2 0x0000000003bbc988 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000711bd5a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000711bd5a969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000711bd5a42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000711bd5a287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000711bd5a2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000711bd5a39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000000000263e262 llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>, int, unsigned int, llvm::RegScavenger*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x263e262)
#10 0x000000000313391c (anonymous namespace)::PEI::runOnMachineFunction(llvm::MachineFunction&) PrologEpilogInserter.cpp:0:0
#11 0x0000000002fbd179 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#12 0x00000000035c6cff llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x35c6cff)
#13 0x00000000035c70b1 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x35c70b1)
#14 0x00000000035c7951 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x35c7951)
#15 0x0000000003f285b2 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f285b2)
#16 0x000000000460209e clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x460209e)
#17 0x000000000660f9cc clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x660f9cc)
#18 0x0000000004602478 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4602478)
#19 0x00000000048be799 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x48be799)
#20 0x0000000004840e2e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4840e2e)
#21 0x00000000049abb8e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49abb8e)
#22 0x0000000000ce93ef cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xce93ef)
#23 0x0000000000ce0e8a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#24 0x0000000004647ae9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#25 0x0000000003bbce34 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3bbce34)
#26 0x00000000046480df clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#27 0x000000000460c1ed clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x460c1ed)
#28 0x000000000460d26e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x460d26e)
#29 0x0000000004614d95 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4614d95)
#30 0x0000000000ce6233 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xce6233)
#31 0x0000000000bb2524 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbb2524)
#32 0x0000711bd5a29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#33 0x0000711bd5a29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#34 0x0000000000ce0935 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xce0935)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134

```

</p>
</details>

### PR DESCRIPTION
**Pull request by wesleywiser**
The first commit is identical to 69bec0afbb8f2aa0021d18ea38768360b16583a9.

The second commit fixes the instruction verification failures by replacing the erroneous instruction with a trap after the error is reported and adds `-verify-machineinstrs` to the tests added in the original PR to catch the issue sooner.

After that change, all tests pass with both `LLVM_ENABLE_EXPENSIVE_CHECKS={On,Off}`.

cc @RKSimon @e-kud @phoebewang @arsenm as reviewers on the original PR

### CODE REVIEW

**Review by phoebewang — APPROVED** [review]
LGTM.

File: llvm/lib/Target/X86/X86RegisterInfo.cpp [hunk 1]
```diff
@@ -958,11 +959,41 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+
+      MI.getOperand(FIOperandNum + 3).setImm(0);
+      MI.getOperand(FIOperandNum + 2).setReg(ScratchReg);
+
+      return false;
+    }
+
+    // ... for 32-bit targets, this is a bug!
+    if (!Is64Bit && !FitsIn32Bits) {
+      MI.emitGenericError(("64-bit offset calculated but target is 32-bit"));
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86RegisterInfo.cpp:991]:
```suggestion
      MI.emitGenericError("64-bit offset calculated but target is 32-bit");
```

Comment (arsenm) [reply llvm/lib/Target/X86/X86RegisterInfo.cpp:991]: Maybe should use DiagnosticInfoResourceLimit instead of a custom error message

Comment (wesleywiser) [reply llvm/lib/Target/X86/X86RegisterInfo.cpp]: Removed the extra parens. The message generated by `DiagnosticInfoResourceLimit` doesn't immediately seem better to me but I can switch to use that if you want me to.

**Comment by wesleywiser** [comment]
ping @RKSimon if you want to take a look at this revision

**Review by RKSimon — APPROVED** [review]
LGTM - cheers
