### PR TITLE
[mlir][transform] Guard parametric loop tiling pass from no option

### LINKED ISSUE #61716: [MLIR]`test-extract-fixed-outer-loops` pass with no option leads to Assertion Failure '!empty()'
I think a default value of `test-outer-loop-sizes` should be set to avoid this crash.

Test commit: https://github.com/llvm/llvm-project/commit/938deaad8ac92d9a45db8ef2d8a71fbf04958d90

steps to reproduce:

```shell
mlir-opt test.mlir -test-extract-fixed-outer-loops
```
test case:

```mlir
  func.func @main(%arg0: memref<?x?xf32>) {
    %c2 = arith.constant 2 : index
    %c44 = arith.constant 44 : index
    %c1 = arith.constant 1 : index
    scf.for %arg1 = %c2 to %c44 step %c1 {
      scf.for %arg2 = %c1 to %c44 step %c2 {
        %0 = memref.load %arg0[%arg1, %arg2] : memref<?x?xf32>
      }
    }
    return
  }
```
crash trace:
```console
mlir-opt: /home/ty/llvm-project/llvm/include/llvm/ADT/SmallVector.h:312: T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::back() [with T = mlir::scf::ForOp; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::reference = mlir::scf::ForOp&]: Assertion `!empty()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/ty/llvm-project/build/bin/mlir-opt test.mlir -test-extract-fixed-outer-loops
 #0 0x0000563a9a8452fa llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ty/llvm-project/build/bin/mlir-opt+0x2282fa)
 #1 0x0000563a9a84258c SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fe71745d980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #3 0x00007fe71610ee87 raise /build/glibc-CVJwZb/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #4 0x00007fe7161107f1 abort /build/glibc-CVJwZb/glibc-2.27/stdlib/abort.c:81:0
 #5 0x00007fe7161003fa __assert_fail_base /build/glibc-CVJwZb/glibc-2.27/assert/assert.c:89:0
 #6 0x00007fe716100472 (/lib/x86_64-linux-gnu/libc.so.6+0x30472)
 #7 0x0000563a9b3dc817 mlir::extractFixedOuterLoops(mlir::scf::ForOp, llvm::ArrayRef<long>) (/home/ty/llvm-project/build/bin/mlir-opt+0xdbf817)
 #8 0x0000563a9bdba764 _ZN4llvm12function_refIFvPN4mlir9OperationEEE11callback_fnIZNS1_6detail4walkILNS1_9WalkOrderE1ENS1_15ForwardIteratorEZN12_GLOBAL__N_130SimpleParametricLoopTilingPass14runOnOperationEvEUlNS1_3scf5ForOpEE_SE_vEENSt9enable_ifIXaantsrSt11disjunctionIJSt7is_sameIT2_S3_ESI_ISJ_PNS1_6RegionEESI_ISJ_PNS1_5BlockEEEE5valuesrSI_IT3_vE5valueESS_E4typeES3_OT1_EUlS3_E_EEvlS3_ TestLoopParametricTiling.cpp:0:0
 #9 0x0000563a9bdba549 void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) (.constprop.191) TestLoopParametricTiling.cpp:0:0
#10 0x0000563a9bdba8e5 (anonymous namespace)::SimpleParametricLoopTilingPass::runOnOperation() TestLoopParametricTiling.cpp:0:0
#11 0x0000563a9c13e08e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/ty/llvm-project/build/bin/mlir-opt+0x1b2108e)
#12 0x0000563a9c13eee3 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (.constprop.510) Pass.cpp:0:0
#13 0x0000563a9c13f56d mlir::PassManager::run(mlir::Operation*) (/home/ty/llvm-project/build/bin/mlir-opt+0x1b2256d)
#14 0x0000563a9c1334e3 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#15 0x0000563a9c133bb1 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPool*) MlirOptMain.cpp:0:0
#16 0x0000563a9c133da1 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#17 0x0000563a9c2006f0 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/home/ty/llvm-project/build/bin/mlir-opt+0x1be36f0)
#18 0x0000563a9c12eec3 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/home/ty/llvm-project/build/bin/mlir-opt+0x1b11ec3)
#19 0x0000563a9c1316ee mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&, bool) (/home/ty/llvm-project/build/bin/mlir-opt+0x1b146ee)
#20 0x0000563a9a8112f0 main (/home/ty/llvm-project/build/bin/mlir-opt+0x1f42f0)
#21 0x00007fe7160f1c87 __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:344:0
#22 0x0000563a9a82414a _start (/home/ty/llvm-project/build/bin/mlir-opt+0x20714a)
```

### LINKED ISSUE #116360: [MLIR]`-test-extract-fixed-outer-loops` triggers Assertion Failure `!empty()'
Test on commit: https://github.com/llvm/llvm-project/commit/6548b6354d1d990e1c98736f5e7c3de876bedc8e
steps to reproduce:
```
mlir-opt test.mlir  --test-extract-fixed-outer-loops
```
test case:
```
module {
  func.func @main(%arg0: tensor<4xi32>) -> () {
    %c4 = arith.constant 4 : index
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %2 = bufferization.to_memref %arg0 : memref<4xi32>
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<4xi32>
    scf.for %arg4 = %c0 to %c4 step %c1 {
      %19 = memref.load %2[%arg4] : memref<4xi32>
      %20 = math.ctlz %19 : i32
      memref.store %20, %alloc[%arg4] : memref<4xi32>
    }
    return
  }
}
```
crash trace:
```
mlir-opt: /home/workdir/llvm-project-19/llvm/include/llvm/ADT/SmallVector.h:309: reference llvm::SmallVectorTemplateCommon<mlir::scf::ForOp>::back() [T = mlir::scf::ForOp]: Assertion `!empty()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./mlir-opt /home/workdir/test.mlir --test-extract-fixed-outer-loops
^[[A #0 0x000055c40f1e53b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./mlir-opt+0x10723b8)
 #1 0x000055c40f1e2ede llvm::sys::RunSignalHandlers() (./mlir-opt+0x106fede)
 #2 0x000055c40f1e5dc8 SignalHandler(int) Signals.cpp:0:0
 #3 0x000070577cebe520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000070577cf129fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000070577cebe476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000070577cea47f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000070577cea471b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000070577ceb5e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000055c41100ce2a mlir::extractFixedOuterLoops(mlir::scf::ForOp, llvm::ArrayRef<long>) (./mlir-opt+0x2e99e2a)
#10 0x000055c411ef97b5 void llvm::function_ref<void (mlir::Operation*)>::callback_fn<std::enable_if<!llvm::is_one_of<mlir::scf::ForOp, mlir::Operation*, mlir::Region*, mlir::Block*>::value && std::is_same<void, void>::value, void>::type mlir::detail::walk<(mlir::WalkOrder)1, mlir::ForwardIterator, (anonymous namespace)::SimpleParametricLoopTilingPass::runOnOperation()::'lambda'(mlir::scf::ForOp), mlir::scf::ForOp, void>(mlir::Operation*, (anonymous namespace)::SimpleParametricLoopTilingPass::runOnOperation()::'lambda'(mlir::scf::ForOp)&&)::'lambda'(mlir::Operation*)>(long, mlir::Operation*) TestLoopParametricTiling.cpp:0:0
#11 0x000055c40f2f371e void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) (./mlir-opt+0x118071e)
#12 0x000055c40f2f371e void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) (./mlir-opt+0x118071e)
#13 0x000055c411ef95dd (anonymous namespace)::SimpleParametricLoopTilingPass::runOnOperation() TestLoopParametricTiling.cpp:0:0
#14 0x000055c4124616df mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./mlir-opt+0x42ee6df)
#15 0x000055c412461ec2 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./mlir-opt+0x42eeec2)
#16 0x000055c41246466e mlir::PassManager::run(mlir::Operation*) (./mlir-opt+0x42f166e)
#17 0x000055c41245d192 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#18 0x000055c41245cdfb llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#19 0x000055c412506ae5 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./mlir-opt+0x4393ae5)
#20 0x000055c412457ff2 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./mlir-opt+0x42e4ff2)
#21 0x000055c4124582a3 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x42e52a3)
#22 0x000055c4124584b2 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./mlir-opt+0x42e54b2)
#23 0x000055c40f1c45d7 main (./mlir-opt+0x10515d7)
#24 0x000070577cea5d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#25 0x000070577cea5e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#26 0x000055c40f1c4145 _start (./mlir-opt+0x1051145)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Lewuathe**
`test-extract-fixed-outer-loops` pass always crash without any `test-outer-loop-sizes` option. We need to keep the pass from crash by checking the option existence. 

Fix https://github.com/llvm/llvm-project/issues/61716, https://github.com/llvm/llvm-project/issues/116360

### CODE REVIEW

File: mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp [hunk 1]
```diff
@@ -40,6 +40,9 @@ class SimpleParametricLoopTilingPass
   }
 
   void runOnOperation() override {
+    // If no outer loop iteration is given, ignore the pass.
+    if (sizes.empty())
+      return;
```
Comment (joker-eph) [inline mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp:45]: Shouldn't we error out here? Seems like an error from the user to me here, and they would be surprised by the behavior. Any valid workflow where silently ignoring this would be better?

Comment (Lewuathe) [reply mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp:45]: @joker-eph Thanks for the feedback. Since it's the invalid input from the user, it should have thrown error instead of ignoring as you suggested. I'll try to change it.

File: mlir/test/Transforms/invalid-outer-loop-size.mlir [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+func.func @no_crash(%arg0: memref<?x?xf32>) {
+  // expected-error@-5 {{expect non-empty outer loop sizes}}
+  %c2 = arith.constant 2 : index
+  %c44 = arith.constant 44 : index
+  %c1 = arith.constant 1 : index
+  scf.for %i = %c2 to %c44 step %c1 {
+    scf.for %j = %c1 to %c44 step %c2 {
+      memref.load %arg0[%i, %j]: memref<?x?xf32>
+    }
+  }
```
Comment (joker-eph) [inline mlir/test/Transforms/invalid-outer-loop-size.mlir:13]: The body could just be empty right?

File: mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp [hunk 3]
```diff
@@ -40,6 +40,11 @@ class SimpleParametricLoopTilingPass
   }
 
   void runOnOperation() override {
+    if (sizes.empty()) {
+      getOperation()->emitError("expect non-empty outer loop sizes");
```
Comment (joker-eph) [inline mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp:44]: I wouldn't use `getOperation()` because we don't need to attach any IR-related context.

I would also make the error message more clear on the fact that the error is about pass-options.

```suggestion
      emitError(UnknownLoc::get(getContext()), "missing `" + getArgument() + "` pass-option for outer loop sizes");
```

**Review by joker-eph — APPROVED** [review]

File: mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp (hunk 3 above)
Comment (Lewuathe) [reply mlir/test/lib/Dialect/SCF/TestLoopParametricTiling.cpp]: @joker-eph 
When I use the unknown location here, the `expected-error` does not work as expected. The `verify-diagnostics` always prints the error message even if it matches. Is that the limitation of the error verification? Is there anything we can do as a workaround for that?

```
/Users/sasaki/dev/llvm-project/build/bin/mlir-opt -test-extract-fixed-outer-loops /Users/sasaki/dev/llvm-project/mlir/test/Transforms/invalid-outer-loop-size.mlir -verify-diagnostics
<unknown>:0: error: unexpected error: missing `test-outer-loop-sizes` pass-option for outer loop sizes
```
