### PR TITLE
[MemCpyOpt] fix miscompile for non-dominated use of src alloca for stack-move optimization

### LINKED ISSUE #65225: memcpyopt: Instruction does not dominate all uses!
```llvm
define i32 @f(ptr %G.9, i64 %0) {
  %A = alloca i1, align 1
  %G = getelementptr i64, ptr %A, i64 -1
  %u = load i8, ptr %G, align 1
  %v = alloca i8, align 4
  %x = load i1, ptr %v, align 4
  %y = getelementptr double, ptr %G, i64 %0
  store i1 %x, ptr %A, align 1
  store i8 %u, ptr %G.9, align 1
  store i1 false, ptr %y, align 1
  ret i32 0
}
```

https://godbolt.org/z/PbMz8asfa

```
Instruction does not dominate all uses!
  %v = alloca i8, align 4
  %G = getelementptr i64, ptr %v, i64 -1
LLVM ERROR: Broken module found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -passes=default<O1> <source>
 #0 0x00000000034b5ac8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x34b5ac8)
 #1 0x00000000034b31fc SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f1d39020420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f1d38ae300b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f1d38ac2859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x0000000000784487 (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x784487)
 #6 0x0000000003405ee8 (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x3405ee8)
 #7 0x0000000002e4add3 (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2e4add3)
 #8 0x000000000087c49e llvm::detail::PassModel<llvm::Module, llvm::VerifierPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x87c49e)
 #9 0x0000000002e108fc llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2e108fc)
#10 0x000000000088648a llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x88648a)
#11 0x000000000078f761 main (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x78f761)
#12 0x00007f1d38ac4083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#13 0x000000000087b80e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x87b80e)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by khei4**
Stack-move optimization, the optimization that merges src and dest alloca of the full-size copy, replaces all uses of the dest alloca with src alloca. For safety, we needed to check all uses of the dest alloca locations are dominated by src alloca, to be replaced. This PR adds the check for that. 

Fixes #65225

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp [hunk 1]
```diff
@@ -1481,28 +1481,35 @@ bool MemCpyOptPass::performStackMoveOptzn(Instruction *Load, Instruction *Store,
     Worklist.push_back(AI);
     unsigned MaxUsesToExplore = getDefaultMaxUsesToExploreForCaptureTracking();
     Worklist.reserve(MaxUsesToExplore);
-    SmallSet<const Use *, 20> Visited;
+    SmallSet<Instruction *, 20> Visited;
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp:1484]: Why did this get switched from Use to Instruction?

Comment (khei4) [reply llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp:1484]: Ah, ... Sorry, that was style noises, I thought it'd be neat to handle Instruction type uniformly if it can be used, (although the const modifier is dropped...). I could revert this because of no rationale for improvements.

File: llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp [hunk 2]
```diff
@@ -1486,6 +1486,14 @@ bool MemCpyOptPass::performStackMoveOptzn(Instruction *Load, Instruction *Store,
       Instruction *I = Worklist.back();
       Worklist.pop_back();
       for (const Use &U : I->uses()) {
+        auto *UI = cast<Instruction>(U.getUser());
+        // If any use that isn't dominated by SrcAlloca exists, non-dominating
+        // uses will be produced.
+        if (!DT->dominates(SrcAlloca, UI)) {
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/MemCpyOptimizer.cpp:1492]: Add a TODO that we could move the SrcAlloca up instead.

**Review by nikic — APPROVED** [review]
LGTM as a conservative fix.
