### PR TITLE
[DirectX]  Start the creation of a DXIL Instruction legalizer

### LINKED ISSUE #126323: [DX] LLVM Optimizations may generate invalid integer types
Given the example below:

```hlsl
export int fn(float ColorIdx) {
  int ColorIdx1 = (int)ColorIdx % 8;
  return (ColorIdx1 + 1) % 8;
}
```
[Godbolt](https://godbolt.org/z/Ecj5bbcfo)

LLVM's Correlated Value Propagation pass reduces the i32 values to i8 since the are constrained to that value space. This results in generation of invalid DXIL.

We need to figure out how we want to handle this. It probably makes the most sense to have a legalization pass late that up-converts to the smallest supported integer sizes based on the compiler settings.

AC:
* come up with a plan to address this
  * option 1: rely on globalisel
  * option 2: add a legalization pass
  * ~~option 3: play whack-a-mole~~

### LINKED ISSUE #129757: [DirectX] Re-evaluate pass ordering for producing correct DXIL module flags
According to #120119, the DXIL Shader Flags pass needs to be executed before the DXIL Op Lowering pass in order to simplify its implementation by being able to work directly with DirectX target intrinsics. However, this dependency creates a challenge, as the shader flag analysis is based on instructions that may not exist after the lowering pass.

This issue was discovered with the implementation of the Int64Ops Shader Flags Analysis and the resulting DXIL failing validation by `dxv` due to mismatched flags (https://github.com/llvm/llvm-project/pull/129089#issuecomment-2695570866). The Shader Flags Analysis currently enables the Int64Ops shader flag in the presence of `extractelement` instructions introduced by the Scalarizer pass. These `extractelement` instructions are subsequently be removed by the DXIL Op Lowering pass. 

```hlsl
RWBuffer<float4> In : register(u0, space0);
RWBuffer<float4> Out : register(u1, space4);

[numthreads(1,1,1)]
void main(uint GI : SV_GroupIndex) {
  Out[GI] = In[GI] * In[GI];
}
```

```
> clang-dxc -T cs_6_0 -Fo simple.dxil simple.hlsl
error: Flags must match usage.
note: Flags declared=1056768, actual=8192
Validation failed.

clang-dxc: error: dxv command failed with exit code 1 (use -v to see invocation)
```
For reference: 1056768 is 0x00102000, and 8192 is 0x00002000.
0x00100000 corresponds to the Int64Ops DXIL module flag.
0x00002000 corresponds to the TypedUAVLoadAdditionalFormats DXIL module flag.
The Int64Ops flag is being set due to `extractelement` instructions with i64 indices introduced by the Scalarizer pass.
The setting of the TypedUAVLoadAdditionalFormats flag relies on the presence of DirectX target intrinsics before DXIL Op Lowering, which occurs after Scalarization.

Are there other shader flags that could produce incorrect results when performed before DXIL Op Lowering?
- Probably not; issues like with the int64ops are likely to be one-offs

Potential Solutions:

1. Perform Shader Flag Analysis before Scalarization: This would ensure that the `extractelement` and `insertelement` instructions from the scalarizer are not yet introduced, thereby avoiding the need to account for their removal later. But it may impact the implementation of current and/or future Shader Flag Analyses. There may also be other sources of i64s we have not accounted for.

2. Split the Shader Flag Analysis into two stages: one before the DXIL Op Lowering Pass and one after. This would also require moving the DXIL Translate Metadata pass to follow after the later Shader Flag Analysis. Shader Flag Analyses that benefit from the DirectX target intrinsics could be performed before DXIL Op Lowering, and the Shader Flag Analyses that don't benefit from that should be performed after DXIL Op Lowering.

3. Complicate the logic for the Int64Ops Shader Flag Analysis: Detect when an instruction returning an i64 or using i64 operands will be removed by a subsequent DXIL Op Lowering pass. This would probably be very ugly.

4. Modify the Scalarizer pass use i32 for `extractelement` and `insertelement` indices instead of i64

5. Modify the IRBuilder to default to i32-typed indices when constructing ExtractElement and InsertElement instructions

6. Make the Int64Ops Shader Flag Analysis ignore constant i64 operands whose values fit within the range of an i32.

7. Add a pass to convert i64 indices into i32 for `extractelement` and `insertelement` (after scalarization and before metadata analysis).

Chosen Solution: 7

### PR DESCRIPTION
**Pull request by farzonl**
- Legalize i8 truncation back to original types
-  remove sext and truncs
- Legalize i64 indicies for insert\extract elements to i32 indicies
- fixes https://github.com/llvm/llvm-project/issues/126323
- fixes https://github.com/llvm/llvm-project/issues/129757

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+        MadeChanges = LegalizationFn(I, ToRemove, ReplacedValues);
+      }
+    }
+    while (!ToRemove.empty()) {
+      Instruction *I = ToRemove.top();
+      I->eraseFromParent();
+      ToRemove.pop();
+    }
+
+    return MadeChanges;
```
Comment (joaosaffran) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:153]: nit: Shouldn't we return true if any of the `LegalizationFn` functions in the pipeline return true? 

For example, if I have 3 functions in the pipeline and their returns in sequence were: `false`, `true`, `false`, this function seems to be returning `false`, when it should be `true`, IMHO. 

Please let me know if I miss understood something

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:154]: its suppose to be `MadeChanges |= .. ;` not `MadeChanges = .. ;` I have that change staged, its coming after I fix a different bug first.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+      ReplacedValues[Trunc] = Trunc->getOperand(0);
+      ToRemove.push(Trunc);
+    }
+  } else if (I.getType()->isIntegerTy(8) ||
+             (Cmp && Cmp->getOperand(0)->getType()->isIntegerTy(8))) {
+    IRBuilder<> Builder(&I);
+
+    std::vector<Value *> NewOperands;
+    Type *InstrType = IntegerType::get(I.getContext(), 32);
+    for (unsigned OpIdx = 0; OpIdx < I.getNumOperands(); ++OpIdx) {
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:49]: so that we don't have to force int32  on all immediates, we need to add another for loop here that trys to set InstrType

File: llvm/test/CodeGen/DirectX/legalize-i8.ll [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+  ; CHECK-NOT: sext i8
+  %1 = trunc nsw i16 %a to i8
+  %2 = sub i8 0, %1
+  %3 = sext i8 %2 to i16
+  ret i16 %3
+}
+
+define i32 @all_imm() {
+  ; CHECK-LABEL: define i32 @all_imm(
+  ; CHECK-NOT: trunc
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/legalize-i8.ll:103]: delete no trunc in this case.

**Review by Icohedron — APPROVED** [review]
Looks good aside from the nits I had on the code comments.
I also rebased my int64ops branch to this PR and found that it does properly fix the dxil validation issues.

**Review by inbelic — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 4]
```diff
@@ -0,0 +1,212 @@
...
+      Value *Insert32Index = Builder.CreateInsertElement(
+          Insert->getOperand(0), Insert->getOperand(1), Idx32,
+          Insert->getName());
+
+      Insert->replaceAllUsesWith(Insert32Index);
+      ToRemove.push(Insert);
+    }
+  }
+
+  return !ToRemove.empty();
```
[the remark this answers is not in the document]
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:141]: The boolean is needed for `PreservedAnalyses::all();` in `DXILLegalizePass::run` but given your comment I think it makes the most sense to make the function we use as lambdas void return statements and just check the `ToRemove` vector size in `runLegalizationPipeline`. `runLegalizationPipeline` is really the only function that needs to be a bool return.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 5]
```diff
@@ -0,0 +1,209 @@
...
+#include <vector>
+
+#define DEBUG_TYPE "dxil-legalize"
+
+using namespace llvm;
+namespace {
+
+static void fixI8TruncUseChain(Instruction &I,
+                               std::stack<Instruction *> &ToRemove,
+                               std::map<Value *, Value *> &ReplacedValues) {
```
Comment (llvm-beanz) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:34]: llvm::DenseMap should almost always be used instead of std::map.
see: https://llvm.org/docs/CodingStandards.html#c-standard-library

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+      for (auto &LegalizationFn : LegalizationPipeline) {
+        LegalizationFn(I, ToRemove, ReplacedValues);
+      }
+    }
+    bool MadeChanges = !ToRemove.empty();
+
+    while (!ToRemove.empty()) {
+      Instruction *I = ToRemove.top();
+      I->eraseFromParent();
+      ToRemove.pop();
```
[the remark this answers is not in the document]
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:158]: I do need a stack because most the i8 cases can’t use replaceAllUsesWith because the instruction types are different. My work around is to remove starting from the last instruction we saw so that  there are no uses when we call eraseFromParent

[the remark this answers is not in the document]
Comment (llvm-beanz) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:158]: You don't need a stack for that. You can reverse iterate a SmallVector: `for (auto *Inst : reverse(ToRemove))`

[the remark this answers is not in the document]
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:158]: So the list size isn't  huge so this probably doesn't matter, but reverse would be applying [std::iter_swap](https://en.cppreference.com/w/cpp/algorithm/iter_swap) to every pair of iterators thats O(n) + O(n) for erasing vs just O(n). I'm guessing the `SmallVector` benefits outweigh this.

[the remark this answers is not in the document]
Comment (llvm-beanz) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:158]: `llvm::reverse` creates a range iterator with reverse iterators, not `std::iter_swap`, so it is O(n):

https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/STLExtras.h#L428

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 7]
```diff
@@ -0,0 +1,209 @@
...
+#include <map>
+#include <stack>
+#include <vector>
+
+#define DEBUG_TYPE "dxil-legalize"
+
+using namespace llvm;
+namespace {
+
+static void fixI8TruncUseChain(Instruction &I,
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:32]: I find the nesting in this function hard to follow, especially since the longest case is in the middle. Since all of the instruction types are mutually exclusive, do you think it would read better to structure it like:
```c++
  if (auto *Trunc = dyn_cast<TruncInst>(&I)) {
    // ...
    return;
  }

  if (auto *Cast = dyn_cast<CastInst>(&I)) {
    // ...
    return;
  }

  auto *Cmp = dyn_cast<CmpInst>(&I);
  if (!I.getType()->isIntegerTy(8) &&
      !(Cmp && Cmp->getOperand(0)->getType()->isIntegerTy(8)))
    // Nothing to do...
    return;

  // ...
```

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 8]
```diff
@@ -0,0 +1,209 @@
...
+  } else if (I.getType()->isIntegerTy(8) ||
+             (Cmp && Cmp->getOperand(0)->getType()->isIntegerTy(8))) {
+    IRBuilder<> Builder(&I);
+
+    std::vector<Value *> NewOperands;
+    Type *InstrType = IntegerType::get(I.getContext(), 32);
+    for (unsigned OpIdx = 0; OpIdx < I.getNumOperands(); ++OpIdx) {
+      Value *Op = I.getOperand(OpIdx);
+      if (ReplacedValues.count(Op))
+        InstrType = ReplacedValues[Op]->getType();
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:52]: Is it possible to get conflicting InstrTypes here? Does this deserve an assert?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 9]
```diff
@@ -0,0 +1,209 @@
...
+    for (unsigned OpIdx = 0; OpIdx < I.getNumOperands(); ++OpIdx) {
+      Value *Op = I.getOperand(OpIdx);
+      if (ReplacedValues.count(Op))
+        NewOperands.push_back(ReplacedValues[Op]);
+      else if (auto *Imm = dyn_cast<ConstantInt>(Op)) {
+        APInt Value = Imm->getValue();
+        unsigned NewBitWidth = InstrType->getIntegerBitWidth();
+        // Note: options here are sext or sextOrTrunc.
+        // Since i8 isn't supported, we assume new values
+        // will always have a higher bitness.
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp:63]: An assert to document/enforce the assumption wouldn't hurt

**Review by bogner — COMMENTED** [review]
A fairly minor style comment and a couple places we could probably add asserts that are probably worth doing if you're planning on more updates in the area.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 7 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp:32]: I think i have something cleaner let me know in the new pr.
