### PR TITLE
[MLIR][Linalg] Harden parsing Linalg named ops

### LINKED ISSUE #129185: [mlir][linalg] Crash parsing `linalg.elemwise_unary`
`mlir-opt` crashes when trying to parse/build ` linalg.elemwise_unary`, the unreachable is being hit in `ElemwiseUnaryOp::regionBuilder`

Reproducer:
```mlir
func.func @main(%arg0 : tensor<?xi32>) -> tensor<?xfi32> {
  %0 = linalg.elemwise_unary ins(%arg0 : tensor<?xi32>) outs(%arg0 : tensor<?xi32>) -> tensor<?xi32>
  return %0 : tensor<?xi32>
}
```

Truncated stack-trace:
```
unsupported non numeric type
UNREACHABLE executed at /home/nod/llvm-project/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:421!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
#11 0x00005bd2e86a9532 (anonymous namespace)::RegionBuilderHelper::buildUnaryFn(mlir::linalg::UnaryFn, mlir::Value) /home/nod/llvm-project/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:0:7
#12 0x00005bd2e86a93f3 mlir::linalg::ElemwiseUnaryOp::regionBuilder(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) /home/nod/llvm-project/build/Debug/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yamlgen.cpp.inc:123:25
#13 0x00005bd2e8865694 void std::__invoke_impl<void, void (*&)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>>(std::__invoke_other, void (*&)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:61:7
#14 0x00005bd2e886560d std::enable_if<is_invocable_r_v<void, void (*&)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>>, void>::type std::__invoke_r<void, void (*&)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>>(void (*&)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:117:5
#15 0x00005bd2e8865535 std::_Function_handler<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>), void (*)(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>::_M_invoke(std::_Any_data const&, mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:290:2
#16 0x00005bd2e8896661 std::function<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>::operator()(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) const /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591:2
#17 0x00005bd2e8896605 void llvm::function_ref<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>::callback_fn<std::function<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>>(long, mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) /home/nod/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:5
#18 0x00005bd2e88653b9 llvm::function_ref<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>::operator()(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) const /home/nod/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:69:5

```

Full stacktrace here: https://gist.github.com/IanWood1/8f4d9c3d613c81b7490cac37872e8fe4

Commit: 746d8b0740095ea3939fef0112a51953ca22cd29

### LINKED ISSUE #132740: [mlir] --mlir-print-stacktrace-on-diagnostic crashes
git version: 59fd2878fce470f02058f43d4b818ed68ce04094

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt  --mlir-print-stacktrace-on-diagnostic a.mlir`

a.mlir:  
``` 
#map = affine_map<(d0, d1) -> (d0 + d0 floordiv 8, d1 mod 8)>
#map1 = affine_map<(d0, d1) -> (d1 floordiv 8)>
module {
  spirv.func @simd_insert_scalar_misa(%arg0: i32, %arg1: i32, %arg2: i32) "None" {
    %0 = builtin.unrealized_conversion_cast %arg2 : i32 to index
    %1 = builtin.unrealized_conversion_cast %arg1 : i32 to index
    %2 = builtin.unrealized_conversion_cast %arg0 : i32 to index
    %c0 = arith.constant 0 : index
    %3 = arith.muli %2, %0 : index
    %4 = arith.muli %2, %1 : index
    %5 = affine.min #map(%3, %4)
    %6 = arith.muli %5, %0 : index
    %7 = arith.muli %5, %4 : index
    %8 = affine.apply #map1(%6, %7)
    scf.for %arg3 = %c0 to %8 step %6 {
      %9 = affine.min #map(%6, %7)
      %10 = affine.apply #map1(%5, %9)
      scf.for %arg4 = %c0 to %10 step %5 {
        %11 = affine.apply #map1(%4, %9)
        %12 = arith.muli %arg3, %11 : index
        "test.foo"(%12) : (index) -> ()
      }
      scf.for %arg4 = %11 to %10 step %9 {
        %13 = affine.apply #map1(%4, %12)
        %14 = arith.muli %arg3, %13 : index
        "test.foo"(%14) : (index) -> ()
      }
    }
    scf.for %arg3 = %8 to %5 step %6 {
      %9 = affine.min #map(%6, %7)
      %10 = affine.apply #map1(%5, %9)
      scf.for %arg4 = %c0 to %10 step %5 {
        %11 = affine.apply #map1(%4, %9)

``` 
stack trace:

``` 
tmp.dlbmYvtohM.mlir:33:41: error: expected operation name in quotes
        %11 = affine.apply #map1(%4, %9)
                                        ^
/data/szy/MLIR/seed/seed15/tmp.dlbmYvtohM.mlir:33:41: note: diagnostic emitted with trace:
 #0 0x0000559eedbb2db8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11bddb8)
 #1 0x0000559ef0cf8b0d emitDiag(mlir::Location, mlir::DiagnosticSeverity, llvm::Twine const&) Diagnostics.cpp:0:0
 #2 0x0000559ef0cf8931 mlir::emitError(mlir::Location, llvm::Twine const&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x4303931)
 #3 0x0000559ef3d17d0d mlir::detail::Parser::emitWrongTokenError(llvm::Twine const&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x7322d0d)
 #4 0x0000559ef3d1c62a (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
 #5 0x0000559ef3d269a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
 #6 0x0000559ef3d2485c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
 #7 0x0000559eefa0ea94 mlir::scf::ForOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x3019a94)
 #8 0x0000559ef3d1b7e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
 #9 0x0000559ef3d269a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#10 0x0000559ef3d2485c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#11 0x0000559eefa0ea94 mlir::scf::ForOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x3019a94)
#12 0x0000559ef3d1b7e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#13 0x0000559ef3d269a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#14 0x0000559ef3d2485c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#15 0x0000559ef3d22acc (anonymous namespace)::CustomOpAsmParser::parseOptionalRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#16 0x0000559ef0083557 mlir::spirv::FuncOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x368e557)
#17 0x0000559ef3d1b7e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#18 0x0000559ef3d269a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#19 0x0000559ef3d246d5 (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#20 0x0000559ef0cd9b9e mlir::ModuleOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x42e4b9e)
#21 0x0000559ef3d1b7e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#22 0x0000559ef3d1a5ad mlir::parseAsmSourceFile(llvm::SourceMgr const&, mlir::Block*, mlir::ParserConfig const&, mlir::AsmParserState*, mlir::AsmParserCodeCompleteContext*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x73255ad)
#23 0x0000559ef0bb9f0f mlir::parseSourceFile(std::shared_ptr<llvm::SourceMgr> const&, mlir::Block*, mlir::ParserConfig const&, mlir::LocationAttr*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c4f0f)
#24 0x0000559ef0bb8e8e mlir::parseSourceFileForTool(std::shared_ptr<llvm::SourceMgr> const&, mlir::ParserConfig const&, bool) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c3e8e)
#25 0x0000559ef0bb867f performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#26 0x0000559ef0bb83ed llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#27 0x0000559ef0c63275 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x426e275)
#28 0x0000559ef0bb2405 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd405)
#29 0x0000559ef0bb26af mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd6af)
#30 0x0000559ef0bb29de mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd9de)
#31 0x0000559eedb91337 main (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119c337)
#32 0x00007f0052599083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#33 0x0000559eedb90e9e _start (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119be9e)
```

### LINKED ISSUE #132755: [mlir] -split-input-file crashes
git version: 59fd2878fce470f02058f43d4b818ed68ce04094

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt  -split-input-file a.mlir`

a.mlir:  
``` 
module {
  func.func @add_dynamic(%arg0: memref<3x4x5xf32>, %arg1 : memref< 3x4x5xi32>, %arg2: memref<3x4x5xf32>, %arg3: memref<3x4x5xf32>) attributes {arm_streaming} {
    linalg.add ins(%arg0, %arg1 : memref<3x4x5xf32>, memref< 3x4x5xi32>) outs(%arg2 : memref<3x4x5xf32>)
    return
  }
}

``` 
stack trace:

``` 
unsupported non numeric type
UNREACHABLE executed at /data/szy/MLIR/llvm-project/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:467!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/szy/MLIR/llvm-project/install/bin/mlir-opt --split-input-file /data/szy/MLIR/seed/seed19/tmp.ObMmrsq6VK.mlir
1.      MLIR Parser: custom op parser 'builtin.module'
2.      MLIR Parser: custom op parser 'func.func'
3.      MLIR Parser: custom op parser 'linalg.add'
 #0 0x00005625234eddb8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11bddb8)
 #1 0x00005625234eb8be llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11bb8be)
 #2 0x00005625234ee736 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007fed4e47d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fed4daba00b raise /build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fed4da99859 abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00005625234d4f3f (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x11a4f3f)
 #7 0x0000562523d9d8fd (anonymous namespace)::RegionBuilderHelper::buildBinaryFn(mlir::linalg::BinaryFn, mlir::Value, mlir::Value) LinalgOps.cpp:0:0
 #8 0x0000562523d9e339 mlir::linalg::AddOp::regionBuilder(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x1a6e339)
 #9 0x0000562523eb9c1d void llvm::function_ref<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>::callback_fn<std::function<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>>(long, mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x1b89c1d)
#10 0x0000562523ea3f33 fillStructuredOpRegion(mlir::OpBuilder&, mlir::Region&, mlir::TypeRange, mlir::TypeRange, llvm::ArrayRef<mlir::NamedAttribute>, llvm::function_ref<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>) LinalgOps.cpp:0:0
#11 0x0000562523d92573 parseNamedStructuredOp(mlir::OpAsmParser&, mlir::OperationState&, unsigned int, llvm::function_ref<void (mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>) LinalgOps.cpp:0:0
#12 0x0000562523d9e4cc mlir::linalg::AddOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x1a6e4cc)
#13 0x00005625296567e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#14 0x00005625296619a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#15 0x000056252965f85c (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#16 0x000056252965dacc (anonymous namespace)::CustomOpAsmParser::parseOptionalRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#17 0x000056252975fe32 mlir::function_interface_impl::parseFunctionOp(mlir::OpAsmParser&, mlir::OperationState&, bool, mlir::StringAttr, llvm::function_ref<mlir::Type (mlir::Builder&, llvm::ArrayRef<mlir::Type>, llvm::ArrayRef<mlir::Type>, mlir::function_interface_impl::VariadicFlag, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&)>, mlir::StringAttr, mlir::StringAttr) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x742fe32)
#18 0x0000562523b707fa mlir::func::FuncOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x18407fa)
#19 0x00005625296567e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#20 0x00005625296619a4 (anonymous namespace)::OperationParser::parseBlock(mlir::Block*&) Parser.cpp:0:0
#21 0x000056252965f6d5 (anonymous namespace)::OperationParser::parseRegion(mlir::Region&, llvm::ArrayRef<mlir::OpAsmParser::Argument>, bool) Parser.cpp:0:0
#22 0x0000562526614b9e mlir::ModuleOp::parse(mlir::OpAsmParser&, mlir::OperationState&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x42e4b9e)
#23 0x00005625296567e4 (anonymous namespace)::OperationParser::parseOperation() Parser.cpp:0:0
#24 0x00005625296555ad mlir::parseAsmSourceFile(llvm::SourceMgr const&, mlir::Block*, mlir::ParserConfig const&, mlir::AsmParserState*, mlir::AsmParserCodeCompleteContext*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x73255ad)
#25 0x00005625264f4f0f mlir::parseSourceFile(std::shared_ptr<llvm::SourceMgr> const&, mlir::Block*, mlir::ParserConfig const&, mlir::LocationAttr*) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c4f0f)
#26 0x00005625264f3e8e mlir::parseSourceFileForTool(std::shared_ptr<llvm::SourceMgr> const&, mlir::ParserConfig const&, bool) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41c3e8e)
#27 0x00005625264f367f performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#28 0x00005625264f33ed llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#29 0x000056252659e726 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef)::$_0::operator()(llvm::StringRef) const ToolUtilities.cpp:0:0
#30 0x000056252659e39d mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x426e39d)
#31 0x00005625264ed405 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd405)
#32 0x00005625264ed6af mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd6af)
#33 0x00005625264ed9de mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x41bd9de)
#34 0x00005625234cc337 main (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119c337)
#35 0x00007fed4da9b083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#36 0x00005625234cbe9e _start (/data/szy/MLIR/llvm-project/install/bin/mlir-opt+0x119be9e)
```

### PR DESCRIPTION
**Pull request by joker-eph**
This thread through proper error handling / reporting capabilities to avoid hitting llvm_unreachable while parsing linalg ops.

Fixes #132755
Fixes #132740
Fixes #129185

### CODE REVIEW

File: mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp [hunk 1]
```diff
@@ -500,8 +531,13 @@ class RegionBuilderHelper {
         return builder.create<complex::SubOp>(arg0.getLoc(), arg0, arg1);
       if (allFloatingPoint)
         return builder.create<arith::SubFOp>(arg0.getLoc(), arg0, arg1);
-      if (allBool)
+      if (allBool) {
+        if (emitError) {
```
Comment (rengolin) [inline mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:536]: There's a lot of repetition of this pattern. Could we perhaps simplify into an extern function?

**Review by rengolin — COMMENTED** [review]
Really nice, thanks! Small comment on my part but otherwise ok.

Will give time to others to look, too.

File: mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp (hunk 1 above)
Comment (joker-eph) [reply mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:536]: There is a return inside a if statement, how would you simplify this? I could see it with a macro maybe but I'm not sure how to do this with a function.
(the error message is also slightly different between all the cases below)

Comment (rengolin) [reply mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:536]: What about something like:
```c++
// Mostly helpful to the constant message ones
Value returnError(StringRef& msg) {
  emitError() << msg;
  return nullptr;
}
```

then use:
```c++
if (emitError)
  return returnError("message here");
llvm_unreachable("message here");
```

Comment (joker-eph) [reply mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:536]: I just looked into this, but this wouldn't be universally applicable in this file: some of the cases are streaming multiple piece together to form the error message, and some function that have this pattern are not returning a Value.

File: mlir/test/Dialect/Linalg/invalid.mlir [hunk 2]
```diff
@@ -1874,3 +1874,13 @@ func.func @reduce_non_operation_name(%arg0: tensor<4xf32>, %arg1: tensor<f32>) -
...
+
+// -----
+
+module {
+  func.func @add_dynamic(%arg0: memref<3x4x5xf32>, %arg1 : memref< 3x4x5xi32>, %arg2: memref<3x4x5xf32>, %arg3: memref<3x4x5xf32>) attributes {arm_streaming} {
+    linalg.add ins(%arg0, %arg1 : memref<3x4x5xf32>, memref< 3x4x5xi32>) outs(%arg2 : memref<3x4x5xf32>)
+    // expected-error @below {{Cannot build binary Linalg operation: expects allComplex, allFloatingPoint, or allInteger, got 'f32' and 'i32'}}
+    return
+  }
+}
```
Comment (banach-space) [inline mlir/test/Dialect/Linalg/invalid.mlir]: 1. Missing new-line charachter.
2. Would you mind adding a block comment to separate this from other Ops? See e.g. [this comment](https://github.com/banach-space/llvm-project/blob/c62abf4d15500182b66e5957f945f790f5d8ad72/mlir/test/Dialect/Linalg/invalid.mlir#L1799-L1801)? (there's one missing for `linalg.reduce` as well).

I also suggest reducing this test (e.g. by removing the attribute, using rank-1 types, etc). This way its clearer what makes this "unique".
```suggestion
// -----

module {
  func.func @add_mixed_types(%in_f32: memref<3xf32>, %in_i32 : memref< 3xi32>, %out_f32: memref<3xf32>, %arg3: memref<3xf32>) {
    linalg.add ins(%in_f32, %in_i32 : memref<3xf32>, memref< 3xi32>) outs(%out_f32 : memref<3xf32>)
    // expected-error @below {{Cannot build binary Linalg operation: expects allComplex, allFloatingPoint, or allInteger, got 'f32' and 'i32'}}
    return
  }
}
```

**Review by banach-space — COMMENTED** [review]
Thanks for taking this on!

Shouldn't this also include tests for `linalg.matmul` and `linalg.elemwise_unary`?

**Comment by joker-eph** [comment]
Added the tests from the two other bugs.

File: mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp [hunk 3]
```diff
@@ -472,18 +488,34 @@ class RegionBuilderHelper {
...
+      return nullptr;
+    }
     llvm_unreachable("unsupported unary function");
   }
 
   // Build the binary functions defined by OpDSL.
-  Value buildBinaryFn(BinaryFn binaryFn, Value arg0, Value arg1) {
+  // If emitError is provided, an error will be emitted if the operation is not
+  // supported and a nullptr will be returned, otherwise an assertion will be
+  // raised.
```
Comment (banach-space) [inline mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:501]: Any particular reason for allowing empty `emitError`? I would make it mandatory and just remove `llvm_unreachable`. Both approaches work, but if the extra flexibility is not needed then we could remove some code :)

File: mlir/test/Dialect/Linalg/invalid.mlir [hunk 4]
```diff
@@ -1868,9 +1868,49 @@ func.func @unpack_static_inner_tile_size_and_dynamic_output_shape(
...
+
+func.func @matmul_invalid_mixed_types(%t: tensor<?xf16>, %f: vector<4xf16>)
+  -> (tensor<?xf16>, vector<4xf16>)
+{
+  // expected-warning @unknown {{could not cast operand of type 'f16' to 'vector<4xf16>'}}
+  // expected-error @below {{Cannot build binary Linalg operation: expects allComplex, allFloatingPoint, or allInteger, got 'vector<4xf16>' and 'f16'}}
+  %0 = linalg.matmul ins(%t, %t : tensor<?xf16>, tensor<?xf16>)
+                                outs(%f : vector<4xf16>) -> tensor<?xf16>
+  func.return %0, %f : tensor<?xf16>, vector<4xf16>
+}
```
Comment (banach-space) [inline mlir/test/Dialect/Linalg/invalid.mlir:1918]: [nit] Move next to the other tests for `linalg.matmul` so that all matmuls are clustered together (makes it easier to find what's tested for a particular Op): https://github.com/llvm/llvm-project/blob/577199f9221ebc805a69372a2b19f4c8ebaf1daf/mlir/test/Dialect/Linalg/invalid.mlir#L307-L322. Thanks!

**Review by banach-space — APPROVED** [review]
LGTM 

I posted 2 additional questions/requests - these are non-blocking.

Thanks again for tackling this!

File: mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp (hunk 3 above)
Comment (joker-eph) [reply mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:501]: We only want emitError in parsing code: these utilities are used outside of parsing context where this becomes an invariant expectation of the API.

File: mlir/test/Dialect/Linalg/invalid.mlir (hunk 4 above)
Comment (joker-eph) [reply mlir/test/Dialect/Linalg/invalid.mlir:1918]: I'm not sure about this: it's not really testing matmul, but matmul is used as proxy to reach some of the generic infrastructure testing named ops.

For example removing the matmul op would lose coverage and we should use another op to get this diagnostic.

Comment (banach-space) [reply mlir/test/Dialect/Linalg/invalid.mlir:1918]: Thanks for clarifying, now I see what you meant by `Named op error checking.`.

In my mind, invalid.mlir is primarily for Op verification. It might be helpful to expand the block comment with something along these lines:
```mlir
Tests for generic infrastructure for named Ops. The actual Ops used are secondary - we merely want to ensure that the diagnostic infra triggers correctly.
```

Otherwise, the intent could easily get lost once this lands. Definitely a nice-to-have, not blocking.

Comment (joker-eph) [reply mlir/test/Dialect/Linalg/invalid.mlir:1918]: Done

**Review by nicolasvasilache — APPROVED** [review]
nice, thanks much!

**Comment by hiraditya** [comment]
Thanks for fixing it the right way. I was having this issue a while back and it was tricky to handle without modifying the region builder API https://discourse.llvm.org/t/rfc-linalgops-regionbuilder-function-needs-to-indicate-if-anything-goes-wrong/86053

**Comment by vzakhari** [comment]
Am I the only one who is having build issues with this patch?

The errors look like this:
```
.../llvm/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.h.inc:1450:39: error: could not convert ‘mlir::linalg::MinOp
::getRegionBuilder()()’ from ‘function<void(mlir::ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>)>’ to ‘function<void(mlir::ImplicitLocOpBui
lder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>, llvm::function_ref<mlir::InFlightDiagnostic()>)>’
.../llvm/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.h.inc: In instantiation of ‘static std::function<void(mlir::
ImplicitLocOpBuilder&, mlir::Block&, llvm::ArrayRef<mlir::NamedAttribute>, llvm::function_ref<mlir::InFlightDiagnostic()>)> mlir::linalg::detail::LinalgOpInterfaceTrai
ts::Model<ConcreteOp>::getRegionBuilder() [with ConcreteOp = mlir::linalg::Mmt4DOp]’:
.../llvm/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.h.inc:361:724:   required from ‘mlir::linalg::detail::Linalg
OpInterfaceTraits::Model<ConcreteOp>::Model() [with ConcreteOp = mlir::linalg::Mmt4DOp]’
/llvm-project/mlir/include/mlir/Support/InterfaceSupport.h:238:9:   required from ‘void mlir::detail::InterfaceMap::insertModel() [with
 InterfaceModel = mlir::linalg::detail::LinalgOpInterfaceTraits::Model<mlir::linalg::Mmt4DOp>]’
```

**Comment by vzakhari** [comment]
I was a false alarm (somewhat), it passed with a clean build.

**Comment by benvanik** [comment]
I too am getting errors with this - will try a clean build - I suspect there's a missing cmake dependency that is causing something to not be rebuilt.

**Comment by benvanik** [comment]
Clean build fixed it, so definitely something shady with the linalg generator cmake dependencies.
