### PR TITLE
[clang-tidy] fix false positives when using name-independent variables after C++26 for bugprone-unused-local-non-trivial-variable

### LINKED ISSUE #121731: [clang-tidy][BUG][C++23][False Positive] on no name placeholder with std::string type
```
auto _ = std::vector<int>{};     // ok, no warning
auto _ = std::unique_ptr<int>{}; // ok, no warning
auto _ = "abc"sv;                // ok, no warning
auto _ = 1234;                   // ok, no warning
auto _ = 3.14;                   // ok, no warning
auto _ = "abcd"sv;               // ok, no warning
auto _ = {1, 2, 3};              // ok, no warning
auto _ = "abcd"s;                // warning by clang-tidy: Unused local variable '_' of type 'basic_string<char>'
auto _ = [] { return ""s; }();   // warning by clang-tidy: Unused local variable '_' of type 'basic_string<char>'
```

My clang-tidy version is 19.1.5.

Note that this false positive occur for `std::string` only, other types, even `std::vector<int>` and `std::unique_ptr<int>` which are obviously non-trivial classes, seem also good as expected.

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixed: #121731
According to https://eel.is/c++draft/basic.scope.scope#5, name independent declaration should not be warned as unused

### CODE REVIEW

**Review by 5chmidti — APPROVED** [review]
LGTM

File: clang-tools-extra/clang-tidy/bugprone/UnusedLocalNonTrivialVariableCheck.cpp [hunk 1]
```diff
@@ -29,6 +29,12 @@ static constexpr StringRef DefaultIncludeTypeRegex =
 
 AST_MATCHER(VarDecl, isLocalVarDecl) { return Node.isLocalVarDecl(); }
 AST_MATCHER(VarDecl, isReferenced) { return Node.isReferenced(); }
+AST_MATCHER_P(VarDecl, explicitMarkUnused, LangOptions, LangOpts) {
+  // Implementations should not emit a warning that a name-independent
+  // declaration is used or unused.
+  return Node.hasAttr<UnusedAttr>() ||
+         (LangOpts.CPlusPlus26 && Node.isPlaceholderVar(LangOpts));
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/bugprone/UnusedLocalNonTrivialVariableCheck.cpp:36]: Out of curiosity, is the CplusPlus26 needed? Won't `isPlaceholderVar` return `false` otherwise?

Comment (PiotrZSL) [reply clang-tools-extra/clang-tidy/bugprone/UnusedLocalNonTrivialVariableCheck.cpp:36]: And, you dont need to pass LangOptions via argument.
From matcher you got access to ASTContext, and that class got [getLangOpts](https://clang.llvm.org/doxygen/classclang_1_1ASTContext.html#a50f31d935973dd09016088579ba81944)

Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/UnusedLocalNonTrivialVariableCheck.cpp:36]: > Out of curiosity, is the CplusPlus26 needed? Won't isPlaceholderVar return false otherwise?

Yes, `isPlaceholderVar` does not check cpp version.
