### PR TITLE
MachineCopyPropagation: Do not remove copies preserved by regmask

### LINKED ISSUE #126107: [MachineCP] Assertion `Reg.isPhysical()' failed in MCRegUnitIterator
During our local testing, we encountered the assertion failure `Reg.isPhysical()` in the `MachineCP` pass.

Reduced reproducer:
 ```
---
name:            main
body:             |
  bb.0.entry:  
    liveins: $ymm7
    renamable $ymm6 = COPY killed renamable $ymm7
    CALL64r killed renamable $rax, csr_64_mostregs
    renamable $ymm6 = VPADDWZ256rr $ymm6, $ymm6
```
Steps to reproduce:
```
$ bin/llc  -run-pass machine-cp test.mir
llc: /root/llvm-project/llvm/include/llvm/MC/MCRegisterInfo.h:649: llvm::MCRegUnitIterator::MCRegUnitIterator(llvm::MCRegister, const llvm::MCRegisterInfo*): Assertion `Reg.isPhysical()' failed
```
Proof: https://godbolt.org/z/PnqdcKbfe

The problematic patch seems to be: https://github.com/llvm/llvm-project/commit/9e436c2daa446da05e9219f0e6a22f932ba8e3cb

Based on my investigation, the issue arises when we remove `renamable $ymm6 = COPY killed renamable $ymm7` due to regmask clobbering. However, during this process, we skip dropping the corresponding RegUnit from the tracking copies, since it's preserved:

```c++
        LLVM_DEBUG(dbgs() << "MCP: Removing copy due to regmask clobbering: ";
                   MaybeDead->dump());

        // Invalidate all entries in the copy map which are not preserved by
        // this register mask.
        for (unsigned RegUnit : TRI->regunits(Reg))
          if (!PreservedRegUnits.test(RegUnit))
            Tracker.clobberRegUnit(RegUnit, *TRI, *TII, UseCopyInstr);

        // erase() will return the next valid iterator pointing to the next
        // element after the erased one.
        DI = MaybeDeadCopies.erase(DI);
        MaybeDead->eraseFromParent();
```

As a result, we retain a pointer to the erased instruction in tracking copies, which leads to a failure when accessing it while processing `renamable $ymm6 = VPADDWZ256rr $ymm6, $ymm6`, clobbering any previous copy definitions.

@ostannard hi, could you please take a look?

### PR DESCRIPTION
**Pull request by jsji**
llvm/llvm-project@9e436c2daa44 tries to handle register masks and
sub-registers, it avoids clobbering RegUnit presreved by regmask. But it
then introduces invalid pointer issues.

We delete the copies without invalidate all the use in the CopyInfo, so
we dereferenced invalid pointers in next interation, causing asserts.

Fixes: #126107

### CODE REVIEW

File: llvm/lib/CodeGen/MachineCopyPropagation.cpp [hunk 1]
```diff
@@ -1018,18 +1018,30 @@ void MachineCopyPropagation::ForwardCopyPropagateBlock(MachineBasicBlock &MBB) {
...
         // erase() will return the next valid iterator pointing to the next
         // element after the erased one.
         DI = MaybeDeadCopies.erase(DI);
+
+        // Preserved by RegMask, DO NOT remove copy
+        if (MIRefedinCopyInfo)
+          continue;
+
+        LLVM_DEBUG(dbgs() << "MCP: Removing copy due to regmask clobbering: ";
+                   MaybeDead->dump());
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineCopyPropagation.cpp:1043]:
```suggestion
        LLVM_DEBUG(dbgs() << "MCP: Removing copy due to regmask clobbering: " << *MaybeDead;
```

**Comment by bzEq** [comment]
Could you please provide the test causing assertion failure?

**Comment by JaydeepChauhan14** [comment]
@arsenm , @evanphx , @bzEq  can please review pr.

**Comment by ostannard** [comment]
Issue #126107 has a reproducer for this, so that can be added as a test. I've checked that applying this patch does fix that assertion.

**Comment by jsji** [comment]
> Issue #126107 has a reproducer for this, so that can be added as a test. I've checked that applying this patch does fix that assertion.

Thanks! Added MIR test from #126107.

**Review by ostannard — APPROVED** [review]
Thanks, LGTM
