### PR TITLE
[Flang][OpenMP] Restructure recursive lowering in `createBodyOfOp`

### LINKED ISSUE #74348: [Flang][OpenMP] Error when unstructured code is present
This is another instance where the presence of unstructured code in OpenMP regions leads to failure.

### Error
error: loc("fname.f90":10:3): operation with block successors must terminate its parent block

### Program
```
subroutine sb(ninter, numnod)
  integer :: ninter, numnod
  integer, dimension(:), allocatable :: indx_nm

  !$omp parallel
  if (ninter>0) then
    allocate( indx_nm(numnod) )
  endif
  220      continue
  goto 220
  !$omp end parallel
end subroutine
```

### PR DESCRIPTION
**Pull request by kparzysz**
This brings `createBodyOfOp` to its final intended form. First, input privatization is performed, then the recursive lowering takes place, and finally the output privatization (lastprivate) is done.

This enables fixing a known issue with infinite loops inside of an OpenMP region, and the fix is included in this patch.

Fixes https://github.com/llvm/llvm-project/issues/74348.

Recursive lowering [5/5]

### CODE REVIEW

File: flang/test/Lower/OpenMP/infinite-loop-in-construct.f90 [hunk 1]
```diff
@@ -0,0 +1,19 @@
+! RUN: bbc -fopenmp -o - %s | FileCheck %s
+
+! Check that this test can be lowered successfully.
+! See https://github.com/llvm/llvm-project/issues/74348
+
+! CHECK-LABEL: func.func @_QPsb
+! CHECK: omp.parallel
```
Comment (skatrak) [inline flang/test/Lower/OpenMP/infinite-loop-in-construct.f90:7]: I think it would be a bit better to also check the general structure inside of omp.parallel. That is, checking the blocks and terminators that are created.

**Review by skatrak — COMMENTED** [review]
Thanks Krzysztof! This looks ok to me, but I suggest waiting for approval from a second reviewer.

**Comment by kiranchandramohan** [comment]
@tblah mentions that this patch fixes the unstructured code issue in worksharing loop with collapse. https://github.com/llvm/llvm-project/pull/77329.

File: flang/lib/Lower/OpenMP.cpp [hunk 2]
```diff
@@ -2223,37 +2247,64 @@ static void createBodyOfOp(
...
+  }
+
+  if (auto *exitBlock = findExitBlock(op.getRegion())) {
+    firOpBuilder.setInsertionPointToEnd(exitBlock);
+    auto *term = Fortran::lower::genOpenMPTerminator(firOpBuilder,
+                                                     op.getOperation(), loc);
+    // Only insert lastprivate code when there actually is an exit block.
+    // Such a block may not exist if the nested code produced an infinite
+    // loop (this may not make sense in production code, but a user could
+    // write that and we should handle it).
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP.cpp:2292]: Is it guaranteed that it is only when there is an infinite loop that no exit block exists?
Also who/what inserts the terminator for this case (when there is infinite loop)?

Comment (kparzysz) [reply flang/lib/Lower/OpenMP.cpp:2292]: We rely on the `genEval` for the nested code to do its thing.  If we consider the nested code (PFT/Evaluation) on its own, it will have a single entry point, and zero or more exit points.  If it creates multiple blocks, it will need to create its own branches to facilitate the control flow.  After `genEval` we remove the temporary terminator, then we look at all the blocks created during `genEval`.  We know that everything that is present inside of these blocks was created for the nested code (and not the enclosing construct we're lowering).  Terminators for our op haven't been created yet, and they can only placed in blocks that don't yet have a terminator.  If every block has a terminator then there is no way to leave the region by means of reaching the end of it (that is aside from function calls).

Based on that, the logical thing to do would be to insert a terminator into all non-terminated blocks.  This would work even if there is always at most one such block.

The assertion that there can only be one comes mostly from two things:
- the requirement from the OpenMP standard that a structured block exits at the bottom of the program text, and
- the current lowering seems to provide a single FIR location that corresponds to the "bottom".

If we can't be sure that the assertion is correct, we should be able to remove it, and process all exiting blocks.

Comment (kparzysz) [reply flang/lib/Lower/OpenMP.cpp:2292]: What I'm going to do is to create a unique exiting block:  create a new block, and for each yet-unterminated block, will insert a branch to the new one.  Then insert the OMP terminator into it, and process the lastprivate in there.

This will get rid of the assertion.

File: flang/test/Lower/OpenMP/infinite-loop-in-construct.f90 (hunk 1 above)
Comment (kparzysz) [reply flang/test/Lower/OpenMP/infinite-loop-in-construct.f90]: That's done.

File: flang/lib/Lower/OpenMP.cpp [hunk 3]
```diff
@@ -2223,37 +2222,100 @@ static void createBodyOfOp(
...
+    llvm::SmallVector<mlir::Block *> exits;
+    for (mlir::Block &b : region) {
+      if (b.empty() || !b.back().hasTrait<mlir::OpTrait::IsTerminator>())
+        exits.push_back(&b);
+    }
+
+    if (exits.empty())
+      return nullptr;
+    // If there already is a unique exiting block, do not create another one.
+    // Additionally, some ops (e.g. omp.sections) require onlt 1 block in
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP.cpp:2284]:
```suggestion
    // Additionally, some ops (e.g. omp.sections) require only 1 block in
```

File: flang/lib/Lower/OpenMP.cpp (hunk 2 above)
Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP.cpp:2303]: OK. Makes sense.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.
