### PR TITLE
[libc][math] Fix signaling NaN handling for math functions.

### LINKED ISSUE #124812: [libc][math] Fix signaling nans and floating point exceptions for some math functions.
The following issues with signaling nans and floating point exceptions are reported by @zimmermann6 with the CORE-MATH test suites:
```
CORE_MATH_CHECK_STD=true LIBM=/localdisk/zimmerma/llvm-project/build/projects/libc/lib/libllvmlibc.a ./check.sh $f

atan2
Running worst cases check in --rndn mode...
Missing inexact exception for x=0x0.0000000000001p-1022 y=0x1p+0 (z=0x0.0000000000001p-1022)

atan2f
Running worst cases check in --rndn mode...
Missing invalid exception for x=nan y=0x1p+0

exp
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=fff0000000000001

exp10
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=fff0000000000001

exp2
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=fff0000000000001

log
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=7ff0000000000001

log10
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=7ff0000000000001

log1p
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=7ff0000000000001

log2
Running worst cases check in --rndn mode...
Error, foo(sNaN) should be qNaN, got sNaN=7ff0000000000001

pow
Running worst cases check in --rndn mode...
Error, foo(sNaN,1.0) should be qNaN, got sNaN=7ff0000000000001

powf
Running worst cases check in --rndn mode...
Error, foo(sNaN,x) should be qNaN, got sNaN=7f800001
```

### PR DESCRIPTION
**Pull request by wldfngrs**
Add tests for signaling NaNs, and fix function behavior for handling signaling NaN input.

Fixes https://github.com/llvm/llvm-project/issues/124812

### CODE REVIEW

**Comment by wldfngrs** [comment]
@lntue, @overmighty please review

**Comment by wldfngrs** [comment]
@jhuber6 Regarding the botched PR, I wasn't paying close attention to what I was committing, my bad!

File: libc/src/math/generic/powf.cpp [hunk 1]
```diff
@@ -657,6 +657,11 @@ LLVM_LIBC_FUNCTION(float, powf, (float x, float y)) {
   uint32_t y_abs = ybits.abs().uintval();
 
   ///////// BEGIN - Check exceptional cases ////////////////////////////////////
+  // if x or y is signaling NaN
```
Comment (lntue) [inline libc/src/math/generic/powf.cpp:660]: Can you move this one inside the condition:
```
if (LIBC_UNLIKELY((y_abs & 0x0007'ffff) == 0) || (y_abs > 0x4f170000)) {
```
and add another one, that only check if `xbits.is_signaling_nan` inside the condition:
```
  if (LIBC_UNLIKELY(((x_u & 0x801f'ffffU) == 0) || x_u >= 0x7f80'0000U ||
                    x_u < 0x0080'0000U)) {
```

File: libc/src/math/generic/powf.cpp [hunk 2]
```diff
@@ -741,8 +742,8 @@ LLVM_LIBC_FUNCTION(float, powf, (float x, float y)) {
         }
       }
       if (y_abs > 0x4f17'0000) {
+        // y is NaN
         if (y_abs > 0x7f80'0000) {
-          // y is NaN
```
Comment (overmighty) [inline libc/src/math/generic/powf.cpp:740]: A bit of a nit, but I think if the comment is going to be on top of the `if`, it should be `// if y is NaN`, otherwise it should remain inside the `if`. My reasoning is that there is a `// y is finite and non-zero.` comment below that is right above an `if` that only checks `x_u`, because it comments what is known about `y` when that `if` is reached and not what would be known about `y` if that `if`'s condition were true.

File: libc/src/math/generic/powf.cpp [hunk 3]
```diff
@@ -804,7 +811,6 @@ LLVM_LIBC_FUNCTION(float, powf, (float x, float y)) {
     }
 
     if (x_abs > 0x7f80'0000) {
-      // x is NaN.
```
Comment (overmighty) [inline libc/src/math/generic/powf.cpp:802]: I don't think this comment should be removed.

**Review by overmighty — COMMENTED** [review]
Are you planning to change other math functions in this same PR? The title says functions in plural.

**Comment by wldfngrs** [comment]
> Are you planning to change other math functions in this same PR? The title says functions in plural.

I'm confused. I updated about 80 files?

File: libc/src/math/generic/atan2f.cpp [hunk 4]
```diff
@@ -7,7 +7,9 @@
 //===----------------------------------------------------------------------===//
 
 #include "src/math/atan2f.h"
+#include "hdr/fenv_macros.h"
```
[the remark this answers is not in the document]
Comment (lntue) [reply libc/src/math/generic/atan2f.cpp:10]: SGTM

File: libc/test/src/math/smoke/pow_test.cpp [hunk 5]
```diff
@@ -7,6 +7,7 @@
 //===----------------------------------------------------------------------===//
 
 #include "hdr/fenv_macros.h"
+#include "src/errno/libc_errno.h"
```
Comment (overmighty) [inline libc/test/src/math/smoke/pow_test.cpp:10]: Why include libc_errno.h here?

File: libc/test/src/math/smoke/powf_test.cpp [hunk 6]
```diff
@@ -32,7 +32,33 @@ TEST_F(LlvmLibcPowfTest, SpecialNumbers) {
     if (!__r.success)
       continue;
 
+    // pow( sNaN, exponent)
```
Comment (overmighty) [inline libc/test/src/math/smoke/powf_test.cpp:35]: Nit: formatting inconsistency.

```suggestion
    // pow( sNaN, exponent )
```

File: libc/test/src/math/smoke/atan_test.cpp [hunk 7]
```diff
@@ -13,8 +13,10 @@
 using LlvmLibcAtanTest = LIBC_NAMESPACE::testing::FPTest<double>;
 
 TEST_F(LlvmLibcAtanTest, SpecialNumbers) {
+  EXPECT_FP_EQ_WITH_EXCEPTION(aNaN, LIBC_NAMESPACE::atan(sNaN), FE_INVALID);
+  EXPECT_MATH_ERRNO(0);
+
   EXPECT_FP_EQ_ALL_ROUNDING(aNaN, LIBC_NAMESPACE::atan(aNaN));
-  // atan(sNaN) = aNaN.
   EXPECT_EQ(FPBits(aNaN).uintval(),
             FPBits(LIBC_NAMESPACE::atan(sNaN)).uintval());
```
Comment (overmighty) [inline libc/test/src/math/smoke/atan_test.cpp:21]: You added a new check for `atan(sNaN)` above so I would say this one is redundant now, although it checks that the result is exactly `aNaN` whereas `EXPECT_FP_EQ*` will accept any NaN as actual value when the expected value is NaN.

```suggestion
```

File: libc/test/src/math/smoke/atan2f_test.cpp [hunk 8]
```diff
@@ -18,6 +18,18 @@ using LlvmLibcAtan2fTest = LIBC_NAMESPACE::testing::FPTest<float>;
...
+  EXPECT_FP_EQ_WITH_EXCEPTION(aNaN, LIBC_NAMESPACE::atan2f(sNaN, sNaN),
+                              FE_INVALID);
+  EXPECT_MATH_ERRNO(0);
+
+  EXPECT_FP_EQ_WITH_EXCEPTION(aNaN, LIBC_NAMESPACE::atan2f(sNaN, 1.0),
+                              FE_INVALID);
+  EXPECT_MATH_ERRNO(0);
+
+  EXPECT_FP_EQ_WITH_EXCEPTION(aNaN, LIBC_NAMESPACE::atan2f(1.0, sNaN),
+                              FE_INVALID);
```
Comment (overmighty) [inline libc/test/src/math/smoke/atan2f_test.cpp:30]: Nit: should use `1.0f` instead of `1.0` since `atan2f` takes a `float` input.

File: libc/src/math/generic/CMakeLists.txt [hunk 9]
```diff
@@ -4129,7 +4129,9 @@ add_entrypoint_object(
     atan2f_float.h
   DEPENDS
     .inv_trigf_utils
+    libc.hdr.fenv_macros
```
Comment (overmighty) [inline libc/src/math/generic/CMakeLists.txt:4132]: If you don't want to fix the missing `#include "hdr/fenv_macros.h"` in atan2f.cpp in this PR anymore then there's no more need to add this dependency here.

Comment (overmighty) [reply libc/src/math/generic/CMakeLists.txt:4132]: Actually, since this PR adds the only use of an fenv macro in atan2f.cpp, maybe it would have been better to just not remove the `#include "hdr/fenv_macros.h"` in the last commit.

**Review by overmighty — APPROVED** [review]
