### PR TITLE
[Clang] Check explicit object parameter for defaulted operators properly

### LINKED ISSUE #100329: ICE on defaulting of operator== with explicit object parameter
Compilation of this (probably invalid) program
```
struct A {
    bool operator == (this const int&, const A&);
};

bool A::operator == (this const int&, const A&) = default;
```
results in
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-18.1.0/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-13.2.0 -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 -Wall -Wextra -pedantic-errors -stdlib=libc++ <source>
1.	<source>:7:1: current parser token 'int'
 #0 0x000000000351ae38 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x351ae38)
 #1 0x0000000003518f84 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3518f84)
 #2 0x0000000003467018 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007c8384442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000005fd5867 (anonymous namespace)::DefaultedComparisonVisitor<(anonymous namespace)::DefaultedComparisonSynthesizer, (anonymous namespace)::StmtListResult, clang::ActionResult<clang::Stmt*, true>, std::pair<clang::ActionResult<clang::Expr*, true>, clang::ActionResult<clang::Expr*, true>>>::visitSubobjects((anonymous namespace)::StmtListResult&, clang::CXXRecordDecl*, clang::Qualifiers) SemaDeclCXX.cpp:0:0
 #5 0x0000000005fde36c (anonymous namespace)::DefaultedComparisonSynthesizer::build() (.constprop.0) SemaDeclCXX.cpp:0:0
 #6 0x0000000005ffea6d clang::Sema::DefineDefaultedComparison(clang::SourceLocation, clang::FunctionDecl*, clang::Sema::DefaultedComparisonKind) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5ffea6d)
 #7 0x000000000604cf2a clang::Sema::SetDeclDefaulted(clang::Decl*, clang::SourceLocation) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x604cf2a)
 #8 0x0000000005ba382a clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5ba382a)
 #9 0x0000000005be32b9 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5be32b9)
#10 0x0000000005b9c4a9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5b9c4a9)
#11 0x0000000005b9d011 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5b9d011)
#12 0x0000000005ba53af clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5ba53af)
#13 0x0000000005ba6f27 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5ba6f27)
#14 0x0000000005b963ba clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x5b963ba)
#15 0x0000000003d5a725 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3d5a725)
#16 0x0000000003fe2aa1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3fe2aa1)
#17 0x0000000003f6010b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3f6010b)
#18 0x00000000040c2473 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x40c2473)
#19 0x0000000000c19746 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0xc19746)
#20 0x0000000000c1211d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#21 0x0000000003da1979 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#22 0x0000000003467443 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3467443)
#23 0x0000000003da1b99 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#24 0x0000000003d69d17 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3d69d17)
#25 0x0000000003d6a6cd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3d6a6cd)
#26 0x0000000003d7445c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0x3d7445c)
#27 0x0000000000c16a21 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0xc16a21)
#28 0x0000000000b0fa84 main (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0xb0fa84)
#29 0x00007c8384429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#30 0x00007c8384429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#31 0x0000000000c1191e _start (/opt/compiler-explorer/clang-18.1.0/bin/clang+++0xc1191e)
```
Online demo: https://gcc.godbolt.org/z/dYKj11x16

### LINKED ISSUE #104413: C++23 default comparisons is incorrectly rejected
Sibling issue of #104414.

According to https://eel.is/c++draft/class.compare#default-1, the following C++23 program should compile.

```cpp
struct A { 
  bool operator ==(this A, A) = default;
};

int main() {
  return A{}.operator ==(A{});
}
```

but Clang (18.1 and trunk) reports

```
<source>:2:20: error: defaulted member equality comparison operator must be const-qualified
    2 |   bool operator ==(this A, A) = default;
      |                    ^
      |                         const
<source>:2:8: error: invalid parameter type for defaulted equality comparison operator; found 'A', expected 'const A &'
    2 |   bool operator ==(this A, A) = default;
      |        ^                   ~
2 errors generated.
```

FWIW, GCC accepts it.

Reproducible at https://godbolt.org/z/qM57nxz5d

See also https://stackoverflow.com/a/78808748/24103368 from @brevzin.

### LINKED ISSUE #104414: C++23 default comparisons is incorrectly accepted
Sibling issue of #104413.

According to https://eel.is/c++draft/class.compare#default-1, the following program should be rejected by Clang but it isn't.

```cpp
struct A {
  bool operator==(this const A, const A&) = default;
};
```

Reproducible at https://godbolt.org/z/reoWEExM7

See also https://stackoverflow.com/a/78808748/24103368 from @brevzin.

### PR DESCRIPTION
**Pull request by MitalAshok**
Previously, the type of explicit object parameters was not considered for relational operators. This was defined by CWG2586, <https://cplusplus.github.io/CWG/issues/2586.html>. This fix also means CWG2547 <https://cplusplus.github.io/CWG/issues/2547.html> is now fully implemented. Fixes #100329, fixes #104413.

Now start rejecting invalid rvalue reference parameters, which weren't checked for, and start accepting non-reference explicit object parameters (like `bool operator==(this C, C) = default;`) which were previously rejected for the object param not being a reference.

Also start rejecting non-reference explicit object parameters for defaulted copy/move assign operators (`A& operator=(this A, const A&) = default;` is invalid but was previously accepted). Fixes #104414.

### CODE REVIEW

**Comment by MitalAshok** [comment]
CC @cor3ntin

File: clang/test/CXX/drs/cwg25xx.cpp [hunk 1]
```diff
@@ -92,6 +92,26 @@ using ::cwg2521::operator""_div;
 #endif
 } // namespace cwg2521
 
+namespace cwg2547 { // cwg2547: 20
+#if __cplusplus >= 202302L
+struct S; // since-cxx23-note 3 {{forward declaration of 'cwg2547::S'}}
+bool operator==(S, S) = default;  // error: S is not complete
+// since-cxx23-error@-1 2 {{variable has incomplete type 'S'}}
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg25xx.cpp:99]:
```suggestion
// since-cxx23-error@-1 {{variable has incomplete type 'S'}}
// since-cxx23-error@-2 {{variable has incomplete type 'S'}}
```
We don't use diagnostic quantifiers in DR test suite

**Review by Endilll — COMMENTED** [review]
Changes to DR tests look good otherwise.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 2]
```diff
@@ -7617,9 +7617,13 @@ bool Sema::CheckExplicitlyDefaultedSpecialMember(CXXMethodDecl *MD,
     // parameter is of (possibly different) type “reference to C”,
     // in which case the type of F1 would differ from the type of F2
     // in that the type of F1 has an additional parameter;
-    if (!Context.hasSameType(
-            ThisType.getNonReferenceType().getUnqualifiedType(),
-            Context.getRecordType(RD))) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaDeclCXX.cpp:7622]: I think your change loses this check - this is the ` bool S::operator==(int) = default` case

Comment (MitalAshok) [reply clang/lib/Sema/SemaDeclCXX.cpp:7622]: That's checked somewhere later, this was operating on `ThisType`.

For an implicit object member function, `ThisType.getNonReferenceType().getUnqualifiedType()` is *always* `Context.getRecordType(RD)` (and this shouldn't fail anyways because the diagnostic emitted here is `err_defaulted_special_member_explicit_object_mismatch`)

The only difference is with explicit object member functions. The old code rejected `S& S::operator=(this int, const S&) = default;`, but accepted `S& S::operator=(this S, const S&)` since it didn't check that it was a reference.

**Review by cor3ntin — APPROVED** [review]
LGTM

**Comment by MitalAshok** [comment]
@cor3ntin If everything is still good with this could you commit this for me? Thanks!

**Comment by cor3ntin** [comment]
@MitalAshok do you need me to merge?

**Comment by MitalAshok** [comment]
@cor3ntin Yes can you do that? Thanks

**Comment by marco-antognini-sonarsource** [comment]
@MitalAshok, thanks for the fix!

Do you think it could also go into the 19.x branch?

**Comment by marco-antognini-sonarsource** [comment]
@MitalAshok, I see -- that's fair enough. Thanks for digging up the process.
