### PR TITLE
[Flang] - Enhance testing for strictly-nested teams in target regions.

### LINKED ISSUE #153173: Missing Flang semantics check causes ICE
The following invalid OpenMP program causes a compiler crash rather than emitting a semantics error:
```f90
! test.f90
program main
  implicit none
  integer, parameter :: n = 100
  integer, parameter :: expected = n+2
  integer :: i
  integer :: counter

  counter = 0
  !$omp target map(tofrom:counter)
    counter = counter+1
    !$omp teams distribute reduction(+:counter)
    do i=1, n
      counter = counter+1
    end do
    counter = counter+1
  !$omp end target

  print '("Result: "I0)', counter
end program
```
This is triggered both when offloading and when compiling exclusively for the host device.
```shell
flang -fopenmp --offload-arch=gfx1030 test.f90
flang -fopenmp test.f90
```
The specific OpenMP restriction being violated by the previous example is found in the specification version 6.0, page 395, lines 33 -- 35:
> [...] If a `teams` region is nested inside a `target` region, the corresponding `target` construct must not contain any statements, declarations or directives outside of the corresponding `teams` construct.

### PR DESCRIPTION
**Pull request by bhandarkar-pranav**
This patch enhances the semantics test for checking that teams directives are strictly nested inside target directives.

Fixes https://github.com/llvm/llvm-project/issues/153173

### CODE REVIEW

File: flang/lib/Semantics/check-omp-loop.cpp [hunk 1]
```diff
@@ -262,6 +262,15 @@ void OmpStructureChecker::Enter(const parser::OpenMPLoopConstruct &x) {
     EnterDirectiveNest(SIMDNest);
   }
 
+  if (CurrentDirectiveIsNested() &&
+      llvm::omp::topTeamsSet.test(GetContext().directive) &&
+      GetContextParent().directive == llvm::omp::Directive::OMPD_target &&
+      !GetDirectiveNest(TargetBlockOnlyTeams)) {
```
Comment (ergawy) [inline flang/lib/Semantics/check-omp-loop.cpp]: Not exactly relevant to this PR since a similar check is used somewhere else. But for the following example:
```
!$omp target ....
  !$omp teams ....
    !$omp target ....
      .... some statement ....
      !$omp teams ....
        ....
....
```

Would the semantic check trigger in this case? I think it won't since `GetDirectiveNest(TargetBlockOnlyTeams)` will return a non-zero result.

Comment (ergawy) [reply flang/lib/Semantics/check-omp-loop.cpp]: >I am torn between spending time fixing it on the one hand while on the other hand letting what seems to be an obscure case slide.

No need to fix it, at least in this PR. Specially since the test is used somewhere else. The way the directive-nest test is currently implemented is just surprising to me (seems a bit too permisive) and wanted to verify if this is really the case.

**Review by ergawy — APPROVED** [review]
