### PR TITLE
[clang-tidy] Fix crash in `cppcoreguidelines-pro-type-member-init` with alias template in constructor initializer

### LINKED ISSUE #192510: [clang-tidy] Check cppcoreguidelines-pro-type-member-init crashes with Qt code
This code (reduced from Qt headers) triggers a crash in clang-tidy check cppcoreguidelines-pro-type-member-init (see https://godbolt.org/z/58qnds39j):
```c++
#include <functional>

template<typename T>
struct C {};

template<typename T>
using CompactStorage = C<T>;

class QRunnable
{
public:
    constexpr QRunnable() noexcept = default;
private:
    class QGenericRunnable;
};

class QRunnable::QGenericRunnable : public QRunnable
{
    class HelperBase
    {
    protected:
        using OpFn = void (*)();
        OpFn fn;
    protected:
        constexpr explicit HelperBase(OpFn f) noexcept : fn(f) {}
    };

    template <typename Callable>
    class Helper : public HelperBase, private CompactStorage<Callable>
    {
        using Storage = CompactStorage<Callable>;
        static void impl()
        {}
    public:
        template <typename UniCallable>
        explicit Helper(UniCallable&& functionToRun) noexcept
            : HelperBase(&impl), Storage{ std::forward<UniCallable>(functionToRun) }
        {}
    };
};

int main()
{
    return 0;
}
```

The issue occurs on the main branch (upcoming clang 23). In clang 22 the same code works fine.

Here is the backtrace:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: /clang-tidy --checks=cppcoreguidelines-pro-type-member-init <source>
1.	<eof> parser at end of file
2.	ASTMatcher: Processing 'cppcoreguidelines-pro-type-member-init' against:
	CXXConstructorDecl QRunnable::QGenericRunnable::Helper::Helper<Callable> : <<source>:36:9, line:38:10>
--- Bound Nodes Begin ---
    ctor - { CXXConstructorDecl QRunnable::QGenericRunnable::Helper::Helper<Callable> : <<source>:36:9, line:38:10> }
    parent - { CXXRecordDecl QRunnable::QGenericRunnable::Helper : <<source>:29:5, line:39:5> }
--- Bound Nodes End ---
 #0 0x00000000057a03d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/clang-tidy+0x57a03d8)
 #1 0x000000000579d514 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000076e05aa42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x0000000000f9d0a0 clang::tidy::cppcoreguidelines::ProTypeMemberInitCheck::checkMissingBaseClassInitializer(clang::ASTContext const&, clang::CXXRecordDecl const&, clang::CXXConstructorDecl const*) (/clang-tidy+0xf9d0a0)
 #4 0x0000000000f9e424 clang::tidy::cppcoreguidelines::ProTypeMemberInitCheck::check(clang::ast_matchers::MatchFinder::MatchResult const&) (/clang-tidy+0xf9e424)
 #5 0x0000000003e9a9b9 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) ASTMatchFinder.cpp:0:0
 #6 0x0000000003ef2f0f clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) (/clang-tidy+0x3ef2f0f)
 #7 0x0000000003e9c89a clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) ASTMatchFinder.cpp:0:0
 #8 0x0000000003ed319d clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
 #9 0x0000000003ee02bc clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionTemplateDecl(clang::FunctionTemplateDecl*) ASTMatchFinder.cpp:0:0
#10 0x0000000003ed31a8 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#11 0x0000000003ed3c29 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) (.part.0) ASTMatchFinder.cpp:0:0
#12 0x0000000003ed1e8c clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#13 0x0000000003ed31a8 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#14 0x0000000003ee066c clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseClassTemplateDecl(clang::ClassTemplateDecl*) ASTMatchFinder.cpp:0:0
#15 0x0000000003ed31a8 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#16 0x0000000003ed3c29 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) (.part.0) ASTMatchFinder.cpp:0:0
#17 0x0000000003ed1e8c clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#18 0x0000000003ed31a8 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#19 0x0000000003ed3c29 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) (.part.0) ASTMatchFinder.cpp:0:0
#20 0x0000000003edfeb2 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) ASTMatchFinder.cpp:0:0
#21 0x0000000003ed31a8 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#22 0x0000000003ed34ad clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) (/clang-tidy+0x3ed34ad)
#23 0x0000000002d65dc8 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/clang-tidy+0x2d65dc8)
#24 0x0000000002f8612c clang::ParseAST(clang::Sema&, bool, bool) (/clang-tidy+0x2f8612c)
#25 0x0000000002d177da clang::FrontendAction::Execute() (/clang-tidy+0x2d177da)
#26 0x0000000002c9391d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/clang-tidy+0x2c9391d)
#27 0x00000000022a04b6 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/clang-tidy+0x22a04b6)
#28 0x000000000224ae67 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef, bool)::ActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) ClangTidy.cpp:0:0
#29 0x0000000002299e1c clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/clang-tidy+0x2299e1c)
#30 0x000000000229bfa0 clang::tooling::ToolInvocation::run() (/clang-tidy+0x229bfa0)
#31 0x000000000229e67c clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/clang-tidy+0x229e67c)
#32 0x000000000225c7a2 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef, bool) (/clang-tidy+0x225c7a2)
#33 0x0000000000cb1957 clang::tidy::clangTidyMain(int, char const**) (/clang-tidy+0xcb1957)
#34 0x000076e05aa29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#35 0x000076e05aa29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#36 0x0000000000ca38a5 _start (/clang-tidy+0xca38a5)
Program terminated with signal: SIGSEGV
```

### PR DESCRIPTION
**Pull request by flovent**
Closes #192510.

### CODE REVIEW

**Comment by flovent** [comment]
This seems been related to #190521, a recent commit, do we need a release note for recent regression?

**Comment by flovent** [comment]
Well, for windows there will be no `CXXCtorInitializer` in ctor, so i remove the check-message (it will be reported in other systems but not windows): 

Windows:
```
`-CXXConstructorDecl <line:15:5, col:12> col:5 X<T> 'void (INT)' implicit-inline
        |-ParmVarDecl <col:7, col:11> col:11 i 'INT':'C<T>'
        `-<<<NULL>>>
```
Linux:
```
-CXXConstructorDecl <line:15:5, col:24> col:5 X<T> 'void (INT)' implicit-inline
        |-ParmVarDecl <col:7, col:11> col:11 referenced i 'INT':'C<T>'
        |-CXXCtorInitializer 'INT':'C<T>'
        | `-ParenListExpr <col:19, col:21> 'NULL TYPE'
        |   `-DeclRefExpr <col:20> 'INT':'C<T>' lvalue ParmVar 0x21813138 'i' 'INT':'C<T>'
        `-CompoundStmt <col:23, col:24>
```

**Comment by zeyi2** [comment]
> This seems been related to #190521, a recent commit, do we need a release note for recent regression?

Personally I don't think it is necessary :)

**Review by zeyi2 — APPROVED** [review]
LGTM

**Review by vbvictor — APPROVED** [review]
LGTM, thank you for fixing this

**Comment by zwuis** [comment]
Note that the original crash reproducer is **valid** code, so

- the added test case is **invalid**, which doesn't represent the original reproducer, and
- the added comment is wrong.

**Comment by flovent** [comment]
> * the added test case is **invalid**, which doesn't represent the original reproducer, and

I think i verified this added case will crash before this patch, and the original reproducer doesn't crash now too(https://godbolt.org/z/GW8YhxGbs), any more details?

> * the added comment is wrong.

You are saying this is a FP?

**Comment by zwuis** [comment]
> > * the added test case is **invalid**, which doesn't represent the original reproducer, and
> 
> I think i verified this added case will crash before this patch, and the original reproducer doesn't crash now too(https://godbolt.org/z/GW8YhxGbs), any more details?

I see. Thanks for the clarification.

> > * the added comment is wrong.
> 
> You are saying this is a FP?

No. The root cause is `getAsCXXRecordDecl` returns `nullptr` for dependent types, regardless of whether it is a target base class. If we change the test to `class X: public C<T>`, it still crashed.

**Comment by flovent** [comment]
>  The root cause is getAsCXXRecordDecl returns nullptr for dependent types, regardless of whether it is a target base class.


I think this is the thing fixed in this PR, we check `getAsCXXRecordDecl`'s return value before using it.

From:
```
BasesToInit.erase(
            Init->getBaseClass()->getAsCXXRecordDecl()->getCanonicalDecl());
```

To:
```
if (const CXXRecordDecl *CRD =
                Init->getBaseClass()->getAsCXXRecordDecl())
          BasesToInit.erase(CRD->getCanonicalDecl());
      }
```

`class X: public C<T>` doesn't seem to crash in trunk: https://godbolt.org/z/dq6rWh6jG

File: clang-tools-extra/clang-tidy/cppcoreguidelines/ProTypeMemberInitCheck.cpp [hunk 1]
```diff
@@ -571,9 +571,13 @@ void ProTypeMemberInitCheck::checkMissingBaseClassInitializer(
       return;
 
     for (const CXXCtorInitializer *Init : Ctor->inits())
-      if (Init->isBaseInitializer() && Init->isWritten())
-        BasesToInit.erase(
-            Init->getBaseClass()->getAsCXXRecordDecl()->getCanonicalDecl());
+      if (Init->isBaseInitializer() && Init->isWritten()) {
+        // In template AST BaseInitializer could be generated too even if it's
+        // not target to base class.
```
Comment (zwuis) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/ProTypeMemberInitCheck.cpp:576]: I meant this comment is wrong.

The fix is correct indeed.

Comment (flovent) [reply clang-tools-extra/clang-tidy/cppcoreguidelines/ProTypeMemberInitCheck.cpp:576]: Oh, i see now. Since it's suitable for all dependent types, i am thinking maybe deleting it, WDYT?

Comment (zwuis) [reply clang-tools-extra/clang-tidy/cppcoreguidelines/ProTypeMemberInitCheck.cpp:576]: SGTM.

Comment (flovent) [reply clang-tools-extra/clang-tidy/cppcoreguidelines/ProTypeMemberInitCheck.cpp:576]: Thanks for catching, just created #205477.
