### PR TITLE
[flang][OpenMP] Error out when CHARACTER type is used in atomic constructs

### LINKED ISSUE #112918: [flang][OpenMP] Add a semantic check to prevent atomic operations on character variables
```
program o30_301
  character(2) hi
  !$omp atomic write
    hi = 'hi'
  !$omp end atomic
end program
```

Fails with `not yet implemented: Unsupported atomic type`. The wording of the standard is that atomic operations should operate on "scalar variables of intrinsic type" (OpenMP 5.2 section 4.3.1.3).

In Fortran 2023, a scalar variable is defined (3.119) as "data entity that can be represented by a single value of the type and that is not an array". I think that means that a the `character` variable in the above example is scalar and of intrinsic type.

gfortran and classic flang do not allow character variables in atomic types.

### PR DESCRIPTION
**Pull request by NimishMishra**
According to OpenMPv5.2 1.2.6, "For Fortran, a scalar variable with intrinsic type, as defined by the base language, excluding character type.". Likewise, section 4.3.1.3 states that atomic operations are on "scalar variables of intrinsic type". This PR hence introduces a check to error out when CHARACTER type is used in atomic operations.

Fixes https://github.com/llvm/llvm-project/issues/112918

### CODE REVIEW

File: flang/lib/Lower/DirectivesCommon.h [hunk 1]
```diff
@@ -128,6 +128,7 @@ static void processOmpAtomicTODO(mlir::Type elementType,
                              Fortran::parser::OmpAtomicClauseList>()) {
     // Based on assertion for supported element types in OMPIRBuilder.cpp
     // createAtomicRead
+    // TODO: Enumerate remaining unsupported types for atomics
     mlir::Type unwrappedEleTy = fir::unwrapRefType(elementType);
     bool supportedAtomicType = fir::isa_trivial(unwrappedEleTy);
```
Comment (NimishMishra) [inline flang/lib/Lower/DirectivesCommon.h:133]: Should we let this in? Or we are in a position to remove this? I didn't remove right now; thought to ask once.

Comment (tblah) [reply flang/lib/Lower/DirectivesCommon.h:133]: I agree it can be replaced by an assertion

**Review by tblah — APPROVED** [review]
Thanks for the quick fix!

File: flang/lib/Lower/DirectivesCommon.h (hunk 1 above)
Comment (tblah) [reply flang/lib/Lower/DirectivesCommon.h:133]: I would replace the function with something like `assert(fir::isa_trivial(fir::unwrapRefType(elementType)) && "is supported type for omp atomic")`

**Comment by NimishMishra** [comment]
This commit (https://github.com/llvm/llvm-project/commit/8ad8db973eb7b9a8100a03c485f2797fb7819119) reverts a MLIR Tosa commit which caused buildbot failures. 

I see aarch64 flang buildbots are clean now.
