### PR TITLE
[SCEV] Do not allow refinement in the rewriting of BEValue

### LINKED ISSUE #117133: [indvars] Miscompile when loop body has an operation with Undefined Behaviour
Here is the problematic IR:
```
define i32 @widget() {
bb:
  br label %bb1

bb1:                                              ; preds = %bb5, %bb
  %phi = phi i32 [ 0, %bb ], [ %udiv6, %bb5 ]
  %phi2 = phi i32 [ 1, %bb ], [ %add, %bb5 ]
  %icmp = icmp eq i32 %phi, 0
  br i1 %icmp, label %bb3, label %bb8

bb3:                                              ; preds = %bb1
  %udiv = udiv i32 10, %phi2
  %urem = urem i32 %udiv, 10
  %icmp4 = icmp eq i32 %urem, 0
  br i1 %icmp4, label %bb7, label %bb5

bb5:                                              ; preds = %bb3
  %udiv6 = udiv i32 %phi2, 0
  %add = add i32 %phi2, 1
  br label %bb1

bb7:                                              ; preds = %bb3
  ret i32 5

bb8:                                              ; preds = %bb1
  ret i32 7
}
```
produces incorrect IR when `indvars` pass is run. I suspect this is because of the `%udiv6 = udiv i32 %phi2, 0` divide by zero operation. 
Look at the indvars transformation here: https://godbolt.org/z/cz1r5178h
The original IR must return 5, while the transformed IR returns 7

Proof of wrong transformation: https://alive2.llvm.org/ce/z/vPFhzg

### PR DESCRIPTION
**Pull request by dtcxzyw**
See the following case:
```
; bin/opt -passes="print<scalar-evolution>" test.ll --disable-output
define i32 @widget() {
b:
  br label %b1

b1:                                              ; preds = %b5, %b
  %phi = phi i32 [ 0, %b ], [ %udiv6, %b5 ]
  %phi2 = phi i32 [ 1, %b ], [ %add, %b5 ]
  %icmp = icmp eq i32 %phi, 0
  br i1 %icmp, label %b3, label %b8

b3:                                              ; preds = %b1
  %udiv = udiv i32 10, %phi2
  %urem = urem i32 %udiv, 10
  %icmp4 = icmp eq i32 %urem, 0
  br i1 %icmp4, label %b7, label %b5

b5:                                              ; preds = %b3
  %udiv6 = udiv i32 %phi2, 0
  %add = add i32 %phi2, 1
  br label %b1

b7:                                              ; preds = %b3
  ret i32 5

b8:                                              ; preds = %b1
  ret i32 7
}
```
```
%phi2 = phi i32 [ 1, %b ], [ %add, %b5 ] -->  {1,+,1}<nuw><nsw><%b1>
%udiv6 = udiv i32 %phi2, 0 --> ({1,+,1}<nuw><nsw><%b1> /u 0)
%phi = phi i32 [ 0, %b ], [ %udiv6, %b5 ] --> ({0,+,1}<nuw><nsw><%b1> /u 0)
```
`ScalarEvolution::createAddRecFromPHI` gives a wrong SCEV result for `%phi`:
https://github.com/llvm/llvm-project/blob/d7d6fb1804415b0f3e7f1cc9290bfb3d711cb707/llvm/lib/Analysis/ScalarEvolution.cpp#L5926-L5950
It converts `phi(0, ({1,+,1}<nuw><nsw><%b1> /u 0))` into `phi(0 / 0, ({1,+,1}<nuw><nsw><%b1> /u 0))`. Then it simplifies the expr into `{0,+,1}<nuw><nsw><%b1> /u 0`.

As we did in https://github.com/llvm/llvm-project/commit/acd700a24b6f767413db3d525e06d03e4245aa40, this patch disallows udiv simplification if we cannot prove that the denominator is a well-defined non-zero value.

Fixes https://github.com/llvm/llvm-project/issues/117133.

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
I don't think that this approach is correct. If I understand correctly, you're basically trying to add the invariant that simplification of SCEV expressions must preserve undefined behavior. But to achieve that, this would be only a very partial implementation, e.g. we could also lose it through `%div * 0` or `%div - %div` or any number of other ways.

I think the problem here is rather in that particular addrec construction code. We basically have a derefinement issue here, similar to what we see in select simplification.

We could hit similar derefinement issues with poison rather than UB, probably some example involving `umin_seq(%maybe_poison, 0)`. And with @fhahn's patches for per-use nowrap flags, this would become a more significant problem.

So I think what we need to guard against is derefinement when replacing the start value.

**Comment by dtcxzyw** [comment]
> If I understand correctly, you're basically trying to add the invariant that simplification of SCEV expressions must preserve undefined behavior.

Yeah. For this case, `ScalarEvolution::createAddRecFromPHI` only checks `initval == refine(f(0))`. It doesn't imply `initval == f(0)`.

> I think the problem here is rather in that particular addrec construction code. We basically have a derefinement issue here, similar to what we see in select simplification.

Do we need an `AllowRefinement` argument for SCEV constructors and disallow refinement in these rewriters?

**Comment by nikic** [comment]
> Do we need an AllowRefinement argument for SCEV constructors and disallow refinement in these rewriters?

Assuming this special case isn't particularly important, can we get away with just checking that the SCEV doesn't contain UB / poison?

File: llvm/lib/Analysis/ScalarEvolution.cpp [hunk 1]
```diff
@@ -5933,18 +5925,21 @@ const SCEV *ScalarEvolution::createAddRecFromPHI(PHINode *PN) {
...
-      if (Start == StartVal) {
-        // Okay, for the entire analysis of this edge we assumed the PHI
-        // to be symbolic.  We now need to go back and purge all of the
-        // entries for the scalars that use the symbolic expression.
-        forgetMemoizedResults(SymbolicName);
-        insertValueToMap(PN, Shifted);
-        return Shifted;
+
+    // Do not allow refinement in rewriting of BEValue.
+    if (isGuaranteedNotToCauseUB(BEValue)) {
```
Comment (dtcxzyw) [inline llvm/lib/Analysis/ScalarEvolution.cpp:5930]: Not sure whether we need `isGuaranteedNotToBePoison` here. IIRC SCEV doesn't leverage poison to refine expressions:

> // The only way poison may be introduced in a SCEV expression is from a
// poison SCEVUnknown (ConstantExprs are also represented as SCEVUnknown,
// not SCEVConstant). Notably, nowrap flags in SCEV nodes can *not*
// introduce poison -- they encode guaranteed, non-speculated knowledge.

Comment (nikic) [reply llvm/lib/Analysis/ScalarEvolution.cpp:5930]: Poison is still a problem if we, for example, replace `0` with `0 *  %a`. Maybe a bit tricky to get things in the right form so it doesn't simplify, but something like `phi(0, zext({1,+,1}) * %a)` (where the addrec is not nuw so zext doesn't fold) might do? The shifted form would be `zext({0,+,1}) * %a` and the shifted start would be `zext(0) * a` which is `0`. But we can't replace 0 by `zext({0,+,1}) * %a`, as it may be more poisonous.

**Comment by Nirhar** [comment]
ping @dtcxzyw !

File: llvm/lib/Analysis/ScalarEvolution.cpp (hunk 1 above)
Comment (dtcxzyw) [reply llvm/lib/Analysis/ScalarEvolution.cpp]: Done.

File: llvm/lib/Analysis/ScalarEvolution.cpp [hunk 2]
```diff
@@ -5933,18 +5925,22 @@ const SCEV *ScalarEvolution::createAddRecFromPHI(PHINode *PN) {
...
-        // Okay, for the entire analysis of this edge we assumed the PHI
-        // to be symbolic.  We now need to go back and purge all of the
-        // entries for the scalars that use the symbolic expression.
-        forgetMemoizedResults(SymbolicName);
-        insertValueToMap(PN, Shifted);
-        return Shifted;
+
+    // Do not allow refinement in rewriting of BEValue.
+    if (isGuaranteedNotToCauseUB(BEValue) &&
+        isGuaranteedNotToBePoison(BEValue)) {
```
Comment (nikic) [inline llvm/lib/Analysis/ScalarEvolution.cpp:5931]:
```suggestion
        impliesPoisoin(BEValue. StartVal)) {
```
I think something like that could avoid most of the test changes? The problem is that we often have something like `phi(%x, {%x,+,1})`, which is unproblematic here but will be rejected by a plain poison check.

File: llvm/test/Analysis/ScalarEvolution/fold.ll [hunk 3]
```diff
@@ -214,7 +214,7 @@ define i64 @test10(i64 %a, i64 %b) {
   ret i64 %t2
 }
 
-define i64 @test11(i64 %a) {
+define i64 @test11(i64 noundef range(i64 1, 0) %a) {
```
Comment (nikic) [inline llvm/test/Analysis/ScalarEvolution/fold.ll:217]: Not needed?

File: llvm/test/Analysis/ScalarEvolution/udiv-of-x-xsmaxone-fold.ll [hunk 4]
```diff
@@ -1,7 +1,7 @@
 ; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
 ; RUN: opt -disable-output -passes="print<scalar-evolution>" < %s 2>&1 | FileCheck %s
 
-define i32 @test_expr_with_constant_1(i32 %x) {
+define i32 @test_expr_with_constant_1(i32 noundef range(i32 1, 0) %x) {
```
Comment (nikic) [inline llvm/test/Analysis/ScalarEvolution/udiv-of-x-xsmaxone-fold.ll:4]: Not needed?

File: llvm/test/Analysis/ScalarEvolution/pr117133.ll
Comment (nikic) [inline llvm/test/Analysis/ScalarEvolution/pr117133.ll:1]: It would be great to construct a test case where poison is problematic.

File: llvm/test/Analysis/ScalarEvolution/pr117133.ll [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+
+b7:                                              ; preds = %b3
+  ret i32 5
+
+b8:                                              ; preds = %b1
+  ret i32 7
+}
+
+; Don't fold %indvar2 into (zext {0,+,1}) * %a
+define i64 @test_poisonous(i64 %a, i32 %n) {
```
Comment (dtcxzyw) [inline llvm/test/Analysis/ScalarEvolution/pr117133.ll:56]: Before:
```
Printing analysis 'Scalar Evolution Analysis' for function 'test':
Classifying expressions for: @test
  %indvar1 = phi i32 [ 0, %entry ], [ %indvar1.next, %loop.body ]
  -->  {0,+,1}<%loop.body> U: full-set S: full-set              Exits: <<Unknown>>              LoopDispositions: { %loop.body: Computable }
  %indvar2 = phi i64 [ 0, %entry ], [ %mul, %loop.body ]
  -->  ((zext i32 {0,+,1}<%loop.body> to i64) * %a) U: full-set S: full-set             Exits: <<Unknown>>              LoopDispositions: { %loop.body: Computable }
  %indvar1.next = add i32 %indvar1, 1
  -->  {1,+,1}<%loop.body> U: full-set S: full-set              Exits: <<Unknown>>              LoopDispositions: { %loop.body: Computable }
  %ext = zext i32 %indvar1.next to i64
  -->  (zext i32 {1,+,1}<%loop.body> to i64) U: [0,4294967296) S: [0,4294967296)                Exits: <<Unknown>>              LoopDispositions: { %loop.body: Computable }
  %mul = mul i64 %ext, %a
  -->  ((zext i32 {1,+,1}<%loop.body> to i64) * %a) U: full-set S: full-set             Exits: <<Unknown>>              LoopDispositions: { %loop.body: Computable }
```

**Review by nikic — APPROVED** [review]
LGTM
