### PR TITLE
[InstCombine] Fix `frexp(frexp(x)) -> frexp(x)` fold

### LINKED ISSUE #138819: InstSimplify: incorrect frexp(frexp(x)) -> frexp(x) fold
It's not ok to fold `frexp(frexp(x))` to `frexp(x)`:

```llvm
; Transforms/InstSimplify/frexp.ll

define {float, i32} @frexp_frexp(float %x) {
  %frexp0 = frexp float %x
  %frexp0.0 = extractvalue {float, i32} %frexp0, 0
  %frexp1 = frexp float %frexp0.0
  ret {float, i32} %frexp1
}
=>
define {float, i32} @frexp_frexp(float %x) {
  %frexp0 = frexp float %x
  ret {float, i32} %frexp0
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:
float %x = #x0000000a (0.000000000000?)

Source:
{float, i32} %frexp0 = { #x3f200000 (0.625), #xffffff6f (4294967151, -145) }
float %frexp0.0 = #x3f200000 (0.625)
{float, i32} %frexp1 = { #x3f200000 (0.625), #x00000000 (0) }

Target:
{float, i32} %frexp0 = { #x3f200000 (0.625), #xffffff6f (4294967151, -145) }
Source value: { #x3f200000 (0.625), #x00000000 (0) }
Target value: { #x3f200000 (0.625), #xffffff6f (4294967151, -145) }
```

cc @arsenm

### PR DESCRIPTION
**Pull request by el-ev**
Fixes #138819

When frexp is applied twice, the second result should be zero.

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 1]
```diff
@@ -3799,6 +3799,18 @@ Instruction *InstCombinerImpl::visitCallInst(CallInst &CI) {
     }
     break;
   }
+  case Intrinsic::frexp: {
+    Value *X;
+    // Frexp is idempotent with the added complication of the struct return.
+    if (match(II->getArgOperand(0), m_ExtractValue<0>(m_Value(X)))) {
+      if (match(X, m_Intrinsic<Intrinsic::frexp>(m_Value()))) {
+        X = Builder.CreateInsertValue(
+            X, ConstantInt::get(II->getType()->getStructElementType(1), 0), 1);
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp:3808]: Constant::getNullValue?

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 2]
```diff
@@ -3799,6 +3799,18 @@ Instruction *InstCombinerImpl::visitCallInst(CallInst &CI) {
     }
     break;
   }
+  case Intrinsic::frexp: {
+    Value *X;
+    // Frexp is idempotent with the added complication of the struct return.
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp:3804]: Adjust the comment for the integer result

**Review by arsenm — APPROVED** [review]

**Review by arsenm — APPROVED** [review]
