### PR TITLE
[clang-format] Correctly annotate token-pasted function decl names

### LINKED ISSUE #142178: clang-format regression with spaces around trailing-return-type
Here is my clang-format file:
```
BasedOnStyle: llvm

AccessModifierOffset: -4
AlignConsecutiveBitFields: Consecutive
AlignEscapedNewlines: Right
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortFunctionsOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: true
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: BeforeComma
BraceWrapping:
  BeforeElse: true
  BeforeCatch: true
ColumnLimit: 100
ConstructorInitializerAllOnOneLineOrOnePerLine: true
IndentWidth: 4
InsertBraces: true
NamespaceIndentation: None
PenaltyBreakAssignment: 60
PenaltyBreakBeforeFirstCallParameter: 175
PointerAlignment: Left
QualifierAlignment: Custom
QualifierOrder: ['static', 'inline', 'constexpr', 'type', 'const', 'volatile']
SortIncludes: true
SortUsingDeclarations: true
SpaceAfterCStyleCast: true
SpaceAfterTemplateKeyword: true
SpacesBeforeTrailingComments: 2
SpacesInSquareBrackets: false
```

On clang 17.0.6, I get this formatting:
```cpp
#define DEFINE_CHECKED(name, op)                                                                   \
    template <typename R, std::integral A, std::integral B>                                        \
    constexpr auto checked_##name(A a, B b) -> CheckedResult<R> {                                  \
        return something_interesting(a, b);                                                        \
    }

DEFINE_CHECKED(add, +)
```
On clang 18.1.4 and later, I started getting this formatting:
```cpp
#define DEFINE_CHECKED(name, op)                                                                   \
    template <typename R, std::integral A, std::integral B>                                        \
    constexpr auto checked_##name(A a, B b)->CheckedResult<R> {                                    \
        return something_interesting(a, b);                                                        \
    }

DEFINE_CHECKED(add, +)
```

The spaces around the trailing-return-type are now absent, as if the formatter things this is class member access instead of being a function declaration. I'm not sure exactly when the change happened, those are just two versions I have handy.

### PR DESCRIPTION
**Pull request by owenca**
Fix #142178

### CODE REVIEW

**Comment by prj-** [comment]
Looking forward to testing this out!

**Comment by owenca** [comment]
> Looking forward to testing this out!

I already tested it with your reproducer in https://github.com/llvm/llvm-project/pull/142251#issuecomment-2928718530.

**Comment by prj-** [comment]
Unfortunately, we have many other use-cases for triggering regressions in our code (hence why we are having this discussion in the first place 😅), but hopefully all will be good afterwards.

**Comment by owenca** [comment]
@prj- I understand. If you use `AlignFunctionDeclarations`, you might see formatting changes as the first token in a token-pasted function decl name was not annotated correctly before this patch.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -2257,6 +2257,13 @@ TEST_F(TokenAnnotatorTest, UnderstandsFunctionDeclarationNames) {
   EXPECT_TOKEN(Tokens[1], tok::identifier, TT_FunctionDeclarationName);
   EXPECT_TOKEN(Tokens[2], tok::l_paren, TT_FunctionDeclarationLParen);
 
+  Tokens = annotate("#define FUNC(foo, bar) \\\n"
+                    "  auto foo##bar() -> Type {}");
+  ASSERT_EQ(Tokens.size(), 19u) << Tokens;
+  EXPECT_TOKEN(Tokens[9], tok::identifier, TT_FunctionDeclarationName);
+  EXPECT_TOKEN(Tokens[12], tok::l_paren, TT_FunctionDeclarationLParen);
+  EXPECT_TOKEN(Tokens[14], tok::arrow, TT_TrailingReturnArrow);
+
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:2266]: Shouldn't we add some of the stuff, which were wrong on the last try?

File: clang/lib/Format/TokenAnnotator.cpp [hunk 2]
```diff
@@ -3848,6 +3848,8 @@ static bool isFunctionDeclarationName(const LangOptions &LangOpts,
   } else {
     if (Current.isNot(TT_StartOfName) || Current.NestingLevel != 0)
       return false;
+    while (Next && Next->startsSequence(tok::hashhash, tok::identifier))
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/TokenAnnotator.cpp:3851]: There should be a test, where this actually loops.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:2266]: Not really as the last try was reverted and we are doing it afresh here. It would be silly to add:
```
EXPECT_TOKEN(Tokens[11], tok::identifier, TT_Unknown);  // Not TT_FunctionDeclarationName
```
because this was the case before that reverted patch and before this patch (after that patch was reverted).

File: clang/lib/Format/TokenAnnotator.cpp (hunk 2 above)
Comment (owenca) [reply clang/lib/Format/TokenAnnotator.cpp:3851]: +1. Updated the test case.

**Review by HazardyKnusperkeks — APPROVED** [review]
