### PR TITLE
[Coverage] Let `Decision` take account of expansions

### LINKED ISSUE #77871: Malformed MC/DC Coverage record with macro definitions
Clang -fcoverage-mcdc emits malformed records to crash llvm-cov with `assert(NumConds == 0);` if:

1. At least two decisions (passes with one decision)
2. Each expression has terms that come from macro definitions

Reproducible code (https://godbolt.org/z/xMGPafdvG)
```
#define D 1

extern void bar(void);

void foo(int a, int b) {
  if (a && D) bar();
  if (b && D) bar();
}
```

Unexpected `Branch` order will be seen.

```
  Decision,File 0, 6:7 -> 6:13 = M:0, C:2
  Branch,File 0, 6:7 -> 6:8 = #2, (#0 - #2) [1,2,0] 
  Expansion,File 0, 6:12 -> 6:13 = #2 (Expanded file = 1)
...
  Decision,File 0, 7:7 -> 7:13 = M:1, C:2
  Branch,File 0, 7:7 -> 7:8 = #5, (#0 - #5) [1,2,0] 
  Expansion,File 0, 7:12 -> 7:13 = #5 (Expanded file = 2)
...
  Branch,File 1, 1:11 -> 1:12 = 0, 0 [2,0,0] 
...
  Branch,File 2, 1:11 -> 1:12 = 0, 0 [2,0,0] 
```
("Decision, branch, branch, decision, branch, branch" is expected)

### PR DESCRIPTION
**Pull request by chapuni**
The current implementation (D138849) assumes `Branch`(es) would follow after the corresponding `Decision`. It is not true if `Branch`(es) are forwarded to expanded file ID. As a result, consecutive `Decision`(s) would be confused with insufficient number of `Branch`(es).

`Expansion` will point `Branch`(es) in other file IDs if `Expansion` is included in the range of `Decision`.

Fixes #77871

### CODE REVIEW

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 1]
```diff
@@ -662,23 +724,39 @@ Error CoverageMapping::loadFunctionRecord(
...
 
       // As we move through all of the MCDCBranchRegions that follow the
       // MCDCDecisionRegion, decrement NumConds to make sure we account for
       // them all before we calculate the bitmap of executed test vectors.
-      if (--NumConds == 0) {
+      switch (Decision.updateBranch(Region)) {
+      case DecisionRow::UpdateResult::NotFound:
+        continue;
+      case DecisionRow::UpdateResult::Updated:
+        goto branch_found;
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:751]: Why `goto`?

```
bool BranchFound = false;
switch(...) {
case DecisionRow::UpdateResult::Updated:
    BranchFound = true;
    break;
...
}
(void)BranchFound;
assert(BranchFound && "Did not find a branch?!");
```

Alternatively, we could return an `Error` when `BranchFound == false`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 2]
```diff
@@ -662,23 +724,39 @@ Error CoverageMapping::loadFunctionRecord(
     }
     Function.pushRegion(Region, *ExecutionCount, *AltExecutionCount);
 
+    if (Region.Kind == CounterMappingRegion::ExpansionRegion) {
+      for (auto &Decision : reverse(Decisions)) {
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:728]: would it make sense to use something like `any_of` here?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 3]
```diff
@@ -580,6 +583,72 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
   return MaxBitmapID + (SizeInBits / CHAR_BIT);
 }
 
+struct DecisionRow {
+  const CounterMappingRegion *DecisionRegion;
+  LineColPair DecisionStartLoc;
+  LineColPair DecisionEndLoc;
+
+  SmallVector<const CounterMappingRegion *, 6> Branches;
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:591]: why 6?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 4]
```diff
@@ -580,6 +583,72 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
   return MaxBitmapID + (SizeInBits / CHAR_BIT);
 }
 
+struct DecisionRow {
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:586]: add doxygen comment

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 5]
```diff
@@ -580,6 +583,72 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+  UpdateResult updateBranch(const CounterMappingRegion &Branch) {
+    if (IDs.contains(Branch.MCDCParams.ID))
+      return UpdateResult::NotFound;
+
+    if (Branch.FileID == DecisionRegion->FileID &&
+        Branch.startLoc() >= DecisionStartLoc &&
+        Branch.endLoc() <= DecisionEndLoc)
+      return (insert(Branch) ? UpdateResult::Committed : UpdateResult::Updated);
+
+    for (const auto *R : Expansions) {
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:624]: looks like `any_of`

```
if (any_of(Expansions, [&Branch](const CounterMappingRegion *R) {
  return Branch.FileID == R->ExpandedFileID; })
    return insert(Branch) ? ...;
```

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 6]
```diff
@@ -445,11 +447,11 @@ class MCDCRecordProcessor {
     //   visualize where the condition is.
     // - Record whether the condition is constant folded so that we exclude it
     //   from being measured.
-    for (const auto &B : Branches) {
-      Map[B.MCDCParams.ID] = &B;
-      PosToID[I] = B.MCDCParams.ID - 1;
-      CondLoc[I] = B.startLoc();
-      Folded[I++] = (B.Count.isZero() && B.FalseCount.isZero());
+    for (const auto *B : Branches) {
+      Map[B->MCDCParams.ID] = B;
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:451]: assert `B` is not null?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 7]
```diff
@@ -580,6 +583,72 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+      : DecisionRegion(&Decision), DecisionStartLoc(Decision.startLoc()),
+        DecisionEndLoc(Decision.endLoc()) {}
+
+  bool insert(const CounterMappingRegion &Branch) {
+    auto ID = Branch.MCDCParams.ID;
+    if (ID == 1)
+      Branches.insert(Branches.begin(), &Branch);
+    else
+      Branches.push_back(&Branch);
+    IDs.insert(ID);
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:605]: are all IDs expected to be unique?

**Comment by evodius96** [comment]
I'd be OK going this direction as opposed to https://github.com/llvm/llvm-project/pull/78819, since it doesn't have to scan ahead to add branch regions, but it does add new complexity to the tracking. Can you also post your tests?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 6 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:451]: This is in #78918.
I don't think `B` could be null, since `Branches` is pushed with only `Region&`.
Any other concerns?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 4 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:588]: I have added comments in `DecisionRow`. Please give me suggestions.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 3 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:598]: For now, the maximum number of conditions is 6.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 2 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:744]: I have rewritten whole things in `DecisionRow`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 1 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:767]: Why NOT goto? I prefer it rather than relying on a variable.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 8]
```diff
@@ -580,6 +583,72 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+
+  bool updateExpansion(const CounterMappingRegion &Expansion) {
+    if (Expansion.FileID == DecisionRegion->FileID &&
+        Expansion.startLoc() >= DecisionStartLoc &&
+        Expansion.endLoc() <= DecisionEndLoc) {
+      Expansions.push_back(&Expansion);
+      return true;
+    }
+
+    for (const auto *R : Expansions) {
```
[the remark this answers is not in the document]
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: I have introduced `inExpansions(R)`.

**Review by chapuni — COMMENTED** [review]
I have rewritten `DecisionRow` and added comments.

Tests are not ready. Please be patient.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 7 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: Yes.

I had to introduce `DenseMap` to distinguish parallel sets of `Branch`(es).

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 4 above)
Comment (ornata) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:588]: What does it represent in the MC/DC algorithm?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 3 above)
Comment (ornata) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:598]: Worth a comment?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 9]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+  DenseSet<CounterMappingRegion::MCDCConditionID> IDs;
+
+  /// Relevant `Expansion`(s) should be caught to find expanded Branches.
+  SmallVector<const CounterMappingRegion *> Expansions;
+
+  DecisionRow(const CounterMappingRegion &Decision)
+      : DecisionRegion(&Decision), DecisionStartLoc(Decision.startLoc()),
+        DecisionEndLoc(Decision.endLoc()) {}
+
+  /// Determine whether `R` is included in `DecisionRegion`.
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:610]: Nit:

- Use `\p` or `\param` in Doxygen. (http://www.doxygen.jp/commands.html#cmdp)
- Backticks unnecessary in Doxygen.

E.g.

```
\returns true if \p R is included in DecisionRegion
```

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 10]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+    Updated,
+    Completed,
+  };
+
+  /// Add `Branch` into the Decision
+  UpdateResult updateBranch(const CounterMappingRegion &Branch) {
+    auto ID = Branch.MCDCParams.ID;
+    assert(ID > 0 && "MCDCBranch.ID should begin with 1");
+
+    if (!IDs.contains(ID) &&
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:634]: You can reduce indentation in this code by negating this `if`:

```
if (IDs.contains(ID) || (!inDecisionRegion(Branch) && !inExpansions(Branch))
  return UpdateResult::NotFound;
const auto NumConditions = DecisionRegion->MCDCParams.NumConditions;
assert(Branches.size() < NumConditions && "Have more than the max number of conditions?!");
/*...*/
return Branches.size() == NumConditions ? UpdateResult::Completed : UpdateResult::Updated;
```

It seems a little strange to me that `IDs.contains(ID)` means we return `UpdateResult::NotFound`. Why is that?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 11]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+      return UpdateResult::NotFound;
+  }
+
+  /// Record `Expansion` if it is dominated to the Decision.
+  /// Each `Expansion` may nest.
+  bool updateExpansion(const CounterMappingRegion &Expansion) {
+    if (inDecisionRegion(Expansion) || inExpansions(Expansion)) {
+      Expansions.push_back(&Expansion);
+      return true;
+    } else
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:662]: this `else can be removed`

IMO, the `if` should be negated as well:

```
// Check if the expansion is dominated by the decision region.
if (!inDecisionRegion(Expansion) && !inExpansions(Expansion))
  return false;
// It is dominated. Record it.
Expansions.push_back(&Expansion);
return true;
```

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 12]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+  }
+
+  /// Determin whether `R` is pointed by any of Expansions.
+  bool inExpansions(const CounterMappingRegion &R) {
+    return any_of(Expansions, [&](const auto &Expansion) {
+      return (Expansion->ExpandedFileID == R.FileID);
+    });
+  }
+
+  enum class UpdateResult {
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:623]: This should be documented

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 1 above)
Comment (ornata) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:767]: I think that maybe the `goto` is a sign that this switch should be pulled into a function.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 13]
```diff
@@ -664,23 +740,39 @@ Error CoverageMapping::loadFunctionRecord(
...
+
     // If a MCDCDecisionRegion was seen, store the BranchRegions that
     // correspond to it in a vector, according to the number of conditions
     // recorded for the region (tracked by NumConds).
-    if (NumConds > 0 && Region.Kind == CounterMappingRegion::MCDCBranchRegion) {
-      MCDCBranches.push_back(&Region);
+    for (int I = Decisions.size() - 1; I >= 0; --I) {
+      auto &Decision = Decisions[I];
 
       // As we move through all of the MCDCBranchRegions that follow the
```
[the remark this answers is not in the document]
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:760]: Yes, I know I have to revise them below.

**Review by chapuni — COMMENTED** [review]
TODO:
- Revise comments in the latter half
- Construct tests

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 14]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+      return (Branches.size() == DecisionRegion->MCDCParams.NumConditions
+                  ? UpdateResult::Completed
+                  : UpdateResult::Updated);
+    } else
+      return UpdateResult::NotFound;
+  }
+
+  /// Record `Expansion` if it is dominated to the Decision.
+  /// Each `Expansion` may nest.
+  bool updateExpansion(const CounterMappingRegion &Expansion) {
```
Comment (chapuni) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:658]: Is it better with `updateExpansions` (than `addExpansion`)?

I suppose this updates the status of expansions, even if this is appending actually.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 1 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:767]: I've noticed that `Decisions` can be encapsulated. I supposed it was still a simple vector.

I don't think `goto` is absolutely evil, though!

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 14 above)
Comment (ornata) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:658]: Maybe

```
addDominatedExpansionToList
```

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 15]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+
+  /// They are reflected from `DecisionRegion` for convenience.
+  LineColPair DecisionStartLoc;
+  LineColPair DecisionEndLoc;
+
+  /// This is passed to `MCDCRecordProcessor`, so this should be compatible to
+  /// `ArrayRef<const CounterMappingRegion *>`.
+  SmallVector<const CounterMappingRegion *, 6> Branches;
+
+  /// Each `ID` in `Branches` should be unique.
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:600]: I think this comment needs to be updated

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 16]
```diff
@@ -582,6 +583,87 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
   return MaxBitmapID + (SizeInBits / CHAR_BIT);
 }
 
+/// This holds the DecisionRegion and MCDCBranch(es) under it.
+/// Also traverses Expansion(s).
+struct DecisionRow {
+  /// The subject
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:589]: This comment is confusing

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 17]
```diff
@@ -638,18 +720,12 @@ Error CoverageMapping::loadFunctionRecord(
...
   FunctionRecord Function(OrigFuncName, Record.Filenames);
   for (const auto &Region : Record.MappingRegions) {
-    // If an MCDCDecisionRegion is seen, track the BranchRegions that follow
-    // it according to Region.NumConditions.
     if (Region.Kind == CounterMappingRegion::MCDCDecisionRegion) {
-      assert(NumConds == 0);
-      MCDCDecision = &Region;
-      NumConds = Region.MCDCParams.NumConditions;
+      // Start recording `Region` as the `Decision`
+      Decisions.emplace_back(Region);
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:728]: why `emplace_back` instead of `push_back`?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 16 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:589]: It came from "should-name-everything-syndrome". I think it'd be enough to mention from the class comment.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 14 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:658]: I will dissolve it into the unified method to be introduced.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 17 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:728]: I thought it would be made smaller if the constructor has default constructors for `SmallVector`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 1 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: I've introduced `MCDCDecisionRecorder`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 4 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: Now it is `MCDCDecisionRecorder::DecisionRecord` (and made private)

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 9 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: I haven't written doxygen comments for long time. Please point out any mistakes.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 14 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: I've taken a simpler name, `recordExpansion()`

**Comment by evodius96** [comment]
Thanks for working on this; I apologize I haven't been able to keep up.  As far as I can tell the benefits to this approach over https://github.com/llvm/llvm-project/pull/78819 are:

1. Records are processed as they're seen with no scan-ahead and therefore no possibility that a record will be needlessly visited multiple times.
2. The IDs of the branch regions in the decision are also tracked to ensure they're unique. Thus you can better flag malformed records as opposed to a missing TestVector assertion failure.
3. The Decision/Expansion/Branch processing is better encapsulated.

Is that right?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 9 above)
Comment (MaskRay) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp]: Doxygen comments are not required. I think much new code doesn't use Doxygen...

**Comment by chapuni** [comment]
I have imported a testcase from #78819 (thanks!). I think this is ready as well.

File: llvm/test/tools/llvm-cov/mcdc-macro.test [hunk 18]
```diff
@@ -0,0 +1,92 @@
...
+// CHECK-NEXT:  |
+// CHECK-NEXT:  ------------------
+
+Instructions for regenerating the test:
+
+# cd %S/Inputs
+cp mcdc-macro.c /tmp
+
+clang -fcoverage-mcdc -fprofile-instr-generate -fcoverage-compilation-dir=. \
+    -fcoverage-mapping /tmp/mcdc-macro.c -o /tmp/mcdc-macro.o
```
Comment (MaskRay) [inline llvm/test/tools/llvm-cov/mcdc-macro.test:90]: The output is an executable.

The tests have zero execution counts. Running once will make a more interesting test.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 19]
```diff
@@ -582,6 +583,177 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
   return MaxBitmapID + (SizeInBits / CHAR_BIT);
 }
 
+namespace {
+
+/// Collect Decisions, Branchs, and Expansions and associate them.
+class MCDCDecisionRecorder {
+
```
Comment (MaskRay) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:590]: delete blank line

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 20]
```diff
@@ -638,20 +810,13 @@ Error CoverageMapping::loadFunctionRecord(
...
   for (const auto &Region : Record.MappingRegions) {
-    // If an MCDCDecisionRegion is seen, track the BranchRegions that follow
-    // it according to Region.NumConditions.
-    if (Region.Kind == CounterMappingRegion::MCDCDecisionRegion) {
-      assert(NumConds == 0);
-      MCDCDecision = &Region;
-      NumConds = Region.MCDCParams.NumConditions;
+    // MCDCDecisionRegion should be handled first since it overlaps with
+    // others inside.
+    if (MCDCDecisions.registerDecision(Region))
```
Comment (MaskRay) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:818]: I think it reads better if the `CounterMappingRegion::MCDCDecisionRegion` guard is moved here. The same applies to `MCDCDecisions.processRegion(Region);`

I.e. we check different types of `Region` here and dispatch actions to `MCDCDecisions`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 21]
```diff
@@ -582,6 +583,177 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
+  /// If Region is ExpansionRegion, record it.
+  /// If Region is MCDCBranchRegion, add it to DecisionRecord.
+  /// \param Region to be inspected
+  /// \returns DecisionsAndBranches if DecisionRecord completed.
+  ///     Or returns nullopt.
+  std::optional<DecisionAndBranches>
+  processRegion(const CounterMappingRegion &Region) {
+
+    // Record ExpansionRegion.
+    if (Region.Kind == CounterMappingRegion::ExpansionRegion) {
```
Comment (MaskRay) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:723]: I think it's clear to move `ExpansionRegion` handling to the caller.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 20 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:818]: I did because of symmetry to `processRegion`. I can rework this.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 21 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:723]: I wanted to make `MCDCDecisionRecorder` richer, since it simply encapsulated `SmallVector<DecisionRecord> Decisions`.

File: llvm/test/tools/llvm-cov/mcdc-macro.test [hunk 22]
```diff
@@ -13,18 +13,18 @@
...
 // CHECK-NEXT:  |  Number of Conditions: 5
 // CHECK-NEXT:  |     Condition C1 --> (9:7)
-// CHECK-NEXT:  |     Condition C2 --> (2:11)
-// CHECK-NEXT:  |     Condition C3 --> (3:11)
-// CHECK-NEXT:  |     Condition C4 --> (3:23)
-// CHECK-NEXT:  |     Condition C5 --> (9:22)
+// CHECK-NEXT:  |     Condition C2 --> (9:22)
+// CHECK-NEXT:  |     Condition C3 --> (2:11)
+// CHECK-NEXT:  |     Condition C4 --> (3:11)
+// CHECK-NEXT:  |     Condition C5 --> (3:23)
```
Comment (evodius96) [inline llvm/test/tools/llvm-cov/mcdc-macro.test:19]: `if (a && D && E || b)`

Why is the condition `b` above changed to be C2 rather than C5?  Intuitively it better matches the order of lines in the Branch Report coverage above as the 5th condition. I don't mind so much as long as it's consistent, but it seems less intuitive to me.

Comment (evodius96) [reply llvm/test/tools/llvm-cov/mcdc-macro.test:19]: > I could tweak the order to honor the location of `Expansion`. Your #78819 is better in this point. Is it better for me to rework?

That would be my preference. Honoring the location seems more intuitive to me when reading the output.

**Comment by MaskRay** [comment]
The description is too brief for the involved problem:) Feel free to incorporate my comment https://github.com/llvm/llvm-project/issues/77871#issuecomment-1913454161 into the description/commit message.

**Comment by whentojump** [comment]
Hey everyone. Thanks for this great work!

Will you please add this test:

```c
#define C c
#define D 1
#define E (C != a) && (C > a)
#define F E
#define G(x) (((x) & D) == D)

void __attribute__((noinline)) func1(void) { return; }

void __attribute__((noinline)) func(int a, int b, int c) {
  if (a && D && E || b)
    func1();
  if (b && D)
    func1();
  if (a && (b && C) || (D && F))
    func1();
  if (G(a) && G(b))
    func1();
}

int main() {
  func(2, 3, 3);
  return 0;
}
```

Currently it doesn't seem to work on my side. I'm also glad to investigate that.

**Comment by MaskRay** [comment]
I think this is correct, but the consumer side complexity makes me wonder whether the additional complexity makes our "boring algorithm" overall worse than GCC https://gcc.gnu.org/pipermail/gcc-patches/2024-January/644269.html

(From https://maskray.me/blog/2024-01-28-mc-dc-and-compiler-implementations)

Pros:

* Easier to understand
* Each condition instrumentation adds just one single bitwise OR instruction, instead of possibly three (one bitwise AND plus two bitwise OR).

Cons:

* More bits to encode N conditions (`2**N` vs. `2*N`)
* More metadata to encode the reduced ordered BDDs, required by the reader to compute independence pairs
* Determining independent pairs involves a brute-force algorithm in llvm-cov, which has a high time complexity but probably acceptable due to the limited condition count.

**Comment by chapuni** [comment]
@whentojump Could you try #78966, too?

@MaskRay
> I think this is correct,
What about "this"?

**Comment by evodius96** [comment]
> I think this is correct, but the consumer side complexity makes me wonder whether the additional complexity makes our "boring algorithm" overall worse than GCC 

From the perspective of embedded, I think it makes more sense to keep the instrumentation light and off-load processing in llvm-cov. Also, I think we can look at better modularization of metadata sections (I.e. keeping them in the executable but out of what is loaded in memory, which is what we do downstream and was discussed at the last Developers' meeting embedded workshop). Even going beyond six conditions isn't that bad, but I don't think 32 conditions (as mentioned in GCC context) is at all typical, especially in embedded context. I know we want this to work outside of embedded as well, but we also have to keep in mind when MC/DC is not only useful but practical to fulfill.

Conceivably (just thinking out loud) we may also be able to enable different modes that balance the tradeoffs differently between the different algorithms.

**Comment by whentojump** [comment]
> @whentojump Could you try #78966, too?

These two PRs combined worked smoothly for my case. Thanks a lot!

**Review by MaskRay — APPROVED** [review]

**Comment by chapuni** [comment]
Thanks @MaskRay . I know I have to do;
1. Rewrite the description (and possibly the subject)
2. Regenerate and test the testcase.o

By the way, do you have any comments in #78966?

**Comment by evodius96** [comment]
@chapuni Can you backport this onto 18.x branch along with #78966?
