### PR TITLE
[Clang] Treat constexpr-unknown value as invalid in `EvaluateAsInitializer`

### LINKED ISSUE #127475: [Clang] [CodeGen] Wrong code generation for `extern reference`
Minimal Reproducible Example:

```cpp
/// src.cpp
#include <vector>

struct S {
    std::vector<int> c;
};

static S ls = {{1, 2, 3}};

S& s = ls;

/// main.cpp
#include <cstdio>
#include <vector>

struct S {
    std::vector<int> c;
};

extern S& s;

int main() {
    for (size_t i = 0; i < s.c.size(); i++) {
        printf("aaa\n");
    }

    for (auto& i : s.c) {
        printf("bbb\n");
    }
    return 0;
}
```

https://godbolt.org/z/W1YoYsMYh

### PR DESCRIPTION
**Pull request by dtcxzyw**
It is an alternative to https://github.com/llvm/llvm-project/pull/127525.
Close https://github.com/llvm/llvm-project/issues/127475.

### CODE REVIEW

File: clang/test/SemaCXX/constant-expression-cxx11.cpp [hunk 1]
```diff
@@ -122,9 +122,9 @@ namespace CaseStatements {
 }
 
 extern int &Recurse1;
-int &Recurse2 = Recurse1; // expected-note {{declared here}}
+int &Recurse2 = Recurse1; // pre-cxx23-note {{declared here}}
```
Comment (dtcxzyw) [inline clang/test/SemaCXX/constant-expression-cxx11.cpp:125]: This is a regression.

Comment (efriedma-quic) [reply clang/test/SemaCXX/constant-expression-cxx11.cpp:125]: I'd guess you just need to generate a note when you set `Result = false`, like `the value 'Recurse2' is constexpr-unknown`.

File: clang/lib/AST/ExprConstant.cpp [hunk 2]
```diff
@@ -3628,8 +3628,6 @@ static bool evaluateVarDeclInit(EvalInfo &Info, const Expr *E,
   if (AllowConstexprUnknown) {
     if (!Result)
       Result = &Info.CurrentCall->createConstexprUnknownAPValues(VD, Base);
-    else
-      Result->setConstexprUnknown();
```
Comment (efriedma-quic) [inline clang/lib/AST/ExprConstant.cpp:3632]: Deleting this makes a lot of sense; I was really confused trying to parse what this line in the original patch was supposed to do.

File: clang/lib/AST/Decl.cpp [hunk 3]
```diff
@@ -2587,6 +2587,9 @@ APValue *VarDecl::evaluateValueImpl(SmallVectorImpl<PartialDiagnosticAt> &Notes,
       !Notes.empty())
     Result = false;
 
+  if (Eval->Evaluated.allowConstexprUnknown())
+    Result = false;
```
Comment (efriedma-quic) [inline clang/lib/AST/Decl.cpp:2591]: I think this check should be inside `EvaluateAsInitializer()`... and all the other `Evaluate` entry points also include this check.

File: clang/lib/AST/ExprConstant.cpp [hunk 4]
```diff
@@ -17000,6 +16998,18 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
...
     if (!Info.discardCleanups())
       llvm_unreachable("Unhandled cleanup; missing full expression marker?");
+
+    if (Value.allowConstexprUnknown()) {
+      assert(Value.isLValue() && "Expected an lvalue");
+      auto Base = Value.getLValueBase();
+      const auto *NewVD = Base.dyn_cast<const ValueDecl *>();
+      if (!NewVD)
+        NewVD = VD;
+      Info.FFDiag(getExprLoc(), diag::note_constexpr_var_init_non_constant, 1)
```
Comment (dtcxzyw) [inline clang/lib/AST/ExprConstant.cpp:17008]: Ideally, we should emit a note here:
https://github.com/llvm/llvm-project/blob/a955426a16bcbb9bf05eb0e3894663dff4983b00/clang/lib/AST/ExprConstant.cpp#L3581-L3584

But I don't know how to add a "lazy" note (i.e., these notes will be shown if an error occurs).

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 5]
```diff
@@ -1883,8 +1883,12 @@ llvm::Constant *ConstantEmitter::tryEmitPrivateForVarInit(const VarDecl &D) {
 
   // Try to emit the initializer.  Note that this can allow some things that
   // are not allowed by tryEmitPrivateForMemory alone.
-  if (APValue *value = D.evaluateValue())
+  // Bail out on constexpr-unknown values since they are invalid in CodeGen.
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprConstant.cpp:1886]: Delete the comment.

File: clang/lib/AST/ExprConstant.cpp (hunk 4 above)
Comment (efriedma-quic) [reply clang/lib/AST/ExprConstant.cpp:17008]: I'm not sure what you mean by a "lazy" note; the whole point of constexpr-unknown is that it's not an error at the point it's constructed.

If you need more information to generate a good diagnostic, you could pass that information to createConstexprUnknownAPValues, and store it in the APValue itself, I guess.  Computing the whole diagnostic in advance seems like it would be too expensive, though.

I don't think it's a big deal if we generate slightly different diagnostics depending on whether we're in C++23 mode, as long as we generate some explanation for what's happening.

**Review by efriedma-quic — COMMENTED** [review]
Should the other Expr::Evaluate* entry points have the same bailout?  Do you want to do that in this patch, or a followup?

File: clang/lib/AST/ExprConstant.cpp (hunk 4 above)
Comment (dtcxzyw) [reply clang/lib/AST/ExprConstant.cpp:17008]: > If you need more information to generate a good diagnostic, you could pass that information to createConstexprUnknownAPValues, and store it in the APValue itself, I guess. Computing the whole diagnostic in advance seems like it would be too expensive, though.

That is what the current implementation does.

**Comment by dtcxzyw** [comment]
> Should the other Expr::Evaluate* entry points have the same bailout? Do you want to do that in this patch, or a followup?

Sorry I don't have enough bandwidth to work on other potential constexpr-unknown-related issues. I just want to close https://github.com/llvm/llvm-project/issues/127475 as soon as possible.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Review by shafik — COMMENTED** [review]
I get that we are allowing constexpr unknown values into codegen and that is a mistake but I don't totally follow the fix. Can you go into more details?

If I am reading the code correctly there should be some constexpr cases that generate a diagnostic, can we verify that with a test?

**Comment by efriedma-quic** [comment]
Here's a testcase that's should generate a diagnostic, but doesn't without this patch:

```
int &ff(); int &x = ff(); constinit int &z = x;
```

Some related testcases are a little weird... consider the following:

```
extern int &x; int &z = x;
```

There's a gap between checking for constant expressions, and codegen, due to the following diagnostic; it triggers in constexpr, but allows evaluating for the value because a CCEDiag doesn't stop the evaluation: https://github.com/llvm/llvm-project/blob/52c81598da38532c119db9c06fcc3d7f9c332a8e/clang/lib/AST/ExprConstant.cpp#L3607 .

**Comment by dtcxzyw** [comment]
> If I am reading the code correctly there should be some constexpr cases that generate a diagnostic, can we verify that with a test?

It has been tested by the following case:
```
extern int &Recurse1;
int &Recurse2 = Recurse1;
int &Recurse1 = Recurse2;
constexpr int &Recurse3 = Recurse2;
```
Without diagnostic-related code in this patch, we will lose some notes on `Recurse2`.

**Comment by Mishura4** [comment]
So it looks like 20.1.0 is planned to release tomorrow as there are "no critical issues"... https://discourse.llvm.org/t/20-1-0-release-update-releasing-1-week-early-tomorrow/84932
I'm not an LLVM maintainer so I don't know if it's really my place to say this, but I think you're about to see a lot more GitHub issues filed related to this 😭

**Review by cor3ntin — APPROVED** [review]

**Review by shafik — APPROVED** [review]
I am happy to see a fix here but I would still like some more context on whether we think this still leave some cases uncaught or not.

**Comment by efriedma-quic** [comment]
Opened #129844 with a case that still fails.  Other entry-points to constant evaluation need similar treatment to EvaluateAsInitializer.

**Comment by efriedma-quic** [comment]
And the check for allowConstexprUnknown() isn't catching all the relevant cases; opened #129845.
