### PR TITLE
[clang-tidy] Improve `google-explicit-constructor` checks handling of `explicit(bool)`

### LINKED ISSUE #81121: [clang-tidy] google-explicit-constructor check with already specified `explicit(false)`
Explicit constructor check fix is wrong when already specified `explicit(false)` on that constructor

```cpp
struct A {};

struct B {
  explicit(false) B(A) {}
};
```

The [checker](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp) tries to fix it with adding a new `explicit` keyword which makes compilation error.

```cpp
struct A {};

struct B {
  explicit(false) explicit B(A) {}
};
```

No warning/error should exist when specifying the `explicit(false)` attribute.

### PR DESCRIPTION
**Pull request by AMS21**
We now treat `explicit(false)` the same way we treat `noexcept(false)` in the noexcept checks, which is ignoring it.

Also introduced a new warning message if a constructor has an `explicit` declaration which evaluates to false and no longer emit a faulty FixIt.

Fixes #81121

### CODE REVIEW

File: clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp [hunk 1]
```diff
@@ -130,18 +134,30 @@ void ExplicitConstructorCheck::check(const MatchFinder::MatchResult &Result) {
...
 
+  // Don't complain about explicit(false)
+  const Expr *ExplicitExpr = ExplicitSpec.getExpr();
+  if (ExplicitExpr) {
+    ExplicitExpr = ExplicitExpr->IgnoreImplicit();
+    if (isa<CXXBoolLiteralExpr>(ExplicitExpr))
+      return;
+  }
+
   bool SingleArgument =
```
Comment (EugeneZelenko) [inline clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp:149]: Should be `const`.

**Comment by AMS21** [comment]
Rebased and addressed review comments

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -147,6 +147,10 @@ Changes in existing checks
   <clang-tidy/checks/google/build-namespaces>` check by replacing the local
   option `HeaderFileExtensions` by the global option of the same name.
 
+- Improved :doc:`google-explicit-constructor
+  <clang-tidy/checks/google/explicit-constructor>` check to better handle
+  C++-20 `explicit(bool)`.
```
Comment (EugeneZelenko) [inline clang-tools-extra/docs/ReleaseNotes.rst:152]: `C++20`. Please use double back-ticks for language constructs.

File: clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp [hunk 3]
```diff
@@ -79,8 +79,10 @@ static bool isStdInitializerList(QualType Type) {
 }
 
 void ExplicitConstructorCheck::check(const MatchFinder::MatchResult &Result) {
-  constexpr char WarningMessage[] =
+  constexpr char NoExpressionWarningMessage[] =
       "%0 must be marked explicit to avoid unintentional implicit conversions";
+  constexpr char WithExpressionWarningMessage[] =
+      "%0 explicit expression evaluated to false";
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp:85]: Maybe ? ```evaluates to `false` ```

**Review by PiotrZSL — APPROVED** [review]
LGTM

File: clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp (hunk 3 above)
Comment (AMS21) [reply clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp]: I agree sound better :)

**Review by 5chmidti — APPROVED** [review]

**Review by HerrCai0907 — APPROVED** [review]
