### PR TITLE
[AVX-512] Fix for disjoint-or-fold (VGF2P8AFFINEQB)

### LINKED ISSUE #190502: [AVX-512] Look for disjoint-or fold into VGF2P8AFFINEQB
Zig: [(Godbolt)](https://zig.godbo.lt/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:16,fontUsePx:'0',j:1,lang:zig,selection:(endColumn:2,endLineNumber:3,positionColumn:2,positionLineNumber:3,selectionStartColumn:2,selectionStartLineNumber:3,startColumn:2,startLineNumber:3),source:'export+fn+foo(x:+@Vector(64,+u8))+@Vector(64,+u8)+%7B%0A++++return+(x+%3E%3E+@splat(6))+%7C+@as(@Vector(64,+u8),+@splat(8))%3B%0A%7D'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:50.32888372992842,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:16,fontUsePx:'0',j:1,lang:zig,libs:!(),options:'-target+x86_64-linux+-mcpu%3Dznver5+-O+ReleaseFast+-fomit-frame-pointer',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+zig+trunk+(Editor+%231)',t:'0')),k:49.671116270071586,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
```zig
export fn foo(x: @Vector(64, u8)) @Vector(64, u8) {
    return (x >> @splat(6)) | @as(@Vector(64, u8), @splat(8));
}
```

LLVM: [(Godbolt)](https://llvm.godbo.lt/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:llvm,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'@foo+%3D+alias+%3C64+x+i8%3E+(%3C64+x+i8%3E),+ptr+@example.foo%0A%0Adefine+internal+range(i8+8,+12)+%3C64+x+i8%3E+@example.foo(%3C64+x+i8%3E+%250)+unnamed_addr+align+1+%7B%0AEntry:%0A++%251+%3D+lshr+%3C64+x+i8%3E+%250,+splat+(i8+6)%0A++%252+%3D+or+disjoint+%3C64+x+i8%3E+%251,+splat+(i8+8)%0A++ret+%3C64+x+i8%3E+%252%0A%7D%0A'),l:'5',n:'0',o:'LLVM+IR+source+%231',t:'0')),k:48.73583260680035,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:llctrunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:llvm,libs:!(),options:'-O3+-mcpu%3Dznver5',overrides:!(),selection:(endColumn:18,endLineNumber:16,positionColumn:18,positionLineNumber:16,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+llc+(trunk)+(Editor+%231)',t:'0')),k:51.264167393199656,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
```llvm
define internal range(i8 8, 12) <64 x i8> @foo(<64 x i8> %0) unnamed_addr align 1 {
Entry:
  %1 = lshr <64 x i8> %0, splat (i8 6)
  %2 = or disjoint <64 x i8> %1, splat (i8 8)
  ret <64 x i8> %2
}
```
Currently:
```asm
.LCPI0_2:
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   128
        .byte   64
.LCPI0_3:
        .zero   4,8
foo:
        vgf2p8affineqb  zmm0, zmm0, qword ptr [rip + .LCPI0_2]{1to8}, 0
        vpord   zmm0, zmm0, dword ptr [rip + .LCPI0_3]{1to16}
        ret
```

Could be:
```asm
.LCPI0_2:
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   0
        .byte   128
        .byte   64
foo:
        vgf2p8affineqb  zmm0, zmm0, qword ptr [rip + .LCPI0_2]{1to8}, 8
        ret
```

### PR DESCRIPTION
**Pull request by Ko496-glitch**
Fixes #190502

1. Added implementation of helper 

```
 `static SDValue combineOrWithGF2P8AFFINEQB(SDNode *N, const SDLoc &DL,
                                           SelectionDAG &DAG, EVT VT)`
```

2. Wired the logic with combineOrXorWithSETCC

### CODE REVIEW

**Comment by Ko496-glitch** [comment]
@RKSimon looks like we are folding to vgf2p8affineqb. Please let me know if i should add more test cases or start working on #190520

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -53171,6 +53171,31 @@ static SDValue combineAddOrSubToADCOrSBB(SDNode *N, const SDLoc &DL,
...
+
+  SDValue X, Y, SplatOp;
+  APInt Imm, SplatVal;
+  if (sd_match(N,
+               m_c_BinOp(ISD::OR,
+                         m_OneUse(m_TernaryOp(X86ISD::GF2P8AFFINEQB, m_Value(X),
+                                              m_Value(Y), m_ConstInt(Imm))),
+                         m_Value(SplatOp))) &&
+      X86::isConstantSplat(SplatOp, SplatVal, /*AllowPartialUndefs=*/false)) {
+    uint64_t NewImm = (Imm.getZExtValue() ^ SplatVal.getZExtValue()) & 0xFF;
```
[the remark this answers is not in the document]
Comment (WalterKruger) [reply llvm/lib/Target/X86/X86ISelLowering.cpp]: It seems like the `haveNoCommonBitsSet` check might fails in that case anyway. It is still possible to still fold that case by checking if otherwise known zeros where set by the immediate.

File: llvm/test/CodeGen/X86/gfni-or-fold.ll [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+; AVX512-LABEL: test_or_non_disjoint:
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vgf2p8affineqb $4, %zmm1, %zmm0, %zmm0
+; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
+; AVX512-NEXT:    retq
+  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 4)
+  ; Without the 'disjoint' keyword, the compiler cannot safely fold this into the immediate
+  %or = or <64 x i8> %gfni, splat(i8 4)
+  ret <64 x i8> %or
+}
```
Comment (Ko496-glitch) [inline llvm/test/CodeGen/X86/gfni-or-fold.ll]: @WalterKruger  now we are emitting vpord so this test makes sense for negative cases?

**Comment by Ko496-glitch** [comment]
@RKSimon  i might have limited access to my pc next week, so just wanted to ask if there is anything left on  this fix ? otherwise i can start my work on #190520  :)

I would need some suggestions on how to build #190520 over this

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 3]
```diff
@@ -53171,6 +53171,31 @@ static SDValue combineAddOrSubToADCOrSBB(SDNode *N, const SDLoc &DL,
   return SDValue();
 }
 
+static SDValue combineOrWithGF2P8AFFINEQB(SDNode *N, const SDLoc &DL,
+                                          SelectionDAG &DAG, EVT VT) {
+  using namespace SDPatternMatch;
+  assert(N->getOpcode() == ISD::OR);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp]: (style) missing assert message

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 4]
```diff
@@ -53171,6 +53171,31 @@ static SDValue combineAddOrSubToADCOrSBB(SDNode *N, const SDLoc &DL,
...
+
+  if (!N->getFlags().hasDisjoint() &&
+      !DAG.haveNoCommonBitsSet(N->getOperand(0), N->getOperand(1)))
+    return SDValue();
+
+  SDValue X, Y, SplatOp;
+  APInt Imm, SplatVal;
+  if (sd_match(N,
+               m_c_BinOp(ISD::OR,
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp]: m_c_BinOp() -> m_Or()

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 5]
```diff
@@ -53171,6 +53171,31 @@ static SDValue combineAddOrSubToADCOrSBB(SDNode *N, const SDLoc &DL,
...
+static SDValue combineOrWithGF2P8AFFINEQB(SDNode *N, const SDLoc &DL,
+                                          SelectionDAG &DAG, EVT VT) {
+  using namespace SDPatternMatch;
+  assert(N->getOpcode() == ISD::OR);
+
+  if (!N->getFlags().hasDisjoint() &&
+      !DAG.haveNoCommonBitsSet(N->getOperand(0), N->getOperand(1)))
+    return SDValue();
+
+  SDValue X, Y, SplatOp;
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:53188]: Add a brief comment describing the fold

**Review by RKSimon — CHANGES_REQUESTED** [review]
@WalterKruger are you OK with the test coverage?

File: llvm/test/CodeGen/X86/gfni-or-fold.ll [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+define <64 x i8> @test_or_non_disjoint(<64 x i8> %src, <64 x i8> %matrix) {
+; AVX512-LABEL: test_or_non_disjoint:
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vgf2p8affineqb $4, %zmm1, %zmm0, %zmm0
+; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
+; AVX512-NEXT:    retq
+  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 4)
+  ; Without the 'disjoint' keyword, the compiler cannot safely fold this into the immediate
```
Comment (WalterKruger) [inline llvm/test/CodeGen/X86/gfni-or-fold.ll:55]: If future KnownBits analysis is complex enough, it should be able to detect cases where a otherwise known one is inverted by the immediate making the OR disjoint (well the immediate itself isn't disjoint). I would prefer a test case like this where the splat overlaps with immediate but still has the keyword.

**Review by WalterKruger — COMMENTED** [review]
LGTM - I am happy with the current test coverage.

**Review by RKSimon — APPROVED** [review]
LGTM
