### PR TITLE
[Clang] Fix missing diagnostic for non-standard layout type in `offsetof`

### LINKED ISSUE #64619: Missing diagnostic for non-standard layout types in `offsetof`
Consider the following example (https://godbolt.org/z/o77v1nad9):
```cpp
struct X1 { int a; };
struct X2 { int b; };
struct Y : X1, X2 {};

static_assert(__builtin_offsetof(Y, b) == 4);
static_assert(offsetof(Y, b) == 4);

static_assert(!std::is_standard_layout_v<Y>, "");
```
Only GCC warns that non-standard layout type is passed to `offsetof`, which is [conditionally-supported](http://eel.is/c++draft/support.types.layout#1.sentence-2).
```
<source>:8:34: warning: 'offsetof' within non-standard-layout type 'Y' is conditionally-supported [-Winvalid-offsetof]
    8 | static_assert(__builtin_offsetof(Y, b) == 4);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~
In file included from /opt/compiler-explorer/gcc-trunk-20230811/include/c++/14.0.0/cstddef:50,
                 from <source>:1:
<source>:9:24: warning: 'offsetof' within non-standard-layout type 'Y' is conditionally-supported [-Winvalid-offsetof]
    9 | static_assert(offsetof(Y, b) == 4);
      |                        ^
```
GCC issues it by default, whereas Clang, MSVC, and EDG doesn't even in pedantic modes (or `/W4`).

I'm not sure what the solution should be, but I feel like there is a problem to solve.

### PR DESCRIPTION
**Pull request by kasuga-fj**
Fixes #64619

Clang warns diagnostic for non-standard layout types in `offsetof` only if they are in evaluated context. With this patch, you'll also get diagnostic if you use `offsetof` on non-standard layout types in any other contexts

### CODE REVIEW

**Comment by cor3ntin** [comment]
Thanks for working on this. 

This generally looks good to me.
Can you add an entry in clang/docs/ReleaseNotes.rst? 
Thanks!

**Comment by cor3ntin** [comment]
Thanks. LGTM.
I'd like to do things properly so I'll wait for CI to be fixed before approving, hopefully we can figure that out today!
(Nothing to do on your end)

**Comment by kasuga-fj** [comment]
Thank you for your quick review!

File: clang/test/SemaCXX/ms_struct.cpp [hunk 1]
```diff
@@ -39,6 +40,4 @@ struct C {
 
 static_assert(__builtin_offsetof(C, n) == 8,
               "long long field in ms_struct should be 8-byte aligned");
-#if !defined(TEST_FOR_ERROR) && !defined(TEST_FOR_WARNING)
-// expected-no-diagnostics
-#endif
+// expected-warning@-2 {{offset of on non-standard-layout type 'C'}}
```
Comment (tru) [inline clang/test/SemaCXX/ms_struct.cpp:43]: Missing EOL. Did you run `clang-format`?

Comment (kasuga-fj) [reply clang/test/SemaCXX/ms_struct.cpp:43]: Yes. I ran `git clang-format HEAD~2`, but no files were modified. Should we apply clang-format to the tests as well? (I think removing EOL is not good. I'll fix it)

Comment (cor3ntin) [reply clang/test/SemaCXX/ms_struct.cpp:43]: We do not run clang-format on tests - in part because tests are sensible to line number changes.

Comment (tru) [reply clang/test/SemaCXX/ms_struct.cpp:43]: Ah I missed that it was in a test. We shouldn't run clang-format then. But the EOL should be fixed! Sorry for the drive-by review :)

Comment (cor3ntin) [reply clang/test/SemaCXX/ms_struct.cpp]: Nah, thanks a lot for spotting that, I didn't

**Comment by tbaederr** [comment]
Okay, makes sense to me. Should probably also be backported to 17.

**Comment by cor3ntin** [comment]
@tbaederr We are getting rather conservative as to what gets backported. I think that does not meet the bar.
Maybe for 17.0.x

**Comment by metaflow** [comment]
@kasuga-fj could you please re-upload change to trigger the build?

**Comment by tbaederr** [comment]
@cor3ntin Yes, I wrote this in the wrong PR :facepalm:

**Comment by kasuga-fj** [comment]
@metaflow I added an empty commit and the build was triggered, but it still failed. Could you help me?

**Comment by kasuga-fj** [comment]
Ah, thanks. Then what should I do? Can I make another commit with the same content as the last commit and force push? (sorry, I don't fully understand the LLVM's PR rules)

**Comment by hazohelet** [comment]
Adding an irrelevant new line in a modified test file would suffice to trigger the CI build.
Force-pushing doesn't seem to be desirable during code review.

**Comment by metaflow** [comment]
alright, build has been triggered successfully! thank you <3

**Comment by kasuga-fj** [comment]
The CI failed because `libcxx` uses `offsetof`.
https://github.com/kasuga-fj/llvm-project/blob/b9c767a6a128f57858273eb43d4383e83d0d086b/libcxx/include/__type_traits/datasizeof.h#L50
I investigated but couldn't figure out where to fix it (Should I change the compile time options?). Could someone please help me? It may be unrelated, but I am also concerned that "libc++ test suite in C++03" failed while "libc++ test suite in C++26" succeeded.

**Comment by tru** [comment]
Ping @llvm/pr-subscribers-libcxx

File: clang/test/SemaCXX/offsetof.cpp [hunk 2]
```diff
@@ -17,7 +17,7 @@ struct Base { int x; };
 struct Derived : Base { int y; };
 int o = __builtin_offsetof(Derived, x); // expected-warning{{offset of on non-POD type}}
 
-const int o2 = sizeof(__builtin_offsetof(Derived, x));
+const int o2 = sizeof(__builtin_offsetof(Derived, x)); // expected-warning{{offset of on non-POD type 'Derived'}}
```
Comment (AaronBallman) [inline clang/test/SemaCXX/offsetof.cpp:20]: This is an example of why I think the existing behavior is correct. The fact that we're asking for the offset of a field on a non-POD type is not harmful because the call is never evaluated.

File: clang/test/SemaCXX/ms_struct.cpp [hunk 3]
```diff
@@ -25,6 +25,7 @@ struct B : public A {
 
 static_assert(__builtin_offsetof(B, d) == 12,
   "We can't allocate the bitfield into the padding under ms_struct");
+// expected-warning@-2 {{offset of on non-standard-layout type 'B'}}
```
Comment (AaronBallman) [inline clang/test/SemaCXX/ms_struct.cpp:28]: I think this diagnostic is an improvement over the status quo.

File: clang/test/SemaCXX/offsetof.cpp [hunk 4]
```diff
@@ -50,9 +50,9 @@ struct Derived2 : public Base1, public Base2 {
   int z; 
 };
 
-int derived1[__builtin_offsetof(Derived2, x) == 0? 1 : -1];
-int derived2[__builtin_offsetof(Derived2, y)  == 4? 1 : -1];
-int derived3[__builtin_offsetof(Derived2, z)  == 8? 1 : -1];
+int derived1[__builtin_offsetof(Derived2, x) == 0? 1 : -1]; // expected-warning{{offset of on non-POD type 'Derived2'}}
```
Comment (AaronBallman) [inline clang/test/SemaCXX/offsetof.cpp:53]: This also seems like an improvement in diagnostic behavior.

**Review by AaronBallman — APPROVED** [review]
Hmmm, in some ways I think this is making the diagnostic needlessly chatty, and in other ways the new diagnostic behavior seems reasonable.

On balance, I think the improvements outweigh the regressions, especially for code users are likely to hit. e.g., I suspect there's way more use of offsetof in a static assertion than there are uses of offsetof as an operand to sizeof.

File: clang/test/SemaCXX/offsetof.cpp (hunk 2 above)
Comment (cor3ntin) [reply clang/test/SemaCXX/offsetof.cpp:20]: So you think we should ie, check for `!isUnevaluated()` - ie diag in constant expressions but not in unevaluated contexts?

Comment (AaronBallman) [reply clang/test/SemaCXX/offsetof.cpp:20]: I think that might produce slightly better results by silencing this kind of warning.

Comment (kasuga-fj) [reply clang/test/SemaCXX/offsetof.cpp]: Fixed. Thanks.

**Review by cor3ntin — APPROVED** [review]

**Comment by kasuga-fj** [comment]
@llvm/pr-subscribers-libcxx  Could you please check this comment? https://github.com/llvm/llvm-project/pull/65246#issuecomment-1706219059

**Comment by cor3ntin** [comment]
@philnik777 may be able to help

**Comment by ldionne** [comment]
I think when the @llvm/pr-subscribers-libcxx group was pinged 2 weeks ago, most of us didn't have the right GH notifications set up yet and we didn't see it. Looking now.

**Comment by ldionne** [comment]
Note that you should probably rebase your patch onto `main` and force-push to update the PR. The CI for Clang now runs on Windows from GH PRs as well (it used not to when you submitted the patch, I think).

**Comment by ldionne** [comment]
Ok so after scratching my head a bit, I'm actually not certain of how to proceed with this. I can't find a way to implement `__libcpp_datasizeof` in libc++ that doesn't involve `offsetof`, so our only option would be to silence the warning. We could do it like (if we end up doing that, just take that diff and incorporate it to your patch, we can land both at once and the libc++ CI will also trigger):

```
diff --git a/libcxx/include/__type_traits/datasizeof.h b/libcxx/include/__type_traits/datasizeof.h
index 019099a9cf18..88a702470c3c 100644
--- a/libcxx/include/__type_traits/datasizeof.h
+++ b/libcxx/include/__type_traits/datasizeof.h
@@ -47,7 +47,11 @@ struct __libcpp_datasizeof {
   };
 #endif
 
+  _LIBCPP_DIAGNOSTIC_PUSH
+  _LIBCPP_CLANG_DIAGNOSTIC_IGNORED("-Winvalid-offsetof")
+  _LIBCPP_GCC_DIAGNOSTIC_IGNORED("-Winvalid-offsetof")
   static const size_t value = offsetof(_FirstPaddingByte<>, __first_padding_byte_);
+  _LIBCPP_DIAGNOSTIC_POP
 };
 
 _LIBCPP_END_NAMESPACE_STD
```

However, in C++03, using `offsetof` with a non-POD is undefined behavior (hence the warning, I guess). So we'd technically have UB in our code here, which isn't great. In C++17 doing that is conditionally supported, so I guess we're fine.

So... should we strive to eradicate this from libc++ in the first place, or should we just silence the warning. WDYT?

Also, given that it is conditionally supported in C++17, I assume this warning doesn't trigger at all in C++17 mode, right?

**Comment by kasuga-fj** [comment]
Thank you for your review! Here are some comments and my thoughts.

> Note that you should probably rebase your patch onto main and force-push to update the PR

Does it mean that I can rebase and force-push since (it should be avoided in normal case but) this is a special case?

> So... should we strive to eradicate this from libc++ in the first place, or should we just silence the warning. WDYT?

I think it's good to only silence the warning and (if necessary) leave some TODO comments about the `offsetof` usage because it's undesirable for this patch to be larger than it needs to be..

> Also, given that it is conditionally supported in C++17, I assume this warning doesn't trigger at all in C++17 mode, right?

I believe the purpose of this warning is to tell you that your program works now, but may not be compiled with another compiler. So the similar warning should appear even in C++17 mode. I chedked and found that `_FirstPaddingByte<>` is standard layout but non-POD (I checked them with `std::is_standard_layout` and `std::is_pod`). Using `offsetof` with a standard-layout class is supported in C++17, so I guess there is no warning

**Comment by ldionne** [comment]
> Thank you for your review! Here are some comments and my thoughts.
> 
> > Note that you should probably rebase your patch onto main and force-push to update the PR
> 
> Does it mean that I can rebase and force-push since (it should be avoided in normal case but) this is a special case?

That's what I usually do. Do we have any Github workflow documentation that mentions we shouldn't force-push to update PRs? If so, I am not aware of it.

> 
> > So... should we strive to eradicate this from libc++ in the first place, or should we just silence the warning. WDYT?
> 
> I think it's good to only silence the warning and (if necessary) leave some TODO comments about the `offsetof` usage because it's undesirable for this patch to be larger than it needs to be..

My question is about the desired end state of libc++, not whether that end state should be achieved in this specific patch or not.

> 
> > Also, given that it is conditionally supported in C++17, I assume this warning doesn't trigger at all in C++17 mode, right?
> 
> I believe the purpose of this warning is to tell you that your program works now, but may not be compiled with another compiler. So the similar warning should appear even in C++17 mode. I chedked and found that `_FirstPaddingByte<>` is ~standard layout but non-POD~ both standard-layout and POD (I checked them with `std::is_standard_layout` and `std::is_pod`). Using `offsetof` with a standard-layout class is supported in C++17, so I guess there is no warning

What `T` type did you use to check that `_FirstPaddingByte<>` was standard layout and POD? Certainly `_FirstPaddingByte<>` can't be standard layout if the `T` it holds is not standard layout?

@philnik777 do you have thoughts on this?

**Comment by kasuga-fj** [comment]
> Do we have any Github workflow documentation that mentions we shouldn't force-push to update PRs?

According to the [LLVM GitHub User Guide](https://llvm.org/docs/GitHub.html#rebasing-pull-requests-and-force-pushes), we should generally avoid rebasing and pushing force. But I trust it will be allowed in this case.

> My question is about the desired end state of libc++, not whether that end state should be achieved in this specific patch or not.

I misunderstood, sorry. I'm not an expert of libcxx, so I cannot determine what is should be (although it is only what an amateur thinks, at least it seems to be working fine now, so just suppressing warning would not be a big problem, I think). 
Incidentally, as you may have already noticed, it may be worth noting that a relatively recent commit introduced `__libcpp_datasizeof` (https://github.com/llvm/llvm-project/commit/c4e98722ca79c827dd57b809e0ef16b3b8da8c72).

> Certainly _FirstPaddingByte<> can't be standard layout if the T it holds is not standard layout?

Yes, you are correct. I was only checking with standard-layout class... I tried passing a non-standard layout class in the type parameter and `_FirstPaddingByte<>` became non standard-layout. By the way, I checked the CI's failure log and it looks that perhaps there is no test which uses `__libcpp_datasizeof` with non standard-layout type (I may have missed something). I think it would be better adding such one.

**Comment by philnik777** [comment]
Assuming that Clang doesn't plan on optimizing anything based on this, I think it should be fine to just silence the warning. We could also add a `__datasizeof` builtin in a separate patch if we want. That would probably be less error-prone and cheaper than our current solution. FWIW we'll need some version of this when we want to replace `__compressed_pair`, so a cheaper solution would probably be a good idea.

**Comment by ldionne** [comment]
@kasuga-fj Ok, let's take the diff I posted earlier in the comments and silence the warning in libc++ then. Once you do that, the libc++ test suite shouldn't fail with your patch anymore so your CI should be green. Then libc++ will be out of your way and it's up to the Clang folks whether this is worth doing.

File: libcxx/include/__type_traits/datasizeof.h [hunk 5]
```diff
@@ -47,7 +47,11 @@ struct __libcpp_datasizeof {
   };
 #endif
```
[the remark this answers is not in the document]
Comment (kasuga-fj) [reply libcxx/include/__type_traits/datasizeof.h:49]: Done. Thanks

**Comment by kasuga-fj** [comment]
Previous CI failures due to `offsetof` warnings have been resolved. Thank you for your cooperation! The current CI error (libcxx-ci Benchmark) does not seem to be caused by this patch (other PRs seem to be failing in the same one), so I'll wait until it's fixed.

File: libcxx/include/__type_traits/datasizeof.h [hunk 6]
```diff
@@ -47,7 +47,13 @@ struct __libcpp_datasizeof {
...
 
+  // Disable warnings related to the use of `offsetof` on non-standard layout or non-POD types
+  // TODO : Find a way to replace `offsetof` ?
+  _LIBCPP_DIAGNOSTIC_PUSH
+  _LIBCPP_CLANG_DIAGNOSTIC_IGNORED("-Winvalid-offsetof")
+  _LIBCPP_GCC_DIAGNOSTIC_IGNORED("-Winvalid-offsetof")
```
Comment (philnik777) [inline libcxx/include/__type_traits/datasizeof.h:54]: GCC doesn't warn on this, so we shouldn't suppress anything here.

File: libcxx/include/__type_traits/datasizeof.h [hunk 7]
```diff
@@ -47,7 +47,13 @@ struct __libcpp_datasizeof {
   };
 #endif
 
+  // Disable warnings related to the use of `offsetof` on non-standard layout or non-POD types
+  // TODO : Find a way to replace `offsetof` ?
```
Comment (philnik777) [inline libcxx/include/__type_traits/datasizeof.h:51]: I don't think this TODO is actionable from the libc++ side of things currently, so I'd rather not add it. `offsetof` is the right tool for what we are trying to achieve - even if it's technically UB.

File: libcxx/include/__type_traits/datasizeof.h [hunk 8]
```diff
@@ -47,7 +47,13 @@ struct __libcpp_datasizeof {
   };
 #endif
 
+  // Disable warnings related to the use of `offsetof` on non-standard layout or non-POD types
```
Comment (philnik777) [inline libcxx/include/__type_traits/datasizeof.h:50]:
```suggestion
  // _FirstPaddingByte<> is sometimes non-standard layout. Using `offsetof` is UB in that case, but GCC and Clang allow the use as an extension.
```

**Comment by ldionne** [comment]
> Previous CI failures due to `offsetof` warnings have been resolved. Thank you for your cooperation! The current CI error (libcxx-ci Benchmark) does not seem to be caused by this patch (other PRs seem to be failing in the same one), so I'll wait until it's fixed.

The CI issues with the Benchmarks should be fixed now, so if you rebase onto `main` it shouldn't be a problem anymore

**Review by philnik777 — APPROVED** [review]
LGTM from the libc++ side of things.

**Comment by kasuga-fj** [comment]
Thanks! (The upstream build process seems to be broken now, so I'll wait until it's fixed)
