### PR TITLE
[Hexagon] Fix -Wuninitialized warning

### LINKED ISSUE #125545: `-Wuninitialized` warnings in `llvm/lib/Target/Hexagon/`
```
In file included from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.cpp:55:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h: In constructor ‘llvm::BitTracker::UseQueueType::UseQueueType()’:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h:75:27: warning: member ‘llvm::BitTracker::UseQueueType::Dist’ is used uninitialized [-Wuninitialized]
   75 |     UseQueueType() : Uses(Dist) {}
      |                           ^~~~
In file included from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/HexagonBitSimplify.cpp:9:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h: In constructor ‘llvm::BitTracker::UseQueueType::UseQueueType()’:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h:75:27: warning: member ‘llvm::BitTracker::UseQueueType::Dist’ is used uninitialized [-Wuninitialized]
   75 |     UseQueueType() : Uses(Dist) {}
      |                           ^~~~
In file included from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/HexagonBitTracker.h:12,
                 from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/HexagonBitTracker.cpp:9:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h: In constructor ‘llvm::BitTracker::UseQueueType::UseQueueType()’:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h:75:27: warning: member ‘llvm::BitTracker::UseQueueType::Dist’ is used uninitialized [-Wuninitialized]
   75 |     UseQueueType() : Uses(Dist) {}
      |                           ^~~~
In file included from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/HexagonGenInsert.cpp:9:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h: In constructor ‘llvm::BitTracker::UseQueueType::UseQueueType()’:
/home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h:75:27: warning: member ‘llvm::BitTracker::UseQueueType::Dist’ is used uninitialized [-Wuninitialized]
   75 |     UseQueueType() : Uses(Dist) {}
      |                           ^~~~
```

I am using `gcc (GCC) 14.2.1 20240910` on Manjaro Linux.

### PR DESCRIPTION
**Pull request by androm3da**
`gcc (GCC) 14.2.1 20240910` reports the warning below on the baseline, this change fixes the warning.

    In file included from /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.cpp:55:
    /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h: In constructor ‘llvm::BitTracker::UseQueueType::UseQueueType()’:
    /home/user/CLionProjects/llvm-project/llvm/lib/Target/Hexagon/BitTracker.h:75:27: warning: member ‘llvm::BitTracker::UseQueueType::Dist’ is used uninitialized [-Wuninitialized]
       75 |     UseQueueType() : Uses(Dist) {}
          |                           ^~~~

Fixes #125545

### CODE REVIEW

File: llvm/lib/Target/Hexagon/BitTracker.h [hunk 1]
```diff
@@ -72,7 +72,7 @@ struct BitTracker {
   // Priority queue of instructions using modified registers, ordered by
   // their relative position in a basic block.
   struct UseQueueType {
-    UseQueueType() : Uses(Dist) {}
+    UseQueueType() : Dist(), Uses(Dist) {}
```
Comment (firewave) [inline llvm/lib/Target/Hexagon/BitTracker.h:75]: The explicit `Dist()` is redundant.

Comment (androm3da) [reply llvm/lib/Target/Hexagon/BitTracker.h]: fixed, thanks.

**Review by firewave — APPROVED** [review]

**Review by iajbar — APPROVED** [review]
