### PR TITLE
[clang-format] Fix TableGen nested DAGArg format

### LINKED ISSUE #154634: [Clang format] [Tablegen] Formatting tablegen lacks whitespaces
Commit 920079b7935352c28385c17bc8c36256bebcd279 

This link https://github.com/llvm/llvm-project/pull/153252#discussion_r2275556144 details an instance where tablegen formatting through clang format follows the top version instead of the bottom.
```
def : Pat<(vec.vt(avgceilu(vec.vt V128:$lhs), (vec.vt V128:$rhs))), (inst $lhs,
                                                                        $rhs)>;
```

```
def : Pat<(vec.vt (avgceilu (vec.vt V128:$lhs), (vec.vt V128:$rhs))),
          (inst $lhs, $rhs)>;
```

Between `vec.vt` and `(avgceilu`, I would think the formatter would leave a whitespace

### PR DESCRIPTION
**Pull request by hnakamura5**
Fixes https://github.com/llvm/llvm-project/issues/154634. 
Allow inserting space before DAGArg's opener paren when nested.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/unittests/Format/FormatTestTableGen.cpp [hunk 1]
```diff
@@ -185,11 +185,18 @@ TEST_F(FormatTestTableGen, SimpleValue6) {
                "      i32:$dst6,                                // dst6\n"
                "      i32:$dst7                                 // dst7\n"
                "  );\n"
-               "  let DAGArgBang = (!cast<SomeType>(\"Some\") i32:$src1,\n"
-               "      i32:$src2);\n"
+               "  let DAGArgBang =\n"
+               "      (!cast<SomeType>(\"Some\") i32:$src1, i32:$src2);\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTestTableGen.cpp:189]: Why does the line wrapping change (for better?) here now?

File: clang/unittests/Format/FormatTestTableGen.cpp [hunk 2]
```diff
@@ -185,11 +185,18 @@ TEST_F(FormatTestTableGen, SimpleValue6) {
...
+               "  let NestedDAGArg = ((DAGArg1 (v111 v112, v113), v12) v2,\n"
+               "      (DAGArg3 (v31 v32)));\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTestTableGen.cpp:191]: But here the line breaking is not after the `=`.

**Review by owenca — APPROVED** [review]
