### PR TITLE
[RISCV] Fix incorrect folding of select on ctlz/cttz

### LINKED ISSUE #155014: risc-v backend miscompile of cttz-related optimization
this function:
```
declare i7 @llvm.cttz.i7(i7, i1 immarg)

define i7 @f(i7 %0) {
  %2 = call i7 @llvm.cttz.i7(i7 %0, i1 false)
  %3 = icmp eq i7 %0, 0
  %4 = select i1 %3, i7 0, i7 %2
  ret i7 %4
}
```
is getting miscompiled by the RISCV64+B backend as:
```
f:
	ori	a0, a0, 128
	ctz	a0, a0
	andi	a0, a0, 6
	ret
```
the `6` in the output doesn't make sense, it is coming from an insufficiently-protected `Bitwidth - 1`. 

@MitchBriles, a student working with me, has the following candidate patch. it certainly fixes this case but we've not fully vetted it yet. actually, if nobody is in a rush to fix this, Mitch would like to be the one to submit the PR for it.

```
diff --git a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
index 4a1db80076..7a5ebf74c4 100644
--- a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
+++ b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
@@ -18740,6 +18740,10 @@ static SDValue foldSelectOfCTTZOrCTLZ(SDNode *N, SelectionDAG &DAG) {
   if (Cond->getOperand(0) != CountZeroesArgument)
     return SDValue();
 
+  unsigned BitWidth = CountZeroes.getValueSizeInBits();
+  if (!isPowerOf2_32(BitWidth))
+    return SDValue();
+
   if (CountZeroes.getOpcode() == ISD::CTTZ_ZERO_UNDEF) {
     CountZeroes = DAG.getNode(ISD::CTTZ, SDLoc(CountZeroes),
                               CountZeroes.getValueType(), CountZeroesArgument);
@@ -18748,7 +18752,6 @@ static SDValue foldSelectOfCTTZOrCTLZ(SDNode *N, SelectionDAG &DAG) {
                               CountZeroes.getValueType(), CountZeroesArgument);
   }
 
-  unsigned BitWidth = CountZeroes.getValueSizeInBits();
   SDValue BitWidthMinusOne =
       DAG.getConstant(BitWidth - 1, SDLoc(N), CountZeroes.getValueType());
 ```

### PR DESCRIPTION
**Pull request by MitchBriles**
This patch tries to fix [#155014](https://github.com/llvm/llvm-project/issues/155014). The pattern of `ctlz`/`cttz` -> `icmp` -> `select` can occur when accounting for targets which don't support `cttz(0)` or `ctlz(0)`. We can replace this with a mask, but **only on power-of-2 bitwidths**.

cc @lenary, @topperc

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -18754,7 +18758,6 @@ static SDValue foldSelectOfCTTZOrCTLZ(SDNode *N, SelectionDAG &DAG) {
                               CountZeroes.getValueType(), CountZeroesArgument);
   }
 
-  unsigned BitWidth = CountZeroes.getValueSizeInBits();
   SDValue BitWidthMinusOne =
       DAG.getConstant(BitWidth - 1, SDLoc(N), CountZeroes.getValueType());
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:18762]: Could we still allow non-power of 2 types if we used `maskTrailingOnes(BitWidth)` instead?

Comment (MitchBriles) [reply llvm/lib/Target/RISCV/RISCVISelLowering.cpp:18762]: This wouldn't work because it's handling the case where the MSB is set (which only happens with an input of 0). For example, in the case of `i7`, that mask would be `0b111` which is the max output of `ctlz`/`cttz` anyway.

File: llvm/test/CodeGen/RISCV/ctlz-cttz-select-fold.ll
[the remark this answers is not in the document]
Comment (MitchBriles) [reply llvm/test/CodeGen/RISCV/ctlz-cttz-select-fold.ll:1]: Ah, I see, thank you. That seems like the right move, I'll move them now.

**Review by topperc — APPROVED** [review]
LGTM

**Review by lukel97 — APPROVED** [review]

**Comment by lukel97** [comment]
Thanks for fixing this. Before this lands can you turn off "Keep my email address private" in your GitHub account settings? It's a developer policy so buildbots are able to notify you if something comes up with your patch: https://llvm.org/docs/DeveloperPolicy.html#id12

**Comment by MitchBriles** [comment]
> Thanks for fixing this. Before this lands can you turn off "Keep my email address private" in your GitHub account settings? It's a developer policy so buildbots are able to notify you if something comes up with your patch: https://llvm.org/docs/DeveloperPolicy.html#id12

Done.
