### PR TITLE
[clang-tidy] Fix `readability-container-data-pointer` check

### LINKED ISSUE #164852: [clang-tidy] readability-container-data-pointer suggests incorrect fix for container held by pointer
compiler explorer reproducer here: https://godbolt.org/z/nM3TPeKhj

The following code:
```
#include <memory>
#include <vector>

void g(int *p);

void f()
{
    std::unique_ptr<std::vector<int>> p{std::make_unique<std::vector<int>>()};
    g(&(*p)[0]);
}
```

is correctly flagged at the call site to `g()`, but the fixit suggested is incorrect: `g(*p.data())` because the `.` binds tighter than the `*`.  The correct fixit should be `g((*p).data())`.

The failure can be reproduced by adding `--fix` to the compiler explorer options for clang-tidy.

### PR DESCRIPTION
**Pull request by zeyi2**
Fix issue in readability-container-data-pointer when the container expression is a dereference (e.g., `&(*p)[0]`). The previous fix-it suggested `*p.data()`, which changes semantics because `.` binds tighter than `*`. The fix now correctly suggests `(*p).data()`.

Closes [#164852](https://github.com/llvm/llvm-project/issues/164852)

### CODE REVIEW

**Review by EugeneZelenko — COMMENTED** [review]
Please mention changes in Release Notes.

File: clang-tools-extra/test/clang-tidy/checkers/readability/container-data-pointer.cpp [hunk 1]
```diff
@@ -144,3 +150,9 @@ int *r() {
   // CHECK-MESSAGES: :[[@LINE-1]]:10: warning: 'data' should be used for accessing the data pointer instead of taking the address of the 0-th element [readability-container-data-pointer]
   // CHECK-FIXES: return holder.v.data();
 }
+
+void s(std::unique_ptr<std::vector<unsigned char>> p) {
```
[the remark this answers is not in the document]
Comment (zeyi2) [reply clang-tools-extra/test/clang-tidy/checkers/readability/container-data-pointer.cpp]: Hi, thanks for reviewing. I've added a new test as requested :)

File: clang-tools-extra/clang-tidy/readability/ContainerDataPointerCheck.cpp [hunk 2]
```diff
@@ -71,20 +71,20 @@ void ContainerDataPointerCheck::registerMatchers(MatchFinder *Finder) {
...
+              cxxOperatorCallExpr(
+                  hasOverloadedOperatorName("[]"), argumentCountIs(2),
+                  hasArgument(0, ContainerExpr), hasArgument(1, Zero)),
+              cxxMemberCallExpr(callee(cxxMethodDecl(hasName("operator[]"))),
+                                on(ContainerExpr), argumentCountIs(1),
+                                hasArgument(0, Zero)),
+              arraySubscriptExpr(hasLHS(ContainerExpr), hasRHS(Zero)))))))
+          .bind(AddressOfName);
+
+  Finder->addMatcher(traverse(TK_AsIs, AddressOfMatcher), this);
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/readability/ContainerDataPointerCheck.cpp]: You moved `TK_AsIs` from functions-level to `addMatcher` which essentially is the same.
What I suggest is not introducing `TK_AsIs` in the first place anywhere

Comment (vbvictor) [reply clang-tools-extra/clang-tidy/readability/ContainerDataPointerCheck.cpp]: Thank you for detailed description! Your English is good enough to understand everything:)

So based on the feedback, I think we should drop support for `template unique_ptr<T>` case with `TK_AsIs` because it may introduce the following problem:

Consider 2 specializations, one with `MyArray` which doesn't have `data()` member:
```cpp
template <typename T>
void u(std::unique_ptr<T> p) {
  f(&(*p)[0]); // warning because of 'std::vector<int>'
}

template void u<std::vector<int>>(std::unique_ptr<std::vector<int>>);
template void u<MyArray>(std::unique_ptr<MyArray>); // don't have `.data()`
```

So the check will fire for `std::vector` but we can't actually change `[0]` to `data()` because our other type `MyArray` will give compilation error because it doesn't have `data()` member.

This is I think why `TK_IgnoreUnlessSpelledInSource` was used in the first place: to avoid such false-positives.

I guess we can not just revert to previous version and LGTM

**Review by vbvictor — APPROVED** [review]
LGTM
You can apply changes from GitHub and could be merged
