### PR TITLE
[CodeGen] Get rid of incorrect `std` template specializations

### LINKED ISSUE #160684: [CodeGen] `std::less<llvm::rdf::RegisterRef>` and `std::equal_to<llvm::rdf::RegisterRef>` full specializations don't satisfy the standard requirements
The following full specializations don't satisfy [[namespace.std]/5.2](https://eel.is/c++draft/namespace.std#5.2).

> 5. A program may explicitly instantiate a class template defined in the standard library only if the declaration
> - (5.1) depends on the name of at least one program-defined type, and
> - (5.2) the instantiation meets the standard library requirements for the original template.

https://github.com/llvm/llvm-project/blob/c1f8dbb11cff9e017e3d65c22162e11d04a61dfa/llvm/include/llvm/CodeGen/RDFRegisters.h#L337-L347
https://github.com/llvm/llvm-project/blob/c1f8dbb11cff9e017e3d65c22162e11d04a61dfa/llvm/include/llvm/CodeGen/RDFRegisters.h#L356-L367

These full specializations violate the requirements by being non-default-constructible, and arguably, being non-empty/stateful.

Perhaps it's better to specify non-`std` comparators rather than simply use `std::set<RegisterRef>` or `std::map<RegisterRef, T>`.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
This patch renames comparators
- from `std::equal_to<llvm::rdf::RegisterRef>` to `llvm::rdf::RegisterRefEqualTo`, and
- from `std::less<llvm::rdf::RegisterRef>` to `llvm::rdf::RegisterRefLess`.

The original specializations don't satisfy the requirements for the original `std` templates by being stateful and non-default-constructible, so they make the program have UB due to C++17 [namespace.std]/2, C++20/23 [namespace.std]/5.

> A program may explicitly instantiate a class template defined in the standard library only if the declaration
> - depends on the name of at least one program-defined type, and
> - the instantiation meets the standard library requirements for the original template.

Fixes #160684.

### CODE REVIEW

File: llvm/include/llvm/CodeGen/RDFRegisters.h [hunk 1]
```diff
@@ -334,42 +361,17 @@ template <> struct hash<llvm::rdf::RegisterAggr> {
...
-  // Make it a pointer just in case. See comment in `less` below.
-  const llvm::rdf::PhysicalRegisterInfo *PRI;
-};
-
 template <> struct equal_to<llvm::rdf::RegisterAggr> {
   bool operator()(const llvm::rdf::RegisterAggr &A,
                   const llvm::rdf::RegisterAggr &B) const {
     return A == B;
   }
 };
```
Comment (frederick-vs-ja) [inline llvm/include/llvm/CodeGen/RDFRegisters.h:369]: This full specialization is correct but probably meaningless. Perhaps we should remove it in a later PR.

**Comment by androm3da** [comment]
This change makes sense to me.

@iajbar or @aankit-quic please take a look.

**Comment by kparzysz** [comment]
You should clarify which requirement is violated.

**Comment by frederick-vs-ja** [comment]
@kparzysz Thanks. The requirements was in [namespace.std]/2 in C++17. I've updated the PR message and comments to make the reason of changes clearer.

**Review by kparzysz — APPROVED** [review]
