### PR TITLE
[clang] Fix missing diagnostic of declaration use when accessing TypeDecls through typename access

### LINKED ISSUE #58547: Missing diagnostic of declaration use when accessing TypeDecls through typename access
Repro: https://godbolt.org/z/TeTzfcdsv
```cpp
struct A {
  using ta [[deprecated]] = int;
};

using t1 = typename A::ta;

template <class B1> struct B {
  using tb = typename B1::ta;
};

template struct B<A>;
```

GCC emits diagnostic for deprecated `ta` on both uses, Clang emits no diagnostics at all.

### PR DESCRIPTION
**Pull request by mizvekov**
We were missing a call to DiagnoseUseOfDecl when performing typename access.

This refactors the code so that TypeDecl lookups funnel through a helper which performs all the necessary checks, removing some related duplication on the way.

Fixes #58547

Differential Revision: https://reviews.llvm.org/D136533

### CODE REVIEW

**Review by zyn0217 — COMMENTED** [review]
Sorry I didn't quite follow the discussion on phab, but do we still have issues with libc++ at this point?

**Comment by mizvekov** [comment]
No, at the time, I didn't have a MacOS machine to test this, and no one followed up to help track the problem.

Now that I have such a machine, I don't see the issue anymore.

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -3168,6 +3168,10 @@ class Sema final : public SemaBase {
 
   DeclGroupPtrTy ConvertDeclToDeclGroup(Decl *Ptr, Decl *OwnedType = nullptr);
 
+  enum class DiagCtorKind { None, Implicit, Typename };
+  QualType getTypeDeclType(DeclContext *LookupCtx, DiagCtorKind DCK,
+                           TypeDecl *TD, SourceLocation NameLoc);
```
Comment (zyn0217) [inline clang/include/clang/Sema/Sema.h:3173]: Although this is factored out from existing code, can we document the differences with `Ctx.getTypeDeclType()?` E.g. when do we want to use `Sema::getTypeDeclType()` and when otherwise

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -35,6 +35,9 @@ Potentially Breaking Changes
 ============================
 
 - The Objective-C ARC migrator (ARCMigrate) has been removed.
+- Fix missing diagnostics for uses of declarations when performing typename access,
+  such as when performing member access on a '[[deprecated]]' type alias.
+  `Issue 58547 <https://github.com/llvm/llvm-project/issues/58547>`
```
Comment (zyn0217) [inline clang/docs/ReleaseNotes.rst:40]: (#GH58547)

**Review by zyn0217 — APPROVED** [review]
Thanks for picking it up. I haven't dived into it yet, so let me ask if I understand the issue correctly: did we previously miss a call to `DiagnoseUseOfDecl()` in `Sema::CheckTypenameType()`? Otherwise, this looks good to me assuming there are no problems on macOS.

**Comment by mizvekov** [comment]
> Thanks for picking it up. I haven't dived into it yet, so let me ask if I understand the issue correctly: did we previously miss a call to `DiagnoseUseOfDecl()` in `Sema::CheckTypenameType()`? Otherwise, this looks good to me assuming there are no problems on macOS.

Yeah, missing check. This refactors the code so this bug is more unlikely to resurface.

**Comment by mizvekov** [comment]
When I posted the PR, I had run the libc++ tests locally on a MacOS machine and this all passes.

**Review by erichkeane — APPROVED** [review]
Shafik is going to ask for more details in the commit message :)  Could you better describe the problem there and how you fixed it?

**Comment by zmodem** [comment]
We're seeing new -Wunguarded-availability warnings after this. A reduced example:

```
$ cat /tmp/x.cc
template<class T> struct remove_cv { typedef T type; };

struct __attribute__((__availability__(android, introduced = 29))) AAudioStreamWrapper { };

template <typename T> struct Foo {
  T *p;
};

template <typename T> struct Bar {
  typename remove_cv<T>::type *p;
};


struct __attribute__((__availability__(android, introduced = 29))) User {
  AAudioStreamWrapper a; // okay
  Foo<AAudioStreamWrapper> b; // okay

  Bar<AAudioStreamWrapper> c; // not okay?
};

$ build/bin/clang -c -target aarch64-linux-android26 -Wunguarded-availability /tmp/x.cc
/tmp/x.cc:10:26: warning: 'AAudioStreamWrapper' is only available on Android 29 or newer [-Wunguarded-availability]
   10 |   typename remove_cv<T>::type *p;
      |                          ^
/tmp/x.cc:18:28: note: in instantiation of template class 'Bar<AAudioStreamWrapper>' requested here
   18 |   Bar<AAudioStreamWrapper> c; // not okay?
      |                            ^
/tmp/x.cc:3:68: note: 'AAudioStreamWrapper' has been marked as being introduced in Android 29 here, but the deployment target is Android 26
    3 | struct __attribute__((__availability__(android, introduced = 29))) AAudioStreamWrapper { };
      |                                                                    ^
/tmp/x.cc:9:30: note: annotate 'Bar<AAudioStreamWrapper>' with an availability attribute to silence this warning
    9 | template <typename T> struct Bar {
      |                              ^
1 warning generated.
```

I believe the new warning is not correct, since `c` (like the other members) is in fact guarded by the availability attribute.

I'll revert to green for now until this can be investigated.

**Comment by mizvekov** [comment]
@zmodem  Alright, I think this may have been the original bug, but you are the first to step in with a reproducer, thank you very much!
