### PR TITLE
Don't mark lambda non-dependent if nested in a generic lambda.

### LINKED ISSUE #118187: Cannot call lambda defined in immediate lambda
The following code compiles on both GCC and MSVC, but is refused by Clang ([Godbolt link](https://godbolt.org/z/M7KdM36YE)):
```c++
void func_1(auto)
{
    [](auto) consteval
    {
        [](auto)
        {
        }(123);
    };
}

auto func_2()
{
    func_1(123);
}
```

The error message:
```
<source>:6:9: error: no matching function for call to object of type '(lambda at <source>:6:9)'
    6 |         [](auto)
      |         ^~~~~~~~
    7 |         {
      |         ~
    8 |         }(123);
      |         ~
<source>:5:5: note: while substituting into a lambda expression here
    5 |     {
      |     ^
<source>:14:5: note: in instantiation of function template specialization 'func_1<int>' requested here
   14 |     func_1(123);
      |     ^
<source>:6:9: note: candidate template ignored: couldn't infer template argument 'auto:1'
    6 |         [](auto)
      |         ^
1 error generated.
```

From my experimentation:
- `func_1` must be a function template;
- The outer lambda must be immediate;
- The outer lambda must be a lambda template;
- The inner lambda must be a lambda template.

Note: the code from which I wrote this test-case is almost the same where I originally found #117676, so there could be some relation (or not).

### LINKED ISSUE #156579: [Clang][Regression:21] Rejects valid lambda invocation in constexpr if
The following C++20 code should be valid:
```c++
template <class>
auto f{[] (auto...) {
    if constexpr ([] (auto) { return true; }(0))
        return 0;
}};

int main() {
    f<int>();
}
```

Error since Clang 21:
```console
<source>:3:19: error: no matching function for call to object of type '(lambda at <source>:3:19)'
    3 |     if constexpr ([] (auto) { return true; }(0))
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:2:21: note: while substituting into a lambda expression here
    2 | auto f{[] (auto...) {
      |                     ^
<source>:8:5: note: in instantiation of variable template specialization 'f' requested here
    8 |     f<int>();
      |     ^
<source>:3:19: note: candidate template ignored: couldn't infer template argument 'auto:1'
    3 |     if constexpr ([] (auto) { return true; }(0))
      |    
```

See https://compiler-explorer.com/z/Kx5qWPev7.

### PR DESCRIPTION
**Pull request by katzdm**
Fixes #118187
Fixes #156579

An instantiated `LambdaExpr` can currently be marked as `LDK_NeverDependent` if it's nested within a generic lambda. If that `LambdaExpr` in fact depends on template parameters introduced by the enclosing generic lambda, then its dependence will be misreported as "never dependent" and spurious diagnostics can result.

The fix here proposed is a bit ugly, but the condition that it's being bolted onto already seems like a bit of a hack, so this seems no worse for wear.

Note that #89702 surfaced this change because it caused the inner lambda expression to (correctly) be considered in a constant-evaluated context. The affected check for whether to mark the inner lambda as `LDK_NeverDependent` therefore started to apply, whereas it didn't before.

**Tested**: `check-clang` and `check-cxx`.

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -15512,6 +15512,8 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
     DC = DC->getParent();
   if ((getSema().isUnevaluatedContext() ||
        getSema().isConstantEvaluatedContext()) &&
+      !(dyn_cast_or_null<CXXRecordDecl>(DC->getParent()) &&
```
Comment (erichkeane) [inline clang/lib/Sema/TreeTransform.h:15631]: We'd want to use `isa_and_present` (or `isa_and_nonnull` or w/e it is called) in this case.

That said, we probably would prefer to do something like extracting above the `if` a `const auto *RD = dyn_cast_if_present<CXXRecordDecl>(DC->getParent());`  then changing the check to RD && RD->isGenericLambda()` (or perhaps BETTER, pulling that whole thing out to a separate boolean with a reasonable name, so you have a place to put a comment).

Which brings me to the last thing, I'd like a comment explaining WHY this check should be here, it looks enough out of place as to why this cannot be dependent.

File: clang/lib/Sema/TreeTransform.h [hunk 2]
```diff
@@ -15512,6 +15512,8 @@ TreeTransform<Derived>::TransformLambdaExpr(LambdaExpr *E) {
...
+        cast<CXXRecordDecl>(DC->getParent())->isGenericLambda()) &&
       (DC->isFileContext() || !DC->getParent()->isDependentContext()))
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:15633]: So if I understand correctly, the inner generic lambda was previously caught by !DC->getParent()->isDependentContext() because its parent, despite it being a generic, is living in a non-dependent context (instantiated `t`?) such that the parent is never dependent which entails !isDependentContext()?

I am not quite sure if the approach is correct because the semantic of the dependency kind for lambda is sometimes counter-intuitive. For example, we even consider a generic lambda non-dependent if it lives in e.g. a namespace scope.

On the other hand, if the outer lambda (assuming it is generic) gets instantiated, then the 'generic' flag on it is still preserved, see `TransformTemplateParameterList()` in this function below and `CompleteLambdaCallOperator`, so at the time when the nested lambdas are half-transformed, the inner dependency kind might still be unexpected.

@mizvekov has been working on the removal of the DependencyKind and he might have some ideas too.

Comment (mizvekov) [reply clang/lib/Sema/TreeTransform.h:15633]: Yes, an instantiated generic lambda is still a generic lambda. Maybe this fix wants to look at whether the parent is a dependent context instead.

**Review by mizvekov — COMMENTED** [review]
FYI this fix and surrounding code should become obsolete when I get around to finishing https://github.com/llvm/llvm-project/pull/107942

**Review by zyn0217 — APPROVED** [review]
@katzdm 

I apologize for the long delay. After a second thought, I think the patch should work as expected.

Can you please rebase the patch and also add a test case for https://github.com/llvm/llvm-project/issues/156579? The added constant evaluation context reveals another bug, where we considered lambdas non-dependent too eagerly, causing template argument deduction to occur on mismatched template depths.

cc @cor3ntin we should backport this too

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -557,6 +557,7 @@ Bug Fixes to C++ Support
 - Diagnose unresolved overload sets in non-dependent compound requirements. (#GH51246) (#GH97753)
 - Fix a crash when extracting unavailable member type from alias in template deduction. (#GH165560)
 - Fix incorrect diagnostics for lambdas with init-captures inside braced initializers. (#GH163498)
+- Fixed spurious diagnoses of certain nested lambda expressions. (#GH149121)
```
Comment (zyn0217) [inline clang/docs/ReleaseNotes.rst]: Nit: it would be nice to mention 156579 too.

**Review by zyn0217 — APPROVED** [review]
LGTM, thanks!

File: clang/docs/ReleaseNotes.rst (hunk 3 above)
Comment (katzdm) [reply clang/docs/ReleaseNotes.rst]: Done!
