### PR TITLE
[llvm-objcopy] Apply encryptable offset to first segment, not section

### LINKED ISSUE #130472: llvm-objcopy regression: Invalid iOS Mach-O: __TEXT segment fileoffset is not zero
`llvm-objcopy good bad` on an iOS binary produces an output that is considered invalid by dyld.

`dyld_info bad` fails with:

```
bad [arm64]:
   __TEXT segment fileoffset is not zero
```

This regressed in https://github.com/llvm/llvm-project/pull/120995, identified by `git bisect` and verified by reverting https://github.com/llvm/llvm-project/commit/1a830aa1fe1e88749b563fefe18382842e0cff90. cc @drodriguez (**edit:** See https://github.com/llvm/llvm-project/pull/120995#issuecomment-2708707433 for what I believe that patch got wrong).

Steps to reproduce (sorry, don't have a version without Rust):

```shell
echo "fn main() {}" >> good.rs

# Rust version doesn't matter for this.
# Tested with the latest nightly & stable.
rustc --target=aarch64-apple-ios good.rs

llvm-objcopy good bad

# This is fine:
dyld_info good

# This fails:
dyld_info bad
```

### PR DESCRIPTION
**Pull request by drodriguez**
Bug introduced #120995. The LLD code calculates the "size" of the Mach-O headers, and then uses that size to place the segments, but the `__TEXT` section stays at `fileoff` zero. When I wrote the code into llvm-objcopy I calculated the extra space into the initial offset, which moved all the sections back 1 page.

Besides the modified test checking for the right `fileoff` values of the sections and the segments, I also manually checked the generated binaries after `llvm-objcopy` using `dyld_info`, as the bug report suggested.

Fixes #130472

### CODE REVIEW

**Comment by jh7370** [comment]
Unfortunately, this is outside my minimal knowledge of Mach-O, so I'll leave it to another reviewer to look into. If nobody else shows up, let me know and I'll try adding some other possible reviewers.

**Comment by drodriguez** [comment]
Sorry James. I though you were the other commenter in the other thread. My bad.

@glandium do you mind checking if this was what was affecting your binary from #120995 ? For some reason the `fileoff` being a page into the binary was not crashing anything for me, but the `dyld_info` checker obviously find it incorrect.

**Comment by jh7370** [comment]
> Sorry James. I though you were the other commenter in the other thread. My bad.

Not a problem. I'm involved in pretty much every change in llvm-objcopy ELF and generic code, but have also been heavily involved in some aspects of the other file formats, so confusion is entirely understandable.

File: llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp [hunk 1]
```diff
@@ -116,11 +116,10 @@ uint64_t MachOLayoutBuilder::layoutSegments() {
...
       O.Header.FileType == MachO::HeaderFileType::MH_OBJECT;
   uint64_t Offset = IsObjectFile ? (HeaderSize + O.Header.SizeOfCmds) : 0;
-  if (O.EncryptionInfoCommandIndex) {
-    // If we are emitting an encryptable binary, our load commands must have a
-    // separate (non-encrypted) page to themselves.
-    Offset = alignToPowerOf2(HeaderSize + O.Header.SizeOfCmds, PageSize);
-  }
+  // If we are emitting an encryptable binary, our load commands must have a
+  // separate (non-encrypted) page to themselves.
+  bool FirstSectExtraEncryptableOffset =
```
Comment (alx32) [inline llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp:121]: nit: `FirstSectExtraEncryptableOffset` sounds like `uint64_t` rather than `bool`
```suggestion
  bool RequiresPageAlignedSectionOffset =
```

**Review by alx32 — APPROVED** [review]
LGTM

**Review by DataCorrupted — APPROVED** [review]

File: llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp (hunk 1 above)
Comment (drodriguez) [reply llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp]: I chose a different spelling, but still using `Requires…`, which should be clearer this was a boolean. Thanks for the feedback!
