### PR TITLE
[InstrProf] Fix frontend generated function hash

### LINKED ISSUE #160248: llvm-cov wrongly reported execution count as 0 for executed functions
Reproducer:

```
$ cat foo.h
inline int foo(int a, int b, int c, int d, int e, int f) {
  if (a != b)
    return a < b;
  if (c != d)
    return c < d;
  if (a != c)
    return a < c;
  return e < f;
}

$ cat bar.c
#include "foo.h" // This is used to generate an unused record with hash 0 for foo()
int unused;

$ cat main.c
#include "foo.h"
int main() {
  return foo(4, 4, 8, 6, 2, 3);
}

$ clang -O2 -fprofile-instr-generate -fcoverage-mapping -shared bar.c -o libbar.so
$ clang -O2 -fprofile-instr-generate -fcoverage-mapping main.c ./libbar.so -o main
$ ./main
$ llvm-profdata merge ./default.profraw -o default.data
$ llvm-cov show -instr-profile ./default.data -object ./libbar.so -object ./main
foo.h:
    1|      0|inline int foo(int a, int b, int c, int d, int e, int f) {
    2|      0|  if (a != b)
    3|      0|    return a < b;
    4|      0|  if (c != d)
    5|      0|    return c < d;
    6|      0|  if (a != c)
    7|      0|    return a < c;
    8|      0|  return e < f;
    9|      0|}

main.c:
    1|       |#include "foo.h"
    2|       |
    3|      1|int main() {
    4|      1|  return foo(4, 4, 8, 6, 2, 3);
    5|      1|}

```

clang version:
```
$ clang --version
Homebrew clang version 21.1.1
Target: arm64-apple-darwin24.3.0
Thread model: posix
InstalledDir: .../homebrew/Cellar/llvm/21.1.1/bin
Configuration file: .../homebrew/etc/clang/arm64-apple-darwin24.cfg
```

In main.c, `foo()` was called once, but in foo.h, it's reported as unexecuted.

The root cause is stupid. I'll post it in the later comment.

### PR DESCRIPTION
**Pull request by zsrkmyn**
The most significant 4 bits in function hash are reserved bits, and are now used as context-sensitive flag, so they must be masked out. This tries to fix #160248.

### CODE REVIEW

**Review by ellishg — APPROVED** [review]

**Review by evodius96 — APPROVED** [review]
Sorry for the delay; I was out last week. LGTM.  Let me know if you need merge assistance.

**Comment by zsrkmyn** [comment]
@evodius96, many thanks for reviewing! And yes, my commit permission was revoked due to long-time inactivity, and need your help to merge it :-) thanks!

**Comment by zsrkmyn** [comment]
Actually I checked it days ago, and I believe the failed test isn't related to this change. Let me update the branch and check if it's still there.

**Comment by ellishg** [comment]
```
******************** TEST 'Profile-x86_64 :: check-same-common-code.test' FAILED ********************
  Exit Code: 1
  
  Command Output (stdout):
  --
  725c725
  < #define INSTR_PROF_INDEX_VERSION 12
  ---
  > #define INSTR_PROF_INDEX_VERSION 13
```

You'll need to update the `InstrProfData.inc` file in `compiler-rt` to fix the test.

**Comment by zsrkmyn** [comment]
Ooof, my bad. The log of CI was too long, and maybe I missed some things :-/ Let me try again.

**Comment by zsrkmyn** [comment]
@ellishg @evodius96 All check has passed now. Could you help merge it? many thanks!

**Comment by ellishg** [comment]
> @ellishg @evodius96 All check has passed now. Could you help merge it? many thanks!

I can merge this tomorrow morning

File: llvm/lib/ProfileData/InstrProfWriter.cpp [hunk 1]
```diff
@@ -542,7 +542,7 @@ Error InstrProfWriter::writeImpl(ProfOStream &OS) {
   // The WritePrevVersion handling will either need to be removed or updated
   // if the version is advanced beyond 12.
```
Comment (ellishg) [inline llvm/lib/ProfileData/InstrProfWriter.cpp:543]: It looks like we should either remove `WritePrevVersion` or update this version.
@teresajohnson you added this in https://github.com/llvm/llvm-project/pull/84505. Do you think we should continue to support this option and update the "prev" version?
