### PR TITLE
[flang][OpenMP][Semantics] resolve objects in the flush arg list

### LINKED ISSUE #136583: [flang] [OpenMP] Common block name symbol is not found (with the prefix "Internal")
The OpenMP spec may allow "a common block name (enclosed in slashes)."
```
% cat foo.f90
  common /c/ x
  real :: x
  !$omp flush(/c/)
end
% flang foo.f90
% flang -fopenmp foo.f90
flang-21: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: Semantic errors in foo.f90
./foo.f90:3:16: error: Internal: no symbol found for 'c'
    !$omp flush(/c/)
                 ^
```
Does the `Internal` signal that this is not-yet-implemented?  If so, please change the message to include the phrase "not yet implemented:".  Thanks!

### PR DESCRIPTION
**Pull request by tblah**
Fixes #136583

Normally the flush argument list would contain a DataRef to some variable. All DataRefs are handled generically in resolve-names and so the problem wasn't observed. But when a common block name is specified, this is not parsed as a DataRef. There was already handling in resolve-directives for OmpObjectList but not for argument lists. I've added a visitor for FLUSH which ensures all of the arguments have been resolved.

The test is there to make sure the compiler doesn't crashed encountering the unresolved symbol. It shows that we currently deny flushing a common block. I'm not sure that it is right to restrict common blocks from flush argument lists, but fixing that can come in a different patch. This one is fixing an ICE.

### CODE REVIEW

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -409,6 +409,19 @@ class OmpAttributeVisitor : DirectiveAttributeVisitor<llvm::omp::Directive> {
   }
   void Post(const parser::OpenMPDepobjConstruct &) { PopContext(); }
 
+  bool Pre(const parser::OpenMPFlushConstruct &x) {
+    PushContext(x.source, llvm::omp::Directive::OMPD_flush);
+    for (auto &arg : x.v.Arguments().v) {
+      if (auto *locator{std::get_if<parser::OmpLocator>(&arg.u)}) {
+        if (auto *object{std::get_if<parser::OmpObject>(&locator->u)}) {
+          ResolveOmpObject(*object, Symbol::Flag::OmpDependObject);
```
Comment (kiranchandramohan) [inline flang/lib/Semantics/resolve-directives.cpp:417]: Assuming this is a copy paste error. This is not a `DependObject`, so I think adding the `Symbol::Flag::OmpDependObject` is probably not right.

What do we want to do here? Is it just resolving the names in the flush argument list to the appropriate Fortran declarations? If so, we should use `ResolveName`.

Comment (kiranchandramohan) [reply flang/lib/Semantics/resolve-directives.cpp:417]: If common blocks are not handled in `ResolveName` then you can probably use `OmpFlushed` as the Symbol in `ResolveOmpObject`.

Comment (tblah) [reply flang/lib/Semantics/resolve-directives.cpp]: Yes it was a copy and paste error. Thanks for catching this.

I had assumed that given an object, the right way to resolve it was to call ResolveOmpObject. I have now changed to include only the relevant parts of the code inline.

**Review by kiranchandramohan — APPROVED** [review]
LG.

Note: There is a CI failure.

**Comment by tblah** [comment]
The CI failure looks unrelated. Thanks for the quick review.
