### PR TITLE
[clang-repl] Improve error message on failed undos

### LINKED ISSUE #143668: clang-repl %undo message is misleading when there is nothing left to undo
This is the smallest problem but it might be a good first time contributor issue so I'm reporting it anyway.

Start clang-repl and immediately `%undo`:
```
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\build>.\bin\clang-repl
clang-repl> %undo
error: Operation failed. Too many undos
```
Would be nice if this could tell it had reached the top (or bottom?) of the undo stack and customise the error to say that instead.
```
error: Operation failed. No input left to undo.
```
Here's a longer example that shows building a set of lines and undo-ing back to the beginning:
```
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\build>.\bin\clang-repl
clang-repl> int i = 1;
clang-repl> int j = i + 1;
clang-repl> %undo
clang-repl> int k = j + 1;
In file included from <<< inputs >>>:1:
input_line_3:1:9: error: use of undeclared identifier 'j'
    1 | int k = j + 1;
      |         ^
error: Parsing failed.
clang-repl> %undo
clang-repl> int l = i + 1;
input_line_4:1:9: error: use of undeclared identifier 'i'
    1 | int l = i + 1;
      |         ^
error: Parsing failed.
clang-repl> %undo
error: Operation failed. Too many undos
clang-repl>
```

### PR DESCRIPTION
**Pull request by aadanen**
Updated error message logic for undo function. Throws different errors for the case of there being nothing to undo, and for the case of requesting more undos than there are operations to undo.

Fixes https://github.com/llvm/llvm-project/issues/143668

### CODE REVIEW

**Comment by DavidSpickett** [comment]
> Hi all. This is my first pull request to an open source project. I am a student so have mercy on me!

Welcome!

> All i did was grep -r "Too many undos" and replace all instances of that string with the suggested replacement.

Simple and effective but, there is a little bit more context in this case, which I'll explain in a review comment in a moment.

Some admin stuff:
* We prefer that PRs (which become git commits) have a title of the form "[some project tags] <what it does>". So in this case I did `git log -- clang/lib/Interpreter/Interpreter.cpp` and concluded that it's probably `[clang-repl]`. This isn't some machine enforced thing, it just helps us humans recognise the changes later in logs and emails.
* The PR description will become the git commit's message (this is a setting GitHub allows projects to change, so you may see it work other ways in other projects). Which means that the PR description is more commit message, less cover letter. What I tend to do is put that sort of thing in a new comment.

Having said that, I think you'll be better able to describe the change once we've gone through some review. So leave both of those as is, for now, and we'll make sure they're ok later.

Another thing that you may not have had to do for the change as is, but will when I explain a bit more, is run the tests locally. So if you haven't already, follow https://llvm.org/docs/GettingStarted.html and get to the point where you can build clang. From there you can either use `ninja check-clang` or `ninja check-clang-unit`. The latter is just a specific subset of tests, which does cover what you're modifying here.

In addition to that, our CI will be running tests for you but it is much more useful to have them running locally so your edit -> run -> edit loop can be faster.

File: clang/unittests/Interpreter/InterpreterTest.cpp [hunk 1]
```diff
@@ -158,12 +158,12 @@ TEST_F(InterpreterTest, UndoCommand) {
...
   // Fail to undo.
   auto Err1 = Interp->Undo();
-  EXPECT_EQ("Operation failed. Too many undos",
+  EXPECT_EQ("Operation failed. No input left to undo",
             llvm::toString(std::move(Err1)));
   auto Err2 = Interp->Parse("int foo = 42;");
   EXPECT_TRUE(!!Err2);
   auto Err3 = Interp->Undo(2);
-  EXPECT_EQ("Operation failed. Too many undos",
+  EXPECT_EQ("Operation failed. No input left to undo",
```
Comment (DavidSpickett) [inline clang/unittests/Interpreter/InterpreterTest.cpp:166]: The complication here is that although the clang-repl `%undo` only undoes one input, the internal method can actually undo more than that. This test for example is trying to undo 2 things.

So the code needs to be a bit more intelligent. You have two situations:
* You have nothing left to undo.
* You have some things left to undo but *want* to undo more than that.

In both cases you error because you don't want to partially undo something, but the message should be specific. In the same order as above, I suggest:
* "No input left to undo"
* "Want to undo X inputs, only have Y" (with the message formatted with the correct numbers)

For formatting the error, we have some utilities to do that, I will find those for you.

Side note: "inputs" might not be the right noun, but stick with it for now and we can ask a clang-repl maintainer whether it's ok.

Comment (DavidSpickett) [reply clang/unittests/Interpreter/InterpreterTest.cpp:166]: I guess that the internal method can undo more than one input because you might be piping many lines at once into clang-repl? Anyway it's there so we should assume it is there for a good reason.

**Comment by DavidSpickett** [comment]
https://github.com/llvm/llvm-project/pull/149396#issuecomment-3088555387 is one of our automated checks, please follow its guidance. The reason we do this is so we can attribute changes for reasons around the licensing of contributions, there's more info in those links. It can be any valid address, you don't have to use a "personal" one, for instance I use my email address provided by my employer (that and they require that I do, but beside the point).

**Comment by aadanen** [comment]
1. I am able to build clang, compile the project, and I am currently running the "ninja check-clang-unit" tests. Although it does take an incredibly long time ( 45 minutes to an hour) but that's off topic

2. I attached my email

3. I think I understand what you're describing as far as how the code should be smarter. I will investigate and try to figure out where that edit will take place.

4. some of the commits in this PR are me updating the branch with changes to the main branch. I think its okay because this whole thing will get squashed at the end but just checking

**Comment by aadanen** [comment]
I put in inputs vs undo requests logic but I think the unit test might need to be edited as well

**Comment by aadanen** [comment]
Okay I think that does it :)

**Comment by DavidSpickett** [comment]
Looks great! CI should confirm the test is correct, and I added the clang-repl maintainer on review in case they have anything to say.

**Comment by DavidSpickett** [comment]
> I am able to build clang, compile the project, and I am currently running the "ninja check-clang-unit" tests. Although it does take an incredibly long time ( 45 minutes to an hour) but that's off topic

llvm/clang is not a light build at the best of times, but there are some things you can try - https://llvm.org/docs/GettingStarted.html#common-problems

If you do pick up another issue, I can give you some tailored suggestions for the specific task. For instance here, "check-clang" is runs all clang checks but I happened to know that the test you're changing is what we call a "unit test" and has it's own smaller target.

> some of the commits in this PR are me updating the branch with changes to the main branch. I think its okay because this whole thing will get squashed at the end but just checking

That's right. In fact I think those "merge" commits are preferred during review, versus rebasing, because GitHub likes to hide review state if you do the latter. It's also fine to not update the PR branch until review has concluded.

**Comment by DavidSpickett** [comment]
You have formatting to fix, I suggest you just copy and paste the diff in this one time.

Folks will have different ways to setup clang-format, I use the script https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting and manually run it (because I am too lazy to integrate it somewhere :) ).

I also add "black" for python formatting, into one giant command:
```
git diff -U0 --no-color --relative HEAD^ | ./clang/tools/clang-format/clang-format-diff.py -p1 -i -binary /home/david.spickett/build-llvm-aarch64/bin/clang-format && darker --revision HEAD~1 $(git diff-tree --no-commit-id --name-only HEAD -r)
```

If you're using an editor, do look into applying the format on save, it's much more convenient.

**Review by vgvassilev — APPROVED** [review]
Lgtm! Thank you @aadanen!

**Review by DavidSpickett — APPROVED** [review]
LGTM

@aadanen you won't be able to merge this yourself but I can once you've fixed the formatting.

**Comment by aadanen** [comment]
@DavidSpickett I applied clang-format and I think everything is looking good. Do I need to do anything else? Or is squashing the commits and merging up to someone with write permissions?

Also, thanks a lot for the help. I plan to find a new issue to work on soon. Thanks for offering to help there as well! I bet it will save me a lot of time and confusion.

**Comment by DavidSpickett** [comment]
> Do I need to do anything else?

No, all good.

> Or is squashing the commits and merging up to someone with write permissions?

GitHub will do the squashing, and yes I just clicked the merge button for you. Once you have established a track record you can [ask for permissions](https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access) to be able to do this yourself.

At no point do you *have* to have those permissions though, so I wouldn't bother with it for a while.

> Also, thanks a lot for the help. I plan to find a new issue to work on soon.

If you want to stay around clang-repl, I opened https://github.com/llvm/llvm-project/issues/143666 around the same time. Feel free to pick anything else of interest though.
