### PR TITLE
[clang] Fix wrong warning about missing init for flexible array members

### LINKED ISSUE #66300: [clang] `-Wmissing-field-initializers` incorrectly emits a warning when the last field of the initialized struct is a flexible array
$ cat test.c
```
struct S {
  int f0;
  int f1[];
};

typedef struct S S;

S s = {1, {2, 3}};
```

$ clang -c test.c -Wmissing-field-initializers 
test.c:8:17: warning: missing field 'f1' initializer [-Wmissing-field-initializers]
    8 | S s = {1, {2, 3}};

### PR DESCRIPTION
**Pull request by Fznamznon**
91088978d712cd7b33610c59f69d87d5a39e3113 shouldn't have removed an additional check that field has incomplete array type.

Fixes https://github.com/llvm/llvm-project/issues/66300

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
LGTM !
(double checking: this does not need a release note because it fixes something that was changed post 17 branch. Correct?)

**Comment by Fznamznon** [comment]
> (double checking: this does not need a release note because it fixes something that was changed post 17 branch. Correct?)

Exactly. There is a release note for guilty change.

File: clang/test/Sema/missing-field-initializers.c [hunk 1]
```diff
@@ -50,3 +50,11 @@ struct { int:5; int a; int:5; int b; int:5; } noNamedImplicit[] = {
...
   { 1 } // expected-warning {{missing field 'b' initializer}}
 };
+
+// GH66300
+struct S {
+  int f0;
+  int f1[];
+};
+
+struct S s = {1, {1, 2}}; // No warning
```
Comment (AaronBallman) [inline clang/test/Sema/missing-field-initializers.c:60]: Errr this test is dangerous because nothing allocates the flexible array member (so it's a buffer overrun and the `No warning` comment makes it seem like we never want to warn on that buffer overrun). I think tweaking the comment would help, but feel free to reword if you prefer.
```suggestion
// We previously would accidentally diagnose missing a field initializer for
// f1, now we no longer issue that warning (note, this code is still unsafe
// because of the buffer overrun).
struct S s = {1, {1, 2}};
```

**Comment by shafik** [comment]
Thank you for the quick fix

**Review by AaronBallman — APPROVED** [review]
LGTM!
