### PR TITLE
[clang-doc] Add basic e2e test

### LINKED ISSUE #93925: [clang][clang-doc] Introduce e2e test to clang-doc
Currently there isn't any e2e test for clang-doc html output it would be beneficial to add this in order to test for regressions between changes to clang-docs and view diffs of output as the tool progresses

### PR DESCRIPTION
**Pull request by PeterChou1**
Adds e2e tests for clang-doc, which serves as useful test against regression in the html output. It also serves as a helpful tool for code review as we can see the diffs to clang-docs output

Closes https://github.com/llvm/llvm-project/issues/93925

### CODE REVIEW

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 1]
```diff
@@ -0,0 +1,370 @@
+// RUN: mkdir -p %T/clang-doc/build
+// RUN: mkdir -p %T/clang-doc/include
+// RUN: mkdir -p %T/clang-doc/src
+// RUN: mkdir -p %T/clang-doc/docs
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:4]:
```suggestion
// RUN: mkdir -p %t/clang-doc/build
// RUN: mkdir -p %t/clang-doc/include
// RUN: mkdir -p %t/clang-doc/src
// RUN: mkdir -p %t/clang-doc/docs
```
`%T` is deprecated. https://llvm.org/docs/TestingGuide.html#substitutions
Also,  begin w/ `rm -rf %t`. It's probaly also fine to  rewrite the whole thing as a one-liner.
```suggestion
// RUN: rm -rf %t && mkdir -p %t/clang-doc/build %t/clang-doc/include %t/clang-doc/src %t/clang-doc/docs
```

File: clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/database_template.json [hunk 2]
```diff
@@ -0,0 +1,22 @@
+[
+{
+  "directory": "$test_dir/build",
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/database_template.json:3]: can't this just be "."? then everything is relative to that dir? if necessary you can `cd %t` to run commands in that dir. Subsequent test files run by `lit` will start from the build dir, so you don't have to cd back. It is generally nicer to have commands that can be run directly from the build dir, but its better to have easy to understand tests (and any tests at all) than to get bogged down with a minor detail like that. We can always file a bug to track that improvement as well.

You can see something similar to what I've suggested in `clang-tools-extra/test/clang-tidy/infrastructure/run-clang-tidy.cpp`.

Getting rid of `test_dir` should also mean you don't need that `sed` command.

File: clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/main.cpp [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+    std::cout << "Circle Area: " << circle.area() << std::endl;
+    std::cout << "Circle Perimeter: " << circle.perimeter() << std::endl;
+
+    // Rectangle
+    Rectangle rectangle(4.0, 6.0);
+    std::cout << "Rectangle Area: " << rectangle.area() << std::endl;
+    std::cout << "Rectangle Perimeter: " << rectangle.perimeter() << std::endl;
+
+    return 0;
+}
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/main.cpp:25]: Is this file necessary? there's no documentation in it ...

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 4]
```diff
@@ -0,0 +1,370 @@
...
+// RUN: sed 's|$test_dir|%/T/clang-doc|g' %S/Inputs/clang-doc-project1/database_template.json > %T/clang-doc/build/compile_commands.json
+// RUN: cp %S/Inputs/clang-doc-project1/*.h  %T/clang-doc/include
+// RUN: cp %S/Inputs/clang-doc-project1/*.cpp %T/clang-doc/src
+// RUN: cd %T/clang-doc/build
+// RUN: clang-doc --format=html --executor=all-TUs --output=%T/clang-doc/docs ./compile_commands.json
+// RUN: FileCheck -input-file=%T/clang-doc/docs/index_json.js -check-prefix=CHECK-JSON-INDEX %s
+// RUN: FileCheck -input-file=%T/clang-doc/docs/GlobalNamespace/Shape.html -check-prefix=CHECK-HTML-SHAPE %s
+// RUN: FileCheck -input-file=%T/clang-doc/docs/GlobalNamespace/Calculator.html -check-prefix=CHECK-HTML-CALC %s
+// RUN: FileCheck -input-file=%T/clang-doc/docs/GlobalNamespace/Rectangle.html -check-prefix=CHECK-HTML-RECTANGLE %s
+// RUN: FileCheck -input-file=%T/clang-doc/docs/GlobalNamespace/Circle.html -check-prefix=CHECK-HTML-CIRCLE %s
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:14]: nit: the typical way `FileCheck` lines are written is `FileCheck %s -check-prefix=FOO < %t/some/file`. Using `--input-file is fine, but its probably more typical to have it either be last, or for the `-check-prefix=` to be last.

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 5]
```diff
@@ -0,0 +1,370 @@
...
+
+// CHECK-JSON-INDEX: var JsonIndex = `
+// CHECK-JSON-INDEX: {
+// CHECK-JSON-INDEX:   "USR": "{{([0-9A-F]{40})}}",
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:18]: If you expect lines after the first match to be sequential, then use `CHECK-NEXT` (in this case `CHECK-JSON-INDEX-NEXT`) to make sure that the matches re in order.

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 6]
```diff
@@ -0,0 +1,370 @@
...
+// CHECK-HTML-CIRCLE:       </li>
+// CHECK-HTML-CIRCLE:     </ol>
+// CHECK-HTML-CIRCLE:   </div>
+// CHECK-HTML-CIRCLE: </main>
+
+
+
+
+
+
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:370]: nit: remove extra lines

**Review by ilovepi — CHANGES_REQUESTED** [review]

**Review by ilovepi — CHANGES_REQUESTED** [review]
Screen shots don't belong in the commit message. Public URLs are often OK for reference to LLVM source or a standards doc, but do make sure those are permalinks, and not pointed to something on say the `main` branch, which will change over time. 

In general, prefer including text and format it using markdown. This will show up in terminals and the GitHub UI equally well.

**Comment by ilovepi** [comment]
Also, I just noticed that the first comment has an `@` in it. The first comment in Github is special, as its really the body of the commit message, and will become that when you hit `Squash and merge`. Your question for @petrhosek may not even have been sent, as I don't know how github handles that. Please update the first message to be appropriate for the commit body, and copy any questions/context you have to another comment.

File: clang-tools-extra/test/lit.cfg.py [hunk 7]
```diff
@@ -69,8 +70,15 @@
 clang_tidy_headers = os.path.join(
     config.test_source_root, "clang-tidy", "checkers", "Inputs", "Headers"
 )
+
 config.substitutions.append(("%clang_tidy_headers", clang_tidy_headers))
 
+clang_doc_install = os.path.join(
+    os.path.dirname(shutil.which("clang-doc")), "..", "share", "clang"
+)
```
Comment (ilovepi) [inline clang-tools-extra/test/lit.cfg.py:78]: I don't think we wan't to be using something equivalent to `which clang-doc` in the lit config. First, I don't see this pattern used anywhere else in LLVM. Second, its completely unclear to me why this is necessary.

Comment (PeterChou1) [reply clang-tools-extra/test/lit.cfg.py:78]: I'd wanted a way to copy index.js to the install directory is there another way to accomplish that?

Comment (ilovepi) [reply clang-tools-extra/test/lit.cfg.py:78]: what do you mean by "install directory"? the directory that we install toolchain components into w/ `ninja install`? the place where you're running tests? or something else?

Comment (PeterChou1) [reply clang-tools-extra/test/lit.cfg.py:78]: when the windows runner is building it isn't copying the asset files to the ${CMAKE_INSTALL_DATADIR}/clang defined here https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-doc/tool/CMakeLists.txt
you can view some the logs here
https://buildkite.com/llvm-project/github-pull-requests/builds/68626#018fcd51-66a7-4091-b861-7f756301a191

I figured i would just manually copy the files in run directives for the test cases

**Comment by ilovepi** [comment]
A few meta comments on the particulars of the commit title and message:
1. Please change the title to only have the [clang-doc] tag. This doesn't impact `clang` at all. We use the`[tag] Title` convention to make it easy to understand where the changes are, and what they affect. Here something appropriate is either `[clang-doc] Add basic e2e test` or `[clang-doc][test] Add basic e2e test`.
2. The first comment on GitHub is special in a PR, as its the commit body. Ideally, it would have a description of what your change is doing and why. For tests, its often beneficial to put some rationale or explanation in the commit message, if there isn't a place to document it in the source.
3. If you only reference an issue, it just creates a cross ref. If your commit should fix or close the issue, there are special keywords you can put in the commit body for that (see [this reference](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)).

File: clang-tools-extra/test/lit.cfg.py (hunk 7 above)
Comment (ilovepi) [reply clang-tools-extra/test/lit.cfg.py:78]: so the CMAKE_INSTALL_DATADIR variable is used when you build the install target w/ `ninja install` or equivalent. The install target isn't the build of clang/llvm or even clang-doc. Instead it copies the artifacts you want to install into their final location. Essentially, imagine if you wanted to install clang to`/usr/bin/`, and all its headers to `/usr/include/`, and all its libs to `/usr/lib/`. That's basically what the install step is for, and you can point the base install directory to be anywhere. For instance I have a `$HOME/clang-install/` folder that I install the toolchain into when I need to use it in production type situations. For daily development, I just run things out of my `build` folder. The build folder is also where tests run.

This may be hidden by your IDE, but esentialy, you point CMake at the project, and tell it to build everything in some folder, usually called `build`.  After CMake runs and sets up all the build files for a build system, like `ninja` or `make`,  you can build the project by using the right build command. For clang-doc, that would be something like `ninja clang-doc` or `ninja check-clang-extra-clang-doc` to run its tests. But that won't install anything, it just builds things in the `build` directory. To install you'd run `ninja install` and then only the things that were important to ship would be installed to the location you specified, or to `/usr/local/` on Linux if you didn't specify anything.

The default style sheet (and any other fixed resources) should be easy for you to either copy to the right place, or to pass into the `clang-doc` command line, since its path relative to the source directory is fixed. @petrhosek may know of some other mechanism to force an asset to be copied into the build directory, but I'm not sure that is required in this case.

Comment (PeterChou1) [reply clang-tools-extra/test/lit.cfg.py:78]: I will note that currently there isn't a mechanism to pass another default stylesheet to the clang-doc the option               --stylesheets=<string> in clang-doc only extends the css stylesheet but still requires default stylesheet to be present.
I was trying to find a ways to copy the asset via the lit command line but i can't seem to do it

Comment (PeterChou1) [reply clang-tools-extra/test/lit.cfg.py:78]: actually that's probably a problem with clang-doc default behaviour. It should be that --stylesheet should replace the default stylesheet not extend it

Comment (ilovepi) [reply clang-tools-extra/test/lit.cfg.py:78]: That's also likely true, but TBH I don't have a problem running clang-doc from the build directory, so maybe something else is wrong?

**Review by ilovepi — COMMENTED** [review]
All of the changes related to allowing a different path for the assets belong in their own PR, or if they're invasive, perhaps multiple PRs.

File: clang-tools-extra/clang-doc/tool/ClangDocMain.cpp [hunk 8]
```diff
@@ -186,19 +196,36 @@ Example usage for a project using a compile commands database:
...
-    llvm::SmallString<128> IndexJS;
-    llvm::sys::path::native(AssetsPath, IndexJS);
-    llvm::sys::path::append(IndexJS, "index.js");
-    CDCtx.UserStylesheets.insert(CDCtx.UserStylesheets.begin(),
-                                 std::string(DefaultStylesheet));
-    CDCtx.FilesToCopy.emplace_back(IndexJS.str());
+    if (!UserAssetPath.empty()) {
+        std::error_code code;
+        llvm::sys::fs::directory_iterator dirIt(std::string(UserAssetPath), code);
+        while (!code && dirIt != llvm::sys::fs::directory_iterator()) {
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:202]: I'm not sure the logic here is correct. You check the error code, but what happens if that directory doesn't exist? To me it looks like the AssetsPath is never configured.

File: clang-tools-extra/clang-doc/tool/ClangDocMain.cpp [hunk 9]
```diff
@@ -186,19 +196,36 @@ Example usage for a project using a compile commands database:
...
+        llvm::SmallString<128> DefaultStylesheet;
+        llvm::sys::path::native(AssetsPath, DefaultStylesheet);
+        llvm::sys::path::append(DefaultStylesheet,
+                                "clang-doc-default-stylesheet.css");
+        llvm::SmallString<128> IndexJS;
+        llvm::sys::path::native(AssetsPath, IndexJS);
+        llvm::sys::path::append(IndexJS, "index.js");
+        CDCtx.UserStylesheets.insert(CDCtx.UserStylesheets.begin(),
+                                     std::string(DefaultStylesheet));
+        CDCtx.FilesToCopy.emplace_back(IndexJS.str());
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:227]: probably each of these branches could be extracted into a helper function to make this a bit easier to follow, but you do want to be careful to ensure the user path can fall back to the default behavior, or give very clear errors about missing assets/paths.

**Comment by ilovepi** [comment]
Also, the current PR only has tests for the HTML output. Please file separate bugs for the other formats, and be sure to follow up with more tests for those formats.

**Comment by PeterChou1** [comment]
I split the PR into 2 this PR relies on https://github.com/llvm/llvm-project/pull/94717

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 10]
```diff
@@ -0,0 +1,361 @@
+// RUN: rm -rf %t && mkdir -p %t/build %t/include %t/src %t/docs
+// RUN: sed 's|$test_dir|%/t|g' %S/Inputs/clang-doc-project1/database_template.json > %t/build/compile_commands.json
+// RUN: cp %S/Inputs/clang-doc-project1/*.h  %t/include
+// RUN: cp %S/Inputs/clang-doc-project1/*.cpp %t/src
+// RUN: cd %t
+// RUN: clang-doc --format=html --executor=all-TUs --asset=%S/Inputs ./build/compile_commands.json
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:6]: I'm still not convinced you need to `cp` almost anything. If the "project" folder in inputs is laid out correctly (modulo the output location for documentation) then I think you'll be good w/o the need to copy any files. The `compile_commands.json` can be used in place if a relative path works for the "directory" key. If that doesn't work, you'll likely still have to copy the `compile_commands.json` file, but you can just replace the `test_dir` w/  the expansion of `%S/Inputs` using `sed` and won't have to `cd` at all if you use the  `--output=` option and point it at `%t`.

Does that make sense? I'm trying to limit the amount of complexity in the test setup, because I don't see the copy steps as necessary or valuable. To me, it seems like if the `Inputs/basic-project` files and directories are set up the way you want them, then you don't really need to do much, other than use the right command line w/ `clang-doc`. This is typically how we want to set up tests, whenever possible.

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp [hunk 11]
```diff
@@ -0,0 +1,361 @@
+// RUN: rm -rf %t && mkdir -p %t/build %t/include %t/src %t/docs
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/clang-doc-project1.cpp:1]: I think this is a `.cp` file because it used to hold `main()`, right? Probably just `basic-project.test` is fine. or `shape-project.test`. It's typical to use a `.test` extension in files that are only used to hold the `RUN`/`CHECK` lines. `lld/test/ELF` has a lot of examples like that. I'm sure there are others too.

**Review by ilovepi — COMMENTED** [review]
This is getting pretty close, but there's a few things I'd like to iron out before landing. Plus I believe this has a dependency on the `--assets` flag changes.

File: clang-tools-extra/test/clang-doc/clang-doc-project1.cpp (hunk 10 above)
Comment (PeterChou1) [reply clang-tools-extra/test/clang-doc/clang-doc-project1.cpp]: I removed the copying so the commands run should be simplified I based most of the commands off a test case I found here https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/test/clang-move/move-class.cpp
its also why I used the .cpp extension for the test case 😅

File: clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/database_template.json [hunk 12]
```diff
@@ -0,0 +1,17 @@
+[
+  {
+    "directory": "$test_dir/build",
```
[the remark this answers is not in the document]
Comment (PeterChou1) [reply clang-tools-extra/test/clang-doc/Inputs/clang-doc-project1/database_template.json]: I tried getting relative paths to work but it didn't seem to work

**Comment by petrhosek** [comment]
Do we really need a full CSS when we're only checking the HTML? Could we just include a super minimal (or even empty) CSS?

**Comment by PeterChou1** [comment]
> Do we really need a full CSS when we're only checking the HTML? Could we just include a super minimal (or even empty) CSS?

I just realize we probably don't need any css or js we just need the files

**Comment by PeterChou1** [comment]
I think this finally works i think we could also shelve https://github.com/llvm/llvm-project/pull/94717
since I wrote that pr to get around the fact that we can't copy assets

File: clang-tools-extra/clang-doc/tool/CMakeLists.txt [hunk 13]
```diff
@@ -25,3 +25,11 @@ install(FILES ../assets/clang-doc-default-stylesheet.css
...
   DESTINATION "${CMAKE_INSTALL_DATADIR}/clang"
   COMPONENT clang-doc)
+
+add_custom_target(copy-clang-doc-assets
+        COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/../assets" "${CMAKE_BINARY_DIR}/share/clang"
+        DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/../assets"
+        COMMENT "Copying Clang-Doc Assets"
+)
+set_target_properties(copy-clang-doc-assets PROPERTIES FOLDER "Clang-Doc/Assets")
+add_dependencies(clang-doc copy-clang-doc-assets)
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/tool/CMakeLists.txt:35]: Let's leave this to #95187. The copying of assets is a separate issue, and that is already under review.

**Review by ilovepi — COMMENTED** [review]
The files in the `Input` folder don't need a `clang-doc` prefix. They're already under `test/clang-doc`

I'd also suggest renaming the folder from `project1` to something like `basic-project`.

**Review by ilovepi — COMMENTED** [review]
Also, I'm not sure I understand the need for empty files. If we don't need them, then lets remove them. If you need to use an empty file for some test, you can create those w/ `touch` in the test itself, but I don't see those referenced at all in `basic-project.test`.

**Comment by ilovepi** [comment]
> I think this finally works i think we could also shelve #94717 since I wrote that pr to get around the fact that we can't copy assets

I think being able to override the `css` and `js` files is still probably useful. 

What I'm wondering, now is that if the `.css` and `.js` files can be empty, is there a reason its a fatal error to not have those available? Again, that's an independent change, but if it doesn't then we may not need to update the cmake in https://github.com/llvm/llvm-project/pull/95187 at all.

If that is the case, we should stop making it a fatal error if `clang-doc` can't find the asset files. Then, I can abandon #95187, and you can probably land #94717, since it won't fail anymore. Tests can then use the `--asset=` flag as needed to customize the HTML. @petrhosek WDYT?

**Comment by ilovepi** [comment]
Petr and I spoke offline. https://github.com/llvm/llvm-project/pull/95187, is still independently useful, since it matches our normal conventions about the build directory matching the install directory. 

I think we agree on it not being a fatal error, though if it can generate HTML without those assets. https://github.com/llvm/llvm-project/pull/94717, is also useful.

File: clang-tools-extra/clang-doc/tool/ClangDocMain.cpp [hunk 14]
```diff
@@ -299,8 +299,7 @@ Example usage for a project using a compile commands database:
   llvm::outs() << "Generating assets for docs...\n";
   Err = G->get()->createResources(CDCtx);
   if (Err) {
-    llvm::errs() << toString(std::move(Err)) << "\n";
-    return 1;
+    llvm::outs() << "Warning: " << toString(std::move(Err)) << "\n";
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/tool/ClangDocMain.cpp:302]: @petrhosek do you know if there's a better way to emit a warning from clang-tools? I'm hesitant to say this is a good practice. I see this in clang-tidy, but IDK if that's really an idiomatic way to handle it. https://github.com/llvm/llvm-project/blob/c091dd48008ba6d85aee68227077ee05daeb7ca7/clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp#L640

In clang or LLVM, we'd normally use one of the Reports APIs, but I don't think we have access to those in clang-doc. not sure what the right thing to do here is.

Also,  think we normally use lower-case `warning:`.

**Review by ilovepi — APPROVED** [review]

File: clang-tools-extra/test/clang-doc/basic-project.test [hunk 15]
```diff
@@ -0,0 +1,358 @@
...
+// JSON-INDEX-NEXT:       ]
+// JSON-INDEX-NEXT:     }
+// JSON-INDEX-NEXT:   ]
+// JSON-INDEX-NEXT: }`;
+
+// HTML-SHAPE: <!DOCTYPE html>
+// HTML-SHAPE-NEXT: <meta charset="utf-8"/>
+// HTML-SHAPE-NEXT: <title>class Shape</title>
+// HTML-SHAPE-NEXT: <link rel="stylesheet" href="../clang-doc-default-stylesheet.css"/>
+// HTML-SHAPE-NEXT: <script src="../index.js"></script>
```
Comment (nico) [inline clang-tools-extra/test/clang-doc/basic-project.test:60]: This uses `../index.js` while the other three use `{{.*}}/index.js`. Shouldn't all four be consistent?

File: clang-tools-extra/test/clang-doc/Inputs/basic-project/src/Calculator.cpp [hunk 16]
```diff
@@ -0,0 +1,21 @@
+#include "Calculator.h"
+#include <stdexcept>
```
Comment (nico) [inline clang-tools-extra/test/clang-doc/Inputs/basic-project/src/Calculator.cpp:2]: Tests must be freestanding and cannot include system headers.

**Comment by bogner** [comment]
This test fails on multi-config cmake generators (`cmake -G 'Visual Studio` etc), exposing an existing bug in clang-doc. Since binaries end up under a subdirectory like `build/Release/bin` but the default json and such end up in `build/share/clang-doc`, running `clang-doc` from the bin dir doesn't find the default configs.

There's one attempt to fix this here: https://github.com/llvm/llvm-project/pull/97505
