### PR TITLE
[clang] Extend lifetime analysis to support assignments for pointer-like objects.

### LINKED ISSUE #63310: Extend -Wdangling to handle assignments, not just initializations
Currently, `-Wdangling`/`-Wdangling-gsl` detect the following:
```cpp
std::string foo() { return ""; }
int main() {
    std::string_view v = foo();  // error: object backing the pointer will be destroyed at the end of the full-expression [-Werror,-Wdangling-gsl]
}
```
However, they fail to detect this case:
```cpp
std::string foo() { return ""; }
int main() {
    std::string_view v;
    v = foo();  // no error
}
```
It seems the compiler currently only handles initializations, not regular assignments, despite them posing the same issue. So it would be great to handle the second case as well.

More generally, if a `lifetimebound` object is assigned to a non-temporary expression, then I believe it would be correct to issue the diagnostic.

### PR DESCRIPTION
**Pull request by hokein**
This is a follow-up patch to #96475 to detect dangling assignments for C++ pointer-like objects (classes annotated with the `[[gsl::Pointer]]`).  Fixes #63310.

Similar to the behavior for built-in pointer types, if a temporary owner (`[[gsl::Owner]]`) object is assigned to a pointer-like class object, and this temporary object is destroyed at the end of the full assignment expression, the assignee pointer is considered dangling. In such cases, clang will emit a warning:

```
/tmp/t.cpp:7:20: warning: object backing the pointer my_string_view will be destroyed at the end of the full-expression [-Wdangling-assignment-gsl]
    7 |   my_string_view = CreateString();
      |                    ^~~~~~~~~~~~~~
1 warning generated.
```

This new warning is `-Wdangling-assignment-gsl`. It is initially disabled, but I intend to enable it by default in clang 20.

I have initially tested this patch on our internal codebase, and it has identified many use-after-free bugs, primarily related to `string_view`.

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Any reason why it is not enabled by default for clang-19? Are there any known false positives or just precautions?

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 1]
```diff
@@ -1073,14 +1078,16 @@ static void checkExprLifetimeImpl(Sema &SemaRef,
...
+      if (!MTE || pathContainsInit(Path))
         return false;
       assert(shouldLifetimeExtendThroughPath(Path) ==
                  PathLifetimeKind::NoExtend &&
              "No lifetime extension for assignments");
-      if (!pathContainsInit(Path))
-        SemaRef.Diag(DiagLoc, diag::warn_dangling_pointer_assignment)
-            << AEntity->LHS << DiagRange;
+      SemaRef.Diag(DiagLoc,
+                   IsGslPtrInitWithGslTempOwner
```
Comment (Xazax-hun) [inline clang/lib/Sema/CheckExprLifetime.cpp:1087]: `IsGslPtrInitWithGslTempOwner` might no longer be an accurate name as it is also used for assignments. Naming is hard, I am ok leaving this as is. Alternatively, it could be something like `IsGslPtrValueFromGslTempOwner`.

**Review by Xazax-hun — APPROVED** [review]
Overall, looks good to me, thanks!

**Comment by hokein** [comment]
> Any reason why it is not enabled by default for clang-19? Are there any known false positives or just precautions?

It's primarily for caution. We're close to the clang 19 release cut, so I want to be conservative here. I haven't found any false positives with the current implementation, but I'd prefer to ensure stability before making it the default.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 2]
```diff
@@ -1284,16 +1294,26 @@ void checkExprLifetime(Sema &SemaRef, const InitializedEntity &Entity,
   auto LTResult = getEntityLifetime(&Entity);
   LifetimeKind LK = LTResult.getInt();
   const InitializedEntity *ExtendingEntity = LTResult.getPointer();
-  checkExprLifetimeImpl(SemaRef, &Entity, ExtendingEntity, LK, nullptr, Init);
+  bool EnableLifetimeWarnings = !SemaRef.getDiagnostics().isIgnored(
+      diag::warn_dangling_lifetime_pointer, SourceLocation());
+  checkExprLifetimeImpl(SemaRef, &Entity, ExtendingEntity, LK, nullptr, Init,
```
Comment (Xazax-hun) [inline clang/lib/Sema/CheckExprLifetime.cpp:1299]: Not really a problem since I do not expect people to turn off the default dangling warnings, but I wonder if we actually run this code when all dangling related diagnostics are off.

**Comment by Xazax-hun** [comment]
> We're close to the clang 19 release cut, so I want to be conservative here. 

I totally understand that. That being said, I think it should be really easy to cherry-pick turning a warning off to the release branch, so I'd be also OK with the alternative approach of releasing a release candidate with the warning on and only disabling it in a cherry-pick if there are some users experiencing some issues.

**Comment by Xazax-hun** [comment]
To clarify, I don't have strong feelings about whether the warning is on or off, I just wanted to point out that I would not be concerned about the short period before the feature work cutoff date. There is still some time to stabilize after the branching.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 3]
```diff
@@ -966,7 +969,8 @@ static bool pathOnlyInitializesGslPointer(IndirectLocalPath &Path) {
     if (It.Kind == IndirectLocalPathEntry::LifetimeBoundCall)
       continue;
     return It.Kind == IndirectLocalPathEntry::GslPointerInit ||
-           It.Kind == IndirectLocalPathEntry::GslReferenceInit;
+           It.Kind == IndirectLocalPathEntry::GslReferenceInit ||
```
Comment (usx95) [inline clang/lib/Sema/CheckExprLifetime.cpp:972]: nit: rename this function to `pathOnlyHandlesGslPointer` as it is not specific to initialisation.

File: clang/lib/Sema/CheckExprLifetime.cpp (hunk 2 above)
Comment (shafik) [inline clang/lib/Sema/CheckExprLifetime.cpp:1299]:
```suggestion
  checkExprLifetimeImpl(SemaRef, &Entity, ExtendingEntity, LK, /*AEntity=*/nullptr, Init,
```

nitpick

Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: We still need to run the code (not the gsl-specific part) even if we disable all dangling diagnostics. Because this code has the functionality that performs the lifetime extension when needed (see https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/CheckExprLifetime.cpp#L1043-L1045).

Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Done.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 4]
```diff
@@ -966,7 +969,8 @@ static bool pathOnlyInitializesGslPointer(IndirectLocalPath &Path) {
     if (It.Kind == IndirectLocalPathEntry::LifetimeBoundCall)
```
[the remark this answers is not in the document]
Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Rewrote the `if` with the `switch`.

File: clang/lib/Sema/CheckExprLifetime.cpp (hunk 3 above)
Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Done.

File: clang/lib/Sema/CheckExprLifetime.cpp (hunk 1 above)
Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Done, renamed to `IsGslPtrValueFromGslTempOwner`.

**Review by hokein — COMMENTED** [review]
Thanks for the review.

File: clang/test/SemaCXX/warn-dangling-local.cpp [hunk 5]
```diff
@@ -34,6 +34,6 @@ struct basic_string {
 };
 }  // namespace std
 void test(const char* a) {
-  // verify we're emitting the `-Wdangling-assignment` warning.
+  // verify we're emitting the `-Wdangling-assignment-gsl` warning.
   a = std::basic_string().c_str(); // expected-warning {{object backing the pointer a will be destroyed at the end of the full-expression}}
```
Comment (ilya-biryukov) [inline clang/test/SemaCXX/warn-dangling-local.cpp:38]: I'm a little confused here, since `a` is of type `const char*`, why do we mention the `-gsl` version of the warning here?

**Review by ilya-biryukov — APPROVED** [review]
LGTM, but I also have one question (either I don't understand something or there might be an error in the comment)

**Review by usx95 — APPROVED** [review]
LGTM. Thanks.
