### PR TITLE
[AMDGPU] Fix VGPR lowering for V_DUAL_FMAMK_F32

### LINKED ISSUE #170552: [AMDGPU] "Invalid VOPD pair was created" error with V_FMAMK_F32
If I add this test case:
```
diff --git a/llvm/test/CodeGen/AMDGPU/vopd-combine-gfx1250.mir b/llvm/test/CodeGen/AMDGPU/vopd-combine-gfx1250.mir
index b05edd046b87..93648f9dc0aa 100644
--- a/llvm/test/CodeGen/AMDGPU/vopd-combine-gfx1250.mir
+++ b/llvm/test/CodeGen/AMDGPU/vopd-combine-gfx1250.mir
@@ -4481,3 +4481,12 @@ body: |
       $vgpr3 = V_MOV_B32_e32 0, implicit $exec
       $vgpr0 = V_ADD_F32_e64_dpp $vgpr0, 0, $vgpr2, 0, $vgpr1, 0, 1, 1, 15, 15, 1, implicit $mode, implicit $exec
 ...
+
+---
+name: vopd_no_combine_fmamk_src1
+tracksRegLiveness: true
+body: |
+  bb.0:
+    $vgpr142 = V_FMAMK_F32 $vgpr377, 1069066811, $vgpr142, implicit $mode, implicit $exec
+    $vgpr145 = V_FMAC_F32_e32 1069066811, $vgpr366, $vgpr145, implicit $mode, implicit $exec
+...
```
it fails with:
```
Invalid VOPD pair was created
UNREACHABLE executed at /home/jayfoad2/git/llvm-project/llvm/lib/Target/AMDGPU/AMDGPULowerVGPREncoding.cpp:213!
```

### PR DESCRIPTION
**Pull request by rampitec**
Fixes: https://github.com/llvm/llvm-project/issues/170552

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp [hunk 1]
```diff
@@ -3450,6 +3450,12 @@ getVGPRLoweringOperandTables(const MCInstrDesc &Desc) {
   static const AMDGPU::OpName VOP2MADMKOps[4] = {
       AMDGPU::OpName::src0, AMDGPU::OpName::NUM_OPERAND_NAMES,
       AMDGPU::OpName::src1, AMDGPU::OpName::vdst};
+  static const AMDGPU::OpName VOPDFMAMKOpsX[4] = {
```
Comment (shiltian) [inline llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp]: I guess we are gonna run into similar issues in the future as well, since we have so many variants of how these operands are named. I fixed one not long ago as well.

**Review by shiltian — APPROVED** [review]

**Review by Sisyph — APPROVED** [review]
