### PR TITLE
[clang-format] Fix a bug in annotating lambda l_square

### LINKED ISSUE #95072: [clang-format]  incorrectly interprets C++ file as Objective-C
Minimal example test.h:
```c++
[this,a=a]() -> struct S { return {}; }
```
.clang-format:
```
---                                                                                                                                                                                                                                                                           
Language:        Cpp
```
Output of clang-format --style=file test.h:
Configuration file(s) do(es) not support Objective-C: /tmp/.clang-format

clang-format --version:
clang-format version 18.1.7

### PR DESCRIPTION
**Pull request by owenca**
Fixes #95072.

### CODE REVIEW

**Review by rymiel — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -1591,6 +1591,12 @@ TEST_F(TokenAnnotatorTest, UnderstandsLambdas) {
   EXPECT_TOKEN(Tokens[15], tok::arrow, TT_TrailingReturnArrow);
   EXPECT_TOKEN(Tokens[17], tok::l_brace, TT_LambdaLBrace);
 
+  Tokens = annotate("auto l = [] -> struct S { return {}; };");
```
Comment (rymiel) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1594]: Is the assignment to a variable necessary? None of the other lambda tests have this

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp]: Not really. I removed the assignment.
