### PR TITLE
[clang-format] Fix a bug in `DerivePointerAlignment: true`

### LINKED ISSUE #150327: clang-format adds extra spaces between type and pointer
After a8f5e9ed6b44562938ce07e2790be90be8f0a6b5, when using Google style, `MACRO(int*, std::function<void() &&>)` expands `int*` to `int *`.

i.e. if I add this test case to clang/unittests/Format/FormatTest.cpp, this now fails:
```c++
TEST_F(FormatTest, Macro) {
  verifyGoogleFormat("MACRO(int*, std::function<void() &&>);");
}
```

with this error:
```
clang/unittests/Format/FormatTestBase.h:90: Failure
Expected equality of these values:
  ExpectedCode
    Which is: "MACRO(int*, std::function<void() &&>);"
  FormattedCode
    Which is: "MACRO(int *, std::function<void() &&>);"
```

I'm not sure whether or not this is a diff we're fine just accepting. I'll ask around.

### PR DESCRIPTION
**Pull request by owenca**
This effectively reverts a4d4859dc70c046ad928805ddeaf8fa101793394 which didn't fix the problem that `int*,` was not counted as "Left" alignment.

Fixes #150327

### CODE REVIEW

File: clang/lib/Format/Format.cpp [hunk 1]
```diff
@@ -2641,28 +2641,19 @@ class Formatter : public TokenAnalyzer {
...
-        bool SpaceAfter = Tok->Next->hasWhitespaceBefore();
-        if (SpaceBefore && !SpaceAfter)
-          ++AlignmentDiff;
-        if (!SpaceBefore && SpaceAfter)
-          --AlignmentDiff;
+        const auto *Next = Tok->Next;
+        if (!Next)
+          break;
+        if (Prev->Tok.getIdentifierInfo())
+          AlignmentDiff += Tok->hasWhitespaceBefore() ? 1 : -1;
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/Format.cpp:2654]:
```suggestion
        if (Prev->Tok.getIdentifierInfo())
          AlignmentDiff += Tok->hasWhitespaceBefore() ? 1 : -1;
        if (!Next)
          break;
```
It could be incomplete code.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/Format.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/Format.cpp:2654]: Good point, but I still got a bug: `AlignmentDiff` gets incremented/decremented twice for each of `int *i`/`int* i`.

File: clang/lib/Format/Format.cpp [hunk 2]
```diff
@@ -2639,32 +2639,42 @@ class Formatter : public TokenAnalyzer {
...
+            // e.g. `int * i` or `int*i`
+            (PrecededByName && FollowedByName && SpaceBefore == SpaceAfter)) {
+          continue;
         }
-        bool SpaceBefore = Tok->hasWhitespaceBefore();
-        bool SpaceAfter = Tok->Next->hasWhitespaceBefore();
-        if (SpaceBefore && !SpaceAfter)
+
+        if ((PrecededByName && SpaceBefore) ||
+            (FollowedByName && !SpaceAfter)) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/Format.cpp:2669]: I don't know if this is the right thing.
I'm thinking of function definitions, where some arguments are not used and therefore not named.
`void foo(int* /*reserved*/, int &arg, int*)`

Comment (owenca) [reply clang/lib/Format/Format.cpp:2669]: Your example has two left alignments and one right alignment, so it gets formatted with left alignments:
```cpp
void foo(int* /*reserved*/, int& arg, int*)
```
Anything wrong here?

Comment (HazardyKnusperkeks) [reply clang/lib/Format/Format.cpp:2669]: But are the two left aligned `FollowedByName`? For the first one `Next` is a comment, for the second a parenthesis, no identifier. Or am I misunderstanding the code?

Comment (owenca) [reply clang/lib/Format/Format.cpp:2669]: I’ll add a comment for the `if` and `else if`.

Comment (HazardyKnusperkeks) [reply clang/lib/Format/Format.cpp:2669]: Thanks.

**Review by HazardyKnusperkeks — APPROVED** [review]
