### PR TITLE
[LifetimeSafety] Handle xvalue operand of LValueToRValue cast

### LINKED ISSUE #176292: [LifetimeSafety] lifetime annotation suggestion and inference does not work with `-std=c++23` or `-std=c++26`
https://godbolt.org/z/fPefGroxn

```cpp
auto id(auto a) { return a; }

int main() {
    int *p{};
    {
        int a = 42;
        p = id(&a);
    }
    auto result = *p;
}
```

With `-std=c++23 -Werror=experimental-lifetime-safety -Werror=experimental-lifetime-safety-cross-tu-suggestions -Wexperimental-lifetime-safety-intra-tu-suggestions -Xclang -fexperimental-lifetime-safety -Xclang -fexperimental-lifetime-safety-inference`:

```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 0
```

With `-std=c++20 -Werror=experimental-lifetime-safety -Werror=experimental-lifetime-safety-cross-tu-suggestions -Wexperimental-lifetime-safety-intra-tu-suggestions -Xclang -fexperimental-lifetime-safety -Xclang -fexperimental-lifetime-safety-inference`:

```
<source>:3:9: warning: parameter in intra-TU function should be marked [[clang::lifetimebound]] [-Wexperimental-lifetime-safety-intra-tu-suggestions]
    3 | auto id(auto a) { return a; }
      |         ^~~~~~
      |                [[clang::lifetimebound]]
<source>:9:13: note: in instantiation of function template specialization 'id<int *>' requested here
    9 |         p = id(&a);
      |             ^
<source>:3:26: note: param returned here
    3 | auto id(auto a) { return a; }
      |                          ^
<source>:9:17: error: object whose reference is captured does not live long enough [-Werror,-Wexperimental-lifetime-safety-permissive]
    9 |         p = id(&a);
      |                 ^
<source>:10:5: note: destroyed here
   10 |     }
      |     ^
<source>:11:20: note: later used here
   11 |     auto result = *p;
      |                    ^
1 warning and 1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by aeft**
Under C++23, P2266 wraps the operand of `return p;` in an xvalue NoOp cast for by-value parameters. The `CK_LValueToRValue` branch in FactsGenerator guarded on `!SubExpr->isLValue()`, breaking origin flow and silencing the suggestion for `int* id(int* p) { return p; }`.

Use `isGLValue()`, matching how origins are built and stripped elsewhere in the analysis.

Only add a RUN in suggestion test file, since some tests in `warn-lifetime-safety.cpp` cause a hard error under C++23. For example: `MyObj& f() { MyObj s; return s; }`. `error: non-const lvalue reference to type 'MyObj' cannot bind to a temporary of type 'MyObj'`.

Fixes: #176292

### CODE REVIEW

File: clang/test/Sema/warn-lifetime-safety-suggestions.cpp [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // RUN: rm -rf %t
 // RUN: split-file %s %t
 // RUN: %clang_cc1 -fsyntax-only -flifetime-safety-inference -fexperimental-lifetime-safety-tu-analysis -Wlifetime-safety-suggestions -Wlifetime-safety -Wno-dangling -I%t -I%S -verify %t/test_source.cpp
+// RUN: %clang_cc1 -fsyntax-only -std=c++23 -flifetime-safety-inference -fexperimental-lifetime-safety-tu-analysis -Wlifetime-safety-suggestions -Wlifetime-safety -Wno-dangling -I%t -I%S -verify %t/test_source.cpp
```
Comment (usx95) [inline clang/test/Sema/warn-lifetime-safety-suggestions.cpp:4]: Can you also add the previously failing test in the issue.

Comment (aeft) [reply clang/test/Sema/warn-lifetime-safety-suggestions.cpp:4]: We already have these tests, including `return_pointer_directly`, `return_ptr_to_ref`, `template_identity`, `test_template_inference_with_stack`. These tests failed before this patch under C++23.

Comment (usx95) [reply clang/test/Sema/warn-lifetime-safety-suggestions.cpp:4]: Oh I see. Thanks for the clarification.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp [hunk 2]
```diff
@@ -288,8 +288,7 @@ void FactsGenerator::VisitCastExpr(const CastExpr *CE) {
 
   switch (CE->getCastKind()) {
   case CK_LValueToRValue:
-    // TODO: Decide what to do for x-values here.
-    if (!SubExpr->isLValue())
+    if (!SubExpr->isGLValue())
```
Comment (usx95) [inline clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp:291]: Can you please verify that this does not introduce crashes while building LLVM with lifetime safety.

**Review by usx95 — APPROVED** [review]
LGTM. 

One request to run it on LLVM to verify no crashes.

File: clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp (hunk 2 above)
Comment (aeft) [reply clang/lib/Analysis/LifetimeSafety/FactsGenerator.cpp:291]: Done. No crashes were found.

**Comment by usx95** [comment]
Thanks for the confirmation. Will land this as it is now.
