### PR TITLE
[MIPS]Fix QNaNs in the MIPS legacy NaN encodings

### LINKED ISSUE #100495: MIPS: wrong qNaN encoding for r2 from IR
```
define dso_local float @f(float noundef %a, float noundef %b) local_unnamed_addr #0 {
entry:
  %0 = tail call float @llvm.minimum.f32(float %a, float %b)
  ret float %0
}
```

```
./bin/clang --target=mips-linux-gnu -march=mips32r2 -mnan=legacy zz.ll -S -O3
```

```
$CPI0_0:   
        .4byte  0x7fc00000                      # float NaN
```

### PR DESCRIPTION
**Pull request by anbbna**
The MSB of the mantissa should be zero for QNaNs in the MIPS legacy NaN encodings, and one for sNaNs.

Fix #100495

### CODE REVIEW

**Review by wzssyqa — APPROVED** [review]

File: llvm/lib/Target/Mips/MipsISelLowering.cpp [hunk 1]
```diff
@@ -467,6 +467,8 @@ MipsTargetLowering::MipsTargetLowering(const MipsTargetMachine &TM,
   setOperationAction(ISD::FMA,               MVT::f64,   Expand);
   setOperationAction(ISD::FREM,              MVT::f32,   Expand);
   setOperationAction(ISD::FREM,              MVT::f64,   Expand);
+  setOperationAction(ISD::ConstantFP, MVT::f32, Custom);
+  setOperationAction(ISD::ConstantFP, MVT::f64, Custom);
```
Comment (brad0) [inline llvm/lib/Target/Mips/MipsISelLowering.cpp:471]: These should line up like the entries above them.

Comment (anbbna) [reply llvm/lib/Target/Mips/MipsISelLowering.cpp:471]: OK, I'll amend that.
