### PR TITLE
[DAGCombiner] visitFREEZE: Early exit when N is deleted

### LINKED ISSUE #128143: [DAGCombiner] Assertion `Num < NumOperands && "Invalid child # of SDNode!"' failed.
Reproducer: https://godbolt.org/z/7aTdb9c5d
```
; bin/llc test.ll -o -
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@g_132 = external global [2 x [3 x i8]]
@g_200 = external global i8

define i64 @test(i1 %cmp24.i.i.i.i.i, i32 %0) {
entry:
  %cmp24.i.i.i.i.i2 = icmp ne ptr @g_132, @g_200
  %.fr.i.i.i.i.i = freeze ptr @g_132
  %1 = icmp ne ptr %.fr.i.i.i.i.i, @g_200
  %rem.i424.i.2.i.zext.i.i.i.i = zext i1 %1 to i32
  %or.cond20.i.i.1.i.i.i.i.i = select i1 %cmp24.i.i.i.i.i, i1 %cmp24.i.i.i.i.i2, i1 false
  %spec.select.i.i.1.i.i.i.i.i = select i1 %or.cond20.i.i.1.i.i.i.i.i, i32 0, i32 1
  %conv300.i.1.i.i.i.i.i = sext i32 %spec.select.i.i.1.i.i.i.i.i to i64
  %cmp3.i429.i.2.i.i.i.i.i = icmp ult i32 %0, %rem.i424.i.2.i.zext.i.i.i.i
  %or.cond20.i.i.2.i.i.i.i.i = select i1 %cmp24.i.i.i.i.i, i1 %cmp3.i429.i.2.i.i.i.i.i, i1 false
  %spec.select.i.i.2.i.i.i.i.i = select i1 %or.cond20.i.i.2.i.i.i.i.i, i32 0, i32 1
  %conv300.i.2.i.i.i.i.i = sext i32 %spec.select.i.i.2.i.i.i.i.i to i64
  %or301.i.2.i.i.i.i.i = or i64 %conv300.i.1.i.i.i.i.i, %conv300.i.2.i.i.i.i.i
  ret i64 %or301.i.2.i.i.i.i.i
}
```
```
llc: /root/llvm-project/llvm/include/llvm/CodeGen/SelectionDAGNodes.h:993: const llvm::SDValue& llvm::SDNode::getOperand(unsigned int) const: Assertion `Num < NumOperands && "Invalid child # of SDNode!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@test'
 #0 0x0000000003e76458 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3e76458)
 #1 0x0000000003e73e14 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x0000715c02a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x0000715c02a969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x0000715c02a42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x0000715c02a287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x0000715c02a2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x0000715c02a39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x00000000039e7fd3 (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x39e7fd3)
 #9 0x0000000003aa01d1 (anonymous namespace)::DAGCombiner::visitFREEZE(llvm::SDNode*) (.isra.0) DAGCombiner.cpp:0:0
#10 0x0000000003abcc7f (anonymous namespace)::DAGCombiner::visit(llvm::SDNode*) DAGCombiner.cpp:0:0
#11 0x0000000003abf3ac (anonymous namespace)::DAGCombiner::combine(llvm::SDNode*) DAGCombiner.cpp:0:0
#12 0x0000000003ac0c98 (anonymous namespace)::DAGCombiner::Run(llvm::CombineLevel) DAGCombiner.cpp:0:0
#13 0x0000000003ac35ab llvm::SelectionDAG::Combine(llvm::CombineLevel, llvm::BatchAAResults*, llvm::CodeGenOptLevel) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3ac35ab)
#14 0x0000000003c24ba9 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3c24ba9)
#15 0x0000000003c288d5 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3c288d5)
#16 0x0000000003c29b75 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3c29b75)
#17 0x0000000003c1a4ef llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x3c1a4ef)
#18 0x0000000002da289a llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#19 0x00000000033b772f llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x33b772f)
#20 0x00000000033b7ae1 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x33b7ae1)
#21 0x00000000033b8381 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x33b8381)
#22 0x00000000008c51b3 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#23 0x00000000007b4cde main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x7b4cde)
#24 0x0000715c02a29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#25 0x0000715c02a29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#26 0x00000000008bb995 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x8bb995)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```
llvm version: 3302bef5b41a99547f10b91d0aabe59aa3dc7fb0

### PR DESCRIPTION
**Pull request by dtcxzyw**
`N` may get merged with existing nodes inside the loop. Early exit when it is deleted to avoid the crash.
Alternative solution: use `DAGNodeDeletedListener` to refresh the value of N.

Closes https://github.com/llvm/llvm-project/issues/128143.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -16158,11 +16158,11 @@ SDValue DAGCombiner::visitFREEZE(SDNode *N) {
...
     }
-  }
 
-  // This node has been merged with another.
-  if (N->getOpcode() == ISD::DELETED_NODE)
-    return SDValue(N, 0);
+    // This node has been merged with another.
+    if (N->getOpcode() == ISD::DELETED_NODE)
+      return SDValue(N, 0);
+  }
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:16165]: Worth adding `assert(N->getOpcode() != ISD::DELETED_NODE && "????????");` here?

**Review by RKSimon — APPROVED** [review]
LGTM with one optional minor
