### PR TITLE
[WinEH] Emit state stores for SEH scopes

### LINKED ISSUE #90946: Destructors are not called during unwinding of SEH exceptions for Windows x86 binaries with `/EHa`
Building sample below with cl.exe (both x64 and x86) using `cl.exe /EHa a.cpp` yields the following expected output:

```
Destructor called
Exception thrown
```

Building it with clang-cl.exe for x86 using `clang-cl.exe -m32 /EHa a.cpp` yields the following output:

```
Destructor NOT called
Exception thrown
```

As one can see, the destructor is not being called when unwinding.
Note that compiling that sample using clang-cl for x64 works completely fine. This is only an issue with x86.

Another thing worth mentioning is that taking the code from `HandleDestructorCallWithException` and putting it directly within `CatchNativeExceptions` causes the x86 binary to crash, while x64 works fine.

The sample:

```C++
#include <cstdio>


struct Destructor {
  Destructor(bool* destructorCalled) : mDestructorCalled(destructorCalled) {}
  ~Destructor() { *mDestructorCalled = true; }
  bool* mDestructorCalled;
};


void HandleDestructorCallWithException(bool* destructorCalled)
{
  Destructor x(destructorCalled);
  *reinterpret_cast<int*>(1) = 1;
}


void CatchNativeExceptions(bool* destructorCalled, bool* exceptionThrown)
{
  try {
    HandleDestructorCallWithException(destructorCalled);
  }
  catch(...) {
    *exceptionThrown = true;
  }
}


int main()
{
  bool destructorCalled = false;
  bool exceptionThrown = false;

  CatchNativeExceptions(&destructorCalled, &exceptionThrown);

  puts(destructorCalled ? "Destructor called" : "Destructor NOT called");
  puts(exceptionThrown ? "Exception thrown" : "Exception NOT thrown");

  return destructorCalled && exceptionThrown ? 0 : 1;
}

```

### PR DESCRIPTION
**Pull request by momo5502**
At the moment Windows 32 bit SEH state stores are only emitted for throwing calls.

Windows 32 bit SEH state stores should also be emitted before SEH scope begin and before SEH scope end.
An invalid inline memory access would otherwise not trigger unwinding, in combination with /EHa.

This fixes #90946

### CODE REVIEW

**Comment by momo5502** [comment]
```C++
#include <cstdio>

struct Destructor {
  Destructor(int* destructorCalled) : mDestructorCalled(destructorCalled) {}
  ~Destructor() { ++*mDestructorCalled; }
  int* mDestructorCalled;
};

void HandleDestructorCallWithException(int* destructorCalled, bool _throw_1)
{
  {
  Destructor x(destructorCalled);

  if(_throw_1)
    *reinterpret_cast<int*>(1) = 1;

  }
  
  *reinterpret_cast<int*>(2) = 2;
}

void CatchNativeExceptions(int* destructorCalled, bool* exceptionThrown, bool _throw_1)
{
  try {
    HandleDestructorCallWithException(destructorCalled, _throw_1);
  }
  catch(...) {
    *exceptionThrown = true;
  }
}


int main()
{
  int destructorCalled = 0;
  bool exceptionThrown = false;

  CatchNativeExceptions(&destructorCalled, &exceptionThrown, true);

  printf("Destructor called %i times\n",destructorCalled );
  puts(exceptionThrown ? "Exception thrown" : "Exception NOT thrown");

  
  destructorCalled = 0;
  exceptionThrown = false;

  CatchNativeExceptions(&destructorCalled, &exceptionThrown, false);

  printf("Destructor called %i times\n",destructorCalled );
  puts(exceptionThrown ? "Exception thrown" : "Exception NOT thrown");

  return 0;
}
```

Output using cl: 

```
Destructor called 1 times
Exception thrown
Destructor called 1 times
Exception thrown
```

Output using clang-cl with the fix here:

```
Destructor called 1 times
Exception thrown
Destructor called 2 times
Exception thrown
```

--> state restore is still needed

**Comment by momo5502** [comment]
See issue #90946 for analysis details

File: llvm/lib/Target/X86/X86WinEHState.cpp [hunk 1]
```diff
@@ -653,7 +672,15 @@ void WinEHStatePass::addStateStores(Function &F, WinEHFuncInfo &FuncInfo) {
       InitialState = FinalState = ParentBaseState;
     for (Instruction &I : *BB) {
       auto *Call = dyn_cast<CallBase>(&I);
-      if (!Call || !isStateStoreNeeded(Personality, *Call))
+      if (!Call)
+        continue;
+
+      if (isSehScopeEnd(*Call)) {
```
Comment (rnk) [inline llvm/lib/Target/X86/X86WinEHState.cpp:678]: SEH scope ends are effectively non-throwing no-op pseudo instructions, so there should be no functional difference between inserting the store before or after the no-op. For simplicity, can we insert the state stores before the scope ends? That would make this a bit more uniform.

I haven't played around with the /EHa SEH scope codegen patterns since they were added, but it would be pretty reasonable for codegen to lower them to a direct branch, which after branch folding would get optimized out anyway.

Comment (momo5502) [reply llvm/lib/Target/X86/X86WinEHState.cpp]: I added the state store before the scope end. To do that, I added a condition to `getStateForCall` as unlike other invoke instructions, that reference the state of the unwind destination, this one should reference the state of the normal destination (as the unwind destination is the same as for SEH scope begin).

I also thought about adapting `calculateStateNumbersForInvokes` within `WinEHPrepare.cpp`, which fills the `InvokeStateMap`. However, I wasn't sure what is better, so I put the SEH scope end check into `getStateForCall`, as that would be the smallest change.

**Review by rnk — APPROVED** [review]
Thanks for the patch!
