### PR TITLE
[clang] Fix parenthesized list initialization of arrays not working with `new`

### LINKED ISSUE #68198: Bug with aggregate initialization with a parenthesized list of values
As of c++20, you can use a parenthesized list to initialize a dynamic array, but the following code
```
int test_it (void) {
    
    double *ptr;
    ptr=new double[](1,2,3);

    return 0;
}

int main(void) {
    return test_it();
}
```
Gives the error
```
paren.cpp:4:9: error: array 'new' cannot have initialization arguments
    4 |     ptr=new double[](1,2,3);
      |         ^            ~~~~~
1 error generated.
```
This was built on Ubuntu 22.04 using the main branch of llvm at time of reporting (75f295c2455131993f9c945320736b84c5fcf99c) with the -stdc++20 flag.
It builds successfully on up to date versions of GCC  (from 11.1)

### PR DESCRIPTION
**Pull request by alanzhao1**
This bug is caused by parenthesized list initialization not being implemented in `CodeGenFunction::EmitNewArrayInitializer(...)`.

Parenthesized list initialization of `struct`s  with `operator new` already works in Clang and is not affected by this bug.

Additionally, fix the test new-delete.cpp as it incorrectly assumes that using parentheses with operator new to initialize arrays is illegal for C++ versions >= C++17.

Fixes #68198

### CODE REVIEW

File: clang/lib/CodeGen/CGExprCXX.cpp [hunk 1]
```diff
@@ -1101,7 +1103,8 @@ void CodeGenFunction::EmitNewArrayInitializer(
     }
 
     CharUnits StartAlign = CurPtr.getAlignment();
-    for (unsigned i = 0, e = ILE->getNumInits(); i != e; ++i) {
+    ArrayRef<Expr *> InitExprs = ILE ? ILE->inits() : CPLIE->getInitExprs();
+    for (unsigned i = 0; i < InitExprs.size(); ++i) {
```
Comment (cor3ntin) [inline clang/lib/CodeGen/CGExprCXX.cpp:1107]: You could use a range for loop here

File: clang/lib/CodeGen/CGExprCXX.cpp [hunk 2]
```diff
@@ -1073,7 +1075,7 @@ void CodeGenFunction::EmitNewArrayInitializer(
       return;
     }
 
-    InitListElements = ILE->getNumInits();
+    InitListElements = ILE ? ILE->getNumInits() : CPLIE->getInitExprs().size();
```
Comment (cor3ntin) [inline clang/lib/CodeGen/CGExprCXX.cpp:1078]: This is not great, but I think it will do for now.
Maybe we want to have both CXXParenListInitExpr and  InitListExpr inherit from some abstract base class that implement some of the shared functionality with CRTP. We'd avoid all these if.

I don't think we need to do that in this patch though

**Review by cor3ntin — COMMENTED** [review]
Sema changes look okay.
I'd like @erichkeane to look at the codegen tests

**Comment by efriedma-quic** [comment]
Have you considered the following case?

```
  void foo() {
    char* arr = new char[]("asdf");
  }
```

**Comment by alanzhao1** [comment]
> Have you considered the following case?
> 
> ```
>   void foo() {
>     char* arr = new char[]("asdf");
>   }
> ```

Thanks for catching this - this causes this patch to crash. Working on this right now.

File: clang/lib/Sema/SemaInit.cpp [hunk 3]
```diff
@@ -5495,14 +5495,12 @@ static void TryOrBuildParenListInitialization(
         return;
     }
     //   ...and value-initialized for each k < i <= n;
-    if (ArrayLength > Args.size()) {
```
Comment (efriedma-quic) [inline clang/lib/Sema/SemaInit.cpp:5498]: What is this change supposed to do?

The existing code is intentionally trying to avoid creating an array filler if it won't be used (so, for example, the code will compile if the default constructor is deleted).

File: clang/lib/CodeGen/CGExprCXX.cpp [hunk 4]
```diff
@@ -1038,11 +1038,14 @@ void CodeGenFunction::EmitNewArrayInitializer(
     return true;
   };
 
+  const InitListExpr *ILE = dyn_cast<InitListExpr>(Init);
+  const CXXParenListInitExpr *CPLIE = dyn_cast<CXXParenListInitExpr>(Init);
+  const StringLiteral *SL = dyn_cast<StringLiteral>(Init);
   // If the initializer is an initializer list, first do the explicit elements.
-  if (const InitListExpr *ILE = dyn_cast<InitListExpr>(Init)) {
+  if (ILE || CPLIE || SL) {
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprCXX.cpp:1045]: This code is assuming the initializer for an array must be one of the following:

- An InitListExpr with a list of elements
- A CXXParentListInitExpr with a list of elements
- An InitListExpr with a "string" (isStringLiteralInit is true)
- A StringLiteral

Looking at the standard, I guess this is a complete list.

The last one seems a little suspect to me, though; if it's using the same IsStringInit() as InitListExpr does, a "string" might not be a StringLiteral.

File: clang/lib/Sema/SemaInit.cpp (hunk 3 above)
Comment (alanzhao1) [reply clang/lib/Sema/SemaInit.cpp:5498]: > What is this change supposed to do?

`CodeGenFunction::EmitNewArrayInitializer(...)` needs an array filler for dynamic-sized arrays - e.g.

```cpp
void foo(int n) {
  new int[n](1, 2);
}
```

> The existing code is intentionally trying to avoid creating an array filler if it won't be used (so, for example, the code will compile if the default constructor is deleted).

Thanks for pointing this out! There was no test for this case with a deleted constructor, so I'll have to create a separate PR to add one later.

In the meantime, I resolved this by adding `Entity.isVariableLengthArrayNew()` to the conditional here. This is also what we do in `InitListChecker` to detect this condition.

File: clang/lib/CodeGen/CGExprCXX.cpp (hunk 4 above)
Comment (alanzhao1) [reply clang/lib/CodeGen/CGExprCXX.cpp:1045]: This is parsed as a `StringLiteral` as shown in the AST.

`new-array.cc`:

```cpp
char* x = new char[]("asdf");
```

```
$ ./bin/clang -Xclang -ast-dump -std=c++20 ~/src/tests/new-array.cc

(irrelevant bits omitted)

|-VarDecl 0x557ce6fee8c0 </usr/local/google/home/ayzhao/src/tests/new-array.cc:1:1, col:28> col:7 x 'char *' cinit
| `-CXXNewExpr 0x557ce700cca0 <col:11, col:28> 'char *' array Function 0x557ce6fef0a0 'operator new[]' 'void *(unsigned long)'
|   |-IntegerLiteral 0x557ce700cc50 <col:15> 'unsigned long' 5
|   `-StringLiteral 0x557ce6feea00 <col:22> 'char[5]' "asdf"
```

**Comment by alanzhao1** [comment]
Ping. Any more comments?

File: clang/lib/CodeGen/CGExprCXX.cpp (hunk 4 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprCXX.cpp:1045]: Sure, but have you tried, for example, `char* x = new char[](__extension__ "asdf");`.  Or in objective-c++ mode, `char* x = new char[](@encode(int));`

Comment (alanzhao1) [reply clang/lib/CodeGen/CGExprCXX.cpp:1045]: Thanks again for catching these - they both cause crashes.

For the `__extension__` example, we have a `StringLiteral` wrapped in a `UnaryOperator`

```
|-VarDecl 0x561d5f1ba190 </usr/local/google/home/ayzhao/src/tests/extension.cc:1:1, col:42> col:7 x 'char *' cinit
| `-CXXNewExpr 0x561d5f1d8580 <col:11, col:42> 'char *' array Function 0x561d5f1ba990 'operator new[]' 'void *(unsigned long)'
|   |-IntegerLiteral 0x561d5f1d8530 <col:15> 'unsigned long' 5
|   `-UnaryOperator 0x561d5f1ba2f0 <col:22, col:36> 'char[5]' prefix '__extension__' cannot overflow
|     `-StringLiteral 0x561d5f1ba2d0 <col:36> 'char[5]' "asdf"
```

and for the Objective-C++ example, we have a `ObjCEncodeExpr`:

```
|-VarDecl 0x55b8a4d0a150 </usr/local/google/home/ayzhao/src/tests/encode.mii:1:1, col:34> col:7 x 'char *' cinit
| `-CXXNewExpr 0x55b8a4d2a560 <col:11, col:34> 'char *' array Function 0x55b8a4d0a940 'operator new[]' 'void *(unsigned long)'
|   |-IntegerLiteral 0x55b8a4d2a510 <col:15> 'unsigned long' 2
|   `-ObjCEncodeExpr 0x55b8a4d0a2a0 <col:22, col:33> 'char[2]' 'int'
```

Comment (alanzhao1) [reply clang/lib/CodeGen/CGExprCXX.cpp:1045]: OK, I've implemented a fix for this locally (but I haven't pushed my branch yet as I haven't written tests).

I'm running into a problem with the example:

```objc
char* x = new char[](@encode(int));
```

Clang produces the error:

```
$ bin/clang++ -c -o - -S -emit-llvm -std=c++20 ~/src/tests/encode.mii
/usr/local/google/home/ayzhao/src/tests/encode.mii:1:28: error: cannot compile this aggregate expression yet
    1 | const char* x = new char[](@encode(int));
      |                            ^~~~~~~~~~~~
1 error generated.
```

Clang emits the same error for a braced initialization-list:

```
$ bin/clang++ -c -o - -S -emit-llvm -std=c++20 ~/src/tests/encode.mii
/usr/local/google/home/ayzhao/src/tests/encode.mii:1:28: error: cannot compile this aggregate expression yet
    1 | const char* x = new char[]{@encode(int)};
      |                            ^~~~~~~~~~~~
1 error generated.
```

while GCC happily compiles both examples: https://godbolt.org/z/494x4ne5o

Given that braced initialization of a `ObjCEncodeExpr` is already broken in clang, I'm leaning towards maintaining the same behavior between clang's braced-initialization and parenthesized initialization here, but if others have any other ideas, I'm happy to hear them.

**Comment by cor3ntin** [comment]
@MitalAshok You want to review this?

File: clang/lib/CodeGen/CGExprCXX.cpp (hunk 2 above)
Comment (MitalAshok) [reply clang/lib/CodeGen/CGExprCXX.cpp:1091]:
```suggestion
    ArrayRef<const Expr *> InitExprs = ILE ? ILE->inits() : CPLIE->getInitExprs();
    InitListElements = InitExprs.size();
```

If you move this up from below it can look cleaner

File: clang/lib/CodeGen/CGExprCXX.cpp [hunk 5]
```diff
@@ -1561,16 +1577,21 @@ llvm::Value *CodeGenFunction::EmitCXXNewExpr(const CXXNewExpr *E) {
...
+  // If there is a brace-initializer or C++20 parenthesized initializer, cannot
+  // allocate fewer elements than inits.
   unsigned minElements = 0;
   if (E->isArray() && E->hasInitializer()) {
-    const InitListExpr *ILE = dyn_cast<InitListExpr>(E->getInitializer());
-    if (ILE && ILE->isStringLiteralInit())
+    const Expr *Init = E->getInitializer();
+    const InitListExpr *ILE = dyn_cast<InitListExpr>(Init);
+    const CXXParenListInitExpr *CPLIE = dyn_cast<CXXParenListInitExpr>(Init);
+    if ((ILE && ILE->isStringLiteralInit()) || isa<StringLiteral>(Init)) {
```
Comment (MitalAshok) [inline clang/lib/CodeGen/CGExprCXX.cpp:1587]: You forget to `IgnoreParenImpCasts` or check for `ObjCEncodeExpr`. Currently:

```c++
// seg fault
int n = 0; char* p = new char[n](("a"));

// throws bad_alloc (expected)
int n = 0; char* p = new char[n](("a"));
```

File: clang/lib/CodeGen/CGExprCXX.cpp (hunk 4 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprCXX.cpp]: That's fine.

**Review by efriedma-quic — APPROVED** [review]
LGTM

The logic in CGExprCXX.cpp is a bit more complicated than I'd like, but I don't see any obvious way to simplify it.
