### PR TITLE
[Clang][Sema] Disable checking invalid template id in initializer of primary variable template `std::format_kind` with libstdc++

### LINKED ISSUE #139067: [clang] fails to compile print("{}", 5s) when using libstdc++
This [fails to compile](https://godbolt.org/z/EWrMKdd3o) without adding libc++:

```cpp
#include <chrono>
#include <print>

int main() {
	using namespace std::chrono_literals;
	std::print("{}", 5s);
}
```

### PR DESCRIPTION
**Pull request by zwuis**
#134522 triggers compilation error with libstdc++, in which primary variable template `std::format_kind` is defined like

```cpp
template <typename R>
constexpr auto format_kind =
__primary_template_not_defined(
  format_kind<R>
);
```

See #139067 or <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120190>.

This PR disables checking template id in initializer of primary variable template `std::format_kind` in libstdc++ (by checking `__GLIBCXX__`).

Fixes #139067

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -4383,6 +4383,11 @@ Sema::CheckVarTemplateId(VarTemplateDecl *Template, SourceLocation TemplateLoc,
     };
 
     if (VarDecl *Var = Template->getTemplatedDecl();
+        // Skipping std::format_kind in libstdc++ is a hack for
+        // GH139067 / https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120190
+        !(Var->getName() == "format_kind" &&
+          Var->getDeclContext()->isStdNamespace() &&
+          PP.isMacroDefined("__GLIBCXX__")) &&
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:4390]: It would be great if we could find some sort of way to check the actual VERSION of the hack once they fix this, but it doesn't look like they have a fix in flight.

**Review by erichkeane — COMMENTED** [review]
Can you add a test for this too?

File: clang/lib/Sema/SemaTemplate.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplate.cpp:4390]: Clang you add something like `// HACK workaround libstdc++ 14.x (2025-02)` so it's easier to find?

**Review by shafik — COMMENTED** [review]
Can you please describe the issue in the summary instead of just saying it fixes .... Also add details such as this is fixing an issue introduced by ... 

Also please as Erich asked, add a test too

**Comment by zyn0217** [comment]
@cor3ntin @erichkeane I question if a hack is really necessary here. We had run into a similar situation when we broke libstdc++ 14.1 (#92439), and the consensus then was to wait for the next dot release. I'd expect they'll fix this issue in the next dot release too?

@jwakely Will the next GCC release come before Clang 21, i.e. before September?

**Comment by cor3ntin** [comment]
@zyn0217 At the very minimum, it breaks compiler explorer and anyone who uses trunk; it is disruptive

**Comment by cor3ntin** [comment]
I think we should
 - 1/ Land this patch as is
 - 2/ Extract the parsing of `__GLIBCXX__` in a separate function
 - 3/ have a function, probably in Preprocessor (so that it is available from Sema and Parser) such as `IsLibStdCxxBefore(_version_)` that let us do these checks uniformly and are easy to grep for. Ditto for libc++.

I don't have time at the moment but it would be a useful improvement :)

**Review by erichkeane — APPROVED** [review]

**Comment by cor3ntin** [comment]
@zwuis Can you land that? Thanks!

**Comment by zwuis** [comment]
@cor3ntin I don't have commit access. Please help me land this.

By the way, should I request commit access?

**Comment by cor3ntin** [comment]
> @cor3ntin I don't have commit access. Please help me land this.
> 
> By the way, should I request commit access?

It might be a good idea ! https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access
