### PR TITLE
[CodeGen] Support arrays with initializers of 64-bit size

### LINKED ISSUE #57353: Incorrect initialization of global arrays that are 2^32 bytes or larger
C programs with partially initialized arrays that are larger than 2^32 bytes aren't compiled correctly:
* `char` arrays get initialized entirely to zero, even if they have a non-zero initializer in the original source code
* when initializing arrays of other types, LLVM emits a `.space` or `.zero` directive with a negative byte count, which is rejected by the assembler.

```C
char bad_char[4294967296] = {1};
char ok_char[4294967295u] = {1};

int bad_int[1073741824] = {1};
int ok_int[1073741823] = {1};
```

Compiling this with `clang -S -arch x86_64 bad_static_arrays.c` produces:

```asm
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 10, 15	sdk_version 10, 15
	.globl	_bad_char               ## @bad_char
.zerofill __DATA,__common,_bad_char,4294967296,4
	.section	__DATA,__data
	.globl	_ok_char                ## @ok_char
	.p2align	4
_ok_char:
	.byte	1                       ## 0x1
	.space	4294967294

	.globl	_bad_int                ## @bad_int
	.p2align	4
_bad_int:
	.long	1                       ## 0x1
	.space	4294967292
	.space	-4294967296

	.globl	_ok_int                 ## @ok_int
	.p2align	4
_ok_int:
	.long	1                       ## 0x1
	.space	4294967288


.subsections_via_symbols

```

That's from compiling with Clang 11.0, but it looks like the issue exists in the most recent version too: https://godbolt.org/z/eobvhbf7s

### PR DESCRIPTION
**Pull request by MaskRay**
Based on @OfekShochat's https://reviews.llvm.org/D133648

init.c is the primary test for array initialization, but it uses a
32-bit triple, which would lead to an "array is too large" error. Add
the new test to array-init.c instead.

Fix #57353

### CODE REVIEW

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 1]
```diff
@@ -949,11 +949,11 @@ tryEmitGlobalCompoundLiteral(ConstantEmitter &emitter,
...
-                  llvm::Type *CommonElementType, unsigned ArrayBound,
+                  llvm::Type *CommonElementType, uint64_t ArrayBound,
                   SmallVectorImpl<llvm::Constant *> &Elements,
                   llvm::Constant *Filler) {
   // Figure out how long the initial prefix of non-zero elements is.
-  unsigned NonzeroLength = ArrayBound;
+  uint64_t NonzeroLength = ArrayBound;
   if (Elements.size() < NonzeroLength && Filler->isNullValue())
     NonzeroLength = Elements.size();
   if (NonzeroLength == Elements.size()) {
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprConstant.cpp:959]: Do we also need to fix the type of `TrailingZeroes`?

Comment (MaskRay) [reply clang/lib/CodeGen/CGExprConstant.cpp:959]: Thanks for catching this. Fixed and added a test.

**Review by efriedma-quic — APPROVED** [review]
LGTM
