### PR TITLE
[mlir][dataflow] Fix LivenessAnalysis/RemoveDeadValues handling of loop induction variables

### LINKED ISSUE #157934: [MLIR][RemoveDeadValues] RemoveDeadValues pass fails due to deleting loop induction variable.
Running `remove-dead-values` on the following IR produces the error below. The pass attempts to delete the loop induction variable because it is not used in the body but scf.for requires the block argument be present.

```mlir
func.func @dead_value_loop_ivs(%lb: index, %ub: index, %step: index, %b : i1) -> i1 {
  %loop_ret = scf.for %iv = %lb to %ub step %step iter_args(%iter = %b) -> (i1) {
    cf.assert %b, "loop not dead"
    scf.yield %b : i1
  }
  return %loop_ret : i1
}
```

```
/temp.mlir:2:15: error: 'scf.for' op different number of inits and region iter_args: 1 != 0
  %loop_ret = scf.for %iv = %lb to %ub step %step iter_args(%iter = %b) -> (i1) {
              ^
/temp.mlir:2:15: note: see current operation: 
%0 = "scf.for"(%arg0, %arg1, %arg2, %arg3) ({
^bb0(%arg4: i1):
  "cf.assert"(%arg3) <{msg = "loop not dead"}> : (i1) -> ()
  "scf.yield"(%arg3) : (i1) -> ()
}) : (index, index, index, i1) -> i1
```

### PR DESCRIPTION
**Pull request by linuxlonelyeagle**
Fix https://github.com/llvm/llvm-project/issues/157934. In liveness analysis, variables that are not analyzed are set as dead variables, but some variables are definitely live.

### CODE REVIEW

File: mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp [hunk 1]
```diff
@@ -309,15 +310,29 @@ RunLivenessAnalysis::RunLivenessAnalysis(Operation *op) {
              << " has no liveness info (unreachable), mark dead";
       solver.getOrCreateState<Liveness>(result.value());
     }
+    SmallVector<Value> mustLiveValues;
+    if (auto loopOp = dyn_cast<LoopLikeOpInterface>(op)) {
```
Comment (joker-eph) [inline mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp:314]: That seems very ad-hoc to me to look for this specific interface, seems like a workaround for something more important going on: likely that all entry-block arguments should be live, unless RegionBranchOpInterface could say they aren't.

Comment (joker-eph) [reply mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp]: I think you haven't understood what I'm saying: I'd like to see a fix that does not use any interface and treat the program in the most conservative way.

File: mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp [hunk 2]
```diff
@@ -165,6 +165,28 @@ void LivenessAnalysis::visitBranchOperand(OpOperand &operand) {
...
+        ValueRange regionInputs = successor.getSuccessorInputs();
+        for (auto argument : arguments) {
+          if (llvm::find(regionInputs, argument) == regionInputs.end()) {
+            (void)getLatticeElement(argument)->markLive();
+            LDBG() << "Marking RegionBranchOp's success argument live: "
+                   << argument;
+          }
+        }
+      }
+    }
```
Comment (joker-eph) [inline mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp]: Isn't this something where we should instead propagate the liveness of the result backward to the loop carried value instead of marking it unconditionally live?

File: mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp [hunk 3]
```diff
@@ -224,13 +244,20 @@ void LivenessAnalysis::visitBranchOperand(OpOperand &operand) {
     Liveness *operandLiveness = getLatticeElement(operand.get());
     LDBG() << "Marking branch operand live: " << operand.get();
     propagateIfChanged(operandLiveness, operandLiveness->markLive());
+    for (BlockArgument argument : argumentNotOperand) {
+      Liveness *argumentLiveness = getLatticeElement(argument);
+      LDBG() << "Marking RegionBranchOp's argument live: " << argument;
+      propagateIfChanged(argumentLiveness, argumentLiveness->markLive());
```
Comment (joker-eph) [inline mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp]: Do we agree that this is a conservative fix and in theory we should be able to remove %a in the example you posted above?
If so let's write a TODO:


```suggestion
      // TODO: this is overly conservative: we should be able to eliminate unused 
      // values in a RegionBranchOpInterface operation but that may requires removing
      // operation results which is beyond current capabilities of this pass right now.
      propagateIfChanged(argumentLiveness, argumentLiveness->markLive());
```

File: mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp [hunk 4]
```diff
@@ -309,6 +336,7 @@ RunLivenessAnalysis::RunLivenessAnalysis(Operation *op) {
              << " has no liveness info (unreachable), mark dead";
       solver.getOrCreateState<Liveness>(result.value());
     }
+
```
Comment (joker-eph) [inline mlir/lib/Analysis/DataFlow/LivenessAnalysis.cpp]:
```suggestion
```

Nit: unrelated change

**Review by joker-eph — APPROVED** [review]
That's conservative, but it's a bug fix so let's land it.

**Comment by linuxlonelyeagle** [comment]
> That's conservative, but it's a bug fix so let's land it.

Although it's a bug fix, strictly speaking it's my first pull request fixing data flow analysis, so it makes sense.I'm really glad to communicate with you—our conversations always leave me with gains.😘
