### PR TITLE
[clang-repl] [codegen] Reduce the state in TBAA. NFC for static compilation.

### LINKED ISSUE #95581: [clang-repl] Segfault on assignment when JIT compiling with -O1 or above
Hi folks. I've been working with @vgvassilev to identify an issue with Clang/LLVM 19. Currently running on Vassil's branch here: https://github.com/llvm/llvm-project/pull/94166

NOTE: This issue does not exist in LLVM 18 (1118c2e05e67a36ed8ca250524525cdb66a55256).

I have a minimal repro case shown below. It works with `-O0`, but crashes with `-O1` or higher.

## The C++ source
```cpp
struct box {
  box() = default;
  box(int *const data) : data{data} {}

  int *data{};
};

box foo() {
  box ret;
  /* The assignment here causes the crash. Using direct initialization works.
   * With -O0, this compiles and works. With -O1 or above, it dies. */
  ret = new int{};
  return ret;
}
```

## The repro steps
```
❯ ./build/bin/clang-repl -Xcc -O1
clang-repl> #include "foo.hpp"
Segmentation fault (core dumped)
```

## The backtrace
```
#0  0x0000555558b9e025 in clang::CodeGen::CodeGenTypes::ConvertRecordDeclType(clang::RecordDecl const*) ()
#1  0x0000555558b9ef2b in clang::CodeGen::CodeGenTypes::getCGRecordLayout(clang::RecordDecl const*) ()
#2  0x0000555558b9ab87 in clang::CodeGen::CodeGenTBAA::CollectFields(unsigned long, clang::QualType, llvm::SmallVectorImpl<llvm::MDBuilder::TBAAStructField>&, bool) ()
#3  0x0000555558b9b358 in clang::CodeGen::CodeGenTBAA::getTBAAStructInfo(clang::QualType) ()
#4  0x00005555589a6853 in clang::CodeGen::CodeGenFunction::EmitAggregateCopy(clang::CodeGen::LValue, clang::CodeGen::LValue, clang::QualType, clang::CodeGen::AggValueSlot::Overlap_t, bool) ()
#5  0x00005555589bc204 in clang::CodeGen::CodeGenFunction::EmitCXXMemberOrOperatorMemberCallExpr(clang::CallExpr const*, clang::CXXMethodDecl const*, clang::CodeGen::ReturnValueSlot, bool, clang::NestedNameSpecifier*, bool, clang::Expr const*) ()
#6  0x00005555589bd268 in clang::CodeGen::CodeGenFunction::EmitCXXOperatorMemberCallExpr(clang::CXXOperatorCallExpr const*, clang::CXXMethodDecl const*, clang::CodeGen::ReturnValueSlot) ()
#7  0x00005555589955bd in clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) ()
#8  0x0000555558995700 in clang::CodeGen::CodeGenFunction::EmitCallExprLValue(clang::CallExpr const*) ()
#9  0x000055555899597e in clang::CodeGen::CodeGenFunction::EmitLValueHelper(clang::Expr const*, clang::CodeGen::KnownNonNull_t) ()
#10 0x00005555589963d4 in clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*, clang::CodeGen::KnownNonNull_t) ()
#11 0x0000555558995d0d in clang::CodeGen::CodeGenFunction::EmitLValueHelper(clang::Expr const*, clang::CodeGen::KnownNonNull_t) ()
#12 0x0000555558994070 in clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) ()
#13 0x0000555558ab0d92 in clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) ()
#14 0x0000555558ab7ef9 in clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) ()
#15 0x0000555558b14cdc in clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) ()
#16 0x0000555558b2672f in clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) ()
#17 0x0000555558b6a44a in clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) ()
#18 0x0000555558b664bc in clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) ()
#19 0x0000555558b66d5b in clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) ()
#20 0x0000555558b6e1b7 in clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) [clone .part.0] ()
#21 0x0000555558896d81 in (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ()
#22 0x00005555588719e7 in clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) ()
#23 0x000055555834df3f in clang::IncrementalASTConsumer::HandleTopLevelDecl(clang::DeclGroupRef) ()
#24 0x0000555558351424 in clang::IncrementalParser::ParseOrWrapTopLevelDecl() ()
#25 0x000055555835225d in clang::IncrementalParser::Parse(llvm::StringRef) ()
#26 0x0000555558342568 in clang::Interpreter::ParseAndExecute(llvm::StringRef, clang::Value*) ()
#27 0x0000555556333495 in main ()
```

## Environment details
* OS: Ubuntu 24.04 (distrobox)
* LLVM commit: 0b3fc785ecb7b751ff67b7d972e033a95a45738f

### PR DESCRIPTION
**Pull request by vgvassilev**
In incremental compilation clang works with multiple `llvm::Module`s. Our current approach is to create a CodeGenModule entity for every new module request (via StartModule). However, some of the state such as the mangle context needs to be preserved to keep the original semantics in the ever-growing TU.

Fixes: llvm/llvm-project#95581.

cc: @jeaye

### CODE REVIEW

**Comment by fhahn** [comment]
Would it be possible to add a test case? Could you add a bit more detail how different mange contexts cause crashes in TBAA?

**Comment by vgvassilev** [comment]
> Would it be possible to add a test case?

Good point. Forgot to `git add` it. 

> Could you add a bit more detail how different mange contexts cause crashes in TBAA?

On a high level clang's CodeGen is designed to work with a single llvm::Module. However, incremental compilation assumes multiple llvm::Modules per each incremental input. We trick CodeGen by creating a new CodeGenModule for each input. However, CodeGen has various of places where it caches things. That is, for convenience we store a reference to the CodeGenModule (CGM), MangleContext (MContext) and others which points to memory that was destroyed in the multi-module setup.

This patch essentially reduces the state we have and decreases the chances to hit something that was gone. It still accesses the same objects via CodeGenTypes (CGTypes) but they are connected to the correct CodeGenModule and MangleContext.

The approach is fragile but that's the only way I could think of to support the multi-module setups without major refactorings of CodeGen. It has been reasonably reliable over the years but we hit things like that occasionally...

Does that make sense?

**Comment by jeaye** [comment]
Thanks, Vassil! I'm following up to confirm that this does fix the hard crash I was seeing. Really hoping we can get this merged.

**Comment by vgvassilev** [comment]
Hi @AaronBallman, could we move that forward?

**Comment by AaronBallman** [comment]
> Hi @AaronBallman, could we move that forward?

I've added the Clang codegen code owners, as they really should be involved in this sort of change.

**Comment by vgvassilev** [comment]
ping.

File: clang/lib/CodeGen/CodeGenTypes.h [hunk 1]
```diff
@@ -106,9 +101,9 @@ class CodeGenTypes {
   }
   CodeGenModule &getCGM() const { return CGM; }
   ASTContext &getContext() const { return Context; }
-  const ABIInfo &getABIInfo() const { return TheABIInfo; }
+  const ABIInfo &getABIInfo() const;
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CodeGenTypes.h:104]: Given almost all the callers of getABIInfo() are calling `CGM.getTypes().getABIInfo()`, we probably want to just move this helper to CodeGenModule.

Comment (vgvassilev) [reply clang/lib/CodeGen/CodeGenTypes.h]: Good point. I've addressed that. Thank you.

**Review by efriedma-quic — APPROVED** [review]
LGTM
