### PR TITLE
[clang][Tooling] Fix assertion failure when processing CUDA files

### LINKED ISSUE #173777: [Tooling][CUDA] Assertion `Actions.size() > 1' failed.
There are a lot of cases that will trigger this assertion failure:

(`empty.cu` is a empty file)

- `-E`:
`../build/bin/clang-check empty.cu -- --offload-arch=sm_70 -E`
- multi-arch device-only
`../build/bin/clang-check empty.cu -- --cuda-device-only --offload-arch=sm_70 --offload-arch=sm_80`
- `-M`:
`../build/bin/clang-check empty.cu -- --offload-arch=sm_70 -M`
- `-fsyntax-only`:
`../build/bin/clang-check empty.cu -- --offload-arch=sm_70 -fsyntax-only`

I also verify that this is a CUDA only problem.

Logs are basically the same:
```
clang-check: /home/mitchell/Documents/projects/llvm-project/clang/lib/Tooling/Tooling.cpp:111: bool ignoreExtraCC1Commands(const clang::driver::Compilation*): Assertion `Actions.size() > 1' failed.
 #0 0x0000560570e21709 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/mitchell/Documents/projects/llvm-project/build/bin/clang-check+0x2ff4709)
 #1 0x0000560570e1e984 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x00007f220383e4d0 (/usr/lib/libc.so.6+0x3e4d0)
 #3 0x00007f220389890c (/usr/lib/libc.so.6+0x9890c)
 #4 0x00007f220383e3a0 raise (/usr/lib/libc.so.6+0x3e3a0)
 #5 0x00007f220382557a abort (/usr/lib/libc.so.6+0x2557a)
 #6 0x00007f22038254e3 __assert_perror_fail (/usr/lib/libc.so.6+0x254e3)
 #7 0x000056056e640c78 clang::tooling::getCC1Arguments(clang::DiagnosticsEngine*, clang::driver::Compilation*) (.cold) Tooling.cpp:0:0
 #8 0x00005605711721fc clang::tooling::ToolInvocation::run() (/home/mitchell/Documents/projects/llvm-project/build/bin/clang-check+0x33451fc)
 #9 0x0000560571173d5a clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/home/mitchell/Documents/projects/llvm-project/build/bin/clang-check+0x3346d5a)
#10 0x000056056ea9f904 main (/home/mitchell/Documents/projects/llvm-project/build/bin/clang-check+0xc72904)
#11 0x00007f2203827635 (/usr/lib/libc.so.6+0x27635)
#12 0x00007f22038276e9 __libc_start_main (/usr/lib/libc.so.6+0x276e9)
#13 0x000056056ec11635 _start (/home/mitchell/Documents/projects/llvm-project/build/bin/clang-check+0xde4635)
```

### PR DESCRIPTION
**Pull request by zeyi2**
Running clang-tidy on CUDA files without specifying `--cuda-host-only` or `--cuda-device-only` would trigger an assertion failure in `Actions.size() > 1`, a related discussion: https://github.com/llvm/llvm-project/pull/173699#discussion_r2649279975.

This occurred because the Clang Driver generates a single top-level `OffloadAction` in `-fsyntax-only`, `-E`, `-M`. This commit removes the overly strict assertions.

Closes #173777

### CODE REVIEW

**Review by carlosgalvezp — CHANGES_REQUESTED** [review]
These asserts are here for a reason, they must not be removed.

Also, this is not a "clang-tidy" patch, it's a Clang patch and must be reviewed by Clang owners.

**Comment by zeyi2** [comment]
@AaronBallman Hi Aaron, could you take a look at this when you have time? I really want to land this before clang22 release :)

**Review by jhuber6 — COMMENTED** [review]
I'm not actually sure why this assertion is here, it contradicts my understanding of the OffloadAction. It's mainly used to combine actions so the driver can traverse the tree and propagate information. In the device-only case it will have dependencies for each architecture you passed, which is one if you only passed one.
```
            +- 0: input, "/dev/null", cuda, (device-cuda, sm_89)
         +- 1: preprocessor, {0}, cuda-cpp-output, (device-cuda, sm_89)
      +- 2: compiler, {1}, ir, (device-cuda, sm_89)
   +- 3: backend, {2}, assembler, (device-cuda, sm_89)
+- 4: assembler, {3}, object, (device-cuda, sm_89)
5: offload, "device-cuda (nvptx64-nvidia-cuda:sm_89)" {4}, none
```

From that it feels like this assertion is too strict, but I've never really worked with the tooling before so I don't know exactly what they were trying to test.

File: clang/lib/Tooling/Tooling.cpp [hunk 1]
```diff
@@ -108,13 +108,14 @@ static bool ignoreExtraCC1Commands(const driver::Compilation *Compilation) {
...
-            (isa<driver::BindArchAction>(Actions.front()) &&
-             isa<driver::CompileJobAction>(*Actions.front()->input_begin())));
+        if (Actions.size() > 1) {
+          assert(
+              isa<driver::CompileJobAction>(Actions.front()) ||
+              // On MacOSX real actions may end up being wrapped in
+              // BindArchAction.
+              (isa<driver::BindArchAction>(Actions.front()) &&
+               isa<driver::CompileJobAction>(*Actions.front()->input_begin())));
+        }
```
Comment (jhuber6) [inline clang/lib/Tooling/Tooling.cpp]: Is this even valid if we pass more than one architecture? We should have a test for `--offload-arch=sm_70,sm_80`

File: clang/unittests/Tooling/ToolingTest.cpp [hunk 2]
```diff
@@ -85,6 +85,13 @@ TEST(runToolOnCode, CudaSyntaxOnly) {
        "-nocudainc"}));
 }
 
+TEST(runToolOnCode, CudaMultipleArchs) {
+  EXPECT_TRUE(runToolOnCodeWithArgs(
+      std::make_unique<TestAction>(std::make_unique<clang::ASTConsumer>()), "",
+      {"-fsyntax-only", "-x", "cuda", "--offload-arch=sm_70,sm_80",
+       "-nocudalib", "-nocudainc"}));
```
Comment (jhuber6) [inline clang/unittests/Tooling/ToolingTest.cpp]: We should probably test both configurations, one architecture and multiple. They actrually have slightly different semantics because `-o` is forbidden with more than one.

Comment (jhuber6) [reply clang/unittests/Tooling/ToolingTest.cpp]: Oh, I think the github view only showed the change to that commit for some reason. Yeah this is fine.

**Review by jhuber6 — APPROVED** [review]
