### PR TITLE
[DirectX] Legalize `llvm.lifetime.*` intrinsics in EmbedDXILPass

### LINKED ISSUE #147395: [DirectX] `llvm.lifetime.start/.end` non-`i8*` pointers causing `Invalid record` validation error
## The problem

DXIL bitcode containing `llvm.lifetime.start/end` intrinsics emitted by Clang can fail to validate under the DXIL validator (dxv) due to error `Invalid record` located here: https://github.com/microsoft/DirectXShaderCompiler/blob/main/lib/Bitcode/Reader/BitcodeReader.cpp#L4722

Debugging the cause of the error with lldb, I have found that nullptr is being returned here:
https://github.com/microsoft/DirectXShaderCompiler/blob/a11702ef0a393a9e0b78f982f9f0fa66d919c867/lib/Bitcode/Reader/BitcodeReader.cpp#L836-L837
```c
    if (Ty && Ty != V->getType())
      return nullptr;
```
because `Ty` is `i8*` and `V->getType()` is not equal to `Ty`.

## Reproducing the problem

Sample shader that reproduces the problem:
```hlsl
// compile args: -E CSMain -T cs_6_6
uint2 Foo(uint2 a[2], uint i) {
  return a[i];
}
cbuffer Constants {
  uint2 arr[2];
}
RWStructuredBuffer<uint> output;
[numthreads(1, 1, 1)]
void CSMain(uint3 Tid : SV_DispatchThreadID) {
  output[0] = Foo(arr, Tid.x).x;
}
```

https://godbolt.org/z/haz47M8fz

Validation error:
```
Invalid record
Validation failed.
```

due to the lifetime intrinsic:
```llvm
 %1 = alloca [4 x i32], align 8
 call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %1), !dbg !100
```

The BitcodeReader expects `V->getType()` to be an `i8*`, but it is currently a `[4 x i32]*`.

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #147395

This PR:
- Excludes lifetime intrinsics from the Int64Ops shader flags analysis to match DXC behavior and pass DXIL validation.
- Performs legalization of `llvm.lifetime.*` intrinsics in the EmbedDXILPass just before invoking the DXILBitcodeWriter.
- After invoking the DXILBitcodeWriter, all lifetime intrinsics and associated bitcasts are removed from the module to keep the Module Verifier happy. This is fine since lifetime intrinsics are not needed by any passes after the EmbedDXILPass.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp [hunk 1]
```diff
@@ -70,8 +116,17 @@ class EmbedDXILPass : public llvm::ModulePass {
...
 
+    // Perform late legalization of lifetime intrinsics that would otherwise
+    // fail the Module Verifier if performed in an earlier pass
+    legalizeLifetimeIntrinsics(M);
+
     WriteDXILToFile(M, OS);
 
+    // We no longer need lifetime intrinsics after bitcode serialization, so we
+    // simply remove them to keep the Module Verifier happy after our
+    // not-so-legal legalizations
```
Comment (bob80905) [inline llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:127]: You might consider mentioning that any function containing a lifetime intrinsic gets entirely removed, rather than just the intrinsic instructions.

File: llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp [hunk 2]
```diff
@@ -52,6 +53,51 @@ class WriteDXILPass : public llvm::ModulePass {
...
+        LifetimeIntrinsic *LI = dyn_cast<LifetimeIntrinsic>(U);
+        assert(LI && "Expected user of lifetime intrinsic function to be "
+                     "a LifetimeIntrinsic instruction");
+        BitCastInst *BCI = dyn_cast<BitCastInst>(LI->getArgOperand(1));
+        assert(BCI && "Expected pointer operand of LifetimeIntrinsic to be a "
+                      "BitCastInst");
+        LI->eraseFromParent();
+        BCI->eraseFromParent();
+      }
+      F.eraseFromParent();
```
Comment (bob80905) [inline llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:97]: Why does the entire function get erased?

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:97]: It gets erased because the lifetime intrinsic's name is no longer mangled. Otherwise the pass will fail the module verifier with the message `Intrinsic name not mangled correctly for type arguments! Should be: llvm.lifetime.end.p0`

File: llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp (hunk 1 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:127]: It's only the lifetime intrinsic function declaration that is removed, no?

File: llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp (hunk 2 above)
Comment (bob80905) [reply llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:97]: Ah, for a second I thought you were erasing the function containing the user. This makes sense.

**Comment by bob80905** [comment]
Is it possible to add a test so that we see the lifetime intrinsics / bitcasts getting removed, along with the lifetime function declaration? Perhaps by using a CHECK-NOT?

File: llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp [hunk 3]
```diff
@@ -52,6 +53,51 @@ class WriteDXILPass : public llvm::ModulePass {
...
+                                            PtrTy, "", CI->getIterator());
+      CI->setArgOperand(1, NoOpBitCast);
+    }
+  }
+}
+
+static void removeLifetimeIntrinsics(Module &M) {
+  for (Function &F : make_early_inc_range(M))
+    if (Intrinsic::ID IID = F.getIntrinsicID();
+        IID == Intrinsic::lifetime_start || IID == Intrinsic::lifetime_end) {
```
Comment (llvm-beanz) [inline llvm/lib/Target/DirectX/DXILWriter/DXILWriterPass.cpp:86]: nit: I'd usually recommend inverting the condition and having a continue here instead of nesting further. That matches what you did above and aligns with the coding standards.

https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

**Review by llvm-beanz — COMMENTED** [review]
One small style nit, but otherwise LGTM.

**Review by llvm-beanz — APPROVED** [review]
