### PR TITLE
[libc] Make BigInt bit_cast-able to compatible types

### LINKED ISSUE #74258: `libc/src/__support/FPUtil/FPBits.h:111:14`: error: no matching function for call to `bit_cast`
I encountered the following error when trying to compile LLVM libc for baremetal riscv32 target:
```
/usr/local/google/home/phosek/llvm/llvm-project/build/baremetal/./bin/clang++ --target=riscv32-unknown-elf -DLIBC_NAMESPACE=__llvm_libc_18_0_0_git -D_DEBUG -D_FILE_OFFSET_BITS=64 -D_GLIBCXX_ASSERTIONS -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/local/google/home/phosek/llvm/llvm-project/libc -isystem /usr/local/google/home/phosek/llvm/llvm-project/build/baremetal/include
/riscv32-unknown-elf --target=riscv32-unknown-elf -march=rv32imafc -mabi=ilp32f -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstrin
g-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -ffunction-sections -fdata-sections -ffile-prefix-map=/usr/local/google/home/phosek/llvm/llvm-project/build/baremetal/runtimes/runtimes-riscv32-unknown-elf-bins=../../../../ -ffile-prefix-map=/usr/local/google/home/phosek/llvm/llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=gnu++17 --target=riscv32-unknown-elf -O2 -fpie -ffreestanding -fno-builtin -f
no-exceptions -fno-lax-vector-conversions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -Wall -Wextra -Wconversion -Wno-sign-conversion -Wimplicit-fallthrough -Wwrite-strings -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wstrict-prototypes -Wthread-safety -Wglobal-constructors -DLIBC_COPT_PUBLIC_PACKAGING -UNDEBUG -MD -MT libc/src/math/generic/CMakeFiles/libc.src.math.generic.fabsl.dir/fabsl.
cpp.obj -MF libc/src/math/generic/CMakeFiles/libc.src.math.generic.fabsl.dir/fabsl.cpp.obj.d -o libc/src/math/generic/CMakeFiles/libc.src.math.generic.fabsl.dir/fabsl.cpp.obj -c /usr/local/google/home/phosek/llvm/llvm-project/libc/src/math/generic/fabsl.cpp                                                                                                                                                                         
In file included from /usr/local/google/home/phosek/llvm/llvm-project/libc/src/math/generic/fabsl.cpp:10:                                                                                                            
In file included from /usr/local/google/home/phosek/llvm/llvm-project/libc/src/__support/FPUtil/BasicOperations.h:12:                                                                                                                                                                                                                                                                                                                     
/usr/local/google/home/phosek/llvm/llvm-project/libc/src/__support/FPUtil/FPBits.h:111:14: error: no matching function for call to 'bit_cast'                                                                        
  111 |       : bits(cpp::bit_cast<UIntType>(x)) {}                                                       
      |              ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                                              
/usr/local/google/home/phosek/llvm/llvm-project/libc/src/__support/FPUtil/BasicOperations.h:22:13: note: in instantiation of function template specialization '__llvm_libc_18_0_0_git::fputil::FPBits<long double>::FPBits<long double, 0>' requested here                                                                                                                                                                                
   22 |   FPBits<T> bits(x);                                                                              
      |             ^                                                                                     
/usr/local/google/home/phosek/llvm/llvm-project/libc/src/math/generic/fabsl.cpp:16:18: note: in instantiation of function template specialization '__llvm_libc_18_0_0_git::fputil::abs<long double, 0>' requested here                                                                                                                                                                                                                    
   16 |   return fputil::abs(x);                                                                                                                                                                                     
      |                  ^                                                                                                                                                                                           
/usr/local/google/home/phosek/llvm/llvm-project/libc/src/__support/CPP/bit.h:36:26: note: candidate template ignored: substitution failure [with To = UIntType, From = long double, $2 = cpp::enable_if_t<sizeof(UIntType) == sizeof(long double)>]: implicit instantiation of undefined template '__llvm_libc_18_0_0_git::cpp::enable_if<false>'                                                                                         
   36 | LIBC_INLINE constexpr To bit_cast(const From &from) {                                                                                                                                                        
      |                          ^                                                                                                                                                                                                                                                                                                                                                                                                        
1 error generated.
```

### PR DESCRIPTION
**Pull request by gchatelet**
This is a second take on #74837 to fix #74258

### CODE REVIEW

**Comment by gchatelet** [comment]
Contrary to #74837 this patch does not try to make the type `bit_cast`-able directly but adds `bit_cast` implementations that know how to interact with the type.

**Comment by gchatelet** [comment]
@michaelrj-google @lntue @petrhosek 

Now even with this patch in, when we disable native support for 128 bit uint types in
https://github.com/llvm/llvm-project/blob/a9adcef45011f95ab54e7e40983da7cf9e14a08a/libc/src/__support/UInt128.h#L14-L20
and use `UInt128 = cpp::UInt<128>`, we have the following error:
```
[ RUN      ] LlvmLibcStrToLDTest.SimpleTest
external/llvm-project/libc/test/src/stdlib/strtold_test.cpp:90: FAILURE
      Expected: actual_fp.bits
      Which is: 0x7fffc000000000000000
To be equal to: expected_fp.bits
      Which is: 0x4005f600000000000000
external/llvm-project/libc/test/src/stdlib/strtold_test.cpp:92: FAILURE
      Expected: actual_fp.get_exponent()
      Which is: 16384
To be equal to: expected_fp.get_exponent()
      Which is: 6
external/llvm-project/libc/test/src/stdlib/strtold_test.cpp:93: FAILURE
      Expected: actual_fp.get_mantissa()
      Which is: 0x4000000000000000
To be equal to: expected_fp.get_mantissa()
      Which is: 0x7600000000000000
[  FAILED  ] LlvmLibcStrToLDTest.SimpleTest
```

I tried to trace it down but it feels like an issue with the `BigInt` implementation. `strtold` seems to exercise paths where `BigInt` does not quite have the same semantics as `__uint128_t`.

File: libc/src/__support/CPP/bit.h [hunk 1]
```diff
@@ -25,6 +25,27 @@ namespace LIBC_NAMESPACE::cpp {
 #define LLVM_LIBC_HAS_BUILTIN_MEMCPY_INLINE
 #endif
 
+// Performs a copy from 'src' to 'dst' of 'size' bytes.
+// The semantics is valid if 'src' and 'dst' are equal but undefined if the
```
Comment (michaelrj-google) [inline libc/src/__support/CPP/bit.h:29]: nit: semantics are valid

File: libc/src/__support/CPP/bit.h [hunk 2]
```diff
@@ -25,6 +25,27 @@ namespace LIBC_NAMESPACE::cpp {
...
+// regions defined by [src, src + size] and [dst, dst + size] overlap.
+template <size_t size, typename DstT, typename SrcT>
+LIBC_INLINE constexpr void memcpy_inline(DstT *__restrict dst,
```
Comment (michaelrj-google) [inline libc/src/__support/CPP/bit.h:32]: is this function intended to be available for general internal use? If not, should it be in an `internal` namespace?

**Review by michaelrj-google — COMMENTED** [review]
This looks fine to me, though I'd say wait for other reviewers to approve.

File: libc/src/__support/CPP/bit.h (hunk 2 above)
Comment (gchatelet) [reply libc/src/__support/CPP/bit.h:32]: We definitely need this function to implement the `memcpy` function. It was previously only defined in `libc/src/string/memory_utils/utils.h` but it's needed elsewhere now so I made it globally available in this header. It might not be the best place for it especially since it's not an official std function but I don't have a good home for it now. Do you have a suggestion? We can also leave it here, I don't think it hurts.

File: libc/src/__support/UInt.h [hunk 3]
```diff
@@ -952,6 +952,35 @@ struct make_signed<UInt<Bits>> : type_identity<Int<Bits>> {
...
+namespace internal {
+template <typename T> struct is_custom_uint : cpp::false_type {};
+template <size_t Bits> struct is_custom_uint<UInt<Bits>> : cpp::true_type {};
+} // namespace internal
+
+// bit_cast to UInt
+template <typename To, typename From,
+          typename = cpp::enable_if_t<internal::is_custom_uint<To>::value>,
+          typename = cpp::enable_if_t<sizeof(To) == sizeof(From)>,
+          typename = cpp::enable_if_t<cpp::is_trivially_copyable<From>::value>>
```
Comment (lntue) [inline libc/src/__support/UInt.h:964]: Why using separate template parameters for the conditions instead of logically combining in just one `enable_if_t`?

Comment (gchatelet) [reply libc/src/__support/UInt.h:964]: For consistency with the original implementation
https://github.com/llvm/llvm-project/blob/41096d19ab07650747a434345842a9e55fa972d7/libc/src/__support/CPP/bit.h#L28-L36

Now we could also pack everything in a single condition for both implementations at the _cost_ of explicitly picking up a different type for `std::enable_if` (otherwise they would both resolve to `template <typename To, typename From, void>` and compiler would complain it can't choose between the two).

Comment (gchatelet) [reply libc/src/__support/UInt.h:964]: As discussed with @legrosbuffle the list of `typename`s is surprising so I'll change it to a single `enable_if_t` with a conjunction. I'll add a tag for the specialization so the signatures differ.

Comment (gchatelet) [reply libc/src/__support/UInt.h]: So this was not possible to use a single `typename` for function discrimination. I added an extended explanation. Let me know if it works for you.

File: libc/src/__support/UInt.h [hunk 4]
```diff
@@ -952,6 +952,49 @@ struct make_signed<UInt<Bits>> : type_identity<Int<Bits>> {
...
+// bit_cast from UInt
+template <
+    typename To, size_t Bits,
+    typename = cpp::enable_if_t<sizeof(To) == sizeof(UInt<Bits>) &&
+                                cpp::is_trivially_constructible<To>::value &&
+                                cpp::is_trivially_copyable<To>::value &&
+                                cpp::is_trivially_copyable<UInt<Bits>>::value>>
+LIBC_INLINE constexpr To bit_cast(const UInt<Bits> &from) {
+  To out;
+  cpp::memcpy_inline<sizeof(out)>(&out, from.val);
```
Comment (legrosbuffle) [inline libc/src/__support/UInt.h:994]: Why no `return bit_cast<To>(from.val);` ?

File: libc/src/__support/UInt.h [hunk 5]
```diff
@@ -952,6 +952,49 @@ struct make_signed<UInt<Bits>> : type_identity<Int<Bits>> {
...
+// redeclaration of the same function leading to "error: template parameter
+// redefines default argument".
+template <typename To, typename From,
+          typename = cpp::enable_if_t<sizeof(To) == sizeof(From) &&
+                                      cpp::is_trivially_copyable<To>::value &&
+                                      cpp::is_trivially_copyable<From>::value>,
+          typename = cpp::enable_if_t<internal::is_custom_uint<To>::value>>
+LIBC_INLINE constexpr To bit_cast(const From &from) {
+  To out;
+  cpp::memcpy_inline<sizeof(out)>(out.val, &from);
```
Comment (legrosbuffle) [inline libc/src/__support/UInt.h:981]: I would suggest changing `BigInt` to make the storage a value type rather than an array type:

```
template <size_t Bits, bool Signed>
struct BigInt {
    struct Storage {
      uint64_t words[WORDCOUNT];
    };

    Storage val{};
};
```

Then all storage manipulations can be done with value semantics.

In particular this can be written `out.val = bit_cast<Storage>(from);`

Comment (gchatelet) [reply libc/src/__support/UInt.h]: That makes a lot of sense. Thx for the suggestion.

File: libc/src/__support/CPP/bit.h (hunk 2 above)
Comment (gchatelet) [reply libc/src/__support/CPP/bit.h:32]: With @legrosbuffle https://github.com/llvm/llvm-project/pull/75063#discussion_r1432534464 I think we can do away with this and put the function back into `libc/src/string/memory_utils/utils.h`.

**Review by legrosbuffle — APPROVED** [review]

**Review by lntue — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]

**Review by legrosbuffle — APPROVED** [review]
