### PR TITLE
[Clang] Remove unnecessary Decl transform & profiles for SizeOfPackExpr

### LINKED ISSUE #124161: Clang frontend bug report
# Error Logs

[buf-f965e1.sh](https://github.com/user-attachments/files/18524598/buf-f965e1.sh.txt)
[buf-f965e1.hh](https://github.com/user-attachments/files/18524599/buf-f965e1.hh.txt)
[buf-f965e1.reduced.hh](https://github.com/user-attachments/files/18524601/buf-f965e1.reduced.hh.txt)
[stack-dump-f965e1.txt](https://github.com/user-attachments/files/18524595/stack-dump-f965e1.txt)

[buf-c54075.sh](https://github.com/user-attachments/files/18524600/buf-c54075.sh.txt)
[buf-c54075.hh](https://github.com/user-attachments/files/18524596/buf-c54075.hh.txt)
[stack-dump-c54075.txt](https://github.com/user-attachments/files/18524597/stack-dump-c54075.txt)

# Source Code

[unreachable.hpp](https://github.com/user-attachments/files/18524568/unreachable.hpp.txt)
[throw.hpp](https://github.com/user-attachments/files/18524564/throw.hpp.txt)
[MCSL_MSG_LOCALIZATION.hpp](https://github.com/user-attachments/files/18524566/MCSL_MSG_LOCALIZATION.hpp.txt)
[MCSL.hpp](https://github.com/user-attachments/files/18524563/MCSL.hpp.txt)
[contig_base.hpp](https://github.com/user-attachments/files/18524562/contig_base.hpp.txt)
[concepts.hpp](https://github.com/user-attachments/files/18524565/concepts.hpp.txt)
[buf.hpp](https://github.com/user-attachments/files/18524560/buf.hpp.txt)
[assert.hpp](https://github.com/user-attachments/files/18524567/assert.hpp.txt)
[alloc.hpp](https://github.com/user-attachments/files/18524561/alloc.hpp.txt)
[alloc.cpp](https://github.com/user-attachments/files/18524559/alloc.cpp.txt)

# PS

I acquired clang through the apt package manager.
creduce appears to have done nothing because of the gnu-style line directives in the preprocessed file that clang told me to include.

### PR DESCRIPTION
**Pull request by zyn0217**
We used to always transform the pattern declaration for SizeOfPackExpr to ensure the constraint expression's profile produced the desired result. However, this approach failed to handle pack expansions when the pack referred to function parameters. In such cases, the function parameters were formerly expanded to 1 to avoid building Subst* nodes (see e6974daa7). That workaround caused us to transform a pack without a proper ArgumentPackSubstitutionIndex, leading to crashes when transforming the pattern.

It turns out that profiling the pattern for partially substituted SizeOfPackExprs is unnecessary because their transformed forms are also profiled within the partial arguments.

(No release note because this is actually a trunk regression)

Fixes https://github.com/llvm/llvm-project/issues/124161

### CODE REVIEW

File: clang/test/SemaTemplate/concepts-out-of-line-def.cpp [hunk 1]
```diff
@@ -720,6 +720,34 @@ template <typename... Ts> struct d {
 template struct c<int>;
 template struct d<int, int>;
 
+namespace Regression_123441 {
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/concepts-out-of-line-def.cpp:723]:
```suggestion
namespace GH123441 {
```

File: clang/test/SemaTemplate/concepts-out-of-line-def.cpp [hunk 2]
```diff
@@ -720,6 +720,34 @@ template <typename... Ts> struct d {
...
+
+template <class... T>
+constexpr foo<T...>::foo(auto&&... initList) // expected-error {{does not match any declaration}}
+  requires (sizeof...(T) <= 8) {}
+
+}
+
 } // namespace GH115098
 
 namespace GH114685 {
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/concepts-out-of-line-def.cpp:753]: Did you meant to be nested in another namespace ?

**Review by cor3ntin — APPROVED** [review]
LGTM except for nits

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks!

**Review by shafik — COMMENTED** [review]
In my comment here, it really looks like a clang-17 regression: https://github.com/llvm/llvm-project/issues/124161#event-16079402729

From what I can tell you also address the simplified version, so I believe a release note is probably warrented.

Are there really multiple bugs here?

**Comment by AaronBallman** [comment]
> In my comment here, it really looks like a clang-17 regression: [#124161 (comment)](https://github.com/llvm/llvm-project/issues/124161#event-16079402729)
> 
> From what I can tell you also address the simplified version, so I believe a release note is probably warrented.
> 
> Are there really multiple bugs here?

Yeah, this does appear to be a regression and so it warrants a release note. Reminder: please be sure to check back on issues to make sure we're addressing all of the comments (sometimes new information comes up in comments that's not reflected in the issue summary).

**Comment by zyn0217** [comment]
@shafik @AaronBallman Here is the complete backstory:

We were not performing well in out-of-line concept comparison, especially for expressions involving packs. I tried to address these issues around commit 04d20b170, but it quickly became evident that the fix was insufficient for https://github.com/llvm/llvm-project/issues/101735. To resolve that, we harnessed a feature that TreeTransform would expand function parameters if the parameters were instantiated as a pack, rather than keeping them in non-expanded forms.

That solution (developed during the 20 cycle and backported to 19) worked but introduced a pitfall: if we needed to transform a pack declaration within an expression, we would also need a valid ArgumentPackSubstitutionIndex to expand the pack.

Shortly after, I addressed #93099 (also during the 20 development cycle), where a SizeOfPackExpr was improperly profiled for constraint comparison due to its declaration being non-transformed. To that end, I added a declaration transformation step when normalizing constraints. Combined with the previously mentioned pitfall, this again crashed #124161 since no ArgumentPackSubstitutionIndex was set.

Technically, this should have worked at some point, as @shafik observed, which I believe was prior to the fix for #93099. And as far as I can tell, the latest crash was introduced by the fix for #93099, so I didn’t add a release note as usual.

**Comment by AaronBallman** [comment]
Thank you for the explanation, that makes more sense to me.
