### PR TITLE
[clang-doc] fix names of conversions for template parameters

### LINKED ISSUE #59812: [clang-doc] template operator T() produces a bad name
This operator:
```cpp
  template <SignedPrimitiveInteger U>
    requires(::sus::mem::size_of<U>() >= ::sus::mem::size_of<PrimitiveT>())
  constexpr inline explicit operator U() const {
    return primitive_value;
  }              
```
Produces this docs:
```
operator type-parameter-0-0
public U operator type-parameter-0-0()

```
Which could be greatly improved by just saying "conversion operator to type U. But should also include the concept SignedPrimitiveInteger as the conversion is only valid to a matching type.

### PR DESCRIPTION
**Pull request by evelez7**
Fixes #59812

The names of conversion functions of template type parameters were being emitted as "type-parameter-N-M". Now we check if the conversion type is a TemplateTypeParmType and reconstruct the source name.

### CODE REVIEW

**Comment by evelez7** [comment]
Should note that #59812 also mentions the `requires` clause being omitted but that should be addressed by a different issue/patch because that will be applicable to all function types.

File: clang-tools-extra/clang-doc/Serialize.cpp [hunk 1]
```diff
@@ -525,7 +525,13 @@ template <typename T>
 static void populateInfo(Info &I, const T *D, const FullComment *C,
                          bool &IsInAnonymousNamespace) {
   I.USR = getUSRForDecl(D);
-  I.Name = D->getNameAsString();
+  auto ConversionDecl = dyn_cast_or_null<CXXConversionDecl>(D);
+  if (ConversionDecl && ConversionDecl->getConversionType()
+                            .getTypePtr()
+                            ->isTemplateTypeParmType())
```
Comment (ilovepi) [inline clang-tools-extra/clang-doc/Serialize.cpp:531]:
```suggestion
  if(auto ConversionDecl = dyn_cast_or_null<CXXConversionDecl>(D); ConversionDecl && ConversionDecl->getConversionType()
                            .getTypePtr()
                            ->isTemplateTypeParmType())
```
I think you can rewrite this as a single conditional. https://godbolt.org/z/b46c96ccr

**Review by ilovepi — CHANGES_REQUESTED** [review]
I think this needs a test before it can land.

**Review by ilovepi — APPROVED** [review]
LGTM, but would you mind pre-committing the test so its easy to see what's changing in the output with this patch? I've been trying to get more of that done when we're changing clang-doc output. Otherwise it's hard to know exactly what we're achieving with a particular patch. I can rubber stamp the pre-commit patch.

**Comment by evelez7** [comment]
> would you mind pre-committing the test so its easy to see what's changing in the output with this patch?

Could you explain what this means please? Do you mean reorganizing the PR so that the first commit is the test and then the second is the code change?

**Comment by ilovepi** [comment]
Sorry, I mean committing a test w/ the current in-tree behavior, and then this patch would have your fix and a small delta to the test showing the new behavior. Some information on that can be found here: https://llvm.org/docs/TestingGuide.html#precommit-workflow-for-tests

**Comment by ilovepi** [comment]
You can find a stack where I did that here: https://app.graphite.dev/github/pr/llvm/llvm-project/135705/%5Bllvm%5D%5Blto%5D-Precommit-test-for-libcall-internalization

Those aren't landed, since we're hashing out the proper way to fix things, but I added a test w/ the behavior today, and then in the next patch its very easy to see what changed.

**Comment by evelez7** [comment]
Opened #141168. I'll make the test changes once that's in.

I can see why Graphite would be useful to learn. Makes me miss Phabricator a bit. 🥲

**Comment by ilovepi** [comment]
stacked PRs are still not as nice as phabricator or gerrit, but Graphite is a lot more firendly than I found spr, or winging it w/ github PRs. For a precommit test, it isn't too hard to upload a patch for before and then rebase the "after" patch after it lands.
