### PR TITLE
[Clang] Fix missed initializer instantiation bug for variable templates

### LINKED ISSUE #135032: [clang] Crash instantiating static variable template specialization member of class template
The following program crashes during codegen, and looks to have done so since Clang 9.

```cpp
template <typename>
struct TCls {
  template <typename T>
  static auto var = T::smem;
};

struct S { static constexpr int smem = 1; };

int main() {
  (void) TCls<int>::var<S>;
}

```

https://godbolt.org/z/x9eYMKfrv

### PR DESCRIPTION
**Pull request by dty2**
Try to fix missing initializer for inline static template member with auto caused by delayed template instantiation.

Bug Fix: [Bug 135032](https://github.com/llvm/llvm-project/issues/135032)
Problem Description:
Due to nested templates, when instantiating the outer layer (the template class), the inner layer (the template variable) uses delayed instantiation.
This causes the declaration (VarDecl) of the template variable to retain the type from the original template declaration (i.e., auto), and it loses the initializer.
Later, when instantiating the template variable, its VarTemplateSpecializationDecl type depends on the VarDecl type.
Thus, the VarTemplateSpecializationDecl also has no initializer, and its type remains auto.
Ultimately, when building the reference expression in Sema::BuildDeclarationNameExpr, the expression's type is auto and stays as auto until code generation, triggering llvm_unreachable in CodeGenTypes::ConvertType.

Reproduction Steps:
Test Code:
``` cxx
template <typename T> struct B {
  template <typename G> inline static auto var = 5;
};

int main() {
  int bb = B<int>::var<int>;
  return 0;
}
```
GDB Breakpoints for Debugging:
Annotations like #(1) mark the call order in a tree structure. For example, two #(3) entries mean Sema::CheckVarTemplateId calls Sema::BuildDeclarationNameExpr after its own execution.
``` gdb
#(1)
b Sema::BuildTemplateIdExpr
#(2)
b Sema::CheckVarTemplateId
#(3)
b Sema::CheckVarTemplateId
#(4)
b Sema::BuildVarTemplateInstantiation
#(5)
b TemplateDeclInstantiator::VisitVarTemplateSpecializationDecl
#(6)
b VarTemplateSpecializationDecl::Create
#(7)
b VarTemplateSpecializationDecl::VarTemplateSpecializationDecl
#(8)
b VarDecl::VarDecl
#(6)
b Sema::BuildVariableInstantiation
#(7)
b Sema::InstantiateVariableInitializer
#(3)
b Sema::BuildDeclarationNameExpr
#(4)
b Sema::BuildDeclRefExpr
```
Key Observations:
While debugging, I generated the AST for the test code and noticed a contradiction:

The AST shows VarTemplateSpecializationDecl as int (correct), but GDB reveals its type is actually auto during execution.

Example from AST:

DeclRefExpr 0x598f651f5a60 <col:9, col:27> 'auto' lvalue VarTemplateSpecialization 0x598f651f5980 'var' 'int' (VarTemplate 0x598f651d1938 'var')
The DeclRefExpr has type auto, while its referenced VarTemplateSpecialization claims to be int—a clear inconsistency.

Solution:
Since I noticed that the deduction of auto type is caused by the initializer
I plan to do special processing for template variables of type auto, that is, to prevent their delayed instantiation
so that their initializers will not be lost when the outer template class is instantiated

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -6027,8 +6027,15 @@ void Sema::BuildVariableInstantiation(
   Context.setManglingNumber(NewVar, Context.getManglingNumber(OldVar));
   Context.setStaticLocalNumber(NewVar, Context.getStaticLocalNumber(OldVar));
 
+  bool VarTemplateWithAutoType = false;
+  QualType VarSourceType = OldVar->getTypeSourceInfo()->getType();
+  if (VarSourceType->getAs<AutoType>()) {
+    VarTemplateWithAutoType = true;
+  }
+
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6035]:
```suggestion
  bool VarTemplateWithAutoType = OldVar->getTypeSourceInfo()->getType()->getAs<AutoType>();
```

Can we avoid getTypeSourceInfo?

**Comment by zyn0217** [comment]
Also, can you help me test if this fixes https://github.com/llvm/llvm-project/issues/134526? Thanks

**Comment by dty2** [comment]
> Also, can you help me test if this fixes #134526? Thanks

sure, no problem.

**Comment by dty2** [comment]
@zyn0217

**Comment by dty2** [comment]
@zyn0217 
I can compile it successfuly, and the output is 1.

``` cxx
#include <iostream>
template <class T>
struct S {
  template <class U> static const auto var = T();
  template <class U> static const auto foo = var<T>;
};

int main() {
  const int p = S<int>::var<int> + S<int>::foo<int> + 1;
  std::cout << p;
  return 0;
}
```

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 2]
```diff
@@ -6027,8 +6027,15 @@ void Sema::BuildVariableInstantiation(
   Context.setManglingNumber(NewVar, Context.getManglingNumber(OldVar));
   Context.setStaticLocalNumber(NewVar, Context.getStaticLocalNumber(OldVar));
 
+  bool VarTemplateWithAutoType = false;
+  QualType VarSourceType = OldVar->getTypeSourceInfo()->getType();
+  if (VarSourceType->getAs<AutoType>()) {
```
Comment (zwuis) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6032]: Can we use `->isUndeducedType()` to handle this case
```cpp
template <typename T> struct S { S(T); };
template <typename T> struct B { 
   template <typename G> inline static S var = 5; 
 };
```
?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 1 above)
Comment (dty2) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6035]: Your suggestion is correct, I will adopt it.

**Review by zwuis — COMMENTED** [review]
Please add a release note in clang/docs/ReleaseNotes.rst .

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 3]
```diff
@@ -6027,8 +6027,15 @@ void Sema::BuildVariableInstantiation(
...
+    VarTemplateWithAutoType = true;
+  }
+
   // Figure out whether to eagerly instantiate the initializer.
-  if (InstantiatingVarTemplate || InstantiatingVarTemplatePartialSpec) {
+  if ((InstantiatingVarTemplate && !VarTemplateWithAutoType) ||
+      InstantiatingVarTemplatePartialSpec) {
     // We're producing a template. Don't instantiate the initializer yet.
   } else if (NewVar->getType()->isUndeducedType()) {
     // We need the type to complete the declaration of the variable.
```
Comment (zwuis) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6041]: It seems that we can just swap these two `if` statements. We need to handle partial specializations as well. E.g.

```cpp
template <typename> struct B {
  template <typename, typrname> inline static auto var = 6;
  template <typename T> inline static auto var<int, T> = 7;
};

int b = B<int>::var<int, int>;
```

Comment (dty2) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: Thank you for your review. I think the two if statements should not be swapped, because clang adopts the strategy of delaying template instantiation. If the two if statements are swapped, it will completely violate this strategy. Therefore, I do not plan to swap the two if statements, but only pre-instantiate the template variables of auto type. Of course, if there are other reasons or my understanding is wrong, please let me know and I will consider it again. In addition, thank you again for reminding me to handle some specialized templates, so I modified the if statement to handle this situation.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: I don't understand what "strategy" is going to be violated. So you have an example?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 4]
```diff
@@ -6027,8 +6027,12 @@ void Sema::BuildVariableInstantiation(
   Context.setManglingNumber(NewVar, Context.getManglingNumber(OldVar));
   Context.setStaticLocalNumber(NewVar, Context.getStaticLocalNumber(OldVar));
 
+  bool VarTemplateWithAutoType =
+      OldVar->getTypeSourceInfo()->getType()->getAs<AutoType>();
+
   // Figure out whether to eagerly instantiate the initializer.
-  if (InstantiatingVarTemplate || InstantiatingVarTemplatePartialSpec) {
+  if (!VarTemplateWithAutoType &&
+      (InstantiatingVarTemplate || InstantiatingVarTemplatePartialSpec)) {
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6035]: This is special casing AutoType, but this should have the same problem for any DeducedType, like deduced template specializations as well, right?

Wouldn't just swapping the first two branches of the if-else chain here work?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 2 above)
Comment (zwuis) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: This test case makes me thinking that we should swap that rwo `if` statement. @dty2

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 4 above)
Comment (dty2) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6035]: Oh, I realized my mistake, thank you for correcting me.

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 2 above)
Comment (dty2) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: Oh my goodness, I realize my mistake, thank you for your patience in correcting me. You are right.

**Review by zwuis — COMMENTED** [review]
LGTM

**Review by mizvekov — APPROVED** [review]
LGTM

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks for working on this

@dty2 Can you fix the merge conflict? Will you need us to merge that for you?

File: clang/test/CodeGenCXX/cxx1z-inline-variables.cpp [hunk 5]
```diff
@@ -1,5 +1,19 @@
 // RUN: %clang_cc1 -std=c++1z %s -emit-llvm -o - -triple x86_64-linux-gnu | FileCheck %s
 
+template <typename T> struct InlineAuto {
+  template <typename G> inline static auto var = 5;
+};
+int inlineauot = InlineAuto<int>::var<int>;
```
Comment (zyn0217) [inline clang/test/CodeGenCXX/cxx1z-inline-variables.cpp:6]: inlineauto?

File: clang/test/CodeGenCXX/cxx1z-inline-variables.cpp [hunk 6]
```diff
@@ -1,5 +1,19 @@
...
+// CHECK: @_ZN10InlineAutoIiE3varIiEE = {{.*}}i32 5{{.*}}comdat
+//
+template <typename> struct PartialInlineAuto {
+  template <typename, typename> inline static auto var = 6;
+  template <typename T> inline static auto var<int, T> = 7;
+};
+
+int partialinlineauot = PartialInlineAuto<int>::var<int, int>;
```
Comment (zyn0217) [inline clang/test/CodeGenCXX/cxx1z-inline-variables.cpp:14]: ditto

File: clang/test/SemaTemplate/cxx17-inline-variables.cpp [hunk 7]
```diff
@@ -27,3 +27,15 @@ template <typename T> constexpr int A<T>::n = sizeof(A) + sizeof(T);
...
+  template <typename G> inline static auto var = 5;
+};
+
+template <typename> struct PartialInlineAuto {
+  template <typename, typename> inline static auto var = 6;
+  template <typename T> inline static auto var<int, T> = 7;
+};
+
+int inlineauot = InlineAuto<int>::var<int>;
+int partialinlineauot = PartialInlineAuto<int>::var<int, int>;
```
Comment (zyn0217) [inline clang/test/SemaTemplate/cxx17-inline-variables.cpp:41]: ditto

**Review by zyn0217 — APPROVED** [review]
LGTM plus nits

**Comment by ilovepi** [comment]
I have a revert up for this in #140930, due to the regressions reported in #140773, which breaks Fuchsia builds with new toolchains. We're fairly certain that changing the instantiation order as done in the patch is the root cause of the regression.
