### PR TITLE
[clang][Sema] Avoid non-empty unexpanded pack assertion for FunctionParmPackExpr

### LINKED ISSUE #61460: Assertion failure with nested parameter packs and lambdas
https://godbolt.org/z/4Pj4GhY9s
```cpp
template <typename... Ts> void g(Ts... p1s) {
  (void)[&](auto... p2s) { ([&] { p1s; p2s; }, ...); };
}                                                       
void f1() {
  g();
}
```

Looks like (according to GCC and Clang without assertions) this is probably valid (though I'm not entirely sure how/why - not sure how the lambda pack applies/doesn't to the function template pack) 

The crash backtrace is:
```console
clang++: /root/llvm-project/clang/lib/Sema/SemaTemplateVariadic.cpp:407: bool clang::Sema::DiagnoseUnexpandedParameterPack(clang::Expr*, clang::Sema::UnexpandedParameterPackContext): Assertion `!Unexpanded.empty() && "Unable to find unexpanded parameter packs"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<eof> parser at end of file
2.	<source>:1:32: instantiating function definition 'g<>'
 #0 0x00005555a36d685f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fee85f)
 #1 0x00005555a36d459c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fec59c)
 #2 0x00005555a3621d28 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f04e7246420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f04e6d1300b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f04e6cf2859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f04e6cf2729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f04e6d03fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00005555a69239c2 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x723b9c2)
 #9 0x00005555a640e83e clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d2683e)
#10 0x00005555a669107e clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6fa907e)
#11 0x00005555a68af229 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#12 0x00005555a687863f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformLambdaExpr(clang::LambdaExpr*) SemaTemplateInstantiate.cpp:0:0
#13 0x00005555a68791fa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#14 0x00005555a688144f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCXXFoldExpr(clang::CXXFoldExpr*) SemaTemplateInstantiate.cpp:0:0
#15 0x00005555a6879449 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#16 0x00005555a68adfcf clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
#17 0x00005555a68af229 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#18 0x00005555a687863f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformLambdaExpr(clang::LambdaExpr*) SemaTemplateInstantiate.cpp:0:0
#19 0x00005555a68791fa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#20 0x00005555a68aa5a2 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCStyleCastExpr(clang::CStyleCastExpr*) SemaTemplateInstantiate.cpp:0:0
#21 0x00005555a6879374 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#22 0x00005555a68adfcf clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
#23 0x00005555a68af229 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#24 0x00005555a68b48ae clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x71cc8ae)
#25 0x00005555a6903baa clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x721bbaa)
#26 0x00005555a6901eff clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7219eff)
#27 0x00005555a5efdd70 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#28 0x00005555a5efe45a clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x681645a)
#29 0x00005555a5d99913 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b1913)
#30 0x00005555a5d8d49a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66a549a)
#31 0x00005555a48fb2f8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52132f8)
#32 0x00005555a4161839 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a79839)
#33 0x00005555a40e5a46 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49fda46)
#34 0x00005555a4245517 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b5d517)
#35 0x00005555a0c62b66 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x157ab66)
#36 0x00005555a0c5e98a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#37 0x00005555a3f4c53d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#38 0x00005555a3622210 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f3a210)
#39 0x00005555a3f4cdff clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#40 0x00005555a3f1413c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x482c13c)
#41 0x00005555a3f14bdd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x482cbdd)
#42 0x00005555a3f1c97d clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x483497d)
#43 0x00005555a0c61010 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1579010)
#44 0x00005555a0b6d4a5 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x14854a5)
#45 0x00007f04e6cf4083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#46 0x00005555a0c596ce _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x15716ce)
```

### PR DESCRIPTION
**Pull request by zyn0217**
Closes https://github.com/llvm/llvm-project/issues/61460.

We have FunctionParmPackExpr that serves as the unexpanded expression but from which the visitor collects none, which may lead to assertion failure during the template instantiation.

### CODE REVIEW

File: clang/test/SemaCXX/pr61460.cpp [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// RUN: %clang_cc1 -std=c++17 %s -fsyntax-only -verify
+// expected-no-diagnostics
+template <typename... Ts> void g(Ts... p1s) {
+  (void)[&](auto... p2s) { ([&] { p1s; p2s; }, ...); };
+}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/pr61460.cpp:5]: can you add a test that
```cpp
template <typename... Ts> void g(Ts... p1s) {
  (void)[&](auto... p2s) { [&] { p1s; p2s; }; };
}                                                       
```
 does produce a diagnostic?

**Comment by cor3ntin** [comment]
I think the issue here is that we make the assumption that a full expression cannot contain an unexpanded pack
But that does not hold  for lambda.

Maybe instead of removing the assert entirely we could check whether one of the enclosing scope is a lambda.

While I think the change would be correct, i also think the assert is useful and I'm a bit concerned that removing it entirely will create problems down the line.

so i would encouraging researching 

```cpp
assert((!Unexpanded.empty() || enclosedInAnOtherExpression()) && "Unable to find unexpanded parameter packs");
```

where `enclosedInAnOtherExpression` would try to check that we are in a lambda  - maybe `Sema::getEnclosingLambda()` is sufficient - not sure though.


Can we run into similar problems with statement expressions ? (I don't think so as they don't have parameter or capture list)

**Comment by zyn0217** [comment]
Sorry for my late update - I've had a busy week ;)

> I don't think so as they don't have parameter or capture list

+1. and it looks like we don't allow expanding a pack outside a statement expression, which more or less prevents the appearance of `FunctionParmPackExpr`.

> so i would encouraging researching
> ```cpp
> assert((!Unexpanded.empty() || enclosedInAnOtherExpression()) && "Unable to find unexpanded parameter packs");
> ```
> where enclosedInAnOtherExpression would try to check that we are in a lambda - maybe Sema::getEnclosingLambda() is sufficient - not sure though.

Instead of putting it inside an assertion, how about adding a check for FunctionParmPackExpr separately? I mean,
```cpp
if (auto *Expr = dyn_cast<FunctionParmPackExpr>(E); Expr && getEnclosingLambda())
  return false;
```
to bail out only inside the `Expr` overload of `DiagnoseUnexpandedParameterPack`. (since it's the one being called anyways during template instantiation.)

**Comment by cor3ntin** [comment]
> Instead of putting it inside an assertion, how about adding a check for FunctionParmPackExpr separately? I mean,

If that works it would be fine with me, yes

File: clang/lib/Sema/SemaTemplateVariadic.cpp [hunk 2]
```diff
@@ -402,6 +402,20 @@ bool Sema::DiagnoseUnexpandedParameterPack(Expr *E,
...
+  // used such as `collectUnexpandedParameterPacks`, this type of expression
+  // is not expected to be collected.
+  //
+  // Nonetheless, this function for diagnosis is still called anyway during
+  // template instantiation, with an expression of such a type if we're inside a
+  // lambda with unexpanded parameters.
+  //
+  // Rule out this case to prevent the assertion failure.
+  if (auto *Expr = dyn_cast<FunctionParmPackExpr>(E);
+      Expr && getEnclosingLambda())
```
Comment (tbaederr) [inline clang/lib/Sema/SemaTemplateVariadic.cpp:416]:
```suggestion
  if (isa<FunctionParmPackExpr>(E) && getEnclosingLambda())
```

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateVariadic.cpp:416]: Thanks, I almost forget it ;)

**Comment by cor3ntin** [comment]
Looks generally good to me. can you remove the whitespace only changes? thanks!

**Comment by zyn0217** [comment]
Done. Sorry for leaving irrelevant changes ;)

File: clang/lib/Sema/SemaTemplateVariadic.cpp [hunk 3]
```diff
@@ -402,6 +402,19 @@ bool Sema::DiagnoseUnexpandedParameterPack(Expr *E,
...
+  // Exception: The `CollectUnexpandedParameterPacksVisitor` collects nothing
+  // from a FunctionParmPackExpr. In the context where the collector is being
+  // used such as `collectUnexpandedParameterPacks`, this type of expression
+  // is not expected to be collected.
+  //
+  // Nonetheless, this function for diagnosis is still called anyway during
+  // template instantiation, with an expression of such a type if we're inside a
+  // lambda with unexpanded parameters.
+  //
+  // Rule out this case to prevent the assertion failure.
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaTemplateVariadic.cpp:414]:
```suggestion
  // CollectUnexpandedParameterPacksVisitor does not expect to see a FunctionParmPackExpr, but
  // diagnosing unexpected parameter packs may still see such an expression in a lambda body. We'll
  // bail out early in this case to avoid triggering an assertion.
```
Slight rewording.

**Comment by zyn0217** [comment]
Thank you folks for the suggestions! I've updated, PTAL. :-)

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks
