### PR TITLE
[EarlyCSE] Compare GEP instructions based on offset

### LINKED ISSUE #65763: LoopFullUnrollPass failed due to constant inference in opaque pointer mode.
I tried to disable the opaque pointer in https://github.com/rust-lang/rust/issues/115339 to get the SLPVectorizer optimization.
See https://godbolt.org/z/GqdPGarsn.

According to my investigation, the success of optimization in non-opaque pointer mode relates to [SROA.cpp#L1831-L1845](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/Scalar/SROA.cpp#L1831-L1845)  or [InstructionCombining.cpp#L2220-L2274](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp#L2220-L2274). Unfortunately, these two transformations have been removed during opaque pointer migration.

My plan is to restore the behavior of [InstructionCombining.cpp#L2220-L2274](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp#L2220-L2274) using `alloc` instead of `bitcast`.
Looking at the code comments, this seems to be an important optimization. So it might be worth backporting to LLVM 17?

### PR DESCRIPTION
**Pull request by dianqk**
Closes #65763.
This will provide more opportunities for constant propagation for subsequent optimizations.

### CODE REVIEW

**Comment by nikic** [comment]
Please check the compile-time impact of this change. The impact was high when I tried something like this before, but maybe I made a mistake.

**Comment by DianQK** [comment]
> Please check the compile-time impact of this change. The impact was high when I tried something like this before, but maybe I made a mistake.

Could you add https://github.com/DianQK/llvm-project to https://llvm-compile-time-tracker.com/? Thanks.

**Comment by nikic** [comment]
> > Please check the compile-time impact of this change. The impact was high when I tried something like this before, but maybe I made a mistake.
> 
> Could you add https://github.com/DianQK/llvm-project to https://llvm-compile-time-tracker.com/? Thanks.

I'll do this on Thursday. I'm currently on vacation and don't have the SSH key with me.

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 1]
```diff
@@ -336,6 +336,13 @@ static unsigned getHashValueImpl(SimpleValue Val) {
   if (CallInst *CI = dyn_cast<CallInst>(Inst))
     return hashCallInst(CI);
 
+  if (auto *GEP = dyn_cast<GetElementPtrInst>(Inst)) {
+    auto &DL = GEP->getModule()->getDataLayout();
+    APInt Offset(DL.getIndexTypeSizeInBits(GEP->getType()), 0);
+    if (GEP->accumulateConstantOffset(DL, Offset))
+      return hash_combine(GEP->getOpcode(), GEP->getOperand(0), Offset);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:343]: nit: getPointerOperand().

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 2]
```diff
@@ -405,6 +412,17 @@ static bool isEqualImpl(SimpleValue LHS, SimpleValue RHS) {
            LII->getArgOperand(1) == RII->getArgOperand(0);
   }
 
+  if (auto *LGEP = dyn_cast<GetElementPtrInst>(LHSI)) {
+    auto *RGEP = cast<GetElementPtrInst>(RHSI);
+    if (LGEP->getOperand(0) != RGEP->getOperand(0))
+      return false;
+    auto &DL = LGEP->getModule()->getDataLayout();
+    APInt LOffset(DL.getIndexTypeSizeInBits(LGEP->getType()), 0);
+    APInt ROffset(DL.getIndexTypeSizeInBits(LGEP->getType()), 0);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:421]: nit: Avoid duplicate getIndexTypeSizeInBits() call (can't have different bitwidths if the pointer operand is the same)

**Comment by DianQK** [comment]
> > > > Please check the compile-time impact of this change. The impact was high when I tried something like this before, but maybe I made a mistake.
> > > 
> > > 
> > > Could you add https://github.com/DianQK/llvm-project to https://llvm-compile-time-tracker.com/? Thanks.
> > 
> > 
> > I'll do this on Thursday. I'm currently on vacation and don't have the SSH key with me.
> 
> Done, results are here: http://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=e079f3f9107f55e1595a47aafec5fe4e03277665&stat=instructions:u

Sad result. My initial guess was that in `GEP 1 1 .... 1 1 a` did redundant calculations.
But https://github.com/DianQK/llvm-project/commit/f3fdea44cd6ba0b129337850fecf567c35de6790 got [worse results](https://llvm-compile-time-tracker.com/?config=NewPM-O3&stat=instructions%3Au&remote=DianQK).
My other guess is that iteration itself is expensive. I'll try again. If that still doesn't work, I'd look into valgrind related tools.

**Comment by DianQK** [comment]
It's not ready for review yet. It may contain many nits.

Progress update:
Since lookups require frequent computation of constant offsets. GEP should not be considered as a `SimpleValue`.
I got better results than the last commit. I'll analyze it next with specific source code.

https://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=31e2ec9d89aeded9ea5da822262449b0c4e8ab16&stat=instructions:u

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 3]
```diff
@@ -553,6 +552,77 @@ bool DenseMapInfo<CallValue>::isEqual(CallValue LHS, CallValue RHS) {
...
+      return DenseMapInfo<Instruction *>::getTombstoneKey();
+  }
+
+  static unsigned getHashValue(GEPValue Val);
+  static bool isEqual(GEPValue LHS, GEPValue RHS);
+};
+
+} // end namespace llvm
+
+unsigned DenseMapInfo<GEPValue>::getHashValue(GEPValue Val) {
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:604]:
```suggestion
unsigned DenseMapInfo<GEPValue>::getHashValue(const GEPValue &Val) {
```
Here and elsewhere.

**Comment by DianQK** [comment]
Using references works well!
https://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=089349f9eb47c57cfa2049ce0af5c7dd079a8581&stat=instructions%3Au

I've also tried some approaches. 
It should be useful to avoid offset calculations. I tried counting only with a GEP i8, but there is some extra cost to the determination of this one.
Simplifying the offset calculation is of some use, but I'm not sure it makes sense. Results are here https://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=8ba478eb77c6dc09b87e9b511614e45e167be2b5&stat=instructions%3Au

**Comment by nikic** [comment]
Okay, those results look reasonable. It's somewhat unfortunate that this requires duplicating a bunch of code for the separate GEP handling. I'm wondering, would we be able to achieve similar results if we add a `DenseMap<GetElementPtrInst *, APInt>` cache for the offset but otherwise keep the previous code structure? Or would the extra hash lookup make this slow again?

**Comment by DianQK** [comment]
> I'm wondering, would we be able to achieve similar results if we add a `DenseMap<GetElementPtrInst *, APInt>` cache for the offset but otherwise keep the previous code structure? Or would the extra hash lookup make this slow again?

I feel like I misunderstood. Do you mean putting the GEP back into `SimpleValue`? And then create a global (or EarlyCSE only) cache value?

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 4]
```diff
@@ -553,6 +553,77 @@ bool DenseMapInfo<CallValue>::isEqual(CallValue LHS, CallValue RHS) {
...
+//===----------------------------------------------------------------------===//
+// GEPValue
+//===----------------------------------------------------------------------===//
+
+namespace {
+
+struct GEPValue {
+  Instruction *Inst;
+  APInt ConstantOffset;
+  bool HasConstantOffset;
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:565]: Use std::optional instead?

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 5]
```diff
@@ -553,6 +553,77 @@ bool DenseMapInfo<CallValue>::isEqual(CallValue LHS, CallValue RHS) {
...
+      assert((isSentinel() || canHandle(I)) && "Inst can't be handled!");
+  }
+
+  bool isSentinel() const {
+      return Inst == DenseMapInfo<Instruction *>::getEmptyKey() ||
+             Inst == DenseMapInfo<Instruction *>::getTombstoneKey();
+  }
+
+  static bool canHandle(Instruction *Inst) {
+      return isa<GetElementPtrInst>(Inst);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:582]: The indents in these functions look wrong -- clang-format?

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 6]
```diff
@@ -553,6 +553,77 @@ bool DenseMapInfo<CallValue>::isEqual(CallValue LHS, CallValue RHS) {
...
+  }
+
+  static unsigned getHashValue(const GEPValue &Val);
+  static bool isEqual(const GEPValue &LHS, const GEPValue &RHS);
+};
+
+} // end namespace llvm
+
+unsigned DenseMapInfo<GEPValue>::getHashValue(const GEPValue &Val) {
+  GetElementPtrInst *GEP = cast<GetElementPtrInst>(Val.Inst);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:606]: nit: Use `auto *` with  `cast<>`.

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 5 above)
Comment (DianQK) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp]: https://github.com/llvm/llvm-project/pull/65875/files#diff-77f80fb318742b6bfa0825b341fb6e8cf89141fe8200f3574d556aa48db5114fL551-R551
This line breaks git-based incremental formatting.

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 4 above)
Comment (DianQK) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp:565]: I seem to get a poor performance. Maybe I missed something, I'll look at it again.
- Compare it to using bool: https://llvm-compile-time-tracker.com/compare.php?from=12eda5cf2df6438453683ce8c917a64786686a69&to=ff70ae265ac5ad9da12836ae954fd64ce5b38df4&stat=instructions:u
- Full: https://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=ff70ae265ac5ad9da12836ae954fd64ce5b38df4&stat=instructions%3Au

**Comment by DianQK** [comment]
> > > I'm wondering, would we be able to achieve similar results if we add a `DenseMap<GetElementPtrInst *, APInt>` cache for the offset but otherwise keep the previous code structure? Or would the extra hash lookup make this slow again?
> > 
> > 
> > I feel like I misunderstood. Do you mean putting the GEP back into `SimpleValue`? And then create a global (or EarlyCSE only) cache value?
> 
> Yes (EarlyCSE only cache). This is just a suggestion for something to check, but I suspect the performance of that approach will not be good enough and we have to go with this version.

I did not try this approach. My understanding is that this only adds extra lookups if applied to a single EarlyCSE. Since each result needs to be calculated once. The current patch is the no-hash approach as I understand it.
This result may be invalid if shared in EarlyCSE.

I made a new attempt to save uint64_t instead of APInt.
This result looks pretty good. https://llvm-compile-time-tracker.com/compare.php?from=ac1daad9bb4eb083df6b215c029816d3149e00d8&to=82f1eca7c180b0dfe8af36e933670f938a49bab1&stat=instructions%3Au

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp [hunk 7]
```diff
@@ -1561,6 +1646,31 @@ bool EarlyCSE::processNode(DomTreeNode *Node) {
       continue;
     }
 
+    // Compare GEP instructions based on offset.
+    if (GEPValue::canHandle(&Inst)) {
+      auto *GEP = cast<GetElementPtrInst>(&Inst);
+      APInt Offset = APInt(SQ.DL.getIndexTypeSizeInBits(GEP->getType()), 0);
+      GEPValue GEPVal(GEP, GEP->accumulateConstantOffset(SQ.DL, Offset)
+                               ? Offset.tryZExtValue()
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/EarlyCSE.cpp:1654]: I think the offset should be `int64_t` and use `trySExtValue()` here. GEP offsets are signed. (Mainly for clarify, I think it will not make a functional difference?)

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Scalar/EarlyCSE.cpp (hunk 7 above)
Comment (DianQK) [reply llvm/lib/Transforms/Scalar/EarlyCSE.cpp]: Yes, it's more clear to use `int64_t`.
