### PR TITLE
[Clang] Implement LWG3819 for `__reference_meows_from_temporary`

### LINKED ISSUE #114344: [Clang] Unexpected results from `__reference_{constructs,converts}_from_temporary`
It seems that the following `static_assert`'s should pass, but Clang currently rejects them ([link](https://www.godbolt.org/z/7Wec34cnT)).

```C++
static_assert(!__reference_constructs_from_temporary(void(&&)(), void()), "Normal function is treated as lvalue.");
static_assert(!__reference_converts_from_temporary(void(&)(), void()), "Normal function is treated as lvalue.");
static_assert(!__reference_constructs_from_temporary(void(&)(), void()), "Normal function is treated as lvalue.");
static_assert(!__reference_converts_from_temporary(void(&&)(), void()), "Normal function is treated as lvalue.");
static_assert(__reference_constructs_from_temporary(int&&, const int), "const int is adjusted to int");
static_assert(__reference_converts_from_temporary(int&&, const int), "const int is adjusted to int");
```

- Per [[expr.type]/2](https://eel.is/c++draft/expr.type#2), "`const int` prvalue" needs to be adjusted to "`int` prvalue", so there shouldn't be cv-qualification dropping and the binding to temporary object should be valid.
- For the (normal) function case, as `decltype(std::declval<Fun>())` is `Fun&` when `Fun` is a normal function type, the reference binding should be valid. But despite the binding being valid or not, there can never be a temporary and thus the traits should report `false`.

This probably doesn't block the library implementation of [P2255R2](https://wg21.link/p2255r2) because workaround can be easily implemented.

----
Moreover, the results of these traits is a bit unclear to me for the following cases ([link](https://www.godbolt.org/z/jqrM3hvWP)):

```C++
struct Abstract {
  virtual void fun() = 0;
};

static_assert(__reference_constructs_from_temporary(Abstract&&, Abstract), "The code is so abstract.");
static_assert(__reference_converts_from_temporary(Abstract&&, Abstract), "The code is so abstract.");

static_assert(__reference_constructs_from_temporary(int(&&)[], int[]), "Array-of-unknown-bound prvalue?");
static_assert(__reference_converts_from_temporary(int(&&)[], int[]), "Array-of-unknown-bound prvalue?");
```

It seems that the abstractness of the class should be ignored in the spirit of [P0929R2](https://wg21.link/p0929r2) (so Clang is giving correct results for the `Abstract` case), but this doesn't seem clear in the current standard wording.

The case for `int[]` is really weird as there's no prvalue of type `T[]`.

CC @cjdb @cor3ntin @timsong-cpp

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Also fix use cases for function reference binding (`__reference_binds_to_temporary` is also affected despite being deprecated).

Fixes #114344. Towards #105079.

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]

**Comment by cor3ntin** [comment]
I am assuming you want to handle the libc++ changes separately? (They would need tests/status update)

**Comment by frederick-vs-ja** [comment]
> I am assuming you want to handle the libc++ changes separately? (They would need tests/status update)

Yeah. I guess it's better to separate the changes in two PRs, as combination of another library implementation with Clang will benefit slightly more quickly.

File: clang/lib/Sema/SemaTypeTraits.cpp [hunk 1]
```diff
@@ -1343,12 +1343,21 @@ static bool EvaluateBooleanTypeTrait(Sema &S, TypeTrait Kind,
     if (RD && RD->isAbstract())
       return false;
 
+    // LWG3819: For reference_meows_from_temporary traits, && is not added to
```
Comment (shafik) [inline clang/lib/Sema/SemaTypeTraits.cpp:1346]: So I see `reference_meows_from_temporary` in [LWG3819](https://cplusplus.github.io/LWG/issue3819) but I don't get it. Maybe this require some explanation or at least a pointer to an issues that explains it?

Comment (frederick-vs-ja) [reply clang/lib/Sema/SemaTypeTraits.cpp:1346]: Formerly, `reference_meows_from_temporary` requires `is_constructible`, which in turn depends on `declval` ([[meta.rel]/5](https://eel.is/c++draft/meta.rel#5)). And for each object type `U`, the return type of `declval<U>` is `U&&`. As a result, both binding to `U` (prvalue) and binding to `U&&` (xvalue) were required.

LWG3819 removed such dependency, and then `reference_meows_from_temporary` traits only rely on binding to `U` prvalue when `U` is an object type.

Do we want to expand the whole story in the comments?

Comment (shafik) [reply clang/lib/Sema/SemaTypeTraits.cpp:1346]: I apologize, maybe I am just being dense but is this some sort of inside joke or word play? Within the draft I do not find `reference_meows_from_temporary` or `is_meowible`. So there reference is quite opaque.

Comment (shafik) [reply clang/lib/Sema/SemaTypeTraits.cpp:1346]: After some offline discussion I now get that `meow` is basically an `X` which can be replaced a series of terms, this case converts/constructs.

I still think this will confusing to anyone not already familiar w/ LWG but I don't have a good replacement suggestion.
