### PR TITLE
[clang-tidy] Fix invalid fixit from modernize-use-ranges for nullptr used with std::unique_ptr

### LINKED ISSUE #124815: [clang-tidy] Invalid fixit from modernize-use-ranges for nullptr used with std::unique_ptr
~~~c++
#include <vector>
#include <algorithm>
#include <memory>
#include <ranges>

bool f(const std::vector<std::unique_ptr<int>>& v) {
    return std::find(v.begin(), v.end(), nullptr) == v.end();
}

bool g(const std::vector<std::unique_ptr<int>>& v) {
    return std::ranges::find(v, std::unique_ptr<int>()) == v.end();
}

int main() {
    std::vector<std::unique_ptr<int>> a;
    a.emplace_back();
    return g(a);
}
~~~
~~~
<source>:7:12: warning: use a ranges version of this algorithm [modernize-use-ranges]
    1 | #include <vector>
    2 | #include <algorithm>
    3 | #include <memory>
    4 | #include <ranges>
    5 | 
    6 | bool f(const std::vector<std::unique_ptr<int>>& v) {
    7 |     return std::find(v.begin(), v.end(), nullptr) == v.end();
      |            ^~~~~~~~~ ~~~~~~~~~  ~~~~~~~
      |            std::ranges::find v
1 warning generated.
~~~
https://godbolt.org/z/zsP6nM9oc
I'm not sure why `ranges::find` does not accept `nullptr` here (as opposed to normal `find`), but it is rejected by all three major compilers.

### PR DESCRIPTION
**Pull request by Andrewyuan34**
This PR fixes issue #124815 by correcting the handling of `nullptr` with `std::unique_ptr` in the `modernize-use-ranges` check.

### Changes:
1. **Modified `clang-tools-extra/clang-tidy/modernize/UseRangesCheck.cpp`**:
    - Updated the logic to suppress warnings for `nullptr` in `std::find`.

2. **Added unit tests**:
   - Added new test cases to verify no warning is generated for `nullptr`.
   - Ensured existing behavior for `std::unique_ptr<int>()` remains unchanged.

### Linked Issue:
Fixes #124815.

### Testing:
- All existing unit tests pass.
- New unit tests have been added to verify the fix.

Note:
This is my first PR to the LLVM project. If there are any issues or areas for improvement, please let me know—I’m happy to make adjustments and learn from your feedback! Thank you for your patience and guidance.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/utils/UseRangesCheck.cpp [hunk 1]
```diff
@@ -215,6 +215,16 @@ void UseRangesCheck::check(const MatchFinder::MatchResult &Result) {
     const auto *Call = Result.Nodes.getNodeAs<CallExpr>(Buffer);
     if (!Call)
       continue;
+    if (Function->getName() == "find") {
+      unsigned ValueArgIndex = 2;
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/utils/UseRangesCheck.cpp:219]:
```suggestion
      const unsigned ValueArgIndex = 2;
```

File: clang-tools-extra/clang-tidy/utils/UseRangesCheck.cpp [hunk 2]
```diff
@@ -215,6 +215,16 @@ void UseRangesCheck::check(const MatchFinder::MatchResult &Result) {
...
+      if (Call->getNumArgs() <= ValueArgIndex)
+        continue;
+      const Expr *ValueExpr =
+          Call->getArg(ValueArgIndex)->IgnoreParenImpCasts();
+      if (isa<CXXNullPtrLiteralExpr>(ValueExpr)) {
+        return;
+      }
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/utils/UseRangesCheck.cpp:226]:
```suggestion
      if (isa<CXXNullPtrLiteralExpr>(ValueExpr))
        return;
```

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-ranges.cpp [hunk 3]
```diff
@@ -1,14 +1,24 @@
...
 // CHECK-FIXES-CPP23: #include <numeric>
 // CHECK-FIXES: #include <ranges>
 
-#include "fake_std.h"
+#include "use-ranges/fake_std.h"
+#include "smart-ptr/unique_ptr.h"
 
 void Positives() {
   std::vector<int> I, J;
+
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-ranges.cpp:14]: I assume those tests pass due to "fake_std", would be good to use proper vector:
```
std::vector<std::unique_ptr<int>>
```
for these tests.

**Review by PiotrZSL — APPROVED** [review]
Short release notes entry about fix would be nice.

**Comment by Andrewyuan34** [comment]
> Short release notes entry about fix would be nice.

Done

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-ranges.cpp (hunk 3 above)
Comment (Andrewyuan34) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-ranges.cpp:15]: > I assume those tests pass due to "fake_std", would be good to use proper vector:
> 
> ```
> std::vector<std::unique_ptr<int>>
> ```
> 
> for these tests.

good point! Already applied.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -109,6 +109,9 @@ Changes in existing checks
 - Improved :doc:`misc-redundant-expression
   <clang-tidy/checks/misc/redundant-expression>` check by providing additional
   examples and fixing some macro related false positives.
+  
+- Fixed a false positive in :doc:`modernize-use-ranges
```
Comment (vbvictor) [inline clang-tools-extra/docs/ReleaseNotes.rst:113]:
```suggestion
- Improved :doc:`modernize-use-ranges
```
I think we should stick to uniform style of ReleaseNotes, example can be found [here](https://releases.llvm.org/19.1.0/tools/clang/tools/extra/docs/ReleaseNotes.html).

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -109,6 +109,9 @@ Changes in existing checks
...
+  <clang-tidy/checks/modernize/use-ranges>`update the logic to suppress warnings for `nullptr` in `std::find`.
```
Comment (vbvictor) [inline clang-tools-extra/docs/ReleaseNotes.rst:114]:
```suggestion
  <clang-tidy/checks/modernize/use-ranges>` check by updating suppress warnings logic for ``nullptr`` in ``std::find``.
```

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -109,6 +109,9 @@ Changes in existing checks
 - Improved :doc:`misc-redundant-expression
   <clang-tidy/checks/misc/redundant-expression>` check by providing additional
   examples and fixing some macro related false positives.
+  
+- Improved :doc:`modernize-use-ranges
+  <clang-tidy/checks/modernize/use-ranges>` check by updating suppress warnings logic for ``nullptr`` in ``std::find``.
```
Comment (vbvictor) [inline clang-tools-extra/docs/ReleaseNotes.rst:114]: Please make lines no more than 80 characters long (rule applied to all docs).

**Comment by chrchr-github** [comment]
Thanks for addressing this. However I think a more general solution is required (instead of special-casing `std::unique_ptr`/`nullptr`), see https://github.com/llvm/llvm-project/issues/124815#issuecomment-2676753012

**Review by HerrCai0907 — COMMENTED** [review]
LGTM. since it is just a patch instead of ideal solution for `std::equality_comparable_with` stuff, could you add some FIXME in code?

**Comment by Andrewyuan34** [comment]
> Thanks for addressing this. However I think a more general solution is required (instead of special-casing `std::unique_ptr`/`nullptr`), see [#124815 (comment)](https://github.com/llvm/llvm-project/issues/124815#issuecomment-2676753012)

Thanks for the comment, I got confused by the following comments, should I just leave a FIXME or use a more general way to solve it.

**Review by HerrCai0907 — APPROVED** [review]

**Comment by HerrCai0907** [comment]
ping me if you want to merge it.

**Comment by Andrewyuan34** [comment]
> ping me if you want to merge it.

Thanks! I'd like to merge it.

**Comment by Andrewyuan34** [comment]
> ping me if you want to merge it.

sorry about forgetting to use git-clang-format to check the differences. Now it should work.

**Comment by Andrewyuan34** [comment]
> ping me if you want to merge it.

I‘m sorry for requesting approval again. But I'm really confused that should I make sure my branch is alwasy up-to-date?

**Comment by vbvictor** [comment]
> I‘m sorry for requesting approval again. But I'm really confused that should I make sure my branch is alwasy up-to-date?

Rebase from `main` periodically, at least before merge.
It's just to make sure that there are no merge conflicts.

**Comment by Andrewyuan34** [comment]
> > I‘m sorry for requesting approval again. But I'm really confused that should I make sure my branch is alwasy up-to-date?
> 
> Rebase from `main` periodically, at least before merge. It's just to make sure that there are no merge conflicts.
Thanks for the explanation!

**Comment by Andrewyuan34** [comment]
@HerrCai0907 Sorry for requesting your approval again, I really have no experience sending a PR.  
I appreciate your patience and feedback on my changes. Let me know if there's anything else I should improve.  
Thanks for your time! 😊

**Comment by HerrCai0907** [comment]
Thanks for you contributions!

Some tips: 
1. run git-clang-format -f before commit change
2. actually you don't need to rebase often. but in past several weeks we have a major release and it causes release notes are cleared. in this case, rebase is needed.
3. After several successfully land, you can request write access. then you can merge it by yourself.

**Comment by Andrewyuan34** [comment]
> Thanks for you contributions!
> 
> Some tips:
> 
> 1. run git-clang-format -f before commit change
> 2. actually you don't need to rebase often. but in past several weeks we have a major release and it causes release notes are cleared. in this case, rebase is needed.
> 3. After several successfully land, you can request write access. then you can merge it by yourself.

I really appreciate all of the suggestions! Will take those in mind. Looking forward to the day I have write access.
