### PR TITLE
Reland: [clang] Fix missing diagnostic of declaration use when accessing TypeDecls through typename access

### LINKED ISSUE #58547: Missing diagnostic of declaration use when accessing TypeDecls through typename access
Repro: https://godbolt.org/z/TeTzfcdsv
```cpp
struct A {
  using ta [[deprecated]] = int;
};

using t1 = typename A::ta;

template <class B1> struct B {
  using tb = typename B1::ta;
};

template struct B<A>;
```

GCC emits diagnostic for deprecated `ta` on both uses, Clang emits no diagnostics at all.

### PR DESCRIPTION
**Pull request by mizvekov**
We were missing a call to DiagnoseUseOfDecl when performing typename access.

This refactors the code so that TypeDecl lookups funnel through a helper which performs all the necessary checks, removing some related duplication on the way.

When diagnosing availability uses through typedefs, this changes the implementation so it won't dig through subst nodes, as those uses should be diagnosed through the template specialization it was accessed from. This takes care of the regression reported here: https://github.com/llvm/llvm-project/pull/129681#issuecomment-2710469954

Fixes #58547

Original PR: https://github.com/llvm/llvm-project/pull/129681
Differential Revision: https://reviews.llvm.org/D136533

### CODE REVIEW

File: clang/test/Sema/attr-availability-macosx.cpp [hunk 1]
```diff
@@ -14,4 +14,17 @@ bool try_acquire_for(T duration) { // expected-note{{'try_acquire_for<int>' has
...
+
+  template<class T> struct B { using type = T; };
+  template <class T> struct C {
+    typename B<T>::type v;
+  };
+
+  struct [[clang::availability(macos, introduced = 16)]] D {
+    C<A> c;
+  };
+} // namespace typename_template
```
Comment (mizvekov) [inline clang/test/Sema/attr-availability-macosx.cpp:30]: This tests https://github.com/llvm/llvm-project/pull/129681#issuecomment-2710469954

File: clang/lib/Sema/SemaAvailability.cpp [hunk 2]
```diff
@@ -99,16 +99,29 @@ ShouldDiagnoseAvailabilityOfDecl(Sema &S, const NamedDecl *D,
...
+        T = NextT;
         continue;
       }
+      Result = D->getAvailability(Message);
+      break;
     }
-    break;
   }
-
+done:
```
Comment (mizvekov) [inline clang/lib/Sema/SemaAvailability.cpp:124]: This fixes https://github.com/llvm/llvm-project/pull/129681#issuecomment-2710469954

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaAvailability.cpp [hunk 3]
```diff
@@ -99,16 +99,29 @@ ShouldDiagnoseAvailabilityOfDecl(Sema &S, const NamedDecl *D,
...
   while (const auto *TD = dyn_cast<TypedefNameDecl>(D)) {
-    if (Result == AR_Available) {
-      if (const auto *TT = TD->getUnderlyingType()->getAs<TagType>()) {
+    if (Result != AR_Available)
+      break;
+    for (const Type *T = TD->getUnderlyingType().getTypePtr(); /**/; /**/) {
+      if (auto *TT = dyn_cast<TagType>(T)) {
         D = TT->getDecl();
-        Result = D->getAvailability(Message);
+      } else if (isa<SubstTemplateTypeParmType>(T)) {
```
Comment (zyn0217) [inline clang/lib/Sema/SemaAvailability.cpp:107]: Do we need to take care of NTTP/template template parameters here?

Comment (mizvekov) [reply clang/lib/Sema/SemaAvailability.cpp:107]: NTTP it looks unlikely, as we would be needing to dig through expressions, which we don't here, but maybe elsewhere.

Template Template parameters maybe, but it looks far fetched for the kind of application this availability thing has.
