### PR TITLE
[ASan][Windows] Fix memmove/memcpy interception on x64

### LINKED ISSUE #126077: [asan][win][regression] memcpy is not alias for memmove with dynamic setup on latest Windows
I have seen the following error on some of our internal test machines
```
Failed Tests (5):
  AddressSanitizer-Unit :: ./Asan-x86_64-calls-Dynamic-Test.exe/AddressSanitizer/MemCpyOOBTest
  AddressSanitizer-Unit :: ./Asan-x86_64-inline-Dynamic-Test.exe/AddressSanitizer/MemCpyOOBTest
  AddressSanitizer-x86_64-windows-dynamic :: TestCases/Windows/dll_intercept_memcpy_indirect.cpp
  AddressSanitizer-x86_64-windows-dynamic :: TestCases/Windows/intercept_memcpy.cpp
  AddressSanitizer-x86_64-windows-dynamic :: TestCases/memset_test.cpp
```

After some investigation, with the latest Windows setup(these failures only reproduced on those setup) and dynamic setup(the static test config does not have these failures), 
```
#elif SANITIZER_WINDOWS64
#define PLATFORM_HAS_DIFFERENT_MEMCPY_AND_MEMMOVE 0
```
is not true anymore. The `memcpy` is not the alias for `memmove`, and we will have to intercept them both. However, simply changing this to `1` for Windows, although it can fix the failures for latest Windows, would bring huge regression for not-so-update-to-date Windows.

I have no further idea how to solve this problem, but I think this would affect more users with time after users update their OS and runtime. And I don't sure which part of the environment is causing this difference.

System information:
```
OS: Microsoft Windows 11 Enterprise LTSC 24H2 10.0.26100
msvcrt.dll version: 7.0.26100.1882
vcruntime140.dll version: 14.42.34433.0
```
I don't know if this information is enough, and I am happy to provide other information if needed.

### PR DESCRIPTION
**Pull request by aganea**
On Windows x64, memcpy and memmove used to share an implementation in `vcruntime140.dll`, but newer versions of the CRT may provide them as separate functions. Detect this at runtime and intercept accordingly, rather than unconditionally assuming they alias each other.

Should fix https://github.com/llvm/llvm-project/issues/126077

### CODE REVIEW

File: compiler-rt/lib/asan/asan_allocator.cpp [hunk 1]
```diff
@@ -803,11 +803,12 @@ struct Allocator {
...
       if (chunk_state != CHUNK_ALLOCATED)
         ReportInvalidFree(old_ptr, chunk_state, stack);
-      CHECK_NE(REAL(memcpy), nullptr);
       uptr memcpy_size = Min(new_size, m->UsedSize());
       // If realloc() races with free(), we may start copying freed memory.
       // However, we will report racy double-free later anyway.
-      REAL(memcpy)(new_ptr, old_ptr, memcpy_size);
+      // Avoid intercepted CRT memcpy/memmove (see
+      // sanitizer_allocator_combined.h)
+      internal_memcpy(new_ptr, old_ptr, memcpy_size);
```
Comment (thurstond) [inline compiler-rt/lib/asan/asan_allocator.cpp]: `internal_memcpy`/`__sanitizer_internal_memcpy` is a fairly simple implementation. Unless the auto-vectorization is smart, I wonder if this will be a performance regression on non-Windows platforms? (Though I guess Reallocate is not that common.)

Comment (thurstond) [reply compiler-rt/lib/asan/asan_allocator.cpp]: Nit: since this change affects cross-platform code, I suggest renaming the pull request title to not imply that it is a Windows-only change

Comment (aganea) [reply compiler-rt/lib/asan/asan_allocator.cpp]: Changed so that this only applies to WIN64 and only for this specific CRT version (when memmove != memcpy).

**Comment by zmodem** [comment]
Thanks for working on this!

I tried this locally and get similar errors as the CI (e.g. the AddressSanitizer.ReallocTest failure), even though it seems the code is trying to address that.

**Comment by aganea** [comment]
> I tried this locally and get similar errors as the CI (e.g. the AddressSanitizer.ReallocTest failure), even though it seems the code is trying to address that.

Fixed.

**Review by zmodem — APPROVED** [review]
lgtm

**Comment by zmodem** [comment]
Thanks again for fixing this!

Just out of curiosity, do you know when the vcruntime140.dll change happened? I'm surprised we didn't run into this on our side, given it was reported more than a year ago and I think we're using pretty recent versions of everything.

**Comment by aganea** [comment]
I think I've broken this bot: https://lab.llvm.org/buildbot/#/builders/107/builds/19020 - I am working on a fix now.

**Comment by aganea** [comment]
> Just out of curiosity, do you know when the vcruntime140.dll change happened? I'm surprised we didn't run into this on our side, given it was reported more than a year ago and I think we're using pretty recent versions of everything.

Not sure. These functions seem to come with both vcruntime140.dll and ucrtbase.dll, so probably the reproducer depends on a number of factors, how the binary was linked, how the IAT resolves the imports (dynamic or static build), OS version, ucrt version, etc. On my machine, one the DLLs (vcruntime140) shows separate symbols whereas the other (ucrtbase) shows aliases:
```
>dumpbin /exports "%SystemRoot%\System32\vcruntime140.dll" | findstr /i "memcpy memmove"
         61   3C 00013010 memcpy
         62   3D 00012030 memmove

>dumpbin /exports "%SystemRoot%\System32\ucrtbase.dll" | findstr /i "memcpy memmove"
       1611  64A 0006B3F0 _o_memcpy_s
       1731  6C2 0003E400 _o_wmemcpy_s
       1732  6C3 0003D650 _o_wmemmove_s
       2310  905 000EDB20 memcpy
       2311  906 000950F0 memcpy_s
       2312  907 000EDB20 memmove
       2313  908 0007A260 memmove_s
       2483  9B2 0003E620 wmemcpy_s
       2484  9B3 00092F70 wmemmove_s
```
