### PR TITLE
[Flang][Semantics] Fix crash on invalid function result declaration

### LINKED ISSUE #194596: [Flang][Semantics] Flang crashes on invalid CHARACTER function result declaration instead of reporting semantic error.
When compiling the following Fortran code, flang crashes instead of emitting a proper error message for an invalid function result declaration. 

Minimal reproducer:

```
character*(a) function bb() result(a) ! ERROR
implicit integer(a)
A = "a"
end
```

https://godbolt.org/z/P8G4Gqv7r

### PR DESCRIPTION
**Pull request by ShashwathiNavada**
Fixes https://github.com/llvm/llvm-project/issues/194596.

When the function result symbol is encountered while the compiler is already completing the function result type, flang could recursively re-enter _CompleteFunctionResultType()_ and crash on invalid code.
Example:
```
character*(a) function bb() result(a) ! ERROR
implicit integer(a)
A = "a"
end
```
Instead of crashing on conflicting declarations, flang now reports an “already declared” error and stops further recursion.

### CODE REVIEW

**Review by cenewcombe — CHANGES_REQUESTED** [review]
These changes look good to me. Could you add a LIT test to ensure there are no regressions?

You can start with the file `resolve128.cpp` on my closed PR (I accidentally overlapped with your work): https://github.com/llvm/llvm-project/pull/194678/changes.

- You'd need to change the `!CHECK` lines, as the error messages will be different.
- Suggest adding a test case for the `result()` suffix
- Please remove the spaces between `!` and `RUN`/`CHECK` -- those were a mistake!

Thanks and sorry for the confusion/duplication -- that was my fault!

**Comment by ShashwathiNavada** [comment]
[cenewcombe](https://github.com/cenewcombe) Done! I have added the said testcase with the changes suggested. Thank you!

**Review by cenewcombe — APPROVED** [review]
Thanks for adding those test cases! LGTM, but please wait for review from @eugeneepshteyn before merging.

File: flang/lib/Semantics/resolve-names.cpp [hunk 1]
```diff
@@ -498,6 +496,8 @@ class FuncResultStack {
     // Result symbol
     Symbol *resultSymbol{nullptr};
     bool inFunctionStmt{false}; // true between Pre/Post of FunctionStmt
+    bool completingType{
+        false}; // re-entrancy guard for CompleteFunctionResultType
```
Comment (tarunprabhu) [inline flang/lib/Semantics/resolve-names.cpp]: Nit: Do you mind moving the comment above the statement. It would stop `clang-format` from formatting this line in a strange way.

```suggestion
    // re-entrancy guard for CompleteFunctionResultType
    bool completingType{false};
```

**Review by tarunprabhu — COMMENTED** [review]
Just a quick comment. Feel free to merge once Eugene approves.

File: flang/lib/Semantics/resolve-names.cpp (hunk 1 above)
Comment (eugeneepshteyn) [inline flang/lib/Semantics/resolve-names.cpp]: Could you please move `// re-entrancy guard for CompleteFunctionResultType` to just before `completingType`, so that `bool completingType{false};` could be on one line?

(This may seem like a silly request, but when one tries to review lots of code, every unusually formatted change slows the brain down. :-)

File: flang/test/Semantics/resolve128.f90 [hunk 2]
```diff
@@ -0,0 +1,25 @@
+!RUN: not %flang_fc1 -fsyntax-only %s 2>&1 | FileCheck %s
```
Comment (eugeneepshteyn) [inline flang/test/Semantics/resolve128.f90]: This seems like a good test for test_errors.py:
```
!RUN: %python %S/test_errors.py %s %flang_fc1
...
!ERROR: 'f1' is already declared in this scoping unit
```

File: flang/lib/Semantics/resolve-names.cpp (hunk 1 above)
Comment (eugeneepshteyn) [reply flang/lib/Semantics/resolve-names.cpp]: Oh, what Tarun said! (Sorry, hadn't noticed this comment before.)

Comment (ShashwathiNavada) [reply flang/lib/Semantics/resolve-names.cpp]: Done! Thank you!

Comment (ShashwathiNavada) [reply flang/lib/Semantics/resolve-names.cpp]: Done!! Thank you!

File: flang/test/Semantics/resolve128.f90 (hunk 2 above)
Comment (ShashwathiNavada) [reply flang/test/Semantics/resolve128.f90]: Done!

File: flang/test/Semantics/resolve128.f90 [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+  f = 2
+end function
+
+!ERROR: 'f3' is already declared in this scoping unit
+integer(f3) function f3()
+  f3 = 2
+end function
+
+!ERROR: 'f4' is already declared in this scoping unit
+character*(f4) function bb() result(f4) ! ERROR
```
Comment (eugeneepshteyn) [inline flang/test/Semantics/resolve128.f90]: One nit: could you please remove the trailing `! ERROR` comment?

**Review by eugeneepshteyn — APPROVED** [review]
LGTM, with one small nit. Thank you for the change!

File: flang/test/Semantics/resolve128.f90 (hunk 3 above)
Comment (ShashwathiNavada) [reply flang/test/Semantics/resolve128.f90]: Done!! Thank you!!

**Review by tarunprabhu — APPROVED** [review]
LGTM. Thanks.
