### PR TITLE
[mlir][affine] Modify assertion into a user visible diagnostic

### LINKED ISSUE #122227: [Mlir] --affine-super-vectorizer-test="vectorize-affine-loop-nest" crashes in VectorUtils.cpp:145: AffineMap makePermutationMap git version: e4372c4454c9
system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt a.mlir --affine-super-vectorizer-test="vectorize-affine-loop-nest"`

a.mlir: 
``` 
#map = affine_map<(d0)[s0] -> (d0 mod s0)>
#map1 = affine_map<(d0)[s0] -> (d0 floordiv s0)>
module {
  memref.global "private" constant @__constant_17x18xf32 : memref<17x18xf32> = dense<0.000000e+00> {alignment = 64 : i64}
  memref.global "private" constant @__constant_17x18xi32 : memref<17x18xi32> = dense<0> {alignment = 64 : i64}
  func.func private @func3(%arg0: index) -> (memref<17x18xf32>, memref<17x18xi32>, memref<17x18xf32>) {
    %c18 = arith.constant 18 : index
    %cst = arith.constant 1.000000e+00 : f32
    %0 = memref.get_global @__constant_17x18xi32 : memref<17x18xi32>
    %1 = memref.get_global @__constant_17x18xf32 : memref<17x18xf32>
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<17x18xf32>
    affine.for %arg1 = 0 to 306 {
      %2 = affine.apply #map(%arg1)[%c18]
      %3 = affine.apply #map1(%arg1)[%c18]
      affine.store %cst, %alloc[%3, %2] : memref<17x18xf32>
    }
    return %1, %0, %alloc : memref<17x18xf32>, memref<17x18xi32>, memref<17x18xf32>
  }
}


``` 
stack trace:

```
mlir-opt: /data/szy/MLIR/llvm-release/llvm-project/mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:145: AffineMap makePermutationMap(ArrayRef<Value>, const DenseMap<Operation *, unsigned int> &): Assertion `perm[kvp.second] == getAffineConstantExpr(0, context) && "permutationMap already has an entry along dim"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt a.mlir --affine-super-vectorizer-test=vectorize-affine-loop-nest
 #0 0x00005590fd797ce8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11f2ce8)
 #1 0x00005590fd7957fe llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11f07fe)
 #2 0x00005590fd79867d SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fe98ff96420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fe98f5d300b raise /build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fe98f5b2859 abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007fe98f5b2729 get_sysdep_segment_value /build/glibc-LcI20x/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007fe98f5b2729 _nl_load_domain /build/glibc-LcI20x/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007fe98f5c3fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x0000559100095e16 mlir::makePermutationMap(mlir::Block*, llvm::ArrayRef<mlir::Value>, llvm::DenseMap<mlir::Operation*, unsigned int, llvm::DenseMapInfo<mlir::Operation*, void>, llvm::detail::DenseMapPair<mlir::Operation*, unsigned int>> const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x3af0e16)
#10 0x00005590fd8d3e0c vectorizeOneOperation(mlir::Operation*, (anonymous namespace)::VectorizationState&) SuperVectorize.cpp:0:0
#11 0x00005590fd8d3549 mlir::WalkResult llvm::function_ref<mlir::WalkResult (mlir::Operation*)>::callback_fn<vectorizeLoopNest(std::vector<llvm::SmallVector<mlir::affine::AffineForOp, 2u>, std::allocator<llvm::SmallVector<mlir::affine::AffineForOp, 2u>>>&, mlir::affine::VectorizationStrategy const&)::$_0>(long, mlir::Operation*) SuperVectorize.cpp:0:0
#12 0x00005590fd8c3228 mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x131e228)
#13 0x00005590fd8c31d7 mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x131e1d7)
#14 0x00005590fd8d1b6f vectorizeLoopNest(std::vector<llvm::SmallVector<mlir::affine::AffineForOp, 2u>, std::allocator<llvm::SmallVector<mlir::affine::AffineForOp, 2u>>>&, mlir::affine::VectorizationStrategy const&) SuperVectorize.cpp:0:0
#15 0x00005590fd8d18a2 mlir::affine::vectorizeAffineLoopNest(std::vector<llvm::SmallVector<mlir::affine::AffineForOp, 2u>, std::allocator<llvm::SmallVector<mlir::affine::AffineForOp, 2u>>>&, mlir::affine::VectorizationStrategy const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x132c8a2)
#16 0x00005591008c6353 (anonymous namespace)::VectorizerTestPass::runOnOperation() TestVectorizationUtils.cpp:0:0
#17 0x00005591006f2496 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x414d496)
#18 0x00005591006f2dc0 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x414ddc0)
#19 0x00005591006f831e auto void mlir::parallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0>(mlir::MLIRContext*, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0&&)::'lambda'(__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>&&)::operator()<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&>(__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>&&) const Pass.cpp:0:0
#20 0x00005591006f473b mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x414f73b)
#21 0x00005591006f25ef mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x414d5ef)
#22 0x00005591006f2dc0 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x414ddc0)
#23 0x00005591006f56c2 mlir::PassManager::run(mlir::Operation*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41506c2)
#24 0x00005591006edaea performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#25 0x00005591006ed73d llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#26 0x0000559100794785 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41ef785)
#27 0x00005591006e7755 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4142755)
#28 0x00005591006e79ff mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41429ff)
#29 0x00005591006e7d2e mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4142d2e)
#30 0x00005590fd776a67 main (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11d1a67)
#31 0x00007fe98f5b4083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#32 0x00005590fd7765de _start (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11d15de)
```

### PR DESCRIPTION
**Pull request by Prakhar-Dixit**
Fixes  #122227
The loop’s induction variable (%i) is used to compute two different indices via affine.apply.
And the Vectorization Assumption is Violated i.e, Each vectorized loop should contribute at most one non-invariant index.

**Minimal example crashing :**

```
#map = affine_map<(d0)[s0] -> (d0 mod s0)>
#map1 = affine_map<(d0)[s0] -> (d0 floordiv s0)>

func.func @single_loop_unrolling_2D_access_pattern(%arg0: index) -> memref<2x2xf32> {
  %c2 = arith.constant 2 : index
  %cst = arith.constant 1.0 : f32
  %alloc = memref.alloc() : memref<2x2xf32>

    affine.for %i = 0 to 4 {
      %row = affine.apply #map1(%i)[%c2]  
      %col = affine.apply #map(%i)[%c2]  
      affine.store %cst, %alloc[%row, %col] : memref<2x2xf32>
    }

    return %alloc : memref<2x2xf32>
  }
```
  
The single loop %i contributes two indices (%row and %col) to the 2D memref access.

The permutation map expects one index per vectorized loop dimension, but here one loop (%i) maps to two indices (dim=0 and dim=1).

The code detects this when trying to assign the second index (dim=1) to the same vector dimension (perm[0]).

### CODE REVIEW

**Comment by Prakhar-Dixit** [comment]
@ftynse

File: mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp [hunk 1]
```diff
@@ -141,8 +141,14 @@ static AffineMap makePermutationMap(
...
     for (unsigned dim = 0; dim < numIndices; ++dim) {
       if (!invariants.count(indices[dim])) {
-        assert(perm[kvp.second] == getAffineConstantExpr(0, context) &&
-               "permutationMap already has an entry along dim");
+        if (perm[kvp.second] != getAffineConstantExpr(0, context)) {
+          auto loopOp = cast<affine::AffineForOp>(kvp.first);
+          loopOp->emitError(
+              "loop induction variable is used in multiple indices, which is "
+              "unsupported for vectorization. Consider using nested loops "
+              "instead of a single loop with affine.apply.");
```
Comment (joker-eph) [inline mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: If this isn't invalid IR as input, why is this triggering an error instead of just not performing the transformation?

Comment (Prakhar-Dixit) [reply mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: No, this is an invalid IR as input, and therefore it's triggering an error.
Please refer to this comment where I’ve written my findings on it:
https://github.com/llvm/llvm-project/issues/122227#issuecomment-2727467097
Thanks for reviewing!

Comment (joker-eph) [reply mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: I feel I am missing something here: if this is invalid IR, then it should be a verifier test, not a vectorizer one though.

Comment (Prakhar-Dixit) [reply mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: I guess I may be a bit off in my approach. I just want to know the ideal way of emitting a user-visible diagnostic and also not performing the transformation at the same time?
Since this is the main idea behind this PR.

Comment (joker-eph) [reply mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: What about keeping the assert in the utility here, and change `lib/Dialect/Affine/Transforms/SuperVectorize.cpp` where this API is called to detect when it the condition aren't met and just ignore these loop nest that can't be vectorized?

Comment (Prakhar-Dixit) [reply mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp:149]: That seems reasonable.
Thanks for helping.

File: mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp [hunk 2]
```diff
@@ -1262,6 +1277,21 @@ static Operation *vectorizeAffineStore(AffineStoreOp storeOp,
...
+    for (Value idx : indices)
+      if (!invariants.count(idx))
+        ++nonInvariant;
+    if (nonInvariant > 1) {
+      LLVM_DEBUG(dbgs() << "\n[early-vect] Bail out: loop IV "
+                        << forOp.getInductionVar() << " drives " << nonInvariant
+                        << " indices (must be ≤1)\n");
+      return nullptr;
+    }
+  }
```
Comment (joker-eph) [inline mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp:1294]: Seems like code duplication here and above? Can you extract this in a helper function?

File: mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir [hunk 3]
```diff
@@ -9,3 +9,71 @@ func.func @unparallel_loop_reduction_unsupported(%in: memref<256x512xf32>, %out:
...
+// CHECK:           %[[VAL_1:.*]] = arith.constant 2 : index
+// CHECK:           %[[VAL_2:.*]] = arith.constant 1.000000e+00 : f32
+// CHECK:           %[[VAL_3:.*]] = memref.alloc() : memref<2x2xf32>
+// CHECK:           affine.for %[[VAL_4:.*]] = 0 to 4 {
+// CHECK:             %[[VAL_5:.*]] = affine.apply #[[$ATTR_0]](%[[VAL_4]]){{\[}}%[[VAL_1]]]
+// CHECK:             %[[VAL_6:.*]] = affine.apply #[[$ATTR_1]](%[[VAL_4]]){{\[}}%[[VAL_1]]]
+// CHECK:             affine.store %[[VAL_2]], %[[VAL_3]]{{\[}}%[[VAL_5]], %[[VAL_6]]] : memref<2x2xf32>
+// CHECK:           }
+// CHECK:           return %[[VAL_3]] : memref<2x2xf32>
+// CHECK:         }
```
Comment (joker-eph) [inline mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir:46]: What are we checking here? Can you minimize the checks please.

File: mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir [hunk 4]
```diff
@@ -9,3 +9,71 @@ func.func @unparallel_loop_reduction_unsupported(%in: memref<256x512xf32>, %out:
  }
  return
 }
+
+// -----
+
+#map = affine_map<(d0)[s0] -> (d0 mod s0)>
+#map1 = affine_map<(d0)[s0] -> (d0 floordiv s0)>
+
+func.func @single_loop_unrolling_2D_access_pattern_storeOp(%arg0: index) -> memref<2x2xf32> {
```
Comment (joker-eph) [inline mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir:18]: The name does not seems super clear about what we test.

File: mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp (hunk 2 above)
Comment (Prakhar-Dixit) [reply mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp:1294]: Yeah sure !

**Comment by Prakhar-Dixit** [comment]
@joker-eph

File: mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp [hunk 5]
```diff
@@ -1185,6 +1185,31 @@ static Value vectorizeOperand(Value operand, VectorizationState &state) {
...
 }
 
+/// Returns true if any vectorized loop IV drives more than one index.
+static bool isIVMappedToMultipleIndices(
+    ArrayRef<Value> indices,
+    const DenseMap<Operation *, unsigned> &loopToVectorDim) {
+  for (auto &kvp : loopToVectorDim) {
+    AffineForOp forOp = cast<AffineForOp>(kvp.first);
+    // Find which indices are invariant w.r.t. this loop IV.
+    auto invariants =
```
Comment (ftynse) [inline mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp:1195]: Nit: expand `auto`. In MLIR, we use `auto` when the type is obvious from the statement-level context (e.g., RHS is a cast) or very long to spell (map iterator above).

File: mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp [hunk 6]
```diff
@@ -1185,6 +1185,31 @@ static Value vectorizeOperand(Value operand, VectorizationState &state) {
...
+        affine::getInvariantAccesses(forOp.getInductionVar(), indices);
+    // Count how many vary (i.e. are not invariant).
+    unsigned nonInvariant = 0;
+    for (Value idx : indices)
+      if (!invariants.count(idx))
+        ++nonInvariant;
+    // Bail if more than one index varies for this single loop IV.
+    if (nonInvariant > 1) {
```
Comment (ftynse) [inline mlir/lib/Dialect/Affine/Transforms/SuperVectorize.cpp:1203]: Nit: you can put this check inside the `if (!invariants.count(...))` above and return immediately. Consider also inverting the check to use `continue` to reduce identitation.

File: mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir [hunk 7]
```diff
@@ -9,3 +9,34 @@ func.func @unparallel_loop_reduction_unsupported(%in: memref<256x512xf32>, %out:
...
+// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0)[s0] -> (d0 mod s0)>
+
+// CHECK-LABEL:   func.func @iv_mapped_to_multiple_indices_unsupported(
+// CHECK-SAME:      %[[VAL_0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: index) -> memref<2x2xf32> {
+// CHECK:           %[[VAL_1:.*]] = arith.constant 2 : index
+// CHECK:           affine.for %[[VAL_4:.*]] = 0 to 4 {
+// CHECK:             %[[VAL_5:.*]] = affine.apply #[[$ATTR_0]](%[[VAL_4]]){{\[}}%[[VAL_1]]]
+// CHECK:             %[[VAL_6:.*]] = affine.apply #[[$ATTR_1]](%[[VAL_4]]){{\[}}%[[VAL_1]]]
+// CHECK:           }
+// CHECK:         }
```
Comment (ftynse) [inline mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir:42]: Nit: please configure your editor to add/keep the trailing newline.

File: mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir [hunk 8]
```diff
@@ -9,3 +9,34 @@ func.func @unparallel_loop_reduction_unsupported(%in: memref<256x512xf32>, %out:
...
+    }
+    
+    return %alloc : memref<2x2xf32>
+  }
+
+// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0)[s0] -> (d0 floordiv s0)>
+// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0)[s0] -> (d0 mod s0)>
+
+// CHECK-LABEL:   func.func @iv_mapped_to_multiple_indices_unsupported(
+// CHECK-SAME:      %[[VAL_0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: index) -> memref<2x2xf32> {
```
Comment (ftynse) [inline mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir:36]: Nit: do we really need this super-complex regexp here?

**Review by ftynse — APPROVED** [review]

File: mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir (hunk 8 above)
Comment (banach-space) [reply mlir/test/Dialect/Affine/SuperVectorize/vectorize_unsupported.mlir:36]: I presume this was auto-generated by `generate-test-checks.py` -  see [#128083](https://github.com/llvm/llvm-project/pull/128083).

I agree that, in most cases, this strictness is unnecessary, and I’ve effectively reverted that behavior in [#136721](https://github.com/llvm/llvm-project/pull/136721).

Btw, I'd like to make a few more improvements to `generate-test-checks.py` if time permits.

**Review by ftynse — APPROVED** [review]
