### PR TITLE
[clang][Sema] Handle pointer and reference type more robustly in HeuristicResolver::resolveMemberExpr()

### LINKED ISSUE #124450: HeuristicResolver cannot resolve chained dependent field access
In the following code:

```c++
int next;

template <typename T>
struct Link {
  Link<T> *next;
};

template <typename T>
void foo(Link<T> *link) {
  link->next->next;
}
```

HeuristicResolver is able to resolve the first `next` in `link->next->next`, but not the second.

This can be seen in clangd: go-to-definition on the second `next` will also offer the unrelated global variable as a result, indicating that it's falling back to the textual heuristic because semantic resolution failed.

### PR DESCRIPTION
**Pull request by HighCommander4**
Fixes https://github.com/llvm/llvm-project/issues/124450

### CODE REVIEW

File: clang/lib/Sema/HeuristicResolver.cpp [hunk 1]
```diff
@@ -133,8 +133,8 @@ TemplateName getReferencedTemplateName(const Type *T) {
 CXXRecordDecl *HeuristicResolverImpl::resolveTypeToRecordDecl(const Type *T) {
   assert(T);
 
-  // Unwrap type sugar such as type aliases.
-  T = T->getCanonicalTypeInternal().getTypePtr();
+  // Unwrap references and type sugar such as type aliases.
+  T = T->getCanonicalTypeInternal().getNonReferenceType().getTypePtr();
```
Comment (zyn0217) [inline clang/lib/Sema/HeuristicResolver.cpp:137]: Does it work if `b` were a pointer?

Comment (HighCommander4) [reply clang/lib/Sema/HeuristicResolver.cpp]: In the revised version of the patch, we handle both reference and pointer types and we do it more robustly, checking for them after each step of simplification of the type.

**Comment by HighCommander4** [comment]
(The Windows buildkite failure looks unrelated.)

**Review by zyn0217 — APPROVED** [review]

**Comment by kadircet** [comment]
FWIW, i bisected a performance regression (and possibly an infinite loop) in clangd to this PR. trying to get a reproducer now.
