### PR TITLE
[lldb] Fix use-color settings not persistent

### LINKED ISSUE #22981: settings set use-color false has no effect
|  |  |
| --- | --- |
| Bugzilla Link | [22607](https://llvm.org/bz22607) |
| Version | unspecified |
| OS | FreeBSD |

## Extended Description 
At r229382 on FreeBSD-11. By default the (lldb) prompt is light gray. It remains light gray after "settings set use-color false"

### PR DESCRIPTION
**Pull request by da-viper**
Fixes https://github.com/llvm/llvm-project/issues/22981

Do you think it is necessary for the`SetUseColor` to return a bool for the interface

### CODE REVIEW

File: lldb/include/lldb/Core/IOHandler.h [hunk 1]
```diff
@@ -99,6 +99,12 @@ class IOHandler {
     // Prompt support isn't mandatory
     return false;
   }
+
+  virtual bool SetUseColor(bool use_color) {
+    // Use color isn't mandatory
```
Comment (JDevlieghere) [inline lldb/include/lldb/Core/IOHandler.h:104]:
```suggestion
    // Color support isn't mandatory.
```

**Review by JDevlieghere — APPROVED** [review]
LGTM.
