### PR TITLE
[ms] [llvm-ml] Allow PTR casting of registers to their own size

### LINKED ISSUE #132084: [ms] [llvm-ml] Allow size directives on register operands
```asm
        .CODE
        mov rsp, r11
        mov qword ptr rsp, r11
        mov rsp, qword ptr r11
        mov qword ptr rsp, qword ptr r11
        END
```

```console
$ ml64 -nologo -Cp -c -Fo test.obj -W3 test.asm
 Assembling: test.asm
$ objdump -D --section='.text$mn' test.obj

test.obj:     file format pe-x86-64


Disassembly of section .text$mn:

0000000000000000 <.text$mn>:
   0:   49 8b e3                mov    %r11,%rsp
   3:   49 8b e3                mov    %r11,%rsp
   6:   49 8b e3                mov    %r11,%rsp
   9:   49 8b e3                mov    %r11,%rsp
$ llvm-ml64 -c -Fo test.obj test.asm
test.asm:3:23: error: expected memory operand after 'ptr', found register operand instead
        mov qword ptr rsp, r11
                      ^
test.asm:4:28: error: expected memory operand after 'ptr', found register operand instead
        mov rsp, qword ptr r11
                           ^
test.asm:5:23: error: expected memory operand after 'ptr', found register operand instead
        mov qword ptr rsp, qword ptr r11
                      ^
```

Not sure if the size directive is needed here or not, but LLVM exits with a error. Microsoft's ml64 accepts the move register-to-register with a size directive. Is it 'nonsensical' to apply size directives to the register in reg-to-reg mov? Maybe LLVM should just warn rather than error on this case. 

cc @ericastor

### PR DESCRIPTION
**Pull request by ericastor**
MASM allows no-op casts on register operands; for example, `DWORD PTR eax` is a legal expression. Any other cast is an error.

Fixes #132084

### CODE REVIEW

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 1]
```diff
@@ -2577,14 +2584,40 @@ bool X86AsmParser::ParseIntelMemoryOperandSize(unsigned &Size) {
   return false;
 }
 
+uint16_t RegSizeInBits(MCRegister RegNo, const MCRegisterInfo &MRI) {
```
[the remark this answers is not in the document]
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Agreed that I'd very much like to see this defined there. But for now... swapped.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 2]
```diff
@@ -2577,14 +2584,40 @@ bool X86AsmParser::ParseIntelMemoryOperandSize(unsigned &Size) {
...
+    Size = 128;
+  else if (X86MCRegisterClasses[X86::VR128XRegClassID].contains(RegNo))
+    Size = 128;
+  else if (X86MCRegisterClasses[X86::VR256XRegClassID].contains(RegNo))
+    Size = 256;
+  else if (X86MCRegisterClasses[X86::VR512RegClassID].contains(RegNo))
+    Size = 512;
+  else
+    llvm_unreachable("Register without known register class");
+  return Size;
```
[the remark this answers is not in the document]
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Swapped to an early-return style; thanks!

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 3]
```diff
@@ -2577,14 +2584,37 @@ bool X86AsmParser::ParseIntelMemoryOperandSize(unsigned &Size) {
...
+  if (X86MCRegisterClasses[X86::GR32RegClassID].contains(RegNo))
+    return 32;
+  if (X86MCRegisterClasses[X86::GR64RegClassID].contains(RegNo))
+    return 64;
+  if (X86MCRegisterClasses[X86::RFP80RegClassID].contains(RegNo))
+    return 80;
+  if (X86MCRegisterClasses[X86::VR128RegClassID].contains(RegNo))
+    return 128;
+  if (X86MCRegisterClasses[X86::VR128XRegClassID].contains(RegNo))
+    return 128;
```
Comment (compnerd) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2601]: Does it make sense to merge these two?

```suggestion
  if (X86MCRegisterClasses[X86::VR128RegClassID].contains(RegNo) || 
      X86MCRegisterClasses[X86::VR128XRegClassID].contains(RegNo))
    return 128;
```

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 4]
```diff
@@ -2569,6 +2574,8 @@ bool X86AsmParser::ParseIntelMemoryOperandSize(unsigned &Size) {
     .Cases("ZMMWORD", "zmmword", 512)
     .Default(0);
   if (Size) {
+    if (SizeStr)
+      *SizeStr = getTok().getString();
```
Comment (compnerd) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2578]: This gets the raw token spelling right? The use of that for the diagnostics seems less than ideal (IIRC Microsoft doesn't treat the tokens as case sensitive).

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 5]
```diff
@@ -2601,9 +2631,20 @@ bool X86AsmParser::parseIntelOperand(OperandVector &Operands, StringRef Name) {
...
+                              "found register operand instead");
+
+        // If we are parsing MASM, we are allowed to cast registers to their own
+        // sizes, but not to other types.
+        if (RegSizeInBits(*getContext().getRegisterInfo(), RegNo) != Size)
+          return Error(
+              Start,
+              "cannot cast register '" +
+                  StringRef(getContext().getRegisterInfo()->getName(RegNo)) +
+                  "' to '" + SizeStr + "'; size does not match");
```
Comment (compnerd) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2646]: I wonder if the size class in the diagnostic message is helpful. I don't think that
```
cannot cast register 'AL' to 'word'; size does not match
```
is particularly helpful. Perhaps something more along the lines of:
```
8-bit GPR 'AX' cannot be used as a 32-bit GPR
```

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 3 above)
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2601]: Done.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 4 above)
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2578]: Agreed; I'm still pulling out the StringRef for the token, but I've switched the diagnostic to print the upper-case version as a standardization step.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 5 above)
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: I still think the size class is helpful to MASM users. However, I've added a bit-width specification to the diagnostic. WDYT?

Comment (compnerd) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: I wouldn't mind getting a second opinion on the diagnostic that we emit.

**Review by AaronBallman — COMMENTED** [review]
FWIW, the diagnostic text looks reasonable to me.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp [hunk 6]
```diff
@@ -2577,14 +2584,36 @@ bool X86AsmParser::ParseIntelMemoryOperandSize(unsigned &Size) {
...
+  if (X86MCRegisterClasses[X86::GR16RegClassID].contains(RegNo))
+    return 16;
+  if (X86MCRegisterClasses[X86::GR32RegClassID].contains(RegNo))
+    return 32;
+  if (X86MCRegisterClasses[X86::GR64RegClassID].contains(RegNo))
+    return 64;
+  if (X86MCRegisterClasses[X86::RFP80RegClassID].contains(RegNo))
+    return 80;
+  if (X86MCRegisterClasses[X86::VR128RegClassID].contains(RegNo) ||
+      X86MCRegisterClasses[X86::VR128XRegClassID].contains(RegNo))
```
Comment (phoebewang) [inline llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2599]: VR128RegClassID is a subset of X86::VR128XRegClassID, checking the latter is enough. However, we cannot deduce the size of a XMM register, because it can be f16/f32/f64 or a 128-bit vector.

Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2599]: That's a good point, and I'm not entirely sure how MASM handles it for the purposes of this "no-op PTR cast" handling. Is it true for any of the other vector registers, or just the XMM set?

Once I understand that, I think I should (for now) restrict this no-op PTR cast support to only the registers where we can clearly deduce the size correctly. We can extend it if we find cases where MASM actually handles this.

Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2599]: I don't think we can simply get the exact information. That's why AT&T syntax uses size prefix and Intel syntax uses `ptr` modifier.

BTW, what to do with instructions only have memory operand or the other operand is an immediate value?

Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2599]: Sorry, I wasn't clear; I meant could you help by saying which registers don't have deducible size? Is it all the vector registers, just the XMM set, etc.?

In terms of instructions that have non-register operands - MASM allows casting on these already. It's just the register operands that MASM (unusually) allows casts on as long as they don't actually change the size in any way.

Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:2599]: XMM is the biggest trouble since you can't tell it's a scalar FP or vector. However, YMM/ZMM have size problem in some instructions too, e.g.,

```
vcvtpd2ps ymm0, zmmptr rax
vcvtps2pd zmm0, ymmptr rax
```

OTOH, I don't see a size mismatch in GPR instructions so far. So would be good to limit to GPR only.

File: llvm/test/tools/llvm-ml/cast.asm [hunk 7]
```diff
@@ -0,0 +1,25 @@
+; RUN: llvm-ml -m64 -filetype=s %s /Fo - | FileCheck %s
```
Comment (MaskRay) [inline llvm/test/tools/llvm-ml/cast.asm:1]: (I am travelling with limited computer access until May 4th, and my response time may be delayed..)

I am not familiar with llvm-ml parsing, does this exercise the object generation code path (MCObjectStreamer)? If not, this might not usefully test the X86AsmParser.cpp changes.

File: llvm/test/tools/llvm-ml/cast_errors.asm [hunk 8]
```diff
@@ -0,0 +1,41 @@
+; RUN: not llvm-ml -m64 -filetype=s %s /Fo /dev/null 2>&1 | FileCheck %s
+
+.code
+
+mov word ptr al, ax
+; CHECK: error: 8-bit register 'AL' cannot be used as a 16-bit WORD
```
Comment (MaskRay) [inline llvm/test/tools/llvm-ml/cast_errors.asm:6]: For errors, test line/column information like `[[#@LINE-1]:5: error:`. You might git log how I improve/refactor `llvm/test/MC/` tests.

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 6 above)
Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Updated to exclude all of the vector registers, but include the TBYTE registers.

File: llvm/test/tools/llvm-ml/cast_errors.asm (hunk 8 above)
Comment (ericastor) [reply llvm/test/tools/llvm-ml/cast_errors.asm]: Done!

File: llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp (hunk 6 above)
Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: RFP80 is used for pseudo instructions during codegen phase. In the assembly, there's no instrucrtion has both register operand and memory operand.

Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Apologies - but does this mean we can't know what size these registers are? (It's not about the contents in this case, just the size.)

Comment (phoebewang) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Right. MS's ml cannot handle it either, e.g., `fld [rsp + 4]`.

Comment (ericastor) [reply llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp]: Removed, then. Thanks!

**Comment by MisterDA** [comment]
Gentle ping! IIUC this PR has been reviewed and approved, is it just a rebase away from being merged?

**Comment by nikic** [comment]
> > Not sure what's going on here, but this change increases the ThinLTO link time for clang by 2.5% (https://llvm-compile-time-tracker.com/compare_clang.php?from=40edc34782b3a804639042c2981c3c4ae6661a92&to=344708c2a3de005060242a77ccfea753406af8d0&stat=instructions%3Au&sortBy=interestingness).
> 
> All I can think is that we brought in `"X86RegisterInfo.h"`? But that doesn't seem like it should be dramatic.

I've checked that it's not the header. I expect that something in this change is exposing pathological behavior in LLVM.
