### PR TITLE
[Clang] Show inlining hints for __attribute__((warning/error))

### LINKED ISSUE #1571: Report inlining location when using __attribute__((__warning__(msg)))
When `__warning__(msg)` reports from usage within an inline, there's no information about where the inline was used. For example:

gcc says `inlined from 'main' at /app/example.c`

```
In file included from /app/example.c:5:
In function 'indirection',
    inlined from 'main' at /app/example.c:9:5:
example.h:6:9: error: call to '__write_overflow' declared with attribute warning: eek [-Werror=attribute-warning]
    6 |         __write_overflow();
      |         ^~~~~~~~~~~~~~~~~~
```

Clang doesn't include that hint:
```
In file included from /app/example.c:5:
example.h:6:9: error: call to __write_overflow declared with 'warning' attribute: eek [-Werror,-Wattribute-warning]
        __write_overflow();
        ^
```

https://godbolt.org/z/W9PjxsE6z

Which makes FORTIFY_SOURCE warnings much harder to find. :)

```
In file included from net/mptcp/protocol.c:10:
In file included from ./include/linux/module.h:13:
In file included from ./include/linux/stat.h:19:
In file included from ./include/linux/time.h:60:
In file included from ./include/linux/time32.h:13:
In file included from ./include/linux/timex.h:65:
In file included from ./arch/x86/include/asm/timex.h:5:
In file included from ./arch/x86/include/asm/processor.h:22:
In file included from ./arch/x86/include/asm/msr.h:11:
In file included from ./arch/x86/include/asm/cpumask.h:5:
In file included from ./include/linux/cpumask.h:12:
In file included from ./include/linux/bitmap.h:11:
In file included from ./include/linux/string.h:253:
./include/linux/fortify-string.h:230:4: warning: call to __write_overflow_field declared with 'warning' attribute: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Wattribute-warning]
                        __write_overflow_field(p_size_field, size);
                        ^
```

### PR DESCRIPTION
**Pull request by JustinStitt**
When functions marked with `[[gnu::warning/error]]` are called through inlined functions, we now show the inlining chain that led to the call when ``-fdiagnostics-show-inlining-chain`` is enabled.

With this flag, two modes are possible:

- **heuristic** mode: Uses `srcloc` and `inlined.from` metadata to reconstruct the inlining chain. Functions that are `inline`, `static`, `always_inline`, or in anonymous namespaces get `srcloc` metadata attached. This mode emits a note suggesting `-gline-directives-only` for more accurate locations.

- **debug** mode: Automatically used instead of heuristic when building with at least `-gline-directives-only` (implied by `-g1` or higher). Leverages `DILocation` debug info for reliable source locations.

Fixes: https://github.com/ClangBuiltLinux/linux/issues/1571

---

To demonstrate this, here's the simplest example:

```c
$ cat -n test.c
   1 [[gnu::warning("foo")]]
   2 void foo(void);
   3
   4 static inline void bar(int x) {
   5     if (x == 10)
   6         foo();
   7 }
   8
   9 void baz() {
  10     bar(10);
  11 }
  12
  13 void quux() {
  14     bar(9);
  15 }
`` 

<details>
<summary>Before (clang trunk)</summary>
<pre>
<code>
$ clang test.c -O2 -Wall

test.c:6:9: warning: call to 'foo' declared with 'warning' attribute: foo [-Wattribute-warning]
    6 |         foo();
      |         ^
1 warning generated.
</code>
</pre>
</details>

<details>
<summary>After (this PR)</summary>
<pre>
<code>
$ clang test.c -O2 -Wall

test.c:6:9: warning: call to 'foo' declared with 'warning' attribute: foo [-Wattribute-warning]
    6 |         foo();
      |         ^
test.c:6:9: note: called by function 'bar'
test.c:10:5: note: inlined by function 'baz'
   10 |     bar(10);
      |     ^
note: use '-gline-directives-only' (implied by '-g1' or higher) for more accurate inlining chain locations
1 warning generated.
</code>
</pre>
</details>

This proves especially useful when there are multiple calls to one of these dontcalls:
```c
$ cat -n test2.h

   1 void __write_overflow(void) [[gnu::warning("eek")]];
   2
   3 static inline void indirection(int x)
   4 {
   5     if (__builtin_constant_p(x) && x > 10)
   6         __write_overflow();
   7     else
   8         printf("safe\n");
   9 }
  10
  11 #define do_something(x)  indirection(x)


$ cat -n test2.c

   1 #include <stdio.h>
   2 #include <stdint.h>
   3 #include <stdlib.h>
   4 #include <limits.h>
   5 #include "test2.h"
   6
   7 void foo() {
   8     do_something(11);
   9
  10     do_something(12);
  11
  12     do_something(4);
  13
  14     do_something(99);
  15 }
  16
  17 int bar();
  18
  19 int main(int argc, char *argv[])
  20 {
  21     do_something(11);
  22
  23     bar();
  24
  25     return 0;
  26 }

```

<details>
<summary>Before (clang trunk)</summary>
<pre>
<code>
$ clang test2.c -O2 -Wall
In file included from test2.c:5:
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
    6 |         __write_overflow();
      |         ^
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
4 warnings generated.
</code>
</pre>
</details>

<details>
<summary>After (this PR)</summary>
<pre>
<code>
$ clang test2.c -O2 -Wall

./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
    6 |         __write_overflow();
      |         ^
./test2.h:6:9: note: called by function 'indirection'
test2.c:8:5: note: inlined by function 'foo'
    8 |     do_something(11);
      |     ^
./test2.h:11:26: note: expanded from macro 'do_something'
   11 | #define do_something(x)  indirection(x)
      |                          ^
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
    6 |         __write_overflow();
      |         ^
./test2.h:6:9: note: called by function 'indirection'
test2.c:10:5: note: inlined by function 'foo'
   10 |     do_something(12);
      |     ^
./test2.h:11:26: note: expanded from macro 'do_something'
   11 | #define do_something(x)  indirection(x)
      |                          ^
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
    6 |         __write_overflow();
      |         ^
./test2.h:6:9: note: called by function 'indirection'
test2.c:14:5: note: inlined by function 'foo'
   14 |     do_something(99);
      |     ^
./test2.h:11:26: note: expanded from macro 'do_something'
   11 | #define do_something(x)  indirection(x)
      |                          ^
./test2.h:6:9: warning: call to '__write_overflow' declared with 'warning' attribute: eek [-Wattribute-warning]
    6 |         __write_overflow();
      |         ^
./test2.h:6:9: note: called by function 'indirection'
test2.c:21:5: note: inlined by function 'main'
   21 |     do_something(11);
      |     ^
./test2.h:11:26: note: expanded from macro 'do_something'
   11 | #define do_something(x)  indirection(x)
      |                          ^
4 warnings generated.
</code>
</pre>
</details>

You can see that with the inlining hints it is now much more clear which calls actually end up calling the warning/error-annotated methods.

I ran benchmarks building a defconfig+CONFIG_FORTIFY_SOURCE x86_64 Linux kernel multiple times with each mode:
`none` (baseline): 82.717 s avg
`heuristic`: 82.724 s avg
`debug`: 83.404 s avg

Note that these wall time averages are probably not that reliable.

---

This PR is a spiritual revival of https://github.com/llvm/llvm-project/pull/73552 which seemed to kind of die out as Nick moved on to other things paired with reviewers wanting different implementations.

I polished off the bitrot from Nick's original draft PR and read the various RFCs https://reviews.llvm.org/D141451#inline-1445409 and https://discourse.llvm.org/t/rfc-improving-clangs-middle-and-back-end-diagnostics/69261/17 to inform this current implementation.

### CC's based on previous involvement with Nick's pr
@cc @kees @nickdesaulniers @dwblaikie @erichkeane

### CODE REVIEW

File: clang/include/clang/Basic/CodeGenOptions.h [hunk 1]
```diff
@@ -120,6 +120,14 @@ class CodeGenOptions : public CodeGenOptionsBase {
     Embed_Marker    // Embed a marker as a placeholder for bitcode.
   };
 
+  /// Inlining chain tracking __attribute__((warning)) or __attribute__((error))
+  /// diagnostics
+  enum InliningChainKind {
```
Comment (erichkeane) [inline clang/include/clang/Basic/CodeGenOptions.h]: Can we do a scoped enum here instead?

**Review by erichkeane — COMMENTED** [review]
I'd like to give others a chance to take a look, but I don't really see anything in the Clang side that i have concerns about.  So this is more or less a LGTM barring further discussion.  We definitely need more reviewers than I though.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -348,6 +348,12 @@ New Compiler Flags
 - New options for enabling allocation token instrumentation: ``-fsanitize=alloc-token``, ``-falloc-token-max=``, ``-fsanitize-alloc-token-fast-abi``, ``-fsanitize-alloc-token-extended``.
 - The ``-resource-dir`` option is now displayed in the list of options shown by ``--help``.
 - New option ``-fmatrix-memory-layout`` added to control the memory layout of Clang matrix types. (e.g. ``-fmatrix-memory-layout=column-major`` or ``-fmatrix-memory-layout=row-major``).
+- New option ``-fdiagnostics-show-inlining-chain=`` added to show inlining chain
+  notes for ``__attribute__((warning))`` and ``__attribute__((error))``
```
Comment (nickdesaulniers) [inline clang/docs/ReleaseNotes.rst]: Man, C23 standardized the C++20 syntax for attributes, which uses `[[]]`. Let's use the standard syntax, throughout this PR? `[[gnu::warning]]`

File: clang/lib/Frontend/CompilerInvocation.cpp [hunk 3]
```diff
@@ -2253,6 +2253,14 @@ bool CompilerInvocation::ParseCodeGenArgs(CodeGenOptions &Opts, ArgList &Args,
       Opts.getDebugInfo() == llvm::codegenoptions::NoDebugInfo)
     Opts.setDebugInfo(llvm::codegenoptions::LocTrackingOnly);
 
+  // Debug mode for inlining chain diagnostics requires at least
+  // -gline-directives-only to track inlining locations via DILocation.
+  if (Opts.getInliningChain() == CodeGenOptions::Inlining_Debug &&
+      Opts.getDebugInfo() < llvm::codegenoptions::DebugDirectivesOnly) {
+    Diags.Report(diag::warn_fe_inlining_debug_requires_g);
+    Opts.setInliningChain(CodeGenOptions::Inlining_Heuristic);
+  }
```
Comment (nickdesaulniers) [inline clang/lib/Frontend/CompilerInvocation.cpp]: Maybe it would be better to emit a Note diagnostic on the -Wwarning diagnostics if `FD->getStorageClass() == SC_Static` that enabling `-gline-directives-only` (or higher level debug flags) can provide additional info?

**Review by nickdesaulniers — COMMENTED** [review]
> Q) Why have three modes?
A) Fully re-purposing the debug info architecture for inline tracing requires at least -gline-directives-only (I believe.) which is probably not something everyone wants by default. A heuristic approach is the middle ground and of course none matches the current clang behavior without this PR.

Hmm...I think we can improve the ergonomics here a little bit.  I feel like it should be possible to have 2 modes instead of three.  Like in CGCall if `-gline-directives-only` or higher is set, then we can elide the `srcloc`. Then when a dontcall is triggered we scan for (possibly absent) debug info. If that doesn't exist, fall back to looking for `srcloc`.  idk, something just feels off about a ternary flag, with a second flag required to use one of the the three states.  Most flags are binary, and perhaps the tacked on note diagnostic that says "enable debug info for additional information" is palatable and simpler for users?

File: clang/include/clang/Basic/AttrDocs.td [hunk 4]
```diff
@@ -8397,6 +8397,13 @@ pointing to precise locations of the call site in the source.
       dontcall(); // No Warning
     sizeof(dontcall()); // No Warning
   }
+
+When the call occurs through inlined functions, the
+``-fdiagnostics-show-inlining-chain=`` option can be used to show the
+inlining chain that led to the call. This helps identify which call site
+triggered the diagnostic when the attributed function is called from
+multiple locations through inline functions. See ``clang --help`` for
+available modes.
```
Comment (nickdesaulniers) [inline clang/include/clang/Basic/AttrDocs.td]: I don't think we want our HTML docs to say "run `clang --help` for the options."  This is our official docs, spell them out!!!

Comment (JustinStitt) [reply clang/include/clang/Basic/AttrDocs.td]: Makes sense :)

fixed with [`e866945` (#174892)](https://github.com/llvm/llvm-project/pull/174892/commits/e866945f1c61774e745ec3a793629104ef473fee)

File: clang/lib/CodeGen/CGCall.cpp [hunk 5]
```diff
@@ -6048,13 +6048,22 @@ RValue CodeGenFunction::EmitCall(const CGFunctionInfo &CallInfo,
...
+  // Add srcloc metadata for __attribute__((error/warning)) diagnostics.
+  // In heuristic mode, also track inline/static calls for inlining chain.
+  if (TargetDecl) {
+    bool NeedSrcLoc = TargetDecl->hasAttr<ErrorAttr>();
+    if (!NeedSrcLoc && CGM.getCodeGenOpts().getInliningChain() ==
+                           CodeGenOptions::Inlining_Heuristic) {
+      if (const auto *FD = dyn_cast<FunctionDecl>(TargetDecl))
+        NeedSrcLoc = FD->isInlined() || FD->isInlineSpecified() ||
+                     FD->hasAttr<AlwaysInlineAttr>() ||
+                     FD->getStorageClass() == SC_Static;
```
[the remark this answers is not in the document]
Comment (JustinStitt) [reply clang/lib/CodeGen/CGCall.cpp]: Since methods inside of an anonymous namespace are pretty likely to be inlined at -O2 I've added them to the heuristic in e866945f1c61774e745ec3a793629104ef473fee. thanks

File: clang/include/clang/Basic/CodeGenOptions.h (hunk 1 above)
Comment (JustinStitt) [reply clang/include/clang/Basic/CodeGenOptions.h]: Sounds good to me. PTAL e866945f1c61774e745ec3a793629104ef473fee

File: clang/lib/CodeGen/CGCall.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (nickdesaulniers) [reply clang/lib/CodeGen/CGCall.cpp]: Please add a .cpp file unit test testing the behavior of callees declared in anonymous namespaces, to prove to reviewers this works as intended in C++ mode.

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -348,6 +348,13 @@ New Compiler Flags
 - New options for enabling allocation token instrumentation: ``-fsanitize=alloc-token``, ``-falloc-token-max=``, ``-fsanitize-alloc-token-fast-abi``, ``-fsanitize-alloc-token-extended``.
 - The ``-resource-dir`` option is now displayed in the list of options shown by ``--help``.
 - New option ``-fmatrix-memory-layout`` added to control the memory layout of Clang matrix types. (e.g. ``-fmatrix-memory-layout=column-major`` or ``-fmatrix-memory-layout=row-major``).
+- New option ``-fdiagnostics-show-inlining-chain`` added to show inlining chain
+  notes for ``[[gnu::warning]]`` and ``[[gnu::error]]`` diagnostics. When a
+  function with these attributes is called from an inlined context, Clang can
+  now show which functions were inlined to reach the call. When debug info is
+  available (``-gline-directives-only`` or higher), accurate source locations
```
Comment (nickdesaulniers) [inline clang/docs/ReleaseNotes.rst]: If you use `diagtool tree`, you'll get a printout of the hierarchy of diagnostic group flags from clang. I assume that `-gline-directives-only` is implicitly enabled at `-g1` (and higher).  Verify that assumption; if it holds, it might be worth adding:

```suggestion
  available (``-gline-directives-only`` (implicitly enabled at ``-O1``)) or higher), accurate source locations
```

File: clang/lib/CodeGen/CGCall.cpp [hunk 7]
```diff
@@ -6048,13 +6048,23 @@ RValue CodeGenFunction::EmitCall(const CGFunctionInfo &CallInfo,
...
-    llvm::MDTuple *MDT = llvm::MDNode::get(getLLVMContext(), {MD});
-    CI->setMetadata("srcloc", MDT);
+  // Add srcloc metadata for [[gnu::error/warning]] diagnostics.
+  // When ShowInliningChain is enabled, also track inline/static calls for the
+  // heuristic fallback when debug info is not available.
+  if (TargetDecl) {
+    bool NeedSrcLoc = TargetDecl->hasAttr<ErrorAttr>();
+    if (!NeedSrcLoc && CGM.getCodeGenOpts().ShowInliningChain) {
+      if (const auto *FD = dyn_cast<FunctionDecl>(TargetDecl))
+        NeedSrcLoc = FD->isInlined() || FD->isInlineSpecified() ||
```
Comment (nickdesaulniers) [inline clang/lib/CodeGen/CGCall.cpp]: Just curious, what does `isInlined` _mean_ for a `FunctionDecl`?

File: clang/lib/CodeGen/CGCall.cpp [hunk 8]
```diff
@@ -6048,13 +6048,23 @@ RValue CodeGenFunction::EmitCall(const CGFunctionInfo &CallInfo,
...
-    llvm::ConstantInt *Line =
-        llvm::ConstantInt::get(Int64Ty, Loc.getRawEncoding());
-    llvm::ConstantAsMetadata *MD = llvm::ConstantAsMetadata::get(Line);
-    llvm::MDTuple *MDT = llvm::MDNode::get(getLLVMContext(), {MD});
-    CI->setMetadata("srcloc", MDT);
+  // Add srcloc metadata for [[gnu::error/warning]] diagnostics.
+  // When ShowInliningChain is enabled, also track inline/static calls for the
+  // heuristic fallback when debug info is not available.
+  if (TargetDecl) {
+    bool NeedSrcLoc = TargetDecl->hasAttr<ErrorAttr>();
```
Comment (nickdesaulniers) [inline clang/lib/CodeGen/CGCall.cpp]: Do we need to check `WarningAttr`, too?

File: clang/lib/Frontend/CompilerInvocation.cpp (hunk 3 above)
Comment (nickdesaulniers) [reply clang/lib/Frontend/CompilerInvocation.cpp]: > it can get a bit noisy when there are multiple diagnostics.

I'm ok with that. If your code emits multiple instances of _any_ diagnostic that additionally has a note attached, clang generally doesn't dedup the notes IIRC, so that's in line with the status quo.

File: clang/lib/CodeGen/CGCall.cpp (hunk 7 above)
Comment (JustinStitt) [reply clang/lib/CodeGen/CGCall.cpp]: You mean when compared to `isInlineSpecified`? I think `isInlined` is a broader check encompassing `isInlineSpecified` (which checks for explicit inline keyword) and other criteria likely to result in a method being inlined. I put both here because I don't know the exact differences and I got better results (especially with C++ code) with both included in the heuristic.

File: clang/docs/ReleaseNotes.rst (hunk 6 above)
Comment (JustinStitt) [reply clang/docs/ReleaseNotes.rst]: Good suggestion, I took it in 38e8f6dade4a72c05106a46fbe7df6ed3b311fe6 but dropped the extraneous paren. thanks

File: clang/docs/ReleaseNotes.rst [hunk 9]
```diff
@@ -348,6 +348,13 @@ New Compiler Flags
 - New options for enabling allocation token instrumentation: ``-fsanitize=alloc-token``, ``-falloc-token-max=``, ``-fsanitize-alloc-token-fast-abi``, ``-fsanitize-alloc-token-extended``.
 - The ``-resource-dir`` option is now displayed in the list of options shown by ``--help``.
 - New option ``-fmatrix-memory-layout`` added to control the memory layout of Clang matrix types. (e.g. ``-fmatrix-memory-layout=column-major`` or ``-fmatrix-memory-layout=row-major``).
+- New option ``-fdiagnostics-show-inlining-chain`` added to show inlining chain
+  notes for ``[[gnu::warning]]`` and ``[[gnu::error]]`` diagnostics. When a
+  function with these attributes is called from an inlined context, Clang can
+  now show which functions were inlined to reach the call. When debug info is
+  available (``-gline-directives-only`` (implicitly enabled at ``-g1``) or
```
Comment (nickdesaulniers) [inline clang/docs/ReleaseNotes.rst]: I think you should copy the `-g1` hint to the AttrDocs.td below. It's more useful there than in the release notes (happy to see it in _both_ places).

**Comment by nickdesaulniers** [comment]
I'd be curious @AaronBallman 's thoughts on having note diagnostics like this where the note encourages you to enable debug info for better (more precise) diagnostics. I don't think there's _any_ prior art in Clang here.

If @AaronBallman is cool with the idea, then towards the goal of improved ergonomics, I'd be curious if we could push further and not even have/add `-fdiagnostics-show-inlining-chain` at all; attach the note on instances of `-Werror`/`-Wwarning` that `-gline-directives-only` (and higher) can give you additional info (hopefully the presence of debug info doesn't change inlining decisions :P).

If @AaronBallman is not cool with the idea, then I think this PR has to be scuttled.

Previously @AaronBallman has expressed that diagnostics should not differ between optimization levels.  I think there's a subtle difference here; for _backend_ diagnostics, encouraging the user to enable debug info can add additional/helpful notes, in this case for potentially stopping buffer overflows _known at compile time_ (for the Linux kernel's implementation of FORTIFY_SOURCE) for which clang is currently _strictly worse than GCC here_.

@AaronBallman what are your thoughts here?

**Comment by nickdesaulniers** [comment]
I think @dwblaikie also expressed similar sentiments (or perhaps I'm mixing up a conversation I had with David with Aaron, IDK). Anyways, all feedback welcome here.

**Comment by efriedma-quic** [comment]
> Previously @AaronBallman has expressed that diagnostics should not differ between optimization levels. I think there's a subtle difference here; for backend diagnostics, encouraging the user to enable debug info can add additional/helpful notes, in this case for potentially stopping buffer overflows known at compile time (for the Linux kernel's implementation of FORTIFY_SOURCE) for which clang is currently strictly worse than GCC here.

The notion of diagnosing buffer overflows at compile-time sounds great, but doing it in the backend has practical problems... among other issues, we've had multiple bug reports that boiled down to "a false-positive diagnostic triggered because of a missed optimization" . Anyway, that's only indirectly related to this patch.

I don't think modifying the text of the notes based on information we have available will cause any practical issues.  The consistency issue is mostly about whether the primary diagnostic is consistent.

**Comment by JustinStitt** [comment]
an aside, is [this buildbot failure](https://github.com/llvm/llvm-project/pull/174892#issuecomment-3740884157) relevant? I guess I touched `llvm/include/llvm/IR/DiagnosticInfo.h` which includes `BranchProbability.h` and `SourceMgr.h` (and, transitively, `User.h`) but those `LLVM_ABI` annotations were missing before I got here :)

Also, those includes it wants in the diff seem off. Shouldn't we be including without the `llvm/include` prefix?
```diff
-#include "llvm/include/llvm/Support/Compiler.h"
+#include "llvm/Support/Compiler.h"
````

**Comment by AaronBallman** [comment]
> I'd be curious @AaronBallman 's thoughts on having note diagnostics like this where the note encourages you to enable debug info for better (more precise) diagnostics. I don't think there's _any_ prior art in Clang here.
> 
> If @AaronBallman is cool with the idea, then towards the goal of improved ergonomics, I'd be curious if we could push further and not even have/add `-fdiagnostics-show-inlining-chain` at all; attach the note on instances of `-Werror`/`-Wwarning` that `-gline-directives-only` (and higher) can give you additional info (hopefully the presence of debug info doesn't change inlining decisions :P).
> 
> If @AaronBallman is not cool with the idea, then I think this PR has to be scuttled.
> 
> Previously @AaronBallman has expressed that diagnostics should not differ between optimization levels. I think there's a subtle difference here; for _backend_ diagnostics, encouraging the user to enable debug info can add additional/helpful notes, in this case for potentially stopping buffer overflows _known at compile time_ (for the Linux kernel's implementation of FORTIFY_SOURCE) for which clang is currently _strictly worse than GCC here_.
> 
> @AaronBallman what are your thoughts here?

I'm still strongly opposed to diagnostics which depend on optimization levels; that's a poor user experience because you build locally (in say debug mode) and everything is fine and then you commit and a post-commit build bot running in a release mode suddenly starts to complain. But this is about "top-level" diagnostics; e.g., whether you get the warning or the error *at all*.

This PR is about attaching notes to a top-level diagnostic, so it's a different ball of wax. So long as the top-level diagnostic is correct, I think it's fine to add additional contextual information as notes when the command line options allows us to do so. The user still gets the important (correct) diagnostic regardless of command line flags, it's just a matter of how much extra detail they're presented with.

**Comment by nickdesaulniers** [comment]
Cool, then it sounds to me like @AaronBallman and @efriedma-quic are cool with this approach.

In that case, @JustinStitt WDYT about just attaching the note about `-gline-directives-only` to WarningAttr (and thus eliding the addition of `-fdiagnostics-show-inlining-chain`?

With that landed, we could re-asses if `-fdiagnostics-show-inlining-chain` would still be handy, after we've had instances where we confronted such inlining-related failures in the Linux kernel when building with clang?

i.e.:
1. add the note
2. wait for instances where clang spots such issues at compile time in the linux kernel
3. determine if `-gline-directives-only` is sufficient to precisely locate the failure.
4. if not, re-evaluate adding `-fdiagnostics-show-inlining-chain`

I recognize that kernel CI can just always enable `-fdiagnostics-show-inlining-chain`, but I also feel like the number of times this problem crops up is rare (though, I've been "out of the game" for a while now) and `-Wwarning`/`-Werror` and inlining is not generally tied to stopping buffer overflows (but is for the Linux kernel's implementation of FORTIFY_SOURCE). i.e. `-fdiagnostics-show-inlining-chain` feels only useful to one codebase (for an optional configuration of it).  And this minimizes the number of additional flags necessary to debug when this crops again.

**Comment by JustinStitt** [comment]
@AaronBallman 
> That's what I was envisioning as well


After removing the flag and running the test I now believe that we should keep the flag but just have it on by default. This is because there's a WHOLE BUNCH of llvm IR tests that are not expecting to see my `srcloc` metadata and I'd love to specify ``-fno-diagnostics-show-inlining-chain`` on those tests.

I guess the two options are 1) update all the tests, 2) add `-fno...` to them

Thoughts?

File: clang/test/CodeGenCXX/inheriting-constructor-cleanup.cpp [hunk 10]
```diff
@@ -37,7 +37,7 @@ void f() {
   // EXCEPTIONS: %[[TMP1:.*]] = alloca %struct.S1
   // EXCEPTIONS: %[[TMP2:.*]] = alloca %struct.S2
   // EXCEPTIONS: invoke void (ptr, ptr, ptr, ptr, ...) @_ZN4BaseC2ERK2S1RK2S2PKcz(ptr {{.*}}, ptr noundef nonnull align 1 dereferenceable(1) %[[TMP1]], ptr noundef nonnull align 1 dereferenceable(1) %[[TMP2]], ptr {{.*}})
-  // EXCEPTIONS-NEXT: to label %[[CONT:.*]] unwind label %[[LPAD:.*]]
+  // EXCEPTIONS-NEXT: to label %[[CONT:.*]] unwind label %[[LPAD:.*]], !srcloc
```
Comment (bwendling) [inline clang/test/CodeGenCXX/inheriting-constructor-cleanup.cpp]: Is `!srcloc` part of your changes? If not, then this and the other tests with similar changes, could be reverted.

**Review by AaronBallman — COMMENTED** [review]
Clang bits LGTM but I'd appreciate some more eyes on the codegen and LLVM parts before landing.

File: llvm/lib/IR/DiagnosticInfo.cpp [hunk 11]
```diff
@@ -484,8 +484,27 @@ void llvm::diagnoseDontCall(const CallInst &CI) {
...
+
+      if (const DebugLoc &DL = CI.getDebugLoc()) {
+        SmallVector<DebugInlineInfo, 4> DebugChain;
+        auto AddLocation = [&](const DILocation *Loc) {
+          if (auto *Scope = Loc->getScope())
+            if (auto *SP = Scope->getSubprogram())
+              DebugChain.push_back({SP->getName(), Loc->getFilename(),
+                                    Loc->getLine(), Loc->getColumn()});
+        };
+        if (const DILocation *Loc = DL.get()) {
```
Comment (bwendling) [inline llvm/lib/IR/DiagnosticInfo.cpp]: Because of the check at 491, it looks like `DL.get()` can only return a non-null pointer here.

File: clang/lib/CodeGen/CGCall.cpp [hunk 12]
```diff
@@ -6064,13 +6064,23 @@ RValue CodeGenFunction::EmitCall(const CGFunctionInfo &CallInfo,
...
-    llvm::ConstantInt *Line =
-        llvm::ConstantInt::get(Int64Ty, Loc.getRawEncoding());
-    llvm::ConstantAsMetadata *MD = llvm::ConstantAsMetadata::get(Line);
-    llvm::MDTuple *MDT = llvm::MDNode::get(getLLVMContext(), {MD});
-    CI->setMetadata("srcloc", MDT);
+  // Add srcloc metadata for [[gnu::error/warning]] diagnostics. Track
+  // inline/static calls for the heuristic fallback when debug info is not
+  // available. This heuristic is conservative and best-effort since static or
+  // inline-annotated functions are still not guaranteed to be inlined.
+  if (TargetDecl) {
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGCall.cpp]: Should we be checking if debug info is enabled before we go down this codepath?

**Review by bwendling — COMMENTED** [review]
The LLVM bits looks sensible to me. Just a little nit.

File: clang/include/clang/Options/Options.td [hunk 13]
```diff
@@ -2168,10 +2168,12 @@ defm diagnostics_show_option : BoolFOption<"diagnostics-show-option",
...
-defm diagnostics_show_note_include_stack : BoolFOption<"diagnostics-show-note-include-stack",
-    DiagnosticOpts<"ShowNoteIncludeStack">, DefaultFalse,
-    PosFlag<SetTrue, [], [ClangOption], "Display include stacks for diagnostic notes">,
-    NegFlag<SetFalse>, BothFlags<[], [ClangOption, CC1Option]>>;
+defm diagnostics_show_note_include_stack
+    : BoolFOption<"diagnostics-show-note-include-stack",
+                  DiagnosticOpts<"ShowNoteIncludeStack">, DefaultFalse,
+                  PosFlag<SetTrue, [], [ClangOption],
+                          "Display include stacks for diagnostic notes">,
+                  NegFlag<SetFalse>, BothFlags<[], [ClangOption, CC1Option]>>;
```
[the remark this answers is not in the document]
Comment (JustinStitt) [reply clang/include/clang/Options/Options.td]: `git-clang-format` picked it up, not sure why. Should I revert that change?

File: clang/lib/CodeGen/CGCall.cpp (hunk 12 above)
Comment (JustinStitt) [reply clang/lib/CodeGen/CGCall.cpp]: Yep that makes sense. Since this is the heuristic path I will make sure we don't do redundant work when the better option (w/ debug info) is available.

File: clang/lib/CodeGen/CGCall.cpp [hunk 14]
```diff
@@ -6064,13 +6064,23 @@ RValue CodeGenFunction::EmitCall(const CGFunctionInfo &CallInfo,
...
+    bool NeedSrcLoc = TargetDecl->hasAttr<ErrorAttr>();
+    if (!NeedSrcLoc) {
+      if (const auto *FD = dyn_cast<FunctionDecl>(TargetDecl))
+        NeedSrcLoc = FD->isInlined() || FD->hasAttr<AlwaysInlineAttr>() ||
+                     FD->getStorageClass() == SC_Static ||
+                     FD->isInAnonymousNamespace();
```
[the remark this answers is not in the document]
Comment (JustinStitt) [reply clang/lib/CodeGen/CGCall.cpp]: > This is imposing a non-zero cost on all code, whether or not it uses ErrorAttr. Imposing a cost on everyone for the sake of the Linux kernel isn't great.

The cost is a dyn_cast-check and some short-circuitable trivial checks. The most expensive check after the dynamic cast is probably the `hasAttr` check. I don't see how I can avoid it :(

> How much does this cost? Do we expect diagnostics that are relevant outside the Linux kernel to use this?

I put some benchmarks I ran a couple of weeks ago in the PR description.

File: llvm/lib/IR/DiagnosticInfo.cpp (hunk 11 above)
Comment (JustinStitt) [reply llvm/lib/IR/DiagnosticInfo.cpp]: Makes sense. I wasn't sure if `.get()` could still return null here somehow. I removed the redundant check with 269a85772dbb43d16b88100da1760e8110d3f111

File: clang/lib/CodeGen/CGCall.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGCall.cpp]: The actual checks here should be fast (maybe could make them a little faster by checking the linkage instead of directly checking isInAnonymousNamespace()).  More concerned about scattering srcloc metadata all over files which don't actually use the error attribute.

I think I'd like to see peak memory usage numbers for some C++ code.

[the remark this answers is not in the document]
Comment (JustinStitt) [reply clang/lib/CodeGen/CGCall.cpp]: @efriedma-quic 
> I think I'd like to see peak memory usage numbers for some C++ code.

I ran some benchmarks and saw the following results, note that each block is 10 runs building some clang Sema code. 

```
median peak memory usage building Sema/SemaExpr.cpp                                                            
    ┌─────────────┬──────────────┬──────────────┬──────────────┐                 
    │ Config      │    Blk 1     │    Blk 2     │   Overhead   │                 
    ├─────────────┼──────────────┼──────────────┼──────────────┤                 
    │ Vanilla     │  1013.9 MB   │  1013.4 MB   │      -       │                 
    │ Heuristic   │  1031.2 MB   │  1031.0 MB   │   +1.7%      │                 
    │ Debug       │  1353.9 MB   │  1355.8 MB   │  +33.7%      │
    └─────────────┴──────────────┴──────────────┴──────────────┘ 
```

I am not exactly sure how representative `SemaExpr.cpp` is of C++ code in the wild but we probably shouldn't be pushing 2% memory overhead too frequently, especially for simple diagnostic changes. 

I wanted to hide all of this behind a flag but as you can see early on in this PR we opted to not do that. What are other options here? Can we drop the heuristic mode entirely and just let users build with `-g1` if they are debugging a `error/warning`-annotated stack? Or maybe this 2% overhead is fine if other features end up using this srcloc information?

[the remark this answers is not in the document]
Comment (bwendling) [reply clang/lib/CodeGen/CGCall.cpp]: Tangential, though potentially related, question. Since `isInAnonymousNamespace()` isn't constant time, as the name would imply, wouldn't it be better to cache the value the first time it's called? This would ameliorate the cost.

@JustinStitt is this function called before (or after) it reaches your code?

[the remark this answers is not in the document]
Comment (bwendling) [reply clang/lib/CodeGen/CGCall.cpp]: The Line was just an idea. It probably won't help anything, because it will have to be stored somewhere no matter what.

**Review by nikic — COMMENTED** [review]
Without commenting on the memory usage question yet, I'll note that this is missing LangRef wording for the new metadata and tests for the inliner.

**Comment by nickdesaulniers** [comment]
Hey, sorry for [suggesting](https://github.com/llvm/llvm-project/pull/174892#issuecomment-3753254069) we elide `-fdiagnostics-show-inlining-chain`, i.e.

> In that case, @JustinStitt WDYT about just attaching the note about -gline-directives-only to WarningAttr (and thus eliding the addition of -fdiagnostics-show-inlining-chain?

_then stepping away from upstream reviews here for over 2 months_.  I'm back at Google now, managing Android's LLVM team, so I should have more time for reviews now (famous last words).

> but otherwise I want it off by default.

Understandable; don't pay for what you don't use.  I guess I didn't consider that perspective enough when I made my above sugguestion.  In that case, we'd need to _go back to having an explicit flag (`-fdiagnostics-show-inlining-chain`)_ that we could keep off by default, then the Linux kernel could enable explicitly via feature detecting support for the command line flag.

>> I think ~1% memory overhead is acceptable given the benefits
>> I think these attributes are used outside of the kernel too.
> A large fraction of those uses are using it in a way that doesn't benefit from this patch.

I agree with @efriedma-quic here; the point is really to help someone writing code that calls libc standard library functions that have a _particular implementation of FORTIFY_SOURCE_.  It's conceivable that other libc implementations don't have FORTIFY_SOURCE, or their implementation wouldn't benefit from this. Also conceivable that these inline hints are helpful for other diagnostics than `-Wwarning`/`-Werror`, but that's a stretch.

---
So, again, sorry for derailing this with a half baked suggestion, then running off.

Perhaps if @efriedma-quic and @AaronBallman could agree with us going back to having an explicit off-by-default `-fdiagnostics-show-inlining-chain` and @JustinStitt doesn't mind going back to that version, then that would be a compromise that makes everyone happy, so that we can unstick this, and we can better help Linux kernel developers better spot their known at compile time bounds overflows?

**Comment by AaronBallman** [comment]
> I'm fine with the off-by-default option.

I'm also okay with that approach. We can enable by default in the future if we feel it's justified, but going the opposite direction is much harder.

**Review by nickdesaulniers — APPROVED** [review]
Please get @efriedma-quic and @AaronBallman 's final blessings before landing!

**Review by efriedma-quic — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM!
