### PR TITLE
[flang][OpenMP] Verify uses of OmpCancellationConstructTypeClause

### LINKED ISSUE #138224: [Flang][OpenMP] Flang crashes on invalid OpenMP directive "omp sections parallel"
When compiling the following Fortran code with Flang, the compiler crashes.
This code is intentionally invalid and should trigger a syntax error, but instead, Flang crashes.
This reproducer was generated by ChatGPT.
https://godbolt.org/z/s59av95EY
```f90
!$omp sections parallel
!$omp section
    x = x + 1
!$omp end sections
end
```

With assertion-enabled flang, I got the following assertion failure:
```txt
flang: /path_to_project/llvm-project/flang/lib/Lower/OpenMP/Decomposer.cpp:87: Fortran::lower::omp::ConstructQueue Fortran::lower::omp::buildConstructQueue(mlir::ModuleOp, Fortran::semantics::SemanticsContext &, Fortran::lower::pft::Evaluation &, const parser::CharBlock &, llvm::omp::Directive, const List<Fortran::lower::omp::Clause> &): Assertion `!decompose.output.empty() && "Construct decomposition failed"' failed.
```

### PR DESCRIPTION
**Pull request by kparzysz**
Some directive names can be used as clauses, for example in "cancel". In case where a directive name is misplaced, it could be interpreted as a clause.

Verify that such uses are valid, and emit a diagnostic message if not.

Fixes https://github.com/llvm/llvm-project/issues/138224

### CODE REVIEW

File: flang/test/Semantics/OpenMP/cancellation-construct-type.f90 [hunk 1]
```diff
@@ -0,0 +1,11 @@
+!RUN: %python %S/../test_errors.py %s %flang_fc1 %openmp_flags
+
+subroutine f(x)
+  integer :: x
+!ERROR: Cancellation construct type is not allowed on SECTIONS
```
Comment (tblah) [inline flang/test/Semantics/OpenMP/cancellation-construct-type.f90:5]: I think the meaning of this error will not be obvious to the user. Perhaps "PARALLEL cannot follow SECTIONS"?

**Review by tblah — COMMENTED** [review]
Nice work diagnosing this, it is a surprising bug.

**Review by tblah — APPROVED** [review]
Thanks
