### PR TITLE
[SelectionDAG] Fix incorrect fold condition in foldSetCCWithFunnelShift.

### LINKED ISSUE #136746: fshr-related miscompile by AArch64 backend
here's a function:
```llvm
; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.fshr.i64(i64, i64, i64) #0

define i1 @f(i64 %0) {
  %2 = or i64 1, %0
  %3 = call i64 @llvm.fshr.i64(i64 %2, i64 %0, i64 0)
  %4 = icmp uge i64 0, %3
  ret i1 %4
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```
the AArch64 backend lowers it as follows:
```
_f:
	mov	w0, wzr
	ret
```
but `f(0)` should evaluate to 1 (and it does when compiled using Apple's latest clang)

(test case generated by @dtcxzyw's mutator)

### PR DESCRIPTION
**Pull request by Ruhung**
Proposed by [2ed1598](https://github.com/llvm/llvm-project/commit/2ed15984b49a1af87be37ec8bd6ee3ab7f724767):

`fshl X, (or X, Y), C ==/!= 0 --> or (srl Y, BW-C), X ==/!= 0`

This transformation is valid when (C%Bitwidth) != 0 , as verified by [Alive2](https://alive2.llvm.org/ce/z/TQYM-m).

Fixes #136746

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 1]
```diff
@@ -4462,7 +4462,8 @@ static SDValue foldSetCCWithFunnelShift(EVT VT, SDValue N0, SDValue N1,
 
   unsigned BitWidth = N0.getScalarValueSizeInBits();
   auto *ShAmtC = isConstOrConstSplat(N0.getOperand(2));
-  if (!ShAmtC || ShAmtC->getAPIntValue().uge(BitWidth))
+  APInt AmtVal = ShAmtC->getAPIntValue();
+  if (!ShAmtC || AmtVal.uge(BitWidth) || AmtVal.isZero())
```
Comment (davemgreen) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4466]: If can't access ShAmtC (through `ShAmtC->getAPIntValue()`) before testing that it is vali (through `!ShAmtC`).

Comment (Ruhung) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: > If can't access ShAmtC (through `ShAmtC->getAPIntValue()`) before testing that it is valid (through `!ShAmtC`).

@davemgreen Done. Thanks.

Comment (Ruhung) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: > A more precise way to implement this check would be to first reduce the shift amount modulo the bitwidth:
> 
> ```
>   unsigned ShAmt = ShAmtC->getAPIntValue().urem(BitWidth).getZExtValue();
> ```
> 
> and then bail out if it is zero.

The shift amount needs to be less than BitWidth, so a modulo operation may not be necessary?

**Review by davemgreen — APPROVED** [review]
LGTM if there are no other comments. Thanks

**Review by efriedma-quic — APPROVED** [review]

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 2]
```diff
@@ -4462,7 +4462,11 @@ static SDValue foldSetCCWithFunnelShift(EVT VT, SDValue N0, SDValue N1,
 
   unsigned BitWidth = N0.getScalarValueSizeInBits();
   auto *ShAmtC = isConstOrConstSplat(N0.getOperand(2));
-  if (!ShAmtC || ShAmtC->getAPIntValue().uge(BitWidth))
+  if (!ShAmtC)
+    return SDValue();
+
+  APInt AmtVal = ShAmtC->getAPIntValue();
+  if (AmtVal.uge(BitWidth) || AmtVal.isZero())
     return SDValue();
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4470]: Why not:
```cpp
uint64_t AmtVal = ShAmtC->getAPIntValue().urem(BitWidth);
if (AmtVal == 0)
  return SDValue();
```

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 1 above)
Comment (jayfoad) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: > It looks like it might only be fshr that is incorrect

What is "incorrect" here? (I was not pointing out a bug, just a way to make the implementation a bit simpler _and_ handle more cases.)

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 2 above)
Comment (davemgreen) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4470]: From my point of view - just because it should not come up from non-canonical code IIUC, and so fixing the bug is the more important issue and trying to handle other cases that could lead to further bugs for little benefit. But it sounds OK so long as the rest of the code handles it correctly.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 1 above)
Comment (davemgreen) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: I didn't mean your suggestion was incorrect, just that it was only the fshr by 0 case that was incorrect in the original code (as it turns into a shift by 32-0, which turns into poison). The other cases did not look worth supporting to me as they are more likely to introduce more issues than letting the funnel shift by a constant canonicalize before optimizing it again, but if you want to go that route it sounds OK so long as the other code works with it.

Comment (Ruhung) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp]: @jayfoad Sorry for the initial misunderstanding, it's OK to take the modulo first and then check whether it's zero ([Alive2](https://alive2.llvm.org/ce/z/TQYM-m)). I've fixed it. Thanks!

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 2 above)
Comment (Ruhung) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4470]: @RKSimon You're right. It's OK to take the modulo first. I've fixed it. Thanks!

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 3]
```diff
@@ -4462,11 +4462,14 @@ static SDValue foldSetCCWithFunnelShift(EVT VT, SDValue N0, SDValue N1,
 
   unsigned BitWidth = N0.getScalarValueSizeInBits();
   auto *ShAmtC = isConstOrConstSplat(N0.getOperand(2));
-  if (!ShAmtC || ShAmtC->getAPIntValue().uge(BitWidth))
+  if (!ShAmtC)
+    return SDValue();
+
+  uint64_t ShAmt = ShAmtC->getAPIntValue().urem(BitWidth);
```
Comment (jayfoad) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4468]: Doesn't this need a `.getZExtValue` to convert from APInt to uint64_t?

**Review by jayfoad — APPROVED** [review]
LGTM

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 3 above)
Comment (RKSimon) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4468]: urem(uint64_t) returns a uint64_t
