### PR TITLE
[mlir][IR] Fix bug in AffineExpr simplifier `lhs % rhs` where `lhs = lhs floordiv rhs`

### LINKED ISSUE #114654: [mlir] Inconsistent results for affine.apply
I have the following MLIR program:
test.mlir:
```
#map2 = affine_map<(d0, d1) -> (((d1 - (d1 + 2)) floordiv 8) mod 8)>

module {
  func.func nested @func1() -> f32 {
    %idx1 = arith.constant 1 : index
    %res2 = affine.apply #map2(%idx1, %idx1)
    vector.print %res2 : index
    %0 = arith.index_cast %res2 : index to i64
    %1 = arith.sitofp %0 : i64 to f32
    return %1 : f32
  }
}
```
When I ran ```/data/tmp/v1102/llvm-project/build/bin/mlir-opt --lower-affine --convert-arith-to-llvm --convert-vector-to-llvm --convert-func-to-llvm --convert-index-to-llvm --reconcile-unrealized-casts test.mlir | /data/tmp/v1102/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1102/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1102/llvm-project/build/lib/libmlir_c_runner_utils.so``` on the program, I got the result of:
```
7
7.000000e+00
```
However, when I ran ```/data/tmp/v1102/llvm-project/build/bin/mlir-opt --affine-simplify-structures --lower-affine --convert-arith-to-llvm --convert-vector-to-llvm --convert-func-to-llvm --convert-index-to-llvm --reconcile-unrealized-casts test.mlir | /data/tmp/v1102/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1102/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1102/llvm-project/build/lib/libmlir_c_runner_utils.so``` on the program, I got the result of:
```
8
8.000000e+00
```
The above two results seem to be inconsistent. I'm not sure if there is any bug in my program or if the wrong usage of the above passes caused these results.

My git version is 33bdb53d864e3e244d8fd5649062f17b7d4c958d.

### PR DESCRIPTION
**Pull request by christopherbate**
Fixes an issue where the `SimpleAffineExprFlattener` would simplify
`lhs % rhs` to just `-(lhs floordiv rhs)` instead of `lhs - (lhs floordiv rhs)`
if `lhs` happened to be equal to `lhs floordiv rhs`.

The reported failure case was `(d0, d1) -> (((d1 - (d1 + 2)) floordiv 8) % 8)`
from https://github.com/llvm/llvm-project/issues/114654.

Note that many paths that simplify AffineMaps (e.g. the AffineApplyOp
folder and canonicalization) would not observe this bug because of
of slightly different paths taken by the code. Slightly different grouping
of the terms could also result in avoiding the bug. The way to reproduce was
by constructing the map directly, replacing `d1` with `1` and calling
`mlir::simplifyAffineExpr`.

Resolves https://github.com/llvm/llvm-project/issues/114654.

### CODE REVIEW

File: mlir/unittests/IR/AffineExprTest.cpp [hunk 1]
```diff
@@ -129,3 +129,24 @@ TEST(AffineExprTest, d0PlusD0FloorDivNeg2) {
   auto sum = d0 + d0.floorDiv(-2) * 2;
   ASSERT_EQ(toString(sum), "d0 + (d0 floordiv -2) * 2");
 }
+
+TEST(AffineExprTEst, simpleAffineExprFlattenerRegression) {
```
Comment (Groverkss) [inline mlir/unittests/IR/AffineExprTest.cpp:133]: AffineExprTEst -> AffineExprTest

File: mlir/unittests/IR/AffineExprTest.cpp [hunk 2]
```diff
@@ -129,3 +129,24 @@ TEST(AffineExprTest, d0PlusD0FloorDivNeg2) {
...
+  MLIRContext ctx;
+  OpBuilder b(&ctx);
+
+  auto d0 = b.getAffineDimExpr(0);
+  auto d1 = b.getAffineDimExpr(1);
+
+  // Manually replace variables by constants to avoid constant folding.
+  AffineExpr expr = (d0 - (d1 + 2)).floorDiv(8) % 8;
+  expr = expr.replaceDims(
+      {b.getAffineConstantExpr(1), b.getAffineConstantExpr(1)});
```
Comment (Groverkss) [inline mlir/unittests/IR/AffineExprTest.cpp:147]: This will just simplify the AffineExpr to a constant. The later call to simplifyAffineExpr will simply not materialize. I ran this test with your patch and without your patch and the printing is same:

```
Original:
((d0 - (d1 + 2)) floordiv 8) mod 8
Replacement:
7
Simplified:
7
```

Please add a symbolic test where the bug can actually be seen.

File: mlir/lib/IR/AffineExpr.cpp [hunk 3]
```diff
@@ -1385,7 +1385,7 @@ LogicalResult SimpleAffineExprFlattener::visitModExpr(AffineBinaryOpExpr expr) {
     lhs[getLocalVarStartIndex() + numLocals - 1] = -rhsConst;
   } else {
     // Reuse the existing local id.
-    lhs[getLocalVarStartIndex() + loc] = -rhsConst;
+    lhs[getLocalVarStartIndex() + loc] -= rhsConst;
```
Comment (Groverkss) [inline mlir/lib/IR/AffineExpr.cpp:1388]: This looked right to me before. Can you add a proper test showing that this is wrong?

**Review by Groverkss — CHANGES_REQUESTED** [review]

File: mlir/unittests/IR/AffineExprTest.cpp (hunk 2 above)
Comment (Groverkss) [reply mlir/unittests/IR/AffineExprTest.cpp:147]: I think what you wanted was to use `b.getAffineDimExpr(1)`. I can reproduce the error with that.

File: mlir/lib/IR/AffineExpr.cpp (hunk 3 above)
Comment (Groverkss) [reply mlir/lib/IR/AffineExpr.cpp:1388]: Actually, I printed it and I see what is happening here. Your change makes sense.

**Review by Groverkss — COMMENTED** [review]
LGTM, please fix the test before landing.

**Review by Groverkss — APPROVED** [review]

File: mlir/unittests/IR/AffineExprTest.cpp (hunk 2 above)
Comment (christopherbate) [reply mlir/unittests/IR/AffineExprTest.cpp]: Thanks, yeah I put in the test wrong, not sure what I was thinking there. Fixed it so that it fails before the change and passes after.
