### PR TITLE
[Clang][P1061] Fix invalid pack binding crash

### LINKED ISSUE #134882: constexpr decomposition declaration make clang crash
```cpp
struct foo { char a; int b; };
constexpr foo t{'a', 1};
constexpr auto [...m] = t;
```
https://godbolt.org/z/Ynqh9rnKr

### PR DESCRIPTION
**Pull request by ricejasonf**
Fixes #134882 

Consider
```
struct foo { char a; int b; };
constexpr foo t{'a', 1};
constexpr auto [...m] = t;
```
Without the `constexpr` qualifier, the decomposition declaration just happens to not crash in the call to `DeclMustBeEmitted` because it returns early because of its "discardable gval linkage". So, the fix is in `flat_bindings` where we cannot assume the pack binding is valid. There is also a fix along the same vein from a suggestion made by @shafik. The tests are still building on my machine, but I thought I would submit this to get eyes on it earlier since it is trivial.

### CODE REVIEW

**Review by zyn0217 — APPROVED** [review]
thanks

**Comment by cor3ntin** [comment]
thanks! do you need us to merge that for you?

**Comment by ricejasonf** [comment]
Yes, please, merge it when you can.

File: clang/test/SemaCXX/cxx2c-binding-pack-nontemplate.cpp [hunk 1]
```diff
@@ -3,9 +3,15 @@
 // RUN: %clang_cc1 -std=c++23 -verify=cxx23,nontemplate -fsyntax-only -Wc++26-extensions %s
 
 void decompose_array() {
-  int arr[4] = {1, 2, 3, 6};
```
Comment (shafik) [inline clang/test/SemaCXX/cxx2c-binding-pack-nontemplate.cpp:6]: We should have both cases tested, we want as wide test coverage as possible. 

Since we just saw w/ the bug this fixes the change in semantics uncovered a bug so covering both semantics is the right thing to do.

**Review by shafik — COMMENTED** [review]
Thank you for the quick fix, I left a comment on the test which should be addressed in a follow up, unless I am missing something and the coverage is elsewhere already.

**Comment by ricejasonf** [comment]
Sorry, I haven't had time to revisit this, but in that test we are only checking the validity of the decomposition declarations so I think the addition of `constexpr` to that variable should not affect the checks on the other declarations. There is plenty of coverage on decompositions in the other not "nontemplate" test file. Still, I probably did not need to step on the original test like that. I will consider adding more "invalid declaration" tests and address this when I get more time. Thank you.
