### PR TITLE
Fix OOM in FormatDiagnostic

### LINKED ISSUE #70930: "Multiple diagnostics in flight at once!" assert, and runaway memory usage in release builds, on C++20 testcase with PCH
version :  llvmorg-17.0.3 

Recently, when using clangd in vscode remote, once a certain file is encountered, the memory will explode, eventually causing the entire machine to go out of memory (clangd consumes more than 64G of memory). Below is the stack (using the release version, compiled with -g)

```
#0  0x00007f4d2d1a8233 in _int_malloc () from /lib64/libc.so.6
#1  0x00007f4d2d1ab10c in malloc () from /lib64/libc.so.6
#2  0x0000000000a2b2d8 in llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) ()
#3  0x0000000000f35070 in llvm::SmallVectorTemplateCommon<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, void>::grow_pod (TSize=16, MinSize=<optimized out>, this=0x7f4d25fe3710) at /llvmorg-17.0.3/llvm/include/llvm/ADT/SmallVector.h:140
#4  llvm::SmallVectorTemplateBase<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, true>::grow (MinSize=<optimized out>, this=0x7f4d25fe3710) at /llvmorg-17.0.3/llvm/include/llvm/ADT/SmallVector.h:529
#5  llvm::SmallVectorTemplateCommon<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, void>::reserveForParamAndGetAddressImpl<llvm::SmallVectorTemplateBase<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, true> > (N=1, Elt=<synthetic pointer>..., This=0x7f4d25fe3710)
    at /llvmorg-17.0.3/llvm/include/llvm/ADT/SmallVector.h:246
#6  llvm::SmallVectorTemplateBase<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, true>::reserveForParamAndGetAddress (N=1, Elt=<synthetic pointer>..., this=0x7f4d25fe3710) at /llvmorg-17.0.3/llvm/include/llvm/ADT/SmallVector.h:541
#7  llvm::SmallVectorTemplateBase<std::pair<clang::DiagnosticsEngine::ArgumentKind, long>, true>::push_back (Elt=..., this=0x7f4d25fe3710) at /llvmorg-17.0.3/llvm/include/llvm/ADT/SmallVector.h:566
#8  clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a4068 <(anonymous namespace)::StaticDiagInfoDescriptions+249544> "'", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1142
#9  0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#10 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a3d23 <(anonymous namespace)::StaticDiagInfoDescriptions+248707> ")' clause%select{s|}1", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#11 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#12 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a3cf0 <(anonymous namespace)::StaticDiagInfoDescriptions+248656> " cannot be mixed with '%0(%select{sink:vec|source}1)' clause%select{s|}1", DiagEnd=<optimized out>, OutStr=...)
    at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#13 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#14 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a3cdb <(anonymous namespace)::StaticDiagInfoDescriptions+248635> ")' clause%select{|s}1 cannot be mixed with '%0(%select{sink:vec|source}1)' clause%select{s|}1", DiagEnd=<optimized out>, OutStr=...)
    at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#15 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#16 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a2e66 <(anonymous namespace)::StaticDiagInfoDescriptions+244934> "", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#17 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#18 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a138a <(anonymous namespace)::StaticDiagInfoDescriptions+238058> "", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#19 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#20 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x6a08f0 <(anonymous namespace)::StaticDiagInfoDescriptions+235344> " type", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#21 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#22 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69fb28 <(anonymous namespace)::StaticDiagInfoDescriptions+231816> ", not %0", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#23 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#24 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69f1b4 <(anonymous namespace)::StaticDiagInfoDescriptions+229396> " because assigning method's 2nd parameter of type %0 is not an Objective-C pointer type", DiagEnd=<optimized out>, OutStr=...)
    at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#25 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#26 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69ea67 <(anonymous namespace)::StaticDiagInfoDescriptions+227527> " element must have Objective-C object return type instead of %0", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#27 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#28 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69e6bf <(anonymous namespace)::StaticDiagInfoDescriptions+226591> " %3", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#29 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#30 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69e660 <(anonymous namespace)::StaticDiagInfoDescriptions+226496> " declaration conflicts with previous %select{|direct }2declaration of %select{method|property}1 %3", DiagEnd=<optimized out>, OutStr=...)
    at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#31 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#32 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69e3eb <(anonymous namespace)::StaticDiagInfoDescriptions+225867> "", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#33 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#34 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69c9ab <(anonymous namespace)::StaticDiagInfoDescriptions+219147> "", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#35 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#36 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69bde6 <(anonymous namespace)::StaticDiagInfoDescriptions+216134> "", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#37 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#38 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69b4bd <(anonymous namespace)::StaticDiagInfoDescriptions+213789> " follows declaration in %select{the global module|module %4}3", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#39 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#40 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69b239 <(anonymous namespace)::StaticDiagInfoDescriptions+213145> " method %0 not found ; did you mean %2?", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#41 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#42 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69ad1b <(anonymous namespace)::StaticDiagInfoDescriptions+211835> ", but function has %select{non-const lvalue|rvalue}2 ref-qualifier", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#43 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#44 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69aa5c <(anonymous namespace)::StaticDiagInfoDescriptions+211132> " %2?", DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#45 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#46 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x69a6ec <(anonymous namespace)::StaticDiagInfoDescriptions+210252> " integers and enum types, but was given %2%select{| whose underlying type is %4}3", DiagEnd=<optimized out>, OutStr=...)
    at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
   .......
   .......
   ....... something like FormatDiagnostic
   .......
   .......
   .......
   .......
#224 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930, DiagStr=0x67f46c <(anonymous namespace)::StaticDiagInfoDescriptions+99020> " found %select{%select{no super class|super class with type %5}4|instance variable '%4' access control is %select{|@private|@protected|@public|@package}5}3",
    DiagEnd=<optimized out>, OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#225 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#226 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930,
    DiagStr=0x67f30c <(anonymous namespace)::StaticDiagInfoDescriptions+98668> " has different definitions in different modules; first difference is this %select{||||static assert|field|method|type alias|typedef|data member|friend declaration|function template|method|instance var"..., DiagEnd=<optimized out>,
    OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#227 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#228 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930,
    DiagStr=0x67f1e8 <(anonymous namespace)::StaticDiagInfoDescriptions+98376> " found %select{end of class|public access specifier|private access specifier|protected access specifier|static assert|field|method|type alias|typedef|data member|friend declaration|function template|m"..., DiagEnd=<optimized out>,
    OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#229 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#230 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930,
    DiagStr=0x67f064 <(anonymous namespace)::StaticDiagInfoDescriptions+97988> " found %select{%select{method %5|constructor|destructor}4 that has %6 parameter%s6|%select{method %5|constructor|destructor}4 with %ordinal6 parameter of type %7%select{| decayed from %9}8|%select{met"..., DiagEnd=<optimized out>,
    OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#231 0x0000000000f35375 in HandleSelectModifier (OutStr=..., ArgumentLen=<optimized out>, Argument=<optimized out>, ValNo=<optimized out>, DInfo=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:628
#232 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930,
    DiagStr=0x67eeea <(anonymous namespace)::StaticDiagInfoDescriptions+97610> " first difference is %select{return type is %4|%ordinal4 parameter with name %5|%ordinal4 parameter with type %5%select{| decayed from %7}6|%ordinal4 parameter with%select{out|}5 a default argument|%o"..., DiagEnd=<optimized out>,
    OutStr=...) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:1001
#233 0x0000000001de8f76 in clang::clangd::fillNonLocationData (DiagLevel=clang::DiagnosticsEngine::Error, Info=..., D=...) at /llvmorg-17.0.3/clang-tools-extra/clangd/Diagnostics.cpp:664
#234 0x0000000001dea974 in operator() (__closure=__closure@entry=0x7f4d25ff66e0, D=...) at /llvmorg-17.0.3/clang-tools-extra/clangd/Diagnostics.cpp:720
#235 0x0000000001df8222 in clang::clangd::StoreDiags::HandleDiagnostic (this=0x7f4d25ff9be0, DiagLevel=<optimized out>, Info=...) at /opt/gcc-11.1.0/include/c++/11.1.0/optional:440
#236 0x0000000000f3a572 in clang::DiagnosticIDs::EmitDiag (DiagLevel=clang::DiagnosticIDs::Error, Diag=..., this=0x7f4d1c01e1f0) at /llvmorg-17.0.3/clang/lib/Basic/DiagnosticIDs.cpp:823
#237 clang::DiagnosticIDs::ProcessDiag (this=this@entry=0x7f4d1c01e1f0, Diag=...) at /llvmorg-17.0.3/clang/lib/Basic/DiagnosticIDs.cpp:815
#238 0x0000000000f33f1b in clang::DiagnosticsEngine::ProcessDiag (this=0x7f4d1c001990) at /llvmorg-17.0.3/clang/include/clang/Basic/Diagnostic.h:1037
#239 clang::DiagnosticsEngine::EmitCurrentDiagnostic (this=0x7f4d1c001990, Force=<optimized out>) at /llvmorg-17.0.3/clang/lib/Basic/Diagnostic.cpp:545
#240 0x0000000000b61590 in clang::DiagnosticBuilder::~DiagnosticBuilder() ()
#241 0x0000000000e0f1f4 in clang::ODRDiagsEmitter::diagnoseMismatch(clang::FunctionDecl const*, clang::FunctionDecl const*) const ()
#242 0x0000000002b5b877 in clang::ASTReader::diagnoseOdrViolations() [clone .localalias] ()
#243 0x0000000002b5e761 in clang::ASTReader::FinishedDeserializing() [clone .part.0] ()
#244 0x0000000002bbac65 in clang::ASTReader::ReadDeclRecord(unsigned int) ()
#245 0x0000000002b4d6c9 in clang::ASTReader::GetDecl(unsigned int) [clone .localalias] ()
#246 0x0000000002b665c3 in clang::ASTReader::completeVisibleDeclsMap(clang::DeclContext const*) [clone .part.0] ()
#247 0x00000000018c2e1e in (anonymous namespace)::LookupVisibleHelper::lookupInDeclContext(clang::DeclContext*, clang::LookupResult&, bool, bool) ()
#248 0x00000000018c5282 in clang::Sema::LookupVisibleDecls(clang::DeclContext*, clang::Sema::LookupNameKind, clang::VisibleDeclConsumer&, bool, bool, bool) [clone .localalias] ()
#249 0x00000000018cf4f4 in clang::Sema::makeTypoCorrectionConsumer(clang::DeclarationNameInfo const&, clang::Sema::LookupNameKind, clang::Scope*, clang::CXXScopeSpec*, clang::CorrectionCandidateCallback&, clang::DeclContext*, bool, clang::ObjCObjectPointerType const*, bool) [clone .localalias] ()
#250 0x00000000018d0c1d in clang::Sema::CorrectTypo(clang::DeclarationNameInfo const&, clang::Sema::LookupNameKind, clang::Scope*, clang::CXXScopeSpec*, clang::CorrectionCandidateCallback&, clang::Sema::CorrectTypoKind, clang::DeclContext*, bool, clang::ObjCObjectPointerType const*, bool) ()
#251 0x0000000001536b02 in clang::Sema::DiagnoseUnknownTypeName(clang::IdentifierInfo*&, clang::SourceLocation, clang::Scope*, clang::CXXScopeSpec*, clang::OpaquePtr<clang::QualType>&, bool) ()
#252 0x0000000002a1a27d in clang::Parser::ParseImplicitInt(clang::DeclSpec&, clang::CXXScopeSpec*, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) [clone .localalias] ()
#253 0x0000000002a1e49c in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) [clone .localalias] ()
#254 0x0000000002af8dad in clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) [clone .localalias] ()
#255 0x0000000002af9e9f in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.0] ()
#256 0x0000000002b00676 in clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) [clone .localalias] ()
#257 0x0000000002b018da in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) [clone .localalias] ()
#258 0x00000000029fe3ca in clang::ParseAST(clang::Sema&, bool, bool) [clone .localalias] ()
#259 0x000000000116f5f9 in clang::FrontendAction::Execute() ()
#260 0x0000000001ee75fd in clang::clangd::ParsedAST::build (Filename=..., Inputs=..., CI=..., CompilerInvocationDiags=..., Preamble=...) at /llvmorg-17.0.3/clang-tools-extra/clangd/ParsedAST.cpp:669
#261 0x0000000001f5d462 in clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics (this=0x3946950, Invocation=..., Inputs=..., CIDiags=...) at /opt/gcc-11.1.0/include/c++/11.1.0/bits/basic_string.h:912
#262 0x0000000001f5dd83 in operator() (__closure=0x7f4cf80022d0) at /opt/gcc-11.1.0/include/c++/11.1.0/bits/unique_ptr.h:172
#263 0x0000000001f56965 in llvm::unique_function<void ()>::operator()() (this=0x3946bb0) at /llvmorg-17.0.3/llvm/include/llvm/ADT/FunctionExtras.h:382
#264 llvm::function_ref<void ()>::callback_fn<llvm::unique_function<void ()> >(long) (callable=60058544) at /llvmorg-17.0.3/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#265 llvm::function_ref<void ()>::operator()() const (this=<synthetic pointer>) at /llvmorg-17.0.3/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#266 clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void()>) (this=this@entry=0x3946950, Name=..., Task=...) at /llvmorg-17.0.3/clang-tools-extra/clangd/TUScheduler.cpp:1324
#267 0x0000000001f58439 in clang::clangd::(anonymous namespace)::ASTWorker::run (this=0x3946950) at /llvmorg-17.0.3/clang-tools-extra/clangd/TUScheduler.cpp:1458
#268 0x0000000002106f25 in llvm::unique_function<void ()>::operator()() (this=0x392abc0) at /llvmorg-17.0.3/llvm/include/llvm/ADT/FunctionExtras.h:382
#269 operator() (__closure=0x392aba0) at /llvmorg-17.0.3/clang-tools-extra/clangd/support/Threading.cpp:101
#270 operator()<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()>&> (F=..., __closure=<optimized out>) at /llvmorg-17.0.3/llvm/include/llvm/Support/thread.h:43
#271 std::__invoke_impl<void, llvm::thread::GenericThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > >(void*)::<lambda(auto:4&&, auto:5&& ...)>, clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()>&> (__f=...) at /opt/gcc-11.1.0/include/c++/11.1.0/bits/invoke.h:61
#272 std::__invoke<llvm::thread::GenericThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > >(void*)::<lambda(auto:4&&, auto:5&& ...)>, clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()>&> (__fn=...) at /opt/gcc-11.1.0/include/c++/11.1.0/bits/invoke.h:96
#273 std::__apply_impl<llvm::thread::GenericThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > >(void*)::<lambda(auto:4&&, auto:5&& ...)>, std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> >&, 0> (__t=..., __f=...) at /opt/gcc-11.1.0/include/c++/11.1.0/tuple:1806
#274 std::apply<llvm::thread::GenericThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > >(void*)::<lambda(auto:4&&, auto:5&& ...)>, std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> >&> (__t=..., __f=...) at /opt/gcc-11.1.0/include/c++/11.1.0/tuple:1817
#275 llvm::thread::GenericThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > > (Ptr=0x392aba0) at /llvmorg-17.0.3/llvm/include/llvm/Support/thread.h:41
#276 llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(const llvm::Twine&, llvm::unique_function<void()>)::<lambda()> > >(void *) (Ptr=0x392aba0) at /llvmorg-17.0.3/llvm/include/llvm/Support/thread.h:55
#277 0x00007f4d2e258e25 in start_thread () from /lib64/libpthread.so.0
#278 0x00007f4d2d22335d in clone () from /lib64/libc.so.6

```

the  input to `clang::Diagnostic::FormatDiagnostic` look like this:

```
 f 232
#232 clang::Diagnostic::FormatDiagnostic (this=0x7f4d25ff6930,
    DiagStr=0x67eeea <(anonymous namespace)::StaticDiagInfoDescriptions+97610> " first difference is %select{return type is %4|%ordinal4 parameter with name %5|%ordinal4 parameter with type %5%select{| decayed from %7}6|%ordinal4 parameter with%select{out|}5 a default argument|%o"..., DiagEnd=<optimized out>,
    OutStr=...) at /source/install/llvm/llvm.git/clang/lib/Basic/Diagnostic.cpp:1001
1001            HandleSelectModifier(*this, Val, Argument, ArgumentLen, OutStr);
(gdb) p DiagStr
$5 = 0x67eeea <(anonymous namespace)::StaticDiagInfoDescriptions+97610> " first difference is %select{return type is %4|%ordinal4 parameter with name %5|%ordinal4 parameter with type %5%select{| decayed from %7}6|%ordinal4 parameter with%select{out|}5 a default argument|%o"...
(gdb) printf "%s\n", DiagStr
 first difference is %select{return type is %4|%ordinal4 parameter with name %5|%ordinal4 parameter with type %5%select{| decayed from %7}6|%ordinal4 parameter with%select{out|}5 a default argument|%ordinal4 parameter with a default argument|function body}3
(gdb)

```

and the `OutStr` contains the hugh memory

```
(gdb) p OutStr
$24 = (llvm::SmallVectorImpl<char> &) @0x7f4d25ff6500: {
  <llvm::SmallVectorTemplateBase<char, true>> = {
    <llvm::SmallVectorTemplateCommon<char, void>> = {
      <llvm::SmallVectorBase<unsigned long>> = {
        BeginX = 0x7f48d43fa010,
        Size = 4511505832,
        Capacity = 8724152319
      }, <No data fields>},
    members of llvm::SmallVectorTemplateBase<char, true>:
    static TakesParamByValue = true
  }, <No data fields>}
(gdb)

```

the content of `OutStr` 

```
(gdb) x /20xs (0x7f48d43fa010)
0x7f48d43fa010: "'std::midpoint' has different definitions in different modules; 1 first difference is '_Tp'"
0x7f48d43fa06c: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa0bf: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa112: " 1 has different definitions in different modules; first difference is this '_Tp'"
0x7f48d43fa164: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa1b7: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa20a: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa25d: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa2b0: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa303: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa356: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa3a9: " has different definitions in different modules; first difference is 1 found '_Tp'"
0x7f48d43fa3fc: "template parameter lists have a different number of parameters ( vs 2)"
0x7f48d43fa443: "template parameter has different kinds in different translation units"
0x7f48d43fa489: "field  declared with incompatible types in different translation units (2 vs. 1)"
0x7f48d43fa4da: "external function  declared with incompatible types in different translation units (2 vs. 1)"
0x7f48d43fa537: "instance variable  declared with incompatible types in different translation units (2 vs. 1)"
0x7f48d43fa594: "non-type template parameter declared with incompatible types in different translation units ( vs. 2)"
0x7f48d43fa5f9: " method 2 has a different number of parameters in different translation units (1 vs. '_Tp')"
0x7f48d43fa655: " method 2 has a parameter with a different types in different translation units (1 vs. '_Tp')"


(gdb) x /20xs (0x7f48d43fa010 + 4511505832 - 200)
0x7f49e127bcf0: "ncurrent"
0x7f49e127bcf9: "expected  in OpenMP clause '2'"
0x7f49e127bd18: "modifier '' cannot be used along with modifier '2'"
0x7f49e127bd4b: "mapping of union members is not allowed"
0x7f49e127bd73: "incorrect reduction identifier, expected one of '+', '-', '*', '&', '"
0x7f49e127bdb9: ""
0x7f49e127bdba: ""
0x7f49e127bdbb: ""
0x7f49e127bdbc: ""
0x7f49e127bdbd: ""
0x7f49e127bdbe: ""
```

### PR DESCRIPTION
**Pull request by igelbox**
Resolves: #70930 (and probably latest comments from https://github.com/clangd/clangd/issues/251)
by fixing racing for the shared `DiagStorage` value which caused messing with args inside the storage and then formatting the following message with `getArgSInt(1)` == 2:
```
def err_module_odr_violation_function : Error<
  "%q0 has different definitions in different modules; "
  "%select{definition in module '%2'|defined here}1 "
  "first difference is "
```
which causes `HandleSelectModifier` to go beyond the `ArgumentLen` so the recursive call to `FormatDiagnostic` was made with `DiagStr` > `DiagEnd` that leads to infinite `while (DiagStr != DiagEnd)`.

**The Main Idea:**
Reuse the existing `DiagStorageAllocator` logic to make all `DiagnosticBuilder`s having independent states.
Also, encapsulating the rest of state (e.g. ID and Loc) into `DiagnosticBuilder`.

**TODO (if it will be requested by reviewer):**
- [x] add a test (I have no idea how to turn a whole bunch of my proprietary code which leads `clangd` to OOM into a small public example.. probably I must try using [this](https://github.com/llvm/llvm-project/issues/70930#issuecomment-2209872975) instead)
- [x] [`Diag.CurDiagID != diag::fatal_too_many_errors`](https://github.com/llvm/llvm-project/pull/108187#pullrequestreview-2296395489)
- [ ] ? get rid of `DiagStorageAllocator` at all and make `DiagnosticBuilder` having they own `DiagnosticStorage` coz it seems pretty small so should fit the stack for short-living `DiagnosticBuilder` instances

### CODE REVIEW

File: clang/lib/Basic/DiagnosticIDs.cpp [hunk 1]
```diff
@@ -571,8 +571,7 @@ DiagnosticIDs::getDiagnosticSeverity(unsigned DiagID, SourceLocation Loc,
   }
 
   // If explicitly requested, map fatal errors to errors.
-  if (Result == diag::Severity::Fatal &&
-      Diag.CurDiagID != diag::fatal_too_many_errors && Diag.FatalsAsError)
```
Comment (igelbox) [inline clang/lib/Basic/DiagnosticIDs.cpp:575]: I'm not sure why do we checked for `Diag.CurDiagID != diag::fatal_too_many_errors` here.
Moreover even without this piece of code unit-tests succeed.

File: clang/include/clang/Basic/Diagnostic.h [hunk 2]
```diff
@@ -1333,13 +1263,7 @@ class DiagnosticBuilder : public StreamingDiagnostic {
 public:
   /// Copy constructor.  When copied, this "takes" the diagnostic info from the
   /// input and neuters it.
-  DiagnosticBuilder(const DiagnosticBuilder &D) : StreamingDiagnostic() {
-    DiagObj = D.DiagObj;
-    DiagStorage = D.DiagStorage;
```
Comment (igelbox) [inline clang/include/clang/Basic/Diagnostic.h:1338]: Well well, `DiagStorage` might be allocated via `DiagStorageAllocator` so this looked like a potential memory manager mess. Now, I fixed this (see cpp).

File: clang/lib/Basic/Diagnostic.cpp [hunk 3]
```diff
@@ -538,24 +511,51 @@ bool DiagnosticsEngine::EmitCurrentDiagnostic(bool Force) {
...
 
-  return Emitted;
+DiagnosticBuilder::DiagnosticBuilder(const DiagnosticBuilder &D)
+    : StreamingDiagnostic() {
+  CurDiagLoc = D.CurDiagLoc;
+  CurDiagID = D.CurDiagID;
+  FlagValue = D.FlagValue;
+  DiagObj = D.DiagObj;
+  DiagStorage = D.DiagStorage;
+  D.DiagStorage = nullptr;
```
Comment (igelbox) [inline clang/lib/Basic/Diagnostic.cpp:540]: Prevent potential memory manager mess if it was allocated by `DiagStorageAllocator`

File: clang/lib/Basic/Diagnostic.cpp [hunk 4]
```diff
@@ -538,24 +511,51 @@ bool DiagnosticsEngine::EmitCurrentDiagnostic(bool Force) {
...
-  // If there was a delayed diagnostic, emit it now.
-  if (!Force && DelayedDiagID)
-    ReportDelayed();
+DiagnosticBuilder::DiagnosticBuilder(DiagnosticsEngine *diagObj,
+                                     SourceLocation CurDiagLoc,
+                                     unsigned CurDiagID)
+    : StreamingDiagnostic(diagObj->DiagAllocator), DiagObj(diagObj),
+      CurDiagLoc(CurDiagLoc), CurDiagID(CurDiagID), IsActive(true) {
+  assert(diagObj && "DiagnosticBuilder requires a valid DiagnosticsEngine!");
+}
```
Comment (AaronBallman) [inline clang/lib/Basic/Diagnostic.cpp:531]:
```suggestion
DiagnosticBuilder::DiagnosticBuilder(DiagnosticsEngine *DiagObj,
                                     SourceLocation CurDiagLoc,
                                     unsigned CurDiagID)
    : StreamingDiagnostic(diagObj->DiagAllocator), DiagObj(DiagObj),
      CurDiagLoc(CurDiagLoc), CurDiagID(CurDiagID), IsActive(true) {
  assert(DiagObj && "DiagnosticBuilder requires a valid DiagnosticsEngine!");
}
```

File: clang/lib/Basic/Diagnostic.cpp (hunk 3 above)
Comment (AaronBallman) [reply clang/lib/Basic/Diagnostic.cpp:540]: Hmmm the downside to this is that someone may be expecting a copy operation and be caught off-guard by the copy constructor mutating the original object. Perhaps a bad idea, but I wonder if maybe we should have a move constructor that needs to be used if there's allocations by `DiagStorageAllocator` and the copy constructor can be used otherwise?

File: clang/lib/Basic/Diagnostic.cpp [hunk 5]
```diff
@@ -538,24 +511,51 @@ bool DiagnosticsEngine::EmitCurrentDiagnostic(bool Force) {
...
+                       const DiagnosticBuilder &DiagBuilder)
+    : DiagObj(DO), CurDiagLoc(DiagBuilder.CurDiagLoc),
+      CurDiagID(DiagBuilder.CurDiagID), FlagValue(DiagBuilder.FlagValue),
+      DiagStorage(*DiagBuilder.getStorage()) {}
+
+Diagnostic::Diagnostic(const DiagnosticsEngine *DO, SourceLocation CurDiagLoc,
+                       unsigned CurDiagID, const DiagnosticStorage &DiagStorage,
+                       StringRef storedDiagMessage)
+    : DiagObj(DO), CurDiagLoc(CurDiagLoc), CurDiagID(CurDiagID),
+      DiagStorage(DiagStorage), StoredDiagMessage(storedDiagMessage) {}
```
Comment (AaronBallman) [inline clang/lib/Basic/Diagnostic.cpp:557]:
```suggestion
                       StringRef StoredDiagMessage)
    : DiagObj(DO), CurDiagLoc(CurDiagLoc), CurDiagID(CurDiagID),
      DiagStorage(DiagStorage), StoredDiagMessage(StoredDiagMessage) {}
```

File: clang/lib/Basic/DiagnosticIDs.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/Basic/DiagnosticIDs.cpp:575]: That came from 878271b2945e89b868fb8daefea3dfaffce32710 and doesn't appear to have been tested. I think the logic is: if the severity is fatal, we would downgrade to error, but we do not want to downgrade the "too many fatal errors" diagnostic because that *has* to be fatal.

We could probably use better test coverage in this area; I suspect that code is still needed.

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this! I'm not certain that there is a reasonable way to add test coverage for the changes, but if you can devise a test, that would be appreciated.

Have you run your changes with address and ub sanitizers to see if there are some uncaught edge cases?

The changes are mostly looking good to me, but more sets of eyes on the changes would be appreciated.

File: clang/lib/Basic/Diagnostic.cpp (hunk 3 above)
Comment (igelbox) [reply clang/lib/Basic/Diagnostic.cpp:540]: > and be caught off-guard by the copy constructor mutating the original object

Yeah. But this is the original behavior (see the original "and neuters it" comment above the constructor declaration) even before my patch.

I'll try to declare it as a moving constructor.. and spend another hour to re-build the code.. soo slow and resource-demanding operation)

**Comment by igelbox** [comment]
> Have you run your changes with address and ub sanitizers to see if there are some uncaught edge cases?

Not quire sure I get the point about UB-sanitizers. I tested this changes against my proprietary code which caused the issue with OOM/infinite-loop and it works just fine. I can and will build the `clangd` with assertions enabled and test it against my codebase to try catching other cases.

**Comment by igelbox** [comment]
> I'm not certain that there is a reasonable way to add test coverage for the changes, but if you can devise a test, that would be appreciated.

I wonder there should be some tests like:
- input = some source files
- output = expected it compiles well and has no assertions fired

but not sure yet where to find such a tests-folder. I'm just a newbie in clang development workflow, so I wonder is someone more experienced would point me that.

**Comment by AaronBallman** [comment]
> > Have you run your changes with address and ub sanitizers to see if there are some uncaught edge cases?
> 
> Not quire sure I get the point about UB-sanitizers. I tested this changes against my proprietary code which caused the issue with OOM/infinite-loop and it works just fine. I can and will build the `clangd` with assertions enabled and test it against my codebase to try catching other cases.

Thanks! Mostly just trying to verify correctness given the breadth of changes; I didn't spot any UB, but it's easy for that to creep in.

> I wonder there should be some tests like:
> 
>     input = some source files
>     output = expected it compiles well and has no assertions fired
> 
> but not sure yet where to find such a tests-folder. I'm just a newbie in clang development workflow, so I wonder is someone more experienced would point me that.

Welcome! Most of our test coverage lives in `clang/test/` and tests individual components of the compiler. It looks like there are some good reduced test cases in the linked issue, now that I look more closely at the conversations there. I would recommend taking https://github.com/llvm/llvm-project/issues/70930#issuecomment-2209872975 and adding it as a test case to `clang/test/PCH`

File: clang/lib/Basic/DiagnosticIDs.cpp (hunk 1 above)
Comment (igelbox) [reply clang/lib/Basic/DiagnosticIDs.cpp:575]: I researched over the codebase and found many easy to prove usage patterns:
- `DiagID` comes from the same `Diag` object, e.g. https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Diagnostic.cpp#L536
  => they're interchangeable
- code compares the result level with `> DiagnosticsEngine::Warning`, e.g. https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/Driver.cpp#L277
or `>= DiagnosticsEngine::Error` - https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaDecl.cpp#L16351 
or `if (CurLevel < DiagnosticsEngine::Error)` - https://github.com/llvm/llvm-project/blob/main/clang/lib/Serialization/ASTReader.cpp#L498
  but both `Fatal` and `Error` are greater than `Warning` (or not less than `Error`)
  => these comparisons aren't affected at all

as well as some not so easy to prove:
- https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/ParsedAST.cpp#L578
  but it checks levels of a particular DiagIDs
  => probably we shouldn't rely on how many errors we faced before this checks (many of not so)
- https://github.com/llvm/llvm-project/blob/main/clang/tools/diagtool/ShowEnabledWarnings.cpp#L138
  ! here I'm not sure should we prevent downgrading some `Fatal`s to `Error`s here if the current diagnostic is in the `fatal_too_many_errors` "state"
- https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.h#L217
  !! the hardest one to prove coz it has so many usages

Well, for now I would do it in a simple/hopeful way - just use the `DiagID` argument. But, if it doesn't seem safe to reviewers - I could add smth like `size_t count_in_flight__fatal_too_many_errors` to the `DiagnosticsEngine` to mimic the original behavior.

File: clang/lib/Basic/Diagnostic.cpp (hunk 3 above)
Comment (igelbox) [reply clang/lib/Basic/Diagnostic.cpp:540]: Just tried to turn copy-constructor into a moving one and got a whole bunch of errors like:
```
/home/igelbox/llvm-project/clang/lib/Basic/SourceMgrAdapter.cpp: In member function ‘void clang::SourceMgrAdapter::handleDiag(const llvm::SMDiagnostic&)’:
/home/igelbox/llvm-project/clang/lib/Basic/SourceMgrAdapter.cpp:120:66: error: use of deleted function ‘clang::DiagnosticBuilder::DiagnosticBuilder(const clang::DiagnosticBuilder&)’
  120 |   DiagnosticBuilder Builder = Diagnostics.Report(Loc, DiagID) << Message;
      |                                                                  ^~~~~~~
In file included from /home/igelbox/llvm-project/clang/include/clang/Basic/SourceManager.h:37,
                 from /home/igelbox/llvm-project/clang/include/clang/Basic/SourceMgrAdapter.h:17,
                 from /home/igelbox/llvm-project/clang/lib/Basic/SourceMgrAdapter.cpp:14:
/home/igelbox/llvm-project/clang/include/clang/Basic/Diagnostic.h:1192:7: note: ‘clang::DiagnosticBuilder::DiagnosticBuilder(const clang::DiagnosticBuilder&)’ is implicitly declared as deleted because ‘clang::DiagnosticBuilder’ declares a move constructor or move assignment operator
 1192 | class DiagnosticBuilder : public StreamingDiagnostic {
      |       ^~~~~~~~~~~~~~~~~
[ 14%] Building R600GenCallingConv.inc...
make[3]: *** [tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/build.make:530: tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/SourceMgrAdapter.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:41994: tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/all] Error 2
```
I think they caused by `<<` operators which take `const Builder&` and return `const Builder&` as well that cannot match the moving constructor argument (which is a mutable value of course). Then tried to make them all non-const but it's still failing to compile in several places. I believe it's doable but afraid it would blow up the amount of changes in this PR. So, keeping in mind the original behavior was the same ("and neuters it" original comment) I suggest leaving this surprise-included copy-constructor as it is (like as it was).

File: clang/lib/Basic/DiagnosticIDs.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/Basic/DiagnosticIDs.cpp:575]: > Well, for now I would do it in a simple/hopeful way - just use the DiagID argument. But, if it doesn't seem safe to reviewers - I could add smth like size_t count_in_flight__fatal_too_many_errors to the DiagnosticsEngine to mimic the original behavior.

I think it should be reasonably safe to use `DiagID`. We could add some test coverage near https://github.com/llvm/llvm-project/blob/2670565afc4ec855fa406b8f582dde44ce1739fb/clang/unittests/Basic/DiagnosticTest.cpp#L61 as it seems we can only downgrade fatal diagnostics to errors as part of internal APIs rather than user-facing flags. The test could look something like (I've not tried this out myself):
```
TEST(DiagnosticTest, fatalsAsError) {
  DiagnosticsEngine Diags(new DiagnosticIDs(),
                          new DiagnosticOptions,
                          new IgnoringDiagConsumer());
  Diags.setFatalsAsError(true);

  // Report a fatal_too_many_errors diagnostic to ensure that still
  // acts as a fatal error despite downgrading fatal errors to errors.
  Diags.Report(diag::fatal_too_many_errors);
  EXPECT_TRUE(Diags.hasFatalErrorOccurred());

  // Ensure that the severity of that diagnostic really is "fatal".
  EXPECT_EQ(Diags.getDiagnosticIDs()->getDiagnosticSeverity(diag::fatal_too_many_errors, {}, Diags), diags::Severity::Fatal);
}
```

File: clang/lib/Basic/Diagnostic.cpp (hunk 3 above)
Comment (AaronBallman) [reply clang/lib/Basic/Diagnostic.cpp:540]: I agree, that seems reasonable to me. Thank you for investigating!

File: clang/test/PCH/race-condition.cpp [hunk 6]
```diff
@@ -0,0 +1,41 @@
+// RUN: %clang_cc1 -fallow-pch-with-compiler-errors -std=c++20 -x c++-header -emit-pch %s -o %t -verify
+// RUN: %clang_cc1 -fallow-pch-with-compiler-errors -std=c++20 -include-pch %t %s -verify
```
Comment (igelbox) [inline clang/test/PCH/race-condition.cpp:2]: In the `main` branch it didn't fail but simply hangs. Better than nothing though.

**Comment by igelbox** [comment]
Whew, managed to add both tests.

File: clang/include/clang/Basic/Diagnostic.h [hunk 7]
```diff
@@ -945,50 +959,11 @@ class DiagnosticsEngine : public RefCountedBase<DiagnosticsEngine> {
...
-
 private:
   // This is private state used by DiagnosticBuilder.  We put it here instead of
   // in DiagnosticBuilder in order to keep DiagnosticBuilder a small lightweight
-  // object.  This implementation choice means that we can only have one
-  // diagnostic "in flight" at a time, but this seems to be a reasonable
+  // object.  This implementation choice means that we can only have a few
+  // diagnostics "in flight" at a time, but this seems to be a reasonable
   // tradeoff to keep these objects small.  Assertions verify that only one
   // diagnostic is in flight at a time.
```
Comment (vvd170501) [inline clang/include/clang/Basic/Diagnostic.h:968]: "Assertions verify that only one diagnostic is in flight at a time" is now outdated and can be removed.

Comment (igelbox) [reply clang/include/clang/Basic/Diagnostic.h]: Okay. Removed misleading `Cur`-prefix (coz it isn't current it's the one per builder/diagnostic obj) and seemingly meaningless comments as well.

**Review by AaronBallman — APPROVED** [review]
LGTM! Do you need someone to land these changes on your behalf?

**Comment by igelbox** [comment]
> LGTM! Do you need someone to land these changes on your behalf?

I suppose so.. or what are my options? The Merge button isn't active of course.
I believe someone from maintainers would merge this PR and I will be so proud)

**Comment by AaronBallman** [comment]
> > LGTM! Do you need someone to land these changes on your behalf?
> 
> I suppose so.. or what are my options? The Merge button isn't active of course. I believe someone from maintainers would merge this PR and I will be so proud)

I've merged on your behalf (I sometime struggle to tell who has commit privileges and who doesn't), thank you!

**Comment by erichkeane** [comment]
@igelbox: That seems to be a problem with this patch!  If it is something you cannot fix/get a review up for very quickly so we can accept/get it in, we'll have to revert this.  Please let us know ASAP what you'd like to do.

**Comment by AaronBallman** [comment]
I've reverted; @igelbox, you can create a new PR that addresses the failures found by post-commit CI and I'll review them.
