### PR TITLE
[mlir-runner] Check entry function does not expect arguments

### LINKED ISSUE #136143: [MLIR] unused llvm.mlir.poison crashes at runtime (JitRunner crashed with segmentation fault)
test commit: [e6f23b3](https://github.com/llvm/llvm-project/commit/e6f23b383e0c08ecc380d879035e594019f34211)

step to reproduce:
```
mlir-runner test.mlir -e main -entry-point-result=void -shared-libs=/home/workdir/llvm-project/build/lib/libmlir_runner_utils.so
```

test case:
```
module {
  llvm.func @main(%arg0: !llvm.ptr, %arg1: !llvm.ptr) {
    %0 = llvm.mlir.poison : !llvm.struct<(ptr, ptr, i64, array<3 x i64>, array<3 x i64>)>
    llvm.return
  }
}
```

Crash backtrace:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: mlir-runner test.mlir -e main -entry-point-result=void -shared-libs=/home/workdir/llvm-project/build/lib/libmlir_runner_utils.so
 #0 0x000056435113a408 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/workdir/llvm-project/build/bin/mlir-runner+0x501408)
 #1 0x000056435113807e llvm::sys::RunSignalHandlers() (/home/workdir/llvm-project/build/bin/mlir-runner+0x4ff07e)
 #2 0x000056435113abd1 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007f95764af520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f9576af3018 
 #5 0x00005643516305e6 compileAndExecute((anonymous namespace)::Options&, mlir::Operation*, llvm::StringRef, (anonymous namespace)::CompileAndExecuteConfig, void**, std::unique_ptr<llvm::TargetMachine, std::default_delete<llvm::TargetMachine>>) JitRunner.cpp:0:0
 #6 0x000056435162da90 compileAndExecuteVoidFunction((anonymous namespace)::Options&, mlir::Operation*, llvm::StringRef, (anonymous namespace)::CompileAndExecuteConfig, std::unique_ptr<llvm::TargetMachine, std::default_delete<llvm::TargetMachine>>) JitRunner.cpp:0:0
 #7 0x000056435162bdc6 mlir::JitRunnerMain(int, char**, mlir::DialectRegistry const&, mlir::JitRunnerConfig) (/home/workdir/llvm-project/build/bin/mlir-runner+0x9f2dc6)
 #8 0x0000564350f48b4f main (/home/workdir/llvm-project/build/bin/mlir-runner+0x30fb4f)
 #9 0x00007f9576496d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#10 0x00007f9576496e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#11 0x0000564350f486c5 _start (/home/workdir/llvm-project/build/bin/mlir-runner+0x30f6c5)
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by CoTinker**
This PR fixes a crash if entry function has inputs. Fixes #136143.

### CODE REVIEW

**Review by matthias-springer — APPROVED** [review]

File: mlir/lib/ExecutionEngine/JitRunner.cpp [hunk 1]
```diff
@@ -222,9 +222,13 @@ static Error compileAndExecuteVoidFunction(
     CompileAndExecuteConfig config, std::unique_ptr<llvm::TargetMachine> tm) {
   auto mainFunction = dyn_cast_or_null<LLVM::LLVMFuncOp>(
       SymbolTable::lookupSymbolIn(module, entryPoint));
-  if (!mainFunction || mainFunction.empty())
+  if (!mainFunction || mainFunction.isExternal())
     return makeStringError("entry point not found");
 
+  if (cast<LLVM::LLVMFunctionType>(mainFunction.getFunctionType())
+          .getNumParams() != 0)
+    return makeStringError("function inputs not supported");
```
Comment (joker-eph) [inline mlir/lib/ExecutionEngine/JitRunner.cpp:230]:
```suggestion
    return makeStringError("JIT can't invoke a main function expecting arguments");
```

Somehow the errors in this file seem a bit short on description.

**Review by jpienaar — APPROVED** [review]
LG with Mehdi's comment addressed.
