### PR TITLE
[mlir][linalg] Fix EraseIdentityLinalgOp on fill-like ops

### LINKED ISSUE #129414: [mlir] Inconsistent results for linalg.generic
I have the following MLIR program:
test.mlir:
```
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @main() -> i32 {
    %c0_i32 = arith.constant 0 : i32
    %idx0 = index.constant 0
    %c1_i32 = arith.constant 1 : i32
    %alloc = memref.alloc() : memref<16x1x16xi32>
    linalg.fill ins(%c1_i32 : i32) outs(%alloc : memref<16x1x16xi32>)
    linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%alloc : memref<16x1x16xi32>) outs(%alloc : memref<16x1x16xi32>) {
    ^bb0(%in: i32, %out: i32):
      linalg.yield %c0_i32 : i32
    }
    %0 = memref.load %alloc[%idx0, %idx0, %idx0] : memref<16x1x16xi32>
    vector.print %0 : i32
    return %0 : i32
  }
}
```
When I ran 
```
/data/tmp/v0302/llvm-project/build/bin/mlir-opt \
--lower-affine --convert-index-to-llvm --convert-linalg-to-loops --convert-scf-to-cf --convert-arith-to-llvm --convert-vector-to-llvm --finalize-memref-to-llvm --convert-cf-to-llvm --convert-func-to-llvm --convert-arith-to-llvm --reconcile-unrealized-casts test.mlir | /data/tmp/v0302/llvm-project/build/bin/mlir-runner --entry-point-result=i32 --shared-libs=/data/tmp/v0302/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v0302/llvm-project/build/lib/libmlir_c_runner_utils.so
```
on the program, I got the result of:
```
0
0
```
However, when I ran 
```
/data/tmp/v0302/llvm-project/build/bin/mlir-opt \
--canonicalize \
--lower-affine --convert-index-to-llvm --convert-linalg-to-loops --convert-scf-to-cf --convert-arith-to-llvm --convert-vector-to-llvm --finalize-memref-to-llvm --convert-cf-to-llvm --convert-func-to-llvm --convert-arith-to-llvm --reconcile-unrealized-casts test.mlir | /data/tmp/v0302/llvm-project/build/bin/mlir-runner --entry-point-result=i32 --shared-libs=/data/tmp/v0302/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v0302/llvm-project/build/lib/libmlir_c_runner_utils.so
```
on the program, I got the result of:
```
1
1
```
The above two results seem to be inconsistent. I'm not sure if there is any bug in my program or if the wrong usage of the above passes caused these results.

My git version is b6d5fa05ada6e51ede32c62ff47f046ca5085d28.

### PR DESCRIPTION
**Pull request by IanWood1**
Adds a check to make sure that the linalg op is safe to erase by ensuring that the `linalg.yield` is yielding one of the linalg op's block args. This check already exists for linalg ops with pure tensor semantics.

Closes https://github.com/llvm/llvm-project/issues/129414

### CODE REVIEW

**Comment by mdehling** [comment]
@dcaballe @nicolasvasilache @rengolin Sorry to summon you like this :)

Is there any concern with this PR?  The fix looks good to me.

Asking because one of our engineers just spent some time looking into an issue and found this canonicalization bug to be the cause of it.

**Comment by banach-space** [comment]
This looks pretty straightforward and overall LGTM. That said, it's not my area of expertise, so an extra pair of eyes would be helpful.

I've left a few minor suggestions inline. Also - could you update the outdated comment above `EraseIdentityLinalgOp`?

> /// Remove any linalg operation (on tensors) that are just copying

And regarding:

> This check already exists for linalg ops with pure tensor semantics.

Is there a negative test for the tensor case?

File: mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp [hunk 1]
```diff
@@ -1304,18 +1305,24 @@ struct EraseIdentityLinalgOp : public OpRewritePattern<OpTy> {
...
     // In the buffer case, we need to check exact buffer equality.
     if (linalgOp.hasPureBufferSemantics()) {
-      if (linalgOp.getNumDpsInputs() == 1 && linalgOp.getNumDpsInits() == 1 &&
-          linalgOp.getDpsInputOperand(0)->get() ==
-              linalgOp.getDpsInitOperand(0)->get()) {
-        rewriter.eraseOp(linalgOp);
-        return success();
-      }
-      return failure();
+      if (linalgOp.getNumDpsInputs() != 1 || linalgOp.getNumDpsInits() != 1 ||
```
Comment (MaheshRavishankar) [inline mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp:1308]: Please add `{` `}` around multi-line statments here and below.

**Review by MaheshRavishankar — APPROVED** [review]
