### PR TITLE
[CUDA] make kernel stub ICF-proof

### LINKED ISSUE #88883: CUDA on Windows: COMDAT folding may cause wrong kernel to be launched
**Summary**

CUDA's kernel launch mechanism requires each kernel's device stub function to have a unique address. When targeting Windows, the linker defaults to performing identical COMDAT folding (ICF). Since the device stubs tend to be identical when the kernel arguments are the same, this deduplication can lead to non-unique addresses. In the end, attempting to invoke any of the kernels whose device stubs were folded into one will always invoke the first of these kernels.

**Version history**

@kpyzhov originally fixed this problem in 15e678e8438c56703c775fcb45afb25e09b31cff (Clang 9.0) by removing the COMDAT attribute from kernels and device stubs. @yxsamliu then introduced a regression in 80072fde61d40a4e8a9da673476730d34a483fa2 (Clang 14.0) that reallows COMDAT attributes on device stubs.

**Minimal working example**

```cuda
#include <stdio.h>
#include <cuda.h>

template<typename F>
__global__
void forEach(F f, int n) {
    int i = blockIdx.x*blockDim.x + threadIdx.x;
    if (i < n) {
        f(i);
    }
}

void check(cudaError_t err, unsigned line) {
    if (err != cudaSuccess) {
        printf("CUDA error in line %d: %s\n", line, cudaGetErrorName(err));
        exit(1);
    }
}
#define CHECK(err) check(err, __LINE__)

struct Test {
  void bad() {
    float *data = nullptr;

    forEach<<<1,1>>>([data] __host__ __device__ (int i) {
#ifdef __CUDA_ARCH__
        __trap(); 
#endif
    }, 1);
  }

  void good() {
    float *data;
    CHECK(cudaMalloc(reinterpret_cast<void**>(&data), sizeof(float)));
    CHECK(cudaMemset(data, 0xff, sizeof(float)));

    forEach<<<1,1>>>([data] __host__ __device__ (int i) {
        data[i] = 1.0f;
    }, 1);
    CHECK(cudaDeviceSynchronize());

    float host;
    CHECK(cudaMemcpy(&host, data, sizeof(float), cudaMemcpyDeviceToHost));
    if (host == 1.0f) {
        printf("success\n");
    } else {
        printf("failure\n");
    }

    CHECK(cudaFree(data));
  }
};


int main(int argc, char** argv)
{
    Test t;
    if (argc > 10) {
        t.bad();
    } else {
        t.good();
    }
    return 0;
}
```

**Reproduction**

Compile the above code with `clang.exe --target=x86_64-pc-windows-msvc -std=c++17 -O3 --cuda-gpu-arch=sm_75 -lcudart -fuse-ld=lld-link.exe -o test.exe test.cu` and then execute the binary without any command-line arguments. Observe a `cudaErrorLaunchFailure` coming from `cudaDeviceSynchronize()`. The issue can also be observed without `-fuse-ld=lld-link.exe`.

Now, add `-Wl,/OPT:NOICF` and observe that the error goes away. This is a fine workaround for the present bug, but obviously ICF may be desirable outside of CUDA device stubs.

For comparison, compile with NVCC (`nvcc.exe -std=c++17 -O3 -gencode arch=compute_75,code=sm_75 -cudart shared -extended-lambda -o test_nvcc.exe test.cu`) and observe that it runs successfully.

I've also posted the code to Godbolt: https://cuda.godbolt.org/z/15s87KPz6. Here you can see that Clang trunk and 8.0 generates the device stub as `define linkonce_odr dso_local ... comdat`, while Clang 11.0 generates it as `define linkonce_odr dso_local ...`.

### PR DESCRIPTION
**Pull request by yxsamliu**
MSVC linker merges functions having comdat which have identical set of instructions. CUDA uses kernel stub function as key to look up kernels in device executables. If kernel stub function for different kernels are merged by ICF, incorrect kernels will be launched.

To prevent ICF from merging kernel stub functions, an unique global variable is created for each kernel stub function having comdat and a store is added to the kernel stub function. This makes the set of instructions in each kernel function unique.

Fixes: https://github.com/llvm/llvm-project/issues/88883

### CODE REVIEW

File: clang/lib/CodeGen/CGCUDANV.cpp [hunk 1]
```diff
@@ -424,6 +424,34 @@ void CGNVCUDARuntime::emitDeviceStubBodyNew(CodeGenFunction &CGF,
...
   CGF.EmitCall(FI, CGCallee::forDirect(cudaLaunchKernelFn), ReturnValueSlot(),
                LaunchKernelArgs);
+
+  // To prevent CUDA device stub functions from being merged by ICF in MSVC
+  // environment, create an unique global variable for each kernel and write to
+  // the variable in the device stub.
+  if (CGM.getContext().getTargetInfo().getCXXABI().isMicrosoft() &&
+      !CGF.getLangOpts().HIP) {
+    llvm::Function *KernelFunction = llvm::cast<llvm::Function>(Kernel);
+    if (KernelFunction->hasComdat()) {
```
Comment (rnk) [inline clang/lib/CodeGen/CGCUDANV.cpp:434]: ICF may apply to all functions under [`/Gy`](https://learn.microsoft.com/en-us/cpp/build/reference/gy-enable-function-level-linking?view=msvc-170), and those are not reflected in the IR, so I would just do this for all kernels.

File: clang/lib/CodeGen/CGCUDANV.cpp [hunk 2]
```diff
@@ -424,6 +424,34 @@ void CGNVCUDARuntime::emitDeviceStubBodyNew(CodeGenFunction &CGF,
...
+      std::string KernelName = KernelFunction->getName().str();
```
Comment (rnk) [inline clang/lib/CodeGen/CGCUDANV.cpp:435]: Please avoid making an extra copy of the original name, since C++ names can be many kilobytes. Use `(KernelFunction->getName() + ".id").str()` to construct the `std::string`.

File: clang/lib/CodeGen/CGCUDANV.cpp [hunk 3]
```diff
@@ -424,6 +424,34 @@ void CGNVCUDARuntime::emitDeviceStubBodyNew(CodeGenFunction &CGF,
...
+        HandleVar = new llvm::GlobalVariable(
+            CGM.getModule(), CGM.Int8Ty,
+            /*Constant=*/false, KernelFunction->getLinkage(),
+            llvm::ConstantInt::get(CGM.Int8Ty, 0), GlobalVarName);
+        HandleVar->setDSOLocal(KernelFunction->isDSOLocal());
+        HandleVar->setVisibility(KernelFunction->getVisibility());
+        HandleVar->setComdat(CGM.getModule().getOrInsertComdat(GlobalVarName));
+      }
+
+      CGF.Builder.CreateAlignedStore(llvm::ConstantInt::get(CGM.Int8Ty, 1),
```
Comment (rnk) [inline clang/lib/CodeGen/CGCUDANV.cpp:450]: LLVM knows how to optimize away a single write to an otherwise unused global, so I would mark this store volatile.

File: clang/lib/CodeGen/CGCUDANV.cpp (hunk 1 above)
Comment (yxsamliu) [reply clang/lib/CodeGen/CGCUDANV.cpp:434]: will do

File: clang/lib/CodeGen/CGCUDANV.cpp (hunk 2 above)
Comment (yxsamliu) [reply clang/lib/CodeGen/CGCUDANV.cpp:435]: will do

File: clang/lib/CodeGen/CGCUDANV.cpp (hunk 3 above)
Comment (yxsamliu) [reply clang/lib/CodeGen/CGCUDANV.cpp:450]: will do

**Review by rnk — APPROVED** [review]
Looks good to me, thanks!
