### PR TITLE
[Sema] Fix lifetime extension for temporaries in range-based for loops in C++23

### LINKED ISSUE #109793: Unnecessary warning for the fixed range-based for loop in C++23
Consider (for the complete example, see: https://www.godbolt.org/z/oajGrd56M):

```
std::vector<std::string> getData() {  return {"OK?", "other", "ok"}; }

for (auto c : getData()[0]) {
  std::cout << c << '\n';
}
```

Iterating over a reference to an rvalue was an error before C++23, but since C++23 it no longer is.

Thanks for making the approporiate fix in clang. However, there is still a warning as if we don't have the fix. 

```
<source>:13:17: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
   13 |   for (auto c : getData()[0]) {
      |                 ^~~~~~~~~
1 warning generated.
ASM generation compiler returned: 0
<source>:13:17: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
   13 |   for (auto c : getData()[0]) {
      |                 ^~~~~~~~~
```

So, this warning should go away with C++23. Not sure how easy it is to fix it, though, as this is a special behavior just in the range-based for loop.

### PR DESCRIPTION
**Pull request by mrcvtl**
C++23 mandates that temporaries used in range-based for loops are lifetime-extended
to cover the full loop. This patch adds a check for loop variables and compiler-
generated `__range` bindings to apply the correct extension.

Includes test cases based on examples from CWG900/P2644R1.

Fixes https://github.com/llvm/llvm-project/issues/109793

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Could you associate this PR with the issue to fix, if any?

**Comment by mrcvtl** [comment]
> Could you associate this PR with the issue to fix, if any?

Done!

**Comment by mrcvtl** [comment]
A couple of quick notes:

- This is my first LLVM PR, so if there are any issues with code style or conventions, please let me know!
- I'm not entirely satisfied with the `VD->getName().starts_with("__range")` check, but it was the most reliable approach I found. Walking up the AST from the node didn’t seem feasible (likely due to optimizations?) and I noticed that pattern here: https://github.com/llvm/llvm-project/blob/075cb691a5e810f7114369c67b475dfd9127d4af/clang/lib/Sema/SemaStmt.cpp#L2481-L2485

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 1]
```diff
@@ -57,6 +57,31 @@ enum LifetimeKind {
...
 using LifetimeResult =
     llvm::PointerIntPair<const InitializedEntity *, 3, LifetimeKind>;
+
+/// Returns true if the given entity is part of a range-based for loop and
+/// should trigger lifetime extension under C++23 rules.
+///
+/// This handles both explicit range loop variables and internal compiler-
+/// generated variables like `__range1`.
+static bool
+isRangeBasedForLoopVariable(const Sema &SemaRef,
```
Comment (zwuis) [inline clang/lib/Sema/CheckExprLifetime.cpp]: This parameter type can be `const LangOptions &`.

File: clang/test/SemaCXX/range-for-lifetime-cxx23.cpp [hunk 2]
```diff
@@ -0,0 +1,79 @@
+// RUN: %clangxx -std=c++23 -fsyntax-only -Xclang -verify %s
```
Comment (zwuis) [inline clang/test/SemaCXX/range-for-lifetime-cxx23.cpp]: Use `%clang_cc1` for frontend tests.

`-Xclang` can be removed.

File: clang/test/SemaCXX/range-for-lifetime-cxx23.cpp [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+#include <string>
+#include <vector>
+#include <map>
+#include <tuple>
+#include <optional>
+#include <variant>
+#include <array>
+#include <span>
```
Comment (zwuis) [inline clang/test/SemaCXX/range-for-lifetime-cxx23.cpp]: Do not include files outside test folders. You can search `namespace std` to see how other test files handle this case.

**Review by zwuis — COMMENTED** [review]
Thank you for the patch!

Please add a release note in `clang/docs/ReleaseNotes.rst` so that users can know the improvement.

**Comment by yronglin** [comment]
> A couple of quick notes:
> 
> * This is my first LLVM PR, so if there are any issues with code style or conventions, please let me know!
> * I'm not entirely satisfied with the `VD->getName().starts_with("__range")` check, but it was the most reliable approach I found. Walking up the AST from the node didn’t seem feasible (likely due to optimizations?) and I noticed that pattern here: https://github.com/llvm/llvm-project/blob/075cb691a5e810f7114369c67b475dfd9127d4af/clang/lib/Sema/SemaStmt.cpp#L2481-L2485

Thanks for you fix!
Maybe we can use `isInLifetimeExtendingContext()` instead of check the `__range` variable name. We usually  get into an `LifetimeExtendingContex` in Sema. FYI, the initial PR is https://github.com/llvm/llvm-project/pull/76361.

File: clang/test/SemaCXX/range-for-lifetime-cxx23.cpp (hunk 3 above)
Comment (yronglin) [reply clang/test/SemaCXX/range-for-lifetime-cxx23.cpp]: We can construct some simple fake std dependencies.
Eg.
```cpp
namespace std {
  typedef decltype(sizeof(int)) size_t;
  template <class E>
  struct initializer_list {
    const E *begin;
    size_t   size;
    initializer_list() : begin(nullptr), size(0) {}
  };

  template <typename E>
  struct list {
    list() {}
    ~list() {}
    E *begin();
    E *end();
    const E *begin() const;
    const E *end() const;
  };

  template <typename E>
  struct vector {
    vector() {}
    vector(std::initializer_list<E>) {}
    ~vector() {}
    E *begin();
    E *end();
    const E *begin() const;
    const E *end() const;
  };
} // namespace std
```

**Comment by mrcvtl** [comment]
I’ve taken some time to better understand the code and think through the solution.

I tried using `isInLifetimeExtendingContext()`, but it still returns false, and I believe I now understand why. In your PR, the flag is set here:
https://github.com/llvm/llvm-project/blob/b581f9d056babadf55098b9d5d100271621b90db/clang/lib/Parse/ParseDecl.cpp#L2314-L2318

However, the warning is actually triggered starting from this location:
https://github.com/llvm/llvm-project/blob/b581f9d056babadf55098b9d5d100271621b90db/clang/lib/Parse/ParseDecl.cpp#L2266

An alternative approach would be to apply your logic and set again the flag in here:
https://github.com/llvm/llvm-project/blob/43d042b350af8ee8c7401d6b102df68d6c176b5a/clang/lib/Parse/ParseStmt.cpp#L2174-L2179

Maybe we could act on `ForRangeInfo.LifetimeExtendTemps.back()`, or even directly on `Actions.currentEvaluationContext();`. If that works, we might be able to rely solely on `isInLifetimeExtendingContext()` and remove the need for `isRangeBasedForLoopVariable` altogether.

What do you think? I'm absolutely open to every approach (the cleaner, the better!).

**Comment by yronglin** [comment]
> I’ve taken some time to better understand the code and think through the solution.
> 
> I tried using `isInLifetimeExtendingContext()`, but it still returns false, and I believe I now understand why. In your PR, the flag is set here:
> 
> https://github.com/llvm/llvm-project/blob/b581f9d056babadf55098b9d5d100271621b90db/clang/lib/Parse/ParseDecl.cpp#L2314-L2318
> 
> However, the warning is actually triggered starting from this location:
> 
> https://github.com/llvm/llvm-project/blob/b581f9d056babadf55098b9d5d100271621b90db/clang/lib/Parse/ParseDecl.cpp#L2266
> 
> An alternative approach would be to apply your logic and set again the flag in here:
> 
> https://github.com/llvm/llvm-project/blob/43d042b350af8ee8c7401d6b102df68d6c176b5a/clang/lib/Parse/ParseStmt.cpp#L2174-L2179
> 
> Maybe we could act on `ForRangeInfo.LifetimeExtendTemps.back()`, or even directly on `Actions.currentEvaluationContext();`. If that works, we might be able to rely solely on `isInLifetimeExtendingContext()` and remove the need for `isRangeBasedForLoopVariable` altogether.
> 
> What do you think? I'm absolutely open to every approach (the cleaner, the better!).

IMO, we have 2 options:
1. Add a flag variable into `ExpressionEvaluationContextRecord`. Represent that we are initializing the for-range __range variable. 
Eg.
```diff
diff --git a/clang/include/clang/Sema/Sema.h b/clang/include/clang/Sema/Sema.h
index 9397546c8fc5..c639a4b4af58 100644
--- a/clang/include/clang/Sema/Sema.h
+++ b/clang/include/clang/Sema/Sema.h
@@ -6786,6 +6786,9 @@ public:
     /// Whether we should rebuild CXXDefaultArgExpr and CXXDefaultInitExpr.
     bool RebuildDefaultArgOrDefaultInit = false;
 
+    /// Whether we are initializing a C++ for-range implicit variable '__range'.
+    bool InitCXXForRangeVar = false;
+
     // When evaluating immediate functions in the initializer of a default
     // argument or default member initializer, this is the declaration whose
     // default initializer is being evaluated and the location of the call
diff --git a/clang/lib/Sema/CheckExprLifetime.cpp b/clang/lib/Sema/CheckExprLifetime.cpp
index 060ba3166055..150e27f8acf7 100644
--- a/clang/lib/Sema/CheckExprLifetime.cpp
+++ b/clang/lib/Sema/CheckExprLifetime.cpp
@@ -1341,6 +1341,8 @@ checkExprLifetimeImpl(Sema &SemaRef, const InitializedEntity *InitEntity,
       }
 
       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
+        if (SemaRef.currentEvaluationContext().InitCXXForRangeVar)
+          return false;
         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
             << DiagRange;
         return false;
diff --git a/clang/lib/Sema/SemaStmt.cpp b/clang/lib/Sema/SemaStmt.cpp
index 923a9e81fbd6..da97d34854ac 100644
--- a/clang/lib/Sema/SemaStmt.cpp
+++ b/clang/lib/Sema/SemaStmt.cpp
@@ -2374,6 +2374,13 @@ static bool FinishForRangeVarDecl(Sema &SemaRef, VarDecl *Decl, Expr *Init,
       SemaRef.ObjC().inferObjCARCLifetime(Decl))
     Decl->setInvalidDecl();
 
+  // EnterExpressionEvaluationContext ForRangeInitContext(
+  //     SemaRef, Sema::ExpressionEvaluationContext::PotentiallyEvaluated,
+  //     /*LambdaContextDecl=*/nullptr,
+  //     Sema::ExpressionEvaluationContextRecord::EK_Other,
+  //     SemaRef.getLangOpts().CPlusPlus23);
+  if (SemaRef.getLangOpts().CPlusPlus23)
+    SemaRef.currentEvaluationContext().InitCXXForRangeVar = true;
   SemaRef.AddInitializerToDecl(Decl, Init, /*DirectInit=*/false);
   SemaRef.FinalizeDeclaration(Decl);
   SemaRef.CurContext->addHiddenDecl(Decl);
```
2. Introduce a bitfields into `clang::VarDecl::NonParmVarDeclBitfields`, like `CXXForRangeDecl`(Eg. `CXXForRangeImplicitVar`)

CC @cor3ntin

File: clang/test/SemaCXX/range-for-lifetime-cxx23.cpp (hunk 3 above)
Comment (yronglin) [reply clang/test/SemaCXX/range-for-lifetime-cxx23.cpp]: I have a more simple reproducer:
```cpp
using size_t = decltype(sizeof(void *));

namespace std {
template <typename T> struct vector {
  T &operator[](size_t I);
};

struct string {
  const char *begin();
  const char *end();
};

} // namespace std

extern "C" int printf(const char *, ...);

std::vector<std::string> getData();

void foo() {
  for (auto c : getData()[0]) {
    printf("%c\n", c);
  }
}

```

**Review by shafik — COMMENTED** [review]
As a previous comment noted, this needs a release note but I think the summary should also mention that this fixes the warning diagnostic from `-Wdangling-gsl`. Maybe worth a comment in the test explaining these are verifying we don't trigger a diagnostic from `-Wdangling-gsl`

File: clang/test/SemaCXX/range-for-lifetime-cxx23.cpp (hunk 3 above)
Comment (mrcvtl) [reply clang/test/SemaCXX/range-for-lifetime-cxx23.cpp]: Yup, my initial test was actually very similar (even if I used the stdlib), but I wanted to try out all the scenarios mentioned in the paper that you implemented. Since that doesn’t really make much sense, I’ll stick with this approach, thanks!

**Comment by mrcvtl** [comment]
> IMO, we have 2 options:
> 
> 1. Add a flag variable into `ExpressionEvaluationContextRecord`. Represent that we are initializing the for-range __range variable.
>    Eg.
> 
> ```diff
> diff --git a/clang/include/clang/Sema/Sema.h b/clang/include/clang/Sema/Sema.h
> index 9397546c8fc5..c639a4b4af58 100644
> --- a/clang/include/clang/Sema/Sema.h
> +++ b/clang/include/clang/Sema/Sema.h
> @@ -6786,6 +6786,9 @@ public:
>      /// Whether we should rebuild CXXDefaultArgExpr and CXXDefaultInitExpr.
>      bool RebuildDefaultArgOrDefaultInit = false;
>  
> +    /// Whether we are initializing a C++ for-range implicit variable '__range'.
> +    bool InitCXXForRangeVar = false;
> +
>      // When evaluating immediate functions in the initializer of a default
>      // argument or default member initializer, this is the declaration whose
>      // default initializer is being evaluated and the location of the call
> diff --git a/clang/lib/Sema/CheckExprLifetime.cpp b/clang/lib/Sema/CheckExprLifetime.cpp
> index 060ba3166055..150e27f8acf7 100644
> --- a/clang/lib/Sema/CheckExprLifetime.cpp
> +++ b/clang/lib/Sema/CheckExprLifetime.cpp
> @@ -1341,6 +1341,8 @@ checkExprLifetimeImpl(Sema &SemaRef, const InitializedEntity *InitEntity,
>        }
>  
>        if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
> +        if (SemaRef.currentEvaluationContext().InitCXXForRangeVar)
> +          return false;
>          SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>              << DiagRange;
>          return false;
> diff --git a/clang/lib/Sema/SemaStmt.cpp b/clang/lib/Sema/SemaStmt.cpp
> index 923a9e81fbd6..da97d34854ac 100644
> --- a/clang/lib/Sema/SemaStmt.cpp
> +++ b/clang/lib/Sema/SemaStmt.cpp
> @@ -2374,6 +2374,13 @@ static bool FinishForRangeVarDecl(Sema &SemaRef, VarDecl *Decl, Expr *Init,
>        SemaRef.ObjC().inferObjCARCLifetime(Decl))
>      Decl->setInvalidDecl();
>  
> +  // EnterExpressionEvaluationContext ForRangeInitContext(
> +  //     SemaRef, Sema::ExpressionEvaluationContext::PotentiallyEvaluated,
> +  //     /*LambdaContextDecl=*/nullptr,
> +  //     Sema::ExpressionEvaluationContextRecord::EK_Other,
> +  //     SemaRef.getLangOpts().CPlusPlus23);
> +  if (SemaRef.getLangOpts().CPlusPlus23)
> +    SemaRef.currentEvaluationContext().InitCXXForRangeVar = true;
>    SemaRef.AddInitializerToDecl(Decl, Init, /*DirectInit=*/false);
>    SemaRef.FinalizeDeclaration(Decl);
>    SemaRef.CurContext->addHiddenDecl(Decl);
> ```
> 
> 2. Introduce a bitfields into `clang::VarDecl::NonParmVarDeclBitfields`, like `CXXForRangeDecl`(Eg. `CXXForRangeImplicitVar`)
> 
> CC @cor3ntin

I like option one! Maybe a stupid question, but why can’t we use `InLifetimeExtendingContext` flag here? It feels like it’s meant to capture the same kind of situation. Is there a subtle difference I’m missing? 

I updated (locally) the PR to address the other feedbacks and I will push it to be reviewed when I have the green light to use option 1!

**Comment by yronglin** [comment]
> but why can’t we use InLifetimeExtendingContext flag here? 
> Is there a subtle difference I’m missing?

This flag will tiger subroutines to collect `MaterializedTemporaryExpr` and rebuild default init/arg。 All we need to know here is that `ExtendingDecl` is a C++ `__range` var in for-range-loop, so I think we should introduce a new flag in VarDecl. We may need to also modify handling of VarDecl in ASTWriter and ASTReader to ensure that the AST serialization is correct. WDYT?

**Comment by mrcvtl** [comment]
> > but why can’t we use InLifetimeExtendingContext flag here?
> > Is there a subtle difference I’m missing?
> 
> This flag will tiger subroutines to collect `MaterializedTemporaryExpr` and rebuild default init/arg。 All we need to know here is that `ExtendingDecl` is a C++ `__range` var in for-range-loop, so I think we should introduce a new flag in VarDecl. We may need to also modify handling of VarDecl in ASTWriter and ASTReader to ensure that the AST serialization is correct. WDYT?

Agreed.

My last commit should implement this. Let me know if something is wrong! 

Edit: I pushed again because I messed up with the branches, sorry!

File: clang/lib/Serialization/ASTWriterDecl.cpp [hunk 4]
```diff
@@ -2740,6 +2741,7 @@ void ASTWriter::WriteDeclAbbrevs() {
             // isInline, isInlineSpecified, isConstexpr,
             // isInitCapture, isPrevDeclInSameScope, hasInitWithSideEffects,
             // EscapingByref, HasDeducedType, ImplicitParamKind, isObjCForDecl
+            // isCXXForRangeDecl
```
Comment (mrcvtl) [inline clang/lib/Serialization/ASTWriterDecl.cpp:2744]: This should be `IsCXXForRangeImplicitVar`

File: clang/include/clang/AST/Decl.h [hunk 5]
```diff
@@ -1585,6 +1590,20 @@ class VarDecl : public DeclaratorDecl, public Redeclarable<VarDecl> {
...
+  /// variable used to hold the range expression in a C++11 and later for-range
+  /// statement.
+  bool isCXXForRangeImplicitVar() const {
+    return isa<ParmVarDecl>(this) ? false
+                                  : NonParmVarDeclBits.IsCXXForRangeImplicitVar;
+  }
+
+  void setCXXForRangeImplicitVar(bool FRV) {
+    assert(!isa<ParmVarDecl>(this) &&
+           "Cannot set IsCXXForRangeRangeVar on ParmVarDecl");
```
Comment (mrcvtl) [inline clang/include/clang/AST/Decl.h:1603]: Also here should be `Cannot set IsCXXForRangeRangeVar...`.

File: clang/include/clang/AST/Decl.h [hunk 6]
```diff
@@ -1584,6 +1589,20 @@ class VarDecl : public DeclaratorDecl, public Redeclarable<VarDecl> {
     NonParmVarDeclBits.IsCXXCondDecl = true;
   }
 
+  /// Determine whether this variable is the compiler-generated '__range'
```
Comment (yronglin) [inline clang/include/clang/AST/Decl.h]:
```suggestion
  /// Whether this variable is the implicit '__range' variable in C++ range-based for loops.
```

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 7]
```diff
@@ -57,6 +57,7 @@ enum LifetimeKind {
 };
 using LifetimeResult =
     llvm::PointerIntPair<const InitializedEntity *, 3, LifetimeKind>;
+
```
Comment (yronglin) [inline clang/lib/Sema/CheckExprLifetime.cpp]: Nit: Let's revert blank modification.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 8]
```diff
@@ -1341,6 +1342,13 @@ checkExprLifetimeImpl(Sema &SemaRef, const InitializedEntity *InitEntity,
       }
 
       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
+
+        if (SemaRef.getLangOpts().CPlusPlus23) {
+          if (const VarDecl *VD = cast<VarDecl>(InitEntity->getDecl());
```
Comment (yronglin) [inline clang/lib/Sema/CheckExprLifetime.cpp]:
```suggestion
          if (const VarDecl *VD = dyn_cast_if_present<VarDecl>(InitEntity->getDecl());
```

File: clang/lib/Sema/SemaStmt.cpp [hunk 9]
```diff
@@ -2374,6 +2374,9 @@ static bool FinishForRangeVarDecl(Sema &SemaRef, VarDecl *Decl, Expr *Init,
       SemaRef.ObjC().inferObjCARCLifetime(Decl))
     Decl->setInvalidDecl();
 
+  if (SemaRef.getLangOpts().CPlusPlus23)
```
Comment (yronglin) [inline clang/lib/Sema/SemaStmt.cpp]: I think we don't need this change. We already has a flag in `VarDecl`.

**Comment by mrcvtl** [comment]
Old clang tidy test failing seems flaky, locally it pass correctly. If it continue to fail I can rebase on upstream.

**Review by yronglin — APPROVED** [review]
Thanks for your fix! LGTM

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 10]
```diff
@@ -1341,6 +1341,14 @@ checkExprLifetimeImpl(Sema &SemaRef, const InitializedEntity *InitEntity,
       }
 
       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
+
+        if (SemaRef.getLangOpts().CPlusPlus23) {
```
Comment (hokein) [inline clang/lib/Sema/CheckExprLifetime.cpp]: the analysis is done here, and we filter out the result. I think we can filter out this case before (in `checkExprLifetimeImpl`) running the analysis to save some cost. 

Can you add a testcase (for the `lifetimebound` attr)? Make sure we don't warn on it

```
using size_t = decltype(sizeof(void *));

namespace my_ns {
template <typename T> struct vector {
  T &operator[](size_t I) [[clang::lifetimebound]];
};

struct string {
  const char *begin();
  const char *end();
};

} // namespace std

my_ns::vector<my_ns::string> getData();

void foo() {

  for (auto c : getData()[0]) {
    (void)c;
  }
}
```

Comment (mrcvtl) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Using `[[clang::lifetimebound]]` currently produces a warning, thanks for pointing it out!
Moving the check up to `checkExprLifetimeImpl`, as you suggested, also results in no warning for the test case you proposed.

However, after this change, running all Sema tests causes `SemaCXX/attr-lifetimebound.cpp to fail`, precisely because the warning is no longer emitted in the following case:

```
std::vector make_vector();
void use_reversed_range() {
  // FIXME: Don't expose the name of the internal range variable.
  for (auto x : reversed(make_vector())) {} // expected-warning {{temporary implicitly bound to local reference will be destroyed at the end of the full-expression}}
}
```

As this is seems exactly the test case you suggested, make sense to update this test instead of adding a new one?

Comment (yronglin) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Only update this test seems make sense.

Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Yeah, just update the existing test. The test file `attr-lifetimebound.cpp` is compiled with `-std=c++23`, we should not diagnose this test.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 11]
```diff
@@ -1304,6 +1304,13 @@ checkExprLifetimeImpl(Sema &SemaRef, const InitializedEntity *InitEntity,
   if (LK == LK_FullExpression)
     return;
 
+  if (LK == LK_Extended && SemaRef.getLangOpts().CPlusPlus23) {
```
Comment (mrcvtl) [inline clang/lib/Sema/CheckExprLifetime.cpp]: both this and the previous if condition can also be moved in the switch case after the temporary visitor. No strong opinion here.

Comment (hokein) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Is the `LK == LK_Extended` check necessary here? I think we can simply bail out in this case, regardless of the LK value.

**Review by hokein — COMMENTED** [review]
There are some test failures in the presubmit checks, you probably need to update these tests.

File: clang/lib/Sema/CheckExprLifetime.cpp (hunk 11 above)
Comment (mrcvtl) [reply clang/lib/Sema/CheckExprLifetime.cpp]: Yes, we can. We just need to check also for `InitEntity != nullptr` and it works I guess.

**Comment by mrcvtl** [comment]
> There are some test failures in the presubmit checks, you probably need to update these tests.

Yes, indeed. For example, in `AST/ast-dump-for-range-lifetime.cpp` we move from:
 `-MaterializeTemporaryExpr {{.*}} 'C':'P2718R0::C' xvalue extended by Var {{.*}} '__range1' 'C &&'` 
 to: 
`-MaterializeTemporaryExpr  {{.*}} 'C':'P2718R0::C' xvalue`. 
At a first look it seems like we are losing info in the AST, but also a couple of line later we got:
`-MaterializeTemporaryExpr {{.*}} 'const C':'const P2718R0::C' lvalue extended by Var {{.*}} '__range1' 'C &&'`
So it might be fine...

In `special/class.temporary/p6.cpp` instead is a bit more weird, because it seems we are losing some IR call in case of for-range loops. You can take a look in the logs of the failing test.

Given that I don't know enough about it to say if it is okay or not, I wanted to double check with you. What do you think?

**Comment by hokein** [comment]
> Yes, indeed. For example, in `AST/ast-dump-for-range-lifetime.cpp` we move from: `-MaterializeTemporaryExpr {{.*}} 'C':'P2718R0::C' xvalue extended by Var {{.*}} '__range1' 'C &&'` to: `-MaterializeTemporaryExpr {{.*}} 'C':'P2718R0::C' xvalue`. At a first look it seems like we are losing info in the AST, but also a couple of line later we got: `-MaterializeTemporaryExpr {{.*}} 'const C':'const P2718R0::C' lvalue extended by Var {{.*}} '__range1' 'C &&'` So it might be fine...
> 
> In `special/class.temporary/p6.cpp` instead is a bit more weird, because it seems we are losing some IR call in case of for-range loops. You can take a look in the logs of the failing test.
> 
> Given that I don't know enough about it to say if it is okay or not, I wanted to double check with you. What do you think?

Thanks for looking at them.

It seems this patch is causing some unexpected behavior changes. From what I can tell, this patch only adds a new bit to Decl, which shouldn’t affect the two failing tests. However, I don't spot any obvious cause by reading the patch. Maybe @yronglin has some insights here.

**Comment by yronglin** [comment]
I have debug the issue, seems we cannot move the `__range` variable check to the start of `checkExprLifetimeImpl`, we may missing extending lifetime of temporaries. 
Eg.
```cpp
template <typename T>
struct ListWrapper {
  ListWrapper() {}
  ~ListWrapper() {}
  const T *begin() const;
  const T *end() const;
  ListWrapper& r();
  ListWrapper g();
};

using A = ListWrapper<int>;

A g() { return A(); }
const A &f1(const A &t) { return t; }

void member_call() {
  // CHECK-CXX23: void @_ZN7P2718R011member_call11member_callEv()
  // CHECK-CXX23-LABEL: for.cond.cleanup:
  // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
  // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
  // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
  // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
  for (auto e : g().r().g().r().g().r().g()) {}
}
```
I think we should revert to the previous approach, what do you think?
```cpp
      if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
        if (const auto *VD =
                dyn_cast_if_present<VarDecl>(ExtendingEntity->getDecl());
            SemaRef.getLangOpts().CPlusPlus23 && VD &&
            VD->isCXXForRangeImplicitVar())
          return true;
        SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
            << DiagRange;
        return false;
      }
```

**Comment by mrcvtl** [comment]
> I have debug the issue, seems we cannot move the `__range` variable check to the start of `checkExprLifetimeImpl`, we may missing extending lifetime of temporaries. Eg.
> 
> ```c++
> template <typename T>
> struct ListWrapper {
>   ListWrapper() {}
>   ~ListWrapper() {}
>   const T *begin() const;
>   const T *end() const;
>   ListWrapper& r();
>   ListWrapper g();
> };
> 
> using A = ListWrapper<int>;
> 
> A g() { return A(); }
> const A &f1(const A &t) { return t; }
> 
> void member_call() {
>   // CHECK-CXX23: void @_ZN7P2718R011member_call11member_callEv()
>   // CHECK-CXX23-LABEL: for.cond.cleanup:
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   for (auto e : g().r().g().r().g().r().g()) {}
> }
> ```
> 
> I think we should revert to the previous approach, what do you think?
> 
> ```c++
>       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
>         if (const auto *VD =
>                 dyn_cast_if_present<VarDecl>(ExtendingEntity->getDecl());
>             SemaRef.getLangOpts().CPlusPlus23 && VD &&
>             VD->isCXXForRangeImplicitVar())
>           return true;
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>             << DiagRange;
>         return false;
>       }
> ```

Agree, there are some side effect that I can't fully understand.

> I have debug the issue, seems we cannot move the `__range` variable check to the start of `checkExprLifetimeImpl`, we may missing extending lifetime of temporaries. Eg.
> 
> ```c++
> template <typename T>
> struct ListWrapper {
>   ListWrapper() {}
>   ~ListWrapper() {}
>   const T *begin() const;
>   const T *end() const;
>   ListWrapper& r();
>   ListWrapper g();
> };
> 
> using A = ListWrapper<int>;
> 
> A g() { return A(); }
> const A &f1(const A &t) { return t; }
> 
> void member_call() {
>   // CHECK-CXX23: void @_ZN7P2718R011member_call11member_callEv()
>   // CHECK-CXX23-LABEL: for.cond.cleanup:
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   for (auto e : g().r().g().r().g().r().g()) {}
> }
> ```
> 
> I think we should revert to the previous approach, what do you think?
> 
> ```c++
>       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
>         if (const auto *VD =
>                 dyn_cast_if_present<VarDecl>(ExtendingEntity->getDecl());
>             SemaRef.getLangOpts().CPlusPlus23 && VD &&
>             VD->isCXXForRangeImplicitVar())
>           return true;
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>             << DiagRange;
>         return false;
>       }
> ```

I agree. There are so

> I have debug the issue, seems we cannot move the `__range` variable check to the start of `checkExprLifetimeImpl`, we may missing extending lifetime of temporaries. Eg.
> 
> ```c++
> template <typename T>
> struct ListWrapper {
>   ListWrapper() {}
>   ~ListWrapper() {}
>   const T *begin() const;
>   const T *end() const;
>   ListWrapper& r();
>   ListWrapper g();
> };
> 
> using A = ListWrapper<int>;
> 
> A g() { return A(); }
> const A &f1(const A &t) { return t; }
> 
> void member_call() {
>   // CHECK-CXX23: void @_ZN7P2718R011member_call11member_callEv()
>   // CHECK-CXX23-LABEL: for.cond.cleanup:
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   // CHECK-CXX23-NEXT: call void @_ZN7P2718R011member_call11ListWrapperIiED1Ev(
>   for (auto e : g().r().g().r().g().r().g()) {}
> }
> ```
> 
> I think we should revert to the previous approach, what do you think?
> 
> ```c++
>       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
>         if (const auto *VD =
>                 dyn_cast_if_present<VarDecl>(ExtendingEntity->getDecl());
>             SemaRef.getLangOpts().CPlusPlus23 && VD &&
>             VD->isCXXForRangeImplicitVar())
>           return true;
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>             << DiagRange;
>         return false;
>       }
> ```

Thanks for debugging that! 
I agree btw, didn't think about this side effect before.

**Comment by mrcvtl** [comment]
> I think we should revert to the previous approach, what do you think?
> 
> ```c++
>       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
>         if (const auto *VD =
>                 dyn_cast_if_present<VarDecl>(ExtendingEntity->getDecl());
>             SemaRef.getLangOpts().CPlusPlus23 && VD &&
>             VD->isCXXForRangeImplicitVar())
>           return true;
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>             << DiagRange;
>         return false;
>       }
> ```

Thanks for debugging that!
I agree btw, didn't think about this side effect before.

**Comment by mrcvtl** [comment]
Forgot that the revert wouldn't include the `lifetimebound` attribute. I restructured the switch case like that, in order to catch both:
```
    case LK_Extended: {
      if (!MTE) {
        // The initialized entity has lifetime beyond the full-expression,
        // and the local entity does too, so don't warn.
        //
        // FIXME: We should consider warning if a static / thread storage
        // duration variable retains an automatic storage duration local.
        return false;
      }
      
      switch (shouldLifetimeExtendThroughPath(Path)) {
      case PathLifetimeKind::Extend:
        assert(!IsGslPtrValueFromGslTempOwner); // Just a test, to be sure that we aren't losing something here.
                                                // can be removed safely I guess.
           
        // Update the storage duration of the materialized temporary.
        // FIXME: Rebuild the expression instead of mutating it.
        MTE->setExtendingDecl(ExtendingEntity->getDecl(),
                              ExtendingEntity->allocateManglingNumber());
        // Also visit the temporaries lifetime-extended by this initializer.
        return true;
      
    case PathLifetimeKind::NoExtend:
      if (SemaRef.getLangOpts().CPlusPlus23 && InitEntity) {
        if (const VarDecl *VD =
            dyn_cast_if_present<VarDecl>(InitEntity->getDecl());
            VD && VD->isCXXForRangeImplicitVar())
          return false;
      }
          
          
      if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
        SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
            << DiagRange;
        return false;
      }

        // If the path goes through the initialization of a variable or field,
        // it can't possibly reach a temporary created in this full-expression.
        // We will have already diagnosed any problems with the initializer.
        if (pathContainsInit(Path))
          return false;

        SemaRef.Diag(DiagLoc, diag::warn_dangling_variable)
            << RK << !InitEntity->getParent()
            << ExtendingEntity->getDecl()->isImplicit()
            << ExtendingEntity->getDecl() << Init->isGLValue() << DiagRange;
        break;
      }
      break;
    }
```

**Comment by yronglin** [comment]
> Forgot that the revert wouldn't include the `lifetimebound` attribute. I restructured the switch case like that, in order to catch both:
> 
> ```
>     case LK_Extended: {
>       if (!MTE) {
>         // The initialized entity has lifetime beyond the full-expression,
>         // and the local entity does too, so don't warn.
>         //
>         // FIXME: We should consider warning if a static / thread storage
>         // duration variable retains an automatic storage duration local.
>         return false;
>       }
>       
>       switch (shouldLifetimeExtendThroughPath(Path)) {
>       case PathLifetimeKind::Extend:
>         assert(!IsGslPtrValueFromGslTempOwner); // Just a test, to be sure that we aren't losing something here.
>                                                 // can be removed safely I guess.
>            
>         // Update the storage duration of the materialized temporary.
>         // FIXME: Rebuild the expression instead of mutating it.
>         MTE->setExtendingDecl(ExtendingEntity->getDecl(),
>                               ExtendingEntity->allocateManglingNumber());
>         // Also visit the temporaries lifetime-extended by this initializer.
>         return true;
>       
>     case PathLifetimeKind::NoExtend:
>       if (SemaRef.getLangOpts().CPlusPlus23 && InitEntity) {
>         if (const VarDecl *VD =
>             dyn_cast_if_present<VarDecl>(InitEntity->getDecl());
>             VD && VD->isCXXForRangeImplicitVar())
>           return false;
>       }
>           
>           
>       if (IsGslPtrValueFromGslTempOwner && DiagLoc.isValid()) {
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_lifetime_pointer)
>             << DiagRange;
>         return false;
>       }
> 
>         // If the path goes through the initialization of a variable or field,
>         // it can't possibly reach a temporary created in this full-expression.
>         // We will have already diagnosed any problems with the initializer.
>         if (pathContainsInit(Path))
>           return false;
> 
>         SemaRef.Diag(DiagLoc, diag::warn_dangling_variable)
>             << RK << !InitEntity->getParent()
>             << ExtendingEntity->getDecl()->isImplicit()
>             << ExtendingEntity->getDecl() << Init->isGLValue() << DiagRange;
>         break;
>       }
>       break;
>     }
> ```

Could you push the changes to this PR?

**Comment by hokein** [comment]
> I have debug the issue, seems we cannot move the __range variable check to the start of checkExprLifetimeImpl, we may missing extending lifetime of temporaries.

Ah, that makes sense -- I missed the fact that this part of the code is also responsible for extending the object’s lifetime. Thanks a lot for looking into this and clarifying it.

**Review by hokein — APPROVED** [review]
This change looks good to me.

**Review by yronglin — APPROVED** [review]
LGTM

**Comment by yronglin** [comment]
Do you need the help to merge this PR?

**Comment by mrcvtl** [comment]
> Do you need the help to merge this PR?

Yes please, also not sure if I can merge being my first PR.
Also should we wait on the third review? Not sure about the reviews policies!

**Comment by yronglin** [comment]
Congratulations, the first LLVM PR has landed!

**Comment by yronglin** [comment]
> LLVM Buildbot has detected a new failure on builder `sanitizer-aarch64-linux` running on `sanitizer-buildbot7` while building `clang` at step 2 "annotate".
> 
> Full details are available at: https://lab.llvm.org/buildbot/#/builders/51/builds/19520
> 
> Here is the relevant piece of the build log for the reference

This failure seem not caused by this PR.
