### PR TITLE
[libc++] Fix std::make_exception_ptr interaction with ObjC

### LINKED ISSUE #135089: [libc++] [libc++abi] Regression: std::make_exception_ptr breaks catching ObjC objects on rethrow
This is a regression introduced in LLVM commit 51e91b64d0deb6a743861c2a0fba84865250036e (PR #65534). The following code used to work prior to the change:

```objc++
#include <exception>
#import <Foundation/Foundation.h>

NSError* RecoverException(const std::exception_ptr& exc) {
  try {
    std::rethrow_exception(exc);
  } catch (NSError* error) {
    return error;
  } catch (...) {
  }
  return nil;
}

int main() {
  NSError* error = [NSError errorWithDomain:NSPOSIXErrorDomain code:EPERM userInfo:nil];
  std::exception_ptr exc = std::make_exception_ptr(error);
  NSError* recov = RecoverException(exc);
  if (recov) {
    printf("[+] PASS: %s\n", recov.description.UTF8String);
  } else {
    printf("[-] FAIL: Expected NSError, got nil\n");
  }
}
```

This kind of code may be written when working with an Objective-C++ codebase that uses exceptions, and NSError*/NSException* types need to be handled alongside C++ errors. I believe this is supported because Objective-C exceptions are [interoperable](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Exceptions/Articles/Exceptions64Bit.html#//apple_ref/doc/uid/TP40009044-SW1) with C++ exceptions.

This broke with the aforementioned commit because `std::make_exception_ptr` no longer internally throws the exception object and uses `std::current_exception` to capture the value. Instead, it directly allocates and populates the  `__cxxabiv1::__cxa_exception` using the C++ type information. However, when an ObjC exception is thrown natively, it uses [a different representation](https://github.com/apple-oss-distributions/objc4/blob/objc4-928.2/runtime/objc-exception.mm#L385) for the exception's typeinfo.

This is apparent when looking at the assembly output from `clang++ -S`. In the sample program above, the Catch TypeInfos in `GCC_except_table0` for `RecoverException()` is a `_OBJC_EHTYPE_$_NSError`. This corresponds to the type stored in a `struct objc_exception` produced in the ObjC runtime when an object is thrown via `objc_exception_throw`.

But in the assembly produced after that commit, the template instantiation for `std::exception_ptr std::make_exception_ptr<NSError*>(NSError*)` produces an exception with a reference to the `__ZTIP7NSError` typeinfo. I.e., after the commit, the exception stores the C++ typeinfo for the object, rather than the ObjC typeinfo. When the exception is rethrown, the catch arms fail to match because the typeinfos between the catch arm and the exception object do not match.

Putting a breakpoint on `RecoverException` and then inspecting the argument shows this too. After the commit:

```
(lldb) p *(((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)
(__cxxabiv1::__cxa_exception) {
  reserve = 0x0000000000000000
  referenceCount = 1
  exceptionType = 0x00000001000040a0
  exceptionDestructor = 0x0000000100000b8c (cocoa-exc`std::exception_ptr std::make_exception_ptr[abi:ne180000]<NSError*>(NSError*)::'lambda'(void*)::__invoke(void*) at exception_ptr.h:91)
  unexpectedHandler = 0x0000000100141570 (libc++abi.1.dylib`demangling_unexpected_handler() at cxa_default_handlers.cpp:90)
  terminateHandler = 0x000000010014138c (libc++abi.1.dylib`demangling_terminate_handler() at cxa_default_handlers.cpp:39)
  nextException = nil
  handlerCount = 0
  handlerSwitchValue = 0
  actionRecord = 0x0000000000000000
  languageSpecificData = 0x0000000000000000
  catchTemp = 0x0000000000000000
  adjustedPtr = 0x0000000000000000
  unwindHeader = {
    exception_class = 4849336966747728640
    exception_cleanup = 0x0000000100177288 (libc++abi.1.dylib`__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) at cxa_exception.cpp:134)
    private_1 = 0
    private_2 = 0
  }
}
(lldb) p/s (((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)->exceptionType->name()
(const char *) "P7NSError" "P7NSError"
(lldb) x/2a (((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)->exceptionType
0x1000040a0: 0x0000000100183bc0 libc++abi.1.0.dylib`vtable for __cxxabiv1::__pointer_type_info + 16
0x1000040a8: 0x8000000100000cf7 (0x0000000100000cf7) cocoa-exc`typeinfo name for NSError*
```

Before the commit:

```
(lldb) p *(((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)
(__cxxabiv1::__cxa_exception) {
  reserve = 0x0000000000000000
  referenceCount = 1
  exceptionType = 0x00006000008c4088
  exceptionDestructor = 0x000000019290b1ec (libobjc.A.dylib`_objc_exception_destructor(void*))
  unexpectedHandler = 0x0000000192c8dd30 (libc++abi.dylib`demangling_unexpected_handler())
  terminateHandler = 0x0000000192914cd8 (libobjc.A.dylib`_objc_terminate())
  nextException = nil
  handlerCount = 0
  handlerSwitchValue = 1
  actionRecord = 0x0000000100000bc1 "\U00000001"
  languageSpecificData = 0x0000000100000bb0 "\xff\x9b\U00000015\U00000001\f\U0000001c\U00000004(\U00000001 ("
  catchTemp = 0x0000000100000a90
  adjustedPtr = 0x00006000008c4080
  unwindHeader = {
    exception_class = 4849336966747728640
    exception_cleanup = 0x0000000192ca1af4 (libc++abi.dylib`__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*))
    private_1 = 0
    private_2 = 6171911792
  }
}
(lldb) p/s (((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)->exceptionType->name()
(const char *) "NSError" "NSError"
(lldb) x/2a (((__cxxabiv1::__cxa_exception*)exc.__ptr_)-1)->exceptionType
0x6000008c4088: 0x0000000202c44938 libobjc.A.dylib`objc_ehtype_vtable + 16
0x6000008c4090: 0x0000000194de7dfa "NSError"
```

Also filed as FB17179536.

### PR DESCRIPTION
**Pull request by itrofimow**
Clang treats throwing/catching ObjC types differently from C++ types, and omitting the `throw` in `std::make_exception_ptr` breaks ObjC invariants about how types are thrown/caught.

Fixes #135089

### CODE REVIEW

**Comment by jyknight** [comment]
It's not great to condition only on `__OBJC__` preprocessor define, since that'll create a potential ODR issue for std::make_exception_ptr on a C++ type, when you're mixing a TU built with C++ and another TU built with ObjC++ in the same program (which, everyone is).

If you switch to the `throw` impl only for ObjC object-pointers, that stops being a problem, as an ObjC object pointer type cannot exist in a non-ObjC++ TU.

As a refinement to my suggestion on the issue, I think `std::is_pointer_v<_Ep> && std::is_convertible_v<_Ep, id>` would be better (so as to not accidentally trigger on a C++ value with a user-defined conversion `operator id()`).

**Comment by jyknight** [comment]
Are you still planning to update this patch?

**Comment by itrofimow** [comment]
Hi! Yes, sorry, just got back to office

I was thinking, wouldn't just `std::is_pointer_v<_Ep>` condition be better it terms of readability?
After all, this is just an optimization, and given that people very seldom create exception pointers from pointers, it shouldn't be that much of a performance hit, and the less odd conditions we have here the better

**Comment by jyknight** [comment]
You mean without the OBJC ifdef? I think that would be OK. But IMO it's not actually an improvement, because the condition is no longer clearly connected with the actual _reason_ for the existence of the alternate codepath.

**Comment by itrofimow** [comment]
I don't think CI failure has to do with these changes, @jyknight could you please have a look?

File: libcxx/include/__exception/exception_ptr.h [hunk 1]
```diff
@@ -94,38 +95,50 @@ class _LIBCPP_EXPORTED_FROM_ABI exception_ptr {
 template <class _Ep>
 _LIBCPP_HIDE_FROM_ABI exception_ptr make_exception_ptr(_Ep __e) _NOEXCEPT {
 #  if _LIBCPP_HAS_EXCEPTIONS
-#    if _LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION && __cplusplus >= 201103L
-  using _Ep2 = __decay_t<_Ep>;
-
-  void* __ex = __cxxabiv1::__cxa_allocate_exception(sizeof(_Ep));
+#    if _LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION && __cplusplus >= 201703L
```
Comment (philnik777) [inline libcxx/include/__exception/exception_ptr.h:98]: This should really be `_LIBCPP_STD_VER >= 17`. Also, why did this change from C++11 to C++17?

Comment (itrofimow) [reply libcxx/include/__exception/exception_ptr.h:98]: This is about language-level features rather than libc++ features: c++11 or higher was required for the lambda to compile; c++17 or higher is now required for `if constexpr`

Comment (philnik777) [reply libcxx/include/__exception/exception_ptr.h:99]: Both are available as extensions in older versions. No need to put this behind a guard.

File: libcxx/include/__exception/exception_ptr.h [hunk 2]
```diff
@@ -95,37 +96,49 @@ template <class _Ep>
...
+    try {
+      ::new (__ex) _Ep2(__e);
+      return exception_ptr::__from_native_exception_pointer(__ex);
+    } catch (...) {
+      __cxxabiv1::__cxa_free_exception(__ex);
+      return current_exception();
+    }
   }
-#    else
+#    else // !(_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION && __cplusplus >= 201703L)
```
Comment (jyknight) [inline libcxx/include/__exception/exception_ptr.h]: comment looks wrong? Should be "201103L"

**Review by jyknight — COMMENTED** [review]
Change looks fine. 

But is there any way to add a test-case for this? (It's not clear to me there is since it depends on the non-llvm-project objc runtime, but it'd be great if there was.)

**Comment by rsesek** [comment]
> Change looks fine.
> 
> But is there any way to add a test-case for this? (It's not clear to me there is since it depends on the non-llvm-project objc runtime, but it'd be great if there was.)

There's some prior art in [`func.blocks.arc.pass.mm`](https://github.com/llvm/llvm-project/blob/e953623f50929dfa038d4d7d234f9822d63dc729/libcxx/test/libcxx/utilities/function.objects/func.blocks.arc.pass.mm) for depending on the Blocks runtime in a test. Not sure if it's also okay to depend on the host libobjc similarly.

**Comment by itrofimow** [comment]
I'll see what I can do about the test for this.
I don't think it's actually _necessary_ (but would be nice to have) to depend on objc runtime: maybe just a objc-codegen test is somewhat enough

**Comment by ldionne** [comment]
@itrofimow @jyknight Thanks for the PR. I updated the PR with a test and I refactored the code as a drive-by so it would be easier to understand -- after adding yet another `if` in there, the function was getting pretty hard to follow. Can you please have a look at the PR? I'd like to get it merged whenever possible.

**Comment by ldionne** [comment]
We might be able to make it into LLVM 20.1.9 if we end up having such a release.

File: libcxx/include/__exception/exception_ptr.h [hunk 3]
```diff
@@ -92,24 +93,18 @@ class _LIBCPP_EXPORTED_FROM_ABI exception_ptr {
 };
 
 template <class _Ep>
-_LIBCPP_HIDE_FROM_ABI exception_ptr make_exception_ptr(_Ep __e) _NOEXCEPT {
-#  if _LIBCPP_HAS_EXCEPTIONS
-#    if _LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION && __cplusplus >= 201103L
+_LIBCPP_HIDE_FROM_ABI exception_ptr __make_exception_ptr_explicit(_Ep& __e) _NOEXCEPT {
```
Comment (jyknight) [inline libcxx/include/__exception/exception_ptr.h:98]: Probably both these new helper functions need to be guarded by `#if _LIBCPP_HAS_EXCEPTIONS`; at the least the one with throw/catch needs to be since that doesn't compile without exceptions enabled.

File: libcxx/include/__exception/exception_ptr.h [hunk 4]
```diff
@@ -118,14 +113,42 @@ _LIBCPP_HIDE_FROM_ABI exception_ptr make_exception_ptr(_Ep __e) _NOEXCEPT {
...
+  // That function creates an exception with a special Objective-C typeinfo instead of
+  // the usual C++ typeinfo, since that is needed to implement the behavior documented
+  // at [1]).
+  //
+  // Because of this special behavior, we can't create an exception via `__cxa_init_primary_exception`
+  // for Objective-C exceptions, otherwise we'd bypass `objc_exception_throw`. See https://llvm.org/PR135089.
+  //
+  // [1]:
+  // https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Exceptions/Articles/Exceptions64Bit.html
+  if constexpr (is_pointer<_Ep>::value) {
```
Comment (ldionne) [inline libcxx/include/__exception/exception_ptr.h]: Here, if there was a way to query Clang whether `_Ep` is an Objective-C pointer type, that would match exactly the condition they use in https://github.com/llvm/llvm-project/blob/5b384c3015100ad815f4d994d7ef35cc947db711/clang/lib/CodeGen/CGException.cpp#L456 to decide whether to generate an Objective-C `throw` or a normal C++ `throw`. Do you think that is something we should be able to query directly from Clang?

Comment (jyknight) [reply libcxx/include/__exception/exception_ptr.h]: I had suggested `std::is_pointer_v<_Ep> && std::is_convertible_v<_Ep, id>` earlier if we want to avoid C++ pointers.

Comment (ldionne) [reply libcxx/include/__exception/exception_ptr.h]: The problem is that `id` is not a known identifier in C++, so we have to guard this with an `#ifdef` checking whether we're compiling in Objective-C mode, and I think we had ODR issues with doing that?

Naively adding the check right now, I get:

```
exception_ptr.h:141:71: error: use of undeclared identifier 'id'
```

**Comment by ldionne** [comment]
Gentle ping @itrofimow @jyknight WDYT about the current PR? It's passing CI and I'd like to get it merged whenever possible!

**Comment by itrofimow** [comment]
Hi @ldionne! Thank you for taking care of this PR, I've got completely consumed by work and absolutely failed to clean up my own mess in time.

Personally, I don't think narrowing the "could it be ObjC type" condition any further via compiler intrinsics is worth it: for me (as someone who just reads libcxx source code from time to time, not a maintainer) the mere presence of ObjC-related code/comments in libcxx seems confusing enough, and I'd say that `std::make_exception_ptr<T*>` in C++ is a use-case too niche to further complicate code here, especially via something directly ObjC-related.

Nice refactoring by you, and I'm happy to see CI finally working.

LGTM

File: libcxx/include/__exception/exception_ptr.h (hunk 4 above)
Comment (jyknight) [reply libcxx/include/__exception/exception_ptr.h]: Right; it needs an ifdef. That shouldn't cause issues -- I think -- because the template arg cannot be an ObjC type and thus convertible to id if it's not an objc file. The reason not to do it was just itrofimow's feeling it was too complicated. It may well be, I don't have strong feelings here. So probably best to just leave it the way you have it now.

**Review by jyknight — APPROVED** [review]

**Comment by ldionne** [comment]
Thanks for the reviews. I'll merge this once CI is green.

**Comment by ldionne** [comment]
CI is red for reasons unrelated to this patch, landing.
