### PR TITLE
[Clang] Ensure ``if consteval`` consititute an immediate function context

### LINKED ISSUE #91509: [Clang] [Sema] C++23 consteval if not recognised as immediate function context in templated function
Consider <https://godbolt.org/z/qTexTzKrb>:

```c++
consteval int f(int) { return 0; }

template<typename T>
constexpr int g(int x) {
    if consteval {
        return f(x);
    }
    return 1;
}

int h(int x) {
    return g<void>(x);
}
```

The invocation being inside the `if consteval` means it's in an immediate function context ([[expr.const]p(16.3)](https://eel.is/c++draft/expr.const#16.3)), so it shouldn't be immediate-escalating, and `g<void>` should *not* be an immediate function, yet Clang complains that it is.

```
<source>:12:12: error: call to immediate function 'g<void>' is not a constant expression
   12 |     return g<void>(x);
      |            ^
<source>:6:16: note: 'g<void>' is an immediate function because its body contains a call to a consteval function 'f' and that call is not a constant expression
    6 |         return f(x);
      |                ^~~~
<source>:12:20: note: function parameter 'x' with unknown value cannot be used in a constant expression
   12 |     return g<void>(x);
      |                    ^
<source>:11:11: note: declared here
   11 | int h(int x) {
      |           ^
```

### PR DESCRIPTION
**Pull request by cor3ntin**
We did not set the correct evaluation context for the compound statement of an ``if consteval`` statement
in a templated entity in TreeTransform.

Fixes #91509

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -7964,6 +7964,15 @@ TreeTransform<Derived>::TransformIfStmt(IfStmt *S) {
...
   StmtResult Then;
   if (!ConstexprConditionValue || *ConstexprConditionValue) {
+    Sema::ExpressionEvaluationContext Context =
+        S->isNonNegatedConsteval()
+            ? Sema::ExpressionEvaluationContext::ImmediateFunctionContext
+            : Sema::ExpressionEvaluationContext::PotentiallyEvaluated;
+
+    EnterExpressionEvaluationContext Ctx(
+        getSema(), Context, nullptr,
+        Sema::ExpressionEvaluationContextRecord::EK_Other);
```
Comment (MitalAshok) [inline clang/lib/Sema/TreeTransform.h:7974]:
```suggestion
    EnterExpressionEvaluationContext Ctx(
        getSema(), Sema::ExpressionEvaluationContext::ImmediateFunctionContext, nullptr,
        Sema::ExpressionEvaluationContextRecord::EK_Other,
        S->isNonNegatedConsteval());
```

(and ditto for the else branch) to only push a context if needed

Comment (cor3ntin) [reply clang/lib/Sema/TreeTransform.h]: You are right, it's nicer this way, thanks.

**Review by erichkeane — APPROVED** [review]
