### PR TITLE
Move interceptors for libresolv functions to MSan

### LINKED ISSUE #59007: AddressSanitizer:DEADLYSIGNAL in getaddrinfo() when compiled with clang-15 with "-nodefaultlibs" without "-lresolv"
The following code
```cpp
#include <arpa/inet.h>
#include <netdb.h>
#include <stdio.h>

int main() {
  addrinfo hints = {};
  addrinfo* res;
  getaddrinfo("api.binance.com", nullptr, &hints, &res);
  printf("%s\n", inet_ntoa(reinterpret_cast<sockaddr_in*>(res->ai_addr)->sin_addr));
  freeaddrinfo(res);
  return 0;
}
```
compiled with
```shell
clang-15 -fsanitize=address test.cpp -nodefaultlibs -lgcc_eh -lc -lm -lpthread -ldl
```
produces the following error:
```console
$ ./a.out
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1010333==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffd91eac050 sp 0x7ffd91eab808 T0)
==1010333==Hint: pc points to the zero page.
==1010333==The signal is caused by a READ memory access.
==1010333==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x7f5bab6b6805 in gaih_getanswer_slice /build/glibc-SzIz7B/glibc-2.31/resolv/nss_dns/dns-host.c:1147:8

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==1010333==ABORTING
```

If `-lresolv` option is added, it works as expected:

```console
$ clang-15 -fsanitize=address test.cpp -nodefaultlibs -lgcc_eh -lc -lm -lpthread -ldl -lresolv -o b.out && ./b.out
13.32.142.177
```
It also works as expected if I use `clang-14` instead of `clang-15`.

This is a very practical issue, because it is reproduced when using python's `requests` module with dynamically loaded sanitizer runtime (necessary when using sanitized python extensions):
```console
$ LD_PRELOAD=$(clang++-15 -print-file-name=libclang_rt.asan-x86_64.so) python -c 'import requests
print(requests.get("https://api.binance.com/"))'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==919440==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffe180677c0 sp 0x7ffe18066f78 T0)
==919440==Hint: pc points to the zero page.
==919440==The signal is caused by a READ memory access.
==919440==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x7f3048604805 in gaih_getanswer_slice /build/glibc-SzIz7B/glibc-2.31/resolv/nss_dns/dns-host.c:1147:8

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==919440==ABORTING
```

More info:
```console
$ ldd ./a.out # this one crashes
	linux-vdso.so.1 (0x00007ffc6537a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f77efcbf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f77efb70000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f77efb4d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f77efb47000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77f0930000)

$ ldd ./b.out # this one does not crash
	linux-vdso.so.1 (0x00007ffde1385000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15e3c18000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f15e3ac9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15e3aa6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f15e3aa0000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f15e3a84000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15e488c000)

$ clang-15 --version
Ubuntu clang version 15.0.4-++20221031075612+08bd84e8a635-1~exp1~20221031075700.87
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ python --version
Python 3.8.10

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

I posted the same bug at https://github.com/google/sanitizers/issues/1592, because I am not sure if it is related to sanitizers or clang-15.

### PR DESCRIPTION
**Pull request by aaronpuchert**
The functions are not relevant for most sanitizers and only required for MSan to see which regions have been written to. This eliminates a link dependency for all other sanitizers and fixes #59007: while `-lresolv` had been added for the static runtime in 6dce56b2a308, it wasn't added to the shared runtimes.

Instead of just moving the interceptors, we adapt them to MSan conventions:
* We don't skip intercepting when `msan_init_is_running` is true, but directly call ENSURE_MSAN_INITED() like most other interceptors. It seems unlikely that these functions are called during initialization.
* We don't unpoison `errno`, because none of the functions is specified to use it.

### CODE REVIEW

File: clang/lib/Driver/ToolChains/CommonArgs.cpp [hunk 1]
```diff
@@ -1410,7 +1410,7 @@ void tools::linkSanitizerRuntimeDeps(const ToolChain &TC,
   // libresolv.a, even if exists, is an empty archive to satisfy POSIX -lresolv
   // requirement.
   if (TC.getTriple().isOSLinux() && !TC.getTriple().isAndroid() &&
-      !TC.getTriple().isMusl())
+      !TC.getTriple().isMusl() && TC.getSanitizerArgs(Args).needsMsanRt())
```
Comment (aaronpuchert) [inline clang/lib/Driver/ToolChains/CommonArgs.cpp:1413]: This is not very efficient, because `getSanitizerArgs` actually extracts them from `Args` every time it is called. I've started working on a change to fix that.

**Review by aaronpuchert — COMMENTED** [review]
Regarding the removed test: there is still the MSan-specific test [compiler-rt/test/msan/Linux/b64.cpp](https://github.com/llvm/llvm-project/blob/main/compiler-rt/test/msan/Linux/b64.cpp).

File: clang/lib/Driver/ToolChains/CommonArgs.cpp (hunk 1 above)
Comment (vitalybuka) [reply clang/lib/Driver/ToolChains/CommonArgs.cpp:1413]: I propose do not change this part at all, or in a separate PR

**Review by vitalybuka — APPROVED** [review]

File: clang/lib/Driver/ToolChains/CommonArgs.cpp (hunk 1 above)
Comment (aaronpuchert) [reply clang/lib/Driver/ToolChains/CommonArgs.cpp:1413]: Done in #119442.

**Comment by nico** [comment]
This broke Linux/dn_expand.cpp on our bots, see https://issues.chromium.org/issues/384188036

**Comment by nico** [comment]
I reverted this in 1464b8ec8a675fd11dc7280db1c56aac03771b0a for now.

**Comment by aaronpuchert** [comment]
@nico, could you provide some more information? This didn't break on the lab.llvm.org infrastructure, and I'm not sure what's different in your build. Locally I also used a Release build with assertions on x86_64 on Linux.

For what it's worth, the change simply moves the interceptors, and it should still unpoison for the length of the string plus one. So I'm not sure why the last byte of the string is poisoned for you.

**Comment by aaronpuchert** [comment]
Specifically, this is the output:
```
 Uninitialized bytes in strcmp at offset 0 inside [0x7fffffffe1e0, 12)
 ==1131638==WARNING: MemorySanitizer: use-of-uninitialized-value
     #0 0x55555565c159 in testWrite() /b/s/w/ir/cache/builder/src/third_party/llvm/compiler-rt/test/msan/Linux/dn_expand.cpp:20:3
```
The code:
```c++
  assert(res == 12);
  assert(strcmp(output, "google\\.com") == 0); // line 20
  __msan_check_mem_is_initialized(output, strlen(output) + 1);
```
The expected string has 11 characters, and in the old (and new) interceptor we have `__msan_unpoison(dest, internal_strlen(dest) + 1);`. Do you get the same result for the function? Does `internal_strlen` not return 11? Or does `__msan_unpoison` not work?

**Comment by nico** [comment]
I'll try to find a Linux box tomorrow to get more details. https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8728518597999528929/+/u/package_clang/stdout?format=raw is the full build output. If you ctrl-f for "cmake -G", you should find all cmake vars that that bot sets. (It first builds a bootstrap compiler, then an instrumented compiler, then a final compiler, then compiler-rt with that.)

**Comment by nico** [comment]
@alanzhao1 has been trying to reproduce the problem, I think. I'm not sure what the current status is.

**Comment by alanzhao1** [comment]
Managed to reproduce it. This seems to break if the sysroot is set to the one Chrome uses. Our sysroot can be downloaded at https://commondatastorage.googleapis.com/chrome-linux-sysroot/dec7a3a0fc5b83b909cba1b6d119077e0429a138eadef6bf5a0f2e03b1904631

Command I used:

```
$ cmake -DLLVM_ENABLE_LLD=ON -DCMAKE_USE_LINKER=/usr/bin/lld  -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLLVM_ENABLE_ZSTD=OFF -DLLVM_TARGETS_TO_BUILD='X86' -DLLVM_ENABLE_RUNTIMES='compiler-rt' -DCOMPILER_RT_BUILD_SANITIZERS=ON -DCOMPILER_RT_SANITIZERS_TO_BUILD='asan;dfsan;msan;hwasan;tsan;cfi' -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang' -DLLVM_ENABLE_PIC=OFF -DCMAKE_SYSROOT='/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm-build-tools/debian_bullseye_amd64_sysroot' -DRUNTIMES_i386-unknown-linux-gnu_CMAKE_SYSROOT=/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm-build-tools/debian_bullseye_i386_sysroot -DBUILTINS_i386-unknown-linux-gnu_CMAKE_SYSROOT=/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm-build-tools/debian_bullseye_i386_sysroot -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON -G Ninja ../llvm

$ ninja check-runtimes
```

**Comment by aaronpuchert** [comment]
Where do I find these?
```
-DRUNTIMES_i386-unknown-linux-gnu_CMAKE_SYSROOT=/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm-build-tools/debian_bullseye_i386_sysroot \
-DBUILTINS_i386-unknown-linux-gnu_CMAKE_SYSROOT=/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm-build-tools/debian_bullseye_i386_sysroot
```
Or are they not relevant, because we're actually interested in 64-bit x86?

**Comment by aaronpuchert** [comment]
Without these two options, the build fails for me:
```
FAILED: bin/llvm-jitlink
: && /usr/bin/clang++ --sysroot=/home/aaron/chrome-sysroot -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -fno-pie -fuse-ld=lld -Wl,--color-diagnostics   -Wl,--export-dynamic  -Wl,--gc-sections tools/llvm-jitlink/CMakeFiles/llvm-jitlink.dir/llvm-jitlink.cpp.o tools/llvm-jitlink/CMakeFiles/llvm-jitlink.dir/llvm-jitlink-coff.cpp.o tools/llvm-jitlink/CMakeFiles/llvm-jitlink.dir/llvm-jitlink-elf.cpp.o tools/llvm-jitlink/CMakeFiles/llvm-jitlink.dir/llvm-jitlink-macho.cpp.o tools/llvm-jitlink/CMakeFiles/llvm-jitlink.dir/llvm-jitlink-statistics.cpp.o -o bin/llvm-jitlink  -Wl,-rpath,"\$ORIGIN/../lib:"  [...]  -ldl  -lpthread  -lm  /home/aaron/chrome-sysroot/usr/lib/x86_64-linux-gnu/libz.so  lib/libLLVMDemangle.a && :
ld.lld: error: undefined symbol: shm_open
>>> referenced by MemoryMapper.cpp
>>>               MemoryMapper.cpp.o:(llvm::orc::SharedMemoryMapper::reserve(unsigned long, llvm::unique_function<void (llvm::Expected<llvm::orc::ExecutorAddrRange>)>)::$_0::operator()(llvm::Error, llvm::Expected<std::pair<llvm::orc::ExecutorAddr, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>)) in archive lib/libLLVMOrcJIT.a
>>> did you mean: sem_open
>>> defined in: /home/aaron/chrome-sysroot/usr/lib/x86_64-linux-gnu/libpthread.so

ld.lld: error: undefined symbol: shm_unlink
>>> referenced by MemoryMapper.cpp
>>>               MemoryMapper.cpp.o:(llvm::orc::SharedMemoryMapper::reserve(unsigned long, llvm::unique_function<void (llvm::Expected<llvm::orc::ExecutorAddrRange>)>)::$_0::operator()(llvm::Error, llvm::Expected<std::pair<llvm::orc::ExecutorAddr, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>)) in archive lib/libLLVMOrcJIT.a
>>> did you mean: sem_unlink
>>> defined in: /home/aaron/chrome-sysroot/usr/lib/x86_64-linux-gnu/libpthread.so
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Apparently we're missing `-lrt`, which has the functions:
```
> readelf --dyn-syms --wide  /home/aaron/chrome-sysroot/usr/lib/x86_64-linux-gnu/librt.so | grep shm
    55: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __shm_directory@GLIBC_PRIVATE (12)
    73: 0000000000004640   353 FUNC    GLOBAL DEFAULT   14 shm_open@@GLIBC_2.2.5
    91: 00000000000047b0   303 FUNC    GLOBAL DEFAULT   14 shm_unlink@@GLIBC_2.2.5
```
Why are we not linking with that? It's correctly detected:
```
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
```
Have to investigate. Without sysroot but otherwise the same command line I can't reproduce it.

**Comment by aaronpuchert** [comment]
That configuration output is from `compiler-rt`, but we need it in `llvm`. In `llvm/lib/ExecutionEngine/Orc/CMakeLists.txt`:
```cmake
if( CMAKE_HOST_UNIX AND HAVE_LIBRT )
  set(rt_lib rt)
endif()
```
We have `CMAKE_HOST_UNIX` = 1, but `HAVE_LIBRT` is empty. It comes from `check_library_exists(rt clock_gettime "" HAVE_LIBRT)` in `llvm/cmake/config-ix.cmake`. The corresponding output:
```
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
```
This looks correct to me:
```
> readelf --dyn-syms --wide /home/aaron/chrome-sysroot/usr/lib/x86_64-linux-gnu/librt.so | grep clock_gettime
    38: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __clock_gettime@GLIBC_PRIVATE (7)
```
Instead it's in `libc.so.6`:
```
> readelf --dyn-syms --wide /home/aaron/chrome-sysroot/lib/x86_64-linux-gnu/libc.so.6 | grep clock_gettime
   840: 00000000000c3420   111 FUNC    GLOBAL DEFAULT   13 __clock_gettime@@GLIBC_PRIVATE
  1748: 00000000000c3420   111 FUNC    GLOBAL DEFAULT   13 clock_gettime@GLIBC_2.2.5
  1751: 00000000000c3420   111 FUNC    GLOBAL DEFAULT   13 clock_gettime@@GLIBC_2.17
```
On my system that's not an issue because `libc.so` has both `clock_gettime` and `shm_open`, so `librt.so` is never needed. Do you have any additional patches or why does this work for you?

**Comment by aaronpuchert** [comment]
With my change reverted I get the failure as well:
```
FAIL: SanitizerCommon-msan-x86_64-Linux :: Linux/dn_expand.cpp (5088 of 5094)
******************** TEST 'SanitizerCommon-msan-x86_64-Linux :: Linux/dn_expand.cpp' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 1: [...]/bin/clang  --driver-mode=g++ -gline-tables-only -fsanitize=memory  -funwind-tables --sysroot=/home/aaron/chrome-sysroot  -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/msan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp &&  [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/msan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
+ [...]/bin/clang --driver-mode=g++ -gline-tables-only -fsanitize=memory -funwind-tables --sysroot=/home/aaron/chrome-sysroot -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/msan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp
+ [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/msan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
MemorySanitizer:DEADLYSIGNAL
==18030==ERROR: MemorySanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x000000000400 sp 0x7ffe85eb3638 T18030)
==18030==Hint: pc points to the zero page.
==18030==The signal is caused by a READ memory access.
==18030==Hint: address points to the zero page.
    #0 0x000000000000  (<unknown module>)
    #1 0x55e9e7fc6f54 in __sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int) [...]/compiler-rt/lib/msan/msan.cpp:342:12
    #2 0x55e9e7fbf356 in ReportDeadlySignalImpl [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:275:3
    #3 0x55e9e7fbf356 in __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:289:5
    #4 0x55e9e7fbf6e0 in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:298:3
    #5 0x7fe82565797f  (/lib64/libc.so.6+0x5797f) (BuildId: 4f849c7c3d8ac76c5b3bafcb925d42a5e83bc222)

==18030==Register values:
rax = 0x00002fe825ca8690  rbx = 0x00007ffe85eb3690  rcx = 0x00007ffe85eb3690  rdx = 0x00007ffe85eb3aa7
rdi = 0x00007ffe85eb3a90  rsi = 0x00007ffe85eb3ab3  rbp = 0x0000000000000400  rsp = 0x00007ffe85eb3638
 r8 = 0x0000000000000400   r9 = 0x00007fe825d1247e  r10 = 0x00007fe825618de0  r11 = 0x00007fe8256413be
r12 = 0x00007ffe85eb3a90  r13 = 0xffffaf0000000000  r14 = 0x00007ffe85eb3aa7  r15 = 0x00007ffe85eb3ab3
MemorySanitizer can not provide additional info.
SUMMARY: MemorySanitizer: SEGV (<unknown module>)
==18030==ABORTING

--

********************
FAIL: SanitizerCommon-asan-x86_64-Linux :: Linux/dn_expand.cpp (5090 of 5094)
******************** TEST 'SanitizerCommon-asan-x86_64-Linux :: Linux/dn_expand.cpp' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 1: [...]/bin/clang  --driver-mode=g++ -gline-tables-only -fsanitize=address  -funwind-tables --sysroot=/home/aaron/chrome-sysroot  -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/asan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp &&  [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/asan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
+ [...]/bin/clang --driver-mode=g++ -gline-tables-only -fsanitize=address -funwind-tables --sysroot=/home/aaron/chrome-sysroot -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/asan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp
+ [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/asan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
AddressSanitizer:DEADLYSIGNAL
=================================================================
==18038==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffd1ccba1b0 sp 0x7ffd1ccb9968 T0)
==18038==Hint: pc points to the zero page.
==18038==The signal is caused by a READ memory access.
==18038==Hint: address points to the zero page.
    #0 0x000000000000  (<unknown module>)
    #1 0x55b3f6ded096 in testWrite() [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp:16:13
    #2 0x55b3f6ded9ba in main [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp:86:3
    #3 0x7f4f98c40eeb in __libc_start_call_main (/lib64/libc.so.6+0x40eeb) (BuildId: 4f849c7c3d8ac76c5b3bafcb925d42a5e83bc222)

==18038==Register values:
rax = 0x00000000970de001  rbx = 0x00007b4f970de070  rcx = 0x00007b4f970de070  rdx = 0x00007b4f970de037
rdi = 0x00007b4f970de020  rsi = 0x00007b4f970de043  rbp = 0x00007ffd1ccba1b0  rsp = 0x00007ffd1ccb9968
 r8 = 0x0000000000000400   r9 = 0x0000000000000000  r10 = 0x00000f69f2e1bc08  r11 = 0x0000000000000003
r12 = 0x00007b4f970de043  r13 = 0x00007b4f970de070  r14 = 0x00000000970de000  r15 = 0x00007b4f970de037
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==18038==ABORTING

--

********************
FAIL: SanitizerCommon-tsan-x86_64-Linux :: Linux/dn_expand.cpp (5094 of 5094)
******************** TEST 'SanitizerCommon-tsan-x86_64-Linux :: Linux/dn_expand.cpp' FAILED ********************
Exit Code: 66

Command Output (stderr):
--
RUN: at line 1: [...]/bin/clang  --driver-mode=g++ -gline-tables-only -fsanitize=thread  -funwind-tables --sysroot=/home/aaron/chrome-sysroot  -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/tsan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp &&  [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/tsan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
+ [...]/bin/clang --driver-mode=g++ -gline-tables-only -fsanitize=thread -funwind-tables --sysroot=/home/aaron/chrome-sysroot -I[...]/compiler-rt/test -ldl [...]/compiler-rt/test/sanitizer_common/TestCases/Linux/dn_expand.cpp -o [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/tsan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp
+ [...]/runtimes/runtimes-bins/compiler-rt/test/sanitizer_common/tsan-x86_64-Linux/Linux/Output/dn_expand.cpp.tmp [...]/compiler-rt/test/sanitizer_common/TestCases/Linux
ThreadSanitizer:DEADLYSIGNAL
==18043==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x000000000400 sp 0x7ffef632c3e8 T18043)
==18043==Hint: pc points to the zero page.
==18043==The signal is caused by a READ memory access.
==18043==Hint: address points to the zero page.
    #0 <null> <null> (0x000000000000)
    #1 __sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int) [...]/compiler-rt/lib/tsan/rtl/tsan_stack_trace.cpp:55:3 (dn_expand.cpp.tmp+0xe10d0)
    #2 ReportDeadlySignalImpl [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:275:3 (dn_expand.cpp.tmp+0x53af6)
    #3 __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:289:5 (dn_expand.cpp.tmp+0x53af6)
    #4 __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) [...]/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:298:3 (dn_expand.cpp.tmp+0x53e80)
    #5 <null> <null> (libc.so.6+0x5797f) (BuildId: 4f849c7c3d8ac76c5b3bafcb925d42a5e83bc222)

==18043==Register values:
rax = 0x0000563f3b6f553c  rbx = 0x00007ffef632c450  rcx = 0x00007ffef632c450  rdx = 0x00007ffef632c867
rdi = 0x00007ffef632c850  rsi = 0x00007ffef632c873  rbp = 0x0000000000000400  rsp = 0x00007ffef632c3e8
 r8 = 0x0000000000000400   r9 = 0x00000fffffffffff  r10 = 0x00007f134225f3d0  r11 = 0x0000000000001180
r12 = 0x00007ffef632c873  r13 = 0x00007ffef632c850  r14 = 0x00007f13422c6780  r15 = 0x00007ffef632c867
ThreadSanitizer can not provide additional info.
SUMMARY: ThreadSanitizer: SEGV (<unknown module>)
==18043==ABORTING
```
Of course that is with a system libc ≥ 2.34. Building and running the test against the sysroot, it succeeds as above. Could it be that you've ignored those test cases? Or am I seeing a different error than you?

**Comment by aaronpuchert** [comment]
With my change reverted, the test lives in `compiler-rt/test/sanitizer_common`, where we get an additional `--sysroot=` argument. This comes from `compiler-rt/test/sanitizer_common/lit.site.cfg.py.in`:
```python
# Tool-specific config options.
config.name_suffix = "@CONFIG_NAME@"
config.tool_name = "@SANITIZER_COMMON_LIT_TEST_MODE@"
config.target_cflags = "@SANITIZER_COMMON_TEST_TARGET_CFLAGS@"
config.target_arch = "@SANITIZER_COMMON_TEST_TARGET_ARCH@"
```
In this case configured to `compiler-rt/test/sanitizer_common/msan-x86_64-Linux/lit.site.cfg.py`:
```python
# Tool-specific config options.
config.name_suffix = "msan-x86_64-Linux"
config.tool_name = "msan"
config.target_cflags = "-funwind-tables --sysroot=/home/aaron/chrome-sysroot"
config.target_arch = "x86_64"
```
This comes from `compiler-rt/test/sanitizer_common/CMakeLists.txt`:
```cmake
      if(CMAKE_SYSROOT)
        list(APPEND SANITIZER_COMMON_TEST_TARGET_CFLAGS "--sysroot=${CMAKE_SYSROOT}")
      endif()
```
However, in `compiler-rt/test/msan/lit.site.cfg.py.in`:
```python
# Tool-specific config options.
config.name_suffix = "-@CONFIG_NAME@"
config.target_cflags = "@MSAN_TEST_TARGET_CFLAGS@"
config.target_arch = "@MSAN_TEST_TARGET_ARCH@"
config.use_lld = @MSAN_TEST_USE_LLD@
config.use_thinlto = @MSAN_TEST_USE_THINLTO@
```
Configured to e.g. `compiler-rt/test/msan/X86_64/lit.site.cfg.py`:
```python
# Tool-specific config options.
config.name_suffix = "-X86_64"
config.target_cflags = ""
config.target_arch = "x86_64"
config.use_lld = False
config.use_thinlto = False
```
This comes from `compiler-rt/test/msan/CMakeLists.txt`:
```cmake
get_test_cc_for_arch(${arch} MSAN_TEST_TARGET_CC MSAN_TEST_TARGET_CFLAGS)
```
which in turn goes to `compiler-rt/cmake/config-ix.cmake`:
```cmake
# Returns a compiler and CFLAGS that should be used to run tests for the
# specific architecture.  When cross-compiling, this is controled via
# COMPILER_RT_TEST_COMPILER and COMPILER_RT_TEST_COMPILER_CFLAGS.
macro(get_test_cc_for_arch arch cc_out cflags_out)
  if (NOT ${ARGC} EQUAL 3)
    message(FATAL_ERROR "got too many args. expected 3, got ${ARGC} (namely: ${ARGV})")
  endif()
  if(ANDROID OR (NOT APPLE AND ${arch} MATCHES "arm|aarch64|riscv32|riscv64"))
    # This is only true if we are cross-compiling.
    # Build all tests with host compiler and use host tools.
    set(${cc_out} ${COMPILER_RT_TEST_COMPILER})
    set(${cflags_out} ${COMPILER_RT_TEST_COMPILER_CFLAGS})
  else()
    get_target_flags_for_arch(${arch} ${cflags_out})
    if(APPLE)
      list(APPEND ${cflags_out} ${DARWIN_osx_CFLAGS})
    endif()
    string(REPLACE ";" " " ${cflags_out} "${${cflags_out}}")
  endif()
endmacro()
```
@vitalybuka, should we move the sysroot option into this macro? And always interpose both spellings?
