### PR TITLE
[lld][ELF] Fix wrap when __real_X is weak to avoid undefined symbol

### LINKED ISSUE #98294: [LLD][ELF] undefined reference to foo when using --wrap=foo when __real_foo is declared weak
foo.c
```c
extern __attribute__((weak)) int __real_foo();
int __wrap_foo() {
  if (__real_foo) return __real_foo();
  return 42;
}
int foo();

void _exit(int);
int _start() {
  _exit(foo());
}

```

It's okay to compile and run it with GNU ld or mold:

```sh
❯ clang -o foo foo.c -Wl,--wrap=foo -fuse-ld=ld -nostartfiles
❯ ./foo
❯ echo $?
42
❯ ld -v
GNU ld (GNU Binutils for Ubuntu) 2.38
```

But when I switch to lld, I got an error instead
```sh
❯ clang -o foo foo.c -Wl,--wrap=foo -fuse-ld=lld -nostartfiles
ld.lld: error: undefined symbol: foo
>>> referenced by foo.c
>>>               /tmp/foo-e30076.o:(__wrap_foo)
>>> referenced by foo.c
>>>               /tmp/foo-e30076.o:(__wrap_foo)
>>> did you mean: __wrap_foo
>>> defined in: /tmp/foo-e30076.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
❯ ld.lld -v
LLD 19.0.0 (https://github.com/llvm/llvm-project.git 4d052a76185875bf8d8343d723a444795b87c8c5) (compatible with GNU linkers)
```

I'm sure that I'm using the latest LLVM. I will try to submit a patch soon

### PR DESCRIPTION
**Pull request by xdqi**
Fix #98294.

When you specify --wrap=foo, sometimes foo is undefined in any context. If you declare __real_foo as weak, GNU ld will not attempt to find the strong symbol foo, instead, it generates a weak undefined symbol.

This pull request imitates this behavior by copying the binding attribute from __real_foo to foo.

### CODE REVIEW

File: lld/ELF/Driver.cpp [hunk 1]
```diff
@@ -2551,8 +2551,12 @@ static std::vector<WrappedSymbol> addWrappedSymbols(opt::InputArgList &args) {
     // If __real_ is referenced, pull in the symbol if it is lazy. Do this after
     // processing __wrap_ as that may have referenced __real_.
     StringRef realName = saver().save("__real_" + name);
-    if (symtab.find(realName))
+    if (Symbol *real = symtab.find(realName)) {
       symtab.addUnusedUndefined(name, sym->binding);
+      // update sym's binding to __real_'s binding, as sym will replacing
```
Comment (MaskRay) [inline lld/ELF/Driver.cpp:2556]: Capitalize the comment.

`// Update sym's binding, which will replace real's later in SYmbolTable::wrap.`

File: lld/test/ELF/wrap-weak.s [hunk 2]
```diff
@@ -0,0 +1,23 @@
+# REQUIRES: x86
+# RUN: llvm-mc -filetype=obj -triple=x86_64-pc-linux %s -o %t.o
+# RUN: ld.lld -shared -o %t.so %t.o -wrap foo
+
+# RUN: llvm-readelf --dyn-syms %t.so | FileCheck %s --check-prefix=CHECK
```
Comment (MaskRay) [inline lld/test/ELF/wrap-weak.s:5]: remove `--check-prefix=CHECK`

File: lld/test/ELF/wrap-weak.s [hunk 3]
```diff
@@ -0,0 +1,23 @@
+# REQUIRES: x86
+# RUN: llvm-mc -filetype=obj -triple=x86_64-pc-linux %s -o %t.o
```
Comment (MaskRay) [inline lld/test/ELF/wrap-weak.s:2]: `-triple=x86_64`

**Review by MaskRay — APPROVED** [review]

**Comment by MaskRay** [comment]
> title: #98294

Can you remove `#98294` from the subject and add `Fix #98294` to the body instead?
