### PR TITLE
[Clang] Fix parsing of reversible type traits in template arguments

### LINKED ISSUE #95598: __is_pointer used both as a trait and an identifier seems inconsistent
Take:
```

template<typename _Tp, bool _IsPtr = __is_pointer(_Tp)>
  struct __is_pointer {};

template<typename _Tp>
inline bool t = __is_pointer(_Tp); // is accepted

template<bool>
struct ts{};

template<typename _Tp>
  struct is_pointer : ts<__is_pointer(_Tp)> {}; // is rejected

int tt = t<int>;
```

I would have expected the variable template t would have been rejected the same way as the template argument for the base class is_pointer being rejected but it is inconsistent here.

This shows up now in libstdc++'s headers (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115497).

### PR DESCRIPTION
**Pull request by cor3ntin**
Constructs like `__is_pointer(Foo)` are never considered to be functions declarations.

This matches usages in libstdc++, and we can hope
no one else redefine these reserved identifiers.

Fixes #95598

### CODE REVIEW

File: clang/test/Parser/cxx-template-argument.cpp [hunk 1]
```diff
@@ -141,3 +141,15 @@ namespace r360308_regression {
     return a == b;
   }
 }
+
+namespace GH95598 {
+template<typename _Tp, bool _IsPtr = __is_pointer(_Tp)>
+struct __is_pointer {};
+// expected-warning@-1 {{keyword '__is_pointer' will be made available as an identifier for the remainder of the translation unit}}
```
Comment (AaronBallman) [inline clang/test/Parser/cxx-template-argument.cpp:148]: This diagnostic is very confusing because it implies the name is only available as an identifier when in reality it's available as *either* an identifier or a keyword. This seems to be the original functionality though: https://godbolt.org/z/WzTs4T31j (based on the changes in https://github.com/llvm/llvm-project/commit/47642d2b7ea175a6c0d80bf14354246ca20af342 which added this diagnostic).

So I think your changes are aligned with the original intent of the diagnostic, but I've CCed @zygoloid and @rnk just in case others from this era recall differently.

Comment (zygoloid) [reply clang/test/Parser/cxx-template-argument.cpp:148]: I think we've incrementally ended up in a bad place. Here's my memory of what happened:

Originally, the idea was: we provide builtins such as `__is_pointer` for use by the standard library. But for a bunch of those, libstdc++ provides a type with the same name that works it out for itself. OK, we can work around that: if we see a declaration with that name, then the standard library isn't using our builtin, so we treat it as a non-keyword so that libstdc++ doesn't break.

But then it turns out that boost uses these things as keywords directly, rather than using the standard library functionality. To keep both that and libstdc++ working at the same time, we treat the keyword followed by an open paren as having the builtin meaning even when the keyword has been reverted to being a non-keyword.

And now we're noticing that we also need special behavior in other parts of the parser to treat the keyword followed by an open paren as a special case.

I don't think we should be extending this hack further. I've suggested on the libstdc++ bug report that this be fixed in libstdc++ instead, by stopping using our keywords as their type names. Maybe one day we can then remove it entirely.

Comment (zygoloid) [reply clang/test/Parser/cxx-template-argument.cpp:148]: One thing we could consider doing would be removing the entire "revertible keyword" mechanism, and instead, in the lexer, classifying these tokens as keywords only if the next pp-token is an `lparen`. That would probably simplify the handling of these keywords everywhere, and would happen to give the outcome that libstdc++ is expecting in this case too. (It's a breaking change for some weird corner cases, such as producing the keyword via macro expansion and things like `bool __is_pointer(true);`, but hopefully those things don't happen in practice!)

Comment (MitalAshok) [reply clang/test/Parser/cxx-template-argument.cpp:148]: @zygoloid https://github.com/itanium-cxx-abi/cxx-abi/blob/07427ac5b6ff0799c47e8c754609cf8220c05cc0/gcc-tinfo2.cc#L373 :(

File: clang/lib/Parse/ParseTentative.cpp [hunk 2]
```diff
@@ -1385,6 +1385,12 @@ Parser::isCXXDeclarationSpecifier(ImplicitTypenameContext AllowImplicitTypename,
     if (!getLangOpts().ObjC && Next.is(tok::identifier))
       return TPResult::True;
 
+    if (Next.is(tok::l_paren) &&
+        Tok.getIdentifierInfo()->hasRevertedTokenIDToIdentifier() &&
+        isRevertibleTypeTrait(Tok.getIdentifierInfo())) {
```
Comment (MitalAshok) [inline clang/lib/Parse/ParseTentative.cpp:1390]: You can set the correct `tok::TokenKind` here too since it will be set later anyway when this is re-parsed as an expression

File: clang/lib/Parse/ParseTentative.cpp [hunk 3]
```diff
@@ -1385,6 +1385,12 @@ Parser::isCXXDeclarationSpecifier(ImplicitTypenameContext AllowImplicitTypename,
     if (!getLangOpts().ObjC && Next.is(tok::identifier))
       return TPResult::True;
 
+    if (Next.is(tok::l_paren) &&
```
Comment (MitalAshok) [inline clang/lib/Parse/ParseTentative.cpp:1388]: We might need a comment above this like:

```c++
// If this identifier was reverted from a token ID, and the next token
// is a '(', this is likely to be a use of a type trait. If it is, this
// can never be a type name.
```

File: clang/test/Parser/cxx-template-argument.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/test/Parser/cxx-template-argument.cpp:148]: @zygoloid I prototyped something https://github.com/llvm/llvm-project/pull/96097

One of the test has a default constructor declaration, ie `is_pod()`, which the lexer approach would struggle to cope with. Let me know what you think

The alternative is to keep status quo or go with the current PR and change the warning to a depreciation warning.
My concern is that until we support older libstdc++ (which will be the case for a long time), we won't be able to rip the hack out

Comment (zygoloid) [reply clang/test/Parser/cxx-template-argument.cpp:148]: There are now patches posted for libstdc++ to avoid using our type trait keywords as identifiers.

**Comment by Endilll** [comment]
Stumbled upon a related bug #29631

**Comment by cor3ntin** [comment]
I think we should go with this patch and independently make sure to fix the warning
the approach in https://github.com/llvm/llvm-project/pull/96097 does not seem workable and I don;t think it's worth spending too much effort on this

**Comment by AaronBallman** [comment]
> I think we should go with this patch and independently make sure to fix the warning the approach in #96097 does not seem workable and I don;t think it's worth spending too much effort on this
> 
> @AaronBallman

That sounds reasonable to me, thank you for the investigative work done in #96097!

File: clang/lib/Parse/ParseTentative.cpp (hunk 2 above)
Comment (cor3ntin) [reply clang/lib/Parse/ParseTentative.cpp:1390]: I would rather not mutate anything in this function

**Review by AaronBallman — APPROVED** [review]
Presuming precommit CI comes back without surprises, this LGTM!
