### PR TITLE
[X86][AVX] Fix handling of out-of-bounds shift amounts in AVX2 vector logical shift nodes #83840

### LINKED ISSUE #83840: [X86][AVX] Recognise out of bounds AVX2 shift amounts
Pulled out of #39822 which was a bit too general.

Unlike the general ISD SRA/SRL/SHL nodes, the AVX2 vector shift nodes X86ISD VSRAV/VSRLV/VSHLV handle out of bounds shift amounts:

- VSRAV clamps the unsigned shift amount to (BITWIDTH-1)
- VSRLV/VSHLV returns a zero value for unsigned shift amounts greater than (BITWIDTH-1).

So when lowering vector shifts, we should be able to fold any shift amount clamp patterns and use the X86ISD nodetypes.

e.g.

```ll
define <4 x i32> @ashr(<4 x i32> %sh, <4 x i32> %amt) {
  %elt.min.i = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %amt, <4 x i32> <i32 31, i32 31, i32 31, i32 31>)
  %shr = ashr <4 x i32> %sh, %elt.min.i
  ret <4 x i32> %shr
}
```
-> 
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpbroadcastd    xmm2, dword ptr [rip + .LCPI0_0] # xmm2 = [31,31,31,31]
        vpminud xmm1, xmm1, xmm2
        vpsravd xmm0, xmm0, xmm1
        ret
```
vs
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpsravd xmm0, xmm0, xmm1
        ret
```

Logical shifts are trickier but also foldable:
```ll
define <4 x i32> @lshr(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %shr = lshr <4 x i32> %sh, %amt
  %0 = select <4 x i1> %cmp.i, <4 x i32> %shr, <4 x i32> zeroinitializer
  ret <4 x i32> %0
}

define <4 x i32> @lshr2(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %0 = select <4 x i1> %cmp.i, <4 x i32> %sh, <4 x i32> zeroinitializer
  %shr = lshr <4 x i32> %0, %amt
  ret <4 x i32> %shr
}
```

### PR DESCRIPTION
**Pull request by SahilPatidar**
Resolve #83840

### CODE REVIEW

**Comment by SahilPatidar** [comment]
I finished some dirty work for `SRL`. Does it look alright?

**Comment by SahilPatidar** [comment]
@RKSimon

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -47443,6 +47456,22 @@ static SDValue combineShiftRightLogical(SDNode *N, SelectionDAG &DAG,
   if (SDValue V = combineShiftToPMULH(N, DAG, Subtarget))
     return V;
 
+  if (N0.getOpcode() == ISD::VSELECT &&
+      supportedVectorVarShift(VT, Subtarget, ISD::SRL)) {
```
[the remark this answers is not in the document]
Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47460]: Do we need to change the parameter to get a `Subtarget`?

[the remark this answers is not in the document]
Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47460]: No, just do similar to what I suggested in the other fold

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 2]
```diff
@@ -47384,6 +47408,24 @@ static SDValue combineShiftLeft(SDNode *N, SelectionDAG &DAG) {
   ConstantSDNode *N1C = dyn_cast<ConstantSDNode>(N1);
   EVT VT = N0.getValueType();
 
+  // Exploits AVX2 VSHLV/VSRLV instructions for efficient unsigned vector shifts
+  // with out-of-bounds clamping.
+  if (N0.getOpcode() == ISD::VSELECT &&
+      supportedVectorVarShift(VT, DAG.getSubtarget<X86Subtarget>(), ISD::SHL)) {
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47414]: Sorry I misunderstood you're question - just add the `const X86Subtarget &Subtarget` arg to combineShiftLeft to match combineShiftRightArithmetic

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47414]: done

**Comment by SahilPatidar** [comment]
@RKSimon, Implemented the changes you suggested, Please take another look!

**Comment by SahilPatidar** [comment]
@RKSimon

**Comment by SahilPatidar** [comment]
@RKSimon

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 3]
```diff
@@ -45612,6 +45612,30 @@ static SDValue combineSelect(SDNode *N, SelectionDAG &DAG,
...
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC &&
+        Cond.getOperand(0) == LHS.getOperand(1) &&
+        cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT &&
+        ISD::isConstantSplatVector(Cond.getOperand(1).getNode(), SV) &&
+        ISD::isConstantSplatVectorAllZeros(RHS.getNode()) &&
+        SV == VT.getScalarSizeInBits()) {
+      return DAG.getNode(
+          LHS.getOpcode() == ISD::SRL ? X86ISD::VSRLV : X86ISD::VSHLV, DL,
+          LHS->getVTList(), LHS.getOperand(0), LHS.getOperand(1));
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:45635]: LHS->getVTList() can be replaced with VT

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 4]
```diff
@@ -47378,12 +47402,31 @@ static SDValue combineShiftToPMULH(SDNode *N, SelectionDAG &DAG,
...
+    SDValue N00 = N0.getOperand(1);
+    SDValue N01 = N0.getOperand(2);
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC && Cond.getOperand(0) == N1 &&
+        cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT &&
+        ISD::isConstantSplatVector(Cond.getOperand(1).getNode(), SV) &&
+        ISD::isConstantSplatVectorAllZeros(N01.getNode()) &&
+        SV == VT.getScalarSizeInBits()) {
+      SDLoc DL(N);
+      return DAG.getNode(X86ISD::VSHLV, DL, N->getVTList(), N00, N1);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47426]: N->getVTList() -> VT

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 5]
```diff
@@ -47502,6 +47545,24 @@ static SDValue combineShiftRightLogical(SDNode *N, SelectionDAG &DAG,
...
+    SDValue N00 = N0.getOperand(1);
+    SDValue N01 = N0.getOperand(2);
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC && Cond.getOperand(0) == N1 &&
+        cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT &&
+        ISD::isConstantSplatVector(Cond.getOperand(1).getNode(), SV) &&
+        ISD::isConstantSplatVectorAllZeros(N01.getNode()) &&
+        SV == VT.getScalarSizeInBits()) {
+      SDLoc DL(N);
+      return DAG.getNode(X86ISD::VSRLV, DL, N->getVTList(), N00, N1);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47562]: N->getVTList() -> VT

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 6]
```diff
@@ -45612,6 +45612,30 @@ static SDValue combineSelect(SDNode *N, SelectionDAG &DAG,
     }
   }
 
+  // Exploits AVX2 VSHLV/VSRLV instructions for efficient unsigned vector shifts
+  // with out-of-bounds clamping.
+
+  // Unlike general shift instructions (SHL/SRL), AVX2's VSHLV/VSRLV handle
+  // shift amounts exceeding the element bitwidth. VSHLV clamps the amount to
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:45619]: Merge the near identical VSHLV+VSRLV sentences - "VSHLV/VSRLV clamps the amount to...."

**Comment by SahilPatidar** [comment]
@RKSimon

File: llvm/test/CodeGen/X86/combine-srl.ll [hunk 7]
```diff
@@ -606,3 +606,436 @@ define <4 x i32> @combine_vec_lshr_trunc_and(<4 x i32> %x, <4 x i64> %y) {
...
+; AVX2-NEXT:    vpsllvd %xmm1, %xmm0, %xmm0
+; AVX2-NEXT:    retq
+;
+; AVX512-LABEL: combine_vec_shl_commuted_clamped:
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vpsllvd %xmm1, %xmm0, %xmm0
+; AVX512-NEXT:    retq
+  %cmp.i = icmp uge <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
+  %1 = select <4 x i1> %cmp.i, <4 x i32> zeroinitializer, <4 x i32> %sh
+  %shr = shl <4 x i32> %1, %amt
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-srl.ll:988]: Shouldn't this be in side combine-shl.ll?

Comment (SahilPatidar) [reply llvm/test/CodeGen/X86/combine-srl.ll]: done.

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 8]
```diff
@@ -45950,6 +45950,30 @@ static SDValue combineSelect(SDNode *N, SelectionDAG &DAG,
...
+  if (N->getOpcode() == ISD::VSELECT &&
+      (LHS.getOpcode() == ISD::SRL || LHS.getOpcode() == ISD::SHL) &&
+      supportedVectorVarShift(VT, Subtarget, LHS.getOpcode())) {
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC &&
+        Cond.getOperand(0) == LHS.getOperand(1) &&
+        cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT &&
+        ISD::isConstantSplatVector(Cond.getOperand(1).getNode(), SV) &&
+        ISD::isConstantSplatVectorAllZeros(RHS.getNode()) &&
+        SV == VT.getScalarSizeInBits()) {
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:45970]: Can you not just match against ISD::UMAX ?

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:45970]: Tried compare with `ISD::UMIN`, but it seems to be breaking test checks.

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:45970]: @RKSimon

File: llvm/test/CodeGen/X86/combine-srl.ll [hunk 9]
```diff
@@ -606,3 +606,252 @@ define <4 x i32> @combine_vec_lshr_trunc_and(<4 x i32> %x, <4 x i64> %y) {
...
+; SSE41-NEXT:    pblendw {{.*#+}} xmm0 = xmm0[0,1],xmm5[2,3],xmm0[4,5],xmm5[6,7]
+; SSE41-NEXT:    retq
+;
+; AVX2-LABEL: combine_vec_lshr_commuted_clamped:
+; AVX2:       # %bb.0:
+; AVX2-NEXT:    vpbroadcastd {{.*#+}} xmm2 = [31,31,31,31]
+; AVX2-NEXT:    vpminud %xmm2, %xmm1, %xmm2
+; AVX2-NEXT:    vpcmpeqd %xmm2, %xmm1, %xmm2
+; AVX2-NEXT:    vpand %xmm0, %xmm2, %xmm0
+; AVX2-NEXT:    vpsrlvd %xmm1, %xmm0, %xmm0
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-srl.ll:780]: missed match?

File: llvm/test/CodeGen/X86/combine-srl.ll [hunk 10]
```diff
@@ -606,3 +606,252 @@ define <4 x i32> @combine_vec_lshr_trunc_and(<4 x i32> %x, <4 x i64> %y) {
...
+; SSE41-NEXT:    retq
+;
+; AVX2-LABEL: combine_vec_lshr_commuted_clamped1:
+; AVX2:       # %bb.0:
+; AVX2-NEXT:    vpbroadcastd {{.*#+}} xmm2 = [31,31,31,31]
+; AVX2-NEXT:    vpsrlvd %xmm1, %xmm0, %xmm0
+; AVX2-NEXT:    vpminud %xmm2, %xmm1, %xmm2
+; AVX2-NEXT:    vpcmpeqd %xmm2, %xmm1, %xmm1
+; AVX2-NEXT:    vpand %xmm0, %xmm1, %xmm0
+; AVX2-NEXT:    retq
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-srl.ll:847]: missed match?

File: llvm/test/CodeGen/X86/combine-srl.ll (hunk 9 above)
Comment (RKSimon) [reply llvm/test/CodeGen/X86/combine-srl.ll:780]: Why did it match for AVX512 not AVX2?

Comment (SahilPatidar) [reply llvm/test/CodeGen/X86/combine-srl.ll:780]: I tried. I think it was failing because `cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT` since the condition opcode was `ISD::SETUGE`. but
 ```llvmir
-; AVX2-LABEL: combine_vec_lshr_commuted_clamped:
-; AVX2:       # %bb.0:
-; AVX2-NEXT:    vpbroadcastd {{.*#+}} xmm2 = [31,31,31,31]
-; AVX2-NEXT:    vpminud %xmm2, %xmm1, %xmm2
-; AVX2-NEXT:    vpcmpeqd %xmm2, %xmm1, %xmm2
-; AVX2-NEXT:    vpand %xmm0, %xmm2, %xmm0
-; AVX2-NEXT:    vpsrlvd %xmm1, %xmm0, %xmm0
-; AVX2-NEXT:    retq
-;
-; AVX512-LABEL: combine_vec_lshr_commuted_clamped:
-; AVX512:       # %bb.0:
-; AVX512-NEXT:    vpsrlvd %xmm1, %xmm0, %xmm0
-; AVX512-NEXT:    retq
+; AVX-LABEL: combine_vec_lshr_commuted_clamped:
+; AVX:       # %bb.0:
+; AVX-NEXT:    vpxor %xmm0, %xmm0, %xmm0
+; AVX-NEXT:    vpsrlvd %xmm1, %xmm0, %xmm0
+; AVX-NEXT:    retq
```
I got this with these changes:
```cpp
    if (Cond.getOpcode() == ISD::SETCC && Cond.getOperand(0) == N1 &&
        ((cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETULT &&
          ISD::isConstantSplatVectorAllZeros(N01.getNode())) ||
         (cast<CondCodeSDNode>(Cond.getOperand(2))->get() == ISD::SETUGE &&
          ISD::isConstantSplatVectorAllZeros(N00.getNode()))) &&
        ISD::isConstantSplatVector(Cond.getOperand(1).getNode(), SV) &&
        // ISD::isConstantSplatVectorAllZeros(N01.getNode()) &&
        SV == VT.getScalarSizeInBits()) {

```

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 11]
```diff
@@ -45950,6 +45950,30 @@ static SDValue combineSelect(SDNode *N, SelectionDAG &DAG,
...
+  // Unlike general shift instructions (SHL/SRL), AVX2's VSHLV/VSRLV handle
+  // shift amounts exceeding the element bitwidth. VSHLV/VSRLV clamps the amount
+  // to bitwidth-1 for unsigned shifts, effectively performing a maximum left
+  // shift of bitwidth-1 positions. and returns zero for unsigned right shifts
+  // exceeding bitwidth-1.
+  if (N->getOpcode() == ISD::VSELECT &&
+      (LHS.getOpcode() == ISD::SRL || LHS.getOpcode() == ISD::SHL) &&
+      supportedVectorVarShift(VT, Subtarget, LHS.getOpcode())) {
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC &&
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:45965]: Add a description comment:
```
// fold select(icmp_ult(amt,BW),shl(x,amt),0) -> avx2 psllv(x,amt)
// fold select(icmp_ult(amt,BW),srl(x,amt),0) -> avx2 psrlv(x,amt)
```

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 12]
```diff
@@ -47701,12 +47725,31 @@ static SDValue combineShiftToPMULH(SDNode *N, SelectionDAG &DAG,
...
 
+  // Exploits AVX2 VSHLV/VSRLV instructions for efficient unsigned vector shifts
+  // with out-of-bounds clamping.
+  if (N0.getOpcode() == ISD::VSELECT &&
+      supportedVectorVarShift(VT, Subtarget, ISD::SHL)) {
+    SDValue Cond = N0.getOperand(0);
+    SDValue N00 = N0.getOperand(1);
+    SDValue N01 = N0.getOperand(2);
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC && Cond.getOperand(0) == N1 &&
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47743]: Add a description comment:
```
// fold shl(select(icmp_ult(amt,BW),x,0),amt) -> avx2 psllv(x,amt)
```

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 13]
```diff
@@ -47825,6 +47868,24 @@ static SDValue combineShiftRightLogical(SDNode *N, SelectionDAG &DAG,
...
 
+  // Exploits AVX2 VSHLV/VSRLV instructions for efficient unsigned vector shifts
+  // with out-of-bounds clamping.
+  if (N0.getOpcode() == ISD::VSELECT &&
+      supportedVectorVarShift(VT, Subtarget, ISD::SRL)) {
+    SDValue Cond = N0.getOperand(0);
+    SDValue N00 = N0.getOperand(1);
+    SDValue N01 = N0.getOperand(2);
+    APInt SV;
+    if (Cond.getOpcode() == ISD::SETCC && Cond.getOperand(0) == N1 &&
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47879]: Add a description comment:
```
// fold srl(select(icmp_ult(amt,BW),x,0),amt) -> avx2 psrlv(x,amt)
```

**Review by RKSimon — COMMENTED** [review]
Sorry - this fell off my radar. One last request and this is ready to go - we can iterate later.

**Comment by SahilPatidar** [comment]
Apologies for the delay. I'm currently working on my GSoC project, which is causing the delays.

**Review by RKSimon — APPROVED** [review]
LGTM
