### PR TITLE
[Clang] Fix evaluation context of lambdas appearing in discarded statements

### LINKED ISSUE #146063: Regression with lambda return type deduction
The following used to compile without diagnostic in Clang 20.1:
```
template<class T, class U>
struct is_same {
  static constexpr bool value = false;
};
 
template<class T>
struct is_same<T, T> {
  static constexpr bool value = true;
};

template <typename T, int N>
struct A {
      static_assert([]() constexpr { // error: value of type 'void' is not contextually convertible to 'bool'
        if constexpr (is_same<T, int>::value)
          return true;
        else
          return (10 != N);
      }());
};                                                                                                                                            
int f1() {
    if constexpr (false) {
        A<int, 256> a;
    }
    return 0;
} 
```
but now gives an error on trunk: https://godbolt.org/z/fd5WY4xhY

Note, if you remove the `if constexpr (false)` from `f1()`, then the code compiles. If you add `-> bool` to the lambda, the code also compiles.

The code compiles without diagnostics in GCC, MSVC, and EDG.

### PR DESCRIPTION
**Pull request by cor3ntin**
Fixes 2 bugs reported in #146063

 - The body of a lambda appearing in a discarded statement was sometimes considered discarded itself
 - A lambda conversion operator that was not odr-used was sometimes not defined even if it was needed

Fixes #146063

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -18252,6 +18252,11 @@ static bool isImplicitlyDefinableConstexprFunction(FunctionDecl *Func) {
 
   if (Func->isImplicitlyInstantiable() || !Func->isUserProvided())
     return true;
+
+  // Lambda conversion operators are never user provided
```
Comment (tbaederr) [inline clang/lib/Sema/SemaExpr.cpp]:
```suggestion
  // Lambda conversion operators are never user provided.
```

**Review by erichkeane — APPROVED** [review]
