### PR TITLE
[mlir] Add support for `memref.alloca` sub-byte emulation

### LINKED ISSUE #15515: Missing sub-byte emulation support for memref.alloca
@Max191 reports the issue this morning. The emulation is missing at this moment. It should be as same as what has been done for `memref.alloc`.

https://github.com/llvm/llvm-project/blob/9ef829097bbc4cf908698e3891af11a154e1d3e2/mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp#L59

Assigning it to @Max191 for now. If you are not working at it, please reassign it to @saienduri

### PR DESCRIPTION
**Pull request by Max191**
Adds a similar case to `memref.alloc` for `memref.alloca` in EmulateNarrowTypes.

Fixes https://github.com/openxla/iree/issues/15515

### CODE REVIEW

File: mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp [hunk 1]
```diff
@@ -53,18 +53,22 @@ static Value getOffsetForBitwidth(Location loc, OpFoldResult srcIdx,
...
 
 //===----------------------------------------------------------------------===//
-// ConvertMemRefAlloc
+// ConvertMemRefAllocation
 //===----------------------------------------------------------------------===//
 
-struct ConvertMemRefAlloc final : OpConversionPattern<memref::AllocOp> {
-  using OpConversionPattern::OpConversionPattern;
+template <typename OpTy>
+struct ConvertMemRefAllocation final : OpConversionPattern<OpTy> {
```
Comment (MaheshRavishankar) [inline mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp:60]: Do you think we can do this using an `AllocLikeOpInterface` ? Its fine to do as a follow up as well (or leave a TODO saying this could be generalized using the interface).

**Review by MaheshRavishankar — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]
Please help fix the conflicts.
