### PR TITLE
[HLSL] Make it possible to assign an array from a cbuffer

### LINKED ISSUE #133767: [HLSL] Assigning array from cbuffer fails
Now that cbuffer values are declared in a unique address space we're seeing a failure assigning an array from a cbuffer:

```hlsl
cbuffer CBArrays : register(b0) {
  float c1[2];
  int4 c2[2][2];
  bool c3[2];
}

struct Arrays {
  float c1[2];
  int4 c2[2][2];
  bool c3[2];
};

RWStructuredBuffer<Arrays> Out : register(u0);

[numthreads(1,1,1)]
void main() {
  Out[0].c1 = c1;
  Out[0].c2 = c2;
  Out[0].c3 = c3;
}
```

[Compiler Explorer](https://hlsl.godbolt.org/z/ne6avb8vd)

### PR DESCRIPTION
**Pull request by spall**
Update Sema Checking to always do an HLSL Array RValue cast in the case we are dealing with hlsl constant array types
Instead of comparing canonical types, compare canonical unqualified types
Add a test to show it is possible to assign an array from a cbuffer.
Closes #133767

### CODE REVIEW

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -2268,17 +2268,15 @@ static bool IsStandardConversion(Sema &S, Expr* From, QualType ToType,
     // handling here.
     if (ToType->isArrayParameterType()) {
       FromType = S.Context.getArrayParameterType(FromType);
-      SCS.First = ICK_HLSL_Array_RValue;
     } else if (FromType->isArrayParameterType()) {
       const ArrayParameterType *APT = cast<ArrayParameterType>(FromType);
```
Comment (inbelic) [inline clang/lib/Sema/SemaOverload.cpp:2272]: nit:
```suggestion
    } else if (const ArrayParameterType *APT = dyn_cast<ArrayParameterType>(FromType)) {
```
I think this is equivalent? The function seems to just be a wrapper to the `isa<..>` equivalent

File: clang/lib/Sema/SemaOverload.cpp [hunk 2]
```diff
@@ -2268,17 +2268,15 @@ static bool IsStandardConversion(Sema &S, Expr* From, QualType ToType,
...
       FromType = APT->getConstantArrayType(S.Context);
-      SCS.First = ICK_HLSL_Array_RValue;
-    } else {
-      SCS.First = ICK_Identity;
     }
 
-    if (S.Context.getCanonicalType(FromType) !=
-        S.Context.getCanonicalType(ToType))
+    SCS.First = ICK_HLSL_Array_RValue;
+
```
Comment (inbelic) [inline clang/lib/Sema/SemaOverload.cpp:2277]:
```suggestion

    // Compare unqualified types because irrelevant qualifiers can cause assignment
    // to fail. Eg: when casting from a cbuffer value, it will have a unique address space
    // that shouldn't matter for casting
```

Or something or other, just to make the why we are dropped the qualifiers more visible. From https://github.com/llvm/llvm-project/issues/133767#issuecomment-2773224779

**Review by inbelic — APPROVED** [review]
LGTM, just two small things

**Review by farzonl — APPROVED** [review]

**Review by bogner — APPROVED** [review]
The fact that we get memcpy here points out some of the issues we have with representing cbuffers - it would really be nicer if this ended up generating elementwise copies instead. However, I think fixing that is out of the scope of this change (it'll also come up for structs, etc) and will be rather complicated, so this looks reasonable to me.

File: clang/lib/Sema/SemaOverload.cpp (hunk 1 above)
Comment (spall) [reply clang/lib/Sema/SemaOverload.cpp:2272]: This looks like its just an NFC change to code I didn't touch, so I think I'll leave it as is.

**Comment by jplehr** [comment]
Hi, this turned a few bots red.
Can this be fixed forward or should we revert in the meantime?
Let me know if you need help with the bot setup / build config. Thanks!

**Comment by spall** [comment]
> Hi, this turned a few bots red. Can this be fixed forward or should we revert in the meantime? Let me know if you need help with the bot setup / build config. Thanks!

It can be reverted
