### PR TITLE
[libc++][math] Fix undue overflowing of `std::hypot(x,y,z)`

### LINKED ISSUE #92782: Incorrect overflow in std::hypot
Consider:

```
#include <cmath>
float f = std::hypot(1e20f,1e20f,1e20f);
```

With libc++, this produces +inf.  Other libraries appear to handle this correctly. (The C standard suggests hypot() should return a result "without undue overflow or underflow"... although that only applies to the two-argument form).

### PR DESCRIPTION
**Pull request by PaulXiCao**
Closes #92782.

The 3-dimentionsional `std::hypot(x,y,z)` was sub-optimally implemented. This lead to possible over-/underflows in (intermediate) results which can be circumvented by this proposed change.

The idea is to to scale the arguments (see linked issue for full discussion).

Tests have been added for problematic over- and underflows.

### CODE REVIEW

File: libcxx/include/__math/hypot.h [hunk 1]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+      static_assert(+16'384 == std::numeric_limits<_Real>::max_exponent);
+      __underflow = __hypot_factors<_Real>{0x1.0p-8'190l, 0x1.0p9'000l, 0x1.0p-9'000l};
+      __overflow  = __hypot_factors<_Real>{0x1.0p8'190l, 0x1.0p-9'000l, 0x1.0p+9'000l};
+    }
+  }
+  return {__underflow, __overflow};
+}
+
+template <class _Real>
+_Real __hypot(_Real __x, _Real __y, _Real __z) {
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:88]:
```suggestion
_LIBCPP_HIDE_FROM_ABI _Real __hypot(_Real __x, _Real __y, _Real __z) {
```

File: libcxx/include/__math/hypot.h [hunk 2]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+    __x *= __underflow.__scale_xyz;
+    __y *= __underflow.__scale_xyz;
+    __z *= __underflow.__scale_xyz;
+    __M = __underflow.__scale_M;
+  } else
+    __M = 1;
+  return __M * __math::sqrt(__x * __x + __y * __y + __z * __z);
+}
+
+inline _LIBCPP_HIDE_FROM_ABI float hypot(float __x, float __y, float __z) { return __hypot(__x, __y, __z); }
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:106]:
```suggestion
inline _LIBCPP_HIDE_FROM_ABI float hypot(float __x, float __y, float __z) { return __math::__hypot(__x, __y, __z); }
```

File: libcxx/include/__math/hypot.h [hunk 3]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+
+inline _LIBCPP_HIDE_FROM_ABI double hypot(double __x, double __y, double __z) { return __hypot(__x, __y, __z); }
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:108]:
```suggestion
inline _LIBCPP_HIDE_FROM_ABI double hypot(double __x, double __y, double __z) { return __math::__hypot(__x, __y, __z); }
```

File: libcxx/include/__math/hypot.h [hunk 4]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+
+inline _LIBCPP_HIDE_FROM_ABI long double hypot(long double __x, long double __y, long double __z) {
+  return __hypot(__x, __y, __z);
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:111]:
```suggestion
  return __math::__hypot(__x, __y, __z);
```

File: libcxx/include/__math/hypot.h [hunk 5]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+template <class _Real>
+struct __hypot_factors {
+  _Real __threshold;
+  _Real __scale_xyz;
+  _Real __scale_M;
+};
+
+// returns [underflow_factors, overflow_factors]
+template <class _Real>
+std::array<__hypot_factors<_Real>, 2> __create_factors() {
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:59]:
```suggestion
_LIBCPP_HIDE_FROM_ABI array<__hypot_factors<_Real>, 2> __create_factors() {
```

File: libcxx/include/__math/hypot.h [hunk 6]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
 
+#if _LIBCPP_STD_VER >= 17
+template <class _Real>
+struct __hypot_factors {
+  _Real __threshold;
+  _Real __scale_xyz;
+  _Real __scale_M;
+};
+
+// returns [underflow_factors, overflow_factors]
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:57]: Can you please add a comment explaining what this is?

File: libcxx/include/__math/hypot.h [hunk 7]
```diff
@@ -41,6 +46,83 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+      static_assert(-16'381 == std::numeric_limits<_Real>::min_exponent);
+      static_assert(+16'384 == std::numeric_limits<_Real>::max_exponent);
+      __underflow = __hypot_factors<_Real>{0x1.0p-8'190l, 0x1.0p9'000l, 0x1.0p-9'000l};
+      __overflow  = __hypot_factors<_Real>{0x1.0p8'190l, 0x1.0p-9'000l, 0x1.0p+9'000l};
+    }
+  }
+  return {__underflow, __overflow};
+}
+
+template <class _Real>
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:87]: I think a comment that explains what the implementation strategy is and why we do this instead of the naive definition would be really useful.

File: libcxx/test/std/numerics/c.math/cmath.pass.cpp [hunk 8]
```diff
@@ -1136,24 +1177,30 @@ void test_hypot()
...
-    static_assert((std::is_same<decltype(std::hypot((float)0, (int)0, (unsigned long long)0)), double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((float)0, (double)0, (double)0)), double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((float)0, (long double)0, (long double)0)), long double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((float)0, (float)0, (double)0)), double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((float)0, (float)0, (long double)0)), long double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((float)0, (double)0, (long double)0)), long double>::value), "");
-    static_assert((std::is_same<decltype(std::hypot((int)0, (int)0, (int)0)), double>::value), "");
-    static_assert((std::is_same<decltype(hypot(Ambiguous(), Ambiguous(), Ambiguous())), Ambiguous>::value), "");
+    // clang-format off
+    static_assert((std::is_same_v<decltype(std::hypot((float)0, (float)0,          (float)0)),              float>));
```
Comment (ldionne) [inline libcxx/test/std/numerics/c.math/cmath.pass.cpp:1181]:
```suggestion
    static_assert(std::is_same_v<decltype(std::hypot((float)0, (float)0,          (float)0)),              float>);
```

While we're at it, you don't need double parens. Also applies to the surrounding lines.

File: libcxx/test/std/numerics/c.math/cmath.pass.cpp [hunk 9]
```diff
@@ -1113,6 +1116,44 @@ void test_fmin()
     assert(std::fmin(1,0) == 0);
 }
 
+struct TestHypot3 {
+    template <class Real>
+    static void operator()() {
```
Comment (ldionne) [inline libcxx/test/std/numerics/c.math/cmath.pass.cpp:1121]:
```suggestion
    void operator()() const {
```

More friendly to older Standards!

**Review by ldionne — CHANGES_REQUESTED** [review]
Thanks for the fix! I have some comments. TBH, I have not really looked deeply into the implementation changes, I'm waiting for you to address some of my comments about explaining what's going on. But I'm sure I'll be OK with the changes once I understand them :).

File: libcxx/include/__math/hypot.h (hunk 7 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h:87]: I agree with you that a comment is useful for this non-obvious implementation. I will add an explaining comment to the code as well.

For reference: The idea behind this change was discussed in the original issue #92782 (linked in mr title). I left a [summarizing comment](https://github.com/llvm/llvm-project/issues/92782#issuecomment-2125800131) therein.

File: libcxx/include/__math/hypot.h (hunk 5 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h:59]: This might be a newbie question, but what is the purpose of removing `std::` for `std::array`?

File: libcxx/test/std/numerics/c.math/cmath.pass.cpp (hunk 8 above)
Comment (PaulXiCao) [reply libcxx/test/std/numerics/c.math/cmath.pass.cpp:1181]: I saw that as well, but it is like this all throughout this rather large file. I tried to stay consistent to it...

What do you think if I create another mr which changes only this style issue all throughout the file later on? (And keeping it as is for this mr?)

File: libcxx/include/__math/hypot.h (hunk 5 above)
Comment (ldionne) [reply libcxx/include/__math/hypot.h:59]: It's just as valid, it's only a matter of consistency. We generally don't qualify types when we don't need to throughout the library (not with 100% consistency though).

File: libcxx/include/__math/hypot.h (hunk 2 above)
Comment (ldionne) [reply libcxx/include/__math/hypot.h:106]: Those qualifications are to prevent ADL from kicking in, and also for consistency (since ADL doesn't really do anything in this case).

Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in ad123177c71e3992d238a33f8935a9e29a0f7222.

File: libcxx/include/__math/hypot.h (hunk 3 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in ad123177c71e3992d238a33f8935a9e29a0f7222.

File: libcxx/include/__math/hypot.h (hunk 4 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in ad123177c71e3992d238a33f8935a9e29a0f7222.

File: libcxx/include/__math/hypot.h (hunk 5 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in ada9edbb84e415b443fb23bc792effcba873762f, aeb72521a887bb2eed14ec4f8e907314a936aaef.

File: libcxx/include/__math/hypot.h (hunk 6 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Done in d5d3ec524baaa2d07216f3b218352255cff4e07b.

File: libcxx/include/__math/hypot.h (hunk 7 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h:93]: Done in d5d3ec524baaa2d07216f3b218352255cff4e07b.

File: libcxx/test/std/numerics/c.math/cmath.pass.cpp (hunk 9 above)
Comment (PaulXiCao) [reply libcxx/test/std/numerics/c.math/cmath.pass.cpp]: Fixed in a80b11e49e67a816c6c7cb116ea155ad9957764b.

File: libcxx/test/std/numerics/c.math/cmath.pass.cpp (hunk 8 above)
Comment (ldionne) [reply libcxx/test/std/numerics/c.math/cmath.pass.cpp:1181]: That sounds totally reasonable!

File: libcxx/include/__math/hypot.h (hunk 1 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in ada9edbb84e415b443fb23bc792effcba873762f.

File: libcxx/include/__math/hypot.h [hunk 10]
```diff
@@ -9,11 +9,16 @@
...
 
+#include <__algorithm/max.h>
 #include <__config>
+#include <__math/abs.h>
+#include <__math/roots.h>
 #include <__type_traits/enable_if.h>
 #include <__type_traits/is_arithmetic.h>
 #include <__type_traits/is_same.h>
 #include <__type_traits/promote.h>
+#include <array>
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:20]: Sorry for not spotting this earlier, but I would like to avoid including `<array>` here. This is a low-level math function and we should avoid pulling in `<array>`, which then pulls in a ton of additional stuff (like some algorithms we totally don't need here).

It's kinda hacky, but we could just define our own `__hypot_factors_pair` type as a struct with two members instead.

@philnik777 WDYT about introducing something like this to break dependencies for internal uses only (not as part of this patch though)?

```c++
template <class _Tp, class _Up>
struct __basic_pair {
  [[no_unique_address]] _Tp __first;
  [[no_unique_address]] _Up __second;
};
```

File: libcxx/include/__math/hypot.h [hunk 11]
```diff
@@ -41,6 +46,89 @@ inline _LIBCPP_HIDE_FROM_ABI typename __promote<_A1, _A2>::type hypot(_A1 __x, _
...
+struct __hypot_factors {
+  _Real __threshold;
+  _Real __scale_xyz;
+  _Real __scale_M;
+};
+
+// Computes `__hypot_factors` needed to determine if over-/underflow might happen for `std::hypot(x,y,z)`.
+// Returns: [underflow_factors, overflow_factors]
+template <class _Real>
+_LIBCPP_HIDE_FROM_ABI array<__math::__hypot_factors<_Real>, 2> __create_factors() {
```
Comment (ldionne) [inline libcxx/include/__math/hypot.h:61]: This could also be moved to a static member function like

```c++
template <class _Real>
 struct __hypot_factors {
   _Real __threshold;
   _Real __scale_xyz;
   _Real __scale_M;

  _LIBCPP_HIDE_FROM_ABI static array<__hypot_factors<_Real>, 2> __create() { ... }
 };
```

That way there's no ambiguity if we ever introduce another function called `__math::__create_factors`, which I could imagine since this is a pretty generic name. Non-blocking, this is just a suggestion.

**Review by ldionne — COMMENTED** [review]
Basically LGTM with still a bit of feedback.

File: libcxx/include/__math/hypot.h (hunk 10 above)
Comment (philnik777) [reply libcxx/include/__math/hypot.h:20]: `__utility/pair.h` is quite lean by now I think. It's mostly depending on type traits and (since C++20) concepts. `std::pair` is also used in quite a few public interfaces, so I'm not sure we'd gain much from introducing another `pair`.

Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: Fixed in cf378ed2d4dd28d8bb5e50ba66c61e30e2195994. I replaced `std::array` usage by `std::pair`.

File: libcxx/include/__math/hypot.h (hunk 11 above)
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h]: To get rid of the `std::array` usage I refactored the implementation of `__hypot`. Now there is no more `hypot_factors` struct nor this `create()` function. Only one function returning the `overflow_threshold` and its respective `overflow_scaling` factor.

File: libcxx/include/__math/hypot.h [hunk 12]
```diff
@@ -9,11 +9,16 @@
...
+#include <__math/roots.h>
 #include <__type_traits/enable_if.h>
 #include <__type_traits/is_arithmetic.h>
 #include <__type_traits/is_same.h>
 #include <__type_traits/promote.h>
+#include <__utility/pair.h>
+#include <limits>
 
 #if !defined(_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER)
 #  pragma GCC system_header
```
[the remark this answers is not in the document]
Comment (PaulXiCao) [reply libcxx/include/__math/hypot.h:24]: @ldionne Fixed the CI and rebased.

**Comment by ldionne** [comment]
@PaulXiCao This seems to be failing with many error messages that seem legitimate: 

```
__math/hypot.h:74:15: error: magnitude of floating-point constant too large for type 'long double'; maximum is 1.7976931348623157E+308 [-Werror,-Wliteral-range]
      return {0x1.0p+8'190l, 0x1.0p-9'000l};
              ^
```

**Comment by PaulXiCao** [comment]
> @PaulXiCao This seems to be failing with many error messages that seem legitimate:
> 
> ```
> __math/hypot.h:74:15: error: magnitude of floating-point constant too large for type 'long double'; maximum is 1.7976931348623157E+308 [-Werror,-Wliteral-range]
>       return {0x1.0p+8'190l, 0x1.0p-9'000l};
>               ^
> ```

@ldionne I am looking at this at the moment as well but do not understand yet why this happens. I have even included `static_assert`s.
```cpp
// file: hypot.h: ll.67..76
...
else { // long double
    static_assert(std::is_same_v<_Real, long double>);
    if constexpr (sizeof(_Real) == sizeof(double))
      return static_cast<std::pair<_Real, _Real>>(__math::__hypot_factors<double>());
    else {
      static_assert(-16'381 == std::numeric_limits<_Real>::min_exponent);
      static_assert(+16'384 == std::numeric_limits<_Real>::max_exponent);
      return {0x1.0p+8'190l, 0x1.0p-9'000l}; // <-- THIS LINE THROWS THE ERROR
    }
  }
```

**Comment by PaulXiCao** [comment]
> @PaulXiCao This seems to be failing with many error messages that seem legitimate:
> 
> ```
> __math/hypot.h:74:15: error: magnitude of floating-point constant too large for type 'long double'; maximum is 1.7976931348623157E+308 [-Werror,-Wliteral-range]
>       return {0x1.0p+8'190l, 0x1.0p-9'000l};
>               ^
> ```

@ldionne Should be fixed now.

**Review by ldionne — APPROVED** [review]

**Comment by kamaub** [comment]
It looks like this commit breaks the following buildbots: [sanitizer-ppc64le-linux](https://lab.llvm.org/buildbot/#/builders/72) build no. [1522](https://lab.llvm.org/buildbot/#/builders/72/builds/1522) and [sanitizer-ppc64be-linux](https://lab.llvm.org/buildbot/#/builders/109) build no. [1249](https://lab.llvm.org/buildbot/#/builders/109/builds/1249). I will attempt to isolate and provide more information about the failure but could you take a look and provide a fix as soon as possible or revert if the fix will take too long.

**Comment by hctim** [comment]
And, for your reference, this only breaks when building libcxx on PowerPC (as far as we're aware). The sanitizer buildbots are okay on other architectures (x86, arm64):

```
[1683/1855] Building CXX object libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o
FAILED: libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o 
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/./bin/clang++ --target=powerpc64le-unknown-linux-gnu -DLIBCXX_BUILDING_LIBCXXABI -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_LINK_PTHREAD_LIB -D_LIBCPP_LINK_RT_LIB -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/libcxx/src -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/powerpc64le-unknown-linux-gnu/c++/v1 -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1 -I/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/libcxxabi/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=c++23 -UNDEBUG -faligned-allocation -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -fsized-deallocation -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o -c /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/libcxx/src/valarray.cpp
In file included from /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/libcxx/src/valarray.cpp:9:
In file included from /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/valarray:363:
In file included from /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/cmath:316:
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/__math/hypot.h:60:17: error: static assertion failed due to requirement 'std::numeric_limits<long double>::is_iec559'
   60 |   static_assert(std::numeric_limits<_Real>::is_iec559);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/__math/hypot.h:94:65: note: in instantiation of function template specialization 'std::__math::__hypot_factors<long double>' requested here
   94 |   const auto [__overflow_threshold, __overflow_scale] = __math::__hypot_factors<_Real>();
      |                                                                 ^
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/__math/hypot.h:116:18: note: in instantiation of function template specialization 'std::__math::__hypot<long double>' requested here
  116 |   return __math::__hypot(__x, __y, __z);
      |                  ^
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/__math/hypot.h:76:19: error: static assertion failed due to requirement 'sizeof(long double) == sizeof(double)'
   76 |     static_assert(sizeof(_Real) == sizeof(double));
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_default/include/c++/v1/__math/hypot.h:76:33: note: expression evaluates to '16 == 8'
   76 |     static_assert(sizeof(_Real) == sizeof(double));
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by PaulXiCao** [comment]
I will probably not have time to work on this before the weekend. The fix is probably another special case guarded by preprocessor `#ifdef`.
