### PR TITLE
[IRCE] Skip icmp ptr in `InductiveRangeCheck::parseRangeCheckICmp`

### LINKED ISSUE #89959: Assertion in Scalar Evolution when running IRCE
The following IR crashes with 
```llvm
define void @foo() {
top:
  br label %L3

L3:                                               ; preds = %L13, %top
  %value_phi = phi ptr [ null, %top ], [ %0, %L13 ]
  %0 = getelementptr i8, ptr %value_phi, i64 8
  %.not = icmp ule ptr %value_phi, null
  br i1 %.not, label %L13, label %L15

L13:                                              ; preds = %L3
  br label %L3

L15:                                              ; preds = %L3
  ret void
}
```

`opt --passes=irce` 

https://godbolt.org/z/1sbvaT7r1

### PR DESCRIPTION
**Pull request by dtcxzyw**
Fixes https://github.com/llvm/llvm-project/issues/89959.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp [hunk 1]
```diff
@@ -279,6 +279,10 @@ bool InductiveRangeCheck::parseRangeCheckICmp(Loop *L, ICmpInst *ICI,
   Value *LHS = ICI->getOperand(0);
   Value *RHS = ICI->getOperand(1);
 
+  // ICmp with pointers are unsupported.
+  if (LHS->getType()->isPtrOrPtrVectorTy())
```
Comment (danilaml) [inline llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp:283]: I think the actual current restriction is more like,
```cpp
if (!LHS->getType()->isIntegerTy())
  return false;
```
but this also works.

File: llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp [hunk 2]
```diff
@@ -279,6 +279,9 @@ bool InductiveRangeCheck::parseRangeCheckICmp(Loop *L, ICmpInst *ICI,
   Value *LHS = ICI->getOperand(0);
   Value *RHS = ICI->getOperand(1);
 
+  if (!LHS->getType()->isIntegerTy())
```
Comment (fhahn) [inline llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp:282]: Better to use `SE->isSCEVable(LHS->getType())` as it makes the intention more explicit?

Comment (dtcxzyw) [reply llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp:282]: Pointer type is SCEVable, but `willNotOverflow` only supports binops with integers.

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp (hunk 2 above)
Comment (fhahn) [reply llvm/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp:282]: Ah my bad, thanks for clarifying
