### PR TITLE
[Flang][OpenMP] Fix copyin allocatable lowering to MLIR

### LINKED ISSUE #113191: [flang][OpenMP] runtime segfault when an allocatable variable is used with copyin
```
program foo
  real, allocatable :: ra
  !$omp threadprivate(ra)
  allocate(ra)
  ra = 10
  !$omp parallel num_threads(2) copyin(ra)
  print *,ra
  !$omp end parallel
end program
```

Compiling with `flang -fopenmp` version `8e6abf52e7` gives a segfault in the compiled aplication after the print.

CC @DavidTruby

### PR DESCRIPTION
**Pull request by kaviya2510**
Fixes https://github.com/llvm/llvm-project/issues/113191

Issue: [flang][OpenMP] Runtime segfault when an allocatable variable is used with copyin

Rootcause: The value of the threadprivate variable is not being copied from the primary thread to the other threads within a parallel region. As a result it tries to access a null pointer inside a parallel region which causes segfault.

Fix: When allocatables used with copyin clause need to ensure that, on entry to any parallel region each thread’s copy of a variable  will acquire the allocation status of the primary thread, before copying the value of a threadprivate variable of the primary thread to the threadprivate variable of each other member of the team.

### CODE REVIEW

**Review by jeanPerier — COMMENTED** [review]
The patch makes sense for that direction (original item allocated, thread copy unallocated), but I think the logic is probably broken in the other direction too (original item unallocated, copy allocated).

The requirement for copyin in OpenMP spec says that _"If the original list item does not
have the POINTER attribute but has the allocation status of unallocated, each copy will have the same status."_

So the copy should be unallocated in the else case if it allocated.

Example:
```
subroutine allocatable4()
  use omp_lib, only: omp_get_thread_num
  integer, allocatable, save :: a
  !$omp threadprivate(a)
  !$omp parallel
    allocate(a)
  !$omp end parallel

  deallocate(a)

  !$omp parallel copyin(a)
    print *, omp_get_thread_num(), allocated(a)
  !$omp end parallel
end subroutine

  call allocatable4()
end
```

This should print (in any order):
```
           0 F
           3 F
           1 F
           2 F
```

But I think it will print `T` with flang outside of the main thread after this patch (and would crash before the patch).

File: flang/lib/Lower/Bridge.cpp [hunk 1]
```diff
@@ -1298,10 +1298,15 @@ class FirConverter : public Fortran::lower::AbstractConverter {
     } else if (isAllocatable &&
                (flags.test(Fortran::semantics::Symbol::Flag::OmpFirstPrivate) ||
                 flags.test(Fortran::semantics::Symbol::Flag::OmpCopyIn))) {
-      // For firstprivate and copyin allocatable variables, RHS must be copied
+      // For firstprivate allocatable variables, RHS must be copied
```
[the remark this answers is not in the document]
Comment (kaviya2510) [reply flang/lib/Lower/Bridge.cpp]: I have added a separate check for copyin clause. So I think this change isn't necessary.

File: flang/lib/Lower/Bridge.cpp [hunk 2]
```diff
@@ -1290,9 +1290,31 @@ class FirConverter : public Fortran::lower::AbstractConverter {
...
+                  // unallocated, unallocate the copy if it is allocated, else
+                  // do nothing.
+                  Fortran::lower::genDeallocateIfAllocated(*this, new_box, loc);
+                },
+                [&](const auto &) -> void {});
+          })
+          .end();
+    } else if (isAllocatable &&
+               (flags.test(
+                   Fortran::semantics::Symbol::Flag::OmpFirstPrivate))) {
```
Comment (luporl) [inline flang/lib/Lower/Bridge.cpp:1316]: nit: parentheses can be removed here.

File: flang/test/Lower/OpenMP/copyin.f90 [hunk 3]
```diff
@@ -391,12 +391,34 @@ subroutine pointer()
 ! CHECK:             %[[VAL_4:.*]] = omp.threadprivate %[[VAL_1]]#1 : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>> -> !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
 ! CHECK:             %[[VAL_5:.*]]:2 = hlfir.declare %[[VAL_4]] {fortran_attrs = #fir.var_attrs<allocatable>, uniq_name = "_QFallocatableEp"} : (!fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) -> (!fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>)
 ! CHECK:             %[[VAL_6:.*]] = fir.load %[[VAL_3]]#0 : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
-! CHECK:             hlfir.assign %[[VAL_6]] to %[[VAL_5]]#0 realloc : !fir.box<!fir.heap<!fir.array<?xi32>>>, !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
+! CHECK:             %[[VAL_7:.*]] = fir.box_addr %[[VAL_6]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
+! CHECK:             %[[VAL_8:.*]] = fir.convert %[[VAL_7]] : (!fir.heap<!fir.array<?xi32>>) -> i64
+! CHECK:             %[[C0_I64:.*]] = arith.constant 0 : i64
+! CHECK:             %[[VAL_9:.*]] = arith.cmpi ne, %[[VAL_8]], %[[C0:.*]]_i64 : i64
+! CHECK:             fir.if %9 {
```
Comment (luporl) [inline flang/test/Lower/OpenMP/copyin.f90:398]: `fir.if %[[VAL_9]]` ?

Comment (kaviya2510) [reply flang/test/Lower/OpenMP/copyin.f90:398]: Thanks for the comments @luporl . 
Sorry I missed to change %9 to @[[VAL_9]] and yeah it should be `fir.if %[[VAL_9]]`

File: flang/lib/Lower/Bridge.cpp (hunk 2 above)
Comment (kaviya2510) [reply flang/lib/Lower/Bridge.cpp]: Done.

**Review by tblah — APPROVED** [review]
LGTM, thanks!

**Review by jeanPerier — APPROVED** [review]
Thanks for addressing my comments, LGTM

**Review by luporl — APPROVED** [review]
LGTM, thanks.

**Comment by kaviya2510** [comment]
Thanks for the review @tblah @jeanPerier @luporl .
