### PR TITLE
[clang-format] Fix a bug in formating `#define A x:`

### LINKED ISSUE #70789: [clang-format] Breaks line in macro definitions with a colon at the end
The formatter will break the line if a colon is present at the end of the line:
```
#define A x:
```

becomes
```
#define A \
  x:
```

### PR DESCRIPTION
**Pull request by owenca**
Fixed #70789.

### CODE REVIEW

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 1]
```diff
@@ -1171,6 +1171,13 @@ void UnwrappedLineParser::parsePPDefine() {
   assert((int)Line->PPLevel >= 0);
   Line->InMacroBody = true;
 
+  if (FormatTok->is(tok::identifier) &&
+      Tokens->peekNextToken()->is(tok::colon)) {
+    nextToken();
+    nextToken();
+    addUnwrappedLine();
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/UnwrappedLineParser.cpp:1178]: Why that new line?

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp]: Good catch!

**Review by mydeveloperday — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]
