### PR TITLE
[Clang] Fix -Wunused-private-field false negative with defaulted comparison operators

### LINKED ISSUE #116270: Clang fails to warn -Wunused-private-field
clang version: 19.1
os: ubuntu 22.04

```c++
class A
{
public:
   A() : m_x(0)
   {
   }
private:
   const int m_x;
};

#ifdef BUG
class C
{
    friend auto operator==(C, C) -> bool = default;
};
#endif

int main()
{
   [[maybe_unused]] auto c = A();
}
```

clang++ -std=c++20 -Wall main.cpp

```
main.cpp:8:14: warning: private field 'm_x' is not used [-Wunused-private-field]
    8 |    const int m_x;
      |              ^
1 warning generated.
```

clang++ -DBUG -std=c++20 -Wall main.cpp

no warnings

### PR DESCRIPTION
**Pull request by whiteio**
Fix -Wunused-private-field incorrectly suppressing warnings for friend defaulted comparison operators. The warning should only be suppressed when the defaulted comparison is a class member function.

Fixes #116270

### CODE REVIEW

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -7535,7 +7535,7 @@ void Sema::CheckExplicitlyDefaultedFunction(Scope *S, FunctionDecl *FD) {
     return;
   }
 
-  if (DefKind.isComparison())
+  if (DefKind.isComparison() && isa<CXXRecordDecl>(FD->getDeclContext()))
     UnusedPrivateFields.clear();
```
Comment (Maetveis) [inline clang/lib/Sema/SemaDeclCXX.cpp:7539]: If I read this correctly what you did here is you stopped clearing `UnusedPrivateFields` on comparison functions declared as a `friend` function.

It is not a problem for `friend` functions to mark fields as used. The problem in #116270 is that an unrelated class (`C` in the example) causes the warning to be skipped for another class (`A`).
Instead of clearing all fields from `UnusedPrivateFields` (which contain fields of both `A` and `C` in the example) only `C`'s fields should be cleared.

You should loop over `C`'s field and remove all of them from `UnusedPrivateFields` using `UnusedFunctions.remove(Field)`. You find the declaration of `C` by looking at the first parameter of the function being checked, like it is done here [SemaDeclCXX.cpp:9055-9058](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaDeclCXX.cpp#L9055-L9058). The fields can then be queried using `Decl.fields()` which gives you a range of `FieldDecl` pointers, you can pass each of those to `UnusedFunctions.remove`.

If you have questions or if I'm not clear enough feel free to ask :). Thanks for contributing to LLVM!

File: clang/test/SemaCXX/warn-unused-private-field.cpp [hunk 2]
```diff
@@ -20,6 +20,17 @@ class SpaceShipDefaultCompare {
...
 
+class UnusedConstPrivateField {
+ public:
+  UnusedConstPrivateField() : unused_(0) {}
+ private:
+  const int unused_; // expected-warning{{private field 'unused_' is not used}}
+};
+
+class FriendEqDefaultCompare {
+  friend auto operator==(FriendEqDefaultCompare, FriendEqDefaultCompare) -> bool = default;
```
Comment (Maetveis) [inline clang/test/SemaCXX/warn-unused-private-field.cpp:31]: Can you add a test case with a non-friend (normal method) on the unrelated class too?
Also it would be nice to extend the original test (the positive one) with a case where the comparison is defined as a friend function.

File: clang/test/SemaCXX/warn-unused-private-field.cpp [hunk 3]
```diff
@@ -20,6 +20,17 @@ class SpaceShipDefaultCompare {
   int operator<=>(const SpaceShipDefaultCompare &) const = default;
 };
 
+class UnusedConstPrivateField {
+ public:
+  UnusedConstPrivateField() : unused_(0) {}
+ private:
+  const int unused_; // expected-warning{{private field 'unused_' is not used}}
+};
```
Comment (Maetveis) [inline clang/test/SemaCXX/warn-unused-private-field.cpp:28]: Its not relevant that the field is const, and the constructor is also irrelevant to the bug in question.

```suggestion
class HasUnusedField {
  int unused_; // expected-warning{{private field 'unused_' is not used}}
};
```

File: clang/test/SemaCXX/warn-unused-private-field.cpp [hunk 4]
```diff
@@ -20,6 +20,17 @@ class SpaceShipDefaultCompare {
...
+
+class FriendEqDefaultCompare {
```
Comment (Maetveis) [inline clang/test/SemaCXX/warn-unused-private-field.cpp:30]: I would emphasize with the name that this class has no relation to the previous one, because that is what the bug is about.

```suggestion
class UnrelatedFriendEqDefaultCompare {
```

**Review by Maetveis — CHANGES_REQUESTED** [review]

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 1 above)
Comment (whiteio) [reply clang/lib/Sema/SemaDeclCXX.cpp]: Thanks for the pointers! I believe I understand now. I've push a new commit with the changes 1f64a2bb972f5cf9e6455eb721acfd8281ad6981

File: clang/test/SemaCXX/warn-unused-private-field.cpp (hunk 2 above)
Comment (whiteio) [reply clang/test/SemaCXX/warn-unused-private-field.cpp:29]: I've updated the tests, hopefully I didn't misinterpret your comments. I added a non-friend method to the unrelated class and added a case where the comparison is defined as a friend function.

**Comment by whiteio** [comment]
I'll update my changes to fix the other tests that are failing this evening, sorry about that, should have ran the rest of them after making the change.

**Review by Maetveis — APPROVED** [review]
LGTM Thanks!. Can you add a note in the clang release notes here: https://github.com/llvm/llvm-project/blob/d8a1c6d72739c99f4b52a84e907b96b685b44c5e/clang/docs/ReleaseNotes.rst?plain=1#L559

I think this should be good for the text:
```rst
- Fixed a bug where Clang would not emit ``-Wunused-private-field`` warnings when an unrelated class 
  defined a defaulted comparison operator (#GH116270).

  .. code-block:: c++

    class A {
    private:
      int a; // warning: private field 'a' is not used, no diagnostic previously
    };

    class C {
      bool operator==(const C&) = default;
    };

```

(If you want to build the clang documentation to check locally, you can follow https://github.com/llvm/llvm-project/blob/main/llvm/docs/README.txt#L11 and replace `docs-llvm-html` with `docs-clang-html`.)

**Comment by whiteio** [comment]
Thanks for that @Maetveis! I've updated the release notes.

**Comment by Maetveis** [comment]
Thanks! I added @AaronBallman, as a reviewer just to make sure I didn't miss anything, as I don't consider myself an expert when it comes to frontend. @AaronBallman I think you can merge if everything looks okay, I'm pretty sure @whiteio does not have commit rights.

**Comment by Maetveis** [comment]
Hey, @whiteio I'm sorry the review is taking long, Aaron was off for the holidays. In the meantime it looks like some conflicts came up, are you comfortable resolving those or do you need help?

I'll ping Aaron or find some other front-end reviewer once the conflicts are resolved.

**Comment by whiteio** [comment]
@Maetveis Thanks for letting me know, I'll resolve the conflicts and let you know once they're resolved.

**Comment by whiteio** [comment]
Hey @Maetveis, I've addressed the conflicts 👍

**Comment by Maetveis** [comment]
> Hey @Maetveis, I've addressed the conflicts 👍

Thanks, ping @AaronBallman or @erichkeane I would appreciate a second look from someone closer to frontend.

**Review by erichkeane — APPROVED** [review]

**Comment by Maetveis** [comment]
@whiteio You seem to have the [Keep my email addresses private](https://github.com/settings/emails) setting enabled in your account. This will make the merged commit reference `84482442+whiteio@users.noreply.github.com` if you'd like to use your actual address please disable this option.

**Comment by whiteio** [comment]
@Maetveis I've disabled that settings now. Thanks!

**Comment by nico** [comment]
Thanks for this fix!

In our codebase, one example where this warning used to not fire (mostly by coincidence) was a class that did this:

```
class CSSVariableData  {
public:
  CSSVariableData()
      : length_(0),
        is_animation_tainted_(false),
        is_attr_tainted_(false),
        needs_variable_resolution_(false),
        is_8bit_(true),
        has_font_units_(false),
        has_root_font_units_(false),
        has_line_height_units_(false),
        unused_(0) {}

private:
  const unsigned length_ : 22;
  const unsigned is_animation_tainted_ : 1;       // bool.
  const unsigned is_attr_tainted_ : 1;            // bool.
  const unsigned needs_variable_resolution_ : 1;  // bool.
  const unsigned is_8bit_ : 1;                    // bool.
  unsigned has_font_units_ : 1;                   // bool.
  unsigned has_root_font_units_ : 1;              // bool.
  unsigned has_line_height_units_ : 1;            // bool.
  const unsigned unused_ : 3;
};
```

While it's true that `unused_` was unused, initializing all bits in a word seems like a good thing to do, and I can't think of a great way of doing that other than having a named bitfield that's being set to a value.

(You could make the bitfield unnamed and memset the bitfield area to 0, but then you'd have to do that from the class ctor body, meaning you'd have to initialize all member variables there too instead of in the initializer list, and it's pretty awkward, and memsetting member vars is questionable, etc.)

Is there a better way to deal with this particular case that I'm not seeing? Or should this warning maybe not fire for member variables that are part of a bitfield, where other parts are used?

**Comment by VitorRamos** [comment]
There are a few ways around this: if you are using c++17 or later, there is `[[maybe_unused]]`. Another option is to ignore this warning in a specific region with:

```c++
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-private-field"
// your code for which the warning gets suppressed 
#pragma clang diagnostic pop
// not suppressed here
```

**Comment by erichkeane** [comment]
> There are a few ways around this: if you are using c++17 or later, there is `[[maybe_unused]]`. Another option is to ignore this warning in a specific region with:
> 
> ```c++
> #pragma clang diagnostic push
> #pragma clang diagnostic ignored "-Wunused-private-field"
> // your code for which the warning gets suppressed 
> #pragma clang diagnostic pop
> // not suppressed here
> ```

Note you can also spell the standard attribute as `__attribute__((unused))` in boht GCC and Clang.
