### PR TITLE
[ELF] Error for executable .note.GNU-stack unless -z execstack or -r

### LINKED ISSUE #121234: lld silently ignores .note.GNU-stack section that requests exectuable stack
lld contains the comment
```
    // The GNU linker uses .note.GNU-stack section as a marker indicating
    // that the code in the object file does not expect that the stack is
    // executable (in terms of NX bit). If all input files have the marker,
    // the GNU linker adds a PT_GNU_STACK segment to tells the loader to
    // make the stack non-executable. Most object files have this section as
    // of 2017.
```

This is not entirely correct -- the presence of .note.GNU-stack does not necessarily indicate that the object file is compatible with non-exec stack. That is indeed the most common case, but the note actually indicates the object's expected stack protection -- it may have an X flag to indicate an object file that requires executable stack. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278939 for the FreeBSD issue that prompted this.

```
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
...
  [14] .note.GNU-stack   PROGBITS        0000000000000000 0077d8 000000 00   X  0   0  1
```

Executable stacks **should** be exceedingly rare and I have no issue with requiring an explicit `-z execstack`, but I think we should at least produce an error if there's a .note.GNU-stack that specifies exec stack and `-z execstack` is not specified. We should not silently produce broken output.

### PR DESCRIPTION
**Pull request by MaskRay**
.note.GNU-stack with the SHF_EXECINSTR flag requires an executable
stack. This is exceedingly rare. We report an error to force
the user to explicitly request an executable stack.

Close #121234

### CODE REVIEW

File: lld/ELF/InputFiles.cpp [hunk 1]
```diff
@@ -1026,8 +1026,15 @@ InputSectionBase *ObjFile<ELFT>::createInputSection(uint32_t idx,
     // explicitly told to do otherwise (by -z execstack). Because the stack
     // executable-ness is controlled solely by command line options,
     // .note.GNU-stack sections are simply ignored.
```
Comment (smithp35) [inline lld/ELF/InputFiles.cpp:1028]: I think we could update the comment. Something like
```
.note.GNU-stack sections are with one exception, ignored. We give an error message if we encounter an executable .note.GNU-stack to force the user to explicitly request an executable stack.
```

**Review by smithp35 — APPROVED** [review]
LGTM. One small suggestion to update the comment.

File: lld/ELF/InputFiles.cpp (hunk 1 above)
Comment (MaskRay) [reply lld/ELF/InputFiles.cpp:1028]: Thanks for the suggestion. Adopted.

**Comment by vitalybuka** [comment]
https://lab.llvm.org/buildbot/#/builders/139/builds/9570

CC @thurstond

**Comment by thurstond** [comment]
> https://lab.llvm.org/buildbot/#/builders/139/builds/9570
> 
> CC @thurstond

Thanks @vitalybuka! I've updated the QEMU buildbot to add `-z execstack` for MIPS scudo builds (https://github.com/llvm/llvm-zorg/commit/3860e160630ab69cef8a3ef55fa292e1a2b42875)
