### PR TITLE
[SelectionDAG] Fix AArch64 machine verifier bug when expanding LOOP_DEPENDENCE_MASK

### LINKED ISSUE #168227: Machine verifier failure in CodeGen/AArch64/alias_mask.ll
After #167527 (commit e5baf073cb74), running ninja check-llvm-codegen-aarch64 fails with:

```# After Instruction Selection
# Machine code for function whilewr_8_scalarize: IsSSA, TracksLiveness
...
  CCMPXr %2:gpr64common, 0, 4, 13, implicit-def $nzcv, implicit $nzcv
  %4:gpr32 = CSINCWr $wzr, $wzr, 1, implicit $nzcv
...

*** Bad machine code: Expected a register operand. ***
- function:    whilewr_8_scalarize
- basic block: %bb.0 entry (0x109034d18)
- instruction: CCMPXr %2:gpr64common, 0, 4, 13, implicit-def $nzcv, implicit $nzcv
- operand 1:   0
LLVM ERROR: Found 1 machine code errors.```

This happens with the LLVM IR:
```define <1 x i1> @whilewr_8_scalarize(ptr %a, ptr %b) {
; CHECK-LABEL: whilewr_8_scalarize:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub x8, x1, x0
; CHECK-NEXT:    cmp x8, #0
; CHECK-NEXT:    ccmp x8, #0, #4, le
; CHECK-NEXT:    cset w0, eq
; CHECK-NEXT:    ret
entry:
  %0 = call <1 x i1> @llvm.loop.dependence.war.mask.v1i1(ptr %a, ptr %b, i64 1)
  ret <1 x i1> %0
}
```

TargetConstant nodes don't match TableGen ImmLeaf patterns during instruction selection
When the zero constant flows into CCMP formation, the pattern matcher cannot match CCMPXi (immediate form) because the imm0_31 predicate only matches regular Constant nodes.

### PR DESCRIPTION
**Pull request by AZero13**
Fixes: https://github.com/llvm/llvm-project/issues/168227

TargetConstant nodes don't match TableGen ImmLeaf patterns during instruction selection. When this zero constant flows into the AArch64 CCMP formation code, the machine verifier hits an assertion in expensive checks.

### CODE REVIEW

**Comment by AZero13** [comment]
@juliannagele

**Comment by topperc** [comment]
The type legalizer changes LGTM. I don't know anything about the AArch64ISelLowering changes.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -26013,9 +26013,12 @@ static SDValue reassociateCSELOperandsForCSE(SDNode *N, SelectionDAG &DAG) {
...
     // operands of the SUBS instruction.
-    std::swap(CmpOpToMatch, CmpOpOther);
-    if (SDValue R = Fold(getSwappedCondition(CC), CmpOpToMatch, CmpOpToMatch))
-      return R;
+    auto NewCC = getSwappedCondition(CC);
+    if (NewCC != AArch64CC::AL) {
+      std::swap(CmpOpToMatch, CmpOpOther);
+      if (SDValue R = Fold(NewCC, CmpOpToMatch, CmpOpToMatch))
+        return R;
+    }
```
Comment (MacDue) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp]: Does this have any relation to the LOOP_DEPENDENCE_MASK change? Looks like you've just copied in https://github.com/llvm/llvm-project/pull/160753.

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp]: Yeah that commit was fused in by mistake.

**Review by MacDue — APPROVED** [review]
