### PR TITLE
[GlobalISel] Constant-fold G_PTR_ADD with different type sizes

### LINKED ISSUE #81464: [AMDGPU][GlobalISel] Assertion failure in constant folding in buildPtrAdd
On this [test case](https://github.com/llvm/llvm-project/files/14237614/r.txt) I get:
```
$ llc -mtriple=amdgcn -mcpu=gfx1030 -global-isel r.ll
llc: lib/Support/APInt.cpp:198: llvm::APInt &llvm::APInt::operator+=(const llvm::APInt &): Assertion `BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed.
```

### PR DESCRIPTION
**Pull request by Pierre-vh**
All other opcodes in the list are constrained to have the same type on both operands, but not G_PTR_ADD.

Fixes  #81464

### CODE REVIEW

File: llvm/lib/CodeGen/GlobalISel/Utils.cpp [hunk 1]
```diff
@@ -660,8 +660,15 @@ std::optional<APInt> llvm::ConstantFoldBinOp(unsigned Opcode,
   default:
     break;
   case TargetOpcode::G_ADD:
-  case TargetOpcode::G_PTR_ADD:
     return C1 + C2;
+  case TargetOpcode::G_PTR_ADD: {
+    // Types can be of different width here.
+    if (C1.getBitWidth() < C2.getBitWidth())
+      return C1.zext(C1.getBitWidth()) + C2;
```
Comment (piotrAMD) [inline llvm/lib/CodeGen/GlobalISel/Utils.cpp:667]: C2.getBitWidth() ?

**Comment by tschuett** [comment]
I am not yet convinced.
```
G_PTR_ADD p8 %5, s32 %6
```
The pointer and the offset have different types and probably different sizes. p8 could be some weird 128bit pointer in address space 8.

**Comment by tschuett** [comment]
Does `LLT::pointer(8, 128)` guarantee that I may perform plain integer arithmetic on the pointer?

**Comment by Pierre-vh** [comment]
Depends on the operation, if you have `G_PTR_ADD` then you can directly increment the pointer.
If you `G_PTRTOINT` first you can use `G_ADD` but then you need the type of the LHS and RHS to match, so you need to ext/trunc as needed.
For `G_PTR_ADD` it's like a GEP so you can use a different type for the offset.

File: llvm/lib/CodeGen/GlobalISel/Utils.cpp [hunk 2]
```diff
@@ -660,8 +660,17 @@ std::optional<APInt> llvm::ConstantFoldBinOp(unsigned Opcode,
...
     return C1 + C2;
+  case TargetOpcode::G_PTR_ADD: {
+    // Types can be of different width here.
+    if (C1.getBitWidth() > C2.getBitWidth())
+      return C2.zext(C1.getBitWidth()) + C1;
+    // We always need to return something the same size as C1, so
+    // truncate in this case.
+    if (C1.getBitWidth() < C2.getBitWidth())
+      return C1 + C2.trunc(C1.getBitWidth());
+    return C1 + C2;
```
Comment (jayfoad) [inline llvm/lib/CodeGen/GlobalISel/Utils.cpp:672]: Just use C2.zextOrTrunc unconditionally? Also, why is zero extending correct? (Why not sign extending for example?)

**Comment by tschuett** [comment]
Is constant-folding G_PTR_ADD target-independent? Does it depend on the address space? Do AMDGPU and AArch64 do the same for *all* address spaces?

**Comment by Pierre-vh** [comment]
> Is constant-folding G_PTR_ADD target-independent? Does it depend on the address space? Do AMDGPU and AArch64 do the same for _all_ address spaces?

Very good question, and I believe the answer is yes - it depends on the AS. It's safe for most address spaces but in the case that the AS is special (e.g. fat pointer) it's probably not safe. I think we're missing a hook somewhere to ask the target if it's safe to trivially fold G_PTR_ADD as a `G_ADD`. cc @arsenm ?
That or I'm misunderstanding how G_PTR_ADD is supposed to work.

File: llvm/lib/CodeGen/GlobalISel/Utils.cpp (hunk 2 above)
Comment (Pierre-vh) [reply llvm/lib/CodeGen/GlobalISel/Utils.cpp:672]: I think sext is probably more correct as offsets can be negative, right?

**Comment by arsenm** [comment]
You should check the DataLayout for nonintegral address spaces

**Comment by Pierre-vh** [comment]
> You should check the DataLayout for nonintegral address spaces

I just noticed it's checked by the caller. That function isn't called for G_PTR_ADD for non-integral AS

File: llvm/lib/CodeGen/GlobalISel/Utils.cpp (hunk 2 above)
Comment (Pierre-vh) [reply llvm/lib/CodeGen/GlobalISel/Utils.cpp]: I think SEXT is the correct one. It's what the legalizer does for widenScalar on `G_PTR_ADD`.

Comment (jayfoad) [reply llvm/lib/CodeGen/GlobalISel/Utils.cpp]: OK.

File: llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+    ; CHECK-NEXT: SI_RETURN_TO_EPILOG implicit $sgpr0
+    %1:_(p1) = G_CONSTANT i64 0
+    %3:_(s32) = G_CONSTANT i32 3
+    %0:_(<4 x s32>) = G_LOAD %1 :: (load (<4 x s32>) from `ptr addrspace(1) null`, addrspace 1)
+    %2:_(s32) = G_EXTRACT_VECTOR_ELT %0, %3
+    $sgpr0 = COPY %2
+    SI_RETURN_TO_EPILOG implicit $sgpr0
+...
+
+# Tries to emit a foldable G_PTR_ADD with (p1, s128) operands.
```
Comment (jayfoad) [inline llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir:23]: Does this actually succeed in creating G_PTR_ADD with s128 RHS? If not, maybe it would be better to enforce in MachineVerifier that the RHS is no wider than the LHS?

**Comment by jayfoad** [comment]
I wonder if G_PTR_ADD has the same semantics as IR getelementptr, where only the low order index-size bits of the pointer value are affected. @nikic do you know?

**Comment by nikic** [comment]
> I wonder if G_PTR_ADD has the same semantics as IR getelementptr, where only the low order index-size bits of the pointer value are affected. @nikic do you know?

As we lower getelementptr to G_PTR_ADD, I'd expect so...

File: llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir (hunk 3 above)
Comment (Pierre-vh) [reply llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir:23]: It should, `MachineVerifier` doesn't check for it + `MachineIRBuilder` doesn't complain

I can make a follow-up patch to enforce `RHS <= LHS` if you want

**Review by jayfoad — APPROVED** [review]

File: llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir (hunk 3 above)
Comment (jayfoad) [reply llvm/test/CodeGen/AMDGPU/GlobalISel/combine-extract-vector-load.mir:23]: > _If_ we do anything, maybe we should enforce that the RHS has to be the width of the index size for the address space.

#84352
