### PR TITLE
[clang] CTAD: Generate deduction guides for alias templates from non-template explicit deduction guides

### LINKED ISSUE #94927: CTAD for alias templates fails with non-template explicit deduction guide
Example:
```cpp
template<typename T> struct A {
    A(T);
};

A(int) -> A<char>;

template<typename T>
using B = A<T>;

A a2(100);
B b2(100);

using A2 = A<char>;
using A2 = decltype(a2); // works

using B2 = B<char>;
using B2 = decltype(b2); // fails, deduces A<int>
```

https://godbolt.org/z/v5W1M4TKq

### PR DESCRIPTION
**Pull request by hokein**
This patch addresses an issue where non-template explicit deduction guides were not considered when synthesized the deduction guides for alias templates.

Fixes #94927.

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -3216,6 +3226,44 @@ void DeclareImplicitDeductionGuidesForTypeAlias(
...
+      // Clone the parameters.
+      unsigned ProcessedParamIndex = 0;
+      for (auto *P : DG->parameters()) {
+        auto *TSI = SemaRef.Context.getTrivialTypeSourceInfo(P->getType());
+        ParmVarDecl *NewParam = ParmVarDecl::Create(
+            SemaRef.Context, G->getDeclContext(), P->getBeginLoc(),
+            P->getLocation(), nullptr, TSI->getType(), TSI, SC_None, nullptr);
+        NewParam->setScopeInfo(0, ProcessedParamIndex);
+        FPTL.setParam(ProcessedParamIndex, NewParam);
+        ProcessedParamIndex++;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:3245]: Do we need to inject the `NewParam` into the new `DeductionGuide` later? i.e. call `NewParam->setOwningFunction()` somewhere below.

**Review by zyn0217 — COMMENTED** [review]
Thanks for the patch! I think the overall approach looks good, and with this patch, I also need to remove the assumption in my https://github.com/llvm/llvm-project/pull/96084 that there's always a template decl associated with the implicit deduction guide.

**Review by zyn0217 — APPROVED** [review]
One nit, otherwise LGTM.

Regarding the issue of attaching the constraint to a non-template function, pragmatically, this is just something internal to compiler, and we're still conforming to the standard in terms of the user's codes. So, it is probably fine now, given that GCC also seems to take a similar approach here.

However, let's wait another few days before merging if @zygoloid has some insights.
