### PR TITLE
R600: Expand is_fpclass

### LINKED ISSUE #135083: Luxmark crashes on Mesa Clover with LLVM Error: Cannot select: 0x7fdadb775150: i32 = is_fpclass 0x7fdadbf90ad0, TargetConstant:i32<504>
To reproduce:

- On Debian Sid
- with a terascale 2 GPU (other terascale gpus may also be affected)
- running Mesa 25.0.3-1/LLVM 19.1.7
- download and run Luxmark V3.1

This gives the following error:
```
./luxmark
LLVM ERROR: Cannot select: 0x7fdadb775150: i32 = is_fpclass 0x7fdadbf90ad0, TargetConstant:i32<504>
  0x7fdadbf90ad0: f32 = extract_vector_elt 0x7fdad911c920, Constant:i32<1>
    0x7fdad911c920: v2f32 = bitcast 0x7fdad8eec650
      0x7fdad8eec650: v2i32,ch = load<(load (s64) from %ir.sunkaddr, align 4, !tbaa !14, addrspace 1)> 0x7fdaf3951948, 0x7fdad8eed740, undef:i32
        0x7fdad8eed740: i32 = add nuw 0x7fdad8e286f0, Constant:i32<8>
          0x7fdad8e286f0: i32,ch = CopyFromReg 0x7fdaf3951948, Register:i32 %4
            0x7fdad8eed4a0: i32 = Register %4
          0x7fdad8eedcf0: i32 = Constant<8>
        0x7fdad90f7840: i32 = undef
    0x7fdadbf90360: i32 = Constant<1>
  0x7fdadb775d20: i32 = TargetConstant<504>
In function: AdvancePaths_MK_SPLAT_SAMPLE
./luxmark: line 12: 12037 Aborted                 ./luxmark.bin "$@"
```
Similar errors result from other Opencl applications.
`clpeak` seg faults instead:
```
Starting program: /usr/bin/clpeak 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdc7ff6c0 (LWP 11482)]
[New Thread 0x7fffdbffe6c0 (LWP 11483)]
[New Thread 0x7fffdd1ff6c0 (LWP 11484)]
[New Thread 0x7fffdb7fd6c0 (LWP 11485)]

Platform: Clover
  Device: AMD CAICOS (DRM 2.50.0 / 6.12.21-amd64, LLVM 19.1.7)
    Driver version  : 25.0.3-1 (Linux x64)
    Compute units   : 2
    Clock frequency : 625 MHz

Thread 1 "clpeak" received signal SIGSEGV, Segmentation fault.
0x00007fffdf0c6bf4 in llvm::TargetRegisterInfo::getMatchingSuperRegClass(llvm::TargetRegisterClass const*, llvm::TargetRegisterClass const*, unsigned int) const ()
   from /lib/x86_64-linux-gnu/libLLVM.so.19.1
```
This entirely breaks OpenCL on Mesa on Debian Sid.

### PR DESCRIPTION
**Pull request by arsenm**
Fixes #135083

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/R600ISelLowering.cpp [hunk 1]
```diff
@@ -100,6 +100,11 @@ R600TargetLowering::R600TargetLowering(const TargetMachine &TM,
 
   setOperationAction(ISD::FSUB, MVT::f32, Expand);
 
+  setOperationAction(ISD::IS_FPCLASS,
+                     {MVT::f32, MVT::v2f32, MVT::v3f32, MVT::v4f32, MVT::v5f32,
```
Comment (shiltian) [inline llvm/lib/Target/AMDGPU/R600ISelLowering.cpp:104]: Does it really support this many data types?

**Review by shiltian — COMMENTED** [review]
WOW, R600 related changes…

File: llvm/lib/Target/AMDGPU/R600ISelLowering.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Target/AMDGPU/R600ISelLowering.cpp:104]: Technically only need to set this for the minimum set of legal types, but it doesn't hurt to set it on illegal types that already defaulted to expand

Comment (arsenm) [reply llvm/lib/Target/AMDGPU/R600ISelLowering.cpp:104]: It turns out this is also working around some kind of bug in select / select_cc handling so I'm going to leave it alone

**Review by shiltian — APPROVED** [review]
