### PR TITLE
[clangd] check for synthesized symbols when tracking include locations

### LINKED ISSUE #75115: clangd in MSVC mode crashes when indexing a C source file which defines assert macro
In MSVC compat mode, a simple C source code like this causes clangd to make an illegal hash map insertion, leading to a crash that can be observed with an assertions enabled build:
```
#define assert
```
Produces:
```
Assertion failed: !KeyInfoT::isEqual(Val, EmptyKey) && !KeyInfoT::isEqual(Val, TombstoneKey) && "Empty/Tombstone value shouldn't be inserted into map!"
```

The problem here is that we are not checking for invalid source locations when inserting symbols into the symbol -> include file map, which is a situation that occurs with synthesized symbols.

In this repro, the assert definition triggers a workaround (https://github.com/llvm/llvm-project/commit/8da090381d567d0ec555840f6b2a651d2997e4b3) where a `static_assert` macro is also implicitly defined.

### PR DESCRIPTION
**Pull request by mizvekov**
This fixes https://github.com/llvm/llvm-project/issues/75115

In C mode with MSVC compatibility, when the `assert` macro is defined, as a workaround, `static_assert` is implicitly defined as well, if not already so, in order to work around a broken `assert.h` implementation.
This workaround was implemented in https://github.com/llvm/llvm-project/commit/8da090381d567d0ec555840f6b2a651d2997e4b3

A synthesized symbol does not occur in source code, and therefore should not have valid source location, but this was not checked when inserting this into a `symbol -> include file` map.

The invalid FileID value is used for empty key representation in the include file hash table, so it's not valid to insert it.

### CODE REVIEW

**Comment by kadircet** [comment]
Hi @mizvekov thanks for the fix, but I am not sure if this is at the right level. The way you're bailing out currently prevents clangd from indexing all implicit definitions, even if we have a hard-coded mapping for them (based on the symbol name).

Also the map you're preventing the insertion stores FileIDs as values, not keys, hence it isn't the place firing assertion failures. Can you instead move the logic to SymbolCollector::finish, which uses FileIDs to determine includers for objective-c symbols? we should only perform that logic if there's a valid FileID.

**Comment by mizvekov** [comment]
> Hi @mizvekov thanks for the fix, but I am not sure if this is at the right level. The way you're bailing out currently prevents clangd from indexing all implicit definitions, even if we have a hard-coded mapping for them (based on the symbol name).
> 
> Also the map you're preventing the insertion stores FileIDs as values, not keys, hence it isn't the place firing assertion failures. Can you instead move the logic to SymbolCollector::finish, which uses FileIDs to determine includers for objective-c symbols? we should only perform that logic if there's a valid FileID.

I see. Though the situation you describe seems impossible at the present state of the implementation.

For standard library stuff, we have hardcoded std::move and std::remove, implemented [here](https://github.com/llvm/llvm-project/blob/6d8fe3dc9a4f6225c4c84de578469efc50d7684d/clang-tools-extra/include-cleaner/lib/FindHeaders.cpp#L117) but those require some sort of user provided declaration somewhere in code, which will have a valid source location, and we indeed unit test that.

As an aside, I think in the above case we should honor the `-freestanding` flag, but currently we do not.

For the builtin-which-requires-include case, that is unimplemented, with a FIXME note: https://github.com/llvm/llvm-project/blob/6d8fe3dc9a4f6225c4c84de578469efc50d7684d/clang-tools-extra/include-cleaner/lib/FindHeaders.cpp#L177

I agree in principle to the change you suggested, even if presently non testable, but I still think it makes sense to skip inserting invalid FileIDs into the `IncludeFiles` map.

**Comment by mizvekov** [comment]
@kadircet ping

**Comment by mizvekov** [comment]
@kadircet gentle ping

File: clang-tools-extra/clangd/index/SymbolCollector.cpp [hunk 1]
```diff
@@ -821,7 +821,8 @@ void SymbolCollector::setIncludeLocation(const Symbol &S, SourceLocation DefLoc,
 
   // Use the expansion location to get the #include header since this is
   // where the symbol is exposed.
-  IncludeFiles[S.ID] = SM.getDecomposedExpansionLoc(DefLoc).first;
+  if (FileID FID = SM.getDecomposedExpansionLoc(DefLoc).first; FID.isValid())
```
Comment (kadircet) [inline clang-tools-extra/clangd/index/SymbolCollector.cpp:824]: i still think it's wasteful to check both in both places, but now that you do a `lookup` instead of `at` below, i'll leave this to you.

**Review by kadircet — APPROVED** [review]
thanks and sorry for leaving this out there, I was busy with other things and then OOO.
