### PR TITLE
[clangd] Fix crash with null check for Token at Loc

### LINKED ISSUE #94599: Clangd doesn't find cross references to UDL
```cpp
bool operator"" _b(unsigned long long value);
    
bool x = 1_b;
```

Finding references on `_^b` does not give any references except itself. Reference to `_b` in `bool x = 1_b` is missing.

Similarly, `1_^b` gives no references at all.

### PR DESCRIPTION
**Pull request by usx95**
Fixes https://github.com/llvm/llvm-project/issues/94599

### CODE REVIEW

File: clang-tools-extra/clangd/XRefs.cpp [hunk 1]
```diff
@@ -1354,6 +1354,8 @@ maybeFindIncludeReferences(ParsedAST &AST, Position Pos,
 
         ReferencesResult::Reference Result;
         const auto *Token = AST.getTokens().spelledTokenAt(Loc);
+        if (!Token)
```
Comment (kadircet) [inline clang-tools-extra/clangd/XRefs.cpp:1357]: it's a little bit hard to see what issue we're fixing/preventing here, can you add some context?

Looking at the test case, i guess we're getting a reference for the UDLs pointing at the middle of a token?

If that's the case, i think we might as well fix the feature instead of working around. Moreover I don't think that broken behavior is specific to xrefs on includes, it'll show up on other places that use `spelledTokenAt` too.

In this code path particularly, we actually don't want a `Token`, we can just use `Loc` and `Lexer::getLocForEndOfToken(Loc)` for the `range` calculation below.

I think a more complete fix would be to actually change `spelledTokenAt` to return the `Token` as long as `Loc` is contained (or have a new method that returns the token containing the location). That one is more involved though, so if you choose not to do that, can you at least file a bug around clangd features not working properly with UDLs pointing into this PR?

**Review by kadircet — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clangd/XRefs.cpp (hunk 1 above)
Comment (usx95) [reply clang-tools-extra/clangd/XRefs.cpp:1357]: I have filled https://github.com/llvm/llvm-project/issues/94599.

```cpp
bool operator"" _b(unsigned long long value);
auto x = 1_b;
```
As you said, the problem is that we get a reference to the middle of a spelled token. Ref at`1^_b`, spelled token: `[[1^b]]`.

All the users of `spelledTokenAt` seems to be doing the null check or an assertion. So I think a null check here seems warranted (if not an assertion).

As far as supporting UDL as `spelledTokens`, in general, I don't have a great idea. `clang::Token` from `Lexer::LexFromRawLexer` seems to not break the token into two [1][_b].

Another simpler solution could be to just change `spelledTokens` and instead of returning `nullptr` in 
````
 if (!Tok || Tok->location() != Loc)
    return nullptr;
```
we could return if `Tok` if `Tok->location() <= Loc && Loc < Tok->endLocation()`
WDYT ?

Comment (kadircet) [reply clang-tools-extra/clangd/XRefs.cpp:1357]: > All the users of spelledTokenAt seems to be doing the null check or an assertion. So I think a null check here seems warranted (if not an assertion).

this place also deserves an assertion, we already go the extra mile to map the location into main-file, hence we can also assert (but that won't help with your crash :/)

> As far as supporting UDL as spelledTokens, in general, I don't have a great idea. clang::Token from Lexer::LexFromRawLexer seems to not break the token into two [1][_b].

Unfortunately it's a single token for raw-lexer. But we don't need a token here, it's enough to get the end location for the token. Hence I was suggesting to use `Lexer::getLocForEndOfToken` and just populate the ranges, without really finding a `Token` associated with the location. (or are you saying even `getLocForEndOfToken` is doing the wrong thing here?)

> we could return if Tok if Tok->location() <= Loc && Loc < Tok->endLocation()

Right, that's what I meant with `I think a more complete fix would be to actually change spelledTokenAt to return the Token as long as Loc is contained`. If you feel like it, i'd definitely appreciate such a change. All call-sites are in clangd, so we just need to decide if all of them are actually OK with this behavior and don't really rely on `spelledTokenAt` failing when it's called with a random offset into the token.

Comment (usx95) [reply clang-tools-extra/clangd/XRefs.cpp:1357]: Modified `spelledTokenAt`.

File: clang/lib/Tooling/Syntax/Tokens.cpp [hunk 2]
```diff
@@ -387,8 +387,8 @@ const syntax::Token *TokenBuffer::spelledTokenAt(SourceLocation Loc) const {
   assert(Loc.isFileID());
   const auto *Tok = llvm::partition_point(
       spelledTokens(SourceMgr->getFileID(Loc)),
-      [&](const syntax::Token &Tok) { return Tok.location() < Loc; });
-  if (!Tok || Tok->location() != Loc)
+      [&](const syntax::Token &Tok) { return Tok.endLocation() <= Loc; });
+  if (!Tok || Tok->location() > Loc || Loc >= Tok->endLocation())
```
Comment (kadircet) [inline clang/lib/Tooling/Syntax/Tokens.cpp:391]: i don't think `Loc >= Tok->endLocation()` can ever be true. `partition_point` will return either null or a `Tok` s.t. `Loc < Tok.endLocation()`.

nit: can you re-write the previous condition as `Loc < Tok->location()`, i think it's easier to visualize the relationship when it's left-to-right :D

File: clang-tools-extra/clangd/XRefs.cpp (hunk 1 above)
Comment (kadircet) [reply clang-tools-extra/clangd/XRefs.cpp:1357]: thanks! can you also rename `spelledTokenAt` to `spelledTokenCotaining` and update the comment and change the null-check here to an assertion?

also, what's the conclusion of investigation around `don't really rely on spelledTokenAt failing when it's called with a random offset into the token`?

File: clang/lib/Tooling/Syntax/Tokens.cpp (hunk 2 above)
Comment (kadircet) [reply clang/lib/Tooling/Syntax/Tokens.cpp:391]: can you also update `clang/unittests/Tooling/Syntax/TokensTest.cpp` ?

**Review by kadircet — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clangd/XRefs.cpp (hunk 1 above)
Comment (usx95) [reply clang-tools-extra/clangd/XRefs.cpp:1357]: Done.
> also, what's the conclusion of investigation around don't really rely on spelledTokenAt failing when it's called with a random offset into the token?

I relied on the tests here. Also, the usages of `spelledTokenCotaining` does not seem to relying on getting a `nullptr` if the location is inside a token, as compared to strictly at the beginning of tok.

File: clang-tools-extra/clangd/SemanticHighlighting.cpp [hunk 3]
```diff
@@ -447,7 +447,7 @@ class HighlightingsBuilder {
     if (!RLoc.isValid())
       return;
 
-    const auto *RTok = TB.spelledTokenAt(RLoc);
+    const auto *RTok = TB.spelledTokenContaining(RLoc);
```
Comment (kadircet) [inline clang-tools-extra/clangd/SemanticHighlighting.cpp:450]: so looks like this call site was actually expecting it to be null when provided with an offset into the token, but that's OK overall, as it's also trying to just slice the token.

can you update the surroundings to reflect the new behavior so we don't leave old state documented for future travelers? something like:
```

// RLoc is either part of `>>` or a spelled token on its own `>`.
// If it's the former, slice to have length of 1, if latter use the token as-is.
assert(RTok);
if (RTok->kind() == ...) 
```

**Review by kadircet — APPROVED** [review]

File: clang-tools-extra/clangd/SemanticHighlighting.cpp (hunk 3 above)
Comment (usx95) [reply clang-tools-extra/clangd/SemanticHighlighting.cpp:450]: Done.
