### PR TITLE
[clang-tidy] Fix some false negatives in `bugprone-throw-keyword-missing`

### LINKED ISSUE #115540: [clang-tidy] `bugprone-throw-keyword-missing` false negatives from `hasAncestor` skipping too much
The matcher is using `hasAncestor` and could be skipping many different issues, simply because they have an ancestor node (e.g., `VarDecl`) but that node is not closely related to the construct expression itself.

```c++
struct RegularException {
    RegularException(int);
};
void foo() {
    const auto var = []() {
        RegularException{0};  // FN, ignored because of `hasAncestor(varDecl())`
        return 0;
    };
}

struct Bar {
    Bar() : v{0} {
        RegularException{0};  // FN, ignored because of `hasAncestor(cxxConstructorDecl())`
    }
    int v;
};
```

https://godbolt.org/z/6br6f91vc

### PR DESCRIPTION
**Pull request by localspook**
Fixes #115540.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/throw-keyword-missing.cpp [hunk 1]
```diff
@@ -49,7 +49,7 @@ struct RegularException {
 
 // --------------
```
Comment (zeyi2) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/throw-keyword-missing.cpp]: Could we add a new test like:
```c++
namespace std {
  class exception {
  public:
    virtual ~exception();
  };
}

struct RegularException : public std::exception {
  RegularException(int);
};

void DestructorTest() {
  RegularException(0);
}
```

File: clang-tools-extra/clang-tidy/bugprone/ThrowKeywordMissingCheck.cpp [hunk 2]
```diff
@@ -11,24 +11,29 @@
...
 using namespace clang::ast_matchers;
+using namespace clang::ast_matchers::internal;
 
 namespace clang::tidy::bugprone {
 
 void ThrowKeywordMissingCheck::registerMatchers(MatchFinder *Finder) {
+  const VariadicDynCastAllOfMatcher<Stmt, AttributedStmt> AttributedStmt;
+  // Matches an 'expression-statement', as defined in [stmt.expr]/1.
+  // Not to be confused with the similarly-named GNU extension, the
+  // statement expression.
```
Comment (localspook) [inline clang-tools-extra/clang-tidy/bugprone/ThrowKeywordMissingCheck.cpp]: https://eel.is/c++draft/stmt.expr

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -426,7 +426,8 @@ Changes in existing checks
 - Improved :doc:`bugprone-throw-keyword-missing
   <clang-tidy/checks/bugprone/throw-keyword-missing>` check by only considering
   the canonical types of base classes as written and adding a note on the base
-  class that triggered the warning.
+  class that triggered the warning. Also, fixed an issue where the check
+  wouldn't fire in constructors or (in certain contexts) lambdas.
```
Comment (EugeneZelenko) [inline clang-tools-extra/docs/ReleaseNotes.rst]: `false negatives` wording?

**Review by zeyi2 — APPROVED** [review]
But please wait for other reviewers :)

**Review by vbvictor — APPROVED** [review]
