### PR TITLE
[Flang] Fix symbol name clash when dummy procedure name is the same as common-block-name

### LINKED ISSUE #122822: [Flang] Compilation abnormally terminates when dummy procedure name is the same as common-block-name
```
Version of flang : 20.0.0(f4230b4332262dffb0bd3b7a2f8d6deb2e96488e)/AArch64
```

When `dummy procedure name` is the same as `common-block-name`, a compilation terminates abnormally (Lowering to LLVM IR failed).  
There should be no problem that the dummy procedure name and common-block-name have the same name.

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

terrcom3_2.f:
```fortran
      subroutine ss5()
      common /com_dummy1/ x
      interface
         subroutine com_dummy1()
         end subroutine
      end interface
      print *,fun_sub(com_dummy1)
      end
```

```
$ flang terrcom3_2.f -c
error: loc("/work/home/ohno/CT/test/fort/tp/reproducerJ/MCS/fe2ferr/terrcom3_2.f":4:21): redefinition of symbol named 'com_dummy1_'
error: Lowering to LLVM IR failed
error: loc("/work/home/ohno/CT/test/fort/tp/reproducerJ/MCS/fe2ferr/terrcom3_2.f":2:15): LLVM Translation failed for operation: fir.global
error: failed to create the LLVM module
$
```

```
$ gfortran terrcom3_2.f -c
terrcom3_2.f:2:25:

    2 |       common /com_dummy1/ x
      |                         1
Error: COMMON block ‘com_dummy1’ at (1) cannot have the EXTERNAL attribute
$
```

```
$ ifx terrcom3_2.f -c; ls -al *.o
-rw-r--r--. 1 32800043 32800043 1136 Jan  8 02:00 terrcom3_2.o
$
```

### PR DESCRIPTION
**Pull request by ceseo**
Dummy procedures in interface blocks are not external procedures that need to be linked. Do not externalize those.

Fixes #122822

### CODE REVIEW

File: flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp [hunk 1]
```diff
@@ -82,6 +82,48 @@ void ExternalNameConversionPass::runOnOperation() {
...
+              for (auto use : *uses) {
+                auto *user = use.getUser();
+                if (mlir::isa<fir::CallOp>(user) ||
+                    mlir::isa<mlir::func::CallOp>(user)) {
+                  isDirectlyCalled = true;
+                  break;
+                }
+              }
+            }
+            if (!isDirectlyCalled) {
```
Comment (clementval) [inline flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp:120]: No brace on simple if

File: flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp [hunk 2]
```diff
@@ -82,6 +82,48 @@ void ExternalNameConversionPass::runOnOperation() {
...
+
+          // Skip externalization if the function has a conflicting common block
+          // and is not directly called (i.e. procedure pointers or type
+          // specifications)
+          if (hasConflictingCommonBlock) {
+            bool isDirectlyCalled = false;
+            auto uses = funcOp.getSymbolUses(mod);
+            if (uses.has_value()) {
+              for (auto use : *uses) {
+                auto *user = use.getUser();
```
Comment (clementval) [inline flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp:112]: Spell out auto

File: flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp [hunk 3]
```diff
@@ -82,6 +82,48 @@ void ExternalNameConversionPass::runOnOperation() {
...
+            }
+            return mlir::WalkResult::advance();
+          });
+
+          // Skip externalization if the function has a conflicting common block
+          // and is not directly called (i.e. procedure pointers or type
+          // specifications)
+          if (hasConflictingCommonBlock) {
+            bool isDirectlyCalled = false;
+            auto uses = funcOp.getSymbolUses(mod);
```
Comment (clementval) [inline flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp:109]: Spell out auto

File: flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp [hunk 4]
```diff
@@ -82,6 +82,48 @@ void ExternalNameConversionPass::runOnOperation() {
         mlir::SymbolTable::getSymbolAttrName());
     auto deconstructedName = fir::NameUniquer::deconstruct(symName);
     if (fir::NameUniquer::isExternalFacingUniquedName(deconstructedName)) {
+      // Check if this is a private function that would conflict with a common
+      // block and get its mangled name.
+      if (auto funcOp = llvm::dyn_cast<mlir::func::FuncOp>(funcOrGlobal)) {
+        if (funcOp.isPrivate()) {
+          auto mangledName =
```
Comment (clementval) [inline flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp:89]: Spell out auto

File: flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp [hunk 5]
```diff
@@ -82,6 +82,46 @@ void ExternalNameConversionPass::runOnOperation() {
...
+      // block and get its mangled name.
+      if (auto funcOp = llvm::dyn_cast<mlir::func::FuncOp>(funcOrGlobal)) {
+        if (funcOp.isPrivate()) {
+          std::string mangledName =
+              mangleExternalName(deconstructedName, appendUnderscoreOpt);
+          auto mod = funcOp->getParentOfType<mlir::ModuleOp>();
+          bool hasConflictingCommonBlock = false;
+
+          // Check if any existing global has the same mangled name.
+          mlir::SymbolTable symbolTable(mod);
```
[the remark this answers is not in the document]
Comment (ceseo) [reply flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp:95]: OK, I'll take a look. Thanks!

**Comment by ceseo** [comment]
@clementval any other comments about this? Thanks!

**Review by clementval — COMMENTED** [review]
Overall it looks good. I'm just thinking if your case requires to keep the symbol table up to date with the other renaming happening in this pass.

**Comment by ceseo** [comment]
> Overall it looks good. I'm just thinking if your case requires to keep the symbol table up to date with the other renaming happening in this pass.

OK, I'll rebase against the current master since it's been a while this is under review. If you have any suggestions for a test that might expose potential issues, please let me know.

**Comment by clementval** [comment]
> > > > Overall it looks good. I'm just thinking if your case requires to keep the symbol table up to date with the other renaming happening in this pass.
> > > 
> > > 
> > > OK, I'll rebase against the current master since it's been a while this is under review. If you have any suggestions for a test that might expose potential issues, please let me know.
> > 
> > 
> > Your rebase likely went wrong.
> 
> Sorry about that. Git was configured to merge by default.

You can fix it and force push

**Review by clementval — APPROVED** [review]
