### PR TITLE
[AArch64] Move BSL generation to lowering.

### LINKED ISSUE #149380: [AArch64] ORRv: Bad machine code: Using an undefined physical register
For a build with expensive checks enabled, this input:

https://godbolt.org/z/jvGvPfaP7

```
#include <algorithm>
unsigned short a;
void g(int b, unsigned long long c[][5], unsigned long long d[]) {
  for (short e = 0; e < (short)b; e += 3)
    for (short f = 0; f < 15; f += 2)
      a = std::min(a, (unsigned short)(signed char)std::max(d[e], c[f][f]));
}
```

compiled with `clang++  -Ofast -mcpu=grace`, runs into this error:

```
*** Bad machine code: Using an undefined physical register ***
- function:    _Z1giPA5_yPy
- basic block: %bb.13 vector.body (0xaaaab3961410)
- instruction: $q10 = ORRv16i8 $q3, killed $q3
- operand 2:   killed $q3
```

### PR DESCRIPTION
**Pull request by davemgreen**
It is generally better to allow the target independent combines before creating AArch64 specific nodes (providing they don't mess it up). This moves the generation of BSL nodes to lowering, not a combine, so that intermediate nodes are more likely to be optimized. There is a small change in the constant handling to detect legalized buildvector arguments correctly.

Fixes #149380 but not directly. #151856 contains a direct fix for expanding the pseudos.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -14737,12 +14737,109 @@ static SDValue tryLowerToSLI(SDNode *N, SelectionDAG &DAG) {
...
+  // We only have to look for constant vectors here since the general, variable
+  // case can be handled in TableGen.
+  unsigned Bits = VT.getScalarSizeInBits();
+  for (int i = 1; i >= 0; --i)
+    for (int j = 1; j >= 0; --j) {
+      APInt Val1, Val2;
+
+      if (ISD::isConstantSplatVector(N0->getOperand(i).getNode(), Val1) &&
+          ISD::isConstantSplatVector(N1->getOperand(j).getNode(), Val2) &&
+          ~Val1.trunc(Bits) == Val2.trunc(Bits)) {
```
Comment (sdesmalen-arm) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:14806]: I see this function is not entirely a case of moving. Can you pre-commit the moving of this function as a non-functional change, and rebase this one on top?

**Review by rj-jesus — COMMENTED** [review]
Hi @davemgreen, I think this sounds like a good idea. The free variable cases I looked at recently should be unaffected by this change in any case. :)

**Comment by davemgreen** [comment]
I've rebased over 6f272d1ecf70fc555efb1a0c601095031d5b2ca9 and addressed some comments. Thanks.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 2]
```diff
@@ -14742,23 +14742,15 @@ static SDValue tryLowerToSLI(SDNode *N, SelectionDAG &DAG) {
...
   SDLoc DL(N);
   const auto &Subtarget = DAG.getSubtarget<AArch64Subtarget>();
 
-  if (!VT.isVector())
-    return SDValue();
-
   if (VT.isScalableVector() && !Subtarget.hasSVE2())
     return SDValue();
 
-  if (VT.isFixedLengthVector() &&
```
Comment (sdesmalen-arm) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:14758]: Did you remove this condition on purpose?

**Review by sdesmalen-arm — APPROVED** [review]

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 3]
```diff
@@ -14808,14 +14800,13 @@ static SDValue tryCombineToBSL(SDNode *N, TargetLowering::DAGCombinerInfo &DCI,
...
   unsigned Bits = VT.getScalarSizeInBits();
-  uint64_t BitMask = Bits == 64 ? -1ULL : ((1ULL << Bits) - 1);
   for (int i = 1; i >= 0; --i)
     for (int j = 1; j >= 0; --j) {
       APInt Val1, Val2;
 
       if (ISD::isConstantSplatVector(N0->getOperand(i).getNode(), Val1) &&
           ISD::isConstantSplatVector(N1->getOperand(j).getNode(), Val2) &&
-          (BitMask & ~Val1.getZExtValue()) == Val2.getZExtValue()) {
+          ~Val1.trunc(Bits) == Val2.trunc(Bits)) {
```
Comment (rj-jesus) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:14809]: I guess the issue here and below was that the mask wasn't applied to both sides? Either way, I think the new version looks good.

**Review by rj-jesus — APPROVED** [review]
As far as I can tell this looks good to me, thanks!
