### PR TITLE
[lldb] Removed gdbserver ports map from lldb-server

### LINKED ISSUE #97537: lldb-server's GDB port map (--min/max-gdbserver-port) has a race condition when killing the debugee on a slow remote system
To reproduce, the remote needs to be something relatively slow. In my case QEMU.

Start an lldb-server on the remote in platform mode with some restricted ports:
```
$ ./lldb-server plaform --server --listen 0.0.0.0:54321 --min-gdbserver-port 49140 --max-gdbserver-port 49150
```
Then connect lldb and run a program:
```
$ ./bin/lldb
(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) platform connect connect://127.0.0.1:54321
  Platform: remote-linux
    Triple: aarch64-unknown-linux-gnu
OS Version: 6.10.0 (6.10.0-rc4-g14d7c92f8df9)
  Hostname: e125016
 Connected: yes
WorkingDir: /home/davspi01
    Kernel: #1 SMP PREEMPT Tue Jun 18 15:14:36 BST 2024
(lldb) target create /tmp/test.o
Current executable set to '/tmp/test.o' (aarch64).
(lldb) b main
Breakpoint 1: where = test.o`main at test.c:1:21, address = 0x0000000000400574
(lldb) run
Process 263 launched: '/tmp/test.o' (aarch64)
Process 263 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x0000000000400574 test.o`main at test.c:1:21
-> 1   	int main() { return 0; }
```
At this point lldb-server has started a new process to handle this client's connection and given it a port map that has one open port, that it has used to start a gdb-server process.

From here, if you finish the program then run it again, everything is fine. The gdbserver is torn down and the port is freed, then reused for the new gdbserver.

However, if you run before the program finishes there is a race between the platform killing the gdbserver process and the platform handling the launch gdb server request packet:
```
$ ./bin/lldb
(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) platform connect connect://127.0.0.1:54321
  Platform: remote-linux
    Triple: aarch64-unknown-linux-gnu
OS Version: 6.10.0 (6.10.0-rc4-g14d7c92f8df9)
  Hostname: e125016
 Connected: yes
WorkingDir: /home/davspi01
    Kernel: #1 SMP PREEMPT Tue Jun 18 15:14:36 BST 2024
(lldb) target create /tmp/test.o
Current executable set to '/tmp/test.o' (aarch64).
(lldb) b main
Breakpoint 1: where = test.o`main at test.c:1:21, address = 0x0000000000400574
(lldb) run
Process 263 launched: '/tmp/test.o' (aarch64)
Process 263 stopped
* thread #1, name = 'test.o', stop reason = breakpoint 1.1
    frame #0: 0x0000000000400574 test.o`main at test.c:1:21
-> 1   	int main() { return 0; }
(lldb) run
There is a running process, kill it and restart?: [Y/n] y
Process 263 exited with status = 9 (0x00000009) killed
error: unable to launch a GDB server on 'e125016'
```
We can see that the packets are sent in the right order:
```
lldb             <   5> send packet: $k#6b
lldb             <  19> read packet: $X09;process:115#cc
Process 277 exited with status = 9 (0x00000009) killed
<...>
lldb             <  34> send packet: $qLaunchGDBServer;host:e125016;#12
lldb             <   7> read packet: $E09#ae
error: unable to launch a GDB server on 'e125016'
```
On the server side it uses `kill()` to kill the process and it should then free the port here:
https://github.com/llvm/llvm-project/blob/76c84e702bd9af7db2bb9373ba6de0508f1e57a9/lldb/tools/lldb-server/lldb-platform.cpp#L300

(introduced by https://github.com/llvm/llvm-project/pull/88845, which I think made the feature overall better, but in doing so exposed this issue)

If the remote is slow enough that the kill doesn't actually finish before we get back there, then it won't and it'll try to find a free port, find none, and fail to launch the gdb server. Some ad-hoc logging shows this on the server side:
```
265: port map begins --------------------   <<< 256 is the main process
first: 49140 second: 0
first: 49141 second: 0
first: 49142 second: 0
first: 49143 second: 0
first: 49144 second: 0
first: 49145 second: 0
first: 49146 second: 0
first: 49147 second: 0
first: 49148 second: 0
first: 49149 second: 0
265: port map ends--------------------
266: port map begins -------------------- <<< 266 is created to handle the connection to lldb
first: 49140 second: 0
266: port map ends--------------------   <<< the first gdbserver is launched on the only unallocated port, 49140
266: port map begins --------------------
first: 49140 second: 271
266: port map ends-------------------- <<< looks for a free port, but the 1 port is allocated to pid 271 still
266: No free port found in map!  <<< error returned to lldb
266: FreePortForProcess 271 49140 <<< it finally notices that kill() has happened
```
This does not happen debugging locally on real hardware.

I discovered this running some of the SVE tests again. They run the debugee once to discover the supported vector lengths and then again to run the actual test case. Adding a `sleep(5)` in the test cases between those 2 runs also "fixes" the issue.

The workaround is to not use a port map at all, but often giving full network access to a VM is difficult. So I'd like to find a way to make this work, or at least work around it in the tests most likely to be run this way.

### PR DESCRIPTION
**Pull request by slydiman**
Listen to gdbserver-port, accept the connection and run `lldb-server gdbserver --fd` on all platforms. 
Parameters --min-gdbserver-port and --max-gdbserver-port are deprecated now.

This is the part 2 of #101283.

Fixes #97537.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Thanks for putting so much work into this. I will test this out with my VM setup.

> Parameters --min-gdbserver-port and --max-gdbserver-port are deprecated now.

Are they just consumed but the port number is not used because it can use the first port for everything?

(I do see the logic of leaving the options in at first, so we can tell whether any problems are from the changes in this PR or purely from removing the options)

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 1]
```diff
@@ -601,15 +570,24 @@ int main_platform(int argc, char *argv[]) {
...
+  /*
+  if (acceptor_gdb && gdb_thread.IsJoinable()) {
+    g_listen_gdb = false;
+    static_cast<TCPSocket *>(acceptor_gdb->m_listener_socket_up.get())
+        ->CloseListenSockets();
+    lldb::thread_result_t result;
+    gdb_thread.Join(&result);
+  }
+  */
+
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:590]: This won't work. This is exactly the pattern from that kernel bug we were arguing over. It's just not possible to safely close an fd while another thread may be operating on it.

You need to use an out-of-band mechanism (e.g. a pipe) to notify the thread that it's time to terminate. However, since that will involve some form of multiplexing (e.g. `select(2)`). I would strongly prefer to just multiplex over the two sockets we are accepting. We should be able to use the `MainLoop` class for that -- just register the two sockets with the class, and let it call the right callback when needed. Basically, the code should look similar to [this](https://github.com/llvm/llvm-project/blob/f71b63865140cf3c286baf3a77ba3e467f929504/lldb/source/Host/common/TCPSocket.cpp#L267), except that it will be listening to two unrelated sockets.

File: lldb/unittests/tools/lldb-server/tests/TestClient.h [hunk 2]
```diff
@@ -20,6 +20,10 @@
 #include <optional>
 #include <string>
 
+#ifdef SendMessage
+#undef SendMessage
+#endif
+
```
Comment (labath) [inline lldb/unittests/tools/lldb-server/tests/TestClient.h:26]: I guess that means we're including a windows header somewhere. Any chance to avoid that? Llvm is pretty strict about that. Lldb is not, though I think it's a good practice.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp [hunk 3]
```diff
@@ -666,7 +756,23 @@ ConnectionStatus
...
+#ifdef _WIN32
+  int64_t fd = -1;
+  if (!s.getAsInteger(0, fd)) {
+    // Assume we own fd.
+    std::unique_ptr<TCPSocket> tcp_socket =
+        std::make_unique<TCPSocket>((NativeSocket)fd, true, false);
+    m_io_sp = std::move(tcp_socket);
+    m_uri = s.str();
+    return eConnectionStatusSuccess;
+  }
```
Comment (labath) [inline lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp:768]: I don't exactly have an alternative in mind yet, but I'm not sure this is a good idea. File descriptors are a thing on windows as well (though, IIUC, they're more of like an in-process thing rather than a kernel entity), and we do have code which treats them as such, so I think it could be confusing that this functions considers an "fd" to be a socket handle.

**Review by labath — COMMENTED** [review]
The termination part definitely needs to be done differently, but overall, I think this is a pretty good start.

(PSA: I will be OOO all of next week.)

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp [hunk 4]
```diff
@@ -879,20 +879,12 @@ lldb::thread_result_t GDBRemoteCommunication::ListenThread() {
   return {};
 }
 
-Status GDBRemoteCommunication::StartDebugserverProcess(
-    const char *url, Platform *platform, ProcessLaunchInfo &launch_info,
-    uint16_t *port, const Args *inferior_args, int pass_comm_fd) {
+bool GDBRemoteCommunication::GetDebugserverPath(
+    Platform *platform, FileSpec &debugserver_file_spec) {
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp:883]: I tried to minimize changes here. `bool debugserver_exists` already was here. GetDebugserverPath() is used in GDBRemoteCommunicationServerPlatform.cpp for checking debugserver w/o launching. Invalid FileSpec is not convenient for this purpose.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 1 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp:590]: Oh, Linux... Such pattern works just fine on Windows. I saw MainLoop. But I think it is much safer just exit the app. Terminating the main thread is enough. I will remove this comment in the code and the g_listen_gdb flag.

File: lldb/unittests/tools/lldb-server/tests/TestClient.h (hunk 2 above)
Comment (slydiman) [reply lldb/unittests/tools/lldb-server/tests/TestClient.h:26]: Note TestClient.cpp and LLGSTest.cpp already contain this code. Windows headers are necessary for socket definitions. It is impossible to separate them. This fix is necessary because the order of headers has been changed. Note we can remove the same code in TestClient.cpp and LLGSTest.cpp. I just minimized changes. Should I remove it from TestClient.cpp and LLGSTest.cpp?

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp (hunk 3 above)
Comment (slydiman) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp:768]: Right, file descriptors on Windows are in-process CRT specific things. But we already have this API. I don't see any point in complicating things here.

**Comment by slydiman** [comment]
> Are they just consumed but the port number is not used because it can use the first port for everything?
> 
> (I do see the logic of leaving the options in at first, so we can tell whether any problems are from the changes in this PR or purely from removing the options)

We need only 1 port defined by `--gdbserver-port`. I kept `--min-gdbserver-port` and `--max-gdbserver-port` for backward compatibility. 
```
lldb-server p --server --listen *:1234 --gdbserver-port 1235 --min-gdbserver-port 1236 --max-gdbserver-port 1237
```
1235 is used for gdb
```
lldb-server p --server --listen *:1234 --min-gdbserver-port 1236 --max-gdbserver-port 1237
```
1236 is used for gdb
```
lldb-server p --server --listen *:1234 --max-gdbserver-port 1237 --min-gdbserver-port 1236
```
1237 is used for gdb

File: lldb/unittests/tools/lldb-server/tests/TestClient.h (hunk 2 above)
Comment (slydiman) [reply lldb/unittests/tools/lldb-server/tests/TestClient.h:26]: I will retest it after #104439. Probably we won't need it.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 5]
```diff
@@ -47,111 +48,10 @@ using namespace llvm;
...
-  Pipe m_socket_pipe;
-  NativeSocket m_socket;
-#endif
-  shared_fd_t m_fd;
-};
-
 static int g_debug = 0;
 static int g_verbose = 0;
 static int g_server = 0;
+static volatile bool g_listen_gdb = true;
```
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: yeah, but volatile still isn't the right choice for that. It would have to be an atomic var.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 1 above)
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: <rant>It's not just linux, that kind of pattern is racy on all posix operating systems. It's possible that other OSs will not hang in this situation, but that doesn't mean that usage is safe. Even on windows, that can cause you to call (WSA)accept on a dangling socket descriptor -- since you can never be sure whether the other thread has already called the function, or is it merely about to do that. It's less likely to blow up in your face because windows does not recycle FDs like posix systems do, but I wouldn't recommend that anywhere.</rant>

Exiting the main thread may be convenient, but I definitely wouldn't call it "safe", as that means the other thread may be running, executing random code and memory, while the main thread is shutting everything down and deleting that memory. It may not matter often, as the process is done anyway, but if anyone was observing the exit code, he may be suprised to see a SEGV instead of a clean exit.

Reasoning about a singlethreaded application is much easier than for a multithreaded one. We should already have all of the pieces to do this the right way, so let's just do that.

**Comment by DavidSpickett** [comment]
Only had time to build so far but:
```
/home/davspi01/work/open_source/llvm-project/lldb/tools/lldb-server/lldb-platform.cpp: In function ‘int main_platform(int, char**)’:
/home/davspi01/work/open_source/llvm-project/lldb/tools/lldb-server/lldb-platform.cpp:354:49: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  354 |       if (port_offset < LOW_PORT || port_offset > HIGH_PORT) {
      |                                                 ^
/home/davspi01/work/open_source/llvm-project/lldb/tools/lldb-server/lldb-platform.cpp:372:41: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  372 |       if (portnum < LOW_PORT || portnum > HIGH_PORT) {
      |                                         ^
[2796/2796] Linking CXX executable bin/lldb-server
```
I think this warning was already there, I'm just seeing it now in a clean build. `u` means `unsigned` and `portnum` is `uint16_t`.

File: lldb/unittests/tools/lldb-server/tests/TestClient.h (hunk 2 above)
Comment (labath) [reply lldb/unittests/tools/lldb-server/tests/TestClient.h:26]: If it's just due to header moves that's fine.

It's definitely possible to isolate the windows headers. Lllvm does that by making sure it only includes the system headers in implementation files (of the library wrapping them). It'd be nice to have lldb do the same thing, but we're pretty far off.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp (hunk 3 above)
Comment (labath) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp:768]: I do. I don't think it's a good state if half of our "fd" refer to file descriptors and others to handles. (In reality, it's not half/half, but more like 90/10, and this is the minority case/)

**Comment by slydiman** [comment]
> I think this warning was already there, I'm just seeing it now in a clean build. `u` means `unsigned` and `portnum` is `uint16_t`.

I will revert the original definition `#define HIGH_PORT (49151u)`. Thanks.

File: lldb/docs/man/lldb-server.rst [hunk 6]
```diff
@@ -147,15 +147,8 @@ GDB-SERVER CONNECTIONS
...
- times to allow multiple ports. Has no effect if --min-gdbserver-port
- and --max-gdbserver-port are specified.
-
-.. option:: --min-gdbserver-port <port>
-.. option:: --max-gdbserver-port <port>
-
- Specify the range of ports that can be used for gdb-server connections. Both
- options need to be specified simultaneously. Overrides --gdbserver-port.
+ Define a port to be used for gdb-server connections. This port is used for
+ multiple connections.
```
Comment (DavidSpickett) [inline lldb/docs/man/lldb-server.rst:151]: I don't know much about how ports work, can you explain briefly how that single port knows to route traffic from each client lldb to the right lldb-server gdbserver?

It appears to "just work" but I'm curious.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp (hunk 3 above)
Comment (slydiman) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp:768]: What are you suggesting here? We are trying to reduce usage of `#ifdef _WIN32`. HANDLE(s) are Windows specific. We can refactor it later if necessary. I'm trying to reduce changes.

**Comment by DavidSpickett** [comment]
I did some testing with my usual setup which is x86 Linux to AArch64 Linux running in a simulator.

```
<simulator>
$ ./lldb-server platform --server --listen 0.0.0.0:1234 --gdbserver-port 49140
<host>
$ ./bin/lldb-dotest --platform-name remote-linux --platform-url connect://172.17.0.2:1234 --platform-working-dir /tmp/test_lldb --arch aarch64 -p TestSVE*
```
The SVE tests are the ones that found https://github.com/llvm/llvm-project/issues/97537.

And everything works as expected. I don't normally run remote tests with `ninja check-lldb`, so I just ran the above command in a couple of terminals at the same time and there weren't any problems.

```
\_ ./lldb-server platform --server --listen 0.0.0.0:1234 --gdbserver-port 49140
    \_ lldb-server platform --child-platform-fd 9 --gdbserver-port 49140
    \_ lldb-server platform --child-platform-fd 9 --gdbserver-port 49140
    \_ /home/davspi01/lldb-server gdbserver  --fd=9 --native-regs
    |   \_ sh -c /usr/bin/lsb_release -i
    |       \_ /usr/bin/python3 -Es /usr/bin/lsb_release -i
    \_ /home/davspi01/lldb-server gdbserver  --fd=9 --native-regs
        \_ sh -c /usr/bin/lsb_release -i
            \_ /usr/bin/python3 -Es /usr/bin/lsb_release -i
```
Snapshot of the processes during that, all makes sense to me. Main platform, two connected clients and each one has spawned a gdbserver.

File: lldb/docs/man/lldb-server.rst (hunk 6 above)
Comment (slydiman) [reply lldb/docs/man/lldb-server.rst:151]: Before: 
- `lldb-server platform`
  - got the query `qLaunchGDBServer`
  - request a gdb port from the map (it may be 0)
  - launch `lldb-server gdbserver host:port`
  - if the port was 0, read the actual port back via pipe
  - answer OK and report the actual port and pid
- lldb client connects to gdbserver using host:port (if handshake failed, lldb client kills gdbserver by pid via platform protocol)

After:
- `lldb-server platform`
  - listen to gdbserver-port
  - got the query `qLaunchGDBServer`
  - answer OK and report always known gdbserver-port and ibvalid pid
- lldb client connects to gdbserver using host:port (do nothing if handshake failed)
- `lldb-server platform` got connection and launch `lldb-server gdbserver --fd socket`
  - `lldb-server platform` will transfer the socket info to gdbserver via pipe on Windows (or kill gdbserver if it failed)

**Comment by slydiman** [comment]
> And everything works as expected. I don't normally run remote tests with `ninja check-lldb`, so I just ran the above command in a couple of terminals at the same time and there weren't any problems.

Note we are testing 
- API, Shell, unittests locally on Windows x86_64
- API, Shell, unittests locally on Linux x86_64
- API, Shell test cross Windows x86_64 host + Linux AArch64 target
- API, Shell test cross Linux x86_64 host + Linux AArch64 target

Currently we have 2 tests failed on Windows host/local. But these fails are not related to this patch.

File: lldb/docs/man/lldb-server.rst (hunk 6 above)
Comment (DavidSpickett) [reply lldb/docs/man/lldb-server.rst:151]: Thanks, I understood that bit.

What I was missing was basic socket theory, that on the remote side we can look at the IP address of the sender so IP A to port N can be differentiated from IP B sending to port N. It's been a very long time since I had to think about this, but in hindsight, of course lots of things multiplex this way.

Nothing wrong with the code, if anything it was a bit too magical :) And a good improvement for the way I use lldb in my work.

**Comment by slydiman** [comment]
@labath 
> Basically, the code should look similar to [this](https://github.com/llvm/llvm-project/blob/f71b63865140cf3c286baf3a77ba3e467f929504/lldb/source/Host/common/TCPSocket.cpp#L267), except that it will be listening to two unrelated sockets.

> Reasoning about a singlethreaded application is much easier than for a multithreaded one. We should already have all of the pieces to do this the right way, so let's just do that.

So, the TCPSocket class supports a list of listening native sockets. But Acceptor does not support them. MainLoop is not accessible anywhere.  I'm going to remove the new thread for accepting gdb connections and refactor Acceptor to listen on 2 ports in the same main thread instead.

**Comment by slydiman** [comment]
I have updated the patch.
Note all changes in Socket.* and TCPSocket.cpp will go away after merging #106640.
The class Acceptor uses the MainLoop and contains the own list of listen sockets.
Please review. Thanks.

**Comment by labath** [comment]
What I meant was something like [this](https://github.com/llvm/llvm-project/pull/106955). Basically, keep the socket code inside the socket class, but make it asynchronous. This way you can listen for as many sockets (and other things) as you like. It shouldn't be necessary to do the socket handling stuff externally.

I haven't looked into exactly how this would fit into the Acceptor class in lldb-server, but my preferred solutions would be:
- delete it (or at least significantly slim down it's functionality -- it's a very thin wrapper over the Socket class, and probably only exists due to historic reasons)
- make it callback-based as well

I don't like the idea of making Acceptor responsible for multiple ports for the same reason I did not want to do that for TCPSocket -- it's complicated and inflexible.

**Comment by slydiman** [comment]
I have updated this patch based on #106955 to see how it will look and work.

**Comment by slydiman** [comment]
Refactored after merging #106955.
Acceptor.cpp has been deleted.
Please review. Thanks.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 7]
```diff
@@ -421,97 +417,210 @@ int main_platform(int argc, char *argv[]) {
...
-      // If not running as a server, this process will not accept
-      // connections while a connection is active.
-      acceptor_up.reset();
-
-      // When not running in server mode, use all available ports
-      platform.SetPortMap(std::move(gdbserver_portmap));
+    llvm::Expected<std::vector<MainLoopBase::ReadHandleUP>> gdb_handles =
+        sock_gdb->Accept(*g_main_loop, [&platform, &gdb_inferior_arguments](
+                                           std::unique_ptr<TCPSocket> sock_up) {
+          printf("Gdb connection established.\n");
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:568]: Do we want to print this for every new connection?

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 8]
```diff
@@ -421,97 +417,210 @@ int main_platform(int argc, char *argv[]) {
...
+                Host::Kill(child_pid, SIGTERM);
+                LLDB_LOGF(log, "gdbserver CompleteSending failed: %s",
+                          error.AsCString());
+              }
+            }
+          } else
+            LLDB_LOGF(log, "gdbserver SharedSocket failed: %s",
+                      error.AsCString());
+
+          sock_up.reset();
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:593]: the socket is going to get destroyed anyway.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 9]
```diff
@@ -421,97 +417,210 @@ int main_platform(int argc, char *argv[]) {
...
+    do {
+      g_main_loop->Run();
+    } while (!g_terminate);
+
+    gdb_handles->clear();
+    platform_handles->clear();
+
+    g_main_loop.reset();
+    sock_gdb.reset();
+    sock_platform.reset();
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:610]: This isn't very c++-y. Could this be arranged so that the natural c++ destructor order destroys things in the right order. Perhaps by creating the mainloop inside this block (which means that the reaping callback would need to get it via an argument)?

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 7 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Removed.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 8 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Removed.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 9 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I have added platform_tcp() and platform_named() and placed handles inside a block.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 10]
```diff
@@ -150,12 +153,17 @@ static void client_handle(GDBRemoteCommunicationServerPlatform &platform,
...
-static GDBRemoteCommunicationServerPlatform::PortMap gdbserver_portmap;
-static std::mutex gdbserver_portmap_mutex;
-
 static void spawn_process_reaped(lldb::pid_t pid, int signal, int status) {
-  std::lock_guard<std::mutex> guard(gdbserver_portmap_mutex);
-  gdbserver_portmap.FreePortForProcess(pid);
+  if (g_single_pid != LLDB_INVALID_PROCESS_ID && g_single_pid == pid) {
+    // If not running as a server and the platform connection is closed
+    if (!g_terminate) {
+      g_terminate = true;
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: We need this callback only in case of non-server mode and tcp protocol.
Note this callback is called from the MonitorChildProcessThread. 
See the issue #101475. We must be very careful with this callback and we cannot change any arguments. 
I have removed g_terminate.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 11]
```diff
@@ -421,97 +417,210 @@ int main_platform(int argc, char *argv[]) {
...
+
+    gdb_handles->clear();
+    platform_handles->clear();
+
+    g_main_loop.reset();
+    sock_gdb.reset();
+    sock_platform.reset();
+  } else {
+    Socket *conn_up = nullptr;
+    error = sock_named->Accept(conn_up);
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I think it is out of scope of this patch.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 12]
```diff
@@ -421,97 +417,210 @@ int main_platform(int argc, char *argv[]) {
...
+    if (!gdb_handles) {
+      printf("Failed to accept gdb: %s\n",
+             llvm::toString(gdb_handles.takeError()).c_str());
+      return socket_error;
     }
 
-    platform.SetConnection(std::unique_ptr<Connection>(conn));
+    do {
+      g_main_loop->Run();
+    } while (!g_terminate);
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: g_terminate has been removed.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp]: Updated.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp [hunk 13]
```diff
@@ -667,7 +669,22 @@ ConnectionStatus
...
+  if (error_ptr)
+    *error_ptr = Status::FromErrorStringWithFormat(
+        "invalid file descriptor: \"%s\"", s.str().c_str());
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp]: ConnectionFileDescriptorPosix.cpp is unchanged now.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 14]
```diff
@@ -160,66 +95,58 @@ GDBRemoteCommunicationServerPlatform::~GDBRemoteCommunicationServerPlatform() =
...
   // Spawn a debugserver and try to get the port it listens to.
   ProcessLaunchInfo debugserver_launch_info;
-  if (hostname.empty())
-    hostname = "127.0.0.1";
-
   Log *log = GetLog(LLDBLog::Platform);
-  LLDB_LOGF(log, "Launching debugserver with: %s:%u...", hostname.c_str(),
-            *port);
+  LLDB_LOG(log, "Launching debugserver url='{0}', fd={1}...", url.str(),
+           (int64_t)fd);
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp]: Updated.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp (hunk 3 above)
Comment (slydiman) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp]: ConnectionFileDescriptorPosix.cpp is unchanged now.
I have moved the SharedSocket using to lldb-gdbserver.cpp.
I don't like the idea about SharedSocket::GetSocket() because of ambiguity Socket/TCPSocket/UDPSocket and additional parameters should_close, child_processes_inherit, etc. It may reduce using of NativeSocket, but will not reduce the code in general.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Yes, we need to be very careful, but I don't think this is how being careful looks like. `SetMonitorProcessCallback` takes a std::function, so we can add (or remove) as many arguments as we like.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
Comment (labath) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp:1]: I think this file looks good now. In the interests of moving this forward, and reducing the size of this patch, could you split it into a separate patch?

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Unix sockets accept only one socket. A single blocking accept() is enough. I think a MainLoop is redundant for unix sockets. Now the code in platform_named() is clear and consistent. Adding MainLoop and callbacks just will needlessly complicate the code.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Ok, I see what you meant with https://github.com/llvm/llvm-project/issues/101475 now. That said I don't think this solves anything, cause the same thing could now happen with the mainloop pointer (if it is destroyed just as this function is exiting). The way I'd ideally solve this is by ensuring that the main loop does not terminate (which means the main loop and the platform objects will not be destroyed) until this function is called.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.h [hunk 15]
```diff
@@ -25,90 +25,30 @@ namespace process_gdb_remote {
...
-                           const std::string &socket_name);
+  void SetPendingGdbServer(const std::string &socket_name);
 
 protected:
   const Socket::SocketProtocol m_socket_protocol;
-  const std::string m_socket_scheme;
-  std::recursive_mutex m_spawned_pids_mutex;
-  std::set<lldb::pid_t> m_spawned_pids;
+  static std::mutex g_spawned_pids_mutex;
+  static std::set<lldb::pid_t> g_spawned_pids;
```
Comment (labath) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.h:47]: I guess this is related to #101475, but I think we should figure out a solution that does not require making these static.

File: lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp (hunk 3 above)
Comment (labath) [reply lldb/source/Host/posix/ConnectionFileDescriptorPosix.cpp]: Okay, I think I can live with that.

File: lldb/tools/lldb-server/lldb-gdbserver.cpp [hunk 16]
```diff
@@ -195,18 +195,31 @@ void ConnectToRemote(MainLoop &mainloop,
...
+    }
+    connection_up =
+        std::unique_ptr<Connection>(new ConnectionFileDescriptor(new TCPSocket(
+            sockfd, /*should_close=*/true, /*child_processes_inherit=*/false)));
+#else
     url = llvm::formatv("fd://{0}", connection_fd).str();
 
     // Create the connection.
-#if LLDB_ENABLE_POSIX && !defined _WIN32
+#if LLDB_ENABLE_POSIX
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-gdbserver.cpp:220]: I don't think we actually need this. _WIN32 is basically the opposite of POSIX. AFAICT, https://reviews.llvm.org/D33213 was just being (too) defensive.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I don't think so. The added code should be much smaller compared to the number of lines of code in lldb-platform that it will save. The impact is even bigger when you take into acount that lldb-platform is a huge messy monolith whereas the new function will be self-contained and unit-tested.
You don't have to make the existing Accept function go through the MainLoop like I did with TCP. You can just make an independent implementation if that's easier.

I'll also note that lldb-server currently supports accepting multiple connections over domain sockets (--server mode), whereas your implementation does not. if you added support for that, it would be even more duplicated code.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Note this callback is called from an uncontrollable thread and any pending arguments in the std::function wrapper may be invalid during the process destroying procedure.
I have updated the logic around g_server and removed <atomic> and g_single_pid at all.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: You have an idea of ​​what it should look like. I don't. 
I'm not expert in unix sockets. I have no idea how multiple named sockets may be connected simultaneously. 
I don't see how the following code may be reduced using a MainLoop and callbacks
```
  std::unique_ptr<Socket> sock_named = Socket::Create(protocol, false, error);
  error = sock_named->Listen(name, backlog);
  Socket *conn_up = nullptr;
  error = sock_named->Accept(conn_up);
  GDBRemoteCommunicationServerPlatform platform(protocol, 0);
  platform.SetConnection(std::unique_ptr<Connection>(new ConnectionFileDescriptor(conn_up)));
  client_handle(platform, args);
```
Anyway, this shouldn't be a stopper for this patch.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 17]
```diff
@@ -160,66 +95,56 @@ GDBRemoteCommunicationServerPlatform::~GDBRemoteCommunicationServerPlatform() =
...
-    m_spawned_pids.insert(pid);
-    if (*port > 0)
-      m_port_map.AssociatePortWithProcess(*port, pid);
+  if (error.Success()) {
+    pid = debugserver_launch_info.GetProcessID();
+    if (pid != LLDB_INVALID_PROCESS_ID)
+      AddSpawnedProcess(pid);
+    LLDB_LOGF(log,
+              "GDBRemoteCommunicationServerPlatform::%s() "
+              "debugserver launched successfully as pid %" PRIu64,
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:141]: Exactly. 
A non-error Status mean the process was launched. But don't add LLDB_INVALID_PROCESS_ID to the list. 
We can add assert() here but I don't like it.
```
  if (error.Success()) {
    pid = debugserver_launch_info.GetProcessID();
    if (pid != LLDB_INVALID_PROCESS_ID)
      AddSpawnedProcess(pid);
    LLDB_LOGF(log,
              "GDBRemoteCommunicationServerPlatform::%s() "
              "debugserver launched successfully as pid %" PRIu64,
              __FUNCTION__, pid);
  } else {
    LLDB_LOGF(log,
              "GDBRemoteCommunicationServerPlatform::%s() "
              "debugserver launch failed: %s",
              __FUNCTION__, error.AsCString());
  }
```

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I'm not particularly happy with the design of this callback, but that doesn't mean it can't be used safely. The "uncontrollable" aspect means it is up to you (its user) to ensure the callback does not access any arguments after they are destroyed. It doesn't matter if they're local or global or how they're passed into the callback. The new implementation is better (because it's easier to reason about), but it still accesses the global main loop object, which will get destroyed some time after `main` returns. So, the question here is "is there anything ensuring that does not happen?" and not "is mainloop a global?". If there is (for example, because the main thread waits for the callback to call `RequestTermination()`), then I'm pretty this could be refactored to avoid the global. If there isn't, then this is a problem even though the variable is global.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:141]: Why not? That's exactly what the assert is for. It says "it you say the process was launched, you better be able to give me its PID"

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.h (hunk 15 above)
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.h:47]: There is no a safe way except static. 
Note GDBRemoteCommunicationServerPlatform works in a separated single thread process. I think it is ok.

File: lldb/tools/lldb-server/lldb-gdbserver.cpp (hunk 16 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-gdbserver.cpp:220]: `!defined _WIN32` is redunded here because this block is inside the another #ifdef now:
```
#ifdef _WIN32
...
#else
 // no need to check !defined _WIN32 here
#endif
```

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: There are a lot of discussions around `Detached threads accessing global or static objects` in the internet.
Detached threads are bad and the design of this callback is bad.
But if GDBRemoteCommunicationServerPlatform::g_spawned_pids is static (now) it reduces the chances of a crash to 0.(0)1%.
We have no handle of this thread. So the static global g_main_loop is the safest way and g_main_loop must be destroyed (almost) last. No 100% guarantee. But it is the better solution w/o redesigning the child process monitoring.
Ultimately we can just remove `fixes #101475` in the description because this patch improves the situation but do not fix it 100%.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp:1]: I have created #107388. 
Note I did not include `#include "lldb/Host/Socket.h"` and shared_fd_t using because it requires changes in lldb/unittests/tools/lldb-server/tests/TestClient.*

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 18]
```diff
@@ -160,66 +95,56 @@ GDBRemoteCommunicationServerPlatform::~GDBRemoteCommunicationServerPlatform() =
...
+    const lldb_private::Args &args, lldb::pid_t &pid, std::string &socket_name,
+    shared_fd_t fd) {
+  std::ostringstream url;
+  if (fd == SharedSocket::kInvalidFD) {
+    if (m_socket_protocol == Socket::ProtocolTcp) {
+      // Just check that GDBServer exists. GDBServer must be launched after
+      // accepting the connection.
+      if (!GetDebugserverPath(nullptr))
+        return Status::FromErrorString("unable to locate debugserver");
+      return Status();
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:107]: It is inconvenient. It can be called from 
GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer()
and
lldb-platform.cpp, client_handle().
We can rename it to something like `CheckOrLaunchGDBServer()`.
BTW, Handle_qLaunchGDBServer() does not really launch the process now too in case of TCP protocol.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:140]: Added assert() to AddSpawnedProcess().

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I think I know the problems with detached threads pretty well (remember how I said I found bugs in lldb's dependencies -- [one of them](https://sourceware.org/bugzilla/show_bug.cgi?id=19951) is in glibc's pthread_detach). And I'm not interested in changing the design of the monitoring callback. It's detached and it's going to stay detached for a long time to come.

The thing I'm questioning is whether the code you are running inside the callback has to be detached (because the fact that the outer callback machinery is detached doesn't mean that the callback itself has to be detached).

The problems with detached threads are a runtime property. If a thread *accesses* something after it has been destroyed, you have a bug. I emphasised "access" because the access has to happen. Mere existence of a pointer/reference that would permit that access is not in itself a problem. So code like
```
int main() {
  std::condition_variable cv;
  std::thread([&]{cv.notify_one();}).detach();
  cv.wait();
  return;
}
```
is safe because even though the detached thread holds a reference to the local object (and may continue to hold it after its destroyed), the program ensures that the (only) usage of that reference happens while the object is alive. If I removed `cv.wait()` then we'd have a problem.

Why I'm mentioning this? Because this is exactly the pattern we have (or one that I think we should have) here, just instead of `cv.wait()` we have `mainloop.Run()` and `cv.notify()` is replaced by `mainloop.RequestTermination()`

If we can make sure things work this way, we're safe, or at least the (0.1%) problems are "not our problem". If we can't undetach this code, then we're exacerbating the problem, because even if someone wanted to make the undetach the monitoring callback machinery, he could make that work because the code inside it would be detached.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp]: It will be reduced (to nothing) if it can use the same mainloop code that used by the tcp path. I think it is a showstopper because it makes the makes the patch very ugly. I can implement the mainloop/accept version for unix sockets, but it will only happen next week.

**Comment by slydiman** [comment]
I have separated changes `int connection_fd = -1` -> `shared_fd_t connection_fd = SharedSocket::kInvalidFD` to #107553 (NFC).

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: The child monitor callback is used in 2 places:

* lldb-platform.cpp: In case of non-server mode we need to exit after disconnecting (when the child process handling the platform connection exited). In theory we should be in the middle of MainLoop except the case when an assert happened somewhere. So access g_main_loop is safe here. But the safest way is to use a terminate flag and a dummy connection instead of accesing g_main_loop. We can pass a reference to MainLoop as a callback argument but it changes nothing. A global variable is much clear here.

* The child process handling the platform connection uses the single instance of GDBRemoteCommunicationServerPlatform, which uses a list of PIDs g_spawned_pids. This process will exit after disconnecting and the child process monitor callback is most dangerous point. Any processes may exit at any time. We need the PIDs list only for Handle_qKillSpawnedProcess response. It would be better to try to kill the process anyway and just check somehow that this PID is still alive. I think the best solution here is the static g_spawned_pids. Any other solutions are out the scope of this patch.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: It will reduce the function platform_named() to nothing. But current platform_tcp() and GDBRemoteCommunicationServerPlatform will grow and will become terrible.
Unix sockets do not require ports and accept only 1 connection. GDBRemoteCommunicationServerPlatform has the different logic for TCP and unix sockets. We don't wait for a connection before launching gdbserver to provide fd in case of unix sockets. Using MainLoop for unix sockets will make lldb-platform.cpp and GDBRemoteCommunicationServerPlatform extremely confusing. Currently we don't need a separated child process to handle unix socket connection. Unix sockets are used only locally. The only point in using unix sockets - they are lite. But you want to make the connection process as hard as possible - unnecessary child processes, shared sockets for both lldb-platform and gdbserver, etc. I totally disagree. But if it is the showstopper, I will wait for your implementation of the mainloop/accept version for unix sockets.

**Comment by slydiman** [comment]
@labath
I tried to refactor this patch using #108188. No any profit. I had functions platform_tcp() and platform_named().
Now I can unify only 3 lines:
```
std::unique_ptr<Socket> sock_platform = Socket::Create(protocol, /*child_processes_inherit=*/false, error);
sock_platform->Listen(name, backlog);
...
main_loop->Run();
```
The rest 150 lines cannot be unified.
The code of platform_named() was clear and consistent
```
  std::unique_ptr<Socket> sock_named = Socket::Create(protocol, false, error);
  error = sock_named->Listen(name, backlog);
  Socket *conn_up = nullptr;
  error = sock_named->Accept(conn_up);
  GDBRemoteCommunicationServerPlatform platform(protocol, 0);
  platform.SetConnection(std::unique_ptr<Connection>(new ConnectionFileDescriptor(conn_up)));
  client_handle(platform, args);
```
Now it is really ugly because of a lot `if (protocol == Socket::ProtocolTcp)`, casts to TCPSocket, etc. 
It is necessary to resolve the listen ports for tcp.
We don't need the listen socket for gdb connection in case of ProtocolUnixDomain.
The accept callbacks are very different for unix and tcp sockets.
We used `GDBRemoteCommunicationServerPlatform platform(Socket::ProtocolTcp, gdbserver_port);` in the child process `lldb-server p --child-platform-fd`. If you want do execute such child process for unix socket too, it is necessary to transfer the protocol somehow too. It is an unnecessary complication.
I can commit the version where platform_named() uses `main_loop->Run();` but does not execute the child process `lldb-server p --child-platform-fd`. It will just add 30 lines. 
It is impossible to unify the code of functions platform_tcp() and platform_named().

**Comment by slydiman** [comment]
@labath Let's decide how to finish this patch, please.
I would prefer to commit the new functionality. 
Any cosmetics and refactoring is possible at any time.

**Comment by labath** [comment]
>  If you want to execute such child process for unix socket too, it is necessary to transfer the protocol somehow too.

I do want it. I don't think it's necessary to transfer the type of the socket, as that can be determined by inspecting the socket FD (`getsockopt(SO_DOMAIN/SO_PROTOCOL)`). I'd probably do it by creating a new `Socket::Create` static function which takes the FD, and instantiates the appropriate type based on what this function returns.

**Comment by slydiman** [comment]
> I do want it. I don't think it's necessary to transfer the type of the socket, as that can be determined by inspecting the socket FD (getsockopt(SO_DOMAIN/SO_PROTOCOL)).

Oh, I expected this. We can determine non-tcp by missing or 0 gdb port. But it is impossible to separare ProtocolUnixDomain and ProtocolUnixAbstract. The difference is only the implementation of Socket::GetNameOffset().
getsockopt(SO_DOMAIN/SO_PROTOCOL) will not help.
We can provide `--listen same_host_port ` to the child process additionally to `--child-platform-fd X`  and move the parsing of the listen parameter to the beginning to get the correct protocol.
I will make the second commit with the version where I will mux functions platform_tcp() and platform_named() back together, complicated and hard as possible.

**Comment by slydiman** [comment]
I have updated Socket::Create() with minimal changes. But later I used TCPSocket and DomainSocket constructors directly to keep Socket.cpp untouched.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 19]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+  std::unique_ptr<Socket> sock_platform =
+      Socket::Create(protocol, /*child_processes_inherit=*/false, error);
+  if (error.Fail()) {
+    printf("Failed to create platform socket: %s\n", error.AsCString());
+    return socket_error;
+  }
+  error = sock_platform->Listen(
+      protocol == Socket::ProtocolTcp
+          ? llvm::formatv("{0}:{1}", hostname, platform_port).str()
+          : hostname,
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:470]: Is `hostname` the unix socket path? That's definitely surprising. Can you instead define a single (string) variable called address (or whatever is the name of the argument to `Socket::Listen`, and assign it the appropriate value in the if block on line 415?

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 20]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+  }
+
+  GDBRemoteCommunicationServerPlatform platform(protocol, gdbserver_port);
+  {
+    llvm::Expected<std::vector<MainLoopBase::ReadHandleUP>> platform_handles =
+        sock_platform->Accept(
+            *g_main_loop,
+            [progname, gdbserver_port, inferior_arguments, log_file,
+             log_channels](std::unique_ptr<Socket> sock_up) {
+              // If not running as a server, this process will not accept
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:517]: AIUI, this is here to prevent multiple connections in non-server mode. Correct?

Is there any situation in non-server mode where we need to accept more than one successful connection?

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 21]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+    // Try to match socket name as $host:port - e.g., localhost:5555
+    llvm::Expected<Socket::HostAndPort> host_port =
+        Socket::DecodeHostAndPort(listen_host_port);
+    if (!llvm::errorToBool(host_port.takeError())) {
+      protocol = Socket::ProtocolTcp;
+      hostname = host_port->hostname;
+      platform_port = host_port->port;
+    } else
+      hostname = listen_host_port;
   }
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:438]: Let's make a helper function for this. It could either return a decomposed/parsed socket address or maybe even a constructed socket object.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 22]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+      printf("Failed to accept platform: %s\n",
+             llvm::toString(platform_handles.takeError()).c_str());
+      return socket_error;
     }
 
-    platform.SetConnection(std::unique_ptr<Connection>(conn));
-    client_handle(platform, inferior_arguments);
-  } while (g_server);
+    std::vector<MainLoopBase::ReadHandleUP> gdb_handles;
+    if (protocol == Socket::ProtocolTcp) {
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:543]: Put this into a helper function (`AcceptGdbConnectionsIfNeeded`?). Also move the listening code there.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 20 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp:517]: We must accept only 1 platform connection in non-server mode. But we can accept multiple gdb connections.

Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp:517]: Okay, in that case, I'd suggest that, instead of dropping connections on the floor, we close the listening handles (`platform_handles->clear()`) and also close the listening socket, so that the other side gets an ECONNREFUSED.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 23]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+      socket = new TCPSocket(sockfd, /*should_close=*/true,
+                             /*child_processes_inherit=*/false);
+    else {
+#if LLDB_ENABLE_POSIX
+      socket = new DomainSocket(sockfd, /*should_close=*/true,
+                                /*child_processes_inherit=*/false);
+#else
+      LLDB_LOGF(log,
+                "lldb-platform child: Unix domain sockets are not supported on "
+                "this platform.");
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Probably you will never see that in stderr because it is a child process. But ok. Updated.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 24]
```diff
@@ -393,125 +362,222 @@ int main_platform(int argc, char *argv[]) {
...
+              "--gdbserver-port %u is redundant for non-tcp protocol %s.",
+              gdbserver_port, Socket::FindSchemeByProtocol(protocol));
+      return socket_error;
+    }
+    if (g_server) {
+      fprintf(stderr,
+              "Ambiguous parameters --server --listen %s.\n"
+              "The protocol must be tcp for the server mode.",
+              listen_host_port.c_str());
+      return socket_error;
```
[the remark this answers is not in the document]
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: I don't know how it works. But ok. Removed.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 19 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Done

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 20 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp:575]: In case of unix sockets (no gdb listener) it will cause to immediately exit the main loop, exit the app and kill the child process which handles the platform connection.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 21 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Done

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 22 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: It is hard to combine listening and accepting code in the same helper. gdbserver_port may be updated after Listen() and it is used in the platform callback. I have created 2 helpers ListenGdbConnectionsIfNeeded() and AcceptGdbConnectionsIfNeeded().

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 20 above)
Comment (labath) [reply lldb/tools/lldb-server/lldb-platform.cpp:575]: I think that's actually great, as it allows us to synchronize with the exit of the child process and solve our global/detached thread problem -- after returning from MainLoop::Run, we just wait for a notification that the process has really exited. Something like:
```
std::promise<void> child_exited;
handles = socket.Accept(loop, [&]{
...
launch_info.SetMonitorProcessCallback([&child_exited]{child_exited.set_value();});
Launch(launch_info);
handles.clear();
});
loop.Run();
child_exited.get_future().get();
```

Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Done.

**Comment by slydiman** [comment]
Polite ping.
Let's complite this PR, please.

**Comment by labath** [comment]
I'm currently fighting some fires, so I didn't look at the new version yet, but I think the biggest blocker right now are the global variables in the platform class. I don't like globals, and I don't think they should be necessary to solve the problem at hand. If you can revert those (put them into a separate patch so we can continue the discussion), I think we can wrap this up relatively quickly.

**Comment by slydiman** [comment]
> I think the biggest blocker right now are the global variables in the platform class. I don't like globals, and I don't think they should be necessary to solve the problem at hand. If you can revert those (put them into a separate patch so we can continue the discussion), I think we can wrap this up relatively quickly.

Ok, I will remove globals and let it crash.

**Comment by slydiman** [comment]
> I don't like globals

Is this the only argument? I don't like globals too. But no one suggested better solution w/o huge refactoring of MonitorProcessCallback.

Updated. The child process will crash 50/50 at the end, but no one will see. The problem will remain hidden.

**Comment by labath** [comment]
> > I don't like globals
> 
> Is this the only argument? 

No, it's not. You can find my second reason in the full text of my previous message. The third reason is that I think this is something that should be handled independenly of this (already larger that I'd like) patch.

> I don't like globals too. But no one suggested better solution w/o huge refactoring of MonitorProcessCallback.

You didn't ask for one either. Declaring it's [the only way](https://github.com/llvm/llvm-project/pull/104238#discussion_r1745282649) isn't the most traditional way of soliciting feedback. 

> 
> Updated. The child process will crash 50/50 at the end, but no one will see it. The problem will remain hidden. Removed `fixes #101475` in the description. I can create a separate patch after merging this PR.

:+1: 

I'm going to look at the patch now.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (labath) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:104]: I am still looking for an answer to this one. If it's only the `Handle_qLaunchGDBServer` that needs to *not* launch an lldb-server then I don't see why the check couldn't/shouldn't be performed there.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 25]
```diff
@@ -318,75 +231,67 @@ GDBRemoteCommunicationServerPlatform::Handle_qKillSpawnedProcess(
...
-  {
-    std::lock_guard<std::recursive_mutex> guard(m_spawned_pids_mutex);
-    if (m_spawned_pids.find(pid) == m_spawned_pids.end()) {
-      // not a pid we know about
-      return SendErrorResponse(10);
-    }
+  // verify that we know anything about this pid.
+  if (SpawnedProcessFinished(pid)) {
+    // not a pid we know about
+    return SendErrorResponse(10); // ECHILD
```
Comment (labath) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:237]: Let's get rid of these comments. If we really wanted these to have a meaning, they should be one of the GDB_ESOMETHING constants defined in GDBRemoteCommunication.h.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp [hunk 26]
```diff
@@ -318,75 +231,67 @@ GDBRemoteCommunicationServerPlatform::Handle_qKillSpawnedProcess(
...
+    return SendErrorResponse(11); // EDEADLK
+}
+
+void GDBRemoteCommunicationServerPlatform::AddSpawnedProcess(lldb::pid_t pid) {
+  assert(pid != LLDB_INVALID_PROCESS_ID);
+  std::lock_guard<std::recursive_mutex> guard(m_spawned_pids_mutex);
+  m_spawned_pids.insert(pid);
+}
+
+bool GDBRemoteCommunicationServerPlatform::SpawnedProcessFinished(
```
Comment (labath) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp:253]: I'd suggest inverting this condition and calling this `SpawnedProcessIsRunning` (or sth like that). The reason being that "Finished" implies that process was running at some point, but this function does not distinguish a terminated process from one that was never run.

File: lldb/tools/lldb-server/lldb-platform.cpp [hunk 27]
```diff
@@ -119,20 +175,78 @@ static Status save_socket_id_to_file(const std::string &socket_id,
...
+  if (error.Fail())
+    return error;
+
+  if (gdbserver_port == 0)
+    gdbserver_port = gdb_sock->GetLocalPortNumber();
+
+  return Status();
+}
+
+static Status AcceptGdbConnectionsIfNeeded(
```
Comment (labath) [inline lldb/tools/lldb-server/lldb-platform.cpp:196]: return `Expected<handles>` here.

**Comment by slydiman** [comment]
> I am still looking for an answer to this one. If it's only the Handle_qLaunchGDBServer that needs to not launch an lldb-server then I don't see why the check couldn't/shouldn't be performed there.

I cannot answer in the thread, no idea why. The answer is here
https://github.com/llvm/llvm-project/pull/104238#issuecomment-2368274458

LaunchGDBServer() may be called from the child process at the beginnig if inferior_arguments are present. The behavior depends on the protocol. gdbserver will be launched in case of unix sockets. Otherwise we need to check that gdbserver is exists and wait for the tcp gdb connection. This part cannot be optimized/simplified.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 25 above)
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp]: Done.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp (hunk 26 above)
Comment (slydiman) [reply lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerPlatform.cpp]: Done.

File: lldb/tools/lldb-server/lldb-platform.cpp (hunk 27 above)
Comment (slydiman) [reply lldb/tools/lldb-server/lldb-platform.cpp]: Done.

**Comment by labath** [comment]
> > I am still looking for an answer to this one. If it's only the Handle_qLaunchGDBServer that needs to not launch an lldb-server then I don't see why the check couldn't/shouldn't be performed there.
> 
> I cannot answer in the thread, no idea why. The answer is here [#104238 (comment)](https://github.com/llvm/llvm-project/pull/104238#issuecomment-2368274458)
> 
> LaunchGDBServer() may be called from the child process at the beginnig if inferior_arguments are present. The behavior depends on the protocol. gdbserver will be launched in case of unix sockets. Otherwise we need to check that gdbserver is exists and wait for the tcp gdb connection. This part cannot be optimized/simplified.

Okay, that makes sense. Let's see how this goes.

**Review by labath — APPROVED** [review]

**Comment by slydiman** [comment]
#111033

**Comment by DavidSpickett** [comment]
> ******************** TEST 'lldb-api :: lang/c/shared_lib_stripped_symbols/TestSharedLibStrippedSymbols.py' FAILED ********************

This test is flaky on Arm 32, I'll figure it out.

**Comment by DavidSpickett** [comment]
Hi @slydiman, I am looking at commits that warrant a release note for LLDB 20, and I think your work on lldb-server's port map might fit the bill. If you want to do that yourself you can send a PR adding a bullet point to https://github.com/llvm/llvm-project/blob/main/llvm/docs/ReleaseNotes.md#changes-to-lldb, describing the changes.

Or you can tell me a 1/2 sentence summary of it and I'll meld it into release notes style. I know that it has helped my work because I only have to open 2 ports now (1 platform and 1 gdb-server), but I'm not 100% sure of the detail.

**Comment by slydiman** [comment]
@DavidSpickett 
> Or you can tell me a 1/2 sentence summary of it and I'll meld it into release notes style

lldb-server now listens to a single port for gdbserver connections and provides it to the connection handler processes. This allows only 2 ports to be opened in the firewall. lldb-server now also works on Windows in the server mode.

Thanks

**Comment by DavidSpickett** [comment]
Thanks! - https://github.com/llvm/llvm-project/commit/cfd7e024c6a97b0083f2e25a9d03d7dd516a0452#diff-9a29352a0c8c114f51b142b44cb1d5d6688787df1f78f3785ada73e1355a7379R463
