### PR TITLE
Fix out of line Concept-comparisons of NestedNameSpecifiers

### LINKED ISSUE #65810: clang: concept checking bug in out-of-line definitions of inner class member functions
This code:

```
template<typename Param>
concept TrivialConcept =
  requires(Param param) {
    (void)param;
  };

template <typename T>
struct Base {
    class InnerClass;
};

template <typename T>
class Base<T>::InnerClass {
    template <typename Param>
    requires TrivialConcept<Param> 
    int func(Param param) const;
};

template <typename T>
template <typename Param>
requires TrivialConcept<Param>
int Base<T>::InnerClass::func(Param param) const {
    return 0;
}
```

Works on clang-16 and gcc trunk, fails on clang trunk. I believe it should be allowed per C++20 and above.

Bisecting points to 6db007a0654e as the likely culprit (this got reverted a couple of times previously for similar issues; this one slipped past).

Tagging a few interested people from the diff and from #63782, which points to the same commit:
@alexander-shaposhnikov @erichkeane @shafik

### PR DESCRIPTION
**Pull request by erichkeane**
As reported in GH65810, we don't properly collect ALL of the template parameters in a nested name specifier, and were only doing the 'inner level'.

This patch makes sure we collect from all levels.

Fixes: #65810

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -231,14 +231,18 @@ Response HandleFunctionTemplateDecl(const FunctionTemplateDecl *FTD,
...
     NestedNameSpecifier *NNS = FTD->getTemplatedDecl()->getQualifier();
-    const Type *Ty;
-    const TemplateSpecializationType *TSTy;
-    if (NNS && (Ty = NNS->getAsType()) &&
-        (TSTy = Ty->getAs<TemplateSpecializationType>()))
-      Result.addOuterTemplateArguments(const_cast<FunctionTemplateDecl *>(FTD),
-                                       TSTy->template_arguments(),
-                                       /*Final=*/false);
+
+    while (const Type *Ty = NNS ? NNS->getAsType() : nullptr) {
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:235]: This make sense, I was just looking at the AST: https://godbolt.org/z/P3brjcsMG

and I see that `InnerClass` has:

```console
| |-NestedNameSpecifier TypeSpec 'Base<T>'
```

and I wondering what the prefix is there? Maybe the AST is not telling the whole story?

Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:235]: So that one you're seeing there is for the `InnerClass` on line 13, the `NestedNameSpecifier` is for 'everything else' outside of that declaration.  So in THAT case, the Prefix of that one is nothing, since the `Base<T>`  is the entirety of the thing.

However, that AST doesn't show the `NNS` of `func` on line 22, for some reason we're not dumping that.  In THAT case, the `NNS` is `Base<T>::InnerClass`.  At that point, the `InnerClass` doesn't have template arguments (since it isn't a template!), but its `Prefix` is just the `Base<T>`, which has them (which is why/how this loop works).

**Comment by erichkeane** [comment]
Huh, blarg, build-bot found an issue with my patch, curiously in the same file I was editing!  I'll look into it.  I at least reproduce it, which is nice...

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (shafik) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:240]: It does not look like there is a simple way of getting like w/ `CXXRecordDecl` so some work would be involved.

**Comment by erichkeane** [comment]
So the latest patch doesn't FIX it, it has a problem with: 

``` 
template<typename T> concept Concept = true;

template<int>
struct S { 
struct Inner0 {
struct Inner1 {
template<Concept C>
static constexpr int method();
};
};
};

template<>
template<Concept C>
constexpr int S<1>::Inner0::Inner1::method() { return 0;}
```

The problem/special case here is the `template<>`, which causes there to be no level of 'template parameters' when filling in the Depths of the method.  HOWEVER, our `NestedNameSpecifier` list ends up finding the `1` there (for obvious reasons), so the replacement is wrong.

I don't have a feeling of how to get those, I thought the `NNS` was a good analog, but it is clearly not.  I suspect this might be the source of other similar/awkward issues elsewhere.

At the moment, I'm done with this for at least the night, so if someone else wants to take a look, they are encouraged to share their' findings.

File: clang/lib/Sema/SemaTemplateInstantiate.cpp (hunk 1 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:240]: I don't understand what you mean?  `TagDecl` (IIRC?) has a `getQualifier()` to get the appropriate `NestedNameSpecifier`.  I believe our NNS tree is correct the way I've implemented it above, with the exception of the issue I posted about a moment ago.

Comment (shafik) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:240]: Yeah, I just realized I was looking at the code a moment ago `FTD->getTemplatedDecl()->getQualifier()`

**Comment by erichkeane** [comment]
Alright, I think I got it this time, we'll see how the buildbots treat it, but it passes locally for me.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -218,6 +218,9 @@ Bug Fixes in This Version
   (`#65156 <https://github.com/llvm/llvm-project/issues/65156>`_`)
 - Clang no longer considers the loss of ``__unaligned`` qualifier from objects as
   an invalid conversion during method function overload resolution.
+- Clang now properly handles out of line template specializations when there is
+  a non-template inner-class between the function and the class template
+  (`#65810 <https://github.com/llvm/llvm-project/issues/65810>`_).
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:223]:
```suggestion
  a non-template inner-class between the function and the class template.
  (`#65810 <https://github.com/llvm/llvm-project/issues/65810>`_)
```

For consistency (Yes, it's weird). Can you also move that to the "Bug Fixes to C++ Support" section?

**Review by cor3ntin — APPROVED** [review]
You obviously have a better grasp of that part of the code than I do, but the patch looks sensible to me. Thanks!

**Comment by rupprecht** [comment]
Downstream, this is causing a funny build error in c++20 mode:
```
__chrono/duration.h:404:12: error: missing '#include <__compare/three_way_comparable.h>'; default argument of 'three_way_comparable' must be defined before it is used
  404 |   requires three_way_comparable<common_type_t<_Rep1, _Rep2>>
      |            ^
__chrono/duration.h:406:16: note: while calculating associated constraint of template '' here
  406 | constexpr auto operator<=>(const duration<_Rep1, _Period1>& __lhs,
      |                ^
__compare/three_way_comparable.h:34:34: note: default argument declared here is not reachable
   34 | template<class _Tp, class _Cat = partial_ordering>
      |                                  ^
```
It doesn't seem to fail on the public libcxx buildbots, so I'm not sure what's different about our setup that triggers this failure. (cc @ilya-biryukov)

**Comment by ilya-biryukov** [comment]
I couldn't reproduce the error with module-enabled builds of libc++ either, but internally we are building the libc++ module from a generated module map file (and different) rather than the one distributed with libc++.

It seems that Clang has an actual bug with C++20 modules exposing the same problem: #66255. It seems that it's been there for a long time. I believe the patch somehow exposes it. @erichkeane maybe this looks familiar?

**Comment by erichkeane** [comment]
This doesn't, I was really hoping it did for you :)  This is a really strange one, it almost seems like it doesnt' realize it is IN the header or something?
