### PR TITLE
[HLSL][Sema] Fix Struct Size Calculation containing 16/32 bit scalars

### LINKED ISSUE #119641: [HLSL] `packoffset` validation does not handle 16-bit or 64-bit types well
Packoffset layout validation assumes all struct fields are aligned to 4 bytes. That is not true for fields with 16-bit types which are aligned to 2 bytes.

For example this is valid on DXC while Clang reports `error: packoffset overlap between 'f', 's'`:
https://godbolt.org/z/5eqTerhvY

```
struct S {
  half a;
  half b;
  half c;
  half d;
  half e;
  half f;
  half g;
  half h;
};

cbuffer CB0 {
  S s : packoffset(c0.x);
  float f : packoffset(c1.x);
}
```

DXC layout:
```
; cbuffer CB0
; {
;
;   struct CB0
;   {
;
;       struct struct.S
;       {
;
;           half a;                                   ; Offset:    0
;           half b;                                   ; Offset:    2
;           half c;                                   ; Offset:    4
;           half d;                                   ; Offset:    6
;           half e;                                   ; Offset:    8
;           half f;                                   ; Offset:   10
;           half g;                                   ; Offset:   12
;           half h;                                   ; Offset:   14
;       
;       } s;                                          ; Offset:    0
;
;       float f;                                      ; Offset:   16
;   
;   } CB0;                                            ; Offset:    0 Size:    20
;
; }
```

Another case with 64-bit types where DXC and Clang differs:
```
struct S {
  float a;
  double b;
  float c;
};

cbuffer CB0 {
  S s : packoffset(c0.x);
  float f : packoffset(c1.x);
}
```
https://godbolt.org/z/51E19bThY
DXC correctly reports `error: packoffset overlap between 'f', 's'` while Clang accepts it.

### PR DESCRIPTION
**Pull request by V-FEXrt**
Fixes #119641

Update SemaHLSL to correctly calculate the alignment barrier for scalars that are not 4 bytes wide

### CODE REVIEW

File: clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -172,6 +172,27 @@ Decl *SemaHLSL::ActOnStartBuffer(Scope *BufferScope, bool CBuffer,
   return Result;
 }
 
+static unsigned calculateLegacyCbufferFieldAlign(const ASTContext &Context,
+                                                 QualType T) {
+  // Aggregate types are always aligned to new buffer rows
+  if (T->isAggregateType())
+    return 16;
+
+  assert(Context.getTypeSize(T) <= 64 &&
```
Comment (tex3d) [inline clang/lib/Sema/SemaHLSL.cpp:181]: After determining this is not an aggregate, we still need to get the scalar element before proceeding if this is a vector, right?

File: clang/lib/Sema/SemaHLSL.cpp [hunk 2]
```diff
@@ -172,6 +172,27 @@ Decl *SemaHLSL::ActOnStartBuffer(Scope *BufferScope, bool CBuffer,
...
+         "Scalar bit widths larger than 64 not supported");
+
+  // 64 bit types such as double and uint64_t align to 8 bytes
+  if (Context.getTypeSize(T) == 64)
+    return 8;
+
+  // Half types align to 2 bytes only if native half is available
+  if (T->isHalfType() && Context.getLangOpts().NativeHalfType)
```
Comment (tex3d) [inline clang/lib/Sema/SemaHLSL.cpp:189]: The `half` type should be a native 32-bit floating point type, just like the `float` type, when `NativeHalfType` is false.  If that's not already the case, that's future work I suppose.

In any case, this means the alignment should be based on the element size, so I'm not sure why any conditionals are needed here, until we try to support min-precision types that is.

**Review by tex3d — COMMENTED** [review]
What happens for vector fields?

File: clang/lib/Sema/SemaHLSL.cpp (hunk 1 above)
Comment (V-FEXrt) [reply clang/lib/Sema/SemaHLSL.cpp:181]: Ah it seems I have incorrectly assumed that vector is considered an aggregate, I need to go handle that case

File: clang/lib/Sema/SemaHLSL.cpp (hunk 2 above)
Comment (V-FEXrt) [reply clang/lib/Sema/SemaHLSL.cpp:189]: True, I can probably make this function a lot simpler by just looking at the bitwidth.  Are there any types where the bitwidth is 32 but the alignment is not 4 bytes? 

I think I read somewhere that "everything is 4 byte align except these X exceptions" which is a weird way to write it unless some non-32 bitwide type is also 4 byte aligned. Otherwise its clearer to say "everything is aligned to its bytewidth except these X exceptions"

File: clang/lib/Sema/SemaHLSL.cpp (hunk 1 above)
Comment (V-FEXrt) [reply clang/lib/Sema/SemaHLSL.cpp:181]: I suppose even if that assumption is/where true it would still do the wrong layout

File: clang/test/CodeGenHLSL/cbuffer_align.hlsl [hunk 3]
```diff
@@ -0,0 +1,60 @@
+// RUN: %clang_cc1 -std=hlsl2021 -finclude-default-header -x hlsl -triple \
+// RUN:   dxil-pc-shadermodel6.3-library %s -fnative-half-type \
+// RUN:   -emit-llvm -disable-llvm-passes -o - | FileCheck %s --check-prefix=CHECK-HALF
+
+// RUN: %clang_cc1 -std=hlsl2021 -finclude-default-header -x hlsl -triple \
+// RUN:   dxil-pc-shadermodel6.3-library %s \
+// RUN:   -emit-llvm -disable-llvm-passes -o - | FileCheck %s --check-prefix=CHECK-FLOAT
+
+
```
[the remark this answers is not in the document]
Comment (V-FEXrt) [reply clang/test/CodeGenHLSL/cbuffer_align.hlsl:26]: Pushed what I could get done before leaving for a flight. Test structure has been updated but I need to add more test cases

**Comment by V-FEXrt** [comment]
@tex3d @hekota Okay PTAL when you have a moment!

**Review by hekota — APPROVED** [review]
LGTM!

**Review by tex3d — APPROVED** [review]
Looks good!

File: clang/lib/Sema/SemaHLSL.cpp [hunk 4]
```diff
@@ -172,6 +172,23 @@ Decl *SemaHLSL::ActOnStartBuffer(Scope *BufferScope, bool CBuffer,
...
 
+static unsigned calculateLegacyCbufferFieldAlign(const ASTContext &Context,
+                                                 QualType T) {
+  // Arrays and Structs are always aligned to new buffer rows
+  if (T->isArrayType() || T->isStructureType())
+    return 16;
+
+  // Vectors are aligned to the type they contain
+  if (const VectorType *VT = T->getAs<VectorType>())
+    return calculateLegacyCbufferFieldAlign(Context, VT->getElementType());
```
[the remark this answers is not in the document]
Comment (tex3d) [reply clang/lib/Sema/SemaHLSL.cpp:183]: This test would have had no difference with the change you made.  It would have looked the same as two 64-bit values, with the same locations.  I think you'll need something like this:

```hlsl
struct S6 {
  float a;
  float2 b;
};

cbuffer CB6Pass {
  S6 s6p : packoffset(c0.x);
  float f6p : packoffset(c0.w);
}
```

[the remark this answers is not in the document]
Comment (V-FEXrt) [reply clang/lib/Sema/SemaHLSL.cpp:183]: Right, I see! Thanks!
