### PR TITLE
[libc] Fix warnings emitted by GCC

### LINKED ISSUE #98709: [libc] aarch64 gcc warnings
- [ ] return types
 ```
       [811/5026] Building CXX object libc/test/src/...test.__unit__.__build__.dir/fpbits_test.cpp.o
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp: In function ‘constexpr auto make(Sign, FP) [with T = __llvm_libc_19_0_0_git::fputil::internal::FPRep<__llvm_libc_19_0_0_git::fputil::FPType::IEEE754_Binary16>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
  241 | }
      | ^
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp: In function ‘constexpr auto make(Sign, FP) [with T = __llvm_libc_19_0_0_git::fputil::internal::FPRep<__llvm_libc_19_0_0_git::fputil::FPType::IEEE754_Binary32>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp: In function ‘constexpr auto make(Sign, FP) [with T = __llvm_libc_19_0_0_git::fputil::internal::FPRep<__llvm_libc_19_0_0_git::fputil::FPType::IEEE754_Binary64>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp: In function ‘constexpr auto make(Sign, FP) [with T = __llvm_libc_19_0_0_git::fputil::internal::FPRep<__llvm_libc_19_0_0_git::fputil::FPType::IEEE754_Binary128>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp: In function ‘constexpr auto make(Sign, FP) [with T = __llvm_libc_19_0_0_git::fputil::internal::FPRep<__llvm_libc_19_0_0_git::fputil::FPType::X86_Binary80>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/FPUtil/fpbits_test.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
[839/5026] Building CXX object libc/test/src/...est.__unit__.__build__.dir/big_int_test.cpp.o
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In member function ‘virtual void __llvm_libc_19_0_0_git::LlvmLibcUIntClassTest_BitCastToFromNativeFloat16::Run()’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:267:31: warning: converting to ‘float16’ {aka ‘_Float16’} from ‘double’ with greater conversion rank
  267 |   const float16 array[] = {0, 0.1, 1};
      |                               ^~~
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<64, false, long unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
   35 | }
      | ^
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<64, true, long unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<128, false, __int128 unsigned>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<128, true, __int128 unsigned>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<16, false, short unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<16, true, short unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<64, false, short unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp: In function ‘auto __llvm_libc_19_0_0_git::create(Value) [with T = BigInt<64, true, short unsigned int>]’:
/home/schrodinger/development/llvm-project/libc/test/src/__support/big_int_test.cpp:35:1: warning: control reaches end of non-void function [-Wreturn-type]
[854/5026] Building CXX object libc/test/src/..._unit__.__build__.dir/roundevenf16_test.cpp.o^C
ninja: build stopped: interrupted by user.
```
- [ ] conversion rank
```
/home/schrodinger/development/llvm-project/libc/test/src/math/smoke/FrexpTest.h:30:42: warning: converting to ‘_Float16’ from ‘double’ with greater conversion rank
   30 |     EXPECT_FP_EQ_ALL_ROUNDING(-0.0, func(-0.0, &exponent));
      |                                          ^~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/LibcTest.h:406:7: note: in definition of macro ‘LIBC_TEST_SCAFFOLDING_’
  406 |   if (TEST)                                                                    \
      |       ^~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/LibcTest.h:492:3: note: in expansion of macro ‘LIBC_TEST_MATCH_’
  492 |   LIBC_TEST_MATCH_(MATCHER, MATCH, #MATCHER, #MATCH, )
      |   ^~~~~~~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/FPMatcher.h:122:3: note: in expansion of macro ‘EXPECT_THAT’
  122 |   EXPECT_THAT(actual, LIBC_NAMESPACE::testing::getMatcher<                     \
      |   ^~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/FPMatcher.h:207:7: note: in expansion of macro ‘EXPECT_FP_EQ’
  207 |       EXPECT_FP_EQ((expected), (actual));                                      \
      |       ^~~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/src/math/smoke/FrexpTest.h:30:5: note: in expansion of macro ‘EXPECT_FP_EQ_ALL_ROUNDING’
   30 |     EXPECT_FP_EQ_ALL_ROUNDING(-0.0, func(-0.0, &exponent));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/src/math/smoke/FrexpTest.h:30:42: warning: converting to ‘_Float16’ from ‘double’ with greater conversion rank
   30 |     EXPECT_FP_EQ_ALL_ROUNDING(-0.0, func(-0.0, &exponent));
      |                                          ^~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/LibcTest.h:406:7: note: in definition of macro ‘LIBC_TEST_SCAFFOLDING_’
  406 |   if (TEST)                                                                    \
      |       ^~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/LibcTest.h:492:3: note: in expansion of macro ‘LIBC_TEST_MATCH_’
  492 |   LIBC_TEST_MATCH_(MATCHER, MATCH, #MATCHER, #MATCH, )
      |   ^~~~~~~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/FPMatcher.h:122:3: note: in expansion of macro ‘EXPECT_THAT’
  122 |   EXPECT_THAT(actual, LIBC_NAMESPACE::testing::getMatcher<                     \
      |   ^~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/UnitTest/FPMatcher.h:211:7: note: in expansion of macro ‘EXPECT_FP_EQ’
  211 |       EXPECT_FP_EQ((expected), (actual));                                      \
      |       ^~~~~~~~~~~~
/home/schrodinger/development/llvm-project/libc/test/src/math/smoke/FrexpTest.h:30:5: note: in expansion of macro ‘EXPECT_FP_EQ_ALL_ROUNDING’
   30 |     EXPECT_FP_EQ_ALL_ROUNDING(-0.0, func(-0.0, &exponent));
```
- [ ] `sprintf` buffer and restrict
```
1890/4107] Building CXX object libc/test/src...est.__unit__.__build__.dir/sprintf_test.cpp.o
/home/schrodinger/development/llvm-project/libc/test/src/stdio/sprintf_test.cpp: In member function ‘virtual void LlvmLibcSPrintfTest_PointerConv::Run()’:
/home/schrodinger/development/llvm-project/libc/test/src/stdio/sprintf_test.cpp:633:37: warning: passing argument 1 to ‘restrict’-qualified parameter aliases with argument 3 [-Wrestrict]
  633 |   written = LIBC_NAMESPACE::sprintf(buff, "%p", buff);
      |                                     ^~~~        ~~~~
/home/schrodinger/development/llvm-project/libc/test/src/stdio/sprintf_test.cpp: In member function ‘virtual void LlvmLibcSPrintfTest_FloatDecimalLongDoubleConv::Run()’:
/home/schrodinger/development/llvm-project/libc/test/src/stdio/sprintf_test.cpp:1690:8: warning: unused variable ‘big_buff’ [-Wunused-variable]
 1690 |   char big_buff[10000]; // Used for long doubles and other extremely wide
```

### PR DESCRIPTION
**Pull request by overmighty**
Fixes #98709.

### CODE REVIEW

**Comment by overmighty** [comment]
Remaining warnings when compiling with GCC 14.1.1 on x86-64:

```
In file included from /home/overmighty/projects/llvm-project/libc/test/UnitTest/Test.h:37,
                 from /home/overmighty/projects/llvm-project/libc/test/src/__support/CPP/type_traits_test.cpp:11:
/home/overmighty/projects/llvm-project/libc/test/src/__support/CPP/type_traits_test.cpp: In member function ‘virtual void __llvm_libc_19_0_0_git::cpp::LlvmLibcTypeTraitsTest_aligned_storage::Run()’:
/home/overmighty/projects/llvm-project/libc/test/src/__support/CPP/type_traits_test.cpp:122:13: warning: ISO C++ does not allow ‘alignof’ with a non-type [-Wpedantic]
  122 |   EXPECT_EQ(alignof(buf), alignof(S));
      |             ^~~~~~~
/home/overmighty/projects/llvm-project/libc/test/UnitTest/LibcTest.h:406:7: note: in definition of macro ‘LIBC_TEST_SCAFFOLDING_’
  406 |   if (TEST)                                                                    \
      |       ^~~~
/home/overmighty/projects/llvm-project/libc/test/UnitTest/LibcTest.h:420:29: note: in expansion of macro ‘LIBC_TEST_BINOP_’
  420 | #define EXPECT_EQ(LHS, RHS) LIBC_TEST_BINOP_(EQ, LHS, RHS, )
      |                             ^~~~~~~~~~~~~~~~
/home/overmighty/projects/llvm-project/libc/test/src/__support/CPP/type_traits_test.cpp:122:3: note: in expansion of macro ‘EXPECT_EQ’
  122 |   EXPECT_EQ(alignof(buf), alignof(S));
      |   ^~~~~~~~~
```

```
/home/overmighty/projects/llvm-project/libc/test/src/string/memory_utils/op_tests.cpp:198:26: warning: ignoring attributes on template argument ‘__m128i’ [-Wignored-attributes]
  198 |     generic::Bcmp<__m128i>,
      |                          ^
/home/overmighty/projects/llvm-project/libc/test/src/string/memory_utils/op_tests.cpp:201:26: warning: ignoring attributes on template argument ‘__m256i’ [-Wignored-attributes]
  201 |     generic::Bcmp<__m256i>,
      |                          ^
/home/overmighty/projects/llvm-project/libc/test/src/string/memory_utils/op_tests.cpp:281:28: warning: ignoring attributes on template argument ‘__m128i’ [-Wignored-attributes]
  281 |     generic::Memcmp<__m128i>, //
      |                            ^
/home/overmighty/projects/llvm-project/libc/test/src/string/memory_utils/op_tests.cpp:284:28: warning: ignoring attributes on template argument ‘__m256i’ [-Wignored-attributes]
  284 |     generic::Memcmp<__m256i>, //
      |                            ^
```

The attributes ignored seem to be `__aligned__(16)` and `__aligned__(32)`.

Notes without warnings:

```
In file included from /home/overmighty/projects/llvm-project/libc/src/stdio/printf_core/printf_main.cpp:15:
/home/overmighty/projects/llvm-project/libc/src/stdio/printf_core/parser.h: In instantiation of ‘__llvm_libc_19_0_0_git::cpp::optional<T> __llvm_libc_19_0_0_git::printf_core::Parser<ArgProvider>::get_arg_value(size_t) [with T = long double; ArgProvider = __llvm_libc_19_0_0_git::internal::ArgList; size_t = long unsigned int]’:
/home/overmighty/projects/llvm-project/libc/src/stdio/printf_core/parser.h:236:11:   required from ‘__llvm_libc_19_0_0_git::printf_core::FormatSection __llvm_libc_19_0_0_git::printf_core::Parser<ArgProvider>::get_next_section() [with ArgProvider = __llvm_libc_19_0_0_git::internal::ArgList]’
   52 |     auto temp = get_arg_value<arg_type>(index);                                \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/overmighty/projects/llvm-project/libc/src/stdio/printf_core/printf_main.cpp:27:59:   required from here
   27 |   for (FormatSection cur_section = parser.get_next_section();
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~^~
/home/overmighty/projects/llvm-project/libc/src/stdio/printf_core/parser.h:415:51: note: the ABI of passing union with ‘long double’ has changed in GCC 4.4
  415 |   template <class T> LIBC_INLINE cpp::optional<T> get_arg_value(size_t index) {
      |                                                   ^~~~~~~~~~~~~
```

File: libc/test/src/__support/big_int_test.cpp [hunk 1]
```diff
@@ -264,7 +265,11 @@ TEST(LlvmLibcUIntClassTest, BitCastToFromNativeFloat128) {
 TEST(LlvmLibcUIntClassTest, BitCastToFromNativeFloat16) {
   static_assert(cpp::is_trivially_copyable<LL_UInt16>::value);
   static_assert(sizeof(LL_UInt16) == sizeof(float16));
-  const float16 array[] = {0, 0.1, 1};
+  const float16 array[] = {
+      static_cast<float16>(0.0),
+      static_cast<float16>(0.1),
+      static_cast<float16>(1.0),
+  };
```
Comment (overmighty) [inline libc/test/src/__support/big_int_test.cpp:272]: Using `static_cast<float16>` because using the `f16` suffix on the literals would cause this warning instead:

```
warning: ‘f16’ or ‘F16’ suffix on floating constant only available with ‘-std=c++2b’ or ‘-std=gnu++2b’ [-Wpedantic]
```

**Review by SchrodingerZhu — APPROVED** [review]

**Review by SchrodingerZhu — APPROVED** [review]
LGTM
