### PR TITLE
[flang][RISCV] Add target-abi ModuleFlag.

### LINKED ISSUE #115679: [flang]When flang-new compiles for the RISC-V platform, the object files have an incorrect ABI.
I am cross-compiling the **SPEC CPU2006** benchmarks using the **LLVM 19.1.0** compiler on an Intel machine. The C/C++ examples can be successfully built into executable files using runspec and run successfully on the** RISC-V** platform. However, for Fortran examples like **410.bwaves**, building with flang-new fails, and the error is:

ld.lld: error: bwaves.lto.o: cannot link object files with different floating-point ABI from ~/gnu-riscv64-20241106/sysroot/usr/lib/crt1.o.

PS. config info 
**FOPTIMIZE **= -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static **-flto** -ffast-math 
**EXTRA_LDFLAGS **= -fuse-ld==ld.lld -L${gnu-riscv64}/lib/

Through debugging, I found that the ABI of bwaves.lto.o is rv64i2p1, while the ABI of the library file crt1.o is rv64i2p1_m2p0_a2p1_f2p2_d2p2_c2p0_zicsr2p0_zmmul1p0. Clearly, bwaves.lto.o is generated incorrectly. Could you please advise me on how to resolve this issue? Thank you very much!

The complete run script is：
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot  -c -o block_solver.o    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math       -DSPEC_CPU_LP64        -DSPEC_LP64   block_solver.f
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot  -c -o flow_lam.o    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math       -DSPEC_CPU_LP64        -DSPEC_LP64   flow_lam.f
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot  -c -o flux_lam.o    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math       -DSPEC_CPU_LP64        -DSPEC_LP64   flux_lam.f
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot  -c -o jacobian_lam.o    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math       -DSPEC_CPU_LP64        -DSPEC_LP64   jacobian_lam.f
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot  -c -o shell_lam.o    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math       -DSPEC_CPU_LP64        -DSPEC_LP64  shell_lam.f
$ flang-new --target=riscv64-unknown-linux-gnu --gcc-toolchain={RISCV} --sysroot={RISCV}/sysroot    -march=rv64gcv_zba_zbb_zbc_zbs -O3 -static -flto -ffast-math  -DSPEC_CPU_LP64     -fuse-ld=ld.lld -L{RISCV}/lib/    block_solver.o flow_lam.o flux_lam.o jacobian_lam.o shell_lam.o    -o bwaves

### PR DESCRIPTION
**Pull request by topperc**
This is needed to generate proper ABI flags in the ELF header for LTO builds. If these flags aren't set correctly, we can't link with objects that were built with the correct flags.

For non-LTO builds the mcpu/mattr in the TargetMachine will cause the backend to infer an ABI. For LTO builds the mcpu/mattr aren't set.

I've only added lp64, lp64f, and lp64d ABIs. ilp32* requires riscv32 which is not yet supported in flang. lp64e requires a different DataLayout string and would need additional plumbing.

Fixes #115679

### CODE REVIEW

File: flang/lib/Frontend/CompilerInvocation.cpp [hunk 1]
```diff
@@ -464,6 +464,7 @@ static void parseTargetArgs(TargetOptions &opts, llvm::opt::ArgList &args) {
 
   if (const llvm::opt::Arg *a =
           args.getLastArg(clang::driver::options::OPT_mabi_EQ)) {
+    opts.abi = a->getValue();
     llvm::StringRef V = a->getValue();
     if (V == "vec-extabi") {
```
Comment (jrtc27) [inline flang/lib/Frontend/CompilerInvocation.cpp:469]: Existing bug but why are these not checking the target is powerpc...

**Review by jeanPerier — APPROVED** [review]
I do not know much the target-abi LLVM module flag, but this looks reasonable.

File: flang/lib/Frontend/CompilerInvocation.cpp (hunk 1 above)
Comment (kkwli) [reply flang/lib/Frontend/CompilerInvocation.cpp:469]: Yes, it should check the target here. I will fix it.

**Comment by rofirrim** [comment]
LGTM. Thanks @topperc !

**Review by tarunprabhu — APPROVED** [review]
Looks reasonable. Thanks.

File: flang/lib/Frontend/CompilerInvocation.cpp (hunk 1 above)
Comment (kkwli) [reply flang/lib/Frontend/CompilerInvocation.cpp:469]: @jrtc27 I look at it further. The guard is not necessary. In `AddPPCTargetArgs`, the option is added only if it is PPC and `isOSAIX()` is true. So if it is not PPC, `args` in `parseTargetArgs` will not contain `-mabi=vec-extabi`.
