### PR TITLE
[clang][bytecode] Handle negative array sizes in constexpr `new` instead of asserting

### LINKED ISSUE #152904: [clang][bytecode] Assertion `NumElements.isPositive()' failed.
Reproducer:
https://godbolt.org/z/8j5f1To58
```cpp
constexpr void f() {
  int a = -1;
  int *b = new int[a];
}
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/AST/ByteCode/Interp.h:3461: bool clang::interp::AllocN(clang::interp::InterpState&, clang::interp::CodePtr, clang::interp::PrimType, const clang::Expr*, bool) [with clang::interp::PrimType Name = clang::interp::PT_Sint32; SizeT = clang::interp::Integral<32, true>]: Assertion `NumElements.isPositive()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -fexperimental-new-constant-interpreter <source>
1.	<eof> parser at end of file
2.	<source>:1:20: parsing function body 'f'
 #0 0x000000000400b2d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x400b2d8)
 #1 0x0000000004008704 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4008704)
 #2 0x0000000003f4d048 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000745123c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000745123c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000745123c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000745123c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000745123c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000745123c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000007af5f06 bool clang::interp::AllocN<(clang::interp::PrimType)4, clang::interp::Integral<32u, true>>(clang::interp::InterpState&, clang::interp::CodePtr, clang::interp::PrimType, clang::Expr const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7af5f06)
#10 0x0000000007b6d3b1 clang::interp::Interpret(clang::interp::InterpState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7b6d3b1)
#11 0x000000000798e227 clang::interp::Context::isPotentialConstantExpr(clang::interp::State&, clang::FunctionDecl const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x798e227)
#12 0x000000000792e6a2 clang::Expr::isPotentialConstantExpr(clang::FunctionDecl const*, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x792e6a2)
#13 0x0000000006af9366 clang::Sema::CheckConstexprFunctionDefinition(clang::FunctionDecl const*, clang::Sema::CheckConstexprKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6af9366)
#14 0x0000000006a80953 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a80953)
#15 0x00000000067c65ef clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67c65ef)
#16 0x00000000066bd483 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66bd483)
#17 0x00000000066f33ad clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66f33ad)
#18 0x00000000066b07ee clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b07ee)
#19 0x00000000066b0f8f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b0f8f)
#20 0x00000000066b8763 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b8763)
#21 0x00000000066b9675 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b9675)
#22 0x00000000066b9b30 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b9b30)
#23 0x00000000066ab843 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66ab843)
#24 0x00000000049b0d28 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49b0d28)
#25 0x0000000004ca5115 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ca5115)
#26 0x0000000004c2144e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c2144e)
#27 0x0000000004d96861 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4d96861)
#28 0x0000000000daf00f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdaf00f)
#29 0x0000000000da5cba ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#30 0x0000000004a18669 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#31 0x0000000003f4d4e4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f4d4e4)
#32 0x0000000004a18c7f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#33 0x00000000049daf1d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49daf1d)
#34 0x00000000049dbfae clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49dbfae)
#35 0x00000000049e39f5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49e39f5)
#36 0x0000000000dab4c5 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdab4c5)
#37 0x0000000000c5f554 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc5f554)
#38 0x0000745123c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#39 0x0000745123c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#40 0x0000000000da5765 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda5765)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by snarang181**
This patch fixes a crash in the constexpr interpreter when evaluating `new T[n]` with a negative element count.

Fixes https://github.com/llvm/llvm-project/issues/152904

### CODE REVIEW

File: clang/test/SemaCXX/new-neg-size.cpp [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// RUN: not %clang_cc1 -std=c++20 -fsyntax-only %s 2>&1 \
+// RUN:   | FileCheck %s --implicit-check-not='Assertion `NumElements.isPositive()` failed'
+
+// In C++20, constexpr dynamic allocation is permitted *only* if valid.
+// A negative element count must be diagnosed (and must not crash).
+
+constexpr void f_bad_neg() {
+  int a = -1;
+  (void) new int[a]; // triggers negative-size path in the interpreter
+}
```
Comment (frederick-vs-ja) [inline clang/test/SemaCXX/new-neg-size.cpp:10]: It seems to me that we should also cover `new (std::nothrow) int[a]`, in which case a null pointer should be returned.

File: clang/test/SemaCXX/new-neg-size.cpp [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// RUN: not %clang_cc1 -std=c++20 -fsyntax-only %s 2>&1 \
+// RUN:   | FileCheck %s --implicit-check-not='Assertion `NumElements.isPositive()` failed'
+
```
Comment (tbaederr) [inline clang/test/SemaCXX/new-neg-size.cpp:3]: You don't use `FileCheck` for these kinds of tests, use `-verify`.

Comment (tbaederr) [reply clang/test/SemaCXX/new-neg-size.cpp:3]: Oh and the test should go into `test/AST/ByteCode/`

File: clang/test/SemaCXX/new-neg-size.cpp (hunk 1 above)
Comment (snarang181) [reply clang/test/SemaCXX/new-neg-size.cpp]: Added

File: clang/test/AST/ByteCode/new-delete.cpp [hunk 3]
```diff
@@ -1070,14 +1070,13 @@ namespace BaseCompare {
...
 
-namespace NegativeArraySize {
+namespace NegativeArraySize { 
 
-constexpr void f() {
+constexpr void f() { // both-error {{constexpr function never produces a constant expression}}
   int x = -1;
-  int *p = new int[x]; // expected-note {{cannot allocate array with negative size in a constant expression}}
+  int *p = new int[x]; // expected-note {{cannot allocate array with negative size in a constant expression}} \
+                       // ref-note {{cannot allocate array; evaluated array bound -1 is negative}}
```
[the remark this answers is not in the document]
Comment (snarang181) [reply clang/test/AST/ByteCode/new-delete.cpp:1078]: Without the byte code interpreter, the diagnostic is not emitted. 
` note: cannot allocate array; evaluated array bound -1 is negative`
However, with the `-fexperimental-new-constant-interpreter` flag,  we hit the diagnostic. 
`note: cannot allocate array with negative size in a constant expression`

[the remark this answers is not in the document]
Comment (snarang181) [reply clang/test/AST/ByteCode/new-delete.cpp]: I changed the Bytecode interpreter to reuse the same diagnostic now; I had created a new one earlier. There's coherent output between both the interpreters now.

File: clang/lib/AST/ByteCode/Interp.h [hunk 4]
```diff
@@ -3490,7 +3490,15 @@ inline bool AllocN(InterpState &S, CodePtr OpPC, PrimType T, const Expr *Source,
     S.Stk.push<Pointer>(0, nullptr);
     return true;
   }
-  assert(NumElements.isPositive());
+  if (!NumElements.isPositive()) {
```
Comment (tbaederr) [inline clang/lib/AST/ByteCode/Interp.h:3493]:
```suggestion
  if (NumElements.isNegative()) {
```

File: clang/lib/AST/ByteCode/Interp.h [hunk 5]
```diff
@@ -3490,7 +3490,15 @@ inline bool AllocN(InterpState &S, CodePtr OpPC, PrimType T, const Expr *Source,
...
+    if (!IsNoThrow) {
+      S.FFDiag(Source, diag::note_constexpr_new_negative)
```
Comment (tbaederr) [inline clang/lib/AST/ByteCode/Interp.h:3495]:
```suggestion
      S.FFDiag(S.Current->getSource(OpPC), diag::note_constexpr_new_negative)
```

File: clang/test/AST/ByteCode/new-delete.cpp [hunk 6]
```diff
@@ -1069,6 +1069,30 @@ namespace BaseCompare {
...
+
+namespace NegativeArraySize { 
+
+constexpr void f() { // both-error {{constexpr function never produces a constant expression}}
+  int x = -1;
+  int *p = new int[x]; //both-note {{cannot allocate array; evaluated array bound -1 is negative}} 
+}
+
+} // namespace NegativeArraySize
+
```
Comment (tbaederr) [inline clang/test/AST/ByteCode/new-delete.cpp:1081]:
```suggestion
namespace NegativeArraySize { 
  constexpr void f() { // both-error {{constexpr function never produces a constant expression}}
    int x = -1;
    int *p = new int[x]; //both-note {{cannot allocate array; evaluated array bound -1 is negative}} 
  }
} // namespace NegativeArraySize

```

**Review by tbaederr — APPROVED** [review]
