### PR TITLE
[Flang][MLIR] - Handle the mapping of subroutine arguments when they are subsequently used inside the region of  an `omp.target` Op

### LINKED ISSUE #134912: [flang] Flang crashes in lowering to OpenMP when `fir.boxchar` is used in a `map` clause on `omp target`
```
$> cat reproducer.f90
  subroutine TestOfCharacter(a0, a1)
    character(len=*), intent(in) :: a0
    character(len=*), intent(inout):: a1

    !$omp target map(to:a0) map(from: a1)
    a1 = a0
    !$omp end target
  end subroutine TestOfCharacter
$> flang-new -fc1 -emit-hlfir  -fopenmp reproducer.f90
flang-new: /work1/omp-nightly/build/git/trunk21.0/llvm-project/flang/lib/Lower/OpenMP/OpenMP.cpp:1374: void genBodyOfTargetOp(Fortran::lower::AbstractConverter&, Fortran::lower::SymMap&, Fortran::semantics::SemanticsContext&, Fort\
ran::lower::pft::Evaluation&, mlir::omp::TargetOp&, const Fortran::common::openmp::EntryBlockArgs&, const mlir::Location&, const ConstructQueue&, llvm::SmallVectorImpl<tomp::DirectiveWithClauses<Fortran::lower::omp::Clause> >::con\
st_iterator, Fortran::lower::omp::DataSharingProcessor&): Assertion `valOp != nullptr' failed.
 
```

```
$> flang-new --version
flang version 21.0.0git (https://github.com/llvm/llvm-project a168ddc470825091ad52da12042fb38491ed81d6)
Target: x86_64-unknown-linux-gnu
```

### PR DESCRIPTION
**Pull request by bhandarkar-pranav**
This is a fix for https://github.com/llvm/llvm-project/issues/134912 which is a problem with mapping `fir.boxchar<k>` type values to the target i.e an `omp.target` op.

There really are two problems. Fixing the first exposed the second. The first problem is that OpenMP lowering of maps in `omp.target` in Flang cannot handle the mapping of a value that doesnt have a defining operation. In other words, a value that is a block argument. This is a corner case and it happens when a value is used inside the region of an `omp.target` and that value is a block argument in the region enclosing the `omp.target` op.  This patch fixes this by trying its best to not use a block argument inside the omp.target if it is possible.

The second problem this fixes is that it adds bounds to `omp.map.info` ops that map `fir.char<k, ?>` types by extracting the length from the corresponding `fir.boxchar`

### CODE REVIEW

File: flang/lib/Lower/OpenMP/OpenMP.cpp [hunk 1]
```diff
@@ -268,8 +274,54 @@ static void bindEntryBlockArgs(lower::AbstractConverter &converter,
...
+            // v.addr is
+            //  %4:2 = hlfir.declare (%3#0, %3#1, %2):(!fir.ref<!fir.char<1,?>>,
+            //                        index,!fir.dscope) ->
+            //                       (!fir.boxchar<1>, !fir.ref<!fir.char<1,?>>)
+            // v.len is
+            //  %3:2 = fir.unboxchar %arg0 : (!fir.boxchar<1>) ->
+            //         (!fir.ref<!fir.char<1,?>>, index)
+
+            // Mapping this to the target will create a use of %arg0 on the
+            // target. Since omp.target is IsolatedFromAbove, %arg0 will have to
```
Comment (vzakhari) [inline flang/lib/Lower/OpenMP/OpenMP.cpp:301]: Sorry, I do not understand why using `%3#2` in the target code results in mapping of `%arg0` - can you please clarify?  It should be just a use of a scalar `index` value, that can be made `firstprivate`.

Comment (bhandarkar-pranav) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: @vzakhari  - `%arg0`  itself isn't a scalar. From my understanding, it'll then have to be mapped so that it can be "unboxed"  (`fir.unbox %arg0`).

The problem really is that `v.len` should have been expressed in terms of `%4:2`. (Please correct me if I am wrong about my understanding of any of these points)

Comment (vzakhari) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: I think I see it now that `cloneBound` clones the defining operation given one of its results.  It was also assuming that the cloned result is `#0` of the operation, which is wrong, and you fixed it for `UnboxCharOp`.

This looks broken to me.  I think what we really want to pass to the OpenMP region is the scalar bound value, and this can be done without cloning the whole defining operation.

The bounds should be scalars, as I understand, so it should be unnecessary to clone the char box to get the bound value.

Consider how this case works:
```
subroutine TestOfCharacter(a0, a1, l)
  integer, intent(in) :: l
  real, intent(in) :: a0(l:)
  real, intent(inout):: a1(l:)

  !$omp target map(to:a0) map(from: a1)
  a1 = a0
  !$omp end target
end subroutine TestOfCharacter
```

The lower bounds are stored into temporaries for passing them via implicit maps to the target region:
```
    %0 = fir.alloca i32
    %1 = fir.alloca i32
    %2 = fir.dummy_scope : !fir.dscope
    %3:2 = hlfir.declare %arg2 dummy_scope %2 {fortran_attrs = #fir.var_attrs<intent_in>, uniq_name = "_QFtestofcharacterEl"} : (!fir.ref<i32>, !fir.dscope) -> (!fir.ref<i32>, !fir.ref<i32>)
    %4 = fir.load %3#0 : !fir.ref<i32>
    fir.store %4 to %0 : !fir.ref<i32>
...
    %9 = fir.load %3#0 : !fir.ref<i32>
    fir.store %9 to %1 : !fir.ref<i32>
...
    %24 = omp.map.info var_ptr(%1 : !fir.ref<i32>, i32) map_clauses(implicit, exit_release_or_enter_alloc) capture(ByCopy) -> !fir.ref<i32> {name = ""}
    %25 = omp.map.info var_ptr(%0 : !fir.ref<i32>, i32) map_clauses(implicit, exit_release_or_enter_alloc) capture(ByCopy) -> !fir.ref<i32> {name = ""}
    omp.target map_entries(%18 -> %arg3, %23 -> %arg4, %24 -> %arg5, %25 -> %arg6 : !fir.ref<!fir.array<?xf32>>, !fir.ref<!fir.array<?xf32>>, !fir.ref<i32>, !fir.ref<i32>) {
      %26 = fir.load %arg6 : !fir.ref<i32>
      %27 = fir.load %arg5 : !fir.ref<i32>
```

I do not know exactly where this happens, but I think the character length should be handled the same way.

Do you know where this array lower bounds handling happens?

Comment (bhandarkar-pranav) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: Since the lower bound `l` is needed in the target OpenMP region in the `hfir.declare` ops for `a0` and `a1`, it is implicitly captured. It is explicitly mapped though because all values used insde the `omp.target` region need to be mapped to incoming block arguments because `omp.target` is `IsolatedFromAbove`. 

The problem in the case that this PR is solving is that this process of creating a temporary for an implicitly captured value is contingent upon such a value having a `definingOp` that is non-null. In the case of block arguments, the definingOp is null.

Comment (vzakhari) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: Isn't the length of the character (i.e. the `index` value itself, not its defining op) also needed in the `hlfir.declare` of the character var?  Or is it different because in the array lower bound there is `!fir.ref<i32>` and in the length case it is `i32`?

> The problem in the case that this PR is solving is that this process of creating a temporary for an implicitly captured value is contingent upon such a value having a definingOp that is non-null. In the case of block arguments, the definingOp is null.

Can you please point me to where this is done?


Again, my general concern here is that we should probably just pass the chracter length value as a literal firstprivate, instead of cloning the defining `fir.unboxchar`.

Comment (agozillon) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: https://github.com/llvm/llvm-project/blob/main/flang/lib/Lower/OpenMP/OpenMP.cpp#L1371 this is the segment I believe, we map or clone across dependencies on the bounds

Comment (vzakhari) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: Thank you! So the temporarization of the direct uses is run after `bindEntryBlockArgs`, and I assume it will kick in if we just generate a direct use of the `index` Value of the character length.  Won't it happen automatically, if you just avoid the cloning, i.e., in the original code, replace this:
```
            converter.bindSymbol(
                sym, fir::CharBoxValue(arg, cloneBound(v.getLen())));
```
with this:
```
            converter.bindSymbol(
                sym, fir::CharBoxValue(arg, v.getLen()));
```
?

Comment (bhandarkar-pranav) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:301]: @vzakhari  - For the reduced testcase that I have added to this PR, not cloning the length works. I'll test this a little more rigorously, while also trying to unearth the motivation for the presence of the clone in the first place (it predates my PR of course)

**Comment by bhandarkar-pranav** [comment]
@vzakhari  - I have changed my approach and updated this PR. I have tested this locally to the extent that I could and things work fine. Could you please review this PR?

@agozillon @TIFitis @raghavendhra @ergawy @skatrak  - Could you please review this PR? TIA

File: flang/lib/Optimizer/OpenMP/MapInfoFinalization.cpp [hunk 2]
```diff
@@ -550,7 +552,39 @@ class MapInfoFinalizationPass
       // iterations from previous function scopes.
       localBoxAllocas.clear();
 
-      // First, walk `omp.map.info` ops to see if any record members should be
+      // First, walk `omp.map.info` ops to see if any of them have varPtrs
+      // with an underlying type of fir.char<k, ?>, i.e a character
+      // with dynamic length. If so, check if they need bounds added.
+      func->walk([&](mlir::omp::MapInfoOp op) {
+        if (!op.getBounds().empty())
+          return mlir::WalkResult::advance();
```
Comment (skatrak) [inline flang/lib/Optimizer/OpenMP/MapInfoFinalization.cpp:560]: Nit: Here you can use the `void` callback specialization of `Operation::walk()`, since we don't need to interrupt the walk or skip nested operations.
```suggestion
          return;
```

File: flang/include/flang/Optimizer/Builder/DirectivesCommon.h [hunk 3]
```diff
@@ -131,6 +133,31 @@ gatherBoundsOrBoundValues(fir::FirOpBuilder &builder, mlir::Location loc,
...
+    mlir::Value zero = builder.createIntegerConstant(loc, idxTy, 0);
+    mlir::Value one = builder.createIntegerConstant(loc, idxTy, 1);
+    mlir::Value extent = unboxed.getResult(1);
+    mlir::Value stride = one;
+    mlir::Value ub = builder.create<mlir::arith::SubIOp>(loc, extent, one);
+    mlir::Type boundTy = builder.getType<mlir::omp::MapBoundsType>();
+    return builder.create<mlir::omp::MapBoundsOp>(
+        loc, boundTy, /*lower_bound=*/zero,
+        /*upper_bound=*/ub, /*extent=*/extent, /*stride=*/stride,
+        /*stride_in_bytes = */ true, /*start_idx=*/zero);
```
Comment (skatrak) [inline flang/include/flang/Optimizer/Builder/DirectivesCommon.h:157]:
```suggestion
        /*stride_in_bytes=*/ true, /*start_idx=*/zero);
```

File: flang/test/Lower/OpenMP/map-character.f90 [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+  !$omp target map(to:a0) map(from: a1)
+  a1 = a0
+  !$omp end target
+end subroutine TestOfCharacter
+
+
+!CHECK:  %[[A0_BOXCHAR_ALLOCA:.*]] = fir.alloca !fir.boxchar<1>
+!CHECK:  %[[A1_BOXCHAR_ALLOCA:.*]] = fir.alloca !fir.boxchar<1>
+!CHECK:  %[[UNBOXED_ARG0:.*]]:2 = fir.unboxchar %arg0 : (!fir.boxchar<1>) -> (!fir.ref<!fir.char<1,?>>, index)
```
Comment (skatrak) [inline flang/test/Lower/OpenMP/map-character.f90:16]: Nit: I'd suggest not hard coding function arguments like `%arg0`, but rather capturing it from a check line (e.g. `CHECK: func.func @...(%[[ARG:.*]]...`) just in case this breaks in the future.

**Review by skatrak — APPROVED** [review]
Thank you Pranav, I gave this a somewhat superficial look and seems reasonable to me. Please wait for @vzakhari's approval before merging, although it's probably best if someone more knowledgeable about OpenMP map handling gave it a look as well.

File: flang/lib/Lower/OpenMP/OpenMP.cpp [hunk 5]
```diff
@@ -217,59 +217,36 @@ static void bindEntryBlockArgs(lower::AbstractConverter &converter,
...
-           "target map-like clause operand unsupported bound type");
-    };
-
-    auto cloneBounds = [cloneBound](llvm::ArrayRef<mlir::Value> bounds) {
-      llvm::SmallVector<mlir::Value> clonedBounds;
-      llvm::transform(bounds, std::back_inserter(clonedBounds),
-                      [&](mlir::Value bound) { return cloneBound(bound); });
-      return clonedBounds;
-    };
-
```
Comment (TIFitis) [inline flang/lib/Lower/OpenMP/OpenMP.cpp:240]: I remember it being essential to clone the bounds rather than using them directly inside the region. But, maybe things have changed which allows this now.

Can you please check if the following snippet works fine with this change?

```
subroutine omp_target_implicit(n)
   integer :: n
   integer :: a(n, 1024)
   !$omp target
      a(2,3) = 10
   !$omp end target
end subroutine omp_target_implicit
```

Also, it would be great if @jeanPerier could +1 this change :)

Comment (bhandarkar-pranav) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:240]: Thanks @TIFitis for taking a look. The above snippet compiled fine with this PR.

**Review by TIFitis — APPROVED** [review]

**Review by vzakhari — APPROVED** [review]
Looks much clearer to me. Thank you!

File: flang/lib/Lower/OpenMP/OpenMP.cpp (hunk 5 above)
Comment (jeanPerier) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:240]: It matters that they are cloned somehow since the region is isolated from above, but I think you may be handling it in the code below on line 1347 that is cloning all the values that do not belong to the region. So, explicit cloning is likely not needed anymore.

```
  mlir::getUsedValuesDefinedAbove(region, valuesDefinedAbove);
  while (!valuesDefinedAbove.empty()) {
```
