### PR TITLE
[LLVM][CodeGen] Ensure optimizeIncrementingWhile only accepts scalable vectors.

### LINKED ISSUE #148347: [AArch64] Cannot select: PTRUE TargetConstant:i32<4>
Compiling this:

```
extern char a[][3][8];
void b(bool c) {
  for (;;)
    for (short d = 1; d < 6; d += 38772)
      for (short e = 1; e < c + 15; e += 4)
        a[0][2][e] = 0;
}
```

with this:

```
-O3 -mcpu=grace t.cpp
```

results in:

```
fatal error: error in backend: Cannot select: 0x28168230: v8i8 = AArch64ISD::PTRUE TargetConstant:i32<4>
In function: _Z1bb
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -fno-verbose-asm -S -target aarch64-linux-gnu --gcc-toolchain=/opt/compiler-explorer/arm64/gcc-12.2.0/aarch64-unknown-linux-gnu --sysroot=/opt/compiler-explorer/arm64/gcc-12.2.0/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot -fcolor-diagnostics -fno-crash-diagnostics -O3 -mcpu=grace <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'AArch64 Instruction Selection' on function '@_Z1bb'
 #0 0x0000000003c7a1b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c7a1b8)
 #1 0x0000000003c77b8c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c77b8c)
 #2 0x0000000003bc83d3 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3bc83d3)
 #3 0x0000000003c6f3de llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3c6f3de)
 #4 0x0000000000da499b LLVMErrorHandler(void*, char const*, bool) cc1_main.cpp:0:0
 #5 0x0000000003bd2303 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3bd2303)
 #6 0x000000000524118a llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x524118a)
 #7 0x0000000005247061 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5247061)
 #8 0x0000000000f48fd7 (anonymous namespace)::AArch64DAGToDAGISel::Select(llvm::SDNode*) AArch64ISelDAGToDAG.cpp:0:0
```

See also:

https://godbolt.org/z/r38qsM7Pv

### PR DESCRIPTION
**Pull request by paulwalker-arm**
Fixes https://github.com/llvm/llvm-project/issues/148347

### CODE REVIEW

**Review by sjoerdmeijer — APPROVED** [review]
Thanks for the quick fix, LGTM.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -5509,7 +5509,8 @@ static SDValue optimizeIncrementingWhile(SDNode *N, SelectionDAG &DAG,
   unsigned Op0 = N->getOpcode() == ISD::INTRINSIC_WO_CHAIN ? 1 : 0;
   unsigned Op1 = N->getOpcode() == ISD::INTRINSIC_WO_CHAIN ? 2 : 1;
 
-  if (!isa<ConstantSDNode>(N->getOperand(Op1)))
+  if (!N->getValueType(0).isScalableVector() ||
```
Comment (rj-jesus) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5512]: Would it make sense to do this check in `performActiveLaneMaskCombine` instead? I think for fixed length vectors this can't be reached from anywhere else, and we already have a similar check there which perhaps we could reuse.

If we do keep it here, it may still be worth moving it a few lines below to the `if (!isa<ConstantSDNode>(N->getOperand(Op0)))` in case we ever call this for fixed length vectors with a max value operand and `IsEqual = true`.

Comment (paulwalker-arm) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5512]: I suspect relying on the call site is what caused this in the first place as the function then got used elsewhere.

The IsEqual case only applies to the SVE intrinsics, which means there is no route where fixed length vectors can exercises the code. Even when using SVE VLS the intrinsics continue to use scalable vectors. For this reason I'd rather keep the bailout code together.

Comment (rj-jesus) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:5512]: Indeed, that's a good point. I had in mind we still leave an assert here to make it clear that fixed length vectors are currently unsupported, but bailing out is also good.

I was thinking of a scenario where this could get used elsewhere at some point for fixed length vectors with IsEqual set to true, but we can revisit it if that ever happens.

Thanks very much for fixing this. :)

**Review by rj-jesus — APPROVED** [review]
