### PR TITLE
[WebAssembly] validate `table.grow` correctly

### LINKED ISSUE #79966: wasm assembly type checker throws incorrect error
Consider the following example:

```asm
.section .text.foobar,"",@
.hidden foobar
.globl foobar
foobar:
  .functype foobar () -> (i32)
  i32.const 0
  table.get __indirect_function_table
  i32.const 42
  table.grow __indirect_function_table
  end_function
```

```c
#include <stdio.h>

int foobar(void);

int main(void) {
  printf("%d\n", foobar());
  printf("%d\n", foobar());
}
```

When compiling with `clang -mreference-types -O3 foobar.s asdf.c -o asdf.wasm -Wl,--growable-table`, it outputs the following error:

```
foobar.s:9:3: error: popped funcref, expected externref
  table.grow __indirect_function_table
  ^
```

But if I forcibly disable the wasm assembly type checker with `-Wa,--no-type-check`, then it compiles and runs just fine. The issue above is reported with latest llvm `master`.

### PR DESCRIPTION
**Pull request by HerrCai0907**
This PR add support in wasm asm type checker to implement checker of `table.grow`
Fixes: #79966.

### CODE REVIEW

File: llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.cpp [hunk 1]
```diff
@@ -401,7 +411,7 @@ bool WebAssemblyAsmTypeCheck::typeCheck(SMLoc ErrorLoc, const MCInst &Inst,
     for (unsigned I = II.getNumOperands(); I > II.getNumDefs(); I--) {
       const auto &Op = II.operands()[I - 1];
       if (Op.OperandType == MCOI::OPERAND_REGISTER) {
-        auto VT = WebAssembly::regClassToValType(Op.RegClass);
+        wasm::ValType VT = WebAssembly::regClassToValType(Op.RegClass);
```
Comment (sbc100) [inline llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.cpp:414]: Why this change?   Maybe revert his line if its not needed?

File: llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.cpp [hunk 2]
```diff
@@ -288,6 +288,16 @@ bool WebAssemblyAsmTypeCheck::typeCheck(SMLoc ErrorLoc, const MCInst &Inst,
...
+  } else if (Name == "table.size") {
+    if (getTable(Operands[1]->getStartLoc(), Inst, Type))
+      return true;
+    Stack.push_back(wasm::ValType::I32);
+  } else if (Name == "table.grow") {
+    if (getTable(Operands[1]->getStartLoc(), Inst, Type))
+      return true;
+    if (popType(ErrorLoc, wasm::ValType::I32))
+      return true;
+    Stack.push_back(wasm::ValType::I32);
```
Comment (sbc100) [inline llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.cpp:300]: Wow, this is pretty broken.

**Review by sbc100 — APPROVED** [review]
