### PR TITLE
[DirectX] Do not flatten GEP chains for unsupported types

### LINKED ISSUE #150463: [DXIL] DXIL Flatten Arrays Pass crashing
Repro case: https://godbolt.org/z/b6xPsKfYG

The DXIL Flatten Arrays Pass is crashing if a struct survives and it tries to flatten an array inside a struct. While it is unlikely this will generate valid DXIL, we shouldn't crash.

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #150463 by not processing GEPs for unsupported types such as structs in the DXILFlattenArrays pass.

### CODE REVIEW

**Review by bob80905 — APPROVED** [review]
Looks to me like line 298 is the way out for parent GEPs that have a struct type or otherwise unsupported type. 
Might be worth updating the comment with something like, "we also don't need to do any flattening for children GEPs if the type is unsupported, e.g., a struct"
But that's a nit / verifying my understanding is correct. Code / test LGTM

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 1]
```diff
@@ -263,8 +263,13 @@ bool DXILFlattenArraysVisitor::visitGetElementPtrInst(GetElementPtrInst &GEP) {
   // merge the byte offsets. Otherwise, this GEP is itself the root of a GEP
   // chain and we need to deterine the root array type
   if (auto *PtrOpGEP = dyn_cast<GEPOperator>(PtrOperand)) {
-    assert(GEPChainInfoMap.contains(PtrOpGEP) &&
-           "Expected parent GEP to be visited before this GEP");
+
+    // If the parent GEP was not processed, then we do not want to process its
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:267]: The comment makes sense as does the fix, Was wondering should we have something more explict about type checking for structs and bailing?

**Review by farzonl — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 1 above)
Comment (bob80905) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:267]: Agreed, I think the comment on 296 is a good spot to indicate that

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:267]: I could throw an error when there is an unsupported type, but would the DXILFlattenArrays pass really be the place to throw such errors?

Line 296 and below already has
```c++
    // If the root type is not an array, we don't need to do any flattening
    if (!isa<ArrayType>(RootTy))
      return false;
```
to indicate that only arrays are applicable to this transformation. 
The name of the pass "DXIL Flatten Arrays" to me also implies it only applies to arrays.

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:267]: This can be addressed in a follow-up PR if needed.
