### PR TITLE
[libc++][bit] Improves rotate functions.

### LINKED ISSUE #96612: `std::rotr()` causes implicit-integer-sign-change UBSan failure if passed negative shift
The following program built with `-std=c++23 -stdlib=libc++ -fsanitize=implicit-integer-sign-change`
causes:

```
include/c++/v1/__bit/rotate.h:27:8: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'unsigned int' changed the value to 4294967295 (32-bit, unsigned)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opt/compiler-explorer/clang-18.1.0/bin/../include/c++/v1/__bit/rotate.h:27:8 
```

```cpp
#include <bit>

int main()
{
    return std::rotr(0u, -1);
}
```

https://godbolt.org/z/EveTsa8Gs

If you think this is worth fixing I can submit a patch.

### PR DESCRIPTION
**Pull request by mordante**
Investigating #96612 shows our implementation was different from the Standard and could cause UB. Testing the codegen showed quite a bit of assembly generated for these functions. The functions have been written differently which allows Clang to optimize the code to use simple CPU rotate instructions.

Fixes: https://github.com/llvm/llvm-project/issues/96612

### CODE REVIEW

File: libcxx/include/__bit/rotate.h [hunk 1]
```diff
@@ -20,24 +20,37 @@
 
 _LIBCPP_BEGIN_NAMESPACE_STD
 
+// Writing two full functions for rotl and rotr makes it easier for the compiler
+// to optimize the code. On x86 this function becomes the ROL instruction and
+// the rotr function becomes the ROR instruction.
 template <class _Tp>
-_LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX14 _Tp __rotr(_Tp __t, int __cnt) _NOEXCEPT {
-  static_assert(__libcpp_is_unsigned_integer<_Tp>::value, "__rotr requires an unsigned integer type");
-  const unsigned int __dig = numeric_limits<_Tp>::digits;
```
Comment (mk-huawei) [inline libcxx/include/__bit/rotate.h:26]: Given that `numeric_limits<_Tp>::digits` (cf. https://en.cppreference.com/w/cpp/types/numeric_limits/digits) already returns an `int` (signed). Wouldn't it be simpler to just do the following (no other changes required if I'm not mistaken)?
```
const int __dig = numeric_limits<_Tp>::digits;
```

File: libcxx/include/__bit/rotate.h [hunk 2]
```diff
@@ -20,24 +20,37 @@
...
-  if ((__cnt % __dig) == 0)
-    return __t;
+_LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX14 _Tp __rotl(_Tp __x, int __s) _NOEXCEPT {
+  static_assert(__libcpp_is_unsigned_integer<_Tp>::value, "__rotl requires an unsigned integer type");
+  const unsigned int __N = numeric_limits<_Tp>::digits;
```
Comment (ldionne) [inline libcxx/include/__bit/rotate.h:29]: Agreed with other reviewers, I think we want:

```suggestion
  const int __N = numeric_limits<_Tp>::digits;
```

We can't do `constexpr` because of C++03, but it shouldn't matter.

**Review by ldionne — APPROVED** [review]
LGTM w/ comments.

File: libcxx/include/__bit/rotate.h (hunk 1 above)
Comment (mordante) [reply libcxx/include/__bit/rotate.h:26]: Seems I didn't submit my comment before. We typically don't use `const` at all. The code was based on the original code. I'll changes it as suggested by Louis.

**Comment by chfast** [comment]
Can this be backported to LLVM 19?

**Comment by mordante** [comment]
/cherry-pick [79caa06](https://github.com/llvm/llvm-project/commit/79caa066ea6d4f2479aed6a28c6c04fd7857bec8)
