### PR TITLE
[Utils][mlir] Fix interaction between CodeExtractor and OpenMPIRBuilder

### LINKED ISSUE #138102: [Flang][OpenMP] Referring to an instruction in another function!
Reproducible on Godbolt:
https://godbolt.org/z/44Ej9E6Gj
```f90
integer, parameter :: N = 100000, CHUNKSZ = 10000
real :: Z(N)
integer :: C, i

do C = 1, N, CHUNKSZ
    !$omp task
        !$omp target map(Z(C:C+CHUNKSZ-1))
            !$omp parallel do
            do i = C, C+CHUNKSZ-1
            end do
        !$omp end target
    !$omp end task
end do
end
```

### PR DESCRIPTION
**Pull request by mrkajetanp**
CodeExtractor can currently erroneously insert an alloca into a different function than it inserts its users into, in cases where code is being extracted out of a function that has already been outlined. Add an assertion that the two blocks being inserted into are actually in the same function.

Add a check to findAllocaInsertPoint in OpenMP to LLVMIR translation to prevent the aforementioned scenario from happening.

OpenMPIRBuilder relies on a callback mechanism to fix-up a module later on during the finaliser step. In some cases this results in the module being invalid prior to the finalise step running. Remove calls to verifyModule wrapped in LLVM_DEBUG from CodeExtractor, as the presence of those results in the compiler crashing with -mllvm -debug due to premature module verification where it would not crash without -debug.

Call ompBuilder->finalize() the end of mlir::translateModuleToLLVMIR, in order to make sure the module has actually been finalized prior to trying to verify it.

Resolves https://github.com/llvm/llvm-project/issues/138102.

### CODE REVIEW

File: llvm/lib/Transforms/Utils/CodeExtractor.cpp [hunk 1]
```diff
@@ -1868,8 +1866,14 @@ CallInst *CodeExtractor::emitReplacerCall(
...
       BasicBlock::Create(Context, "codeRepl", oldFunction, ReplIP);
+  // In cases with multiple levels of outlining, e.g. with OpenMP,
+  // AllocationBlock may end up in a function different than oldFunction. We
+  // need to make sure we do not use it in those cases, otherwise the alloca
+  // will end up in a different function from its users and break the module.
   BasicBlock *AllocaBlock =
-      AllocationBlock ? AllocationBlock : &oldFunction->getEntryBlock();
+      (AllocationBlock && oldFunction == AllocationBlock->getParent())
+          ? AllocationBlock
+          : &oldFunction->getEntryBlock();
```
Comment (ergawy) [inline llvm/lib/Transforms/Utils/CodeExtractor.cpp]: `AllocationBlock` is assigned on construction of the `CodeExtractor` object. Should we instead make sure that we pass a suitable basic block when we construct the code extractor object?

File: mlir/lib/Target/LLVMIR/ModuleTranslation.cpp [hunk 2]
```diff
@@ -2332,6 +2332,10 @@ mlir::translateModuleToLLVMIR(Operation *module, llvm::LLVMContext &llvmContext,
   // beforehand.
   translator.debugTranslation->addModuleFlagsIfNotPresent();
 
+  // Call the OpenMP IR Builder callbacks prior to verifying the module
+  if (auto *ompBuilder = translator.getOpenMPBuilder())
+    ompBuilder->finalize();
+
   if (!disableVerification &&
       llvm::verifyModule(*translator.llvmModule, &llvm::errs()))
     return nullptr;
```
Comment (ergawy) [inline mlir/lib/Target/LLVMIR/ModuleTranslation.cpp:2340]: I think we can move module verification to `~ModuleTranslation` instead. This way we both make sure that verification happens after finalization and we do not need to add the `isFinalized` bool.

**Review by ergawy — COMMENTED** [review]
Thanks @mrkajetanp. Just a few comments for possible improvements.

File: mlir/lib/Target/LLVMIR/ModuleTranslation.cpp (hunk 2 above)
Comment (mrkajetanp) [reply mlir/lib/Target/LLVMIR/ModuleTranslation.cpp:2340]: We could do this, but then we'd have to change the signature of `mlir::translateModuleToLLVMIR` to remove the `disableVerification` option as it would no longer be possible to run the translation without verification, because verification would always happen in the destructor. Is this desirable?

File: llvm/lib/Transforms/Utils/CodeExtractor.cpp (hunk 1 above)
Comment (mrkajetanp) [reply llvm/lib/Transforms/Utils/CodeExtractor.cpp]: If we go up the chain, the problem originates over here:
https://github.com/llvm/llvm-project/blob/fccab5d757778204666d70e2f1592952fc8b336d/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L501
`findAllocaInsertPoint` does a stackWalk to find a preexisting alloca insert point, and it does find it - but it's in a different function. We could put a check here to make sure that we only use it if it's in the same function as `builder.getInsertBlock()`? 
This would fix the issue, but fixing it inside CodeExtractor would make it it more robust for other cases when a wrong block might be passed on accident. I think I'd lean towards keeping it as-is on that account, but if other people have strong preferences or arguments to the contrary then I am happy to change it.

Comment (tblah) [reply llvm/lib/Transforms/Utils/CodeExtractor.cpp]: Maybe it should be fixed in the stack walk and have an assertion added to the code extractor?

Comment (mrkajetanp) [reply llvm/lib/Transforms/Utils/CodeExtractor.cpp]: That's a good way to do it, thanks for the suggestion - done :)

Comment (tblah) [reply llvm/lib/Transforms/Utils/CodeExtractor.cpp]: Thanks for the update.

Sorry to be difficult but looking at this change gave me an idea: I think this situation just shouldn't ever happen.

Say we have something like this
```
omp.op1 {
  other.op1
  omp.op2 {
    other.op2
  }
  other.op3
}
```

If the lowering for omp.op2 is trying to put allocas in the alloca region for op1 then yes both of those could be outlined to different functions. But I don't think this should ever happen. If omp.op2 is expecting to be outlined, I think it should define its own alloca insertion point on the alloca stack.

I suspect one of the operations in your test needs to add an insertion point to the stack.

Comment (mrkajetanp) [reply llvm/lib/Transforms/Utils/CodeExtractor.cpp]: Whenever things are saved on that stack, the thing being saved is what was previously returned by findAllocaInsertPoint. E.g.:
https://github.com/llvm/llvm-project/blob/fccab5d757778204666d70e2f1592952fc8b336d/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L2265

The specific call which finds the block in a different function during the stack walk is inside convertOmpTarget, here:
https://github.com/llvm/llvm-project/blob/fccab5d757778204666d70e2f1592952fc8b336d/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L5555.

findAllocaInsertPoint defines its own insert point if it can't already find one, hence adding that extra check fixes the problem at hand. In this case the outer op - task - does add the alloca insertion point to the stack like it should, but that insertion point is inside of main as opposed to the outlined function for task.

That is to say - I don't think there are missing SaveStack operations at the point where it's relevant for this specific case. `target` does not save the alloca point it finds (maybe it should?) but by the time target _would_ be saving it, the block that was found is already wrong.

File: mlir/lib/Target/LLVMIR/ModuleTranslation.cpp (hunk 2 above)
Comment (ergawy) [reply mlir/lib/Target/LLVMIR/ModuleTranslation.cpp:2340]: I think leaving it here makes more sense indeed. Thanks for looking into it.

**Review by ergawy — APPROVED** [review]

**Review by tblah — APPROVED** [review]
LGTM this is the best fix we can do before LLVM-21.

I had a deeper look at this. The bug is in `OpenMPIRBuilder::createTarget`. This creates the outlined target function immediately instead of using storing an `OpenMPIRBuilder::OutlineInfo` like every other `OpenMPIRBuilder` method. Doing this invalidates the saved alloca insertion points in `OpenMPToLLVMIRTranslation.cpp`. I expect this probably results in other yet to be discovered unintended consequences too because this breaks assumptions in other operations.

Is there a reason that target has to be handled differently? If not, either target offload maintainers should fix this to conform with the existing design or we should have an RFC discussing dropping the delayed outlining (`OutlineInfo`) entirely so that outlining occurs in a consistent way.

(I'm aware that `OutlineInfo` probably doesn't have the right information for target outlining now, but that would be easy to add. My concern is that the outlining should all be done in the order defined by the `OutlineInfos` stack in `OpenMPIRBuilder`).

**Comment by skatrak** [comment]
> Is there a reason that target has to be handled differently? If not, either target offload maintainers should fix this to conform with the existing design or we should have an RFC discussing dropping the delayed outlining (`OutlineInfo`) entirely so that outlining occurs in a consistent way.

I tracked down the discussion about this decision to the initial implementation of `target` support: [D147172](https://reviews.llvm.org/D147172#4244736). Perhaps @jsjodin could check if the original reasons to not use `OutlineInfo` are still applicable, after things have matured a bit.
