### PR TITLE
[flang][OpenMP] Reassociate logical ATOMIC update expressions

### LINKED ISSUE #144944: [flang][OpenMP] OMP ATOMIC restriction too strong?
Consider the following code:
```
subroutine test(a,b,c)
  logical :: a,b,c
  !$OMP ATOMIC
  ! This fails:
  a = a .and. b .and. c
  ! This succeeds:
  a = a .and. (b .and. c)
end subroutine
```
Compiling with flang:
```
$ flang -c -fopenmp atomic-err.f90 
flang-21: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: Semantic errors in atomic-err.f90
./atomic-err.f90:5:7: error: The atomic variable a cannot be a proper subexpression of an argument (here: a.and.b) in the update operation
    a = a .and. b .and. c
        ^^^^^^^^^^^^^^^^^
./atomic-err.f90:5:7: error: The atomic variable a should appear as an argument of the top-level AND operator
    a = a .and. b .and. c
        ^^^^^^^^^^^^^^^^^
```
It seems to be a bit arbitrary that `a = a .and. b .and. c` fails, but `a = a .and. (b .and. c)` succeeds. Perhaps it would be possible to process `a = a .and. b .and. c` as if it had parenthesis in the right places?

FWIW, gfortran and ifx accept this code.

Compiler version:
```
$ flang --version
flang version 21.0.0git (https://github.com/llvm/llvm-project 3de01d07c33c10dfefc753c87c0a926fd512425b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
...
```

### PR DESCRIPTION
**Pull request by kparzysz**
This is a follow-up to PR153488 and PR155840, this time for expressions of logical type. The handling of logical operations in Expr<T> differs slightly from regular arithmetic operations. The difference is that the specific operation (e.g. and, or, etc.) is not a part of the type, but stored as a data member.
Both the matching code and the reconstruction code needed to be extended to correctly handle the data member.

This fixes https://github.com/llvm/llvm-project/issues/144944

### CODE REVIEW

File: flang/lib/Semantics/check-omp-atomic.cpp [hunk 1]
```diff
@@ -167,37 +181,53 @@ struct ReassocRewriter : public evaluate::rewrite::Identity {
...
+        return evaluate::Expr<T>(TypeS( //
+            opCode, std::move(atom),
+            evaluate::Expr<T>(TypeS( //
+                opCode, std::move(op1), std::move(op2)))));
+      }
+    } else {
+      // Generic reconstruction.
+      return evaluate::Expr<T>(TypeS( //
+          std::move(atom),
+          evaluate::Expr<T>(TypeS( //
```
Comment (eugeneepshteyn) [inline flang/lib/Semantics/check-omp-atomic.cpp:226]: Empty comments at the end of the line?

Comment (kparzysz) [reply flang/lib/Semantics/check-omp-atomic.cpp:226]: These are to aid clang-format in keeping these expressions in a desirable format.  The expressions in the two return statements are almost identical, and I wanted to emphasize their similarities.

**Review by tblah — APPROVED** [review]
Clever stuff
