### PR TITLE
[clang][ExprConst] Reject field access with nullptr base

### LINKED ISSUE #113821: [ExprConst] Field access resulting in null pointer is diagnosed at compile time
Sorry for the clunky title.

Consider this code:
```c++
  constexpr struct C {int a[2];} *c = nullptr;
  static_assert(&c->a[1] - &c->a[0] == 1);
```
The output is:
```console
./array.cpp:141:17: error: static assertion expression is not an integral constant expression
  141 |   static_assert(&c->a[1] - &c->a[0] == 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
./array.cpp:141:21: note: cannot access field of null pointer
  141 |   static_assert(&c->a[1] - &c->a[0] == 1);
      |                     ^
```

We diagnose this here: https://github.com/llvm/llvm-project/blob/7fe149cdf09d04fb8390b97c91bd9214c968cd3e/clang/lib/AST/ExprConstant.cpp#L1715-L1720

Because `IsNullPtr` is true here: https://github.com/llvm/llvm-project/blob/7fe149cdf09d04fb8390b97c91bd9214c968cd3e/clang/lib/AST/ExprConstant.cpp#L1702-L1712

However, if the field we're talking about coincidentally doesn't start at offset 0 (and thus `c->a` isn't `0`), we don't diagnose at all and this example just works:

```c++
  constexpr struct C {char pad; int a[2];} *c = nullptr;
  static_assert(&c->a[1] - &c->a[0] == 1);
```
https://godbolt.org/z/vzTr6sEMo

As you can see in the godbolt link, GCC rejects this as well.

I'm wondering that is right here. Should the code work in both cases or in neither case?

CC @zygoloid @AaronBallman

### PR DESCRIPTION
**Pull request by tbaederr**
Reject them if the base is null, not only if the entire pointer is null.

Fixes #113821

### CODE REVIEW

File: clang/lib/AST/ExprConstant.cpp [hunk 1]
```diff
@@ -1703,7 +1703,7 @@ namespace {
     bool checkNullPointerDiagnosingWith(const GenDiagType &GenDiag) {
       if (Designator.Invalid)
         return false;
-      if (IsNullPtr) {
+      if (getLValueBase().isNull()) {
```
Comment (zygoloid) [inline clang/lib/AST/ExprConstant.cpp:1706]: Why was the old check not good enough here? In the added testcase, `nb` is a null pointer.

Comment (zygoloid) [reply clang/lib/AST/ExprConstant.cpp:1706]: Oh, I see. We're adjusting the offset *before* we call `addDecl`. I think this would be better fixed by reversing the order in which we do those steps -- first `addDecl` and then adjust the offset. A null base isn't necessarily a null pointer, so checking for a null base here seems wrong (but only in the weird case of a zero integer cast to a non-null pointer value, which we should only accept in constant-folding mode, not when properly evaluating).

Comment (tbaederr) [reply clang/lib/AST/ExprConstant.cpp:1706]: Looks like the check here was `!Base` until 402804b6d67c880c97e575342189025fe28c0f81

**Comment by tbaederr** [comment]
Ping

**Review by AaronBallman — APPROVED** [review]
LGTM but the changes should come with a release note.

**Comment by tbaederr** [comment]
@zygoloid Do you approve too?

**Comment by zygoloid** [comment]
As mentioned in the comment thread, I'd prefer to see this addressed by reversing the order in which we call `addDecl` versus add an offset. While it's a corner case, I think this change would cause us to start rejecting things like [this example](https://godbolt.org/z/5Pae6Ghd7) where we form a non-null pointer with no base in a constant-folded region. Currently, the subsequent member access (`->hardware_register_1`) is accepted, because it's not accessing a member of a null pointer -- it's accessing a member of an integral non-null pointer.

I don't know how important things like this example are, but they do at least seem useful in some cases.

**Comment by tbaederr** [comment]
I think I understand what you mean by changing the order now. I changed two other places as well, just to be consistent.

**Review by zygoloid — APPROVED** [review]
LG, thank you!
