### PR TITLE
[X86] combineVTRUNCSAT - don't split 128-bit concatenated vectors when folding to PACKSS/US

### LINKED ISSUE #194344: [X86] combineVTRUNCSAT - crash on sub-128-bit concatenated vectors
https://zig.godbolt.org/z/GGGoo174z
```
define <8 x i8> @_mm_packs_pu16_manual(<4 x i16> %a, <4 x i16> %b) nounwind {
  %sh  = shufflevector <4 x i16> %a, <4 x i16> %b, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %minv = tail call <8 x i16> @llvm.smax.v8i16(<8 x i16> %sh, <8 x i16> splat (i16 0))
  %sat = tail call <8 x i16> @llvm.umin.v8i16(<8 x i16> %minv, <8 x i16> splat (i16 255))
  %tr  = trunc nuw <8 x i16> %sat to <8 x i8>
  ret <8 x i8> %tr
}
```
Hit this while demonstrating how mmx intrinsics can revectorize to 128/256/512-bit vector widths :/

### PR DESCRIPTION
**Pull request by RKSimon**
If the VTRUNCS/US node has 128-bit src and dst types, then ensure we don't split into sub-128-bit vectors - just treat it as padded with zeros to match VTRUNC behaviour.

Fixes #194344

### CODE REVIEW

**Comment by phoebewang** [comment]
> If the VTRUNCS/US node has 128-bit src/dst types

This reads as either one has 128-bit type.

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -55643,7 +55644,17 @@ static SDValue combineVTRUNCSAT(SDNode *N, SelectionDAG &DAG,
       (EltSizeInBits * 2) == Src.getScalarValueSizeInBits() &&
       isFreeToSplitVector(Src, DAG)) {
     SDLoc DL(N);
-    auto [LHS, RHS] = splitVector(Src, DAG, DL);
+    SDValue LHS, RHS;
+    if (Src.getValueSizeInBits() == VT.getSizeInBits()) {
+      assert(VT.is128BitVector() && "128-bit VTRUNC source expected");
+      LHS = Src;
+      RHS = getZeroVector(Src.getSimpleValueType(), Subtarget, DAG, DL);
```
Comment (phoebewang) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:55651]: Can this be an undef vector?

Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:55651]: No, because we're trying to match the behavior of X86ISD::VTRUNCS/US nodes (which implicitly zero the upper elements beyond the truncated elements) with a X86ISD::PACKS/US node, so the rhs (upper elements) need to be explicitly zero.

If we don't demand the upper elements, the SimplifyDemanded folds should later simplify to UNDEF.

**Review by phoebewang — APPROVED** [review]
LGTM.
