### PR TITLE
[mlir][Interface] Allow scalar operands and require ranked shaped operands in IndexingMapOpInterface

### LINKED ISSUE #179043: mlir-opt crash: Assertion failure in LinalgInterface when linalg.generic uses !amx.tile operand
mlir-opt version: 22.1.0
A crash occurs in **mlir-opt** when processing a **linalg.generic** operation that takes an !amx.tile type as an input. The internal LinalgInterface fails an assertion because it expects operands to be ranked tensors or memrefs to calculate shapes, but it receives a dialect-specific tile type instead.
```mlir
module {
  func.func @main() {
    %0 = amx.tile_zero : !amx.tile<16x16xf32>
    %1 = shape.const_size 16
    %2 = mpi.comm_world : !mpi.comm
    %3 = tensor.empty() : tensor<16x16xf32>
    %4 = linalg.generic {indexing_maps = [affine_map<(i, j) -> (i, j)>, affine_map<(i, j) -> (i, j)>], iterator_types = ["parallel", "parallel"]} ins(%0 : !amx.tile<16x16xf32>) outs(%3 : tensor<16x16xf32>) {
    ^bb0(%arg0: f32, %arg1: f32):
      linalg.yield %arg0 : f32
    } -> tensor<16x16xf32>
    return
  }
}
```
```
mlir-opt test.mlir
```
```
mlir-opt: llvm-project-llvmorg-22.1.0-rc1/build/tools/mlir/include/mlir/Dialect/Linalg/IR/LinalgInterfaces.h.inc:1212: llvm::ArrayRef<long int> mlir::linalg::detail::LinalgOpTrait<ConcreteOp>::getShape(mlir::OpOperand*) [with ConcreteOp = mlir::linalg::GenericOp]: Assertion `(isa<MemRefType>(t) || isa<RankedTensorType>(t)) && "expected a ranked tensor or memref in LinalgInterface::getRank"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: llvmorg-22.1.0-install/bin/mlir-opt test.mlir
 #0 0x00005b16a2657e32 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (llvmorg-22.1.0-install/bin/mlir-opt+0x252fe32)
 #1 0x00005b16a26545af llvm::sys::RunSignalHandlers() (llvmorg-22.1.0-install/bin/mlir-opt+0x252c5af)
 #2 0x00005b16a26546fc SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x0000706e14445330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #4 0x0000706e1449eb2c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x0000706e1449eb2c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x0000706e1449eb2c pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x0000706e1444527e raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x0000706e144288ff abort ./stdlib/abort.c:81:7
 #9 0x0000706e1442881b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x0000706e1443b517 (/lib/x86_64-linux-gnu/libc.so.6+0x3b517)
```

### PR DESCRIPTION
**Pull request by snarang181**
This change adjusts `IndexingMapOpInterface::verifyImpl`: Scalars are allowed as operands (treated as rank-0), vectors remain allowed, unranked tensors/memrefs are rejected with explicit diagnostics.

Fixes https://github.com/llvm/llvm-project/issues/179043

### CODE REVIEW

**Review by sweiglbosker — APPROVED** [review]
LGTM

**Comment by snarang181** [comment]
@sweiglbosker, LMK how this look. We can probably emit a better diagnostic this way.

```cpp
diff --git a/mlir/lib/Interfaces/IndexingMapOpInterface.cpp b/mlir/lib/Interfaces/IndexingMapOpInterface.cpp
index 2ef36a21a1ac..115408da5af6 100644
--- a/mlir/lib/Interfaces/IndexingMapOpInterface.cpp
+++ b/mlir/lib/Interfaces/IndexingMapOpInterface.cpp
@@ -35,12 +35,39 @@ LogicalResult mlir::IndexingMapOpInterface::verifyImpl() {
       return this->emitOpError("unexpected symbols in indexing_map #")
              << opOperand.getOperandNumber();
 
+    Type operandTy = opOperand.get().getType();
+
+    // Ranked container.
+    auto rankedTensorTy = dyn_cast<RankedTensorType>(operandTy);
+    auto memrefTy = dyn_cast<MemRefType>(operandTy);
+
+    // Unranked tensor is an "unknown rank".
+    bool unrankedTensor = isa<UnrankedTensorType>(operandTy);
+
+    // Other shaped (but not supported) types are invalid.
+    bool shapedButNotSupported = isa<ShapedType>(operandTy) &&
+                                 !rankedTensorTy && !memrefTy &&
+                                 !unrankedTensor && !isa<VectorType>(operandTy);
+
     // Result rank must match operand rank.
-    if (indexingMap.getNumResults() != rank)
+    if (indexingMap.getNumResults() != rank) {
+      // If this operand does not have a meaningful rank,
+      // emit a type-based diagnostic instead of a rank-based one.
+      if (unrankedTensor || shapedButNotSupported) {
+        return this->emitOpError("expected operand #")
+               << opOperand.getOperandNumber()
+               << " to be a ranked tensor or memref type to match the result "
+                  "rank of "
+                  "indexing_map ("
+               << indexingMap.getNumResults() << "), but got " << operandTy;
+      }
+
+      // Scalars/vectors (and true rank-0 cases).
       return this->emitOpError("expected operand #")
              << opOperand.getOperandNumber() << " rank (" << rank
              << ") to match the result rank of indexing_map ("
              << indexingMap.getNumResults() << ")";
+    }
 
     llvm::append_range(allShapesSizes, shape);
   }

```

**Comment by snarang181** [comment]
> I dont really like that, would be better to fix the rank computation. Even easier solution would be to emit some thing like "expeceted tensor or memref with rank {rank} to match the indexing map, got {type}" for all cases. But i dont think you need to worry about it in this pr anyway, just keep your original changes and ill fix that code later

Sounds good, reverted those changes.

**Review by sweiglbosker — APPROVED** [review]

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Instead of this can we add a verifier for `IndexMapOpInterface` that checks the operands are the expected type.

**Comment by snarang181** [comment]
> Instead of this can we add a verifier for `IndexMapOpInterface` that checks the operands are the expected type.

What if other code calls `getStaticOperand()`, `getRank()` without calling `verifyImpl()`, I am not sure how the current approach would look like.

File: mlir/lib/Interfaces/IndexingMapOpInterface.cpp [hunk 1]
```diff
@@ -14,6 +14,36 @@ namespace mlir {
 #include "mlir/Interfaces/IndexingMapOpInterface.cpp.inc"
 } // namespace mlir
 
+static LogicalResult verifyIndexingMapOperandType(Operation *op, Type t,
+                                                  unsigned operandNumber) {
+  // Scalars are allowed (treated as rank-0). verifyImpl checks the rank.
+  if (!isa<ShapedType>(t) && !isa<VectorType>(t))
```
Comment (MaheshRavishankar) [inline mlir/lib/Interfaces/IndexingMapOpInterface.cpp]: Thats too leaky, but it matches the check below.

**Review by MaheshRavishankar — APPROVED** [review]
