### PR TITLE
[clang-format] Skip line splices when sorting C++ includes

### LINKED ISSUE #109864: [clang-format] Regression: Include sorting is broken with backslashes in multiline comments.
Hi everyone, 

The latest released `clang-format` (19.1.5) cannot sort includes and remove duplicates if those are preceded with `/* */` comments containing backslashes. 

`clang-format` 18.1.8 produces correct results.

The problem can be reproduced regardless of the presence or contents of `.clang-format`.

Example:
```cpp
~ » cat a.cpp
/* COPYRIGHT *\
\* (C) 2024  */

#include <b>
#include <a>
#include <b>

~ » clang-format a.cpp
/* COPYRIGHT *\
\* (C) 2024  */

#include <b>
#include <a>
#include <b>

~ » cat b.cpp
/* COPYRIGHT *
 * (C) 2024  */

#include <b>
#include <a>
#include <b>

~ » clang-format b.cpp
/* COPYRIGHT *
 * (C) 2024  */

#include <a>
#include <b>
```

### PR DESCRIPTION
**Pull request by owenca**
Fixes #109864.

### CODE REVIEW

File: clang/lib/Format/Format.cpp [hunk 1]
```diff
@@ -3246,8 +3246,15 @@ tooling::Replacements sortCppIncludes(const FormatStyle &Style, StringRef Code,
   SmallVector<StringRef, 2> RawStringMatches;
   std::string RawStringTermination = ")\"";
 
-  for (;;) {
-    auto Pos = Code.find('\n', SearchFrom);
+  for (const auto Size = Code.size(); SearchFrom < Size;) {
```
Comment (rymiel) [inline clang/lib/Format/Format.cpp:3249]: Why is the extra `Size` variable needed? Why can't it stay as `for (;;)` ?

Comment (owenca) [reply clang/lib/Format/Format.cpp:3249]: Because it's used in `SearchFrom < Size`. My previous version using `for (;;)` caused a crash in ToolingTests.

**Review by mydeveloperday — APPROVED** [review]
