### PR TITLE
[Clang][Driver] report unsupported option error when link + compile in same process

### LINKED ISSUE #116278: [clang] `clang -mpopcnt hello.c <link flag>` fails to generate warning when file precedes link flag
on aarch64 darwin using the `-mpopcnt` flag will result in a warning on clang 16 and error on clang 19.1.3. however, if a linker flag trails the file name no warning / error is generated. eg:

```console
$ clang -mpopcnt hello.c -lc
$ ./a.out
hello world
```

however, re-ordering the command line so the file name comes after `-lc` will generate the expected error

```console
$ clang -mpopcnt -lc hello.c
clang: error: unsupported option '-mpopcnt' for target 'aarch64-apple-darwin'
```

this behavior is not seen with all link flags, eg `-flat_namespace` always will generate an error, but when used in conjunction with `-Wl` will generate an error (as do other flags, like `-v`)
```console
$ clang -mpopcnt -flat_namespace hello.c
clang: error: unsupported option '-mpopcnt' for target 'aarch64-apple-darwin'
$ clang -mpopcnt hello.c -flat_namespace
clang: error: unsupported option '-mpopcnt' for target 'aarch64-apple-darwin'
$ clang -mpopcnt -Wl,-flat_namespace hello.c
clang: error: unsupported option '-mpopcnt' for target 'aarch64-apple-darwin'
$ clang -mpopcnt hello.c -Wl,-flat_namespace
$ ./a.out
hello world
```

```console
$ clang -v
clang version 19.1.3
Target: aarch64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /nix/store/6b4vxqc16xq1nq8jhdsylfml244vah22-clang-19.1.3/bin
```

### PR DESCRIPTION
**Pull request by paparodeo**
Fixes: https://github.com/llvm/llvm-project/issues/116278

This change updates clang to report unsupported option errors regardless of the command line argument order.

When clang is invoked with a source file and without `-c` it will both compile and link. When an unsupported option is also part of the command line clang should generated an error. However, if the source file name comes before an object file, eg: `-lc`, the error is ignored.

```
$ clang --target=x86_64 -lc hello.c -mhtm
clang: error: unsupported option '-mhtm' for target 'x86_64'
$ echo $?
1
```

but if `-lc` comes after `hello.c` the error is dropped

```
$ clang --target=x86_64 hello.c -mhtm -lc
$ echo $?
0
```

after this change clang will report the error regardless of the command line argument order.

### CODE REVIEW

**Comment by paparodeo** [comment]
ping

**Comment by paparodeo** [comment]
Ping

File: clang/lib/Driver/Driver.cpp [hunk 1]
```diff
@@ -4129,10 +4130,8 @@ void Driver::handleArguments(Compilation &C, DerivedArgList &Args,
     }
   }
 
-  // If we are linking, claim any options which are obviously only used for
-  // compilation.
-  // FIXME: Understand why the last Phase List length is used here.
-  if (FinalPhase == phases::Link && LastPLSize == 1) {
+  // claim any options which are obviously only used for compilation.
```
Comment (MaskRay) [inline clang/lib/Driver/Driver.cpp:4133]: Capitalize this diagnostic

**Review by MaskRay — APPROVED** [review]
