### PR TITLE
[Clang] Do not skip over `RequiresExprBodyDecl` when creating lambdas

### LINKED ISSUE #147650: Error on use of NTTP in lambda in requires clause with same name as variable template
https://godbolt.org/z/3r8erG8dP

```cpp
template<int> int a;

template<int a> void f() requires requires { [] { a; }; } {}

int main() {}
```

```
<source>:3:51: error: use of variable template 'a' requires template arguments
    3 | template<int a> void f() requires requires { [] { a; }; } {}
      |                                                   ^
<source>:1:19: note: template is declared here
    1 | template<int> int a;
      | ~~~~~~~~~~~~~     ^
1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by cor3ntin**
When we create a lambda, we would skip over declaration contexts representing a require expression body, which would lead to wrong lookup.

Note that I wasn't able to establish why the code
in `Sema::createLambdaClosureType` was there to begin with (it's not exactly recent)

The changes to mangling only ensure the status quo is preserved and do not attempt to address the known issues of
mangling lambdas in require clauses.

In particular the itanium mangling is consistent with Clang before this patch but differs from GCC's.

Fixes #147650

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]

File: clang/lib/AST/ItaniumMangle.cpp [hunk 1]
```diff
@@ -1088,6 +1088,9 @@ void CXXNameMangler::mangleNameWithAbiTags(GlobalDecl GD,
     return;
   }
 
+  while (DC->isRequiresExprBody())
+    DC = DC->getParent();
```
Comment (mizvekov) [inline clang/lib/AST/ItaniumMangle.cpp:1092]: Is this sufficient? For example, what if the lambda is still nested in a requires body, but its parent is some other kind of DeclContext?

Comment (cor3ntin) [reply clang/lib/AST/ItaniumMangle.cpp:1092]: It is sufficient to fix this particular bug - it's more than likely that there are other issues with requires and mangling https://github.com/search?q=repo%3Allvm%2Fllvm-project+requires+lambda+is%3Aopen&type=issues 

I can't think of a scenario here though - you can only have expressions in a compound requirement (there are asserts to protect from any scenarios we might have missed)

Comment (zyn0217) [reply clang/lib/AST/ItaniumMangle.cpp:1092]: We had a similar while loop in TransformLambdaExpr, is that still needed?

Also I was going to ask if that high lambda patch could resolve these issues. But that still needs many iterations, so i think it's fine to just land the changes as is.

Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:1092]: With a compound expression you can introduce lots of other kinds of DeclContexts here.
