### PR TITLE
[analyzer] MallocChecker – Fix false positive leak for smart pointers in temporary objects

### LINKED ISSUE #60896: [clang-tidy]: potential memory leak when init struct field during construction
# To reproduce:

check out the minimal reproducer example at:
https://github.com/igagis/clang-tidy-test/blob/master/src/main.cpp

the relevant part of the code is:
```cpp
struct result{
    std::shared_ptr<std::string> p;
    bool some_other_field;
};

result potential_memory_leak_2(bool arg){
    result ret{.p = std::make_shared<std::string>("Hello world!")};

    if(arg){
        throw std::runtime_error("error");
    }

    return ret;
}
```

run `clang-tidy` with all checks on.

Or just refer to the minimal reproducer's CI run:
https://github.com/igagis/clang-tidy-test/actions/runs/4231046017/jobs/7349082519

# Expected result:
No false-positive potential memory leaks found

# Actual result:
The following error is reported by `clang-tidy`:
```
src/main.cpp:26:1: error: Potential leak of memory pointed to by field '_M_pi' [clang-analyzer-cplusplus.NewDeleteLeaks,-warnings-as-errors]
```

### PR DESCRIPTION
**Pull request by ivanmurashko**
## Summary

Fixes [PR60896](https://github.com/llvm/llvm-project/issues/60896) — false positive leak reports in various smart pointer scenarios including temporaries, inheritance, direct constructor calls, and mixed ownership patterns. Previously, the analyzer had no smart pointer handling in `checkPostCall`, causing it to report false positive leaks for memory properly managed by smart pointers while missing legitimate raw pointer leaks.

## Root Cause and Solution

The original `MallocChecker::checkPostCall()` implementation only handled existing post-call handlers and had no logic for smart pointer scenarios. This caused the analyzer to miss destructor calls for smart pointers in temporary objects, inheritance hierarchies, and direct constructor calls, leading to false positive leak reports for memory that would be properly freed by smart pointer destructors.

The solution implements comprehensive smart pointer detection in `checkPostCall` to identify smart pointer fields in by-value record arguments and direct constructor calls. Add targeted escape logic that only escapes symbols reachable from smart pointer field regions, preserving leak detection for raw pointers. Introduce `EscapeTrackedCallback` class to efficiently mark allocated symbols as escaped when managed by smart pointers. Create helper functions to detect smart pointer types (`unique_ptr`, `shared_ptr`) in both std and custom implementations. Extend field analysis to handle inheritance hierarchies and multiple smart pointer fields. Transform `checkPostCall` from simple post-handler dispatch to unified smart pointer processing while maintaining all existing functionality.

### CODE REVIEW

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 1]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+        isa<CXXConstructExpr>(AE) || isa<InitListExpr>(AE) ||
+        isa<ImplicitCastExpr>(AE) ||   // handle common rvalue materializations
+        isa<CXXBindTemporaryExpr>(AE); // handle CXXBindTemporaryExpr
+    if (!LooksLikeTemp)
+      continue;
+
+    // Require at least one direct smart owning pointer field by type.
+    const auto *CRD = T->getAsCXXRecordDecl();
+    if (!CRD)
+      continue;
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3221]: How can this fail if we already know its of a record type?
Wouldnt it be simpler to just do this earlier instead of checking the type?

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 2]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    bool HasSmartPtrField = false;
+    for (const FieldDecl *FD : CRD->fields()) {
+      if (isSmartOwningPtrType(FD->getType())) {
+        HasSmartPtrField = true;
+        break;
+      }
+    }
+    if (!HasSmartPtrField)
+      continue;
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3230]: This hunk should be hoisted into a dedicated function.
It could use `llvm::any_of` too.
That said, we would again, iterate over the fields later in `collectDirectSmartOwningPtrFieldRegions` if I'm not mistaken. That would again, filter for `isSmartOwningPtrType`.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 3]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+      // region, mark all allocated symbols as escaped
+      ProgramStateRef State = C.getState();
+      RegionStateTy RS = State->get<RegionState>();
+      ProgramStateRef NewState = State;
+      for (auto [Sym, RefSt] : RS) {
+        if (RefSt.isAllocated() || RefSt.isAllocatedOfSizeZero()) {
+          NewState =
+              NewState->set<RegionState>(Sym, RefState::getEscaped(&RefSt));
+        }
+      }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3250]: This does something very similar to `EscapeTrackedCallback`. Have you considered reusing some code?

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 4]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+  }
+}
+
 void MallocChecker::checkPostCall(const CallEvent &Call,
                                   CheckerContext &C) const {
+  // Keep existing post-call handlers.
   if (const auto *PostFN = PostFnMap.lookup(Call)) {
     (*PostFN)(this, C.getState(), Call, C);
-    return;
+  }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3188]: This `checkPostCall` was really simple, and would become a lot more complicated now.
I think we could do better to split things into named functions and separate concerns.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 5]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+      if (hasByValueRecordWithSmartPtr) {
+        ProgramStateRef State = C.getState();
+        RegionStateTy RS = State->get<RegionState>();
+        ProgramStateRef NewState = State;
+        for (auto [Sym, RefSt] : RS) {
+          if (RefSt.isAllocated() || RefSt.isAllocatedOfSizeZero()) {
+            NewState =
+                NewState->set<RegionState>(Sym, RefState::getEscaped(&RefSt));
+          }
+        }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3316]: There is a lot of code duplication again and again.
Please think about organizing the code to a more maintainable form.

File: clang/test/Analysis/NewDeleteLeaks-PR60896.cpp [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+
+// We use a custom implementation of unique_ptr for testing purposes
+template <typename T>
+struct unique_ptr {
+  T* ptr;
+  unique_ptr(T* p) : ptr(p) {}
+  ~unique_ptr() { delete ptr; }
+  unique_ptr(unique_ptr&& other) : ptr(other.ptr) { other.ptr = nullptr; }
+  T* get() const { return ptr; }
+};
```
Comment (steakhal) [inline clang/test/Analysis/NewDeleteLeaks-PR60896.cpp:22]: I'm pretty sure some header simulator already has a unique_ptr somewhere. We should use that.

File: clang/test/Analysis/NewDeleteLeaks-PR60896-shared.cpp [hunk 7]
```diff
@@ -0,0 +1,37 @@
+// RUN: %clang_analyze_cc1 -analyzer-checker=core,cplusplus,unix -verify %s
+// expected-no-diagnostics
+
```
Comment (steakhal) [inline clang/test/Analysis/NewDeleteLeaks-PR60896-shared.cpp:3]: Can we combine this test into the unique_ptr one? These two sort of cover the same subjects, so it would make more sense to me to test them in a single file, nearby to each other.

**Review by steakhal — CHANGES_REQUESTED** [review]
Hey, thanks for the PR. I can see that you spent some time thinking about this issue.
I see no fundamental issues with the proposed changes, except that we could improve the implementation a bit.
Thanks again!

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 8]
```diff
@@ -1096,6 +1100,41 @@ class StopTrackingCallback final : public SymbolVisitor {
...
+/// The visitor traverses reachable symbols from a given set of memory regions
+/// (typically smart pointer field regions) and marks any allocated symbols as
+/// escaped. Escaped symbols are not reported as leaks by checkDeadSymbols.
+///
+/// Usage:
+///   auto Scan =
+///   State->scanReachableSymbols<EscapeTrackedCallback>(RootRegions);
+///   ProgramStateRef NewState = Scan.getState();
+///   if (NewState != State) C.addTransition(NewState);
+class EscapeTrackedCallback final : public SymbolVisitor {
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Updated as suggested: constructor is now private, added EscapeTrackedRegionsReachableFrom() static helper, and replaced direct visitor usage with the new helper.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 9]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+
+static bool isInStdNamespace(const DeclContext *DC) {
+  while (DC) {
+    if (const auto *NS = dyn_cast<NamespaceDecl>(DC))
+      if (NS->isStdNamespace())
+        return true;
+    DC = DC->getParent();
+  }
+  return false;
+}
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Removed custom isInStdNamespace; now using isWithinStdNamespace from CheckerHelpers.h.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 10]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+      return false;
+
+    const auto *ND = dyn_cast_or_null<NamedDecl>(TD->getTemplatedDecl());
+    if (!ND)
+      return false;
+
+    // Check if it's in std namespace
+    const DeclContext *DC = ND->getDeclContext();
+    if (!isInStdNamespace(DC))
+      return false;
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Updated to pass NamedDecl * directly to isWithinStdNamespace

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 11]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+  if (RT) {
+    const auto *RD = RT->getDecl();
+    if (RD) {
+      StringRef Name = RD->getName();
+      if (Name == "unique_ptr" || Name == "shared_ptr") {
+        // Accept any custom unique_ptr or shared_ptr implementation
+        return true;
+      }
+    }
+  }
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Replaced manual logic with QualType::getAsCXXRecordDecl()

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 12]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    // By-value record only (no refs).
+    if (!T->isRecordType() || T->isReferenceType())
+      continue;
+
+    // **Relaxation 2**: accept common temp/construct forms but don't overfit.
+    const bool LooksLikeTemp =
+        isa<CXXTemporaryObjectExpr>(AE) || isa<MaterializeTemporaryExpr>(AE) ||
+        isa<CXXConstructExpr>(AE) || isa<InitListExpr>(AE) ||
+        isa<ImplicitCastExpr>(AE) ||   // handle common rvalue materializations
+        isa<CXXBindTemporaryExpr>(AE); // handle CXXBindTemporaryExpr
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Combined into single isa<T1, T2, ...> call

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 13]
```diff
@@ -3107,24 +3111,13 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
-  while (DC) {
-    if (const auto *NS = dyn_cast<NamespaceDecl>(DC))
-      if (NS->isStdNamespace())
-        return true;
-    DC = DC->getParent();
-  }
-  return false;
-}
+// Use isWithinStdNamespace from CheckerHelpers.h instead of custom
+// implementation
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3115]: Is this comment still relevant?

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 14]
```diff
@@ -1096,6 +1098,47 @@ class StopTrackingCallback final : public SymbolVisitor {
...
+public:
+  /// Escape tracked regions reachable from the given roots.
+  static ProgramStateRef
+  EscapeTrackedRegionsReachableFrom(ArrayRef<const MemRegion *> Roots,
+                                    ProgramStateRef State) {
+    EscapeTrackedCallback Visitor(State);
+    for (const MemRegion *R : Roots) {
+      State->scanReachableSymbols(loc::MemRegionVal(R), Visitor);
+    }
+    return Visitor.getState();
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1128]: scanReachableSymbols is really expensive. Can't you invoke it only once and just pass Roots to it?

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 15]
```diff
@@ -1096,6 +1098,47 @@ class StopTrackingCallback final : public SymbolVisitor {
...
+  }
+
+  ProgramStateRef getState() const { return State; }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1131]: I suppose we no longer need this.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 16]
```diff
@@ -1096,6 +1098,47 @@ class StopTrackingCallback final : public SymbolVisitor {
...
+
+  bool VisitSymbol(SymbolRef Sym) override {
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1133]: This can be in the private part, if we made `SymbolVisitor` friend.

**Review by steakhal — CHANGES_REQUESTED** [review]
I like the progress. It's definitely going in the right direction.
Keep it up!

**Review by pskrgag — COMMENTED** [review]
Thanks for your work!

I am more C person, so I might be missing some CXX semantics. Except for nits left above patch LGTM.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 17]
```diff
@@ -3068,11 +3107,217 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+  if (!CRD)
+    return;
+
+  for (const FieldDecl *FD : CRD->fields()) {
+    if (!isSmartOwningPtrType(FD->getType()))
+      continue;
+    SVal L = C.getState()->getLValue(FD, loc::MemRegionVal(Base));
+    if (const MemRegion *FR = L.getAsRegion())
+      Out.push_back(FR);
+  }
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3219]: Added base class field support: hasSmartPtrField and collectDirectSmartOwningPtrFieldRegions now recurse into base classes (including virtual). Added base_class_smart_ptr_PR60896 test to verify no false positives for inherited smart pointer fields.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 2 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Addressed — the smart pointer field check is now hoisted into a dedicated `hasSmartPtrField` helper using `llvm::any_of`, and we avoid duplicate iteration by only calling `collectDirectSmartOwningPtrFieldRegions` if the check passes.

File: clang/test/Analysis/NewDeleteLeaks-PR60896.cpp (hunk 6 above)
Comment (ivanmurashko) [reply clang/test/Analysis/NewDeleteLeaks-PR60896.cpp]: I looked at system-header-simulator-cxx.h — it has unique_ptr, but without a destructor implementation. For correctness, I kept the custom unique_ptr in the test to ensure proper leak modeling.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 18]
```diff
@@ -3068,11 +3111,174 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+// implementation
+
+// Allowlist of owning smart pointers we want to recognize.
+// Start with unique_ptr and shared_ptr. (intentionally exclude weak_ptr)
+static bool isSmartOwningPtrType(QualType QT) {
+  QT = QT->getCanonicalTypeUnqualified();
+
+  // First try TemplateSpecializationType (for std smart pointers)
+  const auto *TST = QT->getAs<TemplateSpecializationType>();
+  if (TST) {
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Applied

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 19]
```diff
@@ -52,6 +52,7 @@
 #include "clang/AST/DeclTemplate.h"
 #include "clang/AST/Expr.h"
 #include "clang/AST/ExprCXX.h"
+
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Applied

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 13 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: I removed the comment - not needed anymore

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 16 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: I moved `VisitSymbol` to the private part of the class

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 20]
```diff
@@ -3068,11 +3111,174 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    if (!isRvalueByValueRecordWithSmartPtr(AE))
+      continue;
+
+    // Find a region for the argument.
+    SVal VCall = Call.getArgSVal(I);
+    SVal VExpr = C.getSVal(AE);
+    const MemRegion *RCall = VCall.getAsRegion();
+    const MemRegion *RExpr = VExpr.getAsRegion();
+
+    const MemRegion *Base = RCall ? RCall : RExpr;
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: You are absolutely right - that one was fixed

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 21]
```diff
@@ -3068,11 +3111,174 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    if (!Base) {
+      // Fallback: if we have a by-value record with smart pointer fields but no
+      // region, mark all allocated symbols as escaped
+      ProgramStateRef State = C.getState();
+      ProgramStateRef NewState = escapeAllAllocatedSymbols(State);
+      if (NewState != State)
+        C.addTransition(NewState);
+      continue;
+    }
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: I refactored that part of the code and addressed the comment. Especially, I removed the comparison and just set `needsStateUpdate = true` when we know we need a state change

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 22]
```diff
@@ -3068,11 +3110,195 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+        AE = AE->IgnoreParenImpCasts();
+
+        if (isRvalueByValueRecordWithSmartPtr(AE)) {
+          hasByValueRecordWithSmartPtr = true;
+          break;
+        }
+      }
+
+      if (hasByValueRecordWithSmartPtr) {
+        State = escapeAllAllocatedSymbols(State);
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3293]: Wow, there is an issue, and the behaviour is not what was expected from the patch. I need to add the corresponding test and fix for the problem.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 14 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Fixed

**Comment by pskrgag** [comment]
I am sorry, looks like I found another regression:

```cpp

#include <memory>

struct Foo {
  std::unique_ptr<int> ptr;
  int *raw;

  Foo() : ptr(std::make_unique<int>(1)), raw(new int) {}
};

void add(Foo foo) {}

int main(int argc, const char **argv) {
  add(Foo());
  return 0;
}
```

With your patch applied `raw` leak is not reported, however current CSA finds it: https://godbolt.org/z/569x11e7a.

I didn't trace why it happens, will be able to come back tomorrow.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (pskrgag) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Thansk!

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 5 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: The code was refactored and duplication was removed

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 23]
```diff
@@ -3068,12 +3125,235 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+  }
+
+  return false;
+}
+
+/// Check if a call is a smart pointer constructor call that takes ownership
+/// of pointer arguments.
+static bool isSmartPtrCall(const CallEvent &Call) {
+  // Only check for smart pointer constructor calls
+  if (const auto *CD = dyn_cast_or_null<CXXConstructorDecl>(Call.getDecl())) {
```
Comment (pskrgag) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3223]: nit: I think, early returns would make function more readable.

**Review by pskrgag — APPROVED** [review]
Thanks! I've left only one small nit.

LGTM!

File: clang/test/Analysis/NewDeleteLeaks-PR60896.cpp [hunk 24]
```diff
@@ -0,0 +1,80 @@
...
+
+void add(Foo foo) {
+  // The shared_ptr destructor will be called when foo goes out of scope
+}
+
+void test() {
+  // No warning should be emitted for this - the memory is managed by shared_ptr 
+  // in the temporary Foo object, which will properly clean up the memory
+  add({make_shared<int>(1)});
+}
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/test/Analysis/NewDeleteLeaks-PR60896.cpp]: Done! Added test case with multiple memory owning arguments and fixed the `addTransition` API misuse using early return when post-handlers exist. All tests pass.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 25]
```diff
@@ -3068,12 +3124,240 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+  // Handle existing post-call handlers first
   if (const auto *PostFN = PostFnMap.lookup(Call)) {
     (*PostFN)(this, C.getState(), Call, C);
-    return;
+    return; // Post-handler already called addTransition, we're done
   }
+
+  // Handle smart pointer related processing only if no post-handler was called
+  ProgramStateRef State = handleSmartPointerRelatedCalls(Call, C, C.getState());
+  C.addTransition(State);
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3360]:
```suggestion
  C.addTransition(handleSmartPointerRelatedCalls(Call, C, C.getState()));
```

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 26]
```diff
@@ -3068,12 +3124,240 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+      return true;
+    }
+  }
+
+  return false;
+}
+
+static void collectDirectSmartOwningPtrFieldRegions(
+    const MemRegion *Base, QualType RecQT, CheckerContext &C,
+    SmallVectorImpl<const MemRegion *> &Out) {
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3246]: Shouldnt `out` have set semantics?

**Review by steakhal — COMMENTED** [review]
I think it looks pretty good. A lot of improvements!

I don't think I have the time to do a proper focused review, so I'd at this point forward you to @NagyDonat to finish the reviews.

**Comment by steakhal** [comment]
One more comment. Please don't use force-pushes on GitHub. That ruins the review experience. Use merges instead, and never break your commit history chain.

Another remark would be to add the commit hash to the reply comment where you say that something was fixed. That way the reviewer can easily click on the commit and verify that yes, indeed it was fixed in the right way.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 27]
```diff
@@ -3068,12 +3124,240 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    if (ParamType->isPointerType() && !ParamType->isFunctionPointerType() &&
+        !ParamType->isVoidPointerType()) {
+      return true;
+    }
+  }
+
+  return false;
+}
+
+static void collectDirectSmartOwningPtrFieldRegions(
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Good catch! You're absolutely right. I've renamed the function from `collectDirectSmartOwningPtrFieldRegions` to `collectSmartOwningPtrFieldRegions` to better reflect that it now traverses the entire inheritance hierarchy, not just direct fields (commit a166bb306961).

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 26 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Good point! I've changed the parameter to use `llvm::SmallPtrSetImpl<const MemRegion *>` to ensure each region is only collected once, preventing duplicates from inheritance traversal (commit a166bb306961).

**Comment by ivanmurashko** [comment]
Thanks for the feedback! I've already added the commit hashes to my responses above. I'll avoid force-pushes going forward and use merges to preserve the commit history.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 28]
```diff
@@ -3068,12 +3124,242 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+      return false;
+
+    return isSmartPtrName(ND->getName());
+  }
+
+  // Also try RecordType (for custom smart pointer implementations)
+  if (const auto *RD = QT->getAsCXXRecordDecl()) {
+    // Accept any custom unique_ptr or shared_ptr implementation
+    return isSmartPtrName(RD->getName());
+  }
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3158]: What is the practical purpose of this block?

As far as I see this block returns `true` when it encounters non-template classes named `unique_ptr` or `shared_ptr`, and I don't think that this is an established coding pattern which deserves a separate branch. Is this a block that will never be entered during real-world use of the analyzer or do I misunderstand something here?

(If I understand correctly your tests rely on this branch, but I think it's inelegant to tweak the behavior of the actual software in order to slightly simplify the test code. I would prefer using [or writing] a suitable system header simulator.)

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 29]
```diff
@@ -3194,7 +3480,6 @@ void MallocChecker::checkEscapeOnReturn(const ReturnStmt *S,
   if (!Sym)
     // If we are returning a field of the allocated struct or an array element,
     // the callee could still free the memory.
-    // TODO: This logic should be a part of generic symbol escape callback.
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3197]: Is this just a random obsolete TODO, or is it fixed by the this PR? (No action excepted, just curious.)

**Review by NagyDonat — COMMENTED** [review]
I reviewed the code changes within this commit, and overall I'm very grateful for this contribution, because it overcomes lots of technical challenges to introduce a promising heuristic.

As this code is unavoidable complex, I think it's especially important to make it _as readable as possible_, so I added several suggestions that try to improve the code quality. I understand that you are probably a bit tired after implementing this impressive commit (and getting through suggestions from other reviewers), so I'm sorry for piling on these additional suggestions. If you feel that some of them are unreasonable, feel free to "push back" -- I'll try to be flexible.

So far I only read the changes in `MallocChecker.cpp`, but I'll also review the tests soon.

Unfortunately I didn't have time to look at the resolved discussion by other reviewers, I'm very sorry if I'm revisiting some topic that was already discussed there.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 30]
```diff
@@ -3068,12 +3124,242 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+    if (!TD)
+      return false;
+
+    const auto *ND = dyn_cast_or_null<NamedDecl>(TD->getTemplatedDecl());
+    if (!ND)
+      return false;
+
+    // Check if it's in std namespace
+    if (!isWithinStdNamespace(ND))
+      return false;
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: I removed the namespace std checks consistently across all smart pointer detection paths to provide broader coverage and reduce false positives, see 08a24effa0007135844fb37d0ecf6e8f1972a45b

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 28 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Good catch! You're absolutely right. The RecordType fallback became redundant after the constructor-based detection was introduced in bb5eacc79dc69. The constructor mechanism (`handleSmartPointerConstructorArguments`) now properly handles both template and non-template smart pointers, making the RecordType branch unnecessary. That's why I removed it in 08a24effa0007135844fb37d0ecf6e8f1972a45b.

**Review by NagyDonat — COMMENTED** [review]
Thanks for updating the commit!

I reviewed the tests and added some minor suggestions in the implementation.

Among my earlier suggestions [the visibility of VisitSymbol](https://github.com/llvm/llvm-project/pull/152751/files#r2301055454) and the [complex code duplication question](https://github.com/llvm/llvm-project/pull/152751/files#r2301561854) are still relevant.

Moreover I thought about the approach that you currently emphasize "owning" in every name and comment where you speak about smart pointers. As this is not a distinguishing feature of these functions (you never interact with non-owning smart pointers) and these function names tend to be very long, I think it would be better to omit "owning" from these names. It is enough to mention the exclusion of `weak_ptr` in a single comment (next to the function that recognizes the names of the smart pointer classes).

**Comment by steakhal** [comment]
> > > > I don't think I have the time to do a proper focused review, so I'd at this point forward you to @NagyDonat to finish the reviews.
> > > 
> > > 
> > > @steakhal The "Requested change" review status is still active from your old review. Is it just a github glitch?
> > 
> > Im on vacation. I do not track this PR. Merge it if you want.
> 
> Thanks for the information, and sorry for pinging you while on vacation. We'll merge this when the ongoing discussion is finished.

I still cant hold myself from looking at things once or twice a day, but I'm very careful of when I react to something.

**Comment by ivanmurashko** [comment]
Thanks for the review, @NagyDonat. I am still working on addressing the "duplicates the traversal logic" comment and will return to the other comments right after the commit that addresses this major part of the refactoring. Overall, I plan to address all comments by the end of the week and have everything ready for review by Monday.

> 
> I reviewed the tests and added some minor suggestions in the implementation.

Thank you very much. 

> 
> Among my earlier suggestions [the visibility of VisitSymbol](https://github.com/llvm/llvm-project/pull/152751/files#r2301055454) 

Ah, I am very sorry—it looks like my change was missed there. I will definitely add it.

> and the [complex code duplication question](https://github.com/llvm/llvm-project/pull/152751/files#r2301561854) are still relevant.
> 
> Moreover I thought about the approach that you currently emphasize "owning" in every name and comment where you speak about smart pointers. As this is not a distinguishing feature of these functions (you never interact with non-owning smart pointers) and these function names tend to be very long, I think it would be better to omit "owning" from these names. It is enough to mention the exclusion of `weak_ptr` in a single comment (next to the function that recognizes the names of the smart pointer classes).

I also had doubts when choosing between the naming: with or without "Owning." I think it will be better to omit the word "Owning" to keep the names as simple as possible.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 29 above)
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3197]: The change is not directly related to the PR. I believe that the TODO comment became obsolete a long time ago, and I deleted it for that reason. 

The TODO comment was added in February 2012 (see 4ca45b1d00e97c590bc1bf012bd35b1f73926565) when fixing a false positive in the malloc checker related to returning fields of allocated structs or array elements via pointer arithmetic. The author of the commit embedded escape-on-return logic directly in `checkPreStmt` but recognized this was architecturally suboptimal, suggesting it should be part of a "generic symbol escape callback" instead.

This TODO was rendered unnecessary when commit 122171e235827 refactored the code by extracting the escape logic into a dedicated `checkEscapeOnReturn` method that could be reused by multiple callbacks (`checkPreStmt` and `checkEndFunction`). This addressed the architectural concern without requiring a complete redesign of the symbol escape callback system.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 31]
```diff
@@ -3068,12 +3124,225 @@ void MallocChecker::checkDeadSymbols(SymbolReaper &SymReaper,
...
+        !ParamType->isVoidPointerType()) {
+      return true;
+    }
+  }
+
+  return false;
+}
+
+static void collectSmartOwningPtrFieldRegions(
+    const MemRegion *Base, QualType RecQT, CheckerContext &C,
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Good point. I applied the name change in 49b7d31d174559b343d83a3629b35e03a36d96e0.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 32]
```diff
@@ -1096,6 +1104,54 @@ class StopTrackingCallback final : public SymbolVisitor {
...
+///
+/// The visitor traverses reachable symbols from a given set of memory regions
+/// (typically smart pointer field regions) and marks any allocated symbols as
+/// escaped. Escaped symbols are not reported as leaks by checkDeadSymbols.
+class EscapeTrackedCallback final : public SymbolVisitor {
+  ProgramStateRef State;
+
+  explicit EscapeTrackedCallback(ProgramStateRef S) : State(std::move(S)) {}
+
+  bool VisitSymbol(SymbolRef Sym) override {
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1126]: That's my bad. I hope that I finally addressed that in 64d3aef5bf2058ed6ba92cbdc6ce9ce362de8900

**Comment by ivanmurashko** [comment]
> Moreover I thought about the approach that you currently emphasize "owning" in every name and comment where you speak about smart pointers. As this is not a distinguishing feature of these functions (you never interact with non-owning smart pointers) and these function names tend to be very long, I think it would be better to omit "owning" from these names. It is enough to mention the exclusion of `weak_ptr` in a single comment (next to the function that recognizes the names of the smart pointer classes).

I eliminated the "owning" word in commit 692db9e74c0cd11e24d01777d28849151250edd7

File: clang/test/Analysis/NewDeleteLeaks-PR60896.cpp [hunk 33]
```diff
@@ -187,12 +202,12 @@ void test_variadic_constructor_bounds() {
   // The constructor has 1 formal parameter (T* p) plus ellipsis, but we pass multiple args
   // This should trigger the bounds checking issue in handleSmartPointerConstructorArguments
   int* raw_ptr = new int(42);
-  process_variadic_smart_ptr(VariadicSmartPtr<int>(raw_ptr, 1, 2, 3, 4, 5));
+  process_variadic_smart_ptr(unique_ptr<int>(raw_ptr, 1, 2, 3, 4, 5));
   
   (void)malloc_ptr;
 } // expected-warning {{Potential leak of memory pointed to by 'malloc_ptr'}} expected-note {{Potential leak of memory pointed to by 'malloc_ptr'}}
```
Comment (NagyDonat) [inline clang/test/Analysis/NewDeleteLeaks-PR60896.cpp:208]:
```suggestion
} // expected-warning {{Potential leak of memory pointed to by 'malloc_ptr'}}
  // expected-note@-1 {{Potential leak of memory pointed to by 'malloc_ptr'}}
```
It is possible to move an `expected-` markers onto a different line (by adding `@` + relative line number) and it may be a nice touch on long lines like this.

**Review by NagyDonat — APPROVED** [review]
Thanks for all the updates!

I think the change is basically ready to merge, but I added two very minor suggestions in inline comments.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 34]
```diff
@@ -3145,27 +3144,71 @@ static bool isSmartOwningPtrType(QualType QT) {
...
+      return FieldConsumer{BaseObjRegion, *C, *Out};
+    }
+    return std::nullopt;
+  }
+};
+
 /// Check if a record type has smart owning pointer fields (directly or in base
-/// classes).
-static bool hasSmartOwningPtrField(const CXXRecordDecl *CRD) {
+/// classes). When FC is provided, also collect the field regions.
```
[the remark this answers is not in the document]
Comment (ivanmurashko) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: @ NagyDonat, Good point! Added documentation explaining this dual behavior in 196abdb3e4bd4eced37933ddf2d351bf3a39320e. When FC is provided, the return value should be ignored since it always returns false for full traversal.

[the remark this answers is not in the document]
Comment (NagyDonat) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Thanks!
