### PR TITLE
[Clang] Fix incorrect mutability of decltype((x)) in lambda return types

### LINKED ISSUE #180460: Incorrect type deduction in a non-mutable lambda that captures by value
The C++23 standard has an example showing how types are deduced in a lambda: https://timsong-cpp.github.io/cppwp/n4950/expr.prim.id.unqual#example-1. Relevant parts of the example are reproduced below.

```cpp
void f() {
  float x;

  [=]() -> decltype((x)) {      // lambda returns float const& because this lambda is not mutable and
                                // x is an lvalue
    decltype(x) y1;             // y1 has type float
    decltype((x)) y2 = y1;      // y2 has type float const&
    return y2;
  };
}
```

This example fails to compile with clang https://godbolt.org/z/zqEsa7T8f.

```
<source>:21:12: error: binding reference of type 'float' to value of type 'const float' drops 'const' qualifier
   21 |     return y2;
      |            ^~
```

Clang replaces `decltype((x))` with `float&` in the _trailing-return-type_. However, in the _compound-statement_, `decltype((x))` is replaced with `const float&`. This causes the compilation to fail.

It seems that clang is still looking at the outside `x` and not the `x` in the closure generated by the lambda when evaluating the `decltype` in the _trailing-return-type_.

### PR DESCRIPTION
**Pull request by samrudhnelli**
Previously, the parser did not update the lambda's mutability state before parsing the trailing return type. This caused decltype((x)) to incorrectly deduce a non-const reference even in a non-mutable lambda.
Fixes #180460

### CODE REVIEW

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 1]
```diff
@@ -1383,6 +1383,9 @@ ExprResult Parser::ParseLambdaExpressionAfterIntroducer(
     addStaticToLambdaDeclSpecifier(*this, StaticLoc, DS);
     addConstexprToLambdaDeclSpecifier(*this, ConstexprLoc, DS);
     addConstevalToLambdaDeclSpecifier(*this, ConstevalLoc, DS);
+    if (clang::sema::LambdaScopeInfo *LSI = Actions.getCurLambda()) {
+      LSI->Mutable = MutableLoc.isValid();
+    }
```
Comment (cor3ntin) [inline clang/lib/Parse/ParseExprCXX.cpp]: This is not quite correct. My guess is that we should call `ActOnLambdaClosureQualifiers` (that call is currently on line 1451) before calling `ParseTrailingReturnType` (instead of after) (starting on line 1425)

@zyn0217

**Review by zyn0217 — APPROVED** [review]
Thanks

**Review by cor3ntin — APPROVED** [review]

**Comment by SamrudhNelli** [comment]
Hi @cor3ntin @zyn0217, thank you for your help in solving the issue!! 
Since the PR is now approved, should I rebase and squash the branch? 
If not, could you please merge it when you have a moment, as I don’t have commit access to the repository? Thanks.
