### PR TITLE
[win/arm64] Enable tail call with inreg arguments when possible

### LINKED ISSUE #133098: aarch64-pc-windows: failed to perform tail call elimination on a call site marked musttail
Consider:

```
$ cat /tmp/a.ii
struct S {};

struct T {
  S Foo(S);
  S Get(S);
};

S T::Get(S key) {
  [[clang::musttail]] return Foo(key);
}

$ clang -cc1 -triple aarch64-pc-windows-msvc19.34.0 -emit-obj /tmp/a.ii
fatal error: error in backend: failed to perform tail call elimination on a call site marked musttail
```

(Other aarch64 triples, such as aarch64-unknown-unknown, work.)

### PR DESCRIPTION
**Pull request by zmodem**
Tail calls were disabled from callers with inreg parameters in 5dc8aeb with a fixme to check if the callee also takes an inreg parameter.

The issue is that inreg parameters (which are passed in x0 or x1 for free and member functions respectively) are supposed to be returned (in x0) at the end of the function. In case of a tail call, that means the callee needs to return the same value as the caller would.

We can check for that case, and it's not as niche as it sounds, as that's how Clang will lower one function with an sret return value calling another, such as:

```
struct T { int x; };
struct S {
    T foo();
    T bar();
};
T S::foo() { return bar(); } // foo's sret argument will get passed directly to bar
```

Fixes #133098

### CODE REVIEW

**Comment by mstorsjo** [comment]
TBH I'm not sure that I can give a very useful review here, as I'm not very familiar with these aspects. But your reasoning sounds sensible.

As for the reduced testcase:

> struct T { int x; };
> struct S {
>     T foo();
>     T bar();
> };
> T S::foo() { return bar(); } // foo's sret argument will get passed directly to bar

This is kinda beside the point, but for purposes of getting a minimal repro, isn't the structure `S` unnecessary here - wouldn't this be reproducible with two plain global functions as well? Or does the implicit `this` pointer affect the calling conventions of the methods, necessary for triggering this case?

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -8703,13 +8703,19 @@ bool AArch64TargetLowering::isEligibleForTailCallOptimization(
...
-      return false;
+    // In this case, it is necessary to save X0/X1 in the callee and return it
+    // in X0. Tail call opt may interfere with this, so we disable tail call
+    // opt when the caller has an "inreg" attribute -- except if the callee
+    // also has that attribute on the same argument, and the same value is
+    // passed.
+    if (i->hasInRegAttr()) {
+      unsigned ArgNum = i - CallerF.arg_begin();
+      if (!CLI.CB || CLI.CB->arg_size() <= ArgNum ||
+          !CLI.CB->getParamAttr(ArgNum, Attribute::InReg).isValid() ||
```
Comment (efriedma-quic) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:8714]: I think this should check that both the caller and callee argument are also marked "sret", since that matches the check in the calling convention specification.

Otherwise, this is reasonable, I guess.  Checking that the argument is a specific llvm::Value* is a little gross, but I guess that's the best we can do given the way "sret" is defined.

Comment (rnk) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:8714]: This is also re-checking invariants that have already been checked for musttail calls by the verifier (matching the prototype and inreg / sret attributes). 

Can we skip this whole loop if `CLI.CB && CLI.CB->isMustTailCall()` is true? I haven't reviewed aarch64 byval, but musttail ensures the stack memory lines up, making it significantly easier to implement correctly.

Comment (zmodem) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:8714]: > I think this should check that both the caller and callee argument are also marked "sret"

Done.

> Can we skip this whole loop if `CLI.CB && CLI.CB->isMustTailCall()` is true?

As Eli said, I think some of the checks are redundant for musttail, but not all. And I want regular "no-must" tail calls to work too, so I'm not sure that it would make the code simpler.

**Comment by zmodem** [comment]
> wouldn't this be reproducible with two plain global functions as well?

Yes, but we have to tweak the return type a little to get the `inreg` attribute: https://github.com/llvm/llvm-project/blob/2c1bdd4a0811af89eb9631935fbd90f13a04eacb/clang/lib/CodeGen/MicrosoftCXXABI.cpp#L1185-L1187

```
struct T { ~T(); };
T bar();
T foo() { return bar(); }
```

(MSVC doesn't seem to do the tail call either: https://godbolt.org/z/ofzebfd9P)

**Comment by mstorsjo** [comment]
> > wouldn't this be reproducible with two plain global functions as well?
> 
> Yes, but we have to tweak the return type a little to get the `inreg` attribute:
> 
> https://github.com/llvm/llvm-project/blob/2c1bdd4a0811af89eb9631935fbd90f13a04eacb/clang/lib/CodeGen/MicrosoftCXXABI.cpp#L1185-L1187

Oh, tricky! Sorry for the distraction here, then. :-)

**Review by efriedma-quic — APPROVED** [review]
LGTM
