### PR TITLE
[RISCV] Check VL dominates and potentially move in tryReduceVL

### LINKED ISSUE #106735: Error in RISC-V Vector Peephole Optimization (riscv-vector-peephole) pass
Running ` llc -mtriple=riscv64 -mattr=+v` with this snippet as input
```
define void @foo(ptr %a, i32 zeroext %avl) {
  %sp = call <vscale x 8 x i8> @llvm.stepvector()
  %evl = call i32 @llvm.experimental.get.vector.length(i32 %avl, i32 8, i1 true)
  call void @llvm.vp.store(<vscale x 8 x i8> %sp, ptr %a, <vscale x 8 x i1> splat(i1 true), i32 %evl)
  ret void
}

declare <vscale x 8 x i8> @llvm.stepvector()
declare void @llvm.vp.store(<vscale x 8 x i8>, ptr, <vscale x 8 x i1>, i32)
declare i32 @llvm.experimental.get.vector.length(i32, i32, i1)
```
causes a crash. I do believe the problem is a use-before-def one caused by the `riscv-vector-peephole` pass, because adding the `-print-changed` flag I can see:
```
*** IR Dump After RISC-V DAG->DAG Pattern Instruction Selection (riscv-isel) on foo ***
# Machine code for function foo: IsSSA, TracksLiveness
Function Live Ins: $x10 in %0, $x11 in %1

bb.0 (%ir-block.0):
  liveins: $x10, $x11
  %1:gprnox0 = COPY $x11
  %0:gpr = COPY $x10
  %2:vr = PseudoVID_V_M1 $noreg(tied-def 0), -1, 3, 1
  %3:gprnox0 = PseudoVSETVLI %1:gprnox0, 192, implicit-def dead $vl, implicit-def dead $vtype
  PseudoVSE8_V_M1 killed %2:vr, %0:gpr, killed %3:gprnox0, 3 :: (store unknown-size into %ir.a, align 8)
  PseudoRET

# End machine code for function foo.

*** IR Dump After Finalize ISel and expand pseudo-instructions (finalize-isel) on foo omitted because no change ***
*** IR Dump After RISC-V Vector Peephole Optimization (riscv-vector-peephole) on foo ***
# Machine code for function foo: IsSSA, TracksLiveness
Function Live Ins: $x10 in %0, $x11 in %1

bb.0 (%ir-block.0):
  liveins: $x10, $x11
  %1:gprnox0 = COPY $x11
  %0:gpr = COPY $x10
  %2:vr = PseudoVID_V_M1 $noreg(tied-def 0), %3:gprnox0, 3, 1
  %3:gprnox0 = PseudoVSETVLI %1:gprnox0, 192, implicit-def dead $vl, implicit-def dead $vtype
  PseudoVSE8_V_M1 killed %2:vr, %0:gpr, killed %3:gprnox0, 3 :: (store unknown-size into %ir.a, align 8)
  PseudoRET

# End machine code for function foo.
...
```
where the `PseudoVID` got its vector lenght argument changed from VLMax (`-1`) to `%3:gprnox0`, which is defined on the next line.

/cc @lukel97

### PR DESCRIPTION
**Pull request by lukel97**
Similar to what we do in foldVMV_V_V with the passthru, if we end up changing the Src's VL in tryReduceVL we need to make sure it dominates.

Fixes #106735

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp [hunk 1]
```diff
@@ -456,6 +460,26 @@ static bool dominates(MachineBasicBlock::const_iterator A,
...
+                                          MachineInstr &Src) const {
+  assert(MO.getParent()->getParent() == Src.getParent());
+  if (!MO.isReg() || MO.getReg() == RISCV::NoRegister)
+    return true;
+
+  MachineInstr *Def = MRI->getVRegDef(MO.getReg());
+  if (Def->getParent() == Src.getParent() && !dominates(Def, Src)) {
+    if (!isSafeToMove(Src, *Def->getNextNode()))
+      return false;
+    // FIXME: Update V0Defs
```
Comment (preames) [inline llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp:476]: Noticing the FIXME.  I assume this is something you noticed when inspecting the code?  How can a VL (scalar) be a VO (vector) register def?  And if it's safe to move, doesn't that guarantee the reaching VO is the same?

**Review by preames — APPROVED** [review]
LGTM

This was really my bug, so thanks for jumping on it before I did.

File: llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp (hunk 1 above)
Comment (lukel97) [reply llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp:476]: V0Defs stores the current definition of V0 at each instruction, so this is about updating the current value at Src if we move it.

isSafeToMove checks that any physical register uses aren't clobbered, so if Src doesn't use V0 then it might be moved past a new V0 def.

So masked pseudos won't get moved currently and I don't think we miscompile anything, but we probably do our bookkeeping here anyway.

**Comment by lukel97** [comment]
It slipped past my review too so I think I'm also partly to blame!

File: llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp (hunk 1 above)
Comment (preames) [reply llvm/lib/Target/RISCV/RISCVVectorPeephole.cpp:476]: Other option is to only add instructions which have a mask use to the mapping, then moving source wouldn't need to update the mapping.  Would also keep the mapping (much) smaller.
