### PR TITLE
[OpenMP] Fix crash when diagnosing dist_schedule

### LINKED ISSUE #139266: [OpenMP] Assertion `Idx < getNumArgs() && "Argument index out of range!"' failed.
Reproducible on Godbolt:
https://godbolt.org/z/jjxM8vqYj
```cpp
void f(void) {
#pragma omp distribute dist_schedule(static, 0)
  for (int i = 0; i < 10; i++)
    ;
}
```

### PR DESCRIPTION
**Pull request by AaronBallman**
We were failing to pass a required argument when emitting the diagnostic, so the source range was being used in place of an index. This caused a failed assertion due to the incorrect index.

Fixes #139266

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]

**Review by alexey-bataev — APPROVED** [review]

File: clang/test/OpenMP/teams_distribute_dist_schedule_messages.cpp [hunk 1]
```diff
@@ -105,3 +105,11 @@ int main(int argc, char **argv) {
 
   return (tmain<int, 5>(argc) + tmain<char, 1>(argv[0][0])); // expected-note {{in instantiation of function template specialization 'tmain<int, 5>' requested here}} expected-note {{in instantiation of function template specialization 'tmain<char, 1>' requested here}}
 }
+
+namespace GH139266 {
+void f(void) {
+#pragma omp distribute dist_schedule(static, 0) // expected-error {[argument to 'dist_schedule' clause must be a strictly positive integer value}}
```
Comment (Fznamznon) [inline clang/test/OpenMP/teams_distribute_dist_schedule_messages.cpp:111]: a '{' is missing.

Comment (AaronBallman) [reply clang/test/OpenMP/teams_distribute_dist_schedule_messages.cpp:111]: Yup, already fixed it. :-)
