### PR TITLE
[SelectionDAG] Fix zext assertion check for scalable vectors

### LINKED ISSUE #176037: [CodeGen[AArch64] Assertion `isScalableVector() == VT.isScalableVector() && "Comparison between scalable and fixed types"' failed.
https://godbolt.org/z/cEaxWvxKh

### PR DESCRIPTION
**Pull request by manasij7479**
Use element type comparisons in getZeroExtendInReg to avoid comparing scalable and fixed types.

Fixes #176037

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 1]
```diff
@@ -1591,7 +1594,8 @@ SDValue SelectionDAG::getVPZeroExtendInReg(SDValue Op, SDValue Mask,
          "getVPZeroExtendInReg type and operand type should be vector!");
   assert(VT.getVectorElementCount() == OpVT.getVectorElementCount() &&
          "Vector element counts must match in getZeroExtendInReg");
-  assert(VT.bitsLE(OpVT) && "Not extending!");
+  assert(VT.getScalarType().bitsLE(OpVT.getScalarType()) &&
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: This same assert exists in getZeroExtendInReg, should it be updated too?

Comment (manasij7479) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Good catch, fixed.

File: llvm/test/CodeGen/AArch64/aarch64-sve-setcc-promote-nxv8i8-crash.ll [hunk 2]
```diff
@@ -0,0 +1,23 @@
+; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mattr=+sve -o - %s | FileCheck %s
+
+target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
+target triple = "aarch64-unknown-linux-gnu"
```
[the remark this answers is not in the document]
Comment (manasij7479) [reply llvm/test/CodeGen/AArch64/aarch64-sve-setcc-promote-nxv8i8-crash.ll]: changed

**Review by topperc — APPROVED** [review]
LGTM
