### PR TITLE
Fix codegen of consteval functions returning an empty class, and related issues

### LINKED ISSUE #93040: Codegen bug: Derived ctor with consteval base ctor
Originally reported as a potential [security issue](https://bugs.chromium.org/p/llvm/issues/detail?id=67) but we believe the codegen bug has no security implications. So, refiling it here.

Original report:
>Take a look at this code example - https://godbolt.org/z/s6nM69Gqn
> GCC and MSVC flag this as an error while Clang compiles this fine, but crashes on running.

@serge-sans-paille reduced it to:
```
struct vec {
  int (*func)() = nullptr;
  int * data = nullptr;
  int size;
  vec() = default;
  ~vec() { delete [] data;}
};

struct Base {
  consteval Base() {}
};

struct Derived : vec, Base {};

int main() {
  Derived d;
  if(d.func)
    d.func();
  return 0;
}
```

@AaronBallman said:
> Oof, this is a neat one. Clang and EDG accept, GCC and MSVC reject. However, I think Clang and EDG are correct, and I think GCC considers the rejection to be a bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98752
> However, there's still a codegen bug here in that we're storing undef into the empty base class:
```
define linkonce_odr dso_local void @Derived::Derived()(ptr noundef nonnull align 8 dereferenceable(20) %this) unnamed_addr comdat align 2 {
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  tail call void @llvm.dbg.declare(metadata ptr %this.addr, metadata !55, metadata !DIExpression())
  %this1 = load ptr, ptr %this.addr, align 8
  call void @vec::vec()(ptr noundef nonnull align 8 dereferenceable(20) %this1) #4
  %0 = getelementptr inbounds %struct.Base, ptr %this1, i32 0, i32 0
  store i8 undef, ptr %0, align 8 // DRAGONS START HERE
  ret void
}
```
> I think the issue is that our codegen is getting the initialization wrong with an empty base class and a consteval constructor. You can get the same undef even without multiple base classes: https://godbolt.org/z/GnvvxaTMx

### PR DESCRIPTION
**Pull request by efriedma-quic**
Fix codegen of consteval functions returning an empty class, and related issues

If a class is empty, don't store it to memory: the store might overwrite useful data.  Similarly, if a class has tail padding that might overlap other fields, don't store the tail padding to memory.

The problem here turned out a bit more general than I initially thought: basically all uses of EmitAggregateStore were broken. Call lowering had a method that did mostly the right thing, though: CreateCoercedStore. Adapt CreateCoercedStore so it always does the conservatively right thing, and use it for both calls and ConstantExpr.

Also, along the way, fix the "overlap" bit in AggValueSlot: the bit was set incorrectly for empty classes in some cases.

Fixes #93040.

### CODE REVIEW

**Review by zygoloid — APPROVED** [review]
Looks good. Do we also need to worry about overwriting tail padding here?

**Comment by efriedma-quic** [comment]
I didn't think so at first glance... but yes, we do, in certain obscure cases:

```
#include <new>
struct A { char c; A(); };
struct __attribute((packed)) S  { char a; int x; __attribute((aligned(2))) char y; consteval S() : x(1), a(3), y(2) {} };
struct S2 { [[no_unique_address]] S s; [[no_unique_address]] A a; };
static_assert(sizeof(S)==8 && sizeof(S2)==8);
void f2(S2 *s) { new (&s->s) S; }
```

I'll look into reworking this.

File: clang/lib/CodeGen/CGExprAgg.cpp [hunk 1]
```diff
@@ -135,6 +135,17 @@ class AggExprEmitter : public StmtVisitor<AggExprEmitter> {
     EnsureDest(E->getType());
 
     if (llvm::Value *Result = ConstantEmitter(CGF).tryEmitConstantExpr(E)) {
+      // An empty record can overlap other data (if declared with
+      // no_unique_address); omit the store for such types - as there is no
```
Comment (serge-sans-paille) [inline clang/lib/CodeGen/CGExprAgg.cpp:139]: Candide question: Empty record still need one byte when their address is taken (thus this comment about `no_unique_address` I guess), why don't we see that in the diff?

Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprAgg.cpp:139]: See what, exactly?  Given the derived class, computing the address of the base class doesn't take any instructions, because it's the same address.

File: clang/test/CodeGenOpenCL/addr-space-struct-arg.cl [hunk 2]
```diff
@@ -177,7 +179,12 @@ kernel void KernelTwoMember(struct StructTwoMember u) {
 // AMDGCN-LABEL: define{{.*}} amdgpu_kernel void @KernelLargeTwoMember
 // AMDGCN-SAME:  (%struct.LargeStructTwoMember %[[u_coerce:.*]])
 // AMDGCN:  %[[u:.*]] = alloca %struct.LargeStructTwoMember, align 8, addrspace(5)
-// AMDGCN:  store %struct.LargeStructTwoMember %[[u_coerce]], ptr addrspace(5) %[[u]]
+// AMDGCN:  %[[U_PTR0:.*]] = getelementptr inbounds %struct.LargeStructTwoMember, ptr addrspace(5) %[[u]], i32 0, i32 0
```
Comment (efriedma-quic) [inline clang/test/CodeGenOpenCL/addr-space-struct-arg.cl:182]: Unifying the codepaths makes FCA promotion happen more often.

File: clang/test/CodeGenCXX/address-space-cast-coerce.cpp [hunk 3]
```diff
@@ -46,9 +46,9 @@ int mane() {
     char1 f1{1};
     char1 f2{1};
 
-// CHECK: [[TMP:%.+]] = alloca i16
```
Comment (efriedma-quic) [inline clang/test/CodeGenCXX/address-space-cast-coerce.cpp:49]: The revised version of casting integers is a bit more aggressive; it's hard to make it precisely match the old code while still preserving the correct semantics.

File: clang/test/CodeGen/arm-mve-intrinsics/vld24.c [hunk 4]
```diff
@@ -48,10 +48,13 @@ uint8x16x4_t test_vld4q_u8(const uint8_t *addr)
 
 // CHECK-LABEL: @test_vst2q_u32(
 // CHECK-NEXT:  entry:
-// CHECK-NEXT:    [[VALUE_COERCE_FCA_0_0_EXTRACT:%.*]] = extractvalue [[STRUCT_UINT32X4X2_T:%.*]] [[VALUE_COERCE:%.*]], 0, 0
-// CHECK-NEXT:    [[VALUE_COERCE_FCA_0_1_EXTRACT:%.*]] = extractvalue [[STRUCT_UINT32X4X2_T]] [[VALUE_COERCE]], 0, 1
-// CHECK-NEXT:    call void @llvm.arm.mve.vst2q.p0.v4i32(ptr [[ADDR:%.*]], <4 x i32> [[VALUE_COERCE_FCA_0_0_EXTRACT]], <4 x i32> [[VALUE_COERCE_FCA_0_1_EXTRACT]], i32 0)
-// CHECK-NEXT:    call void @llvm.arm.mve.vst2q.p0.v4i32(ptr [[ADDR]], <4 x i32> [[VALUE_COERCE_FCA_0_0_EXTRACT]], <4 x i32> [[VALUE_COERCE_FCA_0_1_EXTRACT]], i32 1)
+// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue [[STRUCT_UINT32X4X2_T:%.*]] [[VALUE_COERCE:%.*]], 0
```
Comment (efriedma-quic) [inline clang/test/CodeGen/arm-mve-intrinsics/vld24.c:51]: Apparently I've stumbled over some limitation of instcombine.

File: clang/test/CodeGen/arm-vfp16-arguments2.cpp [hunk 5]
```diff
@@ -44,20 +44,20 @@ struct S1 f1(struct S1 s1) { return s1; }
 
 // CHECK-SOFT: define{{.*}} void @_Z2f22S2(ptr dead_on_unwind noalias nocapture writable writeonly sret(%struct.S2) align 8 %agg.result, [4 x i32] %s2.coerce)
 // CHECK-HARD: define{{.*}} arm_aapcs_vfpcc [2 x <2 x i32>] @_Z2f22S2([2 x <2 x i32>] returned %s2.coerce)
-// CHECK-FULL: define{{.*}} arm_aapcs_vfpcc %struct.S2 @_Z2f22S2(%struct.S2 returned %s2.coerce)
+// CHECK-FULL: define{{.*}} arm_aapcs_vfpcc %struct.S2 @_Z2f22S2(%struct.S2 %s2.coerce)
```
Comment (efriedma-quic) [inline clang/test/CodeGen/arm-vfp16-arguments2.cpp:47]: This is also the instcombine issue.

**Comment by efriedma-quic** [comment]
(I'd like a re-review of the latest version: I made significant revisions to address the tail-padding issues.)

File: clang/lib/CodeGen/CGCall.cpp [hunk 6]
```diff
@@ -1336,75 +1336,56 @@ static llvm::Value *CreateCoercedLoad(Address Src, llvm::Type *Ty,
...
-  if (isa<llvm::ScalableVectorType>(SrcTy) ||
-      isa<llvm::ScalableVectorType>(DstTy) ||
-      SrcSize.getFixedValue() <= DstSize.getFixedValue()) {
-    Dst = Dst.withElementType(SrcTy);
-    CGF.EmitAggregateStore(Src, Dst, DstIsVolatile);
+  if (SrcSize.isScalable() || SrcSize <= DstSize) {
+    if (SrcTy->isIntegerTy() && Dst.getElementType()->isPointerTy() &&
+        SrcSize == CGM.getDataLayout().getTypeAllocSize(Dst.getElementType())) {
+      // If the value is supposed to be a pointer, convert it before storing it.
+      Src = CoerceIntOrPtrToIntOrPtr(Src, Dst.getElementType(), *this);
```
Comment (zygoloid) [inline clang/lib/CodeGen/CGCall.cpp:1370]: It looks like we used to create either an `inttoptr` or `ptrtoint` here and now we only handle the `inttoptr` case. Is that OK?

File: clang/lib/CodeGen/CodeGenFunction.h [hunk 7]
```diff
@@ -4772,7 +4772,8 @@ class CodeGenFunction : public CodeGenTypeCache {
 
   /// Build all the stores needed to initialize an aggregate at Dest with the
   /// value Val.
```
Comment (zygoloid) [inline clang/lib/CodeGen/CodeGenFunction.h:4774]: This comment looks out of date.

**Review by zygoloid — APPROVED** [review]

File: clang/lib/CodeGen/CGCall.cpp (hunk 6 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGCall.cpp:1370]: inttoptr comes from constructs like a struct containing a pointer, which the calling convention code sometimes chooses to just coerce to an integer instead of trying to compute a prettier type.  The other direction would be very unusual: it would mean we somehow coerced some non-pointer value to a pointer.

And this isn't really a correctness thing, anyway; type-punning in memory is basically the same as doing it in a register.  This just makes the intended types more clear for optimizations.

Comment (zygoloid) [reply clang/lib/CodeGen/CGCall.cpp:1370]: Yeah, it definitely seems like it'd be a pretty big surprise to need this. OK.

**Comment by RSilicon** [comment]
Is this worth back porting as it is a bugfix over code gen?

**Comment by AaronBallman** [comment]
> Is this worth back porting as it is a bugfix over code gen?

IMO, it's worth considering, but if we want to go down this route, I think we need to do so relatively quickly -- we have about two weeks until rc3, and given the size of this change, I'm not certain we should try landing it any later than rc3 just due to risk.

**Comment by efriedma-quic** [comment]
This is maybe slightly risky in terms of possible regressions, but it is a fix for a miscompile, and we're early enough in the release process that it's probably fine.

/cherry-pick 1762e01
