### PR TITLE
[clang][Sema] Fixed Compound Literal is not Constant Expression

### LINKED ISSUE #87867: getting: "error: initializer element is not a compile-time constant" Even when struct is inside function
```C
int foo(int *a, int b)
{
    return 0;
}

int main()
{
    int x;
    (struct {
          typeof(foo(&(struct { int t; }){.t = x}.t, 0)) t;
        }){0};
}
```

the above code compiles with gcc and tcc. but fails with clang.

The error I get is: 
```
err_test.c:10:48: error: initializer element is not a compile-time constant
          typeof(foo(&(struct { int t; }){.t = x}.t, 0)) t;
                                               ^
1 error generated.
```

This error seems to be for global or static variables, but for some reason is triggering even though the variable is defined inside a function and inside a `typeof`

### PR DESCRIPTION
**Pull request by Mr-Anyone**
Added a check for a compound literal hiding inside a function.

fixes #87867

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -7219,6 +7219,17 @@ Sema::ActOnCompoundLiteral(SourceLocation LParenLoc, ParsedType Ty,
   return BuildCompoundLiteralExpr(LParenLoc, TInfo, RParenLoc, InitExpr);
 }
 
+static bool IsInsideFunction(Scope *S) {
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp]:
```suggestion
static bool IsContainedByFunctionScope(const Scope *S) {
```
makes it more clear that we're checking whether the given scope is itself somewhere within a function scope.

**Review by AaronBallman — APPROVED** [review]
LGTM aside from a nit, thank you for working on this!

File: clang/lib/Sema/SemaExpr.cpp (hunk 1 above)
Comment (shafik) [reply clang/lib/Sema/SemaExpr.cpp]: @AaronBallman it feels like it makes sense to sink this into `Scope` just like `isInObjCMethodScope()`

Comment (AaronBallman) [reply clang/lib/Sema/SemaExpr.cpp]: I can go either way. This is currently the first time we've needed this, so a static function makes sense. But if we need this a second time, then absolutely agreed it should be hoisted into `Scope`. WDYT?

Comment (Mr-Anyone) [reply clang/lib/Sema/SemaExpr.cpp]: I do see people using this from time to time. I just moved this logic into `Scope`.

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by Mr-Anyone** [comment]
@AaronBallman I don't have merge access. Could you please merge this for me? Thanks.

**Comment by AaronBallman** [comment]
> @AaronBallman I don't have merge access. Could you please merge this for me? Thanks.

Absolutely, thank you for letting me know. :-)
