### PR TITLE
[clang][NFC] Prevent scope pollution from repeat type specifiers

### LINKED ISSUE #187664: [clang]Assertion failure in TypeLoc (ElaboratedTypeLoc/TypedefTypeLoc) on invalid default template type parameter combining two type specifiers
## The following invalid code causes **Clang** to crash since 16.0.0:
when two **type specifiers** are combined in a default template argument:

```cpp
class A {
public:
    class B {};
};

using X = A::B;

class C {
    template <typename T = X class A::B> void f();
};
```
**https://godbolt.org/z/Mh8j156E7**

## **OUTPUT:**
```
<source>:9:30: error: cannot combine with previous 'type-name' declaration specifier
    9 |     template <typename T = X class A::B> void f();
      |                              ^
clang++: /root/llvm-project/llvm/tools/clang/include/clang/AST/TypeLoc.h:746: void clang::ElaboratedNameTypeLoc<TL, T>::set(clang::SourceLocation, clang::NestedNameSpecifierLoc, clang::SourceLocation) [with TL = clang::TypedefTypeLoc; T = clang::TypedefType]: Assertion `QualifierLoc.getNestedNameSpecifier() == this->getTypePtr()->getQualifier()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:9:40: current parser token '>'
2.	<source>:8:1: parsing struct/union/class body 'C'
 #0 0x000000000445abc8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x445abc8)
 #1 0x00000000044579f4 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44579f4)
 #2 0x0000000004458014 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4458014)
 #3 0x00000000043973b8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x000079b404842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x000079b4048969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x000079b404842476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x000079b4048287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x000079b40482871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x000079b404839e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x000000000791dffb (anonymous namespace)::TypeSpecLocFiller::VisitTypedefTypeLoc(clang::TypedefTypeLoc) (.isra.0) SemaType.cpp:0:0
#11 0x0000000007943685 clang::TypeLocVisitor<(anonymous namespace)::TypeSpecLocFiller, void>::Visit(clang::UnqualTypeLoc) SemaType.cpp:0:0
#12 0x000000000794ba3b GetFullTypeForDeclarator((anonymous namespace)::TypeProcessingState&, clang::QualType, clang::TypeSourceInfo*) SemaType.cpp:0:0
#13 0x000000000794c85f clang::Sema::GetTypeForDeclarator(clang::Declarator&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x794c85f)
#14 0x000000000794cb9e clang::Sema::ActOnTypeName(clang::Declarator&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x794cb9e)
#15 0x0000000006d0a1c3 clang::Parser::ParseTypeName(clang::SourceRange*, clang::DeclaratorContext, clang::AccessSpecifier, clang::Decl**, clang::ParsedAttributes*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d0a1c3)
#16 0x0000000006dd0535 clang::Parser::ParseTypeParameter(unsigned int, unsigned int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd0535)
#17 0x0000000006dd76b1 clang::Parser::ParseTemplateParameter(unsigned int, unsigned int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd76b1)
#18 0x0000000006dd824e clang::Parser::ParseTemplateParameterList(unsigned int, llvm::SmallVectorImpl<clang::NamedDecl*>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd824e)
#19 0x0000000006dd8a2d clang::Parser::ParseTemplateParameters(clang::Parser::MultiParseScope&, unsigned int, llvm::SmallVectorImpl<clang::NamedDecl*>&, clang::SourceLocation&, clang::SourceLocation&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd8a2d)
#20 0x0000000006ddb2d3 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (.part.0) ParseTemplate.cpp:0:0
#21 0x0000000006d26225 clang::Parser::ParseCXXClassMemberDeclaration(clang::AccessSpecifier, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::ParsingDeclRAIIObject*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d26225)
#22 0x0000000006d282af clang::Parser::ParseCXXClassMemberDeclarationWithPragmas(clang::AccessSpecifier&, clang::ParsedAttributes&, clang::TypeSpecifierType, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d282af)
#23 0x0000000006d29f8f clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d29f8f)
#24 0x0000000006d2c873 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d2c873)
#25 0x0000000006cff986 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cff986)
#26 0x0000000006cbae17 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cbae17)
#27 0x0000000006cbb89f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cbb89f)
#28 0x0000000006cc2ec1 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cc2ec1)
#29 0x0000000006cc3df5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6cc3df5)
#30 0x0000000006ca54ba clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ca54ba)
#31 0x0000000004f439a8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f439a8)
#32 0x000000000525e6a5 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x525e6a5)
#33 0x00000000051dc19e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51dc19e)
#34 0x000000000535a68d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x535a68d)
#35 0x0000000000df5092 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdf5092)
#36 0x0000000000deb9ca ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#37 0x0000000000debb4d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#38 0x0000000004facb69 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#39 0x00000000043977f4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43977f4)
#40 0x0000000004fad196 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#41 0x0000000004f6c272 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f6c272)
#42 0x0000000004f6d21e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f6d21e)
#43 0x0000000004f74dd5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f74dd5)
#44 0x0000000000df13f4 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdf13f4)
#45 0x0000000000ca8f0a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xca8f0a)
#46 0x000079b404829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#47 0x000079b404829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#48 0x0000000000deb465 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdeb465)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

The crash also occurs with:

```cpp
class A {
public:
    class B {};
};

typedef A::B X;

class C {
    template <typename T = X class A::B> void f();
};
```

and:

```cpp
class A {
public:
    class B {};
};

using X = char;

class C {
    template <typename T = X class A::B> void f();
};
```

But if you remove the _**type alias**_, the same pattern no longer crashes:

```cpp
class A {
public:
    class B {};
};

class C {
    template <typename T = A::B class A::B> void f();
};
```

This code does not crash either:
```cpp
class A {
public:
    class B {};
};

class C {
    template <typename T = A::B class A> void f();
};
```

### PR DESCRIPTION
**Pull request by ojhunt**
Fixes #187664

When parsing `type-specifier {class,union,struct,enum,etc} nested-name` ParseClassSpecifier and ParseEnumSpecifier both operated on the current declaration scope on the assumption that they were the only type specifier. Of course in incorrect code that assumption is false, and as a result when parsing the name specifier they would pollute the the real scope.

This is not relevant to the semantic correctness: the error is detected and reported. The problem is that the subsequent state is not correct, though not in a way that impacts functional behavior of release builds.

In assertion builds however this is detected (via a somewhat obtuse path) when we attempt to plant namespace location information from the invalid declaration on the initial declaration.

This PR fixes the state corruption by moving the name parsing in enum and record type specifiers into a throwaway scope if the declaration already has a type specifier.

### CODE REVIEW

**Comment by ojhunt** [comment]
@TPPPP72 So I think this is the correct fix - we stop the parser from mutating the scope of the declaration context when there is already a type specifier.

@mizvekov @cor3ntin I'm not sure if we should also gate any other mutation of the declcontext as I'm not sure how much of that mutation is responsible for the detection of the duplicated specifier. I'm also not sure the point of "duplicate type specifiers" it's worth trying to be pedantic about where the other errors are?

**Comment by ojhunt** [comment]
(also - based on behavior I think this is purely assertion impact so NFC and no need for release note)

File: clang/lib/Parse/ParseDecl.cpp [hunk 1]
```diff
@@ -5076,7 +5076,11 @@ void Parser::ParseEnumSpecifier(SourceLocation StartLoc, DeclSpec &DS,
                          (AllowEnumSpecifier == AllowDefiningTypeSpec::Yes ||
                           CanBeOpaqueEnumDeclaration);
 
-  CXXScopeSpec &SS = DS.getTypeSpecScope();
+  // We use a temporary scope when parsing the name specifier for a
+  // declaration with additional invalid type specifiers
```
Comment (tbaederr) [inline clang/lib/Parse/ParseDecl.cpp]:
```suggestion
  // declaration with additional invalid type specifiers.
```

File: clang/lib/Parse/ParseDeclCXX.cpp [hunk 2]
```diff
@@ -1694,8 +1694,12 @@ void Parser::ParseClassSpecifier(tok::TokenKind TagTokKind,
   PreserveAtomicIdentifierInfoRAII AtomicTokenGuard(
       Tok, ShouldChangeAtomicToIdentifier);
 
+  // We use a temporary scope when parsing the name specifier for a
+  // declaration with additional invalid type specifiers
```
Comment (tbaederr) [inline clang/lib/Parse/ParseDeclCXX.cpp]:
```suggestion
  // declaration with additional invalid type specifiers.
```

**Comment by TPPPP72** [comment]
Yes. Indeed, compared to cleaning up TypeScope in DeclSpec, intercepting directly during the Parse phase is a more straightforward approach.

File: clang/lib/Parse/ParseDeclCXX.cpp (hunk 2 above)
Comment (ojhunt) [reply clang/lib/Parse/ParseDeclCXX.cpp]: I really don't like this duplication but I couldn't see any way to avoid it (at least not without excessive Architecture(tm) )

**Comment by ojhunt** [comment]
> Yes. Indeed, compared to cleaning up TypeScope in DeclSpec, intercepting directly during the Parse phase is a more straightforward approach.

The real work is determining whether the invalid state is actually expected as a result of the parse issue - I think we were all happy with it being cleared later on down the line, it just took me trying to come up with different test cases to realize that it was likely an unexpectedly incorrect state.

But we'll need to see if other folk agree with this fix :D

**Review by cor3ntin — COMMENTED** [review]
This is a cleaner fix - i like it

--

This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

**Review by mizvekov — APPROVED** [review]
