### PR TITLE
[clang-tidy] Ignore unused parameters in `rvalue-reference-param-not-moved check`

### LINKED ISSUE #68209: [clang-tidy] False positive for cppcoreguidelines-rvalue-reference-param-not-moved when parameter has [[maybe_unused]]
The following seemingly valid code

```
#include <tuple>
#include <utility>

void conditional_use([[maybe_unused]] int && x) {
#ifdef USE_X
    int y = std::move(x);
    std::ignore = y;
#endif
}

int main() {
    conditional_use(5);
}
```

results in the error
```
repro.cpp:4:46: error: rvalue reference parameter 'x' is never moved from inside the function body [cppcoreguidelines-rvalue-reference-param-not-moved,-warnings-as-errors]
    4 | void conditional_use([[maybe_unused]] int && x) {
```

Encountered on
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
```
$ clang-tidy --version
Ubuntu LLVM version 17.0.2
  Optimized build.
```
installed with the script from https://apt.llvm.org/llvm.sh .

### PR DESCRIPTION
**Pull request by AMS21**
With this patch we no longer issue a warning for unused parameters which are marked as such.

This fixes #68209

### CODE REVIEW

**Comment by AMS21** [comment]
I'm not sure if we should rather have this as an option like `IgnoreUnnamedParams`

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/rvalue-reference-param-not-moved.cpp [hunk 1]
```diff
@@ -333,3 +333,22 @@ void instantiate_a_class_template() {
   AClassTemplate<Obj&> withObjRef(o);
   withObjRef.never_moves(o);
 }
+
+namespace gh68209
+{
+  void f1([[maybe_unused]] int&& x) {}
+
+  void f2(__attribute__((unused)) int&& x) {}
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/rvalue-reference-param-not-moved.cpp:341]: Add info to documentation, that params with such attributes are unused.

**Review by PiotrZSL — APPROVED** [review]
Looks fine, I don't thing that this needs to be configurable.
If someone put explicitly attribute, then there is assumption that such param can be unused.

**Comment by AMS21** [comment]
Added the suggested change and also added another test case

**Review by PiotrZSL — APPROVED** [review]

**Comment by AMS21** [comment]
If there are no more problems I would kindly ask for someone to push this on my behalf :)
