### PR TITLE
[SelectionDAG] Fix isKnownNeverZeroFloat for vectors

### LINKED ISSUE #77805: Incorrect code generated for float llvm.maximum/minimum intrinsics
I believe [this change](https://github.com/llvm/llvm-project/commit/7bff37783f72ed99e4cdd0fd7dad1bf1f119f793) introduced a bug preventing correct handing of signed zeroes in certain cases.

This check
```cpp
  if (Op->getOpcode() == ISD::BUILD_VECTOR ||
      Op->getOpcode() == ISD::SPLAT_VECTOR) {
    for (const SDValue &OpVal : Op->op_values()) {
      if (OpVal.isUndef())
        return false;
      if (auto *C = dyn_cast<ConstantFPSDNode>(OpVal))
        if (C->isZero())
          return false;
    }
    return true;
  }
```

Returns `true` by default, marking most BUILD/SPLAT vectors as known non-zeroes preventing the negative zero check generation.

See this example: https://godbolt.org/z/Yh5oE916v
```llvm
target triple = "x86_64-unknown-linux-gnu"

declare float @llvm.maximum.f32(float, float)
declare <8 x float> @llvm.maximum.v8f32(<8 x float>,<8 x float>)

define <8 x float> @foo(float %a, <8 x float> %vec) #0 {
entry:
  %splatinsert = insertelement <8 x float> poison, float %a, i64 0
  %splat = shufflevector <8 x float> %splatinsert, <8 x float> poison, <8 x i32> zeroinitializer
  %res = call nnan noundef <8 x float> @llvm.maximum.v8f32(<8 x float> %splat, <8 x float> %vec)
  ret <8 x float> %res
}

attributes #0 = { "target-cpu"="haswell" }
```

I believe the check should look something like
```cpp
  if (Op->getOpcode() == ISD::BUILD_VECTOR ||
      Op->getOpcode() == ISD::SPLAT_VECTOR) {
    return llvm::all_of(Op->op_values(), [](const SDValue &OpVal){
      if (auto *C = dyn_cast<ConstantFPSDNode>(OpVal))
        return !C->isZero();
      return false;
    });
  }
```

### PR DESCRIPTION
**Pull request by danilaml**
Return true iff all of vector elements are constant AND not zero

Fixes #77805

Previously, it'd return `true` (as in - the value is known to be never zero) for any build_vector/splat_vector with non-constant elements.

### CODE REVIEW

**Review by RKSimon — COMMENTED** [review]
Please can you rebase on d6ee91b1100a3356506643da37cbd6891a663db9 to show the codegen diff

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 1]
```diff
@@ -5239,14 +5239,11 @@ bool SelectionDAG::isKnownNeverZeroFloat(SDValue Op) const {
...
-      if (OpVal.isUndef())
-        return false;
+    return llvm::all_of(Op->op_values(), [](const SDValue &OpVal){
       if (auto *C = dyn_cast<ConstantFPSDNode>(OpVal))
-        if (C->isZero())
-          return false;
-    }
-    return true;
+        return !C->isZero();
+      return false;
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:5245]: You might be able to do this with matchUnaryFpPredicate

Comment (danilaml) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp]: Nice. Didn't know about it. I hope I used it correctly.

**Comment by danilaml** [comment]
SSE2 codegen is terrible (is this all to avoid a simple branch?), but otherwise looks fine to me.

**Review by arsenm — APPROVED** [review]
