### PR TITLE
[llvm] Fix __builtin_object_size interaction between Negative Offset …

### LINKED ISSUE #111709: UBSan false positive: runtime error: load of address with insufficient space for an object of type 'int'
Please consider this small reduced testcase:
```c++
int x;
int main(void) {
  int array[4] = {0};
  int *ptr;
  if (x) {
    ptr = 0;
  } else {
    ptr = array + 4;
  }
  return ptr[-1];
}
```
This, as far as I know, is a strictly conforming C program. But Clang's UBSan rejects it as of version 15:
```
$ clang-14 test.c -O3 -o test -fsanitize=undefined && ./test
$ clang-15 test.c -O3 -o test -fsanitize=undefined && ./test
test.c:10:10: runtime error: load of address 0xffffd0f236dc with insufficient space for an object of type 'int'
0xffffd0f236dc: note: pointer points here
  00 00 00 00 00 00 00 00  00 38 f2 d0 ff ff 00 00  c4 84 f1 eb 72 e1 00 00  78 38 f2 d0 ff ff 00 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test.c:10:10 in
```
This continues to be rejected in all later versions too. From what I can tell debugging, it's going wrong in `llvm::lowerObjectSizeCall`: this sets `EvalOptions.EvalMode = ObjectSizeOpts::Mode::ExactSizeFromOffset`. `ExactSizeFromOffset` allows combining `SizeOffsetValue`s if the sizes are the same, even if the offsets are different. So, we combine "0 bytes into a 0-byte-sized object" and "16 bytes into a 16-byte-sized object" into just "0 bytes into a 0-byte-sized object". But that is wrong when we then use that to conclude that we cannot access any bytes before that object.

If I change LLVM as
```diff
diff --git a/llvm/lib/Analysis/MemoryBuiltins.cpp b/llvm/lib/Analysis/MemoryBuiltins.cpp
index e1abf5e4d885..8abbb074647c 100644
--- a/llvm/lib/Analysis/MemoryBuiltins.cpp
+++ b/llvm/lib/Analysis/MemoryBuiltins.cpp
@@ -610,7 +610,7 @@ Value *llvm::lowerObjectSizeCall(
     EvalOptions.EvalMode =
         MaxVal ? ObjectSizeOpts::Mode::Max : ObjectSizeOpts::Mode::Min;
   else
-    EvalOptions.EvalMode = ObjectSizeOpts::Mode::ExactSizeFromOffset;
+    EvalOptions.EvalMode = ObjectSizeOpts::Mode::ExactUnderlyingSizeAndOffset;

   EvalOptions.NullIsUnknownSize =
       cast<ConstantInt>(ObjectSize->getArgOperand(2))->isOne();
```
then this program gets accepted. But I expect this change to not be right, I expect this to result in poorer codegen where `lowerObjectSizeCall` is already doing the right thing.

### PR DESCRIPTION
**Pull request by serge-sans-paille**
…and Select/Phi

When picking a SizeOffsetAPInt through combineSizeOffset, the behavior differs if we're going to apply a constant offset that's positive or negative: If it's positive, then we need to compare the remaining bytes (i.e. Size
- Offset), but if it's negative, we need to compare the preceding bytes (i.e. Offset).

Fix #111709

### CODE REVIEW

File: llvm/lib/Analysis/MemoryBuiltins.cpp [hunk 1]
```diff
@@ -981,18 +992,39 @@ ObjectSizeOffsetVisitor::combineSizeOffset(SizeOffsetAPInt LHS,
...
-    return (getSizeWithOverflow(LHS).sgt(getSizeWithOverflow(RHS))) ? LHS : RHS;
-  case ObjectSizeOpts::Mode::ExactSizeFromOffset:
-    return (getSizeWithOverflow(LHS).eq(getSizeWithOverflow(RHS)))
-               ? LHS
-               : ObjectSizeOffsetVisitor::unknown();
-  case ObjectSizeOpts::Mode::ExactUnderlyingSizeAndOffset:
-    return LHS == RHS ? LHS : ObjectSizeOffsetVisitor::unknown();
+  // If the ConstantOffset we add in the end is negative, then we're actually
+  // interested in selecting the nodes based on their offset rather than their
+  // size.
```
Comment (hvdijk) [inline llvm/lib/Analysis/MemoryBuiltins.cpp:997]: Are we? I cannot really understand how this logic works, sorry. When `Options.EvalMode==ObjectSizeOpts::Mode::ExactSizeFromOffset`, that specifies that we should combine `LHS` and `RHS` when the remaining sizes of `LHS` and `RHS` are the same, that is how it is documented, and it feels risky to add a field to `ObjectSizeOffsetVisitor` that makes it so that this function no longer behaves as documented.

**Comment by hvdijk** [comment]
If I apply this PR locally, although I no longer see the UBSan error, I still get a number of differences in `__builtin_object_size` between Clang and GCC when I change my test to print `__builtin_object_size`'s result directly. I am not sure what the status of `__builtin_object_size` in Clang is, are we meant to return the same results as GCC?

**Comment by serge-sans-paille** [comment]
> If I apply this PR locally, although I no longer see the UBSan error, I still get a number of differences in `__builtin_object_size` between Clang and GCC when I change my test to print `__builtin_object_size`'s result directly. I am not sure what the status of `__builtin_object_size` in Clang is, are we meant to return the same results as GCC?

We're allowed to have a different behavior than GCC if we produce accurate result instead of -1/0. Otherwise that's probably an error. Would you mind sharing the differences?

File: llvm/lib/Analysis/MemoryBuiltins.cpp (hunk 1 above)
Comment (serge-sans-paille) [reply llvm/lib/Analysis/MemoryBuiltins.cpp:997]: That being said, I do see a way for us to keep the mentioned behavior, let me try a few things.

**Comment by hvdijk** [comment]
> We're allowed to have a different behavior than GCC if we produce accurate result instead of -1/0. Otherwise that's probably an error. Would you mind sharing the differences?

Sure. For the avoidance of confusion, in general this is not specifically about negative offsets, but here is an example where we produced a different result to GCC, we still produce a different result to GCC with your PR, but no longer the same result as before.

```c++
#include <stdio.h>
int x;
int main(void) {
  int array1[4] = {0};
  int array2[4] = {0};
  int *ptr;
  if (x) {
    ptr = array1 + 2;
  } else {
    ptr = array2 + 3;
  }
  printf("%zu\n", __builtin_object_size(ptr - 1, 0));
}
```
GCC prints 16. Clang used to print 12. Clang with your PR prints 8. I believe GCC's result is correct, taking the maximum of the number of bytes available for both branches gives 16.

**Comment by serge-sans-paille** [comment]
I've fixed my PR, it now respects the semantic as you hinted, and I had a small bug that I got  rid of.
It now prints 12 in the example you just shared. I do think it's the correct result, you can replace the `ptr - 1` by `ptr` in your example and see that gcc and clang agree on the result (8 on my laptop, which is indeed `12 - sizeof(int)`)

**Comment by hvdijk** [comment]
Yeah, I think you're right that 12 is the correct result in that test. Your updated PR looks good to me at a quick glance, thanks! I'll do some additional testing tomorrow.

**Comment by hvdijk** [comment]
The PR makes it so that `ObjectSizeOffsetVisitor::visitPHINode` can return different results for the same PHI node when called with a different `ConstantOffset`, but that seems like it would interfere with the caching done in `ObjectSizeOffsetEvaluator::compute_`. I do not have a test case that shows wrong behaviour because of that though.

Here is another test demonstrating the PHI handling is not quite right yet, this one not related to negative offsets:
```c++
#include <stdio.h>
int x;
int main(void) {
  int array1[4] = {0};
  int array2[4] = {0};
  int *ptr;
  if (x) {
    ptr = array1;
  } else {
    ptr = array2;
  }
  printf("%zu\n", __builtin_object_size(ptr, 3));
}
```
Regardless of whether it's `array1` or `array2`, 16 bytes are available, so .

**Comment by serge-sans-paille** [comment]
> ```c++
> #include <stdio.h>
> int x;
> int main(void) {
>   int array1[4] = {0};
>   int array2[4] = {0};
>   int *ptr;
>   if (x) {
>     ptr = array1;
>   } else {
>     ptr = array2;
>   }
>   printf("%zu\n", __builtin_object_size(ptr, 3));
> }
> ```

I'll have a look to that caching issue.

For the other example, LLVM doesn't seem to support Type=3, see

https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGBuiltin.cpp#L1122

**Comment by serge-sans-paille** [comment]
> The PR makes it so that `ObjectSizeOffsetVisitor::visitPHINode` can return different results for the same PHI node when called with a different `ConstantOffset`, but that seems like it would interfere with the caching done in `ObjectSizeOffsetEvaluator::compute_`. I do not have a test case that shows wrong behaviour because of that though.

The cache belongs to the `ObjectSizeOffsetEvaluator` while `ConstantOffset` belongs to `ObjectSizeOffsetVisitor`. I don't see any state shared between the two so I don't see the issue (but it was worth double checking, thanks for having me do that).

**Comment by hvdijk** [comment]
Thanks for pointing me to `Type = 3` just not being generally supported, and I agree with your explanation of why the caching should be a non-issue.

Unfortunately, more testing reveals that since this only works when the constant offset is known, it does not yet handle all cases, there are cases where the constant offset is not visible. With a modification to my test, I still get a false UBSan positive.
```c++
int x;
int main(void) {
  int array[4] = {0};
  int *ptr;
  if (x) {
    ptr = 0;
  } else {
    ptr = array + 2;
  }
  if (x) {
    ptr = 0;
  } else {
    ptr = ptr + 2;
  }
  return ptr[-1];
}
```

**Comment by serge-sans-paille** [comment]
Thanks for this test case!  Bug fixed and test case added to the test suite.

File: llvm/lib/Analysis/MemoryBuiltins.cpp [hunk 2]
```diff
@@ -706,7 +715,11 @@ SizeOffsetAPInt ObjectSizeOffsetVisitor::computeImpl(Value *V) {
   IntTyBits = DL.getIndexTypeSizeInBits(V->getType());
   Zero = APInt::getZero(IntTyBits);
 
+  APInt PrevConstantOffset = ConstantOffset;
+
+  ConstantOffset = ConstantOffset.sextOrTrunc(Offset.getBitWidth()) + Offset;
```
Comment (hvdijk) [inline llvm/lib/Analysis/MemoryBuiltins.cpp:720]: Is it safe to possibly truncate here? The below bit with `IndexTypeSizeChanged` tries to very carefully handle the possibility that pointers (and hence indices on those pointers) have different sizes, it's a bit hard to see how exactly that should be handled here.

Comment (serge-sans-paille) [reply llvm/lib/Analysis/MemoryBuiltins.cpp]: I've moved to a call to `CheckedZextOrTrunc` which bails out in case of failure.

**Comment by hvdijk** [comment]
I'm still a bit wary: since this relies on the offset being known, since we get incorrect results if the offset isn't known, it suggests to me that if we ever end up in `ObjectSizeOffsetEvaluator::visitGEPOperator` for a non-constant offset, where that then calls `compute_(GEP.getPointerOperand())` where `compute_` first tries to get a result via `ObjectSizeOffsetVisitor`, that `ObjectSizeOffsetVisitor` could still return an incorrect result. I cannot come up with a test case where this actually fails though.

At the same time, this PR looks to me like it makes things strictly better: if there are cases that get mishandled, they would already get mishandled even in current LLVM. So even if we end up remaining unsure that this fix is complete, it may still be fine to merge.

I would appreciate it if someone more familiar with this code could also take a look, but if no one does in a reasonable time, I think merging this should be okay, thanks.

**Comment by serge-sans-paille** [comment]
> I'm still a bit wary: since this relies on the offset being known, since we get incorrect results if the offset isn't known

Actually if we report an offset as unknown, `__builtin_object_size` returns an error code (either 0 or -1 depending on its arguments) and the caller can handle that gracefully, so it's not an error.

Error occur when we report an incorrect size, which is what happened in your original code, so I think we're not regressing in any way.

**Comment by hvdijk** [comment]
> Actually if we report an offset as unknown, `__builtin_object_size` returns an error code (either 0 or -1 depending on its arguments) and the caller can handle that gracefully, so it's not an error.

That is true for `__builtin_object_size`, but `ObjectSizeOffsetEvaluator::visitGEPOperator` is not used for that, it is used for `__builtin_dynamic_object_size` (as well as some other `-fsanitize` options) which does handle unknown offsets. That is the one where I worry there may still be cases not caught.

**Comment by serge-sans-paille** [comment]
```
% cat /tmp/a.c
#include <stdio.h>
int x, i = -1;
int main() {
  int array1[4];
  int array2[8];
  int *ptr;
  if (x) {
    ptr = array1;
  } else {
    ptr = array2 + 4;
  }
  printf("%zd\n", __builtin_dynamic_object_size(ptr + i, 0));
}
% ./bin/clang /tmp/a.c -o /tmp/a && /tmp/a
-1
```

which is totally fine (I've just changed the `printf` call to output signed value instead of unsigned in your example)

**Comment by hvdijk** [comment]
The return value is unsigned and printing it as signed makes it trickier to explain what values are correct: instead of 20 or greater, it's 20 or greater, or negative, where the reason negative numbers are okay is because they aren't actually negative. But anyway, that is not the reason you are getting a different output, it is because you have not enabled any optimisations. The previous test cases have been with optimisations enabled, this one is too. At any optimisation level (`-Og`, `-O1`, `-O2`, `-O3`, `-Os`, `-Oz`) it doesn't print -1, it prints 0. -1 is a valid output, 0 is not.

**Comment by serge-sans-paille** [comment]
Thanks! Indeed I can reproduce (and the problem seems to predate my change!) and I also have a patch. I'll test it and add it to this patchset.

**Comment by hvdijk** [comment]
Sorry, but that looks like a very wrong approach to me. The code you're modifying in your last commit was already correct, and this new version means we no longer detect accesses before the start of an object as out of bounds.
```c++
#include <stdio.h>
int i = -1;
int main() {
  int array[4];
  printf("%zu\n", __builtin_dynamic_object_size(array + i, 0));
}
```
Here, we used to print 0, and 0 is the best possible value to print. Your update makes it so that we print 20.

When you've got an index that you *know* is before the start of an object, you know it's invalid to access any bytes, that's what the code there was correctly handling. The problem isn't that check, it's that the PHI handling wrongly concludes that we know we're at the start of an object when we're not, and that is the bit that needs to be fixed.

**Comment by serge-sans-paille** [comment]
I now have a better understanding, and indeed you're right. It's actually exactly the same situation as the one in non-dynamic case, but because the offset is negative *and* dynamic, the choice is incorrect. Which makes me think that in both cases, if we have the choice between two object with the same size + offset value, then choosing the one with the larger offset solves the issue. I'll check that.

**Comment by hvdijk** [comment]
> Which makes me think that in both cases, if we have the choice between two object with the same size + offset value, then choosing the one with the larger offset solves the issue. I'll check that.

That works for this test, though for `__builtin_dynamic_object_size(ptr + index, 1)` it might cause a too large value to be returned.

I think we need to, at least in the `__builtin_dynamic_object_size` case, use `ObjectSizeOpts::Mode::ExactUnderlyingSizeAndOffset` in which case we can return that we do not statically know the size of the object. That way, we end up in `ObjectSizeOffsetEvaluator::visitPHINode` and can handle each incoming value separately and return the correct value.

**Comment by serge-sans-paille** [comment]
Just pushed a variant that makes a more educated pick between the two combined offset in case of equality. It seems to me it passes all the test you've been crafting so far ^^!

**Comment by hvdijk** [comment]
The problem is not limited to the case where remaining object sizes are equal though, it's just that those are easiest to come up with test cases for. Consider:
```c++
#include <stdio.h>
int x;
int main(void) {
  int array1[4];
  int array2[8];
  int *ptr;
  if (x) {
    printf("hello\n");
    ptr = array1 + 1;
  } else {
    ptr = array2 + 6;
  }
  printf("%zu\n", __builtin_object_size(ptr - 2, 0));
}
```
This must print 16 or higher, but prints 0 (when optimisations are enabled). During InstCombine `__builtin_object_size` cannot be resolved yet, so instead it is saved for LowerConstantIntrinsics. During LowerConstantIntrinsics, it evaluates with `ObjectSizeOpts::Mode::Max`, sees incoming PHI values {16, 4} and {32, 24}. The former says 12 bytes are available, the latter 8, so it picks the former. Then it applies the negative offset of -8 bytes to it, and because it thinks it knows it's 4 bytes past the start of an object, it wrongly concludes the pointer arithmetic produces an out of bounds value.

**Comment by serge-sans-paille** [comment]
> The problem is not limited to the case where remaining object sizes are equal though, it's just that those are easiest to come up with test cases for. Consider:
> 
> ```c++
> #include <stdio.h>
> int x;
> int main(void) {
>   int array1[4];
>   int array2[8];
>   int *ptr;
>   if (x) {
>     printf("hello\n");
>     ptr = array1 + 1;
>   } else {
>     ptr = array2 + 6;
>   }
>   printf("%zu\n", __builtin_object_size(ptr - 2, 0));
> }
> ```
> 
> This must print 16 or higher, but prints 0 (when optimisations are enabled). During InstCombine `__builtin_object_size` cannot be resolved yet, so instead it is saved for LowerConstantIntrinsics. During LowerConstantIntrinsics, it evaluates with `ObjectSizeOpts::Mode::Max`, sees incoming PHI values {16, 4} and {32, 24}. The former says 12 bytes are available, the latter 8, so it picks the former. Then it applies the negative offset of -8 bytes to it, and because it thinks it knows it's 4 bytes past the start of an object, it wrongly concludes the pointer arithmetic produces an out of bounds value.

Indeed. Looks like my previous approach which propagates the constant (negative) offset would have worked in that situation. But it couldn't work with a dynamic negative offset!
Looks like we should be able to pick different bounds based on the offset sign, I'll explore that path.

In any case, thanks *a lot* for your patience regarding this issue. :bow:

**Comment by hvdijk** [comment]
> Indeed. Looks like my previous approach which propagates the constant (negative) offset would have worked in that situation. But it couldn't work with a dynamic negative offset!

You're right, that would handle that one. Can I suggest an alternative though?

Right now, we act on `SizeOffsetAPInt` objects which contain a size (optional) and offset (optional), and the problem with the PHI handling is that we intentionally risk returning an incorrect offset and an incorrect size, on the assumption that we know how the result will be used and the two errors will cancel out. It turns out they do not cancel out in all cases because we do not have a full understanding of how they are used.

What if, instead, we track *three* `APInt`s? What if we track `TotalSize`, `Offset`, `RemainingSize`?

For my original test, we have PHIs where the incoming values resolve to `SizeOffsetAPInt`s of `{0, 0}` and `{16, 16}`. With my idea, they would instead resolve to `{0, 0, 0}` and `{16, 16, 0}`. This can then be correctly combined into `{unknown, unknown, 0}`, which gives us enough information to say that if a subsequently applied offset is negative, we cannot draw any conclusions. At the same time, this fully preserves the `RemainingSize` to allow the currently intended optimisations, which assume positive offsets, to continue to be performed: for any positive offset, only `RemainingSize` needs to be looked at.

It does not quite handle all the cases that your `ConstantOffset` approach handles, but it would, I believe, be easier to understand and reason to be correct, it would be easier to assure ourselves we are not missing any cases.

**Comment by serge-sans-paille** [comment]
@hvdijk I went from your idea, but using only two values: one to track the amount of memory available before current point, and one to track the amount of memory available after current point. It is indeed easy to reason about, as in your proposal, and behaves in a very elegant manner wrt. the combine operation.
And it passes all our examples \o/
Please let me know what you think of this.

**Comment by hvdijk** [comment]
Nice work! Using a new class rather than extending `SizeOffsetAPInt` is probably good, it helps maintain compatibility, which is a plus if it means we can also backport this to LLVM 19 to fix the wrong UBSAN errors there.

The change to `llvm/test/Transforms/InstCombine/builtin-object-size-offset.ll` should not be needed. With `-passes=instcombine`, it is supposed to check for the size to be known exactly. Here, the size was previously known exactly and it is a regression that we no longer pick that up. The reason this is failing is because in `ObjectSizeOffsetVisitor::compute`, you have `if (!Span.bothKnown()) return {};`, but if `EvalMode != ObjectSizeOpts::Mode::ExactUnderlyingSizeAndOffset`, that is not the best way of handling it. For `ExactSizeFromOffset` specifically, the idea is that `Before` does not matter to the caller, you can construct the result from `After` alone. By requiring both `Before` and `After` to be known, you are effectively making it so that `ExactSizeFromOffset` and `ExactUnderlyingSizeAndOffset` do the same thing, which they should not.

However, if `ExactSizeFromOffset` is restored to handle that case, it then becomes important to ensure that nothing calls `ObjectSizeOffsetVisitor::compute` with `Options.EvalMode = ObjectSizeOpts::Mode::ExactSizeFromOffset` if actually it does care about the offset. Yet `ObjectSizeOffsetEvaluator::compute_` does exactly that. Fixing that is possible by making sure `ObjectSizeOffsetVisitor` has some public `compute` version that returns `OffsetSpan`, and making `ObjectSizeOffsetEvaluator::compute_` use that as well. Alternatively, it may be possible to get `ObjectSizeOffsetEvaluator::compute_` to use a different `EvalMode`, depending on how exactly `ObjectSizeOffsetVisitor::compute` gets changed.

---

P.S.: The reason why I suggested keeping `TotalSize` is that this case can give an upper bound when we know we are indexing into a specific object, but do not know the index (e.g. `__builtin_object_size(array + i, 0)` where `i` is only known at runtime can still be bound by `sizeof array`). I thought we already handled that, but we don't, so it is fine that your PR leaves that unhandled.

I will do more extensive testing later.

**Comment by serge-sans-paille** [comment]
patch updated with your suggestion to adjust the 'before' field when it actually doesn't matter. Works like a charm!

**Comment by hvdijk** [comment]
I did write in my previous comment:

> However, if `ExactSizeFromOffset` is restored to handle that case, it then becomes important to ensure that nothing calls `ObjectSizeOffsetVisitor::compute` with `Options.EvalMode = ObjectSizeOpts::Mode::ExactSizeFromOffset` if actually it does care about the offset. Yet `ObjectSizeOffsetEvaluator::compute_` does exactly that.

The result is that this latest iteration does not handle my test case from https://github.com/llvm/llvm-project/pull/111827#issuecomment-2419260982: that now prints 0 again, but should not.

The possible approach I mentioned in my previous comment to use a different `EvalMode` is simple to do:
```diff
--- a/llvm/lib/Analysis/MemoryBuiltins.cpp
+++ b/llvm/lib/Analysis/MemoryBuiltins.cpp
@@ -1083,7 +1083,9 @@ SizeOffsetValue ObjectSizeOffsetEvaluator::compute(Value *V) {
 }
 
 SizeOffsetValue ObjectSizeOffsetEvaluator::compute_(Value *V) {
-  ObjectSizeOffsetVisitor Visitor(DL, TLI, Context, EvalOpts);
+  ObjectSizeOpts VisitorEvalOpts(EvalOpts);
+  VisitorEvalOpts.EvalMode = ObjectSizeOpts::Mode::ExactUnderlyingSizeAndOffset;
+  ObjectSizeOffsetVisitor Visitor(DL, TLI, Context, VisitorEvalOpts);
   SizeOffsetAPInt Const = Visitor.compute(V);
   if (Const.bothKnown())
     return SizeOffsetValue(ConstantInt::get(Context, Const.Size),
```
This does also need `builtin-object-size-phi.ll` to be updated, but I think the effect that it has on that is correct, I think that adequately tests that the bug is fixed.

**Comment by serge-sans-paille** [comment]
I've applied your patch with a few extra comments in the diff and in the commit.

File: llvm/lib/Analysis/MemoryBuiltins.cpp [hunk 3]
```diff
@@ -686,10 +686,23 @@ ObjectSizeOffsetVisitor::ObjectSizeOffsetVisitor(const DataLayout &DL,
...
+  // In ExactSizeFromOffset mode, we don't care about the Before Field, so allow
+  // us to overwrite it if needs be.
+  if (Span.knownAfter() && !Span.knownBefore() &&
+      Options.EvalMode == ObjectSizeOpts::Mode::ExactSizeFromOffset)
+    Span.Before = APInt::getZero(Span.After.getBitWidth());
+
+  if (!Span.bothKnown())
+    return {};
+  if (Span.Before.isNegative() || Span.After.isNegative())
+    return {};
```
Comment (hvdijk) [inline llvm/lib/Analysis/MemoryBuiltins.cpp:700]: Do we need this bit? If this condition is true, we know we have an out of bounds pointer, yet we return that we know nothing about the object's size. I believe if we take this out, the below `return {Span.Before + Span.After, Span.Before};` already handles it correctly and indicates to the caller that we know we have an out of bounds pointer.

A test case for this is

```c++
#include <stdio.h>
int x;
int main() {
  int array[4];
  int *ptr = array + 8;
  printf("%zu\n", __builtin_object_size(ptr, 0));
}
```
Any output is valid, but an output of `0` is best. Previously, we used to print `0`. With your PR, we print `18446744073709551615`. If we take these two lines out, we pass all existing tests, and print `0` again for this new test.

**Review by hvdijk — COMMENTED** [review]
Thanks, at this stage, I believe your PR is correct and fixes all the bugs! In one case, it results in slightly worse results (but still valid results) though, I've left a comment on the specific bit of code that causes this, please take a look and see if you agree.

File: llvm/lib/Analysis/MemoryBuiltins.cpp (hunk 3 above)
Comment (serge-sans-paille) [reply llvm/lib/Analysis/MemoryBuiltins.cpp]: Indeed. I've just forced size and offset to Zero in that case to make it clear we 're doing something wrong

Comment (hvdijk) [reply llvm/lib/Analysis/MemoryBuiltins.cpp]: That may be right at the C++ level, but I think it's wrong at the LLVM IR level. At the LLVM IR level, we may generate `getelementptr` without the `inbounds` attribute, do pointer arithmetic that takes us outside of an object, and then do more pointer arithmetic to take us back in, think the equivalent of `(array + 8) - 6`. If we do nothing special, we will return that `array + 8` is 32 bytes after the start of an object of size 16. We can then compute that `(array + 8) - 6` is 8 bytes into an object of size 16, and allows 8 bytes to be accessed. If we instead return that `array + 8` is zero bytes after the start of an object of size zero, `(array + 8) - 6` would be considered out of bounds.

It may take some effort to come up with a concrete test case demonstrating this though.

Comment (serge-sans-paille) [reply llvm/lib/Analysis/MemoryBuiltins.cpp]: As you proposed at some point, I just removed the check and checked it was still passing the (now well enhanced) test suite, it's indeed the case. Way to go!

**Review by hvdijk — APPROVED** [review]
I am happy with this version, I think it is correct, thank you for the hard work! Please leave a little time before merging to give others time to review if they want, but I will mark it as approved from my end.

**Comment by serge-sans-paille** [comment]
(rebased on `main`, I'll merge afterward)
