### PR TITLE
Fixes and closes #53952. Setting the ASTHasCompilerErrors member variable correctly based on the PP diagnostics.

### LINKED ISSUE #53952: clang::ASTWriter can create a crashing PCH if an incorrect hasErrors value is passed
With the following code:
```cpp
#include "clang/Frontend/ASTUnit.h"
#include "clang/Serialization/ASTWriter.h"
#include "clang/Serialization/InMemoryModuleCache.h"
#include "clang/Tooling/Tooling.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Bitstream/BitstreamWriter.h"
#include <fstream>
#include <memory>
#include <sstream>
#include <string>

int main() {
	std::ifstream codeFile("input.cc");
	std::stringstream code;
	code << codeFile.rdbuf();

	const std::unique_ptr<clang::ASTUnit> astUnit = clang::tooling::buildASTFromCode(code.str());

	const bool hasErrors = false; // This will not cause a crash if this is true
	llvm::SmallString<128> pchData;
	llvm::BitstreamWriter pchDataStream(pchData);
	clang::InMemoryModuleCache moduleCache;
	clang::ASTWriter astWriter(pchDataStream, pchData, moduleCache, {}, false);
	astWriter.WriteAST(astUnit->getSema(), "", nullptr, "", hasErrors);

	std::ofstream file("input.gch", std::ios::binary | std::ios::out);
	file << static_cast<std::string>(pchData);
}
```
and the below file:
```cpp
// input.cc
int main() {
	foo(FOO);
}
```
`clang` will crash when using the `input.gch` file generated from the code.

Output:
```
$ ./a.out                         
input.cc:3:6: error: use of undeclared identifier 'FOO'    
        foo(FOO);                                          
            ^
$ clang input.gch
/tmp/input.cc:3:2: error: cannot compile this l-value expression yet
        foo(FOO);
        ^~~
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang-13 -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name input.gch -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/tmp -resource-dir /usr/lib/clang/13.0.1 -fdebug-compilation-dir=/tmp -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/input-11f595.o -x precompiled-header input.gch
1.	<eof> parser at end of file
2.	/tmp/input.cc:2:5: LLVM IR generation of declaration 'main'
3.	/tmp/input.cc:2:5: Generating code for declaration 'main'
 #0 0x00007fd23586cea7 (/usr/lib/libLLVM-13.so+0xba6ea7)
 #1 0x00007fd23586a6a6 (/usr/lib/libLLVM-13.so+0xba46a6)
 #2 0x00007fd234920da0 __restore_rt sigaction.c:0:0
 #3 0x00007fd235a39b48 llvm::PointerType::get(llvm::Type*, unsigned int) (/usr/lib/libLLVM-13.so+0xd73b48)
 #4 0x00007fd23cdec3bd clang::CodeGen::CodeGenFunction::EmitUnsupportedLValue(clang::Expr const*, char const*) (/usr/lib/libclang-cpp.so.13+0x180e3bd)
 #5 0x00007fd23ce020e5 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) (/usr/lib/libclang-cpp.so.13+0x18240e5)
 #6 0x00007fd23ce12222 clang::CodeGen::CodeGenFunction::EmitCallee(clang::Expr const*) (/usr/lib/libclang-cpp.so.13+0x1834222)
 #7 0x00007fd23ce1266b clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/usr/lib/libclang-cpp.so.13+0x183466b)
 #8 0x00007fd23ce1dbbe (/usr/lib/libclang-cpp.so.13+0x183fbbe)
 #9 0x00007fd23ce57e52 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/usr/lib/libclang-cpp.so.13+0x1879e52)
#10 0x00007fd23ce11cdf clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/usr/lib/libclang-cpp.so.13+0x1833cdf)
#11 0x00007fd23ce11eb6 clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) (/usr/lib/libclang-cpp.so.13+0x1833eb6)
#12 0x00007fd23cf1f972 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/usr/lib/libclang-cpp.so.13+0x1941972)
#13 0x00007fd23cf20822 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/lib/libclang-cpp.so.13+0x1942822)
#14 0x00007fd23cf78446 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/usr/lib/libclang-cpp.so.13+0x199a446)
#15 0x00007fd23cf98d40 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/lib/libclang-cpp.so.13+0x19bad40)
#16 0x00007fd23cfa1d78 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/lib/libclang-cpp.so.13+0x19c3d78)
#17 0x00007fd23cf9fb75 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/lib/libclang-cpp.so.13+0x19c1b75)
#18 0x00007fd23cfc01bf (/usr/lib/libclang-cpp.so.13+0x19e21bf)
#19 0x00007fd23d00f5a4 (/usr/lib/libclang-cpp.so.13+0x1a315a4)
#20 0x00007fd23cf2c779 (/usr/lib/libclang-cpp.so.13+0x194e779)
#21 0x00007fd23d3de019 (/usr/lib/libclang-cpp.so.13+0x1e00019)
#22 0x00007fd23d3683ab non-virtual thunk to clang::ASTReader::StartTranslationUnit(clang::ASTConsumer*) (/usr/lib/libclang-cpp.so.13+0x1d8a3ab)
#23 0x00007fd23bfcc0f6 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.13+0x9ee0f6)
#24 0x00007fd23d5548b9 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.13+0x1f768b9)
#25 0x00007fd23d4fabbf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.13+0x1f1cbbf)
#26 0x00007fd23d59ff20 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.13+0x1fc1f20)
#27 0x000055fe56ac784c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-13+0x1684c)
#28 0x000055fe56ac9c2d (/usr/bin/clang-13+0x18c2d)
#29 0x000055fe56abe185 main (/usr/bin/clang-13+0xd185)
#30 0x00007fd23490bb25 __libc_start_main (/usr/lib/libc.so.6+0x27b25)
#31 0x000055fe56ac048e _start (/usr/bin/clang-13+0xf48e)
clang-13: error: unable to execute command: Segmentation fault (core dumped)
clang-13: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-13: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

### PR DESCRIPTION
**Pull request by rajkumarananthu**
The issue #53952 is reported indicating clang is giving a crashing pch file, when hasErrors is been passed incorrectly to WriteAST method.

To fix the issue, I have a added an assertion to make sure the given value of ASTHasCompilerErrors is matching with Preprocessor diagnostics. And this assertion will get triggered inside Debug builds.

For release builds, based on the conditional check, forcefully set the ASTHasCompilerErrors member variable to a valid value from Preprocessor.

### CODE REVIEW

File: clang/lib/Serialization/ASTWriter.cpp [hunk 1]
```diff
@@ -4628,6 +4628,12 @@ ASTFileSignature ASTWriter::WriteAST(Sema &SemaRef, StringRef OutputFile,
   WritingAST = true;
 
   ASTHasCompilerErrors = hasErrors;
+  bool trueHasErrors = SemaRef.PP.getDiagnostics().hasUncompilableErrorOccurred();
```
Comment (shafik) [inline clang/lib/Serialization/ASTWriter.cpp:4631]: So this logic seems wrong. You are on one hand asserting `ASTHasCompilerErrors == trueHasErrors` and yet checking if they are not equal.


Is `getDiagnostics().hasUncompilableErrorOccurred()` in `ASTUnit::serialize` not the same as `SemaRef.PP.getDiagnostics().hasUncompilableErrorOccurred()`?

**Review by shafik — COMMENTED** [review]
The fix does not look correct but perhaps someone else will have more insight.

File: clang/lib/Serialization/ASTWriter.cpp (hunk 1 above)
Comment (rajkumarananthu) [reply clang/lib/Serialization/ASTWriter.cpp:4631]: Hi @shafik, thanks for your time for the review.

The scenario here is that, at line 4630 you can see the `ASTHasCompilerErrors` is being set using `hasErrors` which is an input to the method here `ASTWriter::WriteAST()`.

And if you see the description of the issue reported, the user is purposely passing the `hasErrors` as `false` even when there is a compiler error in the input file, because of this clang is giving a crashing pch file.

So, if the `hasErrors` is not a valid value, I am setting it to the correct value. May be I can just remove all the unnecessary code and just directly assign `ASTHasCompilerErrors = SemaRef.PP.getDiagnostics().hasUncompilableErrorOccured();` which will be correct.

And assertion I have added to detect this in debug build early, may be I am wrong, sorry for the confusion, it should not behave differently in release and debug builds.

Let me know what you think of this?

Thanks
Rajkumar Ananthu.

Comment (AaronBallman) [reply clang/lib/Serialization/ASTWriter.cpp:4631]: I would rather fix this by disallowing the user from passing `hasErrors` as an argument at all. The only callers of this API are all passing the same thing: `PP.getDiagnostics().hasUncompilableErrorOccured()`, so let's remove the parameter and use this directly. This makes the interface more simple and it fixes the crash; WDYT?

Comment (rajkumarananthu) [reply clang/lib/Serialization/ASTWriter.cpp:4631]: Yeah @AaronBallman, that does sound better, I will remove the argument and update the pull request. Thanks for the review.

Comment (rajkumarananthu) [reply clang/lib/Serialization/ASTWriter.cpp]: Hi Team, Added a new commit by removing the argument `hasErrors` to the method `ASTWriter::WriteAST`.

**Review by AaronBallman — APPROVED** [review]
Thank you for the fix, the changes LGTM! The precommit CI failure appears to be unrelated to these changes. I don't think this requires test coverage or a release note.

**Comment by rajkumarananthu** [comment]
Hi @AaronBallman I could see a revert of my change here: https://reviews.llvm.org/rGa6acf3fd49a20c570a390af2a3c84e10b9545b68

Can you please help me confirm whether the change is accepted or reverted. Should we resubmit the changes here?

Thanks
Rajkumar Ananthu

**Comment by phyBrackets** [comment]
Not sure but the issue in the reverted commit seems like a backporting issue, so you may need to backport the changes in case. But I'd say wait for Aaron comment.

**Comment by AaronBallman** [comment]
There was a mix-up. I landed the original changes, @kazutakahirata saw what appeared to be a linker error after pulling those changes down and did a revert, but that turned out to be an issue local to their machine so I've reverted the revert (re-landing the original changes). So the code should be in now and should hopefully stay in,.

**Comment by rajkumarananthu** [comment]
Thanks for taking care of this @AaronBallman
