### PR TITLE
[CLANG][DWARF] Handle DIE offset collision in DW_IDX_parent

### LINKED ISSUE #93886: debug_names incorrect parent due to collision between CU and TU
from https://github.com/llvm/llvm-project/pull/91808#issuecomment-2138480664

```
namespace A {
namespace B {
struct C { };
struct D { };
}  // namespace B
}  // namespace A
void f1(A::B::C, A::B::D) { }
```
```
$ clang++-tot names.cpp -g2 -O0 -gpubnames -c -fdebug-types-section && llvm-dwarfdump-tot -debug-names names.o | grep "Name \|Entry \|Tag: \|DW_IDX\|String: "
```
```
      String: 0x000000a0 "_Z2f1N1A1B1CENS0_1DE"
      Entry @ 0xe5 {
        Tag: DW_TAG_subprogram
        DW_IDX_die_offset: 0x00000023
        DW_IDX_parent: <parent not indexed>
```
```
      String: 0x000000b5 "A"
      Entry @ 0xeb {
        Tag: DW_TAG_namespace
        DW_IDX_type_unit: 0x00
        DW_IDX_die_offset: 0x00000023
        DW_IDX_parent: <parent not indexed>
      Entry @ 0xf1 {
        Tag: DW_TAG_namespace
        DW_IDX_type_unit: 0x01
        DW_IDX_die_offset: 0x00000023
        DW_IDX_parent: <parent not indexed>
      Entry @ 0xf7 {
        Tag: DW_TAG_namespace
        DW_IDX_die_offset: 0x00000044
        DW_IDX_parent: <parent not indexed>
```
```
      String: 0x000000b7 "B"
      Entry @ 0x103 {
        Tag: DW_TAG_namespace
        DW_IDX_type_unit: 0x00
        DW_IDX_die_offset: 0x00000025
        DW_IDX_parent: Entry @ 0xe5
      Entry @ 0x10d {
        Tag: DW_TAG_namespace
        DW_IDX_type_unit: 0x01
        DW_IDX_die_offset: 0x00000025
        DW_IDX_parent: Entry @ 0xf1
      Entry @ 0x117 {
        Tag: DW_TAG_namespace
        DW_IDX_die_offset: 0x00000046
        DW_IDX_parent: Entry @ 0xf7
```

So the second and third "B" entries match up with the appropriate "A" entries, but the first jumps over to refer to a different DIE in the CU that has the same offset.

This is because the UniqueID on a unit is only unique within that type of unit (it's unique across CUs and, separately, unique across TUs) - so the "DieOffsetAndUnitID" is not a globally unique identifier for an entry - it'd need the type of unit in there too to completely uniquify it.

Adding this patch is enough to expose the issue more directly:
```
diff --git a/llvm/lib/CodeGen/AsmPrinter/AccelTable.cpp b/llvm/lib/CodeGen/AsmPrinter/AccelTable.cpp
index 5b679fd3b9f9..cc8b8d1881ed 100644
--- a/llvm/lib/CodeGen/AsmPrinter/AccelTable.cpp
+++ b/llvm/lib/CodeGen/AsmPrinter/AccelTable.cpp
@@ -615,8 +615,10 @@ Dwarf5AccelTableWriter::Dwarf5AccelTableWriter(
 
   for (auto &Bucket : Contents.getBuckets())
     for (auto *Hash : Bucket)
-      for (auto *Value : Hash->getValues<DWARF5AccelTableData *>())
-        IndexedOffsets.insert(Value->getDieOffsetAndUnitID());
+      for (auto *Value : Hash->getValues<DWARF5AccelTableData *>()) {
+        auto Inserted = IndexedOffsets.insert(Value->getDieOffsetAndUnitID()).second;
+        assert(Inserted);
+      }
 
   populateAbbrevsMap();
 }
```
The two different units (one CU, one TU) with the same unit ID end up colliding in the `IndexedOffsets` set - and only one ends up in there, and so then the loop here:
```
for (OffsetAndUnitID Offset : IndexedOffsets)
  DIEOffsetToAccelEntryLabel.insert({Offset, Asm->createTempSymbol("")});
```
Only inserts the copy once, oh... and /this/ code:
```
if (EmittedAccelEntrySymbols.insert(EntrySymbol).second)
  Asm->OutStreamer->emitLabel(EntrySymbol);
```
Silently skips emitting the label even though it matches more than one entry unintentionally, because it can match more than one entry /intentionally/ (if there's multiple entries for exactly the same entity, but known by different names (like the mangled name and unmangled name)).

So, yeah.

Hmm, I guess at least the type unit number probably isn't gapless - there are cases where we create a type unit and then potentially throw it away (see the TypeUnitsUnderConstruction stuff) - but we don't reuse the type unit number. 

So, maybe it's possible to use a single numbering for CUs and TUs, gaps and all?

The only thing I was worried about was that some code might be using the numbering to index into an array of units at some point, but if that's not the case - great! Probably more intuitive that they be totally unique numbers.

### PR DESCRIPTION
**Pull request by ayermolo**
This fixes https://github.com/llvm/llvm-project/issues/93886. The UnitID is not
unique between CUs and TUs. This led to DW_IDX_parent to point ot an entry for a
DIE in a CU if it had the same relative offset as a TU die.

Added a IsTU to the hash for parent chain.

### CODE REVIEW

File: llvm/include/llvm/CodeGen/AccelTable.h [hunk 1]
```diff
@@ -257,17 +257,37 @@ class AppleAccelTableData : public AccelTableData {
 
 /// Helper class to identify an entry in DWARF5AccelTable based on their DIE
 /// offset and UnitID.
-struct OffsetAndUnitID : std::pair<uint64_t, uint32_t> {
```
Comment (felipepiovezan) [inline llvm/include/llvm/CodeGen/AccelTable.h:260]: would it make it sense to just use tuple here to avoid having to define the dense map boilerplate?

**Review by felipepiovezan — APPROVED** [review]
Thanks for fixing this! LGTM but left a suggestion to use a tuple if you also believe it would simplify the code

File: llvm/include/llvm/CodeGen/AccelTable.h (hunk 1 above)
Comment (ayermolo) [reply llvm/include/llvm/CodeGen/AccelTable.h:260]: I don't really have a strong opinion. Poking around I don't really see tuple being used with DenseMap. More standard approach seems this boilerplate code. 
@dwblaikie to break a tie? :)

**Comment by ayermolo** [comment]
Merged, if there is a strong opinion about tuple I can put up follow up PR.

**Comment by dwblaikie** [comment]
Out on vacation until tomorrow, but did you try making the die numbering unique across type and compile units? I would've thought that might be simpler, but maybe had too many knock-on effects/other things that'd need fixing/changing.

**Comment by fmayer** [comment]
I think this broke the ASan bot:

```
=================================================================
==120988==ERROR: AddressSanitizer: heap-use-after-free on address 0x52100002d11c at pc 0x563e760d1c6d bp 0x7f0eef1c59d0 sp 0x7f0eef1c59c8
READ of size 2 at 0x52100002d11c thread T20
    #0 0x563e760d1c6c in getTag /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/CodeGen/DIE.h:855:38
    #1 0x563e760d1c6c in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:1362:34
    #2 0x563e760d1c6c in void llvm::function_ref<void (llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo&)>::callback_fn<llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitDWARFv5DebugNamesSection(llvm::Triple const&)::$_0::operator()(llvm::dwarf_linker::parallel::DwarfUnit*) const::'lambda'(llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo const&)>(long, llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo&) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #3 0x563e76114898 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #4 0x563e76114898 in forEach /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/ArrayList.h:67:9
    #5 0x563e76114898 in llvm::dwarf_linker::parallel::CompileUnit::forEachAcceleratorRecord(llvm::function_ref<void (llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo&)>) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.h:576:24
    #6 0x563e760d12e7 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:1350:9
    #7 0x563e760d12e7 in void llvm::function_ref<void (llvm::dwarf_linker::parallel::DwarfUnit*)>::callback_fn<llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitDWARFv5DebugNamesSection(llvm::Triple const&)::$_0>(long, llvm::dwarf_linker::parallel::DwarfUnit*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #8 0x563e760be1b1 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #9 0x563e760be1b1 in forEachCompileAndTypeUnit /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:1088:9
    #10 0x563e760be1b1 in llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitDWARFv5DebugNamesSection(llvm::Triple const&) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:1348:3
    #11 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #12 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #13 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:214:11
    #14 0x563e76778eb5 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #15 0x563e76778eb5 in __call<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:225:5
    #16 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:171:12
    #17 0x563e76778eb5 in std::__1::__function::__func<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0, std::__1::allocator<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0>, void ()>::operator()() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:313:10
    #18 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #19 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #20 0x563e76774e92 in llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:141:7
    #21 0x563e767751e0 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:36
    #22 0x563e767751e0 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #23 0x563e767751e0 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:193:3
    #24 0x563e767751e0 in void* std::__1::__thread_proxy[abi:nn190000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:202:3
    #25 0x563e726d1646 in asan_thread_start(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
    #26 0x7f0f03497b59  (/lib/x86_64-linux-gnu/libc.so.6+0x97b59) (BuildId: 502d55a5e424889ddb2846eb6dbeddaedd75b323)
    #27 0x7f0f035285fb  (/lib/x86_64-linux-gnu/libc.so.6+0x1285fb) (BuildId: 502d55a5e424889ddb2846eb6dbeddaedd75b323)
0x52100002d11c is located 28 bytes inside of 4096-byte region [0x52100002d100,0x52100002e100)
freed by thread T6 here:
    #0 0x563e7270b327 in operator delete(void*, unsigned long, std::align_val_t) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:173:3
    #1 0x563e7610a61d in Deallocate /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/AllocatorBase.h:99:5
    #2 0x563e7610a61d in DeallocateSlabs /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:361:28
    #3 0x563e7610a61d in ~BumpPtrAllocatorImpl /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:98:5
    #4 0x563e7610a61d in llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(std::__1::optional<std::__1::reference_wrapper<llvm::Triple const>>, llvm::dwarf_linker::parallel::TypeUnit*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.cpp:1288:1
    #5 0x563e760c96c8 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:672:32
    #6 0x563e760c96c8 in llvm::Expected<bool> llvm::function_ref<llvm::Expected<bool> ()>::callback_fn<llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(llvm::dwarf_linker::parallel::CompileUnit&, llvm::dwarf_linker::parallel::TypeUnit*, llvm::dwarf_linker::parallel::CompileUnit::Stage)::$_0>(long) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #7 0x563e760b3643 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #8 0x563e760b3643 in llvm::dwarf_linker::finiteLoop(llvm::function_ref<llvm::Expected<bool> ()>, unsigned long) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/DWARFLinker/Utils.h:30:45
    #9 0x563e760b44c4 in llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(llvm::dwarf_linker::parallel::CompileUnit&, llvm::dwarf_linker::parallel::TypeUnit*, llvm::dwarf_linker::parallel::CompileUnit::Stage) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:597:19
    #10 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #11 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:242:11
    #12 0x563e767790a9 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:240:16) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #13 0x563e767790a9 in __call<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:240:16) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:225:5
    #14 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:171:12
    #15 0x563e767790a9 in std::__1::__function::__func<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0, std::__1::allocator<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0>, void ()>::operator()() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:313:10
    #16 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #17 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #18 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:214:11
    #19 0x563e76778eb5 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #20 0x563e76778eb5 in __call<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:225:5
    #21 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:171:12
    #22 0x563e76778eb5 in std::__1::__function::__func<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0, std::__1::allocator<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0>, void ()>::operator()() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:313:10
    #23 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #24 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #25 0x563e76774e92 in llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:141:7
    #26 0x563e767751e0 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:36
    #27 0x563e767751e0 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #28 0x563e767751e0 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:193:3
    #29 0x563e767751e0 in void* std::__1::__thread_proxy[abi:nn190000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:202:3
    #30 0x563e726d1646 in asan_thread_start(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
previously allocated by thread T6 here:
    #0 0x563e7270a4e2 in operator new(unsigned long, std::align_val_t) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #1 0x563e7285836e in Allocate /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/AllocatorBase.h:92:12
    #2 0x563e7285836e in StartNewSlab /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:344:42
    #3 0x563e7285836e in llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>::AllocateSlow(unsigned long, unsigned long, llvm::Align) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:200:5
    #4 0x563e7610d2e9 in Allocate /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:176:12
    #5 0x563e7610d2e9 in Allocate /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:214:12
    #6 0x563e7610d2e9 in operator new<llvm::MallocAllocator, 4096UL, 4096UL, 128UL> /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/Allocator.h:448:20
    #7 0x563e7610d2e9 in get /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/CodeGen/DIE.h:850:12
    #8 0x563e7610d2e9 in createDIE /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DIEGenerator.h:32:17
    #9 0x563e7610d2e9 in llvm::dwarf_linker::parallel::CompileUnit::createPlainDIEandCloneAttributes(llvm::DWARFDebugInfoEntry const*, llvm::dwarf_linker::parallel::DIEGenerator&, unsigned long&, std::__1::optional<long>&, std::__1::optional<long>&) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.cpp:1399:33
    #10 0x563e7610ac90 in llvm::dwarf_linker::parallel::CompileUnit::cloneDIE(llvm::DWARFDebugInfoEntry const*, llvm::StringMapEntry<std::__1::atomic<llvm::dwarf_linker::parallel::TypeEntryBody*>>*, unsigned long, std::__1::optional<long>, std::__1::optional<long>, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>&, llvm::dwarf_linker::parallel::TypeUnit*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.cpp:1309:23
    #11 0x563e7610a20d in llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(std::__1::optional<std::__1::reference_wrapper<llvm::Triple const>>, llvm::dwarf_linker::parallel::TypeUnit*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.cpp:1248:44
    #12 0x563e760c96c8 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:672:32
    #13 0x563e760c96c8 in llvm::Expected<bool> llvm::function_ref<llvm::Expected<bool> ()>::callback_fn<llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(llvm::dwarf_linker::parallel::CompileUnit&, llvm::dwarf_linker::parallel::TypeUnit*, llvm::dwarf_linker::parallel::CompileUnit::Stage)::$_0>(long) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #14 0x563e760b3643 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #15 0x563e760b3643 in llvm::dwarf_linker::finiteLoop(llvm::function_ref<llvm::Expected<bool> ()>, unsigned long) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/DWARFLinker/Utils.h:30:45
    #16 0x563e760b44c4 in llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(llvm::dwarf_linker::parallel::CompileUnit&, llvm::dwarf_linker::parallel::TypeUnit*, llvm::dwarf_linker::parallel::CompileUnit::Stage) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:597:19
    #17 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #18 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:242:11
    #19 0x563e767790a9 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:240:16) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #20 0x563e767790a9 in __call<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:240:16) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:225:5
    #21 0x563e767790a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:171:12
    #22 0x563e767790a9 in std::__1::__function::__func<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0, std::__1::allocator<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_0>, void ()>::operator()() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:313:10
    #23 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #24 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #25 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:214:11
    #26 0x563e76778eb5 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #27 0x563e76778eb5 in __call<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:213:9) &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:225:5
    #28 0x563e76778eb5 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:171:12
    #29 0x563e76778eb5 in std::__1::__function::__func<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0, std::__1::allocator<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0>, void ()>::operator()() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:313:10
    #30 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:430:12
    #31 0x563e76774e92 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__functional/function.h:989:10
    #32 0x563e76774e92 in llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:141:7
    #33 0x563e767751e0 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:36
    #34 0x563e767751e0 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #35 0x563e767751e0 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:193:3
    #36 0x563e767751e0 in void* std::__1::__thread_proxy[abi:nn190000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:202:3
    #37 0x563e726d1646 in asan_thread_start(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
Thread T20 created by T1 here:
    #0 0x563e726b9331 in pthread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:250:3
    #1 0x563e76774573 in __libcpp_thread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/support/pthread.h:182:10
    #2 0x563e76774573 in thread<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30), 0> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:212:14
    #3 0x563e76774573 in construct<std::__1::thread, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator.h:166:24
    #4 0x563e76774573 in construct<std::__1::thread, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30), 0> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator_traits.h:319:9
    #5 0x563e76774573 in __construct_one_at_end<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/vector:920:5
    #6 0x563e76774573 in emplace_back<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/vector:1510:5
    #7 0x563e76774573 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:17
    #8 0x563e76774573 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:27)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #9 0x563e76774573 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:27)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:193:3
    #10 0x563e76774573 in void* std::__1::__thread_proxy[abi:nn190000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()>>(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:202:3
    #11 0x563e726d1646 in asan_thread_start(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
Thread T1 created by T0 here:
    #0 0x563e726b9331 in pthread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:250:3
    #1 0x563e767726d2 in __libcpp_thread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/support/pthread.h:182:10
    #2 0x563e767726d2 in thread<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:27), 0> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:212:14
    #3 0x563e767726d2 in ThreadPoolExecutor /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:15
    #4 0x563e767726d2 in llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::Creator::call() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:95:38
    #5 0x563e76767168 in llvm::ManagedStaticBase::RegisterManagedStatic(void* (*)(), void (*)(void*)) const /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/ManagedStatic.cpp:34:19
    #6 0x563e767715c9 in operator* /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/ManagedStatic.h:89:7
    #7 0x563e767715c9 in getDefaultExecutor /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:180:53
    #8 0x563e767715c9 in llvm::parallel::getThreadCount() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:187:10
    #9 0x563e760a780f in PerThreadAllocator /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/Support/PerThreadBumpPtrAllocator.h:31:25
    #10 0x563e760a780f in LinkingGlobalData /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerGlobalData.h:85:7
    #11 0x563e760a780f in llvm::dwarf_linker::parallel::DWARFLinkerImpl::DWARFLinkerImpl(std::__1::function<void (llvm::Twine const&, llvm::StringRef, llvm::DWARFDie const*)>, std::__1::function<void (llvm::Twine const&, llvm::StringRef, llvm::DWARFDie const*)>) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp:22:18
    #12 0x563e760a7500 in make_unique<llvm::dwarf_linker::parallel::DWARFLinkerImpl, std::__1::function<void (const llvm::Twine &, llvm::StringRef, const llvm::DWARFDie *)> &, std::__1::function<void (const llvm::Twine &, llvm::StringRef, const llvm::DWARFDie *)> &> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/unique_ptr.h:620:30
    #13 0x563e760a7500 in llvm::dwarf_linker::parallel::DWARFLinker::createLinker(std::__1::function<void (llvm::Twine const&, llvm::StringRef, llvm::DWARFDie const*)>, std::__1::function<void (llvm::Twine const&, llvm::StringRef, llvm::DWARFDie const*)>) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/DWARFLinker/Parallel/DWARFLinker.cpp:19:10
    #14 0x563e727a3d93 in llvm::Error llvm::dwarfutil::linkDebugInfoImpl<llvm::dwarf_linker::parallel::DWARFLinker>(llvm::object::ObjectFile&, llvm::dwarfutil::Options const&, llvm::raw_pwrite_stream&) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/tools/llvm-dwarfutil/DebugInfoLinker.cpp:336:7
    #15 0x563e727a39eb in llvm::dwarfutil::linkDebugInfo(llvm::object::ObjectFile&, llvm::dwarfutil::Options const&, llvm::raw_pwrite_stream&) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/tools/llvm-dwarfutil/DebugInfoLinker.cpp:472:12
    #16 0x563e7270e679 in applyCLOptions /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/tools/llvm-dwarfutil/llvm-dwarfutil.cpp:451:21
    #17 0x563e7270e679 in main /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/tools/llvm-dwarfutil/llvm-dwarfutil.cpp:527:11
    #18 0x7f0f0342814f  (/lib/x86_64-linux-gnu/libc.so.6+0x2814f) (BuildId: 502d55a5e424889ddb2846eb6dbeddaedd75b323)
Thread T6 created by T1 here:
    #0 0x563e726b9331 in pthread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:250:3
    #1 0x563e76774573 in __libcpp_thread_create /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/support/pthread.h:182:10
    #2 0x563e76774573 in thread<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30), 0> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:212:14
    #3 0x563e76774573 in construct<std::__1::thread, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator.h:166:24
    #4 0x563e76774573 in construct<std::__1::thread, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30), 0> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__memory/allocator_traits.h:319:9
    #5 0x563e76774573 in __construct_one_at_end<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/vector:920:5
    #6 0x563e76774573 in emplace_back<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:30)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/vector:1510:5
    #7 0x563e76774573 in operator() /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:64:17
    #8 0x563e76774573 in __invoke<(lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:27)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__type_traits/invoke.h:150:25
    #9 0x563e76774573 in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/lib/Support/Parallel.cpp:62:27)> /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:193:3
    #10 0x563e76774573 in void* std::__1::__thread_proxy[abi:nn190000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()>>(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/libcxx_build_asan/include/c++/v1/__thread/thread.h:202:3
    #11 0x563e726d1646 in asan_thread_start(void*) /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
SUMMARY: AddressSanitizer: heap-use-after-free /b/sanitizer-x86_64-linux-bootstrap-asan/build/llvm-project/llvm/include/llvm/CodeGen/DIE.h:855:38 in getTag
Shadow bytes around the buggy address:
  0x52100002ce80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52100002cf00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52100002cf80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52100002d000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52100002d080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x52100002d100: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
  0x52100002d180: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x52100002d200: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x52100002d280: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x52100002d300: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x52100002d380: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==120988==ABORTING

```

**Comment by ayermolo** [comment]
Thanks for flagging.
Looks like issue is in: llvm/lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp

```
DebugNames->addName(
            *DebugStrStrings.getExistingEntry(Info.String), Info.OutOffset,
            std::nullopt /*ParentDIEOffset*/, Info.Tag, CU->getUniqueID(),
            CU->getOutUnitDIE()->getTag() == dwarf::DW_TAG_type_unit);
```
Passing false instead fixes asan.

**Comment by fmayer** [comment]
Passing false to what exactly?

**Comment by ayermolo** [comment]
> Passing false to what exactly?

to DebugNames->addName, instead of CU->getOutUnitDIE()->getTag() == dwarf::DW_TAG_type_unit.

Basically issue was I was accessing getOutUnitDIE which was allocated local BumpAllocator in CompileUnit::cloneAndEmit. So memory was garbage.

**Comment by ayermolo** [comment]
Fixed asan: https://github.com/llvm/llvm-project/pull/95339
