### PR TITLE
[SPARC] Allow overaligned `alloca`s

### LINKED ISSUE #89569: llc crash when exec 'llc -mtriple=sparcel'
# description
when i use 'llc' to translate an IR, crash happened. I don't know whether it's a bug of 'llc' and want to be sure about it.

thank you for your help!

# bug ir
```
define i32 @main() {
  
  br label %2

2: 
  %A = alloca i64, align 16
  ret i32 0
}
```
# cmd
`llc -mtriple=sparcel test.ll`

# crash info
https://godbolt.org/z/hEafj9887

### PR DESCRIPTION
**Pull request by koachan**
SPARC doesn't do stack realignment, so let LLVM know about it in `SparcFrameLowering`. This has the side effect of making all overaligned allocations go through `LowerDYNAMIC_STACKALLOC`, so implement the missing logic there too for overaligned allocations.
This makes the SPARC backend not crash on overaligned `alloca`s and fix https://github.com/llvm/llvm-project/issues/89569.

### CODE REVIEW

File: llvm/lib/Target/Sparc/SparcISelLowering.cpp [hunk 1]
```diff
@@ -2811,12 +2818,17 @@ static SDValue LowerDYNAMIC_STACKALLOC(SDValue Op, SelectionDAG &DAG,
     regSpillArea = 96;
   }
 
-  unsigned SPReg = SP::O6;
-  SDValue SP = DAG.getCopyFromReg(Chain, dl, SPReg, VT);
-  SDValue NewSP = DAG.getNode(ISD::SUB, dl, VT, SP, Size); // Value
-  Chain = DAG.getCopyToReg(SP.getValue(1), dl, SPReg, NewSP);    // Output chain
+  AlignedPtr = DAG.getNode(ISD::SUB, dl, VT, AlignedPtr, Size);
```
Comment (s-barannikov) [inline llvm/lib/Target/Sparc/SparcISelLowering.cpp:2821]: The subtraction should be done before aligning to avoid excessive stack usage.
Take for example
`old sp = 40, size = 8, align = 16`
The current formula gives:
`new sp = (40 - 16) & -16 - 8 = 8`
That is, it allocates 24 bytes instead of just 8 (which would be sufficient because `40 - 8 = 32` is 16-byte aligned).

File: llvm/test/CodeGen/SPARC/alloca-align.ll [hunk 2]
```diff
@@ -0,0 +1,113 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
+; RUN: llc -march=sparc < %s | FileCheck %s --check-prefixes=CHECK32
+; RUN: llc -march=sparcv9 < %s | FileCheck %s --check-prefixes=CHECK64
+
+define void @variable_alloca_with_overalignment(i32 %num) {
```
Comment (s-barannikov) [inline llvm/test/CodeGen/SPARC/alloca-align.ll:5]: To avoid generation of cfi directives:
```suggestion
define void @variable_alloca_with_overalignment(i32 %num) nounwind {
```

**Comment by rorth** [comment]
I'm currently building with this patch on Solaris/sparcv9, initially as is.  Later I'm going to enable ASan on 32-bit SPARC to see how this goes (Issue #57626).

**Comment by rorth** [comment]
I've made some progess on the 32-bit Solaris/sparc side:
```
Failed Tests (36):
  AddressSanitizer-Unit :: ./Asan-sparc-calls-Dynamic-Test/65/93
  AddressSanitizer-Unit :: ./Asan-sparc-calls-Test/65/93
  AddressSanitizer-Unit :: ./Asan-sparc-inline-Dynamic-Test/65/93
  AddressSanitizer-Unit :: ./Asan-sparc-inline-Test/65/93
  AddressSanitizer-sparc-sunos :: TestCases/Posix/stack-overflow.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_big_alignment.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_detect_custom_size_.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_loop_unpoisoning.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_overflow_partial.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_overflow_right.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_safe_access.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_underflow_left.cpp
  AddressSanitizer-sparc-sunos :: TestCases/alloca_vla_interact.cpp
  AddressSanitizer-sparc-sunos :: TestCases/global-overflow.cpp
  AddressSanitizer-sparc-sunos :: TestCases/large_func_test.cpp
  AddressSanitizer-sparc-sunos :: TestCases/vla_chrome_testcase.cpp
  AddressSanitizer-sparc-sunos :: TestCases/vla_condition_overflow.cpp
  AddressSanitizer-sparc-sunos :: TestCases/vla_loop_overfow.cpp
  AddressSanitizer-sparc-sunos :: TestCases/zero_page_pc.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/Posix/stack-overflow.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_big_alignment.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_detect_custom_size_.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_loop_unpoisoning.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_overflow_partial.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_overflow_right.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_safe_access.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_underflow_left.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_vla_interact.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/global-overflow.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/large_func_test.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/vla_chrome_testcase.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/vla_condition_overflow.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/vla_loop_overfow.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/zero_page_pc.cpp
  SanitizerCommon-asan-sparc-SunOS :: sanitizer_coverage_trace_pc_guard-dso.cpp
  SanitizerCommon-asan-sparc-SunOS :: sanitizer_coverage_trace_pc_guard.cpp

```
Some of the failures are generic issues with the testcases (e.g. performing unaligned accesses on a strict-alignment target), others might be an endianess issue, but a considerable part of the failures may be related to an issue with your patch, e.g.
`AddressSanitizer-sparc-sunos :: TestCases/alloca_big_alignment.cpp` which, like quite a number of others, `FAIL`s like
```
Assertion failed: !(reinterpret_cast<uintptr_t>(str) & 127L), file /vol/llvm/src/llvm-project/local/compiler-rt/test/asan/TestCases/alloca_big_alignment.cpp, line 10
```
ISTM that your patch doesn't yet heed `__attribute__((aligned(128)))`.

The Linux/sparc64 side of things is considerably worse, unfortunately: quite a number of ASan tests just hang, and while the unittests do work, several 64-bit tests `SEGV`.  Getting this to work will probably take quite a debugging effort.  I guess I'll concentrate on the Solaris side, at least initially.

**Comment by rorth** [comment]
Just for reference, I've posted the patches I've used for my ASan testing: PR #107403 for the driver side and PR #107405 for enabling the ASan tests in `compiler-rt`.

**Comment by rorth** [comment]
> > Just for reference, I've posted the patches I've used for my ASan testing: PR #107403 for the driver side and PR #107405 for enabling the ASan tests in `compiler-rt`.
> 
> Are these patches for Solaris only or do they apply for Linux too? I'd like to try the asan tests too, but after applying them on my Linux box it seems like `check-asan` is still not available:
> 
> ```
> $ ninja check-asan
> ninja: error: unknown target 'check-asan', did you mean 'check-all'?
> ```

The patches work on Linux/sparc64, too.  You don't need the driver one (`clang` on Linux always assumes ASan is supported).  I'd revised the `compiler-rt` test one last night when I managed to avoid hangs in many ASan tests on Linux.  Besides, I've removed `sparcv9` again: while there is some support for that in `compiler-rt`, neither `clang` nor `gcc` have anything matching, so there were hundreds of `sparcv9` ASan failures.  I'm currently finishing one that avoids failures on tests involving stack overflows (works on Solaris already, needs some tweeks for Linux) and posted two testsuite adjustments for ASan on SPARC in general (PRs #108206 and #108200).  There's also one to disable `InstallAtForkHandler` on Linux/sparc64, but that may well be a hack rather than a fix.

I guess it's best if you give me a day or two to finish this stuff.

Thanks a lot for your work, which finally will allow `clang` ASan support to be on par with `gcc`.

**Comment by rorth** [comment]
Most patches should be in place now.  On Solaris/sparcv9, there are only two failures left:
```
  AddressSanitizer-sparc-sunos :: TestCases/alloca_big_alignment.cpp

Assertion failed: !(reinterpret_cast<uintptr_t>(str) & 127L), file compiler-rt/test/asan/TestCases/alloca_big_alignment.cpp, line 10

  AddressSanitizer-sparc-sunos :: TestCases/alloca_vla_interact.cpp

Assertion failed: q == top, file compiler-rt/test/asan/TestCases/alloca_vla_interact.cpp, line 45
```
The necessary patches are PRs #107405, #108206, #108200, and #108542.

There's one patch left that's in final testing: tests like `AddressSanitizer-sparc-sunos :: TestCases/Posix/stack-overflow.cpp` that involve stack overflows currently incur a second `SEGV` when trying to read the frame pointer from the (now invalid) stack.  The patch to avoid that is working on Solaris.  It requires a V9 insn which can only be used with `-mcpu=v9` on Linux/sparc64.  That isn't the default however, and a [patch to enable it](https://reviews.llvm.org/D130688) has been stalled for 2 years now.  I'm currently trying to finish it.

There are several more failures on Linux/sparc64, some of which involve (lack of) `printf` interception as reported in Issue #108392, while a few others require further analysis.

File: llvm/lib/Target/Sparc/SparcISelLowering.cpp (hunk 1 above)
Comment (s-barannikov) [reply llvm/lib/Target/Sparc/SparcISelLowering.cpp]: It should be `(ptr - size) & -align`.

**Comment by rorth** [comment]
Your last change brought the Solaris/sparcv9 failures down to just one:
```
  AddressSanitizer-sparc-sunos :: TestCases/alloca_vla_interact.cpp
  AddressSanitizer-sparc-sunos-dynamic :: TestCases/alloca_vla_interact.cpp
```
same as reported before:
```
Assertion failed: q == top, file /vol/llvm/src/llvm-project/local/compiler-rt/test/asan/TestCases/alloca_vla_interact.cpp, line 45
```
Linux/sparc64 is worse, but AFAICS none of the failures there are related to this patch, just Linux/sparc64 specific issues.

Thanks again!

**Comment by rorth** [comment]
> I admit I still find it hard to understand what is this testing, so may I ask for some explaination? I'm not very familiar with the constructs used there, and, particularly, the asan functions...

Neither am I.  I guess it's best to ask the author of the testcase, originally submitted in [Implement variable-sized alloca instrumentation (take 2).](https://reviews.llvm.org/D7098).  However, I cannot find a github account for him (m.ostapenko).  Maybe @yugr or @vitalybuka can shed some light?

FWIW, I've tried to build the testcase with gcc (which supports 32-bit ASan on SPARC just fine), but the test fails there, too.

**Comment by rorth** [comment]
> Taking out the WIP status since I think this is ready for merging now. (Aside from the one asan failure case - but if GCC also fails there that means that at least we're on par with it, no?)

I've just retried the testcase on Linux/i386 with `gcc-14`, where it `FAIL`s as well.  It may well depend on `-mllvm -asan-instrument-dynamic-allocas` which `gcc` obviously doesn't support.

That said, I'm fine with merging the patch now, with one caveat: please first file an Issue for the remaining failure with everything that's known about the issue, then `XFAIL` the testcase on SPARC to avoid the Solaris/sparcv9 bot turning red immediately (oh wait, it already is due to PR #106951 ;-().

**Comment by chefmax7** [comment]
> > ```
> > Assertion failed: q == top, file /vol/llvm/src/llvm-project/local/compiler-rt/test/asan/TestCases/alloca_vla_interact.cpp, line 45
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Linux/sparc64 is worse, but AFAICS none of the failures there are related to this patch, just Linux/sparc64 specific issues.
> > Thanks again!
> 
> I admit I still find it hard to understand what is this testing, so may I ask for some explaination? I'm not very familiar with the constructs used there, and, particularly, the asan functions...

Hi, sorry for the late response, I took some time for me to restore my GH account...

I don't remember all the details, but from what I remember, when implementing VLA/alloca poisoning, LLVM showed different behavior for allocation slots management between VLAs/allocas into loop nest:
* for **VLA**, I saw its stack slot being reused between loop iterations (i.e. each VLA's alloca was preceded by `@llvm.stacksave.p0()` all and followed by corresponding `@llvm.stackrestore.p0(...)`.
* for **alloca** I saw LLVM allocating a new stack slot on each loop iteration (no reuse).

So the test case was indented to check that ASAN can handle poisoning/unpoisoning correctly in presence of both VLAs/allocas into same loop nest.

However, looking on freshly generated LLVM IR, it seems this difference is not the case anymore, maybe it was a bug in LLVM back then...
That said, I think this test case doesn't have value anymore (and maybe it's even invalid now).

I'm sorry that I can't provide more technical details now, this patch is pretty old...

**Comment by rorth** [comment]
> > That said, I'm fine with merging the patch now, with one caveat: please first file an Issue for the remaining failure with everything that's known about the issue
> 
> Posted the issue tracker at #110956.

Fine, thanks.

> > then `XFAIL` the testcase on SPARC to avoid the Solaris/sparcv9 bot turning red immediately (oh wait, it already is due to PR #106951 ;-().
> 
> The buildbot should be green again now :)

It is indeed.  I wonder what to do about the testcase now.  I guess there are 3 options:
- `XFAIL` it on SPARC, referencing the Issue.
- Mark the test `UNSUPPORTED` everywhere.
- Remove it wholesale.

**Comment by brad0** [comment]
@s-barannikov

File: llvm/lib/Target/Sparc/SparcFrameLowering.cpp [hunk 3]
```diff
@@ -97,12 +98,6 @@ void SparcFrameLowering::emitPrologue(MachineFunction &MF,
   // Debug location must be unknown since the first debug location is used
   // to determine the end of the prologue.
   DebugLoc dl;
-  bool NeedsStackRealignment = RegInfo.shouldRealignStack(MF);
```
Comment (s-barannikov) [inline llvm/lib/Target/Sparc/SparcFrameLowering.cpp:100]: `hasStackRealignment` now also always returns false (there are a couple of uses in this file).

File: llvm/lib/Target/Sparc/SparcISelLowering.cpp [hunk 4]
```diff
@@ -2811,16 +2805,30 @@ static SDValue LowerDYNAMIC_STACKALLOC(SDValue Op, SelectionDAG &DAG,
     regSpillArea = 96;
```
Comment (s-barannikov) [inline llvm/lib/Target/Sparc/SparcISelLowering.cpp:2805]: Is this and the big comment above still relevant?

**Comment by brad0** [comment]
@s-barannikov

**Review by s-barannikov — APPROVED** [review]
LGTM (I didn't look closely at the tests)
