### PR TITLE
[Clang][Concepts] Correct the CurContext for friend declarations

### LINKED ISSUE #78101: [Clang18][Concepts] Using static data member as concept argument in partially specialized template fails to compile
The following example compiles with Clang 17 but not in Clang 18 (since approximately 1 week):

```cpp
template<typename T, typename U, int i>
concept True = true;

template<typename T, int I>
struct Template
{
    static constexpr int i = I;

    friend constexpr auto operator+(True<T, i> auto f)
    {
        return i;
    }
};

template<int I>
struct Template<float, I>
{
    static constexpr int i = I;

    friend constexpr auto operator+(True<float, i> auto f)
    {
        return i;
    }
};

Template<void, 4> f{};

static_assert(+Template<float, 5>{} == 5);
```
With `-std=c++20` on clang 18 I get:

`<source>:9:45: error: no member 'i' in 'Template<float, 5>'; it has not yet been instantiated`

The error is caused in the static_assert. What's interesting is that it's refering to line 9, which is not the specialization `Template<float, 5>`.
The error goes away if I remove the variable `f`, when I don't have a partial specialization, or I use `I` directly.
This is a problem when I don't want to just use the value of `I` but the result of a complex expression dependent on `I` and that result is repeatedly used throughout the specialization, not just 1 function.

### PR DESCRIPTION
**Pull request by zyn0217**
`FindInstantiatedDecl()` relies on the `CurContext` to find the corresponding class template instantiation for a class template declaration.

Previously, we pushed the semantic declaration context for constraint comparison, which is incorrect for constraints on friend declarations. In issue #78101, the semantic context of the friend is the TU, so we missed the implicit template specialization `Template<void, 4>` when looking for the instantiation of the primary template `Template` at the time of checking the member instantiation; instead, we mistakenly picked up the explicit specialization `Template<float, 5>`, hence the error.

As a bonus, this also fixes a crash when diagnosing constraints. The DeclarationName is not necessarily an identifier, so it's incorrect to call `getName()` on e.g. overloaded operators. Since the DiagnosticBuilder has correctly handled Decl printing, we don't need to find the printable name ourselves.

Fixes https://github.com/llvm/llvm-project/issues/78101

### CODE REVIEW

File: clang/lib/Sema/SemaConcept.cpp [hunk 1]
```diff
@@ -1012,7 +1012,14 @@ static const Expr *SubstituteConstraintExpressionWithoutSatisfaction(
   // possible that e.g. constraints involving C<Class<T>> and C<Class> are
   // perceived identical.
   std::optional<Sema::ContextRAII> ContextScope;
-  if (auto *RD = dyn_cast<CXXRecordDecl>(DeclInfo.getDeclContext())) {
+  const DeclContext *DC = [&] {
+    if (!DeclInfo.getDecl())
+      return DeclInfo.getDeclContext();
+    return DeclInfo.getDecl()->getFriendObjectKind()
+               ? DeclInfo.getLexicalDeclContext()
+               : DeclInfo.getDeclContext();
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaConcept.cpp:1020]: I wonder if we should have a function that handles that logic of getting a lexical context for friends - we do it in a few places

**Review by cor3ntin — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaConcept.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:1020]: Agreed, probably something like `Decl::getFriendDeclContext()`
