### PR TITLE
[Inline][Cloning] Defer constant propagation after phi-nodes resolution

### LINKED ISSUE #87534: wrong code at -O1 on x86_64-linux-gnu
It appears to be a regression from 14.0.0, and affects 15.* and later. 

Compiler Explorer: https://godbolt.org/z/57cnEr81r

```
[546] % clangtk -v
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 07a566793b2f94d0de6b95b7e6d1146b0d7ffe49)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/software/local/clang-trunk/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
[547] % 
[547] % clangtk -O1 small.c
[548] % ./a.out
Aborted
[549] % cat small.c
struct a {
  int b;
  int c;
  int d;
  int e;
  int f;
} g, h = {1,0,0,0,0}, *i;
void j(struct a k) {
  struct a *l = &g;
  if (k.b)
    l = i = &k;
  if (l != &k)
    __builtin_abort();
}
int main() {
  j(h);
  return 0;
}
```

### PR DESCRIPTION
**Pull request by antoniofrighetto**
A logic issue arose when inlining via `CloneAndPruneFunctionInto`, which, besides cloning, performs instruction simplification as well. By the time a new cloned instruction is being simplified, phi-nodes are not remapped yet as the whole CFG needs to be processed first. As `VMap` state at this stage is incomplete, `threadCmpOverPHI` and variants could lead to unsound optimizations. This issue has been addressed by performing basic constant folding while cloning, and postponing instruction simplification once phi-nodes are revisited.

Fixes: https://github.com/llvm/llvm-project/issues/87534.

### CODE REVIEW

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 1]
```diff
@@ -823,52 +804,45 @@ void llvm::CloneAndPruneIntoFromInst(Function *NewFunc, const Function *OldFunc,
...
+  const DataLayout &DL = NewFunc->getParent()->getDataLayout();
+  auto *NewEntryBlock = cast<BasicBlock>(VMap[StartingBB]);
+  ReversePostOrderTraversal<BasicBlock *> RPOT(NewEntryBlock);
+  for (auto &BB : RPOT) {
+    for (BasicBlock::iterator II = BB->begin(), IE = BB->end(); II != IE;) {
+      auto *NewI = &*II++;
+      if (isa<DbgInfoIntrinsic>(NewI))
+        continue;
+
+      CallBase *CB = dyn_cast<CallBase>(NewI);
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/Utils/CloneFunction.cpp:826]:
```suggestion
     // Skip over non-intrinsic callsites, we don't want to remove any nodes from
     // the CGSCC.
      CallBase *CB = dyn_cast<CallBase>(NewI);
```

Should we keep the comment?

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 2]
```diff
@@ -823,52 +804,45 @@ void llvm::CloneAndPruneIntoFromInst(Function *NewFunc, const Function *OldFunc,
...
-    else
-      VMap[OrigV] = I;
+  // As phi-nodes have been now remapped, allow incremental simplification of
+  // newly-cloned instructions.
+  const DataLayout &DL = NewFunc->getParent()->getDataLayout();
+  auto *NewEntryBlock = cast<BasicBlock>(VMap[StartingBB]);
+  ReversePostOrderTraversal<BasicBlock *> RPOT(NewEntryBlock);
+  for (auto &BB : RPOT) {
+    for (BasicBlock::iterator II = BB->begin(), IE = BB->end(); II != IE;) {
+      auto *NewI = &*II++;
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/Utils/CloneFunction.cpp:822]: IIRC we can use the helper `make_early_inc_range` instead.

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 3]
```diff
@@ -823,52 +804,46 @@ void llvm::CloneAndPruneIntoFromInst(Function *NewFunc, const Function *OldFunc,
...
-
-    // Replace the instruction with its simplified value.
-    I->replaceAllUsesWith(SimpleV);
+  auto GetOriginalValueInVMap = [&](const auto &I) -> Value * {
+    for (const auto &[OrigI, NewI] : VMap) {
+      if (NewI == I)
+        return const_cast<Value *>(OrigI);
+    }
+    return nullptr;
+  };
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/CloneFunction.cpp:813]: This looks very inefficient if many values are cloned and simplified.

**Review by nikic — COMMENTED** [review]
What's the compile-time impact of this change?

File: llvm/lib/Transforms/Utils/CloneFunction.cpp (hunk 3 above)
Comment (antoniofrighetto) [reply llvm/lib/Transforms/Utils/CloneFunction.cpp:813]: Had the same concern, though in practice I would expect it not to happen that often as most of the times the instruction would be trivially dead? Alternatively, we could iterate over all the instructions of the old function, looking up `VMap` each time to get the new instruction and see if that can be simplified? Not sure if it’d be worth it though. Compile time does not look excessively bad: http://llvm-compile-time-tracker.com/compare.php?from=d34a2c2adb2a4f1dc262c5756d3725caa4ea2571&to=79475c2bf9493e51dcdf46e49b8bd15da326e912&stat=instructions:u. Also, IIRC RPOT was outperforming classic iteration in a few settings (`stage2-O3`).

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 4]
```diff
@@ -823,52 +804,46 @@ void llvm::CloneAndPruneIntoFromInst(Function *NewFunc, const Function *OldFunc,
...
+          NewI.replaceAllUsesWith(V);
+
+        if (isInstructionTriviallyDead(&NewI)) {
+          NewI.eraseFromParent();
+        } else {
+          // Did not erase it? Restore the new instruction into VMap.
+          auto *OriginalI = GetOriginalValueInVMap(&NewI);
+          assert(OriginalI != nullptr &&
+                 "Previously remapped value was not found?");
+          VMap[OriginalI] = &NewI;
```
[the remark this answers is not in the document]
Comment (antoniofrighetto) [reply llvm/lib/Transforms/Utils/CloneFunction.cpp:842]: `replaceAllUsesWith` will drop the old value in `VMap`, and update it with the newly-simplified one via `ValueHandleBase::ValueIsRAUWd`. If we do not erase the instruction, we have to manually restore `NewI`. I must have missed something while refactoring the code, since clearly we have to retrieve `OriginalI` through the just-replaced value `V`, not via `NewI`, as `VMap` has been changed. No need to do anything when the instruction gets erased. Fixed it now, thanks.

File: llvm/lib/Transforms/Utils/CloneFunction.cpp (hunk 3 above)
Comment (antoniofrighetto) [reply llvm/lib/Transforms/Utils/CloneFunction.cpp]: FWIW avoiding instruction simplification outright leads to overall worse regressions despite some little amelioration here and there: http://llvm-compile-time-tracker.com/compare.php?from=d34a2c2adb2a4f1dc262c5756d3725caa4ea2571&to=f9307dc124eba7bb019310c9de043166e494f7a3&stat=instructions:u.

Comment (nikic) [reply llvm/lib/Transforms/Utils/CloneFunction.cpp]: It would be good to understand what causes the sqlite3 regression. My theory is that this is because the block cloning is lazy: If we see that the branch condition has folded to a constant, we may only clone one successor.

I think that after this change that logic is essentially dead and we'll always clone the whole function. The whole function might be much larger than just the part reachable via folded conditions. Especially if you take into account that InlineCost does the same thing, so inlining a very large function may be cheap if most of it is dead based on caller information.

If this theory is true, then what we might want to do is to still eagerly perform constant folding, and then do the InstSimplify pass afterwards. (We could also test doing only constant folding...)

**Comment by antoniofrighetto** [comment]
@nikic, I confirm performing basic constant folding on average decreases the number of blocks being cloned; I think we should be more on track now (http://llvm-compile-time-tracker.com/compare.php?from=eec268e41000faad50b7bf977c9f1161e4006bab&to=65847e8c168123ad328683f96b1b37cd269ea85c&stat=instructions:u). I think we still want to do InstSimplify after cloning, since not doing it leads to regressions in stage2 scenario (http://llvm-compile-time-tracker.com/compare.php?from=60baaf153d05a7828b304050aba461ebb66232c6&to=78c72fd92fa1b22fd2d113bb4e821b484322aadd&stat=instructions:u), besides the following local failures:
```
********************
Failed Tests (8):
  LLVM :: DebugInfo/Generic/assignment-tracking/inline/shared-alloca.ll
  LLVM :: Transforms/Inline/byval.ll
  LLVM :: Transforms/Inline/inline_cleanup.ll
  LLVM :: Transforms/Inline/nonnull.ll
  LLVM :: Transforms/Inline/pr50270.ll
  LLVM :: Transforms/Inline/pr50589.ll
  LLVM :: Transforms/Inline/ptr-diff.ll
  LLVM :: Transforms/Inline/simplify-instruction-computeKnownFPClass-context.ll
```

**Comment by antoniofrighetto** [comment]
• s/isInstTriviallyDead/wouldInstBeTriviallyDead/: http://llvm-compile-time-tracker.com/compare.php?from=2a47ee070145438424b065a35c4a680ea0cb0c1f&to=893dc199c447806aeb29436cc9e4dd3878c91bc4&stat=instructions:u
• Simple constant folding: http://llvm-compile-time-tracker.com/compare.php?from=60baaf153d05a7828b304050aba461ebb66232c6&to=78c72fd92fa1b22fd2d113bb4e821b484322aadd&stat=instructions:u (+ above failures).

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 5]
```diff
@@ -540,18 +541,11 @@ void PruningFunctionCloner::CloneBlock(
...
-        // On the off-chance that this simplifies to an instruction in the old
-        // function, map it back into the new function.
-        if (NewFunc != OldFunc)
-          if (Value *MappedV = VMap.lookup(V))
-            V = MappedV;
-
-        if (!NewInst->mayHaveSideEffects()) {
+      // Eagerly constant fold the newly cloned instruction. If successful, add
+      // a mapping to the new value.
+      if (Value *V = ConstantFoldInstruction(
```
Comment (efriedma-quic) [inline llvm/lib/Transforms/Utils/CloneFunction.cpp:546]: Maybe worth explicitly noting that non-constant operands might not incomplete at this point, so we don't want to try to do simplifications based on them.

File: llvm/lib/Transforms/Utils/CloneFunction.cpp [hunk 6]
```diff
@@ -540,18 +541,11 @@ void PruningFunctionCloner::CloneBlock(
...
+              NewInst, BB->getModule()->getDataLayout())) {
+        if (wouldInstructionBeTriviallyDead(NewInst)) {
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/CloneFunction.cpp:548]: I'd personally use isInstructionTriviallyDead here just to be more obvious (even though we know that there are no uses at this point.)

**Review by nikic — APPROVED** [review]
LGTM. A bit unfortunate that we have to do it this way, but I don't really see a good alternative.

**Comment by dtcxzyw** [comment]
This patch breaks our downstream CI: https://github.com/dtcxzyw/llvm-opt-benchmark/issues/550

Reduced testcase:
```
; bin/opt -passes=inline -S test.ll

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN4core4iter6traits8iterator8Iterator3zip17h5482e9cf1625f275E.llvm.18097807149992804452() {
"_ZN123_$LT$$RF$alloc..collections..btree..map..BTreeMap$LT$K$C$V$C$A$GT$$u20$as$u20$core..iter..traits..collect..IntoIterator$GT$9into_iter17haee589ca14fbbed3E.exit":
  %0 = load ptr, ptr null, align 8
  %.not.i.i = icmp eq ptr %0, null
  %1 = load i64, ptr null, align 8
  %.sroa.1.0 = select i1 %.not.i.i, i64 undef, i64 %1
  ret void
}

define noundef i1 @"_ZN98_$LT$alloc..collections..btree..map..BTreeMap$LT$K$C$V$C$A$GT$$u20$as$u20$core..cmp..PartialEq$GT$2eq17h320375e90a5cf86fE"() {
  call void @_ZN4core4iter6traits8iterator8Iterator3zip17h5482e9cf1625f275E.llvm.18097807149992804452()
  ret i1 false
}
```

```
opt: /home/dtcxzyw/WorkSpace/Projects/compilers/llvm-project/llvm/include/llvm/IR/User.h:170: llvm::Value* llvm::User::getOperand(unsigned int) const: Assertion `i < NumUserOperands && "getOperand() out of range!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bin/opt -passes=inline reduced.ll -S
 #0 0x0000750d65c06c10 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.19.0git+0x206c10)
 #1 0x0000750d65c03c1f llvm::sys::RunSignalHandlers() (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.19.0git+0x203c1f)
 #2 0x0000750d65c03d75 SignalHandler(int) Signals.cpp:0:0
 #3 0x0000750d65642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000750d656969fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x0000750d656969fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x0000750d656969fc pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x0000750d65642476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x0000750d656287f3 abort ./stdlib/abort.c:81:7
 #9 0x0000750d6562871b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x0000750d65639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x0000750d608cbb18 (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMAnalysis.so.19.0git+0x4cbb18)
#12 0x0000750d608d5e42 bool handleGuaranteedNonPoisonOps<llvm::mustTriggerUB(llvm::Instruction const*, llvm::SmallPtrSetImpl<llvm::Value const*> const&)::'lambda'(llvm::Value const*)>(llvm::Instruction const*, llvm::mustTriggerUB(llvm::Instruction const*, llvm::SmallPtrSetImpl<llvm::Value const*> const&)::'lambda'(llvm::Value const*) const&) ValueTracking.cpp:0:0
#13 0x0000750d608d71f8 programUndefinedIfUndefOrPoison(llvm::Value const*, bool) ValueTracking.cpp:0:0
#14 0x0000750d608d7c0e isGuaranteedNotToBeUndefOrPoison(llvm::Value const*, llvm::AssumptionCache*, llvm::Instruction const*, llvm::DominatorTree const*, unsigned int, UndefPoisonKind) ValueTracking.cpp:0:0
#15 0x0000750d608ea785 llvm::impliesPoison(llvm::Value const*, llvm::Value const*) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMAnalysis.so.19.0git+0x4ea785)
#16 0x0000750d606c761b simplifySelectInst(llvm::Value*, llvm::Value*, llvm::Value*, llvm::SimplifyQuery const&, unsigned int) InstructionSimplify.cpp:0:0
#17 0x0000750d606b659d simplifyInstructionWithOperands(llvm::Instruction*, llvm::ArrayRef<llvm::Value*>, llvm::SimplifyQuery const&, unsigned int) InstructionSimplify.cpp:0:0
#18 0x0000750d606c8bce llvm::simplifyInstruction(llvm::Instruction*, llvm::SimplifyQuery const&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMAnalysis.so.19.0git+0x2c8bce)
#19 0x0000750d60cdc165 llvm::CloneAndPruneIntoFromInst(llvm::Function*, llvm::Function const*, llvm::Instruction const*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false>>>&, bool, llvm::SmallVectorImpl<llvm::ReturnInst*>&, char const*, llvm::ClonedCodeInfo*) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMTransformUtils.so.19.0git+0xdc165)
#20 0x0000750d60cdcc89 llvm::CloneAndPruneFunctionInto(llvm::Function*, llvm::Function const*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false>>>&, bool, llvm::SmallVectorImpl<llvm::ReturnInst*>&, char const*, llvm::ClonedCodeInfo*) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMTransformUtils.so.19.0git+0xdcc89)
#21 0x0000750d60d5351f llvm::InlineFunction(llvm::CallBase&, llvm::InlineFunctionInfo&, bool, llvm::AAResults*, bool, llvm::Function*) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMTransformUtils.so.19.0git+0x15351f)
#22 0x0000750d61e2f1f9 llvm::InlinerPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMipo.so.19.0git+0x22f1f9)
#23 0x0000750d62ec6106 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::InlinerPass, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMPasses.so.19.0git+0xc6106)
#24 0x0000750d60583ff0 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMAnalysis.so.19.0git+0x183ff0)
#25 0x0000750d62ec2b96 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMPasses.so.19.0git+0xc2b96)
#26 0x0000750d605861a4 llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMAnalysis.so.19.0git+0x1861a4)
#27 0x0000750d62ec2b46 llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMPasses.so.19.0git+0xc2b46)
#28 0x0000750d5ff475c1 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/../lib/libLLVMCore.so.19.0git+0x3475c1)
#29 0x0000750d660c51d4 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMOptDriver.so.19.0git+0x2d1d4)
#30 0x0000750d660d2378 optMain (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMOptDriver.so.19.0git+0x3a378)
#31 0x0000750d65629d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#32 0x0000750d65629e40 call_init ./csu/../csu/libc-start.c:128:20
#33 0x0000750d65629e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#34 0x00005bc002bc8095 _start (bin/opt+0x1095)
```

opt crashes when processing `ret void` in `handleGuaranteedWellDefinedOps`:
https://github.com/llvm/llvm-project/blob/d609029d6c9aae84b52238f39c35200316bdbb93/llvm/lib/Analysis/ValueTracking.cpp#L7572-L7575

I don't know why the ret attribute `noundef` exists in a function that returns void.

**Comment by UsmanNadeem** [comment]
Multiple bots are broken, maybe revert this patch in the meanwhile?

https://lab.llvm.org/buildbot/#/builders/121/builds/41052/steps/10/logs/stdio
https://lab.llvm.org/buildbot/#/builders/179/builds/9966/steps/11/logs/stdio
https://lab.llvm.org/buildbot/#/builders/252/builds/9368/steps/6/logs/stdio

**Comment by efriedma-quic** [comment]
@antoniofrighetto the first rule of buildbots is that they stay green.  No matter what the root cause is, if you break the bots, you revert first, and sort it out later.

**Comment by nikic** [comment]
See https://github.com/llvm/llvm-project/pull/87482 for discussion about this issue.

Possibly this change also provide a way to fix that one properly, by delaying simplification until after the returns have been rewritten...

**Comment by danilaml** [comment]
I've noticed that before this PR, certain calls were simplified-away and now they are not because of
```cpp
      // Skip over non-intrinsic callsites, we don't want to remove any nodes
      // from the CGSCC.
      CallBase *CB = dyn_cast<CallBase>(NewI);
      if (CB && CB->getCalledFunction() &&
          !CB->getCalledFunction()->isIntrinsic())
        continue;
```

I'm not clear if this check is still required. And if it is, was the fact that it was missing in CloneBLock before a bug? Shouldn't it still be added there, since ConstantFold can still eliminate some non-intrinsic calls (i.e. some math functions)? It was added by @majnemer in 5554edabef3814395360c37e9854fa4aa7b1731e

**Comment by nikic** [comment]
@danilaml It should be safe to drop. There used to be VMap-based CG updates for the legacy PM, but the relevant function went away entirely in https://github.com/llvm/llvm-project/commit/fa6ea7a419f37befbed04368bcb8af4c718facbb.

**Comment by danilaml** [comment]
@nikic made a PR with the check removal here: https://github.com/llvm/llvm-project/pull/92577
