### PR TITLE
[DAGCombiner] Reconstruct borrow chain from icmp pattern for USUBO_CARRY

### LINKED ISSUE #106118: Poor codegen with __builtin_subcll
In using __builtin_subcll to do a multi-precision comparison, clang fails to optimize to use a `cmp` and `sbb` operation. This seems to be a regression for trunk vs clang15.

https://godbolt.org/z/dsheW9YbK

```
bool edata_cmp_summary_less(edata_cmp_summary_t a, edata_cmp_summary_t b) {
    unsigned long long borrow = 0;
    __builtin_subcll(a.addr, b.addr, borrow, &borrow);
    __builtin_subcll(a.sn, b.sn, borrow, &borrow);
    return borrow != 0;
}
```

Clang trunk:
```
edata_cmp_summary_less(edata_cmp_summary_s, edata_cmp_summary_s):
        cmp     rsi, rcx
        setb    cl
        cmp     rdi, rdx
        setb    dl
        sete    al
        and     al, cl
        or      al, dl
        ret
```

Optimal assembly (gcc / clang 15.0):

```
edata_cmp_summary_less(edata_cmp_summary_s, edata_cmp_summary_s):
        cmp     rsi, rcx
        sbb     rdi, rdx
        setb    al
        ret
```

### PR DESCRIPTION
**Pull request by chfast**
DAG-level alternative to #189018 (CGP): match the canonical icmp form
  carry_out = or(icmp ult A, B, and(icmp eq A, B, carry_in))
in visitOR and rewrite to USUBO_CARRY so the backend can chain the
borrow through sbb/sbcs.

Gated on USUBO_CARRY being legal/custom at the type the integer
legalizes to, so targets without hardware carry-flag support are
unaffected. For oversize integers (e.g. i128 on x86_64/aarch64) type
legalization then expands one USUBO_CARRY into a chain of
register-width USUBO_CARRYs, which gives strictly better code than the
CGP-level reconstruction.

Fixes #106118.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -3907,6 +3907,34 @@ static SDValue combineCarryDiamond(SelectionDAG &DAG, const TargetLowering &TLI,
...
+                                        m_SpecificCondCode(ISD::SETEQ)),
+                              m_Value(CarryIn)))))
+    return SDValue();
+
+  // Require USUBO_CARRY on the post-legalization type; for oversize integers
+  // (e.g. i128) type legalization then expands one USUBO_CARRY into a chain
+  // of register-width USUBO_CARRYs, which is exactly what we want.
+  EVT IntVT = A.getValueType();
+  if (!TLI.isOperationLegalOrCustom(
+          ISD::USUBO_CARRY, TLI.getTypeToTransformTo(*DAG.getContext(), IntVT)))
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: Should this be getLegalTypeToTransformTo which will iterate getTypeToTransformTo to a legal type? getTypeToTransformTo will only return the type of the next step.

Comment (chfast) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: yes, fixed.

File: llvm/test/CodeGen/AArch64/cgp-usubo.ll [hunk 2]
```diff
@@ -120,19 +120,126 @@ define i1 @usubo_eq_constant1_op1_i32(i32 %x, ptr %p) nounwind {
...
+; CHECK-NEXT:    csinc w0, w8, wzr, ge
+; CHECK-NEXT:    ret
+  %b0 = icmp ult i64 %x0, %y0
+  %b1 = icmp slt i64 %x1, %y1
+  %e1 = icmp eq i64 %x1, %y1
+  %bp = and i1 %b0, %e1
+  %br = or i1 %b1, %bp
+  ret i1 %br
+}
+
```
Comment (arsenm) [inline llvm/test/CodeGen/AArch64/cgp-usubo.ll:229]: Test vector cases

Comment (chfast) [reply llvm/test/CodeGen/AArch64/cgp-usubo.ll:229]: Added tests and fixed a bug. Thanks.

**Review by topperc — APPROVED** [review]
LGTM

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 3]
```diff
@@ -3907,6 +3907,34 @@ static SDValue combineCarryDiamond(SelectionDAG &DAG, const TargetLowering &TLI,
   return Merged.getValue(1);
 }
 
+// Reconstruct a subtract-with-borrow chain from its canonicalized icmp form:
+//   carry_out = or(icmp ult A, B, and(icmp eq A, B, carry_in))
+// InstCombine collapses chained usub.with.overflow intrinsics into this
+// shape, losing the direct USUBO_CARRY that the backend can chain through
+// sbb/sbcs. Fixes llvm#106118.
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: drop "Fixes llvm#106118." - we don't tend to include PR tags in code

**Review by RKSimon — APPROVED** [review]
LGTM with one minor
