### PR TITLE
[LV] Ensure getScaledReductions only matches extends inside the loop

### LINKED ISSUE #148260: [LV] Assertion `Val && "isa<> used on a null pointer"' failed
Compile this:

```
int a;
extern bool b[];
char d, c;
void f() {
  for (int e(d); e; e += 4LL) {
    b[e] = 0;
    a += c;
  }
}
```

with:

    clang++  -Ofast  -mcpu=grace  -c func.cpp

to trigger this assert:

```
llvm/include/llvm/Support/Casting.h:109: static bool llvm::isa_impl_cl<llvm::VPWidenCastRecipe, const llvm::VPRecipeBase *>::doit(const From *) [To = llvm::VPWidenCastRecipe, From = const llvm::VPRecipeBase *]: Assertion `Val && "isa<> used on a null pointer"' failed.
```

See also: https://godbolt.org/z/G9nM71bbr

### PR DESCRIPTION
**Pull request by david-arm**
In getScaledReductions for the case where we try to match a partial reduction of the form:

%phi = phi i32 ...
...
%add = add i32 %phi, %zext

where

%zext = i8 %some_val to i32

we should ensure that %zext is actually inside the loop.

Fixes https://github.com/llvm/llvm-project/issues/148260

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 1]
```diff
@@ -8109,14 +8109,19 @@ bool VPRecipeBuilder::getScaledReductions(
...
                          &ExtOpTypes](SmallVectorImpl<Value *> &Ops) -> bool {
     unsigned I = 0;
     for (Value *OpI : Ops) {
       Value *ExtOp;
       if (!match(OpI, m_ZExtOrSExt(m_Value(ExtOp))))
         return false;
       Exts[I] = cast<Instruction>(OpI);
+
+      // Other operand should live inside the loop
+      if (!CM.TheLoop->contains(Exts[I]))
```
Comment (fhahn) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8125]: Is there a reason it is difficult/not possible to support live-in operands?

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll [hunk 2]
```diff
@@ -911,6 +911,253 @@ for.exit:                        ; preds = %for.body
...
+entry:
+  %conv = zext i8 %d to i32
+  %a.promoted = load i32, ptr %a, align 1
+  br label %for.body
+
+for.body:
+  %iv = phi i32 [ %conv, %entry ], [ %iv.next, %for.body ]
+  %rdx = phi i32 [ %a.promoted, %entry ], [ %rdx.next, %for.body ]
+  %idxprom = sext i32 %iv to i64
+  %arrayidx = getelementptr inbounds [0 x i8], ptr %b, i64 0, i64 %idxprom
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]:
```suggestion
  %arrayidx = getelementptr inbounds i8, ptr %b, ii64 %idxprom
```
That should work I think, w/o using an array type with zero elements.

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll [hunk 3]
```diff
@@ -911,6 +911,253 @@ for.exit:                        ; preds = %for.body
...
+  store i8 0, ptr %arrayidx, align 1
+  %conv1 = zext i8 %c to i32
+  %rdx.next = add nsw i32 %rdx, %conv1
+  %iv.next = add i32 %iv, 4
+  %cmp = icmp eq i32 %iv.next, 0
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]: This could probably be something like 
```suggestion
  %cmp = icmp eq i32 %iv.next, 1024
```

to avoid wrapping IV and various SCEV runtime checks.

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll [hunk 4]
```diff
@@ -911,6 +911,253 @@ for.exit:                        ; preds = %for.body
...
+  br i1 %cmp, label %exit, label %for.body
+
+exit:
+  %add.lcssa = phi i32 [ %rdx.next, %for.body ]
+  store i32 %add.lcssa, ptr %a, align 4
+  ret void
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]:
```suggestion
  %add.lcssa = phi i32 [ %rdx.next, %for.body ]
  ret i32 %add.lcssa
```

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll [hunk 5]
```diff
@@ -911,6 +911,253 @@ for.exit:                        ; preds = %for.body
...
+; CHECK-MAXBW-NEXT:    [[CMP:%.*]] = icmp eq i32 [[IV_NEXT]], 0
+; CHECK-MAXBW-NEXT:    br i1 [[CMP]], label [[EXIT:%.*]], label [[FOR_BODY]]
+; CHECK-MAXBW:       exit:
+; CHECK-MAXBW-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[RDX_NEXT]], [[FOR_BODY]] ]
+; CHECK-MAXBW-NEXT:    store i32 [[ADD_LCSSA]], ptr [[A]], align 4
+; CHECK-MAXBW-NEXT:    ret void
+;
+entry:
+  %conv = zext i8 %d to i32
+  %a.promoted = load i32, ptr %a, align 1
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]: can just pass `i32 %a` as argument?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 1 above)
Comment (david-arm) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8125]: Maybe it is possible, but given we're close to the branch point I thought it might be better to disable it first and look at adding support for it afterwards. What do you think?

I think the problem lies in the cost model (specifically VPPartialReduction::computeCost) and some assumptions made about the ordering of PHI operands.

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll [hunk 6]
```diff
@@ -911,6 +911,239 @@ for.exit:                        ; preds = %for.body
...
+; CHECK-MAXBW-NEXT:    [[RDX_NEXT]] = add nsw i32 [[RDX]], [[CONV1]]
+; CHECK-MAXBW-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 4
+; CHECK-MAXBW-NEXT:    [[CMP:%.*]] = icmp eq i32 [[IV_NEXT]], 1024
+; CHECK-MAXBW-NEXT:    br i1 [[CMP]], label [[EXIT:%.*]], label [[FOR_BODY]]
+; CHECK-MAXBW:       exit:
+; CHECK-MAXBW-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[RDX_NEXT]], [[FOR_BODY]] ]
+; CHECK-MAXBW-NEXT:    ret i32 [[ADD_LCSSA]]
+;
+entry:
+  %conv = zext i8 %d to i32
```
Comment (MDevereau) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]: Since we're testing that partial reductions aren't emitted here, `%conv = zext i8 %d to i32` is also present in the test `add_of_loop_invariant_zext` as the iv phi's operand.

Shouldn't %d just be an i32 here so we have a fully independent test for the IV phi having a zext operand, and also the reduction add having a zext operand? Otherwise I think these tests are doing the same thing.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 7]
```diff
@@ -8112,14 +8112,19 @@ bool VPRecipeBuilder::getScaledReductions(
...
+  auto CollectExtInfo = [this, &Exts,
                          &ExtOpTypes](SmallVectorImpl<Value *> &Ops) -> bool {
     unsigned I = 0;
     for (Value *OpI : Ops) {
       Value *ExtOp;
       if (!match(OpI, m_ZExtOrSExt(m_Value(ExtOp))))
         return false;
       Exts[I] = cast<Instruction>(OpI);
+
+      // Other operand should live inside the loop
```
Comment (MDevereau) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Unnecessary comment which says the same as the code below it. I'd remove it or be more specific about why it's here.

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll (hunk 6 above)
Comment (david-arm) [reply llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce.ll]: I've changed the tests now so they are a bit more obvious. I've removed the zext of %d in each test, and changed the loop to remove the SCEV checks and also avoid having to use scatter instructions when vectorising the store. Hopefully it should be clearer now - `@add_of_zext_outside_loop` doesn't use partial reductions, but `@add_of_loop_invariant_zext` does because the zext is inside the loop.

**Review by MDevereau — APPROVED** [review]
Thanks @david-arm!

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 1 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8125]: Ok, TODO seems fine for now, although it would ideally be fixed at the source.

**Review by fhahn — APPROVED** [review]
LGTM, thanks

**Comment by david-arm** [comment]
> Ok, TODO seems fine for now, although it would ideally be fixed at the source.

Yep, as soon as we've branched for the release I'll try to fix this properly.
