### PR TITLE
[LLDB][NativePDB] Find functions by basename

### LINKED ISSUE #51933: LLDB failed to lookup method names in NativePDB plugin
|  |  |
| --- | --- |
| Bugzilla Link | [52591](https://llvm.org/bz52591) |
| Version | unspecified |
| OS | All |
| CC | @JDevlieghere,@labath |

## Extended Description 
The following lldb commands fail to lookup/set breakpoint on given method names:
`image lookup -n A::foo()`
`b A::foo()`

The problem is that lldb passes the function base name(e.g. "foo()") to Plugins' FindFunctions, and NativePDB plugin can only lookup functions by their full names.

Is there a way to only pass functions' full names to FindFunctions?

### PR DESCRIPTION
**Pull request by Nerixyz**
This adds the ability for functions to be matched by their basename.

Before, the globals were searched for the name. This works if the full name is available but fails for basenames.
PDB only includes the full names of functions, so we need to cache all basenames. This is (again) very similar to [SymbolFilePDB](https://github.com/llvm/llvm-project/blob/b242150b075a8a720b00821682a9469258bbcd30/lldb/source/Plugins/SymbolFile/PDB/SymbolFilePDB.cpp#L1291-L1383). There are two main differences:

- We can't just access the parent of a function to determine that it's a member function - we need to check the type of the function, and its "this type".
- SymbolFilePDB saved the full method name in the map. However, when searching for methods, only the basename is passed, so the function never found any methods.

Fixes #51933.

### CODE REVIEW

File: lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp [hunk 1]
```diff
@@ -1677,34 +1766,56 @@ void SymbolFileNativePDB::FindFunctions(
...
-  std::vector<SymbolAndOffset> matches = m_index->globals().findRecordsByName(
-      name.GetStringRef(), m_index->symrecords());
-  for (const SymbolAndOffset &match : matches) {
-    if (match.second.kind() != S_PROCREF && match.second.kind() != S_LPROCREF)
-      continue;
-    ProcRefSym proc(match.second.kind());
-    cantFail(SymbolDeserializer::deserializeAs<ProcRefSym>(match.second, proc));
+    for (uint32_t id : ids) {
+      if (resolved_ids.find(id) != resolved_ids.end())
+        continue;
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp:1783]: could do
```suggestion
      if (!resolved_ids.insert(id))
        continue;
```
Then don't need the insert at the end of the loop. Of course that means we won't retry resolving an ID if it failed the first time. But don't think anything would change in between invocations of this lambda for the ID to suddently become resolved if it failed the first time?

File: lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp [hunk 2]
```diff
@@ -1677,34 +1766,56 @@ void SymbolFileNativePDB::FindFunctions(
...
-    sc_list.Append(sc);
-  }
+      if (!IsValidRecord(proc))
+        continue;
+
+      CompilandIndexItem &cci =
+          m_index->compilands().GetOrCreateCompiland(proc.modi());
+      SymbolContext sc;
+
+      sc.comp_unit = GetOrCreateCompileUnit(cci).get();
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp:1804]: missing `sc.comp_unit` nullptr check

File: lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.h [hunk 3]
```diff
@@ -282,6 +284,13 @@ class SymbolFileNativePDB : public SymbolFileCommon {
       m_parent_types;
 
   lldb_private::UniqueCStringMap<uint32_t> m_type_base_names;
+
+  /// Global ID -> mangled name/full function name
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.h:288]: Did you mean for these mapping comments to be reversed. E.g.,:
```
/// mangled name/full function name -> Global ID
```
?

Comment (Nerixyz) [reply lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.h]: Right, sorry for the confusion.

**Review by ZequanWu — APPROVED** [review]

**Comment by JDevlieghere** [comment]
Failures looks related to I'm going to revert to unblock the bot

```
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/test/Shell/SymbolFile/NativePDB/find-functions.cpp:144:24: error: FIND-OVERLOAD-FULL: expected string not found in input
// FIND-OVERLOAD-FULL: FuncType: id = {{.*}}, compiler_type = "int (char)"
                       ^
<stdin>:12:74: note: scanning from here
 FuncType: id = {0x000100e4}, byte-size = 0, compiler_type = "int (void)"
                                                                         ^

Input file: <stdin>
Check file: /home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/test/Shell/SymbolFile/NativePDB/find-functions.cpp

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           .
           .
           .
           7:  CompileUnit: id = {0x00000000}, file = "/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/test/Shell/SymbolFile/NativePDB/find-functions.cpp", language = "c++" 
           8:  Function: id = {0x70400001}, name = "Struct::overloaded_method", decl_context = {}, range = find-functions.cpp.tmp.exe[0x0000000140001204-0x000000014000121a) 
           9:  FuncType: id = {0x00010114}, byte-size = 0, compiler_type = "int (char)" 
          10:  CompileUnit: id = {0x00000000}, file = "/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/test/Shell/SymbolFile/NativePDB/find-functions.cpp", language = "c++" 
          11:  Function: id = {0x4d800001}, name = "Struct::overloaded_method", decl_context = {}, range = find-functions.cpp.tmp.exe[0x0000000140001184-0x00000001400011bd) 
          12:  FuncType: id = {0x000100e4}, byte-size = 0, compiler_type = "int (void)" 
check:144                                                                              X error: no match found
          13:  
check:144     ~

>>>>>>
```

[stdio-4.txt](https://github.com/user-attachments/files/21726140/stdio-4.txt)
