### PR TITLE
[ItaniumMangle] Add substitutions for record types when mangling vtables

### LINKED ISSUE #108015: [ABI] mangleCXXCtorVTable mangles an incorrect name
```C++

namespace A {

class VBase {
 public:
  virtual ~VBase() {};
};

struct Wrap {};

template <typename T>
class Impl : public virtual VBase {
 public:
};

}  // namespace A

struct Inst : public A::Impl<A::Wrap> {};

void Test() { Inst a; }
```
The code above will generate a `CtorVTable` with the name `_ZTC4Inst0_N1A4ImplINS_4WrapEEE`. After demangling, the result is `construction vtable for A::Impl<Inst::Wrap>-in-Inst`. However, `Inst::Wrap` is incorrect.

https://github.com/llvm/llvm-project/blob/b0ffaa79050460d724eec1b12363c439b43d5ae5/clang/lib/AST/ItaniumMangle.cpp#L7327-L7338

Because `mangleNameOrStandardSubstitution` never adds `RD` as a substitution.

### PR DESCRIPTION
**Pull request by tcwzxx**
Fix #108015 

The mangleNameOrStandardSubstitution function does not add the RD type into the substitution, which causes the mangling of the \<base type\> to be incorrect.

### CODE REVIEW

File: clang/lib/AST/ItaniumMangle.cpp [hunk 1]
```diff
@@ -7326,11 +7326,13 @@ void ItaniumMangleContextImpl::mangleCXXCtorVTable(const CXXRecordDecl *RD,
                                                    raw_ostream &Out) {
   // <special-name> ::= TC <type> <offset number> _ <base type>
   CXXNameMangler Mangler(*this, Out);
+  QualType RDType = getASTContext().getRecordType(RD);
+  QualType TypeType = getASTContext().getRecordType(Type);
   Mangler.getStream() << "_ZTC";
-  Mangler.mangleNameOrStandardSubstitution(RD);
+  Mangler.mangleType(RDType);
```
Comment (mizvekov) [inline clang/lib/AST/ItaniumMangle.cpp:7332]: The only difference here is whether we perform / add a substitution for RD.

We only ever see a problem for `mangleCXXCtorVTable` because it's the only user of `mangleNameOrStandardSubstitution` which mangles anything at all after a call to that function.

I can't find this production in the ItaniumABI docs, but if the comment is right, I think performing this substitution is correct.

I'd prefer we fix `mangleNameOrStandardSubstitution` itself.
We could rename it to `mangleCXXRecordDecl`, have it take a CXXRecordDecl*, and handle the substitutions there.
This would avoid the same trap in a potential future user.

CC @rjmccall @zygoloid

Comment (tcwzxx) [reply clang/lib/AST/ItaniumMangle.cpp:7332]: > I can't find this production in the ItaniumABI docs, but if the comment is right, I think performing this substitution is correct.

I also can't find any Itanium ABI documentation, but I found that GCC follows the same process. So, I believe the comment is correct, and it is necessary to perform the substitution for RD.

Comment (tcwzxx) [reply clang/lib/AST/ItaniumMangle.cpp:7332]: > I'd prefer we fix `mangleNameOrStandardSubstitution` itself.
> We could rename it to `mangleCXXRecordDecl`, have it take a CXXRecordDecl*, and handle the substitutions there.
> This would avoid the same trap in a potential future user.

After rechecking the code, I found that the users of the `mangleNameOrStandardSubstitution` function are `mangleCXXCtorVTable`, `mangleCXXVTable`, and `mangleCXXVTT`. In the Itanium ABI documentation, these situations are considered as 'Type'. So, maybe we can remove `mangleNameOrStandardSubstitution` and then use `mangleType`.

Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:7332]: Yes, although as I said before, there should be no observable change for these other users, as we don't perform other manglings either before or after calling `mangleNameOrStandardSubstitution`.

I would prefer the ergonomics of a function which takes a CXXRecordDecl. MangleType is also more complex and  will perform a bunch of checks which are not necessary if you only would ever have a RecordType, so there is also some aspect of micro-optimization and ease of debugging in having a specialized function.

Comment (tcwzxx) [reply clang/lib/AST/ItaniumMangle.cpp:7332]: Thanks, i see what you mean.

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks!

Can you also add a release note, mentioning the potential ABI breaking change?

Please wait 24h before merging in case the other reviewers want to chime in.

**Comment by zyn0217** [comment]
Do we need an ABI flag guarding against the change as well?

File: clang/test/CodeGenCXX/mangle.cpp [hunk 2]
```diff
@@ -1214,3 +1216,25 @@ namespace test61 {
...
+template <typename T>
+class Impl : public virtual VBase {
+ public:
+};
+
+}  // namespace A
+
+struct Inst : public A::Impl<A::Wrap> {};
+
+void Test() { Inst a; }
```
Comment (zygoloid) [inline clang/test/CodeGenCXX/mangle.cpp:1239]: This is a huge test file and unfortunately the test expectations here end up well over a thousand lines from the test. Can you move this to a different test file, maybe `mangle-subst.cpp` instead?

**Comment by zygoloid** [comment]
> Do we need an ABI flag guarding against the change as well?

Yeah, I think this change should respect `-fclang-abi-compat`.

File: clang/test/CodeGenCXX/mangle-subst.cpp [hunk 3]
```diff
@@ -1,4 +1,8 @@
 // RUN: %clang_cc1 -emit-llvm %s -o - -triple=x86_64-apple-darwin9 | FileCheck %s
+// RUN: %clang_cc1 -emit-llvm %s -o - -triple=x86_64-apple-darwin9 -fclang-abi-compat=19 | FileCheck %s --check-prefix=CHECK-CLANG-19
+
+//CHECK: @_ZTCN16MangleCtorVTable4InstE0_NS_1A4ImplINS1_4WrapEEE
+//CHECK-CLANG-19: @_ZTCN16MangleCtorVTable4InstE0_NS_1A4ImplINS0_4WrapEEE
```
Comment (zyn0217) [inline clang/test/CodeGenCXX/mangle-subst.cpp:5]: Can you move these two checks directly above the corresponding codes? Thanks!

File: clang/test/CodeGenCXX/mangle.cpp [hunk 4]
```diff
@@ -11,6 +11,7 @@ struct Y { };
 //CHECK: @pr5966_i = external global
 //CHECK: @_ZL8pr5966_j = internal global
 
+
```
Comment (zyn0217) [inline clang/test/CodeGenCXX/mangle.cpp:14]: nit: revert the blank line

File: clang/include/clang/Basic/LangOptions.h [hunk 5]
```diff
@@ -237,6 +237,11 @@ class LangOptionsBase {
     /// in the initializers of members of local classes.
     Ver18,
 
+    /// Attempt to be ABI-compatible with code generated by Clang 19.0.x.
+    /// This causes clang to:
+    ///   - Incorrect Mangling of CXXCtorVTable
```
Comment (zyn0217) [inline clang/include/clang/Basic/LangOptions.h:242]:
```suggestion
    ///   - Incorrectly mangle CXX vtable substitutions in some cases...
```

It would be great if you could flesh out the behavior changes here.

**Review by zyn0217 — APPROVED** [review]
Some nits, otherwise LGTM as well.

File: clang/test/CodeGenCXX/mangle-subst.cpp (hunk 3 above)
Comment (tcwzxx) [reply clang/test/CodeGenCXX/mangle-subst.cpp:5]: The construction vtable name is a global variable, so it cannot be moved above the corresponding code.

File: clang/include/clang/Basic/LangOptions.h (hunk 5 above)
Comment (tcwzxx) [reply clang/include/clang/Basic/LangOptions.h]: Thanks. Updated.
