### PR TITLE
[flang][Driver] Add support for -f[no-]wrapv and -f[no]-strict-overflow in the frontend

### LINKED ISSUE #78934: [Flang] TSVC s243: some `nsw` flags for address calculations will help vectorization
Flang can't vectorize the loop in `s243` of [TSVC](https://www.netlib.org/benchmark/vectors) while Clang can vectorize the loop written in C.

```fortran
! Fortran version
      module mod
      integer ld, nloops
      parameter (ld=1000,nloops=135)
      real a(ld), b(ld), c(ld), d(ld), e(ld)
      real aa(ld,ld), bb(ld,ld), cc(ld,ld)
      interface
      subroutine dummy(ld,n,a,b,c,d,e,aa,bb,cc,x)
         integer ld, n
         real a(ld), b(ld), c(ld), d(ld), e(ld)
         real aa(ld,ld), bb(ld,ld), cc(ld,ld)
         real, value :: x
      end subroutine
      end interface
      end module

      subroutine s243 (n)
      use mod
      integer n, i

      call init(ld,n,a,b,c,d,e,aa,bb,cc,'s243 ')
      do 10 i = 1,n-1
         a(i) = b(i) + c(i)   * d(i)
         b(i) = a(i) + d(i)   * e(i)
         a(i) = b(i) + a(i+1) * d(i)
  10  continue
      call dummy(ld,n,a,b,c,d,e,aa,bb,cc,1.)
      end
```

```c
// C version
#define LEN 32000
#define LEN2 256
float a[LEN], b[LEN], c[LEN], d[LEN], e[LEN];
float aa[LEN2][LEN2], bb[LEN2][LEN2], cc[LEN2][LEN2];

int s243() {
  init( "s243 ");
  for (int i = 0; i < LEN-1; i++) {
    a[i] = b[i] + c[i  ] * d[i];
    b[i] = a[i] + d[i  ] * e[i];
    a[i] = b[i] + a[i+1] * d[i];
  }
  dummy(a, b, c, d, e, aa, bb, cc, 0.);
  return 0;
}
```

```console
$ flang-new -v -Ofast s243.f -S -Rpass=vector
flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git 0e93d04001e45f39cabf0ffb5093512a7f622cc0)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/install/bin
Found candidate GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Selected GCC installation: /path/to/lib/gcc/aarch64-unknown-linux-gnu/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/install/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -S -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -ffast-math -target-cpu generic -target-feature +neon -target-feature +v8a -fstack-arrays -fversion-loops-for-stride -Rpass=vector -O3 -o s243.s -x f95-cpp-input s243.f
$ clang -Ofast s243.c -S -Rpass=vector
s243.c:15:3: remark: vectorized loop (vectorization width: 4, interleaved count: 1) [-Rpass=loop-vectorize]
   15 |                 for (int i = 0; i < LEN-1; i++) {
      |                 ^
```

The Fortran code isn't vectorized because DSE doesn't remove the first store to `a(i)`.
DSE uses BasicAA, and BasicAA can't say that `a(i)` and `a(i+1)` don't alias each other. So DSE doesn't work.

Actually, Flang generates LLVM IR like the following C code that makes alias analysis harder.
(FYI: BasicAA avoids complicated analyses which can affect the compilation time.)

```c
for (int i = 1; i <= n-1; i++) {
  a[i-1] = b[i-1] + c[i-1] * d[i-1];
  b[i-1] = a[i-1] + d[i-1] * e[i-1];
  a[i-1] = b[i-1] + a[i] * d[i-1];
}
```

Conversely, the following Fortran code is easy to be vectorized.

```fortran
      do 10 i = 0,n-2
         a(i+1) = b(i+1) + c(i+1) * d(i+1)
         b(i+1) = a(i+1) + d(i+1) * e(i+1)
         a(i+1) = b(i+1) + a(i+2) * d(i+1)
  10  continue
```

```console
$ flang-new -Ofast s243_2.f -S -Rpass=vector
path/to/s243_2.f:14:7: remark: vectorized loop (vectorization width: 4, interleaved count: 1) [-Rpass=loop-vectorize]
```

### PR DESCRIPTION
**Pull request by yus3710-fj**
This patch introduces the options for integer overflow flags into Flang.
The behavior is similar to that of Clang.

### CODE REVIEW

File: clang/lib/Driver/ToolChains/Flang.cpp [hunk 1]
```diff
@@ -866,6 +866,17 @@ void Flang::ConstructJob(Compilation &C, const JobAction &JA,
...
+  // -fstrict-overflow won't turn off an explicitly enabled -fwrapv.
+  if (Arg *A = Args.getLastArg(options::OPT_fwrapv, options::OPT_fno_wrapv)) {
+    if (A->getOption().matches(options::OPT_fwrapv))
+      CmdArgs.push_back("-fwrapv");
+  } else if (Arg *A = Args.getLastArg(options::OPT_fstrict_overflow,
+                                      options::OPT_fno_strict_overflow)) {
+    if (A->getOption().matches(options::OPT_fno_strict_overflow))
+      CmdArgs.push_back("-fwrapv");
+  }
+
```
Comment (tarunprabhu) [inline clang/lib/Driver/ToolChains/Flang.cpp:879]: If this code is exactly the same as it is in clang, it would be better if it is shared. In `clang/lib/Driver/ToolChains/CommonArgs.cpp`, see `handleColorDiagnosticsArgs` for a case of common argument handling functionality between clang and flang. This was done in #109210

File: flang/test/Driver/integer-overflow.f90 [hunk 2]
```diff
@@ -0,0 +1,10 @@
+! Test for correct forwarding of integer overflow flags from the compiler driver
+! to the frontend driver
+
+! RUN: %flang -### -fno-strict-overflow %s 2>&1 | FileCheck %s --check-prefixes CHECK,INDUCED
```
Comment (tarunprabhu) [inline flang/test/Driver/integer-overflow.f90:4]: Do we need both the `CHECK` and `INDUCED` here?

**Review by tarunprabhu — CHANGES_REQUESTED** [review]

File: clang/lib/Driver/ToolChains/Flang.cpp (hunk 1 above)
Comment (yus3710-fj) [reply clang/lib/Driver/ToolChains/Flang.cpp]: Thank you for showing me a better way.
I created a function `renderIntegerOverflowOptions` to handle common options between clang and flang. However, I'm not sure the name of the function is appropriate because there are other related options handled only by clang (e.g. `-ftrapv`).

File: flang/test/Driver/integer-overflow.f90 (hunk 2 above)
Comment (yus3710-fj) [reply flang/test/Driver/integer-overflow.f90]: As you mentioned, the check for `CHECK` is redundant. I removed it.

File: clang/lib/Driver/ToolChains/Flang.cpp (hunk 1 above)
Comment (tarunprabhu) [reply clang/lib/Driver/ToolChains/Flang.cpp]: Perhaps the function could be named `renderCommonIntegerOverflowOptions` which suggests that it does not handle all overflow options?

File: clang/lib/Driver/ToolChains/Clang.cpp [hunk 3]
```diff
@@ -6921,16 +6921,9 @@ void Clang::ConstructJob(Compilation &C, const JobAction &JA,
...
-  // -fstrict-overflow won't turn off an explicitly enabled -fwrapv.
-  if (Arg *A = Args.getLastArg(options::OPT_fwrapv, options::OPT_fno_wrapv)) {
-    if (A->getOption().matches(options::OPT_fwrapv))
-      CmdArgs.push_back("-fwrapv");
-  } else if (Arg *A = Args.getLastArg(options::OPT_fstrict_overflow,
-                                      options::OPT_fno_strict_overflow)) {
-    if (A->getOption().matches(options::OPT_fno_strict_overflow))
-      CmdArgs.push_back("-fwrapv");
-  }
+  // handle -f[no-]wrapv and -f[no-]strict-overflow, which are used by both
```
Comment (MaskRay) [inline clang/lib/Driver/ToolChains/Clang.cpp:6924]: `// Handle ... `

Capitalization and adding a trailing period.

File: flang/include/flang/Common/LangOptions.h [hunk 4]
```diff
@@ -27,6 +27,14 @@ namespace Fortran::common {
 class LangOptionsBase {
 
 public:
+  enum SignedOverflowBehaviorTy {
+    // -fno-wrapv (default behavior in Flang)
+    SOB_Undefined,
```
Comment (MaskRay) [inline flang/include/flang/Common/LangOptions.h:32]: unused? Not sure that this definition is useful

File: clang/lib/Driver/ToolChains/Flang.cpp (hunk 1 above)
Comment (yus3710-fj) [reply clang/lib/Driver/ToolChains/Flang.cpp]: That sounds good. I fixed it. Thank you.

File: clang/lib/Driver/ToolChains/Clang.cpp (hunk 3 above)
Comment (yus3710-fj) [reply clang/lib/Driver/ToolChains/Clang.cpp]: Thank you for pointing it out. I fixed it.

File: flang/include/flang/Common/LangOptions.h (hunk 4 above)
Comment (yus3710-fj) [reply flang/include/flang/Common/LangOptions.h:32]: This is used as the default value of a LangOption `SignedOverflowBehavior`. If the behavior is not defined, `nsw` could be added to some operations such as `add`.
FWIW, this implementation is simliar to [that of Clang](https://github.com/llvm/llvm-project/blob/b672071ba51ef6b64651a62bcfaf78bdfdb7d3d4/clang/include/clang/Basic/LangOptions.h#L87-L96).

**Review by tarunprabhu — APPROVED** [review]
Thank you for the changes, Minato san. LGTM.

**Comment by yus3710-fj** [comment]
Gentle ping @MaskRay.

**Review by tblah — APPROVED** [review]
This looks good to me, thanks!

**Review by MaskRay — APPROVED** [review]
clangDriver part LG.

**Comment by yus3710-fj** [comment]
Thank you all for the review! I'll merge this after rebasing.

**Comment by yus3710-fj** [comment]
CI failed due to `ClangdTests/25/79` (`DynamicIndexIncludeInsertion` in CodeCompleteTests.cpp?). It's weird because there is no functional change on clang (and clangd). In addition, I can't reproduce this on my machine.
I'll try re-running CI with an empty commit.

**Comment by yus3710-fj** [comment]
CI failed again, but the test mentioned above was passed this time. So, I think I can merge this.
