### PR TITLE
[clang-tidy] use specified type verbatim in modernize-use-using fix

### LINKED ISSUE #33760: modernize-use-using evaluates macros when constructing the replacement
|  |  |
| --- | --- |
| Bugzilla Link | [34412](https://llvm.org/bz34412) |
| Version | unspecified |
| OS | Linux |
| Blocks | llvm/llvm-project#37846  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Version of clang-tidy: 4.0
Check: modernize-use-using

// Before:

#ifndef	SpecialMode
    #define SomeMacro(x) x              
#else
    #define SomeMacro(x) SpecialType
#endif

class SomeMacro(SomeType) { };

typedef void(SomeMacro(SomeType)::*FunctionType)(float arg1, int arg2);

// After:

#ifndef SpecialMode
    #define SomeMacro(x) x
#else
    #define SomeMacro(x) SpecialType
#endif

class SomeMacro(SomeType) { };

using FunctionType = void (SomeType::*)(float, int); // evaluated macro instead of "SomeMacro(SomeType)"

### LINKED ISSUE #37846: modernize-use-using breaks certain function pointer types with macros
|  |  |
| --- | --- |
| Bugzilla Link | [38498](https://llvm.org/bz38498) |
| Version | unspecified |
| OS | Linux |
| Depends On | llvm/llvm-project#33760  |
| CC | @AaronBallman,@EugeneZelenko,@steveire |

## Extended Description 
clang-tidy version: 6.0.0

While replacing macros with their definitions (which is wrong, see bug 34412), clang-tidy breaks function pointer types badly. See the following example:

  #define CDECL __attribute((cdecl))

  // BEFORE
  typedef void (CDECL *FuncType)(int a);
  // AFTER
  using FuncType = void (*)(int) __attribute__((cdecl)))(int a);
  // should be
  using FuncType = void (CDECL *)(int a);

I don't know if this only happens when the macro contains an attribute (what with the parentheses), but I don't know what else I'd want to put in there.

### LINKED ISSUE #41685: modernize-use-using ignores __attribute__
|  |  |
| --- | --- |
| Bugzilla Link | [42340](https://llvm.org/bz42340) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko |

## Extended Description 
Giving this example input and command, the __attribute__ is ignored by this clang-tidy check and lost by the --fix flag.

$ cat /tmp/x.cpp
typedef __attribute__((__aligned__(1))) unsigned int UUINT;

$ bin/clang-tidy --checks=modernize-use-using /tmp/x.cpp --
1 warning generated.
/tmp/x.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef __attribute__((__aligned__(1))) unsigned int UUINT;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using UUINT = unsigned int

$ bin/clang-tidy --checks=modernize-use-using -fix /tmp/x.cpp --
1 warning generated.
/tmp/x.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef __attribute__((__aligned__(1))) unsigned int UUINT;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using UUINT = unsigned int
/tmp/x.cpp:1:1: note: FIX-IT applied suggested code changes
clang-tidy applied 1 of 1 suggested fixes.

$ cat /tmp/x.cpp
using UUINT = unsigned int;

### LINKED ISSUE #83568: Clang-tidy modernize-use-using on function pointers removes the argument names
`typedef int(*name)(int arg1, int arg2);` is a valid definition of a function pointer where not only the types are given, though they also got names. The clang-tidy check modernize-use-using wants to convert this into `using name = int (*)(int, int);`, the expectation is that this gets converted to `using name = int (*)(int arg1, int arg2);`

Link on compiler-explorer: https://compiler-explorer.com/z/Gan7Y77zq

### LINKED ISSUE #95716: clang-tidy: modernize-use-using wrongly expands macro
Prepare `/tmp/a.cpp`:

```cpp
#ifdef FOO
#define REAL float
#else
#define REAL double
#endif

typedef REAL foo;
```

and `/tmp/compile_commands.json`:

```json
[ { "directory": "/tmp", "command": "clang++ -std=c++11 -c -o a.o a.cpp", "file": "a.cpp", "output": "a.o" } ]
```

```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 17.0.6
  Optimized build.
$ clang-tidy --fix --checks=modernize-use-using a.cpp 
1 warning generated.
a.cpp:7:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
    7 | typedef REAL foo;
      | ^~~~~~~~~~~~~~~~
      | using foo = double
a.cpp:7:1: note: FIX-IT applied suggested code changes
clang-tidy applied 1 of 1 suggested fixes.
```

gives

```cpp
using foo = double;
```

which must be

```cpp
using foo = REAL;
```

<https://godbolt.org/z/s17GT95EW>

### LINKED ISSUE #97009: clang-tidy: modernize-use-using replaces typedef names by the aliased type
clang-tidy check modernize-use-using (LLVM 18.1.2) replaces the typedef name (PointType) by the aliased type (double*)

The code fragment
```
typedef double PointType[3];
typedef bool (*Function)(PointType, PointType);
```
is refactored to 
```
typedef double PointType[3];
using Function = bool (*)(double *, double *);
```

but should have been refactored to
```
typedef double PointType[3];
using Function = bool (*)(PointType, PointType);
```

### PR DESCRIPTION
**Pull request by 5chmidti**
Previously, the implementation used the printed type, which contains expanded
macro arguments, deletes comments, and removes function argument names 
from the alias declaration. Instead, this check can be more surgical and use the
actual written type verbatim.

Fixes #33760
Fixes #37846
Fixes #41685
Fixes #83568
Fixes #95716
Fixes #97009

### CODE REVIEW

File: clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp [hunk 1]
```diff
@@ -119,14 +122,55 @@ void UseUsingCheck::check(const MatchFinder::MatchResult &Result) {
...
+                       Lexer::getLocForEndOfToken(MatchedDecl->getLocation(), 0,
+                                                  *Result.SourceManager,
+                                                  getLangOpts()),
+                       Lexer::getLocForEndOfToken(TL.getEndLoc(), 0,
+                                                  *Result.SourceManager,
+                                                  getLangOpts())),
+                   *Result.SourceManager, getLangOpts()))
+                  .str(),
+              ""};
+    }
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp:149]: Could you somehow refactor this part of code. It is too hard to understand what is the meaning of each  substring due to indentation

Comment (5chmidti) [reply clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp]: Is something like this what you had in mind?

**Review by 5chmidti — COMMENTED** [review]
I noticed some more issues that this is fixing, so I've added their examples as test-cases

**Comment by 5chmidti** [comment]
Ping

**Review by HerrCai0907 — APPROVED** [review]
LGTM
