### PR TITLE
[lldb] Fix windows debug build after 9d07f43

### LINKED ISSUE #104895: After this patch it is very hard to build lldb (debug version) on Windows.
After this patch it is very hard to build lldb (debug version) on Windows.
We got the errors like the following
```
D:\llvm-project\lldb\source\Plugins\ScriptInterpreter\Python\Interfaces\ScriptedThreadPlanPythonInterface\ScriptedThreadPlanPythonInterface.cpp: 
fatal error C1041: cannot open program database 'D:\build-lldb\tools\lldb\source\Plugins\ScriptInterpreter\Python\Interfaces\ScriptedThreadPlanPythonInterface\CMakeFiles\lldbPluginScriptInterpreterPythonScriptedThreadPlanPythonInterface.dir\lldbPluginScriptInterpreterPythonScriptedThreadPlanPythonInterface.pdb'; 
if multiple CL.EXE write to the same .PDB file, please use /FS
```
Note MAX_PATH is 260 on Windows. But the length of the path to .pdb is 262.
It is necessary to use 7 chars or less folder in the root of a disk to build lldb (debug version) on Windows using Microsoft VC++. 
You must reduce the length of the paths.

_Originally posted by @slydiman in https://github.com/llvm/llvm-project/issues/101672#issuecomment-2289481324_

### PR DESCRIPTION
**Pull request by medismailben**
This patch tries to fix an issue with the windows debug builds where the PDB file for python scripted interfaces cannot be opened since its path length exceed the windows `MAX_PATH` limit:

https://github.com/llvm/llvm-project/pull/101672#issuecomment-2289481324

This patch addresses the issue by building all the interfaces as a single library plugin that initiliazes each component as part of its `Initialize` method, instead of building each interface as its own library plugin.

This keeps the build artifact path length smaller while respecting the naming convention and without making any exception in the build system.

Fixes #104895.

### CODE REVIEW

File: lldb/source/Plugins/ScriptInterpreter/Python/Interfaces/ScriptInterpreterPythonInterfaces.cpp [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+using namespace lldb_private;
+
+LLDB_PLUGIN_DEFINE(ScriptInterpreterPythonInterfaces)
+
+llvm::StringRef
+ScriptInterpreterPythonInterfaces::GetPluginDescriptionStatic() {
+  return "Script Interpreter Python Interfaces";
+}
+
+void ScriptInterpreterPythonInterfaces::Initialize() {
```
Comment (medismailben) [inline lldb/source/Plugins/ScriptInterpreter/Python/Interfaces/ScriptInterpreterPythonInterfaces.cpp:27]: FWIW, this is the most interesting part.

**Review by JDevlieghere — APPROVED** [review]
LGTM!

**Review by bulbazord — APPROVED** [review]

**Comment by labath** [comment]
Thanks.
