### PR TITLE
[compiler-rt][test] Add REQUIRES: shell to compiler-rt tests that use the `ulimit` command

### LINKED ISSUE #102398: [llvm-lit] Ulimit command not found in lit internal shell
The LLVM's lit internal shell fails to find the `ulimit` command and fails to set resource limits.
Error displayed:
```
# executed command: ulimit -s 1000
# .---command stderr------------
# | 'ulimit': command not found
# `-----------------------------
# error: command failed with exit status: 127
```

### PR DESCRIPTION
**Pull request by Harini0924**
This patch adds the `REQUIRES: shell`  directive to six test files that use the `ulimit` command, ensuring these tests are only run in environments where a full POSIX-compliant shell is available. The lit internal shell does not use or support the `ulimit` command, which causes failures when running tests with  `LIT_USE_INTERNAL_SHELL=1 ninja check-compiler-rt`
Specifically, one of the errors encountered is: 
```
# RUN: at line 4
ulimit -s 1000
# executed command: ulimit -s 1000
# .---command stderr------------
# | 'ulimit': command not found
# `-----------------------------
# error: command failed with exit status: 127
```
Since, the lit internal shell doesn't support `ulimit`, adding this requirement prevents these tests from failing in the lit internal shell, thereby improving the reliability of the test suite in environments where the full shell is not available.

This change is relevant for [[RFC] Enabling the Lit Internal Shell by Default](https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179/3)  
fixes:  #102398

### CODE REVIEW

**Comment by Harini0924** [comment]
CC: @ilovepi @petrhosek @jh7370

File: compiler-rt/test/asan/TestCases/Linux/allocator_oom_test.cpp [hunk 1]
```diff
@@ -7,7 +7,7 @@
 // Limit this test to Linux since we're relying on allocator internal
 // limits (shadow memory size, allocation limits etc.)
 
-REQUIRES: shell
+REQUIRES : shell
```
[the remark this answers is not in the document]
Comment (ilovepi) [reply compiler-rt/test/asan/TestCases/Linux/allocator_oom_test.cpp:10]: Ah, I missed that the `Requires :` is not prefixed with `//`. Please address that too.

[the remark this answers is not in the document]
Comment (ilovepi) [reply compiler-rt/test/asan/TestCases/Linux/allocator_oom_test.cpp]: The code formatting still seems to be an issue. The changes to the c++ should not be in the patch at all.

File: compiler-rt/test/fuzzer/ulimit.test [hunk 2]
```diff
@@ -1,4 +1,5 @@
 # FIXME: Disabled on Windows for now because Windows has no ulimit command.
+REQUIRES: shell
 UNSUPPORTED: target={{.*windows.*}}
```
Comment (MaskRay) [inline compiler-rt/test/fuzzer/ulimit.test:3]: Remove `windows` and FIXME

File: compiler-rt/test/fuzzer/merge-posix.test [hunk 3]
```diff
@@ -1,3 +1,4 @@
+REQUIRES: shell
 XFAIL: ios
 UNSUPPORTED: target={{.*windows.*}}
```
Comment (MaskRay) [inline compiler-rt/test/fuzzer/merge-posix.test:3]: Remove `windows` and FIXME

**Review by MaskRay — APPROVED** [review]

File: compiler-rt/test/fuzzer/ulimit.test (hunk 2 above)
Comment (ilovepi) [reply compiler-rt/test/fuzzer/ulimit.test:3]: Maybe the fixme should stay(or be updated), since we could remove REQUIRES: shell, without the use of ulimit? WDYT?

**Comment by Harini0924** [comment]
After discussing with @ilovepi we decided to rebase all the commits to fix the code formatter issues.

**Comment by Harini0924** [comment]
@MaskRay I removed `windows` and FIXME. Should I change anything else in this patch?

**Comment by ilovepi** [comment]
Probably worth updating the title to `[compiler-rt][test] Add REQUIRES: shell in tests that use the ulimit`, since you're not changing anything in `llvm-lit`.

File: compiler-rt/test/asan/TestCases/Posix/deep_call_stack.cpp [hunk 4]
```diff
@@ -1,3 +1,4 @@
+// REQUIRES: shell
```
Comment (fmayer) [inline compiler-rt/test/asan/TestCases/Posix/deep_call_stack.cpp:1]: nit: i would prefer if the comment stayed in the first line

File: compiler-rt/test/hwasan/TestCases/print-memory-usage.c [hunk 5]
```diff
@@ -1,3 +1,4 @@
+// REQUIRES: shell
```
Comment (fmayer) [inline compiler-rt/test/hwasan/TestCases/print-memory-usage.c:1]: as above

File: compiler-rt/test/msan/Linux/reexec_unlimited_stack.cpp [hunk 6]
```diff
@@ -1,3 +1,4 @@
+// REQUIRES: shell
```
Comment (fmayer) [inline compiler-rt/test/msan/Linux/reexec_unlimited_stack.cpp:1]: as above

**Review by fmayer — APPROVED** [review]

File: compiler-rt/test/asan/TestCases/Posix/deep_call_stack.cpp (hunk 4 above)
Comment (Harini0924) [reply compiler-rt/test/asan/TestCases/Posix/deep_call_stack.cpp]: Done.

File: compiler-rt/test/hwasan/TestCases/print-memory-usage.c (hunk 5 above)
Comment (Harini0924) [reply compiler-rt/test/hwasan/TestCases/print-memory-usage.c]: Done.

File: compiler-rt/test/msan/Linux/reexec_unlimited_stack.cpp (hunk 6 above)
Comment (Harini0924) [reply compiler-rt/test/msan/Linux/reexec_unlimited_stack.cpp]: Done.
