### PR TITLE
[clang] Reject constexpr-unknown values as constant expressions more consistently

### LINKED ISSUE #129844: Miscompile with C++23 constexpr-unknown constant evaluation
Testcase:

```
int &ff();
int &x = ff();
struct A { int& x; };
struct B { A x[20]; };
B f() { return {x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x}; }
```

Generates the following, which is wrong because the references point to x itself, not the referenced lvalue.

```
[...]
@constinit = private constant [20 x %struct.A] [%struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }, %struct.A { ptr @x }], align 8
[...]
define dso_local void @_Z1fv(ptr dead_on_unwind noalias writable sret(%struct.B) align 8 %agg.result) #2 {
entry:
  %x = getelementptr inbounds nuw %struct.B, ptr %agg.result, i32 0, i32 0
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %x, ptr align 8 @constinit, i64 160, i1 false)
  ret void
}
```

This is synthetic; I have no idea how likely it is for anyone to actually run into this.  Filing as a followup to discussion on #128409.

### LINKED ISSUE #129845: accepts-invalid with C++23 constexpr-unknown with struct containing reference
```
int &ff();
int &x = ff();
struct A { int& x; };
constexpr A g = {x};
const A* gg = &g;
```

Should be rejected, currently accepted.  (And related variations miscompile.)

### PR DESCRIPTION
**Pull request by efriedma-quic**
Perform the check for constexpr-unknown values in the same place we perform checks for other values which don't count as constant expressions.

While I'm here, also fix a rejects-valid with a reference that doesn't have an initializer.  This diagnostic was also covering up some of the bugs here.

The existing behavior with -fexperimental-new-constant-interpreter seems to be correct, but the diagnostics are slightly different; it would be helpful if someone could check on that as a followup.

Followup to #128409.

Fixes #129844. Fixes #129845.

### CODE REVIEW

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp [hunk 1]
```diff
@@ -154,3 +154,26 @@ int g() {
     static_assert(f(arr) == 5);
 }
 }
+
+namespace GH128409 {
+  int &ff();
+  int &x = ff(); // nointerpreter-note {{declared here}}
+  constinit int &z = x; // expected-error {{variable does not have a constant initializer}}
```
Comment (tbaederr) [inline clang/test/SemaCXX/constant-expression-p2280r4.cpp:161]: If you end the comments in `\`, you don't need to add the `@-2` stuff.

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp [hunk 2]
```diff
@@ -154,3 +154,26 @@ int g() {
...
+                        // expected-note@-1 {{required by 'constinit' specifier here}}
+                        // nointerpreter-note@-2 {{initializer of 'x' is not a constant expression}}
```
Comment (tbaederr) [inline clang/test/SemaCXX/constant-expression-p2280r4.cpp:163]: I don't want to block on this, but the diagnostic here is a little off... Even _if_ the initializer of `x` was a constant expression, the declaration of `z` would still not be valid because `x` is not const (or constexpr).

In other words, if I saw this error in practice, I'd try to fix `x`'s initializer, just to be greeted by another diagnostic.

**Review by cor3ntin — APPROVED** [review]
I think this makes sense.
Presumably we would backport it to 20

File: clang/test/SemaCXX/constant-expression-p2280r4.cpp (hunk 2 above)
Comment (efriedma-quic) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp:163]: Both clang and gcc accept the following:

```
int y;
int &r1 = y;
constinit int &r2 = r1;
```

I think that's right, looking at the rules for "potentially-constant" variables?

Comment (tbaederr) [reply clang/test/SemaCXX/constant-expression-p2280r4.cpp]: https://godbolt.org/z/81M8aYGPn
Yeah, not a fan of any of this. But this patch LGTM.

**Comment by DavidSpickett** [comment]
The failure above is real, ABI or 32-bitness issue I think. Looking at it now.

**Comment by DavidSpickett** [comment]
https://github.com/llvm/llvm-project/pull/130589
