### PR TITLE
[lldb-dap] Specify the executable path in the attach info

### LINKED ISSUE #138197: [lldb-dap] Parallel test execution caused attach by name failure
While investing some lldb-dap attach issues I have been running the lldb-dap test suite and one failure I came across is the test that attaches by name attached to another running tests `a.out`.

From the logs for `TestDAP_attach.test_by_name_waitFor` https://github.com/llvm/llvm-project/blob/8d02529f77f809a1a8db623a3a124a33f0be94b9/lldb/test/API/tools/lldb-dap/attach/TestDAP_attach.py#L98-L115

```
1746130571.456615925 <-- (stdin/stdout) {"body":{"isLocalProcess":true,"name":"/Users/harjohn/Projects/lldb-build/lldb-test-build.noindex/tools/lldb-dap/commands/TestDAP_commands.test_command_directive_abort_on_error_post_run_commands/a.out","startMethod":"attach","systemProcessId":97352},"event":"process","seq":0,"type":"event"}
```

It ended up attaching to `TestDAP_commands.test_command_directive_abort_on_error_post_run_commands/a.out`, which is the wrong binary.

This likely happened because the tests were running in parallel on my machine but we should see if we can prevent this from happening.

### PR DESCRIPTION
**Pull request by JDevlieghere**
Currently, we are only using the executable name when attaching. The AttachRequestHandler isn't setting the path in the attach info, which means that we rely on the target when attaching by name. When wo go down this path, we only look at the executable's filename, not its full path. Since we know the full path from the attach arguments, we should specify it in the attach info.

Fixes #138197

### CODE REVIEW

File: lldb/tools/lldb-dap/Handler/AttachRequestHandler.cpp [hunk 1]
```diff
@@ -161,7 +157,13 @@ void AttachRequestHandler::operator()(const llvm::json::Object &request) const {
         dap.target.ConnectRemote(listener, connect_url.c_str(), "gdb-remote",
                                  error);
       } else {
-        // Attach by process name or id.
+        // Attach by pid or process name.
+        lldb::SBAttachInfo attach_info;
+        if (pid != LLDB_INVALID_PROCESS_ID)
+          attach_info.SetProcessID(pid);
+        if (dap.configuration.program.has_value())
```
Comment (Jlalond) [inline lldb/tools/lldb-dap/Handler/AttachRequestHandler.cpp:164]: just a nit, but wouldn't an `if else` make sense here, because if we have the pid we don't even need to send the executable path in the attach info?

**Review by ashgti — APPROVED** [review]
LGTM!
