### PR TITLE
[Clang] Fix : More Detailed "No expected directives found"

### LINKED ISSUE #58290: "No expected directives found" error message is confusing if `-verify=foo` was passed
If one passes `-verify=foo`, the error message when no `foo-*` directives are found is:

```console
error: no expected directives found: consider use of 'expected-no-diagnostics'
```
however, what's meant here is not `expected-no-diagnostics` but of course `foo-no-diagnostics`. This is especially confusing if multiple compiler invocations with different `-verify=` values are present.

The error message should use the proper prefix.

### PR DESCRIPTION
**Pull request by Sh0g0-1758**
Fixes: #58290

**PR SUMMARY**: "Updated the error message to use the proper prefix when no expected directives are found by changing the hard coded expected in the message to a dynamic value in two error messages"

### CODE REVIEW

**Comment by Sh0g0-1758** [comment]
Screenshot from 2024-01-17 02-39-09
Here you can see a working implementation of the asked feature.

**Comment by Sh0g0-1758** [comment]
I have pushed code in this PR that aims to solve this [issue](https://github.com/llvm/llvm-project/pull/66540) also.

**Comment by Sh0g0-1758** [comment]
Screenshot from 2024-01-17 02-48-15
Here is a working implementation of the second issue that I aim to solve.

File: clang/include/clang/Basic/Diagnostic.h [hunk 1]
```diff
@@ -9,7 +9,9 @@
 /// \file
 /// Defines the Diagnostic-related interfaces.
 //
-//===----------------------------------------------------------------------===//
+//===----------------------------------------------------------------------===//]
+
+// look into this file as well
```
Comment (asl) [inline clang/include/clang/Basic/Diagnostic.h:14]: Remove

File: clang/lib/AST/ASTContext.cpp [hunk 2]
```diff
@@ -1404,7 +1404,7 @@ void ASTContext::InitBuiltinTypes(const TargetInfo &Target,
     getTranslationUnitDecl()->addDecl(MSGuidTagDecl);
   }
 }
-
+// maybe change here also.
```
Comment (asl) [inline clang/lib/AST/ASTContext.cpp:1407]: Ditto

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 3]
```diff
@@ -1098,7 +1098,10 @@ void VerifyDiagnosticConsumer::CheckDiagnostics() {
     // Produce an error if no expected-* directives could be found in the
     // source file(s) processed.
     if (Status == HasNoDirectives) {
-      Diags.Report(diag::err_verify_no_directives).setForceEmit();
+      // change here
```
Comment (asl) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1101]: Ditto

File: llvm/utils/git/github-automation.py [hunk 4]
```diff
@@ -635,16 +635,16 @@ def execute_command(self) -> bool:
         """
         This function reads lines from STDIN and executes the first command
         that it finds.  The 2 supported commands are:
-        /cherry-pick commit0 <commit1> <commit2> <...>
```
Comment (asl) [inline llvm/utils/git/github-automation.py:638]: Do not include unrelated things into a PR

**Review by asl — CHANGES_REQUESTED** [review]
Ensure that PR does not contain unrelated things. See https://llvm.org/docs/Contributing.html#how-to-submit-a-patch for more information

File: llvm/utils/git/github-automation.py (hunk 4 above)
Comment (Sh0g0-1758) [reply llvm/utils/git/github-automation.py:638]: Hello, I was assigned two issues and I have solved both of them to the best of my knowledge. And I pushed the patch for the second issue after solving the first one. Since I can't create a new PR when my first PR has not been merged yet, So I thought of just pushing it as I wanted to work on more issues. The issues are : [this](https://github.com/llvm/llvm-project/issues/58290#issuecomment-1886650144) and [this](https://github.com/llvm/llvm-project/issues/64803)

Comment (Sh0g0-1758) [reply llvm/utils/git/github-automation.py:638]: Since @tbaederr was involved in both the issues, I hope both the patches can be considered in a single PR.

**Comment by Sh0g0-1758** [comment]
I have removed the unnecessary comments. @asl please do let me know whether I should submit different PRs for the issues. But I think that @tbaederr can review them both in this PR only. Also @asl , do let me know any other required changes.

File: llvm/utils/git/github-automation.py (hunk 4 above)
Comment (asl) [reply llvm/utils/git/github-automation.py:638]: You certainly could submit multiple PRs for separate changes.

File: clang/include/clang/Basic/Diagnostic.h [hunk 5]
```diff
@@ -9,7 +9,7 @@
 /// \file
 /// Defines the Diagnostic-related interfaces.
 //
-//===----------------------------------------------------------------------===//
+//===----------------------------------------------------------------------===//]
```
Comment (asl) [inline clang/include/clang/Basic/Diagnostic.h:12]: still unrelated change. I would suggest you to carefully check all the code in the PR

**Comment by Sh0g0-1758** [comment]
@asl, I have checked all the files I changed and I have removed the unrelated changes and the changes related to another issue. Really sorry for this, I hope you can overlook it since this is my very first PR in LLVM.

File: clang/include/clang/Basic/Diagnostic.h (hunk 5 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/Diagnostic.h]: done

**Review by tbaederr — CHANGES_REQUESTED** [review]

File: clang-tools-extra/clangd/test/indexer.test [hunk 6]
```diff
@@ -5,5 +5,5 @@
 # `.ii` file and `-verify` triggers extra diagnostics generation. Clangd should
 # strip those.
 # RUN: clangd-indexer %t.cpp -- -Xclang -verify --save-temps -- 2>&1 | FileCheck %s
-# CHECK-NOT: error: no expected directives found: consider use of 'expected-no-diagnostics'
+# CHECK-NOT: error: no expected directives found: consider use of {{.*}}-no-diagnostics
```
[the remark this answers is not in the document]
Comment (Sh0g0-1758) [reply clang-tools-extra/clangd/test/indexer.test]: ah yes, overlooked that. Will revert it.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td [hunk 7]
```diff
@@ -179,7 +179,7 @@ def err_verify_invalid_no_diags : Error<
     "%select{expected|'expected-no-diagnostics'}0 directive cannot follow "
     "%select{'expected-no-diagnostics' directive|other expected directives}0">;
 def err_verify_no_directives : Error<
-    "no expected directives found: consider use of 'expected-no-diagnostics'">;
+    "no expected directives found: consider use of '%0'-no-diagnostics">;
```
[the remark this answers is not in the document]
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td]: changed it to this norm and modified the test cases correspondingly.

**Comment by Sh0g0-1758** [comment]
@tbaederr, please review the changes.

File: clang/test/ARCMT/verify.m [hunk 8]
```diff
@@ -11,7 +11,7 @@
 #error
 // expected-error@-1 {{}}
 
-//      CHECK: error: no expected directives found: consider use of 'expected-no-diagnostics'
+//      CHECK: error: no expected directives found: consider use of '{{.*}}-no-diagnostics'
```
Comment (tbaederr) [inline clang/test/ARCMT/verify.m:14]: Do all these tests really fail if you leave "expected-no-diagnostics" in the expected output? Or can you just change that to a concrete value instead of the regex?

Comment (Sh0g0-1758) [reply clang/test/ARCMT/verify.m:14]: yes since I changed the error output value in the tds file, these tests needed to be changed with the regex.

Comment (tbaederr) [reply clang/test/ARCMT/verify.m:14]: And what is the output now? Both RUN lines only pass `-verify` so the prefix shouldn't change?

Comment (Sh0g0-1758) [reply clang/test/ARCMT/verify.m:14]: Oh, I think I overlooked this. I then would have to revert the test changes. Please give me a confirmation to do so and also suggest whether or not I should write separate test cases for -verify=foo,bar for the change that this PR intends to implement.

Comment (tbaederr) [reply clang/test/ARCMT/verify.m:14]: This test only passes `-verify` though, what's the new output and why doesn't the old expected output work?

Comment (Sh0g0-1758) [reply clang/test/ARCMT/verify.m:14]: the intended behavior is that when only `-verify` is passed and there are no diagnostics in the file then `expected-no-diagnostics` should be the error and when `-verify=foo` is passed and no such diagnostics is present in the file, then `foo-no-diagnostics` should be the error.

Comment (Sh0g0-1758) [reply clang/test/ARCMT/verify.m]: @tbaederr, I understand what you are trying to point out and I hope I rectified that in my new commit. I will add a screenshot of the working implementation also.

**Comment by Sh0g0-1758** [comment]
Please see the desired behavior in this screenshot : 

Screenshot from 2024-01-20 00-23-12

With `-verify=` we get `expected-no-diagnostics` and with `-verify=foo` we get `foo-no-diagnostics`

**Comment by Sh0g0-1758** [comment]
gentle ping @tbaederr .

**Comment by tbaederr** [comment]
The policy is to ping _once a week_. It's the weekend.

**Comment by Sh0g0-1758** [comment]
Ah really sorry. Pardon my enthu (ó﹏ò｡)

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 9]
```diff
@@ -1098,7 +1098,16 @@ void VerifyDiagnosticConsumer::CheckDiagnostics() {
     // Produce an error if no expected-* directives could be found in the
     // source file(s) processed.
     if (Status == HasNoDirectives) {
-      Diags.Report(diag::err_verify_no_directives).setForceEmit();
+      std::string directives;
+      for (auto &Prefix : Diags.getDiagnosticOptions().VerifyPrefixes) {
+        directives = directives + Prefix + ",";
+      }
```
Comment (tbaederr) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1104]: In `PrintUnexpected` we're simply using `Diags.getDiagnosticOptions().VerifyPrefixed.begin`.  How is this case different?

Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1104]: yes suppose multiple diagnostics were not found like given in the third case here : 

> Screenshot from 2024-01-20 00-23-12

then in the error generated, I give all the diagnostics as ```consider use of 'foo,alpha,bar,gamma-no-diagnostics'```. But if that is not the intended behavior or if multiple errors are expected to be emitted in response to multiple diagnostics not found, then that can also be done. Please specify which of the two is required.

Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1104]: I think the one I implemented is a better option as it batched the same types of errors into one and gave the programmer a concise view of the error.

Comment (tbaederr) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1104]: Well but I can't add a "foo,alpha,bar,gamma-no-diagnostics"(literally) comment to the test, right? That doesn't work?

Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1104]: Yes, I see your point. In that case I will change the code to now emit multiple errors and not batch them into one. so if you pass ```-verify=foo,bar``` and there are no such directives in the code then two errors with ```foo-no-diagnostics``` and ```bar-no-diagnostics``` will be generated. Please give me a confirmation to do so.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 10]
```diff
@@ -1098,7 +1098,13 @@ void VerifyDiagnosticConsumer::CheckDiagnostics() {
     // Produce an error if no expected-* directives could be found in the
     // source file(s) processed.
     if (Status == HasNoDirectives) {
-      Diags.Report(diag::err_verify_no_directives).setForceEmit();
+      std::string directives;
+      if (Diags.getDiagnosticOptions().VerifyPrefixes.empty()) {
+        directives = "expected";
```
Comment (tbaederr) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1103]: I don't think this can be empty. Have you checked that this can actually happen?

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 11]
```diff
@@ -1098,7 +1098,13 @@ void VerifyDiagnosticConsumer::CheckDiagnostics() {
     // Produce an error if no expected-* directives could be found in the
     // source file(s) processed.
     if (Status == HasNoDirectives) {
-      Diags.Report(diag::err_verify_no_directives).setForceEmit();
+      std::string directives;
```
Comment (tbaederr) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1101]:
```suggestion
      std::string Directive;
```

**Review by tbaederr — CHANGES_REQUESTED** [review]

**Comment by tbaederr** [comment]
Adding Aaron since we're probably getting close.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 10 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1103]: yes, when there are no diagnostics passed in the verify, ie. when we pass ```-verify=``` only. In this case ```expected-no-directives``` should be the error output when no directives are present. and when we pass ```-verify=foo``` then ```foo-no-diagnostics``` should be the error when no foo directives are present. If I don't include this check, then with only ```-verify=``` it results in a segmentation fault.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 11 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp]: done.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 10 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp]: any thoughts on this?

Comment (tbaederr) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp]: I guess that's fine then.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 9 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp]: Considering this as resolved.

**Comment by Sh0g0-1758** [comment]
@asl @tbaederr @AaronBallman, can you please review this PR and merge it if everything seems fine.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td [hunk 12]
```diff
@@ -179,7 +179,7 @@ def err_verify_invalid_no_diags : Error<
     "%select{expected|'expected-no-diagnostics'}0 directive cannot follow "
     "%select{'expected-no-diagnostics' directive|other expected directives}0">;
 def err_verify_no_directives : Error<
-    "no expected directives found: consider use of 'expected-no-diagnostics'">;
+    "no expected directives found: consider use of '%0-no-diagnostics'">;
```
Comment (jrtc27) [inline clang/include/clang/Basic/DiagnosticFrontendKinds.td:182]:
```suggestion
    "no %0 directives found: consider use of '%0-no-diagnostics'">;
```
no?

Comment (jrtc27) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:182]: I guess elsewhere we refer to them as expected diagnostics, it's only in single quotes that we intend it to match the source?

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td [hunk 13]
```diff
@@ -179,7 +179,7 @@ def err_verify_invalid_no_diags : Error<
     "%select{expected|'expected-no-diagnostics'}0 directive cannot follow "
     "%select{'expected-no-diagnostics' directive|other expected directives}0">;
```
Comment (jrtc27) [inline clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: This looks like it needs templating?

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 12 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:182]: this is just some formatting issue. I was following the directions of the original issue, where @tbaederr mentioned changing only the latter expected part of the string.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 13 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: Can you please elaborate on this.

**Comment by Sh0g0-1758** [comment]
gentle ping @reviewers

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 12 above)
Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:182]: > I guess elsewhere we refer to them as expected diagnostics, it's only in single quotes that we intend it to match the source?

Correct, there are expected (English sense of the word) directives, and there are 'expected' (syntax sense of the word) directives. We want single quotes around the syntax part.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 13 above)
Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: I think @jrtc27 is saying that this diagnostic should also change to use `%0` similar to what you've done for `err_verify_no_directives` because it has the same issue with saying `'expected-no-diagnostics'`.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 14]
```diff
@@ -1098,7 +1098,14 @@ void VerifyDiagnosticConsumer::CheckDiagnostics() {
...
     if (Status == HasNoDirectives) {
-      Diags.Report(diag::err_verify_no_directives).setForceEmit();
+      std::string Err_Directive;
+      if (Diags.getDiagnosticOptions().VerifyPrefixes.empty()) {
+        Err_Directive = "expected";
+      } else {
+        Err_Directive = *Diags.getDiagnosticOptions().VerifyPrefixes.begin();
+      }
+      Diags.Report(diag::err_verify_no_directives).setForceEmit()
+          << Err_Directive;
```
Comment (AaronBallman) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1108]:
```suggestion
      std::string ErrDirective;
      if (Diags.getDiagnosticOptions().VerifyPrefixes.empty())
        ErrDirective = "expected";
      else
        ErrDirective = *Diags.getDiagnosticOptions().VerifyPrefixes.begin();
      Diags.Report(diag::err_verify_no_directives).setForceEmit()
          << ErrDirective;
```
We might want to split this logic out into a helper function if we're also updating `err_verify_invalid_no_diags` at the same time.

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! Can you please add more description to what is being fixed and how to the PR summary (as that becomes the commit message when we land the changes)?

I don't think a release note is necessary because this isn't really a user-facing feature (it's a feature for developers of Clang), but the changes should come with some test coverage, probably in `clang/test/Frontend/verify.c` or a new test similar to it.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 13 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: I see, that can be done easily but I think according to LLVM PR standards, its best to limit one PR for one issue. Maybe you can start it as a different issue and then I will submit a PR for the same.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 14 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:1114]: Please let me know if we are doing this also in this PR. I think its best to raise a separate issue for the same as LLVM PR standards imply.

**Comment by Sh0g0-1758** [comment]
Hey @AaronBallman, I have added a test for the same in ```clang/test/Frontend/verify.c``` and made the necessary changes as well. I have added a short **PR SUMMARY** to the top-level comment as you instructed. As for changes in other error messages, I think its best to merge this PR and raise a separate PR for the same.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 12 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:182]: Considering this as resolved.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 13 above)
Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: I think this is the same issue -- in both cases, it's a hard-coded `expected-no-diagnostics` that is incorrect in the presence of a different prefix being used. Because of that, I'd still recommend doing it as part of this PR instead of as a separate one.

Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: Okay, sure thing, I will drop the changes within a few hours then.

Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: @AaronBallman, I don't think it needs templating. After a careful look I believe that the current implementation is for ```-verify``` only. Also the error says ```err_verify_invalid_no_diags``` which implicitly means that we are passing no ```-verify``` diagnostics in the first place. My point being in this case, there are no prefixes being used.

**Comment by Sh0g0-1758** [comment]
gentle ping regarding this  :

> @AaronBallman, I don't think it needs templating. After a careful look I believe that the current implementation is for `-verify` only. Also the error says `err_verify_invalid_no_diags` which implicitly means that we are passing no `-verify` diagnostics in the first place. My point being in this case, there are no prefixes being used.

**Comment by Sh0g0-1758** [comment]
gentle ping. Please check the mergeability of this PR.

**Comment by Endilll** [comment]
> gentle ping. Please check the mergeability of this PR.

Friendly reminder of one ping per week policy.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td (hunk 13 above)
Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: @AaronBallman , please correct me if I am wrong.

Comment (Endilll) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: @Sh0g0-1758 Please have patience and don't ping people more often than once a wekk. Clang is very constrained on reviewer time of experienced people like Aaron.

Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: Ah really sorry about that. Since this was pending for a few days and I wanted to push more PRs for the other issues without making a separate branch and rebasing them, I got a little impatient. Will surely keep this thing in mind from now on.

Comment (Endilll) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: I definitely sympathize with you wanting to push more than one PR at a time, but the way to do it is to follow GitHub flow, specifically a part of it that says you should work in branches, and create your PRs from then: https://docs.github.com/en/get-started/using-github/github-flow#create-a-branch. This way PRs that touch different code can go through as many rounds of review as needed, without blocking other PRs.

Nagging reviewers won't get you anywhere, or even worse, deter reviewers from your PRs.

Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: Yes I understand. I made a beginners mistake of not making a branch for the changes in this PR. Will surely keep that in mind from now on. Also I hope you can overlook my enthu, was not trying to nag any reviewers.

Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td:180]: No worries about the extra pings (we'd rather see people "too" enthusiastic than disengaged!), just something to keep in mind for the future. :-)

The reason I think this diagnostic also needs to be updated is because of: https://godbolt.org/z/sEf4o8YY9 and https://godbolt.org/z/8oMWffoxY where it says `'expected-no-diagnostics'` in the diagnostic message. I think those should also say `'foo-no-diagnostics'` similar to how you've fixed it for the `no expected directives found` warning.

Comment (Sh0g0-1758) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td]: Thanks a lot for looking over it. 

I have made the required changes and added more tests for the same. Please take a look and suggest changes.

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp [hunk 15]
```diff
@@ -396,6 +396,15 @@ class VerifyDiagnosticConsumer::MarkerTracker {
...
 };
 
+std::string DetailedErrorString(DiagnosticsEngine &Diags) {
+  std::string ErrDirective;
+  if (Diags.getDiagnosticOptions().VerifyPrefixes.empty())
+    ErrDirective = "expected";
+  else
+    ErrDirective = *Diags.getDiagnosticOptions().VerifyPrefixes.begin();
+  return ErrDirective;
+}
```
Comment (AaronBallman) [inline clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:406]:
```suggestion
static std::string DetailedErrorString(const DiagnosticsEngine &Diags) {
  if (Diags.getDiagnosticOptions().VerifyPrefixes.empty())
    return "expected";
  return *Diags.getDiagnosticOptions().VerifyPrefixes.begin();
}
```
Some minor changes here but are mostly NFC.

**Review by AaronBallman — COMMENTED** [review]
Thank you, aside from some small suggestions, this LGTM

File: clang/lib/Frontend/VerifyDiagnosticConsumer.cpp (hunk 15 above)
Comment (Sh0g0-1758) [reply clang/lib/Frontend/VerifyDiagnosticConsumer.cpp]: Done

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you!

**Comment by AaronBallman** [comment]
I believe the concerns from @asl and @tbaederr have been addressed and we're fine to land this, but I'll land it tomorrow to give them both a chance to weigh-in and to give precommit CI a chance to finish.
