### PR TITLE
[DirectX] Convert private global variables to internal linkage during Finalize Linkage pass

### LINKED ISSUE #140420: [DirectX] External declaration 'switch.table.*' is unused
Currently seeing 6 errors of this on DML shaders

```bash
lldb -- dxv validation/QLinearConvDp4a7x7x2_QLConvI8_u8u8.dat
error: External declaration 'switch.table.CSMain' is unused
```

## Emited Error DeclNotUsedExternal: 
https://github.com/microsoft/DirectXShaderCompiler/blob/adffd31eb02f690d9d1afe86c7fa6f12b4e70aa1/lib/DxilValidation/DxilValidation.cpp#L3798

## Erroring Instruction

```llvm
(lldb) expr GV->dump()
@switch.table.CSMain = private unnamed_addr constant [4 x i32] [i32 1, i32 257, i32 65793, i32 16843009], align 4
```
If we go beyond this breakpoint we eventually hit this assert:
## Assert in:
https://github.com/microsoft/DirectXShaderCompiler/blob/adffd31eb02f690d9d1afe86c7fa6f12b4e70aa1/lib/IR/Globals.cpp#L210
```cpp
void GlobalVariable::setInitializer(Constant *InitVal) {
  if (!InitVal) {
    if (hasInitializer()) {
      // Note, the num operands is used to compute the offset of the operand, so
      // the order here matters.  Clearing the operand then clearing the num
      // operands ensures we have the correct offset to the operand.
      Op<0>().set(nullptr);
      setGlobalVariableNumOperands(0);
    }
  } else {
    /*line 210 -->*/ assert(InitVal->getType() == getType()->getElementType() &&
           "Initializer type must match GlobalVariable type");
    // Note, the num operands is used to compute the offset of the operand, so
    // the order here matters.  We need to set num operands to 1 first so that
    // we get the correct offset to the first operand when we set it.
    if (!hasInitializer())
      setGlobalVariableNumOperands(1);
    Op<0>().set(InitVal);
  }
}
```

### PR DESCRIPTION
**Pull request by kmpeng**
Fixes #140420. The switch.table.* validation errors were caused by DXIL not supporting private global variables. Converting them to internal linkage fixes the bug.

May need more discussion on the preserved analyses/a follow-up PR that fixes what this pass says it preserves.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp:1]: Are we able to add a test that demonstrates this change?

Comment (kmpeng) [reply llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp:1]: Was also wondering that but I'm not familiar with how that works for these shaders. When I tested it locally the validation succeeded. 

@farzonl is there a way to add a test?

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp:1]: Finn is just asking for you to write a test that confirms we convert private globals to internal. You don’t need to hook up the validator.

File: llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp [hunk 1]
```diff
@@ -18,6 +18,16 @@
...
 
 static bool finalizeLinkage(Module &M) {
+  bool MadeChange = false;
+
+  // Convert private global variables to internal linkage.
+  for (GlobalVariable &GV : M.globals()) {
+    if (GV.hasPrivateLinkage()) {
+      GV.setLinkage(GlobalValue::InternalLinkage);
+      MadeChange = true;
+    }
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp:28]: Should we be removing these if `GV.use_empty()` to match what we do with functions? Alternatively, if we don't expect to ever get here with unused private globals, can we `assert(!GV.use_empty())` here? Or is it okay/expected for us to leave unused internal variables around?

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFinalizeLinkage.cpp:28]: Thats the solution we worked for this ticket https://github.com/llvm/llvm-project/issues/139023. My understanding was though we didn't want to blanket do this because of external linkage.  so, I suppose we could do something like 

```cpp
if(GV.use_empty() && !GV.hasExtenalLinkage())
    ToErase.push_back(&G);
```

**Review by farzonl — APPROVED** [review]
I'm fine with this change. I beleive Justin's concerns can be addressed when we put up a pr for https://github.com/llvm/llvm-project/issues/139023

**Review by bogner — APPROVED** [review]
