### PR TITLE
[profile] Use base+vaddr for `__llvm_write_binary_ids` note pointers

### LINKED ISSUE #114605: SIGSEGV in __llvm_write_binary_ids due to bad NOTE pointers
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2322754

Fedora rawhide has a new version of binutils that ends up splitting NOTEs into separate LOAD segments, and one of those has an extra 0x10000 memory offset, relative to its file offset. This isn't accounted for in `__llvm_write_binary_ids`, and on aarch64 it ends up trying to read *between* segments for a SIGSEGV. I believe the code is wrong regardless of arch though.

Steps to Reproduce:
1. `echo 'int main() {}' >main.c`
2. `clang -fprofile-instr-generate -fcoverage-mapping main.c -o main`
3. `./main`

With the old binutils, we would get `readelf -Wl` like this:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000400040 0x0000000000400040 0x0001f8 0x0001f8 R   0x8
  INTERP         0x00027c 0x000000000040027c 0x000000000040027c 0x00001b 0x00001b R   0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x000000 0x0000000000400000 0x0000000000400000 0x0093b8 0x0093b8 R E 0x10000
  LOAD           0x00fcf8 0x000000000041fcf8 0x000000000041fcf8 0x006510 0x008788 RW  0x10000
  DYNAMIC        0x00fd38 0x000000000041fd38 0x000000000041fd38 0x0001e0 0x0001e0 RW  0x8
  NOTE           0x000238 0x0000000000400238 0x0000000000400238 0x000044 0x000044 R   0x4
  GNU_EH_FRAME   0x0078c4 0x00000000004078c4 0x00000000004078c4 0x000474 0x000474 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
  GNU_RELRO      0x00fcf8 0x000000000041fcf8 0x000000000041fcf8 0x000308 0x000308 R   0x1
```

After the update, the instrumented program crashes in `__llvm_write_binary_ids`. The headers look like:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000400040 0x0000000000400040 0x000230 0x000230 R   0x8
  INTERP         0x000294 0x0000000000400294 0x0000000000400294 0x00001b 0x00001b R   0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x000000 0x0000000000400000 0x0000000000400000 0x0093f8 0x0093f8 R E 0x10000
  LOAD           0x00fcf8 0x000000000041fcf8 0x000000000041fcf8 0x0087a8 0x0087a8 RW  0x10000
  DYNAMIC        0x00fd38 0x000000000041fd38 0x000000000041fd38 0x0001e0 0x0001e0 RW  0x8
  NOTE           0x000270 0x0000000000400270 0x0000000000400270 0x000024 0x000024 R   0x4
  NOTE           0x018480 0x0000000000428480 0x0000000000428480 0x000020 0x000020 R   0x4
  GNU_EH_FRAME   0x007904 0x0000000000407904 0x0000000000407904 0x000474 0x000474 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
  GNU_RELRO      0x00fcf8 0x000000000041fcf8 0x000000000041fcf8 0x000308 0x000308 R   0x1
```

It crashes because the following line computes the second "Note = 0x400000 + 0x018480 = 0x418480", which is between LOAD segments, and the note is actually loaded at `0x428480`.

https://github.com/llvm/llvm-project/blob/f54cdc5d6ee5532da117f2489c105148c94dcb39/compiler-rt/lib/profile/InstrProfilingPlatformLinux.c#L218-L219

That code is in the first branch of an `if-else`, which by comments is intended for inspecting files, while the `else` is for inspecting memory. However, the condition for `memsz == filesz` is met regardless. The other case still wouldn't compute the right address either, because `ElfHeader + vaddr` would double-count the `0x400000` base address. That would probably be right for PIE or SOs though.

https://github.com/llvm/llvm-project/blob/f54cdc5d6ee5532da117f2489c105148c94dcb39/compiler-rt/lib/profile/InstrProfilingPlatformLinux.c#L227-L228

---

I reproduced this using Fedora's clang build, but the code in question hasn't changed since 2021 in commit f261e258ecc0fc5b8e8a70dbe45752d1bb3c2d69.

### PR DESCRIPTION
**Pull request by cuviper**
This function is always examining its own ELF headers in memory, but it
was trying to use conditions between examining files or memory, and it
wasn't accounting for LOAD offsets at runtime. This is especially bad if
a loaded segment has additional padding that's not in the file offsets.

Now we do a first scan of the program headers to figure out the runtime
base address based on `PT_PHDR` and/or `PT_DYNAMIC` (else assume zero),
similar to libc's `do_start`. Then each `PT_NOTE` pointer is simply the
base plus the segments's `pt_vaddr`, which includes LOAD offsets.

Fixes #114605

### CODE REVIEW

File: compiler-rt/lib/profile/InstrProfilingPlatformLinux.c [hunk 1]
```diff
@@ -194,41 +194,33 @@ static int WriteBinaryIds(ProfDataWriter *Writer, const ElfW(Nhdr) * Note,
...
-       * When examining notes in memory, use p_vaddr, which is the address of
-       * section after loaded to memory, to find the start of notes.
-       */
-      Note =
-          (const ElfW(Nhdr) *)((uintptr_t)ElfHeader + ProgramHeader[I].p_vaddr);
-      NotesEnd =
-          (const ElfW(Nhdr) *)((const char *)(Note) + ProgramHeader[I].p_memsz);
-    }
+    const ElfW(Nhdr) *Note =
+        (const ElfW(Nhdr) *)(Base + ProgramHeader[I].p_vaddr);
```
Comment (cuviper) [inline compiler-rt/lib/profile/InstrProfilingPlatformLinux.c:221]: I may need to clarify: this is close to the former `ElfHeader + p_vaddr`, but in the case of non-PIE, the vaddr already includes the fixed base address. The `Base` computation above works either way since it's finding the difference between the runtime address and the header's vaddr, so it's just 0 for non-PIE.

Also, I don't think the code was ever reaching the old `else` case at all. At least in all the files I looked at, `p_filesz` and `p_memsz` were always the same, so we would always be in the "examining notes in file" case.

**Comment by cuviper** [comment]
Pinging for review, please!

**Review by gulfemsavrun — APPROVED** [review]

**Review by david-xl — COMMENTED** [review]
possible to add a test case?

**Comment by cuviper** [comment]
> possible to add a test case?

I'm not sure, but I'll look at the existing binary-id tests and see if I can coerce particular NOTE layouts.

**Comment by cuviper** [comment]
I figured out how to force the error on *any* arch in a test with `-Wl,--section-start`, whereas we were only getting crashes on aarch64 in Fedora rawhide for #114605. The fix does work, with correct build-ids confirmed in the test.

**Review by david-xl — APPROVED** [review]

**Comment by cuviper** [comment]
@gulfemsavrun @david-xl Thank you both for reviews!

I don't have write access to the repo myself, so if you think this is ready, please do merge it.

**Comment by gulfemsavrun** [comment]
> @gulfemsavrun @david-xl Thank you both for reviews!
> 
> I don't have write access to the repo myself, so if you think this is ready, please do merge it.

Ok, I'll merge this for you. Thanks for fixing it.

**Comment by cuviper** [comment]
It seems the section-start trick failed on a couple buildbots:

* https://lab.llvm.org/buildbot/#/builders/145/builds/3327
   > ld.lld: error: output file too large: 18446744073457995232 bytes
  * That's 0xfffffffff1018de0 -- probably a subtraction overflow?

* https://lab.llvm.org/buildbot/#/builders/42/builds/1996
  > /usr/bin/ld: section .interp LMA [0000000001000270,000000000100027e] overlaps section .dynsym LMA [0000000001000150,00000000010004f7]
  * I didn't directly manipulate either of those sections, but I guess the linker still got confused?

**Comment by amy-kwan** [comment]
> It seems the section-start trick failed on a couple buildbots:
> 
> * https://lab.llvm.org/buildbot/#/builders/145/builds/3327
>   > ld.lld: error: output file too large: 18446744073457995232 bytes
>   
>   
>   
>   * That's 0xfffffffff1018de0 -- probably a subtraction overflow?
> * https://lab.llvm.org/buildbot/#/builders/42/builds/1996
>   > /usr/bin/ld: section .interp LMA [0000000001000270,000000000100027e] overlaps section .dynsym LMA [0000000001000150,00000000010004f7]
>   
>   
>   
>   * I didn't directly manipulate either of those sections, but I guess the linker still got confused?

@cuviper The buildbots are still failing for this test case. Could we revert this patch in the mean time so the test case failures can be investigated?

**Comment by cuviper** [comment]
Without write access, I can't revert it myself, but if someone else wants to do that they can. I'll continue looking for a more robust approach either way.

**Comment by cuviper** [comment]
Maybe just the test case can be reverted though? I think the code fix itself is not problematic.

**Comment by maryammo** [comment]
> Maybe just the test case can be reverted though? I think the code fix itself is not problematic.

The failure on [ppc64le bot](https://lab.llvm.org/buildbot/#/builders/145/builds/3327) suggests an overflow which might be a bug in the fix itself, if so then reverting just the test hids the actual problem I think.

**Comment by cuviper** [comment]
@maryammo that's a link error while compiling the test with `--section-start`, not at runtime.

**Comment by cuviper** [comment]
See #117647 for my attempt at improving that test.
