### PR TITLE
Fix crash in install_bad_alloc_error_handler

### LINKED ISSUE #83040: Crash in install_bad_alloc_error_handler
The function `install_bad_alloc_error_handler` asserts that a bad_alloc error handler is not already installed. 
However, it actually checks for the fatal-error handler, not for the bad_alloc error handler, causing an assertion failure if a fatal-error handler is already installed.
Correct behavior would be to only crash if a bad_alloc handler is already installed, making it independent from fatal-error handlers.

Minimal working example: 

```C++
#include <llvm/Support/ErrorHandling.h>

int main() {
    llvm::install_fatal_error_handler([](void*,const char*,bool){});
    llvm::install_bad_alloc_error_handler([](void*,const char*,bool){}); // <-- Crash occurs here
}
```

Propsed Fix:

```Diff
diff --git a/llvm/lib/Support/ErrorHandling.cpp b/llvm/lib/Support/ErrorHandling.cpp
index b8b3b7424ac6..c268543eb1fd 100644
--- a/llvm/lib/Support/ErrorHandling.cpp
+++ b/llvm/lib/Support/ErrorHandling.cpp
@@ -130,7 +130,7 @@ void llvm::install_bad_alloc_error_handler(fatal_error_handler_t handler,
 #if LLVM_ENABLE_THREADS == 1
   std::lock_guard<std::mutex> Lock(BadAllocErrorHandlerMutex);
 #endif
-  assert(!ErrorHandler && "Bad alloc error handler already registered!\n");
+  assert(!BadAllocErrorHandler && "Bad alloc error handler already registered!\n");
   BadAllocErrorHandler = handler;
   BadAllocErrorHandlerUserData = user_data;
 }
```

### PR DESCRIPTION
**Pull request by fabianbs96**
Fixes #83040

### CODE REVIEW

**Comment by aganea** [comment]
Thanks for the PR! Do you think you can craft a minimal unit test (the one provided in the issue)? You could probably add that to one of the Support unit tests.

**Comment by fabianbs96** [comment]
Sure!
Do you have any recommendations on how to best "assert" no crash? It seems weird adding unittests without any assertions inside.

File: llvm/unittests/Support/ErrorTest.cpp [hunk 1]
```diff
@@ -1132,4 +1132,26 @@ TEST(Error, moveInto) {
   }
 }
 
+TEST(Error, FatalBadAllocErrorHandlersInteraction) {
+  auto ErrorHandler = [](void *Data, const char *, bool) {};
+  install_fatal_error_handler(ErrorHandler, nullptr);
+  // The following call should not crash
```
Comment (aganea) [inline llvm/unittests/Support/ErrorTest.cpp:1138]: I think you should expand just a little more your comment, just to explain we're doing this sequence of calls because of a bug that happened previously inside `install_bad_alloc_error_handler`.

File: llvm/unittests/Support/ErrorTest.cpp [hunk 2]
```diff
@@ -1132,4 +1132,26 @@ TEST(Error, moveInto) {
...
+  install_bad_alloc_error_handler(ErrorHandler, nullptr);
+
+  // Don't interfere with other tests:
```
Comment (aganea) [inline llvm/unittests/Support/ErrorTest.cpp:1141]: Remove `:` and finish with a full stop (`.`)

**Review by aganea — COMMENTED** [review]
> Sure! Do you have any recommendations on how to best "assert" no crash? It seems weird adding unittests without any assertions inside.

If you revert locally your fix in `ErrorHandling.cpp` a crash should fail the test. That is enough I think to cover the issue (along with an explanation like suggested below).

**Review by aganea — APPROVED** [review]
LGTM, thanks for making the changes!
