### PR TITLE
[LoopFusion] Validate loop structure before creating LoopCandidates

### LINKED ISSUE #156670: crashes with assertion failure when running opt -passes=loop-fusion
Run opt with -passes=loop-fusion

Reproducer:
https://godbolt.org/z/Ge6dP18WM

Backtrace:
```console
opt: /root/llvm-project/llvm/lib/Transforms/Scalar/LoopFuse.cpp:372: bool {anonymous}::FusionCandidate::reportInvalidCandidate(llvm::Statistic&) const: Assertion `L && Preheader && "Fusion candidate not initialized properly!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -passes=loop-fusion <source>
1.	Running pass "function(loop-fusion)" on module "<source>"
2.	Running pass "loop-fusion" on function "cannot_split"
 #0 0x000000000578f178 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x578f178)
 #1 0x000000000578c024 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000072b1dfa42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000072b1dfa969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x000072b1dfa42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x000072b1dfa287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x000072b1dfa2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x000072b1dfa39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x00000000044db2cc (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x44db2cc)
 #9 0x00000000044e9996 llvm::LoopFusePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x44e9996)
#10 0x0000000002e24e2e llvm::detail::PassModel<llvm::Function, llvm::LoopFusePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2e24e2e)
#11 0x000000000557ad21 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x557ad21)
#12 0x0000000000edbafe llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xedbafe)
#13 0x000000000557928a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x557928a)
#14 0x000000000096caae llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x96caae)
#15 0x0000000005578c41 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x5578c41)
#16 0x0000000000976da8 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x976da8)
#17 0x000000000096ae17 optMain (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x96ae17)
#18 0x000072b1dfa29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#19 0x000072b1dfa29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#20 0x0000000000961f35 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x961f35)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by madhur13490**
This patch adds early check in LoopFuse.cpp to skip loops missing preheader, header, exiting, exit block or latch. Such loop structure is demonstrated when jump tables are used with `indirectbr`. It also makes `reportInvalidCandidate` gracefully return false instead of asserting when Preheader is null. 

In other words this patch skips loops which lack the required structure.

Fixes #156670.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp [hunk 1]
```diff
@@ -363,7 +363,9 @@ struct FusionCandidate {
 
   bool reportInvalidCandidate(Statistic &Stat) const {
     using namespace ore;
-    assert(L && Preheader && "Fusion candidate not initialized properly!");
+    assert(L && "Fusion candidate has null loop!");
+    if (!Preheader)
+      return false;
```
Comment (amehsan) [inline llvm/lib/Transforms/Scalar/LoopFuse.cpp]: This should remain an assert. The assert just tells us that we assume at this point we have a valid loop that has a preheader. If our assumption fails to be correct we want the compiler crash so we know what we missed. In this case the root cause should be fixed and this assert should remain as a checkpoint. 

We are not checking anything here. Checks for preheader should be done elsewhere.

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp [hunk 2]
```diff
@@ -573,6 +575,14 @@ struct LoopFuser {
   /// Flow Equivalent sets, sorted by dominance.
   void collectFusionCandidates(const LoopVector &LV) {
     for (Loop *L : LV) {
+      // Skip loops that do not have the structure required for fusion (e.g.
+      // loops with indirectbr may lack a preheader). Creating a FusionCandidate
+      // for such loops can lead to reportInvalidCandidate being called with
+      // a null Preheader.
+      if (!L->getLoopPreheader() || !L->getHeader() || !L->getExitingBlock() ||
+          !L->getExitBlock() || !L->getLoopLatch())
+        continue;
```
Comment (amehsan) [inline llvm/lib/Transforms/Scalar/LoopFuse.cpp]: can we have a loop with no header? Loops in LLVM are natural loops, so they must have a header IIUC.

**Review by amehsan — COMMENTED** [review]
I need to check one more thing, but I leave a couple of comments for now.

**Comment by CongzheUalberta** [comment]
I think you should call `isLoopSimplifyForm()` to check if the loop is in simplified form. The pass already does it but you probably need to move that piece of code to before or at the beginning of construction of `FusionCandidate`.

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp
Comment (amehsan) [inline llvm/lib/Transforms/Scalar/LoopFuse.cpp:584]: Looks like the check that you want to perform already exists in `isEligibleForFusion`. The problem is that this function calls `reportInvalidCandidate`, which seems to assume some conditions are already met. (In particular preheader exists). 

Don't keep the redundant check if you want to do this checks earlier. You may modify this function to skip updating stats and emitting optimization remarks (and that will fix the problem). Right now loop fusion is very conservative, and stats and remarks for this cases is not really useful. 

Also we call `isLoopSimplifyForm` and `isRotatedForm` inside `isEligibleForFusion`. I suspect some of the earlier checks in the fuction are redundant. But it is OK for me if you don't want address this redundancy in this PR.

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp (hunk 1 above)
Comment (amehsan) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp]: alternatively you can modify this function so that it doesn't need the preheader. Header should always exist, so you can probably use the header for reporting.

**Comment by madhur13490** [comment]
@amehsan @CongzheUalberta In the current revision, I am taking suggestion from @amehsan as to depend on header than preheader as it should exist. The current revision has a new optimization remark, removes assert altogether and depends on header while emitting  the existing remark when STATS is enabled. It seem that the assert is there only to ensure that its access is valid in ORE. But, we can't be sure of preheader always. 

I have tested in release and debug binaries and this is fine. Please let me know if there can a better remark message.

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp
Comment (madhur13490) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp:584]: Please see https://github.com/llvm/llvm-project/pull/192280#issuecomment-4258503045

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp (hunk 2 above)
Comment (madhur13490) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp]: Doesn't seems so. Please see https://github.com/llvm/llvm-project/pull/192280#issuecomment-4258503045

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp (hunk 1 above)
Comment (madhur13490) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp]: addressed here https://github.com/llvm/llvm-project/pull/192280#issuecomment-4258503045

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp [hunk 3]
```diff
@@ -363,12 +363,15 @@ struct FusionCandidate {
...
 #if LLVM_ENABLE_STATS
     ++Stat;
     ORE.emit(OptimizationRemarkAnalysis(DEBUG_TYPE, Stat.getName(),
-                                        L->getStartLoc(), Preheader)
-             << "[" << Preheader->getParent()->getName() << "]: "
+                                        L->getStartLoc(), L->getHeader())
+             << "[" << L->getHeader()->getParent()->getName() << "]: "
              << "Loop is not a candidate for fusion: " << Stat.getDesc());
 #endif
     return false;
```
Comment (amehsan) [inline llvm/lib/Transforms/Scalar/LoopFuse.cpp:377]: LGTM, but I would remove checking `LLVM_ENABLE_STATS` macro and the duplicated opt report inside it.

**Review by amehsan — APPROVED** [review]

File: llvm/lib/Transforms/Scalar/LoopFuse.cpp (hunk 3 above)
Comment (madhur13490) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp:377]: In `ENABLE_STATS_MODE` the remark is printing `Stat.getName()`and `Stat.getDesc` so it is not really a duplicate opt and printing some new information. If we want to get rid of printing stats altogether from this pass, then I believe that is a separate patch.

Comment (amehsan) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp:377]: Yeah, I noticed the difference. No I didn't mean getting rid of printing stats, but if you look elsewhere in the code (I mean other passes):

1-`ENABLE_STATS_MODE` is not checked for incrementing statistics variables.
2- I don't think we print stats as part of optimization remarks. Stats have their own report, and optimization remarks serve another purpose.

We do want to have stats, but some clean up is needed. They are not managed very well in loop fusion. But if you prefer to merge this and follow up with another patch that is fine. We can do it as well if you are busy.

Comment (madhur13490) [reply llvm/lib/Transforms/Scalar/LoopFuse.cpp:377]: I prefer to merge the patch in its current state and take the cleanup as a follow-up as time permits. It will be better to have separate discussion.
