### PR TITLE
[Clang] Distinguish expanding-packs-in-place cases for SubstTemplateTypeParmTypes

### LINKED ISSUE #113518: clangd crashes when deducing template arguments
```cpp
#include <array>
#include <iostream>

template<typename T>
struct ArrayType {
    template<size_t size>
    using Array = std::array<T, size>;
};

template<ArrayType<int>::Array array>
void test() {
    for (const auto& item : array) {
        std::cout << item << std::endl;
    }
}

void foo() {
    test<{1,2,3}>();
}
```

<details>
<summary>It crashes clangd.</summary>

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	/home/openvscode-server/latte/source/bug.hpp:18:19: current parser token ')'
1.	/home/openvscode-server/latte/source/bug.hpp:17:12: parsing function body 'foo'
2.	/home/openvscode-server/latte/source/bug.hpp:17:12: in compound statement ('{}')
I[03:30:27.300] ut symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.so.19.1      0x00007f1b8c46512f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 63
1  libLLVM.so.19.1      0x00007f1b8c462e39 llvm::sys::RunSignalHandlers() + 89
2  libLLVM.so.19.1      0x00007f1b8c465880
3  libc.so.6            0x00007f1b8a6c9250
4  libclang-cpp.so.19.1 0x00007f1b94430402 clang::TypeLoc::getLocalAlignmentForType(clang::QualType) + 34
5  libclang-cpp.so.19.1 0x00007f1b94430485 clang::TypeLoc::getFullDataSizeForType(clang::QualType) + 101
6  libclang-cpp.so.19.1 0x00007f1b95005834 clang::TypeLocBuilder::pushTrivial(clang::ASTContext&, clang::QualType, clang::SourceLocation) + 68
7  libclang-cpp.so.19.1 0x00007f1b94f67653
8  libclang-cpp.so.19.1 0x00007f1b94f6734f
9  libclang-cpp.so.19.1 0x00007f1b94f1f71f
10 libclang-cpp.so.19.1 0x00007f1b94f266ab
11 libclang-cpp.so.19.1 0x00007f1b94f5f9a4
12 libclang-cpp.so.19.1 0x00007f1b94f5f2e1
13 libclang-cpp.so.19.1 0x00007f1b94f28716
14 libclang-cpp.so.19.1 0x00007f1b94f565d9
15 libclang-cpp.so.19.1 0x00007f1b94f26732
16 libclang-cpp.so.19.1 0x00007f1b94f5fa46
17 libclang-cpp.so.19.1 0x00007f1b94f5f2e1
18 libclang-cpp.so.19.1 0x00007f1b94f28716
19 libclang-cpp.so.19.1 0x00007f1b94f565d9
20 libclang-cpp.so.19.1 0x00007f1b94f26732
21 libclang-cpp.so.19.1 0x00007f1b94f5f9a4
22 libclang-cpp.so.19.1 0x00007f1b94f66916
23 libclang-cpp.so.19.1 0x00007f1b94f63e48
24 libclang-cpp.so.19.1 0x00007f1b94f1f71f
25 libclang-cpp.so.19.1 0x00007f1b94f266ab
26 libclang-cpp.so.19.1 0x00007f1b94f2652d clang::Sema::SubstTemplateArgument(clang::TemplateArgumentLoc const&, clang::MultiLevelTemplateArgumentList const&, clang::TemplateArgumentLoc&, clang::SourceLocation, clang::DeclarationName const&) + 77
27 libclang-cpp.so.19.1 0x00007f1b94de5599
28 libclang-cpp.so.19.1 0x00007f1b94de5125 clang::Sema::SubstDefaultTemplateArgumentIfAvailable(clang::TemplateDecl*, clang::SourceLocation, clang::SourceLocation, clang::Decl*, llvm::ArrayRef<clang::TemplateArgument>, llvm::ArrayRef<clang::TemplateArgument>, bool&) + 405
29 libclang-cpp.so.19.1 0x00007f1b94e6dc14 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) + 1924
30 libclang-cpp.so.19.1 0x00007f1b94ecb657
31 libclang-cpp.so.19.1 0x00007f1b947042a0 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) + 64
32 libclang-cpp.so.19.1 0x00007f1b94e6fba0 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) + 2912
33 libclang-cpp.so.19.1 0x00007f1b94d51906 clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) + 774
34 libclang-cpp.so.19.1 0x00007f1b94c23699
35 libclang-cpp.so.19.1 0x00007f1b94c169b4
36 libclang-cpp.so.19.1 0x00007f1b94c15ea4 clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) + 1780
37 libclang-cpp.so.19.1 0x00007f1b94de7018 clang::Sema::CheckTemplateArgument(clang::NonTypeTemplateParmDecl*, clang::QualType, clang::Expr*, clang::TemplateArgument&, clang::TemplateArgument&, clang::Sema::CheckTemplateArgumentKind) + 520
38 libclang-cpp.so.19.1 0x00007f1b94de6651 clang::Sema::CheckTemplateArgument(clang::NamedDecl*, clang::TemplateArgumentLoc&, clang::NamedDecl*, clang::SourceLocation, clI[03:30:27.300] Built preamble of size 0 for file /home/openvscode-server/latte/source/Tokenizer.hpp version 123 in ang::SourceLocation, unsigned int, llvm::SmallVectorImpl<clang::TemplateArgument>&, llvm::SmallVectorImpl<clang::TemplateArgument>&, clang::Sema::CheckTemplateArgumentKind) + 2113
0.78 seconds
39 libclang-cpp.so.19.1 0x00007f1b94ddb908 clang::Sema::CheckTemplateArgumentList(clang::TemplateDecl*, clang::SourceLocation, clang::TemplateArgumentListInfo&, bool, llvm::SmallVectorImpl<clang::TemplateArgument>&, llvm::SmallVectorImpl<clang::TemplateArgument>&, bool, bool*, bool) + 1256
I[03:30:27.300] --> workspace/semanticTokens/refresh(1)
I[03:30:27.300] --> textDocument/clangd.fileStatus
40 libclang-cpp.so.19.1 0x00007f1b94e6c736 clang::Sema::SubstituteExplicitTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo&, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, llvm::SmallVectorImpl<clang::QualType>&, clang::QualType*, clang::sema::TemplateDeductionInfo&) + 374
I[03:30:27.301] <-- reply(1)
41 libclang-cpp.so.19.1 0x00007f1b94ecb5b7
42 libclang-cpp.so.19.1 0x00007f1b947042a0 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) + 64
43 libclang-cpp.so.19.1 0x00007f1b94e6f2e1 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) + 673
44 libclang-cpp.so.19.1 0x00007f1b94d51906 clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) + 774
45 libclang-cpp.so.19.1 0x00007f1b94d61e5d
46 libclang-cpp.so.19.1 0x00007f1b94d61d1e clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) + 318
I[03:30:27.302] BeginSourceFile() failed when building AST for /home/openvscode-server/latte/source/Tokenizer.hpp
I[03:30:27.302] --> textDocument/publishDiagnostics
I[03:30:27.302] --> textDocument/clangd.fileStatus
47 libclang-cpp.so.19.1 0x00007f1b94d6207c clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) + 156
48 libclang-cpp.so.19.1 0x00007f1b94d6237d clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 365
49 libclang-cpp.so.19.1 0x00007f1b94a032a7 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) + 1527
50 libclang-cpp.so.19.1 0x00007f1b94a173c1 clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) + 81
51 libclang-cpp.so.19.1 0x00007f1b93dcbd8f clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) + 5439
52 libclang-cpp.so.19.1 0x00007f1b93dcd4bc clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) + 1900
53 libclang-cpp.so.19.1 0x00007f1b93dc8cbf clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) + 287
54 libclang-cpp.so.19.1 0x00007f1b93dc8b82 clang::Parser::ParseExpression(clang::Parser::TypeCastState) + 18
55 libclang-cpp.so.19.1 0x00007f1b93e31f29 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) + 73
56 libclang-cpp.so.19.1 0x00007f1b93e3012d clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) + 1085
57 libclang-cpp.so.19.1 0x00007f1b93e2faa6 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) + 358
58 libclang-cpp.so.19.1 0x00007f1b93e38972 clang::Parser::ParseCompoundStatementBody(bool) + 1650
59 libclang-cpp.so.19.1 0x00007f1b93e39aaa clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) + 186
60 libclang-cpp.so.19.1 0x00007f1b93e541d1 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) + 3889
61 libclang-cpp.so.19.1 0x00007f1b93d94547 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) + 6279
62 libclang-cpp.so.19.1 0x00007f1b93e530fd clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) + 1133
63 libclang-cpp.so.19.1 0x00007f1b93e52a65 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) + 565
64 libclang-cpp.so.19.1 0x00007f1b93e51c24 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) + 2164
65 libclang-cpp.so.19.1 0x00007f1b93e4ffb8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) + 1592
66 libclang-cpp.so.19.1 0x00007f1b93d7c4be clang::ParseAST(clang::Sema&, bool, bool) + 814
67 libclang-cpp.so.19.1 0x00007f1b95ecda0c clang::FrontendAction::Execute() + 92
68 clangd-19            0x00005576b322c533
69 clangd-19            0x00005576b32c7479
70 clangd-19            0x00005576b32c6eda
71 clangd-19            0x00005576b32c3680
72 clangd-19            0x00005576b32c31db
73 clangd-19            0x00005576b342c5d1
74 libc.so.6            0x00007f1b8a725e2e
75 libc.so.6            0x00007f1b8a7b7834 __clone + 68
Signalled during AST worker action: Build AST
  Filename: bug.hpp
  Directory: /home/openvscode-server/latte/source
  Command Line: /usr/lib/llvm-19/bin/clang++ --driver-mode=g++ -std=c++23 -stdlib=libc++ -resource-dir=/usr/lib/llvm-19/lib/clang/19 -- /home/openvscode-server/latte/source/bug.hpp
  Version: 62
[Error - 3:30:27 AM] The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
</details>

### PR DESCRIPTION
**Pull request by zyn0217**
In 50e5411e4, we preserved the pack substitution index within SubstTemplateTypeParmType nodes and performed in-place expansions of packs such that type constraints on a lambda that serve as a pattern of a fold expression could be evaluated if the type constraints contain any packs that are expanded by the fold expression.

However, we made an incorrect assumption of the condition under which in-place expansion should occur. For example, a SizeOfPackExpr case relies on SubstTemplateTypeParmType nodes being transformed to SubstTemplateTypeParmPackTypes rather than expanding them immediately in place.

This fixes that by adding a flag to SubstTemplateTypeParmType to discriminate such in-place expansion situations.

Fixes https://github.com/llvm/llvm-project/issues/113518

### CODE REVIEW

File: clang/include/clang/AST/Type.h [hunk 1]
```diff
@@ -6393,7 +6396,8 @@ class SubstTemplateTypeParmType final
   Decl *AssociatedDecl;
 
   SubstTemplateTypeParmType(QualType Replacement, Decl *AssociatedDecl,
-                            unsigned Index, std::optional<unsigned> PackIndex);
+                            unsigned Index, std::optional<unsigned> PackIndex,
+                            bool ExpandPacksInPlace);
```
Comment (erichkeane) [inline clang/include/clang/AST/Type.h:6400]: I of course have a preference for this to be a scoped enum instead of a bool.

**Review by erichkeane — COMMENTED** [review]
Seems reasonable to me, 1 nit, but I'd like the others to have a chacne to review anyway.

File: clang/lib/AST/Type.cpp [hunk 2]
```diff
@@ -4205,6 +4205,7 @@ SubstTemplateTypeParmType::SubstTemplateTypeParmType(
 
   SubstTemplateTypeParmTypeBits.Index = Index;
   SubstTemplateTypeParmTypeBits.PackIndex = PackIndex ? *PackIndex + 1 : 0;
+  SubstTemplateTypeParmTypeBits.ExpandPacksInPlace = ExpandPacksInPlace;
```
Comment (mizvekov) [inline clang/lib/AST/Type.cpp:4208]: ExpandPacksInPlace should only ever be true if there is a PackIndex. Can we enforce that here, and other places which are relevant, like profiling?

**Review by mizvekov — APPROVED** [review]
LGTM with small nit, thanks!

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 3]
```diff
@@ -3149,9 +3156,15 @@ struct ExpandPackedTypeConstraints
 
     assert(SemaRef.ArgumentPackSubstitutionIndex != -1);
 
+    TemplateArgument Arg = TemplateArgs(T->getDepth(), T->getIndex());
+
+    std::optional<unsigned> PackIndex;
+    if (Arg.getKind() == TemplateArgument::Pack)
+      PackIndex = Arg.pack_size() - 1 - SemaRef.ArgumentPackSubstitutionIndex;
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:3163]: Can't we use `getPackIndex` here:

https://github.com/zyn0217/llvm-project/blob/734f00daf65c079c63c8c338122c02ce56130df6/clang/lib/Sema/SemaTemplateInstantiate.cpp#L1385-L1390

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3163]: These index transformations also come up in other places, where some other index is used, instead of the current Sema pack subst index. That would be worth refactoring, also consolidating asserts.
