### PR TITLE
[lldb] Fix type lookup in DWARF .o files via debug map

### LINKED ISSUE #87176: SymbolFileDWARFDebugMap::FindTypes only finds types defined in the first compile unit
The early-exit condition inside `SymbolFileDWARFDebugMap::FindTypes ` is inverted:

```cpp
void SymbolFileDWARFDebugMap::FindTypes(const TypeQuery &query,
                                        TypeResults &results) {
  std::lock_guard<std::recursive_mutex> guard(GetModuleMutex());
  ForEachSymbolFile([&](SymbolFileDWARF *oso_dwarf) -> bool {
    oso_dwarf->FindTypes(query, results);
    return !results.Done(query); // Keep iterating if we aren't done.
  });
}
```

`ForEachSymbolFile` stops iterating when the closure returns `true`. As a result, type queries only consider the first compile unit in a module.

### PR DESCRIPTION
**Pull request by pabusse**
An inverted condition causes `SymbolFileDWARFDebugMap::FindTypes` to bail out after inspecting the first .o file in each module.

The same kind of bug is found in `SymbolFileDWARFDebugMap::ParseDeclsForContext`.

Correct both early exit conditions and add a regression test for lookup of up a type defined in a secondary compilation unit.

Fixes #87176

### CODE REVIEW

**Comment by marcauberer** [comment]
@pabusse Hi, thanks for the patch!
Please remove the semicolons from the python code to make the formatting check pass.

**Comment by Michael137** [comment]
Thanks for the patch, sounds like it should fix https://github.com/llvm/llvm-project/issues/86184

**Review by Michael137 — APPROVED** [review]

**Review by marcauberer — APPROVED** [review]

File: lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp [hunk 1]
```diff
@@ -1391,7 +1391,7 @@ void SymbolFileDWARFDebugMap::ParseDeclsForContext(
     lldb_private::CompilerDeclContext decl_ctx) {
   ForEachSymbolFile([&](SymbolFileDWARF *oso_dwarf) -> bool {
     oso_dwarf->ParseDeclsForContext(decl_ctx);
-    return true; // Keep iterating
+    return false; // Keep iterating
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp:1394]: Outside the scope of this patch, but note that `ParseDeclsForContext` isn't actually doing anything specific to the object file. Calling it multiple times for the same `decl_ctx` happens to be a no-op, but this doesn't feel like something that should be on `SymbolFile`.
