### PR TITLE
[Clang][analyzer] replace Stmt* with ConstCFGElementRef in SymbolConjured

### LINKED ISSUE #57270: [analyzer] Crash using `clang_analyzer_explain()` in the `debug.ExprInspection` checker
The following snippet causes the Static Analyzer to fail an assertion in debug mode, or crash in release mode.

```c++
struct S {
    static int a;
    ~S(){};
};
int S::a = 0;

void foo() {
    S::a = 0;

    int x = 3;
    memset(&x, 1, sizeof(x));

    S *arr = new S[x];
    delete[] arr;

    clang_analyzer_explain(S::a);
}
```

`memset` sets the value of `S::a` to `derived_$12{conj_$8{int, LC1, no stmt, #1},a}`, and later when `clang_analyzer_explain()` tries to explain the value, it encounters a `nullptr` which it dereferences.

`conj_$8{int, LC1, no stmt, #1}` doesn't contain any statement, so when `SValExplainer::VisitSymbolConjured()` calls `SValExplainer::printStmt(const Stmt *S)` it passes a `nullptr` to it as an argument. The called function assumes it always receives a valid pointer, and it simply calls `S->printPretty()` without any validation, and this is when the crash happens.

For more information please see [godbolt](https://godbolt.org/z/hMYcs8f8z).

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Closes #57270.

This PR changes the `Stmt *` field in `SymbolConjured` with `CFGBlock::ConstCFGElementRef`. The motivation is that, when conjuring a symbol, there might not always be a statement available, causing information to be lost for conjured symbols, whereas the CFGElementRef can always be provided at the callsite.

Following the idea, this PR changes callsites of functions to create conjured symbols, and replaces them with appropriate `CFGElementRef`s.

### CODE REVIEW

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h [hunk 1]
```diff
@@ -171,20 +172,27 @@ class SValBuilder {
...
+    return SymMgr.conjureSymbol(ElemRef, LCtx, type, visitCount, symbolTag);
   }
 
-  const SymbolConjured* conjureSymbol(const Expr *expr,
-                                      const LocationContext *LCtx,
-                                      unsigned visitCount,
-                                      const void *symbolTag = nullptr) {
-    return SymMgr.conjureSymbol(expr, LCtx, visitCount, symbolTag);
-  }
+  // const SymbolConjured* conjureSymbol(const Stmt *stmt,
```
Comment (fangyi-zhou) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:182]: Will remove these commented out lines before marking this PR as ready.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 2]
```diff
@@ -113,19 +120,21 @@ class SymbolConjured : public SymbolData {
...
   void dumpToStream(raw_ostream &os) const override;
 
-  static void Profile(llvm::FoldingSetNodeID &profile, const Stmt *S,
+  static void Profile(llvm::FoldingSetNodeID &profile,
+                      const CFGBlock::ConstCFGElementRef ElemRef,
                       const LocationContext *LCtx, QualType T, unsigned Count,
                       const void *SymbolTag) {
     profile.AddInteger((unsigned)SymbolConjuredKind);
-    profile.AddPointer(S);
+    // profile.Add(ElemRef);
```
Comment (fangyi-zhou) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:128]: Q: Do I need to add `ElemRef` to the profile?

File: clang/lib/StaticAnalyzer/Core/RegionStore.cpp [hunk 3]
```diff
@@ -1376,8 +1379,8 @@ StoreRef RegionStoreManager::invalidateRegions(
   }
 
   RegionBindingsRef B = getRegionBindings(store);
-  InvalidateRegionsWorker W(*this, StateMgr, B, S, Count, LCtx, IS, ITraits,
-                            Invalidated, GlobalsFilter);
+  InvalidateRegionsWorker W(*this, StateMgr, B, Call->getCFGElementRef(), Count,
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/RegionStore.cpp:1382]: Q: Here `Call` is possibly null, how should I get a ref here?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h (hunk 2 above)
Comment (isuckatcs) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:128]: Yes

**Comment by isuckatcs** [comment]
The source of the crash you mentioned in the issue is `CStringChecker.cpp:1304`, where the `CallEvent` is a `nullptr`.
```c++
return State->invalidateRegions(R, E, C.blockCount(), LCtx,
                                CausesPointerEscape, nullptr, nullptr,
                                &ITraits);
```

File: clang/lib/StaticAnalyzer/Core/RegionStore.cpp (hunk 3 above)
Comment (isuckatcs) [reply clang/lib/StaticAnalyzer/Core/RegionStore.cpp:1382]: Here we initially passed `const Stmt *S` to the worker, so we should pass the `CFGElementRef` of `const Stmt *S` and not what we obtain from the call, I guess.

As for that, you can pass it down from the only callsite of this function, as you have access to the engine.
```c++
ProgramStateRef ProgramState::invalidateRegions(
  ...
  ExprEngine &Eng = Mgr.getOwningEngine()
  ...
  const StoreRef &NewStore = Mgr.StoreMgr->invalidateRegions(
      getStore(), Values, Eng.getCFGElementRef(), Count, LCtx, Call, *IS,
      *ITraits, &TopLevelInvalidated, &Invalidated);
  ...
}
```

I don't know if that's a reference that we want here, but with trial and error we will see.

File: clang/lib/StaticAnalyzer/Core/SymbolManager.cpp [hunk 4]
```diff
@@ -82,7 +82,7 @@ void UnarySymExpr::dumpToStream(raw_ostream &os) const {
 
 void SymbolConjured::dumpToStream(raw_ostream &os) const {
   os << getKindStr() << getSymbolID() << '{' << T << ", LC" << LCtx->getID();
-  if (S)
+  if (const auto *S = getStmt())
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Core/SymbolManager.cpp:85]: Here we might actually want to dump the `CFGElementRef` not the statement.

**Review by isuckatcs — CHANGES_REQUESTED** [review]
So far we have some progress, so keep it up.

Keep in mind that we'll also need to update `SValExplainer`, but you'll see it once you run the tests and start seeing the warning messages.

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 5]
```diff
@@ -111,8 +111,13 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
   }
 
   std::string VisitSymbolConjured(const SymbolConjured *S) {
-    return "symbol of type '" + S->getType().getAsString() +
-           "' conjured at statement '" + printStmt(S->getStmt()) + "'";
+    std::string Str;
+    llvm::raw_string_ostream OS(Str);
+    OS << "symbol of type '" + S->getType().getAsString() +
+              "' conjured at statement '";
+    S->getCFGElementRef()->dumpToStream(OS);
```
Comment (fangyi-zhou) [inline clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:118]: Q: Do we have a way to pretty print a CFGElementRef instead of `dumpToStream`?

File: clang/lib/StaticAnalyzer/Core/SValBuilder.cpp [hunk 6]
```diff
@@ -151,72 +151,63 @@ SValBuilder::getRegionValueSymbolVal(const TypedValueRegion *region) {
...
-
-  // Compute the type of the result. If the expression is not an R-value, the
-  // result should be a location.
-  QualType ExType = Ex->getType();
-  if (Ex->isGLValue())
-    T = LCtx->getAnalysisDeclContext()->getASTContext().getPointerType(ExType);
-
-  return conjureSymbolVal(SymbolTag, Ex, LCtx, T, Count);
-}
+// DefinedOrUnknownSVal SValBuilder::conjureSymbolVal(const void *SymbolTag,
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:154]: Note to self: This should probably be added back in some shape or form since it has some different behaviour when handling expressions with a provided type --- which means it's not entirely same to calling `conjureSymbolVal(SymbolTag, Ex, LCtx, Ex->getType(), Count)`. Probably need to revisit all callsites and check.

**Comment by fangyi-zhou** [comment]
I've made some more progress, the crash goes away, there are still some review comments that I need to address, which I'll try to complete later.

```
/home/fangyi/playground/bug.cc:21:5: warning: value derived from (symbol of type 'int' conjured at statement '->~S() (Implicit destructor)
') for global variable 'S::a' [debug.ExprInspection]
   21 |     clang_analyzer_explain(S::a);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h (hunk 5 above)
Comment (isuckatcs) [reply clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:118]: I don't know about any. You could create a similar helper to `printStmt()` in this class though.

Comment (isuckatcs) [reply clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:120]: Yes, but you can extract the "dumping to an ostream" logic into a separate function and tweak it there however you want. This is what I ment by similar to `printStmt()`.

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 7]
```diff
@@ -113,8 +113,18 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
...
+    // HACK: dumpToStream will output a new line in the end, this is
+    // undesireable, thus we remove it.
+    if (Str.back() == '\n') {
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:123]: What if we are on windows and the line ending is `\r\n`?

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 8]
```diff
@@ -113,8 +113,18 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
...
+      Str.pop_back();
+    }
+    OS << "'";
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:126]:
```suggestion
    OS << '\'';
```

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h [hunk 9]
```diff
@@ -151,6 +151,11 @@ class CheckerContext {
     return Pred->getSVal(S);
   }
 
+  /// Get the CFG Element Ref from the ExprEngine
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h:154]: I think you can remove this comment. It's obvious what the function does even without it.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h [hunk 10]
```diff
@@ -171,19 +172,11 @@ class SValBuilder {
...
-    return SymMgr.conjureSymbol(stmt, LCtx, type, visitCount, symbolTag);
-  }
-
-  const SymbolConjured* conjureSymbol(const Expr *expr,
-                                      const LocationContext *LCtx,
-                                      unsigned visitCount,
-                                      const void *symbolTag = nullptr) {
-    return SymMgr.conjureSymbol(expr, LCtx, visitCount, symbolTag);
+  const SymbolConjured *
+  conjureSymbol(const CFGBlock::ConstCFGElementRef ElemRef,
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:176]: Here we had an overload without a `QualType`, don't we need it?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h [hunk 11]
```diff
@@ -198,32 +191,24 @@ class SValBuilder {
...
-  DefinedOrUnknownSVal conjureSymbolVal(const void *symbolTag, const Stmt *S,
-                                        const LocationContext *LCtx,
-                                        QualType type, unsigned count);
-  DefinedOrUnknownSVal conjureSymbolVal(const Stmt *stmt,
-                                        const LocationContext *LCtx,
-                                        QualType type,
-                                        unsigned visitCount);
+  DefinedOrUnknownSVal
+  conjureSymbolVal(const void *symbolTag, const Expr *expr,
+                   const CFGBlock::ConstCFGElementRef elemRef,
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:196]: Why do we need both a `const Expr *` and a `const CFGBlock::ConstCFGElementRef`? I'd imagine, the `ConstCFGElementRef` points to the `Expr`.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h [hunk 12]
```diff
@@ -198,32 +191,24 @@ class SValBuilder {
...
-
-  /// Conjure a symbol representing heap allocated memory region.
-  ///
-  /// Note, now, the expression *doesn't* need to represent a location.
-  /// But the type need to!
-  DefinedSVal getConjuredHeapSymbolVal(const Expr *E,
-                                       const LocationContext *LCtx,
-                                       QualType type, unsigned Count);
+  DefinedSVal
+  getConjuredHeapSymbolVal(const CFGBlock::ConstCFGElementRef elemRef,
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:209]: The overload without a `QualType` is missing. Why did we remove it?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 13]
```diff
@@ -80,17 +81,18 @@ class SymbolRegionValue : public SymbolData {
...
-  SymbolConjured(SymbolID sym, const Stmt *s, const LocationContext *lctx,
-                 QualType t, unsigned count, const void *symbolTag)
-      : SymbolData(SymbolConjuredKind, sym), S(s), T(t), Count(count),
-        LCtx(lctx), SymbolTag(symbolTag) {
+  SymbolConjured(SymbolID sym, CFGBlock::ConstCFGElementRef elemRef,
+                 const LocationContext *lctx, QualType t, unsigned count,
+                 const void *symbolTag)
+      : SymbolData(SymbolConjuredKind, sym), ElemRef(elemRef), T(t),
+        Count(count), LCtx(lctx), SymbolTag(symbolTag) {
     // FIXME: 's' might be a nullptr if we're conducting invalidation
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:96]: This FIXME is no longer valid, because a `ConstCFGElementRef` is never a `nullptr`, IIUC.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 14]
```diff
@@ -533,18 +538,12 @@ class SymbolManager {
...
   const SymExprT *acquire(Args &&...args);
 
-  const SymbolConjured *conjureSymbol(const Stmt *E,
-                                      const LocationContext *LCtx, QualType T,
-                                      unsigned VisitCount,
-                                      const void *SymbolTag = nullptr) {
-    return acquire<SymbolConjured>(E, LCtx, T, VisitCount, SymbolTag);
-  }
+  const SymbolConjured *
+  conjureSymbol(const CFGBlock::ConstCFGElementRef ElemRef,
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:542]: An overload without a type is missing.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 15]
```diff
@@ -1299,8 +1299,8 @@ ProgramStateRef CStringChecker::invalidateBufferAux(
     RegionAndSymbolInvalidationTraits ITraits;
     bool CausesPointerEscape = InvalidationTraitOperations(ITraits, R);
 
-    return State->invalidateRegions(R, E, C.blockCount(), LCtx,
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1302]: This change makes `E` an unused parameter.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 16]
```diff
@@ -1515,7 +1515,8 @@ void CStringChecker::evalCopyCommon(CheckerContext &C, const CallEvent &Call,
       // conjure a return value for later.
       if (lastElement.isUnknown())
         lastElement = C.getSValBuilder().conjureSymbolVal(
-            nullptr, Call.getOriginExpr(), LCtx, C.blockCount());
+            nullptr, Call.getOriginExpr(), C.getCFGElementRef(), LCtx,
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1518]: At this point, isn't it the `Call` that conjured the symbol? Shouldn't we pass a `CFGElementRef` to the `Call` instead?

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 17]
```diff
@@ -1665,8 +1666,9 @@ void CStringChecker::evalMemcmp(CheckerContext &C, const CallEvent &Call,
     State = CheckBufferAccess(C, State, Left, Size, AccessKind::read, CK);
     if (State) {
       // The return value is the comparison result, which we don't know.
-      SVal CmpV = Builder.conjureSymbolVal(nullptr, Call.getOriginExpr(), LCtx,
-                                           C.blockCount());
+      SVal CmpV =
+          Builder.conjureSymbolVal(nullptr, Call.getOriginExpr(),
+                                   C.getCFGElementRef(), LCtx, C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1671]: Same here

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 18]
```diff
@@ -1770,7 +1772,8 @@ void CStringChecker::evalstrLengthCommon(CheckerContext &C,
       // All we know is the return value is the min of the string length
       // and the limit. This is better than nothing.
       result = C.getSValBuilder().conjureSymbolVal(
-          nullptr, Call.getOriginExpr(), LCtx, C.blockCount());
+          nullptr, Call.getOriginExpr(), C.getCFGElementRef(), LCtx,
+          C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1776]: And here.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 19]
```diff
@@ -1794,7 +1797,8 @@ void CStringChecker::evalstrLengthCommon(CheckerContext &C,
     // value, so it can be used in constraints, at least.
     if (result.isUnknown()) {
       result = C.getSValBuilder().conjureSymbolVal(
-          nullptr, Call.getOriginExpr(), LCtx, C.blockCount());
+          nullptr, Call.getOriginExpr(), C.getCFGElementRef(), LCtx,
+          C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1801]: .

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 20]
```diff
@@ -2261,7 +2265,8 @@ void CStringChecker::evalStrcpyCommon(CheckerContext &C, const CallEvent &Call,
     // If this is a stpcpy-style copy, but we were unable to check for a buffer
     // overflow, we still need a result. Conjure a return value.
     if (ReturnEnd && Result.isUnknown()) {
-      Result = svalBuilder.conjureSymbolVal(nullptr, Call.getOriginExpr(), LCtx,
+      Result = svalBuilder.conjureSymbolVal(nullptr, Call.getOriginExpr(),
+                                            C.getCFGElementRef(), LCtx,
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2269]: .

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 21]
```diff
@@ -2361,8 +2366,9 @@ void CStringChecker::evalStrcmpCommon(CheckerContext &C, const CallEvent &Call,
   const StringLiteral *RightStrLiteral =
       getCStringLiteral(C, state, Right.Expression, RightVal);
   bool canComputeResult = false;
-  SVal resultVal = svalBuilder.conjureSymbolVal(nullptr, Call.getOriginExpr(),
-                                                LCtx, C.blockCount());
+  SVal resultVal =
+      svalBuilder.conjureSymbolVal(nullptr, Call.getOriginExpr(),
+                                   C.getCFGElementRef(), LCtx, C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2371]: .

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 22]
```diff
@@ -2469,14 +2475,14 @@ void CStringChecker::evalStrsep(CheckerContext &C,
...
+                       SVB.conjureSymbolVal(getTag(), C.getCFGElementRef(),
                                             LCtx, CharPtrTy, C.blockCount()),
                        LCtx);
   } else {
     assert(SearchStrVal.isUnknown());
     // Conjure a symbolic value. It's the best we can do.
-    Result = SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(), LCtx,
-                                  C.blockCount());
+    Result = SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(),
+                                  C.getCFGElementRef(), LCtx, C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2485]: .

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 23]
```diff
@@ -2469,14 +2475,14 @@ void CStringChecker::evalStrsep(CheckerContext &C,
     // further along in the same string, or NULL if there are no more tokens.
     State =
         State->bindLoc(*SearchStrLoc,
-                       SVB.conjureSymbolVal(getTag(), Call.getOriginExpr(),
+                       SVB.conjureSymbolVal(getTag(), C.getCFGElementRef(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2478]: .

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 24]
```diff
@@ -2520,7 +2526,8 @@ void CStringChecker::evalStdCopyCommon(CheckerContext &C,
   SValBuilder &SVB = C.getSValBuilder();
 
   SVal ResultVal =
-      SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(), LCtx, C.blockCount());
+      SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(), C.getCFGElementRef(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2529]: .

File: clang/lib/StaticAnalyzer/Checkers/ContainerModeling.cpp [hunk 25]
```diff
@@ -326,7 +330,7 @@ void ContainerModeling::handleAssignment(CheckerContext &C, SVal Cont,
           auto &SVB = C.getSValBuilder();
           // Then generate and assign a new "end" symbol for the new container.
           auto NewEndSym =
-              SymMgr.conjureSymbol(CE, C.getLocationContext(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/ContainerModeling.cpp:329]: This makes `CE` an unused parameter.

File: clang/lib/StaticAnalyzer/Checkers/ErrnoModeling.cpp [hunk 26]
```diff
@@ -260,7 +260,7 @@ ProgramStateRef setErrnoStdMustBeChecked(ProgramStateRef State,
   const MemRegion *ErrnoR = State->get<ErrnoRegion>();
   if (!ErrnoR)
     return State;
-  State = State->invalidateRegions(ErrnoR, InvalE, C.blockCount(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/ErrnoModeling.cpp:263]: `InvalE` is an unused parameter, the element reference should point to that I think.

File: clang/lib/StaticAnalyzer/Checkers/ErrnoTesterChecker.cpp [hunk 27]
```diff
@@ -130,8 +130,9 @@ void ErrnoTesterChecker::evalSetErrnoIfErrorRange(CheckerContext &C,
 
   ProgramStateRef StateFailure = State->BindExpr(
       Call.getOriginExpr(), C.getLocationContext(), SVB.makeIntVal(1, true));
-  DefinedOrUnknownSVal ErrnoVal = SVB.conjureSymbolVal(
-      nullptr, Call.getOriginExpr(), C.getLocationContext(), C.blockCount());
+  DefinedOrUnknownSVal ErrnoVal =
+      SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(), C.getCFGElementRef(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/ErrnoTesterChecker.cpp:134]: Same as multiple previous question about the call.

File: clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp [hunk 28]
```diff
@@ -467,7 +467,7 @@ void IteratorModeling::handleComparison(CheckerContext &C, const Expr *CE,
   SymbolRef Sym;
   if (!LPos || !RPos) {
     auto &SymMgr = C.getSymbolManager();
-    Sym = SymMgr.conjureSymbol(CE, C.getLocationContext(),
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp:470]: `CE` is unused parameter.

File: clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp [hunk 29]
```diff
@@ -494,7 +494,7 @@ void IteratorModeling::handleComparison(CheckerContext &C, const Expr *CE,
     auto &SymMgr = C.getSymbolManager();
     auto *LCtx = C.getLocationContext();
     RetVal = nonloc::SymbolVal(SymMgr.conjureSymbol(
-        CE, LCtx, C.getASTContext().BoolTy, C.blockCount()));
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp:497]: .

File: clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp [hunk 30]
```diff
@@ -688,7 +688,8 @@ void IteratorModeling::assignToContainer(CheckerContext &C, const Expr *CE,
 
   auto State = C.getState();
   const auto *LCtx = C.getLocationContext();
-  State = createIteratorPosition(State, RetVal, Cont, CE, LCtx, C.blockCount());
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp:691]: .

File: clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp [hunk 31]
```diff
@@ -229,7 +230,7 @@ DefinedSVal makeRetVal(CheckerContext &C, const CallExpr *CE) {
 
   const LocationContext *LCtx = C.getLocationContext();
   return C.getSValBuilder()
-      .conjureSymbolVal(nullptr, CE, LCtx, C.blockCount())
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp:232]: `CE` in unused.

**Review by isuckatcs — CHANGES_REQUESTED** [review]
I didn't have enough time to check the whole patch, I'll get back to it later.

The general patterns seems to be that when a conjured symbol is created, it's always the reference to the current CFG element that is passed as the source statement instead of some other statement that was passed in the past. 

I think every place, where we conjure a symbol should be double checked, so that we make sure we pass the CFG element reference to the correct statement, that actually conjured the value.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h (hunk 11 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:196]: If you look at the implementation code, there's some special treatment wrt the type of the expression

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h (hunk 12 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:209]: Same as above.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h (hunk 14 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:542]: Same as above.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp (hunk 16 above)
Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1518]: I don't know what's the correct one to pass and don't have a way to check reliably since I don't understand the static analysis code. I don't understand your intention in this comment, do you mean I should pass the CFGElementRef to the Call or not?

File: clang/lib/StaticAnalyzer/Core/RegionStore.cpp (hunk 3 above)
Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Core/RegionStore.cpp]: Are you referring to this instance that I should pass the refernece to the statement instead of the call? I think I misunderstood this comment so I changed the references to not use the one from the call in all places.

File: clang/lib/StaticAnalyzer/Core/SValBuilder.cpp [hunk 32]
```diff
@@ -166,57 +166,47 @@ DefinedOrUnknownSVal SValBuilder::conjureSymbolVal(const void *SymbolTag,
...
-  SymbolRef sym = SymMgr.conjureSymbol(stmt, LCtx, type, visitCount);
+  SymbolRef sym = SymMgr.conjureSymbol(elemRef, LCtx, type, visitCount);
 
   if (Loc::isLocType(type))
     return loc::MemRegionVal(MemMgr.getSymbolicRegion(sym));
 
   return nonloc::SymbolVal(sym);
 }
 
-DefinedSVal SValBuilder::getConjuredHeapSymbolVal(const Expr *E,
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:209]: This overload is removed since it's not possible to retrieve the type from the CFGElementRef. If there's a way to obtain it please let me know so I can add it back.

File: clang/lib/StaticAnalyzer/Core/SValBuilder.cpp [hunk 33]
```diff
@@ -151,10 +151,10 @@ SValBuilder::getRegionValueSymbolVal(const TypedValueRegion *region) {
   return nonloc::SymbolVal(sym);
 }
 
-DefinedOrUnknownSVal SValBuilder::conjureSymbolVal(const void *SymbolTag,
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:154]: This overload would have been removed, but its behaviour is not entirely the same as obtaining the type from the expression directly. (See the check for `isGLValue`). Without complicating the refactor in this PR I decided to leave it as is, and add a new parameter for the CFG Element Ref

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/LoopWidening.h [hunk 34]
```diff
@@ -27,7 +27,8 @@ namespace ento {
 /// by the loop body in any iteration.
 ProgramStateRef getWidenedLoopState(ProgramStateRef PrevState,
                                     const LocationContext *LCtx,
-                                    unsigned BlockCount, const Stmt *LoopStmt);
+                                    unsigned BlockCount, const Stmt *LoopStmt,
```
Comment (Xazax-hun) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/LoopWidening.h:30]: Do we need both the Stmt and the ElemRef here?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h [hunk 35]
```diff
@@ -101,8 +103,10 @@ class SymbolConjured : public SymbolData {
   }
 
 public:
-  /// It might return null.
-  const Stmt *getStmt() const { return S; }
```
Comment (Xazax-hun) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h:105]: Would it make sense to keep `getStmt`? It could still return null but some callers might find it useful.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp (hunk 16 above)
Comment (Xazax-hun) [reply clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:1518]: You can dump the CFGElementRef and the expr. We want to make sure they match, so there is no semantic change. That is one way to check if the code is correct.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h (hunk 10 above)
Comment (Xazax-hun) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:176]: Could we still extract a type from the `ElemRef` in the implementation? Does the caller have a reasonable type to pass in when `ElemRef` is not referring to an expression?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/LoopWidening.h (hunk 34 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/LoopWidening.h:30]: Not any more, will remove.

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h (hunk 10 above)
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h:176]: We can try to downcast the `ElemRef` for a statement, and try to downcast as an expression to obtain the type in those cases. I guess it would work in the callsites in the deleted overload if the `ElemRef` are statements.

File: clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp [hunk 36]
```diff
@@ -494,7 +494,7 @@ void IteratorModeling::handleComparison(CheckerContext &C, const Expr *CE,
     auto &SymMgr = C.getSymbolManager();
     auto *LCtx = C.getLocationContext();
     RetVal = nonloc::SymbolVal(SymMgr.conjureSymbol(
-        CE, LCtx, C.getASTContext().BoolTy, C.blockCount()));
+        C.getCFGElementRef(), LCtx, C.getASTContext().BoolTy, C.blockCount()));
     State = State->BindExpr(CE, LCtx, RetVal);
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Checkers/IteratorModeling.cpp:498]: Used here.

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 37]
```diff
@@ -29,6 +31,18 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
   ASTContext &ACtx;
   ProgramStateRef State;
 
+  std::string printCFGElementRef(const CFGBlock::ConstCFGElementRef ElemRef) {
+    std::string Str;
+    llvm::raw_string_ostream OS(Str);
+    ElemRef->dumpToStream(OS);
+    // HACK: `CFGBlock::ConstCFGElementRef::dumpToStream` contains a new line
+    // character in the end of the string, we don't want it so we remove it here.
+    while (!Str.empty() && std::isspace(Str.back())) {
```
Comment (isuckatcs) [inline clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:40]: `std::isspace` is dependant on the local, so I would advise against using it.

Also don't we have a builtin `trim()` function in LLVM, which can be used here?

File: clang/lib/StaticAnalyzer/Core/SValBuilder.cpp [hunk 38]
```diff
@@ -151,10 +153,13 @@ SValBuilder::getRegionValueSymbolVal(const TypedValueRegion *region) {
...
-                                                   const Expr *Ex,
-                                                   const LocationContext *LCtx,
-                                                   unsigned Count) {
+/// When using this overload, the \p elemRef provided must be a \p CFGStmt.
```
Comment (isuckatcs) [inline clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:156]: This is asserted. The comment is not necessary I think.

**Review by isuckatcs — CHANGES_REQUESTED** [review]
Can you please add a testcase with the snippetin the issue that used to crash?

File: clang/include/clang/Analysis/CFG.h [hunk 39]
```diff
@@ -695,6 +695,21 @@ class CFGBlock {
     void dump() const {
       dumpToStream(llvm::errs());
     }
+
+    void Profile(llvm::FoldingSetNodeID &ID) const {
+      ID.AddPointer(Parent);
+      ID.AddInteger(Index);
+    }
+
+    int64_t getID() const {
```
[the remark this answers is not in the document]
Comment (fangyi-zhou) [reply clang/include/clang/Analysis/CFG.h:704]: Any suggestion for replacement?

[the remark this answers is not in the document]
Comment (isuckatcs) [reply clang/include/clang/Analysis/CFG.h:704]: Why do we want to print the ID in the first place? It probably doesn't hold a value to our users anyway.

Either print a stament if there is any, or a source location, etc. The CFG is essentially the statements in the source file in execution order, so I imagine we always have a statement.

**Comment by fangyi-zhou** [comment]
May I get a re-review for the changes please?

**Review by steakhal — CHANGES_REQUESTED** [review]
I've only spotchecked. It looks correct at first glance.
I somewhat dislike that practically every file needs to include CFG.h; I'd advise revisiting this.

Do you intentionally take `CFGBlock::ConstCFGElementRef` as a const parameter? That doesn't seem to do anything. I'd rather not spell `const` unless there is a compelling reason to do so.

Then the final question, why is `ConstCFGElementRef` nested under the `CFGBlock`? It makes it spell every time, leading to noise. I'd revisit this, and possibly change its implementation to allow less mouthful spelling of this type.

**Comment by fangyi-zhou** [comment]
Sorry I've been a bit busy with other things, just had some time to address the review comments. Please let me know if anything else needs changing

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 40]
```diff
@@ -29,6 +32,17 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
   ASTContext &ACtx;
   ProgramStateRef State;
 
+  std::string printCFGElementRef(CFGBlock::ConstCFGElementRef ElemRef) {
```
Comment (steakhal) [inline clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:35]: Having the `CFGBlock::ConstCFGElementRef` qualified name spelled every time could get messy really quick.
I didn't count how many times this is spelled throughout the PR, but it's gotta be a lot.

I've just checked that forward declaring is not really an option, and hoisting could be also quite a bit of work. However, we could at least have a type alias to avoid the `CFGBlock::` being spelled out every time.

Could you put `using ConstCFGElementRef = CFGBlock::ConstCFGElementRef;` after the definition of `CFGBlock`?

File: clang/include/clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h [hunk 41]
```diff
@@ -313,7 +313,8 @@ class ProgramState : public llvm::FoldingSetNode {
   /// be triggered by this event.
   ///
   /// \param Regions the set of regions to be invalidated.
-  /// \param E the expression that caused the invalidation.
+  /// \param ElemRef \p CFGBlock::ConstCFGElementRef that caused the
```
Comment (steakhal) [inline clang/include/clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h:316]:
```suggestion
  /// \param ElemRef The CFG element that caused the
```

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 42]
```diff
@@ -273,36 +273,41 @@ class CStringChecker : public Checker< eval::Call,
   /// Invalidate the destination buffer determined by characters copied.
   static ProgramStateRef
   invalidateDestinationBufferBySize(CheckerContext &C, ProgramStateRef S,
-                                    const Expr *BufE, SVal BufV, SVal SizeV,
-                                    QualType SizeTy);
+                                    const Expr *BufE,
+                                    CFGBlock::ConstCFGElementRef ElemRef,
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:277]: In all of these examples, I feel that `ElemRef` is too verbose. `Elem` or `Place` should be a shorter name without compromising readability. Also, like I previously suggested, not having to spell out the `CFGBlock::` would be a huge help here too.

File: clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp [hunk 43]
```diff
@@ -2463,19 +2473,19 @@ void CStringChecker::evalStrsep(CheckerContext &C,
...
+                       SVB.conjureSymbolVal(getTag(), Call.getCFGElementRef(),
                                             LCtx, CharPtrTy, C.blockCount()),
                        LCtx);
   } else {
     assert(SearchStrVal.isUnknown());
     // Conjure a symbolic value. It's the best we can do.
-    Result = SVB.conjureSymbolVal(nullptr, Call.getOriginExpr(), LCtx,
+    Result = SVB.conjureSymbolVal(nullptr, Call.getCFGElementRef(), LCtx,
                                   C.blockCount());
   }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp:2490]: I think it's such a common pattern that we want to conjure at a call, that we should have a shorthand for it.
Conjure takes a bunch of obscured parameters and it's annoying to dig them up every time.
The "Call" should already have most stuff, thus we could have the opportunity to simplify the API for Calls.
It could be done later though. I just leave this for food for though.

File: clang/lib/StaticAnalyzer/Checkers/ErrnoModeling.h [hunk 44]
```diff
@@ -13,6 +13,7 @@
 #ifndef LLVM_CLANG_LIB_STATICANALYZER_CHECKERS_ERRNOMODELING_H
 #define LLVM_CLANG_LIB_STATICANALYZER_CHECKERS_ERRNOMODELING_H
 
+#include "clang/Analysis/CFG.h"
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/ErrnoModeling.h:16]: Actually, if we only declare an API that uses a class as a by-value parameter, that doesn't need the definition of the class.

File: clang/lib/StaticAnalyzer/Checkers/STLAlgorithmModeling.cpp [hunk 45]
```diff
@@ -97,11 +99,12 @@ bool STLAlgorithmModeling::evalCall(const CallEvent &Call,
   if (!Handler)
     return false;
 
-  return (this->**Handler)(C, CE);
+  return (this->**Handler)(C, CE, Call.getCFGElementRef());
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/STLAlgorithmModeling.cpp:102]: Ideally, here we would pass the `Call` instead of `CE`. Then the handlers could dig up the Elem if they need that using the `Call.getCFGElementRef()`. I'd prefer this over what we propose here right now unless there is some compelling argument doing it this way.

File: clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp [hunk 46]
```diff
@@ -645,6 +645,7 @@ struct StreamOperationEvaluator {
   SymbolRef StreamSym = nullptr;
   const StreamState *SS = nullptr;
   const CallExpr *CE = nullptr;
+  std::optional<CFGBlock::ConstCFGElementRef> ElemRef;
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp:648]: Why is this declared here and not where the later assignment is?
As a rule of thumb, we should keep the lifetimes of objects as small as possible, and have their definitions as close to their uses as possible to enhance local reasoning.
Why do we need this optional anyway if we unconditionally unwrap it later?

File: clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp [hunk 47]
```diff
@@ -21,18 +21,19 @@ using namespace ento;
 using llvm::APSInt;
 
 /// Optionally conjure and return a symbol for offset when processing
-/// an expression \p Expression.
+/// a \p CFGElementRef.
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp:24]: ˙\p` should refer to a parameter name in the declaration. Consequently, this should be probably `ElemRef` currently.
But ideally, something like `Elem` or `Place` should be a better fit in general.

File: clang/lib/StaticAnalyzer/Core/LoopWidening.cpp [hunk 48]
```diff
@@ -93,9 +76,8 @@ ProgramStateRef getWidenedLoopState(ProgramStateRef PrevState,
                      RegionAndSymbolInvalidationTraits::TK_PreserveContents);
   }
 
-  return PrevState->invalidateRegions(Regions, getLoopCondition(LoopStmt),
-                                      BlockCount, LCtx, true, nullptr, nullptr,
-                                      &ITraits);
+  return PrevState->invalidateRegions(Regions, ElemRef, BlockCount, LCtx, true,
```
[the remark this answers is not in the document]
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/LoopWidening.cpp:78]: I mean if it did so far, we didn't change the behavior, the assertion inside should still hold. Am I missing something?
That said, I wish we could keep the assertion within `getWidenedLoopState`.

File: clang/lib/StaticAnalyzer/Core/SValBuilder.cpp (hunk 38 above)
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:155]: I agree, let's drop this line.
```suggestion
```

**Review by steakhal — CHANGES_REQUESTED** [review]
Looks almost perfect. Thank you.
I've added a couple of comments, and suggestions.
There were a couple of suggestions that were not solved or commented why was disregarded since the last review. I'd suggest having a thorough look and reply to every unresolved conversations to make sure we all align on the directions.

I think we are pretty close to completion, WDYT @isuckatcs?

**Comment by fangyi-zhou** [comment]
Thanks for the review. I might have missed some comments since I was away from this pull request for quite a while and I probably forgot. I'll have another revision.

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h [hunk 49]
```diff
@@ -114,7 +128,8 @@ class SValExplainer : public FullSValVisitor<SValExplainer, std::string> {
 
   std::string VisitSymbolConjured(const SymbolConjured *S) {
     return "symbol of type '" + S->getType().getAsString() +
-           "' conjured at statement '" + printStmt(S->getStmt()) + "'";
+           "' conjured at statement '" +
```
[the remark this answers is not in the document]
Comment (fangyi-zhou) [reply clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:131]: My intention was to keep this is as for now to avoid making visible changes (i.e. the emitted diagnostics). If it's desirable to change this to a CFG Element, I can make the required change (although that would include changing some test cases)

File: clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp (hunk 46 above)
Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp:648]: I'm not entirely sure whether I get your point correctly. This value needs to be stored when `Init` is called, and used in other calls (e.g. `bindReturnValue`). The reason why this is declared as an optional is that there is no default constructor for `ConstCFGElementRef`, so I used an optional to give an absent value (I guess it could have been a pointer like other ones)

File: clang/lib/StaticAnalyzer/Core/LoopWidening.cpp (hunk 48 above)
[the remark this answers is not in the document]
Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Core/LoopWidening.cpp:78]: I don't have a good answer to these questions... Any tips? I don't see any immediate ways to extract the required information

File: clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h (hunk 49 above)
[the remark this answers is not in the document]
Comment (steakhal) [reply clang/include/clang/StaticAnalyzer/Checkers/SValExplainer.h:131]: Please do. These are only used in tests, and not in production.

File: clang/lib/StaticAnalyzer/Core/LoopWidening.cpp (hunk 48 above)
[the remark this answers is not in the document]
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/LoopWidening.cpp:78]: @isuckatcs

File: clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp (hunk 46 above)
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp:648]: Ah I completely missed the context. nvm.

File: clang/lib/StaticAnalyzer/Core/ExprEngine.cpp [hunk 50]
```diff
@@ -2556,10 +2556,19 @@ void ExprEngine::processCFGBlockEntrance(const BlockEdge &L,
     const Stmt *Term = nodeBuilder.getContext().getBlock()->getTerminatorStmt();
     if (!isa_and_nonnull<ForStmt, WhileStmt, DoStmt, CXXForRangeStmt>(Term))
       return;
+
+    // FIXME:
```
Comment (fangyi-zhou) [inline clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2560]: Please have a look at this workaround. I've noticed that, after adding back the assertion, the CFG element from the `ExprEngine` was incorrect. Therefore this workaround is put in place as a replacement for the terminator.

Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2560]: Now thinking about this, and looking at the assertion within `getWidenedLoopState` we don't actually need to assert that the wrapped Stmt is a loop statement. As for correctness, it might be surprising to hear but it also doesn't really matter what CFGElement we would pass, the important part to pass something, and do so deterministically.

So if it makes the code simpler, we can drop the assertion inside, and even pass the wrong CFGElement here.
Would it make the patch simpler?

Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2560]: Fair enough, I will remove the assertion but leave this FIXME here for future reference.

**Review by steakhal — APPROVED** [review]

**Comment by fangyi-zhou** [comment]
Looks like there's an Asan issue at the stale CFG element for loop widening https://lab.llvm.org/buildbot/#/builders/55/builds/10398. Do we need to revert?

**Comment by steakhal** [comment]
@fangyi-zhou Could you please check what's wrong?
PS: I reverted this patch for now.

File: clang/lib/StaticAnalyzer/Core/ExprEngine.cpp (hunk 50 above)
Comment (fangyi-zhou) [reply clang/lib/StaticAnalyzer/Core/ExprEngine.cpp:2563]: I suspect we need to actually provide a valid CFG element here, so maybe we need to pass the first element in the new CFG Block?
