### PR TITLE
[DAG] Enable bitcast STLF for Constant/Undef

### LINKED ISSUE #151683: [DAG] ForwardStoreValueToDirectLoad - failure to peek through non-matching load types
ForwardStoreValueToDirectLoad can peek through a load of a store of a constant to use the constant directly:
```ll
define float @test_stlf(ptr %p, float %v) {
  store float zeroinitializer, ptr %p, align 4
  %f = load float, ptr %p, align 4
  %r = fmul fast float %f, %v
  ret float %r
}
```

```asm
test_stlf: # @test_stlf
  movl $0, (%rdi)
  xorps %xmm0, %xmm0
  retq
```

But if we are storing a different type (typically due to load combining etc.) then the forwarding fails:

```ll
define float @test_stlf_integer(ptr %p, float %v) {
  store i32 zeroinitializer, ptr %p, align 4
  %f = load float, ptr %p, align 4
  %r = fmul fast float %f, %v
  ret float %r
}
define float @test_stlf_vector(ptr %p, float %v) {
  store <4 x float> zeroinitializer, ptr %p, align 4
  %f = load float, ptr %p, align 4
  %r = fmul fast float %f, %v
  ret float %r
}
define float @test_stlf_bitcast(ptr %p, float %v) {
  store <2 x i64> zeroinitializer, ptr %p, align 4
  %f = load float, ptr %p, align 4
  %r = fmul fast float %f, %v
  ret float %r
}
```
```asm
test_stlf_integer: # @test_stlf_integer
  movl $0, (%rdi)
  mulss (%rdi), %xmm0
  retq
test_stlf_vector: # @test_stlf_vector
  xorps %xmm1, %xmm1
  movups %xmm1, (%rdi)
  mulss (%rdi), %xmm0
  retq
test_stlf_bitcast: # @test_stlf_bitcast
  xorps %xmm1, %xmm1
  movups %xmm1, (%rdi)
  mulss (%rdi), %xmm0
  retq
```

### PR DESCRIPTION
**Pull request by Michael-Chen-NJU**
This patch introduces support for Store-to-Load Forwarding (STLF) in `DAGCombiner::ForwardStoreValueToDirectLoad` when the store and load have **different types but equal memory size** (e.g., storing an `i32` then loading a `float` from the same location).

### What this patch does:
 **Enables Optimization:** It allows for the safe forwarding of the stored value as a Bitcast when the value is:
    * A **Constant** (`ConstantSDNode`, `ConstantFPSDNode`, `ConstantPoolSDNode`).
    * **Undef**.
    * And the memory sizes (`LdMemSize` == `StMemSize`) match.

### Scope and Next Steps:

This patch **only implements forwarding for constant and undef values that has the same memory size** so far.

**I am submitting this initial patch to get early review feedback on the core logic and fix the immediate crashes before tackling the more complex scenarios.**

For the simple case:
```llvm
; Case Handled by this PR so far (e.g., zeroinitializer is a constant)
define float @test_stlf_integer(ptr %p, float %v) {
  store i32 0, ptr %p, align 4 
  %f = load float, ptr %p, align 4 
  ; ...
}
```
Fixes: #151683

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -20478,8 +20478,18 @@ SDValue DAGCombiner::ForwardStoreValueToDirectLoad(LoadSDNode *LD) {
       break;
     if (STMemType != LDMemType) {
       // TODO: Support vectors? This requires extract_subvector/bitcast.
-      if (!STMemType.isVector() && !LDMemType.isVector() &&
-          STMemType.isInteger() && LDMemType.isInteger())
+      if (LdMemSize == StMemSize) {
+        bool IsConstantOrUndef = isa<ConstantSDNode>(Val) ||
+                                 isa<ConstantFPSDNode>(Val) ||
+                                 isa<ConstantPoolSDNode>(Val) || Val.isUndef();
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: Should be using one of the other isConstant helpers instead of inventing a new sequence. I also doubt the ConstantPool case would ever occur here

File: llvm/test/CodeGen/X86/dag-stlf-mismatch.ll [hunk 2]
```diff
@@ -0,0 +1,43 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
+; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s
+
+target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
```
Comment (arsenm) [inline llvm/test/CodeGen/X86/dag-stlf-mismatch.ll]:
```suggestion
```

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 3]
```diff
@@ -20478,8 +20478,18 @@ SDValue DAGCombiner::ForwardStoreValueToDirectLoad(LoadSDNode *LD) {
...
-      if (!STMemType.isVector() && !LDMemType.isVector() &&
-          STMemType.isInteger() && LDMemType.isInteger())
+      if (LdMemSize == StMemSize) {
+        bool IsConstantOrUndef =
+            Val.isUndef() || DAG.isConstantIntBuildVectorOrConstantInt(Val) ||
+            DAG.isConstantFPBuildVectorOrConstantFP(Val);
+
+        if (IsConstantOrUndef && isTypeLegal(Val.getValueType()) &&
+            TLI.isOperationLegalOrCustom(ISD::BITCAST, LDMemType))
+          Val = DAG.getBitcast(LDMemType, Val);
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: I'd generally expect this bitcast to constant fold. The other branches in this function don't seem to concern themselves with the legality of the casts. Is this combine only run on the pre-legalized dag?

File: llvm/test/CodeGen/X86/dag-stlf-mismatch.ll [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+; CHECK-NEXT:    movl $0, (%rdi)
+; CHECK-NEXT:    movl $0, (%rsp)
+; CHECK-NEXT:    callq ext_func@PLT
+; CHECK-NEXT:    popq %rax
+; CHECK-NEXT:    .cfi_def_cfa_offset 8
+; CHECK-NEXT:    retq
+  store i32 0, ptr %ptr, align 4
+  call void @ext_func(ptr byval(%struct.Data) align 4 %ptr)
+  ret void
+}
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/dag-stlf-mismatch.ll]: missing newline at EOF

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 3 above)
Comment (Michael-Chen-NJU) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: I've verified that without this check,the test `CodeGen/AMDGPU/build_vector-r600.ll` crashes with `Unexpected illegal type`!.
I've investigated the crash with the test case (using `-mtriple=r600-- -mcpu=redwood`) and confirmed that the `isTypeLegal(STMemType)` is indeed necessary.In this specific path, we have a constant value with STMemType = v2i16 and LDMemType = i32. Even though the operand is a constant, DAG.getBitcast(i32, <2 x i16> Constant) **fails to constant fold** because v2i16 is an illegal type on this targe.

As shown in the backtrace, the crash occurs during the Legalization phase (SelectionDAGLegalize::LegalizeOp).

Adding isTypeLegal(STMemType) ensures that we only attempt this optimization when the bitcast is guaranteed to be valid for the target's current legalization state.

**Review by RKSimon — CHANGES_REQUESTED** [review]

**Review by arsenm — APPROVED** [review]

**Comment by KennethHilmersson** [comment]
Thanks, that sounds good!
