### PR TITLE
[clang] Fixes inf loop parsing fixed point literal

### LINKED ISSUE #83050: [clang] clang hangs when instantiate an array of fixed points.
clang hangs with:
```
static constexpr unsigned short _Fract A[][] = { 0x1.0p-1uhr, ... };
```
https://godbolt.org/z/rcfe6qa4b

### PR DESCRIPTION
**Pull request by PiJoules**
Clang was incorrectly finding the start of the exponent in a fixed point hex literal. It would unconditionally find the first `e/E/p/P` in a constant regardless of if it were hex or not and parser the remaining digits as an APInt. In a debug build, this would be caught by an assertion, but in a release build, the assertion is removed and we'd end up in an infinite loop.

Fixes #83050

### CODE REVIEW

**Review by lntue — APPROVED** [review]

File: clang/test/Frontend/GH83050.cpp [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/// This is the regression test for https://github.com/llvm/llvm-project/issues/83050.
+/// This just needs to compile.
+// RUN: %clang_cc1 -x c++ -ffixed-point -S %s -o /dev/null -triple=x86_64-linux -ffixed-point
+static constexpr unsigned short _Fract SQRT_FIRST_APPROX[12][2] = {
+    {0x1.e8p-1uhr, 0x1.0cp-2uhr}, {0x1.bap-1uhr, 0x1.28p-2uhr},
+    {0x1.94p-1uhr, 0x1.44p-2uhr}, {0x1.74p-1uhr, 0x1.6p-2uhr},
+    {0x1.6p-1uhr, 0x1.74p-2uhr},  {0x1.4ep-1uhr, 0x1.88p-2uhr},
+    {0x1.3ep-1uhr, 0x1.9cp-2uhr}, {0x1.32p-1uhr, 0x1.acp-2uhr},
+    {0x1.22p-1uhr, 0x1.c4p-2uhr}, {0x1.18p-1uhr, 0x1.d4p-2uhr},
+    {0x1.08p-1uhr, 0x1.fp-2uhr},  {0x1.04p-1uhr, 0x1.f8p-2uhr},
```
Comment (nickdesaulniers) [inline clang/test/Frontend/GH83050.cpp:10]: Also, do we need the full list of constants to expose this issue? I would have expected one such literal to expose this.

Comment (PiJoules) [reply clang/test/Frontend/GH83050.cpp:10]: Right, we don't need the whole list since it's only ones with an `e` before the exponent that trigger this. I copied this since the original godbolt reproducer had it, but we can just have the first element to reproduce.

**Comment by nickdesaulniers** [comment]
For the commit message and PR description, please consider:
1. using a subject that describes more of what the patch does, such as "[clang] fixes inf loop parsing fixed point literal"
2. put "Fixes #83050" in the commit body; when merged, github will auto close the corresponding issue.

File: clang/test/Frontend/GH83050.cpp (hunk 1 above)
Comment (nickdesaulniers) [reply clang/test/Frontend/GH83050.cpp]: I think what you added to clang/test/Frontend/fixed_point_declarations.c covers the same thing as the newly added test file? Are both necessary?

Comment (PiJoules) [reply clang/test/Frontend/GH83050.cpp]: Oh, no they both aren't so I'll just remove this one.

**Review by nickdesaulniers — APPROVED** [review]
