### PR TITLE
[ARM] Use TargetMachine over Subtarget in ARMAsmPrinter

### LINKED ISSUE #165422: llc crashes while compiling code for arm
llc crashes while trying to compile the attached file ([ghc_ll.txt](https://github.com/user-attachments/files/23192059/ghc_ll.txt)) with the following traceback:

```
Command line: _build/stage0/bin/ghc -Wall -Wcompat -fdiagnostics-color=never -hisuf p_hi -osuf p_o -hcsuf p_hc -static -prof -hide-all-packages -no-user-package-db '-package-env -' '-package-db _build/stage1/inplace/package.conf.d' '-this-unit-id ghc-bignum-1.3-34fd' '-this-package-name ghc-bignum' '-package-id ghc-prim-0.12.0-57da' -i -i/build/reproducible-path/ghc-9.10.3/_build/stage1/libraries/ghc-bignum/build -i/build/reproducible-path/ghc-9.10.3/_build/stage1/libraries/ghc-bignum/build/autogen -i/build/reproducible-path/ghc-9.10.3/libraries/ghc-bignum/src/ -Irts/include -I_build/stage1/libraries/ghc-bignum/build -I_build/stage1/libraries/ghc-bignum/build/include/ -Ilibraries/ghc-bignum/include/ -I/build/reproducible-path/ghc-9.10.3/rts/include -I/build/reproducible-path/ghc-9.10.3/_build/stage1/rts/build/include -optP-include -optP_build/stage1/libraries/ghc-bignum/build/autogen/cabal_macros.h -optc-marm -optP-DBIGNUM_GMP -outputdir _build/stage1/libraries/ghc-bignum/build -Wall -this-unit-id ghc-bignum -fno-catch-nonexhaustive-cases -XHaskell2010 -no-global-package-db -package-db=/build/reproducible-path/ghc-9.10.3/_build/stage1/inplace/package.conf.d -ghcversion-file=rts/include/ghcversion.h -ghcversion-file=rts/include/ghcversion.h -Wnoncanonical-monad-instances -optc-Wno-error=inline -c libraries/ghc-bignum/src/GHC/Num/Backend/Selected.hs -o _build/stage1/libraries/ghc-bignum/build/GHC/Num/Backend/Selected.p_o -fsplit-sections -O -H64m -O2 -haddock -D__ARM_PCS_VFP -Wno-deprecated-flags
===> Command failed with error code: 1
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: llc-19 -O2 -relocation-model=pic -mcpu=arm1176jzf-s -mattr=+strict-align /tmp/ghc57961_0/ghc_7.bc -o /tmp/ghc57961_0/ghc_8.lm_s
 #0 0xf14585f4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0xf1455ff4 llvm::sys::RunSignalHandlers() build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Signals.cpp:0:5
 #2 0xf1458ee8 SignalHandler build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:0:3
 #3 0xf078ecd0 __default_sa_restorer ./signal/../sysdeps/unix/sysv/linux/arm/sigrestorer.S:67:0
 #4 0xf3a872ac getObjectFormat build-llvm/tools/clang/stage2-bins/llvm/include/llvm/TargetParser/Triple.h:405:53
 #5 0xf3a872ac isOSBinFormatMachO build-llvm/tools/clang/stage2-bins/llvm/include/llvm/TargetParser/Triple.h:740:12
 #6 0xf3a872ac isTargetMachO build-llvm/tools/clang/stage2-bins/llvm/lib/Target/ARM/ARMSubtarget.h:312:52
 #7 0xf3a872ac GetARMGVSymbol build-llvm/tools/clang/stage2-bins/llvm/lib/Target/ARM/ARMAsmPrinter.cpp:861:18
 #8 0xf3a872ac emitXXStructor build-llvm/tools/clang/stage2-bins/llvm/lib/Target/ARM/ARMAsmPrinter.cpp:93:45
 #9 0xf1d58140 llvm::AsmPrinter::emitXXStructorList(llvm::DataLayout const&, llvm::Constant const*, bool) build-llvm/tools/clang/stage2-bins/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:2970:20
#10 0xf1d4d8ac llvm::AsmPrinter::emitSpecialLLVMGlobal(llvm::GlobalVariable const*) build-llvm/tools/clang/stage2-bins/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:0:0
#11 0xf1d4cd70 llvm::AsmPrinter::emitGlobalVariable(llvm::GlobalVariable const*) build-llvm/tools/clang/stage2-bins/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:710:9
#12 0xf1d5515c llvm::AsmPrinter::doFinalization(llvm::Module&) build-llvm/tools/clang/stage2-bins/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:2297:22
#13 0xf15bf8d0 llvm::FPPassManager::doFinalization(llvm::Module&) build-llvm/tools/clang/stage2-bins/llvm/lib/IR/LegacyPassManager.cpp:1503:55
#14 0xf15ba464 runOnModule build-llvm/tools/clang/stage2-bins/llvm/lib/IR/LegacyPassManager.cpp:1590:55
#15 0xf15ba464 llvm::legacy::PassManagerImpl::run(llvm::Module&) build-llvm/tools/clang/stage2-bins/llvm/lib/IR/LegacyPassManager.cpp:541:44
#16 0x00ab3b30 compileModule build-llvm/tools/clang/stage2-bins/llvm/tools/llc/llc.cpp:742:17
#17 0x00ab18c4 main build-llvm/tools/clang/stage2-bins/llvm/tools/llc/llc.cpp:0:22
#18 0xf077f4ba __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#19 0xf077f556 call_init ./csu/libc-start.c:128:20
#20 0xf077f556 __libc_start_main ./csu/libc-start.c:347:5
`llc-19' failed in phase `LLVM Compiler'. (Exit code: -11)
```

I have tried with various LLVM versions from 17 to 21 (all from the official Debian archives).

The attached file is generated by GHC (while compiling GHC), so currently we are unable to build GHC on armv7 (tracked [here](https://gitlab.haskell.org/ghc/ghc/-/issues/26510)).

### LINKED ISSUE #167577: ARM: crash in ARMAsmPrinter::GetARMGVSymbol
Minimal reproducer:
```
target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "armv7-unknown-linux-android23"

@llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 65535, ptr @upb_GeneratedRegistry_Constructor_dont_copy_me__upb_internal_use_only, ptr null }]

; Uncommenting this block will resolve the crash.
;define void @test() {
;ret void
;}

declare void @upb_GeneratedRegistry_Constructor_dont_copy_me__upb_internal_use_only()
```
Instructions to reproduce:
`llc <  reduced.ll`

The crash occurs on Subtarget field of ARMAsmPrinter inside of ARMAsmPrinter::GetARMGVSymbol. This is only initialized when runOnMachineFunction is called. That is why simply adding a function definition is "fixing" the crash.

### PR DESCRIPTION
**Pull request by davemgreen**
The subtarget may not be set if no functions are present in the module. Attempt to use the TargetMachine directly in more cases.

Fixes #165422
Fixes #167577

### CODE REVIEW

**Review by smithp35 — APPROVED** [review]
This looks good to me. All the changes relate to things that don't vary per function like the object file format.

Will be good to leave some time for reviewers in the US time zone to comment.

File: llvm/lib/Target/ARM/ARMSubtarget.cpp [hunk 1]
```diff
@@ -317,20 +317,25 @@ bool ARMSubtarget::isRWPI() const {
          TM.getRelocationModel() == Reloc::ROPI_RWPI;
 }
 
-bool ARMSubtarget::isGVIndirectSymbol(const GlobalValue *GV) const {
+bool ARMSubtarget::isGVIndirectSymbol(const TargetMachine &TM,
```
Comment (efriedma-quic) [inline llvm/lib/Target/ARM/ARMSubtarget.cpp]: Please move this implementation into ARMTargetMachine.

**Review by efriedma-quic — COMMENTED** [review]
Can we completely delete the "Subtarget" variable from ArmAsmPrinter?  It seems easy to misuse, and I think everywhere that legitimately uses a Subtarget should be able to get it from the corresponding MachineFunction.

**Review by efriedma-quic — APPROVED** [review]
LGTM
