### PR TITLE
[clang-tidy] fix false positives for bugprone-macro-parentheses in C++ templates

### LINKED ISSUE #91155: wrong fix of clang-tidy bugprone-macro-parentheses
In this program

```
#define my_cast(type, p) reinterpret_cast<type*>(p)

void foo(void *p)
{
    (void)my_cast(int, p);
}
```

This command
` % /grid/common/test/llvm-v17.0.6d1rh74_lnx86/bin/clang-tidy --fix --checks=bugprone-macro-parentheses bugprone-macro-parentheses.cpp -- -std=c++17 -stdlib=libc++`
converts the macro to
`#define my_cast(type, p) (reinterpret_cast<(type)*>(p))
`
And then the compilation fails
```
% /grid/common/test/llvm-v17.0.6d1rh74_lnx86/bin/clang++ -c -std=c++17 -stdlib=libc++ bugprone-macro-parentheses.cpp
bugprone-macro-parentheses.cpp:10:11: error: expected a type
    5 |     (void)my_cast(int, p);
      |           ^
bugprone-macro-parentheses.cpp:6:44: note: expanded from macro 'my_cast'
    1 | #define my_cast(type, p) (reinterpret_cast<(type)*>(p))
      |                                            ^
bugprone-macro-parentheses.cpp:10:11: error: expected '>'
bugprone-macro-parentheses.cpp:6:50: note: expanded from macro 'my_cast'
    1 | #define my_cast(type, p) (reinterpret_cast<(type)*>(p))
      |                                                  ^
bugprone-macro-parentheses.cpp:10:11: note: to match this '<'
bugprone-macro-parentheses.cpp:6:43: note: expanded from macro 'my_cast'
    1 | #define my_cast(type, p) (reinterpret_cast<(type)*>(p))
      |                                           ^
bugprone-macro-parentheses.cpp:10:11: error: expected expression
    5 |     (void)my_cast(int, p);
      |           ^
bugprone-macro-parentheses.cpp:6:51: note: expanded from macro 'my_cast'
    1 | #define my_cast(type, p) (reinterpret_cast<(type)*>(p))
      |                                                   ^
3 errors generated.
```

### PR DESCRIPTION
**Pull request by zeyi2**
Closes #91155

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/MacroParenthesesCheck.cpp [hunk 1]
```diff
@@ -235,9 +236,17 @@ void MacroParenthesesPPCallbacks::argument(const Token &MacroNameTok,
       continue;
 
     // C++ template parameters.
-    if (PP->getLangOpts().CPlusPlus && Prev.isOneOf(tok::comma, tok::less) &&
-        Next.isOneOf(tok::comma, tok::greater))
-      continue;
+    if (PP->getLangOpts().CPlusPlus && Prev.isOneOf(tok::comma, tok::less)) {
+      const auto *NextIt = TI + 1;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/bugprone/MacroParenthesesCheck.cpp]: nit: TI++ or std::next();

Comment (vbvictor) [reply clang-tools-extra/clang-tidy/bugprone/MacroParenthesesCheck.cpp]: oh, i see that there is a lot of usage of "IT + 2", etc.. Correct to this if you like.

This gave me an idea of a check to convert `it + n` to `std::next(it, n)`

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/macro-parentheses.cpp [hunk 2]
```diff
@@ -54,3 +54,36 @@
...
+#define CAST8(type, p)    (static_cast<volatile type*>(p))
+#define CAST9(type, p)    (static_cast<type const*>(p))
+#define CAST10(type, p)   (reinterpret_cast<type * const &>(p))
+
+#define TEMPLATE1(T)      (std::vector<T*>)
+#define TEMPLATE2(T)      (std::vector<T&>)
+#define TEMPLATE3(T)      (std::vector<const T*>)
+#define TEMPLATE4(T)      (std::map<T*, T*>)
+
+#define BAD_TEMPLATE1(T)  (std::vector<T*2>)
```
Comment (localspook) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/macro-parentheses.cpp]: Does the check correctly diagnose the case where the LHS and RHS are reversed? e.g.:
```cpp
#define BAD_TEMPLATE1(T)  (std::vector<2*T>)
```

Comment (zeyi2) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/macro-parentheses.cpp]: I added a new test case, and it triggers a warning as expected :)

**Review by localspook — APPROVED** [review]

**Review by vbvictor — APPROVED** [review]
