### PR TITLE
[libc][signal] clean up usage of sighandler_t

### LINKED ISSUE #125598: [libc][signal] fix declaration of sighandler_t
cross compiling our unit tests (built hermetically) with llvm-libc fails with:
```
llvm-project/libc/test/UnitTest/FPExceptMatcher.cpp:40:3: error: unknown type name 'sighandler_t'; did you mean '__sighandler_t'?
   40 |   sighandler_t oldSIGFPEHandler = signal(SIGFPE, &sigfpeHandler);
      |   ^~~~~~~~~~~~
      |   __sighandler_t
llvm-project/build_aarch64/libc/include/llvm-libc-types/struct_sigaction.h:28:16: note: '__sighandler_t' declared here
   28 | typedef void (*__sighandler_t)(int);
      |                ^
```
it looks like our generated signal.h defines `sighandler_t` with two leading underscores (for some reason, 215c9fa4deac9ec6b4e504843830551f03b60620 seems related).  Whatever the problem was should be revisited.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
`man 3 signal`'s declaration has a face _only a mother could love_.

sighandler_t and __sighandler_t are not defined in the C standard, or POSIX.

They are helpful typedefs provided by glibc and the Linux kernel UAPI headers
respectively since working with function
pointers' syntax can be painful. But we should not rely on them; in C++ we have
`auto*` and `using` statements.

Remove the proxy header, and only include a typedef for sighandler_t when
targeting Linux, for compatibility with glibc.

Fixes: #125598

### CODE REVIEW

File: libc/src/signal/linux/signal.cpp [hunk 1]
```diff
@@ -8,14 +8,16 @@
...
-#include "hdr/types/sighandler_t.h"
 #include "src/__support/common.h"
 #include "src/__support/macros/config.h"
 #include "src/signal/sigaction.h"
 
 namespace LIBC_NAMESPACE_DECL {
 
-LLVM_LIBC_FUNCTION(sighandler_t, signal, (int signum, sighandler_t handler)) {
+// Our LLVM_LIBC_FUNCTION macro doesn't handle function pointer return types.
+using signal_handler = void (*)(int);
```
Comment (nickdesaulniers) [inline libc/src/signal/linux/signal.cpp:18]: perhaps `decltype` would be better here?

Comment (nickdesaulniers) [reply libc/src/signal/linux/signal.cpp:18]: hmm...no nevermind. We'd only be able to do `decltype(signal)`, which would not be the type of the parameter or return value.

Comment (nickdesaulniers) [reply libc/src/signal/linux/signal.cpp:18]: Perhaps `auto` would work...

**Comment by nickdesaulniers** [comment]
failure in presubmit:
```
llvm-project/build/libc/include/signal.h:20:10: fatal error: 'llvm-libc-types/__sighandler_t.h' file not found
   20 | #include "llvm-libc-types/__sighandler_t.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
the `libc.include.signal.__generated_hdr__` target doesn't have a dependency expressed on libc.include.llvm-libc-types.__sighandler_t. Need to add that.

**Comment by enh-google** [comment]
shouldn't `__sighandler_t` come from the uapi header, and only if you're using the uapi headers? (so nothing except the uapi headers should ever refer to that type, and the uapi headers themselves should be fine because they'll take care of their own transitive includes.)

**Comment by nickdesaulniers** [comment]
> shouldn't __sighandler_t come from the uapi header,

Did you mean `__signalfn_t`? It looks like asm-generic/signal-defs.h depends on `__sighandler_t`, but they themselves do not define that typedef. (unless something is really wrong with my grep-fu).

> and only if you're using the uapi headers?

We're inconsistent about our use of uapi headers.  I would like to try to use them more, but I suspect most libcs have run into issues with the uapi headers.  Probably a longer conversation to have there...

**Comment by enh-google** [comment]
> > shouldn't __sighandler_t come from the uapi header,
> 
> Did you mean `__signalfn_t`? It looks like asm-generic/signal-defs.h depends on `__sighandler_t`, but they themselves do not define that typedef. (unless something is really 
wrong with my grep-fu).

not in AOSP's clean copy (external/kernel-headers/). it's just split in two for readability (though i feel like the `__user` destroys that), but they're on adjacent lines in the file you mentioned:
```
typedef void __signalfn_t(int);
typedef __signalfn_t __user *__sighandler_t;
```

> > and only if you're using the uapi headers?
> 
> We're inconsistent about our use of uapi headers. I would like to try to use them more, but I suspect most libcs have run into issues with the uapi headers. Probably a longer conversation to have there...

yeah, they're kind of a mess, with some hacks for glibc compatibility (which is weird because glibc copy & pastes instead; bionic and musl compatibility would make more sense!). but, yes, if a side-effect of llvm-libc was making the uapi headers a bit less direct-libc-use-hostile, that would be good.

**Comment by nickdesaulniers** [comment]
Regardless, looking at the usage of `__sighandler_t` in asm-generic/signal-defs.h, I suspect that the libc is expected to provide the typedef to the kernel uapi header (which seems ass-backwards to me, but perhaps there's a good reason I'm unfamiliar with). (Also, perhaps I should just send a kernel patch to just use `void (*member)(int);` then in 100 years we can depend on it).

So I worry about a (hypothetical, perhaps contrived) case where: a user of llvm-libc somehow manages to `#include <asm-generic/signal.h>` before include llvm-libc's `<signal.h>` such that `__sighandler_t` is not defined.  Because the kernel headers themselves do not define `__sighandler_t`, that results in a compilation failure since there is no definition of `__sighandler_t`.  Is that possible? Or something else I'm misssing?

**Review by lntue — APPROVED** [review]

**Comment by enh-google** [comment]
> Regardless, looking at the usage of `__sighandler_t` in asm-generic/signal-defs.h, I suspect that the libc is expected to provide the typedef to the kernel uapi header (which seems ass-backwards to me, but perhaps there's a good reason I'm unfamiliar with). (Also, perhaps I should just send a kernel patch to just use `void (*member)(int);` then in 100 years we can depend on it).

i wasn't involved in the upstream uapi stuff, but as a _user_ of the uapi headers i've always assumed the opposite: that they deliberately use "not quite the names" to avoid conflicts with userspace. (it seems obvious that they _try_ somewhat, even if they're not particularly successful/systematic.)

> So I worry about a (hypothetical, perhaps contrived) case where: a user of llvm-libc somehow manages to `#include <asm-generic/signal.h>` before include llvm-libc's `<signal.h>` such that `__sighandler_t` is not defined. Because the kernel headers themselves do not define `__sighandler_t`, that results in a compilation failure since there is no definition of `__sighandler_t`. Is that possible? Or something else I'm misssing?

i still claim you're wrong there --- my unadulterated copy of the uapi headers _does_ define `__sighandler_t`, as i copy & pasted above and will repeat here:
```
typedef void __signalfn_t(int);
typedef __signalfn_t __user *__sighandler_t;
```
and i think -- without ever having talked to anyone responsible -- this is the whole point of all these double-underscore "almost right" names; they want things to "just work" wherever possible, without accidentally getting in the way.

(it's perhaps worth mentioning that it's very spotty. one of the main things we do when transforming the uapi headers from their upstream form to the form included in bionic is that we do a lot of "replace struct/type with a #include of our corresponding <bits/...> file" so we can have consistent behavior in all the cases the uapi headers _didn't_ think about. as i think i already mentioned, glibc mainly gets by with copy & paste, and musl seems to be on its usual "don't do that then" side of the fence.)

**Comment by enh-google** [comment]
> asm-generic/signal.h

(it's possible you missed that the relevant #include is _not_ at the top of the file ... it's just before the struct that needs the `__sighandler_t` type.)

**Comment by nickdesaulniers** [comment]
> not in AOSP's clean copy (external/kernel-headers/).

Oh, shoot, I am blind. For some reason both `ag` and `rg` don't search these kernel headers, but `grep -rn` does...wtf.

**Comment by nickdesaulniers** [comment]
Looks like `ag` and `rg` default ignore searching .h files unless `-uuu` is passed...good to know...

**Comment by nickdesaulniers** [comment]
Ok, given my misunderstanding due to my poor grep-fu, I think it's best to eliminate any reference to the double underscore prefix symbol (both in sources, and in file names). I'll clean that up.

File: libc/include/llvm-libc-types/sighandler_t.h [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+#ifndef LLVM_LIBC_TYPES_SIGHANDLER_T_H
+#define LLVM_LIBC_TYPES_SIGHANDLER_T_H
+
+#ifdef __linux__
```
Comment (enh-google) [inline libc/include/llvm-libc-types/sighandler_t.h:12]: sure you don't want a `_GNU_SOURCE` or whatever your internal equivalent is? (both glibc and bionic have `__USE_GNU` as the post-<features.h>-inclusion internal equivalent.)

File: libc/include/CMakeLists.txt [hunk 3]
```diff
@@ -275,13 +275,14 @@ add_header_macro(
   signal.h
   DEPENDS
     .llvm-libc-macros.signal_macros
+    .llvm-libc-types.__sighandler_t
```
Comment (enh-google) [inline libc/include/CMakeLists.txt]: should this be `sighandler_t` instead?

File: libc/include/signal.yaml [hunk 4]
```diff
@@ -69,10 +69,15 @@ functions:
...
+    # May the Geneva Convention have mercy on my soul... Why this insanity?
+    # Well: signal returns a function pointer to a function with no return
+    # value and which accepts an int. The parameter list appears on the far
+    # right of the declaration. i.e.
+    # void (*signal(int, void (*)(int)))(int);
+    return_type: void (*
     arguments:
       - type: int
-      - type: sighandler_t
+      - type: void (*)(int)))(int
```
Comment (enh-google) [inline libc/include/signal.yaml:81]: is the unmatched `(` intentional?

File: libc/include/llvm-libc-types/__sighandler_t.h [hunk 5]
```diff
@@ -10,5 +10,6 @@
 #define LLVM_LIBC_TYPES___SIGHANDLER_T_H
 
 typedef void (*__sighandler_t)(int);
```
Comment (enh-google) [inline libc/include/llvm-libc-types/__sighandler_t.h]: i thought the plan was to leave `__sighandler_t` to the <linux/signal.h> header?

(will the llvm-libc <signal.h> include that by default, like bionic's does, or copy & paste like musl?)

File: libc/include/llvm-libc-types/sighandler_t.h (hunk 2 above)
Comment (nickdesaulniers) [reply libc/include/llvm-libc-types/sighandler_t.h:12]: No, we don't currently hold folk's code hostage based on them defining `_GNU_SOURCE` or not, and I don't plan to add it.

File: libc/include/signal.yaml (hunk 4 above)
Comment (nickdesaulniers) [reply libc/include/signal.yaml:81]: Yes, see the comment. hdrgen just pastes `return_type` + `name` + `(` + arguments + `)`.

File: libc/include/CMakeLists.txt (hunk 3 above)
Comment (nickdesaulniers) [reply libc/include/CMakeLists.txt]: This comment was left on a previous version of the patch series.  Been fixed already. Reload your browser tab. ;)

File: libc/include/llvm-libc-types/__sighandler_t.h (hunk 5 above)
Comment (nickdesaulniers) [reply libc/include/llvm-libc-types/__sighandler_t.h]: This comment was left on a previous version of the patch series. Been fixed already. Reload your browser tab. ;)

That said, I'm doing neither include linux/signal.h nor copy+paste; currently we provide no declaraion of `__sighandler_t` through inclusion of our `<signal.h>` at all.  Perhaps that's problematic for users that really insist on using `__sighandler_t` in their code?

I know your position on making their lives easier...

File: libc/include/llvm-libc-types/sighandler_t.h (hunk 2 above)
Comment (enh-google) [reply libc/include/llvm-libc-types/sighandler_t.h:12]: i flirted with that myself for bionic, but it's a bit more complicated in practice --- "what when the GNU variant _conflicts_ with the POSIX one?", say, or "what when people are trying to build code that's incompatible with GNU extensions [because they use some of the names themselves, say]"...

(the weird one for Android is `_BSD_SOURCE` where by historical accident that's always on. but `_GNU_SOURCE` is something developers are used to turning on/off either via `-std=gnu23` vs `-std=c23` or `-D`/`#define`.)

File: libc/include/signal.yaml (hunk 4 above)
Comment (enh-google) [reply libc/include/signal.yaml:81]: i still don't understand ... shouldn't that still have matching parens?

File: libc/include/llvm-libc-types/__sighandler_t.h (hunk 5 above)
Comment (enh-google) [reply libc/include/llvm-libc-types/__sighandler_t.h]: yeah, that's kind of what i meant: "you probably shouldn't define `__sighandler_t`, and should leave that to the uapi header [which callers can #include directly if they want it]" ... except that "what about all the other stuff?". because bionic doesn't _deliberately_ export `__sighandler_t`; it just gets it because it's in the same uapi header as all the other stuff that we _do_ need to export, and we have a pretty strict [absolute?] rule about "no copy & paste of content that's in a uapi header --- include the uapi header instead".

(technically we do explicitly filter some stuff _out_ of uapi headers, but generally only when they actively cause widespread breakage/pollution if you leave them in.)

File: libc/include/signal.yaml (hunk 4 above)
Comment (nickdesaulniers) [reply libc/include/signal.yaml:81]: The result in the generated header (visible at build time, not something I can link to in sources) is:

```c
void (* signal(int, void (*)(int)))(int)
```
which looks correct to me, typechecks (via `clang build/libc/include/signal.h -isystem build/libc/include -fsyntax-only -Wsystem-headers`), and cdecl seems to be able to decode this declaration as I would have expected. https://cdecl.org/?q=void+%28*+signal%28int%2C+void+%28*%29%28int%29%29%29%28int%29

File: libc/include/llvm-libc-types/sighandler_t.h (hunk 2 above)
Comment (nickdesaulniers) [reply libc/include/llvm-libc-types/sighandler_t.h:12]: I was thinking more about this last night, and `qsort_r` came to mind.

So I guess I should change my stance slightly from "never" to "perhaps when there _is_ a conflict."

Is there a conflict here? Well, `sig_t` and `sighandler_t` don't conflict with each other, and the issue isn't as severe as `qsort_r`.  But Bionic provides both without requiring users to pledge allegiance; if bionic doesn't llvm-libc should not either (IMO).

> I learned it from you, Dad! /runs away crying

But I will keep that in mind that `_GNU_SOURCE` and `_BSD_SOURCE` do exist more for than just pledges of allegiance and holding user code hostage, and that we may need to deploy those in llvm-libc in the future.  I still don't think we need to here (yet; famous last words).

---

> but _GNU_SOURCE is something developers are used to turning on/off either via -std=gnu23 vs -std=c23

Wait...what?!

```sh
$ clang -std=gnu++23 --target=x86_64-linux-gnu -dM -E -x c++ /dev/null | grep GNU_SOURCE
#define _GNU_SOURCE 1
$ clang -std=gnu23 --target=x86_64-linux-gnu -dM -E -x c /dev/null | grep GNU_SOURCE
$ g++ -dM -E -x c++ /dev/null | grep GNU_SOURCE
#define _GNU_SOURCE 1
$ gcc -dM -E -x c /dev/null | grep GNU_SOURCE
$
```
uh...so perhaps not a bug in clang as the first two statements made me think...but WTF!?

File: libc/include/llvm-libc-types/__sighandler_t.h (hunk 5 above)
Comment (nickdesaulniers) [reply libc/include/llvm-libc-types/__sighandler_t.h]: Perhaps it would be better for me to `#include <linux/signal.h>` from our generated `signal.h` in order to provide `__sighandler_t` (and everything else that entails) such that users don't need to directly+explicitly depend on `<linux/signal.h>`.

It's worth deeper discussions with all of us about policy relating to kernel headers. (https://sourceware.org/glibc/wiki/Synchronizing_Headers comes to mind, but perhaps isn't the only approach as you've mentioned).

But for now, I'm in a sprint to get llvm-libc's test harness to cross compile.  The fix is to clean up the usage of `__sighandler_t`, which is the intent of this PR.

File: libc/include/llvm-libc-types/sighandler_t.h (hunk 2 above)
Comment (enh-google) [reply libc/include/llvm-libc-types/sighandler_t.h:12]: > I was thinking more about this last night, and `qsort_r` came to mind.
> 
> So I guess I should change my stance slightly from "never" to "perhaps when there _is_ a conflict."
> 
> Is there a conflict here? Well, `sig_t` and `sighandler_t` don't conflict with each other, and the issue isn't as severe as `qsort_r`. But Bionic provides both without requiring users to pledge allegiance; if bionic doesn't llvm-libc should not either (IMO).
> 
> > I learned it from you, Dad! /runs away crying
> 
> But I will keep that in mind that `_GNU_SOURCE` and `_BSD_SOURCE` do exist more for than just pledges of allegiance and holding user code hostage, and that we may need to deploy those in llvm-libc in the future. I still don't think we need to here (yet; famous last words).

yeah, as you can probably tell, i do think "provide all the things until/unless proven problematic" is a developer-friendly option.

the only real counterargument i've heard is "it's bad for source portability in the _other_ direction". but i've always cared more that people's stuff "just works" when ported _to_ the libc i have control over rather than what might happen when ported _away_ (in part because that's probably less common anyway; any library that's first developed on Android seems likely to be Android-specific in some way, or you'd probably make it cross-platform from the beginning).

> > but _GNU_SOURCE is something developers are used to turning on/off either via -std=gnu23 vs -std=c23
> 
> Wait...what?!
> 
> ```shell
> $ clang -std=gnu++23 --target=x86_64-linux-gnu -dM -E -x c++ /dev/null | grep GNU_SOURCE
> #define _GNU_SOURCE 1
> $ clang -std=gnu23 --target=x86_64-linux-gnu -dM -E -x c /dev/null | grep GNU_SOURCE
> $ g++ -dM -E -x c++ /dev/null | grep GNU_SOURCE
> #define _GNU_SOURCE 1
> $ gcc -dM -E -x c /dev/null | grep GNU_SOURCE
> $
> ```
> 
> uh...so perhaps not a bug in clang as the first two statements made me think...but WTF!?

oh, yeah, that's it ... i never do this myself, so i can never remember _which_ combinations imply `_GNU_SOURCE`, just that there are dragons in that area.

madness indeed. (especially because `gnu` vs `c` _does_ let you opt in/out of _language_ extensions. if you were going to do anything here, consistency would have been nice. i assume there was a historical accident somewhere -- like bionic's always-on `_BSD_SOURCE` and they just couldn't fix it by the time they realized.)

File: libc/include/llvm-libc-types/__sighandler_t.h (hunk 5 above)
Comment (enh-google) [reply libc/include/llvm-libc-types/__sighandler_t.h]: > Perhaps it would be better for me to `#include <linux/signal.h>` from our generated `signal.h` in order to provide `__sighandler_t` (and everything else that entails) such that users don't need to directly+explicitly depend on `<linux/signal.h>`.

yeah, i think i'm not alone in saying that user code generally shouldn't `#include <linux/*>`, and _especially_ not when there's a standard header.

i _think_ that's why musl and glibc don't seem to care as much as me about whether or not that even works --- they have a stronger "don't do that then" stance.

> It's worth deeper discussions with all of us about policy relating to kernel headers. (https://sourceware.org/glibc/wiki/Synchronizing_Headers comes to mind, but perhaps isn't the only approach as you've mentioned).

yeah, that's the "doesn't really work well, even for glibc" solution i've mentioned before. i do think it would be good to have a cleaner option, and maybe that's more likely now between your kernel connections _and_ there now [maybe] being two libcs that want to not duplicate anything that's in a uapi header _and_ the existing glibc "it would be _nice_ if you could include the glibc header and the uapi header without conflicts".

> But for now, I'm in a sprint to get llvm-libc's test harness to cross compile. The fix is to clean up the usage of `sighandler_t`, which is the intent of this PR.

yeah, don't mind me ... i'm just trying to brain dump as much of the bionic history as i can, in particular when we have things that went well vs things that went badly (and orthogonally things we did on purpose vs things that were accidents).

TL;DR: i do think `sighandler_t` is somewhat useful for source compatibility (and even "not in POSIX? not coming in!" musl has it, which is always useful anecdata in that it probably means something fairly significant was broken without it). i have no reason to believe `__sighandler_t` is useful, but bionic's default "never duplicate something that's in a uapi header" policy means we'd have to go out of our way to _not_ expose it, and i've never had any reason to believe _that_ was useful either. (and your yaml format doesn't work well for examples like signal() :-P )

Comment (nickdesaulniers) [reply libc/include/llvm-libc-types/__sighandler_t.h]: > i'm just trying to brain dump as much of the bionic history as i can, in particular when we have things that went well vs things that went badly (and orthogonally things we did on purpose vs things that were accidents).

Having that in writing and documented is appreciated; especially handy to be able to link to in the future.

> (and your yaml format doesn't work well for examples like signal() :-P )

Did you just call my baby ugly? :P

> bionic's default "never duplicate something that's in a uapi header" policy
> maybe that's more likely now between your kernel connections and there now [maybe] being two libcs that want to not duplicate anything that's in a uapi header and the existing glibc "it would be nice if you could include the glibc header and the uapi header without conflicts".

Right!  I plan to do more research into why this is a problem, and what various kernel developers and libc maintainers view as the problems.  I suspect we can clean this up upstream in the kernel sources for everyone (that matters).

> yeah, don't mind me ...

May I have +2 then from you? I think my fellow reviewers are watching this from the sidelines and deferring to your experience here.

File: libc/include/CMakeLists.txt (hunk 3 above)
Comment (nickdesaulniers) [reply libc/include/CMakeLists.txt]: Ah!  So in gerrit, there's distinct UI to distinguish between patches in a patch series, vs each individual patches having a revision.

Github does not have this distinction (unfortunately), so it's ambiguous when someone has multiple commits whether their intent was to have a distinct patch series to review vs having multiple revisions of one patch.

Perhaps a tell:
As I've been responding to feedback, I've been pushing new commits on top rather than force pushing.  That's how I would distinguish between the two, but there's no rule in github that that's what you have to do, so it remains ambiguous to reviewers still!

In the case of this PR, I plan to squash when merging.  In that case, clicking through the individual commits is akin to clicking through the revisions of one patch in gerrit; instead, just view the combined diff by clicking "Files Changed" rather than "Commits."

FWIW, I was in the thread when llvm discussed successors to phab, personally advocating for gerrit.

**Review by enh-google — APPROVED** [review]
