### PR TITLE
[lldb] Fix dwim-print to not delete non-result persistent variables

### LINKED ISSUE #84806: LLDB: Inconsistant existance of expression global variable (`use of undeclared identifier`)
# Problem

During LLDB debug session, global variables that are declared in a previous expression evaluation is sometimes reported as undeclared identifier _after_ a program restart.

TL;DR LLDB output (see full output at the end):
```
(lldb) p int $i = 32; $i
(int) 32
...
(lldb) r
...
(lldb) p $i
(int) 32
(lldb) p $i + a
error: <user expression 2>:1:1: use of undeclared identifier '$i'
    1 | $i + a
      | ^
(lldb) p $i
error: <user expression 3>:1:1: use of undeclared identifier '$i'
    1 | $i
      | ^
(lldb) 
```

In the above, **there are two issues**:
1. `$i` in `$i + a` was deemed undeclared after a print of `$i` itself was successful.
2. After the above issue happened, the printing of `$i` itself no longer works, either.

# Repro steps

Create a `main.cpp`:
```
int main() { 
    int a = 1;
    return a;
}
```

Compile:
```
clang++ -g -O0 main.cpp
```

Start `lldb a.out` then type the following comands. The output from LLDB follows.
```
b /main/
r

p a
p int $i = 32; $i
p $i + a
r

p $i
p $i + a
p $i
```

Full LLDB output:
```
(lldb) target create "a.out"
Current executable set to '/Users/<username>/tmp2/a.out' (arm64).
(lldb) b /main/
Breakpoint 1: where = a.out`main + 12 at main.cpp:2:9, address = 0x0000000100003f98
(lldb) r

Process 73517 launched: '/Users/<username>/tmp2/a.out' (arm64)

Process 73517 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100003f98 a.out`main at main.cpp:2:9
   1   	int main() {
-> 2   	    int a = 1;
   3   	    return a;
   4   	}
(lldb) p a
(int) -2035101492
(lldb) p int $i = 32; $i
(int) 32
(lldb) p $i + a
(int) -2035101460
(lldb) r
There is a running process, kill it and restart?: [Y/n] 
Process 73517 exited with status = 9 (0x00000009) killed
Process 73523 launched: '/Users/<username>/tmp2/a.out' (arm64)
Process 73523 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100003f98 a.out`main at main.cpp:2:9
   1   	int main() {
-> 2   	    int a = 1;
   3   	    return a;
   4   	}
(lldb) p $i
(int) 32
(lldb) p $i + a
error: <user expression 2>:1:1: use of undeclared identifier '$i'
    1 | $i + a
      | ^
(lldb) p $i
error: <user expression 3>:1:1: use of undeclared identifier '$i'
    1 | $i
      | ^
(lldb) 
```

### PR DESCRIPTION
**Pull request by kastiglione**
`EvaluateExpression` does not always create a new persistent result. If the expression is a bare persistent variable, then a new persistent result is not created. This means the caller can't assume a new persistent result is created for each evaluation. However, `dwim-print` was doing exactly that: assuming a new persistent result for each evaluation. This resulted in a bug:

```
(lldb) p int $j = 23
(lldb) p $j
(lldb) p $j
```

The first `p $j` would not create a persistent result, and so `dwim-print` would inadvertently delete `$j`. The second `p $j` would fail.

The fix is to try `expr` as a persistent variable, after trying `expr` as a frame variable. For persistent variables, this avoids calling `EvaluateExpression`.

Resolves https://github.com/llvm/llvm-project/issues/84806

rdar://124688427

### CODE REVIEW

File: lldb/source/Commands/CommandObjectDWIMPrint.cpp [hunk 1]
```diff
@@ -170,6 +170,14 @@ void CommandObjectDWIMPrint::DoExecute(StringRef command,
     ExpressionResults expr_result = target.EvaluateExpression(
         expr, exe_scope, valobj_sp, eval_options, &fixed_expression);
 
+    auto persistent_name = valobj_sp->GetName();
+    // EvaluateExpression doesn't generate a new persistent result (`$0`) when
+    // the expression is already just a persistent variable (`$var`). Instead,
+    // the same persistent variable is reused. Take note of when a persistent
+    // result is created, to prevent unintentional deletion of a user's
+    // persistent variable.
+    bool did_persist_result = persistent_name != expr;
```
Comment (jimingham) [inline lldb/source/Commands/CommandObjectDWIMPrint.cpp:179]: This seems like a really fragile way to test what you want to test, which is whether the result of the expression was a new expression result variable.  It might be better to add a "PeekNextPersistentVariableName" that just prints what the next persistent variable would be called but doesn't increment the counter, then assert that the variable you produced is NOT called that?

Comment (kastiglione) [reply lldb/source/Commands/CommandObjectDWIMPrint.cpp:179]: I agree that it's not ideal, but I felt it was sufficient.

> what you want to test, which is whether the result of the expression was a new expression result variable

exactly. However I think peeking at the result variables is also not ideal. Both my initial stab at this, and your suggestion are deducing whether a new expression result variable was created. If I'm to change the API, I think it'd be ideal to make the API communicate have means to communicate this explicitly.

There's another approach I considered taking. Before calling `EvaluateExpression`, try the expression as a persistent variable and check in the target to see if it exists, and if it does exist, use it (and avoid `EvaluateExpression` altogether). This is similar to how expressions are first treated as frame variables (and as @felipepiovezan has requested, we should try `target variable` too).

Comment (jimingham) [reply lldb/source/Commands/CommandObjectDWIMPrint.cpp:179]: It would be good to have EvaluateExpression tell you whether it created a result variable or not.  For instance, calling a void function produces no result.  It would be nice to know that happened directly rather than attempting to guess from the returned ValueObject.  We definitely know this...
That would definitely be a better way to do this.

Comment (kastiglione) [reply lldb/source/Commands/CommandObjectDWIMPrint.cpp]: Jim, I have updated the PR to try the expression as a persistent variable – prior to expression evaluation. My thinking is, instead of evaluating first, then asking if a persistent variable was created, it's more straight to the point to first ask "is this a persistent variable".

I like the idea of trying the various kinds of variables in sequence: frame, target, persistent.

**Comment by jimingham** [comment]
That's an okay approach if the only time an expression produces a result variable dwim-print should not delete is when a persistent variable is explicitly mentioned.  But anyway, since that's the case we're fixing, and checking as a persistent variable as a short-cut early on isn't a bad idea, it is fine for these purposes.

I think you need to get the persistent variables for whatever the language of the expression happens to be, not just get all the persistent variables. Otherwise, if you define a C persistent variable, then stop in a swift frame and do:

(lldb) p $works_in_c
10
(lldb) p $works_in_c + 10
unknown identifier "$works_in_c"

which would be confusing.

**Comment by kastiglione** [comment]
I'll change this to scope lookup of persistent variables to the expected language.

However, there's an argument to be made that `dwim-print $my_var` should work anywhere. I think that follows the spirit of "do what I mean". Maybe in the future I'll propose that in a separate change.

**Comment by jimingham** [comment]
The counter to this is that `dwim-print` differs from `frame var` in that it supports complex expressions.  So having it work for simple statements of a variable name (what frame var and target var already do just fine) but then fail when the SAME name is used in a slightly more complicated expression is a serious failure to do its particular job.

Jim

**Comment by kastiglione** [comment]
I don't consider it a failure to not be able to perform mixed language expressions. But it would have to be presented to the user in a way that is understandable, which could be a challenge.

Anyway, I pushed the change that scopes the lookup to the expected language.

thank you for the reviews

**Comment by jimingham** [comment]
> I don't consider it a failure to not be able to perform mixed language expressions. But it would have to be presented to the user in a way that is understandable, which could be a challenge.
> 
> Anyway, I pushed the change that scopes the lookup to the expected language.
> 
> thank you for the reviews

I'm not sure what you mean by "mixed language expressions".  What I'm trying to avoid is, if stopped in a swift frame, you get:

(lldb) p cpp_object_ptr
<get a value>
(lldb) p cpp_object_ptr->cpp_method()
<unknown identifier cpp_object_ptr>

That's not a cross language expression, that's a perfectly good C++ expression.  I don't think it makes sense to present simple variables of all language types, but not evaluate expressions using all the available expression parsers, starting with the obvious one first.

**Review by jimingham — APPROVED** [review]
LGTM

**Comment by kastiglione** [comment]
> I'm not sure what you mean by "mixed language expressions". 

I was thinking about the case where a user attempts `p $some_c_var + 1` in Swift frame – which is valid swift as far as the debugger is concerned.

**Comment by jimingham** [comment]
> > I'm not sure what you mean by "mixed language expressions".
> 
> I was thinking about the case where a user attempts `p $some_c_var + 1` in Swift frame – which is valid swift as far as the debugger is concerned. I said mixed because it's got a C var inside a Swift expression.

The important thing is not whether this is abstractly a valid swift expression, but rather that is an expression that would execute correctly in the Swift Expression parser.  That won't happen with this expression because the swift compiler can't find `$some_c_var` and and even if it could it wouldn't know how to use it.

My take is that if I do `p some_var` and you return `some_var` successfully, then when I do `p some_var->some_method()` you will use the language in which you found that symbol to evaluate that expression that uses it.  I don't see how you will know that directly, I think the best you can do is try them all in some reasonable order.

`dwim-print` has a language option because it's really trying to be the expression parser but done as efficiently as possible.  Having it just sometimes ignore whatever that language option is supposed to instruct it to do seems wrong, and having it sometimes ignore the language and other times not is even more wrong, IMO.
