### PR TITLE
[LLDB] Avoid crashes when inspecting MSVC STL types

### LINKED ISSUE #115216: [lldb] resolving optional crashes lldb(-dap) (clang/windows/msvc)
When debugging from vscode/cursor using lldb-dap. the debugger will crash when trying to resolve an std::optional. switching the std::optional out with an different implementation (like Optional26 by beman) fixes the problem.

link to a minimal repro: https://github.com/BjornSAIM/lldb-optional-crash
just set a breakpoint anywhere after the assignment to the optional.

clang/lldb/... are all on 19.1.1
Visual Studio 2022 version 17.9

### LINKED ISSUE #120310: [LLDB] `frame variable` crashes when printing a shared_ptr when program uses MSVC STL
LLDB is crashing when im trying to execute `frame variable` command and there is instance of a class that contains shared_ptr inside of it

Platform: Windows 11 23H2 
Compiler that used to build executable: MSVC v19.41

What version of lldb were tested: 
lldb v19.0 (installed from visual studio installer)
lldb v20.0 (builded from sources on 17 of december 2024)

Minimal code to reproduce bug
```cpp
#include <iostream>

class Test
{
public:
  Test(std::shared_ptr<int> v)
      : value(v)
  {}

  std::shared_ptr<int> GetValue() { return value; }

private:
  std::shared_ptr<int> value;
};

int main()
{

  std::unique_ptr<int> test = std::make_unique<int>(25);

  std::cout << "Test " << *test << std::endl;

  Test t(std::make_shared<int>(42));

  std::cout << "Test2 " << *t.GetValue() << std::endl;
}
```

Actions to reproduce this bug
1) Build executable
2) Attach lldb to it with `lldb app.exe`
3) Set breakpoint on main
4) run program to hit the breakpoint
5) execute command `frame variable`
6) expect crash

Stacktrace generated by lldb v20.0 builded from sources
```
Exception Code: 0xC0000005
 #0 0x00007ff953a9d065 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x29d065)
 #1 0x00007ff953d8ad4e lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x58ad4e)
 #2 0x00007ff953c87964 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x487964)
 #3 0x00007ff953ab3e4b lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b3e4b)
 #4 0x00007ff953ab44ec lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b44ec)
 #5 0x00007ff953ab583a lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b583a)
 #6 0x00007ff953ab3b09 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b3b09)
 #7 0x00007ff953ab3fba lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b3fba)
 #8 0x00007ff953ab44ec lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b44ec)
 #9 0x00007ff953ab583a lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2b583a)
#10 0x00007ff953c77308 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x477308)
#11 0x00007ff955cb80cb lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x24b80cb)
#12 0x00007ff953ae0aee lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2e0aee)
#13 0x00007ff953aed662 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2ed662)
#14 0x00007ff953aef829 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2ef829)
#15 0x00007ff953a90f60 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x290f60)
#16 0x00007ff953a488b9 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2488b9)
#17 0x00007ff953afa519 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x2fa519)
#18 0x00007ff953930a74 lldb::SBDebugger::RunCommandInterpreter(bool, bool) (W:\llvm-project\Release\bin\liblldb.dll+0x130a74)
#19 0x00007ff6003d5083 (W:\llvm-project\Release\bin\lldb.exe+0x5083)
#20 0x00007ff6003d921f (W:\llvm-project\Release\bin\lldb.exe+0x921f)
#21 0x00007ff6003fd4ec (W:\llvm-project\Release\bin\lldb.exe+0x2d4ec)
#22 0x00007ffa6c42259d (C:\WINDOWS\System32\KERNEL32.DLL+0x1259d)
#23 0x00007ffa6d34af38 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5af38)
```

Stacktrace generated by lldb v19.0.0 (from visual studio installer)
```
Exception Code: 0xC0000005
 #0 0x00007ff9a4b2547c lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x50547c)
 #1 0x00007ff9a486b95a lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x24b95a)
 #2 0x00007ff9a4881a0b lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x261a0b)
 #3 0x00007ff9a48820a7 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x2620a7)
 #4 0x00007ff9a4883362 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x263362)
 #5 0x00007ff9a488179e lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x26179e)
 #6 0x00007ff9a4881b85 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x261b85)
 #7 0x00007ff9a48820a7 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x2620a7)
 #8 0x00007ff9a4883362 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x263362)
 #9 0x00007ff9a484e3a6 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x22e3a6)
#10 0x00007ff9a67d898f lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x21b898f)
#11 0x00007ff9a48b8dce lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x298dce)
#12 0x00007ff9a48c6a05 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x2a6a05)
#13 0x00007ff9a48c849b lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x2a849b)
#14 0x00007ff9a4861d72 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x241d72)
#15 0x00007ff9a480bed9 lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x1ebed9)
#16 0x00007ff9a48d2b1c lldb::SBUnixSignals::SetShouldSuppress(int, bool) (W:\binary\liblldb.dll+0x2b2b1c)
#17 0x00007ff9a471445a lldb::SBDebugger::RunCommandInterpreter(bool, bool) (W:\binary\liblldb.dll+0xf445a)
#18 0x00007ff6eb084568 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe 0x4568 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe 0x52a9
#19 0x00007ff6eb084568 C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe 0x2adb4 (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe+0x4568)
#20 0x00007ff6eb084568
#21 0x00007ff6eb084568 (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe+0x4568)
0x00007FF9A4B2547C, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x50547C byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x3538EC byte(s)
0x00007FF9A486B95A, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x24B95A byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x99DCA byte(s)
0x00007FF9A4881A0B, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x261A0B byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xAFE7B byte(s)
0x00007FF9A48820A7, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x2620A7 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xB0517 byte(s)
0x00007FF9A4883362, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x263362 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xB17D2 byte(s)
0x00007FF9A488179E, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x26179E byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xAFC0E byte(s)
0x00007FF9A4881B85, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x261B85 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xAFFF5 byte(s)
0x00007FF9A48820A7, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x2620A7 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xB0517 byte(s)
0x00007FF9A4883362, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x263362 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xB17D2 byte(s)
0x00007FF9A484E3A6, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x22E3A6 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x7C816 byte(s)
0x00007FF9A67D898F, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x21B898F byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x2006DFF byte(s)
0x00007FF9A48B8DCE, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x298DCE byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xE723E byte(s)
0x00007FF9A48C6A05, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x2A6A05 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xF4E75 byte(s)
0x00007FF9A48C849B, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x2A849B byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0xF690B byte(s)
0x00007FF9A4861D72, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x241D72 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x901E2 byte(s)
0x00007FF9A480BED9, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x1EBED9 byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x3A349 byte(s)
0x00007FF9A48D2B1C, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0x2B2B1C byte(s), ?SetShouldSuppress@SBUnixSignals@lldb@@QEAA_NH_N@Z() + 0x100F8C byte(s)
0x00007FF9A471445A, W:\binary\liblldb.dll(0x00007FF9A4620000) + 0xF445A byte(s), ?RunCommandInterpreter@SBDebugger@lldb@@QEAAX_N0@Z() + 0x21A byte(s)
0x00007FF6EB084568, C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe(0x00007FF6EB080000) + 0x4568 byte(s)
0x00007FF6EB0852A9, C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe(0x00007FF6EB080000) + 0x52A9 byte(s)
0x00007FF6EB0AADB4, C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\lldb.exe(0x00007FF6EB080000) + 0x2ADB4 byte(s)
0x00007FFA6C42259D, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFA6C410000) + 0x1259D byte(s), BaseThreadInitThunk() + 0x1D byte(s)
0x00007FFA6D34AF38, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFA6D2F0000) + 0x5AF38 byte(s), RtlUserThreadStart() + 0x28 byte(s)
```

There should be diagnostics logs in my Temp folder according to this message
```
LLDB diagnostics will be written to C:\Users\{USER}\AppData\Local\Temp\diagnostics-897c9d
```

But `diagnostics.log` file is competly empty.

### PR DESCRIPTION
**Pull request by Nerixyz**
When inspecting/printing types from MSVC's STL, LLDB would crash because it assumes these types were from libstdc++. Specifically, `std::shared_ptr` and `std::optional` would crash because of a null pointer dereference. I added a minimal test that tests the types with C++ helpers for libstdc++ (only tests for crashes).

- Fixes #115216 
- Fixes #120310 

This still has one unresolved discussion: What about MS STL types? This is https://github.com/llvm/llvm-project/issues/24834, but there was a bit of discussion in #120310 as well. The main issue is that MSVC's STL uses the same type names as libstdc++ (i.e. neither uses an inline namespace like libc++ for some types).

### CODE REVIEW

File: lldb/source/Plugins/Language/CPlusPlus/GenericOptional.cpp [hunk 1]
```diff
@@ -74,9 +74,11 @@ lldb::ChildCacheState GenericOptionalFrontend::Update() {
 
   if (m_stdlib == StdLib::LibCxx)
     engaged_sp = m_backend.GetChildMemberWithName("__engaged_");
-  else if (m_stdlib == StdLib::LibStdcpp)
-    engaged_sp = m_backend.GetChildMemberWithName("_M_payload")
-                     ->GetChildMemberWithName("_M_engaged");
+  else if (m_stdlib == StdLib::LibStdcpp) {
+    ValueObjectSP payload = m_backend.GetChildMemberWithName("_M_payload");
+    if (payload)
```
Comment (Michael137) [inline lldb/source/Plugins/Language/CPlusPlus/GenericOptional.cpp:79]:
```suggestion
    if (ValueObjectSP payload = m_backend.GetChildMemberWithName("_M_payload"))
```

File: lldb/test/Shell/Process/Windows/msstl_smoke.cpp [hunk 2]
```diff
@@ -0,0 +1,57 @@
+// clang-format off
+
+// REQUIRES: target-windows
+// RUN: %build --compiler=clang-cl -o %t.exe --std c++20 -- %s
+// RUN: env LLDB_USE_NATIVE_PDB_READER=1 %lldb -f %t.exe -o "b main" -o "run" -o "fr v" -o c | FileCheck %s
+
+#include <bitset>
```
Comment (Michael137) [inline lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Are we not running the data-formatter tests on Windows at all? There's definitely tests for all of these elsewhere in the API test-suite

File: lldb/test/Shell/helper/build.py [hunk 3]
```diff
@@ -683,14 +683,14 @@ def _get_compilation_command(self, source, obj):
             args.append("-fms-compatibility-version=19")
         args.append("/c")
 
+        if self.std:
```
Comment (Michael137) [inline lldb/test/Shell/helper/build.py:686]: Why is this change necessary?

**Review by Michael137 — COMMENTED** [review]
Seems like a fine stop-gap for now to avoid crashing

Just left some clarification questions

File: lldb/test/Shell/helper/build.py (hunk 3 above)
Comment (Nerixyz) [reply lldb/test/Shell/helper/build.py:686]: `/std` was appended after the `--`, so the compiler interpreted it as a file.

Comment (Michael137) [reply lldb/test/Shell/helper/build.py:686]: I see, lets do that in a separate patch please

File: lldb/test/Shell/Process/Windows/msstl_smoke.cpp (hunk 2 above)
Comment (Nerixyz) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Do you have any specific tests? Ideally ones that test optional and shared_ptr. I can look at them later.

**Comment by Nerixyz** [comment]
> Seems like a fine stop-gap for now to avoid crashing

Yes, exactly. The formatted output for these types is still incomplete (often, types are formatted without any children).
I'd love to help with support for MSVC's STL, but it's probably better to discuss that in #24834.

File: lldb/test/Shell/Process/Windows/msstl_smoke.cpp (hunk 2 above)
Comment (Michael137) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: The tests in `lldb/test/API/functionalities/data-formatter/data-formatter-stl`

Comment (Nerixyz) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Most of these tests are unsupported due to being in the libc++/libstdc++ categories which aren't supported on Windows ("Don't know how to build with libc++ on windows"). The only tests that run are `libstdcpp/unique_ptr/invalid` and `libcxx-simulators/*`.

Comment (Michael137) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Hmm right that makes sense. Should we then have a Windows data-formatter subdirectory in `lldb/test/API/functionalities/data-formatter/data-formatter-stl`? We should ideally have two test configurations:

1. Tests that ensure we at least don't crash when using the MSVC STL? I.e., `std::optional` and `std::shared_ptr`. This would test your current PR
2. Tests for libc++ on Windows (which AFAIU, isn't the recommended configuration on Windows but is definitely used in the wild)

Not sure how easy it is to set up (2). That shouldn't block this PR, but would be nice to get around to it.

But (1) should be doable. Though not sure how equipped the API test infrastructure is to compile against MSVC STL. Worst case we could go for Shell tests there like you did here

CC @DavidSpickett @labath @omjavaid for opinions on Windows testing

Comment (Nerixyz) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: > Tests for libc++ on Windows (which AFAIU, isn't the recommended configuration on Windows but is definitely used in the wild)

libstdc++ and (sometimes) libc++ are used on MinGW (and probably Cygwin). There, MS' STL can't be used.

One other thing: https://lldb.llvm.org/use/variable.html#categories mentions that the formatters for libc++ and libstdc++ would be in different categories (`libcxx`, `gnu-libstdc++`), but (at least the built-in ones) are [all put in the `cplusplus` category](https://github.com/llvm/llvm-project/blob/76a55d3860f76c15ca51d188e10e4352fecf61e9/lldb/source/Plugins/Language/CPlusPlus/CPlusPlusLanguage.cpp#L1731-L1737).

Comment (Michael137) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Hmm I wonder if that was leftover documentation from when the data-formatters were all written in python? But yea, now they're all in the `cplusplus` category IIUC

Comment (DavidSpickett) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: I presume all API tests on Windows are compiling against MSVC STL when compiled on Windows (it has nothing else to use). If you're wondering whether there's a good way to detect that is the case, yeah, that might be tricky.

For number 2, I'm not into the idea of changing the existing bot to build everything against libcxx, but if we can enable the runtime and then libcxx specific tests will be run as well, that's fine. Windows is supported and tested for libcxx as long as clang/clang-cl is the compiler, which we use already on the bot.

Comment (Michael137) [reply lldb/test/Shell/Process/Windows/msstl_smoke.cpp:7]: Thanks for the additional context David. I'm not super familiar with the Windows test bot setup

Not sure what the best testing strategy here is then. Since the STL formatters in LLDB currently don't support MSVC STL, and we just want to make sure they don't crash, maybe we could even omit tests for this PR until we get proper support for it? Though I don't mind the smoke test added here either tbh, maybe with a FIXME? Just diverges a bit from the rest of our formatter testing.

**Review by Michael137 — APPROVED** [review]

File: lldb/test/Shell/Process/Windows/msstl_smoke.cpp [hunk 4]
```diff
@@ -0,0 +1,57 @@
+// clang-format off
```
Comment (Michael137) [inline lldb/test/Shell/Process/Windows/msstl_smoke.cpp:1]:
```suggestion
// clang-format off
```

**Review by Michael137 — APPROVED** [review]
LGTM (just left small test comments)

**Review by DavidSpickett — CHANGES_REQUESTED** [review]
Request changes just so the remaining comment doesn't get forgotten, the rest Michael has approved and if he's cool with it so am I.

File: lldb/test/Shell/helper/build.py (hunk 3 above)
Comment (Nerixyz) [reply lldb/test/Shell/helper/build.py:686]: Sorry, I should've asked if it's supposed to be a separate PR or commit - opened https://github.com/llvm/llvm-project/pull/141782 now.

**Comment by Michael137** [comment]
@Nerixyz do you need us to merge this for you?

**Comment by Nerixyz** [comment]
> @Nerixyz do you need us to merge this for you?

Yeah, that would be great!

**Comment by Nerixyz** [comment]
I put a summary and some ideas about MSVC STL support in https://github.com/llvm/llvm-project/issues/24834#issuecomment-2923312723.
