### PR TITLE
[Clang][SystemZ] Fix unwanted unsequenced volatile accesses in codegen tests

### LINKED ISSUE #186584: [Clang][SystemZ] Unwanted unsequenced volatile accesses in codegen tests.
When trying to add new Sema check in PR https://github.com/llvm/llvm-project/pull/180955 some tests failed.
As far as I undestand, unsequenced accesses is unwanted in them and warning is correct. As diagnostic say, problem places is ~1500 summary.
Example:
```c++
volatile vector float vf;
vf = vec_sel(vf, vf, vui);
```
List of problematic tests:
Clang :: CodeGen/SystemZ/builtins-systemz-i128.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector-constrained.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector2-constrained.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector2.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector3.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector4.c
Clang :: CodeGen/SystemZ/builtins-systemz-vector5.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector-constrained.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector-error.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector2-constrained.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector2.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector3.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector4.c
Clang :: CodeGen/SystemZ/builtins-systemz-zvector5.c

### PR DESCRIPTION
**Pull request by Seraphimt**
This PR  fix  #186584 

For fix I write one-use program that found and renamed volatile var in funcall. After use tests seems valid(but more verbose) and it's pass. Except
1) builtins-systemz-i128.c autogenerated and I update it with update_cc_test_checks.py
2) builtins-systemz-zvector-constrained.c not pass and I "false" fix it done by analogy other line in this file. What is the best way to do this? @uweigand  Could you help me with it ?

Link to script: https://pastebin.com/QR71We5b

### CODE REVIEW

File: clang/test/CodeGen/SystemZ/builtins-systemz-zvector-constrained.c [hunk 1]
```diff
@@ -67,14 +67,9 @@ void test_core(void) {
   vec_scatter_element(vd, vul, ptrd, 1);
   // CHECK-ASM: vsceg %{{.*}}, 0(%{{.*}},%{{.*}}), 1
 
-  vd = vec_xl(idx, cptrd);
-  // CHECK-ASM: vst
-
```
Comment (uweigand) [inline clang/test/CodeGen/SystemZ/builtins-systemz-zvector-constrained.c:73]: Thanks!  The `vec_xld2` and `vec_xstd2` terms should also go away then.

Comment (Seraphimt) [reply clang/test/CodeGen/SystemZ/builtins-systemz-zvector-constrained.c:73]: Done

**Review by uweigand — APPROVED** [review]
Thanks again.  This LGTM assuming the tests pass.

**Comment by Seraphimt** [comment]
Hi @uweigand. I run 16 modified tests and all pass. Github precommit tests passed too. If this covers what you suggested and there are no further comments, please merge this change.
