### PR TITLE
[CodeGen] Fix cleanup attribute for C89 for-loop init variables

### LINKED ISSUE #154624: __attribute__((cleanup)) on variable declaration in for loop initialization doesn't work correctly in c89/90
clang has an extension that allows variable declarations in initialization statements of for loops before C99. The variable doesn't go out of scope at the end of the for loop.

```
// This compiles without errors with `-std=c89`.
void foo() {
  for (int i = 1; 0;)
    ;
  printf("i=%d\n", i);
}

However, when the declared variable has a cleanup, the cleanup function is run at the end of the for loop rather than at the end of function `foo`.

$ cat test.c
```
#include <stdio.h>

void cleaner(int *a) { printf("run cleanup\n"); }

void foo() {
  for (__attribute__((cleanup(cleaner))) int i = 1; 0;)
    ;
  printf("i=%d\n", i);
}

int main() {
  foo();
  return 0;
}
```

$ clang test.c -std=c89
$ ./a.out
run cleanup
i=1

### PR DESCRIPTION
**Pull request by jongmyeong-choi**
In C89, for-init variables have function scope, so cleanup should occur at function exit, not loop exit. This implements deferred cleanup registration for C89 mode while preserving C99+ behavior.

Fixes #154624

### CODE REVIEW

**Review by efriedma-quic — COMMENTED** [review]
"End of the function" is not really correct. It's still the end of the scope... just the scope in question is different.  This matters if you have, for example, a nested loop.

Probably need to change CodeGenFunction::EmitForStmt to push the scope at the right point.

**Review by efriedma-quic — COMMENTED** [review]
Instead of creating a separate cleanup stack and adding special deferred handling for that cleanup stack, can we just skip creating the scope in the first place?  We have `LexicalScope ForScope(*this, S.getSourceRange());`; can we replace that with something like the following?

```
std::optional<LexicalScope> ForScope;
if (getLangOpts().C99 || getLangOpts().CPlusPlus)
  ForScope.emplace(*this, S.getSourceRange());
```

**Review by efriedma-quic — COMMENTED** [review]
This is roughly what I expected.  But it looks like there are some build failures on the bot.

**Comment by jongmyeong-choi** [comment]
Thank you for your thorough review. I think this approach is much cleaner than the delayed cleanup 👍 Please let me know if you have any additional comments.

File: clang/test/CodeGen/attr-cleanup.c [hunk 1]
```diff
@@ -5,3 +5,26 @@ void g(void) {
   __attribute__((cleanup(f))) void *g;
 }
 
+// Test for cleanup in for-loop initialization (PR #154624)
+// RUN: %clang_cc1 -std=c89 -emit-llvm %s -o - | FileCheck %s --check-prefix=C89
+// RUN: %clang_cc1 -std=c99 -emit-llvm %s -o - | FileCheck %s --check-prefix=C99
```
Comment (efriedma-quic) [inline clang/test/CodeGen/attr-cleanup.c:10]: Move the RUN lines to the beginning of the file, and delete the redundant RUN line.

Maybe try update_cc_test_checks.py and see if you like the result.

Comment (jongmyeong-choi) [reply clang/test/CodeGen/attr-cleanup.c:10]: When you mentioned "delete the redundant RUN line" - were you referring to this line? `// RUN: %clang_cc1 -emit-llvm %s -o %t`

And update_cc_test_checks seems to check the entire IR. I don't have much experience, so I'm wondering if this approach is better. Personally, I feel that localized tests are more intuitive.

Comment (efriedma-quic) [reply clang/test/CodeGen/attr-cleanup.c:10]: Yes, that line.

Your choice on update_cc_test_checks; in this case, I could go either way.  Yes, it checks a bunch of stuff that isn't really relevant here, but the fact that it's automated makes it easier to review and update

**Review by efriedma-quic — APPROVED** [review]
LGTM with one minor comment

**Comment by jongmyeong-choi** [comment]
> Automation is slightly broken, but:
> 
> > ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo.
> > Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account.
> > See [LLVM Developer Policy](https://llvm.org/docs/DeveloperPolicy.html#email-addresses) and [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.

Oh, I just turned off the settings. Sorry for bothering you.
