### PR TITLE
[flang][debug] Set scope of internal functions correctly.

### LINKED ISSUE #96314: [flang][debug] Scope of the contained subroutine is not correct.
If the following program is compiled with flang, the scope of `sub1` is not the parent function that contains it. As a result, when control is stopped in `sub1`, debugger fails to evaluate the variable in parent function (e.g.`i`) .

with gfortran
```
Breakpoint 1, test::sub1 (m=2) at ../../test1.f90:11
11          print *, "sub1: ", m
(gdb) p i
$1 = 2
```
With flang
```
Breakpoint 1, sub1 (m=2) at ../test1.f90:11
11          print *, "sub1: ", m
(gdb) p i
No symbol "i" in current context.
```

```
program test
  integer i
  i = 2
  call sub1(i)
  i = i + 1
  call sub2(5)
  print *, i
contains
  subroutine sub1(m)
    integer m
    print *, "sub1: ", m
  end subroutine sub1
end program test

subroutine sub2(n)
    integer n
    print *, "sub2: ", n
end subroutine sub2
```

### PR DESCRIPTION
**Pull request by abidh**
The functions internal to subroutine should have the scope set to the parent function. This allows a user to evaluate local variables of parent function when control is stopped in the child.

Fixes #96314

### CODE REVIEW

File: flang/lib/Optimizer/Transforms/AddDebugInfo.cpp [hunk 1]
```diff
@@ -299,9 +299,29 @@ void AddDebugInfoPass::runOnOperation() {
...
     unsigned line = getLineFromLoc(l);
-    if (!result.second.modules.empty())
+    if (fir::isInternalProcedure(funcOp)) {
+      // For contained functions, the scope is the parent subroutine.
+      mlir::SymbolRefAttr sym = mlir::cast<mlir::SymbolRefAttr>(
+          funcOp->getAttr(fir::getHostSymbolAttrName()));
+      if (sym) {
+        if (auto func = symbolTable.lookup<mlir::func::FuncOp>(
+                sym.getLeafReference())) {
+          // FIXME: Can there be situation where we process contained function
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/AddDebugInfo.cpp:309]: I believe that the current lowering implementation visits (and creates a function declaration) for the parent before the contained function: https://github.com/llvm/llvm-project/blob/cc2fb58639a6b87f155e6052f5ef2bbe05d5c378/flang/lib/Lower/Bridge.cpp#L488

In MLIR, the module is just an operation with a nested region like any other operation. So I presume the order of functions inside of a module is stable (in the same way that the order of operations nested inside of a function is well defined).

However, I wonder if some current or future pass might erase and re-create functions (thereby possibly shuffling their order). Perhaps all of this could be abstracted out into a function which calls itself recursively if the parent is not yet processed. The recursion will be bounded by the level of function nesting and for the reasons outlined above won't happen at all in most cases.

Comment (abidh) [reply flang/lib/Optimizer/Transforms/AddDebugInfo.cpp]: Thanks for the review. I have moved the function processing in a separate function and now we can make sure that parent is processed before contained subroutine.

**Review by tblah — APPROVED** [review]
LGTM, thanks for the update!
