### PR TITLE
[clang-tidy] Fix false positives in `readability-redundant-inline-specifier`

### LINKED ISSUE #130745: Clang-tidy: False positive readability-redundant-inline-specifier on out-of-line explicitly defaulted constructors
https://godbolt.org/z/Eqf1Er9M5
```cpp
struct awoo {
    ~awoo();
};

inline awoo::~awoo() = default;
```
```
<source>:5:1: warning: function '~awoo' has inline specifier but is implicitly inlined [readability-redundant-inline-specifier]
    5 | inline awoo::~awoo() = default;
      | ^~~~~~
1 warning generated.
```
This warning is wrong: https://eel.is/c++draft/dcl.fct.def.default#3

The out-of-line explicitly-defaulted definition is not the first declaration, so it is not implicitly `inline`.

### PR DESCRIPTION
**Pull request by bjosv**
The out-of-line explicitly-defaulted definition is not the first declaration, so it is not implicitly inline.

Alt. reference:
9.5.2 (3) Explicitly-defaulted functions in [N4950](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4950.pdf).
or https://timsong-cpp.github.io/cppwp/n4861/dcl.fct.def.default#3

Fixes #130745

### CODE REVIEW

File: clang-tools-extra/clang-tidy/readability/RedundantInlineSpecifierCheck.cpp [hunk 1]
```diff
@@ -72,11 +72,13 @@ static SourceLocation getInlineTokenLocation(SourceRange RangeLocation,
 }
 
 void RedundantInlineSpecifierCheck::registerMatchers(MatchFinder *Finder) {
+  const auto IsPartOfRecordDecl = hasAncestor(recordDecl());
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/readability/RedundantInlineSpecifierCheck.cpp:75]: Note: I wonder, maybe hasDeclContext should be used here instead of hasAncestor or just match cxxMethodDecl directly instead of functionDecl.

**Review by PiotrZSL — APPROVED** [review]
LGTM

**Review by HerrCai0907 — APPROVED** [review]

**Review by vbvictor — APPROVED** [review]
