### PR TITLE
[clang][dataflow]Use cast_or_null instead of cast to prevent crash

### LINKED ISSUE #68412: clang-tidy crash
Got a segmentation fault during bugprone-unchecked-optional-access using clang-tidy version 17.0.2.
Full output: [error.log](https://github.com/llvm/llvm-project/files/12831109/error.log)

### PR DESCRIPTION
**Pull request by jcsxky**
`getStorageLocation` may return `nullptr` and this will produce crash when use `cast`, use `dyn_cast_or_null` instead. I test it locally using [FTXUI](https://github.com/ArthurSonzogni/FTXUI) and it may be the cause of issue [issue](https://github.com/llvm/llvm-project/issues/68412), but I am not sure.

### CODE REVIEW

**Review by Xazax-hun — COMMENTED** [review]
The fix looks great to me! On the other hand, we usually try to add a regression test for each of the fixes. Any chance you could get a minimal reproducer from the codebase you are looking at?

**Comment by jcsxky** [comment]
> The fix looks great to me! On the other hand, we usually try to add a regression test for each of the fixes. Any chance you could get a minimal reproducer from the codebase you are looking at?

Thanks for your suggestion! Test case has been added to reproduce this issue.

**Review by HerrCai0907 — COMMENTED** [review]
please update release note also

File: clang/lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp [hunk 1]
```diff
@@ -599,7 +599,7 @@ void transferAssignment(const CXXOperatorCallExpr *E, BoolValue &HasValueVal,
                         LatticeTransferState &State) {
   assert(E->getNumArgs() > 0);
 
-  if (auto *Loc = cast<RecordStorageLocation>(
+  if (auto *Loc = dyn_cast_or_null<RecordStorageLocation>(
```
Comment (HerrCai0907) [inline clang/lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp:602]: If getStorageLocation may return nullptr, it should be cast_or_null. `dyn_cast` means it may be not RecordStorageLocation

**Comment by jcsxky** [comment]
> please update release note also

Although `bugprone-unchecked-optional-access` is used to test this issue, root cause is in `FlowSensitiveAnalysis`. So, I am confused about which file should be updated about release not. Look forward to your suggestion! Thank you.

File: clang/lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp (hunk 1 above)
Comment (jcsxky) [reply clang/lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp]: updated

**Review by PiotrZSL — APPROVED** [review]
LGTM,
When release notes could be nice (clang-tools-extra/doc/ReleaseNotest.rst) with something like: `Improved bugprone-unchecked-optional-acces check to not crash during handling of optional values` or `to not crash i certain situations`  it may also not be so necessary, as this is just very quick fix.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -202,6 +202,10 @@ Changes in existing checks
   <clang-tidy/checks/bugprone/reserved-identifier>` check, so that it does not
   warn on macros starting with underscore and lowercase letter.
 
+- Improved :doc:`bugprone-unchecked-optional-access
+  <clang-tidy/checks/bugprone/unchecked-optional-access>` check, use `cast_or_null`
+  instead `cast` so that it does not crash during handling of optional values.
```
Comment (PiotrZSL) [inline clang-tools-extra/docs/ReleaseNotes.rst:207]: information about cast or cast_or_null is not needed here, this is just info for users who had this check crashed, and decided to disable it, to consider re-enabling it or even testing it again on their projects.

**Comment by jcsxky** [comment]
> LGTM, When release notes could be nice (clang-tools-extra/doc/ReleaseNotest.rst) with something like: `Improved bugprone-unchecked-optional-acces check to not crash during handling of optional values` or `to not crash i certain situations` it may also not be so necessary, as this is just very quick fix.

Release notes have been updated according to your suggestion. Thank you for detail guidance!

**Review by HerrCai0907 — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp [hunk 3]
```diff
@@ -180,3 +180,44 @@ void std_forward_rvalue_ref_safe(absl::optional<int>&& opt) {
...
+template <typename T>
+class vector {
+public:
+  vector() {}
+  T &operator[](unsigned long index) { return data[index]; }
+  bool empty() { return size == 0UL; }
+
+private:
+  T *data;
+  unsigned long size;
```
Comment (ymand) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp:206]: I think simpler would be better here -- please leave out the definitions of the methods and the private data.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp [hunk 4]
```diff
@@ -180,3 +180,44 @@ void std_forward_rvalue_ref_safe(absl::optional<int>&& opt) {
...
+};
+
+} // namespace std
+
+struct LinearGradient {
+  struct Stop {
+    std::optional<float> position;
+  };
+  std::vector<Stop> stops;
```
Comment (ymand) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp:215]: Is it necessary for the repro to have this surrounding struct of `LinearGradient`? Will it crash with just `std::vector<Stop>`?

**Review by ymand — CHANGES_REQUESTED** [review]
Thanks for this fix! Unfortunately, I wasn't able to repro the crash in godbolt: https://godbolt.org/z/s741z5djY.  Can you double check that the check crashes on that example without your fix?

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp [hunk 5]
```diff
@@ -180,3 +180,44 @@ void std_forward_rvalue_ref_safe(absl::optional<int>&& opt) {
...
   std::forward<absl::optional<int>>(opt).value();
 }
+
+namespace std {
+
+template<typename T>
+class optional {
+public:
+	template <typename U>
+  optional& operator=(const U &u){
```
[the remark this answers is not in the document]
Comment (jcsxky) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/unchecked-optional-access.cpp:190]: Using `absl::optional` would produce a compilation error.

```cpp
clang-tools-extra/test/clang-tidy/checkers/bugprone/Inputs/unchecked-optional-access/absl/types/optional.h:32:7: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'int' to 'const optional<float>' for 1st argument
   32 | class optional {
      |       ^~~~~~~~
```

**Comment by jcsxky** [comment]
> Thanks for this fix! Unfortunately, I wasn't able to repro the crash in godbolt: https://godbolt.org/z/s741z5djY. Can you double check that the check crashes on that example without your fix?

The test case is different from that in this patch. Use `float` in `optional`.

**Comment by jcsxky** [comment]
@ymand Could you take a look at this pr?

**Review by ymand — APPROVED** [review]
Thanks, looks good! 

You can submit as is, but if you're up for it, it would actually be better to add the new test case directly to the model's unittests. Something like this test (though just one case is enough -- please put it in a separate TEST_P): https://github.com/llvm/llvm-project/blob/a3a0f59a1e1cb0ac02f06b19f730ea05a6541c96/clang/unittests/Analysis/FlowSensitive/UncheckedOptionalAccessModelTest.cpp#L1966

In general, the lit tests for the clang tidy check only do minimal testing to ensure the check is properly calling the model.

**Comment by jcsxky** [comment]
> Thanks, looks good!
> 
> You can submit as is, but if you're up for it, it would actually be better to add the new test case directly to the model's unittests. Something like this test (though just one case is enough -- please put it in a separate TEST_P):
> 
> https://github.com/llvm/llvm-project/blob/a3a0f59a1e1cb0ac02f06b19f730ea05a6541c96/clang/unittests/Analysis/FlowSensitive/UncheckedOptionalAccessModelTest.cpp#L1966
> 
> In general, the lit tests for the clang tidy check only do minimal testing to ensure the check is properly calling the model.

Thanks for your suggestion! New test case has been added to unittests.
