### PR TITLE
[MLIR][memref] Fix normalization issue in memref.load

### LINKED ISSUE #82675: [MLIR][memref] The Normalizing Memref on removing extra input arguments on`memref.load`
Hi. If you want to normalize the `memref` layout that reduces the dimensionality, the `-normalize-memrefs` pass will work perfectly if there is `affine.load`, but in the case that the operation is `memref.load`, the code fails to reduce the inputs to `memref.load`.

Complier explorer link: https://godbolt.org/z/zYT7jxs9n
```
#map0 = affine_map<(i,k) -> (2*(i mod 2) + (k mod 2) + 4 * (i floordiv 2) + 8*(k floordiv 2))>
#map1 = affine_map<(k,j) -> ((k mod 2) + 2 * (j mod 2) + 8 * (k floordiv 2) + 4*(j floordiv 2))>
#map2 = affine_map<(i,j) -> (4*i+j)>

func.func @test_norm(%arg0 :  memref<4x4xf32,#map2>) -> () {
    %0 = memref.alloc() : memref<4x8xf32,#map0>
    %1 = memref.alloc() : memref<8x4xf32,#map1>
    %2 = memref.alloc() : memref<4x4xf32,#map2>

    %cst = arith.constant 3.0 : f32
    %cst0 = arith.constant 0 : index

    affine.for %i = 0 to 4 {
        affine.for %j = 0 to 8 {
                affine.for %k = 0 to 8 {
                    %a = memref.load %0[%i, %k] : memref<4x8xf32,#map0>

                    %b = memref.load %1[%k, %j] :memref<8x4xf32,#map1>
                    %c = memref.load %2[%i, %j] : memref<4x4xf32,#map2>

                    %3 = arith.mulf %a, %b : f32 
                    %4 = arith.addf %3, %c : f32
                    affine.store %4, %arg0[%i, %j] : memref<4x4xf32,#map2>
            }
        }
    }
    return
}
```

Reproducing the error
```
mlir-opt -normalize-memrefs test.mlir
```

The error
```
# For more information see the output window
MLIR opt (trunk) - 908ms
<source>:16:26: error: 'memref.load' op incorrect number of indices for load, expected 1 but got 2
                    %a = memref.load %0[%i, %k] : memref<4x8xf32,#map0>
                         ^
<source>:16:26: note: see current operation: %5 = "memref.load"(%0, %arg1, %arg3) : (memref<32xf32>, index, index) -> f32
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by DarshanRamakant**
This change will fix the normalization issue with
memref.load when the associated affine map is
reducing the dimension.
This PR fixes #82675

### CODE REVIEW

File: mlir/lib/Dialect/Affine/Utils/Utils.cpp [hunk 1]
```diff
@@ -1146,7 +1147,88 @@ LogicalResult mlir::affine::replaceAllMemRefUsesWith(
       // is set.
       return failure();
     }
-    op->setOperand(memRefOperandPos, newMemRef);
+
+    // Check if it is a memref.load
+    auto memrefLoad = dyn_cast<memref::LoadOp>(op);
```
[the remark this answers is not in the document]
Comment (DarshanRamakant) [reply mlir/lib/Dialect/Affine/Utils/Utils.cpp:1236]: Done

File: mlir/test/Dialect/MemRef/normalize-memrefs.mlir [hunk 2]
```diff
@@ -363,3 +363,33 @@ func.func @memref_with_strided_offset(%arg0: tensor<128x512xf32>, %arg1: index,
...
+  // CHECK-NOT:  memref<4x8xf32>
+  // CHECK-NOT:  memref<8x4xf32>
+  // CHECK-NOT:  memref<4x4xf32>
+  %cst = arith.constant 3.0 : f32
+  %cst0 = arith.constant 0 : index
+  affine.for %i = 0 to 4 {
+    affine.for %j = 0 to 8 {
+      affine.for %k = 0 to 8 {
+        // CHECK: affine.apply #map{{.*}}(%{{.*}}, %{{.*}})
+        // CHECK: memref.load %alloc[%{{.*}}] : memref<32xf32>
```
Comment (Lewuathe) [inline mlir/test/Dialect/MemRef/normalize-memrefs.mlir:384]: We can know the normalization does not fail with this test. But it would be better to check the calculation of the affine_map is kept precisely as well as we do with `affine.load` if possible.

How about checking `affine.apply` is calling the same logic as follows to ensure the consistency?

```
          %0 = affine.load %alloc[%arg1 * 2 + %arg3 + (%arg3 floordiv 2) * 6] : memref<32xf32>
          %1 = affine.load %alloc_0[%arg3 + %arg2 * 2 + (%arg3 floordiv 2) * 6] : memref<32xf32>
          %2 = affine.load %alloc_1[%arg1 * 4 + %arg2] : memref<16xf32>
```

https://godbolt.org/z/bPhYGrhKa

**Review by Lewuathe — COMMENTED** [review]
I have left one comment to improve the test coverage. If that point is improved, I think it looks good to me overall.

File: mlir/test/Dialect/MemRef/normalize-memrefs.mlir (hunk 2 above)
Comment (DarshanRamakant) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir:384]: The output IR for the test after the transform will be like below :

Comment (DarshanRamakant) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: Made the test more stricter

Comment (Lewuathe) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: Sorry for the late response. What I meant was to match the affine map logic itself. So it would be great if we can match the map names.

Is it possible to match with the code something like this? It checks the affine map correspondense by its name. 

```mlir
#[[$MAP1:#map[0-9]+]] = affine_map<(d0, d1) -> ((d0 mod 2) * 2 + d1 mod 2 + (d0 floordiv 2) * 4 + (d1 floordiv 2) * 8)>

...

// CHECK: %[[INDEX0:.*]] = affine.apply #[[$MAP1]]{{.*}}(%{{.*}}, %{{.*}})

```

Comment (DarshanRamakant) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: I have already tried to match like this with the below code :

Comment (Lewuathe) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: > I guess this is because of the "CHECK-LABEL" match previously, which may start scan after this match.

Ah, I see. That makes sense.

Comment (Lewuathe) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: I experimented to make the test pass somehow.

I found we could put the affine map definition on top of the test file and use them in the function after the `CHECK-LABEL`. That's because the affine map is defined at the top of the module, I guess. 

```
// CHECK-DAG: #[[$REDUCE_MAP1:.*]] = affine_map<(d0, d1) -> ((d0 mod 2) * 2 + d1 mod 2 + (d0 floordiv 2) * 4 + (d1 floordiv 2) * 8)>
// CHECK-DAG: #[[$REDUCE_MAP2:.*]] = affine_map<(d0, d1) -> (d0 mod 2 + (d1 mod 2) * 2 + (d0 floordiv 2) * 8 + (d1 floordiv 2) * 4)>
// CHECK-DAG: #[[$REDUCE_MAP3:.*]] = affine_map<(d0, d1) -> (d0 * 4 + d1)>

...

// CHECK-LABEL: func @memref_load_with_reduction_map
func.func @memref_load_with_reduction_map(%arg0 :  memref<4x4xf32,#map2>) -> () {
  %0 = memref.alloc() : memref<4x8xf32,#map0>
  %1 = memref.alloc() : memref<8x4xf32,#map1>
  %2 = memref.alloc() : memref<4x4xf32,#map2>
  // CHECK-NOT:  memref<4x8xf32>
  // CHECK-NOT:  memref<8x4xf32>
  // CHECK-NOT:  memref<4x4xf32>
  %cst = arith.constant 3.0 : f32
  %cst0 = arith.constant 0 : index
  affine.for %i = 0 to 4 {
    affine.for %j = 0 to 8 {
      affine.for %k = 0 to 8 {
        // CHECK: %[[INDEX0:.*]] = affine.apply #[[$REDUCE_MAP1]](%{{.*}}, %{{.*}})
        // CHECK: memref.load %alloc[%[[INDEX0]]] : memref<32xf32>
        %a = memref.load %0[%i, %k] : memref<4x8xf32,#map0>
        // CHECK: %[[INDEX1:.*]] = affine.apply #[[$REDUCE_MAP2]](%{{.*}}, %{{.*}})
        // CHECK: memref.load %alloc_0[%[[INDEX1]]] : memref<32xf32>
        %b = memref.load %1[%k, %j] :memref<8x4xf32,#map1>
        // CHECK: %[[INDEX2:.*]] = affine.apply #[[$REDUCE_MAP3]](%{{.*}}, %{{.*}})
        // CHECK: memref.load %alloc_1[%[[INDEX2]]] : memref<16xf32>
        %c = memref.load %2[%i, %j] : memref<4x4xf32,#map2>
        %3 = arith.mulf %a, %b : f32
        %4 = arith.addf %3, %c : f32
        affine.store %4, %arg0[%i, %j] : memref<4x4xf32,#map2>
      }
    }
  }
  return
}
```

Comment (Lewuathe) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: Here is the change I tried to check the affine map definition in the spec. 

https://github.com/llvm/llvm-project/commit/aa7787923f1a52940fe08002ba464bce592e03e5

Comment (DarshanRamakant) [reply mlir/test/Dialect/MemRef/normalize-memrefs.mlir]: Thanks for taking time and giving me this fix ! I could also verify that this passes. I have modified my patch with the change now. Thanks again.

**Review by Lewuathe — APPROVED** [review]
Thank you for updating the patch accordingly. It looks good to me now!

**Comment by DarshanRamakant** [comment]
> Thank you for updating the patch accordingly. It looks good to me now!

Thanks @Lewuathe . Can you please merge this PR ?

**Comment by Lewuathe** [comment]
@DarshanRamakant Merged. Thank for creating the patch to fix this issue!
