### PR TITLE
[ELF][Objcopy] Dont corrupt symbol table when `--update-section` is called for ELF files

### LINKED ISSUE #168060: [ELF][Objcopy] unable to locate the extended symbol index table after update-section
## Problem:
I'm trying to insert some data into my ELF file. To achieve this, I create a const char array with the attribute `__attribute__((section(".rodata.holder")))`. Then, I try to insert the data into the object file using `llvm-objcopy --update-section`. However, during the linking process, I get an error from the linker:

```text
ld.lld: error: found an extended symbol index (5), but unable to locate the extended symbol index table
```

### Step 1 : Download and build llvm 21.1.5 tools
```bash
git clone https://github.com/llvm/llvm-project.git && cd llvm-project && git checkout llvmorg-21.1.5

mkdir bld && cd bld
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="llvm;clang;lld" ../llvm
ninja clang lld llvm-objcopy
```

### Step 2 : Put broken sources into build directory
Source examples:
```cpp
// main.cpp
int External(const char*, const char*, const char*) { return 0; }
int main() { return 0; }
```

```cpp
//lib.cpp
static __attribute__((section(".rodata.holder"))) const char resource_holder[0x1000] = {0};

int External(const char*, const char*, const char*);

static const int REG1 = External("Range1", resource_holder + 128 * 0, resource_holder + 128 * 1);
static const int REG2 = External("Range2", resource_holder + 128 * 1, resource_holder + 128 * 2);
static const int REG3 = External("Range3", resource_holder + 128 * 2, resource_holder + 128 * 3);
```

Generate some random binary data:
```bash
head -c 4k /dev/urandom > data.bin
```

### Step 3 : Try to compile
```
./bin/clang++ lib.cpp -c -O0 -g0 -o lib.o

./bin/llvm-objcopy lib.o --update-section=.rodata.holder=data.bin

./bin/clang++ lib.o main.cpp -o a.out -fuse-ld=lld --ld-path=./bin/ld.lld
# ld.lld: error: found an extended symbol index (5), but unable to locate the extended symbol index table
```

# Possible bug(?) explanation
I've spent some time debugging. It seems the problem is related to the code of the `Object::updateSectionData` function:
https://github.com/llvm/llvm-project/blob/3b83e7fa4ec18991a25d49741418e2b3d325692c/llvm/lib/ObjCopy/ELF/ELFObject.cpp#L2160-L2182

If we create a new section, then there will not be any calls to `Object::replaceSections`:
https://github.com/llvm/llvm-project/blob/3b83e7fa4ec18991a25d49741418e2b3d325692c/llvm/lib/ObjCopy/ELF/ELFObject.cpp#L2173-L2179

So, the symbols were not updated with the appropriate section index and an error occurred.

Could anyone tell me is it correct behaviour or we should fix it?

### PR DESCRIPTION
**Pull request by Nechda**
This PR fixes #168060

### CODE REVIEW

**Comment by Nechda** [comment]
@jh7370 Could you please review this PR or assign appropriate people to it? I don't have enough permissions to assign reviewers myself.

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp [hunk 1]
```diff
@@ -2171,7 +2171,14 @@ Error Object::updateSectionData(SecPtr &Sec, ArrayRef<uint8_t> Data) {
                              Data.size(), Sec->Name.c_str(), Sec->Size);
 
   if (!Sec->ParentSegment) {
-    Sec = std::make_unique<OwnedDataSection>(*Sec, Data);
+    // Be careful: the "Sec" refers to an item in a std::vector,
+    // so any changes to the std::vector could invalidate this reference.
+    // To avoid possible memory-related issues, save raw pointers.
+    auto Replaced = Sec.get();
+    auto Modified = &addSection<OwnedDataSection>(*Sec, Data);
```
Comment (jh7370) [inline llvm/lib/ObjCopy/ELF/ELFObject.cpp]: If I'm not mistaken, won't this end up with a section containing the new contents as well as a section with the old contents in the object?

**Review by jh7370 — COMMENTED** [review]
Rather than a gtest test, this is probably better off being tested by a lit test that runs the whole llvm-objcopy process. There are plenty of examples at llvm/test/tools/llvm-objcopy/ELF. You can take the suggested test input I provided in the issue, run llvm-objcopy --update-section and then use llvm-readobj to dump the symbols to show that the section indexes are correct. You should probably also show the section list and contents are correct still too. There's no need to use a sanitizer - the issues with linking you saw in the ticket were caused by the corrupted symbol table that your new test will spot without the fix.

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp (hunk 1 above)
Comment (Nechda) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp]: You are right, the `addSection` function does add one more section with the same name. However, the function `replaceSections`, which is called two lines later, removes the old section and replaces its pointer with the new one.

https://github.com/llvm/llvm-project/blob/830ef4e4e2d0f181ed1cfacbc3daacb2555ff9e4/llvm/lib/ObjCopy/ELF/ELFObject.cpp#L2273-L2282

Comment (jh7370) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp]: You're right, thanks.

I think the above comment about the `std::vector` could be reworked a bit to mention that `addSection` and `replaceSections` and and remove the respective sections, to make this clearer.

**Comment by Nechda** [comment]
I apologize for my sudden disappearance. I was sick.

> There's no need to use a sanitizer - the issues with linking you saw in the ticket were caused by the corrupted symbol table that your new test will spot without the fix.

There is a problem. If I don't build llvm-objcopy with sanitizers, then the simple test case that I have provided in this PR does not corrupt the symbol table at all (this is true for my environment, you may get different result).

This is just a coincidence, and I think that if I change the allocator, compiler, or libcxx, the test will fail more often. In summary, I can move the test case from gtest to lit sute, but I'm not sure if lit suites run with sanitizers, so the test might become flaky.

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp (hunk 1 above)
Comment (Nechda) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp]: I have completely rewritten the comment. I hope this new version of the text is more clear.

Resolve this thread if you are agree.

**Comment by yonghong-song** [comment]
linux kernel bpf selftest also hit this issue. See
   https://lore.kernel.org/bpf/20251224005752.201911-1-ihor.solodrai@linux.dev/
This patch can fix the issue.

If this patch is accepted, is it possible that this fix can be backported to llvm21?

File: llvm/test/tools/llvm-objcopy/ELF/update-section-dont-corrupt-symtab.test [hunk 2]
```diff
@@ -0,0 +1,120 @@
+# REQUIRES: x86-registered-target
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/ELF/update-section-dont-corrupt-symtab.test]: 1. I think the test name might be better as `update-section-not-in-segment.test`, because that is the code path that is currently broken. The corrupt symbol table is the symptom, rather than the behaviour being tested.

2. I'm not sure I follow why your test is so elaborate, when, at least for a basic build on Windows, I can see the failure with the input I posted in the issue. The following test looks like it should be sufficient:

```
## Show that when updating a section not in a segment, symbols still correctly
## refer to the updated section.

# RUN: echo -n 11223344 > %t.data
# RUN: yaml2obj %s -o %t.in
# RUN: llvm-objcopy --update-section=.foo=%t.data %t.in %t.out
# RUN: llvm-readelf --symbols %t.out | FileCheck %s

# CHECK: Num: {{.*}} Ndx Name
# CHECK:   1: {{.*}}   1 sym

--- !ELF
FileHeader:
  Class: ELFCLASS64
  Data:  ELFDATA2LSB
  Type:  ET_REL
Sections:
  - Name: .foo
    Type: SHT_PROGBITS
    Size: 0x10
Symbols:
  - Name: sym
    Type: STT_FUNC
    Value: 0x1
    Section: .foo
```
Without your patch, this test fails, since the section index referred to by the `sym` symbol is bogus (the section it references in memory doesn't have a valid index). Of course, it's possible this won't always be the case (since the memory might conveniently have the "right" value). However, as it fails at least under some configurations, it's sufficient for the purposes we have. Furthermore, there are build bots that run the lit test suite with sanitizers enabled and this test should definitely fail under this configuration.

If you want to be a little more robust/clear, you could also dump the sections and show that the .foo section index is the same as the section index referred to by the symbol entry.

**Review by jh7370 — COMMENTED** [review]
In general, please don't force push to PRs under active review: it's against LLVM policy, because it trashes the review history (the commit hashes comments are made against are no longer the ones in the PR and the diff versus last state no longer works properly). Instead, use merges from main, if a rebase is required.

File: llvm/test/tools/llvm-objcopy/ELF/update-section-dont-corrupt-symtab.test (hunk 2 above)
Comment (Nechda) [reply llvm/test/tools/llvm-objcopy/ELF/update-section-dont-corrupt-symtab.test]: > Furthermore, there are build bots that run the lit test suite with sanitizers enabled and this test should definitely fail under this configuration.

Then I'll use a simple version of the test.

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp [hunk 3]
```diff
@@ -2171,7 +2171,17 @@ Error Object::updateSectionData(SecPtr &Sec, ArrayRef<uint8_t> Data) {
...
+    // Calling the function addSection adds a new element to this std::vector,
+    // which may cause a reallocation and lead to dangling references.
+    // To avoid possible memory-related issues, you should save a raw pointer.
+    SectionBase *Replaced = Sec.get();
+    SectionBase *Modified = &addSection<OwnedDataSection>(*Sec, Data);
+    // We also don't need to additionally remove the "Replaced" section,
+    // as this removal will be handled during the replaceSections call.
+    DenseMap<SectionBase *, SectionBase *> Replacements{{Replaced, Modified}};
+    if (auto err = replaceSections(Replacements))
+      return err;
```
[the remark this answers is not in the document]
Comment (Nechda) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp]: Fixed

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp [hunk 4]
```diff
@@ -2171,23 +2171,18 @@ Error Object::updateSectionData(SecPtr &Sec, ArrayRef<uint8_t> Data) {
                              Data.size(), Sec->Name.c_str(), Sec->Size);
 
   if (!Sec->ParentSegment) {
-    // Be careful: the "Sec" refers to an element in a std::vector.
-    // Calling the function addSection adds a new element to this std::vector,
-    // which may cause a reallocation and lead to dangling references.
-    // To avoid possible memory-related issues, you should save a raw pointer.
+    // addSection modifies the container that Sec is stored in, potentially
+    // invalidating the Sec reference. We obtain the raw pointer Sec owns before
+    // calling addSection, so that it can be safely passed into replaceSections.
```
Comment (jh7370) [inline llvm/lib/ObjCopy/ELF/ELFObject.cpp]: You've lost the bit about `replaceSections` deleting the old section.

**Review by jh7370 — COMMENTED** [review]
Mostly looks good.

Just to check, have you run the new test with sanitizers enabled?

**Review by jh7370 — APPROVED** [review]
LGTM. Do you need someone to merge it for you?
