### PR TITLE
[clang-tidy] `readability-simplify-boolean-expr` avoid to warn expression expand from macro when ``IgnoreMacro`` option is enabled.

### LINKED ISSUE #91487: [clang-tidy]: readability-simplify-boolean-expr wants to use DeMorgan's theorem on macros despite IgnoreMacros
clang-tidy produces a `readability-simplify-boolean-expr` warning to simplify expressions with macros using DeMorgan's theorem despite `readability-simplify-boolean-expr.IgnoreMacros` being set to `true`.

Simplified test case:
```
#define is_a_favorite_number(_i) (_i == 42 || _i == 3 || _i == 1000000)

bool UseNumber(int i) { return i >= 0 && !is_a_favorite_number(i); }
```

.clang-tidy config:
```
---
Checks:
    '-*,
    readability-simplify-boolean-expr
    '
CheckOptions:
    - key:      readability-simplify-boolean-expr.IgnoreMacros
      value:    true
```

Produces the following:
```
1 warning generated.
test_bool_simplification.cpp:4:42: error: boolean expression can be simplified by DeMorgan's theorem [readability-simplify-boolean-expr,-warnings-as-errors]
    4 | bool UseNumber(int i) { return i >= 0 && !is_a_favorite_number(i); }
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #91487

### CODE REVIEW

File: clang-tools-extra/clang-tidy/readability/SimplifyBooleanExprCheck.cpp [hunk 1]
```diff
@@ -513,17 +513,25 @@ class SimplifyBooleanExprCheck::Visitor : public RecursiveASTVisitor<Visitor> {
...
+    return !Check->canBeBypassed(E) && isa<UnaryOperator>(E) &&
            cast<UnaryOperator>(E)->getOpcode() == UO_LNot;
   }
 
+  static bool isExpectedBinaryOp(SimplifyBooleanExprCheck *Check,
+                                 const Expr *E) {
+    const auto *BinaryOp = dyn_cast<BinaryOperator>(E);
+    return !Check->canBeBypassed(E) && BinaryOp && BinaryOp->isLogicalOp() &&
+           BinaryOp->getType()->isBooleanType();
+  }
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/readability/SimplifyBooleanExprCheck.cpp:527]: just remove static, and then you will have access to Check class member.

**Review by PiotrZSL — APPROVED** [review]
Just nits.
