### PR TITLE
[compiler-rt][test] Rewrote test to remove curly braces

### LINKED ISSUE #102382: [llvm-lit] lit internal shell failing to parse and execute curly brace syntax
lit’s internal shell cannot recognize and execute the `{}` syntax, which is used in tests across lld and compiler-rt.

Example error message:

```
FAIL: lld :: ELF/error-handling-script-linux.test (9 of 2939)
******************** TEST 'lld :: ELF/error-handling-script-linux.test' FAILED ********************
Exit Code: 127

Command Output (stdout):
--

# RUN: at line 21
{ echo 'a_: ret'; echo 'bar: movl a(%rip), %eax' ; } | /usr/local/google/home/connieyzhu/llvm-project/build/bin/llvm-mc -filetype=obj -triple=x86_64 - -o /usr/local/google/home/connieyzhu/llvm-project/build/tools/lld/test/ELF/Output/error-handling-script-linux.test.tmp3.o
# executed command: '{' echo 'a_: ret'
# .---command stderr------------
# | '{': command not found
# `-----------------------------
# error: command failed with exit status: 127
```

### PR DESCRIPTION
**Pull request by connieyzhu**
This patch removes curly braces from a test, as lit's internal shell implementation does not support curly brace syntax.

Fixes https://github.com/llvm/llvm-project/issues/102382.

### CODE REVIEW

File: compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // RUN: %clangxx_asan -xc++ -shared -fPIC -o %t.so - < %s
 // RUN: %clang_asan %s -o %t.out -ldl
 //
-// RUN: { env ASAN_OPTIONS=verbosity=1 %t.out %t.so || : ; } 2>&1 | FileCheck %s
+// RUN: env ASAN_OPTIONS=verbosity=1 %t.out %t.so 2>&1 | FileCheck %s || :
```
Comment (ilovepi) [inline compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c:4]: I don't think these are equivalent, and we probably don't want to change the return code for `FileCheck`, since we still want CHECK lines to trigger a failure. It seems that this program will always return a non-zero exit code, so maybe we can just use `not` instead of `|| :`? Alternatively, we could make the program return `0`, but I'm guessing the author were worried about some optimization preventing the test from working correctly, and I'm not familar enough w/ this test to know if that would be problematic.

File: compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c [hunk 2]
```diff
@@ -1,7 +1,10 @@
 // RUN: %clangxx_asan -xc++ -shared -fPIC -o %t.so - < %s
 // RUN: %clang_asan %s -o %t.out -ldl
 //
-// RUN: { env ASAN_OPTIONS=verbosity=1 %t.out %t.so || : ; } 2>&1 | FileCheck %s
+// The program can potentially return a non-zero exit code, so use || : to
+// ensure command returns true
+// RUN: env ASAN_OPTIONS=verbosity=1 %t.out %t.so &> %t_env || :
```
Comment (arichardson) [inline compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c:6]: The initial version of this commit used `not`: https://github.com/llvm/llvm-project/commit/cbd28cd05bb11e9d76d71c6cc2d38d89dbb1fe1a but for some reason that was changed in https://github.com/llvm/llvm-project/commit/a30a4a35ecbd2ebff79de8a193e7045b17da3ff5 

Maybe removing `not` was used to work around the missing `UNSUPPORTED:` that was only added in https://github.com/llvm/llvm-project/commit/307daa71a8f0bb258d4c89d5bad2579f468162ca CC: @serge-sans-paille @hahnjo 

I'd be tempted to restore this to using `not` instead of `|| :` and see if the builders are happy.

Comment (connieyzhu) [reply compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c]: I replaced `||:` with `not` in my most recent commit. The tests are passing when I run things locally - still need to wait for builders though.

File: compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c [hunk 3]
```diff
@@ -1,7 +1,9 @@
 // RUN: %clangxx_asan -xc++ -shared -fPIC -o %t.so - < %s
 // RUN: %clang_asan %s -o %t.out -ldl
 //
-// RUN: { env ASAN_OPTIONS=verbosity=1 %t.out %t.so || : ; } 2>&1 | FileCheck %s
+// The program can potentially return a non-zero exit code, so use || : to
```
Comment (arichardson) [inline compiler-rt/test/asan/TestCases/Linux/dlopen-mixed-c-cxx.c:4]: Stale comment here.

**Review by arichardson — APPROVED** [review]
Comment needs updating otherwise LGTM

**Review by vitalybuka — APPROVED** [review]
