### PR TITLE
[Clang] Fix pack indexing profiling

### LINKED ISSUE #138255: Pack indexing specifier can't be used with templated function declaration inside a class
Example:
```cpp
#include <concepts>

template<typename... Ts>
using front_t = Ts...[0];

struct Foo {
    template<typename... Ts>
         requires std::same_as<Ts...[0], int>
    static auto buggy() -> void;

    template<typename... Ts>
        requires std::same_as<front_t<Ts...>, int>
    static auto working() -> void;
};

template<typename... Ts>
    requires std::same_as<Ts...[0], int>
auto Foo::buggy() -> void {}

template<typename... Ts>
    requires std::same_as<front_t<Ts...>, int>
auto Foo::working() -> void {}

int main() {
    Foo::buggy<int>();
    Foo::working<int>();
}
```
```
<source>:18:11: error: out-of-line definition of 'buggy' does not match any declaration in 'Foo'
   18 | auto Foo::buggy() -> void {}
      |           ^~~~~
<source>:6:8: note: Foo defined here
    6 | struct Foo {
      |        ^~~
1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by cor3ntin**
When profiling a pack indexing that has been partially substituted, we should profile the expansions, rather than the pattern itseld

This is a better approach to #139057

This mirrors the fix done for SizeOfPackExpr in #124533

Fixes #138255

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
I like this better too.

File: clang/include/clang/AST/ExprCXX.h [hunk 1]
```diff
@@ -4549,6 +4549,10 @@ class PackIndexingExpr final
 
   bool isFullySubstituted() const { return FullySubstituted; }
 
+  bool isPartiallySubstituted() const {
```
Comment (zyn0217) [inline clang/include/clang/AST/ExprCXX.h:4552]: Please document the difference with FullySubstituted

**Review by zyn0217 — APPROVED** [review]
Thanks for the iteration!

File: clang/include/clang/AST/ExprCXX.h (hunk 1 above)
Comment (cor3ntin) [reply clang/include/clang/AST/ExprCXX.h]: I got rid of it entierly, it's cleaner

File: clang/lib/AST/StmtProfile.cpp [hunk 2]
```diff
@@ -2291,9 +2291,15 @@ void StmtProfiler::VisitSizeOfPackExpr(const SizeOfPackExpr *S) {
...
-  VisitExpr(E->getPackIdExpression());
   VisitExpr(E->getIndexExpr());
+
+  if (E->expandsToEmptyPack() || E->getExpressions().size() != 0) {
+    ID.AddInteger(E->getExpressions().size());
+    for (const Expr *Sub : E->getExpressions())
+      Visit(Sub);
+  } else {
+    VisitExpr(E->getPackIdExpression());
+  }
```
Comment (mizvekov) [inline clang/lib/AST/StmtProfile.cpp:2302]: These `VisitExpr` calls are not right, this only profiles the expression kind and it's children, skipping it's other properties.

These should have been plain Visit calls.

The other issue is that this skips `VisitExpr(E)` entirely, which doesn't record this expressions kind in the profile. I believe this can lead to false matches.

`VisitExpr(E)` also would visit this node's children, which you do manually only some of them afterwards.

I believe it would be simpler and more consistent with how other expressions behave if `PackIndexingExpr` would just report the correct set of children, and then this profiling function would just be a single `VisitExpr(E);` call.

File: clang/test/SemaTemplate/concepts-out-of-line-def.cpp [hunk 3]
```diff
@@ -779,3 +781,75 @@ template <typename T>
...
+template <typename...> struct TplClass {
+  template <int... Ts>
+  requires C<Ts...[0]>
+  static auto buggy() -> void;
+};
+
+template <>
+template <int... Ts>
+requires C<Ts...[0]>
+auto TplClass<int>::buggy() -> void {}
```
Comment (mizvekov) [inline clang/test/SemaTemplate/concepts-out-of-line-def.cpp:854]: This test case (and possibly similar others above) should not have worked, because of an unrelated bug in `getTemplateInstantiationArgs`.

It only works because of the aforementioned bug in profiling.

Example: https://compiler-explorer.com/z/vK715Phvn
```C++
template <int... T> concept C = true;

template <int...> struct TplClass {
  template <int... Ts, int... Us>
  requires C<Ts...[0]>
  static auto buggy() -> void;
};

template <>
template <int... Ts, int... Us>
requires C<Us...[0]>
auto TplClass<0>::buggy() -> void {}
```

You can see it accepts the out-of-line definition even with the template parameters swapped around (Ts vs Us).
That's because with the profiling issue, the depth and index of the template parameters in the DeclRefExpr are not recorded.

The fact this was not accepted has nothing to do with PackIndex feature at all.
Example: https://compiler-explorer.com/z/Yhv1dcEK5
```C++
template <int T> concept C = true;

template <int> struct TplClass {
  template <int Ts>
  requires C<Ts>
  static auto buggy() -> void;
};

template <>
template <int Ts>
requires C<Ts>
auto TplClass<0>::buggy() -> void {}
```

here you can see the simple case where it's just a simple NTTP, and it doesn't work...

There is a bug in `getInjectedTemplateArgs` where the instantiation args for transforming the out-of-class definition is incomplete, leading to the NTTP references not being transformed and a depth mismatch ocurring.

**Review by mizvekov — COMMENTED** [review]
FYI this introduces a bug that is blocking me in another patch.
