### PR TITLE
[Clang] Evaluate dependent indexes of pack indexing in a constant context

### LINKED ISSUE #105900: [Clang] Error on pack indexing in return type
Consider (https://godbolt.org/z/3ThcG9r9d):
```c++
template <typename... opts>
struct temp  {
    template <unsigned idx>
    static constexpr __SIZE_TYPE__ get_index() { return idx; }

    template <unsigned s>
    static auto x() -> opts...[get_index<s>()] {}
};
```

Attempting to call `x` like this
```c++
temp<void>::x<0>();
```
fails with the following (rather weird) error:
```
<source>:11:5: error: no matching function for call to 'x'
   11 |     temp<void>::x<0>(); // Error
      |     ^~~~~~~~~~~~~~~~
<source>:7:17: note: candidate template ignored: substitution failure [with s = 0]: array size is not a constant expression
    7 |     static auto x() -> opts...[get_index<s>()] {}
      |                 ^              ~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by cor3ntin**
Fixes #105900

### CODE REVIEW

File: clang/test/SemaCXX/cxx2c-pack-indexing.cpp [hunk 1]
```diff
@@ -231,3 +231,30 @@ struct type_info {
...
+    template <unsigned idx>
+    static constexpr __SIZE_TYPE__ get_index() { return idx; }
+
+    template <unsigned s>
+    static auto x() -> decltype(opts...[get_index<s>()]) {return 0;}
+};
+
+void f() {
+    types<void>::x<0>(); // Error
+    vars<0>::x<0>(); // Error
```
Comment (zyn0217) [inline clang/test/SemaCXX/cxx2c-pack-indexing.cpp:258]:
```suggestion
    types<void>::x<0>();
    vars<0>::x<0>();
```

**Review by zyn0217 — APPROVED** [review]
Thanks!
