### PR TITLE
[SystemZ] Fix compile time regression in adjustInliningThreshold().

### LINKED ISSUE #134714: [SystemZ] Large compile time regression in `SystemZTTIImpl::adjustInliningThreshold()`
#106058 appears to have caused a large compile time regression in LLVM 20. [zig-bootstrap](https://github.com/ziglang/zig-bootstrap) used to be able to compile and link the `zig` binary for `s390x-linux-(gnu,musl)` in a matter of minutes when we were on LLVM 19. Now on LLVM 20, I decided to cancel the build after it had been running for about an hour.

Some investigation shows that a *lot* of time is being spent in `SystemZTTIImpl::adjustInliningThreshold()`, in particular in this section:

https://github.com/llvm/llvm-project/blob/c1c0d551bae4e4f4ed13fcd9264834a2713fe44b/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp#L98-L105

Some thoughts:

* A module can have lots of globals.
    * This doesn't appear to be the problem here, however.
* A global can have lots of users (think common deduplicated/merged constant values).
    * This seems to be the case here, though I couldn't determine exactly how many users we're talking about because I was using a `RelWithDebInfo` build of LLVM where `p Global.users()` was optimized out.
        * Building a `Debug` compiler as I file this to hopefully find out...
* `std::set` seems less than ideal compared to `std::unordered_set` here.
    * I tried changing this to `std::unordered_set` but it didn't seem to have too much of an impact. Still seems desirable to do, though.

In general, all of this seems like a lot of work to be doing on ~every inlining decision.

cc @JonPsson1 @uweigand

### PR DESCRIPTION
**Pull request by JonPsson1**
Instead of always iterating over all GlobalVariable:s in the Module to find the case where both Caller and Callee is using the same GV heavily, first scan Callee (only if less than 200 instructions) for all GVs used more than 10 times, and then do the counting for the Caller for just those relevant GVs.

The limit of 200 instructions makes sense as this aims to inline a relatively small function using a GV +10 times. This limit changed only 7 files across 3 SPEC benchmarks . Previously only perlbench performance was affected, and perl is not among these 3 changed benchmarks, so there should not be any difference to consider here. SPEC runs seem to confirm this ("full/home-dir").

Compile time across SPEC shows no difference compared to main. It however resolves the compile time problem with zig where it is on main (compared to removing the heuristic) a 380% increase, but with this change only 2.4% increase (total user compile time with opt).

Fixes #134714.

### CODE REVIEW

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 1]
```diff
@@ -92,29 +91,38 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
-  for (const GlobalVariable &Global : M->globals())
-    for (const User *U : Global.users())
-      if (const Instruction *User = dyn_cast<Instruction>(U)) {
-        if (User->getParent()->getParent() == Callee)
-          CalleeGlobals.insert(&Global);
-        if (User->getParent()->getParent() == Caller)
-          CallerGlobals.insert(&Global);
+  // Give bonus for globals used much in both caller and a relatively small
+  // callee.
+  if (Callee->getInstructionCount() < 200) {
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:96]: getInstructionCount() is going to iterate over the whole function to determine the instruction count. It's usually better to always do the analysis and just bail out if it inspects too many instructions.

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 2]
```diff
@@ -92,29 +91,38 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
+    std::map<const Value *, unsigned> Ptr2NumUses;
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:97]: Use SmallDenseMap instead.

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 3]
```diff
@@ -92,29 +91,38 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
+    for (auto &BB : *Callee)
+      for (auto &I : BB) {
+        if (const auto *SI = dyn_cast<StoreInst>(&I)) {
+          if (!SI->isVolatile())
+            Ptr2NumUses[SI->getPointerOperand()]++;
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:102]: It would be better to only count global uses, which will reduce the size of the map a lot.

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 4]
```diff
@@ -92,29 +91,38 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
+        } else if (const auto *LI = dyn_cast<LoadInst>(&I)) {
+          if (!LI->isVolatile())
+            Ptr2NumUses[LI->getPointerOperand()]++;
+        } else if (const auto *GEP = dyn_cast<GetElementPtrInst>(&I)) {
+          unsigned NumStores = 0, NumLoads = 0;
+          countNumMemAccesses(GEP, NumStores, NumLoads, Callee);
+          Ptr2NumUses[GEP->getPointerOperand()] += NumLoads + NumStores;
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:109]: It seems like nothing actually cares about loads and stores separately? Make things simpler by having countNumMemAccesses return the total count?

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 5]
```diff
@@ -92,29 +91,38 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
-      unsigned CalleeStores = 0, CalleeLoads = 0;
-      unsigned CallerStores = 0, CallerLoads = 0;
-      countNumMemAccesses(GV, CalleeStores, CalleeLoads, Callee);
-      countNumMemAccesses(GV, CallerStores, CallerLoads, Caller);
-      if ((CalleeStores + CalleeLoads) > 10 &&
-          (CallerStores + CallerLoads) > 10) {
-        Bonus = 1000;
-        break;
+
+    for (auto I : Ptr2NumUses) {
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:113]:
```suggestion
    for (auto [Ptr, NumCalleeUses] : Ptr2NumUses) {
```

**Comment by JonPsson1** [comment]
@alexrp Does this help on your side as well?

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp (hunk 1 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp]: ok, using a counter instead.

**Comment by JonPsson1** [comment]
@nikic thanks for review! I followed your suggestions and indeed see a further speedup: zig.bc is now regressing <0.5% with this heuristic (compared to removing it), so nearly gone. And average over SPEC for InlinerPass is now 2% better than with main (1.46% vs 1.49%).

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 6]
```diff
@@ -92,29 +91,41 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
-        if (User->getParent()->getParent() == Caller)
-          CallerGlobals.insert(&Global);
+  // Give bonus for globals used much in both caller and a relatively small
+  // callee.
+  unsigned InstrCount = 0;
+  SmallDenseMap<const Value *, unsigned> Ptr2NumUses;
+  for (auto &BB : *Callee)
+    for (auto &I : BB.instructionsWithoutDebug()) {
+      if (++InstrCount == 200)
+        goto GlobalsDone;
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:101]: Maybe extract this heuristic into a separate function so you can return instead of using goto?

Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp]: ok, with the instructions() iteration, the nested loops disappeared so I could just break instead.

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 7]
```diff
@@ -92,25 +92,37 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
-      if (const Instruction *User = dyn_cast<Instruction>(U)) {
-        if (User->getParent()->getParent() == Callee)
-          CalleeGlobals.insert(&Global);
-        if (User->getParent()->getParent() == Caller)
-          CallerGlobals.insert(&Global);
+  // Give bonus for globals used much in both caller and a relatively small
+  // callee.
+  unsigned InstrCount = 0;
+  SmallDenseMap<const Value *, unsigned> Ptr2NumUses;
+  for (auto &I : instructions(Callee)) {
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:99]: Do we need to watch out for debug instructions here?  We don't want the count == 200 check to differ between a debug and a non-debug compile ...

Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:99]: I started out with that actually, but @nikic suggested this not being needed with the new debug refs, which was committed for SystemZ a month ago. (haven't double-checked though)

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 8]
```diff
@@ -92,25 +92,37 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
+    if (++InstrCount == 200) {
+      Ptr2NumUses.clear();
+      break;
+    }
+    if (const auto *SI = dyn_cast<StoreInst>(&I)) {
+      if (!SI->isVolatile())
+        if (auto GV = dyn_cast<GlobalVariable>(SI->getPointerOperand()))
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:106]:
```suggestion
        if (auto *GV = dyn_cast<GlobalVariable>(SI->getPointerOperand()))
```

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp [hunk 9]
```diff
@@ -92,25 +92,37 @@ unsigned SystemZTTIImpl::adjustInliningThreshold(const CallBase *CB) const {
...
+          Ptr2NumUses[GV]++;
+    } else if (const auto *LI = dyn_cast<LoadInst>(&I)) {
+      if (!LI->isVolatile())
+        if (auto GV = dyn_cast<GlobalVariable>(LI->getPointerOperand()))
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:110]:
```suggestion
        if (auto *GV = dyn_cast<GlobalVariable>(LI->getPointerOperand()))
```

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp (hunk 7 above)
Comment (nikic) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:99]: This is due to the switch from debug intrinsics to debug records. It's a separate change from debug instr ref (which is a backend thing).

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp (hunk 8 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp]: done

File: llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp (hunk 7 above)
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp:99]: I see, thanks.   Would this still be the case for a LLVM 20 backport?  (Not sure when this change came in ...)

**Review by uweigand — APPROVED** [review]
LGTM as well, thanks!   This should also go into LLVM 20 to fix the regression.
