### PR TITLE
[flang][OpenMP] Remove experimental warning

### LINKED ISSUE #110008: [Flang][OpenMP] Important issues to be fixed prior to removing experimental status of OpenMP
### TODOs for unsupported OpenMP 5.2 features

- [x] conditional modifier for lastprivate   https://github.com/llvm/llvm-project/pull/110568
- [x] iterator modifier for affinity, depend, from, map, to (@kparzysz)
- [x] scan directive :  https://github.com/llvm/llvm-project/pull/102792 @anchuraj 
- [x] inscan modifier for reduction (@Leporacanthicus)
- [x] task modifier for reduction clause (@Leporacanthicus)
- [x] in_reduction clause for task and target (@Leporacanthicus)
- [x] task_reduction clause for taskgroup (@Leporacanthicus)
- [x] reduction, in_reduction clause for taskloop (@kaviya2510)  https://github.com/llvm/llvm-project/pull/139704
- [x] close, present, ompx_hold map-type modifiers for map clause (@kparzysz) https://github.com/llvm/llvm-project/pull/111860
- [x] none parameter for defaultmap clause (Currently caught in Semantics giving an error - leaving as is for now @Leporacanthicus)
- [x] declare mapper directive @Leporacanthicus https://github.com/llvm/llvm-project/pull/115160
- [x] metadirective (@kparzysz)
  - [x] https://github.com/llvm/llvm-project/pull/122900
  - [x] https://github.com/llvm/llvm-project/pull/121817 (approved)
  - [x] https://github.com/llvm/llvm-project/pull/123243
  - [x] https://github.com/llvm/llvm-project/pull/123397 (approved)
  - [x] https://github.com/llvm/llvm-project/pull/124278
- [x] declare variant directive : ARM @kiranchandramohan WIP https://github.com/llvm/llvm-project/pull/130578
- [x] collapse of imperfectly nested loops for simd, worksharing, distribute and taskloop. Currently there is a semantics error.
- [x] affinity clause for task (@kparzysz) https://github.com/llvm/llvm-project/pull/113485
- [x] detach clause for task (@NimishMishra): https://github.com/llvm/llvm-project/pull/112312, https://github.com/llvm/llvm-project/pull/116601, https://github.com/llvm/llvm-project/pull/119128, https://github.com/llvm/llvm-project/pull/119172
- [x] cancel construct : support for taskloop (@kiranktp )
- [x] mutexinoutset for depend clause (@kparzysz) https://github.com/llvm/llvm-project/pull/114895
- [x] ancestor modifier for device clause of target construct
- [x] depend and nowait clause for taskwait (@Leporacanthicus)
- [x] acq_rel, acquire, release clauses for atomic construct
- [x] depend clause extensions to support iterators and depend objects with depobj construct (@kparzysz) https://github.com/llvm/llvm-project/pull/113622, https://github.com/llvm/llvm-project/pull/114074
- [x] Combined constructs master taskloop, parallelmaster, parallel master taskloop, master taskloop simd, parallel master taskloop simd @kiranchandramohan https://github.com/llvm/llvm-project/pull/113893
- [x] iterators in map clause and data motion clauses of target update (@kparzysz)
- [x] present argument for defaultmap ( @agozillon )
- [x] align clause on allocate directive : ARM https://github.com/llvm/llvm-project/pull/120791
- [x] allocator and align modifiers for allocate clause : ARM https://github.com/llvm/llvm-project/pull/121356
- [x] adjust_args and append_args clauses for declare variant directive : ARM
- [x] dispatch construct : https://github.com/llvm/llvm-project/pull/121982 @Leporacanthicus 
- [x] Assumption directives : https://github.com/llvm/llvm-project/pull/120770 @Leporacanthicus 
- [x] nothing directive (@kparzysz) https://github.com/llvm/llvm-project/pull/120606
- [x] error directive : ARM   https://github.com/llvm/llvm-project/pull/119582
- [ ] Loop transformation constructs. The parsing of these constructs work and a TODO is emitted, but semantic checks should be updated to allow loop transformation constructs in place of Fortran do loops. @Stylie777 
- [x] scope directive @kiranchandramohan https://github.com/llvm/llvm-project/pull/113700
- [x] strict modifier for grainsize and num_tasks clause @kiranchandramohan https://github.com/llvm/llvm-project/pull/113136
- [x] thread_limit clause for target directive. Frontend and Lowering support is present. Translation support is probably missing (@skatrak).
- [x] has_device_addr clause for target construct. Frontend and Lowering support is present. Translation support is probably missing. (@kparzysz) https://github.com/llvm/llvm-project/pull/128568
- [x] interop directive : [Swateesh- AMD] https://github.com/llvm/llvm-project/pull/120584
- [x] compare, fail clauses : ARM Compare support: https://github.com/llvm/llvm-project/pull/117032 and 1https://github.com/llvm/llvm-project/pull/18683
- [x] seq_cst clause for flush construct https://github.com/llvm/llvm-project/pull/114072
- [x] inoutset argument for depend clause (@kparzysz) https://github.com/llvm/llvm-project/pull/114895
- [x] Allow copyprivate, nowait on the directive (in addition to end directive) (@Thirumalai-Shaktivel, https://github.com/llvm/llvm-project/pull/127769)
- [x] Deprecation of destroy with depobj (@kparzysz) https://github.com/llvm/llvm-project/pull/114988
- [x] step modifier for linear. Deprecation (@kparzysz) https://github.com/llvm/llvm-project/pull/119278
- [x] Deprecation of modifiers without comma separators (@kparzysz) https://github.com/llvm/llvm-project/pull/117447
- [x] enter as synonym for to clause in declare target . to clause is deprecated. @Stylie777 https://github.com/llvm/llvm-project/pull/143505
- [x] declare mapper directive extension to accept iterator-modifier and the present map-type-modifier (@kparzysz) https://github.com/llvm/llvm-project/pull/144359
- [x] allocators construct. allocate directive for ALLOCATE statement is deprecated : @Stylie777 https://github.com/llvm/llvm-project/pull/142378
- [x] dispatch construct has optional end directive : @Leporacanthicus https://github.com/llvm/llvm-project/pull/121982
- [x] otherwise clause as synonym for default on metadirective (@kparzysz) (https://github.com/llvm/llvm-project/pull/121817)
- [x] allocate and firstprivate for scope directive : ARM (@Leporacanthicus) https://github.com/llvm/llvm-project/pull/116801
- [x] target enter and exit data has default map type : @Stylie777 https://github.com/llvm/llvm-project/pull/144715
- [x] doacross clause as synonym for depend in some situations (@kparzysz) https://github.com/llvm/llvm-project/pull/115396 https://github.com/llvm/llvm-project/pull/115397

### TODOs for unsupported OpenMP 4.0 features
- [x] declare reduction @Leporacanthicus 

### Must fix issues from the tracker
A subset of issues from https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+label%3Aflang%3Aopenmp
- [x] Atomic with array constructor https://github.com/llvm/llvm-project/issues/104526 @Thirumalai-Shaktivel https://github.com/llvm/llvm-project/pull/121181
- [x] Atomic write to complex https://github.com/llvm/llvm-project/issues/113479 @NimishMishra  https://github.com/llvm/llvm-project/pull/121055
- [x] Error when capture-statement described in atomic capture construct contains a different type https://github.com/llvm/llvm-project/issues/115652  @NimishMishra : https://github.com/llvm/llvm-project/pull/121055
- [x] Runtime segfault when allocatable threadprivate variable is used with copyin https://github.com/llvm/llvm-project/issues/113191 @kaviya2510 : https://github.com/kaviya2510/llvm-project/tree/copyin_allocatable
- [x] Assertion failure using default clause with critical https://github.com/llvm/llvm-project/issues/112572
- [x] Crash in OpenMPIRBuilder when trying to outline a parallel region with an infinite loop https://github.com/llvm/llvm-project/issues/112884 @tblah
- [x] Problem building GAMESS (delayed privatisation of derived type) https://github.com/llvm/llvm-project/issues/109727
- [x] dot product inside of omp.parallel (part of cp2k) https://github.com/llvm/llvm-project/issues/116954
- [x] Privatisation with sections ICE https://github.com/llvm/llvm-project/issues/135108 @tblah
- [x] Common block name in omp flush https://github.com/llvm/llvm-project/issues/136583 @tblah
- [x] threadprivate with pointer to character https://github.com/llvm/llvm-project/issues/108136 @tblah
- [x] https://github.com/llvm/llvm-project/issues/140754 @mrkajetanp https://github.com/llvm/llvm-project/pull/142415
- [x] https://github.com/llvm/llvm-project/issues/140741 @mrkajetanp https://github.com/llvm/llvm-project/pull/142160
- [x] https://github.com/llvm/llvm-project/issues/140732 @mrkajetanp https://github.com/llvm/llvm-project/pull/142783
- [x] https://github.com/llvm/llvm-project/issues/139071 @kparzysz https://github.com/llvm/llvm-project/pull/144593
- [x] https://github.com/llvm/llvm-project/issues/138436 @tblah https://github.com/llvm/llvm-project/pull/142997
- [x] https://github.com/llvm/llvm-project/issues/138102 @mrkajetanp https://github.com/llvm/llvm-project/pull/145051
- [x] https://github.com/llvm/llvm-project/issues/133685 @tblah https://github.com/llvm/llvm-project/pull/140798
- [x] https://github.com/llvm/llvm-project/issues/133678 @mrkajetanp https://github.com/llvm/llvm-project/pull/142595
- [x] https://github.com/llvm/llvm-project/issues/126451
- [x] https://github.com/llvm/llvm-project/issues/116428
- [x] https://github.com/llvm/llvm-project/issues/142365 @tblah https://github.com/llvm/llvm-project/pull/143112
- [x] https://github.com/llvm/llvm-project/issues/142404 @tblah https://github.com/llvm/llvm-project/pull/143907
- [x] https://github.com/llvm/llvm-project/issues/142123 @mrkajetanp https://github.com/llvm/llvm-project/pull/144092
- [x] https://github.com/llvm/llvm-project/issues/142935
- [x] https://github.com/llvm/llvm-project/issues/143231 @tblah https://github.com/llvm/llvm-project/pull/144502
- [x] https://github.com/llvm/llvm-project/issues/143229 @tblah https://github.com/llvm/llvm-project/pull/144040
- [x] https://github.com/llvm/llvm-project/issues/144178 @tblah

### Must fix issues not in tracker

- [x] Default loop schedule modifier for worksharing-loop constructs without static schedule and ordered clause is nonmonotonic since OpenMP 5.0 @tblah
- [x] Privatization issues in interfacing with OpenMPIRBuilder. https://discourse.llvm.org/t/rfc-openmp-fix-issue-in-mlir-to-llvmir-translation-for-delayed-privatisation/81225. Fixed by @tblah https://github.com/llvm/llvm-project/pull/111844
- [x] Support for deferred task execution @tblah https://github.com/llvm/llvm-project/pull/125307

Minor bugs:
- [x] Crash with undeclared variable and `implicit none`:  https://github.com/llvm/llvm-project/issues/131655
- [x] Bad word ordering leads to assert in lowering: https://github.com/llvm/llvm-project/issues/131659

### PR DESCRIPTION
**Pull request by tblah**
RFC: https://discourse.llvm.org/t/rfc-removing-the-openmp-experimental-warning-for-llvm-21/86455

Fixes: #110008

There are a handful of open issues still to resolve before this can go out of draft. See the linked issue.

### CODE REVIEW

File: flang/test/Driver/fopenmp.f90 [hunk 1]
```diff
@@ -74,6 +74,6 @@
 ! CHECK-LD-ANYMD: "{{.*}}ld{{(.exe)?}}"
 ! CHECK-LD-ANYMD: "-l{{(omp|gomp|iomp5md)}}"
 !
-! RUN: %flang -fopenmp -c %s -### 2>&1 | FileCheck %s --check-prefix=CHECK-EXPERIMENTAL
+! RUN: %flang -fopenmp -fopenmp-version=40 -c %s -### 2>&1 | FileCheck %s --check-prefix=CHECK-EXPERIMENTAL
```
Comment (bhandarkar-pranav) [inline flang/test/Driver/fopenmp.f90]: NIT: ``sed 's/EXPERIMENTAL/INCOMPLETE/g'``

**Review by bhandarkar-pranav — APPROVED** [review]
LGTM. I have a nit, but too minor to warrant an update to this PR. Only address it if you are planning to push an update to this PR on account of someone else's review with beefier changes requested.

**Review by NimishMishra — APPROVED** [review]
LGTM. Thanks a lot

**Review by kparzysz — APPROVED** [review]
LGTM

**Comment by tblah** [comment]
I've taken this out of draft.

The only remaining item in #110008 is some improved semantic checks for Loop transformation constructs. The parsing of these constructs works already and a TODO is emitted, but semantic checks should be updated to allow loop transformation constructs in place of Fortran do loops e.g.
```
!$omp parallel do
!$omp unroll
do i = 1, N
...
```

@Stylie777 is already working on this, but his work could conflict with #143715 and #144785 he will likely base his patch upon that other work and post after they are merged. 

I would like to go ahead and merge this now because the loop transformation constructs are an OpenMP 5.1 feature and they do not lead to a compiler crash, only a misleading semantic error.

Is everyone okay with this being merged?

**Comment by NimishMishra** [comment]
> I would like to go ahead and merge this now because the loop transformation constructs are an OpenMP 5.1 feature and they do not lead to a compiler crash, only a misleading semantic error.


I am okay with it.

**Review by tarunprabhu — APPROVED** [review]
Thanks Tom. I'm fine with merging this.

**Comment by tblah** [comment]
[ebd2980](https://github.com/llvm/llvm-project/pull/144915/commits/ebd2980051b3994d1c419d06f3cba22927283aec) moves the warning to the frontend driver so it can use the checks added in #145725

**Review by kparzysz — APPROVED** [review]

**Review by mrkajetanp — APPROVED** [review]
