### PR TITLE
[clangd] fix extract-to-function for overloaded operators

### LINKED ISSUE #1254: "Extract to Function" tweak often not offered where it should be
For example:
```
int main()
{
    std::cout << "x";
}
```
Contrary to what one would expect, selecting the line with the statement does not trigger the "Extract to Function" tweak.
Debugging shows that ExtractFunction::prepare() bails out very early, because the "common ancestor" of the SelectionTree (a CXXOperatorCall in this case) is marked as Unselected. This looks wrong to me, but I'm not entirely sure about the semantics there.

Output of `clangd --version`: clangd version 16.0.0 (https://github.com/llvm/llvm-project.git 9f947abf94e16fa7c759ab56a4fb030d6ef25961)

### PR DESCRIPTION
**Pull request by 5chmidti**
When selecting code that contains the use of overloaded operators,
the SelectionTree will attribute the operator to the operator
declaration, not to the `CXXOperatorCallExpr`. To allow
extract-to-function to work with these operators, make unselected
`CXXOperatorCallExpr`s valid root statements, just like `DeclStmt`s.

Partially fixes clangd/clangd#1254

### CODE REVIEW

**Comment by 5chmidti** [comment]
Ping

**Comment by 5chmidti** [comment]
Rebase & Ping

**Comment by BenBlumer** [comment]
Would be great to see this merged. This bug prevents basic function extractions from working.

**Comment by BenBlumer** [comment]
I can confirm this builds and fixes the issue. For example, in: 

```
#include <iostream>

#include <ostream>




int main() {

int a = 5;

int b = 7;

int c;

c =  a+b;

std::cout <<  a+b << std::endl;

return 0;

}
```

Without this patch, there is no refactor available for: 
```
c =  a+b;

std::cout <<  a+b << std::endl
```
With the patch, it can be extracted

File: clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp [hunk 1]
```diff
@@ -105,7 +105,7 @@ bool isRootStmt(const Node *N) {
   if (N->Selected == SelectionTree::Partial)
     return false;
   // A DeclStmt can be an unselected RootStmt since VarDecls claim the entire
-  // selection range in selectionTree. Additionally, an CXXOperatorCallExpr of a
+  // selection range in selectionTree. Additionally, a CXXOperatorCallExpr of a
   // binary operation can be unselected because it's children claim the entire
```
Comment (ckandeler) [inline clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp:109]: "it's" should also be changed to "its"

**Comment by ckandeler** [comment]
Needs rebase and another typo fix. Looks good to me otherwise.

**Comment by BenBlumer** [comment]
@5chmidti I'm excited for this to be mainlined. Give me a thumbs up if you want me to fix the typo and rebase for you -- happy to do it this weekend.

File: clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp [hunk 2]
```diff
@@ -104,9 +104,12 @@ bool isRootStmt(const Node *N) {
   // Root statement cannot be partially selected.
   if (N->Selected == SelectionTree::Partial)
     return false;
-  // Only DeclStmt can be an unselected RootStmt since VarDecls claim the entire
-  // selection range in selectionTree.
-  if (N->Selected == SelectionTree::Unselected && !N->ASTNode.get<DeclStmt>())
+  // A DeclStmt can be an unselected RootStmt since VarDecls claim the entire
+  // selection range in selectionTree. Additionally, a CXXOperatorCallExpr of a
+  // binary operation can be unselected because it's children claim the entire
```
Comment (5chmidti) [inline clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp:109]:
```suggestion
  // selection range in selectionTree. Additionally, a CXXOperatorCallExpr of a
  // binary operation can be unselected because its children claim the entire
```

**Review by 5chmidti — COMMENTED** [review]
CC @HighCommander4 @kadircet 

Technically, Sam told me last EuroLLVM that he had some refactor of the `SelectionTree` that would resolve issues like this in the general case, but as it is unclear that those changes will get in someday/in the 'near' future, I think that this PR makes sense to merge. Even though this is kind of a band-aid fix. Thoughts?

**Comment by BenBlumer** [comment]
I'm a bit of a outsider to the LLVM project, but I'd say a fix to a broken,
already shipped, feature now is better than a general fix down the line.

**Comment by HighCommander4** [comment]
Do I understand correctly that this is a partial fix for https://github.com/clangd/clangd/issues/1254 in that it addresses the issue with overloaded operators in particular, but it still leaves in place the limitation that a **single** expression statement (of any kind) cannot be extracted?

If so, would you mind adding an "unavailable" test case for the latter case, with some sort of "TODO, we'd like to relax this limitation" comment?

**Comment by 5chmidti** [comment]
> Do I understand correctly that this is a partial fix for [clangd/clangd#1254](https://github.com/clangd/clangd/issues/1254) in that it addresses the issue with overloaded operators in particular, but it still leaves in place the limitation that a **single** expression statement (of any kind) cannot be extracted?

Exactly

> If so, would you mind adding an "unavailable" test case for the latter case, with some sort of "TODO, we'd like to relax this limitation" comment?

Done

**Comment by BenBlumer** [comment]
Thanks for your work on this, Julian! I'm excited to have this tool work properly!

File: clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp [hunk 3]
```diff
@@ -104,9 +104,12 @@ bool isRootStmt(const Node *N) {
...
+  // selection range in the selection tree (e.g. <<).
+  if (N->Selected == SelectionTree::Unselected && !N->ASTNode.get<DeclStmt>() &&
```
Comment (HighCommander4) [inline clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp:111]: Do we need to make a corresponding change [here](https://searchfox.org/llvm/rev/30213e99b86a078c9d472264c7edeea9aa638dd4/clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp#141-146)? The comment suggests that it's special-casing `DeclStmt` for the same reason as this code.

File: clang-tools-extra/clangd/unittests/tweaks/ExtractFunctionTests.cpp [hunk 4]
```diff
@@ -190,6 +190,14 @@ F (extracted();)
     }]]
   )cpp";
   EXPECT_EQ(apply(CompoundFailInput), "unavailable");
+
+  ExtraArgs.push_back("-std=c++14");
+  // FIXME: Expressions are currently not extracted
+  EXPECT_EQ(apply(R"cpp(
+                void sink(int);
+                void call() { sink([[1+1]]); }
```
Comment (HighCommander4) [inline clang-tools-extra/clangd/unittests/tweaks/ExtractFunctionTests.cpp:198]: I was thinking more specifically about entire expression-statements, e.g. `[[stream << 42;]]`.

Extraction of arbitrary subexpressions would be nice as well, but likely more involved; there is a work in progress [here](https://reviews.llvm.org/D140619).

(We can keep this test case too.)

Comment (5chmidti) [reply clang-tools-extra/clangd/unittests/tweaks/ExtractFunctionTests.cpp]: I've added another testcase for extracting a single expression

**Review by HighCommander4 — APPROVED** [review]
Thanks. +1 to taking this targeted fix without waiting for a larger refactor.
