### PR TITLE
[flang][OpenMP] Fix construct privatization in default clause

### LINKED ISSUE #71914: [Flang][OpenMP] default(private) failing with parallel do
`default(private)` fails to privatize when used with parallel do. Reproducer:

```
program sample
   integer :: x
   x = 0
   !$omp parallel do default(private) num_threads(50)
      do i = 1, 50
        x = x + 1
      end do
   !$omp end parallel do
   print *, x
end program sample
```

As expected, gfortran prints x=0. However, LLVM flang prints a non-zero value (< 50). Use of an additional `if(.false.)` ensures x=50.

A dump of `--emit-fir` shows `fir.store %10 to %1`

```
    %0 = fir.alloca i32 {bindc_name = "i", uniq_name = "_QFEi"}
    %1 = fir.alloca i32 {bindc_name = "x", uniq_name = "_QFEx"}
    %c0_i32 = arith.constant 0 : i32
    fir.store %c0_i32 to %1 : !fir.ref<i32>
    %c50_i32 = arith.constant 50 : i32
    omp.parallel num_threads(%c50_i32 : i32) {
      %8 = fir.alloca i32 {adapt.valuebyref, pinned}
      %c1_i32 = arith.constant 1 : i32
      %c50_i32_0 = arith.constant 50 : i32
      %c1_i32_1 = arith.constant 1 : i32
      omp.wsloop for  (%arg0) : i32 = (%c1_i32) to (%c50_i32_0) inclusive step (%c1_i32_1) {
        fir.store %arg0 to %8 : !fir.ref<i32>
        %9 = fir.load %1 : !fir.ref<i32>
        %c1_i32_2 = arith.constant 1 : i32
        %10 = arith.addi %9, %c1_i32_2 : i32
        **fir.store %10 to %1 : !fir.ref<i32>**
        omp.yield
      }
      omp.terminator
    }

```

Expected IR should be as follows:

```
    %0 = fir.alloca i32 {bindc_name = "i", uniq_name = "_QFEi"}
    %1 = fir.alloca i32 {bindc_name = "x", uniq_name = "_QFEx"}
    %c0_i32 = arith.constant 0 : i32
    fir.store %c0_i32 to %1 : !fir.ref<i32>
    %c50_i32 = arith.constant 50 : i32
    omp.parallel num_threads(%c50_i32 : i32) {
      %8 = fir.alloca i32 {adapt.valuebyref, pinned}
      **%9 = fir.alloca i32 {bindc_name = "x", pinned, uniq_name = "_QFEx"}**
      %c1_i32 = arith.constant 1 : i32
      %c50_i32_0 = arith.constant 50 : i32
      %c1_i32_1 = arith.constant 1 : i32
      omp.wsloop for  (%arg0) : i32 = (%c1_i32) to (%c50_i32_0) inclusive step (%c1_i32_1) {
        fir.store %arg0 to %8 : !fir.ref<i32>
        %10 = fir.load %9 : !fir.ref<i32>
        %c1_i32_2 = arith.constant 1 : i32
        %11 = arith.addi %10, %c1_i32_2 : i32
        **fir.store %11 to %9 : !fir.ref<i32>**
        omp.yield
      }
      omp.terminator
    }
```

### PR DESCRIPTION
**Pull request by NimishMishra**
Current implementation of default clause privatization incorrectly fails to privatize in presence of non-OpenMP constructs (i.e. nested constructs with regions whose symbols need to be privatized in the scope of the parent OpenMP construct). This patch fixes the same by considering non-OpenMP constructs separately by collecting symbols of a nested region if it is a non-OpenMP construct with a region, and privatizing it in the scope of the parent OpenMP construct.

Fixes https://github.com/llvm/llvm-project/issues/71914 and https://github.com/llvm/llvm-project/issues/71915

### CODE REVIEW

File: flang/lib/Lower/OpenMP.cpp [hunk 1]
```diff
@@ -120,7 +120,6 @@ class DataSharingProcessor {
   llvm::SetVector<const Fortran::semantics::Symbol *> privatizedSymbols;
   llvm::SetVector<const Fortran::semantics::Symbol *> defaultSymbols;
   llvm::SetVector<const Fortran::semantics::Symbol *> symbolsInNestedRegions;
-  llvm::SetVector<const Fortran::semantics::Symbol *> symbolsInParentRegions;
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP.cpp:123]: Why is this not required anymore?

**Review by kiranchandramohan — COMMENTED** [review]
> fails to privatize in presence of non-OpenMP constructs.

Could you comment on what non-OpenMP constructs are you talking about here? Is it constructs with regions? 

In general, could you expan on the issue and the fix?

File: flang/lib/Lower/Bridge.cpp [hunk 2]
```diff
@@ -855,7 +855,7 @@ class FirConverter : public Fortran::lower::AbstractConverter {
                               bool collectSymbol) {
             if (collectSymbol && oriSymbol.test(flag))
               symbolSet.insert(&oriSymbol);
-            if (checkHostAssociatedSymbols)
+            else if (checkHostAssociatedSymbols)
```
[the remark this answers is not in the document]
Comment (NimishMishra) [reply flang/lib/Lower/Bridge.cpp:858]: I have expanded on the comment in AbstractConverter.h. Could you please see if it is ok now?

File: flang/lib/Lower/OpenMP.cpp (hunk 1 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:123]: Bad design from my end. Earlier, we were collecting both the symbol as well as the host-association details, and then removing one of them using this list. I have modified the current implementation to a use a `else if`, and hence this isn't required.

File: flang/lib/Lower/OpenMP.cpp [hunk 3]
```diff
@@ -426,14 +425,10 @@ void DataSharingProcessor::collectSymbols(
...
   for (Fortran::lower::pft::Evaluation &e : eval.getNestedEvaluations()) {
-    if (e.hasNestedEvaluations())
+    if (e.hasNestedEvaluations() && !e.isConstruct())
       converter.collectSymbolSet(e, symbolsInNestedRegions, flag,
                                  /*collectSymbols=*/true,
                                  /*collectHostAssociatedSymbols=*/false);
-    else
-      converter.collectSymbolSet(e, symbolsInParentRegions, flag,
-                                 /*collectSymbols=*/false,
-                                 /*collectHostAssociatedSymbols=*/true);
```
Comment (luporl) [inline flang/lib/Lower/OpenMP.cpp:436]: With this change and that in `collectSymbolSet()`, it seems that host associated symbols are never collected anymore, isn't it? If this is the case, can't we remove the `collectHostAssociatedSymbols` and `collectSymbols` flags from `collectSymbolSet()`?

Comment (luporl) [reply flang/lib/Lower/OpenMP.cpp:436]: I guess not, because it's an `if (collectSymbol && oriSymbol.test(flag)`. Sorry for the noise.

**Comment by NimishMishra** [comment]
Ping for review!

File: flang/lib/Lower/OpenMP.cpp [hunk 4]
```diff
@@ -426,14 +425,10 @@ void DataSharingProcessor::collectSymbols(
                              /*collectSymbols=*/true,
                              /*collectHostAssociatedSymbols=*/true);
   for (Fortran::lower::pft::Evaluation &e : eval.getNestedEvaluations()) {
-    if (e.hasNestedEvaluations())
+    if (e.hasNestedEvaluations() && !e.isConstruct())
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP.cpp:428]: Why is it collected in non-constructs (like OpenMP)?

Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: @kiranchandramohan I was on leave mainly for past few days; sorry about the delayed response.

So we maintain two lists: `defaultSymbols` and `symbolsInNestedRegions`. For non-constructs like OpenMP, we would not like to collected the host associated symbols for nested regions (thereby `collectHostAssociatedSymbols = false`). They can be handled as the `default` clause may be in their respective nested blocks. This was the earlier design.

However, for non-OpenMP constructs, the handling is different. This is because even though the inner construct has a block region (like OpenMP constructs do), all privatization of variables in the nested construct needs to happen in the outer OpenMP construct. Hence, we do not need to populate the `symbolsInNestedRegions` list. Otherwise, no privatization will happen, leading to incorrect results.

That said, if you think so, I can relook the design of the lists once. It has been quite some time when we implemented the default clause. So maybe, we can think of improving this lowering flow once. What are your suggestions?

Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: @kiranchandramohan A ping on this! How can we take this forward?

Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP.cpp:428]: > So we maintain two lists: defaultSymbols and symbolsInNestedRegions. For non-constructs like OpenMP, we would not like to collected the host associated symbols for nested regions (thereby collectHostAssociatedSymbols = false). They can be handled as the default clause may be in their respective nested blocks. This was the earlier design.

Some OpenMP constructs (like critical) will not have a default clause because such a clause is not supported for these constructs. Some OpenMP constructs might not have them specified (i.e no default clause is present eventhough it is supported). Do we need to distinguish these cases? For those constructs which have them specified, for every pair of defaults do their exact values matter for the inner construct's symbols?

outer(default=shared), inner(default=shared) : Nothing to do
outer(default=private), inner(default=shared) : ?
outer(default=shared), inner(default=private) : ?
outer(default=private),inner(default=private) : ?

> However, for non-OpenMP constructs, the handling is different. This is because even though the inner construct has a block region (like OpenMP constructs do), all privatization of variables in the nested construct needs to happen in the outer OpenMP construct. Hence, we do not need to populate the symbolsInNestedRegions list.

Makes sense.

Comment (luporl) [inline flang/lib/Lower/OpenMP.cpp:428]: I had a hard time trying to understand how `collectSymbols()` work.
This is how I understand it:
- First, all symbols used in `eval` that match `flag` are collected into `defaultSymbols`, including host associated symbols
   (why host associated symbols need to be collected? To look at the outer scope? But if the symbol in the outer scope  matches the default DSA, does anything need to be done?)
- For each evaluation that is a direct child of `eval`:
  - If the evaluation has children and is not a Fortran construct (such as if, do, etc)
    - Add the symbols used in it, that match `flag`, to `symbolsInNestedRegions`, skipping host associated symbols
      (because otherwise symbols from the top `eval` level could also be collected?)
- Later, in `defaultPrivatize`, `symbolsInNestedRegions` are excluded from `defaultSymbols`, presumably because each nested region will handle them appropriately. Then, the remaining symbols are privatized, with some exceptions, such as procedures.

Is my understanding correct?

It would be nice to add a brief comment to `collectSymbols`, explaining what it does.

Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: @kiranchandramohan I checked for the use-cases mentioned. The lowering seems to be okay. Should I add these combinations in the tests for default clause?

**outer(default=private), inner(default=private)**

Consider the following example:

```
integer :: j
!$omp parallel default(private)
      j = 10
      !$omp parallel default(firstprivate)
                 j = j + 5
      !$omp end parallel
!$omp end parallel
```

This lowers as:

```
%0 = fir.alloca i32 ......
%1:2 = hlfir.declare %0 .....
omp.parallel {
       %2 = fir.alloca i32 .....      // privatized j
        %3:2 = hlfir.declare %2
        %c = arith.constant 10 
        hlfir.assign %c to %3#0 ....
        omp.parallel {
                 %4 = fir.alloca i32 ....
                 %5:2 = hlfir.declare %4 ....
                 %6 = fir.load %3#0 .....
                 hlfir.assign %6 to %5#0 ......
        }
}
```

**outer(default=private), inner(default=shared)**

Example:

```
integer :: j
!$omp parallel default(private)
      j = 10
      !$omp parallel
                 j = j + 5
      !$omp end parallel
!$omp end parallel
```

This lowers as:

```
%0 = fir.alloca i32 ......
%1:2 = hlfir.declare %0 .....
omp.parallel {
       %2 = fir.alloca i32 .....      // privatized j
        %3:2 = hlfir.declare %2
        %c = arith.constant 10 
        hlfir.assign %c to %3#0 ....
        omp.parallel {
                 %4 = fir.load %3#0 .....
                 // add 5 to %4 and store in %5
                 hlfir.assign %5 to %3#0 ....
        }
}
```

**outer(default=shared), inner(default=private)**

Example:

```
integer :: j
!$omp parallel
      j = 10
      !$omp parallel default(private)
                 j = j + 5
      !$omp end parallel
!$omp end parallel
```

This lowers as:

```
%0 = fir.alloca i32 ......
%1:2 = hlfir.declare %0 .....
omp.parallel {
        %c = arith.constant 10 
        hlfir.assign %c to %3#0 ....
        omp.parallel {
                 %2 = fir.alloca ....
                 %3:2 = hlfir.declare %2 ....
                 %4 = fir.load %3#0 .....
                 // add 5 to %4 and store in %5
                 hlfir.assign %5 to %3#0 ....
        }
}
```

And should be consider `firstprivate` in the inner parallel:

```
%0 = fir.alloca i32 ......
%1:2 = hlfir.declare %0 .....
omp.parallel {
        %c = arith.constant 10 
        hlfir.assign %c to %3#0 ....
        omp.parallel {
                 %2 = fir.alloca ....
                 %3:2 = hlfir.declare %2 ....
                 %4 = fir.load %1#0 ....
                 hlfir.assign %4 to %3#0 .....
                 %5 = fir.load %3#0 .....
                 // add 5 to %4 and store in %6
                 hlfir.assign %6 to %3#0 ....
        }
}
```

Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: Additionally, for constructs like `critical` not having an explicit default clause, the lowered IR is in line with the correct symbols that the construct should be using.

Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: Thanks @luporl for the review. Yes, the understanding is correct. Since each nested region needs to handle the symbols separately, we needed to make `collectSymbols` as it is now. In fact, in response to Kiran's comment above, I have given the lowered IR for combinations of nested constructs with default clause. You could check if you are ok with the current behaviour.

And sure, I'll capture more details on `collectSymbols` with this PR.

Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP.cpp:428]: I was trying to understand the need to distinguish between OpenMP and non-OpenMP constructs for collecting symbols recursively.  Particularly in cases where the variable on which a default applies is only visible inside the nested OpenMP construct. Consider the following example : 

```
program mn
  call sb1()
contains
 subroutine sb1()
   integer :: x
   x = 20
   !$omp parallel default(private)
   !$omp critical
   x = 30
   !$omp end critical
   !$omp end parallel
   print *, x
 end subroutine
end program
```

But the following example with nested parallel works. I am assuming the semantics code is creating symbols here. Is that the reason? 
If so, why not handle everything (nested openmp and nested non-openmp constructs) in the frontend? What is the split between semantics and the code here?
```
program mn
  call sb1()
contains
 subroutine sb1()
   integer :: x
   x = 20
   !$omp parallel default(private)
   !$omp parallel 
   x = 30
   !$omp end parallel
   !$omp end parallel
   print *, x
 end subroutine
end program
```

Comment (luporl) [reply flang/lib/Lower/OpenMP.cpp:428]: Thanks for the explanation @NimishMishra. The current behavior seems ok to me.
I'm planning to use `collectSymbols` to handle symbols with implicit DSA, such as those of `task`, that must be `firstprivate` if no `default` clause is present (and outer context doesn't define it as shared).

**Comment by luporl** [comment]
> So, all OpenMP constructs that may take data-sharing attribute clauses may sort of have an implicit default data-sharing attribute or inherit from the outer scope. For instance, `parallel` uses the implicit default data-sharing attribute, while `critical` just uses what's coming from the outer scope.

OpenMP 4.5, subclause 2.15.1.1 lists the rules of implicit data-sharing attributes. In fact, some of them are missing in Flang, like that of `task`: https://github.com/llvm/llvm-project/issues/64480

File: flang/lib/Lower/OpenMP.cpp (hunk 4 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP.cpp:428]: Hello @kiranchandramohan,

        I  re-looked at the possibility of handling the entire default clause at one place. For instance, I checked whether we can handle it completely during lowering. One possible way:

1. Use a function similar to `collectSymbolSet` with a bool `checkFlag`, such that the function checks symbol flag iff `checkFlag = True`, otherwise it simply adds the symbol to the symbol list.

2. Given any OpenMP context, all symbols encountered in the same context can then be collected through `checkFlag = True`. In other words, any symbol in the same region where `default(private)` is specified should only collect symbols with the `private` data-sharing attribute. However, any symbol in a nested region can be collected irrespective of the specified flag on that symbol.

This approach, unfortunately, does not work without the symbol modifications we currently do in semantics.

For your question on handling OpenMP and non OpenMP constructs in semantics itself, currently, both are being handled. It's just that while lowering, for nested OpenMP constructs, we need to collect host-associated symbols as well. For non-OpenMP constructs, we skip host-associated symbols.

I tried a few variations in which to simply this (use a single list `defaultSymbols` instead of two lists: `defaultSymbols` and `symbolsInNestedRegions`). But so far, nothing concrete has come up...

**Comment by luporl** [comment]
I have been using this patch (rebased on top of main) without issues for some time.
But today I have noticed a strange behavior with a test program, which I reduced to the following:

```f90
!$omp parallel do default(private) firstprivate(y)
  do i = 1, 10
    y = 1
    !$omp parallel default(private)
      y = 2
    !$omp end parallel
  end do
!$omp end parallel do
end
```

This program hits an assert:
`Assertion failed: (success && "Privatization failed due to existing binding"), function cloneSymbol, file DataSharingProcessor.cpp, line 74.`

The problem is that the inner parallel directive is inside a Fortran construct (`do`), which causes its symbols to not be collected as `symbolsInNestedRegions`. This results in `defaultPrivatize` trying to privatize `y` twice.

A possible solution could be to visit nested evaluations recursively and, in each one, collect the symbols from the first OpenMP construct (if any).

**Comment by NimishMishra** [comment]
Thank you @luporl for pointing this out.

I think you are right in stating that a recursive solution would be better in this context. I'll work on this and send out a revision.

**Comment by NimishMishra** [comment]
> A possible solution could be to visit nested evaluations recursively and, in each one, collect the symbols from the first OpenMP construct (if any).

Hi @luporl,

   I am revisiting this patch, and am wondering if recursion is needed here. Checking up with you once if I am missing something.

```
!$omp parallel do default(private) firstprivate(y)
  do i = 1, 10
    y = 1           ! Point X
    !$omp parallel default(private)
      y = 2        ! Point Y
    !$omp end parallel
  end do
!$omp end parallel do
end
```

Then `collectSymbolSet()` on the outermost evaluation shall collect all symbols within the region. Then we enter into its nested evaluations and catch `do{... region ...}`, which is essentially,

```
do{
     assignment-stmt
     parallel{... region ...}
}
```

So if we iterate over these evaluations, and do the following:

1. For non-OpenMP constructs, skip adding symbols to `symbolsInNestedRegion`. This shall skip the symbol `y` marked at `Point X`.
2. For OpenMP constructs, add symbols. This shall add the symbol `y` marked at `Point Y`.

Concisely, for a `do{... region ...}`, if we have a OpenMP region inside it, then we can add **all** symbols within it to `symbolsInNestedRegion` with just one `collectSymbolSet` call (which in turn is recursive). So I was wondering if we need additional recursion at this point.

**Comment by NimishMishra** [comment]
Thanks @luporl. Yeah, I think recursion is the best way to go forward. I made the required changes for a recursive solution, and for the following:

```
program main
      integer :: y, z
      !$omp parallel default(private) firstprivate(y)
      do i = 1, 10 
            y = 1
            do j = 1, 10
            z = 20
            !$omp parallel default(private)
                y = 2
            !$omp end parallel
            end do
        end do
      !$omp end parallel 
end program
```

I have the following FIR:

```
%0 = fir.alloca i32 {bindc_name = "i", uniq_name = "_QFEi"}
    %1 = fir.declare %0 {uniq_name = "_QFEi"} : (!fir.ref<i32>) -> !fir.ref<i32>
    %2 = fir.alloca i32 {bindc_name = "j", uniq_name = "_QFEj"}
    %3 = fir.declare %2 {uniq_name = "_QFEj"} : (!fir.ref<i32>) -> !fir.ref<i32>
    %4 = fir.alloca i32 {bindc_name = "y", uniq_name = "_QFEy"}
    %5 = fir.declare %4 {uniq_name = "_QFEy"} : (!fir.ref<i32>) -> !fir.ref<i32>
    %6 = fir.alloca i32 {bindc_name = "z", uniq_name = "_QFEz"}
    %7 = fir.declare %6 {uniq_name = "_QFEz"} : (!fir.ref<i32>) -> !fir.ref<i32>
    omp.parallel {
      %8 = fir.alloca i32 {bindc_name = "j", pinned}
      %9 = fir.declare %8 {uniq_name = "_QFEj"} : (!fir.ref<i32>) -> !fir.ref<i32>
      %10 = fir.alloca i32 {bindc_name = "i", pinned}
      %11 = fir.declare %10 {uniq_name = "_QFEi"} : (!fir.ref<i32>) -> !fir.ref<i32>
      %12 = fir.alloca i32 {bindc_name = "y", pinned, uniq_name = "_QFEy"}
      %13 = fir.declare %12 {uniq_name = "_QFEy"} : (!fir.ref<i32>) -> !fir.ref<i32>
      %14 = fir.load %5 : !fir.ref<i32>
      fir.store %14 to %13 : !fir.ref<i32>
      %15 = fir.alloca i32 {bindc_name = "z", pinned, uniq_name = "_QFEz"}
      %16 = fir.declare %15 {uniq_name = "_QFEz"} : (!fir.ref<i32>) -> !fir.ref<i32>
      %17 = fir.convert %c1_i32 : (i32) -> index
      %18 = fir.convert %c10_i32 : (i32) -> index
      %19 = fir.convert %17 : (index) -> i32
      %20:2 = fir.do_loop %arg0 = %17 to %18 step %c1 iter_args(%arg1 = %19) -> (index, i32) {
        fir.store %arg1 to %11 : !fir.ref<i32>
        fir.store %c1_i32 to %13 : !fir.ref<i32>
        %21 = fir.convert %c1_i32 : (i32) -> index
        %22 = fir.convert %c10_i32 : (i32) -> index
        %23 = fir.convert %21 : (index) -> i32
        %24:2 = fir.do_loop %arg2 = %21 to %22 step %c1 iter_args(%arg3 = %23) -> (index, i32) {
          fir.store %arg3 to %9 : !fir.ref<i32>
          fir.store %c20_i32 to %16 : !fir.ref<i32>
          omp.parallel {
            %33 = fir.alloca i32 {bindc_name = "y", pinned, uniq_name = "_QFEy"}
            %34 = fir.declare %33 {uniq_name = "_QFEy"} : (!fir.ref<i32>) -> !fir.ref<i32>
            fir.store %c2_i32 to %34 : !fir.ref<i32>
            omp.terminator
          }
          %29 = arith.addi %arg2, %c1 : index
          %30 = fir.convert %c1 : (index) -> i32
          %31 = fir.load %9 : !fir.ref<i32>
          %32 = arith.addi %31, %30 : i32
          fir.result %29, %32 : index, i32
        }
        fir.store %24#1 to %9 : !fir.ref<i32>
        %25 = arith.addi %arg0, %c1 : index
        %26 = fir.convert %c1 : (index) -> i32
        %27 = fir.load %11 : !fir.ref<i32>
        %28 = arith.addi %27, %26 : i32
        fir.result %25, %28 : index, i32
      }
      fir.store %20#1 to %11 : !fir.ref<i32>
      omp.terminator
```

The behaviour of the IR seems fine to me. Is it okay with you? I'll push the revision thereafter.

**Comment by luporl** [comment]
> The behaviour of the IR seems fine to me. Is it okay with you? I'll push the revision thereafter.

@NimishMishra, the test program and resulting IR looks good to me too. Thanks for working on this.

**Comment by NimishMishra** [comment]
> > The behaviour of the IR seems fine to me. Is it okay with you? I'll push the revision thereafter.
> 
> @NimishMishra, the test program and resulting IR looks good to me too. Thanks for working on this.

Thanks @luporl . I have pushed the change. I think a similar treatment (to deeply nested constructs) is also needed when we manipulate symbols while resolving directives. However, that problem has already been resolved with your change at https://github.com/llvm/llvm-project/pull/85989, where `shared(z)` uses the parent's copy. Once both the changes go in, the problem should be solved. Is that fine with you? Or should I merge both changes into one patch and then raise a review for the same?

**Comment by luporl** [comment]
> Thanks @luporl . I have pushed the change. I think a similar treatment (to deeply nested constructs) is also needed when we manipulate symbols while resolving directives. However, that problem has already been resolved with your change at #85989, where `shared(z)` uses the parent's copy. Once both the changes go in, the problem should be solved. Is that fine with you? Or should I merge both changes into one patch and then raise a review for the same?

@NimishMishra, I think that, if it's not too much work, it would be nice to move from #85989 to this change the part that filters out symbols that are out of `eval` scope. It would be the `if (clauseScopes.contains(&sym->owner())) symbols.insert(sym)` part and all of its dependencies. This would avoid a regression in default clause handling, while #85989 doesn't land.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 5]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
+}
+
+// Collect symbols to be default privatized in two steps.
+// In step 1, collect all symbols in `eval` that match `flag`
+// into `defaultSymbols`.
+// In step 2, for nested constructs (if any), if and only if
+// the nested construct is an OpenMP construct, collect those nested
+// symbols skipping host assicauted symbols into `symbolsInNestedRegions`.
+// Finally, in current context, lower all symbols in the set
+// `defaultSymbols` - `symbolsInNestedRegions`.
```
Comment (luporl) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:297]: Without reading `collectSymbols` code, this may leave the impression that this member function also does the lowering.

Maybe it could be changed to something like:
Later, in current context, all symbols in the set `defaultSymbols` - `symbolsInNestedRegions` will be privatized.

**Review by luporl — COMMENTED** [review]
Looks good, thanks for the comments explaining how default privatization works.

**Comment by kiranchandramohan** [comment]
Have all the changes been made here @NimishMishra? If so can @luporl approve?

**Comment by luporl** [comment]
> Have all the changes been made here @NimishMishra? If so can @luporl approve?

Besides some minor nitpicks, there is an issue remaining, that causes a regression in some specific cases, as when you have nested default clauses with `shared`, like the example below:

```
    !$omp parallel default(private)
        !$omp parallel default(firstprivate)
            x = y
        !$omp end parallel
        !$omp parallel default(private) shared(z)
            w = x + z
        !$omp end parallel
    !$omp end parallel 
```

In this case, `z` will end up being privatized in the inner parallel. https://github.com/llvm/llvm-project/pull/85989 fixes this.
I think it would be better to move that fix to this patch. But if we assume that https://github.com/llvm/llvm-project/pull/85989 is going to be merged soon and you are also ok with this, then this can be approved as is.

**Comment by NimishMishra** [comment]
I am okay with the changes in https://github.com/llvm/llvm-project/pull/85989; that merge can go ahead once this PR is merged. If @kiranchandramohan is fine with https://github.com/llvm/llvm-project/pull/85989, we can do thus. Otherwise, I will port the relevant code from that PR into this one. Let me know the preferred approach...

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 6]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
+  for (Fortran::lower::pft::Evaluation &nestedEval :
+       eval.getNestedEvaluations()) {
+    if (nestedEval.hasNestedEvaluations()) {
+      if (nestedEval.isConstruct())
+        // Recursively look for OpenMP constructs within `nestedEval`'s region
+        collectSymbolsInNestedRegions(nestedEval, flag, symbolsInNestedRegions);
+      else
+        converter.collectSymbolSet(nestedEval, symbolsInNestedRegions, flag,
+                                   /*collectSymbols=*/true,
+                                   /*collectHostAssociatedSymbols=*/false);
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:285]: Why is `collectHostAssociatedSymbols` `false` here? Is it because a previous invocation of collectSymbolSet has already collected it?

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 7]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
+// In step 2, for nested constructs (if any), if and only if
+// the nested construct is an OpenMP construct, collect those nested
+// symbols skipping host assicauted symbols into `symbolsInNestedRegions`.
+// Finally, in current context, lower all symbols in the set
+// `defaultSymbols` - `symbolsInNestedRegions`.
 void DataSharingProcessor::collectSymbols(
     Fortran::semantics::Symbol::Flag flag) {
   converter.collectSymbolSet(eval, defaultSymbols, flag,
                              /*collectSymbols=*/true,
                              /*collectHostAssociatedSymbols=*/true);
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:302]: Can this be folded into collectSymbolsInNestedRegions? I see the value of `collectHostAssociatedSymbols` is different.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 8]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
+                                   /*collectHostAssociatedSymbols=*/false);
+    }
+  }
+}
+
+// Collect symbols to be default privatized in two steps.
+// In step 1, collect all symbols in `eval` that match `flag`
+// into `defaultSymbols`.
+// In step 2, for nested constructs (if any), if and only if
+// the nested construct is an OpenMP construct, collect those nested
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:294]: Do you mean if it `not` an OpenMP construct?

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 9]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
+void DataSharingProcessor::collectSymbolsInNestedRegions(
+    Fortran::lower::pft::Evaluation &eval,
+    Fortran::semantics::Symbol::Flag flag,
+    llvm::SetVector<const Fortran::semantics::Symbol *>
+        &symbolsInNestedRegions) {
+  for (Fortran::lower::pft::Evaluation &nestedEval :
+       eval.getNestedEvaluations()) {
+    if (nestedEval.hasNestedEvaluations()) {
+      if (nestedEval.isConstruct())
+        // Recursively look for OpenMP constructs within `nestedEval`'s region
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:280]: Do you mean look for `non-OpenMP` constructs?

**Review by kiranchandramohan — APPROVED** [review]
I have a few questions. Otherwise looks OK.

> I am okay with the changes in https://github.com/llvm/llvm-project/pull/85989; that  merge can go ahead once this PR is merged. If @kiranchandramohan is fine with https://github.com/llvm/llvm-project/pull/85989, we can do thus. Otherwise, I will port the relevant code from that PR into this one. Let me know the preferred approach...

We can submit this and submit the relevant code either along with #85989 or as a separate patch.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp (hunk 6 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:285]: Yes that is correct.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp (hunk 7 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:302]: Actually, that might not work. `defaultSymbols` collect both the symbols as well as host-associations (if any). While `collectSymbolsInNestedRegions` skip host associations. This prevents any duplicate privatization

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp (hunk 8 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:294]: For non-OpenMP constructs, we skip collecting any symbols in `symbolsInNestedRegions`.

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 10]
```diff
@@ -268,21 +268,39 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
...
 }
 
+void DataSharingProcessor::collectSymbolsInNestedRegions(
+    Fortran::lower::pft::Evaluation &eval,
+    Fortran::semantics::Symbol::Flag flag,
+    llvm::SetVector<const Fortran::semantics::Symbol *>
+        &symbolsInNestedRegions) {
+  for (Fortran::lower::pft::Evaluation &nestedEval :
+       eval.getNestedEvaluations()) {
+    if (nestedEval.hasNestedEvaluations()) {
```
[the remark this answers is not in the document]
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:278]: I don't think so. All such constructs should have a block associated with them, and thus will be lowered as nested evals

**Comment by NimishMishra** [comment]
Thanks @luporl and @kiranchandramohan for the detailed reviews on this patch.

@luporl I have fixed description of `collectSymbolSet` as you mentioned. Does all look ok now? If so, could you approve the PR, post which I can submit it. Thanks!

**Comment by NimishMishra** [comment]
Have a `Error: clangformat failed to install`. Will try rebasing after a while and see if that is fixed.

**Review by luporl — APPROVED** [review]
LGTM. Thanks for all your work on this.

**Comment by NimishMishra** [comment]
Accidentally closed. Rebasing and reopening

**Comment by kiranchandramohan** [comment]
@NimishMishra Could you remind me why we want to skip collecting symbols in nested OpenMP regions?

**Comment by NimishMishra** [comment]
> @NimishMishra Could you remind me why we want to skip collecting symbols in nested OpenMP regions?

Sure @kiranchandramohan. We need to do that since `defaultSymbols` captures both the symbol and its host association. In the nested OpenMP region, we collect the nested symbol (but not the host associations, that is why we set `checkHostAssociatedSymbols = false` in nested regions).

If we don't do this, then privatization fails due to already existing bindings.

```
      std::function<void(const Fortran::semantics::Symbol &, bool)>
          insertSymbols = [&](const Fortran::semantics::Symbol &oriSymbol,
                              bool collectSymbol) {
            if (collectSymbol && oriSymbol.test(flag))
              symbolSet.insert(&oriSymbol);
            else if (checkHostAssociatedSymbols)
              if (const auto *details{
                      oriSymbol
                          .detailsIf<Fortran::semantics::HostAssocDetails>()})
                insertSymbols(details->symbol(), true);
          };
      insertSymbols(sym, collectSymbols);
    };
```

**Comment by NimishMishra** [comment]
I'm planning to spend time now on the documentation that you mentioned. I was held up mostly with the other issue, but now that is done. I'll send across a PR for review
