### PR TITLE
[flang][openacc][openmp] Support implicit casting on the atomic interface

### LINKED ISSUE #112911: [flang][OpenMP] atomic capture on complex variables with different kinds
The following program fails MLIR op verification for `omp.atomic.read`:

```
program o30_221a
  complex(4) :: a = 0
  complex(8) :: b
  !$omp parallel
    !$omp atomic capture
      a = a + (1,1)
      b = a
    !$omp end atomic
  !$omp end parallel
end program
```

```
./bin/flang -fopenmp /tmp/atomic2.f90
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: 'omp.atomic.read' op failed to verify that all of {x, v} have same type
error: verification of lowering to FIR failed
```
Using flang version `8e6abf526e74`

### PR DESCRIPTION
**Pull request by khaki3**
ACCMP atomics do not support type conversion. Specifically, I have encountered semantically incorrect code for atomic reads.

Example:

```
program main
  implicit none
  real(8) :: n
  integer :: x
  x = 1.0
  !$acc atomic capture
  n = x
  x = n
  !$acc end atomic
end program main
```

We have this error when compiling it with flang-new: `error: loc("rep.f90":6:9): expected three operations in atomic.capture region (one terminator, and two atomic ops)`

Yet, in the following generated FIR code, we observe three issues.

1. `fir.convert` intrudes into the capture region.
2. An incorrect temporary (`%2`) is being updated instead of `n`.
3. If we allow `n` in place of `%2`, the operand types of `atomic.read` do not match. Introducing a `!fir.ref<i32> -> !fir.ref<f64>` conversion on `x` is inaccurate because we need to convert the value of `x`.

```
    %2 = "fir.alloca"() <{in_type = i32, operandSegmentSizes = array<i32: 0, 0>}> : () -> !fir.ref<i32>
    %3 = "fir.alloca"() <{bindc_name = "n", in_type = f64, operandSegmentSizes = array<i32: 0, 0>, uniq_name = "_QFEn"}> : () -> !fir.ref<f64>
    %4:2 = "hlfir.declare"(%3) <{operandSegmentSizes = array<i32: 1, 0, 0, 0>, uniq_name = "_QFEn"}> : (!fir.ref<f64>) -> (!fir.ref<f64>, !fir.ref<f64>)
    %5 = "fir.alloca"() <{bindc_name = "x", in_type = i32, operandSegmentSizes = array<i32: 0, 0>, uniq_name = "_QFEx"}> : () -> !fir.ref<i32>
    %6:2 = "hlfir.declare"(%5) <{operandSegmentSizes = array<i32: 1, 0, 0, 0>, uniq_name = "_QFEx"}> : (!fir.ref<i32>) -> (!fir.ref<i32>, !fir.ref<i32>)
    %7 = "arith.constant"() <{value = 1 : i32}> : () -> i32
    "hlfir.assign"(%7, %6#0) : (i32, !fir.ref<i32>) -> ()
    %8 = "fir.load"(%4#0) : (!fir.ref<f64>) -> f64
    %9 = "fir.convert"(%8) : (f64) -> i32
    "fir.store"(%9, %2) : (i32, !fir.ref<i32>) -> ()
    %10 = "fir.load"(%6#0) : (!fir.ref<i32>) -> i32
    %11 = "fir.convert"(%10) : (i32) -> f64
    "acc.atomic.capture"() ({
      "acc.atomic.read"(%2, %6#1) <{element_type = f64}> : (!fir.ref<i32>, !fir.ref<i32>) -> ()
      %12 = "fir.convert"(%11) : (f64) -> i32
      "acc.atomic.write"(%2, %12) : (!fir.ref<i32>, i32) -> ()
      "acc.terminator"() : () -> ()
    }) : () -> ()
```

This PR updates `flang/lib/Lower/DirectivesCommon.h` to solve the issues by taking the following approaches (from top to bottom):

1. Move `fir.convert` for `atomic.write` out of the capture region.
2. Remove the `!fir.ref<i32> -> !fir.ref<f64>` conversion found in `genOmpAccAtomicRead`.
3. Eliminate unnecessary `genExprAddr` calls on the RHS, which create an invalid temporary for `x = 1.0`.
4. When generating a capture operation, refer to the original LHS instead of the type-casted RHS.

Here, we have to allow for the cases where the operand types of `atomic.read` differ from one another. Thus, this PR also removes the `AllTypesMatch` trait from both `acc.atomic.read` and `omp.atomic.read`.

The example code is converted as follows:

```
    %0 = fir.alloca f64 {bindc_name = "n", uniq_name = "_QFEn"}
    %1:2 = hlfir.declare %0 {uniq_name = "_QFEn"} : (!fir.ref<f64>) -> (!fir.ref<f64>, !fir.ref<f64>)
    %2 = fir.alloca i32 {bindc_name = "x", uniq_name = "_QFEx"}
    %3:2 = hlfir.declare %2 {uniq_name = "_QFEx"} : (!fir.ref<i32>) -> (!fir.ref<i32>, !fir.ref<i32>)
    %c1_i32 = arith.constant 1 : i32
    hlfir.assign %c1_i32 to %3#0 : i32, !fir.ref<i32>
    %4 = fir.load %1#0 : !fir.ref<f64>
    %5 = fir.convert %4 : (f64) -> i32
    acc.atomic.capture {
      acc.atomic.read %1#1 = %3#1 : !fir.ref<f64>, !fir.ref<i32>, i32
      acc.atomic.write %3#1 = %5 : !fir.ref<i32>, i32
    }
```

Fixes #112911.

### CODE REVIEW

**Comment by khaki3** [comment]
Probably, instead of this PR, we should put temps around the capture so that

```
  real :: n
  integer :: x
  !$acc atomic capture
  n = x
  x = n * n
  !$acc end atomic
```

becomes

```
  real :: n
  integer :: x, n_tmp
  %0 = float(n_tmp)
  %1 = %0 * %0
  !$acc atomic capture
  n_tmp = x
  x = %0
  !$acc end atomic
  n = n_tmp
```

Closing this PR.

**Comment by khaki3** [comment]
Regarding #93776, it appears to have a  `!fir.ref<i32> -> !fir.ref<f64>` conversion, which is not suitable here.

**Comment by khaki3** [comment]
Another idea is to assume a converted reference type on the LHS of `atomic.read`. The verifier checks if `x`s of `read` and `write` are the same, so we cannot convert `x` only for `read`.

```
  real :: n
  integer :: x
  !$acc atomic capture
  n = x
  x = n * n
  !$acc end atomic
```

could become

```
    %0 = fir.alloca f32 {bindc_name = "n", uniq_name = "_QFEn"}
    %1:2 = hlfir.declare %0 {uniq_name = "_QFEn"} : (!fir.ref<f32>) -> (!fir.ref<f32>, !fir.ref<f32>)
    %2 = fir.convert %1#1 : (!fir.ref<f32>) -> !fir.ref<i32>
    %3 = fir.alloca i32 {bindc_name = "x", uniq_name = "_QFEx"}
    %4:2 = hlfir.declare %3 {uniq_name = "_QFEx"} : (!fir.ref<i32>) -> (!fir.ref<i32>, !fir.ref<i32>)
    %5 = fir.load %1#0 : !fir.ref<f32>
    %6 = fir.load %1#0 : !fir.ref<f32>
    %7 = arith.mulf %5, %6 fastmath<contract> : f32
    %8 = fir.convert %7 : (f32) -> i32
    acc.atomic.capture {
      acc.atomic.read %2 = %4#1 : !fir.ref<i32>, f32
      acc.atomic.write %4#1 = %8 : !fir.ref<i32>, i32
    }
```

My first attempt was to extend the declaration of `read` to accept the original type of `v`. But it was a destructive change. The current change in this PR adds a temp for the `read` LHS.

File: flang/lib/Lower/DirectivesCommon.h [hunk 1]
```diff
@@ -411,12 +417,22 @@ void genOmpAccAtomicRead(Fortran::lower::AbstractConverter &converter,
...
       *Fortran::semantics::GetExpr(assignmentStmtVariable), stmtCtx));
   fir::FirOpBuilder &builder = converter.getFirOpBuilder();
-  if (fromAddress.getType() != toAddress.getType())
-    fromAddress =
-        builder.create<fir::ConvertOp>(loc, toAddress.getType(), fromAddress);
-  genOmpAccAtomicCaptureStatement(converter, fromAddress, toAddress,
+  mlir::Value LHSTemp = toAddress;
+  if (fromAddress.getType() != toAddress.getType()) {
+    // Create a temp for implicit type conversion.
+    LHSTemp = builder.create<fir::AllocaOp>(
```
Comment (tblah) [inline flang/lib/Lower/DirectivesCommon.h:423]: You can use `fir::FirOpBuilder::getAllocaBlock` to find an appropriate place to insert an alloca.

Putting it here runs the risk of allocating stack space inside of a loop.

**Review by tblah — COMMENTED** [review]
Thanks for the fix. I think this will also fix an OpenMP issue https://github.com/llvm/llvm-project/issues/112911

This looks good to me (with one comment), but please wait for another reviewer to take a look as well.

File: flang/lib/Lower/DirectivesCommon.h (hunk 1 above)
Comment (khaki3) [reply flang/lib/Lower/DirectivesCommon.h]: Thank you for your comment. I tried `createTemporary` in the FIR builder. But that caused an issue in the operation walk.  Maybe I could take a different approach. This line was already deleted in the latest change.

**Comment by khaki3** [comment]
I believe it is reasonable to add a type declaration for the `v` of `atomic.read` because the `!fir.ref<f32> -> !fir.ref<i32>` conversion is meaningless, and we should eliminate unnecessary operations.

I reverted my changes. Other two approaches can be found in the commits.

**Review by razvanlupusoru — APPROVED** [review]
This looks better with no temp. Seems reasonable to not require same type and to relax this on the atomic ops. Looks good to me.
