### PR TITLE
[mlir][func] Fix crashes in FuncToLLVM discardable attributes propagation logic

### LINKED ISSUE #181464: [MLIR] Crash in FuncToLLVM conversion during -gpu-lower-to-nvvm-pipeline when creating LLVMFuncOp
Hi, I found a crash in the pass `-gpu-lower-to-nvvm-pipeline`. See the following code example:

#### Code Example
```llvm
module {
  func.func @host() attributes {linkage = #llvm.linkage<internal>} {
    %0 = arith.constant 1.0 : f64
    %1 = arith.constant 2.0 : f64
    %2 = arith.cmpf "ogt", %0, %1 : f64
    %3 = arith.select %2, %0, %1 : f64
    return
  }
  gpu.module @gpu_mod {
    gpu.func @gpu_kernel() kernel {
      gpu.return
    }
  }
}
```

#### Stack Trace
```bash
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: mlir-opt ext_integer.mlir -gpu-lower-to-nvvm-pipeline
 #0 0x00005747e6ece87d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /llvm/lib/Support/Unix/Signals.inc:842:11
 #1 0x00005747e6ecedab PrintStackTraceSignalHandler(void*) /llvm/lib/Support/Unix/Signals.inc:924:1
 #2 0x00005747e6eccc64 llvm::sys::RunSignalHandlers() /llvm/lib/Support/Signals.cpp:108:5
 #3 0x00005747e6ecf449 SignalHandler(int, siginfo_t*, void*) /llvm/lib/Support/Unix/Signals.inc:429:38
 #4 0x000078a20e445330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #5 0x000078a20e49eb2c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x000078a20e49eb2c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #7 0x000078a20e49eb2c pthread_kill ./nptl/pthread_kill.c:89:10
 #8 0x000078a20e44527e raise ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x000078a20e4288ff abort ./stdlib/abort.c:81:7
#10 0x000078a20e42881b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#11 0x000078a20e43b517 (/lib/x86_64-linux-gnu/libc.so.6+0x3b517)
#12 0x00005747f56cb793 mlir::DictionaryAttr::sortInPlace(llvm::SmallVectorImpl<mlir::NamedAttribute>&) /mlir/lib/IR/BuiltinAttributes.cpp:128:10
#13 0x00005747f583884a mlir::NamedAttrList::getDictionary(mlir::MLIRContext*) const /mlir/lib/IR/OperationSupport.cpp:56:5
#14 0x00005747f58299f0 mlir::Operation::create(mlir::OperationState const&) /mlir/lib/IR/Operation.cpp:37:31
#15 0x00005747f56be391 mlir::OpBuilder::create(mlir::OperationState const&) /mlir/lib/IR/Builders.cpp:458:17
#16 0x00005747f404a460 mlir::LLVM::LLVMFuncOp::create(mlir::OpBuilder&, mlir::Location, llvm::StringRef, mlir::Type, mlir::LLVM::linkage::Linkage, bool, mlir::LLVM::cconv::CConv, mlir::SymbolRefAttr, llvm::ArrayRef<mlir::NamedAttribute>, llvm::ArrayRef<mlir::DictionaryAttr>, std::optional<unsigned long>) /build_all/tools/mlir/include/mlir/Dialect/LLVMIR/LLVMOps.cpp.inc:33007:55
#17 0x00005747efc8b3c9 mlir::convertFuncOpToLLVMFuncOp(mlir::FunctionOpInterface, mlir::ConversionPatternRewriter&, mlir::LLVMTypeConverter const&, mlir::SymbolTableCollection*) /mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp:360:20
#18 0x00005747efc90c52 (anonymous namespace)::FuncOpConversion::matchAndRewrite(mlir::func::FuncOp, mlir::func::FuncOpAdaptor, mlir::ConversionPatternRewriter&) const /mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp:493:45
#19 0x00005747e7073f59 llvm::LogicalResult mlir::ConversionPattern::dispatchTo1To1<mlir::ConvertOpToLLVMPattern<mlir::func::FuncOp, false>, mlir::func::FuncOp>(mlir::ConvertOpToLLVMPattern<mlir::func::FuncOp, false> const&, mlir::func::FuncOp, mlir::func::FuncOp::GenericAdaptor<llvm::ArrayRef<mlir::ValueRange>>, mlir::ConversionPatternRewriter&) /mlir/include/mlir/Transforms/DialectConversion.h:1069:15
#20 0x00005747e7072b73 mlir::ConvertOpToLLVMPattern<mlir::func::FuncOp, false>::matchAndRewrite(mlir::func::FuncOp, mlir::func::FuncOpGenericAdaptor<llvm::ArrayRef<mlir::ValueRange>>, mlir::ConversionPatternRewriter&) const /mlir/include/mlir/Conversion/LLVMCommon/Pattern.h:265:12
#21 0x00005747e7072acc mlir::ConvertOpToLLVMPattern<mlir::func::FuncOp, false>::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::ValueRange>, mlir::ConversionPatternRewriter&) const /mlir/include/mlir/Conversion/LLVMCommon/Pattern.h:251:12
#22 0x00005747f51eff69 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const /mlir/lib/Transforms/Utils/DialectConversion.cpp:2409:10
#23 0x00005747f5287228 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::$_0::operator()() const /mlir/lib/Rewrite/PatternApplicator.cpp:223:31
#24 0x00005747f5286ed5 void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::$_0>(long) /llvm/include/llvm/ADT/STLFunctionalExtras.h:46:5
#25 0x00005747e6ef4a19 llvm::function_ref<void ()>::operator()() const /llvm/include/llvm/ADT/STLFunctionalExtras.h:69:5
#26 0x00005747f5288a2b void mlir::MLIRContext::executeAction<mlir::ApplyPatternAction, mlir::Pattern const&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pattern const&) /mlir/include/mlir/IR/MLIRContext.h:291:3
#27 0x00005747f52852ba mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>) /mlir/lib/Rewrite/PatternApplicator.cpp:242:9
#28 0x00005747f51fca58 (anonymous namespace)::OperationLegalizer::legalizeWithPattern(mlir::Operation*) /mlir/lib/Transforms/Utils/DialectConversion.cpp:2829:21
#29 0x00005747f51f0c62 (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*) /mlir/lib/Transforms/Utils/DialectConversion.cpp:2608:17
#30 0x00005747f51f0532 mlir::OperationConverter::convert(mlir::Operation*, bool) /mlir/lib/Transforms/Utils/DialectConversion.cpp:3306:26
#31 0x00005747f51f15fd llvm::LogicalResult mlir::OperationConverter::legalizeOperations<mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>)::$_0>(llvm::ArrayRef<mlir::Operation*>, mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>)::$_0, bool) /mlir/lib/Transforms/Utils/DialectConversion.cpp:3407:16
#32 0x00005747f51f11ae mlir::OperationConverter::applyConversion(llvm::ArrayRef<mlir::Operation*>) /mlir/lib/Transforms/Utils/DialectConversion.cpp:3453:26
#33 0x00005747f5201d2c applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode)::$_0::operator()() const /mlir/lib/Transforms/Utils/DialectConversion.cpp:4176:30
#34 0x00005747f5201c95 void llvm::function_ref<void ()>::callback_fn<applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode)::$_0>(long) /llvm/include/llvm/ADT/STLFunctionalExtras.h:46:5
#35 0x00005747e6ef4a19 llvm::function_ref<void ()>::operator()() const /llvm/include/llvm/ADT/STLFunctionalExtras.h:69:5
#36 0x00005747f521df83 void mlir::MLIRContext::executeAction<ApplyConversionAction>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>) /mlir/include/mlir/IR/MLIRContext.h:291:3
#37 0x00005747f51f4da8 applyConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig, (anonymous namespace)::OpConversionMode) /mlir/lib/Transforms/Utils/DialectConversion.cpp:4180:1
#38 0x00005747f51f4c5c mlir::applyPartialConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) /mlir/lib/Transforms/Utils/DialectConversion.cpp:4189:10
#39 0x00005747f51f4e45 mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) /mlir/lib/Transforms/Utils/DialectConversion.cpp:4196:10
#40 0x00005747efc8ef9c (anonymous namespace)::ConvertFuncToLLVMPass::runOnOperation() /mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp:843:16
#41 0x00005747f5347e74 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_3::operator()() const /mlir/lib/Pass/Pass.cpp:0:19
#42 0x00005747f5347e15 void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_3>(long) /llvm/include/llvm/ADT/STLFunctionalExtras.h:46:5
#43 0x00005747e6ef4a19 llvm::function_ref<void ()>::operator()() const /llvm/include/llvm/ADT/STLFunctionalExtras.h:69:5
#44 0x00005747f534b31b void mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) /mlir/include/mlir/IR/MLIRContext.h:291:3
#45 0x00005747f533f2be mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /mlir/lib/Pass/Pass.cpp:619:17
#46 0x00005747f533f9da mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) /mlir/lib/Pass/Pass.cpp:688:16
#47 0x00005747f53452bd mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) /mlir/lib/Pass/Pass.cpp:1123:10
#48 0x00005747f5344846 mlir::PassManager::run(mlir::Operation*) /mlir/lib/Pass/Pass.cpp:1097:60
#49 0x00005747e6fd8dfb performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:591:17
#50 0x00005747e6fd84d1 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, mlir::SourceMgrDiagnosticVerifierHandler*, llvm::ThreadPoolInterface*) /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:673:12
#51 0x00005747e6fd818c mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef, llvm::raw_ostream&) const /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:771:12
#52 0x00005747e6fd8096 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&) /llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#53 0x00005747f58a4c5a llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&) const /llvm/include/llvm/ADT/STLFunctionalExtras.h:69:12
#54 0x00005747f58a401a mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) /mlir/lib/Support/ToolUtilities.cpp:30:12
#55 0x00005747e6fd3e16 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:776:26
#56 0x00005747e6fd4215 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:822:14
#57 0x00005747e6fd43e8 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) /mlir/lib/Tools/mlir-opt/MlirOptMain.cpp:838:10
#58 0x00005747e6ea3485 main /mlir/tools/mlir-opt/mlir-opt.cpp:347:33
#59 0x000078a20e42a1ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#60 0x000078a20e42a28b call_init ./csu/../csu/libc-start.c:128:20
#61 0x000078a20e42a28b __libc_start_main ./csu/../csu/libc-start.c:347:5
#62 0x00005747e6ea32f5 _start (/mnt/raid/build_all/bin/mlir-opt+0x46a92f5)
Aborted
```

### PR DESCRIPTION
**Pull request by hockyy**
Refactor how `func.func` discardable attributes are handled in the Func-to-LLVM conversion. Instead of ad hoc checks for linkage and readnone followed by a simple filter, the pass now generically processes inherent attributes from LLVMFuncOp.

Attributes that correspond to inherent `llvm.func` ODS names can be attached as `llvm.<name>` on `func.func` and are stripped to `<name>` when building `LLVM::LLVMFuncOp`, so LLVM-specific knobs stay namespaced on the source op but land on the right inherent slots on `llvm.func`.

Other discardable attributes continue to be propagated as-is.

Fixes #175959
Fixes #181464

Assisted-by: CLion code completion, GPT 5.3-Codex

### CODE REVIEW

File: mlir/lib/Dialect/Func/IR/FuncOps.cpp [hunk 1]
```diff
@@ -280,6 +280,16 @@ FuncOp FuncOp::clone() {
...
 
+/// TODO: Should we add some exception for attributes that are not
+/// dialect-prefixed?
+LogicalResult FuncOp::verify() {
+  for (const NamedAttribute &attr : (*this)->getDiscardableAttrs()) {
+    if (attr.getNameDialect())
+      continue;
+  }
+  return success();
+}
```
Comment (joker-eph) [inline mlir/lib/Dialect/Func/IR/FuncOps.cpp]: This does not do anything right now.

File: mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp [hunk 2]
```diff
@@ -59,19 +68,114 @@ static bool shouldUseBarePtrCallConv(Operation *op,
...
+/// Add custom lowered funcOp to llvm.func attributes here.
+struct LoweredFuncAttrs {
+  LLVM::Linkage linkage = LLVM::Linkage::External;
+  bool hasReadnone = false;
+  SmallVector<NamedAttribute, 4> attrs;
+};
+
+static LogicalResult lowerLinkageAttr(FunctionOpInterface func,
+                                      Attribute attrValue,
+                                      LoweredFuncAttrs &lowered) {
```
Comment (joker-eph) [inline mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp]: You just need a reference to the linkage here, not the full structure.

File: mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp [hunk 3]
```diff
@@ -59,19 +68,114 @@ static bool shouldUseBarePtrCallConv(Operation *op,
...
+  return success();
+}
+
+static LogicalResult lowerReadnoneAttr(FunctionOpInterface func,
+                                       Attribute attrValue,
+                                       LoweredFuncAttrs &lowered) {
+  StringRef readnoneAttrName = LLVM::LLVMDialect::getReadnoneAttrName();
+  if (!isa<UnitAttr>(attrValue)) {
+    func->emitError() << "Contains " << readnoneAttrName
+                      << " attribute not of type UnitAttr";
```
Comment (joker-eph) [inline mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp]: You're emitting an error, but this may not lead to a complete failure in case of a partial conversion. This is an anti-pattern.

File: mlir/lib/Dialect/Async/Transforms/AsyncToAsyncRuntime.cpp [hunk 4]
```diff
@@ -242,8 +242,8 @@ static CoroMachinery setupCoroMachinery(func::FuncOp func) {
 
   // The switch-resumed API based coroutine should be marked with
   // presplitcoroutine attribute to mark the function as a coroutine.
-  func->setAttr("passthrough", builder.getArrayAttr(
-                                   StringAttr::get(ctx, "presplitcoroutine")));
+  func->setAttr("llvm.passthrough", builder.getArrayAttr(StringAttr::get(
```
[the remark this answers is not in the document]
Comment (hockyy) [reply mlir/lib/Dialect/Async/Transforms/AsyncToAsyncRuntime.cpp]: As mentioned by @jeanPerier, it seems like we can't simply discard ALL discardable attributes from `func.func`

File: mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp [hunk 5]
```diff
@@ -47,7 +48,15 @@ namespace mlir {
 using namespace mlir;
 
 #define PASS_NAME "convert-func-to-llvm"
-
+#define DEBUG_TYPE PASS_NAME
+
+// Attribute names on `func.func` consumed by this conversion.
```
[the remark this answers is not in the document]
Comment (hockyy) [reply mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp]: Yes, now that I have seen the consumer, it's handling only some specific special attributes inside this function. The rest of them get passed to LLVMFuncOp

**Comment by hockyy** [comment]
So the behavior that I expect is:
- If it has the `llvm.*` prefix, remove it, and **propagate** it to LLVMFuncOp.
	- `llvm.passthrough` -> `passthrough`
	- `llvm.target_cpu` -> `target_cpu`
	- `llvm.target_features` -> `target_features`
	- `llvm.tune_cpu` -> `tune_cpu`
- If it has an ODS attribute name without the prefix, remove it OR, **keep it, and report an error during LLVMFuncOp creation** because it will crash the builder.
    - `linkage` only -> remove it
    - `passthrough` only -> remove it
- If it has special meaning, parse it, and assign it and put the info in `LoweredFuncAttrs`
	- `llvm.linkage` -> parse it
	- `llvm.readnone` -> parse it
- Other than that, should be an undefined behavior. Because the legacy code is propagating all of the attributes, I will just add it to `lowered.attrs`

cc @matthias-springer, sorry for tagging, I considered your comment https://github.com/llvm/llvm-project/pull/182987#discussion_r2845064902 here, but instead of letting it crash, I'm thinking of refactoring the attribute passing, and erroring out the creation when it's finding a duplicated attribute names.

> To work around the crash, you could error out before creating the llvm.func op if you detect an attribute that's defined in the ODS of llvm.func. However, there are around 50 attributes on llvm.func (each of which can likely reproduce this crash), and hard-coding these does not seem right. (I do not know of any mechanism to enumerate all ODS-defined attribute names.)

File: mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp [hunk 6]
```diff
@@ -59,19 +68,114 @@ static bool shouldUseBarePtrCallConv(Operation *op,
...
+    StringRef inherent = attrName;
+    LDBG() << "inherent: " << inherent;
+    if (inherent.consume_front("llvm.")) {
+      if (odsAttrNames.contains(inherent)) {
+        LDBG() << "inserting to attrs: " << inherent;
+        lowered.attrs.emplace_back(StringAttr::get(ctx, inherent),
+                                   attr.getValue());
+      }
+    } else {
+      lowered.attrs.push_back(attr);
```
[the remark this answers is not in the document]
Comment (hockyy) [reply mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp]: > To be clear: this quote is a generality about the MLIR verifier, not something specific about this transformation.
> 
> But also:
> 
> > here, we will remove only these three linkageAttrName, varargsAttrName, and LLVM::LLVMDialect::getReadnoneAttrName(). The rest of them is going through.
> 
> Can you clarify how a `llvm.foo` attribute gets propagated here?

I see...
```mlir
hocky@hocky:~/llvm-project/build_clion$ mlir-opt tc.mlir
module {
  func.func @host_next_to_gpu_module() attributes {llvm.foo, llvm.linkage = #llvm.linkage<internal>} {
    return
  }
  gpu.module @gpu_mod {
    gpu.func @gpu_kernel() kernel {
      gpu.return
    }
  }
}

hocky@hocky:~/llvm-project/build_clion$ mlir-opt tc.mlir --convert-func-to-llvm
module {
  llvm.func internal @host_next_to_gpu_module() attributes {llvm.foo} {
    llvm.return
  }
  gpu.module @gpu_mod {
    gpu.func @gpu_kernel() kernel {
      gpu.return
    }
  }
}

```

This is the legacy behavior

File: flang/lib/Optimizer/Transforms/VScaleAttr.cpp [hunk 7]
```diff
@@ -48,6 +50,14 @@ namespace fir {
 
 namespace {
 
+/// See FunctionAttr.cpp: `llvm.func` properties on `func.func` need the `llvm.`
+/// prefix for convert-func-to-llvm.
+static mlir::StringAttr getLlvmFuncPropertyAttrName(mlir::MLIRContext *ctx,
+                                                    mlir::StringAttr baseName) {
+  std::string storage = (llvm::Twine("llvm.") + baseName.getValue()).str();
+  return mlir::StringAttr::get(ctx, storage);
```
Comment (joker-eph) [inline flang/lib/Optimizer/Transforms/VScaleAttr.cpp]: Same

**Review by joker-eph — COMMENTED** [review]
Thanks! This LGTM overall, modulo some inline comments.

Can you also add a clear documentation for the attributes handling behavior in the pass documentation?

**Review by joker-eph — APPROVED** [review]

**Comment by antmox** [comment]
@joker-eph I can help on the buildbot machine if needed

**Comment by joker-eph** [comment]
Actually the mlir-opt part of the test which involves this pass is independent of the JIT environment, so I could run it locally, here is the diff:
```
$ diff /tmp/after  /tmp/before 
5c5
<   llvm.func @matmul_transpose_a(%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: i64, %arg3: i64, %arg4: i64, %arg5: i64, %arg6: i64, %arg7: !llvm.ptr, %arg8: !llvm.ptr, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64, %arg13: i64, %arg14: !llvm.ptr, %arg15: !llvm.ptr, %arg16: i64, %arg17: i64, %arg18: i64, %arg19: i64, %arg20: i64) {
---
>   llvm.func @matmul_transpose_a(%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: i64, %arg3: i64, %arg4: i64, %arg5: i64, %arg6: i64, %arg7: !llvm.ptr, %arg8: !llvm.ptr, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64, %arg13: i64, %arg14: !llvm.ptr, %arg15: !llvm.ptr, %arg16: i64, %arg17: i64, %arg18: i64, %arg19: i64, %arg20: i64) attributes {arm_locally_streaming, arm_new_za} {

```

So we have two attributes that gets dropped unexpectedly here, because they aren't prefixed. 

The fix is to add the `llvm.` prefix in `mlir/lib/Dialect/ArmSME/Transforms/EnableArmStreaming.cpp`
