### PR TITLE
[analyzer] Detect use-after-free for field address (e.g., &ptr->field)

### LINKED ISSUE #152446: Clang Static Analyzer (MallocChecker) misses use-after-free via field address (e.g. &ptr->field)
Clang Static Analyzer's `MallocChecker` currently **fails to detect use-after-free** when the memory is accessed via the address of a field inside a freed structure.

For example, the following use-after-free goes undetected:

```c
#include <stdlib.h>

struct Obj {
  int field;
};

void use(void *);

void test() {
  struct Obj *o = malloc(sizeof(struct Obj));
  free(o);
  use(&o->field); // ⚠️ No warning reported by CSA (MallocChecker)
}
```
In this example, the heap memory pointed to by o has been freed, yet &o->field is passed to a function. This is a classic use-after-free bug, but MallocChecker does not currently report it.
Root Cause
In MallocChecker.cpp, argument checking currently relies on:
```cpp
SymbolRef Sym = ArgSVal.getAsSymbol();
```
This fails for field address expressions like &ptr->field, because such expressions produce a MemRegionVal, and getAsSymbol() does not extract the base symbol in those cases.

### PR DESCRIPTION
**Pull request by LoboQ1ng**
This patch improves MallocChecker to detect use-after-free bugs when
a freed structure's field is passed by address (e.g., `&ptr->field`).

Previously, MallocChecker would miss such cases, as it only checked the top-level symbol of argument values.
This patch analyzes the base region of arguments and extracts the symbolic region (if any), allowing UAF detection even for field address expressions.

Fixes #152446

### CODE REVIEW

**Comment by steakhal** [comment]
Hey, thanks for contributing!

I usually look at the tests before looking at the actual change. Could you demonstrate the improvement?
You can grep for files containing similar diagnostics under the `clang/test/Analysis` folder if you look for the report messages. Pick one file which seems relevant to add your tests to.

**Comment by LoboQ1ng** [comment]
> Hey, thanks for contributing!
> 
> I usually look at the tests before looking at the actual change. Could you demonstrate the improvement? You can grep for files containing similar diagnostics under the `clang/test/Analysis` folder if you look for the report messages. Pick one file which seems relevant to add your tests to.

Okay, I’ve now submitted a new test at clang/test/Analysis/malloc-checker-arg-uaf.c. It should help illustrate the improvement I made.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 1]
```diff
@@ -3156,8 +3156,14 @@ void MallocChecker::checkPreCall(const CallEvent &Call,
...
     if (isa<Loc>(ArgSVal)) {
-      SymbolRef Sym = ArgSVal.getAsSymbol();
-      if (!Sym)
+      const MemRegion *MR = ArgSVal.getAsRegion();
+      if (!MR)
+        continue;
+      const MemRegion *BaseRegion = MR->getBaseRegion();
+      SymbolRef Sym = nullptr;
+      if (const auto *SR = dyn_cast<SymbolicRegion>(BaseRegion))
+        Sym = SR->getSymbol();
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3165]:
```suggestion
      SymbolRef Sym = ArgSVal.getAsSymbol(/*IncludeBaseRegions=*/true);
```
Your code is completely correct and does the right thing, but it can be shortened by using the optional argument of `getAsSymbol` (which will do the same thing).

Comment (LoboQ1ng) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp]: Thank you for the suggestion! Your patch is indeed a better approach. I hadn't seen `getAsSymbol` used that way before — it's really convenient. I appreciate you pointing it out!

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 2]
```diff
@@ -3156,8 +3156,8 @@ void MallocChecker::checkPreCall(const CallEvent &Call,
   for (unsigned I = 0, E = Call.getNumArgs(); I != E; ++I) {
     SVal ArgSVal = Call.getArgSVal(I);
     if (isa<Loc>(ArgSVal)) {
-      SymbolRef Sym = ArgSVal.getAsSymbol();
-      if (!Sym)
+      SymbolRef Sym = ArgSVal.getAsSymbol(/*IncludeBaseRegions=*/true);
+      if (!Sym)
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:3160]:
```suggestion
      if (!Sym)
```

File: clang/test/Analysis/malloc-checker-arg-uaf.c [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+  free(o);
+  use(o);   // expected-warning{{Use of memory after it is freed}}
+}
+
+void test_nested_field() {
+    struct Obj *o = malloc(sizeof(struct Obj));
+    int *f = &o->field;
+    free(o);
+    use(f); // expected-warning{{Use of memory after it is freed}}
+}
```
Comment (steakhal) [inline clang/test/Analysis/malloc-checker-arg-uaf.c:44]:
```suggestion
}

```

File: clang/test/Analysis/malloc-checker-arg-uaf.c [hunk 4]
```diff
@@ -0,0 +1,44 @@
+// RUN: %clang_analyze_cc1 -analyzer-checker=unix.Malloc -verify %s
```
Comment (steakhal) [inline clang/test/Analysis/malloc-checker-arg-uaf.c:1]:
```suggestion
// RUN: %clang_analyze_cc1 -analyzer-checker=core,unix.Malloc -verify %s
```

File: clang/test/Analysis/malloc-checker-arg-uaf.c [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+
+void test_nested_alloc() {
+  struct Obj *o = (struct Obj *)malloc(sizeof(struct Obj));
+  use(o);   // no-warning
+  free(o);
+  use(o);   // expected-warning{{Use of memory after it is freed}}
+}
+
+void test_nested_field() {
+    struct Obj *o = malloc(sizeof(struct Obj));
```
Comment (steakhal) [inline clang/test/Analysis/malloc-checker-arg-uaf.c:40]:
```suggestion
    struct Obj *o = (struct Obj *)malloc(sizeof(struct Obj));
```

**Review by steakhal — APPROVED** [review]
Thank you for your finding. ~It will be automatically merged once the CI bots are happy.~
It seems like I'll need to come back to this and check if the bots are green, and merge the PR.
