### PR TITLE
[HLSL] Make load methods take const attribute

### LINKED ISSUE #192557: [HLSL] RWByteAddressBuffer::Load not marked const, preventing use through const references
Calling Load on a const RWByteAddressBuffer fails because the method is not marked const. DXC accepts this pattern.

Repro:

```hlsl
 RWByteAddressBuffer gBuf : register(u0);
 
 void UseConst(const RWByteAddressBuffer buf, out uint val) {
     val = buf.Load(0);
 }
 
 [numthreads(1,1,1)]
 void main() {
     const RWByteAddressBuffer local = gBuf;
     uint val;
     UseConst(local, val);
     gBuf.Store(0, val);
 }
```

Command: `clang-dxc -T cs_6_0 -Fo out.o input.hlsl`

Error:
```
 error: no matching member function for call to 'Load'
 note: candidate function not viable: 'this' argument has type 'const RWByteAddressBuffer', but method is not marked const
```
Clang version: 23.0.0git (commit 2a2ba99)

### PR DESCRIPTION
**Pull request by bob80905**
Previously, HLSL shaders that declare a local resource const, cannot use the `Load` method, since it is not attributed with const.
Load does not change a resource, it is a read-only operation, so the method should be marked const.
This PR changes the methods so that they are marked const.
Fixes https://github.com/llvm/llvm-project/issues/192557

Assisted by: Github Copilot

### CODE REVIEW

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp [hunk 1]
```diff
@@ -2253,12 +2256,12 @@ BuiltinTypeDeclBuilder &BuiltinTypeDeclBuilder::addHandleAccessFunction(
 
   if (IsRef) {
     ReturnTy = AddrSpaceElemTy;
-    if (IsConst)
+    if (IsConstReturn)
       ReturnTy.addConst();
```
Comment (s-perron) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp:2262]: Could this be done more easily by saying that we don't add const if we return by value?

```suggestion
    if (IsConstMethod && IsRef)
      ReturnTy.addConst();
```

Then we don't need the extra parameter.

**Review by tex3d — COMMENTED** [review]
I believe the constness of the returned value is independent from the constness of the method and the constness of the resource object instance itself. All resource methods should be const, since none of them change the handle.

See: https://github.com/microsoft/hlsl-specs/blob/main/proposals/0007-const-member-functions.md#const-correct-resources

**Comment by bob80905** [comment]
Yes, I agree with you.
I will revert back to the commit where we could specify return type constness and method constness independently.
Maintaining scope to the load method, however, would be ideal.

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp [hunk 2]
```diff
@@ -1408,9 +1409,10 @@ BuiltinTypeDeclBuilder &BuiltinTypeDeclBuilder::addLoadMethods() {
   IdentifierInfo &II = AST.Idents.get("Load", tok::TokenKind::identifier);
   DeclarationName Load(&II);
   // TODO: We also need versions with status for CheckAccessFullyMapped.
-  addHandleAccessFunction(Load, /*IsConst=*/false, /*IsRef=*/false,
+  addHandleAccessFunction(Load, /*IsConstMethod=*/true,
+                          /*IsConstReturn=*/false, /*IsRef=*/false,
                           AST.UnsignedIntTy);
-  addLoadWithStatusFunction(Load, /*IsConst=*/false);
+  addLoadWithStatusFunction(Load, /*IsConstMethod=*/true);
```
Comment (s-perron) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp]: If `IsConstMethod` is always true, we could just remove the parameter.

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp [hunk 3]
```diff
@@ -2253,12 +2256,12 @@ BuiltinTypeDeclBuilder &BuiltinTypeDeclBuilder::addHandleAccessFunction(
...
     ReturnTy = AddrSpaceElemTy;
-    if (IsConst)
+    if (IsConstReturn)
       ReturnTy.addConst();
     ReturnTy = AST.getLValueReferenceType(ReturnTy);
   } else {
     ReturnTy = ElemTy;
-    if (IsConst)
+    if (IsConstReturn)
       ReturnTy.addConst();
```
Comment (s-perron) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp:2267]: do we need to add const if we are returning by value?

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp [hunk 4]
```diff
@@ -2232,15 +2235,15 @@ BuiltinTypeDeclBuilder &BuiltinTypeDeclBuilder::addLoadWithStatusFunction(
...
+    DeclarationName &Name, bool IsConstMethod, bool IsConstReturn, bool IsRef,
+    QualType IndexTy, QualType ElemTy) {
   assert(!Record->isCompleteDefinition() && "record is already complete");
   ASTContext &AST = SemaRef.getASTContext();
   using PH = BuiltinTypeMethodBuilder::PlaceHolder;
   bool NeedsTypedBuiltin = !ElemTy.isNull();
 
   // The empty QualType is a placeholder. The actual return type is set below.
-  BuiltinTypeMethodBuilder MMB(*this, Name, QualType(), IsConst);
+  BuiltinTypeMethodBuilder MMB(*this, Name, QualType(), IsConstMethod);
```
Comment (s-perron) [inline clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp]: I think @tex3d's point is that `IsConstMethod` should always be true for the handle access functions because they do not modify the handle. We could use `true` here, and remove the paramter.

**Review by s-perron — APPROVED** [review]

File: clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp (hunk 1 above)
Comment (tex3d) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp:2262]: I don't understand the suggested edit. We are already under the `if (IsRef)` block, and `ReturnTy` is overridden to be `AddrSpaceElemTy` for the ref case, then turned into an LValue ref type after adding const. Though, I agree that we don't need to add const in the return-by-value case.

Comment (s-perron) [reply clang/lib/Sema/HLSLBuiltinTypeDeclBuilder.cpp:2262]: I was looking at the change without the context. Ignore it.

**Review by tex3d — APPROVED** [review]
Looks good, though I second @s-perron's comment about not needing to add const for return-by-value.
