### PR TITLE
[openmp] Use core_siblings_list if physical_package_id not available

### LINKED ISSUE #111809: [openmp] Missing physical_package_id not handled
On some powerpc systems, the following affinity tests fail:
```
  libomp :: affinity/kmp-abs-hw-subset.c
  libomp :: affinity/kmp-affinity.c
  libomp :: affinity/kmp-hw-subset.c
  libomp :: affinity/omp-places.c
```
The reason is that `/sys/devices/system/cpu/cpuN/topology/physical_package_id` returns `-1`. This is checked in https://github.com/llvm/llvm-project/blob/3645c64d87a0e4576c1195281efa005e90b529b7/openmp/runtime/src/kmp_affinity.cpp#L3560 and we then fall back to flat topology.

As far as I can tell, the behavior of returning `-1` is intentional on the side of the Linux kernel, which reports the `"ibm,chip-id"` property here, if it exists. (Rather than doing something useful, and matching `/sys/devices/system/node/nodeN`.)

The needed information could be reconstructed from `/sys/devices/system/cpu/cpuN/topology/core_siblings_list` (which is what the tests do) or `/sys/devices/system/node/nodeN/cpulist`.

### PR DESCRIPTION
**Pull request by nikic**
On powerpc, physical_package_id may not be available. Currently, this causes openmp to fall back to flat topology and various affinity tests fail.

Fix this by parsing core_siblings_list to deterimine which cpus belong to the same socket. This matches what the testing code does. The code to parse the CPU list format thankfully already exists.

Fixes https://github.com/llvm/llvm-project/issues/111809.

### CODE REVIEW

File: openmp/runtime/test/affinity/kmp-hw-subset.c [hunk 1]
```diff
@@ -25,7 +25,7 @@ static int compare_hw_subset_places(const place_list_t *openmp_places,
     expected_per_place = nthreads_per_core;
   } else {
     expected_total = nsockets;
-    expected_per_place = ncores_per_socket;
+    expected_per_place = ncores_per_socket * nthreads_per_core;
```
Comment (nikic) [inline openmp/runtime/test/affinity/kmp-hw-subset.c:28]: Unless I'm misunderstanding something, the count should always be in terms of threads. I think maybe this test has been getting away with it, because on x86 the number of threads per core is at most 2, so after halving it it is always 1 and this multiplication does not matter. On the ppc system I'm testing the number of threads per core is 6, so after halving it's 3 and the test would fail if we don't multiply here.

**Review by jpeyton52 — APPROVED** [review]
LGTM
