### PR TITLE
[LLD][COFF] Align EC code ranges to page boundaries

### LINKED ISSUE #168119: ARM64EC code ranges broken
# Description
LLD writes out ARM64EC code ranges on 4-byte granularity. Windows expects code ranges on page granularity (4096 bytes). The end result is catastrophically broken code ranges in CHPE metadata.

EDIT: Attempting to executing broken code ranges will result in access violation .
EDIT2: Corrected clang to lld.

# Affected versions
At least LLD 21.1.4 and 21.1.5, I did not try older versions.

# Reproducing
The easiest way to reproduce this is by forcefully aligning a function. This will produce a "hole" in range.

## Files
``code.amd64.cpp``:
```cpp
extern "C" {
    __declspec(code_seg(".text1$aaa")) int amd64_code_before() { return 0x12340001; }
    __declspec(code_seg(".text3$zzz")) int amd64_code_after() { return 0x12340005; }
}
```

``code.arm64.cpp``:
```cpp
extern "C" {
    __declspec(code_seg(".text2$bbb")) __declspec(align(0x800)) int arm64_code_first() {
        return 0x12340002; 
    }
    __declspec(code_seg(".text2$ccc")) __declspec(align(0x800)) int arm64_code_middle() {
        return 0x12340003; 
    }
    __declspec(code_seg(".text2$ddd")) int arm64_code_last() {
        return 0x12340004; 
    }
}
```

``main.cpp``:
```cpp
#include <stdio.h>

extern "C" int amd64_code_before();
extern "C" int arm64_code_first();
extern "C" int arm64_code_middle();
extern "C" int arm64_code_last();
extern "C" int amd64_code_after();

extern "C" char RtlIsEcCode(uintptr_t CodePointer);

struct range { unsigned start; unsigned length; };
extern "C" char __ImageBase;
extern "C" unsigned __chpe_metadata[];

int main() {
  range* code_map = (range*)((char*)&__ImageBase + __chpe_metadata[1]);
  unsigned code_map_count = __chpe_metadata[2];
  printf("Code ranges:\n");
  for (int i = 0; i < code_map_count; ++i) {
    printf("%08X %08X\n", code_map[i].start, code_map[i].length);
  }

  printf("amd64_code_before %zx is_ec %u\n", (size_t)amd64_code_before - (size_t)&__ImageBase, RtlIsEcCode((uintptr_t)amd64_code_before));
  printf("arm64_code_first %zx is_ec %u\n", (size_t)arm64_code_first - (size_t)&__ImageBase, RtlIsEcCode((uintptr_t)arm64_code_first));
  printf("arm64_code_middle %zx is_ec %u\n", (size_t)arm64_code_middle - (size_t)&__ImageBase, RtlIsEcCode((uintptr_t)arm64_code_middle));
  printf("arm64_code_last %zx is_ec %u\n", (size_t)arm64_code_last - (size_t)&__ImageBase, RtlIsEcCode((uintptr_t)arm64_code_last));
  printf("amd64_code_after %zx is_ec %u\n", (size_t)amd64_code_after - (size_t)&__ImageBase, RtlIsEcCode((uintptr_t)amd64_code_after));
}
```

``build.bat``:
```sh
"D:/LLVM/LLVM-21.1.5/bin/clang-cl.exe" -nologo -O2 -GS- -Fomain.cpp.obj -c main.cpp
"D:/LLVM/LLVM-21.1.5/bin/clang-cl.exe" -nologo -O2 -GS- -Focode.amd64.cpp.obj -c code.amd64.cpp
"D:/LLVM/LLVM-21.1.5/bin/clang-cl.exe" -nologo -O2 -GS- -arm64EC -Focode.arm64.cpp.obj -c code.arm64.cpp
"D:/LLVM/LLVM-21.1.5/bin/lld-link.exe" -nologo -Brepro -machine:ARM64EC -subsystem:console -out:range-test-llvm.exe "../arm64/arm64rt.lib" ucrt.lib msvcrt.lib ntdll.lib main.cpp.obj code.amd64.cpp.obj code.arm64.cpp.obj
```

# Output
```sh
Code ranges:
00001001 000003D4
00002002 00000F06
00009002 00000006
0000A801 0000081C
0000C002 00000006
amd64_code_before 9000 is_ec 0
arm64_code_first a800 is_ec 1
arm64_code_middle b000 is_ec 0
arm64_code_last b010 is_ec 0
amd64_code_after c000 is_ec 0
```

# Expected output
```sh
Code ranges:
00001001 000003D4
00002002 00000F06
00009002 00000006
0000A001 0000100C
0000C002 00000006
amd64_code_before 9000 is_ec 0
arm64_code_first a800 is_ec 1
arm64_code_middle b000 is_ec 1
arm64_code_last b010 is_ec 1
amd64_code_after c000 is_ec 0
```

# Workaround
Patching out final PE file externally to fix clangs broken code ranges.

### PR DESCRIPTION
**Pull request by cjacek**
We already ensure that code for different architectures is always placed in different pages in `assignAddresses`. We represent those ranges using their first and last chunks. However, the RVAs of those chunks may not be page-aligned, for example, due to extra padding for entry-thunk offsets. Align the chunk RVAs to the page boundary so that the emitted ranges correctly include the entire region.

This change affects an existing test that checks corner cases triggered by merging a data section into a code section. We may now include such data in the code range. This differs from MSVC’s behavior, but it should not cause practical issues, and the new behavior is arguably more correct.

Fixes #168119.

### CODE REVIEW

File: lld/COFF/Chunks.cpp [hunk 1]
```diff
@@ -946,7 +946,7 @@ void ECCodeMapChunk::writeTo(uint8_t *buf) const {
   auto table = reinterpret_cast<chpe_range_entry *>(buf);
   for (uint32_t i = 0; i < map.size(); i++) {
     const ECCodeMapEntry &entry = map[i];
-    uint32_t start = entry.first->getRVA();
+    uint32_t start = entry.first->getRVA() & ~0xfff;
```
Comment (mstorsjo) [inline lld/COFF/Chunks.cpp]: This looks reasonable, but do we use explicit `0xfff` for page alignment here/elsewhere so far, or do we have some constant for that?

**Review by mstorsjo — APPROVED** [review]
Looks ok, one minor comment.

File: lld/COFF/Chunks.cpp (hunk 1 above)
Comment (cjacek) [reply lld/COFF/Chunks.cpp]: Yes, we already use `0xfff` in several places in LLD, mostly, but not exclusively, in `Chunks.cpp`.
