### PR TITLE
[clang-tidy] Correct fix-it range for function pointer-like typedef in `modernize-use-using`

### LINKED ISSUE #173732: clang-tidy: `modernize-use-using` wrongly modifies typedef of referenced array
```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 21.1.6
  Optimized build.
```

Prepare the following file, `/tmp/a.cpp`:

```cpp
typedef char (&refarray)[2];
typedef char &ref;
```

and `/tmp/compile_commands.json`:

```json
[
  {
    "directory": "/tmp",
    "command": "/usr/bin/clang++ -o a.o -c a.cpp",
    "file": "a.cpp",
    "output": "a.o"
  }
]
```

Then run clang-tidy:

```console
$ clang-tidy --checks='-*,modernize-use-using' --fix a.cpp
2 warnings generated.
/tmp/a.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
    1 | typedef char (&refarray)[2];
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      | using refarray = char (&)[2]
/tmp/a.cpp:2:6: warning: use 'using' instead of 'typedef' [modernize-use-using]
    2 | typedef char &ref;
      |      ^~~~~~~~~~~~
```

which gives malformed code

```
using refarray = char (&)[2];
typed;
using ref = char &;
```

<https://godbolt.org/z/cxdfnGhEY>

### PR DESCRIPTION
**Pull request by flovent**
Extends the function case to all function pointer-like cases, because their source range contains name.
see more in https://github.com/llvm/llvm-project/pull/65558

Closes [#173732](https://github.com/llvm/llvm-project/issues/173732)

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp [hunk 1]
```diff
@@ -437,3 +437,22 @@ namespace GH97009 {
...
+namespace GH173732 {
+  // reference to array
+  typedef char (&refarray)[2];
+  // CHECK-MESSAGES: :[[@LINE-1]]:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
+  // CHECK-FIXES: using refarray = char (&)[2];
+  typedef char &ref;
+  // CHECK-MESSAGES: :[[@LINE-1]]:3: warning: use 'using' instead of 'typedef' [modernize-use-using]
+  // CHECK-FIXES: using ref = char &;
+
+
```
Comment (zeyi2) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp]: Could we add tests that look like:
```c++
typedef char (&refArray)[2], (*ptrArray)[2];
```

File: clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp [hunk 2]
```diff
@@ -205,8 +208,7 @@ void UseUsingCheck::check(const MatchFinder::MatchResult &Result) {
   }
 
   if (!ReplaceRange.getEnd().isMacroID()) {
-    const SourceLocation::IntTy Offset =
-        MatchedDecl->getFunctionType() ? 0 : Name.size();
+    const SourceLocation::IntTy Offset = FunctionPointerCase ? 0 : Name.size();
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp]: Could we use `Lexer::getLocForEndOfToken` for this?

e.g. `Lexer::getLocForEndOfToken(ReplaceRange.getEnd(), 0, SM, LO);`

I think with this API, `bool FunctionPointerCase = false;` is no longer needed :)

**Review by zeyi2 — CHANGES_REQUESTED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp (hunk 1 above)
Comment (flovent) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp]: Added, this check can generate two warnings for this code, but it can't get a correct fix-it due to `this fix will not be applied because it overlaps with another fix`.

Same things happens for multi function typedef too:
```
   typedef int(*name)(int arg1, int arg2), (*aname)();
```

File: clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp (hunk 2 above)
Comment (flovent) [reply clang-tools-extra/clang-tidy/modernize/UseUsingCheck.cpp]: Using `getLocForEndOfToken` will use get the loc of `,` as the beginning of replace for second typedef in this case comparing to the old way, which makes two fixs' ranges will not overlap and being able to provide a fix, although it's wrong.

It seems not very trivial make multi function pointer case work, because their type is mixed up together.
For single typedef:
```
  typedef char (&refArray)[2];
```
We actually put `char (&`(type loc begin to name begin) and `)[2]`(name end to type loc end) together to get its type string.

But when there are multi alias types, their share the same type begin, that's why `ptrArray` will get `char (&refArray)[2], (*` for the first part.

**Review by zeyi2 — APPROVED** [review]
But will be a good idea to wait for other reviewers :)

**Review by vbvictor — APPROVED** [review]
LGTM, cheers!
