### PR TITLE
[HLSL][DirectX] Use a padding type for HLSL buffers.

### LINKED ISSUE #144573: [DirectX] Accessing a cbuffer array with a dynamic index hits an assertion error or generates incorrect code
Compiling the following shader results in an assertion error (if compiled with assertions enabled) or incorrect code generated (if no assertions are enabled) when compiled under clang: https://godbolt.org/z/5Yszfrx1K

`clang-dxc -E CSMain -T cs_6_2 -enable-16bit-types`

```hlsl
RWStructuredBuffer<uint32_t> output;
cbuffer Constants {
  uint32_t v[2];
}
[numthreads(1, 1, 1)] 
void CSMain(uint3 Tid : SV_DispatchThreadID) {
  output[Tid.x] = v[Tid.x];
}
```
```
clang-dxc: /workspace/llvm-project/llvm/lib/Target/DirectX/DXILCBufferAccess.cpp:69: size_t getOffsetForCBufferGEP(GEPOperator *, GlobalVariable *, const DataLayout &): Assertion `Success && "Offsets into cbuffer globals must be constant"' failed.
```
https://github.com/llvm/llvm-project/blob/9e0186d925f0c375a627866c59394f25c22eb3ff/llvm/lib/Target/DirectX/DXILCBufferAccess.cpp#L69

The generated DXIL has the following incorrect cbuffer load instruction which always loads from index 0 instead of the thread id.
```
  %3 = call i32 @dx.op.threadId.i32(i32 93, i32 0) #2
  %4 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %2, i32 0) #1, !dbg !101
```

The same shader will successfully compile and validate under dxc.

### LINKED ISSUE #147352: [HLSL] Use explicit padding instead of target layout types in `__cblayout`
When creating `__cblayout` types we should use explicit padding instead of target layout types, as per https://github.com/llvm/wg-hlsl/pull/311. This will force us to use explicit conversions between objects in cbuffers and those with C++ layouts, should clean up a number of issues where the backend fails to clean up layout differences, and avoids us needing to duplicate a lot of logic between the DirectX and SPIR-V backends.

### LINKED ISSUE #147353: [HLSL] Remove target layout types
Remove the dx.Layout and spirv.Layout types, and the various references to them once the work following https://github.com/llvm/wg-hlsl/pull/311 is in place.

### LINKED ISSUE #156084: [DirectX] Incorrect indexing into array of vectors from a Constant Buffer
Indices when accessing an element of a vector from an array of vectors from a Constant Buffer can be incorrect.

This appears to be the cause of issues #155919 (10800 test failures) and #155890 (1773 test failures), and likely the majority of the rest of the DML Operator Test failures.

Reproduction: https://godbolt.org/z/dfKsqf3MG

```hlsl
// compile args: -T cs_6_7
RWBuffer<uint> output;
cbuffer Constants {
    uint4 s[2];
};
[numthreads(1,1,1)]
void main() {
    output[0] = s[1][3];
}
```

IR Output
```llvm
...
define void @main() {
  %1 = call %dx.types.Handle @dx.op.createHandleFromBinding(i32 217, %dx.types.ResBind { i32 0, i32 0, i32 0, i8 1 }, i32 0, i1 false) #1, !dbg !80
  %2 = call %dx.types.Handle @dx.op.annotateHandle(i32 216, %dx.types.Handle %1, %dx.types.ResourceProperties { i32 4106, i32 261 }) #1, !dbg !80
  %3 = call %dx.types.Handle @dx.op.createHandleFromBinding(i32 217, %dx.types.ResBind { i32 0, i32 0, i32 0, i8 2 }, i32 0, i1 false) #1, !dbg !82
  %4 = call %dx.types.Handle @dx.op.annotateHandle(i32 216, %dx.types.Handle %3, %dx.types.ResourceProperties { i32 13, i32 32 }) #1, !dbg !82
  %5 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %4, i32 1) #2, !dbg !83
  %6 = extractvalue %dx.types.CBufRet.i32 %5, 0, !dbg !83 ; <-- the index 0 should be a 3
  call void @dx.op.bufferStore.i32(i32 69, %dx.types.Handle %2, i32 0, i32 undef, i32 %6, i32 %6, i32 %6, i32 %6, i8 15), !dbg !91
  ret void
}
...
```

Thanks to @llvm-beanz for pointing out the RWStructuredBuffer reproductions were not an issue at all; the 12-byte offset was encoded into the rawbuffer read so the 0 index was actually correct. Also pointed out the issue is with the dxil-cbuffer-access pass computing the incorrect offset: https://godbolt.org/z/zhPK4473f

### PR DESCRIPTION
**Pull request by bogner**
This change drops the use of the "Layout" type and instead uses explicit padding throughout the compiler to represent types in HLSL buffers.

There are a few parts to this, though it's difficult to split them up as they're very interdependent:

1. Refactor HLSLBufferLayoutBuilder to allow us to calculate the padding of arbitrary types.
2. Teach Clang CodeGen to use HLSL specific paths for cbuffers when generating aggregate copies, array accesses, and structure accesses.
3. Simplify DXILCBufferAccesses such that it directly replaces accesses with dx.resource.getpointer rather than recalculating the layout.
4. Basic infrastructure for SPIR-V handling, but the implementation itself will need work in follow ups.

Fixes several issues, including #138996, #144573, and #156084.
Resolves #147352.

### CODE REVIEW

File: clang/lib/CodeGen/HLSLBufferLayoutBuilder.h [hunk 1]
```diff
@@ -25,24 +24,34 @@ class CodeGenModule;
...
+  /// classes) and calls layoutField to converts each field to its corresponding
+  /// LLVM type and to calculate its HLSL constant buffer layout. Any embedded
+  /// structs (or arrays of structs) are converted to layout types as well.
+  ///
+  /// When PackOffsets are specified the elements will be placed based on the
+  /// user-specified offsets. Not all elements must have a
+  /// packoffset/register(c#) annotation though. For those that don't, the
+  /// PackOffsets array will contain -1 value instead. These elements must be
+  /// placed at the end of the layout after all of the elements with specific
+  /// offset.
```
Comment (hekota) [inline clang/lib/CodeGen/HLSLBufferLayoutBuilder.h]: This comment needs to be updated. It talks about PackOffsets, but the code uses OffsetInfo. And `layoutField` function does not exist.

File: clang/test/CodeGenHLSL/resources/cbuffer.hlsl [hunk 2]
```diff
@@ -1,37 +1,121 @@
...
+// CHECK-SAME: [1 x i16], target("dx.Padding", 14),
+// CHECK-SAME: <{ [1 x <{ i64, target("dx.Padding", 8) }>], i64 }>, target("dx.Padding", 8),
+// CHECK-SAME: <{ [3 x <{ i32, target("dx.Padding", 12) }>], i32 }>
+// CHECK-SAME: }>
+
+// CHECK: %__cblayout_CBStructs = type <{
+// CHECK-SAME:   %A, target("dx.Padding", 8),
+
+// TODO: We should have target("dx.Padding", 2) padding after %B, but we don't correctly handle
+// 2- and 3-element vectors inside structs yet because of DataLayout rules.
```
Comment (hekota) [inline clang/test/CodeGenHLSL/resources/cbuffer.hlsl]: Do we have an issue for this? It might be worth adding a link to it here.

File: clang/lib/CodeGen/CGHLSLRuntime.cpp [hunk 3]
```diff
@@ -1101,3 +1110,235 @@ std::optional<LValue> CGHLSLRuntime::emitResourceArraySubscriptExpr(
...
+  Address Addr =
+      CGF.EmitPointerWithAlignment(E->getBase(), &EltBaseInfo, &EltTBAAInfo);
+  llvm::Value *Idx = EmitIdxAfterBase(/*Promote*/ true);
+
+  // Index into the object as-if we have an array of the padded element type,
+  // and then dereference the element itself to avoid reading padding that may
+  // be past the end of the in-memory object.
+  SmallVector<llvm::Value *, 2> Indices;
+  Indices.push_back(Idx);
+  Indices.push_back(llvm::ConstantInt::get(Indices[0]->getType(), 0));
```
Comment (hekota) [inline clang/lib/CodeGen/CGHLSLRuntime.cpp]:
```suggestion
  Indices.push_back(llvm::ConstantInt::get(Idx->getType(), 0));
```

File: clang/lib/CodeGen/CGHLSLRuntime.cpp [hunk 4]
```diff
@@ -1101,3 +1110,235 @@ std::optional<LValue> CGHLSLRuntime::emitResourceArraySubscriptExpr(
...
+  // Get the field index for the struct.
+  const RecordDecl *Rec = Field->getParent();
+  unsigned FieldIdx =
+      CGM.getTypes().getCGRecordLayout(Rec).getLLVMFieldNo(Field);
+
+  // Work out the buffer layout type to index into.
+  QualType RecType = CGM.getContext().getCanonicalTagType(Rec);
+  assert(RecType->isStructureOrClassType() && "Invalid type in HLSL buffer");
+  // Since this is a member of the buffer and not the buffer itself, we
+  // shouldn't have any offsets we need to contend with.
```
Comment (hekota) [inline clang/lib/CodeGen/CGHLSLRuntime.cpp]: I know what you mean, but it took me a while to parse this. How about:
```suggestion
  // Since this is a member of struct/class in the buffer and not the struct/class itself, we
  // shouldn't have any offsets on the members we need to contend with.
```

File: clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp [hunk 5]
```diff
@@ -95,187 +46,98 @@ HLSLBufferLayoutBuilder::createLayoutType(const RecordType *RT,
...
-      LayoutElements.push_back(nullptr);
+  SmallVector<std::pair<const FieldDecl *, uint32_t>> FieldsWithOffset;
+  unsigned OffsetIdx = 0;
+  for (const CXXRecordDecl *RD : llvm::reverse(RecordDecls))
+    for (const auto *FD : RD->fields())
+      FieldsWithOffset.emplace_back(FD, OffsetInfo[OffsetIdx++]);
+
+  llvm::stable_sort(FieldsWithOffset, [](const auto &LHS, const auto &RHS) {
+    return CGHLSLOffsetInfo::compareOffsets(LHS.second, RHS.second);
+  });
```
Comment (hekota) [inline clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp]: Just as in one of my comments above, I wonder if we could save some of the work that is not necessary in the common case:
```suggestion
  if (!OffsetInfo.empty())
    llvm::stable_sort(FieldsWithOffset, [](const auto &LHS, const auto &RHS) {
      return CGHLSLOffsetInfo::compareOffsets(LHS.second, RHS.second);
    });
```

**Review by hekota — COMMENTED** [review]
Great to see this taking shape! I just reviewed the Clang part so far and it is looking good - just a few comments.

File: clang/lib/CodeGen/CGHLSLRuntime.cpp [hunk 6]
```diff
@@ -1101,3 +1111,236 @@ std::optional<LValue> CGHLSLRuntime::emitResourceArraySubscriptExpr(
...
+  llvm::Value *Idx = EmitIdxAfterBase(/*Promote*/ true);
+
+  // Index into the object as-if we have an array of the padded element type,
+  // and then dereference the element itself to avoid reading padding that may
+  // be past the end of the in-memory object.
+  SmallVector<llvm::Value *, 2> Indices;
+  Indices.push_back(Idx);
+  Indices.push_back(llvm::ConstantInt::get(Idx->getType(), 0));
+
+  llvm::Value *GEP = CGF.Builder.CreateGEP(LayoutTy, Addr.emitRawPointer(CGF),
```
Comment (s-perron) [inline clang/lib/CodeGen/CGHLSLRuntime.cpp]: It does not need to change for now but I wonder if we can get the size of the array from `E` or not. We will need this when doing the "structured gep" that @Keenuts is working on.

**Review by s-perron — APPROVED** [review]
I think this looks good. There are a number of issue we will have in the spir-v backend, but they are not for this PR.

1. SPIR-V backend needs to lower the padding type. The first step will be to simply use int8, then in we can add a pass to remove the padding when we start to care about reflection (or earlier).
2. There are many issues with pointer in the SPIR-V backend. We'll have to decide if we simply wait for the structured GEP or try to fix them earlier.
3. I'll have to commit my change to lower the peeled array back into a single array. I think I have that available somewhere.

I'll get to 1 and 3 next week.

File: llvm/test/CodeGen/DirectX/CBufferAccess/gep-ce-two-uses.ll [hunk 7]
```diff
@@ -3,28 +3,24 @@
...
   store float %a1, ptr %dst, align 32
 
-  ; CHECK: [[CB:%.*]] = load target("dx.CBuffer", {{.*}})), ptr @CB.cb
-  ; CHECK: [[LOAD:%.*]] = call { float, float, float, float } @llvm.dx.resource.load.cbufferrow.4.{{.*}}(target("dx.CBuffer", {{.*}})) [[CB]], i32 1)
-  ; CHECK: [[X:%.*]] = extractvalue { float, float, float, float } [[LOAD]], 0
-  ; CHECK: store float [[X]], ptr %dst
-  %a2 = load float, ptr addrspace(2) getelementptr inbounds nuw (i8, ptr addrspace(2) @a1, i32 4), align 4
+  ; CHECK: [[PTR:%.*]] = call ptr addrspace(2) @llvm.dx.resource.getpointer.{{.*}}(target("dx.CBuffer", %__cblayout_CB) {{%.*}}, i32 0)
+  ; CHECK: getelementptr inbounds nuw i8, ptr addrspace(2) [[PTR]], i32 16
+  %a2 = load float, ptr addrspace(2) getelementptr inbounds nuw (i8, ptr addrspace(2) @a1, i32 16), align 4
```
Comment (hekota) [inline llvm/test/CodeGen/DirectX/CBufferAccess/gep-ce-two-uses.ll]: This test seems to be exactly the same as above (line 16).

File: llvm/test/CodeGen/DirectX/CBufferAccess/arrays.ll [hunk 8]
```diff
@@ -1,124 +1,50 @@
...
+  store target("dx.CBuffer", %__cblayout_CB) %CB.cb_h.i.i, ptr @CB.cb, align 4
 
-  ; CHECK: [[CB:%.*]] = load target("dx.CBuffer", {{.*}})), ptr @CB.cb
-  ; CHECK: [[LOAD:%.*]] = call { float, float, float, float } @llvm.dx.resource.load.cbufferrow.4.{{.*}}(target("dx.CBuffer", {{.*}})) [[CB]], i32 1)
-  ; CHECK: [[X:%.*]] = extractvalue { float, float, float, float } [[LOAD]], 0
-  ; CHECK: store float [[X]], ptr %dst
-  %a1 = load float, ptr addrspace(2) getelementptr inbounds nuw (i8, ptr addrspace(2) @a1, i32 4), align 4
+  ; CHECK: [[PTR:%.*]] = call ptr addrspace(2) @llvm.dx.resource.getpointer.{{.*}}(target("dx.CBuffer", %__cblayout_CB) {{%.*}}, i32 0)
+  ; CHECK: getelementptr inbounds nuw i8, ptr addrspace(2) [[PTR]], i32 16
+  %a1 = load float, ptr addrspace(2) getelementptr inbounds nuw (i8, ptr addrspace(2) @a1, i32 16), align 4
```
Comment (hekota) [inline llvm/test/CodeGen/DirectX/CBufferAccess/arrays.ll]: It would be nice to add to comment what is this accessing (`a1[1]`, `a2[1]` and `a2[0][1]`, right?)

**Review by hekota — COMMENTED** [review]
The backend part looks good, but I am confused about the tests. I get that a lot of the CBufferAccess tests have been removed because big part of the the cbuffer access logic is now in DXILResourceAccesPass, but the Clang codegen tests in this change all generate typed GEPs such as:

 `getelementptr (<{ float, target("dx.Padding", 12) }>, ptr addrspace(2) @c1, i32 7, i32 0)`, 

And the few remaining tests in the backend are only testing untyped GEPs:

`getelementptr inbounds nuw (i8, ptr addrspace(2) @a1, i32 16)`.

Shouldn't we be testing the typed variants too? Or is something always translating typed GEPs into untyped before CBufferAccess runs?

**Review by hekota — APPROVED** [review]
LGTM! :)
