### PR TITLE
[analyzer] Fix false double free when including 3rd-party headers with overloaded delete operator as system headers

### LINKED ISSUE #58820: [LLVM 15.0 Regression] [cplusplus.NewDelete] False positive when using `QPointer<>`
Linting a codebase that uses Qt 6 with clang-tidy 15 (have tested 15.0.0 and 15.0.3) results in a false positive within `QWeakPointer` (triggered by usage of `QPointer`):
```console
(py3) [nkiesel@host repro]$ clang-tidy -checks='-*,clang-analyzer-*' -p build/ main.cpp
1 warning generated.
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:162:50: error: Use of memory after it is freed [clang-analyzer-cplusplus.NewDelete,-warnings-as-errors]
        inline void operator delete(void *ptr) { ::operator delete(ptr); }
                                                 ^
/tmp/nkiesel/repro/main.cpp:21:21: note: Calling implicit destructor for 'MainWindow'
    return app.exec();
                    ^
/tmp/nkiesel/repro/main.cpp:21:21: note: Calling implicit destructor for 'QPointer<QWidget>'
/tmp/nkiesel/repro/main.cpp:21:21: note: Calling '~QWeakPointer'
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:34: note: Assuming field 'd' is non-null
    inline ~QWeakPointer() { if (d && !d->weakref.deref()) delete d; }
                                 ^
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:34: note: Left side of '&&' is true
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:39: note: Assuming the condition is true
    inline ~QWeakPointer() { if (d && !d->weakref.deref()) delete d; }
                                      ^~~~~~~~~~~~~~~~~~~
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:30: note: Taking true branch
    inline ~QWeakPointer() { if (d && !d->weakref.deref()) delete d; }
                             ^
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:60: note: Memory is released
    inline ~QWeakPointer() { if (d && !d->weakref.deref()) delete d; }
                                                           ^~~~~~~~
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:579:60: note: Calling 'ExternalRefCountData::operator delete'
    inline ~QWeakPointer() { if (d && !d->weakref.deref()) delete d; }
                                                           ^~~~~~~~
/mnt/vol02/nkiesel/opt/qt/Qt-6.2.4/include/QtCore/qsharedpointer_impl.h:162:50: note: Use of memory after it is freed
        inline void operator delete(void *ptr) { ::operator delete(ptr); }
                                                 ^                 ~~~
1 warning treated as error
```

`ExternalRefCountData::operator delete(void*)` is incorrectly treated as a proper `::operator delete(void*)`, and the memory is marked as freed. Parsing then continues down the stack and sees the true call of `::operator delete(void*)`, triggering the error since clang-tidy thinks the memory has already been freed.

LLVM 12.0.1 and 14.0.6 did not exhibit this behavior.

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.11...3.22)


project(repro CXX)


find_package(Qt6 COMPONENTS Gui Widgets)


set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)


add_executable(repro main.cpp)
target_link_libraries(repro PRIVATE Qt6::Gui Qt6::Widgets)
```

main.cpp:
```cpp
#include <QApplication>
#include <QMainWindow>
#include <QWidget>
#include <QPointer>

class MainWindow : public QMainWindow {
public:
    MainWindow(QWidget *parent = nullptr) : QMainWindow(parent) {}

private:
    QPointer<QWidget> m_widget;
};

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);

    MainWindow main_window;
    main_window.show();

    return app.exec();
}
```

### LINKED ISSUE #62985: False positive clang-analyzer-cplusplus.NewDelete for QWeakPointer when using `-isystem` flags
For the following example code, run the Clang-Tidy as `clang-tidy foo.cpp  -- -isystem /usr/include/qt/QtCore/ -I/usr/include/qt/` (Suppose the Qt 5 headers installed at `/usr/include/qt`)

```C++
#include <QWeakPointer>

void test(const QWeakPointer<QObject>& p)
{
	QWeakPointer<QObject> t;
	t = p;
}
```

The following warning generated
```console
1 warning generated.
/usr/include/qt/QtCore/qsharedpointer_impl.h:159:50: warning: Use of memory after it is freed [clang-analyzer-cplusplus.NewDelete]
        inline void operator delete(void *ptr) { ::operator delete(ptr); }
                                                 ^
```

It's strange when using `-I` instead of `-isystem`, it won't report this problem, which is expected (Even using `-header-filter=.*`).

It can be reproduce on Windows platform too.

### PR DESCRIPTION
**Pull request by Snape3058**
Fixes #62985
Fixes #58820

When 3rd-party header files are included as system headers, their overloaded `new` and `delete` operators are also considered as the std ones. However, those overloaded operator functions will also be inlined. This makes the same
symbolic memory marked as released twice: during `checkPreCall` of the overloaded `delete` operator and when calling `::operator delete` after inlining the overloaded operator function (if it has).

This patch attempts to fix this bug by adjusting the strategy of verifying whether the callee is a standard `new` or `delete` operator in the `isStandardNewDelete` function.

### CODE REVIEW

**Comment by Snape3058** [comment]
This version is just a trivial workaround for this issue. Refer to the FIXME comment in the checker. Feel free to provide suggestions on fixing this bug.

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp [hunk 1]
```diff
@@ -1090,7 +1090,8 @@ static bool isStandardNewDelete(const FunctionDecl *FD) {
   // If the header for operator delete is not included, it's still defined
   // in an invalid source location. Check to make sure we don't crash.
   return !L.isValid() ||
-         FD->getASTContext().getSourceManager().isInSystemHeader(L);
+         (!FD->hasBody() && // FIXME: Still a false alarm after CTU inlining.
+          FD->getASTContext().getSourceManager().isInSystemHeader(L));
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1094]: This check still has some problems.
`FD` is not guaranteed to be the function decl which has the body, thus consequently, the location of `FD` might not point to the definition, even if FD has a definition.

`FD` likely points to the last decl declaration spelling.
I didn't have time to publish my extra tests demonstrating this, but I'll come back to this.

**Review by steakhal — CHANGES_REQUESTED** [review]

File: clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp (hunk 1 above)
Comment (Snape3058) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1094]: > FD is not guaranteed to be the function decl which has the body

But `FunctionDecl::hasBody` will traverse all re-declarations and verify whether there is a decl has a body defined. So I think it will not affect the correctness no matter which re-declaration it points to.

My concern is the situation when the current TU does not have its definition but can be imported from other TUs during CTU inlining. Under this circumstance, the declaration can still pass the check here but trigger a false positive after CTU inlining.

```
+------------+   +------------------+   +----------------+
|checkPreCall|-->|No body in this TU|-->|Mark as Released|
+------------+   +------------------+   +----------------+
      |
      v
  +--------+   +---+   +----------------------+   +--------------------+
  |evalCall|-->|CTU|-->|Found body in other TU|-->|Inline external body|
  +--------+   +---+   +----------------------+   +--------------------+
      |
      v
+--------------------------------+   +-------------------------+
|the real delete in imported body|-->|double free (false alarm)|
+--------------------------------+   +-------------------------+
```

I am not sure whether there are other scenarios like this that can also trigger this false positive. If so, how can we update the conditions for these scenarios?

The current version is just a workaround for this bug we encountered here, rather than a robust verifier for checking whether a given overload is a standard one.

Comment (balazske) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1094]: Is it possible to move the check into `checkPostCall`? Then this situation can not happen.

Comment (steakhal) [reply clang/lib/StaticAnalyzer/Checkers/MallocChecker.cpp:1094]: This is an excellent question! :D

**Comment by steakhal** [comment]
I had a deeper look at the patch and I think it's good.
To be on the safe side, I canonicalize `FD` to prefer decls with definitions if the redeclchain contains a definition.
This ensures that if we have a definition, `L` will refer to the beginning of that definition.

I'll merge this PR in a couple of days unless someone objects, or you challenge my proposed changes @Snape3058.
Thanks for the PR btw.

**Review by steakhal — APPROVED** [review]

**Comment by nathanjsmith** [comment]
Any update on whether this can be merged? The false positive detection is preventing me from upgrading beyond clang 14.

**Review by NagyDonat — APPROVED** [review]
It seems that we forgot about this issue :sweat:, sorry for the trouble!

The change looks good to me at first glance, although I didn't investigate the context and the the possible indirect effects.
