### PR TITLE
[flang][OpenMP] Fix LINEAR clause validation and test expectations

### LINKED ISSUE #175688: [flang][OpenMP] Fix the test Semantics/OpenMP/linear-clause01.f90
After https://github.com/llvm/llvm-project/pull/175383 test `Semantics/OpenMP/linear-clause01.f90` started failing everywhere.

I disabled the failing check in the test to unblock the builds. Filing this issue to ensure that the test will be properly fixed.

@KrxGu please fix this issue.

### PR DESCRIPTION
**Pull request by KrxGu**
Fixes #175688

After #175383 was merged, the test `Semantics/OpenMP/linear-clause01.f90` was failing because it had an early return that prevented multiple errors from being reported.

This PR fixes two issues:

1. **Removes the early return** after detecting a modifier error on DO/SIMD directives. Previously, when a modifier error was found, the function would return immediately without checking other restrictions like the scalar requirement. Now all applicable errors are reported.

2. **Updates test expectations** to expect both the modifier error AND the scalar error for Case 1, where `arg(:)` is an array used with `uval` modifier on a DO directive.

Thanks to @NimishMishra for catching this during review - arrays should always be rejected in LINEAR clauses (except for `declare simd` with `ref` modifier), regardless of whether there are other errors.

### CODE REVIEW

File: flang/test/Semantics/OpenMP/linear-clause01.f90 [hunk 1]
```diff
@@ -7,11 +7,8 @@
 ! Case 1
 subroutine linear_clause_01(arg)
     integer, intent(in) :: arg(:)
-!    !ERROR: A modifier may not be specified in a LINEAR clause on the DO directive
-!    !ERROR: List item 'arg' in LINEAR clause must be a scalar variable
```
Comment (NimishMishra) [inline flang/test/Semantics/OpenMP/linear-clause01.f90]: Please correct me if I am missing something here, but isn't `arg` an assumed array here? So why should the semantic error on LINEAR clause not be emitted?

**Review by kparzysz — APPROVED** [review]

**Review by tblah — APPROVED** [review]

**Review by NimishMishra — APPROVED** [review]

**Comment by KrxGu** [comment]
> Hi, is someone looking at the reported test failures?

I am waiting for a more experienced member to diagnose the issue, as I have not been able to determine what went wrong.
Cc: @NimishMishra @tblah @kparzysz

**Comment by KrxGu** [comment]
> Hi, is someone looking at the reported test failures?

I am waiting for a more experienced member to diagnose the issue, as I have not been able to determine what went wrong.
Cc: @NimishMishra @tblah @kparzysz

**Comment by KrxGu** [comment]
> Hi, is someone looking at the reported test failures?

I am waiting for a more experienced member to diagnose the issue, as I have not been able to determine what went wrong.
Cc: @NimishMishra @tblah @kparzysz

**Comment by KrxGu** [comment]
> Hi, is someone looking at the reported test failures?

I am waiting for a more experienced member to diagnose the issue, as I have not been able to determine what went wrong.
Cc: @NimishMishra @tblah @kparzysz

**Comment by omjavaid** [comment]
Hi I have temporarily reverted the change to make the CI green again.

**Comment by tblah** [comment]
@KrxGu the failing test is flang/test/Semantics/OpenMP/clause-validity01.f90. You should be able to reproduce this yourself by building [6e62d40](https://github.com/llvm/llvm-project/commit/6e62d40b7c65a67ac0e5c6e0f462ce2663db98b9)
