### PR TITLE
[clang] Enable C++17 relaxed template template argument matching by default

### LINKED ISSUE #36505: Alias template produces seemingly bogus "template template argument has different template parameters" error
|  |  |
| --- | --- |
| Bugzilla Link | [37157](https://llvm.org/bz37157) |
| Version | trunk |
| OS | All |
| CC | @DougGregor |

## Extended Description 
I (and also GCC 7.0-and-later) claim that this program is legal C++.

    template<template<class> class X> struct A {};
    template<template<class...> class Y> using B = A<Y>;
    template<class> struct S;
    B<S> b;

Clang, on the other hand, bails out at line 2:

prog.cc:2:50: error: template template argument has different template parameters than its corresponding template template parameter
template<template<class...> class Y> using B = A<Y>;
                                                 ^
prog.cc:2:19: note: template type parameter pack does not match template type parameter in template argument
template<template<class...> class Y> using B = A<Y>;
                  ^
prog.cc:1:19: note: previous template type parameter declared here
template<template<class> class X> struct A {};
                  ^

Clang becomes happy if I change it from 'using B = A<Y>' to 'struct B {}', and then sad again if I change it to 'struct B : A<Y> {}'.

### PR DESCRIPTION
**Pull request by mizvekov**
This patch will finally allow us to mark C++17 support in clang as complete.

This is a continuation of the review process from an [old PR in phab](https://reviews.llvm.org/D109496).

Recap: The original patch from phab initially contained no workarounds / provisional resolutions for core defects,
Though testing by @yxsamliu [here](https://reviews.llvm.org/D109496#3101839) showed problems with some important libraries used in GPU applications, and we ended up reverting it.

In order to implement this as a DR and avoid breaking reasonable code that worked before P0522, this patch implements a provisional resolution for CWG2398: When deducing template template parameters against each other, and the argument side names a template specialization, instead of just deducing A, we deduce a synthesized template template parameter based on A, but with it's parameters using the template specialization's arguments as defaults.

This does not fix all possible regressions introduced by P0522, but it does seem to match in effect an undocumented workaround implemented by GCC. Though it's unconfirmed how closely we match, as I have not received official word regarding this yet.
Fixing other regressions will require more extensive changes, some of them would require possibly controversial wording changes, and so is left for future work.

The driver flag is deprecated with a warning, and it will not have any effect.

Fixes https://github.com/llvm/llvm-project/issues/36505

@yxsamliu Can you confirm this version avoids any breakages in your setup?

CC: @yuanfang-chen @MaskRay @chandlerc @jicama @lichray @AaronBallman

### CODE REVIEW

File: clang/lib/Driver/ToolChains/Clang.cpp [hunk 1]
```diff
@@ -6561,7 +6561,7 @@ void Clang::ConstructJob(Compilation &C, const JobAction &JA,
   if (const Arg *A =
           Args.getLastArg(options::OPT_fvisibility_global_new_delete_hidden)) {
     D.Diag(diag::warn_drv_deprecated_arg)
-        << A->getAsString(Args)
+        << A->getAsString(Args) << true
```
Comment (erichkeane) [inline clang/lib/Driver/ToolChains/Clang.cpp:6564]: Add a comment on the 'true' to show what it means.  Elsewher etoo.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 2]
```diff
@@ -8343,58 +8343,52 @@ bool Sema::CheckTemplateTemplateArgument(TemplateTemplateParmDecl *Param,
   // C++1z [temp.arg.template]p3: (DR 150)
   //   A template-argument matches a template template-parameter P when P
   //   is at least as specialized as the template-argument A.
-  // FIXME: We should enable RelaxedTemplateTemplateArgs by default as it is a
-  //  defect report resolution from C++17 and shouldn't be introduced by
-  //  concepts.
-  if (getLangOpts().RelaxedTemplateTemplateArgs) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:8349]: This is just being deprecated, right?  Don't we still need this?

**Review by erichkeane — COMMENTED** [review]
We probably need to attach this to ClangABI as well, this is an ABI breaking change.

**Review by erichkeane — COMMENTED** [review]
Also needs a release note, entry into breaking changes, and a post on mailing list or whatever for the 'breaking change' subscribers to pay attention to.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: Only the flag is deprecated, we want the new 'on' behavior to stay.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: It's a removal of the flag's behavior, with the addition of provisional wording changes, in order to moot the original reason the flag existed.

I see where the confusion comes from. The original patch did not remove the flag completely, just changed the default, but still deprecated it. After some offline discussion with @zygoloid, we decided to remove the flag as well, but I forgot to update the title.

@zygoloid thoughts on that?

How about for starters we just change the default, but still deprecate the flag both ways anyway?
If the transition is a concern, I think it would be a problem that we don't start to warn the users of the flags as soon as possible. Otherwise, I think this will be specially problematic if there are current users of the negative spelling `-fno-relaxed-template-template-args`.

Comment (erichkeane) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: >How about for starters we just change the default, but still deprecate the flag both ways anyway?
If the transition is a concern, I think it would be a problem that we don't start to warn the users of the flags as soon as possible. Otherwise, I think this will be specially problematic if there are current users of the negative spelling -fno-relaxed-template-template-args.

Seems reasonable to me.  

I had missed the impact of the CWG issue, if @zygoloid thinks we're Ok with just deprecating the flags (or removing them?  I think I'd prefer the deprecate-but-do-nothing over removal), I'm Ok too.

Comment (zygoloid) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: I think the goal should be to remove the flags eventually, but given that it's easy to keep the flags functioning, I think it'd be a good idea to do so for at least long enough for people to tell us if this change breaks something. Maybe one release cycle with the default flipped and the flags working but warning, then we remove them if people aren't complaining?

Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: I also wonder if, at least for the time being, we should leave C++03 alone (despite the paper being a DR)

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 3]
```diff
@@ -519,13 +571,45 @@ DeduceTemplateArguments(Sema &S, TemplateParameterList *TemplateParams,
...
+        assert(DefaultArguments.size() <= As->size());
+        SmallVector<NamedDecl *, 4> Params(As->size());
+        for (unsigned I = 0; I < DefaultArguments.size(); ++I)
+          Params[I] =
+              DeduceTemplateArguments(S, As->getParam(I), DefaultArguments[I]);
+        for (unsigned I = DefaultArguments.size(); I < As->size(); ++I)
+          Params[I] = As->getParam(I);
+        // FIXME: We could unique these, and also the parameters, but we don't
+        // expect programs to contain a large enough amount of these deductions
+        // for that to be worthwhile.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:600]: Double checking: These parameters are only used for deduction, so not unique them would not affect type identity?

**Review by cor3ntin — COMMENTED** [review]
I'm pretty happy with the direction this is going in.
I'd like to see the specific test in https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2398, the ones we exchanged by mails and some tests with constraints

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: > I think the goal should be to remove the flags eventually, but given that it's easy to keep the flags functioning, I think it'd be a good idea to do so for at least long enough for people to tell us if this change breaks something. Maybe one release cycle with the default flipped and the flags working but warning, then we remove them if people aren't complaining?

Thats was exactly my thought, thanks!  I would like that too.


>I also wonder if, at least for the time being, we should leave C++03 alone (despite the paper being a DR)

I think we should do it whole-hog or not at all.  I don't see how 03 is significantly different here, and it would likely result in us delaying removing the flags an additional release cycle.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp:8349]: Yes, I think if there are problems in existing C++03 code, we should know about it, I can't see how that same problem wouldn't necessarily apply to newer standards.

File: clang/www/cxx_status.html [hunk 4]
```diff
@@ -1133,8 +1133,8 @@ <h2 id="cxx17">C++17 implementation status</h2>
     <!-- Issaquah 2016 papers -->
     <tr>
       <td>Matching template template parameters to compatible arguments</td>
-      <td><a href="https://wg21.link/p0522r0">P0522R0</a></td>
-      <td class="partial" align="center">Partial <a href="#p0522">(10)</a></td>
+      <td><a href="https://wg21.link/p0522r0">P0522R0</a> (<a href="#dr">DR</a>)</td>
+      <td class="full" align="center">Clang 4 <a href="#p0522">(10)</a></td>
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/www/cxx_status.html:1137]: This entry was one of the review requests from @zygoloid in the original phab PR: https://reviews.llvm.org/D109496?id=384873#3031693

I think saying we implemented in Clang 4 is more accurate, we even explain in the note that it was behind a switch. But still users have known about it and have been using it for a long time.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 3 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:600]: Yeah, doesn't affect identity. The results from deduction are assumed to be sugared, this was one of the changes I made to the deduction machinery back in 2021 or so.

Where identity is concerned, the types should be canonicalized, and we have a special step for canonicalizing template template parameters.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 5]
```diff
@@ -507,10 +507,62 @@ static TemplateDeductionResult DeduceNonTypeTemplateArgument(
...
+    auto *R = NonTypeTemplateParmDecl::Create(
+        S.Context, A->getDeclContext(), SourceLocation(), SourceLocation(),
+        T->getDepth(), T->getIndex(), T->getIdentifier(), T->getType(),
+        /*ParameterPack=*/false, T->getTypeSourceInfo());
+    R->setDefaultArgument(Default.getAsExpr());
+    if (auto *PTC = T->getPlaceholderTypeConstraint())
+      R->setPlaceholderTypeConstraint(PTC);
+    return R;
+  }
+  case Decl::TemplateTemplateParm: {
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:546]: Good point, NVM

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 6]
```diff
@@ -507,10 +507,62 @@ static TemplateDeductionResult DeduceNonTypeTemplateArgument(
       S, TemplateParams, NTTP, DeducedTemplateArgument(New), T, Info, Deduced);
 }
 
+static NamedDecl *DeduceTemplateArguments(Sema &S, NamedDecl *A,
+                                          TemplateArgument Default) {
+  switch (A->getKind()) {
+  case Decl::TemplateTypeParm: {
+    auto *T = cast<TemplateTypeParmDecl>(A);
+    // FIXME: DefaultArgument can't represent a pack.
+    if (T->isParameterPack())
```
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:516]: You have an example? 
But I think you are right, however I still do not understand the fixme.

File: clang/www/cxx_status.html (hunk 4 above)
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/www/cxx_status.html:1137]: We usually put the version that has the most complete implementation on that page. No strong opinion though.

**Comment by pinskia** [comment]
Reference to https://github.com/llvm/llvm-project/issues/55894 .

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:516]: The test `foo` in `clang/test/CXX/temp/temp.decls/temp.fct/temp.func.order/p6.cpp` exercises this, but it doesn't involve any default arguments, so any effects are incidental / harmless.

I have actually just come up with a relevant test case that shows something interesting that I wasn't aware before, this could possibly be new info for the core issue.

https://godbolt.org/z/rnbzhnqG7

This shows a change of behavior introduced by P05522, only instead of introducing ambiguity, it causes different candidates to be picked. Also affects GCC.

---

Regarding the FIXME:

So the (Type | NonType | Template) template parameter declarations store the default argument for themselves. They have a `setDefaultArgument` method for setting that. While for template template parameter declarations the `setDefaultArgument` takes a `TemplateArgument`, and that means it can use any kind of TemplateArgument as a default argument, including packs.

The same is not true for (Type | NonType) template parameter declarations, their `setDefaultArgument` only takes a (Type / Expression), which means a pack can't be passed.

This is done presumably to save space in those declarations, while a Type and an Expression are a single pointer, a `TemplateArgument` is considerably larger, and you would need at least a pointer and an integer to represent a pack.

To 'fix' this FIXME, we would have to change that, and allow those declarations to be larger in at least some circumstances.

**Comment by mizvekov** [comment]
So Jason pointed out that GCC's provisional wording for CWG2398 picks a dubious candidate for this example:
```C++
template<typename T, typename U> struct match2;

template<template<typename A> class t1,typename T>
struct match2<t1<T>, typename t1<T>::type > { typedef int type; }; // #5                                                 

template<template<typename B, typename C> class t2,typename T0,typename T1>
struct match2<t2<T0,T1>, typename t2<T0,T0>::type > { typedef int type; }; // #6                                         

template <class T, class U = T> struct Q { typedef int type; };
match2<Q<int>, int> m;
```

They pick #6, where with this PR we stay with ambiguous.
According to [this GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114841), he suggests changing GCC to adopt the wording proposed here.

**Comment by yxsamliu** [comment]
> This patch will finally allow us to mark C++17 support in clang as complete.
> 
> This is a continuation of the review process from an [old PR in phab](https://reviews.llvm.org/D109496).
> 
> Recap: The original patch from phab initially contained no workarounds / provisional resolutions for core defects, Though testing by @yxsamliu [here](https://reviews.llvm.org/D109496#3101839) showed problems with some important libraries used in GPU applications, and we ended up reverting it.
> 
> In order to implement this as a DR and avoid breaking reasonable code that worked before P0522, this patch implements a provisional resolution for CWG2398: When deducing template template parameters against each other, and the argument side names a template specialization, instead of just deducing A, we deduce a synthesized template template parameter based on A, but with it's parameters using the template specialization's arguments as defaults.
> 
> This does not fix all possible regressions introduced by P0522, but it does seem to match in effect an undocumented workaround implemented by GCC. Though it's unconfirmed how closely we match, as I have not received official word regarding this yet. Fixing other regressions will require more extensive changes, some of them would require possibly controversial wording changes, and so is left for future work.
> 
> The driver flag is deprecated with a warning, and it will not have any effect.
> 
> @yxsamliu Can you confirm this version avoids any breakages in your setup?
> 
> CC: @yuanfang-chen @MaskRay @chandlerc @jicama @lichray @AaronBallman

I confirm this version avoids breakages in rocThrust which were reported before. Thanks.

File: clang/test/CXX/drs/cwg2398.cpp [hunk 7]
```diff
@@ -0,0 +1,115 @@
+// RUN: %clang_cc1 %s -fsyntax-only -std=c++23                                     -verify=expected,new
+// RUN: %clang_cc1 %s -fsyntax-only -std=c++23 -fno-relaxed-template-template-args -verify=expected,old
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg2398.cpp:2]: We don't test non-conforming modes of operation in DR test suite.
This should be tested elsewhere, e.g. in SemaTemplate tests.

File: clang/test/CXX/drs/cwg2398.cpp [hunk 8]
```diff
@@ -0,0 +1,115 @@
+// RUN: %clang_cc1 %s -fsyntax-only -std=c++23                                     -verify=expected,new
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg2398.cpp:1]: Why only C++23 is tested? DR tests should test all language modes.

**Review by Endilll — DISMISSED** [review]

File: clang/test/CXX/drs/cwg2398.cpp (hunk 7 above)
Comment (mizvekov) [reply clang/test/CXX/drs/cwg2398.cpp:2]: Okay, I think I misunderstood then what `CXX/drs` was about, I should probably move it elsewhere.

File: clang/test/CXX/drs/cwg2398.cpp (hunk 8 above)
Comment (mizvekov) [reply clang/test/CXX/drs/cwg2398.cpp:1]: While it's true this is a DR, I just don't think for this particular case it's worth the cost of testing every single mode, as there are no particularly interesting interactions there.
Moot point as I will be moving it away anyway.

File: clang/test/CXX/drs/cwg2398.cpp (hunk 7 above)
Comment (Endilll) [reply clang/test/CXX/drs/cwg2398.cpp]: Given that you're fixing CWG2398, you should be adding a test here to update https://clang.llvm.org/cxx_dr_status.html. This corner of our test suite lives by its own rules to some extent, so you should stay consistent with 700 tests we already have.

Comment (mizvekov) [reply clang/test/CXX/drs/cwg2398.cpp]: Thanks.

Since the core issue is not resolved by WG21, I don't want to claim to be resolving it here with this patch.

And while we don't remove the non-conforming flag, we should still test it, and it's just much more economical and error proof that we reuse the same tests.

Comment (Endilll) [reply clang/test/CXX/drs/cwg2398.cpp]: > Since the core issue is not resolved by WG21, I don't want to claim to be resolving it here with this patch.

It'd be far from the first time we're testing an issue that is still open (https://github.com/llvm/llvm-project/blob/bd53c7cce418fe7f3e171859d4718df15d03dc2b/clang/test/CXX/drs/dr24xx.cpp#L62), but the fact that 2398 filing lacks any possible resolution that we can be testing against, it complicates the matter.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: My question was more whether we want to deduce packs at all.

I think the new behavior make sense, in that it is consistent with https://eel.is/c++draft/temp.deduct#partial-11 (
I suspect because both candidates are valid, this tie breaker gets triggered)

We might change that in the future, but now packs can't be defaulted, so I struggle to come up to think of a case where considering the pack would change the order of partial ordering (and not trailing packs can't be deduced)

here are more tests which I think are consistent https://godbolt.org/z/5Ke3TGfK6

**Comment by cor3ntin** [comment]
@mizvekov We have a bunch of related issues, could you look at them
https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+%22-frelaxed-template-template-args%22 ?

(and add tests + "Fixes #XXXX` to the commit message, as well as mentioning all the fixed issues in the release notes)

Thanks!

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 9]
```diff
@@ -507,10 +507,62 @@ static TemplateDeductionResult DeduceNonTypeTemplateArgument(
...
+        S.Context, A->getDeclContext(), SourceLocation(), SourceLocation(),
+        T->getDepth(), T->getIndex(), T->getIdentifier(),
+        T->wasDeclaredWithTypename(), /*ParameterPack=*/false,
+        T->hasTypeConstraint());
+    R->setDefaultArgument(
+        S.Context.getTrivialTypeSourceInfo(Default.getAsType()));
+    if (R->hasTypeConstraint()) {
+      auto *C = R->getTypeConstraint();
+      R->setTypeConstraint(C->getConceptReference(),
+                           C->getImmediatelyDeclaredConstraint());
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:535]: It's the same tests I linked in the other thread: https://github.com/llvm/llvm-project/blob/15f02723d49be9a828fbf072966a225babd60457/clang/test/CXX/temp/temp.decls/temp.fct/temp.func.order/p6.cpp#L48

**Comment by cor3ntin** [comment]
In particular #49185, #63281 and #62529 seem worth looking into

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: I see.

The code I posted was an attempt to construct such an example, where a pack doesn't need to be defaulted as-written for the proposed changes in the rules to have an effect. Except that example hits the wall at something else first, and I haven't fully investigated that. I haven't excluded the possibility that such an example could be constructed yet.

So when I proposed that provisional wording, I didn't exclude packs from the equation. I don't see a reason to, as without excluding them, the rules stay simpler and more general and should still work.

If we want to exclude them for implementation efficiency reasons, we could, as presumably it could still work as-if.

**Comment by mizvekov** [comment]
> @mizvekov We have a bunch of related issues, could you look at them https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+%22-frelaxed-template-template-args%22 ?

Removed a bunch of duplicates. 4 issues remaining:

1) #36505 Is the issue we are fixing in this patch.
2) #65843 Is unrelated.
3) #63281 Is not a bug
4) #62529 The bug is accepting it, although perhaps we could seek clarification if we should exclude template template parameters from [CWG1430](https://cplusplus.github.io/CWG/issues/1430.html)

**Review by cor3ntin — APPROVED** [review]
I'm reasonably convinced the remaining issues are somewhat orthogonal and can be addressed separately.
I think we should move forward with this (and see if it sticks) but please give @erichkeane @zygoloid @shafik a few days in case they have additional feedback

Thanks a  lot for working on this

**Review by erichkeane — APPROVED** [review]

File: clang/www/cxx_status.html [hunk 10]
```diff
@@ -1133,8 +1133,8 @@ <h2 id="cxx17">C++17 implementation status</h2>
     <!-- Issaquah 2016 papers -->
     <tr>
       <td>Matching template template parameters to compatible arguments</td>
-      <td><a href="https://wg21.link/p0522r0">P0522R0</a></td>
-      <td class="partial" align="center">Partial <a href="#p0522">(10)</a></td>
+      <td><a href="https://wg21.link/p0522r0">P0522R0</a> (<a href="#dr">DR</a>)</td>
+      <td class="full" align="center">Clang 19 <a href="#p0522">(10)</a></td>
```
Comment (cor3ntin) [inline clang/www/cxx_status.html:1137]: This should have been "unreleased", not "full".
Sorry I missed that during review

**Comment by eaeltsin** [comment]
Hi, is there a way to make a compile-time check for this feature?

Looking at 
1. https://github.com/xtensor-stack/xtensor/blob/master/include/xtensor/xutils.hpp#L1029
2. https://github.com/xtensor-stack/xtensor/blob/master/include/xtensor/xstorage.hpp#L1415

After this commit, 2 becomes ambiguous. If 2 is deleted, the code doesn't compile before this commit.

Or am I wrong and this code has another problem?

Output after the commit:
```
n file included from xtensor/xexpression_holder.hpp:17:
In file included from xtensor/xarray.hpp:19:
In file included from xtensor/xbuffer_adaptor.hpp:21:
In file included from xtensor/xstorage.hpp:23:
In file included from xtensor/xtensor_simd.hpp:17:
ERROR: xtensor/xutils.hpp:899:31 ambiguous partial specializations of 'rebind_container<long, xt::svector<unsigned long>>'
  899 |         using type = typename rebind_container<std::ptrdiff_t, S>::type;
      |                               ^
xtensor/xutils.hpp:927:5 in instantiation of template class 'xt::get_strides_type<xt::svector<unsigned long>>' requested here
  927 |     using get_strides_t = typename get_strides_type<C>::type;
      |     ^
xtensor/xarray.hpp:53:30 in instantiation of template type alias 'get_strides_t' requested here
   53 |         using strides_type = get_strides_t<shape_type>;
      |                              ^
xtensor/xcontainer.hpp:36:43 in instantiation of template class 'xt::xcontainer_inner_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   36 |         using inner_shape_type = typename xcontainer_inner_types<D>::inner_shape_type;
      |                                           ^
xtensor/xarray.hpp:64:11 in instantiation of template class 'xt::xcontainer_iterable_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   64 |         : xcontainer_iterable_types<xarray_container<EC, L, SC, Tag>>
      |           ^
xtensor/xiterable.hpp:43:43 in instantiation of template class 'xt::xiterable_inner_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   43 |         using inner_shape_type = typename iterable_types::inner_shape_type;
      |                                           ^
xtensor/xiterable.hpp:151:30 (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  151 |     class xiterable : public xconst_iterable<D>
      |                              ^
xtensor/xiterable.hpp:311:42 in instantiation of template class 'xt::xiterable<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
  311 |     class xcontiguous_iterable : private xiterable<D>
      |                                          ^
xtensor/xcontainer.hpp:71:31 in instantiation of template class 'xt::xcontiguous_iterable<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   71 |     class xcontainer : public xcontiguous_iterable<D>,
      |                               ^
xtensor/xcontainer.hpp:260:39 in instantiation of template class 'xt::xcontainer<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
  260 |     class xstrided_container : public xcontainer<D>
      |                                       ^
xtensor/xarray.hpp:82:37 in instantiation of template class 'xt::xstrided_container<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   82 |     class xarray_container : public xstrided_container<xarray_container<EC, L, SC, Tag>>,
      |                                     ^
xtensor/xexpression_holder.hpp:192:32 in instantiation of template class 'xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>' requested here
  192 |             xt::xarray<double> empty_arr;
      |                                ^
xtensor/xutils.hpp:886:12 partial specialization matches [with X = long, C = xt::svector, T = unsigned long, N = 4]
  886 |     struct rebind_container<X, C<T, N>>
      |            ^
xtensor/xstorage.hpp:1415:12 partial specialization matches [with X = long, T = unsigned long, N = 4, A = std::allocator<unsigned long>, B = true]
 1415 |     struct rebind_container<X, svector<T, N, A, B>>
      |            ^
```

Output before the commit if the second specialization is deleted:
```
In file included from xtensor/test/test_extended_broadcast_view.cpp:15:
In file included from xtensor/xarray.hpp:19:
In file included from xtensor/xbuffer_adaptor.hpp:21:
In file included from xtensor/xstorage.hpp:23:
In file included from xtensor/xtensor_simd.hpp:17:
xtensor/xutils.hpp:899:31: error: implicit instantiation of undefined template 'xt::rebind_container<long, xt::svector<unsigned long>>'
  899 |         using type = typename rebind_container<std::ptrdiff_t, S>::type;
      |                               ^
xtensor/xutils.hpp:927:5: note: in instantiation of template class 'xt::get_strides_type<xt::svector<unsigned long>>' requested here
  927 |     using get_strides_t = typename get_strides_type<C>::type;
      |     ^
xtensor/xarray.hpp:53:30: note: in instantiation of template type alias 'get_strides_t' requested here
   53 |         using strides_type = get_strides_t<shape_type>;
      |                              ^
xtensor/xcontainer.hpp:36:43: note: in instantiation of template class 'xt::xcontainer_inner_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   36 |         using inner_shape_type = typename xcontainer_inner_types<D>::inner_shape_type;
      |                                           ^
xtensor/xarray.hpp:64:11: note: in instantiation of template class 'xt::xcontainer_iterable_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   64 |         : xcontainer_iterable_types<xarray_container<EC, L, SC, Tag>>
      |           ^
xtensor/xiterable.hpp:43:43: note: in instantiation of template class 'xt::xiterable_inner_types<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   43 |         using inner_shape_type = typename iterable_types::inner_shape_type;
      |                                           ^
xtensor/xiterable.hpp:151:30: note: (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  151 |     class xiterable : public xconst_iterable<D>
      |                              ^
xtensor/xiterable.hpp:311:42: note: in instantiation of template class 'xt::xiterable<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
  311 |     class xcontiguous_iterable : private xiterable<D>
      |                                          ^
xtensor/xcontainer.hpp:71:31: note: in instantiation of template class 'xt::xcontiguous_iterable<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   71 |     class xcontainer : public xcontiguous_iterable<D>,
      |                               ^
xtensor/xcontainer.hpp:260:39: note: in instantiation of template class 'xt::xcontainer<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
  260 |     class xstrided_container : public xcontainer<D>
      |                                       ^
xtensor/xarray.hpp:82:37: note: in instantiation of template class 'xt::xstrided_container<xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>>' requested here
   82 |     class xarray_container : public xstrided_container<xarray_container<EC, L, SC, Tag>>,
      |                                     ^
xtensor/test/test_extended_broadcast_view.cpp:34:24: note: in instantiation of template class 'xt::xarray_container<xt::uvector<double>, xt::layout_type::row_major, xt::svector<unsigned long>>' requested here
   34 |         xarray<double> py_a = {
      |                        ^
xtensor/xutils.hpp:79:12: note: template is declared here
   79 |     struct rebind_container;
      |            ^
```

**Comment by mizvekov** [comment]
> Hi, is there a way to make a compile-time check for this feature?

Yes, this is exposed by a standard feature testing macro: https://en.cppreference.com/w/cpp/feature_test#cpp_template_template_args

> 
> Looking at
> 

Thanks for reporting this. A few questions:
* Does https://github.com/llvm/llvm-project/pull/90820 help here?
* Does it reproduce with GCC, using `-std=c++17` and above?
* Are you able to reduce this test case?

**Comment by mizvekov** [comment]
Oh I see the code already includes workaround for GCC vs non-GCC. It's possible in this case you may replace the workaround with a check for the feature testing macro.

But if this is a new ambiguity not covered by any of the cases I am tracking, it could still be worthwhile to isolate it. It could be we can cover it with new provisional wording.

**Comment by eaeltsin** [comment]
Thanks, guarding the second specialization with the feature test macro works.

I will try to reduce the test case tomorrow, if you still need this.

**Comment by mizvekov** [comment]
> Thanks, guarding the second specialization with the feature test macro works.
> 
> 
> 
> I will try to reduce the test case tomorrow, if you still need this.
> 
> 

Thanks. If it's not too much work for you, that would be great. Otherwise, I think a pretty good guess can be made from reading the source code, but I may not be able to try until next week. If that happens and I still don't manage to reproduce it, I will ask again.

**Comment by sam-mccall** [comment]
This patch introduced a crash on code that clang previously accepted (I'm not sure whether the code is correct).

The code is https://github.com/nvidia/stdexec/tree/467f4a68ee04f3bb4c35e7a5dd13a3419da160cb, building `test/stdexec/algos/adaptors/test_stopped_as_optional.cpp` crashes.

<details>
<summary>Errors prior to crash</summary>

```
third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:38:19: error: static assertion failed
   38 |     static_assert(ex::sender_in<decltype(snd), empty_env>);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:38:19: note: because 'ex::sender_in<decltype(snd), empty_env>' evaluated to false
./third_party/stdexec/include/stdexec/execution.hpp:824:9: note: because 'decltype(__impl<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>()())' (aka 'stdexec::_ERROR_<stdexec::_BAD_SUBSTITUTION_<>, stdexec::_WITH_META_FUNCTION_T_<stdexec::__try_value_types_of_t>, stdexec::_WITH_TYPES_<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env, stdexec::__q<stdexec::__stopped_as_xxx::__stopped_as_optional_impl::__set_value_t>, stdexec::__q<stdexec::__compl_sigs::__ensure_concat>>>') does not satisfy '__valid_completion_signatures':
  824 |         get_completion_signatures((_Sender&&) __sndr, (_Env&&) __env)
      |         ^
./third_party/stdexec/include/stdexec/execution.hpp:273:5: note: because 'stdexec::_ERROR_<stdexec::_BAD_SUBSTITUTION_<>, stdexec::_WITH_META_FUNCTION_T_<stdexec::__try_value_types_of_t>, stdexec::_WITH_TYPES_<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env, stdexec::__q<stdexec::__stopped_as_xxx::__stopped_as_optional_impl::__set_value_t>, stdexec::__q<stdexec::__compl_sigs::__ensure_concat>>>' does not satisfy '__ok'
  273 |     __ok<_Completions> && __is_instance_of<_Completions, completion_signatures>;
      |     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:243:18: note: because '__same_as<__ok_t<_ERROR_<_BAD_SUBSTITUTION_<__mstring<76UL>{"The specified meta-function could not be evaluated with the types provided."}>, _WITH_META_FUNCTION_T_<stdexec::__try_value_types_of_t>, _WITH_TYPES_<__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, empty_env, __q<stdexec::__stopped_as_xxx::__stopped_as_optional_impl::__set_value_t>, __q<stdexec::__compl_sigs::__ensure_concat> > > >, __msuccess>' evaluated to false
  243 |   concept __ok = __same_as<__ok_t<_Arg>, __msuccess>;
      |                  ^
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:51:23: note: because '__is_same(stdexec::_ERROR_<stdexec::_BAD_SUBSTITUTION_<>, stdexec::_WITH_META_FUNCTION_T_<stdexec::__try_value_types_of_t>, stdexec::_WITH_TYPES_<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env, stdexec::__q<stdexec::__stopped_as_xxx::__stopped_as_optional_impl::__set_value_t>, stdexec::__q<stdexec::__compl_sigs::__ensure_concat> > >, int)' evaluated to false
   51 |   concept __same_as = __is_same(_Ap, _Bp);
      |                       ^
third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:45:15: error: no matching function for call to object of type 'const __connect::connect_t'
   45 |     auto op = ex::connect(std::move(snd), expect_value_receiver{std::optional<int>{}});
      |               ^~~~~~~~~~~
./third_party/stdexec/include/stdexec/execution.hpp:1471:12: note: candidate template ignored: constraints not satisfied [with _Sender = __libcpp_remove_reference_t<__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)> &>, _Receiver = expect_value_receiver<empty_env, optional<int>>]
 1471 |       auto operator()(_Sender&& __sndr, _Receiver&& __rcvr) const
      |            ^
./third_party/stdexec/include/stdexec/execution.hpp:1468:18: note: because '__connectable_with_tag_invoke<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_value_receiver<stdexec::__env::empty_env, std::optional<int> > >' evaluated to false
 1468 |         requires __connectable_with_tag_invoke<_Sender, _Receiver>
      |                  ^
./third_party/stdexec/include/stdexec/execution.hpp:1415:7: note: because '__connectable_with_tag_invoke_<__tfx_sender<__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, expect_value_receiver<empty_env, optional<int> > >, (anonymous namespace)::expect_value_receiver<stdexec::__env::empty_env, std::optional<int> > >' evaluated to false
 1415 |       __connectable_with_tag_invoke_<__tfx_sender<_Sender, _Receiver>, _Receiver>;
      |       ^
./third_party/stdexec/include/stdexec/execution.hpp:1409:7: note: because 'sender_in<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, env_of_t<expect_value_receiver<empty_env, optional<int> > > >' evaluated to false
 1409 |       sender_in<_Sender, env_of_t<_Receiver>> && //
      |       ^
./third_party/stdexec/include/stdexec/execution.hpp:824:9: note: because 'decltype(__impl<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>()())' (aka '_ERROR_<stdexec::__error__::_UNRECOGNIZED_SENDER_TYPE_<__mstring<134UL>{"The given type cannot be used as a[...]"}>, stdexec::__error__::_WITH_SENDER_<stdexec::__sexpr<stdexec::__stopped_as_xxx::stopped_as_optional_t, stdexec::__, stdexec::__sexpr<stdexec::__transfer_just::transfer_just_t, std::tuple<(anonymous namespace)::stopped_scheduler, int>>>>, stdexec::__error__::_WITH_ENVIRONMENT_<stdexec::__env::empty_env>>') does not satisfy '__valid_completion_signatures':
  824 |         get_completion_signatures((_Sender&&) __sndr, (_Env&&) __env)
      |         ^
./third_party/stdexec/include/stdexec/execution.hpp:273:5: note: because 'stdexec::_ERROR_<stdexec::__error__::_UNRECOGNIZED_SENDER_TYPE_<>, stdexec::__error__::_WITH_SENDER_<stdexec::__sexpr<stdexec::__stopped_as_xxx::stopped_as_optional_t, stdexec::__, stdexec::__sexpr<stdexec::__transfer_just::transfer_just_t, std::tuple<(anonymous namespace)::stopped_scheduler, int>>>>, stdexec::__error__::_WITH_ENVIRONMENT_<stdexec::__env::empty_env>>' does not satisfy '__ok'
  273 |     __ok<_Completions> && __is_instance_of<_Completions, completion_signatures>;
      |     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:243:18: note: because '__same_as<__ok_t<_ERROR_<_UNRECOGNIZED_SENDER_TYPE_<__mstring<134UL>{"The given type cannot be used as a sender with the given environment because the attempt to compute the completion signatures failed."}>, _WITH_SENDER_<__sexpr<stopped_as_optional_t, __, __sexpr<transfer_just_t, tuple<stopped_scheduler, int> > > >, _WITH_ENVIRONMENT_<empty_env> > >, __msuccess>' evaluated to false
  243 |   concept __ok = __same_as<__ok_t<_Arg>, __msuccess>;
      |                  ^
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:51:23: note: because '__is_same(stdexec::_ERROR_<stdexec::__error__::_UNRECOGNIZED_SENDER_TYPE_<>, stdexec::__error__::_WITH_SENDER_<stdexec::__sexpr<stdexec::__stopped_as_xxx::stopped_as_optional_t, stdexec::__, stdexec::__sexpr<stdexec::__transfer_just::transfer_just_t, std::tuple<(anonymous namespace)::stopped_scheduler, int> > > >, stdexec::__error__::_WITH_ENVIRONMENT_<stdexec::__env::empty_env> >, int)' evaluated to false
   51 |   concept __same_as = __is_same(_Ap, _Bp);
      |                       ^
./third_party/stdexec/include/stdexec/execution.hpp:1469:18: note: and '__connectable_with_co_await<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_value_receiver<stdexec::__env::empty_env, std::optional<int> > >' evaluated to false
 1469 |               || __connectable_with_co_await<_Sender, _Receiver>
      |                  ^
./third_party/stdexec/include/stdexec/execution.hpp:1419:7: note: because '__callable<__connect_awaitable_t, __tfx_sender<__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, expect_value_receiver<empty_env, optional<int> > >, (anonymous namespace)::expect_value_receiver<stdexec::__env::empty_env, std::optional<int> > >' evaluated to false
 1419 |       __callable<__connect_awaitable_t, __tfx_sender<_Sender, _Receiver>, _Receiver>;
      |       ^
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:31:7: note: because '((_Fun &&)__fun)((_As &&)__as...)' would be invalid: no matching function for call to object of type 'stdexec::__connect_awaitable_::__connect_awaitable_t'
   31 |       ((_Fun&&) __fun)((_As&&) __as...);    //
      |       ^
./third_party/stdexec/include/stdexec/execution.hpp:1470:18: note: and 'env_of_t<expect_value_receiver<empty_env, optional<int>>>' (aka 'stdexec::__env::empty_env') does not satisfy '__is_debug_env'
 1470 |               || __is_debug_env<env_of_t<_Receiver>>
      |                  ^
./third_party/stdexec/include/stdexec/execution.hpp:382:30: note: because 'tag_invocable<__debug::__is_debug_env_t, stdexec::__env::empty_env>' evaluated to false
  382 |     concept __is_debug_env = tag_invocable<__debug::__is_debug_env_t, _Env>;
      |                              ^
./third_party/stdexec/include/stdexec/functional.hpp:319:49: note: because 'tag_invoke((_Tag &&)__tag, (_Args &&)__args...)' would be invalid: no matching function for call to 'tag_invoke'
  319 |       requires(_Tag __tag, _Args&&... __args) { tag_invoke((_Tag&&) __tag, (_Args&&) __args...); };
      |                                                 ^
In file included from third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:18:
./third_party/stdexec/include/stdexec/execution.hpp:262:18: error: no matching function for call to '__for_all_sigs_'
  262 |         decltype(__compl_sigs::__for_all_sigs_( //
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:301:5: note: in instantiation of template type alias '__for_all_sigs' requested here
  301 |     using __g = _Fn<_Args...>;
      |     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:291:3: note: in instantiation of template type alias '__g' requested here
  291 |   using __meval = typename __i<_Ok<_Args...>>::template __g<_Fn, _Args...>;
      |   ^
./third_party/stdexec/include/stdexec/execution.hpp:268:5: note: in instantiation of template type alias '__meval' requested here
  268 |     using __maybe_for_all_sigs = __meval<__for_all_sigs, _Completions, _TaggedTuple, _Variant>;
      |     ^
./third_party/stdexec/include/stdexec/execution.hpp:884:3: note: in instantiation of template type alias '__maybe_for_all_sigs' requested here
  884 |   using __only_gather_signal = //
      |   ^
./third_party/stdexec/include/stdexec/execution.hpp:891:3: note: in instantiation of template type alias '__only_gather_signal' requested here
  891 |   using __gather_signal = //
      |   ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:301:5: note: in instantiation of template type alias '__gather_signal' requested here
  301 |     using __g = _Fn<_Args...>;
      |     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:291:3: note: in instantiation of template type alias '__g' requested here
  291 |   using __meval = typename __i<_Ok<_Args...>>::template __g<_Fn, _Args...>;
      |   ^
./third_party/stdexec/include/stdexec/execution.hpp:898:3: note: in instantiation of template type alias '__meval' requested here
  898 |   using __gather_completions_for = //
      |   ^
./third_party/stdexec/include/stdexec/execution.hpp:3559:5: note: in instantiation of template type alias '__gather_completions_for' requested here
 3559 |     using __result_domain_t = //
      |     ^
./third_party/stdexec/include/stdexec/execution.hpp:3599:27: note: in instantiation of template type alias '__result_domain_t' requested here
 3599 |           using _Domain = __result_domain_t<_Set, _Child, _Fun, _Env, _Sched>;
      |                           ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: in instantiation of function template specialization 'stdexec::__let::__mk_transform_sender_fn(const stdexec::__env::empty_env &)::(anonymous class)::operator()<(lambda at third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:66:23), (anonymous namespace)::fallible_just<int>>' requested here
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:597:21: note: in instantiation of template type alias '__call_result_t' requested here
  597 |                  -> __call_result_t<_Fun, _Tag, __minvoke<_Cvref, _Captures>...>
      |                     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: while substituting deduced template arguments into function template 'operator()' [with _Cvref = stdexec::__cp, _Fun = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:3593:14)]
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:502:10: note: in instantiation of template type alias '__call_result_t' requested here
  502 |       -> __call_result_t<__detail::__impl_of<_Sender>, __copy_cvref_fn<_Sender>, _ApplyFn> {  //
      |          ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:629:76: note: while substituting deduced template arguments into function template 'apply' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:3593:14)]
  629 |         -> decltype(STDEXEC_CALL_EXPLICIT_THIS_MEMFN(((_Sender&&) __sndr), apply)(
      |                                                                            ^
./third_party/stdexec/include/stdexec/execution.hpp:3678:16: note: while substituting deduced template arguments into function template 'operator()' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:3593:14)]
 3678 |         return __sexpr_apply((_Sender&&) __sndr, __mk_transform_sender_fn<__let_t<_Set>>(__env));
      |                ^
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:15: note: in instantiation of function template specialization 'stdexec::__let::__let_t<stdexec::__receivers::set_error_t>::transform_sender<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |               ^
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:9: note: in instantiation of requirement here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:58:7: note: while substituting template arguments into constraint expression here
   58 |       requires(_DomainOrTag __tag, _Sender&& __sender, const _Env&... __env) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |       };
      |       ~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:65:10: note: while checking the satisfaction of concept '__has_transform_sender<stdexec::__let::__let_t<stdexec::__receivers::set_error_t>, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   65 |       && __has_transform_sender<tag_of_t<_Sender>, _Sender, _Env...>;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:65:10: note: while substituting template arguments into constraint expression here
   65 |       && __has_transform_sender<tag_of_t<_Sender>, _Sender, _Env...>;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:105:21: note: while checking the satisfaction of concept '__has_default_transform_sender<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  105 |       if constexpr (__domain::__has_default_transform_sender<_Sender, _Env>) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:15: note: in instantiation of function template specialization 'stdexec::default_domain::transform_sender<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |               ^
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:9: note: in instantiation of requirement here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:58:7: note: while substituting template arguments into constraint expression here
   58 |       requires(_DomainOrTag __tag, _Sender&& __sender, const _Env&... __env) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |       };
      |       ~
./third_party/stdexec/include/stdexec/execution.hpp:601:23: note: while checking the satisfaction of concept '__has_transform_sender<stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  601 |         if constexpr (__domain::__has_transform_sender<_Domain, _Sender, _Env...>) {
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: in instantiation of function template specialization 'stdexec::__domain::__transform_sender_1::operator()<stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/execution.hpp:617:26: note: in instantiation of template type alias '__call_result_t' requested here
  617 |         using _Sender2 = __call_result_t<__transform_sender_1, _Domain, _Sender, const _Env&...>;
      |                          ^
./third_party/stdexec/include/stdexec/execution.hpp:682:18: note: in instantiation of function template specialization 'stdexec::__domain::__transform_sender::operator()<stdexec::__domain::__transform_sender, stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  682 |           return __domain::__transform_sender()(__domain2, std::move(__sndr2), __env);
      |                  ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: in instantiation of function template specialization 'stdexec::dependent_domain::transform_sender(stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)> &&, const stdexec::__env::empty_env &)::(anonymous class)::operator()<stdexec::__let::__let_t<stdexec::__receivers::set_error_t>, (lambda at third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:66:23), (anonymous namespace)::fallible_just<int>>' requested here
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:597:21: note: in instantiation of template type alias '__call_result_t' requested here
  597 |                  -> __call_result_t<_Fun, _Tag, __minvoke<_Cvref, _Captures>...>
      |                     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: while substituting deduced template arguments into function template 'operator()' [with _Cvref = stdexec::__cp, _Fun = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:502:10: note: in instantiation of template type alias '__call_result_t' requested here
  502 |       -> __call_result_t<__detail::__impl_of<_Sender>, __copy_cvref_fn<_Sender>, _ApplyFn> {  //
      |          ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:629:76: note: while substituting deduced template arguments into function template 'apply' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  629 |         -> decltype(STDEXEC_CALL_EXPLICIT_THIS_MEMFN(((_Sender&&) __sndr), apply)(
      |                                                                            ^
./third_party/stdexec/include/stdexec/execution.hpp:668:12: note: while substituting deduced template arguments into function template 'operator()' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  668 |     return __sexpr_apply(
      |            ^
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:15: note: in instantiation of function template specialization 'stdexec::dependent_domain::transform_sender<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |               ^
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:59:9: note: in instantiation of requirement here
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__domain.hpp:58:7: note: while substituting template arguments into constraint expression here
   58 |       requires(_DomainOrTag __tag, _Sender&& __sender, const _Env&... __env) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   59 |         __tag.transform_sender((_Sender&&) __sender, __env...);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |       };
      |       ~
./third_party/stdexec/include/stdexec/execution.hpp:601:23: note: while checking the satisfaction of concept '__has_transform_sender<stdexec::dependent_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  601 |         if constexpr (__domain::__has_transform_sender<_Domain, _Sender, _Env...>) {
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: in instantiation of function template specialization 'stdexec::__domain::__transform_sender_1::operator()<stdexec::dependent_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/execution.hpp:617:26: note: in instantiation of template type alias '__call_result_t' requested here
  617 |         using _Sender2 = __call_result_t<__transform_sender_1, _Domain, _Sender, const _Env&...>;
      |                          ^
./third_party/stdexec/include/stdexec/execution.hpp:673:29: note: in instantiation of function template specialization 'stdexec::__domain::__transform_sender::operator()<stdexec::__domain::__transform_sender, stdexec::dependent_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  673 |           (_Data&&) __data, __domain::__transform_sender()(*this, (_Childs&&) __childs, __env2)...);
      |                             ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: in instantiation of function template specialization 'stdexec::dependent_domain::transform_sender(stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)> &&, const stdexec::__env::empty_env &)::(anonymous class)::operator()<stdexec::__stopped_as_xxx::stopped_as_optional_t, stdexec::__, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>>' requested here
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:597:21: note: in instantiation of template type alias '__call_result_t' requested here
  597 |                  -> __call_result_t<_Fun, _Tag, __minvoke<_Cvref, _Captures>...>
      |                     ^
./third_party/stdexec/include/stdexec/__detail/__meta.hpp:753:36: note: while substituting deduced template arguments into function template 'operator()' [with _Cvref = stdexec::__cp, _Fun = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  753 |   using __call_result_t = decltype(__declval<_Fun>()(__declval<_As>()...));
      |                                    ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:502:10: note: in instantiation of template type alias '__call_result_t' requested here
  502 |       -> __call_result_t<__detail::__impl_of<_Sender>, __copy_cvref_fn<_Sender>, _ApplyFn> {  //
      |          ^
./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:629:76: note: while substituting deduced template arguments into function template 'apply' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  629 |         -> decltype(STDEXEC_CALL_EXPLICIT_THIS_MEMFN(((_Sender&&) __sndr), apply)(
      |                                                                            ^
./third_party/stdexec/include/stdexec/execution.hpp:668:12: note: while substituting deduced template arguments into function template 'operator()' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _ApplyFn = (lambda at ./third_party/stdexec/include/stdexec/execution.hpp:670:7)]
  668 |     return __sexpr_apply(
      |            ^
./third_party/stdexec/include/stdexec/execution.hpp:640:37: note: in instantiation of function template specialization 'stdexec::dependent_domain::transform_sender<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
  640 |           __dom, dependent_domain().transform_sender((_Sender&&) __sndr, __env), __env);
      |                                     ^
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:31:7: note: in instantiation of function template specialization 'stdexec::__domain::__transform_dependent_sender::operator()<stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   31 |       ((_Fun&&) __fun)((_As&&) __as...);    //
      |       ^
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:31:7: note: in instantiation of requirement here
   31 |       ((_Fun&&) __fun)((_As&&) __as...);    //
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:30:5: note: while substituting template arguments into constraint expression here
   30 |     requires(_Fun&& __fun, _As&&... __as) { //
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |       ((_Fun&&) __fun)((_As&&) __as...);    //
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   32 |     };
      |     ~
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:35:5: note: while checking the satisfaction of concept '__callable<stdexec::transform_sender_t, stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
   35 |     __callable<_Fun, _As...> && //
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/__detail/__concepts.hpp:35:5: note: while substituting template arguments into constraint expression here
   35 |     __callable<_Fun, _As...> && //
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/execution.hpp:1443:14: note: while checking the satisfaction of concept '__nothrow_callable<stdexec::transform_sender_t, stdexec::default_domain, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, stdexec::__env::empty_env>' requested here
 1443 |           && __nothrow_callable<transform_sender_t, _Domain, _Sender, env_of_t<_Receiver&>>;
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/execution.hpp:1465:40: note: in instantiation of function template specialization 'stdexec::__connect::connect_t::__select_impl<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>' requested here
 1465 |       using __select_impl_t = decltype(__select_impl<_Sender, _Receiver>());
      |                                        ^
./third_party/stdexec/include/stdexec/execution.hpp:1473:30: note: in instantiation of template type alias '__select_impl_t' requested here
 1473 |           -> __call_result_t<__select_impl_t<_Sender, _Receiver>> {
      |                              ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:147:10: note: while substituting deduced template arguments into function template 'operator()' [with _Sender = stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, _Receiver = (anonymous namespace)::expect_error_receiver<>]
  147 | decltype(std::declval<_Fp>()(std::declval<_Args>()...))
      |          ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:157:19: note: while substituting deduced template arguments into function template '__invoke' [with _Fp = stdexec::__connect::connect_t, _Args = <stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>]
  157 |   static decltype(std::__invoke(std::declval<_XFp>(), std::declval<_XArgs>()...)) __try_call(int);
      |                   ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:163:28: note: while substituting deduced template arguments into function template '__try_call' [with _XFp = stdexec::__connect::connect_t, _XArgs = (no value)]
  163 |   using _Result = decltype(__try_call<_Fp, _Args...>(0));
      |                            ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:211:24: note: in instantiation of template class 'std::__invokable_r<void, stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>' requested here
  211 |     : public enable_if<__invokable<_Fp, _Args...>::value, typename __invokable_r<void, _Fp, _Args...>::_Result> {};
      |                        ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:262:45: note: in instantiation of template class 'std::__invoke_of<stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>' requested here
  262 | struct _LIBCPP_TEMPLATE_VIS invoke_result : __invoke_of<_Fn, _Args...> {};
      |                                             ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:265:1: note: in instantiation of template class 'std::invoke_result<stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>' requested here
  265 | using invoke_result_t = typename invoke_result<_Fn, _Args...>::type;
      | ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__functional/invoke.h:26:53: note: in instantiation of template type alias 'invoke_result_t' requested here
   26 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 invoke_result_t<_Fn, _Args...>
      |                                                     ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__concepts/invocable.h:28:3: note: while substituting deduced template arguments into function template 'invoke' [with _Fn = stdexec::__connect::connect_t, _Args = <stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>]
   28 |   std::invoke(std::forward<_Fn>(__fn), std::forward<_Args>(__args)...); // not required to be equality preserving
      |   ^
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__concepts/invocable.h:28:3: note: in instantiation of requirement here
   28 |   std::invoke(std::forward<_Fn>(__fn), std::forward<_Args>(__args)...); // not required to be equality preserving
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__concepts/invocable.h:27:21: note: while substituting template arguments into constraint expression here
   27 | concept invocable = requires(_Fn&& __fn, _Args&&... __args) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   28 |   std::invoke(std::forward<_Fn>(__fn), std::forward<_Args>(__args)...); // not required to be equality preserving
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   29 | };
      | ~
third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:69:20: note: while checking the satisfaction of concept 'invocable<stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>' requested here
   69 |     static_assert(!std::invocable);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/stdexec/include/stdexec/execution.hpp:256:10: note: candidate template ignored: substitution failure [with _TaggedTuple = stdexec::__mtry_catch<stdexec::__select_completions_for<stdexec::__receivers::set_error_t, stdexec::__qf<stdexec::__receivers::set_error_t>>, stdexec::__mconst<stdexec::__>>, _Variant = stdexec::__remove<stdexec::__, stdexec::__q<stdexec::completion_signatures>>, _Sigs = <stdexec::__receivers::set_value_t (int), stdexec::__receivers::set_error_t (std::exception_ptr)>]: pack expansion used as argument for non-pack parameter of alias template
  256 |     auto __for_all_sigs_(completion_signatures<_Sigs...>*, _TaggedTuple*, _Variant*)
      |          ^
```

</details>

<details>
<summary>Crash dump</summary>

```
PLEASE submit a bug report to http://go/clang-crash-bug and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang -frandom-seed=blaze-out/k8-fastbuild/bin/third_party/stdexec/test/_objs/stdexec_algos_adaptors_test_stopped_as_optional/test_stopped_as_optional.pic.o -DCATCH_CONFIG_NO_CPP17_UNCAUGHT_EXCEPTIONS -DSTDEXEC_USE_EXCEPTIONS -DABSL_ALLOCATOR_NOTHROW -DINTERNAL_DEPLOYMENT -iquote . -iquote blaze-out/k8-fastbuild/genfiles -iquote blaze-out/k8-fastbuild/bin -iquote blaze-out/k8-fastbuild-ST-c90edcb1652f/genfiles -iquote blaze-out/k8-fastbuild-ST-c90edcb1652f/bin -isystem third_party/catch/single_include -isystem blaze-out/k8-fastbuild/genfiles/third_party/catch/single_include -isystem blaze-out/k8-fastbuild/bin/third_party/catch/single_include -isystem third_party/stl/cxx17 -isystem blaze-out/k8-fastbuild-ST-c90edcb1652f/genfiles/third_party/stl/cxx17 -isystem blaze-out/k8-fastbuild-ST-c90edcb1652f/bin/third_party/stl/cxx17 -isystem third_party/stl/itanium_abi -isystem blaze-out/k8-fastbuild-ST-c90edcb1652f/genfiles/third_party/stl/itanium_abi -isystem blaze-out/k8-fastbuild-ST-c90edcb1652f/bin/third_party/stl/itanium_abi -fno-omit-frame-pointer -no-canonical-prefixes -DCOMPILER_GCC3 -DCOMPILER_GCC4 -DGOOGLE_GLIBCXX_VERSION=40901 -DHASH_NAMESPACE=__gnu_cxx -D__STDC_FORMAT_MACROS -DSUPPRESS_USE_FILE_OFFSET64 -fdiagnostics-show-option -fmessage-length=0 -fno-exceptions -fbracket-depth=768 -fno-strict-aliasing -fmerge-all-constants -flax-vector-conversions=all -funsigned-char -ffile-reproducible -fcolor-diagnostics -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -fno-assume-unique-vtables -Wall -Werror -Wno-address-of-packed-member -Wno-defaulted-function-deleted -Wno-enum-compare-switch -Wno-expansion-to-defined -Wno-ignored-attributes -Wno-ignored-qualifiers -Wno-inconsistent-missing-override -Wno-potentially-evaluated-expression -Wno-range-loop-analysis -Wno-strict-prototypes -Wno-tautological-type-limit-compare -Wno-tautological-undefined-compare -Wno-tautological-unsigned-zero-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-undefined-func-template -Wno-unused-but-set-variable -Wno-unused-lambda-capture -Wno-unused-local-typedef -Wno-deprecated-builtins -Wno-deprecated-volatile -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-compare -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-compare-conditional -Wno-deprecated-enum-float-conversion -Wno-deprecated-this-capture -Wno-deprecated-array-compare -Wno-deprecated-comma-subscript -Wno-bitfield-constant-conversion -Wno-bitwise-instead-of-logical -Wno-comment -Wno-compound-token-split -Wno-deprecated-non-prototype -Wno-enum-constexpr-conversion -Wno-misleading-indentation -Wno-psabi -Wno-unqualified-std-cast-call -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-deprecated-declarations -Wno-deprecated-pragma -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-implicit-int-float-conversion -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-private-header -Wno-sign-compare -Wno-strict-overflow -Wno-unknown-pragmas -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-private-field -Wno-user-defined-warnings -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wunused-but-set-parameter -Wunused-comparison -Wvla -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wctad-maybe-unsupported -Wgoogle3-inline-namespace -Wgoogle3-literal-operator -Wthread-safety-beta --cuda-host-only -faligned-allocation -fnew-alignment=8 -Wno-trigraphs -Woverloaded-virtual -Wno-invalid-offsetof -Wno-final-dtor-non-final-class -Wnon-virtual-dtor -Wimplicit-fallthrough -fshow-overloads=best -Wno-c++23-lambda-attributes -fcoro-aligned-allocation -O1 -fno-asynchronous-unwind-tables -ffp-contract=off --target=x86_64-grtev4-linux-gnu -DOS_LINUX -fno-unique-section-names -maes -mcx16 -msse4.2 -mpclmul -mprefer-vector-width=128 -mprfchw -fsplit-dwarf-inlining -gz=zstd --system-header-prefix=third_party/ --no-system-header-prefix=third_party/absl/ --no-system-header-prefix=third_party/blue/ --no-system-header-prefix=third_party/car/ --no-system-header-prefix=third_party/crubit/ --no-system-header-prefix=third_party/diff/ --no-system-header-prefix=third_party/eigen3/ --no-system-header-prefix=third_party/giza/ --no-system-header-prefix=third_party/gnupg/ --no-system-header-prefix=third_party/gnupg2/ --no-system-header-prefix=third_party/gpus/nccl_plugins/ --no-system-header-prefix=third_party/golang/ --no-system-header-prefix=third_party/google_home_platform/ --no-system-header-prefix=third_party/googlefuzztest/ --no-system-header-prefix=third_party/googletest/ --no-system-header-prefix=third_party/halide/ --no-system-header-prefix=third_party/icu/ --no-system-header-prefix=third_party/iree/ --no-system-header-prefix=third_party/libaddressinput/ --no-system-header-prefix=third_party/libwebp/ --no-system-header-prefix=third_party/llvm/ --no-system-header-prefix=third_party/mlir_edge/ --no-system-header-prefix=third_party/nik/ --no-system-header-prefix=third_party/nss/ --no-system-header-prefix=third_party/openssl/ --no-system-header-prefix=third_party/program_image_remapper/ --no-system-header-prefix=third_party/protobuf/ --no-system-header-prefix=third_party/py/riegeli/ --no-system-header-prefix=third_party/riegeli/ --no-system-header-prefix=third_party/safari/ --no-system-header-prefix=third_party/sketchology/ --no-system-header-prefix=third_party/stg/ --no-system-header-prefix=third_party/tcmalloc/ --no-system-header-prefix=third_party/tensorflow/ --no-system-header-prefix=third_party/tensorflow_text/ --no-system-header-prefix=third_party/tink/ --no-system-header-prefix=third_party/windmill/ -Wthread-safety-analysis -D__GOOGLE3_RANDOMIZATION_ROLLOUT=6 -D_LIBCPP_DEBUG_RANDOMIZE_UNSPECIFIED_STABILITY -D_LIBCPP_DEBUG_STRICT_WEAK_ORDERING_CHECK -D_LIBCPP_ENABLE_CXX17_REMOVED_RANDOM_SHUFFLE -D_LIBCPP_ENABLE_CXX17_REMOVED_BINDERS -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -D_LIBCPP_ENABLE_CXX20_REMOVED_BINDER_TYPEDEFS -D_LIBCPP_ENABLE_CXX20_REMOVED_NEGATORS -D_LIBCPP_ENABLE_CXX20_REMOVED_SHARED_PTR_UNIQUE -D_LIBCPP_ENABLE_CXX20_REMOVED_RAW_STORAGE_ITERATOR -D_LIBCPP_ENABLE_CXX20_REMOVED_TYPE_TRAITS -D_LIBCPP_GOOGLE3_EARLY_DELETED_STRING_VIEW_NULLPTR_CTOR -fsanitize=alignment,return,returns-nonnull-attribute,vla-bound,unreachable,float-cast-overflow -fsanitize-trap=all -DUNDEFINED_BEHAVIOR_SANITIZER -fsanitize=null -fmodule-name=//third_party/stdexec/test:stdexec_algos_adaptors_test_stopped_as_optional -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/stdexec/test/stdexec_algos_adaptors_test_stopped_as_optional.cppmap -Xclang=-fno-cxx-modules -Xclang=-fmodule-map-file-home-is-cwd -fsized-deallocation -fno-direct-access-external-data -fPIE -fPIC -fmodules-strict-decluse -Wprivate-header -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/crosstool/v18/llvm_unstable/gen-crosstool-x86.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/stdexec/test/test_common.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/catch/catch_single_include.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/stdexec/stdexec.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/stdexec/exec.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/third_party/stdexec/stdexec_detail.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/tools/cpp/link_extra_lib.cppmap -fmodule-map-file=blaze-out/k8-fastbuild/bin/tools/cpp/malloc.cppmap -fmodule-map-file=blaze-out/k8-fastbuild-ST-c90edcb1652f/bin/third_party/crosstool/v18/llvm_unstable/stl_cc_library.cppmap -fmodule-map-file=blaze-out/k8-fastbuild-ST-c90edcb1652f/bin/third_party/crosstool/v18/llvm_unstable/src/libc/llvmlibc_cc_library.cppmap -fmodule-map-file=third_party/grte/grte-v5-x86.cppmap -ffunction-sections -fdata-sections -pthread -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -fexceptions -fcoroutines -ftemplate-backtrace-limit=0 -ferror-limit=0 -fmacro-backtrace-limit=0 -Wno-ctad-maybe-unsupported --sysroot=third_party/grte/v5_x86/release/usr/grte/v5 -std=gnu++20 -stdlib=libc++ -Wno-tautological-type-limit-compare -Wno-thread-safety-reference-return -Wno-nan-infinity-disabled -Wno-alias-template-in-declaration-name -Wno-nullability-completeness -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -c third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp -o blaze-out/k8-fastbuild/bin/third_party/stdexec/test/_objs/stdexec_algos_adaptors_test_stopped_as_optional/test_stopped_as_optional.pic.o
1.	third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:69:89: current parser token ')'
2.	third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:26:1: parsing namespace '(anonymous)'
3.	third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:63:40: parsing function body '(anonymous namespace)::C_A_T_C_H_T_E_S_T_10'
4.	third_party/stdexec/test/stdexec/algos/adaptors/test_stopped_as_optional.cpp:63:40: in compound statement ('{}')
5.	third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:262:29: instantiating class definition 'std::invoke_result<stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>'
6.	third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:210:8: instantiating class definition 'std::__invoke_of<stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>'
7.	third_party/crosstool/v18/llvm_unstable/toolchain/bin/../include/c++/v1/__type_traits/invoke.h:155:8: instantiating class definition 'std::__invokable_r<void, stdexec::__connect::connect_t, stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>'
8.	./third_party/stdexec/include/stdexec/execution.hpp:1439:29: instantiating function definition 'stdexec::__connect::connect_t::__select_impl<stdexec::__sexpr<(lambda at ./third_party/stdexec/include/stdexec/__detail/__basic_sender.hpp:594:18)>, (anonymous namespace)::expect_error_receiver<>>'
  #0 0x0000563cd26a92f8 llvm::sys::RunSignalHandlers() (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x80a92f8)
  #1 0x0000563cd2670d16 CrashRecoverySignalHandler(int) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x8070d16)
  #2 0x00007f5b789e1e80 __restore_rt (/usr/grte/v5/lib64/libpthread.so.0+0x14e80)
  #3 0x0000563ccf94406d clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::IntExprEvaluator, bool>::Visit(clang::Stmt const*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x534406d)
  #4 0x0000563ccf8e802c Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x52e802c)
  #5 0x0000563ccf8e3d86 EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x52e3d86)
  #6 0x0000563ccf8e36e5 clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, clang::ASTContext const&, clang::Expr::ConstantExprKind) const (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x52e36e5)
  #7 0x0000563cceb70feb clang::ActionResult<clang::Expr*, true> calculateConstraintSatisfaction<calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::$_0>(clang::Sema&, clang::Expr const*, clang::ConstraintSatisfaction&, calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::$_0&&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4570feb)
  #8 0x0000563cceb6a94e CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x456a94e)
  #9 0x0000563cceb6a6f6 clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x456a6f6)
 #10 0x0000563ccf320c39 clang::Sema::CheckConceptTemplateId(clang::CXXScopeSpec const&, clang::SourceLocation, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::ConceptDecl*, clang::TemplateArgumentListInfo const*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d20c39)
 #11 0x0000563ccf471e56 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformConceptSpecializationExpr(clang::ConceptSpecializationExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e71e56)
 #12 0x0000563ccf492616 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCondition(clang::SourceLocation, clang::VarDecl*, clang::Expr*, clang::Sema::ConditionKind) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e92616)
 #13 0x0000563ccf49053c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformIfStmt(clang::IfStmt*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e9053c)
 #14 0x0000563ccf478e42 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e78e42)
 #15 0x0000563ccf465c02 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e65c02)
 #16 0x0000563ccf4b1c5b clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4eb1c5b)
 #17 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #18 0x0000563ccf3ffb5c clang::Sema::DeduceReturnType(clang::FunctionDecl*, clang::SourceLocation, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dffb5c)
 #19 0x0000563ccee979b4 clang::Sema::DiagnoseUseOfDecl(clang::NamedDecl*, llvm::ArrayRef<clang::SourceLocation>, clang::ObjCInterfaceDecl const*, bool, bool, clang::ObjCInterfaceDecl*, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48979b4)
 #20 0x0000563ccf27bbd3 FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7bbd3)
 #21 0x0000563ccf27baa4 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7baa4)
 #22 0x0000563ccee9fd58 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x489fd58)
 #23 0x0000563cceec2b9b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48c2b9b)
 #24 0x0000563ccf4725bb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e725bb)
 #25 0x0000563ccf48481b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDecltypeType(clang::TypeLocBuilder&, clang::DecltypeTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8481b)
 #26 0x0000563ccf45ee32 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ee32)
 #27 0x0000563ccf45f840 clang::Sema::SubstType(clang::QualType, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5f840)
 #28 0x0000563ccf310188 clang::Sema::CheckTemplateIdType(clang::TemplateName, clang::SourceLocation, clang::TemplateArgumentListInfo&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d10188)
 #29 0x0000563ccf481988 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e81988)
 #30 0x0000563ccf48952a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8952a)
 #31 0x0000563ccf486469 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformElaboratedType(clang::TypeLocBuilder&, clang::ElaboratedTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e86469)
 #32 0x0000563ccf45ee32 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ee32)
 #33 0x0000563ccf466390 (anonymous namespace)::TemplateInstantiator::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e66390)
 #34 0x0000563ccf481274 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e81274)
 #35 0x0000563ccf48952a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8952a)
 #36 0x0000563ccf486469 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformElaboratedType(clang::TypeLocBuilder&, clang::ElaboratedTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e86469)
 #37 0x0000563ccf45ff2c clang::Sema::SubstFunctionDeclType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, clang::CXXRecordDecl*, clang::Qualifiers, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ff2c)
 #38 0x0000563ccf4a9537 clang::TemplateDeclInstantiator::SubstFunctionType(clang::FunctionDecl*, llvm::SmallVectorImpl<clang::ParmVarDecl*>&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea9537)
 #39 0x0000563ccf4a6541 clang::TemplateDeclInstantiator::VisitCXXMethodDecl(clang::CXXMethodDecl*, clang::TemplateParameterList*, clang::TemplateDeclInstantiator::RewriteKind) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea6541)
 #40 0x0000563ccf4df1f9 void llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4edf1f9)
 #41 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #42 0x0000563ccf4afd92 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4eafd92)
 #43 0x0000563ccf3fa834 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfa834)
 #44 0x0000563ccf456f96 void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::$_2>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e56f96)
 #45 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #46 0x0000563ccf3fc253 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfc253)
 #47 0x0000563ccf265009 clang::Sema::AddMethodTemplateCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::TemplateArgumentListInfo*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, clang::OverloadCandidateParamOrder) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c65009)
 #48 0x0000563ccf2852e0 clang::Sema::BuildCallToObjectOfClassType(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c852e0)
 #49 0x0000563cceea0286 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48a0286)
 #50 0x0000563cceec2b9b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48c2b9b)
 #51 0x0000563ccf4725bb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e725bb)
 #52 0x0000563ccf48481b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDecltypeType(clang::TypeLocBuilder&, clang::DecltypeTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8481b)
 #53 0x0000563ccf45fcec clang::Sema::SubstFunctionDeclType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, clang::CXXRecordDecl*, clang::Qualifiers, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5fcec)
 #54 0x0000563ccf4a9537 clang::TemplateDeclInstantiator::SubstFunctionType(clang::FunctionDecl*, llvm::SmallVectorImpl<clang::ParmVarDecl*>&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea9537)
 #55 0x0000563ccf4a7b48 clang::TemplateDeclInstantiator::VisitFunctionDecl(clang::FunctionDecl*, clang::TemplateParameterList*, clang::TemplateDeclInstantiator::RewriteKind) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea7b48)
 #56 0x0000563ccf4df1f9 void llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4edf1f9)
 #57 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #58 0x0000563ccf4afd92 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4eafd92)
 #59 0x0000563ccf3fa834 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfa834)
 #60 0x0000563ccf456f96 void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::$_2>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e56f96)
 #61 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #62 0x0000563ccf3fc253 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfc253)
 #63 0x0000563ccf26558e clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c6558e)
 #64 0x0000563ccf27b45d AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b45d)
 #65 0x0000563ccf27b36b clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b36b)
 #66 0x0000563ccf27b62c clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b62c)
 #67 0x0000563ccf27b8ed clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b8ed)
 #68 0x0000563ccee9fd58 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x489fd58)
 #69 0x0000563cceec2b9b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48c2b9b)
 #70 0x0000563ccf4725bb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e725bb)
 #71 0x0000563ccf48481b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDecltypeType(clang::TypeLocBuilder&, clang::DecltypeTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8481b)
 #72 0x0000563ccf45fcec clang::Sema::SubstFunctionDeclType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, clang::CXXRecordDecl*, clang::Qualifiers, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5fcec)
 #73 0x0000563ccf4a9537 clang::TemplateDeclInstantiator::SubstFunctionType(clang::FunctionDecl*, llvm::SmallVectorImpl<clang::ParmVarDecl*>&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea9537)
 #74 0x0000563ccf4a6541 clang::TemplateDeclInstantiator::VisitCXXMethodDecl(clang::CXXMethodDecl*, clang::TemplateParameterList*, clang::TemplateDeclInstantiator::RewriteKind) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea6541)
 #75 0x0000563ccf4df1f9 void llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4edf1f9)
 #76 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #77 0x0000563ccf4afd92 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4eafd92)
 #78 0x0000563ccf3fa834 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfa834)
 #79 0x0000563ccf456f96 void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::$_2>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e56f96)
 #80 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #81 0x0000563ccf3fc253 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfc253)
 #82 0x0000563ccf26558e clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c6558e)
 #83 0x0000563ccf27b45d AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b45d)
 #84 0x0000563ccf27b36b clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b36b)
 #85 0x0000563ccf27b62c clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b62c)
 #86 0x0000563ccf27b8ed clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b8ed)
 #87 0x0000563ccee9fd58 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x489fd58)
 #88 0x0000563cceec2b9b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48c2b9b)
 #89 0x0000563ccf4725bb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e725bb)
 #90 0x0000563ccf48481b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDecltypeType(clang::TypeLocBuilder&, clang::DecltypeTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8481b)
 #91 0x0000563ccf45ee32 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ee32)
 #92 0x0000563ccf45eb55 clang::Sema::SubstType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5eb55)
 #93 0x0000563ccf49eb7d clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(clang::TypedefNameDecl*, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e9eb7d)
 #94 0x0000563ccf49fbf3 clang::TemplateDeclInstantiator::VisitTypeAliasDecl(clang::TypeAliasDecl*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e9fbf3)
 #95 0x0000563ccf462c7d clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e62c7d)
 #96 0x0000563ccf464f9b clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e64f9b)
 #97 0x0000563ccf549cf3 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f49cf3)
 #98 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
 #99 0x0000563ccf52bae4 clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2bae4)
#100 0x0000563ccf52b3b5 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2b3b5)
#101 0x0000563ccea4d3e6 clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x444d3e6)
#102 0x0000563cceeae23a clang::Sema::BuildQualifiedDeclarationNameExpr(clang::CXXScopeSpec&, clang::DeclarationNameInfo const&, bool, clang::Scope const*, clang::TypeSourceInfo**) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48ae23a)
#103 0x0000563ccf477425 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentScopeDeclRefExpr(clang::DependentScopeDeclRefExpr*, bool, clang::TypeSourceInfo**) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e77425)
#104 0x0000563ccf46640d (anonymous namespace)::TemplateInstantiator::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e6640d)
#105 0x0000563ccf481274 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e81274)
#106 0x0000563ccf48952a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8952a)
#107 0x0000563ccf486469 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformElaboratedType(clang::TypeLocBuilder&, clang::ElaboratedTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e86469)
#108 0x0000563ccf45ee32 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ee32)
#109 0x0000563ccf4623cb clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e623cb)
#110 0x0000563ccf462b08 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e62b08)
#111 0x0000563ccf464f9b clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e64f9b)
#112 0x0000563ccf549cf3 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f49cf3)
#113 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
#114 0x0000563ccf52bae4 clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2bae4)
#115 0x0000563ccf52b3b5 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2b3b5)
#116 0x0000563cced86119 clang::Sema::CheckBaseSpecifier(clang::CXXRecordDecl*, clang::SourceRange, bool, clang::AccessSpecifier, clang::TypeSourceInfo*, clang::SourceLocation) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4786119)
#117 0x0000563ccf462673 clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e62673)
#118 0x0000563ccf462b08 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e62b08)
#119 0x0000563ccf464f9b clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e64f9b)
#120 0x0000563ccf549cf3 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f49cf3)
#121 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
#122 0x0000563ccf52bae4 clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2bae4)
#123 0x0000563ccf52b3b5 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4f2b3b5)
#124 0x0000563ccea4d3e6 clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x444d3e6)
#125 0x0000563ccf33af4d clang::Sema::CheckTypenameType(clang::ElaboratedTypeKeyword, clang::SourceLocation, clang::NestedNameSpecifierLoc, clang::IdentifierInfo const&, clang::SourceLocation, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d3af4d)
#126 0x0000563ccf48269a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType(clang::TypeLocBuilder&, clang::DependentNameTypeLoc, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8269a)
#127 0x0000563ccf45ee32 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5ee32)
#128 0x0000563ccf45f840 clang::Sema::SubstType(clang::QualType, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5f840)
#129 0x0000563ccf310188 clang::Sema::CheckTemplateIdType(clang::TemplateName, clang::SourceLocation, clang::TemplateArgumentListInfo&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d10188)
#130 0x0000563ccf481988 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e81988)
#131 0x0000563ccf48952a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e8952a)
#132 0x0000563ccf486469 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformElaboratedType(clang::TypeLocBuilder&, clang::ElaboratedTypeLoc) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e86469)
#133 0x0000563ccf45fcec clang::Sema::SubstFunctionDeclType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, clang::CXXRecordDecl*, clang::Qualifiers, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e5fcec)
#134 0x0000563ccf4a9537 clang::TemplateDeclInstantiator::SubstFunctionType(clang::FunctionDecl*, llvm::SmallVectorImpl<clang::ParmVarDecl*>&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea9537)
#135 0x0000563ccf4a7b48 clang::TemplateDeclInstantiator::VisitFunctionDecl(clang::FunctionDecl*, clang::TemplateParameterList*, clang::TemplateDeclInstantiator::RewriteKind) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4ea7b48)
#136 0x0000563ccf4df1f9 void llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4edf1f9)
#137 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
#138 0x0000563ccf4afd92 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4eafd92)
#139 0x0000563ccf3fa834 clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfa834)
#140 0x0000563ccf456f96 void llvm::function_ref<void ()>::callback_fn<clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>)::$_2>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e56f96)
#141 0x0000563cce9aa46f clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x43aa46f)
#142 0x0000563ccf3fc253 clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, bool, clang::QualType, clang::Expr::Classification, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4dfc253)
#143 0x0000563ccf26558e clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c6558e)
#144 0x0000563ccf27b45d AddOverloadedCallCandidate(clang::Sema&, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b45d)
#145 0x0000563ccf27b36b clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b36b)
#146 0x0000563ccf27b62c clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b62c)
#147 0x0000563ccf27b8ed clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4c7b8ed)
#148 0x0000563ccee9fd58 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x489fd58)
#149 0x0000563cceec2b9b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x48c2b9b)
#150 0x0000563ccf4725bb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e725bb)
#151 0x0000563ccf47a7d6 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformRequiresExpr(clang::RequiresExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e7a7d6)
#152 0x0000563ccf46ccbd (anonymous namespace)::TemplateInstantiator::TransformRequiresExpr(clang::RequiresExpr*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e6ccbd)
#153 0x0000563ccf467780 clang::Sema::SubstConstraintExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4e67780)
#154 0x0000563cceb72289 calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::$_0::operator()(clang::Expr const*) const (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4572289)
#155 0x0000563cceb70f52 clang::ActionResult<clang::Expr*, true> calculateConstraintSatisfaction<calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::$_0>(clang::Sema&, clang::Expr const*, clang::ConstraintSatisfaction&, calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, clang::SourceLocation, clang::MultiLevelTemplateArgumentList const&, clang::Expr const*, clang::ConstraintSatisfaction&)::$_0&&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4570f52)
#156 0x0000563cceb6a94e CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x456a94e)
#157 0x0000563cceb6a6f6 clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::MultiLevelTemplateArgumentList const&, clang::SourceRange, clang::ConstraintSatisfaction&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x456a6f6)
#158 0x0000563ccf320c39 clang::Sema::CheckConceptTemplateId(clang::CXXScopeSpec const&, clang::SourceLocation, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::ConceptDecl*, clang::TemplateArgumentListInfo const*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d20c39)
#159 0x0000563ccf321127 clang::Sema::BuildTemplateIdExpr(clang::CXXScopeSpec const&, clang::SourceLocation, clang::LookupResult&, bool, clang::TemplateArgumentListInfo const*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4d21127)
#160 0x0000563ccee9f8e9 clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, clang::CorrectionCandidateCallback*, bool, clang::Token*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x489f8e9)
#161 0x0000563cce631216 clang::Parser::tryParseCXXIdExpression(clang::CXXScopeSpec&, bool, clang::Token&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4031216)
#162 0x0000563cce632936 clang::Parser::ParseCXXIdExpression(bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4032936)
#163 0x0000563cce622928 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4022928)
#164 0x0000563cce623584 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4023584)
#165 0x0000563cce61e0e4 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x401e0e4)
#166 0x0000563cce620b71 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4020b71)
#167 0x0000563cce61e0e4 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x401e0e4)
#168 0x0000563cce6201fa clang::Parser::ParseConstantExpressionInExprEvalContext(clang::Parser::TypeCastState) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40201fa)
#169 0x0000563cce64d3c6 clang::Parser::ParseStaticAssertDeclaration(clang::SourceLocation&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x404d3c6)
#170 0x0000563cce67591c clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x407591c)
#171 0x0000563cce6ad236 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40ad236)
#172 0x0000563cce6ac634 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40ac634)
#173 0x0000563cce6b7650 clang::Parser::ParseCompoundStatementBody(bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40b7650)
#174 0x0000563cce6b85c6 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40b85c6)
#175 0x0000563cce5fe267 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ffe267)
#176 0x0000563cce6785e5 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x40785e5)
#177 0x0000563cce5fce72 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ffce72)
#178 0x0000563cce5fc88e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ffc88e)
#179 0x0000563cce5fb99d clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ffb99d)
#180 0x0000563cce648cd6 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4048cd6)
#181 0x0000563cce64816e clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x404816e)
#182 0x0000563cce675c0f clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x4075c0f)
#183 0x0000563cce5fb254 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ffb254)
#184 0x0000563cce5f9aa7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ff9aa7)
#185 0x0000563cce5f49fe clang::ParseAST(clang::Sema&, bool, bool) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ff49fe)
#186 0x0000563cce36bd3a clang::FrontendAction::Execute() (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3d6bd3a)
#187 0x0000563cce2e56e4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3ce56e4)
#188 0x0000563ccd49b6cf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e9b6cf)
#189 0x0000563ccd490bec cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e90bec)
#190 0x0000563ccd48dc26 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e8dc26)
#191 0x0000563cce46b99e void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__u::optional<llvm::StringRef>>, std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char>>*, bool*) const::$_0>(long) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3e6b99e)
#192 0x0000563cd2670aef llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x8070aef)
#193 0x0000563cce46b17a clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__u::optional<llvm::StringRef>>, std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char>>*, bool*) const (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3e6b17a)
#194 0x0000563cce42d77d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3e2d77d)
#195 0x0000563cce42da2f clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__u::pair<int, clang::driver::Command const*>>&, bool) const (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3e2da2f)
#196 0x0000563cce44aed0 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__u::pair<int, clang::driver::Command const*>>&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x3e4aed0)
#197 0x0000563ccd48d224 clang_main(int, char**, llvm::ToolContext const&) (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e8d224)
#198 0x0000563ccd48b6f4 main (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e8b6f4)
#199 0x00007f5b788723d4 __libc_start_main (/usr/grte/v5/lib64/libc.so.6+0x613d4)
#200 0x0000563ccd48b62a _start (third_party/crosstool/v18/llvm_unstable/toolchain/bin/clang+0x2e8b62a)
clang: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version google3-trunk (1d87465a0a95cee9accc5dce7abdabbbc3f3c122)
Target: x86_64-grtev4-linux-gnu
Thread model: posix
InstalledDir: third_party/crosstool/v18/llvm_unstable/toolchain/bin
clang: note: diagnostic msg: 
```

</details>

**Comment by cor3ntin** [comment]
@sam-mccall Thanks! do you have a reduction? or at least a preprocessed source file we could reduce?

**Comment by sam-mccall** [comment]
Here's a preprocessed file: [repro.zip](https://github.com/llvm/llvm-project/files/15250584/repro.zip)

I tried to reduce, and got rid of most of the test code and some of the stdexec code, but there's still a lot left.
I hit the end of my timebox on that. Maybe creduce can do better.

**Comment by mizvekov** [comment]
> Here's a preprocessed file: [repro.zip](https://github.com/llvm/llvm-project/files/15250584/repro.zip)
> 
> I tried to reduce, and got rid of most of the test code and some of the stdexec code, but there's still a lot left. I hit the end of my timebox on that. Maybe creduce can do better.

That crashes with released clang 18.1.4 as well, same stack trace it seems.
```
Homebrew clang version 18.1.4
Target: arm64-apple-darwin23.4.0
```

Is it possible you may have reduced into a different bug?
It's always helpful in that case to keep testing with known good compiler while reducing.

**Comment by eaeltsin** [comment]
> > Thanks, guarding the second specialization with the feature test macro works.
> > I will try to reduce the test case tomorrow, if you still need this.
> 
> Thanks. If it's not too much work for you, that would be great. Otherwise, I think a pretty good guess can be made from reading the source code, but I may not be able to try until next week. If that happens and I still don't manage to reproduce it, I will ask again.

Here is my reduction - https://godbolt.org/z/Mrcafn8h6

**Comment by Endilll** [comment]
@bgra8 Your reduction has names replaced by the tool. This is quite hard to work with. Can you reduce again, but with renaming passes disabled?
I uploaded your reproducer to CE: https://godbolt.org/z/9PK1oPoPW

**Comment by Endilll** [comment]
If you're using `creduce`, this set of arguments disables all renaming passes: `--remove-pass pass_clang rename-fun --remove-pass pass_clang rename-param --remove-pass pass_clang rename-var --remove-pass pass_clang rename-class --remove-pass pass_clang rename-cxx-method --remove-pass pass_clex rename-toks`

**Comment by mizvekov** [comment]
> @mizvekov I have a [reduced test case](https://github.com/llvm/llvm-project/files/15261978/repro.zip) for the crash @sam-mccall reported.
> 
> Clang does not crash before but crashes at this revision.

Thanks. I confirm it crashes, but it crashes on clang 18.1.4 as well, if one just passes `-frelaxed-template-template-args`.
So most likely this is the same problem, we exposed it by default, but wasn't caused by changes in this patch per se.

The program became invalid with the change. The crash is most likely secondary, caused by bad error recovery.

The former is the most interesting thing here, we can try to see if it's one of the cases where we can solve with additional wording, but the reduction process might have mangled this.

Is it possible the original code already had workaround for template-template-args with GCC, but the workaround was otherwise GCC specific, not using the feature testing macro?

**Comment by sam-mccall** [comment]
This commit did three things: A) changed the implementation, B) changed the flag default, and C) deprecated the flag.

Since clang now crashes on widely-used, real-world code, can we at least revert C, and ideally B until the crashes are fixed?

(It would also have been helpful to separate A and B, automated bisection can't tell the difference between the two, and generally we'd deal with crashes in default config by reverting the whole commit)

**Comment by cor3ntin** [comment]
I don't think there is motivation to revert anything at this point (we should avoid churn), however I do agree this is a regression that we should fix quickly @mizvekov.

(Even if it's not a new bug, it is a newly exposed bug, the pain for users is the same)

If the fix takes a long time to manifest then we should consider more aggressive mitigations.

**Comment by Endilll** [comment]
It'd also be nice if someone can share a reproducer that crashes on trunk but not on 18.1.0 without names reduced to 1-2 letters. Definitely would speed up the work towards the fix.

**Comment by cor3ntin** [comment]
Having a clean reduction to decide whether the code is supposed to compile or not is indeed a good first step.

Clang 18 was not conforming and people might have relied on it.

There is a  -fno-relaxed-template-template-args that can be used as a workaround for now

**Comment by erichkeane** [comment]
I agree with @sam-mccall : I think "crashes on some widely-used real-world code" means we should revert `B` until we can make that case work.  Yes, it is a pre-existing issue, however it means that we aren't "ready" to change the flag default.

However, we DEFINITELY need a useful reproducer, and I'm OK holding off on a revert if we can get a fix in 'the next few days' timeframe.

**Comment by Endilll** [comment]
> but not having a convenient reproducer is not a good reason to keep the ToT Clang in a broken state

As someone who worked on a different reduction of Sam's reproducer yesterday, and spent whopping 8 hours of work time to get https://github.com/llvm/llvm-project/issues/91566#issuecomment-2102739179, I disagree with your framing. I don't find it acceptable to claim that you provided an actionable reproducer, when it's 400 lines of dense code that can't be reduced automatically, and have half of the names stripped.

**Comment by erichkeane** [comment]
> Can we start with either reverting the whole commit or at least removing the flag deprecation and returning the old default (`-fno-relaxed-template-template-args`)? I think, @bgra8 and @sam-mccall can try to provide a reduced test case without renaming next week (it's sort of a [long weekend](https://www.thelocal.de/20220307/german-word-of-the-day-der-bruckentag) in Germany with some folks not working), but not having a _convenient_ reproducer is not a good reason to keep the ToT Clang in a broken state.

I'd like to give @mizvekov a chance to fix this and it isn't 'work hours' in his time zone yet.  I'd like to give him time to estimate a fix before we do the code churn of a revert.  I'm also not convinced that a break in the stdexec project raises to the "ToT is broken" definition that Chromium/a few others cause.

**Comment by Endilll** [comment]
To be clear, we're asking for a reproducer with normal names first and foremost. I'm thankful for @bgra8 help running `creduce` over what they had, but we wouldn't had this particular conversation if they also provided full original reproducer that we could run `creduce` on with the settings we see fit.

**Comment by mizvekov** [comment]
I am repeating myself here, but the crash happens after a bunch of errors: it's not significant, we have evidence this sort of crash is associated with error recovery.

This patch implements a standard mandated breaking change, and this 'stdexec' is user code.
Without evidence that stdexec does something that should be accepted within reason, I don't think that's grounds for revert.

The simplest thing to look for here: Does this project already workaround the changes as they were implemented in GCC?
If so, this could be just a matter of changing a preprocessor test.

Here is what I think would be a good evidence that something is wrong with this patch: A snippet of code, extracted from 'stdexec', that works on GCC, works on official clang, but doesn't after this patch.

**Comment by mizvekov** [comment]
By the way, creduce/cvise won't help much here unless the interestingness test accounts for 'works on GCC'.

Otherwise, It'd be trivial to conjure some snippet of code that works before P0522, but breaks afterward as intended.

**Comment by cor3ntin** [comment]
We operated a partial revert here https://github.com/llvm/llvm-project/pull/91811
That should fix the issues in trunk while we investigate the regression more thoroughly

**Comment by mizvekov** [comment]
@sam-mccall @bgra8 @ericniebler I believe this MR should fix your issues: https://github.com/llvm/llvm-project/pull/91833

Can you double check?

You might consider applying https://github.com/llvm/llvm-project/pull/91837,
since that is stacked on that and will revert the default back to enabling relaxed matching by default. Otherwise, you have to compile with `-frelaxed-template-template-args`.

**Comment by sam-mccall** [comment]
@mizvekov Thank you! With that patch, clang not only doesn't crash on stdexec with `-frelaxed-template-template-args`, but in fact accepts the code.

**Comment by sam-mccall** [comment]
I'm sorry that I wasn't able to more usefully reduce the failure cases. When such regressions show up, we usually don't have any meaningful context on the code. For our own code, we have guidelines to try to limit complexity which makes reduction more tractable, but third-party libraries are harder.

For publicly-available code, it's not clear to me how much of the burden should fall on people that identify the problem.
I want to do as much of this work as I can, it's difficult to balance the urgency of providing some reproducer (it gets hard to push for a fix if we wait a week for a good reproducers), the quality of reduction, and other work/deadlines. (As mentioned, the timing was difficult this time as this landed just before a holiday).

**Comment by AaronBallman** [comment]
> For publicly-available code, it's not clear to me how much of the burden should fall on people that identify the problem. I want to do as much of this work as I can, it's difficult to balance the urgency of providing some reproducer (it gets hard to push for a fix if we wait a week for a good reproducers), the quality of reduction, and other work/deadlines. (As mentioned, the timing was difficult this time as this landed just before a holiday).

(Not talking about the revert policy, but just about reduced reproducers.)

I don't think we have (or want) hard-and-fast rules for how much of the burden falls on folks who find the issue -- we want to encourage people to report issues even if they don't have the time or ability to reduce the problem, but we also don't want to overload the community with issues that need significant reduction work. My suggestion is: initially, provide *anything* that demonstrates the issue so that folks are aware a problem exists, but with an understanding that the harder it is to reproduce (or the larger the reproducer is), the less likely it is the issue will be addressed in a timely manner. So if something is of critical importance to you, then the bar is higher for you to provide as much help as possible in getting to the point we can fix the issue on a timeline that works for you. But it's definitely a balancing act and the community should be willing to pitch in to help with reduction and mitigate fallout as much as possible (as what seems to have happened in this case).

**Comment by erichkeane** [comment]
> I'm sorry that I wasn't able to more usefully reduce the failure cases. When such regressions show up, we usually don't have any meaningful context on the code. For our own code, we have guidelines to try to limit complexity which makes reduction more tractable, but third-party libraries are harder.
> 
> For publicly-available code, it's not clear to me how much of the burden should fall on people that identify the problem. I want to do as much of this work as I can, it's difficult to balance the urgency of providing some reproducer (it gets hard to push for a fix if we wait a week for a good reproducers), the quality of reduction, and other work/deadlines. (As mentioned, the timing was difficult this time as this landed just before a holiday).

I agree here for the most part.  BUT our problem was that until we saw the reproducer from the bug report, it wasn't clear that this was a regression that required a revert.  I think that if someone is going to request a revert that they have to show that we have a regression, and not 'the patch doing what it was supposed to'.  I'll note that ~4 of us spent HOURS trying to figure this out as well, so we ALSO need to balance the work/deadlines of those trying to determine whether it is worth a revert.

For example, on this patch and a few recent ones, we've had a handful of folks bringing 'regressions' to us that were just the intent of the patch.  It was not clear in this case that the regression shown here wasn't just another case of "we diagnose something we didn't before, but that is because we wanted to".  Because it was a "crash-after-invalid", it wasn't particularly serious, particularly as it was a crash that happened with this flag before.

This is VERY different from "diagnoses improperly" (deserves a revert) and "crashes on valid" (also deserves a revert).  

In this case we actually DIDN'T get to either of the two above, but the minimal reproducer let a few of us spend a few hours figuring out that this is a C++ Core issue, depending on your interpretation of a core issue this is either valid or invalid code.  

Within a few hours of determining this was the case, we reverted to leave the 'previous' behavior until the standard is clarified.  In the end, your reproducer may very well still 'fail' (if WG21 decides that way), and wouldn't be a regression when we make that change.

TLDR; the request for a reduction was because it was associated with requests for a revert in a case it wasn't clear met the barrier for revert.

**Comment by mizvekov** [comment]
> @mizvekov Thank you! With that patch, clang not only doesn't crash on stdexec with `-frelaxed-template-template-args`, but in fact accepts the code.

Thanks! The crash is still there and is pre-existing, but it's a 'crash-on-invalid' issue, which is lower priority.

**Comment by sam-mccall** [comment]
All makes sense to me. 

I'd point out that the only revert I was asking for was asking for was of the deprecation of the flag to restore the old behavior, and *optionally* the default flip. 

The combination of {prominent oss library, accepted by clang-18 and gcc, now ICE, flag to fix is deprecated} doesn't seem tenable even if the code is invalid, so I don't think that resolving it hinged on reproducer quality.

Others requested a broader revert. I suspect this is fix-forward being bad for tree stability, and revert + partial-reapply being better in this respect. Which... well, tradeoffs.

In any case I think we lost some nuance here, I'll try to be more helpful in future!

**Comment by mizvekov** [comment]
> I'd point out that the only revert I was asking for was asking for was of the deprecation of the flag to restore the old behavior, 
> 

I missed that when I originally read your first statement.

For future reference, why was the deprecation itself a problem for you? It only means that we intend to remove the flag in the future, but it still works. It was meant to keep users informed of changes.

If deprecation by itself meant the flag was unusable for some reason, then we might as well have removed the old behavior and kept the flag as a no-op.

**Comment by sam-mccall** [comment]
The immediate deprecation causes a few issues:

- mechanical: we build with `-Wall -Werror -Wno-deprecated-declarations -Wno-deprecated-other-stuff` in part to catch driver misuse and fix it early. However this warning is not actionable, so now we need `-Wno-deprecated` which has undesirable effects and is also just changing unreasonably many things at once.
- mixed messages: there was a lot of confusion that this commit made the flag both required and deprecated. This isn't usual practice.
- scary with unclear expectations: deprecation warning means we need to migrate now, but we can't (not our code, authors probably won't take this seriously until clang-19). So our toolchain could break any day now?
- compatibility: there's no non-deprecated argv that results in the same behavior before and after this commit. What is a build system supposed to do if it can't version-lock clang? (Google actually *does* version-lock clang, this is only tangentially relevant to us because of clang-tidy, clangd etc. More relevant to others)
 
I think a good alternative would be: fix behavior + change default now in clang-19 cycle, deprecate `-fno-relaxed` flag in clang-20 cycle, remove `-fno-relaxed` and deprecate `-frelaxed` in clang-21 cycle. I believe this is more in line with what we've done in the past. Removing `-fno-relaxed` support is the real win here, and as this breaks deployed code doing that before clang-21 is probably unrealistic anyway.

---

(I forgot to mention earlier - a consequence of the crashes is that clang-tidy pipelines, clangd etc started crashing, which was disruptive to a lot of people. For clang per se it's not terribly severe to crash after emitting diagnostics, but other tools need to be able to consume real-world code and keep running, whether it's valid or not. In that sense this was more severe than a usual crash-on-invalid)

**Comment by joanahalili** [comment]
Hello @ mizvekov

We are seeing a widespread breakage due to this commit and could use having the flag `-fno-relaxed-template-template-args` un-deprecated for a while.  This would help do a cleanup on our end.

**Comment by zygoloid** [comment]
> The immediate deprecation causes a few issues

On the one hand: waiting to deprecate something that we know we're going to deprecate usually doesn't help anyone. We delay getting the message out to our users, we sometimes forget to do it for the next release, and at best it means it takes an extra release cycle to deliver whatever kind of benefit we were aiming for. So I think that we should generally start issuing deprecation warnings as soon as the new thing is ready and we know that we plan to remove the old thing.

On the other hand: a warning without a dedicated warning flag is, for some of our users, the same thing as an error. And, for some of our users, a deprecation error is the same thing as removing the feature immediately. So that doesn't work in this case :)

Would it be reasonable to add a `-Wno-deprecated-relaxed-template-template-args` flag (or something like that) for this specific deprecation?

**Comment by mizvekov** [comment]
> Would it be reasonable to add a `-Wno-deprecated-relaxed-template-template-args` flag (or something like that) for this specific deprecation?

I had similar idea, but what about instead implementing something generic to ignore deprecation of any driver flag?

**Comment by mizvekov** [comment]
Regarding @joanahalili 's post

Does it sound good for everyone that we revert the deprecation of the positive spelling of the flag for a while, until we come up with a patch for a new flag which helps ignore these deprecations?

**Comment by erichkeane** [comment]
> > Would it be reasonable to add a `-Wno-deprecated-relaxed-template-template-args` flag (or something like that) for this specific deprecation?
> 
> I had similar idea, but what about instead implementing something generic to ignore deprecation of any driver flag?

I think I prefer pretty fine-grained ones TBH, it makes our deprecation warnings more valuable.  In a perfect world, it would change every release of the compiler so that folks would be frequently reminded of it, but it isn't a perfect world :) 

> Does it sound good for everyone that we revert the deprecation of the negative spelling of the flag for a while, until we come up with a patch for a new flag which helps ignore these deprecations?

Is doing so much of a task? I would expect it to be like other diagnostics and take roughly the same amount of time as reverting the negative-spelling-deprecation.  I don't see the request to remove the deprecation (it IS just a warning afterall!) to be particularly motivating until release time (it IS just a warning afterall!), so I'd think it would a better spending of time to implement what Richard suggested.

**Comment by mizvekov** [comment]
> I think I prefer pretty fine-grained ones TBH, it makes our deprecation warnings more valuable. In a perfect world, it would change every release of the compiler so that folks would be frequently reminded of it, but it isn't a perfect world :)

I meant something fine grained, but generic, like `-Wno-deprecated-flag=-fno-relaxed-template-template-args`.
We have something similar for generic warnings.
That would probably take a little longer to get everyone onboard the design, and may lack other motivators presently.
 
> Is doing so much of a task? I would expect it to be like other diagnostics and take roughly the same amount of time as reverting the negative-spelling-deprecation. I don't see the request to remove the deprecation (it IS just a warning afterall!) to be particularly motivating until release time (it IS just a warning afterall!), so I'd think it would a better spending of time to implement what Richard suggested.

Right, it takes about the same amount of time, so we may as well implement the simple thing, and argue about something else later if someone sees motivation.

**Comment by erichkeane** [comment]
Great, I agree that is the right way forward.  A more complicated flag like that might be cool someday, but not something we need today.

**Comment by mizvekov** [comment]
@joanahalili This is now merged in main: https://github.com/llvm/llvm-project/pull/92324

You can pass `-Wno-deprecated-no-relaxed-template-template-args` to disable the deprecation warning for `-fno-relaxed-template-template-args` specifically, without affecting other warnings.

**Comment by cor3ntin** [comment]
@joanahalili 
> We are seeing a widespread breakage due to this commit and could use having the flag -fno-relaxed-template-template-args un-deprecated for a while. This would help do a cleanup on our end.

Can you provide more information? How widespread are we talking about? You have example of common breakages?
Thanks

**Comment by joanahalili** [comment]
Thank you for the quick response to this! 
I have come up with a small repro to illustrate the breakages we are encountering https://godbolt.org/z/rM518enr4. 
We have a number of cases similar to this that we are now working to fix.
Thanks!

**Comment by mizvekov** [comment]
No problem!

It looks like this example is salvageable, nothing is stopping us from just applying the same rules when deducing a template template parameter against other kinds of templates.

This shouldn't stop you from cleaning up the code, whatever rules we come up here are for salvaging old code, not necessarily to entomb these as examples of good practice.

**Comment by eaeltsin** [comment]
@mizvekov - can you please take a look at https://godbolt.org/z/ahro3vnPd ?

This is what I ended up reducing yet another `xtensor` thing that failed with too deep recursive template instantiation with relaxed argument matching and compiled okay without relaxed argument matching.

The reduced example fails somewhat differently, but it complains on `implicit instantiation of undefined template` _with_ relaxed argument matching enabled and compiles OK without...

**Comment by mizvekov** [comment]
> @mizvekov - can you please take a look at https://godbolt.org/z/ahro3vnPd ?
> The reduced example fails somewhat differently, but it complains on `implicit instantiation of undefined template` _with_ relaxed argument matching enabled and compiles OK without...

Thank you, this example does look interesting. I will try to reduce further.

**Comment by mizvekov** [comment]
@eaeltsin You example boils down to https://godbolt.org/z/axnanxP1z:
```C++
template <class> struct xtype_for_shape;
template <template <class, long> class S, class X, long N>
struct xtype_for_shape<S<X, N>> {};

template <class, bool> struct svector;
template struct xtype_for_shape<svector<int, false>>;
```
There is wide divergence between implementations on what happens during deduction, at least when NTTPs are involved.

clang picks the partial specialization, all other implementations pick the primary template.
This is not something new from this PR either.

The other implementations reject the matching in deduction, but all implementations agree that it would work if directly specified: https://godbolt.org/z/Gfs3dbYEe

(discounting EDG which doesn't seem to implement P0522R0 at all).

I think what clang does makes the most sense; I see no point in having deduction be more strict than the matching itself.

Also, you can create a similar situation with NTTPs where this adds new ambiguity: https://godbolt.org/z/cWPM7jWvd

**Comment by eaeltsin** [comment]
Thanks @mizvekov ! This explanation sheds some light on why the original tests diverge in behavior so much, will look further.

Is there a way to dump which template was picked for which instantiation?

(I tried templight but it doesn't seem to handle this case yet, for me it went in one step through the recursive instantiation that hits the depth limit).

**Comment by mizvekov** [comment]
No, I never used templight for this. I don't know of any easy to use tools that would work for a complex sample without modification.

Otherwise, the reduction wasn't difficult, it was mostly that creduce / cvise are lacking steps to reduce template type aliases, and the typedef within a class template equivalent.

There is also a seemingly complex pack expansion of a boolean expression, that you can just replace with false; cvise missed this as well.

**Comment by eaeltsin** [comment]
:( My goal now is to fix xtensor implementation/original tests, so this is not a question of reduction. I need to understand where the compiler picked a different specialization with relaxed argument matching.

**Comment by mizvekov** [comment]
> :( My goal now is to fix xtensor implementation/original tests, so this is not a question of reduction. I need to understand where the compiler picked a different specialization with relaxed argument matching.

So from the reduction you can see you have a problem where `svector` is matching a partial specialization of `xtype_for_shape`, which it shouldn't.

I see that you have a very similar problem to your first one, which is not fixed in main yet, where one of the partial specializations is ifdef'd out in a similar manner, that also very suspiciously looks like it should have been using the feature test macro instead:
https://github.com/xtensor-stack/xtensor/blob/d9c3782ed51027b2d00be3c26288b2f74e4dbe94/include/xtensor/xexpression_traits.hpp#L106

Does changing that to the feature test macro help?

**Comment by eaeltsin** [comment]
Huge thanks, @mizvekov! That was a precise guess!
