### PR TITLE
[SPIR-V] Ensure that a correct pointer type is deduced from the Value argument of OpAtomic* instructions

### LINKED ISSUE #127491: [SPIR-V] Incorrect pointer type is deduced for OpAtomic* instructions when a pointer argument is created by an `inttoptr .. to` instruction
A GPUToLLVMSPV user of the SPIR-V backend reports about a case when incorrect pointer type is deduced for OpAtomic* instructions. The reproducer is

```
define dso_local spir_func void @test4(i64 noundef %arg, float %val) local_unnamed_addr {
entry:
  %ptr1 = inttoptr i64 %arg to ptr addrspace(1)
  %v1 = atomicrmw fadd ptr addrspace(1) %ptr1, float %val seq_cst, align 4
  ret void
}
```

while triaging shows that the problem may be also reproduced for a wider set of instructions and SPIR-V op-codes, for example:

```
define dso_local spir_func void @test4(i64 noundef %arg, float %val) local_unnamed_addr {
entry:
  %ptr1 = inttoptr i64 %arg to ptr addrspace(1)
  %v1 = atomicrmw fadd ptr addrspace(1) %ptr1, float %val seq_cst, align 4
  %ptr2 = inttoptr i64 %arg to float addrspace(1)*
  %v2 = atomicrmw fsub ptr addrspace(1) %ptr2, float %val seq_cst, align 4
  %ptr3 = inttoptr i64 %arg to float addrspace(1)*
  %v3 = tail call spir_func float @_Z21__spirv_AtomicFAddEXT(ptr addrspace(1) %ptr3, i32 1, i32 16, float %val)
  %ptr4 = inttoptr i64 %arg to float addrspace(1)*
  %v4 = tail call spir_func float @_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order(ptr addrspace(1) %ptr4, float %val, i32 0)
  %ptr5 = inttoptr i64 %arg to float addrspace(1)*
  %v5 = tail call spir_func float @_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicff12memory_order(ptr addrspace(1) %ptr5, float %val, i32 0)
  ret void
}

declare dso_local spir_func float @_Z21__spirv_AtomicFAddEXT(ptr addrspace(1), i32, i32, float)
declare spir_func float @_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order(ptr addrspace(1), float, i32)
declare spir_func float @_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicff12memory_order(ptr addrspace(1), float, i32)
```

and also for OpAtomicLoad/OpAtomicStore:

```
define spir_func void @test_types1(ptr addrspace(1) %ptr, float %val) {
entry:
  %r = call spir_func float @atomic_load(ptr addrspace(1) %ptr)
  ret void
}

define spir_func void @test_types2(ptr addrspace(1) %ptr, float %val) {
entry:
  call spir_func void @atomic_store(ptr addrspace(1) %ptr, float %val)
  ret void
}

define spir_func void @test_types3(i64 noundef %arg, float %val) {
entry:
  %ptr1 = inttoptr i64 %arg to float addrspace(1)*
  %r = call spir_func float @atomic_load(ptr addrspace(1) %ptr1)
  ret void
}

define spir_func void @test_types4(i64 noundef %arg, float %val) {
entry:
  %ptr2 = inttoptr i64 %arg to float addrspace(1)*
  call spir_func void @atomic_store(ptr addrspace(1) %ptr2, float %val)
  ret void
}

declare spir_func float @atomic_load(ptr addrspace(1))
declare spir_func void @atomic_store(ptr addrspace(1), float)
```

Incorrect pointer type is deduced for OpAtomic* instructions when a pointer argument is created by an `inttoptr .. to` instruction, with a root cause is that information about pointee type is ignored unless this argument is a pointer as well. A solution could be to account for a pointee type using the Value argument type of the corresponding LLVM IR instruction/SPIR-V op-code, depending on the context of the case.

### PR DESCRIPTION
**Pull request by VyacheslavLevytskyy**
This PR improves the set of rules for type inference by ensuring that a correct pointer type is deduced from the Value argument of OpAtomic* instructions, also when a pointer argument is coming from an `inttoptr .. to` instruction that caused problems earlier. Existing test cases are updated accordingly. This fixes https://github.com/llvm/llvm-project/issues/127491

### CODE REVIEW

File: llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp [hunk 1]
```diff
@@ -182,7 +182,7 @@ class SPIRVEmitIntrinsics
 
   bool deduceOperandElementTypeCalledFunction(
       CallInst *CI, SmallVector<std::pair<Value *, unsigned>> &Ops,
-      Type *&KnownElemTy);
+      Type *&KnownElemTy, bool &Uncomplete);
```
Comment (MrSidims) [inline llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp:185]: nitpick (probably?): the name implies the procedure that `deduceOperandElementTypeCalledFunction` does can be canceled or postponed. Is it the case?

File: llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp [hunk 2]
```diff
@@ -934,9 +937,23 @@ bool SPIRVEmitIntrinsics::deduceOperandElementTypeCalledFunction(
...
+      case SPIRV::OpAtomicStore: {
+        if (CI->arg_size() < 4)
+          return true;
+        Value *ValOp = CI->getArgOperand(3);
+        KnownElemTy = isPointerTy(ValOp->getType())
+                          ? getAtomicElemTy(GR, CI, Op)
+                          : ValOp->getType();
+        if (!KnownElemTy)
+          return true;
+        Uncomplete = isTodoType(Op);
```
Comment (MrSidims) [inline llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp:956]: ... so if the idea to set that the type is TBD, then parameter should be name `Incomplete` (and please accept my apologies for such nitpicking :) )

Also, I don't see `Un/Incomplete` variable to be really used in the code (originally based on the name I though there would be
```
 if (Uncomplete) {
 /* store something and do early exit */
 }
```

but seems like it's added as a function parameter just to silence the warning of the unused return from `isTodoType`, or am I missing something?

Comment (VyacheslavLevytskyy) [reply llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp:956]: It's the same patter as we see in deduceOperandElementType() - this variable means that a related pointer has the default type (i8) assigned rather than a deduced one, and we may change the type if we get a better type. It's in use actually, please see

```
      if (!Uncomplete)
        eraseTodoType(Op);
```

below the call to deduceOperandElementTypeCalledFunction().

**Review by MrSidims — APPROVED** [review]
