### PR TITLE
[AArch64][TTI] Improve `LegalVF` when computing gather-loads cost

### LINKED ISSUE #68953: [SLPVectorizer][AArch64][SVE] Opt crashed when optimizing
Clang crashed when compiling `flang/lib/Evaluate/intrinsics-library.cpp` after #67275 in [clang-aarch64-sve-vls-2stage1](https://lab.llvm.org/buildbot/#/builders/176/builds/5474).
After reproducing and reducing, I get the IR causing crash: [aarch-sve-crash.ll](https://gist.github.com/XChy/4cb02b756de70d807440aaa88dbeeab3).

I'm not a expert in backend. So I try `opt -S -O3 -vectorize-slp -vectorize-loops`, and it performed well.
But when I tried `opt -S -O3 -vectorize-loops -vectorize-slp -mtriple aarch64-unknown-linux-gnu --mcpu=neoverse-512tvb`, it crashed and reported "Not a vector MVT!"

It seems to be a backend/target bug.

### PR DESCRIPTION
**Pull request by antoniofrighetto**
After determining the cost of loads that could not be coalesced into `VectorizedLoads`, computing the cost of a gather-vectorized load is carried out. Take into account the case where the type of a group of loads, whose type is a vector of size dependent upon `VF`, may be legalized into a scalar value. 

Current number of loads is held in `LT.first`.

Fixes: https://github.com/llvm/llvm-project/issues/68953.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp [hunk 1]
```diff
@@ -2989,7 +2989,14 @@ InstructionCost AArch64TTIImpl::getGatherScatterOpCost(
...
 
-  ElementCount LegalVF = LT.second.getVectorElementCount();
+  ElementCount LegalVF;
+  if (LT.second.isVector()) {
+    LegalVF = LT.second.getVectorElementCount();
+  } else {
+    // If the legalized type is a simple type, treat it as a 1-element vector.
+    LegalVF = ElementCount::getFixed(1);
+  }
+
```
Comment (alexey-bataev) [inline llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp:2999]: Shall isLegalMaskedGather() just return false for such types instead?

Comment (alexey-bataev) [reply llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp:2999]: If thу vector type gets scalarized (like in your check), isLegalMaskedGather() shall return false for such types, even though useNeonVector() returns true. SLP shall not assume emitting masked gather here at all, the scalarization increases the cost significantly, we should end up with the simple gather here

File: llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp [hunk 2]
```diff
@@ -2989,7 +2989,14 @@ InstructionCost AArch64TTIImpl::getGatherScatterOpCost(
       ElementCount::getScalable(1))
```
[the remark this answers is not in the document]
Comment (antoniofrighetto) [reply llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp:2989]: If we bail out when `isLegalMaskedGather` returns false, which indeed would happen with such types, – as per @alexey-bataev suggestion above – I don't think we would ever be reaching this point.

[the remark this answers is not in the document]
Comment (davemgreen) [reply llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp:2989]: It didn't look like that function was called when I tried it, and it is best if these functions work correctly in isolation. It's possible to call it throught the cost model: https://godbolt.org/z/z4635vodq.

I think that because the gather will not become a scalable SVE gather in this case, the line above with useNeonVector should be returning true so we use the BaseT::getGatherScatterOpCost for the cost.

File: llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp [hunk 3]
```diff
@@ -2996,6 +2996,9 @@ static unsigned getSVEGatherScatterOverhead(unsigned Opcode) {
 InstructionCost AArch64TTIImpl::getGatherScatterOpCost(
     unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask,
     Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I) {
+  if (!isLegalMaskedGatherScatter(DataTy))
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp:2999]: This doesn't sound right - to return an invalid cost. If the gather/scatter can be scalarized then it should have some cost, even if it's quite high. There are some scalable vectors that can't be scalarized, but in general for fixed-width it should be OK.

Is the isElementTypeLegalForScalableVector check below enough to fix the issues you were seeing? We should probably have some fixed-length cost checks too.

If not, I think doing this would make sense, so that it returned the base cost:
```
if (useNeonVector(DataTy) || !isLegalMaskedGatherScatter(DataTy))
  return BaseT::getGatherScatterOpCost(...)
```

Comment (antoniofrighetto) [reply llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp]: Thought we wanted to favour an invalid cost in those cases, but makes sense. I confirm `isElementTypeLegalForScalableVector` is fixing the issues previously seen.

**Review by davemgreen — APPROVED** [review]
Thanks, this LGTM.  Thanks for the fix!
