### PR TITLE
Fix false positive of [[clang::require_explicit_initialization]] on copy/move constructors

### LINKED ISSUE #126490: false positive of [[clang::require_field_initialization]]
https://godbolt.org/z/eaG1e7ojY

```
struct Foo {
  int x;
  int y [[clang::require_explicit_initialization]];
};

struct Bar {
  Bar(Foo foo) : foo_(foo) {} // Field in 'Foo' requires explicit initialization but is not explicitly initialized

  Foo foo_;
};
```

This is caused by the https://github.com/llvm/llvm-project/commit/20fd7df0b847bb46aac2f0b5b71d242220027cbc

cc @higher-performance

### PR DESCRIPTION
**Pull request by higher-performance**
Fixes #126490

### CODE REVIEW

File: clang/test/SemaCXX/uninitialized.cpp [hunk 1]
```diff
@@ -1582,7 +1582,21 @@ void aggregate() {
       F("___"),
       F("____")
   };
-  (void)ctors;
+
+  struct Copy {
+    Embed e;
+    EmbedDerived ed;
+    F f;
+    Copy(const Copy &c) : e(c.e), ed(c.ed), f(c.f) {} // no-error
```
Comment (AaronBallman) [inline clang/test/SemaCXX/uninitialized.cpp:1590]: Can you add test coverage for a move constructor as well?

**Review by AaronBallman — APPROVED** [review]
LGTM, but waiting for @hokein to have a chance to approve as well.

**Review by alexfh — APPROVED** [review]
I verified all compilations failures related to #126490 we found so far, and they are all fixed by this PR. Thanks!

**Comment by metaflow** [comment]
thank you!

File: clang/lib/Sema/SemaInit.cpp [hunk 2]
```diff
@@ -4576,7 +4576,9 @@ static void TryConstructorInitialization(Sema &S,
     if (!IsListInit &&
```
Comment (hokein) [inline clang/lib/Sema/SemaInit.cpp:4576]: nit: I think this if condition is becoming complex enough that it's worth adding a comment for explanation.

**Review by hokein — COMMENTED** [review]
Thanks for the quick fix.

**Comment by AaronBallman** [comment]
> Oh - @AaronBallman would you mind tagging this for the release so we can cherry pick?

Sure!
