### PR TITLE
[clang] Use different memory layout type for _BitInt(N) in LLVM IR

### LINKED ISSUE #83419: clang: Assertion fail for simple _Bitint code
Given this source code:

```c
void f()
{
	static _BitInt(130) p = {}; 
}
```

then recent clang trunk does this:

```console
$ clang -c bug38.c
clang: /home/dcb38/llvm/trunk/clang/lib/CodeGen/CGDecl.cpp:366: llvm::GlobalVariable* clang::CodeGen::CodeGenFunction::AddInitializerToStaticVarDecl(const clang
::VarDecl&, llvm::GlobalVariable*): Assertion `VarSize == CstSize && "Emitted constant has unexpected size"' failed.
```
A slightly smaller size of 120 seems to work ok. It looks like the
boundary size is likely to be 128 or so.

If this is a fixed boundary, a tidy "not implemented" error message 
is better than an assertion fail and a crash.

### LINKED ISSUE #85139: Deduced _BitInt type with certain values causes assert in EmitGlobalVarDefinition
I found this messing around with _BitInt

https://godbolt.org/z/d6EYahK85
```
auto x = static_cast<_BitInt(257)>(0);
```

See stack trace below.  It seems that the static_cast of SOMETHING (or the result of the expression on the RHS?) PLUS a deduced type is required.  ALSO the value of the size of the `_BitInt` doesn't have an obvious pattern.  All values sub-129 seem valid, but 255 and 256 are both valid (so its not a power-of-2 thing?).  It seems any value 193-256 is valid as well (only spot checked).

I haven't mapped out ALL the values, but it seems a little odd where the holes are.  

```
clang++: /root/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:5294: void clang::CodeGen::CodeGenModule::EmitGlobalVarDefinition(const clang::VarDecl*, bool): Assertion `VarSize == CstSize && "Emitted constant has unexpected size"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -Wall <source>
1.	<eof> parser at end of file
2.	<source>:3:6: LLVM IR generation of declaration 'x'
3.	<source>:3:6: Generating code for declaration 'x'
 #0 0x00000000038fc108 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x38fc108)
 #1 0x00000000038f9dec llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x38f9dec)
 #2 0x0000000003841908 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007ffaa8c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007ffaa8c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007ffaa8c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007ffaa8c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007ffaa8c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007ffaa8c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000003cd4204 clang::CodeGen::CodeGenModule::EmitGlobalVarDefinition(clang::VarDecl const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cd4204)
#10 0x0000000003cf53a1 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cf53a1)
#11 0x0000000003cf5a33 clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3cf5a33)
#12 0x0000000003cff94b clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#13 0x0000000004195ce6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#14 0x00000000041866e8 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41866e8)
#15 0x00000000061758ec clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x61758ec)
#16 0x0000000004193908 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4193908)
#17 0x000000000440efc9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x440efc9)
#18 0x000000000438c6fe clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x438c6fe)
#19 0x00000000044f199e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44f199e)
#20 0x0000000000c27226 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc27226)
#21 0x0000000000c1ef8a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#22 0x00000000041d5099 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#23 0x0000000003841db4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3841db4)
#24 0x00000000041d568f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#25 0x000000000419d195 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x419d195)
#26 0x000000000419dbfd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x419dbfd)
#27 0x00000000041a5b35 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41a5b35)
#28 0x0000000000c2470d clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc2470d)
#29 0x0000000000b198e4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb198e4)
#30 0x00007ffaa8c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#31 0x00007ffaa8c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#32 0x0000000000c1ea4e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc1ea4e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by Fznamznon**
There are two problems with _BitInt prior to this patch:
1. For at least some values of N, we cannot use LLVM's iN for the type of struct elements, array elements, allocas, global variables, and so on, because the LLVM layout for that type does not match the high-level layout of _BitInt(N).
Example: Currently for i128:128 targets correct implementation is possible either for __int128 or for  _BitInt(129+) with lowering to iN, but not both, since we have now correct implementation of __int128 in place after a21abc7.
When this happens, opaque [M x i8] types used, where M = sizeof(_BitInt(N)).
2. LLVM doesn't guarantee any particular extension behavior for integer types that aren't a multiple of 8. For this reason, all _BitInt types are now have in-memory representation that is a whole number of bytes. I.e. for example _BitInt(17) now will have memory layout type i32.

This patch also introduces concept of load/store type and adds an API to CodeGenTypes that returns the IR type that should be used for load and store operations. This is particularly useful for the case when a _BitInt ends up having array of bytes as memory layout type.  For _BitInt(N), let M = sizeof(_BitInt(N)), and let BITS = M * 8. Loads and stores of iM would both (1) produce far better code from the backends and (2) be far more optimizable by IR passes than loads and stores of [M x i8].

Fixes https://github.com/llvm/llvm-project/issues/85139
Fixes https://github.com/llvm/llvm-project/issues/83419

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
This is unfortunate, and will likely result in the FPGAs needing to generate extra bits here, so this is somewhat harmful in that regard.

It seems to me this is a case where we're trying to work -around an llvm bug?  Should we just be fixing that instead?

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 1]
```diff
@@ -1774,6 +1774,18 @@ llvm::Constant *ConstantEmitter::emitForMemory(CodeGenModule &CGM,
     return Res;
   }
 
+  if (const auto *BIT = destType->getAs<BitIntType>()) {
+    if (BIT->getNumBits() > 128) {
+      // Long _BitInt has array of bytes as in-memory type.
+      ConstantAggregateBuilder Builder(CGM);
+      llvm::Type *DesiredTy = CGM.getTypes().ConvertTypeForMem(destType);
+      auto *CI = cast<llvm::ConstantInt>(C);
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprConstant.cpp:1782]: I'm not sure this cast is guaranteed to succeed?  At least in some cases, we emit constant expressions involving a ptrtoint.  Maybe at the widths in question, that can't happen, but this deserves a comment explaining what's going on.

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 2]
```diff
@@ -5348,6 +5348,13 @@ Value *ScalarExprEmitter::VisitVAArgExpr(VAArgExpr *VE) {
     return llvm::UndefValue::get(ArgTy);
   }
 
+  if (const auto *BIT = Ty->getAs<BitIntType>()) {
+    if (BIT->getNumBits() > 128) {
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprScalar.cpp:5352]: This seems a little fragile; specifically for _BitInt, we assume the pointer is wrong and the return type is right, but in other cases, we assume the pointer is right and we need to do some sort of conversion.

Can we fix the interface of EmitVAArg so we can just EmitLoadOfScalar() here?

**Review by efriedma-quic — COMMENTED** [review]
Maybe add a helper somewhere to check "is this type a bitint wider than 128 bits"?

**Comment by efriedma-quic** [comment]
> It seems to me this is a case where we're trying to work -around an llvm bug? Should we just be fixing that instead?

You mean, revert https://reviews.llvm.org/D86310 ?  Making any changes in LLVM here is painful; I'd rather not revisit that.  CC @hvdijk @rnk

**Comment by erichkeane** [comment]
> > It seems to me this is a case where we're trying to work -around an llvm bug? Should we just be fixing that instead?
> 
> You mean, revert https://reviews.llvm.org/D86310 ? Making any changes in LLVM here is painful; I'd rather not revisit that. CC @hvdijk @rnk

I didn't, no, but I hadn't seen all that conversation.

Aaron has explained a bit more of the context here, and I'm finding myself pretty confused/out of the loop.  As this is effectively all codegen, I suspect you, plus your CCs are the best ones to review this.  I don't see a problem except for the FPGA folks to this, though between:

1- FPGA folks rarely/ever use large types like this if they can help it.
2- The FPGA group being spun off from Intel, meaning the original stakeholders are all gone
and 3- Me no longer being at Intel 

I don't think I have strong feelings here.

**Comment by efriedma-quic** [comment]
I don't think FPGA folks will run into any practical issue with this; this only impacts the in-memory types, and backends shouldn't really be using in-memory types for anything anyways.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 3]
```diff
@@ -1989,6 +1989,14 @@ llvm::Value *CodeGenFunction::EmitLoadOfScalar(Address Addr, bool Volatile,
     return EmitAtomicLoad(AtomicLValue, Loc).getScalarVal();
   }
 
+  if (const auto *BIT = Ty->getAs<BitIntType>()) {
+    if (BIT->getNumBits() > 128) {
```
Comment (hvdijk) [inline clang/lib/CodeGen/CGExpr.cpp:1993]: For a number of bits >64, <=128, LLVM's `iN` type will have identical representation to Clang `_BitInt(N)` but different alignment. I think this is fine, I think nothing needs their alignment to match Clang's, but could you double-check to make sure you agree?

**Comment by hvdijk** [comment]
Thanks for doing this, it's unfortunate that Clang is in a rather broken state with these types right now and it will be good to see improvement. I think the approach you're taking here is the only approach that will work.

**Comment by rnk** [comment]
I played with the idea of using LLVM packed structs (`<{ i129 }>`) to represent something like this, but they don't work the way I expected them to do: https://godbolt.org/z/M6hMYYhax

LLVM DataLayout's idea of `sizeof(i129)` is still rounded up from 17 bytes to 32 bytes.

Using byte arrays for the in-memory type should work, so it's probably the best path forward.

**Comment by rjmccall** [comment]
Hmm.  I think this is actually pretty different from the `bool` pattern.  Suppose we're talking about `_BitInt(N)`.  Let `BYTES := ceil(N/8)`, and let `BITS := BYTES * 8`.

The problem being presented here is this:

1. For at least some values of `N`, we cannot use LLVM's `iN` for the type of struct elements, array elements, `alloca`s, global variables, and so on, because the LLVM layout for that type does not match the high-level layout of `_BitInt(N)`.  The only available type that does match the layout appears to be `[BYTES x i8]`.

However, it doesn't follow from the need to use `[BYTES x i8]` for memory layout that we have to use `[BYTES x i8]` for loads and stores.  IIUC, loads and stores of both `iN` and `iBITS` are in fact required to only touch `BYTES` bytes and so should be valid.  It is near-certain that loads and stores of either of those types would both (1) produce far better code from the backends and (2) be far more optimizable by IR passes than loads and stores of `[BYTES x i8]`.

`bool` does run into (1) because of targets like PPC where `sizeof(bool) == 4`.  However, we still use `i8` as the in-memory type for `bool` on other targets.  Partly, this is to discourage portability bugs where people write IR-gen code that doesn't handle the PPC pattern.  But IIRC the main reason is actually to solve this other problem:

2. LLVM doesn't guarantee any particular extension behavior for integer types that aren't a multiple of 8, but ABIs do generally require objects of type `bool` to have all bits valid.

I expect that problem (2) also applies to `_BitInt`.  The upshot is that I think we need to emit code like this:

```
  %alloca = alloca [12 x i8]
  %storedv = zext i129 %v to i136 
  store i136 %storedv, ptr %alloca
```

**Comment by rjmccall** [comment]
If you want to do things that way, you will need to (1) generalize CodeGenTypes with a new API that will return this load/store type when applicable and (2) look at all the places we call `ConvertTypeForMem`, `EmitToMemory`, and `EmitFromMemory` to make sure they do the right things.

**Comment by efriedma-quic** [comment]
You're suggesting we should fork ConvertTypeForMem into two functions?  So there's actually three types: the "register" type, the "load/store" type, and the "in-memory" type.  I guess that makes sense from a theoretical perspective, but... as a practical matter, I'm not sure how many places need to call the proposed "ConvertTypeForLoadStore".

In EmitLoadOfScalar(), instead of checking for BitInt, you just unconditionally do `Addr = Addr.withElementType(ConvertTypeForLoadStore(Ty));`.  Logical cleanup, I guess.  In EmitStoreOfScalar, you don't really need the interface because you can assume the result of EmitToMemory() has the load/store type.  And then... what else calls it?

**Comment by rjmccall** [comment]
My experience is that compiler writers are really good at hacking in special cases to make their test cases work and really bad at recognizing that their case isn't as special as they think.  There are three types already called out for special treatment in `ConvertTypeForMem`, of which two are handled in `EmitFromMemory` and only one is handled in `EmitToMemory`.  I want to set up a pattern that the next person with this sort of problem can follow.

**Comment by Fznamznon** [comment]
Thank you everyone for the feedback. I'm working on applying.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 4]
```diff
@@ -1989,6 +1989,14 @@ llvm::Value *CodeGenFunction::EmitLoadOfScalar(Address Addr, bool Volatile,
...
+      // Long _BitInt has array of bytes as in-memory type.
+      llvm::Type *NewTy = ConvertType(Ty);
```
Comment (momchil-velikov) [inline clang/lib/CodeGen/CGExpr.cpp:1995]: Shouldn't we call calling `ConvertTypeForMem` here?

Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp:1995]: The idea was to load not array, but iN, so ConverType here was intentional. However I'm updating this patch soon, it will be using special load/store type whose idea is described by https://github.com/llvm/llvm-project/pull/91364#issuecomment-2099351151 .

Comment (momchil-velikov) [reply clang/lib/CodeGen/CGExpr.cpp:1995]: Oh, I see. It looks close to what we are trying to do with https://github.com/llvm/llvm-project/pull/93495, which is:
* create in-memory representations according to the target ABI
* improve efficiency of loads/stores, e.g. load/store of `i18` in LLVM must touch just 3 bytes, so a compiler would emit one 16-bit load and one 8-bit load, but if `i18` comes from `_BitInt(18)` then a single 32-bit load would work better.

Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp]: This patch was mostly intended to fix codegen issues when it comes to big _BitInt types (>128 for 64bit targets), however I'm adding new idea of load/store type, so that seems close.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 1 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp:1796]: I've added a comment. I'm not able to get a ptrtoint in a constant expression involving a big _BitInt.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 3 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp]: These types remain unchanged.

**Comment by Fznamznon** [comment]
Well, I hope I got the idea right, I updated PR so now it is introducing `convertTypeForLoadStore` API, returning `iBITS` (Let `BYTES := sizeof(_BitInt(N))`, and let `BITS := BYTES * 8`).
I've also tried to inspect as many places where `ConvertTypeForMem`, `emitToMemory`, emitFromMemory` are used and actually found a couple of places that original patch broke.

File: clang/lib/CodeGen/CGStmt.cpp [hunk 5]
```diff
@@ -1533,9 +1533,17 @@ void CodeGenFunction::EmitReturnStmt(const ReturnStmt &S) {
     Builder.CreateStore(Result.getScalarVal(), ReturnValue);
   } else {
     switch (getEvaluationKind(RV->getType())) {
-    case TEK_Scalar:
-      Builder.CreateStore(EmitScalarExpr(RV), ReturnValue);
-      break;
+    case TEK_Scalar: {
+      llvm::Value *Ret = EmitScalarExpr(RV);
+      // EmitStoreOfScalar could be used here, but it extends bool which for
+      // some targets is returned as i1 zeroext.
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGStmt.cpp:1539]: For the sake of consistency, I'd prefer to use EmitStoreOfScalar here, even if that means we have to change more code elsewhere (presumably to use EmitLoadOfScalar).

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 6]
```diff
@@ -436,9 +436,9 @@ class ScalarExprEmitter
 
     if (Value *Result = ConstantEmitter(CGF).tryEmitConstantExpr(E)) {
       if (E->isGLValue())
-        return CGF.Builder.CreateLoad(Address(
-            Result, CGF.ConvertTypeForMem(E->getType()),
-            CGF.getContext().getTypeAlignInChars(E->getType())));
+        return CGF.Builder.CreateLoad(
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprScalar.cpp:439]: EmitLoadOfScalar?

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 7]
```diff
@@ -761,6 +761,10 @@ bool ConstStructBuilder::Build(const InitListExpr *ILE, bool AllowOverwrite) {
       if (Field->hasAttr<NoUniqueAddressAttr>())
         AllowOverwrite = true;
     } else {
+      llvm::Type *LoadType = CGM.getTypes().convertTypeForLoadStore(
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprConstant.cpp:764]: I have no idea what this is supposed to do; why don't we want to use the "memory" type here?

File: clang/lib/CodeGen/CodeGenTypes.h [hunk 8]
```diff
@@ -128,6 +128,15 @@ class CodeGenTypes {
   /// memory representation is usually i8 or i32, depending on the target.
   llvm::Type *ConvertTypeForMem(QualType T, bool ForBitField = false);
 
+  /// Check that size and abi alignment of given LLVM type matches size and
+  /// alignment of given AST type.
+  bool LLVMTypeLayoutMatchesAST(QualType ASTTy, llvm::Type *LLVMTy);
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CodeGenTypes.h:133]: I'm not sure we should be exposing LLVMTypeLayoutMatchesAST as a public API?  If any code cares, it's probably not calling ToMemory/FromMemory like it should.

File: clang/test/OpenMP/distribute_parallel_for_simd_if_codegen.cpp [hunk 9]
```diff
@@ -2567,16 +2567,16 @@ int main() {
 // CHECK3-NEXT:    [[I:%.*]] = alloca i32, align 4
 // CHECK3-NEXT:    [[DOTCAPTURE_EXPR__CASTED:%.*]] = alloca i64, align 8
 // CHECK3-NEXT:    [[DOTBOUND_ZERO_ADDR:%.*]] = alloca i32, align 4
-// CHECK3-NEXT:    [[DOTCAPTURE_EXPR__CASTED12:%.*]] = alloca i64, align 8
```
Comment (efriedma-quic) [inline clang/test/OpenMP/distribute_parallel_for_simd_if_codegen.cpp:2570]: Please regenerate the OpenMP tests in a separate pull request, to reduce the number of irrelevant changes.

File: clang/lib/CodeGen/CGStmt.cpp (hunk 5 above)
Comment (rjmccall) [reply clang/lib/CodeGen/CGStmt.cpp:1539]: Well, we don't normally have to expose the address of `ReturnValue` with scalar results, so we *could* avoid unnecessary promotions/truncations here in common cases by just making `ReturnValue` be an alloca of the scalar type instead of the for-memory type.  However, that would add complexity for the one case where `ReturnValue` *is* exposed, which is when the ABI requires the function to return indirectly; in that case, it would be important that we promote the return value before initializing the return value slot.  So there's a trade-off here: we can unconditionally treat `ReturnValue` as having the for-memory type (at the cost of emitting some extra promotions/truncations), or we can track whether we were passed it vs. just allocated internally to this function (at the cost of compiler complexity around most uses of `ReturnValue`, which is a relatively small amount of code).

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 10]
```diff
@@ -5348,18 +5348,8 @@ Value *ScalarExprEmitter::VisitVAArgExpr(VAArgExpr *VE) {
...
-  if (ArgTy != Val->getType()) {
-    if (ArgTy->isPointerTy() && !Val->getType()->isPointerTy())
-      Val = Builder.CreateIntToPtr(Val, ArgTy);
-    else
-      Val = Builder.CreateTrunc(Val, ArgTy);
-  }
-
-  return Val;
+  return CGF.EmitLoadOfScalar(ArgPtr, Ty.isVolatileQualified(), Ty,
+                              VE->getExprLoc());
```
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprScalar.cpp:5352]: > That seems like it'd be wrong on big-endian targets if the variadic argument was promoted.

I don't think we actually depend on this behavior anymore; we either adjust the pointer to point to the correct bytes, or store the value in a temporary.

[the remark this answers is not in the document]
Comment (rjmccall) [reply clang/lib/CodeGen/CGExprScalar.cpp:5352]: Should we just make `EmitVAArg` return an `RValue`?  Sema appears to unconditionally consider it a pr-value, so while CodeGen has an l-value path for it, that's probably dead.

[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprScalar.cpp:5352]: > Should we just make EmitVAArg return an RValue?

You mean, using the same signature as EmitAnyExpr?  That should work, sure.

> while CodeGen has an l-value path for it, that's probably dead.

I think we end up using EmitVAArgExprLValue in C, for something like `va_arg(x, struct X).x`.  But that's not a real lvalue; it's just a temporary.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 11]
```diff
@@ -2012,26 +2015,27 @@ llvm::Value *CodeGenFunction::EmitLoadOfScalar(Address Addr, bool Volatile,
...
-  // Bool has a different representation in memory than in registers.
-  if (hasBooleanRepresentation(Ty)) {
-    // This should really always be an i1, but sometimes it's already
-    // an i8, and it's awkward to track those cases down.
-    if (Value->getType()->isIntegerTy(1))
-      return Builder.CreateZExt(Value, ConvertTypeForMem(Ty), "frombool");
-    assert(Value->getType()->isIntegerTy(getContext().getTypeSize(Ty)) &&
-           "wrong value rep of bool");
+  if (hasBooleanRepresentation(Ty) ||
+      (Ty->isBitIntType() && Value->getType()->isIntegerTy())) {
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp:2019]: `_BitInt` that now has an array of bytes as memory type,  is returned from a function via sret(memory type) parameter. Additionally in `EmitFunctionEpilog` there is a load and a store (demo of these load an store https://godbolt.org/z/K37j4f1jn) of return value emitted that has memory type. 

Same for bool, though its memory type is not an array. I suppose there can be more cases, see comment that used to be on lines 2017-2018
```
    // This should really always be an i1, but sometimes it's already
    // an i8, and it's awkward to track those cases down.
```

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 7 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp:764]: In `ConstantEmitter::emitForMemory` we now split constant into individual bytes if the target type is a long `_BitInt`. However after an integer constant expected by `AppendBitField`, so this just folds individual bytes back to an integer.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 12]
```diff
@@ -1774,6 +1784,22 @@ llvm::Constant *ConstantEmitter::emitForMemory(CodeGenModule &CGM,
...
+      // So, split constant into individual bytes.
+      ConstantAggregateBuilder Builder(CGM);
+      llvm::Type *DesiredTy = CGM.getTypes().ConvertTypeForMem(destType);
+      // LLVM type doesn't match AST type only for big enough _BitInts, these
+      // types don't appear in constant expressions involving ptrtoint, so it
+      // is safe to expect a constant int here.
+      auto *CI = cast<llvm::ConstantInt>(C);
+      llvm::APInt Value = CI->getValue();
+      Builder.addBits(Value, /*OffsetInBits=*/0, /*AllowOverwrite=*/false);
+      return Builder.build(DesiredTy, /*AllowOversized*/ false);
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp:1799]: I'm not seeing `undef`s in resulting constants. `zeroinitializer` for all unused bytes is emitted instead. The test CodeGen/ext-int.c illustrates this behavior.

File: clang/test/OpenMP/distribute_parallel_for_simd_if_codegen.cpp (hunk 9 above)
Comment (Fznamznon) [reply clang/test/OpenMP/distribute_parallel_for_simd_if_codegen.cpp:2570]: They failed due to the change that generalized handling of `bool` and `_BitInt` in `EmitToMemory`/`EmitFromMemory`. I will need to revert that change then.

Comment (efriedma-quic) [reply clang/test/OpenMP/distribute_parallel_for_simd_if_codegen.cpp:2570]: It looked like some of the changes weren't related... if they're all in fact related, it's fine, I guess.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 7 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprConstant.cpp:764]: Oh, I see... please move the duplicated code into the implementation of AppendBitField, and add a comment explaining it.

File: clang/lib/CodeGen/CGExprScalar.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprScalar.cpp:5352]: Do you mean I should apply `RValue::get()` in `CodeGenFunction::EmitVAArg`? And all the callers of `EmitVAAArg` therefore should do `getScalarVal()` or similar to get a `llvm::value`?
Or is it still better to do in another PR?
If I revert the current change with `EmitLoadOfScalar` there should be a manipulation for _BitInt like it was in first version of the patch and received this comment - https://github.com/llvm/llvm-project/pull/91364#discussion_r1592864982 .

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 7 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp:764]: That would change `AppendBitField` to have a `llvm::Value` parameter instead of `llvm::ConstantInt`, is that still ok?

File: clang/lib/CodeGen/CodeGenTypes.h (hunk 8 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.h:133]: `ConstantEmitter::emitForMemory` is calling `LLVMTypeLayoutMatchesAST ` to determine if a big _BitInt constant needs to be split into individual bytes.

File: clang/lib/CodeGen/CGExprScalar.cpp (hunk 6 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprScalar.cpp]: Done.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 13]
```diff
@@ -2012,26 +2015,27 @@ llvm::Value *CodeGenFunction::EmitLoadOfScalar(Address Addr, bool Volatile,
 }
 
 llvm::Value *CodeGenFunction::EmitToMemory(llvm::Value *Value, QualType Ty) {
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp:2020]: Done.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 14]
```diff
@@ -2012,26 +2015,27 @@ llvm::Value *CodeGenFunction::EmitLoadOfScalar(Address Addr, bool Volatile,
...
+    // <N x i1> --> <P x i1>.
+    Value = emitBoolVecConversion(Value, MemNumElems, "insertvec");
+    // <P x i1> --> iP.
+    Value = Builder.CreateBitCast(Value, StoreTy);
   }
 
   return Value;
 }
 
 llvm::Value *CodeGenFunction::EmitFromMemory(llvm::Value *Value, QualType Ty) {
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp:2044]: Done.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 15]
```diff
@@ -2044,6 +2048,12 @@ llvm::Value *CodeGenFunction::EmitFromMemory(llvm::Value *Value, QualType Ty) {
     return emitBoolVecConversion(V, ValNumElems, "extractvec");
   }
 
+  if (hasBooleanRepresentation(Ty) || Ty->isBitIntType()) {
+    llvm::Type *ResTy = ConvertType(Ty);
+    bool Signed = Ty->isSignedIntegerOrEnumerationType();
+    return Builder.CreateIntCast(Value, ResTy, Signed, "loadedv");
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp]: It is always a `trunc`. Changed it to `CreateTrunc`.

File: clang/lib/CodeGen/CGExprScalar.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprScalar.cpp:5353]: > And all the callers of EmitVAAArg therefore should do getScalarVal() or similar to get a llvm::value

Yes, that's the idea.  Should significantly simplify the code for some targets.

This should be a dependent PR; we merge that first, then this PR doesn't need to touch the varargs code.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 7 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CGExprConstant.cpp:764]: I think you can use llvm::Constant? But that's fine, sure.

File: clang/lib/CodeGen/CodeGenTypes.h (hunk 8 above)
Comment (efriedma-quic) [reply clang/lib/CodeGen/CodeGenTypes.h:133]: In that case, please rename this to something that more accurately corresponds to that usage.

File: clang/lib/CodeGen/CodeGenTypes.cpp [hunk 16]
```diff
@@ -118,6 +124,37 @@ llvm::Type *CodeGenTypes::ConvertTypeForMem(QualType T, bool ForBitField) {
...
+
+  if (!T->isBitIntType() && LLVMTy->isIntegerTy(1))
+    return llvm::IntegerType::get(getLLVMContext(),
+                                  (unsigned)Context.getTypeSize(T));
+
+  if (T->isBitIntType()) {
+    llvm::Type *R = ConvertType(T);
+    if (!LLVMTypeLayoutMatchesAST(T, R))
+      return llvm::Type::getIntNTy(
+          getLLVMContext(), Context.getTypeSizeInChars(T).getQuantity() * 8);
```
Comment (hassnaaHamdi) [inline clang/lib/CodeGen/CodeGenTypes.cpp:148]: `return llvm::Type::getIntNTy(
          getLLVMContext(), Context.getTypeSizeInChars(T).getQuantity() * 8);`
Could you plz explain the logic behind using this implementation ? do you support all types > 128 and also types < 128 ? or it's specific to the types > 128 only ?

Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: We intend to support all types. In general, _BitInt(N) is lowered to iN type in LLVM IR. However it is not possible for certain sizes and some targets now due to different alignment defined for iN and _BitInt(N). This now happens for _BitInt(>=129) for x86_64 targets. `LLVMTypeLayoutMatchesAST` checks for this mismatch. If there is mismatch, say NBytes = sizeof(_BitInt(N)), we use [i8 x NBytes] as in-memory type. It is better to load and store value using iNBytes type instead of an array type since it is better for optimization and guarantees that all bits of the loaded/stores value is valid. For more info, please refer to https://github.com/llvm/llvm-project/pull/91364#issuecomment-2099351151 as well.

Comment (momchil-velikov) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: I don't understand why the choice of type is conditional. No matter of the "layout" matches or not, the stores have to produce valid in-memory representation (according to the target ABI), which in the general case means writing **all the** bits of the in-memory representation.

Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: The choice is conditional to keep changes less invasive.

I wonder if that requires to have different in-memory type for all _BitInt types?
But in case when the "layout" matches we could use `iNBytes ` for both memory type and load-store type.
Though that makes me wonder what will be the whole point of small `_BitInt` then...

Comment (momchil-velikov) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: cf. https://github.com/llvm/llvm-project/pull/91364#issuecomment-2099384663

I'm fairly certain using load/store type of `iBITS` is the correct thing to do, unconditionally.
Not quite sure about the choice between `iBITS` and `[BYTES x i8]`, if we're not talking about a load/stores how the array type could possibly be less efficient, so we don't default unconditionally to it?

Comment (rjmccall) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: We could literally use `[N x i8]` as the allocation type of every single type and save ourselves a lot of grief.  It's nicer to generate more semantic types when we can, though; it produces IR that's easier to both read and test.

File: clang/lib/CodeGen/CGExprScalar.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprScalar.cpp:5353]: I posted https://github.com/llvm/llvm-project/pull/94635 .

I somehow had to load the value anyway, since inner `EmitVAArg` that seems to be target-dependent returns an Address as well.

File: clang/lib/CodeGen/CGStmt.cpp (hunk 5 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGStmt.cpp:1539]: > So there's a trade-off here: we can unconditionally treat ReturnValue as having the for-memory type (at the cost of emitting some extra promotions/truncations), or we can track whether we were passed it vs. just allocated internally to this function (at the cost of compiler complexity around most uses of ReturnValue, which is a relatively small amount of code).

Isn't the latter happening now?

Comment (rjmccall) [reply clang/lib/CodeGen/CGStmt.cpp:1539]: I don't think so; we'd need an actual flag in `CodeGenFunction`.  Maybe we could recreate it without that by looking at the value.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 17]
```diff
@@ -610,8 +610,26 @@ bool ConstStructBuilder::AppendBytes(CharUnits FieldOffsetInChars,
...
 bool ConstStructBuilder::AppendBitField(
-    const FieldDecl *Field, uint64_t FieldOffset, llvm::ConstantInt *CI,
+    const FieldDecl *Field, uint64_t FieldOffset, llvm::Constant *C,
     bool AllowOverwrite) {
+
+  llvm::ConstantInt *CI = nullptr;
+  if (!isa<llvm::ConstantInt>(C)) {
+    // Constants for long _BitInt types are split into individual bytes.
+    // Try to fold these back into an integer constant. If that doesn't work
+    // out, we We are trying to initialize a bitfield with a non-trivial
```
Comment (Fznamznon) [inline clang/lib/CodeGen/CGExprConstant.cpp:620]:
```suggestion
    // out, then we are trying to initialize a bitfield with a non-trivial
```

File: clang/lib/CodeGen/CodeGenTypes.cpp (hunk 16 above)
Comment (nikic) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: FWIW, using `[N x i8]` for all types is exactly what Rust does nowadays.

File: clang/lib/CodeGen/CGStmt.cpp (hunk 5 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGStmt.cpp]: @rjmccall if wonder if checking `CurFnInfo->getReturnInfo().getKind()` will succeed? 
If so, I'm not really sure where else this needs to be checked, could you give a hint?

File: clang/lib/CodeGen/CodeGenTypes.h (hunk 8 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.h]: Renamed to `typeRequiresSplitIntoByteArray`. Let me know if this is better.

File: clang/lib/CodeGen/CodeGenTypes.cpp (hunk 16 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: I have a concern that this way we will always need to use a different memory type for _BitInt (perhaps always `[N x i8]`). I'm not sure it is right for all targets?

Comment (rjmccall) [reply clang/lib/CodeGen/CodeGenTypes.cpp:148]: I would like to use LLVM's `iN` type when it actually has the right data layout.  If we decide to give up and use a Rust-like opaque approach, we should do it comprehensively and not just for `_BitInt`.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (rjmccall) [reply clang/lib/CodeGen/CGExpr.cpp:2022]: That really shouldn't happen — the precondition on this function should be that `Value` has the actual scalar type.  Whenever you're not seeing that, there's somewhere else that's doing a raw load that needs to use `EmitLoadOfScalar` function instead.  Certainly that's the case of an indirect return value.

[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp]: I see, fixed now.

**Comment by Fznamznon** [comment]
Ping.

**Comment by Fznamznon** [comment]
Ping!

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (rjmccall) [reply clang/lib/CodeGen/CGExprConstant.cpp:1801]: `C` is of the scalar type, not the load/store type, right?  So tail-padding with `zeroinitializer` is still wrong:
- Given a negative value, we need to fill the "padding" with 1s, not 0s.
- On a big-endian target, the padding needs to come before the value, not after it.
Both of these are fixed by sign/zero-extending the constant to the load/store type.

File: clang/lib/CodeGen/CodeGenTypes.cpp [hunk 18]
```diff
@@ -118,6 +124,39 @@ llvm::Type *CodeGenTypes::ConvertTypeForMem(QualType T, bool ForBitField) {
...
+llvm::Type *CodeGenTypes::convertTypeForLoadStore(QualType T,
+                                                  llvm::Type *LLVMTy) {
+  if (!LLVMTy)
+    LLVMTy = ConvertType(T);
+
+  if (!T->isBitIntType() && LLVMTy->isIntegerTy(1))
+    return llvm::IntegerType::get(getLLVMContext(),
+                                  (unsigned)Context.getTypeSize(T));
+
+  if (T->isBitIntType()) {
```
Comment (rjmccall) [inline clang/lib/CodeGen/CodeGenTypes.cpp:147]: You can avoid a second call to `isBitIntType()` by just putting this block before the one above it.

File: clang/lib/CodeGen/CodeGenTypes.h [hunk 19]
```diff
@@ -128,6 +128,16 @@ class CodeGenTypes {
...
   llvm::Type *ConvertTypeForMem(QualType T, bool ForBitField = false);
 
+  /// Check that size and ABI alignment of given LLVM type matches size and
+  /// alignment of given AST type. If they don't, values of the type need to be
+  /// emitted as byte array.
+  bool typeRequiresSplitIntoByteArray(QualType ASTTy,
+                                      llvm::Type *LLVMTy = nullptr);
+
+  /// For AST types with special memory representation returns type
+  /// that ought to be used for load and store operations.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CodeGenTypes.h:138]:
```
  /// Given that T is a scalar type, return the IR type that should
  /// be used for load and store operations.  For example, this might
  /// be i8 for _Bool or i96 for _BitInt(65).  The store size of the
  /// load/store type (as reported by LLVM's data layout) is always
  /// the same as the alloc size of the memory representation type
  /// returned by ConvertTypeForMem.
  ///
  /// As an optimization, if you already know the scalar value type
  /// for T (as would be returned by ConvertType), you can pass
  /// it as the second argument so that it does not need to be
  /// recomputed in common cases where the value type and
  /// load/store type are the same.
```

File: clang/lib/CodeGen/CodeGenTypes.h [hunk 20]
```diff
@@ -128,6 +128,16 @@ class CodeGenTypes {
   /// memory representation is usually i8 or i32, depending on the target.
   llvm::Type *ConvertTypeForMem(QualType T, bool ForBitField = false);
 
+  /// Check that size and ABI alignment of given LLVM type matches size and
+  /// alignment of given AST type. If they don't, values of the type need to be
+  /// emitted as byte array.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CodeGenTypes.h:133]:
```suggestion
  /// Check whether the given type needs to be laid out in memory
  /// using an opaque byte-array type because its load/store type
  /// does not have the correct alloc size in the LLVM data layout.
  /// If this is false, the load/store type (convertTypeForLoadStore)
  /// and memory representation type (ConvertTypeForMem) will
  /// be the same type.
```

**Review by rjmccall — CHANGES_REQUESTED** [review]
Getting very close.

File: clang/lib/CodeGen/CodeGenTypes.h (hunk 20 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.h]: Thanks, applied.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 21]
```diff
@@ -610,8 +610,26 @@ bool ConstStructBuilder::AppendBytes(CharUnits FieldOffsetInChars,
 }
 
 bool ConstStructBuilder::AppendBitField(
-    const FieldDecl *Field, uint64_t FieldOffset, llvm::ConstantInt *CI,
+    const FieldDecl *Field, uint64_t FieldOffset, llvm::Constant *C,
     bool AllowOverwrite) {
+
+  llvm::ConstantInt *CI = nullptr;
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp]: Done.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp:1806]: I see, thanks. I added extending.

File: clang/lib/CodeGen/CodeGenTypes.cpp (hunk 18 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.cpp:143]: Ok, done.

File: clang/lib/CodeGen/CodeGenTypes.h (hunk 19 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.h:147]: Thanks, applied.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 1 above)
Comment (momchil-velikov) [reply clang/lib/CodeGen/CGExprConstant.cpp:1910]: How about a "small" `_BitInt` ? The comment starts
> // LLVM type doesn't match AST type only for big enough _BitInts,
and for AArch32 and AArch64 we are going to have a non-matching LLVM types even for "small" `_BitInt`s - for AArch32 because the ABI wants the padding bing in-memory representation to contain zero or the sign-bit, and for both we'd like to emit loads/stores in bigger chunks, e.g. `i17` is a single `i32` load store, as opposed to two separate accesses to `i16` and `i8`.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 22]
```diff
@@ -609,9 +609,25 @@ bool ConstStructBuilder::AppendBytes(CharUnits FieldOffsetInChars,
...
-bool ConstStructBuilder::AppendBitField(
-    const FieldDecl *Field, uint64_t FieldOffset, llvm::ConstantInt *CI,
-    bool AllowOverwrite) {
+bool ConstStructBuilder::AppendBitField(const FieldDecl *Field,
+                                        uint64_t FieldOffset, llvm::Constant *C,
+                                        bool AllowOverwrite) {
+
+  llvm::ConstantInt *CI = dyn_cast<llvm::ConstantInt>(C);
+  if (!CI) {
+    // Constants for long _BitInt types are split into individual bytes.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CGExprConstant.cpp:618]:
```suggestion
    // Constants for _BitInt types are sometimes split into individual bytes.
```

Let's try to remember that this isn't *necessarily* a function of the size of the `_BitInt` type.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 1 above)
Comment (rjmccall) [reply clang/lib/CodeGen/CGExprConstant.cpp:1910]: The test case here is just going to be something like `_SomeSplitBitIntType x = (unsigned long) &someVariable;`.  What code do we actually produce for this?  Sometimes we'll be able to fall back on dynamic initialization, but that's not always an option.

Ideally, it's just invalid to do something like that.  It certainly needs to be diagnosed if the integer type is narrower than the pointer, and wider is also problematic, although less so and in a different way.

File: clang/test/CodeGen/ext-int.c [hunk 23]
```diff
@@ -1,12 +1,25 @@
...
+// WIN32: %struct.S2 = type { [40 x i8], i32, [4 x i8] }
+// LIN32: %struct.S2 = type { [36 x i8], i32 }
+// LIN64: %struct.S3 = type { [17 x i8], [7 x i8] }
+// WIN64: %struct.S3 = type { [24 x i8] }
 
 //GH62207
 unsigned _BitInt(1) GlobSize1 = 0;
 // CHECK: @GlobSize1 = {{.*}}global i1 false
 
+// CHECK64: @__const.foo.A = private unnamed_addr constant { i17, [4 x i8], <{ i8, [23 x i8] }> } { i17 1, [4 x i8] undef, <{ i8, [23 x i8] }> <{ i8 -86, [23 x i8] zeroinitializer }> }, align 8
```
Comment (rjmccall) [inline clang/test/CodeGen/ext-int.c:19]: Hmm.  Why is `i17` in the member layout here?  Doesn't the ABI require these small `_BitInt`s to be extended out to the nearest power of 2?  So the load/store type needs to be `i32`, and that should work as the memory layout type as well.

File: clang/lib/CodeGen/CodeGenTypes.cpp (hunk 16 above)
Comment (momchil-velikov) [reply clang/lib/CodeGen/CodeGenTypes.cpp:146]: Getting back to this...

> I wonder making it unconditional that requires to have different in-memory type for all _BitInt types?

The in-memory representation is a whole number of bytes, so in general the number of in-memory bits will be different from the declared number on a `_BitInt` type.

If you have `_BitInt(K)` and a load/store type `iN`, then loading/storing `iK` won't necessarily write to the same bytes as loading/storing `iN` would. That means we won't be writing to all the bytes of the in-memory representation which might be incorrect (e.g. for AArch32 ABI which requires padding bits to be sign- or zero- extended). It can also be inefficient, because LLVM requires memory accesses to be the minimum number of bytes sufficient to hold an `iK` - e.g. `i17` will end up as a load store of `i16` followed by a load store of `i8`, whereas the in-memory representation is 4 bytes  and can be accesses as a single `i32`.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 24]
```diff
@@ -1886,6 +1896,29 @@ llvm::Constant *ConstantEmitter::emitForMemory(CodeGenModule &CGM,
     return Res;
   }
 
+  if (destType->isBitIntType()) {
+    if (CGM.getTypes().typeRequiresSplitIntoByteArray(destType, C->getType())) {
+      // Long _BitInt has array of bytes as in-memory type.
+      // So, split constant into individual bytes.
+      ConstantAggregateBuilder Builder(CGM);
+      llvm::Type *DesiredTy = CGM.getTypes().ConvertTypeForMem(destType);
+      llvm::Type *LoadStoreTy =
```
Comment (momchil-velikov) [inline clang/lib/CodeGen/CGExprConstant.cpp:1905]: It would seem instead of invoking `convertTypeForLoadStore` we could use the bit width of the in-memory type and sign-/zero- extend the `APInt Value`, something like.
```
llvm::APInt Value;
if destType is unsigned 
  Value = CI->getValue().zext(Width);
else
 Value = CI->getValue().sext(Width);
```

File: clang/test/CodeGen/ext-int.c (hunk 23 above)
Comment (Fznamznon) [reply clang/test/CodeGen/ext-int.c]: Ok, now it is i32. In fact, all _BitInt types now have memory layout type with a whole number of bytes. Please let me know if I got the idea right.
That broke almost every _BitInt test clang has, I fixed some of them, but I didn't manage to fix all.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 24 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp]: Using `convertTypeForLoadStore` is aligned with other similar places and IMO seems more generalized approach.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 22 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp]: Ok, done.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 25]
```diff
@@ -2093,17 +2107,10 @@ void CodeGenFunction::EmitStoreOfScalar(llvm::Value *Value, Address Addr,
...
-      unsigned MemNumElems = MemIntTy->getPrimitiveSizeInBits();
-      // <N x i1> --> <P x i1>.
-      Value = emitBoolVecConversion(Value, MemNumElems, "insertvec");
-      // <P x i1> --> iP.
-      Value = Builder.CreateBitCast(Value, MemIntTy);
-    } else if (!CGM.getCodeGenOpts().PreserveVec3Type) {
+    if (!CGM.getCodeGenOpts().PreserveVec3Type) {
       // Handle vec3 special.
-      if (VecTy && cast<llvm::FixedVectorType>(VecTy)->getNumElements() == 3) {
+      if (!ClangVecTy->isExtVectorBoolType() && VecTy &&
```
[the remark this answers is not in the document]
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExpr.cpp]: Done.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 1 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CGExprConstant.cpp]: Well, it seems it doesn't depend on the size of _BitInt. Using something like `_SomeSplitBitIntType x = (unsigned long) &someVariable;` either fails if I for example apply `constexpr` or falls back on dynamic initialization. So I changed the comment to make it more generic.

File: clang/lib/CodeGen/CGExprConstant.cpp (hunk 24 above)
Comment (rjmccall) [reply clang/lib/CodeGen/CGExprConstant.cpp]: Right.  Momchil, your description is actually a totally reasonable way of understanding what `convertTypeForLoadStore` *means* for `_BitInt`: the load/store type is an integer type that has the same width as the in-memory type.  We're just recognizing that as a more general concept.

File: clang/lib/CodeGen/CodeGenTypes.cpp [hunk 26]
```diff
@@ -89,7 +89,7 @@ void CodeGenTypes::addRecordTypeName(const RecordDecl *RD,
 /// ConvertType in that it is used to convert to the memory representation for
 /// a type.  For example, the scalar representation for _Bool is i1, but the
 /// memory representation is usually i8 or i32, depending on the target.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CodeGenTypes.cpp:91]:
```suggestion
/// memory representation is usually i8 or i32, depending on the target.
///
/// We generally assume that the alloc size of this type under the LLVM
/// data layout is the same as the size of the AST type.  The alignment
/// does not have to match: Clang should always use explicit alignments
/// and packed structs as necessary to produce the layout it needs.
/// But the size does need to be exactly right or else things like struct
/// layout will break.
```

File: clang/lib/CodeGen/CodeGenTypes.cpp [hunk 27]
```diff
@@ -107,17 +107,52 @@ llvm::Type *CodeGenTypes::ConvertTypeForMem(QualType T, bool ForBitField) {
     return llvm::IntegerType::get(FixedVT->getContext(), BytePadded);
   }
 
-  // If this is a bool type, or a bit-precise integer type in a bitfield
-  // representation, map this integer to the target-specified size.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CodeGenTypes.cpp:111]: Let's keep this comment; we just need to update it a little:

```
  // If T is _Bool or a _BitInt type, ConvertType will produce an IR type
  // with the exact semantic bit-width of the AST type; for example,
  // _BitInt(17) will turn into i17.  In memory, however, we need to store
  // such values extended to their full storage size as decided by AST
  // layout; this is an ABI requirement.  Ideally, we would always use an
  // integer type that's just the bit-size of the AST type; for example, if
  // sizeof(_BitInt(17)) == 4, _BitInt(17) would turn into i32.  That is what's
  // returned by convertTypeForLoadStore.  However, that type does not
  // always satisfy the size requirement on memory representation types
  // describe above.  For example, a 32-bit platform might reasonably set
  // sizeof(_BitInt(65)) == 12, but i96 is likely to have to have an alloc size
  // of 16 bytes in the LLVM data layout.  In these cases, we simply return
  // a byte array of the appropriate size.
```

**Review by rjmccall — COMMENTED** [review]
This is generally looking great, and I think it's ready to go as soon as you can finish the tests. (You said you weren't able to update all the tests — did you have questions about the remaining tests?)

I did have a thought, though.  Are we confident that the in-memory layout that LLVM is using for these large integer types matches the layout specified by the ABI?  I know this patch makes the overall sizes match, but there's also an endianness question.  When LLVM stores an i96, I assume it always stores them using the overall endianness of the target; for example,  on i386, it might do three 32-bit stores with the low 32 bits at offset 0, the middle 32 bits at offset 4, and the high 32 bits at offset 8.  I just want to make sure that the ABI specification for _BitInt always matches that.  In particular, I'm worried that it might do some middle-endian thing where it breaks the integer into chunks and then stores those chunks in little-endian order even on a big-endian machine.  (That is generally the right thing to do for BigInt types because most arithmetic operations access the chunks in little-endian order, and doing adjacent memory accesses in increasing order is generally more architecture-friendly.)

**Comment by AaronBallman** [comment]
> This is generally looking great, and I think it's ready to go as soon as you can finish the tests. (You said you weren't able to update all the tests — did you have questions about the remaining tests?)
> 
> I did have a thought, though. Are we confident that the in-memory layout that LLVM is using for these large integer types matches the layout specified by the ABI? I know this patch makes the overall sizes match, but there's also an endianness question. When LLVM stores an i96, I assume it always stores them using the overall endianness of the target; for example, on i386, it might do three 32-bit stores with the low 32 bits at offset 0, the middle 32 bits at offset 4, and the high 32 bits at offset 8. I just want to make sure that the ABI specification for _BitInt always matches that. In particular, I'm worried that it might do some middle-endian thing where it breaks the integer into chunks and then stores those chunks in little-endian order even on a big-endian machine. (That is generally the right thing to do for BigInt types because most arithmetic operations access the chunks in little-endian order, and doing adjacent memory accesses in increasing order is generally more architecture-friendly.)

FWIW, I was chasing down ABI documents yesterday, and found:

x86-64 (https://gitlab.com/x86-psABIs/x86-64-ABI): 
```
_BitInt(N) types are signed by default, and unsigned _BitInt(N) types
are unsigned.
• _BitInt(N) types are stored in little-endian order in memory. Bits in each byte
are allocated from right to left.
• For N <= 64, they have the same size and alignment as the smallest of (signed and
unsigned) char, short, int, long and long long types that can contain them.
• For N > 64, they are treated as struct of 64-bit integer chunks. The number of
chunks is the smallest number that can contain the type. _BitInt(N) types are
byte-aligned to 64 bits. The size of these types is the smallest multiple of the 64-bit
chunks greater than or equal to N.
• The value of the unused bits beyond the width of the _BitInt(N) value but within
the size of the _BitInt(N) are unspecified when stored in memory or register.
```

ARM 32-bit (https://github.com/ARM-software/abi-aa/blob/main/aapcs32/aapcs32.rst):
```
_BitInt(N <= 64) 	Smallest of the signed Fundamental Integral Data Types where byte-size*8 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. Non-significant bits within the Machine Type are sign-extended.
unsigned _BitInt(N <= 64) 	Smallest of the unsigned Fundamental Integral Data Types where byte-size*8 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. Non-significant bits within the Machine Type are zero-extended.
_BitInt(N > 64) 	Allocated as if unsigned int64_t[M] array where M*64 >= N. Last element contains sign bit. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. The lower addressed double-word contains the least significant bits of the type on a little-endian view and the most significant bits of the type in a big-endian view. Non-significant bits within the last double-word are sign-extended.
unsigned _Bitint(N > 64) 	Allocated as if unsigned int64_t[M] where M*64 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. The lower addressed double-word contains the least significant bits of the type on a little-endian view and the most significant bits of the type in a big-endian view. Non-significant bits within the last double-word are zero-extended.
```

ARM 64-bit (https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst):
```
_BitInt(N <= 128) 	Smallest of the signed Fundamental Integral Data Types where byte-size*8 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. Non-significant bits within the Machine Type are unspecified.
unsigned _BitInt(N <= 128) 	Smallest of the unsigned Fundamental Integral Data Types where byte-size*8 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. Non-significant bits within the Machine Type are unspecified.
_BitInt(N > 128) 	Mapped as if unsigned __int128[M] array where M*128 >= N. Last element contains sign bit. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. The lower addressed quad-word contains the least significant bits of the type on a little-endian view and the most significant bits of the type in a big-endian view. Non-significant bits within the last quad-word are unspecified.
unsigned _Bitint(N > 128) 	Mapped as if unsigned __int128[M] where M*128 >= N. 	C2x Only. Significant bits are allocated from least significant end of the Machine Type. The lower addressed quad-word contains the least significant bits of the type on a little-endian view and the most significant bits of the type in a big-endian view. Non-significant bits within the last quad-word are unspecified.
```

The latest RISC-V, LoongArch, and CSKY ABI documents I could find did not mention `_BitInt`. I could not find any modern ABI document for PowerPC (power.org seems to no longer be about powerpc), but the one on Internet Archive also does not mention `_BitInt`.

File: clang/lib/CodeGen/CodeGenTypes.cpp (hunk 27 above)
Comment (Fznamznon) [reply clang/lib/CodeGen/CodeGenTypes.cpp:111]: Added, thanks.

**Comment by rjmccall** [comment]
Okay, so x86_64 describes it in byte terms and says they're little-endian, which is consistent with the overall target.  Interestingly, it does not guarantee the content of the excess bits.  The code-generation in this patch is consistent with that: the extension we do is unnecessary but allowed, and then we truncate it away after load.  If we ever add some way to tell the backend that a truncation is known to be reversing a sign/zero-extension, we'll need to not set it on this target.

32-bit and 64-bit ARM describe it in terms of smaller units, but the units are expressly laid out according to the overall endianness of the target, which composes to mean that the bytes overall are also laid out according to that endianness.

**Comment by rjmccall** [comment]
Given all that, I feel pretty comfortable relying on using LLVM's `i96` stores and so on.  I do worry some that we're eventually going to run into a target where the `_BitInt` ABI does not match what LLVM wants to generate for `i96` load/store, but we should be able to generalize this so that targets can override the `_BitInt` operations pretty easily.

File: clang/lib/CodeGen/CGExprConstant.cpp [hunk 28]
```diff
@@ -609,9 +609,25 @@ bool ConstStructBuilder::AppendBytes(CharUnits FieldOffsetInChars,
...
-bool ConstStructBuilder::AppendBitField(
-    const FieldDecl *Field, uint64_t FieldOffset, llvm::ConstantInt *CI,
-    bool AllowOverwrite) {
+bool ConstStructBuilder::AppendBitField(const FieldDecl *Field,
+                                        uint64_t FieldOffset, llvm::Constant *C,
+                                        bool AllowOverwrite) {
+
+  llvm::ConstantInt *CI = dyn_cast<llvm::ConstantInt>(C);
+  if (!CI) {
+    // Constants long _BitInt types are sometimes split into individual bytes.
```
Comment (rjmccall) [inline clang/lib/CodeGen/CGExprConstant.cpp:618]:
```suggestion
    // Constants for long _BitInt types are sometimes split into individual bytes.
```

**Review by rjmccall — APPROVED** [review]
LGTM

**Comment by nikic** [comment]
> Okay, so x86_64 describes it in byte terms and says they're little-endian, which is consistent with the overall target. Interestingly, it does not guarantee the content of the excess bits. The code-generation in this patch is consistent with that: the extension we do is unnecessary but allowed, and then we truncate it away after load. If we ever add some way to tell the backend that a truncation is known to be reversing a sign/zero-extension, we'll need to not set it on this target.

FYI this already exists in the form of `trunc nuw` / `trunc nsw`. (Though it's not fully optimized yet.)

**Comment by momchil-velikov** [comment]
This solves 5-6 issues we had downstream, many thanks!

**Comment by rjmccall** [comment]
> > Okay, so x86_64 describes it in byte terms and says they're little-endian, which is consistent with the overall target. Interestingly, it does not guarantee the content of the excess bits. The code-generation in this patch is consistent with that: the extension we do is unnecessary but allowed, and then we truncate it away after load. If we ever add some way to tell the backend that a truncation is known to be reversing a sign/zero-extension, we'll need to not set it on this target.
> 
> FYI this already exists in the form of `trunc nuw` / `trunc nsw`. (Though it's not fully optimized yet.)

Ah, neat.  Mariya, would you mind looking into setting this properly on the truncates we're doing here?  It'd be fine to do that as a follow-up; no need to hold up this PR for it.  You'll need some kind of target hook to tell us whether to set it or not.  Probably that ought to go in the Basic TargetInfo just so all of the target-specific ABI configuration is done in one place.

**Review by rjmccall — APPROVED** [review]

**Comment by Fznamznon** [comment]
> Mariya, would you mind looking into setting this properly on the truncates we're doing here? It'd be fine to do that as a follow-up; no need to hold up this PR for it. You'll need some kind of target hook to tell us whether to set it or not. Probably that ought to go in the Basic TargetInfo just so all of the target-specific ABI configuration is done in one place.

Sure.
