### PR TITLE
[Clang] Instantiate local constexpr functions eagerly

### LINKED ISSUE #35052: lambda expression is not a constant expression when auto (generic) parameter is used.
|  |  |
| --- | --- |
| Bugzilla Link | [35704](https://llvm.org/bz35704) |
| Version | trunk |
| OS | Windows NT |
| Attachments | [sample cpp file](https://user-images.githubusercontent.com/60944935/143756747-1ebddae5-0c33-4886-ae99-12a8f1d0fed6.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

When constexpr lambda used in constant expression it going non constant when its parameter is auto.

In this sample got an error:

1>  ConsoleApplication1.cpp(20,16): error : constexpr if condition is not a constant expression
1>          if constexpr (f(TypeTag<T>::value))
1>                        ^~~~~~~~~~~~~~~~~~~~

But if

auto predicate = [](auto v) constexpr -> bool

replaced by

auto predicate = [](*size_t* v) constexpr -> bool

all ok.

----------------------------------------------
#include <iostream>

template<typename T>
struct TypeTag
{
	constexpr static size_t value = 1;
};

template<>
struct TypeTag<float>
{
	constexpr static size_t value = 2;
};

template<typename T, typename F>
constexpr auto func(F f)
{
	if constexpr (f(TypeTag<T>::value))
	{
		return int{1};
	}
	else
	{
		return float{2.2f};
	}
}

int main()
{
	auto predicate = [](auto v) constexpr -> bool 	// does not compile when v is auto
	{
		return v == 1;
	};

	constexpr auto ok = predicate(75);

	constexpr auto fail = func<int>(predicate);

	return 0;
}

### LINKED ISSUE #94849: [clang++] constexpr is not propagated in lambda in a template context under specific condition
I initially discovered this issue on the official clang 18 build on Ubuntu. Then I did a quick test on [compiler explorer](https://godbolt.org/), and it seems to affect all clang versions (starting clang 5) that support C++17 constexpr lambda feature; perhaps platform does not really matter.

Consider the following code:
```cpp
template<typename = void>
void doStuff() {
	auto equalsOne = [](auto x) -> bool {
		return x == 1;
	};
	static_assert(equalsOne(1), "oops");
}

int main() {
	doStuff();
}
```
And compile with:
```sh
clang++ -std=c++17 ./example.cpp -o example
```
This code does not compile and will generate the following errors:
> static assertion expression is not an integral constant expression \
> static_assert(equalsOne(1), "oops");

There are a few observations:
- The code compiles on GCC and MSVC.
- Make `doStuff` non-template, i.e. removing `template<typename = void>`, compiles.
- Change the lambda call signature from `auto x` to `int x`, compiles. However, it still does not compile if it is in C++20 and replace `auto` with explicit lambda template parameter. This basically means it does not compile when lambda is a template, regardless of how it is templated.
- Change the trailing return type of lambda `-> bool` to `-> auto`, or equivalently removing the trailing return type, compiles.
- It does not compile even if decorating the lambda with `constexpr`, i.e. `[](auto x) constexpr -> bool`.

### PR DESCRIPTION
**Pull request by zyn0217**
We had a code path in `Sema::MarkFunctionReferenced()` that deferred local lambda instantiation even for constexprs. This resulted in any calls to them referring to function decls that lack bodies and hence failures at constant evaluation.

The issue doesn't occur when the lambda has no explicit return type because the return type deduction requires instantiation.

Fixes https://github.com/llvm/llvm-project/issues/35052
Fixes https://github.com/llvm/llvm-project/issues/94849

### CODE REVIEW

**Comment by EricWF** [comment]
This looks good to me, but I'm not comfortable officially LGTMing it.

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -18112,7 +18112,8 @@ void Sema::MarkFunctionReferenced(SourceLocation Loc, FunctionDecl *Func,
 
         if (FirstInstantiation || TSK != TSK_ImplicitInstantiation ||
             Func->isConstexpr()) {
-          if (isa<CXXRecordDecl>(Func->getDeclContext()) &&
+          if (!Func->isConstexpr() &&
```
Comment (mizvekov) [inline clang/lib/Sema/SemaExpr.cpp:18115]: Nit: Slight simplification, you might as well move this branch after the `else if (Func->isConstexpr())` below instead of testing it's negation.

**Review by mizvekov — APPROVED** [review]
LGTM

**Comment by zyn0217** [comment]
Thanks for the review! I will commit when CI turns green.

**Comment by zyn0217** [comment]
Linux CI failed with an unrelated error.
```
TIMEOUT: lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py (87750 of 87750)
  | ******************** TEST 'lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py' FAILED ********************
```

**Comment by cor3ntin** [comment]
@zyn0217 What is the status of that?

**Comment by zyn0217** [comment]
It's still broken, and I haven’t figured out an approach to fix the regression.

I do recall that we were planning to wire up Sema and the constant evaluator, so this patch might end up being completely superseded if that gets implemented.
