### PR TITLE
[mlir][Vector] Add a rewrite pattern for gather over a strided memref

### LINKED ISSUE #15364: iree-compile fails because of the lowering to builtin.unrealized_conversion_cast operations
### What happened?

During the compilation of the following reproducer, IREE fails with the error: `failed to legalize operation 'builtin.unrealized_conversion_cast' that was explicitly marked illegal`.

### Steps to reproduce your issue

model.mlir:
```
module @execute_model attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2592000x3xf32>, %arg1: tensor<518400x1xi32>) -> tensor<518400xf32> {
      %0 = stablehlo.slice %arg0 [0:2592000, 0:1] : (tensor<2592000x3xf32>) -> tensor<2592000x1xf32>
      %1 = stablehlo.reshape %0 : (tensor<2592000x1xf32>) -> tensor<2592000xf32>
      %2 = "stablehlo.gather"(%1, %arg1) {dimension_numbers = #stablehlo.gather<collapsed_slice_dims = [0], start_index_map = [0], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = dense<1> : tensor<1xi64>} : (tensor<2592000xf32>, tensor<518400x1xi32>) -> tensor<518400xf32>
      return %2 : tensor<518400xf32>
  }
}
```

Command: `iree-compile --iree-input-type=stablehlo --iree-hal-target-backends=llvm-cpu model.mlir`

### What component(s) does this issue relate to?

_No response_

### Version information

commit 7b92a6d38599d3255b4513f1019c540a3401cfd3 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by banach-space**
This patch adds a rewrite pattern for `vector.gather` over a strided memref like the following:

```mlir
%subview = memref.subview %arg0[0, 0] [100, 1] [1, 1] :
    memref<100x3xf32> to memref<100xf32, strided<[3]>>
%gather = vector.gather %subview[%c0] [%idxs], %cst_0, %cst :
    memref<100xf32, strided<[3]>>, vector<4xindex>, vector<4xi1>, vector<4xf32>
    into vector<4xf32>
```

```mlir
%collapse_shape = memref.collapse_shape %arg0 [[0, 1]] :
    memref<100x3xf32> into memref<300xf32>
%1 = arith.muli %arg3, %cst : vector<4xindex>
%gather = vector.gather %collapse_shape[%c0] [%1], %cst_1, %cst_0 :
    memref<300xf32>, vector<4xindex>, vector<4xi1>, vector<4xf32>
    into vector<4xf32>
```

Fixes https://github.com/openxla/iree/issues/15364.

### CODE REVIEW

**Review by NicolaLancellotti — APPROVED** [review]
Thank you @banach-space , LGTM!

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 1]
```diff
@@ -96,6 +96,82 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+    Value base = op.getBase();
+    if (!base.getDefiningOp())
+      return failure();
+
+    // TODO: Strided accesses might be coming from other ops as well
+    auto subview = dyn_cast<memref::SubViewOp>(base.getDefiningOp());
+    if (!subview)
+      return failure();
+
+    // TODO: Allows ranks > 2.
```
Comment (MacDue) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:129]: It's a little confusing the example above seems to show a 1D subview.

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 2]
```diff
@@ -96,6 +96,82 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+
+    // Get strides
+    auto layout = subview.getResult().getType().getLayout();
+    auto stridedLayoutAttr = llvm::dyn_cast<StridedLayoutAttr>(layout);
+
+    // TODO: Allow the access to be strided in multiple dimensions.
+    if (stridedLayoutAttr.getStrides().size() != 1)
+      return failure();
+
+    int64_t srcTrailingDim = subview.getSource().getType().getShape().back();
```
Comment (MacDue) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:141]: Maybe make `sourceType` a variable? It's used above too (and this is a little bit of a long chain :))

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 3]
```diff
@@ -96,6 +96,82 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+    if (!subview)
+      return failure();
+
+    // TODO: Allows ranks > 2.
+    if (subview.getSource().getType().getRank() != 2)
+      return failure();
+
+    // Get strides
+    auto layout = subview.getResult().getType().getLayout();
+    auto stridedLayoutAttr = llvm::dyn_cast<StridedLayoutAttr>(layout);
```
Comment (MacDue) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:135]: Can `stridedLayoutAttr` be null here?

**Review by MacDue — APPROVED** [review]
This seems alright to me, though maybe let someone else have a quick check. Just a few little nits:

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp (hunk 3 above)
Comment (MacDue) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:135]: (It's used unchecked below)

File: mlir/test/Dialect/Vector/vector-gather-lowering.mlir [hunk 4]
```diff
@@ -151,3 +151,57 @@ func.func @gather_tensor_1d_none_set(%base: tensor<?xf32>, %v: vector<2xindex>,
...
+// CHECK:           %[[MASK_0:.*]] = vector.extract %[[MASK]][0] : i1 from vector<4xi1>
+// CHECK:           %[[IDX_0:.*]] = vector.extract %[[NEW_IDXS]][0] : index from vector<4xindex>
+// CHECK:           scf.if %[[MASK_0]] -> (vector<4xf32>)
+// CHECK:             %[[M_0:.*]] = vector.load %[[COLLAPSED]]{{\[}}%[[IDX_0]]] : memref<300xf32>, vector<1xf32>
+// CHECK:             %[[V_0:.*]] = vector.extract %[[M_0]][0] : f32 from vector<1xf32>
+
+// CHECK:           %[[MASK_1:.*]] = vector.extract %[[MASK]][1] : i1 from vector<4xi1>
+// CHECK:           %[[IDX_1:.*]] = vector.extract %[[NEW_IDXS]][1] : index from vector<4xindex>
+// CHECK:           scf.if %[[MASK_1]] -> (vector<4xf32>)
+// CHECK:             %[[M_1:.*]] = vector.load %[[COLLAPSED]]{{\[}}%[[IDX_1]]] : memref<300xf32>, vector<1xf32>
```
Comment (hanhanW) [inline mlir/test/Dialect/Vector/vector-gather-lowering.mlir:194]: nit: we don't need to escape `[` in this case. Because we don't capture `%` in variables. It is a trick that I learned from other MLIR contributers.

```suggestion
// CHECK:             %[[M_1:.*]] = vector.load %[[COLLAPSED]][%[[IDX_1]]] : memref<300xf32>, vector<1xf32>
```

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 5]
```diff
@@ -96,6 +96,82 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+  using OpRewritePattern::OpRewritePattern;
+
+  LogicalResult matchAndRewrite(vector::GatherOp op,
+                                PatternRewriter &rewriter) const override {
+    Value base = op.getBase();
+    if (!base.getDefiningOp())
+      return failure();
+
+    // TODO: Strided accesses might be coming from other ops as well
+    auto subview = dyn_cast<memref::SubViewOp>(base.getDefiningOp());
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:125]: Based on the comment, have you considered to use `OffsetSizeAndStrideOpInterface` interface?

btw, we prefer moving the casting to `getDefiningOp` method, e.g.,

```suggestion
    auto subview = base.getDefiningOp<memref::SubViewOp>();
```

File: mlir/test/Dialect/Vector/vector-gather-lowering.mlir [hunk 6]
```diff
@@ -151,3 +151,57 @@ func.func @gather_tensor_1d_none_set(%base: tensor<?xf32>, %v: vector<2xindex>,
...
+  %c0 = arith.constant 0 : index
+  %x_1 = affine.apply #map()[%x]
+  // Strided MemRef
+  %subview = memref.subview %M_in[0, 0] [100, 1] [1, 1] : memref<100x3xf32> to memref<100xf32, strided<[3]>>
+  %cst_0 = arith.constant dense<true> : vector<4xi1>
+  %cst = arith.constant dense<0.000000e+00> : vector<4xf32>
+  // Gather of a strided MemRef
+  %7 = vector.gather %subview[%c0] [%idxs], %cst_0, %cst : memref<100xf32, strided<[3]>>, vector<4xindex>, vector<4xi1>, vector<4xf32> into vector<4xf32>
+  %subview_1 = memref.subview %M_out[%x_1] [%y] [1] : memref<518400xf32> to memref<?xf32, strided<[1], offset: ?>>
+  vector.store %7, %subview_1[%c0] : memref<?xf32, strided<[1], offset: ?>>, vector<4xf32>
```
[the remark this answers is not in the document]
Comment (hanhanW) [reply mlir/test/Dialect/Vector/vector-gather-lowering.mlir:170]: +1

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 7]
```diff
@@ -96,6 +96,82 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+    if (!subview)
+      return failure();
```
[the remark this answers is not in the document]
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:127]: Hm, I'm not sure that that would work here. I'd still need something like this:
```cpp
    auto subview = dyn_cast_if_present<memref::SubViewOp>(base.getDefiningOp());
    if (!subview)
      return failure();
```

In most places `dyn_cast_if_present` would be used like this:
```cpp
    if (auto subview = dyn_cast_if_present<memref::SubViewOp>(base.getDefiningOp())) {
       // some logic here
    }
```

I could do the same, but then I would be unnecessarily indenting the whole function, which is something I'd rather avoid (also trying to follow https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code). Unless I am missing something 🤔 .

[the remark this answers is not in the document]
Comment (c-rhodes) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:127]: > Hm, I'm not sure that that would work here. I'd still need something like this:
> 
> ```c++
>     auto subview = dyn_cast_if_present<memref::SubViewOp>(base.getDefiningOp());
>     if (!subview)
>       return failure();
> ```

this is what I meant, so the if above can be removed. But I think @hanhanW suggestion to do the cast as part of `getDefiningOp` is better.

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp (hunk 5 above)
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:125]: > btw, we prefer moving the casting to getDefiningOp method

Thanks! Would you have a link to a relevant discussion? Otherwise I will probably repeat similar mistake :(

Comment (MacDue) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp]: There's also a subtle (safety) difference, `base.getDefiningOp()` can return null, which will fail to `dyn_cast`. `getDefiningOp<memref::SubViewOp>()` accounts for that (via doing a `dyn_cast_or_null` internally).

**Comment by banach-space** [comment]
I've just sent an update and resolved threads that should be address by that update. Please re-open if I missed something 🙏🏻 .

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 8]
```diff
@@ -168,6 +244,6 @@ struct Gather1DToConditionalLoads : OpRewritePattern<vector::GatherOp> {
 
 void mlir::vector::populateVectorGatherLoweringPatterns(
     RewritePatternSet &patterns, PatternBenefit benefit) {
-  patterns.add<FlattenGather, Gather1DToConditionalLoads>(patterns.getContext(),
-                                                          benefit);
+  patterns.add<FlattenGather, RemoveStrideFromGatherSource,
```
[the remark this answers is not in the document]
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:252]: ATM all patterns will match, but I believe that only [Gather1DToConditionalLoads](https://github.com/llvm/llvm-project/blob/205f53010d0da11a9c4ab7a4655edb4a2ded1b02/mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp#L102) is problematic here as it lowers to `vector.load` and:
* https://github.com/llvm/llvm-project/blob/205f53010d0da11a9c4ab7a4655edb4a2ded1b02/mlir/lib/Dialect/Vector/IR/VectorOps.cpp#L4544

(as in, that would be an unsupported `vector.load`). So, let me update `Gather1DToConditionalLoads`. Please check whether that makes sense to you 🙏🏻 .

[the remark this answers is not in the document]
Comment (dcaballe) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:263]: Thanks! I was more thinking that we don't know the order in which all these patterns will be applied. If we have a pattern that is able to remove the stride and we want that to always happen before the gather is lowered, we have to make sure that the rest of the patterns have a check to bail out when a stride is found.

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp (hunk 5 above)
Comment (hanhanW) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp]: I actually don't have a pointer to a relevant discussion. It is mostly from my review experience and codebase exploring. It is shorter and safer, so I think it is a hidden convention.

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 9]
```diff
@@ -96,6 +96,87 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+/// %subview = memref.subview %M (...) memref<100x3xf32> to memref<100xf32,
+/// strided<[3]>> %gather = vector.gather %subview (...) : memref<100xf32,
+/// strided<[3]>>
+/// ```
+/// ==>
+/// ```mlir
+/// %collapse_shape = memref.collapse_shape %M (...) memref<100x3xf32> into
+/// memref<300xf32> %1 = arith.muli %idxs, %c3 : vector<4xindex> %gather =
+/// vector.gather %collapse_shape (...) : memref<300xf32> (...)
+/// ```
```
Comment (hanhanW) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:112]: can you format the MLIR snippet a bit? Perhaps we can have one operation per line, e.g.,

```suggestion
/// ```mlir
/// %subview = memref.subview %M (...) memref<100x3xf32> to memref<100xf32,
///     strided<[3]>>
/// %gather = vector.gather %subview (...) : memref<100xf32, strided<[3]>>
/// ```
/// ==>
/// ```mlir
/// %collapse_shape = memref.collapse_shape %M (...) memref<100x3xf32> into
///     memref<300xf32>
/// %1 = arith.muli %idxs, %c3 : vector<4xindex>
/// %gather = vector.gather %collapse_shape (...) : memref<300xf32> (...)
/// ```
```

**Review by hanhanW — APPROVED** [review]
LGTM, just one nit. Thanks!

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp (hunk 9 above)
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:112]: Argh, that's clang-format, sorry :( Thanks for pointing it out! 🙏🏻

**Review by dcaballe — APPROVED** [review]
Thanks!

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 10]
```diff
@@ -96,6 +96,89 @@ struct FlattenGather : OpRewritePattern<vector::GatherOp> {
...
+/// ATM this is effectively limited to reading a 1D Vector from a 2D MemRef,
+/// but should be fairly straightforward to extend beyond that.
+struct RemoveStrideFromGatherSource : OpRewritePattern<vector::GatherOp> {
+  using OpRewritePattern::OpRewritePattern;
+
+  LogicalResult matchAndRewrite(vector::GatherOp op,
+                                PatternRewriter &rewriter) const override {
+    Value base = op.getBase();
+    if (!base.getDefiningOp())
+      return failure();
```
Comment (c-rhodes) [inline mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:125]: this can be removed now

**Review by c-rhodes — APPROVED** [review]
Few things I think can be removed, but otherwise LGTM, cheers

File: mlir/test/Dialect/Vector/vector-gather-lowering.mlir [hunk 11]
```diff
@@ -151,3 +151,59 @@ func.func @gather_tensor_1d_none_set(%base: tensor<?xf32>, %v: vector<2xindex>,
...
 }
+
+// Check that vector.gather of a strided memref is replaced with a
+// vector.gather with indices encoding the original strides. Note that multiple
+// patterns are run for this example, e.g.:
+  //  1. "remove stride from gather source"
+  //  2. "flatten gather"
+// However, the main goal is to the test Pattern 1 above.
+#map = affine_map<()[s0] -> (s0 * 4096)>
+#map1 = affine_map<()[s0] -> (s0 * -4096 + 518400, 4096)>
```
[the remark this answers is not in the document]
Comment (banach-space) [reply mlir/test/Dialect/Vector/vector-gather-lowering.mlir:162]: Thanks 🙏🏻

File: mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp [hunk 12]
```diff
@@ -115,6 +198,17 @@ struct Gather1DToConditionalLoads : OpRewritePattern<vector::GatherOp> {
 
     Value condMask = op.getMask();
     Value base = op.getBase();
+
+    // vector.load requires the most minor memref dim to have unit stride
+    if (auto memType = dyn_cast<MemRefType>(base.getType())) {
+      memType.getLayout();
```
[the remark this answers is not in the document]
Comment (banach-space) [reply mlir/lib/Dialect/Vector/Transforms/LowerVectorGather.cpp:204]: Thanks 🙏🏻
