### PR TITLE
[Clang] Demote mixed enumeration arithmetic error to a warning

### LINKED ISSUE #92340: unsuppressable error about invalid bitwise operation between different enumeration types
We use Infiniband API installed on hundreds of servers in our farm.  It is in /usr/include/infiniband/verbs.h.  For R&D, it is third-party software.
This program
`#include <infiniband/verbs.h>`
Then compilation fails like this
```
/grid/common/test/llvm-v18.1.1d1rh74_lnx86/bin/clang++ -c -std=c++26 -Wno-error -Wno-enum-conversion -Wno-deprecated-anon-enum-enum-conversion enum.cpp
In file included from enum.cpp:1:
/usr/include/infiniband/verbs.h:550:53: error: invalid bitwise operation between different enumeration types ('(unnamed enum at /usr/include/infiniband/verbs.h:539:1)' and 'ibv_create_cq_wc_flags')
  550 |         IBV_CREATE_CQ_SUP_WC_FLAGS = IBV_WC_STANDARD_FLAGS |
      |                                      ~~~~~~~~~~~~~~~~~~~~~ ^
  551 |                                 IBV_WC_EX_WITH_COMPLETION_TIMESTAMP |
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
With -std=++2b, it does not.
The error is correct.  What is incorrect is that the error has no ID and cannot be suppressed in any known way.
According to this page
https://clang.llvm.org/docs/DiagnosticsReference.html#wanon-enum-enum-conversion
I can make the second enum anon, too, by adding -Dibv_create_cq_wc_flags= to the command line.  The error changes but stays an error:
```
/usr/include/infiniband/verbs.h:550:53: error: invalid bitwise operation between different enumeration types ('(unnamed enum at /usr/include/infiniband/verbs.h:539:1)' and
      '(unnamed enum at /usr/include/infiniband/verbs.h:524:1)')
```
This is a wrong general situation, every message must have an ID and be suppressable.
This is some info about the header:
-rw-r--r-- 1 root root 92862 Mar 22  2021 /usr/include/infiniband/verbs.h
a07809625d1024f1dfdf3db62a66ce88  /usr/include/infiniband/verbs.h
I am unsure if copying a couple of lines from that header to this ticket is a good idea.

### PR DESCRIPTION
**Pull request by cor3ntin**
In C++, defaulted to an error.

C++ removed these features but the removal negatively impacts users.

Fixes #92340

### CODE REVIEW

**Comment by cor3ntin** [comment]
(this should be backported)

File: clang/test/SemaCXX/cxx2c-enum-compare.cpp [hunk 1]
```diff
@@ -1,9 +1,10 @@
-// RUN: %clang_cc1 %s -std=c++2c -fsyntax-only -verify -triple %itanium_abi_triple
+// RUN: %clang_cc1 %s -std=c++2c -fsyntax-only -verify=both,expected
+// RUN: %clang_cc1 %s -std=c++2c -fsyntax-only -verify=both,nowarn -Wno-enum-enum-conversion
```
Comment (AaronBallman) [inline clang/test/SemaCXX/cxx2c-enum-compare.cpp:2]: `nowarn` is unused, but I think it should be silencing the invalid comparison diagnostic, shouldn't it?

Comment (cor3ntin) [reply clang/test/SemaCXX/cxx2c-enum-compare.cpp:2]: Comparing with double seems a lot weirder than comparing with another enum and no one complained about that; I think it should remain an error

Comment (AaronBallman) [reply clang/test/SemaCXX/cxx2c-enum-compare.cpp]: Whoops, I was misreading the test, there is test coverage for this. Sorry!

**Review by AaronBallman — APPROVED** [review]
LGTM, but be sure to add a release note on the backport so users know about the change in behavior.

**Comment by tstellar** [comment]
@cor3ntin Were you able to manually create a backport PR for this?

**Comment by cor3ntin** [comment]
@tstellar it slipped my mind, I can do that later today though

**Comment by cor3ntin** [comment]
@tstellar https://github.com/llvm/llvm-project/pull/139396
