### PR TITLE
[Clang][Sema] Revise the transformation of CTAD parameters of nested class templates

### LINKED ISSUE #88142: Clang frontend crash with deduction guide inside class template
This seems to be a regression from 17 to 18/trunk. 

```cpp
template <typename, typename...>
struct X {
  template <typename>
  struct Y {
    template <typename T>
    Y(T) {}
  };

  template <typename T, typename... Vs>
  Y(T, Vs...) -> Y<T>;
};

using T = X<int>::Y<int>;
```
https://godbolt.org/z/K5d3sWGjP

### PR DESCRIPTION
**Pull request by zyn0217**
This fixes a regression introduced by bee78b88f.

When we form a deduction guide for a constructor, basically, we do the following work:
- Collect template parameters from the constructor's surrounding class template, if present.
- Collect template parameters from the constructor.
- Splice these template parameters together into a new template parameter list.
- Turn all the references (e.g. the function parameter list) to the invented parameter list by applying a `TreeTransform` to the function type.

In the previous fix, we handled cases of nested class templates by substituting the "outer" template parameters (i.e. those not declared at the surrounding class template or the constructor) with the instantiating template arguments. The approach per se makes sense, but there was a flaw in the following case:

```cpp
template <typename U, typename... Us> struct X {
  template <typename V> struct Y {
    template <typename T> Y(T) {}
  };

  template <typename T> Y(T) -> Y<T>;
};

X<int>::Y y(42);
```

While we're transforming the parameters for `Y(T)`, we first attempt to transform all references to `V` and `T`; then, we handle the references to outer parameters `U` and `Us` using the template arguments from `X<int>` by transforming the same `ParamDecl`. However, the first step results in the reference `T` being `<template-param-0-1>` because the invented `T` is the last of the parameter list of the deduction guide, and what we're substituting with is a corresponding parameter pack (which is `Us`, though empty). Hence we're messing up the substitution.

I think we can resolve it by reversing the substitution order, which means handling outer template parameters first and then the inner parameters.

There's no release note because this is a regression in 18, and I hope we can catch up with the last release.

Fixes https://github.com/llvm/llvm-project/issues/88142

### CODE REVIEW

**Review by antangelo — APPROVED** [review]
These changes make sense to me, but please wait for the others to review as well.

File: clang/test/SemaTemplate/nested-implicit-deduction-guides.cpp [hunk 1]
```diff
@@ -84,3 +84,17 @@ nested_init_list<int>::concept_fail nil_invalid{1, ""};
 // expected-note@#INIT_LIST_INNER_INVALID {{candidate template ignored: substitution failure [with F = const char *]: constraints not satisfied for class template 'concept_fail' [with F = const char *]}}
 // expected-note@#INIT_LIST_INNER_INVALID {{candidate function template not viable: requires 1 argument, but 2 were provided}}
 // expected-note@#INIT_LIST_INNER_INVALID {{candidate function template not viable: requires 0 arguments, but 2 were provided}}
+
+namespace PR88142 {
```
Comment (hokein) [inline clang/test/SemaTemplate/nested-implicit-deduction-guides.cpp:88]: nit: PR => GH

File: clang/lib/Sema/SemaTemplate.cpp [hunk 2]
```diff
@@ -2583,11 +2580,27 @@ struct ConvertConstructorToDeductionGuideTransform {
...
         NewParam = transformFunctionTypeParam(NewParam, OuterInstantiationArgs,
                                               MaterializedTypedefs);
+        if (!NewParam)
+          return QualType();
+      }
+      // Then, transform all the references to template parameters that are
+      // defined at the class template and the constructor. In this example,
+      // they're U and V, respectively.
+      NewParam =
+          transformFunctionTypeParam(NewParam, Args, MaterializedTypedefs);
```
Comment (hokein) [inline clang/lib/Sema/SemaTemplate.cpp:2603]: We have the same pattern on Line 2438-2452 in this file, where we perform a substitution of `OuterInstantiationArgs` on a new transformed parameter decl, I think we should probably fix it as well.

**Review by hokein — COMMENTED** [review]
The fix looks good to me, and thanks for the comprehensive explanation in the description.

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplate.cpp:2603]: I think that's just fine, although it looks weird: those lines are merely "creating" new template parameters rather than doing type substitution. (it's applying a `TemplateDeclInstantiator` with the instantiating arguments - the only valuable part from these arguments is the depth we're supposed to deduct, and the type isn't something we're concerned about at that time.)

Frankly, I have to say I didn't fully understand why we have such discrepancies (use the `transformTemplateParameter` first and then a `TemplateDeclInstantiator` for nested cases). I was expecting that perhaps we could unify them in one call. I think it warrants a separate refactoring PR, then.

**Comment by zyn0217** [comment]
I'm merging it now - if something breaks and I'm not in front of my computer, feel free to revert then.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (antangelo) [reply clang/lib/Sema/SemaTemplate.cpp:2603]: The `TemplateDeclInstantiator` is used for that substitution to avoid evaluating constraints at that point. Without this, the constraint template argument depths on `NewParam` would be as if the parameter were at depth 0 (instead of the nested template depth), causing a crash when evaluated later.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplate.cpp:2603]: @antangelo : thanks for the explanation. I was considering if we can reuse the `transformTemplateTypeParam` stuff instead of a `TemplateDeclInstantiator` (we can make the constraint evaluation opt-in in that function; I presumed this would behave like what `setEvaluateConstraints(false)` does.), but doing that doesn't look like it would simplify the logic here significantly, so I hesitated to do so.

The other part `Depth1Args` also prevents us from combining these substitution into one call - I think I have to go through it further. Anyhow, this shouldn't block a backport.
