### PR TITLE
[SPIR-V] Cast ptr kernel args to i8* when used as Store's value operand

### LINKED ISSUE #72864: [SPIR-V][OpenCL] Type mismatch on OpStore instruction
The following snippet:
```c
kernel void k(global ulong *dst) {
  dst[0] = 123;
  dst[1] = 321;
  dst[2] = 1111;
}
```
Fails to validate:
```
$ clang -target spirv64v1.2 -O0 -fintegrated-objemitter store-issue.cl -c -o - | spirv-val -
error: line 31: OpStore Pointer <id> '17[%dst_addr]'s type does not match Object <id> '15[%dst]'s type.
  OpStore %dst_addr %dst Aligned 8

```

### PR DESCRIPTION
**Pull request by michalpaszkowski**
Handle a special case when StoreInst's value operand is a kernel argument of a pointer type. Since these arguments could have either a basic element type (e.g. float*) or OpenCL builtin type (sampler_t), bitcast the StoreInst's value operand to default pointer element type (i8).

This pull request addresses the issue https://github.com/llvm/llvm-project/issues/72864

### CODE REVIEW

File: llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp [hunk 1]
```diff
@@ -282,7 +283,26 @@ void SPIRVEmitIntrinsics::insertPtrCastInstr(Instruction *I) {
...
   unsigned OperandToReplace;
-  if (StoreInst *SI = dyn_cast<StoreInst>(I)) {
+  bool AllowCastingToChar = false;
+
+  StoreInst *SI = dyn_cast<StoreInst>(I);
+  if (SI && F->getCallingConv() == CallingConv::SPIR_KERNEL &&
+      SI->getValueOperand()->getType()->isPointerTy() &&
+      isa<Argument>(SI->getValueOperand())) {
+    Argument *Arg = dyn_cast<Argument>(SI->getValueOperand());
+    MDString *ArgType = getOCLKernelArgType(*Arg->getParent(), Arg->getArgNo());
```
Comment (iliya-diyachkov) [inline llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp:293]: Can Arg be nullptr?

File: llvm/test/CodeGen/SPIRV/pointers/store-kernel-arg-ptr-as-value-operand.ll [hunk 2]
```diff
@@ -0,0 +1,19 @@
+; RUN: llc -O0 -mtriple=spirv64-unknown-unknown %s -o - | FileCheck %s
+; RUN: %if spirv-tools %{ llc -O0 -mtriple=spirv64-unknown-unknown %s -o - -filetype=obj | spirv-val %}
+
+define spir_kernel void @foo(ptr addrspace(1) %arg) !kernel_arg_addr_space !1 !kernel_arg_access_qual !2 !kernel_arg_type !3 !kernel_arg_base_type !3 !kernel_arg_type_qual !4 {
```
Comment (Keenuts) [inline llvm/test/CodeGen/SPIRV/pointers/store-kernel-arg-ptr-as-value-operand.ll:4]: Do we have a test that covers the case you mentioned where the arguments can be found in the module-level metadata?

**Review by sudonatalie — APPROVED** [review]

File: llvm/test/CodeGen/SPIRV/pointers/store-kernel-arg-ptr-as-value-operand.ll (hunk 2 above)
Comment (michalpaszkowski) [reply llvm/test/CodeGen/SPIRV/pointers/store-kernel-arg-ptr-as-value-operand.ll:4]: Yes, we do have a test in `llvm/test/CodeGen/SPIRV/opencl/metadata/kernel_arg_type_module_metadata.ll`

File: llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp (hunk 1 above)
Comment (michalpaszkowski) [reply llvm/lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp:293]: Thanks @sudonatalie! Fixed!
