### PR TITLE
[AArch64] Fixes for Windows varargs handling.

### LINKED ISSUE #139856: [ARM64EC] Can't call a virtual function by function pointer
Minimal code to reproduce:
````c++
struct ChildClass {
  virtual void fn() {}
};


int main()
{
  ChildClass obj;
  auto fnptr = &ChildClass::fn;
  (obj.*fnptr)();
  return 0;
}
````

The crash point always like this:

> [0x0]   ConsoleApplication1!ChildClass::`vcall'{0}'+0x54   0x7d75cffb80   0x7ff6e577106c   

Image

Verison: clang 20.1.4
target: arm64ec-pc-windows-msvc

This is a arm64ec specific problem. This can't be reproduced on arm64-pc-windows-msvc
For a simple virtual function call like `obj->fn()`, there is no problem.

This bug also makes `std::invoke`, and googletest unusable.

### PR DESCRIPTION
**Pull request by efriedma-quic**
Omit spills when va_start is not present, like we do on other targets.  In most situations this is just an optimization, but for thunks in arm64ec, we need this because it's illegal to reference varargs in a thunk.

Fix the bug that prevented omitting vararg spills from working properly: we need to avoid interfering with musttail handling.  (This is not a Windows-only issue, but it mostly affects Windows because musttail thunks are mostly used for the Microsoft C++ ABI.)

On arm64ec, don't set x4 and x5 for musttail thunks; forward them from the caller.

Fixes #139856 .

### CODE REVIEW

**Comment by mstorsjo** [comment]
I presume this has the same end effect as #126780, so perhaps it would be nice to reference that reverted PR in the description too.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -9439,7 +9439,8 @@ AArch64TargetLowering::LowerCall(CallLoweringInfo &CLI,
     }
   }
 
-  if (IsVarArg && Subtarget->isWindowsArm64EC()) {
+  if (IsVarArg && Subtarget->isWindowsArm64EC() &&
+      !(CLI.CB && CLI.CB->isMustTailCall())) {
```
Comment (rnk) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:9443]: I see you have the test case to show that we forward X4 and X5 through musttail. 👍

**Review by rnk — APPROVED** [review]
Thanks!

**Review by pskrgag — APPROVED** [review]
Thanks for addressing Windows side!

**Review by dpaoliello — APPROVED** [review]
