### PR TITLE
[OpenACC] Fix invalid routine case where 'bind' didn't exist

### LINKED ISSUE #192245: [clang][OpenACC] Assertion `Val && "isa<> used on a null pointer"' failed.
Reproducer:
https://godbolt.org/z/5qbT7z98K
```cpp
#pragma acc routine seq device_type(*)
#pragma acc routine bind("asdf") seq
void foo();
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/include/llvm/Support/Casting.h:109: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = clang::OpenACCBindClause; From = clang::OpenACCClause]: Assertion `Val && "isa<> used on a null pointer"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -fopenacc <source>
1.	<eof> parser at end of file
 #0 0x00000000044d3258 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44d3258)
 #1 0x00000000044d0084 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44d0084)
 #2 0x00000000044d06a4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44d06a4)
 #3 0x000000000440e3e8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x0000733d74a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x0000733d74a969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x0000733d74a42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x0000733d74a287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x0000733d74a2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #9 0x0000733d74a39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x000000000752ccf3 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x752ccf3)
#11 0x000000000753b87b clang::SemaOpenACC::CheckRoutineDecl(clang::SourceLocation, llvm::ArrayRef<clang::OpenACCClause const*>, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x753b87b)
#12 0x000000000753ba82 clang::SemaOpenACC::ActOnEndRoutineDeclDirective(clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::Expr*, clang::SourceLocation, llvm::ArrayRef<clang::OpenACCClause const*>, clang::SourceLocation, clang::OpaquePtr<clang::DeclGroupRef>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x753ba82)
#13 0x0000000006dcdbc0 clang::Parser::ParseOpenACCAfterRoutineDecl(clang::AccessSpecifier&, clang::ParsedAttributes&, clang::TypeSpecifierType, clang::Decl*, clang::Parser::OpenACCDirectiveParseInfo&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dcdbc0)
#14 0x0000000006dd6e71 clang::Parser::ParseOpenACCDirectiveDecl(clang::AccessSpecifier&, clang::ParsedAttributes&, clang::TypeSpecifierType, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dd6e71)
#15 0x0000000006dc5603 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dc5603)
#16 0x0000000006dc64b5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dc64b5)
#17 0x0000000006dc68a0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6dc68a0)
#18 0x0000000006da73e3 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6da73e3)
#19 0x0000000004fd8948 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4fd8948)
#20 0x00000000052f6565 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52f6565)
#21 0x000000000527520e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x527520e)
#22 0x00000000053f2f2d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x53f2f2d)
#23 0x0000000000de34d2 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde34d2)
#24 0x0000000000dd9e0a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#25 0x0000000000dd9f8d int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#26 0x0000000005042d59 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#27 0x000000000440e824 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x440e824)
#28 0x0000000005043386 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#29 0x0000000005001892 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5001892)
#30 0x000000000500283e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x500283e)
#31 0x000000000500a4e5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x500a4e5)
#32 0x0000000000ddf834 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xddf834)
#33 0x0000000000c9878a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc9878a)
#34 0x0000733d74a29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#35 0x0000733d74a29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#36 0x0000000000dd98a5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd98a5)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by erichkeane**
For some reason I'd failed to check the result of `find_if` and just assumed that the `bind` clause must exist!  Looking through my other tests, I've validated every other combination other than this one for some reason.

Fixes: #192245

### CODE REVIEW

File: clang/lib/Sema/SemaOpenACC.cpp [hunk 1]
```diff
@@ -2416,35 +2416,38 @@ void SemaOpenACC::CheckRoutineDecl(SourceLocation DirLoc,
...
-      auto OtherBindItr =
-          llvm::find_if(RA->Clauses, llvm::IsaPred<OpenACCBindClause>);
-      if (OtherBindItr != RA->Clauses.end() &&
-          (*cast<OpenACCBindClause>(*BindItr)) !=
-              (*cast<OpenACCBindClause>(*OtherBindItr))) {
-        Diag((*BindItr)->getBeginLoc(), diag::err_acc_duplicate_unnamed_bind);
-        Diag((*OtherBindItr)->getEndLoc(), diag::note_acc_previous_clause_here)
-            << (*BindItr)->getClauseKind();
-        return;
+  if (BindItr != Clauses.end()) {
```
Comment (ojhunt) [inline clang/lib/Sema/SemaOpenACC.cpp:2419]: I can't tell from the diff, but is it possible for this to be an early return instead?

Comment (erichkeane) [reply clang/lib/Sema/SemaOpenACC.cpp:2419]: That would cause us to duplicate the code on 2454, which seemed like a worse decision than just tabbing in 1 more level.

Comment (ojhunt) [reply clang/lib/Sema/SemaOpenACC.cpp:2419]: That's fair

Though you could undertake a giant refactor to make a it a method ("extract as method": 1 function, 500 parameters!) :D
