### PR TITLE
[Flang][OpenMP] Prevent ICE for certain constructs in unnamed programs

### LINKED ISSUE #72748: [Flang][OpenMP] crash when a structure exists
Compiling the following program with `-fopenmp` causes a crash.
```console
$ cat struct.f90
structure /s/
end structure

end
```

Compile with: `flang-new -fopenmp struct.f90`

Output:
```console
fatal internal error: SemanticsContext::FindScope(): invalid source location for 'structure /s/'
```

Stack dump:
```console
 #0 0x0000561f919513c3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) 
 #1 0x0000561f91951a3e SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f6348bf7520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007f6348c4ba7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #4 0x00007f6348c4ba7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #5 0x00007f6348c4ba7c pthread_kill ./nptl/pthread_kill.c:89:10
 #6 0x00007f6348bf7476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00007f6348bdd7f3 abort ./stdlib/abort.c:81:7
 #8 0x0000561f929098b6 Fortran::common::getFlangRepositoryPath[abi:cxx11]()
 #9 0x0000561f921d3219 
#10 0x0000561f92346a88 Fortran::semantics::Scope* GetScope<Fortran::parser::MainProgram>(Fortran::semantics::SemanticsContext&, Fortran::parser::MainProgram const&) resolve-directives.cpp:0:0
#11 0x0000561f92346958 _ZNSt8__detail9__variant17__gen_vtable_implINS0_12_Multi_arrayIPFNS0_21__deduce_visit_resultIPN7Fortran9semantics6SymbolEEEOZZNS5_23ResolveOmpTopLevelPartsERNS5_16SemanticsContextERKNS4_6parser7ProgramEENK4$_15clIZNS5_23ResolveOmpTopLevelPartsESA_SE_E4$_16EEDaT_EUlRSI_E_RKSt7variantIJNS4_6common11IndirectionINSB_11MainProgramELb0EEENSO_INSB_18FunctionSubprogramELb0EEENSO_INSB_20SubroutineSubprogramELb0EEENSO_INSB_6ModuleELb0EEENSO_INSB_9SubmoduleELb0EEENSO_INSB_9BlockDataELb0EEENSO_INSB_17CompilerDirectiveELb0EEENSO_INSB_23OpenACCRoutineConstructELb0EEEEEEJEEESt16integer_sequenceImJLm0EEEE14__visit_invokeESL_S17_ resolve-directives.cpp:0:0
#12 0x0000561f92343b29 Fortran::semantics::ResolveOmpTopLevelParts(Fortran::semantics::SemanticsContext&, Fortran::parser::Program const&) 
#13 0x0000561f921859f2 Fortran::semantics::ResolveNames(Fortran::semantics::SemanticsContext&, Fortran::parser::Program const&, Fortran::semantics::Scope&) 
#14 0x0000561f921d3d6b Fortran::semantics::Semantics::Perform() 
#15 0x0000561f91972835 Fortran::frontend::FrontendAction::runSemanticChecks() 
#16 0x0000561f91d65f43 Fortran::frontend::CodeGenAction::beginSourceFileAction() 
#17 0x0000561f91971f13 Fortran::frontend::FrontendAction::beginSourceFile(Fortran::frontend::CompilerInstance&, Fortran::frontend::FrontendInputFile const&) 
#18 0x0000561f91968cf0 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) 
#19 0x0000561f919751aa Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) 
#20 0x0000561f91637f8d fc1_main(llvm::ArrayRef<char const*>, char const*) 
#21 0x0000561f91636f76 main 
#22 0x00007f6348bded90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#23 0x00007f6348bdee40 call_init ./csu/../csu/libc-start.c:128:20
#24 0x00007f6348bdee40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#25 0x0000561f916364d5 _start 
flang-new: error: unable to execute command: Aborted
flang-new: error: flang frontend command failed due to signal (use -v to see invocation)
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git e2210cefb18171496573957945f9bd48eb631170)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

### PR DESCRIPTION
**Pull request by skatrak**
This patch fixes #72748 by modifying the processing of program units to search for a symbol to which OpenMP REQUIRES clauses can bind to. Rather than picking up the first PFT node with a source reference and getting its associated scope, it picks up the last one.

This avoids using the source from the first specification construct of an nameless program, which can sometimes not be associated to any scope, causing an ICE due to an invalid source location.

### CODE REVIEW

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -25,7 +25,7 @@
 template <typename T>
 static Fortran::semantics::Scope *GetScope(
     Fortran::semantics::SemanticsContext &context, const T &x) {
-  std::optional<Fortran::parser::CharBlock> source{GetSource(x)};
+  std::optional<Fortran::parser::CharBlock> source{GetLastSource(x)};
```
Comment (klausler) [inline flang/lib/Semantics/resolve-directives.cpp:28]: Why does this fix the bug?  Wouldn't it still fail when presented with a list or vector or tuple of parse tree nodes with a single element that would fail without this change?

Comment (skatrak) [reply flang/lib/Semantics/resolve-directives.cpp:28]: This function is only called for `MainProgram`, `FunctionSubprogram`, `SubroutineSubprogram` and `BlockData` (see `ResolveOmpTopLevelParts` in the same file). It tries to get the scope associated to these nodes and crashes while doing so in certain situations when it is a nameless `MainProgram`. As far as I can tell, the issue is that, when the optional `ProgramStmt` is not present (nameless program) the call to `GetSource` will return the source object of the first sourced PFT node that appears in the program, which may not have a scope associated.

In my opinion, it is incorrect to return the scope associated to any inner constructs when querying the program itself. This change makes it so the END statement of the program/function/subroutine/block, which is always present, is picked up every time, preventing this problem and stopping the crash from happening.

Maybe it'd be good to possibly restrict the `GetScope` function so it fails to compile if we pass any unexpected PFT node type, or just add a comment to describe its intended use. I'll gladly do it if that helps, or if there are any other suggestions as to how to deal with this case.

Comment (skatrak) [reply flang/lib/Semantics/resolve-directives.cpp:28]: Does this sound like a reasonable solution? Thanks!

Comment (skatrak) [reply flang/lib/Semantics/resolve-directives.cpp:28]: Ping @klausler, I'd appreciate it if you could let me know whether my previous explanation addresses your concerns. Thanks for your time!

**Review by klausler — APPROVED** [review]
