### PR TITLE
[Clang] Correctly determine constexprness of dependent lambdas.

### LINKED ISSUE #97958: lambda's operator() is non-constexpr function
This program
```c++
static_assert(
    []<int I=0>() -> decltype([]{ return true; })
    { return {}; }()());
```
is accepted in GCC, MSVC and Clang 17, but Clang 18 complains:
```
error: static assertion expression is not an integral constant expression
    2 |     []<int I=0>() -> decltype([]{ return true; })
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 |     { return {}; }()());
      |     ~~~~~~~~~~~~~~~~~~
<source>:2:5: note: non-constexpr function 'operator()' cannot be used in a constant expression
<source>:2:31: note: declared here
    2 |     []<int I=0>() -> decltype([]{ return true; })
```
Online demo: https://gcc.godbolt.org/z/nW74e4q9v

It is a modified example from https://stackoverflow.com/q/77431308/7325599

### LINKED ISSUE #114234: Clang: immediately-invoked lambda in template arg is not implicitly constexpr
An IILE as a template argument inside some other templates; this is the smallest SSCCE I could find.

```cpp
template <auto Arg>
auto g() { return Arg; }

template <typename>
auto f() {
    []<typename>() {
        // lambda is not treated as implicitly constexpr?
        g<[] { return 123; }()>();
        // explicit constexpr works
        // g<[] () constexpr { return 123; }()>();
    }.template operator()<int>();
}

int main() { f<int>(); }
```

produces:

```console
<source>:8:9: error: no matching function for call to 'g'
    8 |         g<[] { return 123; }()>();
      |         ^~~~~~~~~~~~~~~~~~~~~~~
<source>:6:20: note: while substituting into a lambda expression here
    6 |     []<typename>() {
      |                    ^
<source>:14:14: note: in instantiation of function template specialization 'f<int>' requested here
   14 | int main() { f<int>(); }
      |              ^
<source>:2:6: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Arg'
    2 | auto g() { return Arg; }
      |      ^
1 error generated.
```

https://godbolt.org/z/x6heGf38x

### PR DESCRIPTION
**Pull request by cor3ntin**
We skipped checking if a lambda is constexpr if the parent context was dependent, even if the lambda itself wasn't (and there is no other opportunity to establish constexprness)

Fixes #114234
Fixes #97958

### CODE REVIEW

File: clang/lib/Sema/SemaLambda.cpp [hunk 1]
```diff
@@ -2239,18 +2239,18 @@ ExprResult Sema::BuildLambdaExpr(SourceLocation StartLoc, SourceLocation EndLoc,
...
-                                          CaptureInits, EndLoc,
-                                          ContainsUnexpandedParameterPack);
+  LambdaExpr *Lambda =
+      LambdaExpr::Create(Context, Class, IntroducerRange, CaptureDefault,
+                         CaptureDefaultLoc, ExplicitParams, ExplicitResultType,
+                         CaptureInits, EndLoc, ContainsUnexpandedParameterPack);
+
   // If the lambda expression's call operator is not explicitly marked constexpr
   // and we are not in a dependent context, analyze the call operator to infer
   // its constexpr-ness, suppressing diagnostics while doing so.
```
Comment (Sirraide) [inline clang/lib/Sema/SemaLambda.cpp:2249]: Maybe this comment needs updating now?

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -991,6 +991,7 @@ Bug Fixes to C++ Support
 - Fixed assertions or false compiler diagnostics in the case of C++ modules for
   lambda functions or inline friend functions defined inside templates (#GH122493).
 - Clang now rejects declaring an alias template with the same name as its template parameter. (#GH123423)
+- Correctly determine the implicit constexprness of dependent lambdas. (#GH97958) (#GH114234)
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:994]:
```suggestion
- Correctly determine the implicit constexprness of lambdas in dependent contexts. (#GH97958) (#GH114234)
```
Maybe this is a bit clearer because strictly speaking this is about cases where the lambda itself *isn’t* dependent.

**Review by Sirraide — APPROVED** [review]
Makes sense. After thinking about this for a bit, I don’t think there is a reason why we’d ever need to care about the parent context at all for the purpose of determining `constexpr`ness, is there?

File: clang/lib/Sema/SemaLambda.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaLambda.cpp]: Indeed, thanks for catching that

**Review by zyn0217 — APPROVED** [review]
Thanks
