### PR TITLE
[Clang] [Sema] Make `-Wincompatible-pointer-types` an error by default

### LINKED ISSUE #74605: Make -Wincompatible-pointer-types an error by default
GCC 14 plans to make `-Wincompatible-pointer-types` an error by default for >= C99. GCC may still roll back this specific change (while retaining the other modern C changes) for GCC 14 and reinstate that one change again later depending on how we get on with the porting work. My hope is that we won't need to do that, but I mention it for full disclosure.

Clang has a subset warning, `-Wincompatible-function-pointer-types`, which was made fatal in Clang 16. GCC hasn't implemented this subset warning, but after discussion (some at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109835, some off-bug), decided this probably wasn't worth it, and to go wholehog with `-Wincompatible-pointer-types` as an error instead.

fweimer and I have already been doing the various autoconf configure comparisons and so on. so far, the damage isn't really bad at all for the configure check side, although the blast radius in general for C is still fairly big (but manageable) for the warning overall.

I think it makes sense for Clang to make `-Wincompatible-pointer-types` an error as well, given that it's _very_ often an indicator of wrong code. So far, many of the examples I've seen were either always outright broken, or at least broken on 32-bit. I also think it makes sense to have a united front for the overall Modern C effort and to have consistent behaviour for GCC and Clang here.

cc @AaronBallman

### PR DESCRIPTION
**Pull request by Sirraide**
GCC 14 also made this an error by default, and I thought it’d make sense to follow suit.

Fixes #74605

### CODE REVIEW

**Comment by thesamesam** [comment]
https://github.com/llvm/llvm-project/issues/74605

**Review by cor3ntin — APPROVED** [review]
LGTM but let's see if other people have opinions in the next few days.
That GCC did it first and did not get pushback is reassuring

@erichkeane

**Review by erichkeane — APPROVED** [review]
I think this makes sense, and if GCC hasn't gotten a huge amount of pushback, then there is no reason for us not to do this.

File: clang/test/Analysis/uninit-vals-union.c [hunk 1]
```diff
@@ -8,6 +9,6 @@ typedef struct { int x; } A;
 
 void foo(void) {
   U u = {};
-  A *a = &u; // expected-warning{{incompatible pointer types}}
+  A *a = (A*)&u;
```
Comment (shafik) [inline clang/test/Analysis/uninit-vals-union.c:12]: So I see the `no-crash` below and worry a bit b/c sometimes crashes can be dependent on previous issues on previous lines. So maybe this is not longer a regression test?

Comment (Sirraide) [reply clang/test/Analysis/uninit-vals-union.c:12]: I suppose we can also use `-Wno-error` for this test; I tried to avoid doing that in case we ever make this a hard error because then all those tests will have to be updated again...

**Comment by asb** [comment]
> Looks like this is causing errors in llvm-testsuite, but I’m candidly not sure how this is usually handled: https://lab.llvm.org/buildbot/#/builders/210/builds/2746

I think we'll want to add `-Wno-incompatible-pointer-types` to the relevant CMakeLists.txt. As an example, we can see @AaronBallman making such changes around https://github.com/llvm/llvm-test-suite/commits/099fc20d7e352f51d7c76a5d89fecbd15d7fae5e for the `-Wimplicit-int` change.

**Comment by adrian-prantl** [comment]
@medismailben @Sirraide This seems to have broken several tests several tests in the LLDB test suite: 
https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/as-lldb-cmake/33215/

**Comment by Sirraide** [comment]
> This seems to have broken several tests several tests in the LLDB test suite: https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/as-lldb-cmake/33215/

Weird, I’m pretty sure I ran the LLDB tests locally and didn’t observe any errors; I’m looking into it.

**Comment by medismailben** [comment]
Thanks, feel free to merge whenever

**Comment by alexfh** [comment]
This diagnostic fires in the following code - https://gcc.godbolt.org/z/G6sYcTnWc:
```
extern void f(struct stat*);
#include <sys/stat.h>
void g() {
    struct stat s;
    f(&s);
}
```

```
<source>:1:22: warning: declaration of 'struct stat' will not be visible outside of this function [-Wvisibility]
    1 | extern void f(struct stat*);
      |                      ^
<source>:5:7: error: incompatible pointer types passing 'struct stat *' to parameter of type 'struct stat *' [-Wincompatible-pointer-types]
    5 |     f(&s);
      |       ^~
<source>:1:27: note: passing argument to parameter here
    1 | extern void f(struct stat*);
      |                           ^
```
Is this expected?

**Comment by alexfh** [comment]
> > This diagnostic fires in the following code - https://gcc.godbolt.org/z/G6sYcTnWc:
> > ...
> > Is this expected?
> 
> Yes. The prototype of `f` is using a `locally` defined struct (see the `Wvisibility` diagnostic). So that type is ONLY visible on line 1.

Thanks for the explanation! Interestingly, neither of the two diagnostics is issued when compiling the code as C++, though I would expect this to be invalid C++ code. Any thoughts on how this works in C++?

...
> IF this is your code, I'd suggest doing a forward-declaration of `struct stat` outside of a function prototype.

Yep, a forward declaration (or better `#include <sys/stat.h>`) before the first use of `struct stat` is needed to make this code unambiguously correct.
