### PR TITLE
[X86][AVX] Fix handling of out-of-bounds shift amounts in AVX2 vector shift nodes

### LINKED ISSUE #83840: [X86][AVX] Recognise out of bounds AVX2 shift amounts
Pulled out of #39822 which was a bit too general.

Unlike the general ISD SRA/SRL/SHL nodes, the AVX2 vector shift nodes X86ISD VSRAV/VSRLV/VSHLV handle out of bounds shift amounts:

- VSRAV clamps the unsigned shift amount to (BITWIDTH-1)
- VSRLV/VSHLV returns a zero value for unsigned shift amounts greater than (BITWIDTH-1).

So when lowering vector shifts, we should be able to fold any shift amount clamp patterns and use the X86ISD nodetypes.

e.g.

```ll
define <4 x i32> @ashr(<4 x i32> %sh, <4 x i32> %amt) {
  %elt.min.i = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %amt, <4 x i32> <i32 31, i32 31, i32 31, i32 31>)
  %shr = ashr <4 x i32> %sh, %elt.min.i
  ret <4 x i32> %shr
}
```
-> 
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpbroadcastd    xmm2, dword ptr [rip + .LCPI0_0] # xmm2 = [31,31,31,31]
        vpminud xmm1, xmm1, xmm2
        vpsravd xmm0, xmm0, xmm1
        ret
```
vs
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpsravd xmm0, xmm0, xmm1
        ret
```

Logical shifts are trickier but also foldable:
```ll
define <4 x i32> @lshr(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %shr = lshr <4 x i32> %sh, %amt
  %0 = select <4 x i1> %cmp.i, <4 x i32> %shr, <4 x i32> zeroinitializer
  ret <4 x i32> %0
}

define <4 x i32> @lshr2(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %0 = select <4 x i1> %cmp.i, <4 x i32> %sh, <4 x i32> zeroinitializer
  %shr = lshr <4 x i32> %0, %amt
  ret <4 x i32> %shr
}
```

### PR DESCRIPTION
**Pull request by SahilPatidar**
Resolve #83840

### CODE REVIEW

**Comment by SahilPatidar** [comment]
@RKSimon

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -47291,6 +47291,16 @@ static SDValue combineShiftRightArithmetic(SDNode *N, SelectionDAG &DAG,
...
     return V;
 
+  APInt ShiftAmt;
+  SDNode *UMinNode = N1.getNode();
+  if (UMinNode->getOpcode() == ISD::UMIN &&
+      ISD::isConstantSplatVector(UMinNode->getOperand(1).getNode(), ShiftAmt) &&
+      ShiftAmt == VT.getScalarSizeInBits() - 1) {
+    SDValue ShrAmtVal = UMinNode->getOperand(0);
+    SDLoc DL(N);
+    return DAG.getNode(N->getOpcode(), DL, N->getVTList(), N0, ShrAmtVal);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: The N->getOpcode() is just the regular ISD::SRA opcode - we need to use the X86ISD::VSRAV equivalent, but only if its safe to do so - we can check that with supportedVectorShiftWithImm

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: I tried the following code:
```cpp
unsigned int Opcode = N->getOpcode();
if (supportedVectorShiftWithImm(VT, Subtarget, X86ISD::VSRAV)) {
     Opcode = X86ISD::VSRAV;
}
```
But with this code, it crashes the above test.:
```
LLVM ERROR: Cannot select: t13: v4i32 = X86ISD::VSRAV t2, t4
  t2: v4i32,ch = CopyFromReg t0, Register:v4i32 %0
    t1: v4i32 = Register %0
  t4: v4i32,ch = CopyFromReg t0, Register:v4i32 %1
    t3: v4i32 = Register %1
In function: combine_vec_ashr_out_of_bound
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build/bin/llc -mtriple=x86_64-unknown-unknown -mattr=+sse4.1
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@combine_vec_ashr_out_of_bound'
 #0 0x0000000107ec3c14 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105c37c14)
 #1 0x0000000107ec417c PrintStackTraceSignalHandler(void*) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105c3817c)
 #2 0x0000000107ec1d58 llvm::sys::RunSignalHandlers() (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105c35d58)
 #3 0x0000000107ec5db4 SignalHandler(int) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105c39db4)
 #4 0x000000018d945a24 (/usr/lib/system/libsystem_platform.dylib+0x18046da24)
 #5 0x000000018d915cc0 (/usr/lib/system/libsystem_pthread.dylib+0x18043dcc0)
 #6 0x000000018d821a40 (/usr/lib/system/libsystem_c.dylib+0x180349a40)
 #7 0x0000000107d53964 llvm::report_fatal_error(llvm::Twine const&, bool) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105ac7964)
 #8 0x0000000107bb2154 llvm::SmallVectorTemplateCommon<(anonymous namespace)::MatchScope, void>::back() (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105926154)
 #9 0x0000000107bae860 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105922860)
#10 0x00000001048779a4 (anonymous namespace)::X86DAGToDAGISel::SelectCode(llvm::SDNode*) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1025eb9a4)
#11 0x000000010486c1e4 (anonymous namespace)::X86DAGToDAGISel::Select(llvm::SDNode*) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1025e01e4)
#12 0x0000000107b9ff2c llvm::SelectionDAGISel::DoInstructionSelection() (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105913f2c)
#13 0x0000000107b9eb5c llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105912b5c)
#14 0x0000000107b9d708 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true>, false, true>, bool&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x105911708)
#15 0x0000000107b9be54 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x10590fe54)
#16 0x0000000107b993a0 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x10590d3a0)
#17 0x000000010485cad4 (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1025d0ad4)
#18 0x0000000106031ce0 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x103da5ce0)
#19 0x0000000106b6bfb0 llvm::FPPassManager::runOnFunction(llvm::Function&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1048dffb0)
#20 0x0000000106b731e8 llvm::FPPassManager::runOnModule(llvm::Module&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1048e71e8)
#21 0x0000000106b6c844 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1048e0844)
#22 0x0000000106b6c3d0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1048e03d0)
#23 0x0000000106b735e8 llvm::legacy::PassManager::run(llvm::Module&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1048e75e8)
#24 0x00000001022925a4 compileModule(char**, llvm::LLVMContext&) (/Users/sahilpatidar/Desktop/llvm/llvm-project/build/bin/llc+0x1000065a4)
```

Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: Shouldn't it be `supportedVectorShiftWithImm(VT, Subtarget, ISD::SRA)` ?

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: Oops, I misunderstood.

Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: It might be useful to add an assertion inside supportedVectorShiftWithImm that checks that Opcode is a ISD::SHL/SRA/SRL

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: just to be clear Does that mean if a Subtarget natively supports ISD::SRA for vector shifts, we should use ISD::SRA?

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: just to be clear Does that mean if a Subtarget natively supports ISD::SRA for vector shifts, we should use ISD::SRA?

Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: No, because ISD::SRA nodes treat out of bounds shift amounts as undefined - we must replace it with a X86ISD::VSRAV node as we want the explicit behaviour explained in the issue - which means we can only perform this fold if X86ISD::VSRAV is legal (vXi32 on AVX2 - vXi64 on AVX512F - vXi16 on AVX512BW) - supportedVectorShiftWithImm should handle that for us.

Comment (SahilPatidar) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: Okay, here is the modified code:
```cpp
if (supportedVectorShiftWithImm(VT, Subtarget, ISD::SRA) &&
      UMinNode->getOpcode() == ISD::UMIN &&
      ISD::isConstantSplatVector(UMinNode->getOperand(1).getNode(), ShiftAmt) &&
      ShiftAmt == VT.getScalarSizeInBits() - 1) {
    SDValue ShrAmtVal = UMinNode->getOperand(0);
    SDLoc DL(N);
    return DAG.getNode(X86ISD::VSRAV, DL, N->getVTList(), N0, ShrAmtVal);
  }
```
With this code, it still crashes.

Comment (RKSimon) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:47301]: I'm sorry but that should have been `supportedVectorVarShift` :(

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 2]
```diff
@@ -28927,6 +28927,9 @@ SDValue X86TargetLowering::LowerWin64_INT128_TO_FP(SDValue Op,
 // supported by the Subtarget
 static bool supportedVectorShiftWithImm(EVT VT, const X86Subtarget &Subtarget,
                                         unsigned Opcode) {
+  assert(Opcode == ISD::SHL || Opcode == ISD::SRA || Opcode == ISD::SRL &&
+        "Unexpected Opcode!");
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:28931]: Please rebase as I already added these asserts at 7b90a67fe717338f7ae4e53f6b97d0f29bacde8e

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 3]
```diff
@@ -521,3 +521,33 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
...
+; SSE-NEXT:    retq
+;
+; AVX-LABEL: combine_vec_ashr_out_of_bound:
+; AVX:       # %bb.0:
+; AVX-NEXT:    vpsravd %xmm1, %xmm0, %xmm0
+; AVX-NEXT:    retq
+  %1 = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %y, <4 x i32> <i32 31, i32 31, i32 31, i32 31>)
+  %2 = ashr <4 x i32> %x, %1
+  ret <4 x i32> %2
+}
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:553]: Please can you add `<8 x i16>` and `<4 x i64>` test coverage - that should check for differences in the AVX2/AVX512 cases

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 4]
```diff
@@ -47334,6 +47334,17 @@ static SDValue combineShiftRightArithmetic(SDNode *N, SelectionDAG &DAG,
   if (SDValue V = combineShiftToPMULH(N, DAG, Subtarget))
     return V;
 
+  APInt ShiftAmt;
+  SDNode *UMinNode = N1.getNode();
+  if (supportedVectorVarShift(VT, Subtarget, ISD::SRA) &&
+      UMinNode->getOpcode() == ISD::UMIN &&
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47340]: `N1.getOpcode() == ISD::UMIN`

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 5]
```diff
@@ -47334,6 +47334,17 @@ static SDValue combineShiftRightArithmetic(SDNode *N, SelectionDAG &DAG,
...
+      ISD::isConstantSplatVector(UMinNode->getOperand(1).getNode(), ShiftAmt) &&
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47341]: `ISD::isConstantSplatVector(N1.getOperand(1).getNode(), ShiftAmt)`

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 6]
```diff
@@ -47334,6 +47334,17 @@ static SDValue combineShiftRightArithmetic(SDNode *N, SelectionDAG &DAG,
...
+      ShiftAmt == VT.getScalarSizeInBits() - 1) {
+    SDValue ShrAmtVal = UMinNode->getOperand(0);
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:47343]: `SDValue ShrAmtVal = N1.getOperand(0);`

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 7]
```diff
@@ -521,3 +521,278 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
...
+; AVX2-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
+; AVX2-NEXT:    vzeroupper
+; AVX2-NEXT:    retq
+;
+; AVX512-LABEL: combine_vec16_ashr_out_of_bound:
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vpminuw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1, %xmm1
+; AVX512-NEXT:    vpsravw %xmm1, %xmm0, %xmm0
+; AVX512-NEXT:    retq
+  %1 = tail call <8 x i16> @llvm.umin.v4i16(<8 x i16> %y, <8 x i16> <i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31>)
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:610]: Why 31?

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 8]
```diff
@@ -521,3 +521,278 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
   %2 = ashr <4 x i32> %1, <i32 10, i32 10, i32 10, i32 10>
   ret <4 x i32> %2
 }
+
+define <8 x i16> @combine_vec16_ashr_out_of_bound(<8 x i16> %x, <8 x i16> %y) {
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:525]: vec16 -> v8i16

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 9]
```diff
@@ -521,3 +521,278 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
...
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vpminuw {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1, %xmm1
+; AVX512-NEXT:    vpsravw %xmm1, %xmm0, %xmm0
+; AVX512-NEXT:    retq
+  %1 = tail call <8 x i16> @llvm.umin.v4i16(<8 x i16> %y, <8 x i16> <i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31>)
+  %2 = ashr <8 x i16> %x, %1
+  ret <8 x i16> %2
+}
+
+define <4 x i32> @combine_vec32_ashr_out_of_bound(<4 x i32> %x, <4 x i32> %y) {
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:615]: vec32 -> v4i32

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 10]
```diff
@@ -521,3 +521,278 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
...
+; AVX-LABEL: combine_vec32_ashr_out_of_bound:
+; AVX:       # %bb.0:
+; AVX-NEXT:    vpsravd %xmm1, %xmm0, %xmm0
+; AVX-NEXT:    retq
+  %1 = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %y, <4 x i32> <i32 31, i32 31, i32 31, i32 31>)
+  %2 = ashr <4 x i32> %x, %1
+  ret <4 x i32> %2
+}
+
+define <4 x i64> @combine_vec64_ashr_out_of_bound(<4 x i64> %x, <4 x i64> %y) {
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:672]: vec64 -> v4i64

File: llvm/test/CodeGen/X86/combine-sra.ll [hunk 11]
```diff
@@ -521,3 +521,278 @@ define <4 x i32> @combine_vec_ashr_positive_splat(<4 x i32> %x, <4 x i32> %y) {
...
+; AVX2-NEXT:    vpxor %ymm2, %ymm0, %ymm0
+; AVX2-NEXT:    vpsubq %ymm2, %ymm0, %ymm0
+; AVX2-NEXT:    retq
+;
+; AVX512-LABEL: combine_vec64_ashr_out_of_bound:
+; AVX512:       # %bb.0:
+; AVX512-NEXT:    vpminuq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm1, %ymm1
+; AVX512-NEXT:    vpsravq %ymm1, %ymm0, %ymm0
+; AVX512-NEXT:    retq
+  %1 = tail call <4 x i64> @llvm.umin.v4i64(<4 x i64> %y, <4 x i64> <i64 31, i64 31, i64 31, i64 31>)
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/combine-sra.ll:795]: why 31?

**Review by RKSimon — COMMENTED** [review]
A few more comments, but this is ready to move from draft to general review

File: llvm/test/CodeGen/X86/combine-sra.ll (hunk 7 above)
Comment (SahilPatidar) [reply llvm/test/CodeGen/X86/combine-sra.ll:610]: I am sorry I didn't see it need to be 15

Comment (SahilPatidar) [reply llvm/test/CodeGen/X86/combine-sra.ll:610]: and also it need to be changed v4i16 -> v8i16?

**Review by RKSimon — COMMENTED** [review]
one final comment

**Review by RKSimon — APPROVED** [review]
LGTM
