### PR TITLE
[Clang][Comments] Allow HTML tags across multiple lines

### LINKED ISSUE #28321: -Wdocumentation gives warnings on HTML tags split across multiple lines, when Doxygen does not
|  |  |
| --- | --- |
| Bugzilla Link | [27947](https://llvm.org/bz27947) |
| Version | 3.8 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mordante |

## Extended Description 
The following code is parsed fine by Doxygen and correctly rendered as a hyperlink without any warnings - but -Wdocumentation gives a warning.

$ cat test.c
/**
 * <a
 * href="http://example.com/">test</a>
 */
int main(void) {
    return 0;
}
$ clang -Werror=documentation test.c
test.c:3:2: error: HTML start tag prematurely ended, expected attribute name or '>' [-Werror,-Wdocumentation]
 * href="http://example.com/">test</a>
 ^
test.c:2:5: note: HTML tag started here
 * <a
    ^
1 error generated.
$ clang --version
clang version 3.8.0-2ubuntu3 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### PR DESCRIPTION
**Pull request by Nerixyz**
HTML starting tags that span multiple lines were previously not allowed (or rather, only the starting line was lexed as HTML). Doxygen allows those tags.

This PR allows the starting tags to span multiple lines. They can't span multiple (C-)Comments, though (it's likely a user-error). Multiple BCPL comments are fine as those are single lines (shown below).

Example:

```c
/// <a
///     href="foo"
/// >Aaa</a>b
int Test;
```

Fixes #28321.

### CODE REVIEW

File: clang/unittests/AST/CommentLexer.cpp [hunk 1]
```diff
@@ -1453,6 +1453,129 @@ TEST_F(CommentLexerTest, HTML19) {
   ASSERT_EQ(tok::newline,      Toks[2].getKind());
 }
 
+TEST_F(CommentLexerTest, HTML20) {
```
Comment (cor3ntin) [inline clang/unittests/AST/CommentLexer.cpp:1456]: can we add tests for 
```<
a
>
```
To make sure we don;t do something unreasonable - even though it's not a valid tag?

**Review by AaronBallman — COMMENTED** [review]
Please be sure to also add a release note to `clang/docs/ReleaseNotes.rst` so users know about the fix. In principle, the changes LGTM but I do wonder if this is a part of the compiler that could benefit from some fuzzing to help shake out parsing issues.

**Comment by Nerixyz** [comment]
> but I do wonder if this is a part of the compiler that could benefit from some fuzzing to help shake out parsing issues.

That's probably a good idea. I'm not sure how fuzzing works in Clang. At least having `-Wdocumentation` on while fuzzing would be good (assuming the fuzzer generates comments).

---

One thing that's still missing from comment parsing is the ability to skip HTML comments (`<!-- ... -->`). I could make a followup PR for this.

**Comment by Nerixyz** [comment]
Ping - This is done from my end, the fuzzer and parsing for `<!-- -->` can be done in followup PRs.

**Review by AaronBallman — APPROVED** [review]
LGTM!
