### PR TITLE
[clang-tidy] Fix erroneous warning to make deleted function public

### LINKED ISSUE #54276: `modernize-use-equals-delete` should not warn if all other function declarations are private
`modernize-use-equals-delete` warns that deleted member functions should be public, even when all other member function declarations aren't.
```
class S {
    void do_stuff(int);
    void do_stuff(long) = delete; // modernize-use-equals-delete warns here

protected:
    void do_other_stuff(int);
    void do_other_stuff(long) = delete; // and here
};
```
https://godbolt.org/z/YGojEGa1s

### LINKED ISSUE #135249: modernize-use-equals-delete should recommend relocating only special members to public
From [the doc](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-equals-delete.html) as of v21.0.0), `modernize-use-equals-delete`:

> Identifies unimplemented private special member functions, and recommends using = delete for them.

This is great. It then goes on:

> Additionally, it recommends relocating any deleted member function from the private to the public section.

This is great for special member functions. It's not so great for non-special member functions. I think it would be better if that read (and the behavior was):

_Additionally, it recommends relocating any deleted **special** member function from the private to the public section._

The primary use of `= delete` is for special member functions. We can use it to disable copy and move support on a class. The copyability and moveability of a class is inherently part of the public interface of a class. It makes sense to me for copy and move constructors and assignment operators to be deleted in the public section of a class. The check gets this right.

But `= delete` has additional uses. It is a very useful way to "override" the C++ overload selection, implicit conversion, and binding rules. On the latter point, it helps us guard against lifetime problems when binding to const-reference function parameters. The clang-tidy check [`return-const-ref-from-parameter`](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/return-const-ref-from-parameter.html) mentions the use of `= delete` for this.

In these use cases, in my opinion, it makes code far more readable if overloads are grouped together, regardless of whether they are deleted or not. The `modernize-use-equals-delete` check recommends moving deleted overloads of private functions to the `public` section of a class, while the undeleted overloads remain `private`. This feels like overreach. I think the check does this because it is motivated to modernize the pattern of suppressing special member functions, and moving these to the `public` section is the right thing to do for special member functions, not because it's the right thing in other use cases.

```cpp
class Foo
{
 public:
  // Skipped

 private:
  const Bar& validate_bar_(const Bar&);
  // Prevent calling the function, above, with an expiring value.
  const Bar& validate_bar_(Bar&&) = delete; // This should remain private, alongside other overloads
};
```

Related issue: https://github.com/llvm/llvm-project/issues/54276

### PR DESCRIPTION
**Pull request by jwidauer**
This PR fixes #54276 and fixes #135249 by only matching private deleted functions with a public overload or special member functions.
Please let me know if there's a better way one could do this!

### CODE REVIEW

File: clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp [hunk 1]
```diff
@@ -39,6 +40,21 @@ AST_MATCHER(CXXMethodDecl, isSpecialFunction) {
...
+
+  if (LookupResult.isSingleResult())
+    return false; // No overloads
+
+  auto IsPublicOverload = [](const Decl *Overload) {
+    return isa<CXXMethodDecl>(Overload) && Overload->getAccess() == AS_public;
+  };
+
+  return std::any_of(LookupResult.begin(), LookupResult.end(),
+                     IsPublicOverload);
```
Comment (localspook) [inline clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp]:
```suggestion
  return llvm::any_of(LookupResult, IsPublicOverload);
```

**Review by localspook — COMMENTED** [review]
Overall, this looks good!

I believe this also fixes #135249.

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-equals-delete.cpp [hunk 2]
```diff
@@ -219,3 +219,20 @@ namespace PR33759 {
...
+    private:
+      void foo(int) = delete;
+      // CHECK-MESSAGES: :[[@LINE-1]]:12: warning: deleted member function should be public [modernize-use-equals-delete]
+  };
+
+  class PrivateDeletedFunctionWithPrivateOverload {
+    private:
+      void foo() {}
+      void foo(int) = delete;
+  };
```
[the remark this answers is not in the document]
Comment (jwidauer) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-equals-delete.cpp]: Yeah, it did feel kinda dirty to do, tbh!
Would you want me to remove it and also remove it in the namespace above as well?

File: clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp [hunk 3]
```diff
@@ -39,6 +40,21 @@ AST_MATCHER(CXXMethodDecl, isSpecialFunction) {
...
 }
+
+AST_MATCHER(CXXMethodDecl, hasPublicOverload) {
+  const DeclContext::lookup_result LookupResult =
+      Node.getParent()->lookup(Node.getNameInfo().getName());
+
+  if (LookupResult.isSingleResult())
+    return false; // No overloads
+
+  auto IsPublicOverload = [](const Decl *Overload) {
```
[the remark this answers is not in the document]
Comment (jwidauer) [reply clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp]: Nice! Good idea! Thanks!

File: clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp [hunk 4]
```diff
@@ -39,6 +39,22 @@ AST_MATCHER(CXXMethodDecl, isSpecialFunction) {
...
+AST_MATCHER(CXXMethodDecl, hasPublicOverload) {
+  const DeclContext::lookup_result LookupResult =
+      Node.getParent()->lookup(Node.getNameInfo().getName());
+
+  if (LookupResult.isSingleResult())
+    return false; // No overloads
+
+  static constexpr auto IsPublicOverload = [](const Decl *Overload) {
+    return (isa<CXXMethodDecl>(Overload) ||
+            isa<FunctionTemplateDecl>(Overload)) &&
```
Comment (localspook) [inline clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp]:
```suggestion
    return isa<CXXMethodDecl, FunctionTemplateDecl>(Overload) &&
```

**Review by localspook — APPROVED** [review]
One nit, otherwise LGTM (as long as tests are fixed of course)

**Review by zeyi2 — APPROVED** [review]
After fixing the alphabetical order in Release Notes, LGTM :)

File: clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp (hunk 4 above)
Comment (jwidauer) [reply clang-tools-extra/clang-tidy/modernize/UseEqualsDeleteCheck.cpp]: Ah yeah, forgot about that! Thanks! Done!

**Comment by jwidauer** [comment]
> I'll give this a couple days if anyone else has comments, then merge it.
> 
> Also, I've edited the description to add "fixes #135249", since I do believe this PR is a solution to it. If others disagree, do say so.

Sure thing! Thanks a bunch for the quick and nice review!
Let me know if there's anything you need me to do before merging!
