### PR TITLE
[Coroutines] properly update CallGraph in CoroSplit

### LINKED ISSUE #107139: "Invalidated the current SCC" assertion failure after #79712
For the source file in https://gist.github.com/smeenai/fcd14380467e813a28f1ef8c5484b775 (reduced from a large example that uses libunifex; it's probably possible to reduce this further but I'm not at all familiar with coroutines), the following command succeeds with Clang 18 but fails with Clang 19 and trunk:

```
$ clang -c -o /dev/null coroutine_crash.cpp -std=c++20 -w
clang: llvm/lib/Analysis/CGSCCPassManager.cpp:1167: LazyCallGraph::SCC &updateCGAndAnalysisManagerForPass(llvm::LazyCallGraph &, LazyCallGraph::SCC &, LazyCallGraph::Node &, llvm::CGSCCAnalysisManager &, llvm::CGSCCUpdateResult &, llvm::FunctionAnalysisManager &, bool): Assertion `!UR.InvalidatedSCCs.count(C) && "Invalidated the current SCC!"' failed.
```

I bisected this to #79712. CC @fpasserby, @ChuanqiXu9, and @yuxuanchen1997

### PR DESCRIPTION
**Pull request by yuxuanchen1997**
Fixes https://github.com/llvm/llvm-project/issues/107139.

We weren't updating the call graph properly in CoroSplit. This crash is due to the await_suspend() function calling the coroutine, forming a multi-node SCC. The issue bisected to https://github.com/llvm/llvm-project/pull/79712 but I think this is red herring. We haven't been properly updating the call graph. 

Added an example of such code as a test case.

### CODE REVIEW

File: llvm/lib/Transforms/Coroutines/CoroSplit.cpp [hunk 1]
```diff
@@ -2080,12 +2080,13 @@ splitCoroutine(Function &F, SmallVectorImpl<Function *> &Clones,
   return Shape;
 }
 
-static void updateCallGraphAfterCoroutineSplit(
+static LazyCallGraph::SCC &updateCallGraphAfterCoroutineSplit(
     LazyCallGraph::Node &N, const coro::Shape &Shape,
     const SmallVectorImpl<Function *> &Clones, LazyCallGraph::SCC &C,
     LazyCallGraph &CG, CGSCCAnalysisManager &AM, CGSCCUpdateResult &UR,
     FunctionAnalysisManager &FAM) {
```
Comment (ChuanqiXu9) [inline llvm/lib/Transforms/Coroutines/CoroSplit.cpp:2087]: nit: the signature is slightly odd to me. It looks better to make it the below `CurrentSCC` to be an output parameter of the function. So that we can avoid the odd the pattern

**Review by ChuanqiXu9 — APPROVED** [review]

File: llvm/lib/Transforms/Coroutines/CoroSplit.cpp (hunk 1 above)
Comment (yuxuanchen1997) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp:2087]: Actually, I can't. It's not just to keep it consistent with the semantics of `updateCGAndAnalysisManagerForCGSCCPass`. The `LazyCallGraph::SCC &C` is an lvalue ref and cannot be rebound. If I do `C = update...` it will invoke the Move Assignment operator for `LazyCallGraph::SCC`. Not sure the consequence will be intended. 

My other option is to make this input a `LazyCallGraph::SCC **` or `LazyCallGraph::SCC *&`, which is also not very obvious.

Comment (ChuanqiXu9) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp:2087]: Can't we make the type of  `C` to `LazyCallGraph::SCC *&`?

Comment (TylerNowicki) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp:2087]: I noted that the signature is actually very similar to LLVM's updateCGAndAnalysisManagerForPass() signature. Perhaps it is better to be consistent with that? https://llvm.org/doxygen/CGSCCPassManager_8cpp.html#a490117b63072462d035a6933fdb94c1f

Comment (yuxuanchen1997) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp]: > I noted that the signature is actually very similar to LLVM's updateCGAndAnalysisManagerForPass() signature. Perhaps it is better to be consistent with that? https://llvm.org/doxygen/CGSCCPassManager_8cpp.html#a490117b63072462d035a6933fdb94c1f

Perhaps. Or perhaps the answer is to rewrite `updateCGAndAnalysisManagerForPass`. I really don't like the current semantics. I will see what I can do in another patch.

Comment (yuxuanchen1997) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp]: @ChuanqiXu9 I am reverting this suggestion for now. We can do a refactor to change all `updateCGAndAnalysisManagerFor(Function|CGSCC)?Pass` usage once we decide on a new design.

Comment (yuxuanchen1997) [reply llvm/lib/Transforms/Coroutines/CoroSplit.cpp:2087]:
```
$ rg "updateCGAndAnalysisManagerFor(Function|CGSCC)?Pass"
llvm/unittests/Analysis/CGSCCPassManagerTest.cpp
1212:            updateCGAndAnalysisManagerForFunctionPass(CG, C, H2N, AM, UR, FAM);
1258:            updateCGAndAnalysisManagerForFunctionPass(CG, C, H2N, AM, UR, FAM);
1370:            updateCGAndAnalysisManagerForCGSCCPass(CG, C, H2N, AM, UR, FAM));
1407:        updateCGAndAnalysisManagerForFunctionPass(CG, C, H2N, AM, UR, FAM),
1438:            updateCGAndAnalysisManagerForCGSCCPass(CG, C, FN, AM, UR, FAM));
1469:        updateCGAndAnalysisManagerForFunctionPass(CG, C, FN, AM, UR, FAM),
1508:            updateCGAndAnalysisManagerForCGSCCPass(CG, C, FN, AM, UR, FAM));
1545:    ASSERT_DEATH(updateCGAndAnalysisManagerForCGSCCPass(CG, C, FN, AM, UR, FAM),
1777:              updateCGAndAnalysisManagerForCGSCCPass(CG, C, *N, AM, UR, FAM))
1867:          updateCGAndAnalysisManagerForCGSCCPass(CG, C, *N, AM, UR, FAM))
1923:        // Check that updateCGAndAnalysisManagerForCGSCCPass() after
1925:        updateCGAndAnalysisManagerForCGSCCPass(CG, *CG.lookupSCC(*N1), *N1, AM,
1987:          updateCGAndAnalysisManagerForCGSCCPass(CG, C, *N, AM, UR, FAM))

llvm/lib/Transforms/Utils/CallGraphUpdater.cpp
68:    updateCGAndAnalysisManagerForCGSCCPass(*LCG, *C, N, *AM, *UR, *FAM);

llvm/lib/Transforms/IPO/Inliner.cpp
497:    C = &updateCGAndAnalysisManagerForCGSCCPass(CG, *C, N, AM, UR, FAM);

llvm/lib/Transforms/Coroutines/CoroSplit.cpp
2108:    updateCGAndAnalysisManagerForCGSCCPass(CG, C, N, AM, UR, FAM);
2114:  updateCGAndAnalysisManagerForFunctionPass(CG, C, N, AM, UR, FAM);

llvm/lib/Analysis/CGSCCPassManager.cpp
561:      CurrentC = &updateCGAndAnalysisManagerForFunctionPass(CG, *CurrentC, *N,
876:static LazyCallGraph::SCC &updateCGAndAnalysisManagerForPass(
925:        // promoted before updateCGAndAnalysisManagerForPass runs.
1178:LazyCallGraph::SCC &llvm::updateCGAndAnalysisManagerForFunctionPass(
1182:  return updateCGAndAnalysisManagerForPass(G, InitialC, N, AM, UR, FAM,
1185:LazyCallGraph::SCC &llvm::updateCGAndAnalysisManagerForCGSCCPass(
1189:  return updateCGAndAnalysisManagerForPass(G, InitialC, N, AM, UR, FAM,

llvm/include/llvm/Analysis/CGSCCPassManager.h
419:LazyCallGraph::SCC &updateCGAndAnalysisManagerForFunctionPass(
430:LazyCallGraph::SCC &updateCGAndAnalysisManagerForCGSCCPass(
```
This is manageable refactoring I'd say. Let's do this in a separate patch.
