### PR TITLE
[MachineLICM] Recognize registers clobbered at EH landing pad entry

### LINKED ISSUE #122315: [MachineLICM] Wrong codegen post-RA due to ignored EH landing pad clobbers
Compiling the following test case on SystemZ:

```
declare i64 @personality(i64, i64, i64, ptr, ptr)
declare void @callee(i64, i64, i64, i64, i64)
declare void @panic()

define void @test() uwtable personality ptr @personality {
start:
  br label %bb1

bb1:
  call void @callee(i64 0, i64 0, i64 0, i64 0, i64 0)
  invoke void @panic()
          to label %bb2 unwind label %bb3

bb2:
  ret void

bb3:
  %lp = landingpad { ptr, i32 }
          catch ptr null
  br label %bb1
}
```

results in:

```
        stmg    %r6, %r15, 48(%r15)
        aghi    %r15, -160
        lghi    %r6, 0
.LBB0_1:                                # %bb1
                                        # =>This Inner Loop Header: Depth=1
        lghi    %r2, 0
        lghi    %r3, 0
        lghi    %r4, 0
        lghi    %r5, 0
        brasl   %r14, callee@PLT
.Ltmp0:
        brasl   %r14, panic@PLT
.Ltmp1:
        j       .LBB0_3
.LBB0_2:                                # %bb3
                                        #   in Loop: Header=BB0_1 Depth=1
.Ltmp2:
        j       .LBB0_1
.LBB0_3:                                # %bb2
        lmg     %r6, %r15, 208(%r15)
        br      %r14
```

The problem is that the initalization of `%r6` was pulled out of the loop.  However, the loop includes a path where the `panic` routine throws, and the exception is caught at `.Ltmp2`.  At this point the register `%r6` was clobbered by unwind library code - it is used as the "exception pointer register".

Looking at `MachineLICMImpl::HoistRegionPostRA`, there is special code to handle "funclet entry block" by acknowledging they'll implicitly clobber some registers:
```
    // Funclet entry blocks will clobber all registers
    if (const uint32_t *Mask = BB->getBeginClobberMask(TRI))
      applyBitsNotInRegMaskToRegUnitsMask(*TRI, RUClobbers, Mask);
```

However, this does not handle Linux-style EH landing pad blocks.

If I add the following code immediately after the above:
```
    // EH landing pads clobber exception pointer/selector registers
    if (BB->isEHPad()) {
      const MachineFunction &MF = *BB->getParent();
      if (MF.getFunction().hasPersonalityFn()) {
        auto PersonalityFn = MF.getFunction().getPersonalityFn();
        const TargetLowering &TLI = *MF.getSubtarget().getTargetLowering();
        if (unsigned Reg = TLI.getExceptionPointerRegister(PersonalityFn))
          for (MCRegUnitIterator RUI(Reg, TRI); RUI.isValid(); ++RUI)
            RUClobbers.set(*RUI);
        if (unsigned Reg = TLI.getExceptionSelectorRegister(PersonalityFn))
          for (MCRegUnitIterator RUI(Reg, TRI); RUI.isValid(); ++RUI)
            RUClobbers.set(*RUI);
      }
    }
```

the problem disappears.  Not sure if this is the best fix - maybe this case should be considered inside `getBeginClobberMask` in the first place?

### PR DESCRIPTION
**Pull request by uweigand**
EH landing pad entry implicitly clobbers target-specific exception pointer and exception selector registers.  The post-RA MachineLICM pass needs to take these into account when deciding whether to hoist an instruction out of the loop that initializes one of these registers.

Fixes: https://github.com/llvm/llvm-project/issues/122315

### CODE REVIEW

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 1]
```diff
@@ -639,6 +639,21 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
...
+        auto PersonalityFn = MF.getFunction().getPersonalityFn();
+        const TargetLowering &TLI = *MF.getSubtarget().getTargetLowering();
+        if (unsigned Reg = TLI.getExceptionPointerRegister(PersonalityFn))
+          for (MCRegUnitIterator RUI(Reg, TRI); RUI.isValid(); ++RUI)
+            RUClobbers.set(*RUI);
+        if (unsigned Reg = TLI.getExceptionSelectorRegister(PersonalityFn))
+          for (MCRegUnitIterator RUI(Reg, TRI); RUI.isValid(); ++RUI)
+            RUClobbers.set(*RUI);
+      }
+    }
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineLICM.cpp:655]: This is the wrong place for this. This pass is already inventing its own liveness tracking instead of LiveRegUnits, which it should be using.

Why is this case special? Are these not reserved and/or callee saved?

Comment (uweigand) [reply llvm/lib/CodeGen/MachineLICM.cpp:655]: They are not reserved, but they are callee saved.  That's why they're considered candidates to be hoisted even though there's a call in the loop.  And normally that would be fine except for the special EH landing pad case.

I'm not sure where else these should be handled, I simply noticed that several other places also handle these registers specially.

Comment (s-barannikov) [reply llvm/lib/CodeGen/MachineLICM.cpp:655]: This should be just
```
    if (BB->isEHPad()) {
      if (const uint32_t *Mask =
              TRI->getCustomEHPadPreservedMask(*BB->getParent()))
        applyBitsNotInRegMaskToRegUnitsMask(*TRI, RUClobbers, Mask);
    }
```

Note however that this only partly addresses the issue. The `continue` at the beginning of the loop is wrong because it results in un-analyzed instructions. If an inner loop had a register def/clobber, it won't be taken into account by the loop over Candidates below.

I've been debugging a similar issue for quite some time now, but I'm struggling to reproduce it on an upstream target =\

Comment (s-barannikov) [reply llvm/lib/CodeGen/MachineLICM.cpp:655]: > Should this be just

Please ignore this. It appears this method only needs to be implemented if the unwinder clobbers registers other than exception pointer/selector. DWARF exception handling would usually preserve those other registers.

That said, it *should* be queried by LICM, but it is a different issue.

Comment (s-barannikov) [reply llvm/lib/CodeGen/MachineLICM.cpp:655]: I wonder whether `livein_iterator` (used just above) should take care of these registers implicitly like `liveout_iterator` does
https://github.com/llvm/llvm-project/blob/66f158d91803875de63d8f2a437ce8ecb22c4141/llvm/include/llvm/CodeGen/MachineBasicBlock.h#L550-L559

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 2]
```diff
@@ -639,6 +639,21 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
     if (const uint32_t *Mask = BB->getBeginClobberMask(TRI))
       applyBitsNotInRegMaskToRegUnitsMask(*TRI, RUClobbers, Mask);
 
+    // EH landing pads clobber exception pointer/selector registers
+    if (BB->isEHPad()) {
+      const MachineFunction &MF = *BB->getParent();
+      if (MF.getFunction().hasPersonalityFn()) {
+        auto PersonalityFn = MF.getFunction().getPersonalityFn();
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineLICM.cpp:646]: no auto

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 3]
```diff
@@ -639,6 +639,21 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
...
+        const TargetLowering &TLI = *MF.getSubtarget().getTargetLowering();
+        if (unsigned Reg = TLI.getExceptionPointerRegister(PersonalityFn))
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineLICM.cpp:648]: Use MCRegister

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 4]
```diff
@@ -639,6 +639,21 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
     if (const uint32_t *Mask = BB->getBeginClobberMask(TRI))
       applyBitsNotInRegMaskToRegUnitsMask(*TRI, RUClobbers, Mask);
 
+    // EH landing pads clobber exception pointer/selector registers
+    if (BB->isEHPad()) {
+      const MachineFunction &MF = *BB->getParent();
+      if (MF.getFunction().hasPersonalityFn()) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineLICM.cpp:645]: Does the verifier not enforce there must be a personality function if there is an EH pad?

Comment (uweigand) [reply llvm/lib/CodeGen/MachineLICM.cpp]: Indeed it does, thanks!  Patch updated.

File: llvm/lib/CodeGen/MachineLICM.cpp (hunk 1 above)
Comment (s-barannikov) [reply llvm/lib/CodeGen/MachineLICM.cpp]: Thanks, that makes sense to me now.

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 5]
```diff
@@ -639,6 +639,19 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
     if (const uint32_t *Mask = BB->getBeginClobberMask(TRI))
       applyBitsNotInRegMaskToRegUnitsMask(*TRI, RUClobbers, Mask);
 
+    // EH landing pads clobber exception pointer/selector registers
```
Comment (s-barannikov) [inline llvm/lib/CodeGen/MachineLICM.cpp:642]:
```suggestion
    // EH landing pads clobber exception pointer/selector registers.
```

File: llvm/lib/CodeGen/MachineLICM.cpp [hunk 6]
```diff
@@ -639,6 +639,19 @@ void MachineLICMImpl::HoistRegionPostRA(MachineLoop *CurLoop,
...
+    if (BB->isEHPad()) {
+      const MachineFunction &MF = *BB->getParent();
+      const Constant *PersonalityFn = MF.getFunction().getPersonalityFn();
+      const TargetLowering &TLI = *MF.getSubtarget().getTargetLowering();
+      if (MCRegister Reg = TLI.getExceptionPointerRegister(PersonalityFn))
+        for (MCRegUnitIterator RUI(Reg, TRI); RUI.isValid(); ++RUI)
+          RUClobbers.set(*RUI);
```
Comment (s-barannikov) [inline llvm/lib/CodeGen/MachineLICM.cpp:649]: Here and below:
```suggestion
        for (MCRegUnit Unit : TRI->regunits(Reg))
          RUClobbers.set(Unit);
```

**Review by s-barannikov — APPROVED** [review]
LGTM with a suggestion

File: llvm/lib/CodeGen/MachineLICM.cpp (hunk 6 above)
Comment (uweigand) [reply llvm/lib/CodeGen/MachineLICM.cpp]: Done, thanks!
