### PR TITLE
[llvm-objcopy] Always update indirectsymoff in MachO

### LINKED ISSUE #117723: Artificial MachO binary processed by llvm-objcopy/strip is not accepted by codesign
## Symptom

Artificial MachO binary processed by llvm-objcopy/strip is not accepted by codesign.

codesign fails with error:

> main executable failed strict validation

## Investigation
According to [Darling/libsecurity_utilities/lib/macho++.cpp](https://github.com/darlinghq/darling-security/blob/9bba1c54a75a30ba826e2ff07f17e64c5c0fdf98/OSX/libsecurity_utilities/lib/macho%2B%2B.cpp)

```
libsecurity_utilities/lib/macho++.cpp|238 col 3| mSuspicious = true;
libsecurity_utilities/lib/macho++.cpp|617 col 7| mSuspicious = true;
libsecurity_utilities/lib/macho++.cpp|629 col 7| mSuspicious = true;
libsecurity_utilities/lib/macho++.cpp|635 col 8| mSuspicious = true;
libsecurity_utilities/lib/macho++.cpp|643 col 6| mSuspicious = true;
libsecurity_utilities/lib/macho++.cpp|654 col 5| mSuspicious = true;
```

According to `MachO::validateStructure`

1. The sum of the last `LoadCommand` and its size must equal to the total size of "fat" component,
which sometimes corresponds to the end of file.

According to `Universal::Universal`

1. Alignment of "fat" components must be less than 2^30, and
2. The gap size between "fat" components must be less than its alignment.
3. The gap must be filled with zero bytes.
4. No junk shall be past end of file or "fat" component.

### Relevant requirement

From the above there should be no data in MachO past contents of a load command with the largest `offset+size`.

## Problem description

`llvm-objcopy` does not update `indirectsymoff` field if the resulting `IndirectSymTable` (after stripping) is empty [1]. As a result `indirectsymoff` keeps old value, which is garbage, and can point past `offset+size` of the last load command. As a result `totalSize()` returns size that is larger than the actual stripped MachO [2].

This clearly violates one of the checks mentioned above (there are zero-bytes filled past `offset+size` of the last load command.

- [1] https://github.com/llvm/llvm-project/blob/ec41462d7a7d2fcd74dcf1c60218f134fcfd55b2/llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp#L364-L368
- [2] https://github.com/llvm/llvm-project/blob/ec41462d7a7d2fcd74dcf1c60218f134fcfd55b2/llvm/lib/ObjCopy/MachO/MachOWriter.cpp#L92-L94

### PR DESCRIPTION
**Pull request by ridzenis**
Let's say we've run llvm-strip over some MachO. The resulting MachO became smaller and there are no indirect symbols anymore.

Then according to previous code we would not update indirectsymoff field. This would lead to `MachOWriter::totalSize()` report size that is larger than the new MachO. As a result we would get MachO that has zero bytes past contents of the very last load command.

Codesign has a strict check that size of MachO file must be equal to

    lastLoadCommand.offset + lastLoadCommand.size

If this is not satisfied codesign reports the following error

    main executable failed strict validation

Fixes #117723

### CODE REVIEW

File: llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp [hunk 1]
```diff
@@ -361,11 +361,10 @@ Error MachOLayoutBuilder::layoutTail(uint64_t Offset) {
...
 
-      if (!O.IndirectSymTable.Symbols.empty()) {
-        MLC.dysymtab_command_data.indirectsymoff = StartOfIndirectSymbols;
-        MLC.dysymtab_command_data.nindirectsyms =
-            O.IndirectSymTable.Symbols.size();
-      }
+      MLC.dysymtab_command_data.nindirectsyms =
+          O.IndirectSymTable.Symbols.size();
+      MLC.dysymtab_command_data.indirectsymoff =
+          O.IndirectSymTable.Symbols.empty() ? 0 : StartOfIndirectSymbols;
```
Comment (compnerd) [inline llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp:367]: Why the reordering here? (not that it matters).

**Review by compnerd — COMMENTED** [review]
Please add a test case for a binary that has 0 and >0 indirect symbols.

**Comment by RIscRIpt** [comment]
> Please add/update a test case to cover this behaviour.

I find it difficult generating a MachO reliably so that all the nuances are preserved to observe the desired effect.

I try to investigate how to craft such MachO if reviewers think I should add a regression test.

> Please could you add some reviewers who have been involved in modifying the Mach-O code in llvm-objcopy, either officially as reviewers, or by pinging them in the comments, depending on whether you have commit access or not.

As far as I can see @nuta who was the author of this file was not contributing to llvm-project lately (as per `git log --author=nuta`), so I've added people who were reviewing his changes.

File: llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp (hunk 1 above)
Comment (RIscRIpt) [reply llvm/lib/ObjCopy/MachO/MachOLayoutBuilder.cpp:367]: I thought to use `MLC.dysymtab_command_data.nindirectsyms` instead of `O.IndirectSymTable.Symbols.empty()` when I wrote the code initially.

I will change the ordering back.

**Comment by compnerd** [comment]
> I find it difficult generating a MachO reliably so that all the nuances are preserved to observe the desired effect.

Take a look at obj2yaml - that will allow you to generate the code once and then trim down the MachO binary to the shape that we need for the test.

> I try to investigate how to craft such MachO if reviewers think I should add a regression test.

Yes, please add the regression tests for this.

**Comment by alexander-shaposhnikov** [comment]
Thanks for the fix, i second @compnerd's suggestions

**Comment by RIscRIpt** [comment]
> Take a look at obj2yaml - that will allow you to generate the code once and then trim down the MachO binary to the shape that we need for the test.

I didn't know `yaml2obj` exists, thanks!

> Yes, please add the regression tests for this.

I've added a very small test, please see if it's enough.

**Review by compnerd — COMMENTED** [review]
Do you think it would be possible to add a test case where there are indirect symbols (or is there an existing test case for that?)

**Comment by RIscRIpt** [comment]
> Do you think it would be possible to add a test case where there are indirect symbols (or is there an existing test case for that?)

There are some:

```
❯ cd llvm/test/tools/llvm-objcopy/MachO
❯ rg "indirectsymoff:\\s*[1-9]"
linkedit-order-1.test
254:    indirectsymoff:  49424

Inputs/strip-all-with-codesignature.yaml
194:    indirectsymoff:  8424

linkedit-order-2.test
198:    indirectsymoff:  33000

symtbl-zero-indirectsymoff.test
39:    indirectsymoff:  42

remove-lc-index-update.test
194:    indirectsymoff:  8264

symbol-table.test
329:    indirectsymoff:  8480
```

File: llvm/test/tools/llvm-objcopy/MachO/symtbl-zero-indirectsymoff.test [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    iundefsym:       0
+    nundefsym:       0
+    tocoff:          0
+    ntoc:            0
+    modtaboff:       0
+    nmodtab:         0
+    extrefsymoff:    0
+    nextrefsyms:     0
+    indirectsymoff:  42
+    nindirectsyms:   0
```
Comment (compnerd) [inline llvm/test/tools/llvm-objcopy/MachO/symtbl-zero-indirectsymoff.test:40]: Should we also ensure that this field is cleared? The indirect symbol table itself is empty, the new value written here should indicate that.

Comment (RIscRIpt) [reply llvm/test/tools/llvm-objcopy/MachO/symtbl-zero-indirectsymoff.test]: That's a good idea! I should have thought about it myself. Thanks. I've added a check and I've updated comment in the header of the test.

Comment (RIscRIpt) [reply llvm/test/tools/llvm-objcopy/MachO/symtbl-zero-indirectsymoff.test]: I realized I should also set `nindirectsyms` to non-zero value. I am trying to come up with minimal changes that let this value be non-zero.

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@alexander-shaposhnikov - any additional feedback?

**Comment by RIscRIpt** [comment]
Many thanks for the review! If there would be no additional feedback, I'll merge it in a couple of days, when I have more time to be online in case of test failures in main.

**Review by alexander-shaposhnikov — APPROVED** [review]
LG
