### PR TITLE
[LV] Handle partial sub-reductions with sub in middle block.

### LINKED ISSUE #178703: Cost and register usage in some partial reductions doesn't match the generated instructions
If we consider these two functions:
```
int test1(int n, char *a, char *b) {
  int accum = 0;
  for (int i = 0; i < n; i++) {
    accum += a[i] * b[i];
  }
  return accum;
}

int test2(int n, char *a, char *b) {
  int accum = 0;
  for (int i = 0; i < n; i++) {
    accum -= a[i] * b[i];
  }
  return accum;
}
```
Compiling with ``clang --target=aarch64-none-elf -mcpu=neoverse-v1 -O3 -mllvm -force-vector-interleave=1`` the vector loops generated for these are
```
test1:
.LBB0_7:                                // %vector.body     
                                        // =>This Inner Loop Header: Depth=1  
        ldr     q1, [x12], #16                                                                       
        ldr     q2, [x13], #16                                                                                                                                                                             
        subs    x14, x14, #16                                                                        
        udot    v0.4s, v2.16b, v1.16b                                                                
        b.ne    .LBB0_7   

test2:
.LBB1_7:                                // %vector.body                                              
                                        // =>This Inner Loop Header: Depth=1                         
        ldr     q1, [x12], #16                                                                       
        ldr     q2, [x13], #16     
        subs    x14, x14, #16       
        umull2  v3.8h, v2.16b, v1.16b                                                                
        umull   v1.8h, v2.8b, v1.8b                                                                  
        usubw   v0.4s, v0.4s, v1.4h
        usubw2  v0.4s, v0.4s, v1.8h                                                                  
        usubw   v0.4s, v0.4s, v3.4h                                                                  
        usubw2  v0.4s, v0.4s, v3.8h                                                                  
        b.ne    .LBB1_7    
```
If you look at what's going on in the vectorizer with ``-mllvm -debug`` then it says
```
LV: Checking a loop in 'test1' from tmp.c
Cost of 1 for VF 16: EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32))
LV(REG): Calculating max register usage:
LV(REG): Scaled down VF from 8 to 2 for EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32))
LV(REG): Scaled down VF from 16 to 4 for EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32))

LV: Checking a loop in 'test2' from tmp.c
Cost of 1 for VF 16: EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (sub (0, mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32)))
LV(REG): Calculating max register usage:
LV(REG): Scaled down VF from 8 to 2 for EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (sub (0, mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32)))
LV(REG): Scaled down VF from 16 to 4 for EXPRESSION vp<%9> = ir<%accum.09> + partial.reduce.add (sub (0, mul nuw nsw (ir<%1> zext to i32), (ir<%0> zext to i32)))
```
It thinks that the cost of both reductions is the same, and that the relevant type in both for calculating register usage is v4i32 (which is the result type) so the register usage is 1. In test1 the reduction becomes a single udot instruction so this looks correct, but in test2 we get a sequence of 6 instructions and use one extra registers due to using an intermediate v16xi16 which gets split into two v8xi16. So both the cost and register usage are wrong.

### PR DESCRIPTION
**Pull request by sdesmalen-arm**
Sub-reductions can be implemented in two ways:
(1) negate the operand in the vector loop (the default way).
(2) subtract the reduced value from the init value in the middle block.

Note that both ways keep the reduction itself as an 'add' reduction,
which is necessary because only llvm.vector.partial.reduce.add exists.

The ISD nodes for partial reductions don't support folding the
sub/negation into its operands because the following is not a valid
transformation:
```
     sub(0, mul(ext(a), ext(b)))
  -> mul(ext(a), ext(sub(0, b)))
```
It can therefore be better to choose option (2) such that the partial
reduction is always positive (starting at '0') and to do a final
subtract in the middle block.

For AArch64 there are no dot-product instructions that can
do a `partial.reduce.sub(acc, mul(ext(a), ext(b)))` operation.
I'm not sure if such instructions exist for other targets.
(If so then we may want to make this decision a target option)

This PR also increases the AArch64 cost of a partial sub-reduction
when this exists in an 'add-sub' reduction chain.

Fixes https://github.com/llvm/llvm-project/issues/178703

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 1]
```diff
@@ -5828,7 +5833,46 @@ void VPlanTransforms::createPartialReductions(VPlan &Plan,
     }
   }
 
-  for (const auto &[_, Chains] : ChainsByPhi)
+  for (auto &[Phi, Chains] : ChainsByPhi) {
+    RecurKind RK = cast<VPReductionPHIRecipe>(Phi)->getRecurrenceKind();
+    bool IsTransformed = false;
     for (const VPPartialReductionChain &Chain : Chains)
-      transformToPartialReduction(Chain, Range, CostCtx, Plan);
+      IsTransformed |=
```
Comment (huntergr-arm) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Can we actually have a case where one chain is transformed and the other not for the same phi? Do you have a test for that?

Comment (sdesmalen-arm) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: Thanks, I'll fix this in a separate PR!

File: llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce-sub-sdot.ll [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+
+; CHECK: LV: Checking a loop in 'add_sub_chained_reduction'
+; CHECK: Cost of 1 for VF 16: EXPRESSION vp<{{.*}}> = ir<%acc> + partial.reduce.add (mul (ir<%load1> sext to i32), (ir<%load2> sext to i32))
+; CHECK: Cost of 9 for VF 16: EXPRESSION vp<{{.*}}> = vp<%9> + partial.reduce.add (sub (0, mul (ir<%load2> sext to i32), (ir<%load3> sext to i32)))
+
+target triple = "aarch64"
+
+; Test the cost of a SUB reduction, where the SUB is implemented outside the loop
+; and therefore not part of the partial reduction.
+define i32 @sub_reduction(ptr %arr1, ptr %arr2, i32 %init, i32 %n) #0 {
```
Comment (fhahn) [inline llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce-sub-sdot.ll]: can we also check the NEON costs? Not sure if that could be done easily by using different run lines with CPUs with and without SVE support?

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 3]
```diff
@@ -5828,7 +5833,46 @@ void VPlanTransforms::createPartialReductions(VPlan &Plan,
...
+    if (IsTransformed && !Range.isEmpty() && RK == RecurKind::Sub) {
+      // Update start value of PHI node.
+      auto *StartInst = cast<VPInstruction>(Phi->getStartValue());
+      assert(StartInst->getOpcode() == VPInstruction::ReductionStartVector);
+      VPValue *OldStartValue = StartInst->getOperand(0);
+      StartInst->setOperand(0, StartInst->getOperand(1));
+
+      // Replace reduction_result by 'sub (startval, reductionresult)'.
+      VPInstruction *RdxResult = vputils::findComputeReductionResult(Phi);
+      assert(RdxResult && "Could not find reduction result");
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: > transformToPartialReduction is called for each value in the partial reduction chain, where this only needs to happen once for the entire chain as a whole. What is the value of doing this in transformToPartialReduction?

The benefit would be to perform the transformation of the link together with the exit value. Could be done when transforming the phi node, where we already also update the reduction start value.

> This code updates the scalar ComputeReductionResult value from the (partially-reduced-vector -> scalar) reduction in the middle-block. I don't see how a VPlan-based sinking pass can help here?
Ah yes

File: llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp [hunk 4]
```diff
@@ -5615,6 +5616,40 @@ static bool transformToPartialReduction(const VPPartialReductionChain &Chain,
...
+      VPBuilder Builder = VPBuilder::getToInsertAfter(RdxResult);
+      constexpr unsigned SubOpc = Instruction::BinaryOps::Sub;
+      VPInstruction *NewResult = Builder.createNaryOp(
+          SubOpc, {OldStartValue, RdxResult},
+          VPIRFlags::getDefaultFlags(SubOpc), RdxPhi->getDebugLoc());
+      RdxResult->replaceUsesWithIf(
+          NewResult,
+          [&NewResult](VPUser &U, unsigned Idx) { return &U != NewResult; });
+    }
+  }
```
Comment (fhahn) [inline llvm/lib/Transforms/Vectorize/VPlanTransforms.cpp]: nit: could exit early to reduce indent level, same for handling the sub below.
```suggestion
  if (!IsLastInChain) 
  return true
  
    // Scale the PHI and ReductionStartVector by the VFScaleFactor
    assert(RdxPhi->getVFScaleFactor() == 1 && "scale factor must not be set");
    RdxPhi->setVFScaleFactor(ScaleFactor);

    auto *StartInst = cast<VPInstruction>(RdxPhi->getStartValue());
    assert(StartInst->getOpcode() == VPInstruction::ReductionStartVector);
    auto *NewScaleFactor = Plan.getConstantInt(32, ScaleFactor);
    StartInst->setOperand(2, NewScaleFactor);

    // If this is the last value in a sub-reduction chain, then update the PHI
    // node to start at `0` and update the reduction-result to subtract from
    // the PHI's start value.
    if (RK == RecurKind::Sub) {
      // Update start value of PHI node.
      VPValue *OldStartValue = StartInst->getOperand(0);
      StartInst->setOperand(0, StartInst->getOperand(1));

      // Replace reduction_result by 'sub (startval, reductionresult)'.
      VPInstruction *RdxResult = vputils::findComputeReductionResult(RdxPhi);
      assert(RdxResult && "Could not find reduction result");

      VPBuilder Builder = VPBuilder::getToInsertAfter(RdxResult);
      constexpr unsigned SubOpc = Instruction::BinaryOps::Sub;
      VPInstruction *NewResult = Builder.createNaryOp(
          SubOpc, {OldStartValue, RdxResult},
          VPIRFlags::getDefaultFlags(SubOpc), RdxPhi->getDebugLoc());
      RdxResult->replaceUsesWithIf(
          NewResult,
          [&NewResult](VPUser &U, unsigned Idx) { return &U != NewResult; });
    }
 
```

**Review by fhahn — APPROVED** [review]
LGTM, thanks

**Comment by aeubanks** [comment]
we're seeing test failures after this patch, which opt-bisect does bisect to loop-vectorize. it seems more like a miscompile than UB based on initial investigation, but still trying to get the IR out

**Comment by sdesmalen-arm** [comment]
Thanks for reporting! From a quick glance, it seems that for the vectorized epilogue loop the PHI value of the reduction doesn't start at `zeroinitializer`. I'll dig into it a bit further!
