### PR TITLE
[clang-format] Continue aligned lines better

### LINKED ISSUE #53497: [clang-format] AlignConsecutiveAssignments breaks formatting of continued functions
Related to #52772.

Given:
```
BasedOnStyle: LLVM
AlignConsecutiveAssignments: Consecutive
ColumnLimit: 50 # just for the ease of reproduce
```

The code:
```
auto b = f(aaaaaaaaaaaaaaaaaaaaaaaaa,
           ccc ? aaaaa : bbbbb,
           dddddddddddddddddddddddddd);
```
is formatted correctly.

However, this one, with alignment on the assignment:
```
auto aaaaaaaaaaaa = f();
auto b            = f(aaaaaaaaaaaaaaaaaaaaaaaaa,
           ccc ? aaaaa : bbbbb,
                      dddddddddddddddddddddddddd);
```
has its last line being aligned with the opening parenthesis.

Expected formatting (not sure about the indentation of the last two lines though):
```
auto aaaaaaaaaaaa = f();
auto b            = f(aaaaaaaaaaaaaaaaaaaaaaaaa,
           ccc ? aaaaa : bbbbb,
           dddddddddddddddddddddddddd);
```

### LINKED ISSUE #56078: clang-format incorrect indent after `AlignConsecutiveAssignments` enabled
```c
int  abcdefghijk = 111; 
auto lambda      = [] { 
    int c = call(1,     
                      2, <--
                      3, <--
                      4) <--
};                      
```
the align of function params is incorrect if its outside lambda is aligned with `AlignConsecutiveAssignments`.

the code should be
```c
int  abcdefghijk = 111;  
auto lambda      = [] {  
    int c = call(1,      
                 2, 
                 3, 
                 4);
};                       
```

### PR DESCRIPTION
**Pull request by sstwcw**
Fixes #53497.

Fixes #56078.

after with config `{AlignConsecutiveAssignments: true}`

```C++
auto aaaaaaaaaaaaaaaaaaaaa = {};
auto b                     = [] {
  x = {.one_foooooooooooooooo = 2, //
       .two_fooooooooooooo    = 3, //
       .three_fooooooooooooo  = 4};
};

A B          = {"Hello "
                "World"};
BYTE payload = 2;

float i2 = 0;
auto v   = type{i2 = 1, //
                i  = 3};
```

before

```C++
auto aaaaaaaaaaaaaaaaaaaaa = {};
auto b                     = [] {
  x = {.one_foooooooooooooooo = 2, //
                           .two_fooooooooooooo    = 3, //
                           .three_fooooooooooooo  = 4};
};

A B          = {"Hello "
                         "World"};
BYTE payload = 2;

float i2 = 0;
auto v   = type{i2 = 1, //
              i  = 3};
```

When a line gets aligned, the following lines may need to move with it. This patch replaces the old algorithm with a simpler one.  It uses the `IsAligned` attribute.  It makes most of the scope stack irrelevant. Now the stack only needs to keep track of 2 levels.

The old algorithm had problems like these.

- Whether lines inside a braced list moved depended on whether there was a type at the start.  It should depend on whether the inside was aligned to the brace.  The first case that came up with a type name at the start happened to have a comma at the end of the list so the inside was not aligned to the brace.

- Excluding lines inside closures did not always work.

- A continued string could move twice as much as it should.

The following problems are not fixed yet.

A token that opens a scope is needed.  Operator precedence is not enough.

```C++
auto aaaaaaaaaaaaaaaaaaaaa = {};
auto b                     = 0 + //
         0;
```

The algorithm has trouble when things that should not move and things that should move are nested.  This is related to the `IsAligned` attribute being a boolean.  It also affects how spaces and tabs are selected.

```C++
auto aaaaaaaaaaaaaaaaaaaaa = {};
auto b                     = {.a = {
              .a = 0,
          }};
```

### CODE REVIEW

File: clang/lib/Format/WhitespaceManager.cpp [hunk 1]
```diff
@@ -349,104 +348,29 @@ AlignTokenSequence(const FormatStyle &Style, unsigned Start, unsigned End,
...
-
-        // Continued template parameter.
-        if (Changes[ScopeStart - 1].Tok->is(TT_TemplateOpener))
+        if (InsideNestedScope && CurrentChange.IsAligned)
           return true;
-
         return false;
       };
 
       if (ShouldShiftBeAdded())
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/WhitespaceManager.cpp:370]:
```suggestion
      if (ContinuedStringLiteral || (InsideNestedScope && CurrentChange.IsAligned))
```
Should this be further simplified?

**Review by HazardyKnusperkeks — APPROVED** [review]
Looks nice.

**Review by HazardyKnusperkeks — APPROVED** [review]
Everything is fine.
