### PR TITLE
[ThinLTO]Mark referencers of local ifunc not eligible for import

### LINKED ISSUE #58740: LTO + target_clones leads to undefined references
```console
tavianator@graphene $ clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
tavianator@graphene $ cat foo.c
int foo(void) {
        return 1;
}
tavianator@graphene $ cat bar.c
int foo(void);

__attribute__((target_clones("popcnt", "default")))
static int bar(void) {
        return foo();
}

int main(void) {
        return bar();
}
tavianator@graphene $ clang -O1 -flto -c foo.c -o foo.o
tavianator@graphene $ clang -O1 -flto -c bar.c -o bar.o
tavianator@graphene $ clang -O1 -flto foo.o bar.o -o baz
/usr/bin/ld: /tmp/lto-llvm-0ef63e.o: in function `bar.default.1':
ld-temp.o:(.text.bar.default.1+0x2): undefined reference to `foo'
/usr/bin/ld: /tmp/lto-llvm-0ef63e.o: in function `bar.popcnt.0':
ld-temp.o:(.text.bar.popcnt.0+0x2): undefined reference to `foo'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
If an ifunc has local linkage, do not add it into ref edges and mark its referencer (a function or global variable) not eligible for import. An ifunc doesn't have summary and ThinLTO cannot promote it. Importing the referencer may cause linkage errors.

To reference a similar fix, https://reviews.llvm.org/D158961 marks callers of local ifunc not eligible for import to fix https://github.com/llvm/llvm-project/issues/58740

### CODE REVIEW

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp [hunk 1]
```diff
@@ -88,16 +88,22 @@ extern cl::opt<unsigned> MaxNumVTableAnnotations;
...
-// global vars at all. When importing function we aren't interested if any
-// instruction in it takes an address of any basic block, because instruction
-// can only take an address of basic block located in the same function.
+//
+// Return true if any user references a block address, and sets
+// `RefLocalLinkageIFunc` to true if the analyzed value references local ifunc.
+// - If a local-linkage ifunc is referenced, the analyzed value is not eligible
+// for import.
+// - Additionally, global vars will be marked as not eligible to import if they
+// references references basic block address, because we can't import it
```
Comment (teresajohnson) [inline llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:97]: s/references references/reference a/

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp [hunk 2]
```diff
@@ -787,7 +804,9 @@ static void computeVariableSummary(ModuleSummaryIndex &Index,
                                    SmallVectorImpl<MDNode *> &Types) {
   SetVector<ValueInfo, std::vector<ValueInfo>> RefEdges;
   SmallPtrSet<const User *, 8> Visited;
-  bool HasBlockAddress = findRefEdges(Index, &V, RefEdges, Visited);
+  bool RefIFunc = false;
```
Comment (teresajohnson) [inline llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:807]: Suggest "RefLocalIFunc"

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp [hunk 3]
```diff
@@ -326,7 +343,7 @@ static void computeFunctionSummary(
 
   bool HasInlineAsmMaybeReferencingInternal = false;
   bool HasIndirBranchToBlockAddress = false;
-  bool HasIFuncCall = false;
```
Comment (teresajohnson) [inline llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:329]: Suggest "HasLocalIFuncCallOrRef" to be more explicit

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp [hunk 4]
```diff
@@ -88,16 +88,22 @@ extern cl::opt<unsigned> MaxNumVTableAnnotations;
...
-// Return true if any of the operands contains blockaddress. This is important
-// to know when computing summary for global var, because if global variable
-// references basic block address we can't import it separately from function
-// containing that basic block. For simplicity we currently don't import such
-// global vars at all. When importing function we aren't interested if any
-// instruction in it takes an address of any basic block, because instruction
-// can only take an address of basic block located in the same function.
+//
+// Return true if any user references a block address, and sets
+// `RefLocalLinkageIFunc` to true if the analyzed value references local ifunc.
```
Comment (teresajohnson) [inline llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:93]: Since the RefLocalLinkageIFunc doesn't affect the return value, I suggest leaving the original comment as is, but add a separate blurb below it about the new output parameter.

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp (hunk 1 above)
Comment (teresajohnson) [reply llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:97]: Ignore if you put the old comment block back as I suggest above.

File: llvm/lib/Analysis/ModuleSummaryAnalysis.cpp (hunk 2 above)
Comment (teresajohnson) [reply llvm/lib/Analysis/ModuleSummaryAnalysis.cpp:807]: Also, can you add this case to your new test? I think it is only testing the call case.

Comment (minglotus-6) [reply llvm/lib/Analysis/ModuleSummaryAnalysis.cpp]: Renamed and added `@var = constant { [1 x ptr] } { [1 x ptr] [ptr @callee]}` in the test.

**Review by mingmingl-llvm — COMMENTED** [review]
ptal, thanks!

**Review by teresajohnson — APPROVED** [review]

**Comment by minglotus-6** [comment]
The failed test is irrelevant

```
# After downloading logs from https://buildkite.com/llvm-project/github-pull-requests/builds/64747#018f8296-6cf1-497e-94ab-8a53cd351a8f

cat github-pull-requests_build_64747_linux-linux-x64.log | grep -B 10 -A 10 "Failed Tests"
bk;t=1715887562543[0.70s,0.80s) :: [                                        ] :: [  1/419]
bk;t=1715887562543[0.60s,0.70s) :: [                                        ] :: [  1/419]
bk;t=1715887562543[0.50s,0.60s) :: [                                        ] :: [  6/419]
bk;t=1715887562543[0.40s,0.50s) :: [                                        ] :: [  9/419]
bk;t=1715887562543[0.30s,0.40s) :: [**                                      ] :: [ 23/419]
bk;t=1715887562543[0.20s,0.30s) :: [*************                           ] :: [142/419]
bk;t=1715887562543[0.10s,0.20s) :: [***************                         ] :: [167/419]
bk;t=1715887562543[0.00s,0.10s) :: [******                                  ] :: [ 69/419]
bk;t=1715887562543--------------------------------------------------------------------------
bk;t=1715887562543********************
bk;t=1715887562543Failed Tests (1):
bk;t=1715887562543  BOLT :: RISCV/unnamed-sym-no-entry.c
bk;t=1715887562543
bk;t=1715887562543
bk;t=1715887562543Testing Time: 2.56s
bk;t=1715887562543
bk;t=1715887562543Total Discovered Tests: 431
bk;t=1715887562543  Skipped          :   7 (1.62%)
bk;t=1715887562543  Unsupported      :  13 (3.02%)
bk;t=1715887562543  Passed           : 409 (94.90%)
bk;t=1715887562543  Expectedly Failed:   1 (0.23%)

```
