### PR TITLE
Reland: [clang] Track function template instantiation from definition

### LINKED ISSUE #55509: Clang crashes in clang::Sema::BuildExpressionFromIntegralTemplateArgument with c++2b
The following code makes clang to crash. See [at godbolt](https://godbolt.org/z/4q6co9Gae).

```cpp
template<int N>
struct A {
    template<class C>
    friend auto cica(const A<N-1>&, C) {
        return N-1;
    }
};

template<>
struct A<0> {
    template<class C>
    friend auto cica(const A<0>&, C);
};

template <int N, class AT, class = decltype(cica(AT{}, nullptr))>
static constexpr bool MakeCica(int);

template <int N, class AT>
static constexpr bool MakeCica(short, A<N+1> = {});

template <int N, class AT = A<N>, class Val = decltype(MakeCica<N, AT>(0))>
static constexpr bool has_cica = Val{};

constexpr bool cica2 = has_cica<0> || has_cica<0>;
```

### PR DESCRIPTION
**Pull request by mizvekov**
This fixes instantiation of definition for friend function templates,
when the declaration found and the one containing the definition
have different template contexts.

In these cases, the the function declaration corresponding to the
definition is not available; it may not even be instantiated at all.

So this patch adds a bit which tracks which function template
declaration was instantiated from the member template.
It's used to find which primary template serves as a context
for the purpose of obtainining the template arguments needed
to instantiate the definition.

Fixes https://github.com/llvm/llvm-project/issues/55509

### CODE REVIEW

**Comment by mstorsjo** [comment]
I’m not in a position where I can test the patch properly right now, but if the whole qtbase can be built (not only the reduced testcase or the specific source file that triggered the issue before), I’m good with it - thanks!

**Comment by mizvekov** [comment]
> I’m not in a position where I can test the patch properly right now, but if the whole qtbase can be built (not only the reduced testcase or the specific source file that triggered the issue before), I’m good with it - thanks!

Yes it does, no problem!

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -5276,9 +5277,31 @@ void Sema::InstantiateFunctionDefinition(SourceLocation PointOfInstantiation,
...
+                                    ->isCompatibleWithDefinition();
+                              });
+      assert(It != Primary->redecls().end() &&
+             "Should't get here without a definition");
+      if (FunctionDecl *Def = cast<FunctionTemplateDecl>(*It)
+                                  ->getTemplatedDecl()
+                                  ->getDefinition())
+        DC = Def->getLexicalDeclContext();
+      else
+        DC = (*It)->getLexicalDeclContext();
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5300]: Can we get into a situation like `regression2` with friends?
I wonder if we can use `DC = (*It)->getDeclContext();` (not lexical!) unconditionally.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5300]: We need the lexical context because we are interested in the template context of the declaration, ie what set of parameters it sits under, which is a lexical thing.

I don't follow what you mean this situation with friends, can you provide an example?
regression2 is a situation very specific to member function templates, but friends are not members.

Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5300]: Sorry, nevermind. I understand what you are doing now.

However, I'm wondering if we are not reinventing `getTemplateInstantiationPattern(true)` here, It looks strangely similar. Have you explored that?

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:5300]: Well, there is commonality in that both are using the same helpers, but `getTemplateInstantiationPattern(true)` doesn't do what we need here, and this bit doesn't do what the other users of `getTemplateInstantiationPattern(true)` need. I am not sure it would be worth joining both implementations, adding an extra parameter to `getTemplateInstantiationPattern`.

File: clang/include/clang/AST/Decl.h [hunk 2]
```diff
@@ -2298,6 +2298,13 @@ class FunctionDecl : public DeclaratorDecl,
     FunctionDeclBits.IsLateTemplateParsed = ILT;
   }
 
+  bool isInstantiatedFromMemberTemplate() const {
+    return FunctionDeclBits.IsInstantiatedFromMemberTemplate;
+  }
+  void setInstantiatedFromMemberTemplate(bool Val = true) {
+    FunctionDeclBits.IsInstantiatedFromMemberTemplate = Val;
+  }
+
```
Comment (cor3ntin) [inline clang/include/clang/AST/Decl.h:2307]: Is that even used?

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]: Yes, from new methods in DeclTemplate.h, which themselves are used from SemaTemplateInstantiateDecl.cpp and from the ASTReader / Writer.

Comment (cor3ntin) [reply clang/include/clang/AST/Decl.h:2307]: `ASTReader / Writer.`, sure.
However, I don't understand where `IsInstantiatedFromMemberTemplate` is initially set
(and i don't understand why we would need it - we already store that information on the `FunctionTemplateDecl` - which is what you have in your changes to `InstantiateFunctionDefinition`.

Go through the different calls to `setInstantiatedFromMemberTemplate` and see that this is _only_ used in ASTreader, and the new `FunctionTemplateDecl::setInstantiatedFromMemberTemplate` is not used - unless I am blind, which is always a possibility at 7am :) 

Note that `RedeclarableTemplateDecl::setInstantiatedFromMemberTemplate` is already called everywhere it needs to (hopefully)  and `isCompatibleWithDefinition()` can just be   `return `isInstantiatedFromMemberTemplate() || isThisDeclarationADefinition();` - unless I am missing something, but in that case the PR needs more explanation.

From a FunctionFecl, `FunctionDecl::getInstantiatedFromDecl/FunctionDecl::getInstantiatedFromMemberFunction` _should_ also have the information

@erichkeane @AaronBallman

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]: The new `setInstantiatedFromMemberTemplate` is being used from existing callers, which before this patch would call this member from a FunctionTemplateDecl object, which would call `RedeclarableTemplateDecl::setInstantiatedFromMemberTemplate`.

With this patch, these callers will find `FunctionTemplateDecl::setInstantiatedFromMemberTemplate` instead.

See the implementation of the latter, where it also forwards the call to the former.

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]:
```
Note that RedeclarableTemplateDecl::setInstantiatedFromMemberTemplate is already called everywhere it needs to (hopefully) and isCompatibleWithDefinition() can just be  return isInstantiatedFromMemberTemplate() || isThisDeclarationADefinition();` - unless I am missing something, but in that case the PR needs more explanation.
```
The field `RedeclarableTemplateDecl::setInstantiatedFromMemberTemplate` uses is in the common area, the new flag which is set from the new `setInstantiatedFromMemberTemplate` is per declaration.

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]: By the way, this was all discussed in the original review: https://github.com/llvm/llvm-project/pull/110387

Comment (erichkeane) [reply clang/include/clang/AST/Decl.h:2307]: This is a 'thanks i hate it' :)  Basically, the `RedeclarableTemplateDecl` applies to the declaration chain, but this is separately tracking on a per-declaration basis.  It is a little frustrating that we have to do this.

But I think we're stuck with it unless someone has a better idea

**Review by erichkeane — APPROVED** [review]

File: clang/include/clang/AST/Decl.h (hunk 2 above)
Comment (erichkeane) [reply clang/include/clang/AST/Decl.h:2307]: I consider we could probably do this tracking more cleanly at the `RedeclarableTemplateDecl` level (have it track WHICH declaration is the one that was instantiated), but that both requires modifying the `RedeclarableTemplateDecl` after it was generated (making it not-const), plus using 64 bits, instead of 1-per-decl.

Comment (cor3ntin) [reply clang/include/clang/AST/Decl.h:2307]: I had a chat with @erichkeane - I think I understand a bit more now.
At least I understand why `RedeclarableTemplateDecl` is not suitable

However, why is `FunctionDecl::getInstantiatedFromDecl` / `FunctionDecl::getMemberSpecializationInfo`  not what we want?

If we can't use that, why are we storing a bit in FunctionDecl and not in `FunctionTemplateSpecializationInfo` for example?

I think we need comments somewhere explaining all of that because It's not trivial.

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]: Yes, one possibility would be to move the `InstantiatedFromMemberTemplate` field from the common area into the redeclarable.

This would also increase source representation accuracy, as we would be able to point to the exact template redeclaration for each instantiated redeclaration, but it would waste one pointer per Redeclarable. The Function is the only part which really requires the extra information for correctness reasons.

We could on a follow up consider that change, but it would have to stand on its own against the costs, without relying on the bug fix to make it worthwhile.

> However, why is FunctionDecl::getInstantiatedFromDecl / FunctionDecl::getMemberSpecializationInfo not what we want?

These are for different things. `getInstantiatedFromDecl` is used to tell which function this "was instantiated from, if this is a function declaration declared locally inside of a function template".

`getMemberSpecializationInfo` is info for member functions, but friends are not members.

> If we can't use that, why are we storing a bit in FunctionDecl and not in FunctionTemplateSpecializationInfo for example?

Because FunctionDecl has free bits, so this  change has basically no space cost :)

Comment (cor3ntin) [reply clang/include/clang/AST/Decl.h:2307]: > These are for different things. getInstantiatedFromDecl is used to tell which function this "was instantiated from, if this is a function declaration declared locally inside of a function template".

UGH, completely missed that - all of this could use some more comments

> Because FunctionDecl has free bits, so this change has basically no space cost :)

Yeah, but 1/it's a bit confusing 2/ bits there are fairly precious

You could add a bit to FunctionTemplateSpecializationInfo::Function

I don't insist on it. However can you add some comments? It took me a while to understand and I suspect i won;t be the only one.

Thanks, I'll approve when i wake up (and sorry it took me a while to understand everything)

Oh, another solution would be to have a DenseMap of FunctionTemplateDecl -> FunctionTemplateDecl in Sema, storing specialization of friend functions template (only!) in it - hopefully these things are fairly rare - and it might simplify the change to InstantiateFunctionDefinition

Comment (mizvekov) [reply clang/include/clang/AST/Decl.h:2307]: Thanks, I have added a further comment explaining more things.
