### PR TITLE
[HLSL][SPIRV] Add -fspv-use-unknown-image-format option

### LINKED ISSUE #148270: [HLSL][SPIRV] Guess at the image format for storage images
Even in VK1.3, not all driver have to support reading and writing to a storage image without a format. If we were to use the `unknown` format, users may see a regression when compared to DXC. To make things easier to port, we will implement https://github.com/microsoft/DirectXShaderCompiler/pull/7632. At some point we may decide to make it the default.

- [ ] Add the new option `-fspv-use-unknown-image-format` to clang-dxc.
- [ ] Update the wg-hlsl spir-v resource proposal to reflect this change.

### PR DESCRIPTION
**Pull request by s-perron**
This option allows users to control the image format used for HLSL resources
when targeting SPIR-V. When the option is enabled, the unknown image format
is used. Otherwise, the image format is guessed based on the input type.

Fixes https://github.com/llvm/llvm-project/issues/148270

### CODE REVIEW

**Review by Keenuts — APPROVED** [review]

File: clang/lib/CodeGen/Targets/SPIR.cpp [hunk 1]
```diff
@@ -513,14 +513,65 @@ llvm::Type *CommonSPIRTargetCodeGenInfo::getHLSLType(
...
+  // number of channels. This is intended to match the behaviour of DXC.
+  if (LangOpts.HLSLSpvUseUnknownImageFormat ||
+      attributes.ResourceClass != llvm::dxil::ResourceClass::UAV) {
+    return 0; // Unknown
+  }
+
+  if (SampledType->isIntegerTy(32)) {
+    if (Ty->isSignedIntegerType()) {
+      if (NumChannels == 1)
+        return 24; // R32i
```
Comment (shafik) [inline clang/lib/CodeGen/Targets/SPIR.cpp:532]: We can use enums for these values and give them a name that clarifies intent and not have to worry about keeping comments up to date?
