### PR TITLE
[DirectX] Use scalar arguments for @llvm.dx.dot intrinsics

### LINKED ISSUE #134569: [DirectX] The `dx.dot2/3/4` and `dx.dot2add` intrinsics leave vectors around post-scalarization
The `dx.dot2`, `dot3`, `dot4`, and `dot2add` intrinsics are defined as taking vector arguments and have special handling to scalarize those arguments in `DXILOpLowering`. This causes issues, as the vectors don't get entirely cleaned up before we generate DXIL.

From https://github.com/llvm-beanz/offload-test-suite/pull/61:
```
# .---command stdout------------
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%17 = insertelement <3 x float> undef, float %16, i32 0' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%18 = insertelement <3 x float> %17, float %15, i32 1' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%19 = insertelement <3 x float> %18, float %14, i32 2' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%20 = extractelement <3 x float> %19, i32 0' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%21 = extractelement <3 x float> %19, i32 1' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%22 = extractelement <3 x float> %19, i32 2' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%23 = extractelement <3 x float> %19, i32 0' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%24 = extractelement <3 x float> %19, i32 1' in block '#0' of function 'main'.
# | Function: main: error: Instructions must be of an allowed type.
# | note: at '%25 = extractelement <3 x float> %19, i32 2' in block '#0' of function 'main'.
# | Validation failed.
```

It would be simpler to make these intrinsics match their DXIL ops more closely and simply take scalar arguments. This will allow the scalarizer to do its job earlier in the pipeline.

Alternatively, we could improve the vectorArgExpansion logic in DXILOpLowering to clean up any remaining vector artifacts, but this seems like it would be redundant with the logic in the scalarizer.

### PR DESCRIPTION
**Pull request by bogner**
The `dx.dot2`, `dot3`, and `dot4` intrinsics exist purely to lower `dx.fdot`, and they map exactly to the DXIL ops of the same name. Using vectors for their arguments adds unnecessary complexity and causes us to have vector operations that are not trivial to lower post-scalarizer.

Similarly, the `dx.dot2add` intrinsic is overly generic for something that only needs to lower to a single `dot2AddHalf` DXIL op. Update its signature to match the operation it lowers to.

Fixes #134569.

### CODE REVIEW

File: clang/lib/CodeGen/CGHLSLBuiltins.cpp [hunk 1]
```diff
@@ -385,12 +385,17 @@ Value *CodeGenFunction::EmitHLSLBuiltinExpr(unsigned BuiltinID,
            "Intrinsic dot2add is only allowed for dxil architecture");
     Value *A = EmitScalarExpr(E->getArg(0));
     Value *B = EmitScalarExpr(E->getArg(1));
-    Value *C = EmitScalarExpr(E->getArg(2));
+    Value *Acc = EmitScalarExpr(E->getArg(2));
+
+    Value *AX = Builder.CreateExtractElement(A, Builder.getSize(0));
```
Comment (farzonl) [inline clang/lib/CodeGen/CGHLSLBuiltins.cpp:390]: im not sure how i feel about scalarization in the frontend. This seems like a one off so have a minor concern that changes like this will make the vectorized DXIL coming in 6.9 have special cases in the frontend.  This is a concern for the future so take it with a grain of salt.

**Review by farzonl — APPROVED** [review]
This looks reasonable

File: clang/lib/CodeGen/CGHLSLBuiltins.cpp (hunk 1 above)
Comment (bogner) [reply clang/lib/CodeGen/CGHLSLBuiltins.cpp:390]: I would argue that this really is a special case. `dot2add` can only possibly take two-element vectors (it's right in the name), so we don't need to worry about scalarizing vectors of different lengths. It's also unlikely that we'll be adding DXIL operations for anything other than this version that works with `half`. If this operation were something more generic I'd be a little more hesitant to do this logic early, but I don't think we need to worry here.

File: llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp [hunk 2]
```diff
@@ -185,8 +186,14 @@ static Value *expandFloatDotIntrinsic(CallInst *Orig, Value *A, Value *B) {
         /* gen_crash_diag=*/false);
     return nullptr;
   }
-  return Builder.CreateIntrinsic(ATy->getScalarType(), DotIntrinsic,
-                                 ArrayRef<Value *>{A, B}, nullptr, "dot");
+
+  SmallVector<Value *> Args;
+  for (int I = 0; I < NumElts; ++I)
```
[the remark this answers is not in the document]
Comment (bogner) [reply llvm/lib/Target/DirectX/DXILIntrinsicExpansion.cpp:191]: I still think having a generic `fdot` for the frontend to emit makes sense. The implementation being per vector size is a bit odd and wouldn't scale, so if we did ever have a >4 element `fdot` I feel like it would be nicer for the backend to handle it rather than need the frontend to contend with all of these details.

**Comment by farzonl** [comment]
There is a `dot2add.c` test case you will need to update. Target builtins are suppose to work across language modes.

**Review by inbelic — APPROVED** [review]
