### PR TITLE
[ubsan] Support static linking with standalone runtime

### LINKED ISSUE #51538: Using  -fsanitize=undefined with -static segfault the binary
|  |  |
| --- | --- |
| Bugzilla Link | [52196](https://llvm.org/bz52196) |
| Version | unspecified |
| OS | Linux |
| CC | @Kojoley |

## Extended Description 
With

-- foo.cpp --
```cpp
int main() {
	return 0;
}
```
```console
$ clang-14 -static -fsanitize=undefined foo.cpp -lstdc++ && ./a.out
segmentation fault  ./a.out
```

With gcc
```console
$ gcc-10 -static -fsanitize=undefined foo.cpp -lstdc++ && ./a.out && echo $?
0
```

### PR DESCRIPTION
**Pull request by MaskRay**
The standalone runtime (not
-fsanitize-minimal-runtime/-fsanitize-trap=undefined) installs some
signal handlers using `real_sigaction`. With static linking
(-static/-static-pie), the called `REAL(sigaction)` is null, leading to
an immediate segfault, which is confusing (#51538).

Fix #51538 by bailing out.

`// REQUIRES: librt_has_multf3` from https://reviews.llvm.org/D109709
actually disabled the test because `librt_has_*` features are only for
`compiler-rt/test/builtins`. The test does not reproduce for me:
libclang_rt.builtins.a or libgcc. Revert the REQUIRES.

### CODE REVIEW

**Review by PiJoules — APPROVED** [review]

File: compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp [hunk 1]
```diff
@@ -66,6 +66,11 @@ void InitializeDeadlySignals() {
     return;
   is_initialized = true;
   InitializeSignalInterceptors();
+#if SANITIZER_INTERCEPT_SIGNAL_AND_SIGACTION
+  // REAL(sigaction_symname) is nullptr in a static link. Bail out.
+  if (!REAL(sigaction_symname))
```
Comment (vitalybuka) [inline compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: I thin it should be in inside of internal_sigaction
and it should fallback to "return sigaction(" like GO

Comment (MaskRay) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: `internal_sigaction` cannot call `sigaction` (interceptor), as there will be a dead lock. In asan, `AsanInitInternal` (which holds `asan_inited_mutex`) calls `InitializeSignalInterceptors`. If the `sigaction` interceptor is called, `asan_inited_mutex` will be held again -> dead lock.

It seems that testing `REAL(sigaction_symname)` in `ubsan` (and future sanitizers that can be used with static linking) is better?

Comment (MaskRay) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: @vitalybuka ^ :)

Comment (vitalybuka) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: standalone UBSAN ubsan without asan, so it should be fine

Comment (vitalybuka) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: So as-is this patch introduce interceptor related logic into UBSAN, which would be nice to avoid

```
int internal_sigaction(int signum, const void *act, void *oldact) {
#  if !SANITIZER_GO
  if (&real_sigaction)
    return real_sigaction(signum, act, oldact);
#  endif
  return sigaction(signum, (const struct sigaction *)act,
                   (struct sigaction *)oldact);
}
```
From this code, it already should throughout to `sigaction`, so it does not match the test in the description: 

> with static linking
(-static/-static-pie), the called REAL(sigaction) is null, leading to
an immediate segfault,

Comment (vitalybuka) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: Actually signal interceptors are there :(

I think the best for `-static` is to avoid code
```
#define SIGNAL_INTERCEPTOR_ENTER() __ubsan::InitializeDeadlySignals()
#include "sanitizer_common/sanitizer_signal_interceptors.inc"
```

maybe in any  UBSAN

`InitializeSignalInterceptors` is only needed to enforce options like `handle_segv=2`
which are not very critical

**Review by vitalybuka — APPROVED** [review]

File: compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp (hunk 1 above)
Comment (MaskRay) [reply compiler-rt/lib/ubsan/ubsan_signals_standalone.cpp:71]: > So as-is this patch introduce interceptor related logic into UBSAN, which would be nice to avoid
> 
> ```
> int internal_sigaction(int signum, const void *act, void *oldact) {
> #  if !SANITIZER_GO
>   if (&real_sigaction)
>     return real_sigaction(signum, act, oldact);
> #  endif
>   return sigaction(signum, (const struct sigaction *)act,
>                    (struct sigaction *)oldact);
> }
> ```
> 
> From this code, it already should throughout to `sigaction`, so it does not match the test in the description:
> 
> > with static linking
> > (-static/-static-pie), the called REAL(sigaction) is null, leading to
> > an immediate segfault,

The description is correct.
`real_sigaction` is defined due to `SANITIZER_INTERCEPT_SIGNAL_AND_SIGACTION`.
`real_sigaction` calls a function pointer, `REAL(sigaction)`, which is null in the static linking case.

> I think the best for -static is to avoid code
> 
>> #define SIGNAL_INTERCEPTOR_ENTER() __ubsan::InitializeDeadlySignals()
>> #include "sanitizer_common/sanitizer_signal_interceptors.inc"

Without the `!REAL(sigaction_symname)` check as done in this PR, just making `SIGNAL_INTERCEPTOR_ENTER` a no-op does not fix the static linking crash.

Yes, `ubsan_signals_standalone.cpp` defines the signal interceptors. ISTM adding a few lines in this file is the cleanest approach, in contract to an alternative that modifies a generic file which is not needed by another sanitizer.
