### PR TITLE
[Clang] Use the templated declaration for DiagnoseUseOfDecl

### LINKED ISSUE #160776: diagnose_if fails on constructor templates when the expression is argument-independent
This test case for `clang/test/SemaCXX/diagnose_if.cpp` fails:
```c++
struct ConstructorTemplate {
  template <class T>
  explicit ConstructorTemplate(T x)
      _diagnose_if(sizeof(T) == sizeof(char), "oh no", "error") {}
};

void run() {
  ConstructorTemplate('1'); // expected-error{{oh no}}
}
```

Replacing `sizeof(T)` with `sizeof(x)` makes it succeed. It seems the code path for `diagnoseArgIndependentDiagnoseIfAttrs` isn't called in some cases that it's supposed to, but I got lost trying to track it down.

### PR DESCRIPTION
**Pull request by zyn0217**
We missed the check of diagnose_if attributes for the constructor templates, because we used the template declaration, rather than its templated one.

Also, we can avoid the duplicate constraint checking because it's already performed in overload resolution.

There are some diagnostic regressions, all of which are warnings for uses of lambdas in C++03 mode, which I believe we should still diagnose.

Fixes https://github.com/llvm/llvm-project/issues/160776

### CODE REVIEW

File: clang/test/SemaCXX/diagnose_if.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
-// RUN: %clang_cc1 %s -verify -fno-builtin -std=c++14
-// RUN: %clang_cc1 %s -verify -fno-builtin -std=c++14 -fexperimental-new-constant-interpreter
+// RUN: %clang_cc1 %s -verify -fno-builtin -std=c++20
+// RUN: %clang_cc1 %s -verify -fno-builtin -std=c++20 -fexperimental-new-constant-interpreter
```
Comment (cor3ntin) [inline clang/test/SemaCXX/diagnose_if.cpp:2]: Can we keep c++14? (even if we add 20)

**Review by cor3ntin — APPROVED** [review]
LGTM modulo one comment

**Review by shafik — COMMENTED** [review]
Thank you for the detailed summary, I had some questions and then I reread your summary and the answer was there 🎉
