### PR TITLE
[MachineLoopInfo] Fix assertion failure on undef use operands

### LINKED ISSUE #100115: [AMDGPU] Assertion failure in MachineLICM when using llvm.amdgcn.update.dpp.i64
With this [test case](https://github.com/user-attachments/files/16349068/r.txt) I get:
```
$ llc -mtriple=amdgcn -mcpu=gfx1100 -filetype=null r.txt
llc: /home/jayfoad2/git/llvm-project/llvm/lib/CodeGen/MachineLoopInfo.cpp:294: bool llvm::MachineLoop::isLoopInvariant(llvm::MachineInstr &, const llvm::Register) const: Assertion `MRI->getVRegDef(Reg) && "Machine instr not mapped for this vreg?!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

### PR DESCRIPTION
**Pull request by jayfoad**
Fixes #100115

### CODE REVIEW

File: llvm/lib/CodeGen/MachineLoopInfo.cpp [hunk 1]
```diff
@@ -287,7 +287,7 @@ bool MachineLoop::isLoopInvariant(MachineInstr &I,
       }
     }
 
-    if (!MO.isUse())
+    if (!MO.readsReg())
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineLoopInfo.cpp:290]: this needs a mir test too

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+  ; CHECK-NEXT:   S_BRANCH %bb.2
+  ; CHECK-NEXT: {{  $}}
+  ; CHECK-NEXT: bb.5:
+  ; CHECK-NEXT:   S_ENDPGM 0
+  bb.0:
+    successors: %bb.1(0x80000000)
+    liveins: $vgpr0, $vgpr1
+
+    %59:vgpr_32 = IMPLICIT_DEF
+    %60:sreg_32 = IMPLICIT_DEF
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir:48]: run-pass=none to compact register numbers

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir [hunk 3]
```diff
@@ -0,0 +1,77 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
+# RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -run-pass=early-machinelicm %s | FileCheck %s
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir:2]: More specific test file / function name, mention the issue number

**Review by arsenm — APPROVED** [review]
lgtm with nits

**Review by pravinjagtap — APPROVED** [review]

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir (hunk 2 above)
Comment (jayfoad) [reply llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir:48]: This is straight out of llvm-reduce in MIR mode. It would be really handy if llvm-reduce could do the compaction itself.

File: llvm/lib/CodeGen/MachineLoopInfo.cpp (hunk 1 above)
Comment (jayfoad) [reply llvm/lib/CodeGen/MachineLoopInfo.cpp:290]: Done.

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir (hunk 2 above)
Comment (jayfoad) [reply llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir]: Done anyway.

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir (hunk 3 above)
Comment (jayfoad) [reply llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir]: Done.

File: llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir (hunk 2 above)
Comment (arsenm) [reply llvm/test/CodeGen/AMDGPU/machinelicm-crash.mir]: yes, that was on my todo list last I was working on the mir support
