### PR TITLE
AMDGPU: fix isSafeToSink expecting exactly one predecessor

### LINKED ISSUE #89200: Crash in `SIInstrInfo::isSafeToSink`
New test case `test/CodeGen/AMDGPU/machine-sink-crash.mir`:
```
# RUN: llc -mtriple=amdgcn -mcpu=gfx1030 -run-pass=machine-sink %s | FileCheck %s

---
name: f
body: |
  bb.0:
    %81:sreg_32_xm0_xexec = IMPLICIT_DEF
    S_CBRANCH_SCC1 %bb.2, implicit undef $scc
    S_BRANCH %bb.1
  
  bb.1:
    S_BRANCH %bb.3
  
  bb.2:
    S_BRANCH %bb.6
  
  bb.3:
    successors: %bb.4, %bb.5
  
    %10:sreg_32_xm0_xexec = SI_IF undef %81, %bb.5, implicit-def $exec, implicit-def $scc, implicit $exec
    S_BRANCH %bb.4
  
  bb.4:
  
  bb.5:
    successors: %bb.2(0x00000000), %bb.3(0x80000000)
  
    %61:sreg_32 = COPY undef %10
    S_CBRANCH_VCCNZ %bb.3, implicit undef $vcc
    S_BRANCH %bb.2
  
  bb.6:
    ADJCALLSTACKUP 0, 0, implicit-def $scc
    ADJCALLSTACKDOWN 0, 0, implicit-def $scc
...
```
I get:
```
llc: lib/Target/AMDGPU/SIInstrInfo.cpp:220: virtual bool llvm::SIInstrInfo::isSafeToSink(llvm::MachineInstr &, llvm::MachineBasicBlock *, llvm::MachineCycleInfo *) const: Assertion `ExitBlocks[0]->getSinglePredecessor()' failed.
```

`SIInstrInfo::isSafeToSink` was introduced by #67456.

Cc @sameerds

### PR DESCRIPTION
**Pull request by petar-avramovic**
isSafeToSink needs to check if machine cycle has divergent exit branch
but first it needs the MBB that contains cycle exit branch.
Early-tailduplication can delete exit block created by structurize-cfg
so there is still exactly one cycle exit block but the new cycle exit
block can have multiple predecessors.
Simplify search for MBBs that contain cycle exit branch by introducing
helper method getExitingBlocks in GenericCycle.

Fixes #89200

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 1]
```diff
@@ -217,10 +217,20 @@ bool SIInstrInfo::isSafeToSink(MachineInstr &MI,
         SmallVector<MachineBasicBlock *, 1> ExitBlocks;
         FromCycle->getExitBlocks(ExitBlocks);
         assert(ExitBlocks.size() == 1);
-        assert(ExitBlocks[0]->getSinglePredecessor());
-
+        // After structurize-cfg, cycle exit block should have exactly one
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: Isn't it simpler to write this code so that it makes no assumptions about structurized CFGs? E.g.
```c++
  FromCycle->getExitBlocks(ExitBlocks);
  for (ExitBlock : ExitBlocks)
    for (Pred : ExitBlock->predecessors())
      if (FromCycle->contains(Pred) && hasDivergentBranch(Pred))
        return false;
```

Comment (petar-avramovic) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: OK, write it like that for simplicity and delete asserts. Can we leave some of the comments? I don't like fully hiding expected CFG as it could give wrong impression that we can deal with cycle with two divergent exits or similar

Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: > it could give wrong impression that we can deal with cycle with two divergent exits or similar

*This* code can deal with all those cases, can't it?

Comment (petar-avramovic) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: Your proposal without asserts would return something even if input was not "structurized-cfg". Do we want to return something even when CFG is something we don't handle?

Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: Yes, if *this* code can easily handle arbitrary CFGs then it should do so.

If other parts of the code cannot handle arbitrary CFGs, then they should detect the problems.

Comment (ssahasra) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:220]: Yes, whether we return a block should be independent of structrize-cfg. But we should keep the comment for our own future help.

**Review by ssahasra — APPROVED** [review]
LGTM, but please wait for @jayfoad

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 2]
```diff
@@ -213,17 +213,20 @@ bool SIInstrInfo::isSafeToSink(MachineInstr &MI,
       // Check if there is a FromCycle that contains SgprDef's basic block but
       // does not contain SuccToSinkTo and also has divergent exit condition.
       while (FromCycle && !FromCycle->contains(ToCycle)) {
-        // After structurize-cfg, there should be exactly one cycle exit.
+        // After structurize-cfg, there should be exactly one cycle exit. Also,
+        // cycle exit block should have exactly one predecessor, the cycle exit.
+        // Early-tailduplication can removed that block so we have to search for
+        // predecessor that is in cycle.
```
Comment (ruiling) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:219]: The comment here is not useful anymore. The logic should work in general CFG. Meanwhile, I would like to see the code cleaner. Instead of getting exit blocks and check its predecessors. Let's just check against cycle exiting blocks.
```
FromCycle->getExitingBlocks(ExitingBlocks);
for (auto *Exiting : ExistingBlocks)
  if (hasDivergentBranch(Exiting))
    return false;
```

Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:219]: `LoopInfo` has `getExitingBlocks` but `CycleInfo` does not.

I would be happy with removing the comment but @ssahasra suggested to keep it.

Comment (petar-avramovic) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp]: I like getExitingBlocks more.
btw, is that the formal name for blocks that contain branch that exits the cycle?

Comment (petar-avramovic) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp]: Should I switch to using LoopInfo then? For our targets cycles at this point should all be natural loops.

Comment (arsenm) [reply llvm/lib/Target/AMDGPU/SIInstrInfo.cpp]: I maintain it is fully invalid to expect anything out of the MIR CFG. If it isn't enforced by the machine verifier, it isn't required. You cannot assume natural loops

File: llvm/include/llvm/ADT/GenericCycleImpl.h [hunk 3]
```diff
@@ -66,6 +66,19 @@ void GenericCycle<ContextT>::getExitBlocks(
...
 
+template <typename ContextT>
+void GenericCycle<ContextT>::getExitingBlocks(
+    SmallVectorImpl<BlockT *> &TmpStorage) const {
+  TmpStorage.clear();
+
+  for (BlockT *Block : blocks()) {
+    for (BlockT *Succ : successors(Block)) {
+      if (!contains(Succ))
+        TmpStorage.push_back(Block);
```
Comment (jayfoad) [inline llvm/include/llvm/ADT/GenericCycleImpl.h:77]: `break` from the inner loop here.

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 4]
```diff
@@ -214,13 +214,12 @@ bool SIInstrInfo::isSafeToSink(MachineInstr &MI,
...
-        FromCycle->getExitBlocks(ExitBlocks);
-        assert(ExitBlocks.size() == 1);
-        assert(ExitBlocks[0]->getSinglePredecessor());
+        SmallVector<MachineBasicBlock *, 1> ExitingBlocks;
+        FromCycle->getExitingBlocks(ExitingBlocks);
+        assert(ExitingBlocks.size() == 1);
 
         // FromCycle has divergent exit condition.
-        if (hasDivergentBranch(ExitBlocks[0]->getSinglePredecessor())) {
+        if (hasDivergentBranch(ExitingBlocks[0])) {
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:222]: Please return false if _any_ exiting block has a divergent branch

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 5]
```diff
@@ -214,14 +214,14 @@ bool SIInstrInfo::isSafeToSink(MachineInstr &MI,
...
+        SmallVector<MachineBasicBlock *, 1> ExitingBlocks;
+        FromCycle->getExitingBlocks(ExitingBlocks);
 
         // FromCycle has divergent exit condition.
-        if (hasDivergentBranch(ExitBlocks[0]->getSinglePredecessor())) {
-          return false;
+        for (MachineBasicBlock *ExitingBlock : ExitingBlocks) {
+          if (hasDivergentBranch(ExitingBlock)) {
+            return false;
+          }
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:224]: Nit: don't need braces around a single physical line.

**Review by jayfoad — COMMENTED** [review]
Looks reasonable to me but please check with @ssahasra and @ruiling.

**Review by ruiling — APPROVED** [review]
Thanks for fixing this. LGTM

File: llvm/lib/Target/AMDGPU/SIInstrInfo.cpp [hunk 6]
```diff
@@ -214,14 +214,13 @@ bool SIInstrInfo::isSafeToSink(MachineInstr &MI,
       // does not contain SuccToSinkTo and also has divergent exit condition.
       while (FromCycle && !FromCycle->contains(ToCycle)) {
         // After structurize-cfg, there should be exactly one cycle exit.
```
Comment (ruiling) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.cpp:216]: I just notice the old comment is still there, please help remove it. Thanks!
