### PR TITLE
[C23] Fixed the value of BOOL_WIDTH

### LINKED ISSUE #117348: wrong value for BOOL_WIDTH
C23 has a new feature test macro BOOL_WIDTH which is fixed by the standard to the value 1.
Clang has it as 8 in v. 14 to 20, gcc has the correct value.

Test this by compiling with `-std=c2x`

```
#include <limits.h>
static_assert(BOOL_WIDTH == 1);
```

Thanks
Jens

### PR DESCRIPTION
**Pull request by AaronBallman**
The standard mandates that this returns the width of the type, which is the number of bits in the value. For bool, that's required to be `1` explicitly.

Fixes #117348

### CODE REVIEW

**Review by Sirraide — APPROVED** [review]
LGTM

**Review by jyknight — APPROVED** [review]

File: clang/lib/Frontend/InitPreprocessor.cpp [hunk 1]
```diff
@@ -1103,7 +1103,15 @@ static void InitializePredefinedMacros(const TargetInfo &TI,
...
 
-  Builder.defineMacro("__BOOL_WIDTH__", Twine(TI.getBoolWidth()));
+  // The macro is specifying the number of bits in the value representation,
+  // not the number of bits in the object representation, which is what
+  // getBoolWidth() will return. For the bool/_Bool data type, there is only
+  // ever one bit in the value representation. See C23 6.2.6.2p2 for the rules
+  // in C. Note that [basic.fundamental]p10 allows an implementation-defined
+  // value representation for bool; Clang represents bool as an i1 when
+  // lowering to LLVM, so this value is also correct for C++ for our
+  // implementation.
```
Comment (zygoloid) [inline clang/lib/Frontend/InitPreprocessor.cpp:1113]: Clang represents bools as i8 in memory, and for example you can `bit_cast` between `bool` and `char` because our `bool` has no padding bits.

File: clang/lib/Frontend/InitPreprocessor.cpp [hunk 2]
```diff
@@ -1103,7 +1103,15 @@ static void InitializePredefinedMacros(const TargetInfo &TI,
   assert(TI.getCharWidth() == 8 && "Only support 8-bit char so far");
   Builder.defineMacro("__CHAR_BIT__", Twine(TI.getCharWidth()));
 
-  Builder.defineMacro("__BOOL_WIDTH__", Twine(TI.getBoolWidth()));
+  // The macro is specifying the number of bits in the value representation,
```
Comment (zygoloid) [inline clang/lib/Frontend/InitPreprocessor.cpp:1106]: It's the width, not the number of bits in the value representation (which in C++'s definition of "value representation" would be 8, because all 8 bits affect the determination of the value and whether that value is valid).

File: clang/lib/Frontend/InitPreprocessor.cpp [hunk 3]
```diff
@@ -1103,7 +1103,15 @@ static void InitializePredefinedMacros(const TargetInfo &TI,
...
+  // not the number of bits in the object representation, which is what
+  // getBoolWidth() will return. For the bool/_Bool data type, there is only
```
[the remark this answers is not in the document]
Comment (gustedt) [reply clang/lib/Frontend/InitPreprocessor.cpp:1108]: Yes, on modern architectures, `bool` and `_BitInt` should be the only integer types that have padding bits.

File: clang/lib/Frontend/InitPreprocessor.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/lib/Frontend/InitPreprocessor.cpp:1106]: Good catch, fixed.

File: clang/lib/Frontend/InitPreprocessor.cpp [hunk 4]
```diff
@@ -1103,7 +1103,15 @@ static void InitializePredefinedMacros(const TargetInfo &TI,
...
+  // ever one bit in the value representation. See C23 6.2.6.2p2 for the rules
+  // in C. Note that [basic.fundamental]p10 allows an implementation-defined
```
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/lib/Frontend/InitPreprocessor.cpp:1110]: Good call, done

File: clang/lib/Frontend/InitPreprocessor.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/Frontend/InitPreprocessor.cpp:1113]: Done

File: clang/test/C/C23/n2412.c [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+static_assert(CHAR_WIDTH == CHAR_BIT);
+
+static_assert(USHRT_WIDTH >= 16);
+static_assert(UINT_WIDTH >= 16);
+static_assert(ULONG_WIDTH >= 32);
+static_assert(ULLONG_WIDTH >= 64);
+static_assert(BITINT_MAXWIDTH >= ULLONG_WIDTH);
+
+static_assert(MB_LEN_MAX >= 1);
+
```
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/test/C/C23/n2412.c:27]: Pretty sure that's the EOL for the last line in the file, which we want to keep.

File: clang/lib/Frontend/InitPreprocessor.cpp [hunk 6]
```diff
@@ -1103,7 +1103,15 @@ static void InitializePredefinedMacros(const TargetInfo &TI,
   assert(TI.getCharWidth() == 8 && "Only support 8-bit char so far");
   Builder.defineMacro("__CHAR_BIT__", Twine(TI.getCharWidth()));
 
-  Builder.defineMacro("__BOOL_WIDTH__", Twine(TI.getBoolWidth()));
+  // The macro is specifying the number of bits in the width, not the number of
+  // bits the object requires for its in-memory representation, which is what
+  // getBoolWidth() will return. The bool/_Bool data type is only ever one bit
+  // wide. See C23 6.2.6.2p2 for the rules in C. Note that
+  // C++23 [basic.fundamental]p10 allows an implementation-defined value
+  // representation for bool; when lowing to LLVM, Clang represents bool as an
```
Comment (tbaederr) [inline clang/lib/Frontend/InitPreprocessor.cpp:1111]:
```suggestion
  // representation for bool; when lowering to LLVM, Clang represents bool as an
```

**Review by zygoloid — APPROVED** [review]
