### PR TITLE
[llvm][ir]: fix llc crashes on function definitions with label parameters

### LINKED ISSUE #136144: llc crashes on function definitions with `label` parameters
## Example

```llvm
define void @test(label %0) {
1:
    ret void
}
```

## Actual Behavior

```plaintext
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@test'
 #0 0x0000000003acc698 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3acc698)
 #1 0x0000000003aca254 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x0000735660842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x0000000002ffc46b llvm::DataLayout::getABITypeAlign(llvm::Type*) const (/opt/compiler-explorer/clang-trunk/bin/llc+0x2ffc46b)
 #4 0x00000000037c91ab llvm::SelectionDAGISel::LowerArguments(llvm::Function const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x37c91ab)
 #5 0x00000000038858ca llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x38858ca)
 #6 0x0000000003886676 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3886676)
 #7 0x0000000003873171 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3873171)
 #8 0x0000000002b4b018 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
 #9 0x00000000030c5ff2 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x30c5ff2)
#10 0x00000000030c6281 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x30c6281)
#11 0x00000000030c7be9 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x30c7be9)
#12 0x00000000008b937f compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#13 0x0000000000795efe main (/opt/compiler-explorer/clang-trunk/bin/llc+0x795efe)
#14 0x0000735660829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#15 0x0000735660829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#16 0x00000000008b0e45 _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x8b0e45)
```

[Godbolt](https://godbolt.org/z/sz84o8qc4)

## Expected Behavior

The program should be rejected.

## Environment

LLVM trunk on x86_64 Linux.

### PR DESCRIPTION
**Pull request by YLChenZ**
Closes #136144.

After the patch:
```llvm
; label-crash.ll
define void @invalid_arg_type(i32 %0) {
1:
  call void @foo(label %1)
  ret void
}

declare void @foo(label)
```
```
lambda@ubuntu22:~/test$ llc -o out.s label-crash.ll 
Function argument cannot be of label type!
label %0
ptr @foo
llc: error: 'label-crash.ll': input module cannot be verified
```

### CODE REVIEW

File: llvm/lib/IR/Verifier.cpp [hunk 1]
```diff
@@ -2931,6 +2931,8 @@ void Verifier::visitFunction(const Function &F) {
           FT->getParamType(i));
     Check(Arg.getType()->isFirstClassType(),
           "Function arguments must have first-class types!", &Arg);
+    Check(!Arg.getType()->isLabelTy(),
```
Comment (phoebewang) [inline llvm/lib/IR/Verifier.cpp:2934]: We should allow it for asm, see https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/X86/asm-block-labels.ll

Comment (nikic) [reply llvm/lib/IR/Verifier.cpp:2934]: This is checking arguments on the function not calls.

Though really, we should not allow labels as inline asm operands either -- it looks like this is some leftover from an old implementation the predates both blockaddresses and callbr.

File: llvm/test/Verifier/invalid-label-param.ll [hunk 2]
```diff
@@ -0,0 +1,7 @@
+; RUN: not llvm-as < %s 2>&1 | FileCheck %s
+
+define void @invalid_arg_type(label %p) {
+; CHECK: Function argument cannot be of label type!
+  ret void
+}
+
```
Comment (phoebewang) [inline llvm/test/Verifier/invalid-label-param.ll:7]: Add a test for call site, e.g.:

```
define void @test(i32 %0) {
1:
  call void @foo(label %1)
  ret void
}

declare void @foo(label)
```

**Review by phoebewang — APPROVED** [review]
LGTM with one suggestion.

**Comment by YLChenZ** [comment]
@phoebewang Done.
