### PR TITLE
[Coroutines] Mark parameter allocas with coro.outside.frame metadata

### LINKED ISSUE #127499: [coro] Use-after-free of callee-destructed parameter in coroutine which doesn't suspend
Consider:

```
$ cat /tmp/a.cc
#include <coroutine>
#include <stdio.h>

class BasicCoroutine { // Borrowed from https://theshoemaker.de/posts/yet-another-cpp-coroutine-tutorial
public:
  struct Promise {
    BasicCoroutine get_return_object() { return BasicCoroutine {}; }
    void unhandled_exception() noexcept { }
    void return_void() noexcept { }
    std::suspend_never initial_suspend() noexcept { return {}; }
    std::suspend_never final_suspend() noexcept { return {}; }
  };
  using promise_type = Promise;
};

struct [[clang::trivial_abi]] Trivial {
  Trivial(int x) : x(x) {}
  ~Trivial() { printf("~Trivial @ %p: %d\n", this, x); }
  int x;
};

BasicCoroutine coro(Trivial t) {
  co_return;
}

int main() {
  Trivial t(42);
  coro(t);
}
```

```
$ build/bin/clang++ -std=c++20 /tmp/a.cc -fsanitize=address && ASAN_OPTIONS=external_symbolizer_path=$PWD/build/bin/llvm-symbolizer ./a.out
~Trivial @ 0x7c00cfc20058: 42
=================================================================
==3352321==ERROR: AddressSanitizer: heap-use-after-free on address 0x7c00cfc20054 at pc 0x56082ebe8441 bp 0x7ffdcd77b600 sp 0x7ffdcd77b5f8
READ of size 4 at 0x7c00cfc20054 thread T0
    #0 0x56082ebe8440 in Trivial::~Trivial() (/work/llvm-project/a.out+0x114440)
    #1 0x56082ebe7843 in coro(Trivial) (/work/llvm-project/a.out+0x113843)
    #2 0x56082ebe7c8b in main (/work/llvm-project/a.out+0x113c8b)
    #3 0x7fd0d0a40c89 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7fd0d0a40d44 in __libc_start_main csu/../csu/libc-start.c:360:3
    #5 0x56082eb01380 in _start (/work/llvm-project/a.out+0x2d380)

0x7c00cfc20054 is located 20 bytes inside of 32-byte region [0x7c00cfc20040,0x7c00cfc20060)
freed by thread T0 here:
    #0 0x56082ebe6c52 in operator delete(void*, unsigned long) /work/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:155:3
    #1 0x56082ebe7829 in coro(Trivial) (/work/llvm-project/a.out+0x113829)
    #2 0x56082ebe7c8b in main (/work/llvm-project/a.out+0x113c8b)
    #3 0x7fd0d0a40c89 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x56082ebe5fed in operator new(unsigned long) /work/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
    #1 0x56082ebe74fa in coro(Trivial) (/work/llvm-project/a.out+0x1134fa)
    #2 0x56082ebe7c8b in main (/work/llvm-project/a.out+0x113c8b)
    #3 0x7fd0d0a40c89 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-use-after-free (/work/llvm-project/a.out+0x114440) in Trivial::~Trivial()
Shadow bytes around the buggy address:
  0x7c00cfc1fd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7c00cfc1fe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7c00cfc1fe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7c00cfc1ff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7c00cfc1ff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7c00cfc20000: fa fa 00 00 00 fa fa fa fd fd[fd]fd fa fa fa fa
  0x7c00cfc20080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7c00cfc20100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7c00cfc20180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7c00cfc20200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7c00cfc20280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3352321==ABORTING
```

Note the `[[clang::trivial_abi]]` attribute, which means the `t` parameter should be destructed at the end of `coro`. The same problem applies without the attribute when targeting Windows with the MSVC ABI.

Clang emits a move-constructed copy of `t` to go in the coro frame, and a call to destruct the original `t` at the end of the ramp-up. However, it also puts the original `t` in the frame, and since `coro` doesn't suspend, the frame is deleted before reaching the destructor call, which ends up dereferencing a pointer into the deleted coro frame.

### PR DESCRIPTION
**Pull request by zmodem**
Parameters to a coroutine get copied (moved) to coroutine-local instances which code inside the coroutine then uses.

The original parameters should not be part of the frame. Normally CoroSplit figures that out by itself, but for [[clang::trivial_abi]] parameters which, get destructed at the end of the ramp function, it does not (see bug), causing use-after-free's if the frame is destroyed before the end of the ramp (as happens if it doesn't suspend).

Since Clang knows these should never be part of the frame, use metadata to make it so.

Fixes #127499

### CODE REVIEW

**Comment by zmodem** [comment]
I think this is a better fix than #127524. Please take a look.

**Comment by efriedma-quic** [comment]
Adding metadata to an instruction should never be required for correctness: optimizations are not required to preserve metadata on instructions, so this "fix" will just break again later.

If we need two different kinds of alloca in coroutine functions, we need a different way to identify them.

**Comment by rnk** [comment]
That may be true, but grepping suggests that `coro_outside_frame` is pre-existing load-bearing metadata. I think it would be reasonable to use it to fix correctness today and work towards the longer term goal of representing important semantic information as first class alloca fields. We already have a significant semantics changing property, `inalloca`, that we could model this after.

**Comment by efriedma-quic** [comment]
I'm not really happy with that... but if the semantics were never properly defined in the first place, I guess this isn't making things worse.

Not sure if marking the allocas themselves is actually the right approach long-term.  It seems like there's a distinction between code that's "inside" the coroutine (between the begin/end) and "outside" the coroutine, and there are a bunch of restrictions on code that's "outside" the coroutine.  I'm not sure I really understand the mechanics of that, though.

**Comment by ChuanqiXu9** [comment]
I don't feel the previous approach is too problematic. And for this one, I agree with Eli that the metadate may get erased somehow during the transformation.

**Comment by zmodem** [comment]
I pushed a sketch of what using an intrinsic instead would look like. What do you think?

**Review by rnk — COMMENTED** [review]
In the issue (#127499) you pointed out that this issue applies to the MSVC ABI where all parameters are destroyed in the callee. Is it reasonable to construct the analogous test case in that environment? I tried to do this locally, but can't for unrelated build configuration reasons.

**Comment by ChuanqiXu9** [comment]
> > Adding metadata to an instruction should never be required for correctness
> 
> I figured the existing use and the fact that it only needs to survive until CoroSplit made it good enough. But you're right, we should do better.
> 
> I do think we need an explicit way to tell CoroSplit whether an alloca should go in the frame or not. I was thinking of adding an intrinsic when I found this metadata.
> 
> How about turning `coro.outside.frame` into an intrinsic instead?

My instinct reaction is, it may block some optimizations to optimize the alloca out. I don't feel very good about it. Is it possible to introduce the intrinsics without blocking optimizations?

> 
> > I don't feel the previous approach is too problematic.
> 
> I was concerned that it relied on semantics which aren't really defined. There is nothing in the langref which says that the coro frame cannot be accessed after coro.end. As far as I can tell, doing so might be fine as long as the frame hasn't been deallocated, which we can't infer statically.

I believe we shouldn't access the coroutine frame after coro.end. If the doc doesn't make it clear, let's try to make it.

It is true that this may be fine with an optimization, but we don't need to care about that.

> 
> In fact, my change broke a test which seems to be doing exactly that. Just because it's old doesn't mean it was wrong. So the patch didn't feel solid.

I do feel it is wrong since it accesses the frame after it ends. It makes no sense.

> 
> On the other hand, the frontend knows exactly what's going on with these parameter allocas: they should be outside the frame, so having a way to communicate that seems like a solid fix.

**Comment by zmodem** [comment]
> In the issue (#127499) you pointed out that this issue applies to the MSVC ABI where all parameters are destroyed in the callee. Is it reasonable to construct the analogous test case in that environment?

Yes, in fact the reproducer on that issue will trigger use-after-free on x86-64 Windows also without the `trivial_abi` attribute.

I've updated coro-params.cpp to cover this as well.

> My instinct reaction is, it may block some optimizations to optimize the alloca out.

The intrinsic gets dropped by CoroSplit, so after that it's not a problem. Before that, I'm not sure much interesting optimization can happen to allocas anyway? Especially since it's not known if they will be part of the coro frame or not at that point.

> I believe we shouldn't access the coroutine frame after coro.end. If the doc doesn't make it clear, let's try to make it.

How would we motivate that change though?

Also, would that solve the GRO issue (#49843) which led to adding the existing metadata?

>> In fact, my change broke a test which seems to be doing exactly that. Just because it's old doesn't mean it was wrong. So the patch didn't feel solid.

> I do feel it is wrong since it accesses the frame after it ends. It makes no sense.

(To make it easier to follow, we're talking about [this access](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L75).) 

Looking closer, I think that code might be fine. The code after `coro.end` will go at the end of the ramp function. At that point the coro frame is still alive. And since that alloca is also [accessed in the resume function](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L67) (after a suspend), it *needs* to be in the frame.

**Comment by ChuanqiXu9** [comment]
> > In the issue (#127499) you pointed out that this issue applies to the MSVC ABI where all parameters are destroyed in the callee. Is it reasonable to construct the analogous test case in that environment?
> 
> Yes, in fact the reproducer on that issue will trigger use-after-free on x86-64 Windows also without the `trivial_abi` attribute.
> 
> I've updated coro-params.cpp to cover this as well.
> 
> > My instinct reaction is, it may block some optimizations to optimize the alloca out.
> 
> The intrinsic gets dropped by CoroSplit, so after that it's not a problem. Before that, I'm not sure much interesting optimization can happen to allocas anyway? Especially since it's not known if they will be part of the coro frame or not at that point.

As far as I know, a lot of allocas related optimizations/transformation happens before CoroSplit. e.g., mem2reg. And this is the reason why we put CoroSplit in the middle of passes.

> 
> > I believe we shouldn't access the coroutine frame after coro.end. If the doc doesn't make it clear, let's try to make it.
> 
> How would we motivate that change though?
> 
> Also, would that solve the GRO issue (#49843) which led to adding the existing metadata?

I think so.

> 
> > > In fact, my change broke a test which seems to be doing exactly that. Just because it's old doesn't mean it was wrong. So the patch didn't feel solid.
> 
> > I do feel it is wrong since it accesses the frame after it ends. It makes no sense.
> 
> (To make it easier to follow, we're talking about [this access](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L75).)
> 
> Looking closer, I think that code might be fine. The code after `coro.end` will go at the end of the ramp function. At that point the coro frame is still alive. And since that alloca is also [accessed in the resume function](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L67) (after a suspend), it _needs_ to be in the frame.

On the one hand, I still suspect to the validness of the old test. On the other hand, I think we should improve our algorithm to identify the area after coro.end as special area when calculating whether or not to put an alloca to the frame.

The short term solution may consider the case the coroutine won't suspend specially.

**Comment by zmodem** [comment]
> > > My instinct reaction is, it may block some optimizations to optimize the alloca out.
> > 
> > 
> > The intrinsic gets dropped by CoroSplit, so after that it's not a problem. Before that, I'm not sure much interesting optimization can happen to allocas anyway? Especially since it's not known if they will be part of the coro frame or not at that point.
> 
> As far as I know, a lot of allocas related optimizations/transformation happens before CoroSplit. e.g., mem2reg. And this is the reason why we put CoroSplit in the middle of passes.

You're right. I hadn't realized that we run mem2reg before CoroSplit and then spill values back to the frame as needed.

I suppose mem2reg is especially relevant since it operates on allocas. If the transform could remove an alloca, we should not let the intrinsic block it. I've updated the PR to handle that.

For other optimizations that analyze uses of the alloca, I've marked the intrinsic `memory(none)` and the argument `nocapture`.

I think this way the intrinsic will not block important optimizations.


> > > > In fact, my change broke a test which seems to be doing exactly that. Just because it's old doesn't mean it was wrong. So the patch didn't feel solid.
> > 
> > 
> > > I do feel it is wrong since it accesses the frame after it ends. It makes no sense.
> > 
> > 
> > (To make it easier to follow, we're talking about [this access](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L75).)
> > Looking closer, I think that code might be fine. The code after `coro.end` will go at the end of the ramp function. At that point the coro frame is still alive. And since that alloca is also [accessed in the resume function](https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0-rc2/llvm/test/Transforms/Coroutines/coro-debug.ll#L67) (after a suspend), it _needs_ to be in the frame.
> 
> On the one hand, I still suspect to the validness of the old test. On the other hand, I think we should improve our algorithm to identify the area after coro.end as special area when calculating whether or not to put an alloca to the frame.

I think until someone points out exactly what's wrong about the old test, we have to assume that it's valid.

> The short term solution may consider the case the coroutine won't suspend specially.

Can you explain this more?

**Comment by efriedma-quic** [comment]
I think if we're trying to automatically identify whether an alloca has one of two lifetimes, and one of those lifetimes isn't a subset of the other, we're guaranteed to run into trouble again, eventually.  We have to pick the right lifetime 100% of the time... but without assistance from the frontend, it's impossible to write an algorithm that doesn't give up in some cases, given a pointer that escapes.  So it's not really a question of "improving" the existing algorithm; we need markers in the IR, like coro_outside_frame, and the algorithm should be based on that.

**Comment by rnk** [comment]
Re: sroa/mem2reg, that's a valid concern with Hans's intrinsic approach.

> So it's not really a question of "improving" the existing algorithm; we need markers in the IR, like coro_outside_frame, and the algorithm should be based on that.

To check my understanding, by explicit markers, you mean first class fields of `AllocaInst`, like the `inalloca` bit, right?

----

Going back to the beginning, why do we end up in a UAF situation? IIUC, the ramp function should do the following:
- store the bytes of the trivial abi argument into an alloca
- call the move ctor into the coro frame
- co_return
- destroy the coro frame objects, matching the move ctor call
- destroy the alloca, matching the construction from earlier in the caller

What is coro split doing that breaks this? It sounds like it's rewriting the second destructor to destroy the variable in the frame, but that's incorrect.

I guess the issue is that the coroutine frame is not modelled in IR during frontend lowering. It's implied that all allocas get moved into the frame, except in two cases, apparently.

What's different between the case where we suspend and the case where there are no suspend points?

**Comment by zmodem** [comment]
> Re: sroa/mem2reg, that's a valid concern with Hans's intrinsic approach.

Is it still a concern in the latest version, which makes mem2reg aware of the intrinsic?

I don't have a good feel for whether putting a flag on `AllocaInst` or using an intrinsic is less disruptive. Happy to take input on that one.

> Going back to the beginning, why do we end up in a UAF situation? IIUC, the ramp function should do the following:
> * store the bytes of the trivial abi argument into an alloca
> * call the move ctor into the coro frame
> * co_return
> * destroy the coro frame objects, matching the move ctor call
> * destroy the alloca, matching the construction from earlier in the caller
> 
> What is coro split doing that breaks this? It sounds like it's rewriting the second destructor to destroy the variable in the frame, but that's incorrect.

The problem is that the "parameter alloca" (first bullet point) incorrectly gets "promoted" to the coroutine frame. CoroSplit assumes it may be accessed across suspension points (I think it has to, as the address escapes via the "src" argument in the move ctor call).

> What's different between the case where we suspend and the case where there are no suspend points?

The parameter's destructor runs at the end of the ramp function (last bullet point). If we're suspending, the coro frame is still alive at this point (for use when resuming). If the coro finished without suspending, the coro frame has been destroyed at this point, and we get UAF.

**Comment by zmodem** [comment]
The discussion seems to be stalling. I'll try to summarize.

There seem to be two major questions:

1. Whether the front-end should explicitly mark some allocas as not belonging in the coroutine frame, or whether we should enhance CoroSplit to infer it automatically.

   I think explicitly marking the allocas is the best solution for the current bug (https://github.com/llvm/llvm-project/issues/127499), as well as the previous bug (https://github.com/llvm/llvm-project/issues/49843) which already adopted this approach.

   Based on @efriedma-quic's most recent comment,  I think he's also in favor of this approach(?):

   > So it's not really a question of "improving" the existing algorithm; we need markers in the IR, like coro_outside_frame, and the algorithm should be based on that.

   I don't think @rnk expressed an opinion on this question yet.

   @ChuanqiXu9 has argued in favor of the approach from https://github.com/llvm/llvm-project/pull/127524 instead: making CoroSplit treat allocas referenced after the `coro.end` intrinsic as belonging outside the frame.

2. If we do use explicit markers for the allocas, how should that be done?

   Currently, `coro.outside.frame` metadata on the allocas is used for this.

   @efriedma-quic pointed out metadata must never be required for correctness, and we all agree this current state is bad.

   I've proposed using an intrinsic.

   @rnk has suggested that we could put an explicit field on the alloca instruction, similar to `inalloca`.

   @ChuanqiXu9 has raised concerns about an intrinsic blocking optimization.

---

I'm keen to unbreak our users here, as well as implementing the proper long-term solution. Since there is some disagreement, maybe we shouldn't do it all at once.

I've rolled back my PR to just use the existing metadata. While that's not a complete solution, it should be a strict improvement: it fixes the immediate issue using the existing mechanism. I'd like to go ahead and land this.

I will follow up with a PR to remove the metadata, and we can continue discussing there.

File: clang/lib/CodeGen/CGCoroutine.cpp [hunk 1]
```diff
@@ -855,6 +855,16 @@ void CodeGenFunction::EmitCoroutineBody(const CoroutineBodyStmt &S) {
     // Create parameter copies. We do it before creating a promise, since an
     // evolution of coroutine TS may allow promise constructor to observe
     // parameter copies.
+    for (const ParmVarDecl *Parm : FnArgs) {
+      // If the original param is in an alloca, exclude it from the coroutine
+      // frame. The parameter copy will be part of the frame.
```
Comment (rnk) [inline clang/lib/CodeGen/CGCoroutine.cpp:860]: Please elaborate in this comment:
```
// frame. The parameter copy will be part of the frame. The parameter copy 
// will live on the heap, but the original parameter memory should remain on
// the stack. This is necessary to ensure that parameters destroyed in callees, as
// with `trivial_abi` or in the MSVC C++ ABI, are appropriately destroyed after
// setting up the coroutine.
```

File: clang/test/CodeGenCoroutines/coro-params.cpp [hunk 2]
```diff
@@ -190,3 +210,38 @@ method some_class::good_coroutine_calls_custom_constructor(float) {
...
+
+
+struct MSParm {
+  int val;
+  ~MSParm();
+};
+
+void consume(int) noexcept;
+
+// Similarly to the [[clang::trivial_abi]] parameters, with the MSVC ABI
```
Comment (rnk) [inline clang/test/CodeGenCoroutines/coro-params.cpp:222]: Right, this is a good edge case to motivate generalizing this for all parameters.

**Review by rnk — APPROVED** [review]
I think correctness comes first, so this prioritization makes sense.

**Review by ChuanqiXu9 — APPROVED** [review]
Abstractly the current one looks good to stop the bleeding first.

But for the issue itself, I still feel we can fix it in the middle end. Since the case a coroutine without a suspend point is relatively rare case to me.

**Comment by rkjnsn** [comment]
> Since the case a coroutine without a suspend point is relatively rare case to me.

For what it's worth, this issue isn't limited to coroutines without any suspend point. It can also occur:

- If the coroutine conditionally doesn't await (e.g., `if (condition) { co_await foo(); }` and `condition` is false)
- If the coroutine awaits, but the awaitor's `await_ready()` returns true so the coroutine doesn't suspend
- If the coroutine suspends, but the awaitor's `await_suspend()` returns false so the coroutine is immediately resumed
- If the coroutine suspends, but the awaitor's `await_suspend()` causes the coroutine to resume before the ramp function finishes (either by resuming on the same thread or losing a race)
- If the coroutine suspends, but the awaitor's `await_suspend()` returns a coroutine handle whose resumption ultimately results in the current coroutine resuming before the ramp function finishes

**Comment by ChuanqiXu9** [comment]
> > Since the case a coroutine without a suspend point is relatively rare case to me.
> 
> For what it's worth, this issue isn't limited to coroutines without any suspend point. It can also occur:
> 
> * If the coroutine conditionally doesn't await (e.g., `if (condition) { co_await foo(); }` and `condition` is false)
> * If the coroutine awaits, but the awaitor's `await_ready()` returns true so the coroutine doesn't suspend
> * If the coroutine suspends, but the awaitor's `await_suspend()` returns false so the coroutine is immediately resumed
> * If the coroutine suspends, but the awaitor's `await_suspend()` causes the coroutine to resume before the ramp function finishes (either by resuming on the same thread or losing a race)
> * If the coroutine suspends, but the awaitor's `await_suspend()` returns a coroutine handle whose resumption ultimately results in the current coroutine resuming before the ramp function finishes

Or we can model it as, if it is possible to reach the section after coro.end from entry without reaching a real suspend point.

**Comment by rkjnsn** [comment]
Even for a real suspend, though, isn't it still possible for the coroutine to be resumed on a different thread, completed, and the frame deleted, all before the coroutine ramp finishes executing on the current thread?

**Comment by ChuanqiXu9** [comment]
> Even for a real suspend, though, isn't it still possible for the coroutine to be resumed on a different thread, completed, and the frame deleted, all before the coroutine ramp finishes executing on the current thread?

Technically possible, you got me.

File: clang/lib/CodeGen/CGCoroutine.cpp (hunk 1 above)
Comment (zmodem) [reply clang/lib/CodeGen/CGCoroutine.cpp:860]: Done.
