### PR TITLE
[libc][test] make `str_to_float_comparison_test` independent of C++ headers.

### LINKED ISSUE #129838: [libc] str_to_float_comparison_test should be hermetic
The test in question, https://github.com/llvm/llvm-project/blob/main/libc/test/src/__support/str_to_float_comparison_test.cpp, is not hermetic right now. This causes problems for NixOS/nixpkgs where full builds use clang without a libc. Being able to run all tests without needing the host's libc would be very beneficial.

Relevant log:
```
libc> [1145/1151] Building CXX object libc/test/src/__support/CMakeFiles/libc_str_to_float_comparison_test.dir/str_to_float_comparison_test.cpp.o
libc> FAILED: libc/test/src/__support/CMakeFiles/libc_str_to_float_comparison_test.dir/str_to_float_comparison_test.cpp.o
libc> /nix/store/h3wgz6n8bc4n61vv427xl8cz69vcd96c-clang-wrapper-20.1.0-rc3/bin/clang++ -DLIBC_NAMESPACE=__llvm_libc_20_1_0_rc3  -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wno-comment -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=gnu++17 -MD -MT libc/test/src/__support/CMakeFiles/libc_str_to_float_comparison_test.dir/str_to_float_comparison_test.cpp.o -MF libc/test/src/__support/CMakeFiles/libc_str_to_float_comparison_test.dir/str_to_float_comparison_test.cpp.o.d -o libc/test/src/__support/CMakeFiles/libc_str_to_float_comparison_test.dir/str_to_float_comparison_test.cpp.o -c /build/libc-src-20.1.0-rc3/libc/test/src/__support/str_to_float_comparison_test.cpp
libc> In file included from /build/libc-src-20.1.0-rc3/libc/test/src/__support/str_to_float_comparison_test.cpp:11:
libc> In file included from /nix/store/l71wz2r8ki25kzw33jwssg8rh77xfkpr-gcc-14-20241116/include/c++/14-20241116/stdlib.h:36:
libc> In file included from /nix/store/l71wz2r8ki25kzw33jwssg8rh77xfkpr-gcc-14-20241116/include/c++/14-20241116/cstdlib:41:
libc> In file included from /nix/store/l71wz2r8ki25kzw33jwssg8rh77xfkpr-gcc-14-20241116/include/c++/14-20241116/aarch64-unknown-linux-gnu/bits/c++config.h:680:
libc> /nix/store/l71wz2r8ki25kzw33jwssg8rh77xfkpr-gcc-14-20241116/include/c++/14-20241116/aarch64-unknown-linux-gnu/bits/os_defines.h:39:10: fatal error: 'features.h' file not found
libc>    39 | #include <features.h>
libc>       |          ^~~~~~~~~~~~
libc> 1 error generated.
libc> [1146/1151] Building CXX object libc/src/stdlib/CMakeFiles/libc.src.stdlib.strfromf.dir/strfromf.cpp.o
libc> [1147/1151] Building CXX object libc/src/stdlib/CMakeFiles/libc.src.stdlib.strfromd.dir/strfromd.cpp.o
libc> [1148/1151] Building CXX object libc/src/stdio/printf_core/CMakeFiles/libc.src.stdio.printf_core.converter.dir/converter.cpp.o
libc> ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by bassiounix**
This is an attempt to move away from C++ headers to be able to run the test without `libcxx`.
closes #129838

cc @lntue @RossComputerGuy

### CODE REVIEW

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 1]
```diff
@@ -8,14 +8,11 @@
...
-#include <stdlib.h> // For string to float functions
-
 // #include "src/__support/FPUtil/FPBits.h"
 
-#include <cstdint>
-#include <fstream>
-#include <iostream>
-#include <string>
+#include <stdint.h>
+#include <stdio.h>
```
Comment (lntue) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:14]: Many of these `stdio.h` functions that we used in here have corresponding internal functions and targets.  You can switch to use them in here, update the target dependency and we should be able to remove the `#include <stdio.h>`.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 2]
```diff
@@ -59,30 +56,31 @@ int checkFile(char *inputFileName, int *totalFails, int *totalBitDiffs,
...
     *total = *total + 1;
     uint32_t expectedFloatRaw;
     uint64_t expectedDoubleRaw;
 
-    expectedFloatRaw = fastHexToU32(line.c_str() + 5);
-    expectedDoubleRaw = fastHexToU64(line.c_str() + 14);
-    num = line.substr(31);
+    expectedFloatRaw = fastHexToU32(line + 5);
+    expectedDoubleRaw = fastHexToU64(line + 14);
+    sscanf(line + 31, "%s", num);
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:79]: this could just be `num = line + 31`

Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp]: I had to change it to `const char *` instead of `char[100]` to make this possible

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 3]
```diff
@@ -150,24 +149,23 @@ int main(int argc, char *argv[]) {
...
-            << "Total lines: " << total << "\n";
-  return result;
+
+  EXPECT_EQ(result, 0);
+  EXPECT_EQ(fails, 0);
+  EXPECT_EQ(bitdiffs, 0);
+  EXPECT_EQ(detailedBitDiffs[0], 0);
+  EXPECT_EQ(detailedBitDiffs[1], 0);
+  EXPECT_EQ(detailedBitDiffs[2], 0);
+  EXPECT_EQ(detailedBitDiffs[3], 0);
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:169]: please add the `float low`, `float high` annotations as comments since that will make debugging easier.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 4]
```diff
@@ -150,24 +149,23 @@ int main(int argc, char *argv[]) {
...
-    int curResult =
-        checkFile(argv[i], &fails, &bitdiffs, detailedBitDiffs, &total);
-    if (curResult == 1) {
-      result = 1;
-      break;
-    } else if (curResult == 2) {
-      result = 2;
-    }
+
+  char filename[] = "str_to_float_comparison_data.txt";
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:153]: Ideally this test would still be able to read from a list of files, even if it doesn't normally. It's intended to be used with https://github.com/nigeltao/parse-number-fxx-test-data which has the tests spread over many files.

**Review by michaelrj-google — COMMENTED** [review]
Overall LGTM with some minor comments. Thanks for cleaning up this old test!

File: libc/test/src/__support/CMakeLists.txt [hunk 5]
```diff
@@ -249,31 +249,22 @@ add_libc_test(
...
+    SRCS
+      str_to_float_comparison_test.cpp
+    DEPENDS
+      libc.src.stdio.printf
+      libc.src.stdio.fopen
+      libc.src.stdio.fclose
+      libc.src.stdio.fgets
+      libc.src.stdlib.strtof
+      libc.src.stdlib.strtod
+    NO_RUN_POSTBUILD
```
Comment (lntue) [inline libc/test/src/__support/CMakeLists.txt:266]: nit: move this to right before `SUITE`.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 6]
```diff
@@ -59,30 +57,32 @@ int checkFile(char *inputFileName, int *totalFails, int *totalBitDiffs,
...
+    expectedDoubleRaw = fastHexToU64(line + 14);
+    num = line + 31;
 
-    float floatResult = strtof(num.c_str(), nullptr);
+    float floatResult = LIBC_NAMESPACE::strtof(num, nullptr);
 
-    double doubleResult = strtod(num.c_str(), nullptr);
+    double doubleResult = LIBC_NAMESPACE::strtod(num, nullptr);
 
     uint32_t floatRaw = *(uint32_t *)(&floatResult);
```
Comment (lntue) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:87]: change this to `cpp::bit_cast<uint32_t>(floatResult)`, and similarly for `doubleResult`.

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 3 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:169]: could you elaborate on what are those? I don't know what you mean.

Comment (michaelrj-google) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:169]: In the original code, it printed "float low", "float high", "double low", or "double high" after the lines containing the values of `detailedBitDiffs`. I'd like you to add comments with the same text since that text isn't getting printed anymore.

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 4 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:153]: I'll change it to comma separated file names passed as env variable via cmake.

File: libc/test/src/__support/CMakeLists.txt (hunk 5 above)
Comment (bassiounix) [reply libc/test/src/__support/CMakeLists.txt]: it can't be moved right before `SUITE`, only in the order I put that the test is properly configured.

File: libc/test/src/__support/CMakeLists.txt [hunk 7]
```diff
@@ -249,31 +249,26 @@ add_libc_test(
...
-  )
-
-  add_executable(
-    libc_system_str_to_float_comparison_test
-    str_to_float_comparison_test.cpp
+  add_libc_test(
+    str_to_float_comparison_test
+    SUITE
+      libc-support-tests
+    NO_RUN_POSTBUILD
```
Comment (lntue) [inline libc/test/src/__support/CMakeLists.txt:257]: Just found out that `NO_RUN_POSTBUILD` flag support was not added for hermetic test:
https://github.com/llvm/llvm-project/blob/main/libc/cmake/modules/LLVMLibCTestRules.cmake#L645

We should add that option for hermetic test there, similar to unit tests in https://github.com/llvm/llvm-project/blob/main/libc/cmake/modules/LLVMLibCTestRules.cmake#L197

File: libc/test/src/__support/CMakeLists.txt [hunk 8]
```diff
@@ -249,31 +249,26 @@ add_libc_test(
...
+    ENV "FILES=${CMAKE_CURRENT_SOURCE_DIR}/str_to_float_comparison_data.txt"
```
Comment (lntue) [inline libc/test/src/__support/CMakeLists.txt:258]: On the other hand, `ENV` is not added for unit test, only hermetic tests and integration tests.  It should also be added for unit tests.

File: libc/test/src/__support/CMakeLists.txt [hunk 9]
```diff
@@ -249,31 +249,26 @@ add_libc_test(
     libc.src.__support.memory_size
 )
 
-# FIXME: We shouldn't have regular executables created because we could be
-#        cross-compiling the tests and running through an emulator.
 if(NOT LIBC_TARGET_OS_IS_GPU)
```
Comment (lntue) [inline libc/test/src/__support/CMakeLists.txt:252]: With all the correct dependency, this condition is probably not needed anymore.

File: libc/cmake/modules/LLVMLibCTestRules.cmake [hunk 10]
```diff
@@ -203,7 +206,7 @@ function(create_libc_unittest fq_target_name)
     "LIBC_UNITTEST"
     "NO_RUN_POSTBUILD;C_TEST" # Optional arguments
     "SUITE;CXX_STANDARD" # Single value arguments
-    "SRCS;HDRS;DEPENDS;COMPILE_OPTIONS;LINK_LIBRARIES;FLAGS" # Multi-value arguments
+    "SRCS;HDRS;DEPENDS;ARGS;ENV;COMPILE_OPTIONS;LINK_LIBRARIES;LOADER_ARGS;FLAGS" # Multi-value arguments
```
Comment (lntue) [inline libc/cmake/modules/LLVMLibCTestRules.cmake:209]: you don't need to port `ARGS` and `LOADER_ARGS` that are used by GPU targets here.  When building for GPUs, only hermetic tests are built and unittests are skipped.

File: libc/cmake/modules/LLVMLibCTestRules.cmake [hunk 11]
```diff
@@ -642,7 +665,7 @@ function(add_libc_hermetic test_name)
   endif()
   cmake_parse_arguments(
     "HERMETIC_TEST"
-    "IS_GPU_BENCHMARK" # Optional arguments
+    "IS_GPU_BENCHMARK;NO_RUNPOSTBUILD" # Optional arguments
```
Comment (lntue) [inline libc/cmake/modules/LLVMLibCTestRules.cmake:668]: `NO_RUN_POSTBUILD`

File: libc/test/src/__support/CMakeLists.txt [hunk 12]
```diff
@@ -249,32 +249,25 @@ add_libc_test(
...
+    libc.src.stdio.printf
+    libc.src.stdio.fopen
+    libc.src.stdio.fclose
+    libc.src.stdio.fgets
+    libc.src.stdlib.strtof
+    libc.src.stdlib.strtod
+    libc.src.stdlib.getenv
+    libc.src.string.strtok
+    libc.src.__support.CPP.bit
+  ENV "FILES=${CMAKE_CURRENT_SOURCE_DIR}/str_to_float_comparison_data.txt"
```
Comment (lntue) [inline libc/test/src/__support/CMakeLists.txt:269]: move `ENV` above `DEPENDS`.

File: libc/cmake/modules/LLVMLibCTestRules.cmake (hunk 10 above)
Comment (bassiounix) [reply libc/cmake/modules/LLVMLibCTestRules.cmake:209]: so the part of `set(test-cmd ...` will be removed?

File: libc/cmake/modules/LLVMLibCTestRules.cmake [hunk 13]
```diff
@@ -317,10 +318,24 @@ function(create_libc_unittest fq_target_name)
...
+    set(test_cmd ${LIBC_UNITTEST_ENV}
+        ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:${fq_build_target_name}>)
     add_custom_target(
       ${fq_target_name}
-      COMMAND ${fq_build_target_name}
+      DEPENDS ${fq_target_name}-cmd
+    )
+
+    add_custom_command(
+      OUTPUT ${fq_target_name}-cmd
```
Comment (lntue) [inline libc/cmake/modules/LLVMLibCTestRules.cmake:329]: Can you change this (and also in hermetic test) to `fq_target_name.__cmd__`?

File: libc/cmake/modules/LLVMLibCTestRules.cmake [hunk 14]
```diff
@@ -317,10 +318,24 @@ function(create_libc_unittest fq_target_name)
   target_link_libraries(${fq_build_target_name} PRIVATE ${link_libraries})
 
   if(NOT LIBC_UNITTEST_NO_RUN_POSTBUILD)
+    set(test_cmd ${LIBC_UNITTEST_ENV}
+        ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:${fq_build_target_name}>)
     add_custom_target(
       ${fq_target_name}
-      COMMAND ${fq_build_target_name}
```
Comment (lntue) [inline libc/cmake/modules/LLVMLibCTestRules.cmake:322]: Does changing to`COMMAND ${LIBC_UNITTEST_ENV} ${CMAKE_CROSSCOMPILING_EMULATOR} ${fq_build_target_name}` instead of creating another `${fq_target_name}.__cmd__` work?

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 15]
```diff
@@ -150,24 +152,25 @@ int main(int argc, char *argv[]) {
   int detailedBitDiffs[4] = {0, 0, 0, 0};
 
   int total = 0;
-  for (int i = 1; i < argc; i++) {
-    std::cout << "Starting file " << argv[i] << "\n";
+
+  char *files = LIBC_NAMESPACE::getenv("FILES");
+  for (char *file = LIBC_NAMESPACE::strtok(files, ","); file != nullptr;
+       file = LIBC_NAMESPACE::strtok(nullptr, ",")) {
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:158]: you should probably make a copy of `files` with `malloc`/`memcpy` if you're planning to use `strtok` on it. `getenv` returns a pointer to a section of the `env_ptr`, and `strtok` modifies the string passed to it.

**Review by michaelrj-google — COMMENTED** [review]
Overall LGTM, but wait for lntue to approve for the cmake.

File: libc/cmake/modules/LLVMLibCTestRules.cmake (hunk 14 above)
Comment (bassiounix) [reply libc/cmake/modules/LLVMLibCTestRules.cmake:322]: basically the same thing

File: libc/cmake/modules/LLVMLibCTestRules.cmake [hunk 16]
```diff
@@ -317,9 +318,11 @@ function(create_libc_unittest fq_target_name)
   target_link_libraries(${fq_build_target_name} PRIVATE ${link_libraries})
 
   if(NOT LIBC_UNITTEST_NO_RUN_POSTBUILD)
+    set(test_cmd ${LIBC_UNITTEST_ENV}
+        ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:${fq_build_target_name}>)
```
Comment (lntue) [inline libc/cmake/modules/LLVMLibCTestRules.cmake:322]: `test_cmd` is not needed anymore.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 17]
```diff
@@ -54,80 +56,112 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
-  std::string num;
+static void parseLine(char *line, int *total, int *detailedBitDiffs,
+                      int32_t &curFails, int32_t &curBitDiffs) {
 
-  std::ifstream fileStream(inputFileName, std::ifstream::in);
-
-  if (!fileStream.is_open()) {
-    std::cout << "file '" << inputFileName << "' failed to open. Exiting.\n";
-    return 1;
+  if (line[0] == '#') {
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:62]: you can remove this check

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 18]
```diff
@@ -54,80 +56,112 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+    if (curFails + curBitDiffs < 10) {
+      LIBC_NAMESPACE::printf("Double fail for '%s'. Expected %lx but got %lx\n",
+                             num, expectedDoubleRaw, doubleRaw);
     }
   }
+}
+
+int checkBuffer(int *totalFails, int *totalBitDiffs, int *detailedBitDiffs,
+                int *total) {
+  const char *lines[6] = {"3C00 3F800000 3FF0000000000000 1",
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:120]: can you make it constexpr?

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 19]
```diff
@@ -54,80 +56,112 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+                          "57B7 42F6E979 405EDD2F1A9FBE77 123.456",
+                          "622A 44454000 4088A80000000000 789",
+                          "7C00 7F800000 7FF0000000000000 123.456e789"};
+
+  int32_t curFails = 0;    // Only counts actual failures, not bitdiffs.
+  int32_t curBitDiffs = 0; // A bitdiff is when the expected result and actual
+  // result are off by +/- 1 bit.
+
+  for (uint8_t i = 0; i < 6; i++) {
+    auto line = const_cast<char *>(lines[i]);
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:132]: Why do we need a const_cast? Can't you pass the const char to parseLine?

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 20]
```diff
@@ -150,24 +193,28 @@ int main(int argc, char *argv[]) {
...
-    std::cout << "Starting file " << argv[i] << "\n";
-    int curResult =
-        checkFile(argv[i], &fails, &bitdiffs, detailedBitDiffs, &total);
-    if (curResult == 1) {
-      result = 1;
-      break;
-    } else if (curResult == 2) {
-      result = 2;
+
+  char *files = LIBC_NAMESPACE::getenv("FILES");
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:197]: you can get rid of this since the data will be available on the test now.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 21]
```diff
@@ -54,80 +56,112 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+  *totalFails += curFails;
+
+  if (curFails > 1 || curBitDiffs > 1) {
+    return 2;
+  }
+  return 0;
+}
 
-  fileStream.close();
+int checkFile(char *inputFileName, int *totalFails, int *totalBitDiffs,
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:145]: you can get rid of this since the data will be available on the test now.

File: libc/test/src/__support/CMakeLists.txt [hunk 22]
```diff
@@ -249,32 +249,26 @@ add_libc_test(
...
-
-  set(float_test_file ${CMAKE_CURRENT_SOURCE_DIR}/str_to_float_comparison_data.txt)
-
-  add_custom_command(TARGET libc_str_to_float_comparison_test
-                     POST_BUILD
-                     COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:libc_str_to_float_comparison_test> ${float_test_file}
-                     COMMENT "Test the strtof and strtod implementations against precomputed results."
-                     VERBATIM)
-endif()
+  ENV "FILES=${CMAKE_CURRENT_SOURCE_DIR}/str_to_float_comparison_data.txt"
```
Comment (mikhailramalho) [inline libc/test/src/__support/CMakeLists.txt:259]: you can get rid of this since the data will be available on the test now.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 23]
```diff
@@ -138,7 +172,16 @@ int checkFile(char *inputFileName, int *totalFails, int *totalBitDiffs,
   return 0;
 }
 
-int main(int argc, char *argv[]) {
+int updateResult(int result, int curResult) {
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:175]: you can inline this once the old file handling stuff is removed

**Review by mikhailramalho — CHANGES_REQUESTED** [review]

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 21 above)
Comment (lntue) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:145]: @mikhailramalho @RossComputerGuy  I think the purpose of this test according to @michaelrj-google is to manually run it against large files containing many interesting cases.  Before this PR, the test build was set up manually, and didn't respect the dependency or entrypoint lists that we normally have.  With this change, this test will be build using our normal testing infra as other tests, respecting the dependency (skipped if they are not available), and will not automatically run with `ninja check-libc`.  I hope that would be enough to make it non-blocking when we try to build on new targets?

File: libc/test/src/__support/CMakeLists.txt (hunk 22 above)
Comment (lntue) [reply libc/test/src/__support/CMakeLists.txt:259]: +1

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 24]
```diff
@@ -54,80 +56,112 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+      curFails++;
+    }
+    if (curFails + curBitDiffs < 10) {
+      LIBC_NAMESPACE::printf("Double fail for '%s'. Expected %lx but got %lx\n",
+                             num, expectedDoubleRaw, doubleRaw);
     }
   }
+}
+
+int checkBuffer(int *totalFails, int *totalBitDiffs, int *detailedBitDiffs,
```
Comment (lntue) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:118]: Since you are here, let's modernize these a bit:
1) defining ParseStatus enum to encode the current 3 possibilities,
2) pack the ParseResult struct with these 4 fields, and pass them as reference in these functions.

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 21 above)
Comment (mikhailramalho) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:145]: Got it, but if the goal is to run it manually on large files, can we remove the file from the repo and keep the static data for the automated test?

If so, you can ignore my comments to remove the file handling stuff @bassiounix

Comment (lntue) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:145]: removing the file sounds good to me, but we should add more comments about the usage of this test, and maybe add the link to the other repo with a lot of tests for this one.  I'll let @michaelrj-google decide what to do with the test file(s).

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 17 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:62]: the text file has `#` as a comment.
unless the content is edited, no I can't really remove it!

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 18 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:120]: No not really

```txt
libc/test/src/__support/str_to_float_comparison_test.cpp:120:31: warning: ISO C++11 does not allow conversion from string literal to 'char *const' [-Wwritable-strings]
  120 |   constexpr char *lines[6] = {"3C00 3F800000 3FF0000000000000 1",
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 19 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:132]:
```
Cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'. clang(init_conversion_failed)
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 18 above)
Comment (mikhailramalho) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:136]: Try `constexpr const char*`

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 19 above)
Comment (bassiounix) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:148]: Yes I did.

Comment (mikhailramalho) [reply libc/test/src/__support/str_to_float_comparison_test.cpp:149]: It should work, what's the error you got?

**Review by lntue — APPROVED** [review]
LGTM.  Let's wait for @michaelrj-google @mikhailramalho and @RossComputerGuy to double check.

**Review by michaelrj-google — APPROVED** [review]
LGTM

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 25]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+  uint64_t expectedDoubleRaw;
 
-    expectedFloatRaw = fastHexToU32(line.c_str() + 5);
-    expectedDoubleRaw = fastHexToU64(line.c_str() + 14);
-    num = line.substr(31);
+  expectedFloatRaw = fastHexToU32(line + 5);
+  expectedDoubleRaw = fastHexToU64(line + 14);
 
-    float floatResult = strtof(num.c_str(), nullptr);
+  char *num = line + 31;
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:85]:
```suggestion
  const char *num = line + 31;
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 26]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
-int checkFile(char *inputFileName, int *totalFails, int *totalBitDiffs,
-              int *detailedBitDiffs, int *total) {
-  int32_t curFails = 0;    // Only counts actual failures, not bitdiffs.
-  int32_t curBitDiffs = 0; // A bitdiff is when the expected result and actual
-                           // result are off by +/- 1 bit.
-  std::string line;
-  std::string num;
-
-  std::ifstream fileStream(inputFileName, std::ifstream::in);
+static void parseLine(char *line, ParseResult &parseResult, int32_t &curFails,
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:72]:
```suggestion
static void parseLine(const char *line, ParseResult &parseResult, int32_t &curFails,
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 27]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+      "622A 44454000 4088A80000000000 789",
+      "7C00 7F800000 7FF0000000000000 123.456e789"};
+
+  int32_t curFails = 0;    // Only counts actual failures, not bitdiffs.
+  int32_t curBitDiffs = 0; // A bitdiff is when the expected result and actual
+  // result are off by +/- 1 bit.
+
+  for (uint8_t i = 0; i < 6; i++) {
+    auto line = const_cast<char *>(lines[i]);
+    parseLine(line, parseResult, curFails, curBitDiffs);
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:150]:
```suggestion
    parseLine(lines[i], parseResult, curFails, curBitDiffs);
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 28]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+      "57B7 42F6E979 405EDD2F1A9FBE77 123.456",
+      "622A 44454000 4088A80000000000 789",
+      "7C00 7F800000 7FF0000000000000 123.456e789"};
+
+  int32_t curFails = 0;    // Only counts actual failures, not bitdiffs.
+  int32_t curBitDiffs = 0; // A bitdiff is when the expected result and actual
+  // result are off by +/- 1 bit.
+
+  for (uint8_t i = 0; i < 6; i++) {
+    auto line = const_cast<char *>(lines[i]);
```
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:149]:
```suggestion
```

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 29]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
-  return result;
+
+  EXPECT_EQ(parseStatus, ParseStatus::SUCCESS);
+  EXPECT_EQ(parseResult.totalFails, 0u);
+  EXPECT_EQ(parseResult.totalBitDiffs, 0u);
+  EXPECT_EQ(parseResult.detailedBitDiffs[0], 0u); // float low
+  EXPECT_EQ(parseResult.detailedBitDiffs[1], 0u); // float high
+  EXPECT_EQ(parseResult.detailedBitDiffs[2], 0u); // double low
+  EXPECT_EQ(parseResult.detailedBitDiffs[3], 0u); // double high
+  EXPECT_EQ(parseResult.total, 6u);
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:236]: This assumes every file has exactly 6 lines. This should probably be changed to `printf("Total lines: %d\n", parseResult.total);`

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 30]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
     }
+    if (curFails + curBitDiffs < 10) {
+      LIBC_NAMESPACE::printf("Double fail for '%s'. Expected %lx but got %lx\n",
+                             num, expectedDoubleRaw, doubleRaw);
+    }
+  }
+}
+
+ParseStatus checkBuffer(ParseResult &parseResult) {
+  constexpr const char *lines[6] = {
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:136]: the `6` is unnecessary here, and will make it annoying if we want to add more.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 31]
```diff
@@ -54,120 +69,169 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+      "3D9A 3FB33333 3FF6666666666666 1.4",
+      "57B7 42F6E979 405EDD2F1A9FBE77 123.456",
+      "622A 44454000 4088A80000000000 789",
+      "7C00 7F800000 7FF0000000000000 123.456e789"};
+
+  int32_t curFails = 0;    // Only counts actual failures, not bitdiffs.
+  int32_t curBitDiffs = 0; // A bitdiff is when the expected result and actual
+  // result are off by +/- 1 bit.
+
+  for (uint8_t i = 0; i < 6; i++) {
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:148]: replace the `6` with an expression calculating the number of elements in `lines`, e.g. `sizeof(lines) / sizeof(char*)`. That way if we want to add more lines this will work automatically.

File: libc/test/src/__support/str_to_float_comparison_test.cpp (hunk 30 above)
Comment (mikhailramalho) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:136]: constexpr variables should be capitalized as per https://libc.llvm.org/contributing.html

**Review by mikhailramalho — CHANGES_REQUESTED** [review]
Couple of nits, otherwise it's okay.

**Review by michaelrj-google — CHANGES_REQUESTED** [review]
On local testing I found a few issues, specifically it doesn't seem to work with files. Will provide more information after some testing.

**Review by mikhailramalho — APPROVED** [review]
LGTM.

Please wait for Michael's approval before landing this.

**Comment by RossComputerGuy** [comment]
There's CI failures, I'll be able to look at this soon.

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 32]
```diff
@@ -54,120 +69,168 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
+  parseResult.totalFails += curFails;
 
   if (curFails > 1 || curBitDiffs > 1) {
-    return 2;
+    return ParseStatus::PARSE_ERROR;
+  }
+  return ParseStatus::SUCCESS;
+}
+
+ParseStatus updateResult(ParseStatus result, ParseStatus curResult) {
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:190]: nit: Given that there is a struct named `ParseResult`, having a `ParseStatus` variable named `result` is a little confusing. Rename to `status` and `cur_status`?

File: libc/test/src/__support/str_to_float_comparison_test.cpp [hunk 33]
```diff
@@ -54,120 +69,168 @@ static inline uint64_t fastHexToU64(const char *inStr) {
...
-  std::string num;
-
-  std::ifstream fileStream(inputFileName, std::ifstream::in);
+static void parseLine(const char *line, ParseResult &parseResult,
+                      int32_t &curFails, int32_t &curBitDiffs) {
 
-  if (!fileStream.is_open()) {
-    std::cout << "file '" << inputFileName << "' failed to open. Exiting.\n";
-    return 1;
+  if (line[0] == '#') {
```
Comment (michaelrj-google) [inline libc/test/src/__support/str_to_float_comparison_test.cpp:75]: nit: here and below, LLVM style is to skip the braces on single line ifs
https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

**Review by michaelrj-google — COMMENTED** [review]
Overall LGTM with some minor style nits. The test works locally.

**Review by michaelrj-google — APPROVED** [review]
LGTM, thanks for getting this cleaned up!
