### PR TITLE
[analyzer] Do not destruct fields of unions

### LINKED ISSUE #119415: incorrect modeling of std::optional in cplusplus.NewDelete leads to incorrect warnings
The clang-analyzer incorrectly models the default `~` function for a `union` object (it calls `~` on some of the options, in contradiction to the C++ standard and actual implementation which does not call `~` on any fields). This results in declaration of double-frees (or lost memory) which don't actually occur at runtime for sample code like this.
`cat dtor-test.cpp`
```cpp
#include <iostream>
#include <optional>

class C {
  int *once;
public:
  C(int) {
    std::cout << "C Ctor" << std::endl;
    once = new int[3];
  }
  C(C&&) = delete;
  ~C() {
    std::cout << "C Dtor" << std::endl;
    delete[] once;
  }
};

int main() {
  std::optional<C> S{1};
  return 0;
}
```
```console
$ clang++ -fPIE -std=c++20 dtor-test.cpp  && ./a.out # demo that clang++ runs correctly
C Ctor
C Dtor
$ g++ -fPIE -std=c++20 dtor-test.cpp  && ./a.out # demo that g++ runs correctly
C Ctor
C Dtor
$ clang++ --analyze -analyzer-output=text -std=c++20 dtor-test.cpp # demo that clang-analyzer is wrong
dtor-test.cpp:14:5: warning: Attempt to free released memory [cplusplus.NewDelete]
   14 |     delete[] once;
      |     ^
```
from https://github.com/JuliaLang/julia/pull/56130#issuecomment-2518550050

### PR DESCRIPTION
**Pull request by vtjnash**
The C++ standard prohibits this implicit destructor call, leading to incorrect reports from clang-analyzer. This causes projects that use std::option (including llvm) to fail the cplusplus.NewDelete test incorrectly when run through the analyzer.

Fixes #119415

### CODE REVIEW

**Comment by vtjnash** [comment]
This roughly corresponds to 921bd20dddf5080cdb36f39c0162eb63b2d5325e in Sema, I think (@zygoloid). Maybe @tkremenek or @yronglin has done something in this part of the code recently too as reviewers and to merge this?

**Comment by gbaraldi** [comment]
Bump.
For reference, this is holding julia to an older LLVM version than needed ;)

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! The changes look correct to me, but I added the CFG and Analysis maintainers to give a final sign-off. Can you also add something to `clang/docs/ReleaseNotes.rst` so users know about the fix?

File: clang/test/Analysis/dtor-array.cpp [hunk 1]
```diff
@@ -377,3 +377,27 @@ void directUnknownSymbol() {
...
+      UnionDtor u1{.kind1{}};
+      UnionDtor u2{.kind2{}};
+      auto u3 = new UnionDtor{.kind1{}};
+      auto u4 = new UnionDtor{.kind2{}};
+      delete u3;
+      delete u4;
+  }
+
+  clang_analyzer_eval(unionDtorCalled == 4); // expected-warning {{TRUE}}
+  clang_analyzer_eval(InlineDtor::dtorCalled != 4); // expected-warning {{TRUE}}
```
Comment (steakhal) [inline clang/test/Analysis/dtor-array.cpp:401]:
```suggestion
```

The next line checks the equality of the expected value. That means this assertion is redundant.

**Review by steakhal — APPROVED** [review]
LGTM, thanks.

File: clang/test/Analysis/dtor-array.cpp (hunk 1 above)
Comment (vtjnash) [reply clang/test/Analysis/dtor-array.cpp]: Sure, makes sense. I had left it in as a hint of what the expected bad result would look like in case it breaks, but not necessary

File: clang/test/Analysis/NewDelete-checker-test.cpp [hunk 2]
```diff
@@ -441,3 +441,31 @@ void testLeakBecauseNTTPIsNotDeallocation() {
...
+    ~unique_ptr() {
+      delete q;
+    }
+  };
+
+  union custom_union_t {
+    unique_ptr<int> present;
+    char notpresent;
+    custom_union_t() : present(unique_ptr<int>()) {}
+    ~custom_union_t() {};
```
Comment (Xazax-hun) [inline clang/test/Analysis/NewDelete-checker-test.cpp:460]: Nit: redundant semi after the definition.

File: clang/test/Analysis/NewDelete-checker-test.cpp [hunk 3]
```diff
@@ -441,3 +441,31 @@ void testLeakBecauseNTTPIsNotDeallocation() {
...
+  };
+
+  void testUnionCorrect() {
+    custom_union_t a;
+    a.present.~unique_ptr<int>();
+  }
+
+  void testUnionLeak() {
```
Comment (Xazax-hun) [inline clang/test/Analysis/NewDelete-checker-test.cpp:468]: Could we also have a test where the custom union does not have a dtor declared for completeness? Or is that already covered somewhere?

File: clang/test/Analysis/dtor-array.cpp [hunk 4]
```diff
@@ -377,3 +377,26 @@ void directUnknownSymbol() {
 }
 
 }
+
+void testUnionDtor() {
```
Comment (Xazax-hun) [inline clang/test/Analysis/dtor-array.cpp:381]: I think this is a wonderful test but I would not expect to find it in dtor-array as this has nothing to do with arrays. Would it be possible to move it to a new file? Also to add a same test with a union that does not declare a dtor?

**Review by Xazax-hun — APPROVED** [review]
Overall looks good to me, some nits inline

File: clang/test/Analysis/NewDelete-checker-test.cpp (hunk 3 above)
Comment (vtjnash) [reply clang/test/Analysis/NewDelete-checker-test.cpp:468]: If I don't declare a dtor, it seems to be a C++ syntax error, so I cannot test that, but I will try to fix the other nits

**Review by Xazax-hun — APPROVED** [review]
LG, thanks!
