### PR TITLE
[flang][OpenMP] Rewrite min/max with more than 2 arguments

### LINKED ISSUE #144838: [flang][OpenMP] fujitsu 1037/1037_0048.f90 unexpected 'fir.is_present' op operand #0 must be any reference or box like
```
% flang -fopenmp 1037/1037_0048.f90
flang-21: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: loc(".../1037/1037_0048.f90":21:7): 'fir.is_present' op operand #0 must be any reference or box like, but got 'i32'
error: verification of lowering to FIR failed
```

### PR DESCRIPTION
**Pull request by kparzysz**
Given an atomic operation `w = max(w, x1, x2, ...)` rewrite it as `w = max(w, max(x1, x2, ...))`. This will avoid unnecessary non-atomic comparisons inside of the atomic operation (min/max are expanded inline).

In particular, if some of the x_i's are optional dummy parameters in the containing function, this will avoid any presence tests within the atomic operation.

Fixes https://github.com/llvm/llvm-project/issues/144838

### CODE REVIEW

File: flang/lib/Lower/OpenMP/Atomic.cpp [hunk 1]
```diff
@@ -237,6 +411,85 @@ makeMemOrderAttr(lower::AbstractConverter &converter,
...
+  assert(proc && "Call has no procedure designator");
+  return *proc;
+}
+
+static semantics::SomeExpr //
+genReducedMinMax(const semantics::SomeExpr &orig,
+                 const semantics::SomeExpr *atomArg,
+                 const std::vector<semantics::SomeExpr> &args) {
+  // Take a list of arguments to a min/max operation, e.g. [a0, a1, ...]
+  // One of the a_i's, say a_t, must be atom (or a convert of atom).
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/Atomic.cpp]: ultra-nit
```suggestion
  // One of the a_i's, say a_t, must be atomArg (or a convert of atomArg).
```

File: flang/lib/Lower/OpenMP/Atomic.cpp [hunk 2]
```diff
@@ -350,10 +603,28 @@ genAtomicUpdate(lower::AbstractConverter &converter,
...
-  semantics::SomeExpr input = *evaluate::GetConvertInput(assign.rhs);
-  std::vector<semantics::SomeExpr> args =
-      evaluate::GetTopLevelOperation(input).second;
+  semantics::SomeExpr rhs = assign.rhs;
+  semantics::SomeExpr input = *evaluate::GetConvertInput(rhs);
+  auto [opcode, args] = evaluate::GetTopLevelOperation(input);
   assert(!args.empty() && "Update operation without arguments");
+
+  const semantics::SomeExpr *atomArg = [&]() {
+    for (const semantics::SomeExpr &e : args) {
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/Atomic.cpp:614]:
```
/home/USER/llvm-project/flang/lib/Lower/OpenMP/Atomic.cpp:612:41: error: captured structured bindings are a C++20 extension [-Werror,-Wc++20-extensions]
  612 |     for (const semantics::SomeExpr &e : args) {
      |                                         ^
/home/USER/llvm-project/flang/lib/Lower/OpenMP/Atomic.cpp:608:17: note: 'args' declared here
  608 |   auto [opcode, args] = evaluate::GetTopLevelOperation(input);
      |                 ^
1 error generated.
```

With clang 19

File: flang/lib/Lower/OpenMP/Atomic.cpp [hunk 3]
```diff
@@ -41,6 +43,178 @@ namespace omp {
...
+    llvm_unreachable("Unhandled type");
+  }
+
+  const evaluate::DynamicType &type;
+
+private:
+  // Shorter names.
+  static constexpr auto Character = common::TypeCategory::Character;
+  static constexpr auto Complex = common::TypeCategory::Complex;
+  static constexpr auto Derived = common::TypeCategory::Derived;
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/Atomic.cpp:172]: Unused

File: flang/test/Lower/OpenMP/max-optional-parameters.f90 [hunk 4]
```diff
@@ -0,0 +1,24 @@
+!RUN: %flang_fc1 -emit-hlfir -fopenmp -fopenmp-version=52 %s -o - | FileCheck %s
+
+! Check that the presence tests are done outside of the atomic update
+! construct.
+
+!CHECK: %[[IS_PRESENT:[a-z0-9]+]] = fir.is_present
+!CHECK: %[[IF_VAL:[a-z0-9]+]] = fir.if %[[IS_PRESENT]] -> (f32) {
+!CHECK:   fir.result {{.*}} : f32
```
Comment (tblah) [inline flang/test/Lower/OpenMP/max-optional-parameters.f90]: Please could you add checks for the non-atomic max operation here so that it is clearer where that part goes

File: flang/test/Lower/OpenMP/max-optional-parameters.f90 [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+!CHECK:   %[[V10:[a-z0-9]+]] = arith.cmpf ogt, %[[ARG]], %[[IF_VAL]]
+!CHECK:   %[[V11:[a-z0-9]+]] = arith.select %[[V10]], %[[ARG]], %[[IF_VAL]]
+!CHECK:   omp.yield(%[[V11]] : f32)
+!CHECK: }
+
+subroutine f00(a, x, y)
+  real :: a
+  real, optional :: x, y
+  !$omp atomic update
+  a = max(x, a, y)
```
Comment (tblah) [inline flang/test/Lower/OpenMP/max-optional-parameters.f90]: Please also add a test for `min`

**Review by tblah — COMMENTED** [review]
This is really nice. Just minor comments.

File: flang/lib/Lower/OpenMP/Atomic.cpp (hunk 3 above)
Comment (kparzysz) [reply flang/lib/Lower/OpenMP/Atomic.cpp:172]: Fixed.

File: flang/lib/Lower/OpenMP/Atomic.cpp (hunk 2 above)
Comment (kparzysz) [reply flang/lib/Lower/OpenMP/Atomic.cpp:614]: Fixed.

File: flang/test/Lower/OpenMP/max-optional-parameters.f90 (hunk 5 above)
Comment (kparzysz) [reply flang/test/Lower/OpenMP/max-optional-parameters.f90]: Done.

File: flang/test/Lower/OpenMP/max-optional-parameters.f90 (hunk 4 above)
Comment (kparzysz) [reply flang/test/Lower/OpenMP/max-optional-parameters.f90]: Done.

File: flang/lib/Lower/OpenMP/Atomic.cpp (hunk 1 above)
Comment (kparzysz) [reply flang/lib/Lower/OpenMP/Atomic.cpp]: Fixed.

**Comment by kiranchandramohan** [comment]
I have not gone through this in detail. But why is evaluate processing done during Lowering? Can this canonicalization be performed in the semantics stage?

**Comment by kparzysz** [comment]
Summary: This PR fixes an actual issue, and I wanted to fix it before the LLVM release branch. There is another similar issue that does require rewriting in semantics, but I'd like to add some rewriting framework (which may take a bit of time), before I fix that.  Eventually both of these will be done in semantics.

Longer story:
The original idea was that `w = max(w, x, y)` is semantically correct, and the rewriting is done to generate correct MLIR, and the fix was developed accordingly.

Meanwhile, there is another issue, this time with reassociation: the expression `w = w .and. x .and. y`, which is parsed as `w = (w .and. x) .and. y`, is rejected since `w` is not a top-level argument.  Other compilers (gfortran, and Intel?) accept is even though the rejection is strictly speaking correct.  The rewriting of that will need to be done in semantics.

There is no convenient support for rewriting evaluate::Expr at the moment, and I was hoping to create something before going further with the rewriting.

**Review by tblah — APPROVED** [review]
LGTM if Kiran is happy

**Comment by kiranchandramohan** [comment]
> Eventually both of these will be done in semantics.

OK.

> Meanwhile, there is another issue, this time with reassociation: the expression w = w .and. x .and. y, which is parsed as w = (w .and. x) .and. y, is rejected since w is not a top-level argument. 

There is https://github.com/llvm/llvm-project/issues/138748 assigned to me. If you are working on this, please feel free to assign to yourself.

Thanks for the explanations.

**Review by kiranchandramohan — APPROVED** [review]
LG.
