### PR TITLE
[x86][AVX-VNNI] Fix VPDPBUSD Argument Types

### LINKED ISSUE #97271: [X86] VNNI intrinsics argument types don't match the actual computation
For example: `__m128i _mm_dpbusd_avx_epi32 (__m128i src, __m128i a, __m128i b)`

This takes 1 x <4 x i32> "src" and 2 x <16 x i8> "a * b" multiplication inputs but the clang/llvm intrinsics are defined as:

```
TARGET_BUILTIN(__builtin_ia32_vpdpbusd128, "V4iV4iV4iV4i", "ncV:128:", "avx512vl,avx512vnni|avxvnni")

  def int_x86_avx512_vpdpbusd_128 :
      ClangBuiltin<"__builtin_ia32_vpdpbusd128">,
      DefaultAttrsIntrinsic<[llvm_v4i32_ty], [llvm_v4i32_ty, llvm_v4i32_ty,
                             llvm_v4i32_ty], [IntrNoMem]>;
```

which means we require hardcoded mappings of the src/dst types for any combines that involve them.

### PR DESCRIPTION
**Pull request by BaiXilin**
Fixed intrinsic VPDPBUSD[,S]_128/256/512's argument types to match with the ISA.
Fixes part of #97271

### CODE REVIEW

File: llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp [hunk 1]
```diff
@@ -3902,8 +3902,9 @@ struct MemorySanitizerVisitor : public InstVisitor<MemorySanitizerVisitor> {
            ReturnType->getPrimitiveSizeInBits());
 
     if (I.arg_size() == 3) {
-      assert(ParamType == ReturnType);
-      assert(ParamType == I.getArgOperand(0)->getType());
+      FixedVectorType *AccumulatorType =
+          cast<FixedVectorType>(I.getOperand(0)->getType());
```
Comment (RKSimon) [inline llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp:3906]: (style) `auto *AccumulatorType = cast<FixedVectorType>(I.getOperand(0)->getType());`

**Review by RKSimon — COMMENTED** [review]
Don't the vpdpwss intrinsics need fixing to use vXi16 types as well?

**Review by RKSimon — CHANGES_REQUESTED** [review]
vpdpwss intrinsics need to be updated as well

**Comment by BaiXilin** [comment]
> Don't the vpdpwss intrinsics need fixing to use vXi16 types as well?

Yes, VNNI intrinsic `vpdpbsud[,s], vpdpbssd[,s], vpdpbuud[,s], vpdpwssd, vpdpwuud, vpdpwsud, vpdpwssd` are suffering from the same type problem.

Only `vpdpbusd` and `vpdpbusds` are fixed because:
1. I want to make sure that I'm doing it correctly,
3. The size of this one MR might be too large if I updated all of them

Should I separate other intrinsic into a few MRs (maybe 2) to keep the size of each manageable?

File: llvm/lib/IR/AutoUpgrade.cpp [hunk 2]
```diff
@@ -4148,6 +4148,34 @@ static Value *upgradeX86IntrinsicCall(StringRef Name, CallBase *CI, Function *F,
 
     Value *Args[] = {CI->getArgOperand(0), CI->getArgOperand(1),
                      CI->getArgOperand(2)};
+
+    // Input arguments types were incorrectly set to vectors of i32 before but
+    // they should be vectors of i8. Insert bit cast when encountering the old
+    // types
```
[the remark this answers is not in the document]
Comment (phoebewang) [reply llvm/lib/IR/AutoUpgrade.cpp:4154]: I see. But they are for masked ones only. Can you check if `llvm.x86.avx512.vpdpbusd.*` works with old types? I'm not sure if we should add autoupgrade code for them too.

[the remark this answers is not in the document]
Comment (BaiXilin) [reply llvm/lib/IR/AutoUpgrade.cpp:4154]: I will aim to have one test for each intrinsic and type combo

File: clang/include/clang/Basic/BuiltinsX86.td [hunk 3]
```diff
@@ -1108,27 +1108,27 @@ let Features = "avx512f,evex512", Attributes = [NoThrow, Const, RequiredVectorWi
 }
 
 let Features = "avx512vl,avx512vnni|avxvnni", Attributes = [NoThrow, Const, RequiredVectorWidth<128>] in {
-  def vpdpbusd128 : X86Builtin<"_Vector<4, int>(_Vector<4, int>, _Vector<4, int>, _Vector<4, int>)">;
+  def vpdpbusd128 : X86Builtin<"_Vector<4, int>(_Vector<4, int>, _Vector<16, char>, _Vector<16, char>)">;
```
Comment (RKSimon) [inline clang/include/clang/Basic/BuiltinsX86.td:1111]: Docs say that the first argument is treated as unsigned, second argument is treated as signed, so should this be:
```
X86Builtin<"_Vector<4, int>(_Vector<4, int>, _Vector<16, unsigned char>, _Vector<16, char>)"
```
(same for below)

**Review by RKSimon — CHANGES_REQUESTED** [review]
we usually include basic upgrade tests in CodeGen/X86 as well - but there should be an entry for every intrinsics we've changed - nothing as complex as msan - and it looks like we're missing avx_vnni-intrinsics-upgrade.ll entirely

**Comment by BaiXilin** [comment]
> we usually include basic upgrade tests in CodeGen/X86 as well - but there should be an entry for every intrinsics we've changed - nothing as complex as msan - and it looks like we're missing avx_vnni-intrinsics-upgrade.ll entirely

Phoebe pointed out the same problem. Working on it. Will test on every intrinsic & type combo.

File: llvm/lib/IR/AutoUpgrade.cpp [hunk 4]
```diff
@@ -546,19 +564,37 @@ static bool upgradeX86IntrinsicFunction(Function *F, StringRef Name,
...
+               .Case("vpdpbusds.256", Intrinsic::x86_avx512_vpdpbusds_256)
+               .Case("vpdpbusds.512", Intrinsic::x86_avx512_vpdpbusds_512)
+               .Default(Intrinsic::not_intrinsic);
+      if (ID != Intrinsic::not_intrinsic)
+        return upgradeX86MultiplyAddBytes(F, ID, NewFn);
+    }
+    return false; // No other 'x86.avx512.*'.
+  }
+
   if (Name.consume_front("avx512.mask.cmp.")) {
```
Comment (phoebewang) [inline llvm/lib/IR/AutoUpgrade.cpp:597]: Remove blank block.

File: llvm/lib/IR/AutoUpgrade.cpp [hunk 5]
```diff
@@ -4149,6 +4185,34 @@ static Value *upgradeX86IntrinsicCall(StringRef Name, CallBase *CI, Function *F,
...
+      if (VecWidth == 128)
+        NewArgType = VectorType::get(Builder.getInt8Ty(), 16, false);
+      else if (VecWidth == 256)
+        NewArgType = VectorType::get(Builder.getInt8Ty(), 32, false);
+      else if (VecWidth == 512)
+        NewArgType = VectorType::get(Builder.getInt8Ty(), 64, false);
+      else
+        llvm_unreachable("Unexpected vector bit width");
+
+      if (NewArgType) {
```
Comment (phoebewang) [inline llvm/lib/IR/AutoUpgrade.cpp:4210]: No need check the condition.

**Review by phoebewang — APPROVED** [review]
LGTM.

**Review by RKSimon — APPROVED** [review]
LGTM
