### PR TITLE
[asan][win] Fix CreateThread leak

### LINKED ISSUE #126541: [asan][win] 'CreateThread' leaks on Windows
When I used asan for detection on Windows, I found that oom occurred every time

Judging from ```vmmap```, there is a large amount of ```Private Data``` that has not been released after new.

Image

Image

Due to the call to ```Virtualalloc```, I spent a lot of time finding the cause of the problem

1.Call the ```Virtualalloc``` here to create space
https://github.com/llvm/llvm-project/blob/7ae78a6cdb6ce9ad1534ed10519649fb3d47aca9/compiler-rt/lib/asan/asan_thread.cpp#L96-L112

2.After ```start_routine```, Destory it
https://github.com/llvm/llvm-project/blob/7ae78a6cdb6ce9ad1534ed10519649fb3d47aca9/compiler-rt/lib/asan/asan_win.cpp#L138-L153

The problem here is that when a thread ends on Windows, it will not be called next
```
  t->Destroy();  // POSIX calls this from TSD destructor.
```

```
template <typename ThreadProcedure, bool Ex>
static unsigned long WINAPI thread_start(void* const parameter) throw()
{
   ...

    __try
    {
        ThreadProcedure const procedure = reinterpret_cast<ThreadProcedure>(context->_procedure);
        if constexpr (Ex)
        {
            _endthreadex(procedure(context->_context));
        }
```

```
static void __cdecl common_end_thread(unsigned int const return_code) throw()
{
    __acrt_ptd* const ptd = __acrt_getptd_noexit();
    if (!ptd)
    {
        ExitThread(return_code);
    }

    __acrt_thread_parameter* const parameter = ptd->_beginthread_context;
    if (!parameter)
    {
        ExitThread(return_code);
    }

    if (parameter->_initialized_apartment)
    {
        __acrt_RoUninitialize();
    }

    if (parameter->_thread_handle != INVALID_HANDLE_VALUE && parameter->_thread_handle != nullptr)
    {
        CloseHandle(parameter->_thread_handle);
    }

    if (parameter->_module_handle != INVALID_HANDLE_VALUE && parameter->_module_handle != nullptr)
    {
        FreeLibraryAndExitThread(parameter->_module_handle, return_code);
    }

```

Usually the system calls FreeLibraryAndExitThread to end the thread, As a result, memory cannot be released.
And because my test program happened to frequently create threads and end them normally quickly, it eventually led to oom.

### PR DESCRIPTION
**Pull request by GkvJwa**
Fix #126541

Since ```t->Destroy``` cannot be called after ```start_routine```(When calling standard thread_start in crt), the func is run in advance to avoid memory leaks and remain the same as before.

### CODE REVIEW

File: compiler-rt/lib/asan/asan_win.cpp [hunk 1]
```diff
@@ -143,9 +143,11 @@ static thread_return_t THREAD_CALLING_CONV asan_thread_start(void *arg) {
 
   ThreadStartParams params;
   t->GetStartData(params);
+  // The ExitThread will end the current thread, causing destroy to be unable to
+  // be called.
+  t->Destroy();
```
Comment (rnk) [inline compiler-rt/lib/asan/asan_win.cpp:148]: I think `t` is escaped above, so this isn't correct, it needs to happen after the thread runs.

If the user thread routine calls [ExitThread](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitthread) manually rather than returning, then the proper fix for ASan is probably to intercept ExitThread and do the deallocation there.

Also, it sounds like small memory leaks are expected when calling `ExitThread`, so maybe we shouldn't worry about this:
> A thread in an executable that is linked to the static C run-time library (CRT) should use _beginthread and _endthread for thread management rather than CreateThread and ExitThread. Failure to do so results in small memory leaks when the thread calls ExitThread.

**Review by rnk — CHANGES_REQUESTED** [review]

File: compiler-rt/lib/asan/asan_win.cpp (hunk 1 above)
Comment (GkvJwa) [reply compiler-rt/lib/asan/asan_win.cpp:148]: > I think `t` is escaped above, so this isn't correct, it needs to happen after the thread runs.
> 
> If the user thread routine calls [ExitThread](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitthread) manually rather than returning, then the proper fix for ASan is probably to intercept ExitThread and do the deallocation there.
> 
> Also, it sounds like small memory leaks are expected when calling `ExitThread`, so maybe we shouldn't worry about this:
> 
> > A thread in an executable that is linked to the static C run-time library (CRT) should use _beginthread and _endthread for thread management rather than CreateThread and ExitThread. Failure to do so results in small memory leaks when the thread calls ExitThread.

Yes, But different from CreateThread in static libraries in handling tlsdata issues
The memory allocated through ```Virtualalloc``` itself is not released.(56 bytes are leaked each time)
As a result, my unittest quickly omm

The following demo can be reproduced
```


#include <iostream>
#include <thread>

void test(int i)
{
	std::cout << i << std::endl;
}

int main()
{
	for (int i = 0; i < 10000; i++)
	{
		std::thread t(test, i);
		t.detach();
	}

	char a;
	std::cin >> a;
}

```

I'll try to hook `ExitThread` so that `t` can be released normally.

Comment (GkvJwa) [reply compiler-rt/lib/asan/asan_win.cpp]: If it's just a dynamic library, can modify ```asan_thread_exit```. Here intercept ```ExitThread``` for general purpose

You can review it when you have time

File: compiler-rt/lib/asan/asan_win.cpp [hunk 2]
```diff
@@ -166,6 +190,15 @@ INTERCEPTOR_WINAPI(HANDLE, CreateThread, LPSECURITY_ATTRIBUTES security,
                             thr_flags, tid);
 }
 
+INTERCEPTOR_WINAPI(void, ExitThread, DWORD dwExitCode) {
+  DWORD key = atomic_load(&g_native_tls_key, memory_order_relaxed);
+  AsanThread *t = (AsanThread *)TlsGetValue(key);
```
Comment (vitalybuka) [inline compiler-rt/lib/asan/asan_win.cpp:195]: Isn't this  the same as in SetCurrentThread ?

Comment (GkvJwa) [reply compiler-rt/lib/asan/asan_win.cpp:195]: Different, SetCurrentThread calls AsanTSDSet to save the context

Comment (GkvJwa) [reply compiler-rt/lib/asan/asan_win.cpp:195]: Of course there is another problem with the log
```
  CHECK(t->context());
  VReport(2, "SetCurrentThread: %p for thread %p\n", (void *)t->context(),
          (void *)GetThreadSelf());
  // Make sure we do not reset the current AsanThread.
  CHECK_EQ(0, AsanTSDGet());
---
// In contrast to POSIX, on Windows GetCurrentThreadId()
// returns a system-unique identifier.
tid_t GetTid() {
  return GetCurrentThreadId();
}

uptr GetThreadSelf() {
  return GetTid();
}
```
GetCurrentThreadId is returned a handle on Windows

Comment (GkvJwa) [reply compiler-rt/lib/asan/asan_win.cpp]: > So why we can't just GetCurrentThread()->Destroy()?

Thanks, review it again when you have time

File: compiler-rt/lib/asan/asan_win.cpp [hunk 3]
```diff
@@ -166,6 +165,14 @@ INTERCEPTOR_WINAPI(HANDLE, CreateThread, LPSECURITY_ATTRIBUTES security,
                             thr_flags, tid);
 }
 
+INTERCEPTOR_WINAPI(void, ExitThread, DWORD dwExitCode) {
+  AsanThread *t = (AsanThread *)__asan::GetCurrentThread();
+  if (t) {
```
Comment (vitalybuka) [inline compiler-rt/lib/asan/asan_win.cpp:170]: this code don't use {} in cases like these

**Review by vitalybuka — APPROVED** [review]
LGTM, but It would be nice to get from @rnk who requested changes.

**Review by rnk — APPROVED** [review]
Thanks, I think this approach should work.
