### PR TITLE
[BOLT][Linux] Support ORC for alternative instructions

### LINKED ISSUE #87052: [BOLT] Error when reading .orc_unwind_ip with CONFIG_PARAVIRT=y
With  CONFIG_PARAVIRT=y (default)
```
llvm-bolt -o p.b vmlinux
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: de0abc0983d355bbd971c5c571ba4c209a0c63ea
BOLT-INFO: Linux kernel binary detected
BOLT-INFO: first alloc address is 0x0
BOLT-WARNING: debug info will be stripped from the binary. Use -update-debug-sections to keep it.
BOLT-INFO: static input executable detected
BOLT-INFO: disabling -align-macro-fusion in non-relocation mode
BOLT-INFO: enabling lite mode
BOLT-ERROR: symbol seen in the middle of the function srso_untrain_ret/1(*2). Skipping.
BOLT-ERROR: symbol seen in the middle of the function retbleed_untrain_ret/1(*2). Skipping.
BOLT-WARNING: unable to disassemble instruction at offset 0x50 (address 0xffffffff81000050) in function pvh_start_xen/1
BOLT-WARNING: unable to disassemble instruction at offset 0x4 (address 0xffffffff81054a94) in function native_lkgs/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0xe (address 0xffffffff81095cce) in function native_load_gs_index/1(*2)
BOLT-WARNING: function module_init_section has an object detected in a padding region at address 0xffffffff811a0e8f
BOLT-WARNING: function pcpu_fc_alloc/1(*2) has an object detected in a padding region at address 0xffffffff8351072a
BOLT-WARNING: reference in the middle of instruction detected in function xen_read_msr/1(*2) at offset 0x33
BOLT-ERROR: while running linux-kernel-rewriter in pre-CFG state: no instruction at address 0xffffffff81003187 in .orc_unwind_ip
```

Without CONFIG_PARAVIRT
```
llvm-bolt -o p.b vmlinux
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: de0abc0983d355bbd971c5c571ba4c209a0c63ea
BOLT-INFO: Linux kernel binary detected
BOLT-INFO: first alloc address is 0x0
BOLT-WARNING: debug info will be stripped from the binary. Use -update-debug-sections to keep it.
BOLT-INFO: static input executable detected
BOLT-INFO: disabling -align-macro-fusion in non-relocation mode
BOLT-INFO: enabling lite mode
BOLT-ERROR: symbol seen in the middle of the function srso_untrain_ret/1(*2). Skipping.
BOLT-ERROR: symbol seen in the middle of the function retbleed_untrain_ret/1(*2). Skipping.
BOLT-WARNING: unable to disassemble instruction at offset 0x50 (address 0xffffffff81000050) in function pvh_start_xen/1
BOLT-WARNING: unable to disassemble instruction at offset 0x65 (address 0xffffffff81021d65) in function start_thread_common/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x3da (address 0xffffffff8102226a) in function __switch_to
BOLT-WARNING: unable to disassemble instruction at offset 0x3c1 (address 0xffffffff81022911) in function do_arch_prctl_64
BOLT-WARNING: unable to disassemble instruction at offset 0x2c (address 0xffffffff81022c0c) in function load_gs_index/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x158 (address 0xffffffff8102db28) in function ia32_restore_sigcontext/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x2c (address 0xffffffff8103eafc) in function load_gs_index/2(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x39 (address 0xffffffff810ad6e9) in function mm_release/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x1d2 (address 0xffffffff81e494d2) in function restore_processor_state
BOLT-WARNING: function module_init_section has an object detected in a padding region at address 0xffffffff8118f1df
BOLT-WARNING: function pcpu_fc_alloc/1(*2) has an object detected in a padding region at address 0xffffffff834e87d7
BOLT-INFO: parsed 428244 ORC entries
BOLT-INFO: parsed 4595 static call entries
BOLT-INFO: parsed 1543 exception table entries
BOLT-INFO: parsed 10201 bug table entries
BOLT-WARNING: alternative instruction sequence found in function .altinstr_replacement/1
BOLT-ERROR: while running linux-kernel-rewriter in pre-CFG state: error reading .altinstructions
```
6.8.2 kernel compiled with clang-18 or gcc-13. Same error " no instruction at address 0xffffffff8100xxxxx in .orc_unwind_ip" with official kernels from archlinux stable repo.

### PR DESCRIPTION
**Pull request by maksfb**
Alternative instruction sequences in the Linux kernel can modify the stack and thus they need their own ORC unwind entries. Since there's only one ORC table, it has to be "shared" among multiple instruction sequences. The kernel achieves this by putting a restriction on instruction boundaries. If ORC state changes at a given IP, only one of the alternative sequences can have an instruction starting/ending at this IP. Then, developers can insert NOPs to guarantee the above requirement is met.

The most common use of ORC with alternatives is "pushf; pop %rax" sequence used for paravirtualization.

Before we implement a better support for alternatives, we can safely skip ORC entries associated with them.

Fixes #87052.

### CODE REVIEW

**Comment by maksfb** [comment]
Test case is WIP.

File: bolt/lib/Core/BinaryFunction.cpp [hunk 1]
```diff
@@ -4472,6 +4472,18 @@ MCInst *BinaryFunction::getInstructionAtOffset(uint64_t Offset) {
   }
 }
 
+MCInst *BinaryFunction::getInstructionContainingOffset(uint64_t Offset) {
+  assert(CurrentState == State::Disassembled && "Wrong function state");
+
+  if (Offset > Size)
```
Comment (dcci) [inline bolt/lib/Core/BinaryFunction.cpp:4478]: interesting, is this something that can ever happen, or we want to make it an assertion too?

File: bolt/lib/Rewrite/LinuxKernelRewriter.cpp [hunk 2]
```diff
@@ -313,6 +310,9 @@ class LinuxKernelRewriter final : public MetadataRewriter {
     if (Error E = readAltInstructions())
       return E;
 
+    if (Error E = readORCTables())
+      return E;
```
Comment (dcci) [inline bolt/lib/Rewrite/LinuxKernelRewriter.cpp:314]: we might want to add a comment here explaining why there's this order, i.e. we first have to read `.parainstruction` and `.altrinstruction` as they're a dependency for ORC

File: bolt/lib/Rewrite/LinuxKernelRewriter.cpp [hunk 3]
```diff
@@ -563,11 +563,28 @@ Error LinuxKernelRewriter::readORCTables() {
     if (!BF->hasInstructions())
       continue;
 
-    MCInst *Inst = BF->getInstructionAtOffset(IP - BF->getAddress());
-    if (!Inst)
+    const uint64_t Offset = IP - BF->getAddress();
+    MCInst *Inst = BF->getInstructionAtOffset(Offset);
+    if (!Inst) {
+      // Check if there is an alternative instruction(s) at this IP. Multiple
```
Comment (dcci) [inline bolt/lib/Rewrite/LinuxKernelRewriter.cpp:569]: Great comment, thanks.

**Review by dcci — COMMENTED** [review]
Some comments, but heading in a good direction.

File: bolt/lib/Core/BinaryFunction.cpp (hunk 1 above)
Comment (maksfb) [reply bolt/lib/Core/BinaryFunction.cpp:4478]: > is this something that can ever happen

It depends on how we define the interface. If currently someone accidentally calls this with a large offset, they will get no instruction. Technically, this can happen when a function has a padding space that is considered a part of the function, but does not contain any instructions. That's why we have `Size` and `MaxSize` for `BinaryFunction`.

Comment (dcci) [reply bolt/lib/Core/BinaryFunction.cpp:4478]: Let's leave it like this for now, and maybe switch to an assertion later on.

**Review by dcci — APPROVED** [review]
