### PR TITLE
[mlir][scf] Fix trip count signedness and overflow in SCF Utils

### LINKED ISSUE #178506: Trip count handling in SCF Utils uses incorrect signedness and risks overflow
The trip count computation and usage in mlir/lib/Dialect/SCF/Utils/Utils.cpp has several issues:                                                                                        
                                                                                                                                                                                          
  1. `getConstLoopTripCounts` returns `SmallVector<int64_t>` but should return `SmallVector<uint64_t>` since trip counts are inherently unsigned                                          
  2. Multiple call sites use `APInt::getZExtValue()` which may overflow for large trip counts (e.g., in `loopUnrollFull`, `loopUnrollByFactor`, `loopUnrollJamByFactor`)                  
  3. Inconsistent signedness: `loopUnrollJamByFactor` mixes `getSExtValue()` and `getZExtValue()` on the same APInt                                                                       
  4. Arithmetic operations like `lbCst + tripCountEvenMultiple * stepCst` may overflow with int64_t                                                                                       
                                                                                                                                                                                          
  All trip count handling should consistently use uint64_t and include proper overflow checks.

### PR DESCRIPTION
**Pull request by jhalakpatel**
Change `getConstLoopTripCounts` to return `SmallVector<llvm::APInt>` instead                                                                     
  of `SmallVector<int64_t>` to properly handle signedness and prevent potential                                                                    
  overflow issues. Update all call sites to use APInt methods and uint64_t for                                                                     
  intermediate calculations.                                                                                                                       
                                                                                                                                                   
  - Use APInt::isOne() instead of direct comparison with 1                                                                                         
  - Store trip counts in uint64_t to avoid overflow in modulo operations                                                                           
  - Remove TODOs about signedness and overflow issues that are now fixed                                                                           
                                                                                                                                                   
  Fixes #178506

### CODE REVIEW

File: mlir/lib/Dialect/SCF/Utils/Utils.cpp [hunk 1]
```diff
@@ -504,9 +516,13 @@ LogicalResult mlir::loopUnrollFull(scf::ForOp forOp) {
   const APInt &tripCount = *mayBeConstantTripCount;
   if (tripCount.isZero())
     return success();
-  if (tripCount.getZExtValue() == 1)
+  // Check for overflow before extracting trip count.
+  if (tripCount.getActiveBits() > 64)
```
[the remark this answers is not in the document]
Comment (jhalakpatel) [reply mlir/lib/Dialect/SCF/Utils/Utils.cpp]: This comment applies to many other instances in this PR.

File: mlir/include/mlir/Dialect/SCF/Utils/Utils.h [hunk 2]
```diff
@@ -251,8 +251,7 @@ FailureOr<scf::ParallelOp> parallelLoopUnrollByFactors(
 /// Get constant trip counts for each of the induction variables of the given
 /// loop operation. If any of the loop's trip counts is not constant, return an
 /// empty vector.
-/// TODO(#178506): Should return SmallVector<uint64_t> for correct signedness.
-llvm::SmallVector<int64_t>
+llvm::SmallVector<uint64_t>
```
Comment (joker-eph) [inline mlir/include/mlir/Dialect/SCF/Utils/Utils.h]: > Changed getConstLoopTripCounts return type from SmallVector<int64_t> to SmallVector<uint64_t> since trip counts are inherently unsigned.


We don't use C++ unsigned to mark any indication about the sign of the return value.

The Google C++ guide explains this in detail, I won't just redo the argument here: https://google.github.io/styleguide/cppguide.html#Integer_Types

Comment (matthias-springer) [reply mlir/include/mlir/Dialect/SCF/Utils/Utils.h]: Interesting, I asked for this change in #178060. What does this rule mean in practice?

If I interpret the style guide correctly, you should you always use `int64_t` instead of `uint64_t` when the value represents a number (and not a bag of bits).

In the case of trip counts: let's say I have a trip count stored in an `int64_t`, but it exceeds the maximum value (but it would be in range for `uint64_t`). If you have a check such a `tripCount > 0`, you would get "false" in case of `int64_t`, whereas, for `uint64_t` it would produce the correct result ("true"). So it looks like `uint64_t` would be the better choice here?

Should the entire API operate on `APInt` instead?

Comment (matthias-springer) [reply mlir/include/mlir/Dialect/SCF/Utils/Utils.h]: > however at this point we could ask if 64 bits is enough or is it valid to have larger numbers using i128 for example?

`scf.for` supports arbitrary integer types, so I'd say 64 bits are not generally enough.

I checked the implementation and all uses of this function here (`getConstLoopTripCounts`) within MLIR (there is only 1 call site). I think we should change the return type to `llvm::SmallVector<APInt>`. It's a small change.

File: mlir/lib/Dialect/SCF/Utils/Utils.cpp [hunk 3]
```diff
@@ -397,14 +397,26 @@ FailureOr<UnrolledLoopInfo> mlir::loopUnrollByFactor(
...
-    int64_t tripCountEvenMultiple =
-        constTripCount->getZExtValue() -
-        (constTripCount->getZExtValue() % unrollFactor);
-    // TODO(#178506): This may overflow when computing upperBoundUnrolledCst.
-    int64_t upperBoundUnrolledCst = lbCst + tripCountEvenMultiple * stepCst;
-    int64_t stepUnrolledCst = stepCst * unrollFactor;
+    // Check for overflow before extracting trip count.
+    if (constTripCount->getActiveBits() > 64)
+      return failure();
+    uint64_t tripCountValue = constTripCount->getZExtValue();
```
Comment (matthias-springer) [inline mlir/lib/Dialect/SCF/Utils/Utils.cpp]: I think these could also all be `APInt`, then we don't need any bitwidth checks. In the end, we create an `arith::ConstantOp` with the same type as the `scf.for` (which has the same bitwidth as the `APInt`, so that works out nicely).

File: mlir/lib/Dialect/SCF/Utils/Utils.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (matthias-springer) [reply mlir/lib/Dialect/SCF/Utils/Utils.cpp]: `tripCount.getZExtValue() == 1` ==> `tripCount.isOne()`

File: mlir/lib/Dialect/SCF/Utils/Utils.cpp [hunk 4]
```diff
@@ -1563,22 +1589,30 @@ bool mlir::isPerfectlyNestedForLoops(
...
     return {};
-  // TODO(#178506): The result should be SmallVector<uint64_t> and use uint64_t
-  // for trip counts.
-  llvm::SmallVector<int64_t> tripCounts;
+
+  // Determine signedness from the loop operation if possible.
+  // For scf::ForOp, use the loop's comparison signedness via getUnsignedCmp().
+  // Otherwise, default to signed (most MLIR integer types are signed).
+  bool isSigned = true;
+  if (auto forOp = dyn_cast<scf::ForOp>(loopOp.getOperation()))
```
[the remark this answers is not in the document]
Comment (jhalakpatel) [reply mlir/lib/Dialect/SCF/Utils/Utils.cpp]: @matthias-springer I have address all the suggestions mentioned in this and other review comments.

**Review by matthias-springer — APPROVED** [review]
