### PR TITLE
[llvm][OpenMP] Add implicit cast to omp.atomic.read

### LINKED ISSUE #112908: [flang][OpenMP] support arrays of atomic numbers
Support for atomic operations on scalar complex variables is being added in https://github.com/llvm/llvm-project/pull/92364.

flang also supports atomic operations which read a single element from an array. The openmp standard says that the lhs and rhs of the assignment must be "scalar variables of intrinsic type" (OpenMP 5.2 section 4.3.1.3). The result of the expression on the rhs must be scalar but the expression might involve arrays.

Currently (and after #92364) Flang will crash on an assertion on this code:
```
program atomic_array
  complex :: x(2)
  complex :: y
  !$omp parallel
    !$omp atomic read
      y = x(1)
  !$omp end parallel
end program
```

Reproduce with `flang -fopenmp file.f90`.

CC @NimishMishra

### PR DESCRIPTION
**Pull request by NimishMishra**
Should the operands of `omp.atomic.read` differ, emit an implicit cast. In case of `struct` arguments, extract the 0-th index, emit an implicit cast if required, and store at the destination.

Fixes https://github.com/llvm/llvm-project/issues/112908

### CODE REVIEW

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -265,6 +265,32 @@ computeOpenMPScheduleType(ScheduleKind ClauseKind, bool HasChunks,
   return Result;
 }
 
+/// Emit an implicit cast to convert \p XRead to type of variable \p V
+static llvm::Value *emitImplicitCast(IRBuilder<> &Builder, llvm::Value *XRead,
+                                     llvm::Value *V) {
+  llvm::Type *XReadType = XRead->getType();
+  llvm::Type *VType = V->getType();
+  if (llvm::AllocaInst *vAlloca = dyn_cast<llvm::AllocaInst>(V))
+    VType = vAlloca->getAllocatedType();
```
Comment (tblah) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:274]: Why would AllocaInst::getAllocatedType be different to the value's type?

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 2]
```diff
@@ -265,6 +265,32 @@ computeOpenMPScheduleType(ScheduleKind ClauseKind, bool HasChunks,
...
+
+  if (XReadType->isStructTy() && VType->isStructTy())
+    // No need to extract or convert. A direct
+    // `store` will suffice.
+    return XRead;
+
+  if (XRead->getType()->isStructTy())
```
Comment (tblah) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:281]: Why not use `XReadType` here?

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 3]
```diff
@@ -265,6 +265,32 @@ computeOpenMPScheduleType(ScheduleKind ClauseKind, bool HasChunks,
...
+    XRead = Builder.CreateExtractValue(XRead, /*Idxs=*/0);
+  if (VType->isIntegerTy() && XReadType->isFloatingPointTy())
```
Comment (tblah) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:283]: nit: I think this can be `else if`

**Review by tblah — COMMENTED** [review]
Thanks for circling back and fixing this. I have a few minor comments

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 4]
```diff
@@ -265,6 +265,32 @@ computeOpenMPScheduleType(ScheduleKind ClauseKind, bool HasChunks,
...
+    XRead = Builder.CreateFPToSI(XRead, VType);
+  else if (VType->isFloatingPointTy() && XReadType->isIntegerTy())
+    XRead = Builder.CreateSIToFP(XRead, VType);
```
Comment (Meinersbur) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:286]: An atomic read should not have implicit semantics of converting between int and fp. That could cause some trouble, e.g. rounding.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 5]
```diff
@@ -8076,6 +8102,8 @@ OpenMPIRBuilder::createAtomicRead(const LocationDescription &Loc,
     }
   }
   checkAndEmitFlushAfterAtomic(Loc, AO, AtomicKind::Read);
+  if (XRead->getType() != V.Var->getType())
+    XRead = emitImplicitCast(Builder, XRead, V.Var);
```
Comment (Meinersbur) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:8106]: The code above seems to already handle casting?

**Review by Meinersbur — COMMENTED** [review]
I wonder we should use #101966 instead which handles type punning consistently by itself (https://github.com/llvm/llvm-project/blob/ee84c6bb3146d25f21c14d6d8e0abb794683f5ec/llvm/lib/Transforms/Utils/BuildBuiltins.cpp#L123-L131)

**Comment by NimishMishra** [comment]
> I wonder we should use #101966 instead which handles type punning consistently by itself

I think we can. But how do go ahead with changes in Clang codegen? Will there be opposition from community if we try to merge a solution like https://github.com/llvm/llvm-project/pull/101966?

**Comment by Meinersbur** [comment]
I would remove the changes to Clang and AtomicsExpandPass (in the first iteration). Those were for checking whether the API is sufficiently general.

**Comment by Meinersbur** [comment]
I added `emitAtomicLoadBuiltin` and `emitAtomicStoreBuiltin` into #101966, and use it within OpenMPIRBuilder. The patch is not ready yet, tests are not updated and code duplication needs to be reduced.

However, I hope the benfits become clear:
 * Just one case instead of multiple depending on data type.
 * All data types (incl. complete) able to use the cmpxchg,load,store,atomicrmw etc instead of the libcall fallback. Only the data size matters, not the type.

**Comment by NimishMishra** [comment]
> I added `emitAtomicLoadBuiltin` and `emitAtomicStoreBuiltin` into #101966, and use it within OpenMPIRBuilder. The patch is not ready yet, tests are not updated, tits probably not yet completely correct, and code duplication needs to be reduced.


Thanks for your work on this. I went through the patch, and it does seem this approach is better. I see this PR can also help with sized libcalls. 

I wonder whether work on this needs a separate PR, or whether we can merge with the current PR? Since, it is more generic and solves multiple issues at once. I am okay with picking this work and opening a new PR, where we can discuss improvements and iterate over it. Let me know what you think.

**Comment by NimishMishra** [comment]
> I wonder whether work on this needs a separate PR, or whether we can merge with the current PR? Since, it is more generic and solves multiple issues at once. I am okay with picking this work and opening a new PR, where we can discuss improvements and iterate over it. Let me know what you think.

I discussed this with @kiranktp. We will work on https://github.com/llvm/llvm-project/pull/101966 as a separate PR, since this approach can help with multiple issues (like sized libcalls in atomic).

If everyone is okay, we can merge this current PR for the time being. This would unblock progress towards removal of the experimental message currently.

**Comment by tblah** [comment]
@NimishMishra is this patch still needed?

**Comment by NimishMishra** [comment]
> @NimishMishra is this patch still needed?

I'm sorry; this fell off my radar. Yes, without this, the test-cases in https://github.com/llvm/llvm-project/issues/112908 will segfault. I have addressed your comments, and have added a TODO based on what Michael suggested (and added that to our internal tracking system too). I'll work on integrating Michael's solution. In the meantime, we can probably go with this.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp (hunk 3 above)
Comment (NimishMishra) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:283]: Actually if you consider the test case:

```
program atomic_array
  complex :: x(2)
  integer :: y

  x(1) = (1.0, 1.0)
  x(2) = (2.0, 2.0)
  !$omp parallel
    !$omp atomic read
      y = x(1)
  !$omp end parallel
  print *, y
end program
```

Then we need to extract the real component of `complex` into a `float`, and store it to `integer`.  We thus need this check in place to ensure the conversion takes place.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp (hunk 1 above)
Comment (NimishMishra) [reply llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:274]: Because the type of atomic pointer by default is `ptr`. We would like to know the real type (i.e. `AllocatedType`) in order to know whether we need a conversion or an extraction (in case of complex type).

**Review by tblah — APPROVED** [review]
LGTM, thanks!
