### PR TITLE
[clang-tidy] Fix readability-identifier-naming FP with DefaultCase on function templates

### LINKED ISSUE #189755: clang-tidy readability-identifier-naming reports false-positive for template methods
main.cpp:
```cpp
class foo {
public:
    template <typename t>
    void doStuff() {}
};

int main() {
    return 0;
}
```
.clang-tidy:
```yml
Checks: >
  readability-identifier-naming,
# I set all options I know that could possibly have any affect on this
CheckOptions:
  - { key: readability-identifier-naming.DefaultCase,                    value: lower_case }
  - { key: readability-identifier-naming.FunctionCase,                   value: camelBack }
  - { key: readability-identifier-naming.MemberCase,                     value: camelBack }
  - { key: readability-identifier-naming.ClassMemberCase,                value: camelBack }
  - { key: readability-identifier-naming.MethodCase,                     value: camelBack }
  - { key: readability-identifier-naming.ClassMethodCase,                value: camelBack }
```
Running `clang-tidy main.cpp` outputs only 1 warning instead of 0:
```
(...)/main.cpp:4:10: warning: invalid case style for identifier 'doStuff' [readability-identifier-naming]
    4 |     void doStuff() {}
      |          ^~~~~~~
      |          do_stuff
```
Meanwhile, turning `doStuff()` into a regular method doesn't produce any warnings, as expected

I also found out that this behavior first appeared in [LLVM 22.1.0-rc1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-22.1.0-rc1), clang-tidy from [LLVM 21.1.8](https://github.com/llvm/llvm-project/releases/tag/llvmorg-21.1.8) outputs no warnings

### PR DESCRIPTION
**Pull request by zeyi2**
Closes #189755

### CODE REVIEW

File: clang-tools-extra/clang-tidy/utils/RenamerClangTidyCheck.cpp [hunk 1]
```diff
@@ -270,6 +270,10 @@ class RenamerClangTidyVisitor
   }
 
   bool VisitNamedDecl(NamedDecl *Decl) {
+    if (isa<FunctionTemplateDecl, ClassTemplateDecl, VarTemplateDecl,
+            TypeAliasTemplateDecl>(Decl))
+      return true;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/utils/RenamerClangTidyCheck.cpp]: This is a strange fix (or I don't get something)
We don't rename additional decls, but shouldn't they just don't be diagnosted at all?
> The issue seems to be that they are also visited as FunctionTemplateDecl, and after https://github.com/llvm/llvm-project/commit/2ffaf9d676e6ed2cffc5312d3306f8345bc5a4e5 that wrapper decl started falling back to DefaultCase, which produces an identifier diagnostic before the CXXMethodDecl path.

Can we stop visiting them in IdentifierNamingCheck and instead follow CXXMethodDecl path before "Template" path

Comment (zeyi2) [reply clang-tools-extra/clang-tidy/utils/RenamerClangTidyCheck.cpp]: Fixed, sorry for the mistake I made.

File: clang-tools-extra/clang-tidy/readability/IdentifierNamingCheck.cpp [hunk 2]
```diff
@@ -1303,6 +1303,10 @@ StyleKind IdentifierNamingCheck::findStyleKind(
       return SK_Function;
   }
 
+  if (isa<FunctionTemplateDecl, ClassTemplateDecl, VarTemplateDecl,
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/readability/IdentifierNamingCheck.cpp]: Can we add comment here why we are skipping these as "invalid"

**Review by vbvictor — APPROVED** [review]
