### PR TITLE
[clang][AST] Handle dependent representation of call to function with explicit object parameter in CallExpr::getBeginLoc()

### LINKED ISSUE #126720: [Clang] Frontend crash compiling struct/class method with explicit object parameters
Frontend crash regression when compiling this code. Required flags: -std=c++23/26 (for explicit object parameters)
Works on 19.1.0 even with assertions, crashes on master(both with assertions and without)
```cpp
void operator*(auto) {}

template <typename T>
struct Quaternionz {
    void inverse(this Quaternionz<T>& a) {
        a.inverse() * 0;
    }
};

int main() {}
```
Quaternionz can be a class as well, and inverse can just accept ``` (this Quaternionz& a)``` and still crash.  Function/object names can be shortened. 
Looks like it is an issue with parsing explicit object parameters.

Godbolt link: https://clang.godbolt.org/z/1cYvc66j4
[Full godbolt link](https://clang.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBJcpAAOqAqETgwe3r56icmOAkEh4SxRMVxxdpgOqUIETMQE6T5%2BZZj2uQzVtQT5YZHRsbY1dQ2ZZYNdwT1FfaUAlLaoXsTI7BwAbqh46ADUqPHRTETEAFQQTF5EM1smAOxW1wAiJhoAgk/PBJgs8QYfVwDMbgIAE89sw2FsAComP7YN4KAjELwOLYARS8B2iDFSAC8rrc3ltCVt1pstsFVtElBACAg8ApUeiPsQsQJsdC3FCYeYAGxbJiXG5WF5EkV8gB05MpmAglyOWw00KFzxFN0eL1Vireb2CBC2LCYwRleLuaueHDmtE4AFZeH4OFpSKhOG5rNYtgoFktMFczH8eKQCJpzXMANYgP5WsVmSR/ACcAA4/kmuFaY9c/vpOJJbUHHZxeAoQBoA0G5nBYDBEChUF86NFyJQ0LX6DFkAYjFxY1wmAolHU%2BHQmYWIBFcxFgrUgZx/ePmMQgQB5CLaCqB7i8JtsQQLhi0Kf23hYCJeYBuMS0Qvr0hYfVGcQH694YirvAUy8OzCqCrnFYOnUtXNaDwCJiEnDwsFzBE8BYadeApYgIiSTB7k%2BQxgCAoxSz4AxgAUAA1PBMAAdwXUFYJkQQRDEdgpAo%2BQlDUXNdDidtjFdSx9GAwtIDmXY2kvABaeF0Ghe5TEsaxfV4VB4OITZMG4mVbBaF9nAgVxhiaUhAgmQpiiyJIUgETSDJyVJuj06ZlNaKoxhM5obIEDo6gs3oSgGTp7I8lzdLciQ5g9RZln8zMOBtUg7QdJ0OC2VR425ATuUkLY2zQrZOzFLgxQ0LZTl7aJ%2BMuCBcEIEgfT9GZeDXLQZlDcMsvjaN03jVNEw0a4uDMULs1IGCrWLSLpPzWwixLA8y0rCAkAWAh4nOBsICbeI62IUJWBWOKEqSlLWNyhEvAYENKu0/BDk2PR%2BEo0RxC4bk6MUFR1AfZjSCI0D4lgi1rRzB9ooXc45t1VAqFi%2BLEuS1KjHS2NMuy3Kez7Qrco8ZtonKrhjuq4NSAQTAmCwGIlMtDger6gbc2igtRqx2rSDDP4zCjDQuHjeNrmjSQrW5P5uWuUK/h%2BqLhpp0hyygSakCWlaFqllsUFYgB9BGCtSBQFf2w6B1oIdKFHB9Z0nciDfnJcVwccjN0YAgdz3XMjxPM9aAvcibzQ%2B8HXwZ9KjfXNP2/D5yP/YmHSAkCwIwX8qrkmCr3gxClBQ290OCUBxuwphcII4jSMYcjLuEa6aOkfOHsY56QC61iUHYmxQ8U3j4n4zghIIES/jEmupMdWT5Pr6zVL8dSGHcTxGn8YfXKmdzsiMtJR5GBJDLaSf9IcgfnPqeetPKSonLGFerPhTyt70I%2BfIKPyMfmIKaK%2BsLBaGmLNvBna0ryxHVa2DWjtykrDnRzGpY6oMzFFaVMnVYySF9PGWMZg7rE1JiAfqEUKbDULMWEWYspogBmoDGWNZlotjWmwTgz9tqQ2AHtREh1jqYFOiQc6cR85URusXWQpcnoOl0F1N6TAPrrjvuFQaeYOD/VmucHYIMyEQ12u/FWAh6TfyKijQhaNzAM0AeNOYuN8Z9CJlmXgZMUG/TQdTIBdNwyMzAZICBUC/gwLgfzB%2BIiqrmOJmYZxlMxo1TmPBZIzhJBAA)

### PR DESCRIPTION
**Pull request by HighCommander4**
This fixes a crash where CallExpr::getBeginLoc() tries to access the
first argument of a CallExpr representing a call to a function with
an explicit object parameter, assuming that a first argument exists
because it's the object argument.

This is the case for non-dependent calls, but for dependent calls
the object argument is part of the callee (the semantic analysis
that separates it out has not been performed yet) and so there may
not be a first argument.

Fixes https://github.com/llvm/llvm-project/issues/126720

### CODE REVIEW

File: clang/lib/AST/Expr.cpp [hunk 1]
```diff
@@ -1648,8 +1648,11 @@ SourceLocation CallExpr::getBeginLoc() const {
   if (const auto *Method =
           dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl());
       Method && Method->isExplicitObjectMemberFunction()) {
-    assert(getNumArgs() > 0 && getArg(0));
-    return getArg(0)->getBeginLoc();
+    if (!isTypeDependent()) {
```
Comment (HighCommander4) [inline clang/lib/AST/Expr.cpp:1651]: My rationale for checking `isTypeDependent()` on this line is that I traced the difference between the dependent and non-dependent cases discussed in [this comment](https://github.com/llvm/llvm-project/issues/126720#issuecomment-2652868998) to [this check](https://searchfox.org/llvm/rev/e258bca9505f35e0a22cb213a305eea9b76d11ea/clang/lib/Sema/SemaExpr.cpp#6529) in `Sema::BuildCallExpr()`.

File: clang/lib/AST/Expr.cpp [hunk 2]
```diff
@@ -1648,8 +1648,11 @@ SourceLocation CallExpr::getBeginLoc() const {
...
+      assert(getNumArgs() > 0 && getArg(0));
+      if (getNumArgs() > 0 && getArg(0))
```
Comment (HighCommander4) [inline clang/lib/AST/Expr.cpp:1653]: In addition to fixing the reported test case by adding the `isTypeDependent()` check, I made this branch more defensive in general, by checking the condition `getNumArgs() > 0 && getArg(0)` after asserting it. That way, if there are additional edge cases that would fail this check, they still trip the assertion, but production builds avoid a crash in favour of a much more benign error (a suboptimal begin location).

Comment (zyn0217) [inline clang/lib/AST/Expr.cpp:1653]:
```suggestion
      bool HasFirstArgument = getNumArgs() > 0 && getArg(0);
      assert(HasFirstArgument);
      if (HasFirstArgument)
```

File: clang/lib/AST/Expr.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/AST/Expr.cpp:1651]: Can we move the `isTypeDependent()` check up to the point where we check `isExplicitObjectMemberFunction()`, and add a FIXME explaining why this only applies to non-dependent call expressions?

i.e.
```cpp
// FIXME: Dependent call expressions are not handled because ...
if (!isTypeDependent()) {
  ...
}
```

**Review by zyn0217 — COMMENTED** [review]
Thanks for the patch. While this may not be the most optimal solution, we can likely go with it as-is to put the fire out.

(I think @cor3ntin is not present right now)

File: clang/lib/AST/Expr.cpp (hunk 2 above)
Comment (shafik) [reply clang/lib/AST/Expr.cpp:1653]: I don't think we do this elsewhere and in fact I think we prefer a crash we are violating an invariant and we want a hard fail so we can identify and fix ASAP.

Most folks don't run w/ assertions enabled and we could be hiding a latent bug for a long time.

**Comment by shafik** [comment]
Can we please add more details in the summary about e.g. "This fixes a crash when ... and the fix is ..."

File: clang/lib/AST/Expr.cpp [hunk 3]
```diff
@@ -1645,11 +1645,21 @@ SourceLocation CallExpr::getBeginLoc() const {
...
+  // begin location should come from the first argument.
+  // This does not apply to dependent calls, which are modelled with `o.f`
+  // being the callee.
   if (const auto *Method =
           dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl());
-      Method && Method->isExplicitObjectMemberFunction()) {
-    assert(getNumArgs() > 0 && getArg(0));
-    return getArg(0)->getBeginLoc();
+      Method && Method->isExplicitObjectMemberFunction() &&
+      !isTypeDependent()) {
```
Comment (zyn0217) [inline clang/lib/AST/Expr.cpp:1658]: can we avoid the expensive `getCalleeDecl()` for dependent cases?

```cpp
if (!isTypeDependent()) {
  if (const auto *Method =
          dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl()); Method && Method->isExplicitObjectMemberFunction())
     ...
}
```

File: clang/lib/AST/Expr.cpp (hunk 2 above)
Comment (HighCommander4) [reply clang/lib/AST/Expr.cpp]: I agree with these arguments against checking an asserted condition **in general**.

However, I think in this case it might make sense, for two reasons:
 1. My level of confidence that "((callee is an explicit object member function) and (call is not dependent)) implies (call has a first argument)" is in fact an invariant is not very high.
 2. The impact of hiding a bug here is fairly low (slightly inaccurate source range, likely to only affect tools like clangd which perform hit-testing on the AST) compared to a production crash.

I'm happy to remove the check if you feel that's the right tradeoff in spite of these considerations, but I wanted to call them out.

File: clang/lib/AST/Expr.cpp (hunk 3 above)
Comment (HighCommander4) [reply clang/lib/AST/Expr.cpp]: Done, thanks for the suggestion

**Comment by HighCommander4** [comment]
> While this may not be the most optimal solution, we can likely go with it as-is to put the fire out.

Given [this comment](https://github.com/llvm/llvm-project/pull/126868#discussion_r1953948099) (i.e. that the behaviour with this patch is correct for the dependent case as well), is there anything else not optimal about this solution?

**Comment by HighCommander4** [comment]
> Can we please add more details in the summary about e.g. "This fixes a crash when ... and the fix is ..."

Done.

**Comment by zyn0217** [comment]
> > While this may not be the most optimal solution, we can likely go with it as-is to put the fire out.
> 
> Given [this comment](https://github.com/llvm/llvm-project/pull/126868#discussion_r1953948099) (i.e. that the behaviour with this patch is correct for the dependent case as well), is there anything else not optimal about this solution?

I was considering finding a better AST model, but it's more complex than the approach so this is good enough for now :P

**Review by zyn0217 — APPROVED** [review]
