### PR TITLE
[Clang] Fix wrong call location of `DefaultArgExpr`.

### LINKED ISSUE #119129: [[Clang]] Unexpected source location in method chaining
Image
https://godbolt.org/z/d3WeT6d7W

As you can see, clang gives same source location for all function in method chaining. But GCC and MSVC gives different and actually better results.

After checking AST
```
-FunctionDecl <line:11:1, line:17:1> line:11:5 main 'int ()'
  `-CompoundStmt <col:12, line:17:1>
    `-ExprWithCleanups <line:12:5, line:16:13> 'X' lvalue
      `-CXXMemberCallExpr <line:12:5, line:16:13> 'X' lvalue
        |-MemberExpr <line:12:5, line:16:9> '<bound member function type>' .foo 0xe8a7ac0
        | `-CXXMemberCallExpr <line:12:5, line:15:13> 'X' lvalue
        |   |-MemberExpr <line:12:5, line:15:9> '<bound member function type>' .foo 0xe8a7ac0
        |   | `-CXXMemberCallExpr <line:12:5, line:14:13> 'X' lvalue
        |   |   |-MemberExpr <line:12:5, line:14:9> '<bound member function type>' .foo 0xe8a7ac0
        |   |   | `-CXXMemberCallExpr <line:12:5, line:13:13> 'X' lvalue
        |   |   |   |-MemberExpr <line:12:5, line:13:9> '<bound member function type>' .foo 0xe8a7ac0
        |   |   |   | `-MaterializeTemporaryExpr <line:12:5, col:7> 'X' xvalue
        |   |   |   |   `-CXXFunctionalCastExpr <col:5, col:7> 'X' functional cast to X <NoOp>
        |   |   |   |     `-InitListExpr <col:6, col:7> 'X'
```

I think just using the end location of `CXXMemberCallExpr` rather than begin location can resolve the problem.

### PR DESCRIPTION
**Pull request by 16bit-ykiko**
Fix https://github.com/llvm/llvm-project/issues/119129.

### CODE REVIEW

File: clang/test/SemaCXX/source_location.cpp [hunk 1]
```diff
@@ -1012,3 +1012,21 @@ int h = Var<int>;
...
+static_assert(X{}.
+                foo() ==__LINE__);
+static_assert(X{}.
+
+
+                foo() ==__LINE__);
+#line 10000
+static_assert(X{}.
+                foo() == 10001);
+}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/source_location.cpp:1032]: Add a new line at the end of file

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit

File: clang/test/SemaCXX/source_location.cpp (hunk 1 above)
Comment (16bit-ykiko) [reply clang/test/SemaCXX/source_location.cpp]: Resolve
