### PR TITLE
[AST][RISCV] Preserve RISC-V intrinsic pragma in AST

### LINKED ISSUE #109634: [clang] Can't compile RISC-V vector intrisics with precompiled headers (PCH)
## Summary

Clang supports RISC-V vector intrinsics (`#include <riscv_vector.h>`), but fails to compile them when precompiled headers (PCH) are being used. This affects [clangd](https://github.com/clangd/clangd/issues/2143) since it precompiles the header-portion of source files.

## Testcase

Dependencies on Debian/Ubuntu: clang, gcc-multilib

```c
// test.h
#ifndef TEST_H_
#define TEST_H_

#include <riscv_vector.h>

#endif
```

```c
// test.c
#include "test.h"

vuint64m4_t v_add(vuint64m4_t a, vuint64m4_t b, size_t vl) {
    return __riscv_vadd_vv_u64m4(a, b, vl);
}
```

Compile without PCH:

```shell
$ clang --target=riscv64-linux-gnu -march=rv64gcv -c test.c -o test.o
```

Compile with PCH:

```shell
$ clang --target=riscv64-linux-gnu -march=rv64gcv -x c-header test.h -o test.h.pch
$ clang --target=riscv64-linux-gnu -march=rv64gcv -include-pch test.h.pch -c test.c -o test.o
test.c:4:12: error: call to undeclared function '__riscv_vadd_vv_u64m4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    4 |     return __riscv_vadd_vv_u64m4(a, b, vl);
      |            ^
test.c:4:12: error: returning 'int' from a function with incompatible result type 'vuint64m4_t' (aka '__rvv_uint64m4_t')
    4 |     return __riscv_vadd_vv_u64m4(a, b, vl);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

## Expected Behaviour

PCH doesn't cause a difference in behaviour.

## Actual Behaviour

Functions declared by `#pragma clang riscv intrinsic vector` (from `<riscv_vector.h>`) don't exist when using PCH.

## Versions

Tested with Clang 18.1.8-2 on Arch Linux, Clang 18.1.8 on Android Termux, and Clang 18.0-59 on Ubuntu 24.04

### PR DESCRIPTION
**Pull request by 4vtomat**
RISC-V vector intrinsic is generated dynamically at runtime, thus it's
note preserved in AST yet when using precompile header, neither do
information in SemaRISCV. We need to write these information to ast
record to be able to use precompile header for RISC-V.

Fixes #109634

### CODE REVIEW

File: clang/lib/Serialization/ASTWriter.cpp [hunk 1]
```diff
@@ -5232,6 +5233,15 @@ void ASTWriter::WriteModuleFileExtension(Sema &SemaRef,
   Stream.ExitBlock();
 }
 
+void ASTWriter::WriteRISCVIntrinsicPragmas(Sema &SemaRef) {
+  RecordData Record;
+  Record.push_back(SemaRef.RISCV().DeclareRVVBuiltins);
+  Record.push_back(SemaRef.RISCV().DeclareSiFiveVectorBuiltins);
+  Record.push_back(SemaRef.RISCV().DeclareAndesVectorBuiltins);
+  Record.push_back(Record.size());
```
Comment (topperc) [inline clang/lib/Serialization/ASTWriter.cpp]: Why is the size pushed last? Why not first?

**Review by topperc — APPROVED** [review]
LGTM
