### PR TITLE
[flang][OpenMP] Fix firstprivate not working with lastprivate in DO SIMD

### LINKED ISSUE #168306: [Flang][OpenMP] FIRSTPRIVATE clause specified within DO SIMD construct does not become active
```
Version of flang : 22.0.0(63fe60f830ec00cb44fb7354291a74ddc1a7c513)/AArch64
```

In the attached program (`test011.f90`), `FIRSTPRIVATE clause` and `LASTPRIVATE clause` are specified within `DO SIMD construct`, and the same `variable (a)` is specified in both clauses.
When checking the variable's value, `LASTPRIVATE clause` appears to be active, but `FIRSTPRIVATE clause` seems inactive.
The values for ` main1 : a = ` and ` sub1  : a = ` are expected to output `10`.

The result is correct in the following cases:
- Change `DO SIMD construct` to `DO construct`, or
- Specify only `FIRSTPRIVATE clause` (remove `LASTPRIVATE clause`)

This issue relates to the closed https://github.com/llvm/llvm-project/issues/155195.
The compilation error in the above issue #155195 has been fixed. However, since the current execution result is incorrect, I issue this new issue.

The following are the test program, Flang, Gfortran and ifx compilation/execution results.

test011.f90:
```fortran
subroutine sub
  integer a
  a=10
!$omp do simd lastprivate(a) firstprivate(a)
  do i=1,1
     write(6,*) "sub1  : a = ", a
     a=20
  end do
!$omp end do simd
  write(6,*) "sub2  : a = ", a
end subroutine sub

program main
  integer a
  a=10
!$omp do simd lastprivate(a) firstprivate(a)
  do i=1,1
     write(6,*) "main1 : a = ", a
     a=20
  end do
!$omp end do simd
  write(6,*) "main2 : a = ", a
  call sub
  print *,'pass'
end program main
```

```
$ export OMP_NUM_THREADS=2; flang -fopenmp test011.f90; ./a.out
 main1 : a =  0
 main2 : a =  20
 sub1  : a =  -45698304
 sub2  : a =  20
 pass
$
```

```
$ gfortran -fopenmp test011.f90
test011.f90:4:44:

    4 | !$omp do simd lastprivate(a) firstprivate(a)
      |                                            ^
Error: firstprivate variable ‘a’ is private in outer context
test011.f90:4:44: Error: lastprivate variable ‘a’ is private in outer context
test011.f90:16:44:

   16 | !$omp do simd lastprivate(a) firstprivate(a)
      |                                            ^
Error: firstprivate variable ‘a’ is private in outer context
test011.f90:16:44: Error: lastprivate variable ‘a’ is private in outer context
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp test011.f90; ./a.out
 main1 : a =           10
 main2 : a =           20
 sub1  : a =           10
 sub2  : a =           20
$
```

### PR DESCRIPTION
**Pull request by KrxGu**
This fixes a bug where firstprivate was ignored when the same variable had both firstprivate and lastprivate clauses in a do simd construct.

What was broken:
```
integer :: a
a = 10
!$omp do simd firstprivate(a) lastprivate(a)
do i = 1, 1
   print *, a  ! Should print 10, but printed garbage/0
   a = 20
end do
!$omp end do simd
print *, a  ! Correctly prints 20
```

Inside the loop, [a] wasn't being initialized from the firstprivate clause—it just had whatever uninitialized value was there.

The fix:

In genCompositeDoSimd(), we were using simdItemDSP to handle privatization for the whole loop nest. This only looked at SIMD clauses and missed the firstprivate from the DO part. Changed it to use wsloopItemDSP instead, which handles both DO clauses (firstprivate, lastprivate) correctly.

One line change in OpenMP.cpp

Tests added:

Lowering test to check MLIR generation
Runtime test to verify the actual values are correct
image

Fixes #168306

### CODE REVIEW

File: flang/test/Lower/OpenMP/do-simd-firstprivate-lastprivate.f90 [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+! CHECK-LABEL: func.func @_QPdo_simd_first_last_same_var
+subroutine do_simd_first_last_same_var()
+  integer :: a
+  integer :: i
+  a = 10
+
+  ! CHECK:      omp.wsloop
+  ! CHECK-SAME: private(@{{.*}}firstprivate{{.*}} %{{.*}} -> %[[FIRSTPRIV_A:.*]] : !fir.ref<i32>)
+  ! CHECK-NEXT: omp.simd
+  ! CHECK-SAME: private(@{{.*}} %{{.*}} -> %[[PRIV_A:.*]], @{{.*}} %{{.*}} -> %[[PRIV_I:.*]] : !fir.ref<i32>, !fir.ref<i32>)
```
Comment (tblah) [inline flang/test/Lower/OpenMP/do-simd-firstprivate-lastprivate.f90]: Please could you match the neames of the private variables so that it is easier to keep track of which is used where.

**Review by tblah — COMMENTED** [review]
I'm not sure about your interpretation of the spec. There is no firstprivate clause for the simd construct so the firstprivate cannot apply to the simd. Running flang without your patch it looks like we correctly apply firstprivate and lastprivate to the wsloop but only lastprivate to simd.

This results in LLVM codegen where there are three private variables: the firstprivate copy of a for `omp do` - this is unused and would be removed by the optimizer; the private copy of `a` used in the body of `omp simd`; and the private copy of the loop iteration variable. As you observed, this means that the value of `a` inside the loop is uninitialized memory.

If this is a bug then I think the bug is that there are two completely separate declarations and memory for `a`. This is still visible in your lit test.

**Review by tblah — APPROVED** [review]
Thanks for the update. LG
