### PR TITLE
[FMV] Emit the resolver along with the default version definition.

### LINKED ISSUE #81494: [FMV] incorrect codegen when there is no TU-local caller
https://clang.godbolt.org/z/heoTnxqz5

Compare:
```
__attribute__((target_version("dotprod+lse")))
int foo(void) { return 1; }

__attribute__((target_version("default")))
int foo(void) { return 0; }

#ifdef HAS_CALLER
int caller(void) { return foo(); }
#endif
```

```
--rtlib=compiler-rt -O2 -DHAS_CALLER=1
```
vs
```
--rtlib=compiler-rt -O2
```

While GCC's version has self-consistent and correct behavior, IMO it would be better to always emit the weak ifunc+resolver along with the definition of the `default` version so you can forward-declare the not-attributed version of the function and call these from any other TU.

### PR DESCRIPTION
**Pull request by labrinea**
We would like the resolver to be generated eagerly, even if the
versioned function is not called from the current translation
unit. Fixes #81494. It further allows Multi Versioning to work
even if the default target version attribute is omitted from
function declarations.

### CODE REVIEW

File: clang/test/CodeGen/attr-target-version.c [hunk 1]
```diff
@@ -85,7 +85,21 @@ int hoo(void) {
 }
 
 
+// This should generate one target version but no resolver.
+__attribute__((target_version("default"))) int unused_with_forward_default_decl(void);
+__attribute__((target_version("mops"))) int unused_with_forward_default_decl(void) { return 0; }
 
+// FIXME: If the default declaration follows the non-default definition,
```
Comment (labrinea) [inline clang/test/CodeGen/attr-target-version.c:92]: This bug (if we consider it as such) seems unrelated to this patch, but since I found it it deserves a test at least to monitor what we are currently generating for it.

Comment (jroelofs) [reply clang/test/CodeGen/attr-target-version.c:92]: Ouch. Yeah, I think we should consider that a bug.

**Review by jroelofs — APPROVED** [review]

**Comment by labrinea** [comment]
The key takeaway from my conversation with @DanielKristofKiss was that it is important for Function Multi Versioning to work even when the default target attribute is omitted. It was quite a headache to get this working in clang, but the latest revision supports the desired behavior. It also fixes the previously discovered bug I had mentioned in the test file.

**Comment by jroelofs** [comment]
Can you elaborate on that conversation a bit more? I want to make sure we cover all the corner cases.

**Comment by DanielKristofKiss** [comment]
I'd like to support FMV in existing codebases as lean as possible, so the default version attribute would be optional to write as not all version/toolchain will support it. smallest possible codebase change to introduce multi versioning:

```c
 int foo(void);

+ #ifdef __HAVE_FUNCTION_MULTI_VERSIONING
+ int __attribute__((target_version("feature"))) foo(void);
+ #endif
```

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 2]
```diff
@@ -4120,6 +4127,9 @@ void CodeGenModule::emitMultiVersionFunctions() {
                                    TA->getArchitecture(), Feats);
             } else {
               const auto *TVA = CurFD->getAttr<TargetVersionAttr>();
+              if (TVA->isDefaultVersion() &&
+                  CurFD->doesThisDeclarationHaveABody())
+                EmitResolver = true;
               llvm::SmallVector<StringRef, 8> Feats;
               TVA->getFeatures(Feats);
               Options.emplace_back(cast<llvm::Function>(Func),
```
Comment (jroelofs) [inline clang/lib/CodeGen/CodeGenModule.cpp:4135]: github won't let me put a comment on the line I want to, but should there be a `EmitResolver = true` down in `} else if (FD->isTargetClonesMultiVersion()) {` ?

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 3]
```diff
@@ -4347,6 +4362,19 @@ void CodeGenModule::emitCPUDispatchDefinition(GlobalDecl GD) {
   }
 }
 
+/// Adds a declaration to the list of multi version functions if not present.
+void CodeGenModule::AddDeferredMultiVersionResolverToEmit(GlobalDecl GD) {
+  const auto *FD = cast<FunctionDecl>(GD.getDecl());
+  assert(FD && "Not a FunctionDecl?");
+
+  if (FD->isTargetVersionMultiVersion()) {
+    StringRef NamePrefix = getMangledName(GD).split('.').first;
```
Comment (jroelofs) [inline clang/lib/CodeGen/CodeGenModule.cpp:4371]: ISTM you want `getMangledNameImpl` here instead, with `OmitMultiVersionMangling = true`. Trying to split this on the first `.` seems suspicious, and might not play well with `asm("foo.bar.baz._Mlse")`

File: clang/test/CodeGen/attr-target-version.c [hunk 4]
```diff
@@ -84,9 +84,33 @@ int hoo(void) {
...
+// This should also generate two target versions and the resolver.
+__attribute__((target_version("fp16"))) int unused_with_implicit_default_def(void) { return 0; }
+int unused_with_implicit_default_def(void) { return 1; }
+
+// This should also generate two target versions and the resolver.
+int unused_with_implicit_forward_default_def(void) { return 0; }
+__attribute__((target_version("lse"))) int unused_with_implicit_forward_default_def(void) { return 1; }
+
+// This should generate a normal function.
+__attribute__((target_version("rdm"))) int unused_without_default(void) { return 0; }
```
Comment (jroelofs) [inline clang/test/CodeGen/attr-target-version.c:113]: IIUC this breaks a use case I am _very_ interested in:

header.h:
```
int defined_in_separate_files(void);
```

feature_a.c:
```
#include <header.h>
__attribute__((target_version("featurea")))
int defined_in_separate_files(void) { return 1; }
```

feature_b.c:
```
#include <header.h>
__attribute__((target_version("featureb")))
int defined_in_separate_files(void) { return 2; }
```

default.c:
```
#include <header.h>

__attribute__((target_version("rdm")))
int defined_in_separate_files(void);

__attribute__((target_version("lse")))
int defined_in_separate_files(void);

__attribute__((target_version("default")))
int defined_in_separate_files(void) { return 0; }
```

In my experience, the functions that my users want to multi-version tend to be pretty large and live in separate files, organized per architectural feature that they want to take advantage of.

At the very least it adds a sharp edge: they need to declare the default version in each TU, or put it in a private header shared between them.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 2 above)
Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp:4135]: It is initialized with `!FD->isTargetVersionMultiVersion()` so it is set to true for target clones. However I've just found a bug when we don't have a default definition but we do have a caller in the TU. In that case we should be checking `isUsed()` too. I'll fix this.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 3 above)
Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp:4371]: Initially I was using `FD->getName()` as the key here but this wouldn't work for C++ mangled names. `getMangledName()` internally calls `getMangledNameImpl()` which returns the multi versioned name (this would be "foo.bar.baz._Mlse" in you example). The key needs to be the prefix "foo.bar.baz" so that we don't push every multi version of "foo.bar.baz" in the list `MultiVersionFuncs` to be processed by `emitMultiVersionFunctions()`. This would generate a resolver body with multiple copies of the basic blocks corresponding to each version. Hmm, I am not sure how to handle this example properly, perhaps with `rsplit()`.

File: clang/test/CodeGen/attr-target-version.c (hunk 4 above)
Comment (labrinea) [reply clang/test/CodeGen/attr-target-version.c:113]: I do remember this use case from another review (https://godbolt.org/z/3zaM9MzPb) so I wanted to make sure we support it, which is the case! Now if we would further like to support multi versioning in the absense of default declaration (the header not included) that's a different story. I am not opposing, but will have to check how feasible it is to implement and what do the rest of the stakeholders think about it.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 3 above)
Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp:4371]: I tried experimenting with __asm__ but couldn't construct a sensible example in regards to multi versioning. Can you please show me?

Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp:4371]: As far as I can tell `target_version` and `asm` cannot be combined according to clang's semantic checker, therefore a function declaration which has been renamed via `asm` cannot reach `AddDeferredMultiVersionResolverToEmit()`. In any case I will use `rsplit()` instead.

File: clang/test/CodeGen/attr-target-version.c (hunk 4 above)
Comment (labrinea) [reply clang/test/CodeGen/attr-target-version.c:113]: Anyway, I think this has to do with semantics so it's unrelated to this patch and deserves a separate review if pursued. A quick glance in `clang/lib/Sema/SemaDecl.cpp` suggests that in order to fix it we'd have to remove the early exit in `CheckMultiVersionFirstFunction()`. Let's keep it in mind.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 3 above)
Comment (jroelofs) [reply clang/lib/CodeGen/CodeGenModule.cpp]: `asm`+multiversioning isn't really the point of that argument... sorry, bad example. My point is that the `.` inserted for multi versioning mangling might not be the only one. If you insist on string splitting, it should at least be `rsplit`.

We shouldn't have to rely on string splitting though: `getMangledNameImpl(..., false)` returns the prefix that you need. It is used elsewhere in this multiversioning code to retrieve what the mangled name would be on the function if it did not have the attribute:

https://github.com/llvm/llvm-project/blob/7337db72ed334f8389601f160b762e50c4e61c25/clang/lib/CodeGen/CodeGenModule.cpp#L1857-L1861

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 2 above)
Comment (jroelofs) [reply clang/lib/CodeGen/CodeGenModule.cpp:4135]: oh, ok. cool.

Comment (jroelofs) [reply clang/lib/CodeGen/CodeGenModule.cpp:4135]: I always get `isTargetMultiVersion` confused w/ TargetVersionMultiVersion.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 3 above)
Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp]: Right, I see. I've just thought of another issue with `getMangledNameImpl()`. Even though it would be more reliable to not split strings, we can't use its return value (std::string) as the key to a DenseSet. But let me double check it.

Comment (jroelofs) [reply clang/lib/CodeGen/CodeGenModule.cpp]: Hm. Is there somewhere convenient to stick an `llvm::StringSaver`?

Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp]: Surprisingly it didn't seem necessary. I inserted the std::string to the DenseSet (which still expects a StringRef) and I am now running the Address sanitizer just to be sure :D

Comment (labrinea) [reply clang/lib/CodeGen/CodeGenModule.cpp]: Nopes, it didn't like it!

**Comment by jroelofs** [comment]
The current patch looks mostly good, but I'm still hung up on this:

> I'd like to support FMV in existing codebases as lean as possible, so the default version attribute would be optional to write as not all version/toolchain will support it. smallest possible codebase change to introduce multi versioning:
> 
> ```c
>  int foo(void);
> 
> + #ifdef __HAVE_FUNCTION_MULTI_VERSIONING
> + int __attribute__((target_version("feature"))) foo(void);
> + #endif
> ```

Are you imagining this would multi-version between the un-decorated `int foo(void);` and the `int __attribute__((target_version("feature"))) foo(void);` decorated one? In the current patch, it just gets the non-mangled name. And the fact that we get a not-mangled function that uses `feature` without going through a resolver is concerning to me.

**Comment by labrinea** [comment]
> In the current patch, it just gets the non-mangled name. And the fact that we get a not-mangled function that uses `feature` without going through a resolver is concerning to me.

I am not sure I understand. Are you refering to the StringSet I added which keeps non-mangled names of versioned functions? Those unique non-mangled names will be appended to `MultiVersionFuncs` which are iterated by the outer loop of `CodeGenModule::emitMultiVersionFunctions()`. Then for each of these declarations there is a chain of declarations (mangled function versions), which is iterated by the inner loop (forEachMultiversionedFunctionVersion). In that inner loop we either create (emit) a version or we just get a reference to its declaration. All these mangled versions that are part of the chain and are passed to `EmitMultiVersionResolver()` via `Options`. The reason we are using a Set is to avoid duplicates in the outer loop, which would result in multiple copies of the corresponding basic blocks in the resolver's body. Oh, and btw the default versions always have an implicit target_version attribute by the time they are processed by emitMultiVersionFunctions (added by the sema checker), so they are already mangled. I am not sure I answered. Perhaps we could decipher the concern offline.

**Comment by jroelofs** [comment]
I'm referring to:
```
  // This should generate a normal function.
  int __attribute__((target_version("rdm"))) unused_without_default(void);
```

and:
```
  // CHECK: Function Attrs: noinline nounwind optnone
+ // CHECK-LABEL: define {{[^@]+}}@unused_without_default
+ // CHECK-SAME: () #[[ATTR17:[0-9]+]] {
  // CHECK-NEXT:  entry:
+ // CHECK-NEXT:    ret i32 0
 ```
 
 and am confused why `int __attribute__((target_version("rdm"))) unused_without_default(void)`'s mangling will be `_ unused_without_default` and not `_unused_without_default._Mrdm`.

**Comment by labrinea** [comment]
Ah, I see. That is addressed in #85454 but I have already expressed a concern.

**Comment by labrinea** [comment]
I have raised two related pull requests stacked on this one:
- https://github.com/labrinea/llvm-project/pull/1
- https://github.com/labrinea/llvm-project/pull/2

Is there anything else we would like to address in this patch?

**Review by jroelofs — APPROVED** [review]
All three LGTM.
