### PR TITLE
[clang][bytecode] Fix void*-to-ptr casts originating from new/new[]

### LINKED ISSUE #174131: [Clang][Bytecode] void*-to-ptr casts from new allocations are broken
The following program is well-formed in C++26:
```cpp
static_assert((delete (int*)(void*)new int, true));
static_assert((delete[] (int*)(void*)new int[2], true));
int main() {}
```
However, Clang with `-fexperimental-new-constant-interpreter  -std=c++2c` produces (https://godbolt.org/z/9oebej1f8):
```console
<source>:1:15: error: static assertion expression is not an integral constant expression
    1 | static_assert((delete (int*)(void*)new int, true));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:1:23: note: cast from 'void *' is not allowed in a constant expression because the pointed object type 'int *' is not similar to the target type 'int'
    1 | static_assert((delete (int*)(void*)new int, true));
      |                       ^
<source>:2:15: error: static assertion expression is not an integral constant expression
    2 | static_assert((delete[] (int*)(void*)new int[2], true));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:2:25: note: cast from 'void *' is not allowed in a constant expression because the pointed object type 'int *' is not similar to the target type 'int'
    2 | static_assert((delete[] (int*)(void*)new int[2], true));
      |                         ^
2 errors generated.
Compiler returned: 1
```
The note indicates that Clang falsely interprets the type of the pointed-to object to be `int*`, when it should be `int`, in both cases.

There is no issue without `-fexperimental-new-constant-interpreter`.

### PR DESCRIPTION
**Pull request by keinflue**
In void*-to-ptr casts, the type of the pointed-to object in the source operand needs to be compared to the target pointee type.

If a block was created for a `new`/`new[]`/`std::allocator` expression, then a pointer needs to be stripped from the type of the expression (which points to the single-object allocation or first element of the allocation) to get the former.

`Descriptor::getType` did not do this and `Descriptor::getDataType` returns an array type for array allocations. Therefore this introduces a new function `Descriptor::getDataElemType` with the same behavior as `Descriptor::getDataType`, except that it always produces the element type in the array case and avoids the need for an `ASTContext` reference. Make `Pointer::getType` use this function instead.

Fixes #174131

### CODE REVIEW

File: clang/lib/AST/ByteCode/Pointer.h [hunk 1]
```diff
@@ -354,7 +354,8 @@ class Pointer {
       if (const auto *CT = getFieldDesc()->getType()->getAs<VectorType>())
         return CT->getElementType();
     }
-    return getFieldDesc()->getType();
+
+    return getFieldDesc()->getDataElemType();
```
Comment (keinflue) [inline clang/lib/AST/ByteCode/Pointer.h]: I replaced `->getType()` directly here in `Pointer::getType` instead of only the relevant use site in `PtrPtrCast`, but because `Pointer::getType` has many other users, I am not sure whether this is ok. Tests seem to pass though.

Comment (tbaederr) [reply clang/lib/AST/ByteCode/Pointer.h]: The entire "what QualType does this Pointer point to" story is kinda a mess right now. So this is fine.

File: clang/test/AST/ByteCode/cxx26.cpp [hunk 2]
```diff
@@ -9,6 +9,17 @@ namespace VoidCast {
   constexpr void* p = nullptr;
   constexpr int* q = static_cast<int*>(p);
   static_assert(q == nullptr);
+
+  static_assert((delete (int*)(void*)new int, true));
+  static_assert((delete[] (int*)(void*)new int[2], true));
+
+  // both-error@+2 {{not an integral constant expression}}
+  // both-note@+1 {{cast from 'void *' is not allowed in a constant expression because the pointed object type 'int' is not similar to the target type 'float'}}
+  static_assert((delete (float*)(void*)new int, true));
```
Comment (tbaederr) [inline clang/test/AST/ByteCode/cxx26.cpp]: Move the expected output to the end of the `static_assert` line, like the others in this file.

Comment (keinflue) [reply clang/test/AST/ByteCode/cxx26.cpp]: done

**Review by tbaederr — APPROVED** [review]

**Comment by keinflue** [comment]
@tbaederr Thank you for the approval. I do not have commit access. Can you land the PR for me?

File: clang/lib/AST/ByteCode/Descriptor.cpp [hunk 3]
```diff
@@ -433,6 +433,22 @@ QualType Descriptor::getDataType(const ASTContext &Ctx) const {
   return getType();
 }
 
+QualType Descriptor::getDataElemType() const {
+  if (const auto *E = asExpr()) {
```
Comment (shafik) [inline clang/lib/AST/ByteCode/Descriptor.cpp]: We do this dance in `getDataType()` as well. This code duplication is bad, if anything changes/needs fixing, we need to update this code in both places and likely we will eventually forget and they will diverge. 

This should be refactored so the common code is in one place in some fashion.

Comment (keinflue) [reply clang/lib/AST/ByteCode/Descriptor.cpp]: I could factor out the conditions for the `new`/`allocate` expressions into another function which would then return the element type before it is (possibly) turned into an array type. But that function then also needs to return whether or not the special handling applies (rather than the default path `return getType();`), e.g. by returning an empty `QualType`, maybe?

Alternatively I could add a parameter `bool ElemTypeOnly` to switch between the two variants in a single function. That would look cleaner in the implementation, but has the usual problems of a `bool` parameter affecting the semantics of a function.

Any opinions on these approaches?
