### PR TITLE
ConstantFolding: Do not fold fcmp of denormal without known mode

### LINKED ISSUE #114947: `fcmp` miscompiled to a constant
Alive2 report: https://alive2.llvm.org/ce/z/324E7x

```llvm
----------------------------------------
define i1 @fcmp_double_dynamic_dynamic.2() denormal-fp-math=dynamic,dynamic {
#0:
  %cmp = fcmp une double 0x0008000000000000, -0.000000
  ret i1 %cmp
}
=>
define i1 @fcmp_double_dynamic_dynamic.2() nofree noundef willreturn denormal-fp-math=dynamic,dynamic memory(none) {
#0:
  ret i1 1
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:

Source:
i1 %cmp = #x0 (0)

Target:
Source value: #x0 (0)
Target value: #x1 (1)

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

### PR DESCRIPTION
**Pull request by arsenm**
Fixes #114947

### CODE REVIEW

**Comment by arsenm** [comment]
* **#115407** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115407?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dtcxzyw — APPROVED** [review]
LG

File: llvm/lib/Analysis/ConstantFolding.cpp [hunk 1]
```diff
@@ -1266,14 +1266,16 @@ Constant *llvm::ConstantFoldCompareInstOperands(
...
-  Ops1 = FlushFPConstant(Ops1, I, /* IsOutput */ false);
-  if (!Ops1)
-    return nullptr;
+  if (CmpInst::isFPPredicate(Predicate)) {
+    // Flush any denormal constant float input according to denormal handling
+    // mode.
+    Ops0 = FlushFPConstant(Ops0, I, /* IsOutput=*/false);
+    if (!Ops0)
+      return nullptr;
+    Ops1 = FlushFPConstant(Ops1, I, /* IsOutput= */ false);
```
Comment (nikic) [inline llvm/lib/Analysis/ConstantFolding.cpp:1275]:
```suggestion
    Ops1 = FlushFPConstant(Ops1, I, /* IsOutput=*/false);
```

File: llvm/lib/Analysis/ConstantFolding.cpp [hunk 2]
```diff
@@ -1298,47 +1300,110 @@ Constant *llvm::ConstantFoldBinaryOpOperands(unsigned Opcode, Constant *LHS,
...
+          return nullptr;
+        NewElts.push_back(Folded);
+      }
+    }
+
+    return ConstantVector::get(NewElts);
   }
-  return Operand;
+
+  return nullptr;
```
Comment (nikic) [inline llvm/lib/Analysis/ConstantFolding.cpp:1406]: Side-note: We should probably have a generic method on Constant that does an element wise operation on it, so we don't have to repeat this scalar/splat/vector code everywhere.

File: llvm/test/Transforms/InstSimplify/ConstProp/bitcast.ll [hunk 3]
```diff
@@ -66,15 +66,17 @@ define i1 @fcmp_constexpr_une(float %conv) {
 
 define i1 @fcmp_constexpr_ueq(float %conv) {
 ; CHECK-LABEL: @fcmp_constexpr_ueq(
-; CHECK-NEXT:    ret i1 true
+; CHECK-NEXT:    [[CMP:%.*]] = fcmp ueq float bitcast (i32 ptrtoint (ptr @a to i32) to float), bitcast (i32 ptrtoint (ptr @a to i32) to float)
```
Comment (nikic) [inline llvm/test/Transforms/InstSimplify/ConstProp/bitcast.ll:69]: Shouldn't we still be able to fold this? I think for the purpose of denormal flushing, you probably want to ignore constant expressions rather than bail out for them, so they can still be evaluated symbolically.

File: llvm/lib/Analysis/ConstantFolding.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Analysis/ConstantFolding.cpp:1275]: I thought clang-format took care of these, but it's not here for some reason
