### PR TITLE
[Flang] Give a more specific error message for expressions where an IO Unit is expected

### LINKED ISSUE #125446: [Flang] Incorrect message when concat-op is specified for io-unit
```
Version of flang : 20.0.0(1c4341d176492da5f276937b84a3d0c959e4cf5b)/AArch64
```
The attached program is incorrect.  
When `concat-op` is specified for `io-unit`, a compilation error occurs.  
The message is outputted as `Must have INTEGER`. However, `io-unit` can also specify CHARACTER (`internal-file-variable` = `char-variable`).  
The message is incorrect and should output a message similar to Gfortran.  

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

read.f:
```fortran
      character a,b
      read(b//b,*) a
      end
```

```
$ flang read.f
error: Semantic errors in read.f
./read.f:2:12: error: Must have INTEGER type, but is CHARACTER(1)
        read(b//b,*) a
             ^^^^
$
```

```
$ gfortran read.f
read.f:2:11:

    2 |       read(b//b,*) a
      |           1
Error: UNIT specification at (1) must be an INTEGER expression or a CHARACTER variable
$
```

```
$ ifx read.f
read.f(2): error #6324: This specifier has already been used in this I/O operation.
      read(b//b,*) a
^
read.f(2): error #6330: There is a direction conflict for this I/O operation.
      read(b//b,*) a
^
compilation aborted for read.f (code 1)
$
```

### PR DESCRIPTION
**Pull request by akuhlens**
This PR fixes #125446 by specializing the error message that is generated when an arbitrary expression is used as an IO Unit. See the tests for specific examples, but the general gist is that if you use a non-variable expression as the IO unit argument to a read or write, you now get a more specific error message indicating the the expression could have been a scalar integer expression or character variable.

### CODE REVIEW

**Comment by akuhlens** [comment]
Force pushed to rebase onto main before reviews.

File: flang/lib/Semantics/check-io.cpp [hunk 1]
```diff
@@ -9,7 +9,9 @@
 #include "check-io.h"
 #include "definable.h"
 #include "flang/Common/format.h"
+#include "flang/Common/indirection.h"
```
Comment (jeanPerier) [inline flang/lib/Semantics/check-io.cpp:12]: FYI, The [llvm policy about headers](https://llvm.org/docs/CodingStandards.html#include-as-little-as-possible) says that it is OK to include indirectly and I am fairly sure these two headers are included indirectly already via the tools.h. I am fine with the explicit include (so is the policy), but just know that you do not need to bother adding explicit includes.

**Review by jeanPerier — APPROVED** [review]
This looks great, thanks!

If you have not, please check that there is an unparsing test `flang -fc1 -fdebug-unparse` for READ that verifies that unparsing of IoUnit is still OK with integer expressions.

**Review by eugeneepshteyn — APPROVED** [review]

File: flang/lib/Parser/io-parsers.cpp [hunk 2]
```diff
@@ -23,8 +23,12 @@ namespace Fortran::parser {
 // R905 char-variable -> variable
 // "char-variable" is attempted first since it's not type constrained but
 // syntactically ambiguous with "file-unit-number", which is constrained.
+// Note, "file-unit-number" is replaced by "expr" to allow for better
+// error messages.
 TYPE_PARSER(construct<IoUnit>(variable / lookAhead(space / ",);\n"_ch)) ||
-    construct<IoUnit>(fileUnitNumber) || construct<IoUnit>(star))
+    construct<IoUnit>(
```
Comment (klausler) [inline flang/lib/Parser/io-parsers.cpp:29]: Would not the other uses of `fileUnitNumber` in this file also benefit from this change?  If so, consider modifying the parser for `FileUnitNumber` itself.

Comment (akuhlens) [reply flang/lib/Parser/io-parsers.cpp:29]: When I was looking into it the other uses of fileUnitNumber in this file don't have the same overlap with a character variable that can lead to this issue, and thus I don't think they would benefit from this.
