### PR TITLE
Fix EXTEND_VECTOR_INREG widening when input > result size

### LINKED ISSUE #176966: [AMDGPU] Assertion `N1.getValueType().bitsLE(VT) && "The input must be the same size or smaller than the result."' failed.
Reproducer: https://godbolt.org/z/shje8TWv7
Reduced testcase (original testcase doesn't contain non-power-of-two-sized vector):
```llvm
target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

define <32 x i8> @backsmith_pure_2() {
entry:
  %0 = load <6 x i8>, ptr addrspace(5) null, align 8
  %shuffle5 = shufflevector <6 x i8> %0, <6 x i8> zeroinitializer, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 5, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  ret <32 x i8> %shuffle5
}
```

Dump:
```
clang++: warning: argument unused during compilation: '--gcc-toolchain=/opt/compiler-explorer/gcc-15.2.0' [-Wunused-command-line-argument]
clang++: /root/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:6537: llvm::SDValue llvm::SelectionDAG::getNode(unsigned int, const llvm::SDLoc&, llvm::EVT, llvm::SDValue, llvm::SDNodeFlags): Assertion `N1.getValueType().bitsLE(VT) && "The input must be the same size or smaller than the result."' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-21.1.0/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-15.2.0 -fcolor-diagnostics -fno-crash-diagnostics -x ir --target=amdgcn-amd-amdhsa -mcpu=gfx900 -nogpulib <source>
1.	Code generation
2.	Running pass 'CallGraph Pass Manager' on module '<source>'.
3.	Running pass 'AMDGPU DAG->DAG Pattern Instruction Selection' on function '@backsmith_pure_2'
 #0 0x0000000004019ae8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4019ae8)
 #1 0x0000000004016f14 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4016f14)
 #2 0x0000000003f5b698 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000768698642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007686986969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000768698642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007686986287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000076869862871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000768698639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000000000564c01b llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::EVT, llvm::SDValue, llvm::SDNodeFlags) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x564c01b)
#10 0x000000000576f749 llvm::DAGTypeLegalizer::WidenVecOp_EXTEND_VECTOR_INREG(llvm::SDNode*) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x576f749)
#11 0x000000000577ad14 llvm::DAGTypeLegalizer::WidenVectorOperand(llvm::SDNode*, unsigned int) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x577ad14)
#12 0x000000000571feed llvm::DAGTypeLegalizer::run() (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x571feed)
#13 0x0000000005720b89 llvm::SelectionDAG::LegalizeTypes() (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x5720b89)
#14 0x0000000005691d73 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x5691d73)
#15 0x000000000569595d llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x569595d)
#16 0x0000000005696de5 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x5696de5)
#17 0x000000000153f585 llvm::AMDGPUDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x153f585)
#18 0x00000000056827af llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x56827af)
#19 0x000000000331d873 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#20 0x0000000003944d8f llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x3944d8f)
#21 0x0000000002e448d2 (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) CallGraphSCCPass.cpp:0:0
#22 0x00000000039459b1 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x39459b1)
#23 0x00000000042d2791 clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x42d2791)
#24 0x00000000049d02d0 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x49d02d0)
#25 0x0000000004cc9f95 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4cc9f95)
#26 0x0000000004c4688e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4c4688e)
#27 0x0000000004dbc2e1 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4dbc2e1)
#28 0x0000000000d93cff cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0xd93cff)
#29 0x0000000000d8a8ba ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#30 0x0000000004a36b79 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#31 0x0000000003f5bb34 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x3f5bb34)
#32 0x0000000004a3718f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#33 0x00000000049f915d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x49f915d)
#34 0x00000000049fa1ee clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x49fa1ee)
#35 0x0000000004a02d85 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0x4a02d85)
#36 0x0000000000d9018f clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0xd9018f)
#37 0x0000000000c444d4 main (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0xc444d4)
#38 0x0000768698629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#39 0x0000768698629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#40 0x0000000000d8a365 _start (/opt/compiler-explorer/clang-assertions-21.1.0/bin/clang+++0xd8a365)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by nataliakokoromyti**
This patch fixes an LLVM crash on AMDGPU that occurred when compiling valid code involving non-power-of-two vector sizes. During type legalization, LLVM widened an EXTEND_VECTOR_INREG operation by first widening the input vector, which could make the input larger than the result and trigger an assertion failure. 

The fix changes the logic to widen the result first and then extract the needed portion so there's no invalid size mismatch. I've added a test that previously crashed but now doesn't. 

fixes #176966.

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp [hunk 1]
```diff
@@ -7702,8 +7702,33 @@ SDValue DAGTypeLegalizer::WidenVecOp_EXTRACT_VECTOR_ELT(SDNode *N) {
...
+  // Widen the input as requested by the legalizer.
+  SDValue WideInOp = GetWidenedVector(N->getOperand(0));
+  EVT WideInVT = WideInOp.getValueType();
+
+  // EXTEND_VECTOR_INREG requires input bits <= result bits.
+  // If widening makes the input larger than the original result, widen the
+  // result to match, then extract back down.
+  if (WideInVT.getSizeInBits() > ResVT.getSizeInBits()) {
+    assert(ResVT.isVector() &&
+           "Expected vector result for EXTEND_VECTOR_INREG");
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp]:
```suggestion
```

This is redundant, getVectorElementType will assert anyway (and I assume this is asserted on construction)

File: llvm/test/CodeGen/AMDGPU/extend-vector-inreg-nonpow2.ll [hunk 2]
```diff
@@ -0,0 +1,23 @@
+; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -o /dev/null %s
+;
+; Regression test for https://github.com/llvm/llvm-project/issues/176966
+; Ensures we don't crash in DAG type legalization when widening
+; EXTEND_VECTOR_INREG where the widened input becomes larger than the result.
+
+target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
+target triple = "amdgcn-amd-amdhsa"
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/extend-vector-inreg-nonpow2.ll]:
```suggestion
```

File: llvm/test/CodeGen/AMDGPU/extend-vector-inreg-nonpow2.ll [hunk 3]
```diff
@@ -0,0 +1,23 @@
+; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -o /dev/null %s
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/extend-vector-inreg-nonpow2.ll]: Generate checks and include issue number in file name?

File: llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp [hunk 4]
```diff
@@ -7702,8 +7702,33 @@ SDValue DAGTypeLegalizer::WidenVecOp_EXTRACT_VECTOR_ELT(SDNode *N) {
...
+    unsigned EltBits = ResEltVT.getSizeInBits();
+    assert(EltBits && (WideInVT.getSizeInBits() % EltBits) == 0 &&
+           "Widened input size must be a multiple of result element size");
+
+    unsigned WideNumElts = WideInVT.getSizeInBits() / EltBits;
+    EVT WideResVT = EVT::getVectorVT(*DAG.getContext(), ResEltVT, WideNumElts);
+
+    SDValue WideRes = DAG.getNode(N->getOpcode(), DL, WideResVT, WideInOp);
+    return DAG.getNode(ISD::EXTRACT_SUBVECTOR, DL, ResVT, WideRes,
+                       DAG.getVectorIdxConstant(0, DL));
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp]: return DAG.getExtractSubvector(DL, ResVT, WideRes, 0);

**Review by arsenm — APPROVED** [review]
