### PR TITLE
[clang] fix partial ordering of NTTP packs

### LINKED ISSUE #132562: [clang][rejects-valid] unfound constrained partial specialization of class template with variadic NTTP of class type
The following valid C++20 code is rejected by clang trunk:

```c++
struct Integer
{
  int value{};
};

template <Integer... X>
struct Type;

template <Integer... X>
  requires ((X.value == 0) ||...)
struct Type<X...>
{
};
```

result:

```
<source>:11:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
   11 | struct Type<X...>
      |        ^
<source>:7:8: note: template is declared here
    7 | struct Type;
      |        ^
1 error generated.
```

This bug requires the class type to be parameterized on a variadic pack of non-type template parameters of class type.

repro:
https://godbolt.org/z/fYKe1MEeK

### PR DESCRIPTION
**Pull request by mizvekov**
This fixes partial ordering of pack expansions of NTTPs, by procedding with the check using the pattern of the NTTP through the rules of the non-pack case.

This also unifies almost all of the different versions of FinishTemplateArgumentDeduction (except the function template case). This makes sure they all follow the rules consistently, instantiating the parameters and comparing those with the argument.

Fixes #132562

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -6837,64 +6846,55 @@ ExprResult Sema::CheckTemplateArgument(NonTypeTemplateParmDecl *Param,
...
-  if (ParamType->isDependentType() || Arg->isTypeDependent()) {
-    // Force the argument to the type of the parameter to maintain invariants.
-    auto *PE = dyn_cast<PackExpansionExpr>(Arg);
-    if (PE)
-      Arg = PE->getPattern();
-    ExprResult E = ImpCastExprToType(
-        Arg, ParamType.getNonLValueExprType(Context), CK_Dependent,
-        ParamType->isLValueReferenceType()   ? VK_LValue
-        : ParamType->isRValueReferenceType() ? VK_XValue
-                                             : VK_PRValue);
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:6882]: I ran a debugger and it looked like this is where the issue occurred.

It seemed that `ParamType.getNonLValueExprType(Context)` was dropping the const qualifier from the template argument and thus there would be a mismatch when deducing against the primary template.

This issue seems to have occurred after clang 19 (https://compiler-explorer.com/z/746nc8vdE), but I couldn't pinpoint the regressing commit. So my question is: Did we previously compare the template arguments and parameters in a more relaxed manner (at least in this case), ignoring the constness mismatch and inadvertently accepting the code? And after some work on DeduceTemplateArguments, did it become stricter, causing the issue to surface?

**Review by zyn0217 — APPROVED** [review]
LGTM in general, but please wait for a few days before you commit.

Do we need a backport? This fixes a regression but the patch seems too large.

**Comment by mizvekov** [comment]
We can do a back port once the patch is settled, and it could wait until 20.2.

**Review by erichkeane — APPROVED** [review]
Not sure I get what is going on, but nothing suspicious/no real comments.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 2]
```diff
@@ -7085,18 +7102,24 @@ ExprResult Sema::CheckTemplateArgument(NonTypeTemplateParmDecl *Param,
                                    ? Context.getIntWidth(IntegerType)
                                    : Context.getTypeSize(IntegerType));
 
-      SugaredConverted = TemplateArgument(Context, Value, ParamType);
-      CanonicalConverted =
-          TemplateArgument(Context, Value, Context.getCanonicalType(ParamType));
-      return ArgResult;
+      if (ArgPE) {
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplate.cpp:7105]: So we had a static analysis tool claim that if we get there `ArgPE` will always be `nullptr` based on just manual inspection it was not clear to me this was the case. 

So I decided to change the code based on this assumption and see if anything breaks and nothing broke.

At minimum we are not covering this code in testing which is not ideal. Can you come up with a test case that hits this or maybe show that this indeed dead code?

**Review by shafik — COMMENTED** [review]
@mizvekov

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp:7105]: Right, that's not possible. At some point in the development of this patch, I changed the `StrictCheck` mode to always use the C++17 rules for converted constant expressions, and so the changes to this function from this point forward became unnecessary, but I must have forgotten to go back and remove this.

I posted a patch to clean this up here: https://github.com/llvm/llvm-project/pull/158515
