### PR TITLE
[AArch64] Support symmetric complex deinterleaving with higher factors

### LINKED ISSUE #144795: [LoopVectorizePass] 40% regression on neoverse-v1 after #141865
Performance comes back when reverting 7ef77eb9984d1fb537a409cf4be89560fbb681fe

Before the change:
```
           2124.44 msec task-clock                       #    0.997 CPUs utilized
        5510839431      cycles                           #    2.594 GHz
        6419270661      instructions                     #    1.16  insn per cycle
```

After the change:
```
           3101.06 msec task-clock                       #    0.997 CPUs utilized
        8045294105      cycles                           #    2.594 GHz
        5452469574      instructions                     #    0.68  insn per cycle
```

Attaching LLVM IR dumps before and after the change, and the assembly.

[before.s.gz](https://github.com/user-attachments/files/20804283/before.s.gz)

[before.log.gz](https://github.com/user-attachments/files/20804285/before.log.gz)

[after.s.gz](https://github.com/user-attachments/files/20804286/after.s.gz)

[after.log.gz](https://github.com/user-attachments/files/20804288/after.log.gz)

### PR DESCRIPTION
**Pull request by david-arm**
For loops such as this:

```
struct foo {
  double a, b;
};

void foo(struct foo *dst, struct foo *src, int n) {
  for (int i = 0; i < n; i++) {
    dst[i].a += src[i].a * 3.2;
    dst[i].b += src[i].b * 3.2;
  }
}
```

the complex deinterleaving pass will spot that the deinterleaving
associated with the structured loads cancels out the interleaving
associated with the structured stores. This happens even though
they are not truly "complex" numbers because the pass can handle
symmetric operations too. This is great because it means we can
then perform normal loads and stores instead. However, we can also
do the same for higher interleave factors, e.g. 4:

```
struct foo {
  double a, b, c, d;
};

void foo(struct foo *dst, struct foo *src, int n) {
  for (int i = 0; i < n; i++) {
    dst[i].a += src[i].a * 3.2;
    dst[i].b += src[i].b * 3.2;
    dst[i].c += src[i].c * 3.2;
    dst[i].d += src[i].d * 3.2;
  }
}
```

This PR extends the pass to effectively treat such structures as
a set of complex numbers, i.e.

```
struct foo_alt {
  std::complex<double> x, y;
};
```

with equivalence between members:

```
  foo_alt.x.real == foo.a
  foo_alt.x.imag == foo.b
  foo_alt.y.real == foo.c
  foo_alt.y.imag == foo.d
```

I've written the code to handle sets with arbitrary numbers of
complex values, but since we only support interleave factors
between 2 and 4 I've restricted the sets to 1 or 2 complex
numbers. Also, for now I've restricted support for interleave
factors of 4 to purely symmetric operations only. However, it
could also be extended to handle complex multiplications,
reductions, etc.

Fixes: https://github.com/llvm/llvm-project/issues/144795

### CODE REVIEW

File: llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp [hunk 1]
```diff
@@ -67,6 +67,7 @@
 #include "llvm/CodeGen/TargetLowering.h"
 #include "llvm/CodeGen/TargetSubtargetInfo.h"
 #include "llvm/IR/IRBuilder.h"
+#include "llvm/IR/Intrinsics.h"
```
Comment (igogo-x86) [inline llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp:70]: I think we don't need that

File: llvm/test/CodeGen/AArch64/complex-deinterleaving-symmetric-fixed.ll [hunk 2]
```diff
@@ -0,0 +1,76 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
```
Comment (igogo-x86) [inline llvm/test/CodeGen/AArch64/complex-deinterleaving-symmetric-fixed.ll:1]: I suppose this patch doesn't affect fixed-width? This test shows the same output before and after patch

Comment (david-arm) [reply llvm/test/CodeGen/AArch64/complex-deinterleaving-symmetric-fixed.ll:1]: Yeah so the pass already handles `@simple_symmetric_muladd2`, but I didn't add support for the fixed-width patterns in `@simple_symmetric_muladd4` mainly because I'd expect the VectorCombine pass to have already removed the shuffles before we reach the complex deinterleaving pass. However, if we find cases where actually it would be useful to support fixed-width vectors it should be easy enough to add.

File: llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp [hunk 3]
```diff
@@ -2033,24 +2190,38 @@ ComplexDeinterleavingGraph::identifySplat(Value *R, Value *I) {
     return all_equal(Mask) && Mask[0] == 0;
   };
 
-  if (!IsSplat(R) || !IsSplat(I))
-    return nullptr;
+  // The splats must meet the following requirements:
+  //   1. Must either be all instructions or all values.
+  //   2. Non-constant splats must live in the same block.
+  auto FirstValAsInstruction = dyn_cast<Instruction>(Vals[0].Real);
```
Comment (igogo-x86) [inline llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp:2196]: I feel like it would look nice if we split here into two branches and handle them separately:
```
if (FirstIsInst) {
  // Check that all are instructions and have the same parent
} else {
  // Just check that all Vals are not instructions
}
```

File: llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp [hunk 4]
```diff
@@ -305,10 +351,26 @@ class ComplexDeinterleavingGraph {
...
+#endif
+    return std::make_shared<ComplexDeinterleavingCompositeNode>(Operation,
+                                                                Vals);
+  }
+
   NodePtr submitCompositeNode(NodePtr Node) {
     CompositeNodes.push_back(Node);
-    if (Node->Real)
-      CachedResult[{Node->Real, Node->Imag}] = Node;
+    if (Node->Vals[0].Real) {
```
Comment (igogo-x86) [inline llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp:371]: Braces on a simple single-statement body

File: llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp (hunk 1 above)
Comment (igogo-x86) [reply llvm/lib/CodeGen/ComplexDeinterleavingPass.cpp:70]: Ah, yes, you are right!

**Review by igogo-x86 — APPROVED** [review]
LGTM!
