### PR TITLE
[libc++] Fix unintended ABI break in associative containers with reference comparators

### LINKED ISSUE #118559: [libc++] ABI compat breakage using reference type for std::set key_compare
The following compiled fine with libc++ version 19:
```cpp
#include <set>

struct Cmp {
  __int128 x;
  bool operator()(__int128, __int128) const;
};

struct MySet {
  unsigned char b;
  std::set<__int128, const Cmp &> s;
};

extern char q[sizeof(MySet)];
extern char q[40];
```

It no longer compiles with libc++ trunk (https://godbolt.org/z/cTbEovcer). It seems the size of `MySet` has changed because of a change in `std::set`.
The draft release notes (https://libcxx.llvm.org/ReleaseNotes.html#abi-affecting-changes) mention issues with overaligned empty types, but nothing about reference types.

### PR DESCRIPTION
**Pull request by ldionne**
While reference comparators are a terrible idea and it's not entirely clear whether they are supported, fixing the unintended ABI break is straightforward so we should do it as a first step.

Fixes #118559

### CODE REVIEW

File: libcxx/include/__memory/compressed_pair.h [hunk 1]
```diff
@@ -50,9 +50,18 @@ _LIBCPP_BEGIN_NAMESPACE_STD
...
+// Furthermore, that alignment must be the same as what was used in the old __compressed_pair layout, so we must
+// handle reference types specially since alignof(T&) == alignof(T). See https://github.com/llvm/llvm-project/issues/118559.
 
 #ifndef _LIBCPP_ABI_NO_COMPRESSED_PAIR_PADDING
 
+template <class _Tp>
+struct __compressed_pair_alignment : integral_constant<size_t, _LIBCPP_ALIGNOF(_Tp)> {};
+
+template <class _Tp>
+struct __compressed_pair_alignment<_Tp&> : integral_constant<size_t, _LIBCPP_ALIGNOF(void*)> {};
```
Comment (philnik777) [inline libcxx/include/__memory/compressed_pair.h:63]:
```suggestion
template <class _Tp>
inline const size_t __compressed_pair_alignment = _LIBCPP_ALIGNOF(_Tp);

template <class _Tp>
inline const size_t __compressed_pair_alignment<_Tp&> = _LIBCPP_ALIGNOF(_Tp*);
```

**Review by philnik777 — APPROVED** [review]
I didn't have the time to look at this closely yet, so thanks for taking it on!
