### PR TITLE
[clang][test] Add test for comma operator rejection in preprocessor conditionals

### LINKED ISSUE #132822: Comma expressions rejected in #if for C++23
#if 1 ? 1, 0: 3
#error
#endif

clang -E --std=c++23 --pedantic-errors /tmp/bug.cpp gives:

```
tmp/bug.cpp:1:10: error: comma operator in operand of #if [-Werror,-Wpedantic]
    1 | #if 1 ? 1, 0: 3
      |         ~^ ~
```

1 error generated.

I believe that the comma operator has been permitted in constant expressions in C++ since about C++11.  If true, this should be accepted.

### PR DESCRIPTION
**Pull request by swote-git**
Add test coverage to ensure comma operators remain properly rejected in `#if` directives.

Per CWG 1436, comma is not among the permitted operators in preprocessor conditional expressions. This test prevents regressions and clarifies the intended behavior.

Fixes #132822

### CODE REVIEW

**Comment by swote-git** [comment]
Currently, this only about adding test code.

While adding these tests, I noticed two potential improvements to the current error message `"comma operator in operand of #if"`:

1. The same message appears for `#elif`, `#ifdef`, etc.
2. Per CWG 1436, comma operators are explicitly **not permitted** in preprocessor conditionals. The current message describes **where** the comma is, but doesn't clearly convey **why** it's prohibited.

A clearer message should be more clear.

**Review by Sirraide — COMMENTED** [review]
LGTM, though I wonder if it should be part of the DR tests instead.

CC @Endilll

File: clang/test/Preprocessor/cxx_oper_comma.cpp [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++11
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++14
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++17
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++20
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++23
+
+// Test 1: Top-level comma
+// expected-error@+1 {{expected end of line in preprocessor expression}}
+#if 1, 2
+#endif
```
Comment (DavidSpickett) [inline clang/test/Preprocessor/cxx_oper_comma.cpp:11]: I presume our preprocessor treats `#elif` exactly the same, as `<keyword> <expression>` however I would check at least one of these with `#elif` as well. Just to be sure that's how it works.

Comment (swote-git) [reply clang/test/Preprocessor/cxx_oper_comma.cpp:11]: Missing test case for #elif needs to be corrected. 

Thank you for your thoughtful review!

**Comment by DavidSpickett** [comment]
There are some tests in `clang/test/Preprocessor/expr_invalid_tok.c` right now.

**Comment by swote-git** [comment]
@DavidSpickett Thanks for your help.

I can see similar test in `expr_invalid_tok.c`

```c
// PR2284 - The constant-expr production does not including comma.
// CHECK: [[@LINE+1]]:14: error: expected end of line in preprocessor expression
#if 1 ? 2 : 0, 1
#endif
```

What I wanted to write a little more comprehensively was because of the contents of `expr_comma.c`.

```c
// Comma is not allowed in C89
// RUN: not %clang_cc1 -E %s -std=c89 -pedantic-errors

// Comma is allowed if unevaluated in C99
// RUN: %clang_cc1 -E %s -std=c99 -pedantic-errors 

// PR2279

#if 0? 1,2:3
#endif
```

File: clang/test/Preprocessor/cxx_oper_comma.cpp [hunk 2]
```diff
@@ -0,0 +1,38 @@
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++98
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++11
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++14
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++17
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++20
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++23
+
+// Test 1: Top-level comma
+// expected-error@+1 {{expected end of line in preprocessor expression}}
```
Comment (Endilll) [inline clang/test/Preprocessor/cxx_oper_comma.cpp:9]: Can you open an issue to improve diagnostics here? It would be more actionable to point at the comma than to say that EOL was expected

File: clang/test/Preprocessor/cxx_oper_comma.cpp [hunk 3]
```diff
@@ -0,0 +1,38 @@
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++98
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++11
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++14
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++17
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++20
+// RUN: %clang_cc1 -E -pedantic-errors %s -verify -std=c++23
```
Comment (Endilll) [inline clang/test/Preprocessor/cxx_oper_comma.cpp:6]: `-std=c++2c` is missing

File: clang/test/Preprocessor/cxx_oper_comma.cpp [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+
+// Test 5: Comma in #elif
+#if 0
+#elif (1, 2) // expected-error {{comma operator in operand of #if}}
+#endif
+
+// Test 6: Leading comma (syntax error)
+// expected-error@+1 {{invalid token at start of a preprocessor expression}}
+#if ,
+#endif
```
Comment (Endilll) [inline clang/test/Preprocessor/cxx_oper_comma.cpp:38]: Missing newline at the end

File: clang/test/Preprocessor/cxx_oper_comma.cpp [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+// Test 4: Multiple commas
+// expected-error@+1 {{expected end of line in preprocessor expression}}
+#if 1, 2, 3
+#endif
+
+// Test 5: Comma in #elif
+#if 0
+#elif (1, 2) // expected-error {{comma operator in operand of #if}}
+#endif
+
```
Comment (Endilll) [inline clang/test/Preprocessor/cxx_oper_comma.cpp:34]: `limit` parameter of `#embed` directive is also evaluated as constant-expression https://eel.is/c++draft/cpp#embed.param.limit-2. I think it's worth adding a test case for this, too.

**Review by Endilll — COMMENTED** [review]
Thank you for your work

File: clang/test/Preprocessor/cxx_oper_comma.cpp (hunk 5 above)
Comment (swote-git) [reply clang/test/Preprocessor/cxx_oper_comma.cpp:35]: I added test for #embed case.

 For now, error comes up `expected ')'` , i'm not sure this is right diagnostics.

**Review by Endilll — COMMENTED** [review]
I think this is good to go after you add `#if ,` test suggested earlier

**Comment by swote-git** [comment]
Regarding the #if , test case, I believe I've already added it in the previous version of the patch(test 6). You can find it right here on line[36-39](https://github.com/llvm/llvm-project/pull/155570/files#diff-0339f6a182c253b6ed4d5239b390cc8653cf07187e50e5a3baa9e44b815d3258R37).

Thanks for your support!

**Review by Endilll — APPROVED** [review]
