### PR TITLE
[X86_64] fix empty structure vaarg in c++

### LINKED ISSUE #77036: [x86_64][clang] Empty structure argument are ignored in function variable arguments.
demo
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

extern void *memset (void *__s, int __c, size_t __n);
struct S14 { 
    union{}a; 
};

struct S14 s14;

void check14va (int z, ...) { 
	struct S14 arg, *p; 
	va_list ap; 
    __builtin_va_start(ap, z); 
    arg = __builtin_va_arg(ap, struct S14); 
    double va = __builtin_va_arg(ap, long double);
    printf("%f\n", va);
    if (va != 2.0L) 
        printf("Fail\n"); 
    __builtin_va_end(ap); 
}

int main() {
    memset (&s14, '\0', sizeof(s14));
    check14va(2, s14, 2.0L);
    return 0;
}
```
clang output:
```
0.000000
Fail
```
gcc output:
```
2.000000
```
https://godbolt.org/z/6ErKWPq15

llvm IR
```
define dso_local noundef i32 @main() {
entry:
  %retval = alloca i32, align 4
  %agg.tmp = alloca %struct.S14, align 1
  store i32 0, ptr %retval, align 4
  call void @llvm.memset.p0.i64(ptr align 1 @s14, i8 0, i64 1, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %agg.tmp, ptr align 1 @s14, i64 1, i1 false)
  call void (i32, ...) @check14va(int, ...)(i32 noundef 2, x86_fp80 noundef 0xK40008000000000000000)
  ret i32 0
}
```
I find that clang ignore the empty structure argument `s14`. As a result, the subsequent running result does not meet the expectation.

https://github.com/llvm/llvm-project/blob/597086c60959dd5b3c032552e8b42dd1d053f233/clang/lib/CodeGen/Targets/X86.cpp#L2698-L2701

### PR DESCRIPTION
**Pull request by hstk30-hw**
SizeInBytes of empty structure is 0 in C, while 1 in C++. And empty structure argument of the function is ignored in X86_64 backend.As a result, the value of variable arguments in C++ is incorrect. fix #77036

### CODE REVIEW

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 1]
```diff
@@ -2989,6 +2989,11 @@ static Address EmitX86_64VAArgFromMemory(CodeGenFunction &CGF,
   // an 8 byte boundary.
 
   uint64_t SizeInBytes = (CGF.getContext().getTypeSize(Ty) + 7) / 8;
+
+  if (isEmptyRecord(CGF.getContext(), Ty, true)) {
+    SizeInBytes = 0;
+  }
+
```
Comment (phoebewang) [inline clang/lib/CodeGen/Targets/X86.cpp:2996]: Suggestion:
```
uint64_t SizeInBytes = 0;
if (!isEmptyRecord(CGF.getContext(), Ty, true))
  SizeInBytes = (CGF.getContext().getTypeSize(Ty) + 7) / 8;
```

Comment (CoTinker) [reply clang/lib/CodeGen/Targets/X86.cpp]: done

**Comment by phoebewang** [comment]
I checked it locally, the patch doesn't fix the reported problem:
```
$ clang pr77036.cpp && ./a.out
-nan
Fail
```

**Comment by CoTinker** [comment]
> I checked it locally, the patch doesn't fix the reported problem:
> 
> ```
> $ clang pr77036.cpp && ./a.out
> -nan
> Fail
> ```

isEmptyRecord return false here, I am checking it.

**Comment by CoTinker** [comment]
> I checked it locally, the patch doesn't fix the reported problem:
> 
> ```
> $ clang pr77036.cpp && ./a.out
> -nan
> Fail
> ```

It seems that `struct S14{}` is empty record, but  `struct S14 { union{}a;}` is not.

**Comment by CoTinker** [comment]
I've revised it. Can you check it again? @phoebewang

**Comment by phoebewang** [comment]
> I've revised it. Can you check it again? @phoebewang

I'm not sure the usage of the `isEmptyRecord`. Tagging @asb who modified the interface recently.

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 2]
```diff
@@ -2988,7 +2988,10 @@ static Address EmitX86_64VAArgFromMemory(CodeGenFunction &CGF,
   // AMD64-ABI 3.5.7p5: Step 10. Align l->overflow_arg_area upwards to
   // an 8 byte boundary.
 
-  uint64_t SizeInBytes = (CGF.getContext().getTypeSize(Ty) + 7) / 8;
+  uint64_t SizeInBytes = 0;
+  if (!isEmptyRecord(CGF.getContext(), Ty, true, true))
+    SizeInBytes = (CGF.getContext().getTypeSize(Ty) + 7) / 8;
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/Targets/X86.cpp:2993]: Using isEmptyRecord() like this doesn't seem right.  I mean, it's probably pretty close to being correct in most cases, but I suspect there are edge cases where it does something slightly different.

Also, as far as I can tell, we aren't supposed to realign the va_list if an argument is empty (which could matter for an empty struct with an alignment attribute).

I think we should be using the result of classifyArgumentType() here to check what to do here.  If the ABIArgInfo is "ignore", the argument isn't passed at all, so we shouldn't access the va_list. We should just make a temporary and return its address.

**Comment by CoTinker** [comment]
ping~

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 3]
```diff
@@ -3014,6 +3014,16 @@ Address X86_64ABIInfo::EmitVAArg(CodeGenFunction &CGF, Address VAListAddr,
...
                                        /*isNamedArg*/false);
 
+  // Empty records are ignored for parameter passing purposes.
+  if (AI.isIgnore()) {
+    CharUnits Align = CGF.getContext().getTypeAlignInChars(Ty);
+    VAListAddr = CGF.Builder.CreateStructGEP(VAListAddr, 2);
+    llvm::Value *Load = CGF.Builder.CreateLoad(VAListAddr);
+    llvm::Value *Offset = llvm::ConstantInt::get(CGF.Int32Ty, 0);
+    Load = CGF.Builder.CreateGEP(CGF.Int8Ty, Load, Offset);
+    return Address(Load, CGF.ConvertTypeForMem(Ty), Align);
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/Targets/X86.cpp:3024]: I don't think the address here is guaranteed to be appropriately aligned.  It's probably better to create a temporary like I suggested before.

Also, a GEP with offset 0 does nothing.

Comment (CoTinker) [reply clang/lib/CodeGen/Targets/X86.cpp:3024]: how to create a temporary?

Comment (efriedma-quic) [reply clang/lib/CodeGen/Targets/X86.cpp:3024]: CGF.CreateMemTemp()

**Comment by CoTinker** [comment]
ping~

File: clang/lib/CodeGen/Targets/X86.cpp [hunk 4]
```diff
@@ -3014,6 +3014,11 @@ Address X86_64ABIInfo::EmitVAArg(CodeGenFunction &CGF, Address VAListAddr,
   ABIArgInfo AI = classifyArgumentType(Ty, 0, neededInt, neededSSE,
                                        /*isNamedArg*/false);
 
+  // Empty records are ignored for parameter passing purposes.
+  if (AI.isIgnore()) {
+    return CGF.CreateMemTemp(Ty);
+  }
```
Comment (phoebewang) [inline clang/lib/CodeGen/Targets/X86.cpp:3020]: Does it behave differently between C and C++? Maybe adding a C test for it?

Besides, do not use parentheses for single line code.

**Comment by phoebewang** [comment]
Checked both pr77036.cpp and pr77036.c get the same result, so looks like a right fix. But I want to wait @efriedma-quic to sign off.

File: clang/test/CodeGenCXX/x86_64-vaarg.cpp [hunk 5]
```diff
@@ -0,0 +1,13 @@
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -emit-llvm -o - %s | FileCheck %s
+// RUN: %clang_cc1 -triple x86_64-linux-gnu -emit-llvm -x c -o - %s | FileCheck %s
+
+typedef struct { struct {} a; } empty;
+
+// CHECK-LABEL: define{{.*}} void @{{.*}}empty_record_test{{.*}}()
+empty empty_record_test(void) {
+// CHECK: [[RET:%[a-z]+]] = alloca %struct.empty, align 1
```
Comment (efriedma-quic) [inline clang/test/CodeGenCXX/x86_64-vaarg.cpp:8]: This test doesn't really make it obvious that this is working the way you want; I mean, the existence of TMP sort of hints at it, but it's not comprehensive.

I'd suggest:

- Make the va_list an argument to the function, instead of declaring it as a local.
- Consider autogenerating the CHECK lines using update_cc_test_checks.py

**Review by efriedma-quic — COMMENTED** [review]
Code change looks fine; the regression test needs a few tweaks.

**Review by efriedma-quic — APPROVED** [review]
LGTM
