### PR TITLE
[clang] Fix false positive -Wmissing-field-initializer for anonymous unions

### LINKED ISSUE #70384: [18 regression] false positive `-Wmissing-field-initializer` warning for anonymous union with default member initializer
This code:
```c++
struct A {
    int m;
    union { int n = 0; };
};

A a = A{.m = 0};
```
produces this false-positive warning:
```console
<source>:6:15: warning: missing field 'A::(anonymous union at <source>:3:5)' initializer [-Wmissing-field-initializers]
    6 | A a = A{.m = 0};
      |               ^
```

It looks like this regressed in https://reviews.llvm.org/D157879 / 91088978d712cd7b33610c59f69d87d5a39e3113.

### PR DESCRIPTION
**Pull request by Fznamznon**
Normally warning is not reported when a field has default initializer. Do so for anonymous unions with default initializers as well. No release note since it is a regression in clang 18.

Fixes https://github.com/llvm/llvm-project/issues/70384

### CODE REVIEW

File: clang/test/SemaCXX/cxx2a-initializer-aggregates.cpp [hunk 1]
```diff
@@ -4,7 +4,7 @@
 // RUN: %clang_cc1 -std=c++20 %s -verify=cxx20,expected,reorder -Wno-c99-designator -Werror=reorder-init-list -Wno-initializer-overrides
 // RUN: %clang_cc1 -std=c++20 %s -verify=cxx20,expected,override -Wno-c99-designator -Wno-reorder-init-list -Werror=initializer-overrides
 // RUN: %clang_cc1 -std=c++20 %s -verify=cxx20,expected -Wno-c99-designator -Wno-reorder-init-list -Wno-initializer-overrides
-// RUN: %clang_cc1 -std=c++20 %s -verify=cxx20,expected,wmissing -Wmissing-field-initializers -Wno-c99-designator -Wno-reorder-init-list -Wno-initializer-overrides
+// RUN: %clang_cc1 -std=c++20 %s -verify=cxx20,expected,wmissing -Wmissing-field-initializers -Wno-c99-designator -Wno-reorder-init-list -Wno-initializer-overrides -D NON_PEDANTIC
```
Comment (hnrklssn) [inline clang/test/SemaCXX/cxx2a-initializer-aggregates.cpp:7]: Imo it's clearer to unconditionally compile the same code for each test case, and instead introduce another `-verify` prefix for the diagnostics that aren't emitted by this invocation.

File: clang/lib/Sema/SemaInit.cpp [hunk 2]
```diff
@@ -2537,19 +2555,13 @@ class FieldInitializerValidatorCCC final : public CorrectionCandidateCallback {
 /// actually be initialized.
```
Comment (hnrklssn) [inline clang/lib/Sema/SemaInit.cpp:2555]: The comment above looks like it needs to be updated with `@param`s for `FinishSubobjectInit`, `TopLevelObject` and `InitializedFields`.

Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:2546]: I removed addition of `InitializedFields` parameter, so probably it makes sense to update the comment comment in a separate patch.

**Comment by Fznamznon** [comment]
> I wonder if it would make sense to move the checking for this warning here, to the else case in line 725

Thanks for the suggestion, I gave it a try.

File: clang/lib/Sema/SemaInit.cpp [hunk 3]
```diff
@@ -465,7 +460,8 @@ class InitListChecker {
   void FillInEmptyInitForField(unsigned Init, FieldDecl *Field,
                                const InitializedEntity &ParentEntity,
                                InitListExpr *ILE, bool &RequiresSecondPass,
-                               bool FillWithNoInit = false);
+                               bool FillWithNoInit = false,
+                               bool MaybeEmitMFIWarning = true);
```
Comment (zygoloid) [inline clang/lib/Sema/SemaInit.cpp:464]: This is not an initialism that we can expect future readers of the code to understand. If you want to keep this short, how about something like `WarnIfMissing`?

File: clang/lib/Sema/SemaInit.cpp [hunk 4]
```diff
@@ -727,6 +729,44 @@ void InitListChecker::FillInEmptyInitForField(unsigned Init, FieldDecl *Field,
     if (hadError || VerifyOnly) {
       // Do nothing
     } else if (Init < NumInits) {
```
Comment (zygoloid) [inline clang/lib/Sema/SemaInit.cpp:731]: Is it OK that we don't warn on the `else` case here? Do we still warn for:

```c++
struct A { int x, y; };
A a = {.x = 1}; // missing `.y` initializer
```

File: clang/lib/Sema/SemaInit.cpp [hunk 5]
```diff
@@ -802,9 +842,19 @@ InitListChecker::FillInEmptyInitializations(const InitializedEntity &Entity,
...
       // order to leave them uninitialized, the ILE is expanded and the extra
       // fields are then filled with NoInitExpr.
+
+      // Some checks that required for MFI warning are bound to how many
+      // elements the initializer list originally was provided, perform them
+      // before the list is expanded
+      bool MaybeEmitMFIWarning =
+          !SForm->isIdiomaticZeroInitializer(SemaRef.getLangOpts()) &&
+          ILE->getNumInits() &&
+          !(hasAnyDesignatedInits(SForm) && !SemaRef.getLangOpts().CPlusPlus);
```
Comment (zygoloid) [inline clang/lib/Sema/SemaInit.cpp:857]: Reverse the order of these checks to avoid scanning the whole initializer list here in C++ mode. Please also add a comment here to say we're doing this for GCC compatibility. (Though I question whether we should be! This seems like emulating a GCC warning bug, which we usually don't do.)

File: clang/lib/Sema/SemaInit.cpp [hunk 6]
```diff
@@ -727,6 +729,44 @@ void InitListChecker::FillInEmptyInitForField(unsigned Init, FieldDecl *Field,
...
+            if (!F->isUnnamedBitfield() &&
+                !F->getType()->isIncompleteArrayType() &&
+                !F->isAnonymousStructOrUnion() && !FirstUninitialized)
+              FirstUninitialized = F;
+          }
+
+          if (FirstUninitialized) {
+            SemaRef.Diag(Loc, diag::warn_missing_field_initializers)
+                << FirstUninitialized;
+            return false;
```
Comment (zygoloid) [inline clang/lib/Sema/SemaInit.cpp:758]: I think you should return `FirstUninitialized` here, and produce the warning at the top level if necessary. Right now it looks like this would produce a bogus warning for:

```
struct A {
  union {
    struct { int n; };
    int m = 0;
  };
  int z;
};
A a = {.z = 1};
```
... because you'd visit the anonymous union, then recurse to the anonymous struct, then warn about `n`, then return to the anonymous union and find it's actually initialized.

File: clang/lib/Sema/SemaInit.cpp (hunk 4 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:736]: Yes, we still warn for this case.

File: clang/lib/Sema/SemaInit.cpp (hunk 3 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp]: Okay, I changed the name.

File: clang/lib/Sema/SemaInit.cpp (hunk 5 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp]: Reversed the order.
It seems clang emulates this GCC behavior for 10+ years and changing that can be a disruptive change, I wanted to avoid that.
I added a FIXME highlighting the problem though.

File: clang/lib/Sema/SemaInit.cpp (hunk 6 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp]: Thanks for the catch, fixed and added a test case.

File: clang/test/SemaCXX/cxx2a-initializer-aggregates.cpp (hunk 1 above)
Comment (Fznamznon) [reply clang/test/SemaCXX/cxx2a-initializer-aggregates.cpp]: Ok, done.

File: clang/lib/Sema/SemaInit.cpp (hunk 4 above)
Comment (zygoloid) [reply clang/lib/Sema/SemaInit.cpp:736]: Hmm, how does that work? If this `if` condition doesn't hold and we created an `ImplicitValueInitExpr`, we wouldn't produce the warning.

Ah, I see what's happening: the `if` condition on line 736 is always true, because since cb77930d6b20e53c735233eecf4572a1c30eb0c0 we always resize the init list for a struct to be large enough for all fields, and our optimization to leave off trailing struct members was (accidentally, I think) removed. And we can see the optimization [stops working between Clang 3.6 and Clang 3.7](https://godbolt.org/z/fecM1K7Ec).

Given that we've been living without that optimization for 8 years and no-one seems to have noticed, I suppose that it's fine that we've lost it, but it looks like this function can be simplified a bit as a result. Half of the `if` condition on line 674 is always false, and this `if` condition is always true. Maybe consider changing the L674 condition to an `assert(Init < NumInits)` and simplify this too?

File: clang/lib/Sema/SemaInit.cpp [hunk 7]
```diff
@@ -727,6 +734,38 @@ void InitListChecker::FillInEmptyInitForField(unsigned Init, FieldDecl *Field,
...
+            if (F->isAnonymousStructOrUnion())
+              Uninitialized = CheckAnonMember(F, CheckAnonMember);
+            else if (!F->isUnnamedBitfield() &&
+                     !F->getType()->isIncompleteArrayType() && !Uninitialized &&
+                     !F->hasInClassInitializer())
+              Uninitialized = F;
+
+            if (RD->isUnion() && (F->hasInClassInitializer() || !Uninitialized))
+              return nullptr;
+          }
```
Comment (zygoloid) [inline clang/lib/Sema/SemaInit.cpp:753]: I think this will not warn on
```c++
struct A {
  int a;
  struct {
    int x;
    struct { int y = 0; };
  };
};
A a = A{.a = 0};
```
... because the `Uninitialized` value for `x` will get overwritten by the `nullptr` returned from the struct containing `y`. How about:

```suggestion
          for (auto *F : RD->fields()) {
            FieldDecl *UninitializedFieldInF;
            if (F->isAnonymousStructOrUnion())
              UninitializedFieldInF = CheckAnonMember(F, CheckAnonMember);
            else if (!F->isUnnamedBitfield() &&
                     !F->getType()->isIncompleteArrayType() &&
                     !F->hasInClassInitializer())
              UninitializedFieldInF = F;

            if (RD->isUnion() && !UninitializedFieldInF)
              return nullptr;
            if (!Uninitialized)
              Uninitialized = UninitializedFieldInF;
          }
```

File: clang/lib/Sema/SemaInit.cpp [hunk 8]
```diff
@@ -654,11 +655,17 @@ void InitListChecker::FillInEmptyInitForBase(
...
-void InitListChecker::FillInEmptyInitForField(unsigned Init, FieldDecl *Field,
-                                        const InitializedEntity &ParentEntity,
-                                              InitListExpr *ILE,
-                                              bool &RequiresSecondPass,
-                                              bool FillWithNoInit) {
+static bool hasAnyDesignatedInits(const InitListExpr *IL) {
+  for (const Stmt *Init : *IL)
+    if (isa_and_nonnull<DesignatedInitExpr>(Init))
+      return true;
+  return false;
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaInit.cpp:662]: Can you use llvm::any_of ?

File: clang/lib/Sema/SemaInit.cpp (hunk 7 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp]: Ok, done. Thanks for the catch!

File: clang/lib/Sema/SemaInit.cpp (hunk 8 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp]: Ok, done.

File: clang/lib/Sema/SemaInit.cpp (hunk 4 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:735]: > Maybe consider changing the L674 condition to an assert(Init < NumInits) and simplify this too?

I'm not sure I understand the suggestion. The condition on L674 looks like:
```
if (Init >= NumInits || !ILE->getInit(Init)) {
```
Even if I only remove `Init >= NumInits`, build of check-clang starts asserting with
```
Assertion `Init < getNumInits() && "Initializer access out of range!"'
```

Removing `!ILE->getInit(Init)` also doesn't seem logical to me since `FillInEmptyInitForField` is called for all fields in a record.

**Comment by Fznamznon** [comment]
Ping.

File: clang/lib/Sema/SemaInit.cpp (hunk 4 above)
Comment (zygoloid) [reply clang/lib/Sema/SemaInit.cpp:735]: Hm, right, we still call this with `Init >= NumInits` when in `VerifyOnly` mode (but *only* in that mode).

My concern here is that we're only warning in the `Init < NumInits` case, which is in principle wrong -- we should warn regardless of whether `Init < NumInits`. But in fact, the caller always resizes the `InitListExpr` so that `Init >= NumInits` whenever we're not in `VerifyOnly` mode, so I think this is probably not *actually* wrong, but it still *looks* wrong.

To make it not look wrong, I think we should remove all the dead code here: instead of checking whether `Init < NumInits` in non-`VerifyOnly` mode, we should assert that `Init < NumInits`, and delete the unreachable code that is trying to handle the impossible case: lines 684-685, 704-707, 772-778. Does that make sense?

Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:735]: It seems `Init < NumInits` is always true for non-`VerifyOnly` mode only for structs. So, removing lines `684-685, 704-707, 772-778` breaks a number of tests with unions. The assertion on line 676 confirms:
```
if (Init >= NumInits || !ILE->getInit(Init)) {
  if (const RecordType *RType = ILE->getType()->getAs<RecordType>())
    if (!RType->getDecl()->isUnion())
      assert((Init < NumInits || VerifyOnly) &&
             "This ILE should have been expanded");
```
I can still put warning emission out of `Init < NumInits` check though if that seems more correct.

**Comment by Fznamznon** [comment]
Ping.

**Comment by Fznamznon** [comment]
Ping.

**Review by AaronBallman — COMMENTED** [review]
I think the changes here look reasonable. CC @zygoloid to make sure he agrees as there's still one potentially outstanding comment (if we don't hear back from Richard, I think we can address his concerns post-commit as it seems like a refactoring rather than a behavioral fix).

**Review by AaronBallman — APPROVED** [review]
LGTM, but please wait until sometime mid-next week to land in case Richard has concerns.

**Comment by mikaelholmen** [comment]
Hi @Fznamznon and others!

It looks like this patch not only avoids a false positive, but it also causes warnigns on stuff it didn't warn on before.
So if I add the following to clang/test/Sema/missing-field-initializers.c
```
struct S1 {
  long int l;
  struct  { int a, b; } d1;
};

struct S1 s01 = { 1, {1} }; // expected-warning {{missing field 'b' initializer}}
struct S1 s02 = { .d1.a = 1 };

union U1 {
  long int l;
  struct  { int a, b; } d1;
};

union U1 u01 = { 1 };
union U1 u02 = { .d1.a = 1 };
```
Without the patch it's silent, but with the patch I get
```
  File /repo/uabelho/main-github/clang/test/Sema/missing-field-initializers.c Line 11: missing field 'b' initializer
  File /repo/uabelho/main-github/clang/test/Sema/missing-field-initializers.c Line 19: missing field 'b' initializer
```
so it warns on
```
struct S1 s02 = { .d1.a = 1 };
```
and
```
union U1 u02 = { .d1.a = 1 };
```
I suppose this is not as expected?

We see thousands of warnings like this with our downstream compiler.

**Comment by Fznamznon** [comment]
@mikaelholmen , thanks for the report. These warnings are kind of expected, there is no big difference between `struct S1 s01 = { 1, {1} };` and `struct S1 s02 = { .d1.a = 1 };` in both cases field `b` of `d1` is not initialized. But they are not expected for C, since we aim to silence missing field initializer warning for designated initializers in C, just to match gcc behavior. It seems the patch broke this "silencing" for nested designators, I'll try to provide the fix shortly. If I'm not able, I'll revert.

**Comment by mikaelholmen** [comment]
> I'll try to provide the fix shortly. If I'm not able, I'll revert.

Sounds good. Thank you!

**Comment by mikaelholmen** [comment]
Hi again @Fznamznon 
the following also started causing warnings after this patch (also with the fix)
```
struct S3 {
  long int l;
  struct  { int a, b; } d1[2];
};

struct S3 s32 = { .d1[0].a = 1 };
```
We get
```
foo.c:6:30: warning: missing field 'b' initializer [-Wmissing-field-initializers]
    6 | struct S3 s32 = { .d1[0].a = 1 };
      |                              ^
1 warning generated.
```
with this patch.

**Comment by Fznamznon** [comment]
@mikaelholmen , I see. I'll revert both patches to unblock you and I'll think about the proper solution after the holidays.
Perhaps there should be wider discussion whether we should emulate GCC behavior regarding silencing of these warnings.
IMO, the warnings you're seeing are correct, there is no initializer for field `b`. It is emulating of possible gcc bug that this patch breaks.

**Comment by mikaelholmen** [comment]
@Fznamznon : Thank you!
I wider discussion about how clang should behave sounds good.
