### PR TITLE
[clang] Reapply Handle templated operators with reversed arguments

### LINKED ISSUE #53954: C++20 operator== ambiguous with derived-to-base conversion
```cpp
struct P {
#if 1
    template<class S>
    bool operator==(const S &) const;
#else
    template<class S>
    friend bool operator==(const P &, const S &);
#endif
};

struct A : public P {};
struct B : public P {};

bool check(A a, B b) {
    return a == b;
}
```

The `friend` function works just fine, but the member function dies with
```
<source>:15:14: error: use of overloaded operator '==' is ambiguous (with operand types 'A' and 'B')
    return a == b;
           ~ ^  ~
<source>:4:10: note: candidate function [with S = B]
    bool operator==(const S &) const;
         ^
<source>:4:10: note: candidate function (with reversed parameter order) [with S = A]
```

GCC and MSVC accept both. https://godbolt.org/z/9hj9554fn

@dwblaikie @zygoloid

### PR DESCRIPTION
**Pull request by usx95**
Re-applies https://github.com/llvm/llvm-project/pull/69595 with extra [diff](https://github.com/llvm/llvm-project/pull/72213/commits/79181efd0d7aef1b8396d44cdf40c0dfa4054984)
### New changes

Further relax ambiguities with a warning for member operators of a template class (primary templates of such ops do not match). Eg:
```cpp
template <class T>
struct S {
    template <typename OtherT>
    bool operator==(const OtherT &rhs); 
};
struct A : S<int> {};
struct B : S<bool> {};
bool x = A{} == B{}; // accepted with a warning.
```

This is important for making llvm build using previous clang versions in C++20 mode (eg: this makes the commit e558be51bab051d1471d92e967f8a2aecc13567a keep working with a warning instead of an error).

### Description from https://github.com/llvm/llvm-project/pull/69595

https://github.com/llvm/llvm-project/pull/68999 correctly computed conversion sequence for reversed args to a template operator. This was a breaking change as code, previously accepted in C++17, starts to break in C++20.

Example:
```cpp
struct P {};
template<class S> bool operator==(const P&, const S &);

struct A : public P {};
struct B : public P {};
bool check(A a, B b) { return a == b; }  // This is now ambiguous in C++20.
```

In order to minimise widespread breakages, as a clang extension, we had
previously accepted such ambiguities with a warning
(`-Wambiguous-reversed-operator`) for non-template operators. Due to the
same reasons, we extend this relaxation for template operators.

Fixes https://github.com/llvm/llvm-project/issues/53954

### CODE REVIEW

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -10088,9 +10088,13 @@ static bool allowAmbiguity(ASTContext &Context, const FunctionDecl *F1,
                            const FunctionDecl *F2) {
   if (declaresSameEntity(F1, F2))
     return true;
-  if (F1->isTemplateInstantiation() && F2->isTemplateInstantiation() &&
-      declaresSameEntity(F1->getPrimaryTemplate(), F2->getPrimaryTemplate())) {
-    return true;
+  if (F1->isTemplateInstantiation() && F2->isTemplateInstantiation()) {
+    auto PT1 = F1->getPrimaryTemplate();
+    auto PT2 = F2->getPrimaryTemplate();
+    if (declaresSameEntity(PT1, PT2) ||
```
Comment (ilya-biryukov) [inline clang/lib/Sema/SemaOverload.cpp:10094]: Could we remove the check `getPrimaryTemplate` and instead only look at `getInstantiatedFromMemberTemplate`?

If `getPrimaryTemplate` matches, the `getInstantiatedFromMemberTemplate` will always match as well, right?

Comment (ilya-biryukov) [reply clang/lib/Sema/SemaOverload.cpp:10094]: Also, I believe the crashes [here](https://buildkite.com/llvm-project/clang-ci/builds/6710#018bcc9e-fdcb-44f8-802e-f5e98303916c) are related: `getCommonPtr()` that you see in the stack trace is called  by `getInstantiatedFromMemberTemplate()`.

**Comment by usx95** [comment]
I ran this change internally and noticed a crash for 
```cpp
template <typename T>
class Foo {
 public:
  template <typename U = T>
  bool operator==(const Foo& other) const;
};

bool x = Foo<int>{} == Foo<int>{};
```
<details>
<summary>stacktrace</summary>

```
F0000 00:00:1700029943.315247    8971 logging.cc:57] assert.h assertion failed at third_party/llvm/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:443 in T &llvm::MutableArrayRef<clang::ImplicitConversionSequence>::operator[](size_t) const [T = clang::ImplicitConversionSequence]: Index < this->size() && "Invalid index!"
*** Check failure stack trace: ***
    @     0x55598a5f6a44  absl::log_internal::LogMessage::SendToLog()
    @     0x55598a5f68a2  absl::log_internal::LogMessage::Flush()
    @     0x55598a5f6da9  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x55598a5e70c4  __assert_fail
    @     0x555986a73209  clang::Sema::CheckNonDependentConversions()
    @     0x555986a9db52  llvm::function_ref<>::callback_fn<>()
    @     0x555986c6bc08  llvm::function_ref<>::callback_fn<>()
    @     0x555986bf70b3  clang::Sema::FinishTemplateArgumentDeduction()
    @     0x555986c6bb56  llvm::function_ref<>::callback_fn<>()
    @     0x5559862dbc2f  clang::Sema::runWithSufficientStackSpace()
    @     0x555986bf8f8d  clang::Sema::DeduceTemplateArguments()
    @     0x555986a7229a  clang::Sema::AddMethodTemplateCandidate()
    @     0x555986a72c6f  clang::Sema::AddMethodCandidate()
    @     0x555986a751dd  clang::Sema::AddMemberOperatorCandidates()
    @     0x555986a881f6  clang::Sema::LookupOverloadedBinOp()
    @     0x555986a88673  clang::Sema::CreateOverloadedBinOp()
    @     0x5559866ff91a  BuildOverloadedBinOp()
    @     0x5559866c643e  clang::Sema::ActOnBinOp()
    @     0x555986050faf  clang::Parser::ParseRHSOfBinaryExpression()
    @     0x55598604fcac  clang::Parser::ParseAssignmentExpression()
    @     0x555
```
</details>

**Comment by shafik** [comment]
So currently implementations differ here: https://godbolt.org/z/11331KW6e

This feels related to [cwg2804](https://wg21.link/cwg2804) which is not live yet but can be found [here](https://cplusplus.github.io/CWG/issues/2804.html). I can find the discussion on this from Kona but we ended up sending this to EWG b/c it was not clear what the right fixes for all the related issues are and we wanted design feedback.

CC @zygoloid @AaronBallman

**Comment by usx95** [comment]
This PR is not related to [cwg2804](https://wg21.link/cwg2804). We are already aware of the mentioned issue and are tracking it in https://github.com/llvm/llvm-project/issues/70210.

This PR is different and it fixes an implementation bug in rewriting template non-member operators (the conversion seq was computed incorrectly and associated to incorrect index). The difference in compilers ([godbolt](https://godbolt.org/z/11331KW6e)) you currently see is because of this bug and clang would also correctly consider the example as ambiguous.

**Comment by usx95** [comment]
I wanted to note down the challenges of landing this and the strategy to move forward.

#### Challenges
* Landing this would make old code ambiguous ([example](https://godbolt.org/z/11331KW6e)). This is not unexpected, and it is ambiguous in C++20.
* This would break LLVM in C++20 ([breakage](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/STLExtras.h#L1293-L1303)). We do not want to break LLVM at head.
* But it would not be possible to resolve ambiguity also for **template friend functions** because of [cwg2804](https://cplusplus.github.io/CWG/issues/2804.html).
* In order to resolve this ambiguity, one solution is to make the operator non-friend and add a matching `operator!=` ([P2468R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html)). This is done in https://github.com/llvm/llvm-project/pull/72348. The solution would look like:
  ```cpp
  namespace N{
  struct P {};
  template<class S> bool operator==(const P&, const S &);
  template<class S> bool operator!=(const P&, const S &);
  struct A : public P {};
  struct B : public P {};
  }
  bool x = N::A{} == N::B{};
  ```
* The catch is that clang only recently fixed its  ([P2468R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html)) implementation for `operators==` found through ADL in https://github.com/llvm/llvm-project/commit/9330261143ccbe947ef0687fd20747ba47f26879.
* Without the above fix, LLVM would still be broken in clang-17 (because clang-17 doesn't have https://github.com/llvm/llvm-project/commit/9330261143ccbe947ef0687fd20747ba47f26879).

#### Strategy
1. Wait for cherrypicking https://github.com/llvm/llvm-project-release-prs/pull/778 into clang-17.0.6.
2. Land https://github.com/llvm/llvm-project/pull/72348 to unbreak LLVM.
3. Update the latest revision to build LLVM in C++20 to **17.0.6**.
4. Land this PR https://github.com/llvm/llvm-project/pull/72213 
5. Implement [cwg2804](https://cplusplus.github.io/CWG/issues/2804.html) proposal when finalised.
6. **clang-18** would have correct behaviour for template operators, i.e., correct ambiguities surfaced with the option of resolving through adding matching `operator!=`.

**Comment by usx95** [comment]
All the blockers to land this have been addressed. Since this is not approved, does it look fine to land @ilya-biryukov ?

File: clang/test/CXX/over/over.match/over.match.funcs/over.match.oper/p3-2a.cpp [hunk 2]
```diff
@@ -324,6 +324,113 @@ bool x = X() == X(); // expected-warning {{ambiguous}}
...
+    return true;
+  }
+};
+struct A : public P<int> {};
+struct B : public P<bool> {};
+bool check(A a, B b) { return a == b; } // expected-warning {{ambiguous}}
+}
+
+namespace friend_template_fixme {
+// FIXME(GH70210): This should not rewrite operator== and definitely not a hard error.
```
Comment (ilya-biryukov) [inline clang/test/CXX/over/over.match/over.match.funcs/over.match.oper/p3-2a.cpp:364]: I just wanted to point out that this bug is worrying as it might break some code that's not easy to rewrite.
We worked around the problem in LLVM with 77f2ccbaac5e05e14827247ea8f6cc0f9d214390, but you could already see how the rewrite is complicated.

I don't think we should block on that, especially given that the issue you mention requires further progress from EWG and CWG. But I would keep a close eye for people complaining about this change.

**Review by ilya-biryukov — APPROVED** [review]
I only have minor requests to add a new test and update the release note a bit.
Otherwise LGMT

File: clang/lib/Sema/SemaOverload.cpp (hunk 1 above)
Comment (usx95) [reply clang/lib/Sema/SemaOverload.cpp:10143]: Added test
