### PR TITLE
[InstCombine] Fix FMF propagation in `copysign Mag, (copysign ?, X) -> copysign Mag, X`

### LINKED ISSUE #121432: [InstCombine] FMF flags should not be propagated
Alive2: https://alive2.llvm.org/ce/z/ajCxTh
```
define float @src1(float noundef %x, float noundef %y, float noundef %z) {
  %s = call float @llvm.copysign.f32(float %y, float %z)
  %r = call nnan float @llvm.copysign.f32(float %x, float %s)
  ret float %r
}

define float @tgt1(float noundef %x, float noundef %y, float noundef %z) {
  %r = call nnan float @llvm.copysign.f32(float %x, float %z)
  ret float %r
}

define float @src2(float noundef %x, float noundef %y, float noundef %z) {
  %s = call float @llvm.copysign.f32(float %y, float %z)
  %r = call ninf float @llvm.copysign.f32(float %x, float %s)
  ret float %r
}

define float @tgt2(float noundef %x, float noundef %y, float noundef %z) {
  %r = call ninf float @llvm.copysign.f32(float %x, float %z)
  ret float %r
}

define float @src3(float noundef %x, float noundef %y, float noundef %z) {
  %s = call float @llvm.copysign.f32(float %y, float %z)
  %r = call nsz float @llvm.copysign.f32(float %x, float %s)
  ret float %r
}

define float @tgt3(float noundef %x, float noundef %y, float noundef %z) {
  %r = call nsz float @llvm.copysign.f32(float %x, float %z)
  ret float %r
}
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Closes https://github.com/llvm/llvm-project/issues/121432.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Can we create a new call here instead of modifying the operand? Otherwise there would still be a potential problem with nofpclass on the argument.

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 1]
```diff
@@ -2645,8 +2645,12 @@ Instruction *InstCombinerImpl::visitCallInst(CallInst &CI) {
     // copysign Mag, (copysign ?, X) --> copysign Mag, X
     Value *X;
     if (match(Sign, m_Intrinsic<Intrinsic::copysign>(m_Value(), m_Value(X)))) {
-      II->andIRFlags(Sign);
-      return replaceOperand(*II, 1, X);
+      IRBuilder<>::FastMathFlagGuard FMFGuard(Builder);
+      Builder.setFastMathFlags(II->getFastMathFlags() &
+                               cast<Instruction>(Sign)->getFastMathFlags());
+      Value *CopySign =
+          Builder.CreateBinaryIntrinsic(Intrinsic::copysign, Mag, X);
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp:2652]: We really ought to add FMF arguments to all these CreateFunctions, the guard + set is so clumsy

File: llvm/test/Transforms/InstCombine/copysign.ll [hunk 2]
```diff
@@ -82,14 +82,24 @@ define float @not_known_positive_sign_arg(float %x, float %y) {
...
+define float @copysign_sign_arg_nnan(float %x, float %y, float %z) {
+; CHECK-LABEL: @copysign_sign_arg_nnan(
+; CHECK-NEXT:    [[R:%.*]] = call nnan float @llvm.copysign.f32(float [[X:%.*]], float [[Z:%.*]])
+; CHECK-NEXT:    ret float [[R]]
+;
+  %s = call nnan float @llvm.copysign.f32(float %y, float %z)
+  %r = call nnan float @llvm.copysign.f32(float %x, float %s)
+  ret float %r
+}
+
```
Comment (arsenm) [inline llvm/test/Transforms/InstCombine/copysign.ll:102]: nsz is probably fine as an or but that's maybe overcomplicating it

Comment (arsenm) [inline llvm/test/Transforms/InstCombine/copysign.ll:102]: Test a more complex intersection?

Comment (dtcxzyw) [reply llvm/test/Transforms/InstCombine/copysign.ll:102]: No. https://alive2.llvm.org/ce/z/7spfKH

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp (hunk 1 above)
Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp]: I am working on a prototype.

**Review by arsenm — APPROVED** [review]

**Review by nikic — APPROVED** [review]
LGTM
