### PR TITLE
[flang-rt] Fix system_clock scaling on MacOS

### LINKED ISSUE #176505: [flang] system_clock inflates time differences on macOS
I wrote the program below to demonstrate that Flang's `system_clock` implementation appears to inflate time differences by approximately a factor of 1000.  The other tested compilers listed in the `#else` line all yield the same, expected result in terms of the order of magnitude of time differences.  Clause 16.9.202, lines 31-33 of the [Fortran 2023 Interpretation Document] states that `COUNT_RATE` "is assigned a processor-dependent approximation to the number of processor clock counts per second, or zero if there is no clock for the invoking image," which suggests that, although the approximation is processor-dependent, one would expect the order of magnitude to be the same for a reasonably good approximation with each compiler.

A different set of test programs described [here] indicate that the problem does *not* appear in tests on Linux.  

```
program timer
  use iso_fortran_env, only : int64, real64
  implicit none
  integer(int64) start_time, end_time, clock_rate, i
  integer, parameter :: N = 12
  real(real64) A(N,N), B(N,N), C(N,N)
   
  call system_clock(start_time, clock_rate)

#if defined(__LFORTRAN__)
  call random_init(.true., .true.)
#else
  call random_init(repeatable=.true., image_distinct=.true.)
#endif
  call random_number(A)
  call random_number(B)
  call random_number(C)

#if defined(__LFORTRAN__)
  do i = 1, 2400000
#else
  do i = 1, 24000000
#endif
    A = matmul(B,C)
  end do

  print *, "maxval(A) = ", maxval(A)

  call system_clock(end_time, clock_rate)

#if defined(__flang__) 
    print '(*(a,:,f0.3))', "Elapsed system time (flang): ", (end_time - start_time)/(1000*real(clock_rate, real64)), " sec."
#elif defined(__INTEL_COMPILER) || defined(__LFORTRAN__) || defined(__GFORTRAN__) || defined(_CRAYFTN) || defined(NAGFOR)
    print '(*(a,:,f0.3))', "Elapsed system time: ", (end_time - start_time)/(real(clock_rate, real64)), " sec."
#else
    print '(*(a,:,f0.3))', "Elapsed system time (unknown compiler): ", (end_time - start_time)/real(clock_rate, real64), " sec."
#endif

end program
```

[here]: https://github.com/BerkeleyLab/julienne/issues/155#issuecomment-3651903947
[Fortran 2023 Interpretation Document]: https://go.lbl.gov/fortran-2023

### PR DESCRIPTION
**Pull request by tblah**
The less accurate clock was being adjusted for twice: once in `GetSystemClockCountRate` and again in `ConvertTimevalToCount`.

Also adding missing `static` specifiers I noticed whilst reading the file. I don't know of a way of meaningfully testing this in the repository, but the code in the ticket now produces the correct result.

Fixes #176505

### CODE REVIEW

File: flang-rt/lib/runtime/time-intrinsic.cpp [hunk 1]
```diff
@@ -209,24 +209,20 @@ count_t GetSystemClockCount(int kind, fallback_implementation) {
 #endif // !NO_TIMESPEC
 
 template <typename Unused = void>
-count_t GetSystemClockCountRate(int kind, fallback_implementation) {
-#ifdef NO_TIMESPEC
-  return kind >= 8 ? US_PER_SEC : kind >= 2 ? MS_PER_SEC : DS_PER_SEC;
-#else
+static count_t GetSystemClockCountRate(int kind, fallback_implementation) {
```
Comment (klausler) [inline flang-rt/lib/runtime/time-intrinsic.cpp]: The constant US_PER_SEC might now be unused, which could elicit a C++ compilation warning if so; please check before merging.

**Review by klausler — APPROVED** [review]
One comment to check, otherwise looks great.  Thanks!
