### PR TITLE
[libc++] Implement P3567R2 flat_meow fixes

### LINKED ISSUE #171272: P3567R2: `flat_meow` fixes
Feature-test macros (increased):
```c++
#define __cpp_lib_flat_map                          202511L // also in <flat_map>
#define __cpp_lib_flat_set                          202511L // also in <flat_set>
```

This paper should be treated as a Defect Report and applied to old modes. It resolves LWG4000.

### PR DESCRIPTION
**Pull request by huixie90**
LWG has approved P3567R2 and very likely to be approved in plenary in Kona

Fixes #171272

### CODE REVIEW

File: libcxx/include/__flat_map/flat_map.h
Comment (ldionne) [inline libcxx/include/__flat_map/flat_map.h]: We should update the synopsis for all the flat containers modified here.

File: libcxx/docs/FeatureTestMacroTable.rst
Comment (ldionne) [inline libcxx/docs/FeatureTestMacroTable.rst]: Let's add a release note.

File: libcxx/test/std/containers/container.adaptors/flat.multiset/flat.multiset.modifiers/swap_exception.pass.cpp [hunk 1]
```diff
@@ -7,8 +7,6 @@
 //===----------------------------------------------------------------------===//
 
 // UNSUPPORTED: c++03, c++11, c++14, c++17, c++20
-// `check_assertion.h` requires Unix headers and regex support.
-// REQUIRES: has-unix-headers
 // UNSUPPORTED: no-localization
```
Comment (ldionne) [inline libcxx/test/std/containers/container.adaptors/flat.multiset/flat.multiset.modifiers/swap_exception.pass.cpp]: Can we try removing this?

File: libcxx/test/std/containers/container.adaptors/flat.map/flat.map.modifiers/swap_exception.pass.cpp [hunk 2]
```diff
@@ -7,8 +7,6 @@
 //===----------------------------------------------------------------------===//
 
 // UNSUPPORTED: c++03, c++11, c++14, c++17, c++20
-// `check_assertion.h` requires Unix headers and regex support.
-// REQUIRES: has-unix-headers
 // UNSUPPORTED: no-localization
```
Comment (ldionne) [inline libcxx/test/std/containers/container.adaptors/flat.map/flat.map.modifiers/swap_exception.pass.cpp]:
```suggestion
```

File: libcxx/test/std/containers/container.adaptors/flat.set/flat.set.modifiers/swap_exception.pass.cpp [hunk 3]
```diff
@@ -7,8 +7,6 @@
 //===----------------------------------------------------------------------===//
 
 // UNSUPPORTED: c++03, c++11, c++14, c++17, c++20
-// `check_assertion.h` requires Unix headers and regex support.
-// REQUIRES: has-unix-headers
 // UNSUPPORTED: no-localization
```
Comment (ldionne) [inline libcxx/test/std/containers/container.adaptors/flat.set/flat.set.modifiers/swap_exception.pass.cpp]:
```suggestion
```

**Review by ldionne — APPROVED** [review]
