### PR TITLE
[Attributor] Don't replace `addrspacecast (ptr null to ptr addrspace(x))` with `ptr addrspace(x) null`

### LINKED ISSUE #115083: [AMDGPU] Sprintf test fails after amdgpu-attributor pass
The IR after the `amdgpu-attributor` pass causes the return value of the `sprintf` call to fail in this unit test https://godbolt.org/z/h8x47PjKv. https://github.com/llvm/llvm-project/blob/c1cec8c0dc5b0296f0bc86745b867ff72c0a21e3/libc/test/integration/src/stdio/sprintf_size_test.cpp#L4

### PR DESCRIPTION
**Pull request by shiltian**
`ConstantPointerNull` represents a pointer with value 0, but it doesn’t
necessarily mean a `nullptr`. `ptr addrspace(x) null` is not the same as
`addrspacecast (ptr null to ptr addrspace(x))` if the `nullptr` in AS X is not
zero. Therefore, we can't simply replace it.

Fixes #115083.

### CODE REVIEW

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp [hunk 1]
```diff
@@ -10970,6 +10970,15 @@ struct AAPotentialValuesImpl : AAPotentialValues {
       Value *NewV = getSingleValue(A, *this, getIRPosition(), Values);
       if (!NewV || NewV == &OldV)
         continue;
+      // FIXME: ConstantPointerNull represents a pointer with value 0, but it
+      // doesn’t necessarily mean a nullptr. `ptr addrspace(x) null` is not the
+      // same as `addrspacecast (ptr null to ptr addrspace(x))` if the nullptr
+      // in AS x is not zero. Therefore, we can't simply replace it.
+      if (isa<ConstantPointerNull>(NewV) && isa<ConstantExpr>(OldV)) {
+        auto &CE = cast<ConstantExpr>(OldV);
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10978]: dyn_cast instead of isa + null

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp [hunk 2]
```diff
@@ -10970,6 +10970,15 @@ struct AAPotentialValuesImpl : AAPotentialValues {
       Value *NewV = getSingleValue(A, *this, getIRPosition(), Values);
       if (!NewV || NewV == &OldV)
         continue;
+      // FIXME: ConstantPointerNull represents a pointer with value 0, but it
+      // doesn’t necessarily mean a nullptr. `ptr addrspace(x) null` is not the
+      // same as `addrspacecast (ptr null to ptr addrspace(x))` if the nullptr
+      // in AS x is not zero. Therefore, we can't simply replace it.
+      if (isa<ConstantPointerNull>(NewV) && isa<ConstantExpr>(OldV)) {
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10977]: Does this handle nested subexpressions correctly?

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll [hunk 3]
```diff
@@ -0,0 +1,39 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -S -passes=attributor $s -o - | FileCheck %s
```
[the remark this answers is not in the document]
Comment (shiltian) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:2]: for some reason it work... :-D

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 1 above)
Comment (shiltian) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10978]: yeah, but here we want to check both and only use the name for the second one.

**Comment by shiltian** [comment]
* **#126779** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/126779?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/126779?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 2 above)
Comment (shiltian) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10977]: The result type must be a pointer so that leaves us to `IntToPtr` and `AddrSpaceCast` for the outermost expression. If it is `IntToPtr`, I think they can be directly replaced because the value will have to be 0. With that being said, I think this would work fine.

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10978]: You can use the C++17 `if (auto *CE = dyn_cast<>; CE && CE->getOpcode() != ...)`

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 2 above)
Comment (arsenm) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10977]: Specifically there are some stripPointerCasts that should be restricted to stripPointerCastsSameRepresentation

Comment (shiltian) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10977]: Interestingly, that was exactly the first version of my fix, but I chose the current approach after a second thought.

We still want to look through address space cast when analyzing potential pointer value and/or underlying object. The only thing concerned here is probably nullptr. I think it is okay to treat `ptr addrspace(x) null` same as `addrspacecast (ptr null to ptr addrspace(x))` when we do analysis such that we can know whether a pointer points to nothing, but we will not replace the latter with the former because of the limitation/issue/design we currently have.

On a side note, IMHO, they should be the same and `ptr addrspace(x) null` should present the nullptr in AS x but the source code representation `ConstantPointerNull` means something else. Once we have a new class for DL nullptr, I think `ptr addrspace(x) null` should belong to it.

Comment (nikic) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp]: > We still want to look through address space cast when analyzing potential pointer value and/or underlying object.

It's okay to do this for underlying objects, because the semantics allow it. But I don't think it's valid for PotentialValues.

**Comment by shiltian** [comment]
Ping.

AFAICT, only `ConstantPointerNull` matters here because it represents `null` in all AS. For the others, they are not constant thus will not be replaced by this code path.

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp [hunk 4]
```diff
@@ -10970,6 +10970,15 @@ struct AAPotentialValuesImpl : AAPotentialValues {
...
         continue;
+      // FIXME: ConstantPointerNull represents a pointer with value 0, but it
+      // doesn’t necessarily mean a nullptr. `ptr addrspace(x) null` is not the
+      // same as `addrspacecast (ptr null to ptr addrspace(x))` if the nullptr
+      // in AS x is not zero. Therefore, we can't simply replace it.
+      if (isa<ConstantPointerNull>(NewV)) {
+        if (auto *CE = dyn_cast<ConstantExpr>(&OldV);
+            CE && CE->getOpcode() == Instruction::AddrSpaceCast)
+          continue;
+      }
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10981]: Checking this here, in manifest, and for this specific expression doesn't feel like the right way to address this.

I would trust it slightly more if it was a check on the address space of the pointer type, but I would still expect this logic to be somewhere else

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[TMP0]], ptr [[P0]], ptr null
+; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
+; CHECK-NEXT:    ret i32 [[TMP2]]
+;
+entry:
+  %icmp = icmp eq ptr addrspace(5) %p5, addrspacecast (ptr null to ptr addrspace(5))
+  %select = select i1 %icmp, ptr %p0, ptr null
+  %load = load i32, ptr %select, align 4
+  ret i32 %load
+}
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:18]: Also add another test with a differently typed null

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 4 above)
Comment (arsenm) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10981]: Can this sink somewhere down in getSingleValue?

**Comment by shiltian** [comment]
This will be properly resolved after https://github.com/llvm/llvm-project/pull/131557 (as well as its follow-up patches).

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll (hunk 5 above)
Comment (arsenm) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:18]: Also test vector case ?

**Comment by shiltian** [comment]
I figured it's gonna take much longer time to change the semantics of `ConstantPointerNull` as well as all related stuff, so I pushed an alternative solution here.

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll (hunk 5 above)
Comment (shiltian) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:16]: added one, but we can't differentiate them (at the moment) so even if it has 0 null, it will not be replaced.

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[SELECT]], align 4
+; CHECK-NEXT:    ret i32 [[LOAD]]
+;
+  %loadvec = load <2 x ptr addrspace(5)>, ptr %p1, align 16
+  %icmpvec = icmp eq <2 x ptr addrspace(5)> %loadvec, <ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5)), ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5))>
+  %icmp = extractelement <2 x i1> %icmpvec, i32 1
+  %select = select i1 %icmp, ptr %p0, ptr null
+  %load = load i32, ptr %select, align 4
+  ret i32 %load
+}
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:34]: Also add the versions with addrspace(1) instead of 5 which will use 0 init

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+
+define i32 @foo(ptr %p0, ptr %p1, <2 x ptr addrspace(5)> %ptrvec) {
+; CHECK-LABEL: define i32 @foo(
+; CHECK-SAME: ptr nofree readonly captures(none) [[P0:%.*]], ptr nofree noundef nonnull readonly align 16 captures(none) dereferenceable(16) [[P1:%.*]], <2 x ptr addrspace(5)> [[PTRVEC:%.*]]) #[[ATTR0]] {
+; CHECK-NEXT:    [[LOADVEC:%.*]] = load <2 x ptr addrspace(5)>, ptr [[P1]], align 16
+; CHECK-NEXT:    [[ICMPVEC:%.*]] = icmp eq <2 x ptr addrspace(5)> [[LOADVEC]], <ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5)), ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5))>
```
[the remark this answers is not in the document]
Comment (shiltian) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:22]: `addrspacecast (<2 x ptr> zeroinitializer to <2 x ptr addrspace(5)>)` gets converted to `<ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5)), ptr addrspace(5) addrspacecast (ptr null to ptr addrspace(5))>` automatically even w/o running anything.

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll (hunk 6 above)
Comment (arsenm) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:34]: But you should, that would make the test more useful

Comment (shiltian) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:34]: Added, though honestly I don't think it matters at this point. We don't currently have a way to notify the middle end whether a `nullptr` in a given address space is zero or not, and there's no middle-end hook for that either, so it won't actually change anything in practice. I'd be surprised if it made any difference right now.

**Review by jdoerfert — APPROVED** [review]
I'm not super convinced but it seems necessary for now.
LG

File: llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll (hunk 6 above)
Comment (arsenm) [reply llvm/test/Transforms/Attributor/do-not-replace-addrspacecast-with-constantpointernull.ll:34]: But it will catch the change in the future patch. There's no plus to not making this a target test that will expose the difference
