### PR TITLE
[libcxx][test] Do not assume array::iterator is a pointer

### LINKED ISSUE #100498: [libc++][test] alg.find.last tests assume that `std::array` iterators are pointers
Recently introduced by @strega-nil's #99312. See #74430 for previous fixes.

The following tests assume that `std::array` iterators are pointers, which isn't guaranteed by the Standard, and fails for MSVC's STL:

* [std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last.pass.cpp](https://github.com/llvm/llvm-project/blob/8e43acbfedf53ded43ec693ddaaf518cb7416c1c/libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last.pass.cpp)
* [std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp](https://github.com/llvm/llvm-project/blob/8e43acbfedf53ded43ec693ddaaf518cb7416c1c/libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp)
* [std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if_not.pass.cpp](https://github.com/llvm/llvm-project/blob/8e43acbfedf53ded43ec693ddaaf518cb7416c1c/libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if_not.pass.cpp)

Each test emits many errors. I've attached [full_error_logs.txt](https://github.com/user-attachments/files/16369481/full_error_logs.txt), and here is the full context for the first error emitted by each test (GitHub has a 64K character limit for issues, hence the attachment):

<details><summary>Click to expand first error for ranges.find_last.pass.cpp:</summary>

```
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp(64,34): error: cannot cast from type 'iterator' (aka '_Array_iterator<char, 0>') to pointer type 'char *'
   64 |     return std::ranges::subrange(It(std::ranges::begin(a)), Sent(It(std::ranges::end(a))));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp(93,41): note: in instantiation of function template specialization 'test_iterators()::(anonymous class)::operator()<std::array<char, 0>>' requested here
   93 |       auto ret = std::ranges::find_last(make_range(a), 1).begin();
      |                                         ^
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp(163,7): note: in instantiation of function template specialization 'test_iterators<char *, char *>' requested here
  163 |       test_iterators<Iter>();
      |       ^
D:\GitHub\STL\llvm-project\libcxx\test\support/type_algorithms.h(52,23): note: in instantiation of function template specialization 'test()::(anonymous class)::operator()()::(anonymous class)::operator()<char *>' requested here
   52 |   swallow((f.template operator()<Types>(), 0)...);
      |                       ^
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp(162,12): note: in instantiation of function template specialization 'types::for_each<char *, contiguous_iterator<char *>, random_access_iterator<char *>, bidirectional_iterator<char *>, forward_iterator<char *>, (lambda at D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp:162:57)>' requested here
  162 |     types::for_each(types::forward_iterator_list<T*>{}, []<class Iter> {
      |            ^
D:\GitHub\STL\llvm-project\libcxx\test\support/type_algorithms.h(52,23): note: in instantiation of function template specialization 'test()::(anonymous class)::operator()<char>' requested here
   52 |   swallow((f.template operator()<Types>(), 0)...);
      |                       ^
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp(161,10): note: in instantiation of function template specialization 'types::for_each<char, int, TriviallyComparable<char>, (lambda at D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last.pass.cpp:161:77)>' requested here
  161 |   types::for_each(types::type_list<char, int, TriviallyComparable<char>>{}, []<class T> {
      |          ^
```
</details>

<details><summary>Click to expand first error for ranges.find_last_if.pass.cpp:</summary>

```
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if.pass.cpp(62,32): error: cannot cast from type 'iterator' (aka '_Array_iterator<int, 0>') to pointer type 'const std::_Array_iterator<int, 0> *'
   62 |   return std::ranges::subrange(It(std::ranges::begin(a)), Sent(It(std::ranges::end(a))));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if.pass.cpp(101,44): note: in instantiation of function template specialization 'make_range<const std::_Array_iterator<int, 0> *, const std::_Array_iterator<int, 0> *, std::array<int, 0>>' requested here
  101 |       auto ret = std::ranges::find_last_if(make_range<it, sent>(a), [](auto&&) { return true; }).begin();
      |                                            ^
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if.pass.cpp(191,3): note: in instantiation of function template specialization 'test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>' requested here
  191 |   test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>();
      |   ^
```
</details>

<details><summary>Click to expand first error for ranges.find_last_if_not.pass.cpp:</summary>

```
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if_not.pass.cpp(62,32): error: cannot cast from type 'iterator' (aka '_Array_iterator<int, 0>') to pointer type 'const std::_Array_iterator<int, 0> *'
   62 |   return std::ranges::subrange(It(std::ranges::begin(a)), Sent(It(std::ranges::end(a))));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if_not.pass.cpp(101,48): note: in instantiation of function template specialization 'make_range<const std::_Array_iterator<int, 0> *, const std::_Array_iterator<int, 0> *, std::array<int, 0>>' requested here
  101 |       auto ret = std::ranges::find_last_if_not(make_range<it, sent>(a), [](auto&&) { return false; }).begin();
      |                                                ^
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if_not.pass.cpp(191,3): note: in instantiation of function template specialization 'test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>' requested here
  191 |   test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>();
      |   ^
```
</details>

### PR DESCRIPTION
**Pull request by strega-nil**
In the tests I added for `ranges::find_last{_if{_not}}`, I accidentally introduced an assumption that `same_as<array<T, 0>::iterator, T*>`; this is a faulty assumption on MSVC-STL.

Fixes #100498.

cc @StephanTLavavej, can you test this PR with the MSVC-STL?

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
This LGTM once CI is green, but I am surprised that this wasn't caught by our unstable-ABI job. That job should define `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_ARRAY` and `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_STRING_VIEW`, which use `__wrap_iter` in `array` and `string_view` and should catch those issues.

**Comment by StephanTLavavej** [comment]
@strega-nil There are still errors with MSVC's STL. Full logs: [clang_errors.txt](https://github.com/user-attachments/files/16384329/clang_errors.txt)

Here's my analysis of the first error, which is:

```
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if.pass.cpp(104,21): error: cannot cast from type 'iterator' (aka '_Array_iterator<int, 0>') to pointer type 'it' (aka 'const std::_Array_iterator<int, 0> *')
  104 |       assert(ret == it(a.begin()));
      |                     ^~~~~~~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\assert.h(40,17): note: expanded from macro 'assert'
   40 |             (!!(expression)) ||                                                              \
      |                 ^~~~~~~~~~
D:\GitHub\STL\llvm-project\libcxx\test\std\algorithms\alg.nonmodifying\alg.find.last\ranges.find_last_if.pass.cpp(193,3): note: in instantiation of function template specialization 'test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>' requested here
  193 |   test_iterator_classes<add_const_to_ptr_t, std::type_identity_t>();
      |   ^
```

https://github.com/strega-nil/llvm-project/blob/04a67b5617d11a94627c5ee89f24e2fff9ce8eda/libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp#L104

https://github.com/strega-nil/llvm-project/blob/04a67b5617d11a94627c5ee89f24e2fff9ce8eda/libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp#L188-L193

It appears that `add_const_to_ptr_t` contains the assumption, since it's using `remove_pointer_t` on an array iterator.

**Comment by strega-nil** [comment]
> This LGTM once CI is green, but I am surprised that this wasn't caught by our unstable-ABI job. That job should define `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_ARRAY` and `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_STRING_VIEW`, which use `__wrap_iter` in `array` and `string_view` and should catch those issues.

It looks like defining `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_ARRAY` is not enough to get `array<T, 0>::iterator` to be `int*`...

**Comment by strega-nil** [comment]
@ldionne would you mind taking a look again? I've now actually changed product code (in `array`), since it failed to wrap the iterator for `array<T, 0>`.

**Comment by StephanTLavavej** [comment]
The tests are now passing for MSVC's STL (completely with Clang; with MSVC modulo a compiler bug in `constexpr` evaluation). Thanks!

File: libcxx/include/array [hunk 1]
```diff
@@ -270,18 +270,23 @@ struct _LIBCPP_TEMPLATE_VIS array {
...
+  using iterator       = __wrap_iter<pointer>;
+  using const_iterator = __wrap_iter<const_pointer>;
+#else
+  using iterator       = pointer;
+  using const_iterator = const_pointer;
+#endif
+  using size_type              = size_t;
+  using difference_type        = ptrdiff_t;
+  using reverse_iterator       = std::reverse_iterator<iterator>;
+  using const_reverse_iterator = std::reverse_iterator<const_iterator>;
```
Comment (mordante) [inline libcxx/include/array:289]: Nice, thanks!

File: libcxx/test/support/test_iterators.h [hunk 2]
```diff
@@ -339,59 +339,91 @@ cpp20_random_access_iterator(It) -> cpp20_random_access_iterator<It>;
...
 
-    template <class U> friend class contiguous_iterator;
 public:
     typedef          std::contiguous_iterator_tag              iterator_category;
     typedef typename std::iterator_traits<It>::value_type      value_type;
     typedef typename std::iterator_traits<It>::difference_type difference_type;
     typedef It                                                 pointer;
     typedef typename std::iterator_traits<It>::reference       reference;
-    typedef typename std::remove_pointer<It>::type             element_type;
+    typedef value_type element_type;
```
Comment (mordante) [inline libcxx/test/support/test_iterators.h:355]: please fix the alignment with the lines above.

File: libcxx/test/support/test_iterators.h [hunk 3]
```diff
@@ -339,59 +339,91 @@ cpp20_random_access_iterator(It) -> cpp20_random_access_iterator<It>;
...
+
+    constexpr contiguous_iterator& operator+=(difference_type n) {
+      it_ += n;
+      return *this;
+    }
+    constexpr contiguous_iterator& operator-=(difference_type n) {
+      it_ -= n;
+      return *this;
+    }
+    friend constexpr contiguous_iterator operator+(contiguous_iterator x, difference_type n) {
```
Comment (mordante) [inline libcxx/test/support/test_iterators.h:391]: Why change this? It at least makes the class not usable in C++03. This function it can't be constexpr in C++11, it's more than just a return statement.

**Review by mordante — COMMENTED** [review]
In general it looks good, but I'd like to understand the `constexpr` changes for the `contiguous_iterator`

File: libcxx/include/array [hunk 4]
```diff
@@ -270,18 +270,23 @@ struct _LIBCPP_TEMPLATE_VIS array {
...
+  using const_reference = const value_type&;
+  using pointer         = value_type*;
+  using const_pointer   = const value_type*;
+#if defined(_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_ARRAY)
+  using iterator       = __wrap_iter<pointer>;
+  using const_iterator = __wrap_iter<const_pointer>;
+#else
+  using iterator       = pointer;
+  using const_iterator = const_pointer;
+#endif
```
Comment (philnik777) [inline libcxx/include/array:285]: Can we put this in a separate patch? Technically this could be ABI breaking, since we change the meaning of `_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_ARRAY`. I'm pretty sure it's fine in this case, since we've only introduced this macro recently, but this is potentially API breaking for people (see this very patch). It's also not dependent on the rest of this patch or vice versa.

File: libcxx/test/support/test_iterators.h (hunk 3 above)
Comment (strega-nil) [reply libcxx/test/support/test_iterators.h:391]: This is in a C++17 block.

File: libcxx/include/array (hunk 4 above)
Comment (strega-nil) [reply libcxx/include/array:285]: Sure, I can do that.

**Comment by Zingam** [comment]
@strega-nil Off-topic question are the changes to array and contigious_iterator supposed to fix this type of an error:
>  error: no matching conversion for functional-style cast from 'std::__wrap_iter<int *>' to 'contiguous_iterator<int *>'

**Comment by strega-nil** [comment]
> @strega-nil Off-topic question: are the changes to array and contigious_iterator supposed to fix this type of an error:
> 
> > error: no matching conversion for functional-style cast from 'std::__wrap_iter<int *>' to 'contiguous_iterator<int *>'

No, these would fix `contiguous_iterator<std::__wrap_iter<int*>>` to work at all.

File: libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp [hunk 5]
```diff
@@ -183,8 +183,17 @@ struct NonConstComparable {
   friend constexpr bool operator==(NonConstComparable&, const NonConstComparable&) { return true; }
 };
 
+// note: this should really use `std::const_iterator`
```
Comment (cjdb) [inline libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp:186]: Can you open an issue and change this to a TODO instead please? AIUI we're only not doing that because `const_iterator` isn't around yet.

**Review by cjdb — APPROVED** [review]
LGTM with one request!

File: libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp (hunk 5 above)
Comment (strega-nil) [reply libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp:186]: Sure.

Comment (cjdb) [reply libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp]: Oh, I meant using the issue in the todo as `TODO(<#issue-number>): <reason>`.

**Comment by strega-nil** [comment]
Merging as the only failure was agent lost, and the previous commit (before a comment-only change) did pass.

File: libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp (hunk 5 above)
Comment (cjdb) [reply libcxx/test/std/algorithms/alg.nonmodifying/alg.find.last/ranges.find_last_if.pass.cpp]: > Oh, I meant using the issue in the todo as `TODO(<#issue-number>): <reason>`.

This was a part of my conditional LGTM. I will make it clearer in future reviews.
