### PR TITLE
Fix stack layout for frames larger than 2gb

### LINKED ISSUE #48911: Computation of locals' offsets is wrong when stack size exceeds 2G
|  |  |
| --- | --- |
| Bugzilla Link | [49567](https://llvm.org/bz49567) |
| Version | trunk |
| OS | All |
| CC | @topperc,@cuviper,@jdm,@RKSimon,@phoebewang,@rotateright,@oToToT |

## Extended Description 
Given the following test case:

    ; RUN: llc -O0 -mtriple=x86_64 < %s
    ; RUN: llc -O0 -mtriple=i686 < %s

    %large = type [2148000000 x i8]

    define void @banana() unnamed_addr #0 {
      %1 = alloca %large, align 1
      %2 = alloca %large, align 1
      %3 = getelementptr inbounds %large, %large* %1, i64 0, i64 0
      store i8 42, i8* %3, align 1
      %4 = getelementptr inbounds %large, %large* %2, i64 0, i64 0
      store i8 43, i8* %4, align 1
      ret void
    }

Will produce the following assembly:

	movabsq	$4295999872, %rax               # imm = 0x1000FC180
	subq	%rax, %rsp
	.cfi_def_cfa_offset 1032584
	movb	$42, -2146967424(%rsp)
	movb	$43, -128(%rsp)
	movabsq	$4295999872, %rax               # imm = 0x1000FC180
	addq	%rax, %rsp
	.cfi_def_cfa_offset 8
	retq

You will notice that both the variables `alloca`d in this function are considered to be below the already adjusted stack pointer, rather than above it, where they ought to be.

This looks like a basic signed 32-bit integer overflow somewhere in prologepilog:
```
# *** IR Dump Before Prologue/Epilogue Insertion & Frame Finalization (prologepilog) ***:
# Machine code for function banana: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten
Frame Objects:
  fi#0: size=2148000000, align=1, at location [SP+8]
  fi#1: size=2148000000, align=1, at location [SP+8]

bb.0 (%ir-block.0):
  MOV8mi %stack.0, 1, $noreg, 0, $noreg, 42 :: (store 1 into %ir.3)
  MOV8mi %stack.1, 1, $noreg, 0, $noreg, 43 :: (store 1 into %ir.4)
  RET 0

# *** IR Dump After Prologue/Epilogue Insertion & Frame Finalization (prologepilog) ***:
# Machine code for function banana: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten
Frame Objects:
  fi#0: size=2148000000, align=1, at location [SP-2148000000]
  fi#1: size=2148000000, align=1, at location [SP-4296000000]

bb.0 (%ir-block.0):
  $rax = frame-setup MOV64ri 4295999872
  $rsp = SUB64rr $rsp(tied-def 0), $rax, implicit-def dead $eflags
  CFI_INSTRUCTION def_cfa_offset 1032584
  MOV8mi $rsp, 1, $noreg, -2146967424, $noreg, 42 :: (store 1 into %ir.3)
  MOV8mi $rsp, 1, $noreg, -128, $noreg, 43 :: (store 1 into %ir.4)
  $rax = frame-destroy MOV64ri 4295999872
  $rsp = ADD64rr $rsp(tied-def 0), $rax, implicit-def dead $eflags
  CFI_INSTRUCTION def_cfa_offset 8
  RET 0
```
Worth noting that the the `def_cfa_offset` directive also overflowed in this reproducer here.

### PR DESCRIPTION
**Pull request by wesleywiser**
For very large stack frames, the offset from the stack pointer to a
local can be more than 2^31 which overflows various `int` offsets
in the frame lowering code.

This patch updates the frame lowering code to calculate the offsets as
64-bit values and resolves the overflows, resulting in the correct
codegen for very large frames.

Fixes #48911

### CODE REVIEW

File: llvm/include/llvm/CodeGen/MachineFrameInfo.h [hunk 1]
```diff
@@ -280,7 +280,7 @@ class MachineFrameInfo {
   /// setup/destroy pseudo instructions (as defined in the TargetFrameInfo
   /// class).  This information is important for frame pointer elimination.
   /// It is only valid during and after prolog/epilog code insertion.
-  unsigned MaxCallFrameSize = ~0u;
+  unsigned long MaxCallFrameSize = ~0ul;
```
Comment (RKSimon) [inline llvm/include/llvm/CodeGen/MachineFrameInfo.h:283]: uint64_t ?

Comment (wesleywiser) [reply llvm/include/llvm/CodeGen/MachineFrameInfo.h:283]: I wasn't entirely sure when to use `unsigned long`/`long` instead of `uint64_t`/`int64_t` so I tried to follow the convention of the code I was changing. 

Is there a preferred style I should be using across the whole patch or would you prefer I just update this instance?

Comment (RKSimon) [reply llvm/include/llvm/CodeGen/MachineFrameInfo.h:283]: I'd prefer explicit fixed bitwidth integer types in structs wherever possible tbh

Comment (wesleywiser) [reply llvm/include/llvm/CodeGen/MachineFrameInfo.h]: Updated!

File: llvm/test/CodeGen/X86/huge-stack.ll [hunk 2]
```diff
@@ -0,0 +1,22 @@
+; RUN: llc -O0 -mtriple=x86_64 < %s | FileCheck %s --check-prefix=CHECK
+%large = type [4294967295 x i8]
+
+define void @foo() unnamed_addr #0 {
+  %1 = alloca %large, align 1
+  %2 = alloca %large, align 1
+  %3 = getelementptr inbounds %large, %large* %1, i64 0, i64 0
```
Comment (MaskRay) [inline llvm/test/CodeGen/X86/huge-stack.ll:7]: Use `ptr` opaque types for new tests.

Comment (wesleywiser) [reply llvm/test/CodeGen/X86/huge-stack.ll]: Done!

File: llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp [hunk 3]
```diff
@@ -1376,7 +1376,7 @@ class DarwinX86AsmBackend : public X86AsmBackend {
         memset(SavedRegs, 0, sizeof(SavedRegs));
         StackAdjust = 0;
         SavedRegIdx = 0;
-        MinAbsOffset = std::numeric_limits<int>::max();
+        MinAbsOffset = std::numeric_limits<long>::max();
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp:1379]: long ?

File: llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp [hunk 4]
```diff
@@ -1419,7 +1419,7 @@ class DarwinX86AsmBackend : public X86AsmBackend {
         unsigned Reg = *MRI.getLLVMRegNum(Inst.getRegister(), true);
         SavedRegs[SavedRegIdx++] = Reg;
         StackAdjust += OffsetSize;
-        MinAbsOffset = std::min(MinAbsOffset, abs(Inst.getOffset()));
+        MinAbsOffset = std::min<int64_t>(MinAbsOffset, llabs(Inst.getOffset()));
```
Comment (RKSimon) [inline llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp:1422]: is it necessary to use llabs?

Comment (wesleywiser) [reply llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp:1422]: I think so but advice would be appreciated! My understanding is that on *nix, `long` is a 64-bit signed integer while on Windows, `long` is a 32-bit signed integer. Therefore `labs` is sufficient on *nix where `int64_t` and `long` are both 64-bit but will cause incorrect results on Windows as the `int64_t` will be shortened to a 32-bit `long`. 

Using `llabs` will work correctly on Windows as `long long` is a 64-bit signed integer but on *nix will cause a promotion from `int64_t` to a 128-bit integer and then subsequent conversion back to 64-bit. I think this is ~fine but inefficient.

I looked briefly to see if there was an LLVM utility function somewhere with an implementation of `abs` for `int64_t` but didn't find anything. Is there a better way to handle this?

**Comment by wesleywiser** [comment]
The Windows failure appears to be unrelated to my change. If I checkout the commit prior to my first change, I still get the same failure in `python/dialects/arith_dialect.py`.

File: llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp (hunk 4 above)
Comment (wesleywiser) [reply llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp]: I realized we call `std::abs(int64_t)` in a variety of other places so I just updated this to do the same.

**Comment by wesleywiser** [comment]
I rebased to resolve merge conflicts. Please let me know if you'd like me to squash the history!

**Review by RKSimon — APPROVED** [review]
LGTM - @MaskRay any more comments?

File: llvm/test/CodeGen/PowerPC/huge-frame-size.ll [hunk 5]
```diff
@@ -18,7 +18,7 @@ define void @foo(i8 %x) {
 ; CHECK-LE-NEXT:    oris 0, 0, 65535
 ; CHECK-LE-NEXT:    ori 0, 0, 65504
 ; CHECK-LE-NEXT:    stdux 1, 1, 0
-; CHECK-LE-NEXT:    .cfi_def_cfa_offset 32
+; CHECK-LE-NEXT:    .cfi_def_cfa_offset 4294967328
```
Comment (chenzheng1030) [inline llvm/test/CodeGen/PowerPC/huge-frame-size.ll:21]: This looks correct now on PPC. stack size is 4294967296 + linkagesize(32) = 4294967328 (0x100000020). Without the change, it is truncated to 0x20.

File: llvm/test/CodeGen/X86/huge-stack.ll [hunk 6]
```diff
@@ -1,7 +1,19 @@
...
 ; RUN: llc -O0 -mtriple=x86_64 < %s | FileCheck %s --check-prefix=CHECK
 %large = type [4294967295 x i8]
 
 define void @foo() unnamed_addr #0 {
+; CHECK-LABEL: foo:
+; CHECK:       # %bb.0:
+; CHECK-NEXT:    movabsq $8589934462, %rax # imm = 0x1FFFFFF7E
+; CHECK-NEXT:    subq %rax, %rsp
+; CHECK-NEXT:    .cfi_def_cfa_offset 8589934470
+; CHECK-NEXT:    movb $42, {{[0-9]+}}(%rsp)
```
Comment (wesleywiser) [inline llvm/test/CodeGen/X86/huge-stack.ll:11]: When I updated this test to be autogenerated, I overlooked that it replaced the offsets with regex expressions. The offsets are super important for this test so I'll see if `update_llc_test_checks.py` supports not doing this transformation or revert this change and leave them as manual tests.

Comment (RKSimon) [reply llvm/test/CodeGen/X86/huge-stack.ll:11]: `no_x86_scrub_sp` should do what you're after

Comment (wesleywiser) [reply llvm/test/CodeGen/X86/huge-stack.ll]: Yep, that did it. Thanks!

**Review by RKSimon — APPROVED** [review]
LGTM

File: llvm/include/llvm/MC/MCDwarf.h [hunk 7]
```diff
@@ -538,30 +538,30 @@ class MCCFIInstruction {
...
+                                    int64_t Offset, SMLoc Loc = {}) {
     return MCCFIInstruction(OpDefCfa, L, Register, Offset, Loc);
   }
 
   /// .cfi_def_cfa_register modifies a rule for computing CFA. From now
   /// on Register will be used instead of the old one. Offset remains the same.
   static MCCFIInstruction createDefCfaRegister(MCSymbol *L, unsigned Register,
                                                SMLoc Loc = {}) {
-    return MCCFIInstruction(OpDefCfaRegister, L, Register, 0, Loc);
+    return MCCFIInstruction(OpDefCfaRegister, L, Register, INT64_C(0), Loc);
```
Comment (MaskRay) [inline llvm/include/llvm/MC/MCDwarf.h:550]: `INT64_C(0)` is not necessary. 0 is fairly common for int64_t.

**Review by MaskRay — APPROVED** [review]

File: llvm/include/llvm/MC/MCDwarf.h (hunk 7 above)
Comment (RKSimon) [reply llvm/include/llvm/MC/MCDwarf.h:550]: @wesleywiser Please can you fix those cases before I commit.

Comment (wesleywiser) [reply llvm/include/llvm/MC/MCDwarf.h:550]: Without the explicit cast, gcc complains the call is ambiguous:

```
/home/wesley/llvm-project2/llvm/include/llvm/MC/MCDwarf.h:550:66: error: call of overloaded ‘MCCFIInstruction(llvm::MCCFIInstruction::OpType, llvm::MCSymbol*&, unsigned int&, int, llvm::SMLoc&)’ is ambiguous
  550 |     return MCCFIInstruction(OpDefCfaRegister, L, Register, 0, Loc);
      |                                                                  ^
/home/wesley/llvm-project2/llvm/include/llvm/MC/MCDwarf.h:526:3: note: candidate: ‘llvm::MCCFIInstruction::MCCFIInstruction(llvm::MCCFIInstruction::OpType, llvm::MCSymbol*, unsigned int, unsigned int, llvm::SMLoc)’
  526 |   MCCFIInstruction(OpType Op, MCSymbol *L, unsigned R1, unsigned R2, SMLoc Loc)
      |   ^~~~~~~~~~~~~~~~
/home/wesley/llvm-project2/llvm/include/llvm/MC/MCDwarf.h:519:3: note: candidate: ‘llvm::MCCFIInstruction::MCCFIInstruction(llvm::MCCFIInstruction::OpType, llvm::MCSymbol*, unsigned int, int64_t, llvm::SMLoc, llvm::StringRef, llvm::StringRef)’
  519 |   MCCFIInstruction(OpType Op, MCSymbol *L, unsigned R, int64_t O, SMLoc Loc,
      |   ^~~~~~~~~~~~~~~~
```

Is there a different way I should solve that?

Comment (RKSimon) [reply llvm/include/llvm/MC/MCDwarf.h:550]: OK, we can try to cleanup later

**Comment by RKSimon** [comment]
@wesleywiser we're seeing some EXPENSIVE_CHECKS builds failures - I'm going to revert the patch and add `-verify-machineinstrs` to the problem tests (they should have had this anyhow)

**Comment by wesleywiser** [comment]
@RKSimon thanks for the heads up! Is that something I need to look into? (Sorry, still new to contributing to LLVM)

**Comment by RKSimon** [comment]
If you take a look at the tests I've updated in f92fa7e2cf38341211af262b21c568bef4d76b10 - these should now fail (I'd recommend adding -verify-machineinstrs to X86/huge-stack.ll test as well)

**Comment by wesleywiser** [comment]
@RKSimon thanks for the ping! I've been away last week and haven't had a ton of time to look deeply at it. The crux of the issue is that with my changes, we correctly calculate the offset to various stack locals as being larger than will fit in a 32-bit displacement:

```
MOV8mi $rsp, 1, $noreg, 4294967167, $noreg, 42 :: (store (s8) into %ir.3)
```

If my understanding of x86_64 displacements is correct, then the verification failure is entirely valid as this can't be represented by the displacement. I'm not sure what the right way to fix this is. I think I could change the Prologue/Epilogue Inserter to insert an `lea` to calculate the right address and then perform the `mov`. 

Is there an existing way to handle this? It seems like this kind of situation could occur in many different parts of x86_64 codegen.

**Comment by RKSimon** [comment]
@phoebewang any preference to how we fix this?

**Comment by phoebewang** [comment]
> @phoebewang any preference to how we fix this?

Do you mean https://github.com/llvm/llvm-project/issues/87154? I took a quick look at it. The problem happens in fastISel only. It looks to me DAGISel can select to `lea` or `mov` with different offset. I didn't look deep into it, but guess we may learn how DAGISel handle it or bail out to DAGISel otherwise?

**Comment by efriedma-quic** [comment]
On non-x86 targets, frame indexes that use an addressing mode that ends up being illegal are not rare.  Rare enough that it doesn't really matter for performance, but not so rare it doesn't come up.  In that case, we scavenge a register and generate equivalent math.  It should be possible to do the same on x86.

There are various tricks you can use to make scavenging happen less frequently; for example, using LocalStackSlotAllocation to lower frame indexes for large allocations.

**Comment by MaskRay** [comment]
The patch is still in the reverted, not relanded state.

The patch will resolve a  signed integer overflow at X86RegisterInfo.cpp:951 #75944
