### PR TITLE
[flang] Fixed regression in copy-in/copy-out

### LINKED ISSUE #159149: [flang] Modifying dummy argument via its global actual argument failed for array case with 2 or more elements
Consider the following code:
```
module m
    type base
        integer*4 :: id = -1
        contains
        procedure :: print => printBase
        procedure :: increaseID => increaseBaseID
    end type

    type, extends (base) :: child
        character*20 :: name = 'default'
        contains
        procedure :: print => printChild
    end type

    class (base), pointer :: b1_m (:)

    type (child), save, target :: c1_m (1)
    type (child), save, target :: c2_m (2)

    class (base), pointer :: b1_m_s
    type (child), save, target :: c1_m_s

    contains
    elemental subroutine increaseBaseID (b, i1)
        class (base), intent(inout) :: b
        integer*4, intent(in) :: i1

        b%id = b%id + i1
    end subroutine

    subroutine printBase (b)
        class (base), intent(in) :: b

        print *, b%id
    end subroutine

    subroutine printChild (b)
        class (child), intent(in) :: b

        print *, b%id, b%name
    end subroutine

    subroutine test1 (b)
        type (base), target, intent(inout) :: b (:)

        call b1_m%increaseID (10)
        call b(1)%print
    end subroutine

    subroutine test1_s (b)
        type (base), target, intent(inout) :: b

        call b1_m_s%increaseID (10)
        call b%print
    end subroutine
end module


program fArg033a3
use m

    c1_m = (/child (1,'c1_m')/)
    c2_m = (/(child (i,'c1_m'), i=1,2)/)

    b1_m => c2_m              !! ERROR case: array of 2 elements
    call test1 (b1_m)

    b1_m => c1_m              !! WORKING case: array of 1 element
    call test1 (b1_m)

    c1_m_s = child (1,'c1_m') !! WORKING case: scalar
    b1_m_s => c1_m_s
    call test1_s (b1_m_s)
end
```

Flang failed to update the global variable `c2_m` that is an array of 2 elements in the ERROR case. 
It works fine for the `c1_m` case that is an array of 1 element.
It works fine for the `c1_m_s`, the scalar case.

Flang outputs
```
> a.out
 1
 11
 11
```

Expected output
```
> a.out
 11
 11
 11
```

### PR DESCRIPTION
**Pull request by eugeneepshteyn**
Fixed the polymprphic check for copy-in/copy-out, added regression tests.

Changed MayNeedCopy() to return std::optional<bool> and renamed it to ActualArgNeedsCopy().  This function now returns true/false when it's known that actual arguments needs copy in/out, or std::nullopt to signify that it's now known, whether copy in/out is needed.

Fixes #159149

### CODE REVIEW

File: flang/lib/Evaluate/check-expression.cpp [hunk 1]
```diff
@@ -1493,32 +1493,21 @@ class CopyInOutExplicitInterface {
...
+    // the actual argument could be polymorphic array of child type,
+    // while the dummy argument could be non-polymorphic array of parent
+    // type.)
+    if (dummyObj_.ignoreTKR.test(common::IgnoreTKR::Type)) {
+      return false;
+    }
+    auto actualType{characteristics::TypeAndShape::Characterize(actual_, fc_)};
+    if (actualType && actualType->type().IsPolymorphic() &&
+        !actualType->type().IsAssumedType() &&
+        !dummyObj_.IsPassedByDescriptor(/*isBindC*/ false)) {
```
[the remark this answers is not in the document]
Comment (eugeneepshteyn) [reply flang/lib/Evaluate/check-expression.cpp:1507]: > I do not get why passing by descriptor matters here. It is possible to have assumed shape arrays with the CONTIGUOUS attribute in which case a contiguous copy is still needed even if they are passed by descriptors.

That's why contiguity check is done first. Once contiguity is out of the picture, checking for descriptor differences between actual and dummy args seems to work nicely here.

File: flang/lib/Lower/ConvertCall.cpp [hunk 2]
```diff
@@ -1296,10 +1296,14 @@ static PreparedDummyArgument preparePresentUserCallActualArgument(
...
         callContext.converter.getFoldingContext()};
 
-    bool suggestCopyIn = Fortran::evaluate::MayNeedCopy(
-        arg.entity, arg.characteristics, foldingContext, /*forCopyOut=*/false);
-    bool suggestCopyOut = Fortran::evaluate::MayNeedCopy(
-        arg.entity, arg.characteristics, foldingContext, /*forCopyOut=*/true);
+    bool suggestCopyIn = Fortran::evaluate::ActualArgNeedsCopy(
+                             arg.entity, arg.characteristics, foldingContext,
+                             /*forCopyOut=*/false)
+                             .value_or(false);
```
Comment (jeanPerier) [inline flang/lib/Lower/ConvertCall.cpp]: I would expect `value_or(true)` here and just below (i.e., if we are not sure at compile time, we generate the code that will generate the copy conditionally at runtime based on the contiguity).

**Review by jeanPerier — COMMENTED** [review]
Thanks Eugene, a few comments but this is going in the direction I expect.

File: flang/lib/Evaluate/check-expression.cpp [hunk 3]
```diff
@@ -1572,28 +1553,35 @@ class CopyInOutExplicitInterface {
...
   const bool forCopyIn = !forCopyOut;
   if (!evaluate::IsVariable(*actual)) {
-    // Actual argument expressions that aren’t variables are copy-in, but
-    // not copy-out.
+    // Expressions are copy-in, but not copy-out.
     return forCopyIn;
   }
+  auto maybeContigActual{IsContiguous(*actual, fc)};
+  bool isContiguousActual{
+      maybeContigActual.has_value() && maybeContigActual.value()};
```
[the remark this answers is not in the document]
Comment (eugeneepshteyn) [reply flang/lib/Evaluate/check-expression.cpp]: So, basically, `IsSimplyContiguous()` ;-)

(I originally had plans to do something with `std::optional<bool>` returned by `IsContiguous()`, but then abandoned them.)

File: flang/lib/Lower/ConvertCall.cpp (hunk 2 above)
Comment (eugeneepshteyn) [reply flang/lib/Lower/ConvertCall.cpp]: This results in 56 regressions in lowering tests, which likely means there are some "unknown" cases that should be "known false". I'll investigate.

File: flang/lib/Evaluate/check-expression.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (akuhlens) [reply flang/lib/Evaluate/check-expression.cpp]: `maybeContigActual.value_or(false)`?

File: flang/lib/Evaluate/check-expression.cpp [hunk 4]
```diff
@@ -1575,28 +1559,33 @@ class CopyInOutExplicitInterface {
...
+    return unknown;
   }
   if (actual->isAlternateReturn()) {
-    return false;
+    return unknown;
   }
   const auto *dummyObj{dummy
           ? std::get_if<characteristics::DummyDataObject>(&dummy->u)
           : nullptr};
   const bool forCopyIn = !forCopyOut;
```
Comment (klausler) [inline flang/lib/Evaluate/check-expression.cpp]: braced initialization, please

File: flang/lib/Evaluate/check-expression.cpp [hunk 5]
```diff
@@ -1575,28 +1559,33 @@ class CopyInOutExplicitInterface {
...
+//
 // Note that these copy-in and copy-out checks are done from the caller's
 // perspective, meaning that for copy-in the caller need to do the copy
 // before calling the callee. Similarly, for copy-out the caller is expected
 // to do the copy after the callee returns.
-bool MayNeedCopy(const ActualArgument *actual,
+std::optional<bool> ActualArgNeedsCopy(const ActualArgument *actual,
     const characteristics::DummyArgument *dummy, FoldingContext &fc,
     bool forCopyOut) {
+  constexpr auto unknown = std::nullopt;
```
Comment (klausler) [inline flang/lib/Evaluate/check-expression.cpp]: maybe this would increase readability if it were visible to clients, but it doesn't improve anything in the implementation.

**Review by jeanPerier — APPROVED** [review]
Thanks for addressing my comments @eugeneepshteyn.

**Review by klausler — APPROVED** [review]
