### PR TITLE
[DirectX] Bug fix for Data Scalarization crash

### LINKED ISSUE #117273: [DirectX] DXIL Data Scalarization crash
The following shader to compute a mandelbrot set crashes the DXIL Data Scalarizer:

```hlsl
RWBuffer<float4> Tex;

const static float3 Palette[8] = {float3(0.0, 0.0, 0.0), float3(0.5, 0.5, 0.5),
                                  float3(1.0, 0.5, 0.5), float3(0.5, 1.0, 0.5),
                                  float3(0.5, 0.5, 1.0), float3(0.5, 1.0, 1.0),
                                  float3(1.0, 0.5, 1.0), float3(1.0, 1.0, 0.5)};

const static int Dimension = 4096;

[numthreads(1024, 1, 1)] void main(uint3 DID
                                   : SV_DispatchThreadID) {
  float scale = 1.5 / pow(2.0, 16.0 * abs(sin(0.25 / 16.0)));
  float2 offset = float2(-1.0, 0.0);
  uint2 Index =
      uint2(DID.x % Dimension, DID.x / Dimension + (Dimension * DID.y));
  uint2 DispatchSize = Dimension.xx;
  float X0 =
      scale * (2.0 * (float)Index.x / (float)DispatchSize.x - 1.5) + offset.x;
  float Y0 =
      scale * (2.0 * (float)Index.y / (float)DispatchSize.y - 1.0) + offset.y;

  // Implement Mandelbrot set
  float X = X0;
  float Y = Y0;
  uint Iteration = 0;
  uint MaxIteration = 2000;
  float XTmp = 0.0;
  bool Diverged = false;
  for (; Iteration < MaxIteration; ++Iteration) {
    if (X * X + Y * Y > 2000 * 2000) {
      Diverged = true;
      break;
    }
    XTmp = X * X - Y * Y + X0;
    Y = 2 * X * Y + Y0;
    X = XTmp;
  }

  float3 Color = float3(0, 0, 0);
  if (Diverged) {
    float Gradient = 1.0;
    float Smooth = log2(log2(X * X + Y * Y) / 2.0);
    float ColorIdx = sqrt((float)Iteration + 10.0 - Smooth) * Gradient;
    float LerpSize = frac(ColorIdx);
    LerpSize = LerpSize * LerpSize * (3.0 - 2.0 * LerpSize);
    int ColorIdx1 = (int)ColorIdx % 8;
    int ColorIdx2 = (ColorIdx1 + 1) % 8;
    Color = lerp(Palette[ColorIdx1], Palette[ColorIdx2], LerpSize.xxx);
  }

  Tex[DID.x] = float4(Color, 1.0);
}
```

Crash backtrace:

```
0.      Program arguments: C:\\Users\\cbieneman\\dev\\llvm-project\\llvm\\out\\build\\x64-Clang-Debug\\bin\\clang-dxc.exe -cc1 -triple dxilv1.0-unknown-shadermodel6.0-compute -emit-obj -dumpdir a- -disable-free -clear-ast-before-backend -main-file-name Mandelbrot.hlsl -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -debugger-tuning=gdb -fdebug-compilation-dir=C:\\Users\\cbieneman\\dev\\llvm-project\\llvm\\out\\build\\x64-Clang-Debug -fcoverage-compilation-dir=C:\\Users\\cbieneman\\dev\\llvm-project\\llvm\\out\\build\\x64-Clang-Debug -resource-dir C:\\Users\\cbieneman\\dev\\llvm-project\\llvm\\out\\build\\x64-Clang-Debug\\lib\\clang\\20 -O3 -ferror-limit 19 -fmessage-length=350 -O3 -finclude-default-header -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -vectorize-loops -vectorize-slp -o mandelbrot.yaml -x hlsl C:\\Users\\cbieneman\\dev\\hlsl-test-suite\\test\\Basic\\Inputs\\Mandelbrot.hlsl
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'DXIL Data Scalarization' on module 'C:\Users\cbieneman\dev\hlsl-test-suite\test\Basic\Inputs\Mandelbrot.hlsl'.
Exception Code: 0xC0000005
 #0 0x00007ff735544409 llvm::Value::getValueID(void) const C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\IR\Value.h:533:0
 #1 0x00007ff73556dc13 llvm::ConstantExpr::classof(class llvm::Value const *) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\IR\Constants.h:1385:0
 #2 0x00007ff7365085d3 llvm::isa_impl<class llvm::ConstantExpr, class llvm::User, void>::doit(class llvm::User const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:64:0
 #3 0x00007ff7367fd679 llvm::isa_impl_cl<class llvm::ConstantExpr, class llvm::User const *>::doit(class llvm::User const *) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:110:0
 #4 0x00007ff7367fd636 llvm::isa_impl_wrap<class llvm::ConstantExpr, class llvm::User const *, class llvm::User const *>::doit(class llvm::User const *const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:137:0
 #5 0x00007ff7367fd601 llvm::isa_impl_wrap<class llvm::ConstantExpr, class llvm::User const *const, class llvm::User const *>::doit(class llvm::User const *const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:127:0
 #6 0x00007ff7367fd5c3 llvm::CastIsPossible<class llvm::ConstantExpr, class llvm::User const *, void>::isPossible(class llvm::User const *const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:255:0
 #7 0x00007ff7367fd591 llvm::CastInfo<class llvm::ConstantExpr, class llvm::User *const, void>::isPossible(class llvm::User *const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:509:0
 #8 0x00007ff7367fc583 llvm::isa<class llvm::ConstantExpr, class llvm::User *>(class llvm::User *const &) C:\Users\cbieneman\dev\llvm-project\llvm\include\llvm\Support\Casting.h:549:0
 #9 0x00007ff7367fb947 findAndReplaceVectors C:\Users\cbieneman\dev\llvm-project\llvm\lib\Target\DirectX\DXILDataScalarization.cpp:248:0
#10 0x00007ff7367fbb68 DXILDataScalarizationLegacy::runOnModule(class llvm::Module &) C:\Users\cbieneman\dev\llvm-project\llvm\lib\Target\DirectX\DXILDataScalarization.cpp:284:0
#11 0x00007ff73594e646 `anonymous namespace'::MPPassManager::runOnModule C:\Users\cbieneman\dev\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1521:0
#12 0x00007ff73594e10a llvm::legacy::PassManagerImpl::run(class llvm::Module &) C:\Users\cbieneman\dev\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:539:0
#13 0x00007ff735952de1 llvm::legacy::PassManager::run(class llvm::Module &) C:\Users\cbieneman\dev\llvm-project\llvm\lib\IR\LegacyPassManager.cpp:1648:0
#14 0x00007ff737667208 `anonymous namespace'::EmitAssemblyHelper::RunCodegenPipeline C:\Users\cbieneman\dev\llvm-project\clang\lib\CodeGen\BackendUtil.cpp:1197:0
#15 0x00007ff737660f2b `anonymous namespace'::EmitAssemblyHelper::EmitAssembly C:\Users\cbieneman\dev\llvm-project\clang\lib\CodeGen\BackendUtil.cpp:1221:0
#16 0x00007ff7376601ef clang::EmitBackendOutput(class clang::DiagnosticsEngine &, class clang::HeaderSearchOptions const &, class clang::CodeGenOptions const &, class clang::TargetOptions const &, class clang::LangOptions const &, class llvm::StringRef, class llvm::Module *, enum clang::BackendAction, class llvm::IntrusiveRefCntPtr<class llvm::vfs::FileSystem>, class std::unique_ptr<class llvm::raw_pwrite_stream, struct std::default_delete<class llvm::raw_pwrite_stream>>, class clang::BackendConsumer *) C:\Users\cbieneman\dev\llvm-project\clang\lib\CodeGen\BackendUtil.cpp:1386:0
#17 0x00007ff738031450 clang::BackendConsumer::HandleTranslationUnit(class clang::ASTContext &) C:\Users\cbieneman\dev\llvm-project\clang\lib\CodeGen\CodeGenAction.cpp:355:0
#18 0x00007ff73ade1e03 clang::ParseAST(class clang::Sema &, bool, bool) C:\Users\cbieneman\dev\llvm-project\clang\lib\Parse\ParseAST.cpp:191:0
#19 0x00007ff737d94987 clang::ASTFrontendAction::ExecuteAction(void) C:\Users\cbieneman\dev\llvm-project\clang\lib\Frontend\FrontendAction.cpp:1193:0
#20 0x00007ff738035a7a clang::CodeGenAction::ExecuteAction(void) C:\Users\cbieneman\dev\llvm-project\clang\lib\CodeGen\CodeGenAction.cpp:1140:0
#21 0x00007ff737d9434d clang::FrontendAction::Execute(void) C:\Users\cbieneman\dev\llvm-project\clang\lib\Frontend\FrontendAction.cpp:1081:0
#22 0x00007ff735fff094 clang::CompilerInstance::ExecuteAction(class clang::FrontendAction &) C:\Users\cbieneman\dev\llvm-project\clang\lib\Frontend\CompilerInstance.cpp:1065:0
#23 0x00007ff73611c5ab clang::ExecuteCompilerInvocation(class clang::CompilerInstance *) C:\Users\cbieneman\dev\llvm-project\clang\lib\FrontendTool\ExecuteCompilerInvocation.cpp:296:0
#24 0x00007ff735510fd1 cc1_main(class llvm::ArrayRef<char const *>, char const *, void *) C:\Users\cbieneman\dev\llvm-project\clang\tools\driver\cc1_main.cpp:285:0
#25 0x00007ff7355027db ExecuteCC1Tool C:\Users\cbieneman\dev\llvm-project\clang\tools\driver\driver.cpp:218:0
#26 0x00007ff7355014db clang_main(int, char **, struct llvm::ToolContext const &) C:\Users\cbieneman\dev\llvm-project\clang\tools\driver\driver.cpp:259:0
#27 0x00007ff735538f92 main C:\Users\cbieneman\dev\llvm-project\llvm\out\build\x64-Clang-Debug\tools\clang\tools\driver\clang-driver.cpp:17:0
#28 0x00007ff73f0def79 invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79:0
#29 0x00007ff73f0df0b2 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#30 0x00007ff73f0df13e __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331:0
#31 0x00007ff73f0df15e mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17:0
#32 0x00007ffb446bdbe7 (C:\WINDOWS\System32\KERNEL32.DLL+0x2dbe7)
#33 0x00007ffb4515fbec (C:\WINDOWS\SYSTEM32\ntdll.dll+0xdfbec)
```

### PR DESCRIPTION
**Pull request by farzonl**
Two bugs here. First  calling `Inst->getFunction()`  has undefined behavior if the instruction is not tracked to a function. I suspect the `replaceAllUsesWith` was leaving the GEPs in a weird ghost parent situation. I switched up the visitor to be able to `eraseFromParent` as part of visiting and then everything started working.

The second bug was in `DXILFlattenArrays.cpp`. I was unaware that you can have multidimensional arrays of `zeroinitializer`, and `undef` so fixed up the initializer to handle these two cases.

fixes #117273

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 1]
```diff
@@ -321,6 +321,18 @@ static void collectElements(Constant *Init,
     Elements.push_back(Init);
     return;
   }
+  auto *LLVMArrayType = dyn_cast<ArrayType>(Init->getType());
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:324]: This should either be `cast<ArrayType>` (since the cast can't fail) or we should do the `dyn_cast` and check for null above instead of `isa`.

This is also kind of a weird name - I think `ArrayTy` is the usual abbreviation.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 2]
```diff
@@ -321,6 +321,18 @@ static void collectElements(Constant *Init,
...
+  if (isa<ConstantAggregateZero>(Init)) {
+    for (unsigned I = 0; I < LLVMArrayType->getNumElements(); ++I)
```
Comment (bogner) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:326]: It's best not to call a function in the condition of a for loop. It doesn't really matter much here since this happens to be a simple accessor, but it's good form to avoid it.
```suggestion
    for (unsigned I = 0, E = LLVMArrayType->getNumElements(); I != E; ++I)
```

Same comment a few lines below.

File: llvm/test/CodeGen/DirectX/flatten-bug-117273.ll [hunk 3]
```diff
@@ -0,0 +1,25 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -S -passes='dxil-flatten-arrays,dxil-op-lower' -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s
+
+
+@_ZL7Palette = internal constant [2 x [3 x float]] [[3 x float] zeroinitializer, [3 x float] undef], align 16
```
Comment (bogner) [inline llvm/test/CodeGen/DirectX/flatten-bug-117273.ll:5]: Might as well change these C++ mangled names to something a bit more human readable - they don't matter to the test.

**Review by bogner — APPROVED** [review]
Just a few style comments. LGTM.

File: llvm/lib/Target/DirectX/DXILDataScalarization.cpp [hunk 4]
```diff
@@ -106,6 +90,21 @@ bool DataScalarizerVisitor::visitLoadInst(LoadInst &LI) {
   unsigned NumOperands = LI.getNumOperands();
   for (unsigned I = 0; I < NumOperands; ++I) {
     Value *CurrOpperand = LI.getOperand(I);
+    ConstantExpr *CE = dyn_cast<ConstantExpr>(CurrOpperand);
+    if (CE && CE->getOpcode() == Instruction::GetElementPtr) {
+      GetElementPtrInst *OldGEP =
+          cast<GetElementPtrInst>(CE->getAsInstruction());
+      OldGEP->insertBefore(&LI);
+      Value *NewGEP = createNewGetElementPtr(*OldGEP);
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILDataScalarization.cpp:98]: Few things going on here.  instead of calling `convertUsersOfConstantsToInstructions` we are going to do something simpler to split the GEP Operand into an instruction.

When you call `getAsInstruction()` off a ConstExpr it creates a new instruction. So that we don't lose track of it and so it gets parented we do `insertBefore`.

`createNewGetElementPtr` wasn't strictly necessary. We could have called `visitGetElementPtrInst` at the end and then we wouldn't need to do `OldGEP->eraseFromParent();` 

Infact calling `visitGetElementPtrInst` is how I'm doing it in `DXILFlattenArrays.cpp` because that pass has to deal with more complicated things to update the GEP chains. Only reason I decided to turn `visitGetElementPtrInst` into a helper is because of how straight forward it was to only operate on one instruction.  I don't have strong feelings on this approach so if you think of something better please let me know.

File: llvm/test/CodeGen/DirectX/llc-vector-load-scalarize.ll [hunk 5]
```diff
@@ -33,18 +32,13 @@ define <4 x i32> @load_array_vec_test() #0 {
 ; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr addrspace(3) [[TMP5]], align 4
 ; CHECK-NEXT:    [[TMP7:%.*]] = bitcast ptr addrspace(3) getelementptr (i32, ptr addrspace(3) @arrayofVecData.scalarized.1dim, i32 3) to ptr addrspace(3)
 ; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(3) [[TMP7]], align 4
-; CHECK-NEXT:    [[TMP9:%.*]] = bitcast ptr addrspace(3) @arrayofVecData.scalarized.1dim to ptr addrspace(3)
-; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr [2 x [3 x float]], ptr addrspace(3) [[TMP9]], i32 0, i32 1
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/llc-vector-load-scalarize.ll:37]: This is one of the bugs from `convertUsersOfConstantsToInstructions`. It would split the bitcast from the GEP, but then we would never visit the GEP and so the GEP type never got flattened.

File: llvm/test/CodeGen/DirectX/llc-vector-load-scalarize.ll [hunk 6]
```diff
@@ -87,7 +81,7 @@ define <4 x i32> @load_vec_test() #0 {
 define <4 x i32> @load_static_array_of_vec_test(i32 %index) #0 {
 ; CHECK-LABEL: define <4 x i32> @load_static_array_of_vec_test(
 ; CHECK-SAME: i32 [[INDEX:%.*]]) #[[ATTR0]] {
-; CHECK-NEXT:    [[DOTFLAT:%.*]] = getelementptr [12 x i32], ptr @staticArrayOfVecData.scalarized.1dim, i32 [[INDEX]]
+; CHECK-NEXT:    [[DOTFLAT:%.*]] = getelementptr inbounds [12 x i32], ptr @staticArrayOfVecData.scalarized.1dim, i32 [[INDEX]]
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/llc-vector-load-scalarize.ll:84]: our GEP builders were not preserving inbounds. Now we are.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 7]
```diff
@@ -317,10 +330,22 @@ bool DXILFlattenArraysVisitor::visit(Function &F) {
...
   }
+  unsigned ArrSize = ArrayTy->getNumElements();
+  if (isa<ConstantAggregateZero>(Init)) {
+    for (unsigned I = 0; I < ArrSize; ++I)
+      Elements.push_back(Constant::getNullValue(ArrayTy->getElementType()));
+    return;
+  }
+  if (isa<UndefValue>(Init)) {
+    for (unsigned I = 0; I < ArrSize; ++I)
+      Elements.push_back(UndefValue::get(ArrayTy->getElementType()));
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:346]: Note to myself, we need to figure out what to do with undef for DXIL now that is deprecated.

File: llvm/test/CodeGen/DirectX/flatten-bug-117273.ll [hunk 8]
```diff
@@ -0,0 +1,23 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
+; RUN: opt -S -passes='dxil-flatten-arrays,dxil-op-lower' -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s
+
+
+@ZerroInitAndUndefArr = internal constant [2 x [3 x float]] [[3 x float] zeroinitializer, [3 x float] undef], align 16
```
Comment (llvm-beanz) [inline llvm/test/CodeGen/DirectX/flatten-bug-117273.ll:5]: The test case in #117273 doesn't have anything that should be producing an undef array, and I'm not sure it should be possible to create an undef array in HLSL. Do you know where this is coming from?

Comment (farzonl) [reply llvm/test/CodeGen/DirectX/flatten-bug-117273.ll:5]: It wasn't your exact example I just was playing around with how to change the values in  the array after I saw float3(0,0,0) became `zeroinitializer `. I then noticed that if I created an uninitialized array and passed it to the Pallette array I could get an undef array.
 example with fcgl: https://hlsl.godbolt.org/z/oPxxoKf9f
example without: https://hlsl.godbolt.org/z/rr1TocKnj

**Review by llvm-beanz — APPROVED** [review]

**Review by bogner — APPROVED** [review]
