### PR TITLE
[analyzer] Fix false positive for mutexes inheriting mutex_base

### LINKED ISSUE #104241: [clang][analyzer] Possible false positive from unix.BlockInCriticalSection
Clang-tidy generates a false positive for the `unix.BlockInCriticalSection` check when a thread that enters a critical section performs a  `recv()` with a non-blocking socket. This is because clang-tidy assumes `fcntl` (system call to set the socket to be non-blocking) to always fail.

Example: https://github.com/dmlc/xgboost/blob/0def8e0bae41e0eeeb4ee078e6e699ad6bef1986/src/collective/loop.cc#L88-L105

<details>
  <summary>Error message</summary>

```
/workspace/include/xgboost/collective/socket.h:696:12: warning: Call to blocking function 'recv' inside of critical section [clang-analyzer-unix.BlockInCriticalSection]
  696 |     return recv(handle_, _buf, len, flags);
      |            ^
/workspace/src/collective/loop.cc:272:5: note: Calling 'Loop::Process'
  272 |     this->Process();
      |     ^~~~~~~~~~~~~~~
/workspace/src/collective/loop.cc:154:3: note: Loop condition is true.  Entering loop body
  154 |   while (true) {
      |   ^
/workspace/src/collective/loop.cc:156:24: note: Calling constructor for 'unique_lock<std::mutex>'
  156 |       std::unique_lock lock{mu_};
      |                        ^~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_lock.h:69:2: note: Entering critical section here
   69 |         lock();
      |         ^~~~~~
/workspace/src/collective/loop.cc:156:24: note: Returning from constructor for 'unique_lock<std::mutex>'
  156 |       std::unique_lock lock{mu_};
      |                        ^~~~~~~~~
/workspace/src/collective/loop.cc:167:11: note: Assuming field 'stop_' is false
  167 |       if (stop_) {
      |           ^~~~~
/workspace/src/collective/loop.cc:167:7: note: Taking false branch
  167 |       if (stop_) {
      |       ^
/workspace/src/collective/loop.cc:174:14: note: Assuming the condition is false
  174 |       while (!queue_.empty()) {
      |              ^~~~~~~~~~~~~~~
/workspace/src/collective/loop.cc:174:7: note: Loop condition is false. Execution continues on line 179
  174 |       while (!queue_.empty()) {
      |       ^
/workspace/src/collective/loop.cc:182:17: note: Calling 'Loop::ProcessQueue'
  182 |       auto rc = this->ProcessQueue(&qcopy);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/workspace/src/collective/loop.cc:30:7: note: Assuming field 'stop_' is false
   30 |   if (stop_) {
      |       ^~~~~
/workspace/src/collective/loop.cc:30:3: note: Taking false branch
   30 |   if (stop_) {
      |   ^
/workspace/src/collective/loop.cc:38:10: note: Assuming the condition is true
   38 |   while (!qcopy.empty()) {
      |          ^~~~~~~~~~~~~~
/workspace/src/collective/loop.cc:38:3: note: Loop condition is true.  Entering loop body
   38 |   while (!qcopy.empty()) {
      |   ^
/workspace/src/collective/loop.cc:43:29: note: Assuming 'i' is < 'n_ops'
   43 |     for (std::size_t i = 0; i < n_ops; ++i) {
      |                             ^~~~~~~~~
/workspace/src/collective/loop.cc:43:5: note: Loop condition is true.  Entering loop body
   43 |     for (std::size_t i = 0; i < n_ops; ++i) {
      |     ^
/workspace/src/collective/loop.cc:47:7: note: Control jumps to 'case kSleep:'  at line 56
   47 |       switch (op.code) {
      |       ^
/workspace/src/collective/loop.cc:57:11: note:  Execution continues on line 65
   57 |           break;
      |           ^
/workspace/src/collective/loop.cc:43:29: note: Assuming 'i' is >= 'n_ops'
   43 |     for (std::size_t i = 0; i < n_ops; ++i) {
      |                             ^~~~~~~~~
/workspace/src/collective/loop.cc:43:5: note: Loop condition is false. Execution continues on line 69
   43 |     for (std::size_t i = 0; i < n_ops; ++i) {
      |     ^
/workspace/src/collective/loop.cc:70:9: note: Assuming the condition is false
   70 |     if (!poll.fds.empty()) {
      |         ^~~~~~~~~~~~~~~~~
/workspace/src/collective/loop.cc:70:5: note: Taking false branch
   70 |     if (!poll.fds.empty()) {
      |     ^
/workspace/src/collective/loop.cc:80:11: note: Assuming the condition is true
   80 |     CHECK(!qcopy.empty());
      |           ^
/workspace/include/xgboost/logging.h:144:24: note: expanded from macro 'CHECK'
  144 |   if (XGBOOST_EXPECT(!(cond), false))                   \
      |                        ^~~~
/workspace/include/xgboost/base.h:53:54: note: expanded from macro 'XGBOOST_EXPECT'
   53 | #define XGBOOST_EXPECT(cond, ret)  __builtin_expect((cond), (ret))
      |                                                      ^~~~
/workspace/src/collective/loop.cc:80:5: note: Taking false branch
   80 |     CHECK(!qcopy.empty());
      |     ^
/workspace/include/xgboost/logging.h:144:3: note: expanded from macro 'CHECK'
  144 |   if (XGBOOST_EXPECT(!(cond), false))                   \
      |   ^
/workspace/src/collective/loop.cc:83:5: note: Loop condition is true.  Entering loop body
   83 |     for (std::size_t i = 0; i < n_ops; ++i) {
      |     ^
/workspace/src/collective/loop.cc:88:11: note: Assuming field 'sock' is non-null
   88 |       if (!op.sock) {
      |           ^~~~~~~~
/workspace/src/collective/loop.cc:88:7: note: Taking false branch
   88 |       if (!op.sock) {
      |       ^
/workspace/src/collective/loop.cc:91:9: note: Assuming the condition is false
   91 |         CHECK(op.sock->NonBlocking());
      |         ^
/workspace/include/xgboost/logging.h:144:22: note: expanded from macro 'CHECK'
  144 |   if (XGBOOST_EXPECT(!(cond), false))                   \
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/workspace/include/xgboost/base.h:53:54: note: expanded from macro 'XGBOOST_EXPECT'
   53 | #define XGBOOST_EXPECT(cond, ret)  __builtin_expect((cond), (ret))
      |                                                      ^~~~
/workspace/src/collective/loop.cc:91:9: note: Taking false branch
   91 |         CHECK(op.sock->NonBlocking());
      |         ^
/workspace/include/xgboost/logging.h:144:3: note: expanded from macro 'CHECK'
  144 |   if (XGBOOST_EXPECT(!(cond), false))                   \
      |   ^
/workspace/src/collective/loop.cc:94:7: note: Control jumps to 'case kRead:'  at line 95
   94 |       switch (op.code) {
      |       ^
/workspace/src/collective/loop.cc:96:11: note: Taking true branch
   96 |           if (poll.CheckRead(*op.sock)) {
      |           ^
/workspace/src/collective/loop.cc:97:28: note: Calling 'TCPSocket::Recv'
   97 |             n_bytes_done = op.sock->Recv(op.ptr + op.off, op.n - op.off);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workspace/include/xgboost/collective/socket.h:696:12: note: Call to blocking function 'recv' inside of critical section
  696 |     return recv(handle_, _buf, len, flags);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 --------------------------------
```

</details>

Suggested fix: Add a note in the documentation about possible false positives with non-blocking sockets.

### PR DESCRIPTION
**Pull request by necto**
If a mutex interface is split in inheritance chain, e.g. struct mutex has `unlock` and inherits `lock` from __mutex_base then calls m.lock() and m.unlock() have different "this" targets: m and the __mutex_base of m, which used to confuse the `ActiveCritSections` list.

Taking base region canonicalizes the region used to identify a critical section and enables search in ActiveCritSections list regardless of which class the callee is the member of.

This possibly fixes #104241

CPP-5541

### CODE REVIEW

**Review by NagyDonat — APPROVED** [review]
LGTM, nice catch!

**Review by steakhal — CHANGES_REQUESTED** [review]
Uh that FN seems really bad. Have you measured this change?
Can we relax the canonicalization to only unwrap base class regions, or only apply to classes within the stdlib?

**Comment by necto** [comment]
> Uh that FN seems really bad. Have you measured this change? Can we relax the canonicalization to only unwrap base class regions, or only apply to classes within the stdlib?

relaxed in 744272e

**Comment by steakhal** [comment]
Could you also add this test case?
```c++
namespace std {
struct __mutex_base {
  void lock();
};
struct mutex : __mutex_base {
  void unlock();
  bool try_lock();
};
template <class... MutexTypes> struct scoped_lock {
  explicit scoped_lock(MutexTypes&... m);
  ~scoped_lock();
};
template <class MutexType> class scoped_lock<MutexType> {
public:
  explicit scoped_lock(MutexType& m) : m(m) { m.lock(); }
  ~scoped_lock() { m.unlock(); }
private:
  MutexType& m;
};
} // namespace std

extern "C" unsigned int sleep(unsigned int seconds);

int magic_number;
std::mutex m;

void fixed() {
  int current;
  for (int items_processed = 0; items_processed < 100; ++items_processed) {
    {
      std::scoped_lock guard(m);
      current = magic_number;
    }
    sleep(current); // expected no warning
  }
}
```
Or is it already implied by other tests?

**Comment by necto** [comment]
> Could you also add this test case?
> 
> ```c++
> ```
> 
> Or is it already implied by other tests?

My first test

``` C++
void no_false_positive_gh_104241() {
  std::mutex m;
  m.lock();
  // If inheritance not handled properly, this unlock might not match the lock
  // above because technically they act on different memory regions:
  // __mutex_base and mutex.
  m.unlock();
  sleep(10); // no-warning
}
```

Was derived from your example, so I guess it is implied, but I added your example as is with 0d95583 to make it extra clear.

**Review by steakhal — APPROVED** [review]
Thanks, I'm lovin it!

**Comment by necto** [comment]
@steakhal I added a fix for multiple-inheritance fn, please take another look

File: clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp [hunk 1]
```diff
@@ -241,10 +241,14 @@ BlockInCriticalSectionChecker::checkDescriptorMatch(const CallEvent &Call,
   return std::nullopt;
 }
 
-static const MemRegion *skipBaseClassRegion(const MemRegion *Reg) {
-  while (const auto *BaseClassRegion = dyn_cast<CXXBaseObjectRegion>(Reg)) {
+static const MemRegion *skipStdBaseClassRegion(const MemRegion *Reg) {
+  do {
+    assert(Reg);
+    const auto *BaseClassRegion = dyn_cast<CXXBaseObjectRegion>(Reg);
+    if (!BaseClassRegion || !BaseClassRegion->getDecl()->isInStdNamespace())
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp:247]: FYI `isInStdNamespace` only works if the decl is exactly within std. Any nested namespaces beyond std, or class scopes are rejected even if their parents reside within std.
Have a look at `CallEvent.cpp:isWithinStdNamespace()`. If you think it's what we should use here, we could hoist that function into some utility header and use it.

**Review by steakhal — APPROVED** [review]
Still looks good.

File: clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp (hunk 1 above)
Comment (NagyDonat) [reply clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp:247]: `<pedantery>`
> isInStdNamespace only works if the decl is exactly within std. Any nested namespaces beyond std, or class scopes are rejected even if their parents reside within std.
IIRC `isInStdNamespace` also accepts anonymous subnamespaces of `std` (so that kind of implementation detail won't cause problems at least).
`</pedantery>`

Comment (necto) [reply clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp]: fixed with e94327b

**Review by steakhal — APPROVED** [review]
Let's merge this.
