### PR TITLE
[lldb] Fix string truncation method when substring is the prefix of string (NFC)

### LINKED ISSUE #91211: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp:290: clumsy string resize ?
Static analyser cppcheck says:

lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp:290:19: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]

Source code is

    source_file = source_file.substr(0, pos);

### PR DESCRIPTION
**Pull request by xgupta**
Correct the method used to truncate the source_file string when substring is a prefix. The previous method used substr, which was changed to resize for clarity and efficiency.

Caught by cppcheck - 
lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp:290:19: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]

Source code - 
source_file = source_file.substr(0, pos);

Fix #91211

### CODE REVIEW

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp [hunk 1]
```diff
@@ -287,7 +287,7 @@ Status PlatformAndroid::DownloadModuleSlice(const FileSpec &src_file_spec,
   static constexpr llvm::StringLiteral k_zip_separator("!/");
   size_t pos = source_file.find(k_zip_separator);
   if (pos != std::string::npos)
-    source_file = source_file.substr(0, pos);
+    source_file = source_file.resize(0, pos);
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp:290]: According to https://en.cppreference.com/w/cpp/string/basic_string/resize, `resize(pos)` would be correct here. Otherwise we're resizing to 0 characters.

**Review by DavidSpickett — CHANGES_REQUESTED** [review]

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp (hunk 1 above)
Comment (clayborg) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp:290]: `std::string::resize()` returns `void` so this won't even compile. The right fix is:
```
source_file.resize(pos);
```

**Review by clayborg — CHANGES_REQUESTED** [review]

File: lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp (hunk 1 above)
Comment (bulbazord) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: This still isn't resolved, you're still doing `source_file = source_file.resize(pos)`. It doesn't return a value.

Comment (xgupta) [reply lldb/source/Plugins/Platform/Android/PlatformAndroid.cpp]: Thanks, got it.

**Review by bulbazord — APPROVED** [review]
