### PR TITLE
[RISCV][VLOPT] Allow users that are passthrus if tail elements aren't demanded

### LINKED ISSUE #123760: Handling tied operands in ternary pseudos in RISCVVLOptimizer
TL;DR: we can't express tail undefined with ternary pseudos

I've been exploring using RISCVVLOptimizer to reduce VL toggles with EVL tail folding. In some of the benchmarks we fail to reduce the AVL of a ternary instruction, causing a vl toggle e.g.:

```asm
        vsetvli a4, zero, e32, m2, ta, ma
        vsext.vf2       v14, v10
        vsetvli zero, a1, e32, m2, ta, ma
        vmadd.vv        v14, v12, v8
```

Although we're able to reduce the AVL of the vmadd.vv itself, we can't reduce the AVL of the vsext.vf2 because its user, vmadd.vv, is a tied operand:

```
Trying to reduce VL for early-clobber %43:vrm2 = PseudoVSEXT_VF2_M2 $noreg(tied-
def 0), killed %42:vr, -1, 5, 3

  Checking user: %49:vrm2 = nsw PseudoVMADD_VV_M2 %43:vrm2(tied-def 0), killed %
47:vrm2, %48:vrm2, %40:gprnox0, 5, 1

    Abort because user used as tied operand
```

We don't allow users that are passthrus because the tail elements past `vl` will depend on them.

```c++
std::optional<MachineOperand> RISCVVLOptimizer::checkUsers(MachineInstr &MI) {
  for (auto &UserOp : MRI->use_operands(MI.getOperand(0).getReg())) {
    ...
    // Tied operands might pass through.
    if (UserOp.isTied()) {
      LLVM_DEBUG(dbgs() << "    Abort because user used as tied operand\n");
      return std::nullopt;
    }
```

At first glance we might think that we can relax this restriction if the user's policy is ta/ma. However I don't think this is correct because tail agnostic/mask agnostic != tail undefined/mask undefined, so we still need to preserve the passthru to get "previous or -1" for each element.

I think the problem comes down to how for binary pseudos we represent tail undefined/mask undefined by using NoRegister for the passthru.

For ternary pseudos the third operand is simultaneously also the passthru, so it's not possible to represent a tail undefined/mask undefined pseudo with a non-undefined third operand.

This means that we lose the information that the inactive elements are undefined during instruction selection. One possible solution could be to add new _INACTIVE_UNDEF pseudos with a TSFlag that marks this fact, and use these for regular SDNode patterns. Then RISCVVLOptimizer (and RISCVInsertVSETVLI) could pick up the TSFlag and allow it as a user.

### PR DESCRIPTION
**Pull request by lukel97**
The motivation for this to allow reducing the vl when a user is a ternary pseudo, where the third operand is tied and also acts as a passthru.

When checking the users of an instruction, we currently bail if the user is used as a passthru because all of its elements past vl will be used for the tail.

We can allow passthru users if we know the tail of their result isn't used, which we will have computed beforehand after #124530 

It's worth noting that this is all irrelevant of the tail policy, because tail agnostic still ends up using the passthru.

I've checked that SPEC CPU 2017 + llvm-test-suite pass with this (on qemu with rvv_ta_all_1s=true)

Fixes #123760

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp [hunk 1]
```diff
@@ -53,7 +53,7 @@ class RISCVVLOptimizer : public MachineFunctionPass {
   std::optional<MachineOperand> getMinimumVLForUser(MachineOperand &UserOp);
   /// Returns the largest common VL MachineOperand that may be used to optimize
   /// MI. Returns std::nullopt if it failed to find a suitable VL.
-  std::optional<MachineOperand> checkUsers(MachineInstr &MI);
+  std::optional<MachineOperand> checkUsers(const MachineInstr &MI);
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp:56]: Needed to tweak the signature here since UserMI is const

File: llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp [hunk 2]
```diff
@@ -1235,16 +1236,21 @@ std::optional<MachineOperand> RISCVVLOptimizer::checkUsers(MachineInstr &MI) {
...
-      return std::nullopt;
-    }
-
     auto VLOp = getMinimumVLForUser(UserOp);
     if (!VLOp)
       return std::nullopt;
 
+    // If the user is a passthru, we will need to preserve it if its tail is
+    // demanded.
+    if (UserOp.isTied()) {
```
Comment (michaelmaitland) [inline llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp:1245]: Is it possible for UserOp to be a non-passthru tied def? If so, do we need to check `RISCVII::isFirstDefTiedToFirstUse(UserOp.getParent().getDesc());`?

Comment (lukel97) [reply llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp:1245]: Not that I'm aware of, but I'll add an assert that. i.e. that if an op is tied, it's the first operand and it's tied to the def.

**Review by michaelmaitland — APPROVED** [review]
LGTM. Nice find!

**Comment by michaelmaitland** [comment]
Do we get any impact if we remove `MI.getNumDefs() != 1` in is candidate? Not sure if that would be related here.

**Review by preames — CHANGES_REQUESTED** [review]
Hold on, this is now an unbounded recursion.  This can cause both stack explosion, and more likely, significant compile time regressions.  

I think you can achieve the same thing by adding a transform which uses the result of checkUsers to clear a pass thru to NoRegister.  (That is, convert an instruction from TA/TU to tail undefined.)  When we visit that instruction, it would propagate up.

**Comment by lukel97** [comment]
> Hold on, this is now an unbounded recursion. This can cause both stack explosion, and more likely, significant compile time regressions.

Yeah agreed the recursion is less than ideal, but it's only unbounded by the number of passthrus that are fed into passthrus, which doesn't seem to be common in practice.

> I think you can achieve the same thing by adding a transform which uses the result of checkUsers to clear a pass thru to NoRegister. (That is, convert an instruction from TA/TU to tail undefined.) When we visit that instruction, it would propagate up.

Unfortunately there's no way to represent a tail undefined ternary pseudo, because the passthru is also the third operand. I wrote a bit more of a description of this in #123760. 

I tried adding new `_INACTIVE_UNDEF` pseudos which propagate this information, but the duplication ended up causing a bunch of pain in other places, e.g. we need to handle new opcodes for commuting. 

Given that we're checking the demanded VL of the users downwards, and we iterate upwards over each block, it might be possible to memoize the result of checkUsers? We would need to invalidate it whenever we reduce a VL though. I'll have a think about this tonight anyway to see if there's another approach.

**Comment by lukel97** [comment]
> Do we get any impact if we remove `MI.getNumDefs() != 1` in is candidate? Not sure if that would be related here.

Off the top of my head, vsadd etc. have extra implicit defs, but I'm not sure if it's safe to change their VL. Fault-first loads have an extra explicit def, but I don't think they're safe to reduce either

**Comment by michaelmaitland** [comment]
> > Do we get any impact if we remove `MI.getNumDefs() != 1` in is candidate? Not sure if that would be related here.
> 
> Off the top of my head, vsadd etc. have extra implicit defs, but I'm not sure if it's safe to change their VL. Fault-first loads have an extra explicit def, but I don't think they're safe to reduce either

> Fault-first loads have an extra explicit def, but I don't think they're safe to reduce either

I had played around with a patch in the past that changed this line to `MI.getNumExplicitDefs() != 1` to avoid the fault-first loads. `vsadd` and others who mess with vxsat are not part of `isSupportedInstr`. I think we could probably remove this line. It was placed here to guard against passthru. I think this would give you more optimization.

**Comment by lukel97** [comment]
> Given that we're checking the demanded VL of the users downwards, and we iterate upwards over each block, it might be possible to memoize the result of checkUsers? We would need to invalidate it whenever we reduce a VL though. I'll have a think about this tonight anyway to see if there's another approach.

The solution I ended up with is in #124530. It turns out we don't need to invalidate anything because the demanded VL never changes: We can compute the minimum possible VL for each instruction up front without needing to mutate anything.

I'll rebase this PR on top of it once it's landed, as well as #124549 which was split off to help explain some diffs.

**Comment by lukel97** [comment]
I've rebased this on top of #124530, so now there's no recursion

File: llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp [hunk 3]
```diff
@@ -1188,6 +1188,25 @@ RISCVVLOptimizer::getMinimumVLForUser(MachineOperand &UserOp) {
...
+  assert((!VLOp.isReg() || VLOp.getReg() != RISCV::X0) &&
+         "Did not expect X0 VL");
+
+  // If the user is a passthru it will read the elements past VL, so
+  // abort if any of the elements past VL are demanded.
+  if (UserOp.isTied()) {
+    assert(UserOp.getOperandNo() == UserMI.getNumExplicitDefs() &&
+           RISCVII::isFirstDefTiedToFirstUse(UserMI.getDesc()));
+    auto DemandedVL = DemandedVLs[&UserMI];
+    if (!DemandedVL || !RISCV::isVLKnownLE(*DemandedVL, VLOp)) {
```
Comment (michaelmaitland) [inline llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp:1203]: Just want to confirm here: if !DemandedVL, then that means that the DemandedVL is really "VLMAX", not "VL is not demanded"?

Comment (lukel97) [reply llvm/lib/Target/RISCV/RISCVVLOptimizer.cpp:1203]: Yeah, it should be read as "we couldn't compute the demanded VL for UserMI", so assume it's VLMAX.

**Review by preames — APPROVED** [review]
LGTM

Only point I'm still a bit hesitant on is if we have some instruction with "weird" passthru usage (i.e. read after VL, etc..).  I can't think of any, and spot checking existing code doesn't seem to reveal in any special casing, so I think we're okay here.  Both passthru for TU/MU and FMA style extra sources should be fine with the code as written. 

I guess one other point is that I'm surprised this has so little impact on the tests.  Apparently we really don't use anything other than tail undef in practice do we?

**Comment by lukel97** [comment]
> Only point I'm still a bit hesitant on is if we have some instruction with "weird" passthru usage (i.e. read after VL, etc..).

vslidedowns and vrgathers can read past VL, but we guard against them already via `mayReadPastVL`. 

> Apparently we really don't use anything other than tail undef in practice do we?

It shows up in a lot more places if we stop emitting non-trapping VP intrinsics with EVL tail folding.

We also probably never see tail undef ternary pseudos, because that would mean one of the operands would have to be undef too.
