### PR TITLE
[mlir][OpenMP] implement SIMD reduction

### LINKED ISSUE #144290: [flang][openmp] Please address not yet implemented: Unhandled clause reduction in omp.simd operation
A widely-used close-source app uses OpenMP SIMD reductions.  It would be great if this feature was implemented.  Thanks!

```
module foo
  implicit none

contains
  subroutine bar(arr,n_elem)
    integer i
    integer n_elem
    double precision arr(:),resul

    resul=0d0
 !$OMP SIMD REDUCTION(+:resul)
    do i=1,n_elem
       resul=resul+arr(i)*i
    enddo

  end subroutine bar
end module foo
```
```
% flang -fopenmp -c foo.f90
flang-21: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: loc(".../foo.f90":11:8): not yet implemented: Unhandled clause reduction in omp.simd operation
error: loc(".../foo.f90":11:8): LLVM Translation failed for operation: omp.simd
error: failed to create the LLVM module
```

### PR DESCRIPTION
**Pull request by tblah**
This replicates clang's implementation. Basically:
  - A private copy of the reduction variable is created, initialized to the reduction neutral value (using regions from the reduction declaration op).
  - The body of the loop is lowered as usual, with accesses to the reduction variable mapped to the private copy.
  - After the loop, we inline the reduction region from the declaration op to combine the privatized variable into the original variable.
  - As usual with the SIMD construct, attributes are added to encourage vectorization of the loop and to assert that memory accesses in the loop don't alias across iterations.

I have verified that simple scalar examples do vectorize at -O3 and the tests I could find in the Fujitsu test suite produce correct results. I tested on top of #146097 and this seemed to work for composite constructs as well.

Fixes #144290

### CODE REVIEW

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 1]
```diff
@@ -2872,11 +2883,27 @@ convertOmpSimd(Operation &opInst, llvm::IRBuilderBase &builder,
...
+                                privateReductionVariables, reductionVariableMap,
+                                deferredStores, isByRef)))
+    return failure();
+
   if (handleError(initPrivateVars(builder, moduleTranslation, privateVarsInfo),
                   opInst)
           .failed())
     return failure();
 
+  // TODO: no call to copyFirstPrivateVars?
```
Comment (skatrak) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:2897]: That seems to be missing indeed. I'm guessing `firstprivate` probably doesn't currently work for `simd`, then.

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 2]
```diff
@@ -2921,6 +2948,50 @@ convertOmpSimd(Operation &opInst, llvm::IRBuilderBase &builder,
...
+           llvm::zip(reductionDecls, isByRef, simdOp.getReductionVars(),
+                     privateReductionVariables))) {
+    auto [decl, byRef, reductionVar, privateReductionVar] = tuple;
+
+    OwningReductionGen gen = makeReductionGen(decl, builder, moduleTranslation);
+    llvm::Value *originalVariable = moduleTranslation.lookupValue(reductionVar);
+    llvm::Type *reductionType = moduleTranslation.convertType(decl.getType());
+
+    // We have one less load for by-ref case because that load is now inside of
+    // the reduction region
```
Comment (skatrak) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]:
```suggestion
    // the reduction region.
```

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 3]
```diff
@@ -2921,6 +2948,50 @@ convertOmpSimd(Operation &opInst, llvm::IRBuilderBase &builder,
...
+    llvm::Value *privateRedValue = builder.CreateLoad(
+        reductionType, privateReductionVar, "red.private.value." + Twine(i));
+    llvm::Value *reduced;
+
+    auto res = gen(builder.saveIP(), redValue, privateRedValue, reduced);
+    if (failed(handleError(res, opInst)))
+      return failure();
+    builder.restoreIP(res.get());
+
+    // for by-ref case, the store is inside of the reduction region
```
Comment (skatrak) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]:
```suggestion
    // For by-ref case, the store is inside of the reduction region.
```

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 4]
```diff
@@ -2921,6 +2948,50 @@ convertOmpSimd(Operation &opInst, llvm::IRBuilderBase &builder,
...
+    if (!byRef)
+      builder.CreateStore(reduced, originalVariable);
+  }
+
+  // After the construct, deallocate private reduction variables
```
Comment (skatrak) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]:
```suggestion
  // After the construct, deallocate private reduction variables.
```

File: mlir/test/Target/LLVMIR/openmp-simd-reduction-byref.mlir [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+    omp.loop_nest (%arg4) : i32 = (%1) to (%0) inclusive step (%1) {
+      llvm.store %arg4, %arg2 : i32, !llvm.ptr
+      omp.yield
+    }
+  }
+  llvm.return
+}
+
+// CHECK-LABEL: define void @_QPsimd_reduction
+// CHECK:         %[[VAL_0:.*]] = alloca { ptr, i64, i32, i8, i8, i8, i8, [1 x [3 x i64]] }, i64 1, align 8
```
Comment (ergawy) [inline mlir/test/Target/LLVMIR/openmp-simd-reduction-byref.mlir]: Can you use variable names that clarify the meaning of important ones? Like the reduction variable, private reduction variable, and such.

**Review by ergawy — APPROVED** [review]
LGTM, thanks Tom. Just a small comment.

**Review by skatrak — APPROVED** [review]
Thank you Tom, LGTM.

**Review by NimishMishra — APPROVED** [review]
LGTM. Thanks

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp (hunk 1 above)
Comment (tblah) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:2897]: I'll fix it

Comment (tblah) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:2897]: Ahh it turns out firstprivate isn't listed as an allowed clause for simd. I will update the comment.

Comment (tblah) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:2897]: The dialect does allow it so I have done this in a separate PR which I will post after this is merged. Edit: https://github.com/llvm/llvm-project/pull/146734
