### PR TITLE
[InstCombine] Fix crash when alloc functions are missing `alloc-family`

### LINKED ISSUE #63477: Crash when instcombine tries to optimize away allocation
```console
$ cat /tmp/d.ll
define i32 @f() {
bb:
  %alloc = tail call align 4 dereferenceable_or_null(64) ptr @__rust_alloc(i64 64, i64 4)
  tail call void @__rust_dealloc(ptr %alloc, i64 64, i64 4)
  ret i32 6
}

; Function Attrs: nounwind nonlazybind allockind("alloc,uninitialized,aligned") allocsize(0) uwtable
declare noalias noundef ptr @__rust_alloc(i64 noundef, i64 allocalign noundef) local_unnamed_addr #0

; Function Attrs: nounwind nonlazybind allockind("free") uwtable
declare void @__rust_dealloc(ptr allocptr noundef, i64 noundef, i64 noundef) local_unnamed_addr #1

attributes #0 = { nounwind nonlazybind allockind("alloc,uninitialized,aligned") allocsize(0) uwtable }
attributes #1 = { nounwind nonlazybind allockind("free") uwtable }

$ opt -p instcombine /tmp/d.ll -disable-output
opt: ../../llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:2336: bool isAllocSiteRemovable(Instruction *, SmallVectorImpl<WeakTrackingVH> &, const TargetLibraryInfo &): Assertion `Family' failed.
```

@durin42

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #63477 by bailing out instead of crashing

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstructionCombining.cpp [hunk 1]
```diff
@@ -3302,14 +3302,16 @@ static bool isAllocSiteRemovable(Instruction *AI,
 
         if (getFreedOperand(cast<CallBase>(I), &TLI) == PI &&
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3303]: I'd prefer to add a `Family &&` here. No need to do the other checks if we don't have an allocation family in the first place.

**Review by nikic — APPROVED** [review]
LGTM
