### PR TITLE
[mlir][nvgpu] Fix a division by zero crash in OptimizeSharedMemoryPass

### LINKED ISSUE #173553: mlir-opt crashes in mlir::nvgpu::optimizeSharedMemoryReadsAndWrites
When running opt on the following IR, mlir-opt crashes. 

version 2c02e4c7909a

test.mlir

```
module {
  pdl_interp.func @matcher(%arg0: !pdl.operation) {
    pdl_interp.finalize
  }
  module @rewriters {
  }
  func.func @memref_size0_rhs_index0() {
    %alloc = memref.alloc() : memref<0xf32, 3>
    %alloc_0 = memref.alloc() : memref<0xf32, 0>
    %alloc_1 = memref.alloc() : memref<0xf32, 0>
    return
  }
}
```

commads:

mlir-opt -nvgpu-optimize-shared-memory test.mlir

stacktrace

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: ./build/bin/mlir-opt -nvgpu-optimize-shared-memory test.mlir
 #0 0x000055acf6598358 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./build/bin/mlir-opt+0x1e97358)
 #1 0x000055acf6595a15 llvm::sys::RunSignalHandlers() (./build/bin/mlir-opt+0x1e94a15)
 #2 0x000055acf6599396 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007f2431f9e420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x000055acf87c86cf mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(mlir::Operation*, mlir::Value) (./build/bin/mlir-opt+0x40c76cf)
 #5 0x000055acf87ca637 (anonymous namespace)::OptimizeSharedMemoryPass::runOnOperation() OptimizeSharedMemory.cpp:0:0
 #6 0x000055acfec527be mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (./build/bin/mlir-opt+0xa5517be)
 #7 0x000055acfec53617 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (./build/bin/mlir-opt+0xa552617)
 #8 0x000055acfec5a9ca mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) (./build/bin/mlir-opt+0xa5599ca)
 #9 0x000055acfec5a01f mlir::PassManager::run(mlir::Operation*) (./build/bin/mlir-opt+0xa55901f)
#10 0x000055acf663c377 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#11 0x000055acf663b5a6 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#12 0x000055acfef6d855 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::MemoryBufferRef const&, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (./build/bin/mlir-opt+0xa86c855)
#13 0x000055acf6631166 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (./build/bin/mlir-opt+0x1f30166)
#14 0x000055acf66314a2 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (./build/bin/mlir-opt+0x1f304a2)
#15 0x000055acf6631805 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (./build/bin/mlir-opt+0x1f30805)
#16 0x000055acf657e9b3 main (./build/bin/mlir-opt+0x1e7d9b3)
#17 0x00007f24315d8083 __libc_start_main /build/glibc-B3wQXB/glibc-2.31/csu/../csu/libc-start.c:342:3
#18 0x000055acf657e4ee _start (./build/bin/mlir-opt+0x1e7d4ee)
```

### PR DESCRIPTION
**Pull request by CoTinker**
Fixes #173553.

### CODE REVIEW

**Comment by CoTinker** [comment]
Ping~

File: mlir/lib/Dialect/NVGPU/Transforms/OptimizeSharedMemory.cpp [hunk 1]
```diff
@@ -166,6 +166,9 @@ mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(Operation *parentOp,
   // Check if this is necessary given the assumption of 128b accesses:
   // If dim[rank-1] is small enough to fit 8 rows in a 128B line.
   const int64_t rowSize = memRefType.getDimSize(memRefType.getRank() - 1);
+  if (rowSize == ShapedType::kDynamic || rowSize == 0)
```
Comment (kuhar) [inline mlir/lib/Dialect/NVGPU/Transforms/OptimizeSharedMemory.cpp]: nit: use `ShapedType::isDynamic(rowSize)`

**Review by kuhar — APPROVED** [review]
