### PR TITLE
[flang-rt] Fix REAL(10)/COMPLEX(10) component sizes in runtime type info

### LINKED ISSUE #192085: [flang-rt] Incorrect REAL(10)/COMPLEX(10) component sizes in runtime type info can corrupt derived-type assignment
On x86-64, `Component::GetElementByteSize()` in `flang-rt/lib/runtime/type-info.cpp` uses the Fortran kind value for `REAL(10)` / `COMPLEX(10)` instead of the actual storage size. This causes the runtime's componentwise derived-type assignment path to copy too few bytes and corrupt data.

This was originally noticed in a non-public external test, and the same underlying bug can be reproduced with the standalone example below.

## Standalone reproducer

```fortran
program real10_bug
  implicit none
  type :: seq_t
    sequence
    real(kind=10) :: arr(3)
    integer       :: tag
  end type
  type(seq_t) :: a(4), b(4)
  integer :: i

  do i = 1, 4
    a(i)%arr(1) = real(i * 100, kind=10)
    a(i)%arr(2) = real(i * 200, kind=10)
    a(i)%arr(3) = real(i * 300, kind=10)
    a(i)%tag = i
    b(i)%arr(:) = 0.0_10
    b(i)%tag = 0
  end do

  ! Strided section assignment forces runtime componentwise copy
  b(1:3:2) = a(2:4:2)

  if (b(1)%arr(3) /= 600.0_10) then
    print *, "FAIL: b(1)%arr(3) =", b(1)%arr(3), " expected 600"
    stop 1
  end if
  if (b(3)%arr(3) /= 1200.0_10) then
    print *, "FAIL: b(3)%arr(3) =", b(3)%arr(3), " expected 1200"
    stop 1
  end if
  if (b(1)%tag /= 2 .or. b(3)%tag /= 4) then
    print *, "FAIL: tag mismatch"
    stop 1
  end if

  print *, "PASS"
end program
```

## Observed behavior

**Unfixed build:**
```
FAIL: b(1)%arr(3) = 0.  expected 600
STOP 1
```

**Fixed build:**
```
PASS
```

## Stack trace

With a breakpoint on `Component::SizeInBytes()` while running the standalone reproducer:

```
#0  Fortran::runtime::typeInfo::Component::SizeInBytes at type-info.cpp:84
#1  Fortran::runtime::DerivedAssignTicket<true>::Continue at assign.cpp:620
#2  Fortran::runtime::WorkQueue::ContinueItem at work-queue.cpp:90
#3  Fortran::runtime::WorkQueue::Run at work-queue.cpp:50
#4  Fortran::runtime::AssignTicket::Continue at assign.cpp:474
#5  Fortran::runtime::WorkQueue::ContinueItem at work-queue.cpp:90
#6  Fortran::runtime::WorkQueue::Run at work-queue.cpp:50
#7  Fortran::runtime::Assign at assign.cpp:272
#8  _FortranAAssign at assign.cpp:793
#9  _QQmain at reproducer.f90:29
```

`SizeInBytes()` returns 30 for `real(kind=10) :: arr(3)`, but the correct size on x86-64 is 48.

## Root cause

`GetElementByteSize()` currently does this:

```cpp
case TypeCategory::Real:
  return kind_;
case TypeCategory::Complex:
  return 2 * kind_;
```

For kind 10 on x86-64, that is smaller than the actual storage size.

## Proposed fix

PR #192049 updates `GetElementByteSize()` to use `Descriptor::BytesFor(category(), kind_)` for Real and Complex.

### PR DESCRIPTION
**Pull request by Saieiei**
This fixes a crash caused by incorrect component sizes in runtime type info.

For REAL(10) and COMPLEX(10) components, `Component::GetElementByteSize()` was using the Fortran kind value as the byte size. On x86-64 that underestimates the actual storage size, so component size computation can be wrong for extended-precision types.

This patch routes REAL and COMPLEX component sizes through `Descriptor::BytesFor()`, which matches the runtime’s existing storage-size handling. I also added a runtime unit test covering the relevant `Descriptor::BytesFor()` storage-size behavior for REAL and COMPLEX kinds, including kind 10.

Fixes #192085

### CODE REVIEW

**Review by tarunprabhu — CHANGES_REQUESTED** [review]
Tests that build and run executables should not be added to the core tests in flang. Please find another way to test your changes. If the only way to do this is with an executable test, it should be added to the llvm-test-suite. See, for instance, [this](https://github.com/llvm/llvm-test-suite/pull/361)

**Comment by tarunprabhu** [comment]
Thanks for changing the test. I have requested reviews from @eugeneepshteyn and @jeanPerier who are probably more familiar than I am with the runtime. It doesn't seem as if I can clear my "change requested" block without approving this, so I'll do that after they - or someone else - has had a look.

**Comment by Saieiei** [comment]
> Thanks for changing the test. I have requested reviews from @eugeneepshteyn and @jeanPerier who are probably more familiar than I am with the runtime. It doesn't seem as if I can clear my "change requested" block without approving this, so I'll do that after they - or someone else - has had a look.

Thanks for the review!

**Comment by eugeneepshteyn** [comment]
@Saieiei , could you please provide an example of the crash? In fact, could you please file a proper github issue with the reproducer and the stack trace? Mention your PR in the description and assign the issue to yourself. On the surface, the fix seems reasonable, but the failing mode would provide more context.

Ideally, all such crashes should start as github issues, so that (1) we can investigate and (2) we have a searchable record of issues that were fixed.

File: flang-rt/unittests/Runtime/Descriptor.cpp [hunk 1]
```diff
@@ -280,3 +280,31 @@ TEST(Descriptor, Dump) {
...
+// for Real and Complex types, especially for kind=10 where the x87
+// 80-bit extended precision value is stored in a 16-byte container.
+TEST(Descriptor, BytesForRealAndComplex) {
+  using TC = TypeCategory;
+  // Real kinds: storage size should account for container padding
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 2), 2u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 3), 2u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 4), 4u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 8), 8u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 10),
```
Comment (eugeneepshteyn) [inline flang-rt/unittests/Runtime/Descriptor.cpp]: Kind 10 check should probably be conditioned to only execute on x86.

File: flang-rt/unittests/Runtime/Descriptor.cpp [hunk 2]
```diff
@@ -280,3 +280,31 @@ TEST(Descriptor, Dump) {
   fclose(tmpf);
 }
 #endif // defined(__linux__) && !defined(__ANDROID__)
+
+// Verify that Descriptor::BytesFor returns the correct storage size
+// for Real and Complex types, especially for kind=10 where the x87
+// 80-bit extended precision value is stored in a 16-byte container.
+TEST(Descriptor, BytesForRealAndComplex) {
```
Comment (eugeneepshteyn) [inline flang-rt/unittests/Runtime/Descriptor.cpp:287]: This is a good test, but shouldn't we also test something that calls `Component::GetElementByteSize()`, which was actually modified? :)

File: flang-rt/unittests/Runtime/Descriptor.cpp (hunk 1 above)
Comment (eugeneepshteyn) [reply flang-rt/unittests/Runtime/Descriptor.cpp]: (Note that flang-rt buildbots only run in post-commit, so if this test fails on ARM or some other platform, we may not know for a few days after PR is submitted.)

**Comment by Saieiei** [comment]
> @Saieiei , could you please provide an example of the crash? In fact, could you please file a proper github issue with the reproducer and the stack trace? Mention your PR in the description and assign the issue to yourself. On the surface, the fix seems reasonable, but the failing mode would provide more context.
> 
> Ideally, all such crashes should start as github issues, so that (1) we can investigate and (2) we have a searchable record of issues that were fixed.

Thanks, filed #192085. I wasn’t able to assign it to myself, likely due to repository permissions.

File: flang-rt/unittests/Runtime/Descriptor.cpp (hunk 2 above)
Comment (Saieiei) [reply flang-rt/unittests/Runtime/Descriptor.cpp:287]: Done, I added a direct `Component::GetElementByteSize()` test as well, in addition to the `Descriptor::BytesFor()` coverage.

File: flang-rt/unittests/Runtime/Descriptor.cpp (hunk 1 above)
Comment (Saieiei) [reply flang-rt/unittests/Runtime/Descriptor.cpp]: Done!

File: flang-rt/unittests/Runtime/Descriptor.cpp [hunk 3]
```diff
@@ -280,3 +282,128 @@ TEST(Descriptor, Dump) {
...
+// This is the function modified by the fix; it delegates to
+// Descriptor::BytesFor() for Real and Complex types.
+TEST(Descriptor, ComponentGetElementByteSize) {
+  using TC = TypeCategory;
+  using typeInfo::Component;
+  using typeInfo::Value;
+
+  // Component has all-private members and no setters.  Mirror its layout
+  // with public fields so we can populate category_ and kind_ for testing.
+  struct TestableComponent {
```
Comment (eugeneepshteyn) [inline flang-rt/unittests/Runtime/Descriptor.cpp]: Thank you for adding the test.

Could you please look into a way to create an actual descriptor with the right kind? Having this subset here feels very brittle: we change something in the real descriptor, we forget to modify it here, and then we'll have random buildbots fail for no apparent reason at random times on some platforms but not the others...

Comment (Saieiei) [reply flang-rt/unittests/Runtime/Descriptor.cpp]: Thanks for the suggestion. I removed that layout-based test and kept the safer `Descriptor::BytesFor()` coverage, with the kind-10 checks guarded to x86 only.

**Review by eugeneepshteyn — APPROVED** [review]
LGTM

**Comment by eugeneepshteyn** [comment]
@tarunprabhu , you could approve this now :)

File: flang-rt/unittests/Runtime/Descriptor.cpp [hunk 4]
```diff
@@ -280,3 +280,37 @@ TEST(Descriptor, Dump) {
...
+  using TC = TypeCategory;
+  // Real kinds: storage size should account for container padding
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 2), 2u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 3), 2u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 4), 4u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 8), 8u);
+#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || \
+    defined(_M_IX86)
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 10),
+      16u); // x87: 80-bit in 128-bit container
```
Comment (tarunprabhu) [inline flang-rt/unittests/Runtime/Descriptor.cpp]: nit: Could you use a leading comment here instead of a trailing comment. It would prevent the formatter from splitting the line awkwardly the way it seems to have done.

```suggestion
  // x87: 80-bit in 128-bit container
  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 10), 16u); 
```

File: flang-rt/unittests/Runtime/Descriptor.cpp [hunk 5]
```diff
@@ -280,3 +280,37 @@ TEST(Descriptor, Dump) {
...
+#endif
+  EXPECT_EQ(Descriptor::BytesFor(TC::Real, 16), 16u);
+  // Complex kinds: should be twice the Real storage size
+  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 2), 4u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 3), 4u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 4), 8u);
+  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 8), 16u);
+#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || \
+    defined(_M_IX86)
+  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 10), 32u); // x87: 2 * 16 bytes
```
Comment (tarunprabhu) [inline flang-rt/unittests/Runtime/Descriptor.cpp]: nit: Probably best to use leading comments here too for consistency

```suggestion
  // x87: 2 * 16 bytes
  EXPECT_EQ(Descriptor::BytesFor(TC::Complex, 10), 32u); 
```

**Review by tarunprabhu — COMMENTED** [review]
Since this fixes the related issue, please add a line indicating the issue being fixed as described  [here](https://llvm.org/docs/BugLifeCycle.html#resolving-closing-bugs).

File: flang-rt/unittests/Runtime/Descriptor.cpp (hunk 4 above)
Comment (Saieiei) [reply flang-rt/unittests/Runtime/Descriptor.cpp]: Done!

File: flang-rt/unittests/Runtime/Descriptor.cpp (hunk 5 above)
Comment (Saieiei) [reply flang-rt/unittests/Runtime/Descriptor.cpp]: Done!

**Comment by Saieiei** [comment]
> Since this fixes the related issue, please add a line indicating the issue being fixed as described [here](https://llvm.org/docs/BugLifeCycle.html#resolving-closing-bugs).

Done!

**Comment by eugeneepshteyn** [comment]
> > Since this fixes the related issue, please add a line indicating the issue being fixed as described [here](https://llvm.org/docs/BugLifeCycle.html#resolving-closing-bugs).
> 
> Done!

The PR description needs to have a separate line `Fixes #<issue number>`. This way the issue will be linked to the PR and will be automagically closed once PR is merged. (But not re-opened if PR is reverted, which is annoying.)

**Comment by Saieiei** [comment]
> > > Since this fixes the related issue, please add a line indicating the issue being fixed as described [here](https://llvm.org/docs/BugLifeCycle.html#resolving-closing-bugs).
> > 
> > 
> > Done!
> 
> The PR description needs to have a separate line `Fixes #<issue number>`. This way the issue will be linked to the PR and will be automagically closed once PR is merged. (But not re-opened if PR is reverted, which is annoying.)

Updated the PR description to include Fixes #192085 on a separate line.

**Review by tarunprabhu — APPROVED** [review]
Thanks for all the changes. LGTM.

**Review by jeanPerier — APPROVED** [review]
