### PR TITLE
[lld][MachO] Prevent doubled N_SO when comp_dir and name absolute

### LINKED ISSUE #70995: [LLD] `ld64.lld` adds doubled `N_SO` STABS entry when both `DW_AT_comp_dir` and `DW_AT_name` are absolute
While trying to run the LLDB test suite with a clang configuration on Darwin that uses `ld64.lld` instead of the system `ld`, I discovered that LLDB broadly fails to locate source files for the DWARF (but not dSYM) versions of its test.

The root cause ended up being that these tests had `N_SO` STABS entries of the form `%s/%s`, where the first `%s` is `DW_AT_comp_dir` and the second is `DW_AT_name`. In our case, both `DW_AT_comp_dir` and `DW_AT_name` were absolute paths, which made the resulting path invalid. LLDB uses this path without further correction, although strangely I did find iOS specific logic for this.

I ran the same command line against the Darwin system `ld` from XCode v13.2.1, and it produce correct `N_SO` entry for the path.
Accordingly, I've filed this against LLD, since it seems to be an important behavioral difference between it and the Darwin `ld` it's simulating.

### PR DESCRIPTION
**Pull request by mysterymath**
When forming MachO STABS, this change detects if the DW_AT_name of the compile unit is already absolute (as allowed by DWARF), and if so, does not prepend DW_AT_comp_dir.

Fixes #70995

### CODE REVIEW

File: lld/MachO/InputFiles.cpp [hunk 1]
```diff
@@ -1522,13 +1522,17 @@ void ObjFile::registerEhFrames(Section &ehFrameSection) {
 }
 
 std::string ObjFile::sourceFile() const {
+  const char *unitName = compileUnit->getUnitDIE().getShortName();
```
Comment (smeenai) [inline lld/MachO/InputFiles.cpp:1525]: I would have wondered why the logic was written this way if your commit hadn't mentioned that it was matching the check in libObject :) Could you add a code comment here pointing to that logic so that it's easy to understand why it's written this way?

File: lld/test/MachO/stabs-abs-path.s [hunk 2]
```diff
@@ -0,0 +1,58 @@
+# REQUIRES: x86
+# RUN: llvm-mc -filetype=obj -triple=x86_64-apple-darwin %s -o %t.o
+
+# RUN: %lld -lSystem %t.o -o %t
```
Comment (thevinster) [inline lld/test/MachO/stabs-abs-path.s:4]: `-lSystem` isn't needed here.

**Review by smeenai — APPROVED** [review]
LGTM, and thanks for fixing this! Will you need someone to commit this for you?

File: lld/test/MachO/stabs-abs-path.s [hunk 3]
```diff
@@ -0,0 +1,58 @@
+# REQUIRES: x86
```
Comment (thevinster) [inline lld/test/MachO/stabs-abs-path.s:1]: Is there a need to create a new test file for this use case? This seems like this could be placed in [`stabs.s`](https://github.com/llvm/llvm-project/blob/main/lld/test/MachO/stabs.s)

Comment (mysterymath) [reply lld/test/MachO/stabs-abs-path.s:1]: I was hesitant to try to add another file there given it's complexity, but I'll give it a stab.

**Comment by mysterymath** [comment]
> LGTM, and thanks for fixing this! Will you need someone to commit this for you?

Nah, I've got it. Thanks though! :)

File: lld/MachO/InputFiles.cpp (hunk 1 above)
Comment (mysterymath) [reply lld/MachO/InputFiles.cpp:1525]: Seems more robust just to use the same comment as there.

Comment (smeenai) [reply lld/MachO/InputFiles.cpp:1525]: Sure, works for me.

File: lld/test/MachO/stabs-abs-path.s (hunk 2 above)
Comment (mysterymath) [reply lld/test/MachO/stabs-abs-path.s:4]: Done.
