### PR TITLE
[LV] Check full partial reduction chains in order.

### LINKED ISSUE #167243: [LV] Assert "all accumulators in chain must have same scale factor"
This IR:

```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

define void @_Z1fv() #0 {
entry:
  br label %for.body

for.cond.loopexit.loopexit:                       ; preds = %for.body
  ret void

for.body:                                         ; preds = %for.body, %entry
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %add15.lcssa1921 = phi i32 [ 0, %entry ], [ %add.1, %for.body ]
  %conv8 = sext i16 0 to i32
  %add = add i32 %add15.lcssa1921, %conv8
  %conv8.1 = sext i16 0 to i32
  %add.1 = add i32 %add, %conv8.1
  store i32 %add.1, ptr null, align 4
  %indvars.iv.next = add i64 %indvars.iv, 1
  %0 = and i64 %indvars.iv.next, 255
  %exitcond.not = icmp eq i64 %0, 0
  br i1 %exitcond.not, label %for.cond.loopexit.loopexit, label %for.body
}

attributes #0 = { "target-cpu"="grace" }
```

Triggers this assert:

```
opt: /root/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8181: llvm::VPRecipeBase* llvm::VPRecipeBuilder::tryToCreatePartialReduction(llvm::VPInstruction*, unsigned int): Assertion `ScaleFactor == vputils::getVFScaleFactor(Accumulator->getDefiningRecipe()) && "all accumulators in chain must have same scale factor"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -S -passes=loop-vectorize <source>
1.	Running pass "function(loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>)" on module "<source>"
2.	Running pass "loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>" on function "_Z1fv"
 #0 0x00000000059ad0e8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x59ad0e8)
 #1 0x00000000059a9f94 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x00007efe89442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007efe894969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x00007efe89442476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x00007efe894287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x00007efe8942871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x00007efe89439e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x00000000036b2f1b llvm::VPRecipeBuilder::tryToCreatePartialReduction(llvm::VPInstruction*, unsigned int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36b2f1b)
 #9 0x00000000036b599f llvm::VPRecipeBuilder::tryToCreateWidenRecipe(llvm::VPSingleDefRecipe*, llvm::VFRange&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36b599f)
#10 0x00000000036d4e5e llvm::LoopVectorizationPlanner::tryToBuildVPlanWithVPRecipes(std::unique_ptr<llvm::VPlan, std::default_delete<llvm::VPlan>>, llvm::VFRange&, llvm::LoopVersioning*) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36d4e5e)
#11 0x00000000036d63a8 llvm::LoopVectorizationPlanner::buildVPlansWithVPRecipes(llvm::ElementCount, llvm::ElementCount) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36d63a8)
```

Compile with: `opt -S -passes=loop-vectorize`, see also: https://godbolt.org/z/7oedf34Pq

Reproduced from this C reproducer:

```
int a, b;
extern char e;
int *c;
short *d;
void f() {
  for (int g;;)
    for (char h; h < 20; h++) {
      a = c[h];
      for (int i = 0; i < 22; i += 3) {
        e = 0;
        b += d[g];
      }
    }
}
```

### LINKED ISSUE #167867: Assertion `ScaleFactor == vputils::getVFScaleFactor(Accumulator->getDefiningRecipe()) && "all accumulators in chain must have same scale factor"' failed.
Most likely this issue duplicates https://github.com/llvm/llvm-project/issues/167243

To reproduce run opt with -S -passes=loop-vectorize and the test below:
```
; ModuleID = './reduced.ll'
source_filename = "./reduced.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32-ni:1-p2:32:8:8:32-ni:2"
target triple = "aarch64-none-linux-gnu"

define i64 @wombat(ptr addrspace(1) %arg) #0 gc "statepoint-example" {
bb:
  br label %bb1

bb1:                                              ; preds = %bb1, %bb
  %phi = phi i64 [ 0, %bb ], [ %add3, %bb1 ]
  %phi2 = phi i32 [ 729, %bb ], [ %add4, %bb1 ]
  %load = load i32, ptr addrspace(1) null, align 4
  %sext = sext i32 %load to i64
  %mul = mul i64 %sext, 0
  %add = add i64 %sext, %phi
  %add3 = add i64 %add, %mul
  store i64 %add3, ptr addrspace(1) %arg, align 8
  %add4 = add i32 %phi2, 1
  %icmp = icmp ult i32 %phi2, 1
  br i1 %icmp, label %bb5, label %bb1

bb5:                                              ; preds = %bb1
  ret i64 0
}

attributes #0 = { "target-cpu"="neoverse-n1" }
```
Reproducer: https://godbolt.org/z/d5jGn6P6f

Stack dump:
```
opt: /root/llvm-project/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8234: llvm::VPRecipeBase* llvm::VPRecipeBuilder::tryToCreatePartialReduction(llvm::VPInstruction*, unsigned int): Assertion `ScaleFactor == vputils::getVFScaleFactor(Accumulator->getDefiningRecipe()) && "all accumulators in chain must have same scale factor"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -S -passes=loop-vectorize <source>
1.	Running pass "function(loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>)" on module "<source>"
2.	Running pass "loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>" on function "wombat"
 #0 0x00000000059c2018 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x59c2018)
 #1 0x00000000059beec4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000072eee7e42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000072eee7e969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x000072eee7e42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x000072eee7e287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x000072eee7e2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x000072eee7e39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x00000000036c4de0 llvm::VPRecipeBuilder::tryToCreatePartialReduction(llvm::VPInstruction*, unsigned int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36c4de0)
 #9 0x00000000036c779f llvm::VPRecipeBuilder::tryToCreateWidenRecipe(llvm::VPSingleDefRecipe*, llvm::VFRange&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36c779f)
#10 0x00000000036e69b7 llvm::LoopVectorizationPlanner::tryToBuildVPlanWithVPRecipes(std::unique_ptr<llvm::VPlan, std::default_delete<llvm::VPlan>>, llvm::VFRange&, llvm::LoopVersioning*) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36e69b7)
#11 0x00000000036e7fb8 llvm::LoopVectorizationPlanner::buildVPlansWithVPRecipes(llvm::ElementCount, llvm::ElementCount) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36e7fb8)
#12 0x00000000036e8935 llvm::LoopVectorizationPlanner::plan(llvm::ElementCount, unsigned int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36e8935)
#13 0x00000000036ec5b6 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36ec5b6)
#14 0x00000000036ef4d0 llvm::LoopVectorizePass::runImpl(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36ef4d0)
#15 0x00000000036efbb5 llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36efbb5)
#16 0x0000000002fd72be llvm::detail::PassModel<llvm::Function, llvm::LoopVectorizePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2fd72be)
#17 0x0000000005799e01 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x5799e01)
#18 0x0000000000f035fe llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xf035fe)
#19 0x000000000579847a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x579847a)
#20 0x000000000097defe llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x97defe)
#21 0x0000000005797e31 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x5797e31)
#22 0x000000000098809a llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x98809a)
#23 0x000000000097c311 optMain (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x97c311)
#24 0x000072eee7e29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#25 0x000072eee7e29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#26 0x0000000000973725 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x973725)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by fhahn**
https://github.com/llvm/llvm-project/pull/162822 added another validation step to check if entries in a partial reduction chain have the same scale factor. But the validation was still dependent on the order of entries in PartialReductionChains, and would fail to reject some cases (e.g. if the first first link matched the scale of the second link, but the second link is invalidated later).

To fix that, group chains by their starting phi nodes, then perform the validation for each chain, and if it fails, invalidate the whole chain for the phi.

Fixes https://github.com/llvm/llvm-project/issues/167243.
Fixes https://github.com/llvm/llvm-project/issues/167867.

### CODE REVIEW

**Review by SamTebbs33 — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 1]
```diff
@@ -8016,31 +8019,41 @@ void VPRecipeBuilder::collectScaledReductions(VFRange &Range) {
...
+        auto *UI = cast<Instruction>(U);
+        if (isa<PHINode>(UI) && UI->getParent() == OrigLoop->getHeader()) {
+          return all_of(UI->users(), [ScaleVal, this](const User *U) {
+            auto *UI = cast<Instruction>(U);
+            return ScaledReductionMap.lookup_or(UI, 0) == ScaleVal;
+          });
+        }
+        return ScaledReductionMap.lookup_or(UI, 0) == ScaleVal ||
+               !OrigLoop->contains(UI->getParent());
+      };
```
Comment (sdesmalen-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: This code is quite dizzying and I'm a bit puzzled why it is needed to go through the users() of `Chain.Reduction` and then each of its users(), where I would think this information is already encoded in the `ChainsByPhi` map itself.

My understanding is that `ChainsByPhi` is a map of `PHI -> [ <chain, scale>, <chain, scale>, ... ]` records, where each `chain` is an operation in that particular reduction chain (defined by its own extend instructions, extend-user (e.g. a `mul` or another operand in the chain) and the reduction op itself (e.g. `add` or `sub`)). If so, then why would it not be enough to check that all `<chain, scale>` has the same value for `scale`?

**Review by sdesmalen-arm — APPROVED** [review]
