### PR TITLE
[mlir][Math] Fix IPowIOp folding crash for i1

### LINKED ISSUE #179380: [mlir-opt] Crash in sparsification-and-bufferization pass triggered by emitc.unary_minus folding on i1
The compiler crashes during the **--sparsification-and-bufferization** pass when encountering an emitc.unary_minus operation acting on an i1 (1-bit integer) type. 
The crash is rooted in an APInt assertion failure, specifically when the folding or constant propagation logic attempts to handle the negation of a 1-bit value.
```mlir
module {
  func.func @main() {
    %0 = irdl.c_pred "::llvm::isa<::mlir::IntegerAttr>($_self)"
    %1 = sparse_tensor.has_runtime_library
    %2 = math.ctlz %1 : i1
    %3 = math.ipowi %2, %1 : i1
    %4 = emitc.unary_minus %3 : (i1) -> i1
    return
  }
}
```
```
mlir-opt --sparsification-and-bufferization test.mlir
```
```
mlir-opt: llvm-project-llvmorg-22.1.0-rc1/llvm/include/llvm/ADT/APInt.h:120: llvm::APInt::APInt(unsigned int, uint64_t, bool, bool): Assertion `llvm::isIntN(BitWidth, val) && "Value is not an N-bit signed value"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.      Program arguments: llvmorg-22.1.0-install/bin/mlir-opt --sparsification-and-bufferization test.mlir
 #0 0x000063b75b1b3e32 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (llvmorg-22.1.0-install/bin/mlir-opt+0x252fe32)
 #1 0x000063b75b1b05af llvm::sys::RunSignalHandlers() (llvmorg-22.1.0-install/bin/mlir-opt+0x252c5af)
 #2 0x000063b75b1b06fc SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x000071ea6b445330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #4 0x000071ea6b49eb2c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x000071ea6b49eb2c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x000071ea6b49eb2c pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x000071ea6b44527e raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x000071ea6b4288ff abort ./stdlib/abort.c:81:7
 #9 0x000071ea6b42881b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x000071ea6b43b517 (/lib/x86_64-linux-gnu/libc.so.6+0x3b517)
```

### PR DESCRIPTION
**Pull request by Ayush3941**
### What this problem

Fixes an assertion/crash in math.ipowi constant folding when the result type is i1, observed via mlir-opt --sparsification-and-bufferization. in #179380 of %4 unary_minus that triggered canonalization of %3 math.ipowi which crashes

### Why it happened

IPowIOp::fold constructed APInt(width=1, val=1, isSigned=true). Signed i1 cannot represent +1 (range [-1, 0]), so APInt asserts (isIntN).

### Whats the Fix

Construct oneValue without signed range checking (isSigned=false) so it represents the bitpattern 1 for the given width.

Add a regression test under Dialect/SparseTensor that runs the same pipeline and ensures it no longer crashes.

Fixes #179380

### CODE REVIEW

File: mlir/lib/Dialect/Math/IR/MathOps.cpp [hunk 1]
```diff
@@ -370,7 +370,7 @@ OpFoldResult math::IPowIOp::fold(FoldAdaptor adaptor) {
       [](const APInt &base, const APInt &power) -> std::optional<APInt> {
         unsigned width = base.getBitWidth();
         auto zeroValue = APInt::getZero(width);
-        APInt oneValue{width, 1ULL, /*isSigned=*/true};
+        APInt oneValue{width, 1ULL, /*isSigned=*/false};
```
Comment (matthias-springer) [inline mlir/lib/Dialect/Math/IR/MathOps.cpp]: `std::optional<APInt> oneValue = width == 1 ? std::nullopt : APInt(width, 1ULL, /*isSigned=*/true);`

**Review by matthias-springer — COMMENTED** [review]
Thx for adding the test cases. I think these show that there is still something wrong. Can we give the implementation that I commented a try?

**Review by kuhar — APPROVED** [review]

**Comment by Ayush3941** [comment]
so if the stuff looks alright can this be merged

**Review by matthias-springer — APPROVED** [review]
