### PR TITLE
[DirectX] add GEP i8 legalization

### LINKED ISSUE #140415: [DirectX] Validation Failure: Explicit gep type does not match pointee type of pointer operand
```bash
clang-dxc DirectML/Product/Shaders/Generated/Cast_float16_native_accum16_uint8_packed32_256_Strided4D.hlsl -E CSMain -T cs_6_2  -enable-16bit-types  -O3 -D DXC_COMPILER=1 -D __SHADER_TARGET_MAJOR=6 -D __SHADER_TARGET_MINOR=2 -I DirectML/Product/Shaders/ -Fo Cast_float16_native_accum16_uint8_packed32_256_Strided4D.dat
lldb -- dxv validation/Cast_float16_native_accum16_uint8_packed32_256_Strided4D.dat
```
```gdb
(lldb) expr *(BasePtr->getType()->getScalarType())
(llvm::Type) $18 = {
  Context = 0x000000016fdfdce0
  IDAndSubclassData = 14
  NumContainedTys = 1
  ContainedTys = 0x000000015280e5b8
}
(lldb) expr *Ty
(llvm::Type) $19 = {
  Context = 0x000000016fdfdce0
  IDAndSubclassData = 2058
  NumContainedTys = 0
  ContainedTys = nullptr
}
```
## Validation Error
https://github.com/microsoft/DirectXShaderCompiler/blob/adffd31eb02f690d9d1afe86c7fa6f12b4e70aa1/lib/Bitcode/Reader/BitcodeReader.cpp#L3931

## Function failing to validate

```llvm
 Materializable
; Function Attrs: noinline nounwind
define void @CSMain() unnamed_addr #1 {
  %1 = alloca [4 x i32], align 4
  %2 = alloca [4 x i32], align 4
  %3 = alloca [4 x i32], align 4
  %4 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false) #2
  %5 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 2, i32 0, i32 0, i1 false) #2
  %6 = call i32 @dx.op.threadId.i32(i32 93, i32 0) #3
  %7 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 10) #2
  %8 = extractvalue %dx.types.CBufRet.i32 %7, 3
  %9 = add i32 %8, %6
  %10 = shl i32 %9, 2
  %11 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 10) #2
  %12 = extractvalue %dx.types.CBufRet.i32 %11, 2
  %13 = icmp ult i32 %10, %12
  br i1 %13, label %14, label %46

; <label>:14                                      ; preds = %0
  %15 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 1, i32 1, i1 false) #2
  %16 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 5) #2
  %17 = extractvalue %dx.types.CBufRet.i32 %16, 1
  %18 = extractvalue %dx.types.CBufRet.i32 %16, 2
  %19 = extractvalue %dx.types.CBufRet.i32 %16, 3
  %20 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 9) #2
  %21 = extractvalue %dx.types.CBufRet.i32 %20, 0
  %22 = extractvalue %dx.types.CBufRet.i32 %20, 1
  %23 = extractvalue %dx.types.CBufRet.i32 %20, 2
  %24 = extractvalue %dx.types.CBufRet.i32 %20, 3
  %25 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 1) #2
  %26 = extractvalue %dx.types.CBufRet.i32 %25, 0
  %27 = extractvalue %dx.types.CBufRet.i32 %25, 1
  %28 = extractvalue %dx.types.CBufRet.i32 %25, 2
  %29 = extractvalue %dx.types.CBufRet.i32 %25, 3
  %30 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 3) #2
  %31 = extractvalue %dx.types.CBufRet.i32 %30, 0
  %32 = extractvalue %dx.types.CBufRet.i32 %30, 1
  %33 = extractvalue %dx.types.CBufRet.i32 %30, 2
  %34 = extractvalue %dx.types.CBufRet.i32 %30, 3
  %35 = call %dx.types.ResRet.i32 @dx.op.rawBufferLoad.i32(i32 139, %dx.types.Handle %15, i32 %9, i32 0, i8 1, i32 4)
  %36 = extractvalue %dx.types.ResRet.i32 %35, 0
  %37 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 10) #2
  %38 = extractvalue %dx.types.CBufRet.i32 %37, 1
                                                  ; No predecessors!
                                                  ; No predecessors!
                                                  ; No predecessors!
                                                  ; No predecessors!
                                                  ; No predecessors!
                                                  ; No predecessors!
                                                  ; No predecessors!

; <label>:46                                      ; preds = %0
}
```

## Basic Block failing to validate
```llvm
(lldb) expr getLastInstruction->CurBB->dump()

; <label>:14                                      ; preds = %0
  %15 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 1, i32 1, i1 false) #2
  %16 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 5) #2
  %17 = extractvalue %dx.types.CBufRet.i32 %16, 1
  %18 = extractvalue %dx.types.CBufRet.i32 %16, 2
  %19 = extractvalue %dx.types.CBufRet.i32 %16, 3
  %20 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 9) #2
  %21 = extractvalue %dx.types.CBufRet.i32 %20, 0
  %22 = extractvalue %dx.types.CBufRet.i32 %20, 1
  %23 = extractvalue %dx.types.CBufRet.i32 %20, 2
  %24 = extractvalue %dx.types.CBufRet.i32 %20, 3
  %25 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 1) #2
  %26 = extractvalue %dx.types.CBufRet.i32 %25, 0
  %27 = extractvalue %dx.types.CBufRet.i32 %25, 1
  %28 = extractvalue %dx.types.CBufRet.i32 %25, 2
  %29 = extractvalue %dx.types.CBufRet.i32 %25, 3
  %30 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 3) #2
  %31 = extractvalue %dx.types.CBufRet.i32 %30, 0
  %32 = extractvalue %dx.types.CBufRet.i32 %30, 1
  %33 = extractvalue %dx.types.CBufRet.i32 %30, 2
  %34 = extractvalue %dx.types.CBufRet.i32 %30, 3
  %35 = call %dx.types.ResRet.i32 @dx.op.rawBufferLoad.i32(i32 139, %dx.types.Handle %15, i32 %9, i32 0, i8 1, i32 4)
  %36 = extractvalue %dx.types.ResRet.i32 %35, 0
  %37 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %5, i32 10) #2
  %38 = extractvalue %dx.types.CBufRet.i32 %37, 1
```

### PR DESCRIPTION
**Pull request by farzonl**
fixes #140415

The i8 legalization code in DXILLegalizePass's `fixI8UseChain` needs to be updated to check for i8 geps.
It seems like there are i8 GEPs being left around after we remove all the other i8 instructions and this is causing problem on validation.

Since this is cleaning up a missed GEP The approach is to assume the getPointerOperand is to an alloca we further will check if this is an array alloca then do some byte offset arithmetic to figure out the memory index to use. Finally we will emit the new gep and cleanup the old one.

Finally needed to update upcastI8AllocasAndUses to account for loads off of GEPs instead of just loads from the alloca.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 1]
```diff
@@ -164,6 +166,36 @@ static void fixI8UseChain(Instruction &I,
...
+      BasePtr = ReplacedValues[BasePtr];
+
+    Type *ElementType = BasePtr->getType();
+    if (auto *AI = dyn_cast<AllocaInst>(BasePtr))
+      ElementType = AI->getAllocatedType();
+    if (auto *ArrTy = dyn_cast<ArrayType>(ElementType))
+      ElementType = ArrTy->getArrayElementType();
+
+    ConstantInt *Offset = dyn_cast<ConstantInt>(GEP->getOperand(1));
+    // Note: the only way to convert an i8 offset to an i32 offset without
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: This sentence seems incomplete?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 2]
```diff
@@ -164,6 +166,36 @@ static void fixI8UseChain(Instruction &I,
...
+    // emitting code Would be to emit code. We sould expect this value to be a
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: should

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 3]
```diff
@@ -164,6 +166,36 @@ static void fixI8UseChain(Instruction &I,
...
+    // ConstantInt since Offsets are very regulalrly converted.
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: regularly

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 4]
```diff
@@ -175,25 +207,35 @@ static void upcastI8AllocasAndUses(Instruction &I,
...
 
-  for (User *U : AI->users()) {
-    auto *Load = dyn_cast<LoadInst>(U);
-    if (!Load)
-      continue;
+  auto ProcessLoad = [&](LoadInst *Load) {
     for (User *LU : Load->users()) {
       Type *Ty = nullptr;
-      if (auto *Cast = dyn_cast<CastInst>(LU))
+      if (auto *Cast = dyn_cast<CastInst>(LU)) {
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: unnecessary braces?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 5]
```diff
@@ -175,25 +207,35 @@ static void upcastI8AllocasAndUses(Instruction &I,
...
         Ty = Cast->getType();
-      if (CallInst *CI = dyn_cast<CallInst>(LU)) {
+      } else if (auto *CI = dyn_cast<CallInst>(LU)) {
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: can it be a callinst and a castinst?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp [hunk 6]
```diff
@@ -175,25 +207,35 @@ static void upcastI8AllocasAndUses(Instruction &I,
...
           Ty = Type::getInt32Ty(CI->getContext());
       }
 
       if (!Ty)
         continue;
 
-      if (!SmallestType ||
-          Ty->getPrimitiveSizeInBits() < SmallestType->getPrimitiveSizeInBits())
+      if (!SmallestType || Ty->getPrimitiveSizeInBits() <
+                               SmallestType->getPrimitiveSizeInBits()) {
```
Comment (spall) [inline llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: unnecessary braces?

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 1 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: yeah I didn't save my changes before commit.  put back in draft mode.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 4 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: Having a Mandela effect moment.  I remember a rule that if the other conditionals  ie the `else if`\ `else` cases go multiple lines then you do put braces on the `if` even if it is one line. But now I can't find documentation on that rule so I'll go ahead and make this change.

File: llvm/lib/Target/DirectX/DXILLegalizePass.cpp (hunk 6 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILLegalizePass.cpp]: Yes thank you! Vscode  did some auto complete funny buisness when was trying to move this into a lambda.

**Review by Icohedron — DISMISSED** [review]

**Comment by Icohedron** [comment]
This PR appears to fail to compile this shader: https://godbolt.org/z/9MPc8Wca5

Stack trace:
```
While deleting: ptr addrspace(3) %
Use still stuck around after Def is destroyed:  %2 = load float, ptr addrspace(3) <badref>, align 4
Uses remain when a value is destroyed!
UNREACHABLE executed at /workspace/llvm-project/llvm/lib/IR/Value.cpp:102!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: bin/clang-dxc -T cs_6_3 -E CSMain -enable-16bit-types Reproduce.hlsl
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'Reproduce.hlsl'.
4.      Running pass 'DXIL Legalizer' on function '@CSMain'
 #0 0x00005faf059d7246 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /workspace/llvm-project/llvm/lib/Support/Unix/Signals.inc:804:13
 #1 0x00005faf059d4ff0 llvm::sys::RunSignalHandlers() /workspace/llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #2 0x00005faf059430bd (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /workspace/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:74:5
 #3 0x00005faf059430bd CrashRecoverySignalHandler(int) /workspace/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:391:51
 #4 0x000075164ba40a70 __restore_rt (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x40a70)
 #5 0x000075164ba988ec __pthread_kill_implementation (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x988ec)
 #6 0x000075164ba409c6 gsignal (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x409c6)
 #7 0x000075164ba28938 abort (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x28938)
 #8 0x00005faf05949c9f (bin/clang-dxc+0x4201c9f)
 #9 0x00005faf054ffd50 llvm::Value::~Value() /workspace/llvm-project/llvm/lib/IR/Value.cpp:0:5
#10 0x00005faf054ff976 llvm::Value::deleteValue() /workspace/llvm-project/llvm/lib/IR/Value.cpp:0:3
#11 0x00005faf054673d3 llvm::iplist_impl<llvm::simple_ilist<llvm::Instruction, llvm::ilist_iterator_bits<true>, llvm::ilist_parent<llvm::BasicBlock>>, llvm::SymbolTableListTraits<llvm::Instruction, llvm::ilist_iterator_bits<true>, llvm::ilist_parent<llvm::BasicBlock>>>::erase(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, false>) /workspace/llvm-project/llvm/include/llvm/ADT/ilist.h:206:12
#12 0x00005faf054673d3 llvm::Instruction::eraseFromParent() /workspace/llvm-project/llvm/lib/IR/Instruction.cpp:96:37
#13 0x00005faf0472710a bool std::operator==<llvm::Instruction**>(std::reverse_iterator<llvm::Instruction**> const&, std::reverse_iterator<llvm::Instruction**> const&) /nix/store/gnf3mv68i5g6jmabnbbncsar3kbg13zd-gcc-14-20241116/include/c++/14-20241116/bits/stl_iterator.h:443:25
#14 0x00005faf0472710a bool std::operator!=<llvm::Instruction**>(std::reverse_iterator<llvm::Instruction**> const&, std::reverse_iterator<llvm::Instruction**> const&) /nix/store/gnf3mv68i5g6jmabnbbncsar3kbg13zd-gcc-14-20241116/include/c++/14-20241116/bits/stl_iterator.h:457:20
#15 0x00005faf0472710a (anonymous namespace)::DXILLegalizationPipeline::runLegalizationPipeline(llvm::Function&) /workspace/llvm-project/llvm/lib/Target/DirectX/DXILLegalizePass.cpp:477:21
#16 0x00005faf0472ad22 (anonymous namespace)::DXILLegalizeLegacy::runOnFunction(llvm::Function&) /workspace/llvm-project/llvm/lib/Target/DirectX/DXILLegalizePass.cpp:522:21
#17 0x00005faf05499da9 llvm::FPPassManager::runOnFunction(llvm::Function&) /workspace/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1406:27
#18 0x00005faf054a0c92 llvm::FPPassManager::runOnModule(llvm::Module&) /workspace/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1452:13
#19 0x00005faf0549a4a0 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /workspace/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:0:27
#20 0x00005faf0549a4a0 llvm::legacy::PassManagerImpl::run(llvm::Module&) /workspace/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:539:44
#21 0x00005faf061298ea (anonymous namespace)::EmitAssemblyHelper::RunCodegenPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) /workspace/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1262:9
#22 0x00005faf061298ea (anonymous namespace)::EmitAssemblyHelper::emitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) /workspace/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1285:3
#23 0x00005faf061298ea clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) /workspace/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1450:13
#24 0x00005faf0613d5ea std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>::~unique_ptr() /nix/store/gnf3mv68i5g6jmabnbbncsar3kbg13zd-gcc-14-20241116/include/c++/14-20241116/bits/unique_ptr.h:398:6
#25 0x00005faf0613d5ea clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /workspace/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:316:3
#26 0x00005faf07c789d9 __gnu_cxx::__normal_iterator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>*, std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>>>>::__normal_iterator(std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>* const&) /nix/store/gnf3mv68i5g6jmabnbbncsar3kbg13zd-gcc-14-20241116/include/c++/14-20241116/bits/stl_iterator.h:1068:20
#27 0x00005faf07c789d9 std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>>>::begin() /nix/store/gnf3mv68i5g6jmabnbbncsar3kbg13zd-gcc-14-20241116/include/c++/14-20241116/bits/stl_vector.h:874:16
#28 0x00005faf07c789d9 void clang::finalize<std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>>>>(std::vector<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>, std::allocator<std::unique_ptr<clang::TemplateInstantiationCallback, std::default_delete<clang::TemplateInstantiationCallback>>>>&, clang::Sema const&) /workspace/llvm-project/clang/include/clang/Sema/TemplateInstCallback.h:54:16
#29 0x00005faf07c789d9 clang::ParseAST(clang::Sema&, bool, bool) /workspace/llvm-project/clang/lib/Parse/ParseAST.cpp:190:3
#30 0x00005faf067209f4 clang::FrontendAction::Execute() /workspace/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1225:10
#31 0x00005faf066904ad llvm::Error::getPtr() const /workspace/llvm-project/llvm/include/llvm/Support/Error.h:278:42
#32 0x00005faf066904ad llvm::Error::operator bool() /workspace/llvm-project/llvm/include/llvm/Support/Error.h:241:16
#33 0x00005faf066904ad clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /workspace/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1055:23
#34 0x00005faf0680e5c8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /workspace/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:300:25
#35 0x00005faf045cd043 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /workspace/llvm-project/clang/tools/driver/cc1_main.cpp:297:15
#36 0x00005faf045c93b5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) /workspace/llvm-project/clang/tools/driver/driver.cpp:223:12
#37 0x00005faf06500bd9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0::operator()() const /workspace/llvm-project/clang/lib/Driver/Job.cpp:436:30
#38 0x00005faf06500bd9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) /workspace/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#39 0x00005faf05942cd2 llvm::function_ref<void ()>::operator()() const /workspace/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#40 0x00005faf05942cd2 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /workspace/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:427:3
#41 0x00005faf06500284 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const /workspace/llvm-project/clang/lib/Driver/Job.cpp:436:7
#42 0x00005faf064c1d78 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const /workspace/llvm-project/clang/lib/Driver/Compilation.cpp:196:15
#43 0x00005faf064c1fc7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const /workspace/llvm-project/clang/lib/Driver/Compilation.cpp:251:13
#44 0x00005faf064de649 llvm::SmallVectorBase<unsigned int>::empty() const /workspace/llvm-project/llvm/include/llvm/ADT/SmallVector.h:82:46
#45 0x00005faf064de649 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) /workspace/llvm-project/clang/lib/Driver/Driver.cpp:2229:23
#46 0x00005faf045c8d14 clang_main(int, char**, llvm::ToolContext const&) /workspace/llvm-project/clang/tools/driver/driver.cpp:406:21
#47 0x00005faf045d9006 main /workspace/llvm-project/build/tools/clang/tools/driver/clang-driver.cpp:17:10
#48 0x000075164ba2a1fc __libc_start_call_main (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x2a1fc)
#49 0x000075164ba2a2b9 __libc_start_main@GLIBC_2.2.5 (/nix/store/h7zcxabfxa7v5xdna45y2hplj31ncf8a-glibc-2.40-36/lib/libc.so.6+0x2a2b9)
#50 0x00005faf045c6d25 _start (bin/clang-dxc+0x2e7ed25)
clang-dxc: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 21.0.0git (git@github.com:Icohedron/llvm-project.git 19668a1619396f3ea7447df4644b362af870c982)
Target: dxilv1.3-unknown-shadermodel6.3-compute
Thread model: posix
InstalledDir: /workspace/llvm-project/build/bin
Build config: +assertions
clang-dxc: note: diagnostic msg:
```

**Review by Icohedron — DISMISSED** [review]

**Comment by Icohedron** [comment]
> This PR appears to fail to compile this shader: https://godbolt.org/z/9MPc8Wca5
> 

This shader now compiles, but it currently fails DXIL validation with the message
```
Explicit gep operator type does not match pointee type of pointer operand
Validation failed.
```

I think the i8 legalization is producing an incorrect GEP.

I see the pass converting these instructions:
```llvm
  %2 = getelementptr inbounds nuw i8, ptr addrspace(3) @g, i32 4
  %3 = load float, ptr addrspace(3) %2, align 4
```

into
```llvm
  %2 = load float, ptr addrspace(3) getelementptr inbounds nuw (ptr addrspace(3), ptr addrspace(3) @g, i32 1), align 4
```

but I would have expected this instead:
```llvm
  %2 = load float, ptr addrspace(3) getelementptr inbounds nuw ([2 x float], ptr addrspace(3) @g, i32 0, i32 1), align 4
```

because the global is defined as `@g = local_unnamed_addr addrspace(3) global [2 x float] zeroinitializer, align 4` and an earlier store operation in the IR looks fine
```llvm
  %arrayidx.i = getelementptr inbounds nuw [2 x float], ptr addrspace(3) @g, i32 0, i32 %1
  store float 0.000000e+00, ptr addrspace(3) %arrayidx.i, align 4, !tbaa !5
```

**Comment by farzonl** [comment]
the bug I was looking at used allocas, this one uses a globals its an easy fix to add:
```
if (auto *GV = dyn_cast<GlobalVariable>(BasePtr))
      ElementType = GV->getValueType();
```

However during my testing I found another gap. we still need to figure out how to support constExpr GEPs. 

> > This PR appears to fail to compile this shader: https://godbolt.org/z/9MPc8Wca5
> 
> This shader now compiles, but it currently fails DXIL validation

File: llvm/test/CodeGen/DirectX/legalize-i8.ll [hunk 7]
```diff
@@ -106,3 +106,57 @@ define i32 @all_imm() {
...
+  %2 = getelementptr inbounds nuw i8, ptr %1, i32 0
+  %3 = load i8, ptr %2
+  %4 = sext i8 %3 to i32
+  ret i32 %4
+}
+
+define i32 @i8_geps_index1() {
+  ; CHECK-LABEL: define i32 @i8_geps_index1(
+  ; CHECK-NEXT:    [[ALLOCA:%.*]] = alloca [2 x i32], align 8
+  ; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[ALLOCA]], i32 1
```
Comment (Icohedron) [inline llvm/test/CodeGen/DirectX/legalize-i8.ll]: Shouldn't the GEP type be `[2 x i32]`?
```suggestion
  ; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw [2 x i32], ptr [[ALLOCA]], i32 0, i32 1
```

Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll]: I'm pretty sure the GEP type being incorrect is causing the validation error `Explicit gep operator type does not match pointee type of pointer operand`

**Comment by Icohedron** [comment]
> the bug I was looking at used allocsa, this one uses a globals its an easy fix to add:
> 
> ```
> if (auto *GV = dyn_cast<GlobalVariable>(BasePtr))
>       ElementType = GV->getValueType();
> ```
> 
> However during my testing I found another gap. we still need to figure out how to support constExpr GEPs.
> 
> > > This PR appears to fail to compile this shader: https://godbolt.org/z/9MPc8Wca5
> > 
> > 
> > This shader now compiles, but it currently fails DXIL validation

Incorporating that change still results in a shader that doesn't pass validation due to the same message: `Explicit gep operator type does not match pointee type of pointer operand`

The DXIL Legalize pass now emits:
```llvm
@g = local_unnamed_addr addrspace(3) global [2 x float] zeroinitializer, align 4
...
define void @CSMain() local_unnamed_addr #0 {
entry:
  ...
  %2 = load float, ptr addrspace(3) getelementptr inbounds nuw (float, ptr addrspace(3) @g, i32 1), align 4
```

I would expect the `%2` instruction to be the following to be a valid GEP:
```llvm
  %2 = load float, ptr addrspace(3) getelementptr inbounds nuw ([2 x float], ptr addrspace(3) @g, i32 0, i32 1), align 4
```

Since vectors have been scalarized and arrays have been flattened, this should be straightforward to fix.

File: llvm/test/CodeGen/DirectX/legalize-i8.ll (hunk 7 above)
Comment (farzonl) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll]: Should be fixed now.

File: llvm/test/CodeGen/DirectX/legalize-i8.ll [hunk 8]
```diff
@@ -110,8 +110,8 @@ define i32 @all_imm() {
 define i32 @scalar_i8_geps() {
   ; CHECK-LABEL: define i32 @scalar_i8_geps(
   ; CHECK-NEXT:    [[ALLOCA:%.*]] = alloca i32, align 4
-  ; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[ALLOCA]], i32 0
-  ; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
+  ; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw [1 x i32], ptr [[ALLOCA]], i32 0, i32 0
```
Comment (Icohedron) [inline llvm/test/CodeGen/DirectX/legalize-i8.ll:113]: I'm not sure if the validator will accept this, and I'm also unsure how to test that.
The validator may consider the GEP operator type `[1 x i32]` to be invalid because the pointee type is `i32`.

Comment (farzonl) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:113]: use llc to generate DXIL https://godbolt.org/z/59KEE8rT9 feed that in to the validator

Comment (farzonl) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:113]: I can make the scalars be scalar It just requires more code that is more than just checking type. you have to create an array of indicies or  use a scalar int for index and they can't share the same variable name so you are either  creating two cases of gep builders or you are creating both index types so you can use a terinary to feed it into the gep builder. If the validator can accept this then it would make the code cleaner if not we can always do the alternative.

Comment (Icohedron) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:113]: I can't seem to get llc to produce a binary of the format that the validator is expecting.

Comment (farzonl) [reply llvm/test/CodeGen/DirectX/legalize-i8.ll:113]: sorry  -filetype=obj  https://godbolt.org/z/bjEq84qME

I'm seeing the following validation failures:
```
error: Unknown part 'ISG1' found in DXIL container.
error: Unknown part 'OSG1' found in DXIL container.
error: Unknown part 'PSV0' found in DXIL container.
error: Missing part 'Runtime Data (RDAT)' required by module.
Validation failed.
```
Nothing though that would indicate an issue with GEP.

**Review by Icohedron — APPROVED** [review]
