### PR TITLE
[analyzer] Fix crashing __builtin_bit_cast

### LINKED ISSUE #137417: Static analyzer crashes using std::bit_cast expression
The clang static analyzer crashes using a `std::bit_cast` expression:

```
#include <string>

static bool crash(std::string* x)
{
    return x == std::bit_cast<std::string*>(static_cast<intptr_t>(-1));
}
```

Godbolt:  <https://godbolt.org/z/8PYYEW156>

```
clang++: warning: argument unused during compilation: '-S' [-Wunused-command-line-argument]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-20.1.0/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-14.2.0 -fcolor-diagnostics -fno-crash-diagnostics -std=c++2a -stdlib=libc++ --analyze <source>
1.	<eof> parser at end of file
2.	While analyzing stack: 
	#0 Calling crash(std::string *)
3.	<source>:5:12: Error evaluating statement
4.	<source>:5:12: Error evaluating statement
 #0 0x0000000003a59568 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x3a59568)
 #1 0x0000000003a576ac llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x3a576ac)
 #2 0x00000000039a69e8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000702688642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000006255ab7 (anonymous namespace)::SimpleSValBuilder::evalBinOpLN(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::Loc, clang::ento::NonLoc, clang::QualType) SimpleSValBuilder.cpp:0:0
 #5 0x0000000006266819 clang::ento::SValBuilder::evalBinOp(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::SVal, clang::ento::SVal, clang::QualType) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x6266819)
 #6 0x0000000006198abf clang::ento::ExprEngine::VisitBinaryOperator(clang::BinaryOperator const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x6198abf)
 #7 0x000000000617d177 clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x617d177)
 #8 0x000000000617d4f5 clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x617d4f5)
 #9 0x000000000618bc72 clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x618bc72)
#10 0x00000000061361fd clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x61361fd)
#11 0x0000000006136444 clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x6136444)
#12 0x0000000005d3331d (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*, void>>*) AnalysisConsumer.cpp:0:0
#13 0x0000000005d34449 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) AnalysisConsumer.cpp:0:0
#14 0x00000000062c3aec clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x62c3aec)
#15 0x0000000004682ca1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x4682ca1)
#16 0x000000000460260b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x460260b)
#17 0x000000000476e173 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x476e173)
#18 0x0000000000d116c1 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0xd116c1)
#19 0x0000000000d09eed ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#20 0x00000000043f5b49 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#21 0x00000000039a6e13 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x39a6e13)
#22 0x00000000043f5d69 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#23 0x00000000043b9ebd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x43b9ebd)
#24 0x00000000043bae51 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x43bae51)
#25 0x00000000043c51ec clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x43c51ec)
#26 0x0000000000d0e391 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0xd0e391)
#27 0x0000000000bd3bc4 main (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0xbd3bc4)
#28 0x0000702688629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#29 0x0000702688629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#30 0x0000000000d09985 _start (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0xd09985)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

Also tracked as <rdar://144714840>.

### PR DESCRIPTION
**Pull request by ziqingluo-90**
I am investigating a CSA crash: https://godbolt.org/z/fEExYqoWM.  If one changes the `__builtin_bit_cast` to a C-style cast, the test will be fine.  So the problem is specific to `__builtin_bit_cast`.

Looking at the piece of code below, it seems that CSA handles `__builtin_bit_cast` just as an `LValueToRValue` cast.  The actual operation of cast-to-target-type is missing. 
```
void ExprEngine::VisitCast(const CastExpr *CastE, const Expr *Ex,
                           ExplodedNode *Pred, ExplodedNodeSet &Dst) {

  ExplodedNodeSet dstPreStmt;
  getCheckerManager().runCheckersForPreStmt(dstPreStmt, Pred, CastE, *this);

  if (CastE->getCastKind() == CK_LValueToRValue ||
      CastE->getCastKind() == CK_LValueToRValueBitCast) {
    for (ExplodedNode *subExprNode : dstPreStmt) {
      ProgramStateRef state = subExprNode->getState();
      const LocationContext *LCtx = subExprNode->getLocationContext();
      evalLoad(Dst, CastE, CastE, subExprNode, state, state->getSVal(Ex, LCtx));
    }
    return;
  }
```

The `BuiltinBitCastExpr` node always have the kind `LValueToRValueBitCast`.  I suppose it is just associated to the second argument of a `__builtin_bit_cast` call.  
```
-BuiltinBitCastExpr <col:17, col:45> 'void *' <LValueToRValueBitCast>
```

I'm trying to add the missing part.

Fixes #137417

### CODE REVIEW

**Review by NagyDonat — COMMENTED** [review]
Overall LGTM, thanks for fixing this crash!

I dropped one (somewhat paranoid) inline question.

Moreover, I would suggest following the [coding standard](https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly) and use `UpperCamelCase` for the variables that are freshly introduced (and perhaps also for the variables that were already existing, if you touch most references to them and could easily rename them). Unfortunately we cannot "jump to" this naming standard by globally renaming many variables (because that would heavily pollute the git history), but I think we should gradually transition by following the standard in new variables and perhaps renaming the variables in the code that we touch. (As a personal preference, I consistently update the variable names when I edit some code, but objectively it's also OK to keep the old names to preserve consistency with adjacent existing code.)

**Review by steakhal — COMMENTED** [review]
LGTM overall. Thank you!
I'm also in favor of following the LLVM coding style.

File: clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp [hunk 1]
```diff
@@ -285,15 +285,43 @@ void ExprEngine::VisitCast(const CastExpr *CastE, const Expr *Ex,
...
+                   state->getSVal(Ex, LCtx), true);
+    }
+    // Simulate the operation that actually casts the original value to a new
+    // value of the destination type :
+    StmtNodeBuilder Bldr(dstEvalLoad, Dst, *currBldrCtx);
+
+    for (ExplodedNode *Node : dstEvalLoad) {
+      ProgramStateRef state = Node->getState();
+      const LocationContext *LCtx = Node->getLocationContext();
+      // getAsRegion should always be successful since Ex is an lvalue:
```
[the remark this answers is not in the document]
Comment (ziqingluo-90) [reply clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp:314]: I tried `__builtin_bit_cast(unsigned, *(reinterpret_cast<int*>(0xdeadbeef)))` (there is a compilation error with `static_cast`).

The `core.FixedAddressDereference`  checker will report it before it reaches the point, but the analyzer crashes if I disable the checker.  I think in cases of `loc::ConcreteInt`, the bit_cast should output `Unknown`.

**Comment by ziqingluo-90** [comment]
Thanks for reviewing!

**Comment by ziqingluo-90** [comment]
This fix should solve https://github.com/llvm/llvm-project/issues/71174, and https://github.com/llvm/llvm-project/issues/137417

File: clang/test/Analysis/builtin_bitcast.cpp [hunk 2]
```diff
@@ -1,5 +1,5 @@
 // RUN: %clang_analyze_cc1 -triple x86_64-unknown-unknown -verify %s \
-// RUN:   -analyzer-checker=core,debug.ExprInspection
+// RUN:   -analyzer-checker=debug.ExprInspection -analyzer-disable-checker=core
```
Comment (steakhal) [inline clang/test/Analysis/builtin_bitcast.cpp:2]: Why do you disable core?
That is not supposed to be disabled. Checkers or the engine may crash if core is disabled.

File: clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp [hunk 3]
```diff
@@ -282,15 +282,48 @@ ProgramStateRef ExprEngine::handleLValueBitCast(
...
+    for (ExplodedNode *Node : DstEvalLoc) {
+      ProgramStateRef State = Node->getState();
+      const LocationContext *LCtx = Node->getLocationContext();
+      // Although `Ex` is an lvalue, it could have `Loc::ConcreteInt` kind
+      // (e.g., `(int *)123456`).  In such cases, there is no MemRegion
+      // available and we can't get the value to be casted.
+      const MemRegion *MR = State->getSVal(Ex, LCtx).getAsRegion();
+      SVal CastedV = UnknownVal();
+
+      if (MR) {
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp:320]: You could use init ifs here.

**Review by steakhal — APPROVED** [review]
LGTM.

File: clang/test/Analysis/builtin_bitcast.cpp (hunk 2 above)
Comment (ziqingluo-90) [reply clang/test/Analysis/builtin_bitcast.cpp:2]: Oh, I was going to just disable `core.FixedAddressDereference`

File: clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (NagyDonat) [reply clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp]: Thanks for checking this!

**Review by steakhal — APPROVED** [review]
Still LGTM.
