### PR TITLE
[clang] Accept recursive non-dependent calls to functions with deduced return type

### LINKED ISSUE #71015: [clang] seems like bug with return type deduction in case of recursive function (works in GCC)
Here is an example
```cpp
struct Node {
  int value;
  Node* left;
  Node* right;
};

bool parse(const char*);
Node* parsePrimaryExpr();

auto parseMulExpr(auto node) {
  if (node == nullptr) node = parsePrimaryExpr();
  if (!parse("*")) return node;
  return parseMulExpr(new Node{.left = node, .right = parsePrimaryExpr()});
}

int main(){
  parseMulExpr((Node*)nullptr);
}
```
Clang gives this error
```
<source>:13:10: error: function 'parseMulExpr<Node *>' with deduced return type cannot be used before it is defined
   13 |   return parseMulExpr(new Node{.left = node, .right = parsePrimaryExpr()});
      |          ^
<source>:10:6: note: 'parseMulExpr<Node *>' declared here
   10 | auto parseMulExpr(auto node) {
      |      ^
1 error generated.
Compiler returned: 1
```
https://godbolt.org/z/7WTYYben5

### PR DESCRIPTION
**Pull request by Fznamznon**
Treat such calls as dependent since it is much easier to implement.

Fixes https://github.com/llvm/llvm-project/issues/71015

### CODE REVIEW

**Comment by Fznamznon** [comment]
This attempts to implement the approach described by @zygoloid in https://github.com/llvm/llvm-project/issues/71015#issuecomment-1828745626 .

**Review by erichkeane — APPROVED** [review]

**Comment by Fznamznon** [comment]
Thanks @erichkeane for review!
@zygoloid , I would really appreciate if you took a look as well. Otherwise I'll try to merge in a couple of days.

File: clang/test/SemaCXX/deduced-return-type-cxx14.cpp [hunk 1]
```diff
@@ -640,3 +640,36 @@ namespace PR46637 {
...
+  Node* right;
+};
+
+bool parse(const char*);
+Node* parsePrimaryExpr();
+
+auto parseMulExpr(auto node) { // cxx14-error {{'auto' not allowed in function prototype}}
+  if (node == nullptr) node = parsePrimaryExpr();
+  if (!parse("*")) return node;
+  return parseMulExpr(new Node{.left = node, .right = parsePrimaryExpr()});
```
Comment (zygoloid) [inline clang/test/SemaCXX/deduced-return-type-cxx14.cpp:660]: It would be great to add a test that this is rejected without the previous line `retuen node;`

**Review by zygoloid — APPROVED** [review]
Looks good, thanks!

File: clang/test/SemaCXX/deduced-return-type-cxx14.cpp (hunk 1 above)
Comment (Fznamznon) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:661]: Added the test.

A note here is that It will only be rejected if the function instantiated because clang doesn't take into account return statements if the function is templated due to this part:

https://github.com/llvm/llvm-project/blob/11276563c81987791a2326950dbc3315a32dd709/clang/lib/Sema/SemaStmt.cpp#L3806

gcc rejects even if the function is not instantiated. msvc doesn't. https://compiler-explorer.com/z/hGc8M1esT

Comment (zygoloid) [reply clang/test/SemaCXX/deduced-return-type-cxx14.cpp:661]: I think that's fine, and it's what I expected. While we could try to reject in the template definition if we see a recursive call prior to the end of the first `return` statement, I don't think it's worth the added complexity.

I *think* what GCC's doing here is that it's treating the recursive call as dependent in much the same way that Clang does with this patch, but then performing an instantiation of the function template specialization `parseMulExpr<Node*>` *after* it finishes processing the template definition -- so it's also not eagerly diagnosing the problem. (Clang suppresses performing recursive non-dependent function template instantiations until the template has a point of instantiation outside itself, which GCC doesn't seem to do.) But I could be wrong.

**Comment by shafik** [comment]
Looks like this is linked to the following regression: https://github.com/llvm/llvm-project/issues/133688
