### PR TITLE
[clang][CodeGen][UBSan] Fixing shift-exponent generation for _BitInt

### LINKED ISSUE #80135: Faulty -fsanitize=shift-exponent  checks (seen with _BitInt)
Consider these examples:
```
int test_left(unsigned _BitInt(17) x) {
  return x << 3uwb;  // Shift exponent is OK (3 < 17)  
}

int test_right(unsigned _BitInt(4) x) {
  return x >> 16uwb; // Shift exponent is NOK (16 >= 4)
}
```

When compiled with `-O1 -fsanitize=shift-exponent -emit-llvm -g0` the result is:
```
define dso_local noundef i32 @test_left(i17 noundef zeroext %0) local_unnamed_addr #0 {
  %2 = zext i17 %0 to i64
  tail call void @__ubsan_handle_shift_out_of_bounds(ptr nonnull @2, i64 %2, i64 3) #3
  %3 = shl i17 %0, 3
  %4 = zext i17 %3 to i32
  ret i32 %4
}

define dso_local noundef i32 @test_right(i4 noundef zeroext %0) local_unnamed_addr #2 {
  %2 = zext i4 %0 to i32
  ret i32 %2
}
```

So we actually see the opposite from the expected result (test_left will report UB and test_right will not report UB).

Quick analysis show:
Faults seem to be in ScalarExprEmitter::EmitShl / ScalarExprEmitter::EmitShr / ScalarExprEmitter::GetWidthMinusOneValue.

For the left shift  EmitShl uses the type of the right hand side when doing the ubsan checks. But when using the GetWidthMinusOneValue helper  it is not considered that the upper shift count limit given by the size of the left hand side operand might not fit in the type used by the right hand side. So the value is simply truncated and that results in an incorrect upper bound when doing the check.

For the right shift EmitShr is truncating the shift exponent operand to the size of the left hand side operand before doing the out-of-bounds check. This seems incorrect, as the check really should be performed using the type of the shift exponent operand.

### PR DESCRIPTION
**Pull request by AdamMagierFOSS**
Testing the shift-exponent check with small width _BitInt values exposed a bug in ScalarExprEmitter::GetWidthMinusOneValue when using the result to determine valid exponent sizes. False positives were reported for some left shifts when width(LHS)-1 > range(RHS) and false negatives were reported for right shifts when value(RHS) > range(LHS). This patch caps the maximum value of GetWidthMinusOneValue to fit within range(RHS) to fix the issue with left shifts and fixes a code generation in EmitShr to fix the issue with right shifts and renames the function to GetMaximumShiftAmount to better reflect the new behaviour.

Fixes #80135.

### CODE REVIEW

**Comment by AdamMagierFOSS** [comment]
One thing I'll preemptively address is I didn't know where to put the new unit testing - creating a separate file seems a little heavy handed but I see that there's a test for UBSan shift generation (`clang/test/CodeGen/ubsan-shift.c`) and one for UBSan + _BitInt (`clang/test/CodeGen/ext-int-sanitizer.cpp`). Both seem equally "valid" but neither seem to test in the same way that I'm trying to test these changes. Advice on this would be appreciated.

**Comment by bjope** [comment]
Make sure the commit message refers to fixing #80135.

(Github is a bit weird, so if you want to use the "squash an merge" support in the web UI later, then I think you need to update the first comment in the "Conversation", rather than updating the commits on this pull-request branch.)

File: clang/test/CodeGen/ubsan-shift-bitint.c [hunk 1]
```diff
@@ -0,0 +1,36 @@
+// RUN: %clang_cc1 %s -O0 -fsanitize=shift-exponent -emit-llvm -o - | FileCheck %s
```
Comment (bjope) [inline clang/test/CodeGen/ubsan-shift-bitint.c:1]: I think you for example want to use `-std=c2x -triple=x86_64-unknown-linux` here.
(Not sure exactly if you for example need the triple, but I fear that you would end up with failing build bots otherwise as not all targets support C23 _BitInt literals by default.)

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 2]
```diff
@@ -4121,6 +4121,13 @@ Value *ScalarExprEmitter::GetWidthMinusOneValue(Value* LHS,Value* RHS) {
     Ty = cast<llvm::IntegerType>(VT->getElementType());
   else
     Ty = cast<llvm::IntegerType>(LHS->getType());
+  // Testing with small _BitInt types has shown that Ty->getBitwidth() - 1
```
Comment (bjope) [inline clang/lib/CodeGen/CGExprScalar.cpp:4124]: Prefer if the code comment just help describe what it is doing, and possibly why here.
IMO, the "Testing with small _BitInt types has shown..." part is not really that interesting as a code comment.

One idea is to rename the `GetWidthMinusOneValue` helper function as we slightly change what it does.
It's more like a GetMaximumShiftAmount kind of helper. And there should be an update function description that describe a bit more about what is going on. I'm not sure why this static function is declared inside ScalarExprEmitter but the current description is far away at line 776.

It could say something like this:
Get a maximum legal shift exponent given a shift operation shifting the value LHS by RHS steps. The result type is given by RHS. The scalar bit width of the LHS value gives an upper bound on the shift exponent as it is considered illegal to shift more steps than "width minus one". If that value does not fit in the result type, then return an unsinged max for the result type.

File: clang/test/CodeGen/ubsan-shift-bitint.c [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+// Checking that the code generation is using the unextended/untruncated
+// exponent values and capping the values accordingly
+
+// CHECK-LABEL: define{{.*}} i32 @test_left_variable
+int test_left_variable(unsigned _BitInt(5) b, unsigned _BitInt(2) e) {
+  // CHECK: [[E_REG:%.+]] = load [[E_SIZE:i2]]
+  // CHECK: icmp ule [[E_SIZE]] [[E_REG]], -1
```
Comment (bjope) [inline clang/test/CodeGen/ubsan-shift-bitint.c:9]: So this test case show something that we perhaps should follow up an optimize later.
Not sure if the idea is to make the frontend simple at let the middle end optimize it away, but it is a bit stupid to emit the check here when comparing with -1.

**Comment by rjmccall** [comment]
> One thing I'll preemptively address is I didn't know where to put the new unit testing - creating a separate file seems a little heavy handed but I see that there's a test for UBSan shift generation (`clang/test/CodeGen/ubsan-shift.c`) and one for UBSan + _BitInt (`clang/test/CodeGen/ext-int-sanitizer.cpp`). Both seem equally "valid" but neither seem to test in the same way that I'm trying to test these changes. Advice on this would be appreciated.

Either one is fine as long as you aren't having to narrow the portability of a test case in order to use `_BitInt` in it.

Patch generally LGTM.

File: clang/test/CodeGen/ubsan-shift-bitint.c (hunk 1 above)
Comment (AdamMagierFOSS) [reply clang/test/CodeGen/ubsan-shift-bitint.c]: Sounds good, thank you for the recommendation!

File: clang/lib/CodeGen/CGExprScalar.cpp (hunk 2 above)
Comment (AdamMagierFOSS) [reply clang/lib/CodeGen/CGExprScalar.cpp]: I've renamed the function to be more accurate, but to keep a consistent style with the surrounding code I've not put a formal function description and instead kept the explanatory comment (though rewriting it to not include mentions of _BitInt).

File: clang/test/CodeGen/ubsan-shift-bitint.c (hunk 3 above)
Comment (AdamMagierFOSS) [reply clang/test/CodeGen/ubsan-shift-bitint.c:9]: I tried to include this type of optimization in this patch but there's an assert that expects a check to be generated when the shift-exponent check is enabled. I suppose it wouldn't be too difficult to refactor this but from what I can tell none of the UBSan checks are really optimized in this way and instead rely on the middle end to optimize this out (e.g. the array-bounds check still generates a check on an array of size 256 when indexing with `uint8_t`). Don't know how much of an impact this type of pre-emptive optimization would have either.

**Comment by AdamMagierFOSS** [comment]
> > One thing I'll preemptively address is I didn't know where to put the new unit testing - creating a separate file seems a little heavy handed but I see that there's a test for UBSan shift generation (`clang/test/CodeGen/ubsan-shift.c`) and one for UBSan + _BitInt (`clang/test/CodeGen/ext-int-sanitizer.cpp`). Both seem equally "valid" but neither seem to test in the same way that I'm trying to test these changes. Advice on this would be appreciated.
> 
> Either one is fine as long as you aren't having to narrow the portability of a test case in order to use `_BitInt` in it.
> 
> Patch generally LGTM.

After thinking about it some more maybe it would be best to keep this test its own file. The other two tests check the optimized code but in this test I explicitly want to test the unoptimized code to make sure the base code generation is going as anticipated. The way I understand it, either I include these test cases in the existing tests and there's a disconnect in how the "first part" of the test gets performed vs the "second part" of the test or I keep the test separate. Unless there's a strong opinion otherwise I think this would be the best way forward.

**Review by bjope — APPROVED** [review]
LG
