### PR TITLE
`clangd`: support `-stdlib=` flags from `compile_commands.json`.

### LINKED ISSUE #1784: SystemIncludesExtractor stripping `-stdlib` with `-query-driver`
Very similar to #1410 but for a different flag - the `-stdlib=libc++` flag to `clang` affects the system include location, but is stripped by `SystemIncludesExtractor` when using `query-driver`. I have a patch which keeps the `stdlib` flag in https://github.com/llvm/llvm-project/compare/main...cjc25:llvm-project:clangd-stdlib-support. Let me know if there are any reasons _not_ to send it as a pull request!

--

I built `clang`, `clangd`, `libc++abi`, and `lib++` from llvm-project/llvm commit eab5d337f0f62828a991ad7ed7e4257735c48e11. The following is a pretty small repro:

```
cjc25@host:~/src/bug-report$ cat bug-repro.cc 
#include <semaphore> // On my machine, present for clang libc++, but not libstdc++.
int main(int argc, char** argv) {
    std::counting_semaphore<> c{2};
    c.acquire();
    return 0;
}
cjc25@host:~/src/bug-report$ ../llvm/build/bin/clang -x c++ -stdlib=libstdc++ -lstdc++ -rpath ../llvm/build/lib/x86_64-unknown-linux-gnu/ -- bug-repro.cc
bug-repro.cc:1:10: fatal error: 'semaphore' file not found
    1 | #include <semaphore> // On my machine, present for clang libc++, but not libstdc++.
      |          ^~~~~~~~~~~
1 error generated.
cjc25@host:~/src/bug-report$ ../llvm/build/bin/clang -x c++ -stdlib=libc++ -lc++ -rpath ../llvm/build/lib/x86_64-unknown-linux-gnu/ -- bug-repro.cc
cjc25@host:~/src/bug-report$ echo $?
0
```

With an unmodified clangd:
```
cjc25@host:~/src/bug-report$ ../llvm/build/bin/clangd --query-driver=** --check=bug-repro.cc
I[21:41:16.022] clangd version 18.0.0 (https://github.com/llvm/llvm-project eab5d337f0f62828a991ad7ed7e4257735c48e11)
I[21:41:16.022] Features: linux
I[21:41:16.022] PID: 29892
I[21:41:16.022] Working directory: /home/cjc25/src/bug-report
I[21:41:16.022] argv[0]: ../llvm/build/bin/clangd
I[21:41:16.022] argv[1]: --query-driver=**
I[21:41:16.022] argv[2]: --check=bug-repro.cc
I[21:41:16.022] Entering check mode (no LSP server)
I[21:41:16.022] Testing on source file /home/cjc25/src/bug-report/bug-repro.cc
I[21:41:16.022] Loading compilation database...
I[21:41:16.023] Loaded compilation database from /home/cjc25/src/bug-report/compile_commands.json
I[21:41:16.053] System includes extractor: successfully executed /home/cjc25/src/bug-report/../llvm/build/bin/clang
        got includes: "/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10, /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10, /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/backward, /usr/local/include, /usr/include/x86_64-linux-gnu, /usr/include"
        got target: "x86_64-unknown-linux-gnu"
I[21:41:16.053] Compile command from CDB is: [/home/cjc25/src/bug-report] ../llvm/build/bin/clang -stdlib=libc++ -lc++ -rpath ../llvm/build/lib/x86_64-unknown-linux-gnu/ -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10 -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10 -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/backward -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include --target=x86_64-unknown-linux-gnu -resource-dir=/home/cjc25/src/llvm/build/lib/clang/18 -- /home/cjc25/src/bug-report/bug-repro.cc
I[21:41:16.053] Parsing command...
I[21:41:16.054] internal (cc1) args are: -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name bug-repro.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/cjc25/src/bug-report -fcoverage-compilation-dir=/home/cjc25/src/bug-report -resource-dir /home/cjc25/src/llvm/build/lib/clang/18 -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10 -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10 -isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/backward -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include -internal-isystem ../llvm/build/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -internal-isystem ../llvm/build/bin/../include/c++/v1 -internal-isystem /home/cjc25/src/llvm/build/lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/cjc25/src/bug-report/bug-repro.cc
I[21:41:16.054] Building preamble...
I[21:41:16.187] Built preamble of size 2876640 for file /home/cjc25/src/bug-report/bug-repro.cc version null in 0.13 seconds
I[21:41:16.187] Indexing headers...
E[21:41:16.230] [ambiguous_reference] Line 1: in included file: reference to 'integral_constant' is ambiguous
E[21:41:16.230] [fatal_too_many_errors] Line 1: too many errors emitted, stopping now
I[21:41:16.230] Building AST...
I[21:41:16.233] Indexing AST...
I[21:41:16.233] Building inlay hints
I[21:41:16.233] Building semantic highlighting
I[21:41:16.233] Testing features at each token (may be slow in large files)
I[21:41:16.236] Found definition heuristically in index for acquire
I[21:41:16.236] Found definition heuristically in index for acquire
I[21:41:16.236] All checks completed, 2 errors
```

With a patched clangd:

```
cjc25@host:~/src/bug-report$ ../llvm/build/bin/clangd --query-driver=** --check=bug-repro.cc
I[22:32:38.249] clangd version 18.0.0 (https://github.com/llvm/llvm-project bbb699071d9a4be996fcdf0dcb605fb42e74c0e6)
I[22:32:38.249] Features: linux
I[22:32:38.249] PID: 19073
I[22:32:38.249] Working directory: /home/cjc25/src/bug-report
I[22:32:38.249] argv[0]: ../llvm/build/bin/clangd
I[22:32:38.249] argv[1]: --query-driver=**
I[22:32:38.249] argv[2]: --check=bug-repro.cc
I[22:32:38.249] Entering check mode (no LSP server)
I[22:32:38.249] Testing on source file /home/cjc25/src/bug-report/bug-repro.cc
I[22:32:38.249] Loading compilation database...
I[22:32:38.250] Loaded compilation database from /home/cjc25/src/bug-report/compile_commands.json
I[22:32:38.280] System includes extractor: successfully executed /home/cjc25/src/bug-report/../llvm/build/bin/clang
        got includes: "/home/cjc25/src/llvm/build/bin/../include/x86_64-unknown-linux-gnu/c++/v1, /home/cjc25/src/llvm/build/bin/../include/c++/v1, /usr/local/include, /usr/include/x86_64-linux-gnu, /usr/include"
        got target: "x86_64-unknown-linux-gnu"
I[22:32:38.280] Compile command from CDB is: [/home/cjc25/src/bug-report] ../llvm/build/bin/clang -stdlib=libc++ -lc++ -rpath ../llvm/build/lib/x86_64-unknown-linux-gnu/ -isystem /home/cjc25/src/llvm/build/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -isystem /home/cjc25/src/llvm/build/bin/../include/c++/v1 -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include --target=x86_64-unknown-linux-gnu -resource-dir=/home/cjc25/src/llvm/build/lib/clang/18 -- /home/cjc25/src/bug-report/bug-repro.cc
I[22:32:38.280] Parsing command...
I[22:32:38.281] internal (cc1) args are: -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name bug-repro.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/cjc25/src/bug-report -fcoverage-compilation-dir=/home/cjc25/src/bug-report -resource-dir /home/cjc25/src/llvm/build/lib/clang/18 -isystem /home/cjc25/src/llvm/build/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -isystem /home/cjc25/src/llvm/build/bin/../include/c++/v1 -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include -internal-isystem ../llvm/build/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -internal-isystem ../llvm/build/bin/../include/c++/v1 -internal-isystem /home/cjc25/src/llvm/build/lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/cjc25/src/bug-report/bug-repro.cc
I[22:32:38.281] Building preamble...
I[22:32:38.404] Built preamble of size 2914372 for file /home/cjc25/src/bug-report/bug-repro.cc version null in 0.12 seconds
I[22:32:38.404] Indexing headers...
I[22:32:38.439] Building AST...
I[22:32:38.443] Indexing AST...
I[22:32:38.443] Building inlay hints
I[22:32:38.443] Building semantic highlighting
I[22:32:38.443] Testing features at each token (may be slow in large files)
I[22:32:38.447] All checks completed, 0 errors
```

Note that while this check command reports ambiguous headers, in LSP via VSCode it appears not to find the libc++ headers at all (LSP reporting that `<semaphore>` was missing, despite a working build which matched `compile_commands.json`, was how I found this issue in the first place).

I can force check to look the same as LSP by modifying the `compiler_commands.json` to exclude `-stdlib=libc++` (which doesn't compile). Then it reports the missing `<semaphore>` header I expected. I don't fully understand where check observes `-stdlib=libc++` to add headers in addition to the ones queried from the driver. It looks like it'd be where check builds the CC1 invocation, but I can't find where it'd add new system headers. Teaching query-driver to pass `-stdlib` gets rid of the error in both the check and LSP, but if someone already knows where those -internal-isystem arguments are coming from I'd love to learn before merging this patch!

### PR DESCRIPTION
**Pull request by cjc25**
The `--stdlib` flag can affect the system headers used by `clang` during compilation. By default, `clang` will use the platform-installed C++ standard headers, but with `--stdlib=libc++`, `clang` can use headers included in the distribution for its `libc++` implementation.

Prior to this patch, if `compile_commands.json` specified `-stdlib=libc++` or an equivalent form and `--query-driver` took effect, `clangd` would ignore `stdlib` and index based on the platform's headers. When these mismatch, e.g. due to version differences, `clangd`'s completions and the actual compilation can differ.

fixes clangd/clangd#1784

### CODE REVIEW

File: clang-tools-extra/clangd/SystemIncludeExtractor.cpp [hunk 1]
```diff
@@ -203,6 +214,7 @@ template <> struct DenseMapInfo<DriverArgs> {
         Val.Driver,
         Val.StandardIncludes,
         Val.StandardCXXIncludes,
+        Val.Stdlib,
```
Comment (HighCommander4) [inline clang-tools-extra/clangd/SystemIncludeExtractor.cpp:217]: nit: it looks like the previous patch which introduced `Target` forgot to add it here, could you add please?

Comment (cjc25) [reply clang-tools-extra/clangd/SystemIncludeExtractor.cpp]: Done, and resorted these to match the order in `DriverArgs` definition so it'll be easier to tell when things are missing in the future.

**Review by HighCommander4 — APPROVED** [review]
LGTM
