### PR TITLE
[clang] Fix segmentation fault caused by stack overflow on deeply nested expressions

### LINKED ISSUE #111699: Clang crashes segmentation fault due to stack overflow on deeply nested expressions
For example, if you do ~10,000 nested expression calls like this one:

`a.foo().foo().foo() ...`

You will get a segmentation fault crash.

### PR DESCRIPTION
**Pull request by bricknerb**
Done by calling clang::runWithSufficientStackSpace().
Added CodeGenModule::runWithSufficientStackSpace() method similar to the one in Sema to provide a single warning when this triggers
Fixes: #111699

### CODE REVIEW

File: clang/test/CodeGen/deeply-nested-expressions.cpp [hunk 1]
```diff
@@ -0,0 +1,1013 @@
...
+class AClass {
+public:
+  AClass() {}
+  AClass &foo() { return *this; }
+};
+
+void test_bar() {
+  AClass a;
+  // expected-warning@* {{stack nearly exhausted; compilation time may suffer, and crashes due to stack overflow are likely}}
+  a.foo().foo().foo().foo().foo().foo().foo().foo().foo().foo().foo().foo()
```
Comment (ilya-biryukov) [inline clang/test/CodeGen/deeply-nested-expressions.cpp:12]: Could we use preprocessor to reduce the size of the file?
The typical trick I use is:

```cpp
#define CALLS1 .foo().foo().foo().foo().foo().foo().foo().foo().foo().foo()
#define CALLS2 CALLS1().CALLS1().CALLS1().CALLS1(). ...
...
#define CALLS${N} CALLS${N-1}....

a.CALLS();
```

File: clang/lib/CodeGen/CGExpr.cpp [hunk 2]
```diff
@@ -5817,7 +5817,10 @@ LValue CodeGenFunction::EmitHLSLArrayAssignLValue(const BinaryOperator *E) {
 
 LValue CodeGenFunction::EmitCallExprLValue(const CallExpr *E,
                                            llvm::CallBase **CallOrInvoke) {
-  RValue RV = EmitCallExpr(E, ReturnValueSlot(), CallOrInvoke);
```
Comment (ilya-biryukov) [inline clang/lib/CodeGen/CGExpr.cpp:5820]: Would it be better to wrap a more generic function? I'm thinking about `EmitLValue`

```cpp
LValue CodeGenFunction::EmitLValue(const Expr *E) {
  LValue R;
  R = runWithSufficientStackSpace([] { R = EmitLValueImpl(E); }, ...);
  return R;
}

// The current function...
LValue CodeGenFunction::EmitLValueImpl(const Expr *E) {
  ApplyDebugLocation DL(*this, E);
  switch (E->getStmtClass()) {
  ...
}
```

That way we can cover a broader class of recursive expressions. I'm not sure the coverage is complete,
but should probably be quite good for a start.
(We could also add a few tests for deep expressions that don't involve calls).

**Review by ilya-biryukov — COMMENTED** [review]
I have a few suggestions, but definitely support this.

I've also added a few folks suggested by GitHub as reviewers to make sure we have coverage of someone who looks at CodeGen.

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 1 above)
Comment (bricknerb) [reply clang/test/CodeGen/deeply-nested-expressions.cpp:12]: Sure, I considered it while writing this.
The reason I didn't do it is that I feel that while DRY is important, in this case it makes it less readable harder to understand (less DAMP), even if the end result is shorter.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 2 above)
Comment (bricknerb) [reply clang/lib/CodeGen/CGExpr.cpp]: Done.

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 1 above)
Comment (rnk) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: FWIW I like the pre-processor version of this too. I appreciate that size isn't always the most important dimension of testing, but I prefer the tradeoff for the smaller test here.

Comment (ilya-biryukov) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: I can understand the desire to keep important information visible, but I find the fact that humans have a limited ability to comprehend large chunks of information important.

For a test like this, the important information for me is:
- how deep is the expression,
- what kind of an expression it is.

The vast size of the file makes it harder, not simpler, to get that information and it also requires extra actions (going to the end of the file) to make sure there isn't something else that the reader needs to know.

Preprocessor is generally very reliable and well-understood, so I'd still lean towards the smaller version here.

Comment (ilya-biryukov) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: It's not that I disagree with DAMP or always prefer DRY, I am just trying to make the best trade-off in each situation and also feel the right trade-off one here is closer to DRY.

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 3]
```diff
@@ -1596,6 +1597,19 @@ void CodeGenModule::ErrorUnsupported(const Decl *D, const char *Type) {
   getDiags().Report(Context.getFullLoc(D->getLocation()), DiagID) << Msg;
 }
 
+void CodeGenModule::warnStackExhausted(SourceLocation Loc) {
+  // Only warn about this once.
+  if (!WarnedStackExhausted) {
+    getDiags().Report(Loc, diag::warn_stack_exhausted);
+    WarnedStackExhausted = true;
+  }
+}
```
Comment (cor3ntin) [inline clang/lib/CodeGen/CodeGenModule.cpp:1606]: Is there a way to avoid the duplication with Sema here?

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: In the past we approved these sort of changes without tests, there are no good ways to test them reliably.

Comment (bricknerb) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: Thanks for the feedback!
I've changed the test to use macros to make it shorter.
I also removed the warning check, since it's platform dependent and hard to maintain.

File: clang/test/CodeGen/deeply-nested-expressions.cpp [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+#define CALLS2048 CALLS1024().CALLS1024
+#define CALLS4096 CALLS2048().CALLS2048
+#define CALLS8192 CALLS4096().CALLS4096
+#define CALLS16384 CALLS8192().CALLS8192
+#define CALLS32768 CALLS16384().CALLS16384
+
+void test_bar() {
+  AClass a;
+  a.CALLS32768();
+}
```
Comment (ilya-biryukov) [inline clang/test/CodeGen/deeply-nested-expressions.cpp:29]: NIT: let's add a trailing newline to this file to make GitHub happy (it's also technically required by C++ standard, although I don't think any compiler actually cares in practice)

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 3 above)
Comment (ilya-biryukov) [reply clang/lib/CodeGen/CodeGenModule.cpp:1606]: SGTM and also feels like something that we could do in a follow-up, even if the code here is duplicated for some short period of time.

I suspect there's some wiring up to figure out for sharing this in the same class, so it'd be good to land this while that's still happening.

**Review by ilya-biryukov — APPROVED** [review]
LGTM, I feel we could land this right away and figure out how to share with Sema in a follow-up.

Hopefully @cor3ntin did not mean to block this until that happens, but let's not hold off the follow-up for long to make sure we don't make this a permanent state.

File: clang/test/CodeGen/deeply-nested-expressions.cpp [hunk 5]
```diff
@@ -0,0 +1,29 @@
+// RUN: %clang_cc1 %s -emit-llvm -o - -Wstack-exhausted
```
Comment (ilya-biryukov) [inline clang/test/CodeGen/deeply-nested-expressions.cpp:1]: Maybe add a mention that we cannot `-verify` the warning because it's platform-specific (Windows does not fire it), but we still want to make sure the compiler can handle the deeply nested expressions.

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 1 above)
Comment (ilya-biryukov) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: Having a check that the compiler does not crash seems better than nothing, so the test in its current state seems useful.

However, @bricknerb please check it runs quickly. Another failure mode we've had before is that we would add slow tests and everyone running tests would wait on them, even when they're testing a relatively small thing.

We've had ideas about making the stack size we warn at configurable (either through flags or in only in C++ APIs to allow unit-testing). It might be a way to test this long-term, but it's probably an even bigger thing than unifying the warning with Sema, so I don't necessarily feel like going there unless people have spare time (I've wanted to do this myself, but never found the time)

**Comment by cor3ntin** [comment]
I'm still concerned that the test is going to be super flaky - I would remove it and mention the issue this fixes by adding a comment where runWithSufficientStackSpace is called

**Review by ilya-biryukov — CHANGES_REQUESTED** [review]
Marking with "request changes" to ask removing the test per @cor3ntin's comments

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 4 above)
Comment (bricknerb) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: Done.

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 1 above)
Comment (bricknerb) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: Resolving since we decided to remove this test.

File: clang/test/CodeGen/deeply-nested-expressions.cpp (hunk 5 above)
Comment (bricknerb) [reply clang/test/CodeGen/deeply-nested-expressions.cpp]: Resolving since we decided to remove this test.

**Review by ilya-biryukov — APPROVED** [review]
LGTM
