### PR TITLE
[clang-tidy] insert ``static`` keyword in correct position for misc-use-internal-linkage

### LINKED ISSUE #108760: `misc-use-internal-linkage` fixhint incorrect
`const int * f() {}`
will be fixed as
`const static int * f() {}`

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #108760

### CODE REVIEW

**Comment by HerrCai0907** [comment]
friendly ping @5chmidti and other person who has time to review PR.

File: clang-tools-extra/clang-tidy/misc/UseInternalLinkageCheck.cpp [hunk 1]
```diff
@@ -110,10 +113,36 @@ static constexpr StringRef Message =
     "%0 %1 can be made static or moved into an anonymous namespace "
     "to enforce internal linkage";
 
+static SourceLocation getQualifiedTypeStartLoc(SourceLocation L,
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/misc/UseInternalLinkageCheck.cpp:116]: You could use `FD/VD->getInnerLocStart()` instead of implementing this function. `getInnerLocStart` will return the first location after the things related to templates. 

```diff
-void func_cpp_inc();                                                
+static void func_cpp_inc();                                                                                                                                                                                                                                                                                                 //                                                                                                                                                                                                                                                                                                                         
 //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 #define NDS [[nodiscard]]                                        
 #define NNDS                                                                                                                                                                                                                                                                                                               
                                              
-[[nodiscard]] void func_cpp_inc2();                                                                                                                                                                                                                                                                                        
+[[nodiscard]] static void func_cpp_inc2();                        
 //                                                                                                                                                           
 //                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                            
-NDS void func_cpp_inc3();                                                                                                                                                                                                                                                                                                  
+NDS static void func_cpp_inc3();                                                                                                                                                                                                                                                                                           
 //                                                                                                                                                                                                                                                                                                                         
 //                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                            
-NNDS void func_cpp_inc4();                                                                                                                                                                                                                                                                                                 
+NNDS static void func_cpp_inc4();                                                                                                                            
 //                                                                                                                                                                                                                                                                                                                         
 //                                                                                                                                                                                                                                                                                                                         
```

Admittedly, this depends on attribute locations not being modeled right now, so this could break in the future (maybe add the above examples to the tests).

**Review by SimplyDanny — APPROVED** [review]
