### PR TITLE
 [Clang][AST] Introduce `ExplicitInstantiationDecl` to preserve source info and fix diagnostic locations 

### LINKED ISSUE #52659: clang AST: SourceRange for explicit instantiation cannot be obtained.
**Current behavior:**

For the following file:
```{.cpp}
1 //file my_func.cpp
2 void template<typename Bar> foo(Bar& bar) {
3     // some code
4 }
5 template void foo<double>(double&);
```
one cannot obtain the source range for the explicit instantiation.
From the class `clang::FunctionTemplateSpecializationInfo`, one can get the point of instantiations which will be in this case line 5 and column 15 (the beginning of foo).
However there is no way to obtain the complete SourceRange of the instantiation expression.

**Expected behavior:**

A method similar to `getSourceRange()` in `class clang::FunctionTemplateSpecializationInfo` to obtain the full SourceRange.

**Related links:**
SO: https://stackoverflow.com/questions/70095653/get-the-sourcerange-of-explicit-template-instantiations-using-clang-ast-library
cfe-dev mailing List: https://lists.llvm.org/pipermail/cfe-dev/2021-November/069442.html

### LINKED ISSUE #115418: [clang] [clangd] Missing information about explicit instantiation of function template
```cpp
namespace test {
template <typename T>
void foo() {}
}

struct X {};

template void test::f^oo<X>();
```

Currently, if trigger go-to-definition at the location of `^`, clangd will give no response. And the tokens in the explicit instantiation are 
 also not highlighted.  After some investigation, I found that the underlying cause is that the Clang frontend doesn't store the information about explicit instantiation of function templates.
 
 Dump the AST of above code

 ```cpp
 |-NamespaceDecl 0xd083678 <<source>:1:1, line:4:1> line:1:11 test
| `-FunctionTemplateDecl 0xd0838e8 <line:2:1, line:3:13> col:6 foo
|   |-TemplateTypeParmDecl 0xd083708 <line:2:11, col:20> col:20 typename depth 0 index 0 T
|   |-FunctionDecl 0xd083838 <line:3:1, col:13> col:6 foo 'void ()'
|   | `-CompoundStmt 0xd0839c8 <col:12, col:13>
|   `-FunctionDecl 0xd083d18 <col:1, col:13> col:6 foo 'void ()' explicit_instantiation_definition
|     |-TemplateArgument type 'X'
|     | `-RecordType 0xd083aa0 'X'
|     |   `-CXXRecord 0xd0839f8 'X'
|     `-CompoundStmt 0xd0839c8 <col:12, col:13>
`-CXXRecordDecl 0xd0839f8 <line:6:1, col:11> col:8 referenced struct X definition
  ```

As you can see, the decl from explicit instantiation is only added to its semantic context but not to its lexical context.

If use a visitor to further explore:

```cpp
bool VisitFunctionTemplateDecl(clang::FunctionTemplateDecl* decl) {
    for(auto spec: decl->specializations()) {
        spec->getLocation().dump(srcMgr);
        spec->getFunctionTypeLoc().getReturnLoc().getLocalSourceRange().dump(srcMgr)
        spec->getQualifierLoc().getSourceRange().dump(srcMgr);
        auto info = spec->getTemplateSpecializationInfo();
        info->PointOfInstantiation.dump(srcMgr);
        llvm::outs() << info->TemplateArguments << "\n";
        llvm::outs() << info->TemplateArgumentsAsWritten << "\n";
    }
    return true;
}
```

The output is 
```
test.cpp:3:6
<test.cpp:3:1>
<<invalid sloc>>
test.cpp:8:21
0x564cf04d7560
0x0
```

Only instantiation point is recorded correctly, all other information is from primary template. But for explicit specializations, the information is recorded properly.

### PR DESCRIPTION
**Pull request by 16bit-ykiko**
This is the initial fix of https://github.com/llvm/llvm-project/issues/191442. Following the discussion here https://github.com/llvm/llvm-project/issues/115418#issuecomment-2467017012.

- Fix #21040
- Fix #52659
- Fix #115418
- Fix #14230
- Fix #21133

### Description

This PR introduces a new AST node, `ExplicitInstantiationDecl`, to systematically fix the long-standing issue of missing or incorrect source location information for explicit template instantiations. 

#### Background & The Problem
Historically, Clang's AST lacked a dedicated node to represent the lexical occurrence of an explicit instantiation statement. Instead, `Sema` tried to shoehorn this information into existing specialization nodes (e.g., `FunctionDecl`, `VarTemplateSpecializationDecl`) or simply returned `nullptr`. 

This resulted in fragmented behavior across the seven instantiable entity types:
* Function & Member Function Templates: Returned `nullptr`, completely losing `SourceRange` and `NestedNameSpecifier` information.
* Member Functions & Static Data Members: Mutated existing nodes in-place. Consequently, multiple `template` or `extern template` declarations in the same file would overwrite each other's source locations.
* Variable Templates: Suffered from `dyn_cast` bugs and dropped NNS information.

#### Design Trade-offs Evaluated

Before settling on the current design, I evaluated a mixed redeclaration-chain approach (similar to how explicit *specializations* are handled, creating new `FunctionDecl` nodes and stitching them into the redecl chain). However, this approach had significant flaws:
1. Inconsistency: It couldn't be cleanly applied to member functions or static data members due to `DeclContext` constraints (e.g., a member function shouldn't lexically reside in a namespace `DeclContext`, but placing it in the class context would pollute member lookup).
2. Fragility: It required bypassing standard `FoldingSet` mechanisms (`setFunctionTemplateSpecialization`).
3. Lookup Pollution: Injecting new `NamedDecl` nodes purely for instantiations risked breaking downstream `ASTMatcher`s and altering name lookup behavior.

To avoid these pitfalls, this PR introduces `ExplicitInstantiationDecl` as a **purely lexical annotation node**.

**Key Design Characteristics:**
1. Inherits from `Decl`, not `NamedDecl`: This is the most crucial design choice. Much like `StaticAssertDecl` or `FriendDecl`, this node lives in a `DeclContext` (making it traversable by `RecursiveASTVisitor` and visible in AST dumps) but remains completely invisible to C++ name lookup. It does not interfere with overload resolution or lookup tables.
2. Unified Representation: A single node type now covers all seven entity types. It holds a pointer (`Specialization`) to the underlying instantiated declaration, unifying how functions, variables, classes, and members are handled.
3. Lexical Fidelity: The node resides in the enclosing namespace or Translation Unit where the explicit instantiation was actually written, perfectly preserving the `SourceRange`, `NestedNameSpecifierLoc`, and the exact locations of the `template` and `extern` keywords.

Assisted-by: Claude Code (Anthropic) — used for test writing and checking test results

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -2101,6 +2101,14 @@ Decl *TemplateDeclInstantiator::VisitStaticAssertDecl(StaticAssertDecl *D) {
       InstantiatedMessageExpr.get(), D->getRParenLoc(), D->isFailed());
 }
 
+Decl *TemplateDeclInstantiator::VisitExplicitInstantiationDecl(
+    ExplicitInstantiationDecl *D) {
+  // ExplicitInstantiationDecl is a source-info-only node and should not
+  // appear inside a template pattern. Nothing to instantiate.
+  llvm_unreachable("ExplicitInstantiationDecl should not be instantiated");
+  return nullptr;
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]:
```suggestion
```

Redundant with the unreachable, which is not like an assert (this is not disabled in release builds).

File: clang/include/clang/AST/DeclTemplate.h [hunk 2]
```diff
@@ -3405,6 +3405,122 @@ getReplacedTemplateParameter(Decl *D, unsigned Index);
 /// If we have an implicit instantiation, adjust 'D' to refer to template.
 const Decl &adjustDeclToTemplate(const Decl &D);
 
+/// Represents an explicit instantiation of a template entity in source code.
+///
+/// This node records source location information for an explicit instantiation
+/// statement. It does not participate in name lookup (inherits from Decl, not
+/// NamedDecl), and does not affect code generation. The underlying
+/// specialization decl (FunctionDecl, VarDecl, CXXRecordDecl, etc.) continues
+/// to handle all semantic and codegen responsibilities.
```
Comment (mizvekov) [inline clang/include/clang/AST/DeclTemplate.h]: I feel like most of this block is fine as a PR description, but probably not helpful to leave as a comment,
due to the obviousness.

For example it has wording that alludes to the fact the decl kind didn't exist in the past (ie 'continues'),
which is not something we would say in documentation (but would say in a change log).

File: clang/include/clang/AST/DeclTemplate.h [hunk 3]
```diff
@@ -3405,6 +3405,122 @@ getReplacedTemplateParameter(Decl *D, unsigned Index);
...
+                            const ASTTemplateArgumentListInfo *ArgsAsWritten,
+                            SourceLocation NameLoc,
+                            TypeSourceInfo *TypeAsWritten,
+                            TemplateSpecializationKind TSK)
+      : Decl(ExplicitInstantiation, DC, TemplateLoc),
+        Specialization(Specialization), Range(Range), ExternLoc(ExternLoc),
+        TagKWLoc(TagKWLoc), QualifierLoc(QualifierLoc),
+        TemplateArgsAsWritten(ArgsAsWritten), NameLoc(NameLoc),
+        TypeAsWritten(TypeAsWritten), TSK(TSK) {
+    assert((TSK == TSK_ExplicitInstantiationDeclaration) ==
```
Comment (mizvekov) [inline clang/include/clang/AST/DeclTemplate.h]: We could probably assert more here, if you are already doing it.

For example, we should always have a NameLoc, TemplateLoc, and the angle brackets at least I think.

File: clang/include/clang/AST/DeclTemplate.h [hunk 4]
```diff
@@ -3405,6 +3405,122 @@ getReplacedTemplateParameter(Decl *D, unsigned Index);
...
+///   extern template struct ns::S<int>;      // class template (extern)
+///   template int ns::bar<int>;              // variable template
+///   template void ns::S<int>::method(int);  // member function
+/// \endcode
+class ExplicitInstantiationDecl : public Decl {
+  /// The underlying specialization being explicitly instantiated.
+  NamedDecl *Specialization = nullptr;
+
+  /// The source range of the entire explicit instantiation statement.
+  SourceRange Range;
```
Comment (mizvekov) [inline clang/include/clang/AST/DeclTemplate.h]: We can avoid storing this and computing it from the source locations we have.

I am not thinking about only the space savings, which are a bonus, but because that's one less parameter for the user and one less thing that could be left inconsistent.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 5]
```diff
@@ -9314,10 +9314,40 @@ static void StripImplicitInstantiation(NamedDecl *D, bool MinGW) {
...
+/// explicit template instantiation statement, and add it to \p CurContext.
+static void addExplicitInstantiationDecl(
+    ASTContext &Context, DeclContext *CurContext, const CXXScopeSpec &SS,
+    SourceLocation EndLoc, NamedDecl *Spec, SourceLocation ExternLoc,
+    SourceLocation TemplateLoc, SourceLocation TagKWLoc,
+    const ASTTemplateArgumentListInfo *ArgsAsWritten, SourceLocation NameLoc,
+    TypeSourceInfo *TypeAsWritten, TemplateSpecializationKind TSK) {
+  NestedNameSpecifierLoc QualifierLoc;
+  if (SS.isNotEmpty())
+    QualifierLoc = SS.getWithLocInContext(Context);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp]:
```suggestion
  NestedNameSpecifierLoc QualifierLoc = SS.getWithLocInContext(Context);
```
I don't think this needs to be guarded here.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 6]
```diff
@@ -10827,8 +10869,19 @@ DeclResult Sema::ActOnExplicitInstantiation(Scope *S,
...
+        ArgsAsWritten = VTSD->getTemplateArgsAsWritten();
+      addExplicitInstantiationDecl(Context, CurContext, D.getCXXScopeSpec(),
+                                   D.getSourceRange().getEnd(), Prev, ExternLoc,
+                                   TemplateLoc, SourceLocation(), ArgsAsWritten,
+                                   D.getIdentifierLoc(), T, TSK);
+      // Don't return the EID to the Parser — doing so would trigger
+      // unrelated semantic actions (e.g. access checks via
+      // FinalizeDeclaration).
+      return (Decl *)nullptr;
+    }
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp]: You don't need to introduce this scope since we are at the end of the outer scope anyway.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 7]
```diff
@@ -11065,8 +11127,19 @@ DeclResult Sema::ActOnExplicitInstantiation(Scope *S,
...
+      ArgsAsWritten =
+          ASTTemplateArgumentListInfo::Create(Context, TemplateArgs);
+    addExplicitInstantiationDecl(Context, CurContext, D.getCXXScopeSpec(),
+                                 D.getSourceRange().getEnd(), Specialization,
+                                 ExternLoc, TemplateLoc, SourceLocation(),
+                                 ArgsAsWritten, D.getIdentifierLoc(), T, TSK);
+    // Don't return the EID to the Parser — doing so would trigger
+    // unrelated semantic actions (e.g. access checks via FinalizeDeclaration).
+    return (Decl *)nullptr;
+  }
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp]: Ditto

**Review by mizvekov — COMMENTED** [review]
Well done, thanks!

Just a few nits here, but great work, I appreciate.

**Review by mizvekov — COMMENTED** [review]
It would also be worth adding support for ast-print with a few tests, that looks fairly simple for this declaration.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 8]
```diff
@@ -10827,8 +10865,16 @@ DeclResult Sema::ActOnExplicitInstantiation(Scope *S,
...
+    const ASTTemplateArgumentListInfo *ArgsAsWritten = nullptr;
+    if (auto *VTSD = dyn_cast<VarTemplateSpecializationDecl>(Prev))
+      ArgsAsWritten = VTSD->getTemplateArgsAsWritten();
+    addExplicitInstantiationDecl(Context, CurContext, D.getCXXScopeSpec(), Prev,
+                                 ExternLoc, TemplateLoc, SourceLocation(),
+                                 ArgsAsWritten, D.getIdentifierLoc(), T, TSK);
+    // Don't return the EID to the Parser — doing so would trigger
+    // unrelated semantic actions (e.g. access checks via
+    // FinalizeDeclaration).
+    return (Decl *)nullptr;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp]: Do you have a test if we return something?

File: clang/lib/Sema/SemaTemplate.cpp [hunk 9]
```diff
@@ -11005,10 +11051,20 @@ DeclResult Sema::ActOnExplicitInstantiation(Scope *S,
...
+        ArgsAsWritten =
+            ASTTemplateArgumentListInfo::Create(Context, TemplateArgs);
+      addExplicitInstantiationDecl(Context, CurContext, D.getCXXScopeSpec(),
+                                   Specialization, ExternLoc, TemplateLoc,
+                                   SourceLocation(), ArgsAsWritten,
+                                   D.getIdentifierLoc(), T, TSK);
+      // Don't return the EID to the Parser — doing so would trigger
+      // unrelated semantic actions (e.g. access checks via
+      // FinalizeDeclaration).
+      return (Decl *)nullptr;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp]: ditto

File: clang/test/AST/ast-print-explicit-instantiation.cpp [hunk 10]
```diff
@@ -0,0 +1,41 @@
+// RUN: %clang_cc1 -ast-print %s -o - -std=c++17 | FileCheck %s
+
+namespace ns {
+template <typename T> struct S { T x; };
+template <typename T> void foo(T) {}
+template <typename T> T var = T();
+}
+
+// Class template explicit instantiation.
```
Comment (zyn0217) [inline clang/test/AST/ast-print-explicit-instantiation.cpp]: Can we get rid of these comments? They look useless

File: clang/test/SemaTemplate/explicit-instantiation-diag-location.cpp [hunk 11]
```diff
@@ -0,0 +1,31 @@
+// RUN: %clang_cc1 -fsyntax-only -verify %s
+
+// Verify that the "previous explicit instantiation" note points to the first
+// explicit instantiation statement, not to the implicit instantiation site.
+// This is a regression test for https://github.com/llvm/llvm-project/issues/21133
```
Comment (zyn0217) [inline clang/test/SemaTemplate/explicit-instantiation-diag-location.cpp]: We usually wrap a regression within a namespace, with the name pointing to the issue number. i.e. it should be namespace GH21133 here.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 12]
```diff
@@ -9314,10 +9314,36 @@ static void StripImplicitInstantiation(NamedDecl *D, bool MinGW) {
...
+  // Search for an ExplicitInstantiationDecl that references D. Per
+  // [temp.explicit], explicit instantiations must appear in an enclosing
+  // namespace of the template, so the EID is in D's DeclContext or an ancestor.
+  for (DeclContext *DC = D->getDeclContext(); DC; DC = DC->getParent()) {
+    for (auto *Decl : DC->decls()) {
+      if (auto *EID = dyn_cast<ExplicitInstantiationDecl>(Decl))
+        if (EID->getSpecialization() == D)
+          return EID->getTemplateLoc();
+    }
+  }
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp]: I don't think going through every declaration from their parent contexts is a good idea, it looks greatly inefficient.

File: clang/include/clang/AST/RecursiveASTVisitor.h [hunk 13]
```diff
@@ -2196,23 +2208,23 @@ bool RecursiveASTVisitor<Derived>::TraverseTemplateArgumentLocsHelper(
...
+      }                                                                        \
     }                                                                          \
                                                                                \
     if (getDerived().shouldVisitTemplateInstantiations() ||                    \
         D->getTemplateSpecializationKind() == TSK_ExplicitSpecialization) {    \
       /* Traverse base definition for explicit specializations */              \
       TRY_TO(Traverse##DECLKIND##Helper(D));                                   \
     } else {                                                                   \
-      TRY_TO(TraverseNestedNameSpecifierLoc(D->getQualifierLoc()));            \
-                                                                               \
```
Comment (zyn0217) [inline clang/include/clang/AST/RecursiveASTVisitor.h:2215]: Why this change?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 1 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: Fixed.

File: clang/include/clang/AST/DeclTemplate.h (hunk 2 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/DeclTemplate.h]: Fixed.

File: clang/include/clang/AST/DeclTemplate.h (hunk 3 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/DeclTemplate.h]: Fixed.

File: clang/include/clang/AST/DeclTemplate.h (hunk 4 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/DeclTemplate.h]: Fixed.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 5 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Fixed.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 6 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Fixed.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 7 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Fixed.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Since explicit instantiations are quite rare in the codebase and this logic is on a cold path purely for error diagnostics, I feel the current approach is likely acceptable. 

If we wanted to make this more efficient, we might have to make EID `Redeclarable` and traverse the chain instead. However, that could complicate what is currently a rather clean and straightforward patch. I'm just not sure if introducing that much complexity is worth the trade-off for such a edge case.

Additionally, in typical downstream use cases for EIDs (like in clangd), we don't really need to traverse a chain of all explicit instantiation nodes anyway.  @mizvekov  Any ideas?

File: clang/include/clang/AST/RecursiveASTVisitor.h (hunk 13 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/RecursiveASTVisitor.h:2215]: Here, the canonical decl for an explicit instantiation is `ClassTemplateSpecializationDecl` / `VarTemplateSpecializationDecl`. Before EID, RAV traversed these nodes because they served as the fallback for location info (though often inaccurately, like missing NNS).

Now that EID provides complete and accurate location info, the traversal should be centralized there. Traversing the specialization node alongside the EID causes duplicate callbacks in tools like clang-tidy (e.g., the double-warning for `avoid-c-arrays` fixed in a previous commit).

Note that we kept the `TSK_ExplicitSpecialization` branch: explicit specializations (`template<>`) don't have EIDs, so they still need to traverse their own template args.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 8 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: I tried returning EID from `ActOnExplicitInstantiation`, but it caused 13 test failures. Here are the CI results: https://github.com/llvm/llvm-project/actions/runs/24298212726/artifacts/6390095043

The failures are all access control errors on private members, e.g. explicit instantiation of private member function templates like `template void A::f<int>();`.

The root cause is in `PopParsingDeclaration` (`SemaDeclAttr.cpp`): the Parser uses a delayed diagnostic pool to accumulate access checks during parsing. When `ActOnExplicitInstantiation` looks up `A::f`, an access check is recorded in the pool because `f` is private. At the end of parsing, `PopParsingDeclaration(State, decl)` checks whether `decl` is null — if null, all delayed diagnostics are silently discarded; if non-null, they are emitted. Returning EID (non-null) causes the delayed access checks to fire, even though explicit instantiation of private members is perfectly legal (it happens at namespace scope, outside the access context).

So returning `nullptr` is the correct behavior here — it tells the Parser that there's no "new" declaration to validate.

Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: However, I agree the current code is confusing, I'm just not sure what the best fix is.

File: clang/include/clang/AST/ASTNodeTraverser.h [hunk 14]
```diff
@@ -683,6 +683,18 @@ class ASTNodeTraverser
     Visit(D->getMessage());
   }
 
+  void VisitExplicitInstantiationDecl(const ExplicitInstantiationDecl *D) {
+    // The specialization is already elsewhere in the AST; don't re-traverse it.
+    // Traverse source-location sub-nodes: template arguments and
+    // type-as-written.
+    if (const auto *ArgsAsWritten = D->getTemplateArgsAsWritten())
+      for (unsigned I = 0, E = ArgsAsWritten->NumTemplateArgs; I != E; ++I)
```
Comment (zwuis) [inline clang/include/clang/AST/ASTNodeTraverser.h]:
```cpp
for (TemplateArgumentLoc Loc : ArgsAsWritten->arguments()) {
  // ...
}
```

Use range-based `for`. Ditto elsewhere.

File: clang/lib/AST/DeclPrinter.cpp [hunk 15]
```diff
@@ -1335,6 +1336,43 @@ void DeclPrinter::VisitClassTemplateDecl(ClassTemplateDecl *D) {
...
+    printTemplateArgumentList(NameOS, ArgsAsWritten->arguments(), Policy);
+
+  if (auto *RD = dyn_cast<RecordDecl>(Spec)) {
+    Out << RD->getKindName() << " " << Name;
+  } else if (auto *FD = dyn_cast<FunctionDecl>(Spec)) {
+    FD->getReturnType().print(Out, Policy);
+    Out << " " << Name << "(";
+    for (unsigned I = 0, N = FD->getNumParams(); I < N; ++I) {
+      if (I)
+        Out << ", ";
```
Comment (zwuis) [inline clang/lib/AST/DeclPrinter.cpp]: It's up to you, but we could use `llvm::ListSeparator`.

File: clang/lib/AST/DeclPrinter.cpp [hunk 16]
```diff
@@ -1335,6 +1336,43 @@ void DeclPrinter::VisitClassTemplateDecl(ClassTemplateDecl *D) {
...
+    }
+    if (FD->isVariadic()) {
+      if (FD->getNumParams())
+        Out << ", ";
+      Out << "...";
+    }
+    Out << ")";
+  } else if (auto *TSI = D->getTypeAsWritten()) {
+    TSI->getType().print(Out, Policy, Name);
+  }
```
Comment (zwuis) [inline clang/lib/AST/DeclPrinter.cpp:1378]: Can we add 

```cpp
else {
  llvm_unreachable("...");
}
```

File: clang/lib/AST/DeclTemplate.cpp [hunk 17]
```diff
@@ -1784,3 +1784,40 @@ const Decl &clang::adjustDeclToTemplate(const Decl &D) {
...
+}
+
+SourceLocation ExplicitInstantiationDecl::getEndLoc() const {
+  if (TypeAsWritten) {
+    if (auto FTL = TypeAsWritten->getTypeLoc().getAs<FunctionTypeLoc>())
+      return FTL.getRParenLoc();
+    if (TemplateArgsAsWritten)
+      return TemplateArgsAsWritten->RAngleLoc;
+    // Static data member: end at the name.
+    return NameLoc;
```
Comment (zwuis) [inline clang/lib/AST/DeclTemplate.cpp]: Does it handle things like `int a[1];` correctly? If no, you may refer to `VarDecl::getSourceRange`.

File: clang/lib/AST/TextNodeDumper.cpp [hunk 18]
```diff
@@ -2936,6 +2936,20 @@ void TextNodeDumper::VisitAccessSpecDecl(const AccessSpecDecl *D) {
   dumpAccessSpecifier(D->getAccess());
 }
 
+void TextNodeDumper::VisitExplicitInstantiationDecl(
+    const ExplicitInstantiationDecl *D) {
+  dumpTemplateSpecializationKind(D->getTemplateSpecializationKind());
+  if (D->isExternTemplate())
+    OS << " extern";
+  OS << " template";
```
Comment (mizvekov) [inline clang/lib/AST/TextNodeDumper.cpp]: You don't need to put this here if it's not a flag conditional to anything.

File: clang/lib/AST/DeclTemplate.cpp [hunk 19]
```diff
@@ -1784,3 +1784,41 @@ const Decl &clang::adjustDeclToTemplate(const Decl &D) {
...
+  // For postfix types (arrays, function pointers) and function templates,
+  // the TypeLoc extends past the name. Cf. DeclaratorDecl::getSourceRange().
+  SourceLocation End = NameLoc;
+  if (TemplateArgsAsWritten && TemplateArgsAsWritten->RAngleLoc > End)
+    End = TemplateArgsAsWritten->RAngleLoc;
+  if (TypeAsWritten) {
+    SourceLocation TypeEnd = TypeAsWritten->getTypeLoc().getEndLoc();
+    if (TypeEnd.isValid() && TypeEnd > End)
+      End = TypeEnd;
+  }
```
Comment (mizvekov) [inline clang/lib/AST/DeclTemplate.cpp]: Not many places rely on this assumption that you can order SourceLocations, because that only works when they have the same FileID.

Formally, this could be composed from token from different files, even if it's not in any way common practice.

I think we should be able to quickly tell where the end location is supposed to come from, based on the kind of template is being instantiated.

File: clang/include/clang/AST/DeclTemplate.h [hunk 20]
```diff
@@ -3405,6 +3405,113 @@ getReplacedTemplateParameter(Decl *D, unsigned Index);
...
+  /// Location of the entity name (e.g., 'foo' in 'template void
+  /// ns::foo<int>(int)').
+  SourceLocation NameLoc;
+
+  /// Type source info for the declaration type:
+  ///   - Function templates / member functions: FunctionProtoTypeLoc with
+  ///     return type location and parameter type locations.
+  ///   - Variable templates / static data members: the declared type.
+  ///   - Class templates / nested classes: null.
+  TypeSourceInfo *TypeAsWritten = nullptr;
```
Comment (mizvekov) [inline clang/include/clang/AST/DeclTemplate.h]: I think there is a bit of redundant information here, and we could have a union instead.

For example, I think most templates can be written as a TypeSourceInfo alone, and that can itself contain qualifiers, template args, and name location.

For some other cases, like templated member functions, the template args can reside in the qualifierloc.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 21]
```diff
@@ -9314,10 +9314,37 @@ static void StripImplicitInstantiation(NamedDecl *D, bool MinGW) {
...
 //  declaration or definition.
 static SourceLocation DiagLocForExplicitInstantiation(
     NamedDecl* D, SourceLocation PointOfInstantiation) {
+  // Search for an ExplicitInstantiationDecl that references D. Per
+  // [temp.explicit], explicit instantiations must appear in an enclosing
+  // namespace of the template, so the EID is in D's DeclContext or an ancestor.
+  for (DeclContext *DC = D->getDeclContext(); DC; DC = DC->getParent()) {
+    for (auto *Decl : DC->decls()) {
+      if (auto *EID = dyn_cast<ExplicitInstantiationDecl>(Decl))
+        if (EID->getSpecialization()->getCanonicalDecl() ==
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp]: You can use `declaresSameEntity`.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp]: I am not sure, for a 'normal' program, it doesn't seem that bad, because we are only walking up, never going back down again.

But for a huge program based on modules, this could force everything to be deserialized, which could be painful for very large programs.

**Review by ChuanqiXu9 — COMMENTED** [review]
Can you add two test for this in C++20 modules? One for it in module purview and one for it in GMF. 

My concern is, if this decl lives in GMF, it might be optimized out since no decl will reference it.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Module deserialization is indeed an issue. Since deserialization is lazy, traversing like this would trigger the deserialization of a large number of declarations. I came up with a simple solution: adding a map of instantiated canonical decl -> `ExplicitInstantiationDecl` in `ASTContext`. This way, we could perform lookups easily, and it wouldn't add much complexity. However, there is a question: should `ExplicitInstantiationDecl` be redeclarable? Judging purely from the current use cases, it doesn't seem necessary. For this diagnostic, we only need the location of the explicit instantiation definition, not the declaration.

Comment (ChuanqiXu9) [reply clang/lib/Sema/SemaTemplate.cpp]: ExplicitInstantiationDecl need to be redeclarable. As the we need to merge it from different modules, and they can have different source locations actually.

**Comment by 16bit-ykiko** [comment]
> Can you add two test for this in C++20 modules? One for it in module purview and one for it in GMF.
> 
> My concern is, if this decl lives in GMF, it might be optimized out since no decl will reference it.

After testing, I found that:
- Full BMI: The EIDs of both the GMF and the purview are present.
- Reduced BMI: The EID of the GMF is optimized away, while the one in the purview is retained.

**Comment by ChuanqiXu9** [comment]
> > Can you add two test for this in C++20 modules? One for it in module purview and one for it in GMF.
> > My concern is, if this decl lives in GMF, it might be optimized out since no decl will reference it.
> 
> After testing, I found that:
> 
> * Full BMI: The EIDs of both the GMF and the purview are present.
> * Reduced BMI: The EID of the GMF is optimized away, while the one in the purview is retained.

Yes. 

To solve this, when we write template specialization decl, we need to reference the ExplicitInstantiationDecl to make sure it exists.

This requires us to have a mechanism  to get ExplicitInstantiationDecl from specialization decl. A table in ASTContext may not be bad.

BTW, the "Reduced BMI" will be the default and the only supported one. The "Full BMI" will only be used by build system which supports two-phase compilations to build the object file. So, almost all BMIs will be "Reduced BMI".

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: OK, I will make `ExplicitInstantiationDecl` redeclarable and add a map of instantiated canonical decl -> `ExplicitInstantiationDecl` in ASTContext. .

File: clang/lib/Serialization/ASTWriterDecl.cpp [hunk 22]
```diff
@@ -919,6 +919,11 @@ void ASTDeclWriter::VisitFunctionDecl(FunctionDecl *D) {
     }
   }
 
+  // Ensure associated ExplicitInstantiationDecl survives reduced BMI.
+  if (auto *EID = Record.getASTContext().getExplicitInstantiationDecl(D))
+    Writer.RelatedDeclsMap[Writer.GetDeclRef(D)].push_back(
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTWriterDecl.cpp]: Writer.RelatedDeclsMap not used.

File: clang/include/clang/Serialization/ASTReader.h [hunk 23]
```diff
@@ -651,6 +652,11 @@ class ASTReader
   llvm::DenseMap<std::pair<const Decl *, unsigned>, NamedDecl *>
       LambdaDeclarationsForMerging;
 
+  /// Map from canonical specialization to the corresponding explicit
+  /// instantiation declaration, for merging across modules.
+  llvm::DenseMap<const Decl *, ExplicitInstantiationDecl *>
+      ExplicitInstantiationDeclsForMerging;
```
Comment (ChuanqiXu9) [inline clang/include/clang/Serialization/ASTReader.h]: Why can't we merge it with the table within ASTContext?

**Review by ChuanqiXu9 — COMMENTED** [review]
@boomanaiden154 maybe it is worth to test this with Google's internal workloads.

File: clang/lib/Serialization/ASTWriterDecl.cpp (hunk 22 above)
Comment (16bit-ykiko) [reply clang/lib/Serialization/ASTWriterDecl.cpp]: > To solve this, when we write template specialization decl, we need to reference the ExplicitInstantiationDecl to make sure it exists.

How to achieve this?

Comment (ChuanqiXu9) [reply clang/lib/Serialization/ASTWriterDecl.cpp]: As long as we call GetDeclRef on it, it is referenced.

Comment (16bit-ykiko) [reply clang/lib/Serialization/ASTWriterDecl.cpp]: Fixed.

File: clang/include/clang/Serialization/ASTReader.h (hunk 23 above)
Comment (16bit-ykiko) [reply clang/include/clang/Serialization/ASTReader.h]: Fixed.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp]: I don't get why they need to be merged from different modules though, they are not declaring an entity.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp]: We only need to merge stuff from different modules if they are declaring a single entity, which needs to be referenced from other parts of the program.

There is no referencing ExplicitInstantiationDecl from other parts of the program.

So I think your initial take on `ExplicitInstantiationDecl` not being redeclarable stands on a principle.

Maybe we need a way to track all the explicit instantiations of the same template specialization, but that doesn't need necessarily to be through the redeclarable mechanism.

Comment (ChuanqiXu9) [reply clang/lib/Sema/SemaTemplate.cpp]: Sounds good. If we're not going to reference it, merging them seems to be unnecessary.

**Review by erichkeane — COMMENTED** [review]
I think this is a good direction, we should probably alert our downstreams @llvm/clang-vendors to make sure they are comfortable with the new node/having to deal with the new node in AST searches.

We should probably make sure our AST-matchers has a way of seeing these?

Also: I'm a bit concerned about the additional memory pressure, the `ExplicitInstantiationDecl` is pretty huge.  Can we measure the difference in memory usage in some sort of major project here to see?  

I'm also interested in if this has a sizable negative effect on compile times, we have the tracker, but I don't recall how to start it (@Endilll ?).

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: Get it, so remove redeclarable and related AST serialization changes. We don't need to reference them in the GMF?

Comment (ChuanqiXu9) [reply clang/lib/Sema/SemaTemplate.cpp]: I think we still need to reference it in the GMF. Otherwise  it will be optimized out and the intelligence won't get it. To confirm, you can try to see if it works correctly in intelligence as you expected.

Comment (16bit-ykiko) [reply clang/lib/Sema/SemaTemplate.cpp]: In my experience, it should be similar to `StaticAssert`. Not storing them in the PCM has no real impact, as it doesn't actually affect how the language server functions. There are two main use cases: the first is "find references," which queries the index. Since indexing is based on the AST, this is fine—as long as the declaration is traversed during indexing, it can be found. The second use case is highlighting for open files, which also involves building an AST. In other words, we don't need to traverse the declarations in a PCH/PCM to implement any specific functionality.

The only exception is `CodeAction`; there might be some `CodeAction` in the future that requires this kind of access, though there probably isn't one right now. So, adding the reference probably wouldn't hurt, and it's worth considering. But what about the other AST nodes in the GMF that are optimized away? Are there any potential issues with that?

**Comment by Endilll** [comment]
> but I don't recall how to start it (@Endilll ?)

Contact Nikita Popov (`_nikic` on Discord), asking him to add your fork to LLVM compile time tracker. Then you push branches that start with `perf/`, and observe the results some hours after.

File: clang/lib/AST/DeclTemplate.cpp (hunk 19 above)
Comment (16bit-ykiko) [reply clang/lib/AST/DeclTemplate.cpp]: https://github.com/llvm/llvm-project/blob/078c43c582f0cd0a7c925abcd9eefdf9f63b2040/clang/lib/AST/Decl.cpp#L2103-L2112

If possible, I think we should reuse this logic. But `typeIsPostfix` is a static function. Should we extract it to the method of `QualType`?

https://github.com/llvm/llvm-project/blob/078c43c582f0cd0a7c925abcd9eefdf9f63b2040/clang/lib/AST/Decl.cpp#L2069-L2101

File: clang/lib/Sema/SemaTemplate.cpp (hunk 12 above)
Comment (mizvekov) [reply clang/lib/Sema/SemaTemplate.cpp]: Well they need to be serialized somehow.

It should be possible in principle to serialize a TU, then import and print it out using `-ast-print`, and all of the original source code recovered.

And yes, the same problem applies to static_asserts.

Both can appear as statements, and we would expect serialization of a a context to include all statements that appear within it. The context might be an entity that needs to be merged, but the statements themselves do not get merged, similarly to how other statements and expressions are not merged.

File: clang/include/clang/AST/DeclTemplate.h (hunk 20 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/DeclTemplate.h]: Zip with trailing objects and pointer low bits.

File: clang/lib/AST/DeclTemplate.cpp (hunk 19 above)
Comment (mizvekov) [reply clang/lib/AST/DeclTemplate.cpp]: Yeah, reusing that sounds fine to me.

Comment (16bit-ykiko) [reply clang/lib/AST/DeclTemplate.cpp]: Done.

File: clang/lib/AST/TextNodeDumper.cpp (hunk 18 above)
Comment (16bit-ykiko) [reply clang/lib/AST/TextNodeDumper.cpp]: Fixed.

**Comment by 16bit-ykiko** [comment]
> I think this is a good direction, we should probably alert our downstreams @llvm/clang-vendors to make sure they are comfortable with the new node/having to deal with the new node in AST searches.
> 
> We should probably make sure our AST-matchers has a way of seeing these?
> 
> Also: I'm a bit concerned about the additional memory pressure, the `ExplicitInstantiationDecl` is pretty huge. Can we measure the difference in memory usage in some sort of major project here to see?
> 
> I'm also interested in if this has a sizable negative effect on compile times, we have the tracker, but I don't recall how to start it (@Endilll ?).

After optimization, this class is now quite small. In my experience, explicit instantiations are rarely used in codebases anyway, meaning very few of these nodes will actually be created. Therefore, I believe the impact on compile time will likely be negligible.

**Comment by erichkeane** [comment]
> > I think this is a good direction, we should probably alert our downstreams @llvm/clang-vendors to make sure they are comfortable with the new node/having to deal with the new node in AST searches.
> > We should probably make sure our AST-matchers has a way of seeing these?
> > Also: I'm a bit concerned about the additional memory pressure, the `ExplicitInstantiationDecl` is pretty huge. Can we measure the difference in memory usage in some sort of major project here to see?
> > I'm also interested in if this has a sizable negative effect on compile times, we have the tracker, but I don't recall how to start it (@Endilll ?).
> 
> After optimization, this class is now quite small. In my experience, explicit instantiations are rarely used in codebases anyway, meaning very few of these nodes will actually be created. Therefore, I believe the impact on compile time will likely be negligible.

Still worth running the check benchmark though.  I hope few of these nodes will be created, but we don't know what we don't know!  There could likely be a pathological case here we're not thinking about.

**Comment by 16bit-ykiko** [comment]
> > > I think this is a good direction, we should probably alert our downstreams @llvm/clang-vendors to make sure they are comfortable with the new node/having to deal with the new node in AST searches.
> > > We should probably make sure our AST-matchers has a way of seeing these?
> > > Also: I'm a bit concerned about the additional memory pressure, the `ExplicitInstantiationDecl` is pretty huge. Can we measure the difference in memory usage in some sort of major project here to see?
> > > I'm also interested in if this has a sizable negative effect on compile times, we have the tracker, but I don't recall how to start it (@Endilll ?).
> > 
> > 
> > After optimization, this class is now quite small. In my experience, explicit instantiations are rarely used in codebases anyway, meaning very few of these nodes will actually be created. Therefore, I believe the impact on compile time will likely be negligible.
> 
> Still worth running the check benchmark though. I hope few of these nodes will be created, but we don't know what we don't know! There could likely be a pathological case here we're not thinking about.

Hi, here are the test results. It seems nikic has been busy recently, so I asked my friend to help run the tests. It looks like the impact on compile time is negligible—only a few hundredths of a percent (around 0.0x%).

https://llvm-compile-time-tracker.com/compare.php?from=4fb21a1d226bff588a66b51452a159b41c5373d5&to=ee2fc2ee0c6d96457339ddd073dde107e7369aff&stat=instructions:u

**Comment by erichkeane** [comment]
> > > > I think this is a good direction, we should probably alert our downstreams @llvm/clang-vendors to make sure they are comfortable with the new node/having to deal with the new node in AST searches.
> > > > We should probably make sure our AST-matchers has a way of seeing these?
> > > > Also: I'm a bit concerned about the additional memory pressure, the `ExplicitInstantiationDecl` is pretty huge. Can we measure the difference in memory usage in some sort of major project here to see?
> > > > I'm also interested in if this has a sizable negative effect on compile times, we have the tracker, but I don't recall how to start it (@Endilll ?).
> > > 
> > > 
> > > After optimization, this class is now quite small. In my experience, explicit instantiations are rarely used in codebases anyway, meaning very few of these nodes will actually be created. Therefore, I believe the impact on compile time will likely be negligible.
> > 
> > 
> > Still worth running the check benchmark though. I hope few of these nodes will be created, but we don't know what we don't know! There could likely be a pathological case here we're not thinking about.
> 
> Hi, here are the test results. It seems nikic has been busy recently, so I asked my friend to help run the tests. It looks like the impact on compile time is negligible—only a few hundredths of a percent (around 0.0x%).
> 
> https://llvm-compile-time-tracker.com/compare.php?from=4fb21a1d226bff588a66b51452a159b41c5373d5&to=ee2fc2ee0c6d96457339ddd073dde107e7369aff&stat=instructions:u

Thanks for that, I appreciate you doing that!

I think I'm happy here, but would like to see @zyn0217 and @mizvekov do the approval, since they did a more thorough review than I did.

**Review by zyn0217 — APPROVED** [review]
This also needs a release note, otherwise LGTM

@mizvekov for the final approval.

File: clang/include/clang/AST/ASTContext.h [hunk 24]
```diff
@@ -656,6 +657,11 @@ class ASTContext : public RefCountedBase<ASTContext> {
 
   llvm::DenseMap<FieldDecl *, FieldDecl *> InstantiatedFromUnnamedFieldDecl;
 
+  /// Maps a canonical specialization Decl to all ExplicitInstantiationDecls
+  /// that reference it (declarations and definitions).
+  llvm::DenseMap<const Decl *, llvm::TinyPtrVector<ExplicitInstantiationDecl *>>
```
Comment (mizvekov) [inline clang/include/clang/AST/ASTContext.h]: Nit: couldn't this be a NamedDecl at least?

File: clang/include/clang/AST/ASTNodeTraverser.h [hunk 25]
```diff
@@ -683,6 +683,15 @@ class ASTNodeTraverser
...
   }
 
+  void VisitExplicitInstantiationDecl(const ExplicitInstantiationDecl *D) {
+    for (unsigned I = 0, E = D->getNumTemplateArgs(); I != E; ++I) {
+      TemplateArgumentLoc Loc = D->getTemplateArg(I);
+      Visit(Loc.getArgument(), Loc.getSourceRange());
+    }
+    if (TypeSourceInfo *TSI = D->getTypeAsWritten())
+      Visit(TSI->getTypeLoc());
+  }
```
Comment (mizvekov) [inline clang/include/clang/AST/ASTNodeTraverser.h:693]: Usually on these node traverses, we want to visit things in the order they appear syntactically.

File: clang/include/clang/AST/RecursiveASTVisitor.h [hunk 26]
```diff
@@ -1748,6 +1748,15 @@ DEF_TRAVERSE_DECL(StaticAssertDecl, {
...
 })
 
+DEF_TRAVERSE_DECL(ExplicitInstantiationDecl, {
+  if (D->getQualifierLoc())
+    TRY_TO(TraverseNestedNameSpecifierLoc(D->getQualifierLoc()));
+  for (unsigned I = 0, E = D->getNumTemplateArgs(); I != E; ++I)
+    TRY_TO(TraverseTemplateArgumentLoc(D->getTemplateArg(I)));
+  if (TypeSourceInfo *TSI = D->getTypeAsWritten())
+    TRY_TO(TraverseTypeLoc(TSI->getTypeLoc()));
+})
```
Comment (mizvekov) [inline clang/include/clang/AST/RecursiveASTVisitor.h:1760]: Ditto. Also, when the Qualifier comes from the TSI, are you sure this is not double visiting?

File: clang/lib/AST/DeclTemplate.cpp [hunk 27]
```diff
@@ -1784,3 +1784,136 @@ const Decl &clang::adjustDeclToTemplate(const Decl &D) {
...
+
+NestedNameSpecifierLoc ExplicitInstantiationDecl::getQualifierLoc() const {
+  if (hasTrailingQualifier())
+    return *getTrailingObjects<NestedNameSpecifierLoc>();
+  if (auto *TSI = getRawTypeSourceInfo()) {
+    if (auto TL = TSI->getTypeLoc().getAs<TemplateSpecializationTypeLoc>())
+      return TL.getQualifierLoc();
+    if (auto TL = TSI->getTypeLoc().getAs<TagTypeLoc>())
+      return TL.getQualifierLoc();
+  }
```
Comment (mizvekov) [inline clang/lib/AST/DeclTemplate.cpp]: There is a function in `Type` specifically for this, `getPrefix` I believe.

**Review by mizvekov — APPROVED** [review]
A few nits, but LGTM, Thanks!

File: clang/include/clang/AST/RecursiveASTVisitor.h (hunk 26 above)
Comment (16bit-ykiko) [reply clang/include/clang/AST/RecursiveASTVisitor.h:1760]: Yes, getTypeAsWritten() returns null for class templates/nested classes where the qualifier lives inside the TSI. So no problem here.

**Comment by 16bit-ykiko** [comment]
All tests have passed, but I don't have merge permissions. @mizvekov, could you help merge this? Thanks!

**Comment by shafik** [comment]
We have a regression linked to this change: https://github.com/llvm/llvm-project/issues/197797#issuecomment-4454713037
