### PR TITLE
[Sema] Warning for _Float16 passed to format specifier '%f'

### LINKED ISSUE #68538: passing _Float16 to printf where double is expected should raise a warning
Unlike __fp16, _Float16 is passed without conversion to double, and so it's an unexpected argument type at that position when used with `%f` and the like, and should raise a warning.

https://godbolt.org/z/r5o7djxbd

### PR DESCRIPTION
**Pull request by Luhaocong**
According to https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2844.pdf, default argument promotions for _FloatN types has been removed.

A warning is needed to notice user to promote _Float16 to double explicitly, and then pass it to format specifier '%f', which is consistent with GCC.

Fixes: https://github.com/llvm/llvm-project/issues/68538

### CODE REVIEW

**Comment by Luhaocong** [comment]
This patch improves implement https://github.com/llvm/llvm-project/commit/04e6178ae932c9a1d939dcfe3ef1189f4bbb21aa. Could you please help me review this patch @apple-fcloutier @AaronBallman

**Comment by Luhaocong** [comment]
> Should this only apply in C23 mode? Standard behavior until C23 is that `_Float16` promotes to `double`. What about C++?

It seems clang never support default argument promotions for _Float16, as described in https://github.com/llvm/llvm-project/blob/main/clang/docs/LanguageExtensions.rst#id68 five years ago. Is there any demand to support this in old C/C++ standard？

And I try case with -std=c99 (https://godbolt.org/z/xqx8e6oh5) and -std=c++11 (https://godbolt.org/z/Mrn779Tdq) , GCC give a warning at both.

**Comment by AaronBallman** [comment]
> Should this only apply in C23 mode? Standard behavior until C23 is that `_Float16` promotes to `double`. What about C++?

`_Float16` wasn't standardized until C23; before then it was part of TS 18661, but we never claimed conformance to that (that I'm aware of), so I think we have the wiggle room to be consistent across language modes. My bigger question is: do we codegen properly and what do C standard libraries expect? e.g., if we codegen such that we don't promote in older language modes, will this cause problems for runtime libraries?

CC @jcranmer-intel for additional opinions

**Comment by jcranmer-intel** [comment]
> Should this only apply in C23 mode? Standard behavior until C23 is that `_Float16` promotes to `double`. What about C++?

I can't find any reference in older versions of C or TS 18661-3 that suggests that `_Float16` is promoted to `double`. The wording of 6.5.2.2 used to say

> If the expression that denotes the called function has a type that does not include a prototype, the integer promotions are performed on each argument, and arguments that have type `float` are promoted to `double`. These are called the default argument promotions.

Which suggests that *only* `float` is promoted and that other floating point types are not promoted, and nothing in TS 18661-3 can be construed to suggest promotion either (notably, `_Float32` *doesn't* promote to `double`, even though it's likely the same representation as `float`!).

**Comment by apple-fcloutier** [comment]
[N2844](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2844.pdf), as linked by OP, references the removed language that you are looking for.

As Aaron said, it doesn't matter if clang never claimed conformance/never implemented default argument promotion for these types in the first place.

**Comment by jcranmer-intel** [comment]
> [N2844](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2844.pdf), as linked by OP, references the removed language that you are looking for.

Doing some more spelunking, no released version of the TS ever had default argument promotion. The change to the TS was done shortly before integration in C, in response to the C++ proposal for extended floating-point types, but WG14 objected to the change, so it was dropped in actual integration. See https://mailman.oakapple.net/pipermail/cfp-interest/2020-September/001782.html for the summary.

**Comment by Luhaocong** [comment]
Thanks for everyone's review. Do you have any other suggestions for this change, and can this pull request be accepted ?

File: clang/test/AST/variadic-promotion.c [hunk 1]
```diff
@@ -18,3 +18,8 @@ void test_floating_promotion(__fp16 *f16, float f32, double f64) {
 // CHECK: ImplicitCastExpr {{.*}} 'double' <FloatingCast>
 // CHECK-NEXT: 'float'
 }
+
+void test_Float16_no_default_promotion(_Float16 f16) {
+  variadic(1, f16);
+// CHECK-NOT: ImplicitCastExpr {{.*}} 'double' <FloatingCast>
+}
```
Comment (cor3ntin) [inline clang/test/AST/variadic-promotion.c:25]: This test seems unrelated to the change, we should do that in a  separate PR

**Review by cor3ntin — APPROVED** [review]
LGTM.

The format diagnostics are new in Clang 18 and as such we do not need a release note. Correct?

File: clang/test/AST/variadic-promotion.c (hunk 1 above)
Comment (Luhaocong) [reply clang/test/AST/variadic-promotion.c]: Done

**Comment by Luhaocong** [comment]
> LGTM.
> 
> The format diagnostics are new in Clang 18 and as such we do not need a release note. Correct?

This format diagnostics is existent until https://github.com/llvm/llvm-project/commit/04e6178ae932c9a1d939dcfe3ef1189f4bbb21aa had been committed. Clang 17.0.1 gives a warning: https://godbolt.org/z/xMdK9cETY.

**Review by cor3ntin — APPROVED** [review]
Thanks for confirming.
Do you need me to merge that for you?

**Comment by Luhaocong** [comment]
> Thanks for confirming. Do you need me to merge that for you?

It can't be better, thanks.

**Comment by rorth** [comment]
This patch broke the [Solaris/sparcv9 buildbot](https://lab.llvm.org/buildbot/#/builders/72/builds/1709): the new/changed tests `FAIL` with
```
  File /opt/llvm-buildbot/home/solaris11-sparcv9/clang-solaris11-sparcv9/llvm/clang/test/SemaCXX/format-strings-scanf.cpp Line 25: _Float16 is not supported on this target
1 error generated.
```
