### PR TITLE
[HLSL] [DirectX] Invert the result of `firstbithigh`

### LINKED ISSUE #145752: [HLSL][DirectX] `firstbithigh` returns bit index from wrong side
https://godbolt.org/z/1ahzc64a8

DXC returns `31 - firstbit(S)hi` instead of directly returning `firstbit(S)hi` like clang currently does. This test confirms it is intentional https://github.com/microsoft/DirectXShaderCompiler/blob/b390fb19adc5d7c23180eb470470411fce986910/tools/clang/test/HLSLFileCheck/hlsl/intrinsics/bitwise/firstbitHi.hlsl#L10

Without the inversion the result has the bit set from the wrong direction.

This is a bug in the clang lowering that was caught by https://github.com/llvm/offload-test-suite/pull/210

### PR DESCRIPTION
**Pull request by Icohedron**
Fixes #145752 

This PR inverts the result of `firstbithigh` when targeting DirectX by subtracting it from integer bitwidth - 1 to match the result from DXC.
The result is not inverted if `firstbithigh` returned -1 or when targeting a backend other than DirectX.

### CODE REVIEW

File: clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h [hunk 1]
```diff
@@ -148,6 +148,15 @@ template <typename T> constexpr T ldexp_impl(T X, T Exp) {
   return exp2(Exp) * X;
 }
 
+template <typename T, int Bitwidth> constexpr uint firstbithigh_impl(T X) {
+  return (Bitwidth - 1) - __builtin_hlsl_elementwise_firstbithigh(X);
+}
+
+template <typename T, int N, int Bitwidth>
+constexpr vector<uint, N> firstbithigh_impl(vector<T, N> X) {
+  return (Bitwidth - 1) - __builtin_hlsl_elementwise_firstbithigh(X);
```
Comment (farzonl) [inline clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h]: This does look like it would change the behavior of what DXC currently does when targeting SPIRV. 
 https://godbolt.org/z/vq5EGKTq5

I think thats fine, because its a clear case of divergent behavior. Not sure how we would document this for any vulkan shaders that break.

**Review by farzonl — APPROVED** [review]

**Review by V-FEXrt — CHANGES_REQUESTED** [review]
Okay, yep, I found it. https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh

`If no matching bit is found, 0xFFFFFFFF (-1) is returned.`

So IR is doing this

```
i32 base =  @dx.op.unaryBits.i32(i32 34, i32 %i)
i32 invert = 32 - base
if (base == -1) return base
else return invert
```

and we need to keep that functionality

File: clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h (hunk 1 above)
Comment (V-FEXrt) [reply clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h]: Are we sure that DXC has divergent behavior here between DX and SPRIV? IIRC the opcodes are divergent but the result of the hlsl intrinsic is the same

I'm trying to find proof of this right now but IIRC the DXIL ops (for high bit only) return the number counting from the wrong side (which is why we need the `31 - ans`) but on SPIRV they are consistent so not having the `31 - ans` is the correct lowering

**Comment by V-FEXrt** [comment]
Here is some further reading/context that we want to make sure we've applied here https://github.com/Microsoft/DirectXShaderCompiler/issues/169

File: clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h (hunk 1 above)
Comment (farzonl) [reply clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h]: Thank you for checking Ashley!

**Comment by Icohedron** [comment]
I will fix the failing tests. I just forgot to change the i1 type in the selects to vectors of i1s.

File: clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h [hunk 2]
```diff
@@ -148,6 +148,29 @@ template <typename T> constexpr T ldexp_impl(T X, T Exp) {
...
+  // The firstbithigh DXIL ops count bits from the wrong side, so we need to
+  // invert it for DirectX.
+  uint Inversion = (BitWidth - 1) - FBH;
+  FBH = select(FBH == -1, FBH, Inversion);
+#endif
+  return FBH;
+}
+
+template <typename T, int N, int BitWidth>
+constexpr vector<uint, N> firstbithigh_impl(vector<T, N> X) {
```
[the remark this answers is not in the document]
Comment (Icohedron) [reply clang/lib/Headers/hlsl/hlsl_intrinsic_helpers.h]: The result of firstbithigh and, by extension, the `Inversion` variable are always of type `uint` / `uint32_t` even when the type `T` is, for example, a `int16_t` or `int64_t`.

**Review by V-FEXrt — APPROVED** [review]

File: clang/test/CodeGenHLSL/builtins/firstbithigh.hlsl [hunk 3]
```diff
@@ -1,161 +1,312 @@
...
 
 #ifdef __HLSL_ENABLE_16_BIT
 // CHECK-LABEL: test_firstbithigh_ushort
 // CHECK: call i32 @llvm.[[TARGET]].firstbituhigh.i16
+// DXCHECK: sub i32 15, {{.*}}
+// SPVCHECK-NOT: sub i32 15, {{.*}}
+// DXCHECK: icmp eq i32 {{.*}}, -1
+// SPVCHECK-NOT: icmp eq i32 {{.*}}, -1
+// DXCHECK: select i1 {{.*}}, i32 {{.*}}, i32 {{.*}}
+// SPVCHECK-NOT: select i1 {{.*}}, i32 {{.*}}, i32 {{.*}}
```
Comment (farzonl) [inline clang/test/CodeGenHLSL/builtins/firstbithigh.hlsl]: I see what you are doing here I think a simple `SPVCHECK-NEXT ret i32 ...` would read better. If you don't agree then at a minimum not interweiving DX and SPV checks would be nicer to read linear correctness.

**Review by farzonl — APPROVED** [review]
LGTM. Have a readability nit for the test. Don't feel strongly about it but not a huge fan of  `CHECK-NOT`
