### PR TITLE
[DebugInfo][NewGVN] Fix debug value loss

### LINKED ISSUE #147511: [DebugInfo][NewGVN] Deleting instructions without salvaging their debug values
In NewGVN, `NewGVN::eliminateInstructions` deletes instructions by first marking them for deletion. In the following code, the instruction is deleted after being marked without having its debug value salvaged.

https://github.com/llvm/llvm-project/blob/6c8c836b4f5a0b519db6f97c4882c6c061edd004/llvm/lib/Transforms/Scalar/NewGVN.cpp#L4079

Here is an example: https://godbolt.org/z/K4EanM9Ka. In this example, `%add2` is deleted and its debug value becomes poison.

```llvm
; Before NewGVN
define void @binop(i32 %x, i32 %y) !dbg !5 {
  %add1 = add i32 %x, %y, !dbg !12
    #dbg_value(i32 %add1, !9, !DIExpression(), !12)
  %add2 = add i32 %y, %x, !dbg !13
    #dbg_value(i32 %add2, !11, !DIExpression(), !13)
  call void @use(i32 %add1, i32 %add2), !dbg !14
  ret void, !dbg !15
}

; After NewGVN
define void @binop(i32 %x, i32 %y) !dbg !5 {
  %add1 = add i32 %x, %y, !dbg !12
    #dbg_value(i32 %add1, !9, !DIExpression(), !12)
    #dbg_value(i32 poison, !11, !DIExpression(), !13)
  call void @use(i32 %add1, i32 %add1), !dbg !14
  ret void, !dbg !15
}
```

### PR DESCRIPTION
**Pull request by Apochens**
Fix #147511

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/NewGVN.cpp [hunk 1]
```diff
@@ -4076,6 +4076,7 @@ bool NewGVN::eliminateInstructions(Function &F) {
                 if (!match(DefI, m_Intrinsic<Intrinsic::ssa_copy>()))
                   patchReplacementInstruction(DefI, DominatingLeader);
 
+                salvageDebugInfo(*DefI);
```
Comment (dzhidzhoev) [inline llvm/lib/Transforms/Scalar/NewGVN.cpp]: Should this be moved inside the loop https://github.com/llvm/llvm-project/blob/95cb8336d1598780d66eeb85d8fcb1c9a433a459/llvm/lib/Transforms/Scalar/NewGVN.cpp#L3527 to salvage more instructions?

Comment (Apochens) [reply llvm/lib/Transforms/Scalar/NewGVN.cpp]: That would be a solution, but that would introduce some unnecessary computation overhead of salvaging. For example, salvaging the store instructions in `InstructionsToErase` is unnecessary:

https://github.com/llvm/llvm-project/blob/6c8c836b4f5a0b519db6f97c4882c6c061edd004/llvm/lib/Transforms/Scalar/NewGVN.cpp#L4194-L4196

So, I didn't place this salvage into the loop but place it just before where the salvageable instructions are marked for deletion. But if this unnecessary compulation is acceptable, I can move this salvage into the loop.

Comment (dzhidzhoev) [reply llvm/lib/Transforms/Scalar/NewGVN.cpp]: Thank you. I'm fine with the current version if extra salvaging calls are redundant.

File: llvm/test/Transforms/NewGVN/salvage-eliminate-instruction.ll [hunk 2]
```diff
@@ -0,0 +1,43 @@
+; RUN: opt -S -passes=newgvn %s | FileCheck %s
+
+; Check that eliminateInstruction() salvages the debug value of `Def` (`DefI`)
+; which is marked for deletion.
```
Comment (OCHyams) [inline llvm/test/Transforms/NewGVN/salvage-eliminate-instruction.ll]: The comment has a chance of going stale, referring to the LLVM source. I think function name is ok but instead of LLVM source variables, it's probably better to describe what's happening in terms of the IR in the test.

**Review by OCHyams — COMMENTED** [review]
Could we replace the debug-use of `%add2` with the `%add1` instead of salvaging it?

**Comment by Apochens** [comment]
> Could we replace the debug-use of `%add2` with the `%add1` instead of salvaging it?

@OCHyams I think we can do this replacement. In NewGVN, the instruction pointed by `DefI` (or `Def`) and that pointed by `DominatingLeader` are two equivalent instructions in the same congruence class, and the latter will replace the former.

File: llvm/test/Transforms/NewGVN/salvage-eliminate-instruction.ll (hunk 2 above)
Comment (Apochens) [reply llvm/test/Transforms/NewGVN/salvage-eliminate-instruction.ll]: Thanks, I have refined it in the latest commit.

File: llvm/lib/Transforms/Scalar/NewGVN.cpp [hunk 3]
```diff
@@ -4076,6 +4077,15 @@ bool NewGVN::eliminateInstructions(Function &F) {
                 if (!match(DefI, m_Intrinsic<Intrinsic::ssa_copy>()))
                   patchReplacementInstruction(DefI, DominatingLeader);
 
+                SmallVector<DbgVariableIntrinsic *> DbgUsers;
+                SmallVector<DbgVariableRecord *> DVRUsers;
+                findDbgUsers(DbgUsers, DefI, &DVRUsers);
+
+                for (auto *DVI: DbgUsers)
+                  DVI->replaceVariableLocationOp(DefI, DominatingLeader);
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/NewGVN.cpp]: We're in the process of removing debug intrinsics completely, so it's fine to ignore `DbgUsers`. Also fine to leave this here for now, it will get cleaned up when `findDbgUsers` is updated. Just a note for future patches.

**Review by OCHyams — APPROVED** [review]
LGTM. Please make the clang-format bot happy
