### PR TITLE
[AArch64] Check for negative numbers when adjusting icmps

### LINKED ISSUE #141137: [AArch64] Need to adjust comparison with -1 to comparison with 0 when it is beneficial
When I corrected an issue with getAArch64Cmp: the following changed:

; CHECK-SD-NEXT:    ands w8, w8, w8, asr #31
; CHECK-SD-NEXT:    csinv w8, w8, wzr, ge

to

; CHECK-SD-NEXT:    and w8, w8, w8, asr #31
; CHECK-SD-NEXT:    cmn w8, #1
; CHECK-SD-NEXT:    csinv w8, w8, wzr, gt

Now, this is only one regression; the rest of the changes are improvements. However, it made me realize an issue: the compiler is peephole optimizing a compare with -1 but not because it is better, but because it thought -1 was not a legal immediate for a compare, which my patch corrects the compiler into realizing -1 is a valid cmp, so it changes it to a comparison with 0, which is beneficial in a tiny number of cases, like this one, but does more harm than good.

So the issue is not with this patch, but rather, we ought to peephole optimize a comparison with -1 to be a comparison with 0, if we know cse will do the job.

### PR DESCRIPTION
**Pull request by AZero13**
This relies on the fact that we can use tst and ands for comparisons as by emitComparison.

Also has mitigations for when comparing with -1 and 1 to avoid regressions.

Fixes: https://github.com/llvm/llvm-project/issues/141137

### CODE REVIEW

**Comment by AZero13** [comment]
Note: The patch works perfectly fine as-is, hence why it is not a draft; it is just that it is written in a way that does need improvements.

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -3755,58 +3763,82 @@ static unsigned getCmpOperandFoldingProfit(SDValue Op) {
...
                              const SDLoc &dl) {
   if (ConstantSDNode *RHSC = dyn_cast<ConstantSDNode>(RHS.getNode())) {
     EVT VT = RHS.getValueType();
-    uint64_t C = RHSC->getZExtValue();
-    if (!isLegalArithImmed(C)) {
+    APInt C = RHSC->getAPIntValue();
+    int64_t C = RHSC->getSExtValue();
+    // This is a special case to better fold with emitComparison().
+    if (shouldBeAdjustedToZero(LHS, C, CC)) {
+      if (C.isOne()) {
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:3792]: Could CC be passes to shouldBeAdjustedToZero by referenced and updated inside it, to avoid the need to re-guess what it did?

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:3792]: Yes

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 2]
```diff
@@ -3762,58 +3770,82 @@ static unsigned getCmpOperandFoldingProfit(SDValue Op) {
...
+
 static SDValue getAArch64Cmp(SDValue LHS, SDValue RHS, ISD::CondCode CC,
                              SDValue &AArch64cc, SelectionDAG &DAG,
                              const SDLoc &dl) {
   if (ConstantSDNode *RHSC = dyn_cast<ConstantSDNode>(RHS.getNode())) {
     EVT VT = RHS.getValueType();
-    uint64_t C = RHSC->getZExtValue();
-    if (!isLegalArithImmed(C)) {
+    APInt C = RHSC->getAPIntValue();
+    int64_t C = RHSC->getSExtValue();
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:3803]: There is an extra C here.

Comment (AZero13) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:3803]: Fixed it!

**Review by davemgreen — APPROVED** [review]
Thanks - LGTM

**Comment by AZero13** [comment]
I don't have merge perms. Can you do it please @davemgreen

**Comment by AZero13** [comment]
There are SOME regressions here, but this isn't the patch's fault.

Overall, the improvements outweigh the regressions

Or rather, the cause of the regressions is not something the original code was ever doing for the sake of optimization, but rather luck.

You see, the change of CMN 1 to cmp was in some places allowing better CSE to happen, but with this patch, that's undone, but this also means cse is happening in more places.

The fix is not to reverse this patch, but it is exposing a huge problem with the design of this code: we should be taking CSE into account too.

But how? Espcially when CSE is probably not looking at this from the DAG level and is a different pass?

**Comment by AZero13** [comment]
This is definitely a result of CSE not working because of the mistaken transforms we were doing was just so happening to result in better codegen for some functions.

**Comment by davemgreen** [comment]
Yeah the patch was OK - could it use getNodeIfExists to check for the duplicate nodes? It looks like just using `cmp 0` in more cases might help.

**Comment by AZero13** [comment]
Made a few patches to help correct this:

https://github.com/llvm/llvm-project/pull/143965

https://github.com/llvm/llvm-project/pull/144166

Going to look into the getNodeIfExists thing

**Comment by AZero13** [comment]
https://github.com/llvm/llvm-project/pull/144380 Another PR to address the issue
