### PR TITLE
[lldb] Claim to support swbreak and hwbreak packets when debugging a gdbremote

### LINKED ISSUE #56125: LLDB: GDB remote protocol feature/packet `swbreak` not supported
Hello,
When I was trying to use latest `lldb` with `gdbserver`, I came across an issue of not supported feature/packet `swbreak` in GDB remote protocol. 
As far as I understand, without this feature, software breakpoints do not work correctly then using with `gdbserver`.

On `swbreak` in [gdb manual](https://sourceware.org/gdb/onlinedocs/gdb/Stop-Reply-Packets.html#swbreak-stop-reason):

_On some architectures, such as x86, at the architecture level, when a breakpoint instruction executes the program counter points at the breakpoint address plus an offset. On such targets, the stub is responsible for adjusting the PC to point back at the breakpoint address._

And this is exactly that (not) happens then I trying to use software breakpoints in this setup,
PC register does not adjusted and program crashes.

Is that intendent behaviour?
Will patches adding this feature be accepted?

Ubuntu 20.04.4 LTS x86_64
llvb version : latest master/main
gdbserver version : GNU gdbserver (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

### PR DESCRIPTION
**Pull request by xusheng6**
This fixes https://github.com/llvm/llvm-project/issues/56125 and https://github.com/vadimcn/codelldb/issues/666, as well as the downstream issue in our binary ninja debugger: https://github.com/Vector35/debugger/issues/535

Basically, lldb does not claim to support the `swbreak` packet so the gdbserver would not use it. As a result, the gdbserver always sends the unmodified program counter value which, on systems like x86, causes the program counter to be off-by-one (or otherwise wrong). For reference, the lldb-server always sends the modified program counter value so it works perfectly with lldb.

https://sourceware.org/gdb/current/onlinedocs/gdb.html/Stop-Reply-Packets.html#swbreak-stop-reason

No new code is added to add support `swbreak`, since the way lldb works already expects the remote to have adjusted the program counter. The change just lets the gdbserver know that lldb supports it, so that it will send the adjusted program counter. 

To test this PR, you can use lldb to connect to a gdbserver running on e.g., Ubuntu 22.04, and see the program counter is off-by-one without the patch. With the patch, things work as expected

### CODE REVIEW

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp [hunk 1]
```diff
@@ -2349,6 +2349,9 @@ StateType ProcessGDBRemote::SetThreadStopInfo(StringExtractor &stop_packet) {
         if (!value.getAsInteger(0, addressing_bits)) {
           addressable_bits.SetHighmemAddressableBits(addressing_bits);
         }
+      } else if (key.compare("swbreak") == 0 || key.compare("hwbreak") == 0) {
+        // There is nothing needs to be done for swbreak or hwbreak since
+        // the value is expected to be empty
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp:2354]: This code is run by lldb when parsing a stop packet from the gdbserver, so this comment should also note that lldb's default is to act in the same way as swbreak or hwbreak does, that's why we take no action on it here.

I think making this whole thing a comment is also a good idea, so we don't trip up static analysis tools. Best place for it I think is after the last else if, something like:

```
// swbreak and hwbreak are also expected keys, but we don't need to change our behaviour for them because...
```

Comment (xusheng6) [reply lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp]: Hi @DavidSpickett, thx for the reply! I have address your comments in the last commits

**Comment by DavidSpickett** [comment]
On the testing, lldb sends this qsupported value regardless of what the remote sends. So there's nothing to do there unless you just repeat the feature list. There are some tests that look at lldb-server's qsupported values, but I don't see any for the client lldb.

You could check we don't crash when seeing swbreak/hwbreak in a stop response, but it's the same as checking we don't crash on any other unknown key in there. Since you can't observe any behaviour change from swbreak/hwbreak, so I don't think that has much value either.

What you could do is write a test where lldb connects to a mock gdbserver that claims to be an architecture where the correction to addresses would be done by a gdb server (GDB's gdbserver I mean). Then via lldb check that the stopped location is unmodified. You could then run the test with swbreak / hwbreak / neither of those in the stop info and each time lldb will report the value unchanged.

So in the unlikely case that we decided to change how lldb behaves, the test would fail. `lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py` might be a good starting point.

**Comment by DavidSpickett** [comment]
Also there is probably a qsupported parsing function in lldb-server, please add a comment there to say we consume lldb's swbreak/hwbreak feature but it doesn't change the behaviour of lldb-server.

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp [hunk 2]
```diff
@@ -2353,6 +2353,10 @@ StateType ProcessGDBRemote::SetThreadStopInfo(StringExtractor &stop_packet) {
         uint32_t reg = UINT32_MAX;
         if (!key.getAsInteger(16, reg))
           expedited_register_map[reg] = std::string(std::move(value));
+      } else if (key.compare("swbreak") == 0 || key.compare("hwbreak") == 0) {
+        // swbreak and hwbreak are also expected keys, but we don't need to
+        // change our behaviour for them because lldb always expects the remote
+        // to adjust the program counter (if relevant, e.g., for x86 targets)
```
Comment (DavidSpickett) [inline lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp:2359]: I don't think we need the actual `else if`. Since `if condition do nothing` looks like a programming mistake. The comment is fine on its own here.

**Comment by xusheng6** [comment]
> Also there is probably a qsupported parsing function in lldb-server, please add a comment there to say we consume lldb's swbreak/hwbreak feature but it doesn't change the behaviour of lldb-server.

Fixed in https://github.com/llvm/llvm-project/pull/102873/commits/d0851d4ff7e049d0c7537f5bd6b72bd66b29474a

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp (hunk 2 above)
Comment (xusheng6) [reply lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp]: Fixed in https://github.com/llvm/llvm-project/pull/102873/commits/d61ea562c82eab27ae2cc460b37f2f0d27961c1c

**Comment by DavidSpickett** [comment]
> or do we already have some infra that I can use?

`lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py` is an example of that infrastructure. The `threadStopInfo` is where you would insert the swbreak hwbreak key.

In fact, if i386 is an architecture where this correction of PC might happen (or not) you could just extend that test. The result should be the same whether the mock gdbserver returns "swbreak" "hwbreak" or leaves that field out completely.

If i386 isn't an architecture where correction would be done, you should be able to find some other target xml stubs elsewhere in tests. I don't think this test case is i386 specific. It can be tricky because that XML needs to include a minimal set of registers before lldb will function, so if in doubt, copy paste a working one.

> By the way, do I always need some unit test change to get a PR accepted? In this particular case I do not see a compelling reason to add a new test, though if this is a LLVM development policy then I will start looking into it.

Not 100% of the time but you will always have to justify why it does not have tests, or has the sort of tests that it has. This justification is useful for auditing code later, it also serves as a guide to anyone trying to reproduce an old bug that has no test cases.

https://llvm.org/docs/DeveloperPolicy.html#test-cases is written from the llvm perspective but applies to lldb as well https://lldb.llvm.org/resources/contributing.html#test-infrastructure.

In this case because no one does lldb -> gdbserver testing within the llvm project, so my worry is that this "easy fix" will get forgotten over time and someone will remove it as dead code or forget it in a refactoring. This is not a case of "if it has no tests it will get deleted" but it will certainly be at higher risk.

We have had cases like this before for example, someone fixed a bug handling an msp430 simulator and the test for that replays the packets that it sent to lldb so we don't have to have the actual simulator to hand.

**Comment by DavidSpickett** [comment]
AArch64 for example would be:
```
<?xml version="1.0"?>
<target version="1.0">
  <architecture>aarch64</architecture>
  <feature name="org.gnu.gdb.aarch64.core">
    <reg name="pc" bitsize="64"/>
    <reg name="x0" regnum="0" bitsize="64"/>
    <reg name="cpsr" regnum="33" bitsize="32"/>
  </feature>
</target>
```

**Comment by xusheng6** [comment]
> > or do we already have some infra that I can use?
> 
> `lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py` is an example of that infrastructure. The `threadStopInfo` is where you would insert the swbreak hwbreak key.
> 
> In fact, if i386 is an architecture where this correction of PC might happen (or not) you could just extend that test. The result should be the same whether the mock gdbserver returns "swbreak" "hwbreak" or leaves that field out completely.
> 
> If i386 isn't an architecture where correction would be done, you should be able to find some other target xml stubs elsewhere in tests. I don't think this test case is i386 specific. It can be tricky because that XML needs to include a minimal set of registers before lldb will function, so if in doubt, copy paste a working one.
> 
> > By the way, do I always need some unit test change to get a PR accepted? In this particular case I do not see a compelling reason to add a new test, though if this is a LLVM development policy then I will start looking into it.
> 
> Not 100% of the time but you will always have to justify why it does not have tests, or has the sort of tests that it has. This justification is useful for auditing code later, it also serves as a guide to anyone trying to reproduce an old bug that has no test cases.
> 
> https://llvm.org/docs/DeveloperPolicy.html#test-cases is written from the llvm perspective but applies to lldb as well https://lldb.llvm.org/resources/contributing.html#test-infrastructure.
> 
> In this case because no one does lldb -> gdbserver testing within the llvm project, so my worry is that this "easy fix" will get forgotten over time and someone will remove it as dead code or forget it in a refactoring. This is not a case of "if it has no tests it will get deleted" but it will certainly be at higher risk.
> 
> We have had cases like this before for example, someone fixed a bug handling an msp430 simulator and the test for that replays the packets that it sent to lldb so we don't have to have the actual simulator to hand.

Yes, i386 is an architecture where the PC adjustment happens, and I have tentatively added a unit test for it in https://github.com/llvm/llvm-project/pull/102873/commits/55f9473b8832723b96db45103bf4d5aa0b10da90

**Comment by DavidSpickett** [comment]
The test content is fine, but I was assuming that we'd extend the existing `TestStopPCs.py` to do the same thing in less code. If that test had 1 more thread, you could have normal / swbreak / hwbreak threads in one test case.

File: lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py [hunk 3]
```diff
@@ -10,13 +10,15 @@ class TestStopPCs(GDBRemoteTestBase):
     def test(self):
         class MyResponder(MockGDBServerResponder):
             def haltReason(self):
-                return "T02thread:1ff0d;threads:1ff0d,2ff0d;thread-pcs:10001bc00,10002bc00;"
+                return "T02thread:1ff0d;threads:1ff0d,2ff0d,3ff0d;thread-pcs:10001bc00,10002bc00,10003bc00;"
 
             def threadStopInfo(self, threadnum):
                 if threadnum == 0x1FF0D:
```
Comment (DavidSpickett) [inline lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py:16]: One more comment here please :)

Something like:
# lldb should treat the default halt reason, hwbreak and swbreak in the same way. Which is that it expects the stub to have corrected the PC already, so lldb should not modify it further.

File: lldb/tools/debugserver/source/RNBRemote.cpp [hunk 4]
```diff
@@ -3594,6 +3594,9 @@ rnb_err_t RNBRemote::HandlePacket_qSupported(const char *p) {
   reply << "SupportedWatchpointTypes=x86_64;";
 #endif
 
+  // We consume lldb's swbreak/hwbreak feature, but it doesn't change the
+  // behaviour of lldb-server. We always adjust the program counter for targets
+  // like x86
```
Comment (DavidSpickett) [inline lldb/tools/debugserver/source/RNBRemote.cpp:3599]: Sorry I missed that this is in `debugserver` not `lldb-server`. Confusing I know, but Apple platforms use debugserver which shares some common code.

This comment should go in `GDBRemoteCommunicationServerLLGS::HandleFeature` instead, just after the `// check for client features` for loop should be fine.

File: lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py (hunk 3 above)
Comment (xusheng6) [reply lldb/test/API/functionalities/gdb_remote_client/TestStopPCs.py:18]: Now fixed in https://github.com/llvm/llvm-project/commit/51a356b384f28cce3b2cd874fbba139414b0e207

File: lldb/tools/debugserver/source/RNBRemote.cpp (hunk 4 above)
Comment (xusheng6) [reply lldb/tools/debugserver/source/RNBRemote.cpp]: Now fixed in https://github.com/llvm/llvm-project/commit/51a356b384f28cce3b2cd874fbba139414b0e207

**Comment by DavidSpickett** [comment]
Thanks for the contribution! The test especially, it will keep us honest and protect your downstream tools going forward.

File: lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerLLGS.cpp [hunk 5]
```diff
@@ -4245,6 +4245,10 @@ std::vector<std::string> GDBRemoteCommunicationServerLLGS::HandleFeatures(
             .Case("vfork-events+", Extension::vfork)
             .Default({});
 
+  // We consume lldb's swbreak/hwbreak feature, but it doesn't change the
+  // behaviour of lldb-server. We always adjust the program counter for targets
+  // like x86
```
Comment (jasonmolenda) [inline lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerLLGS.cpp:4250]: Please end the comment with a period.

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp [hunk 6]
```diff
@@ -2354,6 +2354,9 @@ StateType ProcessGDBRemote::SetThreadStopInfo(StringExtractor &stop_packet) {
         if (!key.getAsInteger(16, reg))
           expedited_register_map[reg] = std::string(std::move(value));
       }
+      // swbreak and hwbreak are also expected keys, but we don't need to
+      // change our behaviour for them because lldb always expects the remote
+      // to adjust the program counter (if relevant, e.g., for x86 targets)
```
Comment (jasonmolenda) [inline lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp:2359]: Please end the comment with a period.

**Review by jasonmolenda — COMMENTED** [review]
Thanks for writing up the patch. We do see some handling of this behavior for x86 in lldb, e.g. ProcessWindowsNative, and KDP protocol support with x86 Darwin kernel debugging, also `breakpoint-pc-offset` in ProcessGDBRemote.  But we do assume that the pc value reported by a thread that hit a breakpoint will be the start of the breakpoint instruction, not the end.

The only question I have is -- if we are talking to a stub that supports `swbreak`/`hwbreak`, and we get a stop packet *without* those that hit a breakpoint, do we need to decr the pc value?  I'm guessing gdbserver et al don't report a `reason:breakpoint` key-value pair in the stop packet.  Should we treat the presence of `swbreak` or `hwbreak` as equivalent to receiving a `reason:breakpoint` in the packet (see the `reason` argument passed to `ProcessGDBRemote::SetThreadStopInfo`) to unambiguously indicate that a breakpoint was hit by this thread?

**Comment by jasonmolenda** [comment]
oh lol I missed that this was already merged.  But I am curious what you think about treating `swbreak`/`hwbreak` as equivalent to having received `reason:breakpoint`.

**Comment by jasonmolenda** [comment]
Just to be clear, if I'm understanding the packet we'll be getting back, we have no indication that we hit the breakpoint, we only show that we are stopped at an address which has a breakpoint.  Current lldb stepping behavior will work -- because the rule is, when we stop at a breakpoint address, we will say we hit the breakpoint.  I am refining a patch https://github.com/llvm/llvm-project/pull/96260 which changes this behavior -- we handle "instruction stepped / stopped at a breakpoint" differently than "hit a breakpoint".  I worry this difference will be lost with a stub that reports `swbreak`/`hwbreak`, stepping won't work correctly, and we won't capture it in the testsuite or on any of our CI bots.

**Comment by xusheng6** [comment]
> Just to be clear, if I'm understanding the packet we'll be getting back, we have no indication that we hit the breakpoint, we only show that we are stopped at an address which has a breakpoint. Current lldb stepping behavior will work -- because the rule is, when we stop at a breakpoint address, we will say we hit the breakpoint. I am refining a patch #96260 which changes this behavior -- we handle "instruction stepped / stopped at a breakpoint" differently than "hit a breakpoint". I worry this difference will be lost with a stub that reports `swbreak`/`hwbreak`, stepping won't work correctly, and we won't capture it in the testsuite or on any of our CI bots.

My work mainly concerns the case when lldb is connected to a gdbserver, and as far as I can tell, gdbserver does not send a `reason:breakpoint` packet at all. Maybe lldb-server sends it? I am not sure

Also, I do not think lldb itself is adjusting the PC -- I think lldb-server does it, and that is also the reason why my PR did not need to alter the lldb behavior at all. lldb always expects the remote to have adjusted the PC if necessary, and it just uses whatever value that is reported

**Comment by labath** [comment]
> > Just to be clear, if I'm understanding the packet we'll be getting back, we have no indication that we hit the breakpoint, we only show that we are stopped at an address which has a breakpoint. Current lldb stepping behavior will work -- because the rule is, when we stop at a breakpoint address, we will say we hit the breakpoint. I am refining a patch #96260 which changes this behavior -- we handle "instruction stepped / stopped at a breakpoint" differently than "hit a breakpoint". I worry this difference will be lost with a stub that reports `swbreak`/`hwbreak`, stepping won't work correctly, and we won't capture it in the testsuite or on any of our CI bots.
> 
> My work mainly concerns the case when lldb is connected to a gdbserver, and as far as I can tell, gdbserver does not send a `reason:breakpoint` packet at all. Maybe lldb-server sends it?

Yes, it does.

> Also, I do not think lldb itself is adjusting the PC -- I think lldb-server does it, and that is also the reason why my PR did not need to alter the lldb behavior at all. lldb always expects the remote to have adjusted the PC if necessary, and it just uses whatever value that is reported

That is true, but I believe Jason is saying something slightly different. Currently you are able to use lldb+gdbserver because lldb treats a stop as a breakpoint hit every time we stop and the PC value is equal to one of the breakpoints. Jason's [patch](https://github.com/llvm/llvm-project/pull/96260) will change that and have lldb report a breakpoint hit only if it server tells it that was the reason for the stop. lldb-server does that (`reason:breakpoint`), and everything will work fine, but that will most likely break your use case.

To (preemtively) fix that, you should probably change lldb to recognize the gdb response (`swbreak`) and treat it the same way as the one from lldb-server. Ideally, you should also add a test to make sure this works (and stays working) -- for that, you could probably extend the test you added here to check that lldb reports the correct stop reason.

**Comment by xusheng6** [comment]
> > > Just to be clear, if I'm understanding the packet we'll be getting back, we have no indication that we hit the breakpoint, we only show that we are stopped at an address which has a breakpoint. Current lldb stepping behavior will work -- because the rule is, when we stop at a breakpoint address, we will say we hit the breakpoint. I am refining a patch #96260 which changes this behavior -- we handle "instruction stepped / stopped at a breakpoint" differently than "hit a breakpoint". I worry this difference will be lost with a stub that reports `swbreak`/`hwbreak`, stepping won't work correctly, and we won't capture it in the testsuite or on any of our CI bots.
> > 
> > 
> > My work mainly concerns the case when lldb is connected to a gdbserver, and as far as I can tell, gdbserver does not send a `reason:breakpoint` packet at all. Maybe lldb-server sends it?
> 
> Yes, it does.
> 
> > Also, I do not think lldb itself is adjusting the PC -- I think lldb-server does it, and that is also the reason why my PR did not need to alter the lldb behavior at all. lldb always expects the remote to have adjusted the PC if necessary, and it just uses whatever value that is reported
> 
> That is true, but I believe Jason is saying something slightly different. Currently you are able to use lldb+gdbserver because lldb treats a stop as a breakpoint hit every time we stop and the PC value is equal to one of the breakpoints. Jason's [patch](https://github.com/llvm/llvm-project/pull/96260) will change that and have lldb report a breakpoint hit only if it server tells it that was the reason for the stop. lldb-server does that (`reason:breakpoint`), and everything will work fine, but that will most likely break your use case.
> 
> To (preemtively) fix that, you should probably change lldb to recognize the gdb response (`swbreak`) and treat it the same way as the one from lldb-server. Ideally, you should also add a test to make sure this works (and stays working) -- for that, you could probably extend the test you added here to check that lldb reports the correct stop reason.

Oh I see your point now, and I also see the lldb is handling a `reason:xxxx` packet from the lldb-server. In this sense, I think it is fair to treat "swbreak/hwbreak" in the same way as "reason:breakpoint".

@jasonmolenda do you think you can handle this along with your patch, or you think I should do something for it preemptively as suggested by [labath](https://github.com/labath)? I personally prefer the former case because I am quite new to the lldb code base

**Comment by jasonmolenda** [comment]
> > To (preemtively) fix that, you should probably change lldb to recognize the gdb response (`swbreak`) and treat it the same way as the one from lldb-server. Ideally, you should also add a test to make sure this works (and stays working) -- for that, you could probably extend the test you added here to check that lldb reports the correct stop reason.
> 
> Oh I see your point now, and I also see the lldb is handling a `reason:xxxx` packet from the lldb-server. In this sense, I think it is fair to treat "swbreak/hwbreak" in the same way as "reason:breakpoint".
> 
> @jasonmolenda do you think you can handle this along with your patch, or you think I should do something for it preemptively as suggested by [labath](https://github.com/labath)? I personally prefer the former case because I am quite new to the lldb code base

No problem, I'll make that change in ProcessGDBRemote when I re-land my patch (I have a few outstanding issues the CI bots found when I first landed it).  My change will be untested, but it is a simple change.  We already fake up a reason:watchpoint stop reason when we get `watch`/`rwatch`/`awatch` in a stop reply packet today, it will be the same kind of thing.
