### PR TITLE
[analyzer] Fix use-after-free in CheckerContext::getMacroNameOrSpelling

### LINKED ISSUE #194136: [clang][analyzer] CheckerContext::getMacroNameOrSpelling returns a dangling StringRef
### Description

`clang::ento::CheckerContext::getMacroNameOrSpelling()` can return a
`llvm::StringRef` backed by a dead stack buffer.

Current implementation:

```cpp
StringRef CheckerContext::getMacroNameOrSpelling(SourceLocation &Loc) {
  if (Loc.isMacroID())
    return Lexer::getImmediateMacroName(Loc, getSourceManager(),
                                        getLangOpts());
  SmallString<16> buf;
  return Lexer::getSpelling(Loc, buf, getSourceManager(), getLangOpts());
}
```

When the token spelling needs cleaning, `Lexer::getSpelling()` returns a
`StringRef` backed by the caller-provided buffer. Here that buffer is the local
`SmallString<16> buf`, so the returned `StringRef` dangles immediately after
`getMacroNameOrSpelling()` returns.

The strongest in-tree trigger is in
`GenericTaintChecker::taintUnsafeSocketProtocol()`:

```cpp
SourceLocation DomLoc = Call.getArgExpr(0)->getExprLoc();
StringRef DomName = C.getMacroNameOrSpelling(DomLoc);
bool SafeProtocol = DomName == "AF_SYSTEM" || DomName == "AF_LOCAL" ||
                    DomName == "AF_UNIX" || DomName == "AF_RESERVED_36";
```

If `DomLoc` is not a macro location and the token spelling needs cleaning, the
comparison reads from dead stack storage.

### Reproducer

Save as `generic_taint_socket_line_continuation.c`:

```c
extern int socket(int, int, int);

int AF\
_UNIX = 1;

int trigger(void) {
  return socket(AF\
_UNIX, 0, 0);
}
```

Run with an ASan build of `clang` of current `origin/main` at 1348766d1d686b8825bdaa2f6638c1783d76a4a7 :

```bash
ASAN_OPTIONS=detect_stack_use_after_return=1:detect_leaks=0:halt_on_error=1 \
  bin/clang -cc1 -analyze \
  -analyzer-checker=optin.taint.GenericTaint \
  generic_taint_socket_line_continuation.c
```

```
==3==ERROR: AddressSanitizer: stack-use-after-return on address 0x7b332ab27338 at pc 0x555c7470fe16 bp 0x7ffec606b7c0 sp 0x7ffec606af68
  READ of size 7 at 0x7b332ab27338 thread T0
      #0 0x555c7470fe15 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned
  long) (/tmp/clang-23-head-repro+0x2b5de15) (BuildId: 9c65e8349a110791df6abfceca5a13bebf0d1cee)
      #1 0x555c747102bc in bcmp (/tmp/clang-23-head-repro+0x2b5e2bc) (BuildId: 9c65e8349a110791df6abfceca5a13bebf0d1cee)
      #2 0x555c7bf6ac5e in llvm::operator==(llvm::StringRef, llvm::StringRef) llvm/include/llvm/ADT/StringRef.h:914:10
      #3 0x555c7bf6ac5e in (anonymous namespace)::GenericTaintChecker::taintUnsafeSocketProtocol(clang::ento::CallEvent const&,
  clang::ento::CheckerContext&) const clang/lib/
  StaticAnalyzer/Checkers/GenericTaintChecker.cpp
```

### PR DESCRIPTION
**Pull request by steakhal**
This UAF bug was introduced 14 years ago, in 43de767b55c07.
The first use of this API was in 3b754b25bde4914e5ab693e7db9533c3260e926e, roughly around the same era.
It was dormant because the first param of `socket` and friends are macros, and those didn't trigger this UAF.

I decided to go against adding a test because I figure that would be not really meaningful.

Fixes #194136

### CODE REVIEW

**Comment by steakhal** [comment]
Offline I've discussed this change with @Xazax-hun and we agreed on not changing the used API - and only focus the patch on fixing the lifetime issue.

**Review by Xazax-hun — APPROVED** [review]
LGTM!

File: clang/lib/StaticAnalyzer/Core/CheckerContext.cpp [hunk 1]
```diff
@@ -128,12 +128,13 @@ bool CheckerContext::isHardenedVariantOf(const FunctionDecl *FD,
...
+std::string CheckerContext::getMacroNameOrSpelling(SourceLocation &Loc) {
+  const auto &SM = getSourceManager();
+  const auto &LO = getLangOpts();
   if (Loc.isMacroID())
-    return Lexer::getImmediateMacroName(Loc, getSourceManager(),
-                                             getLangOpts());
+    return Lexer::getImmediateMacroName(Loc, SM, LO).str();
   SmallString<16> buf;
-  return Lexer::getSpelling(Loc, buf, getSourceManager(), getLangOpts());
+  return Lexer::getSpelling(Loc, buf, SM, LO).str();
```
Comment (NagyDonat) [inline clang/lib/StaticAnalyzer/Core/CheckerContext.cpp]: Perhaps capitalize the variable name `buf` given that you're already touching this code?

**Review by NagyDonat — APPROVED** [review]
LGTM!

File: clang/lib/StaticAnalyzer/Core/CheckerContext.cpp (hunk 1 above)
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/CheckerContext.cpp]: Addressed in https://github.com/llvm/llvm-project/pull/194174/commits/48ff729303c058f52526efe6ad3d1a0af2f3ab75
