### PR TITLE
[mlir] allow function type cloning to fail

### LINKED ISSUE #131142: [MLIR] mlir::LLVM::LLVMFunctionType::clone triggers assertion failure: `results.size() == 1 && "expected a single result type"'
Test commit: https://github.com/llvm/llvm-project/commit/9e91725fd4d4ee30e98ab2682f93b423590a4ade

Steps to reproduce:
```shell
mlir-opt test.mlir --pass-pipeline="builtin.module(convert-func-to-llvm)" | mlir-opt --test-funerase-result 
```
Test case:
```mlir
func.func private @mlirAsyncRuntimeAddRef(!llvm.ptr, i64)
```
Crash trace:
```console
mlir-opt: /home/workdir/llvm-project/mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp:235: LLVMFunctionType mlir::LLVM::LLVMFunctionType::clone(TypeRange, TypeRange) const: Assertion `results.size() == 1 && "expected a single result type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/workdir/llvm-project/build/bin/./mlir-opt --test-func-erase-result
 #0 0x0000565228775228 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x12d1228)
 #1 0x0000565228772d4e llvm::sys::RunSignalHandlers() (/home/workdir/llvm-project/build/bin/./mlir-opt+0x12ced4e)
 #2 0x0000565228775c31 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007feb9538f520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007feb953e39fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007feb9538f476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007feb953757f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007feb9537571b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007feb95386e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000565229dd1326 mlir::LLVM::LLVMFunctionType::clone(mlir::TypeRange, mlir::TypeRange) const (/home/workdir/llvm-project/build/bin/./mlir-opt+0x292d326)
#10 0x0000565229ca428e mlir::detail::FunctionOpInterfaceInterfaceTraits::Model<mlir::LLVM::LLVMFuncOp>::cloneTypeWith(mlir::detail::FunctionOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::TypeRange, mlir::TypeRange) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x280028e)
#11 0x000056522b8aa1a6 mlir::FunctionOpInterface::getTypeWithoutResults(llvm::BitVector const&) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x44061a6)
#12 0x000056522beeb6d0 (anonymous namespace)::TestFuncEraseResult::runOnOperation() TestFunc.cpp:0:0
#13 0x000056522b86bcd3 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43c7cd3)
#14 0x000056522b86c572 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43c8572)
#15 0x000056522b86ed4e mlir::PassManager::run(mlir::Operation*) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43cad4e)
#16 0x000056522b8672cb performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#17 0x000056522b866f23 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#18 0x000056522b912475 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x446e475)
#19 0x000056522b860b82 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43bcb82)
#20 0x000056522b860e33 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43bce33)
#21 0x000056522b861042 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/home/workdir/llvm-project/build/bin/./mlir-opt+0x43bd042)
#22 0x00005652287549af main (/home/workdir/llvm-project/build/bin/./mlir-opt+0x12b09af)
#23 0x00007feb95376d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#24 0x00007feb95376e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#25 0x0000565228754505 _start (/home/workdir/llvm-project/build/bin/./mlir-opt+0x12b0505)

```

### PR DESCRIPTION
**Pull request by ftynse**
`FunctionOpInterface` assumed the fact that the function type (attribute of the operation) can be cloned with arbirary lists of function arguments and results to support argument and result list mutation. This is not always correct, in particular, LLVM dialect functions require exactly one result making it impossible to erase the result.

Allow function type cloning to fail and propagate this failure through various APIs that use it. The common assumption is that existing IR has not been modified.

Fixes #131142.

Reland a8c7ecdcbc3e89b493b495c6831cc93671c3b844 / #136300.

### CODE REVIEW

**Review by j2kun — APPROVED** [review]
Seems like a straightforward change, LGTM!

File: mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp [hunk 1]
```diff
@@ -232,7 +232,10 @@ LLVMFunctionType::getChecked(function_ref<InFlightDiagnostic()> emitError,
 
 LLVMFunctionType LLVMFunctionType::clone(TypeRange inputs,
                                          TypeRange results) const {
-  assert(results.size() == 1 && "expected a single result type");
+  if (results.size() != 1 || !isValidResultType(results[0]))
+    return {};
+  if (!llvm::all_of(inputs, isValidArgumentType))
+    return {};
   return get(results[0], llvm::to_vector(inputs), isVarArg());
```
Comment (joker-eph) [inline mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp:239]: Can't we just use `getChecked` here?

Comment (ftynse) [reply mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp:239]: It emits a diagnostic that we don't want here. And we don't have an equivalent of `llvm::nulls` for diagnostics were we could just send it to the void. Overriding the handler locally sounds a bit too heavy here...
