### PR TITLE
[clang-tidy] Fix false positives with deducing this in `readability-convert-member-functions-to-static` check

### LINKED ISSUE #141381: False-positive `readability-convert-member-functions-to-static` when using explicit object parameters
```c++
#include <print>
#include <string>

struct Hello {
  std::string str_;

  void hello(this Hello &self) { std::println("Hello, {0}!", self.str_); }
};

int main() {
  Hello hi{"world"};
  hi.hello();
  return 0;
}
```
Saving this file as `explicit_object_param.cpp`, I get
```
$ clang-tidy --checks=readability-convert-member-functions-to-static explicit_object_param.cpp -- --std=c++23
1 warning generated.
/home/chriselrod/Documents/progwork/cxx/misc/explicit_object_param.cpp:7:8: warning: method 'hello' can be made static [readability-convert-member-functions-to-static]
    7 |   void hello(this Hello &self) { std::println("Hello, {0}!", self.str_); }
      |        ^
      |   static 
```

Of course, `static` is illegal there
```
explicit_object_param.cpp:7:21: error: an explicit object parameter cannot appear in a static function
    7 |   static void hello(this Hello &self) { std::println("Hello, {0}!", self.str_); }
      |   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by flovent**
Fixes #141381.

Add check for `DeclRefExpr` which points to an explicit object parameter.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// RUN: %check_clang_tidy -std=c++23 %s readability-convert-member-functions-to-static %t
+
+namespace std{
+  class string {};
+  void println(const char *format, const std::string &str) {}
+}
+
+namespace PR141381 {
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp:8]: Nit: don't think that this has any profits for readability/maintainability.
AFAIK such namespaces are used for small bug-fixes that are usually placed in big test files, so with such namespaces it's easier to navigate through tests.
Your file is completely new, and there is no need for such namespace.

**Review by vbvictor — CHANGES_REQUESTED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+struct Hello {
+  std::string str_;
+
+  void hello(this Hello &self) { std::println("Hello, {0}!", self.str_); }
```
[the remark this answers is not in the document]
Comment (flovent) [reply clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp]: testcases added.

File: clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStatic.cpp [hunk 3]
```diff
@@ -79,10 +79,10 @@ void ConvertMemberFunctionsToStatic::registerMatchers(MatchFinder *Finder) {
       cxxMethodDecl(
           isDefinition(), isUserProvided(),
           unless(anyOf(
-              isExpansionInSystemHeader(), isVirtual(), isStatic(),
-              hasTrivialBody(), isOverloadedOperator(), cxxConstructorDecl(),
-              cxxDestructorDecl(), cxxConversionDecl(), isTemplate(),
-              isDependentContext(),
+              isExplicitObjectMemberFunction(), isExpansionInSystemHeader(),
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/readability/ConvertMemberFunctionsToStatic.cpp:82]: Please place `isExplicitObjectMemberFunction()` after `cxxConversionDecl()`. These predicates are checked from first to last in order, so for efficiency I'd put it after `cxxConversionDecl()`.

File: clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp [hunk 4]
```diff
@@ -0,0 +1,22 @@
+// RUN: %check_clang_tidy -std=c++23 %s readability-convert-member-functions-to-static %t
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/readability/convert-member-functions-to-static-deducing-this.cpp:1]:
```suggestion
// RUN: %check_clang_tidy -std=c++23-or-later %s readability-convert-member-functions-to-static %t
```

**Review by vbvictor — APPROVED** [review]
LGTM

**Comment by vbvictor** [comment]
Could you please rebase on fresh main, and I will land the PR.

PS. Sorry for mentioning it again, but I've seen a github runner about private email on you [other PR](https://github.com/llvm/llvm-project/pull/143292) and It's a developer policy to have it public (https://llvm.org/docs/DeveloperPolicy.html#email-addresses). If you don't have strong privacy concerns of revealing your email, could you please do it?

**Comment by flovent** [comment]
Rebased and changed my email to public.

Different with this PR, I use github noreply email in my latest PR to commit, do I need to rebase to change it or it will automaticly update to my public email when merging like it will transfter to noreply email when i keep it private like [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) says?

**Review by carlosgalvezp — APPROVED** [review]
LGTM!

**Comment by vbvictor** [comment]
When merging, your new public email will be used, now it says
"This commit will be authored by flbven@protonmail.com." 

So you don't have to do anything with your commits
