### PR TITLE
[llvm-exegesis] Close file descriptors after use

### LINKED ISSUE #86583: [llvm-exegesis] Not closing file descriptors after use
The subprocess executor is currently not closing file descriptors after they have been used, simply leaving them open. This can cause issues in downstream projects that execute/benchmark many blocks before exiting:
```
Failed to annotate block: INTERNAL: Failed to create a pipe for interprocess communication between llvm-exegesis and the benchmarking subprocess: Too many open files
```

### PR DESCRIPTION
**Pull request by boomanaiden154**
There are several insstances in the subprocess executor in llvm-exegesis where we fail to close file descriptors after using them. This leaves them open, which can cause issues later on if a third-party binary is using the exegesis libraries and executing many blocks before exiting. Leaving the descriptors open until process exit is also bad practice. This patch fixes that by explicitly calling close() when we are done with a specific file descriptor.

This patch fixes #86583.

### CODE REVIEW

File: llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp [hunk 1]
```diff
@@ -317,6 +317,7 @@ class SubProcessFunctionExecutorImpl
     int CounterFileDescriptor = Counter->getFileDescriptor();
     Error SendError =
         sendFileDescriptorThroughSocket(WriteFD, CounterFileDescriptor);
+    close(WriteFD);
```
Comment (mshockwave) [inline llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:320]: should we use `make_scope_exit` to make sure this fd is closed no matter how we leave this function?

Comment (boomanaiden154) [reply llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp]: Good point. I've used it within all of these functions to ensure that the file descriptor is properly closed upon exiting the function (especially with error conditions). Thanks for pointing this out! I hadn't heard about `make_scope_exit` before.

**Review by legrosbuffle — APPROVED** [review]
