### PR TITLE
[Clang] Do not treat Foo -> const Foo conversion sequences as perfect

### LINKED ISSUE #147374: [clang] Wrong rewritten `operator==` selected
The following minimal examples are used as a reference: 

**Example A** (https://godbolt.org/z/5Mvbj7ePd):
```cpp
#include <string>
#include <iostream>

class Bar {
public:
    explicit Bar(const std::string aValue) : mValue{aValue} {};

    bool operator==(const std::string aValue) const { 
        std::cout << "bool operator==(const std::string aValue) const\n";
        return aValue == mValue; 
    };

    friend bool operator==(const std::string aLhs, Bar aRhs) { return aRhs == aLhs; }
    
private:
    std::string mValue;
};

int main() {
    auto other1 = Bar("Bar");
    [[ maybe_unused ]] auto equal = other1 == "Bar";
}
```

**Example B** (https://godbolt.org/z/aM5f8odqa):

```cpp
#include <string>
#include <iostream>

template<typename T>
class Foo {
public:
    explicit Foo(const T aValue) : mValue{aValue} {};

    bool operator==(const T aValue) const { 
        std::cout << "bool operator==(const T aValue) const\n";
        return aValue == mValue; 
    };

    friend bool operator==(const T aLhs, Foo aRhs) { return aRhs == aLhs; }
    
private:
    T mValue;
};

int main() {
    auto thing1 = Foo<std::string>("Foo");
    [[maybe_unused]] auto equal = thing1 == "Foo";
}
```

In Clang 21 (and the most recent trunk at the time of writing), **Example A** results in the following warning being emitted:
```
<source>:13:62: warning: all paths through this function will call itself [-Winfinite-recursion]
   13 |     friend bool operator==(const std::string aLhs, Bar aRhs) { return aRhs == aLhs; }
      |      
```

In older versions (e.g., Clang 20.1.0), no warning is emitted. `const`-qualifying `aRhs` resolves the warning in Clang 21. Is this a false positive? I'm not sure I understand what Clang deems to be infinitely recursive here.

Notably, when using a class template as in **Example B**, no warning is emitted.

### PR DESCRIPTION
**Pull request by cor3ntin**
For implicit object arguments.
This fixes a regression introduced by the "perfect match" overload resolution mechanism introduced in 8c5a307.

Note that GCC allows the ambiguity between a const and non-const candidate to be resolved. But this patch focuses on restoring the Clang 20 behavior, and to fix the cases which we did resolve incorrectly.

Fixes #147374

### CODE REVIEW

File: clang/include/clang/Sema/Overload.h [hunk 1]
```diff
@@ -448,11 +453,12 @@ class Sema;
 #endif
         return true;
       }
-      if (!C.hasSameType(getFromType(), getToType(2)))
-        return false;
       if (BindsToRvalue && IsLvalueReference)
         return false;
-      return true;
+      if (IsImplicitObjectArgumentQualificationConversion) {
```
Comment (erichkeane) [inline clang/include/clang/Sema/Overload.h]: Nit: No curleys here.

File: clang/lib/Sema/SemaOverload.cpp [hunk 2]
```diff
@@ -5305,10 +5306,10 @@ TryReferenceInit(Sema &S, Expr *Init, QualType DeclType,
     // FIXME: As a speculative fix to a defect introduced by CWG2352, we rank
     // a reference binding that performs a non-top-level qualification
     // conversion as a qualification conversion, not as an identity conversion.
-    ICS.Standard.Third = (RefConv &
-                              Sema::ReferenceConversions::NestedQualification)
-                             ? ICK_Qualification
-                             : ICK_Identity;
+    ICS.Standard.Third =
```
Comment (erichkeane) [inline clang/lib/Sema/SemaOverload.cpp]: Unrelated change?

**Review by erichkeane — APPROVED** [review]
2 nits, else LGTM.

**Comment by MatzeB** [comment]
FYI: This change breaks common thrift-generated code. Reduced example here shows the problem and produces "expression is not assignable" after this change but is accepted by all released gcc and clang versions as far as I can tell. No idea if the code is valid/invalid:
```
#include <exception>
struct TmsException : public std::exception {
  int _what;

  const char* what() const noexcept override { return ""; }

  template<typename..., typename T=int>
  T& what() & { return _what; }
};
int main() {
  TmsException E;
  E.what() = 42;
}
```

**Comment by alexfh** [comment]
Heads up: this commit causes a huge fallout in our codebase. We'll try to come up with some specific examples tomorrow.

**Comment by cor3ntin** [comment]
Thanks for the heads up!

I'm looking into it.

Reduced to 
```cpp
struct TmsException  {
  int _what;
  const char* what() const;

  template<typename T=int>
  int& what() & { return _what; }
};
int main() {
  TmsException E;
  E.what() = 42;
}
```

**Comment by bgra8** [comment]
Thanks for reverting @cor3ntin !

The fallout @alexfh refers too is caused by code that reduces to something similar to what @MatzeB reported.

**Comment by cor3ntin** [comment]
Sorry for the inconvenience. It was clearly not the right solution in hindsight. It may take me a while to figure out how to approach a fix to https://github.com/llvm/llvm-project/issues/147374
