### PR TITLE
[clang] Report narrowing conversions with const references

### LINKED ISSUE #63151: Clang does not detect narrowing conversion with const ref
Clang compiles

```cpp
struct A { A(const unsigned &x) {} };

int main(void) {
    A a { -1 };
    return 0;
}
```

without emitting any diagnostic, but GCC emits

```console
test.cpp: In function ‘int main()’:
test.cpp:4:14: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
    4 |     A a { -1 };
      |
```

I think it is correct to treat the program as ill formed in this case, but I'm not sure.

### PR DESCRIPTION
**Pull request by Fznamznon**
Fixes https://github.com/llvm/llvm-project/issues/63151

### CODE REVIEW

**Comment by Fznamznon** [comment]
Formatting trouble is intentional.

**Review by erichkeane — APPROVED** [review]
1 nit, otherwise LGTM

File: clang/lib/Sema/SemaInit.cpp [hunk 1]
```diff
@@ -10431,7 +10437,7 @@ static void DiagnoseNarrowingInInitList(Sema &S,
                                         : diag::warn_init_list_type_narrowing)
         << PostInit->getSourceRange()
         << PreNarrowingType.getLocalUnqualifiedType()
-        << EntityType.getLocalUnqualifiedType();
+        << EntityType.getLocalUnqualifiedType().getNonReferenceType();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaInit.cpp:10440]: Since this is supposed to remove local qualifiers, should the reference be removed first?  What happens with a `const int &` as is?

ALSO, does the pre-narrowing-type also need to have references removed?

Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:10440]: > Since this is supposed to remove local qualifiers, should the reference be removed first? What happens with a const int & as is?

Perhaps makes sense. I only removed reference since it is already removed from the pre-narrowing-type and I was a bit inspired by gcc messages https://godbolt.org/z/Tcv17Wxhc . I could leave reference type it as is, then the messages will look like:

```

struct A { A(const unsigned &x) {} };

int foo(const int &aba) {
    A a { -1 }; // constant expression evaluates to -1 which cannot be narrowed to type 'const unsigned int&'
    A b { aba }; // non-constant-expression cannot be narrowed from type 'int' to 'const unsigned int' in initializer list
    return 0;
}
```

Comment (erichkeane) [reply clang/lib/Sema/SemaInit.cpp:10440]: Why does leaving the reference type alone (which seems to be removed 'last' cause the const to stick around, and not the reference?

Comment (Fznamznon) [reply clang/lib/Sema/SemaInit.cpp:10440]: My guess is `getLocalUnqualifiedType` doesn't strip cv qualifiers from reference's pointee type, so we first should remove reference and then qualifiers to see plain `int` in the diagnostic.

Comment (erichkeane) [reply clang/lib/Sema/SemaInit.cpp]: I think we're talking past eachother then.  I was suggesting to remove the reference first, which would have us match GCC's behavior, right?  I think that is better than leaving it 'as is', but I was confused as to what is going on with the change on 10440 (removing the reference AFTER the qualifiers instead of before);

**Review by erichkeane — APPROVED** [review]
Looks like you got what I meant anyway, and we WERE just passionately agreeing with eachother :)  LGTM.

**Comment by Fznamznon** [comment]
> Looks like you got what I meant anyway, and we WERE just passionately agreeing with eachother :) LGTM.

Thanks!
Probably I was being a bit slow, lol

**Comment by alexfh** [comment]
The change in the diagnostic happens to make it much noisier than it was before. Our code was clean w.r.t. -Wc++11-narrowing, but now we see hundreds if not thousands of compilation breakages (we use -Werror, which turns out to be the only robust way to avoid backsliding). I think, the new behavior (though useful) needs to be guarded by a separate warning flag.

**Comment by erichkeane** [comment]
> The change in the diagnostic happens to make it much noisier than it was before. Our code was clean w.r.t. -Wc++11-narrowing, but now we see hundreds if not thousands of compilation breakages (we use -Werror, which turns out to be the only robust way to avoid backsliding). I think, the new behavior (though useful) needs to be guarded by a separate warning flag.

Looks like that was done here; https://github.com/llvm/llvm-project/pull/76094
