### PR TITLE
[InstCombine] Preserve signbit semantics of NaN with fold to fabs

### LINKED ISSUE #136646: [InstCombine] The sign bit of NaN is not preserved when folding `(X <= +/-0.0) ? (0.0 - X) : X to fabs(X)`
Reproducer: https://alive2.llvm.org/ce/z/2JaLU9
```

----------------------------------------
define half @src(half %x) {
#0:
  %gtzero = fcmp ugt half %x, 0x0000
  %negx = fsub half 0x0000, %x
  %fabs = select i1 %gtzero, half %x, half %negx
  ret half %fabs
}
=>
define half @src(half %x) nofree willreturn memory(none) {
#0:
  %fabs = fabs half %x
  ret half %fabs
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:
half %x = #xfd00 (SNaN)

Source:
i1 %gtzero = #x1 (1)
half %negx = #xff00 (QNaN)
half %fabs = #xfd00 (SNaN)

Target:
half %fabs = #x7d00 (SNaN)
Source value: #xfd00 (SNaN)
Target value: #x7d00 (SNaN)

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```
Related issues:
https://github.com/AliveToolkit/alive2/pull/1155
https://github.com/llvm/llvm-project/issues/59279

### PR DESCRIPTION
**Pull request by dtcxzyw**
As per the LangRef and IEEE 754-2008 standard, the sign bit of NaN is preserved if there is no floating-point operation being performed.
See also https://github.com/llvm/llvm-project/commit/862e35e25a68502433da0a8d0819448ff5745339 for reference.

Alive2: https://alive2.llvm.org/ce/z/QYtEGj
Closes https://github.com/llvm/llvm-project/issues/136646

### CODE REVIEW

**Comment by dtcxzyw** [comment]
No real-world impact.

File: llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp [hunk 1]
```diff
@@ -2793,7 +2793,11 @@ static Instruction *foldSelectWithFCmpToFabs(SelectInst &SI,
 
     // fold (X <= +/-0.0) ? (0.0 - X) : X to fabs(X), when 'Swap' is false
     // fold (X >  +/-0.0) ? X : (0.0 - X) to fabs(X), when 'Swap' is true
-    if (match(TrueVal, m_FSub(m_PosZeroFP(), m_Specific(X)))) {
+    // Note: We require "nnan" for this fold because fcmp ignores the signbit
+    //       of NAN, but IEEE-754 specifies the signbit of NAN values with
+    //       fneg/fabs operations.
+    if (cast<FPMathOperator>(CondVal)->hasNoNaNs() &&
+        match(TrueVal, m_FSub(m_PosZeroFP(), m_Specific(X)))) {
```
Comment (arsenm) [inline llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp:2800]: Can't you equivalently check the nnan on the fsub? or check isKnownNeverNan on X?

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp]: > or check isKnownNeverNan on X?

Done.

Comment (arsenm) [reply llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp]: nnan on the select also works? https://alive2.llvm.org/ce/z/R57ux5

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp]: Done

**Review by arsenm — APPROVED** [review]
