### PR TITLE
[DAG] select (sext m), (add X, C), X --> (add X, (and C, (sext m))))

### LINKED ISSUE #66101: [DAG] Failure to fold select(x, sub(x, c), m) -> sub(x, and(c,m))
https://godbolt.org/z/a1PczEM8a

If we're selecting a subtracting a non-constant we fold the select into a and:
```c
#include <x86intrin.h>
auto masked_select(__m128i a, __m128i b, __m128i x, __m128i y) {
    return _mm_blendv_epi8(a, _mm_sub_epi32(a, b), _mm_cmpgt_epi32(x,y));
}
```
```asm
masked_select(long long __vector(2), long long __vector(2), long long __vector(2), long long __vector(2)): # @masked_select(long long __vector(2), long long __vector(2), long long __vector(2), long long __vector(2))
  pcmpgtd %xmm3, %xmm2
  pand %xmm1, %xmm2
  psubd %xmm2, %xmm0
  retq
```
But for constants this fails, which on x86 can result in a BLENDV instruction, which is never faster than a AND
```c
#include <x86intrin.h>
auto masked_select_const(__m128i a, __m128i x, __m128i y) {
    __m128i b = _mm_set1_epi32(24);
    return _mm_blendv_epi8(a, _mm_sub_epi32(a, b), _mm_cmpgt_epi32(x,y));
}
```
```asm
masked_select_const(long long __vector(2), long long __vector(2), long long __vector(2)): # @masked_select_const(long long __vector(2), long long __vector(2), long long __vector(2))
  movdqa %xmm0, %xmm3
  movdqa .LCPI3_0(%rip), %xmm4 # xmm4 = [4294967272,4294967272,4294967272,4294967272]
  paddd %xmm0, %xmm4
  pcmpgtd %xmm2, %xmm1
  movdqa %xmm1, %xmm0
  blendvps %xmm0, %xmm4, %xmm3
  movaps %xmm3, %xmm0
  retq
```

### PR DESCRIPTION
**Pull request by elhewaty**
- [DAG][X86] Add tests for Folding select m, add(X, C), X --> add (X, and(C, m))(NFC)
- [DAG][X86] Fold select (sext m), (add X, C), X --> (add X, (and C, (sext m))))
- Fixes: https://github.com/llvm/llvm-project/issues/66101

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 1]
```diff
@@ -12070,6 +12070,15 @@ SDValue DAGCombiner::visitVSELECT(SDNode *N) {
   if (SDValue F = extractBooleanFlip(N0, DAG, TLI, false))
     return DAG.getSelect(DL, VT, F, N2, N1);
 
+  // select (sext m), (add X, C), X --> (add X, (and C, (sext m))))
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12073]: I think we need to check `TLI.getBooleanContents(N0.getValueType()) == TargetLowering::ZeroOrNegativeOneBooleanContent`. Otherwise there's no guarantee that `m` is all zeros or all ones.

Comment (elhewaty) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12073]: @topperc  I will update it now, but can you please explain why we need this?

Comment (topperc) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12073]: Some targets you use 00000001 as a true value for a vector instead of 11111111. So we need to check what kind of target we're optimizing for.

Comment (elhewaty) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12073]: @topperc done

File: llvm/test/CodeGen/X86/vselect.ll [hunk 2]
```diff
@@ -7,6 +7,38 @@
 ; Verify that we don't emit packed vector shifts instructions if the
 ; condition used by the vector select is a vector of constants.
 
+define <2 x i64> @masked_select_const(<2 x i64> %a, <2 x i64> %x, <2 x i64> %y) {
```
Comment (phoebewang) [inline llvm/test/CodeGen/X86/vselect.ll:10]: Use `<4 x i32>` to avoid unnecessary `bitcast`. And move the test to the end of the file since it's not directly related to above comments.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 3]
```diff
@@ -12070,6 +12070,17 @@ SDValue DAGCombiner::visitVSELECT(SDNode *N) {
...
+  if (N1.getOpcode() == ISD::ADD && N1.getOperand(0) == N2 && N1->hasOneUse() &&
+      DAG.isConstantIntBuildVectorOrConstantInt(N1.getOperand(1)) &&
+      N0.getScalarValueSizeInBits() == N1.getScalarValueSizeInBits() &&
+      TLI.getBooleanContents(N0.getValueType()) ==
+          TargetLowering::ZeroOrNegativeOneBooleanContent) {
```
Comment (phoebewang) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12078]: I wonder if this can prevent for AVX512. I think we don't want this on AVX512 because we have masked instruction.

Comment (topperc) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:12078]: The `N0.getScalarValueSizeInBits() == N1.getScalarValueSizeInBits()` check shouldn't be true for AVX512 since the mask won't be promoted.

File: llvm/test/CodeGen/X86/vselect.ll [hunk 4]
```diff
@@ -4,6 +4,35 @@
 ; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx | FileCheck %s --check-prefixes=AVX,AVX1
 ; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2 | FileCheck %s --check-prefixes=AVX,AVX2
 
+; should Fold select (sext m), (add X, C), X --> (add X, (and C, (sext m))))
```
Comment (RKSimon) [inline llvm/test/CodeGen/X86/vselect.ll:7]: Include the reference to #66101 for people looking at this in the future:
`; PR66101 - Fold select (sext m), (add X, C), X --> (add X, (and C, (sext m))))`

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by elhewaty** [comment]
Hi @RKSimon, I really want to thank you very much for your help. You were the one that reviewied my first patch. I contributed to InstCombine after that, and I have several upstream patches there. I am comfortable with  InstCombine now. I have a lot of free time these days, I want to contribute with big patches. Please If you have a TODO list I can work with you on it, I will need your guidence.

Thanks

**Comment by RKSimon** [comment]
@elhewaty Thank you, I'm trying to tag more "good first issue" tickets and include some likely steps for each - please keep looking if you're interested.
