### PR TITLE
[ubsan] Display correct runtime messages for negative _BitInt

### LINKED ISSUE #64100: ubsan vs. _BitInt
Consider
```c
_BitInt(15) foo (_BitInt(15) x, _BitInt(15) y) { return x + y; }
_BitInt(115) bar (_BitInt(115) x, _BitInt(115) y) { return x + y; }
_BitInt(385) baz (_BitInt(385) x, _BitInt(385) y) { return x + y; }
int
main ()
{
  volatile _BitInt(15) a = foo (16383wb, 1wb);
  volatile _BitInt(115) b = bar (20769187434139310514121985316880383wb, 1wb);
  volatile _BitInt(385) c = baz (39402006196394479212279040100143613805079739270465446667948293404245721771497210611414266254884915640806627990306815wb, 1wb);
}
```
with -fsanitize=undefined.
At least on godbolt with clang trunk I'm getting
/app/example.c:1:59: runtime error: signed integer overflow: 16383 + 1 cannot be represented in type '_BitInt(15)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.c:1:59 in 
/app/example.c:2:62: runtime error: signed integer overflow: 0x0003ffffffffffffffffffffffffffff + 1 cannot be represented in type '_BitInt(115)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.c:2:62 in 
UndefinedBehaviorSanitizer: CHECK failed: ubsan_value.cpp:86 "((0 && "unexpected bit width")) != (0)" (0x0, 0x0) (tid=1)
The ubsan_value.{h,cpp} representation I guess is fine for very small _BitInt, the ones which fit into ValueHandle, the compiler
can/will sign/zero extend the values to ValueHandle bits.  For slightly larger _BitInt (33 to 64 on 32-bit arches, 65 to 128 on 64-bit arches), I guess the compiler could sign/zero extend it in memory, but anything larger will simply not be handled by the library.
I wonder if we shouldn't add Tk_BitInt = 0x0002 and have TypeInfo in that case be the _BitInt precision rather than ceil log2 of it,
though that field is just 16-bit and I think LLVM currently supports even larger _BitInt.

I guess for now I'll add GCC -fsanitize=undefined support just for what can be encoded in the current scheme, but it would be really nice to have libubsan support even for larger _BitInts.

@AaronBallman

### LINKED ISSUE #88093: UBSan output is incorrect for non power-of-2 sized _BitInt types
Consider this test case:
```
unsigned foo(unsigned _BitInt(44) x) {
    _BitInt(9) c = -2;
    return x >> c;
}

int main() {
  return foo(5) ? 1 : 0;    
}
```
As shown by https://godbolt.org/z/M614qnhco , the result when compiling and running this program (with ubsan) is weird:
```
/app/example.c:3:14: runtime error: shift exponent 510 is too large for 64-bit type 'unsigned _BitInt(44)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.c:3:14 
```
The expected error here would be "shift exponent -2 is negative". But it is not only the detection of isNegative for the exponent that is wrong, it also reports an incorrect bitwidth (64-bit type) for the shifted value.

Afaict the problem is that the TypeDescriptor encoding (compiler-rt/lib/ubsan/ubsan_value.h) encodes the _BitInt types like ordinary integer types:
```
    /// An integer type. Lowest bit is 1 for a signed value, 0 for an unsigned
    /// value. Remaining bits are log_2(bit width). The value representation is
    /// the integer itself if it fits into a ValueHandle, and a pointer to the
    /// integer otherwise.
    TK_Integer = 0x0000,
```
But using log_2(bit width) does not work that well when having non-power-of-two bit widths.

One idea could be to introduce a new TK_BitInt kind, that encodes the bit wifth in some other way? Although I have no idea how big impact that has on the rest of the code.

This problem was found when running tests with the fix from https://github.com/llvm/llvm-project/pull/88004

### PR DESCRIPTION
**Pull request by earnol**
Without this patch compiler-rt ubsan library has a bug displaying incorrect values for variables of the _BitInt (previously called _ExtInt) type. This patch affects affects both: generation of metadata inside code generator and runtime part. The runtime part provided only for i386 and x86_64 runtimes. Other runtimes should be updated to take full benefit of this patch.
The patch is constructed the way to be backward compatible and int and float type runtime diagnostics should be unaffected for not yet updated runtimes.

This patch fixes issue https://github.com/llvm/llvm-project/issues/64100.

### CODE REVIEW

File: clang/lib/CodeGen/CGExpr.cpp [hunk 1]
```diff
@@ -64,6 +65,20 @@ static llvm::cl::opt<bool> ClSanitizeGuardChecks(
...
+enum VariableTypeDescriptorKind : uint16_t {
+  /// An integer type.
+  TK_Integer = 0x0000,
+  /// A floating-point type.
+  TK_Float = 0x0001,
+  /// An _BitInt(N) type.
+  TK_BitInt = 0x0002,
+  /// Any other type. The value representation is unspecified.
+  TK_Unknown = 0xffff
+};
```
Comment (rjmccall) [inline clang/lib/CodeGen/CGExpr.cpp:80]: Is this ABI with the ubsan runtime?  It would be good to make that clear in a comment, at least.

File: compiler-rt/lib/ubsan/ubsan_value.h [hunk 2]
```diff
@@ -103,6 +103,14 @@ class TypeDescriptor {
     /// representation is that of bitcasting the floating-point value to an
     /// integer type.
     TK_Float = 0x0001,
+    /// An _BitInt(N) type. Lowest bit is 1 for a signed value, 0 for an
+    /// unsigned
+    /// value. Remaining bits are log_2(bit_width). The value representation is
```
Comment (ilovepi) [inline compiler-rt/lib/ubsan/ubsan_value.h:108]: nit: can you reformat the comment block to avoid the odd line break?

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c [hunk 3]
```diff
@@ -0,0 +1,188 @@
+// RUN: %clang -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -O0 -fsanitize=alignment,array-bounds,bool,float-cast-overflow,implicit-integer-sign-change,implicit-signed-integer-truncation,implicit-unsigned-integer-truncation,integer-divide-by-zero,nonnull-attribute,null,nullability-arg,nullability-assign,nullability-return,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,unsigned-integer-overflow,unsigned-shift-base,vla-bound %s -o %t1 && %run %t1 2>&1 | FileCheck %s --check-prefix=CHECK-R
+// RUN: %clang -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -fsanitize=array-bounds,enum,float-cast-overflow,integer-divide-by-zero,implicit-unsigned-integer-truncation,implicit-signed-integer-truncation,implicit-integer-sign-change,unsigned-integer-overflow,signed-integer-overflow,shift-base,shift-exponent -O0 -S -emit-llvm -o - %s | FileCheck %s --check-prefix=CHECK-IR
```
Comment (ilovepi) [inline compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:2]: Maybe use `RUNTIME` instead of `CHECK-R` and `IR` instead of `CHECK-IR`? The convention seems to be mixed in this dir, but I think its more typical to avoid the CHECK prefix in other parts of the project. This is a nit/suggestion, and I'm fine if you leave it as is.

```suggestion
// RUN: %clang -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -O0 -fsanitize=alignment,array-bounds,bool,float-cast-overflow,implicit-integer-sign-change,implicit-signed-integer-truncation,implicit-unsigned-integer-truncation,integer-divide-by-zero,nonnull-attribute,null,nullability-arg,nullability-assign,nullability-return,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,unsigned-integer-overflow,unsigned-shift-base,vla-bound %s -o %t1 && %run %t1 2>&1 | FileCheck %s --check-prefix=RUNTIME
// RUN: %clang -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -fsanitize=array-bounds,enum,float-cast-overflow,integer-divide-by-zero,implicit-unsigned-integer-truncation,implicit-signed-integer-truncation,implicit-integer-sign-change,unsigned-integer-overflow,signed-integer-overflow,shift-base,shift-exponent -O0 -S -emit-llvm -o - %s | FileCheck %s --check-prefix=IR
```

File: compiler-rt/lib/ubsan/ubsan_value.h [hunk 4]
```diff
@@ -125,6 +138,26 @@ class TypeDescriptor {
     return 1 << (TypeInfo >> 1);
   }
 
+  const char *getBitIntBitCountPointer() const {
+    CHECK(isBitIntTy());
+    CHECK(isSignedBitIntTy());
+    // Scan Name for zero and return the next address
+    const char *p = getTypeName();
+    while (*p != '\0') {
+      p++;
```
Comment (ilovepi) [inline compiler-rt/lib/ubsan/ubsan_value.h:147]:
```suggestion
      ++p;
```
I always forget about this one: https://llvm.org/docs/CodingStandards.html#prefer-preincrement

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c [hunk 5]
```diff
@@ -0,0 +1,188 @@
...
+  _BitInt(37) a[x - 1];
+  // CHECK-R: {{.*}}bit-int.c:[[@LINE-1]]:17: runtime error: variable length array bound evaluates to non-positive value
+  return 0;
+}
+
+uint32_t nullability_arg(_BitInt(37) *_Nonnull x)
+    __attribute__((no_sanitize("address"))) {
+  _BitInt(37) y = *(_BitInt(37) *)&x;
+  return y;
+}
```
Comment (ilovepi) [inline compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:53]: For some of these functions w/o checks, can you add a comment as to what they're for?

I'm also pretty confused here as to what's going on in this particular function. You're taking the address of the parameter (which seems to be `argc` as pointer), casting it to a `_BitInt*`, dereferencing it to store into a local variable and return that... I don't see what's being exercised here, nor why we'd need such contortions.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 6]
```diff
@@ -3318,6 +3350,20 @@ llvm::Constant *CodeGenFunction::EmitCheckTypeDescriptor(QualType T) {
       DiagnosticsEngine::ak_qualtype, (intptr_t)T.getAsOpaquePtr(), StringRef(),
       StringRef(), std::nullopt, Buffer, std::nullopt);
 
+  if (IsBitInt) {
+    // The Structure is: 0 to end the string, 32 bit insigned integer in target
+    // endianness, zero.
```
Comment (ilovepi) [inline clang/lib/CodeGen/CGExpr.cpp:3355]:
```suggestion
    // The Structure is: 0 to end the string, 32 bit unsigned integer in target
    // endianness, zero.
```
typo?

File: clang/lib/CodeGen/CGExpr.cpp [hunk 7]
```diff
@@ -3292,22 +3307,39 @@ LValue CodeGenFunction::EmitPredefinedLValue(const PredefinedExpr *E) {
 ///   { i16 TypeKind, i16 TypeInfo }
 /// \endcode
 ///
-/// followed by an array of i8 containing the type name. TypeKind is 0 for an
-/// integer, 1 for a floating point value, and -1 for anything else.
+/// followed by an array of i8 containing the type name with extra information
+/// for BitInt. TypeKind is 0 for an integer, 1 for a floating point value, 2
+/// for BitInt and -1 for anything else.
```
Comment (ilovepi) [inline clang/lib/CodeGen/CGExpr.cpp:3312]: Do you need to mention the literal numeric values since they're enum constants now?

**Review by ilovepi — COMMENTED** [review]
Modulo some nits, this seems fine to me. I'll leave approval to one of the code owners, though, as I've had little to do w/ big integer code or UBSAN.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 1 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp:80]: Yes. It is in line with UBSan runtime and it should be in line with it to work. Accepted. Will make it more clear.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 6 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp:3355]: Yes. OMG. I should have noticed. I is close to U on my keyboard.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:53]: Short explanation:
Ubsan should not be triggered by assignment even if data is invalid.
Longer explanation: 
This code is clearly invalid, yet i expect no diagnostics here as ubsan sanitizer should not be be triggered on a simple assignment according to the current implementation.
As you can see, when asan is enabled this function throw a diagnostics (as it should). this is the reason why it is disabled.
I hope this explanation is clear.

As for comments addition: accepted.

File: compiler-rt/lib/ubsan/ubsan_value.h (hunk 4 above)
Comment (earnol) [reply compiler-rt/lib/ubsan/ubsan_value.h:147]: Agree.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 3 above)
Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:2]: I have no specific preference, so will follow with your suggestion.

File: compiler-rt/lib/ubsan/ubsan_value.h (hunk 2 above)
Comment (earnol) [reply compiler-rt/lib/ubsan/ubsan_value.h:108]: Accepted.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 7 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp:3312]: I think it is important that those values are 16 bit integers. I'll replace with TK_BitInt(2).

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (ilovepi) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:54]: hmm, does no `CHECK:` line imply that there isn't a diagnostic? I think it will just silently pass... maybe if these are in a different file where there are no diagnostics expected it would work as intended?

I always struggle with checks for output that shouldn't happen, especially since `CHECK-NOT` often keeps passing when it isn't intended to. I know that in `lld` we can use `--fatal-warnings` for tests that should not produce a diagnostic. I'm not sure how that's normally done for the sanitizers though. Maybe just a second test file that checks that there are no `runtime error:` lines? That could be brittle though if the diagnostic gets spelled differently, or if there's a typo in the check. Maybe its easy if UBSAN errors change the return code, though?

Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:54]: > hmm, does no `CHECK:` line imply that there isn't a diagnostic? I think it will just silently pass... maybe if these are in a different file where there are no diagnostics expected it would work as intended?

Yes. It will silently pass, yet unexpected diagnostics in the middle of the check script can throw the FileCheck off and it will barf. My idea is having at least some check (which can provide false negative error detection: detects not error when there is an error) is better compared to no check at all completely.

CHECK-NOT will not work here as it will require the line which should not be encountered and line is not known in this case.
CHECK-EMPTY also does not look like a right choice. 

> That could be brittle though if the diagnostic gets spelled differently, or if there's a typo in the check. Maybe its easy if UBSAN errors change the return code, though?

You have given me a great idea. These examples can be moved to different test file which will be compiled with -fsanitize-trap option. It this case it would be easy to detect the ubsan activation did not happened. On the other hand it will require extra file and i wanted to pack all ubsan _BitInt tests into single file. But probably it is not that bad, if it is the price for check precision.
Alternatively FileCheck can be used with with "--implicit-check-not error" option to verify the fact runtime error was not thrown.
What approach do you think will be the best?

File: clang/lib/CodeGen/CGExpr.cpp (hunk 7 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp]: It was replaced and i hope it will make comment clear.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (ilovepi) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: Sorry, I missed that there was a question at the end. I guess using `-fsanitize-trap` seems fine. I'm hardly an expert on compiler-rt conventions though, so take that w/ a grain of salt.  The other reviewers probably have a more cogent idea about what's appropriate, but I think having the second test where they're expected to pass makes a lot more sense than trying to exclude them here.

Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: I have updated commit using CHECK-NOT with "runtime error". It looks like a reasonable check for me.

Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: Oh... Just seen your response. Do you want me to change it into "-fsanitize-trap" or the current implementation is fine?
For me whatever diagnostics is displayed is having "runtime error" so while line is not known in advance we are pretty sure about part of the line and it can be entered into CHECK-NOT.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int-pass.c [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+  _BitInt(37) y = *(_BitInt(37) *)&x;
+  // CHECK-NOT: runtime error:
+  return y;
+}
+
+// In this test there is an expectation of ubsan not triggeting on returning random address which is inside address space of the process.
+_BitInt(37) nonnull_attribute(__attribute__((nonnull)) _BitInt(37) * x)
+    __attribute__((no_sanitize("address"))) {
+  return *(_BitInt(37) *)&x;
+  // CHECK-NOT: runtime error:
```
Comment (ilovepi) [inline compiler-rt/test/ubsan/TestCases/Integer/bit-int-pass.c:20]: You probably only need the one `CHECK-NOT:` line if none of them are expected to match. I'd take a look at other tests that are expected to work and follow that convention.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (ilovepi) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: Seems reasonable, but maybe check the other UBSAN tests, and follow their conventions for tests that should run w/o an error.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int-pass.c (hunk 8 above)
Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int-pass.c:20]: Yes. I tested it. One check NOT is enough.

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (earnol) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: This is basically what i've done when i looked into ./compiler-rt/test/ubsan/TestCases/Misc/deduplication.cpp it has multiple CHECK-NOTs. But on the second though it looks like also unnecessary.

**Comment by earnol** [comment]
Ping!
Any additional suggestions for the improvements?

File: clang/lib/CodeGen/CGExpr.cpp [hunk 9]
```diff
@@ -3318,6 +3353,20 @@ llvm::Constant *CodeGenFunction::EmitCheckTypeDescriptor(QualType T) {
       DiagnosticsEngine::ak_qualtype, (intptr_t)T.getAsOpaquePtr(), StringRef(),
       StringRef(), std::nullopt, Buffer, std::nullopt);
 
+  if (IsBitInt) {
+    // The Structure is: 0 to end the string, 32 bit unsigned integer in target
+    // endianness, zero.
+    char s[6] = {'\0', '\0', '\0', '\0', '\0', '\0'};
```
Comment (AaronBallman) [inline clang/lib/CodeGen/CGExpr.cpp:3359]:
```suggestion
    char S[6] = {'\0', '\0', '\0', '\0', '\0', '\0'};
```
For usual naming conventions.

File: clang/lib/CodeGen/CGExpr.cpp [hunk 10]
```diff
@@ -3318,6 +3353,20 @@ llvm::Constant *CodeGenFunction::EmitCheckTypeDescriptor(QualType T) {
...
+    const auto *EIT = T->getAs<BitIntType>();
```
Comment (AaronBallman) [inline clang/lib/CodeGen/CGExpr.cpp:3360]:
```suggestion
    const auto *EIT = T->castAs<BitIntType>();
```
We don't expect it to ever return a null pointer, so we might as well cast instead.

**Review by AaronBallman — COMMENTED** [review]
The changes seem pretty reasonable to me (aside from a few small nits), but I'd appreciate someone with more compiler-rt knowledge to also sign off on the changes.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 9 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp:3359]: Good point. Agreed.

File: clang/lib/CodeGen/CGExpr.cpp (hunk 10 above)
Comment (earnol) [reply clang/lib/CodeGen/CGExpr.cpp:3360]: Agreed. We already know the type is some sort of BitIntType.

**Review by AaronBallman — APPROVED** [review]
LGTM

**Comment by fmayer** [comment]
Breakage looks related: https://lab.llvm.org/buildbot/#/builders/72/builds/265

```
FAIL: UBSan-MemorySanitizer-powerpc64le :: TestCases/Integer/bit-int.c (4716 of 4745)
******************** TEST 'UBSan-MemorySanitizer-powerpc64le :: TestCases/Integer/bit-int.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 1: /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/./bin/clang  -fsanitize=memory  -m64 -fno-function-sections  -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -O0 -fsanitize=alignment,array-bounds,bool,float-cast-overflow,implicit-integer-sign-change,implicit-signed-integer-truncation,implicit-unsigned-integer-truncation,integer-divide-by-zero,nonnull-attribute,null,nullability-arg,nullability-assign,nullability-return,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,unsigned-integer-overflow,unsigned-shift-base,vla-bound /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c -o /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_g
 cc/runtimes/runtimes-bins/compiler-rt/test/ubsan/MemorySanitizer-powerpc64le/TestCases/Integer/Output/bit-int.c.tmp1 &&  /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/ubsan/MemorySanitizer-powerpc64le/TestCases/Integer/Output/bit-int.c.tmp1 2>&1 | FileCheck /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c --check-prefix=RUNTIME
+ /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/./bin/clang -fsanitize=memory -m64 -fno-function-sections -Wno-constant-conversion -Wno-array-bounds -Wno-division-by-zero -Wno-shift-negative-value -Wno-shift-count-negative -Wno-int-to-pointer-cast -O0 -fsanitize=alignment,array-bounds,bool,float-cast-overflow,implicit-integer-sign-change,implicit-signed-integer-truncation,implicit-unsigned-integer-truncation,integer-divide-by-zero,nonnull-attribute,null,nullability-arg,nullability-assign,nullability-return,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,unsigned-integer-overflow,unsigned-shift-base,vla-bound /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c -o /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/runtimes/runti
 mes-bins/compiler-rt/test/ubsan/MemorySanitizer-powerpc64le/TestCases/Integer/Output/bit-int.c.tmp1
+ /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/ubsan/MemorySanitizer-powerpc64le/TestCases/Integer/Output/bit-int.c.tmp1
+ FileCheck /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c --check-prefix=RUNTIME
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:93:14: error: RUNTIME: expected string not found in input
 // RUNTIME: {{.*}}bit-int.c:[[@LINE-1]]:24: runtime error: left shift of negative value -1
             ^
<stdin>:25:206: note: scanning from here
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:86:21: runtime error: shift exponent -1 is negative
                                                                                                                                                                                                             ^
<stdin>:25:206: note: with "@LINE-1" equal to "92"
/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:86:21: runtime error: shift exponent -1 is negative
                                                                                                                                                                                                             ^
<stdin>:33:252: note: possible intended match here
SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/ubsan/MemorySanitizer-powerpc64le/TestCases/Integer/Output/bit-int.c.tmp1+0xe6d64) in shift_exponent
                                                                                                                                                                                                                                                           ^

Input file: <stdin>
Check file: /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
           20: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:65:18 
           21: /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:72:19: runtime error: implicit conversion from type 'unsigned _BitInt(37)' of value 137438953471 (64-bit, unsigned) to type '_BitInt(37)' changed the value to -1 (64-bit, signed)
           22: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:72:19 
           23: /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:79:10: runtime error: implicit conversion from type '_BitInt(73)' of value 0x00000000000000008000000000000000 (128-bit, signed) to type '_BitInt(13)' changed the value to 0 (16-bit, signed)
           24: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:79:10 
           25: /home/buildbots/llvm-external-buildbots/workers/ppc64le-sanitizer/sanitizer-ppc64le/build/llvm-project/compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:86:21: runtime error: shift exponent -1 is negative
Step 9 (test compiler-rt gcc) failure: test compiler-rt gcc (failure)

```

**Comment by earnol** [comment]
Yes. It is indeed the cause. Already created a code to address the the issue.

**Comment by mstorsjo** [comment]
In addition to the issue noted on buildbots, this also caused failed tests on i386:
https://github.com/mstorsjo/llvm-mingw/actions/runs/9606458336/job/26504129718#step:8:1501

There seem to be a couple of different errors there:
```
bit-int.c:72:19: runtime error: implicit conversion from type 'unsigned _BitInt(37)' of value [21707795506135039](tel:21707795506135039) (64-bit, unsigned) to type '_BitInt(37)' changed the value to -1 (64-bit, signed)

AddressSanitizer: CHECK failed: ubsan_value.cpp:87 "((0 && "libclang_rt.ubsan was built without __int128 support")) != (0)" (0x0, 0x0) (tid=2296)

```

**Comment by mstorsjo** [comment]
> @mstorsjo It seems your compiler build does not have int128_t enabled.

Indeed, Clang doesn't provide int128_t for 32 bit targets, AFAIK.

> Could you please test #96240 in your environment to verify it has no such problem?

That PR does seem to work fine, in such an environment, in a quick adhoc test setup - thanks!

**Comment by earnol** [comment]
> Indeed, Clang doesn't provide int128_t for 32 bit targets, AFAIK.

It looks like a little bit more complex.
I checked with Standalone-i386 and AddressSanitizer-i386 targets. They do have int128_t for 32 bit targets as soon as clang itself built as 64-bit binary.

> > Could you please test #96240 in your environment to verify it has no such problem?
> That PR does seem to work fine, in such an environment, in a quick adhoc test setup - thanks!
Excellent. Waiting for sign-off in this case.

**Comment by mstorsjo** [comment]
> > Indeed, Clang doesn't provide int128_t for 32 bit targets, AFAIK.
> 
> It looks like a little bit more complex. I checked with Standalone-i386 and AddressSanitizer-i386 targets. They do have int128_t for 32 bit targets as soon as clang itself built as 64-bit binary.

That doesn't quite reflect my experience - the bitness of the host compiler binary should not affect what features are available in the target environment:
```
$ file -L bin/clang
bin/clang: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[xxHash]=724b58c4c8ae1673, not stripped
$ bin/clang -target i386-linux-gnu -E -dM - < /dev/null | grep INT128
$ bin/clang -target x86_64-linux-gnu -E -dM - < /dev/null | grep INT128
#define __SIZEOF_INT128__ 16
$ bin/clang -target i386-windows -E -dM - < /dev/null | grep INT128
$ bin/clang -target x86_64-windows -E -dM - < /dev/null | grep INT128
#define __SIZEOF_INT128__ 16
$ cat int128.c 
__int128_t a = 42;
$ bin/clang -target x86_64-linux-gnu -c int128.c
$ bin/clang -target i386-linux-gnu -c int128.c
int128.c:1:1: error: unknown type name '__int128_t'
    1 | __int128_t a = 42;
      | ^
1 error generated.
```
I'm not quite sure what kind of test setup you have - it sounds like it has detected feature based on the compiler's default target, regardless of what the target really supports?
