### PR TITLE
[RegisterCoalescer] Clear instructions not recorded in `ErasedInstrs` but erased

### LINKED ISSUE #71178: Clang crash: Assertion `isReg() && "This is not a register operand!"' failed.
Clang at -O1 crashes on the test case.

Bisected to 2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0, which was committed by @djtodoro 

Compiler explorer: https://godbolt.org/z/74MTEPh36

```console
% cat a.c
long a, b, e, g;
int c;
short d;
int *f;
int h() {
  long i;
j:
  if (e) {
    int k;
    g = b && -1 / a;
    k = *f;
    if (k) {
      i |= 0 <= 0;
      if (c)
        goto j;
    } else {
      d = 0;
      return 0;
    }
  } else {
    int l;
    for (; d;) {
      e = 9166129423;
      goto j;
    }
    return *f;
  }
  return 0;
}
int main() {}
%
% clang -O1 a.c
clang-14: /tmp/tmp3wrk7acr/tmpxyxr54it/llvm/include/llvm/CodeGen/MachineOperand.h:361: llvm::Register llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/clang-14 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name reduced.c -mrelocation-model static -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/zdata/shaoli/realsmith/watchdir/reduced/case_7TTZKO7D -resource-dir /zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/lib/clang/14.0.0 -internal-isystem /zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -fdebug-compilation-dir=/zdata/shaoli/realsmith/watchdir/reduced/case_7TTZKO7D -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/reduced-b68b25.o -x c a.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'a.c'.
4.      Running pass 'Simple Register Coalescing' on function '@h'
 #0 0x00007fd79170c704 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00007fd791709e2e SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fd790ae8090 (/lib/x86_64-linux-gnu/libc.so.6+0x43090)
 #3 0x00007fd790ae800b raise /build/glibc-BHL3KM/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #4 0x00007fd790ac7859 abort /build/glibc-BHL3KM/glibc-2.31/stdlib/abort.c:81:7
 #5 0x00007fd790ac7729 get_sysdep_segment_value /build/glibc-BHL3KM/glibc-2.31/intl/loadmsgcat.c:509:8
 #6 0x00007fd790ac7729 _nl_load_domain /build/glibc-BHL3KM/glibc-2.31/intl/loadmsgcat.c:970:34
 #7 0x00007fd790ad8fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00007fd791d8fadd isMoveInstr(llvm::TargetRegisterInfo const&, llvm::MachineInstr const*, llvm::Register&, llvm::Register&, unsigned int&, unsigned int&) (.constprop.0) RegisterCoalescer.cpp:0:0
 #9 0x00007fd791d95ada llvm::CoalescerPair::setRegisters(llvm::MachineInstr const*) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libLLVM-14git.so+0xec2ada)
#10 0x00007fd791da10ac (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&) (.constprop.0) RegisterCoalescer.cpp:0:0
#11 0x00007fd791da38cf (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) RegisterCoalescer.cpp:0:0
#12 0x00007fd791da70d5 (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) RegisterCoalescer.cpp:0:0
#13 0x00007fd791bb2a38 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libLLVM-14git.so+0xcdfa38)
#14 0x00007fd7918a12c5 llvm::FPPassManager::runOnFunction(llvm::Function&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libLLVM-14git.so+0x9ce2c5)
#15 0x00007fd7918a1509 llvm::FPPassManager::runOnModule(llvm::Module&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libLLVM-14git.so+0x9ce509)
#16 0x00007fd7918a25f2 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libLLVM-14git.so+0x9cf5f2)
#17 0x00007fd7970948a3 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x1bef8a3)
#18 0x00007fd797472353 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x1fcd353)
#19 0x00007fd795e300d9 clang::ParseAST(clang::Sema&, bool, bool) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x98b0d9)
#20 0x00007fd797470ce8 clang::CodeGenAction::ExecuteAction() (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x1fcbce8)
#21 0x00007fd797ef89a9 clang::FrontendAction::Execute() (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x2a539a9)
#22 0x00007fd797e8238e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x29dd38e)
#23 0x00007fd797f8c223 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/../lib/libclang-cpp.so.14git+0x2ae7223)
#24 0x000055efe3794127 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/clang-14+0x15127)
#25 0x000055efe3790778 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#26 0x000055efe378d361 main (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/clang-14+0xe361)
#27 0x00007fd790ac9083 __libc_start_main /build/glibc-BHL3KM/glibc-2.31/csu/../csu/libc-start.c:342:3
#28 0x000055efe37902ee _start (/zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin/clang-14+0x112ee)
clang-14: error: unable to execute command: Aborted
clang-14: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers/clang-2cdc6f2ca62e83fec445114fbbe6276e9ab2a7d0/bin
clang-14: note: diagnostic msg:
********************
%
```

### LINKED ISSUE #79718: [LoongArch]  Assertion `isReg() && "This is not a register operand!"'
I tried this code with `llc --mtriple=loongarch64`

```llvm
define void @foo(ptr nocapture writeonly %0, i1 %1, i1 %2, i1 %3, i1 %4) {
start:
  br label %bb1

bb1:                                              ; preds = %bb6, %start
  %5 = phi i64 [ 0, %start ], [ %20, %bb6 ]
  %6 = phi i64 [ 0, %start ], [ %21, %bb6 ]
  %7 = phi i64 [ undef, %start ], [ %23, %bb6 ]
  %8 = icmp eq i64 %5, 1
  br label %bb2

bb2:                                              ; preds = %bb6, %bb1
  %9 = phi i64 [ %5, %bb1 ], [ %20, %bb6 ]
  %10 = phi i64 [ %6, %bb1 ], [ %21, %bb6 ]
  %11 = phi i64 [ %6, %bb1 ], [ %22, %bb6 ]
  %12 = phi i64 [ %7, %bb1 ], [ %23, %bb6 ]
  br i1 %1, label %loopexit, label %preheader

preheader:                                        ; preds = %bb2, %bb4
  %13 = phi i64 [ %15, %bb4 ], [ %11, %bb2 ]
  %14 = load volatile { i64, i64 }, ptr null, align 4294967296
  br i1 %2, label %bb3, label %bb5

bb3:                                              ; preds = %preheader
  %15 = add i64 %13, 1
  br i1 %3, label %bb4, label %bb5

bb4:                                              ; preds = %bb3
  br i1 %4, label %loopexit, label %preheader

loopexit:                                         ; preds = %bb4, %bb2
  %16 = phi i64 [ %10, %bb2 ], [ %15, %bb4 ]
  %17 = phi i64 [ %11, %bb2 ], [ %15, %bb4 ]
  store i8 0, ptr %0, align 1
  br label %bb6

bb5:                                              ; preds = %bb3, %preheader
  %18 = phi i64 [ 1, %bb3 ], [ 0, %preheader ]
  %19 = phi i64 [ %15, %bb3 ], [ %12, %preheader ]
  store i64 0, ptr %0, align 8
  br label %bb6

bb6:                                              ; preds = %bb5, %loopexit
  %20 = phi i64 [ %19, %bb5 ], [ %9, %loopexit ]
  %21 = phi i64 [ %18, %bb5 ], [ %16, %loopexit ]
  %22 = phi i64 [ %18, %bb5 ], [ %17, %loopexit ]
  %23 = phi i64 [ %19, %bb5 ], [ %12, %loopexit ]
  br i1 %8, label %bb2, label %bb1
}
```

I got a segmentation fault.
If assertion is turned on, I can get `isReg() && "This is not a register operand!"' failed`.

GodBolt: https://llvm.godbolt.org/z/zT5rKrW6x
From: https://github.com/rust-lang/rust/pull/120268

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #79718. Fixes #71178.

The same instructions may exist in an iteration. We cannot immediately delete instructions in `ErasedInstrs`.

Here's my debug logs, you can see that the instructions that are about to be processed have appeared in the work list ahead of time.

```
BB: foo:preheader work list:
BB: foo:bb3 work list:
BB: foo:bb4 work list:
%52:gpr = COPY %7:gpr in foo:bb4

BB: foo:bb2 work list:
%52:gpr = COPY %7:gpr in foo:bb4

BB: foo:bb6 work list:
%52:gpr = COPY %7:gpr in foo:bb4

BB: foo:loopexit work list:
%48:gpr = COPY %44:gpr in foo:bb4

BB: foo:bb5 work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge // Instruction changes!

BB: foo:BB3 work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge

BB: foo:preheader.preheader work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge

BB: foo:BB6 work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge
%43:gpr = COPY %45:gpr in foo:BB6

BB: foo:bb3.bb5_crit_edge work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge // Same instruction!
%43:gpr = COPY %45:gpr in foo:BB6
%44:gpr = COPY %41:gpr in foo:bb3.bb5_crit_edge
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge // Same instruction!

BB: foo:bb1 work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge
%43:gpr = COPY %45:gpr in foo:BB6
%44:gpr = COPY %41:gpr in foo:bb3.bb5_crit_edge
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge
%0:gpr = COPY %43:gpr in foo:bb1

BB: foo:start work list:
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge
%43:gpr = COPY %45:gpr in foo:BB6
%44:gpr = COPY %41:gpr in foo:bb3.bb5_crit_edge
%45:gpr = COPY %43:gpr in foo:bb3.bb5_crit_edge
%0:gpr = COPY %43:gpr in foo:bb1

llc: llvm-project/llvm/include/llvm/CodeGen/MachineOperand.h:370: Register llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
```

This change is probably due to `removePartialRedundancy`.

<details><summary>Address sanitizer logs</summary>
<p>

```
=================================================================
==200228==ERROR: AddressSanitizer: use-after-poison on address 0x521000054728 at pc 0x7efc7fd597ad bp 0x7ffd3d4d1d10 sp 0x7ffd3d4d1d08
READ of size 8 at 0x521000054728 thread T0
    #0 0x7efc7fd597ac in llvm::MachineInstr::getOpcode() const /home/dianqk/llvm/llvm-project/llvm/include/llvm/CodeGen/MachineInstr.h:543:39
    #1 0x7efc7fd597ac in llvm::MachineInstr::isCopy() const /home/dianqk/llvm/llvm-project/llvm/include/llvm/CodeGen/MachineInstr.h:1392:12
    #2 0x7efc7fd597ac in isMoveInstr(llvm::TargetRegisterInfo const&, llvm::MachineInstr const*, llvm::Register&, llvm::Register&, unsigned int&, unsigned int&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:419:13
    #3 0x7efc7fd57b06 in llvm::CoalescerPair::setRegisters(llvm::MachineInstr const*) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:459:8
    #4 0x7efc7fd7039c in (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:1972:11
    #5 0x7efc7fd6dbaa in (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:3995:20
    #6 0x7efc7fd5fcde in (anonymous namespace)::RegisterCoalescer::joinAllIntervals() /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:4156:10
    #7 0x7efc7fd5fcde in (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/RegisterCoalescer.cpp:4228:5
    #8 0x7efc7f70f043 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:93:13
    #9 0x7efc79d0db54 in llvm::FPPassManager::runOnFunction(llvm::Function&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1445:27
    #10 0x7efc79d260e3 in llvm::FPPassManager::runOnModule(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1491:16
    #11 0x7efc79d0ea3f in (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1560:27
    #12 0x7efc79d0ea3f in llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:542:44
    #13 0x55b3617ef9f4 in compileModule(char**, llvm::LLVMContext&) /home/dianqk/llvm/llvm-project/llvm/tools/llc/llc.cpp:743:8
    #14 0x55b3617e8c9f in main /home/dianqk/llvm/llvm-project/llvm/tools/llc/llc.cpp:412:22
    #15 0x7efc7823f0cd in __libc_start_call_main (/nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6+0x280cd) (BuildId: 155a1ecbcb77ab0451b398b8a9c19795d8e7b047)
    #16 0x7efc7823f188 in __libc_start_main@GLIBC_2.2.5 (/nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6+0x28188) (BuildId: 155a1ecbcb77ab0451b398b8a9c19795d8e7b047)
    #17 0x55b3616af774 in _start (/home/dianqk/llvm/llvm-project/build/bin/llc+0x97774)

0x521000054728 is located 2600 bytes inside of 4096-byte region [0x521000053d00,0x521000054d00)
allocated by thread T0 here:
    #0 0x55b3617e2050 in operator new(unsigned long, std::align_val_t) (/home/dianqk/llvm/llvm-project/build/bin/llc+0x1ca050)
    #1 0x7efc78c4142d in llvm::allocate_buffer(unsigned long, unsigned long) /home/dianqk/llvm/llvm-project/llvm/lib/Support/MemAlloc.cpp:16:10
    #2 0x7efc7f03e5c1 in llvm::MallocAllocator::Allocate(unsigned long, unsigned long) /home/dianqk/llvm/llvm-project/llvm/include/llvm/Support/AllocatorBase.h:92:12
    #3 0x7efc7f03e5c1 in llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>::StartNewSlab() /home/dianqk/llvm/llvm-project/llvm/include/llvm/Support/Allocator.h:339:42
    #4 0x7efc7f03e5c1 in llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>::Allocate(unsigned long, llvm::Align) /home/dianqk/llvm/llvm-project/llvm/include/llvm/Support/Allocator.h:195:5
    #5 0x7efc7f6e22bb in llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>::Allocate(unsigned long, unsigned long) /home/dianqk/llvm/llvm-project/llvm/include/llvm/Support/Allocator.h:209:12
    #6 0x7efc7f6e22bb in llvm::MachineInstr* llvm::Recycler<llvm::MachineInstr, 72ul, 8ul>::Allocate<llvm::MachineInstr, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>>(llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>&) /home/dianqk/llvm/llvm-project/llvm/include/llvm/Support/Recycler.h:89:57
    #7 0x7efc7f6e22bb in llvm::MachineFunction::CreateMachineInstr(llvm::MCInstrDesc const&, llvm::DebugLoc, bool) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/MachineFunction.cpp:399:35
    #8 0x7efc838dcb8a in llvm::BuildMI(llvm::MachineBasicBlock&, llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>, llvm::MIMetadata const&, llvm::MCInstrDesc const&, llvm::Register) /home/dianqk/llvm/llvm-project/llvm/include/llvm/CodeGen/MachineInstrBuilder.h:386:25
    #9 0x7efc838fbe8e in llvm::TargetInstrInfo::createPHISourceCopy(llvm::MachineBasicBlock&, llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>, llvm::DebugLoc const&, llvm::Register, unsigned int, llvm::Register) const /home/dianqk/llvm/llvm-project/llvm/include/llvm/CodeGen/TargetInstrInfo.h:2048:12
    #10 0x7efc7fbc09c6 in (anonymous namespace)::PHIElimination::LowerPHINode(llvm::MachineBasicBlock&, llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/PHIElimination.cpp:522:28
    #11 0x7efc7fbb6dfe in (anonymous namespace)::PHIElimination::EliminatePHINodes(llvm::MachineFunction&, llvm::MachineBasicBlock&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/PHIElimination.cpp:243:5
    #12 0x7efc7fbb6dfe in (anonymous namespace)::PHIElimination::runOnMachineFunction(llvm::MachineFunction&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/PHIElimination.cpp:198:16
    #13 0x7efc7f70f043 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/dianqk/llvm/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:93:13
    #14 0x7efc79d0db54 in llvm::FPPassManager::runOnFunction(llvm::Function&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1445:27
    #15 0x7efc79d260e3 in llvm::FPPassManager::runOnModule(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1491:16
    #16 0x7efc79d0ea3f in (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1560:27
    #17 0x7efc79d0ea3f in llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/dianqk/llvm/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:542:44
    #18 0x55b3617ef9f4 in compileModule(char**, llvm::LLVMContext&) /home/dianqk/llvm/llvm-project/llvm/tools/llc/llc.cpp:743:8
    #19 0x55b3617e8c9f in main /home/dianqk/llvm/llvm-project/llvm/tools/llc/llc.cpp:412:22
    #20 0x7efc7823f0cd in __libc_start_call_main (/nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6+0x280cd) (BuildId: 155a1ecbcb77ab0451b398b8a9c19795d8e7b047)

SUMMARY: AddressSanitizer: use-after-poison /home/dianqk/llvm/llvm-project/llvm/include/llvm/CodeGen/MachineInstr.h:543:39 in llvm::MachineInstr::getOpcode() const
Shadow bytes around the buggy address:
  0x521000054480: 00 00 00 00 00 00 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x521000054500: f7 00 00 00 00 00 00 00 00 f7 f7 f7 f7 f7 f7 f7
  0x521000054580: f7 f7 f7 f7 00 00 00 00 00 00 00 00 f7 f7 f7 f7
  0x521000054600: f7 f7 f7 f7 f7 f7 f7 00 00 00 00 00 00 00 00 f7
  0x521000054680: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 00 00 00 00 00 00
=>0x521000054700: 00 00 f7 f7 f7[f7]f7 f7 f7 f7 f7 f7 f7 00 00 00
  0x521000054780: 00 00 00 00 00 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
  0x521000054800: 00 00 00 00 00 00 00 00 f7 f7 f7 f7 f7 f7 f7 f7
  0x521000054880: f7 f7 f7 00 00 00 00 00 00 00 00 f7 00 00 00 00
  0x521000054900: 00 00 00 00 00 f7 00 00 00 00 00 00 00 00 f7 00
  0x521000054980: 00 00 00 00 00 00 00 00 f7 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==200228==ABORTING
```

</p>
</details>

### CODE REVIEW

File: llvm/lib/CodeGen/RegisterCoalescer.cpp [hunk 1]
```diff
@@ -2156,7 +2159,9 @@ bool RegisterCoalescer::joinCopy(MachineInstr *CopyMI, bool &Again) {
   // CopyMI has been erased by joinIntervals at this point. Remove it from
   // ErasedInstrs since copyCoalesceWorkList() won't add a successful join back
   // to the work list. This keeps ErasedInstrs from growing needlessly.
-  ErasedInstrs.erase(CopyMI);
+  if (ErasedInstrs.erase(CopyMI))
+    // But we may encounter the instruction again in this iteration.
+    CurrentErasedInstrs.insert(CopyMI);
```
Comment (qcolombet) [inline llvm/lib/CodeGen/RegisterCoalescer.cpp:2164]: How do we end up with the same copy instruction twice in the worklist?

**Comment by arsenm** [comment]
#73519 is potentially another attempt at solving the same issue

File: llvm/lib/CodeGen/RegisterCoalescer.cpp (hunk 1 above)
Comment (DianQK) [reply llvm/lib/CodeGen/RegisterCoalescer.cpp:2164]: From the debugging results, it looks like `removePartialRedundancy` changes the contents of the work list.

**Comment by DianQK** [comment]
> #73519 is potentially another attempt at solving the same issue

It does seem to be the same issue. I'm not sure which is the better way to handle this. Do you have any more suggestions?

(This PR seems to be missing multiple duplicates?)

**Comment by DianQK** [comment]
Ping~

Though I know very little about this part. But I think this at least fixes the crash, with no other regressions.

**Comment by DianQK** [comment]
@qcolombet @arsenm
Could you continue to review it? Or submit a new fix? Thanks.

**Review by arsenm — COMMENTED** [review]
I think this is an easier to understand version of the fix. The test can be cleaned up a bit though.

Can you drop the IR section, delete the registers section, use -run-pass=none -simplify-mir to clean up most of the unnecessary bits? 

Also can you add the test from #71178 and #73519

File: llvm/test/CodeGen/LoongArch/register-coalescer-crash-pr79718.mir [hunk 2]
```diff
@@ -0,0 +1,213 @@
...
+  ; CHECK-NEXT: bb.12:
+  ; CHECK-NEXT:   successors: %bb.2(0x7c000000), %bb.1(0x04000000)
+  ; CHECK-NEXT: {{  $}}
+  ; CHECK-NEXT:   BEQ [[COPY7]], [[ORI]], %bb.2
+  ; CHECK-NEXT:   PseudoBR %bb.1
+  bb.0:
+    liveins: $r4, $r5, $r6, $r7, $r8
+
+    %22:gpr = COPY killed $r8
+    %21:gpr = COPY killed $r7
```
Comment (arsenm) [inline llvm/test/CodeGen/LoongArch/register-coalescer-crash-pr79718.mir:98]: run-pass=none will still compact these numbers (which makes it easier to read 1:1 correspondence to the debug output)

**Comment by DianQK** [comment]
> Also can you add the test from #71178 and #73519

Hmm, this PR doesn't fix it. This test case isn't stable, and I can't test it with RegisterCoalescer.

**Comment by DianQK** [comment]
> > Also can you add the test from #71178 and #73519
> 
> Hmm, this PR doesn't fix it. This test case isn't stable, and I can't test it with RegisterCoalescer.

I think it's a similar but different issue.

**Comment by arsenm** [comment]
> > > Also can you add the test from #71178 and #73519
> > 
> > 
> > Hmm, this PR doesn't fix it. This test case isn't stable, and I can't test it with RegisterCoalescer.
> 
> I think it's a similar but different issue.

I think it's the same; it's from relying on the delete inst pointers from removePartialRedundancy

File: llvm/test/CodeGen/X86/PR71178-register-coalescer-crash.ll [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+; CHECK-NEXT:    movl %esi, %eax
+; CHECK-NEXT:    jne .LBB0_6
+; CHECK-NEXT:  .LBB0_10:
+; CHECK-NEXT:    retq
+; CHECK-NEXT:  .LBB0_6: # %.loopexit1
+; CHECK-NEXT:    movl %r8d, %eax
+; CHECK-NEXT:    retq
+  br label %3
+
+3:                                                ; preds = %16, %2
```
Comment (arsenm) [inline llvm/test/CodeGen/X86/PR71178-register-coalescer-crash.ll:46]: Run instnamer on this

File: llvm/lib/CodeGen/RegisterCoalescer.cpp [hunk 4]
```diff
@@ -3982,21 +3987,31 @@ void RegisterCoalescer::lateLiveIntervalUpdate() {
...
     Progress |= Success;
     if (Success || !Again)
       MI = nullptr;
   }
+  // Clear instructions not recorded in `ErasedInstrs` but erased.
+  if (!CurrentErasedInstrs.empty()) {
+    for (MachineInstr *&MI : CurrList)
+      if (MI && CurrentErasedInstrs.count(MI))
+        MI = nullptr;
+    for (MachineInstr *&MI : WorkList)
```
Comment (arsenm) [inline llvm/lib/CodeGen/RegisterCoalescer.cpp:4011]: Braces

File: llvm/lib/CodeGen/RegisterCoalescer.cpp [hunk 5]
```diff
@@ -3982,21 +3987,31 @@ void RegisterCoalescer::lateLiveIntervalUpdate() {
...
       continue;
     }
     bool Again = false;
-    bool Success = joinCopy(MI, Again);
+    bool Success = joinCopy(MI, Again, CurrentErasedInstrs);
     Progress |= Success;
     if (Success || !Again)
       MI = nullptr;
   }
+  // Clear instructions not recorded in `ErasedInstrs` but erased.
```
Comment (arsenm) [inline llvm/lib/CodeGen/RegisterCoalescer.cpp:4006]: This whole thing feels overcomplicated but I don't have any better suggestion

**Comment by DianQK** [comment]
> > > > Also can you add the test from #71178 and #73519
> > > 
> > > 
> > > Hmm, this PR doesn't fix it. This test case isn't stable, and I can't test it with RegisterCoalescer.
> > 
> > 
> > I think it's a similar but different issue.
> 
> I think it's the same; it's from relying on the delete inst pointers from removePartialRedundancy

I found out why. It's a very specific case.
We erased an instruction in `coalesceLocals` and then created a new instruction because it was the same address, and we successfully deleted the record at `ErasedInstrs`. After that, we erased the new instruction again.
Finally, we will lose this record in `while (copyCoalesceWorkList(WorkList))` since `CurrentErasedInstrs` only records one iteration.

File: llvm/lib/CodeGen/RegisterCoalescer.cpp (hunk 4 above)
Comment (DianQK) [reply llvm/lib/CodeGen/RegisterCoalescer.cpp:4011]: If I understand correctly, we don't normally add braces to a single line statement?

Comment (arsenm) [reply llvm/lib/CodeGen/RegisterCoalescer.cpp:4011]: This covers multiple lines

File: llvm/lib/CodeGen/RegisterCoalescer.cpp (hunk 5 above)
Comment (DianQK) [reply llvm/lib/CodeGen/RegisterCoalescer.cpp:4006]: I think all because we are dancing with dangling pointers.

File: llvm/test/CodeGen/X86/PR71178-register-coalescer-crash.ll (hunk 3 above)
Comment (DianQK) [reply llvm/test/CodeGen/X86/PR71178-register-coalescer-crash.ll]: I can't believe I just found this pass, thanks.

File: llvm/lib/CodeGen/RegisterCoalescer.cpp (hunk 4 above)
Comment (DianQK) [reply llvm/lib/CodeGen/RegisterCoalescer.cpp]: Done.

**Review by arsenm — APPROVED** [review]

**Comment by DianQK** [comment]
Thanks for your patience in reviewing.

**Comment by DianQK** [comment]
Oops, since #80147 I should rebase.

**Comment by DianQK** [comment]
> Oops, since #80147 I should rebase.

Fixes.

**Review by qcolombet — COMMENTED** [review]
Sorry guys I'm late to the party.
Finally got time to look closer.
Ultimately I think the issue is we try to maintain a global state whereas the local and non-local worklist are not shared.

In this patch, I feel we are trying to reconstruct which list has been effectively modified and update the other one accordingly.

All in all, I think the complexity is not worth it.
Instead I would recommend that we stop being smart with ErasedInstrs and just remove that call to remove.

If the memory consumption is indeed a problem with ErasedInstrs growing, we can revisit.

@arsenm @DianQK what do you think?

**Comment by DianQK** [comment]
> Sorry guys I'm late to the party. Finally got time to look closer. Ultimately I think the issue is we try to maintain a global state whereas the local and non-local worklist are not shared.
> 
> In this patch, I feel we are trying to reconstruct which list has been effectively modified and update the other one accordingly.
> 
> All in all, I think the complexity is not worth it. Instead I would recommend that we stop being smart with ErasedInstrs and just remove that call to remove.
> 
> If the memory consumption is indeed a problem with ErasedInstrs growing, we can revisit.
> 
> @arsenm @DianQK what do you think?

I agree. `ErasedInstrs` makes maintenance complicated. I would be concerned that this issue would reappear again due to some sort of input. I think there is a need to redesign a solution.
