### PR TITLE
[clang-format] Fix a bug in indenting lambda trailing arrows

### LINKED ISSUE #94181: clang-format incorrectly indents lambda trailing return when lambda has constexpr specifier or noexcept specifier without expression
.clang-format:
```
BasedOnStyle: Google
```

Here is the formatted code when lambda doesn't have constexpr/noexcept specifier:
```c++
#include <type_traits>

void very_long_function_name_yes_it_is_really_long(...);

void do_something(...);

int main() {
  very_long_function_name_yes_it_is_really_long(
      [](auto n)
          -> std::enable_if_t<
              std::is_arithmetic<decltype(n)>::value &&
              !std::is_same<std::remove_cv_t<decltype(n)>, bool>::value> {
        do_something(n * 2);
      });
}
```

As expected trailing return arrow is indented 4 spaces after the lambda. But adding constexpr or noexcept specifier after lambda makes it 0 spaces:
```c++
#include <type_traits>

void very_long_function_name_yes_it_is_really_long(...);

void do_something(...);

int main() {
  very_long_function_name_yes_it_is_really_long(
      // also happens with constexpr specifier
      [](auto n) noexcept
      -> std::enable_if_t<
          std::is_arithmetic<decltype(n)>::value &&
          !std::is_same<std::remove_cv_t<decltype(n)>, bool>::value> {
        do_something(n * 2);
      });
}
```
Somewhat surprisingly, this issue doesn't happen when noexcept specifier with expression is used (e.g. `noexcept(true)`).

clang-format version: 17.0.6
OS: EndeavourOS Linux, kernel 6.9.3-arch1-1

### PR DESCRIPTION
**Pull request by c8ef**
Closes #94181

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -22858,6 +22858,31 @@ TEST_F(FormatTest, FormatsLambdas) {
       "      //\n"
       "    });");
 
+  verifyFormat("int main() {\n"
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/FormatTest.cpp:22861]: Get yourself a style with a lower column limit `auto Style = getLLVMStyleWithColumnLimit(40);` and use that, so that the lines don't have to be wrapped here, that's easier to read.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 2]
```diff
@@ -1457,6 +1457,11 @@ unsigned ContinuationIndenter::getNewLineColumn(const LineState &State) {
       !Current.isOneOf(tok::colon, tok::comment)) {
     return ContinuationIndent;
   }
+  if (Style.isCpp() && Current.is(tok::arrow) &&
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:1460]:
```suggestion
  if (Style.isCpp() && Current.is(TT_TrailingReturnArrow) &&
```
This is what you need, right?

File: clang/unittests/Format/FormatTest.cpp (hunk 1 above)
Comment (HazardyKnusperkeks) [reply clang/unittests/Format/FormatTest.cpp:22861]: Cache the style and re use it.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 3]
```diff
@@ -1457,7 +1457,7 @@ unsigned ContinuationIndenter::getNewLineColumn(const LineState &State) {
       !Current.isOneOf(tok::colon, tok::comment)) {
     return ContinuationIndent;
   }
-  if (Style.isCpp() && Current.is(tok::arrow) &&
+  if (Style.isCpp() && Current.is(TT_TrailingReturnArrow) &&
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:1460]: I also think you can drop the `isCpp`.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by rymiel — APPROVED** [review]

**Comment by rymiel** [comment]
Technically also applies to attributes applied to the return type of the lambda, i.e.
```
int main() {
  very_long_function_name_yes_it_is_really_long(
      // also happens with constexpr specifier
      [](auto n) [[attribute]]
      -> std::enable_if_t<
          std::is_arithmetic<decltype(n)>::value &&
          !std::is_same<std::remove_cv_t<decltype(n)>, bool>::value> {
        do_something(n * 2);
      });
}
```
...but currently at least no valid C++ attribute can go in that spot

File: clang/unittests/Format/FormatTest.cpp [hunk 4]
```diff
@@ -22858,6 +22858,36 @@ TEST_F(FormatTest, FormatsLambdas) {
...
+               LLVMStyle);
+  verifyFormat("int main() {\n"
+               "  very_long_function_name_yes_it_is_really_long(\n"
+               "      [](auto n) noexcept\n"
+               "          -> std::unordered_map<very_long_type_name_A,\n"
+               "                                very_long_type_name_B> {\n"
+               "        really_do_something();\n"
+               "      });\n"
+               "}",
+               LLVMStyle);
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:22880]:
```suggestion
  verifyFormat("very_long_function_name_yes_it_is_really_long(\n"
               "    [](auto n) noexcept [[back_attr]]\n"
               "        -> std::unordered_map<very_long_type_name_A,\n"
               "                              very_long_type_name_B> {\n"
               "      really_do_something();\n"
               "    });",
               Style);
```
Removes `main()` and adds `[[back_attr]]`.

File: clang/unittests/Format/FormatTest.cpp [hunk 5]
```diff
@@ -22858,6 +22858,36 @@ TEST_F(FormatTest, FormatsLambdas) {
...
+  verifyFormat("int main() {\n"
+               "  very_long_function_name_yes_it_is_really_long(\n"
+               "      [](auto n) constexpr\n"
+               "          -> std::unordered_map<very_long_type_name_A,\n"
+               "                                very_long_type_name_B> {\n"
+               "        really_do_something();\n"
+               "      });\n"
+               "}",
+               LLVMStyle);
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:22889]: Please remove `main()`.

**Comment by owenca** [comment]
> Technically also applies to attributes applied to the return type of the lambda, i.e.
> 
> ```
> int main() {
>   very_long_function_name_yes_it_is_really_long(
>       // also happens with constexpr specifier
>       [](auto n) [[attribute]]
>       -> std::enable_if_t<
>           std::is_arithmetic<decltype(n)>::value &&
>           !std::is_same<std::remove_cv_t<decltype(n)>, bool>::value> {
>         do_something(n * 2);
>       });
> }
> ```
> 
> ...but currently at least no valid C++ attribute can go in that spot

We can easily take care of it though. See https://github.com/llvm/llvm-project/pull/94560#discussion_r1632406068.

**Review by owenca — APPROVED** [review]
