### PR TITLE
[clang] CTAD: implement the missing IsDeducible constraint for alias templates 

### LINKED ISSUE #84492: CTAD for alias templates: implement the "is_deducible" constrain
We have an initial support at #77890 now.

However, the feature is not fully implemented yet, the `is_deducible` constrain is missing, see the FIXME at https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplate.cpp#L2909-L2914, and related testcase at https://github.com/llvm/llvm-project/blob/main/clang/test/SemaCXX/cxx20-ctad-type-alias.cpp#L188-L200

### LINKED ISSUE #85192: [clang] CTAD deduces alias template that does not satisfy the condition of the alias template
The following code snippet fails `static_assert`, and the type of `i2` is inferred to be (as reported in the diagnostic message) `std::array<std::array<int, 3>, 1>`, which does not even constitute a legal `my_ints`.

Godbolt link: https://godbolt.org/z/1Mo9hz4W7 .

```c++
#include <array>
#include <type_traits>

template <int N>
using my_ints = std::array<int, N>;

int main() {
    my_ints i = {1, 2, 3};
    my_ints i2 = {i};
    static_assert(std::is_same_v<decltype(i2), decltype(i)>);
    // error: static assertion failed due to requirement 'std::is_same_v<std::array<std::array<int, 3>, 1>, std::array<int, 3>>'
}
```

### PR DESCRIPTION
**Pull request by hokein**
Fixes https://github.com/llvm/llvm-project/issues/85192
Fixes https://github.com/llvm/llvm-project/issues/84492

This patch implements the "IsDeducible" constraint where the template arguments of the alias template can be deduced from the returned type of the synthesized deduction guide, per C++ [over.match.class.deduct]p4. In the implementation, we perform the deduction directly, which is more efficient than the way specified in the standard.

Also update relevant CTAD tests which were incorrectly compiled due to the missing constraint.

### CODE REVIEW

**Comment by hokein** [comment]
Regarding the __is_deducible type trait, GCC also provides one, but it was hidden from users and only used for internal CTAD implementation. I'm not sure if we should follow the same strategy in clang, ideas?

**Review by erichkeane — COMMENTED** [review]
Needs a release note, and I think we actually DO have to do those diagnostics here.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -3207,6 +3241,59 @@ Sema::DeduceTemplateArguments(VarTemplatePartialSpecializationDecl *Partial,
...
+  QualType PType;
+  if (const auto *CTD = dyn_cast<ClassTemplateDecl>(TD)) {
+    // Use the InjectedClassNameType.
+    PType = Context.getTypeDeclType(CTD->getTemplatedDecl());
+  } else if (const auto *AliasTemplate = dyn_cast<TypeAliasTemplateDecl>(TD)) {
+    PType = AliasTemplate->getTemplatedDecl()
+                ->getUnderlyingType()
+                .getCanonicalType();
+  } else {
+    // FIXME: emit a diagnostic, we only only support alias and class templates.
```
[the remark this answers is not in the document]
Comment (hokein) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: It turns out we will never hit other cases in this code path (we will reject the var/function templates when parsing the type trait expr). I changed it to `assert`.

**Comment by hokein** [comment]
> Needs a release note, and I think we actually DO have to do those diagnostics here.

Added a release note for the new builtin.

**Comment by cor3ntin** [comment]
> Regarding the __is_deducible type trait, GCC also provides one, but it was hidden from users and only used for internal CTAD implementation. I'm not sure if we should follow the same strategy in clang, ideas?

I have mixed feeling. What do you think @AaronBallman ?

File: clang/www/cxx_status.html [hunk 2]
```diff
@@ -868,13 +868,7 @@ <h2 id="cxx20">C++20 implementation status</h2>
...
       <td>Class template argument deduction for alias templates</td>
       <td><a href="https://wg21.link/p1814r0">P1814R0</a></td>
-      <td class="partial" align="center">
-        <details>
-          <summary>Clang 19 (Partial)</summary>
-          The associated constraints (over.match.class.deduct#3.3) for the
-          synthesized deduction guides are not yet implemented.
-        </details>
-      </td>
+      <td class="partial" align="center">Clang 19 (Partial)</td>
```
Comment (AaronBallman) [inline clang/www/cxx_status.html:871]: Why is this still partial?

**Comment by AaronBallman** [comment]
> > Regarding the __is_deducible type trait, GCC also provides one, but it was hidden from users and only used for internal CTAD implementation. I'm not sure if we should follow the same strategy in clang, ideas?
> 
> I have mixed feeling. What do you think @AaronBallman ?

Personally, I do not like exposing type traits that aren't for use with the STL. One idea would be to remove the type trait from TokenKinds.def and instead manually add `BTT_IsDeducible` to: https://github.com/llvm/llvm-project/blob/c61f0a8e94004b05d9ec115d3bff8cff331b4491/clang/include/clang/Basic/TypeTraits.h#L21 along with a comment explaining that this is for internal use only rather than be exposed to users. (You'd have to see if there are other places using `TYPE_TRAIT_2` that might need adjustment as well.) Then we can remove the release note, error checking can become assertions, etc.

**Comment by hokein** [comment]
> > > Regarding the __is_deducible type trait, GCC also provides one, but it was hidden from users and only used for internal CTAD implementation. I'm not sure if we should follow the same strategy in clang, ideas?
> > 
> > 
> > I have mixed feeling. What do you think @AaronBallman ?
> 
> Personally, I do not like exposing type traits that aren't for use with the STL. 

This is a valid argument. This type trait is supposed to be clang-internal only and should not be used in other places. The main benefit of exposing it is for testing purposes, and I personally found it to be really useful for debugging.

> One idea would be to remove the type trait from TokenKinds.def and instead manually add `BTT_IsDeducible` to:
> 
> https://github.com/llvm/llvm-project/blob/c61f0a8e94004b05d9ec115d3bff8cff331b4491/clang/include/clang/Basic/TypeTraits.h#L21
> 
> along with a comment explaining that this is for internal use only rather than be exposed to users. (You'd have to see if there are other places using `TYPE_TRAIT_2` that might need adjustment as well.) Then we can remove the release note, error checking can become assertions, etc.

This approach is doable technically, but it feels hacky and fragile. What if we emit an error (or warning) diagnostic and reject the code when we parse the `__is_deducible` type trait?

File: clang/www/cxx_status.html (hunk 2 above)
Comment (hokein) [reply clang/www/cxx_status.html:871]: With this patch, this feature is completed. However, I suspect that there maybe issues, and it needs some time to be productized. Therefore, I hesitate to say that it is "ready" (although I'm not sure what the common practice is).

**Comment by cor3ntin** [comment]
> This approach is doable technically, but it feels hacky and fragile. What if we emit an error (or warning) diagnostic and reject the code when we parse the __is_deducible type trait?

Why do you think it is fragile? I think a comment around `BTT_IsDeducible` would take care of that

File: clang/www/cxx_status.html (hunk 2 above)
Comment (cor3ntin) [reply clang/www/cxx_status.html:871]: Can you add back a details saying that the feature macro has not been updated?
However, i suspect that we do want to finalize the feature for Clang 19.

**Comment by hokein** [comment]
> > This approach is doable technically, but it feels hacky and fragile. What if we emit an error (or warning) diagnostic and reject the code when we parse the __is_deducible type trait?
> 
> Why do you think it is fragile? I think a comment around `BTT_IsDeducible` would take care of that

This is not a single-place change, we have to duplicate the `BTT_IsDeducible` manual change for at least 4 places:

- https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/TypeTraits.h#L28
- https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L21
- https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L30
- https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L61

**Comment by cor3ntin** [comment]
> > > This approach is doable technically, but it feels hacky and fragile. What if we emit an error (or warning) diagnostic and reject the code when we parse the __is_deducible type trait?
> > 
> > 
> > Why do you think it is fragile? I think a comment around `BTT_IsDeducible` would take care of that
> 
> This is not a single-place change, we have to duplicate the `BTT_IsDeducible` manual change for at least 4 places:
> 
> * https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/TypeTraits.h#L28
> * https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L21
> * https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L30
> * https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/TypeTraits.cpp#L61

Something like that seem to be fine

```cpp
// IsDeducible is only used internally by clang and is not exposed to source code
TYPE_TRAIT_2(/**/, IsDeducible, KEYCXX)
```

File: clang/www/cxx_status.html (hunk 2 above)
Comment (hokein) [reply clang/www/cxx_status.html]: Added it back.

**Comment by hokein** [comment]
OK, I have hidden the `__is_deducible` trait as suggested. Please take another look.

**Comment by cor3ntin** [comment]
> OK, I have hidden the `__is_deducible` trait as suggested. Please take another look.

Sorry, I think my suggestion was not clear enough.
did you try to put `TYPE_TRAIT_2(/**/, IsDeducible, KEYCXX)` in `TokenKinds.def` (and then other headers should _NOT_ be modified)

**Comment by hokein** [comment]
> > OK, I have hidden the `__is_deducible` trait as suggested. Please take another look.
> 
> Sorry, I think my suggestion was not clear enough. did you try to put `TYPE_TRAIT_2(/**/, IsDeducible, KEYCXX)` in `TokenKinds.def` (and then other headers should _NOT_ be modified)

Ah, I see. I haven't tried that, but one downside I can see is that it will make diagnostics for CTAD worse, we need to spell the type trait name in error messages when the `__is_deducible` trait fails.

**Comment by cor3ntin** [comment]
> Ah, I see. I haven't tried that, but one downside I can see is that it will make diagnostics for CTAD worse, we need to spell the type trait name in error messages when the __is_deducible trait fails.

I think we should have a custom diag for that anyway
"is not deducible from" is better than " `__is_deducible<>` is false"

**Comment by hokein** [comment]
> > Ah, I see. I haven't tried that, but one downside I can see is that it will make diagnostics for CTAD worse, we need to spell the type trait name in error messages when the __is_deducible trait fails.
> 
> I think we should have a custom diag for that anyway "is not deducible from" is better than " `__is_deducible<>` is false"

I think this is one of the symptoms, missing the trait name in the AST dump is another symptom.

And I'm not aware of an easy way to customize a diagnostic within clang's template-constraint check mechanism. One implementation I can think of is to manual call the `DeduceTemplateArgumentsFromType` in the function overload resolution for the alias CTAD, and then emit a custom diagnostic, but it feels awkward.

**Comment by hokein** [comment]
It appears that the consensus is to avoid exposing the internal `__is_deducible` type trait to end-users, as there are no compelling use cases and it's not expected to be used in libc++. This also aligns with the approach taken by GCC.

Regarding implementation, the current tablegen-based mechanism doesn't offer an optimal solution for defining internal-only builtins. Several options:

1) Making manual changes in the `TypeTrait` structure code, as proposed by @AaronBallman. While feasible, this approach may be somewhat hacky and would require modifications in multiple places (please see the current implementation, which involves four locations).
2) Following the standard defining-builtin approach but emitting a diagnostic warning when Clang parses `__is_deducible`. This option seems to strike the right balance, as it provides a compromise between adherence to clang's standard implementation and user guidance. Additionally, it would allow for dedicated lit tests for this type trait.
3) Following the standard approach but omitting the type trait name in the `TYPE_TRAIT_2` macro, as suggested by @cor3ntin. However, this approach will affect components that need to print the type-trait name (e.g., AST dump, diagnostics).

Opinions and thoughts would be appreciated, @AaronBallman, @cor3ntin, @erichkeane

**Comment by cor3ntin** [comment]
@hokein Independently of the direction taken I'd like to see a better diagnostic than "atomic constraint using an undocumented/cryptic trait that is not in the code is not satisfied". So when we try to print atomic constraints, we should do something more user friendly for is_deducible. (`note_atomic_constraint_evaluated_to_false` in `diagnoseWellFormedUnsatisfiedConstraintExpr` AFAICT).
It might be a bit ad-hoc, but I think it's worth doing

**Comment by hokein** [comment]
> @hokein Independently of the direction taken I'd like to see a better diagnostic than "atomic constraint using an undocumented/cryptic trait that is not in the code is not satisfied". 
> So when we try to print atomic constraints, we should do something more user friendly for is_deducible. (`note_atomic_constraint_evaluated_to_false` in `diagnoseWellFormedUnsatisfiedConstraintExpr` AFAICT). It might be a bit ad-hoc, but I think it's worth doing

I agree with you -- having a well-described diagnostic message is better and clearer. I'm happy to improve it once we settle on the final implementation approach (the current diagnostic `because '__is_deducible(AFoo, Foo<int>)' evaluated to false` seems okay to me. GCC also emits similar diagnostics).

By the way, other parts of this patch are ready for review.

**Comment by cor3ntin** [comment]
> I agree with you -- having a well-described diagnostic message is better and clearer. I'm happy to improve it once we settle on the final implementation approach (the current diagnostic because '__is_deducible(AFoo, Foo<int>)' evaluated to false seems okay to me. GCC also emits similar diagnostics).

Well, if we agree on that, the only thing to do for approach 3 is to deal with "anonymous" traits in ast dump and similar, which seems to be a fairly bounded effort!

**Comment by hokein** [comment]
> > I agree with you -- having a well-described diagnostic message is better and clearer. I'm happy to improve it once we settle on the final implementation approach (the current diagnostic because '__is_deducible(AFoo, Foo)' evaluated to false seems okay to me. GCC also emits similar diagnostics).
> 
> Well, if we agree on that, the only thing to do for approach 3 is to deal with "anonymous" traits in ast dump and similar, which seems to be a fairly bounded effort!

I was worried about the potential need to handle these issues in various places. However, thinking more about it today, I think we can address them locally in the `getTraitSpelling`, which seems like a more favorable approach.

I've now updated the patch to implement approach 3. Please take a look. Note that I haven't addressed the diagnostic improvement part yet; I plan to handle that in a separate follow-up patch.

File: clang/include/clang/Basic/TypeTraits.h [hunk 3]
```diff
@@ -27,7 +27,8 @@ enum TypeTrait {
   ,
 #define TYPE_TRAIT_2(Spelling, Name, Key) BTT_##Name,
 #include "clang/Basic/TokenKinds.def"
-  BTT_Last = UTT_Last // BTT_Last == last BTT_XX in the enum.
+  BTT_Last = UTT_Last
```
Comment (cor3ntin) [inline clang/include/clang/Basic/TypeTraits.h:30]: Why remove the comment?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 4]
```diff
@@ -3307,6 +3341,58 @@ Sema::DeduceTemplateArguments(VarTemplatePartialSpecializationDecl *Partial,
   return ::DeduceTemplateArguments(*this, Partial, TemplateArgs, Info);
 }
 
+TemplateDeductionResult
+Sema::DeduceTemplateArgumentsFromType(TemplateDecl *TD, QualType FromType,
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3345]: We have a lot of `DeduceTemplateArguments` function so I think we want to add a comment here describing what that function does / when it is used.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 5]
```diff
@@ -3239,6 +3239,40 @@ static TemplateDeductionResult FinishTemplateArgumentDeduction(
 
   return TemplateDeductionResult::Success;
 }
+/// Complete template argument deduction for DeduceTemplateArgumentsFromType.
+/// FIXME: this is mostly duplicated with the above two versions. Deduplicate
+/// the three implementations.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3244]: Is that something you would be willing to do in a follow up patch?

File: clang/lib/Sema/SemaTemplate.cpp [hunk 6]
```diff
@@ -2774,6 +2775,41 @@ Expr *transformRequireClause(Sema &SemaRef, FunctionTemplateDecl *FTD,
...
+// C++ [over.match.class.deduct]p3.3:
+//   The associated constraints ([temp.constr.decl]) are the conjunction of the
+//   associated constraints of g and a constraint that is satisfied if and only
+//   if the arguments of A are deducible (see below) from the return type.
+Expr *
+buildAssociatedConstraints(Sema &SemaRef, TypeAliasTemplateDecl *AliasTemplate,
+                           FunctionTemplateDecl *FTD,
+                           llvm::ArrayRef<TemplateArgument> TransformedArgs,
+                           QualType ReturnType) {
+  auto &Context = SemaRef.Context;
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplate.cpp:2788]:
```suggestion
  (const?) ASTContext &Context = SemaRef.Context;
```

File: clang/lib/Sema/SemaTemplate.cpp [hunk 7]
```diff
@@ -18,6 +18,7 @@
 #include "clang/AST/ExprCXX.h"
 #include "clang/AST/RecursiveASTVisitor.h"
 #include "clang/AST/TemplateName.h"
+#include "clang/AST/Type.h"
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplate.cpp:21]: Probably not a needed change

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 8]
```diff
@@ -6116,6 +6116,17 @@ static bool EvaluateBinaryTypeTrait(Sema &Self, TypeTrait BTT, const TypeSourceI
...
+  }
+  case BTT_IsDeducible: {
+    if (const auto *TSTToBeDeduced =
+            LhsT->getAs<DeducedTemplateSpecializationType>()) {
+      sema::TemplateDeductionInfo Info(KeyLoc);
+      return Self.DeduceTemplateArgumentsFromType(
+                 TSTToBeDeduced->getTemplateName().getAsTemplateDecl(), RhsT,
+                 Info) == TemplateDeductionResult::Success;
+    }
+    assert("Expect to see DeducedTemplateSpecializationType!");
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExprCXX.cpp:6128]: that is always true (you probably mean `false && ""`).
But I would remove the `if`, use `cast<DeducedTemplateSpecializationType>(LhsT)` that will assert for you)

File: clang/test/SemaCXX/cxx20-ctad-type-alias.cpp [hunk 9]
```diff
@@ -190,13 +196,15 @@ template <class T> struct Foo { Foo(T); };
 
 template<class V> using AFoo = Foo<V *>;
 template<typename> concept False = false;
-template<False W> using BFoo = AFoo<W>;
+template<False W>
+using BFoo = AFoo<W>; // expected-note {{candidate template ignored: constraints not satisfied [with V = int]}} \
+                      // expected-note {{because '__is_deducible(BFoo, Foo<int *>)' evaluated to false}} \
```
Comment (cor3ntin) [inline clang/test/SemaCXX/cxx20-ctad-type-alias.cpp:201]: I think we want to add code in this PR to improve the diagnostic

File: clang/include/clang/Basic/TypeTraits.h (hunk 3 above)
Comment (hokein) [reply clang/include/clang/Basic/TypeTraits.h:30]: oops, this is not intended. This was left when I reverted some changes.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 5 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3244]: It is in my TODO list, but its priority is currently low, so I don't anticipate addressing it in the near future. This seems like a good candidate for a "GoodFirst" issue, so I'm thinking we can file an issue in case someone wants to contribute.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3345]: This function is public (the documentation and comments are in `Sema.h` header).

File: clang/test/SemaCXX/cxx20-ctad-type-alias.cpp (hunk 9 above)
Comment (hokein) [reply clang/test/SemaCXX/cxx20-ctad-type-alias.cpp:201]: Do you think this is a blocker for landing this PR?  The current state is acceptable to me, although not ideal. I plan to send out a follow-up patch to address it.

**Review by hokein — COMMENTED** [review]
Replied some review comments. I haven't updated the code yet (plan to do it after #90961)

File: clang/include/clang/Basic/TypeTraits.h (hunk 3 above)
Comment (hokein) [reply clang/include/clang/Basic/TypeTraits.h]: Reverted the change.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 7 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Done.

File: clang/test/SemaCXX/cxx20-ctad-type-alias.cpp (hunk 9 above)
Comment (hokein) [reply clang/test/SemaCXX/cxx20-ctad-type-alias.cpp:202]: I'd prefer to do it in a follow up (this patch is quite large already). Added a FIXME.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 6 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplate.cpp:2929]: I'm not seeing a change here?

**Review by cor3ntin — APPROVED** [review]
I'll approve that modulo nit but i think we want

- An issue to keep track of the duplication in `FinishTemplateArgumentDeduction`
- A follow up PR to improve diagnostics


Thanks!

File: clang/lib/Sema/SemaTemplate.cpp (hunk 6 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp:2930]: Oops,  it looks like I forgot to push one commit.

**Comment by hokein** [comment]
Thanks for the review.

> I'll approve that modulo nit but i think we want
> 
> * An issue to keep track of the duplication in `FinishTemplateArgumentDeduction`

Filed #92224.

> * A follow up PR to improve diagnostics

Filed #92225, and assigned to myself. Will do it.

> Thanks!

**Review by cor3ntin — APPROVED** [review]

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 10]
```diff
@@ -3237,6 +3237,40 @@ static TemplateDeductionResult FinishTemplateArgumentDeduction(
...
+  // C++ [temp.deduct.type]p2:
+  //   [...] or if any template argument remains neither deduced nor
+  //   explicitly specified, template argument deduction fails.
+  SmallVector<TemplateArgument, 4> SugaredBuilder, CanonicalBuilder;
+  if (auto Result = ConvertDeducedTemplateArguments(
+          S, TD, /*IsPartialOrdering=*/false, Deduced, Info, SugaredBuilder,
+          CanonicalBuilder);
+      Result != TemplateDeductionResult::Success)
+    return Result;
+
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3263]: This is missing a consistency check, ie [temp.deduct.type]p1.

Otherwise we would incorrectly accept a match where there would be a non-deduced mismatch.
