### PR TITLE
[InstCombine][asan] Don't speculate loads before `select ptr`

### LINKED ISSUE #100639: [asan] Custom poisoning on stack is broken by optimizations
This is reproducer on 
https://github.com/abseil/abseil-cpp/blob/c98bd9c8840f9ded87cf1fd1238455468d325628/absl/strings/cord_test.cc

Note: Revision is important as we are planing to land absl:: workaround.

libc++ also hit that issue

[https://github.com/llvm/llvm-project/pull/79536/files#diff-534bc2907ddb3b074ded1353d18fd7d578daf1707943b3039bab4ed975aba3b3R772](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fllvm%2Fllvm-project%2Fpull%2F79536%2Ffiles%23diff-534bc2907ddb3b074ded1353d18fd7d578daf1707943b3039bab4ed975aba3b3R772)

```
// This must not be static to avoid aggressive optimizations.
ABSL_ATTRIBUTE_WEAK
size_t FalseReport(const absl::Cord& a, bool f);

ABSL_ATTRIBUTE_NOINLINE
size_t FalseReport(const absl::Cord& a, bool f) {
  absl::Cord b;
  const absl::Cord& ref = f ? b : a;
  // Test that sanitizers report nothing here. Without
  // InlineData::Rep::annotated_this() compiler can unconditionally load
  // poisoned parts, assuming that local variable is fully accessible.
  return ref.size();
}

TEST(CordSanitizerTest, SanitizesCordFalseReport) {
  absl::Cord c;
  for (int i = 0; i < 1000; ++i)
    c.Append("a");
  FalseReport(c, false);
}
```

I will add minimized repro later.

The issues is in InstCombine or SimplifyCFG, and likely should be fixed with `llvm::mustSuppressSpeculation`.

### PR DESCRIPTION
**Pull request by vitalybuka**
Even if memory is valid from `llvm` point of view,
e.g. local alloca, sanitizers have API for user
specific memory annotations.

These annotations can be used to track size of the
local object, e.g. inline vectors may prevent
accesses beyond the current vector size.

So valid programs should not access those parts of
alloca before checking preconditions.

Fixes #100639.

### CODE REVIEW

**Review by thurstond — APPROVED** [review]

File: llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp [hunk 1]
```diff
@@ -1042,8 +1042,8 @@ Instruction *InstCombinerImpl::visitLoadInst(LoadInst &LI) {
   }
 
   // None of the following transforms are legal for volatile/ordered atomic
-  // loads.  Most of them do apply for unordered atomics.
-  if (!LI.isUnordered()) return nullptr;
+  // loads and sanitizers.  Most of them do apply for unordered atomics.
+  if (mustSuppressSpeculation(LI)) return nullptr;
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp:1046]: Can we move this check to where it is relevant, i.e. the select fold in particular?

Also, should this check be inside isSafeToLoadUnconditionally maybe?

Comment (vitalybuka) [reply llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp]: Done.

**Review by kstoimenov — APPROVED** [review]

**Review by nikic — APPROVED** [review]
LGTM
