### PR TITLE
[clang-tidy][use-internal-linkage] fix false positive for consteval function

### LINKED ISSUE #122096: misc-use-internal-linkage should not warn about consteval functions
`consteval` functions never end up in the machine code. The `misc-use-internal-linkage` check should omit them.

```cpp
consteval int f(int x) { return x; }
```

https://godbolt.org/z/b37fohnEY

### PR DESCRIPTION
**Pull request by maflcko**
Fixes https://github.com/llvm/llvm-project/issues/122096

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/misc/use-internal-linkage-consteval.cpp [hunk 1]
```diff
@@ -0,0 +1,3 @@
+// RUN: %check_clang_tidy -std=c++20 %s misc-use-internal-linkage %t -- -- -I%S/Inputs/use-internal-linkage
+
+consteval void gh122096() {}
```
Comment (chfast) [inline clang-tools-extra/test/clang-tidy/checkers/misc/use-internal-linkage-consteval.cpp:3]: Can you also check `constexpr void func_constexpr()`?

**Review by chfast — APPROVED** [review]

**Review by HerrCai0907 — APPROVED** [review]
lgtm.

**Review by 5chmidti — APPROVED** [review]
