### PR TITLE
Fixing the logic issue in TransformTypos::TransformDesignatedInitExpr…

### LINKED ISSUE #126113: [Clang FE] Possible logic issue in `TransformTypos::TransformDesignatedInitExpr`
When running the tree-visitor `TransformTypos` on a `DesignatedInitExpr` node, it first tries to transform its initializer
```
// transform the initializer value
  ExprResult Init = getDerived().TransformExpr(E->getInit());
```
and later on decides whether the AST changes by
```
ExprChanged = ExprChanged || Init.get() != E->getArrayIndex(D);
```
at https://github.com/llvm/llvm-project/blob/5492199a9aa4b5d31c38e36928ac153570091d6d/clang/lib/Sema/TreeTransform.h#L13659

The logic in `Init.get() != E->getArrayIndex(D)` seems not correct as the initializer and the index of the designator are being compared, which is  likely to always be true.  In contrast, later in the same function
https://github.com/llvm/llvm-project/blob/5492199a9aa4b5d31c38e36928ac153570091d6d/clang/lib/Sema/TreeTransform.h#L13685
The old initializer and the initializer after transform are compared.

Ran debugger on clang compiling a designator example
```
const char *str[] = {
    [some_typo] = "0"
};
```
and stepped in to the line, `Init.get()` is a StringLiteral and `E->getArrayIndex(D)` is a TypoExpr.

### PR DESCRIPTION
**Pull request by GS-GOAT**
… #126113

-Transforming Indices: For array designators, transform the index expression and update ExprChanged if it's modified.
-Correct Initializer Check: Compare the transformed initializer against the original to accurately track changes.
-Single Initializer Transformation: The initializer is processed once, not per designator, as each DesignatedInitExpr has one initializer.

Fixes #126113

### CODE REVIEW

**Review by zyn0217 — COMMENTED** [review]
Thanks. Though I think we should just fix the problematic condition expression, and other changes seem a bit unnecessary since they are already clear enough.

**Comment by GS-GOAT** [comment]
@zyn0217 Please review.

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -13665,15 +13665,15 @@ TreeTransform<Derived>::TransformDesignatedInitExpr(DesignatedInitExpr *E) {
     }
 
     if (D.isArrayDesignator()) {
-      ExprResult Index = getDerived().TransformExpr(E->getArrayIndex(D));
-      if (Index.isInvalid())
+      ExprResult NewIndex = getDerived().TransformExpr(E->getArrayIndex(D));
```
Comment (zyn0217) [inline clang/lib/Sema/TreeTransform.h:13668]: Can you avoid renaming the variable? Thanks

**Comment by GS-GOAT** [comment]
@zyn0217 Made the suggested changes.

**Review by zyn0217 — APPROVED** [review]
