### PR TITLE
[LoongArch] Enable tail calls for sret and byval functions

### LINKED ISSUE #168152: loongarch64: failed to perform tail call elimination on a call site marked musttail
This LLVM IR

https://godbolt.org/z/8TsGoPvnj

```llvm
target triple = "loongarch64-unknown-linux-gnu"

define internal void @callee(ptr dead_on_unwind noalias noundef nonnull writable writeonly sret([24 x i8]) align 1 captures(none) dereferenceable(24) initializes((0, 24)) %_0) unnamed_addr {
start:
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(24) %_0, i8 0, i64 24, i1 false)
  ret void
}

define void @dispatch(ptr dead_on_unwind noalias noundef writable writeonly sret([24 x i8]) align 1 captures(none) dereferenceable(24) initializes((0, 24)) %_0) unnamed_addr {
start:
  musttail call void @callee(ptr noalias noundef sret([24 x i8]) align 1 captures(none) dereferenceable(24) %_0)
  ret void
}

declare void @llvm.memset.p0.i64(ptr writeonly captures(none), i8, i64, i1 immarg) #1
```

Errors with 

```
LLVM ERROR: failed to perform tail call elimination on a call site marked musttail
```

I suspect riscv has essentially the same problem, see also

- https://github.com/llvm/llvm-project/issues/157814
-  https://github.com/rust-lang/rust/issues/148748

This is inconvenient for rust stabilization of guaranteed tail calls. For rust it would be sufficient to accept the case where the stack space used for the return value is identical for `callee` and `dispatch`, that is probably easier to support than the general case.

### PR DESCRIPTION
**Pull request by heiher**
Allow tail calls for functions returning via sret when the caller's sret pointer can be reused. Also support tail calls for byval arguments.
    
The previous restriction requiring exact match of caller and callee arguments is relaxed: tail calls are allowed as long as the callee does not use more stack space than the caller.

Fixes #168152

### CODE REVIEW

**Comment by folkertdev** [comment]
> I also noticed that the byval argument test cases are still failing on LoongArch (and AArch64).

I'm not sure what you mean here.

Rust currently disallows a `become` on a function call that uses any `PassMode::Indirect` arguments. I want to relax that restriction to accept (what LLVM calls) `byval` arguments. 

However it turns out that many LLVM backends also do not support `byval` arguments correctly: the arm backends do support it now (I suspect since https://github.com/llvm/llvm-project/pull/109943), and I'll try to add support for x86_64 in https://github.com/llvm/llvm-project/pull/168956 by basically emulating the aarch64 approach. With loongarch (this PR), riscv (where we can basically copy this PR) and maybe powerpc/s390x (who have been quite responsive in fixing issues we run into) that should cover all of the major architectures I think.

---

What rust requires is a subset of musttail: we currently only allow sibcalls (so, ABI between caller and callee is a perfect match), but we want to support an arbitrary number of arguments, and want any rust type (that is FFI-safe/has a stable layout) to work as an argument.

**Review by SixWeining — APPROVED** [review]

File: llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp [hunk 1]
```diff
@@ -8225,6 +8226,8 @@ SDValue LoongArchTargetLowering::LowerFormalArguments(
       continue;
     }
     InVals.push_back(ArgValue);
+    if (Ins[InsIdx].Flags.isByVal())
+      LoongArchFI->addIncomingByValArgs(ArgValue);
```
Comment (lenary) [inline llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp:8230]: This has a significant lifetime issue, that we feel is enough to do a revert on RISC-V. The SDValue has a lifetime which matches the current block, not the whole function. the LoongArchFI has function lifetime.

In short, if you have a musttail call in any block except the entry block, this code is not going to work.

**Review by lenary — COMMENTED** [review]
I will be reverting this, the comment inline is the problem that caused me to want to revert on RISC-V, but the reality is there is a follow-on commit (ab17b5408ac83a03807b6f0ea22f51dfb84b0b8a) that touches both RISC-V and LoongArch to fix a different bug, and I think it's much cleaner to revert all three patches entirely and start again.

We're in the middle of the release cycle, so I think there is ample time to fix this and re-land it before the branch for LLVM 23.
