### PR TITLE
[clang] Do not clear FP pragma stack when instantiating functions

### LINKED ISSUE #69717: Problems with float_control pragma stack in Clang 17.x
When working on integrating Clang 17 in our engine we noticed that we were getting some errors when we used `#pragma float_control`, specifically the last `pop` resulted in the following error:

```
pipeline\packages\graphics\GraphicCore\src\graphic\tools\meshtools.cpp(2362,9): error: #pragma float_control(pop, ...) failed: stack empty [-Werror,-Wignored-pragmas]
 2362 | #pragma float_control(pop)
      |         ^
1 error generated.
```

I first thought this was a new warning so I dumped the preprocessed files to see if there was an "imbalance", here is the result:

```
16:#pragma float_control(precise, on, push)
76314:#pragma float_control( push )
76341:#pragma float_control( pop )
306286:#pragma float_control(precise, off, push)
306297:#pragma float_control(pop)
306392:#pragma float_control(precise, off, push)
306403:#pragma float_control(pop)
744987:#pragma float_control(pop)
```

As you see they are balanced. 

I added some debug information in `Sema::ActOnPragmaFloatControl` and noticed that the stack gets randomly reset between calls:

```
float_control(push|set)
stack: 1
float_control(push)
stack: 1
float_control(pop)
stack: 0
float_control(push|set)
stack: 1
float_control(pop)
stack: 0
float_control(push|set)
stack: 1
float_control(pop)
stack: 0
float_control(pop)
```

I noticed that there were some changes by @spavloff in Clang 17 around these and then traced down the following two commits:

https://github.com/llvm/llvm-project/commit/0baf85c331090fbe2d2b42214ed0664d55feb0b5
https://github.com/llvm/llvm-project/commit/2e903709de003dc6ae980197f4a0850a158dd9b8

If I revert these two the stack is behaving as **I** expect it to behave.

I have tried to make a smaller reproducer, but there is probably something missing because just doing several push/pops nested in a single C++ with some headers doesn't reproduce the problem. So it's probably down to something I am missing with the set of patches.

So I need to understand if this is something wrong with our code or a bug in clang.

I have tested both 17.0.3 and HEAD with the same issues.

### PR DESCRIPTION
**Pull request by spavloff**
When instantiation function, a call to Sema::resetFPOption was used to set the FP options associated with AST node. However this function also cleared FP pragma stack, and it is incorrect. Template instantiation takes place on AST representation and semantic information like the FP pragma stack should not affect it. This was a reason for miscompilation in some cases.

To make the Sema interface more consistent, now `resetFPOptions` does not clear FP pragma stack anymore. It is cleared in `FpPragmaStackSaveRAII`, which is used in parsing only.

This change must fix https://github.com/llvm/llvm-project/issues/69717 (Problems with float_control pragma stack in Clang 17.x).

### CODE REVIEW

**Review by rjmccall — COMMENTED** [review]
To be clear, we're still ensuring the current pragma state during instantiation is what it was when the template is parsed, we're just not incorrectly dropping all of the saved pragma state when we're doing it?

**Comment by tru** [comment]
Our code compiles without warnings with this patch!

**Comment by spavloff** [comment]
> To be clear, we're still ensuring the current pragma state during instantiation is what it was when the template is parsed, we're just not incorrectly dropping all of the saved pragma state when we're doing it?

Yes, the pragma is used at parse stage to set correct FP options is AST nodes. During template instantiation the function `resetFPOptions` is used to set the required FP options in Sema, because in some cases (ImplicitCast) the options are taken from Sema and not AST node. As a result the new AST nodes get FP otions as they are specified in the template pattern.

The issue with `resetFPOptions` was that it also reset pragma stack. It is OK for late template parse, or for the functions that are instantiated at the end of translation unit, but not for templates that are instantiated immediately, like consexpr functions.

**Comment by rjmccall** [comment]
That makes sense.  Out of curiosity, since presumably the instantiation path is using the RAII class, and the RAII class seems to save and restore the entire stack, what actually ends up going wrong?  It doesn't look like your test case has local changes to the stack within the instantiated function.  I'm just wondering whether we maybe just have a bad API here.

**Comment by spavloff** [comment]
Actually the pragma stack is not saved during template instantiation. It is saved during late template parsing using class `FpPragmaStackSaveRAII`. For template instantiation the dependency on the stack can be considered as an error, because all information about FP options should be taken from AST.

That was the reason for this issue - the pragma stack was cleared because `resetFPOptions` was introduced for late parsing. If instantiation was made during parsing, it spoiled the pragma stack.

**Comment by rjmccall** [comment]
I see, that makes sense.  It shouldn't really need to be saved even during late template parsing, right?  Late template parsing is never at the top level, and push/pop are only allowed at the top level.

**Comment by spavloff** [comment]
Late parsing (in contrast to template instantiation) is sensitive to the pragma stack because the late parsed text may contain pragmas. If, for example, the parsed text contains unbalanced pus/pop pragmas, it is detected if the pragma stack is empty, but can be missed if there is an unfinished pragma.

**Comment by rjmccall** [comment]
It's certainly possible to see push/pop pragmas in late-parsed code, but Sema should immediately emit an error and ignore them because, like I said, they're only allowed at file context, and AFAIK late-parsed code is never at file context.  If there's some sneaky way to late-parse file-context declarations, that seems like a serious problem, because it's very important to process pragmas in order as we parse the top level.  And contrariwise, if there's some sneaky way to put push/pop pragmas in non-file contexts, that also seems like a serious problem, because the way we process them is not designed to understand local scopes, which means we're just doing random stuff instead of implementing any sort of intelligible language design.

Now, I don't really mind the late-parsing code being overly cautious about things possibly pushing and popping on the pragma stack as long as it's not costing us a significant amount of performance, but it would also be fine for it to assert that that hasn't happened and then just save and restore the active state, which is the only thing that late parsing should ever touch.

**Comment by AaronBallman** [comment]
> And contrariwise, if there's some sneaky way to put push/pop pragmas in non-file contexts, that also seems like a serious problem, because the way we process them is not designed to understand local scopes, which means we're just doing random stuff instead of implementing any sort of intelligible language design.

What if it's a non-sneaky way? ;-) C has several fp-related pragmas that are required to be supported at block scope. For example, the specification for `#pragma STDC FP_CONTRACT` (C23 7.12.2p2) says: 

> ... Each pragma can occur either outside external declarations or preceding all explicit declarations and statements inside a compound statement. When outside external declarations, the pragma takes effect from its occurrence until another FP_CONTRACT pragma is encountered, or until the end of the translation unit. When inside a compound statement, the pragma takes effect from its occurrence until another FP_CONTRACT pragma is encountered (including within a nested compound statement), or until the end of the compound statement; at the end of a compound statement the state for the pragma is restored to its condition just before the compound statement. If this pragma is used in any other context, the behavior is undefined. ...

Other standard pragmas have similar wording. CC @zahiraam who has also been working on pragmas in this area.

**Comment by rjmccall** [comment]
> > And contrariwise, if there's some sneaky way to put push/pop pragmas in non-file contexts, that also seems like a serious problem, because the way we process them is not designed to understand local scopes, which means we're just doing random stuff instead of implementing any sort of intelligible language design.
> 
> What if it's a non-sneaky way? ;-) C has several fp-related pragmas that are required to be supported at block scope. For example, the specification for `#pragma STDC FP_CONTRACT` (C23 7.12.2p2) says:

That's fine because it's scoped to the function and doesn't affect the state at file context.  Even if `FP_CONTRACT` had an explicit push/pop mechanic (which it doesn't), as long as it was localized to the function and couldn't change/observe the outer stack beyond observing the currently-active state, we wouldn't need to save and restore the full pragma stack.  The user model for these file context pragmas, especially push/pop, assumes that there's a well-ordered sequence of file-context declarations and pragmas.  It would be very difficult for us to late-parse parts of the file context for a lot of reasons, but pragma ordering is one of them.  The whole point of late-parsing A is that we want to parse B that comes after A in the TU before we parse A (which we might never parse at all).  If A is part of the file context, the current state of the various pragma stacks in B needs to reflect the top-level pragmas in A (as well as a bunch of other state, of course, like any names introduced in A), which means we'd have to at least partially parse A before we can parse B.

The upshot is that we don't (and shouldn't) ever late-parse at file context, which by design means we can't see stack-manipulating pragmas because they're all restricted to file context.  In late parsing, we only ever observe and change the innermost state of the pragma stack, and so all we need to do is temporarily restore that innermost state to what it was when the tokens were originally captured, then restore it to its "live" value after the late parsing is complete.

**Comment by AaronBallman** [comment]
> > > And contrariwise, if there's some sneaky way to put push/pop pragmas in non-file contexts, that also seems like a serious problem, because the way we process them is not designed to understand local scopes, which means we're just doing random stuff instead of implementing any sort of intelligible language design.
> > 
> > 
> > What if it's a non-sneaky way? ;-) C has several fp-related pragmas that are required to be supported at block scope. For example, the specification for `#pragma STDC FP_CONTRACT` (C23 7.12.2p2) says:
> 
> That's fine because it's scoped to the function and doesn't affect the state at file context.

Oh that's true!

> Even if `FP_CONTRACT` had an explicit push/pop mechanic (which it doesn't), as long as it was localized to the function and couldn't change/observe the outer stack beyond observing the currently-active state, we wouldn't need to save and restore the full pragma stack. The user model for these file context pragmas, especially push/pop, assumes that there's a well-ordered sequence of file-context declarations and pragmas. It would be very difficult for us to late-parse parts of the file context for a lot of reasons, but pragma ordering is one of them. The whole point of late-parsing A is that we want to parse B that comes after A in the TU before we parse A (which we might never parse at all). If A is part of the file context, the current state of the various pragma stacks in B needs to reflect the top-level pragmas in A (as well as a bunch of other state, of course, like any names introduced in A), which means we'd have to at least partially parse A before we can parse B.

Agreed, thank you for the longer explanation. I thought the concern was with having (preprocessor) pragmas that had bounds that could only be determined at parse time.

> The upshot is that we don't (and shouldn't) ever late-parse at file context, which by design means we can't see stack-manipulating pragmas because they're all restricted to file context. In late parsing, we only ever observe and change the innermost state of the pragma stack, and so all we need to do is temporarily restore that innermost state to what it was when the tokens were originally captured, then restore it to its "live" value after the late parsing is complete. The rest of the stack is untouchable.

"shouldn't ever late parse at file context" is something I agree with when I think about most language constructs, but as a counter-example, folks have been agitating more and more for the ability for an attribute argument to reference a subsequent declaration. e.g.,
```
void func(int *ptr [[attr(len)]], size_t len);

struct S {
  int *Ptr [[attr(len)]];
  int Len;
};
```
and the likes. I can imagine someone wanting to extend that to:
```
int *GlobalArray [[attr(GlobalLen)]];
int GlobalLen;
```
because reordering the globals may change other semantic behavior (like initialization order for dynamic init). Should we perhaps add documentation to the internals manual so we capture the issues with file-scope late parsing?

**Comment by rjmccall** [comment]
> > The upshot is that we don't (and shouldn't) ever late-parse at file context, which by design means we can't see stack-manipulating pragmas because they're all restricted to file context. In late parsing, we only ever observe and change the innermost state of the pragma stack, and so all we need to do is temporarily restore that innermost state to what it was when the tokens were originally captured, then restore it to its "live" value after the late parsing is complete. The rest of the stack is untouchable.
> 
> "shouldn't ever late parse at file context" is something I agree with when I think about most language constructs, but as a counter-example, folks have been agitating more and more for the ability for an attribute argument to reference a subsequent declaration. e.g.,
> 
> ```
> void func(int *ptr [[attr(len)]], size_t len);
> 
> struct S {
>   int *Ptr [[attr(len)]];
>   int Len;
> };
> ```
> 
> and the likes. I can imagine someone wanting to extend that to:
> 
> ```
> int *GlobalArray [[attr(GlobalLen)]];
> int GlobalLen;
> ```
> 
> because reordering the globals may change other semantic behavior (like initialization order for dynamic init). Should we perhaps add documentation to the internals manual so we capture the issues with file-scope late parsing?

Yes, I think that'd be good.  To me, the right way of thinking about this kind of code is that it's not truly at file context — it's not really standalone, we just don't really have the `Decl` that it's part of yet.  For example, there's a lot of things you really shouldn't be able to write in a statement-expression in a global initializer, the bound of an array type, and so on, but our checking doesn't always prohibit them because e.g. there isn't a meaningful `DeclContext` we can put in `CurContext` that will reflect that this isn't really a local context.  (The way we solved this in Swift's AST is that a `DeclContext` doesn't have to be a `Decl`, and we lazily create an `Initializer` DC when processing other kinds of top-level expressions.)  This is a longstanding issue.

**Comment by tru** [comment]
Can this be merged and ready for a backport next week?

**Comment by spavloff** [comment]
`pragma pack` uses pragma stack and it is allowed in any place: https://godbolt.org/z/f8fP1vn63 . If such pragma presents in the late-parsed template, and push-pop operations in it are not balanced, the late parse of such function can break the pragma stack and next templates can be parsed incorrectly. It is not a FP pragma, but it demonstrates that the compiler must provide some Sema state isolation for late parsed templates.

For floating-point pragmas the stack could be cleared once, before the late parsing takes place. However it is complicated by the fact that the pragma stack set in precompiled header must be available in the unit that uses the header. Another complication is implicit assumption in some places that the default FP options are defined by LangOpts. It is not true, in some cases target may modify the default state (i386 is an example).

This fix is not optimal. The problems mentioned above are solvable and they should be fixed. However to have a quick solution for the initial PR the fix probably could be used.

**Comment by rjmccall** [comment]
> pragma pack uses pragma stack and it is allowed in any place: https://godbolt.org/z/f8fP1vn63 . If such pragma presents in the late-parsed template, and push-pop operations in it are not balanced, the late parse of such function can break the pragma stack and next templates can be parsed incorrectly. It is not a FP pragma, but it demonstrates that the compiler must provide some Sema state isolation for late parsed templates.

Okay, so if we accept this, this is a hard constraint on our ability to do late parsing of function bodies in situations not blessed by the language.  We could decide not to support that — we probably have to support uses of `#pragma pack` within a function, but we could e.g. emit an error if the effect of the pragmas is non-local (or a warning saying that we're going to ignore it).  It looks like MSVC clears the stack before it does late parsing: you get a warning if you put your test function inside a class body.

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -710,9 +710,11 @@ class Sema final {
     return result;
   }
 
+  // Saves the current floating-point pragma stack and clear it in this Sema.
   class FpPragmaStackSaveRAII {
   public:
-    FpPragmaStackSaveRAII(Sema &S) : S(S), SavedStack(S.FpPragmaStack) {}
+    FpPragmaStackSaveRAII(Sema &S)
+        : S(S), SavedStack(std::move(S.FpPragmaStack)) {}
```
Comment (rjmccall) [inline clang/include/clang/Sema/Sema.h:717]: Does a move of `PragmaStack` guarantee to leave an empty stack?  I guess it's ultimately just a `SmallVector`, and it looks like `SmallVector` does currently make that guarantee.  That seems worth a comment or an assertion.

**Review by rjmccall — COMMENTED** [review]
Otherwise LGTM

**Comment by tru** [comment]
17.0.5 is going to be released tomorrow, is this fix good to go for the backport?

File: clang/include/clang/Sema/Sema.h (hunk 1 above)
Comment (spavloff) [reply clang/include/clang/Sema/Sema.h]: Added explicit stack reset.

**Comment by spavloff** [comment]
Added commit: https://github.com/llvm/llvm-project/commit/93ae26331592f41bf2b1d10b048743d80c468385 to run the test on x86 only.
