### PR TITLE
[clangd] Fix regression regarding new line handling for hover/signature help content

### LINKED ISSUE #2513: Signature information missing line breaks in VSCode
**VSCode version:**
1.104.2

**VSCode clangd extension:**
Version 0.2.0
(also tried with the prerelease version 0.3.2)

**Clangd Version:** 
clangd version 22.0.0git (https://github.com/llvm/llvm-project.git 47211c4b96e99a3344a71570a99b991c5f5c1c01)
Features: mac+xpc
Platform: arm64-apple-darwin24.6.0

VSCode signature help shows code comments without line breaks.  I've tried using the various .clangd CommentFormat values (plaintext, markdown, doxygen) but signature help doesn't change.  This makes the comment information less useful because it's hard to read.

Note that on clangd included with macOS line breaks are correct:

Apple clangd version 17.0.0 (clang-1700.3.19.1)
Features: mac+xpc
Platform: arm64-apple-darwin24.6.0

See attached images.

### PR DESCRIPTION
**Pull request by tcottin**
Fix clangd/clangd#2513

This regression was introduced with #140498.

The issue is that with #140498 the extraction of the documentation comment changed from line based to paragraph based.
This also removed some required line breaks inside paragraphs, which used to be added before the change.

This PR adds the missing line breaks again.

### CODE REVIEW

**Comment by JWTheDBA** [comment]
Is it possible for someone to either approve this PR or provide tcottin feedback on what to correct so it can be merged?

File: clang-tools-extra/clangd/support/Markup.cpp [hunk 1]
```diff
@@ -575,64 +631,18 @@ bool Paragraph::isHardLineBreakIndicator(llvm::StringRef Rest) const {
...
-bool Paragraph::isHardLineBreakAfter(llvm::StringRef Line,
-                                     llvm::StringRef Rest) const {
-  // In Markdown, 2 spaces before a line break forces a line break.
-  // Add a line break for plaintext in this case too.
+bool Paragraph::isHardLineBreakAfter(llvm::StringRef Line, llvm::StringRef Rest,
+                                     bool IsMarkdown) const {
   // Should we also consider whether Line is short?
-  return Line.ends_with("  ") || punctuationIndicatesLineBreak(Line) ||
-         isHardLineBreakIndicator(Rest);
+  return (punctuationIndicatesLineBreak(Line, IsMarkdown) ||
```
Comment (kadircet) [inline clang-tools-extra/clangd/support/Markup.cpp]: nit: drop surrounding parenthesis

**Review by kadircet — APPROVED** [review]
sorry for the delay, thanks!

**Comment by tcottin** [comment]
Thanks for the feedback.
I fixed the findings.
@kadircet could you also merge it then?
