### PR TITLE
[clang-tidy] Fix bugprone-tagged-union-member-count false-positive

### LINKED ISSUE #134840: [clang-tidy] bugprone-tagged-union-member-count false warning when using enum & pthread_mutex_t
Source C file:
```c
#include <pthread.h>

typedef enum {
  MYENUM_ONE,
  MYENUM_TWO,
} myEnumT;

typedef struct {
  pthread_mutex_t mtx;       
  myEnumT         my_enum;
} myTypeT;
```
Using clang-tidy bugprone-tagged-union-member-count:
```
<source>:8:9: warning: tagged union has more data members (3) than tags (2)! [bugprone-tagged-union-member-count]
    8 | typedef struct {
      |         ^
1 warning generated.
```

This is incorrect warning.

clang-tidy vesion: 20.1.1

Issue also reproducible in this link:
https://godbolt.org/z/o3fb9bbrb

### PR DESCRIPTION
**Pull request by tigbr**
This patch implements a fix for the false-positive case described in [issue #134840](https://github.com/llvm/llvm-project/issues/134840) for the [bugprone-tagged-union-member-count](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/tagged-union-member-count.html) clang-tidy check.

The example given in the linked issue was the following:

```C
#include <pthread.h>

typedef enum {
  MYENUM_ONE,
  MYENUM_TWO,
} myEnumT;

typedef struct {
  pthread_mutex_t mtx;       
  myEnumT         my_enum;
} myTypeT;
```

The [bugprone-tagged-union-member-count](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/tagged-union-member-count.html) check emits the following a warning for this struct:

```
<source>:8:9: warning: tagged union has more data members (3) than tags (2)! [bugprone-tagged-union-member-count]
    8 | typedef struct {
      |         ^
1 warning generated.
```

The issue is that `pthread_mutex_t` can be a union behind a typedef like the following:

```C
typedef union
{
  struct __pthread_mutex_s __data;
  char __size[__SIZEOF_PTHREAD_MUTEX_T];
  long int __align;
} pthread_mutex_t;
```

From the checker's point of view therefore `myTypeT` contains a data member with an enum type and another data member with a union type and starts analyzing it like a user-defined tagged union.

The proposed solution is that the types from system headers and the std namespace are no longer candidates to be the enum part or the union part of a user-defined tagged union. This filtering for enums and the std namespace may not be strictly necessary in this example, however I added it preemptively out of (perhaps unnecessary) caution.

Fixes https://github.com/llvm/llvm-project/issues/134840.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/tagged-union-member-count.c [hunk 1]
```diff
@@ -147,3 +147,16 @@ struct Name {\
 
 // CHECK-MESSAGES: :[[@LINE+1]]:44: warning: tagged union has more data members (4) than tags (3)
 DECLARE_TAGGED_UNION_STRUCT(Tags3, Union4, TaggedUnionStructFromMacro);
+
+// Typedefed unions from system header files should be ignored when
+// we are trying to pinpoint the union part in a user-defined tagged union.
+#include "pthread.h"
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/tagged-union-member-count.c:153]: You should include "fake" system header using -i in `// RUN` command.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 2]
```diff
@@ -9,6 +9,9 @@ different from the number of data members inside the union.
 A struct or a class is considered to be a tagged union if it has
 exactly one union data member and exactly one enum data member and
 any number of other data members that are neither unions or enums.
+The union and enum data members that are from system header files or
+the std namespace are not considered to make up the tagged union part
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:13]:
```suggestion
the ``std`` namespace are not considered to make up the tagged union part
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 3]
```diff
@@ -28,6 +31,25 @@ Example:
     } Data;
   };
 
+The following example illustrates the exception for unions and enums from
+system header files and the std namespace.
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:35]:
```suggestion
system header files and the ``std`` namespace.
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 4]
```diff
@@ -28,6 +31,25 @@ Example:
...
+.. code-block:: c++
+
+  #include <pthread.h>
+
+  struct NotTaggedUnion {
+    enum MyEnum { MyEnumConstant1, MyEnumConstant2 } En;
+    pthread_mutex_t Mutex;
+  };
+
+The pthread_mutex_t type may be defined as a union behind a typedef,
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:46]:
```suggestion
The ``pthread_mutex_t`` type may be defined as a union behind a typedef,
```

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 5]
```diff
@@ -28,6 +31,25 @@ Example:
...
+in which case the check could mistake this type as a user-defined tagged union.
+After all it has exactly one enum data member and exactly one union data member.
+To avoid false-positive cases originating from this, unions and enums from
+system headers and the std namespace are ignored when pinpointing the
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:50]:
```suggestion
system headers and the ``std`` namespace are ignored when pinpointing the
```

**Review by vbvictor — COMMENTED** [review]
Please add entry in `ReleaseNotes.rst` file.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst (hunk 2 above)
Comment (EugeneZelenko) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:13]:
```suggestion
the ``std`` namespace are not considered to make up the tagged union part
```

**Comment by EugeneZelenko** [comment]
Please mention changes in Release Notes.

**Comment by vbvictor** [comment]
I'm not sure if we need to check explicitly if some `struct`/`enum` comes from `std` since all `std` namespace is already placed in system headers unless some niece cases like `std::hash<>`. I'm okay leaving it as is, but please then add test with `std` namespace because now only system headers are tested.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 6]
```diff
@@ -28,6 +31,25 @@ Example:
...
+.. code-block:: c++
+
+  #include <pthread.h>
+
+  struct NotTaggedUnion {
+    enum MyEnum { MyEnumConstant1, MyEnumConstant2 } En;
+    pthread_mutex_t Mutex;
+  };
+
+The ``pthread_mutex_t`` type may be defined as a union behind a typedef,
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst:46]:
```suggestion
The ``pthread_mutex_t`` type may be defined as a union behind a ``typedef``,
```

**Review by vbvictor — COMMENTED** [review]
LGMT, with nit.
Please wait for a review from someone with write access who will help merge this PR.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst [hunk 7]
```diff
@@ -9,6 +9,9 @@ different from the number of data members inside the union.
 A struct or a class is considered to be a tagged union if it has
 exactly one union data member and exactly one enum data member and
 any number of other data members that are neither unions or enums.
+The union and enum data members that are from system header files or
+the ``std`` namespace are not considered to make up the tagged union part
+of a user-defined tagged union type.
```
Comment (5chmidti) [inline clang-tools-extra/docs/clang-tidy/checks/bugprone/tagged-union-member-count.rst]: Maybe `Union and enum data members that are from system header files or
the ``std`` namespace are not considered to be the union member or tagging enum member respectively of a user-defined tagged union type.`

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/tagged-union-member-count.c [hunk 8]
```diff
@@ -147,3 +148,16 @@ struct Name {\
 
 // CHECK-MESSAGES: :[[@LINE+1]]:44: warning: tagged union has more data members (4) than tags (3)
 DECLARE_TAGGED_UNION_STRUCT(Tags3, Union4, TaggedUnionStructFromMacro);
+
+// Typedefed unions from system header files should be ignored when
```
Comment (5chmidti) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/tagged-union-member-count.c]: nit: its not just aliases, all unions from system headers are treated like this

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 9]
```diff
@@ -140,6 +140,12 @@ Changes in existing checks
   calls of ``std::string`` constructor with char pointer, start position and
   length parameters.
 
+- Improved :doc:`bugprone-tagged-union-member-count
+  <clang-tidy/checks/bugprone/tagged-union-member-count>` by fixing a false
+  positive when typedefed enums or unions from system header files or the
```
Comment (5chmidti) [inline clang-tools-extra/docs/ReleaseNotes.rst]: not just aliased unions and enums, all unions and enums

**Comment by tigbr** [comment]
Thank you all for the reviews so far. Please let me know if you have any further suggestions.

**Review by 5chmidti — APPROVED** [review]
LGTM

**Comment by tigbr** [comment]
Fixed merge conflict in ReleaseNotes.rst with rebase.

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 10]
```diff
@@ -110,6 +110,19 @@ Changes in existing checks
   <clang-tidy/checks/bugprone/signed-char-misuse>` check by fixing
   false positives on C23 enums with the fixed underlying type of signed char.
 
+- Improved :doc:`bugprone-tagged-union-member-count
+  <clang-tidy/checks/bugprone/tagged-union-member-count>` by fixing a false
+  positive when enums or unions from system header files or the ``std``
+  namespace are treated as the tag or the data part of a user-defined
+  tagged union respectively.
+
+- Improved :doc:`bugprone-unchecked-optional-access
```
Comment (vbvictor) [inline clang-tools-extra/docs/ReleaseNotes.rst:119]: This one I guess is a rebase artifact, need to be deleted

**Comment by vbvictor** [comment]
Could you please make your email public as per https://llvm.org/docs/DeveloperPolicy.html#email-addresses.
I'd merge after that.
