### PR TITLE
[Clang] [Sema] Handle placeholders in '.*' expressions

### LINKED ISSUE #53815: [Clang] ICE in CheckPointerToMemberOperands passing decltype of lambda
This code causes a failed assert on compiler explorer using clang x86-64 assertions trunk

https://godbolt.org/z/q7PYhTcMY
```c++
template <typename Fn>
static bool has_explicitly_named_overload() {
    return requires { Fn().*&Fn::operator(); };
}
int main(){
    has_explicitly_named_overload<decltype([](auto){})>();
}
```
```
clang++: /root/llvm-project/clang/lib/Sema/SemaExprCXX.cpp:5729: clang::QualType clang::Sema::CheckPointerToMemberOperands(clang::ExprResult&, clang::ExprResult&, clang::ExprValueKind&, clang::SourceLocation, bool): Assertion `!LHS.get()->hasPlaceholderType() && !RHS.get()->hasPlaceholderType() && "placeholders should have been weeded out by now"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<eof> parser at end of file
2.	<source>:2:13: instantiating function definition 'has_explicitly_named_overload<(lambda at <source>:6:44)>'
 #0 0x00005623412ac8ef PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005623412aa6f0 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3aaa6f0)
 #2 0x00005623411e0ff8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f11c3c0d3c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f11c36dc18b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
 #5 0x00007f11c36bb859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x25859)
 #6 0x00007f11c36bb729 (/lib/x86_64-linux-gnu/libc.so.6+0x25729)
 #7 0x00007f11c36ccf36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #8 0x000056234367ad2b clang::Sema::CheckPointerToMemberOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::ExprValueKind&, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e7ad2b)
 #9 0x00005623435ceb09 clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dceb09)
#10 0x000056234388ee0c clang::Sema::CreateOverloadedBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::UnresolvedSetImpl const&, clang::Expr*, clang::Expr*, bool, bool, clang::FunctionDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x608ee0c)
#11 0x0000562343587d61 BuildOverloadedBinOp(clang::Sema&, clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) SemaExpr.cpp:0:0
#12 0x00005623435cf857 clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dcf857)
#13 0x0000562343a00cbb clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformBinaryOperator(clang::BinaryOperator*) SemaTemplateInstantiate.cpp:0:0
#14 0x00005623439fdf51 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#15 0x0000562343a20e00 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformRequiresExpr(clang::RequiresExpr*) SemaTemplateInstantiate.cpp:0:0
#16 0x00005623439fe471 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
#17 0x00005623439feb4c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformInitializer(clang::Expr*, bool) (.part.4112) SemaTemplateInstantiate.cpp:0:0
#18 0x00005623439fee8c clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformReturnStmt(clang::ReturnStmt*) SemaTemplateInstantiate.cpp:0:0
#19 0x0000562343a2df6b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#20 0x0000562343a305c3 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x62305c3)
#21 0x0000562343a73b1a clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6273b1a)
#22 0x0000562343a72981 clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6272981)
#23 0x000056234330d34b clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.1495) Sema.cpp:0:0
#24 0x000056234330db4a clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5b0db4a)
#25 0x00005623431fa946 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x59fa946)
#26 0x00005623431f08c9 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x59f08c9)
#27 0x00005623422f0938 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4af0938)
#28 0x0000562341c849f1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44849f1)
#29 0x0000562341c1f42a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x441f42a)
#30 0x0000562341d50ae3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4550ae3)
#31 0x000056233ec08011 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1408011)
#32 0x000056233ec03ea9 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#33 0x0000562341abfad5 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#34 0x00005623411e15e3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39e15e3)
#35 0x0000562341ac1e66 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42c1e66)
#36 0x0000562341a94dca clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4294dca)
#37 0x0000562341a95a5f clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4295a5f)
#38 0x0000562341a9df0a clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x429df0a)
#39 0x000056233eb2c03f main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x132c03f)
#40 0x00007f11c36bd0b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#41 0x000056233ec03a1a _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1403a1a)
clang-15: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by Sirraide**
When analysing whether we should handle a binary expression as an overloaded operator call or a builtin operator, we were calling `checkPlaceholderForOverload()`, which takes care of any placeholders that are not overload sets—which would usually make sense since those need to be handled as part of overload resolution.

Unfortunately, we were also doing that for `.*`, which is not overloadable, and then proceeding to create a builtin operator anyway, which would crash if the RHS happened to be an unresolved overload set (due hitting an assertion in `CreateBuiltinBinOp()`—specifically, in one of its callees—in the `.*` case that makes sure its arguments aren’t placeholders).

This pr instead makes it so we check for *all* placeholders early if the operator is `.*`.

It’s worth noting that,
1. In the `.*` case, we now additionally also check for *any* placeholders (not just non-overload-sets) in the LHS; this shouldn’t make a difference, however—at least I couldn’t think of a way to trigger the assertion with an overload set as the LHS of `.*`; it is worth noting that the assertion in question would also complain if the LHS happened to be of placeholder type, though.
2. There is another case in which we also don’t perform overload resolution—namely `=` if the LHS is not of class or enumeration type after handling non-overload-set placeholders—as in the `.*` case, but similarly to 1., I first couldn’t think of a way of getting this case to crash, and secondly, `CreateBuiltinBinOp()` doesn’t seem to care about placeholders in the LHS or RHS in the `=` case (from what I can tell, it, or rather one of its callees, only checks that the LHS is not a pseudo-object type, but those will have already been handled by the call to `checkPlaceholderForOverload()` by the time we get to this function), so I don’t think this case suffers from the same problem.

This fixes #53815.

### CODE REVIEW

**Comment by Sirraide** [comment]
CC @AaronBallman, @cor3ntin

**Comment by Sirraide** [comment]
One more thing: this code seems to not crash and issue a diagnostic just fine if we simply remove the assertion, so that would also be an option, but I didn’t simply want to remove an assertion without fully knowing why it’s there, so I’ve gone with this as an alternative for now (it should be noted that the code path here is shared with `->*`, which of course is overloadable). 

Alternatively, we could also handle placeholders then and there instead of asserting on them. Thinking about this now, I’m not entirely sure what the best solution would be.

**Comment by Sirraide** [comment]
It seems like the assertion has been in Clang since 2011, and back then, we *were* checking for placeholders in `CreateBuiltinBinOp()`, so at that point it made sense, but this check seems to have been removed since then.

**Comment by Sirraide** [comment]
Yeah, it seems the change that ultimately caused this to break was made in 2011, which moved the handling of placeholders for this code path up into `SemaOverload.cpp`, and from what I can tell, the case of either operand of `.*` potentially being an overload set when `.*` is not overloadable was simply overlooked (i.e. the `assert()` is there because this case *was* being handled before, but this commit removed that):
https://github.com/llvm/llvm-project/commit/526ab47a5573422765ac6c55147dfad00f1d703d#diff-3c28567b5e0c77d68f174541a0b77f5a85d093f58b89cd3675ee04a550a44880L7784-L7800

**Comment by Sirraide** [comment]
In my opinion, we ought to get `.*` ought of the way early—as I’m currently doing in this pr—as it makes little sense to do overloading-specific placeholder handling on an operator that isn’t even overloadable—we should instead just handle all placeholders immediately.

**Comment by Sirraide** [comment]
Lastly, it also seems weird to me that a function called `CreateOverloadedBinOp()` is called to handle `.*`—an operator that can’t be overloaded—but seeing as this function has apparently been handling this case for over a decade now, I’m probably not going to question this any further.

File: clang/lib/Sema/SemaOverload.cpp [hunk 1]
```diff
@@ -14474,6 +14474,23 @@ ExprResult Sema::CreateOverloadedBinOp(SourceLocation OpLoc,
...
   }
 
+  // If this is the .* operator, which is not overloadable, just
+  // create a built-in binary operator.
+  if (Opc == BO_PtrMemD) {
+    auto CheckPlaceholder = [&](Expr *&Arg) {
+      ExprResult Res = CheckPlaceholderExpr(Arg);
+      if (!Res.isInvalid())
+        Arg = Res.get();
+      return Res.isInvalid();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaOverload.cpp:14484]: Do we perhaps want to use `!Res.isUsable()` because `CreateBuiltinBinOp()` expects the `Expr *`s to be nonnull?

**Review by AaronBallman — COMMENTED** [review]
Thank you for the fix! Please be sure to add a release note to `clang/docs/ReleaseNotes.rst` so users know about the fix (and be sure to mention the issue # in the release note).

File: clang/lib/Sema/SemaOverload.cpp (hunk 1 above)
Comment (Sirraide) [reply clang/lib/Sema/SemaOverload.cpp:14484]: I was wondering what the difference between those two was, so thanks for pointing that out. We definitely want that one then.

**Comment by Sirraide** [comment]
> Thank you for the fix! Please be sure to add a release note to `clang/docs/ReleaseNotes.rst` so users know about the fix (and be sure to mention the issue # in the release note).

Ah yes, I keep forgetting about that

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by Sirraide** [comment]
> LGTM!

Thanks. Just so you know, I still don’t have commit access, so you’d have to merge it for me—I should really look into obtaining commit access at this point perhaps

**Comment by ADKaster** [comment]
@AaronBallman @Sirraide would this patch be reasonable to backport to the 18.x release branch? It fixes a problem with our application on the FreeBSD-CURRENT branch. https://github.com/SerenityOS/serenity/issues/23365

**Comment by AaronBallman** [comment]
> @AaronBallman @Sirraide would this patch be reasonable to backport to the 18.x release branch? It fixes a problem with our application on the FreeBSD-CURRENT branch. [SerenityOS/serenity#23365](https://github.com/SerenityOS/serenity/issues/23365)

Yeah, I think the changes are sufficiently safe and small enough that we could consider backporting. We have instructions on how to get that going here: https://www.llvm.org/docs/GitHub.html#backporting-fixes-to-the-release-branches

**Comment by Sirraide** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/d23ef9ef3685eb42ebf719bc28cfe2e4651932fc

**Comment by Sirraide** [comment]
/cherry-pick https://github.com/Sirraide/llvm-project/commit/74fa05dead4d52eef3c33406d05dd1bbaf10d546
