### PR TITLE
[libc++] Fix the mdspan ElementType complete object type mandate

### LINKED ISSUE #191688: [libc++] `std::mdspan<void, ...>` is not rejected
https://eel.is/c++draft/mdspan.mdspan.overview#2.1
> Mandates:
> (2.1) `ElementType` is a complete object type that is neither an abstract class type nor an array type,

`void` is not an object type, so we should diagnose.

```cpp
#include <mdspan>

struct BadAccessor {
  using offset_policy = BadAccessor;
  using element_type = void;
  using reference    = void;
  using data_handle_type = element_type*;
  reference access(data_handle_type, size_t) const;
};

int main() {
  std::mdspan<void, std::dims<2>, std::layout_right, BadAccessor> m;
  m[0, 1]; // not rejected in libstdc++ and libc++
}

```
https://godbolt.org/z/zrqs7nWMd

### PR DESCRIPTION
**Pull request by eiytoq**
Fixes: #191688

### CODE REVIEW

File: libcxx/include/__mdspan/mdspan.h [hunk 1]
```diff
@@ -66,6 +67,9 @@ class mdspan {
 private:
   static_assert(__mdspan_detail::__is_extents_v<_Extents>,
                 "mdspan: Extents template parameter must be a specialization of extents.");
+  static_assert(
```
Comment (hewillk) [inline libcxx/include/__mdspan/mdspan.h:70]: I don't think we want `requires { sizeof(_ElementType); }` here.

`!is_abstract_v<_ElementType>` would already cause a hard error if `_ElementType` is an incomplete type.

Comment (eiytoq) [reply libcxx/include/__mdspan/mdspan.h:70]: According to [[meta.unary.prop](https://eel.is/c++draft/meta.unary.prop#tab:meta.unary.prop)], `is_abstract_v` has a precondition:

>If T is a non-union class type, T shall be a complete type.

So I don't think we can rely on that being a hard error. `requires { sizeof(_ElementType); }` makes sense.

File: libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp [hunk 2]
```diff
@@ -23,6 +23,19 @@ class AbstractClass {
...
 
+struct BadAccessor {
+  using offset_policy    = BadAccessor;
+  using element_type     = void;
+  using reference        = void;
+  using data_handle_type = element_type*;
+  reference access(data_handle_type, std::size_t) const;
+};
+
+int incomplete_type() {
```
Comment (frederick-vs-ja) [inline libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp]: Non-`void` return type doesn't make sense here.
```suggestion
void incomplete_type() {
```

Also, can we also cover rejection of function and reference types? (Maybe in another PR.)

Comment (eiytoq) [reply libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp]: Done, covered those here as well.

File: libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp [hunk 3]
```diff
@@ -23,6 +23,46 @@ class AbstractClass {
   virtual void method() = 0;
 };
 
+struct BadAccessor {
+  using offset_policy    = BadAccessor;
```
Comment (frederick-vs-ja) [inline libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp]: Perhaps we should also test the case for an incomplete class type. Now I think it would make more sense to rename this to `VoidAccessor`.
```suggestion
struct VoidAccessor {
  using offset_policy    = VoidAccessor;
```

Comment (eiytoq) [reply libcxx/test/std/containers/views/mdspan/mdspan/element_type.verify.cpp]: Done.

**Review by frederick-vs-ja — APPROVED** [review]
Thanks for the fix and extensive test coverage!
