### PR TITLE
[clangd] Make EnableFunctionArgSnippets option string-typed

### LINKED ISSUE #2232: Clangd trunk no longer accepts --function-arg-placeholders={false,true}
This is a regression from https://github.com/llvm/llvm-project/commit/18ca7ad3393241b9fc0d5f149247e10837c6f926 (cc @MK-Alias)

The type of the `--function-arg-placeholders` command line argument was changed from `bool` to `int`, to allow the default to be an "unset" value of -1 which allows the value specified using the new `ArgumentLists` config option to take effect.

However, I didn't realize at the time that the the option parser for `bool` is more permissive than the one for `int`: in addition to `0` and `1`, it accepts `true` and `false` (and some [capitalized versions](https://searchfox.org/llvm/rev/56feea7307d8db752f7c98af3a7fa1dd7fc72391/llvm/lib/Support/CommandLine.cpp#409,415) thereof).

That means there are users using a released version of clangd today who have opted to use e.g. `--function-arg-placeholders=false` in their clangd settings, for whom, as things currently stand, clangd will refuse to start when clangd 20 is released and they upgrade to it.

We should do something to avoid this breakage before clangd 20 is released. One idea that comes to mind is to make the option `string` valued so it can accept both the previously accepted values and `-1`.

### PR DESCRIPTION
**Pull request by HighCommander4**
Fixes https://github.com/clangd/clangd/issues/2232

### CODE REVIEW

**Comment by HighCommander4** [comment]
The patch doesn't include a test because the only way I can think of testing this is a clangd lit test and it doesn't seem worth writing one for this, but I could write one if desired.

File: clang-tools-extra/clangd/tool/ClangdMain.cpp [hunk 1]
```diff
@@ -242,13 +242,13 @@ opt<std::string> FallbackStyle{
     init(clang::format::DefaultFallbackStyle),
 };
 
-opt<int> EnableFunctionArgSnippets{
+opt<std::string> EnableFunctionArgSnippets{
```
Comment (hokein) [inline clang-tools-extra/clangd/tool/ClangdMain.cpp:245]: We could also consider the following option, but up to you.
```
enum FunctionArgSnippetsFlag { True, False, None, ... };
opt<FunctionArgSnippetsFlag> EnableFunctionArgSnippets{...
  values(
    clEnumValN(FunctionArgSnippetsFlag::True, "true", ...),
    clEnumValN(FunctionArgSnippetsFlag::True, "True", ...),
    ...
  ),
};
  
```

**Review by hokein — APPROVED** [review]
Not a very related comment, I think we need to add the new `ArgumentLists` config in the clangd config doc https://clangd.llvm.org/config#completion.

File: clang-tools-extra/clangd/tool/ClangdMain.cpp (hunk 1 above)
Comment (HighCommander4) [reply clang-tools-extra/clangd/tool/ClangdMain.cpp:245]: Thanks for the suggestion. I tried this briefly, but I think it makes the `--help` output too noisy because it prints a separate line for each spelling of `"true"`, `"True"`, etc.

**Comment by HighCommander4** [comment]
> I think we need to add the new `ArgumentLists` config in the clangd config doc https://clangd.llvm.org/config#completion.

Definitely. I'll send out a patch documenting this and other options new in clangd 20 in the near future. (We have an entry about this on the [Release checklist](https://github.com/clangd/clangd/wiki/Release-checklist) now, so we don't forget.)
