### PR TITLE
[Clang] Correctly handle allocations in the condition of a `if constexpr`

### LINKED ISSUE #120197: Cannot compare std::string's in if constexpr
This program
```c++
#include <string>

struct A {
    static constexpr std::string name() { return "a"; }  
};

template<class T>
bool f( T && ) {
    if constexpr ( T::name() == "a" )
        return true;
    else
        return false;
}

int main() {
    return f( A{} );
}
```
is accepted by GCC and MSVC, but Clang complains:
```
error: constexpr if condition is not a constant expression
    9 |     if constexpr ( T::name() == "a" )
      |                    ^~~~~~~~~~~~~~~~
```
Online demo: https://gcc.godbolt.org/z/o3nMx3zWj

Original discussion: https://stackoverflow.com/q/79283228/7325599

### LINKED ISSUE #134820: Constexpr allocating temporaries in `if constexpr` are rejected.
Clang fails to compile following while gcc allows it:

https://godbolt.org/z/KcqTdeodx

```cpp
#include <vector>

// ok
static_assert(!std::vector{1,2,3}.empty());

int main() {
    if constexpr(!std::vector{1,2,3}.empty()) {
        return 1;
    }
    return 0;
}
```

Error message:

```
<source>:7:18: error: constexpr if condition is not a constant expression
    7 |     if constexpr(!std::vector{1,2,3}.empty()) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.1/../../../../include/c++/15.0.1/bits/alloc_traits.h:614:20: note: allocation performed here was not deallocated
  614 |       { return __a.allocate(__n); }
      |      
```

The same conditional is allowed in `static_assert` but not in `if constexpr`.

### PR DESCRIPTION
**Pull request by cor3ntin**
Deal with the following scenario

```cpp
struct S {
    char* c = new char;
    constexpr ~S() {
        delete c;
    }
};
if constexpr((S{}, true)){};
```

There were two issues
 - We need to produce a full expression _before_ evaluating the condition (otherwise, automatic variables are never destroyed)
 - We need to preserve the evaluation context of the condition while doing the semantics analysis for it (lest it is evaluated in a non-constant-evaluated context)

Fixes #120197
Fixes #134820

### CODE REVIEW

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 1]
```diff
@@ -1931,15 +1931,13 @@ Parser::ParseCXXCondition(StmtResult *InitStmt, SourceLocation Loc,
...
-    ExprResult Expr = [&] {
-      EnterExpressionEvaluationContext Eval(
-          Actions, Sema::ExpressionEvaluationContext::ConstantEvaluated,
-          /*LambdaContextDecl=*/nullptr,
-          /*ExprContext=*/Sema::ExpressionEvaluationContextRecord::EK_Other,
-          /*ShouldEnter=*/CK == Sema::ConditionKind::ConstexprIf);
-      // Parse the expression.
-      return ParseExpression(); // expression
-    }();
+    EnterExpressionEvaluationContext Eval(
```
Comment (erichkeane) [inline clang/lib/Parse/ParseExprCXX.cpp:1934]: Is the intent to have this eval context apply to the rest of the branch here?  the rest here?  I realize the lambda was a little silly, but it at least limited this to the expression itself?  

I could SWEAR we just touched this less than a month ago...

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -20629,6 +20629,9 @@ Sema::ConditionResult Sema::ActOnCondition(Scope *S, SourceLocation Loc,
 
   case ConditionKind::ConstexprIf:
     Cond = CheckBooleanCondition(Loc, SubExpr, true);
+    assert(isa<FullExpr>(Cond.get()) &&
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp]: `Cond` could still be invalid here, right?  so `.get` would be ill-formed?  Should we be doing some sort of `if (Cond.isUsable())` or something?

Comment (cor3ntin) [reply clang/lib/Sema/SemaExpr.cpp]: Good catch!

File: clang/lib/Parse/ParseExprCXX.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/Parse/ParseExprCXX.cpp:1934]: yes, it needs to survive until `ActOnCondition` (which is wherere we do the actual evaluation)

Comment (erichkeane) [reply clang/lib/Parse/ParseExprCXX.cpp:1934]: Ah, I see!  Though, this covers the `InitStmt`/`ParseCXXCondition` as well.  It isn't 100% clear to me what THAT does here (looks like it is for an init statement?).  I wonder if this doesn't cover that right.  I would imagine the eval context THEN needs to cover the condition after that?

Comment (erichkeane) [reply clang/lib/Parse/ParseExprCXX.cpp:1934]: Oh wait, `ParseCXXCondition` is recursive here, right?  So it WILL cover the ParseCXXCondition on line 1949?

Is it problematic in the init-statement that we would have TWO eval contexts (1 for init + conditon, and 1 for just condition)?

File: clang/lib/Sema/SemaExpr.cpp (hunk 2 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaExpr.cpp]: Actually the assert was incorrect, I removed it

File: clang/lib/Parse/ParseExprCXX.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/Parse/ParseExprCXX.cpp:1934]: No (because they are both constant evaluated and completely nested) - I added tests

File: clang/lib/Sema/SemaExpr.cpp [hunk 3]
```diff
@@ -20643,10 +20641,12 @@ Sema::ConditionResult Sema::ActOnCondition(Scope *S, SourceLocation Loc,
                               {SubExpr}, PreferredConditionType(CK));
     if (!Cond.get())
       return ConditionError();
-  }
-  if (!isa<FullExpr>(Cond.get()))
+  } else if (Cond.isUsable() && !isa<FullExpr>(Cond.get()))
     Cond = ActOnFinishFullExpr(Cond.get(), Loc, /*DiscardedValue*/ false);
 
+  if (Cond.isInvalid())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp]:
```suggestion
  if (!Cond.isUsable())
```
Unless there is a reason that `ConditionResult` would be ok with a 'null' expr?

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Parse/ParseExprCXX.cpp [hunk 4]
```diff
@@ -1931,15 +1931,13 @@ Parser::ParseCXXCondition(StmtResult *InitStmt, SourceLocation Loc,
...
+        Actions, Sema::ExpressionEvaluationContext::ConstantEvaluated,
+        /*LambdaContextDecl=*/nullptr,
+        /*ExprContext=*/Sema::ExpressionEvaluationContextRecord::EK_Other,
+        /*ShouldEnter=*/CK == Sema::ConditionKind::ConstexprIf);
```
Comment (efriedma-quic) [inline clang/lib/Parse/ParseExprCXX.cpp:1938]: Do you need to make an equivalent change to TreeTransform?

I came up with the following testcase:

```
struct S {
    char* c = new char;
    consteval S(){}
    constexpr ~S() {
        delete c;
    }
};
template<typename T> 
int f() {
    if constexpr((T{}, true)) {
        return 1;
    }
    return 0;
}
auto ff = f<S>;
```

Comment (cor3ntin) [reply clang/lib/Parse/ParseExprCXX.cpp:1938]: Indeed, thanks for thinking about that
