### PR TITLE
[Clang] `__attribute__((assume))` refactor

### LINKED ISSUE #71858: clang does not implement `__assume__` attribute, fails libstdc++ build
`gcc` implements `__assume__` attribute as: https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html, quoting the example:

```c
int
foo (int x, int y)
{
  __attribute__((assume(x == 42)));
  __attribute__((assume(++y == 43)));
  return x + y;
}
```

`clang-16` fails to build it as:

```
$ clang -c a.c
a.c:4:18: error: 'assume' attribute cannot be applied to a statement
  __attribute__((assume(x == 42)));
                 ^                ~
a.c:5:18: error: 'assume' attribute cannot be applied to a statement
  __attribute__((assume(++y == 43)));
                 ^                  ~
2 errors generated.
```

Recently `gcc` started using it in `libstdc++` https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=e39b3e02c27bd7 as

```c++
    void
    _M_assume_normalized() const
    {
      unsigned int __ofst = _M_offset;
      __attribute__ ((__assume__ (__ofst < unsigned(_S_word_bit))));
    }
```

and `clang++` now fails to parse `<vector>` from `libstdc++`.

Is there a change `clang` would support this style of `__assume__` attribute or at least skipped it in stead of producing build failure?

### PR DESCRIPTION
**Pull request by Sirraide**
@AaronBallman, @erichkeane This is a followup to #81014 and #84582. For anyone not familiar with what this is about: Clang provides `__attribute__((assume))` and `[[clang::assume]]` as nonstandard spellings for the `[[omp::assume]]` attribute; this results in a potentially very confusing name clash with C++23’s `[[assume]]` attribute. This pr is about deciding what to do about this.

Just to see how much would be affected by this, I’ve gone ahead and removed every last mention of `__attribute__((assume))` and replaced it with `[[omp::assume]]`. Here are a few things I have observed / changes I’ve implemented:
- `[[omp::assume]]` can no longer be spelt `__attribute__((assume))` or `[[clang::assume]]`.
- `__attribute__((assume))` and `[[clang::assume]]` are now alternative spellings for C++23’s `[[assume]]`; this shouldn’t cause any problems due to differences in appertainment: the OMP attribute only appertains to functions, and C++23’s only to empty statements, so any code using `__attribute__((assume))` in that position with Clang would not have compiled anyway. This should also help improve GCC compatibility, as GCC supports `__attribute__((assume))` with the C++23 meaning.
- The OpenMP specification only supports `assume` as an attribute in C++11 and later. However, libclc appears to be using `__attribute__((assume))` internally, specifically, in one header that defines a macro that is then used throughout the codebase. I’m not familiar with libclc or OpenCL, so I’ve added `omp_assume` as an alternative spelling for the OpenMP attribute and replaced the attribute in the header in question with `__attribute__((__omp_assume__))`. 

  If it turns out that using `[[]]`-style attributes in libclc is fine after all, I would suggest using that instead and not providing the `omp_assume` spelling in the first place. It should be noted that, without the `omp_assume` spelling, it would be impossible to use this attribute in C without running into `-pedantic` warnings; we could consider supporting `[[omp::assume]]` in C23, though.
- From what I can tell, no-one except libclc is actually using this attribute? At least on github, the only matches I’ve found for `__attribute__((assume("omp` are in LLVM and various forks thereof. Given that it’s not particularly widely used, I don’t think removal *without* deprecation would be that big of a deal in this case, though if you think that that’s a non-option, then I’d instead suggest deprecating it and removing it in a later version of Clang.

TODO:
- [x] Discuss whether this is what we want to do, or decide on what to do instead.
- [x] Figure out whether we can use `[[omp::assume]]` in libclc.
- [ ] If we decide to support `[[omp::assume]]` in C (or an alternative spelling thereof, in which case we should also update diagnostics that mention `[[omp::assume]]` to display that spelling instead if we’re compiling C, if possible), add some tests for that.
- [x] Update the documentation for `__attribute__((assume))` and C++23’s `[[assume]]`.

### CODE REVIEW

**Comment by Sirraide** [comment]
List of issues that may be fixed by this:
- #71858

**Comment by cor3ntin** [comment]
Have you had a chat with OpenMP folks?

The logic would be that openmp would use something like `[[omp::assume]]` as the non-namespaced attributes are only
supposed to be used by the C & C++ standards and `[[clang::assume]]` is, as  you point out, horribly confusing.
But this would need buy-in from openmp.
`[[clang::omp_assume]]` is _fine_ but we are inventing yet more things out of spec, which is not thrilling.
`[[omp_assume]]` would be fine too, but we should avoid having different spellings in C and C++

And we should be careful about breaks, hence why I prefer a deprecation approach.
We should avoid `[[clang::assume]]` change meaning in the same version.

**Comment by Sirraide** [comment]
> Have you had a chat with OpenMP folks?

@alexey-bataev has been commenting on this matter since the original assume pr, and according to them, `[[omp::assume]]` is the only spelling of the attribute mandated by the OpenMP standard, and we’ve already added that one in #84582. All the other spellings were apparently never really part of OpenMP to begin with.

> The logic would be that openmp would use something like `[[omp::assume]]` as the non-namespaced attributes are only supposed to be used by the C & C++ standards and `[[clang::assume]]` is, as you point out, horribly confusing. But this would need buy-in from openmp. `[[clang::omp_assume]]` is _fine_ but we are inventing yet more things out of spec, which is not thrilling. `[[omp_assume]]` would be fine too, but we should avoid having different spellings in C and C++

I don’t like `omp_assume` either; I’ve only added it because there’s one header in LibCL that uses `__attribute__((assume))`, and I’m candidly just not familiar enough with OpenCL to know whether that can just be replaced with `[[omp::assume]]`; if that’s possible, then I’d definitely not even add `omp_assume` to begin with. It’s is only there as a last resort in case that OpenCL header really can’t do w/o the `__attribute__` spelling—that way I can simply remove it again before we merge this if it turns out that we don’t need it.

> And we should be careful about breaks, hence why I prefer a deprecation approach. We should avoid `[[clang::assume]]` change meaning in the same version.

It wouldn’t really change meaning as there is still a difference in appertainment between the C++ attribute and the OpenMP attribute—unless you mean that it would change from just working to issuing a warning/error when applied to a function, in which case, yeah, we might want to deprecate it first. The only reason I’m considering removal as a possibility is because I don’t think anyone is actually using this spelling, from what I can tell—but of course, there may be users that we’re just not aware of...

**Comment by Sirraide** [comment]
> because there’s one header in LibCL that uses `__attribute__((assume))`

Specifically, [libclc/generic/include/clc/clcfunc.h](https://github.com/llvm/llvm-project/blob/main/libclc/generic/include/clc/clcfunc.h).

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this, it's definitely a complicated situation!

> However, libclc appears to be using __attribute__((assume)) internally, specifically, in one header that defines a macro that is then used throughout the codebase. I’m not familiar with libclc or OpenCL, so I’ve added omp_assume as an alternative spelling for the OpenMP attribute and replaced the attribute in the header in question with __attribute__((__omp_assume__)).

Added @AnastasiaStulova for help with the OpenCL questions. I would love to avoid adding `omp_assume` if possible.

> It should be noted that, without the omp_assume spelling, it would be impossible to use this attribute in C without running into -pedantic warnings; we could consider supporting [[omp::assume]] in C23, though.

My guess is that the OpenMP folks haven't gotten around to rebasing on top of C23 yet and that's really the only thing holding back supporting `[[]]` spellings in C with OpenMP. @alexey-bataev, should we enable OpenMP attribute spellings whenever double square bracket attributes are enabled?

> From what I can tell, no-one except libclc is actually using this attribute? At least on github, the only matches I’ve found for __attribute__((assume("omp are in LLVM and various forks thereof. Given that it’s not particularly widely used, I don’t think removal without deprecation would be that big of a deal in this case, though if you think that that’s a non-option, then I’d instead suggest deprecating it and removing it in a later version of Clang.

This matches my searching around on https://sourcegraph.com/search?q=context:global+__attribute__%28%28assume%28%22omp+-file:.*test.*+-file:.*llvm.*+-file:.*%5C.rst&patternType=keyword&sm=0 so I think removal without deprecation may be reasonable unless @alexey-bataev knows of something we're missing.

**Comment by Sirraide** [comment]
> Added @AnastasiaStulova for help with the OpenCL questions. I would love to avoid adding `omp_assume` if possible.

Thanks, I didn’t know who to ping about that, and yeah, same.

**Comment by alexey-bataev** [comment]
> Thank you for working on this, it's definitely a complicated situation!
> 
> > However, libclc appears to be using **attribute**((assume)) internally, specifically, in one header that defines a macro that is then used throughout the codebase. I’m not familiar with libclc or OpenCL, so I’ve added omp_assume as an alternative spelling for the OpenMP attribute and replaced the attribute in the header in question with **attribute**((**omp_assume**)).
> 
> Added @AnastasiaStulova for help with the OpenCL questions. I would love to avoid adding `omp_assume` if possible.
> 
> > It should be noted that, without the omp_assume spelling, it would be impossible to use this attribute in C without running into -pedantic warnings; we could consider supporting [[omp::assume]] in C23, though.
> 
> My guess is that the OpenMP folks haven't gotten around to rebasing on top of C23 yet and that's really the only thing holding back supporting `[[]]` spellings in C with OpenMP. @alexey-bataev, should we enable OpenMP attribute spellings whenever double square bracket attributes are enabled?
> 
> > From what I can tell, no-one except libclc is actually using this attribute? At least on github, the only matches I’ve found for **attribute**((assume("omp are in LLVM and various forks thereof. Given that it’s not particularly widely used, I don’t think removal without deprecation would be that big of a deal in this case, though if you think that that’s a non-option, then I’d instead suggest deprecating it and removing it in a later version of Clang.
> 
> This matches my searching around on https://sourcegraph.com/search?q=context:global+__attribute__%28%28assume%28%22omp+-file:.*test.*+-file:.*llvm.*+-file:.*%5C.rst&patternType=keyword&sm=0 so I think removal without deprecation may be reasonable unless @alexey-bataev knows of something we're missing.

Idon'think there are any. @jdoerfert thoughts?

**Comment by erichkeane** [comment]
OpenCL is "C" based, not C++.  However, C23 DID add namespacing to attributes, so if OpenCL can use C23, we should be able to make the spelling `[[omp::assume]]`.  That said, I DO see value for an `__attribute__` spelling, so I think `omp_assume` is probably an unfortunate necessity.

File: clang/test/Sema/attr-assume.c [hunk 1]
```diff
@@ -1,14 +0,0 @@
-// RUN: %clang_cc1 -triple i386-apple-darwin9 -fsyntax-only -verify %s
```
Comment (erichkeane) [inline clang/test/Sema/attr-assume.c:1]: Same here, can we just rename this to attr-omp-assume.c and change the name in the test?

File: clang/test/CodeGen/assume_attr.c [hunk 2]
```diff
@@ -1,58 +0,0 @@
-// RUN: %clang_cc1 -emit-llvm -triple i386-linux-gnu %s -o - | FileCheck %s
```
Comment (erichkeane) [inline clang/test/CodeGen/assume_attr.c:1]: would be great if we could just rename/update this test rather than deleting it?

**Comment by jdoerfert** [comment]
FWIW, for OpenMP we only need to support the [[]] spelling in C++. The fact we had everything else was a side-effect of the implementation, IIRC. 
Thus, this should be fine for OpenMP.

File: clang/test/CodeGen/assume_attr.c (hunk 2 above)
Comment (Sirraide) [reply clang/test/CodeGen/assume_attr.c:1]: The main reason I outright deleted it is because I’m hoping we won’t be needing the `__attribute__((omp_assume))` spelling, in which case these test cases become pointless since we’re already testing all of this w/ the `[[omp::assume]]` spelling; that said, if it turns out that we *do* need `omp_assume`, then I’ll add these back with that spelling instead.

**Comment by Sirraide** [comment]
> OpenCL is "C" based, not C++. However, C23 DID add namespacing to attributes, so if OpenCL can use C23, we should be able to make the spelling `[[omp::assume]]`. That said, I DO see value for an `__attribute__` spelling, so I think `omp_assume` is probably an unfortunate necessity.

One thing to note perhaps is that, since an `omp_assume` attribute would basically just be Clang extension, and seeing as we *do* support `[[]]` in language modes before C23 as an extension—can’t we just, to put it bluntly, expect people to use `[[omp::assume]]` in C irrespective of whether they enable C23? 

Afaik, this would only cause issues because of `-pedantic` warnings—but those only exist for portability, and there isn’t any portability to be had here in the first place since it’s a Clang extension anyway. In other words, seeing as you’d only be able to use `omp_assume` with Clang anyway if we do decide to add it, you might as well just use the `[[omp::assume]]` spelling at that point.

**Comment by Sirraide** [comment]
Moreover, the current ‘C version’ of this attribute already isn’t portable, because it’s currently spelt `assume`, which means something entirely different if you’re compiling w/ GCC.

**Comment by erichkeane** [comment]
> Moreover, the current ‘C version’ of this attribute already isn’t portable, because it’s currently spelt `assume`, which means something entirely different if you’re compiling w/ GCC.

I doubt we'd want to have folks use the C23 spelling in earlier modes as a suggestion: they aren't 'ignorable' in previous modes for GCC or MSVC (whereas the `__attribute__` and `__declspec` spellings ARE for the respective compiler).  So I think if OpenCL has a use for this attribute, we should provide a spelling for it .

Also, `assume` doesn't mean anything in C for GCC yet, right?

**Comment by Sirraide** [comment]
> Also, `assume` doesn't mean anything in C for GCC yet, right?

`__attribute__((assume))` in GCC seems to have the same meaning as C++23’s `[[assume]]`, irrespective of   language: https://godbolt.org/z/r79oPWxEW

**Comment by AaronBallman** [comment]
> > FWIW, for OpenMP we only need to support the [[]] spelling in C++. The fact we had everything else was a side-effect of the implementation, IIRC. Thus, this should be fine for OpenMP.
> 
> That is more or less what I’ve been able to gather so far as well. I suppose we’ll have to wait and see what the OpenCL people have to say about this.

CC @AnastasiaStulova

**Comment by Sirraide** [comment]
@AnastasiaStulova ping

**Comment by svenvh** [comment]
The libclc usage seems to have been added by @rjodinchr in https://reviews.llvm.org/D147773 (and approved by @alan-baker).  Perhaps they have an opinion?

**Comment by rjodinchr** [comment]
> The libclc usage seems to have been added by @rjodinchr in https://reviews.llvm.org/D147773 (and approved by @alan-baker). Perhaps they have an opinion?

https://github.com/google/clspv uses the assume attribute. The goal is to be able to put a mark on libclc functions to have a specific lowering in `clspv`.
I'm not against removing the attribute, but we will have to find another way to do that for `clspv`. Do you know something we could use to get rid of the assume attribute?

**Comment by Sirraide** [comment]
> I'm not against removing the attribute, but we will have to find another way to do that for clspv. Do you know something we could use to get rid of the assume attribute?

An attribute does make sense for that imo; the problem is that `assume` is really not an ideal name for an attribute... Would it be possible to use the C++11/C23 attribute syntax using `[[]]`? That would solve the problem because we could use the `[[omp::assume]]` spelling. 

Alternatively, if any attribute would work, we could introduce a separate one to make it clear that it’s intended for libclc, becuase your use case sounds like it doesn’t have anything to do with OpenMP, but maybe I’m misunderstanding something here. Also, maybe @AaronBallman has another idea as to what we could do here.

**Comment by rjodinchr** [comment]
It has nothing to do with OpenMP.
The goal was just to get something in the llvm IR that we could check for. The `assume` attribute allows us to pass a string that we can then check in a llvm pass.

**Comment by erichkeane** [comment]
> It has nothing to do with OpenMP. The goal was just to get something in the llvm IR that we could check for. The `assume` attribute allows us to pass a string that we can then check in a llvm pass.

Could you investigate whether 'annotate' would do what you want?  IIRC, the point of it is to just pass a string onto the AST/IR.

**Comment by rjodinchr** [comment]
> > It has nothing to do with OpenMP. The goal was just to get something in the llvm IR that we could check for. The `assume` attribute allows us to pass a string that we can then check in a llvm pass.
> 
> Could you investigate whether 'annotate' would do what you want? IIRC, the point of it is to just pass a string onto the AST/IR.

At the moment, I did not manage to have annotation working. It's because annotation is an indirect link to the function. Thus it does not stick around when I link modules.

Maybe the easiest way would be to add a real attribute for clspv?

**Comment by Sirraide** [comment]
> Maybe the easiest way would be to add a real attribute for clspv?

What exactly would the requirements for such an attribute be? Does it need to take a parameter or do you only need one way of tagging functions? Asking because I can go ahead add one as part of this pr if that’s the easiest solution so we can clean up this `assume` situation. That also means we wouldn’t need an `omp_assume` spelling for the `assume` attribute. 

On that note, what name would you recommend for such an attribute? Probably `cl_something` or `clspv_something`, but I’m not sure what that `something` would be.

**Comment by rjodinchr** [comment]
It is only to tag functions. I guess the name would be `clspv_libclc_builtin` (https://github.com/llvm/llvm-project/blob/main/libclc/generic/include/clc/clcfunc.h#L11).

I've started to test with such a solution to make sure everything works on clspv side, but I need more time.

**Comment by rjodinchr** [comment]
This is the first time I'm trying to add an attribute, and I think I am missing something.
I am adding this part in `Attr.td`:
```
def ClspvLibclcBuiltin: DeclOrStmtAttr {
  let Spellings = [Clang<"clspv_libclc_builtin">];
  let Documentation = [Undocumented];
  let SimpleHandler = 1;
}
```
It allows the source to be parsed, but then I don't see the attribute in the LLVM IR generated for libclc.

**Comment by svenvh** [comment]
> It allows the source to be parsed, but then I don't see the attribute in the LLVM IR generated for libclc.

You will need to also convert the attribute into an LLVM IR construct (e.g. metadata) in Clang CodeGen.  See `CodeGenFunction::EmitKernelMetadata` for inspiration for example.

**Comment by rjodinchr** [comment]
Alright with those changes, everything should be fine for `clspv`:
```
diff --git a/clang/include/clang/Basic/Attr.td b/clang/include/clang/Basic/Attr.td
index dc87a8c6f022..056f22b56001 100644
--- a/clang/include/clang/Basic/Attr.td
+++ b/clang/include/clang/Basic/Attr.td
@@ -4506,3 +4506,9 @@ def CodeAlign: StmtAttr {
     static constexpr int MaximumAlignment = 4096;
   }];
 }
+
+def ClspvLibclcBuiltin: DeclOrStmtAttr {
+  let Spellings = [Clang<"clspv_libclc_builtin">];
+  let Documentation = [Undocumented];
+  let SimpleHandler = 1;
+}
diff --git a/clang/lib/CodeGen/CodeGenFunction.cpp b/clang/lib/CodeGen/CodeGenFunction.cpp
index 86a6ddd80cc1..b0e3b96cd59d 100644
--- a/clang/lib/CodeGen/CodeGenFunction.cpp
+++ b/clang/lib/CodeGen/CodeGenFunction.cpp
@@ -973,6 +973,11 @@ void CodeGenFunction::StartFunction(GlobalDecl GD, QualType RetTy,
     EmitKernelMetadata(FD, Fn);
   }

+  if (FD && FD->hasAttr<ClspvLibclcBuiltinAttr>()) {
+    Fn->setMetadata("clspv_libclc_builtin",
+                    llvm::MDNode::get(getLLVMContext(), {}));
+  }
+
   // If we are checking function types, emit a function type signature as
   // prologue data.
   if (FD && SanOpts.has(SanitizerKind::Function)) {
diff --git a/libclc/generic/include/clc/clcfunc.h b/libclc/generic/include/clc/clcfunc.h
index ad9eb23f2933..59f45c27019d 100644
--- a/libclc/generic/include/clc/clcfunc.h
+++ b/libclc/generic/include/clc/clcfunc.h
@@ -8,7 +8,7 @@
 #define _CLC_DEF
 #elif defined(CLC_CLSPV) || defined(CLC_CLSPV64)
 #define _CLC_DEF                                                               \
-  __attribute__((noinline)) __attribute__((assume("clspv_libclc_builtin")))
+  __attribute__((noinline)) __attribute__((clspv_libclc_builtin))
 #else
 #define _CLC_DEF __attribute__((always_inline))
 #endif
 ```
 @Sirraide, would you add those (or similar if you feel that changes are needed) directly to that PR?

**Comment by Sirraide** [comment]
> @Sirraide, would you add those (or similar if you feel that changes are needed) directly to that PR?

Yeah, that looks reasonable. If this works for clspv, then I’ll integrate these changes into this pr.

That means I can remove the `omp_assume` spelling for `[[omp::assume]]` that this pr was going to add as a temporary measure, because that’s not going to be needed anymore.

**Comment by erichkeane** [comment]
> > @Sirraide, would you add those (or similar if you feel that changes are needed) directly to that PR?
> 
> Yeah, that looks reasonable. If this works for clspv, then I’ll integrate these changes into this pr.
> 
> That means I can remove the `omp_assume` spelling for `[[omp::assume]]` that this pr was going to add as a temporary measure, because that’s not going to be needed anymore.

Thats fantastic!

However, I'd suggest instead adding the clspv attribute in a separate review/commit.  It isn't really related to this one, other than this has a slight dependency on it.

**Comment by erichkeane** [comment]
> > However, I'd suggest instead adding the clspv attribute in a separate review/commit. It isn't really related to this one, other than this has a slight dependency on it.
> 
> I could add that in a separate pr; that means that one will have to be merged before this one because we have to replace that one use of `assume` in the clcfunc.h header with the new attribute either before or at the same time as we remove the `assume` spelling.

Yep, understood.  I'll do my best to do quick review cycles on the other patch.

**Comment by Sirraide** [comment]
> Yep, understood. I'll do my best to do quick review cycles on the other patch.

Alright, I’ll do that then; as I said though, I’m a bit busy, so I’ll probably only get to this sometime next week unfortunately...

**Comment by erichkeane** [comment]
> > Yep, understood. I'll do my best to do quick review cycles on the other patch.
> 
> Alright, I’ll do that then; as I said though, I’m a bit busy, so I’ll probably only get to this sometime next week unfortunately...

Note @rjodinchr has offered to do the PR for that one, so hopefully he and I will be able to cycle on it and get it committed before you could update this anyway.

**Comment by rjodinchr** [comment]
Here is the PR ready for review: https://github.com/llvm/llvm-project/pull/92126

**Comment by Sirraide** [comment]
Ok, I’ve removed the `omp_assume` spelling; `[[omp::assume]]` is now the only way to spell this attribute.

**Review by erichkeane — APPROVED** [review]

**Comment by Sirraide** [comment]
One last thing: the GNU `__attribute__((assume))` spelling is no longer diagnosed as a C++23 extension, but from what I can tell, this pr is finally done now.

**Comment by Sirraide** [comment]
Ok, the only CI failure is apparently `CoverageMapping/mcdc-system-headers.cpp`, which seems unrelated.

**Comment by Sirraide** [comment]
> the GNU __attribute__((assume)) spelling is no longer diagnosed as a C++23 extension, but from what I can tell, this pr is finally done now.

@erichkeane @AaronBallman Just wanted to double-check whether this is fine because I committed this change after this pr was approved.

**Comment by erichkeane** [comment]
> > the GNU `__attribute__((assume))` spelling is no longer diagnosed as a C++23 extension
> 
> @erichkeane @AaronBallman Just wanted to double-check whether this is fine because I committed this change after this pr was approved.

Yep, that makes sense to me.  Still LGTM.
