### PR TITLE
[Clang][Sema] Fix missing warning when comparing mismatched enums in …

### LINKED ISSUE #29217: -Wenum-compare doesn't catch mismatched enum constant comparison in C mode
|  |  |
| --- | --- |
| Bugzilla Link | [28847](https://llvm.org/bz28847) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mmdriley |

## Extended Description 
Consider this program (test.c)

enum foo_t {
    foo1, foo2, foo3
};

enum bar_t {
    bar1, bar2, bar3
};

int main(void) {
    enum foo_t foo = foo1;
    enum bar_t bar = bar1;

    int cmp1 = foo < bar; // variable - variable
    int cmp2 = foo < bar2; // variable - constant
    int cmp3 = foo1 < bar3; // constant - constant

    return cmp1 || cmp2 || cmp3;
}

If I compile this as C code, I only get a warning for the first comparison. If I compile in C++ mode, I get a warning for all three.

$ clang -Wall test.c
test.c:13:20: warning: comparison of two values with different enumeration types
      ('enum foo_t' and 'enum bar_t') [-Wenum-compare]
    int cmp1 = foo < bar;
               ~~~ ^ ~~~
1 warning generated.
$ clang -Wall -x c++ test.c
test.c:13:20: warning: comparison of two values with different enumeration types
      ('enum foo_t' and 'enum bar_t') [-Wenum-compare]
    int cmp1 = foo < bar;
               ~~~ ^ ~~~
test.c:14:20: warning: comparison of two values with different enumeration types
      ('enum foo_t' and 'bar_t') [-Wenum-compare]
    int cmp2 = foo < bar2;
               ~~~ ^ ~~~~
test.c:15:21: warning: comparison of two values with different enumeration types ('foo_t' and 'bar_t')
      [-Wenum-compare]
    int cmp3 = foo1 < bar3;
               ~~~~ ^ ~~~~
3 warnings generated.


I think the warnings should be emitted in C mode too. Tested with gcc 4.9.2 and 3 warnings are emitted for C code:

$ gcc -Wall test.c
test.c: In function 'main':
test.c:13:20: warning: comparison between 'enum foo_t' and 'enum bar_t' [-Wenum-compare]
     int cmp1 = foo < bar;
                    ^
test.c:14:20: warning: comparison between 'enum foo_t' and 'enum bar_t' [-Wenum-compare]
     int cmp2 = foo < bar2;
                    ^
test.c:15:21: warning: comparison between 'enum foo_t' and 'enum bar_t' [-Wenum-compare]
     int cmp3 = foo1 < bar3;
                     ^

### PR DESCRIPTION
**Pull request by martinkupa**
…C mode

Factored logic from `CheckImplicitConversion` into new methods `Expr::getEnumConstantDecl` and `Expr::getEnumCoercedType` for use in `checkEnumArithmeticConversions`.

Fix #29217

### CODE REVIEW

**Comment by Kupa-Martin** [comment]
ping

File: clang/lib/AST/Expr.cpp [hunk 1]
```diff
@@ -263,6 +263,14 @@ namespace {
   }
 }
 
+QualType Expr::getEnumCoercedType(const ASTContext &Ctx) const {
+  bool NotEnumType = dyn_cast<EnumType>(this->getType()) == nullptr;
+  if (NotEnumType)
```
Comment (erichkeane) [inline clang/lib/AST/Expr.cpp:268]:
```suggestion
  if (!isa<EnumType>(this->getType()))
```

Though, would probably suggest just something like:
```
if (isa<EnumType>(getType())) return getType();

else if (const EnumConstantDecl *ECD = getEnumConstantDecl())
  return Ctx.getTypeDeclType...
return getType();

```

File: clang/lib/AST/Expr.cpp [hunk 2]
```diff
@@ -4097,6 +4105,14 @@ FieldDecl *Expr::getSourceBitField() {
   return nullptr;
 }
 
+EnumConstantDecl *Expr::getEnumConstantDecl() {
+  Expr *E = this->IgnoreParenImpCasts();
+  if (DeclRefExpr *DRE = dyn_cast<DeclRefExpr>(E))
+    if (EnumConstantDecl *ECD = dyn_cast<EnumConstantDecl>(DRE->getDecl()))
```
Comment (erichkeane) [inline clang/lib/AST/Expr.cpp:4111]:
```suggestion
    return dyn_cast<EnumConstantDecl>(DRE->getDecl());
```

**Review by erichkeane — COMMENTED** [review]
Not the best one to review this, but some drive-bys

File: clang/test/Sema/warn-compare-enum-types-mismatch.c [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+  a < B;
+  // expected-warning@-1 {{comparison of different enumeration types}}
+  a < b;
+  // expected-warning@-1 {{comparison of different enumeration types}}
+
+  // In the following cases we purposefully differ from GCC and dont warn 
+  a == C; 
+  A < C;
+  b >= C; 
+}
```
Comment (shafik) [inline clang/test/Sema/warn-compare-enum-types-mismatch.c:42]: Please add a newline at the end of the file

File: clang/lib/AST/Expr.cpp (hunk 1 above)
Comment (shafik) [inline clang/lib/AST/Expr.cpp:268]: This look redundant since `getEnumConstantDecl()` will just return `nullptr`

Comment (Kupa-Martin) [reply clang/lib/AST/Expr.cpp:268]: In C mode enumeration constants have integral type, so `getEnumConstantDecl()` might not return `nullptr` even if the expression doesnt have enum type.

File: clang/test/Sema/warn-compare-enum-types-mismatch.c (hunk 3 above)
Comment (Kupa-Martin) [reply clang/test/Sema/warn-compare-enum-types-mismatch.c]: done

File: clang/lib/AST/Expr.cpp (hunk 1 above)
Comment (Kupa-Martin) [reply clang/lib/AST/Expr.cpp]: done

File: clang/lib/AST/Expr.cpp [hunk 4]
```diff
@@ -263,6 +263,14 @@ namespace {
   }
 }
 
+QualType Expr::getEnumCoercedType(const ASTContext &Ctx) const {
+  if (isa<EnumType>(this->getType()))
+    return this->getType();
+  else if (const EnumConstantDecl *ECD = this->getEnumConstantDecl())
```
Comment (erichkeane) [inline clang/lib/AST/Expr.cpp:269]:
```suggestion
  else if (const auto *ECD = this->getEnumConstantDecl())
```

File: clang/lib/AST/Expr.cpp [hunk 5]
```diff
@@ -4097,6 +4105,13 @@ FieldDecl *Expr::getSourceBitField() {
   return nullptr;
 }
 
+EnumConstantDecl *Expr::getEnumConstantDecl() {
+  Expr *E = this->IgnoreParenImpCasts();
+  if (DeclRefExpr *DRE = dyn_cast<DeclRefExpr>(E))
```
Comment (erichkeane) [inline clang/lib/AST/Expr.cpp:4110]:
```suggestion
  if (auto *DRE = dyn_cast<DeclRefExpr>(E))
```

**Review by erichkeane — COMMENTED** [review]
A couple more coding standard edits, else LGTM.

File: clang/lib/AST/Expr.cpp (hunk 4 above)
Comment (Kupa-Martin) [reply clang/lib/AST/Expr.cpp]: done

**Comment by Kupa-Martin** [comment]
If everything looks good could someone please merge this pr? I dont have commit access.

**Review by erichkeane — APPROVED** [review]

**Comment by nathanchance** [comment]
For what it's worth, this change adds several instances of `-Wenum-enum-conversion` for the Linux kernel: https://github.com/ClangBuiltLinux/linux/issues/2002. I assume this is intentional given the nature of the change as a whole but neither the tests nor the release notes seem to really reflect that. In case it is a bug that this change affected that, consider this a report :)

**Comment by stbergmann** [comment]
This change started to break the following C++26 code:
```
$ cat test.cc
enum E1 { E11 };
enum E2 {
    E21 = E11,
    E22 = 1,
    E23 = E21 + E22
};
```
```
clang++ -std=c++26 -fsyntax-only test.cc
test.cc:5:15: error: invalid arithmetic between different enumeration types ('E1' and 'E2')
    5 |     E23 = E21 + E22
      |           ~~~ ^ ~~~
1 error generated.
```
as within the definition of enum `E2` with unfixed underlying type, while the type of `E21` is indeed `E1`, the type of `E22` there is `int` rather than `E2` (see [dcl.enum]/5.1 "If an initializer is specified for an enumerator, the constant-expression shall be an integral constant expression (7.7). If the expression has unscoped enumeration type, the enumerator has the underlying type of that enumeration type, otherwise it has the same type as the expression.")

**Comment by Kupa-Martin** [comment]
@stbergmann is right. @erichkeane How should I proceed? Should I open a revert PR? Or should I open a separate issue?

**Comment by erichkeane** [comment]
> @stbergmann is right. @erichkeane How should I proceed? Should I open a revert PR? Or should I open a separate issue?

For now, unless someone insists, I think we're likely fine to do a follow-up PR to fix that.  Make sure to put the same reviewers on, and we'll see if we can review this quickly.
