### PR TITLE
[clang] Warn about deprecated volatile-qualified return types

### LINKED ISSUE #133380: Clang fails to warn about deprecated volatile-qualified return type
Code :

```cpp
volatile struct amber jurassic();  // Should warn (deprecated) — Clang misses this
void trex(volatile short left_arm, volatile short right_arm);  // Clang warns (correct)
void fly(volatile struct pterosaur* pteranodon);  // OK (no warning expected)
```

Expected Behavior:
Clang should emit a deprecation warning (-Wvolatile or similar) for the volatile return type in jurassic(), just as GCC does

Actual Behavior:
Clang only warns about volatile parameters (e.g., trex) but silently accepts the deprecated volatile return type.

https://godbolt.org/z/ajs7n8P7h

### PR DESCRIPTION
**Pull request by halbi2**
The old codepath in GetFullTypeForDeclarator was under "if (not a class type)"
so that it failed to warn for class types. Move the diagnostic outside of the
"if" so that it warns in the proper situations.

Fixes #133380

### CODE REVIEW

File: clang/lib/Sema/SemaType.cpp [hunk 1]
```diff
@@ -5056,13 +5056,13 @@ static TypeSourceInfo *GetFullTypeForDeclarator(TypeProcessingState &state,
...
-        // C++2a [dcl.fct]p12:
-        //   A volatile-qualified return type is deprecated
-        if (T.isVolatileQualified() && S.getLangOpts().CPlusPlus20)
-          S.Diag(DeclType.Loc, diag::warn_deprecated_volatile_return) << T;
       }
 
+      // C++2a [dcl.fct]p12:
+      //   A volatile-qualified return type is deprecated
+      if (T.isVolatileQualified() && S.getLangOpts().CPlusPlus20)
+        S.Diag(DeclType.Loc, diag::warn_deprecated_volatile_return) << T;
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaType.cpp:5064]: I see there is another place that issues `warn_deprecated_volatile_return` in `Sema::CheckFunctionReturnType`. I wonder why doesn't it suffice?

File: clang/test/SemaCXX/deprecated.cpp [hunk 2]
```diff
@@ -231,6 +231,13 @@ namespace DeprecatedVolatile {
     a = c = a;
     b += a;
   }
+
+  volatile struct amber jurassic();
```
Comment (Fznamznon) [inline clang/test/SemaCXX/deprecated.cpp:235]: As I can see, if the return type is not a struct/class, the warning is issued. Could you please add a test case with volatile qualifier applied to a basic type (for example int) and make sure there is no double diagnostic issued now?

**Review by Fznamznon — COMMENTED** [review]
Thank you for the fix, could you please also add a release note?

**Review by shafik — COMMENTED** [review]
Can you add more details in the summary. Specifically your approach to fixing the issue.

Something along the lines of "In GetFullTypeForDeclarator ... moved check ... b/c ..."

File: clang/lib/Sema/SemaType.cpp (hunk 1 above)
Comment (halbi2) [reply clang/lib/Sema/SemaType.cpp:5064]: I understand that `CheckFunctionReturnType` is used when checking the type of a function like `using T = volatile int();` but this codepath here is used when checking a function declaration instead.

File: clang/test/SemaCXX/deprecated.cpp (hunk 2 above)
Comment (halbi2) [reply clang/test/SemaCXX/deprecated.cpp:235]: Lines 207-215 are that, are they not?

**Comment by halbi2** [comment]
@shafik I have changed the commit message, can you please look again?

File: clang/lib/Sema/SemaType.cpp (hunk 1 above)
Comment (Fznamznon) [reply clang/lib/Sema/SemaType.cpp:5064]: ok, thanks for clarifying

File: clang/test/SemaCXX/deprecated.cpp (hunk 2 above)
Comment (Fznamznon) [reply clang/test/SemaCXX/deprecated.cpp:235]: Yeah, these are what I meant. Thanks!

**Review by Fznamznon — APPROVED** [review]
That looks good to me unless @shafik has any additional concerns.

**Comment by shafik** [comment]
> @shafik I have changed the commit message, can you please look again?

I see the commit [238d737](https://github.com/llvm/llvm-project/pull/137899/commits/238d73776c85ed22386ac494f275261638cd40d3) which adds the improved summary but I don't see at the top of this page in the summary. As long as this is what ends up as the commit message that is fine but it is better to just edit the summary at the top of the page so the reviewers can see it up front. Thank you!

**Review by shafik — APPROVED** [review]

**Comment by cor3ntin** [comment]
@halbi2 Do you need us to merge that for you?

**Comment by halbi2** [comment]
@cor3ntin yes, please.
