### PR TITLE
[clang] Fix a possible out-of-bounds read

### LINKED ISSUE #79964: clang/lib/Frontend/TextDiagnostic.cpp:1254: suspicious loop ?
Static analyser cppcheck says:

clang/lib/Frontend/TextDiagnostic.cpp:1254:40: error: When I==Spelling.size(), Spelling[I] is out of bounds. [stlOutOfBounds]

Source code is

    for (unsigned I = 0; I <= Spelling.size(); ++I) {
      // This line is done.
      if (isVerticalWhitespace(Spelling[I]) || I == Spelling.size()) {

The for loop line looks like it executes once too many times. Maybe better code

    for (unsigned I = 0; I < Spelling.size(); ++I) {

### PR DESCRIPTION
**Pull request by tbaederr**
Switch to using `std::string::at()` since that seems to assert the given index is in range (when such assertions are enabled).

Fixes #79964

### CODE REVIEW

File: clang/lib/AST/Interp/ByteCodeExprGen.h [hunk 1]
```diff
@@ -109,6 +109,7 @@ class ByteCodeExprGen : public ConstStmtVisitor<ByteCodeExprGen<Emitter>, bool>,
   bool VisitCXXScalarValueInitExpr(const CXXScalarValueInitExpr *E);
   bool VisitSizeOfPackExpr(const SizeOfPackExpr *E);
   bool VisitGenericSelectionExpr(const GenericSelectionExpr *E);
+  bool VisitChooseExpr(const ChooseExpr *E);
```
Comment (Endilll) [inline clang/lib/AST/Interp/ByteCodeExprGen.h:112]: Is this change relevant to the fix?

Comment (tbaederr) [reply clang/lib/AST/Interp/ByteCodeExprGen.h:112]: No, my bad. rebase problems

**Review by Endilll — APPROVED** [review]

File: clang/lib/Frontend/TextDiagnostic.cpp [hunk 2]
```diff
@@ -1251,7 +1251,7 @@ highlightLines(StringRef FileData, unsigned StartLineNumber,
     unsigned LineLength = 0;
     for (unsigned I = 0; I <= Spelling.size(); ++I) {
       // This line is done.
-      if (isVerticalWhitespace(Spelling[I]) || I == Spelling.size()) {
+      if (I == Spelling.size() || isVerticalWhitespace(Spelling.at(I))) {
```
Comment (cor3ntin) [inline clang/lib/Frontend/TextDiagnostic.cpp:1254]: The bug was the order of the instruction,  the `at` is not doing anything useful here here. checking the size first should be necessary and sufficient.

The interesting question is why that wasn't caught by tools?
We have a repro? ( I don't insist on having one to land that though)

Comment (tbaederr) [reply clang/lib/Frontend/TextDiagnostic.cpp:1254]: Well it would've been caught earlier if it had been using `at()` in the first place.

> We have a repro? ( I don't insist on having one to land that though)

Even though I have assertions and sanitizers (but not msan) enabled locally, the `Spelling[I]` did not crash for me or cause anything else in the `I == Spelling.size()` case.

Comment (cor3ntin) [reply clang/lib/Frontend/TextDiagnostic.cpp:1254]: I won't insist but I'd rather remove the at.
It occurs to me that between the lack of warnings, and the fact that unit tests probably have color disabled, this won't be easy to test.... oh well

**Review by cor3ntin — APPROVED** [review]
