### PR TITLE
[SelectionDAG] use HandleSDNode instead of SDValue during SelectInlineAsmMemoryOperands

### LINKED ISSUE #82431: [18 regression] [x86_64] SDValue llvm::SelectionDAG::getNode(unsigned int, const SDLoc &, SDVTList, ArrayRef<SDValue>, const SDNodeFlags): Assertion `Op.getOpcode() != ISD::DELETED_NODE && "Operand is DELETED_NODE!"' failed.
When building the reduced test case in this bug report with AMD specific optimizations (`-target-cpu znver1`, `-target-cpu znver2` etc.), clang 18 crashes with an assertion error.

```
$ clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -target-cpu znver1 -O -x c test.c
clang: /builddir/build/BUILD/llvm-project-release-18.x/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:9845: SDValue llvm::SelectionDAG::getNode(unsigned int, const SDLoc &, SDVTList, ArrayRef<SDValue>, const SDNodeFlags): Assertion `Op.getOpcode() != ISD::DELETED_NODE && "Operand is DELETED_NODE!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -target-cpu znver1 -O -x c test.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'test.c'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@d'
 #0 0x0000ffff9d700510 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM-18.so+0x4300510)
 #1 0x0000ffff9d6ff084 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-18.so+0x42ff084)
 #2 0x0000ffff9d6ffd3c (/lib64/libLLVM-18.so+0x42ffd3c)
 #3 0x0000ffffa6fa37bc (linux-vdso.so.1+0x7bc)
 #4 0x0000ffffa6dee458 (/lib64/libc.so.6+0x8e458)
 #5 0x0000ffffa6da457c raise (/lib64/libc.so.6+0x4457c)
 #6 0x0000ffffa6d90280 abort (/lib64/libc.so.6+0x30280)
 #7 0x0000ffffa6d9dd04 (/lib64/libc.so.6+0x3dd04)
 #8 0x0000ffffa6d9dd7c (/lib64/libc.so.6+0x3dd7c)
 #9 0x0000ffff9e327848 llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::SDVTList, llvm::ArrayRef<llvm::SDValue>, llvm::SDNodeFlags) (/lib64/libLLVM-18.so+0x4f27848)
#10 0x0000ffff9e37dd68 llvm::SelectionDAGISel::Select_INLINEASM(llvm::SDNode*) (/lib64/libLLVM-18.so+0x4f7dd68)
#11 0x0000ffffa15162b0 (/lib64/libLLVM-18.so+0x81162b0)
#12 0x0000ffff9e37b8f4 llvm::SelectionDAGISel::DoInstructionSelection() (/lib64/libLLVM-18.so+0x4f7b8f4)
#13 0x0000ffff9e375b58 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/lib64/libLLVM-18.so+0x4f75b58)
#14 0x0000ffff9e37313c llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/lib64/libLLVM-18.so+0x4f7313c)
#15 0x0000ffff9e36f670 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/lib64/libLLVM-18.so+0x4f6f670)
#16 0x0000ffffa150c408 (/lib64/libLLVM-18.so+0x810c408)
#17 0x0000ffff9dd0bc50 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/lib64/libLLVM-18.so+0x490bc50)
#18 0x0000ffff9d988408 llvm::FPPassManager::runOnFunction(llvm::Function&) (/lib64/libLLVM-18.so+0x4588408)
#19 0x0000ffff9d993e64 llvm::FPPassManager::runOnModule(llvm::Module&) (/lib64/libLLVM-18.so+0x4593e64)
#20 0x0000ffff9d98d040 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/lib64/libLLVM-18.so+0x458d040)
#21 0x0000ffffa5370130 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/lib64/libclang-cpp.so.18+0x2b70130)
#22 0x0000ffffa5773ae4 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.18+0x2f73ae4)
#23 0x0000ffffa3ea841c clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.18+0x16a841c)
#24 0x0000ffffa61ea008 clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.18+0x39ea008)
#25 0x0000ffffa616a698 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.18+0x396a698)
#26 0x0000ffffa6264c50 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.18+0x3a64c50)
#27 0x0000aaaaade950d8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-18+0x250d8)
#28 0x0000aaaaade91824 (/usr/bin/clang-18+0x21824)
#29 0x0000aaaaade9011c clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang-18+0x2011c)
#30 0x0000aaaaade9de50 main (/usr/bin/clang-18+0x2de50)
#31 0x0000ffffa6d90944 (/lib64/libc.so.6+0x30944)
#32 0x0000ffffa6d90a18 __libc_start_main (/lib64/libc.so.6+0x30a18)
#33 0x0000aaaaade8dd30 _start (/usr/bin/clang-18+0x1dd30)
Aborted (core dumped)
```

Reduced test case:

```c
struct {
  long a[1];
} b;
char c();
void d() { asm("" : "+m"(b.a[1 + (c() & 1)])); }
```

The test case is extracted from the Linux kernel.

### PR DESCRIPTION
**Pull request by RicoAfoat**
SelectInlineAsmMemoryOperands - change the vector of SDValue into a list of SDNodeHandle. Fixes issues where x86 might call replaceAllUses when matching address.

Fixes https://github.com/llvm/llvm-project/issues/82431 - see https://github.com/llvm/llvm-project/issues/82431 for more information.

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 1]
```diff
@@ -2278,18 +2278,27 @@ static bool foldMaskedShiftToBEXTR(SelectionDAG &DAG, SDValue N,
...
+                                       unsigned Depth) {
   assert(AM.IndexReg.getNode() == nullptr && "IndexReg already matched");
   assert((AM.Scale == 1 || AM.Scale == 2 || AM.Scale == 4 || AM.Scale == 8) &&
          "Illegal index scale");
 
+  auto adapter = [this, &AM, &Depth](SDValue N) -> SDValue {
+    auto ret_val = matchIndexRecursively(N, AM, Depth + 1);
+    if (ret_val)
+      return ret_val.value();
+    return N;
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2296]: this can all be reduced to
```
return matchIndexRecursively(N, AM, Depth + 1).value_or(N);
```

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 2]
```diff
@@ -2670,97 +2766,14 @@ bool X86DAGToDAGISel::matchAddressRecursively(SDValue N, X86ISelAddressMode &AM,
     break;
   }
   case ISD::ZERO_EXTEND: {
-    // Try to widen a zexted shift left to the same size as its use, so we can
-    // match the shift as a scale factor.
     if (AM.IndexReg.getNode() != nullptr || AM.Scale != 1)
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2769]: Can we remove the `AM.Scale != 1`? matchIndexRecursively needs to be able to accumulate scale

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 3]
```diff
@@ -2670,97 +2766,14 @@ bool X86DAGToDAGISel::matchAddressRecursively(SDValue N, X86ISelAddressMode &AM,
...
-
-      // Convert the shift to scale factor.
-      AM.Scale = 1 << ShAmtV;
-      // If matchIndexRecursively is not called here,
-      // Zext may be replaced by other nodes but later used to call a builder
-      // method
-      AM.IndexReg = matchIndexRecursively(Zext, AM, Depth + 1);
+    // All relevant operations are moved into matchIndexRecursively.
+    auto Index = matchIndexRecursively(N, AM, Depth + 1);
+    if (Index) {
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2773]:
```
if (auto Index = matchIndexRecursively(N, AM, Depth + 1)) {
```

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 4]
```diff
@@ -2859,9 +2872,14 @@ bool X86DAGToDAGISel::selectVectorAddr(MemSDNode *Parent, SDValue BasePtr,
...
-  if (IndexOp.getScalarValueSizeInBits() == BasePtr.getScalarValueSizeInBits())
-    AM.IndexReg = matchIndexRecursively(IndexOp, AM, 0);
-  else
+  if (IndexOp.getScalarValueSizeInBits() ==
+      BasePtr.getScalarValueSizeInBits()) {
+    auto ret_val = matchIndexRecursively(IndexOp, AM, 0);
+    if (ret_val)
+      AM.IndexReg = ret_val.value();
+    else
+      AM.IndexReg = IndexOp;
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2881]:
```
AM.IndexReg = matchIndexRecursively(IndexOp, AM, 0).value_or(IndexOp);
```

**Review by RKSimon — COMMENTED** [review]
A few initial things I've noticed

**Comment by RicoAfoat** [comment]
@RKSimon I tried but failed to find an elegant solution. 

As far as I'm concerned, move all `ZERO_EXTEND` patterns to `matchIndexRecursively` and literally match this patterns recursively would fix the issue. 

But it's hard for me to find a condition which tells whether the pattern match is successful. As mentioned above, `N!=matchIndexRecursively...` will not help. It seems that there's two way left:

1. Modify the return value of `matchIndexRecursively`, which needs to modify all the caller function as well. Maybe hide all of this into a adapter would be elegant.
2. Leave some redundant code in `matchAddressRecursively`, which is also not elegant.

Hope this helpful to you and I would like to know how will you solve the whole problem.

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 5]
```diff
@@ -2346,54 +2352,137 @@ SDValue X86DAGToDAGISel::matchIndexRecursively(SDValue N,
...
+
+    if (Src.getOpcode() == ISD::SHL && Src.hasOneUse()) {
+      // Give up if the shift is not a valid scale factor [1,2,3].
+      SDValue ShlSrc = Src.getOperand(0);
+      SDValue ShlAmt = Src.getOperand(1);
+      auto *ShAmtC = dyn_cast<ConstantSDNode>(ShlAmt);
+      if (!ShAmtC)
+        return std::nullopt;
+      unsigned ShAmtV = ShAmtC->getZExtValue();
+      if (ShAmtV > 3 || (1 << ShAmtV) * AM.Scale > 8)
```
Comment (RicoAfoat) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2423]: Yes, I think we can remove `AM.Scale!=1` in `matchAddressRecursively`. I relax the restriction here but not for the last case where we try to deal with mask and shift.

**Comment by Mekapaedia** [comment]
Does this patch also solve/affect #72026?

**Comment by RKSimon** [comment]
@RicoAfoat Sorry this fell off my radar over the Easter break - I'll take a look soon.

**Comment by Mekapaedia** [comment]
I tested this patch rebased on main and it does seem to correctly compile the reproducer from #72026, so this PR could close that and by extension #85443

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 6]
```diff
@@ -2278,18 +2278,20 @@ static bool foldMaskedShiftToBEXTR(SelectionDAG &DAG, SDValue N,
...
-// Attempt to peek further into a scaled index register, collecting additional
-// extensions / offsets / etc. Returns /p N if we can't peek any further.
-SDValue X86DAGToDAGISel::matchIndexRecursively(SDValue N,
-                                               X86ISelAddressMode &AM,
-                                               unsigned Depth) {
+// Change the return type of matchIndexRecursively to std::optional<SDValue> to
+// make it easier for caller to tell whether the match is successful. Attempt to
+// peek further into a scaled index register, collecting additional extensions /
+// offsets / etc. Returns /p N if we can't peek any further.
+std::optional<SDValue>
```
Comment (topperc) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2285]: I didn't look too closely at that patch. Do we need a std::optional here? SDValue already has an empty state, can't we use that like we normally do in SelectionDAG?

File: llvm/lib/Target/X86/X86ISelDAGToDAG.cpp [hunk 7]
```diff
@@ -2670,97 +2761,13 @@ bool X86DAGToDAGISel::matchAddressRecursively(SDValue N, X86ISelAddressMode &AM,
...
-      CurDAG->RemoveDeadNode(N.getNode());
-
-      // Convert the shift to scale factor.
-      AM.Scale = 1 << ShAmtV;
-      // If matchIndexRecursively is not called here,
-      // Zext may be replaced by other nodes but later used to call a builder
-      // method
-      AM.IndexReg = matchIndexRecursively(Zext, AM, Depth + 1);
+    // All relevant operations are moved into matchIndexRecursively.
+    if (auto Index = matchIndexRecursively(N, AM, Depth + 1)) {
```
Comment (RicoAfoat) [inline llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:2767]: https://github.com/llvm/llvm-project/pull/85081#discussion_r1578811340

@topperc @RKSimon 

For most of the time, `AM.IndexReg` will  be set to the return value of `matchIndexRecursively` whenever this function is called except here. I'm wondering if a bool is nice for the return type, and we directly change the value of `AM.IndexReg` inside `matchIndexRecursively`(We have already done that to `AM.Scale`).

In addition, some functions (`foldMaskAndShiftToExtract`,`foldMaskAndShiftToScale`, `foldMaskedShiftToBEXTR`) which directly modify `AM.IndexReg` and are previously called in `matchAddressRecursively` are moved to `matchIndexRecursively`. It will be a little strange to return the value... Otherwise we need to adjust them as well.

Should we change it to a bool ?

**Comment by topperc** [comment]
To make sure I understand. The fundamental issue seems to be that X86 is deleting nodes while Select_INLINEASM is holding references to them from the selection of an earlier memory operand.

So my immediate thoughs/questions are.
-Can we remove the deletion? If the node is truly dead, it will be pruned when we reach it in the isel selection process. This might affect use counts and affect the behavior of selection while that node is still hanging out in the graph.
-Can we disable the deletion when selecting inline assembly?
-Maybe Select_INLINEASM should be holding the nodes as HandleSDNodes so they will be updated by replaceAllUses.

**Review by RKSimon — COMMENTED** [review]
I'm not sure about this - the point of matchIndexRecursively was that it could improve the indexReg / AM.scale values as it worked up the tree, its not designed to fail in anyway, just stop recursing.

Technically matchIndexRecursively could return void and it updates the AM.IndexReg internally (like it does AM.Scale), I didn't do it that way as I felt the recursion worked better by setting the value on return, but I may have been wrong.

**Comment by RKSimon** [comment]
@RicoAfoat The patch description doesn't match the patch contents at all any more - start over?

**Comment by nikic** [comment]
@RKSimon Is this issue related to the one worked around in https://github.com/llvm/llvm-project/commit/e975ff0a223e79842b693e0ec4d3cac87963869a, or is this independent?

**Comment by RKSimon** [comment]
@RicoAfoat Are you still looking at this please?

**Comment by RicoAfoat** [comment]
Sincerely sorry for my absense. Just manage to respawn from something else.

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp [hunk 8]
```diff
@@ -2111,24 +2111,27 @@ bool SelectionDAGISel::CheckOrMask(SDValue LHS, ConstantSDNode *RHS,
...
-  std::vector<SDValue> InOps;
-  std::swap(InOps, Ops);
+  // change the vector of SDValue into a list of SDNodeHandle for x86 might call
+  // replaceAllUses when matching address
 
-  Ops.push_back(InOps[InlineAsm::Op_InputChain]); // 0
-  Ops.push_back(InOps[InlineAsm::Op_AsmString]);  // 1
-  Ops.push_back(InOps[InlineAsm::Op_MDNode]);     // 2, !srcloc
-  Ops.push_back(InOps[InlineAsm::Op_ExtraInfo]);  // 3 (SideEffect, AlignStack)
+  std::list<HandleSDNode> handles;
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:2117]: Variable names should be capitalized

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp [hunk 9]
```diff
@@ -2158,15 +2161,19 @@ void SelectionDAGISel::SelectInlineAsmMemoryOperands(std::vector<SDValue> &Ops,
...
   }
 
   // Add the glue input back if present.
-  if (e != InOps.size())
-    Ops.push_back(InOps.back());
+  if (e != Ops.size())
+    handles.emplace_back(Ops.back());
+
+  Ops.clear();
+  for (auto &i : handles)
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:2175]: `i` isn't a good variable number. `i` is usually used for counters or iterators. We have neither of those here.

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp [hunk 10]
```diff
@@ -2111,24 +2111,27 @@ bool SelectionDAGISel::CheckOrMask(SDValue LHS, ConstantSDNode *RHS,
 /// by tblgen.  Others should not call it.
 void SelectionDAGISel::SelectInlineAsmMemoryOperands(std::vector<SDValue> &Ops,
                                                      const SDLoc &DL) {
-  std::vector<SDValue> InOps;
-  std::swap(InOps, Ops);
+  // change the vector of SDValue into a list of SDNodeHandle for x86 might call
```
Comment (topperc) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:2114]: This should be a complete sentence starting with a capital letter and ending with a period.

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Comment by RKSimon** [comment]
@RicoAfoat please can you update the patch summary?

**Comment by RKSimon** [comment]
We just need the patch summary updating as the patch no longer changes matchIndexRecursively.
