### PR TITLE
[flang] Remove double pointer indirection for _QQEnvironmentDefaults

### LINKED ISSUE #90537: [flang]  Extra level of indirection to access the EnvironmentDefaultList after https://github.com/llvm/llvm-project/pull/89938
We used to pass the environment as such:
```
extern const struct EnvironmentDefaultList *_QQEnvironmentDefaults;

/* C main stub */
int main(int argc, const char *argv[], const char *envp[]) {
  RTNAME(ProgramStart)(argc, argv, envp, _QQEnvironmentDefaults);
  _QQmain();
  RTNAME(ProgramEndStatement)();
  return 0;
}
```
whereby the global `_QQEnvironmentDefaults` was holding a pointer to an `EnvironmentDefaultList`, thereby adding a level of indirection.

After the PR, when passed in LLVM, we are now passing the address of `_QQEnvironmentDefaults`
```
@_QQEnvironmentDefaults.items = linkonce constant [1 x { ptr, ptr }] [{ ptr, ptr } { ptr @_QQclX464F52545F434F4E5645525400, ptr @_QQclX5357415000 }], comdat
@_QQclX464F52545F434F4E5645525400 = linkonce constant [13 x i8] c"FORT_CONVERT\00", comdat
@_QQclX5357415000 = linkonce constant [5 x i8] c"SWAP\00", comdat
@_QQEnvironmentDefaults.list = linkonce constant { i32, ptr } { i32 1, ptr @_QQEnvironmentDefaults.items }, comdat
@_QQEnvironmentDefaults = constant ptr @_QQEnvironmentDefaults.list
...
define i32 @main(i32 %0, ptr %1, ptr %2) {
  call void @_FortranAProgramStart(i32 %0, ptr %1, ptr %2, ptr @_QQEnvironmentDefaults)
  call void @_QQmain()
  call void @_FortranAProgramEndStatement()
  ret i32 0
}
```

You can see the issue with an empty program
```
flang-new  main.f90 -fconvert=swap
./a.out
Segmentation fault
```
(You may have to try several times)

### PR DESCRIPTION
**Pull request by DavidTruby**
A double pointer was being passed to the call to FortranStart rather than
just a pointer to the EnvironmentDefaults.list. This now passes `null` directly
when there's no EnvironmentDefaults.list and passes the list directly when there
is, removing the original global variable which was a pointer to a pointer containing
null or the EnvironmentDefaults.list global.

Fixes #90537

### CODE REVIEW

File: flang/lib/Lower/Bridge.cpp [hunk 1]
```diff
@@ -360,10 +360,11 @@ class FirConverter : public Fortran::lower::AbstractConverter {
         // not need to be generated even if no defaults are specified.
         // However, generating main or changing when the runtime reads
         // environment variables is required to do so.
-        auto env = fir::runtime::genEnvironmentDefaults(
-            *builder, toLocation(), bridge.getEnvironmentDefaults());
+        // auto env = fir::runtime::genEnvironmentDefaults(
+        //    *builder, toLocation(), bridge.getEnvironmentDefaults());
```
Comment (tblah) [inline flang/lib/Lower/Bridge.cpp:364]: nit

**Review by Renaud-K — APPROVED** [review]
Thank you!

**Review by tblah — APPROVED** [review]
Thanks for the quick fix
