### PR TITLE
[clang-format]  Ignore imports in comments for Java import sorting

### LINKED ISSUE #176771: clang-format Java import sorting fails to ignore 'import' in comments, text blocks
Java source files can contain apparent `import` statements inside block comments (e.g., showing a code example) or Java 15 text blocks (e.g., in codegen code). These can get mixed up with real `import` statements when run through clang-format.

Here are 2 potential test cases and the broken output from current clang-format (trunk):

---

`blockcomment.java`:

```java
/* import org.d;
import org.c;
import org.b; */
import org.a;
```

`clang-format --style=LLVM blockcomment.java`:

```java
/* import org.d;
import org.a;
import org.b; */
import org.c;
```

---

`textblock.java`:

```java
String code = """
    import org.c;
    \"""
    import org.b;
\\""";
import org.a;
```

`clang-format --style=LLVM textblock.java`:

```java
String code = """
\\""";
import org.a;
    \"""
    import org.b;
    import org.c;
```

### PR DESCRIPTION
**Pull request by nataliakokoromyti**
Java source files can contain apparent import statements inside block comments (e.g., showing a code example). These can get mixed up with real import statements when run through clang-format.

This patch tracks block comments (/* ... */) so that we skip lines that are inside them. 

Fixes #176771

### CODE REVIEW

**Comment by owenca** [comment]
> How much of this is needed after #177736?

That patch is unrelated because we don't handle text blocks here now.

File: clang/lib/Format/Format.cpp [hunk 1]
```diff
@@ -3755,6 +3754,7 @@ tooling::Replacements sortJavaImports(const FormatStyle &Style, StringRef Code,
   unsigned Prev = 0;
   unsigned SearchFrom = 0;
```
Comment (owenca) [inline clang/lib/Format/Format.cpp]:
```suggestion
  bool HasImport = false;
```
We don't need both `Prev` and `SearchFrom`.

Comment (owenca) [inline clang/lib/Format/Format.cpp]:
```suggestion
  bool HasImport = false;
```
We don't need both `Prev` and `SearchFrom`.

File: clang/lib/Format/Format.cpp [hunk 2]
```diff
@@ -3767,12 +3767,26 @@ tooling::Replacements sortJavaImports(const FormatStyle &Style, StringRef Code,
         Code.substr(Prev, (Pos != StringRef::npos ? Pos : Code.size()) - Prev);
 
     StringRef Trimmed = Line.trim();
-    if (isClangFormatOff(Trimmed))
+    if (Trimmed.empty()) {
+      // Skip empty lines.
```
Comment (owenca) [inline clang/lib/Format/Format.cpp]:
```suggestion
    if (Trimmed.empty() || PackageRegex.match(Trimmed)) {
      // Skip empty lines and package statements.
```

File: clang/unittests/Format/SortImportsTestJava.cpp [hunk 3]
```diff
@@ -349,6 +349,36 @@ TEST_F(SortImportsTestJava, NoReplacementsForValidImportsWindows) {
...
+            "  \"\"\";\n"
+            "}",
+            sort("import org.a;\n"
+                 "\n"
+                 "class Foo {\n"
+                 "  String code = \"\"\"\n"
+                 "      import org.c;\n"
+                 "      import org.b;\n"
+                 "  \"\"\";\n"
+                 "}"));
```
Comment (owenca) [inline clang/unittests/Format/SortImportsTestJava.cpp]: Ditto.

**Review by owenca — COMMENTED** [review]
Please also add a test case that starts with a package statement.

File: clang/unittests/Format/SortImportsTestJava.cpp [hunk 4]
```diff
@@ -349,6 +349,44 @@ TEST_F(SortImportsTestJava, NoReplacementsForValidImportsWindows) {
...
+
+TEST_F(SortImportsTestJava, SortImportsAfterPackageStatement) {
+  EXPECT_EQ("package org.a;\n"
+            "\n"
+            "import org.a;\n"
+            "import org.b;\n",
+            sort("package org.a;\n"
+                 "\n"
+                 "import org.b;\n"
+                 "import org.a;\n"));
```
Comment (owenca) [inline clang/unittests/Format/SortImportsTestJava.cpp]:
```suggestion
                 "import org.a;"));
```

**Review by owenca — COMMENTED** [review]
Please also address https://github.com/llvm/llvm-project/pull/177326#discussion_r2778905554.

File: clang/unittests/Format/SortImportsTestJava.cpp [hunk 5]
```diff
@@ -349,6 +349,44 @@ TEST_F(SortImportsTestJava, NoReplacementsForValidImportsWindows) {
...
+            "  \"\"\";\n"
+            "}",
+            sort("import org.a;\n"
+                 "\n"
+                 "class Foo {\n"
+                 "  String code = \"\"\"\n"
+                 "      import org.c;\n"
+                 "      import org.b;\n"
+                 "  \"\"\";\n"
+                 "}"));
```
Comment (owenca) [inline clang/unittests/Format/SortImportsTestJava.cpp]:
```suggestion
  constexpr StringRef Code("import org.a;\n"
                           "\n"
                           "class Foo {\n"
                           "  String code = \"\"\"\n"
                           "      import org.c;\n"
                           "      import org.b;\n"
                           "  \"\"\";\n"
                           "}");
  EXPECT_EQ(Code, sort(Code));
```

File: clang/lib/Format/Format.cpp [hunk 6]
```diff
@@ -3743,8 +3740,10 @@ static void sortJavaImports(const FormatStyle &Style,
 
 namespace {
 
-const char JavaImportRegexPattern[] =
-    "^[\t ]*import[\t ]+(static[\t ]*)?([^\t ]*)[\t ]*;";
+constexpr StringRef
+    JavaImportRegexPattern("^import[\t ]+(static[\t ]*)?([^\t ]*)[\t ]*;");
+
+constexpr StringRef JavaPackageRegexPattern("^package[\t ]+");
```
Comment (owenca) [inline clang/lib/Format/Format.cpp]:
```suggestion
constexpr StringRef JavaPackageRegexPattern("^package[\t ]");
```

**Review by owenca — APPROVED** [review]
