### PR TITLE
[LICM] Drop nsw/nuw flags on affected instructions in hoistMulAddAssociation.

### LINKED ISSUE #85457: [LICM] Mul association incorrectly combines no-wrap flags
After the https://github.com/llvm/llvm-project/pull/67736 LICM turns the following IR
```llvm
define i32 @test() {
entry:
  br label %loop

loop:
  %iv = phi i32 [ 1, %entry ], [ %iv.next, %loop ]
  %iv.next = add nuw nsw i32 %iv, 1
  %mul0 = mul nuw nsw i32 30000, %iv
  %mul1 = mul nuw i32 %mul0, 30000
  %cmp = icmp slt i32 %mul1, 1
  br i1 %cmp, label %exit, label %loop

exit:
  ret i32 0
}
```
into the
```llvm
define i32 @test() {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %iv = phi i32 [ 1, %entry ], [ %iv.next, %loop ]
  %iv.next = add nuw nsw i32 %iv, 1
  %mul0 = mul nuw nsw i32 900000000, %iv
  %cmp = icmp slt i32 %mul0, 1
  br i1 %cmp, label %exit, label %loop

exit:                                             ; preds = %loop
  ret i32 0
}
```
https://godbolt.org/z/G5zvEzYEv

The resulting `mul` instruction has 2 flags `nuw nsw`, while in the source code it has `nuw` only. That transformation seems to be incorrect. 

If we run `instcombine` for the case, it would provide `mul nuw i32 %iv, 900000000`:
https://godbolt.org/z/6oWrPbEMn

### PR DESCRIPTION
**Pull request by topperc**
Since we are introducing new multiplies earlier in the arithmetic, the nsw/nuw flags on later instructions are no longer accurate.

Fixes #85457.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/LICM.cpp [hunk 1]
```diff
@@ -2735,6 +2737,12 @@ static bool hoistMulAddAssociation(Instruction &I, Loop &L,
   if (Changes.empty())
     return false;
 
+  // Drop the poison flags for any adds we looked through.
+  if (I.getType()->isIntOrIntVectorTy()) {
+    for (auto *Add : Adds)
+      Add->dropPoisonGeneratingFlags();
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/LICM.cpp:2743]: I think the flag drop on the adds does not have test coverage?

**Comment by danilaml** [comment]
This should also fix https://github.com/llvm/llvm-project/issues/85448

File: llvm/lib/Transforms/Scalar/LICM.cpp (hunk 1 above)
Comment (topperc) [reply llvm/lib/Transforms/Scalar/LICM.cpp:2743]: Aren't they covered by the NOT_CONSTRAINED-NEXT lines? On the test case where I added `nsw nuw` to adds?

**Review by nikic — APPROVED** [review]
LGTM
