### PR TITLE
[clang-format] Don't insert a space between :: and *

### LINKED ISSUE #100841: clang-format 19-rc1 regression: member function pointers as template arguments
In our internal code base, we have a function templated with a member function pointer.
Upgrading from clang-format-17 to 19.1.0-rc1, clang-format proposed the following change, which is incorrect / unexpected

```patch
-template <llvm::Value* (llvm::IRBuilderBase::*func)(llvm::Value*, llvm::Value*, const llvm::Twine&, bool, bool)>
+template <llvm::Value* (llvm::IRBuilderBase::* func)(llvm::Value*, llvm::Value*, const llvm::Twine&, bool, bool)>
 llvm::Value* LLVMTranslator::generateArithmetic(const IRBinaryOp& op) {
 ```

### PR DESCRIPTION
**Pull request by owenca**
Also, don't insert a space after ::* for method pointers.

See https://github.com/llvm/llvm-project/pull/86253#issuecomment-2298404887.

Fixes #100841.

### CODE REVIEW

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -4591,7 +4589,9 @@ bool TokenAnnotator::spaceRequiredBetween(const AnnotatedLine &Line,
     if (!BeforeLeft)
       return false;
     if (BeforeLeft->is(tok::coloncolon)) {
-      return Left.is(tok::star) &&
+      const auto *Prev = BeforeLeft->Previous;
+      return Left.is(tok::star) && Prev &&
+             !Prev->endsSequence(tok::identifier, TT_FunctionTypeLParen) &&
              Style.PointerAlignment != FormatStyle::PAS_Right;
```
Comment (kadircet) [inline clang/lib/Format/TokenAnnotator.cpp:4595]: nit: i think `PointerAlignment` is always `non-right` when we get here, as we bail out on line `4577` when pointer alignment is right (or it's derived to be right).

File: clang/lib/Format/TokenAnnotator.cpp [hunk 2]
```diff
@@ -4591,7 +4589,9 @@ bool TokenAnnotator::spaceRequiredBetween(const AnnotatedLine &Line,
     if (!BeforeLeft)
       return false;
     if (BeforeLeft->is(tok::coloncolon)) {
-      return Left.is(tok::star) &&
+      const auto *Prev = BeforeLeft->Previous;
+      return Left.is(tok::star) && Prev &&
+             !Prev->endsSequence(tok::identifier, TT_FunctionTypeLParen) &&
```
Comment (kadircet) [inline clang/lib/Format/TokenAnnotator.cpp:4594]: i think we can also have cases like `void (A::B::*func)();`

**Review by kadircet — CHANGES_REQUESTED** [review]
thanks a lot for the quick fix!

**Review by mydeveloperday — APPROVED** [review]

File: clang/lib/Format/TokenAnnotator.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/TokenAnnotator.cpp]: Good catch!

File: clang/lib/Format/TokenAnnotator.cpp (hunk 2 above)
Comment (owenca) [reply clang/lib/Format/TokenAnnotator.cpp]: I had thought about adding a loop to handle the nested-name-specifier but decided to wait until we ran into code like the example you gave above in practice. Let me know if you strongly feel that we should handle it now.

Comment (kadircet) [reply clang/lib/Format/TokenAnnotator.cpp]: i think it's actually common enough to handle in this patch, https://github.com/search?q=lang%3Acpp+%2F%3A%3A%5Cw%2B%3A%3A%5C*%5C%29%2F&type=code.

moreover we also have cases like `(std::remove_pointer<O>::type::*)`. so it might actually be easier to match by going forward (which should also ensure we do less operations)? e.g. something like:
```
// Don't add space around function-type pointers.
// - void (*foo)(int);
// - void (::B::*foo)(int);
// - void (A<T>::B::*)(int);
auto OpeningParen = Right.MatchingParen;
if (!OpeningParen && Right.Next)
  OpeningParen = Right.Next->MatchingParen;
if (OpeningParen && OpeningParen->is(TT_FunctionTypeLParen))
  return false;

if (BeforeLeft->is(tok::coloncolon))
  return true;
```

File: clang/lib/Format/TokenAnnotator.cpp [hunk 3]
```diff
@@ -4589,9 +4589,12 @@ bool TokenAnnotator::spaceRequiredBetween(const AnnotatedLine &Line,
...
       return false;
     if (BeforeLeft->is(tok::coloncolon)) {
-      const auto *Prev = BeforeLeft->Previous;
-      return Left.is(tok::star) && Prev &&
-             !Prev->endsSequence(tok::identifier, TT_FunctionTypeLParen);
+      if (Left.isNot(tok::star))
+        return false;
+      if (!Right.startsSequence(tok::identifier, tok::r_paren))
+        return true;
+      const auto *Tok = Right.Next->MatchingParen;
```
Comment (kadircet) [inline clang/lib/Format/TokenAnnotator.cpp:4596]: `Right.Next` might be nullptr

**Review by kadircet — APPROVED** [review]
thanks a lot!

File: clang/lib/Format/TokenAnnotator.cpp (hunk 3 above)
Comment (owenca) [reply clang/lib/Format/TokenAnnotator.cpp:4596]: No, because `startsSequence()` returned `true`. I'll add an assertion though.
