### PR TITLE
[clang-format] Fix option `BreakBinaryOperations` for operator `>>`

### LINKED ISSUE #106228: clang-format: Incorrect behavior with BreakBinaryOperations
Thanks for adding BreakBinaryOperations! It's a great feature.

I notice some strange behavior when dealing with the operator>>:

I'm using `BreakBinaryOperations: RespectPrecedence`

Before formatting:
```
void abc()
{
   int aaaaaa, bbbbbb, cccccc;
   aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc
      >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc;
}
void abc()
{
   int aaaaaa, bbbbbb, cccccc;
   aaaaaa << bbbbbb << cccccc << aaaaaa << bbbbbb << cccccc << aaaaaa << bbbbbb << cccccc << aaaaaa << bbbbbb << cccccc
      << aaaaaa << bbbbbb << cccccc << aaaaaa << bbbbbb << cccccc;
}
```

After formatting:
```
void abc()
{
   int aaaaaa, bbbbbb, cccccc;
   aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc >> aaaaaa >> bbbbbb >> cccccc;
}
void abc()
{
   int aaaaaa, bbbbbb, cccccc;
   aaaaaa
      << bbbbbb
      << cccccc
      << aaaaaa
      << bbbbbb
      << cccccc
      << aaaaaa
      << bbbbbb
      << cccccc
      << aaaaaa
      << bbbbbb
      << cccccc
      << aaaaaa
      << bbbbbb
      << cccccc
      << aaaaaa
      << bbbbbb
      << cccccc;
}
```

`operator<<` works as expected, `operator>>` does not.

### PR DESCRIPTION
**Pull request by andergnet**
Fixes #106228.

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -28188,6 +28188,16 @@ TEST_F(FormatTest, BreakBinaryOperations) {
...
                Style);
+
+  Style.BreakBinaryOperations = FormatStyle::BBO_OnePerLine;
+  // Check operator >> special case
+  verifyFormat("std::cout\n"
+               "    << longOperand1\n"
+               "    << longOperand2\n"
+               "    << longOperand3\n"
+               "    << longOperand4\n"
+               "    << longOperand5;",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:28199]: This test case passes without this patch.

**Review by owenca — COMMENTED** [review]
~With `ColumnLimit: 60`, this patch doesn't seem to format the following  correctly:
`std::cout << longOperand_1 << longOperand_2 << longOperand_3;`~

File: clang/unittests/Format/FormatTest.cpp (hunk 1 above)
Comment (andergnet) [reply clang/unittests/Format/FormatTest.cpp]: About your test: `std::cout << longOperand_1 << longOperand_2 << longOperand_3;` 

I didn't change that behavior, I guess it has something to do with penalties, once it gets big enough it does split correctly.

File: clang/unittests/Format/FormatTest.cpp [hunk 2]
```diff
@@ -28188,6 +28188,17 @@ TEST_F(FormatTest, BreakBinaryOperations) {
                "                  | byte_buffer[2] << 16\n"
                "                  | byte_buffer[3] << 24;",
                Style);
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:28190]:
```suggestion
               Style);

  verifyFormat("std::cin >> longOperand_1 >> longOperand_2\n"
               "    >> longOperand_3;",
               Style);
```
This test case, which is a minimum reproducer of #106228, would still fail.

File: clang/unittests/Format/FormatTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp]: Yeah. I just gave you a minimal test case using the same `<<` in your previous test case. We can leave it to another patch.

File: clang/unittests/Format/FormatTest.cpp (hunk 2 above)
Comment (andergnet) [reply clang/unittests/Format/FormatTest.cpp:28190]: I'm not sure I get what you are trying to tell me. Do you want the unit test to be the minimal reproducer of the error?

As far as I have tested the changes work, these are some unit tests I have done (but not commited) to check it:
```
{
  auto Style = getLLVMStyleWithColumns(60);
  Style.BreakBeforeBinaryOperators = FormatStyle::BOS_NonAssignment;

  Style.BreakBinaryOperations = FormatStyle::BBO_OnePerLine;

  verifyFormat("std::cin\n"
               "    >> longOperand_1\n"
               "    >> longOperand_2\n"
               "    >> longOperand_3_;",
               Style);

  verifyFormat("std::cin >> longOperand_1 >> longOperand_2 >> longOperand_3;",
               Style);

  Style.BreakBinaryOperations = FormatStyle::BBO_RespectPrecedence;
  verifyFormat("std::cin\n"
               "    >> longOperand_1\n"
               "    >> longOperand_2\n"
               "    >> longOperand_3_;",
               Style);

  verifyFormat("std::cin >> longOperand_1 >> longOperand_2 >> longOperand_3;",
               Style);
}
```

Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp:28190]: > This test case, which is a minimum reproducer of #106228, would still fail.

The test case I gave you should pass but would fail. See also https://github.com/llvm/llvm-project/issues/106228#issuecomment-2594566298.

Comment (andergnet) [reply clang/unittests/Format/FormatTest.cpp:28190]: I think we are not agreeing on what the outcome should be :), see the [comment](https://github.com/llvm/llvm-project/issues/106228#issuecomment-2594591797)

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 3]
```diff
@@ -147,7 +147,8 @@ static bool startsNextOperand(const FormatToken &Current) {
 // Returns \c true if \c Current is a binary operation that must break.
 static bool mustBreakBinaryOperation(const FormatToken &Current,
                                      const FormatStyle &Style) {
-  return Style.BreakBinaryOperations != FormatStyle::BBO_Never &&
+  return Current.CanBreakBefore &&
```
[the remark this answers is not in the document]
Comment (andergnet) [reply clang/lib/Format/ContinuationIndenter.cpp:150]: That's hard to put in words, I'll try.

Part of the issue is that `>>` are two tokens and `<<` is only one, and there is an extra step in the processing.

The algorithm tries all possible solutions, split or not to split the line at every point. 
During the processing it reaches this line:
https://github.com/llvm/llvm-project/blob/602e7a81e23c4e7b481494cd92e754ad01aa9007/clang/lib/Format/ContinuationIndenter.cpp#L904

When it's a variable name, the first `>`or the token `<<` it behaves as it should. For a variable mustBreak returns false: it's not a binary operation, and for the others returns according to the format style. However, before the second `<` it does not behave well, because it's a binary operator and tries to apply the format style accordingly (the same way it does for the others) and returns must break to `true`. This in turn causes `CurrentState.NoLineBreak = true;` which prevents further analyzing this solution branch which is valid. 

What I'm trying to do is force must break to be `false` when the token format says it `CanBreakBefore == false`, because it shouldn't be a problem not to break in a place not allowed to break. In the operator `<<` is not relevant because every time it enters this path `CanBreakBefore == true`.

If you still have questions, do not hesitate to come back. It is complicated, it took me a while to figure it out what was going on.

[the remark this answers is not in the document]
Comment (owenca) [reply clang/lib/Format/ContinuationIndenter.cpp:150]: Well explained. I forgot that unlike `<<`, `>>` has been split into two `>`s.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 4]
```diff
@@ -147,7 +147,8 @@ static bool startsNextOperand(const FormatToken &Current) {
...
+         Style.BreakBinaryOperations != FormatStyle::BBO_Never &&
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:151]:
```suggestion
  return Style.BreakBinaryOperations != FormatStyle::BBO_Never &&
          Current.CanBreakBefore &&
```
To have a smaller diff.

File: clang/unittests/Format/FormatTest.cpp [hunk 5]
```diff
@@ -28188,6 +28188,17 @@ TEST_F(FormatTest, BreakBinaryOperations) {
...
+
+  Style.BreakBinaryOperations = FormatStyle::BBO_OnePerLine;
+  // Check operator >> special case
+  verifyFormat("std::cin\n"
+               "    >> longOperand1\n"
+               "    >> longOperand2\n"
+               "    >> longOperand3\n"
+               "    >> longOperand4\n"
+               "    >> longOperand5\n"
+               "    >> longOperand6;",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:28200]:
```suggestion
  // Check operator>> special case.
  verifyFormat("std::cin\n"
               "    >> longOperand_1\n"
               "    >> longOperand_2\n"
               "    >> longOperand_3_;",
```
to test the case where the statement length just exceeds the column limit.

Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp:28200]: You can add the same minimal test case at line 28095.

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 4 above)
Comment (andergnet) [reply clang/lib/Format/ContinuationIndenter.cpp]: Done

File: clang/unittests/Format/FormatTest.cpp (hunk 5 above)
Comment (andergnet) [reply clang/unittests/Format/FormatTest.cpp]: I have added several more tests one per test case that are in the function:
- BBO_Never
- BBO_OnePerLine
- BBO_RespectPrecedence
- BBO_OnePerLine + BOS_NonAssignment
- BBO_RespectPrecedence + BOS_NonAssignment

**Review by owenca — APPROVED** [review]
