### PR TITLE
[LoopUnroll] Fix out-of-date LoopInfo being used during unroll

### LINKED ISSUE #191036: [Bug][LoopUnroll] Invalid LoopInfo used during LoopUnroll
LoopUnroll did not update LoopInfo completely correctly, and invalid loopinfo was passed into `simplifyLoopAfterUnroll()` during the transformation.

The way to reproduce the bug: put a call to `LI.verify(DT)` right before the call of `simplifyLoopAfterUnroll(L, !CompletelyUnroll && ULO.Count > 1, LI, SE, DT, AC, TTI, AA)` inside `llvm::UnrollLoop()` in `llvm/lib/Transforms/Utils/LoopUnroll.cpp`, then run check-llvm-transforms-loopunroll. 

93 out of the 230 tests would fail likely all due to invalid loopinfo. Therefore, `simplifyLoopAfterUnroll()` was called with invalid loopinfo passed into it.

Related parent issue: https://github.com/llvm/llvm-project/issues/190682
Related sub-issue: https://github.com/llvm/llvm-project/issues/190671

### PR DESCRIPTION
**Pull request by CongzheUalberta**
Fix #191036 , where loop unroll did not update LoopInfo entirely correctly.

This patch does a similar fix to [PR #191250](https://github.com/llvm/llvm-project/pull/191250) where similar issue was fixed in loop unroll and jam, whereas this patch addresses this issue that occurred in loop unroll.

Invalid LoopInfo gets passed into `simplifyLoopAfterUnroll()`, which could trigger hidden bugs since it is further used by other functions and components like SCEV. To fix, updated LoopInfo correctly before its use.

### CODE REVIEW

File: llvm/lib/Transforms/Utils/LoopUnroll.cpp [hunk 1]
```diff
@@ -1124,21 +1124,26 @@ llvm::UnrollLoop(Loop *L, UnrollLoopOptions ULO, LoopInfo *LI,
...
     LI->erase(L);
     // We shouldn't try to use `L` anymore.
     L = nullptr;
-  } else {
+  }
+
+  // At this point, the code is well formed.  We now simplify the unrolled loop,
+  // doing constant propagation and dead code elimination as we go.
+  simplifyLoopAfterUnroll(
+      L, !CompletelyUnroll && ULO.Count > 1, LI, SE, DT, AC, TTI,
```
Comment (efriedma-quic) [inline llvm/lib/Transforms/Utils/LoopUnroll.cpp:1140]: If SimplifyIVs is false, does simplifyLoopAfterUnroll actually use LoopInfo/SCEV anywhere?

Comment (CongzheUalberta) [reply llvm/lib/Transforms/Utils/LoopUnroll.cpp:1140]: I think there is still a `LI->replacementPreservesLCSSAForm()` that could be invoked inside `simplifyLoopAfterUnroll()` even if SimplifyIVs is false?

Comment (efriedma-quic) [reply llvm/lib/Transforms/Utils/LoopUnroll.cpp:1140]: I suspect that doesn't actually cause any visible breakage, but sure, better to be on the safe side.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by CongzheUalberta** [comment]
> LGTM

Thanks for the review!

> I suspect that doesn't actually cause any visible breakage, but sure, better to be on the safe side.

Agreed. Another relevant issue I discovered (https://github.com/llvm/llvm-project/issues/191471) actually has similar behavior: it did not cause visible breakage right now but the functionality is not entirely correct.
