### PR TITLE
[LifetimeSafety] Optimize loan propagation by separating persistent and block-local origins

### LINKED ISSUE #164625: Investigate +161% compile time hit for AST/ByteCode/Interp.cpp
File: 
https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/ByteCode/Interp.cpp

Per-file compile-time regressions: 
http://llvm-compile-time-tracker.com/compare_clang.php?from=128eacfaba78162c944c073270db02e237b7b851&to=fddb8174bad28a12830236c05eeb981fab2b2a9b&stat=instructions%3Au&sortBy=relative-difference

TODO: Add instructions for "How to profile a clang compilation ?" and "How to get compile commands for a file ?"

### LINKED ISSUE #165780: Optimize joins by separating block-local origins from cross-block persistent origins
Prevent block-local origins from participating in Join operations

The lifetime analysis currently performs join operations on all origins at every  block boundary, which is expensive. However, many origins are block-local: they  are created and destroyed within a single block, existing only to propagate loans  between persistent origins across temporary declarations.

Proposed optimization:
1. Classify origins into two categories during analysis:
   - Block-local origins: start and die within the same block
   - Persistent origins: visible across multiple blocks
   
2. During join operations at block boundaries, only join the persistent origins and skip block-local ones entirely

Benefits:
- Significantly reduces join complexity, especially in functions with many temporary locals
- Performance improvement scales with the ratio of temporary to persistent origins

Considerations:
- Need a pre-pass to correctly classify origins
- Loan propagation for block-local origins must still work correctly within their block

Implementation:
Split the loan propagation lattice into two separate maps:
1. Persistent origins map: for origins visible across multiple blocks
2. Block-local origins map: for origins confined to a single block

At block entries (after joining), the block-local map would be empty. During  block execution, both maps are populated and used for loan propagation. At block boundaries, only the persistent map participates in join operations. Block-local map naturally empties at block entries.

Credits to @Xazax-hun for this idea.

### PR DESCRIPTION
**Pull request by usx95**
## Summary

Optimizes the lifetime analysis loan propagation by preventing block-local origins from participating in expensive join operations at block boundaries.

## Problem

The lifetime analysis currently performs join operations on all origins at every block boundary. However, many origins are block-local: they exist only to propagate loans between persistent origins across temporary declarations and expressions within a single block. Including them in joins is unnecessary and expensive.

## Solution

This PR classifies origins into two categories:

- **Persistent origins**: referenced in multiple basic blocks, must participate in joins
- **Block-local origins**: confined to a single block, can be discarded at block boundaries

### Implementation

1. **Pre-pass** (`computePersistentOrigins`): Analyzes all facts in the CFG to identify which origins appear in multiple blocks
2. **Split lattice**: Maintains two separate `OriginLoanMap`s:
    - `PersistentOrigins`: participates in join operations
    - `BlockLocalOrigins`: used during block execution, discarded at boundaries
3. **Optimized join**: Only merges persistent origins; block-local map is reset to empty

### Benefits

- Significantly reduces join complexity, especially in functions with many temporary locals
- Performance scales with the ratio of temporary to persistent origins
- Correctness preserved: block-local loan propagation still works within blocks

Fixes: https://github.com/llvm/llvm-project/issues/165780

Fixes: https://github.com/llvm/llvm-project/issues/164625. It brings down regression from **150% to 2%**.

---

### CODE REVIEW

File: clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp [hunk 1]
```diff
@@ -7,34 +7,100 @@
...
+  llvm::BitVector PersistentOrigins(FactMgr.getOriginMgr().getOrigins().size() +
+                                    1);
+
+  llvm::DenseMap<OriginID, const CFGBlock *> OriginToBlock;
+  for (const CFGBlock *B : C) {
+    for (const Fact *F : FactMgr.getFacts(B)) {
+      auto CheckOrigin = [&](OriginID OID) {
+        if (PersistentOrigins.test(OID.Value))
+          return;
+        auto It = OriginToBlock.find(OID);
```
Comment (Xazax-hun) [inline clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp]: Nit: we could use try_emplace to save lookup (id we don't want to switch to a vector).

File: clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp [hunk 2]
```diff
@@ -7,34 +7,100 @@
...
-/// not expressions, because expressions are not visible across blocks.
 struct Lattice {
   /// The map from an origin to the set of loans it contains.
-  OriginLoanMap Origins = OriginLoanMap(nullptr);
-
-  explicit Lattice(const OriginLoanMap &S) : Origins(S) {}
+  /// Origins that appear in multiple blocks. Participates in join operations.
+  OriginLoanMap PersistentOrigins = OriginLoanMap(nullptr);
+  /// Origins confined to a single block. Discarded at block boundaries.
+  OriginLoanMap BlockLocalOrigins = OriginLoanMap(nullptr);
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp]: 1. These are shallow copies. So each program point in a block gets a shallow copy of the block-local origins.
2. I still want to make it part of the lattice to answer `getLoans(OriginID OID, ProgramPoint P)` at all `P` and for all `OID`.

Slightly related: Note that this approach is different from treating origins for expressions differently (which may follow ssa within a block).
In the current approach, even declaration which belong to single block which do not follow single assignment can also be a block-local origin. So even block-local origins can have different loans at different program points.

**Review by Xazax-hun — APPROVED** [review]
This looks great, thanks!

**Review by mrcvtl — COMMENTED** [review]
Really nice! I left a comment while I was taking a look at the changes.

File: clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp [hunk 3]
```diff
@@ -5,36 +5,114 @@
...
+  llvm::BitVector PersistentOrigins(NumOrigins);
+
+  llvm::SmallVector<const CFGBlock *> OriginToFirstSeenBlock(NumOrigins,
+                                                             nullptr);
+  for (const CFGBlock *B : C) {
+    for (const Fact *F : FactMgr.getFacts(B)) {
+      auto CheckOrigin = [&](OriginID OID) {
+        if (PersistentOrigins.test(OID.Value))
+          return;
+        auto &FirstSeenBlock = OriginToFirstSeenBlock[OID.Value];
```
Comment (ymand) [inline clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp]: nit: could you instead just count the occurences of each origin and then, after visiting all blocks in `C`, any origin with count > 1 are persistent?

File: clang/unittests/Analysis/LifetimeSafetyTest.cpp [hunk 4]
```diff
@@ -543,7 +543,6 @@ TEST_F(LifetimeAnalysisTest, PointersInACycle) {
   EXPECT_THAT(Origin("p1"), HasLoansTo({"v1", "v2", "v3"}, "after_loop"));
   EXPECT_THAT(Origin("p2"), HasLoansTo({"v1", "v2", "v3"}, "after_loop"));
   EXPECT_THAT(Origin("p3"), HasLoansTo({"v1", "v2", "v3"}, "after_loop"));
-  EXPECT_THAT(Origin("temp"), HasLoansTo({"v1", "v2", "v3"}, "after_loop"));
```
Comment (ymand) [inline clang/unittests/Analysis/LifetimeSafetyTest.cpp]: Is there a way to test that Origin("temp") is gone?

File: clang/unittests/Analysis/LifetimeSafetyTest.cpp [hunk 5]
```diff
@@ -543,7 +543,6 @@ TEST_F(LifetimeAnalysisTest, PointersInACycle) {
...
 }
```
Comment (ymand) [inline clang/unittests/Analysis/LifetimeSafetyTest.cpp]: Is there a way to test that Origin("temp") is gone?

**Review by ymand — APPROVED** [review]
asked about 2 possible changes, but fine going in as is. Thanks!

File: clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp [hunk 6]
```diff
@@ -5,36 +5,114 @@
...
-/// not expressions, because expressions are not visible across blocks.
 struct Lattice {
   /// The map from an origin to the set of loans it contains.
-  OriginLoanMap Origins = OriginLoanMap(nullptr);
-
-  explicit Lattice(const OriginLoanMap &S) : Origins(S) {}
+  /// Origins that appear in multiple blocks. Participates in join operations.
+  OriginLoanMap PersistentOrigins = OriginLoanMap(nullptr);
+  /// Origins confined to a single block. Discarded at block boundaries.
+  OriginLoanMap BlockLocalOrigins = OriginLoanMap(nullptr);
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/lib/Analysis/LifetimeSafety/LoanPropagation.cpp]: Yes it is possible to do so. There are some benefits of doing so: we can delete more than just block-local origins, we can delete all origins which are dead (using the liveness analysis).

But I would prefer not to do "deletions" though as they are both expensive (logarithmic) + create a lot of holes in the buffer backing the trees and make it quite sparse (the number of deleted origins would be much higher than the persistent origins). 
So I feel the current approach is both simple and efficient in time and memory layout.

File: clang/unittests/Analysis/LifetimeSafetyTest.cpp (hunk 5 above)
Comment (usx95) [reply clang/unittests/Analysis/LifetimeSafetyTest.cpp]: Added   `EXPECT_THAT(Origin("temp"), HasLoansTo({}, "after_loop"));` to test that origin's loanset is dropped.
