### PR TITLE
[mlir][linalg] Preserve cast semantics during generic to matmul

### LINKED ISSUE #174517: [MLIR] `-linalg-specialize-generic-ops` causes wrong-code for `linalg.matmul`
**test commit**: [5cfd02](https://github.com/llvm/llvm-project/commit/5cfd02f44a43a2e2a085a633b022a62f64ba2b93)

## Description:
I found a miscompilation issue in MLIR where adding -linalg-specialize-generic-ops to an otherwise identical lowering pipeline changes the numerical result of a linalg.matmul.

## test case
```
#map = affine_map<(d0, d1, d2) -> (d0, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d2, d1)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
module {
  memref.global "private" constant @__constant_16x32xi32 : memref<16x32xi32> = dense<130> {alignment = 64 : i64}
  memref.global "private" constant @__constant_8x32xi64 : memref<8x32xi64> = dense<159> {alignment = 64 : i64}
  memref.global "private" constant @__constant_16x8xi16 : memref<16x8xi16> = dense<-50> {alignment = 64 : i64}
  func.func private @printMemrefI32(memref<*xi32>)
  func.func @main() {
    %0 = memref.get_global @__constant_16x8xi16 : memref<16x8xi16>
    %1 = memref.get_global @__constant_8x32xi64 : memref<8x32xi64>
    %2 = memref.get_global @__constant_16x32xi32 : memref<16x32xi32>
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<16x32xi32>
    memref.copy %2, %alloc : memref<16x32xi32> to memref<16x32xi32>
    linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]} ins(%0, %1 : memref<16x8xi16>, memref<8x32xi64>) outs(%alloc : memref<16x32xi32>) {
    ^bb0(%in: i16, %in_0: i64, %out: i32):
      %3 = arith.extui %in : i16 to i32
      %4 = arith.trunci %in_0 : i64 to i32
      %5 = arith.muli %3, %4 : i32
      %6 = arith.addi %out, %5 : i32
      linalg.yield %6 : i32
    }
    %cast = memref.cast %alloc : memref<16x32xi32> to memref<*xi32>
    call @printMemrefI32(%cast) : (memref<*xi32>) -> ()
    return
  }
}
```

### 1. without -linalg-specialize-generic-ops

```
mlir-opt test.mlir -convert-linalg-to-affine-loops -lower-affine -convert-scf-to-cf -convert-to-llvm |  mlir-runner -e main -entry-point-result=void -shared-libs=/home/workdir/llvm-project-latest/build/lib/libmlir_runner_utils.so
```

### output:
```
[83298322,   83298322,   83298322,   83298322,   83298322,   83298322,   83298322,   83298322,   ...]]
```
### 2. With -linalg-specialize-generic-ops:

```
mlir-opt test.mlir -linalg-specialize-generic-ops -convert-linalg-to-affine-loops -lower-affine -convert-scf-to-cf -convert-to-llvm |  mlir-runner -e main -entry-point-result=void -shared-libs=/home/workdir/llvm-project-latest/build/lib/libmlir_runner_utils.so
```
### output:
```
[-63470,   -63470,   -63470,   -63470,   -63470,   -63470,   -63470,   -63470,   -63470,   -63470,   ...]]
```

### PR DESCRIPTION
**Pull request by meshtag**
Infer signed/unsigned cast intent from cast ops in linalg.generic bodies and
propagate it via the matmul cast attribute. This could otherwise lead to
silent overflow/underflow errors in e2e execution.

TODO: Extend this to other named ops that support cast attribute.

Fixes a functional bug in the attached issue.

Fixes #174517

### CODE REVIEW

File: mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp [hunk 1]
```diff
@@ -134,14 +135,72 @@ static IndexMatchResult matchOperandMap(AffineMap map, unsigned rowDimIdx,
 //  All the variants expressed as pseudo regular expression:
 //      `linalg.{batch_}?matmul{_transpose_a | _transpose_b}?`
 //  have same number of ins/out, so its easy to stamp different versions.
```
Comment (adam-smnk) [inline mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp]: nit: not related to PR but as we're already here, could you align the whole comment block to have one space after `//`?

File: mlir/test/Dialect/Linalg/specialize-generic-ops.mlir [hunk 2]
```diff
@@ -124,3 +124,126 @@ func.func @op_matvec(%A: tensor<?x?xf32>, %B: tensor<?xf32>, %Out: tensor<?xf32>
...
+// CHECK-LABEL: op_matmul_mixed_cast
+// CHECK: linalg.generic
+// CHECK-NOT: linalg.matmul
+
+// -----
+
+#map = affine_map<(d0, d1, d2) -> (d0, d2)>
+#map1 = affine_map<(d0, d1, d2) -> (d2, d1)>
+#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
+func.func @op_matmul_output_cast(%A: tensor<16x8xi16>, %B: tensor<8x32xi16>,
```
Comment (adam-smnk) [inline mlir/test/Dialect/Linalg/specialize-generic-ops.mlir]: nit: use prefix `@negative_` for test cases that don't match, see other tests in the file

**Review by adam-smnk — COMMENTED** [review]
Thanks for making the linalg morphism more robust 👍

Could you also add a related roundtrip test?
Maybe to `roundtrip-linalg-named-ops.mlir`.

File: mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp [hunk 3]
```diff
@@ -131,17 +132,75 @@ static IndexMatchResult matchOperandMap(AffineMap map, unsigned rowDimIdx,
...
+// attribute is needed for the named matmul op.
 template <typename NamedOpTy>
-static LinalgOp replaceWithMatmulVariant(RewriterBase &rewriter, GenericOp op) {
+static LinalgOp replaceWithMatmulVariant(RewriterBase &rewriter, GenericOp op,
+                                         std::optional<TypeFn> castTy) {
+  SmallVector<NamedAttribute> castAttrVec;
+  // Only explicitly specify the cast attribute if the cast type exists and is
+  // pointing to unsigned cast (the default is signed cast for
+  // linalg.matmul/linalg.batch_matmul).
+  if (castTy.has_value() && *castTy == TypeFn::cast_unsigned)
```
Comment (banach-space) [inline mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp]: Should we special case for the unsigned cast? What if the default changes? 

I feel that we may as well just skip this, keep the code a bit shorter and more future proof, no?

@adam-smnk , wdyt?

File: mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp [hunk 4]
```diff
@@ -131,17 +132,75 @@ static IndexMatchResult matchOperandMap(AffineMap map, unsigned rowDimIdx,
...
       op, ValueRange{op.getDpsInputs()[0], op.getDpsInputs()[1]},
-      ValueRange{op.getDpsInits()[0]});
+      ValueRange{op.getDpsInits()[0]}, castAttrVec);
   return namedOp;
 }
 
+// Determines the required cast type for the specialized matmul op (if any)
+// which is expressed in the form of the input linalg.generic op. Also audits
+// that there are no invalid cast ops for matmul inputs/outputs which can't be
+// expressed using the specialized op.
```
Comment (banach-space) [inline mlir/lib/Dialect/Linalg/Transforms/Specialize.cpp]: Hm, this sounds a bit convoluted.

Shouldn't the return value be std::optional and then:
* if this is a matmul like Op, the return value is set
* otherwise the return value would  be empty.

Then, also rename it as `getCastTypeForMatmulLikeOp`.

**Review by banach-space — COMMENTED** [review]
I've left a few minor suggestions inline, thanks!

**Review by CoTinker — APPROVED** [review]

File: mlir/test/Dialect/Linalg/specialize-generic-ops.mlir [hunk 5]
```diff
@@ -58,8 +62,118 @@ func.func @op_matmul(%A: tensor<?x?xf32>, %B: tensor<?x?xf32>, %Out: tensor<?x?x
...
+   } -> tensor<16x32xi64>
+   return %0 : tensor<16x32xi64>
+}
+
+// CHECK-LABEL: negative_op_matmul_output_cast
+// CHECK: linalg.generic
+// CHECK-NOT: linalg.matmul
+
+// Bitcasts are not modeled by the cast attribute, but should not block
+// specialization.
```
Comment (banach-space) [inline mlir/test/Dialect/Linalg/specialize-generic-ops.mlir]: Very interesting example, thanks!

> should not block specialization

Not sure about this 🤔 What is it specialised to?

File: mlir/test/Dialect/Linalg/specialize-generic-ops.mlir [hunk 6]
```diff
@@ -58,8 +62,118 @@ func.func @op_matmul(%A: tensor<?x?xf32>, %B: tensor<?x?xf32>, %Out: tensor<?x?x
...
+
+// Check matmul with unsigned cast is correctly raised back to named op.
+func.func @op_matmul_unsigned_cast(%A: tensor<16x8xi16>, %B: tensor<8x32xi64>,
+                                   %Out: tensor<16x32xi32>) -> tensor<16x32xi32> {
+  %0 = linalg.generic
+         {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]}
+         ins(%A, %B : tensor<16x8xi16>, tensor<8x32xi64>) outs(%Out : tensor<16x32xi32>) {
+   ^bb0(%in: i16, %in_0: i64, %out: i32):
+     %1 = arith.extui %in : i16 to i32
+     %2 = arith.trunci %in_0 : i64 to i32
```
[the remark this answers is not in the document]
Comment (meshtag) [reply mlir/test/Dialect/Linalg/specialize-generic-ops.mlir]: We only consider casts as conflicting if they have different signedness behaviours, and then we do not specialise if they do conflict. Since this is not such a case, we do not block specialisation. Also the roundtrip lowering back to linalg.generic for such an op is expected to produce the same thing again, so we are not loosing information here.

For example: 
```
%0 = linalg.generic
         {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]}
         ins(%A, %B : tensor<16x8xi16>, tensor<8x32xi64>) outs(%Out : tensor<16x32xi32>) {
   ^bb0(%in: i16, %in_0: i64, %out: i32):
     %1 = arith.extui %in : i16 to i32
     %2 = arith.trunci %in_0 : i64 to i32
     %3 = arith.muli %1, %2 : i32
     %4 = arith.addi %out, %3 : i32
     linalg.yield %4 : i32
   } -> tensor<16x32xi32>
``` 
with `--linalg-specialize-generic-ops` becomes 
```
%0 = linalg.matmul {cast = #linalg.type_fn<cast_unsigned>} ins(%arg0, %arg1 : tensor<16x8xi16>, tensor<8x32xi64>) outs(%arg2 : tensor<16x32xi32>) -> tensor<16x32xi32>
```
and applying `-linalg-generalize-named-ops` on the above gives
```
%0 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]} ins(%arg0, %arg1 : tensor<16x8xi16>, tensor<8x32xi64>) outs(%arg2 : tensor<16x32xi32>) {
    ^bb0(%in: i16, %in_0: i64, %out: i32):
      %1 = arith.extui %in : i16 to i32
      %2 = arith.trunci %in_0 : i64 to i32
      %3 = arith.muli %1, %2 : i32
      %4 = arith.addi %out, %3 : i32
      linalg.yield %4 : i32
    } -> tensor<16x32xi32>
```

So we did not loose any information here.

**Review by adam-smnk — APPROVED** [review]
