### PR TITLE
[LoongArch] Fix '-mno-lsx' option not disabling LASX feature

### LINKED ISSUE #95: GCC and Clang have different priorities between -march and -mno-lsx
Here's the test program,

```C
#if __loongarch_sx
        LSX
#else
        NO LSX
#endif
#if __loongarch_asx
        LASX
#else
        NO LASX
#endif
```

Clang-18 produces obviously wrong result when both `-march=la464` and `-mno-lsx` are specified,

```shell
$ clang-18 test.c -E -mno-lsx -march=la464 | grep L
 NO LSX
 LASX
```

Both GCC 14 and Clang 20 produce reasonable results that are unaffected by the order between `-march=la464` and `-mno-lsx`, but the two results differ,

```
$ gcc test.c -E -mno-lsx -march=la464 | grep L
 NO LSX
 NO LASX
$ clang-20 test.c -E -march=la464 -mno-lsx | grep L
 LSX
 LASX
```

IOW, gcc treats `-mno-lsx` with higher priority than `-march-la464`, while Clang-20 does the opposite.

According to la-toolchain-convention[1],

> 2. `-march=` and `-mabi=` always precede other options.

I think the behavior of Clang-20 is correct. This difference affects firefox 139.0,1 (and possibly earlier versions) build with Clang-20 on eweOS, where the buildscript intends to disable LSX for libyuv[2] but actually fails to do so. `-march` flags supplied by the distribution will instruct libyuv to use SIMD-accelerated symbols which won't be really compiled, resulting in linking failures.

[1]: https://github.com/loongson/la-toolchain-conventions/blob/398e888ab72032b5fba93b0cf179eafe1867ddac/LoongArch-toolchain-conventions-EN.adoc?plain=1#L199
[2]: https://hg-edge.mozilla.org/mozilla-central/file/dc8e8233c9e7bdcffaceb77daba71d994e65c68d/media/libyuv/04_fix_loongarch64_link_failed.patch

### PR DESCRIPTION
**Pull request by Ami-zhang**
When '-march' with LASX feature and '-mno-lsx' options are used together, '-mno-lsx' fails to disable LASX, leaving 'HasFeatureLASX=true' and causing incorrect '__loongarch_sx/asx=1' macro definition.

Fixes https://github.com/loongson-community/discussions/issues/95

### CODE REVIEW

File: clang/test/Preprocessor/init-loongarch.c [hunk 1]
```diff
@@ -946,6 +946,8 @@
 // RUN:   | FileCheck --match-full-lines --check-prefix=MNO-LSX %s
 // RUN: %clang --target=loongarch64 -mno-lasx -mno-lsx -x c -E -dM %s -o - \
 // RUN:   | FileCheck --match-full-lines --check-prefix=MNO-LSX %s
+// RUN: %clang --target=loongarch64 -march=la464 -mno-lsx -x c -E -dM %s -o - \
+// RUN:   | FileCheck --match-full-lines --check-prefix=MNO-LSX %s
```
Comment (SixWeining) [inline clang/test/Preprocessor/init-loongarch.c:950]: Also test switching these 2 options's order (i.e. `-mno-lsx -march=la464`).

Comment (Ami-zhang) [reply clang/test/Preprocessor/init-loongarch.c:950]: Ok, done.

**Review by SixWeining — APPROVED** [review]
