### PR TITLE
[lldb][intel-pt] Fix build error on conversion from llvm::Error to Status::FromError

### LINKED ISSUE #107580: lldb fails to build on `CommandObjectTraceStartIntelPT.cpp:81:21: error: calling a protected constructor of class 'lldb_private::Status'`
On trunk, Debian amd64:

```
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o
/opt/sccache//sccache /build/source/build-llvm/bin/clang++ -DHAVE_ROUND -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/build-llvm/tools/clang/stage2-bins/tools/lldb/source/Plugins/Trace/intel-pt -I/build/source/lldb/source/Plugins/Trace/intel-pt -I/build/source/lldb/include -I/build/source/build-llvm/tools/clang/stage2-bins/tools/lldb/include -I/build/source/build-llvm/tools/clang/stage2-bins/include -I/build/source/llvm/include -I/usr/include/python3.12 -I/build/source/clang/include -I/build/source/build-llvm/tools/clang/stage2-bins/tools/lldb/../clang/include -I/build/source/lldb/source -I/build/source/build-llvm/tools/clang/stage2-bins/tools/lldb/source -isystem /usr/include/libxml2 -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/source/build-llvm/tools/clang/stage2-bins=../../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O2 -DNDEBUG -g1 -std=c++17  -fno-exceptions -funwind-tables -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o -c /build/source/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp
/build/source/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp:81:21: error: calling a protected constructor of class 'lldb_private::Status'
   81 |     result.SetError(Status(std::move(err)));
      |                     ^
/build/source/lldb/include/lldb/Utility/Status.h:173:3: note: declared protected here
  173 |   Status(llvm::Error error);
      |   ^
/build/source/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp:167:21: error: calling a protected constructor of class 'lldb_private::Status'
  167 |     result.SetError(Status(std::move(err)));
      |                     ^
/build/source/lldb/include/lldb/Utility/Status.h:173:3: note: declared protected here
  173 |   Status(llvm::Error error);
      |   ^
2 errors generated.
```

Log:
https://llvm-jenkins.debian.net/job/llvm-toolchain-binaries/architecture=amd64,distribution=unstable,label=amd64/2010/console

### PR DESCRIPTION
**Pull request by kusmour**
Summary: This introduced from upstream [#107163](https://github.com/llvm/llvm-project/pull/107163)

Test Plan: I can build

Closes: #107580

### CODE REVIEW

**Comment by Jlalond** [comment]
Hey @kusmour. I actually looked into this on Thursday, see #108248. If we are going to merge this I think we should just call `std::move` and not `Status::FromError(std::move(err))` as the API takes an err r-value.

**Review by walter-erquinigo — APPROVED** [review]

File: lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp [hunk 1]
```diff
@@ -78,7 +78,7 @@ bool CommandObjectThreadTraceStartIntelPT::DoExecuteOnThreads(
     llvm::ArrayRef<lldb::tid_t> tids) {
   if (Error err = m_trace.Start(tids, m_options.m_ipt_trace_size,
                                 m_options.m_enable_tsc, m_options.m_psb_period))
-    result.SetError(Status(std::move(err)));
+    result.SetError(Status::FromError(std::move(err)));
```
Comment (walter-erquinigo) [inline lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp:81]: just make sure that you really need to invoke std::move. It's possible that the compiler can do that on its own and that you don't need the explicit std::move

**Review by Jlalond — APPROVED** [review]
