### PR TITLE
[RISCV][Sema] Add feature check for target attribute to VSETVL intrinsics

### LINKED ISSUE #125154: __riscv_vsetvlmax_e64m1 & co not available with attribute target arch=+v
Copying out of https://github.com/llvm/llvm-project/issues/56592:

The following fails to compile with `-march=rv64gc`, despite working with `-march=rv64gcv`, which should be what the `__attribute__` achieves:

```
#include<riscv_vector.h>

__attribute__((target("arch=+v")))
int vl_e64m1() {
    return __riscv_vsetvlmax_e64m1();
}
```
https://godbolt.org/z/rPnh5zYE5

I believe this would be because these definitions are preprocessor-gated: https://github.com/llvm/llvm-project/blob/33c42f8bc5615b4dc46cb45ab41da97be52474ec/clang/include/clang/Basic/riscv_vector.td#L637-L675

### PR DESCRIPTION
**Pull request by 4vtomat**
This fixes the target attribute issue for vsetvl and vsetvlmax
intrinsics.
Fixes #125154

### CODE REVIEW

File: clang/lib/Sema/SemaRISCV.cpp [hunk 1]
```diff
@@ -623,13 +623,37 @@ bool SemaRISCV::CheckBuiltinFunctionCall(const TargetInfo &TI,
...
+    llvm::APSInt LMULResult;
+    if (SemaRef.BuiltinConstantArg(TheCall, SEWOffset, SEWResult) ||
+        SemaRef.BuiltinConstantArg(TheCall, LMULOffset, LMULResult))
+      return true;
+    int SEWValue = SEWResult.getSExtValue();
+    int LMULValue = LMULResult.getSExtValue();
+    if (((SEWValue == 0 && LMULValue == 5) ||  // e8mf8
+         (SEWValue == 1 && LMULValue == 6) ||  // e16mf4
+         (SEWValue == 2 && LMULValue == 7) ||  // e32mf2
+         (SEWValue == 3 && LMULValue == 0) ||  // e64m1
```
Comment (topperc) [inline clang/lib/Sema/SemaRISCV.cpp:641]: You don't need to check the LMULValue when SEWValue == 3.

File: clang/lib/Sema/SemaRISCV.cpp [hunk 2]
```diff
@@ -623,13 +623,37 @@ bool SemaRISCV::CheckBuiltinFunctionCall(const TargetInfo &TI,
...
+         (SEWValue == 3 && LMULValue == 1) ||  // e64m2
+         (SEWValue == 3 && LMULValue == 2) ||  // e64m4
+         (SEWValue == 3 && LMULValue == 3)) && // e64m8
+        (!TI.hasFeature("zve64x") && !FunctionFeatureMap.lookup("zve64x")))
```
Comment (tclin914) [inline clang/lib/Sema/SemaRISCV.cpp:645]: Should we check for the feature `zvl64b`?

Comment (topperc) [reply clang/lib/Sema/SemaRISCV.cpp:645]: The requirements for supported vtypes is a function of ELEN not VLEN. A Zvl64b+Zve32x implementation may support `e8,mf8`, `e16,mf4`, `e32,mf2` but it not required by the spec so the code would not be portable.

File: clang/lib/Sema/SemaRISCV.cpp [hunk 3]
```diff
@@ -623,13 +623,37 @@ bool SemaRISCV::CheckBuiltinFunctionCall(const TargetInfo &TI,
   }
   }
 
+  auto checkVsetvl = [&](unsigned SEWOffset,
```
Comment (wangpc-pp) [inline clang/lib/Sema/SemaRISCV.cpp:626]: checkVsetvl -> CheckVSetVL?  At least the first letter should be capital.

File: clang/lib/Sema/SemaRISCV.cpp [hunk 4]
```diff
@@ -623,13 +623,37 @@ bool SemaRISCV::CheckBuiltinFunctionCall(const TargetInfo &TI,
...
+                                        unsigned LMULOffset) -> bool {
+    const FunctionDecl *FD = SemaRef.getCurFunctionDecl();
+    llvm::StringMap<bool> FunctionFeatureMap;
```
Comment (wangpc-pp) [inline clang/lib/Sema/SemaRISCV.cpp:629]: Is there a way to cache this? I don't think we need to re-compute every time.

File: clang/lib/Sema/SemaRISCV.cpp [hunk 5]
```diff
@@ -623,13 +623,37 @@ bool SemaRISCV::CheckBuiltinFunctionCall(const TargetInfo &TI,
   }
   }
 
+  auto checkVsetvl = [&](unsigned SEWOffset,
+                                        unsigned LMULOffset) -> bool {
```
[the remark this answers is not in the document]
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:627]: I think it's not lol

File: clang/lib/Sema/SemaRISCV.cpp (hunk 1 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:641]: Oh I see, let me remove it

File: clang/lib/Sema/SemaRISCV.cpp (hunk 3 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:626]: Agree, let me change it~

File: clang/lib/Sema/SemaRISCV.cpp (hunk 4 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:629]: Maybe it can be constructed at the entry of `CheckBuiltinFunctionCall`, let me refactor it

File: clang/lib/Sema/SemaRISCV.cpp (hunk 3 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:626]: wait I have a question, is lambda treated as a function or a variabl, the reason I make first character lower case is because I treated it as a function lol

Comment (wangpc-pp) [reply clang/lib/Sema/SemaRISCV.cpp:626]: I think it is a variable, most lambdas in tree are capital. :-)

File: clang/lib/Sema/SemaRISCV.cpp (hunk 4 above)
Comment (wangpc-pp) [reply clang/lib/Sema/SemaRISCV.cpp:629]: Put it at the entry of `CheckBuiltinFunctionCall` may not be enough, we still need to construct the feature map for each builtin inside a function. This map should be constructed when entering a function scope.

File: clang/lib/Sema/SemaRISCV.cpp (hunk 3 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:626]: I see, let me change the case

File: clang/lib/Sema/SemaRISCV.cpp (hunk 4 above)
Comment (4vtomat) [reply clang/lib/Sema/SemaRISCV.cpp:629]: Yeah agree

Comment (wangpc-pp) [reply clang/lib/Sema/SemaRISCV.cpp:628]: OK, it can be a future compile-time optimization. We may just cache then result in `getFunctionFeatureMap`.

**Comment by 4vtomat** [comment]
Ping~

**Review by wangpc-pp — APPROVED** [review]
LGTM.
