### PR TITLE
[clang-tidy] Fix false positive for constrained template parameters in `cppcoreguidelines-missing-std-forward`

### LINKED ISSUE #180362: [clang-tidy] false positive on cppcoreguidelines-missing-std-forward with constrained templates
```cpp
#include <concepts>

class A
{
public:
    template <std::derived_from<A> Self>
    auto operator|(this Self &&self, int) -> void {}
};

auto main() -> int
{
    A a;
    a | 1;
}
```

`Self` is a regular rvalue reference and not a forwarding reference in `A::operator|` because of the constraint (and as seen by the compiler error in `main`), but clang-tidy will still warn [cppcoreguidelines-missing-std-forward](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/missing-std-forward.html) on this.

### PR DESCRIPTION
**Pull request by Aditya26189**
Explicit object parameters with a type constraint are skipped to avoid false positives. They are technically still forwarding references per [temp.deduct.call], but rarely intended to be perfectly forwarded.

Fixes #180362

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+template <typename T> struct remove_reference<T&&> { using type = T; };
+
+template <typename T> using remove_reference_t = typename remove_reference<T>::type;
+
+template <typename T> constexpr T &&forward(remove_reference_t<T> &t) noexcept;
+template <typename T> constexpr T &&forward(remove_reference_t<T> &&t) noexcept;
+template <typename T> constexpr remove_reference_t<T> &&move(T &&x);
+
+template <class T, class U>
+concept derived_from = __is_base_of(U, T);
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp]: Can we not use compiler build-ins,
We can just leave it to anything, no need for real behavoir

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+// Tests for constrained template parameters (GH#180362).
+
+class GH180362_A {
+public:
+  template <std::derived_from<GH180362_A> Self>
+  auto operator|(this Self &&self, int) -> void {}
+};
+
+template <std::integral T>
+void gh180362_takes_integral(T &&t) {}
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp]: This seems like a false negative, but I may have bad knowledge of constraints

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp [hunk 3]
```diff
@@ -0,0 +1,49 @@
+// RUN: %check_clang_tidy -std=c++23 %s cppcoreguidelines-missing-std-forward %t -- -- -fno-delayed-template-parsing
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp]:
```suggestion
// RUN: %check_clang_tidy -std=c++23-or-later %s cppcoreguidelines-missing-std-forward %t -- -- -fno-delayed-template-parsing
```

**Review by zeyi2 — APPROVED** [review]
LGTM with a nit :)

File: clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  template <typename Self>
+    requires std::derived_from<Self, GH180362_D>
+  void baz(this Self &&self) {}
+  // CHECK-MESSAGES: :[[@LINE-1]]:24: warning: forwarding reference parameter 'self' is never forwarded inside the function body [cppcoreguidelines-missing-std-forward]
+};
+
+// Constrained non-explicit-object parameter IS still a forwarding reference.
+template <std::integral T>
+void gh180362_takes_integral(T &&t) {}
+// CHECK-MESSAGES: :[[@LINE-1]]:34: warning: forwarding reference parameter 't' is never forwarded inside the function body [cppcoreguidelines-missing-std-forward]
```
[the remark this answers is not in the document]
Comment (Aditya26189) [reply clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/missing-std-forward-cxx23.cpp]: Done

**Review by zeyi2 — APPROVED** [review]
LGTM, thanks!
