### PR TITLE
[BDCE] Avoid replacement of self-referential instructions 

### LINKED ISSUE #194564: BDCE crashes with 'Assertion `!contains(New, this) && "this->replaceAllUsesWith(expr(this)) is NOT valid!"' failed.'
llvm commit: 4f6b1b01f62
Reproduce with:
```opt -passes="bdce" bbi-117102.ll -o /dev/null```
Result:
```
opt: /repo/uabelho/main-github/llvm/lib/IR/Value.cpp:521: void llvm::Value::doRAUW(Value *, ReplaceMetadataUses): Assertion `!contains(New, this) && "this->replaceAllUsesWith(expr(this)) is NOT valid!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes=bdce bbi-117102.ll -o /dev/null
1.	Running pass "function(bdce)" on module "bbi-117102.ll"
2.	Running pass "bdce" on function "func_1"
 #0 0x000055b9098cf236 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x51ee236)
 #1 0x000055b9098cbea1 llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x51eaea1)
 #2 0x000055b9098d0489 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007fe74646c990 __restore_rt (/lib64/libpthread.so.0+0x12990)
 #4 0x00007fe743e0c5af raise (/lib64/libc.so.6+0x4e5af)
 #5 0x00007fe743ddfee5 abort (/lib64/libc.so.6+0x21ee5)
 #6 0x00007fe743ddfdb9 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21db9)
 #7 0x00007fe743e04f06 (/lib64/libc.so.6+0x46f06)
 #8 0x000055b9099a632a llvm::Value::doRAUW(llvm::Value*, llvm::Value::ReplaceMetadataUses) (build-all/bin/opt+0x52c532a)
 #9 0x000055b90b1f255e llvm::BDCEPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x6b1155e)
#10 0x000055b90ae42add llvm::detail::PassModel<llvm::Function, llvm::BDCEPass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#11 0x000055b909b02b55 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x5421b55)
#12 0x000055b90ae445fd llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#13 0x000055b909b0740e llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x542640e)
#14 0x000055b90add139d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) NewPMDriver.cpp:0:0
#15 0x000055b909b01845 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x5420845)
#16 0x000055b90adc98a1 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool, bool) (build-all/bin/opt+0x66e88a1)
#17 0x000055b90986daf0 optMain (build-all/bin/opt+0x518caf0)
#18 0x00007fe743df8865 __libc_start_main (/lib64/libc.so.6+0x3a865)
#19 0x000055b90986b06e _start (build-all/bin/opt+0x518a06e)
Abort (core dumped)
```
The is rather old, I've reproduced it with binaries from late january 2024.

Originally found by running clang and opt with a random opt pipeline on a csmith program so I set the "generated by fuzzer" label.
The opt input contains a loop that is not reachable from the entry block:
```
define i64 @func_1() {
for.body933:
  ret i64 0

for.cond984:                                      ; preds = %for.cond984
  %or1039 = or i32 %or1039, 0
  %conv1003 = trunc i32 %or1039 to i16
  %call1004 = call i16 null(i16 0, i16 %conv1003)
  br label %for.cond984
}
```
[bbi-117102.ll.gz](https://github.com/user-attachments/files/27155048/bbi-117102.ll.gz)
https://godbolt.org/z/esGT5vYao

```

### PR DESCRIPTION
**Pull request by XChy**
Fixes #194564.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Can this be fixed more directly? This doesn't seem like a pass where handling of self-referential values is onerous.

File: llvm/lib/Transforms/Scalar/BDCE.cpp [hunk 1]
```diff
@@ -26,6 +27,7 @@
 #include "llvm/IR/PatternMatch.h"
 #include "llvm/Support/Debug.h"
 #include "llvm/Support/raw_ostream.h"
+#include "llvm/Transforms/Utils/BasicBlockUtils.h"
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/BDCE.cpp]: Not needed?

File: llvm/lib/Transforms/Scalar/BDCE.cpp
Comment (nikic) [inline llvm/lib/Transforms/Scalar/BDCE.cpp]: Would it be sufficient to only guard against `BO != BO->getOperand(0)` in this case? That seems to be the only one that could cause self-rauw.

File: llvm/lib/Transforms/Scalar/BDCE.cpp (hunk 1 above)
Comment (antoniofrighetto) [inline llvm/lib/Transforms/Scalar/BDCE.cpp]: Not needed anymore?

File: llvm/lib/Transforms/Scalar/BDCE.cpp
Comment (XChy) [reply llvm/lib/Transforms/Scalar/BDCE.cpp]: For this case and the sext to zext case, it is sufficient to guard against `BO != BO->getOperand(0)`.

File: llvm/test/Transforms/BDCE/dead-uses.ll [hunk 2]
```diff
@@ -101,3 +101,23 @@ define void @dead_use_invalidation(i32 %a) {
...
+; CHECK-NEXT:    [[CALL:%.*]] = call i16 null(i16 0, i16 [[CONV]])
+; CHECK-NEXT:    br label [[LOOP:%.*]]
+;
+entry:
+  ret i64 0
+
+loop:
+  %or = or i32 %or, 0
+  %conv = trunc i32 %or to i16
+  %call = call i16 null(i16 0, i16 %conv)
```
Comment (nikic) [inline llvm/test/Transforms/BDCE/dead-uses.ll]: Can you replace this weird null call with something like `call void @use(i16 %conv)`?

**Review by nikic — APPROVED** [review]
LGTM

**Comment by mikaelholmen** [comment]
Thanks!
