### PR TITLE
[DebugInfo][SimpleLoopUnswitch] Fix missing debug location updates

### LINKED ISSUE #97559: [DebugInfo][SimpleLoopUnswitch] Missing debug location updates (Part 1)
[**SimpleLoopUnswitch-L1248**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L1248C1-L1253C52)

```cpp
->    auto *MergePN =
          PHINode::Create(I.getType(), /*NumReservedValues*/ 2, ".us-phi");
      MergePN->insertBefore(MergeBB->getFirstInsertionPt());
      I.replaceAllUsesWith(MergePN);
      MergePN->addIncoming(&I, ExitBB);
      MergePN->addIncoming(&ClonedI, ClonedExitBB);
```

[**SimpleLoopUnswitch-L1310**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L1310)

```cpp
    ClonedTerminator->eraseFromParent();
->  BranchInst::Create(ClonedSuccBB, ClonedParentBB);
```

[**SimpleLoopUnswitch-L2339**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L2339)

This instruction `TI` is moved out of the loop (i.e., the hoisted conditional instruction in LoopUnswitch) without dropping its debug location.

```cpp
    TI.moveBefore(*SplitBB, SplitBB->end());
```

[**SimpleLoopUnswitch-L2352**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L2352)

```cpp
      Value *Cond = skipTrivialSelect(BI->getCondition());
      if (InsertFreeze)
->      Cond = new FreezeInst(Cond, Cond->getName() + ".fr", BI->getIterator());
      BI->setCondition(Cond);
```

[**SimpleLoopUnswitch-L2440**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L2440)

```cpp
    // After MSSAU update, remove the cloned terminator instruction NewTI.
    ParentBB->getTerminator()->eraseFromParent();

    // Create a new unconditional branch to the continuing block (as opposed to
    // the one cloned).
->  BranchInst::Create(RetainedSuccBB, ParentBB);
```

[**SimpleLoopUnswitch-L2709**](https://github.com/llvm/llvm-project/blob/298e292a76289d93f7c1a80c26e354830c6080e4/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L2709)

```cpp
->  PHINode *Phi =
        PHINode::Create(SI->getType(), 2, "unswitched.select", SI->getIterator());
    Phi->addIncoming(SI->getTrueValue(), ThenBB);
    Phi->addIncoming(SI->getFalseValue(), HeadBB);
    SI->replaceAllUsesWith(Phi);
    SI->eraseFromParent();
```

godbolt: https://godbolt.org/z/dGGs89eKT (Note that the hoisted br instruction with `!dbg !8` in `%entry` is corresponding to L2339 and other instructions without `!dbg` are corresponding to other Lxxx)

### PR DESCRIPTION
**Pull request by Apochens**
Fix #97559 .

For the change at line 1253, I propagate the debug location of the terminator (i.e., the insertion point) to the new phi. because `MergeBB` is generated by splitting `ExitBB` several lines above, it only has the terminator, which could provide a reasonable debug location.

For the change at line 2348, I switch the order of moving and cloning `TI`. Because `NewTI` cloned from `TI` is inserted into the original place where `TI` is, `NewTI` should preserve the origianl debug location. At the same time, doing this allows us to propagate the debug location to the new branch instruction replacing `NewTI` (the change at line 2446).

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp [hunk 1]
```diff
@@ -2334,21 +2338,25 @@ static void unswitchNontrivialInvariants(
...
-    TI.moveBefore(*SplitBB, SplitBB->end());
-
     // Keep a clone of the terminator for MSSA updates.
     Instruction *NewTI = TI.clone();
     NewTI->insertInto(ParentBB, ParentBB->end());
 
+    // Splice the terminator from the original loop and rewrite its
+    // successors.
+    TI.moveBefore(*SplitBB, SplitBB->end());
+    TI.dropLocation();
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp:2348]: Why move this code down from where it was before?

File: llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp [hunk 2]
```diff
@@ -2334,21 +2338,25 @@ static void unswitchNontrivialInvariants(
...
     // First wire up the moved terminator to the preheaders.
     if (BI) {
       BasicBlock *ClonedPH = ClonedPHs.begin()->second;
       BI->setSuccessor(ClonedSucc, ClonedPH);
       BI->setSuccessor(1 - ClonedSucc, LoopPH);
       Value *Cond = skipTrivialSelect(BI->getCondition());
       if (InsertFreeze)
+        // We don't give any debug location to the new freeze, because the
+        // BI (`dyn_cast<BranchInst>(TI)`) is an in-loop instruction hoisted
+        // out of the loop.
```
Comment (OCHyams) [inline llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp:2359]: nit: Please either add braces around this or hoist the comment out the if statement (see second para [here](https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements)).

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+; Check that SimpleLoopUnswitch's unswitchNontrivialInvariants() drops the
+; debug location of the hoisted terminator and doesn't give any debug location
+; to the new freeze, since it's inserted in a hoist block.
+; Also check that in unswitchNontrivialInvariants(), the new br instruction
+; inherits the debug location of the old terminator in the same block.
+
+; CHECK:       entry:
+; CHECK-NEXT:    [[COND_FR:%.*]] = freeze i1 [[COND:%.*]]{{$}}
+; CHECK-NEXT:    br i1 [[COND_FR]], label %[[ENTRY_SPLIT_US:.*]], label %[[ENTRY_SPLIT:.*]]{{$}}
```
Comment (OCHyams) [inline llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:14]: Glancing at the IR, the old behaviour (new cond branch gets uncond branch location) looks fine, but I think this change does make sense - just to make sure I'm reading this right, is the argument here that the conditional branch above is essentially a `select` from within the loop that's been hoisted out? And that in this case the new branch would get the `select`'s source location, but because it has been hoisted out the loop we should actually drop it.

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+; CHECK:       for.body.us:
+; CHECK-NEXT:    br label %0, !dbg [[DBG13:![0-9]+]]
```
Comment (OCHyams) [inline llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:16]: I'm not 100% what's the correct thing to do for this one - if I'm reading it right this source location is from the `select`. What's the thinking behind you change for this one?

**Review by OCHyams — COMMENTED** [review]
This patch involves some slightly more complex updates than other recent fixes so I've just got a few questions inline to make sure I understand the it and to check that we're doing the right thing.

File: llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp [hunk 5]
```diff
@@ -1245,9 +1245,12 @@ static BasicBlock *buildClonedLoopBlocks(
       if (SE && isa<PHINode>(I))
         SE->forgetValue(&I);
 
+      Instruction *InsertPt = &*MergeBB->getFirstInsertionPt();
```
[the remark this answers is not in the document]
Comment (Apochens) [reply llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp:1248]: Oh, thanks for pointing out this. I'll fix it.

File: llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp (hunk 1 above)
Comment (Apochens) [reply llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp:2348]: `TI` is moved out of the loop and its debug location should be dropped. However, `NewTI` (the code moved up) which is cloned from `TI` should preserve `TI`'s debugl location, because `NewTI` is inserted into the original place where `TI` is at. In addition, `NewTI` will be replaced by a new branch instruction, which should inherit the debug location of `NewTI`.

So, I move the code down after the clone to preserve the debug location so that `NewTI` can preserve the right debug location while the debug location of `TI` can be correctly dropped.

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll (hunk 3 above)
Comment (Apochens) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:14]: This transformation is corresponding to the code change `TI.dropLocation()`. I traced the originality of `TI`:

(1) it the argument of function `unswitchNontrivialInvariants()`;
```cpp
static void unswitchNontrivialInvariants(
    Loop &L, Instruction &TI, ...)
```

(2) The function `unswitchNontrivialInvariants()` is called in function `unswitchBestCondition()`, and the `TI` argument takes `*Best.TI`. `Best` is the result of the function call to `findBestNonTrivialUnswitchCandidate()`, which return the best candidate from `UnswitchCandidates`. And `UnswitchCandidates` are collected by calling the function `collectUnswitchCandidates()`;

```cpp
static bool unswitchBestCondition(...) {
    ...
    collectUnswitchCandidates(UnswitchCandidates, ...);
    ...
    NonTrivialUnswitchCandidate Best = 
        findBestNonTrivialUnswitchCandidate(UnswitchCandidates, ...);
    ...
->  unswitchNontrivialInvariants(L, *Best.TI, ... );
}
```

(3) In function `collectUnswitchCandidates()`, instructions satisfying certain conditions will be added into `UnswitchCandidates`. According to the code, instructions added into `UnswitchCandidates` are all in the loop, including instructions in the header of the loop  (the code it too long to paste it here, see [L2912-2964](https://github.com/llvm/llvm-project/blob/385118644ccabe27a634804c7db60734746c170f/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L2912)).

To sum up, the conditional branch is essentially the hoisted instruction in the loop (it could be a `select`, a `branch`, or a `switch` according to the code).

> Glancing at the IR, the old behaviour (new cond branch gets uncond branch location) looks fine

Acctually, the new cond branch did not get the location of uncond branch. Before the dropping, there is no location propagation from the uncond branch to the new cond branch. See the following snippets ([godbolt](https://godbolt.org/z/3qa8PxoTc)). (Hope I understand `the old branch` right.)

```LLVM IR
entry:
  br label %for.cond, !dbg !8

!8 = !DILocation(line: 1, column: 1, scope: !5)
```

```LLVM IR
entry:
  %cond.fr = freeze i1 %cond
  br i1 %cond.fr, label %entry.split.us, label %entry.split, !dbg !8

!8 = !DILocation(line: 6, column: 1, scope: !5)
```

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll (hunk 4 above)
Comment (Apochens) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:16]: This debug location comes from the debug location update:

```cpp
  Instruction *BI = BranchInst::Create(ClonedSuccBB, ClonedParentBB);
  BI->setDebugLoc(ClonedTerminator->getDebugLoc());
  ClonedTerminator->eraseFromParent();
```

In the update, `BI` points the new br instruction. So, the debug location of `select` is propagated from `ClonedTerminator` to `BI`. To illustrate the instruction that `ClonedTerminator` points to, I paste the IR program before the remove of `ClonedTerminator` in the above code:

```LLVM IR
define i32 @basic(i32 %N, i1 %cond, i32 %select_input) !dbg !5 {
entry:
  br label %entry.split, !dbg !8

entry.split.us:                                   ; No predecessors!
  br label %for.cond.us, !dbg !8

for.cond.us:                                      ; preds = %1, %entry.split.us
  %res.us = phi i32 [ 0, %entry.split.us ], [ %add.us, %1 ], !dbg !9
  %i.us = phi i32 [ 0, %entry.split.us ], [ %inc.us, %1 ], !dbg !10
  %cmp.us = icmp slt i32 %i.us, %N, !dbg !11
  br i1 %cmp.us, label %for.body.us, label %for.cond.cleanup.split.us, !dbg !12

for.body.us:                                      ; preds = %for.cond.us
->br i1 %cond, label %0, label %1, !dbg !13    (ClonedTerminator)
  br label %0, !dbg !13.                                       (BI)

0:                                                ; preds = %for.body.us, %for.body.us
  br label %1, !dbg !13

1:                                                ; preds = %0, %for.body.us
  %unswitched.select.us = phi i32 [ %select_input, %0 ], !dbg !13
  %add.us = add nuw nsw i32 %unswitched.select.us, %res.us, !dbg !14
  %inc.us = add nuw nsw i32 %i.us, 1, !dbg !15
  br label %for.cond.us, !dbg !16

for.cond.cleanup.split.us:                        ; preds = %for.cond.us
  ...
}
```

I just propagate the debug location of the instruction pointed by `ClonedTerminator` to `BI`, and the reason why `ClonedTerminator` has the debug location of the `select` could be resulted by spliting the cloned for body (as the contents of block `%1` is actually the contents of `%for.body`).

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll (hunk 3 above)
Comment (OCHyams) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:14]: Thanks for digging in and confirming - this all makes sense and sounds right to me.

Just one thing:

> Actually, the new cond branch did not get the location of uncond branch. Before the dropping, there is no location propagation from the uncond branch to the new cond branch. See the following snippets ([godbolt](https://godbolt.org/z/3qa8PxoTc)). (Hope I understand the old branch right.)

In the two snippets you posted at the end of the last comment it looks like the unconditional branch's location `!8` (`br label %for.cond, !dbg !8`) gets propagated to the conditional branch `br i1 %cond.fr, label %entry.split.us, label %entry.split, !dbg !8` which seems to oppose what you're saying - I must've missed something here, are we talking about a different unconditional branch?

Comment (Apochens) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:14]: Oh, I think we are talking about the same unconditional branch and I did not state it clearly. The conditional branch in the second code snippet just has the same number of `!dbg` with the unconditional branch in the first code snippet, i.e., `!dbg !8`. However, `!dbg !8` in the first snippet points to line 1 while it points to line 6 in the second snippet. So, the debug location of the unconditional branch did not get propagated to the conditional branch (they just have the same metadata number).

Comment (OCHyams) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:14]: Oh that makes sense, thanks for the clarification.

File: llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll (hunk 4 above)
Comment (OCHyams) [reply llvm/test/Transforms/SimpleLoopUnswitch/preserving-dropping-debugloc-nontrivial.ll:16]: I see, thanks, yep that sounds ok.

**Review by OCHyams — APPROVED** [review]
LGTM, thanks for your patience and detailed explanations.
