### PR TITLE
[libc] Fix all imports of src/string/memory_utils

### LINKED ISSUE #86579: [libc] fix includes of src/__support/macros/config.h
A few of these are being cleaned up in #86554 so it's probably best for that to land first. But, I can see latent includes of src/__support/macros/config.h that look wrong, such as the one in libc/src/string/memory_utils/aarch64/inline_memcpy.h which has a comment that it includes that header for the definition of LIBC_INLINE.

LIBC_INLINE is defined in libc/src/__support/macros/attributes.h. As such libc/src/string/memory_utils/aarch64/inline_memcpy.h should include libc/src/__support/macros/attributes.h, not src/__support/macros/config.h and the corresponding cmake+bazel build rules fixed.

Probably there are other places too where a similar pattern is occurring and show be fixed up, too.

I suspect this is a fixup for 29f8e076bd427.

### PR DESCRIPTION
**Pull request by krishna2803**
Fixed imports for all files *within* `libc/src/string/memory_utils`.
Note: This doesn't include **all** files that need to be fixed.

Fixes #86579

### CODE REVIEW

**Review by nickdesaulniers — COMMENTED** [review]
ah, libc/src/__support/CMakeLists.txt the definition of the `common` header library (L54) is missing the dependency on config.h and attributes.h. It also falsely depends on endian.h, common.h, and cpu_features.h. That should get cleaned up in your PR.

Once that's cleaned up, then we can revisit changing the header source files.

File: libc/src/string/allocating_string_utils.h [hunk 1]
```diff
@@ -11,7 +11,7 @@
 
 #include "src/__support/CPP/new.h"
 #include "src/__support/CPP/optional.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/allocating_string_utils.h:14]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`.

File: libc/src/string/memory_utils/aarch64/inline_bcmp.h [hunk 2]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_AARCH64_INLINE_BCMP_H
 
 #include "src/__support/macros/attributes.h"   // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/aarch64/inline_bcmp.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/aarch64/inline_memset.h [hunk 3]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_AARCH64_INLINE_MEMSET_H
 
 #include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/aarch64/inline_memset.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/generic/builtin.h [hunk 4]
```diff
@@ -10,7 +10,6 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_GENERIC_BUILTIN_H
 
 #include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/generic/builtin.h:13]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_bcmp.h [hunk 5]
```diff
@@ -10,7 +10,7 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_BCMP_H
 
 #include "src/__support/common.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_bcmp.h:13]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_bzero.h [hunk 6]
```diff
@@ -10,7 +10,7 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_BZERO_H
 
 #include "src/__support/common.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_bzero.h:13]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_memmem.h [hunk 7]
```diff
@@ -10,7 +10,6 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_MEMMEM_H
 
 #include "src/__support/macros/attributes.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_memmem.h:13]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_memmove.h [hunk 8]
```diff
@@ -9,7 +9,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_MEMMOVE_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_MEMMOVE_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_memmove.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_strcmp.h [hunk 9]
```diff
@@ -9,7 +9,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_STRCMP_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_STRCMP_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_strcmp.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/inline_strstr.h [hunk 10]
```diff
@@ -9,7 +9,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_STRSTR_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_INLINE_STRSTR_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/inline_strstr.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/x86_64/inline_memset.h [hunk 11]
```diff
@@ -9,7 +9,6 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_X86_64_INLINE_MEMSET_H
 
 #include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/x86_64/inline_memset.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/x86_64/inline_bcmp.h [hunk 12]
```diff
@@ -9,7 +9,6 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_X86_64_INLINE_BCMP_H
 
 #include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/x86_64/inline_bcmp.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/utils.h [hunk 13]
```diff
@@ -14,7 +14,6 @@
 #include "src/__support/CPP/type_traits.h"
 #include "src/__support/endian.h"
 #include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/utils.h:17]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/riscv/inline_memset.h [hunk 14]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_RISCV_INLINE_MEMSET_H
 
 #include "src/__support/macros/attributes.h"               // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/riscv/inline_memset.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/riscv/inline_memmove.h [hunk 15]
```diff
@@ -9,7 +9,6 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_RISCV_INLINE_MEMMOVE_H
 
 #include "src/__support/macros/attributes.h"               // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/riscv/inline_memmove.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/riscv/inline_memcpy.h [hunk 16]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_RISCV_INLINE_MEMCPY_H
 
 #include "src/__support/macros/attributes.h"               // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/riscv/inline_memcpy.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/riscv/inline_memcmp.h [hunk 17]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_RISCV_INLINE_MEMCMP_H
 
 #include "src/__support/macros/attributes.h"               // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/riscv/inline_memcmp.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/riscv/inline_bcmp.h [hunk 18]
```diff
@@ -9,7 +9,6 @@
 #define LIBC_SRC_STRING_MEMORY_UTILS_RISCV_INLINE_BCMP_H
 
 #include "src/__support/macros/attributes.h"               // LIBC_INLINE
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/riscv/inline_bcmp.h:12]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/op_x86.h [hunk 19]
```diff
@@ -12,7 +12,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_X86_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_X86_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/op_x86.h:15]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/op_riscv.h [hunk 20]
```diff
@@ -12,7 +12,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_RISCV_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_RISCV_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/op_riscv.h:15]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/op_generic.h [hunk 21]
```diff
@@ -27,7 +27,7 @@
 #include "src/__support/CPP/type_traits.h"
 #include "src/__support/common.h"
 #include "src/__support/endian.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/op_generic.h:30]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/op_builtin.h [hunk 22]
```diff
@@ -16,7 +16,7 @@
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_BUILTIN_H
 
 #include "src/__support/CPP/type_traits.h"
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/op_builtin.h:19]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

File: libc/src/string/memory_utils/op_aarch64.h [hunk 23]
```diff
@@ -13,7 +13,7 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_AARCH64_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_OP_AARCH64_H
 
-#include "src/__support/macros/config.h"
```
Comment (lntue) [inline libc/src/string/memory_utils/op_aarch64.h:16]: `src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

**Review by lntue — APPROVED** [review]

File: libc/src/string/memory_utils/x86_64/inline_memset.h [hunk 24]
```diff
@@ -8,8 +8,8 @@
 #ifndef LLVM_LIBC_SRC_STRING_MEMORY_UTILS_X86_64_INLINE_MEMSET_H
 #define LLVM_LIBC_SRC_STRING_MEMORY_UTILS_X86_64_INLINE_MEMSET_H
 
-#include "src/__support/macros/attributes.h" // LIBC_INLINE
-#include "src/__support/macros/config.h"
+#include "src/__support/macros/attributes.h" // LIBC_INLINE_VAR
```
Comment (nickdesaulniers) [inline libc/src/string/memory_utils/x86_64/inline_memset.h:11]: `LIBC_INLINE` is also used from this header.

```suggestion
#include "src/__support/macros/attributes.h" // LIBC_INLINE, LIBC_INLINE_VAR
```

File: libc/src/__support/CMakeLists.txt [hunk 25]
```diff
@@ -54,11 +54,9 @@ add_header_library(
 add_header_library(
   common
   HDRS
-    common.h
-    endian.h
     macros/properties/architectures.h
     macros/attributes.h
-    macros/properties/cpu_features.h
```
Comment (nickdesaulniers) [inline libc/src/__support/CMakeLists.txt:61]: May need to audit all uses of `LIBC_TARGET_CPU_HAS` (TODO: @nickdesaulniers )

**Review by nickdesaulniers — CHANGES_REQUESTED** [review]
left more feedback

File: libc/src/string/memory_utils/aarch64/inline_bcmp.h [hunk 26]
```diff
@@ -8,8 +8,7 @@
 #ifndef LIBC_SRC_STRING_MEMORY_UTILS_AARCH64_INLINE_BCMP_H
 #define LIBC_SRC_STRING_MEMORY_UTILS_AARCH64_INLINE_BCMP_H
 
-#include "src/__support/macros/attributes.h"   // LIBC_INLINE
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/src/string/memory_utils/aarch64/inline_bcmp.h:11]: isn't `LIBC_INLINE` supposed to be used from `src/__support/macros/attributes.h`  instead of `src/__support/macros/config.h`?

**Comment by nickdesaulniers** [comment]
> This branch has conflicts that must be resolved

Hi @krishna2803 , thanks for updating this PR. It looks like you'll need to rebase on `main`. Do you mind doing that? You'll need to force push to your github branch.

**Comment by krishna2803** [comment]
yeah sure! I'm on it

File: libc/src/__support/CMakeLists.txt (hunk 25 above)
Comment (krishna2803) [reply libc/src/__support/CMakeLists.txt:90]: can you please provide some guidance on what exactly needs to be done here?

File: libc/src/string/memory_utils/aarch64/inline_bcmp.h (hunk 2 above)
Comment (nickdesaulniers) [reply libc/src/string/memory_utils/aarch64/inline_bcmp.h:12]: This is still an issue in the last version of this patch.

File: libc/src/__support/CMakeLists.txt (hunk 25 above)
Comment (nickdesaulniers) [reply libc/src/__support/CMakeLists.txt:90]: Specifically, there's a bunch of headers in src/__support/FPUtil/ and src/__support/HashTable/ that depend on cpu_features.h.  If their cmake doesn't directly depend on cpu_features header library in their cmake (instead indirectly dependending on them), then this change will sever that dependency.

libc/src/__support/HashTable/CMakeLists.txt LGTM
libc/src/__support/FPUtil/CMakeLists.txt does not LGTM, so you'll need to add explicit dependencies in that cmake file on `libc.src.__support.macros.properties.cpu_features`.

**Review by nickdesaulniers — CHANGES_REQUESTED** [review]

**Review by nickdesaulniers — CHANGES_REQUESTED** [review]

File: libc/src/__support/FPUtil/CMakeLists.txt [hunk 27]
```diff
@@ -150,6 +153,7 @@ add_header_library(
   DEPENDS
     libc.src.__support.common
     libc.src.__support.macros.optimization
+    libc.src.__support.macros.properties.cpu_features
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/src/__support/FPUtil/CMakeLists.txt:156]: shouldn't this be for `nearest_integer.h`?

[the remark this answers is not in the document]
Comment (nickdesaulniers) [reply libc/src/__support/FPUtil/CMakeLists.txt:156]: huh, oh, sorry, did I not unfold the diff in github UI? Anyways, my mistake; for some reason I think this hunk was being added to PolyEval, not nearest_integer.

Ok, I'll approve this once I test it quickly locally, but LGTM.

**Review by nickdesaulniers — APPROVED** [review]
Thanks for the patch! Need us to merge this for you?

**Comment by krishna2803** [comment]
yeah! thanks :D
