### PR TITLE
[AArch64][BTI] Add BTI at EH entries.

### LINKED ISSUE #149267: clang++ 20 Exceptions crash with (recent) libgcc and aarch64 BTI  (Linux)
Reproduced using clang15 and 18 in Amazon Linux 2023 and clang20 in Fedora42

When building a program with BTI (typically in my case `-mbranch-protection=standard`, the program crashes in C++ exception processing.

I've pinpointed the cause to clang not putting a bti instruction at the beginning of the exception "catching" code. Older libgcc (I tested gcc11) work fine because they use a `ret` instruction at the end of `__builtin_eh_return()` when jumping to the catch handler. With gcc 14 (at least using the version in Amazon Linux 2023) however I get a `br` instruction which expects the destination to have the appropriate bti instruction.

It works fine with g++

A simple test program demonstrates the issue:
```
#include <iostream>

int main()
{
	std::cout << "Foo\n";
	try {
		throw 1;
	} catch (int a) 
	{
		std::cout << "Bar\n";
	}
	return 0;
}
```
Compile with:
 ```
$ clang++ -O0 -g2 -mbranch-protection=standard -o test test.cpp`
$ ./test
Foo
Illegal instruction (core dumped)
$ ./test
Foo
Bar
```

You can see in the generated assembly:
```
000000000041030c <main>:
  41030c:       d503233f        paciasp
  410310:       d100c3ff        sub     sp, sp, #0x30
  410314:       a9027bfd        stp     x29, x30, [sp, #32]
  410318:       910083fd        add     x29, sp, #0x20
  41031c:       b81fc3bf        stur    wzr, [x29, #-4]
  410320:       90000180        adrp    x0, 440000 <__cxa_begin_catch@CXXABI_1.3>
  410324:       91020000        add     x0, x0, #0x80
  410328:       90000081        adrp    x1, 420000 <_IO_stdin_used>
  41032c:       91004021        add     x1, x1, #0x10
  410330:       97ffff56        bl      410088 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
  410334:       d2800080        mov     x0, #0x4                        // #4
  410338:       97ffff48        bl      410058 <__cxa_allocate_exception@plt>
  41033c:       52800028        mov     w8, #0x1                        // #1
  410340:       b9000008        str     w8, [x0]
  410344:       f0000161        adrp    x1, 43f000 <GCC_except_table1+0x1ee20>
  410348:       9136a021        add     x1, x1, #0xda8
  41034c:       aa1f03e2        mov     x2, xzr
  410350:       97ffff72        bl      410118 <__cxa_throw@plt>
  410354:       14000022        b       4103dc <_fini>
  __cxa_throw ends up jumping here:
  410358:       2a0103e8        mov     w8, w1     <---- not a BTI instruction, boom !
  41035c:       f9000be0        str     x0, [sp, #16]
  410360:       b9000fe8        str     w8, [sp, #12]
  410364:       14000001        b       410368 <main+0x5c>

 .../...
```

The same code generated by gcc (11 in this case):
```
000000000041028c <main>:
  41028c:       d503233f        paciasp
  410290:       a9bd7bfd        stp     x29, x30, [sp, #-48]!
  410294:       910003fd        mov     x29, sp
  410298:       f9000bf3        str     x19, [sp, #16]
  41029c:       90000080        adrp    x0, 420000 <_IO_stdin_used>
  4102a0:       91004001        add     x1, x0, #0x10
  4102a4:       90000180        adrp    x0, 440000 <__cxa_begin_catch@CXXABI_1.3>
  4102a8:       91020000        add     x0, x0, #0x80
  4102ac:       97ffff77        bl      410088 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
  4102b0:       d2800080        mov     x0, #0x4                        // #4
  4102b4:       97ffff69        bl      410058 <__cxa_allocate_exception@plt>
  4102b8:       52800021        mov     w1, #0x1                        // #1
  4102bc:       b9000001        str     w1, [x0]
  4102c0:       d2800002        mov     x2, #0x0                        // #0
  4102c4:       f0000161        adrp    x1, 43f000 <__FRAME_END__+0x1ee50>
  4102c8:       9136a021        add     x1, x1, #0xda8
  4102cc:       97ffff93        bl      410118 <__cxa_throw@plt>
  __cxa_throw ends up jumping here:
  4102d0:       d503249f        bti     j  <--- here's our BTI
  4102d4:       f100043f        cmp     x1, #0x1
  4102d8:       54000040        b.eq    4102e0 <main+0x54>  // b.none
  4102dc:       97ffff95        bl      410130 <_Unwind_Resume@plt>
  .../...
```

### PR DESCRIPTION
**Pull request by shashforge**
[AArch64][BTI] Add BTI at EH entries

Mark EH landing pads as indirect-branch targets (BTI j) and treat WinEH
funclet entries as call-like (BTI c). Add lit tests for ELF and COFF.
Tests:
Adds lit tests: bti-ehpad.ll and wineh-bti-funclet.ll.

Fixes: #149267

### CODE REVIEW

**Comment by ozbenh** [comment]
Did you drop the change to ensure the BTI is inserted after EH_LABEL ?

**Review by davemgreen — COMMENTED** [review]
If you want me to take this over I am happy to do so.

**Comment by shashforge** [comment]
> Did you drop the change to ensure the BTI is inserted after EH_LABEL ?

Good catch, Thanks  — restored.. We now insert BTI after any leading EH_LABEL and then after meta/CFI, so the first executed instruction in a landing pad is BTI. For non‑EH blocks we keep the legacy order to preserve existing codegen/tests.

File: llvm/lib/Target/AArch64/AArch64BranchTargets.cpp [hunk 1]
```diff
@@ -100,9 +99,15 @@ bool AArch64BranchTargets::runOnMachineFunction(MachineFunction &MF) {
...
       CouldJump = true;
 
+    if (MBB.isEHPad()) {
+      if (HasWinCFI && (MBB.isEHFuncletEntry() || MBB.isCleanupFuncletEntry()))
+        CouldCall = true;
+      else
+        CouldJump = true;
+    }
     if (CouldCall || CouldJump) {
       addBTI(MBB, CouldCall, CouldJump, HasWinCFI);
```
[the remark this answers is not in the document]
Comment (shashforge) [reply llvm/lib/Target/AArch64/AArch64BranchTargets.cpp:112]: Done. After skipping any EH_LABEL, we also skip isMetaInstruction() and EMITBKEY before inserting BTI, so BTI precedes the first real instruction in the pad.

File: llvm/test/CodeGen/AArch64/bti-ehpad.ll [hunk 2]
```diff
@@ -0,0 +1,29 @@
+; REQUIRES: aarch64-registered-target
+; RUN: llc -mtriple=aarch64-unknown-linux-gnu %s -o - | FileCheck %s
+
+target triple = "aarch64-unknown-linux-gnu"
```
[the remark this answers is not in the document]
Comment (shashforge) [reply llvm/test/CodeGen/AArch64/bti-ehpad.ll]: Removed

**Review by davemgreen — COMMENTED** [review]
Nice work. Any reason to not use update_llc_test_checks.py?

**Review by davemgreen — COMMENTED** [review]
Thanks. @ozbenh does this do OK in your testing?

@efriedma-quic @DanielKristofKiss does this sound OK to you? I'm not an expert with pacbti and exception handling, but it seems OK to me.

**Review by DanielKristofKiss — APPROVED** [review]
besides the NITs  LGTM.

File: llvm/test/CodeGen/AArch64/wineh-bti.ll [hunk 3]
```diff
@@ -29,9 +29,9 @@ lbl4:
 
 ; CHECK-LABEL: func:
 ; CHECK-NEXT: .seh_proc func
-; CHECK-NEXT: // %bb.0:
-; CHECK-NEXT: hint #34
-; CHECK-NEXT: .seh_nop
+; CHECK:       // %bb.0: // %entry
+; CHECK-NEXT:  .seh_nop
```
Comment (efriedma-quic) [inline llvm/test/CodeGen/AArch64/wineh-bti.ll:33]: Please rearrange the code so it inserts the seh_nop directive after the bti instruction.

File: llvm/lib/Target/AArch64/AArch64BranchTargets.cpp [hunk 4]
```diff
@@ -143,11 +161,33 @@ void AArch64BranchTargets::addBTI(MachineBasicBlock &MBB, bool CouldCall,
...
-  if (HasWinCFI && MBBI->getFlag(MachineInstr::FrameSetup)) {
+  // If there's already a HINT at the insertion point, handle BTI safely.
+  if (MBBI != MBB.end() && MBBI->getOpcode() == AArch64::HINT) {
+    // Only "upgrade" if it is actually a BTI HINT (base 32). Otherwise,
+    // fall through and insert a BTI before this non-BTI hint, so the
+    // first executed instruction is BTI/PAC as required by enforcement.
+    if (MBBI->getOperand(0).isImm()) {
+      int64_t Imm = MBBI->getOperand(0).getImm();
+      if ((Imm & ~int64_t(BTIMask)) == BTIBase) {
+        unsigned Have = unsigned(Imm) & BTIMask;
```
Comment (efriedma-quic) [inline llvm/lib/Target/AArch64/AArch64BranchTargets.cpp:172]: Is this code actually reachable?  As far as I can tell, no other pass actually generates BTI instructions, so we should never find one.

Comment (shashforge) [reply llvm/lib/Target/AArch64/AArch64BranchTargets.cpp]: Done. I removed the in‑place “BTI HINT upgrade” block 

The insertion rule is now simple and correct: skip EH_LABEL + meta/CFI/EMITBKEY → insert BTI at the first executable instruction. If there were ever a non‑BTI HINT at entry in the future, we would still be correct because we insert the BTI before it (we build at MBBI).

I also replaced the remaining numeric immediate with small named constants (BTIBase/BTIC/BTIJ/BTIMask) so the intent is self‑documenting.

**Review by efriedma-quic — APPROVED** [review]
LGTM
