### PR TITLE
[Clang][Sema] Do not accept "vector _Complex" for AltiVec/ZVector

### LINKED ISSUE #88399: [SystemZ] No compile time error returned for vector double _Complex type
The test expects a compile time error when a `vector double _Complex` variable is declared; however, no error is returned. 
According to the supported vector data types listed in [https://www.ibm.com/docs/en/zos/2.5.0?topic=support-vector-data-types](https://www.ibm.com/docs/en/zos/2.5.0?topic=support-vector-data-types) `vector double _Complex` is not supported, so a compile time error is expected. 

**Test case:**
```
$ cat t.c
 
double _Complex b;
 
int main()
{
    vector double _Complex a = {b};
}
```
**Command to reproduce the actual behaviour:**
```
$ clang -mvx -mzvector  t.c
$ echo $?
0
```
**GCC returns a compile time error as expected:**
```
$ gcc -mvx -mzvector t.c
t.c: In function ‘main’:
t.c:5:5: error: invalid vector type for attribute ‘vector_size’
    5 |     vector double _Complex a = {b};
      |     ^~~~~~
```

### PR DESCRIPTION
**Pull request by uweigand**
The AltiVec (POWER) and ZVector (IBM Z) language extensions do not support using the "vector" keyword when the element type is a complex type, but current code does not verify this.

Add a Sema check and diagnostic for this case.

Fixes: https://github.com/llvm/llvm-project/issues/88399

### CODE REVIEW

File: clang/lib/Sema/DeclSpec.cpp [hunk 1]
```diff
@@ -1191,6 +1191,10 @@ void DeclSpec::Finish(Sema &S, const PrintingPolicy &Policy) {
 
   // Validate and finalize AltiVec vector declspec.
   if (TypeAltiVecVector) {
+    // Complex vector types are not supported.
+    if (TypeSpecComplex != TSC_unspecified)
+      S.Diag(TSCLoc, diag::err_invalid_vector_complex_decl_spec);
```
Comment (chenzheng1030) [inline clang/lib/Sema/DeclSpec.cpp:1196]: Should we stop diagnosing other errors in this function?

File: clang/test/Parser/cxx-altivec.cpp [hunk 2]
```diff
@@ -111,6 +111,20 @@ vector __bool long long v_bll4;      // expected-error {{use of 'long long' with
...
+vector double _Complex v_cd;         // expected-error {{cannot use '_Complex' with '__vector'}}
+#ifndef __VSX__
+                                     // expected-error@-2 {{use of 'double' with '__vector' requires VSX support to be enabled (available on POWER7 or later)}}
+#endif
+vector long double _Complex v_cld;   // expected-error {{cannot use '_Complex' with '__vector'}}
+                                     // expected-error@-1 {{cannot use 'long double' with '__vector'}}
+__vector float _Complex v_cf2;       // expected-error {{cannot use '_Complex' with '__vector'}}
+__vector double _Complex v_cd2;      // expected-error {{cannot use '_Complex' with '__vector'}}
+#ifndef __VSX__
+                                     // expected-error@-2 {{use of 'double' with '__vector' requires VSX support to be enabled (available on POWER7 or later)}}
```
Comment (chenzheng1030) [inline clang/test/Parser/cxx-altivec.cpp:124]: Error message `cannot use '_Complex' with '__vector'` sounds like good enough. This error message is not accurate at all?

**Review by chenzheng1030 — COMMENTED** [review]
Thanks very much for taking care of PPC.

File: clang/lib/Sema/DeclSpec.cpp (hunk 1 above)
Comment (uweigand) [reply clang/lib/Sema/DeclSpec.cpp]: Makes sense.  I've updated the patches.

**Review by chenzheng1030 — APPROVED** [review]
LGTM. Thanks!
