### PR TITLE
[clang-format] Hanlde qualified type name for `QualifierAlignment`

### LINKED ISSUE #125178: [clang-format] QualifierAlignment/QualifierOrder leads to broken code when using qualified names
Example input:

```cpp
#include <cstdint>

std::int64_t constexpr x{123};
```

Run:

```console
$ clang-format --style="{QualifierAlignment: Custom, QualifierOrder:[constexpr,type,const]}" file.cpp
```

Output:
```cpp
#include <cstdint>

std::constexpr int64_t x{123};
```

Repro: https://godbolt.org/z/Tdx4TeMoc

### PR DESCRIPTION
**Pull request by owenca**
Fixes #125178.

### CODE REVIEW

**Comment by rymiel** [comment]
Seems to also work for top-level types (`::int_64_t constexpr x{123};` works correctly) but breaks for fully qualified types (`::std::int64_t constexpr x{123};` becomes `::constexpr std::int64_t x{123};`)

**Comment by owenca** [comment]
> Seems to also work for top-level types (`::int_64_t constexpr x{123};` works correctly) but breaks for fully qualified types (`::std::int64_t constexpr x{123};` becomes `::constexpr std::int64_t x{123};`)

Yeah, I intentionally didn't want to use a loop for names like `A1::A2:: ... ::An` and instead just wanted to handle single-level nested names like `A::B`.

**Comment by HazardyKnusperkeks** [comment]
> > Seems to also work for top-level types (`::int_64_t constexpr x{123};` works correctly) but breaks for fully qualified types (`::std::int64_t constexpr x{123};` becomes `::constexpr std::int64_t x{123};`)
> 
> Yeah, I intentionally didn't want to use a loop for names like `A1::A2:: ... ::An` and instead just wanted to handle single-level nested names like `A::B`.

But why?

**Comment by owenca** [comment]
Same reason we almost never handle them, just like we (almost?) never handle the possibility of templated qualified names of arbitrary nesting levels (e.g. `A1<B1>::A2<B2> … An<Bn>`) and of comments before _every_ token. We can always tweak the code if and when we need to handle these rare cases.

**Comment by owenca** [comment]
> Seems to also work for top-level types (`::int_64_t constexpr x{123};` works correctly)

It didn't work either.

**Comment by owenca** [comment]
> > Seems to also work for top-level types (`::int_64_t constexpr x{123};` works correctly) but breaks for fully qualified types (`::std::int64_t constexpr x{123};` becomes `::constexpr std::int64_t x{123};`)
> 
> Yeah, I intentionally didn't want to use a loop for names like `A1::A2:: ... ::An` and instead just wanted to handle single-level nested names like `A::B`.

Now it handles the general pattern above (and also `::A1::A2:: ... An`).

File: clang/lib/Format/QualifierAlignmentFixer.cpp [hunk 1]
```diff
@@ -412,6 +414,15 @@ const FormatToken *LeftRightQualifierAlignmentFixer::analyzeLeft(
   // The case `const long long volatile int` -> `const volatile long long int`
   // The case `long volatile long int const` -> `const volatile long long int`
   if (TypeToken->isTypeName(LangOpts)) {
+    for (const auto *Prev = TypeToken->getPreviousNonComment();
+         Prev && Prev->is(tok::coloncolon);
+         Prev = Prev->getPreviousNonComment()) {
+      TypeToken = Prev;
+      Prev = Prev->getPreviousNonComment();
+      if (!(Prev && Prev->is(tok::identifier)))
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/QualifierAlignmentFixer.cpp:422]:
```suggestion
      if (!Prev || Prev->isNot(tok::identifier))
```
I personally don't like negated parenthesis.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/QualifierAlignmentFixer.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/QualifierAlignmentFixer.cpp:422]: Neither do I when the conditions inside the parentheses are unrelated. Otherwise, I prefer the negated parentheses. Another example is `!(Foo == A || Foo == B || Foo == C)` (i.e. `Foo` is not one of `A`, `B`, and `C`) vs `Foo != A && Foo != B && Foo != C` (i.e. `Foo` is not `A`, not `B`, and not `C`). The former is more readable to me.

File: clang/lib/Format/QualifierAlignmentFixer.cpp [hunk 2]
```diff
@@ -412,6 +414,15 @@ const FormatToken *LeftRightQualifierAlignmentFixer::analyzeLeft(
   // The case `const long long volatile int` -> `const volatile long long int`
   // The case `long volatile long int const` -> `const volatile long long int`
   if (TypeToken->isTypeName(LangOpts)) {
+    for (const auto *Prev = TypeToken->getPreviousNonComment();
+         Prev && Prev->is(tok::coloncolon);
+         Prev = Prev->getPreviousNonComment()) {
+      TypeToken = Prev;
+      Prev = Prev->getPreviousNonComment();
```
Comment (owenca) [inline clang/lib/Format/QualifierAlignmentFixer.cpp:421]: I will replace `getPreviousNonComment()` with `Previous` for simplicity and better performance as we really don't need to be concerned about code like `::/**/std/**/::/**/int64_t`.

**Review by mydeveloperday — APPROVED** [review]
Thank you

File: clang/lib/Format/QualifierAlignmentFixer.cpp (hunk 2 above)
Comment (owenca) [inline clang/lib/Format/QualifierAlignmentFixer.cpp:421]:
```suggestion
    for (const auto *Prev = TypeToken->Previous;
         Prev && Prev->is(tok::coloncolon);
         Prev = Prev->Previous) {
      TypeToken = Prev;
      Prev = Prev->Previous;
```

File: clang/lib/Format/QualifierAlignmentFixer.cpp [hunk 3]
```diff
@@ -412,6 +414,15 @@ const FormatToken *LeftRightQualifierAlignmentFixer::analyzeLeft(
   // The case `const long long volatile int` -> `const volatile long long int`
   // The case `long volatile long int const` -> `const volatile long long int`
   if (TypeToken->isTypeName(LangOpts)) {
+    for (const auto *Prev = TypeToken->Previous;
+         Prev && Prev->is(tok::coloncolon);
+         Prev = Prev->Previous) {
```
Comment (owenca) [inline clang/lib/Format/QualifierAlignmentFixer.cpp:419]:
```suggestion
         Prev && Prev->is(tok::coloncolon); Prev = Prev->Previous) {
```
