### PR TITLE
[AMDGPU] Fix undefined scc register in successor block of SI_KILL terminators

### LINKED ISSUE #131298: AMDGPU: Using an undefined physical register in testcase using compare over kill
This testcase, derived from llvm/test/CodeGen/AMDGPU/skip-if-dead.ll fails the verifier:

```
; RUN: llc -mtriple=amdgcn -mcpu=tahiti -verify-machineinstrs < %s | FileCheck -check-prefixes=GCN,WAVE64,SI %s

define amdgpu_ps void @phi_use_def_before_kill(float inreg %x, i32 inreg %y) #0 {
bb:
  %tmp = fadd float %x, 1.000000e+00
  %tmp1 = fcmp olt float 0.000000e+00, %tmp
  %tmp2 = select i1 %tmp1, float -1.000000e+00, float 0.000000e+00
  %cmp.tmp2 = fcmp olt float %tmp2, 0.000000e+00
  %uniform.cond = icmp eq i32 %y, 0
  call void @llvm.amdgcn.kill(i1 %cmp.tmp2)
  br i1 %uniform.cond, label %phibb, label %bb8

phibb:                                            ; preds = %bb8, %bb
  %tmp5 = phi float [ %tmp2, %bb ], [ 4.000000e+00, %bb8 ]
  %tmp6 = fcmp oeq float %tmp5, 0.000000e+00
  br i1 %tmp6, label %bb10, label %end

bb8:                                              ; preds = %bb
  store volatile i32 8, ptr addrspace(1) poison, align 4
  br label %phibb

bb10:                                             ; preds = %phibb
  store volatile i32 9, ptr addrspace(1) poison, align 4
  br label %end

end:                                              ; preds = %bb10, %phibb
  ret void
}

declare void @llvm.amdgcn.exp.f32(i32 immarg, i32 immarg, float, float, float, float, i1 immarg, i1 immarg) #1
declare void @llvm.amdgcn.kill(i1) #2
declare void @llvm.amdgcn.s.setreg(i32 immarg, i32) #3
declare float @llvm.amdgcn.image.sample.l.2darray.f32.f32.v8i32.v4i32(i32 immarg, float, float, float, float, <8 x i32>, <4 x i32>, i1 immarg, i32 immarg, i32 immarg) #4
declare <4 x float> @llvm.amdgcn.image.sample.c.1d.v4f32.f32.v8i32.v4i32(i32 immarg, float, float, <8 x i32>, <4 x i32>, i1 immarg, i32 immarg, i32 immarg) #5

attributes #0 = { nounwind }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { nocallback nofree nounwind }
attributes #3 = { nocallback nofree nosync nounwind willreturn }
attributes #4 = { nocallback nofree nosync nounwind willreturn memory(read) }
attributes #5 = { convergent nocallback nofree nosync nounwind willreturn memory(read) }

```

```
# After Instruction Selection
# Machine code for function phi_use_def_before_kill: IsSSA, TracksLiveness
Function Live Ins: $sgpr0 in %2, $sgpr1 in %3

bb.0.bb:
  successors: %bb.5(0x80000000); %bb.5(100.00%)
  liveins: $sgpr0, $sgpr1
  %3:sgpr_32 = COPY $sgpr1
  %2:sgpr_32 = COPY $sgpr0
  %5:sgpr_32 = S_MOV_B32 1065353216
  %7:vgpr_32 = COPY killed %5:sgpr_32
  %6:vgpr_32 = nofpexcept V_ADD_F32_e64 0, %2:sgpr_32, 0, %7:vgpr_32, 0, 0, implicit $mode, implicit $exec
  %8:sgpr_32 = S_MOV_B32 0
  %9:sreg_64_xexec = nofpexcept V_CMP_GT_F32_e64 0, %6:vgpr_32, 0, %8:sgpr_32, 0, implicit $mode, implicit $exec
  %10:sgpr_32 = S_MOV_B32 -1082130432
  %12:vgpr_32 = COPY %8:sgpr_32
  %13:vgpr_32 = COPY killed %10:sgpr_32
  %11:vgpr_32 = V_CNDMASK_B32_e64 0, %12:vgpr_32, 0, %13:vgpr_32, killed %9:sreg_64_xexec, implicit $exec
  %0:sgpr_32 = IMPLICIT_DEF
  %14:sreg_32 = S_MOV_B32 0
  S_CMP_LG_U32 %3:sgpr_32, killed %14:sreg_32, implicit-def $scc
  SI_KILL_F32_COND_IMM_TERMINATOR %6:vgpr_32, 0, 2, implicit-def dead $vcc, implicit $exec

bb.5.bb:
; predecessors: %bb.0
  successors: %bb.2(0x50000000), %bb.1(0x30000000); %bb.2(62.50%), %bb.1(37.50%)

  S_CBRANCH_SCC1 %bb.2, implicit $scc
  S_BRANCH %bb.1

bb.1.phibb:
; predecessors: %bb.2, %bb.5
  successors: %bb.3(0x50000000), %bb.4(0x30000000); %bb.3(62.50%), %bb.4(37.50%)

  %36:vgpr_32 = PHI %11:vgpr_32, %bb.5, %37:vgpr_32, %bb.2
  %24:sgpr_32 = S_MOV_B32 0
  %26:sgpr_32 = COPY killed %24:sgpr_32
  %25:sreg_64 = nofpexcept V_CMP_EQ_F32_e64 0, %36:vgpr_32, 0, %26:sgpr_32, 0, implicit $mode, implicit $exec
  %27:sreg_64 = S_AND_B64 $exec, killed %25:sreg_64, implicit-def dead $scc
  $vcc = COPY %27:sreg_64
  S_CBRANCH_VCCNZ %bb.3, implicit $vcc
  S_BRANCH %bb.4

bb.2.bb8:
; predecessors: %bb.5
  successors: %bb.1(0x80000000); %bb.1(100.00%)

  %16:sreg_64 = IMPLICIT_DEF
  %17:sreg_32 = COPY %16.sub1:sreg_64
  %18:sreg_64 = IMPLICIT_DEF
  %19:sreg_32 = COPY %18.sub0:sreg_64
  %20:sreg_32 = S_MOV_B32 61440
  %21:sreg_32 = S_MOV_B32 -1
  %22:sgpr_128 = REG_SEQUENCE killed %19:sreg_32, %subreg.sub0, killed %17:sreg_32, %subreg.sub1, killed %21:sreg_32, %subreg.sub2, killed %20:sreg_32, %subreg.sub3
  %23:vgpr_32 = V_MOV_B32_e32 8, implicit $exec
  BUFFER_STORE_DWORD_OFFSET killed %23:vgpr_32, killed %22:sgpr_128, 0, 0, 0, 0, implicit $exec :: (volatile store (s32) into `ptr addrspace(1) poison`, addrspace 1)
  %15:sgpr_32 = S_MOV_B32 1082130432
  %37:vgpr_32 = V_MOV_B32_e32 1082130432, implicit $exec
  S_BRANCH %bb.1

bb.3.bb10:
; predecessors: %bb.1
  successors: %bb.4(0x80000000); %bb.4(100.00%)

  %28:sreg_64 = IMPLICIT_DEF
  %29:sreg_32 = COPY %28.sub1:sreg_64
  %30:sreg_64 = IMPLICIT_DEF
  %31:sreg_32 = COPY %30.sub0:sreg_64
  %32:sreg_32 = S_MOV_B32 61440
  %33:sreg_32 = S_MOV_B32 -1
  %34:sgpr_128 = REG_SEQUENCE killed %31:sreg_32, %subreg.sub0, killed %29:sreg_32, %subreg.sub1, killed %33:sreg_32, %subreg.sub2, killed %32:sreg_32, %subreg.sub3
  %35:vgpr_32 = V_MOV_B32_e32 9, implicit $exec
  BUFFER_STORE_DWORD_OFFSET killed %35:vgpr_32, killed %34:sgpr_128, 0, 0, 0, 0, implicit $exec :: (volatile store (s32) into `ptr addrspace(1) poison`, addrspace 1)

bb.4.end:
; predecessors: %bb.1, %bb.3

  S_ENDPGM 0

# End machine code for function phi_use_def_before_kill.

*** Bad machine code: Using an undefined physical register ***
- function:    phi_use_def_before_kill
- basic block: %bb.5 bb (0x14608b290)
- instruction: S_CBRANCH_SCC1 %bb.2, implicit $scc
- operand 1:   implicit $scc
LLVM ERROR: Found 1 machine code errors.

```

### PR DESCRIPTION
**Pull request by mssefat**
Fix issue 131298 where an undefined $scc register causes verifier errors
when using SI_KILL_F32_COND_IMM_TERMINATOR instructions. The problem occurs
because the $scc register defined in a comparison before the kill terminator
is used in successor blocks, but was not properly marked as live-in.

This patch:
- Adds code to check if SCC is used in the successor block
- Adds SCC as a live-in to successor blocks
- Handles both explicit and implicit uses of SCC

With this patch the machine verifier no longer reports undefined $scc errors in
following kill terminator instruction.

Fixes #131298

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/SIISelLowering.cpp [hunk 1]
```diff
@@ -4516,6 +4516,38 @@ SITargetLowering::splitKillBlock(MachineInstr &MI,
   MachineBasicBlock *SplitBB = BB->splitAt(MI, false /*UpdateLiveIns*/);
```
Comment (jmmartinez) [inline llvm/lib/Target/AMDGPU/SIISelLowering.cpp:4516]: What if we set `UpdateLiveIns` to true ? Wouldn't that cover the case we're trying to cover here ?

File: llvm/lib/Target/AMDGPU/SIISelLowering.cpp [hunk 2]
```diff
@@ -4516,6 +4516,38 @@ SITargetLowering::splitKillBlock(MachineInstr &MI,
...
+      const MCInstrDesc &Desc = SuccMI.getDesc();
+      if (Desc.hasImplicitUseOfPhysReg(AMDGPU::SCC)) {
+        IsSCCUsedInSuccessor = true;
+        break;
+      }
+    }
+    
+    if (IsSCCUsedInSuccessor)
+      break;
+  }
```
Comment (jmmartinez) [inline llvm/lib/Target/AMDGPU/SIISelLowering.cpp:4542]: If you move this code to a helper function we would end up with less awkward branching:

```cpp
for (const MachineInstr &SuccMI : *SplitBB) {
    // Check for uses of SCC in the instruction's operands
    for (const MachineOperand &MO : SuccMI.operands())
      if (MO.isReg() && MO.getReg() == AMDGPU::SCC && !MO.isDef())
        return true;

    // Also check for implicit uses of SCC
    const MCInstrDesc &Desc = SuccMI.getDesc();
    if (Desc.hasImplicitUseOfPhysReg(AMDGPU::SCC))
      return true;
}
```

**Review by arsenm — COMMENTED** [review]
Should also include MIR test. We shouldn't really need to scan the entire successor for this

File: llvm/lib/Target/AMDGPU/SIISelLowering.cpp (hunk 1 above)
Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIISelLowering.cpp]: I've pushed the updates, where UpdateLiveIns is now set to true. To support this change, I moved the call to finalizeLowering to the beginning of FinalizeISel::runImpl. This ensures that reserved registers are frozen before live-ins are added. Without this change, llvm::addLiveIns() triggers an assertion failure due to the check for reservedRegsFrozen() when reserved registers are not yet finalized. Please review.

**Comment by mssefat** [comment]
> Should also include MIR test. We shouldn't really need to scan the entire successor for this

I have pushed the updates. Please review.

File: llvm/lib/Target/AMDGPU/SIISelLowering.cpp [hunk 3]
```diff
@@ -4513,7 +4513,7 @@ Register SITargetLowering::getRegisterByName(const char *RegName, LLT VT,
 MachineBasicBlock *
 SITargetLowering::splitKillBlock(MachineInstr &MI,
                                  MachineBasicBlock *BB) const {
-  MachineBasicBlock *SplitBB = BB->splitAt(MI, false /*UpdateLiveIns*/);
+  MachineBasicBlock *SplitBB = BB->splitAt(MI, true /*UpdateLiveIns*/);
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/SIISelLowering.cpp:4516]:
```suggestion
  MachineBasicBlock *SplitBB = BB->splitAt(MI, /*UpdateLiveIns=*/true);
```

File: llvm/lib/CodeGen/FinalizeISel.cpp [hunk 4]
```diff
@@ -47,6 +47,8 @@ static std::pair<bool, bool> runImpl(MachineFunction &MF) {
   const TargetInstrInfo *TII = MF.getSubtarget().getInstrInfo();
   const TargetLowering *TLI = MF.getSubtarget().getTargetLowering();
 
+  TLI->finalizeLowering(MF);
```
Comment (arsenm) [inline llvm/lib/CodeGen/FinalizeISel.cpp:50]: Do you really need this reordering? I'd expect this to be called after the custom insertions

Comment (mssefat) [reply llvm/lib/CodeGen/FinalizeISel.cpp:50]: I think we need this reordering. Without this reordering, llvm::addLiveIns() invoked from MachineBasicBlock::splitAt() triggers an assertion failure due to the check for reservedRegsFrozen() when reserved registers are not yet finalized.

Comment (arsenm) [reply llvm/lib/CodeGen/FinalizeISel.cpp:50]: This API is bad. We probably should split these into separate steps, but given no tests apparently rely on this order I guess this is fine for now

**Review by arsenm — APPROVED** [review]

**Review by arsenm — APPROVED** [review]
