### PR TITLE
[DirectX][ResourceAccess] Resolve resource handles at access

### LINKED ISSUE #165288: [HLSL][DX] Convergence tests failure
#The [convergence tests](https://github.com/llvm/offload-test-suite/pull/473) in offload-suite-test are failing. 

For subgroup_uniform_control_flow.test
https://hlsl.godbolt.org/z/jcToeTv8q

Looking at the IR between DXC and Clang it appears Clang has performed an illegal optimization. It hoisted and duplicated the final WaveActiveMax into two operations in both the if (label 11) and else (label 19) blocks of the top-level if statement. This is not a legal optimization for a convergent operation, and is the likely cause of the issue.

For loop_peeling.test
https://hlsl.godbolt.org/z/xx8qTYqzr
It looks like clang optimizes away the loop so WaveActiveMax is always 7 for a wave size of 8.

### PR DESCRIPTION
**Pull request by inbelic**
This change resolves handles (or corresponding ptr) that all point into a unique global resource by propagating an index into that global resource through control flow.

If a unique global resource can't be resolved, an error is reported instead.

This specifically resolves all handles that point into the same global resource array.

Resolves: https://github.com/llvm/llvm-project/issues/165288

By reporting an error, this is part of resolving https://github.com/llvm/llvm-project/issues/179303.

### CODE REVIEW

**Review by bob80905 — COMMENTED** [review]
couple nits

File: llvm/lib/Target/DirectX/DXILResourceAccess.cpp [hunk 1]
```diff
@@ -28,6 +30,13 @@
 
 using namespace llvm;
 
+static void diagnoseNonUniqueResourceAccess(Instruction *I,
+                                            ArrayRef<IntrinsicInst *> Handles) {
```
Comment (hekota) [inline llvm/lib/Target/DirectX/DXILResourceAccess.cpp]: The `Handles` argument is not used. Did you intend to create a more descriptive error message with that?

File: llvm/lib/Target/DirectX/DXILResourceAccess.cpp [hunk 2]
```diff
@@ -419,6 +428,217 @@ static void createLoadIntrinsic(IntrinsicInst *II, LoadInst *LI,
...
+  DeadInsts.insert(Ptr);
+}
+
+// Try to legalize dx.resource.handlefrom.*.binding and dx.resource.getpointer
+// calls with their respective index values and propogate the index values to
+// be used at resource access.
+//
+// If it can't be transformed to be legal then:
+//
+// Reports an error if a resource access is not guarenteed to be into a unique
```
Comment (hekota) [inline llvm/lib/Target/DirectX/DXILResourceAccess.cpp]:
```suggestion
// Reports an error if a resource access is not guaranteed to be into a unique
```

File: llvm/lib/Target/DirectX/DXILResourceAccess.cpp [hunk 3]
```diff
@@ -419,6 +428,217 @@ static void createLoadIntrinsic(IntrinsicInst *II, LoadInst *LI,
...
+  auto *GetPtr =
+      Builder.CreateIntrinsic(Ptr->getType(), Intrinsic::dx_resource_getpointer,
+                              {Handle, AccessIdx.GetPtrIdx});
+
+  Ptr->replaceAllUsesWith(GetPtr);
+  DeadInsts.insert(Ptr);
+}
+
+// Try to legalize dx.resource.handlefrom.*.binding and dx.resource.getpointer
+// calls with their respective index values and propogate the index values to
```
Comment (hekota) [inline llvm/lib/Target/DirectX/DXILResourceAccess.cpp]:
```suggestion
// calls with their respective index values and propagate the index values to
```

File: llvm/lib/Target/DirectX/DXILResourceAccess.cpp [hunk 4]
```diff
@@ -419,6 +428,217 @@ static void createLoadIntrinsic(IntrinsicInst *II, LoadInst *LI,
...
+
+static SmallVector<IntrinsicInst *> collectUsedHandles(Value *Ptr) {
+  SmallVector<Value *> Worklist = {Ptr};
+  SmallVector<IntrinsicInst *> Handles;
+
+  while (!Worklist.empty()) {
+    Value *X = Worklist.pop_back_val();
+
+    if (!X->getType()->isPointerTy() && !X->getType()->isTargetExtTy())
+      return {}; // Early exit on store/load into non-resource
```
[the remark this answers is not in the document]
Comment (hekota) [reply llvm/lib/Target/DirectX/DXILResourceAccess.cpp]: I don't mind the name `collectUsedHandles` since this whole pass deals with resources, so it is fairly clear a handle is a resource handle. What threw me off was the `getPointerOperand` function. :) I would prefer `getLoadStorePointerOperand` or something like that which would show that it returns a pointer operand of these two ops.

**Review by hekota — APPROVED** [review]
Just a few nits, otherwise LGTM! :)

File: llvm/lib/Target/DirectX/DXILResourceAccess.cpp [hunk 5]
```diff
@@ -419,6 +428,217 @@ static void createLoadIntrinsic(IntrinsicInst *II, LoadInst *LI,
...
+  if (auto *Phi = dyn_cast<PHINode>(I)) {
+    unsigned NumEdges = Phi->getNumIncomingValues();
+    assert(NumEdges != 0 && "Malformed Phi Node");
+
+    IRBuilder<> Builder(Phi);
+    PHINode *GetPtrPhi = PHINode::Create(Builder.getInt32Ty(), NumEdges);
+    PHINode *HandlePhi = PHINode::Create(Builder.getInt32Ty(), NumEdges);
+
+    bool HasGetPtr = true;
+    for (unsigned I = 0; I < NumEdges; I++) {
```
[the remark this answers is not in the document]
Comment (bob80905) [reply llvm/lib/Target/DirectX/DXILResourceAccess.cpp]: I don't think this was resolved.

File: llvm/test/CodeGen/DirectX/ResourceAccess/handle-cases.ll [hunk 6]
```diff
@@ -0,0 +1,117 @@
+; RUN: opt -S -dxil-resource-type -dxil-resource-access -disable-verify \
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/ResourceAccess/handle-cases.ll:1]: @inbelic @hekota  Why are you doing ` -disable-verify` here this seems very wrong.

File: llvm/test/CodeGen/DirectX/ResourceAccess/handle-to-index.ll [hunk 7]
```diff
@@ -0,0 +1,156 @@
+; RUN: opt -S -dxil-resource-type -dxil-resource-access -disable-verify \
```
Comment (farzonl) [inline llvm/test/CodeGen/DirectX/ResourceAccess/handle-to-index.ll:1]: same here @inbelic @hekota
