### PR TITLE
[mlir] explicitly delete copy ctor for DialectRegistry and OperationState

### LINKED ISSUE #118388: [mlir] `mlir::DialectRegistry` can't be copied
Recall

```c++
class DialectRegistry {
  ...
private:
  llvm::MapVector<TypeID, std::unique_ptr<DialectExtensionBase>> extensions;
}
```

then

```c++
template <typename T> void wrap_copy(void *dst, const void *src) {
  new ((T *) dst) T(*(const T *) src);
}

foo() {
  (void)wrap_copy<mlir::DialectRegistry>;
}
```

will produce 

```
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_algobase.h:385:18: error: object of type 'std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>' cannot be assigned because its copy assignment operator is implicitly deleted
  385 |               *__result = *__first;
      |                         ^
```

on 

```
(eudsl) mlevental@Shark17:~/dev_projects/eudsl/projects/eudsl-py/src$ clang-20 --version
Ubuntu clang version 20.0.0 (++20241108053735+b613a54075c6-1~exp1~20241108053914.2037)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-20/bin
```

The copy offending copy comes from `SmallVectorImpl::operator=(const SmallVectorImpl<T> &RHS)`:
https://github.com/llvm/llvm-project/blob/9d85ba5724f22d73c95858246691e0b389bdb28d/llvm/include/llvm/ADT/SmallVector.h#L1017

I don't know what the correct solution is (should `SmallVector` be smarter?) but doing

```c++
DialectRegistry(const DialectRegistry&) = delete;
```

fixes (in the sense that `wrap_copy` reports a call to a deleted ctor, and/or `std::is_copy_constructible<mlir::DialectRegistry>::value == false`). 

Full compile error stack follows.

---

```
In file included from /home/mlevental/dev_projects/eudsl/projects/eudsl-py/src/eudsl_ext.cpp:1:
In file included from /home/mlevental/miniconda3/envs/eudsl/lib/python3.11/site-packages/nanobind/include/nanobind/nanobind.h:32:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/stdexcept:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/string:53:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ext/alloc_traits.h:34:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/alloc_traits.h:33:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_construct.h:119:25: error: call to implicitly-deleted copy constructor of 'std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>'
  119 |       ::new((void*)__p) _Tp(std::forward<_Args>(__args)...);
      |                         ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_uninitialized.h:120:11: note: in instantiation of function template specialization 'std::_Construct<std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>, const std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> &>' requested here
  120 |             std::_Construct(std::__addressof(*__cur), *__first);
      |                  ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_uninitialized.h:137:16: note: in instantiation of function template specialization 'std::__do_uninit_copy<const std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *, std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *>' requested here
  137 |         { return std::__do_uninit_copy(__first, __last, __result); }
      |                       ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_uninitialized.h:185:2: note: in instantiation of function template specialization 'std::__uninitialized_copy<false>::__uninit_copy<const std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *, std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *>' requested here
  185 |         __uninit_copy(__first, __last, __result);
      |         ^
/home/mlevental/dev_projects/eudsl/llvm-install/include/llvm/ADT/SmallVector.h:356:10: note: in instantiation of function template specialization 'std::uninitialized_copy<const std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *, std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *>' requested here
  356 |     std::uninitialized_copy(I, E, Dest);
      |          ^
/home/mlevental/dev_projects/eudsl/llvm-install/include/llvm/ADT/SmallVector.h:1043:9: note: in instantiation of function template specialization 'llvm::SmallVectorTemplateBase<std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>>::uninitialized_copy<const std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *, std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>> *>' requested here
 1043 |   this->uninitialized_copy(RHS.begin()+CurSize, RHS.end(),
      |         ^
/home/mlevental/dev_projects/eudsl/llvm-install/include/llvm/ADT/SmallVector.h:1238:27: note: in instantiation of member function 'llvm::SmallVectorImpl<std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>>::operator=' requested here
 1238 |       SmallVectorImpl<T>::operator=(RHS);
      |                           ^
/home/mlevental/dev_projects/eudsl/llvm-install/include/llvm/ADT/MapVector.h:36:7: note: in instantiation of member function 'llvm::SmallVector<std::pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>, 0>::SmallVector' requested here
   36 | class MapVector {
      |       ^
/home/mlevental/dev_projects/eudsl/projects/eudsl-py/src/eudsl_ext.cpp:282:9: note: in instantiation of function template specialization 'wrap_copy<mlir::DialectRegistry>' requested here
  282 |   (void)wrap_copy<mlir::DialectRegistry>;
      |         ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_pair.h:195:17: note: explicitly defaulted function was implicitly deleted here
  195 |       constexpr pair(const pair&) = default;    ///< Copy constructor
      |                 ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_pair.h:192:11: note: copy constructor of 'pair<mlir::TypeID, std::unique_ptr<mlir::DialectExtensionBase>>' is implicitly deleted because field 'second' has a deleted copy constructor
  192 |       _T2 second;                ///< The second member
      |           ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:514:7: note: 'unique_ptr' has been explicitly marked deleted here
  514 |       unique_ptr(const unique_ptr&) = delete;
```

### PR DESCRIPTION
**Pull request by makslevental**
Both of these classes have fields involving `unique_ptr`s and thus can't be copied.
Holding a unique_ptr should trigger implicit deletion of the copy/assignment constructors, however
not when held through a container:

```
struct Foo {  
  explicit Foo();
  std::vector<std::unique_ptr<Bar>> ptr; // Does not implicitly delete its cpy/assign ctors
};
```

This results in a complicated diagnostics when attempting to copy such a class (it'll point to the
inner implementation of the container), instead of a nicer error message about `Foo` not being able
to be copied/assigned. Explicitly deleting the ctors provides an immediate diagnostic about the issue.

Fixes https://github.com/llvm/llvm-project/issues/118388

### CODE REVIEW

**Comment by makslevental** [comment]
cc @0xddom

**Comment by 0xddom** [comment]
I checked `OperationState`'s  destructor and seems to be doing meaningful work so I retract my rule of zero comment in the issue. This lgtm

**Comment by joker-eph** [comment]
Is this expected that explicitly deleting these should change the behavior compared to have them implicitly deleted because of the unique_ptr member?

I feel like the title/description should elaborate bit more on what's going on here and what are we "fixing".

**Comment by 0xddom** [comment]
> Is this expected that explicitly deleting these should change the behavior compared to have them implicitly deleted because of the unique_ptr member?

For `OperationState`, at least, looks like having the compiler implicitly remove them should be enough. However, I'm also running into this issue with the `StorageUniquer` class, where the copy constructor is left implicit. I'm trying to create Rust bindings for MLIR via [autocxx](https://github.com/google/autocxx) and the autogenerated code fails to compile because of calls to these copy constructors. I[raised an issue](https://github.com/google/autocxx/issues/1485) in their repo about this in case it's a bug on the tool.

**Comment by joker-eph** [comment]
> the problem is they are not being implicitly deleted because (as the original issue documents) 

I don't get it what you mean by "they are not being implicitly deleted"

> SmallVectorImpl defines a copy ctor that is not smart enough.

Maybe but neither the description/title here neither the bug are very clear to me on what's happening actually.

The title here says: "explicitly delete copy ctor to prevent copying DialectRegistry and OperationState", which implies that right now without explicitly deleting them we can copy them. But how do you copy them today?

Here is a minimal test cases showing why the current description of the issue is confusing to me:
```
#include <memory>
class Bar {};
struct Foo {  
  std::unique_ptr<Bar> ptr;
};
void copy(Foo f1, Foo f2) {
   f1 = f2;
}
```

Yield:

```
<source>:8:9: error: use of deleted function 'Foo& Foo::operator=(const Foo&)'
    8 |    f1 = f2;
      |         ^~
<source>:3:8: note: 'Foo& Foo::operator=(const Foo&)' is implicitly deleted because the default definition would be ill-formed:
    3 | struct Foo {
      |        ^~~
```

(same with the copy ctor).

**Comment by joker-eph** [comment]
Or is this patch an "improve diagnostics" kind of thing?  Having `error: call to deleted constructor of 'mlir::DialectRegistry'` instead of having it on the data member?

**Review by joker-eph — APPROVED** [review]
LG with the updated description.

File: mlir/include/mlir/IR/DialectRegistry.h [hunk 1]
```diff
@@ -143,6 +143,8 @@ class DialectRegistry {
 
 public:
   explicit DialectRegistry();
+  DialectRegistry(const DialectRegistry &) = delete;
```
Comment (WillFroom) [inline mlir/include/mlir/IR/DialectRegistry.h:146]: I think this unintentionally changes the behavior to not allowing moving of `DialectRegistry`, I'll create a patch to add the explicit move constructor
