### PR TITLE
[Clang] Disallow explicit object parameters in more contexts

### LINKED ISSUE #85992: [clang] Pointer to member function should reject explicit object parameter
Clang accepts the following invalid code:

```C++
struct S {
  int f(int);
};

using T = int (S::*)(this int);  // Invalid
T t = &S::f;
```

GCC corectly rejects it:

```C++
error: a pointer to member function type cannot have an explicit object parameter
    4 | using T = int (S::*)(this int);  // INVALID
      |                      ^~~~~~~~
note: the type of a pointer to explicit object member function is a regular pointer to function type
```

[GodBolt](https://godbolt.org/z/jq6nKqfPx)

### PR DESCRIPTION
**Pull request by Sirraide**
[[dcl.fct]p6](https://eel.is/c++draft/dcl.fct#6) states:

> [...] An explicit-object-parameter-declaration shall appear only as the first parameter-declaration of a parameter-declaration-list of either:
> - a member-declarator that declares a member function [class.mem], or
> - a lambda-declarator [expr.prim.lambda].

The intent of this pr is to disallow explicit object parameters in all other contexts early on when we handle the function declarator.

This fixes #85992.

### CODE REVIEW

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp [hunk 1]
```diff
@@ -5,7 +5,7 @@
 void f(this); // expected-error{{variable has incomplete type 'void'}} \
               // expected-error{{invalid use of 'this' outside of a non-static member function}}
 
-void g(this auto); // expected-error{{an explicit object parameter cannot appear in a non-member function}}
+void g(this auto); // expected-error{{an explicit object parameter is not allowed here}}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/cxx2b-deducing-this.cpp:8]: I would rather keep the older diagnostic, which is more help. I'd recommend using %select. there are 2 cases

- In a non-member function
- In the declaration of a function pointer type

File: clang/lib/Sema/SemaType.cpp [hunk 2]
```diff
@@ -5287,6 +5287,36 @@ static TypeSourceInfo *GetFullTypeForDeclarator(TypeProcessingState &state,
...
+                : nullptr;
+        if (First && First->isExplicitObjectParameter() &&
+            C != DeclaratorContext::LambdaExpr &&
+
+            // Either not a member or nested declarator in a member.
+            (C != DeclaratorContext::Member ||
+             D.getInnermostNonParenChunk() != &DeclType) &&
+
+            // Allow out-of-line definitions if we have a scope spec.
+            D.getCXXScopeSpec().isEmpty()) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaType.cpp:5312]: What about 
```cpp
namespace a {
    void f();
};
void a::f(this auto) {}```

**Review by cor3ntin — COMMENTED** [review]
Generally, I like the approach.

Note this PR is related to 
https://github.com/llvm/llvm-project/pull/88974/files

@sdkrystian

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp (hunk 1 above)
Comment (Sirraide) [reply clang/test/SemaCXX/cxx2b-deducing-this.cpp:8]: I’d also prefer keeping it but I wasn’t entirely sure how to go about that; I can try and figure something out based on the declarator context.

File: clang/lib/Sema/SemaType.cpp (hunk 2 above)
Comment (Sirraide) [reply clang/lib/Sema/SemaType.cpp:5312]: Oh yeah, good point, I didn’t think of that. 

I think I should be able to borrow some code from the `MemberPointer` case below since that performs essentially the check that we need here on the scope spec (I was going to put this entire check in that case first, but then I noticed that this is also broken for e.g. regular function pointers, which is why I put this here instead).

**Comment by Sirraide** [comment]
> Note this PR is related to
> https://github.com/llvm/llvm-project/pull/88974/files

That’s pr covers a different code path from what I can tell though (unless requires expressions are also modelled as function declarators, I’m honestly not sure about that one).

It also reminds me that this still needs a release note.

**Comment by sdkrystian** [comment]
I'm going to merge #88974 shortly, but I don't think this interferes with anything here

**Comment by Sirraide** [comment]
> I'm going to merge #88974 shortly, but I don't think this interferes with anything here

Yeah, it seems orthogonal to this patch from what I can tell at least.

File: clang/test/SemaCXX/cxx2b-deducing-this.cpp (hunk 1 above)
Comment (Sirraide) [reply clang/test/SemaCXX/cxx2b-deducing-this.cpp]: Done.

**Comment by Sirraide** [comment]
CI failure before seems to have been due to us running out of memory compiling flang from what I can tell?

**Comment by Sirraide** [comment]
ping

File: clang/include/clang/Basic/DiagnosticSemaKinds.td [hunk 3]
```diff
@@ -7525,6 +7525,8 @@ def err_explicit_object_parameter_mutable: Error<
 def err_invalid_explicit_object_type_in_lambda: Error<
   "invalid explicit object parameter type %0 in lambda with capture; "
   "the type must be the same as, or derived from, the lambda">;
+def err_explicit_object_parameter_invalid: Error<
+  "an explicit object parameter is not allowed here">;
```
[the remark this answers is not in the document]
Comment (Sirraide) [reply clang/include/clang/Basic/DiagnosticSemaKinds.td:7529]: I’d have to somehow figure out what ‘here’ is for that... is the `DeclaratorContext` enough to deduce that reliably, or is there some other way of knowing that?

Alternatively, something like ‘an explicit object parameter can only appear as the first argument in a member function’, would also be an option.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 4]
```diff
@@ -11463,6 +11463,23 @@ void Sema::CheckExplicitObjectMemberFunction(Declarator &D,
...
+  //
+  // struct S {
+  //   struct T {
+  //     int f(this T);
+  //   };
+  //
+  //   friend int T::f(this T); // Allow this.
+  //   friend int f(this S);    // But disallow this.
+  // };
+  if (D.getDeclSpec().isFriendSpecified() && D.getCXXScopeSpec().isEmpty()) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaDeclCXX.cpp:11476]: did you consider 

` friend int SomeNamespace::f(this T);` ?

Comment (Sirraide) [reply clang/lib/Sema/SemaDeclCXX.cpp:11476]: I’m candidly not sure anymore; I’ll add a test for that if there isn’t already one.

Comment (Sirraide) [reply clang/lib/Sema/SemaDeclCXX.cpp]: Both of these cases are now diagnosed.

File: clang/include/clang/Basic/DiagnosticSemaKinds.td (hunk 3 above)
[the remark this answers is not in the document]
Comment (Sirraide) [reply clang/include/clang/Basic/DiagnosticSemaKinds.td:7551]: I’ve changed it to ‘an explicit object parameter can only appear as the first parameter of a member function’; while still not great, it at least gives some more indication as to what the problem is. I’m not sure how easy/helpful it would be to give more detailed diagnostics for cases such as
```c++
struct S {
    int (S::*x)(this int);
    int h(int x, int (*)(this S))
};
```

**Comment by Sirraide** [comment]
ping

**Comment by Sirraide** [comment]
ping

**Review by AaronBallman — APPROVED** [review]
LGTM -- @cor3ntin, are you happy with the changes as well?

File: clang/lib/Sema/SemaType.cpp [hunk 5]
```diff
@@ -4845,6 +4845,61 @@ static TypeSourceInfo *GetFullTypeForDeclarator(TypeProcessingState &state,
...
       // return type accordingly.
       if (!D.isInvalidType()) {
+        auto IsClassType = [&](CXXScopeSpec &SS) {
+          // If there already was an problem with the scope, don’t issue another
+          // error about the explicit object parameter.
+          return SS.isInvalid() ||
+                 isa_and_present<CXXRecordDecl>(S.computeDeclContext(SS));
+        };
+
+        // [dcl.fct]p6:
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaType.cpp:4855]:
```suggestion
        // C++23 [dcl.fct]p6:
```

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit
Thanks for working on this
