### PR TITLE
[clang] CTAD alias: fix the transformation for the require-clause expr

### LINKED ISSUE #90177: CTAD: incorrect transformed require-clause for the alias deduction guide
Example:

```
struct Key1  {};

template <class Key>
struct Foo {
  Foo(Key);
};

template <class D>
constexpr bool C = sizeof(D);

template <class Key>
  requires (C<Key>)
Foo(Key) -> Foo<Key>;

template <class T>
struct HasTemplateParam {
  template <class Key>
  using Alias = Foo<Key>;
};

class Forward;
struct Test : HasTemplateParam<Forward> {
  using Foo1 = decltype(Alias{
    Key1(),
  });
};
```

clang rejects the above valid code with the following diagnostics:

```
<source>:9:20: error: invalid application of 'sizeof' to an incomplete type 'Forward'
    9 | constexpr bool C = sizeof(D);
      |                    ^~~~~~~~~
<source>:12:13: note: in instantiation of variable template specialization 'C<Forward>' requested here
   12 |   requires (C<Key>)
      |             ^
<source>:12:13: note: while substituting template arguments into constraint expression here
   12 |   requires (C<Key>)
      |             ^~~~~~
<source>:23:25: note: while checking constraint satisfaction for template '<deduction guide for Alias><Forward>' required here
   23 |   using Foo1 = decltype(Alias{
      |                         ^~~~~
<source>:23:25: note: in instantiation of function template specialization 'HasTemplateParam<Forward>::<deduction guide for Alias><Key1>' requested here
<source>:21:7: note: forward declaration of 'Forward'
   21 | class Forward;
```

It seems to be an issue in the transformed require-clause for the alias deduction guide. The require expression should be evaluated on  the type `Key1`, rather than the outer type `Forward`.

### PR DESCRIPTION
**Pull request by hokein**
In the clang AST, constraint nodes are deliberately not instantiated unless they are actively being evaluated. Consequently, occurrences of template parameters in the require-clause expression have a subtle "depth" difference compared to normal occurrences in places, such as function parameters. When transforming the require-clause, we must take this distinction into account.

The existing implementation overlooks this consideration. This patch is to rewrite the implementation of the require-clause transformation to address this issue.

Fixes #90177

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -2744,31 +2744,155 @@ bool hasDeclaredDeductionGuides(DeclarationName Name, DeclContext *DC) {
   return false;
 }
 
+unsigned getTemplateDepth(NamedDecl *TemplateParam) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:2747]: are we in an anonymous namespace?  Else this should be 'static'.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 2]
```diff
@@ -2744,31 +2744,155 @@ bool hasDeclaredDeductionGuides(DeclarationName Name, DeclContext *DC) {
...
   llvm_unreachable("Unhandled template parameter types");
 }
 
-Expr *transformRequireClause(Sema &SemaRef, FunctionTemplateDecl *FTD,
-                             llvm::ArrayRef<TemplateArgument> TransformedArgs) {
-  Expr *RC = FTD->getTemplateParameters()->getRequiresClause();
+// Transform the require-clause of F if any.
+// The return result is expected to be the require-clause for the synthesized
+// alias deduction guide.
+Expr *transformRequireClause(
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplate.cpp:2776]: Same question/etc here.

**Review by erichkeane — APPROVED** [review]
I think this makes sense, 2 nits, else LGTM.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 1 above)
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2747]: I think this is potentially misleading, as we already have multiple unrelated `getTemplateDepth`, see `Sema.h` / `SemaTemplate.cpp`, `DeclBase.h`, `Expr.h`.

File: clang/lib/Sema/SemaTemplate.cpp [hunk 3]
```diff
@@ -2744,31 +2744,155 @@ bool hasDeclaredDeductionGuides(DeclarationName Name, DeclContext *DC) {
...
+    // as we go.
+    MultiLevelTemplateArgumentList Args;
+    Args.setKind(TemplateSubstitutionKind::Rewrite);
+    Args.addOuterTemplateArguments(AdjustedAliasTemplateArgs);
+    NamedDecl *NewParam = transformTemplateParameter(
+        SemaRef, AliasTemplate->getDeclContext(), TP, Args,
+        /*NewIndex=*/AdjustedAliasTemplateArgs.size(),
+        getTemplateDepth(TP) + AdjustDepth);
+
+    auto NewTemplateArgument = Context.getCanonicalTemplateArgument(
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2822]: Why do we need to canonicalize the argument here?

File: clang/lib/Sema/SemaTemplate.cpp (hunk 1 above)
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplate.cpp:2747]:
```suggestion
unsigned getTemplateParameterDepth(NamedDecl *TemplateParam) {
```

File: clang/lib/Sema/SemaTemplate.cpp [hunk 4]
```diff
@@ -2744,31 +2744,155 @@ bool hasDeclaredDeductionGuides(DeclarationName Name, DeclContext *DC) {
...
+  //   2) When substituting on the require-clause expr of the underlying
+  //   deduction guide, we must use the entire set of template argument lists.
+  //
+  // It's important to note that we're performing this transformation on an
+  // *instantiated* AliasTemplate.
+
+  // For 1), if the alias template is nested within a class template, we
+  // calcualte the 'uninstantiated' depth by adding the substitution level back.
+  unsigned AdjustDepth = 0;
+  if (auto *PrimaryTemplate = AliasTemplate->getInstantiatedFromMemberTemplate())
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:2804]: Should it be a while loop?

File: clang/lib/Sema/SemaTemplate.cpp [hunk 5]
```diff
@@ -2744,31 +2744,155 @@ bool hasDeclaredDeductionGuides(DeclarationName Name, DeclContext *DC) {
...
+  // Particularly, for the `Foo` deduction guide inside the `Outer<int>`:
+  //
+  //   - occurrence of U in the require-expression is [depth:1, index:0]
+  //   - occurrence of U in the function parameter is [depth:0, index:0]
+  //   - the template parameter of U is [depth:0, index:0]
+  //
+  // We add the outer template arguments which is [int] to the multi-level arg
+  // list to ensure that the occurrence U in `C<U>` will be replaced with int
+  // during the substitution.
+  if (F->getInstantiatedFromMemberTemplate()) {
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:2884]: Ditto. Do we want to use the “primary” template after possibly multiple transformations?

File: clang/lib/Sema/SemaTemplate.cpp (hunk 1 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Yeah, we're in an anonymous namespace.

Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Renamed to `getTemplateParameterDepth` per your suggestion.

Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp]: Done.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 2 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp:2776]: We're in an anonymous namespace.

File: clang/lib/Sema/SemaTemplate.cpp (hunk 3 above)
Comment (hokein) [reply clang/lib/Sema/SemaTemplate.cpp:2823]: Probably not needed, and I think avoiding the use of canonical types can lead to a more optimal AST, see #79798. We've already used this pattern in the `ConvertConstructorToDeductionGuideTransform`, and the current implementation here simply follows it.

However, addressing this issue is not the primary focus of this PR. It might be more appropriate to address it in a separate patch.

**Comment by hokein** [comment]
I'm merging it now (happy to address any post-comments).
