### PR TITLE
[clang] Predefine `_CRT_USE_BUILTIN_OFFSETOF` in MS-compatible modes

### LINKED ISSUE #59689: offsetof() is not constant in clang-cl
I use `offsetof` in a template parameter, this works on all compilers (Clang, MSVC, GCC) except clang-cl.

```console
error: non-type template argument is not a constant expression

C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stddef.h(47,31): note: 
      expanded from macro 'offsetof'
  ...offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))    
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    
```

Obviously `reinterpret_cast` is not constant evaluable. So I guess MSVC provides a builtin, but clang-cl does not?

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
This patch makes Clang predefine `_CRT_USE_BUILTIN_OFFSETOF` in MS-compatible modes. The macro can make the `offsetof` provided by MS UCRT's `<stddef.h>` to select the `__builtin_offsetof` version, so with it Clang (Clang-cl) can directly consume UCRT's `offsetof`.

MSVC predefines the macro as `1` since at least VS 2017 19.14, but I think it's also OK to define it in "older" compatible modes.

Fixes #59689.

### CODE REVIEW

File: clang/lib/Basic/Targets/OSTargets.cpp [hunk 1]
```diff
@@ -220,6 +220,8 @@ static void addVisualCDefines(const LangOptions &Opts, MacroBuilder &Builder) {
     Builder.defineMacro("_MSC_FULL_VER", Twine(Opts.MSCompatibilityVersion));
     // FIXME We cannot encode the revision information into 32-bits
     Builder.defineMacro("_MSC_BUILD", Twine(1));
+    // https://github.com/llvm/llvm-project/issues/59689
```
Comment (AaronBallman) [inline clang/lib/Basic/Targets/OSTargets.cpp:223]:
```suggestion
    // Exposed by MSVC, used in their stddef.h.
```

File: clang/test/Sema/offsetof-ucrt.c [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// RUN: %clang_cc1 %s -triple i686-pc-win32 -fsyntax-only -verify -fms-compatibility
```
Comment (AaronBallman) [inline clang/test/Sema/offsetof-ucrt.c:1]: We should have a RUN line which is not `-fms-compatibility` to show we don't define it in that case.

File: clang/test/Sema/offsetof-ucrt.c [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+// expected-no-diagnostics
+
+typedef __typeof__(sizeof(0)) size_t;
+
+#if defined _MSC_VER && !defined _CRT_USE_BUILTIN_OFFSETOF
```
Comment (AaronBallman) [inline clang/test/Sema/offsetof-ucrt.c:6]: We should also have a test for `#ifdef _CRT_USE_BUILTIN_OFFSETOF` to make it clear that we're testing that the macro is predefined.

File: clang/test/Sema/offsetof-ucrt.c (hunk 2 above)
Comment (frederick-vs-ja) [reply clang/test/Sema/offsetof-ucrt.c:1]: Added. I decided to add the positive and negative tests together. Luckily, UCRT's `<stddef.h>` selects `__builtin_offsetof` when `_MSC_VER` isn't defined.

**Review by AaronBallman — APPROVED** [review]
LGTM! When landing, please add a release note to `clang/docs/ReleaseNotes.rst` so users know about the change.
