### PR TITLE
[Clang] fix range calculation for conditionals with throw expressions

### LINKED ISSUE #111854: [clang++] Assertion `BT->isInteger()' failed.
**This testcase is generated by a fuzzer.**

Compiler Explorer: [https://godbolt.org/z/ssjrK4bEz](https://godbolt.org/z/ssjrK4bEz)

This valid code will crash on Clang Assertion Trunk, it seems that this goes back to clang-12:
```cpp
void foo() {
    (true ? throw 0 : 0) <= 0;
}
```

Stack dump:
```
clang++: /root/llvm-project/clang/lib/Sema/SemaChecking.cpp:9433: static {anonymous}::IntRange {anonymous}::IntRange::forValueOfCanonicalType(clang::ASTContext&, const clang::Type*): Assertion `BT->isInteger()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:3:1: current parser token '}'
2.	<source>:1:12: parsing function body 'foo'
3.	<source>:1:12: in compound statement ('{}')
 #0 0x0000000003ba3408 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ba3408)
 #1 0x0000000003ba10cc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ba10cc)
 #2 0x0000000003aee328 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000070784b642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000070784b6969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000070784b642476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000070784b6287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000070784b62871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000070784b639e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006855db1 (anonymous namespace)::IntRange::forValueOfType(clang::ASTContext&, clang::QualType) SemaChecking.cpp:0:0
#10 0x000000000685df83 GetExprRange(clang::ASTContext&, clang::Expr const*, unsigned int, bool, bool) SemaChecking.cpp:0:0
#11 0x000000000685de96 GetExprRange(clang::ASTContext&, clang::Expr const*, unsigned int, bool, bool) SemaChecking.cpp:0:0
#12 0x0000000006870534 CheckTautologicalComparison(clang::Sema&, clang::BinaryOperator*, clang::Expr*, clang::Expr*, llvm::APSInt const&, bool) SemaChecking.cpp:0:0
#13 0x0000000006889cb3 AnalyzeImplicitConversions(clang::Sema&, clang::Expr*, clang::SourceLocation, bool) (.constprop.0) SemaChecking.cpp:0:0
#14 0x000000000688a7f5 clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x688a7f5)
#15 0x0000000006d591ac clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d591ac)
#16 0x00000000070fd3ee clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x70fd3ee)
#17 0x0000000006734304 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6734304)
#18 0x000000000672a63c clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x672a63c)
#19 0x000000000672b550 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x672b550)
#20 0x000000000672c425 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x672c425)
#21 0x000000000672db7a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x672db7a)
#22 0x00000000066409d3 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66409d3)
#23 0x0000000006675ddd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6675ddd)
#24 0x000000000663471e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x663471e)
#25 0x0000000006634ede clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6634ede)
#26 0x000000000663c673 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x663c673)
#27 0x000000000663d55d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x663d55d)
#28 0x000000000663da00 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x663da00)
#29 0x000000000662fa42 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662fa42)
#30 0x00000000044fabf8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44fabf8)
#31 0x00000000047b4579 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47b4579)
#32 0x000000000473311e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x473311e)
#33 0x000000000489a0ee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x489a0ee)
#34 0x0000000000cd9fcf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcd9fcf)
#35 0x0000000000cd1cda ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#36 0x000000000453e8c9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#37 0x0000000003aee7d4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3aee7d4)
#38 0x000000000453eebf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#39 0x00000000045047fd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45047fd)
#40 0x00000000045058ed clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45058ed)
#41 0x000000000450d215 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x450d215)
#42 0x0000000000cd6e9f clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcd6e9f)
#43 0x0000000000ba66c4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xba66c4)
#44 0x000070784b629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#45 0x000070784b629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#46 0x0000000000cd178e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcd178e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #111854

---

The issue arises when `GetExprRange` encounters a `ConditionalOperator` with a `CXXThrowExpr`

```md
ConditionalOperator 0x1108658e0 'int'
|-CXXBoolLiteralExpr 0x110865878 '_Bool' true
|-CXXThrowExpr 0x1108658a8 'void'
| `-IntegerLiteral 0x110865888 'int' 0
`-IntegerLiteral 0x1108658c0 'int' 0
```

https://github.com/llvm/llvm-project/blob/ed3d05178274890fb804f43ae1bcdfd33b5fd8f0/clang/lib/Sema/SemaChecking.cpp#L9628-L9631

The current behavior causes the `GetExprRange` to proceed with the throw expression (`CO->getTrueExpr()`/`void` type)

### CODE REVIEW

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -9827,6 +9827,9 @@ static IntRange GetExprRange(ASTContext &C, const Expr *E, unsigned MaxWidth,
     return IntRange(BitField->getBitWidthValue(C),
                     BitField->getType()->isUnsignedIntegerOrEnumerationType());
```
Comment (a-tarasyuk) [inline clang/lib/Sema/SemaChecking.cpp:9829]: @shafik Getting the expression range for a void type isn't handled at this stage

https://github.com/llvm/llvm-project/blob/bf1a554312bd011cb2016a2c9d7e75d6fe3b02af/clang/lib/Sema/SemaChecking.cpp#L9628-L9631

Throw expressions can be handled if `CondResult` isn't treated as a boolean

https://github.com/llvm/llvm-project/blob/bf1a554312bd011cb2016a2c9d7e75d6fe3b02af/clang/lib/Sema/SemaChecking.cpp#L9633-L9644

It seems this case could be handled either before

https://github.com/llvm/llvm-project/blob/bf1a554312bd011cb2016a2c9d7e75d6fe3b02af/clang/lib/Sema/SemaChecking.cpp#L9629-L9631

or by adding a condition in the recursion call to handle void types. Which approach do you think is better? Thanks

Comment (shafik) [reply clang/lib/Sema/SemaChecking.cpp:9829]: What expr is ending up in `GetExprRange` b/c it looks like the `E = E->IgnoreParens()` should do the job? Right?

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp:9829]: The parentheses are omitted at the start of the method

 https://github.com/llvm/llvm-project/blob/ed3d05178274890fb804f43ae1bcdfd33b5fd8f0/clang/lib/Sema/SemaChecking.cpp#L9587

Comment (shafik) [reply clang/lib/Sema/SemaChecking.cpp:9829]: So why doesn't this `if` statement handle it?

https://github.com/llvm/llvm-project/blob/ed3d05178274890fb804f43ae1bcdfd33b5fd8f0/clang/lib/Sema/SemaChecking.cpp#L9625

Is this line not handling it correctly? 

https://github.com/llvm/llvm-project/blob/ed3d05178274890fb804f43ae1bcdfd33b5fd8f0/clang/lib/Sema/SemaChecking.cpp#L9637

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp:9829]: At this point, we get

```
ConditionalOperator 0x1108658e0 'int'
|-CXXBoolLiteralExpr 0x110865878 '_Bool' true
|-CXXThrowExpr 0x1108658a8 'void'
| `-IntegerLiteral 0x110865888 'int' 0
`-IntegerLiteral 0x1108658c0 'int' 0
```

nd as a result, `GetExprRange` proceeds with the throw expression (`CO->getTrueExpr()`)

https://github.com/llvm/llvm-project/blob/ed3d05178274890fb804f43ae1bcdfd33b5fd8f0/clang/lib/Sema/SemaChecking.cpp#L9628-L9631

Comment (shafik) [reply clang/lib/Sema/SemaChecking.cpp:9829]: I think that makes more sense now, can you add some of these details to the summary please.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp:9829]: I've updated the PR details

**Review by shafik — COMMENTED** [review]
After answering my questions this makes sense to me but I want a second set of eyes.

File: clang/lib/Sema/SemaChecking.cpp [hunk 2]
```diff
@@ -9827,6 +9827,9 @@ static IntRange GetExprRange(ASTContext &C, const Expr *E, unsigned MaxWidth,
...
 
+  if (GetExprType(E)->isVoidType())
+    return IntRange{0, true};
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaChecking.cpp:9831]: I think these changes are fine as-is, but I do wonder if a cleaner model for us to aim for is to make the return value `std::optional` and return no valid object in this case; a void expression has *no* values it can take, and that's different than a value range of [0,0].

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp]: @AaronBallman thanks for the feedback. Do you mean the [following changes](https://github.com/llvm/llvm-project/pull/112081/commits/9c2a745ed365449be45cd062f29c89cabde0f514)?

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp]: @AaronBallman thanks for the feedback. Do you mean the [following changes](https://github.com/llvm/llvm-project/pull/112081/commits/9c2a745ed365449be45cd062f29c89cabde0f514)?

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp]: @AaronBallman thanks for the feedback. Do you mean the [following changes](https://github.com/llvm/llvm-project/pull/112081/commits/9c2a745ed365449be45cd062f29c89cabde0f514)?

**Review by erichkeane — APPROVED** [review]
Update comment, else LGTM.

File: clang/lib/Sema/SemaChecking.cpp [hunk 3]
```diff
@@ -9582,8 +9582,10 @@ static QualType GetExprType(const Expr *E) {
 ///        particular, assume that arithmetic on narrower types doesn't leave
 ///        those types. If \c false, return a range including all possible
 ///        result values.
```
[the remark this answers is not in the document]
Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp]: @erichkeane thanks for the feedback. I've updated the comment.

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaChecking.cpp (hunk 2 above)
Comment (a-tarasyuk) [reply clang/lib/Sema/SemaChecking.cpp]: @AaronBallman @shafik if these changes look good to you, would you mind proceeding with the merge? thanks

**Comment by cor3ntin** [comment]
@a-tarasyuk do you need us to merge that for you?

**Comment by a-tarasyuk** [comment]
@cor3ntin yes, I do. I don't have permission to merge. thanks

**Comment by erichkeane** [comment]
The sanitizer failures are likely unrelated to this, but the self-build of the Flang sources might be?  Do we have evidence of those failing on other commits?
