### PR TITLE
[clang][Sema] Diagnose exceptions only in non-dependent context in discarded `try/catch/throw` blocks

### LINKED ISSUE #138939: Clang++ rejects try-catch in discarded if constexpr branch with -fno-exceptions
**Summary**:
Clang incorrectly rejects code containing a `try-catch` block inside a discarded `if constexpr` branch when compiled with `-fno-exceptions`. The `try-catch` block should not be evaluated, as it is excluded at compile-time, but Clang emits an error: `cannot use 'try' with exceptions disabled`.

**Steps to Reproduce**:
1. Create a file `test.cpp` with the following code:
   ```cpp
   template<auto enable> void foo(auto&& fnc) {
       if constexpr(enable) try{ fnc(); } catch(...){}
       else fnc();
   }

   int main(int, char**) {
       foo<false>([]{});
   }
   ```
2. Compile with:
   ```bash
   clang++ -std=c++20 -fno-exceptions -c test.cpp
   ```
3. Alternatively, see the issue on [Godbolt](https://godbolt.org/z/3ecnde5z4): https://godbolt.org/z/3ecnde5z4

**Actual Results**:
```
test.cpp:2:25: error: cannot use 'try' with exceptions disabled
    if constexpr(enable) try{ fnc(); } catch(...){}
                         ^
1 error generated.
```

**Expected Results**:
The code should compile successfully, as the `try-catch` block is in a discarded `if constexpr` branch and should not be evaluated.

**Additional Information**:
- The code compiles successfully with GCC
- A not called template function with try-catch block rejected too ([Godbolt](https://godbolt.org/z/4nb3vcYTo))

### PR DESCRIPTION
**Pull request by Rajveer100**
Resolves #138939

When enabling `--fno-exceptions` flag, discarded statements containing `try/catch/throw` in an independent context can be avoided from being rejected.

### CODE REVIEW

**Comment by Rajveer100** [comment]
@erichkeane 
As expected the following case is being accepted, which shouldn't happen, let me know what you recommend to diagnose this:

```c++
template <typename T> void foo() {
  try {
  } catch (...) {
  }
  throw 1;
}
void bar2() { foo<int>(); }
```

**Comment by cor3ntin** [comment]
@Rajveer100 I think instead of looking at the context, we should check if the expression (`Ex`) is instantiation dependent

**Comment by erichkeane** [comment]
> @Rajveer100 I think instead of looking at the context, we should check if the expression (`Ex`) is instantiation dependent

I don't think we can just check the expression, the 'throw' itself could be completely fine.  Consider:

```
template<typename T> void foo() {
  throw 1;
```
The expression is NOT dependent, but we don't wanna diagnose anyway unless it is instantiated.


> @erichkeane As expected the following case is being accepted, which shouldn't happen, let me know what you recommend to diagnose this:
> 
> ```c++
> template <typename T> void foo() {
>   try {
>   } catch (...) {
>   }
>   throw 1;
> }
> void bar2() { foo<int>(); }
> ```

What we will have to do likely is move the checking for this to some piece of common code that is used by TreeTransform for these two.  I haven't looked at a good place, but you'll probably see `TransformCXXThrowExpr` (and an equiv for `try`) that will call a rebuild/etc type function, which should then call the `build` (or some variety of a check function).

Also note, even in THOSE cases we have to properly check the decl context, since it could be a partial specialization/instantiation, so please make sure those are tested as well!

**Comment by Rajveer100** [comment]
> @Rajveer100 I think instead of looking at the context, we should check if the expression (`Ex`) is instantiation dependent

Checking the expression causes a crash:

<details><summary>Details</summary>
<p>

```shell
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -fsyntax-only -verify -std=c++20 /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp
1.	/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp:24:8: current parser token ';'
2.	/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp:22:1: parsing namespace 'test1'
3.	/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp:23:10: parsing function body 'test1::f'
4.	/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp:23:10: in compound statement ('{}')
 #0 0x000000010954d198 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10538d198)
 #1 0x000000010954d71c PrintStackTraceSignalHandler(void*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10538d71c)
 #2 0x000000010954b584 llvm::sys::RunSignalHandlers() (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10538b584)
 #3 0x000000010954dfe8 SignalHandler(int, __siginfo*, void*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10538dfe8)
 #4 0x00000001876af624 (/usr/lib/system/libsystem_platform.dylib+0x1804ab624)
 #5 0x000000010a1ef9cc clang::Expr::isInstantiationDependent() const (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10602f9cc)
 #6 0x000000010d507f54 clang::Sema::BuildCXXThrow(clang::SourceLocation, clang::Expr*, bool) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x109347f54)
 #7 0x000000010d507df0 clang::Sema::ActOnCXXThrow(clang::Scope*, clang::SourceLocation, clang::Expr*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x109347df0)
 #8 0x000000010cd0e954 clang::Parser::ParseThrowExpression() (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108b4e954)
 #9 0x000000010ccec734 clang::Parser::ParseAssignmentExpression(clang::TypeCastState) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108b2c734)
#10 0x000000010ccec620 clang::Parser::ParseExpression(clang::TypeCastState) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108b2c620)
#11 0x000000010cd88a2c clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bc8a2c)
#12 0x000000010cd86d74 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bc6d74)
#13 0x000000010cd865e0 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bc65e0)
#14 0x000000010cd8f1f8 clang::Parser::ParseCompoundStatementBody(bool) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bcf1f8)
#15 0x000000010cd90914 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bd0914)
#16 0x000000010cdb078c clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bf078c)
#17 0x000000010cc8d06c clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108acd06c)
#18 0x000000010cdaf884 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bef884)
#19 0x000000010cdaee10 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108beee10)
#20 0x000000010cdae00c clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bee00c)
#21 0x000000010ccbee98 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108afee98)
#22 0x000000010ccbe458 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108afe458)
#23 0x000000010cc8baf0 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108acbaf0)
#24 0x000000010cdadaf8 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bedaf8)
#25 0x000000010cdac010 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108bec010)
#26 0x000000010cc70f38 clang::ParseAST(clang::Sema&, bool, bool) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x108ab0f38)
#27 0x000000010b0dd6a4 clang::ASTFrontendAction::ExecuteAction() (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x106f1d6a4)
#28 0x000000010b0dcf38 clang::FrontendAction::Execute() (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x106f1cf38)
#29 0x000000010aff394c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x106e3394c)
#30 0x000000010b21832c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10705832c)
#31 0x00000001041d1b34 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x100011b34)
#32 0x00000001041c3700 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x100003700)
#33 0x00000001041c2424 clang_main(int, char**, llvm::ToolContext const&) (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x100002424)
#34 0x00000001041fcf0c main (/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21+0x10003cf0c)
#35 0x00000001872d6b4c 
/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/tools/clang/test/SemaCXX/Output/no-exceptions.cpp.script: line 1: 31304 Segmentation fault: 11  /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang -cc1 -internal-isystem /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/clang/21/include -nostdsysteminc -fsyntax-only -verify -std=c++20 /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/clang/test/SemaCXX/no-exceptions.cpp

--

********************
********************
Failed Tests (1):
  Clang :: SemaCXX/no-exceptions.cpp


Testing Time: 7.40s

Total Discovered Tests: 1
  Failed: 1 (100.00%)
```

</p>
</details>

> What we will have to do likely is move the checking for this to some piece of common code that is used by TreeTransform for these two. I haven't looked at a good place, but you'll probably see TransformCXXThrowExpr (and an equiv for try) that will call a rebuild/etc type function, which should then call the build (or some variety of a check function).

Also note, even in THOSE cases we have to properly check the decl context, since it could be a partial specialization/instantiation, so please make sure those are tested as well!

I will have a look.

**Comment by Rajveer100** [comment]
Moving the checks does work for these limited cases, but now that we don't have them there, one of the old tests now doesn't show up the diagnosis:

```c++
void f() {
  throw;
}

void g() {
  try {
    f();
  } catch (...) {
  }
}
```

Since there is a separate call:

```c++
return Actions.ActOnCXXTryBlock(TryLoc, TryBlock.get(), Handlers);
```

and debugging under lldb breakpoints don't reach (i.e exit) the transform calls.

**Comment by AaronBallman** [comment]
> > Moving the checks does work for these limited cases, but now that we don't have them there, one of the old tests now doesn't show up the diagnosis:
> > ```c++
> > void f() {
> >   throw;
> > }
> > 
> > void g() {
> >   try {
> >     f();
> >   } catch (...) {
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since there is a separate call:
> > ```c++
> > return Actions.ActOnCXXTryBlock(TryLoc, TryBlock.get(), Handlers);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and debugging under lldb, breakpoints don't reach (i.e exit early) the transform calls.
> 
> Right, 'transform' only happens during template instantiation. So we need to find 'some place' (that is a seperate function) to do these diagnostics. I might suggest doing a new one, since there doesn't seem to be a sensible place to do so otherwise... perhaps something like:
> 
> ```
> void Sema::DiagnoseExceptionUse(bool isTry) {
> // do the checking + diagnostic here, but have it check the decl-context for dependence
> }
> ```
> 
> NOTE I had that return `void` instead of `bool`. (And is `Diagnose` instead of `Check`). I wonder if there is value to continuing (@AaronBallman??) and putting these in the AST anyway? The continued checking is perhaps valuable, and tooling might appreciate it in the AST anyway.

Naively, I think `-fno-cxx-exceptions` would mean that `try`, `catch`, and `throw` are not even keywords; you're opting into a language dialect where exceptions simply don't exist at all. (`noexcept` is a bit of an outlier, I think the keyword should still exist, but I think `noexcept(false)` should be a semantic diagnostic.) However, that's not how Clang or GCC have traditionally behaved with this option.

GCC's behavior seems to be "if the code is outside of a discarded statement, then diagnose exception constructs, otherwise do not diagnose exception constructs but still validate that they're otherwise correct" which... is a choice: https://godbolt.org/z/36x5qM4dG GCC documents this as a codegen option so it kind of makes sense from that perspective: https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#Code-Gen-Options but then they diagnose even when codegen is not enabled, which is confusing: https://godbolt.org/z/fWfzb94e8

Clang's behavior is: "yell, yell loudly, yell as often as you can, don't ever stop yelling", which is... a worse choice: https://godbolt.org/z/75Y3dMr87 Clang documents this as "enabling C++ exceptions" which is completely vague and unhelpful: https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fcxx-exceptions Directly below, we use the same phrasing for `-fcxx-modules`/`-fno-cxx-modules`, which behaves how I would expect by disabling the keywords: https://godbolt.org/z/eq4K8E7Mr So our docs are inconsistent as well as unhelpful. :-/

What are the use cases for disabling exceptions but still allowing the constructs in source? e.g., do we want to start disabling the keywords entirely, and thus they won't appear in the AST? Or do we want them to be a codegen-only option, at which point they do appear in the AST and we only diagnose at CodeGen time (which is also inconsistent with GCC)? Or do we want to do whatever GCC does? (Note, Clang has -fcxx-exceptions and GCC does not, so we're already somewhat inconsistent between the two compilers.)

**Comment by erichkeane** [comment]
>What are the use cases for disabling exceptions but still allowing the constructs in source? e.g., do we want to start disabling the keywords entirely, and thus they won't appear in the AST? Or do we want them to be a codegen-only option, at which point they do appear in the AST and we only diagnose at CodeGen time (which is also inconsistent with GCC)? Or do we want to do whatever GCC does? (Note, Clang has -fcxx-exceptions and GCC does not, so we're already somewhat inconsistent between the two compilers.)

Yep, thats the question :)  I think the 1st one (ignoring the construct entirely/stop trying to parse it at all/etc) is a worse experience, and inconsistent with history.  AND I wouldn't want people to have a C++ code dialect where they can use 'try' as a variable name.

I don't think we should diagnose at CODEGEN time.  I'm suggesting diagnosing them at 'non-dependent/non-discarded' time, but putting them in the AST anyway.  This will inhibit codegen, but would mean tooling would be able to see them anyway.  WHICH they'll have to do for dependent contexts anyway with the change.

**Comment by cor3ntin** [comment]
In C++26, exceptions are allowed in a constant evaluated context, which is used extensively by reflection and maybe P2300. I also think allowing `try` not to be a keyword in some modes would harm the ecosystem.

Here is an interesting scenario 

```cpp
constexpr void g() {
   throw 42;
} 

constexpr int f() {
   try {g(); } catch {}
   return 0;
}
```

static_assert(f() == 0); // the call to g() from here should be allowed

int main() {
  return f(); //  but not here if we want to disallow exceptions
}

```

So, now that I think about it, doing it at code gen is the only solution post C++26

**Comment by AaronBallman** [comment]
> In C++26, exceptions are allowed in a constant evaluated context, which is used extensively by reflection and maybe P2300.

Good point. :-/

> I also think allowing `try` not to be a keyword in some modes would harm the ecosystem.

[citation needed]

You already cannot safely link code which disables exceptions into code which enables exceptions due to ABI issues, so I'm really not certain what harm would come from letting users use these identifiers themselves if they elect to ignore the language feature.

> Here is an interesting scenario
> 
> ```c++
> constexpr void g() {
>    throw 42;
> } 
> 
> constexpr int f() {
>    try {g(); } catch {}
>    return 0;
> }
> static_assert(f() == 0); // the call to g() from here should be allowed
> 
> int main() {
>   return f(); //  but not here if we want to disallow exceptions
> }
> ```
> 
> So, now that I think about it, doing it at code gen is the only solution post C++26

I disagree. If the user disabled exceptions, why would they expect them to work in constant expressions?

**Comment by Rajveer100** [comment]
I feel like this issue is a little too niche to be adding such complexity, maybe just covering those specific uses cases before codegen might be the way to go?

**Comment by erichkeane** [comment]
> > I feel like this issue is a little too niche to be adding such complexity, maybe just covering those specific uses cases before codegen might be the way to go?
> 
> I think disabling the keywords entirely is a large ask (requires an RFC at a minimum) and so we don't need to go down that route right now.

I would be against said RFC.  If you asked me in 1996/whatever, I could be talked into it.  But we're 30+ years of this behavior.

> 
> I think `constexpr` exceptions are a red herring; if the user disabled C++ exceptions, they should be disabled at compile time same as at runtime. Some users disable exceptions because of overhead, but plenty of users also disable exceptions because of difficulties with reasoning about flow control (some style guides explicitly require exceptions to not be used, for example).

I'm coming around on this one, I think I agree.  -fno-exceptions means `no-exceptions`.  IF we get a further feature request to allow them to work at const-eval time, perhaps we can consider that, but it seems reasonable to do the disallow at the 'fully instantiated' point as I suggested above.

> 
> Since we currently validate that the exception constructs are semantically valid, I think we may as well retain them in the AST for now. It's how we currently behave: https://godbolt.org/z/xPbEPWTK8 so it would be consistent to do so in discarded statements too.

**Comment by AaronBallman** [comment]
> I would be against said RFC. If you asked me in 1996/whatever, I could be talked into it. But we're 30+ years of this behavior.

Doesn't stop WG21 from changing the behavior 30 years later. ;-) My biggest concern is actually that C++ is changing exception handling such that we can no longer hand-wave what this flag means. Does it mean exceptions are enabled or not? If exceptions are not enabled, why are we requiring their use to be correct in source? And why do we want this flag to behave differently from other dialect flags like `-fno-modules` (https://godbolt.org/z/e77sG6Y7d), `-fno-char8_t` (https://godbolt.org/z/xan9d5M1P), `-fno-wchar` (https://godbolt.org/z/7nzeeY4Mq), etc. In fact, as best I can tell, this is the only language dialect mode where we don't act as though we don't know about the keywords.

I think the important question is: what breaks if we were to do this? As best I can tell, nothing. Existing code using the flag continues to behave exactly as it did before, same with existing code not using the flag. The only issue boils down to users writing new code and trying to combine it with other TUs that are not compiled with the flag; but that's invalid anyway for ABI reasons, so I'm not seeing where the concerns are.

**Comment by erichkeane** [comment]
> > I would be against said RFC. If you asked me in 1996/whatever, I could be talked into it. But we're 30+ years of this behavior.
> 
> Doesn't stop WG21 from changing the behavior 30 years later. ;-) My biggest concern is actually that C++ is changing exception handling such that we can no longer hand-wave what this flag means. Does it mean exceptions are enabled or not? If exceptions are not enabled, why are we requiring their use to be correct in source? And why do we want this flag to behave differently from other dialect flags like `-fno-modules` (https://godbolt.org/z/e77sG6Y7d), `-fno-char8_t` (https://godbolt.org/z/xan9d5M1P), `-fno-wchar` (https://godbolt.org/z/7nzeeY4Mq), etc. In fact, as best I can tell, this is the only language dialect mode where we don't act as though we don't know about the keywords.
> 
> I think the important question is: what breaks if we were to do this? As best I can tell, nothing. Existing code using the flag continues to behave exactly as it did before, same with existing code not using the flag. The only issue boils down to users writing new code and trying to combine it with other TUs that are not compiled with the flag; but that's invalid anyway for ABI reasons, so I'm not seeing where the concerns are.

I don't want to change the behavior that drastically.  Folks are USED to this, and we should just stick to it.  Putting them back into 'this could be an identifier' is a bit of extra FE headache at the cost of being 'different' on this than everyone else.  IMO its not worth the effort nor difference.  We should just stick to our current behavior, except allow discarded/uninstantiated statements.

**Comment by erichkeane** [comment]
So @Rajveer100 : I think I bottomed out with Aaron.  I think the solution of 'create a function to diagnose these, but only if not in a dependent `DeclContext`', then call this both from where we do the current checking, plus during `TreeTransform` of these things is the 'right' way forward.  So you're close!

We can discuss the REST of the proposals/ideas in the future if we get an RFC from someone.

In addition, I think there is value to considering an additional flag that works with `-fno-exceptions`/etc to allow in `consteval` functions, which I think gets us most of the `constexpr` uses that folks will care about, and be implimentable trivially after this patch is merged.

**Comment by AaronBallman** [comment]
> So @Rajveer100 : I think I bottomed out with Aaron. I think the solution of 'create a function to diagnose these, but only if not in a dependent `DeclContext`', then call this both from where we do the current checking, plus during `TreeTransform` of these things is the 'right' way forward. So you're close!

Agreed, thank you for the discussion!

**Comment by Sirraide** [comment]
> In addition, I think there is value to considering an additional flag that works with `-fno-exceptions`/etc to allow in `consteval` functions, which I think gets us most of the `constexpr` uses that folks will care about, and be implimentable trivially after this patch is merged.

Yeah, I agree there should be some way to enable exceptions only during constant evaluation once we support that.

**Comment by Rajveer100** [comment]
I am actually facing an issue all of a sudden after rebasing and deletion of build folder:


```shell
rajveersingh@MacBook-Pro llvm-project % build/bin/clang++ -std=c++20 -fno-exceptions debug-clang-138939.cpp -v                                                                     
clang version 21.0.0git (git@github.com:Rajveer100/llvm-project.git 46a9b0193bb5bdb9a082582f19e7a32ac2a3973d)
Target: arm64-apple-darwin24.4.0
Thread model: posix
InstalledDir: /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin
Build config: +unoptimized, +assertions
ignoring nonexistent directory "/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/../include/c++/v1"
ignoring nonexistent directory "/usr/include/c++/v1"
 "/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/bin/clang-21" -cc1 -triple arm64-apple-macosx15.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -dumpdir a- -disable-free -clear-ast-before-backend -main-file-name debug-clang-138939.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -fdefine-target-os-macros -enable-tlsdesc -target-cpu apple-m1 -target-feature +zcm -target-feature +zcz -target-feature +v8.4a -target-feature +aes -target-feature +altnzcv -target-feature +ccdp -target-feature +ccpp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +flagm -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fptoint -target-feature +fullfp16 -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +predres -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sb -target-feature +sha2 -target-feature +sha3 -target-feature +specrestrict -target-feature +ssbs -target-abi darwinpcs -debugger-tuning=lldb -fdebug-compilation-dir=/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project -target-linker-version 1167.4.1 -v -fcoverage-compilation-dir=/Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project -resource-dir /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/clang/21 -internal-isystem /usr/local/include -internal-isystem /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/clang/21/include -internal-externc-isystem /usr/include -internal-iframework /System/Library/Frameworks -internal-iframework /System/Library/SubFrameworks -internal-iframework /Library/Frameworks -std=c++20 -fdeprecated-macro -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fmax-type-align=16 -fcolor-diagnostics -o /var/folders/4t/ztwxql616yv_ltl525j048t40000gn/T/debug-clang-138939-a6988f.o -x c++ debug-clang-138939.cpp
clang -cc1 version 21.0.0git based upon LLVM 21.0.0git default target arm64-apple-darwin24.4.0
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/System/Library/SubFrameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/clang/21/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/usr/bin/ld" -demangle -lto_library /Users/rajveersingh/GitHub-OpenSource/llvm-project/llvm-project/build/lib/libLTO.dylib -no_deduplicate -dynamic -arch arm64 -platform_version macos 15.0.0 15.0.0 -mllvm -enable-linkonceodr-outlining -o a.out /var/folders/4t/ztwxql616yv_ltl525j048t40000gn/T/debug-clang-138939-a6988f.o -lc++ -lSystem
ld: library 'c++' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Linker issues have happened sometimes in the past and I managed to resolve them, maybe this one could be for a different reason, let me know if you can help me out with this.

In the mean time, I will double check with the typical macOS DYLD stuff, Xcode CLT, etc.

**Comment by Rajveer100** [comment]
I have made the changes, let me know if this is fair enough.

File: clang/lib/Sema/SemaStmt.cpp [hunk 1]
```diff
@@ -4410,6 +4409,21 @@ StmtResult Sema::ActOnCXXTryBlock(SourceLocation TryLoc, Stmt *TryBlock,
...
+  const llvm::Triple &T = Context.getTargetInfo().getTriple();
+  const bool IsOpenMPGPUTarget =
+      getLangOpts().OpenMPIsTargetDevice && (T.isNVPTX() || T.isAMDGCN());
+
+  if (IsOpenMPGPUTarget || getLangOpts().CUDA)
+    return;
+
+  if (!getLangOpts().CXXExceptions &&
+      !getSourceManager().isInSystemHeader(Loc) &&
+      !CurContext->isDependentContext()) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaStmt.cpp:4422]: Don't use curley braces on single-line `if` bodies.

**Review by erichkeane — COMMENTED** [review]
Mostly happy, handful of changes but none are design changes.

**Review by erichkeane — APPROVED** [review]
LGTM!  I'll merge this for you, as I believe you dont' have commit rights.
