### PR TITLE
[clang] fix matching of nested template template parameters

### LINKED ISSUE #130362: [Clang] Variadic template template parameter of another template template parameter causes spurious error upon instantiation
Given the following code:

```cpp
template <template <template <typename...> typename> typename>
struct foo {};

template <template <typename> typename>
struct bar {};

using baz = foo<bar>;
```

Clang 20 produces the following error:

```
<source>:1:52: error: too few template parameters in template template parameter redeclaration
    1 | template <template <template <typename...> typename> typename>
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
    2 | struct foo {};
      | ~~~~~~~~~~~~~~
    3 | 
    4 | template <template <typename> typename>
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:7:17: note: template template argument is incompatible with its corresponding template template parameter
    7 | using baz = foo<bar>;
      |                 ^
<source>:4:39: note: template parameter is declared here
    4 | template <template <typename> typename>
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
<source>:7:17: note: template template argument is incompatible with its corresponding template template parameter
    7 | using baz = foo<bar>;
      |                 ^
<source>:1:62: note: template parameter is declared here
    1 | template <template <template <typename...> typename> typename>
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Compiler explorer link: https://godbolt.org/z/7q7n459E1

This code was accepted by Clang 19, and is accepted by GCC, MSVC, and EDG.

### PR DESCRIPTION
**Pull request by mizvekov**
When checking the template template parameters of template template parameters, the PartialOrdering context was not correctly propagated.

This also has a few drive-by fixes, such as checking the template parameter lists of template template parameters, which was previously missing and would have been it's own bug, but we need to fix it in order to prevent crashes in error recovery in a simple way.

Fixes #130362

### CODE REVIEW

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -11363,14 +11363,17 @@ class Sema final : public SemaBase {
 
   /// The context in which we are checking a template parameter list.
   enum TemplateParamListContext {
-    TPC_ClassTemplate,
-    TPC_VarTemplate,
+    // For this context, Class, Variable, TypeAlias, and non-pack Template
+    // Template
+    // Parameters are the same.
+    TPC_Normal,
```
Comment (cor3ntin) [inline clang/include/clang/Sema/Sema.h:11369]: "Normal" doesn't make sense to me. I believe that we are better off just adding 
`TPC_TemplateTemplateParameterPack` and keeping everything else the same (even though _today_ these contexts are not differentiated anywhere)

Comment (mizvekov) [reply clang/include/clang/Sema/Sema.h:11369]: No would be needing to add two actually, TPC_TemplateTemplateParameter and TPC_TemplateTemplateParameterPack.

I think the simplification is worth it, as otherwise we would always be testing four kinds together everywhere.

There is no point in differentiating these cases for the current implementation, and I hope we can find a better name and keep the simplification.

File: clang/include/clang/Sema/Sema.h [hunk 2]
```diff
@@ -11363,14 +11363,17 @@ class Sema final : public SemaBase {
...
+
     TPC_FunctionTemplate,
     TPC_ClassTemplateMember,
     TPC_FriendClassTemplate,
     TPC_FriendFunctionTemplate,
     TPC_FriendFunctionTemplateDefinition,
-    TPC_TypeAliasTemplate
+    TPC_TemplateTemplateParameterPack
```
Comment (zyn0217) [inline clang/include/clang/Sema/Sema.h:11376]: nit: Can we have a trailing comma here?

File: clang/include/clang/Sema/Sema.h (hunk 1 above)
Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:11369]: +1 "normal" sounds odd and I suppose it isn't a term used by the standard?

Comment (mizvekov) [reply clang/include/clang/Sema/Sema.h:11369]: It isn't used, but every other case is defined by some sort of exception, either in the current standard, or previous versions.

Comment (zyn0217) [reply clang/include/clang/Sema/Sema.h:11369]: Oh if that is the case then I don't think I have a better naming option :P

Comment (cor3ntin) [reply clang/include/clang/Sema/Sema.h:11369]: "Other" is what we use elsewhere

Comment (mizvekov) [reply clang/include/clang/Sema/Sema.h:11369]: Yep, I was grasping to remember. That's better, thanks.

File: clang/test/SemaTemplate/cwg2398.cpp [hunk 3]
```diff
@@ -602,6 +602,11 @@ namespace regression3 {
   template <class...> class B {};
   template struct A<B, Node<None>>;
 } // namespace regression3
+namespace regression4 {
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/cwg2398.cpp:605]:
```suggestion
namespace GH130362 {
```

File: clang/include/clang/Sema/Sema.h [hunk 4]
```diff
@@ -11363,14 +11363,16 @@ class Sema final : public SemaBase {
 
   /// The context in which we are checking a template parameter list.
   enum TemplateParamListContext {
-    TPC_ClassTemplate,
-    TPC_VarTemplate,
+    // For this context, Class, Variable, TypeAlias, and non-pack Template
+    // Template Parameters are the same.
```
Comment (cor3ntin) [inline clang/include/clang/Sema/Sema.h:11367]:
```suggestion
    // Template Parameters are treated uniformly.
```

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nits
