### PR TITLE
[clang-tidy] New option to remove arguments from the command line

### LINKED ISSUE #108455: Ignore unknown flags in clang-tidy
Now, `cmake` has started passing gcc-specific flags for modules support, which breaks `clang-tidy`. Is there a way to tell clang-tidy to ignore the flags it doesn't understand instead of erroring out?

https://gitlab.kitware.com/cmake/cmake/-/issues/26283

```shell
FAILED: my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o 
/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E __run_co_compile --launcher=/opt/homebrew/bin/ccache --tidy="/Users/runner/llvm/bin/clang-tidy;-extra-arg=-Wno-unknown-warning-option;--extra-arg-before=--driver-mode=g++" --source=/Users/runner/work/cpp_vcpkg_project/cpp_vcpkg_project/my_exe/test/tests.cpp -- /opt/homebrew/bin/g++-14 -DDO_NOT_USE_WMAIN -DCMAKE_INTDIR=\"Debug\" -I/Users/runner/work/cpp_vcpkg_project/cpp_vcpkg_project/my_exe/include -isystem /Users/runner/work/cpp_vcpkg_project/cpp_vcpkg_project/build/vcpkg_installed/arm64-osx/include -g -std=c++20 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fdiagnostics-color=always -Wall -Wextra -Wextra-semi -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast --coverage -O0 -g -MD -MT my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o -MF my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o.d -fmodules-ts -fmodule-mapper=my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o.modmap -MD -fdeps-format=p1689r5 -x c++ -o my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o -c /Users/runner/work/cpp_vcpkg_project/cpp_vcpkg_project/my_exe/test/tests.cpp
error: unknown argument: '-fdeps-format=p1689r5' [clang-diagnostic-error]
error: unknown argument: '-fmodule-mapper=my_exe/test/CMakeFiles/my_exe_lib_tests.dir/Debug/tests.cpp.o.modmap' [clang-diagnostic-error]
error: unknown argument: '-fmodules-ts' [clang-diagnostic-error]

```

This is also related to https://github.com/clangd/clangd/issues/662
Perhaps a `remove-flag` option could solve the problem.

### PR DESCRIPTION
**Pull request by felix642**
When using clang-tidy from a compilation database, some options might not be
recognized by clang if the compilation database was generated for another compiler.
This forces the user to add conditional code in their CMakeLists.txt to remove
those arguments when using clang-tidy.
A new option was added to the .clang-tidy config to remove
those unknown flags without the need to generate a second compilation_commands.json
    
Fixes #108455

Please see #111453 and #162201 for previous discussions regarding this option.
This implementation was slightly changed from the initial PR based on the following comment (https://github.com/llvm/llvm-project/pull/162201#issuecomment-3393569422).

The goal is to keep this feature as simple as possible and to make sure there aren't any side effects. So the user has to explicitly list the arguments he wants to remove. A mention was also added to warn the user that removing arguments might lead to false positive / negative if the code isn't properly recognized by the clang compiler.

### CODE REVIEW

File: clang-tools-extra/clang-tidy/ClangTidy.cpp [hunk 1]
```diff
@@ -581,6 +581,24 @@ runClangTidy(clang::tidy::ClangTidyContext &Context,
...
+            AdjustedArgs.erase(std::remove(AdjustedArgs.begin(),
+                                           AdjustedArgs.end(), ArgToIgnore),
+                               AdjustedArgs.end());
+          }
+        }
+
+        return AdjustedArgs;
+      };
+
+  Tool.appendArgumentsAdjuster(CompilationArgsToRemove);
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/ClangTidy.cpp]: Nit: for consistency with the one for `ExtraArgs`, maybe we can call this `PerFileArgumentRemover`?

File: clang-tools-extra/clang-tidy/ClangTidy.cpp [hunk 2]
```diff
@@ -581,6 +581,24 @@ runClangTidy(clang::tidy::ClangTidyContext &Context,
...
       };
 
+  // Remove unwanted arguments passed to the compiler
+  ArgumentsAdjuster CompilationArgsToRemove =
+      [&Context](const CommandLineArguments &Args, StringRef Filename) {
+        ClangTidyOptions Opts = Context.getOptionsForFile(Filename);
+        CommandLineArguments AdjustedArgs = Args;
+
+        if (Opts.RemovedArgs) {
+          for (StringRef ArgToIgnore : *Opts.RemovedArgs) {
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/ClangTidy.cpp]: `ArgToRemove`

File: clang-tools-extra/docs/clang-tidy/index.rst [hunk 3]
```diff
@@ -329,6 +329,10 @@ An overview of all the command-line options:
                                    example, to place the correct user name in
                                    TODO() comments in the relevant check.
     WarningsAsErrors             - Same as '--warnings-as-errors'.
+    RemovedArgs                  - List of arguments to remove from the command
+                                   line sent to the compiler. Please note that 
+                                   removing arguments from the command line 
+                                   might lead to false positive or negatives.
```
Comment (carlosgalvezp) [inline clang-tools-extra/docs/clang-tidy/index.rst]: What about: `might change the semantics of the analyzed code, possibly leading to crashes, false positives or false negatives`.

Comment (localspook) [reply clang-tools-extra/docs/clang-tidy/index.rst]: Warning people about false positives and negatives makes sense, but I don't think we should be telling people to expect crashes; a crash is always a bug, it's not something users should ever expect, right?

Comment (carlosgalvezp) [reply clang-tools-extra/docs/clang-tidy/index.rst]: Hmm yes, crash is a strong word. I meant more "hard compiler errors" which cannot simply be suppressed.

File: clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp [hunk 4]
```diff
@@ -355,6 +356,16 @@ see https://clang.llvm.org/extra/clang-tidy/QueryBasedCustomChecks.html.
...
                                               cl::cat(ClangTidyCategory));
 
+static cl::list<std::string> RemovedArgs("removed-arg", desc(R"(
+List of arguments to remove from the command
+                                   line sent to the compiler. Please note that
+                                   removing arguments might change the semantic
+                                   of the analzed code, possibly leading to
+                                   compiler errors, false positives or
+                                   false negatives. This option is applied 
+                                   before --extra-arg and --extra-arg-before)"),
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp]: whole text should be aligned to the left.

File: clang-tools-extra/docs/clang-tidy/index.rst [hunk 5]
```diff
@@ -329,6 +329,13 @@ An overview of all the command-line options:
                                    example, to place the correct user name in
                                    TODO() comments in the relevant check.
     WarningsAsErrors             - Same as '--warnings-as-errors'.
+    RemovedArgs                  - List of arguments to remove from the command
```
Comment (vbvictor) [inline clang-tools-extra/docs/clang-tidy/index.rst]: Could we not duplicate text and use `- Same as '--removed-arg'`

**Review by vbvictor — COMMENTED** [review]
Could you also add this option to `run-clang-tidy.py` and `clang-tidy-diff.py`. They both seem to support `extra-arg` already so we should provide `remove-arg` for them too.

File: clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp [hunk 6]
```diff
@@ -355,6 +356,16 @@ see https://clang.llvm.org/extra/clang-tidy/QueryBasedCustomChecks.html.
                                               cl::init(false),
                                               cl::cat(ClangTidyCategory));
 
+static cl::list<std::string> RemovedArgs("removed-arg", desc(R"(
```
[the remark this answers is not in the document]
Comment (carlosgalvezp) [reply clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp]: I thought about this, yes the intention is to have it as an adjective, "remove-args" sounded strange. Maybe we can find a different adjective that is not a verb :)

PS: I take it that it should be anyway plural `args` since it's a list, right?

[the remark this answers is not in the document]
Comment (carlosgalvezp) [reply clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp]: Another option was `args-to-remove` but it felt strange and inconsistent with `extra-args`.

File: clang-tools-extra/test/clang-tidy/infrastructure/removed-args.cpp [hunk 7]
```diff
@@ -0,0 +1,7 @@
+// RUN: not clang-tidy %s -- -fnot-an-option | FileCheck %s -check-prefix=INVALID-A
+// RUN: clang-tidy %s --config="{RemovedArgs: ['-fnot-an-option']}" -- -fnot-an-option
+// RUN: clang-tidy %s --config="{RemovedArgs: ['-fnot-another-option', '-fnot-an-option']}" -- -fnot-an-option -fnot-another-option
+// RUN clang-tidy %s --removed-arg="-fnot-an-option" -- -fnot-an-option -fnot-another-option | FileCheck %s -check-prefix=INVALID-B
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/infrastructure/removed-args.cpp]:
```suggestion
// RUN: clang-tidy %s --removed-arg="-fnot-an-option" -- -fnot-an-option -fnot-another-option | FileCheck %s -check-prefix=INVALID-B
```

Did the test run before? IIRC for lit to work it needs `:` token..?

File: clang-tools-extra/clang-tidy/ClangTidyOptions.h [hunk 8]
```diff
@@ -151,6 +151,9 @@ struct ClangTidyOptions {
   /// Add extra compilation arguments to the start of the list.
   std::optional<ArgList> ExtraArgsBefore;
 
+  /// Remove command line arguments sent to the compiler matching this.
+  std::optional<std::vector<std::string>> RemovedArgs;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/ClangTidyOptions.h]:
```suggestion
  std::optional<ArgList> RemovedArgs;
```

**Review by vbvictor — APPROVED** [review]
LGTM

**Comment by felix642** [comment]
I would be ready to merge this PR. I'll wait a bit more in case someone has some comments to add, but otherwise I would be ready to merge it in ~48 hours.

**Comment by felix642** [comment]
> Ah test failure is because we recently remove static-analyzer checks from default so now tidy fails by default because no checks are enabled. You should enable any check via --checks in your files or pass --allow-no-checks

Good catch, thanks for the info!

**Review by vbvictor — COMMENTED** [review]
Spot misspell at the last minute, can be merged right after it

**Comment by vbvictor** [comment]
> Hello, I'm trying to use this new option but it's only available in clang-tidy-22 which doesn't seem to be installable yet in Ubuntu 24.04, is this a known issue?

IIRC distributions are in charge of packages. But you can download binaries directly from [here](https://github.com/llvm/llvm-project/releases/tag/llvmorg-22.1.1) or try from https://apt.llvm.org/ thought I haven't used it personally
