### PR TITLE
[flang] handle alloca outside of entry blocks in MemoryAllocation

### LINKED ISSUE #88344: flang-new: forcing arrays to be allocated on the heap and a possible bug
This is related to https://github.com/llvm/llvm-project/issues/56018. 

According to https://github.com/llvm/llvm-project/issues/56018 , `flang -mmlir -fdynamic-heap-array` should force dynamic arrays to be allocated on the heap and hence avoid stackoverflows when large dynamic arrays are present.  The example mentioned at https://github.com/llvm/llvm-project/issues/56018 works but the following does not. 

```fortran
! array.f90

module outprod_mod
contains
function outprod(y, z) result(x)
implicit none
real, intent(in) :: y(:), z(:)
real :: x(size(y), size(z))
integer :: i, j, n, m

m = size(y)
n = size(z)
do i = 1, m
    do j = 1, n
        x(i, j) = y(i) * z(j)
    end do
end do
end function
end module outprod_mod

program prog
use outprod_mod, only : outprod
implicit none

integer, parameter :: k = 10000
integer :: i
real :: y(k)
y = 1.0
do i = 1, k
    write (*, *) i, size(outprod(y(1:i), y(1:i)))
end do
end
```

With flang-new, it crashes with a segfault as follows.

```text
$ uname -a && flang --version && flang -fno-stack-arrays -mmlir -fdynamic-heap-array -o array array.f90 && ./array

Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
flang-new version 19.0.0git (git@github.com:llvm/llvm-project.git 37c175af955f0aeab67e8c553a0a47b2ed0fdba2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
 ... ...
 1445 2088025
 1446 2090916
 Segmentation fault (core dumped)
```

Questions:

- What are the correct flags to effectively force dynamic arrays to be allocated on the heap? 
- `-fdynamic-heap-array` alone cannot be recognized by the  compiler. It must be `-mmlir -fdynamic-heap-array`. Is this intended?  

Notes: 
- `ulimit -s unlimited` seems to help, but we need a solution on flang's side. 
- Compiled with Classic Flang 15.0.3 without any flags, the code runs fine. 

Thank you for taking a look.

### PR DESCRIPTION
**Pull request by jeanPerier**
This patch  generalizes the MemoryAllocation pass (alloca -> heap) to handle fir.alloca regardless of their postion in the IR. Currently, it only dealt with fir.alloca in function entry blocks. The logic is placed in a utility that can be used to replace alloca in an operation on demand to whatever kind of allocation the utility user wants via callbacks (allocmem, or custom runtime calls to instrument the code...).

To do so, a concept of ownership, that was already implied a bit and used in passes like stack-reclaim, is formalized. Any operation with the LoopLikeInterface, AutomaticAllocationScope, or IsolatedFromAbove owns the alloca directly nested inside its regions, and they must not be used after the operation.

The pass then looks for the exit points of region with such interface, and use that to insert deallocation. If dominance is not proved, the pass fallbacks to storing the new address into a C pointer variable created in the entry of the owning region which allows inserting deallocation as needed, included near the alloca itself to avoid leaks when the alloca is executed multiple times due to block CFGs loops.

This should fix https://github.com/llvm/llvm-project/issues/88344.

In a next step, I will try to refactor lowering a bit to introduce lifetime operation for alloca so that the deallocation points can be inserted as soon as possible.

### CODE REVIEW

File: flang/include/flang/Optimizer/Transforms/MemoryUtils.h [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+/// Type of callbacks that produce the replacement for a given fir.alloca.
+/// It is provided extra information about the dominance of the deallocation
+/// points that have been identified, and may refuse to replace the alloca,
+/// even if the MustRewriteCallBack previously returned true, in which case
+/// it should return a null value.
+/// The callback should not delete the alloca, the utility will do it.
+using AllocaRewriterCallBack =
+    llvm::function_ref<mlir::Value(mlir::OpBuilder &, fir::AllocaOp,
+                                   bool /*allocaDominatesDeallocLocations*/)>;
```
Comment (tblah) [inline flang/include/flang/Optimizer/Transforms/MemoryUtils.h:43]: nit: why is this commented?

File: flang/include/flang/Optimizer/Transforms/MemoryUtils.h [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    llvm::function_ref<void(mlir::Location, mlir::OpBuilder &, mlir::Value)>;
+
+/// Utility to replace fir.alloca by dynamic allocations inside \p parentOp.
+/// \p MustRewriteCallBack let the user control which fir.alloca should be
+/// replaced. \p AllocaRewriterCallBack let the user define how the new memory
+/// should be allocated. \p DeallocCallBack let the user decide how the memory
+/// should be deallocated. The boolean result indicate if the utility succeeded
+/// to replace all fir.alloca as requested by the user. Causes of failures are
+/// the presence of unregistered operations, or OpenMP/ACC recipe operation that
+/// returns memory allocated inside their region.
```
Comment (tblah) [inline flang/include/flang/Optimizer/Transforms/MemoryUtils.h:56]: nit
```suggestion
/// \p MustRewriteCallBack lets the user control which fir.alloca should be
/// replaced. \p AllocaRewriterCallBack lets the user define how the new memory
/// should be allocated. \p DeallocCallBack lets the user decide how the memory
/// should be deallocated. The boolean result indicates if the utility succeeded
/// to replace all fir.alloca as requested by the user. Causes of failures are
/// the presence of unregistered operations, or OpenMP/ACC recipe operations that
/// return memory allocated inside their region.
```

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+      if (isOpenACCMPRecipe && terminatorYieldsMemory(*terminator))
+        return nullptr;
+      deallocationPoints.push_back(terminator);
+    }
+  // If the owningRegion did not adhere to the ReturnLike interface for its
+  // terminators, bail and do not attempt to translate it (we could maybe
+  // fallback to consider terminators with no block successor, but since all
+  // FIR, OpenACC, OpenMP, CUF, SCF operations with IsIsolatedFromAbove,
+  // AutomaticAllocationScope, or LoopLikeOpInterface have such terminators,
+  // avoid any untested complexity for now).
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:100]: This seems to conflict with the comment in `isRegionTerminator`

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+  // because the alloc does not properly dominates itself, so the
+  // inserted deallocation will be conditional.
+  // For now, always assume there may always be a loop if any of the
+  // deallocation point does not dominate the alloca. It is
+  // conservative approach. Bringing lifetime markers above will reduce
+  // the false positive for alloca made inside if like constructs or CFG.
+  if (!allocDominatesDealloc(alloca, deallocationPoints))
+    deallocationPoints.push_back(alloca.getOperation());
+  return owningRegion;
+}
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:116]: I'm having trouble understanding this bit. Please could you give a pseudo-IR example?

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 5]
```diff
@@ -0,0 +1,220 @@
...
+
+static mlir::Value castIfNeeed(mlir::Location loc, mlir::RewriterBase &rewriter,
+                               mlir::Type newType, mlir::Value value) {
+  if (value.getType() != newType)
+    return rewriter.create<fir::ConvertOp>(loc, newType, value);
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:121]: Doesn't `fir::ConvertOp::fold` do this already?

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 6]
```diff
@@ -0,0 +1,220 @@
...
+  // Create C pointer variable in the entry block to store the alloc
+  // and access it indirectly in the entry points that do not dominate.
+  rewriter.setInsertionPointToStart(&owningRegion.front());
+  mlir::Type heapType = fir::HeapType::get(alloca.getInType());
+  mlir::Value ptrVar = rewriter.create<fir::AllocaOp>(loc, heapType);
+  mlir::Value nullPtr = rewriter.create<fir::ZeroOp>(loc, heapType);
+  rewriter.create<fir::StoreOp>(loc, nullPtr, ptrVar);
+  // TODO: introducing a pointer compare op in FIR would help
+  // generating less IR here.
+  mlir::Type intPtrTy = rewriter.getI64Type();
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:140]: nit: is there a less platform specific type we could use for pointers? If the target information is unavailable maybe an index will always be pointer-sized?

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 7]
```diff
@@ -0,0 +1,220 @@
...
+}
+
+bool AllocaReplaceImpl::replace(mlir::RewriterBase &rewriter,
+                                fir::AllocaOp alloca) {
+  llvm::SmallVector<mlir::Operation *> deallocationPoints;
+  mlir::Region *owningRegion =
+      findDeallocationPointsAndOwner(alloca, deallocationPoints);
+  if (!owningRegion)
+    return false;
+  // return false;
```
Comment (tblah) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:181]: nit

**Review by tblah — COMMENTED** [review]
Really clean implementation here. Nice work!

**Review by psteinfeld — COMMENTED** [review]
All builds and tests correctly.  But this change is supposed to fix #88344.  But after building flang-new with these changes, the example program in that issue still gets a seg fault in the same place.

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 6 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp:140]: Index is an integer with the ["machine word size"](https://mlir.llvm.org/docs/Rationale/Rationale/#integer-signedness-semantics), it is not guaranteed to be always pointer sized. So it is not much better. I rather keep getI64Type() because it is easier to grep for (less hit, index is used a lot).

LLVM IR just uses icmp with pointer operand without any explicit cast to integer types. We likely want to have some operation to do that to avoid bothering with the target dependency for null pointer comparisons.

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 5 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp:121]: It does, it is just so cheap to check and not needed most of the time that I hate polluting the IR with them (makes IR reading harder). I will use a shared utility to avoid doing that everywhere.

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 3 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp:100]: It does, it is a left over, thanks for the catch.

File: flang/include/flang/Optimizer/Transforms/MemoryUtils.h (hunk 1 above)
Comment (jeanPerier) [reply flang/include/flang/Optimizer/Transforms/MemoryUtils.h:43]: I thought I could not name argument here and did not even try, thanks!

**Comment by jeanPerier** [comment]
> All builds and tests correctly. But this change is supposed to fix #88344. But after building flang-new with these changes, the example program in that issue still gets a seg fault in the same place.

Did you use the `-mmlir -fdynamic-heap-array` switch?

#88344 test is expected to segfault with limited stacks given flang is doing stack allocation by default in many cases (the test needs a huge temp). The bug was that `-mmlir -fdynamic-heap-array`  (which place stack temps on the heap) did not fix the situation. It does for me now (well, I did not wait for the reproducer to terminate, it is a torture test that does 100 billion multiplications and 10 million dynamic allocations.... but without the `-fdynamic-heap-array` option it crashes after a few seconds only).

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 4 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp:116]: There are two things that are being described here: how block loops are detected, and how they are dealt with.
 
1. If the alloca is inside a block based loop, and the deallocation points are after the loop, the deallocation points will not be dominated by the alloca. So we can use dominance to detect block based loops with some false positive (alloca in "if-like" block CFG will also create cases where deallocation points are not dominated by the alloca).

2. if the alloca is inside a block based loop, and the deallocation points are after the loop, an extra deallocation must be added on the back edge to avoid memory leaks. The easiest is to insert a conditional deallocation right before the alloca: If the alloca has ever been executed before, the C pointer variable will be set and is deallocated right before executing the alloca again. This does not require any analysis to find the back edge and can be done in the "false positive" cases with no correctness consequences (in fact, it could always be done).

Here is an illustration:
```
subroutine test(n)
  integer :: n
  real :: res
  interface
    function create_array(i)
      real :: create_array(i)
    end function
  end interface
  res = 0
  do i=1,100
    res = res + sum(create_array(i))
    if (i>n) goto 1
  end do
1 call do_something(res)
end subroutine
```

Because of the goto, the do loop is lowered to block CFG (blocks + `cf.cond_br`). The alloca is contained inside a block for the loop body. The alloca owner is the func.func, since there are no region based operation for the loop. So the deallocation point that was found so far is the func.return. The func.return is not dominated by the block containing the alloca due to the cyclic aspect. Hence, a conditional deallocation will be inserted before the new allocmem.

```
  func.func @_QPtest(%arg0: !fir.ref<i32> {fir.bindc_name = "n"}) {
    cf.br ^bb1

  ^bb1:  // 2 preds: ^bb0, ^bb4
    // ... loop entry
    cf.cond_br %8, ^bb2, ^bb5
  ^bb2:  // pred: ^bb1
    %17 = fir.alloca !fir.array<?xf32>, %15 {bindc_name = ".result"}
    // ... SUM
    // ... cf.cond_br for the IF () GOTO 1
    cf.cond_br %38, ^bb3, ^bb4
  ^bb3:  // pred: ^bb2
    cf.br ^bb5
  ^bb4:  // pred: ^bb2
    // ... index increment and cf.br back to the loop entry
    cf.br ^bb1
  ^bb5:  // 2 preds: ^bb1, ^bb3
    fir.call @_QPdo_something(%6) fastmath<contract> : (!fir.ref<f32>) -> ()
    return
  }
```

Will be turned into:


```
  func.func @_QPtest(%arg0: !fir.ref<i32> {fir.bindc_name = "n"}) {
    // Init pointer variable to nullptr
    %0 = fir.alloca !fir.heap<!fir.array<?xf32>>
    %1 = fir.zero_bits !fir.heap<!fir.array<?xf32>>
    fir.store %1 to %0 : !fir.ref<!fir.heap<!fir.array<?xf32>>>
    cf.br ^bb1
  ^bb1:  // 2 preds: ^bb0, ^bb4
    // loop entry
    cf.cond_br %8, ^bb2, ^bb5
  ^bb2:  // pred: ^bb1
    // Conditionally dealloc the memory if pointer variable is set.
    %19 = fir.load %0 : !fir.ref<!fir.heap<!fir.array<?xf32>>>
    %20 = fir.convert %19 : (!fir.heap<!fir.array<?xf32>>) -> i64
    %21 = arith.cmpi ne, %20, %c0_i64 : i64
    fir.if %21 {
      fir.freemem %19 : !fir.heap<!fir.array<?xf32>>
    }
   // Allocate memory and set pointer variable to it.
    %22 = fir.allocmem !fir.array<?xf32>, %17 {bindc_name = ".result", uniq_name = ""}
    %23 = fir.convert %22 : (!fir.heap<!fir.array<?xf32>>) -> !fir.ref<!fir.array<?xf32>>
    fir.store %22 to %0 : !fir.ref<!fir.heap<!fir.array<?xf32>>>
    //  ...
    cf.cond_br %38, ^bb3, ^bb4
  ^bb3:  // pred: ^bb2
    cf.br ^bb5
  ^bb4:  // pred: ^bb2
    cf.br ^bb1
  ^bb5:  // 2 preds: ^bb1, ^bb3
    fir.call @_QPdo_something(%6) fastmath<contract> : (!fir.ref<f32>) -> ()
    // Conditionally dealloc the memory if pointer variable is set
    // ...
    fir.if %51 {
      fir.freemem %49 : !fir.heap<!fir.array<?xf32>>
    }
    return
  }
```

I rephrased the comment to be a bit more clear.

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 5 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp]: I moved/shared the logic with FIROpBuilder::createConvert to avoid the proliferation of this helper.

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 6 above)
Comment (jeanPerier) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp]: I moved/shared that with  fir::FIROpbuilder::getIntPtrType.

**Comment by psteinfeld** [comment]
> Did you use the `-mmlir -fdynamic-heap-array` switch?
Oops.  I missed that.

But I've rebuilt with the latest sources and tested the original test, and all looks good.

**Review by psteinfeld — APPROVED** [review]
All builds and tests correctly and looks good.

**Review by razvanlupusoru — APPROVED** [review]
Excellent approach and sensible implementation. Looks great!

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp [hunk 8]
```diff
@@ -0,0 +1,217 @@
...
+  // an odd region we cannot reason about (never seen yet in FIR and
+  // mainstream dialects, but MLIR does not really prevent it).
+  if (deallocationPoints.empty())
+    return nullptr;
+
+  // Step 3: detect block based loops between the allocation and deallocation
+  // points, and add a deallocation point on the back edge to avoid memory
+  // leaks.
+  // To avoid complex CFG analysis, the detection uses the fact an alloca
+  // inside a loop does not dominate its deallocation points after the loop. So
```
Comment (vzakhari) [inline flang/lib/Optimizer/Transforms/MemoryUtils.cpp:106]: Is this always true for unstructured loops? For example:
```
subroutine test(x, n)
  interface
     function create_array(i)
       real :: create_array(i)
     end function create_array
  end interface
  real :: x(:)
  integer :: n, i
  i = 1
10 x(i) = sum(create_array(i))
  i = i + 1
  if (i.lt.n) goto 10
end subroutine test
```

The `alloca` still dominates the `return`. It seems that extending the `MemoryAllocationOpt` pass this way will cause memory leaks for this case.  It seems a conservative approach might be to check if the alloca's block is reachable from itself (via unstructured branching), and use the indirect deallocation when it is.

**Review by vzakhari — COMMENTED** [review]
Thank you, Jean!  It looks great, though, I think there might be regressions for some unstructured CFG cases.

**Review by clementval — APPROVED** [review]

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 4 above)
Comment (tblah) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp]: Thank you for explaining. LGTM

**Review by tblah — APPROVED** [review]
LGTM once Slava's comment is addressed. Thanks for the updates

File: flang/lib/Optimizer/Transforms/MemoryUtils.cpp (hunk 8 above)
Comment (vzakhari) [reply flang/lib/Optimizer/Transforms/MemoryUtils.cpp]: Thank you for addressing the issue, Jean! The custom cycle detector looks good to me.

**Review by vzakhari — APPROVED** [review]
