### PR TITLE
[clang-format]: Fix formatting of if statements with BlockIndent 

### LINKED ISSUE #54663: [clang-format] 'else if' clause not broken when using AlignAfterOpenBracket: BlockIndent
**clang-format version:**
`Debian clang-format version 14.0.0-++20220329040358+3f43d803382d-1~exp1~20220329160446.105`

**Code:**
```c++
void foo() {
        if (thisIsRatherALongIfClause && thatIExpectToBeBroken || ontoMultipleLines && whenFormattedCorrectly) {
        }

        if (false) {
        }
        else if (thisIsRatherALongIfClause && thatIExpectToBeBroken || ontoMultipleLines && whenFormattedCorrectly) {
        }
}
```

**Output** with defaults:
```
❯ clang-format --style='{ColumnLimit: 60}' tmp.cc
void foo() {
  if (thisIsRatherALongIfClause && thatIExpectToBeBroken ||
      ontoMultipleLines && whenFormattedCorrectly) {
  }

  if (false) {
  } else if (thisIsRatherALongIfClause &&
                 thatIExpectToBeBroken ||
             ontoMultipleLines && whenFormattedCorrectly) {
  }
}
```

**Output** with `AlignAfterOpenBracket: BlockIndent`
```
❯ clang-format --style='{ColumnLimit: 60, AlignAfterOpenBracket: BlockIndent}' tmp.cc
void foo() {
  if (thisIsRatherALongIfClause && thatIExpectToBeBroken ||
      ontoMultipleLines && whenFormattedCorrectly) {
  }

  if (false) {
  } else if (thisIsRatherALongIfClause && thatIExpectToBeBroken || ontoMultipleLines && whenFormattedCorrectly) {
  }
}
```

**Expected output:**  
First of all, I was intuitively expecting `BlockIndent` to break the if/else-if clause in a similar way to a function declaration:
```c++
void foo(
    int veryLongArgumentName1, int veryLongArgumentName2,
    int veryLongArgumentName3
) {}
```
and my hope was that there would be a `BinPack...` option to place each part of the clause on each line just as one can with arguments and parameters, but that doesn't seem to be the case.

If that's not possible and/or it's not a design goal for that option, then at the least I'd expect the `else if` clause to be broken, because currently it doesn't get wrapped at all when the `BlockIndent` alignment style is used, which seems buggy.

### PR DESCRIPTION
**Pull request by gedare**
A bug with BlockIndent prevents line breaks within if (and else if) clauses.

While fixing this bug, it appears that AlignAfterOpenBracket is not designed to work with loop and if statements, but AlwaysBreak works on if clauses. The documentation and tests are not clear on whether or not this behavior is intended.

This PR preserves the `AlwaysBreak` behavior on `if` clauses without supporting `BlockIndent` on `if` clauses  to avoid regressions while fixing the bug.

It may be reasonable to create an explicit option for alignment of if (and loop) clauses intentionally for both `AlwaysBreak` and `BlockIndent`

Fixes #54663.

Migrated from Differential Revision: https://reviews.llvm.org/D154755
See more discussion there. Addressed last open comment from the rev about refactoring the complex conditional logic involved with the `AlignAfterOpenBracket` line break behavior.

### CODE REVIEW

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 1]
```diff
@@ -768,15 +768,25 @@ void ContinuationIndenter::addTokenOnCurrentLine(LineState &State, bool DryRun,
   // parenthesis by disallowing any further line breaks if there is no line
   // break after the opening parenthesis. Don't break if it doesn't conserve
   // columns.
+  auto isOpeningBracket = [&](const FormatToken &Tok) {
+    auto isStartOfBracedList = [&](const FormatToken &Tok) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:772]:
```suggestion
  auto IsOpeningBracket = [&](const FormatToken &Tok) {
    auto IsStartOfBracedList = [&](const FormatToken &Tok) {
```

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 2]
```diff
@@ -768,15 +768,25 @@ void ContinuationIndenter::addTokenOnCurrentLine(LineState &State, bool DryRun,
...
+    if (Tok.isOneOf(tok::l_paren, TT_TemplateOpener, tok::l_square) ||
+        IsStartOfBracedList()) {
+      if (!Tok.Previous)
+        return true;
+      if (Tok.Previous->isIf())
+        return Style.AlignAfterOpenBracket == FormatStyle::BAS_AlwaysBreak;
+      return !Tok.Previous->isOneOf(TT_CastRParen, tok::kw_for, tok::kw_while,
+                                    tok::kw_switch);
+    }
+    return false;
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:785]:
```suggestion
    if (!Tok.isOneOf(tok::l_paren, TT_TemplateOpener, tok::l_square) &&
        !IsStartOfBracedList()) {
      return false;
    }
    if (!Tok.Previous)
      return true;
    if (Tok.Previous->isIf())
      return Style.AlignAfterOpenBracket == FormatStyle::BAS_AlwaysBreak;
    return !Tok.Previous->isOneOf(TT_CastRParen, tok::kw_for, tok::kw_while,
                                  tok::kw_switch);
```

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 3]
```diff
@@ -768,15 +768,25 @@ void ContinuationIndenter::addTokenOnCurrentLine(LineState &State, bool DryRun,
   // parenthesis by disallowing any further line breaks if there is no line
   // break after the opening parenthesis. Don't break if it doesn't conserve
   // columns.
+  const auto IsOpeningBracket = [&](const FormatToken &Tok) {
+    const auto IsStartOfBracedList = [&]() {
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:772]:
```suggestion
  auto IsOpeningBracket = [&](const FormatToken &Tok) {
    auto IsStartOfBracedList = [&]() {
```

**Review by owenca — APPROVED** [review]
