### PR TITLE
[Sema] Fix c23 not checking CheckBoolLikeConversion

### LINKED ISSUE #79435: Clang is not triggering `-Wtautological-constant-compare` when using `-std=c23`
When compiling the minimal sample with any std flag (that i have tried) other than `-std=c23`, we get the warning:
 
`warning: converting the result of '<<' to a boolean always evaluates to true [-Wtautological-constant-compare]`

This warning is not triggered for c23.

This regression was introduced somewhere between 14.0.0 and 15.0.0.

I have never worked with LLVM before, but i have decided to take a stab at solving the issue.

# Minimal example
[Godbolt](https://godbolt.org/z/hvdrbP19s)
```c
int test() {
  if (1 << 5) {
    return 0;
  }
  return 1;
}
```

### PR DESCRIPTION
**Pull request by pileghoff**
Fixes issue #79435 

Checks for implicit conversion into boolean was previously triggered by `CheckBoolLikeConversion` for C.
When `bool` as a keyword was introduced in C23, `CheckBoolLikeConversion` would no longer trigger when using `-std=c23`, but since logical operators and conditional statements still operate on scalar values, the checks for implicit conversion into bool were never triggered.

This fix changes `CheckBoolLikeConversion` to not return early for C23, even though it has support for bools.

### CODE REVIEW

**Review by shafik — COMMENTED** [review]
Thank you for the Fix! Your summary should be a description of the problem and how your solution fixes that problem. You should also link to the github issue in the summary.

Questions about the changes in the PR should go as a comment to the PR.

Please add a release note and this will need tests as well.

**Comment by pileghoff** [comment]
> Thank you for the Fix! Your summary should be a description of the problem and how your solution fixes that problem. You should also link to the github issue in the summary.
> 
> Questions about the changes in the PR should go as a comment to the PR.
> 
> Please add a release note and this will need tests as well.

Noted. I have updated the description.

With regards to testing, I think I get how to write them, but I'm still unsure about where I'm suppose to put them. Would a new file (`implicit-boolike-conversion.c`?) be appropriate? 

Is the PR requirements/process documented anywhere? I had a look at [here](https://llvm.org/docs/Contributing.html) and i was looking around if there was a template, but i have found nothing.

**Comment by pileghoff** [comment]
I can also see i broke the `n3042.c` test. Stuff like `if (null_val) {}` now throws a warning, since `null_val` is a constant.

I would expect this warning to be okay in that scenario?

**Comment by pileghoff** [comment]
For testing i have fixed the new warnings in `n3042.c` and i have expanded `warn-int-in-bool-context.c` to check c23 specefically (which was broken, but is now fixed) and i added a few extra cases to the test. I will take a look at the release notes later today.

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -16134,7 +16134,7 @@ static void CheckConditionalOperator(Sema &S, AbstractConditionalOperator *E,
 /// Check conversion of given expression to boolean.
 /// Input argument E is a logical expression.
 static void CheckBoolLikeConversion(Sema &S, Expr *E, SourceLocation CC) {
-  if (S.getLangOpts().Bool)
+  if (S.getLangOpts().Bool && !S.getLangOpts().C23)
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaChecking.cpp:16137]: I think it would be good to add some comments here as to why we're checking for !C23 explicitly, WDYT?

**Review by AaronBallman — COMMENTED** [review]
The changes look good to me in general, though I'm waiting for precommit CI to finish before approving just to make sure we caught any other fallout from the changes in the test system.

**Comment by pileghoff** [comment]
If i can get the build to pass (it seems to fail on unrelated tests?), everything should be ready for review.

File: clang/lib/Sema/SemaChecking.cpp (hunk 1 above)
Comment (pileghoff) [reply clang/lib/Sema/SemaChecking.cpp:16137]: Sounds very reasonable

**Review by AaronBallman — CHANGES_REQUESTED** [review]
It looks like a bunch of formatting changes came in with SemaChecking.cpp. You should only be formatting the code that your patch needs to touch. We've got a script for that: https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting or https://clang.llvm.org/docs/ClangFormat.html#git-integration

Can you back out the unrelated formatting changes?

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you for the fix!

**Comment by AaronBallman** [comment]
This passed precommit CI before and the only difference is that there are formatting changes removed, so I'm landing this before precommit CI finishes.
