### PR TITLE
[Clang][Sema] Skip RecordDecl when checking scope of declarations

### LINKED ISSUE #41302: clang crash while parsing a struct in C
|  |  |
| --- | --- |
| Bugzilla Link | [41957](https://llvm.org/bz41957) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reduced testcase for the crash](https://user-images.githubusercontent.com/1748238/143759234-37468778-3fcb-436d-b275-697e9fc2afc1.gz) |
| CC | @DougGregor,@ecnelises,@zygoloid |

## Extended Description 

The expected result would be clang complaining about "__packed" (which would lead to a missing include). This issue was introduced after LLVM 3.7 and is still present in latest clang trunk.

I attached a manually reduced testcase.
https://godbolt.org/z/jdmr5k

Stack dump:

```
0.	Program arguments: /opt/compiler-explorer/clang-trunk-20190521/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name example.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /home/ubuntu/./output.gcno -resource-dir /opt/compiler-explorer/clang-trunk-20190521/lib/clang/9.0.0 -internal-isystem /usr/local/include -internal-isystem /opt/compiler-explorer/clang-trunk-20190521/lib/clang/9.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/ubuntu -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -mllvm --x86-asm-syntax=intel -o ./output.s -x c <source> -faddrsig 

1.	<source>:14:8: current parser token ';'

2.	<source>:2:1: parsing function body 'test'

3.	<source>:2:1: in compound statement ('{}')

4.	<source>:12:2: parsing struct/union body

 #&#8203;0 0x00005616d7606cba llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x269bcba)

 #&#8203;1 0x00005616d7604a84 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x2699a84)

 #&#8203;2 0x00005616d7604bc2 SignalHandler(int) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x2699bc2)

 #&#8203;3 0x00007f146901f890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)

 #&#8203;4 0x00005616d9398be1 clang::DeclContext::addHiddenDecl(clang::Decl*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x442dbe1)

 #&#8203;5 0x00005616d939ce79 clang::DeclContext::addDecl(clang::Decl*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x4431e79)

 #&#8203;6 0x00005616d8c9e06c clang::Sema::PushOnScopeChains(clang::NamedDecl*, clang::Scope*, bool) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3d3306c)

 #&#8203;7 0x00005616d8cb3cb0 clang::Sema::HandleField(clang::Scope*, clang::RecordDecl*, clang::SourceLocation, clang::Declarator&, clang::Expr*, clang::InClassInitStyle, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3d48cb0)

 #&#8203;8 0x00005616d8cb3fdd clang::Sema::ActOnField(clang::Scope*, clang::Decl*, clang::SourceLocation, clang::Declarator&, clang::Expr*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3d48fdd)

 #&#8203;9 0x00005616d8aed736 void llvm::function_ref<void (clang::ParsingFieldDeclarator&)>::callback_fn<clang::Parser::ParseStructUnionBody(clang::SourceLocation, unsigned int, clang::Decl*)::'lambda'(clang::ParsingFieldDeclarator&)>(long, clang::ParsingFieldDeclarator&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b82736)

#&#8203;10 0x00005616d8b05b65 clang::Parser::ParseStructDeclaration(clang::ParsingDeclSpec&, llvm::function_ref<void (clang::ParsingFieldDeclarator&)>) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b9ab65)

#&#8203;11 0x00005616d8b09c15 clang::Parser::ParseStructUnionBody(clang::SourceLocation, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b9ec15)

#&#8203;12 0x00005616d8b1c32c clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3bb132c)

#&#8203;13 0x00005616d8afe18e clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b9318e)

#&#8203;14 0x00005616d8b06494 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b9b494)

#&#8203;15 0x00005616d8b067fa clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b9b7fa)

#&#8203;16 0x00005616d8b6c4c2 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3c014c2)

#&#8203;17 0x00005616d8b6daf9 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3c02af9)

#&#8203;18 0x00005616d8b71121 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3c06121)

#&#8203;19 0x00005616d8b741e3 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3c091e3)

#&#8203;20 0x00005616d8ae1b68 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b76b68)

#&#8203;21 0x00005616d8b02381 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b97381)

#&#8203;22 0x00005616d8adcad9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b71ad9)

#&#8203;23 0x00005616d8add7b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.207) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b727b1)

#&#8203;24 0x00005616d8ae4a06 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b79a06)

#&#8203;25 0x00005616d8ae5469 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b7a469)

#&#8203;26 0x00005616d8ae5995 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b7a995)

#&#8203;27 0x00005616d8ad9246 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x3b6e246)

#&#8203;28 0x00005616d832c017 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x33c1017)

#&#8203;29 0x00005616d7cc8826 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x2d5d826)

#&#8203;30 0x00005616d7c8b41c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x2d2041c)

#&#8203;31 0x00005616d7d86eb3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0x2e1beb3)

#&#8203;32 0x00005616d5bf9d90 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0xc8ed90)

#&#8203;33 0x00005616d5b5c3b2 main (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0xbf13b2)

#&#8203;34 0x00007f1467eddb97 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b97)

#&#8203;35 0x00005616d5bf738a _start (/opt/compiler-explorer/clang-trunk-20190521/bin/clang-9+0xc8c38a)

clang-9: error: unable to execute command: Segmentation fault (core dumped)

clang-9: error: clang frontend command failed due to signal (use -v to see invocation)

Compiler returned: 254
```

### LINKED ISSUE #44080: Crash on release. Assertion `Val & & "isa<> used on a null pointer"' failed.
|  |  |
| --- | --- |
| Bugzilla Link | [44735](https://llvm.org/bz44735) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
Preprocess file:

```
# 1 "<built-in>"
# 1 "test1.c"
a() {
  struct b {
    struct b;
  } struct b {
```

Run script:(clang -x c -o poc poc.c)

```
# Crash reproducer for clang version 11.0.0 (https://github.com/llvm/llvm-project.git 56b7f595d2b402ff177ca42214325c8fdea10fb0)
# Driver args: "-x" "c" "test1.c" "-o" "test"
# Original command:  "/home/rxz226/llvm-project/bld_instru/bin/clang-11" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-main-file-name" "test1.c" "-mrelocation-model" "static" "-mthread-model" "posix" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/home/rxz226/llvm-project/bld_instru/lib/clang/11.0.0" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/home/rxz226/llvm-project/bld_instru/lib/clang/11.0.0/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-fdebug-compilation-dir" "/home/rxz226/fuzz_clang1/hangs/test" "-ferror-limit" "19" "-fmessage-length" "0" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-faddrsig" "-o" "/tmp/test1-83ca24.o" "-x" "c" "test1.c"
 "/home/rxz226/llvm-project/bld_instru/bin/clang-11" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-main-file-name" "test1.c" "-mrelocation-model" "static" "-mthread-model" "posix" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-ferror-limit" "19" "-fmessage-length" "0" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-faddrsig" "-x" "c" "test1-3c73df.c"
```

Stack dump:

```
 #0 0x000000000681faf6 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/rxz226/llvm-project/llvm/lib/Support/Unix/Signals.inc:560:7
 #1 0x000000000681ac5e llvm::sys::RunSignalHandlers() /home/rxz226/llvm-project/llvm/lib/Support/Signals.cpp:69:18
 #2 0x000000000681dd30 llvm::sys::CleanupOnSignal(unsigned long) /home/rxz226/llvm-project/llvm/lib/Support/Unix/Signals.inc:361:3
 #3 0x000000000662a5aa (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /home/rxz226/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:80:5
 #4 0x000000000662a9e6 /home/rxz226/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:361:51
 #5 0x00007f0447486390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #6 0x00007f0445ff0428 raise /build/glibc-LK5gWL/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
 #7 0x00007f0445ff202a abort /build/glibc-LK5gWL/glibc-2.23/stdlib/abort.c:91:0
 #8 0x00007f0445fe8bd7 __assert_fail_base /build/glibc-LK5gWL/glibc-2.23/assert/assert.c:92:0
 #9 0x00007f0445fe8c82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
#10 0x0000000008254861 (/home/rxz226/llvm-project/bld_instru/bin/clang+0x8254861)
#11 0x000000000c1a0139 llvm::isa_impl_wrap<clang::TagDecl, clang::Decl* const, clang::Decl const*>::doit(clang::Decl* const&) /home/rxz226/llvm-project/llvm/include/llvm/Support/Casting.h:122:12
#12 0x000000000c1a0139 bool llvm::isa<clang::TagDecl, clang::Decl*>(clang::Decl* const&) /home/rxz226/llvm-project/llvm/include/llvm/Support/Casting.h:142:0
#13 0x000000000c1a0139 llvm::cast_retty<clang::TagDecl, clang::Decl*>::ret_type llvm::cast<clang::TagDecl, clang::Decl>(clang::Decl*) /home/rxz226/llvm-project/llvm/include/llvm/Support/Casting.h:264:0
#14 0x000000000c1a0139 clang::Sema::ActOnTagStartDefinition(clang::Scope*, clang::Decl*) /home/rxz226/llvm-project/clang/lib/Sema/SemaDecl.cpp:15784:0
#15 0x000000000bc2122a llvm::SmallVector<clang::Decl*, 32u>::SmallVector() /home/rxz226/llvm-project/llvm/include/llvm/ADT/SmallVector.h:0:0
#16 0x000000000bc2122a clang::Parser::ParseStructUnionBody(clang::SourceLocation, clang::TypeSpecifierType, clang::Decl*) /home/rxz226/llvm-project/clang/lib/Parse/ParseDecl.cpp:4222:0
#17 0x000000000bc60e0d clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, c$
ang::Parser::ParsedAttributesWithRange&) /home/rxz226/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:1966:20
#18 0x000000000bc04059 clang::ParsedAttributesView::empty() const /home/rxz226/llvm-project/clang/include/clang/Sema/ParsedAttr.h:0:0
#19 0x000000000bc04059 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) /home/rxz2$
6/llvm-project/clang/lib/Parse/ParseDecl.cpp:3939:0
#20 0x000000000bc03127 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) /home/rxz226/$
lvm-project/clang/lib/Parse/ParseDecl.cpp:1823:10
#21 0x000000000bc02cbd clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) /home/rxz226/llvm-project/clang/lib/Parse/ParseDecl.cpp$
0:12
#22 0x000000000bd8bba6 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) /home/$
xz226/llvm-project/clang/lib/Parse/ParseStmt.cpp:0:13
#23 0x000000000bd8aff1 clang::ParsedAttributesView::empty() const /home/rxz226/llvm-project/clang/include/clang/Sema/ParsedAttr.h:0:0
#24 0x000000000bd8aff1 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /home/rxz226/llvm-project/clang/lib/Parse/ParseStmt.cpp:109:0
#25 0x000000000bd9f27e clang::Parser::ParseCompoundStatementBody(bool) /home/rxz226/llvm-project/clang/lib/Parse/ParseStmt.cpp:1079:11
#26 0x000000000bda2138 clang::ActionResult<clang::Stmt*, true>::isInvalid() const /home/rxz226/llvm-project/clang/include/clang/Sema/Ownership.h:0:0
#27 0x000000000bda2138 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) /home/rxz226/llvm-project/clang/lib/Parse/ParseStmt.cpp:2207:0
#28 0x000000000bbc17c5 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:1349:10
#29 0x000000000bc11c0c clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) /home/rxz226/llvm-project/clang/lib/Parse/ParseDecl.cpp:2069:16
#30 0x000000000bbbe8b9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:0:10
#31 0x000000000bbbcfe9 clang::Parser::ObjCDeclContextSwitch::~ObjCDeclContextSwitch() /home/rxz226/llvm-project/clang/include/clang/Parse/Parser.h:0:0
#32 0x000000000bbbcfe9 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:1126:0
#33 0x000000000bbbae53 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:945:12
#33 0x000000000bbbae53 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:945:12
#34 0x000000000bbb658c clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:696:10
#35 0x000000000bbb537c clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) /home/rxz226/llvm-project/clang/lib/Parse/Parser.cpp:564:26
#36 0x000000000bbaba50 clang::ParseAST(clang::Sema&, bool, bool) /home/rxz226/llvm-project/clang/lib/Parse/ParseAST.cpp:157:15
#37 0x0000000007dff26a clang::ASTFrontendAction::ExecuteAction() /home/rxz226/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1045:1
#38 0x000000000911b260 clang::CodeGenAction::ExecuteAction() /home/rxz226/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1176:28
#39 0x0000000007dfd6b9 clang::FrontendAction::Execute() /home/rxz226/llvm-project/clang/lib/Frontend/FrontendAction.cpp:940:10
#40 0x0000000007d39f27 llvm::Error::operator bool() /home/rxz226/llvm-project/llvm/include/llvm/Support/Error.h:0:0
#41 0x0000000007d39f27 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/rxz226/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:965:0
#42 0x00000000080c5534 clang::CompilerInstance::getFrontendOpts() /home/rxz226/llvm-project/clang/include/clang/Frontend/CompilerInstance.h:0:0
#43 0x00000000080c5534 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/rxz226/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:291:0
#44 0x0000000000a7ac38 llvm::TimeTraceScope::~TimeTraceScope() /home/rxz226/llvm-project/llvm/include/llvm/Support/TimeProfiler.h:0:0
#45 0x0000000000a7ac38 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/rxz226/llvm-project/clang/tools/driver/cc1_main.cpp:240:0
#46 0x0000000000a6c1fb ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /home/rxz226/llvm-project/clang/tools/driver/driver.cpp:328:12
#47 0x0000000007acd530 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1::operator()() const
/home/rxz226/llvm-project/clang/lib/Driver/Job.cpp:402:30
...
```

### PR DESCRIPTION
**Pull request by ecnelises**
In non C++ mode, struct definitions does not create a scope for declaration.

Fixes #41302

Fixes #44080

### CODE REVIEW

**Comment by cor3ntin** [comment]
The change looks good to me, but it is missing a release note in clang/docs/ReleaseNotes.rst

File: clang/test/Sema/nested-redef.c [hunk 1]
```diff
@@ -19,4 +19,8 @@ void f2(void) {
   struct U u;
 }
 
-
+void f3(void) {
```
Comment (shafik) [inline clang/test/Sema/nested-redef.c:22]: So unlike the original test case this one does not seem to cause a crash. Can we add a test case for that as well to verify we are fixing that issue as well.

**Review by AaronBallman — APPROVED** [review]
LGTM!
