### PR TITLE
[X86][AMX] Fix missing stride register for tileloadd

### LINKED ISSUE #110190: [X86_64] [AMX] Wrong tile register reload instruction is generated
[amx-reload-bug.txt](https://github.com/user-attachments/files/17157112/amx-reload-bug.txt)

I build LLC from the main branch and compile the attached test case with `-mcpu=sapphirerapids`. The resulting assembly code has the following instructions:
```
        tilestored      %tmm0, 6016(%rsp,%rax)  # 1024-byte Folded Spill
        tileloadd       6016(%rsp), %tmm7       # 1024-byte Folded Reload
```
Here tile reload misses index register with a stride, therefore zero stride is used and the first row of the stored tile is broadcasted. Also, it looks like this spill/reload pair can be avoided.

### PR DESCRIPTION
**Pull request by phoebewang**
Fixes: #110190

### CODE REVIEW

File: llvm/lib/Target/X86/X86LowerTileCopy.cpp [hunk 1]
```diff
@@ -140,14 +140,16 @@ bool X86LowerTileCopy::runOnMachineFunction(MachineFunction &MF) {
...
-      MO.setReg(GR64Cand ? GR64Cand : X86::RAX);
-      MO.setIsKill(true);
+      MachineOperand *MO = &NewMI->getOperand(2);
+      MO->setReg(GR64Cand ? GR64Cand : X86::RAX);
       // tileloadd (%sp, %idx), %tmm
       Opc = GET_EGPR_IF_ENABLED(X86::TILELOADD);
 #undef GET_EGPR_IF_ENABLED
       NewMI = addFrameReference(BuildMI(MBB, MI, DL, TII->get(Opc), DstReg),
                                 TileSS);
+      MO = &NewMI->getOperand(3);
```
Comment (fzou1) [inline llvm/lib/Target/X86/X86LowerTileCopy.cpp:150]: Is it better to use "1 + X86::AddrIndexReg" instead of "3" as in line [X86InstrInfo.cpp#L4768](https://github.com/llvm/llvm-project/blob/a131fbf1687a641265ced45b19dc97ee1c9e3484/llvm/lib/Target/X86/X86InstrInfo.cpp#L4768)?

Comment (phoebewang) [reply llvm/lib/Target/X86/X86LowerTileCopy.cpp]: Good point, done.

**Comment by phoebewang** [comment]
Ping?

**Review by RKSimon — COMMENTED** [review]
SGTM but I know almost nothing about AMX

**Review by fzou1 — APPROVED** [review]
LGTM
