### PR TITLE
[clang-format] Fix a regression in dumping the config

### LINKED ISSUE #80621: `clang-format -dump-config` "hangs"
Bisected to d813af73f70f.

### PR DESCRIPTION
**Pull request by owenca**
Commit d813af73f70f addressed a regression introduced by commit 3791b3fca6ea
but caused `clang-format -dump-config` to "hang".

This patch reverts changes to ClangFormat.cpp by both commits and reworks the cleanup.

Fixes #80621.

### CODE REVIEW

File: clang/test/Format/dump-config.cpp [hunk 1]
```diff
@@ -0,0 +1,3 @@
+// RUN: clang-format -dump-config 2>&1 | FileCheck %s
```
Comment (bhamiltoncx) [inline clang/test/Format/dump-config.cpp:1]: Can you also add a test with `clang-format --assume-filename=foo.m -dump-config 2>&1 | FileCheck %s`?

It should result in `Language: ObjC`.

**Review by bhamiltoncx — APPROVED** [review]
Looks good. Can you add one more test, please?

File: clang/test/Format/dump-config.cpp (hunk 1 above)
Comment (owenca) [reply clang/test/Format/dump-config.cpp]: Added to dump-config-objc-stdin.m instead.

File: clang/test/Format/dump-config-objc-stdin.m [hunk 2]
```diff
@@ -1,5 +1,8 @@
+// RUN: clang-format -assume-filename=foo.m -dump-config | FileCheck %s
```
Comment (bhamiltoncx) [inline clang/test/Format/dump-config-objc-stdin.m:1]: It looks like you reverted the lit test which just runs `clang-format -dump-config` without any other arguments. Is that what you wanted to do?

Comment (owenca) [reply clang/test/Format/dump-config-objc-stdin.m:1]: Yes, because it wouldn't make a difference before and after the patch. I don't think we can use lit to test that behavior (i.e., not waiting for an EOF) of clang-format in the terminal.

**Comment by tstellar** [comment]
Tracking the backport request here: #81096
