### PR TITLE
[clang-format] Fix a bug in parsing C-style cast of lambdas

### LINKED ISSUE #135959: [clang-format] Incorrect formatting when applying C-style cast to lambda expression
OS: Windows 11

Version: `clang-format version 20.1.2`

Example code:

```cpp
int main() {
    auto foo { (std::function<int()>)[] { return 0; }};
    return 0;
}
```

After formatting:

```cpp
int main() { auto foo{(std::function<int()>)[]{return 0; }
}
;
return 0;
}
```

`auto foo = (std::function<int()>)[] { return 0; };` and `auto foo { std::function<int()>([] { return 0; }) };` works as expected.

### PR DESCRIPTION
**Pull request by owenca**
Fix #135959

### CODE REVIEW

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 1]
```diff
@@ -2371,7 +2371,8 @@ bool UnwrappedLineParser::tryToParseLambdaIntroducer() {
   if ((Previous && ((Previous->Tok.getIdentifierInfo() &&
                      !Previous->isOneOf(tok::kw_return, tok::kw_co_await,
                                         tok::kw_co_yield, tok::kw_co_return)) ||
-                    Previous->closesScope())) ||
+                    (Previous->closesScope() &&
+                     !Previous->endsSequence(tok::r_paren, tok::greater)))) ||
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/UnwrappedLineParser.cpp:2375]: And if it is casted to `int(*)`?

I know we didn't annotate stuff here, it is hard to detect if this is a cast, but is there maybe a different way which would be a bit more resilient?

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp]: I've added the handling of casting to a function pointer, the only other case I can think of.

**Review by mydeveloperday — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]
