### PR TITLE
clang: Make the type_info builtin declaration a singleton

### LINKED ISSUE #38400: [Modules TS] MSVC std library produces ambiguous type_info reference when including module with ms-compatibility
|  |  |
| --- | --- |
| Bugzilla Link | [39052](https://llvm.org/bz39052) |
| Version | 7.0 |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@DougGregor,@zygoloid |

## Extended Description 
When compiling an project on windows using the MSVC standard library I get an ambiguous reference to type_info:

I have attached an archive of the most simple repro of the issue. It also includes the ii file from save-temps.

Error Message:
In file included from main.cpp:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\iostream:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\istream:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\ostream:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\ios:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xlocnum:10:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\streambuf:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xiosbase:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xlocale:8:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\stdexcept:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\exception:27:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\vcruntime_exception.h:10:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\eh.h:52:14: error:
      reference to 'type_info' is ambiguous
             type_info const& _Type,
             ^
note: candidate found by name lookup is 'type_info'
note: candidate found by name lookup is 'type_info'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\eh.h:52:14: error:
      reference to 'type_info' is ambiguous
note: candidate found by name lookup is 'type_info'
note: candidate found by name lookup is 'type_info'

### PR DESCRIPTION
**Pull request by matts1**
This fixes an ambiguous type type_info when you try and reference the `type_info` type while using clang modulemaps with `-fms-compatibility` enabled

Fixes #38400

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
This seems completely reasonable to me, though Aaron should take a look.  We typically don't maintain serialization/module compatibility between released versions, so I don't think this is an issue.

**Review by AaronBallman — APPROVED** [review]
LGTM!

File: clang/include/clang/AST/ASTContext.h [hunk 1]
```diff
@@ -2381,6 +2384,15 @@ class ASTContext : public RefCountedBase<ASTContext> {
     return getTagDeclType(MSGuidTagDecl);
   }
 
+  /// Retrieve the implicitly-predeclared 'struct type_info' declaration.
+  TagDecl *getMSTypeInfoTagDecl() const {
+    // Lazily create this type on demand - it's only needed for MS builds.
```
Comment (shafik) [inline clang/include/clang/AST/ASTContext.h:2389]: I think using a static local achieves this better but since your following the existing pattern then maybe something like that is better as a follow-up PR.

Comment (erichkeane) [reply clang/include/clang/AST/ASTContext.h:2389]: AFAIK: we can't do a static-local.  That ends up causing problems with multiple-loads of the AST/loading from serialization/etc.

**Comment by matts1** [comment]
What's required to get this merged? It's blocking some of my work so I'd prefer it merged sooner rather than later.

**Comment by bolshakov-a** [comment]
Thanks!
