### PR TITLE
[clang-tidy] Enable C99 in `implicit-bool-conversion` and avoid FP with `bool` operands in C23

### LINKED ISSUE #170596: [clangd] readability-implicit-bool-conversion false positive with bool and logical operators in C23
The `readability-implicit-bool-conversion` check incorrectly warns about implicit `bool` -> `int` conversion when using `bool` values with the `&&` operator, even though both operands are scalar types and this is perfectly valid C.

The warning message is misleading - it suggests a type safety issue when this is actually just normal operation of the && operator. If the intent is to enforce a style preference for explicit comparisons, the warning should clearly state that rather than implying a conversion problem.

This only occurs when clangd is set to "-std=c23".

## Expected Behavior
No warning should be issued. The C standard explicitly states that && accepts any scalar type, and bool is a scalar type. There is no implicit conversion issue here.

## Actual Behavior
"Warning: Implicit conversion 'bool' -> 'int'" on the returns_bool() call when used with &&.

## Environment
clangd version: 21.1.4
C standard: C23
Platform: windows

## Example Code
```c
bool returns_bool(void) { return true; }

void test(size_t len) {
    // NO WARNING - bool used directly in condition
    while (returns_bool()) {}
    
    // WARNING: "Implicit conversion 'bool' -> 'int'"
    while ((len > 0) && returns_bool()) {}
}
```

### PR DESCRIPTION
**Pull request by zeyi2**
Closes [#170596](https://github.com/llvm/llvm-project/issues/170596)

### CODE REVIEW

File: clang-tools-extra/clang-tidy/readability/ImplicitBoolConversionCheck.cpp [hunk 1]
```diff
@@ -27,7 +27,9 @@ AST_MATCHER(Stmt, isMacroExpansion) {
   return SM.isMacroBodyExpansion(Loc) || SM.isMacroArgExpansion(Loc);
 }
 
-AST_MATCHER(Stmt, isC23) { return Finder->getASTContext().getLangOpts().C23; }
+AST_MATCHER(Stmt, isC) {
+  return !Finder->getASTContext().getLangOpts().CPlusPlus;
```
[the remark this answers is not in the document]
Comment (zeyi2) [reply clang-tools-extra/clang-tidy/readability/ImplicitBoolConversionCheck.cpp]: > What about `return .getLangOpts().C99`? We don't need to handle C89 in this check.

Thanks! Using LangOpts.C99 would indeed exclude C89, but ASAIK in Clang the C-standard flags are cumulative: C11/C17/C23 (and Obj-C, which defaults to `gnu11`) all set C99 as well. So I think `getLO.C99` alone would also match Obj‑C.

And the documentation didn't mention the scope of this check. If we want this check to apply only to "pure" C, there are other LangOpts that need to be excluded as well: `return !LO.CPlusPlus && !LO.ObjC && !LO.OpenCL && !LO.CUDA && !LO.HIP && !LO.HLSL;`.

File: clang-tools-extra/test/clang-tidy/checkers/readability/implicit-bool-conversion.c [hunk 2]
```diff
@@ -371,3 +361,42 @@ int keepCompactReturnInC_PR71848() {
 // CHECK-MESSAGES: :[[@LINE-1]]:9: warning: implicit conversion 'bool' -> 'int' [readability-implicit-bool-conversion]
 // CHECK-FIXES: return(int)( foo );
 }
+
+bool returns_bool(void) { return true; }
```
Comment (localspook) [inline clang-tools-extra/test/clang-tidy/checkers/readability/implicit-bool-conversion.c]: Ditto
```suggestion
bool returns_bool(void);
```

**Review by vbvictor — COMMENTED** [review]
Code looks good, but TBH I didn't carefully read the discussion for rationale around bool conversions, so I hope someone more immersed in the details would make the final approval.

**Comment by Chase-san** [comment]
I would argue that warning on the bools in `(bool_a || bool_b)` will make the check largely ignored/disabled. AFAIK `&&` and `||` accept any scalar value, so any conversion here is likely a bug itself.

**Comment by Chase-san** [comment]
I do have a few concerns. If this particular warning is reported when we have a `bool || int` or similar situation the general consensus will be to simply disable the warning because that is an extremely common pattern.

Allowances for such things are generally made because they are considered to be safe. This was the case in C17. though it was likely just a macro in c17 rather than a proper type I doubt that the semantics have changed.

To clarify converting from a bool to an int should always safe in the context of a logical operator, warning about it is going to create a lot of noise for very little benefit.

**Review by zwuis — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/readability/implicit-bool-conversion-c99.c [hunk 3]
```diff
@@ -0,0 +1,43 @@
+// RUN: %check_clang_tidy -std=c99 %s readability-implicit-bool-conversion %t
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/readability/implicit-bool-conversion-c99.c]:
```suggestion
// RUN: %check_clang_tidy -std=c99-or-later %s readability-implicit-bool-conversion %t
```

Comment (zeyi2) [reply clang-tools-extra/test/clang-tidy/checkers/readability/implicit-bool-conversion-c99.c]: > Is there a reason to keep only c99?

I think this was a mistake from me, thanks for pointing that out :)

**Review by vbvictor — APPROVED** [review]
