### PR TITLE
[analyzer] Fix crash on using `bitcast(<type>, <array>)` as array subscript

### LINKED ISSUE #94496: [clang][static analyzer] Crash when program contains __builtin_bit_cast
The static analyzer crashes when passed a small program containing __builtin_bit_cast.
```
$ cat test.cpp
int *a;
char b[4];
void c() { a[__builtin_bit_cast(int, b)]; }
$ clang++ --version |& grep version
clang version 19.0.0git (git@github.com:llvm/llvm-project.git dd82fd4744397e0510c8204f1a6031441e21858e)
$ clang++ --analyze test.cpp
clang++: <HOME>/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = clang::ento::NonLoc, From = clang::ento::SVal]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
...
$
```

### PR DESCRIPTION
**Pull request by pskrgag**
Current CSA logic does not expect `LazyCompoundValKind`  as array index. This may happen if array is used as subscript to another, in case of bitcast to integer type.

Catch such cases and return `UnknownVal`, since CSA cannot model array ->
int casts.

Closes #94496

### CODE REVIEW

File: clang/test/Analysis/exercise-ps.c [hunk 1]
```diff
@@ -30,3 +30,10 @@ void f3(void *dest) {
   void *src = __builtin_alloca(5);
   memcpy(dest, src, 1); // expected-warning{{2nd function call argument is a pointer to uninitialized value}}
 }
+
+// Reproduce crash from GH#94496. When array is used as subcript to another array, CSA cannot model it
+// and should just assume it's unknown and do not crash.
+void f4(char *array) {
+  char b[4] = {0};
+  array[__builtin_bit_cast(int, b)] = 0x10; // no crash
```
Comment (steakhal) [inline clang/test/Analysis/exercise-ps.c:38]: Please enable the `debug.ExprInspection` checker too, and then forward declare (but not define) the `void clang_analyzer_dump_int(int);

```suggestion
  clang_analyzer_dump_int(__builtin_bit_cast(int, b)); // expected-warning {{Unknown}}
  array[__builtin_bit_cast(int, b)] = 0x10; // no crash
```

Hold on. Shouldn't we pin the target triple to be able to safely assume that a sizeof `int` is 4 chars? Consider pinning the target using `-triple xxx` in the RUN line.

File: clang/lib/StaticAnalyzer/Core/Store.cpp [hunk 2]
```diff
@@ -472,7 +472,19 @@ SVal StoreManager::getLValueElement(QualType elementType, NonLoc Offset,
...
   // Convert the offset to the appropriate size and signedness.
-  Offset = svalBuilder.convertToArrayIndex(Offset).castAs<NonLoc>();
+  auto Off = svalBuilder.convertToArrayIndex(Offset).getAs<NonLoc>();
+  if (!Off) {
+    // Handle cases when LazyCompoundVal is used for an array index.
+    // Such case is possible if code does:
+    //
+    //   char b[4];
+    //   a[__builtin_bitcast(int, b)];
+    //
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/Store.cpp:482]:
```suggestion
    //   char b[4];
    //   a[__builtin_bitcast(int, b)];
```

**Review by steakhal — CHANGES_REQUESTED** [review]

File: clang/lib/StaticAnalyzer/Core/Store.cpp [hunk 3]
```diff
@@ -472,7 +472,19 @@ SVal StoreManager::getLValueElement(QualType elementType, NonLoc Offset,
   const auto *ElemR = dyn_cast<ElementRegion>(BaseRegion);
 
   // Convert the offset to the appropriate size and signedness.
-  Offset = svalBuilder.convertToArrayIndex(Offset).castAs<NonLoc>();
+  auto Off = svalBuilder.convertToArrayIndex(Offset).getAs<NonLoc>();
```
[the remark this answers is not in the document]
Comment (pskrgag) [reply clang/lib/StaticAnalyzer/Core/Store.cpp:475]: This does not work, since it is not possible to cast `UnknownVal` to `NoLoc`

File: clang/test/Analysis/exercise-ps.c (hunk 1 above)
Comment (pskrgag) [reply clang/test/Analysis/exercise-ps.c:42]: Indeed, I forgot about the that! Also added static_assert to make error a bit more understandable just in case smth gets broken.

Thank you, fixed!

Comment (pskrgag) [reply clang/test/Analysis/exercise-ps.c:42]: Also `clang_analyzer_dump_int(__builtin_bit_cast(int, b));` ends up with `lazyCompoundVal{0x18602338,b}` . I guess, you meant `clang_analyzer_dump_int(array[__builtin_bit_cast(int, b)]);` ?

Comment (steakhal) [reply clang/test/Analysis/exercise-ps.c:42]: Then dump both:
```
clang_analyzer_dump_int(__builtin_bit_cast(int, b)); // expected-warning {{lazyCompoundVal}}
clang_analyzer_dump_ptr(array[__builtin_bit_cast(int, b)]); // expected-warning {{Unknown}}
```

**Review by steakhal — APPROVED** [review]
LGTM already. You may decide to fix add the extra dump or not.

File: clang/test/Analysis/exercise-ps.c (hunk 1 above)
Comment (pskrgag) [reply clang/test/Analysis/exercise-ps.c:47]: Added dump for both expressions. Thanks!

**Comment by steakhal** [comment]
Backporting to clang-19 in https://github.com/llvm/llvm-project/pull/101684

**Comment by ormris** [comment]
Thanks! Appreciate the fix.
