### PR TITLE
[flang][OpenMP] Privatize vars referenced in statement functions

### LINKED ISSUE #74273: [Flang][OpenMP] Incorrect execution result of using statement function in task construct
```
Version of flang-new : 18.0.0(770dc47659d41a5ca7b7daf5b3134c900ca8c33d)
```

When `statement function` is used within `task` construct, such as in an attached program, the value of the variable (iaa) used in `statement function` does not look like `firstprivate` after `task` construct ends.
If a function is used directly instead of `statement function`, the value of the variable is correct.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

:
```fortran
program main
  integer prv
  if(i)=ifun(iaa)
  prv=1; iaa=1; ii=1
!$omp parallel shared(prv)
!$omp task default(firstprivate)
  prv = prv + 1
  ii=if(ii)
!  ii=ifun(iaa)  ! OK if not statement function
!$omp end task
  write(6,*) "prv = ", prv, " iaa = ", iaa
  if (iaa.ne.1) write(6,*) "NG : iaa = ", iaa
!$omp end parallel
end program main

function ifun(j)
  j=100; ifun=1
end function ifun
```

```
$ export OMP_NUM_THREADS=2; flang-new -fopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =  1  iaa =  1
 prv =  1  iaa =  100
 NG : iaa =  100
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =            1  iaa =            1
 prv =            1  iaa =            1
$
```

```
$ export OMP_NUM_THREADS=2; ifort -qopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =            1  iaa =            1
 prv =            1  iaa =            1
$
```

### PR DESCRIPTION
**Pull request by luporl**
Variables referenced in the body of statement functions need to be
handled as if they are explicitly referenced. Otherwise, they are
skipped during implicit privatization, because statement functions
are represented as procedures in the parse tree.

To avoid missing symbols referenced only in statement functions
during implicit privatization, new symbols, associated with them,
are created and inserted into the context of the directive that
privatizes them. They are later collected and processed in
lowering. To avoid confusing these new symbols with regular ones,
they are tagged with the new OmpFromStmtFunction flag.

Fixes https://github.com/llvm/llvm-project/issues/74273

### CODE REVIEW

File: flang/lib/Semantics/resolve-directives.cpp [hunk 1]
```diff
@@ -2126,23 +2152,59 @@ void OmpAttributeVisitor::Post(const parser::Name &name) {
       // it would have the private flag set.
       // This would make x appear to be defined in p2, causing it to be
       // privatized in p2 and its privatization in p1 to be skipped.
-      auto makePrivateSymbol = [&](Symbol::Flag flag) {
-        Symbol *hostSymbol =
-            lastDeclSymbol ? lastDeclSymbol : &symbol->GetUltimate();
-        lastDeclSymbol = DeclarePrivateAccessEntity(
-            *hostSymbol, flag, context_.FindScope(dirContext.directiveSource));
-        return lastDeclSymbol;
+      // TODO Move the lambda functions below to a separate class.
```
Comment (luporl) [inline flang/lib/Semantics/resolve-directives.cpp:2155]: It would be better to either:

1. Move the lambda functions below to a separate class, or
2. Move the code that handles Implicitly determined DSAs to a separate function and, to handle statement functions, call it for each symbol referenced in them.

This code shall be refactored if the current approach to handle privatization of statement functions' symbols is approved by reviewers.

**Review by tblah — APPROVED** [review]
LGTM. Thanks for the fix!

File: flang/lib/Semantics/resolve-directives.cpp [hunk 2]
```diff
@@ -2075,13 +2084,30 @@ void OmpAttributeVisitor::Post(const parser::Name &name) {
...
+        return;
+      }
+    } else if (!IsPrivatizable(symbol)) {
       return;
     }
 
     // Implicitly determined DSAs
     // OMP 5.2 5.1.1 - Variables Referenced in a Construct
-    Symbol *lastDeclSymbol = nullptr;
+    std::vector<const Symbol *> lastDeclSymbols;
```
Comment (tblah) [inline flang/lib/Semantics/resolve-directives.cpp:2110]: nit: `llvm::SmallVector` is preferred: https://llvm.org/docs/ProgrammersManual.html#vector

**Review by mjklemm — APPROVED** [review]
LGTM

**Comment by luporl** [comment]
Thanks for the reviews @tblah and @mjklemm.

As `OmpAttributeVisitor::Post(const parser::Name &name)` was becoming quite complex, I have refactored it in the last commit. The main changes were:
- Move IsPrivatizable to a separate function.
- Move the code that handles symbols with implicitly determined DSAs to a separate function, `CreateImplicitSymbols`, undoing most changes from the first commit in this part.

This allowed the logic that handles statement function symbols to be simplified. Now we just need to collect non-dummy argument symbols from statement functions and call `CreateImplicitSymbols` for each of them.

File: flang/lib/Semantics/resolve-directives.cpp (hunk 2 above)
Comment (luporl) [reply flang/lib/Semantics/resolve-directives.cpp]: Reverted to using `Symbol *lastDeclSymbol = nullptr` with the refactoring.

File: flang/lib/Semantics/resolve-directives.cpp (hunk 1 above)
Comment (luporl) [reply flang/lib/Semantics/resolve-directives.cpp]: Refactored using approach 2, which allowed for greater simplification of the code.
