### PR TITLE
[SystemZ] Add support for half (fp16)

### LINKED ISSUE #50374: SystemZ Backend: Add support for operations such as FP16_TO_FP and FP_TO_FP16
|  |  |
| --- | --- |
| Bugzilla Link | [51030](https://llvm.org/bz51030) |
| Version | unspecified |
| OS | Linux |
| CC | @River707,@ftynse |

## Extended Description 
Hi, 

Recently we're running test suite of TensorFlow v2.5.0 on s390x (Ubuntu 18.04).  

Test case //tensorflow/compiler/tests:sort_ops_test_cpu fails due to the following error:

LLVM ERROR: Cannot select: 0x3ff14167ca0: f32 = fp16_to_fp 0x3ff14167f10
  0x3ff14167f10: i32,ch = load<(dereferenceable load 2 from %ir.4, !alias.scope !&#8203;6, !noalias !&#8203;4), zext from i16> 0x3ff14197548, 0x3ff141678f8, undef:i64
    0x3ff141678f8: i64,ch = load<(load 8 from %ir.3)> 0x3ff14197548, 0x3ff14167890, undef:i64
      0x3ff14167890: i64 = add nuw 0x3ff141674e8, Constant:i64<8>
        0x3ff141674e8: i64,ch = CopyFromReg 0x3ff14197548, Register:i64 %2
          0x3ff14167480: i64 = Register %2
        0x3ff14167828: i64 = Constant<8>
      0x3ff14167758: i64 = undef
    0x3ff14167758: i64 = undef
In function: compare_lt_WCTTAtafbb4__.7

Other test cases such as //tensorflow/python/keras/optimizer_v2:adam_test and //tensorflow/core/kernels/mlir_generated:abs_cpu_f16_f16_gen_test also fail on s390x due to similar reasons. A related issue (https://github.com/tensorflow/tensorflow/issues/44362) has been raised in TensorFlow GitHub issues.

We think the root cause is lack of support for operations such as FP16_TO_FP and FP_TO_FP16 which perform promotions and truncation for half-precision (16 bit) floating numbers in the SystemZ LLVM backend (llvm/lib/Target/SystemZ/SystemZISelLowering.cpp). Could these features be considered to add to SystemZ LLVM backend? Thanks!

### PR DESCRIPTION
**Pull request by JonPsson1**
Make sure that fp16<=>float conversions are expanded to libcalls and that 16-bit fp values can be loaded and stored properly via GPRs. With this patch the Half IR Type used in operations should be handled correctly with the help of pre-existing ISD node expansions. 

Patch in progress...

Fixes #50374

### CODE REVIEW

**Comment by nikic** [comment]
Note that you need to also have softPromoteHalfType return true to get correct legalization for half operations.

**Comment by JonPsson1** [comment]
> Note that you need to also have softPromoteHalfType return true to get correct legalization for half operations.

Thanks for pointing that out - patch updated.

**Comment by uweigand** [comment]
I think we should define and implement a proper ABI for the half type as well.

**Comment by JonPsson1** [comment]
Patch updated after some progress...

With this version, the fp16 values are passed to conversion functions as integer, which seems to be the default. It is however a bit tricky to do this and at the same time pass half values in FP registers.

At this point I wonder for one thing if it would be better to pass FP16 values to the conversion functions as _Float16 instead? It seems this may be possible to change in the configurations by looking at COMPILER_RT_HAS_FLOAT16 / compiler-rt/lib/builtins/extendhfsf2.c / fp_extend.h...

Not really sure if those conversion functions are supposed to be built and only used for soft-promotion of fp16, or if there are any external implications, for instance gcc compatability.

Any other comments also welcome...

File: clang/test/CodeGen/SystemZ/fexcess-precision.c [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+// RUN: | FileCheck %s -check-prefix=NONE
+
+// RUN: %clang_cc1 -triple s390x-linux-gnu \
+// RUN: -ffloat16-excess-precision=fast -emit-llvm -o - %s \
+// RUN: | FileCheck %s -check-prefix=FAST
+
+_Float16 f(_Float16 a, _Float16 b, _Float16 c, _Float16 d) {
+    return a * b + c * d;
+}
+
```
Comment (arsenm) [inline clang/test/CodeGen/SystemZ/fexcess-precision.c:16]: Test vector cases

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 2]
```diff
@@ -784,6 +791,20 @@ bool SystemZTargetLowering::useSoftFloat() const {
...
 }
 
+MVT SystemZTargetLowering::getRegisterTypeForCallingConv(
+      LLVMContext &Context, CallingConv::ID CC,
+      EVT VT) const {
+  // 128-bit single-element vector types are passed like other vectors,
+  // not like their element type.
+  if (VT.isVector() && VT.getSizeInBits() == 128 &&
+      VT.getVectorNumElements() == 1)
+    return MVT::v16i8;
```
Comment (arsenm) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:801]: Seems unrelated?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 3]
```diff
@@ -784,6 +791,20 @@ bool SystemZTargetLowering::useSoftFloat() const {
...
+  // Keep f16 so that they can be recognized and handled.
+  if (VT == MVT::f16)
```
Comment (arsenm) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:803]: I assume this is because it's an illegal type. It would be much nicer if calling convention code just always worked on the original types to begin with

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 4]
```diff
@@ -1597,6 +1618,15 @@ bool SystemZTargetLowering::splitValueIntoRegisterParts(
     return true;
   }
 
+  // Convert f16 to f32 (Out-arg).
+  if (PartVT == MVT::f16) {
+    assert(NumParts == 1 && "");
```
Comment (arsenm) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:1623]: Remove && "" or make it a meaningful message

File: llvm/test/CodeGen/SystemZ/fp-half.ll [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+; CHECK-NEXT:    ldr %f2, %f0
+; CHECK-NEXT:    ldr %f4, %f0
+; CHECK-NEXT:    ldr %f6, %f0
+; CHECK-NEXT:    mvhi 164(%r15), 0
+; CHECK-NEXT:    brasl %r14, bar@PLT
+; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
+; CHECK-NEXT:    br %r14
+  call void @bar (half 0.0, half 0.0, half 0.0, half 0.0, half 0.0)
+  ret void
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/SystemZ/fp-half.ll:201]: Test vector cases

File: llvm/test/CodeGen/SystemZ/fp-half.ll [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+; CHECK-NEXT:    .cfi_def_cfa_offset 328
+; CHECK-NEXT:    lzer %f0
+; CHECK-NEXT:    ldr %f2, %f0
+; CHECK-NEXT:    ldr %f4, %f0
+; CHECK-NEXT:    ldr %f6, %f0
+; CHECK-NEXT:    mvhi 164(%r15), 0
+; CHECK-NEXT:    brasl %r14, bar@PLT
+; CHECK-NEXT:    lmg %r14, %r15, 280(%r15)
+; CHECK-NEXT:    br %r14
+  call void @bar (half 0.0, half 0.0, half 0.0, half 0.0, half 0.0)
```
Comment (arsenm) [inline llvm/test/CodeGen/SystemZ/fp-half.ll:199]: Test non constant values

File: llvm/test/CodeGen/SystemZ/fp-half.ll [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+; CHECK-NEXT:    vlgvf %r0, %v0, 0
+; CHECK-NEXT:    sth %r0, 0(%r13)
+; CHECK-NEXT:    lmg %r13, %r15, 264(%r15)
+; CHECK-NEXT:    br %r14
+entry:
+  %arg = load half, ptr %Src
+  %Res = call half @foo(half %arg)
+  store half %Res, ptr %Dst
+  ret void
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/SystemZ/fp-half.ll:151]: Test a tail call too

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 2 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:801]: Sorry if this confused things during review but this was just a move of this method from the .h file to the .cpp file, before extending it.

**Comment by uweigand** [comment]
> My understanding is that in GCC's `__gnu_h2f_ieee`/`__gnu_f2h_ieee` is always `i32`<->`i16` (integer ABI), then `__extendhfsf2`/`__truncsfhf2` uses either `int16_t` or `_Float16` on a per-target basis as controlled by `__LIBGCC_HAS_HF_MODE__` (I don't know where this gets set). In LLVM compiler-rt, `COMPILER_RT_HAS_FLOAT16` is the control to do the same thing but it affects `extend`/`trunc` as well as `h2f`/`f2h`. I think the discrepancy works out here because if a target has `_Float16`, it will never be calling `__gnu_h2f_ieee` `__gnu_f2h_ieee`.

From what I can see in the libgcc sources, `__gnu_h2f_ieee`/`__gnu_f2h_ieee` is indeed always `i32`<->`i16`, but it is only present on 32-bit ARM, no other platforms.   On AArch64, GCC will always use inline instructions to perform the conversion.  On 32-bit and 64-bit Intel, the compiler will use inline instructions if AVX512-FP16 is available; if not, but SSE2 is available, the compiler will use `__extendhfsf2`/`__truncsfhf2` with a `HFmode` argument (this corresponds to `_Float16`, i.e. it is passed in SSE2 registers, not like an integer); if not even SSE2 is available, using the type will result in an error.

I never see `__extendhfsf2`/`__truncsfhf2` being used with `int16_t`, even in principle, on any platform in libgcc.  There is indeed a setting `__LIBGCC_HAS_HF_MODE__` (controlled indirectly by the GCC target back-end's `TARGET_LIBGCC_FLOATING_POINT_MODE_SUPPORTED_P` setting), but the only thing that appears to be controlled by this flag is whether routines for complex multiplication and division (`__mulhc3` / `__divhc3`) are being built.   Am I missing something here?

 > From your first two sentences it sounds like `f16` is getting passed in a FP register but going FP->GPR->__gnu_h2f_ieee->FP->some_math_op->FP->__gnu_f2h_ieee->GPR->FP? I think it makes sense to either always pass `f16` as `i16` and avoid the FP registers, or make `_Float16` available so `COMPILER_RT_HAS_FLOAT16` can be used.
> 
> @uweigand mentioned figuring out an ABI for `_Float16`, is this possible? That seems like the best option.

Yes, we're working on that.  What we're planning to do is to have `_Float16` be passed and returned in the same way as `float` and `double`, i.e. using (part of) certain floating-point registers.  These registers are available on every SystemZ architecture level, so we would not have to guard their use (like Intel does with the SSE2 registers).
 
> A quick check seems to show that GCC 13 does not support `_Float16` on s390x, nor does the crossbuild `libgcc.a` provide `__gnu_h2f_ieee`, `__gnu_f2h_ieee`, `__extendhfsf2`, or `__truncsfhf2`. So I think LLVM will be the one to set the precedent here.

Yes, we'd have to add those.  I don't think we want `__gnu_h2f_ieee` or `__gnu_f2h_ieee` as those are ARM-only.  We'd be defining and using `__extendhfsf2` and `__truncsfhf2`, which would be defined with `_Float16` arguments passed in floating-point registers.  Either way, we should define the same set of routines (with the same ABI) in libgcc and compiler-rt.

> Note that there are some common issues with these conversions, would probably be good to test against them if possible #97981 #97975.

Thanks for pointing this out!

**Comment by tgross35** [comment]
> From what I can see in the libgcc sources, `__gnu_h2f_ieee`/`__gnu_f2h_ieee` is indeed always `i32`<->`i16`, but it is only present on 32-bit ARM, no other platforms. On AArch64, GCC will always use inline instructions to perform the conversion. On 32-bit and 64-bit Intel, the compiler will use inline instructions if AVX512-FP16 is available; if not, but SSE2 is available, the compiler will use `__extendhfsf2`/`__truncsfhf2` with a `HFmode` argument (this corresponds to `_Float16`, i.e. it is passed in SSE2 registers, not like an integer); if not even SSE2 is available, using the type will result in an error.
>
> I never see `__extendhfsf2`/`__truncsfhf2` being used with `int16_t`, even in principle, on any platform in libgcc. There is indeed a setting `__LIBGCC_HAS_HF_MODE__` (controlled indirectly by the GCC target back-end's `TARGET_LIBGCC_FLOATING_POINT_MODE_SUPPORTED_P` setting), but the only thing that appears to be controlled by this flag is whether routines for complex multiplication and division (`__mulhc3` / `__divhc3`) are being built. Am I missing something here?
 
I think this is accurate, libgcc just appears to (reasonably) not provide any f16-related symbols on platforms where GCC doesn't support `_Float16`. LLVM does seem to use `__gnu_h2f_ieee` and `__gnu_f2h_ieee` though, on targets where Clang doesn't have `_Float16` (e.g. PowerPC, Wasm, x86-32 without SSE), which is why it shows up in the current state of this PR. Presumably this is `HasLegalHalfType`?

For that reason we just always provide the symbol [in rust's compiler-builtins](https://github.com/rust-lang/compiler-builtins/blob/adaef3265c560998a03b6902bd63d88009d3a132/src/float/trunc.rs#L139-L145) (though we let LLVM figure out that `f16` is `i16`).

> > @uweigand mentioned figuring out an ABI for `_Float16`, is this possible? That seems like the best option.
> 
> Yes, we're working on that. What we're planning to do is to have `_Float16` be passed and returned in the same way as `float` and `double`, i.e. using (part of) certain floating-point registers. These registers are available on every SystemZ architecture level, so we would not have to guard their use (like Intel does with the SSE2 registers).

That is great news, especially considering how problematic the target-feature-dependent ABI on x86-32 has been.

File: clang/lib/Sema/SemaExpr.cpp [hunk 8]
```diff
@@ -16534,7 +16534,7 @@ ExprResult Sema::BuildVAArgExpr(SourceLocation BuiltinLoc,
           PromoteType = QualType();
       }
     }
-    if (TInfo->getType()->isSpecificBuiltinType(BuiltinType::Float))
+    if (TInfo->getType()->isFloat16Type() || TInfo->getType()->isFloat32Type())
```
Comment (uweigand) [inline clang/lib/Sema/SemaExpr.cpp:16537]: Why add this promotion rule?   This seems to directly contradict the specification here: https://clang.llvm.org/docs/LanguageExtensions.html

>Because default argument promotion only applies to the standard floating-point types, _Float16 values are not promoted to double when passed as variadic or untyped arguments.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 9]
```diff
@@ -711,6 +711,13 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
     setOperationAction(ISD::BITCAST, MVT::f32, Custom);
   }
 
+  // Expand FP16 <=> FP32 conversions to libcalls and handle FP16 loads and
+  // stores in GPRs.
+  setOperationAction(ISD::FP16_TO_FP, MVT::f32, Expand);
+  setOperationAction(ISD::FP_TO_FP16, MVT::f32, Expand);
+  setLoadExtAction(ISD::EXTLOAD, MVT::f32, MVT::f16, Expand);
+  setTruncStoreAction(MVT::f32, MVT::f16, Expand);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:719]: Do we need to support *both* the conversion operations *and* the truncate/extend?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 10]
```diff
@@ -1597,6 +1618,15 @@ bool SystemZTargetLowering::splitValueIntoRegisterParts(
     return true;
   }
 
+  // Convert f16 to f32 (Out-arg).
+  if (PartVT == MVT::f16) {
+    assert(NumParts == 1 && "");
+    SDValue I16Val = DAG.getBitcast(MVT::i16, Val);
+    SDValue I32Val = DAG.getAnyExtOrTrunc(I16Val, DL, MVT::i32);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:1625]: Doesn't this place the f16 into the *low* bytes of the f32, rather than the high bytes?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 11]
```diff
@@ -1612,6 +1642,18 @@ SDValue SystemZTargetLowering::joinRegisterPartsIntoValue(
...
 
+// F32Val holds a f16 value in f32, return it as an f16 (In-arg). The
+// CopyFromReg was made into an f32 as required as FP32 registers are used
+// for arguments, now convert it to f16.
+static SDValue convertF32ToF16(SDValue F32Val, SelectionDAG &DAG,
+                               const SDLoc &DL) {
+  assert(F32Val->getOpcode() == ISD::CopyFromReg &&
+         "Only expecting to handle f16 with CopyFromReg here.");
+  SDValue I32Val = DAG.getBitcast(MVT::i32, F32Val);
+  SDValue I16Val = DAG.getAnyExtOrTrunc(I32Val, DL, MVT::i16);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:1653]: Likewise here?

File: llvm/test/CodeGen/SystemZ/fp-half.ll [hunk 12]
```diff
@@ -0,0 +1,201 @@
...
+; CHECK-NEXT:    .cfi_offset %r14, -48
+; CHECK-NEXT:    .cfi_offset %r15, -40
+; CHECK-NEXT:    aghi %r15, -168
+; CHECK-NEXT:    .cfi_def_cfa_offset 328
+; CHECK-NEXT:    std %f8, 160(%r15) # 8-byte Folded Spill
+; CHECK-NEXT:    .cfi_offset %f8, -168
+; CHECK-NEXT:    vlgvf %r0, %v2, 0
+; CHECK-NEXT:    llghr %r2, %r0
+; CHECK-NEXT:    vlgvf %r13, %v0, 0
+; CHECK-NEXT:    brasl %r14, __gnu_h2f_ieee@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-half.ll:21]: I believe we should be using `__extendhfsf2` / `__truncsfhf2` here.  At least in GCC, the `__gnu_` routines are treated as something specific to ARM.

File: clang/lib/Sema/SemaExpr.cpp (hunk 8 above)
Comment (JonPsson1) [reply clang/lib/Sema/SemaExpr.cpp:16537]: ah, ok - removed.

**Comment by JonPsson1** [comment]
Patch reworked:

- Make f16 a legal type using FP16BitRegClass in order to properly model in/out args with physregs.

- Add FP16 register class (not "VR16"), and have everything work correctly also without vector support.

- Conversion functions added as libcalls, taking args in fp registers.

(twoaddr-kill.mir test updated as the hard-coded register class enum value for GRH32BitRegClass has changed.)

Still some more points to go over, but it seems to be working fairly well at this point.

- Todo:
  - vector f16..?
  - Support strict F16 as well?
  - atomic memops?
  - Maybe check SystemZTTI cost functions to make sure they do not give low costs for vector operations?
  - F16 vector constants, loads ands stores are not needed (at least currently).

**Comment by JonPsson1** [comment]
Patch improved further:

- Atomic memops handled.

- Spill/reload
  Handled in loadRegFromStackSlot() and storeRegToStackSlot(). VRegs can be used here which
  makes it straightforward, but special sequences needed (without using VSTE/VLE).

- __fp16:
  HalfArgsAndReturns=true => __fp16 arguments allowed.
  Tests added.

- f16 vectors:
  Tests added. All seems to work.

- strict fp:
  Again the question of conversion functions:
  IDS::STRICT_FP_ROUND/STRICT_FP_EXTEND needs to be lowered to something, but not sure
  if that requires special treatment, or if the same conversion functions can be used.
  Maybe wait with strict fp16?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 13]
```diff
@@ -102,6 +102,7 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
     addRegisterClass(MVT::i32, &SystemZ::GR32BitRegClass);
   addRegisterClass(MVT::i64, &SystemZ::GR64BitRegClass);
   if (!useSoftFloat()) {
+    addRegisterClass(MVT::f16, &SystemZ::FP16BitRegClass);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:105]: Do we want to add a VR16BitRegClass if we have vector support?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 14]
```diff
@@ -513,11 +514,37 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
...
        I <= MVT::LAST_FP_VALUETYPE;
        ++I) {
     MVT VT = MVT::SimpleValueType(I);
     if (isTypeLegal(VT)) {
+      // No special instructions for these.
+      setOperationAction(ISD::FSIN, VT, Expand);
+      setOperationAction(ISD::FCOS, VT, Expand);
+      setOperationAction(ISD::FSINCOS, VT, Expand);
+      setOperationAction(ISD::FREM, VT, Expand);
+      setOperationAction(ISD::FPOW, VT, Expand);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:544]: Shouldn't these be Promote just like all the other f16 operations?   Expand triggers a libcall, which doesn't match the excess-precision setting - also, we actually don't have f16 libcalls in libm ...

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 15]
```diff
@@ -6108,6 +6160,133 @@ static SDValue lowerAddrSpaceCast(SDValue Op, SelectionDAG &DAG) {
...
+  SDValue In = Op.getOperand(IsStrict ? 1 : 0);
+  MVT VT = Op.getSimpleValueType();
+  MVT SVT = In.getSimpleValueType();
+  if (SVT != MVT::f16)
+    return Op;
+
+  SDLoc DL(Op);
+  SDValue Chain = IsStrict ? Op.getOperand(0) : SDValue();
+
+  // Need a libcall.  XXX factor out (below)
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6175]: Can't we just return SDValue() here so that common call falls back to Expand (which in this case generates a libcall)?

File: clang/lib/Basic/Targets/SystemZ.h [hunk 16]
```diff
@@ -91,11 +91,28 @@ class LLVM_LIBRARY_VISIBILITY SystemZTargetInfo : public TargetInfo {
...
+
+    // True if the backend supports operations on the half LLVM IR type.
+    // By setting this to false, conversions will happen for _Float16 around
+    // a statement by default, with operations done in float. However, if
+    // -ffloat16-excess-precision=none is given, no conversions will be made
+    // and instead the backend will promote each half operation to float
+    // individually.
+    HasLegalHalfType = false;
+    // Allow half arguments and return values (__fp16).
+    HalfArgsAndReturns = true;
```
Comment (uweigand) [inline clang/lib/Basic/Targets/SystemZ.h:103]: I don't think we should support this, this looks like a ARM-only feature.  It's false on Intel as well.

File: clang/lib/CodeGen/Targets/SystemZ.cpp [hunk 17]
```diff
@@ -185,6 +185,8 @@ bool SystemZABIInfo::isFPArgumentType(QualType Ty) const {
 
   if (const BuiltinType *BT = Ty->getAs<BuiltinType>())
     switch (BT->getKind()) {
+    case BuiltinType::Half:     // __fp16
```
Comment (uweigand) [inline clang/lib/CodeGen/Targets/SystemZ.cpp:188]: Then I think we shouldn't have this either.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 18]
```diff
@@ -6108,6 +6160,133 @@ static SDValue lowerAddrSpaceCast(SDValue Op, SelectionDAG &DAG) {
...
+  if (VT != MVT::f16)
+    return SDValue(); // XXX?
+
+  SDLoc DL(Op);
+  SDValue Chain = IsStrict ? Op.getOperand(0) : SDValue();
+
+  if (SVT != MVT::f32) {
+    SDValue Rnd = DAG.getIntPtrConstant(0, DL, /*isTarget=*/true);
+    In = DAG.getNode(ISD::FP_ROUND, DL, MVT::f32, In, Rnd);
+  }
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6211]: The double rounding may yield an incorrect result.  I think GCC just uses different libcalls for all source types.  Another alternative might be to use the "round to prepare for shorter precision" mode for the first operation.

**Review by uweigand — COMMENTED** [review]
Not a full review, but some general comments inline.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 13 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:105]: So far I have a few points as "todo" for vector support:
  - add a VR16 reg class
  - use VLE/VSTE for reload/spill
  - Use generated vector constants.
 It wouldn't be too hard to add this, but not sure if it's relevant given all the slow conversion function calls. On the other hand, even if it's super-slow, maybe a noticeable speedup might have some value..?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 14 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:544]: I tried Promote but ended up with an f32 operation that was not handled further. Did not find anything like "promote and expand/re-visit", unfortunately, so I did a manual "custom-promotion" and then common-code revisited the new f32 node.

As there is no support for these libcalls for f16, it seems only the corresponding llvm intrinsics need to be handled, I would assume. I started with this, but not quite sure if this is the right way or how many of these (all?) should be handled here.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 15 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6175]: huh - you're right. ExpandNode() fails but it fall-through to ConvertNodeToLibcall().

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 18 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6211]: ok - seems to work fine to let LegalizeDAG expand these conversions also given that those different versions are available.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 19]
```diff
@@ -6285,6 +6465,16 @@ SDValue SystemZTargetLowering::LowerOperation(SDValue Op,
     return lowerAddrSpaceCast(Op, DAG);
   case ISD::ROTL:
     return lowerShift(Op, DAG, SystemZISD::VROTL_BY_SCALAR);
+  case ISD::FP_EXTEND:
+//case ISD::STRICT_FP_EXTEND:
```
[the remark this answers is not in the document]
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6469]: fixed

File: clang/lib/Basic/Targets/SystemZ.h (hunk 16 above)
Comment (JonPsson1) [reply clang/lib/Basic/Targets/SystemZ.h]: ok removed. Interesting that this is left out on purpose even though it would be simple to allow...

**Comment by JonPsson1** [comment]
Updated per review.

- strict fp-round / fp-extend added with tests.
- math functions like fsin promoted instead of expanded to non-existing fsinh.
- conversion functions from e.g. f16 -> f64 used instead of separate steps.
- __fp16 argument/return values removed (and tests in systemz-abi.c removed).
- docs/LanguageExtensions: SystemZ added as supporting _Float16.

Note on compiler-rt: not sure how to build llvm conversion functions and link them (have not tried this yet), but added the mapping in RuntimeLibcalls.cpp.

File: llvm/lib/IR/RuntimeLibcalls.cpp [hunk 20]
```diff
@@ -255,4 +255,9 @@ void RuntimeLibcallsInfo::initLibcalls(const Triple &TT) {
     }
     setLibcallName(RTLIB::MULO_I128, nullptr);
   }
+
+  if (TT.isSystemZ()) {
+    setLibcallName(RTLIB::FPROUND_F32_F16, "__truncsfhf2");
+    setLibcallName(RTLIB::FPEXT_F16_F32, "__extendhfsf2");
+  }
```
Comment (tgross35) [inline llvm/lib/IR/RuntimeLibcalls.cpp:262]: Why do these names need to be set, aren't these the default?

Comment (JonPsson1) [reply llvm/lib/IR/RuntimeLibcalls.cpp:262]: you may be right - as I wrote above I have not really tried this before. Would you happen to know how to build and link these?

Comment (tgross35) [reply llvm/lib/IR/RuntimeLibcalls.cpp:262]: Hm, I see they default to the `__gnu_` functions in this file. Some targets (wasm, hexagon) manually set it to `__extendhfsf2` and `__truncsfhf2` in `*SelfLowering.cpp` but why do targets like x86 correctly lower to these as well without an override either in this file or in selflowering?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 14 above)
Comment (tgross35) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp]: Just crosslinking that there is an effort to add f16 libcalls https://github.com/llvm/llvm-project/issues/95250 but I have no clue what the plan is as far as lowering to them.

File: llvm/lib/IR/RuntimeLibcalls.cpp (hunk 20 above)
Comment (tgross35) [reply llvm/lib/IR/RuntimeLibcalls.cpp:262]: Regarding how to build and link, they are in compiler-rt if that can be built https://github.com/llvm/llvm-project/blob/fa22100d57631bbb0a507dd27e3ebb24b1354623/compiler-rt/lib/builtins/truncsfhf2.c#L15. `__trunc` and `__extend` are what you want to emit here, I'm just not sure what exactly this file needs to do because it seems like `HasLegalHalfType` controls `__extend`/`__trunc` vs. `__gnu_` lowering somehow https://github.com/llvm/llvm-project/pull/109164#issuecomment-2433525551.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 13 above)
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:105]: If it's not too hard, I think it might be good. Not so much because of performance, but also because it makes the code look more similar to what we do for the other types.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 21]
```diff
@@ -513,11 +514,26 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
...
   // Handle floating-point types.
+  // Promote all f16 operations to float, with some exceptions below.
+  for (unsigned Opc = 0; Opc < ISD::BUILTIN_OP_END; ++Opc)
+    setOperationAction(Opc, MVT::f16, Promote);
+  setOperationAction(ISD::ConstantFP, MVT::f16, Expand);
+  for (MVT VT : {MVT::f32, MVT::f64, MVT::f128}) {
+    setLoadExtAction(ISD::EXTLOAD, VT, MVT::f16, Expand);
+    setTruncStoreAction(VT, MVT::f16, Expand);
+    setOperationAction(ISD::FP_EXTEND, VT, Custom);
+    setOperationAction(ISD::STRICT_FP_EXTEND, VT, Custom);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:525]: Minor nit, but those two should probably be done in the loop below.

Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp]: Moved them down but not sure if they should be together (as they are treated the same), or if we should maintain the separation of the STRICT operations (-> move FP_EXTEND up)

**Comment by JonPsson1** [comment]
Improved handling to utilize vector instructions when present. New VR16 regclass, but v8f16 *not* legal. It might make sense to have it as a legal type and e.g. do VL;VST when moving vectors in memory, and also set all vector ops to "Expand". Not sure how trivial that change would be, given some special handlings of vector nodes, so not done as of now: only the scalar f16 is legal.

Seems to work fine to add "16" versions for loads, stores and lzer/lcdfr in case of vector support.

Without vector support, it might make sense to have load/store pseudos with an extra GPR def operand, so that these loads/stores can be expanded as a PostRA pseudo. Then it would only need handling in one place, but OTOH having a second explicit def operand is also undesired, maybe.

f16 immediates handled like f32:
- Basic support added for fp 0.0/-0.0 and generation of vector constants (which should always work btw given their size with vrepih).
- Single-lane vector instructions like WFLCSB not used for fp16 (yet), even though it should be possible to add _16 variants. Doesn't seem important, so skipping.

Should fp16 inline asm operands also be supported at this point?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 21 above)
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp]: I don't have a strong opinion on that.  How you do it currently looks fine to me.

File: llvm/lib/Target/SystemZ/SystemZInstrFP.td [hunk 22]
```diff
@@ -47,8 +49,11 @@ def LDR : UnaryRR <"ldr", 0x28,   null_frag, FP64,  FP64>;
 def LXR : UnaryRRE<"lxr", 0xB365, null_frag, FP128, FP128>;
 
 // For z13 we prefer LDR over LER to avoid partial register dependencies.
-let isCodeGenOnly = 1 in
-  def LDR32 : UnaryRR<"ldr", 0x28, null_frag, FP32, FP32>;
+let isCodeGenOnly = 1 in {
+  def LER16 : UnaryRR <"ler", 0x38, null_frag, FP16, FP16>;
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZInstrFP.td:53]: Formatting is a bit odd here.

File: llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp [hunk 23]
```diff
@@ -1883,6 +1931,10 @@ void SystemZInstrInfo::getLoadStoreOpcodes(const TargetRegisterClass *RC,
   } else if (RC == &SystemZ::FP128BitRegClass) {
     LoadOpcode = SystemZ::LX;
     StoreOpcode = SystemZ::STX;
+  } else if (RC == &SystemZ::FP16BitRegClass ||
+             RC == &SystemZ::VR16BitRegClass) {
+    LoadOpcode = SystemZ::VL16;
```
[the remark this answers is not in the document]
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1936]: Yes, for instance in spill-half-01.mir.

[the remark this answers is not in the document]
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1936]: What I meant is that `VL16` is defined as having a `v16hb` return value
```
    def VL16 : UnaryAliasVRX<z_load, v16hb, bdxaddr12pair>;
```
and `v16hb` is defined to live in `VR16` - *not* `FP16`:
```
def v16hb   : TypedReg<f16,     VR16>;
```

So it seems to me forcing a `FP16` register into the instruction, even if it might seem to do what we want, is not really allowed and might e.g. trigger strict MI checking failures ...

[the remark this answers is not in the document]
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1936]: I was assuming this would work, as FP16 should be a sub-registerclass of VR16 - all FP16 regs are also contained in VR16. I see in the generated file:

```
static const TargetRegisterClass *const FP16BitSuperclasses[] = {
  &SystemZ::VR16BitRegClass,
  nullptr
};
```
Given that, and that -verify-machineinstrs is used in spill-half-01.mir, it seems ok to me.

[the remark this answers is not in the document]
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1936]: Ah OK.  That's probably fine then.

**Comment by JonPsson1** [comment]
>> Without vector support, it might make sense to have load/store pseudos with an extra GPR def operand, so that these loads/stores can be expanded as a PostRA pseudo. Then it would only need handling in one place, but OTOH having a second explicit def operand is also undesired, maybe.

> I don't think we need to spend much effort optimizing for pre-z13 machines at this point.

This wouldn't be an optimization, rather just handling the shift + insert sequences needed for older machines in one place, instead of as of now in both lowerLoadF16(), and in loadRegFromStackSlot() (and similarly for stores).

> Also, looks like the clang-format check is complaining a bit ...

Fixed.

Inline-assembly support for half with tests added.

Implemented bitcast i16<->f16 with vector support but letting it fall back to store+load bitcasting for older archs. This type of bitcasting is used with inline-assembly.

**Comment by JonPsson1** [comment]
Spill f16 using float instructions into 4-byte stack slots:

- Seems to work to use a RegInfoByHwMode to reset the SpillSize for FP16 to 32 bits. By using two HwMode:s, the spill size can still be 16 bits with vector support.

- Using new LE16/STE16 opcodes seems easier than extracting/inserting subregs in storeRegToStackSlot() / loadRegFromStackSlot() via FP32 regs, although that could also work.

**Comment by JonPsson1** [comment]
I was hoping these added lines would enable the conversion functions, but it doesn't seem to work:

```
+  if (TT.isSystemZ()) {
+    setLibcallName(RTLIB::FPROUND_F32_F16, "__truncsfhf2");
+    setLibcallName(RTLIB::FPEXT_F16_F32, "__extendhfsf2");
+  }

clang -target s390x-linux-gnu -march=z16 ./test.c -O3 -o ./a.out --rtlib=compiler-rt
/usr/bin/ld: cannot find /home/ijonpan/llvm-project/build/lib/clang/20/lib/s390x-unknown-linux-gnu/libclang_rt.builtins.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
There is something like COMPILER_RT_HAS_${arch}_FLOAT16 in compiler-rt/lib/builtins/CMakeLists.txt, but I can't find anyplace to add s390x to the targets that will build libclang_rt.builtins.a.

I have configured with -DLLVM_ENABLE_PROJECTS="clang;compiler-rt"

Would anyone know off-hand how to make this work? Thanks.
@nikic @phoebewang @kito-cheng @tgross35

**Comment by efriedma-quic** [comment]
I think you're looking for -DLLVM_RUNTIME_TARGETS ?

**Comment by JonPsson1** [comment]
> -DLLVM_RUNTIME_TARGETS

Thanks.  If I use cmake with -DLLVM_RUNTIME_TARGETS=systemz, and then rebuild, I see one more file being built:

```
ninja
[6/6] Linking CXX shared library lib/clang/20/lib/s390x-unknown-linux-gnu/libclang_rt.asan.so

```
However it does not seem to be quite the file that I need to run my program:

```
./bin/clang -target s390x-linux-gnu -march=z16 ./test4.c -O3 -o ./a.out --rtlib=compiler-rt
/usr/bin/ld: cannot find /home/ijonpan/llvm-project/build/lib/clang/20/lib/s390x-unknown-linux-gnu/libclang_rt.builtins.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Even so, I don't understand why this wouldn't follow if I enable compiler-rt as a project...

**Comment by efriedma-quic** [comment]
I think you need to do some target-specific stuff to get the builtins library to build... see, for example, https://reviews.llvm.org/D42958 .

File: clang/lib/CodeGen/Targets/SystemZ.cpp [hunk 24]
```diff
@@ -446,10 +448,11 @@ ABIArgInfo SystemZABIInfo::classifyArgumentType(QualType Ty) const {
 
     // The structure is passed as an unextended integer, a float, or a double.
     if (isFPArgumentType(SingleElementTy)) {
-      assert(Size == 32 || Size == 64);
+      assert(Size == 16 || Size == 32 || Size == 64);
       return ABIArgInfo::getDirect(
-          Size == 32 ? llvm::Type::getFloatTy(getVMContext())
-                     : llvm::Type::getDoubleTy(getVMContext()));
+          Size == 16   ? llvm::Type::getHalfTy(getVMContext())
```
Comment (arsenm) [inline clang/lib/CodeGen/Targets/SystemZ.cpp:453]: This will break on bfloat, don't assume type size -> fp type

Comment (JonPsson1) [reply clang/lib/CodeGen/Targets/SystemZ.cpp:453]: bfloat is not enabled on SystemZ so shouldn't this be safe?

**Comment by JonPsson1** [comment]
Thanks for help - I think I found the way to enable the building of these functions - patch updated.

I could now (for the first time? :D ) compile and run a program on SystemZ with _Float16 variables, by using `--rtlib=compiler-rt `with clang.

As I am not the expert on FP semantics, I wonder if anyone could confirm that these routines are safe and correct to use as far as FP exceptions, rounding modes, (..?) goes?

File: clang/lib/CodeGen/Targets/SystemZ.cpp (hunk 24 above)
Comment (arsenm) [reply clang/lib/CodeGen/Targets/SystemZ.cpp:453]: I don't think it matters if it's reachable or not, should write future proof code and avoid repeating this pattern

**Comment by JonPsson1** [comment]
Patch rebased and updated.

-- Saw two failing compiler-rt tests now:

```
Failed Tests (2):
  Builtins-s390x-linux :: clear_cache_test.c
  Builtins-s390x-linux :: enable_execute_stack_test.c

```
  clear_cache_test.c contains a call to the compiler-rt clear_cache() function. From README.txt:

```
  // __clear_cache() is used to tell process that new instructions have been
  // written to an address range.  Necessary on processors that do not have
  // a unified instruction and data cache.
  void __clear_cache(void* start, void* end);

  // __enable_execute_stack() is used with nested functions when a trampoline
  // function is written onto the stack and that page range needs to be made
  // executable.
  void __enable_execute_stack(void* addr);

```
I see a lot of target specific pre-processing in clear_cache.c that either disables this to a no-op, or does something target specific. The test itself this is disabled for some targets. Seems reasonable to leave this as unsupported and disable the test (for now?). Also disabling enable_execute_stack_test.c.

-- The 'bool HalfArgsAndReturns' Clang flag seems to desipite the name only be relevant for __fp16, so it is kept as the default 'false'. Added a comment next to it.

-- Handling of FP-args types / sizes updated per review. This was a bit more involved than I first thought as over-alignments actually imply a greater size and type.

-- Added tests for overaligned (a4 / a16)  _Float16 in systemz-abi.c.

@uweigand: patch ready for a review now.

File: clang/lib/CodeGen/Targets/SystemZ.cpp (hunk 24 above)
Comment (JonPsson1) [reply clang/lib/CodeGen/Targets/SystemZ.cpp]: ok - patch updated to do this mapping in a direct way. It was actually more beneficial perhaps than merely guarding against bfloat, as the Size can reflect an overalignment in which case the (for historical reasons I beleive) type actually changes to match the alignment.

File: clang/lib/CodeGen/Targets/SystemZ.cpp [hunk 25]
```diff
@@ -179,20 +179,31 @@ bool SystemZABIInfo::isVectorArgumentType(QualType Ty) const {
...
+llvm::Type *SystemZABIInfo::getFPArgumentType(QualType Ty,
+                                              uint64_t Size) const {
   if (IsSoftFloatABI)
-    return false;
+    return nullptr;
 
   if (const BuiltinType *BT = Ty->getAs<BuiltinType>())
     switch (BT->getKind()) {
+    case BuiltinType::Float16:
+      if (Size == 16)
```
Comment (arsenm) [inline clang/lib/CodeGen/Targets/SystemZ.cpp:193]: I don't understand why a size check is necessary; Float16 implies the size?

File: clang/lib/CodeGen/Targets/SystemZ.cpp [hunk 26]
```diff
@@ -179,20 +179,31 @@ bool SystemZABIInfo::isVectorArgumentType(QualType Ty) const {
...
+        return llvm::Type::getHalfTy(getVMContext());
+      LLVM_FALLTHROUGH;
     case BuiltinType::Float:
+      if (Size == 32)
```
Comment (arsenm) [inline clang/lib/CodeGen/Targets/SystemZ.cpp:197]: Same here. The important part was explicit handling of the types, and that bfloat is separate from half

**Comment by uweigand** [comment]
> I see a lot of target specific pre-processing in clear_cache.c that either disables this to a no-op, or does something target specific. The test itself this is disabled for some targets. Seems reasonable to leave this as unsupported and disable the test (for now?). Also disabling enable_execute_stack_test.c.

Both clear_cache and enable_execute_stack should just be empty no-op functions on our platform.

File: clang/lib/CodeGen/Targets/SystemZ.cpp (hunk 25 above)
Comment (JonPsson1) [reply clang/lib/CodeGen/Targets/SystemZ.cpp:193]: As I wrote earlier, in cases of a single element struct containing e.g. a _Float16 aligned to 8 bytes, the argument will be passed as a Double. At this point, the Size reflects this situation. I guess that's why the code looked like it did before.

**Comment by JonPsson1** [comment]
> Both clear_cache and enable_execute_stack should just be empty no-op functions on our platform.
ah - ok. I fixed clear_cache.c, and this also took care of the other test case which was calling it.

**Comment by JonPsson1** [comment]
rebase

**Comment by tgross35** [comment]
What is needed to move this forward?

**Comment by JonPsson1** [comment]
> What is needed to move this forward?

The review is in progress so this should hopefully land quite soon.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 27]
```diff
@@ -541,11 +543,26 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
...
+  for (MVT VT : {MVT::f32, MVT::f64, MVT::f128}) {
+    setLoadExtAction(ISD::EXTLOAD, VT, MVT::f16, Expand);
+    setTruncStoreAction(VT, MVT::f16, Expand);
+  }
+  for (auto Op : {ISD::LOAD, ISD::ATOMIC_LOAD, ISD::STORE, ISD::ATOMIC_STORE})
+    setOperationAction(Op, MVT::f16, Subtarget.hasVector() ? Legal : Custom);
+  setOperationAction(ISD::FP_ROUND, MVT::f16, LibCall);
+  setOperationAction(ISD::STRICT_FP_ROUND, MVT::f16, LibCall);
+  if (Subtarget.hasVector()) // f16 <-> i16 bitcasts.
+    setOperationAction(ISD::BITCAST, MVT::i16, Custom);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:559]: Not sure about the whole `BITCAST` story here.  `f16` should now be legal always, whether we have vector support or not (either in VR16 or FP16).  That seems to imply that we'll have to have a `BITCAST` implementation in both cases too - does it not?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 28]
```diff
@@ -6464,6 +6522,70 @@ static SDValue lowerAddrSpaceCast(SDValue Op, SelectionDAG &DAG) {
...
+                       Ld->getBasePtr(), Ld->getPointerInfo(), MVT::i16,
+                       Ld->getOriginalAlign(), Ld->getMemOperand()->getFlags());
+  }
+  // Load as integer, shift and then insert into upper 2 bytes of the FP
+  // register.
+  SDValue Shft = DAG.getNode(ISD::SHL, DL, MVT::i32, NewLd,
+                             DAG.getConstant(16, DL, MVT::i32));
+  SDValue BCast = DAG.getNode(ISD::BITCAST, DL, MVT::f32, Shft);
+  SDValue F16Val =
+      DAG.getTargetExtractSubreg(SystemZ::subreg_h16, DL, MVT::f16, BCast);
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6560]: I guess this would be a generic BITCAST implementation, but it's only used here - should this be made more generic?  Also, if we do have vector support, we could do better than the shift sequence ...

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 29]
```diff
@@ -6769,11 +6898,20 @@ SystemZTargetLowering::LowerOperationWrapper(SDNode *N,
...
+    SDLoc DL(N);
     SDValue Src = N->getOperand(0);
-    if (N->getValueType(0) == MVT::i128 && Src.getValueType() == MVT::f128 &&
-        !useSoftFloat()) {
-      SDLoc DL(N);
+    EVT SrcVT = Src.getValueType();
+    EVT ResVT = N->getValueType(0);
+    if (ResVT == MVT::i128 && SrcVT == MVT::f128 && !useSoftFloat())
       Results.push_back(expandBitCastF128ToI128(DAG, Src, DL));
+    else if (SrcVT == MVT::i16 && ResVT == MVT::f16) {
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6907]: Do we need a soft-float check here?  What *is* happening with f16 in soft-float anyway?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 30]
```diff
@@ -6769,11 +6898,20 @@ SystemZTargetLowering::LowerOperationWrapper(SDNode *N,
...
+      SDValue In32 = DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i32, Src);
+      Results.push_back(
+          SDValue(DAG.getMachineNode(SystemZ::LEFR_16, DL, MVT::f16, In32), 0));
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6910]: This unconditionally uses vector instructions.  What if we don't have those?  Do we need a full BITCAST for all cases?

File: compiler-rt/lib/builtins/clear_cache.c [hunk 31]
```diff
@@ -65,6 +65,7 @@ void __clear_cache(void *start, void *end) {
 #elif defined(_WIN32) && (defined(__arm__) || defined(__aarch64__))
   FlushInstructionCache(GetCurrentProcess(), start, end - start);
 #elif defined(__arm__) && !defined(__APPLE__)
+#elif defined(__s390__)
```
[the remark this answers is not in the document]
Comment (JonPsson1) [reply compiler-rt/lib/builtins/clear_cache.c:68]: Oh - it looked to me that arm was doing like Intel above as there was no indentation for the nested prepocessor macro. Will move it up to below Intel.

File: clang/include/clang/Basic/TargetInfo.h [hunk 32]
```diff
@@ -229,7 +229,7 @@ class TargetInfo : public TransferrableTargetInfo,
   bool NoAsmVariants;  // True if {|} are normal characters.
   bool HasLegalHalfType; // True if the backend supports operations on the half
                          // LLVM IR type.
-  bool HalfArgsAndReturns;
+  bool HalfArgsAndReturns; // OpenCL 6.1.1.1, NEON (IEEE 754-2008 half) type.
```
[the remark this answers is not in the document]
Comment (JonPsson1) [reply clang/include/clang/Basic/TargetInfo.h:232]: I tried to make it clear that it relates to __fp16 and not _Float16, like in Type.h:

```
  bool isHalfType() const;         // OpenCL 6.1.1.1, NEON (IEEE 754-2008 half)
  bool isFloat16Type() const;      // C11 extension ISO/IEC TS 18661
```
It's all a bit confusing with all the different names for f16 types. Half seems to relate either to the LLVM I/R type, or to the ARM __fp16 type. HasLegalHalfType refers to LLVM I/R, while HalfArgsAndReturns relate to ARM (IIUC).

File: llvm/lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp [hunk 33]
```diff
@@ -35,100 +35,96 @@ using namespace llvm;
...
 const unsigned SystemZMC::CR64Regs[16] = {
-  SystemZ::C0, SystemZ::C1, SystemZ::C2, SystemZ::C3,
-  SystemZ::C4, SystemZ::C5, SystemZ::C6, SystemZ::C7,
-  SystemZ::C8, SystemZ::C9, SystemZ::C10, SystemZ::C11,
-  SystemZ::C12, SystemZ::C13, SystemZ::C14, SystemZ::C15
-};
+    SystemZ::C0,  SystemZ::C1,  SystemZ::C2,  SystemZ::C3,
+    SystemZ::C4,  SystemZ::C5,  SystemZ::C6,  SystemZ::C7,
+    SystemZ::C8,  SystemZ::C9,  SystemZ::C10, SystemZ::C11,
+    SystemZ::C12, SystemZ::C13, SystemZ::C14, SystemZ::C15};
```
[the remark this answers is not in the document]
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp:127]: Done

File: clang/lib/CodeGen/Targets/SystemZ.cpp (hunk 25 above)
Comment (JonPsson1) [reply clang/lib/CodeGen/Targets/SystemZ.cpp:193]: I am not sure how that would work: provided that getTypeSize() returns the size of the struct, which will match any alignment of the element, we need the size value to get the right type for the element, and the SingleElementTy to know that it is actually an fp type.

Maybe the switch could be simplified a bit by checking first that the SingleElementTy is one of these three types, and then return the type based on the size only?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 28 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6560]: See inline comment.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 30 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6910]: Bitcast without vector via mem.
BITCAST handling is needed AFAIK for IR bitcast instructions, and also for inline assembly that e.g. uses an 'f' constraint while passing an i16 value.
Seems to be working according to added tests.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 29 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6907]: Wrapping all setXXXAction() calls for f16 with a guard against soft-float, which should make sure that no custom handlings that emit vector / fp instructions are reached.

Soft-float fails with calls to non-existing library functions it seems, including calls to the conversion functions we are now using, except with args in GPRs instead.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 34]
```diff
@@ -6470,6 +6540,84 @@ static SDValue lowerAddrSpaceCast(SDValue Op, SelectionDAG &DAG) {
...
+                                              SelectionDAG &DAG) const {
+  SDValue In = Op.getOperand(Op->isStrictFPOpcode() ? 1 : 0);
+  if (In.getSimpleValueType() != MVT::f16)
+    return Op;      // Legal
+  return SDValue(); // Let legalizer emit the libcall.
+}
+
+// Shift the lower 2 bytes of Op to the left in order to insert into the
+// upper 2 bytes of the FP register.
+static SDValue convertToF16(SDValue Op, SelectionDAG &DAG) {
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6553]: Huh.  Now you've extracted these subroutines, but there's still only used in one place.  Wasn't the intent to use those for BITCAST in the no-vector case (this logic would still be preferable over an in-memory transfer).

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 29 above)
Comment (uweigand) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6939]: Agreed that we need to wrap the setXXXAction calls.  I still think it might be preferable to add an explicit `!useSoftFloat()` clause here, just for symmetry with the f128 case.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 35]
```diff
@@ -3830,6 +3876,14 @@ SDValue SystemZTargetLowering::lowerSELECT_CC(SDValue Op,
   ISD::CondCode CC = cast<CondCodeSDNode>(Op.getOperand(4))->get();
   SDLoc DL(Op);
 
+  // SELECT_CC involving f16 will not have the cmp-ops promoted by the
+  // legalizer, as it will be handled according to the type of the resulting
+  // value. Extend them here if needed.
```
Comment (uweigand) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:3881]: Huh, good catch.   Are there other operations where the f16 type only appears on the source side?

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp (hunk 34 above)
Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:6553]: ok, done.

File: llvm/lib/IR/RuntimeLibcalls.cpp (hunk 20 above)
Comment (tgross35) [reply llvm/lib/IR/RuntimeLibcalls.cpp:262]: This bit of code still seems unusual, did it get resolved now that compiler-rt has been updated for systemz?

**Comment by JonPsson1** [comment]
Found one intrinsic that isn't working for f16: 
- Isel fails:
%res = call i32 @llvm.s390.tdc.f16(half %x, i64 123)
LLVM ERROR: Cannot select: t9: i32 = SystemZISD::TDC t2, Constant:i64<123>

- The SystemZTDC pass seems to work with 'half', but no tests.

- The Clang testFPKind doesn't seem to work with _Float16.

I suppose all this could be handled as well with promotion to float in the backend, and allowing it in testFPKind()?

File: llvm/lib/IR/RuntimeLibcalls.cpp (hunk 20 above)
Comment (JonPsson1) [reply llvm/lib/IR/RuntimeLibcalls.cpp]: ah, right - it's enough to reset them in SystemZISelLowering.cpp. Patch updated. Thanks!

Comment (nikic) [reply llvm/lib/IR/RuntimeLibcalls.cpp]: Since https://github.com/llvm/llvm-project/commit/cc539138acf742f53ef455147182a8de11980a02 these are the defaults, so you don't need to reset them at all.

**Comment by JonPsson1** [comment]
Patch rebased as the handling of libcalls had changed on main.

**Comment by phoebewang** [comment]
> * Added STRICT_FMINIMUM and STRICT_FMAXIMUM promotion in LegalizeDAG.cpp, which seems  to be simply unhandled currently. @RKSimon @phoebewang It seems that you added X86 operation actions for these (Promote) a while back ago, but without any tests. Does my patch to LegalizeDAG here look ok to you?

Thanks for the head up! The promotion LGTM, though I'd suggest to split it as a seperate patch since it's target independent.

**Comment by JonPsson1** [comment]
> > * Added STRICT_FMINIMUM and STRICT_FMAXIMUM promotion in LegalizeDAG.cpp, which seems  to be simply unhandled currently. @RKSimon @phoebewang It seems that you added X86 operation actions for these (Promote) a while back ago, but without any tests. Does my patch to LegalizeDAG here look ok to you?
> 
> Thanks for the head up! The promotion LGTM, though I'd suggest to split it as a seperate patch since it's target independent.

I thought about that, but it would be hard to do as there is no test case on SystemZ for it until all of this lands. Maybe you could pre-commit an X86 test case so that I could post a separate review with the promotion. Alternatively, you could just take what I did as well and commit it along with your test case. @phoebewang

**Comment by phoebewang** [comment]
> > > * Added STRICT_FMINIMUM and STRICT_FMAXIMUM promotion in LegalizeDAG.cpp, which seems  to be simply unhandled currently. @RKSimon @phoebewang It seems that you added X86 operation actions for these (Promote) a while back ago, but without any tests. Does my patch to LegalizeDAG here look ok to you?
> > 
> > 
> > Thanks for the head up! The promotion LGTM, though I'd suggest to split it as a seperate patch since it's target independent.
> 
> I thought about that, but it would be hard to do as there is no test case on SystemZ for it until all of this lands. Maybe you could pre-commit an X86 test case so that I could post a separate review with the promotion. Alternatively, you could just take what I did as well and commit it along with your test case. @phoebewang

Alright, I tried but it failed due we don't support expand STRICT_FMINIMUM/STRICT_FMAXIMUM. So let's keep it in SystemZ for now.

**Comment by JonPsson1** [comment]
> > > > * Added STRICT_FMINIMUM and STRICT_FMAXIMUM promotion in LegalizeDAG.cpp, which seems  to be simply unhandled currently. @RKSimon @phoebewang It seems that you added X86 operation actions for these (Promote) a while back ago, but without any tests. Does my patch to LegalizeDAG here look ok to you?
> > > 
> > > 
> > > Thanks for the head up! The promotion LGTM, though I'd suggest to split it as a seperate patch since it's target independent.
> > 
> > 
> > I thought about that, but it would be hard to do as there is no test case on SystemZ for it until all of this lands. Maybe you could pre-commit an X86 test case so that I could post a separate review with the promotion. Alternatively, you could just take what I did as well and commit it along with your test case. @phoebewang
> 
> Alright, I tried but it failed due we don't support expand STRICT_FMINIMUM/STRICT_FMAXIMUM. So let's keep it in SystemZ for now.

I don't understand - I see this in X86ISelLowering.cpp:
```

    setOperationAction(ISD::STRICT_FMINIMUM, MVT::f16, Promote);
    setOperationAction(ISD::STRICT_FMAXIMUM, MVT::f16, Promote);
```
@phoebewang

**Comment by phoebewang** [comment]
> > > > > * Added STRICT_FMINIMUM and STRICT_FMAXIMUM promotion in LegalizeDAG.cpp, which seems  to be simply unhandled currently. @RKSimon @phoebewang It seems that you added X86 operation actions for these (Promote) a while back ago, but without any tests. Does my patch to LegalizeDAG here look ok to you?
> > > > 
> > > > 
> > > > Thanks for the head up! The promotion LGTM, though I'd suggest to split it as a seperate patch since it's target independent.
> > > 
> > > 
> > > I thought about that, but it would be hard to do as there is no test case on SystemZ for it until all of this lands. Maybe you could pre-commit an X86 test case so that I could post a separate review with the promotion. Alternatively, you could just take what I did as well and commit it along with your test case. @phoebewang
> > 
> > 
> > Alright, I tried but it failed due we don't support expand STRICT_FMINIMUM/STRICT_FMAXIMUM. So let's keep it in SystemZ for now.
> 
> I don't understand - I see this in X86ISelLowering.cpp:
> 
> ```
> 
>     setOperationAction(ISD::STRICT_FMINIMUM, MVT::f16, Promote);
>     setOperationAction(ISD::STRICT_FMAXIMUM, MVT::f16, Promote);
> ```
> 
> @phoebewang

Sorry, I meant the F32 is default to expand. It failed after FP16 promoted to F32.

**Comment by JonPsson1** [comment]
> Sorry, I meant the F32 is default to expand. It failed after FP16 promoted to F32.

oh - I see.

**Comment by JonPsson1** [comment]
- Promotion of STRICT_FMAXIMUM LGT @phoebewang (and also ok to commit here - see above).

- Tests added: 
fmuladd-soft-float.ll: (failing) new test in file for f16 looks wrong as the conversion functions use the FP ABI, but now they are called with integer arguments. The same problem in other similar tests. Not sure what to think as there really is no soft-float library so these tests will never run anyway...

fp-mul-15.ll: Test that fmul;fadd does not result in multiply-and-add (passing).

- Status of conversion functions:

With clang --rtlib=libgcc, everything seems fine when extending f16 to float, double and f128. The result seems to be correct with a small program.

With clang --rtlib=compiler-rt, only extension to float has a libfunction, the other two are missing. Moreover, it seems that wrong code is resulting when using this:

test.c:

```
float __attribute__((noinline)) fun2(_Float16 Op0, _Float16 Op1) {
  return ((float) Op0) + ((float) Op1);
}

int main() {
  _Float16 A = 1.5;
  _Float16 B = 0.5;
  float F32Res = fun2(A, B);
  _Float16 Res = ((_Float16) F32Res);
  return Res < 1.0 ? 11 : 3;
}
```

```
clang -target s390x-linux-gnu -march=z16 ./test4.c -O3 -o ./a.out --rtlib=compiler-rt; ./a.out; echo $?                                 
11

clang -target s390x-linux-gnu -march=z16 ./test4.c -O3 -o ./a.out --rtlib=libgcc; ./a.out; echo $?
3
```

The assembly is ofc identical, so I wonder what could be wrong with the compiler-rt conversion function...

For the missing libfunctions, I see these files in compiler-rt/lib/builtins:
```
compiler-rt/lib/builtins/extendhfsf2.c
compiler-rt/lib/builtins/extendhftf2.c
compiler-rt/lib/builtins/extendhfxf2.c
```

For double, I get
undefined reference to `__extendhfdf2' from clang, and in extendhfxf2.c the function seems to be called '__extendhfxf2' instead. Should a wrapper be added for the gcc compatible name whis is emitted?

For f128, I get undefined reference to `__extendhftf2'. My guess is that CRT_HAS_TF_MODE needs to be defined, which is done in compiler-rt/lib/builtins/int_types.h, but I am not quite sure how to do it. Would anybody know the preferred way?

For truncations, there seems to be a __truncdfhf2 but not __trunctfhf2...

**Comment by tgross35** [comment]
> For double, I get undefined reference to `__extendhfdf2' from clang, and in extendhfxf2.c the function seems to be called '__extendhfxf2' instead. Should a wrapper be added for the gcc compatible name whis is emitted?

xf refers to the x87 80-bit long double, f128 should always use tf (except ppc which is kf).

**Comment by JonPsson1** [comment]
> > For double, I get undefined reference to `__extendhfdf2' from clang, and in extendhfxf2.c the function seems to be called '__extendhfxf2' instead. Should a wrapper be added for the gcc compatible name whis is emitted?
> 
> xf refers to the x87 80-bit long double, f128 should always use tf (except ppc which is kf). Afaik `xf` is not a general alias for `long double` so I think you don't need to build that one on s390x.

I don't understand why I am seeing 
```
#elif defined DST_DOUBLE
typedef double dst_t;

```
in fp_extend.h, and then 

```
#define SRC_HALF
#define DST_DOUBLE
#include "fp_extend_impl.inc"

// Long double are expected to be as precise as double.
COMPILER_RT_ABI xf_float __extendhfxf2(src_t a) {
  return (xf_float)__extendXfYf2__(a);
}
```
in extendhfxf2.c. dst_t is double and it becomes 80-bit on x87, how do other target get f64 for double (and in what file?).

**Comment by tgross35** [comment]
Is it using the f16 -> f64 softfloat routine and then implicitly promoting to to `long double` f80?

**Comment by JonPsson1** [comment]
I see

```
// The source type may use a usual IEEE-754 interchange format or Intel 80-bit
// format. In particular, for the source type srcSigFracBits may be not equal to
// srcSigBits. The destination type is assumed to be one of IEEE-754 standard
// types.
static __inline dst_t __extendXfYf2__(src_t a) {
```
So with SRC_HALF and DST_DOUBLE, it actually seems to be a IEEE f16 -> f64 conversion..?

**Comment by tgross35** [comment]
I think that would make sense. From a quick test it looks like LLVM might prefer extending to f32 with the libcall and then using hardware to extend to f64 https://rust.godbolt.org/z/hexKcx9j5, so maybe it doesn't actually use or provide extendhfdf even though GCC has it? It probably should in the softfloat cases though, doing two libcalls for f16->f32->f64 doesn't make sense.

Also I checked and libgcc.a indeed doesn't have any `xf` routines on s390x, the object files exist but they are empty.

**Comment by tgross35** [comment]
I think something like the following precedence would make sense for all targets:

1. Direct asm: Lower to assembly if hardware support is available
2. Indirect mixed: libcall f16->f32 then asm the second conversion (f32->f64 or f32->f128) if hardware is available. The advantage is only linking one libcall (extendhfsf)
3. Direct libcall: If f32->f64 or f32->f128 are not hardware supported, use extendhfsf, extendhfdf, or extendhftf to lower f16->f32, f16->f64, a f16->f128
4. Indirect libcalls: this is LLVM's current behavior without hard float, i.e. libcall f16->f32 and then libcall again for f32->f64 or f32->f128

Option 2 is probably best here. Does s390x have `+soft-float` or any features that toggle the availability of float conversion ops? In these cases I think option 3 is preferable to option 4. (Although since the other targets seem to fall back to option 4, maybe this something that could be fixed globally?)

**Comment by tgross35** [comment]
Looks like GCC uses option 3 https://gcc.godbolt.org/z/fM1EbK6Mn.

If you only need something to test against locally, I was able to get our s390x rust dist built against your patches https://github.com/rust-lang-ci/rust/actions/runs/13668570835. `rust-std-s390x-unknown-linux-gnu/lib/rustlib/s390x-unknown-linux-gnu/lib/libcompiler_builtins-77321e818a95f60c.rlib` has all six conversion symbols, though I haven't been able to test their correctness on the platform.

**Comment by uweigand** [comment]
I think that compiler-rt should provide all six conversion routines (f16<->f32, f16<->f64, f16<->f128), simply because libgcc has them and GCC-generated code will use them, and compiler-rt is supposed to be usable as drop-in replacement.

Also, I think LLVM should ideally generate calls to all those six routines, like GCC does.  Not only is this probably the most efficient (the f16<->f32 and f16<->f64 routines should be pretty much equal in performance), but more importantly, in the truncate case, using only a single truncation is more exact due to avoiding double-rounding effects.

**Comment by JonPsson1** [comment]
>  Does s390x have +soft-float or any features that toggle the availability of float conversion ops?

Yes, we support soft-float, and as I wrote earlier I am worried what happens with soft-float and conversion functions. I saw that with soft-float, the same conversion functions are called, but with args in integer registers, while with hard-float they go in fp-registers. For that to work, there would have to be another library with the same functions but with the soft-float abi. I am not sure if compiler-rt could be built for soft-float, but perhaps the gcc lib has them, in which case it seem reasonable to allow that ABI change in the tests. The user just has to provide a soft-float library for the conversion functions as well.

I guess we should provide all six conversion functions (for hard float) then, per your comments.

**Comment by uweigand** [comment]
To clarify about soft-float - we do support `-msoft-float` as a compiler option, but there is no actual soft-float library provided anywhere; never has been.  The compiler option is still useful in particular for the case of the Linux kernel: kernel code does not actually have any floating-point operations or even data types at the C source level, but the compiler would normally still be free to use floating-point instruction and registers (or even vector instruction and registers).  This would conflict with the fact that the kernel does not save / restore floating-point or vector registers at system call (or interrupt) entry or exit.  Therefore, the kernel uses `-msoft-float` to indicate to the compiler to never touch any floating-point or vector register in generated code.   Because the kernel does not use floating-point operations at the source level, the compiler can achieve this goal without ever emitting any call to a soft-float library routine.

There is no user-space code that uses `-msoft-float` on SystemZ, and that wouldn't really make sense anyway - every SystemZ hardware in existence has full support for floating-point operations natively (IEEE-32, -64, and -128).

To bring this back to the original topic of floating-point support in the compiler runtime libraries: there are a small number of such routines today, but those are not intended for use with soft-float (they do expect the normal hard-float ABI, i.e. passing floating-point values in floating-point registers), but rather implement a few corner-case operations (like int128 <-> float conversion) where we actually do not have hardware instructions.   Any new f16-related compiler runtime library routine would fall into this category, *not* the soft-float category.

**Comment by uweigand** [comment]
> For the missing libfunctions, I see these files in compiler-rt/lib/builtins:
> 
> ```
> compiler-rt/lib/builtins/extendhfsf2.c
> compiler-rt/lib/builtins/extendhftf2.c
> compiler-rt/lib/builtins/extendhfxf2.c
> ```
> 
> For double, I get undefined reference to `__extendhfdf2' from clang, and in extendhfxf2.c the function seems to be called '__extendhfxf2' instead. Should a wrapper be added for the gcc compatible name whis is emitted?

No, XF is a different mode from DF.  There should be a file `extendhfdf2.c` analogous to the others, but using 
```
#define SRC_HALF
#define DST_DOUBLE
```
This seems to be missing currently.

> For f128, I get undefined reference to `__extendhftf2'. My guess is that CRT_HAS_TF_MODE needs to be defined, which is done in compiler-rt/lib/builtins/int_types.h, but I am not quite sure how to do it. Would anybody know the preferred way?

This should be defined by the existing logic in `int_types.h` as far as I can see.   We have
```
#if defined(CRT_HAS_128BIT) && defined(CRT_HAS_F128)
#define CRT_HAS_TF_MODE
#endif
```
and both conditions should be true on s390x.   On the one hand, we have
```
#if defined(__LP64__) || defined(__wasm__) || defined(__mips64) ||             \
    defined(__SIZEOF_INT128__) || defined(_WIN64)
#define CRT_HAS_128BIT
#endif
```
and we should be defining `__LP64__`. 

On the other hand, we have
```
#elif __LDBL_MANT_DIG__ == 113 ||                                              \
    (__FLT_RADIX__ == 16 && __LDBL_MANT_DIG__ == 28)
// Use long double instead of __float128 if it matches the IEEE 128-bit format
// or the IBM hexadecimal format.
#define CRT_LDBL_128BIT
#define CRT_HAS_F128
```
and we should match the `__LBDL_MANT_DIG__ == 113` condition.

So this should already work.  If it doesn't, you'll have to debug the build process here (e.g. look at preprocessed output to see what's actually going on here).
 
> For truncations, there seems to be a __truncdfhf2 but not __trunctfhf2...

I'm pretty sure that would be the same `CRT_HAS_TF_MODE` problem then.

> If there isn't any reason to be consistent with the other LLVM targets then agreed, using the direct libcalls seems better. The new library support could likely land separately, right? As long as the lowering is correct, considering this PR is already pretty expansive.

Sure, that probably should land separately.   I'd still like to at least have an implementation ahead of time just so we can properly test the LLVM back-end support ...

> There isn't actually a softfloat 390x target currently but this will need to be added at some point for RfL support (it's trivial).

Thanks for pointing this out.  I agree, we need that target for s390x then as well.  (And probably soon - the kernel folks are already trying to enable Rust for Linux on s390x.)

**Comment by uweigand** [comment]
> So this should already work. If it doesn't, you'll have to debug the build process here (e.g. look at preprocessed output to see what's actually going on here).

Ah, sorry, now I see what's going on.  In this line you added to the cmake logic:
```
set(s390x_SOURCES ${GENERIC_SOURCES})
```
you need to add `${GENERIC_TF_SOURCES}` as well, otherwise all the TF files won't get built at all.

**Comment by JonPsson1** [comment]
Thanks for the help.

- new file extendhfdf2.c (and added to GENERIC_SOURCES list)
- $GENERIC_TF_SOURCES added to s390x_SOURCES.  This did not work immediately. However, if I removed the check for COMPILER_RT_HAS_FLOAT16 in the source files, it builds. Not sure why/if that is needed there (there is no check for it in e.g. extendhfdf2.c), or how it could be set.

Still problem with wrong-code: All conversions gave wrong-code when building compiler-rt with gcc, but when bootstrapping it (by using -DLLVM_ENABLE_RUNTIMES=compiler-rt), now only the double case fails. The clang assembly files are identical, but the libfunctions are different when I compared with libgcc (correct output) and compiler-rt. I stepped through my small program in gdb and found that as expected when returning from libgcc after the first extension, the register holds 1.5. When doing the same from compiler-rt it doesn't have the correct value. I checked that the ABI is correct at least - first instruction is moving f0 to r0, which seems right. At this point I wouldn't know what to look for to debug it further.

My test program:

```
#define T2 double

T2 __attribute__((noinline)) fun2(T2 Op0, T2 Op1) {
  return Op0 + Op1;
}

volatile _Float16 A;
volatile _Float16 B;
int main() {
  A = 1.5;
  B = 0.5;
  T2 Res2 = fun2(((T2) A), ((T2) B));
  _Float16 Res = ((_Float16) Res2);
  return Res < 1.0 ? 11 : 3;   // Res = 2.0 => return 3  
}

```
```
rm a.out test4.s; ./bin/clang -target s390x-linux-gnu -march=z16 ./test4.c -O3 -o ./a.out --rtlib=libgcc -save-temps ; ./a.out; echo $?
3

rm a.out test4.s; ./bin/clang -target s390x-linux-gnu -march=z16 ../build/test4.c -O3 -o ./a.out --rtlib=compiler-rt -save-temps ; ./a.out; echo $?                         
11
```

**Comment by tgross35** [comment]
To clarify, the code is calling `__extendhfdf2` then `__truncdfhf2` from either libgcc or from compiler-rt with your patches, and the compiler-rt version is incorrect? Could you have it print the intermediate results as u16 hex (`Op0 + Op1`, `Res2`, `Res`)?

Not sure if you are testing only on s390x but there should probably be a unit test at https://github.com/llvm/llvm-project/tree/d90423e310482bdbc731242fa25dcb3dd44e69de/compiler-rt/test/builtins/Unit to see if things work on other platforms.

**Comment by JonPsson1** [comment]
> To clarify, the code is calling `__extendhfdf2` then `__truncdfhf2` from either libgcc or from compiler-rt with your patches, and the compiler-rt version is incorrect? Could you have it print the intermediate results as u16 hex (`Op0 + Op1`, `Res2`, `Res`)?

Yes, my test program is calling either libgcc or compiler-rt implementaions of the same function. Yes, on this branch.

```
                                      libgcc                    compiler-rt

vlreph  %v0, 0(%r1)                   0x3e00             (1.5)  0x3e00
brasl   %r14, __extendhfdf2@PLT       0x3ff8000000000000        0x3fc0000000000000
ldr     %f8, %f0
vlreph  %v0, 0(%r13)                  0x3800             (0.5)  0x3800
brasl   %r14, __extendhfdf2@PLT       0x3fe0000000000000        0x3f00000000000000
ldr     %f2, %f0
ldr     %f0, %f8
brasl   %r14, fun2@PLT                0x4000000000000000 (2.0)  0x3fc0010000000000
brasl   %r14, __truncdfhf2@PLT        0x4000                    0x3000
brasl   %r14, __extendhfsf2@PLT       0x40000000                0x3e000000

```

> Not sure if you are testing only on s390x but there should probably be a unit test at https://github.com/llvm/llvm-project/tree/d90423e310482bdbc731242fa25dcb3dd44e69de/compiler-rt/test/builtins/Unit to see if things work on other platforms.

I am testing on s390x, and I guess it's unfortunate that there is no such test for hfdf - this is the file that was missing and that I added. I guess it should be added once it is confirmed to work properly (or if someone would provide the right values). The tests that are already there have been passing always while working on this, even when building with gcc.

**Comment by tgross35** [comment]
Nothing about the implementation stands out to me as wrong. It looks like the exponent isn't correct, I guess you could step through this portion https://github.com/llvm/llvm-project/blob/ae42f071032b29821beef6a33771258086bbbb1c/compiler-rt/lib/builtins/fp_extend_impl.inc#L65-L66 and double check the intermediate values? Our implementation is doing something similar except it adds in place rather than shifting back and forth, but I don't know why that would make a difference https://github.com/rust-lang/compiler-builtins/blob/7bec089672eb5cd83d7902edd59479527bc9d8d1/src/float/extend.rs#L42-L45.

**Comment by uweigand** [comment]
> * However, if I removed the check for COMPILER_RT_HAS_FLOAT16 in the source files, it builds. Not sure why/if that is needed there (there is no check for it in e.g. extendhfdf2.c), or how it could be set.

This is set if the host compiler used to build compiler-rt supports the `_Float16` type, see this in `compiler-rt/lib/builtins/CMakeLists.txt`:
```
      check_c_source_compiles("_Float16 foo(_Float16 x) { return x; }
                               int main(void) { return 0; }"
                              COMPILER_RT_HAS_${arch}_FLOAT16)
```

If this is not set, you need to figure out why it is not using the correct host compiler.  I think it should be using the clang built from the same sources, which *should* now support `_Float16` - if it doesn't, this may cause other problems, potentially even explaining the wrong results you're seeing.

File: compiler-rt/lib/builtins/extendhfdf2.c [hunk 36]
```diff
@@ -0,0 +1,27 @@
...
+#define DST_DOUBLE
+#include "fp_extend_impl.inc"
+
+// Use a forwarding definition and noinline to implement a poor man's alias,
+// as there isn't a good cross-platform way of defining one.
+COMPILER_RT_ABI NOINLINE float __extendhfdf2(src_t a) {
+  return __extendXfYf2__(a);
+}
+
+COMPILER_RT_ABI float __gnu_h2d_ieee(src_t a) { return __extendhfdf2(a); }
```
Comment (uweigand) [inline compiler-rt/lib/builtins/extendhfdf2.c:19]: I don't think you should define the `__gnu_h2d_ieee` or the `__aeabi_h2d` names here - those are not defined by the ARM standard or by other compilers today.  This function should *only* be present under the `__extendhfdf2` name.

Comment (JonPsson1) [reply compiler-rt/lib/builtins/extendhfdf2.c]: ok - removed.

**Comment by JonPsson1** [comment]
> 
> If this is not set, you need to figure out why it is not using the correct host compiler. I think it should be using the clang built from the same sources, which _should_ now support `_Float16` - if it doesn't, this may cause other problems, potentially even explaining the wrong results you're seeing.

It seems that with a completely new build with the new cmake config the test actually passes:
  
```
-- Performing Test COMPILER_RT_HAS_s390x_FLOAT16
-- Performing Test COMPILER_RT_HAS_s390x_FLOAT16 - Success
```

I previously got confused here after rerunning cmake in the same folder as I thought it was enough to see the newly built clang being used (ninja -v) with compiler-rt. It seems maybe cmake itself got confused and used system gcc for its checks while building with clang? Anyway, it works now, sorry.

I also found the problem with the miscompile (after some debugging, sigh), that the file I copied (extendhfsf.c) has float hard coded as return type, even though it defines DST_SINGLE. extendhftf2.c uses dst_t as return type, but I see other files using the type directly, so I will leave those files and extendhftf2.c as they were. I guess I have a motivating case to use dst_t and src_t everywhere, but that's another issue. So the miscompile was due to a final conversion from double to float before returning. My bad.

While adding the corresponding (to extendsfdf2_test.c) test I tried inserting an obvious error, but this did not cause it to fail, not even with ninja check-all, which I thought covered all tests (ninja check-compiler-rt did not report it either). How can I run these tests?

I tried building (same way as before) and running the existing extendhfsf2_test.c but got:

`error in test__extendhfsf2(0x7e00) = 0.000000, expected nan`

This was unexpected, and I get the same error with libgcc.

> By the way, these sites are pretty helpful for double checking float reprs https://float.exposed https://weitz.de/ieee/.

I tried float.exposed but I couldn't really convert an f16 hex to a double hex. Is it supposed to be able to do this?

**Comment by tgross35** [comment]
> > By the way, these sites are pretty helpful for double checking float reprs https://float.exposed https://weitz.de/ieee/.
> 
> I tried float.exposed but I couldn't really convert an f16 hex to a double hex. Is it supposed to be able to do this?

It should, on the `half` page you can paste the int repr into "Raw Hexadecimal Integer Value", then click `float` or `double` at the top. I don't use it too much for that though, mostly exploding into sign/exponent/mantissa when debugging soft floats.

**Comment by JonPsson1** [comment]
-- A few more tests added covering 
alloca
access into aggregate type with half elements with getelementptr.
atomicrmw

Would a test for { half, half, half, half } in Swift-return.ll make sense?

I think testing coverage now is fairly ok - can't think of any more instructions to handle although not all various combinations and uses of them have been duplicated from float (Test for the new extendhfdf2.cpp function is still todo).

-- Manged to build and run lbm with _Float16 by simply changing the element type o  LBM_Grid from double to _Float16. It ran without crashing, although 4x quicker which I guess/hope is due to some value check that stops execution somewhere. I confirmed   that the executable indeed contains a lot of conversion calls and vlreph and more.

-- Another try to activate the tests for the builtins, but so far no luck. In compiler-rt/test/builtins/CMakeLists.txt, the librt_has_XXX list is built, but I tried

```
diff --git a/compiler-rt/test/builtins/Unit/extendhfsf2_test.c b/compiler-rt/test/builtins/Unit/extendhfsf2_test.c
index 86150e8fb0d7..c85188e76ed3 100644
--- a/compiler-rt/test/builtins/Unit/extendhfsf2_test.c
+++ b/compiler-rt/test/builtins/Unit/extendhfsf2_test.c
@@ -1,5 +1,5 @@
 // RUN: %clang_builtins %s %librt -o %t && %run %t
-// REQUIRES: librt_has_extendhfsf2
+
 
 #include <stdio.h>
 
@@ -12,7 +12,7 @@ int test__extendhfsf2(TYPE_FP16 a, uint32_t expected)
     float x = __extendhfsf2(a);
     int ret = compareResultF(x, expected);
 
-    if (ret){
+    if (true){
         printf("error in test__extendhfsf2(%#.4x) = %f, "
                "expected %f\n", toRep16(a), x, fromRep32(expected));
     }

ninja check-all
```
but no failure...

**Comment by JonPsson1** [comment]
@Meinersbur @petrhosek @smeenai @danliew-apple 

Reaching out here to some people who seem to have been working with this CMake file: Would you have any idea how I could activate and run the compiler-rt tests for s390x (see above for my unsuccessful experiments)? Thanks.

**Comment by JonPsson1** [comment]
Thanks to @boomanaiden154 for pointing out that I need to pass -DCOMPILER_RT_BUILD_BUILTINS=ON to cmake - the tests now builds and runs.

The test for half->double conversions added, with the 64-bit hex values taken from the compiler-rt conversion function results (should be correct, right :). Wanted to use the makeXXX16() functions as much as possible, but not sure what to pass to makeQNaN16(uint16_t rand), so left that as it was, which also should be fine, I suppose.

**Comment by JonPsson1** [comment]
Have nothing more to do for this now, so waiting for review.

File: llvm/lib/Target/SystemZ/SystemZISelLowering.cpp [hunk 37]
```diff
@@ -548,11 +543,28 @@ SystemZTargetLowering::SystemZTargetLowering(const TargetMachine &TM,
   }
 
   // Handle floating-point types.
+  if (!useSoftFloat()) {
+    // Promote all f16 operations to float, with some exceptions below.
+    for (unsigned Opc = 0; Opc < ISD::BUILTIN_OP_END; ++Opc)
+      setOperationAction(Opc, MVT::f16, Promote);
```
Comment (nikic) [inline llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:549]: I thought Promote for half types is broken and you need to use SoftPromoteHalf for correct rounding?

Comment (topperc) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:549]: SoftPromoteHalf is a type legalizer action not an OperationAction. Promote as an OperationAction should work for f16.

Comment (JonPsson1) [reply llvm/lib/Target/SystemZ/SystemZISelLowering.cpp:549]: Ah, I see. Yes, this should work then and are tested, see fp-half-move.ll.

**Comment by JonPsson1** [comment]
Patch rebased.

The reported formatting issue here is in the test which however was mostly copied from a pre-existing test, so maybe clang-format should be done on all these tests or not. Skipping it for now.

File: llvm/test/CodeGen/SystemZ/fp-abs-01.ll [hunk 38]
```diff
@@ -3,6 +3,17 @@
 ; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z10 | FileCheck %s
 ; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z13 | FileCheck %s
 
+; Test f16.
+declare half @llvm.fabs.f16(half %f)
+define half @f0(half %f) {
+; CHECK-LABEL: f0:
+; CHECK: brasl %r14, __extendhfsf2@PLT
+; CHECK: lpdfr %f0, %f0
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-abs-01.ll:11]: There should also be a truncsfhf2 here, right?   Probably best to use a CHECK-NEXT sequence.

File: llvm/test/CodeGen/SystemZ/fp-abs-03.ll [hunk 39]
```diff
@@ -2,6 +2,18 @@
...
 ; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z14 | FileCheck %s
 
+; Test f16.
+declare half @llvm.fabs.f16(half %f)
+define half @f0(half %f) {
+; CHECK-LABEL: f0:
+; CHECK: brasl %r14, __extendhfsf2@PLT
+; CHECK: lpdfr %f0, %f0
+; CHECK: brasl %r14, __truncsfhf2@PLT
+; CHECK: br %r14
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-abs-03.ll:12]: Here as well.

File: llvm/test/CodeGen/SystemZ/fp-conv-08.ll [hunk 40]
```diff
@@ -2,6 +2,15 @@
 ;
 ; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z10 | FileCheck %s
 
+; Test i64->f16. For z10, this results in just a single a libcall.
+define half @f0(i64 %i) {
+; CHECK-LABEL: f0:
+; CHECK: brasl %r14, __floatundihf@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-08.ll:8]: This libcall doesn't actually exist in our library, as far as I can see.  If we want to use it, we need to ensure that it is actually being built in both libgcc and compiler-rt.   Or else, we go via f32 like for the other conversions - that might be the more logical approach.

File: llvm/test/CodeGen/SystemZ/fp-conv-20.ll [hunk 41]
```diff
@@ -30,83 +30,119 @@ define float @f3(i128 %i) {
   ret float %conv
 }
 
-; Test unsigned i128->f128.
-define fp128 @f4(i128 %i) {
+; Test signed i128->f16.
+define half @f4(i128 %i) {
 ; CHECK-LABEL: f4:
+; CHECK: brasl %r14, __floattihf@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-20.ll:36]: Again, we don't have this function.

File: llvm/test/CodeGen/SystemZ/fp-conv-20.ll [hunk 42]
```diff
@@ -30,83 +30,119 @@ define float @f3(i128 %i) {
...
 ; CHECK: brasl %r14, __floatuntisf@PLT
 ; CHECK: br %r14
   %conv = uitofp i128 %i to float
   ret float %conv
 }
 
+; Test unsigned i128->f16.
+define half @f8(i128 %i) {
+; CHECK-LABEL: f8:
+; CHECK: brasl %r14, __floatuntihf@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-20.ll:72]: Or this.

File: llvm/test/CodeGen/SystemZ/fp-conv-20.ll [hunk 43]
```diff
@@ -30,83 +30,119 @@ define float @f3(i128 %i) {
...
 ; CHECK: brasl %r14, __fixsfti@PLT
 ; CHECK: br %r14
   %conv = fptosi float %f to i128
   ret i128 %conv
 }
 
+; Test signed f16->i128.
+define i128 @f12(half %f) {
+; CHECK-LABEL: f12:
+; CHECK: brasl %r14, __fixhfti@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-20.ll:108]: Or this.

File: llvm/test/CodeGen/SystemZ/fp-conv-20.ll [hunk 44]
```diff
@@ -30,83 +30,119 @@ define float @f3(i128 %i) {
...
 ; CHECK: brasl %r14, __fixunssfti@PLT
 ; CHECK: br %r14
   %conv = fptoui float %f to i128
   ret i128 %conv
 }
+
+; Test unsigned f16->i128.
+define i128 @f16(half %f) {
+; CHECK-LABEL: f16:
+; CHECK: brasl %r14, __fixunshfti@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-20.ll:144]: Or this.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll [hunk 45]
```diff
@@ -126,3 +138,23 @@ define void @f9(ptr %cptr, ptr %aptr, ptr %bptr) {
   store fp128 %c, ptr %cptr
   ret void
 }
+
+; Test f16 copies in which the sign comes from an f16.
+define half @f10(half %a, half %b) {
+; CHECK-LABEL: f10:
+; CHECK: brasl %r14, copysignh@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-copysign-01.ll:145]: This function doesn't exist - this should be handled either via extend/trunc, or else via bitops.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll [hunk 46]
```diff
@@ -126,3 +138,23 @@ define void @f9(ptr %cptr, ptr %aptr, ptr %bptr) {
...
+; CHECK: br %r14
+  %res = call half @copysignh(half %a, half %b) readnone
+  ret half %res
+}
+
+; Test f16 copies in which the sign comes from an f32.
+define half @f11(half %a, float %bf) {
+; CHECK-LABEL: f11:
+; CHECK: brasl %r14, __truncsfhf2@PLT
+; CHECK: brasl %r14, copysignh@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-copysign-01.ll:155]: Again, this doesn't exist.

File: llvm/test/CodeGen/SystemZ/fp-copysign-02.ll [hunk 47]
```diff
@@ -2,11 +2,25 @@
...
 declare double @copysign(double, double) readnone
 ; FIXME: not really the correct prototype for SystemZ.
 declare fp128 @copysignl(fp128, fp128) readnone
 
+; Test f16 copies in which the sign comes from an f128.
+define half @f0(half %a, ptr %bptr) {
+; CHECK-LABEL: f0:
+; CHECK: vl %v[[REG:[0-9]+]], 0(%r2)
+; CHECK: brasl %r14, __trunctfhf2@PLT
+; CHECK: brasl %r14, copysignh@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-copysign-02.ll:16]: Here as well.

File: llvm/test/CodeGen/SystemZ/fp-half-mem.ll [hunk 48]
```diff
@@ -0,0 +1,65 @@
...
+; NOVEC-NEXT:    stmg %r14, %r15, 112(%r15)
+; NOVEC-NEXT:    .cfi_offset %r14, -48
+; NOVEC-NEXT:    .cfi_offset %r15, -40
+; NOVEC-NEXT:    aghi %r15, -168
+; NOVEC-NEXT:    .cfi_def_cfa_offset 328
+; NOVEC-NEXT:    la %r2, 166(%r15)
+; NOVEC-NEXT:    brasl %r14, foo@PLT
+; NOVEC-NEXT:    lh %r0, 166(%r15)
+; NOVEC-NEXT:    sll %r0, 16
+; NOVEC-NEXT:    risbhg %r0, %r0, 0, 159, 32
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-half-mem.ll:22]: Those two instructions (sll, risbhg) could be combined into a single 48-bit sllg, right?  I see this in other places, but not here - I think this should always use the single instruction.

File: llvm/test/CodeGen/SystemZ/spill-half-01.mir [hunk 49]
```diff
@@ -0,0 +1,63 @@
...
+    ; CHECK-NEXT: #NO_APP
+    ; CHECK-NEXT: le %f0, 164(%r15)           # 4-byte Reload
+    ; CHECK:      le %f0, 168(%r15)           # 4-byte Reload
+    ; CHECK:      le %f0, 172(%r15)           # 4-byte Reload
+
+    ; VECTOR-LABEL: fun0:
+    ; VECTOR:      aghi %r15, -232
+    ; VECTOR:      vsteh %v4, 166(%r15), 0     # 2-byte Folded Spill
+    ; VECTOR-NEXT: vsteh %v2, 162(%r15), 0     # 2-byte Folded Spill
+    ; VECTOR-NEXT: vsteh %v0, 164(%r15), 0     # 2-byte Folded Spill
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/spill-half-01.mir:30]: Why does this still say "Folded Spill" instead of just "Spill"?   There's probably some new instructions that should be marked `SimpleBDXLoad` / `SimpleBDXStore`.

File: llvm/test/CodeGen/SystemZ/vec-max-05.ll [hunk 50]
```diff
@@ -87,6 +90,15 @@ define <2 x double> @f7(<2 x double> %dummy, <2 x double> %val1,
   ret <2 x double> %ret
 }
 
+; Test the fmaxh library function.
+define half @f11_half(half %dummy, half %val1, half %val2) {
+; CHECK-LABEL: f11_half:
+; CHECK: brasl %r14, fmaxh@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/vec-max-05.ll:96]: We don't have this library function.   This should either go via SF or expanded to a compare sequence.

File: llvm/test/CodeGen/SystemZ/vec-min-05.ll [hunk 51]
```diff
@@ -87,6 +90,15 @@ define <2 x double> @f7(<2 x double> %dummy, <2 x double> %val1,
   ret <2 x double> %ret
 }
 
+; Test the fminh library function.
+define half @f11_half(half %dummy, half %val1, half %val2) {
+; CHECK-LABEL: f11_half:
+; CHECK: %r14, fminh@PLT
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/vec-min-05.ll:96]: Same here.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll (hunk 45 above)
Comment (tgross35) [reply llvm/test/CodeGen/SystemZ/fp-copysign-01.ll:145]: I think `abs` and `copysign` are generally libcall-free, so that would be preferable here if possible.

Not related with that change but as a note, I don't think the `h` suffix exists for `math.h` routines. C23 does specify sized suffixes however, so e.g. `copysignf16` is valid and is provided by both [LLVM's `libc`](https://github.com/llvm/llvm-project/blob/749535ba2808e133682074f712ac6829335f8875/libc/src/math/generic/copysignf16.cpp#L16) and [Rust's builtins](https://docs.rs/compiler_builtins/latest/compiler_builtins/math/full_availability/fn.copysignf16.html).

File: llvm/test/CodeGen/SystemZ/fp-half-mem.ll (hunk 48 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/fp-half-mem.ll:22]: ok - better to convert via i64 since there is no 32-bit extraction/insertion instruction.

File: llvm/test/CodeGen/SystemZ/spill-half-01.mir (hunk 49 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/spill-half-01.mir:30]: Fixed.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll (hunk 45 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/fp-copysign-01.ll:145]: I have come to realize that these tests actually shouldn't involve copysignh at all, as here *libcalls* are tested.

On the other hand, if I compile a C program with copysign() using _Float16, Clang emits calls to the *intrinsic*:

```
 %0 = load half, ptr %v0, align 2, !tbaa !4
  %conv = fpext half %0 to double
  %1 = load half, ptr %v1, align 2, !tbaa !4
  %conv2 = fpext half %1 to double
  %2 = call double @llvm.copysign.f64(double %conv, double %conv2)
```
 
However the DAGCombiner will remove FPEXTs of the operands, so the backend still has to handle FCOPYSIGNs with one or two half operands (the ISD::FCOPYSIGN node can have the second argument of a different type). 

This is now implemented in lowerFCOPYSIGN() and tested in fp-copysign-03.ll.

File: llvm/test/CodeGen/SystemZ/vec-max-05.ll (hunk 50 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/vec-max-05.ll:96]: Removed.
A C program results in a call to the @llvm.maxnum.f16 intrinsic, which there is a test for.

File: llvm/test/CodeGen/SystemZ/vec-min-05.ll (hunk 51 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/vec-min-05.ll:96]: same as with fmax.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll (hunk 45 above)
Comment (tgross35) [reply llvm/test/CodeGen/SystemZ/fp-copysign-01.ll:145]: This is kind of a weird test, is it meant to ensure that LLVM can recognize calls to `libm` functions and replace them with assembly lowerings if that is more optimal? If that is the goal then `copysignh` doesn't seem to be doing anything and maybe it should be a FIXME (it should be `copysignf16` anyway). If that isn't the goal then I don't know why the other tests aren't calling `@llvm.copysign.f32` and similar.

**Comment by JonPsson1** [comment]
Updated per review.

- Custom handlings added to deal with non-existing library functions:

FP_TO_INT: 

Z10 unsigned: 
Expanding fp-> i32/i64 seems to work best to do without first doing the custom extension to f32 in the f16 input case. TargetLowering::expandFP_TO_UINT() can then
look at the types and convert to fp_to_sint and avoid the longer sequence used for float.

For i128 which is not a legal type so this needs to be handled similarly in LowerOperationWrapper() instead.

Unfortunately it is not possible to return and select "Expand or LibCall", so for the i128 case it seems to be necessary to emit the libcall using the makeLibCall() method.

Moved the comment  "Promoting the result to i64...so use the default expansion" that was present in SystemZISelLowering.cpp into this method, but don't quite understand it fully. Is this talking about promoting to signed i64?

INT_TO_FP:

Z10 unsigned:
 Inlined the Promotion of i32 via f32.
 i64 first gets done on f32, and then expanded.

- FCOPYSIGN: test for non-existing library function removed, but handling remains for
  the intrinsic that is used.

- load/store/bitcast of f16 now done via i64 instead to do the shift with a single instruction.

- commenting issue fixed by adding SimpleBDXLoad / SimpleBDXStore bits to instructions.

File: llvm/test/CodeGen/SystemZ/fp-copysign-01.ll (hunk 45 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/fp-copysign-01.ll]: Sorry for the confusion - I commented a bit too early, but now I have pushed my changes as well after some final changes.

**Comment by uweigand** [comment]
> Moved the comment "Promoting the result to i64...so use the default expansion" that was present in SystemZISelLowering.cpp into this method, but don't quite understand it fully. Is this talking about promoting to signed i64?

This is about whether we can (and should) implement a fp->u32 conversion via fp->s64->u32.   If the input is in the valid range for an u32, this will always result in the correct output.  However, the question is what happens if the input is *outside* that range.  The z196 instruction follows the IEEE rules and will generate an invalid operation exception, and I think we intended to match that semantics with the expanded code for z10.  The fp->s64->u32 expansion would not generate an invalid operation exception if the input value is inside the s64 but outside the u32 range, that's why we chose not to use it.

However, now that I'm looking at it again, this decision seems questionable for at least two reasons:
- the LLVM IR explicitly marks that case as undefined: "The `fptoui` instruction converts its floating-point operand into the nearest (rounding towards zero) unsigned integer value. If the value cannot fit in ty2, the result is a poison value."
- even the more complex expansion still doesn't always signal invalid operation (it does for values > UINT_MAX, but not for (all) negative values)

Maybe we should re-think this, but then again z10 doesn't really matter anymore at this point, so it probably doesn't make much sense to change codegen now ...

> FP_TO_INT:
> 
> Z10 unsigned: Expanding fp-> i32/i64 seems to work best to do without first doing the custom extension to f32 in the f16 input case. TargetLowering::expandFP_TO_UINT() can then look at the types and convert to fp_to_sint and avoid the longer sequence used for float.

Right, that makes sense (there is again the question of out-of-range inputs, but given the above discussion, I think this fine).

> For i128 which is not a legal type so this needs to be handled similarly in LowerOperationWrapper() instead.

I see that the LowerOperationWrapper still emits i128 operations.  (E.g. you expand a f16->i128 into a f16->f32 and f32->i128)   But that routine is called because of the illegal input type i128, so I understand it must not leave any operations with the illegal type; rather, it should complete the expansion fully.   This is annoying since for legal i128 we do the expansion in LowerOperation while for illegal i128 we do it in LowerOperationWrapper.   This was the same problem for the atomics, where I avoided code duplication by implementing the expansion in LowerOperationWrapper and then simply calling that routine from LowerOperation.

> Unfortunately it is not possible to return and select "Expand or LibCall", so for the i128 case it seems to be necessary to emit the libcall using the makeLibCall() method.

I see, this is unfortunate, but seems the only option.

> INT_TO_FP:
> 
> Z10 unsigned: Inlined the Promotion of i32 via f32. i64 first gets done on f32, and then expanded.

Why can't you still do the promotion via the Promote action for i32?   Then you wouldn't have to duplicate the common-code case ...
 
>     * FCOPYSIGN: test for non-existing library function removed, but handling remains for
>       the intrinsic that is used.

Ah, this implementation is quite inefficient.  There should be no extend/trunc libcalls needed at all: the sign bit in f16 is in the same place as f32 or f64, so the actual CPSDR instruction should simply work on f16 too.

File: llvm/test/CodeGen/SystemZ/fp-copysign-03.ll [hunk 52]
```diff
@@ -0,0 +1,65 @@
...
+
+; Test f16 copies.
+define half @f0(half %a, half %b) {
+; CHECK-LABEL: f0:
+; CHECK: brasl %r14, __extendhfsf2@PLT
+; CHECK: brasl %r14, __extendhfsf2@PLT
+; CHECK: cpsdr %f0, %f9, %f0
+; CHECK: brasl %r14, __truncsfhf2@PLT
+; CHECK: br %r14
+  %res = call half @llvm.copysign.f16(half %a, half %b)
```
Comment (tgross35) [inline llvm/test/CodeGen/SystemZ/fp-copysign-03.ll:17]: (Nonblocker) a few other architectures use an asm lowering to avoid the calls here, it's just `(a & !MASK) | (Y & MASK)` with `MASK = 1 << 15`.

File: llvm/test/CodeGen/SystemZ/fp-abs-01.ll [hunk 53]
```diff
@@ -3,6 +3,18 @@
...
 ; RUN: llc < %s -mtriple=s390x-linux-gnu -mcpu=z13 | FileCheck %s
 
+; Test f16.
+declare half @llvm.fabs.f16(half %f)
+define half @f0(half %f) {
+; CHECK-LABEL: f0:
+; CHECK:      brasl %r14, __extendhfsf2@PLT
+; CHECK-NEXT: lpdfr %f0, %f0
+; CHECK-NEXT: brasl %r14, __truncsfhf2@PLT
+; CHECK: br %r14
```
Comment (tgross35) [inline llvm/test/CodeGen/SystemZ/fp-abs-01.ll:13]: Similarly `fabs `could be `a & !SIGN_MASK`. It looks like aarch64 uses this, x86 still seems to extend then truncate for whatever reason.

**Comment by JonPsson1** [comment]
> This is about whether we can (and should) implement a fp->u32 conversion via fp->s64->u32.

Thanks for explaining - I updated the comment just a little bit so it is - at least to me - a bit easier to follow.

> I see that the LowerOperationWrapper still emits i128 operations. (E.g. you expand a f16->i128 into a f16->f32 and f32->i128) But that routine is called because of the illegal input type i128, so I understand it must not leave any operations with the illegal type; rather, it should complete the expansion fully.

My understanding is that the TypeLegalizer calls here for *all* i128 operands/results, even though generally it is doing most of the work. The target is allowed to do custom lowerings, but it doesn't have to. New nodes will be revisited if returned in Results.

> This is annoying since for legal i128 we do the expansion in LowerOperation while for illegal i128 we do it in LowerOperationWrapper..

I followed your example of calling LowerOperationWrapper instead to avoid the code duplication - looks better.

> Why can't you still do the promotion via the Promote action for i32? Then you wouldn't have to duplicate the common-code case

You are right, that is unnecessary. I must have gotten carried away with "extending all f16:s", not realizing that common code actually does this in this case.

> Ah, this implementation is quite inefficient. There should be no extend/trunc libcalls needed at all: the sign bit in f16 is in the same place as f32 or f64, so the actual CPSDR instruction should simply work on f16 too.

Added new opcodes for half per what was previously done for float and double. Special handling needed to remove the fpround for f128 as it would otherwise be lowered to a libcall. (The fpround for f128 could be removed for float and double as well, but there are currently no tests for this).

File: llvm/test/CodeGen/SystemZ/fp-copysign-03.ll (hunk 52 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/fp-copysign-03.ll]: fixed now by avoiding the conversions.

File: llvm/test/CodeGen/SystemZ/fp-abs-01.ll (hunk 53 above)
Comment (JonPsson1) [reply llvm/test/CodeGen/SystemZ/fp-abs-01.ll:13]: not sure if it would be worth doing a special lowering for this at this point..?

**Comment by uweigand** [comment]
> > I see that the LowerOperationWrapper still emits i128 operations. (E.g. you expand a f16->i128 into a f16->f32 and f32->i128) But that routine is called because of the illegal input type i128, so I understand it must not leave any operations with the illegal type; rather, it should complete the expansion fully.
> 
> My understanding is that the TypeLegalizer calls here for i128 operands/results for Custom operations, even though the target doesn't have to do anything. If Results is returned empty, TypeLegalizer will try to handle it. New nodes in Results on the other hand will be visited as well.
> 
> > This is annoying since for legal i128 we do the expansion in LowerOperation while for illegal i128 we do it in LowerOperationWrapper..
> 
> I followed your example of calling LowerOperationWrapper instead to avoid the code duplication - looks better.
> 

That's not quite what I was thinking.  You now call into LowerOperationWrapper for f16 always - but f16 is always legal so there shouldn't be a need to do that.  Instead, the type that is sometimes legal and sometimes not is i128 - so I would have thought the right way to call into LowerOperationWrapper for *i128* always.   (For example, when i128 is not legal, where is the libcall even emitted now?  LowerOperation shouldn't be called for legal types, and your current LowerOperationWrapper doesn't emit libcalls?)

> Added new opcodes for half per what was previously done for float and double. Special handling needed to remove the fpround for f128 as it would otherwise be lowered to a libcall. (The fpround for f128 could be removed for float and double as well, but there are currently no tests for this).

This seems to be more suitable for a DAGCombiner rule as it is really a performance optimization.   This could also be done as a separate patch (for all the types).

File: llvm/test/CodeGen/SystemZ/fp-conv-09.ll [hunk 54]
```diff
@@ -2,6 +2,16 @@
 ;
 ; RUN: llc < %s -mtriple=s390x-linux-gnu | FileCheck %s
 
+; Test f316->i32.
```
Comment (uweigand) [inline llvm/test/CodeGen/SystemZ/fp-conv-09.ll:5]: Comment typo.

**Review by uweigand — APPROVED** [review]
You might want to re-test after the recent merge of the z17 patch.   Otherwise, this now looks all good to me, a few further enhancement we discussed can be done as follow-on.  Thanks!

**Comment by JonPsson1** [comment]
- SchedModel for Z17 updated with the new opcodes for fp16 variants.

- fp-half.ll now gets an MVC instead of VL/VST which should be fine according to e071233 "Consider VST/VL as SimpleBDXStore/Load".
