### PR TITLE
[libc][POSIX][unistd] implement getsid

### LINKED ISSUE #126603: [libc][POSIX][unistd] implement getsid
Building llvm against llvm-libc fails with:
```
/llvm-project-main/llvm/lib/Support/LockFileManager.cpp:120:33: error: use of undeclared identifier 'getsid'
```
Looks like this is provided by unistd.h on POSIX systems.

### PR DESCRIPTION
**Pull request by ZakyHermawan**
Fixes https://github.com/llvm/llvm-project/issues/126603

### CODE REVIEW

File: libc/test/src/unistd/getsid_test.cpp [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+#include "src/errno/libc_errno.h"
+#include "src/unistd/getsid.h"
+#include "test/UnitTest/Test.h"
+
+TEST(LlvmLibcGetPidTest, GetCurrSID) {
+  pid_t sid = LIBC_NAMESPACE::getsid(0);
+  ASSERT_NE(sid, -1);
+  ASSERT_ERRNO_SUCCESS();
+}
```
Comment (michaelrj-google) [inline libc/test/src/unistd/getsid_test.cpp:17]: For syscall wrapper tests we prefer to have one test where the syscall succeeds and one where the syscall fails. It looks like this is just checking the succeeds case so far.

File: libc/src/unistd/linux/CMakeLists.txt [hunk 2]
```diff
@@ -235,6 +235,21 @@ add_entrypoint_object(
...
+add_entrypoint_object(
+  getsid
+  SRCS
+    getsid.cpp
+  HDRS
+    ../getsid.h
+  DEPENDS
+    libc.hdr.types.pid_t
+    libc.hdr.fcntl_macros
+    libc.include.unistd
```
Comment (michaelrj-google) [inline libc/src/unistd/linux/CMakeLists.txt:247]: these includes need to be cleaned up. This function doesn't use `fcntl_macros` or `<unistd.h>`.

**Review by michaelrj-google — COMMENTED** [review]
Thanks for this patch, it looks really good! There are some minor things to clean up, but after that this should be good to land. Thanks for contributing!

File: libc/test/src/unistd/getsid_test.cpp [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+#include "src/errno/libc_errno.h"
+#include "src/unistd/getsid.h"
+#include "test/UnitTest/Test.h"
+
+TEST(LlvmLibcGetPidTest, GetCurrSID) {
+  pid_t sid = LIBC_NAMESPACE::getsid(0);
+  ASSERT_NE(sid, -1);
+  ASSERT_ERRNO_SUCCESS();
+
+  pid_t nonexist_sid = LIBC_NAMESPACE::getsid(999999);
```
Comment (michaelrj-google) [inline libc/test/src/unistd/getsid_test.cpp:18]: I'd recommend using the sid `-1` since `999999` might theoretically be valid, which would cause flakey tests.

**Review by michaelrj-google — COMMENTED** [review]
just one more small tweak and it should be ready to land

**Comment by michaelrj-google** [comment]
LGTM, do you need me to merge this for you once the presubmits are done?

**Comment by ZakyHermawan** [comment]
yes, please

**Comment by michaelrj-google** [comment]
Presubmit failures are unrelated, tests pass on my system. Merging.

**Comment by jhuber6** [comment]
Ignore that ^
