### PR TITLE
[AArch64] Add MSVC mangling for the __mfp8 type

### LINKED ISSUE #124907: [clang-cl] arm_neon.h: cannot mangle built-in type __mfp8
On the `release/20.x` and `main` branches, when targeting ARM64 on clang-cl (`--target=aarch64-pc-windows-msvc --driver-mode=cl`):

https://gcc.godbolt.org/z/Mx1Y8hze4

```
In file included from <source>:1:
/opt/compiler-explorer/clang-trunk-20250129/lib/clang/20/include/arm_neon.h(41124,1): error: cannot mangle this built-in type:  __mfp8 yet
 41124 | __ai __attribute__((target("fp8,neon"))) bfloat16x8_t vcvt1_bf16_mf8_fpm(mfloat8x8_t __p0, fpm_t __p1) {
       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 41125 |   bfloat16x8_t __ret;
       |   ~~~~~~~~~~~~~~~~~~~
 41126 |   __ret = (bfloat16x8_t) __builtin_neon_vcvt1_bf16_mf8_fpm(__p0, __p1);
       |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 41127 |   return __ret;
       |   ~~~~~~~~~~~~~
 41128 | }
       | ~
/opt/compiler-explorer/clang-trunk-20250129/lib/clang/20/include/arm_neon.h(124,14): note: expanded from macro '__ai'
  124 | #define __ai static __inline__ __attribute__((__always_inline__, __nodebug__))
      |              ^
1 error generated.
```

Just including `<arm_neon.h>`  causes a compile error, due to the `__mfp8` type. This prevents compiling any Windows ARM64 code that includes the intrinsics header.

Can someone get this fixed before LLVM 20 release please?

### PR DESCRIPTION
**Pull request by momchil-velikov**
Fixes #124907

### CODE REVIEW

File: clang/lib/AST/MicrosoftMangle.cpp [hunk 1]
```diff
@@ -2808,6 +2812,7 @@ void MicrosoftCXXNameMangler::mangleType(const BuiltinType *T, Qualifiers,
 
 #define SVE_TYPE(Name, Id, SingletonId) \
   case BuiltinType::Id:
+#define SVE_SCALAR_TYPE(Name, MangledName, Id, SingletonId, Bits)
```
Comment (MacDue) [inline clang/lib/AST/MicrosoftMangle.cpp:2815]: Is there a reason why this can't be handled by defining `SVE_SCALAR_TYPE` to the the mangling? 
I was a little confused about what this empty define was doing at first.

```suggestion
#define SVE_SCALAR_TYPE(Name, MangledName, Id, SingletonId, Bits)  \
    mangleArtificialTagType(TagTypeKind::Struct, MangledName);     \
    break;
```
Also, is there anyone we can tag that knows about the Microsoft mangling? I'm not sure if there's any process needed for adding a new type.

**Review by sdesmalen-arm — APPROVED** [review]

File: clang/lib/AST/MicrosoftMangle.cpp (hunk 1 above)
Comment (momchil-velikov) [reply clang/lib/AST/MicrosoftMangle.cpp:2815]: It can be done. Doesn't mean it's a good idea.
With the proposed change all the SVE types will fall-through to the `SVE_SCALAR_TYPE` case, or worse
some will and some won't, depending on the relative order in `AArch64SVEACLETypes.def`.
That can work by including the `.def` file twice, once for the scalar type and once for all the SVE types.
Or use a `default:` for the unsupported cases, but I decided to stick to the existing style.

Comment (momchil-velikov) [reply clang/lib/AST/MicrosoftMangle.cpp:2815]: > Also, is there anyone we can tag that knows about the Microsoft mangling? I'm not sure if there's any process needed for adding a new type.

No idea. I just made sure the results are consistent with mangling of `__bf16` , `int8_t`, and vectors of those.

Comment (MacDue) [reply clang/lib/AST/MicrosoftMangle.cpp:2815]: With the current approach there simply won't be cases added for other `SVE_SCALAR_TYPE` types, so they won't be covered by the switch statement at all (which does not appear to have a `default:`). There will probably a warning when building clang, but it looks like at runtime the compiler will just silently drop mangling these types (and won't error).

Comment (MacDue) [reply clang/lib/AST/MicrosoftMangle.cpp:2815]: You could define the macro to check the builtin-type is the one you expect (I think `BuiltinType::MFloat8` is the only SVE_SCALAR_TYPE right now). 
```
#define SVE_SCALAR_TYPE(Name, MangledName, Id, SingletonId, Bits)  \
    case BuiltinType::Id:                                          \
      if (BuiltinType::Id == BuiltinType::MFloat8) {                  \
        mangleArtificialTagType(TagTypeKind::Struct, MangledName);   \
        break;                                                                                            \
      }                                                                                                         \
      [[fallthrough]];
```

Comment (momchil-velikov) [reply clang/lib/AST/MicrosoftMangle.cpp:2815]: > With the current approach there simply won't be cases added for other `SVE_SCALAR_TYPE` types.
Good point. Addressed in https://github.com/llvm/llvm-project/pull/125051

**Comment by MacDue** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/7939ce6295e7fc0214cd307f97dfccc0cabde381
