### PR TITLE
[Flang] Change sizeof argument name to "x"

### LINKED ISSUE #128610: [Flang] Compile error when argument keyword is used as argument to an extension sizeof intrinsic function
```
Version of flang : 21.0.0(f75126eeabba13ce2aab53c2e4296fca12b9da0d)/AArch64
```

When `argument keyword (X=)` is used as argument to an extension `sizeof` intrinsic function, a compilation error occurs.

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

sngts014_22.f90:
```fortran
program main
  call s2
  print *,'pass'
contains
  subroutine s2
    integer,parameter::pi41=sizeof(X=1)
    integer::i41
    if(pi41/=sizeof(X=i41)) print *,'err11'
  end subroutine s2
end program main
```

```
$ flang sngts014_22.f90; ./a.out
error: Semantic errors in sngts014_22.f90
./sngts014_22.f90:6:36: error: unknown keyword argument to intrinsic 'sizeof'
      integer,parameter::pi41=sizeof(X=1)
                                     ^
./sngts014_22.f90:8:21: error: unknown keyword argument to intrinsic 'sizeof'
      if(pi41/=sizeof(X=i41)) print *,'err11'
                      ^
$ 
```

```
$ gfortran sngts014_22.f90; ./a.out
 pass
$ 
```

```
$ ifx sngts014_22.f90; ./a.out
 pass
$ 
```

### PR DESCRIPTION
**Pull request by akuhlens**
This closes #128610 by fixing the name of the argument to the sizeof function to be "x" and adds a test.

### CODE REVIEW

File: flang/test/Intrinsics/sizeof.f90 [hunk 1]
```diff
@@ -0,0 +1,10 @@
+! RUN: %python %S/test_errors.py %s %flang_fc1
+  character(len=20) :: a, b
+  if (sizeof(a) == sizeof(x=b)) then
+    print *, "pass"
+  else
+    print *, "fail"
+  end if
+  ERROR! unknown keyword argument to intrinsic 'sizeof'
```
Comment (klausler) [inline flang/test/Intrinsics/sizeof.f90:8]: This file needs to be in flang/test/Semantics in order to use test_errors.py, and it needs to have a syntax error cleaned up.

**Comment by eugeneepshteyn** [comment]
I reviewed and don't have any other comments. I'll defer to Peter to approve this.

**Review by klausler — APPROVED** [review]

**Review by eugeneepshteyn — APPROVED** [review]
