### PR TITLE
[clang-format] Correctly handle backward compatibility of C headers

### LINKED ISSUE #158704: [clang-format] clang-format v21 ampersand spacing inconsistent in .h file with "Language C" section (regression from v20)
Changes in .h files seems to occur between clang-format v20 and v21, when .clang-format has a "C" Language section

(both indentation and spaces around &)

------------------------ test.h -------------------------
namespace Foo
{
    void bar(arg1 &result);
    void bar2(const arg1 &result);
}
------------------------ -------------------------

----------------------- .clang-format ----------
Language:        Cpp
BasedOnStyle:  LLVM
...
Language:        C
BasedOnStyle:  LLVM
-------------------------------------

-------------------------------------
clang-format-20 (20.1.0)
-------------------------------------
namespace Foo {
void bar(arg1 &result);
void bar2(const arg1 &result);
} // namespace Foo

-------------------------------------
clang-format-21  (21.1.1)
-------------------------------------
namespace Foo {
  void bar(arg1 & result);
  void bar2(const arg1 &result);
}

.h file is obviously considered C not C++ if I remove the Language C section from .clang-format  output is ad in cf-20

namespace Foo {
void bar(arg1 &result);
void bar2(const arg1 &result);
} // namespace Foo

### PR DESCRIPTION
**Pull request by owenca**
This in effect reverts 05fb8408de23c3ccb6125b6886742177755bd757 and 7e1a88b9d1431e263258e3ff0f729c1fdce342d3, the latter of which erroneously changed the behavior of formatting `ObjC` header files when both the default and `ObjC` styles were absent. Now the previous behavior of treating that as an error is restored.

Fixes #158704

### CODE REVIEW

File: clang/unittests/Format/ConfigParseTest.cpp [hunk 1]
```diff
@@ -1294,11 +1294,14 @@ TEST(ConfigParseTest, HandleNonCppDotHFile) {
 
   Style = {};
   Style.Language = FormatStyle::LK_Cpp;
-  EXPECT_EQ(parseConfiguration("Language: ObjC", &Style,
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/ConfigParseTest.cpp:1297]: Why remove this?

Comment (owenca) [reply clang/unittests/Format/ConfigParseTest.cpp:1297]: I've added the explanation in the commit message. Please see https://github.com/llvm/llvm-project/pull/159908#issue-3436689745.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by mydeveloperday — APPROVED** [review]
Looks good I think
