### PR TITLE
[M68k] Prevent folding of loads + stores when it would introduce new chain dependencies

### LINKED ISSUE #146213: [llvm] [M68k] CallSeq assertion failure in SelectionDAG
```ll
; RUN: llc < %s -mtriple=m68k-linux | FileCheck %s

define double @minimized() {
start:
  %_58 = call double null(double 0.000000e+00)
  %_60 = load double, ptr null, align 8
  %_57 = fmul double 0.000000e+00, %_60
  store double %_57, ptr null, align 8
  ret double 0.000000e+00
}
```

fails with `.../bin/FileCheck .../llvm/lib/CodeGen/SelectionDAG/ScheduleDAGRRList.cpp:510: llvm::SDNode* FindCallSeqStart(llvm::SDNode*, unsigned int&, unsigned int&, const llvm::TargetInstrInfo*): Assertion 'Best' failed.`

Something appears to be wrong with the `callseq_start/end` ordering with these instructions, but not yet sure what the exact problem is

### PR DESCRIPTION
**Pull request by knickish**
closes #146213 and #175472

This bug seems to have been exposed by the combined m->m load/store instructions available on M68k (these instructions are not available on i386, which the M68k backend is based on). This meant that token factors were inserted which could lead to distinct call sequence chains, increasing the nesting level and preventing the matching callseq_start from being identified during scheduling. 

The patch addresses this by not allowing combined loads/stores when the folded operation would result in a new chain dependency on a different call sequence. 

I have a patch almost ready to re-fold these loads/stores in a post-scheduling pass, but leaving this out to keep the patch as small as possible.

### CODE REVIEW

**Comment by knickish** [comment]
@mshockwave Would you be up for taking a quick look at this one? Think I actually made some progress on it this time.

File: llvm/lib/Target/M68k/M68kISelDAGToDAG.cpp [hunk 1]
```diff
@@ -172,6 +172,86 @@ struct M68kISelAddressMode {
...
+  SDNode *Found = nullptr;
+  Worklist.push_back(Chain);
+
+  while (!Worklist.empty()) {
+    SDNode *CN = Worklist.pop_back_val().getNode();
+    if (!CN || !Visited.insert(CN).second)
+      continue;
+
+    if (isCallSeqNode(CN)) {
+      if (!Found) {
```
Comment (mysterymath) [inline llvm/lib/Target/M68k/M68kISelDAGToDAG.cpp]: LLVM style has no braces for the inner `if`/`else if`, as they each have only one statement inside. The outer `if` needs braces, but only to avoid dangling `else`.

File: llvm/lib/Target/M68k/M68kISelDAGToDAG.cpp [hunk 2]
```diff
@@ -172,6 +172,86 @@ struct M68kISelAddressMode {
 
 namespace {
 
+struct CallSeqChainInfo {
```
Comment (mysterymath) [inline llvm/lib/Target/M68k/M68kISelDAGToDAG.cpp]: This could use a comment about what the semantics are for this object and its field.

**Review by mysterymath — APPROVED** [review]
LGTM!
