### PR TITLE
[llvm-profdata] Fix binary ids with multiple raw profiles in a single…

### LINKED ISSUE #72699: Profile binary id does not work with shared libraries
```
$ cat a.cpp
void foo();
void bar();

int main() {
foo();
bar();
return 0;
}

$ cat foo.cpp
void foo(){}
$ cat bar.cpp
void bar(){}
$ clang -fprofile-instr-generate -Wl,--build-id -O2 -fpic foo.cpp -o foo.so
$ clang -fprofile-instr-generate -Wl,--build-id -O2 -fpic bar.cpp -o bar.so
$ clang -fprofile-instr-generate -O2 -Wl,-build-id a.cpp $PWD/foo.so $PWD/bar.so -o a.exe
$ env LLVM_PROFILE_FILE="default.profraw" ./a.exe
$ llvm-profdata merge -o profdata default.profraw
$ llvm-profdata show --binary-ids default.profraw
Instrumentation level: Front-end
Total functions: 3
Maximum function count: 1
Maximum internal block count: 0
Binary IDs:
06022829f1a980398e09aa4fc4d26d78a1e9fac0
$ llvm-profdata show --binary-ids profdata
Instrumentation level: Front-end
Total functions: 3
Maximum function count: 1
Maximum internal block count: 0
Binary IDs:
06022829f1a980398e09aa4fc4d26d78a1e9fac0
$ llvm-readobj --notes bar.so
..
Build ID: 06022829f1a980398e09aa4fc4d26d78a1e9fac0
...
```

In this case, there are 3 raw profiles one after another in `default.profraw`. Each of them has a binary id.

Two things I noticed:
1. default.profraw actually contains 3 binary ids for a.exe, foo.so, bar.so, verified using hexdump, but llvm-prodata show --binary-ids is only able to show the one of them (It’s bar.so’s binary id in this case).
2. After merging, profdata only contains one binary id. Does this mean binary id is not useful anymore after merging?

It looks like a the problem is here: 
https://github.com/llvm/llvm-project/blob/becd1cb9d3dfc8a962ec2e4b3fe373de1abce9ba/llvm/lib/ProfileData/InstrProfReader.cpp#L90-L95

This function always returns one binary id. I think the correct way is to iterate all the raw profile headers and lookup binary ids.

### PR DESCRIPTION
**Pull request by ZequanWu**
Save binary ids when iterating through `RawInstrProfReader`.

Fixes #72699.

### CODE REVIEW

File: llvm/lib/ProfileData/InstrProfReader.cpp [hunk 1]
```diff
@@ -571,9 +559,20 @@ Error RawInstrProfReader<IntPtrT>::readHeader(
   if (!useCorrelate() && Correlator)
     return error(instrprof_error::unexpected_debug_info_for_correlation);
 
-  BinaryIdsSize = swap(Header.BinaryIdsSize);
-  if (BinaryIdsSize % sizeof(uint64_t))
+  uint64_t BinaryIdsSize = swap(Header.BinaryIdsSize);
+  // Binary ids start just after the header.
+  const uint8_t *BinaryIdsStart =
+      reinterpret_cast<const uint8_t *>(&Header) + sizeof(RawInstrProf::Header);
+  const uint8_t *BinaryIdEnd = BinaryIdsStart + BinaryIdsSize;
```
Comment (petrhosek) [inline llvm/lib/ProfileData/InstrProfReader.cpp:566]: Can we call it `BinaryIdsEnd` for consistency with `BinaryIdsStart` and `BinaryIdsSize`?

**Review by petrhosek — APPROVED** [review]

File: llvm/lib/ProfileData/InstrProfReader.cpp (hunk 1 above)
Comment (ZequanWu) [reply llvm/lib/ProfileData/InstrProfReader.cpp]: Renamed `BinaryIdsStart` and `BinaryIdsSize` to `BinaryIdStart` and `BinaryIdSize` because there can only be up to one binary id after the header.
