### PR TITLE
Fix MSVC 1920+ auto NTTP mangling for pointers to members

### LINKED ISSUE #70899: clang-cl mismangles C++17 `auto` NTTP of pointer-to-member type
code is quite large, but I get the error:
```
C:\Projects\chimera_client\clientsdk\igl\headers\igl\LinkedList.hpp(212,5): error : definition with same mangled name '??1?$LinkedList@$07@iugo@@QEAA@XZ' as another definition
    212 |     ~LinkedList()
        |     ^
  C:\Projects\chimera_client\clientsdk\igl\headers\igl\LinkedList.hpp(212,5): note: previous definition is here
C:\Projects\chimera_client\clientsdk\igl\headers\igl\LinkedList.hpp(203,5): error : definition with same mangled name '??0?$LinkedList@$07@iugo@@QEAA@$$QEAU01@@Z' as another definition
    203 |     LinkedList(LinkedList&& rhs) noexcept
        |     ^
  C:\Projects\chimera_client\clientsdk\igl\headers\igl\LinkedList.hpp(203,5): note: previous definition is here
```
only on windows with clang-cl

code is, but without includes is:
```cpp
namespace iugo
{
  template<auto NodeMember>
  struct LinkedList;
  
  
#pragma mark - LinkedListNode
  template<class _T>
  struct LinkedListNode
  {
    using T = RemoveReference<_T>;
    using ElementType = Conditional<IsReference<_T>, Ptr<T>, Instance<T>>;

    LinkedListNode() noexcept
    {
    }
    LinkedListNode(LinkedListNode const&) = delete;
    ~LinkedListNode()
    {
    }

    auto& operator =(LinkedListNode const&) = delete;
    
  private:
    template<auto> friend struct LinkedList;

    union
    {
      struct
      {
        Ptr<T> Prev;
        ElementType Next;
      };
    };
#if !FINAL
    bool IsConnected = false;
#endif

    void Create(Ptr<T> prev) noexcept
    {
      iglAssert(!IsConnected);
      unsafe::Construct(Prev, move(prev));
      unsafe::Construct(Next);
#if !FINAL
      IsConnected = true;
#endif
    }
    void Destroy() noexcept
    {
      iglAssert(IsConnected);
      unsafe::Destruct(Next);
      unsafe::Destruct(Prev);
#if !FINAL
      IsConnected = false;
#endif
    }
  };


#pragma mark - LinkedList
  template<class _T, class T, LinkedListNode<_T> T::* NodeMember>
  struct [[clang::trivial_abi]] LinkedList<NodeMember>
  {
    using ElementType = typename LinkedListNode<_T>::ElementType;

#pragma mark - Node
    struct Node: Ptr<T>
    {
      using Ptr<T>::Ptr;
      Node(Ptr<T> rhs) noexcept
      : Ptr<T>{move(rhs)}
      {
      }
      
      using Ptr<T>::operator =;
      
      [[nodiscard]] auto operator ->() const noexcept
      {
        return &Ptr<T>::operator ->*(NodeMember);
      }
    };
    
#pragma mark - Enumerator
    template<class TList>
    struct [[nodiscard]] Enumerator
    {
      TList&& List;

      Enumerator(TList&& list) noexcept
      : List{forward<TList>(list)}
      {
      }

      auto Remove() noexcept requires(!IsConst<RemoveReference<TList>>)
      {
#if !FINAL
        iglAssert(Version == List.Version(), "Modification during enumeration.");
        Version = ++List._Version;

#endif
        return List.Remove(Exchange(Current, (Current->*NodeMember).Next));
      }

      [[nodiscard]] decltype(auto) operator *() const noexcept
      {
        if constexpr(IsRValueReference<TList>)
        {
          return move(*Current);
        }
        else
        {
          return *Current;
        }
      }

      auto& operator ++()
      {
#if !FINAL
        iglAssert(Version == List.Version(), "Modification during enumeration.");

#endif
        Current = (Current->*NodeMember).Next;
        return *this;
      }

      explicit operator bool() const noexcept
      {
        return bool(Current);
      }

    private:
      decltype(declval<TList&>().First()) Current = List.First();
#if !FINAL
      uint Version = List.Version();
#endif
    };

    template<class TList>
    Enumerator(TList&&) -> Enumerator<TList>;

#pragma mark -
    [[nodiscard]] uint Count() const noexcept
    {
      return _Count;
    }
    
    [[nodiscard]] Ptr<T const> First() const noexcept
    {
      return _Head;
    }
    [[nodiscard]] Ptr<T> First() noexcept
    {
      return _Head;
    }
    [[nodiscard]] Ptr<T const> Last() const noexcept
    {
      return _Head ? Node{_Head}->Prev : nullptr;
    }
    [[nodiscard]] Ptr<T> Last() noexcept
    {
      return _Head ? Node{_Head}->Prev : nullptr;
    }

#if !FINAL
    [[nodiscard]] uint Version() const noexcept
    {
      return _Version;
    }
    
#endif
    LinkedList() = default;
    LinkedList(nullptr_t) noexcept
    {
    }
    template<Enumerable TEnum> requires(!IsSame<Unqualify<TEnum>, LinkedList> && (IsInitializable<T, EnumerableType<TEnum>> || IsConvertible<EnumerableType<TEnum>, ElementType>))
    LinkedList(TEnum&& enumerable)
    {
      for (auto&& item : forward<TEnum>(enumerable))
      {
        Add(forward<decltype(item)>(item));
      }
    }
    LinkedList(LinkedList&& rhs) noexcept
    : _Count{rhs._Count}
    , _Head{move(rhs._Head)}
    {
#if !FINAL
      ++rhs._Version;
#endif
      rhs._Count = 0;
    }
    ~LinkedList()
    {
      Destroy(_Head);
    }

    auto& operator =(nullptr_t) noexcept
    {
#if !FINAL
      ++_Version;
#endif
      Destroy(_Head);
      
      _Count = 0;
      unsafe::Reconstruct(_Head);
      return *this;
    }
    auto& operator =(LinkedList&& rhs) noexcept
    {
      iglAssert(this != &rhs);
      
#if !FINAL
      ++_Version;
#endif
      _Count = rhs._Count;
      _Head = move(rhs._Head);

#if !FINAL
      ++rhs._Version;
#endif
      rhs._Count = 0;
      return *this;
    }

    T& Add(ElementType newValue) noexcept
    {
      auto& value = *newValue;

#if !FINAL
      ++_Version;
#endif
      ++_Count;
      
      if (_Head)
      {
        Node node = _Head;
        auto& next = Node{node->Prev}->Next;
        next = move(newValue);
        Node{next}->Create(Exchange(node->Prev, next));
      }
      else
      {
        _Head = move(newValue);
        Node{_Head}->Create(_Head);
      }

      return value;
    }
    template<class... TArgs> requires IsInitializable<T, TArgs...>
    decltype(auto) Add(TArgs&&... args)
    {
      static_assert(IsSame<ElementType, Instance<T>>);
      
      return Add(New<T>(forward<TArgs>(args)...));
    }
    [[nodiscard]] ElementType Extract(Node node) noexcept
    {
      Finally finally = [node] { node->Destroy(); };
      
#if !FINAL
      ++_Version;
#endif
      --_Count;
      
      if (_Head != node)
      {
        Node prev = node->Prev;
        auto& next = prev->Next;
        auto oldValue = Exchange(next, move(node->Next));
        Node{next ? next : _Head}->Prev = prev;
        return oldValue;
      }
      else if (node->Next)
      {
        Node prev = node->Prev;
        auto oldValue = Exchange(_Head, move(node->Next));
        Node{_Head}->Prev = prev;
        return oldValue;
      }
      else
      {
        return move(_Head);
      }
    }
    void Remove(Node node) noexcept
    {
      [[maybe_unused]] ElementType _ = Extract(node);
    }
    [[nodiscard]] ElementType Pop() noexcept
    {
      return Extract(_Head->Prev);
    }

    auto begin()&& noexcept
    {
      return Enumerator{move(*this)};
    }
    auto begin() const& noexcept
    {
      return Enumerator{*this};
    }
    auto begin()& noexcept
    {
      return Enumerator{*this};
    }
    static constexpr auto end() noexcept
    {
      return Sentinel{};
    }
    
    explicit operator bool() const noexcept
    {
      return bool(_Head);
    }

  private:
    uint _Count = 0;
    ElementType _Head;
#if !FINAL
    uint _Version = 0;
#endif
    
    void Destroy(Node node) noexcept
    {
      if (node)
      {
        Destroy(node->Next);

        node->Destroy();
      }
    }
  };
}
```

### PR DESCRIPTION
**Pull request by MaxEW707**
Fixes https://github.com/llvm/llvm-project/issues/70899.

This is a continuation of https://github.com/llvm/llvm-project/pull/92477 for pointers to member data and pointers to member functions.

The mangled name must be prefixed with `$M <mangled-type>` for the deduced type of the nttp parameter.

### CODE REVIEW

File: clang/test/CodeGenCXX/mangle-ms-auto-templates-nullptr.cpp [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+};
+
+template <auto a>
+auto AutoFunc() {
+    return a;
+}
+
+void template_mangling() {
+
+  AutoParmTemplate<nullptr> auto_nullptr;
```
Comment (MaxEW707) [inline clang/test/CodeGenCXX/mangle-ms-auto-templates-nullptr.cpp:17]: This is a separate file since `nullptr` gets mangled the same as an integer literal.

In VS2017 this gets mangled with the `$M <type>` so clang emits an error for emitting the same mangled name definition for two different objects if these test is inside `mangle-ms-auto-templates.cpp` which has tests for mangling integer literals.

VS2017 gets around this by erroneously putting all the definitions into COMDAT sections which clang does not do at the moment when trying to be VS2017 compatible.

File: clang/lib/AST/MicrosoftMangle.cpp [hunk 2]
```diff
@@ -1767,12 +1805,12 @@ void MicrosoftCXXNameMangler::mangleTemplateArg(const TemplateDecl *TD,
...
       if (MPT->isMemberFunctionPointerType() &&
           !isa<FunctionTemplateDecl>(TD)) {
-        mangleMemberFunctionPointer(RD, nullptr);
+        mangleMemberFunctionPointer(RD, nullptr, nullptr, QualType());
         return;
       }
       if (MPT->isMemberDataPointer()) {
         if (!isa<FunctionTemplateDecl>(TD)) {
-          mangleMemberDataPointer(RD, nullptr);
+          mangleMemberDataPointer(RD, nullptr, nullptr, QualType());
```
Comment (MaxEW707) [inline clang/lib/AST/MicrosoftMangle.cpp:1813]: These use cases appear to be added from, https://github.com/llvm/llvm-project/commit/5518a9d7673bfe55b4110bea049140316d032fbf, with support for C++20 nttp changes.

From looking at the code we only hit this path when compiling for C++20 and also already properly mangle according to VS2019+ by doing `$M <type>` elsewhere.

I intend to take a look at C++20 NTTP after this PR and then take a more holistic look to see if we can better merge the C++11-17 and C++20 mangling paths in `MicrosoftMangle.cpp`.

**Review by zmodem — APPROVED** [review]
lgtm
