### PR TITLE
[LLVM][SelectionDAG] Don't assume masked loads access all lanes in memory.

### LINKED ISSUE #180251: [AArch64] Wrong code at -Os -march=armv9-a+sve
Reproducer: https://godbolt.org/z/bKK598ndd
Testcase (generated by Csmith):
```c
#include <stdio.h>
#include <stdint.h>
int32_t g_3, g_5;
int main()
{
    int8_t l_2[6];
    for (g_3 = 0; g_3 < 6; g_3 += 1) l_2[g_3] = 7;
    for (g_3 = 5; g_3 >= 0; g_3 -= 1) g_5 ^= l_2[g_3];
    printf("checksum = %08X\n", g_5);
}
```

### PR DESCRIPTION
**Pull request by paulwalker-arm**
When creating the initial DAG for masked loads we are using the result type to define LocationSize. However, being a masked load we do not know which, if any, memory locations will be read.

Fixes https://github.com/llvm/llvm-project/issues/180251

### CODE REVIEW

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp [hunk 1]
```diff
@@ -5122,7 +5122,7 @@ void SelectionDAGBuilder::visitMaskedLoad(const CallInst &I, bool IsExpanding) {
 
   MachineMemOperand *MMO = DAG.getMachineFunction().getMachineMemOperand(
       MachinePointerInfo(PtrOperand), MMOFlags,
-      VT.getStoreSize(), Alignment, AAInfo, Ranges);
+      LocationSize::beforeOrAfterPointer(), Alignment, AAInfo, Ranges);
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp]: What is the problem here? This should report the maximum possible size read, it doesn't matter if it reads less

Comment (davemgreen) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp]: When I looked at it before it seemed like it would be better for the MMO to have a "predicated" flag or something, so that the store size is correct for the maximal size of the memory operation but the AA can account for cases where the whole location is not necessarily accessed.

**Comment by nikic** [comment]
> NOTE: I do wonder if masked loads and store should using LocationSize::upperBound(VT.getStoreSize())?

Yes, that's generally the right thing to do for masked accesses.

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp (hunk 1 above)
Comment (paulwalker-arm) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp]: The problem is the "possible" part was missing from the reported size read. This leads to alias analysis thinking we're accessing beyond the bounds of an allocated object, which is undefined behaviour that results in assuming there is no alias.

**Review by arsenm — APPROVED** [review]
I think there are more instances of this around

**Review by nikic — APPROVED** [review]
LGTM

We should probably update visitMaskedStore to use upperBound instead of beforeOrAfter as well.

**Comment by davemgreen** [comment]
> We should probably update visitMaskedStore to use upperBound instead of beforeOrAfter as well.

I believe the MMO will internally store the LocationSize as an LLT, and any "non-valid" LocationSize will become an invalid LLT. It needs vector sizes. So this probably won't do anything other than give it an unknown / beforeOrAfterPointer size when coming back out. I'm not sure if I traced that through exactly correctly, but If we wanted something more specific (and for the upperBound size to be honoured / kept around) - we would need keep more data about it in the MMO.
