### PR TITLE
[mlir][affine] fix the issue of ceildiv-mul-ceildiv form expression n…

### LINKED ISSUE #107508: [mlir] Semantic inconsistency in `ceildiv` optimization
Git version: [c28b1a19aa](https://github.com/llvm/llvm-project/commit/c28b1a19aa)
System: Ubuntu 18.04.6 LTS

# Issue Description:
In the following MLIR:
a.mlir
```
func.func @semiaffine_composite_floor(%arg0: index, %arg1: index) -> index {
  %a = affine.apply affine_map<(d0)[s0] ->(((((s0 * 2) ceildiv 4) * 5) + s0 * 42) ceildiv s0)> (%arg0)[%arg1]
  return %a : index
}
```
After running `mlir-opt -canonicalize a.mlir`, the resulting optimized MLIR is:
```
module {
  func.func private @semiaffine_composite_floor(%arg0: index, %arg1: index) -> index {
    %c47 = arith.constant 47 : index
    return %c47 : index
  }
}
```
This leads to the result always being 47.

However, without applying the canonicalize optimization, the result of a.mlir varies depending on the input `%arg1` as follows:

- 44 if `%arg1` is less than 0
- Floating-point exception if `%arg1` is 0
- 47 if `%arg1` is 1
- 45 if `%arg1 `is greater than 1

This seems like a misoptimization in the handling of ceildiv. The canonicalize pass simplifies the expression to always return 47, but the expected behavior is input-dependent as shown above. Is this an unintended side effect of the ceildiv optimization?

### PR DESCRIPTION
**Pull request by lipracer**
…ot satisfying commutative

Fixes https://github.com/llvm/llvm-project/issues/107508

### CODE REVIEW

File: mlir/lib/IR/AffineExpr.cpp [hunk 1]
```diff
@@ -406,12 +419,25 @@ static bool isDivisibleBySymbol(AffineExpr expr, unsigned symbolPos,
     AffineBinaryOpExpr binaryExpr = cast<AffineBinaryOpExpr>(expr);
     if (opKind != expr.getKind())
       return false;
-    return isDivisibleBySymbol(binaryExpr.getLHS(), symbolPos, expr.getKind());
+    if (llvm::any_of(visitedExprs, [](auto expr) {
```
Comment (jreiffers) [inline mlir/lib/IR/AffineExpr.cpp:422]: I don't understand this condition. I didn't understand the condition before either, but I still don't understand it. Won't this say `that s0 // 42 + s0` is divisible by `s0`? 

I think we should have unit tests for isDivisibleBySymbol, not just integration-style tests for all of simplification.

File: mlir/lib/IR/AffineExpr.cpp [hunk 2]
```diff
@@ -406,12 +419,25 @@ static bool isDivisibleBySymbol(AffineExpr expr, unsigned symbolPos,
...
+          return expr.getKind() == AffineExprKind::Mul;
+        }))
+      return false;
+    return isDivisibleBySymbolImpl(binaryExpr.getLHS(), symbolPos,
+                                   expr.getKind(), visitedExprs, depth + 1);
```
Comment (jreiffers) [inline mlir/lib/IR/AffineExpr.cpp:427]: Assuming the logic here is correct, you can replace the `visitedExprs` vector with just a boolean flag that tells you whether you're in a mul.

**Review by jreiffers — CHANGES_REQUESTED** [review]

File: mlir/lib/IR/AffineExpr.cpp (hunk 2 above)
Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp:427]: flag can't be used, If this expression`(s0 * 2) + s0 ceildiv 2)`,I need to reset the flag after visited lhs `add`,Do you think this behavior is easy to understand?

Comment (jreiffers) [reply mlir/lib/IR/AffineExpr.cpp:427]: Maybe I'm missing something. Doesn't your call tree looks like this:

```             
              flag
+             false
   *          false
      s0      true
      2       true
   ceildiv    false
      s0      false
      2       false
```

Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp:427]: Yes.we need to reset flag to false,before visit ceildiv.

Comment (jreiffers) [reply mlir/lib/IR/AffineExpr.cpp:427]: But these are sibling branches of the recursion. The flag is an argument, so it'll be false in ceildiv and below because there's no mul in the call chain.

File: mlir/lib/IR/AffineExpr.cpp (hunk 1 above)
Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp:422]: `a / b / s0 <=> a / s0 / b`. If `a` is a multiple of `s0`, we can simplify a. but if (a / b) * d / s0 does not hold.

File: mlir/lib/IR/AffineExpr.cpp (hunk 2 above)
Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp:427]: Ok.I see.

File: mlir/lib/IR/AffineExpr.cpp (hunk 1 above)
Comment (jreiffers) [reply mlir/lib/IR/AffineExpr.cpp:422]: Ah, so the function is just named incorrectly. How about `canSinkDivisionBySymbol` or something along those lines?

Comment (jreiffers) [reply mlir/lib/IR/AffineExpr.cpp]: Let's do this rename too. `canSimplifyDivisionBySymbol` or `canSinkDivisionBySymbol` would work for me. Maybe the former is better.

Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp]: renamed, sorry my written English is not good.

**Comment by lipracer** [comment]
we can simple `(n * s) ceildiv a ceildiv s` to `n ceildiv a`
because `(n * s) ceildiv a ceildiv b` <=> `(n * s) ceildiv s ceildiv a`
<=> `n ceildiv a`

let's prove the `s floordiv a floor b` <=> `s floordiv b floor a`
let `s = ka +m (m < a)` so `s floordiv a` <=> `s / a - m / a`

similarly, it can be proven that: 
`s floordiv a floordiv b` <=> `s / (a * b) - m / (a * b) - n / (b)   constrain  (n < b)` 
<=> `s / (a * b) - (m + a*n) / (a*b)`

because `a* b - (m + a*n)` <=> `a*b - a*n - m` > `a - m` > `0`
so `s floordiv a floordiv b` <=> `[s / (a*b)]` <=> `s floordiv b floordiv a`
but if `s floordiv b` mutiply a factor above didn't always hold true.

File: mlir/lib/IR/AffineExpr.cpp (hunk 2 above)
Comment (lipracer) [reply mlir/lib/IR/AffineExpr.cpp]: @jreiffers Done.

**Review by jreiffers — APPROVED** [review]
