### PR TITLE
fix: replace report_fatal_error with Diags and exit

### LINKED ISSUE #147187: Clang-21 Crash: fatal error: error in backend: can't open file './xxxxxx': No such file or directory
### Description
I encountered a crash in Clang-21 when compiling the following code with compilation options:
```c
int a;

```
Options:
```sh
-Xclang -fsanitize-system-ignorelist=./xxxxxx -fbounds-check -fno-sanitize-link-runtime -fsigned-char 
```

### Clang Version

```sh
$ clang -v
Ubuntu clang version 21.0.0 (++20250501082025+9b1051281e43-1~exp1~20250501082214.882)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-21/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Command
The compilation command used was:
```sh
clang bug.c -Xclang -fsanitize-system-ignorelist=./optfuzz -fbounds-check -fno-sanitize-link-runtime -fsigned-char  -c -o bug.o
```

### Error Message
```sh
clang: warning: argument unused during compilation: '-fbounds-check' [-Wunused-command-line-argument]
fatal error: error in backend: can't open file './optfuzz': No such file or directory
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -Xclang -fsanitize-system-ignorelist=./optfuzz -fbounds-check -fno-sanitize-link-runtime -fsigned-char <source>
 #0 0x0000000003f7af98 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f7af98)
 #1 0x0000000003f783c4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f783c4)
 #2 0x0000000003ebd246 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3ebd246)
 #3 0x0000000003f6f8de llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f6f8de)
 #4 0x0000000000d8e460 LLVMErrorHandler(void*, char const*, bool) cc1_main.cpp:0:0
 #5 0x0000000003ec8033 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3ec8033)
 #6 0x0000000003ec816c (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3ec816c)
 #7 0x0000000007e99568 clang::SanitizerSpecialCaseList::createOrDie(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, llvm::vfs::FileSystem&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7e99568)
 #8 0x0000000007e97fb9 clang::NoSanitizeList::NoSanitizeList(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, clang::SourceManager&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x7e97fb9)
 #9 0x00000000074c74eb clang::ASTContext::ASTContext(clang::LangOptions&, clang::SourceManager&, clang::IdentifierTable&, clang::SelectorTable&, clang::Builtin::Context&, clang::TranslationUnitKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x74c74eb)
#10 0x0000000004b94382 clang::CompilerInstance::createASTContext() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4b94382)
#11 0x0000000004c2c3cd clang::FrontendAction::BeginSourceFile(clang::CompilerInstance&, clang::FrontendInputFile const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4c2c3cd)
#12 0x0000000004ba490a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4ba490a)
#13 0x0000000004d191f1 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4d191f1)
#14 0x0000000000d90b9f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xd90b9f)
#15 0x0000000000d8777a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#16 0x00000000049955b9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#17 0x0000000003ebd184 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3ebd184)
#18 0x0000000004995bcf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#19 0x0000000004957b9d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4957b9d)
#20 0x0000000004958c2e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4958c2e)
#21 0x00000000049617c5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49617c5)
#22 0x0000000000d8d04f clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xd8d04f)
#23 0x0000000000c42504 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xc42504)
#24 0x0000711292829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#25 0x0000711292829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#26 0x0000000000d87225 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xd87225)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Compiler returned: 70
```

The issue can also be reproduced on Compiler Explorer:https://godbolt.org/z/oWPP496x5
Please let me know if you need any more details.

### PR DESCRIPTION
**Pull request by woruyu**
Summary
This PR resolves https://github.com/llvm/llvm-project/issues/147187

### CODE REVIEW

**Comment by woruyu** [comment]
@hstk30-hw This patch is now ready for review.

**Comment by hstk30-hw** [comment]
Need a test case at least.

File: clang/lib/Basic/SanitizerSpecialCaseList.cpp [hunk 1]
```diff
@@ -30,11 +30,16 @@ SanitizerSpecialCaseList::create(const std::vector<std::string> &Paths,
...
 SanitizerSpecialCaseList::createOrDie(const std::vector<std::string> &Paths,
-                                      llvm::vfs::FileSystem &VFS) {
+                                      llvm::vfs::FileSystem &VFS,
+                                      DiagnosticsEngine &Diags) {
   std::string Error;
   if (auto SSCL = create(Paths, VFS, Error))
     return SSCL;
-  llvm::report_fatal_error(StringRef(Error));
+  unsigned DiagID = Diags.getCustomDiagID(clang::DiagnosticsEngine::Error,
+                                          "failed to load NoSanitize file: %0");
```
Comment (AaronBallman) [inline clang/lib/Basic/SanitizerSpecialCaseList.cpp]: This shouldn't be a custom diagnostic; I would imagine this would be a driver diagnostic. But we can't emit driver diagnostics from Basic.

I think we need a bit wider of an approach where `createOrDie` is `create` which the caller has to respond to if it returns an empty `unique_ptr` so that the driver eventually is what emits the diagnostic.

CC @MaskRay for more opinions

**Comment by woruyu** [comment]
> Need a test case at least.

Done!

**Comment by hstk30-hw** [comment]
@shafik Take a look, pls.

**Comment by woruyu** [comment]
Hi,@hstk30-hw, @shafik, @AaronBallman just wanted to check if there’s anything further needed from my side for this patch. I’d be happy to help clarify or adjust anything.

**Review by AaronBallman — COMMENTED** [review]
Ugh, sorry for the delayed review! I had a comment several days ago but forgot to hit Submit. :-/

File: clang/lib/Basic/SanitizerSpecialCaseList.cpp (hunk 1 above)
Comment (MaskRay) [reply clang/lib/Basic/SanitizerSpecialCaseList.cpp:39]: I agree that ideally this error reporting is delayed.

createOrDie is called by NoSanitizeList::NoSanitizeList, which is called by ASTContext::ASTContext. To report a proper diagnostic, we need to remove these calls from ctors to an init function.

Comment (woruyu) [reply clang/lib/Basic/SanitizerSpecialCaseList.cpp]: Done! I have refactor it!

File: clang/lib/AST/ASTContext.cpp [hunk 2]
```diff
@@ -1697,6 +1698,15 @@ ASTContext::getRelocationInfoForCXXRecord(const CXXRecordDecl *RD) const {
   return std::nullopt;
 }
 
+void ASTContext::initSanitizers(const LangOptions &LangOpts,
+                                SourceManager &SM) {
+  std::string Error;
+  if (!NoSanitizeL->init(LangOpts.NoSanitizeFiles, Error)) {
+    const std::string &Path = LangOpts.NoSanitizeFiles.front();
```
Comment (AaronBallman) [inline clang/lib/AST/ASTContext.cpp:1705]: I think this assumes that the first file in the list is the one we cannot read; what happens if we can read that one fine but a subsequent file is where we struggle? We'd report the wrong path to the user in that case, which would be hard for them to reason about.

Comment (AaronBallman) [reply clang/lib/AST/ASTContext.cpp]: > so I think using CustomDiagID is better!

Custom diagnostics are not an acceptable solution IMO; the reason is because they don't get a warning group associated with them and so users have no way to silence those diagnostics. We have some uses of the API in Clang but in every case they're the wrong tool to use.

We actually document this on the API itself, but not very clearly: https://github.com/llvm/llvm-project/blob/b3e016e05f1d21428298760db82b26fd0266f8bb/clang/include/clang/Basic/Diagnostic.h#L898 (I'll fix up the comment)

Comment (woruyu) [reply clang/lib/AST/ASTContext.cpp]: > Custom diagnostics are not an acceptable solution IMO;

Thanks for the feedback! To confirm: is the correct fix to define dedicated diagnostics in a `.td` file like this:
```
def err_no_sanitize_file_open_fail : Error<
  "failed to load NoSanitize file: can't open file '%0'">;

def err_no_sanitize_file_parse_fail : Error<
  "failed to load NoSanitize file: error parsing file '%0'">;

def SanitizeIgnorelist : DiagGroup<"sanitize-ignorelist">;
```
Then use them accordingly in `ASTContext::initSanitizers`.

Comment (AaronBallman) [reply clang/lib/AST/ASTContext.cpp]: Almost! You can split the diagnostics up if that's easier for you, but another approach would be:
```
def err_no_sanitize_file_failure : Error<
  "failed to %select{load|parse}0 sanitizer ignorelist file '%1'">;
```
where you only have a single diagnostic but pass in an argument to switch between `load` and `parse`.

Note, you don't need:

> `def SanitizeIgnorelist : DiagGroup<"sanitize-ignorelist">;`

because diagnostic groups are only for warnings, and you're producing errors.

Comment (woruyu) [reply clang/lib/AST/ASTContext.cpp]: I decided to go with:
```
def err_sanitize_ignorelist_failure : Error<
  "failed to sanitize ignorelist file: %0">;
```
instead of 
```
def err_no_sanitize_file_failure : Error<
  "failed to %select{load|parse}0 sanitizer ignorelist file '%1'">;
```
for two reasons:
1.The `%select` logic is essentially string formatting and can be handled downstream where the error message is constructed.
2.Changing `SpecialCaseList::createInternal` to propagate structured error info adds unnecessary complexity, especially given its general-purpose nature.

**Comment by woruyu** [comment]
Additionally, I noticed the same issue occurs with `-fprofile-list=` (e.g. `clang test.c -Xclang -fprofile-list=11111 -c`). I plan to address it in a follow-up patch.

File: clang/include/clang/Basic/DiagnosticFrontendKinds.td [hunk 3]
```diff
@@ -370,6 +370,8 @@ def warn_profile_data_misexpect : Warning<
   "potential performance regression from use of __builtin_expect(): "
   "annotation was correct on %0 of profiled executions">,
   BackendInfo, InGroup<MisExpect>;
+def err_sanitize_ignorelist_failure : Error<
+  "failed to sanitizer ignorelist file: %0">;
```
Comment (AaronBallman) [inline clang/include/clang/Basic/DiagnosticFrontendKinds.td:374]: The diagnostic is missing a verb. Failed to open? Failed to parse?

Comment (woruyu) [reply clang/include/clang/Basic/DiagnosticFrontendKinds.td]: Done!

File: clang/lib/AST/ASTContext.cpp (hunk 2 above)
Comment (woruyu) [reply clang/lib/AST/ASTContext.cpp]: Done! By the way, I find many diagnose to modify such as ` err_drv_malformed_sanitizer_coverage_allowlist, err_drv_malformed_sanitizer_ignorelist` and so on, but I get a redefine error of SpecialCaseListFailure, so I change it to %select.

**Comment by woruyu** [comment]
we can't use diagnostics in llvm-tools, so keep the overload function `std::string &Error`, which is called by llvm-cfi-verify.cpp or CodeCoverage.cpp
```
LLVM_ABI static std::unique_ptr<SpecialCaseList>
  create(const std::vector<std::string> &Paths, llvm::vfs::FileSystem &FS,
         std::string &Error);

// first in llvm-cfi-verify.cpp
std::unique_ptr<SpecialCaseList> SpecialCaseList;
  if (IgnorelistFilename != "-") {
    std::string Error;
    SpecialCaseList = SpecialCaseList::create({IgnorelistFilename},
                                              *vfs::getRealFileSystem(), Error);
    if (!SpecialCaseList) {
      errs() << "Failed to get ignorelist: " << Error << "\n";
      exit(EXIT_FAILURE);
    }
  }

// second in CodeCoverage.cpp
// Read in -name-allowlist files.
if (!NameFilterFiles.empty()) {
  std::string SpecialCaseListErr;
  NameAllowlist = SpecialCaseList::create(
      NameFilterFiles, *vfs::getRealFileSystem(), SpecialCaseListErr);
  if (!NameAllowlist)
    error(SpecialCaseListErr);
}
```

**Review by AaronBallman — APPROVED** [review]
Thank you, this LGTM! Do you need someone to merge on your behalf?

**Comment by woruyu** [comment]
> Thank you, this LGTM! Do you need someone to merge on your behalf?

Yes, please — I don’t have commit access.

**Comment by AaronBallman** [comment]
Reverting the changes because these failures look related to the patch. I *think* we're missing a call to `initSanitizers()` somewhere, possibly in `SanitizerSpecialCaseList::create()`. I don't have the bandwidth to try to debug it now, hence the revert.

**Comment by woruyu** [comment]
> Reverting the changes because these failures look related to the patch. I _think_ we're missing a call to `initSanitizers()` somewhere, possibly in `SanitizerSpecialCaseList::create()`. I don't have the bandwidth to try to debug it now, hence the revert.

 I took a closer look at the build logs and I suspect the issue might be related to this code:
```
// in ASTUnit.cpp
  if (ToLoad >= LoadASTOnly)
    AST->Ctx = new ASTContext(*AST->LangOpts, AST->getSourceManager(),
                              PP.getIdentifierTable(), PP.getSelectorTable(),
                              PP.getBuiltinInfo(),
                              AST->getTranslationUnitKind());
```
The failing cases seem to be triggered during C++20 module builds, and from what I can tell, reproducing them locally is quite difficult. That said, this made me reconsider the core design of the merged patch.
Currently, the code assumes that `ASTContext::initSanitizers()` will always be called after constructing the context. However, this assumption introduces a latent risk—if the caller forgets to call `initSanitizers()`, we can end up with a `std::unique_ptr` being null at runtime. In my view, this is not a particularly robust design.
To make this more resilient, I believe it would be safer to revert to the previous approach, where construction and validation are combined via something like:
```
std::unique_ptr<SanitizerSpecialCaseList>
SanitizerSpecialCaseList::createOrDie(...) {
  ...
  if (auto SSCL = create(...))
    return SSCL;
  llvm::remove_fatal_error_handler();
  llvm::report_fatal_error(StringRef(Error), false);
}
```
This way, we can ensure that a valid object is always returned, and we can avoid unexpected crashes (or stack dumps) due to misuse. To me, this seems like a safer and more maintainable direction.
