### PR TITLE
[ELF] Reject certain unknown section types

### LINKED ISSUE #84812: lld/ELF: Report errors for certain unknown section types
From https://maskray.me/blog/2024-03-09-a-compact-relocation-format-for-elf#linker-notes

GNU ld allows certain unknown section types:

* `[SHT_LOUSER,SHT_HIUSER]` and non-`SHF_ALLOC`
* `[SHT_LOOS,SHT_HIOS]` and non-`SHF_OS_NONCONFORMING`

but reports errors and stops linking for others (unless `--no-warn-mismatch` is specified).
When linking a relocatable file using `SHT_RELLEB`, you might encounter errors like the following:

```
% myclang -mrelleb -fuse-ld=bfd a.c b.c
/usr/bin/ld.bfd: unknown architecture of input file `/tmp/a-1e0778.o' is incompatible with i386:x86-64 output
/usr/bin/ld.bfd: unknown architecture of input file `/tmp/b-9963f0.o' is incompatible with i386:x86-64 output
/usr/bin/ld.bfd: error in /tmp/a-1e0778.o(.eh_frame); no .eh_frame_hdr table will be created
/usr/bin/ld.bfd: error in /tmp/b-9963f0.o(.eh_frame); no .eh_frame_hdr table will be created
clang: error: linker command failed with exit code 1 (use -v to see invocation)
% myclang -mrelleb -fuse-ld=bfd a.c b.c -Wl,--no-warn-mismatch && ./a.out
/usr/bin/ld.bfd: error in /tmp/a-a1a5f4.o(.eh_frame); no .eh_frame_hdr table will be created
/usr/bin/ld.bfd: error in /tmp/b-9dd23c.o(.eh_frame); no .eh_frame_hdr table will be created
[1]    2459175 segmentation fault  ./a.out
```

I have a prototype for a new relocation format (RELLEB). Linking a.o and b.o with unpatched lld and gold create an output file with unrelocated `.text` and will crash at run-time.

### PR DESCRIPTION
**Pull request by MaskRay**
Unknown section sections may require special linking rules, and
rejecting such sections for older linkers may be desired. For example,
if we introduce a new section type to replace a control structure (e.g.
relocations), it would be nice for older linkers to reject the new
section type. GNU ld allows certain unknown section types:

* [SHT_LOUSER,SHT_HIUSER] and non-SHF_ALLOC
* [SHT_LOOS,SHT_HIOS] and non-SHF_OS_NONCONFORMING

but reports errors and stops linking for others (unless
--no-warn-mismatch is specified). Port its behavior. For convenience, we
additionally allow all [SHT_LOPROC,SHT_HIPROC] types so that we don't
have to hard code all known types for each processor.

Close https://github.com/llvm/llvm-project/issues/84812

### CODE REVIEW

File: lld/ELF/InputFiles.cpp [hunk 1]
```diff
@@ -741,6 +741,31 @@ template <class ELFT> void ObjFile<ELFT>::initializeJustSymbols() {
...
+static bool isKnownSpecificSectionType(uint32_t t, uint32_t flags) {
+  if (SHT_LOUSER <= t && t <= SHT_HIUSER && !(flags & SHF_ALLOC))
+    return true;
+  if (SHT_LOOS <= t && t <= SHT_HIOS && !(flags & SHF_OS_NONCONFORMING))
+    return true;
+  switch (config->emachine) {
+  case EM_ARM:
+    return t == SHT_ARM_EXIDX || t == SHT_ARM_ATTRIBUTES;
+  case EM_AARCH64:
+    return t == SHT_AARCH64_MEMTAG_GLOBALS_STATIC;
```
Comment (smithp35) [inline lld/ELF/InputFiles.cpp:753]: GNU ld will accept SHT_AARCH64_ATTRIBUTES in AArch64 too. This is reserved for the spec and can be ignored if a linker does not understand the contents. It would be useful to add this so that when  SHT_AARCH64_ATTRIBUTES is added lld doesn't choke on them.

This may be the case for other LOPROC/HIPROC values that lld doesn't currently understand, but I'm only familiar with Arm and AArch64.

Of the ones in AArch64 there is also `SHT_AARCH64_AUTH_RELR` defined in https://github.com/ARM-software/abi-aa/blob/main/pauthabielf64/pauthabielf64.rst#7section-types 

I know there is a pull-request to add LLD support for that. May be worth adding as a constant until the symbolic value is known.

The other section types in https://github.com/ARM-software/abi-aa/blob/main/aaelf32/aaelf32.rst not implemented by LLD don't need to be added as these are linker generated sections for the benefit of debuggers/post-link tools.

**Review by smithp35 — COMMENTED** [review]
Will be good to see if we can get some comments from people interested in their SHT_LOPROC SHT_HIPROC range.

File: lld/ELF/InputFiles.cpp (hunk 1 above)
Comment (MaskRay) [reply lld/ELF/InputFiles.cpp:753]: Thanks. Sounds good to allow SHT_AARCH64_ATTRIBUTES as well even if it is unused now.
SHT_AARCH64_AUTH_RELR is for dynamic relocations only, so rejecting it here is fine. The test has a SHT_RELR example.

Shall we just allow all processor-specific relocation types?

Comment (smithp35) [reply lld/ELF/InputFiles.cpp]: That's an interesting question. It is a pity there isn't a `SHF_PROC_NONCONFORMING` flag that would make this easier to reason about.

I think allowing processor section types would be an easier way to introduce this patch as it wouldn't need all the processor specific looked over, which may be difficult to do. Perhaps start with it this way, then as we get more information we could perhaps limit to the section types that we know exist in the specifications.

I know at Arm we are reluctant to introduce new section types because of the problem of older, and other proprietary linkers, that may not want to suppport them. I expect many other processor namespace ABIs think similarly.

**Review by smithp35 — APPROVED** [review]
LGTM from me. I think we can optionally tighten up the processor specific section in a follow up patch.

**Comment by MaskRay** [comment]
Thanks for the additional context. My motivation was primarily to detect new section types in the generic range `[0, SHT_LOOS)`. These new generic section types, if introduced, may be about new control structures that replace the existing, size-inefficient ones, e.g. https://discourse.llvm.org/t/rfc-relleb-a-compact-relocation-format-for-elf/77600 

I agree that we can optionally tighten up the processor specific section in a follow up patch.

I think certain architectures probably don't want the old-linker-detecting behavior ("time travel compatibility"). So we might not want to introduce the behavior.
