### PR TITLE
[HLSL][SPIRV] Fix firstbitset in spirv

### LINKED ISSUE #143171: [HLSL][SPIRV] 64bit firstbithigh returns incorrect values
Discovered while running the offload-test-suite. The values returned imply an incorrect lowering for the 64bit overload. This only occurs for the Vulkan target which makes sense as it has the most complex lowering. The errors are all off by 32 so its probably an error related to the bit offseting to  account for splitting a i64 into i32x2

```
# .---command stderr------------
# | Test failed: Test1
# | Expected:
# | ---
# | Name:            ExpectedOut
# | Format:          UInt32
# | Stride:          16
# | Data:            [ 4294967295, 3, 0, 63, 4294967295, 3, 0, 63, 4294967295, 
# |                    2, 3, 4294967295 ]
# | OutputProps:
# |   Height:          0
# |   Width:           0
# |   Depth:           0
# | ...
# | Got:
# | ---
# | Name:            Out
# | Format:          UInt32
# | Stride:          16
# | Data:            [ 4294967295, 35, 32, 63, 4294967295, 35, 32, 63, 4294967295, 
# |                    34, 35, 4294967295 ]
# | OutputProps:
# |   Height:          0
# |   Width:           0
# |   Depth:           0
# | ...
# | 
# `-----------------------------
```

See https://github.com/llvm/offload-test-suite/pull/210 for more context

### PR DESCRIPTION
**Pull request by joaosaffran**
This patch fixes the logic when lowering firsbithigh and low when targeting spirv. It adds an aditional check to make sure the second half is also -1, if it is it returns -1 otherwise returns the resulting sum.

Fix: #143003 and #143171

### CODE REVIEW

**Review by V-FEXrt — COMMENTED** [review]
Looking at the test code, I'm not convinced this code actually does anything differently?

For example, you could remap the `firstbituhigh_i64` test to something ala

```
i32x2 parts = split(i64 a)
i32x2 umsb = FindUsb(i32x2 parts)
if (umsb[0] == -1) return umsb[1];
return umsb[0] + 32;
```

while the new code is doing something ala
```
i32x2 parts = split(i64 a)
i32x2 umsb = FindUsb(i32x2 parts)
i32 ans = undef
if (umsb[1] == -1) ans = umsb[0]
else ans = umsb[1]
if (ans == -1) return -1
return ans + (32 if umsb[1] == -1 else 0)
```

which seems more complicated but doesn't actually seem to be doing anything differently than the first case. The extra -1 check should be redundant since the -1 value already in the register should just be fine to return. The `+ 32` seems like it could mess that up except (in the original) we only add 32 when we know its not -1

**Review by V-FEXrt — APPROVED** [review]

File: llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp [hunk 1]
```diff
@@ -5408,7 +5408,7 @@ bool SPIRVInstructionSelector::selectFirstBitSet64(
               .addUse(FBSReg);
 
     // low bits are stored in odd indexes. Extract them from FBSReg
```
Comment (inbelic) [inline llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp]: nit:
```suggestion
    // low bits are stored in odd natural indices. Extract them from FBSReg
```
or `odd natural -> even` so the comment matches.

Same with above.

**Review by inbelic — APPROVED** [review]
LGTM.

Nit, add something like the following to the PR description:

From the SPIRV spec of [`OpBitcast`](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpBitcast):

>  Within this mapping, any single component of S (mapping to multiple components of L) maps its lower-ordered bits to the lower-numbered components of L.

where `L = 2 x u32` and `S = u64`. `OpBitcast` also operates on the logical bits and is endianness agnostic.

This PR updates the behaviour to map the least significant bits to the lowest-component.
