### PR TITLE
[clang] fix crash with c-style casts involving dependent member-pointer types

### LINKED ISSUE #194524: Clang crashes in `ASTContext::UnwrapSimilarTypes()`
Clang crashes when compiling the following code:
```
struct Base
{
	typedef void (Base::*Func)(void);
};

template <class T>
struct Sub
{
	typedef void (T::*TFunc)(void);
	Sub(TFunc tfunc){
		(Base::Func&)tfunc;
	}
};
```
Godbolt: https://godbolt.org/z/fzvoGWK7W
Bisected PR: #132401

Backtrace:

```console
#0 0x000000000453c1b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x453c1b8)
 #1 0x0000000004538fe4 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4538fe4)
 #2 0x0000000004539604 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4539604)
 #3 0x0000000004476d88 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #4 0x00007eba19042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x0000000007e6dca7 clang::ASTContext::UnwrapSimilarTypes(clang::QualType&, clang::QualType&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7e6dca7)
 #6 0x00000000070566c0 CastsAwayConstness(clang::Sema&, clang::QualType, clang::QualType, bool, bool, clang::QualType*, clang::QualType*, clang::Qualifiers*) SemaCast.cpp:0:0
 #7 0x000000000705bf8b DiagnoseCastQual(clang::Sema&, clang::ActionResult<clang::Expr*, true> const&, clang::QualType) SemaCast.cpp:0:0
 #8 0x0000000007064929 clang::Sema::BuildCStyleCastExpr(clang::SourceLocation, clang::TypeSourceInfo*, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7064929)
 #9 0x00000000073c30db clang::Sema::ActOnCastExpr(clang::Scope*, clang::SourceLocation, clang::Declarator&, clang::OpaquePtr<clang::QualType>&, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x73c30db)
#10 0x0000000006ec3614 clang::Parser::ParseParenExpression(clang::ParenParseOption&, bool, clang::ParenExprKind, clang::TypoCorrectionTypeBehavior, clang::OpaquePtr<clang::QualType>&, clang::SourceLocation&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec3614)
#11 0x0000000006eb989d clang::Parser::ParseCastExpression(clang::CastParseKind, bool, bool&, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6eb989d)
#12 0x0000000006ebaa47 clang::Parser::ParseCastExpression(clang::CastParseKind, bool, clang::TypoCorrectionTypeBehavior, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ebaa47)
#13 0x0000000006ebaad9 clang::Parser::ParseAssignmentExpression(clang::TypoCorrectionTypeBehavior) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ebaad9)
#14 0x0000000006ebf119 clang::Parser::ParseExpression(clang::TypoCorrectionTypeBehavior) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ebf119)
#15 0x0000000006f46489 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f46489)
#16 0x0000000006f3d8b4 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f3d8b4)
#17 0x0000000006f3e299 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::LabelDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f3e299)
#18 0x0000000006f46c0e clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f46c0e)
#19 0x0000000006f4742a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f4742a)
#20 0x0000000006e5ab40 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e5ab40)
#21 0x0000000006e5a82d clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e5a82d)
#22 0x0000000006eae816 clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6eae816)
#23 0x0000000006eb102b clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6eb102b)
#24 0x0000000006e84849 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e84849)
#25 0x0000000006f53379 clang::Parser::ParseDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f53379)
#26 0x0000000006f60c39 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (.part.0) ParseTemplate.cpp:0:0
#27 0x0000000006f6104a clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f6104a)
#28 0x0000000006e8b7d0 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e8b7d0)
#29 0x0000000006e47a46 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e47a46)
#30 0x0000000006e48955 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e48955)
#31 0x0000000006e2981a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e2981a)
#32 0x000000000504f028 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x504f028)
#33 0x000000000536e3c5 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x536e3c5)
#34 0x00000000052ecfb8 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52ecfb8)
#35 0x000000000546a8bd clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x546a8bd)
#36 0x0000000000deb3cb cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdeb3cb)
#37 0x0000000000de1d2a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#38 0x0000000000de1ead int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#39 0x00000000050b9229 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#40 0x00000000044771c4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44771c4)
#41 0x00000000050b9856 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#42 0x0000000005077ea2 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5077ea2)
#43 0x0000000005078e4e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5078e4e)
#44 0x0000000005080af5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5080af5)
#45 0x0000000000de7754 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde7754)
#46 0x0000000000c9fd2a main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc9fd2a)
#47 0x00007eba19029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#48 0x00007eba19029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#49 0x0000000000de17c5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xde17c5)
```

### PR DESCRIPTION
**Pull request by mizvekov**
A dependent member-pointer type doesn't necessarily have a class declaration.

This simplifies the check performed in a helper for diagnosing a cast which removes qualifiers, so it doesn't rely on this assumption.

This fixes a regression introduced in https://github.com/llvm/llvm-project/pull/132401, which landed in the last release, and this will be back ported, so no release notes.

Fixes #194524

### CODE REVIEW

File: clang/lib/AST/ASTContext.cpp [hunk 1]
```diff
@@ -7198,18 +7198,13 @@ bool ASTContext::UnwrapSimilarTypes(QualType &T1, QualType &T2,
     return true;
   }
 
-  if (const auto *T1MPType = T1->getAs<MemberPointerType>(),
-      *T2MPType = T2->getAs<MemberPointerType>();
+  if (const auto *T1MPType = T1->getAsCanonical<MemberPointerType>(),
+      *T2MPType = T2->getAsCanonical<MemberPointerType>();
```
Comment (cor3ntin) [inline clang/lib/AST/ASTContext.cpp:7202]: This is subtle, can you add a comment? thanks

**Review by cor3ntin — APPROVED** [review]
LGTM

**Review by shafik — COMMENTED** [review]
Thank you for the quick fix!
