### PR TITLE
Fix assertion of null pointer samples in inline replay mode

### LINKED ISSUE #97108: llvm/test/Transforms/SampleProfile/csspgo-import-list.ll fails in -DLLVM_ENABLE_EXPENSIVE_CHECKS=on builds
The test fails in `-DLLVM_ENABLE_EXPENSIVE_CHECKS=on -DLLVM_ENABLE_ASSERTIONS=on` builds, both Debug and Release.

At `llvm/lib/Transforms/IPO/SampleProfile.cpp:1420`, the initialized `NewCandidate` may have a `null` `CalleeSamples`, leading to `assert(LCS && RCS && "Expect non-null FunctionSamples"); ` failure in `(anonymous namespace)::CandidateComparer::operator()`

@WenleiHe

### PR DESCRIPTION
**Pull request by wlei-llvm**
Fix https://github.com/llvm/llvm-project/issues/97108. In inline replay mode, `CalleeSamples` may be null and the order doesn't matter.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]

File: llvm/lib/Transforms/IPO/SampleProfile.cpp [hunk 1]
```diff
@@ -439,7 +439,10 @@ struct CandidateComparer {
 
     const FunctionSamples *LCS = LHS.CalleeSamples;
     const FunctionSamples *RCS = RHS.CalleeSamples;
-    assert(LCS && RCS && "Expect non-null FunctionSamples");
+    // In inline replay mode, CalleeSamples may be null and the order doesn't
+    // matter.
+    if (!LCS || !RCS)
+      return false;
```
Comment (WenleiHe) [inline llvm/lib/Transforms/IPO/SampleProfile.cpp:445]: I think we should give a deterministic order when only one side is null. With the current change, "non-null" vs "null" and "null" vs "non-null" both are false..

**Review by WenleiHe — APPROVED** [review]
lgtm, thanks.
