### PR TITLE
[mlir][index][spirv] Add conversion for index to spirv

### LINKED ISSUE #63713: [mlir][spirv] Support index to spir-v dialect conversion
Right now MLIR seems to only support index to llvm conversion. We should also support it on the spirv lowering path.

There's already one related user request / bug report on Discourse: https://discourse.llvm.org/t/need-help-in-better-understanding-scf-to-spir-v-lowering/71639:

```mlir
func.func @forward() {
    %c0 = arith.constant 0 : index
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    scf.for %arg2 = %c0 to %c32 step %c1 {
        %1 = index.add %arg2, %arg2
    }
    return
}
```

### PR DESCRIPTION
**Pull request by inbelic**
Due to an issue when lowering from scf to spirv as there was no conversion pass for index to spirv, we are motivated to add a conversion pass from the Index dialect to the SPIR-V dialect. Furthermore, we add the new conversion patterns to the scf-to-spirv conversion.

Fixes #63713

### CODE REVIEW

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp [hunk 1]
```diff
@@ -693,6 +693,8 @@ SPIRVTypeConverter::SPIRVTypeConverter(spirv::TargetEnvAttr targetAttr,
   addConversion([this](IndexType /*indexType*/) { return getIndexType(); });
 
   addConversion([this](IntegerType intType) -> std::optional<Type> {
+    if (!this->options.convertIntAsScalar)
```
Comment (inbelic) [inline mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:696]: The use of this hidden option is currently a hack solution, as when we pass in the integer type we fail the linked check, which will then cause us to return a `nullptr`. Proper implementation would presumably ensure that we are passing the compatibility and extension requirements. So hints for how to solve this are needed.

https://github.com/llvm/llvm-project/blame/77c43e14897a404fbf4a132a1a75d49ba2ec08c1/mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp#L232-L235.

**Comment by kuhar** [comment]
Awesome, I will take a look after I'm done with the LLVM Dev Mtg and the OpenXLA summit. Apologies for the delay.

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp (hunk 1 above)
Comment (kuhar) [reply mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:696]: Can't we resolve this by adding a module with the right target env around the code in test cases? Have you checked where the `const spirv::TargetEnv &targetEnv` parameter in comes from in `convertScalarType`?

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 2]
```diff
@@ -0,0 +1,418 @@
...
+
+using ConvertIndexShl =
+    spirv::ElementwiseOpPattern<ShlOp, spirv::ShiftLeftLogicalOp>;
+using ConvertIndexShrS =
+    spirv::ElementwiseOpPattern<ShrSOp, spirv::ShiftRightArithmeticOp>;
+using ConvertIndexShrU =
+    spirv::ElementwiseOpPattern<ShrUOp, spirv::ShiftRightLogicalOp>;
+
+/// It is the case that when we convert bitwise operations to SPIR-V operations
+/// we must take into account of the special pattern in SPIR-V that if the
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:47]:
```suggestion
/// we must take into account the special pattern in SPIR-V that if the
```

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 3]
```diff
@@ -0,0 +1,418 @@
...
+/// operands are boolean values, then SPIR-V uses `SPIRVLogicalOp`. Otherwise,
+/// for non-boolean operands, SPIR-V should use `SPIRVBitwiseOp`. However,
+/// index.add is never a boolean operation so we can directly convert it to the
+/// Bitwise[And|Or]Op
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:51]:
```suggestion
/// Bitwise[And|Or]Op.
```

Comment (kuhar) [reply mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:51]: This comment is very helpful, thank you!

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 4]
```diff
@@ -0,0 +1,418 @@
...
+// Converts index.bool.constant operation to spirv.Constant.
+struct ConvertIndexConstantBoolOpPattern final
+    : OpConversionPattern<BoolConstantOp> {
+  using OpConversionPattern::OpConversionPattern;
+
+  LogicalResult
+  matchAndRewrite(BoolConstantOp op, BoolConstantOpAdaptor adaptor,
+                  ConversionPatternRewriter &rewriter) const override {
+    rewriter.replaceOpWithNewOp<spirv::ConstantOp>(op, op.getType(),
+                                                   op->getAttr("value"));
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:69]: They don't have a nicer getter for the attribute? If this is the case, maybe we should add one.

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 5]
```diff
@@ -0,0 +1,418 @@
...
+    return success();
+  }
+};
+
+//===----------------------------------------------------------------------===//
+// ConvertIndexCeilDivS
+//===----------------------------------------------------------------------===//
+
+/// Convert `ceildivs(n, m)` into `x = m > 0 ? -1 : 1` and then
+/// `n*m > 0 ? (n+x)/m + 1 : -(-n/m)`.
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:101]: Did you derive these on your own or found some existing reference?

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 6]
```diff
@@ -0,0 +1,418 @@
...
+    rewriter.replaceOpWithNewOp<spirv::SelectOp>(op, cmp, posRes, negRes);
+    return success();
+  }
+};
+
+//===----------------------------------------------------------------------===//
+// ConvertIndexCeilDivU
+//===----------------------------------------------------------------------===//
+
+/// Convert `ceildivu(n, m)` into `n == 0 ? 0 : (n-1)/m + 1`.
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:150]: Same for the other division patterns.

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 7]
```diff
@@ -0,0 +1,418 @@
...
+//===----------------------------------------------------------------------===//
+// ConvertIndexCast
+//===----------------------------------------------------------------------===//
+
+/// Convert a cast op. If the materialized index type is the same as the other
+/// type, fold away the op. Otherwise, use the Convert SPIR-V operation.
+/// Signed casts sign extend when the result bitwidth is larger. Unsigned casts
+/// zero extend when the result bitwidth is larger.
+template <typename CastOp, typename ConvertOp>
+struct ConvertIndexCast : public OpConversionPattern<CastOp> {
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:238]:
```suggestion
struct ConvertIndexCast final : OpConversionPattern<CastOp> {
```

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp [hunk 8]
```diff
@@ -0,0 +1,418 @@
...
+struct ConvertIndexToSPIRVPass
+    : public impl::ConvertIndexToSPIRVPassBase<ConvertIndexToSPIRVPass> {
+  using Base::Base;
+
+  void runOnOperation() override;
+};
+} // namespace
+
+void ConvertIndexToSPIRVPass::runOnOperation() {
+  Operation *op = getOperation();
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp:394]: nit: Could we inline this? I don't see value in this function declaration/definition separation.

**Review by kuhar — COMMENTED** [review]
Looks solid, I'd just like to confirm if we need the hack for scalar types.

Also, is type converter allowed to fail in `getIndexType()`? If we yes, we are missing nullptr checks for failed index queries. My guess is that for any reasonable type converter for SPIR-V, i32 should be always available.

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp (hunk 4 above)
Comment (inbelic) [reply mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp]: They do have a better getter, updated.

File: mlir/include/mlir/Conversion/IndexToSPIRV/IndexToSPIRV.h [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
+// See https://llvm.org/LICENSE.txt for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+#ifndef MLIR_CONVERSION_INDEXTOSPIRV_INDEXTOSPIRV_H
+#define MLIR_CONVERSION_INDEXTOSPIRV_INDEXTOSPIRV_H
+
+#include <memory>
```
[the remark this answers is not in the document]
Comment (inbelic) [reply mlir/include/mlir/Conversion/IndexToSPIRV/IndexToSPIRV.h:13]: IIRC, I added this because it is required when we include `Passes.h.inc` below. I have updated to include the declaration that requires it to this header as well to make it clear.

File: mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp (hunk 8 above)
Comment (inbelic) [reply mlir/lib/Conversion/IndexToSPIRV/IndexToSPIRV.cpp]: Have removed the use of the hack and the options. It was solved by adding `Int64` to the list of capabilities of the SPIRV Target Environment in the test case.

Regarding `getIndexType`, it will determine if we are using a 32 or 64 and then return `IntegerType::get(...)`. Under the assumption that `IntegerType::get(...)` is not allowed to fail then the index will not either. I believe that is the case? Is there any pattern that denotes if a function is allowed to fail or not?

**Comment by inbelic** [comment]
Have removed the use of the hack and the options. It was solved by adding Int64 to the list of capabilities of the SPIRV Target Environment in the test case.

Regarding getIndexType, it will determine if we are using a 32 or 64 and then return IntegerType::get(...). Under the assumption that IntegerType::get(...) is not allowed to fail then the index will not either. I believe that is the case? Is there any pattern that denotes if a function is allowed to fail or not?

**Comment by kuhar** [comment]
> Regarding getIndexType, it will determine if we are using a 32 or 64 and then return `IntegerType::get(...)`. Under the assumption that `IntegerType::get(...)` is not allowed to fail then the index will not either. I believe that is the case? Is there any pattern that denotes if a function is allowed to fail or not?

OK, SGTM, thanks for checking.

**Comment by kuhar** [comment]
> I believe that is the case? Is there any pattern that denotes if a function is allowed to fail or not?

In general things that return `Value`/`Type` may return nullptr. This is definitely the case for `convertType(...)`. For `getIndexType` I think it's reasonable to assume success.

**Review by kuhar — APPROVED** [review]
LGTM. Could you rebase the code before we merge this, @inbelic?

**Comment by joker-eph** [comment]
Seems like this broke the bot: https://lab.llvm.org/buildbot/#/builders/61/builds/50716

**Comment by kuhar** [comment]
Thanks for surfacing, @joker-eph. Reverted in https://github.com/llvm/llvm-project/commit/8b02ceb133341ea6d3e140d0c73ef252fa11415c.

@inbelic could you take a look at this buildbot failure?

**Comment by inbelic** [comment]
@kuhar Yep, starting to investigate now.

**Comment by inbelic** [comment]
Was unable to reproduce the build error locally, but my guess is that the commit was missing the SPIR-V dialect in our linked libs of the CMake file, new commit is related to that. Need some help to verify that this is the case. Is there a way to test the build on a given branch/pr?

File: mlir/lib/Conversion/IndexToSPIRV/CMakeLists.txt [hunk 10]
```diff
@@ -0,0 +1,15 @@
...
+  ${MLIR_MAIN_INCLUDE_DIR}/mlir/Conversion/IndexToSPIRV
+
+  DEPENDS
+  MLIRConversionPassIncGen
+
+  LINK_COMPONENTS
+  Core
+
+  LINK_LIBS PUBLIC
+  MLIRIndexDialect
```
Comment (kuhar) [inline mlir/lib/Conversion/IndexToSPIRV/CMakeLists.txt:14]: Bazel is better at checking build deps. Since there's already a PR adding bazel rules, can we link with the same set of libs as bazel https://github.com/llvm/llvm-project/pull/69743/files?

Also, we can cherry-pick the bazel changes and land this in one go. (We should wake sure *not* to squash during code review so that the author of the bazel patch gets properly attributes when we hit 'merge',)

**Comment by kuhar** [comment]
> Was unable to reproduce the build error locally, but my guess is that the commit was missing the SPIR-V dialect in our linked libs of the CMake file, new pull request #69790 adds this. Need some help to verify that this is the case. Is there a way to test the build on a given branch/pr?

This should be reproducible with `-DBUILD_SHARED_LIBS=1`: https://lab.llvm.org/buildbot/#/builders/61/builds/50716/steps/4/logs/stdio
