### PR TITLE
Remove delayed typo expressions

### LINKED ISSUE #23312: Assertion failed: (DelayedTypos.empty() && "Uncorrected typos!"), function ~Sema
|  |  |
| --- | --- |
| Bugzilla Link | [22938](https://llvm.org/bz22938) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @rnk |

## Extended Description 
Assertion failed: (DelayedTypos.empty() && "Uncorrected typos!"), function ~Sema, file /Users/w/clang-llvm/llvm/tools/clang/lib/Sema/Sema.cpp, line 250.

Still trying to isolate the root cause.  This happens parsing the AST of many files using RecursiveASTVisitor.  

Setup info
----------
uname: Darwin 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

git: trunk as of 2015.03.17

### LINKED ISSUE #32903: clang hangs on provided C example code
|  |  |
| --- | --- |
| Bugzilla Link | [33556](https://llvm.org/bz33556) |
| Version | trunk |
| OS | All |
| Attachments | [top function and called one with wrong parameters.](https://user-images.githubusercontent.com/60944935/143755871-fadd196a-c570-4428-b49c-19f8065b253e.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@DimitryAndric |

## Extended Description 

clang hangs with provided simple example , likely because of too many function parameters. verified with domestic clang v #&#8203;3.8.0  also some other online of the same version.

to reproduce run
clang hang.cpp

thanks

### LINKED ISSUE #58172: clang frontend crash
version: 15.0.1

[source_and_script.tar.gz](https://github.com/llvm/llvm-project/files/9719102/source_and_script.tar.gz)

stacktrace:
```
 #0 0x000055ec4db8f733 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/bin/clang-15+0x34f1733)
 #1 0x000055ec4db8d0ee llvm::sys::RunSignalHandlers() (/usr/bin/clang-15+0x34ef0ee)
 #2 0x000055ec4db8fe7f SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f9ca4b8d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x000055ec507baf39 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/bin/clang-15+0x611cf39)
 #5 0x000055ec50a2097e clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) (/usr/bin/clang-15+0x638297e)
 #6 0x000055ec501efeae clang::Parser::ParseReturnStatement() (/usr/bin/clang-15+0x5b51eae)
 #7 0x000055ec501e80db clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/bin/clang-15+0x5b4a0db)
 #8 0x000055ec501e75bf clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/bin/clang-15+0x5b495bf)
 #9 0x000055ec501f2491 clang::Parser::ParseCompoundStatementBody(bool) (/usr/bin/clang-15+0x5b54491)
#10 0x000055ec501e7f09 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/bin/clang-15+0x5b49f09)
#11 0x000055ec501e75bf clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/bin/clang-15+0x5b495bf)
#12 0x000055ec501ec9ae clang::Parser::ParseIfStatement(clang::SourceLocation*) (/usr/bin/clang-15+0x5b4e9ae)
#13 0x000055ec501e80cb clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/bin/clang-15+0x5b4a0cb)
#14 0x000055ec501e75bf clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/bin/clang-15+0x5b495bf)
#15 0x000055ec501f2491 clang::Parser::ParseCompoundStatementBody(bool) (/usr/bin/clang-15+0x5b54491)
#16 0x000055ec501f3d40 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/bin/clang-15+0x5b55d40)
#17 0x000055ec501c953b clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/bin/clang-15+0x5b2b53b)
#18 0x000055ec5021ef37 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/bin/clang-15+0x5b80f37)
#19 0x000055ec501c7c6d clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/bin/clang-15+0x5b29c6d)
#20 0x000055ec501c774e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/bin/clang-15+0x5b2974e)
#21 0x000055ec501c673b clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/bin/clang-15+0x5b2873b)
#22 0x000055ec501c4310 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/bin/clang-15+0x5b26310)
#23 0x000055ec501befde clang::ParseAST(clang::Sema&, bool, bool) (/usr/bin/clang-15+0x5b20fde)
#24 0x000055ec4e8504e2 clang::FrontendAction::Execute() (/usr/bin/clang-15+0x41b24e2)
#25 0x000055ec4e7af9c2 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/bin/clang-15+0x41119c2)
#26 0x000055ec4e92bed3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/bin/clang-15+0x428ded3)
#27 0x000055ec4c568e33 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-15+0x1ecae33)
#28 0x000055ec4c566dd7 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#29 0x000055ec4c5669bc clang_main(int, char**) (/usr/bin/clang-15+0x1ec89bc)
#30 0x00007f9ca46dd083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#31 0x000055ec4c562eee _start (/usr/bin/clang-15+0x1ec4eee)
```

### LINKED ISSUE #59391: Clang crash on deduced type with typo correction
```cpp
namespace a {
template <typename b> class c {
  c(b);
  b e;
  class d {
    void f() {
      auto x = a::c(cores);
      for (auto core : a::c(cores)) {
      }
    }
  };
};
} // namespace a
```

is a reproducer for clang with `-std=c++17`.
Assertion that fires and the stack trace:

```console
$ clang -xc++ -fsyntax-only test_it.cc -std=c++17
test_it.cc:7:21: error: use of undeclared identifier 'cores'
      auto x = a::c(cores);
                    ^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang-14 -xc++ -c -Xclang -ast-dump test_it.cc -std=c++17 -Xclang -fno-recovery-ast
1.      test_it.cc:8:37: current parser token '{'
2.      test_it.cc:1:1: parsing namespace 'a'
3.      test_it.cc:2:23: parsing struct/union/class body 'a::c'
4.      test_it.cc:6:14: parsing function body 'a::c::d::f'
5.      test_it.cc:6:14: in compound statement ('{}')
 #0 0x00007ffa34aa2671 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea2671)
 #1 0x00007ffa34aa03ce llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea03ce)
 #2 0x00007ffa34aa1a3b llvm::sys::CleanupOnSignal(unsigned long) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xea1a3b)
 #3 0x00007ffa349c98ef (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xdc98ef)
 #4 0x00007ffa3343daa0 (/lib/x86_64-linux-gnu/libc.so.6+0x3daa0)
 #5 0x00007ffa3b114d83 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb14d83)
 #6 0x00007ffa3b115cf6 clang::ASTContext::getTypeInfo(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb15cf6)
 #7 0x00007ffa3b114d8e clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb14d8e)
 #8 0x00007ffa3b115cf6 clang::ASTContext::getTypeInfo(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb15cf6)
 #9 0x00007ffa3b1159b9 clang::ASTContext::getTypeInfoInChars(clang::QualType) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb159b9)
#10 0x00007ffa3b4607c4 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xe607c4)
#11 0x00007ffa3b45cd76 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xe5cd76)
#12 0x00007ffa3b45821d clang::ASTContext::getASTRecordLayout(clang::RecordDecl const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xe5821d)
#13 0x00007ffa3b114e6c clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb14e6c)
#14 0x00007ffa3b115cf6 clang::ASTContext::getTypeInfo(clang::Type const*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb15cf6)
#15 0x00007ffa3b1163e3 clang::ASTContext::getTypeAlignInChars(clang::QualType) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xb163e3)
#16 0x00007ffa3b7e2eaa clang::Sema::CheckArgAlignment(clang::SourceLocation, clang::NamedDecl*, llvm::StringRef, clang::QualType, clang::QualType) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x11e2eaa)
#17 0x00007ffa3b7e4b5f clang::Sema::CheckConstructorCall(clang::FunctionDecl*, clang::QualType, llvm::ArrayRef<clang::Expr const*>, clang::FunctionProtoType const*, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x11e4b5f)
#18 0x00007ffa3b964d72 clang::Sema::CompleteConstructorCall(clang::CXXConstructorDecl*, clang::QualType, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, llvm::SmallVectorImpl<clang::Expr*>&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1364d72)
#19 0x00007ffa3bb6a075 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x156a075)
#20 0x00007ffa3bb66534 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x1566534)
#21 0x00007ffa3b7cd53d (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x11cd53d)
#22 0x00007ffa3b7c8d28 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x11c8d28)
#23 0x00007ffa3b7c8e2a clang::Sema::BuildCXXFunctionalCastExpr(clang::TypeSourceInfo*, clang::QualType, clang::SourceLocation, clang::Expr*, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x11c8e2a)
#24 0x00007ffa3bab9b8d clang::Sema::BuildCXXTypeConstructExpr(clang::TypeSourceInfo*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x14b9b8d)
#25 0x00007ffa3badc185 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x14dc185)
#26 0x00007ffa3bad4f88 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x14d4f88)
#27 0x00007ffa3bab9e25 clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x14b9e25)
#28 0x00007ffa3b0d6a4b clang::Parser::ParseForStatement(clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xad6a4b)
#29 0x00007ffa3b0d1910 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xad1910)
#30 0x00007ffa3b0d0eef clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xad0eef)
#31 0x00007ffa3b0d9841 clang::Parser::ParseCompoundStatementBody(bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xad9841)
#32 0x00007ffa3b0da768 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xada768)
#33 0x00007ffa3b0387d1 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa387d1)
#34 0x00007ffa3b03729a clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa3729a)
#35 0x00007ffa3b03729a clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa3729a)
#36 0x00007ffa3b06a56b clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesWithRange&, unsigned int, clang::Decl*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa6a56b)
#37 0x00007ffa3b067c26 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributesWithRange&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa67c26)
#38 0x00007ffa3b0477a4 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa477a4)
#39 0x00007ffa3b0e221a clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xae221a)
#40 0x00007ffa3b0e14fd clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xae14fd)
#41 0x00007ffa3b0e0e4f clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xae0e4f)
#42 0x00007ffa3b04669b clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributesWithRange&, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa4669b)
#43 0x00007ffa3b0f1bc4 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xaf1bc4)
#44 0x00007ffa3b060c0c clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa60c0c)
#45 0x00007ffa3b060759 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa60759)
#46 0x00007ffa3b0467de clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributesWithRange&, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa467de)
#47 0x00007ffa3b0f1bc4 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xaf1bc4)
#48 0x00007ffa3b0f0a6d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xaf0a6d)
#49 0x00007ffa3b0f05d7 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xaf05d7)
#50 0x00007ffa3b033726 clang::ParseAST(clang::Sema&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0xa33726)
#51 0x00007ffa3cb44ac7 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x2544ac7)
#52 0x00007ffa3ca9c316 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x249c316)
#53 0x00007ffa3cbbe43b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x25be43b)
#54 0x0000000000413edb cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-14/bin/clang+0x413edb)
#55 0x000000000041210c (/usr/lib/llvm-14/bin/clang+0x41210c)
#56 0x00007ffa3c71ab92 (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x211ab92)
#57 0x00007ffa349c965d llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xdc965d)
#58 0x00007ffa3c71a680 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x211a680)
#59 0x00007ffa3c6e4e83 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x20e4e83)
#60 0x00007ffa3c6e510a clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x20e510a)
#61 0x00007ffa3c6ff1c7 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/lib/x86_64-linux-gnu/libclang-cpp.so.14+0x20ff1c7)
#62 0x0000000000411b76 main (/usr/lib/llvm-14/bin/clang+0x411b76)
#63 0x00007ffa3342920a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#64 0x00007ffa334292bc call_init ./csu/../csu/libc-start.c:128:20
#65 0x00007ffa334292bc __libc_start_main ./csu/../csu/libc-start.c:376:5
#66 0x000000000040f00a _start (/usr/lib/llvm-14/bin/clang+0x40f00a)
```

### LINKED ISSUE #69470: clang: Assertion 'idx < size()' failed. In function `clang::Sema::tryCaptureVariable`
The link for quick verification: https://gcc.godbolt.org/z/Y8EWoxv13

The bug triggering program (with option `-fopenmp-simd`):
```
int (^a) (int i, int j) = ^(int i, int j)
{ return i / j; }/ j;
```

Stack dump is pasted below:
```
<source>:1:6: error: blocks support disabled - compile with -fblocks or pick a deployment target that supports them
    1 | int (^a) (int i, int j) = ^(int i, int j)
      |      ^
<source>:1:27: error: blocks support disabled - compile with -fblocks or pick a deployment target that supports them
    1 | int (^a) (int i, int j) = ^(int i, int j)
      |                           ^
<source>:2:20: error: use of undeclared identifier 'j'
    2 | { return i / j; }/ j;
      |                    ^
clang: /root/llvm-project/llvm/include/llvm/ADT/SmallVector.h:294: T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) [with T = clang::sema::FunctionScopeInfo*; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::reference = clang::sema::FunctionScopeInfo*&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics -fopenmp-simd <source>
1.	<source>:2:21: current parser token ';'
 #0 0x00000000037346b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x37346b8)
 #1 0x000000000373237c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x373237c)
 #2 0x000000000367ac28 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fa357695420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fa35715800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007fa357137859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007fa357137729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007fa357148fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x00000000063f5033 clang::Sema::tryCaptureVariable(clang::ValueDecl*, clang::SourceLocation, clang::Sema::TryCaptureKind, clang::SourceLocation, bool, clang::QualType&, clang::QualType&, unsigned int const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63f5033)
 #9 0x00000000063f5411 clang::Sema::getCapturedDeclRefType(clang::ValueDecl*, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x63f5411)
#10 0x0000000006428471 clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::NamedDecl*, clang::TemplateArgumentListInfo const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6428471)
#11 0x0000000006560260 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformDeclRefExpr(clang::DeclRefExpr*) SemaExprCXX.cpp:0:0
#12 0x0000000006562b08 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformBinaryOperator(clang::BinaryOperator*) SemaExprCXX.cpp:0:0
#13 0x0000000006560ef8 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformInitializer(clang::Expr*, bool) (.part.0) SemaExprCXX.cpp:0:0
#14 0x000000000656127c clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformReturnStmt(clang::ReturnStmt*) SemaExprCXX.cpp:0:0
#15 0x0000000006576cb4 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaExprCXX.cpp:0:0
#16 0x000000000657973c clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformBlockExpr(clang::BlockExpr*) SemaExprCXX.cpp:0:0
#17 0x0000000006562b08 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformBinaryOperator(clang::BinaryOperator*) SemaExprCXX.cpp:0:0
#18 0x000000000654f13d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x654f13d)
#19 0x000000000620d29c clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x620d29c)
#20 0x0000000005ed15e3 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ed15e3)
#21 0x0000000005edecb0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5edecb0)
#22 0x0000000005eac30b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eac30b)
#23 0x0000000005eaca3f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#24 0x0000000005eb43e4 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eb43e4)
#25 0x0000000005eb4c0d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eb4c0d)
#26 0x0000000005eb5050 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eb5050)
#27 0x0000000005ea7c82 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ea7c82)
#28 0x00000000049a0c78 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49a0c78)
#29 0x00000000042046a9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x42046a9)
#30 0x0000000004185b4e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4185b4e)
#31 0x00000000042e382e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x42e382e)
#32 0x0000000000bf0b06 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbf0b06)
#33 0x0000000000be83ca ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#34 0x0000000003fe1d39 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#35 0x000000000367b0d4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x367b0d4)
#36 0x0000000003fe232f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#37 0x0000000003faa4f5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3faa4f5)
#38 0x0000000003faaf5d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3faaf5d)
#39 0x0000000003fb2e85 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fb2e85)
#40 0x0000000000bedfac clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbedfac)
#41 0x0000000000ae8141 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xae8141)
#42 0x00007fa357139083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#43 0x0000000000be7eae _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbe7eae)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

### LINKED ISSUE #69874: clang: 18: Assertion `isLValue()' failed.
Compiler Explorer: https://gcc.godbolt.org/z/n87aPY7rP

When compile this program, clang crashes:
```
void f(void) {
  *a = (a_struct){0};
}
```

Interestingly, renaming `a_struct` in the program appears to prevent the crash. For instance, changing `a_struct` to another name, such as `T`, seems to eliminate the issue:
```
void f(void) {
  *a = (T){0};
}
```

The stack dump:
```
<source>:2:9: error: use of undeclared identifier 'a_struct'; did you mean 'struct'?
    2 |   *a = (a_struct){0};
      |         ^~~~~~~~
      |         struct
clang: /root/llvm-project/clang/lib/AST/ExprClassification.cpp:57: Cl clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const: Assertion `isLValue()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:2:18: current parser token '{'
2.	<source>:1:14: parsing function body 'f'
3.	<source>:1:14: in compound statement ('{}')
 #0 0x0000000003742c08 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3742c08)
 #1 0x00000000037408cc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x37408cc)
 #2 0x0000000003689278 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f6722cd5420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f672279800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f6722777859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f6722777729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f6722788fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000006fc23f4 clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6fc23f4)
 #9 0x0000000006fc25bd clang::Expr::isModifiableLvalue(clang::ASTContext&, clang::SourceLocation*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6fc25bd)
#10 0x00000000063f50e9 CheckForModifiableLvalue(clang::Expr*, clang::SourceLocation, clang::Sema&) SemaExpr.cpp:0:0
#11 0x0000000006453557 clang::Sema::CheckAssignmentOperands(clang::Expr*, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, clang::QualType, clang::BinaryOperatorKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6453557)
#12 0x0000000006454ba3 clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6454ba3)
#13 0x0000000006456565 clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6456565)
#14 0x00000000064566e3 clang::Sema::ActOnBinOp(clang::Scope*, clang::SourceLocation, clang::tok::TokenKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x64566e3)
#15 0x0000000005f1b1fb clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f1b1fb)
#16 0x0000000005f1e759 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f1e759)
#17 0x0000000005f99397 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f99397)
#18 0x0000000005f8fa2d clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f8fa2d)
#19 0x0000000005f90868 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f90868)
#20 0x0000000005f917a9 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f917a9)
#21 0x0000000005f930ca clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f930ca)
#22 0x0000000005ec0d71 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ec0d71)
#23 0x0000000005ee8288 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ee8288)
#24 0x0000000005eb51db clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eb51db)
#25 0x0000000005eb590f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#26 0x0000000005ebd2b4 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ebd2b4)
#27 0x0000000005ebdadd clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ebdadd)
#28 0x0000000005ebdf20 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ebdf20)
#29 0x0000000005eb0b52 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eb0b52)
#30 0x00000000049aa318 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49aa318)
#31 0x000000000420eee9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x420eee9)
#32 0x00000000041902de clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x41902de)
#33 0x00000000042edf3e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x42edf3e)
#34 0x0000000000bf1286 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbf1286)
#35 0x0000000000be8b4a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#36 0x0000000003fec189 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#37 0x0000000003689724 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3689724)
#38 0x0000000003fec77f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#39 0x0000000003fb4625 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fb4625)
#40 0x0000000003fb508d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fb508d)
#41 0x0000000003fbcfb5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fbcfb5)
#42 0x0000000000bee72c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbee72c)
#43 0x0000000000ae8071 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xae8071)
#44 0x00007f6722779083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#45 0x0000000000be862e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbe862e)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

### LINKED ISSUE #93308: [clang++] extremely slow when trying to use undeclared identifiers
Given a program in the following format:
```cpp
void test() {
  int a11;
  [...]  // a bunch more  variable declarations not used afterwards
  
  if( a97 == a95 ) {}  // comparing non-existant variables
}
```

`clang++` can take up to 5 minutes compiling this or even crashes, while `clang` can compile it just fine.

<details>
<summary>Full code example</summary>

```cpp
void test() {
  int  a11;
  int  a12;
  int  a13;
  int  a14;
  int* a15;
  int  a16;
  int  a17;
  int  a18;
  int  a22;
  int  a24;
  int  a25;
  int  a35;
  int  a36;
  int  a37;
  int  a38;
  int  a39;
  int  a40;
  int  a42;
  int  a91;
  int  a92;
  int  a98;
  int  a99;

  if(
    a97 == a95,
    a96 == a96,
    a97 == a96,
    a95 == a93,
    a96 == a105
  ) {}
}
```
</details>

The example above compiles for more than 5 minutes for me. Variants can be created by adding/removing more variable declarations, but the code is somehow very sensitive to working correctly (compiling in less than 0.1 second) again.

I'm not able to pinpoint what actually causes this to create an even more minimized example, but as it seems to be influenced by the variable names, I believe that the generator for "did you mean variable x instead?" is somehow at fault here.

Here's some other things I tried/observed:
- Running `time` on it shows that `user/sys` is really low, only `real` increases over time - meaning `clang++` doesn't actually take so long for compiling, but waits for the most time.
- Saving the code above as `test.c` and running `clang++ test.c` takes very long, while using `clang test.c` takes less than a second.
- Changing that single pointer to a normal `int` "fixes" it.
- Using standard assignments instead of `if` checks fixes it, but assigning it within the `if` clause also causes the issue.
- Changing the variable names too much results in taking less time, down to 0.1 seconds.
- The time it takes to finish "compiling" (display errors) varies with the number of declarations and comparisons, but removing the "wrong" ones can fix it again.
- When encountering it in my normal project, I first got some actual crashes from Clang - I cannot re-create those though, and they only occured after what felt like a timeout, when touching the file it read from (saving again)... I can't reproduce it though, so feel free to ignore this one and only focus on the long compile time.

After trying around with this for more than 3 hours without being able to further "destill" down the issue, let's hope someone else around here has a theory on why this occurs.

For experiments, feel free to test with this Godbolt:
[Godbolt](https://godbolt.org/z/rEEY9Tfjx)
- gcc: ~140 ms
- clang (any version): at least 25000 ms

### LINKED ISSUE #107840: Clang clash with the Assertion `idx < size()' failed.
Reproducer: https://gcc.godbolt.org/z/dnoKqaofo 
```
#include <iostream>
#include <algorithm>
#include <array>

auto getCache = getPool([&](bool *const result, tms& ts) {
  std::thread([=] {
    tms time = std::chrono::system_clock::now();
    std::this_thread::sleep_for(ts);
    if (time >= ts) {
        *result = true;

    } else {
        *result = false;
    }
  }).detach();
});

```
and get the result
```
clang++: /root/llvm-project/llvm/include/llvm/ADT/SmallVector.h:291: T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) [with T = clang::sema::FunctionScopeInfo*; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::reference = clang::sema::FunctionScopeInfo*&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics --std=c++20 <source>
1.	<source>:16:1: current parser token '}'
2.	<source>:5:25: lambda expression parsing
3.	<source>:5:58: in compound statement ('{}')
 #0 0x0000000003b258d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b258d8)
 #1 0x0000000003b2359c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b2359c)
 #2 0x0000000003a6c198 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007b4972c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007b4972c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007b4972c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007b4972c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007b4972c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007b4972c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006b5985e clang::Sema::tryCaptureVariable(clang::ValueDecl*, clang::SourceLocation, clang::Sema::TryCaptureKind, clang::SourceLocation, bool, clang::QualType&, clang::QualType&, unsigned int const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b5985e)
#10 0x0000000006b59e48 MarkVarDeclODRUsed(clang::ValueDecl*, clang::SourceLocation, clang::Sema&, unsigned int const*) SemaExpr.cpp:0:0
#11 0x0000000006b5b302 DoMarkVarDeclReferenced(clang::Sema&, clang::SourceLocation, clang::VarDecl*, clang::Expr*, llvm::DenseMap<clang::VarDecl const*, int, llvm::DenseMapInfo<clang::VarDecl const*, void>, llvm::detail::DenseMapPair<clang::VarDecl const*, int>>&) SemaExpr.cpp:0:0
#12 0x0000000006b87b3e MarkExprReferenced(clang::Sema&, clang::SourceLocation, clang::Decl*, clang::Expr*, bool, llvm::DenseMap<clang::VarDecl const*, int, llvm::DenseMapInfo<clang::VarDecl const*, void>, llvm::detail::DenseMapPair<clang::VarDecl const*, int>>&) SemaExpr.cpp:0:0
#13 0x0000000006cdce49 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformDeclRefExpr(clang::DeclRefExpr*) SemaExprCXX.cpp:0:0
#14 0x0000000006cf1d18 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformBinaryOperator(clang::BinaryOperator*) SemaExprCXX.cpp:0:0
#15 0x0000000006cd6530 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCondition(clang::SourceLocation, clang::VarDecl*, clang::Expr*, clang::Sema::ConditionKind) SemaExprCXX.cpp:0:0
#16 0x0000000006cf6046 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformIfStmt(clang::IfStmt*) SemaExprCXX.cpp:0:0
#17 0x0000000006cf6524 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaExprCXX.cpp:0:0
#18 0x0000000006cd54cf clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformLambdaExpr(clang::LambdaExpr*) SemaExprCXX.cpp:0:0
#19 0x0000000006cde858 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformInitializer(clang::Expr*, bool) (.part.0) SemaExprCXX.cpp:0:0
#20 0x0000000006cde546 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformExprs(clang::Expr* const*, unsigned int, bool, llvm::SmallVectorImpl<clang::Expr*>&, bool*) SemaExprCXX.cpp:0:0
#21 0x0000000006ceec51 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCallExpr(clang::CallExpr*) SemaExprCXX.cpp:0:0
#22 0x0000000006cf13c3 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCXXDependentScopeMemberExpr(clang::CXXDependentScopeMemberExpr*) SemaExprCXX.cpp:0:0
#23 0x0000000006ceebde clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCallExpr(clang::CallExpr*) SemaExprCXX.cpp:0:0
#24 0x0000000006ccb03d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ccb03d)
#25 0x0000000006ccb3bd clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ccb3bd)
#26 0x000000000703eade clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x703eade)
#27 0x00000000066b3e24 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b3e24)
#28 0x00000000066aa870 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66aa870)
#29 0x00000000066ab7a0 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66ab7a0)
#30 0x00000000066ac679 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66ac679)
#31 0x000000000664c5d2 clang::Parser::ParseLambdaExpressionAfterIntroducer(clang::LambdaIntroducer&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x664c5d2)
#32 0x000000000664d6ab clang::Parser::ParseLambdaExpression() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x664d6ab)
#33 0x000000000662d6d5 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662d6d5)
#34 0x000000000662e08a clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662e08a)
#35 0x000000000662e229 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662e229)
#36 0x000000000662e58e clang::Parser::ParseExpressionList(llvm::SmallVectorImpl<clang::Expr*>&, llvm::function_ref<void ()>, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662e58e)
#37 0x0000000006632c1a clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6632c1a)
#38 0x000000000662bf31 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662bf31)
#39 0x000000000662e08a clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662e08a)
#40 0x000000000662e229 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x662e229)
#41 0x00000000065e79d6 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65e79d6)
#42 0x00000000065f696b clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f696b)
#43 0x00000000065b59be clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b59be)
#44 0x00000000065b616e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b616e)
#45 0x00000000065bc6f7 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65bc6f7)
#46 0x00000000065bd5cd clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65bd5cd)
#47 0x00000000065b0bba clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b0bba)
#48 0x0000000004470d68 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4470d68)
#49 0x0000000004702ca9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4702ca9)
#50 0x000000000468655e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x468655e)
#51 0x00000000047ec0ce clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47ec0ce)
#52 0x0000000000cb996f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcb996f)
#53 0x0000000000cb2bba ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#54 0x00000000044b4189 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#55 0x0000000003a6c644 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a6c644)
#56 0x00000000044b477f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#57 0x000000000447a6c5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x447a6c5)
#58 0x000000000447b12d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x447b12d)
#59 0x0000000004482d75 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4482d75)
#60 0x0000000000cb6d65 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcb6d65)
#61 0x0000000000b89614 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb89614)
#62 0x00007b4972c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#63 0x00007b4972c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#64 0x0000000000cb266e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcb266e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### LINKED ISSUE #137860: Clang 21 crash (stack dump) when using _Atomic anonymous struct field access with atomic_fetch_add
## Summary

Clang 21 crashes with a stack dump when trying to compile C code that uses _Atomic struct containing an anonymous struct, and accessing a subfield with atomic_fetch_add.
Instead of reporting a normal diagnostic, Clang crashes during semantic analysis (Sema::RefersToMemberWithReducedAlignment).

## Stack Trace

```
Stack dump:
0.      Program arguments: /usr/local/bin/clang-21 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name prueba.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/root -fcoverage-compilation-dir=/root -resource-dir /usr/local/lib/clang/21 -internal-isystem /usr/local/lib/clang/21/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c2x -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/prueba-d1672b.o -x c prueba.cpp
1.      prueba.cpp:17:1: current parser token '}'
2.      prueba.cpp:15:1: parsing function body 'add'
3.      prueba.cpp:15:1: in compound statement ('{}')
 #0 0x000055bf6ccfb18f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/clang-21+0x3c4a18f)
 #1 0x000055bf6ccf8bd4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x00007fcb90f86420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x000055bf704f588b getInterestingTagDecl(clang::TagDecl*) Type.cpp:0:0
 #4 0x000055bf6f170b2b clang::Sema::RefersToMemberWithReducedAlignment(clang::Expr*, llvm::function_ref<void (clang::Expr*, clang::RecordDecl*, clang::FieldDecl*, clang::CharUnits)>) (/usr/local/bin/clang-21+0x60bfb2b)
 #5 0x000055bf6f171180 clang::Sema::CheckAddressOfPackedMember(clang::Expr*) (/usr/local/bin/clang-21+0x60c0180)
 #6 0x000055bf6f43e823 clang::Sema::CheckAddressOfOperand(clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation) (/usr/local/bin/clang-21+0x638d823)
 #7 0x000055bf6f462710 clang::Sema::CreateBuiltinUnaryOp(clang::SourceLocation, clang::UnaryOperatorKind, clang::Expr*, bool) (/usr/local/bin/clang-21+0x63b1710)
 #8 0x000055bf6f462f85 clang::Sema::BuildUnaryOp(clang::Scope*, clang::SourceLocation, clang::UnaryOperatorKind, clang::Expr*, bool) (/usr/local/bin/clang-21+0x63b1f85)
 #9 0x000055bf6f541845 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformInitializer(clang::Expr*, bool) SemaExprCXX.cpp:0:0
#10 0x000055bf6f5415c2 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExprs(clang::Expr* const*, unsigned int, bool, llvm::SmallVectorImpl<clang::Expr*>&, bool*) SemaExprCXX.cpp:0:0
#11 0x000055bf6f54851d clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCallExpr(clang::CallExpr*) SemaExprCXX.cpp:0:0
#12 0x000055bf6f55fd4e (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) SemaExprCXX.cpp:0:0
#13 0x000055bf6f53d14a clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/local/bin/clang-21+0x648c14a)
#14 0x000055bf6f53f45d clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/usr/local/bin/clang-21+0x648e45d)
#15 0x000055bf6f87b09e clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/usr/local/bin/clang-21+0x67ca09e)
#16 0x000055bf6f02fdcc clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/usr/local/bin/clang-21+0x5f7edcc)
#17 0x000055bf6f0236b2 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/local/bin/clang-21+0x5f726b2)
#18 0x000055bf6f024104 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/local/bin/clang-21+0x5f73104)
#19 0x000055bf6f02546c clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/bin/clang-21+0x5f7446c)
#20 0x000055bf6f0277e2 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/bin/clang-21+0x5f767e2)
#21 0x000055bf6ef1ee83 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/bin/clang-21+0x5e6de83)
#22 0x000055bf6ef68f05 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/bin/clang-21+0x5eb7f05)
#23 0x000055bf6ef1762d clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/bin/clang-21+0x5e6662d)
#24 0x000055bf6ef1816e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/bin/clang-21+0x5e6716e)
#25 0x000055bf6ef21d73 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/local/bin/clang-21+0x5e70d73)
#26 0x000055bf6ef236a8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/local/bin/clang-21+0x5e726a8)
#27 0x000055bf6ef1162a clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-21+0x5e6062a)
#28 0x000055bf6d67fe45 clang::CodeGenAction::ExecuteAction() (/usr/local/bin/clang-21+0x45cee45)
#29 0x000055bf6d9649b8 clang::FrontendAction::Execute() (/usr/local/bin/clang-21+0x48b39b8)
#30 0x000055bf6d8e2d3b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-21+0x4831d3b)
#31 0x000055bf6da56c7b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-21+0x49a5c7b)
#32 0x000055bf69f53f51 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-21+0xea2f51)
#33 0x000055bf69f4c5fd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#34 0x000055bf69f4f99f clang_main(int, char**, llvm::ToolContext const&) (/usr/local/bin/clang-21+0xe9e99f)
#35 0x000055bf69e2230b main (/usr/local/bin/clang-21+0xd7130b)
```

## Program

```
#include <stdint.h>
#include <stdatomic.h>
struct S {

    struct {
        uint8_t h;
        uint8_t f;
    };

};
_Atomic struct S s = {
                     .h = UINT8_MIN,};
void add(void)
{
    atomic_fetch_add(&s.f, UINT8_MIN);
}
```

## To reproduce quickly 

https://gcc.godbolt.org/z/ojzzEevv7

### LINKED ISSUE #137867: Clang 21 crash (Stack dump) when using _Atomic(struct) field access incorrectly in C code
## Summary:

Clang 21 crashes with a segmentation fault (SIGSEGV) when compiling C code that uses _Atomic(struct) and tries to load and dereference a member incorrectly.
Instead of reporting a clean error about invalid atomic access, the compiler crashes during semantic analysis (Sema::RefersToMemberWithReducedAlignment).

## Stack dump

```
Stack dump:
0.      Program arguments: /usr/local/bin/clang-21 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name prueba.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/root -fcoverage-compilation-dir=/root -resource-dir /usr/local/lib/clang/21 -internal-isystem /usr/local/lib/clang/21/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c2x -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/prueba-4c1619.o -x c prueba.cpp
1.      prueba.cpp:12:38: current parser token ')'
2.      prueba.cpp:10:1: parsing function body 'main'
3.      prueba.cpp:10:1: in compound statement ('{}')
^[[A #0 0x000056358be8a18f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/clang-21+0x3c4a18f)
 #1 0x000056358be87bd4 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x00007f65c50ae420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x000056358f68488b getInterestingTagDecl(clang::TagDecl*) Type.cpp:0:0
 #4 0x000056358e2ffb2b clang::Sema::RefersToMemberWithReducedAlignment(clang::Expr*, llvm::function_ref<void (clang::Expr*, clang::RecordDecl*, clang::FieldDecl*, clang::CharUnits)>) (/usr/local/bin/clang-21+0x60bfb2b)
 #5 0x000056358e300180 clang::Sema::CheckAddressOfPackedMember(clang::Expr*) (/usr/local/bin/clang-21+0x60c0180)
 #6 0x000056358e5cd823 clang::Sema::CheckAddressOfOperand(clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation) (/usr/local/bin/clang-21+0x638d823)
 #7 0x000056358e5f1710 clang::Sema::CreateBuiltinUnaryOp(clang::SourceLocation, clang::UnaryOperatorKind, clang::Expr*, bool) (/usr/local/bin/clang-21+0x63b1710)
 #8 0x000056358e5f1f85 clang::Sema::BuildUnaryOp(clang::Scope*, clang::SourceLocation, clang::UnaryOperatorKind, clang::Expr*, bool) (/usr/local/bin/clang-21+0x63b1f85)
 #9 0x000056358e6fdb15 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformInitializer(clang::Expr*, bool) SemaExprCXX.cpp:0:0
#10 0x000056358e6fd892 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformExprs(clang::Expr* const*, unsigned int, bool, llvm::SmallVectorImpl<clang::Expr*>&, bool*) SemaExprCXX.cpp:0:0
#11 0x000056358e7047e1 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCallExpr(clang::CallExpr*) SemaExprCXX.cpp:0:0
#12 0x000056358e715f64 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformCXXDependentScopeMemberExpr(clang::CXXDependentScopeMemberExpr*) SemaExprCXX.cpp:0:0
#13 0x000056358e71b813 clang::TreeTransform<clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>)::TyposReplace>::TransformUnaryOperator(clang::UnaryOperator*) SemaExprCXX.cpp:0:0
#14 0x000056358e6cd20d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/usr/local/bin/clang-21+0x648d20d)
#15 0x000056358e6ce45d clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/usr/local/bin/clang-21+0x648e45d)
#16 0x000056358e5e23b5 clang::Sema::ActOnCondition(clang::Scope*, clang::SourceLocation, clang::Expr*, clang::Sema::ConditionKind, bool) (/usr/local/bin/clang-21+0x63a23b5)
#17 0x000056358e1afef0 clang::Parser::ParseParenExprOrCondition(clang::ActionResult<clang::Stmt*, true>*, clang::Sema::ConditionResult&, clang::SourceLocation, clang::Sema::ConditionKind, clang::SourceLocation&, clang::SourceLocation&) (/usr/local/bin/clang-21+0x5f6fef0)
#18 0x000056358e1bb526 clang::Parser::ParseWhileStatement(clang::SourceLocation*) (/usr/local/bin/clang-21+0x5f7b526)
#19 0x000056358e1b211e clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/usr/local/bin/clang-21+0x5f7211e)
#20 0x000056358e1b3104 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/local/bin/clang-21+0x5f73104)
#21 0x000056358e1b446c clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/bin/clang-21+0x5f7446c)
#22 0x000056358e1b67e2 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/bin/clang-21+0x5f767e2)
#23 0x000056358e0ade83 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/bin/clang-21+0x5e6de83)
#24 0x000056358e0f7f05 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/bin/clang-21+0x5eb7f05)
#25 0x000056358e0a662d clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/bin/clang-21+0x5e6662d)
#26 0x000056358e0a716e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/bin/clang-21+0x5e6716e)
#27 0x000056358e0b0d73 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/local/bin/clang-21+0x5e70d73)
#28 0x000056358e0b26a8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/local/bin/clang-21+0x5e726a8)
#29 0x000056358e0a062a clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-21+0x5e6062a)
#30 0x000056358c80ee45 clang::CodeGenAction::ExecuteAction() (/usr/local/bin/clang-21+0x45cee45)
#31 0x000056358caf39b8 clang::FrontendAction::Execute() (/usr/local/bin/clang-21+0x48b39b8)
#32 0x000056358ca71d3b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-21+0x4831d3b)
#33 0x000056358cbe5c7b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-21+0x49a5c7b)
#34 0x00005635890e2f51 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-21+0xea2f51)
#35 0x00005635890db5fd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#36 0x00005635890de99f clang_main(int, char**, llvm::ToolContext const&) (/usr/local/bin/clang-21+0xe9e99f)
#37 0x0000563588fb130b main (/usr/local/bin/clang-21+0xd7130b)
#38 0x00007f65c4b5c083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#39 0x00005635890db07e _start (/usr/local/bin/clang-21+0xe9b07e)
```

## Program

```
#include <stdlib.h>
#include <pthread.h>
struct T {
 char value;
};
void* work(void* p) {
 struct T* t = (struct T*)p;
}
int main()
{
 _Atomic(struct T) t;
 while (!atomic_load(&t.value)->value)
  ;
 return t.value->value;
}
```

## To quickly reproduce

https://gcc.godbolt.org/z/d6GbsWjq5

### LINKED ISSUE #138850: Clang-21 crash with: Assertion `Entry != DelayedTypos.end() && "Failed to get the state for a TypoExpr!"' failed.
### Description
I encountered a crash in Clang-21 when compiling the following code:
```cpp
void _Z4func() {
entry:
        int tmp = add(int, 0, 0);
        uint tmp = add(uint, 1, 1);
        ubyte tmp = add(ubyte, 1, 2);
        sbyte tmp = add(sbyte, 2, 3);
        call(void, f, (int)tmp);
        call(void, g, (ubyte)tmp);
        ret(void);
}
```
### Clang Version

```sh
$ clang -v
Ubuntu clang version 21.0.0 (++20250501082025+9b1051281e43-1~exp1~20250501082214.882)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-21/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Command
The compilation command used was:
```sh
clang++ bug.cpp  -O3 -Wall -Wextra -fno-strict-aliasing -fwrapv -g -fsanitize=address  -c -o bug.o
```

### Error Message
```sh
<source>:3:26: error: expected '(' for function-style cast or type construction
    3 |         int tmp = add(int, 0, 0);
      |                       ~~~^
<source>:4:9: error: use of undeclared identifier 'uint'; did you mean 'int'?
    4 |         uint tmp = add(uint, 1, 1);
      |         ^~~~
      |         int
<source>:4:14: error: redefinition of 'tmp'
    4 |         uint tmp = add(uint, 1, 1);
      |              ^
<source>:3:13: note: previous definition is here
    3 |         int tmp = add(int, 0, 0);
      |             ^
<source>:4:24: error: use of undeclared identifier 'uint'; did you mean 'using'?
    4 |         uint tmp = add(uint, 1, 1);
      |                        ^~~~
      |                        using
<source>:4:24: error: expected expression
<source>:5:9: error: unknown type name 'ubyte'
    5 |         ubyte tmp = add(ubyte, 1, 2);
      |         ^
<source>:5:25: error: use of undeclared identifier 'ubyte'
    5 |         ubyte tmp = add(ubyte, 1, 2);
      |                         ^~~~~
<source>:6:9: error: unknown type name 'sbyte'
    6 |         sbyte tmp = add(sbyte, 2, 3);
      |         ^
<source>:6:25: error: use of undeclared identifier 'sbyte'
    6 |         sbyte tmp = add(sbyte, 2, 3);
      |                         ^~~~~
<source>:7:18: error: expected '(' for function-style cast or type construction
    7 |         call(void, f, (int)tmp);
      |              ~~~~^
<source>:7:20: error: use of undeclared identifier 'f'
    7 |         call(void, f, (int)tmp);
      |                    ^
clang++: /root/llvm-project/llvm/tools/clang/lib/Sema/SemaLookup.cpp:5791: const clang::Sema::TypoExprState& clang::Sema::getTypoExprState(clang::TypoExpr*) const: Assertion `Entry != DelayedTypos.end() && "Failed to get the state for a TypoExpr!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -O3 -Wall -Wextra -fno-strict-aliasing -fwrapv -g -fsanitize=address <source>
1.	<source>:8:9: current parser token 'call'
2.	<source>:1:16: parsing function body '_Z4func'
3.	<source>:1:16: in compound statement ('{}')
 #0 0x0000000003f76d78 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f76d78)
 #1 0x0000000003f74a04 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f74a04)
 #2 0x0000000003eb98c8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007401b9842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007401b98969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007401b9842476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007401b98287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007401b982871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007401b9839e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006d15a66 clang::Sema::getTypoExprState(clang::TypoExpr*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d15a66)
#10 0x0000000006c0e1e7 (anonymous namespace)::TransformTypos::TransformTypoExpr(clang::TypoExpr*) SemaExprCXX.cpp:0:0
#11 0x0000000006c24a69 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformRecoveryExpr(clang::RecoveryExpr*) SemaExprCXX.cpp:0:0
#12 0x0000000006c42d66 (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) SemaExprCXX.cpp:0:0
#13 0x0000000006c1770d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c1770d)
#14 0x0000000006c18d0d clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c18d0d)
#15 0x0000000006f7526e clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f7526e)
#16 0x00000000066f2124 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66f2124)
#17 0x00000000066e9b42 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66e9b42)
#18 0x00000000066eaa6d clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66eaa6d)
#19 0x00000000066f2783 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66f2783)
#20 0x00000000066f2f4a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66f2f4a)
#21 0x00000000065fa913 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65fa913)
#22 0x0000000006630fbd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6630fbd)
#23 0x00000000065ee44e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65ee44e)
#24 0x00000000065eec09 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65eec09)
#25 0x00000000065f652a clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f652a)
#26 0x00000000065f74cd clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f74cd)
#27 0x00000000065f7980 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65f7980)
#28 0x00000000065e9873 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65e9873)
#29 0x0000000004918f78 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4918f78)
#30 0x0000000004c0c235 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c0c235)
#31 0x0000000004b8b83e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b8b83e)
#32 0x0000000004d000e9 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4d000e9)
#33 0x0000000000da766f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda766f)
#34 0x0000000000d9d83a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#35 0x000000000497f839 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#36 0x0000000003eb9d64 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eb9d64)
#37 0x000000000497fe4f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#38 0x000000000494229d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x494229d)
#39 0x000000000494332e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x494332e)
#40 0x000000000494b185 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x494b185)
#41 0x0000000000da35d8 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xda35d8)
#42 0x0000000000c28a64 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc28a64)
#43 0x00007401b9829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#44 0x00007401b9829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#45 0x0000000000d9d2e5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xd9d2e5)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

The issue can also be reproduced on Compiler Explorer:https://godbolt.org/z/ePK8o9EMo
Please let me know if you need any more details.

### LINKED ISSUE #139913: ICE in clang in getTypoExprState, only in trunk version and using -std=c2x
The issue disappear when printf is removed.

## Assertion

```
clang: /root/llvm-project/llvm/tools/clang/lib/Sema/SemaLookup.cpp:5791: const clang::Sema::TypoExprState& clang::Sema::getTypoExprState(clang::TypoExpr*) const: Assertion `Entry != DelayedTypos.end() && "Failed to get the state for a TypoExpr!"' failed.
```

## Stack dump 

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c2x <source>
1.	<source>:5:1: current parser token '}'
2.	<source>:2:12: parsing function body 'main'
3.	<source>:2:12: in compound statement ('{}')
 #0 0x0000000003f95368 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f95368)
 #1 0x0000000003f92ff4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3f92ff4)
 #2 0x0000000003ed7c28 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007e5428c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007e5428c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007e5428c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007e5428c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007e5428c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007e5428c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006d56616 clang::Sema::getTypoExprState(clang::TypoExpr*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6d56616)
#10 0x0000000006c4e767 (anonymous namespace)::TransformTypos::TransformTypoExpr(clang::TypoExpr*) SemaExprCXX.cpp:0:0
#11 0x0000000006c64d29 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformRecoveryExpr(clang::RecoveryExpr*) SemaExprCXX.cpp:0:0
#12 0x0000000006c5b915 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformInitializer(clang::Expr*, bool) (.part.0) SemaExprCXX.cpp:0:0
#13 0x0000000006c5b58e clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformExprs(clang::Expr* const*, unsigned int, bool, llvm::SmallVectorImpl<clang::Expr*>&, bool*) SemaExprCXX.cpp:0:0
#14 0x0000000006c67989 clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCallExpr(clang::CallExpr*) SemaExprCXX.cpp:0:0
#15 0x0000000006c82f86 (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) SemaExprCXX.cpp:0:0
#16 0x0000000006c57c8d clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6c57c8d)
#17 0x0000000006c5928d clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6c5928d)
#18 0x0000000006fb6b7e clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6fb6b7e)
#19 0x000000000672f7a4 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x672f7a4)
#20 0x000000000672729b clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x672729b)
#21 0x00000000067280dd clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 24u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x67280dd)
#22 0x000000000672fe03 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x672fe03)
#23 0x00000000067305ca clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x67305ca)
#24 0x000000000662a573 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x662a573)
#25 0x0000000006660efd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6660efd)
#26 0x000000000661e0ae clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x661e0ae)
#27 0x000000000661e869 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x661e869)
#28 0x000000000662618a clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x662618a)
#29 0x000000000662712d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x662712d)
#30 0x000000000661950a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x661950a)
#31 0x000000000493b128 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x493b128)
#32 0x0000000004c31795 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4c31795)
#33 0x0000000004bb03ce clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4bb03ce)
#34 0x0000000004d25339 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x4d25339)
#35 0x0000000000dab05f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xdab05f)
#36 0x0000000000da122a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#37 0x00000000049a2379 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#38 0x0000000003ed80c4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3ed80c4)
#39 0x00000000049a298f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#40 0x000000000496475d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x496475d)
#41 0x00000000049657ee clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49657ee)
#42 0x000000000496dad5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x496dad5)
#43 0x0000000000da6fc8 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xda6fc8)
#44 0x0000000000c2c8f4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xc2c8f4)
#45 0x00007e5428c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#46 0x00007e5428c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#47 0x0000000000da0cd5 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xda0cd5)
```

## Program

```
#include <stdio.h>
int main() {
    int i = 0;
    printf(CONCAT(foo, i, ));
}
```

To quickly reproduce:

It happens only in trunk with -std=c2x

https://godbolt.org/z/9fjjhc6c1

### LINKED ISSUE #142457: Crash in TypoCorrectionConsumer::getNextCorrection
This code crashes clangd 21.0.0 (20250601)

```c
static void func(void) {
    alloc_image(device,
                allocator,
                &texture->image, &texture->alloc, &texture->view,
                name, width, height, depth,
                mip_levels, sampling, usage, view_type,
                VK_IMAGE_ASPECT_COLOR_BIT, format);
}
```

### PR DESCRIPTION
**Pull request by AaronBallman**
This removes the delayed typo correction functionality from Clang (regular typo correction still remains) due to fragility of the solution.

An RFC was posted here: https://discourse.llvm.org/t/rfc-removing-support-for-delayed-typo-correction/86631 and while that RFC was asking for folks to consider stepping up to be maintainers, and we did have a few new contributors show some interest, experiments show that it's likely worth it to remove this functionality entirely and focus efforts on improving regular typo correction.

This removal fixes ~20 open issues (quite possibly more), improves compile time performance by roughly .3-.4% (https://llvm-compile-time-tracker.com/?config=Overview&stat=instructions%3Au&remote=AaronBallman&sortBy=date), and does not appear to regress diagnostic behavior in a way we wouldn't find acceptable.

Fixes #142457
Fixes #139913
Fixes #138850
Fixes #137867
Fixes #137860
Fixes #107840
Fixes #93308
Fixes #69470
Fixes #59391
Fixes #58172
Fixes #46215
Fixes #45915
Fixes #45891
Fixes #44490
Fixes #36703
Fixes #32903
Fixes #23312
Fixes #69874

### CODE REVIEW

**Comment by AaronBallman** [comment]
Posting the PR for review, but also because I'd like to see what precommit CI thinks of the changes on platforms other than the one I'm on (Windows).

**Review by erichkeane — APPROVED** [review]
I spent a while with these changes, and they all seem correct to me best I can tell.  As most seems to just be deletions, its as good as I can figure.

It would be cool if we could have done this more gradually, but I'm happy to commit-as-is.

File: clang/test/SemaCXX/virtuals.cpp [hunk 1]
```diff
@@ -58,10 +58,8 @@ struct Base {
 };
 
 struct Derived final : Base {
-  virtual ~Derived() = defaul; // #default
+  virtual ~Derived() = defaul; // expected-error {{use of undeclared identifier 'defaul'}}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/virtuals.cpp:61]: I would sort of expect us to try to do typo correction here: we know we're expecting one of a few keywords.  Maybe worth filing a bug,

File: clang/test/SemaCXX/typo-correction.cpp [hunk 2]
```diff
@@ -649,12 +647,12 @@ class AddObservation { // expected-note {{declared here}}
...
 namespace testNonStaticMemberHandling {
 struct Foo {
-  bool usesMetadata;  // expected-note {{'usesMetadata' declared here}}
+  bool usesMetadata;
 };
 int test(Foo f) {
   if (UsesMetadata)  // expected-error-re {{use of undeclared identifier 'UsesMetadata'{{$}}}}
     return 5;
-  if (f.UsesMetadata)  // expected-error {{no member named 'UsesMetadata' in 'testNonStaticMemberHandling::Foo'; did you mean 'usesMetadata'?}}
+  if (f.UsesMetadata)  // expected-error {{no member named 'UsesMetadata' in 'testNonStaticMemberHandling::Foo'}}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/typo-correction.cpp:655]: Why are we losing typo correction here?

File: clang/test/SemaCXX/pr13394-crash-on-invalid.cpp [hunk 3]
```diff
@@ -1,29 +0,0 @@
-// RUN: %clang_cc1 -fsyntax-only -verify -std=c++11 %s
-// Don't crash (PR13394).
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/pr13394-crash-on-invalid.cpp:2]: Is this just not worth keeping because it's strongly connected to delayed typo correction?  Or did this move?

File: clang/test/SemaCXX/member-expr.cpp [hunk 4]
```diff
@@ -207,7 +207,7 @@ namespace PR15045 {
 
     // Show that recovery has happened by also triggering typo correction
     e->Func();  // expected-error {{member reference type 'bar' is not a pointer; did you mean to use '.'?}} \
-                // expected-error {{no member named 'Func' in 'PR15045::bar'; did you mean 'func'?}}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/member-expr.cpp:210]: Why are we losing typo correction here?

File: clang/test/SemaCXX/constant-expression-cxx11.cpp [hunk 5]
```diff
@@ -1888,10 +1888,11 @@ namespace PR15884 {
 }
 
 namespace AfterError {
-  constexpr int error() {
+  constexpr int error() { // pre-cxx23-error {{no return statement in constexpr function}}
```
Comment (efriedma-quic) [inline clang/test/SemaCXX/constant-expression-cxx11.cpp:1891]: It would be nice to suppress this diagnostic: if we discard a "return" statement, we shouldn't be complaining that constexpr eval of the function fails.

**Review by efriedma-quic — COMMENTED** [review]
Briefly looked over the test changes.  Mostly seems fine, but it seems like we're losing typo correction in a few places that don't seem related to delayed typo correction, at least at first glance.

File: clang/lib/Parse/ParseOpenMP.cpp [hunk 6]
```diff
@@ -4920,6 +4914,11 @@ bool Parser::ParseOpenMPVarList(OpenMPDirectiveKind DKind,
             ModifierFound = true;
           } else {
             StepFound = parseStepSize(*this, Data, Kind, Tok.getLocation());
+            if (!StepFound) {
```
Comment (shafik) [inline clang/lib/Parse/ParseOpenMP.cpp:4917]: I am curious why this new code is needed.

File: clang/lib/Sema/SemaOverload.cpp [hunk 7]
```diff
@@ -14055,8 +14055,10 @@ FunctionDecl *Sema::ResolveSingleFunctionTemplateSpecialization(
     //   specified and it, along with any default template arguments,
     //   identifies a single function template specialization, then the
     //   template-id is an lvalue for the function template specialization.
-    FunctionTemplateDecl *FunctionTemplate
-      = cast<FunctionTemplateDecl>((*I)->getUnderlyingDecl());
+    FunctionTemplateDecl *FunctionTemplate =
+        dyn_cast<FunctionTemplateDecl>((*I)->getUnderlyingDecl());
```
Comment (shafik) [inline clang/lib/Sema/SemaOverload.cpp:14059]: Curious, why the change to `dyn_cast`?

**Review by Endilll — COMMENTED** [review]
Changes to DR tests LGTM

File: clang/lib/Parse/ParseOpenMP.cpp (hunk 6 above)
Comment (AaronBallman) [reply clang/lib/Parse/ParseOpenMP.cpp:4917]: Good question! Because without this new code, the OpenMP 5.2 parsing behavior is different from other OpenMP modes in a way that made about a hundred tests need to be updated for an unhelpful "missing ')'" diagnostic difference.

File: clang/lib/Sema/SemaOverload.cpp (hunk 7 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaOverload.cpp:14059]: Fixes a latent crash delayed typo correction was hiding from us.

File: clang/test/SemaCXX/constant-expression-cxx11.cpp (hunk 5 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/constant-expression-cxx11.cpp:1891]: Agreed, I've filed an issue for a few situations you've brought up in this PR plus some I'm aware of.

https://github.com/llvm/llvm-project/issues/143509

File: clang/test/SemaCXX/member-expr.cpp (hunk 4 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/member-expr.cpp:210]: It's one of the cases where we were relying on delayed typo correction for the typo; not certain why though. We lost a few such diagnostics that we'll want to recover someday.

File: clang/test/SemaCXX/pr13394-crash-on-invalid.cpp (hunk 3 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/pr13394-crash-on-invalid.cpp:2]: It only existed for testing a crash with delayed typo correction. When I looked at correcting the diagnostics for the test, it seemed better to just drop the test because it wasn't really testing anything we don't already cover elsewhere.

File: clang/test/SemaCXX/typo-correction.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/typo-correction.cpp:655]: Same as above; it was relying on delayed typo correction for some reason.

File: clang/test/SemaCXX/virtuals.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/virtuals.cpp:61]: Agreed: https://github.com/llvm/llvm-project/issues/143509

**Review by Sirraide — APPROVED** [review]
LGTM, but it’s still missing a release note isn’t it?

**Comment by AaronBallman** [comment]
> LGTM, but it’s still missing a release note isn’t it?

Absolutely correct. :-D

**Comment by AaronBallman** [comment]
Linux precommit CI failures appear to be unrelated:
```
/usr/bin/ld: cannot find /home/gha/actions-runner/_work/llvm-project/llvm-project/build/lib/clang/21/lib/x86_64-unknown-linux-gnu/libclang_rt.tysan.a: No such file or directory
```

File: clang/test/SemaCXX/constant-expression-cxx11.cpp (hunk 5 above)
Comment (efriedma-quic) [reply clang/test/SemaCXX/constant-expression-cxx11.cpp:1891]: Did you mean to refer to some other issue report?  The issue here isn't typo handling, really; it's that we're discarding the "return" without noting it anywhere.

File: clang/lib/Parse/ParseOpenMP.cpp (hunk 6 above)
Comment (shafik) [reply clang/lib/Parse/ParseOpenMP.cpp:4917]: huh, spooky action at a distance

File: clang/test/SemaCXX/constant-expression-cxx11.cpp (hunk 5 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/constant-expression-cxx11.cpp:1891]: Hmm okay, I didn't write it in the issue but I was thinking that suppression of follow-on diagnostics is also about the context of the typo (if typo correction results in us dropping a statement, we should suppress follow-on diagnostics about the dropped statement). But you're right, this is orthogonal, it's more general about error recovery. We previously would not drop the `return` statement here but would instead give it a `RecoveryExpr` for its operand, that no longer happens.

I've filed https://github.com/llvm/llvm-project/issues/143688 on the assumption we're removing delayed typos so this will eventually be true. :-D

File: clang-tools-extra/clangd/unittests/HoverTests.cpp [hunk 8]
```diff
@@ -974,7 +974,7 @@ class Foo final {})cpp";
          HI.Name = "abc";
          HI.Kind = index::SymbolKind::Variable;
          HI.NamespaceScope = "";
-         HI.Definition = "int abc = <recovery - expr>()";
```
Comment (kadircet) [inline clang-tools-extra/clangd/unittests/HoverTests.cpp:977]: despite typoexprs fragile and complicated nature, i think they were providing most of their value by preserving more nodes in the AST, that can later on be used by source tools (especially for more error correction :)).

I don't think we need `TypoExpr`s for most of this, if possible, preserving these `TypoExpr` nodes through `RecoveryExpr`s would actually help a lot with preserving current behavior of tools but also shape of the AST for any other application.

I wouldn't block on this though, and wouldn't be surprised if this isn't trivial, we don't seem to be preserving typoexprs as recovery-exprs most of the time and I am not sure why.

Comment (AaronBallman) [reply clang-tools-extra/clangd/unittests/HoverTests.cpp:977]: Yeah, making a `RecoveryExpr` in these cases would be helpful (though potentially nontrivial). There was another case where we dropped a `ReturnStmt` rather than giving it a `RecoveryExpr` operand, and that caused follow-on diagnostics that were less than helpful.

**Comment by AaronBallman** [comment]
@efriedma-quic and I spoke yesterday about this and he said he thinks it's good to go, so landing the changes now. If there are further concerns, we can address them post-commit.

**Comment by boomanaiden154** [comment]
I was working on trying to land https://github.com/llvm/llvm-project/pull/144033, and ended up bisecting a change in diagnostic behavior impacting a libc++ test in that new configuration to this patch. Before: 
```
gha@fae34ead1955:~/llvm-project/build$ /home/gha/llvm-project/build/./bin/clang++ /home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp -pthread --target=x86_64-unknown-linux-gnu -nostdinc++ -I /home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test-suite-install/include/x86_64-unknown-linux-gnu/c++/v1 -I /home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test-suite-install/include/c++/v1 -I /home/gha/llvm-project/libcxx/test/support -std=c++26 -fmodules -fcxx-modules -fmodules-cache-path=/home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test/ModuleCache -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -Werror=thread-safety -Wuser-defined-warnings  -fsyntax-only -Wno-error  -ferror-limit=0
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:18:18: error: no type named 'unexpected_handler' in namespace 'std'
   18 |   using T = std::unexpected_handler; // expected-error {{no type named 'unexpected_handler' in namespace 'std'}}
      |             ~~~~~^
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:19:8: error: no member named 'unexpected' in namespace 'std'
   19 |   std::unexpected(); // expected-error {{no member named 'unexpected' in namespace 'std'}}
      |        ^~~~~~~~~~
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:20:8: error: no member named 'get_unexpected' in namespace 'std'
   20 |   std::get_unexpected(); // expected-error {{no member named 'get_unexpected' in namespace 'std'}}
      |        ^~~~~~~~~~~~~~
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:21:8: error: no type named 'set_unexpected' in namespace 'std'
   21 |   std::set_unexpected(f); // expected-error {{no type named 'set_unexpected' in namespace 'std'}}
      |   ~~~~~^
4 errors generated.
```

After:

```
gha@fae34ead1955:~/llvm-project/build$ /home/gha/llvm-project/build/./bin/clang++ /home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp -pthread --target=x86_64-unknown-linux-gnu -nostdinc++ -I /home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test-suite-install/include/x86_64-unknown-linux-gnu/c++/v1 -I /home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test-suite-install/include/c++/v1 -I /home/gha/llvm-project/libcxx/test/support -std=c++26 -fmodules -fcxx-modules -fmodules-cache-path=/home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test/ModuleCache -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -Werror=thread-safety -Wuser-defined-warnings  -fsyntax-only -Wno-error  -ferror-limit=0
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:18:18: error: no type named 'unexpected_handler' in namespace 'std'
   18 |   using T = std::unexpected_handler; // expected-error {{no type named 'unexpected_handler' in namespace 'std'}}
      |             ~~~~~^
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:19:8: error: declaration of 'unexpected' must be imported from module 'std.expected.unexpected' before it is required
   19 |   std::unexpected(); // expected-error {{no member named 'unexpected' in namespace 'std'}}
      |        ^
/home/gha/llvm-project/build/runtimes/runtimes-bins/libcxx/test-suite-install/include/c++/v1/__expected/unexpected.h:60:7: note: declaration here is not visible
   60 | class unexpected {
      |       ^
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:20:8: error: no member named 'get_unexpected' in namespace 'std'
   20 |   std::get_unexpected(); // expected-error {{no member named 'get_unexpected' in namespace 'std'}}
      |        ^~~~~~~~~~~~~~
/home/gha/llvm-project/libcxx/test/libcxx/depr/exception.unexpected/unexpected_disabled_cpp17.verify.cpp:21:8: error: no type named 'set_unexpected' in namespace 'std'
   21 |   std::set_unexpected(f); // expected-error {{no type named 'set_unexpected' in namespace 'std'}}
      |   ~~~~~^
4 errors generated.
```

This doesn't seem related to typo correction, but I'm not very familiar with how clang's diagnostics work. I'll keep investigating and see what pops out.

**Comment by boomanaiden154** [comment]
https://github.com/llvm/llvm-project/blob/b5dbf8210a57b986b9802304745f4c5c108cf37b/libcxx/test/libcxx/language.support/support.c.headers/support.c.headers.other/math.lerp.verify.cpp#L9

Looks like this has occurred before and is just handled by disabling the test on the libc++ side. I've put up #144466 to try and get this fixed so we can finally switch over to the runtimes build.

**Comment by AaronBallman** [comment]
> This doesn't seem related to typo correction, but I'm not very familiar with how clang's diagnostics work. I'll keep investigating and see what pops out.

I was surprised by this while working on the patch as well. The "you must import" message was tied to *delayed* typo correction originally. I ended up bringing that functionality back through regular typo correction with this commit in this PR: https://github.com/llvm/llvm-project/pull/143423/commits/88ad970d82bc740aff2c607b2a62ecec0275cc90

So the behavioral change is somewhat expected (it was quite possible that the reason why it was hooked up to delayed typos was for this kind of situation).

> Looks like this has occurred before and is just handled by disabling the test on the libc++ side. I've put up https://github.com/llvm/llvm-project/pull/144466 to try and get this fixed so we can finally switch over to the runtimes build.

I think that's a reasonable path forward for now, thank you (and sorry for the disruption)!

**Comment by shafik** [comment]
Looks like this regression is also linked to this change: https://github.com/llvm/llvm-project/issues/174259

**Comment by hongtaihu** [comment]
Thanks to a (possibly imperfect) bisection, it looks like this PR may also have fixed the following issues:
#111749, #114174, #122053, #127911, #138098, #140018.
If you have a moment, could you please take a look and confirm whether these are indeed resolved by this pr?@AaronBallman

**Comment by hongtaihu** [comment]
#50193  #50228 also bisects to this one
