### PR TITLE
[Clang] Fix warning for non std functions with name `infinity`

### LINKED ISSUE #123231: Erroneous "use of infinity" warning
clang incorrectly emits a warning when a method called infinity is called.

$ cat test.cpp
```
double infinity() { return 0; }

int main() {
   return infinity();
}
```

$ clang++ -ffast-math test.cpp -c
test.cpp:4:11: warning: use of infinity is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
    4 |    return infinity();

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Fix reporting diagnostic for non std functions that has the name `infinity`

Fixes: #123231

### CODE REVIEW

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -8469,7 +8489,7 @@ void Sema::CheckInfNaNFunction(const CallExpr *Call,
     bool IsInfOrIsFinite =
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaChecking.cpp:8489]: As an aside, this is called on every function call, which seems widely inficient.

can we do something like
```cpp
FPOptions FPO = Call->getFPFeaturesInEffect(getLangOpts());
if(FPO.getNoHonorInfs())
  return;
```

(and remove `FPO.getNoHonorInfs()` in the rest of the function)

Comment (AmrDeveloper) [reply clang/lib/Sema/SemaChecking.cpp:8489]: Yes, I agree, i am thinking to change the structure of the function `CheckInfNaNFunction ` too, because if `HasIdentifier` is false that's means `IsStdFunction`, `IsInfOrNanFunction` and `IsInfinityFunction` will return false, so maybe we can just eliminate some un needed function calls by early return.

I will try and update you with result :D

Comment (AmrDeveloper) [reply clang/lib/Sema/SemaChecking.cpp]: I think it's better now, early return if there is no identifier and check `NoHonor.. `first before checking for function name

**Review by cor3ntin — COMMENTED** [review]
Can you add a changelog entry? Thanks

**Comment by AmrDeveloper** [comment]
> Can you add a changelog entry? Thanks

Done, thanks

File: clang/lib/Sema/SemaChecking.cpp [hunk 2]
```diff
@@ -8454,26 +8454,47 @@ static bool IsInfOrNanFunction(StringRef calleeName, MathCheck Check) {
...
+
+    if (const NamespaceDecl *NSDecl =
+            dyn_cast<NamespaceDecl>(RDecl->getDeclContext())) {
+      return NSDecl->isStdNamespace();
+    }
+  }
+
+  return false;
+}
+
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaChecking.cpp:8476]:
```suggestion
  if (FDecl->getName() != "infinity")
    return false;

  if (const CXXMethodDecl *MDecl = dyn_cast<CXXMethodDecl>(FDecl)) {
    const CXXRecordDecl *RDecl = MDecl->getParent();
    if (RDecl->getName() != "numeric_limits")
      return false;

    if (const NamespaceDecl *NSDecl =
            dyn_cast<NamespaceDecl>(RDecl->getDeclContext()))
      return NSDecl->isStdNamespace();
  }

  return false;
}

```

File: clang/lib/Sema/SemaChecking.cpp [hunk 3]
```diff
@@ -8454,26 +8454,47 @@ static bool IsInfOrNanFunction(StringRef calleeName, MathCheck Check) {
...
 void Sema::CheckInfNaNFunction(const CallExpr *Call,
                                const FunctionDecl *FDecl) {
+  if (!FDecl->getIdentifier()) {
+    return;
+  }
+
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaChecking.cpp:8482]:
```suggestion
  if (!FDecl->getIdentifier())
    return;
 
```

**Review by cor3ntin — APPROVED** [review]
LGTM with nits

**Comment by AmrDeveloper** [comment]
> LGTM with nits

Thank you, I addressed the nits

File: clang/lib/Sema/SemaChecking.cpp [hunk 4]
```diff
@@ -8454,26 +8454,43 @@ static bool IsInfOrNanFunction(StringRef calleeName, MathCheck Check) {
...
   FPOptions FPO = Call->getFPFeaturesInEffect(getLangOpts());
-  bool HasIdentifier = FDecl->getIdentifier() != nullptr;
-  bool IsNaNOrIsUnordered =
-      IsStdFunction(FDecl, "isnan") || IsStdFunction(FDecl, "isunordered");
-  bool IsSpecialNaN =
-      HasIdentifier && IsInfOrNanFunction(FDecl->getName(), MathCheck::NaN);
-  if ((IsNaNOrIsUnordered || IsSpecialNaN) && FPO.getNoHonorNaNs()) {
+  if (FPO.getNoHonorNaNs() &&
+      (IsStdFunction(FDecl, "isnan") || IsStdFunction(FDecl, "isunordered") ||
+       IsInfOrNanFunction(FDecl->getName(), MathCheck::NaN))) {
```
Comment (zahiraam) [inline clang/lib/Sema/SemaChecking.cpp:8482]: I think for readability the intermediate `bool` variables can be kept. Same for the condition below.

File: clang/lib/Sema/SemaChecking.cpp [hunk 5]
```diff
@@ -8454,26 +8454,43 @@ static bool IsInfOrNanFunction(StringRef calleeName, MathCheck Check) {
...
+            dyn_cast<NamespaceDecl>(RDecl->getDeclContext()))
+      return NSDecl->isStdNamespace();
+  }
+
+  return false;
+}
+
 void Sema::CheckInfNaNFunction(const CallExpr *Call,
                                const FunctionDecl *FDecl) {
+  if (!FDecl->getIdentifier())
```
Comment (zahiraam) [inline clang/lib/Sema/SemaChecking.cpp:8476]: Wouldn't something like this work?
```suggestion
  if (!FDecl->getIdentifier())
  return;
FPOptions FPO = Call->getFPFeaturesInEffect(getLangOpts());
bool IsNaNOrIsUnordered =
    IsStdFunction(FDecl, "isnan") || IsStdFunction(FDecl, "isunordered");
bool IsSpecialNaN =
    IsInfOrNanFunction(FDecl->getName(), MathCheck::NaN);
bool IsInfOrIsFinite =
    IsStdFunction(FDecl, "isinf") || IsStdFunction(FDecl, "isfinite");
bool IsInfinityOrIsSpecialInf =
    IsInfOrNanFunction(FDecl->getName(), MathCheck::Inf);

if ((IsNaNOrIsUnordered || IsSpecialNaN) && FPO.getNoHonorNaNs()) {
  Diag(Call->getBeginLoc(), diag::warn_fp_nan_inf_when_disabled)
      << 1 << 0 << Call->getSourceRange();
  return;
}
if ((IsInfOrIsFinite || IsInfinityFunction(FDecl) ||
     IsInfinityOrIsSpecialInf) &&
    FPO.getNoHonorInfs()) {
  Diag(Call->getBeginLoc(), diag::warn_fp_nan_inf_when_disabled)
      << 0 << 0 << Call->getSourceRange();
}
```

Comment (AmrDeveloper) [reply clang/lib/Sema/SemaChecking.cpp:8476]: The problem with this is in case of `FPO.getNoHonorNaNs() == false` we performed un needed 3 function call, and in case of it's true we performed 3 more un needed too `IsInfOrIsFinite`, `IsInfinityOrIsSpecialInf`

```call
bool IsNaNOrIsUnordered =
    IsStdFunction(FDecl, "isnan") || IsStdFunction(FDecl, "isunordered");
bool IsSpecialNaN =
    IsInfOrNanFunction(FDecl->getName(), MathCheck::NaN);
    
if ((IsNaNOrIsUnordered || IsSpecialNaN) && false) { <--- Condition will evaluated to false

}
```

Comment (zahiraam) [reply clang/lib/Sema/SemaChecking.cpp:8476]: Oh! right, That makes sense!

**Review by zahiraam — APPROVED** [review]
LGTM. Thanks.

File: clang/lib/Sema/SemaChecking.cpp (hunk 5 above)
Comment (AmrDeveloper) [reply clang/lib/Sema/SemaChecking.cpp:8476]: Thank you

File: clang/test/Sema/warn-infinity-nan-disabled-win.cpp [hunk 6]
```diff
@@ -48,24 +48,49 @@ namespace std __attribute__((__visibility__("default"))) {
...
+template <class _Ty>
+class numeric_limits {
+public:
+    [[nodiscard]] static constexpr _Ty infinity() noexcept {
+        return _Ty();
+    }
+};
+
 } // namespace )
 }
```
Comment (shafik) [inline clang/test/Sema/warn-infinity-nan-disabled-win.cpp:73]: we should annotate the std namespace as well `// std`

File: clang/test/Sema/warn-infinity-nan-disabled-win.cpp [hunk 7]
```diff
@@ -216,11 +244,18 @@ int compareit(float a, float b) {
...
 // no-inf-warning@+1 {{use of infinity is undefined behavior due to the currently enabled floating-point options}}
-  double y = i * numeric_limits<double>::infinity();
+  double y = i * std::numeric_limits<double>::infinity();
+
+  y = i * numeric_limits<double>::infinity(); // expected-no-diagnostics
 
 // no-inf-no-nan-warning@+2 {{use of infinity is undefined behavior due to the currently enabled floating-point options}}
 // no-inf-warning@+1 {{use of infinity is undefined behavior due to the currently enabled floating-point options}}
-  j = numeric_limits<float>::infinity();
+  j = std::numeric_limits<float>::infinity();
```
Comment (shafik) [inline clang/test/Sema/warn-infinity-nan-disabled-win.cpp:253]: So what happens if we are using `using namespace std` and use `numeric_limits<...>::infinity()` do we expect a diagnostic?

**Review by shafik — COMMENTED** [review]
Minor comment and quick question.

File: clang/test/Sema/warn-infinity-nan-disabled-win.cpp (hunk 7 above)
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:253]: > So what happens if we are using `using namespace std` and use `numeric_limits<...>::infinity()` do we expect a diagnostic?

Yes should expect a diagnostic because we check Decl name space not the call expr,

I will create a pr to cover this case and update minor comment related to namespace

I will tag you as reviewer once I push it

Thanks

File: clang/test/Sema/warn-infinity-nan-disabled-win.cpp [hunk 8]
```diff
@@ -216,11 +244,18 @@ int compareit(float a, float b) {
...
+
+  j = numeric_limits<float>::infinity(); // expected-no-diagnostics
+
+  y = infinity(); // expected-no-diagnostics
+
```
[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: I found that we got `use of infinity is undefined behavior due to the currently enabled floating-point options` for `std::numeric_limits<double>::infinity();` for each copy generated from `foo` function, I will check it more and handle it in different pr

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: The same problem will happen with `isinf`, `isnan` and `isunordered` functions because the diagnostic will be reported for every generated function, we need to think of a way to process it once @erichkeane

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Sorry, I'm not getting your point in the previous message.  Can you explain it more for me?  

From my example, I would expect _TWO_ diagnostics (one per use). But I don't want 3 or 4 diagnostics.

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Yes I expected two too but what I got is two same warns on `std::numeric_limits<double>::infinity();` and one on `td::numeric_limits<T>::infinity()`, I am trying to understand from where the extra one come from

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Ah, in that case it is that the same checking code is being called during instantiation, which it almost definitely has to be (to catch the dependent case).

So what you're getting is:

```
std::numeric_limits<T>::infinity(); << Diagnosed ONLY during "Phase 2" of template instantiation.
  std::numeric_limits<double>::infinity(); << Diagnosed BOTH during Phase1 and Phase2.
```

Unfortunately we don't have a GREAT way to suppress warnings in these cases if you don't have access to the actual TreeTransform calls.  Typically we'd try to put the diagnostic somewhere this is ONLY called in Phase1, plus do it again ONLY if transformation happened during Phase 2.

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Yes, exactly.

Can we just enabled it only on phase 2 🤔, Not sure if we have a way to know in which phase we are?

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: We cannot really, since there is no such thing as 'phase 2' for most of the program (non templates).  Typically if you want something ONLY during phase 2, you do it during tree-transform or during the calls to the 'Rebuild' functions.

So you ALSO have to do it during phase-1, but the phase-2 work can suppress its diagnostic if it has already been done (assuming you are close enough to rebuild to do that).

The fix is likely that you'll have to mvoe where this is diagnosed to somewhere that isn't currently being called by the template instantiation, and re-add it then.

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Cool, I will understand the Sema structure more and move it :D

Thanks

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: Do we have a similar case with a place that covers most cases of using CallExpr, I found a function like `CheckInvalidBuiltinCountedByRef`, but it does not cover all cases @erichkeane

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: None I can think of at the moment unfortunately.  If i run across one, I'll bring it up.

[the remark this answers is not in the document]
Comment (AmrDeveloper) [reply clang/test/Sema/warn-infinity-nan-disabled-win.cpp:258]: > None I can think of at the moment unfortunately. If i run across one, I'll bring it up.

Thank you, I created a PR for the test cases, and I will continue searching for a good function or a place so I can create a one
