### PR TITLE
[InstCombine] Propagate FMF from fptrunc when folding `fptrunc fabs(X) -> fabs(fptrunc X)`

### LINKED ISSUE #143122: [InstCombine] ninf should not be propagated
Reproducer: https://alive2.llvm.org/ce/z/GnztNF
```
; bin/opt -passes=instcombine test.ll -S
define half @src(float %x) {
  %abs = call ninf float @llvm.fabs(float %x)
  %trunc = fptrunc float %abs to half
  ret half %trunc
}
```
```

----------------------------------------
define half @src(float %x) {
#0:
  %abs = fabs ninf float %x
  %trunc = fptrunc float %abs to half
  ret half %trunc
}
=>
define half @src(float %x) nofree willreturn memory(none) {
#0:
  %#1 = fptrunc float %x to half
  %trunc = fabs ninf half %#1
  ret half %trunc
}
Transformation doesn't verify!

ERROR: Target is more poisonous than source

Example:
float %x = #x50802003 (17196652544)

Source:
float %abs = #x50802003 (17196652544)
half %trunc = #x7c00 (+oo)

Target:
half %#1 = #x7c00 (+oo)
half %trunc = poison
Source value: #x7c00 (+oo)
Target value: poison

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Alive2: https://alive2.llvm.org/ce/z/DWV3G3
fptrunc yields infinity when the input cannot fit in the target type. So ninf should be propagated from fptrunc. For other intrinsics, the previous check ensures that the result is never an infinity:
https://github.com/llvm/llvm-project/blob/5d3899d293e902124c3602b466031b6b799fb123/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1910-L1917

Closes https://github.com/llvm/llvm-project/issues/143122.

### CODE REVIEW

File: llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp [hunk 1]
```diff
@@ -1926,6 +1926,9 @@ Instruction *InstCombinerImpl::visitFPTrunc(FPTruncInst &FPT) {
       CallInst *NewCI =
           CallInst::Create(Overload, {InnerTrunc}, OpBundles, II->getName());
       NewCI->copyFastMathFlags(II);
+      // A normal value may be converted to an infinity.
+      if (II->getIntrinsicID() == Intrinsic::fabs)
+        NewCI->setHasNoInfs(FPT.hasNoInfs());
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp]: Now that we have FMF on fptrunc, can we always use the fptrunc flags here instead and not bother with the intrinsic flags at all?

**Comment by dtcxzyw** [comment]
FAIL: LLVM :: Transforms/InstCombine/double-float-shrink-2.ll

**Review by nikic — APPROVED** [review]
LGTM
