### PR TITLE
[AArch64] AArch64ISelDAGToDAG.cpp - disable inlining on MSVC release builds

### LINKED ISSUE #114425: [AArch64] Severe AArch64DAGToDAGISel::Select build time regression on MSVC builds
The time taken to build AArch64ISelDAGToDAG.cpp on MSVC release builds has degraded severely over the past few months, with this now taking over 10mins to build on my normal dev machine.

This appears to be entirely due to the size of AArch64DAGToDAGISel::Select and the number of intrinsic expansions (in particular all the additional SME/SVE intrinsics) that are now performed, which appear to all being inlined.

The addition of a `#pragma inline_depth(0)` tag gets the build time to under 2 mins again, and could be an MSVC-only option, but I'd like to ask the aarch64 teams if there's any chance that we can move some of these intrinsics expansions into tablegen instead?

CC @CarolineConcatto @Lukacma @momchil-velikov @MDevereau

### PR DESCRIPTION
**Pull request by RKSimon**
Similar to #110986 - disabling inlining on MSVC release builds avoids an excessive build time issue affecting all recent versions of CL.EXE

Fixes #114425

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp [hunk 1]
```diff
@@ -31,6 +31,11 @@ using namespace llvm;
 #define DEBUG_TYPE "aarch64-isel"
 #define PASS_NAME "AArch64 Instruction Selection"
 
+// https://github.com/llvm/llvm-project/issues/114425
+#if defined(_WIN32) && !defined(__clang__) && !defined(NDEBUG)
```
Comment (sdesmalen-arm) [inline llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:35]: Should this test for MSVC specifically, rather than `!defined(__clang__)` ?

Comment (RKSimon) [reply llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:35]: I've matched #110986 - which IIRC is doing this to avoid it firing on clang-cl

Comment (RKSimon) [reply llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:35]: Yes - clang-cl defines the _MSC_VER macro as well as __clang__ :https://clang.godbolt.org/z/fo9aMYosK

**Review by sdesmalen-arm — APPROVED** [review]

File: llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp (hunk 1 above)
Comment (mstorsjo) [reply llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:35]: But this condition as it stands, `defined(_WIN32) && !defined(__clang__)` will also match for GCC.

The correct one for singling out MSVC but not clang in msvc mode, would be `defined(_MSC_VER) && !defined(__clang__)`.

Comment (RKSimon) [reply llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:35]: I'll create a patch
