### PR TITLE
[RISCV] Allow `Zicsr`/`Zifencei` to duplicate with `g`

### LINKED ISSUE #136803: [RISCV] error: duplicated standard user-level extension 'zifencei' since LLVM 19
See: https://godbolt.org/z/cnan5zh41

Before LLVM 19, we can compile successfully with `-march=rv64gc_zifencei`. But since LLVM 19, it complains:
```
error: invalid arch name 'rv64gc_zifencei', duplicated standard user-level extension 'zifencei'
```

The behavior is not compatible.

Is there something I missed? I know there are issues with `zifencei` implication, did we decide to not accept standalone `zifencei`? But I don't see it in release notes...

### PR DESCRIPTION
**Pull request by wangpc-pp**
This matches GCC and we supported it in LLVM 17/18.

Fixes #136803

### CODE REVIEW

File: llvm/lib/TargetParser/RISCVISAInfo.cpp [hunk 1]
```diff
@@ -717,6 +716,15 @@ RISCVISAInfo::parseArchString(StringRef Arch, bool EnableExperimentalExtension,
     } while (!Ext.empty());
   }
 
+  // We add Zicsr/Zifenci as final to allow duplicated "zicsr"/"zifencei".
```
Comment (lukel97) [inline llvm/lib/TargetParser/RISCVISAInfo.cpp:719]: Nit, give an example that it's duplicated with g?

```suggestion
  // We add Zicsr/Zifenci as final to allow duplicated "rv64g_zicsr_zifencei".
```

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -632,6 +632,8 @@ RISC-V Support
   Qualcomm's `Xqciint` extension to save and restore some GPRs in interrupt
   service routines.
 
+- `Zicsr` / `Zifencei` are allowed to duplicate with `g` in `-march`.
```
Comment (lukel97) [inline clang/docs/ReleaseNotes.rst:635]: Nit
```suggestion
- `Zicsr` / `Zifencei` are allowed to be duplicated in the presence of `g` in `-march`.
```

**Review by lukel97 — APPROVED** [review]
LGTM

**Comment by lukel97** [comment]
If you're planning on backporting this, should the release notes be added in a separate commit? I'm wondering if you'll end up with issues trying to cherry-pick it otherwise

File: llvm/lib/TargetParser/RISCVISAInfo.cpp [hunk 3]
```diff
@@ -717,6 +716,16 @@ RISCVISAInfo::parseArchString(StringRef Arch, bool EnableExperimentalExtension,
     } while (!Ext.empty());
   }
 
+  // We add Zicsr/Zifenci as final to allow duplicated "zicsr"/"zifencei" like
+  // "rv64g_zicsr_zifencei".
+  if (Baseline == 'g') {
+    for (const char *Ext : RISCVGImplicationsZi) {
+      auto Version = findDefaultVersion(Ext);
+      assert(Version && "Default extension version not found?");
+      ISAInfo->Exts[std::string(Ext)] = {Version->Major, Version->Minor};
```
Comment (topperc) [inline llvm/lib/TargetParser/RISCVISAInfo.cpp:725]: Maybe we should skip this assignment if it is already in the string. The user could pass a different version number than the default. Though we only allow the default version from the user today.

**Comment by wangpc-pp** [comment]
According to the sync-up meeting, we can proceed this patch as-is. I will merge this in a few days.

I added back the release note. @asb

**Review by topperc — APPROVED** [review]
LGTM

**Comment by apazos** [comment]
This matter was addressed at the RVI Toolchain SIG meeting on 05/08/25.

It was concluded that the duplication of implied extensions, such as in the cases of G and Zifencei, and F and Zicsr, can be silently disregarded. Both GCC and LLVM toolchains are consistent with this approach through the application of this LLVM patch. 

However, the duplication of unrelated extensions should result in an error message indicating an invalid duplicated extension, which is already implemented in both toolchains.
