### PR TITLE
[mlir][linalg] Bugfix for `InlineScalarOperands`

### LINKED ISSUE #111243: [mlir] Crash when using --linalg-inline-scalar-operands
I have the following MLIR program:
test.mlir:
```
#map = affine_map<(d0, d1, d2) -> ()>
#map1 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @func1(%arg0: tensor<?x?x?xf32>, %arg1: index, %arg2: index) -> (tensor<?x?x?xf32>) {
    %c1_i64 = arith.constant 1 : i64
    %c0_i64 = arith.constant 0 : i64
    %cst = arith.constant 0.000000e+00 : f32
    %0 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "parallel"]} ins(%cst : f32) outs(%arg0 : tensor<?x?x?xf32>) {
    ^bb0(%in: f32, %out: f32):
      linalg.yield %in : f32
    } -> tensor<?x?x?xf32>
    return %0 : tensor<?x?x?xf32>
  }
}
```
The above MLIR program will cause a crash when using the following command:
```
mlir-opt --linalg-inline-scalar-operands test.mlir
```
And the crash backtrace is:
```
mlir-opt: /data/tmp/v1005/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From&) [with To = mlir::TensorType; From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/tmp/v1005/llvm-project/build/bin/mlir-opt --linalg-inline-scalar-operands test.mlir
 #0 0x000056428212843f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x158443f)
 #1 0x00005642821254a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f14b4c7c420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f14b474900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f14b4728859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007f14b4728729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007f14b4739fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x0000564282362e9b decltype(auto) llvm::cast<mlir::TensorType, mlir::Type>(mlir::Type const&) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x17bee9b)
 #8 0x00005642842be308 mlir::tensor::ExtractOp::build(mlir::OpBuilder&, mlir::OperationState&, mlir::Value, mlir::ValueRange) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x371a308)
 #9 0x0000564282edb2a6 (anonymous namespace)::InlineScalarOperands::matchAndRewrite(mlir::linalg::GenericOp, mlir::PatternRewriter&) const InlineScalarOperands.cpp:0:0
#10 0x0000564282a52f2f mlir::detail::OpOrInterfaceRewritePatternBase<mlir::linalg::GenericOp>::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x1eaef2f)
#11 0x00005642885f3dc0 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x7a4fdc0)
#12 0x000056428546c018 (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist() GreedyPatternRewriteDriver.cpp:0:0
#13 0x000056428546ee6b mlir::applyPatternsAndFoldGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x48cae6b)
#14 0x0000564282ed9bca (anonymous namespace)::LinalgInlineScalarOperandsPass::runOnOperation() InlineScalarOperands.cpp:0:0
#15 0x00005642853b74f1 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x48134f1)
#16 0x00005642853b79ca mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x48139ca)
#17 0x00005642853b8514 mlir::PassManager::run(mlir::Operation*) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x4814514)
#18 0x00005642853a9a1b performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#19 0x00005642853aa3e4 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPoolInterface*) MlirOptMain.cpp:0:0
#20 0x00005642853aa594 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#21 0x00005642854b304e mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x490f04e)
#22 0x00005642853a1e39 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x47fde39)
#23 0x00005642853aa701 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x4806701)
#24 0x00005642853aabc6 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x4806bc6)
#25 0x000056428203facb main (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x149bacb)
#26 0x00007f14b472a083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#27 0x00005642820fb62e _start (/data/tmp/v1005/llvm-project/build/bin/mlir-opt+0x155762e)
Aborted (core dumped)
```
My git version is bf895c714e1f8a51c1e565a75acf60bf7197be51.

### PR DESCRIPTION
**Pull request by CoTinker**
This PR fixes a bug where `scalarOperand` is a simple scalar and should be used directly, rather than accessed via `tensor.extract`. Fixes #111243.

### CODE REVIEW

**Comment by CoTinker** [comment]
Ping~

File: mlir/lib/Dialect/Linalg/Transforms/InlineScalarOperands.cpp [hunk 1]
```diff
@@ -78,9 +78,11 @@ struct InlineScalarOperands : public OpRewritePattern<GenericOp> {
       for (auto idx : indices)
         indicesValues.emplace_back(
             rewriter.create<arith::ConstantIndexOp>(loc, idx));
-      Value extractedValue = rewriter.create<tensor::ExtractOp>(
-          loc, opOperand->get(), indicesValues);
-      body->getArgument(idx).replaceAllUsesWith(extractedValue);
+      Value scalarValue = opOperand->get();
+      if (isa<RankedTensorType>(scalarValue.getType()))
```
Comment (MaheshRavishankar) [inline mlir/lib/Dialect/Linalg/Transforms/InlineScalarOperands.cpp:82]: Nit: add `{` `}` around multi-line statements.

**Review by MaheshRavishankar — APPROVED** [review]

File: mlir/lib/Dialect/Linalg/Transforms/InlineScalarOperands.cpp (hunk 1 above)
Comment (CoTinker) [reply mlir/lib/Dialect/Linalg/Transforms/InlineScalarOperands.cpp]: Done
