### PR TITLE
[AArch64] Emit .arch and .arch_extension during assembly to textual asm

### LINKED ISSUE #117221: [MC] Assembly emission removes `.arch`/`.arch_extension` directives
Here is an example program that uses `.arch` in inline assembly to enable LSE instructions:

```c
int main() {
    asm volatile (
        ".arch armv8-a+lse\n"
        "casal x0, x1, [x2]\n"
    );
    return 0;
}
```

If compiled with `clang -c test.c` it works fine, but if I first emit to assembly and then attempt to compile, it no longer succeeds:

```
$ clang -S test.c
$ clang -c test.s
test.s:14:2: error: instruction requires: lse
        casal   x0, x1, [x2]
        ^
```

The generated assembly does not include the `.arch` directive, causing the instruction to be illegal.

```
//APP
casal   x0, x1, [x2]

//NO_APP
```

A similar issue exists for `.arch_directive`

Example:
```c
asm volatile (
    ".arch_extension lse\n"
    "casal x0, x1, [x2]\n"
);
```

Thanks!

### PR DESCRIPTION
**Pull request by zyedidia**
This patch ensures that when assembling to text (`-filetype asm`), `.arch` and `.arch_extension` directives are preserved in the output. This prevents errors related to unavailable extensions in the assembly output (see #117221 for an example).

Fixes #117221.

### CODE REVIEW

File: llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp [hunk 1]
```diff
@@ -7234,6 +7236,8 @@ bool AArch64AsmParser::parseDirectiveArchExtension(SMLoc L) {
     STI.ClearFeatureBitsTransitively(It->Features);
   FeatureBitset Features = ComputeAvailableFeatures(STI.getFeatureBits());
   setAvailableFeatures(Features);
+
+  getTargetStreamer().emitDirectiveArchExtension(Name);
```
Comment (lenary) [inline llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp:7240]: This is wrong, as `Name` might have been updated on (new) line 7222. This would be clear with a `.arch_extension nolse` test.

Comment (zyedidia) [reply llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp]: Thank you for catching that. I have updated the code so that it emits the full name from before the `no` prefix is stripped, along with a test. Let me know if you'd like further changes.

**Review by lenary — APPROVED** [review]
LGTM. Please wait for one of the tagged reviewers to also chime in, they're all at Arm.

**Review by smithp35 — APPROVED** [review]
LGTM too.

I guess this can in theory affect ARM as well, although the .arch+<features> is likely not well supported in ARM either.
