### PR TITLE
[mlir][spirv] Handle vectors of integers of unsupported width

### LINKED ISSUE #118612: [mlir] -convert-to-spirv crashes
git version: d09707070c7460d0887eae8f7022e816510d5eb1

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt  -convert-to-spirv  a.mlir`

a.mlir:  
``` 
func.func @signExtiConstantVector() -> vector<4xi48> {
  %vector = arith.constant dense<[1, 3, 5, 7]> : vector<4xi8>
  %ext = arith.extsi %vector : vector<4xi8> to vector<4xi48>
  return %ext : vector<4xi48>
}
``` 
stack trace:

``` 
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -convert-to-spirv /data/szy/MLIR/seed/seed0/tmp.IpbOKrOrO4.mlir
 #0 0x000055b16a3e0048 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1188048)
 #1 0x000055b16a3ddb5e llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1185b5e)
 #2 0x000055b16a3e09dd SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fdd0b638420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x000055b16d9e08f3 mlir::Type::getContext() const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x47888f3)
 #5 0x000055b16d94a023 mlir::VectorType::get(llvm::ArrayRef<long>, mlir::Type, llvm::ArrayRef<bool>) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x46f2023)
 #6 0x000055b16f252158 (anonymous namespace)::convertVectorType(mlir::spirv::TargetEnv const&, mlir::SPIRVConversionOptions const&, mlir::VectorType, std::optional<mlir::spirv::StorageClass>) SPIRVConversion.cpp:0:0
 #7 0x000055b16f251c70 std::_Function_handler<std::optional<llvm::LogicalResult> (mlir::Type, llvm::SmallVectorImpl<mlir::Type>&), std::enable_if<std::is_invocable_v<mlir::SPIRVTypeConverter::SPIRVTypeConverter(mlir::spirv::TargetEnvAttr, mlir::SPIRVConversionOptions const&)::$_5, mlir::VectorType, llvm::SmallVectorImpl<mlir::Type>&>, std::function<std::optional<llvm::LogicalResult> (mlir::Type, llvm::SmallVectorImpl<mlir::Type>&)>>::type mlir::TypeConverter::wrapCallback<mlir::VectorType, std::enable_if<std::is_invocable_v<mlir::SPIRVTypeConverter::SPIRVTypeConverter(mlir::spirv::TargetEnvAttr, mlir::SPIRVConversionOptions const&)::$_5, mlir::VectorType>, std::function<std::optional<llvm::LogicalResult> (mlir::Type, llvm::SmallVectorImpl<mlir::Type>&)>>::type mlir::TypeConverter::wrapCallback<mlir::VectorType, mlir::SPIRVTypeConverter::SPIRVTypeConverter(mlir::spirv::TargetEnvAttr, mlir::SPIRVConversionOptions const&)::$_5>(mlir::SPIRVTypeConverter::SPIRVTypeConverter(mlir::spirv::TargetEnvAttr, mlir::SPIRVConversionOptions const&)::$_5&&) const::'lambda'(mlir::VectorType, llvm::SmallVectorImpl<mlir::Type>&)>(mlir::SPIRVTypeConverter::SPIRVTypeConverter(mlir::spirv::TargetEnvAttr, mlir::SPIRVConversionOptions const&)::$_5&&) const::'lambda'(mlir::Type, llvm::SmallVectorImpl<mlir::Type>&)>::_M_invoke(std::_Any_data const&, mlir::Type&&, llvm::SmallVectorImpl<mlir::Type>&) SPIRVConversion.cpp:0:0
 #8 0x000055b16d875b8d mlir::TypeConverter::convertType(mlir::Type, llvm::SmallVectorImpl<mlir::Type>&) const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x461db8d)
 #9 0x000055b16d877c47 mlir::TypeConverter::convertType(mlir::Type) const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x461fc47)
#10 0x000055b16f254f33 (anonymous namespace)::FuncOpConversion::matchAndRewrite(mlir::func::FuncOp, mlir::func::FuncOpAdaptor, mlir::ConversionPatternRewriter&) const SPIRVConversion.cpp:0:0
#11 0x000055b16ce56781 mlir::OpConversionPattern<mlir::func::FuncOp>::matchAndRewrite(mlir::func::FuncOp, mlir::func::FuncOpGenericAdaptor<llvm::ArrayRef<mlir::ValueRange>>, mlir::ConversionPatternRewriter&) const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x3bfe781)
#12 0x000055b16ce560ba mlir::OpConversionPattern<mlir::func::FuncOp>::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::ValueRange>, mlir::ConversionPatternRewriter&) const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x3bfe0ba)
#13 0x000055b16d87b704 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4623704)
#14 0x000055b170340851 void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::$_0>(long) PatternApplicator.cpp:0:0
#15 0x000055b17033d51b mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x70e551b)
#16 0x000055b16d87c7d3 (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*, mlir::ConversionPatternRewriter&) DialectConversion.cpp:0:0
#17 0x000055b16d87b827 mlir::OperationConverter::convert(mlir::ConversionPatternRewriter&, mlir::Operation*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4623827)
#18 0x000055b16d87c9ff mlir::OperationConverter::convertOperations(llvm::ArrayRef<mlir::Operation*>) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x46249ff)
#19 0x000055b16d882bbb mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x462abbb)
#20 0x000055b16ce53c8a (anonymous namespace)::ConvertToSPIRVPass::runOnOperation() ConvertToSPIRVPass.cpp:0:0
#21 0x000055b16d81c7a6 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c47a6)
#22 0x000055b16d81d0d0 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c50d0)
#23 0x000055b16d81f6a2 mlir::PassManager::run(mlir::Operation*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c76a2)
#24 0x000055b16d817f4a performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#25 0x000055b16d817b9d llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#26 0x000055b16d8c3d75 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x466bd75)
#27 0x000055b16d811b85 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45b9b85)
#28 0x000055b16d811e2f mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45b9e2f)
#29 0x000055b16d81215e mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45ba15e)
#30 0x000055b16a3c0b37 main (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1168b37)
#31 0x00007fdd0ac56083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#32 0x000055b16a3c06ae _start (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11686ae)
```

### PR DESCRIPTION
**Pull request by kuhar**
Fixes: https://github.com/llvm/llvm-project/issues/118612

### CODE REVIEW

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp [hunk 1]
```diff
@@ -299,6 +299,10 @@ convertScalarType(const spirv::TargetEnv &targetEnv,
 /// supported integer types.
 static Type convertSubByteIntegerType(const SPIRVConversionOptions &options,
                                       IntegerType type) {
+  if (type.getWidth() > 8) {
+    LLVM_DEBUG(llvm::dbgs() << "not a subbyte type\n");
+    return nullptr;
+  }
```
Comment (andfau-amd) [inline mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:305]: This feels like a strange thing to have a runtime error for; if it's for convenience, maybe it should be documented (that nothing is returned if it's not sub-byte), but otherwise it feels like something you'd use an `assert` for, as it represents a bug if this is called on a non-sub-byte type? Maybe others would disagree with me.

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp [hunk 2]
```diff
@@ -292,13 +292,18 @@ convertScalarType(const spirv::TargetEnv &targetEnv,
 }
 
 /// Converts a sub-byte integer `type` to i32 regardless of target environment.
+/// Returns a nullptr for unsupported integer types, including sup-byte types.
```
Comment (andfau-amd) [inline mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:295]: typo: s/sup/sub/

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp (hunk 1 above)
Comment (kuhar) [reply mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:306]: Added a comment. Retuning null on unsupported types follows the general stye of the type conversion in mlir.

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp (hunk 2 above)
Comment (andfau-amd) [reply mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:295]: Also, should this be "including <b>non-</b>sub-byte types"?

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp [hunk 3]
```diff
@@ -348,6 +353,9 @@ convertVectorType(const spirv::TargetEnv &targetEnv,
     }
 
     Type elementType = convertSubByteIntegerType(options, intType);
+    if (!elementType)
+      return nullptr;
```
Comment (andfau-amd) [inline mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:357]: The bug is that previously, it was assumed that if we entered this code path, the integer type was unsupported because of being sub-byte, but it might be unsupported for some other reason?

**Review by andfau-amd — CHANGES_REQUESTED** [review]

File: mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp (hunk 3 above)
Comment (kuhar) [reply mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:357]: The bug was essentially that it assumed that `convertSubByteIntegerType` would always succeed, but this is not the case even prior to my change related to subbyte types.

Comment (andfau-amd) [reply mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp:358]: Thanks. If you want to, you could put this in the pull-request description so it ends up in the commit message, but that may be unnecessary.

**Review by andfau-amd — APPROVED** [review]
