### PR TITLE
[Clang] handle invalid close location in static assert declaration

### LINKED ISSUE #108687: Clang with assertions crashes on invalid code `static_assert(true, ""`
https://gcc.godbolt.org/z/1T39ex4db

```cpp
static_assert(true, ""
```

Uncovered by @dtcxzyw

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #108687

### CODE REVIEW

File: clang/lib/Parse/ParseDeclCXX.cpp [hunk 1]
```diff
@@ -1110,6 +1110,8 @@ Decl *Parser::ParseStaticAssertDeclaration(SourceLocation &DeclEnd) {
   }
 
   T.consumeClose();
+  if (T.getCloseLocation().isInvalid())
+    return nullptr;
```
Comment (cor3ntin) [inline clang/lib/Parse/ParseDeclCXX.cpp:1114]: `consumeClose` returms true on failure so this can just be `if(T.consumeClose()) return nullptr`

Comment (a-tarasyuk) [reply clang/lib/Parse/ParseDeclCXX.cpp]: @cor3ntin Thanks for the review. I've added changes to omit redundant checks.

**Review by cor3ntin — APPROVED** [review]
Thanks, LGTM

**Comment by a-tarasyuk** [comment]
@cor3ntin when you get a chance, could you merge this? I don’t have the permissions. thanks!

**Comment by shafik** [comment]
So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E

Can we figure out which PR this regression came from and make sure the code change makes sense in light of that PR? 

Also please add a more detailed summary to this PR, describing why the crash happens and the approach the PR takes to fixing it.

**Review by shafik — CHANGES_REQUESTED** [review]
So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E

Can we figure out which PR this regression came from and make sure the code change makes sense in light of that PR? 

Also please add a more detailed summary to this PR, describing why the crash happens and the approach the PR takes to fixing it.

**Comment by a-tarasyuk** [comment]
> So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E

@shafik https://gcc.godbolt.org/z/Ebvnjrc8e

**Comment by shafik** [comment]
> > So this looks like a regression: https://gcc.godbolt.org/z/h6GexT18E
> 
> @shafik https://gcc.godbolt.org/z/Ebvnjrc8e

Interesting it crashes in trunk w/o `c++20`: https://gcc.godbolt.org/z/h9xa8eaqo but the backtrace looks the same.

We should test this in C++20 and C++23 as well then.

File: clang/test/SemaCXX/static-assert-cxx20.cpp [hunk 2]
```diff
@@ -0,0 +1,5 @@
+// RUN: %clang_cc1 -std=c++2a -triple=x86_64-linux -fsyntax-only %s -verify
```
Comment (zyn0217) [inline clang/test/SemaCXX/static-assert-cxx20.cpp:1]: You can add another C++20 mode run to clang/test/SemaCXX/static-assert-cxx26.cpp, instead of adding a new file.

Comment (a-tarasyuk) [reply clang/test/SemaCXX/static-assert-cxx20.cpp:1]: The file refers to cxx26 —is it ok to add tests related to C++20 here?"

Comment (zyn0217) [reply clang/test/SemaCXX/static-assert-cxx20.cpp:1]: I believe so, yes. See the example: clang/test/SemaCXX/constant-expression-cxx2b.cpp

Comment (zyn0217) [reply clang/test/SemaCXX/static-assert-cxx20.cpp:1]: Also, you might want to wrap the case with a namespace referring to the issue number.

Furthermore, I think the test should be triaged as a Parser one. Can you please move the test to that directory?

**Comment by zyn0217** [comment]
> Can we figure out which PR this regression came from and make sure the code change makes sense in light of that PR?

https://github.com/llvm/llvm-project/pull/102044. We have backported the P2741R3 implementation to C++11.

**Review by zyn0217 — COMMENTED** [review]
So I took a stab at it.

In `ParseStaticAssertDeclaration()`, we parsed the message in unclosed static_assert as a constant expression rather than an unevaluated string literal per the logic on lines 1079-1089, and this hits the assertion in `BuildStaticAssertDeclaration()`

So this approach gives up building an expression for unclosed expressions, which works but also loses the diagnoses of the condition expression where it would otherwise evaluate to false:


```cpp
static_assert(false, ""
```

Prior to clang 19, with C++11 mode, we give three errors for the above code:

https://gcc.godbolt.org/z/PMPab779n
(note the last `error: static assertion failed`)

While with this patch, we no longer diagnose it. Note that even on the assertion-free trunk with c++26 mode, we do complain about the false conditions. 

I'm not sure if this is acceptable for us.

Maybe an alternative is we could avoid looking ahead tokens if we know it is a string literal:
(Insert it to the look-ahead logic)
```cpp
if (!I && tokenIsLikeStringLiteral(T, getLangOpts()))
  break;
```

**Comment by a-tarasyuk** [comment]
@zyn0217 Thanks for the detailed feedback. I considered handling it earlier and skipping the validation of the closing parenthesis, but I was concerned the message `"expected ';' after 'static_assert'"` might not be accurate in this case., I assumed `""` is a valid string, even if the next token is invalid - it doesn't make this string itself invalid. 

```cpp
static_assert(true, ""  // expected ';' after 'static_assert'
                        // expected ')'
                        // to match this '('


```

**Comment by cor3ntin** [comment]
> I'm not sure if this is acceptable for us.

Yes, I don't think this uncommon failure mode requires doing more heroics than say we expect a parenthesis and don't crash

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by a-tarasyuk** [comment]
@AaronBallman Thanks for the review.

If these changes seem fine, could someone merge them? I don't have the required permissions. thanks
