### PR TITLE
[Clang] prevent null explicit object argument from being deduced

### LINKED ISSUE #102025: Clang crashes when calling an explicit object member function before it is declared.
I'm working on a little project that uses C++16 and does a bunch of compile time programming and metaprogramming, and I've run into this ICE.
[bind-4ddf5a.sh.gz](https://github.com/user-attachments/files/16500926/bind-4ddf5a.sh.gz)
[bind-4ddf5a.cpp.gz](https://github.com/user-attachments/files/16500927/bind-4ddf5a.cpp.gz)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #102025

### CODE REVIEW

File: clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+struct rv {};
+
+template <bool B, typename T> struct enable_if;
+template <typename T> struct enable_if<true, T> { typedef T type; };
+
+template <typename U, typename T>
+typename enable_if<__is_convertible(T, rv), U>::type forward(T &);
+template <typename U, typename T>
+typename enable_if<!__is_convertible(T, rv), U &>::type forward(T &);
+}
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp:13]: You can get rid of all of that

File: clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+struct Foo {
+  template <class T>
+  constexpr auto operator[](this T &&self, auto... i)        // expected-note {{candidate template ignored: substitution failure [with T = Foo &, i:auto = <>]: member '_evaluate' used before its declaration}}
+      -> decltype(_evaluate(std::forward<T>(self), i...)) {
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp:18]:
```suggestion
      -> decltype(_evaluate(self, i...)) {
```

**Review by cor3ntin — COMMENTED** [review]
Fix LGTM
Can you move the test to test/SemaCXX/cxx2b-deducing-this.cpp, 
in a `GH102025` namespace?

**Review by mizvekov — COMMENTED** [review]
I'd have expected we would have a previous step analogous to CheckTemplateArgument which would have bailed out on null explicit arguments, before we started trying to deduce anything.

File: clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp]: @cor3ntin Thanks for the review. I’ve removed unnecessary deps and moved the test to the appropriate file.

Comment (a-tarasyuk) [reply clang/test/SemaTemplate/cxx2b-deduced-explicit-arg.cpp]: @mizvekov Thanks for the feedback. I thought it would be better/safe to explicitly exclude cases where `ObjectType` is used as `ArgType` for the first parameter when the function has `HasExplicitObject`, as this could cause crashes...

https://github.com/llvm/llvm-project/blob/fa343be414f9364911b947f109f3df5539e23068/clang/lib/Sema/SemaTemplateDeduction.cpp#L4371

In other cases, `ArgType` will be based on the arg index. That’s why I added this condition before

https://github.com/llvm/llvm-project/blob/fa343be414f9364911b947f109f3df5539e23068/clang/lib/Sema/SemaTemplateDeduction.cpp#L4464

Or should we completely avoid using `DeduceTemplateArguments` with an empty `ObjectType`?

https://github.com/llvm/llvm-project/blob/6d9cae12bdfcaeb2be10866e20e8883242f02c6c/clang/lib/Sema/SemaOverload.cpp#L7730

I'd appreciate your perspective on that. Thanks

**Comment by cor3ntin** [comment]
I am happy with that.
Trying to move the change to `AddMethodTemplateCandidate` would be more complicated than it's worth as we would
still want to add the function to the overload set for diagnostic purposes

**Review by cor3ntin — APPROVED** [review]

**Comment by a-tarasyuk** [comment]
@cor3ntin Thanks for the review. I've resolved conflicts. Could you merge it after the CI passes? Thanks

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 3]
```diff
@@ -4462,6 +4462,9 @@ TemplateDeductionResult Sema::DeduceTemplateArguments(
       ParamTypesForArgChecking.push_back(ParamType);
 
       if (ParamIdx == 0 && HasExplicitObject) {
+        if (ObjectType.isNull())
+          return TemplateDeductionResult::InvalidExplicitArguments;
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:4466]: It is expected from this return code that `Info.Param` will be pointing to the relevant parameter with invalid explicit argument. So you would need something like:
 ```C++
    Info.Param = makeTemplateParameter(TemplateParams->getParam(0));
```

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:4466]: Also, if we already diagnosed the error that led to the null template argument, the most appropriate return code would be `TemplateDeductionResult::AlreadyDiagnosed`.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:4466]: @mizvekov thanks for your feedback. I assumed `TemplateDeductionResult::AlreadyDiagnosed` was intended for situations where the checker has already detected errors. Is it? Should I revert these changes, or would opening a new issue/PR be better?

/cc @cor3ntin

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:4466]: If we already diagnosed it, or if we are in the process of diagnosing it anyway regardless of any details this function will provide, that would be the most sensible return code.

Any other return code assumes that it is providing error information that will help diagnose the problem down the line.

But we are currently bad at diagnosing deduction failures anyway, and a lot of these deduction error codes are presently ignored, so there are probably no consequences yet.
