### PR TITLE
[HLSL] Desugar ConstantArrayType when calculating cbuffer field layout

### LINKED ISSUE #134668: [HLSL] Cbuffer declaration with array typedef crashes
This code should compile, and if you use 'uint32_t4' directly in the cbuffer instead of the typedef it does.
https://godbolt.org/z/4nx4zsMdf

The type needs to be desugared before being cast to a ConstantArrayType.

### PR DESCRIPTION
**Pull request by spall**
When calculating the layout for a cbuffer field, if that field is a ConstantArrayType, desguar it before casting it to a ConstantArrayType.
Closes #134668

### CODE REVIEW

**Review by farzonl — APPROVED** [review]

File: clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp [hunk 1]
```diff
@@ -195,7 +195,8 @@ bool HLSLBufferLayoutBuilder::layoutField(const FieldDecl *FD,
     // Unwrap array to find the element type and get combined array size.
     QualType Ty = FieldTy;
     while (Ty->isConstantArrayType()) {
-      const ConstantArrayType *ArrayTy = cast<ConstantArrayType>(Ty);
+      const ConstantArrayType *ArrayTy =
+          cast<ConstantArrayType>(Ty.getDesugaredType(CGM.getContext()));
```
Comment (hekota) [inline clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp:199]:
```suggestion
          cast<ConstantArrayType>(Ty->getUnqualifiedDesugaredType());

```

**Review by hekota — APPROVED** [review]
LGTM! One suggestion to use `getUnqualifiedDesugaredType` instead of `getDesugaredType` that requires a context.

**Review by llvm-beanz — APPROVED** [review]

File: clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp [hunk 2]
```diff
@@ -195,7 +195,8 @@ bool HLSLBufferLayoutBuilder::layoutField(const FieldDecl *FD,
     // Unwrap array to find the element type and get combined array size.
     QualType Ty = FieldTy;
     while (Ty->isConstantArrayType()) {
-      const ConstantArrayType *ArrayTy = cast<ConstantArrayType>(Ty);
+      const ConstantArrayType *ArrayTy =
+          cast<ConstantArrayType>(Ty->getUnqualifiedDesugaredType());
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/HLSLBufferLayoutBuilder.cpp:199]:
```suggestion
      auto *ArrayTy = CGM.getContext().getAsConstantArrayType(Ty);
```

**Review by efriedma-quic — APPROVED** [review]
