### PR TITLE
[OpenMP][FIX] Ensure we do not read outside the device image

### LINKED ISSUE #74582: OpenMP Offload test barrier_fence fails on AMDGPU
The test https://github.com/llvm/llvm-project/blob/main/openmp/libomptarget/test/offloading/barrier_fence.c is failing.

Started failing around 
https://lab.llvm.org/buildbot/#/builders/193/builds/43154
https://lab.llvm.org/buildbot/#/builders/193/builds/43156
https://lab.llvm.org/buildbot/#/builders/193/builds/43159

Disabling while investigating.

### PR DESCRIPTION
**Pull request by jdoerfert**
Before we expected all symbols in the device image to be backed up with data that we could read. However, uninitialized values are not. We now check for this case and avoid reading random memory.

This also replaces the correct readGlobalFromImage call with a isSymbolInImage check after
https://github.com/llvm/llvm-project/pull/74550 picked the wrong one.

Fixes: https://github.com/llvm/llvm-project/issues/74582

### CODE REVIEW

File: openmp/libomptarget/plugins-nextgen/common/src/GlobalHandler.cpp [hunk 1]
```diff
@@ -53,9 +57,15 @@ Error GenericGlobalHandlerTy::getGlobalMetadataFromELF(
     const ELF64LE::Shdr &Section, GlobalTy &ImageGlobal) {
 
   // The global's address is computed as the image begin + the ELF section
-  // offset + the ELF symbol value.
-  ImageGlobal.setPtr(advanceVoidPtr(
-      Image.getStart(), Section.sh_offset - Section.sh_addr + Symbol.st_value));
+  // offset + the ELF symbol value except for NOBITS sections that, as the name
+  // suggests, have no bits in the image. We still record the size and use
+  // nullptr to indicate there is no location.
+  if (Section.sh_type == ELF::SHT_NOBITS)
```
Comment (jhuber6) [inline openmp/libomptarget/plugins-nextgen/common/src/GlobalHandler.cpp:63]: Not directly related, but could we remove this function from `GenericGlobalHandlerTy` and just make this a utility in `Elf.cpp` like `getSymbolAddr` that returns said void pointer?

Comment (jhuber6) [reply openmp/libomptarget/plugins-nextgen/common/src/GlobalHandler.cpp:63]: Sure, it makes more sense to avoid propagating ELF specific stuff from the generic interface.

**Review by jhuber6 — APPROVED** [review]
