### PR TITLE
[Clang] Fix handling of overloads differing only by constraints and ref-qualifiers

### LINKED ISSUE #120812: GH58962 regression: Clang rejects &-qualified member function to be overloaded with const-qualified with mutual exclusive constraints
Worked in: Clang 17
Stop working since: Clang 18

### Symptom

Clang 18.1.0 and trunk reject the following program in `-std=c++20`, but accept it in `-std=c++23`. Clang 17.1.0 accepts it in `-std=c++20`, so does GCC and MSVC.

```cpp
namespace GH58962_alt
{

template <unsigned R> struct type
{
    void func() const
        requires(R == 0);
    void func() &
        requires(R == 1);
};

template <typename T>
concept test = requires(T v) { decltype(v)(v).func(); };

static_assert(test<type<0> &>);
static_assert(test<type<0> &&>);
static_assert(test<type<1> &>);
static_assert(not test<type<1> &&>);

static_assert(test<type<0> const &>);
static_assert(test<type<0> const &&>);
static_assert(not test<type<1> const &>);
static_assert(not test<type<1> const &&>);

} // namespace GH58962_alt
```

https://godbolt.org/z/vY63TE43K

### PR DESCRIPTION
**Pull request by cor3ntin**
We should only error about inconsistent qualifiers if the functions are actually overloads.

Fixes #120812

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]

File: clang/test/CXX/drs/cwg24xx.cpp [hunk 1]
```diff
@@ -212,5 +212,16 @@ struct T : S {
     virtual void k() &;
     virtual void l() &&;
 };
+#if __cplusplus >= 202002L
+
+// We should not error on inconsistent ref-qualifiers if the functions
+// have different constraints.
+template <unsigned R> struct type {
+    void func() const requires(R == 0);
+    void func() & requires(R == 1);
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg24xx.cpp:221]: No overriding of virtual functions is happening here. Why is this case in CWG2496 test?
