### PR TITLE
[ELF] Support NOCROSSREFS and NOCROSSERFS_TO

### LINKED ISSUE #41825: "NOCROSSREFS_TO" doesn't supported by LLVM's ld.lld
|  |  |
| --- | --- |
| Bugzilla Link | [42480](https://llvm.org/bz42480) |
| Version | unspecified |
| OS | Linux |
| CC | @P1119r1m,@smithp35 |

## Extended Description 
Build fails on the use of "NOCROSSREFS_TO" command in linker script.

Example:
- funnyos.lds.S:
```
...
NOCROSSREFS_TO (.init .text .data)
...
ENTRY(_start)
...
```

Reported build/link error:
```
ld.lld: error: core/funnyos.lds:11: unknown directive: NOCROSSREFS_TO
>>> NOCROSSREFS_TO (.init .text .data)
>>> ^
```

P.S. Problem also reported on https://stackoverflow.com/questions/56235666/is-it-possible-to-use-nocrossrefs-to-in-linker-script-for-clangs-ld-lld

### PR DESCRIPTION
**Pull request by MaskRay**
Implement the two commands described by
https://sourceware.org/binutils/docs/ld/Miscellaneous-Commands.html

After `outputSections` is available, check each output section described
by at least one `NOCROSSREFS`/`NOCROSSERFS_TO` command. For each checked
output section, scan relocations from its input sections.
This step is slow, therefore utilize `parallelForEach(isd->sections, ...)`.

To support non SHF_ALLOC sections, `InputSectionBase::relocations`
(empty) cannot be used. In addition, we may explore eliminating this
member to speed up relocation scanning.

Some parse code is adapted from #95714.

Close #41825

### CODE REVIEW

File: lld/ELF/ScriptParser.cpp [hunk 1]
```diff
@@ -299,6 +304,15 @@ void ScriptParser::readDefsym(StringRef name) {
...
 }
 
+void ScriptParser::readNoCrossRefs(bool to) {
+  expect("(");
+  NoCrossRefCommand cmd{{}, to};
+  while (!errorCount() && !consume(")"))
+    cmd.outputSections.push_back(unquote(next()));
+  if (cmd.outputSections.size() >= 2)
+    script->noCrossRefs.push_back(std::move(cmd));
+}
```
Comment (smithp35) [inline lld/ELF/ScriptParser.cpp:314]: Would it be worth a warning if the `outputSections.size() < 2` I don't think there could be a legal use case for `NOCROSSREFS()` or `NOCROSSREFS(<section>)`.

File: lld/ELF/Relocations.cpp [hunk 2]
```diff
@@ -2367,7 +2367,63 @@ void elf::hexagonTLSSymbolUpdate(ArrayRef<OutputSection *> outputSections) {
...
+    return cmd.outputSections[0] == osec;
+  return llvm::is_contained(cmd.outputSections, osec);
+}
+
+template <class ELFT, class Rels>
+static void scanCrossRefs(const NoCrossRefCommand &cmd, OutputSection *osec,
+                          InputSection *sec, Rels rels) {
+  for (const auto &r : rels) {
+    Symbol &sym = sec->file->getSymbol(r.getSymbol(config->isMips64EL));
+    // The destination output section can be nullptr, osec, or those described
```
Comment (smithp35) [inline lld/ELF/Relocations.cpp:2381]: I'm don't fully understand what 
``` or those described by the NOCROSSREFS/NOCROSSREFS_TO command.``` means in this context.

If the comment is describing permitted cross-references then I'd expect something like:
```A legal cross-reference is when the destination output section is nullptr, osec for a self-reference, or a section that is not in the set described by the NOCROSSREFS/NOCROSSREFS_TO command.```

File: lld/ELF/Relocations.cpp [hunk 3]
```diff
@@ -2367,7 +2367,63 @@ void elf::hexagonTLSSymbolUpdate(ArrayRef<OutputSection *> outputSections) {
...
 
+static bool matchesRefTo(const NoCrossRefCommand &cmd, StringRef osec) {
+  if (cmd.toFirst)
+    return cmd.outputSections[0] == osec;
+  return llvm::is_contained(cmd.outputSections, osec);
+}
+
+template <class ELFT, class Rels>
+static void scanCrossRefs(const NoCrossRefCommand &cmd, OutputSection *osec,
+                          InputSection *sec, Rels rels) {
```
Comment (smithp35) [inline lld/ELF/Relocations.cpp:2378]: For a NoCrossRefCommand cmd with `toFirst == true` can we early exit if osec == cmd.outputSections[0]? 

This would be the case where we search the relocations from `tosection`.

**Review by smithp35 — COMMENTED** [review]
Only a small number of comments, otherwise LGTM.

File: lld/ELF/Relocations.cpp (hunk 2 above)
Comment (MaskRay) [reply lld/ELF/Relocations.cpp:2381]: Thanks for the suggestion. Improved the comment.

File: lld/ELF/Relocations.cpp (hunk 3 above)
Comment (MaskRay) [reply lld/ELF/Relocations.cpp:2378]: Added an early return to `elf::checkNoCrossRefs`: `(noxref.toFirst && noxref.outputSections[0] == osec->name)`

File: lld/ELF/ScriptParser.cpp (hunk 1 above)
Comment (MaskRay) [reply lld/ELF/ScriptParser.cpp:316]: Added a warning.

**Review by smithp35 — APPROVED** [review]
LGTM thanks for the updates.
