### PR TITLE
[flang][runtime] Build ISO_FORTRAN_ENV to export kind arrays as linkable symbols

### LINKED ISSUE #89403: [flang] Linker for non-constant accesses to kind arrays (integer_kind, logical_kind, real_kind)
When compiling a code like this:

```Fortran
program kinds_issue
   use, intrinsic :: iso_fortran_env, only: integer_kinds
   implicit none
   integer :: k
   k=1
   write (*,'(I0)') integer_kinds(k)
end program
```

Results in an error like this:

```
FIRModule:(.text+0x4e): undefined reference to `_QMiso_fortran_envECinteger_kinds'
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by mjklemm**
Moves definitions of the kind arrays into a Fortran MODULE to not only emit the MOD file, but also compile that MODULE file into an object file.  This file is then linked into libFortranRuntime.so.

Eventually this workaround PR shoud be redone and a proper runtime build should be setup that will then also compile Fortran MODULE files.

Fixes #89403

### CODE REVIEW

File: flang/module/__fortran_builtin_kinds.f90 [hunk 1]
```diff
@@ -0,0 +1,110 @@
+!===-- module/__fortran_bultin_kinds.f90 --=--------------------------------===!
```
Comment (klausler) [inline flang/module/__fortran_builtin_kinds.f90:1]: why can't these definitions remain in iso_fortran_env?

**Comment by clementval** [comment]
Did you move the definitions because you get an error compiling the full `iso_fortran_env.f90` file? I think we can just wrap the part used during folding in a macro and not include it when we build the object file.

File: flang/tools/flang-driver/CMakeLists.txt [hunk 2]
```diff
@@ -19,8 +19,6 @@ add_flang_tool(flang-new
   # These libraries are used in the linker invocation generated by the driver
   # (i.e. when constructing the linker job). Without them the driver would be
   # unable to generate executables.
```
Comment (clementval) [inline flang/tools/flang-driver/CMakeLists.txt:21]: You can probably also remove the comment

**Comment by sscalpone** [comment]
Thanks for looking at this, @mjklemm !   My thought was to move the build of the module files to be part of the runtime build.     One advantage is that the object file can be put into the libFortranRuntime.  The other is that the module file build is more closely associated with the target instead of the host.

**Comment by mjklemm** [comment]
I consider this a first step to resolve the bug, albeit with a workaround.  In the long run, I totally agree that the Fortran runtime part should be built like any other LLVM runtime.

As part of that the module file should be considered to move to be within in the runtime folder and also the CMake for it should move from tools/f18 into the runtime folder.  I think that would greatly simplify the CMake code needed.

File: flang/tools/flang-driver/CMakeLists.txt (hunk 2 above)
Comment (mjklemm) [reply flang/tools/flang-driver/CMakeLists.txt:21]: Good point.  Will do.

File: flang/module/__fortran_builtin_kinds.f90 (hunk 1 above)
Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: Flang was giving me compiler errors for numeric_storage_size, which seems it needs to not be compiled as part of the module file but rather as part of when the module has been included into the host routine.

That's I basically went back to my original idea of how I wanted to fix the bug and moved the intrinsic definitions into their own module file.

**Comment by mjklemm** [comment]
> Did you move the definitions because you get an error compiling the full `iso_fortran_env.f90` file? I think we can just wrap the part used during folding in a macro and not include it when we build the object file. 
> 
> 
> 
> This is the part of the module I'm talking about:
> 
> 
> 
> ```
> 
>   intrinsic :: __builtin_numeric_storage_size
> 
>   ! This value depends on any -fdefault-integer-N and -fdefault-real-N
> 
>   ! compiler options that are active when the module file is read.
> 
>   integer, parameter, public :: numeric_storage_size = &
> 
>     __builtin_numeric_storage_size()
> 
> ```

Yes, exactly.  I think we can leave this as is if we feel that moving the compiled part of iso_fortran_env into it's own module file like I did.

Not sure if we would need this for other stuff in the future, but maybe splitting the intrinsic modules into an implementation file and a definitions file might be something to consider going forward.

File: flang/tools/flang-driver/CMakeLists.txt (hunk 2 above)
Comment (mjklemm) [reply flang/tools/flang-driver/CMakeLists.txt:21]: Done

File: flang/module/__fortran_builtin_kinds.f90 (hunk 1 above)
Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: __builtin_numeric_storage_size() gets special treatment in folding that can easily be adjusted without this kind of disruption.

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: Can you provide a hint how this could be done?  I'm not that deep into the inner workings for Flang yet to see how this can be done.

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: Grep for `builtin_numeric_storage` and you'll see what's going on.

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: I have done that already.  Thing is: when the context is right, `__build_numeric_storage_size` is immediately folded.  However, then compiling `iso_fortran_env.f90`, line 1324-1326 in `fold-integer.cpp` simply leave the evaluation of `__builtin_numeric_storage_size` in the intermediate code, so that the code-gen picks it up and utterly complains about not having code-gen for it.  So, I have tried to add that, but that does not seem the right path to me.

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: Ping :-)

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: yes?

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: Is my sketched approach the correct one or is there a simpler and better way to keep the original expression when compiling the module file?

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: I'm confident that the problem can be solved without splitting the module source file by properly defining the compilations in which the folding the intrinsic must be deferred.

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: Honestly, I did not see how.  So, hints or even a patch about how to do this will be appreciated.

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: In `flang/lib/Evaluate/fold-integer.cpp` ca. line 1340 is the code that folds (underscore underscore) `builtin_numeric_storage`.  It defers that folding today until the reference to that intrinsic function is coming from a module file, at which point the size of a default numeric storage unit must be known.  If you're changing things so that `ISO_FORTRAN_ENV` is now going to be compiled with the size of a default numeric storage unit being well-defined, then you can probably just remove the code that defers the folding.

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: When I remove the code, the compiler folds the current value `32_4` into the `iso_fortran_env.mod` file.  From there on, `numeric_storage_size` always reports 32 as the storage size, regardless of compiler options.

The code removed:

```C++
    if (!context.moduleFileName()) {
      // Don't fold this reference until it appears in the module file
      // for ISO_FORTRAN_ENV -- the value depends on the compiler options
      // that might be in force.
    } else {
```

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: Yes, but since you now need to also compile the modules into distinct `*.o` files for each combination of target and relevant compilation options, isn't that what has to happen?

Comment (mjklemm) [reply flang/module/__fortran_builtin_kinds.f90:1]: That's not needed, if we do the separation like I'm proposing in this PR.  Everything that is compiled into an object file is independent of the relevant compiler options (like `-fdefault-real-8`), while `numeric_storage_size` is left in `iso_fortran_env` that is only treated with `-fsyntax-only`, which resolves the whole issue w/o touching the compiler itself.

Comment (klausler) [reply flang/module/__fortran_builtin_kinds.f90:1]: And complicated module file shenanigans are better somehow than "touching" the compiler?  I guess that's a matter of opinion.  I'll let you find some other reviewer for this, but you can help them out by at least documenting what's going on here with some comments, and fixing the name of the file in its header.

File: flang/tools/f18/CMakeLists.txt [hunk 3]
```diff
@@ -58,18 +76,41 @@ if (NOT CMAKE_CROSSCOMPILING)
...
+    # the link line for the FortranRuntime library.
+    if(include_in_link)
+      set(module_objects ${module_} ${object_output})
+    endif()
   endforeach()
 
+  # Set a CACHE variable that is visible to the CMakeLists.txt in runtime/, so that
+  # the compiled Fortran modules can be added to the link line of the FortranRuntime
+  # library.
+  set(FORTRAN_MODULE_OBJECTS ${module_objects} CACHE INTERNAL "")
```
Comment (Meinersbur) [inline flang/tools/f18/CMakeLists.txt:112]:
```suggestion
  set(FORTRAN_MODULE_OBJECTS ${module_objects} CACHE INTERNAL "" FORCE)
```
Without the [`FORCE`](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry) flag, the cached value will only be overwritten if it was not previously listed in `CMakeCache.txt`. So if a patch ever adds another module_object, all previous CMake build directories must be deleted.

A better alternative is [`set_property(GLOBAL PROPERTY ...)`](https://cmake.org/cmake/help/latest/command/set_property.html). `set(... CACHE)` does not use any caching and works as long as `set_property` and `get_property` are evaluated in the expected order (this file before `runtime/CMakeLists.txt`).

File: flang/module/iso_fortran_env_impl.f90 [hunk 4]
```diff
@@ -0,0 +1,114 @@
+!===-- module/__fortran_bultin_kinds.f90 --=--------------------------------===!
```
Comment (clementval) [inline flang/module/iso_fortran_env_impl.f90:1]:
```suggestion
!===-- module/iso_fortran_env_impl.f90 --=--------------------------------===!
```

**Comment by mjklemm** [comment]
I have made the requested updates.

**Comment by mjklemm** [comment]
@kkwli @Meinersbur @clementval Ping :-)

File: flang/tools/f18/CMakeLists.txt [hunk 5]
```diff
@@ -58,18 +76,41 @@ if (NOT CMAKE_CROSSCOMPILING)
...
         ${FLANG_SOURCE_DIR}/module/${filename}.f90
       DEPENDS flang-new ${FLANG_SOURCE_DIR}/module/${filename}.f90 ${FLANG_SOURCE_DIR}/module/__fortran_builtins.f90 ${depends}
     )
     list(APPEND MODULE_FILES ${base}.mod)
     install(FILES ${base}.mod DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/flang")
+
+    # If a module has been compiled into an object file, add the file to
+    # the link line for the FortranRuntime library.
+    if(include_in_link)
+      set(module_objects ${module_} ${object_output})
```
Comment (Meinersbur) [inline flang/tools/f18/CMakeLists.txt:105]:
```suggestion
      list(APPEND module_objects ${module_})
```

File: flang/module/iso_fortran_env_impl.f90 [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+  integer, parameter, dimension(*), public :: __builtin_real_kinds = [ &
+      pack([real16], real16 >= 0), &
+      pack([bfloat16], bfloat16 >= 0), &
+      pack([real32], real32 >= 0), &
+      pack([real64], real64 >= 0), &
+      pack([real80], real80 >= 0), &
+      pack([real64x2], real64x2 >= 0), &
+      pack([real128], real128 >= 0) &
+    ]
+end module iso_fortran_env_impl
```
Comment (Meinersbur) [inline flang/module/iso_fortran_env_impl.f90:114]: [nit] Missing newline at end of file (UNIX convention; C and C++ before C++11 even require it)

**Review by Meinersbur — APPROVED** [review]
LGTM, with two nits.

**Comment by Meinersbur** [comment]
Btw, you should remove the draft status so flang category subscribers are notified

**Review by kkwli — APPROVED** [review]
LG

File: flang/runtime/CMakeLists.txt [hunk 7]
```diff
@@ -169,6 +169,7 @@ set(sources
   unit-map.cpp
   unit.cpp
   utf.cpp
+  ${FORTRAN_MODULE_OBJECTS}
```
Comment (vzakhari) [inline flang/runtime/CMakeLists.txt:172]: This breaks some of my builds.  I believe this won't work in general unless you make sure that the object file is built before `FortranRuntime` target tries to build, i.e. there has to be a target dependency in this CMake file.

I think you can try to reproduce it by deleting the module object file and running `make FortranRuntime` - it will fail with something like:
```
No rule to make target `tools/flang/tools/f18/iso_fortran_env_impl.o', needed by `lib/libFortranRuntime.a'.  Stop.
```

Comment (mjklemm) [reply flang/runtime/CMakeLists.txt:172]: On it.  Seems like Ninja understands the dependency, as it has a single build file that seems the generated object file in one place and defers the target in the runtime libraries until that object file has been built.  This does not seem to be the case for Makefile builds, because they are split across different Makefiles.

Comment (mjklemm) [reply flang/runtime/CMakeLists.txt:172]: Created https://github.com/llvm/llvm-project/pull/99737 to hopefully resolve this.  Can you please see if the PR resolves the issue?

And sorry for breaking your builds!

Comment (vzakhari) [reply flang/runtime/CMakeLists.txt:172]: Thank you, Michael.  No problem, it should fix my builds, and building `module_files` target before the complete build was a workaround for me.
