### PR TITLE
[mlir] Fix `--mlir-print-ir-tree-dir` when the symbol name contains `/`

### LINKED ISSUE #137622: `--mlir-print-ir-tree-dir` fails with "Error while creating directory ...: No such file or directory" if symbol name contains path separator
Consider the following example MLIR code in `/tmp/test.mlir`:
```mlir
module @"/foo/bar/" {}
```

Running `mlir-opt --canonicalize --mlir-print-ir-before-all --mlir-print-ir-after-all /tmp/test.mlir` outputs the following (as expected):
```
// -----// IR Dump Before Canonicalizer (canonicalize) //----- //
module @"/foo/bar/" {
}


// -----// IR Dump After Canonicalizer (canonicalize) //----- //
module @"/foo/bar/" {
}


module @"/foo/bar/" {
}

```

But when `--mlir-print-ir-tree-dir=/tmp/test` is added to the command - `mlir-opt --canonicalize --mlir-print-ir-before-all --mlir-print-ir-after-all --mlir-print-ir-tree-dir=/tmp/test /tmp/test.mlir` - the output is the following (note the errors):
```
Error while creating directory /tmp/test/builtin_module_/foo/bar/: No such file or directory
Error while creating directory /tmp/test/builtin_module_/foo/bar/: No such file or directory
module @"/foo/bar/" {
}

```
...and the `/tmp/test/` directory is empty.

There is no issue if `/` is swapped for `\` (I am on MacOS, on Windows it may be the opposite):
```
mlir-opt --canonicalize --mlir-print-ir-before-all --mlir-print-ir-after-all --mlir-print-ir-tree-dir=/tmp/test /tmp/test.mlir
module @"\\foo\\bar\\" {
}

tree /tmp/test                                                                                                                                              
/tmp/test
└── builtin_module_\foo\bar\
    ├── 0_canonicalize.mlir
    └── 1_canonicalize.mlir

2 directories, 2 files
```

The code responsible for generating paths is sanitizing op names by replacing `.` with `_`, but does nothing to symbol names:
https://github.com/llvm/llvm-project/blob/e086d7b1464ad091ae849cb907f8647c8439cb66/mlir/lib/Pass/IRPrinting.cpp#L207-L240

[Symbol names can be string literals](https://mlir.llvm.org/docs/LangRef/#identifiers-and-keywords), so there is a need to sanitize them before using in filesystem paths.

### PR DESCRIPTION
**Pull request by joker-eph**
Fixes #137622

### CODE REVIEW

File: mlir/lib/Pass/IRPrinting.cpp [hunk 1]
```diff
@@ -210,22 +211,25 @@ struct BasicIRPrinterConfig : public PassManager::IRPrinterConfig {
...
   Operation *iter = op;
   ++counters.try_emplace(op, -1).first->second;
   while (iter) {
     countPrefix.push_back(counters[iter]);
-    StringAttr symbolName =
+    StringAttr symbolNameAttr =
         iter->getAttrOfType<StringAttr>(SymbolTable::getSymbolAttrName());
+    std::string symbolName =
+        symbolNameAttr ? symbolNameAttr.str() : "no-symbol-name";
+    llvm::replace(symbolName, '/', '_');
```
Comment (j2kun) [inline mlir/lib/Pass/IRPrinting.cpp:228]: The linked issue mentions Windows. I don't know what the expectation of Windows support is for MLIR, but if it is in scope, perhaps you could also add backslash substitution here?

**Review by j2kun — APPROVED** [review]

File: mlir/lib/Pass/IRPrinting.cpp (hunk 1 above)
Comment (joker-eph) [reply mlir/lib/Pass/IRPrinting.cpp:228]: Thanks!
I pushed a change to the test, trying to make the windows build fail first (since I can't test it myself), assuming the test fails I'll then push an update to fix it.

**Review by christopherbate — APPROVED** [review]
LGTM. I was wondering if there was a standard LLVM "sanitization" function for path names. Especially on Windows there could be a lot of edge cases for strings that are allowed symbol names but are not valid Windows path names.

**Comment by joker-eph** [comment]
The test fails on Windows as expected: 

> # | Error while creating directory C:\ws\src\build\tools\mlir\test\Pass\Output\ir-printing-file-tree.mlir.tmp\builtin_module_outer\func_func_sym\backslash: no such file or directory

I pushed the fix now, should fix the CI.

>  I was wondering if there was a standard LLVM "sanitization" function for path names. Especially on Windows there could be a lot of edge cases for strings that are allowed symbol names but are not valid Windows path names.

Good point: I searched in `llvm/include/llvm/Support/FileSystem.h` but couldn't find anything right now.
