### PR TITLE
[AMDGPU] Clean up functions for checking inline literals

### LINKED ISSUE #79369: [AMDGPU] Incorrect parsing of bf16 literals
bf16 immediate operands are not handled correctly by asm parser (but seem OK in the codegen):
```
llvm-mc -arch=amdgcn -mcpu=gfx1200 -show-encoding <<< 'v_dot2_bf16_bf16 v5, v1, v2, 100.0'
v_dot2_bf16_bf16 v5, v1, v2, 0x5640     ; encoding: [0x05,0x00,0x67,0xd6,0x01,0x05,0xfe,0x03,0x40,0x56,0x00,0x00]
```
bf16 constants are essentially fp32 with all zero low 16 bits. So 100.0 shall be encoded as 0x42c80000, and since we only accept 16 bits in the asm hex for it has to be 0x42c8.
```
llvm-mc -arch=amdgcn -mcpu=gfx1200 -show-encoding <<< 'v_dot2_bf16_bf16 v5, v1, v2, 1.0'
v_dot2_bf16_bf16 v5, v1, v2, 0x3c00     ; encoding: [0x05,0x00,0x67,0xd6,0x01,0x05,0xfe,0x03,0x00,0x3c,0x00,0x00]
```
This shall be inline immediate.

Basically we are parsing bf16 constants as f16.

### PR DESCRIPTION
**Pull request by shiltian**
This patch cleans up functions for checking inline literals.

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/AMDGPUISelDAGToDAG.h [hunk 1]
```diff
@@ -107,10 +107,6 @@ class AMDGPUDAGToDAGISel : public SelectionDAGISel {
   std::pair<SDValue, SDValue> foldFrameIndex(SDValue N) const;
   bool isInlineImmediate(const SDNode *N) const;
 
-  bool isInlineImmediate16(int64_t Imm) const {
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUISelDAGToDAG.h:110]: What's the plus of removing this if there's no change to the underlying helper function?

Comment (shiltian) [reply llvm/lib/Target/AMDGPU/AMDGPUISelDAGToDAG.h:110]: The change of `AMDGPU::isInlinableLiteral16` will come soon and then there is no sufficient information here to call the new function. Besides, these functions are literally unused. I don't see any point of keeping them.

File: llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.h [hunk 2]
```diff
@@ -353,7 +353,6 @@ class AMDGPUInstructionSelector final : public InstructionSelector {
   void renderFPPow2ToExponent(MachineInstrBuilder &MIB, const MachineInstr &MI,
                               int OpIdx) const;
 
-  bool isInlineImmediate16(int64_t Imm) const;
```
Comment (Sisyph) [inline llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.h:356]: I see this function as well as isInlineImmediate32 and isInlineImmediate64 are called in
AMDGPUGenGlobalISel.inc AMDGPUInstructionSelector::testImmPredicate_I64, but I'm not sure if that function is used. 

Perhaps you can remove all 3 functions?

**Comment by shiltian** [comment]
gentle ping

File: llvm/lib/Target/AMDGPU/SIInstrInfo.td [hunk 3]
```diff
@@ -797,16 +797,8 @@ def i64imm_32bit : ImmLeaf<i64, [{
...
-  return isInlineImmediate16(Imm);
-}]>;
-
-def InlineImm32 : ImmLeaf<i32, [{
-  return isInlineImmediate32(Imm);
-}]>;
-
 def InlineImm64 : ImmLeaf<i64, [{
-  return isInlineImmediate64(Imm);
+  return isInlineImmediate(APInt(64, static_cast<uint64_t>(Imm)));
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIInstrInfo.td:801]: Can you use IntImmLeaf instead of ImmLeaf here? That way Imm will already be an APInt so you won't have to construct a new APInt.

**Review by jayfoad — APPROVED** [review]
LGTM.
