### PR TITLE
[libc++] Fix ambiguity due to non-uglified member typedefs

### LINKED ISSUE #121618: [libc++] `std::bitset` has non-uglified member typedefs `size_type`, `difference_type`, and `const_reference` causing ambiguity in name lookup
Due to the presence of non-uglified member typedef-names in `std::bitset`, the following program fails to compile in libc++ (while it compiles successfully in libstdc++ and MSVC):

https://godbolt.org/z/4EGY13eah

```cpp
#include <bitset>

struct MyBase {
  using const_reference = const int&;
  using size_type = unsigned;
  using difference_type = int;
};

struct MyDerived : MyBase, std::bitset<42> {};

int main() {
  MyDerived::const_reference r{};
  MyDerived::size_type s{};
  MyDerived::difference_type d{};
}
```

#### Affected Lines:

https://github.com/llvm/llvm-project/blob/e3dafa88a8f651825ac65aad9b273983598279dd/libcxx/include/bitset#L170-L174

https://github.com/llvm/llvm-project/blob/e3dafa88a8f651825ac65aad9b273983598279dd/libcxx/include/bitset#L433-L436

https://github.com/llvm/llvm-project/blob/e3dafa88a8f651825ac65aad9b273983598279dd/libcxx/include/bitset#L550-L553

https://github.com/llvm/llvm-project/blob/e3dafa88a8f651825ac65aad9b273983598279dd/libcxx/include/bitset#L622

#### Proposed Solution:

In my opinion, if the standard does not specify a member typedef, the library should try to avoid or minimize the introduction of extra typedefs, especially public ones, to prevent potential clashes with user-defined classes, as demonstrated above. From the user's perspective, they have the freedom to utilize any member typedefs not specified by the C++ standards in their own code.

If extra typedefs are deemed necessary, I recommend using a naming convention like `__ugly_name` for those not specified in the standards, as we have previously implemented.

### PR DESCRIPTION
**Pull request by winner245**
This PR fixes the ambiguities in name lookup caused by non-standard member typedefs `size_type` and `difference_type` in `std::bitset`.  

Follows up #121620.
Closes #121618.

### CODE REVIEW

File: libcxx/include/__algorithm/count.h [hunk 1]
```diff
@@ -75,8 +75,10 @@ template <class, class _Cp, bool _IsConst, class _Tp, class _Proj, __enable_if_t
 _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 __iter_diff_t<__bit_iterator<_Cp, _IsConst> >
 __count(__bit_iterator<_Cp, _IsConst> __first, __bit_iterator<_Cp, _IsConst> __last, const _Tp& __value, _Proj&) {
   if (__value)
-    return std::__count_bool<true>(__first, static_cast<typename _Cp::size_type>(__last - __first));
-  return std::__count_bool<false>(__first, static_cast<typename _Cp::size_type>(__last - __first));
+    return std::__count_bool<true>(
+        __first, static_cast<typename __size_difference_type_traits<_Cp>::size_type>(__last - __first));
+  return std::__count_bool<false>(
```
Comment (ldionne) [inline libcxx/include/__algorithm/count.h:80]: What happens if you simply use `_Cp::__size_type` and `_Cp::__difference_type` everywhere, instead of introducing `__size_difference_type_traits`?

**Review by ldionne — CHANGES_REQUESTED** [review]

File: libcxx/include/__algorithm/count.h (hunk 1 above)
Comment (winner245) [reply libcxx/include/__algorithm/count.h:80]: Yeah, that would be the ideal approach if these algorithms are only for `bitset::iterator`. However, these algorithms are also used by `vector<bool>::iterator`, where `_Cp` in `__bit_iterator<_Cp, _IsConst>` becomes `vector<bool>`, for which the required member type name is `difference_type`. Only when `_Cp` is `bitset`, the member type becomes `__difference_type`. To address this name difference, I introduced `__size_difference_type_traits`.

Comment (frederick-vs-ja) [reply libcxx/include/__algorithm/count.h:80]: How about just making `__bit_iterator` have `__size_type` and using `__bit_iterator<_Cp, _IsConst>::__size_type`? (Perhaps even pretty name `size_type` is OK, but it seems conventional that iterator types have no `size_type`.)

File: libcxx/include/__bit_reference [hunk 2]
```diff
@@ -41,6 +42,12 @@ struct __has_storage_type {
   static const bool value = false;
 };
 
+template <typename _Cp>
+struct __size_difference_type_traits {
+  using difference_type = typename _Cp::difference_type;
+  using size_type       = typename _Cp::size_type;
+};
```
Comment (frederick-vs-ja) [inline libcxx/include/__bit_reference:49]: I guess we can use SFINAE tricks - if `_Cp` has both `difference_type` & `size_type` then use them, otherwise fall back to `ptrdiff_t` & `size_t`. Then `__size_difference_type_traits` can be only used within this header.

```suggestion
template <class, class = void>
struct __size_difference_type_traits {
  using difference_type = ptrdiff_t;
  using size_type       = size_t;
};

template <class _Cp>
struct __size_difference_type_traits<_Cp, __void_t<typename _Cp::difference_type, typename _Cp::size_type> > {
  using difference_type = typename _Cp::difference_type;
  using size_type       = typename _Cp::size_type;
};
```
 (`<__type_traits/void_t.h>` should be included if do so.)

File: libcxx/include/__algorithm/count.h (hunk 1 above)
Comment (winner245) [reply libcxx/include/__algorithm/count.h:80]: I think I need to meet two goals simultaneously here. Currently, `__bit_iterator<_Cp, _IsConst>` is used as the `iterator` type for both `vector<bool>` and `std::bitset`. 
- When used with `vector<bool>::iterator`, we have `_Cp = vector<bool>` and we can only access `_Cp::{size_type, difference_type}`; 
- When used with `bitset<N>::iterator`, we have `_Cp = vector<bool>` and we can only access `_Cp::{__size_type, __difference_type}`. 

This means that always using one deterministic way would fail, and that's why I need `__size_difference_type_traits` which tells me to access the right member types depending on what `_Cp` is.

Comment (frederick-vs-ja) [reply libcxx/include/__algorithm/count.h:80]: IIUC we don't need `_Cp::{__size_type, __difference_type}` when `_Cp` is `__bitset`  - as the types are always `{size_t, ptrdiff_t}` (and we can just remove these member typedefs instead of __uglifying them).

Comment (winner245) [reply libcxx/include/__algorithm/count.h:80]: Ah, I see what you meant. Yeah, I think your approach works. We can remove these member types instead of uglifying them for `bitset`, as long as `__size_difference_type_traits` directly extracts `{size_t, ptrdiff_t}` when `_Cp` is `__bitset`. This is indeed better than my original approach which keeps these types. Thank you!

File: libcxx/include/__bit_reference (hunk 2 above)
Comment (winner245) [reply libcxx/include/__bit_reference]: Done. Thanks.

**Review by ldionne — APPROVED** [review]
