### PR TITLE
[Mem2Reg] Don't use single store optimization for potentially poison value

### LINKED ISSUE #97702: [Mem2Reg] Incorrect poison propagation
```llvm
; RUN: opt -S -passes=sroa < %a

define i8 @test(i1 %cond) {
start:
  %a = alloca i8, align 1
  br i1 %cond, label %bb1, label %bb2

bb1:
  store i8 poison, ptr %a, align 1
  br label %exit

bb2:
  br label %exit

exit:
  %5 = load i8, ptr %a, align 1
  ret i8 %5
}
```
Results in:
```llvm
define i8 @test(i1 %cond) {
  br i1 %cond, label %bb1, label %bb2

bb1:                                              ; preds = %start
  br label %exit

bb2:                                              ; preds = %start
  br label %exit

exit:                                             ; preds = %bb2, %bb1
  ret i8 poison
}
```

This is incorrect. If `%cond` is false, then the result must be undef, not poison.

The original test case is more along these lines (not sure yet whether the root cause is always the same):
```llvm
define i24 @test(i1 %cond) {
start:
  %a = alloca [3 x i8], align 1
  %b = alloca [1 x i8], align 1
  %a.1 = getelementptr inbounds i8, ptr %a, i64 1
  store i8 1, ptr %a, align 1
  store i8 1, ptr %a.1, align 1
  br i1 %cond, label %bb1, label %bb2

bb1:
  %b.1 = getelementptr inbounds i8, ptr %b, i64 1
  %oob = load i8, ptr %b.1, align 1
  %a.2 = getelementptr inbounds i8, ptr %a, i64 2
  store i8 %oob, ptr %a.2, align 1
  br label %exit

bb2:
  br label %exit

exit:
  %5 = load i24, ptr %a, align 1
  ret i24 %5
}
```

### PR DESCRIPTION
**Pull request by nikic**
If there is a single store, then loads must either load the stored value or uninitialized memory (undef). If the stored value may be poison, then replacing an uninitialized memory load with it would be incorrect. Fall back to the generic code in that case.

This PR only fixes the case where there is a literal poison store -- the case where the value is non-trivially poison will still get miscompiled by phi simplification later, see #96631.

Fixes https://github.com/llvm/llvm-project/issues/97702.

### CODE REVIEW

File: llvm/lib/Transforms/Utils/PromoteMemoryToRegister.cpp [hunk 1]
```diff
@@ -525,7 +525,14 @@ rewriteSingleStoreAlloca(AllocaInst *AI, AllocaInfo &Info, LargeBlockInfo &LBI,
                          SmallSet<DbgAssignIntrinsic *, 8> *DbgAssignsToDelete,
                          SmallSet<DbgVariableRecord *, 8> *DVRAssignsToDelete) {
   StoreInst *OnlyStore = Info.OnlyStore;
-  bool StoringGlobalVal = !isa<Instruction>(OnlyStore->getOperand(0));
+  Value *ReplVal = OnlyStore->getOperand(0);
+  // Loads may either load the stored value or uninitialized memory (undef).
+  // If the stored value may be poison, then replacing an uninitialized memory
+  // load with it would be incorrect.
```
Comment (DianQK) [inline llvm/lib/Transforms/Utils/PromoteMemoryToRegister.cpp:531]: IIUC, a single store implies a similar meaning of dominating all loads (or we add store undef for all other paths). Should we add more clarification here as to why this is incorrect?

**Review by dianqk — APPROVED** [review]
LGTM.

File: llvm/lib/Transforms/Utils/PromoteMemoryToRegister.cpp (hunk 1 above)
Comment (DianQK) [reply llvm/lib/Transforms/Utils/PromoteMemoryToRegister.cpp:531]: Ahhhh, I reread this comment and it looks fine.
