### PR TITLE
Fix crash with modules and constexpr destructor

### LINKED ISSUE #68702: Crash with modules and `constexpr` destructor
The following is a heavily reduced test case of `<vector>` in libstdc++ 13.2.0:
```c++
// RUN: rm -rf %t
// RUN: mkdir %t
// RUN: split-file %s %t

// RUN: %clang_cc1 -std=c++20 -emit-obj -fmodules -fimplicit-module-maps -fmodules-cache-path=%t %t/main.cpp -o %t/main.o

//--- V.h
#ifndef V_H
#define V_H

class A {
public:
  constexpr A() { }
  constexpr ~A() { }
};

template <typename T>
class V {
public:
  V() = default;

  constexpr V(int n, const A& a = A()) {}
};

#endif

//--- inst1.h
#include "V.h"

static void inst1() {
  V<int> v;
}

//--- inst2.h
#include "V.h"

static void inst2() {
  V<int> v(100);
}

//--- module.modulemap
module "M" {
  export *
  module "V.h" {
    export *
    header "V.h"
  }
  module "inst1.h" {
    export *
    header "inst1.h"
  }
}

module "inst2.h" {
  export *
  header "inst2.h"
}

//--- main.cpp
#include "V.h"
#include "inst2.h"

static void m() {
  static V<int> v(100);
}
```

It crashes with
```
Unhandled cleanup; missing full expression marker?
UNREACHABLE executed at clang/lib/AST/ExprConstant.cpp:15617!
```

### PR DESCRIPTION
**Pull request by hahnjo**
With modules, serialization might omit the outer `ExprWithCleanups` as it calls `ParmVarDecl::getDefaultArg()`. Complementary to fixing this in a separate change, make the code more robust by adding a `FullExpressionRAII` and avoid the `llvm_unreachable` in the added test `clang/test/Modules/pr68702.cpp`.

Closes https://github.com/llvm/llvm-project/issues/68702

### CODE REVIEW

File: clang/test/Modules/pr68702.cpp [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+//--- inst2.h
+#include "V.h"
+
+static void inst2() {
+  V<int> v(100);
+}
+
+//--- module.modulemap
+module "M" {
```
Comment (vgvassilev) [inline clang/test/Modules/pr68702.cpp:42]: Is that the new standard nowadays? Can we use `#pragma clang module build` and alike to express the module setup?

File: clang/test/Modules/pr68702.cpp [hunk 2]
```diff
@@ -0,0 +1,65 @@
+// RUN: rm -rf %t
+// RUN: mkdir %t
+// RUN: split-file %s %t
+
+// RUN: %clang_cc1 -std=c++20 -emit-obj -fmodules -fimplicit-module-maps -fmodules-cache-path=%t %t/main.cpp -o %t/main.o
```
Comment (vgvassilev) [inline clang/test/Modules/pr68702.cpp:5]: I thought this is a frontend issue -- do we need `-emit-obj` here?

File: clang/test/Modules/pr68702.cpp (hunk 1 above)
Comment (hahnjo) [reply clang/test/Modules/pr68702.cpp:42]: `split-file` is how many of the modules tests are written, and I find it very handy to reproduce setups with a number of smaller files...

File: clang/test/Modules/pr68702.cpp (hunk 2 above)
Comment (hahnjo) [reply clang/test/Modules/pr68702.cpp]: No, we don't need it, you are right - the crash happens during parsing / sema

**Comment by hahnjo** [comment]
ping @cor3ntin @shafik, could you have a look here?

**Review by ChuanqiXu9 — COMMENTED** [review]
While the change itself looks neat, I am curious about the reason how this interact with modules.

File: clang/lib/AST/ExprConstant.cpp [hunk 3]
```diff
@@ -15604,10 +15604,13 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
     LValue LVal;
     LVal.set(VD);
 
-    if (!EvaluateInPlace(Value, Info, LVal, this,
-                         /*AllowNonLiteralTypes=*/true) ||
-        EStatus.HasSideEffects)
-      return false;
+    {
+      FullExpressionRAII Scope(Info);
```
Comment (shafik) [inline clang/lib/AST/ExprConstant.cpp:15608]: I think we need to add a comment here similar to the one in `EvaluateAsConstexpr(...)` in this case it would be `A full-expression is ... an init-declarator ([dcl.decl]) or a mem-initializer` see https://eel.is/c++draft/intro.execution#5.4

CC @cor3ntin for second look

**Comment by shafik** [comment]
Please make sure you write a more complete description of the problem and why this solves the problem. The description is usually what goes into the git log and that is very useful for quickly understanding commits and tracking down problems. 

I know some folks edit the description on commit but honestly it is very helpful for the reviewers of your PR to have a full description up front.

**Comment by shafik** [comment]
I think this change makes sense but I am not crazy about how we deal w/ full-expressions right now with these `FullExpressionRAII`, it feels very ad-hoc and it takes a bunch of time to understand why they are needed where they are.

**Comment by shafik** [comment]
> While the change itself looks neat, I am curious about the reason how this interact with modules.

IIUC modules is incidental to the problem, it is just a way we run into an underlying issue that we are not dealing with full-expressions properly in this case.

**Comment by hahnjo** [comment]
I can add the comment as requested, but for the other questions related to full expressions and modules I'd really need input from experts...

**Comment by hahnjo** [comment]
ping @shafik @cor3ntin @ChuanqiXu9, how can we make progress here?

File: clang/test/Modules/pr68702.cpp (hunk 1 above)
Comment (dwblaikie) [reply clang/test/Modules/pr68702.cpp:42]: (not expressing any strong opinion on this patch in particular, but it'd be great if the pragmas were more used (but also, they're currently not perfect - my understanding is that `-frewrite-imports` isn't totally robust yet/needs some more investment) so we had more test coverage for it because it'd be really great if it worked well/was considered when adding new features, etc - and I think it'd be a more direct way to write tests than needing to use the extra split-file invocation, etc (like you could copy a single file/command line to run a modules test, instead of splitting things, having a directory of files to deal with/copy/whatever, etc))

**Comment by ChuanqiXu9** [comment]
The key point now is the rationale why this change relates to modules. It looks not good to proceed without understanding this. Otherwise we're playing with a black box... And the concrete method, ..., well, I guess we had no choice but debugging it hardly. For example, comparing the behavior of clang with and without the change.

**Comment by hahnjo** [comment]
I finally had time to debug this: The reason for modules being involved here is because the serialization code calls `ParmVarDecl::getDefaultArg()` which strips the outermost `FullExpr`, such as `ExprWithCleanups`. A potential fix is in https://github.com/llvm/llvm-project/pull/76473 though I'm not really convinced by this asymmetry between `getInit()` but calling `setDefaultArg()`. However, removing the handling of `FullExpr` in `setDefaultArg()` causes a total 29 test failures, so that's not an (easy) option...

Personally, I would argue that adding `FullExpressionRAII` makes the code more robust against the absence of `ExprWithCleanups` so that's maybe a good thing to have regardless of fixing the serialization code.

**Comment by ChuanqiXu9** [comment]
> I finally had time to debug this: The reason for modules being involved here is because the serialization code calls `ParmVarDecl::getDefaultArg()` which strips the outermost `FullExpr`, such as `ExprWithCleanups`. A potential fix is in #76473 though I'm not really convinced by this asymmetry between `getInit()` but calling `setDefaultArg()`. However, removing the handling of `FullExpr` in `setDefaultArg()` causes a total 29 test failures, so that's not an (easy) option...
> 
> Personally, I would argue that adding `FullExpressionRAII` makes the code more robust against the absence of `ExprWithCleanups` so that's maybe a good thing to have regardless of fixing the serialization code.

Thanks for looking into this. Good enough for me. Yeah the asymmetry between `getInit()` but calling `setDefaultArg()` is a concerning. Also it may be not easy to understand and fix the underlying problem (why getDefaultArg() will strip the outmost `FullExpr`) **properly**.

So personally I am fine with the current workaround with a `FIXME`. Let's wait for the opinion from @cor3ntin and @shafik

**Comment by hahnjo** [comment]
Ping, is this ok to be accepted and landed?

> So personally I am fine with the current workaround with a `FIXME`.

You mean next to the comment I already added referring to the C++ standard? Can you formulate what I should put there?

File: clang/lib/AST/ExprConstant.cpp [hunk 4]
```diff
@@ -15754,10 +15754,18 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
...
-    if (!EvaluateInPlace(Value, Info, LVal, this,
-                         /*AllowNonLiteralTypes=*/true) ||
-        EStatus.HasSideEffects)
-      return false;
+    {
+      // C++23 [intro.execution]/p5
+      // A full-expression is ... an init-declarator ([dcl.decl]) or a
+      // mem-initializer.
+      // So we need to make sure temporary objects are destroyed after having
+      // evaluated the expression (per C++23 [class.temporary]/p4).
```
Comment (ChuanqiXu9) [inline clang/lib/AST/ExprConstant.cpp:15762]:
```suggestion
      // evaluated the expression (per C++23 [class.temporary]/p4).
      //
      // FIXME: Otherwise this may break test/Modules/pr68702.cpp. because the serialization code 
      // calls ParmVarDecl::getDefaultArg() which strips the outermost FullExpr, such as ExprWithCleanups. 
```

I mean the reason why this is related to modules. I feel the analysis is valuable.

**Comment by ChuanqiXu9** [comment]
> Ping, is this ok to be accepted and landed?

If it is not hurry, I prefer to wait @cor3ntin to have a look. But given the scale of the patch, it should be good too to land it in 2 weeks if there is no other comments.

**Comment by hahnjo** [comment]
Well, this patch is up since almost three months now (!). Sure, we can keep carrying a similar fix downstream, but ideally I would really like to get rid of as many local changes as possible. That's not possible without proper review, but the current situation is quite unsatisfactory...

**Comment by ChuanqiXu9** [comment]
> Well, this patch is up since almost three months now (!). Sure, we can keep carrying a similar fix downstream, but ideally I would really like to get rid of as many local changes as possible. That's not possible without proper review, but the current situation is quite unsatisfactory...

Yeah, fully understood. I have a lot of similar experiences... 1~2 weeks is not long in comparing with 3 months.

**Comment by shafik** [comment]
> ping @shafik @cor3ntin @ChuanqiXu9, how can we make progress here?

Please add a release note and address my previous comment: https://github.com/llvm/llvm-project/pull/69076#issuecomment-1780327252

CC @cor3ntin

**Comment by hahnjo** [comment]
> address my previous comment: [#69076 (comment)](https://github.com/llvm/llvm-project/pull/69076#issuecomment-1780327252)

I had already expanded the commit message with the full details, now also copied to the PR summary. Is that sufficient to address the comment?

**Comment by cor3ntin** [comment]
This change needs a release note.
Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

File: clang/lib/AST/ExprConstant.cpp (hunk 4 above)
Comment (hahnjo) [reply clang/lib/AST/ExprConstant.cpp:15762]: Done.

**Comment by hahnjo** [comment]
> Please add a release note

> This change needs a release note. Please add an entry to `clang/docs/ReleaseNotes.rst` in the section the most adapted to the change, and referencing any Github issue this change fixes. Thanks!

Done.

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. Thanks for your patience.
