### PR TITLE
[Offload] Revert part of #187138. Workaround #191910

### LINKED ISSUE #191910: [Offload] regression on sm_60 again
```
fatal error: error in backend: PTX does not support "atomic" for orderings different than"NotAtomic" or "Monotonic" for sm_60 or older, but order is: "acquire".
```
appear again triggered by https://github.com/llvm/llvm-project/pull/187138
See old issue with reproducer https://github.com/llvm/llvm-project/issues/138560

### PR DESCRIPTION
**Pull request by ye-luo**
Closes #191910

### CODE REVIEW

File: openmp/device/include/Synchronization.h [hunk 1]
```diff
@@ -62,7 +62,12 @@ V add(Ty *Address, V Val, atomic::OrderingTy Ordering,
 template <typename Ty, typename V = utils::remove_addrspace_t<Ty>>
 V load(Ty *Address, atomic::OrderingTy Ordering,
        MemScopeTy MemScope = MemScopeTy::device) {
+#ifdef __NVPTX__
+  // workaround for Issue #191910
```
Comment (jhuber6) [inline openmp/device/include/Synchronization.h]:
```suggestion
  // FIXME: Workaround for older NVIDIA GPUs (#191910).
```

**Review by jhuber6 — APPROVED** [review]
Thanks
