### PR TITLE
[mlir] Fix debug output for passes that modify top-level operation.

### LINKED ISSUE #80021: [MLIR] Debugging output for passes dereferences `nullptr` in some cases
In `mlir/lib/Rewrite/PatternApplicator.cpp` the `matchAndRewrite` method gets the `dumpRootOp` in a way that may cause it to be a `nullptr` in case the original `op` already has a trait `IsIsolatedFromAbove` (e.g. `bultin.module` op).
We have encountered this in [VAST](https://github.com/trailofbits/vast) when lowering types.
It can be reproduced like this (using debug build of mlir and vast): 
`vast-front -vast-emit-mlir=hl -o - test/vast/Transform/HL/LowerTypes/strlit-a.c | vast-opt --vast-hl-lower-types --debug`.

I already have a fix that I will submit soon.

### PR DESCRIPTION
**Pull request by Jezurko**
Make it so that when the top-level (root) operation itself is being modified, it is also used as the root for debug output in PatternApplicator.
Fix #80021

### CODE REVIEW

File: mlir/lib/Rewrite/PatternApplicator.cpp [hunk 1]
```diff
@@ -40,7 +40,9 @@ static void logImpossibleToMatch(const Pattern &pattern) {
 
 /// Log IR after pattern application.
 static Operation *getDumpRootOp(Operation *op) {
-  return op->getParentWithTrait<mlir::OpTrait::IsIsolatedFromAbove>();
+  return op->hasTrait<mlir::OpTrait::IsIsolatedFromAbove>()
+             ? op
+             : op->getParentWithTrait<mlir::OpTrait::IsIsolatedFromAbove>();
```
Comment (joker-eph) [inline mlir/lib/Rewrite/PatternApplicator.cpp:45]: If you wish to fix the nullptr, I would likely write it as:

```suggestion
  Operation *isolatedParent = op->getParentWithTrait<mlir::OpTrait::IsIsolatedFromAbove>();
  if (isolatedParent) return isolatedParent;
  return op;
```

Comment (matthias-springer) [reply mlir/lib/Rewrite/PatternApplicator.cpp:45]: This change makes sense to me. If there is no isolated-from-above parent, we are modifying the top-level module and we should dump it directly.

Comment (Jezurko) [reply mlir/lib/Rewrite/PatternApplicator.cpp]: You are right, this is better. I have pushed an update

**Review by joker-eph — APPROVED** [review]
