### PR TITLE
[MCA][ResourceManager] Fix a bug in the instruction issue logic.

### LINKED ISSUE #108157: [mca] crash when attempting to use avx512 on znver4
Given the following assembly (minimized code taken from Intel's histogram example):
```asm
histogram_loop:
vpconflictd zmm0, zmm3
kxnorw k1, k1, k1
vpxord zmm1, zmm1, zmm1
```
A crash occurs
```
$ llvm-mca-18 hist.s -mcpu=znver4 --x86-asm-syntax=intel
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-mca-18 hist.s -mcpu=znver4 --x86-asm-syntax=intel
 #0 0x00007adbd7194716 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd94716)
 #1 0x00007adbd71926d0 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd926d0)
 #2 0x00007adbd7194ddb (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd94ddb)
 #3 0x00007adbd5c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007adbd888aec4 llvm::mca::ResourceManager::issueInstruction(llvm::mca::InstrDesc const&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248aec4)
 #5 0x00007adbd888c0fb llvm::mca::Scheduler::issueInstructionImpl(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248c0fb)
 #6 0x00007adbd888c31a llvm::mca::Scheduler::issueInstruction(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248c31a)
 #7 0x00007adbd8895756 llvm::mca::ExecuteStage::issueInstruction(llvm::mca::InstRef&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x2495756)
 #8 0x00007adbd889615e llvm::mca::ExecuteStage::cycleStart() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x249615e)
 #9 0x00007adbd8893b1d llvm::mca::Pipeline::runCycle() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x2493b1d)
#10 0x00007adbd88939d5 llvm::mca::Pipeline::run() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x24939d5)
#11 0x000061300efec201 (/usr/lib/llvm-18/bin/llvm-mca+0x16201)
#12 0x000061300efeac8b (/usr/lib/llvm-18/bin/llvm-mca+0x14c8b)
#13 0x00007adbd5c29d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#14 0x00007adbd5c29e40 call_init ./csu/../csu/libc-start.c:128:20
#15 0x00007adbd5c29e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#16 0x000061300efe4675 (/usr/lib/llvm-18/bin/llvm-mca+0xe675)
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by adibiagio**
Before this patch, the pipeline selection logic in ResourceManager::issueInstruction() didn't know how to correctly handle instructions which consume multiple partially overlapping resource groups. In some cases (like the test case from #108157), the inability to correctly allocate resources on instruction issue was leading to crashes.

The presence of multiple partially overlapping groups complicates the selection process by introducing extra constraints. For those cases, the issue logic now prioritizes groups which are more constrained than others.

Fixes #108157

### CODE REVIEW

File: llvm/lib/MCA/HardwareUnits/ResourceManager.cpp [hunk 1]
```diff
@@ -344,9 +344,90 @@ uint64_t ResourceManager::checkAvailability(const InstrDesc &Desc) const {
...
+      uint64_t lhsReadyUnits = lhsRS.getNumReadyUnits();
+      uint64_t rhsReadyUnits = rhsRS.getNumReadyUnits();
+      if (lhsReadyUnits == rhsReadyUnits)
+        return lhs.first < rhs.first;
+      return lhsReadyUnits < rhsReadyUnits;
+    });
+
+    SmallVector<ResourceWithUsage, 4> NewWorklist;
+
+    for (unsigned I = 0; I < Worklist.size(); ++I) {
```
Comment (RKSimon) [inline llvm/lib/MCA/HardwareUnits/ResourceManager.cpp:409]: `for (unsigned I = 0, E = Worklist.size(); I < E; ++I) {`

Comment (adibiagio) [reply llvm/lib/MCA/HardwareUnits/ResourceManager.cpp]: Thanks. It should be fixed now.

**Review by boomanaiden154 — APPROVED** [review]
LGTM. Thanks for the fix!

Algorithm seems reasonable enough to me. It seems like it would handle all cases that would possibly scheduable, and the worst-case quadratic complexity shouldn't be too bad. I'd imagine even instructions with a quite a few resource groups wouldn't perform terribly, but should be exceptionally rare.

File: llvm/lib/MCA/HardwareUnits/ResourceManager.cpp [hunk 2]
```diff
@@ -344,9 +344,90 @@ uint64_t ResourceManager::checkAvailability(const InstrDesc &Desc) const {
...
+  while (!Worklist.empty()) {
+    sort(Worklist, [&](const ResourceWithUsage &lhs,
+                       const ResourceWithUsage &rhs) {
+      const ResourceState &lhsRS = *Resources[getResourceStateIndex(lhs.first)];
+      const ResourceState &rhsRS = *Resources[getResourceStateIndex(rhs.first)];
+      uint64_t lhsReadyUnits = lhsRS.getNumReadyUnits();
+      uint64_t rhsReadyUnits = rhsRS.getNumReadyUnits();
+      if (lhsReadyUnits == rhsReadyUnits)
+        return lhs.first < rhs.first;
+      return lhsReadyUnits < rhsReadyUnits;
```
Comment (mshockwave) [inline llvm/lib/MCA/HardwareUnits/ResourceManager.cpp:404]: nit: the local variables here should probably be capitalized

File: llvm/include/llvm/MCA/HardwareUnits/ResourceManager.h [hunk 3]
```diff
@@ -428,9 +430,21 @@ class ResourceManager {
...
+
+  void issueInstruction(const InstrDesc &Desc,
+                        SmallVectorImpl<ResourceWithCycles> &Pipes) {
+    if (Desc.HasPartiallyOverlappingGroups)
+      return issueInstructionImpl(Desc, Pipes);
+
+    return fastIssueInstruction(Desc, Pipes);
+  }
+
+  void fastIssueInstruction(const InstrDesc &Desc,
```
Comment (michaelmaitland) [inline llvm/include/llvm/MCA/HardwareUnits/ResourceManager.h:443]: It would be nice to document the difference between fastIssueInstruction and issueInstructionImpl

Comment (adibiagio) [reply llvm/include/llvm/MCA/HardwareUnits/ResourceManager.h:443]: Good idea. I'll add a code comment in issueInstruction.

**Comment by adibiagio** [comment]
Addressed review comments.

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Review by mshockwave — APPROVED** [review]
LGTM

**Review by michaelmaitland — APPROVED** [review]
