### PR TITLE
[lldb] Don't call AddRemoteRegisters if the target XML did not include any registers

### LINKED ISSUE #92541: [lldb] Connecting to GDB remote target crashes when XML data contains no registers
If the XML target from gdb-remote server contains no register then lldb will fallback by calling `DynamicRegisterInfo::SetRegisterInfo` on the on registers returned by `GetFallbackRegisters`. But `DynamicRegisterInfo:Finalize` will have been called and `m_finalized` set. This result in an assertion in `SetRegisterInfo` for debug builds or a crash for release builds.

Find that `GetGDBServerRegisterInfo(arch_to_use)`, that is called from `ProcessGDBRemote::BuildDynamicRegisterInfo`, will return false if there is an empty set of registers, which causes the fallback. But `SetRegisterInfo` (via `AddRemoteRregisters`) will have been called with that empty set of registers, which causes the initial `Finalize` call.

Backtrace of the crash:
[bt-crash.txt](https://github.com/llvm/llvm-project/files/15349590/bt-crash.txt)

Backtrace of the call up to Finalize:
[bt-finalize.txt](https://github.com/llvm/llvm-project/files/15349601/bt-finalize.txt)

The lldb version this bug was found for is:
`lldb version 19.0.0git (https://github.com/llvm/llvm-project.git revision 3f0e1d4cf09b0c90abfb1d06a26cc4c85c1f9568)`

The use case is connecting to a simulator and the simulator's gdb server only provides some data, such as architecture, in the XML. And then relies on the default register layout. This works fine with gdb as client.

When filing a bug I am asked to attach the content of the diagnostics directory, but diagnostics.log file is empty so not attaching that.

### PR DESCRIPTION
**Pull request by DavidSpickett**
Fixes #92541

When e69a3d18f48bc0d81b5dd12e735a2ec898ce64d added fallback register layouts, it assumed that the choices were target XML with registers, or no target XML at all.

In the linked issue, a user has a debug stub that does have target XML, but it's missing register information.

This caused us to finalize the register information using an empty set of registers got from target XML, then fail an assert when we attempted to add the fallback set. Since we think we've already completed the register information.

This change adds a check to prevent that first call and expands the existing tests to check each architecture without target XML and with target XML missing register information.

### CODE REVIEW

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp [hunk 1]
```diff
@@ -4879,7 +4879,9 @@ bool ProcessGDBRemote::GetGDBServerRegisterInfo(ArchSpec &arch_to_use) {
   m_registers_enum_types.clear();
   std::vector<DynamicRegisterInfo::Register> registers;
   if (GetGDBServerRegisterInfoXMLAndProcess(arch_to_use, "target.xml",
-                                            registers))
+                                            registers) &&
+      // Target XML is not required to include register information.
+      (!registers.empty()))
```
Comment (mgorny) [inline lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp:4884]: I'm a bit confused about the extra parentheses here.

**Review by mgorny — APPROVED** [review]
Good catch, thanks!

File: lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp (hunk 1 above)
Comment (DavidSpickett) [reply lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp]: Just paranoia :) I've removed them.
