### PR TITLE
[Clang] skip default argument instantiation for non-defining friend declarations without specialization info to meet [dcl.fct.default] p4

### LINKED ISSUE #113324: [clang] clang trunk crashes at clang::FunctionDecl::getNumParams()
**This testcase is generated by a fuzzer.**

Compiler explorer: [https://godbolt.org/z/aehhzKdd1](https://godbolt.org/z/aehhzKdd1)

This invalid code will crash on both Clang Trunk and Clang Assertion Trunk:
```cpp
template<typename = int>
struct ct {
  friend void f(ct, int = 0);
};
void test() {
  f(ct<>{});
}
```

It seems that this goes back to clang-11.

Stack dump:
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:6:11: current parser token ')'
2.	<source>:5:13: parsing function body 'test'
3.	<source>:5:13: in compound statement ('{}')
 #0 0x0000000003bc6148 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3bc6148)
 #1 0x0000000003bc3e0c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3bc3e0c)
 #2 0x0000000003b114b8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000786adf842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000007a69a14 clang::FunctionDecl::getNumParams() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7a69a14)
 #5 0x0000000007463bc7 clang::Sema::addInstantiatedParametersToScope(clang::FunctionDecl*, clang::FunctionDecl const*, clang::LocalInstantiationScope&, clang::MultiLevelTemplateArgumentList const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7463bc7)
 #6 0x00000000073bdeb5 clang::Sema::SubstDefaultArgument(clang::SourceLocation, clang::ParmVarDecl*, clang::MultiLevelTemplateArgumentList const&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x73bdeb5)
 #7 0x0000000007463fb4 clang::Sema::InstantiateDefaultArgument(clang::SourceLocation, clang::FunctionDecl*, clang::ParmVarDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7463fb4)
 #8 0x0000000006c71c8d clang::Sema::BuildCXXDefaultArgExpr(clang::SourceLocation, clang::FunctionDecl*, clang::ParmVarDecl*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c71c8d)
 #9 0x0000000006c9c7d6 clang::Sema::GatherArgumentsForCall(clang::SourceLocation, clang::FunctionDecl*, clang::FunctionProtoType const*, unsigned int, llvm::ArrayRef<clang::Expr*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::Sema::VariadicCallType, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c9c7d6)
#10 0x0000000006c9dba7 clang::Sema::ConvertArgumentsForCall(clang::CallExpr*, clang::Expr*, clang::FunctionDecl*, clang::FunctionProtoType const*, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c9dba7)
#11 0x0000000006c9f791 clang::Sema::BuildResolvedCallExpr(clang::Expr*, clang::NamedDecl*, clang::SourceLocation, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, clang::CallExpr::ADLCallKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c9f791)
#12 0x000000000712ee9a FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) SemaOverload.cpp:0:0
#13 0x000000000712fda4 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x712fda4)
#14 0x0000000006ca13b8 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ca13b8)
#15 0x0000000006ca391c clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ca391c)
#16 0x0000000006709a0d clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6709a0d)
#17 0x00000000067023d1 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67023d1)
#18 0x0000000006704527 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6704527)
#19 0x00000000067045b9 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67045b9)
#20 0x0000000006708fd9 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6708fd9)
#21 0x000000000678bde9 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x678bde9)
#22 0x000000000678215c clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x678215c)
#23 0x0000000006783070 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6783070)
#24 0x0000000006783f45 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6783f45)
#25 0x000000000678569a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x678569a)
#26 0x0000000006699223 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6699223)
#27 0x00000000066cd8dd clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66cd8dd)
#28 0x000000000668cf6e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x668cf6e)
#29 0x000000000668d72e clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x668d72e)
#30 0x0000000006694ec3 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6694ec3)
#31 0x0000000006695dad clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6695dad)
#32 0x00000000066882ca clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66882ca)
#33 0x000000000453b728 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x453b728)
#34 0x00000000047f6bf9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47f6bf9)
#35 0x00000000047756be clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47756be)
#36 0x00000000048dc3de clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48dc3de)
#37 0x0000000000cdee3f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcdee3f)
#38 0x0000000000cd6b3a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#39 0x000000000457f449 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#40 0x0000000003b11964 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b11964)
#41 0x000000000457fa3f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#42 0x000000000454533d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x454533d)
#43 0x000000000454642d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x454642d)
#44 0x000000000454dd55 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x454dd55)
#45 0x0000000000cdbcff clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcdbcff)
#46 0x0000000000baadf4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbaadf4)
#47 0x0000786adf829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#48 0x0000786adf829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#49 0x0000000000cd65ee _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xcd65ee)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
This fixes a crash when instantiating default arguments for templated friend function declarations which lack a definition.
There are implementation limits which prevents us from finding the pattern for such functions, and this causes difficulties
setting up the instantiation scope for the function parameters.

This patch skips instantiating the default argument in these cases, which causes a minor regression in error recovery, but otherwise avoids the crash.

Fixes #113324

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 1]
```diff
@@ -3437,10 +3437,10 @@ bool Sema::SubstDefaultArgument(
...
       //   void g() { f(0); }
       LIS = std::make_unique<LocalInstantiationScope>(*this);
-      FunctionDecl *PatternFD = FD->getTemplateInstantiationPattern(
-          /*ForDefinition*/ false);
-      if (addInstantiatedParametersToScope(FD, PatternFD, *LIS, TemplateArgs))
-        return true;
+      if (FunctionDecl *PatternFD =
+              FD->getTemplateInstantiationPattern(/*ForDefinition*/ false))
+        if (addInstantiatedParametersToScope(FD, PatternFD, *LIS, TemplateArgs))
+          return true;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:3443]: How about lifting the check for PatternFD to ForCallExpr?

```cpp
if (FunctionDecl *PatternFD = FD->getTemplateInstantiationPattern(); ForCallExpr && ForCallExpr)
  ...
```

So we don't need to construct an extra LocalInstantiationScope if the pattern isn't present.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3443]: OTOH I'm wondering if we could avoid substituting into default arguments if we already know the friend declaration is not a definition. The function declaration instantiation seems to intentionally avoid adding connections to the primary template if the friend declaration is not a definition, which is why `getTemplateInstantiationPattern()` returns nullptr here.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3443]: @zyn0217 thanks for the feedback. 

> How about lifting the check for PatternFD to ForCallExpr?

A check for `ForCallExpr` is already present above
https://github.com/llvm/llvm-project/blob/1e19f0f9d92b5e9c43d53893e387341835d3d96b/clang/lib/Sema/SemaTemplateInstantiate.cpp#L3433

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3443]: I mean, if we could move the pointer check to the same line as ForCallExpr, we could save an LIS then.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp]: @zyn0217 whenever you get a chance, could you take a look at the latest changes? thanks

File: clang/lib/Sema/SemaTemplateInstantiate.cpp [hunk 2]
```diff
@@ -3430,15 +3430,17 @@ bool Sema::SubstDefaultArgument(
...
+            : nullptr;
+    if (PatternFD) {
       // When instantiating a default argument due to use in a call expression,
       // an instantiation scope that includes the parameters of the callee is
       // required to satisfy references from the default argument. For example:
       //   template<typename T> void f(T a, int = decltype(a)());
       //   void g() { f(0); }
       LIS = std::make_unique<LocalInstantiationScope>(*this);
-      FunctionDecl *PatternFD = FD->getTemplateInstantiationPattern(
-          /*ForDefinition*/ false);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateInstantiate.cpp:3441]: I think the actual problem here is that `getTemplateInstantiationPattern` doesn't work for finding the non-defining friend declaration in the class template.

This approach of skipping adding the parameters to the instantiation scope would only work in the simple case where the default argument definition doesn't refer to any of the parameters. The tests added in this PR doesn't cover the non-trivial case where it does refer to them.

Moreover, the whole previous approach seems fraught, as each default argument definition could appear in a different templated context, so there is not one single function template declaration which would serve as a pattern for all default arguments.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3441]: @mizvekov thanks for the detailed feedback.

> The tests added in this PR doesn't cover the non-trivial case where it does refer to them.

I’d appreciate it if you could share an example of the non-trivial cases. This would help move forward with a new approach to resolve the issue and ensure that as many scenarios as possible are covered to prevent future crashes.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp:3441]: Sure.

The first problem I mean something like:
```C++
template <typename = int> struct ct {
  friend void f(ct a, ct = decltype(a){});
};
void test() { f(ct<>{}); }
```

Regarding the second issue, I see now that we enforce that a friend declaration specifying a default argument must be the only declaration. So this would only be a problem in practice if we decided to support that anyway for error recovery purposes.

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplateInstantiate.cpp]: @zyn0217 @mizvekov I've moved the condition to `InstantiateDefaultArgument` and added an additional test. Do the recent updates look acceptable?

File: clang/test/CXX/temp/temp.res/p4.cpp [hunk 3]
```diff
@@ -185,3 +185,27 @@ template<typename T> struct S {
...
+
+template<typename T>
+void foo(T a) { } // expected-note {{candidate function template not viable: requires single argument 'a', but no arguments were provided}}
+
+void test() {
+  f1(ct<>{});
+  f2(ct<>{});
+
+  C<int> c;
+  foo(); // expected-error {{no matching function for call to 'foo'}}
```
Comment (mizvekov) [inline clang/test/CXX/temp/temp.res/p4.cpp:209]: The test I had in mind was something like:
```C++
template<class T> using alias = int;

template<typename T> struct C {
  friend void foo(C, int a = alias<T&>(1));
};

void test() {
  foo(C<void>());
}
```

With your previous patch, we would be able to diagnose the instantiation failure here (forming reference to void), while the current version of the patch doesn't, since it skips instantiation of the default argument.

Comment (a-tarasyuk) [reply clang/test/CXX/temp/temp.res/p4.cpp:209]: Should the previous changes be reverted?

Comment (mizvekov) [reply clang/test/CXX/temp/temp.res/p4.cpp:209]: No, I mean not crashing is definitely better. But the error recovery is worse in some situations.

The right fix would be to somehow find the correct function decl pattern for instantiating the default argument.
This would be the function template declaration where that particular default argument was written.

This might not necessarily need to use `getTemplateInstantiationPattern` for that; you could try some other way of finding it. But that ideal fix might be more involved, and I think the current approach is fine as a quick fix, so feel free to continue with this current patch, or otherwise try the better fix, as you wish.

Comment (mizvekov) [reply clang/test/CXX/temp/temp.res/p4.cpp:209]: I also meant that, whichever way you choose, please add the above test case. In case of keeping the current approach, add a FIXME noting that we miss diagnosing the instantiation failure.

**Review by mizvekov — APPROVED** [review]
LGTM except for a couple of nits.

Thanks!

File: clang/test/CXX/temp/temp.res/p4.cpp [hunk 4]
```diff
@@ -185,3 +185,21 @@ template<typename T> struct S {
...
+
+namespace GH113324 {
+template <typename = int> struct ct {
+  friend void f1(ct, int = 0);               // expected-error {{friend declaration specifying a default argument must be a definition}}
+  friend void f2(ct a, ct = decltype(a){ }); // expected-error {{friend declaration specifying a default argument must be a definition}}
+};
+
+template<class T> using alias = int;
+template<typename T> struct C {
+  friend void f3(C, int a = alias<T&>(1)); // expected-error {{friend declaration specifying a default argument must be a definition}}
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/test/CXX/temp/temp.res/p4.cpp:198]: (It's missing this change by the way)

[the remark this answers is not in the document]
Comment (a-tarasyuk) [reply clang/test/CXX/temp/temp.res/p4.cpp:198]: @mizvekov Could you let me know if you meant these [changes](https://github.com/llvm/llvm-project/pull/113777/files#diff-b0cb098ce09d66d899c8c9743edb974ce84976dfda43dbe21ee1e1a2d4b2855cR197-R198?)?

@zyn0217 could you please review this PR when you have a moment?

**Review by zyn0217 — APPROVED** [review]
LGTM as well, thanks for working on it!

**Comment by a-tarasyuk** [comment]
@mizvekov @zyn0217 if no additional reviews are needed, could someone please merge it? thanks

**Comment by zyn0217** [comment]
BTW, can you flesh out the commit message so we don't just have a single issue link there? Thanks

**Comment by a-tarasyuk** [comment]
@zyn0217 done

**Comment by mizvekov** [comment]
@zyn0217 meant the PR description, which is the body of the commit, not the title.
I already fixed it for you.

**Comment by a-tarasyuk** [comment]
@mizvekov thanks

**Comment by alanzhao1** [comment]
FYI this is causing Clang to crash with Chrome: https://crbug.com/377956048

I'm currently working on getting a reduced repro with CReduce.

**Comment by a-tarasyuk** [comment]
@alanzhao1 thanks for catching that. should I revert it?

**Comment by alanzhao1** [comment]
Based on the [patch reversion policy](https://llvm.org/docs/DeveloperPolicy.html#patch-reversion-policy), I think reverting is the right thing to do.

(I'm working on the reduced repro, but creduce is _really_ slow. In the meantime, I attached the unreduced files). 

[unreduced.tar.gz](https://github.com/user-attachments/files/17671006/unreduced.tar.gz)

**Comment by alanzhao1** [comment]
For posterity, here's the entire stacktrace I got:

```
/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang++ -MMD -MF obj/third_party/dawn/src/dawn/tests/dawn_unittests/CacheRequestTests.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8e31ad42561900383e10dbefc1d3e8f38cedfbe9 -DTMP_REBUILD_HACK -DCR_SYSROOT_KEY=20230611T210420Z-2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DDAWN_ABORT_ON_ASSERT -DDAWN_ENABLE_BACKEND_NULL -DDAWN_ENABLE_BACKEND_OPENGL -DDAWN_ENABLE_BACKEND_DESKTOP_GL -DDAWN_ENABLE_BACKEND_OPENGLES -DDAWN_ENABLE_BACKEND_VULKAN -DDAWN_USE_X11 -DTINT_BUILD_SPV_READER=0 -DTINT_BUILD_SPV_WRITER=1 -DTINT_BUILD_WGSL_READER=1 -DTINT_BUILD_WGSL_WRITER=1 -DTINT_BUILD_MSL_WRITER=1 -DTINT_BUILD_HLSL_WRITER=1 -DTINT_BUILD_GLSL_WRITER=1 -DTINT_BUILD_GLSL_VALIDATOR=1 -DTINT_BUILD_SYNTAX_TREE_WRITER=0 -DTINT_BUILD_IR_BINARY=1 -DTINT_BUILD_IR_FUZZER=0 -DTINT_BUILD_IS_WIN=0 -DTINT_BUILD_IS_MAC=0 -DTINT_BUILD_IS_LINUX=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBENCHMARK_STATIC_DEFINE -DCR_CXX_INCLUDE=\"third_party/rust/chromium_crates_io/vendor/cxx-1.0.129/include/cxx.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=0 -DGTEST_HAS_ABSL -DGTEST_NO_ABSL_FLAGS -DUNIT_TEST -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -I../.. -Igen -I../../buildtools/third_party/libc++ -Igen/third_party/dawn/src -I../../third_party/dawn/src -I../../third_party/dawn -I../../third_party/dawn/include -Igen/third_party/dawn -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/google_benchmark/src/include -Igen/third_party/dawn/include -I../../base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/googletest/custom -I../../third_party/googletest/src/googlemock/include -I../../third_party/googletest/src/googletest/include -I../../third_party/re2/src -I../../third_party/vulkan-headers/src/include -I../../third_party/wayland/src/src -I../../third_party/wayland/include/src -I../../third_party/dawn/third_party/khronos/EGL-Registry/api -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wgnu -Wno-gnu-anonymous-struct -Wno-gnu-conditional-omitted-operand -Wno-gnu-include-next -Wno-gnu-label-as-value -Wno-gnu-redeclared-enum -Wno-gnu-statement-expression -Wno-gnu-zero-variadic-macro-arguments -Wno-zero-length-array -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-thread-safety-reference-return -Wshadow -Werror -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 -ffp-contract=off -Wa,--crel,--allow-experimental-crel -fcomplete-member-pointers -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-math-errno -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../build/linux/debian_bullseye_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_bullseye_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-inconsistent-missing-override -Wno-redundant-parens -Wno-invalid-offsetof -Wenum-compare-conditional -Wno-c++11-narrowing-const-reference -Wno-missing-template-arg-list-after-template-kw -Wno-dangling-assignment-gsl -Wno-nontrivial-memaccess -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include --sysroot=../../build/linux/debian_bullseye_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/dawn/src/dawn/tests/unittests/native/CacheRequestTests.cpp -o obj/third_party/dawn/src/dawn/tests/dawn_unittests/CacheRequestTests.o
clang++: /usr/local/google/home/ayzhao/src/llvm-project/clang/lib/AST/ASTContext.cpp:2398: TypeInfo clang::ASTContext::getTypeInfoImpl(const Type *) const: Assertion `!A->getDeducedType().isNull() && "cannot request the size of an undeduced or dependent auto type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang++ -MMD -MF obj/third_party/dawn/src/dawn/tests/dawn_unittests/CacheRequestTests.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8e31ad42561900383e10dbefc1d3e8f38cedfbe9 -DTMP_REBUILD_HACK -DCR_SYSROOT_KEY=20230611T210420Z-2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DDAWN_ABORT_ON_ASSERT -DDAWN_ENABLE_BACKEND_NULL -DDAWN_ENABLE_BACKEND_OPENGL -DDAWN_ENABLE_BACKEND_DESKTOP_GL -DDAWN_ENABLE_BACKEND_OPENGLES -DDAWN_ENABLE_BACKEND_VULKAN -DDAWN_USE_X11 -DTINT_BUILD_SPV_READER=0 -DTINT_BUILD_SPV_WRITER=1 -DTINT_BUILD_WGSL_READER=1 -DTINT_BUILD_WGSL_WRITER=1 -DTINT_BUILD_MSL_WRITER=1 -DTINT_BUILD_HLSL_WRITER=1 -DTINT_BUILD_GLSL_WRITER=1 -DTINT_BUILD_GLSL_VALIDATOR=1 -DTINT_BUILD_SYNTAX_TREE_WRITER=0 -DTINT_BUILD_IR_BINARY=1 -DTINT_BUILD_IR_FUZZER=0 -DTINT_BUILD_IS_WIN=0 -DTINT_BUILD_IS_MAC=0 -DTINT_BUILD_IS_LINUX=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DBENCHMARK_STATIC_DEFINE -DCR_CXX_INCLUDE=\"third_party/rust/chromium_crates_io/vendor/cxx-1.0.129/include/cxx.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=0 -DGTEST_HAS_ABSL -DGTEST_NO_ABSL_FLAGS -DUNIT_TEST -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -I../.. -Igen -I../../buildtools/third_party/libc++ -Igen/third_party/dawn/src -I../../third_party/dawn/src -I../../third_party/dawn -I../../third_party/dawn/include -Igen/third_party/dawn -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/google_benchmark/src/include -Igen/third_party/dawn/include -I../../base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/googletest/custom -I../../third_party/googletest/src/googlemock/include -I../../third_party/googletest/src/googletest/include -I../../third_party/re2/src -I../../third_party/vulkan-headers/src/include -I../../third_party/wayland/src/src -I../../third_party/wayland/include/src -I../../third_party/dawn/third_party/khronos/EGL-Registry/api -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wgnu -Wno-gnu-anonymous-struct -Wno-gnu-conditional-omitted-operand -Wno-gnu-include-next -Wno-gnu-label-as-value -Wno-gnu-redeclared-enum -Wno-gnu-statement-expression -Wno-gnu-zero-variadic-macro-arguments -Wno-zero-length-array -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-thread-safety-reference-return -Wshadow -Werror -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 -ffp-contract=off -Wa,--crel,--allow-experimental-crel -fcomplete-member-pointers -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-math-errno -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../build/linux/debian_bullseye_amd64-sysroot/usr/include/glib-2.0 -isystem../../build/linux/debian_bullseye_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-inconsistent-missing-override -Wno-redundant-parens -Wno-invalid-offsetof -Wenum-compare-conditional -Wno-c++11-narrowing-const-reference -Wno-missing-template-arg-list-after-template-kw -Wno-dangling-assignment-gsl -Wno-nontrivial-memaccess -std=c++20 -Wno-trigraphs -gsimple-template-names -fno-exceptions -fno-rtti -nostdinc++ -isystem../../third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include --sysroot=../../build/linux/debian_bullseye_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/dawn/src/dawn/tests/unittests/native/CacheRequestTests.cpp -o obj/third_party/dawn/src/dawn/tests/dawn_unittests/CacheRequestTests.o
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      ../../third_party/dawn/src/dawn/tests/unittests/native/CacheRequestTests.cpp:76:1 <Spelling=../../third_party/googletest/src/googletest/include/gtest/internal/gtest-internal.h:1519:60>: Generating code for declaration 'dawn::native::(anonymous namespace)::CacheRequestTests_CacheResultTypes_Test::TestBody'
 #0 0x0000565135d3a488 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x503c488)
 #1 0x0000565135d3803e llvm::sys::RunSignalHandlers() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x503a03e)
 #2 0x0000565135ca8ab6 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fb049e591a0 (/lib/x86_64-linux-gnu/libc.so.6+0x3d1a0)
 #4 0x00007fb049ea70ec __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007fb049e59102 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #6 0x00007fb049e424f2 abort ./stdlib/abort.c:81:7
 #7 0x00007fb049e42415 _nl_load_domain ./intl/loadmsgcat.c:1177:9
 #8 0x00007fb049e51d32 (/lib/x86_64-linux-gnu/libc.so.6+0x35d32)
 #9 0x00005651395a6220 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x88a8220)
#10 0x00005651395a8150 clang::ASTContext::getTypeInfo(clang::Type const*) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x88aa150)
#11 0x00005651395a76db clang::ASTContext::getPreferredTypeAlign(clang::Type const*) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x88a96db)
#12 0x00005651395a57f7 clang::ASTContext::getDeclAlign(clang::Decl const*, bool) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x88a77f7)
#13 0x000056513614f754 clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5451754)
#14 0x000056513614ba2e clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x544da2e)
#15 0x000056513614b4b7 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x544d4b7)
#16 0x00005651360d578b clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x53d778b)
#17 0x00005651360c8aed clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x53caaed)
#18 0x00005651360c7dee clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x53c9dee)
#19 0x00005651360d6b70 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x53d8b70)
#20 0x00005651360b1e72 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x53b3e72)
#21 0x0000565135f6e870 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5270870)
#22 0x0000565135f66332 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5268332)
#23 0x0000565135f5759f clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x525959f)
#24 0x0000565135f575cb clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52595cb)
#25 0x0000565135f575cb clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52595cb)
#26 0x0000565135f575cb clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52595cb)
#27 0x0000565135f575cb clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52595cb)
#28 0x0000565135f575cb clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52595cb)
#29 0x0000565135f543fa clang::CodeGen::CodeGenModule::Release() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x52563fa)
#30 0x00005651365b3928 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#31 0x00005651365abb3e clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x58adb3e)
#32 0x000056513859d599 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x789f599)
#33 0x0000565136a3c64f clang::FrontendAction::Execute() (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5d3e64f)
#34 0x00005651369ae10d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5cb010d)
#35 0x0000565136b25c37 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5e27c37)
#36 0x00005651344b5a5e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x37b7a5e)
#37 0x00005651344b1ffe ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#38 0x0000565136800249 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#39 0x0000565135ca87f6 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x4faa7f6)
#40 0x00005651367ff922 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5b01922)
#41 0x00005651367bee1c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5ac0e1c)
#42 0x00005651367bf127 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5ac1127)
#43 0x00005651367dc818 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x5ade818)
#44 0x00005651344b1641 clang_main(int, char**, llvm::ToolContext const&) (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x37b3641)
#45 0x00005651344c1927 main (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x37c3927)
#46 0x00007fb049e43b8a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#47 0x00007fb049e43c45 call_init ./csu/../csu/libc-start.c:128:20
#48 0x00007fb049e43c45 __libc_start_main ./csu/../csu/libc-start.c:347:5
#49 0x00005651344afbe1 _start (/usr/local/google/home/ayzhao/src/llvm-project/build/bin/clang+++0x37b1be1)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 20.0.0git (git@github.com:llvm/llvm-project.git e8b70e97447dc0d93a277b0373345d3a1bae1aa9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/ayzhao/src/llvm-project/build/bin
Build config: +assertions
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: ../../tools/clang/crashreports/CacheRequestTests-732518.cpp
clang++: note: diagnostic msg: ../../tools/clang/crashreports/CacheRequestTests-732518.sh
clang++: note: diagnostic msg:

********************
ninja: build stopped: subcommand failed.
```

**Comment by mizvekov** [comment]
Reverted. The issue looks like the instantiation of the default argument was skipped, but without any previous error actually being produced, so it proceeded to CodeGen with invalid AST.

**Comment by alanzhao1** [comment]
> Reverted. The issue looks like the instantiation of the default argument was skipped, but without any previous error actually being produced, so it proceeded to CodeGen with invalid AST.

Thanks! Still waiting on CReduce for that repro.

**Comment by aeubanks** [comment]
I was also reducing this, got
```
template <bool, class> using __enable_if_t = int;
template <int __v> struct integral_constant {
  static const int value = __v;
};
struct basic_string {
  template <__enable_if_t<integral_constant<true>::value, int> = 0>
  basic_string(char *);
};
struct CacheRequestImpl {
  template <typename CacheHitFn, typename CacheMissFn>
  friend void LoadOrRun(int, CacheRequestImpl, CacheHitFn, CacheMissFn,
                        basic_string = "") {}
};
void CacheRequestTests_MakesCacheKey_TestTestBody() {
  CacheRequestImpl req;
  auto result = LoadOrRun(
      0, req, [] {}, [] {});
}
```

**Comment by zyn0217** [comment]
Further reduced to:

```cpp
struct CacheRequestImpl {
  friend void LoadOrRun(CacheRequestImpl, int = 42) {}
};
void CacheRequestTests_MakesCacheKey_TestTestBody() {
  CacheRequestImpl req;
  LoadOrRun(req);
}
```

There is no template in this case, so obviously, `FDecl->getMemberSpecializationInfo()` would be null, hence the absence of the default arguments with this patch.

As I have [suggested](https://github.com/llvm/llvm-project/pull/113777#discussion_r1830858725) initially, we should probably put the checking in `Sema::InstantiateDefaultArgument()` because that is where the instantiation of default arguments in templates starts.

**Comment by mstorsjo** [comment]
Thanks for the revert - FWIW, I also ran into issues with this change when building Qt.

Building the https://github.com/qt/qtbase repo fails with an error like this:
```
[790/790] Linking CXX shared library lib/libQt6Gui.so.6.8.0
FAILED: lib/libQt6Gui.so.6.8.0 
/usr/bin/ld: src/gui/CMakeFiles/Gui.dir/painting/qpdf.cpp.o: in function `decltype (((std::declval<std::enable_if<((7)>(0)), void>::type>()),(((qHash(std::declval<QByteArray, QByteArray, int, int, int, QList<QFont::Tag>, QList<float> const&>())),...))),unsigned long{}) qHashMulti<QByteArray, QByteArray, int, int, int, QList<QFont::Tag>, QList<float> >(unsigned long, QByteArray const&, QByteArray const&, int const&, int const&, int const&, QList<QFont::Tag> const&, QList<float> const&)':
qpdf.cpp:(.text._Z10qHashMultiIJ10QByteArrayS0_iii5QListIN5QFont3TagEES1_IfEEEDTcmcmclsr3stdE7declvalINSt9enable_ifIXgtsPDpT_ELi0EEvE4typeEEEfrcmcl5qHashclsr3stdE7declvalIRKS7_EEEtlmEEmDpSC_[_Z10qHashMultiIJ10QByteArrayS0_iii5QListIN5QFont3TagEES1_IfEEEDTcmcmclsr3stdE7declvalINSt9enable_ifIXgtsPDpT_ELi0EEvE4typeEEEfrcmcl5qHashclsr3stdE7declvalIRKS7_EEEtlmEEmDpSC_]+0x9a): undefined reference to `unsigned long QtPrivate::QHashCombine::operator()<QFont::Tag>(unsigned long, QFont::Tag const&) const'
/usr/bin/ld: src/gui/CMakeFiles/Gui.dir/text/qfont.cpp.o: in function `decltype (((std::declval<std::enable_if<((13)>(0)), void>::type>()),(((qHash(std::declval<long long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, QList<QString>, QString, unsigned int, QList<QFont::Tag>, QList<float> const&>())),...))),unsigned long{}) qHashMulti<long long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, QList<QString>, QString, unsigned int, QList<QFont::Tag>, QList<float> >(unsigned long, long long const&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int const&, QList<QString> const&, QString const&, unsigned int const&, QList<QFont::Tag> const&, QList<float> const&)':
qfont.cpp:(.text._Z10qHashMultiIJxjjjjjjj5QListI7QStringES1_jS0_IN5QFont3TagEES0_IfEEEDTcmcmclsr3stdE7declvalINSt9enable_ifIXgtsPDpT_ELi0EEvE4typeEEEfrcmcl5qHashclsr3stdE7declvalIRKS8_EEEtlmEEmDpSD_[_Z10qHashMultiIJxjjjjjjj5QListI7QStringES1_jS0_IN5QFont3TagEES0_IfEEEDTcmcmclsr3stdE7declvalINSt9enable_ifIXgtsPDpT_ELi0EEvE4typeEEEfrcmcl5qHashclsr3stdE7declvalIRKS8_EEEtlmEEmDpSD_]+0x13a): undefined reference to `unsigned long QtPrivate::QHashCombine::operator()<QFont::Tag>(unsigned long, QFont::Tag const&) const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

In a build with static libraries, where this didn't cause immediate errors, I also ran into build errors while building qtdeclarative. I didn't bisect that failure, but it seems closely related:
```
qtdeclarative/src/qmlcompiler/qqmljsregistercontent_p.h:250:20: error: no matching function for call to 'qHashMulti'
  250 |             return qHashMulti(
      |                    ^~~~~~~~~~
aarch64-w64-mingw32/include/QtCore/qhashfunctions.h:344:1: note: candidate template ignored: substitution failure [with T = <QQmlJSMetaProperty, int, int>]
  344 | qHashMulti(size_t seed, const T &... args)
      | ^
aarch64-w64-mingw32/include/QtCore/qhashfunctions.h:390:12: error: no matching function for call to 'qHashMulti'
  390 |     return qHashMulti(seed, key.first, key.second);
      |            ^~~~~~~~~~
qtdeclarative/src/qmlcompiler/qqmljsregistercontent_p.h:157:20: note: in instantiation of function template specialization 'qHash<QQmlJSMetaEnum, QString>' requested here
  157 |             return qHash(std::get<std::pair<QQmlJSMetaEnum, QString>>(registerContent.m_content),
      |                    ^
aarch64-w64-mingw32/include/QtCore/qhashfunctions.h:344:1: note: candidate template ignored: substitution failure [with T = <QQmlJSMetaEnum, QString>]
  344 | qHashMulti(size_t seed, const T &... args)
      | ^
4 errors generated.
```

Before relanding, I would appreciate if you could try building qtbase with the new version of the suggested change!
