### PR TITLE
x86: fix musttail sibcall miscompilation

### LINKED ISSUE #56891: [Backend][X86] Incorrect output + missed optimization for function marked as clang::musttail
As of commit 4bd9d98bc2be3548418dc67accc662cbeb10a2e1

When compiling this source code 

```c
struct A {
    int a[5];
};

extern int G(A a);

int F(A a) {
    [[clang::musttail]] return G(a);
}
```

with `-O3 -target x86_64-linux`, clang generates the following assembly (only showing relevant part)
```asm
_Z1F1A:                                 # @_Z1F1A
	.cfi_startproc
# %bb.0:                                # %entry
	movl	24(%rsp), %eax
	movl	%eax, 16(%rsp)
	movaps	8(%rsp), %xmm0
	movups	%xmm0, (%rsp)
	movaps	%xmm0, 8(%rsp)
	movl	%eax, 24(%rsp)
	jmp	_Z1G1A@PLT                      # TAILCALL
.Lfunc_end0:
```

`movups	%xmm0, (%rsp)` overwrites the return address of caller `F`, which will result in a crash.

### LINKED ISSUE #72390: Miscompile with [[clang::musttail]]
When adding [[clang::musttail]] to a tail function call the program crashes. Inspection of the output asm clearly shows the stack return address is written over by a skewed memcpy, it copies the struct that is passed on the stack over itself but with a shift of 16 globbering the return address. Without [[clang::musttail] the function runs correctly and -fsanitize=undefined,asan does not indicate any problems

https://godbolt.org/z/Y7fq1xK54

### LINKED ISSUE #147813: `musttail` doesn't optimize sibling calls
For example, this code:

```cpp
int bar(int);

int
foo_tail(int x)
{
    // Correct, compiles to a single jmp:
    return bar(x);
}

int
foo_musttail(int x)
{
    // Buggy, loads and re-spills all parameters:
    __attribute__((musttail)) return bar(x);
}
```

Compiles to:

```s
_foo_tail:
  jmp _bar

_foo_musttail:
  movl 4(%esp), %eax
  movl %eax, 4(%esp)
  jmp _bar
```

[Compiler Explorer](https://godbolt.org/z/sYoMMjoxY)

Adding more parameters to the function (and tail call) increases the number of redundant loads/spills, too.

### PR DESCRIPTION
**Pull request by folkertdev**
fixes https://github.com/llvm/llvm-project/issues/56891
fixes https://github.com/llvm/llvm-project/issues/72390
fixes https://github.com/llvm/llvm-project/issues/147813

Currently the x86 backend miscompiles straightforward tail calls when the stack is used for argument passing. This program segfaults on any optimization level:

https://godbolt.org/z/5xr99jr4v

```c
typedef struct {
    uint64_t x;
    uint64_t y;
    uint64_t z;
} S;

__attribute__((noinline))
uint64_t callee(S s) {
    return s.x + s.y + s.z;
}

__attribute__((noinline))
uint64_t caller(S s) {
    [[clang::musttail]]
    return callee(s);
}
```

The immediate issue is that `caller` decides to shuffle values around on the stack, and in the process writes to `*rsp`, which contains the return address. With the return address trashed, the `ret` in  `callee` jumps to an invalid address.

```asm
caller:
        mov     rax, qword ptr [rsp + 24]
        mov     qword ptr [rsp + 16], rax
        movaps  xmm0, xmmword ptr [rsp + 8]
        movups  xmmword ptr [rsp], xmm0 ; <-- that is just all kinds of wrong
        movaps  xmmword ptr [rsp + 8], xmm0
        mov     qword ptr [rsp + 24], rax
        jmp     callee
```

However, I think the actual problem is that the x86 backend never considers `musttail` calls to be sibcalls. For sibcalls, no stack reshuffling is required at all, circumventing the problem here. 

This PR essentially copies https://reviews.llvm.org/D131034 (cc @huangjd), but this time I hope we can actually land this, and solve this problem.

The aarch64 backend also miscompiled this example, but they appear to have fixed it in LLVM 20.

Tail calls just not working for any sort of non-trivial argument types is a blocker for tail call support in rust, see https://github.com/rust-lang/rust/issues/144855#issuecomment-3536643185.

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 1]
```diff
@@ -2098,15 +2153,18 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
       isTailCall = false;
   }
 
-  if (isTailCall && !IsMustTail) {
+  if (isTailCall) {
     // Check if it's really possible to do a tail call.
-    isTailCall = IsEligibleForTailCallOptimization(CLI, CCInfo, ArgLocs,
-                                                   IsCalleePopSRet);
+    IsSibcall = IsEligibleForTailCallOptimization(CLI, CCInfo, ArgLocs,
+                                                  IsCalleePopSRet);
```
Comment (folkertdev) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: these changes to the sibcall logic are still needed to optimize to just a `jmp` in the case where arguments are just passed on (i.e. no stack shuffling is needed).

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 2]
```diff
@@ -2146,6 +2205,74 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
+  SDValue StackPtr;
+  const X86RegisterInfo *RegInfo = Subtarget.getRegisterInfo();
+  int RetAddrSize = 8;
+
+  // If we are doing a tail-call, any byval arguments will be written to stack
+  // space which was used for incoming arguments. If any the values being used
+  // are incoming byval arguments to this function, then they might be
+  // overwritten by the stores of the outgoing arguments. To avoid this, we
+  // need to make a temporary copy of them in local stack space, then copy back
+  // to the argument area.
```
Comment (folkertdev) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: sort of as a general question: wouldn't more code sharing between backends be a good idea? each backend reinventing this wheel just seems kind of unfortunate.

Anyway, this is my best effort of translating this from the arm backend.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 3]
```diff
@@ -2404,16 +2533,23 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
+          ByValSrc = Arg;
+          NeedsStackCopy = !isTailCall;
+        }
+
+        auto PtrVT = getPointerTy(DAG.getDataLayout());
+        SDValue DstAddr = DAG.getFrameIndex(FI, PtrVT);
+
+        // Copy the struct contents from ByValSrc to DstAddr.
+        MemOpChains2.push_back(CreateCopyOfByValArgument(
+            ByValSrc, DstAddr, Chain, Flags, DAG, dl));
```
Comment (folkertdev) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: So in the arm backend this logic is guareded with an `if (NeedsStackCopy)`, but even in my simple cases the `ByValTemporaries` appears to be empty (that does make sense, given how `ByValNeedsCopyForTailCall` exits early where I commented), but the `CreateCopyOfByValArgument` is still needed.

File: llvm/test/CodeGen/X86/musttail-struct.ll [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+; CHECK-NEXT:    mov dword ptr [rsp - 16], eax
+; CHECK-NEXT:    mov ecx, dword ptr [rsp + 16]
+; CHECK-NEXT:    mov dword ptr [rsp - 8], ecx
+
+; CHECK-NEXT:    mov dword ptr [rsp + 8], ecx
+; CHECK-NEXT:    mov dword ptr [rsp + 16], eax
+; CHECK-NEXT:    jmp swap # TAILCALL
+  %r = musttail call i32 @swap(ptr byval(%struct.1xi32) %1, ptr byval(%struct.1xi32) %0)
+  ret i32 %r
+}
```
Comment (folkertdev) [inline llvm/test/CodeGen/X86/musttail-struct.ll]: in this case the copy to the stack is not needed, there is sufficient register space. The arm logic doesn't seem to consider that case (likely because in practice by-val parameters are larger, and it's unlikely that there is sufficient space in register?)

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 5]
```diff
@@ -2018,6 +2018,61 @@ SDValue X86TargetLowering::getMOVL(SelectionDAG &DAG, const SDLoc &dl, MVT VT,
...
+  // Globals are always safe to copy from.
+  if (isa<GlobalAddressSDNode>(Src) || isa<ExternalSymbolSDNode>(Src))
+    return CopyOnce;
+
+  // Can only analyse frame index nodes, conservatively assume we need a
+  // temporary.
+  auto *SrcFrameIdxNode = dyn_cast<FrameIndexSDNode>(Src);
+  auto *DstFrameIdxNode = dyn_cast<FrameIndexSDNode>(Dst);
+  if (!SrcFrameIdxNode || !DstFrameIdxNode)
+    return CopyViaTemp;
```
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: If you look at the caller, Dst is an ISD::ADD, so casting to FrameIndexSDNode will fail.  (Unless the offset happens to be zero.)  I think the Arm backend creates a new FrameIndex for each byval value instead.

You can probably fixup this code to check if Dst is an ISD::ADD of a FrameIndex and a constant.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 6]
```diff
@@ -2018,6 +2018,61 @@ SDValue X86TargetLowering::getMOVL(SelectionDAG &DAG, const SDLoc &dl, MVT VT,
...
+
+  // FIXME:
+
+  //  // If the source is in the local frame, then the copy to the argument
+  //  memory
+  //  // is always valid.
+  //  bool FixedSrc = MFI.isFixedObjectIndex(SrcFI);
+  //  if (!FixedSrc ||
+  //      (FixedSrc && SrcOffset < -(int64_t)AFI->getArgRegsSaveSize()))
+  //    return CopyOnce;
```
[the remark this answers is not in the document]
Comment (efriedma-quic) [reply llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: The basic check here is checking whether we're referring to a non-fixed stack allocation (which will be allocated later), or some fixed stack offset which doesn't overlap the argument list, or some fixed stack offset which does overlap the argument list.  The first two cases, we just need a single copy; for the third case, we need CopyViaTemp.

In the Arm calling convention, this is a bit more complicated because byval values can be split across registers and memory: the allocation for a byval value can start below the argument list, but extend into it.

This isn't a thing on x86, so I think you can just replace the reference to getArgRegsSaveSize() with zero.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp
Comment (efriedma-quic) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: On other targets, if IsEligibleForTailCallOptimization concludes a musttail call can't actually be tail-called, we emit an error.  Probably x86 should do this too, so weird edges break loudly instead of miscompiling.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp (hunk 2 above)
Comment (efriedma-quic) [reply llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: There's been continual effort to refactor call lowering to share various bits of code... but it's hard because every calling convention has its own weird quirks.  Not sure how you'd extract out byval lowering, specifically.

File: llvm/test/CodeGen/X86/musttail-struct.ll (hunk 4 above)
Comment (folkertdev) [reply llvm/test/CodeGen/X86/musttail-struct.ll]: Yeah, I don't think this is worth it (right now).

**Review by folkertdev — COMMENTED** [review]
That was very helpful, thanks!

File: llvm/test/CodeGen/X86/musttail-struct.ll [hunk 7]
```diff
@@ -0,0 +1,197 @@
+; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
+; RUN: llc < %s -mtriple=x86_64-unknown-unknown -x86-asm-syntax=intel | FileCheck %s
```
Comment (folkertdev) [inline llvm/test/CodeGen/X86/musttail-struct.ll]: is testing just for x86_64 OK here?

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 8]
```diff
@@ -2404,21 +2615,40 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
+
+        if (NeedsStackCopy) {
+
+          auto PtrVT = getPointerTy(DAG.getDataLayout());
+          SDValue DstAddr = DAG.getFrameIndex(FI, PtrVT);
+
+          // Copy the struct contents from ByValSrc to DstAddr.
+          MemOpChains2.push_back(CreateCopyOfByValArgument(
+              ByValSrc, DstAddr, Chain, Flags, DAG, dl));
+        }
```
Comment (folkertdev) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: This now works, and prevents needless copies

**Review by efriedma-quic — COMMENTED** [review]
Let me know when you're ready for another round of review.

File: llvm/test/CodeGen/X86/swifttailcc-store-ret-address-aliasing-stack-slot.ll
Comment (efriedma-quic) [inline llvm/test/CodeGen/X86/swifttailcc-store-ret-address-aliasing-stack-slot.ll]: This looks very suspicious.

File: llvm/test/CodeGen/X86/sibcall.ll
[the remark this answers is not in the document]
Comment (folkertdev) [reply llvm/test/CodeGen/X86/sibcall.ll]: We are, because the `auto *SrcFrameIdxNode = dyn_cast<FrameIndexSDNode>(Src);` produces a NULL pointer in `ByValNeedsCopyForTailCall`. The `Src` value is apparently a `t7: i32,ch = CopyFromReg t0, Register:i32 %2`. 

I don't really know what that means, is there a straightforward way to make that check more permissive?

Also I see how `MFI.CreateStackObject` would create a stack object (and causes the `subl` and `addl`, but apparently the actual copy is optimized out?

File: llvm/test/CodeGen/X86/swifttailcc-store-ret-address-aliasing-stack-slot.ll
Comment (folkertdev) [reply llvm/test/CodeGen/X86/swifttailcc-store-ret-address-aliasing-stack-slot.ll]: Hmm, the cause is that the call is now marked as a sibcall. It properly qualifies to be one I think?

```diff
--- <unnamed>
+++ <unnamed>
@@ -17,8 +17,6 @@
 	callq	_foo
 	movq	%r14, (%rax)
 	movl	40(%rsp), %edx
-	movq	24(%rsp), %rcx
-	movq	%rcx, 40(%rsp)
 	movq	%rax, %r14
 	movq	%r13, %rdi
 	movq	%r15, %rsi
@@ -26,7 +24,6 @@
 	addq	$8, %rsp
 	popq	%rbx
 	popq	%r15
-	addq	$16, %rsp
 	jmp	_tc_fn                          ## TAILCALL
 	.cfi_endproc
                                         ## -- End function
```

so previously this moved the value at `rsp + 24` to `rsp + 40`, but then shifted the stack pointer by 16. Now we leave it at `rsp + 40` but don't move the stack pointer. I think that cancels out?

**Review by folkertdev — COMMENTED** [review]
Bit of a procedural question: how should I handle rebasing and force pushes? For me switching branches between different PRs kind of trashes the cache (ccache helps, but it's still a couple of minutes). So, instead I rebase to whatever latest upstream I've pulled in, but then every push is a force push, and reviewing those is difficult (and sometimes buggy). 

Over in the rust repository we have a bot make nice range diffs e.g. since the last review, e.g. 

https://github.com/rust-lang/rust/pull/148302#issuecomment-3490607077

So, how does llvm deal with this in a way that is convenient for the author and the reviewer?

**Comment by folkertdev** [comment]
I believe the problem with that PR, as with my initial implementation, is that it does not handle cases where arguments must be moved around on the stack before the tail call can be made. E.g. from the tests added in this PR:

```llvm
define dso_local i32 @swapByValArguments(ptr byval(%struct.1xi32) %0, ptr byval(%struct.1xi32) %1) {
  %r = musttail call i32 @swap(ptr byval(%struct.1xi32) %1, ptr byval(%struct.1xi32) %0)
  ret i32 %r
}
```

From what I can tell the PR you linked would reject this program because the arguments can't just be forwarded. This PR makes `musttail` work in more cases.

File: llvm/test/CodeGen/X86/musttail-struct.ll [hunk 9]
```diff
@@ -0,0 +1,320 @@
...
+; X32-LABEL: large_caller_new_value:
+; X32:       # %bb.0: # %entry
+; X32-NEXT:    sub esp, 20
+; X32-NEXT:    .cfi_def_cfa_offset 24
+; X32-NEXT:    mov dword ptr [esp], 0
+; X32-NEXT:    mov dword ptr [esp + 4], 1
+; X32-NEXT:    mov dword ptr [esp + 8], 2
+; X32-NEXT:    mov dword ptr [esp + 12], 3
+; X32-NEXT:    mov dword ptr [esp + 16], 4
+; X32-NEXT:    mov dword ptr [esp + 24], 0
```
Comment (rnk) [inline llvm/test/CodeGen/X86/musttail-struct.ll]: Apparently some LLVM subsystem can do MIR load-store-forwarding, that's wild.

**Comment by rnk** [comment]
> Bit of a procedural question: how should I handle rebasing and force pushes? For me switching branches between different PRs kind of trashes the cache (ccache helps, but it's still a couple of minutes). So, instead I rebase to whatever latest upstream I've pulled in, but then every push is a force push, and reviewing those is difficult (and sometimes buggy).

The official recommendation is to merge main into the PR branch: https://llvm.org/docs/GitHub.html#updating-pull-requests

But, I agree, it's not very ergonomic and it usually makes rebuilds slow.

**Review by rnk — COMMENTED** [review]
I think we should work towards merging this because correctness is the first priority.

However, if we want to be more ambitious and generate better code, I think we want to try to use the register file as the temporary storage for our copies. With this PR, we generate this sequence for each byval arg:
- load from source
- store to temp
- load from temp
- store to byval destination

Really what we want is a sequence of:
- load all parts of all byval args into virtual registers
- store all parts of all byval args into destination stack slots

Doing all the loads up front ensures that our writes don't alias our reads. If there's too much register pressure, the allocator will spill what it needs to.

However, implementing that is super complicated, and the common case is just forwarding byval parameters in place, so I think we should just iterate on the PR as is and get this unfortunate correctness issue (I apologize, it was pre-existing!) fixed ASAP.

I had some simplification suggestions to iterate on, but I don't see blockers.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 10]
```diff
@@ -2146,6 +2192,77 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
 
+  SDValue StackPtr;
+  const X86RegisterInfo *RegInfo = Subtarget.getRegisterInfo();
+
+  // If we are doing a tail-call, any byval arguments will be written to stack
+  // space which was used for incoming arguments. If any the values being used
+  // are incoming byval arguments to this function, then they might be
+  // overwritten by the stores of the outgoing arguments. To avoid this, we
+  // need to make a temporary copy of them in local stack space, then copy back
+  // to the argument area.
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]:
```suggestion
  // to the argument area.
  // FIXME: There's potential to improve the code by using virtual registers for temporary
  // storage, and letting the register allocator spill if needed.
```

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 11]
```diff
@@ -2146,6 +2192,77 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
+
+      auto PtrVT = getPointerTy(DAG.getDataLayout());
+
+      if (!StackPtr.getNode())
+        StackPtr =
+            DAG.getCopyFromReg(Chain, dl, RegInfo->getStackRegister(), PtrVT);
+
+      // Destination: where this byval should live in the callee’s frame
+      // after the tail call.
+      int32_t Offset = VA.getLocMemOffset() + FPDiff;
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]:
```suggestion
      int64_t Offset = VA.getLocMemOffset() + FPDiff;
```

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 12]
```diff
@@ -2146,6 +2192,77 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
...
+      int Size = VA.getLocVT().getFixedSizeInBits() / 8;
+      int FI = MF.getFrameInfo().CreateFixedObject(Size, Offset, true);
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]:
```suggestion
      int FI = MF.getFrameInfo().CreateFixedObject(Size, Offset, /*IsImmutable=*/true);
```

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 13]
```diff
@@ -2037,9 +2080,10 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
   bool Is64Bit        = Subtarget.is64Bit();
   bool IsWin64        = Subtarget.isCallingConvWin64(CallConv);
   bool IsSibcall      = false;
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]:
```suggestion
```

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp [hunk 14]
```diff
@@ -2098,15 +2142,18 @@ X86TargetLowering::LowerCall(TargetLowering::CallLoweringInfo &CLI,
       isTailCall = false;
   }
 
-  if (isTailCall && !IsMustTail) {
+  if (isTailCall) {
```
Comment (rnk) [inline llvm/lib/Target/X86/X86ISelLoweringCall.cpp]:
```suggestion
  // Check if this tail call is a "sibling" call, which is loosely defined to
  // be a tail call that only requires shuffling arguments in register
  // parameters.
  bool IsSibcall = false;
  if (isTailCall && !ShouldGuaranteeTCO) {
```

**Review by rnk — COMMENTED** [review]
I made some suggested edits to fix some final nits.

Thanks for the thorough test cases!

**Review by rnk — COMMENTED** [review]
I made some suggested edits to fix some final nits.

Thanks for the thorough test cases!

**Comment by rnk** [comment]
cc @nigham  @sbenzaquen  This PR should fix a Google-internal bug that Sam filed about musttail.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp (hunk 14 above)
Comment (folkertdev) [reply llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: Some `tailcc` tests regress when `!ShouldGuaranteeTCO` is included in the condition (they start explicitly copying arguments to/from the stack). If a `tailcc` call happens to have the shape of a sibcall, it should be fine to use that code path right?

**Comment by folkertdev** [comment]
> I think it would be reasonable to cherry pick this to the release. It's a correctness issue.

That would be neat, and would unblock further experimentation in `rustc` as well.

> I'm surprised these bugs lasted so long in the code.

Thanks for that context. I really had been wondering how this could be so broken in the most-used LLVM backend.

File: llvm/lib/Target/X86/X86ISelLoweringCall.cpp (hunk 11 above)
Comment (rnk) [reply llvm/lib/Target/X86/X86ISelLoweringCall.cpp]: This didn't seem to get applied

**Review by rnk — COMMENTED** [review]
I think the suggested fixes to avoid truncating integers didn't get applied.

**Review by rnk — APPROVED** [review]
Nevermind, they were applied, I was looking at the wrong view

**Review by rnk — APPROVED** [review]
(resolving comments)

**Comment by folkertdev** [comment]
Awesome, thanks for the reviews! 

Is there anything that should be done to nominate this for cherry-picking into LLVM 22?

**Comment by rnk** [comment]
LLVM has a substantial amount of post-commit CI, so I would let it bake for a few days to increase our confidence in its correctness. I set a reminder to propose it on Friday. I think these are the docs on the process:
https://releases.llvm.org/18.1.8/docs/GitHub.html#backporting-fixes-to-the-release-branches
