### PR TITLE
[clang-format] Handle common C++ non-keyword types as such

### LINKED ISSUE #83400: clang-format: Wrong spacing in macro with C-style cast and address-of operator
- Reproducible in 17.0.0 to 17.0.6
- Not reproducible in 16.0.6 and earlier
- 18+ not tested yet, will do when it lands in Fedora 39 or the pre-commit mirror

---

We noticed a regression in clang-format when moving from clang-format 16 to 17 in godotengine/godot: https://github.com/godotengine/godot/pull/88959

The following test case reproduces the issue with the default clang-format config:
```cpp
#include <cstdint>
#include <cstdio>

#define PRINT_ADDRESS(m_name) printf("%d\n", (uint64_t)&m_name)

void func1() {}
void func2() {}

int main() {
  PRINT_ADDRESS(func1);
  PRINT_ADDRESS(func2);
  return 0;
}
```

This is formatted as is by clang-format 16, but running clang-format 17 generates the following diff:
```diff
diff --git a/main.cpp b/main.cpp
index c325f7a..81a6329 100644
--- a/main.cpp
+++ b/main.cpp
@@ -1,7 +1,7 @@
 #include <cstdint>
 #include <cstdio>
 
-#define PRINT_ADDRESS(m_name) printf("%d\n", (uint64_t)&m_name)
+#define PRINT_ADDRESS(m_name) printf("%d\n", (uint64_t) & m_name)
 
 void func1() {}
 void func2() {}
```

It seems to treat `&` as a bitwise operator instead of address-of operator.

Here's a reproduction project with this test case, and a config for `pre-commit` to run both clang-format 16 and 17 in turns. You can set it up with:
```
pip install pre-commit
pre-commit install
pre-commit run -a
```

[clang_format_operator_spacing.zip](https://github.com/llvm/llvm-project/files/14446204/clang_format_operator_spacing.zip)

---

Real life examples found in Godot:

```diff
diff --git a/core/extension/gdextension_interface.cpp b/core/extension/gdextension_interface.cpp
index 0c96c32187a55..f96a8873cafd9 100644
--- a/core/extension/gdextension_interface.cpp
+++ b/core/extension/gdextension_interface.cpp
@@ -1415,7 +1415,7 @@ static void gdextension_editor_help_load_xml_from_utf8_chars(const char *p_data)
 #endif
 }
 
-#define REGISTER_INTERFACE_FUNC(m_name) GDExtension::register_interface_function(#m_name, (GDExtensionInterfaceFunctionPtr)&gdextension_##m_name)
+#define REGISTER_INTERFACE_FUNC(m_name) GDExtension::register_interface_function(#m_name, (GDExtensionInterfaceFunctionPtr) & gdextension_##m_name)
 
 void gdextension_setup_interface() {
 	REGISTER_INTERFACE_FUNC(get_godot_version);
diff --git a/core/variant/variant_internal.h b/core/variant/variant_internal.h
index 171074188f629..79bed9be33709 100644
--- a/core/variant/variant_internal.h
+++ b/core/variant/variant_internal.h
@@ -810,7 +810,7 @@ struct VariantInternalAccessor<bool> {
 #define VARIANT_ACCESSOR_NUMBER(m_type)                                                                        \
 	template <>                                                                                                \
 	struct VariantInternalAccessor<m_type> {                                                                   \
-		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type)*VariantInternal::get_int(v); }    \
+		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type) * VariantInternal::get_int(v); }  \
 		static _FORCE_INLINE_ void set(Variant *v, m_type p_value) { *VariantInternal::get_int(v) = p_value; } \
 	};
 
diff --git a/core/variant/variant_setget.cpp b/core/variant/variant_setget.cpp
index 50c9c10987b2f..20941b944fb3f 100644
--- a/core/variant/variant_setget.cpp
+++ b/core/variant/variant_setget.cpp
@@ -433,9 +433,9 @@ Variant Variant::get_named(const StringName &p_member, bool &r_valid) const {
 			}                                                                                                                        \
 			m_assign_type num;                                                                                                       \
 			if (value->get_type() == Variant::INT) {                                                                                 \
-				num = (m_assign_type)*VariantGetInternalPtr<int64_t>::get_ptr(value);                                                \
+				num = (m_assign_type) * VariantGetInternalPtr<int64_t>::get_ptr(value);                                              \
 			} else if (value->get_type() == Variant::FLOAT) {                                                                        \
-				num = (m_assign_type)*VariantGetInternalPtr<double>::get_ptr(value);                                                 \
+				num = (m_assign_type) * VariantGetInternalPtr<double>::get_ptr(value);                                               \
 			} else {                                                                                                                 \
 				*oob = false;                                                                                                        \
 				*valid = false;                                                                                                      \
@@ -495,9 +495,9 @@ Variant Variant::get_named(const StringName &p_member, bool &r_valid) const {
 			}                                                                                                                  \
 			m_assign_type num;                                                                                                 \
 			if (value->get_type() == Variant::INT) {                                                                           \
-				num = (m_assign_type)*VariantGetInternalPtr<int64_t>::get_ptr(value);                                          \
+				num = (m_assign_type) * VariantGetInternalPtr<int64_t>::get_ptr(value);                                        \
 			} else if (value->get_type() == Variant::FLOAT) {                                                                  \
-				num = (m_assign_type)*VariantGetInternalPtr<double>::get_ptr(value);                                           \
+				num = (m_assign_type) * VariantGetInternalPtr<double>::get_ptr(value);                                         \
 			} else {                                                                                                           \
 				*oob = false;                                                                                                  \
 				*valid = false;                                                                                                \
```

But you can also see in the same PR https://github.com/godotengine/godot/pull/88959 that other cases where `&` _is_ a bitwise operator were fixed by clang-format. I'm not sure there's any easy way for clang-format to know which is which, if so I understand if this is considered a "won't fix".

### PR DESCRIPTION
**Pull request by owenca**
Fixes #83400.

### CODE REVIEW

File: clang/lib/Format/FormatToken.cpp [hunk 1]
```diff
@@ -66,13 +72,17 @@ bool FormatToken::isSimpleTypeSpecifier() const {
   case tok::kw_decltype:
   case tok::kw__Atomic:
     return true;
+  case tok::identifier:
+    return IsCpp && std::binary_search(CppNonKeywordTypes.begin(),
+                                       CppNonKeywordTypes.end(), TokenText);
```
Comment (zygoloid) [inline clang/lib/Format/FormatToken.cpp:77]: Should this really be C++-only? All of the types in your list are standard library header types in C too, except for `byte` (which, as noted above, probably shouldn't be there).

File: clang/lib/Format/FormatToken.cpp [hunk 2]
```diff
@@ -34,9 +34,15 @@ const char *getTokenTypeName(TokenType Type) {
   return nullptr;
 }
 
+// Sorted common C++ non-keyword types.
+static SmallVector<StringRef> CppNonKeywordTypes = {
+    "byte",   "int16_t",  "int32_t",  "int64_t",  "int8_t",
```
Comment (zygoloid) [inline clang/lib/Format/FormatToken.cpp:39]: Does `byte` really belong here? It's not available as an unqualified name, only as `std::byte`. I could see an argument for including `nullptr_t` here because it is available unqualified, but even that seems a little hard to justify since I don't think people write that often. I also expect people use `byte` as a variable name frequently; the same doesn't seem to be true for these other names.

File: clang/lib/Format/FormatToken.cpp [hunk 3]
```diff
@@ -34,9 +34,15 @@ const char *getTokenTypeName(TokenType Type) {
...
+    "size_t", "uint16_t", "uint32_t", "uint64_t", "uint8_t",
```
Comment (zygoloid) [inline clang/lib/Format/FormatToken.cpp:40]: Maybe also `ptrdiff_t`, `intptr_t`, `uintptr_t`. And there's also `float_t`, `double_t`, `uint_least32_t`, ...

I wonder if the best heuristic to use here would be simply to look for an identifier that matches `[a-z0-9_]*_t`.

File: clang/lib/Format/FormatToken.cpp [hunk 4]
```diff
@@ -34,9 +34,15 @@ const char *getTokenTypeName(TokenType Type) {
...
+};
+
 // FIXME: This is copy&pasted from Sema. Put it in a common place and remove
 // duplication.
```
Comment (zygoloid) [inline clang/lib/Format/FormatToken.cpp:44]: Looks like this comment is no longer correct.

**Comment by zygoloid** [comment]
Another possibility to consider for the original bug: `(single_identifier)` is almost certainly a cast, not redundant parentheses, unless `single_identifier` names a macro argument. So I wonder if that would be a better heuristic to use to fix the regression.

File: clang/lib/Format/FormatToken.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:77]: There’s no C per se in clang-format. `IsCpp` by clang-format convention means C/C++/Objective-C/
Objective-C++.

File: clang/lib/Format/FormatToken.cpp (hunk 3 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:40]: As the comment says, the list includes ~common~ non-keyword types. We can always grow the list in the future if necessary. I thought about using regex but went for a specific list in order to minimize the possibility of regression.

File: clang/lib/Format/FormatToken.cpp (hunk 4 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:44]: This comment is still correct. We need to call the function in the lexer to fix it.

File: clang/lib/Format/FormatToken.cpp (hunk 3 above)
Comment (zygoloid) [reply clang/lib/Format/FormatToken.cpp:40]: According to codesearch.isocpp.org, `intptr_t`, `uintptr_t`, and `ptrdiff_t` are all more common than `int8_t`. Also I'd note that POSIX reserves all identifiers ending in `_t` for use as types, and C reserves all identifiers starting with `int` or `uint` and ending in `_t` for use as types.

File: clang/lib/Format/FormatToken.cpp (hunk 4 above)
Comment (zygoloid) [reply clang/lib/Format/FormatToken.cpp:44]: This function is no longer simply copy/pasted from `Sema`. It doesn't even do the same thing as the Sema function any more.

**Comment by owenca** [comment]
> Another possibility to consider for the original bug: `(single_identifier)` is almost certainly a cast, not redundant parentheses, unless `single_identifier` names a macro argument. So I wonder if that would be a better heuristic to use to fix the regression.

I don’t think that would work as`(identifier)` can be a number of constructs depending on the context. It can be part of a function/macro call, function declaration, macro definition, C++ cast, C cast, `sizeof` operand, etc.

**Comment by zygoloid** [comment]
> > Another possibility to consider for the original bug: `(single_identifier)` is almost certainly a cast, not redundant parentheses, unless `single_identifier` names a macro argument. So I wonder if that would be a better heuristic to use to fix the regression.
> 
> I don’t think that would work as`(identifier)` can be a number of constructs depending on the context. It can be part of a function/macro call, function declaration, macro definition, C++ cast, C cast, `sizeof` operand, etc.

OK, but the context is deciding whether `(identifier)&x` or `(identifier)*x` is a binary operator or a cast. Given no other information, the fact that it's a single identifier seems like a very strong signal that it's a cast.

I don't think this PR fixes #83400 -- handling a small handful of common types won't address the same issue for the much larger class of cases where the type name is not one of these types. Eg, in #83400 itself the examples included:

```diff
-		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type)*VariantInternal::get_int(v); }    \
+		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type) * VariantInternal::get_int(v); }  \
```

But looking for a parenthesized single identifier addresses all of the examples in the issue.

File: clang/lib/Format/FormatToken.cpp (hunk 3 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:40]: I was aware of that. By “common” I mean common C-casted. We definitely don’t want to include POSIX-specific types as we have the TypeNames option for that. Also, we don’t want to cater to C-specific constructs if it might regress C++ code.

File: clang/lib/Format/FormatToken.cpp (hunk 4 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:44]: That was the case before this patch though.

**Comment by owenca** [comment]
> > > Another possibility to consider for the original bug: `(single_identifier)` is almost certainly a cast, not redundant parentheses, unless `single_identifier` names a macro argument. So I wonder if that would be a better heuristic to use to fix the regression.
> > 
> > 
> > I don’t think that would work as`(identifier)` can be a number of constructs depending on the context. It can be part of a function/macro call, function declaration, macro definition, C++ cast, C cast, `sizeof` operand, etc.
> 
> OK, but the context is deciding whether `(identifier)&x` or `(identifier)*x` is a binary operator or a cast. Given no other information, the fact that it's a single identifier seems like a very strong signal that it's a cast.
> 
> I don't think this PR fixes #83400 -- handling a small handful of common types won't address the same issue for the much larger class of cases where the type name is not one of these types. Eg, in #83400 itself the examples included:
> 
> ```diff
> -		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type)*VariantInternal::get_int(v); }    \
> +		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type) * VariantInternal::get_int(v); }  \
> ```
> 
> But looking for a parenthesized single identifier addresses all of the examples in the issue.

This patch does not only fix formatting of C-casting to a C++ standard type. It correctly identifies (most of) such types and might have fixed other kinds of bugs. For casting to a user-defined type, the TypeNames option can be used.

File: clang/lib/Format/FormatToken.cpp (hunk 2 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:39]: Good point about `byte`. I will remove it from the list.

File: clang/lib/Format/FormatToken.cpp (hunk 4 above)
Comment (zygoloid) [reply clang/lib/Format/FormatToken.cpp:44]: Before this patch, the two functions were intended to do the same thing, but have apparently diverged. After this patch they are not intended to do the same thing. The FIXME is wrong, can you fix it please?

**Comment by zygoloid** [comment]
> This patch does not only fix formatting of C-casting to a C++ standard type. It correctly identifies (most of) such types and might have fixed other kinds of bugs.

Sure, this patch seems like a good change. But it does not fix #83400.

File: clang/lib/Format/FormatToken.cpp (hunk 3 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:40]: I considered to include all [fixed width integer types](https://en.cppreference.com/w/cpp/types/integer) but decided to include only the common ones to avoid possible regressions. (I also looked at [fixed width floating-point types](https://en.cppreference.com/w/cpp/types/floating-point) and think we should wait until C++23 is commonly used.)

Comment (zygoloid) [reply clang/lib/Format/FormatToken.cpp:40]: On codesearch.isocpp.org, `(intptr_t)` is more common than `(int8_t)` and `(int16_t)`, and similar to `(int32_t)`. But why should this general function that's used in various places in clang-format care about how often the type is cast with a C-style cast? That doesn't make sense to me.

I find it extremely unlikely that anyone would use `intN_t` as anything other than a type; I think your concerns about regressions are unfounded. In contrast, there are 518 hits for `(intptr_t)&` in isocpp codesearch, which seems pretty logical to me because casts to `(intptr_t)` will be casts from pointers.

**Comment by owenca** [comment]
> > This patch does not only fix formatting of C-casting to a C++ standard type. It correctly identifies (most of) such types and might have fixed other kinds of bugs.
> 
> Sure, this patch seems like a good change. But it does not fix #83400.

It does fix the example given. For other diffs involving user-defined types, the user need to use the TypeNames option. (If that doesn't work, a separate issue should be filed.)

**Comment by owenca** [comment]
> But looking for a parenthesized single identifier addresses all of the examples in the issue.

I don't think it would work, but you are welcome to submit a patch to prove me wrong. 🙂

File: clang/lib/Format/FormatToken.cpp (hunk 3 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:40]: > I find it extremely unlikely that anyone would use `intN_t` as anything other than a type; I think your concerns about regressions are unfounded.

"Extremely unlikely" doesn't mean impossible.

I actually hesitated on whether to include `intptr_t`/`uintprt_t` because they are marked as optional. I can include them though.

File: clang/lib/Format/FormatToken.cpp (hunk 4 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:44]: See [here](https://github.com/llvm/llvm-project/pull/83533#issuecomment-1974198544). After this patch,I will add another parameter and call `Token::isSimpleTypeSpecifier()` (which was moved out of `Sema` in #80101) directly. That's the right time to fix (i.e. remove) the comment.

**Comment by zygoloid** [comment]
> It does fix the example given.

#83400 has 6 real-world examples. This patch fixes none of them. It also has a reduced testcase, which this patch does fix. But fixing the reduced testcase without fixing the real-world examples is not fixing the bug.

File: clang/lib/Format/FormatToken.cpp [hunk 5]
```diff
@@ -71,8 +71,21 @@ bool FormatToken::isSimpleTypeSpecifier() const {
   }
 }
 
-bool FormatToken::isTypeOrIdentifier() const {
-  return isSimpleTypeSpecifier() || Tok.isOneOf(tok::kw_auto, tok::identifier);
+// Sorted common C++ non-keyword types.
+static SmallVector<StringRef> CppNonKeywordTypes = {
+    "int16_t",  "int32_t",  "int64_t",  "int8_t",  "intptr_t",  "size_t",
```
Comment (mydeveloperday) [inline clang/lib/Format/FormatToken.cpp:76]: ssize_t too? should everything be considered? https://en.cppreference.com/w/cpp/types/integer

File: clang/lib/Format/QualifierAlignmentFixer.cpp [hunk 6]
```diff
@@ -268,20 +268,24 @@ const FormatToken *LeftRightQualifierAlignmentFixer::analyzeRight(
...
     return Tok;
 
+  const bool IsCpp = Style.isCpp();
+
   // The case `const long long int volatile` -> `long long int const volatile`
   // The case `long const long int volatile` -> `long long int const volatile`
   // The case `long long volatile int const` -> `long long int const volatile`
   // The case `const long long volatile int` -> `long long int const volatile`
-  if (TypeToken->isSimpleTypeSpecifier()) {
+  if (TypeToken->isTypeName(IsCpp)) {
```
Comment (mydeveloperday) [inline clang/lib/Format/QualifierAlignmentFixer.cpp:277]: I'm not a fan of this extra argument proliferation

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 7]
```diff
@@ -620,6 +620,23 @@ TEST_F(TokenAnnotatorTest, UnderstandsCasts) {
   ASSERT_EQ(Tokens.size(), 8u) << Tokens;
   EXPECT_TOKEN(Tokens[3], tok::r_paren, TT_Unknown);
   EXPECT_TOKEN(Tokens[4], tok::amp, TT_BinaryOperator);
+
+  Tokens = annotate("#define FOO(bar) foo((uint64_t)&bar)");
+  ASSERT_EQ(Tokens.size(), 15u) << Tokens;
+  EXPECT_TOKEN(Tokens[10], tok::r_paren, TT_CastRParen);
+  EXPECT_TOKEN(Tokens[11], tok::amp, TT_UnaryOperator);
+
+  Tokens = annotate("#define FOO(bar) foo((time_t) & bar)");
```
Comment (mydeveloperday) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:629]: you didn't have time_t in the list did you? does that mean we are just checking this one uint64_t type above

**Comment by mydeveloperday** [comment]
> > But looking for a parenthesized single identifier addresses all of the examples in the issue.
> 
> I don't think it would work, but you are welcome to submit a patch to prove me wrong. 🙂

+1 for this, it will be the 95%/5% rule, you might think all cases of (identifier) is a cast, but I'm pretty sure it won't be I'm with @owenca  on this, this patch will move us closer, meaning users don't need to add common types to TypeNames

**Review by mydeveloperday — APPROVED** [review]

**Comment by zygoloid** [comment]
> +1 for this, it will be the 95%/5% rule, you might think all cases of (identifier) is a cast, but I'm pretty sure it won't be

Specifically, what I suggested was: when disambiguating whether `(identifier)&...` or `(identifier)*...` is a cast vs a multiplication or bitwise and (that is, the case that the previous patch changed, resulting in the regression we're trying to fix), treat it as a cast unless `identifier` is a macro parameter name. I think that will be right >99% of the time. And even when clang-format gets it wrong, the programmer can fix that by removing the redundant and non-idiomatic parentheses around the identifier.

> I'm with @owenca on this, this patch will move us closer, meaning users don't need to add common types to TypeNames

As I said before, I think special-casing these typedefs is a good thing - it's reasonable for clang-format to assume they're type names. But I don't think this moves us much closer to fixing the bug, because most casts won't be to one of these typedefs.

I do wonder, though -- there's a lot of churn in this patch adding and wiring through a new parameter. Can the `TypeNames` mechanism be prepopulated with this list of types instead?

File: clang/lib/Format/FormatToken.cpp (hunk 5 above)
Comment (owenca) [reply clang/lib/Format/FormatToken.cpp:76]: `ssize_t` is a POSIX type. Regarding the fixed-width integer types, I wanted to start with a few common ones. (I will add `ptrdiff_t` though.)

File: clang/lib/Format/QualifierAlignmentFixer.cpp (hunk 6 above)
Comment (owenca) [reply clang/lib/Format/QualifierAlignmentFixer.cpp:277]: Neither am I, but I don't know of a better way. BTW, `Token::isSimpleTypeSpecifier(const LangOptions &LangOpts)` also has a similar parameter.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 7 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:629]: I intentionally excluded `time_t`, but on second thought I'll add it, along with `clock_t`.

File: clang/lib/Format/QualifierAlignmentFixer.cpp (hunk 6 above)
Comment (mydeveloperday) [reply clang/lib/Format/QualifierAlignmentFixer.cpp:277]: Thanks fine, we'll live with it..

**Comment by mydeveloperday** [comment]
Just thinking out loud and maybe not for this patch but for a more general solution, what we seem to never do is collect information about types local to the file as we go; For example what if a first pass identified types from declarations and function argument declarations, return types, template arguments and added them to a structure that would have some probability that a given identifier was actually a type.


Foo x;
or Bar(Foo x)

This would give "Foo" some sort of weight to it being a type, which then would give more promenance to it being a cast than a binary operation.

The problem I see and why I think I agree more with @owenca is people love to wrap logical operations in '()' so I think assuming (a) is a cast is hard especailly for the `(a) * (b)` cases, but if we had already see `a` as a type we'd at least have some more confidence that a `(a)` was a cast.

Given the example below the macro argument doesn't tell me its a type, but the `<m_type>` does as does the return type of `get()`

By the time we'd arrived at the `(m_type)*` we'd already have a good idea that this m_type was a type and not a variable and so by definition we'd say it was a cast

```
 #define VARIANT_ACCESSOR_NUMBER(m_type)                                                                        \
 	template <>                                                                                                \
 	struct VariantInternalAccessor<m_type> {                                                                   \
-		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type)*VariantInternal::get_int(v); }    \
+		static _FORCE_INLINE_ m_type get(const Variant *v) { return (m_type) * VariantInternal::get_int(v); }  \
 		static _FORCE_INLINE_ void set(Variant *v, m_type p_value) { *VariantInternal::get_int(v) = p_value; } \
 	};
```

There is some precident for this in using the "majority" rule of something local to the file (from Jaspers original slides)

```
More important problems
int *a; or int* a;
● Clang-format has an adaptive mode:
○ Count cases in input
○ Take majority vote
```

Any thoughts?

**Comment by owenca** [comment]
> Can the TypeNames mechanism be prepopulated with this list of types instead?

I don't see how that would work. Please note that the TypeNames option is not specific to C/C++/Objective-C. Otherwise, I could simply change `isTypeName(bool IsCpp)` to `isCppTypeName()`.

**Comment by owenca** [comment]
> Just thinking out loud and maybe not for this patch but for a more general solution, what we seem to never do is collect information about types local to the file as we go; For example what if a first pass identified types from declarations and function argument declarations, return types, template arguments and added them to a structure that would have some probability that a given identifier was actually a type.

I'm kind of skeptical because we can't even correctly annotate the declarators all the time, but someone must actually try it to find out.
