### PR TITLE
[mlir][linalg] Fix `SemiFunctionType` custom parsing crash on missing `()`

### LINKED ISSUE #109128: [mlir] [linalg] Generalize linalg.depthwise_conv_2d_nhwc_hwcm crash
I'm trying to generalize a linalg convolution (see code below) and the compiler crashed (see the file 
[crash.txt](https://github.com/user-attachments/files/17043886/crash.txt)
attached).

// RUN: mlir-opt "$1".mlir --pass-pipeline=" \
// RUN:   builtin.module(transform-interpreter{ \
// RUN:     debug-bind-trailing-args=linalg.depthwise_conv_2d_nhwc_hwcm},canonicalize,cse,symbol-dce)" \
// RUN:   -o "$1"_opt.mlir

// Original depthwise_conv_2d_nhwc_hwcm to be converted into generic.
func.func @depthwise_conv_2d_nhwc_hwcm(%input: tensor<2x4x5x2xf32>, %filter: tensor<2x2x2x3xf32>, %output: tensor<2x3x4x2x3xf32>) {
  %depw = linalg.depthwise_conv_2d_nhwc_hwcm
     { dilations = dense<1> : tensor<2xi64>, strides = dense<1> : tensor<2xi64> }
     ins(%input, %filter : tensor<2x4x5x2xf32>, tensor<2x2x2x3xf32>)
    outs(%output : tensor<2x3x4x2x3xf32>) -> tensor<2x3x4x2x3xf32>
  return %depw : tensor<2x3x4x2x3xf32>
}

module attributes {transform.with_named_sequence} {

  transform.named_sequence @__transform_main(
    %arg0: !transform.any_op,
    %conv: !transform.op<"linalg.depthwise_conv_2d_nhwc_hwcm">) {

    transform.debug.emit_remark_at %conv, "Input conv" : !transform.op<"linalg.depthwise_conv_2d_nhwc_hwcm">

    %res = transform.structured.generalize %conv
      : !transform.op<"linalg.depthwise_conv_2d_nhwc_hwcm">
      -> !transform.any_op 

    transform.debug.emit_remark_at %res, "result" : !transform.any_op

    transform.yield
  }
}

### PR DESCRIPTION
**Pull request by ubfx**
The `SemiFunctionType` allows printing/parsing a set of argument and result types, where there is always exactly one argument type and zero or more result types. If there are no result types, the argument type can be written without enclosing parens in the assembly. If there is at least one result type, the parens are mandatory.

This patch fixes a bug where omitting the parens around the argument types for a `SemiFunctionType` with non-optional result Types would crash the parser. It introduces a `bool` argument `resultOptional` to the parser and printer which, when `false`, correctly enforces the parens around argument types, otherwise printing an error.

Fix https://github.com/llvm/llvm-project/issues/109128

### CODE REVIEW

**Comment by ubfx** [comment]
Ping

File: mlir/lib/Dialect/Linalg/TransformOps/Syntax.cpp [hunk 1]
```diff
@@ -12,9 +12,13 @@
...
   argumentType = resultType = nullptr;
-  bool hasLParen = parser.parseOptionalLParen().succeeded();
+
+  bool hasLParen = resultOptional ? parser.parseOptionalLParen().succeeded()
+                                  : parser.parseLParen().succeeded();
+  if (!resultOptional && !hasLParen)
+    return failure();
   if (parser.parseType(argumentType).failed())
     return failure();
   if (!hasLParen)
```
Comment (Max191) [inline mlir/lib/Dialect/Linalg/TransformOps/Syntax.cpp:24]: Does this need the new `resultOptional` option? Does it work if you do something like:
```cpp
  argumentType = resultType = nullptr;
  bool hasLParen = parser.parseOptionalLParen().succeeded();
  if (parser.parseType(argumentType).failed())
    return failure();
  if (!hasLParen)
    return success(parser.parseRParen().failed() ||
                   parser.parseArrow().failed() ||
                   parser.parseType(resultType).failed());
  return failure(parser.parseRParen().failed() ||
                 parser.parseArrow().failed() ||
                 parser.parseType(resultType).failed());
```

**Review by Max191 — COMMENTED** [review]
I don't have experience working with the parser, but it seems like it might not be necessary to thread this `resultOptional` option through the parser function. Can it be done without the new option?

File: mlir/lib/Dialect/Linalg/TransformOps/Syntax.cpp (hunk 1 above)
Comment (ubfx) [reply mlir/lib/Dialect/Linalg/TransformOps/Syntax.cpp:24]: This causes problems for Ops with exactly one non optional result, like `transform.structured.generalize`. We could write an invalid version of such an op like this:
```mlir
transform.structured.generalize %arg0 : !transform.any_op
```
This would successfully go through your parser because it looks like a valid `SemiFunctionType` with optional or no results. However, this will then lead to a crash during Op creation, because `resultType` is never initialized, yet it is not optional.
In general, if we have a non-optional result, we always either have to fail within the parser, or we have to correctly read the result's Type. Without the `resultOptional` argument enforcing the reading of the result, we can have ops slip through the cracks by using the form without parens and result Types.

Comment (Max191) [reply mlir/lib/Dialect/Linalg/TransformOps/Syntax.cpp:24]: I see. In that case there is no way for the parser to know that the result is required. Considering that these ops must have a result, perhaps it would be better for these transform ops to use some different type of assembly format (that requires a result) instead of SemiFunctionType, but the extra option seems okay to me.

**Review by Max191 — APPROVED** [review]
This seems okay to me now, but maybe wait one more day for others to take a look.

**Comment by Max191** [comment]
@ftynse could you take a look (you are on git blame)?
