### PR TITLE
[GlobalOpt] Handle operators separately when removing GV users

### LINKED ISSUE #64680: Dead Code Elimination Regression at -O3 (trunk vs. llvmorg-16.0.6)
```c
static int a, d;
static int *b[3];
static int **c = &b[2];
void foo(void);
void bar20_(void);
int main() {
  for (; a < 3; ++a) {
    int e = 8;
    bar20_();
    if (!e)
      foo();
    *c = &e;
    *c = &d;
  }
}
```

`clang-01dcad040641 (trunk) -O3` cannot eliminate the call to foo but `clang-llvmorg-16.0.6 -O3` can.

-----------------------------------------------------------------------

`clang-01dcad04064182155d5568a464dfea95ba567764 -O3 case.c -S -emit-llvm -o case.ll`
<details ><summary>Emitted IR</summary><p>

```ll
; ModuleID = 'case.c'
source_filename = "case.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@a = internal unnamed_addr global i32 0, align 4
@b = internal unnamed_addr global [3 x ptr] zeroinitializer, align 16

; Function Attrs: nounwind uwtable
define dso_local i32 @main() local_unnamed_addr #0 {
  %1 = alloca i32, align 4
  %2 = load i32, ptr @a, align 4, !tbaa !5
  %3 = icmp slt i32 %2, 3
  br i1 %3, label %4, label %12

4:                                                ; preds = %0, %8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %1) #3
  store i32 8, ptr %1, align 4, !tbaa !5
  call void @bar20_() #3
  %5 = load i32, ptr %1, align 4, !tbaa !5
  %6 = icmp eq i32 %5, 0
  br i1 %6, label %7, label %8

7:                                                ; preds = %4
  call void @foo() #3
  br label %8

8:                                                ; preds = %7, %4
  store ptr %1, ptr getelementptr inbounds ([3 x ptr], ptr @b, i64 0, i64 2), align 16, !tbaa !9
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %1) #3
  %9 = load i32, ptr @a, align 4, !tbaa !5
  %10 = add nsw i32 %9, 1
  store i32 %10, ptr @a, align 4, !tbaa !5
  %11 = icmp slt i32 %9, 2
  br i1 %11, label %4, label %12, !llvm.loop !11

12:                                               ; preds = %8, %0
  ret i32 0
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

declare void @bar20_() local_unnamed_addr #2

declare void @foo() local_unnamed_addr #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1

attributes #0 = { nounwind uwtable "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #3 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 18.0.0 (git@github.com:llvm/llvm-project.git 01dcad04064182155d5568a464dfea95ba567764)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !7, i64 0}
!11 = distinct !{!11, !12}
!12 = !{!"llvm.loop.mustprogress"}
```

</p></details>

-----------------------------------------------------------------------

`clang-af2ed9f794c422923414d162dd1f48d986e2d6e3 -O3 case.c -S -emit-llvm -o case.ll`
<details ><summary>Emitted IR</summary><p>

```ll
; ModuleID = 'case.c'
source_filename = "case.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@a = internal unnamed_addr global i32 0, align 4
@d = internal global i32 0, align 4
@b = internal unnamed_addr global [3 x ptr] zeroinitializer, align 16

; Function Attrs: nounwind uwtable
define dso_local i32 @main() local_unnamed_addr #0 {
  %1 = load i32, ptr @a, align 4, !tbaa !5
  %2 = icmp slt i32 %1, 3
  br i1 %2, label %3, label %7

3:                                                ; preds = %0, %3
  tail call void @bar20_() #2
  store ptr @d, ptr getelementptr inbounds ([3 x ptr], ptr @b, i64 0, i64 2), align 16, !tbaa !9
  %4 = load i32, ptr @a, align 4, !tbaa !5
  %5 = add nsw i32 %4, 1
  store i32 %5, ptr @a, align 4, !tbaa !5
  %6 = icmp slt i32 %4, 2
  br i1 %6, label %3, label %7, !llvm.loop !11

7:                                                ; preds = %3, %0
  ret i32 0
}

declare void @bar20_() local_unnamed_addr #1

attributes #0 = { nounwind uwtable "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 16.0.6 (git@github.com:llvm/llvm-project.git 7cbf1a2591520c2491aa35339f227775f4d3adf6)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !7, i64 0}
!11 = distinct !{!11, !12}
!12 = !{!"llvm.loop.mustprogress"}
```

</p></details>

-----------------------------------------------------------------------

Bisects to d94e8479fcd7cd57fa9c6f3f3aa24d2ad3e11d89
Committed by: @fhahn

### PR DESCRIPTION
**Pull request by gandhi56**
Refactor globalopt by eliminating redundant code. Fix https://github.com/llvm/llvm-project/issues/64680.

### CODE REVIEW

**Comment by gandhi56** [comment]
I see a flaw in my solution, I will update this PR with a more effective solution. Stay tuned!

**Comment by gandhi56** [comment]
Internal CI passed.

**Comment by gandhi56** [comment]
ping

**Comment by gandhi56** [comment]
@nikic @fhahn ping

**Comment by gandhi56** [comment]
Ping

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 1]
```diff
@@ -201,61 +201,51 @@ CleanupPointerRootUsers(GlobalVariable *GV,
...
-      }
-    } else if (MemTransferInst *MTI = dyn_cast<MemTransferInst>(U)) {
-      GlobalVariable *MemSrc = dyn_cast<GlobalVariable>(MTI->getSource());
-      if (MemSrc && MemSrc->isConstant()) {
-        Changed = true;
-        MTI->eraseFromParent();
-      } else if (Instruction *I = dyn_cast<Instruction>(MTI->getSource())) {
-        if (I->hasOneUse())
-          Dead.push_back(std::make_pair(I, MTI));
-      }
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:237]: Why did you drop the support for memset/memcpy? It causes some regressions https://github.com/dtcxzyw/llvm-opt-benchmark/pull/466#discussion_r1546056742.

Please add some tests with memset/memcpy.

**Review by dtcxzyw — CHANGES_REQUESTED** [review]

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp (hunk 1 above)
Comment (gandhi56) [reply llvm/lib/Transforms/IPO/GlobalOpt.cpp:237]: For some reason we didn't have any tests with memset/memcpy. I will revert this snippet and add some tests.

File: llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-loads.ll [hunk 2]
```diff
@@ -0,0 +1,42 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
```
Comment (fhahn) [inline llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-loads.ll:1]: please add new test coverage in a separate PR (i.e. precommit them, so that here we only see the functional diff)

**Review by fhahn — COMMENTED** [review]
Please clarify the commit title and description to provide more details on the change. `Refactor CleanupPointerRootUsers` makes it sound like there's no change in functionality, but IIUC this adds new functionality.

File: llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-loads.ll (hunk 2 above)
Comment (gandhi56) [reply llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-loads.ll:1]: https://github.com/llvm/llvm-project/pull/87443

**Comment by gandhi56** [comment]
Apologies for so many forced pushes, I was trying to rebase this PR against the precommit PR. I suppose I will wait for the precommit to merge and then I can rebase this patch.

**Comment by gandhi56** [comment]
ping @dtcxzyw

**Comment by gandhi56** [comment]
ping @fhahn

**Comment by gandhi56** [comment]
ping

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 3]
```diff
@@ -201,61 +201,54 @@ CleanupPointerRootUsers(GlobalVariable *GV,
...
+    } while (true);
+    I->eraseFromParent();
+  };
+
+  // Remove the store if it's value operand is a constant or a computation
+  // chain. If the value operand is a computation chain, determine if it is safe
+  // to remove it before removing the store. Remove both the store and the
+  // computation chain if it is safe to do so.
+  while (!Writes.empty()) {
+    auto *Write = Writes.pop_back_val();
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:238]: Can you use a simple for loop over Writes here? The pop_back_val doesn't seem necessary...

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 4]
```diff
@@ -201,61 +201,54 @@ CleanupPointerRootUsers(GlobalVariable *GV,
...
+    auto *V = Write->getOperand(0);
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:239]: This is going to be the stored value for stores, but the memory intrinsics this is going to be the destination pointer. I don't think applying the check to the destination pointer makes sense? For memset we should always allow removal, for memcpy it's tricky (what really matters is the contents of the copied memory there). But in any check there would have to be on the source pointer, not the destination pointer.

File: llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users-gep-constexpr.ll [hunk 5]
```diff
@@ -99,14 +99,14 @@ define i32 @load_gv_from_op_remove_store(ptr %p) local_unnamed_addr {
 ; CHECK-NEXT:    call void @fn0()
 ; CHECK-NEXT:    br label [[IF_END]]
 ; CHECK:       if.end:
-; CHECK-NEXT:    store ptr [[E]], ptr getelementptr inbounds ([3 x ptr], ptr @b, i64 0, i64 2), align 16
+; CHECK-NOT:     store ptr [[E]], ptr getelementptr inbounds ([3 x ptr], ptr @b, i64 0, i64 2), align 16
```
Comment (nikic) [inline llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users-gep-constexpr.ll:102]: Rerun update_test_checks instead of manually editing the file.

File: llvm/test/tools/llvm-ar/extract.test [hunk 6]
```diff
@@ -1,5 +1,4 @@
 ## Test extract operation.
-# XFAIL: system-darwin
```
Comment (nikic) [inline llvm/test/tools/llvm-ar/extract.test:2]: Unrelated changes?

**Comment by gandhi56** [comment]
All llvm tests pass according to my local testing.

File: llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users.ll [hunk 7]
```diff
@@ -12,7 +12,7 @@ define void @test1a() {
 
 define void @test1b(ptr %p) {
 ; CHECK-LABEL: @test1b(
-; CHECK-NEXT: store
+; CHECK-NOT: store
```
Comment (nikic) [inline llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users.ll:15]: This change looks incorrect to me: `%p` might be a malloc-ed pointer here, which would leak after the transform.

Comment (gandhi56) [reply llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users.ll:15]: So, in general, store instructions with a pointer as its value operand should not be removed?

Comment (nikic) [reply llvm/test/Transforms/GlobalOpt/cleanup-pointer-root-users.ll:15]: Not quite. The point of CleanupPointerRootUsers() is to remove assignments for which we know that the value is not dynamically allocated. So e.g. a store of a constant is fine, but a store of an unknown argument is not, because that argument could have come from malloc.

**Comment by gandhi56** [comment]
ping

**Comment by gandhi56** [comment]
ping

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 8]
```diff
@@ -158,12 +158,12 @@ static bool isLeakCheckerRoot(GlobalVariable *GV) {
...
 /// it's safe to remove the store and the chain of computation that feeds the
 /// store.
-static bool IsSafeComputationToRemove(
+static bool isSafeComputationToRemove(
     Value *V, function_ref<TargetLibraryInfo &(Function &)> GetTLI) {
   do {
     if (isa<Constant>(V))
       return true;
-    if (!V->hasOneUse())
+    if (V->getNumUses() > 0)
```
Comment (efriedma-quic) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:166]: hasNUsesOrMore

But also, we have RecursivelyDeleteTriviallyDeadInstructions if you just want to kill off dead computations.  The point of the old code was that it was trying to preserve stores of allocations with other non-trivial uses, which is why it was checking for exactly one use.

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 9]
```diff
@@ -202,60 +212,51 @@ CleanupPointerRootUsers(GlobalVariable *GV,
...
   bool Changed = false;
 
-  // If Dead[n].first is the only use of a malloc result, we can delete its
-  // chain of computation and the store to the global in Dead[n].second.
-  SmallVector<std::pair<Instruction *, Instruction *>, 32> Dead;
+  auto RemoveComputationChain = [&GetTLI](Instruction *I) {
+    do {
+      if (isAllocationFn(I, GetTLI))
+        break;
+      Instruction *J = dyn_cast<Instruction>(I->getOperand(0));
```
Comment (efriedma-quic) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:219]: Can this cast actually fail?  isSafeComputationToRemove is supposed to check for a series of single-operand operations leading to an allocation.

**Review by efriedma-quic — COMMENTED** [review]
With these changes, what's the difference between cleanupPointerRootUsers and CleanupConstantGlobalUsers?

**Comment by gandhi56** [comment]
> With these changes, what's the difference between cleanupPointerRootUsers and CleanupConstantGlobalUsers?

`CleanupConstantGlobalUsers` cleans up the trivial users of `GV`, whereas `cleanupPointerRootUsers` handles computation chains leading up to the pointer root `GV`. `cleanupPointerRootUsers` makes a call to `isSafeComputationToRemove` before removing the chain.

**Comment by gandhi56** [comment]
I might be able to merge the `cleanupPointerRootUsers` and `cleanupConstantGlobalUsers` if I perform checks properly. I will work on that and update this PR.

**Comment by gandhi56** [comment]
ping

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp [hunk 10]
```diff
@@ -318,11 +240,30 @@ static bool CleanupConstantGlobalUsers(GlobalVariable *GV,
...
+      if (getUnderlyingObject(MSI->getRawDest()) == GV)
+        EraseFromParent(MSI);
+    } else if (auto *MTI = dyn_cast<MemTransferInst>(U)) {
+      auto *Src = MTI->getRawSource();
+      auto *Dst = MTI->getRawDest();
+      if (getUnderlyingObject(Dst) != GV)
+        continue;
+      if (isa<Instruction, Operator>(Src)) {
+        EraseFromParent(MTI);
+        if (isSafeComputationToRemove(Src, GetTLI))
```
Comment (efriedma-quic) [inline llvm/lib/Transforms/IPO/GlobalOpt.cpp:264]: Is the isSafeComputationToRemove() call actually doing anything useful here?  Once you call EraseFromParent, the computation is dead; it doesn't really make any difference whether you clean up the dead instructions here, or let instcombine delete them later.

**Comment by efriedma-quic** [comment]
(I'm not exactly against killing off isLeakCheckerRoot, but last time we tried, it caused problems; see https://reviews.llvm.org/D69428 .)

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp (hunk 10 above)
Comment (gandhi56) [reply llvm/lib/Transforms/IPO/GlobalOpt.cpp:264]: The purpose of `isSafeComputationToRemove(..)` at this point is only if we want to remove the computation chain in globalopt. You're right, we could let instcombine handle the removal of the computation chain as we should in my opinion to avoid redundancy. @nikic I would like to hear your thoughts on this.

**Comment by gandhi56** [comment]
> (I'm not exactly against killing off isLeakCheckerRoot, but last time we tried, it caused problems; see https://reviews.llvm.org/D69428 .)

I could try building valgrind to see if there are any failures.

**Comment by gandhi56** [comment]
@efriedma-quic Is anyone familiar with how to run valgrind tests? Or any other comments on this PR?

File: llvm/lib/Transforms/IPO/GlobalOpt.cpp (hunk 10 above)
Comment (efriedma-quic) [reply llvm/lib/Transforms/IPO/GlobalOpt.cpp:266]: I was trying to say that you can just call RecursivelyDeleteTriviallyDeadInstructions without checking if the instruction is dead; it internally checks if the instruction is dead.

But more importantly, it means isSafeComputationToRemove isn't actually doing anything useful, so the end result is that this behaves identically to D69428.

**Review by efriedma-quic — COMMENTED** [review]
I think the testcase is just running a program that stores the result of a malloc to an internal global variable under valgrind.  I don't have any specific examples handy; maybe someone else does.

**Comment by gandhi56** [comment]
@efriedma-quic I took a second look through all the cleanup routines. `isLeakCheckerRoot(GV)` seems necessary to me even though it's rarely applicable. So I am thinking to keep `cleanupPointerRootUsers` and improve it to cover cases as such as in the issue #64680. This will also prevent any potential failures in valgrind tests.

**Comment by efriedma-quic** [comment]
Deleting stores where we can prove the stored value isn't a pointer to an allocation should be fine; it doesn't impact the controversial cases.  (But the current version of the patch is more aggressive, maybe by accident.)

**Comment by gandhi56** [comment]
> Deleting stores where we can prove the stored value isn't a pointer to an allocation should be fine; it doesn't impact the controversial cases. (But the current version of the patch is more aggressive, maybe by accident.)

Assuming GV is a pointer root which is never read from, the store instruction can be removed even if it's value operand is a pointer.

I think the logic implemented to decide whether or not source value operands should be removed was a little messy. Hence the test from #64680 was failing.

**Comment by gandhi56** [comment]
ping

**Comment by vitalybuka** [comment]
> ping

Assuming you are expecting @efriedma-quic reply,  don't forget "note" from https://llvm.org/docs/CodeReview.html#acknowledge-all-reviewer-feedback

**Comment by gandhi56** [comment]
ping

**Comment by gandhi56** [comment]
ping

**Comment by efriedma-quic** [comment]
If you patch isn't getting appropriate review, merging it is not an appropriate way to escalate.  Appropriate ways include privately emailing reviewers, or starting a thread on Discourse.

-----

I apologize for not continuing to review this in a timely fashion.  I should not have ignored the patch like this, after I started reviewing.

There are basically two ways forward for this patch: one, you preserve the "leak root" check so that allocation checking tools don't break.  Two, we explicitly decide to break any tools that depend on "leak root" checking (probably needs an RFC).  Your patch is currently doing neither one of those; it's still trying to straddle the middle in a way I can't understand.

**Comment by nikic** [comment]
FWIW, my opinion on what to do here is https://github.com/llvm/llvm-project/issues/109718#issuecomment-2370770969.
