### PR TITLE
[Flang][OpenMP] Update declare mapper lookup via use-module

### LINKED ISSUE #163385: [flang][OpenMP] Custom mapper not found and crashing compilation when used in different module than which it was defined in
When using a custom mapper outside of the module it was defined, it is not found and crashes the compilation. Below is a short reproducer for the issue:
```fortran
MODULE field_mod
    IMPLICIT NONE

    TYPE :: field_t
        REAL, ALLOCATABLE :: buf(:)
    END TYPE field_t
    !$omp declare mapper(custom: field_t :: t) map(t%buf)
END MODULE field_mod

PROGRAM reproducer
    USE field_mod

    IMPLICIT NONE

    REAL :: validation(5)
    TYPE(field_t) :: f_t
    ALLOCATE(f_t%buf(5))
    f_t%buf = 42.0

    !$omp target map(mapper(custom), tofrom: f_t) map(from: validation)
        validation(:) = f_t%buf(:)
    !$omp end target

    PRINT*, "Expected: 42. 42. 42. 42. 42."
    PRINT*, "Actual:", validation

    DEALLOCATE(f_t%buf)
END PROGRAM reproducer
```

Compiling this code (with cuda in my case) crashes...
```
flang -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-version=52 main.F90 -O3
```
...with the error message:
```
error: loc("f_t"("/home/jfuchs/reproducer/main.F90":18:22)): invalid mapper id
error: verification of lowering to FIR failed
```

We can cross check the correct behavior by moving the `!$omp declare mapper...` line below into the PROGRAM directly. Then compilation succeeds and the values are as expected after the target region.

I am using `flang version 22.0.0git (git@github.com:llvm/llvm-project.git a8057ff12956b7dd6dec44f9610c446c828c4af8)`.

### PR DESCRIPTION
**Pull request by TIFitis**
- Implemented semantic TODO to catch undeclared mappers.
- Fix mapper lookup to include modules imported through USE.
- Update and add tests.

Fixes #163385.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
I don't see changes to add support (in lib/Semantics/mod-file.cpp) for emitting the `declare mapper` directive in the module file (*.mod). How did you manage to get this to work without it?

**Comment by TIFitis** [comment]
@kiranchandramohan Sorry for the earlier misunderstanding — I’m not very familiar with the parsing/semantic side of things.

It was working without exporting to the .mod file because the test originally had both the module and the program in the same file. Once separated, it started failing.

I’ve now updated the PR to export the declare mapper to the .mod file as you suggested, and the lookup works correctly when compiling across different files. I’ve also updated the test accordingly.

As far as I’m aware, FIR/OMP does not emit dummy mappers at any stage.

File: flang/lib/Lower/OpenMP/OpenMP.cpp [hunk 1]
```diff
@@ -4239,3 +4255,32 @@ void Fortran::lower::genOpenMPRequires(mlir::Operation *mod,
...
+    if (auto *md = sym.detailsIf<semantics::MapperDetails>()) {
+      for (const auto *decl : md->GetDeclList()) {
+        if (const auto *mapperDecl =
+                std::get_if<parser::OpenMPDeclareMapperConstruct>(&decl->u)) {
+          genOpenMPDeclareMapperImpl(converter, semaCtx, *mapperDecl, &sym);
+        }
+      }
+    }
+  }
+}
```
Comment (kiranchandramohan) [inline flang/lib/Lower/OpenMP/OpenMP.cpp]: Do we still need this function? Can you check how threadprivate works and whether it needs this kind of handling?

Comment (TIFitis) [reply flang/lib/Lower/OpenMP/OpenMP.cpp]: Threadprivate directive is serialised into the .mod, and we don't need to lookup symbols by name. We need to lookup existing declare mappers in the module when they are referred to through mapper modifiers, as such, I think we need the `materializeOpenMPDeclareMappers` function.

Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP/OpenMP.cpp]: Do we need to recursively go through all the scopes? Or are only the declare mappers at the top-level needed?

Comment (TIFitis) [reply flang/lib/Lower/OpenMP/OpenMP.cpp]: I've reverted to the previous approach.

From what I understand, a function that comes in through a transitive USE is represented in the importing scope by a symbol whose details are `semantics::UseDetails`, pointing back to the defining symbol in the original module. When lowering sees a call, it follows that chain to the ultimate symbol in the source module, so the call is generated exactly as if the function were imported directly. No IR for the callee is emitted in the current compilation unit.

For declare mappers, we need to follow the chain and generate the IR. So we can either take the lazy approach, or we must go through the scopes to find any declare mappers that have brought in through USE modules and lower them.

The declare mappers don't seem to appear at the top-level.

**Review by kiranchandramohan — APPROVED** [review]
I will be away for atleast a week. This needs further review from @agozillon @skatrak or @kparzysz 

Approving to signal that I am not blocking the progress of the patch.

**Comment by TIFitis** [comment]
Ping for review.

**Review by kparzysz — APPROVED** [review]
This looks reasonable.  If some parts turn out to be unnecessary, we can remove them later.
