### PR TITLE
[clang][Sema] Fix type of an statement expression ending with an atomic type

### LINKED ISSUE #106576: Crash on code with StmtExpr and atomic char load in `Expr::EvaluateAsRValue`
The following example crashes `clang-16`, `clang-17` and `clang-18`:

```c
typedef _Atomic char atomic_char;

atomic_char counter;

char load_plus_one() {
  return ({counter;}) + 1;
}
```

See [on Compiler Explorer](https://godbolt.org/z/s6hxnY518).

The crash seems reproducible on release builds on Ubuntu 22 installed from apt.llvm.org, but I can't observe it on non-asserted builds on Compiler Explorer for some reason...

<details>
  <summary>Stack trace</summary>

```
$ clang-18 -fsyntax-only minimal.c
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang-18 -fsyntax-only minimal.c
1.	minimal.c:6:26: current parser token ';'
2.	minimal.c:5:22: parsing function body 'load_plus_one'
3.	minimal.c:5:22: in compound statement ('{}')
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-18.so.18.1   0x000079cec1794716 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 54
1  libLLVM-18.so.18.1   0x000079cec17926d0 llvm::sys::RunSignalHandlers() + 80
2  libLLVM-18.so.18.1   0x000079cec16e41f0
3  libc.so.6            0x000079cec0242520
4  libclang-cpp.so.18.1 0x000079cec90da059
5  libclang-cpp.so.18.1 0x000062b1379df1f8
clang-18: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Ubuntu clang version 18.1.8 (++20240731024944+3b5b5c1ec4a3-1~exp1~20240731145000.144)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-18: note: diagnostic msg: 
```
I am able to get a better stack trace on clang-16:
```
$ clang-16 -fsyntax-only minimal.c
*** stack smashing detected ***: terminated
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang-16 -fsyntax-only minimal.c
1.	minimal.c:6:26: current parser token ';'
2.	minimal.c:5:22: parsing function body 'load_plus_one'
3.	minimal.c:5:22: in compound statement ('{}')
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-16.so.1    0x0000794646bbec16 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 54
1  libLLVM-16.so.1    0x0000794646bbcdb0 llvm::sys::RunSignalHandlers() + 80
2  libLLVM-16.so.1    0x0000794646afd600
3  libc.so.6          0x0000794645442520
4  libc.so.6          0x00007946454969fc pthread_kill + 300
5  libc.so.6          0x0000794645442476 raise + 22
6  libc.so.6          0x00007946454287f3 abort + 211
7  libc.so.6          0x0000794645489676
8  libc.so.6          0x000079464553659a __fortify_fail + 42
9  libc.so.6          0x0000794645536566
10 libclang-cpp.so.16 0x000079464e2f1cde
11 libclang-cpp.so.16 0x000079464e2daf1b
12 libclang-cpp.so.16 0x000079464e2f1307
13 libclang-cpp.so.16 0x000079464e2af018
14 libclang-cpp.so.16 0x000079464e2d67a2
15 libclang-cpp.so.16 0x000079464e2af018
16 libclang-cpp.so.16 0x000079464e2acaf0
17 libclang-cpp.so.16 0x000079464e2a8bca clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&, bool) const + 602
18 libclang-cpp.so.16 0x000079464e7e5412
19 libclang-cpp.so.16 0x000079464e7e2255
20 libclang-cpp.so.16 0x000079464e7d6995
21 libclang-cpp.so.16 0x000079464e7d901f clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) + 207
22 libclang-cpp.so.16 0x000079464eb14604 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) + 324
23 libclang-cpp.so.16 0x000079464ecf0db5 clang::Sema::BuildReturnStmt(clang::SourceLocation, clang::Expr*, bool) + 2485
24 libclang-cpp.so.16 0x000079464ecf033e clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) + 94
25 libclang-cpp.so.16 0x000079464e0748b6 clang::Parser::ParseReturnStatement() + 326
26 libclang-cpp.so.16 0x000079464e06eee9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) + 2649
27 libclang-cpp.so.16 0x000079464e06e25d clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) + 349
28 libclang-cpp.so.16 0x000079464e0766f0 clang::Parser::ParseCompoundStatementBody(bool) + 1600
29 libclang-cpp.so.16 0x000079464e0777af clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) + 175
30 libclang-cpp.so.16 0x000079464e091910 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) + 3376
31 libclang-cpp.so.16 0x000079464dfe1832 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) + 4802
32 libclang-cpp.so.16 0x000079464e090a47 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) + 1031
33 libclang-cpp.so.16 0x000079464e090469 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) + 457
34 libclang-cpp.so.16 0x000079464e08f707 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) + 1943
35 libclang-cpp.so.16 0x000079464e08daae clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) + 1182
36 libclang-cpp.so.16 0x000079464dfcd75e clang::ParseAST(clang::Sema&, bool, bool) + 718
37 libclang-cpp.so.16 0x000079464fbe5565 clang::FrontendAction::Execute() + 85
38 libclang-cpp.so.16 0x000079464fb62754 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 724
39 libclang-cpp.so.16 0x000079464fc5dfe4 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 660
40 clang-16           0x000057ac82bf7f4c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 2348
41 clang-16           0x000057ac82bf51f0
42 libclang-cpp.so.16 0x000079464f83e9a2
43 libLLVM-16.so.1    0x0000794646afd39c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 140
44 libclang-cpp.so.16 0x000079464f83e0c3 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const + 355
45 libclang-cpp.so.16 0x000079464f809922 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const + 866
46 libclang-cpp.so.16 0x000079464f809b7e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const + 142
47 libclang-cpp.so.16 0x000079464f8242fd clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) + 349
48 clang-16           0x000057ac82bf48b5 clang_main(int, char**) + 11541
49 libc.so.6          0x0000794645429d90
50 libc.so.6          0x0000794645429e40 __libc_start_main + 128
51 clang-16           0x000057ac82bf1855 _start + 37
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Ubuntu clang version 16.0.6 (++20231112100510+7cbf1a259152-1~exp1~20231112100554.106)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: 
```
</details>

### PR DESCRIPTION
**Pull request by alejandro-alvarez-sonarsource**
When a statement expression's last statement is an atomic variable, GCC and Clang disagree on the type of the expression. This can be made apparent using `typeof` and forcing a diagnostic message:

```cpp
_Atomic int a = 0;
typeof(({a;})) x = "0";
```

* GCC complains about initializing `int` with `char*`
* Clang complains about initializing `_Atomic(int)` with a `char[2]`

Due to the type of the statement expression being deduced to be atomic, we end with three implicit casts inside the `StmtExpr` on the AST:

* `LValueToRValue` -> `AtomicToNonAtomic`  ->  `NonAtomicToAtomic`

In some situations, this can end on an assertion inside `IntExprEvaluator`, as reported in #106576.

With this patch, we now have two implicit casts, since the type of the statement expression is deduced to be non-atomic:

* `LValueToRValue` -> `AtomicToNonAtomic`

This is consistent with the C standard (6.7.2.4, p4)

>  The properties associated with atomic types are meaningful only for expressions that are lvalues.

But a statement expression is an rvalue.

`IntExprEvaluator` assumptions are now satisfied and there is no assertion error.
Additionally, the `typeof` trick mentioned above shows that the type is consistently deduced between GCC and Clang.

Fixes #106576

### CODE REVIEW

**Review by shafik — COMMENTED** [review]
This will eventually need a release note.

**Comment by alejandro-alvarez-sonarsource** [comment]
Ping?

**Review by shafik — COMMENTED** [review]
This looks about right to me but I would like another set of eyes.

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -15919,10 +15919,17 @@ ExprResult Sema::ActOnStmtExprResult(ExprResult ER) {
   if (Cast && Cast->getCastKind() == CK_ARCConsumeObject)
     return Cast->getSubExpr();
 
+  auto Ty = E->getType().getUnqualifiedType();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp:15922]: What I'm confused by is actually a few lines farther up. Why do we not want to do an lvalue-to-rvalue conversion when the result of the statement expression is an rvalue? That conversion would strip all the qualifiers, including the atomic ones, which seems like exactly the behavior we want.

That comment comes from https://github.com/llvm/llvm-project/commit/34376a68

CC @rjmccall in case you have some recollection here.

Comment (rjmccall) [reply clang/lib/Sema/SemaExpr.cpp:15922]: I believe it's because we're setting up for a PerformCopyInitialization below, so the l-value conversion would be redundant (or possibly slightly wrong for some C++ class types?). Certainly could be clearer in the comment.

As far as this patch goes, my longstanding thought is that `_Atomic` is clearly a qualifier. I know the C standard doesn't agree, but the C standard is wrong, the same way that it's wrong when it says that function references aren't l-values; sometimes the formal system has an obvious truth that doesn't align with the glossary. In this case, the language treats `_Atomic` as a qualifier for almost every purpose, and the compiler generally reflects that: most of the places that uniformly look through qualifiers also look through `_Atomic`, and most of the places that need to look specifically for `_Atomic` also need to look for certain qualifiers.

So my suggestion is that common functions like `getUnqualifiedType()` should just be looking through `_Atomic`, which would have fixed this bug before it happened. If there's a need for a narrower API that only looks through non-`_Atomic` qualifiers (or perhaps some subset of "non-ABI-affecting" qualifiers?), we can add that with a nice name that suggests when it should be used.

Comment (alejandro-alvarez-sonarsource) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > So my suggestion is that common functions like getUnqualifiedType() should just be looking through _Atomic, which would have fixed this bug before it happened. 

While I understand the reasoning, I am wary of touching a method that is used (roughly counted) over 400 times. Unfortunately, I do not currently have the bandwith to commit into carefully combing all of them.

Comment (AaronBallman) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > As far as this patch goes, my longstanding thought is that _Atomic is clearly a qualifier. 

Errrr, I don't agree. I think `_Atomic` is a type specifier. `_Atomic int` and `int` are not the same type (heck, they can even have different sizes and alignments!). It's somewhat like a qualifier in that it impacts how you access the underlying object (so in that regard, it is a bit like `volatile int` and `int`), but I think the fundamental thing is that you rarely want `int` semantics directly when the type is spelled `_Atomic int`.

> So my suggestion is that common functions like getUnqualifiedType() should just be looking through _Atomic, which would have fixed this bug before it happened. If there's a need for a narrower API that only looks through non-_Atomic qualifiers (or perhaps some subset of "non-ABI-affecting" qualifiers?), we can add that with a nice name that suggests when it should be used.

On the one hand, this specific bug has bitten us so many times I want to agree with your proposed approach.

On the other hand, that's going to be a massive undertaking that's pretty risky. We have times when we definitely *do not* want the qualified type to drop the atomic qualifier. For example, when merging function types, we call `getUnqualifiedType()` to determine whether two parameters are compatible. `void func(const int i);` and `void func(int i);` are compatible redeclarations, while `void func(_Atomic int i);` and `void func(int i);` are not. There are other times when we do want the atomic qualifier dropped. It's a frustrating mess and I'm certain we have numerous bugs in this area.

So the question to me becomes: do we fix this narrow issue and kick the can down the road? Or do we try to find someone willing to undergo the more significant cleanup?

Comment (rjmccall) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > > As far as this patch goes, my longstanding thought is that _Atomic is clearly a qualifier.
> 
> Errrr, I don't agree. I think `_Atomic` is a type specifier. `_Atomic int` and `int` are not the same type

`const int` and `int` are also not the same type.

> (heck, they can even have different sizes and alignments!).

Size and alignment is the (back-justified) reason we draw the line where we currently do. It is not a particularly sensible way to do it. Most of our existing qualifiers affect code generation and ABI, just in ways that happen to not affect size and alignment. Several qualifiers affect the ABI rules for containing aggregates, for example.

> It's somewhat like a qualifier in that it impacts how you access the underlying object (so in that regard, it is a bit like `volatile int` and `int`), but I think the fundamental thing is that you rarely want `int` semantics directly when the type is spelled `_Atomic int`.

I'm not quite sure what you're saying here. On the implementation level, the compiler can *never* ignore qualifiers when performing an access to an object; the whole point of qualifiers is that they affect the semantics of accesses. On the language design level, I agree with you that programmers should never perform normal accesses to `_Atomic` objects instead of using the intrinsics. However, that is an argument that it was an unfortunate language design decision that `_Atomic` behaves like a qualifier. In the language that we've actually got, `_Atomic` has most of the characteristics of qualifiers, and there is no benefit to the compiler implementation in pretending otherwise.

The common characteristics of qualifiers:
- They convey an aspect of how a value is stored or accessed other than the abstract value itself.
- They are typically disallowed or silently dropped at the top level in type contexts that primarily describe an abstract value rather than storage, such as casts, return values, and parameters (when determining the function type).
- R-value expressions represent an abstract value and are (for the most part) unqualified at the top level. Using a qualified l-value in a context that requires an r-value drops all qualifiers as part of the conversion to an r-value. The qualifiers typically affect the code-generation of the load.
- Assignment consumes an abstract value and therefore expects an r-value on the RHS, which (per above) is of unqualified type. The qualifier typically affects code-generation of the store.
- The qualifier (if it can apply to structs and unions at all) propagates along member accesses, such that the type of `x.member` has all the top-level qualifiers of both `x` and the member.

Most of these apply to `_Atomic`. The most notable exception is the last, which C makes UB. But it is not uncommon for qualifiers to have tweaks to various of these rules, like how C++ allows qualified return values of class type for some reason.

The subtyping rules around CV qualifiers in C++ are clearly a special case of the CV qualifiers and do not apply to anything else. (You can convert an `int**` to `const int * const *`, but you clearly cannot convert it to `__global const int * const *` — address space qualifiers are ABI-affecting in ways that make this infeasible to implement.)

> > So my suggestion is that common functions like getUnqualifiedType() should just be looking through _Atomic, which would have fixed this bug before it happened. If there's a need for a narrower API that only looks through non-_Atomic qualifiers (or perhaps some subset of "non-ABI-affecting" qualifiers?), we can add that with a nice name that suggests when it should be used.
> 
> On the one hand, this specific bug has bitten us so many times I want to agree with your proposed approach.
> 
> On the other hand, that's going to be a massive undertaking that's pretty risky.

Yeah, I don't disagree with this, and I'm not trying to force the problem to be solved immediately. I would like to try to get consensus on the right thing to do, though.

> We have times when we definitely _do not_ want the qualified type to drop the atomic qualifier. For example, when merging function types, we call `getUnqualifiedType()` to determine whether two parameters are compatible. `void func(const int i);` and `void func(int i);` are compatible redeclarations, while `void func(_Atomic int i);` and `void func(int i);` are not. There are other times when we do want the atomic qualifier dropped. It's a frustrating mess and I'm certain we have numerous bugs in this area.

In this case, I have to wonder if the standard is in the same place Clang is — if this was really an intentional allowance for `_Atomic T` as a parameter in function types or just an oversight. It's hard to imagine what an atomic argument could possibly mean. Perhaps it was an oversight that they no longer feel comfortable fixing.

> So the question to me becomes: do we fix this narrow issue and kick the can down the road? Or do we try to find someone willing to undergo the more significant cleanup?

If we agree that the compiler probably ought to be defaulting to treating atomic types as qualifiers, I think the path is:
1. Introduce a function that looks through `_Atomic` as well as the other qualifiers.
2. Make a best effort to switch existing call sites of `getUnqualifiedType()` that immediately also look through `_Atomic` to instead use the common function. Probably ought to be the same patch as (1).
3. Rework this patch to just use the new function.
4. Introduce a function that explicitly does not look through `_Atomic`.
5. Gradually go through the remaining `getUnqualifiedType()` uses and figure out which of the explicit functions they should use, adding tests as necessary.
6. When that's done, decide if we've got compelling evidence that `getUnqualifiedType()` should just default to looking through `_Atomic`.

I think asking Alejandro to do steps 1-3 as part of this bug fix is reasonable, and then the rest can be an open project.

Comment (AaronBallman) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > > > As far as this patch goes, my longstanding thought is that _Atomic is clearly a qualifier.
> > 
> > 
> > Errrr, I don't agree. I think `_Atomic` is a type specifier. `_Atomic int` and `int` are not the same type
> 
> `const int` and `int` are also not the same type.

Maybe I'm being imprecise, sorry for that. `const int` and `int` are both "morally" of type `int` in that the allowed accesses to either type will give the same code generation and behavior. There's no difference between read accesses to `int` and `const int`: https://godbolt.org/z/GzhKWr8W6

I think `int` and `_Atomic int` are not morally the same types; they have different behaviors due to the accesses: https://godbolt.org/z/xf8WEzaM5, they can have different sizes, they can have different alignments, etc.

I guess I view `int` vs `_Atomic int` being closer in behavior to `int` vs `long long int`.

> > (heck, they can even have different sizes and alignments!).
> 
> Size and alignment is the (back-justified) reason we draw the line where we currently do. It is not a particularly sensible way to do it. Most of our existing qualifiers affect code generation and ABI, just in ways that happen to not affect size and alignment. Several qualifiers affect the ABI rules for containing aggregates, for example.

Do you have an example of impacting the ABI rules in C?

> > It's somewhat like a qualifier in that it impacts how you access the underlying object (so in that regard, it is a bit like `volatile int` and `int`), but I think the fundamental thing is that you rarely want `int` semantics directly when the type is spelled `_Atomic int`.
> 
> I'm not quite sure what you're saying here.

Loading an int to get its value is a different operation than loading an atomic int to get its value; the latter may require entirely different instruction selection. Probably `int` is a bad example, perhaps `struct` values makes the distinction more clear?

> On the implementation level, the compiler can _never_ ignore qualifiers when performing an access to an object; the whole point of qualifiers is that they affect the semantics of accesses. On the language design level, I agree with you that programmers should never perform normal accesses to `_Atomic` objects instead of using the intrinsics. However, that is an argument that it was an unfortunate language design decision that `_Atomic` behaves like a qualifier. In the language that we've actually got, `_Atomic` has most of the characteristics of qualifiers, and there is no benefit to the compiler implementation in pretending otherwise.

Maybe I'm odd (it's known to happen), but I guess I view `_Atomic int` and `int` in C the same way as I view `std::atomic<int>` and `int` in C++. While there's a lot of similarities between how atomics work and how qualifiers work, I instinctively view them as completely separate types.

> The common characteristics of qualifiers:
> 
>     * They convey an aspect of how a value is stored or accessed other than the abstract value itself.

Agreed.

>     * They are typically disallowed or silently dropped at the top level in type contexts that primarily describe an abstract value rather than storage, such as casts, return values, and parameters (when determining the function type).

Agreed, at least sort of. Qualifiers on parameters and return types are deeply weird (IMO): https://godbolt.org/z/zxo3b9WK8

>     * R-value expressions represent an abstract value and are (for the most part) unqualified at the top level. Using a qualified l-value in a context that requires an r-value drops all qualifiers as part of the conversion to an r-value. The qualifiers typically affect the code-generation of the load.

Agreed.

>     * Assignment consumes an abstract value and therefore expects an r-value on the RHS, which (per above) is of unqualified type. The qualifier typically affects code-generation of the store.

Agreed.

>     * The qualifier (if it can apply to structs and unions at all) propagates along member accesses, such that the type of `x.member` has all the top-level qualifiers of both `x` and the member.

Agreed.

> Most of these apply to `_Atomic`. The most notable exception is the last, which C makes UB. But it is not uncommon for qualifiers to have tweaks to various of these rules, like how C++ allows qualified return values of class type for some reason.

Another notable exception is that `_Atomic` is not silently dropped at the top level in type for return values and parameters when determining the function type, as mentioned above.

> The subtyping rules for CV qualifiers — the ability to e.g. convert an `int**` to `const int * const *` — do not generally work for other qualifiers. For example, even just considering semi-standardized qualifiers, you clearly cannot add an address space in a nested position this way. I believe you have to understand this as a useful special case for the CV qualifiers. (It really should not work for `restrict`, although I can't remember what rule we actually implement.)

Agreed.

> > > So my suggestion is that common functions like getUnqualifiedType() should just be looking through _Atomic, which would have fixed this bug before it happened. If there's a need for a narrower API that only looks through non-_Atomic qualifiers (or perhaps some subset of "non-ABI-affecting" qualifiers?), we can add that with a nice name that suggests when it should be used.
> > 
> > 
> > On the one hand, this specific bug has bitten us so many times I want to agree with your proposed approach.
> > On the other hand, that's going to be a massive undertaking that's pretty risky.
> 
> Yeah, I don't disagree with this, and I'm not trying to force the problem to be solved immediately. I would like to try to get consensus on the right thing to do, though.

Agreed, and I appreciate the conversation on this!

> > We have times when we definitely _do not_ want the qualified type to drop the atomic qualifier. For example, when merging function types, we call `getUnqualifiedType()` to determine whether two parameters are compatible. `void func(const int i);` and `void func(int i);` are compatible redeclarations, while `void func(_Atomic int i);` and `void func(int i);` are not. There are other times when we do want the atomic qualifier dropped. It's a frustrating mess and I'm certain we have numerous bugs in this area.
> 
> In this case, I have to wonder if the standard is in the same place Clang is — if this was really an intentional allowance for `_Atomic T` as a parameter in function types or just an oversight. It's hard to imagine what an atomic argument could possibly mean. Perhaps it was an oversight that they no longer feel comfortable fixing.

Doesn't it matter in the same way it matters for `const` parameters: it impacts the accesses to the parameter within the function body itself? One contrived use case is:
```
thrd_t spawn_thread_to_do_things_to(_Atomic int *i);

void func(_Atomic int i) {
  thrd_t t = spawn_thread_to_do_things_to(&i);
  i = 12;
  thrd_join(t, NULL);
}
```

> > So the question to me becomes: do we fix this narrow issue and kick the can down the road? Or do we try to find someone willing to undergo the more significant cleanup?
> 
> If we agree that the compiler probably ought to be defaulting to treating atomic types as qualifiers, I think the path is:
> 
>     1. Introduce a function that looks through `_Atomic` as well as the other qualifiers.
> 
>     2. Make a best effort to switch existing call sites of `getUnqualifiedType()` that immediately also look through `_Atomic` to instead use the common function. Probably ought to be the same patch as (1).

I think we've already done this though. We have `getAtomicUnqualifiedType()` which we use when we want to get a non-atomic, unqualified type.

>     3. Rework this patch to just use the new function.
> 
>     4. Introduce a function that explicitly does not look through `_Atomic`.

Which is `getUnqualifiedType()` currently.

>     5. Gradually go through the remaining `getUnqualifiedType()` uses and figure out which of the explicit functions they should use, adding tests as necessary.
> 
>     6. When that's done, decide if we've got compelling evidence that `getUnqualifiedType()` should just default to looking through `_Atomic`.
> 
> 
> I think asking Alejandro to do steps 1-3 as part of this bug fix is reasonable, and then the rest can be an open project.

So I think what I'm getting is: we should audit all existing calls to `getUnqualifiedType()` and `getAtomicUnqualifiedType()` to determine whether we're correctly handling atomics or not, and if there are more uses of `getAtomicUnqualifiedType()` after correcting issues, then maybe we want `getUnqualifiedType()` to look through atomics and rename `getAtomicUnqualifiedType()` to something else?

Comment (rjmccall) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > > > > As far as this patch goes, my longstanding thought is that _Atomic is clearly a qualifier.
> > > 
> > > 
> > > Errrr, I don't agree. I think `_Atomic` is a type specifier. `_Atomic int` and `int` are not the same type
> > 
> > 
> > `const int` and `int` are also not the same type.
> 
> Maybe I'm being imprecise, sorry for that. `const int` and `int` are both "morally" of type `int` in that the allowed accesses to either type will give the same code generation and behavior. There's no difference between read accesses to `int` and `const int`: https://godbolt.org/z/GzhKWr8W6

That is mostly a special case of `const`. Even `volatile` requires code-gen differences, at least when generating a high-level IR subject to optimization.

> > > (heck, they can even have different sizes and alignments!).
> > 
> > Size and alignment is the (back-justified) reason we draw the line where we currently do. It is not a particularly sensible way to do it. Most of our existing qualifiers affect code generation and ABI, just in ways that happen to not affect size and alignment. Several qualifiers affect the ABI rules for containing aggregates, for example.
> 
> Do you have an example of impacting the ABI rules in C?

If you mean qualifiers officially blessed in any way by WG14, I believe that's just `const`, `volatile`, `restrict`, and the address-space qualifiers from TR 18037.  Address space qualifiers do affect ABI, but they don't specifically affect struct layout because they are not allowed on struct members.

> Loading an int to get its value is a different operation than loading an atomic int to get its value; the latter may require entirely different instruction selection. Probably `int` is a bad example, perhaps `struct` values makes the distinction more clear?

Needing different instruction selection is common for extended qualifiers. Even among the official qualifiers, address spaces typically require different instruction selection.

> Another notable exception is that `_Atomic` is not silently dropped at the top level in type for return values and parameters when determining the function type, as mentioned above.

It actually is dropped for return types; it's just parameters that are different.

> > In this case, I have to wonder if the standard is in the same place Clang is — if this was really an intentional allowance for `_Atomic T` as a parameter in function types or just an oversight. It's hard to imagine what an atomic argument could possibly mean. Perhaps it was an oversight that they no longer feel comfortable fixing.
> 
> Doesn't it matter in the same way it matters for `const` parameters: it impacts the accesses to the parameter within the function body itself?

Sure, but it is not in any way necessary for this to be part of the function type, just as it isn't part of the function type for `const`. The parameter is an independent object and has no relation to anything in the caller, so making the atomic-ness part of the signature is pointless.
> > If we agree that the compiler probably ought to be defaulting to treating atomic types as qualifiers, I think the path is:
> > ```
> > 1. Introduce a function that looks through `_Atomic` as well as the other qualifiers.
> > 
> > 2. Make a best effort to switch existing call sites of `getUnqualifiedType()` that immediately also look through `_Atomic` to instead use the common function. Probably ought to be the same patch as (1).
> > ```
> 
> I think we've already done this though. We have `getAtomicUnqualifiedType()` which we use when we want to get a non-atomic, unqualified type.
> 
> > ```
> > 3. Rework this patch to just use the new function.
> > 
> > 4. Introduce a function that explicitly does not look through `_Atomic`.
> > ```
> 
> Which is `getUnqualifiedType()` currently.

Right, it would have the same behavior as `getUnqualifiedType()` (and presumably would be implemented as a call to it). Making it a separate function lets you keep track of the fact that you considered a caller and deliberately did not want it to look through `_Atomic`, though.

> > I think asking Alejandro to do steps 1-3 as part of this bug fix is reasonable, and then the rest can be an open project.
> 
> So I think what I'm getting is: we should audit all existing calls to `getUnqualifiedType()` and `getAtomicUnqualifiedType()` to determine whether we're correctly handling atomics or not, and if there are more uses of `getAtomicUnqualifiedType()` after correcting issues, then maybe we want `getUnqualifiedType()` to look through atomics and rename `getAtomicUnqualifiedType()` to something else?

Right, with the tweak that the audit *always* switches away from `getUnqualifiedType()`: each call either becomes `getAtomicUnqualifiedType()` (I forgot that this already exists) or `getUnqualifiedTypePreservingAtomic()`, and then the audit is done when there are no remaining calls to `getUnqualifiedType()`. At that point, we decide if having a `getUnqualifiedType()` is a good idea or if we should just force all callers to explicitly choose.

And as mentioned, there's a short-term subset of the plan that unblocks this fix.

Comment (alejandro-alvarez-sonarsource) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > And as mentioned, there's a short-term subset of the plan that unblocks this fix.

Thanks for the feedback and for the enlightening discussion. I will go in this direction, but it will take me a while, since I have quite a few things on the backlog.

Comment (AaronBallman) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > Right, with the tweak that the audit always switches away from getUnqualifiedType(): each call either becomes getAtomicUnqualifiedType() (I forgot that this already exists) or getUnqualifiedTypePreservingAtomic(), and then the audit is done when there are no remaining calls to getUnqualifiedType(). At that point, we decide if having a getUnqualifiedType() is a good idea or if we should just force all callers to explicitly choose.

Okay, this is a plan I can get behind -- thank you for the good discussion!

Comment (rjmccall) [reply clang/lib/Sema/SemaExpr.cpp:15922]: > > And as mentioned, there's a short-term subset of the plan that unblocks this fix.
> 
> Thanks for the feedback and for the enlightening discussion. I will go in this direction, but it will take me a while, since I have quite a few things on the backlog.

Before you get too far into anything else, could you try just changing the call to `getUnqualifiedType()` to `getAtomicUnqualifiedType()` in the original code and seeing if that fixes the problem? That should be fine for the local, short-term fix.

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -163,6 +163,7 @@ Bug Fixes to C++ Support
 
 Bug Fixes to AST Handling
 ^^^^^^^^^^^^^^^^^^^^^^^^^
+- Fixed type deduction of an statement expression (a GCC extension) ending with an atomic type. (#GH106576)
```
Comment (rjmccall) [inline clang/docs/ReleaseNotes.rst:166]:
```suggestion
- Fixed type checking when a statement expression ends in an l-value of atomic type. (#GH106576)
```

File: clang/test/Sema/gh106576.c [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// RUN: %clang_cc1 -fsyntax-only -verify %s
+
+typedef _Atomic char atomic_char;
+
+typedef _Atomic char atomic_char;
```
Comment (rjmccall) [inline clang/test/Sema/gh106576.c:5]: Presumably the redundant typedef is not a critical part of this test.

Comment (alejandro-alvarez-sonarsource) [reply clang/test/Sema/gh106576.c]: It isn't, I have removed the duplicated line.

**Review by rjmccall — APPROVED** [review]
Thanks, LGTM.

**Comment by alejandro-alvarez-sonarsource** [comment]
Thanks! Do you mind doing the merge, since I can't?
