### PR TITLE
[Attributor][FIX] Replace AANoFPClass MBEC propagation

### LINKED ISSUE #78507: [Attributor] Incorrect optimization of math function when attributor module pass is run
The Attributor module pass currently optimized out this math function incorrectly to always return `NaN`. The reproducer is at https://godbolt.org/z/1P9xTjoab. When the attributor is not run, the function remains correct, when it's run it gets incorrectly removed.

### PR DESCRIPTION
**Pull request by jdoerfert**
The old must-be-executed-context (MBEC) propagation did propagate
through calls even if that was not allowed. We now only propagate from
call site arguments. If there are calls/intrinsics that allows
propagation, we need to add them explicitly.

Fixes: https://github.com/llvm/llvm-project/issues/78507

### CODE REVIEW

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp [hunk 1]
```diff
@@ -10332,47 +10332,26 @@ struct AANoFPClassImpl : AANoFPClass {
...
-      }
-    }
+    // TODO: Determine what instructions can be looked through.
+    auto *CB = dyn_cast<CallBase>(I);
+    if (!CB)
+      return false;
 
-    if (!UseV->getType()->isFPOrFPVectorTy())
+    if (!CB->isArgOperand(U))
       return false;
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10341]: An FP type / vector couldn't be the arg operand so is this condition even possible?

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp [hunk 2]
```diff
@@ -10332,47 +10332,26 @@ struct AANoFPClassImpl : AANoFPClass {
...
+      State.addKnownBits(NoFPAA->getState().getKnown());
+    return false;
   }
 
   const std::string getAsStr(Attributor *A) const override {
     std::string Result = "nofpclass";
     raw_string_ostream OS(Result);
+    OS << getKnownNoFPClass();
+    OS << "/";
     OS << getAssumedNoFPClass();
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10355]:
```suggestion
    OS << getKnownNoFPClass() << '/' << getAssumedNoFPClass();
```

File: llvm/test/Transforms/Attributor/nofpclass-frexp.ll [hunk 3]
```diff
@@ -27,8 +27,8 @@ define { float, i32 } @ret_frexp_f32_nonan(float nofpclass(nan) %arg0) {
 
 define float @ret_frexp_f32_0_nonan(float nofpclass(nan) %arg0) {
 ; CHECK-LABEL: define nofpclass(nan sub) float @ret_frexp_f32_0_nonan
-; CHECK-SAME: (float nofpclass(nan sub) [[ARG0:%.*]]) #[[ATTR1]] {
-; CHECK-NEXT:    [[CALL:%.*]] = call { float, i32 } @llvm.frexp.f32.i32(float [[ARG0]]) #[[ATTR7]]
+; CHECK-SAME: (float nofpclass(nan) [[ARG0:%.*]]) #[[ATTR1]] {
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: I think we still need the special case for frexp, this should still imply nofpclass(sub)

File: llvm/lib/Transforms/IPO/AttributorAttributes.cpp (hunk 1 above)
Comment (jdoerfert) [reply llvm/lib/Transforms/IPO/AttributorAttributes.cpp:10341]: Can be a operand bundle entry, I belive.

File: llvm/test/Transforms/Attributor/nofpclass-frexp.ll (hunk 3 above)
Comment (jdoerfert) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: What is the rule then?
This would work already if frexp had the proper argument attribute.

Comment (arsenm) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: You cannot apply the attribute to the return value because it's a struct, not an FP/FP vector. You have to specially recognize the extractvalue of the first element of the struct

Comment (jdoerfert) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: I don't get it. Extractvalue does not imply anything.
What you said first, or what I understood, is that frexp implies that the argument is `nofpclass(sub)`. Is that true? If so, I can implement that.

Comment (arsenm) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: The floating point component of the return value of frexp cannot be a denormal. The input could be anything. Because it returns a struct, anything you want to say about the frexp result has to be applied to the extractvalue user of frexp, not the frexp directly

Comment (jdoerfert) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: The test changed such that the argument of the function, the argument to frexp, is not assumed non-sub. What is the problem here?

Comment (arsenm) [reply llvm/test/Transforms/Attributor/nofpclass-frexp.ll:30]: > What is the problem here?

That I'm reading the argument attribute as the return

File: llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll [hunk 4]
```diff
@@ -0,0 +1,357 @@
...
+declare double @llvm.fabs.f64(double) #0
+
+; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare double @llvm.rint.f64(double) #0
+
+; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare double @llvm.amdgcn.trig.preop.f64(double, i32) #0
+
+; Function Attrs: alwaysinline mustprogress nofree norecurse nosync nounwind willreturn memory(none)
+define hidden double @sin(double noundef %__x) local_unnamed_addr #1 {
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll:30]:
```suggestion
define double @sin(double noundef %__x) #1 {
```

File: llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll [hunk 5]
```diff
@@ -0,0 +1,357 @@
...
+; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare double @llvm.fabs.f64(double) #0
+
+; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare double @llvm.rint.f64(double) #0
+
+; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare double @llvm.amdgcn.trig.preop.f64(double, i32) #0
+
+; Function Attrs: alwaysinline mustprogress nofree norecurse nosync nounwind willreturn memory(none)
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll:29]:
```suggestion
```

File: llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll [hunk 6]
```diff
@@ -0,0 +1,357 @@
...
+; CHECK-NEXT:    [[TMP137:%.*]] = bitcast <2 x i32> [[TMP136]] to double
+; CHECK-NEXT:    ret double [[TMP137]]
+;
+entry:
+  %0 = tail call double @llvm.fabs.f64(double %__x)
+  %1 = fcmp olt double %0, 0x41D0000000000000
+  br i1 %1, label %2, label %21
+
+2:                                                ; preds = %entry
+  %3 = fmul double %0, 0x3FE45F306DC9C883
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll:189]: Use named values, and presumably this can be reduced a lot?

File: llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll [hunk 7]
```diff
@@ -0,0 +1,357 @@
...
+}
+
+attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
+attributes #1 = { alwaysinline mustprogress nofree norecurse nosync nounwind willreturn memory(none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx1030" "target-features"="+16-bit-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx10-3-insts,+gfx10-insts,+gfx8-insts,+gfx9-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize32" }
+attributes #2 = { memory(none) }
+
+!opencl.ocl.version = !{!0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0}
+!llvm.ident = !{!1, !2, !1, !2, !1, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2, !1, !2}
+!llvm.module.flags = !{!3, !4, !5, !6, !7, !8, !9}
+!omp_offload.info = !{!10, !11, !12}
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll:343]: Drop all the metadata?

File: llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll [hunk 8]
```diff
@@ -0,0 +1,357 @@
...
+  %133 = xor i32 %132, %131
+  %134 = insertelement <2 x i32> %127, i32 %133, i64 1
+  %135 = fcmp one double %0, 0x7FF0000000000000
+  %136 = select i1 %135, <2 x i32> %134, <2 x i32> <i32 0, i32 2146959360>
+  %137 = bitcast <2 x i32> %136 to double
+  ret double %137
+}
+
+attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
+attributes #1 = { alwaysinline mustprogress nofree norecurse nosync nounwind willreturn memory(none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx1030" "target-features"="+16-bit-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx10-3-insts,+gfx10-insts,+gfx8-insts,+gfx9-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize32" }
```
Comment (arsenm) [inline llvm/test/Transforms/Attributor/reduced/nofpclass_78507.ll:337]: Drop all the target attributes

**Review by arsenm — COMMENTED** [review]
lgtm with test cleaned up
