### PR TITLE
[ValueTracking] Implement sdiv/udiv support for isKnownNonNullFromDominatingCondition

### LINKED ISSUE #64240: Missed optimization: failure to use div-by-zero UB to delete redundant select
Given this function:

```ll
define i64 @incorrect_safe_div(i64 %n, i64 %d) {
  %1 = icmp eq i64 %d, 0
  %2 = udiv i64 %n, %d
  %3 = select i1 %1, i64 -1, i64 %2
  ret i64 %3
}
```

LLVM does not seem to notice that this `select` is unconditional, because `%2` should imply that `%d != 0` in the entire block, and therefore `%1` can be replaced with `false`. Alive2 confirms this optimization is valid: https://alive2.llvm.org/ce/z/7nLDRe.

### PR DESCRIPTION
**Pull request by dc03**
The second operand of a sdiv/udiv has to be non-null, as division by zero is UB.

Proofs: https://alive2.llvm.org/ce/z/WttZbb

Fixes https://github.com/llvm/llvm-project/issues/64240.

### CODE REVIEW

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -2263,6 +2263,12 @@ static bool isKnownNonNullFromDominatingCondition(const Value *V,
         return true;
     }
 
+    if (const auto *Div = dyn_cast<BinaryOperator>(U);
+        Div && Div->getOpcode() == BinaryOperator::UDiv &&
+        Div->getOperand(1) == V &&
```
Comment (dtcxzyw) [inline llvm/lib/Analysis/ValueTracking.cpp:2268]:
```suggestion
    if (match(U, m_UDiv(m_Value(), m_Specific(V)) &&
```

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 2]
```diff
@@ -2263,6 +2263,12 @@ static bool isKnownNonNullFromDominatingCondition(const Value *V,
...
+        isValidAssumeForContext(cast<Instruction>(U), CtxI, DT))
```
Comment (dtcxzyw) [inline llvm/lib/Analysis/ValueTracking.cpp:2269]: `isValidAssumeForContext` assumes the first argument is an assume intrinsic. It is incorrect to pass a udiv.

Comment (dc03) [reply llvm/lib/Analysis/ValueTracking.cpp:2269]: Hmm, I am not sure of any other way to check for post-dominance.

Comment (dtcxzyw) [reply llvm/lib/Analysis/ValueTracking.cpp:2267]: Maybe `DT->dominates(cast<Instruction>(U), CtxI)`? It guarantees we execute `udiv` before `select`. Then we can simplify the pattern in `simplifySelectWithICmpCond`.

Comment (dc03) [reply llvm/lib/Analysis/ValueTracking.cpp:2267]: In this case, `CtxI` is always the `icmp`, so the `dominates` call will only work when the `icmp` dominates the `udiv` and not the other way round.

Comment (nikic) [reply llvm/lib/Analysis/ValueTracking.cpp:2267]: isValidAssumeForContext() should be fine to use for non-assumes as well. The key property of assumes here is that violating the fact results in immediate undefined behavior, which is also true for divisions.

Though I guess the isEphemeralValueOf() part of the function is only relevant for assumes...

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 3]
```diff
@@ -2263,6 +2263,11 @@ static bool isKnownNonNullFromDominatingCondition(const Value *V,
         return true;
     }
 
+    if ((match(U, m_UDiv(m_Value(), m_Specific(V))) ||
+         match(U, m_SDiv(m_Value(), m_Specific(V)))) &&
```
Comment (dtcxzyw) [inline llvm/lib/Analysis/ValueTracking.cpp:2267]:
```suggestion
    if (match(U, m_IDiv(m_Value(), m_Specific(V))) &&
```

**Comment by dc03** [comment]
Is this a problem?
```diff
diff --git a/llvm/test/Transforms/InstCombine/sdiv-guard.ll b/llvm/test/Transforms/InstCombine/sdiv-guard.ll
index ba9670924108..4894ed90e359 100644
--- a/llvm/test/Transforms/InstCombine/sdiv-guard.ll
+++ b/llvm/test/Transforms/InstCombine/sdiv-guard.ll
@@ -6,9 +6,7 @@ declare void @llvm.experimental.guard(i1, ...)
 ; Regression test. If %flag is false then %s == 0 and guard should be triggered.
 define i32 @a(i1 %flag, i32 %X) nounwind readnone {
 ; CHECK-LABEL: @a(
-; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[X:%.*]], 0
-; CHECK-NEXT:    call void (i1, ...) @llvm.experimental.guard(i1 [[CMP]]) #[[ATTR2:[0-9]+]] [ "deopt"() ]
-; CHECK-NEXT:    [[R:%.*]] = sdiv i32 100, [[X]]
+; CHECK-NEXT:    [[R:%.*]] = sdiv i32 100, [[X:%.*]]
 ; CHECK-NEXT:    ret i32 [[R]]
 ;
   %s = select i1 %flag, i32 %X, i32 0
```

**Comment by nikic** [comment]
@dc03 Yeah, that definitely should not be happening...

**Comment by nikic** [comment]
This is a mistake in the test case, I've put up https://github.com/llvm/llvm-project/pull/67641 to fix it.

**Comment by nikic** [comment]
https://github.com/llvm/llvm-project/pull/69433 has been merged, so that should fix the sdiv-guard.ll test case.

File: llvm/lib/Analysis/ValueTracking.cpp (hunk 3 above)
Comment (dc03) [reply llvm/lib/Analysis/ValueTracking.cpp]: @dtcxzyw I think its fine to keep this PR to just IDiv (I'm mainly interested in closing the issue), the others can be implemented separately.

**Review by nikic — APPROVED** [review]
LGTM
