### PR TITLE
[KnownBits] Remove `hasConflict()` assertions

### LINKED ISSUE #94436: [KnownBits] Remove hasConflict() assertions
The KnownBits infrastructure currently has pervasive !hasConflict() assertions, which ensure that KnownBits don't claim that a bit is both zero *and* one at the same time. However, these kinds of conflicts can naturally arise whenever the value is known to be poison. At this point, these assertions no longer provide value and just result in a steady stream of compiler crashes.

We should remove these assertions. Once that is done, we may also make use of conflicting KnownBits to fold values to poison.

### PR DESCRIPTION
**Pull request by c8ef**
close: #94436

### CODE REVIEW

**Comment by nikic** [comment]
These assertions are not just in KnownBits.h, but also spread across many other places. Basically do a `git grep "hasConflict()"` (There are currently 88 occurrences, though not all of them are in assertions.)

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -1158,7 +1158,6 @@ static void computeKnownBitsFromOperator(const Operator *I,
           Known.makeNonNegative();
       }
 
-      assert(!Known.hasConflict() && "Bits known to be one AND zero?");
```
Comment (nikic) [inline llvm/lib/Analysis/ValueTracking.cpp:1161]: Can you please also drop this one? https://github.com/llvm/llvm-project/blob/5878f2421c3d313758e50389f4854d26c7f4867c/llvm/lib/Analysis/ValueTracking.cpp#L2058 It's also a conflict assertion just written differently.

File: llvm/lib/IR/ConstantRange.cpp [hunk 2]
```diff
@@ -58,8 +58,6 @@ ConstantRange::ConstantRange(APInt L, APInt U)
 
 ConstantRange ConstantRange::fromKnownBits(const KnownBits &Known,
                                            bool IsSigned) {
-  assert(!Known.hasConflict() && "Expected valid KnownBits");
```
Comment (nikic) [inline llvm/lib/IR/ConstantRange.cpp:61]: I think in this case it would be better to change this to:
```
if (Known.hasConflict())
  return getEmpty(Known.getBitWidth());
```

**Comment by nikic** [comment]
There are more checks in KnownBitsTest, but I guess we can drop those in a second step, when removing the various `if (!hasConflict()) setAllZero();` bits.

**Comment by nikic** [comment]
Though one testing-related change we should do is drop this check: https://github.com/llvm/llvm-project/blob/574ab7e7b759a400ecf54c1141b1433bb2415e93/llvm/unittests/Support/KnownBitsTest.h#L29 This means the KnownBits implementation will actually get tested with conflict values, so we can be sure this doesn't produce unexpected crashes somewhere.

**Comment by jayfoad** [comment]
I expect you would have to make some changes like this, since even the supposedly optimal KnownBits implementations do not always report conflict when they should:
```diff
diff --git a/llvm/unittests/Support/KnownBitsTest.cpp b/llvm/unittests/Support/KnownBitsTest.cpp
index 824cf7501fd4..acec5dbfb4e6 100644
--- a/llvm/unittests/Support/KnownBitsTest.cpp
+++ b/llvm/unittests/Support/KnownBitsTest.cpp
@@ -95,9 +95,10 @@ static void testBinaryOpExhaustive(StringRef Name, BinaryBitsFn BitsFn,
           });
         });
 
-        EXPECT_TRUE(!Computed.hasConflict());
-        EXPECT_TRUE(checkResult(Name, Exact, Computed, {Known1, Known2},
-                                CheckOptimality));
+        if (!Exact.hasConflict()) {
+          EXPECT_TRUE(checkResult(Name, Exact, Computed, {Known1, Known2},
+                                  CheckOptimality));
+        }
         // In some cases we choose to return zero if the result is always
         // poison.
         if (RefinePoisonToZero && Exact.hasConflict()) {
```

**Comment by nikic** [comment]
@c8ef Yeah, you should drop that assert.

File: llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp [hunk 3]
```diff
@@ -4212,7 +4212,6 @@ KnownBits SelectionDAG::computeKnownBits(SDValue Op, const APInt &DemandedElts,
     break;
   }
 
-  assert(!Known.hasConflict() && "Bits known to be one AND zero?");
```
Comment (RKSimon) [inline llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:4215]: Maybe just focus on the middle-end initially and then look at removing the DAG/GlobalISel assertions later?

Comment (nikic) [reply llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:4215]: I feel like it's safer to get rid of it everyone at once.

File: llvm/unittests/Support/KnownBitsTest.cpp [hunk 4]
```diff
@@ -726,6 +741,9 @@ TEST(KnownBitsTest, SExtInReg) {
   unsigned Bits = 4;
   for (unsigned FromBits = 1; FromBits <= Bits; ++FromBits) {
     ForeachKnownBits(Bits, [&](const KnownBits &Known) {
+      if (Known.hasConflict())
+        return;
```
Comment (nikic) [inline llvm/unittests/Support/KnownBitsTest.cpp:745]: I think it would be slightly better to move this check until after the Known.sextInReg() call (and also something similar for the other tests). Basically still call the KnownBits helper to make sure it doesn't assert, but don't check what the result will be, as it could be anything.

**Comment by nikic** [comment]
There are some test failures in pre-commit CI:
```
  LLVM :: Analysis/ScalarEvolution/ashr.ll
  LLVM :: Analysis/ScalarEvolution/pr76234.ll
  LLVM :: CodeGen/AArch64/GlobalISel/form-bitfield-extract-from-sextinreg.mir
  LLVM :: CodeGen/AMDGPU/ds-sub-offset.ll
  LLVM :: Transforms/InstCombine/select-obo-peo-ops.ll
  LLVM :: Transforms/LoopStrengthReduce/lsr-term-fold-negative-testcase.ll
  LLVM-Unit :: Analysis/./AnalysisTests.exe/ValueTrackingTest/ComputeNumSignBits_PR32045
  LLVM-Unit :: IR/./IRTests.exe/DemandedBitsTest/Add
  LLVM-Unit :: IR/./IRTests.exe/DemandedBitsTest/Sub
```
I think most of these are due to the various `if (!Known.hasConflict()) Known.setAllZero();` check that you dropped. You could either adjust the test expectations, or leave dropping these checks for a later patch, so that this one can be NFC (no functional change).

**Comment by jayfoad** [comment]
> or leave dropping these checks for a later patch, so that this one can be NFC

I would prefer making this an NFC patch that just drops assertions.

File: llvm/lib/Support/KnownBits.cpp [hunk 5]
```diff
@@ -1011,21 +971,16 @@ KnownBits KnownBits::sdiv(const KnownBits &LHS, const KnownBits &RHS,
...
                           bool Exact) {
   unsigned BitWidth = LHS.getBitWidth();
-  assert(!LHS.hasConflict() && !RHS.hasConflict());
   KnownBits Known(BitWidth);
 
   if (LHS.isZero() || RHS.isZero()) {
-    // Result is either known Zero or UB. Return Zero either way.
-    // Checking this earlier saves us a lot of special cases later on.
-    Known.setAllZero();
+    // Result is either known Zero or UB.
```
Comment (nikic) [inline llvm/lib/Support/KnownBits.cpp:983]: This setAllZero() call should be retained. Otherwise we would now provide a worse result if the LHS is zero. (It would go from result zero to result unknown).

File: llvm/lib/Support/KnownBits.cpp [hunk 6]
```diff
@@ -403,8 +391,7 @@ KnownBits KnownBits::lshr(const KnownBits &LHS, const KnownBits &RHS,
   if (Exact) {
     unsigned FirstOne = LHS.countMaxTrailingZeros();
     if (FirstOne < MinShiftAmount) {
-      // Always poison. Return zero because we don't like returning conflict.
-      Known.setAllZero();
+      // Always poison.
```
Comment (nikic) [inline llvm/lib/Support/KnownBits.cpp:394]: Similar here and in the ashr implementation. We go from returning zero to returning unknown, which is responsible for the regressions in SCEV tests where we go from range `[0, 1)` to `full-set`.

The correct replacement would be something like setConflict(), but given that we don't have that yet and wouldn't be able to make use of it for folding I think it's best to leave these cases alone.

**Review by nikic — COMMENTED** [review]
This looks mostly good to me, but I think some of the setAllZeros() removals should be undone.

File: llvm/lib/Support/KnownBits.cpp [hunk 7]
```diff
@@ -448,8 +433,7 @@ KnownBits KnownBits::ashr(const KnownBits &LHS, const KnownBits &RHS,
     MinShiftAmount = 1;
   if (LHS.isUnknown()) {
     if (MinShiftAmount == BitWidth) {
-      // Always poison. Return zero because we don't like returning conflict.
-      Known.setAllZero();
+      // Always poison.
```
Comment (nikic) [inline llvm/lib/Support/KnownBits.cpp:436]: This one, and the next one as well.

File: llvm/lib/Support/KnownBits.cpp (hunk 6 above)
Comment (nikic) [reply llvm/lib/Support/KnownBits.cpp]: Hm, I see. In that case I think it would be best to just revert *all* the setAllZero() related changes. We will have to update consuming code first so it can do something useful with conflict values before we start generating them.

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/unittests/Support/KnownBitsTest.cpp [hunk 8]
```diff
@@ -68,16 +68,16 @@ static void testUnaryOpExhaustive(StringRef Name, UnaryBitsFn BitsFn,
...
+        EXPECT_TRUE(checkResult(Name, Exact, Computed, Known, CheckOptimality));
+      }
     });
   }
 }
 
 static void testBinaryOpExhaustive(StringRef Name, BinaryBitsFn BitsFn,
                                    BinaryIntFn IntFn,
-                                   bool CheckOptimality = true,
-                                   bool RefinePoisonToZero = false) {
```
Comment (jayfoad) [inline llvm/unittests/Support/KnownBitsTest.cpp:80]: Should restore this RefinePoisonToZero stuff, since you have restored all the "if conflict return zero" cases.

File: llvm/unittests/Support/KnownBitsTest.cpp [hunk 9]
```diff
@@ -653,8 +656,10 @@ TEST(KnownBitsTest, GetMinMaxVal) {
       Min = APIntOps::umin(Min, N);
       Max = APIntOps::umax(Max, N);
     });
-    EXPECT_EQ(Min, Known.getMinValue());
-    EXPECT_EQ(Max, Known.getMaxValue());
+    if (!Known.hasConflict()) {
```
Comment (jayfoad) [inline llvm/unittests/Support/KnownBitsTest.cpp:659]: If there's a conflict you could immediately "continue" at the top of the loop to save some time. Same in the next three functions below.

File: llvm/unittests/Support/KnownBitsTest.cpp [hunk 10]
```diff
@@ -752,8 +765,10 @@ TEST(KnownBitsTest, CommonBitsSet) {
           HasCommonBitsSet |= N1.intersects(N2);
         });
       });
-      EXPECT_EQ(!HasCommonBitsSet,
-                KnownBits::haveNoCommonBitsSet(Known1, Known2));
+      if (!Known1.hasConflict() && !Known2.hasConflict()) {
```
Comment (jayfoad) [inline llvm/unittests/Support/KnownBitsTest.cpp:768]: Same here.

Comment (jayfoad) [reply llvm/unittests/Support/KnownBitsTest.cpp:768]: I meant that you could save some time here by testing for conflict as the first thing in the loop body, before the nested ForeachNumInKnownBits loops.

File: llvm/unittests/Support/KnownBitsTest.cpp (hunk 9 above)
Comment (jayfoad) [reply llvm/unittests/Support/KnownBitsTest.cpp:659]: But in this case you are not calling `Known.anything()` before checking for conflict and bailing out!

Comment (nikic) [reply llvm/unittests/Support/KnownBitsTest.cpp:659]: Hm, yes, I guess we should store Known.getMinValue() etc in a variable first, before the check. Or do people think there is not much value in checking all the functions with conflict inputs?

Comment (jayfoad) [reply llvm/unittests/Support/KnownBitsTest.cpp:659]: > Or do people think there is not much value in checking all the functions with conflict inputs?

I'm not sure how much value there is right now.

At some point we should check that KnownBits functions return conflict when they ought to, and part of that would definitely involve testing them on conflict inputs.

Comment (nikic) [reply llvm/unittests/Support/KnownBitsTest.cpp:659]: These particular APIs don't return KnownBits, so they don't really have any specific behavior they should exhibit for conflict inputs beyond "don't assert".
