### PR TITLE
[HLSL] Implement min and max overloads using templates

### LINKED ISSUE #131170: [HLSL] Add additional `min` and `max` overloads to enable compiling DML shaders
Currently clang fails to resolve cases where mixed vector and scalar types are used as arguments to 'min' and 'max'.
Cases such as:
```
float4 min(float4 p0, int p1) { return min(p0, (float4) p1); }
```

### PR DESCRIPTION
**Pull request by spall**
Replace min and max overload implementation using macros with one using templates.
Enable overloads of the forms:
 vector<T,N> min/max(vector<T,N> p0, T p1)
 vector<T,N> min/max(T p0, vector<T,N> p1)
 Add new tests.
Closes #131170

### CODE REVIEW

**Review by bob80905 — APPROVED** [review]
LGTM! Unfortunate about the macros not working out but this alternative is pretty convenient.

**Comment by spall** [comment]
> LGTM! Unfortunate about the macros not working out but this alternative is pretty convenient.

They would have worked if we didn't need even more overloads!

File: clang/lib/Headers/hlsl/hlsl_compat_overloads.h [hunk 1]
```diff
@@ -54,5 +54,67 @@ clamp(U p0, V p1, W p2) {
...
+template <typename T, typename U, uint N>
+constexpr __detail::enable_if_t<
+    __detail::is_arithmetic<U>::Value && (N > 1 && N <= 4), vector<T, N>>
+max(U p0, vector<T, N> p1) {
+  return max((vector<T, N>)p0, p1);
+}
+
+template <typename T, typename R, uint N>
+constexpr __detail::enable_if_t<(N > 1 && N <= 4), vector<T, N>>
+max(vector<T, N> p0, vector<R, N> p1) {
```
Comment (llvm-beanz) [inline clang/lib/Headers/hlsl/hlsl_compat_overloads.h:77]: I think this overload is a compatibility problem. It is better to error than to cause different behavior.
```hlsl
export float4 fn(int4 I, float4 F) {
    return max(I, F); // calls max(float4, float4)
}
```
see: https://hlsl.godbolt.org/z/xWPfza7d4

**Review by farzonl — APPROVED** [review]

File: clang/lib/Headers/hlsl/hlsl_compat_overloads.h (hunk 1 above)
Comment (spall) [reply clang/lib/Headers/hlsl/hlsl_compat_overloads.h:77]: Is this only a problem for max or is it also a problem for min? If I remove the min overload the DML shaders still error.

File: clang/lib/Headers/hlsl/hlsl_compat_overloads.h [hunk 2]
```diff
@@ -54,5 +54,55 @@ clamp(U p0, V p1, W p2) {
...
+constexpr __detail::enable_if_t<
+    __detail::is_arithmetic<U>::Value && (N > 1 && N <= 4), vector<T, N>>
+max(U p0, vector<T, N> p1) {
+  return max((vector<T, N>)p0, p1);
+}
+
+template <typename U, typename V>
+constexpr __detail::enable_if_t<
+    __detail::is_arithmetic<U>::Value && __detail::is_arithmetic<V>::Value, U>
+max(U p0, V p1) {
```
Comment (llvm-beanz) [inline clang/lib/Headers/hlsl/hlsl_compat_overloads.h:78]: This one is also problematic. DXC will not convert the second argument to the first type every time, it will prefer an int->float conversion over a float->int.

**Review by llvm-beanz — APPROVED** [review]
