### PR TITLE
[Clang][Sema] Fix issue on requires expression with templated base class member function

### LINKED ISSUE #84020: Compiler error for requires expression with templated base class member function
The following code fails to compile with clang trunk and clang 16  (See godbolt link).
The templated member function is not found by clang and therefore the `static_assert` is triggered.

The struct `A` inherits from `T` and therefore the base class member function `foo` exists, thus the `static_assert` should not trigger.
It works for non-templated base class member functions though.

```cpp
struct B {
    template <typename S>
    void foo();

    void bar();
};

template <typename T, typename S>
struct A : T {
    auto foo() {
        static_assert(requires { T::template foo<S>(); });  // fails with clang
        static_assert(requires { T::bar(); });  // works with clang and gcc 12.2
    }
};

int main() {
    A<B, double> a;
    a.foo();
}
```
[Godbolt](https://godbolt.org/z/5Ks5Kj1G8)

### PR DESCRIPTION
**Pull request by jcsxky**
Fix https://github.com/llvm/llvm-project/issues/84020
Skip checking implicit object parameter in the context of `RequiresExprBodyDecl`.

### CODE REVIEW

**Comment by jcsxky** [comment]
> Please add a more useful PR description, since that's useful for reviewers and ends up in the git log.

Thanks for your remind! I am waiting for CI to finish and after that I will add the description. Maybe mark it with draft would be better.

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -7735,7 +7735,8 @@ ExprResult Sema::BuildResolvedCallExpr(Expr *Fn, NamedDecl *NDecl,
   }
 
   if (CXXMethodDecl *Method = dyn_cast_or_null<CXXMethodDecl>(FDecl))
-    if (Method->isImplicitObjectMemberFunction())
+    if (!isa<RequiresExprBodyDecl>(CurContext) &&
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp:7738]: I don't really understand the change, can you better explain why this is the solution here?

Comment (jcsxky) [reply clang/lib/Sema/SemaExpr.cpp:7738]: In require body, name resolving just lookup function name and don't check function parameter without function call(I think).
```cpp
struct B {
    template <typename S>
    void foo(int);

    void bar();
};

template <typename T, typename S>
struct A : T {
    auto foo() {
        static_assert(requires { T::template foo<S>(); });
        static_assert(requires { T::bar(); });
    }
};

int main() {
    A<B, double> a;
    //a.foo(0);
}
```
After add a parameter to `foo`, this code also compiles correctly without calling.

Comment (erichkeane) [reply clang/lib/Sema/SemaExpr.cpp:7738]: I guess I don't see how 'implicit object member function' is what we want there?  It seems what we really want is 'in the context of a requires clause', right?

Comment (jcsxky) [reply clang/lib/Sema/SemaExpr.cpp:7738]: @erichkeane I am still feeling that we have no need to check whether the method has a explicit object parameter in require clause. In type requirement, checking nested member is enough(name resolution and parameter checking has already completed) and we don't need object argument since it isn't a function call.
```cpp
struct S {
  void foo() {}
};
void bar() {
  S::foo(); // need object parameter
  foo();    // name resolution failed
```
It is only doing a function call that object parameter is required.

Comment (erichkeane) [reply clang/lib/Sema/SemaExpr.cpp:7738]: I still dont think 'implictObjectMemberFunction' is the right thing here.  Why does the fact that it is not a 'Explit Object Member Function' matter?  

like:
```
struct S {
void foo(this S){}
};
void bar() {
S::foo();
};
```
??

Or static member functions?  This solution just doesn't seem right to me, and your responses dont' make it more clear.

Comment (jcsxky) [reply clang/lib/Sema/SemaExpr.cpp:7738]: Do you mean that checking whether `Method` is an implicit object function is redundant? After I removed https://github.com/llvm/llvm-project/blob/844b532713986999aa1ffed0883eff2d1339ec7a/clang/lib/Sema/SemaExpr.cpp#L7723-L7726
These testcase failed

https://github.com/llvm/llvm-project/blob/844b532713986999aa1ffed0883eff2d1339ec7a/clang/test/CXX/drs/dr3xx.cpp#L1084-L1095
https://github.com/llvm/llvm-project/blob/844b532713986999aa1ffed0883eff2d1339ec7a/clang/test/SemaTemplate/instantiate-using-decl.cpp#L150-L168
with no diagnose. Or the checking shouldn't be placed at current position?

Comment (jcsxky) [reply clang/lib/Sema/SemaExpr.cpp:7738]: And if only checking whether `Method` is a static method, we failed on:
https://github.com/llvm/llvm-project/blob/ef9446bd2d362ec90cd681ae59463d16bf671fe8/clang/test/CXX/drs/dr26xx.cpp#L225-L240

**Review by erichkeane — APPROVED** [review]
Ah, I had missed (thanks github review tool!) that the 'ImplicitObjectMember' part already existed.  Sorry for that.

**Comment by jcsxky** [comment]
> Ah, I had missed (thanks github review tool!) that the 'ImplicitObjectMember' part already existed. Sorry for that.

Never mind! Partly because I didn't make it more clear due to my poor expression .
