### PR TITLE
[Clang] use parameter location for abbreviated function templates

### LINKED ISSUE #46386: Abbreviated function template in `extern "C"` block generates error with bad location
|  |  |
| --- | --- |
| Bugzilla Link | [47042](https://llvm.org/bz47042) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
When producing an error message about an abbreviated function template appearing in an `extern "C"` block, Clang does not appear to have a proper diagnostic location to refer to (notice the first line of the actual output listed below).

Note: The error message itself appears to stem from words in [temp.pre] that prohibit C language linkage for templates, although [dcl.link] doesn't apply C language linkage to templates in the first place.

Compiler Explorer link: https://godbolt.org/z/GPcoMe

### SOURCE (<stdin>):
```cpp
extern "C" {
  void g(auto) {}
  void g(void) { g(42); }
}
```

### COMPILER INVOCATION:
```
clang++ -cc1 -fsyntax-only -std=c++20 -Wall -Wextra -pedantic-errors -xc++ -
```

### ACTUAL OUTPUT:
```
error: templates must have C++ linkage
<stdin>:1:1: note: extern "C" language linkage specification begins here
extern "C" {
^
<stdin>:3:18: error: no matching function for call to 'g'
  void g(void) { g(42); }
                 ^
<stdin>:3:8: note: candidate function not viable: requires 0 arguments, but 1 was provided
  void g(void) { g(42); }
       ^
2 errors generated.
```

### EXPECTED OUTPUT:
(first error should point to the `declarator-id` of the abbreviated function template)

### COMPILER VERSION INFO (`clang++ -v`):
```
clang version 12.0.0 (https://github.com/llvm/llvm-project.git f92e0d9384763913a745cbe9c757fbb40691dcd1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/wandbox/clang-head/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #46386

--- 

When an abbreviated function template appears in an `extern "C"` block and all template parameters are invented, `TemplateParams->getTemplateLoc()` becomes invalid, leading to an incorrect error location. These changes ensure that the error points to the parameter's location when the template location is invalid.

### CODE REVIEW

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -7991,8 +7991,12 @@ Sema::CheckTemplateDeclScope(Scope *S, TemplateParameterList *TemplateParams) {
   //   have C linkage.
   DeclContext *Ctx = S->getEntity();
   if (Ctx && Ctx->isExternCContext()) {
-    Diag(TemplateParams->getTemplateLoc(), diag::err_template_linkage)
-        << TemplateParams->getSourceRange();
+    SourceRange Range =
+        TemplateParams->getTemplateLoc().isInvalid() && TemplateParams->size()
+            ? TemplateParams->getParam(TemplateParams->size() - 1)
+                  ->getSourceRange()
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplate.cpp:7997]: Why use the last one and not the first one?
(Either getTemplateLoc is valid or all parameters are invented)

Comment (a-tarasyuk) [reply clang/lib/Sema/SemaTemplate.cpp:7997]: @cor3ntin thanks for the review. The decision to retrieve the last parameter was driven by the following comment for this helper https://github.com/llvm/llvm-project/blob/36cd60144b15dd35c8e0081100421c3511242e02/clang/include/clang/AST/DeclTemplate.h#L1091

Or better to use first param?

Comment (cor3ntin) [reply clang/lib/Sema/SemaTemplate.cpp:7997]: I think using the first param would be better, yes

(in the general case, you can have

```cpp
template <typename>
void f(auto);
```

so to establish if there are abbreviated parameters, you need to look at the first one, 
(and getTemplateLoc is always valid)

but in the 
```cpp
void f(auto)
```

case, there are only abbreviated parameters, and you can point to the first one (and getTemplateLoc is never valid).

Does that make sense?

**Review by cor3ntin — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM!
