### PR TITLE
[clang] Disable missing definition warning on pure virtual functions

### LINKED ISSUE #74016: `-Wundefined-func-template` warns that no definition is available for a pure virtual function
The warning seems incorrect as `B::bar` is pure virtual and its definition isn't needed.
```
$ cat test.cpp
```
```cpp
template <typename T> class B {
public:
  constexpr void foo(const T &) { bar(1); }
  virtual constexpr void bar(unsigned int) = 0;
};

template <typename T> class D : public B<T> {
public:
  constexpr void bar(unsigned int) override {}
};

void test() {
  auto t = D<int>();
  t.foo(0);
}
```
```
$ clang++ -std=c++20 test.cpp -Wundefined-func-template -c
test.cpp:4:35: warning: instantiation of function 'B<int>::bar' required here, but no definition is available [-Wundefined-func-template]
  constexpr void foo(const T &) { bar(1); }
                                  ^
test.cpp:5:26: note: forward declaration of template entity is here
  virtual constexpr void bar(unsigned int) = 0;
                         ^
test.cpp:4:35: note: add an explicit instantiation declaration to suppress this warning if 'B<int>::bar' is explicitly instantiated in another translation unit
  constexpr void foo(const T &) { bar(1); }
                                  ^
1 warning generated.
```

### PR DESCRIPTION
**Pull request by charmitro**
Warning '-Wundefined-func-template' incorrectly indicates that no definition is available for a pure virtual function. However, a definition is not needed for a pure virtual function.

Fixes #74016

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 1]
```diff
@@ -4952,7 +4952,8 @@ void Sema::InstantiateFunctionDefinition(SourceLocation PointOfInstantiation,
         std::make_pair(Function, PointOfInstantiation));
     } else if (TSK == TSK_ImplicitInstantiation) {
       if (AtEndOfTU && !getDiagnostics().hasErrorOccurred() &&
-          !getSourceManager().isInSystemHeader(PatternDecl->getBeginLoc())) {
+          !getSourceManager().isInSystemHeader(PatternDecl->getBeginLoc()) &&
+          !Function->isVirtualAsWritten()) {
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:4956]: Should we also check that it is pure? AFAIK `isVirtualAsWritten` returns true for function marked explicitly virtual. There is also `FunctionDecl::isPure()` to check that it is pure.

File: clang/test/SemaTemplate/instantiate-pure-virtual-function.cpp [hunk 2]
```diff
@@ -0,0 +1,20 @@
+// RUN: %clang_cc1 -fsyntax-only -verify -Wundefined-func-template %s
+// expected-no-diagnostics
+
+namespace PR74016 {
```
Comment (Fznamznon) [inline clang/test/SemaTemplate/instantiate-pure-virtual-function.cpp:4]: I think we normally call them GH when a bug was filed as a GitHub issue.
```suggestion
namespace GH74016 {
```

**Review by Fznamznon — COMMENTED** [review]
Perhaps needs a release note.

File: clang/test/SemaTemplate/instantiate-pure-virtual-function.cpp (hunk 2 above)
Comment (charmitro) [reply clang/test/SemaTemplate/instantiate-pure-virtual-function.cpp]: Fixed. I wasn't aware of this, thanks!

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 1 above)
Comment (charmitro) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: Updated.

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 3]
```diff
@@ -4952,7 +4952,8 @@ void Sema::InstantiateFunctionDefinition(SourceLocation PointOfInstantiation,
         std::make_pair(Function, PointOfInstantiation));
     } else if (TSK == TSK_ImplicitInstantiation) {
       if (AtEndOfTU && !getDiagnostics().hasErrorOccurred() &&
-          !getSourceManager().isInSystemHeader(PatternDecl->getBeginLoc())) {
+          !getSourceManager().isInSystemHeader(PatternDecl->getBeginLoc()) &&
+          !Function->isVirtualAsWritten() && !Function->isPure()) {
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:4956]:
```suggestion
          !(Function->isVirtualAsWritten() && Function->isPure()) {
```

Can you add a test to make sure non-pure virtual function still get diagnosed?

Comment (charmitro) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp]: After double-checking this, I think we should just check for `isPure()` and don't bother checking for `isVirtualAsWritten()` at all since non-virtual functions cannot be pure. Also, for reference,

https://github.com/llvm/llvm-project/blob/d6fbd96e5eaf3e8acbf1b43dce7a311352907567/clang/include/clang/AST/Decl.h#L2293-L2295

Code updated to match this. Also a test-case added to verify that non-pure virtual functions still get diagnosed.

**Comment by charmitro** [comment]
> Perhaps needs a release note.

> Can you add a release note indicating #74016 was fixed? Otherwise LGTM.

Release note added.

> If you wanted to make a follow up {R to rename `isPure` to `isPureVirtual`, i think that might be helpful (to avoid confusion with the `gnu::pure` attribute)

Yes, this could be helpful. I'll create a follow up PR for this.

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks

**Comment by ahatanak** [comment]
Any progress on this patch?

As we discussed in https://github.com/llvm/llvm-project/issues/74016, we should make sure clang doesn't stop emitting the warning when the definition of a pure virtual function is actually needed.

It seems to me that we shouldn't set `NeededForConstantEvaluation` or `NeedDefinition` in `Sema::MarkFunctionReferenced` to true when a pure virtual function is used in a virtual function call.

File: clang/lib/Sema/SemaExpr.cpp [hunk 4]
```diff
@@ -18931,7 +18931,7 @@ void Sema::MarkFunctionReferenced(SourceLocation Loc, FunctionDecl *Func,
   //   constant evaluated
   bool NeededForConstantEvaluation =
       isPotentiallyConstantEvaluatedContext(*this) &&
-      isImplicitlyDefinableConstexprFunction(Func);
+      isImplicitlyDefinableConstexprFunction(Func) && !Func->isPure();
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaExpr.cpp:18934]: I don't understand how the function being pure relates to whether it's needed for constant evaluation. I think this should move down to `NeedDefinition` below?

**Review by AaronBallman — APPROVED** [review]
Aside from a minor NFC nit with where we decide to do the check, this LGTM

File: clang/lib/Sema/SemaExpr.cpp (hunk 4 above)
Comment (shafik) [reply clang/lib/Sema/SemaExpr.cpp:18934]: I concur, this does not make sense doing the check here.

Comment (shafik) [reply clang/lib/Sema/SemaExpr.cpp]: I am not sure the diagnostic makes sense in that case since it can never actually be called.

Comment (shafik) [reply clang/lib/Sema/SemaExpr.cpp]: Thank to @erichkeane I realized I am wrong, we can actually define a pure virtual function. So we do want to retain the diagnostic here.

Comment (shafik) [reply clang/lib/Sema/SemaExpr.cpp]: I am not sure why moving it down silences the diagnostic, I would think doing `(OdrUse == OdrUseContext::Used || NeededForConstantEvaluation || !Func->isPure())` should work. 

Can you explain in more detail?

Comment (charmitro) [reply clang/lib/Sema/SemaExpr.cpp]: You're actually right. 

I don't really recall what I was entering back when I was developing it, but it should work now.

**Review by AaronBallman — APPROVED** [review]
LGTM! Do you need someone to land this on your behalf?

**Comment by charmitro** [comment]
> LGTM! Do you need someone to land this on your behalf?

I don't have commit rights. If I remember correctly from when LLVM used Phabricator (reviews.llvm.org) you'd need my name & e-address. If that's so,
`Charalampos Mitrodimas <charmitro@posteo.net>`
