### PR TITLE
[NVPTX] Fixup EXT_LOAD lowering for i128 values

### LINKED ISSUE #138034: [NVPTX] Failure in PTX when generating code for `i128` regresses `libc` tests
A recent patch seems to have changed the behavior of `i128` on NVPTX targets. This is causing failures as shown in https://godbolt.org/z/cPq69rs1T.  This is the reproducer.
```llvm
target triple = "nvptx64-nvidia-cuda"

define i128 @foo() {
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load i8, ptr null, align 1
  %conv = zext i8 %0 to i128
  store i128 %conv, ptr null, align 16
  br label %while.cond
}
```
```console
$ clang --target=nvptx64-nvidia-cuda -march=sm_89 bug.bc
```
This will generate an error and the following PTX.
```asm
//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_89
.address_size 64

	// .globl	foo // -- Begin function foo
                                        // @foo
.visible .func  (.param .align 16 .b8 func_retval0[16]) foo()
{
	.reg .b64 	%rd<4>;

// %bb.0:                               // %entry
	bra.uni 	$L__BB0_1;
$L__BB0_1:                              // %while.cond
                                        // =>This Inner Loop Header: Depth=1
	mov.b64 	%rd1, 0;
	ld.v2.u4 	{%rd2, %rd3}, [%rd1];
	st.v2.u64 	[%rd1], {%rd2, %rd3};
	bra.uni 	$L__BB0_1;
                                        // -- End function
}
```
```
ptxas reduced.s, line 20; error   : Unexpected instruction types specified for 'ld'
ptxas fatal   : Ptx assembly aborted due to errors
clang: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 21.0.0git
Target: nvptx64-nvidia-cuda
Thread model: posix
InstalledDir: /home/jhuber/Documents/llvm/clang/bin
Build config: +assertions
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

### PR DESCRIPTION
**Pull request by AlexMaclean**
Ensure that when custom lowering a vector load/store to a multi-output load/store node we confirm that the memory value type matches the type used by the node. Also add some asserts for basic sanity checking of load size.

Fixes https://github.com/llvm/llvm-project/issues/138034

### CODE REVIEW

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 1]
```diff
@@ -3191,20 +3191,22 @@ SDValue NVPTXTargetLowering::LowerSTORE(SDValue Op, SelectionDAG &DAG) const {
...
 SDValue
 NVPTXTargetLowering::LowerSTOREVector(SDValue Op, SelectionDAG &DAG) const {
-  SDNode *N = Op.getNode();
+  MemSDNode *N = cast<MemSDNode>(Op.getNode());
   SDValue Val = N->getOperand(1);
   SDLoc DL(N);
-  EVT ValVT = Val.getValueType();
+  const EVT ValVT = Val.getValueType();
+  const EVT MemVT = N->getMemoryVT();
+  if (ValVT != MemVT)
```
Comment (Artem-B) [inline llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:3199]: We could use a comment explaining what `ValVT != MemVT` means and when it may happen.

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 2]
```diff
@@ -5762,20 +5764,20 @@ static void ReplaceBITCAST(SDNode *Node, SelectionDAG &DAG,
 /// ReplaceVectorLoad - Convert vector loads into multi-output scalar loads.
 static void ReplaceLoadVector(SDNode *N, SelectionDAG &DAG,
                               SmallVectorImpl<SDValue> &Results) {
-  const EVT ResVT = N->getValueType(0);
-  SDLoc DL(N);
+  LoadSDNode *LD = cast<LoadSDNode>(N);
+  const EVT ResVT = LD->getValueType(0);
+  const EVT MemVT = LD->getMemoryVT();
+  if (ResVT != MemVT)
```
Comment (Artem-B) [inline llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:5770]: Ditto.

**Review by jhuber6 — APPROVED** [review]
Thanks, looks straightforward enough to me but someone more familiar with the NVPTX backend might know more.

File: llvm/test/CodeGen/NVPTX/i128-ld-st.ll [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+; CHECK-EMPTY:
+; CHECK-NEXT:  // %bb.0: // %entry
+; CHECK-NEXT:    bra.uni $L__BB0_1;
+; CHECK-NEXT:  $L__BB0_1: // %while.cond
+; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
+; CHECK-NEXT:    mov.b64 %rd1, 0;
+; CHECK-NEXT:    ld.u8 %rd2, [%rd1];
+; CHECK-NEXT:    st.v2.u64 [%rd1], {%rd2, %rd1};
+; CHECK-NEXT:    bra.uni $L__BB0_1;
+entry:
```
Comment (Artem-B) [inline llvm/test/CodeGen/NVPTX/i128-ld-st.ll:20]: the test case could be cleaned up a bit, dropping the loop and using valid pointers, so there are no questions of whether the input is valid.

E.g. https://godbolt.org/z/EsvbY3dav

**Review by Artem-B — APPROVED** [review]
LGTM, with minor nits.
Thank you for the quick fix!

**Review by Artem-B — APPROVED** [review]
