### PR TITLE
[X86] X86FixupVectorConstantsPass - use scheduler model to avoid regressions

### LINKED ISSUE #135998: [X86][AVX2] X86FixupVectorConstantsPass - performance regression
Moving ISPC from LLVM 18 to LLVM 20, I have encountered performance regression for a few of our benchmarks for ISPC target avx2 (corresponds to `-mcpu=haswell`). It seems to be caused by #122601. It is around ~20-25%, as measured on Intel CPUs i9-12900 and 8360Y.

Compiler explorer link: https://godbolt.org/z/qx8s6K6br

### PR DESCRIPTION
**Pull request by RKSimon**
When attempting to replace a full vector constant load with an instruction that uses a smaller constant, check the scheduler model to ensure the instruction isn't slower.

Throughput must not regress, but allow a small increase in latency based on how much constant data we're saving (I've used a simple estimate of 1 cycle per 128-bits of data saved).

NOTE: this currently ignores hoisted constant loads where the slower instruction might be acceptable.

Fixes #135998

### CODE REVIEW

File: llvm/lib/Target/X86/X86FixupVectorConstants.cpp [hunk 1]
```diff
@@ -355,6 +356,36 @@ bool X86FixupVectorConstantsPass::processInstruction(MachineFunction &MF,
...
+      double OldTput = MCSchedModel::getReciprocalThroughput(*ST, *OldDesc);
+      double NewTput = MCSchedModel::getReciprocalThroughput(*ST, *NewDesc);
+      if (OldTput != NewTput)
+        return NewTput < OldTput;
+
+      int LatTol = (BitsSaved + 127) / 128;
+      int OldLat = MCSchedModel::computeInstrLatency(*ST, *OldDesc);
+      int NewLat = MCSchedModel::computeInstrLatency(*ST, *NewDesc);
+      if (OldLat != NewLat)
+        return NewLat < (OldLat + LatTol);
```
Comment (phoebewang) [inline llvm/lib/Target/X86/X86FixupVectorConstants.cpp:381]: I don't understand the formula here. Is it a heuristic?

**Review by phoebewang — APPROVED** [review]
LGTM.
