### PR TITLE
[Clang] Defer the instantiation of explicit-specifier until constraint checking completes

### LINKED ISSUE #59827: [Clang][concepts] Conditional `explicit` specifier is checked too early in constrained constructor
Repro (3rd version, 2nd version reproduced other possible bug; see edit history):

```c++
template<class X>
constexpr X failure() {
    return nullptr;
}

struct T {
    template<class X>
        requires false
    constexpr explicit(failure<X>()) T(X) { }

    T(int) { }
};

static T t(5);
```

Expected: *correct compilation*

Got:

```console
<source>:3:12: error: cannot initialize return object of type 'int' with an rvalue of type 'std::nullptr_t'
    return nullptr;
           ^~~~~~~
<source>:9:24: note: in instantiation of function template specialization 'failure<int>' requested here
    constexpr explicit(failure<X>()) T(X) { }
                       ^
<source>:14:10: note: while substituting deduced template arguments into function template 'T' [with X = int]
static T t(5);
         ^
```

Compiler explorer: https://godbolt.org/z/sPsGh46Gs
Discovered in: https://github.com/microsoft/STL/pull/3323

### PR DESCRIPTION
**Pull request by LYP951018**
Modifications:

- Skip the instantiation of the explicit-specifier during Decl substitution if we are deducing template arguments and the explicit-specifier is value dependent.

- Instantiate the explicit-specifier after the constraint checking completes.

- Make `instantiateExplicitSpecifier` a member function in order to instantiate the explicit-specifier in different stages.

This PR doesn’t defer the instantiation of the explicit specifier for deduction guides, because I’m not familiar with deduction guides yet. I’ll dig into it after this PR.

According to my local test, GCC 13 tuple works with this PR.

Fixes #59827.

### CODE REVIEW

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -3553,6 +3553,56 @@ static unsigned getPackIndexForParam(Sema &S,
...
+        if (Instantiated.isInvalid()) {
+          ExplicitDecl->setInvalidDecl(true);
+          return clang::Sema::TDK_SubstitutionFailure;
+        }
+        ExplicitDecl->setExplicitSpecifier(Instantiated);
+        return clang::Sema::TDK_Success;
+      };
+  Sema::TemplateDeductionResult DeductionResult = clang::Sema::TDK_Success;
+  if (CXXConstructorDecl *ConstructorDecl =
+          dyn_cast_or_null<CXXConstructorDecl>(Specialization)) {
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3595]: nit: use `dyn_cast` since we have ensured that `Specialization` is non-null at the caller site `FinishTemplateArgumentDeduction`.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 2]
```diff
@@ -3553,6 +3553,56 @@ static unsigned getPackIndexForParam(Sema &S,
...
+        Expr *const Expr = ExplicitSpecifier.getExpr();
+        if (!Expr) {
+          return Sema::TDK_Success;
+        }
+        if (!Expr->isValueDependent()) {
+          return Sema::TDK_Success;
+        }
+        // TemplateDeclInstantiator::InitFunctionInstantiation set the
+        // ActiveInstType to TemplateInstantiation, but we need
+        // to enable SFINAE when instantiating explicit specifier.
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3579]:
```suggestion
        // TemplateDeclInstantiator::InitFunctionInstantiation sets the
        // ActiveInstType to TemplateInstantiation, but we need
        // to enable SFINAE when instantiating an explicit specifier.
```

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 3]
```diff
@@ -3553,6 +3553,56 @@ static unsigned getPackIndexForParam(Sema &S,
...
+  if (CXXConstructorDecl *ConstructorDecl =
+          dyn_cast_or_null<CXXConstructorDecl>(Specialization)) {
+    DeductionResult =
+        TryInstantiateExplicitSpecifierForSingleDecl(ConstructorDecl);
+  } else if (CXXConversionDecl *ConversionDecl =
+                 dyn_cast_or_null<CXXConversionDecl>(Specialization)) {
+    DeductionResult =
+        TryInstantiateExplicitSpecifierForSingleDecl(ConversionDecl);
+  }
+  return DeductionResult;
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3603]: Rather than returning `clang::Sema::TDK_Success` silently, shall we add an assertion that the `Specialization` is either a constructor or a conversion function?

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 4]
```diff
@@ -3553,6 +3553,56 @@ static unsigned getPackIndexForParam(Sema &S,
   llvm_unreachable("parameter index would not be produced from template");
 }
 
+// if `Specialization` is a `CXXConstructorDecl` or `CXXConversionDecl`
+// we try to instantiate and update its explicit specifier after constraint
+// checking.
+static Sema::TemplateDeductionResult
+tryInstantiateExplicitSpecifier(Sema &S, FunctionDecl *Specialization,
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3560]: nit: Do you think we should make this function a (private) member of `Sema` instead of a static function?

**Review by zyn0217 — COMMENTED** [review]
Thank you for working on this! Some nit comments, hope you don't mind.
(Also invited some clang folks to have a detailed look at this. :=)

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 1 above)
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3595]: Thanks for reviewing ;)
Sadly, the type itself is required, because I need to call `CXXConversionDecl/CXXConstructorDecl::getExplicitSpecifier`/`setExplicitSpecifier` to get or set the explicit specifier.
I could not think of a better way to handle this without a template... 
If I put the function into `Sema` as a member function, I need to put two functions (one of them is the templated function) to `Sema`. Is that ok?

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 2 above)
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3579]: Should the `set` here be past tense or present tense here? `TemplateDeclInstantiator::InitFunctionInstantiation` is called before this function and I think it should be past tense... I'm not good at English :(

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 1 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3595]: Ah, I missed that. Hmm... Perhaps keep it inline and just extract the calls to the two functions (get and set ExplicitSpecifier) into their own little functions that 'do the right thing'.  So:

```
 auto getExplicitSpecifier(FunctionDecl *FD) {
   return isa<CXXConstructorDecl>(FD) ? cast<CXXConstructorDecl>(FD)->getExplicitSpecifier() : cast<CXXConversionDecl>(FD)->getExplicitSpecifier;
}
```

Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: Thanks for the advice, I’ve refactored the code. ;)

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 3 above)
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: I've refactored the code here. If `Specialization` is not either constructor or conversion function, `cast` will `assert`.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 4 above)
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: Since this function isn't reused, I prefer to leave it `static` :)

**Review by erichkeane — APPROVED** [review]
This is fine to me, please give other reviewers another day to take a look before merging though.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 5]
```diff
@@ -3682,6 +3725,17 @@ Sema::TemplateDeductionResult Sema::FinishTemplateArgumentDeduction(
     }
   }
 
+  // We skipped the instantiation of the explicit-specifier during subst the
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3728]: This sentence is not super clear, can we spell out `subst` and `FD` as well.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 6]
```diff
@@ -3553,6 +3553,49 @@ static unsigned getPackIndexForParam(Sema &S,
...
+  if (!Expr) {
+    return Sema::TDK_Success;
+  }
+  if (!Expr->isValueDependent()) {
+    return Sema::TDK_Success;
+  }
+  // TemplateDeclInstantiator::InitFunctionInstantiation set the
+  // ActiveInstType to TemplateInstantiation, but we need
+  // to enable SFINAE when instantiating an explicit specifier.
+  Sema::InstantiatingTemplate Inst(
```
[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: This part is a bit tricky... Actually, the `InstantiatingTemplate` here is only used to enable SFINAE, the instantiation depth/count is the same as `FinishTemplateArgumentDeduction`. If the `InstantiatingTemplate` in `FinishTemplateArgumentDeduction` is valid, the `InstantiatingTemplate` in `resolveExplicitSpecifier` should be valid, too.

Is that theory correct? If that's correct, I'll add comment for this.

[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: > the InstantiatingTemplate here is only used to enable SFINAE...

I'm wondering if [`SFINAETrap`](https://github.com/llvm/llvm-project/blob/e6971e5a41fe30264af9a13c8f387c06f93c6d9c/clang/include/clang/Sema/Sema.h#L10006-L10007) does the trick for you.

[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: Thanks for reminding :)
I think you are right,`SFINAETrap` seems do the trick here. I'll take a deeper look at this.

[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: I'm a bit confused here. Do I need to check `SFINAETrap::hasErrorOccurred`? Is `ExprResult::IsValid` enough?

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: I would suggest checking both?  But I cannot come up with a reason why just the ExprResult's validity wouldn't be sufficient.

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: And yet, as soon as I said that, I remembered:  a `RecoveryExpr` (or other attempts at error recovery) can result in an error happening, but a valid expression being returned.

[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3587]: Thanks for your reminder! I've added the `hasErrorOccurred` check.
Also I renamed the function because I found a function named `tryResolveExplicitSpecifier` and I want to make them distinct.

[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3590]: > So we don't have to check Inst.isInvalid()?

comments added

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3590]: Sorry, why do not have to check `Inst.isInvalid`?  We do it everywhere, and it is a good 'catch' for mistakes.

[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3590]: The instantiation depth in `instantiateExplicitSpecifierDeferred` is the depth in `FinishTemplateArgumentDeduction` plus one, but I think, actually, their depths should be equal ... If the depth in `FinishTemplateArgumentDeduction` is valid, the depth in `instantiateExplicitSpecifierDeferred` should be valid, too. So, I didn't check `IsValid`: If I check it, the available depth will be subtracted by one

But it seems that `IsValid` not only check the instantiation depth ... :(

[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3590]: Right, there is quite a bit that it checks, so we  ALWAYS check it (or at least should).

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 7]
```diff
@@ -3580,16 +3580,12 @@ static Sema::TemplateDeductionResult instantiateExplicitSpecifierDeferred(
...
-  // `DeducedTemplateArgumentSubstitution` because ActiveInstType was set to
-  // `TemplateInstantiation` in
-  // `TemplateDeclInstantiator::InitFunctionInstantiation`. The real depth of
-  // instantiation should be the same as the depth in
-  // `FinishTemplateArgumentDeduction`.
-  // So we don't check `InstantiatingTemplate::IsValid` here.
   Sema::InstantiatingTemplate Inst(
       S, Info.getLocation(), FunctionTemplate, DeducedArgs,
       Sema::CodeSynthesisContext::DeducedTemplateArgumentSubstitution, Info);
+  if (Inst.isInvalid()) {
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3586]: This is a single-line block, so per style guide, don't use curley braces.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 8]
```diff
@@ -3553,6 +3553,47 @@ static unsigned getPackIndexForParam(Sema &S,
...
+               : cast<CXXConversionDecl>(D)->getExplicitSpecifier();
+  };
+  auto SetExplicitSpecifier = [](FunctionDecl *D, ExplicitSpecifier ES) {
+    isa<CXXConstructorDecl>(D)
+        ? cast<CXXConstructorDecl>(D)->setExplicitSpecifier(ES)
+        : cast<CXXConversionDecl>(D)->setExplicitSpecifier(ES);
+  };
+
+  ExplicitSpecifier ES = GetExplicitSpecifier(Specialization);
+  Expr *const Expr = ES.getExpr();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3576]:
```suggestion
  Expr *SpecifierExpr = ES.getExpr();
```

We don't typically use const-pointers in clang, particularly for local variables.  Also, a better name would be appreciated.

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 7 above)
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp]: Thanks for catching this! I’m still adapting to the LLVM coding style :(
I've fixed all similar cases.

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 9]
```diff
@@ -3553,6 +3553,47 @@ static unsigned getPackIndexForParam(Sema &S,
...
+  if (!Expr->isValueDependent())
+    return Sema::TDK_Success;
+
+  Sema::InstantiatingTemplate Inst(
+      S, Info.getLocation(), FunctionTemplate, DeducedArgs,
+      Sema::CodeSynthesisContext::DeducedTemplateArgumentSubstitution, Info);
+  if (Inst.isInvalid())
+    return Sema::TDK_InstantiationDepth;
+  Sema::SFINAETrap Trap(S);
+  const auto Instantiated = S.instantiateExplicitSpecifier(SubstArgs, ES);
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3588]: I think this is a case where we don't permit `auto`, though this is an argument that has happened before.

**Review by erichkeane — COMMENTED** [review]
Did a better run-through again, so these are all thats left for me.  Thanks for the patience!

File: clang/lib/Sema/SemaTemplateDeduction.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (LYP951018) [reply clang/lib/Sema/SemaTemplateDeduction.cpp:3582]: ok :)

**Review by erichkeane — APPROVED** [review]

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 10]
```diff
@@ -3553,6 +3553,48 @@ static unsigned getPackIndexForParam(Sema &S,
...
+
+  Sema::InstantiatingTemplate Inst(
+      S, Info.getLocation(), FunctionTemplate, DeducedArgs,
+      Sema::CodeSynthesisContext::DeducedTemplateArgumentSubstitution, Info);
+  if (Inst.isInvalid())
+    return Sema::TDK_InstantiationDepth;
+  Sema::SFINAETrap Trap(S);
+  const ExplicitSpecifier InstantiatedES =
+      S.instantiateExplicitSpecifier(SubstArgs, ES);
+  if (InstantiatedES.isInvalid() || Trap.hasErrorOccurred()) {
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:3590]: Do we have a test that checks this case at all? Same for the other failures, if we know how to test them we should write a test to verify them.

**Review by shafik — APPROVED** [review]
I just want to make sure we have enough testing in place for this change but overall I think I am happy.
