### PR TITLE
[libc++][TZDB] Improves time zone format specifiers.

### LINKED ISSUE #78184: [libc++][format] file_clock should always use UTC as timezone
Actually this clock should always have UTC at timezone, this GMT is wrong too.
[[time.format]/12](http://eel.is/c++draft/time.format#12)
```
Remarks: If %Z is used, it is replaced with STATICALLY-WIDEN<charT>("UTC").
```

_Originally posted by @mordante in https://github.com/llvm/llvm-project/pull/75526#discussion_r1452581034_

### PR DESCRIPTION
**Pull request by mordante**
Per [tab:time.format.spec]
%z  The offset from UTC as specified in ISO 8601-1:2019, subclause
    5.3.4.1. For example -0430 refers to 4 hours 30 minutes behind UTC.
    If the offset is zero, +0000 is used. The modified commands %Ez and
    %Oz insert a : between the hours and minutes: -04:30. If the offset
    information is not available, an exception of type format_error is
    thrown.

Typically the modified versions Oz or Ez would have wording like

  The modified command %OS produces the locale's alternative
  representation.

In this case the modified version does not depend on the locale.

This change is a preparation for formatting sys_info which has time zone information. The function time_put<_CharT>::put() does not have proper time zone support, therefore it's a manual implementation.

Fixes https://github.com/llvm/llvm-project/issues/78184

### CODE REVIEW

File: libcxx/include/__chrono/formatter.h [hunk 1]
```diff
@@ -170,10 +171,45 @@ _LIBCPP_HIDE_FROM_ABI void __format_century(basic_stringstream<_CharT>& __sstr,
...
+// Implements the %z format specifier according to [tab:time.format.spec], where
+// '__modifier' signals %Oz or %Ez were used. (Both modifiers behave the same,
+// so there is no need to distinguish between them.)
+template <class _CharT>
+_LIBCPP_HIDE_FROM_ABI void
+__format_zone_offset(basic_stringstream<_CharT>& __sstr, chrono::seconds __offset, bool __modifier) {
+  if (__offset < 0s) {
+    __sstr << _CharT('-');
+    __offset = -__offset;
+  } else
```
Comment (ldionne) [inline libcxx/include/__chrono/formatter.h:183]: Minor style nit but it looks really weird to me without braces, since the block above has braces.

File: libcxx/include/__chrono/formatter.h [hunk 2]
```diff
@@ -170,10 +171,45 @@ _LIBCPP_HIDE_FROM_ABI void __format_century(basic_stringstream<_CharT>& __sstr,
...
+  else
+    std::format_to(__out_it, _LIBCPP_STATICALLY_WIDEN(_CharT, "{:%H%M}"), __hms);
+}
+
+// Helper to store the time zone information needed for formatting.
+struct _LIBCPP_HIDE_FROM_ABI __time_zone {
+  // Typically these abbreviations as short and fit in the string's internal
+  // buffer.
+  string __abbrev{"UTC"};
+  chrono::seconds __offset{0};
```
Comment (ldionne) [inline libcxx/include/__chrono/formatter.h:199]: It feels weird to me to have these as default initializers. Instead I would not provide any defaults here, but I would initialize the result in `__convert_to_time_zone` below using `{"UTC", 0}`.

**Review by ldionne — APPROVED** [review]
LGTM with minor comments. Thanks!
