### PR TITLE
[Clang] Eagerly instantiate used constexpr function upon definition.

### LINKED ISSUE #73232: Clang reports an undefined function that has been defined
Not sure how to title this properly.

The original reproducer is just:

```c++
#include <string>
constexpr auto z = std::string("", 0);
```
with libstdc++.

Using cvise, I get:
```c++
template <typename _CharT>
struct basic_string {
  constexpr void _M_construct();

  constexpr basic_string() {
    _M_construct();
  }

};


basic_string<char *> a;


template <typename _CharT>
constexpr void basic_string<_CharT>::_M_construct(){}

constexpr basic_string<char*> z{};
```
https://godbolt.org/z/7PzreExcf

Clang's output is:

```console
<source>:18:16: error: constexpr variable 'z' must be initialized by a constant expression
   18 | constexpr auto z = basic_string<char *>();
      |                ^   ~~~~~~~~~~~~~~~~~~~~~~
<source>:6:5: note: undefined function '_M_construct' cannot be used in a constant expression
    6 |     _M_construct();
      |     ^
<source>:18:20: note: in call to 'basic_string()'
   18 | constexpr basic_string<char*> z{}
      |                    ^~~~~~~~~~~~~~~~~~~~~~
<source>:3:18: note: declared here
    3 |   constexpr void _M_construct();
      |                  ^
```

The problem vanishes if `a` is commented out, or if `basic_string` is not a template anymore.

### PR DESCRIPTION
**Pull request by cor3ntin**
Despite CWG2497 not being resolved, it is reasonable to expect the following code to compile (and which is supported by other compilers)

```cpp
  template<typename T> constexpr T f();
  constexpr int g() { return f<int>(); } // #1
  template<typename T> constexpr T f() { return 123; }
  int k[g()];
  // #2
```

To that end, we eagerly instantiate all referenced specializations of constexpr functions when they are defined.

We maintain a map of (pattern, [instantiations]) independant of `PendingInstantiations` to avoid having to iterate that list after each function definition.

We should apply the same logic to constexpr variables, but I wanted to keep the PR small.

Fixes #73232

### CODE REVIEW

**Comment by tbaederr** [comment]
Does this have any compile-time impact?

**Comment by cor3ntin** [comment]
> Does this have any compile-time impact?

Nope, should be ~free. It does add 1 DenseMap lookup per constexpr function definition, which ought to be negligible.

**Comment by zygoloid** [comment]
I *think* the new map should be unnecessary: `FunctionTemplateDecl` and `VarTemplateDecl` already have a list of specializations that you can walk and check the point of instantiation and template specialization kind to see if there's a pending instantiation.

If you want/need to keep the map approach, you'll need to also deal with the case where the template is declared in a PCH and then defined somewhere that includes the PCH, which will mean serializing and deserializing the map contents.

**Comment by zygoloid** [comment]
> > I _think_ the new map should be unnecessary: `FunctionTemplateDecl` and `VarTemplateDecl` already have a list of specializations that you can walk and check the point of instantiation and template specialization kind to see if there's a pending instantiation.
> 
> I don't think that's viable for non-template but templated entities like member function in a class template. Am I missing something?

Hmm, good point, we don't have a way to walk the specializations of a templated function that's not a function template. (You'd need to walk all the instantiations of the enclosing template and check to see if the corresponding member function has a pending instantiation, or something like that, which sounds painful. Friends defined in class templates would probably be especially problematic.)

Let's use your map approach then :-)

**Comment by cor3ntin** [comment]
@zygoloid It took me a while, but I think I got it; what do you think of direction ? (description in the last commit message)
It appears I am doing something a bit novel, but I couldn't think of a better way.

File: clang/include/clang/Sema/ExternalSemaSource.h [hunk 1]
```diff
@@ -181,6 +181,9 @@ class ExternalSemaSource : public ExternalASTSource {
                  SmallVectorImpl<std::pair<ValueDecl *,
                                            SourceLocation> > &Pending) {}
 
+  virtual void ReadPendingOfInstantiationsForConstexprEntity(
```
Comment (zygoloid) [inline clang/include/clang/Sema/ExternalSemaSource.h:184]: The "Of" here seems out of place; maybe remove it? You also have an inconsistent "Of" vs "For" after "Instantiations". Would be good to use a consistent spelling.

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 2]
```diff
@@ -6481,6 +6481,33 @@ void Sema::PerformPendingInstantiations(bool LocalOnly) {
     PendingInstantiations.swap(delayedPCHInstantiations);
 }
 
+// Instantiate all referenced specializations of the given function template
+// definition. This make sure that function template that are defined after the
+// point of instantiation of their used can be evaluated after they are defined.
+// see CWG2497.
+void Sema::InstantiateFunctionTemplateSpecializations(
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6488]: This name doesn't describe what the function does very well. Maybe something more like `PerformPendingInstantiationsOfConstexprFunction` would be clearer?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 3]
```diff
@@ -6481,6 +6481,33 @@ void Sema::PerformPendingInstantiations(bool LocalOnly) {
...
+    for (NamedDecl *Fun : Range) {
+      InstantiateFunctionDefinition(PointOfInstantiation,
+                                    cast<FunctionDecl>(Fun));
+    }
+  };
+
+  auto It =
+      PendingInstantiationsOfConstexprEntities.find(Tpl->getCanonicalDecl());
+  if (It != PendingInstantiationsOfConstexprEntities.end()) {
+    InstantiateAll(It->second);
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6501]: Is this iterator guaranteed to remain valid throughout this call? We might add new keys to the map. Maybe we should move the vector out of the map first.

File: clang/lib/Serialization/ASTReader.cpp [hunk 4]
```diff
@@ -8718,6 +8731,18 @@ void ASTReader::ReadPendingInstantiations(
   PendingInstantiations.clear();
 }
 
+void ASTReader::ReadPendingOfInstantiationsForConstexprEntity(
+    const NamedDecl *D, llvm::SmallSetVector<NamedDecl *, 4> &Decls) {
+  for (auto *Redecl : D->redecls()) {
+    DeclID Id = Redecl->getGlobalID();
+    auto It = PendingInstantiationsOfConstexprEntities.find(Id);
```
Comment (zygoloid) [inline clang/lib/Serialization/ASTReader.cpp:8738]: Maybe skip this lookup for declarations that aren't from an AST file?

File: clang/lib/Serialization/ASTWriter.cpp [hunk 5]
```diff
@@ -4836,6 +4837,16 @@ ASTFileSignature ASTWriter::WriteASTCore(Sema &SemaRef, StringRef isysroot,
   assert(SemaRef.PendingLocalImplicitInstantiations.empty() &&
          "There are local ones at end of translation unit!");
 
+  // Build a record containing all of pending instantiations of constexpr
```
Comment (zygoloid) [inline clang/lib/Serialization/ASTWriter.cpp:4840]:
```suggestion
  // Build a record containing all pending instantiations of constexpr
```

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 6]
```diff
@@ -6481,6 +6481,33 @@ void Sema::PerformPendingInstantiations(bool LocalOnly) {
...
+// Instantiate all referenced specializations of the given function template
+// definition. This make sure that function template that are defined after the
+// point of instantiation of their used can be evaluated after they are defined.
+// see CWG2497.
+void Sema::InstantiateFunctionTemplateSpecializations(
+    SourceLocation PointOfInstantiation, FunctionDecl *Tpl) {
+
+  auto InstantiateAll = [&](const auto &Range) {
+    for (NamedDecl *Fun : Range) {
+      InstantiateFunctionDefinition(PointOfInstantiation,
```
Comment (zygoloid) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:6493]: I think the point of instantiation should be read from the FunctionDecl, not the point where the function is defined, so that the "in instantiation of" note points to the right place.

**Review by zygoloid — COMMENTED** [review]
Thanks!

File: clang/test/SemaCXX/cxx2b-consteval-propagate.cpp [hunk 7]
```diff
@@ -112,6 +112,9 @@ template <typename T>
 constexpr int f(T t) { // expected-note {{'f<int>' defined here}}
     return id(t); // expected-note {{'f<int>' is an immediate function because its body contains a call to a consteval function 'id' and that call is not a constant expression}}
 }
+
+
+
```
Comment (zygoloid) [inline clang/test/SemaCXX/cxx2b-consteval-propagate.cpp:117]: Revert these added blank lines.

**Review by zygoloid — APPROVED** [review]
Thanks! I assume you'll also be looking at the variable case (perhaps as a separate commit)?

**Review by shafik — APPROVED** [review]
Thank you, LGTM

**Comment by cor3ntin** [comment]
> Thanks! I assume you'll also be looking at the variable case (perhaps as a separate commit)?

I'll try to get to it, yes!
Thanks for the review

File: clang/lib/Serialization/ASTWriter.cpp [hunk 8]
```diff
@@ -4836,6 +4837,16 @@ ASTFileSignature ASTWriter::WriteASTCore(Sema &SemaRef, StringRef isysroot,
   assert(SemaRef.PendingLocalImplicitInstantiations.empty() &&
          "There are local ones at end of translation unit!");
 
+  // Build a record containing all pending instantiations of constexpr
+  // entities.
+  RecordData PendingInstantiationsOfConstexprEntities;
+  for (const auto &I : SemaRef.PendingInstantiationsOfConstexprEntities) {
```
Comment (sam-mccall) [inline clang/lib/Serialization/ASTWriter.cpp:4843]: In case this will be relanded in some form:

This loop uses arbitrary hashtable order, leading to nondeterministic PCM output.
