### PR TITLE
[clang][bytecode] Fix crash in void functions returning non-void expr…

### LINKED ISSUE #176536: [clang][bytecode] Assertion `S.Current->getFunction()->hasRVO()' failed.
Reproducer:
https://godbolt.org/z/3j18eja86
```cpp
constexpr void foo(int n) { return n > 1 ? foo(n-1) : 0; }
```

Backtrace:
```console
clang++: /root/llvm-project/llvm/tools/clang/lib/AST/ByteCode/Interp.h:2862: bool clang::interp::RVOPtr(clang::interp::InterpState&, clang::interp::CodePtr): Assertion `S.Current->getFunction()->hasRVO()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -fexperimental-new-constant-interpreter <source>
1.	<eof> parser at end of file
2.	<source>:1:27: parsing function body 'foo'
 #0 0x000000000430a6b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x430a6b8)
 #1 0x0000000004307b14 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4307b14)
 #2 0x0000000004249de8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f652a442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f652a4969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f652a442476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f652a4287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f652a42871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f652a439e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000007fbbca7 clang::interp::RVOPtr(clang::interp::InterpState&, clang::interp::CodePtr) (.isra.0) Interp.cpp:0:0
#10 0x0000000007ff07bc clang::interp::Interpret(clang::interp::InterpState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7ff07bc)
#11 0x0000000007e06d6b clang::interp::Context::isPotentialConstantExpr(clang::interp::State&, clang::FunctionDecl const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7e06d6b)
#12 0x0000000007d967b1 clang::Expr::isPotentialConstantExpr(clang::FunctionDecl const*, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7d967b1)
#13 0x0000000006ec7b3e clang::Sema::CheckConstexprFunctionDefinition(clang::FunctionDecl const*, clang::Sema::CheckConstexprKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ec7b3e)
#14 0x0000000006e4d30b clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e4d30b)
#15 0x0000000006b6b1d4 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b6b1d4)
#16 0x0000000006a715cb clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a715cb)
#17 0x0000000006aa7a3d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6aa7a3d)
#18 0x0000000006a6472b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a6472b)
#19 0x0000000006a64f1f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a64f1f)
#20 0x0000000006a6cd4a clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a6cd4a)
#21 0x0000000006a6dce5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a6dce5)
#22 0x0000000006a6e190 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a6e190)
#23 0x0000000006a4ed33 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6a4ed33)
#24 0x0000000004c722a8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c722a8)
#25 0x0000000004f6bc55 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4f6bc55)
#26 0x0000000004eeb8de clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4eeb8de)
#27 0x000000000506698d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x506698d)
#28 0x0000000000ddcf9e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xddcf9e)
#29 0x0000000000dd396a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) driver.cpp:0:0
#30 0x0000000000dd3aed int llvm::function_ref<int (llvm::SmallVectorImpl<char const*>&)>::callback_fn<clang_main(int, char**, llvm::ToolContext const&)::'lambda'(llvm::SmallVectorImpl<char const*>&)>(long, llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#31 0x0000000004ce55a9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#32 0x000000000424a284 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x424a284)
#33 0x0000000004ce5bbf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#34 0x0000000004ca6592 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ca6592)
#35 0x0000000004ca753e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4ca753e)
#36 0x0000000004cae985 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4cae985)
#37 0x0000000000dd9311 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd9311)
#38 0x0000000000c969c4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc969c4)
#39 0x00007f652a429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#40 0x00007f652a429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#41 0x0000000000dd3405 _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xdd3405)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

Goes back to clang-19:
https://godbolt.org/z/vGjqn5Mq9

### PR DESCRIPTION
**Pull request by Serosh-commits**
The bytecode compiler was incorrectly emitting an 
RVOPtr
 opcode for void functions if the return expression had a non-void type (e.g. from a conditional operator). This triggered an assertion in the interpreter because void functions lack RVO metadata.

This patch updates 
visitReturnStmt
 to check the function’s return type and use 
discard()
 for the expression in void contexts, preventing erroneous RVO pathing.

Fixes #176536

### CODE REVIEW

File: clang/test/AST/ByteCode/gh176536.cpp [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// RUN: %clang_cc1 -fexperimental-new-constant-interpreter -verify %s
+
+constexpr void foo(int n) {
+  return n > 1 ? foo(n - 1) : 0; // expected-error {{return type 'void' must match the return type 'int' of the expression}}
+}
+static_assert((foo(2), true), "");
```
Comment (tbaederr) [inline clang/test/AST/ByteCode/gh176536.cpp]: Add this to an existing test case, where it will also be tested with the current interpreter.

Comment (Serosh-commits) [reply clang/test/AST/ByteCode/gh176536.cpp]: added it dude The code from 
gh176536.cpp
 is now at the end of 
functions.cpp
 inside a namespace GH176536.

File: clang/lib/AST/ByteCode/Compiler.cpp [hunk 2]
```diff
@@ -5678,8 +5678,9 @@ bool Compiler<Emitter>::visitReturnStmt(const ReturnStmt *RS) {
...
     }
 
-    if (RE->getType()->isVoidType()) {
-      if (!this->visit(RE))
+    if (RE->getType()->isVoidType() ||
+        (CompilingFunction && CompilingFunction->getReturnType()->isVoidType())) {
+      if (!this->discard(RE))
         return false;
     } else {
       InitLinkScope<Emitter> ILS(this, InitLink::RVO());
```
[the remark this answers is not in the document]
Comment (Serosh-commits) [reply clang/lib/AST/ByteCode/Compiler.cpp]: I have simplified it to just the RE->containsErrors() check as you suggested and kept it within the original block structure check it

File: clang/lib/AST/ByteCode/Compiler.cpp [hunk 3]
```diff
@@ -5678,11 +5678,10 @@ bool Compiler<Emitter>::visitReturnStmt(const ReturnStmt *RS) {
...
     }
 
-    if (RE->getType()->isVoidType()) {
-      if (!this->visit(RE))
+    if (RE->containsErrors() || RE->getType()->isVoidType()) {
+      if (!this->discard(RE))
         return false;
     } else {
-      InitLinkScope<Emitter> ILS(this, InitLink::RVO());
       // RVO - construct the value in the return location.
```
Comment (tbaederr) [inline clang/lib/AST/ByteCode/Compiler.cpp]: Move it here and just return falls if the expression contains errors.

Comment (Serosh-commits) [reply clang/lib/AST/ByteCode/Compiler.cpp]: @tbaederr
on the containsErrors() placement =  I originally hoisted it just to catch bad code early/everywhere, but you're totally right it really only matters for blocking the RVO path where things could go wrong. I'll move it down into the else block so it's only checked before visit/RVO .
On discard() =  I swapped visit() for discard() just to be safe about stack hygiene. I was worried visit() might leave a value hanging on the stack (like in the ternary case where a void function returns a non-void expr), whereas discard() explicitly evaluates side effects but guarantees a clean pop. That felt safer given the original RVOPtr assertion was stack-related. But if visit() + a manual pop (or whatever the usual pattern is) is preferred for consistency then i am happy to change it back 
On InitLinkScope = basically just skipped it for void functions because they don't do RVO at all, so setting up that scope felt redundant (and was what emitted the bad opcodes leading to the crash in the first place). Non-void cases keep it unchanged.
please need ur help on that i haven't pushed anything yet wanted to run this reasoning by you first. Does this make sense, or do you want me to adjust any of these before I update (revert discard, different guard for the scope) i will be happy to do that

Comment (Serosh-commits) [reply clang/lib/AST/ByteCode/Compiler.cpp]: @tbaederr 
 Updated the patch to just the minimal fix you asked for is it ok right ?

**Review by tbaederr — APPROVED** [review]
