### PR TITLE
[clang-format]: Annotate colons found in inline assembly

### LINKED ISSUE #92616: [clang-format]: token annotator confuses inline asm colon as ObjCMethodExpr or DictLiteral
The token annotator labels colons in inline asm incorrectly.

```
$ echo " asm ( a : );" | clang-format -debug
...
 M=0 C=1 T=ObjCMethodExpr S=0 F=0 B=0 BK=0 P=43 Name=colon L=6 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=':'
...
$ echo " asm { a : };" | clang-format -debug
...
 M=0 C=0 T=DictLiteral S=1 F=1 B=0 BK=0 P=43 Name=colon L=8 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=':'
```

A side-effect is that files with inline assembly using parentheses are identified as ObjC source files.

### PR DESCRIPTION
**Pull request by gedare**
Short-circuit the parsing of tok::colon to label colons found within lines starting with asm as InlineASMColon.

Fixes #92616.

### CODE REVIEW

**Comment by gedare** [comment]
With the patch:
```
$ echo " asm ( a : );" | clang-format -debug
...
 M=0 C=1 T=InlineASMColon S=1 F=0 B=0 BK=0 P=43 Name=colon L=7 PPK=2 FakeLParens= FakeRParens=1 II=0x0 Text=':'
...
$ echo " asm { a : };" | clang-format -debug
...
 M=0 C=1 T=InlineASMColon S=0 F=1 B=0 BK=0 P=43 Name=colon L=7 PPK=2 FakeLParens= FakeRParens=1 II=0x0 Text=':'
```

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -1358,6 +1358,8 @@ class AnnotatingParser {
           Line.First->startsSequence(tok::kw_export, Keywords.kw_module) ||
           Line.First->startsSequence(tok::kw_export, Keywords.kw_import)) {
         Tok->setType(TT_ModulePartitionColon);
+      } else if (Line.First->is(tok::kw_asm)) {
+        Tok->setType(TT_InlineASMColon);
```
Comment (owenca) [inline clang/lib/Format/TokenAnnotator.cpp:1362]: Does the `else if` block (lines 1430-1436) at the end of this `case tok::colon` become redundant now? It should be removed if yes.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -1489,11 +1489,25 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
 TEST_F(TokenAnnotatorTest, UnderstandsAsm) {
   auto Tokens = annotate("__asm{\n"
                          "a:\n"
-                         "};");
-  ASSERT_EQ(Tokens.size(), 7u) << Tokens;
+                         ": x\n"
+                         ":};");
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1493]: Is this real/valid assembly code?

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 3]
```diff
@@ -1489,11 +1489,25 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
-  EXPECT_TOKEN(Tokens[4], tok::r_brace, TT_InlineASMBrace);
+  EXPECT_TOKEN(Tokens[3], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[4], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[6], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[7], tok::r_brace, TT_InlineASMBrace);
+
+  Tokens = annotate("__asm__ volatile (\n"
+                    "a:\n"
+                    ": x\n"
+                    ":);");
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1505]: Same question here. Can we use an example from https://en.cppreference.com/w/c/language/asm instead? Also, please add a test for `asm(...)`.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 2 above)
Comment (gedare) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1493]: It's valid. The input, output, and clobber operands are a comma-separated list of C variables (or equivalently produced CPP macros), which may be empty.

File: clang/lib/Format/TokenAnnotator.cpp (hunk 1 above)
Comment (gedare) [reply clang/lib/Format/TokenAnnotator.cpp:1362]: Yes it appears to be redundant, I have refactored it out.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 3 above)
Comment (gedare) [reply clang/unittests/Format/TokenAnnotatorTest.cpp]: added a few tests for `asm`

File: clang/lib/Format/TokenAnnotator.cpp [hunk 4]
```diff
@@ -1426,12 +1428,9 @@ class AnnotatingParser {
...
       } else if (Contexts.back().ContextKind == tok::l_paren &&
-                 !Line.InPragmaDirective) {
-        if (Style.isTableGen() && Contexts.back().IsTableGenDAGArg) {
-          Tok->setType(TT_TableGenDAGArgListColon);
-          break;
-        }
-        Tok->setType(TT_InlineASMColon);
+                 !Line.InPragmaDirective && Style.isTableGen() &&
+                 Contexts.back().IsTableGenDAGArg) {
+        Tok->setType(TT_TableGenDAGArgListColon);
```
Comment (owenca) [inline clang/lib/Format/TokenAnnotator.cpp:1433]: I was thinking that this entire block could be deleted because `TT_TableGenDAGArgListColon` was already correctly set by now.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 5]
```diff
@@ -1488,12 +1488,91 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+                    "\"a\":\n"
+                    ": x\n"
+                    ":);");
+  ASSERT_EQ(Tokens.size(), 11u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[4], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[7], tok::colon, TT_InlineASMColon);
+
+  Tokens = annotate("__asm__ volatile (\n"
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1522]: Remove `volatile` to have a little more coverage.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 6]
```diff
@@ -1488,12 +1488,91 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+                    ":\n"
+                    ": x\n"
+                    ":);");
+  ASSERT_EQ(Tokens.size(), 11u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[4], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[7], tok::colon, TT_InlineASMColon);
+
+  Tokens = annotate("asm volatile (\n"
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1533]: Ditto.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 7]
```diff
@@ -1488,12 +1488,91 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+                    ":\n"
+                    ": x\n"
+                    ":);");
+  ASSERT_EQ(Tokens.size(), 11u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[4], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[7], tok::colon, TT_InlineASMColon);
+
+  Tokens = annotate("__asm__ volatile (\n"
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1544]: Use `__asm` instead.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 8]
```diff
@@ -1488,12 +1488,91 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+                    ":\n"
+                    ": x\n"
+                    ":);");
+  ASSERT_EQ(Tokens.size(), 12u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[6], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[8], tok::colon, TT_InlineASMColon);
+
+  Tokens = annotate("__asm__ volatile (\n"
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1556]:
```suggestion
  Tokens = annotate("__asm(\n"
```

File: clang/lib/Format/TokenAnnotator.cpp (hunk 4 above)
Comment (gedare) [reply clang/lib/Format/TokenAnnotator.cpp]: done, tests pass. @hnakamura5 any objections?
https://github.com/llvm/llvm-project/pull/92617/files#diff-f7c46dd11ab8379e248666096236ccfb4966e050f6494588cb9484c0e29d4e3dL1428

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 9]
```diff
@@ -1488,12 +1488,247 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+                    "\"a_label:\"\n"
+                    "\"a b c(%%x)\"\n"
+                    ":\n"
+                    ": x\n"
+                    ":);");
+  ASSERT_EQ(Tokens.size(), 12u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[6], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[8], tok::colon, TT_InlineASMColon);
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1644]: They look exactly the same.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 10]
```diff
@@ -1488,12 +1488,247 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
 
 TEST_F(TokenAnnotatorTest, UnderstandsAsm) {
   auto Tokens = annotate("__asm{\n"
-                         "a:\n"
-                         "};");
-  ASSERT_EQ(Tokens.size(), 7u) << Tokens;
+                         "\"a\":\n"
+                         ": x\n"
+                         ":};");
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1493]: Is the unquoted `a:` in assembly code invalid? If not, please add your test instead of editing the existing one.

**Review by owenca — COMMENTED** [review]
It seems that you used 5 different assembly snippets and repeated each 3-6 times. Instead, we can have something like the following:
```
asm{Snippet 1};

__asm(Snippet 2);

__asm__(Snippet 3);

asm volatile (Snippet 4);

__asm volatile (Snippet 5);
```
Also, no space between `tok::kw_asm` (i.e. `asm`, `__asm`, or `__asm__`) and `(`.

File: clang/lib/Format/TokenAnnotator.cpp (hunk 4 above)
Comment (hnakamura5) [reply clang/lib/Format/TokenAnnotator.cpp]: No objection. This seems redundant. Thank you for removing.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 10 above)
Comment (gedare) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1493]: AFAIK it's not valid, unless `a` is a CPP string.

**Comment by gedare** [comment]
> It seems that you used 5 different assembly snippets and repeated each 3-6 times. Instead, we can have something like the following:
> 
> ```
> asm{Snippet 1};
> 
> __asm(Snippet 2);
> 
> __asm__(Snippet 3);
> 
> asm volatile (Snippet 4);
> 
> __asm volatile (Snippet 5);
> ```
> 
> Also, no space between `tok::asm` (i.e. `asm`, `__asm`, or `__asm__`) and `(`.

done, thanks for the clarification

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 11]
```diff
@@ -1488,12 +1488,81 @@ TEST_F(TokenAnnotatorTest, RequiresDoesNotChangeParsingOfTheRest) {
...
+  Tokens = annotate("__asm__ volatile (\n"
+                    "\"ldr r1, [r0, %%[sym]]\"\n"
+                    ":\n"
+                    ": [sym] \"J\" (aaaaa(aaaa, aaaa))\n"
+                    ");");
+  ASSERT_EQ(Tokens.size(), 21u) << Tokens;
+  EXPECT_TOKEN(Tokens[0], tok::kw_asm, TT_Unknown);
+  EXPECT_TOKEN(Tokens[4], tok::colon, TT_InlineASMColon);
+  EXPECT_TOKEN(Tokens[5], tok::colon, TT_InlineASMColon);
 }
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1566]:
```suggestion
  EXPECT_TOKEN(Tokens[6], tok::colon, TT_InlineASMSymbolicNameLSquare);
}
```

**Review by owenca — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 11 above)
Comment (gedare) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1566]: There is no third colon in this test.

Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1566]: It’s an asm `l_square`.

Comment (gedare) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1566]: Nice. I shouldn't review comments on my phone.

**Review by owenca — APPROVED** [review]

**Review by hnakamura5 — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]
