### PR TITLE
[AMDGPU][MC] Allow null where 128b or larger dst reg is expected

### LINKED ISSUE #43058: [AMDGPU][MC][GFX10] null cannot be used with 128 bit and wider dst operands
|  |  |
| --- | --- |
| Bugzilla Link | [43713](https://llvm.org/bz43713) |
| Version | trunk |
| OS | Windows NT |
| CC | @atamazov,@arsenm |

## Extended Description 
Examples of failed tests:

  s_load_dwordx4  null, s[2:3], s0
  s_load_dwordx8  null, s[2:3], s0
  s_load_dwordx16 null, s[2:3], s0

### PR DESCRIPTION
**Pull request by jwanggit86**
For GFX10+, currently null cannot be used as dst reg in instructions that expect the dst reg to be 128b or larger (e.g., s_load_dwordx4). This patch fixes this problem while ensuring null cannot be used as S#, T#, or V#.

### CODE REVIEW

**Comment by jwanggit86** [comment]
@arsenm @jayfoad @mbrkusanin ping.

File: llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp [hunk 1]
```diff
@@ -9720,6 +9720,12 @@ unsigned AMDGPUAsmParser::validateTargetOperandClass(MCParsedAsmOperand &Op,
     // The following code enables it for SReg_64 operands
     // used as source and destination. Remaining source
     // operands are handled in isInlinableImm.
+    //
+    // Additionally, allow null where destination of 128-bit or larger is
+    // expected.
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp:9725]: This comment can merge with the above. It doesn't need to mention specific sizes, it "may be used anywhere scalar sources can normally be used"

File: llvm/test/MC/AMDGPU/gfx10_asm_smem.s [hunk 2]
```diff
@@ -281,6 +281,22 @@ s_load_dwordx16 s[20:35], s[2:3], 0x1234 glc dlc
 s_load_dwordx16 s[20:35], s[2:3], s0 offset:0x12345 glc dlc
 // GFX10: encoding: [0x01,0x45,0x11,0xf4,0x45,0x23,0x01,0x00]
 
+// null as dst
+s_load_dword null, s[2:3], s0
+// GFX10: encoding: [0x41,0x1f,0x00,0xf4,0x00,0x00,0x00,0x00]
+
+s_load_dwordx2 null, s[2:3], s0
+// GFX10: encoding: [0x41,0x1f,0x04,0xf4,0x00,0x00,0x00,0x00]
+
```
Comment (arsenm) [inline llvm/test/MC/AMDGPU/gfx10_asm_smem.s:290]: Test the dwordx3 case

File: llvm/test/MC/AMDGPU/gfx11_asm_smem.s [hunk 3]
```diff
@@ -239,6 +239,22 @@ s_load_b512 s[20:35], s[2:3], s0 glc dlc
 s_load_b512 s[20:35], s[2:3], 0x1234 glc dlc
 // GFX11: encoding: [0x01,0x65,0x10,0xf4,0x34,0x12,0x00,0xf8]
 
+// null as dst
+s_load_b32 null, s[2:3], s0
+// GFX11: encoding: [0x01,0x1f,0x00,0xf4,0x00,0x00,0x00,0x00]
+
+s_load_b64 null, s[2:3], s0
+// GFX11: encoding: [0x01,0x1f,0x04,0xf4,0x00,0x00,0x00,0x00]
+
```
Comment (arsenm) [inline llvm/test/MC/AMDGPU/gfx11_asm_smem.s:248]: Test the b96 case

File: llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp [hunk 4]
```diff
@@ -9720,6 +9720,12 @@ unsigned AMDGPUAsmParser::validateTargetOperandClass(MCParsedAsmOperand &Op,
...
+  case MCK_SReg_128:
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp:9726]: Missing the 96-bit case

**Review by arsenm — COMMENTED** [review]
Manual also states "NULL may not be used as an S#, V# or T#."

Can you add some mimg and mubuf/mtbuf cases? I don't think we can tell from just the operand that the use context is one of these

File: llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp (hunk 1 above)
Comment (jwanggit86) [reply llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp]: done.

File: llvm/test/MC/AMDGPU/gfx11_asm_smem.s (hunk 3 above)
Comment (jwanggit86) [reply llvm/test/MC/AMDGPU/gfx11_asm_smem.s:248]: b96 is not valid.

**Comment by jwanggit86** [comment]
> Manual also states "NULL may not be used as an S#, V# or T#."
> 
> Can you add some mimg and mubuf/mtbuf cases? I don't think we can tell from just the operand that the use context is one of these

Done.

File: llvm/test/MC/AMDGPU/gfx11_asm_smem.s (hunk 3 above)
Comment (jayfoad) [reply llvm/test/MC/AMDGPU/gfx11_asm_smem.s:248]: It's valid for for GFX12, so can you test it there?

File: llvm/lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp [hunk 5]
```diff
@@ -279,8 +279,11 @@ DECODE_OPERAND_REG_7(SReg_64_XEXEC, OPW64)
 DECODE_OPERAND_REG_7(SReg_64_XEXEC_XNULL, OPW64)
 DECODE_OPERAND_REG_7(SReg_96, OPW96)
 DECODE_OPERAND_REG_7(SReg_128, OPW128)
+DECODE_OPERAND_REG_7(SReg_128_XNULL, OPW128)
 DECODE_OPERAND_REG_7(SReg_256, OPW256)
+DECODE_OPERAND_REG_7(SReg_256_XNULL, OPW256)
 DECODE_OPERAND_REG_7(SReg_512, OPW512)
+DECODE_OPERAND_REG_7(SReg_512_XNULL, OPW512)
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp:286]: This one isn't used.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td [hunk 6]
```diff
@@ -910,22 +916,31 @@ multiclass SRegClass<int numRegs,
       let isAllocatable = 0;
       let BaseClassOrder = !mul(numRegs, 32);
     }
+
+    if hasNull then {
+      def SReg_ # suffix :
+        SIRegisterClass<"AMDGPU", regTypes, 32,
+                      !dag(add, [!cast<RegisterClass>("SReg_" # suffix # "_XNULL"), !cast<Register>("SGPR_NULL" # suffix)], ["", ""])> {
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.td:923]: What is the `["", ""]` for here?

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td [hunk 7]
```diff
@@ -809,6 +809,10 @@ def SReg_32 : SIRegisterClass<"AMDGPU", [i32, f32, i16, f16, bf16, v2i16, v2f16,
   let BaseClassOrder = 32;
 }
 
+def SGPR_NULL128 : SIReg<"null">;
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.td:812]: Nit: is there a good reason why this definition is so different from SGPR_NULL64? Maybe they can be commoned up a bit?

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td [hunk 8]
```diff
@@ -881,10 +885,12 @@ def SReg_1 : SIRegisterClass<"AMDGPU", [i1], 32,
   let HasSGPR = 1;
 }
 
+
 multiclass SRegClass<int numRegs,
                      list<ValueType> regTypes,
                      SIRegisterTuples regList,
                      SIRegisterTuples ttmpList = regList,
+                     bit hasNull = 0,
                      int copyCost = !sra(!add(numRegs, 1), 1)> {
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIRegisterInfo.td:894]: Not really related to your patch, but copyCost could be a defvar if no-one is setting it.

**Review by jayfoad — COMMENTED** [review]
Mostly looks good, thanks.

File: llvm/lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp (hunk 5 above)
Comment (jwanggit86) [reply llvm/lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp]: Removed in the latest commit. Thanks!

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td (hunk 6 above)
Comment (jwanggit86) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td]: The whole thing is to use the !dag operator to create a dag. The 2nd and 3rd arguments are lists with the same length. The 2nd list is a list of values while the 3rd the corresponding names. It seems that the names are not important. That's why they are blank. But in the latest commit, I replaced the two blank names with "RegClass" and "NullReg" respectively.

Using 128b as an example, this creates the dag (add SReg_128:"RegClass", SReg_128_XNULL:"NullReg").

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td (hunk 7 above)
Comment (jwanggit86) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td:812]: I was actually not very sure if this def is correct. SGPR_NULL64 is defined with 2 sub-regs. I wasn't sure if SGPR_128NULL should be defined similarly, and if so, what the sub-regs should be. On the other hand, changing SGPR_NULL64 to `def SGPR_NULL64: SIReg<"null">` would fail a lot of tests, possibly because SReg_64 is used when it should really be SReg_64_XNULL. Any suggestions are appreciated.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td (hunk 8 above)
Comment (jwanggit86) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td:892]: Agreed, but I think I'll leave it as is unless you think it should be fixed.

Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td:892]: It's fine to leave it as-is in this patch.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td (hunk 6 above)
Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td]: OK but I don't see why you need to use `!dag`. You can write it literally as `(add !cast<RegisterClass>("SReg_" # suffix # "_XNULL"), !cast<Register>("SGPR_NULL" # suffix))`.

File: llvm/lib/Target/AMDGPU/SIRegisterInfo.td (hunk 7 above)
Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIRegisterInfo.td:812]: I don't know why (or if) SGPR_NULL64 needs to have subregs. Maybe something to investigate later.

**Review by jayfoad — APPROVED** [review]
LGTM
