### PR TITLE
Make [[clang::lifetimebound]] work for expressions coming from default arguments

### LINKED ISSUE #68596: [[clang::lifetimebound]] doesn't work with default arguments
```cpp
const int& foo(const int& x [[clang::lifetimebound]] = 0) {
    return x;
}
int main() {
    const int& x = foo();  // No error
    return x;
}
```

### PR DESCRIPTION
**Pull request by higher-performance**
This is an attempt to fix #68596.

I'm very unfamiliar with this code, so it is very likely that I have made mistakes or overlooked a lot of things, especially things that might introduce unintended false-positives or false-negatives. CC @zygoloid

Please review carefully!

### CODE REVIEW

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 1]
```diff
@@ -532,6 +533,11 @@ static void visitLocalsRetainedByReferenceBinding(IndirectLocalPath &Path,
     }
   } while (Init != Old);
 
+  if (auto *DAE = dyn_cast<CXXDefaultArgExpr>(Init)) {
+    Path.push_back({IndirectLocalPathEntry::DefaultArg, DAE, DAE->getParam()});
+    Init = DAE->getExpr();
+  }
```
Comment (zygoloid) [inline clang/lib/Sema/CheckExprLifetime.cpp:539]: I think this should be in the loop above -- the default argument could itself contain one of the other expressions that we want to skip over.

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 2]
```diff
@@ -19,8 +19,10 @@ namespace usage_invalid {
 namespace usage_ok {
   struct IntRef { int *target; };
 
+  const int *defaultparam(const int &def1 [[clang::lifetimebound]] = 0); // #def1
   int &refparam(int &param [[clang::lifetimebound]]);
   int &classparam(IntRef param [[clang::lifetimebound]]);
+  const int *c = defaultparam(); // expected-warning {{temporary whose address is used as value of local variable 'c' will be destroyed at the end of the full-expression}} expected-note@#def1 {{default argument declared here}}
```
Comment (zygoloid) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:25]: This note doesn't seem very clear -- it's not obvious why you're pointing at a default argument or what it has to do with the diagnostic. You could copy what we do for `note_init_with_default_member_initializer` and add a note something like "initializing parameter with default argument" (which is still not great, but it's consistent and it at least shows why the default argument is relevant to the error).

**Review by zygoloid — COMMENTED** [review]
Thanks, this seems reasonable.

**Review by zygoloid — COMMENTED** [review]
Please can you also add tests for the case where the default argument is a pointer, eg:
```c++
using T = int[];
int *f([[clang::lifetimebound]] int *p = T{1, 2, 3});
int *p = f();
```
I expect that won't be caught, and you'll need to make a similar change to `visitLocalsRetainedByInitializer` to handle it.

**Comment by zygoloid** [comment]
> I expect that won't be caught, and you'll need to make a similar change to `visitLocalsRetainedByInitializer` to handle it.

Actually, maybe the best thing would be to change `visitFunctionCallArguments` to step over `CXXDefaultArgExpr` in `Args`. That should cover both cases, and the only place we should see a `CXXDefaultArgExpr` is at the top level in some form of function call.

**Comment by ilya-biryukov** [comment]
cc @usx95 @bricknerb who were looking at the lifetime annotations recently too.

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 3]
```diff
@@ -34,13 +38,20 @@ namespace usage_ok {
...
   int *r = A(1); // expected-warning {{temporary whose address is used as value of local variable 'r' will be destroyed at the end of the full-expression}}
+  A a = A(""); // expected-warning {{temporary whose address is used as value of local variable 'a' will be destroyed at the end of the full-expression}} expected-note@#def3 {{initializing parameter 'def3' with default argument}}
+  const int &s = A::defaulted_param(); // expected-warning {{temporary bound to local reference 's' will be destroyed at the end of the full-expression}} expected-note@#def4 {{initializing parameter 'def4' with default argument}}
+  const int &t = A::defaulted_param2(); // expected-warning {{temporary bound to local reference 't' will be destroyed at the end of the full-expression}} expected-note@#def4 {{initializing parameter 'def4' with default argument}} expected-note@#def5 {{initializing parameter 'def5' with default argument}}
+  const int &u = defaultparam_array(); // expected-warning {{temporary bound to local reference 'u' will be destroyed at the end of the full-expression}} expected-note@#def2 {{initializing parameter 'p' with default argument}}
```
Comment (usx95) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:54]: Can you also test 
1. valid cases
```cpp
int local;
const int &s = A::defaulted_param(local); // ok.
``` 
2. Use of temporary in default arguments.
`int s = A::defaulted_param(1); // bad.`

3. Assignment. It seems that this doesn't work even for non-default arguments (filed https://github.com/llvm/llvm-project/issues/112234). But we should still add a test with a FIXME.
`s = A::defaulted_param(1); // bad.`

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 4]
```diff
@@ -34,13 +38,20 @@ namespace usage_ok {
   struct A {
     A();
     A(int);
+    A(const char*, const int& def3 [[clang::lifetimebound]] = 0); // #def3
     int *class_member() [[clang::lifetimebound]];
     operator int*() [[clang::lifetimebound]];
+    static const int &defaulted_param(const int &def4 [[clang::lifetimebound]] = 0); // #def4
+    static const int &defaulted_param2(const int &def5 [[clang::lifetimebound]] = defaulted_param()); // #def5
```
Comment (usx95) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:45]: These tests are currently in `namespace usage_ok`.

Can you move to somewhere end of the file under a different namespace like `default_args`

**Comment by usx95** [comment]
Thanks for working on this. Mostly LG. Couple of nits and more ideas for tests.

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 5]
```diff
@@ -1370,7 +1381,7 @@ static void checkExprLifetimeImpl(Sema &SemaRef,
         break;
       }
 
-      case IndirectLocalPathEntry::LambdaCaptureInit:
+      case IndirectLocalPathEntry::LambdaCaptureInit: {
```
Comment (bricknerb) [inline clang/lib/Sema/CheckExprLifetime.cpp:1384]: Revert this change as it seems unrelated?

Comment (bricknerb) [inline clang/lib/Sema/CheckExprLifetime.cpp:1384]: Revert this change as it is unrelated?

File: clang/lib/Sema/CheckExprLifetime.cpp [hunk 6]
```diff
@@ -1383,6 +1394,15 @@ static void checkExprLifetimeImpl(Sema &SemaRef,
             << nextPathEntryRange(Path, I + 1, L);
         break;
       }
+
+      case IndirectLocalPathEntry::DefaultArg: {
+        const auto *DAE = cast<CXXDefaultArgExpr>(Elem.E);
+        SemaRef.Diag(DAE->getParam()->getDefaultArgRange().getBegin(),
+                     diag::note_init_with_default_argument)
+            << DAE->getParam() << nextPathEntryRange(Path, I + 1, L);
```
Comment (bricknerb) [inline clang/lib/Sema/CheckExprLifetime.cpp:1402]: Seems like we only care about DAE->getParam(), and use it twice, so consider introducing a variable for it instead or in addition to DAE.

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 7]
```diff
@@ -107,6 +107,39 @@ namespace std {
 using std::operator""s;
 using std::operator""sv;
 
+namespace default_args {
+  using IntArray = int[];
```
Comment (bricknerb) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:111]: Is this helpful if this is only used once?

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 8]
```diff
@@ -107,6 +107,39 @@ namespace std {
...
+  const int *defaultparam1(const int &def1 [[clang::lifetimebound]] = 0); // #def1
+  const int &defaultparam_array([[clang::lifetimebound]] const int *p = IntArray{1, 2, 3}); // #def2
+  struct A {
+    A(const char*, const int& def3 [[clang::lifetimebound]] = 0); // #def3
+  };
+  const int &defaultparam2(const int &def4 [[clang::lifetimebound]] = 0); // #def4
+  const int &defaultparam3(const int &def5 [[clang::lifetimebound]] = defaultparam2()); // #def5
+  std::string_view defaultparam4(std::string_view s [[clang::lifetimebound]] = std::string()); // #def6
+
+  const int*test_default_args() {
```
Comment (bricknerb) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:121]: Missing space before *

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 9]
```diff
@@ -107,6 +107,39 @@ namespace std {
 using std::operator""s;
 using std::operator""sv;
 
+namespace default_args {
+  using IntArray = int[];
+  const int *defaultparam1(const int &def1 [[clang::lifetimebound]] = 0); // #def1
+  const int &defaultparam_array([[clang::lifetimebound]] const int *p = IntArray{1, 2, 3}); // #def2
+  struct A {
+    A(const char*, const int& def3 [[clang::lifetimebound]] = 0); // #def3
```
Comment (bricknerb) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:115]: Missing space before * and & to be consistent with the rest of the code.

**Review by Xazax-hun — APPROVED** [review]
Some small nits inline, but it looks good to me.

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 10]
```diff
@@ -107,6 +107,39 @@ namespace std {
 using std::operator""s;
 using std::operator""sv;
 
+namespace default_args {
+  using IntArray = int[];
+  const int *defaultparam1(const int &def1 [[clang::lifetimebound]] = 0); // #def1
```
[the remark this answers is not in the document]
Comment (usx95) [reply clang/test/SemaCXX/attr-lifetimebound.cpp:112]: These look like source markers (instead of comment) which are referred by the error messages.

File: clang/test/SemaCXX/attr-lifetimebound.cpp [hunk 11]
```diff
@@ -107,6 +107,39 @@ namespace std {
...
+    const int &s = defaultparam2(); // expected-warning {{temporary bound to local reference 's' will be destroyed at the end of the full-expression}} expected-note@#def4 {{initializing parameter 'def4' with default argument}}
+    const int &t = defaultparam3(); // expected-warning {{temporary bound to local reference 't' will be destroyed at the end of the full-expression}} expected-note@#def4 {{initializing parameter 'def4' with default argument}} expected-note@#def5 {{initializing parameter 'def5' with default argument}}
+    const int &u = defaultparam_array(); // expected-warning {{temporary bound to local reference 'u' will be destroyed at the end of the full-expression}} expected-note@#def2 {{initializing parameter 'p' with default argument}}
+    int local;
+    const int &v = defaultparam2(local); // no warning
+    const int &w = defaultparam2(1); // expected-warning {{temporary bound to local reference 'w' will be destroyed at the end of the full-expression}}
+    int x = defaultparam2(1); // FIXME: This should warn
```
Comment (usx95) [inline clang/test/SemaCXX/attr-lifetimebound.cpp:130]: Ah, this is unfortunate. Filled https://github.com/llvm/llvm-project/issues/112349 for it.
(no action required)

File: clang/test/SemaCXX/attr-lifetimebound.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (Xazax-hun) [reply clang/test/SemaCXX/attr-lifetimebound.cpp:112]: Ah, my bad. Totally missed that.

**Comment by Xazax-hun** [comment]
Yup, feel free to merge it!

**Review by zygoloid — APPROVED** [review]
Thanks, looks good to me too.
