### PR TITLE
[flang][Semantics][OpenMP] Check type of reduction variables

### LINKED ISSUE #92440: [FLANG][OpenMP] Reduction of complex with logical operation causes ICE.
This program causes the compiler produce an internal error, when it ought to give an error at an earlier stage:
```
program main
  complex*8 a

  !$omp parallel reduction(.and. : a)
  !$omp end parallel
end program main
```

The error is:
```error: loc("/data/stuff/fortran/omp-complex-and.f90":4:9): 'fir.convert' op invalid type conversion
error: verification of lowering to FIR failed
```

### PR DESCRIPTION
**Pull request by tblah**
Fixes #92440

I had to delete part of reduction09.f90 because I don't think that should have ever worked.

### CODE REVIEW

File: flang/test/Lower/OpenMP/Todo/reduction-derived-type-field.f90 [hunk 1]
```diff
@@ -1,7 +1,8 @@
 ! RUN: %not_todo_cmd bbc -emit-fir -fopenmp -o - %s 2>&1 | FileCheck %s
 ! RUN: %not_todo_cmd %flang_fc1 -emit-fir -fopenmp -o - %s 2>&1 | FileCheck %s
 
-! CHECK: not yet implemented: Reduction of some types is not supported
+! THere's no definition of '+' for type(t)
```
Comment (tschuett) [inline flang/test/Lower/OpenMP/Todo/reduction-derived-type-field.f90:4]: Why `TH` and not `Th` ?

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 2]
```diff
@@ -2378,6 +2378,89 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
   return false;
 }
 
+static bool isReductionAllowedForType(
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2381]: All functions except accessors should be capitalized in Semantics.

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 3]
```diff
@@ -2378,6 +2378,89 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
...
+    const parser::OmpClause::Reduction &x, const DeclTypeSpec *type) {
+  assert(type && "no type for reduction symbol");
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2383]: Semantics uses a `CHECK()` macro.  But maybe you'd be better off passing a reference rather than a pointer.  Use `DEREF()` to check a pointer and turn it into a reference if you're confident that the pointer will never be null, even in an erroneous program.

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 4]
```diff
@@ -2378,6 +2378,89 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
...
+  const auto &definedOp{std::get<parser::OmpReductionOperator>(x.v.t)};
+  // TODO: user defined reduction operators. Just allow everything for now.
+  bool ok{true};
+
+  auto isLogical = [](const DeclTypeSpec *type) -> bool {
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2388]: Always use braced initialization, please.

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 5]
```diff
@@ -2378,6 +2378,89 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
...
+    return type->category() == DeclTypeSpec::Logical;
+  };
+  auto isCharacter = [](const DeclTypeSpec *type) -> bool {
+    return type->category() == DeclTypeSpec::Character;
+  };
+
+  common::visit(
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2395]: Perhaps you could abstract `CheckReduce()` in lib/Semantics/check-cuda.cpp and also use it here.

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 6]
```diff
@@ -2378,6 +2378,89 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
...
+              // Reduction identifier is not in OMP5.2 Table 5.2
+              default:
+                assert(false &&
+                    "This should have been caught in CheckIntrinsicOperator");
+                ok = false;
+                break;
+              }
+            }
+          },
+          [&](const parser::ProcedureDesignator &procD) {
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2436]: I'm surprised that the parse tree for OMP allows an arbitrary procedure designator here.

Comment (kiranchandramohan) [reply flang/lib/Semantics/check-omp-structure.cpp:2436]: Besides the allowed intrinsic procedures (max, min, iand, ior, ieor), for OpenMP the reduction identifier can be a base language identifier, or a user-defined operator. The latter appears as a ProcedureDesignator. We also had instances of renaming of intrinsics (https://github.com/llvm/llvm-project/issues/68654).

Comment (klausler) [reply flang/lib/Semantics/check-omp-structure.cpp:2436]: Sure, but can it be a procedure component or a procedure binding?

Comment (kiranchandramohan) [reply flang/lib/Semantics/check-omp-structure.cpp:2436]: I think they cannot be a procedure component or binding. Are you suggesting changing the reduction-identifier from a ProcedureDesignator to a Name for procedure-name?

Comment (klausler) [reply flang/lib/Semantics/check-omp-structure.cpp:2436]: So long as a procedure component or procedure binding is caught as an error somewhere in semantics, it doesn't need to be a parsing issue.  A `parser::Name` wouldn't be enough, I don't think, because operators are also acceptable.  If procedure components or procedure bindings are not caught in semantics, I suggest defining a new parse tree node and corresponding parser that are limited to what is allowed to appear only.

File: flang/lib/Semantics/check-omp-structure.cpp (hunk 5 above)
Comment (tblah) [reply flang/lib/Semantics/check-omp-structure.cpp:2395]: Thanks for the suggestion. The two functions are similar but not identical:
- No complex numbers in CUDA
- No subtract in CUDA (although perhaps we don't need to handle that here for OpenMP because it is currently a compiler error to use subtract anyway).
- OpenMP describes iand,ior,ieor,min, and max differently. The OpenMP 5.2 standard (5.5.1) does distinguish between operators and intrinsic procedure names, however I don't think there are any substantive differences between how these are treated.

@kiranchandramohan what do you think - would it be a good fit to change the representation to use `parser::ReductionOperator` instead of `parser::IntrinsicOperator` for these built in reduction operations, so that we can then refactor to share with the CUDA code? I think as a side effect this could let us use the existing array reduction machinery for `min` and `max` without additional work (other than tests).

Comment (kiranchandramohan) [reply flang/lib/Semantics/check-omp-structure.cpp:2394]: For builtin reductions it might be OK. At the parser level, it might not work for renames (https://github.com/llvm/llvm-project/issues/68654). In OpenMP is also user-defined declare reductions and reductions on user-defined operators.

Comment (tblah) [reply flang/lib/Semantics/check-omp-structure.cpp:2394]: Yeah we would have to keep the `ProcedureDesignator` (or similar) around, I just mean not using it for the built in reduction intrinsic procedures.

Comment (kiranchandramohan) [reply flang/lib/Semantics/check-omp-structure.cpp:2394]: Would that mean two different paths for a built-in reduction operation and its renamed version?

Comment (tblah) [reply flang/lib/Semantics/check-omp-structure.cpp:2394]: I guess it would yes. Maybe that makes this a bad idea.

**Comment by tblah** [comment]
@klausler is there anything more you would like to see changed here?

File: flang/lib/Semantics/check-omp-structure.cpp [hunk 7]
```diff
@@ -2378,6 +2378,88 @@ bool OmpStructureChecker::CheckIntrinsicOperator(
...
+                [[fallthrough]];
+              case parser::DefinedOperator::IntrinsicOperator::EQV:
+                [[fallthrough]];
+              case parser::DefinedOperator::IntrinsicOperator::NEQV:
+                ok = IsLogical(type);
+                break;
+
+              // Reduction identifier is not in OMP5.2 Table 5.2
+              default:
+                CHECK(false &&
```
Comment (klausler) [inline flang/lib/Semantics/check-omp-structure.cpp:2428]: `DIE("This should ... ");`

**Review by klausler — APPROVED** [review]

**Review by kiranchandramohan — APPROVED** [review]
LG.
