### PR TITLE
[flang][OpenMP] Add diagnostic for ATOMIC WRITE with pointer to non-intrinsic type

### LINKED ISSUE #161932: [Flang][OpenMP] verification of lowering to FIR failed on omp atomic write with pointer assignment to derived type
Reproducer:
https://godbolt.org/z/odGoe5Evq
```f90
type t
end type

type(t), pointer :: a1, a2

!$omp atomic write
a1 = a2
end
```

The expected behavior is that the code either compiles successfully or produces an appropriate and informative diagnostic.

### PR DESCRIPTION
**Pull request by KrxGu**
Fixes #161932

### Problem
When using `!$omp atomic write` with a POINTER variable to a derived type in intrinsic assignment, Flang would crash with a FIR verifier error instead of providing a clear semantic diagnostic.

**Example that previously crashed:**
```fortran
module p
    type t
    end type
    contains
    subroutine s(a1, a2)
        type(t), pointer :: a1, a2
        !$omp atomic write
        a1 = a2  ! Crashed with FIR verifier error
    end subroutine
end module
```
Solution
Added a semantic check in [CheckAtomicWriteAssignment()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) that detects when:

The assignment is an intrinsic assignment (not pointer assignment =>)
The variable has the POINTER attribute
The pointee type is non-intrinsic (derived type, character, etc.)
The check now emits a clear error message before reaching the FIR stage:
```error: ATOMIC WRITE requires an intrinsic scalar variable; 'a1' has the POINTER attribute and derived type 't'```

image

What remains valid
According to OpenMP 6.0 spec, the following cases are still allowed:

✅ integer, pointer :: p; p = 5 - pointer to intrinsic type with intrinsic assignment
✅ integer, pointer :: p, q; p => q - pointer assignment
✅ [type(t), pointer :: a, b; a => b](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) - pointer assignment with derived type
What is now rejected
❌ [type(t), pointer :: a, b; a = b](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) - intrinsic assignment where the dereferenced value is non-intrinsic

Testing
All existing atomic tests pass (15/15)
New test validates the error diagnostic
Verified the original crash scenario now produces a clear error instead

image

### CODE REVIEW

File: flang/lib/Semantics/check-omp-atomic.cpp [hunk 1]
```diff
@@ -539,7 +539,6 @@ void OmpStructureChecker::CheckAtomicType(
     return;
   }
 
-  // Variable is a pointer.
```
Comment (kparzysz) [inline flang/lib/Semantics/check-omp-atomic.cpp:542]: Unrelated change

File: flang/lib/Semantics/check-omp-atomic.cpp [hunk 2]
```diff
@@ -829,6 +828,32 @@ void OmpStructureChecker::CheckAtomicWriteAssignment(
   if (!IsVarOrFunctionRef(atom)) {
     ErrorShouldBeVariable(atom, rsrc);
   } else {
+    // For intrinsic assignment (x = expr), check if the variable is a pointer
+    // to a non-intrinsic type, which is not allowed in ATOMIC WRITE
```
Comment (kparzysz) [inline flang/lib/Semantics/check-omp-atomic.cpp:832]: This isn't specific to WRITE.  It should be checked in `CheckAtomicType`.

**Comment by kparzysz** [comment]
If you want to work on an issue that is already assigned to someone, at least let them know.

**Comment by KrxGu** [comment]
> If you want to work on an issue that is already assigned to someone, at least let them know.

Hi @kparzysz — apologies for the oversight🙏. I missed that this was already self-assigned to you. I’ll make sure to check assignments and coordinate with the assignee before picking up work in the future.

I’ve opened #162364 with a semantics fix and tests. If you feel it addresses the issue, please go ahead and merge it. If there are minor changes needed, I’m happy to make them quickly. Otherwise, if it’s not up to the mark or conflicts with your approach, I can close the PR. Your call, and thank you for the guidance.

**Review by kparzysz — APPROVED** [review]

**Comment by KrxGu** [comment]
> The commit message is too verbose, plus it contains outdated information. I plan to reduce it when merging. Let me know if you're ok with the text below.
> 
> Added a check for non-intrinsic types in non-pointer assignments.
> 
> Added bool checkTypeOnPointer = true to both CheckAtomicVariable and CheckAtomicType. All atomic assignment functions now pass !IsPointerAssignment(...) to control the check. The pointer-to-non-intrinsic check lives in CheckAtomicType, guarded by the checkTypeOnPointer flag. The check now applies uniformly to all atomic operations while properly excluding pointer assignments (=>).

@kparzysz Yes, SGTM - please go ahead with your version of the commit message. I appreciate you cleaning it up!
