### PR TITLE
[Clang][Concepts] Fix the constraint equivalence checking involving parameter packs

### LINKED ISSUE #101735: [Clang] `requires` clause with parameter pack expansion fails equivalence requirements for redeclarations
Upstream clang currently rejects the following program:
```
#include <concepts>
#include <utility>

template <typename T>
class A {
  template <typename... Ts>
  void method(Ts&... ts)
    requires requires (T t) {
      { t.method(std::forward<Ts>(ts)...) } -> std::same_as<void>;
    };
};

template <typename T>
template <typename... Ts>
void A<T>::method(Ts&... ts)
  requires requires (T t) {
    { t.method(std::forward<Ts>(ts)...) } -> std::same_as<void>;
  } {}
```
The error message is: 
```
test.cc:15:12: error: out-of-line definition of 'method' does not match any declaration in 'A<T>'
   15 | void A<T>::method(Ts&... ts)
      |            ^~~~~~
1 error generated.
```
After getting rid of the `std::forward<Ts>(ts)...`, the error went away. 
On an older clang (17-18) this caused a crash. GCC and MSVC accepted this program. 

See Godbolt for backtrace: https://godbolt.org/z/YoKM3bzvK

### PR DESCRIPTION
**Pull request by zyn0217**
We established an instantiation scope in order for constraint equivalence checking to properly map the uninstantiated parameters. 

That mechanism mapped even packs to themselves. Consequently, parameter packs e.g. appearing in a function call, were not expanded. So they would end up becoming `SubstTemplateTypeParmPackType`s that circularly depend on the canonical declaration of the function template, which is not yet determined, hence the spurious error.

No release note as I plan to backport it to 19.

Fixes https://github.com/llvm/llvm-project/issues/101735

### CODE REVIEW

**Comment by cor3ntin** [comment]
What's the status of that?

**Comment by zyn0217** [comment]
@mizvekov suggested in https://github.com/llvm/llvm-project/issues/101735#issuecomment-2273950029 we should try to decouple the constraint checking from the redeclaration chain building, however that is somehow involved.

File: clang/lib/Sema/SemaConcept.cpp [hunk 1]
```diff
@@ -972,8 +972,15 @@ static const Expr *SubstituteConstraintExpressionWithoutSatisfaction(
...
-      ScopeForParameters.InstantiatedLocal(PVD, PVD);
+    for (auto *PVD : FD->parameters()) {
+      if (!PVD->isParameterPack()) {
+        ScopeForParameters.InstantiatedLocal(PVD, PVD);
+        continue;
+      }
+      // Parameter packs should expand to a size-of-1 argument.
+      ScopeForParameters.MakeInstantiatedLocalArgPack(PVD);
+      ScopeForParameters.InstantiatedLocalPackArg(PVD, PVD);
+    }
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/Sema/SemaConcept.cpp:983]: Also, this new comment should be clearer here.

We are trying to create a no-transformation scope, so in the end there is no actual pack expansion going on here: We are expanding an unexpanded pack into an expansion of one unexpanded pack, so we are back where we started and nothing was expanded. So this looks like a clever hack which avoided creating the SubstTemplateTypeParmPackType through a loophole.

Since concepts make this a valid use case, we could explore improving this abstraction, for example creating some sort of NonInstantiation scope where you just have to register which declarations are in scope, but shouldn't transform them.

[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/lib/Sema/SemaConcept.cpp:983]: Actually, I think the better (future) approach here would be to ditch this scope and improve how FindInstantiatedDecl figures out which declarations should be part of the context being instantiated, and which are outside, so that it just naturally doesn't try to transform these declarations, just as for example it doesn't transform declarations at a template level above the context being instantiated.

[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:983]: Thanks for the suggestion; I’m offline and will add more comments when I get to my computer.

IIRC, this future improvement could also benefit noexcept specifier comparison as it also requires an instantiation scope that just indicates, “We know this declaration is not instantiated; just go on and leave it an uninstantiated state”

Isolating the declaration instantiation from a TreeTransform seems to have inconvenienced other things. Maybe that is what was designed for templates in the first place, but it becomes cumbersome for cases like this and CWG2369, etc, and we need the on-demand instantiation.

File: clang/lib/Sema/SemaConcept.cpp [hunk 2]
```diff
@@ -972,8 +972,30 @@ static const Expr *SubstituteConstraintExpressionWithoutSatisfaction(
...
+        continue;
+      }
+      // This is hacky: we're mapping the parameter pack to a size-of-1 argument
+      // to avoid building SubstTemplateTypeParmPackTypes for
+      // PackExpansionTypes. The SubstTemplateTypeParmPackType node would
+      // otherwise reference the AssociatedDecl of the template arguments, which
+      // is, in this case, the template declaration.
+      //
+      // However, as we're also calculating the redeclarations of the template,
+      // the canonical declarations thereof are actually themselves at the
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaConcept.cpp:987]:
```suggestion
      // However, as we are in the process of comparing potential re-declarations,
      // the canonical declaration is the declaration itself at this point.
```

File: clang/lib/Sema/SemaConcept.cpp [hunk 3]
```diff
@@ -972,8 +972,30 @@ static const Expr *SubstituteConstraintExpressionWithoutSatisfaction(
...
+      // moment. So if we didn't expand these packs, we would end up with an
+      // incorrect profile difference because we will be profiling the
+      // canonical types!
+      //
+      // FIXME: Improve the "no-transform" machinery in FindInstantiatedDecl so
+      // that we can eliminate the Scope in the cases where the declarations are
+      // not necessarily instantiated. It would also benefit the noexcept
+      // specifier comparison.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaConcept.cpp:995]: I wonder if we could temporarily pretend that the declarations are equivalent while checking their constraint so that their canonical type matches.
That way we could just do a normal parameter substitution, I think.
Or maybe @mizvekov solution would be better.

**Review by cor3ntin — APPROVED** [review]
LGTM. 
This fixes the bug, however we should explore a more robust solution

**Comment by cor3ntin** [comment]
should we rename `SubstituteConstraintExpressionWithoutSatisfaction` to make it clear it only works to compare them?

File: clang/lib/Sema/SemaConcept.cpp (hunk 3 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:995]: > I wonder if we could temporarily pretend that the declarations are equivalent while checking their constraint so that their canonical type matches.

I tried that approach in https://github.com/llvm/llvm-project/commit/0727e47124af564826a22a718a64a1da79e6131d. While it works, I don't think I like it quite much because it looks unnatural/dirty to me.

**Comment by zyn0217** [comment]
> should we rename SubstituteConstraintExpressionWithoutSatisfaction to make it clear it only works to compare them?

Good idea. How about `SubstituteConstraintExpressionForEquivalenceChecking` then? We can rename it in the next PR.

File: clang/lib/Sema/SemaConcept.cpp (hunk 3 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaConcept.cpp:995]: I think both approach are equally... in search of a better 3rd approach :D
I like the Decl approach because it doesn't mess too much with substitution at all, the only thing that should be affected is profiling. So I am somewhat more confident about its correctness, if that makes sense.
 
Any preference @mizvekov ?

Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:995]: > the only thing that should be affected is profiling.

Hmm, I see your point...

Comment (mizvekov) [reply clang/lib/Sema/SemaConcept.cpp:995]: I think the solution in this patch improves on the existing one, even if interim, as the idea is to not have TransformDecl change these inserted declarations at all, which we failed to do for packs. So I like it more, as it just adds to existing workarounds, instead of adding a new one.
