### PR TITLE
[clang-tidy] Add handling of type aliases in `use-designated-initializers` check

### LINKED ISSUE #150782: [clang-tidy] modernize-use-designated-initializers fails to detect missing designated initializers
clang-tidy fails to detect missing designated initializers if the data structure is defined via `using MyTypeT =  MyType<T>`
```
template<typename T>
struct Foo {
    T aaaaa;
    T bbbbb;
};

using Foo32u = Foo<uint32_t>;

void myFun() {
    const Foo<uint32_t> f1{1,2};
    const Foo32u f2{1,2};
}
```

clang-tidy correctly detects the missing designated initializers in  `const Foo<uint32_t> f1{1,2};` but it misses them in `const Foo32u f2{1,2};`:

```
 warning: use designated initializer list to initialize 'Foo<unsigned int>' [modernize-use-designated-initializers]
   44 |     const Foo<uint32_t> f1{1,2};
      |                           ^~~~~
      |                            .aaaaa= .bbbbb=
```

Environment:
```
Homebrew LLVM version 20.1.8
  Optimized build.
```

```
CheckOptions:
  modernize-use-designated-initializers.IgnoreMacros: true
  modernize-use-designated-initializers.IgnoreSingleElementAggregates: true
  modernize-use-designated-initializers.RestrictToPODTypes: true
  modernize-use-designated-initializers.StrictCStandardCompliance: true
  modernize-use-designated-initializers.StrictCppStandardCompliance: true
```

### PR DESCRIPTION
**Pull request by SimplyDanny**
Resolves #150782.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp [hunk 1]
```diff
@@ -224,3 +224,22 @@ std::array a{1,2,3};
...
 array c{10, 11};
+
+struct S16 {
+    int a;
+    int b;
+};
+
+using S17 = S16;
+
+S17 s171{1, 2};
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:235]: Just to double check, there are no fix-its for aliases?

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp [hunk 2]
```diff
@@ -224,3 +224,22 @@ std::array a{1,2,3};
 std::array<int,2> b{10, 11};
 using array = std::array<int, 2>;
 array c{10, 11};
+
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:227]: Please add tests with:

- alias with all fields using designated-init
- alias with some field using designated-init

**Review by vbvictor — COMMENTED** [review]
Please add release notes and check name in PR title like "Add handling of type aliases in use-designated-initializers"

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp (hunk 1 above)
Comment (SimplyDanny) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:235]: There are. It's just that the test infrastructure doesn't require them.

Added them ...

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp (hunk 2 above)
Comment (SimplyDanny) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:227]: Done. Can you think of even more test cases?

Comment (vbvictor) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:227]: I think this still needs case like `S18 s183{.a=1, .b=2} // no warning at all`
Probably good to have one nested like
```cpp
struct S20 {
    int i;
    S17 s;
};

S20 s201 {1, 2};
```

**Review by vbvictor — APPROVED** [review]
LGTM
