### PR TITLE
[HLSL][Sema] Validate that occupied register numbers never exceed UINT32_MAX

### LINKED ISSUE #136809: [HLSL] Report error when register binding range overflows UINT32_MAX value
The compiler should report an error when the upper bound of register binding is larger than UINT32_MAX:

```
RWBuffer<float> Buf[10] : register(u4294967294); // UINT32_MAX - 1

[numthreads(1, 1, 1)]
void main() {
  Buf[1][0] = 0;
}
```
https://godbolt.org/z/KM3fPoY74

**Current behavior:**
Clang with `-Od` ignores the binding (resource is not bound).
Clang without `-Od` crashes in `OpLowerer`.
DXC does not report an error if the register range starts at `UINT32_MAX - 1` and it overflows the register slot.
DXC with register range starting at `UINT32_MAX` ignores the binding and assigns the resource `u0`.

### PR DESCRIPTION
**Pull request by bob80905**
This PR adds validation for register numbers.
Register numbers ought never to exceed UINT32_MAX, or 4294967295
Additionally, resource arrays will have each resource element bound sequentially, and those resource's register numbers should not exceed UINT32_MAX, or 4294967295. Even though not explicitly given a register number, their effective register number is also validated.
This accounts for nested resource declarations and resource arrays too.

Fixes https://github.com/llvm/llvm-project/issues/136809

### CODE REVIEW

File: clang/lib/Sema/SemaHLSL.cpp [hunk 1]
```diff
@@ -2361,6 +2361,99 @@ static bool DiagnoseHLSLRegisterAttribute(Sema &S, SourceLocation &ArgLoc,
   return ValidateMultipleRegisterAnnotations(S, D, RegType);
 }
 
+bool ExceedsUInt32Max(llvm::StringRef S) {
+  constexpr size_t MaxDigits = 10; // UINT32_MAX = 4294967295
+  if (S.size() > MaxDigits)
+    return true;
+
+  if (S.size() < MaxDigits)
+    return false;
```
Comment (damyanp) [inline clang/lib/Sema/SemaHLSL.cpp]: Is there a reason for all this MaxDigits stuff?  It seems redundant with other ways we can check if it is an in-range integer.

File: clang/lib/Sema/SemaHLSL.cpp [hunk 2]
```diff
@@ -2361,6 +2361,99 @@ static bool DiagnoseHLSLRegisterAttribute(Sema &S, SourceLocation &ArgLoc,
...
+
+  // Case 1: array type
+  if (const auto *AT = dyn_cast<ArrayType>(T)) {
+    uint64_t Count = 1;
+
+    if (const auto *CAT = dyn_cast<ConstantArrayType>(AT)) {
+      Count = CAT->getSize().getZExtValue();
+    }
+    // TODO: how do we handle non constant resource arrays?
```
[the remark this answers is not in the document]
Comment (damyanp) [reply clang/lib/Sema/SemaHLSL.cpp]: Ah, ok, those are unbounded resource arrays. Really the compiler can only validate that against the root signature - and while it could it seems that neither clang nor DXC does: https://godbolt.org/z/r54neEsqz

IMO we should remove the TODO and file an issue with some repros.

File: clang/lib/Sema/SemaHLSL.cpp [hunk 3]
```diff
@@ -2361,6 +2361,78 @@ static bool DiagnoseHLSLRegisterAttribute(Sema &S, SourceLocation &ArgLoc,
...
+  if (T->isHLSLResourceRecord()) {
+
+    SlotCount += Multiplier;
+    return SlotCount <= Limit;
+  }
+
+  // Case 3: struct / record
+  if (const auto *RT = dyn_cast<RecordType>(T)) {
+    const RecordDecl *RD = RT->getDecl();
+    for (const FieldDecl *Field : RD->fields()) {
```
Comment (inbelic) [inline clang/lib/Sema/SemaHLSL.cpp]: nit:
```suggestion
    for (const FieldDecl *Field : RD->fields())
```

**Review by inbelic — APPROVED** [review]

File: clang/lib/Sema/SemaHLSL.cpp [hunk 4]
```diff
@@ -2361,6 +2361,94 @@ static bool DiagnoseHLSLRegisterAttribute(Sema &S, SourceLocation &ArgLoc,
   return ValidateMultipleRegisterAnnotations(S, D, RegType);
 }
 
+// return false if the slot count exceeds the limit, true otherwise
+static bool AccumulateHLSLResourceSlots(QualType Ty, uint64_t &SlotCount,
+                                        const uint64_t &Limit, ASTContext &Ctx,
+                                        uint64_t Multiplier = 1) {
```
Comment (tex3d) [inline clang/lib/Sema/SemaHLSL.cpp]: It seems to me that `SlotCount` is really like `StartSlot`, and `Multiplier` is really like `ArrayCount`.

File: clang/test/SemaHLSL/resource_binding_attr_error_uint32_max.hlsl [hunk 5]
```diff
@@ -0,0 +1,56 @@
+// RUN: %clang_cc1 -triple dxil-pc-shadermodel6.3-library -x hlsl -o - -fsyntax-only %s -verify
+
+// test semantic validation for register numbers that exceed UINT32_MAX
+
+struct S {
+  RWBuffer<float> A[4];
+  RWBuffer<int> B[10];
```
Comment (tex3d) [inline clang/test/SemaHLSL/resource_binding_attr_error_uint32_max.hlsl]: You'll want to test with multiple resource classes in same struct, and multiple register bindings (for each class) on the corresponding decl.

File: clang/lib/Sema/SemaHLSL.cpp [hunk 6]
```diff
@@ -2361,6 +2361,121 @@ static bool DiagnoseHLSLRegisterAttribute(Sema &S, SourceLocation &ArgLoc,
...
+
+    SlotNumStr.getAsInteger(10, Result);
+    return false;
+  }
+  // handle the cbuffer case
+  if (dyn_cast<HLSLBufferDecl>(TheDecl)) {
+    // resources cannot be put within a cbuffer, so no need
+    // to analyze the structure since the register number
+    // won't be pushed any higher.
+    if (SlotNum > Limit)
```
Comment (tex3d) [inline clang/lib/Sema/SemaHLSL.cpp]: I think we should probably have a `ResourceType` check here.  `b` for `cbuffer` and `t` for `tbuffer`.

Also, I wondered what would happen if the wrong type is specified, but the closest case in the test seems to be this:
```
cbuffer b : register(i0) {
```
Which is a legacy int register assignment that only would have applied to variable decls anyway. It seems like we should reject any register type other than `b`. If we already have that diagnostic, good, but I think the test needs a few more cases to show it. I wonder what happens when someone uses `c0`, as this is a common mistake (only applies to variable decls in `$Globals` for assigning locations).

Comment (tex3d) [reply clang/lib/Sema/SemaHLSL.cpp]: Ok.

Regarding the test, the additions look good, though I'm wondering if there's another place that catches these cases too:
```
cbuffer CB : register(t0) { ... }
tbuffer TB : register(b0) { ... }
```
They are both `HLSLBufferDecl`, but the binding type is mismatched. I don't see this in the test, but perhaps there's another test for this already.

Comment (tex3d) [reply clang/lib/Sema/SemaHLSL.cpp]: I see that SemaHLSL.cpp:2258 should diagnose this case, but I didn't see the test. Not the responsibility of this PR, but seems like it could be easy to add.

**Review by tex3d — APPROVED** [review]
LGTM, thanks!
