### PR TITLE
[clang][modules] Fix false positive -Wweak-vtables in named modules

### LINKED ISSUE #193004: `Wweak-vtables` should not trigger in a module
Given the following translation unit

```c++
export module m;

struct s {
	virtual void f() {
	}
};
```

clang warns

```console
<source>:3:8: warning: 's' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Wweak-vtables]
    3 | struct s {
      |        ^
1 warning generated.
Compiler returned: 0
```

I expect no warnings in this case.

See it live: https://godbolt.org/z/djvjMv8z1

Related: https://github.com/llvm/llvm-project/issues/62465

### PR DESCRIPTION
**Pull request by davidmenggx**
The -Wweak-vtables warning was incorrectly firing for classes defined in C++20 module units. This warning does not apply to module units as the vtable should be owned by the module and emitted only once.

Fixes #193004

### CODE REVIEW

**Comment by davidmenggx** [comment]
@ChuanqiXu9 could you please take a look at this?

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -19274,7 +19269,8 @@ bool Sema::DefineUsedVTables() {
     // no key function or the key function is inlined. Don't warn in C++ ABIs
     // that lack key functions, since the user won't be able to make one.
     if (Context.getTargetInfo().getCXXABI().hasKeyFunctions() &&
-        Class->isExternallyVisible() && ClassTSK != TSK_ImplicitInstantiation &&
+        Class->isExternallyVisible() && !Class->isInCurrentModuleUnit() &&
```
Comment (ChuanqiXu9) [inline clang/lib/Sema/SemaDeclCXX.cpp]: We should use 'Class->getOwningModule() && Class->getOwningModule()->isInterfaceOrPartition()'

**Review by ChuanqiXu9 — APPROVED** [review]
