### PR TITLE
[clang-format] Fix regression in BAS_AlwaysBreak for-await

### LINKED ISSUE #108589: Regression when formatting around `for` condition
formatted with `clang-format -style=Google a.ts`

actual formatting:
```
for await (
    const packageId of ops.api.iterateEmbeddedFiles(
        this.getFileId().getDriveFile(),
        )) {
}
```

expected formatting:
```
for await (const packageId of ops.api.iterateEmbeddedFiles(
    this.getFileId().getDriveFile(),
    )) {
}
```

### PR DESCRIPTION
**Pull request by gedare**
Fixes #108589.

### CODE REVIEW

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 1]
```diff
@@ -809,7 +809,7 @@ void ContinuationIndenter::addTokenOnCurrentLine(LineState &State, bool DryRun,
     if (Tok.Previous->isIf())
       return Style.AlignAfterOpenBracket == FormatStyle::BAS_AlwaysBreak;
     return !Tok.Previous->isOneOf(TT_CastRParen, tok::kw_for, tok::kw_while,
-                                  tok::kw_switch);
+                                  tok::kw_switch, Keywords.kw_await);
```
Comment (owenca) [inline clang/lib/Format/ContinuationIndenter.cpp:812]:
```suggestion
                                  tok::kw_switch) &&
           !(Style.isJavaScript() && Tok.Previous->is(Keywords.kw_await));
```
as `await` is not a keyword in C++, Java, etc.

**Review by owenca — APPROVED** [review]

**Review by mydeveloperday — APPROVED** [review]
