### PR TITLE
[lldb] Support true/false in ValueObject::SetValueFromCString

### LINKED ISSUE #112597: Cannot change boolean variable with lldb-dap
To change the value of a boolean variable, lldb-dap rejects `true` and `false` and makes you use `0` and `1`. 

Using `false`: 
```
{"command":"setVariable","arguments":{"variablesReference":24,"name":"m_is_file","value":"false"},"type":"request","seq":27}
{"body":{"message":"'false' is not a valid integer string value"},"command":"setVariable","request_seq":27,"seq":0,"success":false,"type":"response"}
```

Use `1`:
```
{"command":"setVariable","arguments":{"variablesReference":24,"name":"m_is_file","value":"1"},"type":"request","seq":30}
{"body":{"type":"bool","value":"true","variablesReference":0},"command":"setVariable","request_seq":30,"seq":0,"success":true,"type":"response"}
```

I'm not sure if this is really an lldb-dap issue or `SBValue::SetValueFromCString` doing the wrong thing.

### PR DESCRIPTION
**Pull request by JDevlieghere**
Support "true" and "false" (and "YES" and "NO" in Objective-C) in ValueObject::SetValueFromCString.

Fixes #112597

### CODE REVIEW

File: lldb/test/API/functionalities/data-formatter/setvaluefromcstring/main.m [hunk 1]
```diff
@@ -2,10 +2,15 @@
...
     NSLog(@"hello world"); //% dic = self.frame().FindVariable("dic")
     //% dic.SetPreferSyntheticValue(True)
     //% dic.SetPreferDynamicValue(lldb.eDynamicCanRunTarget)
     //% dic.SetValueFromCString("12")
+    //% b = self.frame().FindVariable("b")
+    //% b.SetValueFromCString("YES")
     return 0; //% dic = self.frame().FindVariable("dic")
-    //% self.assertTrue(dic.GetValueAsUnsigned() == 0xC, "failed to read what I wrote")
+    //% self.assertTrue(dic.GetValueAsUnsigned() == 0xC, "failed to read what I
+    //wrote") % b = self.frame().FindVariable("b") %
```
Comment (bulbazord) [inline lldb/test/API/functionalities/data-formatter/setvaluefromcstring/main.m:14]: Is the formatting here correct? Looks like one line spans two.

Comment (JDevlieghere) [reply lldb/test/API/functionalities/data-formatter/setvaluefromcstring/main.m:14]: I think `black` messed that up. Let me fix it and see what the tool says.

**Review by bulbazord — APPROVED** [review]

**Review by jimingham — APPROVED** [review]
LGTM
