### PR TITLE
[libc++] Fix input-only range handling for `vector`

### LINKED ISSUE #115727: [libcxx]: `__uninitialized_allocator_copy` misses `std::move` before calling `__unwrap_range`
https://github.com/llvm/llvm-project/blob/4c4db3c943d686ff7c1fcf2dbc975e8462497efe/libcxx/include/__memory/uninitialized_algorithms.h#L585-L592

testcase:
```cpp
#include <sstream>
#include <vector>
#include <ranges>
 
int main() {
  auto is = std::istringstream{"1 2 3 4"};
  auto ints = std::views::istream<int>(is);
  std::vector v(std::from_range, std::views::counted(ints.begin(), 3));
}
```
https://godbolt.org/z/rjWeqdPj1

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Changes:
- Carve out sized but input-only ranges for C++23.
- Call `std::move` for related functions when the iterator is possibly input-only.

Fixes #115727.

### CODE REVIEW

File: libcxx/include/__vector/vector.h [hunk 1]
```diff
@@ -1011,23 +1017,31 @@ vector<_Tp, _Allocator>::__assign_with_sentinel(_Iterator __first, _Sentinel __l
...
   if (__new_size <= capacity()) {
     if (__new_size > size()) {
-      _ForwardIterator __mid = std::next(__first, size());
-      std::copy(__first, __mid, this->__begin_);
-      __construct_at_end(__mid, __last, __new_size - size());
+#if _LIBCPP_STD_VER >= 23
+      if constexpr (!forward_iterator<_Iterator>) {
+        auto __mid = ranges::copy_n(std::move(__first), size(), this->__begin_).in;
+        __construct_at_end(std::move(__mid), std::move(__last), __new_size - size());
+      } else
```
Comment (ldionne) [inline libcxx/include/__vector/vector.h:1030]: This trailing `else` is really confusing IMO! I think you can do this instead:

```c++
#if _LIBCPP_STD_VER >= 23
if constexpr (!forward_iterator<_Iterator>) {
  auto __mid = ranges::copy_n(std::move(__first), size(), this->__begin_).in;
  __construct_at_end(std::move(__mid), std::move(__last), __new_size - size());
  return;
}
#endif

// not under any else
_Iterator __mid = std::next(__first, size());
std::copy(__first, __mid, this->__begin_);
__construct_at_end(__mid, __last, __new_size - size());
```

Actually, is there a reason why we don't do this instead?

```c++
#if _LIBCPP_STD_VER >= 23
auto __mid = ranges::copy_n(std::move(__first), size(), this->__begin_).in;
__construct_at_end(std::move(__mid), std::move(__last), __new_size - size());
#else
_Iterator __mid = std::next(__first, size());
std::copy(__first, __mid, this->__begin_);
__construct_at_end(__mid, __last, __new_size - size());
#endif
```

IOW, I don't see why we can't use `ranges::copy_n` regardless of the iterator category in C++23.

**Review by ldionne — COMMENTED** [review]
Thanks a lot for the patch! I'd like to find ways to minimize the intermixing of `#ifdef` and `if constexpr` since that leads to IMO really difficult to read code.

File: libcxx/include/__vector/vector.h (hunk 1 above)
Comment (frederick-vs-ja) [reply libcxx/include/__vector/vector.h]: > This trailing `else` is really confusing IMO! I think you can do this instead:
> 
> ```c++
> #if _LIBCPP_STD_VER >= 23
> if constexpr (!forward_iterator<_Iterator>) {
>   auto __mid = ranges::copy_n(std::move(__first), size(), this->__begin_).in;
>   __construct_at_end(std::move(__mid), std::move(__last), __new_size - size());
>   return;
> }
> #endif
> 
> // not under any else
> _Iterator __mid = std::next(__first, size());
> std::copy(__first, __mid, this->__begin_);
> __construct_at_end(__mid, __last, __new_size - size());
> ```

Oh, we can't, because the "else" branch needs to be discarded for input-only iterators.

----

> Actually, is there a reason why we don't do this instead?
> 
> ```c++
> #if _LIBCPP_STD_VER >= 23
> auto __mid = ranges::copy_n(std::move(__first), size(), this->__begin_).in;
> __construct_at_end(std::move(__mid), std::move(__last), __new_size - size());
> #else
> _Iterator __mid = std::next(__first, size());
> std::copy(__first, __mid, this->__begin_);
> __construct_at_end(__mid, __last, __new_size - size());
> #endif
> ```
> 
> IOW, I don't see why we can't use `ranges::copy_n` regardless of the iterator category in C++23.

Thanks! I think this should work.

**Review by ldionne — APPROVED** [review]
