### PR TITLE
[lldb-dap] Fix: disableASLR launch argument not working.

### LINKED ISSUE #94338: LLDB-DAP in VSC doesn't respect `"disableASLR": false` unless you also do `settings set target.disable-aslr false`
When you try to debug in Docker using LLDB-DAP, by default it fails because it's unable to disable the ASLR.

Adding `"disableASLR": false,` to `launch.json` is supposed to fix it, but currently you need **both** that and `"initCommands": ["settings set target.disable-aslr false"],` for it to work.

Ideally the former should be enough (or if either one worked, that would be perfect). I could swear that the former was enough at some point (maybe when I was using v0.2.0 VSC extension I compiled myself, while now I'm using v0.2.1 from the marketplace).

I'm using `lldb-dap-18` v18.1.3 from apt.llvm.org on Ubuntu 22.04.

### PR DESCRIPTION
**Pull request by da-viper**
Fixes #94338 

https://github.com/user-attachments/assets/8a8bdd27-e476-4b6a-976d-7b1e4947c692

i used `pidof a.out | xargs pmap` to show the memory map of the binary

### CODE REVIEW

**Review by JDevlieghere — COMMENTED** [review]
I'd like to suggest two improvements:

1. Add an overload to `GetBoolean` that returns an `std::optional<bool>` so we know if the value was not set, or explicitly set to `true` or `false`.
2. Have a helper that does the same thing for all the flags: set or clear it depending on whether the value was set, or do nothing if it wasn't set. 

WDYT?

**Comment by Da-Viper** [comment]
> I'd like to suggest two improvements:
> 
> 1. Add an overload to `GetBoolean` that returns an `std::optional<bool>` so we know if the value was not set, or explicitly set to `true` or `false`.
> 2. Have a helper that does the same thing for all the flags: set or clear it depending on whether the value was set, or do nothing if it wasn't set.
> 
> WDYT?

1. I am note sure if it is useful since the boolean will have to be either true or false. 

2. Will the helper functions be scoped to the `RequestHandler.cpp` class. something like 

```cpp

   SetMask(uint32_t &flags, LaunchInfo mask);
   ClearMask(uint32_t &flags, LaunchInfo mask);

```

**Comment by JDevlieghere** [comment]
> 1. I am not sure if it is useful since the boolean will have to be either true or false.

Okay, just to confirm, you're saying that's it's not possible for these values not to be set? 

> 2. Will the helper functions be scoped to the `RequestHandler.cpp` class and be something like

I was thinking something like:

```
SetLaunchFlag(llvm::StringRef key, uint32_t flag, bool default) {
    if (GetBoolean(arguments, key, default))
     flags |= flag;
   else
     flags &= ~flag;
}
// Used like this:
SetLaunchFlag("disableASLR", lldb::eLaunchFlagDisableASLR, true);
SetLaunchFlag("disableSTDIO", lldb::eLaunchFlagDisableSTDIO, false);
```

**Comment by Da-Viper** [comment]
> Okay, just to confirm, you're saying that's it's not possible for these values not to be set?

Yes because lldb has default values for all its settings. using `settings show ...`.
Also internally when fetching a value for the first time it uses a predefined default if it is not set.

see 
https://github.com/llvm/llvm-project/blob/a12744ff05bbc2d0de711afb8b3a1c7a03a33914/lldb/source/Target/TargetProperties.td#L143-L145

**Comment by walter-erquinigo** [comment]
I kind of agree with Jonas' initial remark. Wouldn't it be better to conceptually have something like this:

```
if (HasBoolean(arguments, key)) {
  if (GetBoolean(arguments, key))
     flags |= flag;
   else
     flags &= ~flag;
}
```

that way you can let LLDB set the flag value on its own. An interesting case when this might be useful is if one of the initCommands sets the default value for this setting, then you don't want to change this unless the disableASLR field in the debug config is set explicitly

**Comment by Da-Viper** [comment]
Alright. 

One more thing if it is better to return a flag from function or pass a reference.

```cpp
static setLaunchFlag(uint32_t &flags, const llvm::json::Object *obj,
                              llvm::StringRef key, lldb::LaunchFlags mask,
                              bool default_value) {
  if (HasBoolean(obj, key))
    if (GetBoolean(obj, key, default_value))
      flags |= mask;
    else
      flags &= ~mask;
}

setLaunchFlag(flags, arguments, "disableASLR",
                        lldb::eLaunchFlagDisableASLR, false);
```

```cpp

static uint32_t setLaunchFlag(uint32_t flags, const llvm::json::Object *obj,
                              llvm::StringRef key, lldb::LaunchFlags mask,
                              bool default_value) {
  if (HasBoolean(obj, key))
    if (GetBoolean(obj, key, default_value))
      flags |= mask;
    else
      flags &= ~mask;

  return flags;
}

flags = setLaunchFlag(flags, arguments, "disableASLR",
                        lldb::eLaunchFlagDisableASLR, false);

```

**Comment by JDevlieghere** [comment]
I don't think we need to have both the `HasBoolean` and `GetBoolean`. I think we should rewrite `GetBoolean` from this:

```
bool GetBoolean(const llvm::json::Object &obj, llvm::StringRef key,
                bool fail_value) {
  if (auto value = obj.getBoolean(key))
    return *value;
  if (auto value = obj.getInteger(key))
    return *value != 0;
  return fail_value;
}
```

to this:

```
std::optional<bool> GetBoolean(const llvm::json::Object &obj, llvm::StringRef key) {
    if (auto value = obj.getBoolean(key))
    return *value;
  if (auto value = obj.getInteger(key))
    return *value != 0;
  return std::nullopt;
}
```

All existing uses of `GetBoolean(obj, key, fail_value)` can be rewritten as `GetBoolean(obj, key).value_or(fail_value)`. 

FWIW this applies to all the `GetFoo` helpers in `JSONUtils.cpp`, but obviously that should be a separate PR and I'm not trying to sign up for that work. I think we can add the overload for `GetBoolean` as part of this PR and cleanup the rest in another one.

**Comment by walter-erquinigo** [comment]
Oh yes, I completely agree with `std::optional<bool>` being the best choice. My example was just something conceptual and easy to read.
And indeed, as you say, all the fields should return an optional because the client just sends a blob of JSON and you can't make any guarantees on whether it makes sense or not.

**Review by walter-erquinigo — CHANGES_REQUESTED** [review]
requesting changes given the existing discussion

**Comment by Da-Viper** [comment]
Different timezone, updated the commit with the new changes.

File: lldb/tools/lldb-dap/Handler/RequestHandler.cpp [hunk 1]
```diff
@@ -32,12 +32,12 @@ MakeArgv(const llvm::ArrayRef<std::string> &strs) {
...
 static uint32_t SetLaunchFlag(uint32_t flags, const llvm::json::Object *obj,
-                              llvm::StringRef key, lldb::LaunchFlags mask,
-                              bool default_value) {
-  if (GetBoolean(obj, key).value_or(default_value))
-    flags |= mask;
-  else
-    flags &= ~mask;
+                              llvm::StringRef key, lldb::LaunchFlags mask) {
+  if (const auto opt_value = GetBoolean(obj, key))
+    if (opt_value.value())
```
Comment (JDevlieghere) [inline lldb/tools/lldb-dap/Handler/RequestHandler.cpp:37]: Nit: I don't mind using `opt_value.value()` instead of `*opt_value`, but the latter is much more prevalent in llvm & lldb. 
```suggestion
    if (*opt_value)
```

**Review by JDevlieghere — APPROVED** [review]
LGTM. Thanks for bearing with me.
