### PR TITLE
[mlir][spirv] Fix incorrect metadata in SPIR-V Header

### LINKED ISSUE #99071: [mlir][spirv] Serializer produces incorrect generator metadata in SPIR-V header
See https://github.com/KhronosGroup/SPIRV-Tools/issues/5717 for more. Probably a trivial one-line fix, good low-hanging fruit for a newcomer?

### PR DESCRIPTION
**Pull request by AmrDeveloper**
SRIP-V Generator Magic Number is a 32 bit word: The high order 16 bits are a tool ID. The low order 16 bits are for verion number, currently the tool id is not on the high order 16 bit so it must shifed

fixes: #99071

### CODE REVIEW

**Comment by kuhar** [comment]
@andfau-amd could you help review this?

File: mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ void spirv::appendModuleHeader(SmallVectorImpl<uint32_t> &header,
   // +-------------------------------------------------------------------------+
   // | Magic number                                                            |
   // +-------------------------------------------------------------------------+
-  // | Version number (bytes: 0 | major number | minor number | 0)             |
+  // | Version number (bytes: 0 | 0 | major number | minor number)             |
```
Comment (andfau-amd) [inline mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp:45]: This seems to contradict the text of the spec: https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_physical_layout_of_a_spir_v_module_and_instruction (see section 2.3 "Physical Layout of a SPIR-V Module and Instruction")

Can you demonstrate that it's correct? For example, does `spirv-dis` agree with it?

File: mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp [hunk 2]
```diff
@@ -51,7 +51,7 @@ void spirv::appendModuleHeader(SmallVectorImpl<uint32_t> &header,
   // | 0 (reserved for instruction schema)                                     |
   // +-------------------------------------------------------------------------+
   header.push_back(spirv::kMagicNumber);
-  header.push_back((majorVersion << 16) | (minorVersion << 8));
+  header.push_back((majorVersion << 8) | minorVersion);
   header.push_back(kGeneratorNumber);
```
Comment (andfau-amd) [inline mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp:55]: The generator number was the thing the issue was about, and that isn't changed here, so this pull request doesn't fix the issue.

**Review by andfau-amd — CHANGES_REQUESTED** [review]

**Comment by AmrDeveloper** [comment]
Can you check it @andfau-amd 

Thank you

File: mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp [hunk 3]
```diff
@@ -52,7 +52,7 @@ void spirv::appendModuleHeader(SmallVectorImpl<uint32_t> &header,
   // +-------------------------------------------------------------------------+
   header.push_back(spirv::kMagicNumber);
   header.push_back((majorVersion << 16) | (minorVersion << 8));
-  header.push_back(kGeneratorNumber);
+  header.push_back((kGeneratorNumber << 16) | LLVM_VERSION_MAJOR);
```
Comment (andfau-amd) [inline mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp:55]: This looks good. Ideally the major, minor and patch version should be included, but I don't think 16 bits is enough to fit all of those safely, and it'd be hard to read in something like `spirv-dis`, so this is probably fine. Thanks for the contribution.

**Review by andfau-amd — APPROVED** [review]

**Review by kuhar — COMMENTED** [review]
Could you show a sample output from spirv-dis after this change?

**Comment by AmrDeveloper** [comment]
> Could you show a sample output from spirv-dis after this change?

```
; SPIR-V
; Version: 1.0
; Generator: Google MLIR SPIR-V Serializer; 20
; Bound: 95
; Schema: 0
```
[hello.module.zip](https://github.com/user-attachments/files/16664117/hello.module.zip)

**Review by kuhar — APPROVED** [review]
LGTM, thanks for fixing this
