### PR TITLE
[clang-tidy] Fix broken HeaderFilterRegex when read from config file

### LINKED ISSUE #118009: [clang-tidy] HeaderFilterRegex in .clang-tidy is not applied consistently and depends on working directory
I've encountered a strange behavior regarding "HeaderFilterRegex" (other options might be affected as well...).
I've tested this with clang-tidy version 19.1.2.
With older versions (e.g. clang-tidy 18.1.2) HeaderFilterRegex works as expected, so this seems to be a new issue.

Given the following setup in a project:

```bash
.
└── src
    ├── .clang-tidy
    ├── external.h
    ├── internal.h
    └── main.cpp
```

With the following file contents:

```bash
$ cat src/.clang-tidy
Checks: "-*,modernize-use-trailing-return-type"
HeaderFilterRegex: '.*internal.*'

$ cat src/internal.h
int GetSomeValue();

$ cat src/external.h
int GetSomeLibValue();

$ cat src/main.cpp
#include "internal.h"
#include "external.h"

int GetSomeValue() { return 42; }

int main() {
  return GetSomeValue() + GetSomeLibValue();
}
```

The expectation is that when clang-tidy is run on "main.cpp", it will report the diagnostics for "internal.h" but not for "external.h".
But this does not work consistently. It seems relevant in which workding directory clang-tidy is invoked.

```bash
$ clang-tidy src/main.cpp 2>/dev/null
PATH/TO/PROJ/src/main.cpp:4:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
    4 | int GetSomeValue() { return 42; }
      | ~~~ ^
      | auto               -> int
PATH/TO/PROJ/src/main.cpp:6:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
    6 | int main() {
      | ~~~ ^
      | auto       -> int
```

No diagnostic is applied, i.e. the "HeaderFilterRegex" is essentially set to ''.
If I run clang-tidy in "src", then this works as expected (internal.h is reported, external.h is not):

```bash
cd src/ && clang-tidy main.cpp 2>/dev/null
PATH/TO/PROJ/src/internal.h:1:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
    1 | int GetSomeValue();
      | ~~~ ^
      | auto               -> int
PATH/TO/PROJ/src/main.cpp:4:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
    4 | int GetSomeValue() { return 42; }
      | ~~~ ^
      | auto               -> int
PATH/TO/PROJ/src/main.cpp:6:5: warning: use a trailing return type for this function [modernize-use-trailing-return-type]
    6 | int main() {
      | ~~~ ^
      | auto       -> int
```

Notably, if I dump the configuration with "--dump-config" the resulting configuration is identical in both cases and it clearly sets "HeaderFilterRegex" to ".\*internal.\*".

### LINKED ISSUE #121969: Hierarchical .clang-tidy HeaderFilterRegex Settings Ignored in Clang-Tidy 19
# Summary
Our project uses a hierarchical `.clang-tidy` files to selectively enable checks for specific folders. Previously (in Clang-Tidy 18.1.x), we could rely on `HeaderFilterRegex` to exclude headers in other directories from checks that were only enabled in certain subfolders. After updating to Clang-Tidy 19.1.x, the subfolder’s `HeaderFilterRegex` seems to be ignored, causing unwanted warnings for headers outside the subfolder. 

We traced this regression to [PR #91400](https://github.com/llvm/llvm-project/pull/91400); reverting that PR makes Clang-Tidy 19 behave like 18 again.

# Steps to Reproduce
## Folder Structure
```
.clang-tidy
test.hpp
a/
 ├─ .clang-tidy
 └─ main.cpp
```

## File Contents
1. Root `.clang-tidy`:
  ```yaml
  HeaderFilterRegex: '.*'
  Checks: -.*
  ```

2. Root `test.hpp`:
  ```c++
  int test() {
    return (int)4.0;  // violates google-readability-casting
  }
  ```

3. Subfolder `a/.clang-tidy`:
  ```yaml
  InheritParentConfig: true
  HeaderFilterRegex: '.*a/.*'
  Checks: google-readability-casting
  ```

4. Subfolder `a/main.cpp`:
  ```c++
  #include "test.hpp"
  
  int main() {
    return test();
  }
  ```

### With clang-18 (Expected Behavior)
```
> clang-tidy-18 a/main.cpp --quiet -- -I.
1 warning generated.
```

### With clang-19 (Regression)
```
> clang-tidy-19 a/main.cpp --quiet -- -I.
1 warning generated.
./test.hpp:2:10: error: C-style casts are discouraged; use static_cast [google-readability-casting,-warnings-as-errors]
   2 |   return (int)4.0;
     |          ^~~~~
     |          static_cast<int>( )
```

### LINKED ISSUE #133453: `HeaderFilterRegex` does not work if `.clang-tidy` is in subdirectory
Specifying `HeaderFilterRegex: .*` in the `.clang-tidy` file in a subdirectory doesn't seem to take effect during compilation, but running `clang-tidy --dump-config` in the subdirectory does show `HeaderFilterRegex: '.*'`.

It works as expected if I move the `.clang-tidy` file to the project root, then clean and build.

The output of running `clang-tidy --dump-config` in the subdirectory is the same no matter `.clang-tidy` is placed in the project root or the subdirectory.

This CMake project demonstrates the issue:

[header_filter_subdir.zip](https://github.com/user-attachments/files/19507895/header_filter_subdir.zip)

<details>
<summary>Here are my detailed reproduce steps</summary>

Only relevant command output are shown.

#### In host machine

```console
$ docker run -it fedora:41 bash
$ docker cp header_filter_subdir/ ${CONTAINER}:/root
```

#### In Docker container

```console
# cd
# dnf update
# dnf install @c-development cmake git ninja-build
# git clone https://github.com/llvm/llvm-project.git
# cd llvm-project/
# cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS='clang;lld;clang-tools-extra' -DCMAKE_BUILD_TYPE=Release
# cd build/
# cmake --build .
# cmake --install .
# clang --version
clang version 21.0.0git (https://github.com/llvm/llvm-project.git 316bb89c942c1a1cf61d3e673030f82d6f0b8acf)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
# cd ~/header_filter_subdir/
# CC=clang CXX=clang++ cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 21.0.0
-- The CXX compiler identification is Clang 21.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for clang-tidy
-- Looking for clang-tidy - found
'/usr/local/bin/clang-tidy' '--version'
LLVM (http://llvm.org/):
  LLVM version 21.0.0git
  Optimized build.
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /root/header_filter_subdir/build
# cd build/
# cmake --build .
[2/4] Building CXX object print/CMakeFiles/my_print.dir/print.cpp.o
/root/header_filter_subdir/print/print.cpp:5:21: warning: parameter 'i' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
    5 | void print_impl(int const i);
      |                     ^~~~~
[4/4] Linking CXX executable header_filter_subdir
# cd ../print/
# clang-tidy --dump-config | tee subdir.out
# mv .clang-tidy ..
# cd -
/root/header_filter_subdir/build
# cmake --build . --target clean
# cmake --build .
[1/4] Building CXX object CMakeFiles/header_filter_subdir.dir/main.cpp.o
/root/header_filter_subdir/print/print.h:4:16: warning: parameter 'i' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
    4 | void print(int const i);
      |                ^~~~~
[2/4] Building CXX object print/CMakeFiles/my_print.dir/print.cpp.o
/root/header_filter_subdir/print/print.cpp:5:21: warning: parameter 'i' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
    5 | void print_impl(int const i);
      |                     ^~~~~
/root/header_filter_subdir/print/print.h:4:16: warning: parameter 'i' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls]
    4 | void print(int const i);
      |                ^~~~~
[4/4] Linking CXX executable header_filter_subdir
# cd -
/root/header_filter_subdir/print
# clang-tidy --dump-config | tee rootdir.out
# diff subdir.out rootdir.out # no output
# grep -P ^HeaderFilterRegex subdir.out
HeaderFilterRegex: '.*'
```

</details>

### PR DESCRIPTION
**Pull request by carlosgalvezp**
PR https://github.com/llvm/llvm-project/pull/91400 broke the usage of HeaderFilterRegex via config file, because it is now created at a different point in the execution and leads to a different value.

The result of that is that using HeaderFilterRegex only in the config file does NOT work, in other words clang-tidy stops triggering warnings on header files, thereby losing a lot of coverage.

This patch reverts the logic so that the header filter is created upon calling the getHeaderFilter() function.

Additionally, this patch adds 2 unit tests to prevent regressions in the future:

- One of them, "simple", tests the most basic use case with a single top-level .clang-tidy file.

- The second one, "inheritance", demonstrates that the subfolder only gets warnings from headers within it, and not from parent headers.

Fixes #118009
Fixes #121969
Fixes #133453

### CODE REVIEW

**Comment by tearfur** [comment]
Tested by applying this PR on top of 3e742b517a0606bfed329dfcb8c34c614ed73ea7. Works great AFAICT!

```console
# curl -sL 'https://github.com/llvm/llvm-project/pull/133582.diff' | git apply
```

**Comment by tearfur** [comment]
P.S. Just a heads up that `Fixes #118009, #121969, #133453` is not linking this PR to all 3 issues.

They need to be split to 3 `Fixes #xxx` lines.

File: clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp [hunk 1]
```diff
@@ -571,17 +560,30 @@ void ClangTidyDiagnosticConsumer::checkFilters(SourceLocation Location,
...
 
   unsigned LineNumber = Sources.getExpansionLineNumber(Location);
   LastErrorPassesLineFilter =
       LastErrorPassesLineFilter || passesLineFilter(FileName, LineNumber);
 }
 
+llvm::Regex *ClangTidyDiagnosticConsumer::getHeaderFilter() {
+  if (!HeaderFilter)
+    HeaderFilter =
+        std::make_unique<llvm::Regex>(*Context.getOptions().HeaderFilterRegex);
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:576]: HeaderFilterRegex is `std::optional<>`. How to handle `HeaderFilterRegex` is `std::nullopt`?

Comment (carlosgalvezp) [reply clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:576]: Thanks, good point. That was also changed in the original PR so I will revert that too. I wonder if it makes more sense to do a full revert and reland with the right changes instead. But since the PR is 1 year old it might be tricky.

**Comment by carlosgalvezp** [comment]
Was there anything else I should fix @HerrCai0907 ? It would be good to get this in in soon and cherrypick to branch 20.

**Comment by carlosgalvezp** [comment]
Otherwise maybe @PiotrZSL can you review, I believe you reviewed the original PR?

**Review by HerrCai0907 — APPROVED** [review]
LGTM.

**Comment by carlosgalvezp** [comment]
@tstellar Any chance we can cherry-pick this to the 20.x branch?

File: clang-tools-extra/test/clang-tidy/infrastructure/header-filter-from-config-file/simple/.clang-tidy [hunk 2]
```diff
@@ -0,0 +1 @@
+HeaderFilterRegex: '.*'
```
Comment (carlosgalvezp) [inline clang-tools-extra/test/clang-tidy/infrastructure/header-filter-from-config-file/simple/.clang-tidy:1]: It appears this use case was broken by this [patch](https://github.com/llvm/llvm-project/commit/0249554ee1ac49e6f1d93fa78a55971fc706f635),  @HerrCai0907  . 

There may be more things to fix.
