### PR TITLE
[MachinePipeliner] Fix constraints aren't considered in certain cases

### LINKED ISSUE #93936: [MachinePipeliner] Consideration of `SchedStart` is omitted in some cases?
We found that the `SchedStart` may not be considered when scheduling instructions.
Please refer to the following link for details.
https://godbolt.org/z/G16Kd7Y6P

The following is part of the debugging output.

```
Inst (11)   %77:fpr128 = LDRQui %10:gpr64sp, 0, debug-location !41 :: (load (s128) from %ir.lsr.iv63, align 4, !tbaa !36); example.c:10:24

	es: ffffffe8 ls: ffffffe9 me: 7fffffff ms: ffffffe9
Trying to insert node between -24 and -23 II: 47
	insert at cycle -24   %77:fpr128 = LDRQui %10:gpr64sp, 0, debug-location !41 :: (load (s128) from %ir.lsr.iv63, align 4, !tbaa !36); example.c:10:24

```

In this case, `SchedStart` is -23, so we must insert this instruction at cycle -23, however it's inserted at -24.
Perhaps following part causes this problem.

https://github.com/llvm/llvm-project/blob/e1cc9e4eaddcc295b4e775512e33b947b1514c17/llvm/lib/CodeGen/MachinePipeliner.cpp#L2441-L2449

By the way, is there any reason why `SchedStart` and `EarlyStart` are treated separately (same for `SchedEnd` and `LateStart`) ?
If not, I think merging them makes code simpler.

### PR DESCRIPTION
**Pull request by kasuga-fj**
when scheduling

When scheduling an instruction, if both any predecessors and any successors of the instruction are already scheduled, `SchedStart` isn't taken into account. It may result generating incorrect code. This patch fixes the problem. Also, this patch merges `SchedStart` into `EarlyStart` (same for `SchedEnd`).

I checked the schedule changes due to this patch in llvm-test-suite. In conclusion, as far as I observed, there was no change in most cases. Just in case, details of the results are as follows.

Compile options:
```
-O3 \
-mcpu=neoverse-v1 \
-mllvm -aarch64-enable-pipeliner \
-mllvm -pipeliner-max-stages=1000 \
-mllvm -pipeliner-max-mii=1000 \
-mllvm -pipeliner-enable-copytophi=0 \
-mllvm -pipeliner-ii-search-range=100 \
-mllvm -enable-misched=0 \
-mllvm -enable-post-misched=0
```

Observed changes:
| Test | Summary |
|-|-|
| MultiSource/Benchmarks/ASCI_Purple/SMG2000/smg2000 | The order of some instructions was changed |
| MultiSource/Benchmarks/TSVC/CrossingThresholds-flt/CrossingThresholds-flt | The order of some instructions was changed |
| MultiSource/Benchmarks/ASC_Sequoia/AMGmk/AMGmk | The order of some instructions was changed |

close #93936

### CODE REVIEW

**Comment by kasuga-fj** [comment]
ping

File: llvm/lib/CodeGen/MachinePipeliner.cpp [hunk 1]
```diff
@@ -2420,47 +2420,48 @@ bool SwingSchedulerDAG::schedulePipeline(SMSchedule &Schedule) {
...
+            Schedule.insert(SU, EarlyStart, EarlyStart + (int)II - 1, II);
+      else if (EarlyStart == INT_MIN && LateStart != INT_MAX)
+        scheduleFound =
+            Schedule.insert(SU, LateStart, LateStart - (int)II + 1, II);
+      else if (EarlyStart != INT_MIN && LateStart != INT_MAX) {
+        // To keep original behaviour, start scheduling at the late cycle and go
+        // backwards when all scheduled predecessors are loop-carried
+        // output/order dependencies. Empirically, there are also cases where
+        // scheduling becomes possible with backward search.
+        if (Schedule.onlyHasLoopCarriedOutputOrOrderPreds(SU, this)) {
```
Comment (bcahoon) [inline llvm/lib/CodeGen/MachinePipeliner.cpp:2446]: I'm not sure I see how this keeps the original behavior?  I assume some test case fails without it?
If it's needed, can this be combined with the code at line 2455?

**Review by bcahoon — COMMENTED** [review]
Can you add a test code using the example from the [issue](https://github.com/llvm/llvm-project/issues/93936)?

File: llvm/lib/CodeGen/MachinePipeliner.cpp (hunk 1 above)
Comment (bcahoon) [reply llvm/lib/CodeGen/MachinePipeliner.cpp:2446]: I commented out the code between lines 2446-2449, and noticed some test failures. I took a quick look at sw-bad-sched.ll, and I can see what is going on.

Prior to this patch:
  ```
Inst (3)   %63:intregs = L2_loadri_io %15:intregs, 0 :: (load (s32) from %ir.lsr.iv1, !tbaa !0)
        es: 80000000 ls:        0 me: 7fffffff ms: ffffffff
  Trying to insert node between 0 and -1 II: 3
```

With this patch:
  ```
Inst (3)   %63:intregs = L2_loadri_io %15:intregs, 0 :: (load (s32) from %ir.lsr.iv1, !tbaa !0)
        es: ffffffff ls:        0
  Trying to insert node between 0 and -1 II: 3

```
In the old case, the pipeliner uses does a bottom up schedule because es == INT_MAX and ls == 0.
Because es is -1, with the patch, the pipeliner drops into the case when both es and ls have been defined. Previously, that used a top-down search (unless the SU is a Phi).

I think it's okay for the schedule processing to change after your patch. I feel it would be surprising if it didn't.  For example, in the case of swp-bad-sched.ll, the generated schedules are equivalent when comparing the output from your patch to the output from removing the code in lines 2446-2449. I haven't looked at the other cases though.

The question is - does the bottom-up scheduling produces a better result for certain situations. The patch has a comment "Empirically, there are also cases where scheduling becomes possible with backward search". This would be a reason to add/keep the code that does a backward search. But, I would see those cases and I think it would be better to combine any changes to do a bottom up search with the isPHI() check

Comment (kasuga-fj) [reply llvm/lib/CodeGen/MachinePipeliner.cpp:2446]: > does the bottom-up scheduling produces a better result for certain situations.
Yes. As far as I have checked with llvm-test-suite, there were cases where scheduling failed when stopping the backward search (about 1% of all cases). Removing lines 2446-2449 sometimes generated better schedule, but these were about a tenth of the cases where scheduling failed. Therefore I believe that keeping the original behavior is valuable.

In any case, as you mentioned, merging this process with isPHI() checks looks good to me. I'll fix it.

**Comment by kasuga-fj** [comment]
Added test.

**Review by bcahoon — APPROVED** [review]
Thanks for fixing. LGTM.
