### PR TITLE
[clang] Fix pretty-printing assume_aligned attributes

### LINKED ISSUE #67156: Clang attr emitter tablegen target should guard optional arguments
I noticed a crash for the following valid code when using the `-ast-print` flag:
https://godbolt.org/z/78xYbEosb
```C++
void *top() __attribute__((assume_aligned(__alignof__(unsigned long long))));
```

The AST looks like this:
```
TranslationUnitDecl
`-FunctionDecl <line:1:1, col:76> col:7 top 'void *()'
  `-AssumeAlignedAttr <col:28, col:74>
    |-UnaryExprOrTypeTraitExpr <col:43, col:73> 'unsigned long' __alignof 'unsigned long long'
    `-<<<NULL>>>
```

Notice the last NULL node.

In the clang/include/clang/Basic/Attr.td, we can see that `AssumeAligned` is defined like this:
```
def AssumeAligned : InheritableAttr {
  let Spellings = [GCC<"assume_aligned">];
  let Subjects = SubjectList<[ObjCMethod, Function]>;
  let Args = [ExprArgument<"Alignment">, ExprArgument<"Offset", 1>];
  let Documentation = [AssumeAlignedDocs];
}
```

Notice the `ExprArgument<"Offset", 1>`, where `1` denotes that this argument is optional, thus might be null.
There are a couple other attributes where we set this flag, but they are really rare.
I found only `CUDALaunchBounds`, `AMDGPUWavesPerEU` and `AssumeAligned`.

Apparently, inside clang/utils/TableGen/ClangAttrEmitter.cpp:`ExprArgument::writeValue`, we emit code that doesn't guard optional arguments before visiting them:
```C++
void writeValue(raw_ostream &OS) const override {
  OS << "\";\n";
  OS << "    get" << getUpperName()
     << "()->printPretty(OS, nullptr, Policy);\n";
  OS << "    OS << \"";
}
```

It should have guarded the call to `printPretty()` to make sure the pointer is valid.
I suspect, that other emit functions suffer from this issue.

This is present on clang-16, and on trunk as of now.

### PR DESCRIPTION
**Pull request by steakhal**
Inside `writePrettyPrintFunction()`, we check if we need to emit the given argument:
```C++
if (!arg->isOptional() || arg->getIsOmitted() == "false") {
    FoundNonOptArg = true;
    continue;
}
```
For the `AssumeAligned` attribute, the second argument was optional, but the `getIsOmitted()` returned `false`, thus we treated this argument as **non-optional** in the end because of that disjunction.

It was because `getIsOmitted()` did not account for `Expr *` type, and returned `false` on the fallthrough branch.

Fixes #67156

### CODE REVIEW

File: clang/utils/TableGen/ClangAttrEmitter.cpp [hunk 1]
```diff
@@ -320,10 +320,11 @@ namespace {
...
 
     std::string getIsOmitted() const override {
-      if (type == "IdentifierInfo *")
-        return "!get" + getUpperName().str() + "()";
-      if (type == "TypeSourceInfo *")
+      StringRef T = type;
+      if (T == "TypeSourceInfo *")
         return "!get" + getUpperName().str() + "Loc()";
+      if (T.ends_with(" *"))
+        return "!get" + getUpperName().str() + "()";
```
Comment (erichkeane) [inline clang/utils/TableGen/ClangAttrEmitter.cpp:327]: This might not be sufficient here, it could end in 'const' /etc, right?

Comment (steakhal) [reply clang/utils/TableGen/ClangAttrEmitter.cpp:327]: I think it's not worse than it was before.
If you object, I could as well just directly compare against `type == "Expr *"`, similarly to how it was done before.
Or I'm not sure how to resolve this comment.
Did you think of dropping suffixes like `const`, `volatile`, etc? If so, why?
Out of curiosity, I put there these asserts `assert(!T.ends_with_insensitive("const"))`, `assert(!T.ends_with_insensitive("volatile"))` and they didn't fire when I ran `check-clang`, thus I think we probably keep the logic simple unless we have a use-case to solve.
WDYT?

Comment (erichkeane) [reply clang/utils/TableGen/ClangAttrEmitter.cpp:327]: Ah, you're not wrong about this not being worse... I guess the list of things handled in here are finite, since this is a list from a generated .td file.  

I think handling `Expr *` separately (as a separate condition of the `IdentifierInfo *` line) is probably the 'right' way to go, but I think we should have an 'assert' above the return-false to ensure that anyone who adds a new type makes sure it gets handled here.

Comment (steakhal) [reply clang/utils/TableGen/ClangAttrEmitter.cpp:327]: I see. Makes sense. I'll look into this tomorrow.
Thanks for the review!

Comment (steakhal) [reply clang/utils/TableGen/ClangAttrEmitter.cpp]: Indeed, there are more pointer things in the "type" field. Different kinds of Decls and could be others as well.
I agree that the safest is to only enable this for "Expr *".

File: clang/utils/TableGen/ClangAttrEmitter.cpp [hunk 2]
```diff
@@ -320,11 +320,12 @@ namespace {
...
+      StringRef T = type;
+      if (T == "IdentifierInfo *" || T == "Expr *")
         return "!get" + getUpperName().str() + "()";
-      if (type == "TypeSourceInfo *")
+      if (T == "TypeSourceInfo *")
         return "!get" + getUpperName().str() + "Loc()";
-      if (type == "ParamIdx")
+      if (T == "ParamIdx")
         return "!get" + getUpperName().str() + "().isValid()";
       return "false";
```
Comment (erichkeane) [inline clang/utils/TableGen/ClangAttrEmitter.cpp:330]: So the bit I requested was an assert over 330 here that is: `assert(T=="somethingnothandled" || T=="somethingelsenothandled" || ...)` so that we can catch this in the future.

You SHOULD be able to figure out the list by doing a couple of builds here to see (note that you dont' have to do check-clang, just 'ninja clang' (or w/e), since this is tablegen.

**Comment by erichkeane** [comment]
Also, it appears that the clang-format bot dislikes this commit (but frustratingly won't tell us why?), so perhaps run `git clang-format against all the commits here`

File: clang/utils/TableGen/ClangAttrEmitter.cpp (hunk 2 above)
Comment (steakhal) [reply clang/utils/TableGen/ClangAttrEmitter.cpp:336]: Done.

**Comment by steakhal** [comment]
> Also, it appears that the clang-format bot dislikes this commit (but frustratingly won't tell us why?), so perhaps run `git clang-format against all the commits here`

Yup, I have it on save already. It complains about lines I never touched.
As per guidelines, I only run clang-format on the lines touched by the diff, using `git clang-format`.
It says "clang-format did not modify any files"

**Review by erichkeane — APPROVED** [review]

**Comment by steakhal** [comment]
Thanks for the review @erichkeane!
