### PR TITLE
[clang-format] Add ClassHeadName to help annotating StartOfName

### LINKED ISSUE #124574: Regression clang-formatting __declspec(uuid(...))
Current HEAD (3322ba493ad7):

```
% out/gn/bin/clang-format declspec-uuid.cc                                  
template <>
struct __declspec(uuid(
    "3895C200-8F26-4F5A-B29D-2B5D72E68F99")) IAsyncOperation<IUnknown *>
    : IAsyncOperation_impl<IUnknown *> {};
```

Back at 10664813 (Oct 2023, a while ago):

```
% ~/src/chrome/src/buildtools/mac_arm64/format/clang-format declspec-uuid.cc
template <>
struct __declspec(uuid("3895C200-8F26-4F5A-B29D-2B5D72E68F99"))
IAsyncOperation<IUnknown *> : IAsyncOperation_impl<IUnknown *> {};
```

The old formatting is more correct.

### PR DESCRIPTION
**Pull request by owenca**
Fixes #124574.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by mydeveloperday — APPROVED** [review]
This looks good to me like we might be able to differentiate better

**Review by gedare — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -1146,6 +1175,8 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
   EXPECT_TOKEN(Tokens[31], tok::greater, TT_TemplateCloser);
   EXPECT_EQ(Tokens[31]->FakeRParens, 1u);
   EXPECT_TRUE(Tokens[31]->ClosesRequiresClause);
+  // FIXME:
+  // EXPECT_TOKEN(Tokens[33], tok::identifier, TT_Unknown); // Not ClassHeadName
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1179]:
```suggestion
  // FIXME:
  // EXPECT_TOKEN(Tokens[33], tok::identifier, TT_Unknown); // Not TrailingAnnotation
```

Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1179]: Fixed in 4fb80788872e1c1c789fc9a06edd123414a427e6.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -3458,6 +3509,9 @@ TEST_F(TokenAnnotatorTest, BraceKind) {
   Tokens = annotate("a = class Foo extends goog.a {};",
                     getGoogleStyle(FormatStyle::LK_JavaScript));
   ASSERT_EQ(Tokens.size(), 12u) << Tokens;
+  EXPECT_TOKEN(Tokens[3], tok::identifier, TT_ClassHeadName);
+  // FIXME:
+  // EXPECT_TOKEN(Tokens[4], tok::identifier, TT_Unknown); // Not StartOfName
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:3514]: Fixed in ea84474966f19af4f1f4a1250ec258af1c6e2571.
