### PR TITLE
RegisterCoalescer: Fix assert on remat to copy-to-physreg with subregs

### LINKED ISSUE #120970: "Already live at def" assertion in RegisterCoalescer
[already-live-at-def.mir.zip](https://github.com/user-attachments/files/18230543/already-live-at-def.mir.zip)

```
llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -o /dev/null -run-pass=register-coalescer -verify-coalescing /Users/matt/src/llvm-project/llvm/test/CodeGen/AMDGPU/already-live-at-def.mir
Assertion failed: (SlotIndex::isEarlierInstr(Def, S->start) && "Already live at def"), function createDeadDef, file LiveInterval.cpp, line 114.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./bin/llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -o /dev/null -run-pass=register-coalescer -verify-coalescing /Users/matt/src/llvm-project/llvm/test/CodeGen/AMDGPU/already-live-at-def.mir
1.	Running pass 'Function Pass Manager' on module '/Users/matt/src/llvm-project/llvm/test/CodeGen/AMDGPU/already-live-at-def.mir'.
2.	Running pass 'Register Coalescer' on function '@already_live_at_def'
 #0 0x00000001090126fc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x106b066fc)
 #1 0x0000000109012c6c PrintStackTraceSignalHandler(void*) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x106b06c6c)
 #2 0x0000000109010a64 llvm::sys::RunSignalHandlers() (/Users/matt/src/llvm-project/build_debug/bin/llc+0x106b04a64)
 #3 0x0000000109013584 SignalHandler(int) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x106b07584)
 #4 0x00000001850a0184 (/usr/lib/system/libsystem_platform.dylib+0x180484184)
 #5 0x000000018506af70 (/usr/lib/system/libsystem_pthread.dylib+0x18044ef70)
 #6 0x0000000184f77908 (/usr/lib/system/libsystem_c.dylib+0x18035b908)
 #7 0x0000000184f76c1c (/usr/lib/system/libsystem_c.dylib+0x18035ac1c)
 #8 0x0000000106b518f8 (anonymous namespace)::CalcLiveRangeUtilBase<(anonymous namespace)::CalcLiveRangeUtilVector, llvm::LiveRange::Segment*, llvm::SmallVector<llvm::LiveRange::Segment, 2u>>::createDeadDef(llvm::SlotIndex, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>*, llvm::VNInfo*) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x1046458f8)
 #9 0x0000000106b50f70 llvm::LiveRange::createDeadDef(llvm::SlotIndex, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>&) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104644f70)
#10 0x0000000106fd0754 (anonymous namespace)::RegisterCoalescer::reMaterializeTrivialDef(llvm::CoalescerPair const&, llvm::MachineInstr*, bool&) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104ac4754)
#11 0x0000000106fcd000 (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&, llvm::SmallPtrSetImpl<llvm::MachineInstr*>&) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104ac1000)
#12 0x0000000106fca1c4 (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104abe1c4)
#13 0x0000000106fc73c8 (anonymous namespace)::RegisterCoalescer::joinAllIntervals() (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104abb3c8)
#14 0x0000000106fc4f10 (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) (/Users/matt/src/llvm-project/build_debug/bin/llc+0x104ab8f10)

```

If the unused $vgpr0 block live in is removed, the assert is avoided but there is a verifier error after coalescing

### PR DESCRIPTION
**Pull request by arsenm**
Do not try to rematerialize a super-register def used by a subregister
extract copy into a copy to a physical register if the other pieces of the
full physreg are live at the rematerialization point. It would insert the
super-register def at the rematerialization point, and assert since the
other half of the register was already live.

This is analagous to the undef subregister def handling above,
which handled the virtual register case.

Fixes #120970

### CODE REVIEW

**Comment by arsenm** [comment]
* **#121734** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/121734?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/121734?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: llvm/lib/CodeGen/RegisterCoalescer.cpp [hunk 1]
```diff
@@ -1339,6 +1334,32 @@ bool RegisterCoalescer::reMaterializeTrivialDef(const CoalescerPair &CP,
...
     return false;
 
+  // Only support subregister destinations when the def is read-undef.
+  MachineOperand &DstOperand = CopyMI->getOperand(0);
+  Register CopyDstReg = DstOperand.getReg();
+  if (DstOperand.getSubReg() && !DstOperand.isUndef())
+    return false;
+
+  // Only support subregister destinations when the def is read-undef, in the
+  // physical register case. We're widening the def and need to avoid clobbering
```
Comment (qcolombet) [inline llvm/lib/CodeGen/RegisterCoalescer.cpp:1344]: I would start the comment with: "In the physical register case checking that the def is read-undef is not enough [...]" instead of repeating the beginning of the previous comment.

**Review by qcolombet — APPROVED** [review]
LGTM
