### PR TITLE
[C API] Fix LLVMGetOrdering/LLVMIsAtomicSingleThread for fence/memory instrs

### LINKED ISSUE #65227: [C API] GetOrdering/IsAtomicSingleThread do not work for fence/load/store
Two related issues with atomics in the C API:
 - `LLVMGetOrdering` currently does not support fence instructions
 - `LLVMIsAtomicSingleThread` currently does not support fence or load/store instructions 

In both cases, we will cast the unsupported instruction types to an unrelated type (whatever the else branch assumes it is), which will result in reading garbage. This will crash if assertions are enabled, otherwise it will just return whatever value it gets: in the case of `LLVMGetOrdering` this can return invalid enum values

### PR DESCRIPTION
**Pull request by Benjins**
Fixes https://github.com/llvm/llvm-project/issues/65227

LLVMGetOrdering previously did not support Fence instructions, and calling it on a fence would lead to a bad cast as it
assumed a load/store, or an AtomicRMWInst. This would either read a garbage memory order, or assertion

LLVMIsAtomicSingleThread did not support either Fence instructions, loads, or stores, and would similarly lead to a bad cast.
It happened to work out since the relevant types all have their synch scope ID at the same offset, but it still should be fixed

These cases are now fixed for the C API, and tests for these instructions are added. The echo test utility now also supports cloning Fence instructions, which it did not previously

-----

From what I can tell, there's no unified API to pull `getOrdering`/`getSyncScopeID` from, and instead requires casting to individual types: if there is a better way of handling this I can switch to that

### CODE REVIEW

**Comment by Benjins** [comment]
From the build logs:
```
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "unittests\Testing\Support\TestingSupportTests.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```
Possibly Windows Defender triggering on it?

**Review by cdisselkoen — APPROVED** [review]
This all looks good to me (and I'm happy to see this change in order to resolve https://github.com/cdisselkoen/llvm-ir/issues/44 and https://github.com/cdisselkoen/llvm-ir/issues/15)

**Comment by Benjins** [comment]
Bumping this in case it was missed: if anyone with merge access would be relevant to review or merge, I can ping them. I tried locally merging this into latest main and the tests still passed, so it should still be good in this state

File: llvm/lib/IR/Core.cpp [hunk 1]
```diff
@@ -3769,6 +3771,8 @@ void LLVMSetOrdering(LLVMValueRef MemAccessInst, LLVMAtomicOrdering Ordering) {
 
   if (LoadInst *LI = dyn_cast<LoadInst>(P))
     return LI->setOrdering(O);
+  else if (FenceInst *FI = dyn_cast<FenceInst>(P))
+    return FI->setOrdering(O);
```
Comment (nikic) [inline llvm/lib/IR/Core.cpp:3775]: Missing atomicrmw handling?

Comment (Benjins) [reply llvm/lib/IR/Core.cpp:3775]: I can add this as well. My understanding is that the bindings tests will not use that, since it uses `LLVMBuildAtomicRMW` to set the ordering directly. Is that okay?

**Review by nikic — APPROVED** [review]

**Comment by Benjins** [comment]
Should I merge again from main, or is this good to land?

**Comment by nikic** [comment]
Should be good to land.

**Comment by Benjins** [comment]
Is that something you can do, or should I reach out to someone else? I don't have access rights to merge it

**Comment by nikic** [comment]
Oh, I thought you have commit access because you are marked as "Member". Apparently that also includes people in bz-contributors that do not have commit access as well.
