### PR TITLE
[HLSL] Fix debug info generation for RWBuffer types

### LINKED ISSUE #118523: [HLSL] Assertion failure when generating DebugInfo for RWBuffer types
Given a simple program involving an RWBuffer:

```hlsl
// clang --driver-mode=dxc -Zi -Fc out.s -T cs_6_3 %s

RWBuffer<float4> Out : register(u7, space4);

[numthreads(8,1,1)]
void main(uint GI : SV_GroupIndex) {
  Out[GI] = 0;
}
```

We get an assert during debug info generation like so:

> Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 572.

```
  * frame #4: 0x0000000103bd3ca4 clang`decltype(auto) llvm::cast<clang::PointerType, clang::QualType>(Val=0x000000016fdf04d0) at Casting.h:572:3
    frame #5: 0x0000000103bd3734 clang`clang::CodeGen::CGDebugInfo::getOrCreateInstanceMethodType(this=0x000000015c832800, ThisPtr=QualType @ 0x000000016fdf04d0, Func=0x000000015b8c3300, Unit=0x00006000037c5110) at CGDebugInfo.cpp:2027:38
    frame #6: 0x0000000103bd34a0 clang`clang::CodeGen::CGDebugInfo::getOrCreateMethodType(this=0x000000015c832800, Method=0x000000015b8c4a00, Unit=0x00006000037c5110) at CGDebugInfo.cpp:1989:10
    frame #7: 0x0000000103be2edc clang`clang::CodeGen::CGDebugInfo::getOrCreateFunctionType(this=0x000000015c832800, D=0x000000015b8c4a00, FnType=QualType @ 0x000000016fdf08a0, F=0x00006000037c5110) at CGDebugInfo.cpp:4340:12
    frame #8: 0x0000000103be57b0 clang`clang::CodeGen::CGDebugInfo::emitFunctionStart(this=0x000000015c832800, GD=GlobalDecl @ 0x000000016fdf0bb8, Loc=(ID = 0), ScopeLoc=(ID = 0), FnType=QualType @ 0x000000016fdf0bb0, Fn=0x00006000021c1b98, CurFuncIsThunk=false) at CGDebugInfo.cpp:4491:38
    frame #9: 0x0000000104067128 clang`clang::CodeGen::CodeGenFunction::StartFunction(this=0x000000016fdf3478, GD=GlobalDecl @ 0x000000016fdf3008, RetTy=QualType @ 0x000000016fdf3000, Fn=0x00006000021c1b98, FnInfo=0x0000600003dc4200, Args=0x000000016fdf33a8, Loc=(ID = 0), StartLoc=(ID = 0)) at CodeGenFunction.cpp:1133:9
```

The issue is that in HLSL "this" is a reference, but the debug info generation here expects a pointer.

### PR DESCRIPTION
**Pull request by joaosaffran**
This PR fix the debug infor generation for RWBuffer types.
- This implements the [same fix as DXC](https://github.com/microsoft/DirectXShaderCompiler/pull/6296).
- Adds the HLSLAttributedResource debug info generation

Closes #118523

### CODE REVIEW

File: clang/lib/CodeGen/CGDebugInfo.cpp [hunk 1]
```diff
@@ -2021,28 +2021,10 @@ llvm::DISubroutineType *CGDebugInfo::getOrCreateInstanceMethodType(
   // ThisPtr may be null if the member function has an explicit 'this'
   // parameter.
   if (!ThisPtr.isNull()) {
-    const CXXRecordDecl *RD = ThisPtr->getPointeeCXXRecordDecl();
-    if (isa<ClassTemplateSpecializationDecl>(RD)) {
```
Comment (bogner) [inline clang/lib/CodeGen/CGDebugInfo.cpp:2025]: Is removing this entire block NFC? I'm surprised that this doesn't affect anything. If so, we should probably make the NFC change separately from the HLSL specific one so that it's clear what (isn't) changing.

Comment (joaosaffran) [reply clang/lib/CodeGen/CGDebugInfo.cpp:2025]: Well, this is a consequence of the `this` fix, the same done in DXC. After applying the fix the code becomes:

```c++
if (isa<ClassTemplateSpecializationDecl>(RD)) {
    // HLSL Change Begin - This is a reference.
    llvm::DIType *ThisPtrType = getOrCreateType(ThisPtr, Unit);
    // HLSL Change End - This is a reference.
    TypeCache[ThisPtr.getAsOpaquePtr()].reset(ThisPtrType);
    // TODO: This and the artificial type below are misleading, the
    // types aren't artificial the argument is, but the current
    // metadata doesn't represent that.
    ThisPtrType = DBuilder.createObjectPointerType(ThisPtrType);
    Elts.push_back(ThisPtrType);
  } else {
    llvm::DIType *ThisPtrType = getOrCreateType(ThisPtr, Unit);
    TypeCache[ThisPtr.getAsOpaquePtr()].reset(ThisPtrType);
    ThisPtrType = DBuilder.createObjectPointerType(ThisPtrType);
    Elts.push_back(ThisPtrType);
  }
```

Removing the comments, if and else blocks become the same code, so I just removed the branching

Comment (llvm-beanz) [reply clang/lib/CodeGen/CGDebugInfo.cpp:2025]: This code has been around in clang for _a long time_, and it was implemented back when LLVM's testing standards were not quite as high as they are today (https://github.com/llvm/llvm-project/commit/fa59ac363ef4747fdb142d993326c43d832629bb).

The test case that was introduced with the original code here is [here](https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGenCXX/debug-info-template-limit.cpp), and it generates identical IR with and without this PR.

It would be nice to have someone who understands C++ debug info well review this change as well, but it looks to me like the special handling here is vestigial and no longer needed.

@dwblaikie, @adrian-prantl, or @Michael137, can one of you take a look at this please?

Comment (dwblaikie) [reply clang/lib/CodeGen/CGDebugInfo.cpp:2025]: huh, interesting archaeology... Wish we knew which test in particular it was.
This change might've been before I changed one of the old/core (before vtables, template specializations, and ctor homing) -flimit-debug-info thing which was more ad-hoc, to be powered by class "required to be complete" events. 

So, yeah, I could totally believe whatever this code did may've been subsumed by other work/generalizations/etc since then.

but, yeah, if we're removing it, best to do it separately in an NFC change & if someone's feeling like doing due diligence, perhaps building clang with/without this change (on linux, or otherwise with -flimit-debug-info enabled) and checking the binary output is identical?

Comment (joaosaffran) [reply clang/lib/CodeGen/CGDebugInfo.cpp:2025]: Created a NFC with this change, please take a look here: https://github.com/llvm/llvm-project/pull/119445

File: clang/lib/CodeGen/CGDebugInfo.cpp [hunk 2]
```diff
@@ -3834,12 +3839,14 @@ llvm::DIType *CGDebugInfo::CreateTypeNode(QualType Ty, llvm::DIFile *Unit) {
 
   case Type::TemplateSpecialization:
     return CreateType(cast<TemplateSpecializationType>(Ty), Unit);
+  case Type::HLSLAttributedResource: {
+    return CreateType(cast<HLSLAttributedResourceType>(Ty), Unit);
+  }
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CGDebugInfo.cpp:3844]: nit: remove unnecessary braces.
```suggestion
  case Type::HLSLAttributedResource:
    return CreateType(cast<HLSLAttributedResourceType>(Ty), Unit);
```

File: clang/test/CodeGenHLSL/debug/rwbuffer_debug_info.hlsl [hunk 3]
```diff
@@ -0,0 +1,11 @@
+// RUN: %clang  --driver-mode=dxc -Zi -Fc - -T cs_6_6 -O0 %s | FileCheck %s
+
+// CHECK: #dbg_declare(ptr [[ThisReg:%this\..*]], [[ThisMd:![0-9]+]],
+// CHECK-DAG: [[ThisMd]] = !DILocalVariable(name: "this", arg: 1, scope: !{{[0-9]+}}, type: ![[type:[0-9]+]], flags: DIFlagArtificial | DIFlagObjectPointer)
```
Comment (llvm-beanz) [inline clang/test/CodeGenHLSL/debug/rwbuffer_debug_info.hlsl:4]: What is the actual type this is specifying? My read is it specifies `float4` which isn't really what we want. We probably want it to instead become an opaque struct pointer.

**Review by llvm-beanz — APPROVED** [review]
