### PR TITLE
[RISCV] Track Linker Relaxable through Assembly Relaxation

### LINKED ISSUE #150071: Missing Linker Relaxation Relocations after Assembly Relocation
The following example, when assembled with `llvm-mc --triple=riscv32 -mattr=+relax,+experimental-xqcilb` seems to have a bug:

```
.global foo

bar:
  jal x1, foo
  bne a0, a1, bar
  ret
```

Looking at the `llvm-objdump -dr` output (this has not been truncated)

```
jal.o:  file format elf32-littleriscv

Disassembly of section .text:

00000000 <bar>:
       0: c01f 0000 0000        qc.e.jal        0x0 <bar>
                        00000000:  R_RISCV_VENDOR       QUALCOMM
                        00000000:  R_RISCV_CUSTOM195    foo
                        00000000:  R_RISCV_RELAX        *ABS*
       6: feb51de3      bne     a0, a1, 0x0 <bar>
       a: 8082          ret
```

The `bne` is branching over a relaxable instruction, but has been resolved instead of having a relocation on it. This means that if the linker relaxes the `qc.e.jal` instruction, the `bne` will be incorrect.

I think the sequence of what is happening is:
- `jal x1, foo` is parsed as `JAL`, as would be expected.
- `JAL` is compressed to `C_JAL` in `RISCVAsmParser::emitToStreamer`
- `C_JAL` is emitted, with a `RISCV::fixup_riscv_rvc_jump` fixup, which is not marked as linker relaxable.
- `C_JAL` is jumping to an undefined symbol, so will be changed with `relaxInstruction`
- `relaxInstruction` first relaxes to `JAL` and then the second time to `QC_E_JAL`
- `QC_E_JAL` has a `RISCV::fixup_riscv_qc_e_call_plt` fixup, which is marked as linker relaxable!
- nothing now marks the fragment and the section as linker relaxable.
- When it comes time to apply the fixup to `bne`, I think `RISCVAsmBackend::isPCRelFixupResolved` is returning that the fixup is fully resolved, when it shouldn't be.

I think the relaxation of `JAL` to `QC_E_JAL` might be the only one we have right now which changes the fixup from being non-linker-relaxable to being linker-relaxable. (This is not going to be the case indefinitely, as there are now linker relaxations for `R_RISCV_JAL`, so the `C_JAL` to `JAL` relaxation will have the same bug once we update `RISCVMCCodeEmitter::getImmOpValue` for new relaxations in the psABI since we did this last time)

I think this is still violating invariants of the code, that fragments (and their parent sections) with linker relaxable fixups should be marked as linker relaxable.

### PR DESCRIPTION
**Pull request by lenary**
Span-dependent instructions on RISC-V interact in a complex manner with linker relaxation. The span-dependent assembler algorithm implemented in LLVM has to start with the smallest version of an instruction and then only make it larger, so we compress instructions before emitting them to the streamer.

When the instruction is streamed, the information that the instruction (or rather, the fixup on the instruction) is linker relaxable must be accurate, even though the assembler relaxation process may transform a not-linker-relaxable instruction/fixup into one that that is linker relaxable, for instance `c.jal` becoming `qc.e.jal`, or `bne` getting turned into `beq; jal` (the `jal` is linker relaxable).

I do not fully understand why the linker relaxation information has to be accurate at streaming-time if the assembler knows it may be relaxing the instruction (i.e., potentially making it longer), but I have been told this is the case.

In order for this to work, the following things have to happen:
- Any instruction/fixup which might be relaxed to a linker-relaxable instruction/fixup, gets marked as `RelaxCandidate = true` in RISCVMCCodeEmitter.
- In RISCVAsmBackend, when emitting the `R_RISCV_RELAX` relocation, we have to check that the relocation/fixup kind is one that may need a relax relocation, as well as that it is marked as linker relaxable (the latter will not be set if relaxation is disabled).
- Linker Relaxable instructions streamed to a Relaxable fragment need to mark the fragment and its section as linker relaxable.

I also added more debug output for Sections/Fixups which are marked Linker Relaxable.

This results in more relocations, when these PC-relative fixups cross an instruction with a fixup that is resolved as not linker-relaxable but caused the fragment to be marked linker relaxable at streaming time (i.e. `c.j`).

Fixes: #150071

### CODE REVIEW

File: llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp [hunk 1]
```diff
@@ -803,6 +803,41 @@ void RISCVAsmBackend::maybeAddVendorReloc(const MCFragment &F,
   Asm->getWriter().recordRelocation(F, VendorFixup, VendorTarget, VendorValue);
 }
 
+static bool fixupGetsRelaxRelocation(const MCFixupKind Kind) {
+  switch (Kind) {
```
Comment (MaskRay) [inline llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp:807]: Why does any fixup need special treatment? check-llvm-mc still passes if fixupGetsRelaxRelocation returns false.

Comment (lenary) [reply llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp:807]: if we don't have this, we'll end up with R_RISCV_RELAX on compressed instructions which are in-range but require a relocation (i.e. reference something close but the other side of something relaxable). I'll make a testcase for this tomorrow.

Comment (lenary) [reply llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp:807]: I added more to the linker-relaxation-pr150071.s test which will fail if this either always returns `true` or `false`.

The problem is about the over-approximation of `RelaxCandidate = true` in the MCCodeEmitter. Now, many more relocations are marked as linkerrelaxable, which is good, but those might be pc-relative resolvable, like a jump over non-relaxable data. In these cases we want to allow the fixup itself to resolve if possible (these will only be left if they are in range, when xqcilb is enabled).

And then we want to make sure, if a fixup is not resolved, that only fixups expecting R_RISCV_RELAX get that relocation, even if the fixup is marked linker relaxable.

File: llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp [hunk 2]
```diff
@@ -861,25 +896,24 @@ bool RISCVAsmBackend::addReloc(const MCFragment &F, const MCFixup &Fixup,
...
     Asm->getWriter().recordRelocation(F, Fixup, Target, FixedValue);
-  }
 
-  if (Fixup.isLinkerRelaxable()) {
-    auto FA = MCFixup::create(Fixup.getOffset(), nullptr, ELF::R_RISCV_RELAX);
-    Asm->getWriter().recordRelocation(F, FA, MCValue::get(nullptr),
-                                      FixedValueA);
+    // Some Fixups may get a RELAX relocation, record it (directly) after we
+    // add the relocation.
+    maybeAddRelaxReloc(F, Fixup);
```
[the remark this answers is not in the document]
Comment (lenary) [reply llvm/lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp]: Done

File: llvm/test/MC/RISCV/linker-relaxation-pr150071.s [hunk 3]
```diff
@@ -0,0 +1,79 @@
+# RUN: llvm-mc --triple=riscv32 -mattr=+relax,+experimental-xqcilb,+experimental-xqcibi \
```
[the remark this answers is not in the document]
Comment (lenary) [reply llvm/test/MC/RISCV/linker-relaxation-pr150071.s]: Done

**Review by MaskRay — APPROVED** [review]

**Comment by lenary** [comment]
Yeah, I'll see what I can do for 21.x, I do have the entirely different implementation which I tested and is working for us downstream.

**Comment by lenary** [comment]
/pull-request https://github.com/llvm/llvm-project/pull/153670
