### PR TITLE
[Clang] enhance error recovery with RecoveryExpr for trailing commas in call arguments

### LINKED ISSUE #100921: Build a RecoveryExpr for a call expression with a trailing command in the argument list
For the following code:

```c++
void func(int a, int b);

int main() {
  f(1,);
}
```

the AST contains no descendants for the `CompoundStmt` of main:

```
`-FunctionDecl 0x555de3b98098 <line:3:1, line:5:1> line:3:5 main 'int ()'
  `-CompoundStmt 0x555de3b981d0 <col:12, line:5:1>
```

It would be nice if the parser could recover from this and build an AST similar to the one that would be built if the trailing comma was not present:

```c++
void func(int a, int b);

int main() {
  f(1);
}
```

Here the number of arguments is still incorrect, but a `RecoveryExpr` is successfully built:

```
`-FunctionDecl 0x5589d407d098 <line:3:1, line:5:1> line:3:5 main 'int ()'
  `-CompoundStmt 0x5589d407d248 <col:12, line:5:1>
    `-RecoveryExpr 0x5589d407d218 <line:4:3, col:6> '<dependent type>' contains-errors lvalue
      |-UnresolvedLookupExpr 0x5589d407d170 <col:3> '<overloaded function type>' lvalue (ADL) = 'f' empty
      `-IntegerLiteral 0x5589d407d1b0 <col:5> 'int' 1
```

The `RecoveryExpr` is important because it allows e.g. go-to-definition in clangd to work on the function name.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #100921

### CODE REVIEW

File: clang/test/AST/ast-dump-recovery.cpp [hunk 1]
```diff
@@ -32,6 +32,21 @@ void test_invalid_call(int s) {
...
+  // CHECK-NEXT: |-UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  // CHECK-NEXT: `-IntegerLiteral {{.*}} 'int' 1
+  some_func2(1, );
+}
+
+void test_invalid_call_3() {
+  // CHECK:   `-RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: |-UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  // CHECK-NEXT: `-IntegerLiteral {{.*}} 'int' 1
+  some_func2(1);
```
Comment (hokein) [inline clang/test/AST/ast-dump-recovery.cpp:47]: I think this case is already covered below, we can remove it.

File: clang/test/AST/ast-dump-recovery.cpp [hunk 2]
```diff
@@ -32,6 +32,21 @@ void test_invalid_call(int s) {
   int var = some_func(undef1);
 }
 
+int some_func2(int a, int b);
+void test_invalid_call_2() {
+  // CHECK:   `-RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: |-UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  // CHECK-NEXT: `-IntegerLiteral {{.*}} 'int' 1
+  some_func2(1, );
```
Comment (hokein) [inline clang/test/AST/ast-dump-recovery.cpp:40]: Does the case `some_func2(,);` work?

**Review by hokein — COMMENTED** [review]
Thanks, this is nice.

Can you also add a release note?

File: clang/lib/Parse/ParseDecl.cpp [hunk 3]
```diff
@@ -2890,8 +2890,9 @@ Decl *Parser::ParseDeclarationAfterDeclaratorAndAttributes(
       // ProduceConstructorSignatureHelp only on VarDecls.
       ExpressionStarts = SetPreferredType;
     }
-
-    bool SawError = ParseExpressionList(Exprs, ExpressionStarts);
+    bool HasTrailingComma = false;
+    bool SawError =
+        ParseExpressionList(Exprs, ExpressionStarts, HasTrailingComma);
```
Comment (Fznamznon) [inline clang/lib/Parse/ParseDecl.cpp:2895]: This change doesn't seem necessary.

Comment (a-tarasyuk) [reply clang/lib/Parse/ParseDecl.cpp]: @Fznamznon yes, thanks for pointing that out. I've remove it

File: clang/test/AST/ast-dump-recovery.cpp (hunk 2 above)
Comment (hokein) [reply clang/test/AST/ast-dump-recovery.cpp:40]: I think this is addressed on the latest revision, please update the comment next time.

File: clang/test/AST/ast-dump-recovery.cpp [hunk 4]
```diff
@@ -32,6 +32,26 @@ void test_invalid_call(int s) {
...
+void test_invalid_call_3() {
+  // CHECK:   `-RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: -UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  some_func2(,);
+}
+
+void test_invalid_call_4() {
+  // CHECK:   `-RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: -UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  some_func2(,,);
```
Comment (hokein) [inline clang/test/AST/ast-dump-recovery.cpp:52]: nit: we can bundle all three cases into a single function, as they all tests the trailing comma case. 

Can you also check the `some_func2(,1);` case?

Comment (hokein) [reply clang/test/AST/ast-dump-recovery.cpp:52]: I should have been clearer earlier. I think it’s fine that clang doesn’t handle recovery well in this case. I’m just curious about it and not suggesting you address it.

Comment (a-tarasyuk) [reply clang/test/AST/ast-dump-recovery.cpp]: @hokein Thanks for the clarification! I've updated the tests

File: clang/lib/Parse/ParseExpr.cpp [hunk 5]
```diff
@@ -3705,6 +3713,12 @@ bool Parser::ParseExpressionList(SmallVectorImpl<Expr *> &Exprs,
     Token Comma = Tok;
     ConsumeToken();
     checkPotentialAngleBracketDelimiter(Comma);
+
+    if (Tok.is(tok::r_paren)) {
+      if (HasTrailingComma)
+        *HasTrailingComma = true;
+      break;
+    }
```
Comment (zyn0217) [inline clang/lib/Parse/ParseExpr.cpp:3721]: We can't handle the 'r_paren' at the caller side i.e. somewhere in ParsePostfixExpressionSuffix()?

Comment (a-tarasyuk) [reply clang/lib/Parse/ParseExpr.cpp:3721]: @zyn0217 To handle a trailing comma, the previous token has to be a comma, and the next one a `r_paren`.

https://github.com/llvm/llvm-project/blob/46f43b6d92e49b80df13e8a537a95767ffbaac9f/clang/lib/Parse/ParseExpr.cpp#L3702-L3707

File: clang/test/AST/ast-dump-recovery.cpp [hunk 6]
```diff
@@ -32,6 +32,25 @@ void test_invalid_call(int s) {
...
+  // CHECK:   -RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: `-UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  some_func2(,,);
+
+  // CHECK:   `-RecoveryExpr {{.*}} 'int' contains-errors
+  // CHECK-NEXT: |-UnresolvedLookupExpr {{.*}} '<overloaded function type>' lvalue (ADL) = 'some_func2'
+  // CHECK-NEXT: `-IntegerLiteral {{.*}} 'int' 1
+  some_func2(1,);
+
+  // CHECK-NOT: `-RecoveryExpr
```
Comment (hokein) [inline clang/test/AST/ast-dump-recovery.cpp:50]: nit: maybe add a `FIXME: recover for this case`, otherwise it is unclear whether `CEHCK-NOT` is intended or not.

**Review by hokein — APPROVED** [review]
Thanks, looks good.

File: clang/test/AST/ast-dump-recovery.cpp (hunk 6 above)
Comment (a-tarasyuk) [reply clang/test/AST/ast-dump-recovery.cpp:51]: @hokein I've added `FIXME` comment.

**Comment by shafik** [comment]
This PR is linked to the following regression: https://github.com/llvm/llvm-project/issues/125225

**Comment by a-tarasyuk** [comment]
@shafik thanks for pointing that out! I'll check it ASAP

**Comment by hokein** [comment]
I have a fix for it #125232
