### PR TITLE
[libc++] Overhaul the PSTL dispatching mechanism

### LINKED ISSUE #70718: [libc++][PSTL] Dispatching to default algorithms is broken in some cases (at least std::any_of)
The default implementation of `std::none_of` in the PSTL is ([here](https://github.com/llvm/llvm-project/blob/68c384676cf92289d823576f915ed296d209354f/libcxx/include/__algorithm/pstl_any_all_none_of.h#L118-L123)):

```
      [&](_ForwardIterator __g_first, _ForwardIterator __g_last, _Pred __g_pred) -> optional<bool> {
        auto __res = std::__any_of(__policy, __g_first, __g_last, __g_pred);
        if (!__res)
          return nullopt;
        return !*__res;
      },
```

Notice how this calls `std::__any_of` with lvalues `__g_first, __g_last, __g_pred`. Now, `__any_of` is implemented like ([here](https://github.com/llvm/llvm-project/blob/68c384676cf92289d823576f915ed296d209354f/libcxx/include/__algorithm/pstl_any_all_none_of.h#L38-L51)):

```
template <class _ExecutionPolicy, class _ForwardIterator, class _Predicate, ...>
optional<bool>
__any_of(_ExecutionPolicy&& __policy, _ForwardIterator&& __first, _ForwardIterator&& __last, _Predicate&& __pred) {
  return std::__pstl_frontend_dispatch(
      _LIBCPP_PSTL_CUSTOMIZATION_POINT(__pstl_any_of, _RawPolicy),
      [&](_ForwardIterator __g_first, _ForwardIterator __g_last, _Predicate __g_pred) -> optional<bool> {
        auto __res = std::__find_if(__policy, __g_first, __g_last, __g_pred);
        if (!__res)
          return nullopt;
        return *__res != __g_last;
      },
      std::move(__first),
      std::move(__last),
      std::move(__pred));
}
```

Since `__any_of` is called with lvalues and we're taking universal references, when `none_of` calls `__any_of` we get the following deduction: `_ForwardIterator&& == _Iter& &&` for some ref-unqualified type `_Iter`. As a result, the lambda declaration inside `__any_of` basically has signature `[&](_Iter&, _Iter&, _Predicate)` and that doesn't work since we're trying to pass it a rvalue (`std::move(__first)` & al).

This issue happens whenever the default implementation of `std::any_of` is used. It can be seen by removing:

```
libcxx/include/__algorithm/pstl_backends/cpu_backends/any_of.h
```

Normally, things should work even in that case because `any_of` is not a mandatory algorithm for general backends.

### PR DESCRIPTION
**Pull request by ldionne**
The experimental PSTL's current dispatching mechanism was designed with
flexibility in mind. However, while reviewing the in-progress OpenMP
backend, I realized that the dispatching mechanism based on ADL and
default definitions in the frontend had several downsides. To name a
few:

1. The dispatching of an algorithm to the back-end and its default
   implementation is bundled together via `_LIBCPP_PSTL_CUSTOMIZATION_POINT`.
   This makes the dispatching really confusing and leads to annoyances
   such as variable shadowing and weird lambda captures in the front-end.
2. The distinction between back-end functions and front-end algorithms
   is not as clear as it could be, which led us to call one where we meant
   the other in a few cases. This is bad due to the exception requirements
   of the PSTL: calling a front-end algorithm inside the implementation of
   a back-end is incorrect for exception-safety.
3. There are two levels of back-end dispatching in the PSTL, which treat
   CPU backends as a special case. This was confusing and not as flexible
   as we'd like. For example, there was no straightforward way to dispatch
   all uses of `unseq` to a specific back-end from the OpenMP backend,
   or for CPU backends to fall back on each other.

This patch rewrites the backend dispatching mechanism to solve these
problems, but doesn't touch any of the actual implementation of
algorithms. Specifically, this rewrite has the following characteristics:

- All back-ends are full top-level backends defining all the basis operations
required by the PSTL. This is made realistic for CPU backends by providing
the CPU-based basis operations as simple helpers that can easily be reused
when defining the PSTL basis operations.

- The default definitions for algorithms are separated from their dispatching
logic and grouped in families instead, based on the basis operation they
require for their default implementation.

- The front-end is thus simplified a whole lot and made very consistent
for all algorithms, which makes it easier to audit the front-end for
things like exception-correctness, appropriate forwarding, etc.

Fixes #70718

### CODE REVIEW

**Comment by ldionne** [comment]
This is a draft patch. I'm going to be chipping away at it by extracting smaller reviews like #88127.

File: libcxx/include/__pstl/dispatch.h [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+#endif
+
+_LIBCPP_PUSH_MACROS
+#include <__undef_macros>
+
+_LIBCPP_BEGIN_NAMESPACE_STD
+namespace __pstl {
+
+template <template <class, class> class _Algorithm, class _Backend, class _ExecutionPolicy, class = void>
+struct __is_implemented : false_type {};
```
Comment (philnik777) [inline libcxx/include/__pstl/dispatch.h:30]: Might as well make it a variable template?

File: libcxx/include/__pstl/dispatch.h [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+template <template <class, class> class _Algorithm, class _ExecutionPolicy>
+constexpr bool __cant_find_backend_for = false;
+
+template <template <class, class> class _Algorithm, class _BackendConfiguration, class _ExecutionPolicy>
+struct __find_first_implemented;
+
+template <template <class, class> class _Algorithm, class _ExecutionPolicy>
+struct __find_first_implemented<_Algorithm, __backend_configuration<>, _ExecutionPolicy> {
+  static_assert(__cant_find_backend_for<_Algorithm, _ExecutionPolicy>,
+                "Could not find a PSTL backend for the given algorithm and execution policy");
```
Comment (philnik777) [inline libcxx/include/__pstl/dispatch.h:49]:
```suggestion
  static_assert(false, "Could not find a PSTL backend for the given algorithm and execution policy");
```

File: libcxx/include/__pstl/handle_exception.h [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+#endif
+
+_LIBCPP_PUSH_MACROS
+#include <__undef_macros>
+
+_LIBCPP_BEGIN_NAMESPACE_STD
+namespace __pstl {
+
+template <class _BackendFunction, class... _Args>
+_LIBCPP_HIDE_FROM_ABI _LIBCPP_ALWAYS_INLINE auto __handle_exception_impl(_Args&&... __args) noexcept {
```
Comment (philnik777) [inline libcxx/include/__pstl/handle_exception.h:29]: Why the `always_inline`?

File: libcxx/include/__pstl/handle_exception.h [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+//===----------------------------------------------------------------------===//
+
+#ifndef _LIBCPP___PSTL_HANDLE_EXCEPTION_H
+#define _LIBCPP___PSTL_HANDLE_EXCEPTION_H
+
+#include <__config>
+#include <__utility/forward.h>
+#include <__utility/move.h>
+#include <new> // __throw_bad_alloc
+#include <optional>
```
Comment (philnik777) [inline libcxx/include/__pstl/handle_exception.h:16]: Why is this include required?

**Review by philnik777 — COMMENTED** [review]
Mostly LGTM, just some minor nits.

File: libcxx/include/__pstl/handle_exception.h (hunk 4 above)
Comment (ldionne) [reply libcxx/include/__pstl/handle_exception.h:16]: For `nullopt`. It's kind of annoying to add `optional` everywhere, but we really need it for propagating errors.

File: libcxx/include/__pstl/handle_exception.h (hunk 3 above)
Comment (ldionne) [reply libcxx/include/__pstl/handle_exception.h:29]: I have no idea, removed.

File: libcxx/include/__algorithm/pstl.h [hunk 5]
```diff
@@ -509,67 +151,31 @@ equal(_ExecutionPolicy&& __policy,
...
-          (void)__policy; // Avoid unused lambda capture warning
-          return std::equal(
-              std::move(__g_first1),
-              std::move(__g_last1),
-              std::move(__g_first2),
-              std::move(__g_last2),
-              std::move(__g_pred));
-        }
-      },
+  using _Implementation = __pstl::__dispatch<__pstl::__equal_3leg, __pstl::__current_configuration, _RawPolicy>;
```
[the remark this answers is not in the document]
Comment (ldionne) [reply libcxx/include/__algorithm/pstl.h:172]: This variant of `std::equal` is often referred to as the "3 leg" version because it takes 3 iterators `[first1, last1)` and `first2` as opposed to "4 legs" which would be `[first1, last1)` and `[first2, last2)`. It's not an official term or anything, but I needed something to differentiate between the two.

File: libcxx/include/__pstl/dispatch.h (hunk 1 above)
Comment (ldionne) [reply libcxx/include/__pstl/dispatch.h:30]: Done.

File: libcxx/include/__pstl/dispatch.h (hunk 2 above)
Comment (ldionne) [reply libcxx/include/__pstl/dispatch.h:49]: As the comment above says:

```c++
// Helpful to provide better error messages. This will show the algorithm and the execution policy
// in the compiler diagnostic.
```

This makes a good difference when hitting a compiler error due to a misconfigured backend.
