### PR TITLE
[Analyzer][CFG] Correctly handle rebuilt default arg and default init expression

### LINKED ISSUE #93725: [clang][diagnostics] `-Wunreachable-code` prints incorrect source range if a constructor has a default value set to a builtin
Originally reported in https://github.com/llvm/llvm-project/pull/91879#issuecomment-2136251656

After https://github.com/llvm/llvm-project/pull/91879, unreachable calls to constructors with default parameters set to builtins would underline the builtin as the source range instead of the call to the constructor - e.g.

```cpp
struct A {
  explicit A(int = __builtin_LINE());
};

int h(int a) {
  return 3;
  A();
}
```

used to produce the diagnostic
```
<source>:7:3: error: code will never be executed [-Werror,-Wunreachable-code]
    7 |   A();
      |   ^~~
```

but now produces the (incorrect) diagnostic
```<source>:2:20: error: code will never be executed [-Werror,-Wunreachable-code]
    2 |   explicit A(int = __builtin_LINE());
      |                    ^~~~~~~~~~~~~~~~
```

godbolt: https://godbolt.org/z/6TEdrx55d

### PR DESCRIPTION
**Pull request by yronglin**
Clang currently support extending lifetime of object bound to reference members of aggregates, that are created from default member initializer. This PR address this change and updaye CFG and ExprEngine.

This PR reapply https://github.com/llvm/llvm-project/pull/91879.
Fixes https://github.com/llvm/llvm-project/issues/93725.

### CODE REVIEW

**Review by steakhal — APPROVED** [review]
LGTM, thanks!

**Comment by yronglin** [comment]
Thanks for the review! @cor3ntin Do you have any comments on the changes of `CXXDefaultArgExpr` and `CXXDefaultInitExpr`?

File: clang/include/clang/AST/Stmt.h [hunk 1]
```diff
@@ -850,11 +854,17 @@ class alignas(void *) Stmt {
     LLVM_PREFERRED_TYPE(ExprBitfields)
     unsigned : NumExprBits;
 
-    /// Whether this CXXDefaultInitExprBitfields rewrote its argument and stores
-    /// a copy.
+    /// Whether this CXXDefaultInitExpr rewrote its argument and stores
+    /// a copy, unlike HasRebuiltInit, when this flag is true, the argument may
+    /// be partial rebuilt.
```
Comment (cor3ntin) [inline clang/include/clang/AST/Stmt.h:859]: Do we really need both? Can you explain why? What do you mean by partially?

Comment (cor3ntin) [inline clang/include/clang/AST/Stmt.h:859]:
```suggestion
    /// Whether this CXXDefaultInitExpr rewrote its argument and stores
    /// a copy, unlike HasRebuiltInit, when this flag is true, the argument may
    /// be partially rebuilt.
```

Comment (yronglin) [reply clang/include/clang/AST/Stmt.h:859]: For example:
```c++
struct A {};
struct B {
    A a = A{};
};

B c{}, d{};

```
```
|-CXXRecordDecl 0x13f1289d8 <line:2:1, line:4:1> line:2:8 referenced struct B definition
| |-DefinitionData pass_in_registers aggregate standard_layout trivially_copyable literal has_constexpr_non_copy_move_ctor can_const_default_init
| | |-DefaultConstructor exists non_trivial constexpr needs_implicit defaulted_is_constexpr
| | |-CopyConstructor simple trivial has_const_param needs_implicit implicit_has_const_param
| | |-MoveConstructor exists simple trivial needs_implicit
| | |-CopyAssignment simple trivial has_const_param needs_implicit implicit_has_const_param
| | |-MoveAssignment exists simple trivial needs_implicit
| | `-Destructor simple irrelevant trivial constexpr needs_implicit
| |-CXXRecordDecl 0x13f128b10 <col:1, col:8> col:8 implicit struct B
| `-FieldDecl 0x13f149808 <line:3:5, col:13> col:7 a 'A'
|   `-CXXFunctionalCastExpr 0x13f149aa0 <col:11, col:13> 'A' functional cast to A <NoOp>
|     `-InitListExpr 0x13f1498f0 <col:12, col:13> 'A'
|-VarDecl 0x13f149b18 <line:6:1, col:5> col:3 c 'B' listinit
| `-InitListExpr 0x13f149c10 <col:4, col:5> 'B'
|   `-CXXDefaultInitExpr 0x13f149c58 <col:5> 'A' has rewritten init
|     `-CXXFunctionalCastExpr 0x13f149aa0 <line:3:11, col:13> 'A' functional cast to A <NoOp>
|       `-InitListExpr 0x13f1498f0 <col:12, col:13> 'A'
`-VarDecl 0x13f149ea0 <line:6:1, col:10> col:8 d 'B' listinit
  `-InitListExpr 0x13f149f48 <col:9, col:10> 'B'
    `-CXXDefaultInitExpr 0x13f149f90 <col:10> 'A' has rewritten init
      `-CXXFunctionalCastExpr 0x13f149aa0 <line:3:11, col:13> 'A' functional cast to A <NoOp>
        `-InitListExpr 0x13f1498f0 <col:12, col:13> 'A'
```
The sub-expr in `CXXDefaultInitExpr` will appears multiple times in the AST. We can't add the default argument if it's not rewritten because we could end up with the same expression appearing multiple times.

**Review by cor3ntin — CHANGES_REQUESTED** [review]
I'd like more time to think about this change and discuss it with @AaronBallman / @erichkeane

**Comment by erichkeane** [comment]
> I'd like more time to think about this change and discuss it with @AaronBallman / @erichkeane

I'm having some doubts too.  This seems like the sort of thing we usually trace by knowing the original template, and seeing if we aren't that.  So find the thing that owns this expression, and walk over to see if the primary template matches this one (though that isn't a perfect simile here).

**Comment by yronglin** [comment]
When the it was used, is it possible for us to rebuild all default-arg and default-init?

**Comment by yronglin** [comment]
friendly ping~

**Comment by yronglin** [comment]
friendly ping~

**Comment by yronglin** [comment]
friendly ping~

File: clang/include/clang/AST/Stmt.h (hunk 1 above)
Comment (yronglin) [reply clang/include/clang/AST/Stmt.h]: Fixed

**Comment by yronglin** [comment]
friendly ping~

**Comment by erichkeane** [comment]
I don't have a great solution for this unfortuantely, but `HasRebuiltInit` doesn't seem right to me, it looks like we're just trying to smuggle a bit around for a few .  First, it doesn't seem clear to me why the 'rebuilt-ness' of an initializer should have anything to do with anything.  

Second, whether or not it was rebuilt should be a property of that expression perhaps?  The init itself should know whether it needs to be built again or not.

I honestly don't think I understand the requirement well enough, but I DO think this looks/smells incorrect here.  It seems to me the static analyzer should be responsible for this perhaps, and not the AST.  But again, it isn't clear to me that is the case.

**Comment by cor3ntin** [comment]
I think `HasRebuiltInit` is just `CXXDefaultArgExpr::getExpr() != CXXDefaultArgExpr::getParam()->getDefaultArg()`

@yronglin Can you modify `hasRebuiltInit()` to be and see if anything breaks? (and if it works we don't need the bit)

```cpp
bool hasRebuiltInit() const { return getExpr() != getParam()->getDefaultArg(); }`
```

**Comment by yronglin** [comment]
@cor3ntin @erichkeane Many thanks for the review! 

> @yronglin Can you modify hasRebuiltInit() as follow and see if anything breaks? (and if it works we don't need the bit)

Sure, let me give a try. 

> It seems to me the static analyzer should be responsible for this perhaps, and not the AST. 

Yeah, this function was only used in static analyzer now, maybe we can move it into static analyzer's code.

**Comment by yronglin** [comment]
I've made changes in Sema, if the rewritten-expr same as `Field->getInClassInitializer()`/`Param->getDefaultArg()`, this PR will set `{CXXDefaultArgExprBits, CXXDefaultInitExprBits}.HasRewrittenInit` false.

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -5570,8 +5570,10 @@ ExprResult Sema::BuildCXXDefaultArgExpr(SourceLocation CallLoc,
           /*SkipImmediateInvocations=*/NestedDefaultChecking))
     return ExprError();
 
+  Expr *RewrittenExpr = Init == Param->getDefaultArg() ? nullptr : Init;
```
Comment (erichkeane) [inline clang/lib/Sema/SemaExpr.cpp:5573]:
```suggestion
  Expr *RewrittenExpr = (Init == Param->getDefaultArg() ? nullptr : Init);
```

MINOR preference to reverse this condition?  But not sure enough to suggest this.

**Review by erichkeane — COMMENTED** [review]
I'm WAY happier with this.  I don't have the ability to review the SA stuff well enough to give an approval, but the rest of the stuff is good.  1 Nit, else LGTM.

File: clang/lib/Sema/SemaExpr.cpp (hunk 2 above)
Comment (yronglin) [reply clang/lib/Sema/SemaExpr.cpp]: Fixed

**Comment by yronglin** [comment]
> I'm WAY happier with this. I don't have the ability to review the SA stuff well enough to give an approval, but the rest of the stuff is good. 1 Nit, else LGTM.

Thanks for the review! There are no functional changes in Static Analyzer after @steakhal's +1 (just renamed a function).

**Review by cor3ntin — APPROVED** [review]
Much better!
Thanks a lot for working on this

**Comment by zmodem** [comment]
We're hitting an assert after this:

```
clang/lib/Analysis/CFG.cpp:822: void (anonymous namespace)::CFGBuilder::appendStmt(CFGBlock *, const Stmt *): Assertion `!isa<Expr>(S) || cast<Expr>(S)->IgnoreParens() == S' failed.
```

See https://crbug.com/394015869 for stack trace and reproducer. I'll revert for now to unbreak the build, and start a creduce to see if we can get a smaller repro.

**Comment by zmodem** [comment]
creduce'd reproducer:

```
$ cat /tmp/a.cc
class Location {
public:
  static Location Current(int = __builtin_LINE());
};
class DOMMatrix;
class BasicMember {
public:
  BasicMember(DOMMatrix *);
};
template <typename> using Member = BasicMember;
class ExceptionState {
public:
  ExceptionState &ReturnThis();
  ExceptionState(Location);
};
class NonThrowableExceptionState : public ExceptionState {
public:
  NonThrowableExceptionState(Location location = Location::Current())
      : ExceptionState(location) {}
};
class DOMMatrix {
public:
  static DOMMatrix *
  Create(int *, ExceptionState & = (NonThrowableExceptionState().ReturnThis()));
};
class CSSMatrixComponent {
  int CSSMatrixComponent_matrix;
  CSSMatrixComponent()
      : matrix_(DOMMatrix::Create(&CSSMatrixComponent_matrix)) {}
  Member<DOMMatrix> matrix_;
};
$ clang -c -Wunreachable-code-aggressive /tmp/a.cc
clang: /work/llvm-project/clang/lib/Analysis/CFG.cpp:822: void (anonymous namespace)::CFGBuilder::appendStmt(CFGBlock *, const Stmt *): Assertion `!isa<Expr>(S) || cast<Expr>(S)->IgnoreParens() == S' failed.
```
