### PR TITLE
To support unlimited polymorphic argument for intrinsic MERGE.

### LINKED ISSUE #143582: [flang] Unlimited polymorphic argument for intrnsic MERGE caused FIR verification failure
Consider the following code:
```

  type base
    real :: r1
  end type

contains
  SUBROUTINE Sub(Arg1, Arg2)
  !CLASS(base) :: Arg1(:, :), Arg2(:, :)                       !! Workaround
  CLASS(*) :: Arg1(:, :), Arg2(:, :)
  LOGICAL :: Mask(2, 2) = .true.

  SELECT TYPE ( V=>MERGE(Arg1, Arg2, Mask) )
    CLASS DEFAULT
      print*, "in class default"
  END SELECT

  END SUBROUTINE
end
```

Flang fails at the compile time with
```
error: loc("/home/cdchen/temp/SltArrFuncPolyPtr.f":11:3): nonscalar intrinsic argument
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/cdchen/FLANG/build/bin/flang -fc1 -triple powerpc64-ibm-aix7.2.0.0 -emit-obj -ffree-form -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -target-cpu pwr7 -resource-dir /home/cdchen/FLANG/build/lib/clang/21 -mframe-pointer=all -o /tmp/SltArrFuncPolyPtr-81bc14.o -x f95 SltArrFuncPolyPtr.f
flang-21: error: unable to execute command: IOT/Abort trap
flang-21: error: flang frontend command failed due to signal (use -v to see invocation)
flang version 21.0.0git (git@github.com:DanielCChen/llvm-project.git b896d262ebc530a92327b912b2bd5ac3b0bb0e56)
Target: powerpc64-ibm-aix7.2.0.0
Thread model: posix
InstalledDir: /home/cdchen/FLANG/build/bin
Build config: +assertions
flang-21: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
flang-21: note: diagnostic msg: /tmp/SltArrFuncPolyPtr-0a9010
flang-21: note: diagnostic msg: /tmp/SltArrFuncPolyPtr-0a9010.sh
flang-21: note: diagnostic msg:
```

If I use the workaround marked in the code, it compiles successfully.

### PR DESCRIPTION
**Pull request by DanielCChen**
This PR will allow unlimited polymorphic arguments `class(*)` for intrinsics.

Fixes #143582

### CODE REVIEW

File: flang/include/flang/Optimizer/Dialect/FIRType.h [hunk 1]
```diff
@@ -372,6 +372,9 @@ bool isBoxedRecordType(mlir::Type ty);
 /// Return true iff `ty` is a type that contains descriptor information.
 bool isTypeWithDescriptor(mlir::Type ty);
 
+/// Return true if CLASS(*)
+bool isClassStarType(mlir::Type ty);
```
Comment (jeanPerier) [inline flang/include/flang/Optimizer/Dialect/FIRType.h]: nit: please move the declaration near `isUnlimitedPolymorphicType` and `isAssumedType`.

**Review by jeanPerier — APPROVED** [review]
Thanks
