### PR TITLE
[Mips] Fix compiler crash when returning fp128 after calling a functi…

### LINKED ISSUE #96432: Compiler crash when targeting `mips64` when returning `fp128` after calling a function returning `{ i8, i128 }`
Attempting to compiler the following IR causes LLVM to crash ([compiler explorer](https://godbolt.org/z/cqKz4Ybxb)):

```llvm
target triple = "mips64el-unknown-linux-gnuabi64"

define fp128 @foo() {
  call { i8, i128 } @bar()
  ret fp128 0xL00000000000000000000000000000000
}

define { i8, i128 } @bar() {
  ret { i8, i128 } zeroinitializer
}
```

Crash backtrace:

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'MIPS DAG->DAG Pattern Instruction Selection' on function '@foo'
 #0 0x0000000003739428 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3739428)
 #1 0x0000000003736dac SignalHandler(int) Signals.cpp:0:0
 #2 0x0000718fcb642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00000000034c3bb3 llvm::SelectionDAG::FoldConstantArithmetic(unsigned int, llvm::SDLoc const&, llvm::EVT, llvm::ArrayRef<llvm::SDValue>, llvm::SDNodeFlags) (/opt/compiler-explorer/clang-trunk/bin/llc+0x34c3bb3)
 #4 0x00000000034c79f4 llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::EVT, llvm::SDValue, llvm::SDNodeFlags) (/opt/compiler-explorer/clang-trunk/bin/llc+0x34c79f4)
 #5 0x0000000003430a84 getCopyFromParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue const*, unsigned int, llvm::MVT, llvm::EVT, llvm::Value const*, llvm::SDValue, std::optional<unsigned int>, std::optional<llvm::ISD::NodeType>) (.isra.0) SelectionDAGBuilder.cpp:0:0
 #6 0x000000000343fb56 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (/opt/compiler-explorer/clang-trunk/bin/llc+0x343fb56)
 #7 0x000000000344172d llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (/opt/compiler-explorer/clang-trunk/bin/llc+0x344172d)
 #8 0x0000000003462354 llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*, llvm::TargetLowering::PtrAuthInfo const*) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3462354)
 #9 0x0000000003478998 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3478998)
#10 0x000000000348d487 llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x348d487)
#11 0x0000000003505a53 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void, true, llvm::BasicBlock>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void, true, llvm::BasicBlock>, false, true>, bool&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3505a53)
#12 0x0000000003507124 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3507124)
#13 0x0000000003508f94 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3508f94)
#14 0x00000000015c3c1b llvm::MipsDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x15c3c1b)
#15 0x00000000034f8ac1 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x34f8ac1)
#16 0x000000000283368b llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#17 0x0000000002d72152 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2d72152)
#18 0x0000000002d722d1 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2d722d1)
#19 0x0000000002d73f80 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2d73f80)
#20 0x0000000000846ed4 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#21 0x000000000073ece6 main (/opt/compiler-explorer/clang-trunk/bin/llc+0x73ece6)
#22 0x0000718fcb629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#23 0x0000718fcb629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#24 0x000000000083eb0e _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x83eb0e)
```

### PR DESCRIPTION
**Pull request by yingopq**
…on returning { i8, i128 }

Fixes https://github.com/llvm/llvm-project/issues/96432.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Can you please provide some more context on this fix? It's not really obvious to me how the call returning `{ i8, i128 }` and the following return of `fp128` are related at all.

**Comment by yingopq** [comment]
> Can you please provide some more context on this fix? It's not really obvious to me how the call returning `{ i8, i128 }` and the following return of `fp128` are related at all.

OK, I would update the commit message.

**Comment by yingopq** [comment]
error message with debug:
```
Creating constant: t2: i64 = TargetConstant<0>
Creating new node: t3: ch,glue = callseq_start t0, TargetConstant:i64<0>, TargetConstant:i64<0>
Creating new node: t5: i64,ch = CopyFromReg t3, Register:i64 $sp_64
Creating new node: t8: ch,glue = MipsISD::JmpLink t3, TargetGlobalAddress:i64<ptr @bar> 0, RegisterMask:Untyped
Creating new node: t9: ch,glue = callseq_end t8, TargetConstant:i64<0>, TargetConstant:i64<0>, t8:1
Call result #2 has unhandled type i64
UNREACHABLE executed at /swecoproj/huangying/llvm/llvm/lib/CodeGen/CallingConvLower.cpp:172!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./build/bin/llc -debug -mtriple=mips64el-linux-gnuabi64 -mcpu=mips64 -filetype=asm 1.ll
1.	Running pass 'Function Pass Manager' on module '1.ll'.
2.	Running pass 'MIPS DAG->DAG Pattern Instruction Selection' on function ['@foo](mailto:'@foo)'
```

**Comment by yingopq** [comment]
Hi @nikic, I have updated the commit message with detailed description, please help review whether my understanding is correct, thanks!

**Comment by yingopq** [comment]
Ping

**Review by nikic — CHANGES_REQUESTED** [review]
I looked into this in more detail, and as far as I understand, the problem here is a confusion between the call return type and the function return type in CanLowerReturn. This function is used both for function returns and call return values, and we analyze the wrong one. This needs to be fixed by analyzing the correct type. Adding additional registers will change the actual calling convention to no longer use sret demotion.

**Comment by nikic** [comment]
It's probably necessary to change the signature of CanLowerReturn to pass in the return type.

**Comment by yingopq** [comment]
> I looked into this in more detail, and as far as I understand, the problem here is a confusion between the call return type and the function return type in CanLowerReturn. This function is used both for function returns and call return values, and we analyze the wrong one. This needs to be fixed by analyzing the correct type. Adding additional registers will change the actual calling convention to no longer use sret demotion.

Yes, your analysis above is right, the issue reason was "This function is used both for function returns and call return values, and we analyze the wrong one. " 
I have considered to add a new parameter (eg, call return type) in function `CanLowerReturn`, but this would require to change every backend. I thought this change is bigger or would trigger other trouble, so I did not choose this method.
Now, did you support this above method?
Thanks!

**Comment by yingopq** [comment]
> It's probably necessary to change the signature of CanLowerReturn to pass in the return type.

Hi @nikic, please help review, thanks!

File: llvm/include/llvm/CodeGen/TargetLowering.h [hunk 1]
```diff
@@ -4781,7 +4781,7 @@ class TargetLowering : public TargetLoweringBase {
   virtual bool CanLowerReturn(CallingConv::ID /*CallConv*/,
                               MachineFunction &/*MF*/, bool /*isVarArg*/,
                const SmallVectorImpl<ISD::OutputArg> &/*Outs*/,
-               LLVMContext &/*Context*/) const
+               LLVMContext &/*Context*/, const Type *RetTy) const
```
Comment (arsenm) [inline llvm/include/llvm/CodeGen/TargetLowering.h:4784]: A new parameter should not be necessary. Outs should already correspond to the decomposed aggregate type derived from the original IR type

File: llvm/lib/Target/Mips/MipsCallingConv.td [hunk 2]
```diff
@@ -207,7 +207,7 @@ def RetCC_MipsN : CallingConv<[
       CCIfType<[i8, i16, i32, i64],
           CCIfInReg<CCPromoteToUpperBitsInType<i64>>>>,
 
-  // i64 are returned in registers V0_64, V1_64
+  // i64 are returned in registers V0_64, V1_64, A0_64
```
Comment (arsenm) [inline llvm/lib/Target/Mips/MipsCallingConv.td:210]: Unrelated change?

File: llvm/test/CodeGen/Mips/mips64-f128.ll [hunk 3]
```diff
@@ -2903,6 +2903,63 @@ entry:
...
+; CMP_CC_FMT-NEXT:    daddiu $2, $zero, 0
+; CMP_CC_FMT-NEXT:    daddiu $4, $zero, 0
+; CMP_CC_FMT-NEXT:    ld $gp, 32($sp) # 8-byte Folded Reload
+; CMP_CC_FMT-NEXT:    ld $ra, 40($sp) # 8-byte Folded Reload
+; CMP_CC_FMT-NEXT:    daddiu $sp, $sp, 48
+; CMP_CC_FMT-NEXT:    jrc $ra
+entry:
+  call { i8, i128 } @bar()
+  ret fp128 0xL00000000000000000000000000000000
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/Mips/mips64-f128.ll:2962]: Needs to test more situations (e.g. more aggregates with the fp128 in different positions), and this needs a comment. It's not obvious why there is the call to bar and it's not used for the return value.

Also test the caller side for fp128 returns, and tail calls

File: llvm/lib/Target/Mips/MipsCCState.h [hunk 4]
```diff
@@ -191,6 +192,16 @@ class MipsCCState : public CCState {
     return Return;
   }
 
+  bool CheckCallReturn(const SmallVectorImpl<ISD::OutputArg> &ArgsFlags,
+                   CCAssignFn Fn, const Type *RetTy) {
+    PreAnalyzeCallReturnForF128(ArgsFlags, RetTy);
+    PreAnalyzeReturnForVectorFloat(ArgsFlags);
```
Comment (arsenm) [inline llvm/lib/Target/Mips/MipsCCState.h:198]: I don't understand how this fixes it, but this looks like hacking around something that shouldn't require special casing

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 3 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/mips64-f128.ll:2962]: This is the test case described in issue, so I quote it.
OK, I would add the test including testing the caller side for fp128 returns and tail call and add a comment.

File: llvm/lib/Target/Mips/MipsCallingConv.td (hunk 2 above)
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsCallingConv.td:210]: Yes, this was the patch V1, sorry, I would delete it.

File: llvm/include/llvm/CodeGen/TargetLowering.h (hunk 1 above)
Comment (yingopq) [reply llvm/include/llvm/CodeGen/TargetLowering.h:4784]: Because in Mips backend, when process hook function CanLowerReturn, they now use MF function return type to check whether call function return type was origin from fp128. 
In fact, when they check whether MF function return type was origin from fp128, they should use MF function return type; when they check whether call function return type was origin from fp128, they should use call function return type.
So, we need a new parameter to specify the right return type.

File: llvm/lib/Target/Mips/MipsCCState.h (hunk 4 above)
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsCCState.h:198]: Add a new function to check whether call funtion return type was origin from fp128.

File: llvm/include/llvm/CodeGen/TargetLowering.h (hunk 1 above)
Comment (yingopq) [reply llvm/include/llvm/CodeGen/TargetLowering.h:4784]: We can know each element value type in `Outs`, but we can not get the call return type from `Outs`. So I think it is necessary to add a new parameter.

**Comment by yingopq** [comment]
Ping

**Review by arsenm — APPROVED** [review]
I'm still confused by this change, but it seems to be just following prior art in Mips that's been there since at least 2014. Whatever pre-processing it's doing should be consistently applied in all the calling convention contexts.

I don't understand why originalTypeIsF128 special cases a single element struct, and doesn't need to try to figure out the original element type from the EVT, or why this is how it implements that. But that's all pre-existing

File: llvm/test/CodeGen/Mips/mips64-f128.ll [hunk 5]
```diff
@@ -2903,6 +2903,225 @@ entry:
   %cond = select i1 %cmp, fp128 %c, fp128 %d
   ret fp128 %cond
 }
+
+define { i8, i128 } @bar_structure_without_fp128() {
+  ret { i8, i128 } zeroinitializer
+}
+
+define fp128 @call_structure_without_fp128() {
```
Comment (nikic) [inline llvm/test/CodeGen/Mips/mips64-f128.ll:2911]:
```suggestion
define fp128 @call_structure_without_fp128() nounwind {
```
to reduce some of the noise.

**Comment by nikic** [comment]
> I'm still confused by this change, but it seems to be just following prior art in Mips that's been there since at least 2014. Whatever pre-processing it's doing should be consistently applied in all the calling convention contexts.
> 
> I don't understand why originalTypeIsF128 special cases a single element struct, and doesn't need to try to figure out the original element type from the EVT, or why this is how it implements that. But that's all pre-existing

For MIPS the ABI for f128 and i128 is different, but the calling convention code sees this as just two i64s in both cases. Is there some cleaner way to distinguish these cases, short of making f128 a legal type?

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 5 above)
Comment (nikic) [reply llvm/test/CodeGen/Mips/mips64-f128.ll:2911]: Ideally we would also switch this test to not use `-relocation-model=pic`, but that should be pre-commited as an independent change.

File: llvm/test/CodeGen/Mips/mips64-f128.ll [hunk 6]
```diff
@@ -2903,6 +2903,225 @@ entry:
...
+; CMP_CC_FMT-NEXT:    ld $gp, 0($sp) # 8-byte Folded Reload
+; CMP_CC_FMT-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
+; CMP_CC_FMT-NEXT:    daddiu $sp, $sp, 16
+; CMP_CC_FMT-NEXT:    jrc $ra
+entry:
+  %call = tail call fp128 @bar_structure_fp128()
+  ret fp128 0xL00000000000000000000000000000000
+}
+
+define fp128 @bar_fp128() {
```
Comment (arsenm) [inline llvm/test/CodeGen/Mips/mips64-f128.ll:3019]: This function is missing checks for some reason

**Comment by arsenm** [comment]
> For MIPS the ABI for f128 and i128 is different, but the calling convention code sees this as just two i64s in both cases. Is there some cleaner way to distinguish these cases, short of making f128 a legal type?

How are the ABIs different? If it's passed as a pair of FP registers or something like that, maybe could override getRegisterTypeForCallingConv+getNumRegistersForCallingConv to split into 2 x f64

**Comment by nikic** [comment]
> > For MIPS the ABI for f128 and i128 is different, but the calling convention code sees this as just two i64s in both cases. Is there some cleaner way to distinguish these cases, short of making f128 a legal type?
> 
> How are the ABIs different? If it's passed as a pair of FP registers or something like that, maybe could override getRegisterTypeForCallingConv+getNumRegistersForCallingConv to split into 2 x f64

For the hard float ABI it's passed in a pair of FP registers, for the soft float ABI it's passed in GPR, but different ones than usual. I think your suggestion works for the hard float case, but I think it doesn't for soft-float, as we'd still end up with 2 x i64 in that case?

MIPS also has some additional code for handling libcalls though (isF128SoftLibCall), not sure how that fits into things.

**Comment by arsenm** [comment]
> For the hard float ABI it's passed in a pair of FP registers, for the soft float ABI it's passed in GPR, but different ones than usual. I think your suggestion works for the hard float case, but I think it doesn't for soft-float, as we'd still end up with 2 x i64 in that case?

If the type is forced to 2 x f64, the f64 cases would be processed differently but I think it should work the same way

File: llvm/lib/Target/Mips/MipsCCState.cpp [hunk 7]
```diff
@@ -93,6 +93,15 @@ void MipsCCState::PreAnalyzeCallResultForF128(
...
 
+void MipsCCState::PreAnalyzeCallReturnForF128(
+    const SmallVectorImpl<ISD::OutputArg> &Outs, const Type *RetTy) {
+  for (unsigned i = 0; i < Outs.size(); ++i) {
+    OriginalArgWasF128.push_back(
+        originalTypeIsF128(RetTy, nullptr));
+    OriginalArgWasFloat.push_back(
+        RetTy->isFloatingPointTy());
+  }
+}
```
[the remark this answers is not in the document]
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsCCState.cpp:104]: OK, good idea.

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 5 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/mips64-f128.ll:2911]: OK.

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 6 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/mips64-f128.ll:3019]: OK, I would add check for these bar* functions.

File: llvm/lib/Target/Mips/MipsCCState.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsCCState.cpp:106]: > Can we drop PreAnalyzeReturnForF128 now? It should be the same as PreAnalyzeCallReturnForF128 and passing MD.getFunction().getReturnType().

Applied.

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 6 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/mips64-f128.ll]: Applied.

File: llvm/test/CodeGen/Mips/mips64-f128.ll (hunk 5 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/mips64-f128.ll]: Applied `nounwind`.

**Review by arsenm — APPROVED** [review]
I still think the whole feature could be simplified later

**Comment by yingopq** [comment]
> I still think the whole feature could be simplified later

OK, thanks!

File: llvm/lib/Target/Mips/MipsCCState.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsCCState.cpp:106]: Ping

**Review by nikic — APPROVED** [review]
LGTM
