### PR TITLE
[Clang] Track constraint's SubstIndex only if it contains outer parameter packs

### LINKED ISSUE #190169: [Clang] C++26 fold expression in concept constraint expands pack incorrectly when constrained lambda is nested inside generic lambda
With `-std=c++26`, a concept with a fold expression over a parameter pack incorrectly evaluates the fold by substituting the same pack element for every iteration, instead of iterating through the pack. This causes valid code to be rejected, or could cause a silent miscompilation. The same code compiles correctly in C++23 mode (`-std=c++23`).

The bug is in the C++26-specific `FoldExpandedConstraint` normalization path (guarded by `getLangOpts().CPlusPlus26` in `SemaConcept.cpp`). In C++23 mode, fold expressions in constraints are evaluated directly as `CXXFoldExpr`, which works correctly.

## Reproducer

https://godbolt.org/z/GY9MhjcrW

```cpp
template <typename Type, typename... Choices>
concept OneOf = (... || __is_same(Type, Choices));

template <typename F, typename... Ts>
using check = decltype((F{}(Ts{}), ...));

using X = check<decltype([](auto val) {
  [](OneOf<int, char> auto) {}(val);
}), char>;
```

`clang++ -std=c++26 -c test.cpp`

**Expected:** Compiles successfully. `OneOf<char, int, char>` should expand to `__is_same(char, int) || __is_same(char, char)`, which is true.

## Diagnostic output

```
test.cpp:8:6: note: because 'OneOf<char, int, char>' evaluated to false
    8 |   [](OneOf<int, char> auto) {}(val);
      |      ^
test.cpp:2:25: note: because '__is_same(char, int)' evaluated to false
    2 | concept OneOf = (... || __is_same(Type, Choices));
      |                         ^
test.cpp:2:25: note: and '__is_same(char, int)' evaluated to false
```

Note both fold iterations report `__is_same(char, int)`. The second should be `__is_same(char, char)`.

## Essential conditions

All four are required to trigger the bug:

1. **Concept with fold expression over a pack** — `(... || __is_same(Type, Choices))`
2. **Used as constraint on a lambda `auto` parameter** — `OneOf<int, char> auto`
3. **That lambda nested inside a generic (`auto`) outer lambda** — `[](auto val) { ... }`
4. **Outer lambda instantiated through a pack expansion context** — the `(F{}(Ts{}), ...)` fold in the `check` alias template

Removing any one of these makes the bug disappear.

## Affected versions

- **Fails:** clang 22.1.2, clang 22.1.0 — with `-std=c++26` or `-std=c++2c`
- **Passes:** Same versions with `-std=c++23` or `-std=c++2b`, clang 21.1.0
- **Passes:** gcc 14.2.0 with `-std=c++2c`

## Root cause

In C++26 mode, `SemaConcept.cpp` normalizes fold expressions in constraints into `FoldExpandedConstraint` nodes (line ~2398, guarded by `S.getLangOpts().CPlusPlus26`). The `FoldExpandedConstraint::EvaluateSlow` method iterates the pack by setting `ArgPackSubstIndex` to the loop variable `I`. However, when the constraint is evaluated in the context of an outer pack expansion (from the `check` alias template's fold), the outer `ArgPackSubstIndex` appears to interfere with the inner fold's pack element selection, causing all iterations to substitute the same element.

In C++23 mode, this normalization is skipped and the fold is evaluated directly as a `CXXFoldExpr` via `calculateConstraintSatisfaction`, which correctly iterates the pack.

### PR DESCRIPTION
**Pull request by zyn0217**
I believe that is the intent of SubstIndex in AssociatedConstraint.
So this enforces the checking explicitly, in case nested SubstIndexes
confuses our poor constraint evaluator.

I reverted the previous fix 257cc5ad89840cdfba4affcc8fe62cf9d02d9017 because that was wrong.
As a drive-by fix, this also removes an strange assertion and an unnecessary
SubstIndex setup in nested requirement transform.

No release note because this is a regression fix.

Fixes https://github.com/llvm/llvm-project/issues/188505
Fixes https://github.com/llvm/llvm-project/issues/190169

### CODE REVIEW

File: clang/lib/Sema/SemaConcept.cpp [hunk 1]
```diff
@@ -493,12 +493,6 @@ class ConstraintSatisfactionChecker {
       CachedTemplateArgs;
 
 private:
-  template <class Constraint>
-  UnsignedOrNone getOuterPackIndex(const Constraint &C) const {
-    return C.getPackSubstitutionIndex() ? C.getPackSubstitutionIndex()
-                                        : PackSubstitutionIndex;
-  }
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaConcept.cpp:500]: We do that a couple of times so I think we should keep the function

**Review by cor3ntin — APPROVED** [review]
LGTM modulo nit
