### PR TITLE
[llvm][EmbedBitcodePass] Prevent modifying the module with ThinLTO

### LINKED ISSUE #139440: -fwhole-program-vtables breaks in combination with -ffat-lto-objects
the following

```cpp
#include <stdexcept>

struct Foo : std::runtime_error {
    Foo() : runtime_error("") {}
};

Foo foo{};
```

when built into an object file with
`clang++ -flto=thin -fwhole-program-vtables -ffat-lto-objects -fPIC -fvisibility=hidden -c foo.cpp -o foo.o`
and then linked into a shared library with
`clang++ -flto=thin -shared foo.o -o foo.so`
will fail with
`ld.lld: error: undefined hidden symbol: vtable for Foo`

Removing either the `-fwhole-program-vtables` or `-ffat-lto-objects` when compiling the object file works fine.

Note that this isn't related to this specific underlying type, I only discovered it with `std::runtime_error` first. Reproduces on libstdc++ and libc++ (when linking dynamically)

### PR DESCRIPTION
**Pull request by ilovepi**
Since ThinLTOBitcodeWriterPass handles many things for CFI and WPD, like
updating vtable linkage, we need to prevent those changes from
persisting in the non-LTO object code we will compile under FatLTO.

The only non-invasive way to do that is to clone the module when
serializing the module in ThinLTOBitcodeWriterPass. We may be able to
avoid cloning in the future with additional infrastructure to restore
the IR to its original state.

Fixes #139440

### CODE REVIEW

**Comment by ilovepi** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/139999?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#139999** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/139999?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/139999?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#139998** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/139998?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nikic — COMMENTED** [review]
Didn't we switch away from cloning because it breaks blockaddress somehow?

**Comment by ilovepi** [comment]
I thought we switched away from cloning to avoid redundancy. I'll take a look through previous patches though.

**Comment by ilovepi** [comment]
Well, with my patch the program in initial bug report from #70703 is passing w/ this patch, and the rest of the test suite seems OK ... maybe its fine to clone now?

**Comment by nikic** [comment]
@ilovepi Does it also work on the release branch? I'd mainly see the clone module approach as something easily backportable for the release branch, but I assume for main we'll want a different solution?

**Comment by ilovepi** [comment]
I'm testing the release branch now. I believe that the issue w/ cloning was solved before we cut the release, and the patch above just added regression tests, so I expect it to work.

I'm all ears if you can think of a better way to handle this on main. The main problem I saw as I looked was that there isn't a good way to figure out what ThinLTOBitcodeWriter changed in the module (e.g. did it remove a comdat, change a linkage, etc.). We want those things to happen for the ThinLTO bitcode, but its awfully problematic for the rest of the compile. I guess we could add some metadata to the instructions we changed and then clean up after, but that also seems to not be great.

**Comment by ilovepi** [comment]
The test suite seems just as happy with the FatLTO fix as it does with ThinLTO on the release branch. I see the same three tests failing, and the reported test case passes as well.

For completeness these are the failing tests. This was consistent w/ FatLTO + ThinLTO, and ThinLTO alone on built from releases/20.x with the call to CloneModule().
 
```
 test-suite :: MultiSource/UnitTests/Float/rounding/rounding.test
  test-suite :: SingleSource/Regression/C/gcc-c-torture/execute/GCC-C-execute-pr17377.test
  test-suite :: SingleSource/UnitTests/Float/classify.test
```

**Comment by ilovepi** [comment]
@nikic I spent some time over the weekend looking at this, I think if we want to avoid cloning the module, we'd need to record enough metadata to recover the old state. For the Vtable I think that's not too much data, but IDK about the rest. That said, that whole approach seems awfully invasive to the pass and is likely to be both buggy and brittle.  I just don't see a good way for us to roll back those changes to the VTable otherwise...

Should we just land this for now, and try to come up with something better/different as a follow up?

**Review by pcc — APPROVED** [review]
Cloning makes sense to me at least to begin with. Since fat LTO is a seldomly used feature, it may be better overall to be a bit less efficient in order to reduce the overall maintenance burden.

File: llvm/lib/Transforms/IPO/EmbedBitcodePass.cpp [hunk 1]
```diff
@@ -33,8 +34,11 @@ PreservedAnalyses EmbedBitcodePass::run(Module &M, ModuleAnalysisManager &AM) {
 
   std::string Data;
   raw_string_ostream OS(Data);
+  // Clone the module with with Thin LTO, since ThinLTOBitcodeWriterPass changes
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/EmbedBitcodePass.cpp:37]:
```suggestion
  // Clone the module with Thin LTO, since ThinLTOBitcodeWriterPass changes
```

**Review by nikic — APPROVED** [review]
Okay, let's go with this for now.

Compile-time impact of cloning the module is about 0.2% when building clang with fat LTO: https://llvm-compile-time-tracker.com/compare.php?from=11a01e851a06188ae946ace1140f866d7a667221&to=46e037d763e7997a83ce78c9a602248fd67f0d44&stat=instructions:u

**Comment by ilovepi** [comment]
### Merge activity

* **May 29, 5:24 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/139999).

**Comment by tstellar** [comment]
@ilovepi I've bisected a crash down to this commit.  Attached is a reproducer: 
[proactor_test-f405d8.cpp.txt](https://github.com/user-attachments/files/20847114/proactor_test-f405d8.cpp.txt)
[proactor_test-f405d8.sh.txt](https://github.com/user-attachments/files/20847115/proactor_test-f405d8.sh.txt)

**Comment by ilovepi** [comment]
> @ilovepi I've bisected a crash down to this commit. Attached is a reproducer: [proactor_test-f405d8.cpp.txt](https://github.com/user-attachments/files/20847114/proactor_test-f405d8.cpp.txt) [proactor_test-f405d8.sh.txt](https://github.com/user-attachments/files/20847115/proactor_test-f405d8.sh.txt)

Sorry, looks like I missed the notification. I'm a bit puzzled as to how cloning the module could break things if the block address issue is fixed... I'll start looking. Should we revert?  the  link error  we were fixing seems preferable to a crash...

**Comment by PiJoules** [comment]
Reverting since we also ran into another crash bisected to this

```
; Function Attrs: optsize
declare noundef i32 @_ZN8perfetto4base9CloseFileEi(i32 noundef %0) local_unnamed_addr #2

Unknown constant!
UNREACHABLE executed at llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2998!
```

[client_impl-ef56d7.sh.txt](https://github.com/user-attachments/files/20934972/client_impl-ef56d7.sh.txt)
[client_impl-ef56d7.cpp.txt](https://github.com/user-attachments/files/20934973/client_impl-ef56d7.cpp.txt)

**Comment by nikic** [comment]
Both of those test cases reference a function inside DITemplateValueParameter metadata. Unfortunately, I'm not able to reproduce this issue when running through `opt` instead of `clang`.

**Comment by nikic** [comment]
Added support for running the fat LTO pipeline in opt in https://github.com/llvm/llvm-project/pull/146048, though this does not help reproducing this issue.

Here is a reduction:
```cpp
// RUN: clang -g -flto=thin -ffat-lto-objects %s
template <void CloseFunction()>
struct ScopedResource {
  ~ScopedResource() { CloseFunction(); }
};
 
void CloseFile();
 
struct Client {
  void CreateInstance(ScopedResource<CloseFile>);
  Client();
};
 
struct ClientImpl {
  ClientImpl(ScopedResource<CloseFile>, int *);
};
 
int CreateInstance_task_runner;
void Client::CreateInstance(ScopedResource<CloseFile> conn_args) {
  ClientImpl(conn_args, &CreateInstance_task_runner);
}
```

**Comment by nikic** [comment]
As one would expect, what ultimately causes the crash is a failure to remap a metadata reference of the declaration of the one from the new module. But I'm having a hard time understanding what exactly the root cause for that is. What I see is that we do correctly remap one of the transitive references from the DISubprogram, but not the one in the declaration DISubprogram. The difference between running clang and opt is that in the latter case the type referenced by DISubprogram and its declaration DISubprogram is the same, while in the former case it is different.

**Comment by ilovepi** [comment]
@nikic for whatever reason I could't get your reproducer to work. It took about 12 days, but I got this out of cvise (would love to know how you got something so small so fast!).

```c++
//RUN: clang -cc1 -debug-info-kind=constructor -flto=thin -ffat-lto-objects -emit-llvm bad.reduced.cpp
void pn_condition_free(int *);

template <class T, void(T *)> struct auto_free {};
struct handler {
  auto_free<int, pn_condition_free> last_condition;
};

struct proactor {
  proactor();
  void connect(handler *) {}
};

void test() {
  handler chsh;
  proactor client;
  client.connect(0);
}
```

This still hits the unreachable for me, though I'm still very confused about when things go off the rails once the module is being cloned.
