### PR TITLE
[clang][ast]: Add DynamicAllocLValue and TypeInfoLValue support to APValue::dump().

### LINKED ISSUE #134996: Add `DynamicAllocLValue` and `TypeInfoLValue` support to `APValue::dump()`
`APValue` recently gained support for `dump()`ing lvalues, however, the code to handle them is missing support for lvalue bases of type `TypeInfoLValue` and `DynamicAllocLValue`:
https://github.com/llvm/llvm-project/blob/a29be9f28e8e0d4ca7a8a3cfdffe616ac780c754/clang/lib/AST/TextNodeDumper.cpp#L732-L761

Before the `else {` branch that unconditionally assumes the base to be a `const ValueDecl*`, we need to check whether the base is a dynamic alloc value or a typeid value: https://github.com/llvm/llvm-project/blob/a29be9f28e8e0d4ca7a8a3cfdffe616ac780c754/clang/lib/AST/ExprConstant.cpp#L2124-L2125

... and print something appropriate, or at least not crash.

### PR DESCRIPTION
**Pull request by YLChenZ**
Closes #134996.
The crash about `TypeInfoLValue` is https://godbolt.org/z/73WY31s55. 
After the patch:
```cpp
//test.cpp
#include <typeinfo>
constexpr const std::type_info* val = &typeid(int);
```
```
lambda@ubuntu22:~/test$ clang++ -std=c++20 -Xclang -ast-dump -fsyntax-only test.cpp
LValue Base=TypeInfoLValue typeid(int), Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
```

```cpp
//DAtest.cpp
constexpr int *m = new int(42);
```
```
lambda@ubuntu22:~/test$ clang++ -std=c++20 -Xclang -ast-dump -fsyntax-only DAtest.cpp
LValue Base=DynamicAllocLValue 'int', Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
```

### CODE REVIEW

File: clang/lib/AST/TextNodeDumper.cpp [hunk 1]
```diff
@@ -738,6 +738,10 @@ void TextNodeDumper::Visit(const APValue &Value, QualType Ty) {
     else if (const auto *BE = B.dyn_cast<const Expr *>()) {
       OS << BE->getStmtClassName() << ' ';
       dumpPointer(BE);
+    } else if (B.is<TypeInfoLValue>()) {
+      OS << "TypeInfoLValue";
+    } else if (B.is<DynamicAllocLValue>()) {
+      OS << "DynamicAllocLValue";
```
Comment (tbaederr) [inline clang/lib/AST/TextNodeDumper.cpp:744]: Would be good to print more information about them.

**Comment by tbaederr** [comment]
I don't think we can test `DynamicAllocLValue` like this, since we can't save it in the `APValue` for an initialized global. You'll have to add a call to `dump()` e.g. like:
```diff
diff --git i/clang/lib/AST/ExprConstant.cpp w/clang/lib/AST/ExprConstant.cpp
index d1cc722fb794..df52ff82ea2a 100644
--- i/clang/lib/AST/ExprConstant.cpp
+++ w/clang/lib/AST/ExprConstant.cpp
@@ -17087,6 +17087,8 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
         return false;
     }

+    Value.dump();
+
     // At this point, any lifetime-extended temporaries are completely
     // initialized.
     Info.performLifetimeExtension();
```
to reproduce it.

**Comment by YLChenZ** [comment]
> I don't think we can test `DynamicAllocLValue` like this, since we can't save it in the `APValue` for an initialized global. You'll have to add a call to `dump()` e.g. like:
> 
> ```diff
> diff --git i/clang/lib/AST/ExprConstant.cpp w/clang/lib/AST/ExprConstant.cpp
> index d1cc722fb794..df52ff82ea2a 100644
> --- i/clang/lib/AST/ExprConstant.cpp
> +++ w/clang/lib/AST/ExprConstant.cpp
> @@ -17087,6 +17087,8 @@ bool Expr::EvaluateAsInitializer(APValue &Value, const ASTContext &Ctx,
>          return false;
>      }
> 
> +    Value.dump();
> +
>      // At this point, any lifetime-extended temporaries are completely
>      // initialized.
>      Info.performLifetimeExtension();
> ```
> 
> then you can compile
> 
> ```c++
> constexpr int *m = new int(12);
> ```
> 
> to reproduce it.

Okay, I got it. Already reproduced the crash.
```
lambda@ubuntu22:~/test$ clang++ -std=c++20 -Xclang -ast-dump -fsyntax-only DAtest.cpp
LValue Base=DynamicAllocLValue, Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
DAtest.cpp:1:16: error: constexpr variable 'm' must be initialized by a constant expression
    1 | constexpr int *m = new int(42);
      |                ^   ~~~~~~~~~~~
DAtest.cpp:1:16: note: pointer to heap-allocated object is not a constant expression
DAtest.cpp:1:20: note: heap allocation performed here
    1 | constexpr int *m = new int(42);
      |                    ^
LValue Base=DynamicAllocLValue, Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
```

**Comment by YLChenZ** [comment]
> Would be good to print more information about them.

@tbaederr  It seems to only dump their type, like this:
```cpp
case APValue::LValue: {
    (void)Context;
    OS << "LValue Base=";
    APValue::LValueBase B = Value.getLValueBase();
    ...
    } else if (B.is<TypeInfoLValue>()) {
      OS << "TypeInfoLValue";
      const auto BTI = B.get<TypeInfoLValue>();
      BTI.print(OS, PrintPolicy);
    } else if (B.is<DynamicAllocLValue>()) {
      OS << "DynamicAllocLValue";
      auto BDA = B.getDynamicAllocType();
      dumpType(BDA);
    }
```

```cpp
//test.cpp
#include <typeinfo>
constexpr const std::type_info* val = &typeid(int);
```
```
lambda@ubuntu22:~/test$ clang++ -std=c++20 -Xclang -ast-dump -fsyntax-only test.cpp
LValue Base=TypeInfoLValue typeid(int), Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
```

```cpp
//DAtest.cpp
constexpr int *m = new int(42);
```
```
lambda@ubuntu22:~/test$ clang++ -std=c++20 -Xclang -ast-dump -fsyntax-only DAtest.cpp
LValue Base=DynamicAllocLValue 'int', Null=0, Offset=0, HasPath=1, PathLength=0, Path=()
```

File: clang/lib/AST/TextNodeDumper.cpp [hunk 2]
```diff
@@ -738,6 +738,15 @@ void TextNodeDumper::Visit(const APValue &Value, QualType Ty) {
     else if (const auto *BE = B.dyn_cast<const Expr *>()) {
       OS << BE->getStmtClassName() << ' ';
       dumpPointer(BE);
+    } else if (B.is<TypeInfoLValue>()) {
```
Comment (tbaederr) [inline clang/lib/AST/TextNodeDumper.cpp:741]:
```suggestion
    } else if (const auto BTI=  B.dyn_casty<TypeInfoLValue>()) {
```

Comment (YLChenZ) [reply clang/lib/AST/TextNodeDumper.cpp]: Done.

**Review by tbaederr — APPROVED** [review]

**Comment by tbaederr** [comment]
Can you merge this or do you need to someone else to do it for you?

**Comment by YLChenZ** [comment]
@tbaederr I don't have access to merge pr. It should require some help to merge.
