### PR TITLE
[Tooling] Fix misleading progress report when files have multiple compile commands

### LINKED ISSUE #169168: clang-tidy misreports progress when duplicating files due to multiple targets
Here is the log of `clang-tidy` progress when I run it on my repo, I edited paths to be relative and space-aligned first 9 items for readability.

```txt
[ 1/18] Processing file include/glug/detail/backport/type_traits.hpp.
[ 2/18] Processing file include/glug/filesystem.hpp.
[ 3/18] Processing file include/glug/filter.hpp.
[ 4/18] Processing file include/glug/glob.hpp.
[ 5/18] Processing file include/glug/regex.hpp.
[ 6/18] Processing file src/filesystem.cpp.
[ 7/18] Processing file src/filesystem.cpp.
[ 8/18] Processing file src/filter.cpp.
[ 9/18] Processing file src/filter.cpp.
[10/18] Processing file src/glob.cpp.
[11/18] Processing file src/glob.cpp.
[12/18] Processing file src/main.cpp.
[13/18] Processing file src/regex.cpp.
[14/18] Processing file src/regex.cpp.
[15/18] Processing file test/unit/main.cpp.
[16/18] Processing file test/unit/parametrized.hpp.
[17/18] Processing file test/unit/test_filesystem_explorer.cpp.
[18/18] Processing file test/unit/test_glob_decompose.cpp.
[19/18] Processing file test/unit/test_glob_filter.cpp.
[20/18] Processing file test/unit/test_glob_to_regex.cpp.
[21/18] Processing file test/unit/tree.cpp.
[22/18] Processing file test/unit/tree.hpp.
```

Note that all files in `src/` except for `main.cpp` are analyzed twice. This is completely expected, as they appear twice in the `compile_commands.json`: once for the main executable, once for UT. What I would like to see fixed though is the `[22/18]` part, as it is confusing and misleading, it should instead read as `[*/22]`, since that is the total number to analyse.

Environment:
* Invoked as: `clang-tidy $(git ls-files **.hpp **.cpp)`
* OS: `Linux 6.16.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 Oct 2025 19:26:36
 +0000 x86_64 GNU/Linux`
* LLVM: `20.1.8`

### PR DESCRIPTION
**Pull request by zeyi2**
This patch fixes an issue in progress reporting where the processed item counter could exceed the total item count, leading to confusing outputs like [22/18].

Closes [#169168](https://github.com/llvm/llvm-project/issues/169168)

### CODE REVIEW

**Review by vbvictor — COMMENTED** [review]
Can we make any tests for this new format?
If the user can see it - we should be able to cover it, could be test in clang-tidy `infrastructure/` (test different scenarios).

**Comment by zeyi2** [comment]
The failed testcase seems unrelated to this PR, I'll try rebase onto `main` again later.

File: clang/lib/Tooling/Tooling.cpp [hunk 1]
```diff
@@ -617,13 +617,21 @@ int ClangTool::run(ToolAction *Action) {
...
+      if (NumOfTotalFiles > 1 || CompileCommandsForFile.size() > 1) {
+        llvm::errs() << "[" + std::to_string(CurrentFileIndex) + "/" +
+                            std::to_string(NumOfTotalFiles) + "]";
+        if (CompileCommandsForFile.size() > 1) {
+          llvm::errs() << " (" + std::to_string(CurrentCommandIndexForFile) +
+                              "/" +
+                              std::to_string(CompileCommandsForFile.size()) +
+                              ")";
+        }
+        llvm::errs() << " Processing file " + File << ".\n";
```
Comment (vbvictor) [inline clang/lib/Tooling/Tooling.cpp]: Does `llvm::errs()` support stream-like api?
If so can we instead write `llvm::errs() << "[" << ...`

**Comment by zeyi2** [comment]
Hi, Aaron.

Could you please review this patch? It fixes a misleading progress report issue in Tooling (e.g. `[22/18]`) when files have multiple compile commands.

I have addressed previous feedback from vbvictor and zwuis, could you do some furthur reviews?

Thanks for your time.

**Review by AaronBallman — COMMENTED** [review]
The changes seem pretty reasonable but there's a fair amount of unrelated formatting changes. It'd be easier on reviewers to back those unrelated changes out so we can more easily see just what's been materially modified.

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you!
