### PR TITLE
[clang-tidy] Invalid Fix-It generated for implicit-widening-multiplication-result

### LINKED ISSUE #56728: [clang-tidy] wrong fixup for bugprone-implicit-widening-of-multiplication-result
```console
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 14.0.6
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver2
```

clang tidy tries to fix the following:

```cpp
TEST(test_mem, std_list_in_vmem) {
    monotonic_virtual_memory_resource vmem(1024 * 1024, 1024 * 1024 * 1024);
    {/*<code>*/}
```

```cpp
TEST(test_mem, std_list_in_vmem) {
    monotonic_virtual_memory_resource vmem(1024 * 1024, 1024 * 1024 * 1024);
    {/*<code>*/}
```

```cpp
// TODO this does not test
TEST(test_mem, std_list_in_vmem) {
    monotonic_virtual_memory_resource vmem(static_cast<size_t>(1024 * )1024, 1024 * 1024 * 1024);
    {
```

This results in code which is not compilable anymore.

### LINKED ISSUE #63070: incorrect code action for bugprone-implicit-widening-of-multiplication-result
I[13:16:13.005] clangd version 16.0.4
I[13:16:13.005] Features: windows

// before fix
```cpp
size_t abc = 128*1024;
```

// fixed
```cpp
size_t abc = static_cast<size_t>(128*)1024;
```

### PR DESCRIPTION
**Pull request by felix642**
The check currently emits warnings for the following code:
    `uint64_t fn() { return 1024 * 1024; }`

But the code generated after applying the notes will look like this:
    `uint64_t fn() { return static_cast<uint64_t>(1024 * )1024; }`
```
[<source>:5:12: warning: performing an implicit widening conversion to type 'uint64_t' (aka 'unsigned long') of a multiplication performed in type 'int' [bugprone-implicit-widening-of-multiplication-result]](javascript:;)
    5 |     return 1024 * 1024;
      |            ^
[<source>:5:12: note: make conversion explicit to silence this warning](javascript:;)
    1 | #include <cstdint>
    2 | 
    3 | uint64_t fn()
    4 | {
    5 |     return 1024 * 1024;
      |            ^~~~~~~~~~~
      |            static_cast<uint64_t>( )
[<source>:5:12: note: perform multiplication in a wider type](javascript:;)
    5 |     return 1024 * 1024;
      |            ^~~~
      |            static_cast<long>()
1 warning generated.
```

This is because when generating the notes the check will use the beginLoc() and EndLoc() of the subexpr of the implicit cast.
But in some cases the AST Node might not have a beginLoc and EndLoc. This seems to be true when the Node is composed of only 1 token (for example an integer literal). Calling the getEndLoc() on this type of node will simply return the known location which is, in this case, the beginLoc.

Fixes #63070 #56728

I was not able to add tests for this commit and this is because the check currently emits two notes for every detection. 
The first suggestion is to silence the warning by casting the whole operation.
The second suggestion is there to fix the issue (And I think the suggested code is invalid, but I've opened another issue for that: https://github.com/llvm/llvm-project/issues/76311).

Since both suggestions are overlapping clang-tidy refuses to apply them and I was not able to add new tests.

The first suggestion seems useless since we should not suggest a fix-it to silence an issue (the message seems sufficient to me). 
But this requires more discussion and the change is not trivial so I've left it how it is for now.

### CODE REVIEW

**Comment by felix642** [comment]
A patch that proposed a similar fix was previously submitted for this issue but never landed : https://reviews.llvm.org/D141058

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/implicit-widening-of-multiplication-result-pointer-offset.cpp [hunk 1]
```diff
@@ -18,7 +18,7 @@ char *t0(char *base, int a, int b) {
   // CHECK-NOTES-CXX:                  static_cast<ptrdiff_t>( )
   // CHECK-NOTES-ALL: :[[@LINE-5]]:17: note: perform multiplication in a wider type
   // CHECK-NOTES-C:                    (ptrdiff_t)
-  // CHECK-NOTES-CXX:                  static_cast<ptrdiff_t>()
+  // CHECK-NOTES-CXX:                  static_cast<ptrdiff_t>( )
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/implicit-widening-of-multiplication-result-pointer-offset.cpp:21]: NOTE: This is legacy issue and shoudn't be fixed under this PR, but all those checks with CHECK-NOTES looks invalid. We should use CHECK-MESSAGES and CHECK-FIXES, in that case we could verify that fixed line after applying fix looks correctly instead of checking clang-tidy output.

**Review by PiotrZSL — APPROVED** [review]
LGTM.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/implicit-widening-of-multiplication-result-pointer-offset.cpp (hunk 1 above)
Comment (felix642) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/implicit-widening-of-multiplication-result-pointer-offset.cpp:21]: I agree with you, like I've mentionned :

> Since both suggestions are overlapping clang-tidy refuses to apply them [...]

This is probably the reason why they are currently not using `CHECK-FIXES`. It would be a good idea to update the tests to use `CHECK-FIXES` but we would probably need to remove one of the FIX-IT for it to work.

**Comment by felix642** [comment]
@PiotrZSL thank you for the review. 
I would greatly appreciate if you could merge this PR for me since I do not have the rights to do it.
