### PR TITLE
[LifetimeSafety] Use per-container invalidation rules to fix false positives

### LINKED ISSUE #181912: [LifetimeSafety] False-positive warning after inserting into a std::set
After #179093, I'm seeing a false-positive when accessing an iterator after inserting into a `std::set` with `-Wlifetime-safety`. Here's a minimal reproducer:
```c++
#include <set>
#include <cassert>

void func()
{
    std::set<int> foo;
    foo.insert(0);
    auto first = foo.begin();
    foo.insert(2);
    assert(*first == 0);
}
```

Results in:
```bash
testset.cpp:8:18: warning: object whose reference is captured is later invalidated [-Wlifetime-safety-invalidation]
    8 |     auto first = foo.begin();
      |                  ^~~
testset.cpp:9:9: note: invalidated here
    9 |     foo.insert(2);
      |     ~~~~^~~~~~~~~
testset.cpp:10:13: note: later used here
   10 |     assert(*first == 0);
```

Inserting into a `std::set` should not invalidate any iterators or references, so I believe this warning is incorrect.

### PR DESCRIPTION
**Pull request by aeft**
- Refactor `isContainerInvalidationMethod()` to per-container invalidation sets, based on https://en.cppreference.com/w/cpp/container#Iterator_invalidation.
- Follow reference invalidation rules instead of iterator invalidation rules. Specifically:
   - Methods that only invalidate iterators but not references are excluded (e.g. `deque::push_back`, `unordered_map::emplace`).
   - Methods that only invalidate references to the removed element itself are excluded (e.g. `vector::pop_back`, `deque::pop_*`, and `erase`/`extract` on all node-based containers).
- Fix false positives for `insert`/`emplace` etc on ordered associative containers (`set`, `map`, `multiset`, `multimap`), which never invalidate iterators per the standard.
- Add previously missing methods: `emplace_hint`, `insert_or_assign`, `push_range`, `replace_with_range`, `resize_and_overwrite`, `merge`.
- `operator[]` now only invalidates for `flat_map`. `map::operator[]` and `unordered_map::operator[]` may insert but don't invalidate references.

Fixes #181912

### CODE REVIEW

File: clang/lib/Analysis/LifetimeSafety/LifetimeAnnotations.cpp [hunk 1]
```diff
@@ -272,28 +272,109 @@ bool isUniquePtrRelease(const CXXMethodDecl &MD) {
...
 }
 
+/// Returns the set of methods that invalidate iterators for the given
+/// container, or nullptr if the container is not recognized.
+///
+/// Iterator invalidation rules per the C++ standard:
+/// https://en.cppreference.com/w/cpp/container#Iterator_invalidation
+static const llvm::StringSet<> *
+getInvalidatingMethods(StringRef ContainerName) {
+  static const llvm::StringSet<> Vector = {// Insertion
```
Comment (usx95) [inline clang/lib/Analysis/LifetimeSafety/LifetimeAnnotations.cpp]: We currently do not have a way to differentiate between iterator invalidation and reference invalidation.

In cases where iterators are invalidated but not references, this could be overly strict. This is particularly problematic for `UnorderedAssociative`containers. I am inclined towards keeping this less restrictive until we start to differentiate between iterators and interior references

@Xazax-hun thoughts ?

File: clang/lib/Analysis/LifetimeSafety/LifetimeAnnotations.cpp [hunk 2]
```diff
@@ -272,28 +272,109 @@ bool isUniquePtrRelease(const CXXMethodDecl &MD) {
...
-      "set", "multiset", "map", "multimap",
-      // Unordered Associative
-      "unordered_set", "unordered_multiset", "unordered_map",
-      "unordered_multimap",
-      // C++23 Flat
-      "flat_map", "flat_set", "flat_multimap", "flat_multiset"};
-
-  if (!Containers.contains(ContainerName))
+  const llvm::StringSet<> *InvalidatingMethods =
+      getInvalidatingMethods(ContainerName);
```
[the remark this answers is not in the document]
Comment (aeft) [reply clang/lib/Analysis/LifetimeSafety/LifetimeAnnotations.cpp]: I see what you mean about the abstraction. The `StringSet` is only used within `isContainerInvalidationMethod` itself. The reason it's a two-step (get set, then query) is that we need a "known container" check as an early exit before the operator handling logic (L380-397), which doesn't use the `StringSet`.

File: clang/test/Sema/warn-lifetime-safety-invalidations.cpp [hunk 3]
```diff
@@ -374,3 +374,85 @@ void ChangingRegionOwnedByContainerIsOk() {
...
+}
+
+void MapClearInvalidates() {
+  std::map<int, int> m;
+  auto it = m.begin();  // expected-warning {{object whose reference is captured is later invalidated}}
+  m.clear(); // expected-note {{invalidated here}}
+  *it; // expected-note {{later used here}}
+}
+
+void MapSubscriptDoesNotInvalidate() {
```
Comment (usx95) [inline clang/test/Sema/warn-lifetime-safety-invalidations.cpp]: Can you also add a case where you use this in a function call.

```cpp
#include <map>
#include <flat_map>

void PrintMax(const int& a, const int& b);

void foo(std::map<int, int> mp, int a, int b) {
    PrintMax(mp[a], mp[b]);
}

void bar(std::flat_map<int, int> mp, int a, int b) {
    PrintMax(mp[a], mp[b]);
}

```

https://godbolt.org/z/5xTec85Wz

Currently both are errors. Expected: first is ok, second is not.

**Review by usx95 — APPROVED** [review]
The structure looks great to me. LGTM. (some ideas for tests inline)

Let's wait for approval from @Xazax-hun

**Review by Xazax-hun — APPROVED** [review]
Let's remove some of the `cppreference` links as it is not the single source of truth when it comes to C++, we usually try to reference the standard directly when we need references. Otherwise, it looks good to me.
