### PR TITLE
[Clang] Consider default template arguments when synthesizing CTAD guides

### LINKED ISSUE #133132: [Clang] CTAD for alias template failed as a default type argument is not used for deduction
```c++
template <class T>
struct A {};

template <class T>
using Foo = A<A<T>>;

template <class T = int>
using Bar = Foo<T>;

Bar a{};
```

Output:
```console
```

### PR DESCRIPTION
**Pull request by zyn0217**
We copy arguments from different template parameter lists depending on the deducibility of the template parameters. In particular, we may lose the default template argument from the original alias declaration, and this patch helps preserve that.

Fixes https://github.com/llvm/llvm-project/issues/133132

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
This seems reasonable/right to me, but please give @mizvekov a chance to double-check, he's more familiar with deduction than I am.

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp [hunk 1]
```diff
@@ -1061,15 +1061,36 @@ BuildDeductionGuideForTypeAlias(Sema &SemaRef,
...
+  // In terms of Bar, we want U to appear in the synthesized deduction guide,
+  // but U would remain undeduced if we deduce against A<T> instead of T.
+  // Also note that since the deduced results are only used for synthesizing
+  // template parameters, they should not introduce unintended behavior in
+  // theory.
+  ArrayRef<TemplateArgument> Ps = FReturnType->template_arguments();
+  if (auto *DG = dyn_cast<CXXDeductionGuideDecl>(F->getTemplatedDecl());
+      DG && DG->getSourceDeductionGuideKind() ==
+                CXXDeductionGuideDecl::SourceDeductionGuideKind::Alias)
+    Ps = F->getInjectedTemplateArgs(Context);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: From what I gather about the context of this function, F is always a deduction guide, so the dyn_cast is superfluous.

Also, wouldn't we always be wanting to deduce against the injected template parameters of F anyway, so you could instead just change `FReturnType->template_arguments()` below to `F->getInjectedTemplateArgs(Context)`? And you could then nuke the whole part above about obtaining `FReturnType`, making this fix a simplification overall?

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: > Also, wouldn't we always be wanting to deduce against the injected template parameters of F anyway, so you could instead just change FReturnType->template_arguments() below to F->getInjectedTemplateArgs(Context)?

Ugh actually I ran into an assertion failure even without your suggestion

```cpp
template<typename T, typename...Us>
struct A{
  template<typename V> requires __is_same(V, int)
  A(V);
};

template<typename...TS>
using AA = A<int, TS...>;

template<typename...TS>
using BB = AA<TS...>;

BB a{0};
```

The (synthesized) template parameters are not guaranteed to be syntactially correct, so we ended up having
```cpp
template <typename... Us, typename V>
AA(V) -> A<int, Us...>;
```
for AA, and using `<Us..., V>` instead of `<int, Us...>` would violate the assumption in `hasTemplateArgumentForDeduction`: `Pack not at the end of argument list?`

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: This needs some thought, unless we are performing the rewrite incorrectly, this looks like it should be rejected.

The standard rules specifies this rewrite, and from then on this falls into the normal function template rules.

If the rewrite produces an invalid function template, then the program is ill-formed, unless there was some exception for this, which I don't think there is.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: I finally figured out another way to address it: we don't need to bother looking at the injected template arguments.

Comment (mizvekov) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: I still think the invalid rewrite problem is worth exploring, this could be a core issue.
Maybe leave a FIXME then?

**Review by mizvekov — APPROVED** [review]
LGTM, but it would be good leaving a FIXME.

File: clang/lib/Sema/SemaTemplateDeductionGuide.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaTemplateDeductionGuide.cpp]: Done, I added a fixme to the test

**Review by cor3ntin — APPROVED** [review]
