### PR TITLE
[Clang] Fix a crash when diagnosing a non relocatable with no copy ctr

### LINKED ISSUE #143325: relocation diagnostics asserts in response to code that is broken for unrelated reasons #awesome
I made an error in one of my test cases and got a crash due to a null value. After much confusion I realized the problem is actually that I had redefined the same struct multiple times, and that's what caused the unexpected state.

The test case:

```cpp
struct Foo  {
  Foo(const Foo&);
  ~Foo();
};

struct Foo {
  Foo();
  int;
};

struct Wrapper {
  union {
    Foo p;
  } u;
};
static_assert(__builtin_is_cpp_trivially_relocatable(Wrapper));
```

The assertion is triggered under `DiagnoseNonTriviallyRelocatableReason` in this code:
```cpp
  if (!D->hasSimpleMoveConstructor() && !D->hasSimpleCopyConstructor()) {
    const auto *Decl = cast<CXXConstructorDecl>(
        LookupSpecialMemberFromXValue(SemaRef, D, /*Assign=*/false));
    if (Decl && Decl->isUserProvided())
      SemaRef.Diag(Loc, diag::note_unsatisfied_trait_reason)
          << diag::TraitNotSatisfiedReason::UserProvidedCtr
          << Decl->isMoveConstructor() << Decl->getSourceRange();
  }
```

The issue is the `cast< CXXConstructorDecl >` as `LookupSpecialMemberFromXValue` can return null. The `cast<>` is followed by a null check so it's presumably expected that `LookupSpecialMemberFromXValue` returns null, in which case the fix is likely just to replace `cast` with `cast_or_null`. If it's expected that the cast itself may fail then I assume there's `dyn_cast_or_null` that should be used.

### PR DESCRIPTION
**Pull request by cor3ntin**
If lookup did not find a copy constructor, it would return nulll, leading to an assert in `cast`.

Fixes #143325

### CODE REVIEW

File: clang/lib/Sema/SemaTypeTraits.cpp [hunk 1]
```diff
@@ -2052,7 +2052,7 @@ static void DiagnoseNonTriviallyRelocatableReason(Sema &SemaRef,
   }
 
   if (!D->hasSimpleMoveConstructor() && !D->hasSimpleCopyConstructor()) {
-    const auto *Decl = cast<CXXConstructorDecl>(
+    const auto *Decl = cast_or_null<CXXConstructorDecl>(
```
Comment (ojhunt) [inline clang/lib/Sema/SemaTypeTraits.cpp:2055]: I didn't realize that this path was being hit solely as a "is there some other constructor?" check, I was paranoid that there was a prior state error that meant a constructor was expected to exist.

**Review by ojhunt — APPROVED** [review]
Looks good
