### PR TITLE
[X86] Enable bfloat type support in inline assembly constraints

### LINKED ISSUE #68149: Can't pass `__m512bh` as inline assembly operand
Normally constraint `x` allows passing SIMD vectors as X86 inline assembly operands, as documented here for LLVM inline assembly:
https://llvm.org/docs/LangRef.html#inline-assembler-expressions

This Compiler Explorer link shows that this works for `__m512` but not for `__m512bh`.
https://godbolt.org/z/Wrrnr6E4d

Pasted here:

```c
#include <immintrin.h>
#include <stdint.h>

__m512bh broadcast_load_2xbf16(const void *src) {
  __m512bh dst;
  asm("vbroadcastss %[dst], dword ptr [%[src]]" :[dst]"=x"(dst) : [src]"r"(src) :);
  return dst;
}

__m512 broadcast_load_f32(const void *src) {
  __m512 dst;
  asm("vbroadcastss %[dst], dword ptr [%[src]]" :[dst]"=x"(dst) : [src]"r"(src) :);
  return dst;
}
```

Compile with flags: `-O3 -masm=intel -mavx -mavx2 -mfma -mf16c -mavx512f -mavx512vl -mavx512cd -mavx512bw -mavx512dq -mavx512bf16` .

The function `broadcast_load_f32` compiles but the function `broadcast_load_2xbf16` errors with:

```
<source>:6:7: error: couldn't allocate output register for constraint 'x'
    6 |   asm("vbroadcastss %[dst], dword ptr [%[src]]" :[dst]"=x"(dst) : [src]"r"(src) :);
      |       ^
1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by phoebewang**
Similar to FP16 but we don't have native scalar instruction support, so limit it to vector types only.

Fixes #68149

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -56904,6 +56904,10 @@ X86TargetLowering::getRegForInlineAsmConstraint(const TargetRegisterInfo *TRI,
         if (!Subtarget.hasFP16())
           break;
         [[fallthrough]];
+      case MVT::v8bf16:
+        if (!Subtarget.hasBF16())
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:56908]: Are multiple fallthroughs going to work? What happens for a subtarget that supports FP16 but not BF16?

Comment (phoebewang) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:56908]: Good catch! Repalce fallthrough with return.

**Comment by phoebewang** [comment]
Ping~

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 2]
```diff
@@ -56903,7 +56903,15 @@ X86TargetLowering::getRegForInlineAsmConstraint(const TargetRegisterInfo *TRI,
       case MVT::v8f16:
         if (!Subtarget.hasFP16())
           break;
-        [[fallthrough]];
+        if (VConstraint)
```
Comment (RKSimon) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:56906]: Why did you drop the Subtarget.hasVLX()?

Comment (phoebewang) [reply llvm/lib/Target/X86/X86ISelLowering.cpp:56906]: Good catch. I intended to drop for FP16 because it implies VLX. But I forgot to add back for BF16 which doesn't.

**Review by RKSimon — APPROVED** [review]
LGTM
