### PR TITLE
[clang-tidy] bugprone-lambda-function-name ignore macro in captures

### LINKED ISSUE #89065: [clang-tidy] bugprone-lambda-function-name false positive
Hi, I'm fixing my code and using this check for wrong function name prints, but fixing this error creates false positive.

How to reproduce:
```cpp
#include <iostream>
// Type your code here, or load an example.
int bug(int num) {
    return [num](){
        std::cout << __func__ << "\n";
        return num;
    }();
}

int fixed(int num) {
    return [num, func=__func__](){
        std::cout << func << "\n";
        return num;
    }();
}

int main()
{
    bug(1);
    fixed(1);
    return 0;
}
```
Execute clang-tydy, with: 

 -checks=-*,bugprone-lambda-function-name

Result:

```
<[source>:5:22: warning: inside a lambda, '__func__' expands to the name of the function call operator; consider capturing the name of the enclosing function explicitly [bugprone-lambda-function-name]]
    5 |         std::cout << __func__ << "\n";
      |                      ^
[<source>:11:23: warning: inside a lambda, '__func__' expands to the name of the function call operator; consider capturing the name of the enclosing function explicitly [bugprone-lambda-function-name]]
   11 |     return [num, func=__func__](){
      |
```

Code execution result:
```
operator()
fixed
```

We can see that 'bug' function have a error and it is found.
But we can see that the fix in 'fixed' function, where we are capturing __func__ name inside lambda capture is also flagged, and it should not be.

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #89065

### CODE REVIEW

File: clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp [hunk 1]
```diff
@@ -69,9 +71,8 @@ void LambdaFunctionNameCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
 }
 
 void LambdaFunctionNameCheck::registerMatchers(MatchFinder *Finder) {
-  // Match on PredefinedExprs inside a lambda.
-  Finder->addMatcher(predefinedExpr(hasAncestor(lambdaExpr())).bind("E"),
-                     this);
+  auto IsInsideALambda = hasAncestor(cxxMethodDecl(isInLambda()));
+  Finder->addMatcher(predefinedExpr(IsInsideALambda).bind("E"), this);
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp:75]: this may not work for `[] (const char* func = __func__){ func; }();`
maybe we should check only body of function

File: clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp [hunk 2]
```diff
@@ -69,9 +73,13 @@ void LambdaFunctionNameCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
...
-  // Match on PredefinedExprs inside a lambda.
-  Finder->addMatcher(predefinedExpr(hasAncestor(lambdaExpr())).bind("E"),
-                     this);
+  Finder->addMatcher(
+      functionDecl(cxxMethodDecl(isInLambda()),
+                   hasBody(hasDescendant(expr(
+                       predefinedExpr(hasAncestor(functionDecl().bind("fn")))
+                           .bind("E")))),
+                   functionDecl(equalsBoundNode("fn"))),
+      this);
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp:82]: If you make the outer `functionDecl` the `cxxMethodDecl`, then you can remove the inner `cxxMethodDecl` that encloses the lambda. Or was there a reason for doing it this way?
You can also drop the `expr` matcher that surrounds the `predefinedExpr`, and the `functionDecl` surrounding the `equalsBoundNode`.

I.e.:
```c++
cxxMethodDecl(isInLambda(),
                    hasBody(hasDescendant(
                        predefinedExpr(hasAncestor(functionDecl().bind("fn")))
                            .bind("E"))),
                    equalsBoundNode("fn"))
```

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -151,6 +151,10 @@ Changes in existing checks
   <clang-tidy/checks/bugprone/inc-dec-in-conditions>` check to ignore code
   within unevaluated contexts, such as ``decltype``.
 
+- Improved :doc:`bugprone-lambda-function-name
+  <clang-tidy/checks/bugprone/lambda-function-name>` check by ignoring
+  ``__func__`` macro in lambda captures and nested function declaration.
```
Comment (5chmidti) [inline clang-tools-extra/docs/ReleaseNotes.rst:156]: I think the default parameter part should be included as well (+nits):
`check by ignoring the ``__func__`` macro in lambda captures, initializers of default parameters and nested function declarations.`

File: clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp [hunk 4]
```diff
@@ -69,9 +73,13 @@ void LambdaFunctionNameCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
 }
 
 void LambdaFunctionNameCheck::registerMatchers(MatchFinder *Finder) {
-  // Match on PredefinedExprs inside a lambda.
-  Finder->addMatcher(predefinedExpr(hasAncestor(lambdaExpr())).bind("E"),
-                     this);
+  Finder->addMatcher(
+      cxxMethodDecl(isInLambda(),
+                    hasBody(hasDescendant(expr(
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp:78]: this will find only first usage, but not a second.
In such case if you would have class declaration with a method in lambda, then it would found only this.
```
  [] {
    struct S {
      void f() {
        __func__;
      }
    };
    __func__();
  }();
```

this test is missing, other option would be to have:
```
cxxMethodDecl(isInLambda(),
                          decl().bind("fn"),
                          hasBody(foreachDescendant(predefinedExpr(hasAncestor(cxxMethodDecl().bind("fn2")),
                                                                                                   hasAncestor(cxxMethodDecl(equalsBoundNode("fn"), equalsBoundNode("fn2"))))
```

or instead of using double equalsBoundNode, you can put this code into check method, in such case we could avoid second hasAncestor, other option would be something like `hasAncestor(compoundStmt(hasParent(cxxMethodDecl...` but this also can be error prone, as it will skip functions in lambdas.

Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp:78]: Why does it need two `equalsBoundNode`. I try to use it and it can work.
```c++
      cxxMethodDecl(isInLambda(),
                    hasBody(forEachDescendant(
                        predefinedExpr(hasAncestor(cxxMethodDecl().bind("fn")))
                            .bind("E"))),
                    equalsBoundNode("fn")),
```

Comment (PiotrZSL) [reply clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp]: May work, as forEachDescendant may be doing new "set" of variables, to be sure try this:
```
  [] {
    struct S {
      void f() {
        __func__;
      }
    };
    __func__();

    struct S2 {
      void f() {
        __func__;
      }
    };

    __func__();
  }();
```

If it work correctly then both func should be found.

Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/bugprone/LambdaFunctionNameCheck.cpp]: Yes, it work correctly.

**Review by PiotrZSL — APPROVED** [review]
LGTM

**Review by 5chmidti — APPROVED** [review]
