### PR TITLE
[libc++] fix atomic::wait memory order

### LINKED ISSUE #109290: [libc++] Incorrect memory order in atomic wait
I think I've found an issue in `__libcpp_atomic_wait`, where an atomic operation with an overly-relaxed memory order argument could theoretically result in a lost wakeup. For what it's worth, the equivalent part of libstdc++'s atomic wait implementation uses stronger memory ordering, which I believe to be correct.

To be clear, I don't think this is a problem in practice on x86 or ARM, but according to the C++ standard it looks like a bug.

### Background

The atomic wait implementation in libc++ uses platform wait primitives such as futexes (linux) and `__ulock_wait/__ulock_wait` (macOS) to perform wait and notify operations. Because the platform wait primitives usually only work for values of a particular width (32-bit [on Linux](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/include/__atomic/contention_t.h#L23-L24)), you can't always wait on the user's value directly. The library instead does a laundering trick where internally it waits on a proxy value of the correct size. To do this, it uses the address of the user's atomic value to look up an entry in a '[contention table](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L127-L128)'. Each entry in the table contains [two atomic values of an appropriate size for the platform](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L122-L123); one representing a monotonically increasing counter which is used as the proxy for the user's value, and one holding a count of the number of threads currently waiting on the variable. The latter is used in a nifty optimisation which allows the platform `notify` call to be elided when there are no threads waiting on the value.

### The key parts of the algorithm

The algorithm that does the contention tracking is split across a few functions:
[__libcpp_contention_wait](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L151), [__libcpp_atomic_notify](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L163), [__libcpp_contention_notify](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L138)

But after inlining and removal of non-relevant parts, it essentially boils down to this pseudocode:

```c++
std::atomic<uint32_t> platform_state;   // Monotonically increasing count
std::atomic<uint32_t> contention_state; // Waiter count

-------------------------------
// Notifying thread
platform_state.fetch_add(1, mo_release);      // (1) <---- Here is the problem
if (0 != contention_state.load(mo_seq_cst)) { // (2) 
  platform_notify_all(platform_state);
}

-------------------------------
// Waiting thread
contention_state.fetch_add(1, mo_seq_cst);    // (3)
platform_wait(platform_state, old_value);     // (4)
contention_state.fetch_sub(1, mo_release);    // (5)
```

The line marked "Here is the problem" corresponds to [this line in `atomic.cpp`](https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L166-L167).

### The problem

According to the C++ memory model, we should reason about code involving atomics in terms of "synchronizes-with" and "happens-before" relations, rather than potential reorderings. The contention tracking algorithm cannot be reasoned about *solely* in terms of synchronization between release-acquire pairs. It also requires the waiting thread and the notifying thread to agree on a single total order for operations `(1)`, `(2)`, `(3)` and `(4)`. The way to achieve that (according to the standard) is to make all four operations seq-cst.

Based on that, the `mo_release` on `(1)` looks insufficient. Informally, under the C++ memory model, I do not believe there is anything stopping `(1)` from 'reordering' with `(2)`. We need some sort of StoreLoad barrier to get the single total order property.

### A Herd7 simulation shows that a lost wakeup *could* occur under the C++ memory model

Inspired by @jiixyj's [Herd7](https://diy.inria.fr/doc/herd.html) simulation of a [similar contention tracking mechanism in the semaphore implementation](https://reviews.llvm.org/D114119#3193088), I thought I'd have a go here too. I'm certainly no expert with Herd, so treat this with a pinch of salt.

I've modelled the existing algorithm as:
#### `prog.litmus`
```c++
C prog

{
}

P0 (atomic_int* plat, atomic_int* waiters) {
  atomic_fetch_add_explicit(plat, 1, memory_order_release);
  int num_waiters = atomic_load_explicit(waiters, memory_order_seq_cst);
  int do_notify = (num_waiters != 0);
}

P1 (atomic_int* plat, atomic_int* waiters) {
  atomic_fetch_add_explicit(waiters, 1, memory_order_seq_cst);
  int do_wait = (atomic_load_explicit(plat, memory_order_seq_cst) == 0);
  
  // Deliberately left out - it's not relevant to the analysis
  //atomic_fetch_sub_explicit(waiters, 1, memory_order_release);
}

exists
(0:do_notify=0 /\ 1:do_wait=1)
```

It's not possible to model read-compare-wait operations in Herd. Instead I've modelled the platform wait as a sequentially consistent load; I'm genuinely unsure if that's justified. I've found [some discussion on stack overflow](https://stackoverflow.com/a/56192407) but I don't find it fully convincing. In [D114119](https://reviews.llvm.org/D114119#3193088) it's modelled as a relaxed compare-exchange-strong. That looks like it might be overkill for this situation, but I can't say for sure. Guidance on this would be welcome.

The proposition at the bottom looks for the case where thread P1 enters a waiting state, but thread P0 decides *not* to call `notify`, which could result in deadlock. The `/\` token represents logical conjunction.

Executing this in Herd with:
```
mkdir -p output
rm -f output/prog.dot
herd7 -c11 -show prop -graph columns -o output -showinitwrites false -oneinit false prog.litmus
dot -Tpdf output/prog.dot > prog.pdf
```
shows that there is one possible execution exhibiting the lost wake-up behaviour. It corresponds to thread P0 running to the end without calling `notify`, while P1 decides that a 'wait' is necessary. Crucially, even though P0 has incremented `plat` 'before' checking `waiters`, P1 observes an *older* value in the modification order of `plat` and therefore decides to enter a waiting state.

In the Herd simulation, the issue can be solved by enforcing a total order on the operations involving `plat`. Upgrading the relaxed increment of `plat` in thread P0 to have `seq_cst` memory order results in Herd reporting *no remaining executions satisfying the proposition*.

### Would a compiler ever make such reordering?
I've not found good sources on this. My suspicion is that it's unlikely to happen in practice. But I believe the standard allows it.

### Could it happen on x86?
On x86, even a [fully relaxed RMW operation has sequentially consistent behaviour](https://stackoverflow.com/a/66957641). So no, it can't happen on x86.

### Could it happen on ARM architectures?
On AArch64, the 'notify' side of the algorithm [compiles down to](https://godbolt.org/z/vh8rh6MTa) a Load-linked/Store-conditional (LL/SC) loop for incrementing the platform counter, followed by a load-acquire (`LDAR`) for reading the number of waiters. The [`STLXR` in the LL/SC loop](https://developer.arm.com/documentation/ddi0602/2024-06/Base-Instructions/STLXR--Store-release-exclusive-register-), and the following `LDAR` instruction [both have acquire-release semantics](https://developer.arm.com/documentation/102336/0100/Load-Acquire-and-Store-Release-instructions), so they will not reorder.

For what it's worth, if the `LDAR` is relaxed to a plain `LDR` (i.e. `std::memory_order_relaxed`) then Herd shows that it can reorder with the `STLXR` and result in a lost wakeup. The relevant parts of the algorithm are modelled here:
```
AArch64 Contention_Tracking
{
0:X0=plat; 0:X1=count;
1:X0=plat; 1:X1=count;
}
 P0                 | P1;
 label1:            | label2:;
 LDXR W8, [X0]      | LDAXR W8, [x1];
 ADD W8, W8, #1     | ADD W8, W8, #1;
 STLXR W9, W8, [X0] | STLXR W9, W8, [x1];
 CBNZ W9, label1    | CBNZ W9, label2;
 LDR W2, [X1]       | LDAR W3, [X0];
exists
(0:X2=0 /\ 1:X3=0)
```
You can try this in the [online Herd sim](https://diy.inria.fr/www/). The proposition at the bottom corresponds to the notify side seeing no waiters (and therefore not calling the platform notify operation), and the waiter side not seeing the increment to the platform variable.

### Could it happen on more relaxed architectures?

It looks like it is [possible on POWER](https://stackoverflow.com/a/52636008), but I haven't done any further investigation.

### Potential solutions
I think the best solution is probably to upgrade `(1)` to `mo_seq_cst`. This is what [libstdc++ does](https://github.com/gcc-mirror/gcc/blob/4af196b2ebd662c5183f1998b0184985e85479b2/libstdc%2B%2B-v3/include/bits/atomic_wait.h#L234). On x86, even a [fully relaxed RMW operation has sequentially consistent behaviour](https://stackoverflow.com/a/66957641), so the change will only affect potential compiler reorderings. On ARM, [upgrading a RMW op from `release` to `seq_cst`](https://godbolt.org/z/d1z794sz8) turns an `ldxr` into a `ldaxr` in the LL/SC loop. This ought to be far cheaper than any sort of fence.

Other options would be to turn `(2)` into a read-don't-modify-write operation (`fetch_add(0, mo_acq_rel)`) or to insert `seq_cst` fences between `(1)` & `(2)` and `(3)` and `(4)`  (along with fully relaxing the other operations). Both of which look more expensive to me.

### Concrete proposal
Update this line to be `std::memory_order_seq_cst`:
https://github.com/llvm/llvm-project/blob/7e56a092781b094307155457f129df7deda411ae/libcxx/src/atomic.cpp#L166

### PR DESCRIPTION
**Pull request by huixie90**
Fixes #109290 

See the GH issue for the details. In conclusion, we have two issues in the `atomic<T>::wait` when `T` does not match our `contention_t`:
- We don't have a total single order which can leads to missed notification based on the Herd7 simulation on relaxed architectural like PowerPC
- We assumed the platform wait (`futex_wait`/`__ulock_wait`) has seq_cst barrier internally but there is no such guarantee

### CODE REVIEW

**Comment by aharrison24** [comment]
Thanks for taking this issue on! This looks like a correct implementation of ["Option 1a"](https://github.com/llvm/llvm-project/issues/109290#issuecomment-2369783010) from the original issue I raised. That's been verified by three separate people using Herd, Dartagnan and GenMC respectively, so we're relatively sure it's doing the right thing at this point!

File: libcxx/src/atomic.cpp [hunk 1]
```diff
@@ -163,7 +164,7 @@ static void __libcpp_contention_wait(__cxx_atomic_contention_t volatile* __conte
 static void __libcpp_atomic_notify(void const volatile* __location) {
   auto const __entry = __libcpp_contention_state(__location);
   // The value sequence laundering happens on the next line below.
-  __cxx_atomic_fetch_add(&__entry->__platform_state, __cxx_contention_t(1), memory_order_release);
+  __cxx_atomic_fetch_add(&__entry->__platform_state, __cxx_contention_t(1), memory_order_seq_cst);
```
Comment (aharrison24) [inline libcxx/src/atomic.cpp:169]: I'm not familiar with LLVM coding conventions, but would it be worth adding a note here about the fact that there are no platform guarantees of a memory barrier in the platform wait implementation?

**Review by ldionne — APPROVED** [review]
LGTM, but +1 about adding a comment.

File: libcxx/src/atomic.cpp [hunk 2]
```diff
@@ -151,7 +151,10 @@ __libcpp_contention_monitor_for_wait(__cxx_atomic_contention_t volatile* /*__con
 static void __libcpp_contention_wait(__cxx_atomic_contention_t volatile* __contention_state,
                                      __cxx_atomic_contention_t const volatile* __platform_state,
                                      __cxx_contention_t __old_value) {
-  __cxx_atomic_fetch_add(__contention_state, __cxx_contention_t(1), memory_order_seq_cst);
+  __cxx_atomic_fetch_add(__contention_state, __cxx_contention_t(1), memory_order_relaxed);
+  // https://github.com/llvm/llvm-project/issues/109290
+  // There are no platform guarantees of a memory barrier in the platform wait implementation
+  __cxx_atomic_thread_fence(memory_order_seq_cst);
```
Comment (gonzalobg) [inline libcxx/src/atomic.cpp:157]: @huixie90 why `seq_cst`? Could we add a comment explaining that?

File: libcxx/src/atomic.cpp [hunk 3]
```diff
@@ -163,7 +166,7 @@ static void __libcpp_contention_wait(__cxx_atomic_contention_t volatile* __conte
 static void __libcpp_atomic_notify(void const volatile* __location) {
   auto const __entry = __libcpp_contention_state(__location);
   // The value sequence laundering happens on the next line below.
-  __cxx_atomic_fetch_add(&__entry->__platform_state, __cxx_contention_t(1), memory_order_release);
+  __cxx_atomic_fetch_add(&__entry->__platform_state, __cxx_contention_t(1), memory_order_seq_cst);
```
Comment (gonzalobg) [inline libcxx/src/atomic.cpp:169]: Similar as above, why is `seq_cst` required?
