### PR TITLE
[AMDGPU] Mark ASYNCMARK as meta instruction to fix hazard cycle miscounting

### LINKED ISSUE #186878: [AMDGPU] asyncmark/wait.asyncmark intrinsics produce incorrect code for 3-stage software-pipelined loops
The `llvm.amdgcn.asyncmark` and `llvm.amdgcn.wait.asyncmark` intrinsics (introduced in #180467) produce numerically incorrect results when used in 3-stage software-pipelined loops with `buffer_load_dwordx4 ... lds` (async DMA to LDS). 2-stage pipelines are unaffected.

### Reproducer

Given the `.optimized.ll` from a 4096×4096×4096 f32 GEMM with 3-stage pipelining, replacing the asyncmark intrinsics with explicit `s_waitcnt` calls produces correct results while the original IR produces ~40% wrong output elements.

The replacement:
```llvm
; REMOVED:
call void @llvm.amdgcn.asyncmark()

; REPLACED:
call void @llvm.amdgcn.wait.asyncmark(i16 2)
→ call void @llvm.amdgcn.s.waitcnt(i32 8184)  ; vmcnt(8) = 2 groups × 4 loads/group

call void @llvm.amdgcn.wait.asyncmark(i16 0)
→ call void @llvm.amdgcn.s.waitcnt(i32 8176)  ; vmcnt(0)
```

Both versions compiled with `llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -O3`. The LLVM IR and assembly for both the broken (original) and working (fixed) cases are attached.

A self-contained reproducer script is available at: https://github.com/jerryyin/scripts/tree/master/iree/reproducers/asyncmark_bug

### Results

| Case | max abs diff vs baseline | Wrong elements | Verdict |
|------|--------------------------|----------------|---------|
| Original (with asyncmark) | ~50 | ~6.8M / 16.8M (40%) | **FAIL** |
| Modified (asyncmark → s_waitcnt) | 0.000000 | 0 / 16.8M | **PASS** |

### Analysis

The `ASYNCMARK`/`WAIT_ASYNCMARK` pseudo-instructions inherit `IntrHasSideEffects` from their intrinsic definitions in `IntrinsicsAMDGPU.td`. This has two consequences:

1. **Scheduling barrier**: `SIInstrInfo::isGlobalMemoryObject()` (via `TargetInstrInfo::isGlobalMemoryObject()`) returns `true` for instructions with unmodeled side effects. This makes the pseudos act as global memory barriers in the machine scheduler DAG, producing structurally different instruction ordering and register allocation.

2. **Score tracking**: In `SIInsertWaitcnts.cpp`, async LDS DMA writes are excluded from normal LDSDMA tracking (`isNonAsyncLdsDmaWrite` check at line 1206) and routed through `AsyncScore`/`AsyncMarks` instead. The `mergeAsyncMarks()` function incorrectly merges scores during loop backedge processing when 3+ marks interact simultaneously.

The assembly diff between original (822 lines) and fixed (817 lines) shows different register allocation and instruction ordering — confirming that the scheduling barrier effect, not just vmcnt values, contributes to the incorrect codegen.

### PR DESCRIPTION
**Pull request by adeshcom14**
ASYNCMARK emits no hardware code it is used for tracking purpose but was not marked as meta, causing getNumWaitStates to return 1 and GCNHazardRecognizer to incorrectly count it as a pipeline cycle.
This patch marks ASYNCMARK as meta-Instruction so it correctly reports 0 wait states.

Fixes: #186878

### CODE REVIEW

**Comment by RyanRio** [comment]
> TSFlag bits are precious and it's not worth wasting one on a single instruction case. Just add the helper function

Good point, oh well

File: llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp [hunk 1]
```diff
@@ -3263,7 +3263,9 @@ bool SIInsertWaitcnts::insertWaitcntInBlock(MachineFunction &MF,
                                          E = Block.instr_end();
        Iter != E; ++Iter) {
     MachineInstr &Inst = *Iter;
-    if (Inst.isMetaInstruction())
+    // ASYNCMARK is meta instr but needs processing by
+    // generateWaitcntInstBefore and recordAsyncMark for vmcnt tracking.
+    if (Inst.isMetaInstruction() && Inst.getOpcode() != AMDGPU::ASYNCMARK)
```
[the remark this answers is not in the document]
Comment (adeshcom14) [reply llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp]: Added static helper

File: llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp [hunk 2]
```diff
@@ -3263,7 +3269,7 @@ bool SIInsertWaitcnts::insertWaitcntInBlock(MachineFunction &MF,
                                          E = Block.instr_end();
        Iter != E; ++Iter) {
     MachineInstr &Inst = *Iter;
-    if (Inst.isMetaInstruction())
+    if (shouldSkipForWaitcnt(Inst))
```
Comment (ssahasra) [inline llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp]:
```suggestion
    if (!needsWaitcntInsertion(Inst))
```
@Pierre-vh would you agree that this suggestion reflects the actual decision being made at this point?

**Review by ssahasra — APPROVED** [review]
LGTM, but please give @Pierre-vh a chance to have a look.

**Review by Pierre-vh — APPROVED** [review]
LGTM if the nit is addressed

File: llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp (hunk 2 above)
Comment (adeshcom14) [reply llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp]: fixed

**Comment by FrederickVu** [comment]
@adeshcom14 I believe wait_asyncmark also exhibits this phantom wait state behavior.

**Comment by adeshcom14** [comment]
> @adeshcom14 I believe wait_asyncmark also exhibits this phantom wait state behavior.

Yes, it is also marked as meta now

**Comment by adeshcom14** [comment]
@ssahasra @Pierre-vh PTAL

**Review by arsenm — APPROVED** [review]

**Comment by arsenm** [comment]
Has conflict

File: llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp [hunk 3]
```diff
@@ -223,6 +223,13 @@ static const unsigned
         AMDGPU::S_WAIT_KMCNT,     AMDGPU::S_WAIT_XCNT,
         AMDGPU::S_WAIT_ASYNCCNT};
 
+// ASYNCMARK and WAIT_ASYNCMARK are meta instructions that emit no hardware
+// code but still need to be processed by this pass for async vmcnt tracking.
+static bool isNonWaitcntMetaInst(const MachineInstr &MI) {
+  return MI.isMetaInstruction() && MI.getOpcode() != AMDGPU::ASYNCMARK &&
+         MI.getOpcode() != AMDGPU::WAIT_ASYNCMARK;
+}
+
```
Comment (ssahasra) [inline llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp:237]: The following is more readable. It avoids the repeated calls to `getOpcode()`, and it brings the exceptions up front.

```suggestion
static bool shouldSkipForWaitcnt(const MachineInstr &MI) {
  switch (MI.getOpcode()) {
    case AMDGPU::ASYNCMARK:
    case AMDGPU::WAIT_ASYNCMARK:
      return false;
    default:
      return MI.isMetaInstruction();
  }
}
```

File: llvm/test/CodeGen/AMDGPU/asyncmark-pregfx12.ll [hunk 4]
```diff
@@ -366,10 +366,11 @@ define void @test_pipelined_loop(ptr addrspace(1) %foo, ptr addrspace(3) %lds, p
 ; SDAG-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
 ; SDAG-NEXT:    v_readfirstlane_b32 s4, v2
 ; SDAG-NEXT:    s_mov_b32 m0, s4
-; SDAG-NEXT:    v_mov_b32_e32 v5, 0
+; SDAG-NEXT:    s_nop 0
 ; SDAG-NEXT:    global_load_dword v[0:1], off lds
 ; SDAG-NEXT:    ; asyncmark
 ; SDAG-NEXT:    global_load_dword v[0:1], off lds
+; SDAG-NEXT:    v_mov_b32_e32 v5, 0
```
Comment (ssahasra) [inline llvm/test/CodeGen/AMDGPU/asyncmark-pregfx12.ll:373]: So the `v_mov` got replaced by an `s_nop`, and then it was scheduled later. What does that mean?

File: llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp (hunk 3 above)
Comment (adeshcom14) [reply llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp:237]: Fixed

File: llvm/test/CodeGen/AMDGPU/asyncmark-pregfx12.ll (hunk 4 above)
Comment (adeshcom14) [reply llvm/test/CodeGen/AMDGPU/asyncmark-pregfx12.ll:373]: The v_mov didn't really get "replaced" by s_nop , actually marking ASYNCMARK as Meta changed the post-RA scheduler's bundling decisions, which moved v_mov later and exposed a hazard gap that s_nop now fills.

When ASYNCMARK becomes meta, the post-RA scheduler treats it as transient instr as well and bundles it with the adjacent loads {GLOBAL_LOAD_LDS_DWORD, ASYNCMARK, GLOBAL_LOAD_LDS_DWORD}. GCNHazardRecognizer::getHazardType() skips hazard checking for bundles, so the bundle gets placed right after S_MOV_B32 m0, pushing v_mov after the bundle. Previously ASYNCMARK was a standalone scheduling unit, so the first GLOBAL_LOAD_LDS_DWORD triggered an m0-to-LDS load hazard and v_mov was picked to fill the 1 cycle gap.

The post-RA hazard recognizer pass then walks inside the bundle, detects the m0-to-LDS-load hazard, and inserts S_NOP 0.
