### PR TITLE
[ValueTracking] Fix bug of using wrong condition for deducing KnownBits

### LINKED ISSUE #124275: wrong code at -O1 and above on x86_64-linux-gnu
It appears to be a recent regression from 19.1.0. 

Compiler Explorer: https://godbolt.org/z/haMfGoo6h

```
[548] % clangtk -v
clang version 20.0.0git (https://github.com/llvm/llvm-project.git ddd2f57b29661f21308eec0400fa92a6d075b0c6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/home/suz/suz-local/software/local/clang-trunk/bin
Build config: +assertions
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 12.1
[549] % 
[549] % clangtk -O1 small.c
[550] % ./a.out
Aborted
[551] % 
[551] % cat small.c
int printf(const char *, ...);
unsigned a;
int b, c = 1;
int main() {
  int d;
  a = -1;
  if (a < 1)
    goto e;
  d = c;
  if (d) {
  e:;
  }
  if (!d)
    __builtin_abort();
  if (b)
    goto e;
  return 0;
}
```

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[ValueTracking] Add test for issue 124275**
- **[ValueTracking] Fix bug of using wrong condition for deducing KnownBits**

Fixes https://github.com/llvm/llvm-project/issues/124275

Bug was introduced by https://github.com/llvm/llvm-project/pull/114689

Now that computeKnownBits supports breaking out of recursive Phi
nodes, `IncValue` can be an operand of a different Phi than `P`. This
breaks the previous assumptions we had when using the possibly
condition at `CxtI` to constrain `IncValue`.

### CODE REVIEW

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -1705,9 +1711,10 @@ static void computeKnownBitsFromOperator(const Operator *I,
                     m_Br(m_c_ICmp(Pred, m_Specific(IncValue), m_APInt(RHSC)),
```
Comment (nikic) [inline llvm/lib/Analysis/ValueTracking.cpp:1711]: Can we fix this by replacing RecQ.CxtI with `P->getIncomingBlock(u)->getTerminator()` instead? (In terms of minimally ugly correct implementation, not maximally theoretically powerful.)

Comment (goldsteinn) [reply llvm/lib/Analysis/ValueTracking.cpp:1711]: I don't think so. Take the test case. If the branch in `%B1` used a `%cmp` on `%sub` that would be patently incorrect to use when analyzing `%sub` in `%B0`

**Review by nikic — APPROVED** [review]
LGTM
