### PR TITLE
Fix scalar overload name constructed by ReplaceWithVeclib.cpp

### LINKED ISSUE #111093: ReplaceWithVeclib constructs scalar overload intrinsic name incorrectly
The ReplaceWithVeclib (replace-with-veclib) pass constructs the scalar overload name used to look up the veclib call by passing all the input argument types (converted to scalar) to `Intrinsic::getName`.  

https://github.com/llvm/llvm-project/blob/e9b7a093417bda7e0bed2bd62bcaeb7c2a662665/llvm/lib/CodeGen/ReplaceWithVeclib.cpp#L132

This is incorrect.  Instead, it should be using `isVectorIntrinsicWithOverloadTypeAtArg` to determine whether an argument type contributes to the overload, including the return argument (-1).

This mostly went unnoticed because most intrinsics supported so far only had one argument, and that argument type matched the return type.  For other intrinsics, such as `pow` or `atan2` with two arguments, this would construct a name like `llvm.pow.f64.f64`.  This won't match the name in the table defined in `VecFuncs.def`, causing it to fail replacement silently.

There is a note in `llvm/test/CodeGen/AArch64/replace-with-veclib-armpl.ll` noting the bug above the `llvm.pow` checks, and the checks were written to match the input (no translation).  I didn't see the note until I debugged the pass after running into the bug while trying to implement this for `atan2`.

https://github.com/llvm/llvm-project/blob/e9b7a093417bda7e0bed2bd62bcaeb7c2a662665/llvm/test/CodeGen/AArch64/replace-with-veclib-armpl.ll#L337-L340

### PR DESCRIPTION
**Pull request by tex3d**
ReplaceWithVeclib.cpp would construct overload name using all the arguments in the intrinsic, but overloads should only be constructed from arguments for which isVectorIntrinsicWithOverloadTypeAtArg returns true, including the return type first (index -1).

Additionally,
- skip when `Intrinsic::not_intrinsic`, otherwise `isVectorIntrinsicWithOverloadTypeAtArg` asserts for some IntrinsicCalls.

Unblocks translation for pow and atan2 intrinsics.

Fixes #111093

### CODE REVIEW

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 1]
```diff
@@ -108,8 +108,22 @@ static bool replaceWithCallToVeclib(const TargetLibraryInfo &TLI,
...
+
+  // OloadTys collects types used in scalar intrinsic overload name.
+  SmallVector<Type *, 3> OloadTys;
+  if (VTy && isVectorIntrinsicWithOverloadTypeAtArg(IID, -1))
+    OloadTys.push_back(VTy->getElementType());
+
   for (auto Arg : enumerate(II->args())) {
     auto *ArgTy = Arg.value()->getType();
+    // Gather type if it is used in the overload name.
+    if (isVectorIntrinsicWithOverloadTypeAtArg(IID, Arg.index())) {
```
Comment (farzonl) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:120]: We seem to be duplicating things used later and i'm wonder if  it wouldn't be better to store some of this stuff in variables like :
- `isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index()`
- `auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)`

If you do that  you should be able to flatten the conditional  and combine it with the conditionals on 127 ans 129

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 2]
```diff
@@ -129,7 +143,7 @@ static bool replaceWithCallToVeclib(const TargetLibraryInfo &TLI,
   // using scalar argument types.
   std::string ScalarName =
       Intrinsic::isOverloaded(IID)
-          ? Intrinsic::getName(IID, ScalarArgTypes, II->getModule())
```
Comment (farzonl) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:132]: I feel weird about this. Does `ScalarArgTypes` get used anywhere else? From the PR perspective now the code that pushes to the `SmallVector` isn't being used, but you have left it in.

**Comment by mgabka** [comment]
you need also to adjust more tests:
replace-with-veclib-sleef-scalable.ll
replace-with-veclib-sleef.ll

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 1 above)
Comment (mgabka) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:120]: are there any tests, testing this logic? I think the pow case is working thanks to the condition added to line 114

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 2 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:132]: It's used to construct the function type `ScalarFTy` below.  This is why it needs all the argument types.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 1 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp]: The `pow` case is impacted by both this logic and return type logic, since `OloadTys` should include only the return type for `pow`, not each of the argument types.  `isVectorIntrinsicWithOverloadTypeAtArg()` is how you determine the arguments that the intrinsic is overloaded on, when not `void`, and defaults to -1 (return type).

Other tests will be running through this logic (and turning out the same), but the pow one is the only case with two arguments which had existing tests meant to match a vector lib call right now.  `atan2` will be added soon, which also needs this.  Other intrinsics could require this change in theory, if there's a matching vector lib call for them.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 3]
```diff
@@ -100,27 +100,38 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
...
+
   for (auto Arg : enumerate(II->args())) {
     auto *ArgTy = Arg.value()->getType();
-    if (isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index())) {
-      ScalarArgTypes.push_back(ArgTy);
-    } else if (auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)) {
-      ScalarArgTypes.push_back(VectorArgTy->getElementType());
+    auto *ScalarArgTy = ArgTy->getScalarType();
+    ScalarArgTypes.push_back(ScalarArgTy);
+    if (isVectorIntrinsicWithOverloadTypeAtArg(IID, Arg.index()))
```
Comment (farzonl) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:125]:
```suggestion
    bool RequiresOverloadType = isVectorIntrinsicWithOverloadTypeAtArg(IID, Arg.index());
    if (RequiresOverloadType)
```

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 4]
```diff
@@ -100,27 +100,38 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
...
+        OloadTys.push_back(ScalarArgTy);
+    if (auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)) {
       // When return type is void, set EC to the first vector argument, and
       // disallow vector arguments with different ECs.
       if (EC.isZero())
         EC = VectorArgTy->getElementCount();
       else if (EC != VectorArgTy->getElementCount())
         return false;
-    } else
+    } else if (!isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index()))
```
Comment (farzonl) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:134]:
```suggestion
    }
    if (!RequiresOverloadType)
```

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 5]
```diff
@@ -100,27 +100,38 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
...
     auto *ArgTy = Arg.value()->getType();
-    if (isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index())) {
-      ScalarArgTypes.push_back(ArgTy);
-    } else if (auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)) {
-      ScalarArgTypes.push_back(VectorArgTy->getElementType());
+    auto *ScalarArgTy = ArgTy->getScalarType();
+    ScalarArgTypes.push_back(ScalarArgTy);
+    if (isVectorIntrinsicWithOverloadTypeAtArg(IID, Arg.index()))
+        OloadTys.push_back(ScalarArgTy);
+    if (auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)) {
```
Comment (farzonl) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:127]: So we changed the behavior here  before it was  `isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index())` is true and `VectorArgTy` is not NULL. Now you changed it that `isVectorIntrinsicWithScalarOpAtArg` can be true or false and we still  run this block. Why is this the case?

Does it make sens to do 
```c++
if (!isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index()))
   return false;
OloadTys.push_back(ScalarArgTy);
if (auto *VectorArgTy = dyn_cast<VectorType>(ArgTy)) {
...
}
```

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 3 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:125]: I don't understand the need for this.  It's the only place this is called for this argument index.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 4 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:134]: This is a different call for a different property: `ScalarOpAtArg`, not `OverloadTypeAtArg`.

Comment (farzonl) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:134]: if `isVectorIntrinsicWithOverloadTypeAtArg(IID, Arg.index());` is false on line 125 then it will be false here too. `IID` and `Arg.index()` do not change in the 9 lines in between.

Comment (farzonl) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:134]: Anyways we can ignore this comment if we go with https://github.com/llvm/llvm-project/pull/111095/files#r1790956438

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 5 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:127]: > before it was isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index()) is true and VectorArgTy is not NULL

That's not quite right.  It was if `isVectorIntrinsicWithScalarOpAtArg` is false and VectorArgTy is not NULL.

The difference is that before, if `isVectorIntrinsicWithScalarOpAtArg` returned true and you had a vector arg type, we would have added the vector arg type instead of a scalar type to the overload and the function signature.  This would be a vector arg present in the scalar form of the intrinsic that doesn't scale with vectorization of the intrinsic.

I don't think the trivially vectorizable intrinsic path is meant to handle that case in the first place, so I didn't think this code is meant to do so either.  So the assumption was made that we only need to add the scalar types to these sets, which simplified the code a bit.

If you think we do want to handle that case, I can change the code back to adding the (potentially) vector argument type when `isVectorIntrinsicWithScalarOpAtArg` is true.

I can think of a sort of intrinsic that could do that: a resource load or store intrinsic with a vector for coordinates that doesn't match the vector dimension for the width of the load or store.  Would we want these to be considered trivially vectorizable intrinsics?

Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:127]: In any case, we definitely should not do this up front:
```
if (!isVectorIntrinsicWithScalarOpAtArg(IID, Arg.index()))
   return false;
```

Otherwise, any intrinsic with a vector operand will be skipped.  That's not what this code does.  It expects a vector or scalar operand.  If vector, the scalar type is used and it checks that the size matches, otherwise, it's a scalar operand, this scalar type is used, and `isVectorIntrinsicWithScalarOpAtArg` should return true (it would return false for vector operands).

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 4 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:134]: These two functions are not the same:
`isVectorIntrinsicWithScalarOpAtArg`
`isVectorIntrinsicWithOverloadTypeAtArg`

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 5 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp]: I've updated the change to preserve vectors when considered `isVectorIntrinsicWithScalarOpAtArg` just to be on the safe side.  The latest change returns the flow control in the loop to something closer to the original.

**Review by farzonl — APPROVED** [review]

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 6]
```diff
@@ -100,20 +100,39 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
 static bool replaceWithCallToVeclib(const TargetLibraryInfo &TLI,
                                     IntrinsicInst *II) {
   assert(II != nullptr && "Intrinsic cannot be null");
-  // At the moment VFABI assumes the return type is always widened unless it is
```
Comment (mgabka) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:103]: this comment was useful as it explains the why EC is computed in such a way please do not delete it

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 7]
```diff
@@ -100,20 +100,39 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
...
+  bool RetIsScalar = isVectorIntrinsicWithScalarOpAtArg(IID, -1);
+  Type *RetTy = II->getType();
+  Type *ScalarRetTy = RetTy->getScalarType();
+
   // Compute the argument types of the corresponding scalar call and check that
   // all vector operands match the previously found EC.
   SmallVector<Type *, 8> ScalarArgTypes;
-  Intrinsic::ID IID = II->getIntrinsicID();
+  auto *VTy = dyn_cast<VectorType>(RetTy);
+  ElementCount EC(!RetIsScalar && VTy ? VTy->getElementCount()
```
Comment (mgabka) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:116]: the extra !RetIsScalar is not needed, if the return type is vector then isVectorIntrinsicWithScalarOpAtArg(IID, -1) return false, the original place where EC was computed was correct, could you please revert this change?

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 8]
```diff
@@ -100,20 +100,39 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
...
-  // At the moment VFABI assumes the return type is always widened unless it is
-  // a void type.
-  auto *VTy = dyn_cast<VectorType>(II->getType());
-  ElementCount EC(VTy ? VTy->getElementCount() : ElementCount::getFixed(0));
+  Intrinsic::ID IID = II->getIntrinsicID();
+  if (IID == Intrinsic::not_intrinsic)
+    return false;
+
+  // RetIsScalar: Return type is not widened.
+  bool RetIsScalar = isVectorIntrinsicWithScalarOpAtArg(IID, -1);
```
Comment (mgabka) [inline llvm/lib/CodeGen/ReplaceWithVeclib.cpp:108]: I believe that VFABI does not allow such cases so in my opinion such cases should not be handled,  but simply rejected, at the very beginning of this function.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp [hunk 9]
```diff
@@ -100,20 +100,39 @@ static void replaceWithTLIFunction(IntrinsicInst *II, VFInfo &Info,
 static bool replaceWithCallToVeclib(const TargetLibraryInfo &TLI,
                                     IntrinsicInst *II) {
   assert(II != nullptr && "Intrinsic cannot be null");
-  // At the moment VFABI assumes the return type is always widened unless it is
-  // a void type.
-  auto *VTy = dyn_cast<VectorType>(II->getType());
-  ElementCount EC(VTy ? VTy->getElementCount() : ElementCount::getFixed(0));
+  Intrinsic::ID IID = II->getIntrinsicID();
+  if (IID == Intrinsic::not_intrinsic)
+    return false;
```
[the remark this answers is not in the document]
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:105]: It only calls this for IntrinsicInst, but some of those have `getIntrinsicID() == Intrinsic::not_intrinsic`.  This caused the assert to fire in `isVectorIntrinsicWithOverloadTypeAtArg`.  Some hits were in an AMDGPU nop intrinsic, but there were others as well.  I'm afraid I don't still have the list of tests on hand that asserted without this.

Before this check, we would have exited a little later, usually when an argument returned false from `isVectorIntrinsicWithScalarOpAtArg` and also wasn't a vector type.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 6 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:103]: I made the change to rely on using `isVectorIntrinsicWithScalarOpAtArg` as well because it seemed like the right thing to do.  If it ever returned true for the return index `-1`, that would contradict the comment.

However, since I see other paths do not use this for the return and this doesn't return true for index `-1` for any intrinsic, I can change this part back, since it would likely require other code changes if this assumption were to ever change.

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (mgabka) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp:105]: Ah I see, the casting method uses  just  ```bool isIntrinsic() const``` which only checks if the name starts with the llvm. and is not checking if there is intrinsic ID, while there seems to be tests using llvm. functions which aren't intrinsics.

That is a but in the top level function in this pass, could you move this extra check to runImpl function so we have all the filtering in one place?

[the remark this answers is not in the document]
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp]: Updated.

**Comment by tex3d** [comment]
Note: buildkite failure is an ongoing unrelated failure with:
```
RuntimeError: __cxx03/__algorithm/adjacent_find.h: Header cxx03 is not a valid header
```

File: llvm/lib/CodeGen/ReplaceWithVeclib.cpp (hunk 1 above)
Comment (tex3d) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp]: There are three tests impacted by this change.  If you think there's a specific deficiency at this point not addressed by existing testing, please let me know.  For now, I'll be resolving this comment.  Please re-activate if you think it still needs addressing.

Comment (mgabka) [reply llvm/lib/CodeGen/ReplaceWithVeclib.cpp]: ah, there is one unit tests using "powi", which is overloaded on a scalar type.
For now we do not have mappings for it in the TLI, so there is no lit tests for it.


The regular pow is not affecting this code path as is only overloaded only on return type.

**Review by mgabka — APPROVED** [review]
