### PR TITLE
Fix -fno-unsafe-math-optimizations behavior

### LINKED ISSUE #87523: -fno-unsafe-math-optimizations enables constrained intrinsics
I expected -fno-unsafe-math-optimizations would be the default behavior and only undo -funsafe-math-optimizations. Instead it enables constrained intrinsics. https://godbolt.org/z/ooYdY4Kox

I checked with @andykaylor who thought this behavior might be because gcc documentation says -fno-unsafe-math-optimizations implies -ftrapping-math. gcc has -ftrapping-math by default, but clang does not.

### PR DESCRIPTION
**Pull request by andykaylor**
This changes the handling of -fno-unsafe-fp-math to stop having that
option imply -ftrapping-math. In gcc, -fno-unsafe-math-optimizations sets
-ftrapping-math, but that dependency is based on the fact the
-ftrapping-math is enabled by default in gcc. Because clang does not
enable -ftrapping-math by default, there is no reason for
-fno-unsafe-math-optimizations to set it.

On the other hand, -funsafe-math-optimizations continues to imply
-fno-trapping-math because this option necessarily disables strict
exception semantics.

This fixes https://github.com/llvm/llvm-project/issues/87523

### CODE REVIEW

File: clang/test/Driver/fast-math.c [hunk 1]
```diff
@@ -271,30 +271,32 @@
...
 // RUN:   | FileCheck --check-prefix=CHECK-NO-UNSAFE-MATH %s
 // RUN: %clang -### -ffast-math -ftrapping-math -c %s 2>&1 \
-// RUN:   | FileCheck --check-prefix=CHECK-NO-UNSAFE-MATH %s
+// RUN:   | FileCheck --check-prefix=CHECK-TRAPPING-NO-UNSAFE-MATH %s
 // RUN: %clang -### -ffast-math -fno-unsafe-math-optimizations -c %s 2>&1 \
 // RUN:   | FileCheck --check-prefix=CHECK-NO-UNSAFE-MATH %s
 
 // CHECK-NO-UNSAFE-MATH: "-cc1"
 // CHECK-NO-UNSAFE-MATH-NOT: "-funsafe-math-optimizations"
-// CHECK-NO_UNSAFE-MATH-NOT: "-mreassociate"
```
Comment (arsenm) [inline clang/test/Driver/fast-math.c:296]: So this test was full of broken test checks?

File: clang/test/Driver/fast-math.c [hunk 2]
```diff
@@ -318,12 +320,12 @@
...
-// RUN:   | FileCheck --check-prefix=CHECK-NO-REASSOC-NO-UNSAFE-MATH %s
+// RUN:   | FileCheck --check-prefix=CHECK-NO-UNSAFE-MATH %s
 
 // CHECK-NO-REASSOC-NO-UNSAFE-MATH: "-cc1"
-// CHECK-NO-REASSOC-NO_UNSAFE-MATH-NOT: "-funsafe-math-optimizations"
-// CHECK-NO-REASSOC-NO_UNSAFE-MATH-NOT: "-mreassociate"
-// CHECK-NO-REASSOC-NO_UNSAFE-MATH-NOT: "-funsafe-math-optimizations"
+// CHECK-NO-REASSOC-NO-UNSAFE-MATH-NOT: "-funsafe-math-optimizations"
+// CHECK-NO-REASSOC-NO-UNSAFE-MATH-NOT: "-mreassociate"
+// CHECK-NO-REASSOC-NO-UNSAFE-MATH-NOT: "-funsafe-math-optimizations"
```
Comment (arsenm) [inline clang/test/Driver/fast-math.c:328]: I don't think this testing technique works. All of these flags would be printed on the same line as cc1. You would need to use CHECK-SAME-NOT, but I'm not sure you can actually compose -SAME and -NOT checks 

-NOT checks are hazardous this way, can we positively check for the flags that are emitted.

Comment (andykaylor) [reply clang/test/Driver/fast-math.c:328]: I'd be happy to make that change. I was a little lazy with this test. I just wanted something that tested the change I was making, and then the rest of what I did was just what seemed necessary to make the test pass while still testing the things it meant to test. The whole thing seemed a bit of a mess. I can clean it up some with a bit more effort.

Comment (zahiraam) [reply clang/test/Driver/fast-math.c:333]: Yes, I think that should work!

File: clang/test/Driver/fast-math.c (hunk 1 above)
Comment (zahiraam) [reply clang/test/Driver/fast-math.c:296]: It looks like the lines with `_` were just ignored! That's bad.

**Comment by andykaylor** [comment]
I've made some minor changes to clean up the LIT test checks for this PR. I started to clean up the entire test, but it quickly became obvious that I should put that into a separate PR.

I will submit a new PR to clean up the entire fast-math.c test. I have an idea that I think will work, hard-coding the order of the math-related flags and using a separate prefix for each one plus negative checks. Then the test can just use "--check-prefixes=..." to put together the combinations that are expected. I think that will be more maintainable and more readable than trying to group checks in the more-or-less arbitrary way the test currently does.

**Comment by andykaylor** [comment]
I've made extensive changes to the fast-math.c test here: https://github.com/llvm/llvm-project/pull/89687

That update isn't intended to change any existing behavior. A few things worked differently than I expected, but I left the checks consistent with the current behavior and added comments where I thought the current behavior was incorrect.

**Comment by andykaylor** [comment]
ping for review

**Comment by zahiraam** [comment]
LGTM! Thanks.

**Review by jcranmer-intel — APPROVED** [review]
