### PR TITLE
[LLDB][NativePDB] Use undecorated name for types if UniqueName isn't mangled

### LINKED ISSUE #152051: [LLDB] [Native PDB] Wrong name is used for Rust types
Mentioned [here](https://github.com/llvm/llvm-project/issues/114906#issuecomment-3151067271), the Native parser appears to be using a unique ID field instead of the name field for Rust types. Example:

Native:

Image

Dia:

Image

### PR DESCRIPTION
**Pull request by Nerixyz**
Languages other than C/C++ don't necessarily emit mangled names in the  `UniqueName` field of type records. Rust specifically emits a unique ID that doesn't contain the name.

For example, `(i32, i32)` is emitted as

```llvm
!266 = !DICompositeType(
  tag: DW_TAG_structure_type, name: "tuple$<i32,i32>", file: !9, size: 64, align: 32,
  elements: !267, templateParams: !17, identifier: "19122721b0632fe96c0dd37477674472"
)
```

which results in

```
  0x1091 | LF_STRUCTURE [size = 72, hash = 0x1AC67] `tuple$<i32,i32>`
           unique name: `19122721b0632fe96c0dd37477674472`
           vtable: <no type>, base list: <no type>, field list: 0x1090
           options: has unique name, sizeof 8
```

In C++ with Clang and MSVC, a structure similar to this would result in
```
   0x136F | LF_STRUCTURE [size = 44, hash = 0x30BE2] `MyTuple`
            unique name: `.?AUMyTuple@@`
            vtable: <no type>, base list: <no type>, field list: 0x136E
            options: has unique name, sizeof 8
```

With this PR, if a `UniqueName` is encountered that couldn't be parsed, it will fall back to using the undecorated (→ do the same as if the unique name is empty/unavailable).

I'm not sure how to test this. Maybe compiling the LLVM IR that rustc emits?

Fixes #152051.

### CODE REVIEW

File: lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp [hunk 1]
```diff
@@ -618,18 +618,14 @@ lldb::TypeSP SymbolFileNativePDB::CreateSimpleType(TypeIndex ti,
...
 
 static std::string GetUnqualifiedTypeName(const TagRecord &record) {
-  if (!record.hasUniqueName()) {
-    MSVCUndecoratedNameParser parser(record.Name);
-    llvm::ArrayRef<MSVCUndecoratedNameSpecifier> specs = parser.GetSpecifiers();
-
-    return std::string(specs.back().GetBaseName());
-  }
+  if (!record.hasUniqueName())
+    return std::string(MSVCUndecoratedNameParser::DropScope(record.Name));
```
Comment (Michael137) [inline lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp:622]: Was this change required? Or a drive-by cleanup?

**Review by Michael137 — COMMENTED** [review]
Seems reasonable to me. I'd let @ZequanWu or @Walnut356 take a look too

File: lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp (hunk 1 above)
Comment (Nerixyz) [reply lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp:622]: No, this isn't required. This was basically the implementation of [`DropScope`](https://github.com/llvm/llvm-project/blob/d4f51bd53ed583cb4c8b149d5e3d31ac5f64d82a/lldb/source/Plugins/Language/CPlusPlus/MSVCUndecoratedNameParser.cpp#L99-L104) before. I changed it for clarity - to be identical with the other case.

**Comment by ZequanWu** [comment]
Can you add a test for this if it's not hard to create one?

**Comment by Nerixyz** [comment]
> Can you add a test for this if it's not hard to create one?

Found a way to make the IR a bit smaller by compiling an rlib with a `main()`.

**Review by ZequanWu — APPROVED** [review]
