### PR TITLE
[OpenMP] Fix infinite loop on recursive initializers

### LINKED ISSUE #69194: clang: 18: hangs on a simple syntax error
Compiler Explorer: https://gcc.godbolt.org/z/7c9dKMGcW

When compile this program with option `-O0 -fopenmp-simd`, Clang hangs:
```cpp
static int a;
#pragma omp declare target
b = b ^ 3 + a;
```

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
If the user tried to initialize a gobal declare target variable with
itself the compiler will hang forever. Add a visited set to make sure
this stops.

Fixes: https://github.com/llvm/llvm-project/issues/69194

### CODE REVIEW

File: clang/lib/Sema/SemaOpenMP.cpp [hunk 1]
```diff
@@ -22819,8 +22819,12 @@ class GlobalDeclRefChecker final : public StmtVisitor<GlobalDeclRefChecker> {
   void declareTargetInitializer(Decl *TD) {
     A = TD->getAttr<OMPDeclareTargetDeclAttr>();
     DeclVector.push_back(cast<VarDecl>(TD));
+    llvm::DenseSet<Decl *> Visited;
     while (!DeclVector.empty()) {
       VarDecl *TargetVarDecl = DeclVector.pop_back_val();
```
Comment (shiltian) [inline clang/lib/Sema/SemaOpenMP.cpp:22824]: Doesn't `pop_back_val` already remove the element from `DeclVector`, which means `DeclVector` will eventually go empty?

Comment (jhuber6) [reply clang/lib/Sema/SemaOpenMP.cpp:22824]: It gets added back in `Visit`.

**Comment by shiltian** [comment]
The fix looks reasonable to me. @alexey-bataev WDYT?

File: clang/lib/Sema/SemaOpenMP.cpp [hunk 2]
```diff
@@ -22819,8 +22819,12 @@ class GlobalDeclRefChecker final : public StmtVisitor<GlobalDeclRefChecker> {
   void declareTargetInitializer(Decl *TD) {
     A = TD->getAttr<OMPDeclareTargetDeclAttr>();
     DeclVector.push_back(cast<VarDecl>(TD));
+    llvm::DenseSet<Decl *> Visited;
```
Comment (alexey-bataev) [inline clang/lib/Sema/SemaOpenMP.cpp:22822]: Better to use SmallDenseSet

**Review by alexey-bataev — APPROVED** [review]
LG with a nit

**Comment by jhuber6** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/605a9e37b64b5b5647f1f3e560f7ffe31157841c
