### PR TITLE
[clang-tidy] Fix handling of functional cast in google-readability-casting

### LINKED ISSUE #57959: clang-tidy [google-readability-casting] module warning about c-style cast in throw statement
I have a small test case here which illustrates the problem I've been having

```cpp
#include <stdexcept>

uint64_t bar(int a1, ...);

template <typename T>
int64_t foo(T val)
{
  const int64_t status = bar(0, val);
  if (status != 0) {
    throw std::runtime_error(std::to_string(status));
  }

  return status;
}
```

When I run clang-tidy on it eg `clang-tidy -checks=google-readability-casting tidy_test.cpp` I get
```console
warning: C-style casts are discouraged; use static_cast/const_cast/reinterpret_cast [google-readability-casting]
    throw std::runtime_error(std::to_string(status));
          ^
Suppressed 11 warnings (11 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

I don't see this issue with clang-tidy 12, but I saw it starting version 14.0.0, and also confirmed on a few other versions including 14.0.6, 15.0.1, and trunk (using godbolt).

### PR DESCRIPTION
**Pull request by PiotrZSL**
Fix issue with constructor call being interpreted as functional cast and considered for a replacement
with static cast or being removed as redundant.

Closes #57959

### CODE REVIEW

File: clang-tools-extra/clang-tidy/google/AvoidCStyleCastsCheck.cpp [hunk 1]
```diff
@@ -18,19 +18,22 @@ namespace clang::tidy::google::readability {
 
 void AvoidCStyleCastsCheck::registerMatchers(
     ast_matchers::MatchFinder *Finder) {
+
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/google/AvoidCStyleCastsCheck.cpp:21]: Intended newline?

**Review by 5chmidti — APPROVED** [review]
LGTM
