### PR TITLE
[MLIR][OpenMP] Fix type mismatch in linear clause for INTEGER(8) variables

### LINKED ISSUE #173332: [flang][OpenMP] fails to compile OpenMP parallel do simd with linear clause on INTEGER(8) variable
Reproducer:
https://godbolt.org/z/Th44q4cK9
```f90
integer(8) :: i, j

!$omp parallel do simd linear(j)
do i = 1,100,1
end do
!$omp end parallel do simd

end
```

With assertion-enabled flang, compiling the above reproducer hits the following assertion failure:
```txt
llvm-project/llvm/lib/IR/Instructions.cpp:2706: static llvm::BinaryOperator *llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value *, llvm::Value *, const llvm::Twine &, llvm::InsertPosition): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.
```

### PR DESCRIPTION
**Pull request by KrxGu**
Fixes #173332 

The compiler was crashing when compiling OpenMP `parallel do simd` with a `linear` clause on `INTEGER(8)` variables. The assertion failure occurred during MLIR-to-LLVM translation:
Cannot create binary operator with two operands of differing type!

**Root Cause:**
The bug was in `LinearClauseProcessor::updateLinearVar()` where the step value (i32) and induction variable were multiplied without normalizing to the linear variable's type (i64), causing type mismatches in LLVM IR generation.

**Solution:**
Updated the translation logic to cast both the induction variable and step value to `linearVarTypes[index]` before performing arithmetic operations. This ensures type consistency for both integer and floating-point linear variables.

**Testing:**
- Added integration test verifying successful compilation to LLVM IR
- Added lowering test for MLIR generation with various linear clause forms
- Verified the exact reproducer from the issue now compiles without errors

### CODE REVIEW

**Comment by KrxGu** [comment]
@k-arrows this PR is ready for review.

CI is all green, Good To Merge!!

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 1]
```diff
@@ -187,17 +187,45 @@ class LinearClauseProcessor {
...
-      llvm::LoadInst *linearVarStart = builder.CreateLoad(
-          linearVarTypes[index], linearPreconditionVars[index]);
-      auto mulInst = builder.CreateMul(loopInductionVar, linearSteps[index]);
-      if (linearVarTypes[index]->isIntegerTy()) {
-        auto addInst = builder.CreateAdd(linearVarStart, mulInst);
+      llvm::Type *linearVarType = linearVarTypes[index];
+      llvm::Value *iv = loopInductionVar;
+      llvm::Value *step = linearSteps[index];
+
+      // Helper to cast signed integers with sign extension or truncation
```
[the remark this answers is not in the document]
Comment (KrxGu) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]: Gotcha!

**Comment by KrxGu** [comment]
@kparzysz i have addressed all the reviews. 

CI is all green, Good To Merge!!
Happy New year!!

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 2]
```diff
@@ -187,17 +187,37 @@ class LinearClauseProcessor {
...
+      llvm::Value *iv = loopInductionVar;
+      llvm::Value *step = linearSteps[index];
+
+      if (!iv->getType()->isIntegerTy())
+        llvm_unreachable("OpenMP loop induction variable must be an integer "
+                         "type");
+
+      if (linearVarType->isIntegerTy()) {
+        // Integer path: normalize all arithmetic to linearVarType
+        iv = builder.CreateSExtOrTrunc(iv, linearVarType);
```
Comment (NimishMishra) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]: Would a single `step = builder.CreateSExtOrTrunc(step, iv->getType());` not work here, like the Float path below?

File: flang/test/Lower/OpenMP/parallel-do-simd-linear-i8.f90 [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+! Test with multiple INTEGER(8) linear variables
+! CHECK-LABEL: func.func @_QPtest_multiple_i8
+subroutine test_multiple_i8
+    implicit none
+    integer(8) :: i, j, k
+    
+    ! CHECK-DAG: %[[J:.*]]:2 = hlfir.declare {{.*}} {uniq_name = "_QFtest_multiple_i8Ej"}
+    ! CHECK-DAG: %[[K:.*]]:2 = hlfir.declare {{.*}} {uniq_name = "_QFtest_multiple_i8Ek"}
+    ! CHECK-DAG: %[[STEP:.*]] = arith.constant 1 : i32
+    ! CHECK: omp.simd linear(%[[J]]#0 = %[[STEP]] : !fir.ref<i64>, %[[K]]#0 = %[[STEP]] : !fir.ref<i64>)
```
Comment (NimishMishra) [inline flang/test/Lower/OpenMP/parallel-do-simd-linear-i8.f90]: Is there something specific you are checking during FIR lowering? Since the truncation / sign-ext is happening during translation of the MLIR op, it is best to have MLIR tests. I think we can do away with this test explicitly.

**Review by NimishMishra — COMMENTED** [review]
Thanks for the fix. A couple of comments.

**Review by tblah — COMMENTED** [review]
Thanks for the bug fix!

**Review by NimishMishra — COMMENTED** [review]
Thanks for the changes. It looks okay to me. Just one request: is it also possible to add a test for the float path too? Just to check the `else` part too.

**Review by NimishMishra — APPROVED** [review]
LGTM, thanks. Please wait for a few days for others to take a look. But please do land this before LLVM 22 branches.
