### PR TITLE
[AMDGPU] Fix register class constraints for si-fold-operands pass when folding immediate into copies

### LINKED ISSUE #130020: AMDGPU pass does not respect register class constraint when folding immediate into copies
```
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -run-pass=si-fold-operands -verify-machineinstrs -o - %s

# av_class constraint is not respected, and copy is replaced with an illegal v_mov_b32

---
name: s_mov_b32_imm_literal_copy_s_to_av_32
tracksRegLiveness: true
body:             |
  bb.0:
    %0:sreg_32 = S_MOV_B32 999
    %1:av_32 = COPY %0
    $agpr0 = COPY %1
    S_ENDPGM 0
...

---
name: v_mov_b32_imm_literal_copy_v_to_av_32
tracksRegLiveness: true
body:             |
  bb.0:
    %0:vgpr_32 = V_MOV_B32_e32 999, implicit $exec
    %1:av_32 = COPY %0
    $agpr0 = COPY %1
    S_ENDPGM 0

...

```

This hits a machine verifier failure:
```
Append normal operand 1
  %1:av_32 = V_MOV_B32_e32 %0:vgpr_32
Folded source from %0:vgpr_32 = V_MOV_B32_e32 999, implicit $exec
 into OpNo 1 of %1:av_32 = V_MOV_B32_e32 999, implicit $exec

# After SI Fold Operands
# Machine code for function v_mov_b32_imm_literal_copy_v_to_av_32: IsSSA, NoPHIs, TracksLiveness

bb.0:
  %1:av_32 = V_MOV_B32_e32 999, implicit $exec
  $agpr0 = COPY %1:av_32
  S_ENDPGM 0

# End machine code for function v_mov_b32_imm_literal_copy_v_to_av_32.

*** Bad machine code: Illegal virtual register for instruction ***
- function:    v_mov_b32_imm_literal_copy_v_to_av_32
- basic block: %bb.0  (0x13b009928)
- instruction: %1:av_32 = V_MOV_B32_e32 999, implicit $exec
- operand 0:   %1:av_32
Expected a VGPR_32 register, but got a AV_32 register

```

It is not possible to directly write a literal value to an AGPR, so it is not legal to fold these

### PR DESCRIPTION
**Pull request by mssefat**
Fixes https://github.com/llvm/llvm-project/issues/130020

This fixes an issue where the si-fold-operands pass would incorrectly fold immediate values into COPY instructions targeting av_32 registers.

The pass now checks register class constraints before attempting to fold the immediate.

### CODE REVIEW

**Comment by mssefat** [comment]
@arsenm could you please review?

**Comment by arsenm** [comment]
The tests for the issue are already in llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir (and you should also mention this fixes issue number in the description)

**Comment by mssefat** [comment]
@arsenm I updated accordingly. Please check.

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp [hunk 1]
```diff
@@ -1047,6 +1047,11 @@ void SIFoldOperandsImpl::foldOperand(
     if (MovOp == AMDGPU::COPY)
       return;
 
+    // Check if the destination register of the MOV operation belongs
+    // to a vector superclass. Folding would be illegal.
+    if (TRI->isVectorSuperClass(DestRC))
+      return;
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1053]: Would be better to query the register class of the result register, and check if there is a common class between it and the virtual register class. In the future it would be better to replace the instruction and modify the register class to enable folds in some cases

Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1053]: Thanks for your suggestion. Based on your comment, I've implemented the check. The snippet looks like following:

```
    // Check if the destination register class has a common class
    // with the expected register class for the MOV instruction.
    const MCInstrDesc &MovDesc = TII->get(MovOp);
    if (MovDesc.operands()[0].RegClass != -1) {
      const TargetRegisterClass *ResRC = 
          TRI->getRegClass(MovDesc.operands()[0].RegClass);
      const TargetRegisterClass *CommonRC = 
          TRI->getCommonSubClass(DestRC, ResRC);

      if (!CommonRC) {
        return;
      }
    }
```

Can you please confirm if this aligns correctly with your suggestion or further adjustments are needed?

File: llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir [hunk 2]
```diff
@@ -185,52 +185,49 @@ body:             |
...
-# body:             |
-#   bb.0:
-#     %0:vgpr_32 = V_MOV_B32_e32 999, implicit $exec
-#     %1:av_32 = COPY %0
-#     $agpr0 = COPY %1
-#     S_ENDPGM 0
-
-# ...
+---
+name: s_mov_b32_inlineimm_copy_s_to_av_32
```
[the remark this answers is not in the document]
Comment (mssefat) [reply llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir:132]: I have pushed the updated changes. Could you please review?

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp (hunk 1 above)
Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp]: I have pushed the updated changes. Could you please review?

Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp]: Ping

File: llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir (hunk 2 above)
[the remark this answers is not in the document]
Comment (mssefat) [reply llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir:132]: Ping

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp [hunk 3]
```diff
@@ -1047,6 +1047,16 @@ void SIFoldOperandsImpl::foldOperand(
...
       return;
 
+    // Fold if the destination register class of the MOV instruction (ResRC)
+    // is a superclass of (or equal to) the destination register class of the COPY (DestRC).
+    // If this condition fails, folding would be illegal.
+    const MCInstrDesc &MovDesc = TII->get(MovOp);
+    if (MovDesc.getNumDefs() > 0 && MovDesc.operands()[0].RegClass != -1) {
+      const TargetRegisterClass *ResRC = 
+          TRI->getRegClass(MovDesc.operands()[0].RegClass);
+      if (!DestRC -> hasSuperClassEq(ResRC)) return;
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1057]: No space around `->`. Body of `if` on separate line.
```suggestion
      if (!DestRC->hasSuperClassEq(ResRC))
        return;
```

File: llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir [hunk 4]
```diff
@@ -1,14 +1,23 @@
-# RUN: llc -mtriple=amdgcn -run-pass si-fold-operands -verify-machineinstrs %s -o - | FileCheck -check-prefix=GCN %s
-
-# GCN-LABEL:       name: fold-imm-copy
-# GCN:             V_AND_B32_e32 65535
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
```
Comment (jayfoad) [inline llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir:1]: Please make a separate PR for this and commit it first. Then rebase the current PR.

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp (hunk 3 above)
Comment (arsenm) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1057]: Can you use getCommonSubClass or getMatchingSuperRegClass instead of directly checking hasSuperClassEq

File: llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir (hunk 4 above)
Comment (mssefat) [reply llvm/test/CodeGen/AMDGPU/fold-imm-copy.mir]: Done and I have pushed the updated changes. Could you please review?

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp (hunk 3 above)
Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp]: I have pushed the updated changes. Could you please review?

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp [hunk 5]
```diff
@@ -1047,6 +1047,16 @@ void SIFoldOperandsImpl::foldOperand(
     if (MovOp == AMDGPU::COPY)
       return;
 
+    // Fold if the destination register class of the MOV instruction (ResRC)
+    // is a superclass of (or equal to) the destination register class of the COPY (DestRC).
+    // If this condition fails, folding would be illegal.
+    const MCInstrDesc &MovDesc = TII->get(MovOp);
+    if (MovDesc.getNumDefs() > 0 && MovDesc.operands()[0].RegClass != -1) {
```
[the remark this answers is not in the document]
Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp]: Done, can you please review?

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp [hunk 6]
```diff
@@ -1068,6 +1068,20 @@ void SIFoldOperandsImpl::foldOperand(
...
+
+    const MCInstrDesc &MovDesc = TII->get(MovOp);
+    assert(MovDesc.getNumDefs() > 0 && MovDesc.operands()[0].RegClass != -1);
+    const TargetRegisterClass *ResRC =
+        TRI->getRegClass(MovDesc.operands()[0].RegClass);
+    const TargetRegisterClass *CommonRC = TRI->getCommonSubClass(DestRC, ResRC);
+
+    if (!CommonRC || !DestRC->hasSuperClassEq(CommonRC))
+      return;
+
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1084]:
```suggestion
    if (!CommonRC)
      return;

```

hasSuperClassEq should be redundant with finding the common class

Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1084]: I think hasSuperClassEq is not redundant with finding common subclass. Consider this basic block where the copy operation is illegal:

bb.0:
  %1:av_32 = V_MOV_B32_e32 32, implicit $exec
  $agpr0 = COPY %1:av_32
  S_ENDPGM 0

In this example:

DestRC is AV_32
ResRC is VGPR_32
CommonRC is VGPR_32

If we only check for CommonRC, the check would allow folding in this case since CommonRC exists (VGPR_32). However, folding here is illegal. And I think we need the condition if ( !DestRC->hasSuperClassEq(CommonRC) return.

**Comment by mssefat** [comment]
@arsenm @jayfoad Ping

File: llvm/lib/Target/AMDGPU/SIFoldOperands.cpp (hunk 6 above)
Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1084]: Why do you need CommonRC? Isn't the whole check equivalent to `DestRC->hasSuperClassEq(ResRC)`?

Comment (jayfoad) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp:1084]: The code as you have written it is weird, because CommonRC is by construction a subclass of DestRC, and then you are checking that it is a superclass of DestRC. These can only both be true if CommonRC *is* DestRC.

Comment (mssefat) [reply llvm/lib/Target/AMDGPU/SIFoldOperands.cpp]: They should be equivalent check. I am reverting to the previous use of DestRC->hasSuperClassEq(ResRC). @arsenm please let me know if I am missing something.

**Review by arsenm — APPROVED** [review]
