### PR TITLE
[Clang] Fix a partial ordering bug involving CTAD injected template arguments

### LINKED ISSUE #134613: Clang 20 implicit CTAD regression?
```C++
#include <type_traits>

template<typename R>
struct Foo
{
	using value_type = R ;

	Foo() = default;
    Foo(const Foo&) = delete;
    Foo(Foo&&) = delete;

	Foo(Foo<Foo<R>>&& rhs)
	{
	}
};

/*template<typename R>
Foo(Foo<Foo<R>>&&) -> Foo<R>;*/

int main()
{
	auto r1 = Foo(Foo<Foo<int>>{});
	static_assert(std::is_same_v<decltype(r1)::value_type, int>);
}
```

Compiles with Clang 19.1.0 but fails the static_assert with Clang 20.1.0: https://godbolt.org/z/daqjan7e5
Uncommenting the explicit deduction guide seems to work around the issue.

### PR DESCRIPTION
**Pull request by zyn0217**
The synthesized deduction guides use injected template arguments for distinguishment of explicit and implicit deduction guides.

In partial ordering, we may substitute into these injected types when checking consistency. Properly substituting them needs the instantiated class template specializations which isn't the case at that point. So instead, we check their template specialization types.

No release note because I think we want a backport, after baking it for a couple of days.

Fixes https://github.com/llvm/llvm-project/issues/134613

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]

File: clang/lib/Sema/SemaTemplateDeduction.cpp [hunk 1]
```diff
@@ -5525,6 +5525,8 @@ static TemplateDeductionResult CheckDeductionConsistency(
   // FIXME: A substitution can be incomplete on a non-structural part of the
   // type. Use the canonical type for now, until the TemplateInstantiator can
   // deal with that.
+  if (auto *Injected = P->getAs<InjectedClassNameType>())
+    P = Injected->getInjectedSpecializationType();
```
Comment (mizvekov) [inline clang/lib/Sema/SemaTemplateDeduction.cpp:5529]: It's not immediately clear to me these injected class template types only appear at the top level type of the parameters, that they can't appear nested within, and there is no explanation for that.

If we can't fix this at the deduction guide level, I think the next best thing would be to make sure the substitution here produces the right injected vs non-injected type to match the other side, by manipulating the current context.

**Review by mizvekov — APPROVED** [review]
LGTM, thanks!

**Review by shafik — COMMENTED** [review]
Are you planning to backport? Otherwise then it should have a release note.

**Comment by mizvekov** [comment]
Yeah, the PR description says so.
