### PR TITLE
[clang-tidy][modernize-use-using]fix function pointer typedef correctly

### LINKED ISSUE #65055: clang-tidy: `modernize-use-using` wrongly modifies typedef of function pointer
```shellsession
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 15.0.7
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

Prepare the following file, `/tmp/a.cpp`:
```cpp
typedef void (*v0123456789)(int);
typedef bool (*b)(int);
```
and `/tmp/compile_commands.json`:
```json
[
  {
    "directory": "/tmp",
    "command": "/usr/bin/clang++ -o a.o -c a.cpp",
    "file": "a.cpp",
    "output": "a.o"
  }
]
```

Then run `clang-tidy`:

```shellsession
$ clang-tidy --checks='-*,modernize-use-using' --fix a.cpp
2 warnings generated.
/tmp/a.cpp:1:1: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef void (*v0123456789)(int);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using v0123456789 = void (*)(int)
/tmp/a.cpp:1:1: note: FIX-IT applied suggested code changes
/tmp/a.cpp:2:9: warning: use 'using' instead of 'typedef' [modernize-use-using]
typedef bool (*b)(int);
        ^~~~~~~~~~~~~~
/tmp/a.cpp:2:9: note: FIX-IT applied suggested code changes
clang-tidy applied 2 of 2 suggested fixes.
```

Here, the message for the second line must be
```shellsession
typedef bool (*b)(int);
^~~~~~~~~~~~~~~~~~~~~~
using b = bool (*)(int)
```

The file is wrongly modified:
```cpp
using v0123456789 = void (*)(int);
typedef ;
using b = bool (*)(int);
```

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixed #65055
For normal type, typedef is from typedef to the end of original type, but for function pointer it is from typedef to the end.
So it needs to consider alias name length for normal type.

### CODE REVIEW

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp [hunk 1]
```diff
@@ -314,3 +314,10 @@ typedef struct { struct { int a; struct { struct { int b; } c; int d; } e; } f;
 typedef struct { struct { int a; } b; union { int c; float d; struct { int e; }; }; struct { double f; } g; } PR50990_siblings;
 // CHECK-MESSAGES: :[[@LINE-1]]:1: warning: use 'using' instead of 'typedef'
 // CHECK-FIXES: using PR50990_siblings = struct { struct { int a; } b; union { int c; float d; struct { int e; }; }; struct { double f; } g; };
+
+typedef void (*ISSUE_65055_1)(int);
+typedef bool (*ISSUE_65055_2)(int);
+// CHECK-MESSAGES: :[[@LINE-2]]:1: warning: use 'using' instead of 'typedef'
+// CHECK-MESSAGES: :[[@LINE-2]]:1: warning: use 'using' instead of 'typedef'
+// CHECK-FIXES: using ISSUE_65055_1 = void (*)(int)
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp:322]: put `;` at the end of CHECK-FIXES, just to verify that it wont be removed.

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp [hunk 2]
```diff
@@ -314,3 +314,10 @@ typedef struct { struct { int a; struct { struct { int b; } c; int d; } e; } f;
 typedef struct { struct { int a; } b; union { int c; float d; struct { int e; }; }; struct { double f; } g; } PR50990_siblings;
 // CHECK-MESSAGES: :[[@LINE-1]]:1: warning: use 'using' instead of 'typedef'
 // CHECK-FIXES: using PR50990_siblings = struct { struct { int a; } b; union { int c; float d; struct { int e; }; }; struct { double f; } g; };
+
+typedef void (*ISSUE_65055_1)(int);
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp:318]: Original issue were mainly with single character variable names, maybe test something like:
`typedef void (*C)(int);`

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -246,6 +246,9 @@ Changes in existing checks
   <clang-tidy/checks/modernize/use-std-print>` check to accurately generate
   fixes for reordering arguments.
 
+- Improved :doc:`modernize-use-using<clang-tidy/checks/modernize/use-using>`
```
Comment (PiotrZSL) [inline clang-tools-extra/docs/ReleaseNotes.rst:249]: put space before <, juts for visibility.

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp (hunk 2 above)
Comment (HerrCai0907) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp:318]: length of variable names is not related with this bugs.

Comment (PiotrZSL) [reply clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp:318]: ok

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp [hunk 4]
```diff
@@ -314,3 +314,10 @@ typedef struct { struct { int a; struct { struct { int b; } c; int d; } e; } f;
...
+typedef bool (*ISSUE_65055_2)(int);
+// CHECK-MESSAGES: :[[@LINE-2]]:1: warning: use 'using' instead of 'typedef'
+// CHECK-MESSAGES: :[[@LINE-2]]:1: warning: use 'using' instead of 'typedef'
+// CHECK-FIXES: using ISSUE_65055_1 = void (*)(int);
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-using.cpp:322]: use start character in CHECK_FIXES, otherwise this could also match case were typedef is not deleted.
`// CHECK-FIXES: {{^}}using ISSUE_65055_1 = void (*)(int);{{$}}`

**Review by PiotrZSL — APPROVED** [review]
LGTM,

This is weird issues because it always happen when two typedefs are one after other.
I would personally thing more that LastReplacementEnd is to big, not too small.
But if tests check this properly, then I'm fine with it.

**Comment by HerrCai0907** [comment]
> This is weird issues because it always happen when two typedefs are one after other.

```c++
typedef void (*ISSUE_65055_1)(int);
typedef bool (*ISSUE_65055_2)(int);
typedef void VOID;
```
The typedef matcher will match following position:

```
TypedefDecl 0x1610ba960 <ID/test.cpp:1:1, col:34> col:16 ISSUE_65055_1 'void (*)(int)'
TypedefDecl 0x1610bab30 <line:2:1, col:34> col:16 ISSUE_65055_2 'bool (*)(int)'
TypedefDecl 0x1610bab98 <line:3:1, col:14> col:14 VOID 'void'
```
That means typedef normal type is from `typedef` to the end of original type but for function pointer is from `typedef` to the end.
