### PR TITLE
[clang-tidy] Add options to throw unannotated functions in `bugprone-exception-escape`

### LINKED ISSUE #164795: [clang-tidy] add option to treat all unannotated functions as throwing in `bugprone-exception-escape`
Currently the `bugprone-exception-escape` check only reports findings when it actually sees an exception being thrown (hence some warnings only appearing with libc++ - see #152026 and #109587).

Adding an option which treats all functions not flagged as non-throwing as potentially throwing would mitigate that. That option could be made more granular as to differentiate between functions with known and unknown implementations.

An additional tunable along `FunctionsThatWillNotThrow` could also be added for helping with known non-throwing functions which are not annotated as such (as in legacy APIs).

It is possible that this needs to be spun into its own check.

### PR DESCRIPTION
**Pull request by zeyi2**
As of AI Usage: Gemini 3 was used for rephrasing the documentation.

Closes https://github.com/llvm/llvm-project/issues/164795

### CODE REVIEW

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h [hunk 1]
```diff
@@ -52,7 +52,7 @@ class ExceptionAnalyzer {
     using Throwables = llvm::SmallDenseMap<const Type *, ThrowInfo, 2>;
 
     static ExceptionInfo createUnknown() { return {State::Unknown}; }
-    static ExceptionInfo createNonThrowing() { return {State::Throwing}; }
+    static ExceptionInfo createNonThrowing() { return {State::NotThrowing}; }
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]: I understand there are valid reasons for this function to return `Throwing`, but it still feels a bit counter-intuitive for something named `createNonThrowing` to produce a `Throwing`.

If this change doesn't match your preference, I'm totally fine reverting it. Thanks in advance.

**Comment by zeyi2** [comment]
Sorry for the CI noise. I currently don't have power on for my laptop and have to rely on the CI for verification.

File: clang-tools-extra/docs/clang-tidy/checks/bugprone/exception-escape.rst [hunk 2]
```diff
@@ -71,3 +71,15 @@ Options
...
+
+   When `true`, treat calls to functions with visible definitions that are not
+   explicitly declared as non-throwing (i.e. lack ``noexcept`` or ``throw()``)
+   as potentially throwing, even if their bodies are visible and no explicit
+   throw is found. Default value is `false`.
+
+.. option:: UnknownAsThrowing
+
+   When `true`, treat calls to functions without visible definitions as
+   potentially throwing. Default value is `false`.
```
[the remark this answers is not in the document]
Comment (firewave) [reply clang-tools-extra/docs/clang-tidy/checks/bugprone/exception-escape.rst]: > That's a valid point, but it feels slightly divergent from the primary goal of this check, which focuses on preventing crashes/UB rather than enforcing noexcept usage for optimization or style. IMO this can be done with a seperate check (maybe under `modernize-`?)

I think that should rather go under `misc` as it changes the behavior as it does not modernize stuff per se (suggesting `noexcept` instead of `throw(false)` would be a modernization in my eyes). But it would be along the lines of suggesting `[[nodiscard]]` which is `modernize-`...

> I think it might be better to land the current Enum-based implementation first and consider a more granular split or a dedicated check in a future patch. WDYT?

Since it requires an opt-in by the user it should be fine. But it might change the behavior of the opt-in afterwards so it might make sense to at least lay out the path beforehand to avoid that.

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h [hunk 3]
```diff
@@ -124,12 +140,20 @@ class ExceptionAnalyzer {
     /// after filtering.
     bool ContainsUnknown;
 
+    bool UnknownFromMissingDefinition = false;
+    bool UnknownFromKnownUnannotated = false;
```
[the remark this answers is not in the document]
Comment (zeyi2) [reply clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]: Hi, I've "finished" the cleanup. But I'm not sure whether I understand you correctly. Could you take a look at the new implementaion when you have time?

**Comment by zeyi2** [comment]
friendly ping ;)

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h (hunk 1 above)
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]: Do you have in mind some tests that this change will affect?
AFAIK, none of the existing tests were corrected, so this piece of code is not covered..?

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.cpp [hunk 4]
```diff
@@ -483,10 +486,20 @@ ExceptionAnalyzer::ExceptionInfo ExceptionAnalyzer::throwsException(
     }
 
     CallStack.erase(Func);
+    // Optionally treat unannotated functions as potentially throwing if they
+    // are not explicitly non-throwing and no throw was discovered.
+    if (AssumeUnannotatedThrowing &&
+        Result.getBehaviour() == State::NotThrowing && canThrow(Func)) {
+      Result.registerUnknownException();
+      return Result;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.cpp]: Useless return? We will anyway return on the next line

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.cpp [hunk 5]
```diff
@@ -483,10 +486,20 @@ ExceptionAnalyzer::ExceptionInfo ExceptionAnalyzer::throwsException(
...
+    }
     return Result;
   }
 
   auto Result = ExceptionInfo::createUnknown();
+  if (MissingDefinitionsAreThrowing)
+    Result.registerUnknownException();
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.cpp]: I think we should only registern Unknown exception at the end if none were inserted in loop `for (const QualType &Ex : FPT->exceptions()) {`
because in func-proto we may find exceptions so this part will effectively do nothing.

I guess logically it should be in the end if nothing else found exceptions

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h [hunk 6]
```diff
@@ -154,6 +175,8 @@ class ExceptionAnalyzer {
   bool IgnoreBadAlloc = true;
   llvm::StringSet<> IgnoredExceptions;
   llvm::DenseMap<const FunctionDecl *, ExceptionInfo> FunctionCache{32U};
+  bool AssumeUnannotatedThrowing = false;
+  bool MissingDefinitionsAreThrowing = false;
```
Comment (vbvictor) [inline clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]:
```suggestion
  bool AssumeMissingDefinitionsFunctionsAsThrowing = false;
```

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h [hunk 7]
```diff
@@ -154,6 +175,8 @@ class ExceptionAnalyzer {
   bool IgnoreBadAlloc = true;
   llvm::StringSet<> IgnoredExceptions;
   llvm::DenseMap<const FunctionDecl *, ExceptionInfo> FunctionCache{32U};
+  bool AssumeUnannotatedThrowing = false;
```
[the remark this answers is not in the document]
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]: wdyt?

File: clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h (hunk 1 above)
Comment (zeyi2) [reply clang-tools-extra/clang-tidy/utils/ExceptionAnalyzer.h]: If I remember correctly, the reason why tests passed with the initial incorrect `createNonThrowing` (returning Throwing) is due to `analyzeDispatch` calling `filterIgnoredExceptions`, which in turn calls `reevaluateBehaviour`. Since the exception set was empty, `reevaluateBehaviour` correctly reset the state to `NotThrowing`, masking the initial bug.

**Review by vbvictor — APPROVED** [review]
LGTM with some potential readablity improvements

File: clang-tools-extra/clang-tidy/bugprone/ExceptionEscapeCheck.cpp [hunk 8]
```diff
@@ -111,6 +150,9 @@ void ExceptionEscapeCheck::check(const MatchFinder::MatchResult &Result) {
                                    "%0 which should not throw exceptions")
       << MatchedDecl;
 
+  if (Info.getExceptions().empty())
+    return;
```
[the remark this answers is not in the document]
Comment (vbvictor) [reply clang-tools-extra/clang-tidy/bugprone/ExceptionEscapeCheck.cpp]: Sure

**Review by vbvictor — APPROVED** [review]
LGTM with minor nit on docs

**Review by HerrCai0907 — APPROVED** [review]
LGTM
