### PR TITLE
[Clang] Treat default template argument as constant expressions

### LINKED ISSUE #107048: Clang error when using a constexpr variable as NTTP default value in lambda expression.
```c++
void foo()
{
    constexpr int x{};
    auto a = []<int=x>{};
}
```

Looks like a regression from 16 to 17, persists in 18 and current trunk. 

https://godbolt.org/z/TErqq79ao

### PR DESCRIPTION
**Pull request by cor3ntin**
We only check that a default argument is a converted constant expression when using the default argument.

However, when parsing a default argument, we need to make sure to parse it as a constant expression such as not ODR-use variables. (otherwise, we would try to capture default template arguments of generic lambdas)

Fixes #107048

### CODE REVIEW

File: clang/lib/Parse/ParseTemplate.cpp [hunk 1]
```diff
@@ -960,6 +960,8 @@ Parser::ParseNonTypeTemplateParameter(unsigned Depth, unsigned Position) {
       EnterExpressionEvaluationContext ConstantEvaluated(
           Actions, Sema::ExpressionEvaluationContext::ConstantEvaluated);
       DefaultArg = Actions.CorrectDelayedTyposInExpr(ParseInitializer());
+      if (DefaultArg.isUsable())
+        DefaultArg = Actions.ActOnConstantExpression(DefaultArg);
```
Comment (zyn0217) [inline clang/lib/Parse/ParseTemplate.cpp:964]: How about
```cpp
DefaultArg = Actions.ActOnConstantExpression(ParseInitializer())
```

Besides, I still don't understand why we shouldn't accept such code, according to the approach taken here
```cpp
struct S {};

void foo()
{
    constexpr S x{};
    auto a = []<auto = x>{};
}
```

but rather accept only non-record-type cases
```cpp
void foo()
{
    constexpr int x{};
    auto a = []<auto = x>{};
}
```

Can you add some standard quotes here?

Comment (cor3ntin) [reply clang/lib/Parse/ParseTemplate.cpp:964]: I am not sure what you mean. both should be valid

Comment (zyn0217) [reply clang/lib/Parse/ParseTemplate.cpp:964]: If you look at `Sema::CheckLValueToRValueConversionOperand()`, it would bail out if `E` is of a RecordType.
So the following would still be rejected
```cpp
struct S {};

void foo()
{
    constexpr S x{};
    auto a = []<auto = x>{};
}
```

Comment (cor3ntin) [reply clang/lib/Parse/ParseTemplate.cpp:964]: Oh, sorry. Yes
https://eel.is/c++draft/basic#def.odr-5

Comment (cor3ntin) [reply clang/lib/Parse/ParseTemplate.cpp:964]: https://compiler-explorer.com/z/Ybn4nbaz4 is another example of that where compilers agree

Comment (zyn0217) [reply clang/lib/Parse/ParseTemplate.cpp:964]: OK, I'm sold. (The *intervening scope* concept is still a bit harder for me to understand at the moment, so I'll probably look into it at some point.)

Feel free to merge this after one nit, which makes it a bit simpler

```cpp
DefaultArg = Actions.ActOnConstantExpression(ParseInitializer());
```

It would also be great if you could add the record-type case to the test. :)

**Review by zyn0217 — APPROVED** [review]

File: clang/test/SemaCXX/cxx2a-template-lambdas.cpp [hunk 2]
```diff
@@ -97,3 +97,29 @@ void foo() {
...
+    // expected-note@-1 {{candidate template ignored: substitution failure: reference to local variable 'z' declared in enclosing function}}
+    return t;
+  }();
+
+  struct S {};
+  constexpr S s;  // expected-note {{'s' declared here}}
+  auto class_type = []<S=s>{};
+  // expected-error@-1 {{variable 's' cannot be implicitly captured in a lambda with no capture-default specified}} \
+  // expected-note@-1 {{lambda expression begins here}} \
+  // expected-note@-1 4{{capture}}
```
Comment (shafik) [inline clang/test/SemaCXX/cxx2a-template-lambdas.cpp:123]: Curious about these cases: https://godbolt.org/z/xWbWYfnf3

```cpp
struct S {};
constexpr S s; 

void f() {
  auto class_type = []<S=s>{};
}

void h() {
  static constexpr S s;
  auto class_type = []<S=s>{};
}

template <S=s>
void g() {}
```

Comment (cor3ntin) [reply clang/test/SemaCXX/cxx2a-template-lambdas.cpp:130]: All of these work (because they are not local entities so don't need capturing https://eel.is/c++draft/basic#pre-7)
