### PR TITLE
[clangd] Correctly identify the next token after the completion point

### LINKED ISSUE #1785: Completion of function calls sometimes fails to include snippet
In the following code:

```c++
void waldo(int arg);

int main()
{
  int val;
  wal^

    // if (true)
  
}
```

Place the cursor at the location indicated by `^`, invoke completion, and select the only result.

Expected result: `waldo(int arg)` is inserted.

Actual result: `waldo` is inserted.

The behaviour has something to do with the commented line.

### PR DESCRIPTION
**Pull request by HighCommander4**
The code was previously using Lexer::findNextToken() which does not handle being passed the completion point as input.

Fixes https://github.com/clangd/clangd/issues/1785

### CODE REVIEW

**Comment by HighCommander4** [comment]
I've no idea what the error causing the format check ("Error: Unable to determine a difference between 8592241e29e29f0e7e407e0989489c6e70c91c42..e1ae800faed2fe3f612686edf6fe61f5b16e090d") to fail means.

**Comment by zyn0217** [comment]
I guess it's a signal for 'rebasing your branch please' :)

**Comment by HighCommander4** [comment]
> I guess it's a signal for 'rebasing your branch please' :)

Could you say more about that? Where is the requirement that my branch be sufficient recently coming from? It's only about 3 weeks old.

I don't like rebasing too often because rebuilding takes long.

**Comment by zyn0217** [comment]
> Where is the requirement that my branch be sufficiently recent coming from?

There's no such explicit requirement AFAIK; In my recollection, I've encountered several CI issues on Phabricator, and all of those were solved by rebasing my patch on top of the main.

**Comment by zyn0217** [comment]
(Maybe this is the reason: https://github.com/llvm/llvm-project/commit/cefc31c9213a82879254006ef479ed5ef6af7e69. Only top-100 commits are fetched by the CI currently. And sorry for bikeshedding the PR)

File: clang-tools-extra/clangd/CodeComplete.cpp [hunk 1]
```diff
@@ -1491,6 +1491,46 @@ FuzzyFindRequest speculativeFuzzyFindRequestForCompletion(
...
 }
 
+// This function is similar to Lexer::findNextToken(), but assumes
+// that the input SourceLocation is the completion point (which is
+// a case findNextToken() does not handle).
+std::optional<Token>
+findTokenAfterCompletionPoint(SourceLocation CompletionPoint,
+                              const SourceManager &SM,
+                              const LangOptions &LangOpts) {
+  SourceLocation Loc = CompletionPoint;
```
Comment (zyn0217) [inline clang-tools-extra/clangd/CodeComplete.cpp:1501]: I was about to comment that we should add an assertion here to reflect the contract. However, after going through the codes, it seems hard to tell the token kind under a source location without a lexer. :(

Also, do you think it's possible to make this function a static member of `Lexer` like `Lexer::findNextToken`? That way we might need a slight refactor to reuse some common logics.

**Review by zyn0217 — APPROVED** [review]
I'd like to approve the patch boldly since the `findTokenAfterCompletionPoint` is mostly duplicated from `Lexer::findNextToken` except for a difference that our version calls `Loc.getLocWithOffset(1)` rather than `MeasureTokenLength()` for the next token's location.

I have also tried another approach similar to Nathan's, in which I have constructed a lexer from the current location (i.e. the completion point) as well as the preprocessor. It looks as complicated as this way, and I don't think that is more optimal. (Or should I conclude that this is the best option?)

**Comment by HighCommander4** [comment]
Rebased

File: clang-tools-extra/clangd/CodeComplete.cpp (hunk 1 above)
Comment (HighCommander4) [reply clang-tools-extra/clangd/CodeComplete.cpp:1501]: > do you think it's possible to make this function a static member of `Lexer` like `Lexer::findNextToken`? That way we might need a slight refactor to reuse some common logics.

I think this would be a good improvement, but I'd like to leave it to a follow-up patch, because it involves adding new public API to `clang/Lex/Lexer.h`, so it should probably be approved by a code owner of the Lexer component.

**Comment by HighCommander4** [comment]
Thank you @zyn0217 for the review!
