### PR TITLE
[clang][AST] Handle implicit first argument in CallExpr::getBeginLoc()

### LINKED ISSUE #135522: [Clang] Missing source location in diagnostic for invalid conversion in function w/ explicit object parameter
Consider (https://godbolt.org/z/aa475YbW6):
```c++
struct X{};

template <typename T = void>
struct A {
    auto Error(this auto&& This) -> T {
        return T();
    }
};

struct B : A<X> {
    bool f();
};

bool B::f() {
    return Error();
}
```

Obviously, `X` isn’t convertible to `bool`, so we print an error, but the error is missing a source location:
```console
error: no viable conversion from returned value of type 'X' to function return type 'bool'
```

If I remove the explicit object parameter, we instead print
```console
<source>:15:12: error: no viable conversion from returned value of type 'X' to function return type 'bool'
   15 |     return Error();
      |            ^~~~~~~
```

This appears to be a regression since the source location *is* present in Clang 19.

### PR DESCRIPTION
**Pull request by HighCommander4**
Fixes https://github.com/llvm/llvm-project/issues/135522

### CODE REVIEW

File: clang/lib/AST/Expr.cpp [hunk 1]
```diff
@@ -1652,8 +1652,11 @@ SourceLocation CallExpr::getBeginLoc() const {
   if (!isTypeDependent()) {
     if (const auto *Method =
             dyn_cast_if_present<const CXXMethodDecl>(getCalleeDecl());
-        Method && Method->isExplicitObjectMemberFunction())
-      return getArg(0)->getBeginLoc();
+        Method && Method->isExplicitObjectMemberFunction()) {
+      if (auto FirstArgLoc = getArg(0)->getBeginLoc(); FirstArgLoc.isValid()) {
```
Comment (HighCommander4) [inline clang/lib/AST/Expr.cpp:1656]: Note, I took the approach of falling through if `FirstArgLoc` is invalid for any reason; presumably we never want to return an invalid location when we might fall through to a valid one in `getCallee()->getBeginLoc()`.

We could alternatively make the check more specific, to e.g. `!getArg(0)->isImplicitCXXThis()`.

**Review by cor3ntin — APPROVED** [review]
Can you add a changelog entry?
Otherwise LGTM

**Comment by HighCommander4** [comment]
Added changelog entry.

Should we backport this to 20.x?

**Review by zyn0217 — APPROVED** [review]
Yes, would be great to see it get backported

**Comment by HighCommander4** [comment]
> Yes, would be great to see it get backported

Filed backport issue: https://github.com/llvm/llvm-project/issues/135922
