### PR TITLE
[mlir][tosa] Fix not to crash with large permutation indexes 

### LINKED ISSUE #67763: [mlir][TOSA] --tosa-infer-shapes crashed with assertion failure "invalid index for shaped type"
git version: 8c1270740f6bf659e5fbf556c1145ddaa7aa5366

system: ```Ubuntu 20.04.6 LTS (Focal Fossa)```

reproduced with: ```mlir-opt --tosa-infer-shapes a.mlir```

a.mlir:
```
func.func @func2(%arg0: memref<7x2xi64>, %arg1: index) {
  %c6 = arith.constant 6 : index
  %cst_26 = arith.constant dense<[1185677355, 332462212]> : tensor<2xi32>
  %14 = tensor.empty(%c6) : tensor<?x27xi64>
  %72 = tosa.transpose %14, %cst_26 : (tensor<?x27xi64>, tensor<2xi32>) -> tensor<?x27xi64>
  return
}
```

trace:
```
mlir-opt: /data/bin/llvm-project/build/tools/mlir/include/mlir/IR/BuiltinTypeInterfaces.h.inc:195: int64_t mlir::ShapedType::getDimSize(unsigned int) const: Assertion `idx < getRank() && "invalid index for shaped type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/bin/llvm-project/build/bin/mlir-opt --tosa-infer-shapes a.mlir
 #0 0x000055b9cec1cd4f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/bin/llvm-project/build/bin/mlir-opt+0x157cd4f)
 #1 0x000055b9cec19de4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007ffbe6a95420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007ffbe658000b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007ffbe655f859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007ffbe655f729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007ffbe6570fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x000055b9d43c3d8a mlir::ShapeAdaptor::getDimSize(int) const (/data/bin/llvm-project/build/bin/mlir-opt+0x6d23d8a)
 #8 0x000055b9d08d9fde mlir::tosa::TransposeOp::inferReturnTypeComponents(mlir::MLIRContext*, std::optional<mlir::Location>, mlir::tosa::TransposeOpAdaptor, llvm::SmallVectorImpl<mlir::ShapedTypeComponents>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x3239fde)
 #9 0x000055b9d08da279 mlir::detail::InferShapedTypeOpInterfaceInterfaceTraits::Model<mlir::tosa::TransposeOp>::inferReturnTypeComponents(mlir::MLIRContext*, std::optional<mlir::Location>, mlir::ValueShapeRange, mlir::DictionaryAttr, mlir::OpaqueProperties, mlir::RegionRange, llvm::SmallVectorImpl<mlir::ShapedTypeComponents>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x323a279)
#10 0x000055b9d09337aa (anonymous namespace)::propagateShapesInRegion(mlir::Region&) TosaInferShapes.cpp:0:0
#11 0x000055b9d093523e (anonymous namespace)::TosaInferShapes::runOnOperation() TosaInferShapes.cpp:0:0
#12 0x000055b9d164fe8e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fafe8e)
#13 0x000055b9d165036a mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fb036a)
#14 0x000055b9d1650d6c mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::'lambda'(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const Pass.cpp:0:0
#15 0x000055b9d164f4c5 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/data/bin/llvm-project/build/bin/mlir-opt+0x3faf4c5)
#16 0x000055b9d164fc2a mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fafc2a)
#17 0x000055b9d165036a mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fb036a)
#18 0x000055b9d1650b94 mlir::PassManager::run(mlir::Operation*) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fb0b94)
#19 0x000055b9d164146b performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#20 0x000055b9d1642924 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPool*) MlirOptMain.cpp:0:0
#21 0x000055b9d1642ad4 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#22 0x000055b9d1740f84 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/data/bin/llvm-project/build/bin/mlir-opt+0x40a0f84)
#23 0x000055b9d163bef7 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/bin/llvm-project/build/bin/mlir-opt+0x3f9bef7)
#24 0x000055b9d1642dfb mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fa2dfb)
#25 0x000055b9ceb55feb main (/data/bin/llvm-project/build/bin/mlir-opt+0x14b5feb)
#26 0x00007ffbe6561083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#27 0x000055b9cebeda0e _start (/data/bin/llvm-project/build/bin/mlir-opt+0x154da0e)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Lewuathe**
The tosa-infer-shape pass does not check the permutation validity if it’s a constant value. We need to compare the rank size with the input tensor not to crash the pass.

closes https://github.com/llvm/llvm-project/issues/67763

### CODE REVIEW

File: mlir/lib/Dialect/Tosa/IR/TosaOps.cpp [hunk 1]
```diff
@@ -966,6 +966,16 @@ LogicalResult tosa::TransposeOp::inferReturnTypeComponents(
   if (matchPattern(adaptor.getPerms(), m_Constant(&attr)) &&
       attr.getType().getRank() == 1) {
     ShapeAdaptor permShape = attr;
+    // Constant permutation must be the same length as the input rank.
+    if (inputShape.getRank() != permShape.getRank())
+      return failure();
```
Comment (jpienaar) [inline mlir/lib/Dialect/Tosa/IR/TosaOps.cpp:971]: return emitOptionalError(location, ...) ?

File: mlir/lib/Dialect/Tosa/IR/TosaOps.cpp [hunk 2]
```diff
@@ -966,6 +966,16 @@ LogicalResult tosa::TransposeOp::inferReturnTypeComponents(
...
+
+    // Constant permutation values must be within the input rank.
+    for (int i = 0; i < inputShape.getRank(); i++) {
```
Comment (jpienaar) [inline mlir/lib/Dialect/Tosa/IR/TosaOps.cpp:974]: https://llvm.org/docs/CodingStandards.html#don-t-evaluate-end-every-time-through-a-loop

File: mlir/test/Dialect/Tosa/tosa-infer-shapes.mlir [hunk 3]
```diff
@@ -1272,3 +1272,29 @@ func.func @test_tosa_use_def_chain(%arg0: tensor<1x32x32x3xf32>, %arg1: tensor<1
...
+// CHECK-LABEL: test_large_constant_permutation
+func.func @test_large_constant_permutation() {
+  %c6 = arith.constant 6 : index
+  %cst_26 = arith.constant dense<[1185677355, 332462212]> : tensor<2xi32>
+  %14 = tensor.empty(%c6) : tensor<?x27xi64>
+  // Fail to infer the shape but not crash.
+  // CHECK: (tensor<?x27xi64>, tensor<2xi32>) -> tensor<?x27xi64>
+  %72 = tosa.transpose %14, %cst_26 : (tensor<?x27xi64>, tensor<2xi32>) -> tensor<?x27xi64>
+  return
+}
```
Comment (jpienaar) [inline mlir/test/Dialect/Tosa/tosa-infer-shapes.mlir:1300]: Missing new line at end.

File: mlir/lib/Dialect/Tosa/IR/TosaOps.cpp [hunk 4]
```diff
@@ -966,6 +966,18 @@ LogicalResult tosa::TransposeOp::inferReturnTypeComponents(
   if (matchPattern(adaptor.getPerms(), m_Constant(&attr)) &&
       attr.getType().getRank() == 1) {
     ShapeAdaptor permShape = attr;
+    // Constant permutation must be the same length as the input rank.
+    if (inputShape.getRank() != permShape.getRank())
+      return emitOptionalError(location,
+                               "Constant permutation must be the same length"
```
Comment (jpienaar) [inline mlir/lib/Dialect/Tosa/IR/TosaOps.cpp:972]: Convention for errors via emitError etc is sentence fragments (start lower cased and no trailing punctuation)

**Review by jpienaar — APPROVED** [review]
