### PR TITLE
[lldb/linux] Make sure the process continues running after a detach

### LINKED ISSUE #85084: LLDB TestConcurrentVFork.py is flaky on Arm and AArch64 Linux
`lldb/test/API/functionalities/fork/concurrent_vfork/TestConcurrentVFork.py` sometimes fails with a timeout. I've seen this on AArch64 and Arm Linux.

For example https://lab.llvm.org/buildbot/#/builders/17/builds/50450.
```
TIMEOUT: lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py (2684 of 2684)
******************** TEST 'lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py' FAILED ********************
Script:
--
/usr/bin/python3.8 /home/tcwg-buildbot/worker/lldb-arm-ubuntu/llvm-project/lldb/test/API/dotest.py -u CXXFLAGS -u CFLAGS --env ARCHIVER=/usr/local/bin/llvm-ar --env OBJCOPY=/usr/bin/llvm-objcopy --env LLVM_LIBS_DIR=/home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./lib --env LLVM_INCLUDE_DIR=/home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/include --env LLVM_TOOLS_DIR=/home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./bin --arch armv8l --build-dir /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/lldb-test-build.noindex --lldb-module-cache-dir /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/lldb-test-build.noindex/module-cache-lldb/lldb-api --clang-module-cache-dir /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/lldb-test-build.noindex/module-cache-clang/lldb-api --executable /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./bin/lldb --compiler /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./bin/clang --dsymutil /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./bin/dsymutil --llvm-tools-dir /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./bin --lldb-libs-dir /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/./lib /home/tcwg-buildbot/worker/lldb-arm-ubuntu/llvm-project/lldb/test/API/functionalities/fork/concurrent_vfork -p TestConcurrentVFork.py
--
Exit Code: -9
Timeout: Reached timeout of 600 seconds
Command Output (stdout):
--
lldb version 19.0.0git (https://github.com/llvm/llvm-project.git revision e48d5a838f69e0a8e0ae95a8aed1a8809f45465a)
  clang revision e48d5a838f69e0a8e0ae95a8aed1a8809f45465a
  llvm revision e48d5a838f69e0a8e0ae95a8aed1a8809f45465a
--
```
Inspecting the container afterwards shows that we are using way more PIDs than you'd expect, and we have around 600 processes like:
```
 tcwg-bu+ 4177936       1  0 Mar11 pts/0    00:00:00 /home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/lldb-test-build.noindex/functionalities/fork/concurrent_vfork/TestConcurrentVFork.test_follow_child_vfork_call_exec/a.out
```

This container persists so this could be the result of the test not cleaning up processes, and them piling up until the system complains, or someone tries to debug the wrong process and gets no response. On AArch64 I have seen it lead to system resource errors as the leftover processes pile up.

I'm going to skip all the tests on these platforms while I look into it.

### PR DESCRIPTION
**Pull request by labath**
Fixes #85084

Whenever an inferior thread stops, lldb-server sends a SIGSTOP to all other threads in the process to force them to stop as well. If those threads stop on their own before they get a signal, this SIGSTOP will remain pending and be delivered the next time the process resumes.

Normally, this is not a problem, because lldb-server will detect this stale SIGSTOP and resume the process. However, if we detach from the process while it has these SIGSTOPs pending, they will get immediately delivered, and the process will remain stopped (most likely forever).

This patch fixes that by sending a SIGCONT just before detaching from the process. This signal cancels out any pending SIGSTOPs, and ensures it is able to run after we detach. It does have one somewhat unfortunate side-effect that in that the process's SIGCONT handler (if it has one) will get executed spuriously (from the process's POV).

This could be _sometimes_ avoided by tracking which threads got send a SIGSTOP, and whether those threads stopped due to it. From what I could tell by observing its behavior, this is what gdb does. I have not tried to replicate that behavior here because it adds a nontrivial amount of complexity and the result is still uncertain -- we still need to send a SIGCONT (and execute the handler) when any thread stops for some other reason (and leaves our SIGSTOP hanging). Furthermore, since SIGSTOPs don't stack, it's also possible that our SIGSTOP/SIGCONT combination will cancel a genuine SIGSTOP being sent to the debugger application (by someone else), and there is nothing we can do about that. For this reason I think it's simplest and most predictible to just always send a SIGCONT when detaching, but if it turns out this is breaking something, we can consider implementing something more elaborate.

One alternative I did try is to use PTRACE_INTERRUPT to suspend the threads instead of a SIGSTOP. PTRACE_INTERUPT requires using PTRACE_SEIZE to attach to the process, which also made this solution somewhat complicated, but the main problem with that approach is that PTRACE_INTERRUPT is not considered to be a signal-delivery-stop, which means it's not possible to resume it while injecting another signal to the inferior (which some of our tests expect to be able to do). This limitation could be worked around by forcing the thread into a signal delivery stop whenever we need to do this, but this additional complication is what made me think this approach is also not worthwhile.

This patch should fix (at least some of) the problems with TestConcurrentVFork, but I've also added a dedicated test for checking that a process keeps running after we detach. Although the problem I'm fixing here is linux-specific, the core functinoality of not stopping after a detach should function the same way everywhere.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Will fix https://github.com/llvm/llvm-project/issues/85084.

**Comment by DavidSpickett** [comment]
Thanks for looking into this. I had no idea what it might be but your explanation makes a lot of sense.

File: lldb/test/API/commands/process/detach-resumes/main.cpp [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+void break_here() {}
+
+void tfunc() {
+  pseudo_barrier_wait(barrier);
+
+  break_here();
+}
+
+int main(int argc, char const *argv[]) {
+  lldb_enable_attach();
```
Comment (jeffreytan81) [inline lldb/test/API/commands/process/detach-resumes/main.cpp:23]: Just curious, why this is needed? 
Is it that some special OS may restrict the default attaching behavior for security reason unless lldb_enable_attach() is explicitly called?

**Review by jeffreytan81 — APPROVED** [review]

File: lldb/test/API/commands/process/detach-resumes/TestDetachResumes.py [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+            "thread list",
+            STOPPED_DUE_TO_BREAKPOINT,
+            substrs=["stopped", "stop reason = breakpoint"],
+        )
+
+        # Detach, the process should keep running after this, and not be stopped
+        # by the signals that the debugger may have used to suspend the threads.
+        self.runCmd("detach")
+
+        lldbutil.wait_for_file_on_target(self, exit_file_path)
```
[the remark this answers is not in the document]
Comment (labath) [reply lldb/test/API/commands/process/detach-resumes/TestDetachResumes.py:59]: Yes, and just in case it does not, the file name has an embedded time stamp (mainly a remnant of the time where we were not automatically cleaning up the test dir :) )

File: lldb/test/API/commands/process/detach-resumes/main.cpp (hunk 1 above)
Comment (labath) [reply lldb/test/API/commands/process/detach-resumes/main.cpp:23]: Yes, but it's not really a "special" OS. Most linux systems are configured like that by default, where you're only allowed to debug your own children (unless they explicitly allow that, or you're root, etc.). Check out https://www.kernel.org/doc/html/v4.15/admin-guide/LSM/Yama.html. lldb_enable_attach is our own invention, which calls the appropriate os interface to enable attaching if necessary. Currently, it's only implemented on linux.

**Review by DavidSpickett — APPROVED** [review]
LGTM
