### PR TITLE
[CodeGen][counted_by] See past parentheses and no-op casts

### LINKED ISSUE #151236: `__builtin_dynamic_object_size` of pointer member marked with `counted_by` confused by extra parens
Strangely, `__builtin_dynamic_object_size()` of a pointer member annotated with `counted_by` goes wrong if passed with wrapping parens. As in, the latter reports `SIZE_MAX`.

```
        printf("%zu\n", __builtin_dynamic_object_size(fixed->a, 1));
        printf("%zu\n", __builtin_dynamic_object_size((fixed->a), 1));
```

This should not be, and doesn't happen for any other similar constructions:

```
#include <stdio.h>

struct fixed_size {
        int *a __attribute__((counted_by(a_count)));
        short a_count;
};

struct dyn_size {
        short b_count;
        int b[] __attribute__((counted_by(b_count)));
};

void __attribute__((noinline))
foo(struct fixed_size *fixed, struct dyn_size *dyn)
{
        int b;
        int *p = &b;

        printf("%zu\n", __builtin_dynamic_object_size(p, 1));
        printf("%zu\n", __builtin_dynamic_object_size((p), 1));
        printf("%zu\n", __builtin_dynamic_object_size(dyn->b, 1));
        printf("%zu\n", __builtin_dynamic_object_size((dyn->b), 1));
        printf("%zu\n", __builtin_dynamic_object_size(&fixed->a_count, 1));
        printf("%zu\n", __builtin_dynamic_object_size((&fixed->a_count), 1));
        printf("%zu\n", __builtin_dynamic_object_size(fixed->a, 1));
        printf("%zu\n", __builtin_dynamic_object_size((fixed->a), 1));
}

int main(void)
{
        struct fixed_size f = { .a_count = 0 };
        struct dyn_size d = { .b_count = 0 };

        foo(&f, &d);
        return 0;
}
```

Prints:

```
4
4
0
0
2
2
0
18446744073709551615
```

@bwendling

### PR DESCRIPTION
**Pull request by bwendling**
Parentheses and no-op casts don't change the value. Skip past them to get to a MemberExpr.

Fixes #151236

### CODE REVIEW

**Review by AaronBallman — APPROVED** [review]
LGTM!

Thought it did raise a question of whether this code should work: https://godbolt.org/z/aoqf85r1x
```
struct S {
  int *a __counted_by(a_count);
  _Atomic int a_count;
};
```
(Not necessary as part of this PR, just something I noticed when poking around with the ignoring noop casts change.)

**Comment by bwendling** [comment]
> LGTM!
> 
> Thought it did raise a question of whether this code should work: https://godbolt.org/z/aoqf85r1x
> 
> ```
> struct S {
>   int *a __counted_by(a_count);
>   _Atomic int a_count;
> };
> ```
> 
I don't know. That's a question for the Apple people.

File: clang/test/CodeGen/attr-counted-by-for-pointers.c [hunk 1]
```diff
@@ -471,3 +471,80 @@ size_t test9(struct annotated_sized_ptr *p, int index) {
...
+// SANITIZE-WITHOUT-ATTR-NEXT:  entry:
+// SANITIZE-WITHOUT-ATTR-NEXT:    ret i64 -2
+//
+// NO-SANITIZE-WITHOUT-ATTR-LABEL: define dso_local range(i64 0, -1) i64 @test11(
+// NO-SANITIZE-WITHOUT-ATTR-SAME: ptr noundef readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR1]] {
+// NO-SANITIZE-WITHOUT-ATTR-NEXT:  entry:
+// NO-SANITIZE-WITHOUT-ATTR-NEXT:    ret i64 -2
+//
+size_t test11(struct pr151236_struct *p) {
+  return __bdos(p->a) + __bdos((p->a));
```
Comment (shafik) [inline clang/test/CodeGen/attr-counted-by-for-pointers.c:513]: Maybe also worth trying a comma operator inside the parens e.g. `(0,p->a)`

I noted that had the same behavior in the original example: https://godbolt.org/z/j9765v75z

Comment (bwendling) [reply clang/test/CodeGen/attr-counted-by-for-pointers.c:513]: I'm not super worried about that construction, and it can get into very tricky situations. For instance, only the final expression is the "result" of the comma operator, the preceding expressions could be arbitrarily complex, and they cannot have side-effects. This is a can of worms that I want to keep shut (as I hope such usage is extremely rare)... :-)

Comment (shafik) [reply clang/test/CodeGen/attr-counted-by-for-pointers.c:513]: So there are two concerns here 1) What is the behavior we expect and documenting that, via tests one way of doing that 2) Making sure we don't crash or some other bad behavior.

I spend a lot of time triaging and folks do plenty of stuff we don't expect and or discourage and if we can predict some of them in advance that saves us time later on.

Comment (bwendling) [reply clang/test/CodeGen/attr-counted-by-for-pointers.c:513]: What I want is to reject that behavior. It's completely abnormal. But whatever. I'll send a patch.
