### PR TITLE
[lldb] checks beforehand if lldb can trace/attach a process on FreeBSD.

### LINKED ISSUE #79634: [lldb] Unclear error message when failing to debug programs on FreeBSD
FreeBSD supports a security setting, exposed in the `security.bsd.unprivileged_proc_debug` sysctl, preventing programs from being debugged globally (except for the `root` user).

When this sysctl is set to `0`, `lldb` fails with `error: Cannot launch 'program': Operation not permitted`. While this is as expected, it would be helpful to improve this error dialog and prompt the user to verify this sysctl upon this error.

### PR DESCRIPTION
**Pull request by devnexen**
before having the generic EINVAL message, we check if the `security.bsd.unprivileged_proc_debug` allows process debugging.

close #79634

### CODE REVIEW

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp [hunk 1]
```diff
@@ -48,14 +48,37 @@ static Status EnsureFDFlags(int fd, int flags) {
...
 }
 
+static Status CanTrace() {
+  Status status;
+  int proc_debug, ret;
+  size_t len = sizeof(proc_debug);
+  ret = ::sysctlbyname("security.bsd.unprivileged_proc_debug", &proc_debug,
+                       &len, nullptr, 0);
+  if (ret != 0)
+    return Status("sysctlbyname() security.bsd.unprivileged_proc_debug failed");
```
Comment (bulbazord) [inline lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:58]: How long has FreeBSD had `security.bsd.unprivileged_proc_debug`? If you're debugging an older FreeBSD system that does not have it, this will prevent it from debugging anything.

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp [hunk 2]
```diff
@@ -48,14 +48,37 @@ static Status EnsureFDFlags(int fd, int flags) {
   return error;
 }
 
+static Status CanTrace() {
+  Status status;
```
Comment (bulbazord) [inline lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:52]: Suggestion: You can remove this and just return {} below.

**Review by bulbazord — CHANGES_REQUESTED** [review]

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp (hunk 1 above)
Comment (devnexen) [reply lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:58]: since a long time :) e.g. even 9.0, EOL since more than a decade, had it.

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp (hunk 2 above)
Comment (devnexen) [reply lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:52]: true

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp (hunk 1 above)
Comment (emaste) [reply lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:57]: It's had the current name for over 2 decades, https://github.com/freebsd/freebsd-src/commit/e409590d0e0e57c6ec37d95bcb9fa3728051ebb1

The sysctl existed prior to that with a different name; I didn't bother looking to see when that was introduced.

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp [hunk 3]
```diff
@@ -48,14 +48,36 @@ static Status EnsureFDFlags(int fd, int flags) {
...
 // Public Static Methods
 
 llvm::Expected<std::unique_ptr<NativeProcessProtocol>>
 NativeProcessFreeBSD::Manager::Launch(ProcessLaunchInfo &launch_info,
                                       NativeDelegate &native_delegate) {
   Log *log = GetLog(POSIXLog::Process);
-
   Status status;
+
+  status = CanTrace();
```
Comment (emaste) [inline lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:74]: I might suggest moving these checks into the Fail case below, avoiding the extra syscall that's not necessary in the common case. Also, we may have other cases we could start checking for.

**Comment by emaste** [comment]
Thanks for picking this up -- I was starting to take a look but was sidetracked with a lot of yak shaving.

File: lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp (hunk 1 above)
Comment (bulbazord) [reply lldb/source/Plugins/Process/FreeBSD/NativeProcessFreeBSD.cpp:57]: Thanks for the explanation. Consider my concerns addressed, don't let my "Requested Changes" block this from going in after another approval. :)

**Comment by devnexen** [comment]
ping :)

**Review by bulbazord — APPROVED** [review]
LGTM but I'm not really an expert on FreeBSD. @emaste ?

**Review by emaste — APPROVED** [review]

**Comment by emaste** [comment]
commit message probably needs updating for the logic change (no longer beforehand)

Another reason to defer the check until failure occurs - if the user happens to be running lldb as root ptrace will be able to attach independent of the state of that sysctl
