### PR TITLE
[Clang] Fix handling of immediate escalation for inherited constructors

### LINKED ISSUE #112677: [clang] consteval constructor executes at runtime when invoked by escalated immediate function (or fails to link)
Consider the following code:

```c++
#include <iostream>
#include <optional>


class ConstEval {
 public:
  consteval ConstEval(const char* value) {
    const char* current_char = value;
    while (*current_char) {
      if (*current_char == 'a') {
        throw "Disallowed character!";
      }
      ++current_char;
    }
    value_ = value;
  }
  constexpr const char* value() { return value_; }
 private:
  const char* value_;
};

void TakesOptional(std::optional<ConstEval> maybe_value) {
  if (maybe_value.has_value()) {
    std::cout << "Value: " << maybe_value->value() << std::endl;
  } else {
    std::cout << "No value" << std::endl;
  }
}

int main(int argc, const char*argv[]) {
  // 1
  TakesOptional("testing 123");
  // 2
  std::optional<ConstEval> foo2 = "testing 123";
  // 3
  constexpr std::optional<ConstEval> foo3 = "testing 123";
  // 4
  TakesOptional(ConstEval{"testing 123"});
}

// 5
std::optional<ConstEval> foo5 = "testing 123";
// 6
constinit std::optional<ConstEval> foo6 = "testing 123";
```

Assuming I'm reading things correctly, I would expect the `std::optional` constructor to be an immediate-escalating function (because it is "a function that results from the instantiation of a templated entity defined with the constexpr specifier"), and a contained call to `ConstEval`'s constructor to be an immediate-escalating expression, causing the `std::optional` constructor to become an immediate function.

Thus, I would expect lines 1, 2, 3, 5, and 6 all to immediately invoke the `std::optional` constructor to create a compile-time constant `std::optional` (indirectly invoking the `ConstEval` constructor), while 4 would immediately invoke the `ConstEval` constructor to create a constant `ConstEval`, which would then passed to the (not immediate, in this case) `std::optional` constructor.

Given that, I would further expect that changing "testing" to "tasting" on any of the 6 lines would result in a compiler failure (specifically, one informing me that `throw "Disallowed character!"` is not valid in a constant expression).

However, with clang built from revision 3dbd929ea6af134650dd1d91baeb61a4fc1b0eb8, only lines 3, 4, and 6 fail to compile if "testing" is changed to "tasting". Lines 1, 2, and 5 unexpectedly continue to compile if "testing" in changed to "tasting", and instead cause an abort at runtime due to the uncaught exception. Thus, it appears that while clang properly considers the invocation of the explicitly-immediate `ConstEval` constructor to be a constant expression in 4, it erroneously does _not_ consider the invocation of the escalated-to-immediate `std::optional` constructor to be a constant expression in 1, 2, and 5. Meanwhile, 3 and 6 invoke the constructor within an explicit constant expression, so those work as expected.

A further note: the observed behavior of `ConstEval`'s constructor executing (and crashing if "testing" is changed to "tasting") at runtime for 1, 2, and 5 appears only to happen if it's small enough to inline into the generated `std::optional` specialization. If the constructor is more complicated and doesn't get inlined, lines 1, 2, and 5 will instead generate a linker error due to the symbol `ConstEval::ConstEval(char const*)` not being defined.

### PR DESCRIPTION
**Pull request by cor3ntin**
Fixes #112677

### CODE REVIEW

File: clang/lib/AST/Decl.cpp [hunk 1]
```diff
@@ -3284,6 +3284,13 @@ bool FunctionDecl::isImmediateEscalating() const {
   // consteval specifier,
   if (isDefaulted() && !isConsteval())
     return true;
+
+  if (auto *CD = dyn_cast<CXXConstructorDecl>(this);
```
Comment (tbaederr) [inline clang/lib/AST/Decl.cpp:3288]:
```suggestion
  if (const auto *CD = dyn_cast<CXXConstructorDecl>(this);
```

File: clang/lib/AST/Decl.cpp [hunk 2]
```diff
@@ -3304,6 +3311,12 @@ bool FunctionDecl::isImmediateFunction() const {
   if (isImmediateEscalating() && BodyContainsImmediateEscalatingExpressions())
     return true;
 
+  if (auto *CD = dyn_cast<CXXConstructorDecl>(this);
```
Comment (tbaederr) [inline clang/lib/AST/Decl.cpp:3314]:
```suggestion
  if (const auto *CD = dyn_cast<CXXConstructorDecl>(this);
```

**Review by erichkeane — APPROVED** [review]

**Comment by efriedma-quic** [comment]
Consider the following testcase:

```
struct ConstEval {
  consteval ConstEval(int) {}
};
struct SimpleCtor { constexpr SimpleCtor(int) {}};
struct TemplateCtor {
  template <class Anything = int> constexpr
  TemplateCtor (int arg) {}
};
struct ConstEvalMember1 : SimpleCtor {
    int y = 10;
    ConstEval x = y;
    using SimpleCtor::SimpleCtor;
};
struct ConstEvalMember2 : TemplateCtor {
    int y = 10;
    ConstEval x = y;
    using TemplateCtor::TemplateCtor;
};
void f() {
  ConstEvalMember1 i(0);
  ConstEvalMember2 i2(0);
}
```

With this patch, the first one produces an error, the second doesn't.  Which... seems dubious?  Not sure.  Inheriting the "immediate-escalating" property seems surprising to me.

**Comment by rkjnsn** [comment]
> With this patch, the first one produces an error, the second doesn't. Which... seems dubious?

I am far from a standards expert, but I would _expect_ both to compile? When calling an inherited constructor, "all other bases and members of Derived are initialized as if by the defaulted default constructor", and a "a defaulted special member function that is not declared with the consteval specifier" is an immediate-escalating function.

So, my thought is that there is a compiler generated constructor that is immediate-escalating, which in turn calls the base class constructor, which may or may not be immediate or immediate-escalating. So, in the reduced test case from the original bug #112677, the FakeOptionalBase constructor is immediate-escalating, as is the compiler generated FakeOptional constructor. Since the ConstEval constructor is immediate, the FakeOptionalBase constructor escalates to being immediate, which in turn causes the FakeOptional constructor to escalate to being immediate.

In the testcase here, the TemplateCtor constructor is immedate-escalating and SimpleCtor constructor is not, but in neither case is the resulting base constructor immediate. However, I would expect the generated constructor for both ConstEvalMember1 and CostEvalMember2 to be immediate-escalating, and both to then escalate to being immediate due to the call to the immediate ConstEval constructor, as I believe default member initializers used to initialize a member subobject have been clarified to be part of the body of the constructor.

**Comment by rkjnsn** [comment]
I tried to poke around at this. I believe the simplest change to the PR to match my intuition would be to change

```c++
  if (const auto *CD = dyn_cast<CXXConstructorDecl>(this);
      CD && CD->isInheritingConstructor())
    return CD->getInheritedConstructor()
        .getConstructor()
        ->isImmediateEscalating();
```

to 

```c++
  if (const auto *CD = dyn_cast<CXXConstructorDecl>(this);
      CD && CD->isInheritingConstructor())
    return true;
```

in `FunctionDecl::isImmediateEscalating()`.

However, it might be additionally be desirable to have `BodyContainsImmediateEscalatingExpressions()` return true if the call to the inherited constructor in the base class is an immediately-escalating expression, similar to other field and base-class initialization. That would allow removing

```c++
  if (const auto *CD = dyn_cast<CXXConstructorDecl>(this);
      CD && CD->isInheritingConstructor())
    return CD->getInheritedConstructor()
        .getConstructor()
        ->isImmediateFunction();
```

from `FunctionDecl::isImmediateFunction()` and just relying on

```c++
  if (isImmediateEscalating() && BodyContainsImmediateEscalatingExpressions())
    return true;
```

to handle the immediate-inherited-constructor case.

However, I am not familiar enough with the code to know the proper way to make that happen.

**Comment by cor3ntin** [comment]
@erichkeane mind re-reviewing that?

**Review by erichkeane — APPROVED** [review]
I have no concerns.
