### PR TITLE
[BOLT][AArch64] Fixes assertion errors occurred when perf2bolt was executed

### LINKED ISSUE #83114: [BOLT] Perf2bolt is failing with assertion on AArch64
Hi Everyone,

I've bumped in to an assertion when I tried to convert basic perf.data /without LBR/ to BOLT format on AArch64. I used a small bubble sort example and compiled as static. In my cases the indirect branch patterns bit differ from the common patter what BOLT expect. I also enclose a diff as a workaround. What do you think? Please see the details below: 

Perf2bolt cmd:

```
perf2bolt -p perf.data -p perf.fdata bubble_sort_clang_arm64 -nl
```
Issue:

```
PERF2BOLT: Starting data aggregation job for perf.data-pmu-cycle
PERF2BOLT: spawning perf job to read events without LBR
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: a0b3dbaf4b3c01dc7f0a83fce059a26360b58eb2
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x400000, offset 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: static input executable detected
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-WARNING: Failed to analyze 1014 relocations
BOLT-INFO: pre-processing profile using perf data aggregator
BOLT-WARNING: build-id will not be checked because we could not read one from input binary
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT: waiting for perf task events collection to finish...
PERF2BOLT: parsing perf-script task events output
PERF2BOLT: input binary is associated with 1 PID(s)
PERF2BOLT: waiting for perf events collection to finish...
PERF2BOLT: parsing basic events (without LBR)...
PERF2BOLT: waiting for perf mem events collection to finish...
BOLT-WARNING: internal call detected at 0x237fb0 in function __libc_start_main/1(*4). Skipping.
perf2bolt: /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:751: bool (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranchFragment(const MCInst &, DenseMap<const MCInst *, SmallVector<MCInst *, 4>> &, const MCExpr *&, int64_t &, int64_t &, MCInst *&) const: Assertion `DefJTBaseAdd->getOpcode() == AArch64::ADDXri && "Failed to match jump table base address pattern! (1)"' failed.
 #0 0x0000aaaaaf4d2600 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x0000aaaaaf4d2b10 PrintStackTraceSignalHandler(void*) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x0000aaaaaf4d0cb8 llvm::sys::RunSignalHandlers() /home/kadam/llvm-project/llvm/lib/Support/Signals.cpp:105:5
 #3 0x0000aaaaaf4d3350 SignalHandler(int) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x0000ffff9196e8f8 (linux-vdso.so.1+0x8f8)
 #5 0x0000ffff9139f200 (/lib/aarch64-linux-gnu/libc.so.6+0x7f200)
 #6 0x0000ffff9135a67c gsignal (/lib/aarch64-linux-gnu/libc.so.6+0x3a67c)
 #7 0x0000ffff91347130 abort (/lib/aarch64-linux-gnu/libc.so.6+0x27130)
 #8 0x0000ffff91353fd0 (/lib/aarch64-linux-gnu/libc.so.6+0x33fd0)
 #9 0x0000ffff91354040 __assert_perror_fail (/lib/aarch64-linux-gnu/libc.so.6+0x34040)
#10 0x0000aaaaaff06d00 (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranchFragment(llvm::MCInst const&, llvm::DenseMap<llvm::MCInst const*, llvm::SmallVector<llvm::MCInst*, 4u>, llvm::DenseMapInfo<llvm::MCInst const*, void>, llvm::detail::DenseMapPair<llvm::MCInst const*, llvm::SmallVector<llvm::MCInst*, 4u>>>&, llvm::MCExpr const*&, long&, long&, llvm::MCInst*&) const /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:753:9
#11 0x0000aaaaaff020c0 (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranch(llvm::MCInst&, llvm::bolt::MCPlusBuilder::InstructionIterator, llvm::bolt::MCPlusBuilder::InstructionIterator, unsigned int, llvm::MCInst*&, unsigned int&, unsigned int&, long&, llvm::MCExpr const*&, llvm::MCInst*&) const /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:852:9
#12 0x0000aaaaaff687e4 llvm::bolt::BinaryFunction::processIndirectBranch(llvm::MCInst&, unsigned int, unsigned long, unsigned long&) /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:810:43
#13 0x0000aaaaaff69f2c llvm::bolt::BinaryFunction::handleIndirectBranch(llvm::MCInst&, unsigned long, unsigned long) /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:1110:22
#14 0x0000aaaaaff6b290 llvm::bolt::BinaryFunction::disassemble() /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:1336:11
#15 0x0000aaaaaf5a81b0 llvm::bolt::RewriteInstance::disassembleFunctions() /home/kadam/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3179:30
#16 0x0000aaaaaf5a2fc0 llvm::bolt::RewriteInstance::run() /home/kadam/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:743:3
#17 0x0000aaaaaeac6750 main /home/kadam/llvm-project/bolt/tools/driver/llvm-bolt.cpp:267:24
#18 0x0000ffff913473fc (/lib/aarch64-linux-gnu/libc.so.6+0x273fc)
#19 0x0000ffff913474cc __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274cc)
#20 0x0000aaaaaeac58b0 _start (./llvm-project/build-orig-bolt-arm64/bin/perf2bolt+0x2758b0)
```

```
PERF2BOLT: Starting data aggregation job for perf.data-pmu-cycle
PERF2BOLT: spawning perf job to read events without LBR
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: a0b3dbaf4b3c01dc7f0a83fce059a26360b58eb2
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x400000, offset 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: static input executable detected
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-WARNING: Failed to analyze 1014 relocations
BOLT-INFO: pre-processing profile using perf data aggregator
BOLT-WARNING: build-id will not be checked because we could not read one from input binary
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT: waiting for perf task events collection to finish...
PERF2BOLT: parsing perf-script task events output
PERF2BOLT: input binary is associated with 1 PID(s)
PERF2BOLT: waiting for perf events collection to finish...
PERF2BOLT: parsing basic events (without LBR)...
PERF2BOLT: waiting for perf mem events collection to finish...
BOLT-WARNING: internal call detected at 0x237fb0 in function __libc_start_main/1(*4). Skipping.
BOLT-WARNING: internal call detected at 0x249488 in function __run_exit_handlers/1(*2). Skipping.
Failed to match indirect branch! (fragment 3)
UNREACHABLE executed at /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:712!
 #0 0x0000aaaab41d2600 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x0000aaaab41d2b10 PrintStackTraceSignalHandler(void*) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x0000aaaab41d0cb8 llvm::sys::RunSignalHandlers() /home/kadam/llvm-project/llvm/lib/Support/Signals.cpp:105:5
 #3 0x0000aaaab41d3350 SignalHandler(int) /home/kadam/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x0000ffffabbe18f8 (linux-vdso.so.1+0x8f8)
 #5 0x0000ffffab61f200 (/lib/aarch64-linux-gnu/libc.so.6+0x7f200)
 #6 0x0000ffffab5da67c gsignal (/lib/aarch64-linux-gnu/libc.so.6+0x3a67c)
 #7 0x0000ffffab5c7130 abort (/lib/aarch64-linux-gnu/libc.so.6+0x27130)
 #8 0x0000aaaab4116fc0 llvm::install_out_of_memory_new_handler() /home/kadam/llvm-project/llvm/lib/Support/ErrorHandling.cpp:193:0
 #9 0x0000aaaab4c0693c (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranchFragment(llvm::MCInst const&, llvm::DenseMap<llvm::MCInst const*, llvm::SmallVector<llvm::MCInst*, 4u>, llvm::DenseMapInfo<llvm::MCInst const*, void>, llvm::detail::DenseMapPair<llvm::MCInst const*, llvm::SmallVector<llvm::MCInst*, 4u>>>&, llvm::MCExpr const*&, long&, long&, llvm::MCInst*&) const /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:715:9
#10 0x0000aaaab4c020c0 (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranch(llvm::MCInst&, llvm::bolt::MCPlusBuilder::InstructionIterator, llvm::bolt::MCPlusBuilder::InstructionIterator, unsigned int, llvm::MCInst*&, unsigned int&, unsigned int&, long&, llvm::MCExpr const*&, llvm::MCInst*&) const /home/kadam/llvm-project/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:872:9
#11 0x0000aaaab4c68810 llvm::bolt::BinaryFunction::processIndirectBranch(llvm::MCInst&, unsigned int, unsigned long, unsigned long&) /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:810:43
#12 0x0000aaaab4c69f58 llvm::bolt::BinaryFunction::handleIndirectBranch(llvm::MCInst&, unsigned long, unsigned long) /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:1110:22
#13 0x0000aaaab4c6b2bc llvm::bolt::BinaryFunction::disassemble() /home/kadam/llvm-project/bolt/lib/Core/BinaryFunction.cpp:1336:11
#14 0x0000aaaab42a81b0 llvm::bolt::RewriteInstance::disassembleFunctions() /home/kadam/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:3179:30
#15 0x0000aaaab42a2fc0 llvm::bolt::RewriteInstance::run() /home/kadam/llvm-project/bolt/lib/Rewrite/RewriteInstance.cpp:743:3
#16 0x0000aaaab37c6750 main /home/kadam/llvm-project/bolt/tools/driver/llvm-bolt.cpp:267:24
#17 0x0000ffffab5c73fc (/lib/aarch64-linux-gnu/libc.so.6+0x273fc)
#18 0x0000ffffab5c74cc __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274cc)
#19 0x0000aaaab37c58b0 _start (./llvm-project/build-orig-bolt-arm64/bin/perf2bolt+0x2758b0)
```
Example:

```
clang bubblesort.c -o bubble_sort_clang_arm64 --target=aarch64-linux -fuse-ld=lld -flto=thin -O2 -static -Wl,--emit-relocs
```
```
perf record -e cycles:u -- bubble_sort_clang_arm64
```

```
#include <stdio.h>
#include <stdlib.h>

void swap(int* xp, int* yp)
{
        int temp = *xp;
        *xp = *yp;
        *yp = temp;
}

void bubbleSort(int arr[], int n)
{
        int i, j;
        for (i = 0; i < n - 1; i++)

                for (j = 0; j < n - i - 1; j++)
                        if (arr[j] > arr[j + 1])
                                swap(&arr[j], &arr[j + 1]);
}

void printArray(int arr[], int size)
{
        int i;
        for (i = 0; i < size; i++)
                printf("%d ", arr[i]);
        printf("\n");
}

void fillUp(int* array , int size)
{
   for (int i=0; i < size; ++i) {
     *(array+i) = rand() % 1000000;
   }
}

int main()
{
        int arr_new[100000];
        srand((unsigned) 41);
        fillUp(&arr_new[0], 100000);
        bubbleSort(arr_new, 100000);
        return 0;
}
```

As a workaround:

```
diff --git a/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp b/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp
index d90512e21225..1b0a781b3ebe 100644
--- a/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp
+++ b/bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp
@@ -701,8 +701,15 @@ public:
     unsigned ShiftVal = AArch64_AM::getArithShiftValue(OperandExtension);
     AArch64_AM::ShiftExtendType ExtendType =
         AArch64_AM::getArithExtendType(OperandExtension);
-    if (ShiftVal != 2)
-      llvm_unreachable("Failed to match indirect branch! (fragment 2)");
+    if (ShiftVal != 2) {
+       // In that case when shift amount i.e. could be zero.
+       //   adr     x6, 0x219fb0 <sigall_set+0x88>
+       //   add     x6, x6, x14, lsl #2
+       //   ldr     w7, [x6]
+       //   add     x6, x6, w7, sxtw => no shift
+       //   br      x6
+      return false;
+    }
 
     if (ExtendType == AArch64_AM::SXTB)
       ScaleValue = 1LL;
@@ -747,6 +754,16 @@ public:
       return true;
     }
 
+    if (DefJTBaseAdd->getOpcode() == AArch64::ADR) {
+      // Array indexing 'table branch'
+      //  adr     x13, 0x215a18 <_nl_value_type_LC_COLLATE+0x50>
+      //  ldrh    w13, [x13, w12, uxtw #1]
+      //  adr     x12, 0x247b30 <__gettextparse+0x5b0>
+      //  add     x13, x12, w13, sxth #2
+      //  br      x13
+      return false;
+    }
+
     assert(DefJTBaseAdd->getOpcode() == AArch64::ADDXri &&
            "Failed to match jump table base address pattern! (1)");
 ```

### PR DESCRIPTION
**Pull request by kaadam**
BOLT only checks for the most common indirect branch pattern during the branch analyzation.
Extended the logic with two other indirect patterns which slightly differ from the expected one.
Those patterns may be hit when statically linking libc (pattern 2 requires 'lld' linker).

As a workaround mark them as UNKNOWN branch for now. 

Fixes: #83114

### CODE REVIEW

**Comment by yota9** [comment]
Hello, thank you for a change.
But aren't these changes related to JT? We're loading table address, offset, add them and jump - I'm not completely sure why we want to skip it.
Also please add proper test.

**Comment by kaadam** [comment]
Hi @yota9, Sorry for the delayed response.
Started to work on to handle these two patterns maybe you can give me some pointers about them.  
Preprocessing indirect branch we should extract PCRelBase, and JumpTable (label address) + Offset if it is possible.

Considering this pattern, this adr  instruction its address could be PCRelbase, as I tried to follow the original logic maybe it could be "JT" as well. But we only have the address of the entry in sigall_set "section", should we know about the label address of the sigall_set?

```
      //   adr     x6, 0x219fb0 <sigall_set+0x88> => PCRelBase, JT?
      //   add     x6, x6, x14, lsl #2
      //   ldr     w7, [x6]
      //   add     x6, x6, w7, sxtw
      //   br      x6
```
a snippet of the print-cfg:

```
.Ltmp7286 (10 instructions, align : 1)
  CFI State : 0
  Predecessors: .LFT5416
    00000268:   ldp     q5, q6, [x1], #0x20
    0000026c:   stp     q1, q2, [x3], #0x20
    00000270:   and     x3, x3, #0xfffffffffffffff0
    00000274:   sub     x2, x2, #0x20
    00000278:   hint    #0x0 # NOP: 1
    0000027c:   adr     x6, #-365276
    00000280:   add     x6, x6, x14, lsl #2
    00000284:   ldr     w7, [x6]
    00000288:   add     x6, x6, w7, sxtw
    0000028c:   br      x6 # UNKNOWN CONTROL FLOW
  CFI State: 0
```

Binary attached: 
[bubblesort_arm64_static.zip](https://github.com/llvm/llvm-project/files/14758180/bubblesort_arm64_static.zip)

**Comment by yota9** [comment]
Hi @kaadam ! The signal_set is just closest (from above) symbol in the binary, probably it has nothing to do with JT. Consider 0x219fb0 as a base address.

**Comment by paschalis-mpeis** [comment]
Two cases are identified in this patch, and TMU the first of which (`(ShiftVal != 2)`)  is hit by users more often. Virtually any stage-0 binary that is statically linked should hit this.

With the patch as is (ie returning 'false'), BOLT won't be able to build the CFG for such functions, meaning less optimizations but a stable binary regardless.

@kaadam has made some good progress locally, to properly parse these patterns, but it's still incomplete.

So I would suggest that we do this on 2 steps:

#### 1) have a quick workaround in place:
Merge for now something like the latest commit, plus some **added test**:

Any .c file, statically linked with libc triggers the first error.
Maybe we can emit some additional warning before returning false, or use `--print-cfg` or `-v=1` and FileCheck that. 

test.c:
```c
int main() { return 1; }
```

in lit test:
```bash
clang -O0 test.c -static -o out
llvm-bolt out -o out.bolt
```

#### 2) use follow-up patches for a proper solution:
Parse the 2 patterns, extract any relevant info (JumpTable/Offset/Scale/Base), and adjust tests as needed.
The `DefJTBaseAdd` being an `ADR` would need an extra test. There's already good local progress on this direction..

File: bolt/test/AArch64/test-indirect-branch.c [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+//  nop   => nop/adr instead of adrp/add
+//  adr     x13, 0x215a18 <_nl_value_type_LC_COLLATE+0x50>
+//  ldrh    w13, [x13, w12, uxtw #1]
+//  adr     x12, 0x247b30 <__gettextparse+0x5b0>
+//  add     x13, x12, w13, sxth #2
+//  br      x13
+
+
+// REQUIRES: system-linux
+// RUN: %clang %s -o %t.exe -Wl,-q -static -fuse-ld=lld --target=aarch64-linux
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/test-indirect-branch.c:24]: Re `--target=aarch64-linux`, there was a recent change that makes this obsolete. So if merged like that, the tests would fail.

Can you please:
1. rebase to the latest main, which includes a handful of commits that did that change (details if you want here [comment here](https://github.com/llvm/llvm-project/pull/93584#issuecomment-2147063138)),
2. and then replace that with `--target=aarch64-unknown-linux-gnu` ?

File: bolt/test/AArch64/test-indirect-branch.c [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+// RUN: llvm-bolt %t.exe -o %t.bolt --print-cfg \
+// RUN:  --debug 2>&1 | FileCheck --match-full-lines %s
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/test-indirect-branch.c:26]: It looks like the `--debug` flag is making tests very slow?

And IMHU we could 'relax' the assertion a bit with a BOLT-WARNING (using just `err()` as in other places in BOLT), which would allow you removing the `--debug` flag from the test, making it faster.

File: bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp [hunk 3]
```diff
@@ -752,6 +765,20 @@ class AArch64MCPlusBuilder : public MCPlusBuilder {
...
 
+    if (DefJTBaseAdd->getOpcode() == AArch64::ADR) {
+      // TODO: handle that case when we do not have adrp/add pair.
+      // It also occurs when the binary is static.
+      //  adr     x13, 0x215a18 <_nl_value_type_LC_COLLATE+0x50>
+      //  ldrh    w13, [x13, w12, uxtw #1]
+      //  adr     x12, 0x247b30 <__gettextparse+0x5b0>
+      //  add     x13, x12, w13, sxth #2
+      //  br      x13
+      LLVM_DEBUG(
```
Comment (paschalis-mpeis) [inline bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:776]: Maybe we could use just `err()` for a BOLT-WARNING? (same applies to previous pattern. see comment on tests).

File: bolt/test/AArch64/test-indirect-branch.c (hunk 1 above)
Comment (kaadam) [reply bolt/test/AArch64/test-indirect-branch.c]: Good to know. Thanks for you comment. Updated!

File: bolt/test/AArch64/test-indirect-branch.c (hunk 2 above)
Comment (kaadam) [reply bolt/test/AArch64/test-indirect-branch.c]: Yes, probably it's better to use errs() indeed, we have less output.

**Comment by kaadam** [comment]
Seems CIs are happy for now. @yota9 could you take a look at it again please? What do you think about it? Thanks!

**Comment by yota9** [comment]
Hi! I don't really mind to add stubs like this, although I would prefer asm test, since it is too deeply relies on the compiler code generation. Let also @rafaelauler tell his opinion on this :)

File: bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp [hunk 4]
```diff
@@ -706,8 +706,20 @@ class AArch64MCPlusBuilder : public MCPlusBuilder {
     unsigned ShiftVal = AArch64_AM::getArithShiftValue(OperandExtension);
     AArch64_AM::ShiftExtendType ExtendType =
         AArch64_AM::getArithExtendType(OperandExtension);
-    if (ShiftVal != 2)
-      llvm_unreachable("Failed to match indirect branch! (fragment 2)");
+    if (ShiftVal != 2) {
+      // TODO: handle that case where ShiftVal != 2.
```
Comment (paschalis-mpeis) [inline bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:710]: nit: 'handle the pattern where..'

File: bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp [hunk 5]
```diff
@@ -752,6 +764,19 @@ class AArch64MCPlusBuilder : public MCPlusBuilder {
       return true;
     }
 
+    if (DefJTBaseAdd->getOpcode() == AArch64::ADR) {
+      // TODO: handle that case when we do not have adrp/add pair.
+      // It also occurs when the binary is static.
+      //  adr     x13, 0x215a18 <_nl_value_type_LC_COLLATE+0x50>
```
Comment (paschalis-mpeis) [inline bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:770]: nit: '..handle the pattern where there is no adrp...'

**Review by paschalis-mpeis — COMMENTED** [review]
#### Regarding tests:
> I would prefer asm test, since it is too deeply relies on the compiler code generation.

I don't have a strong opinion, but I do agree that an asm specific test would be a better test.


#### Regarding the safety of relaxation of assertions to BOLT-WARNINGS:
With some small local tests, I've seen that BOLT simply won't modify such functions, so we won't have any correctness issues (hence the initial suggestion). But I wanted to be sure we weren't missing any corner cases, so I've discussed this yesterday during BOLT 'Office Hours' with Rafael and Maks.

From the discussion, such workaround would still allow moving the function around as a single piece, but it would not allow modifications within the function itself, which is what we want. The nops elimination pass was mentioned in particular as a potential corner case (there wasn't 100% certainty).

Testing with BOLT shows that after all analyses are complete, when we are ready to `runAllPasses`, any relevant `BinaryFunction` would return false for its `hasCFG()` member function (reflecting just it's `BinaryFunction::State`).
And such `BinaryFunction` would have an empty list of basic blocks, meaning `RemoveNops` or any other intra-procedural pass wouldn't perform any changes that could potentially affect jump table offsets.

So it looks be safe.

---

Other than my above discussion on tests, it LGTM.

**Comment by kaadam** [comment]
Thanks the review for you all, I create an minimized assembly test. I cannot argue with that it deeply depend on how compiler generates the code.

File: bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp (hunk 5 above)
Comment (kaadam) [reply bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp:770]: Thanks for the review. Done.

File: bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp (hunk 4 above)
Comment (kaadam) [reply bolt/lib/Target/AArch64/AArch64MCPlusBuilder.cpp]: Thanks for the review. Done.

**Comment by kaadam** [comment]
> Hi! I don't really mind to add stubs like this, although I would prefer asm test, since it is too deeply relies on the compiler code generation. Let also @rafaelauler tell his opinion on this :)

Hi @yota9, I've updated the PR. I enclosed an asm test instead of C one. Could you take a look at it again, please? Thanks Adam.

File: bolt/test/AArch64/test-indirect-branch.s [hunk 6]
```diff
@@ -0,0 +1,107 @@
+// Test how BOLT handles indirect branch sequence of instructions in
+// AArch64MCPlus builder.
+// This test checks that case when we have no shift amount after add
+// instruction. This pattern comes from libc, so needs to build '-static'
+// binary to reproduce the issue easily.
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/test-indirect-branch.s:5]: nit: maybe adjust a bit these comments from the previous c test.

**Review by paschalis-mpeis — APPROVED** [review]

**Comment by yota9** [comment]
LGTM, but maybe handle nop+adr case in this patch? It shouldn't be difficult

**Comment by kaadam** [comment]
> LGTM, but maybe handle nop+adr case in this patch? It shouldn't be difficult

Hi @yota9, Thanks for your comment. So You mean that to also detect 'nop' after adr instruction in 'analyzeIndirectBranchFragment' following this pattern below? Or are you thinking of a completely different pattern? 
```
  nop   => nop/adr instead of adrp/add
  adr     x13, 0x215a18 <_nl_value_type_LC_COLLATE+0x50>
  ldrh    w13, [x13, w12, uxtw #1]
  adr     x12, 0x247b30 <__gettextparse+0x5b0>
  add     x13, x12, w13, sxth #2
  br      x13 ```

File: bolt/test/AArch64/test-indirect-branch.s [hunk 7]
```diff
@@ -0,0 +1,110 @@
+// Test how BOLT handles indirect branch sequence of instructions in
+// AArch64MCPlus builder.
+// This test checks the pattern where there is no shift amount after add
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/test-indirect-branch.s:3]: nit: replace:
```cpp
// This test checks the pattern where there is no shift amount after add
// instruction. The pattern come from libc, it can be reproduced with
// a 'static' built binary.
```

with something like (first line is an empty comment to separate from above):
```cpp
//
// Pattern 1: there is no shift amount after the 'add' instruction.

```

File: bolt/test/AArch64/test-indirect-branch.s [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+// instruction. The pattern come from libc, it can be reproduced with
+// a 'static' built binary.
+//
+//   adr     x6, 0x219fb0 <sigall_set+0x88>
+//   add     x6, x6, x14, lsl #2
+//   ldr     w7, [x6]
+//   add     x6, x6, w7, sxtw => no shift amount
+//   br      x6
+//
+// It also tests another case where there is no adrp/add pair.
```
Comment (paschalis-mpeis) [inline bolt/test/AArch64/test-indirect-branch.s:13]: nit: replace
```cpp
// It also tests another case where there is no adrp/add pair.
// The pattern also come from libc, and it only represents in the binary
// if the lld linker is used to create the static binary.
// It doesn't occur with GCC ld linker.
```

with something like:
```cpp
// Pattern 2: nop/adr pair is used in place of adrp/add
```

File: bolt/test/AArch64/test-indirect-branch.s (hunk 7 above)
Comment (kaadam) [reply bolt/test/AArch64/test-indirect-branch.s]: Done.

File: bolt/test/AArch64/test-indirect-branch.s (hunk 8 above)
Comment (kaadam) [reply bolt/test/AArch64/test-indirect-branch.s]: Done.

**Comment by kaadam** [comment]
@yota9 @paschalis-mpeis I've minimized the test case (just reorganized and removed superfluous instructions). Updated the PR (commit) description as well. What do you think?

**Comment by yota9** [comment]
@kaadam Hi, could you please reformat test to smth like:

```
  .section .text
  .align 4
  .globl _start
  .type  _start, %function
_start:
  bl test1
  bl test2

 .globl test1
 .type test2, %function
test1:
  adr     x3, jump_table
  ldrh    w3, [x3, x1, lsl #1]
  adr     x1, .test1_0
  add     x3, x1, w3, sxth #2
  br      x3

test1_0:
  ret
test1_1:
  ret

 .globl test2
 .type test2, %function
test2:
  nop
  adr     x3, jump_table
  ldrh    w3, [x3, x1, lsl #1]
  adr     x1, .case0
  add     x3, x1, w3, sxth #2

  .section .rodata,"a",@progbits
jump_table:
  .hword  (.case0-.case0)>>2
  .hword  (.case1-.case0)>>2

test2_0:
  ret
rest2_1:
  ret
test2_2:
  ret

datatable:
  .word test2_0-datatable
  .word test2_1-datatable
  .word test2_2-datatable
```

So they won't be connected, this way it would be much more readable

File: bolt/test/AArch64/test-indirect-branch.s (hunk 8 above)
Comment (paschalis-mpeis) [reply bolt/test/AArch64/test-indirect-branch.s]: Hey @kaadam ,
thanks for the changes, looks good.
Applying the latest suggestion from @yota9 and then we are good to go!

**Comment by kaadam** [comment]
@yota9 @paschalis-mpeis Thanks for your review. I've updated the test based on yota suggestion. I had to pass  '--strict' option to to llvm-bolt. (Since I got 'BOLT-ERROR: Cannot relax adr in non-simple function test1/test2', and test failed). Could you take a look at it again, please?

**Review by yota9 — APPROVED** [review]
Hi! Thanks for test changing. I'm approving this tmp patch since handling the functions with IndirectBranchType::UNKNOWN is still better than aborting on these cases.

**Comment by kaadam** [comment]
> Hi! Thanks for test changing. I'm approving this tmp patch since handling the functions with IndirectBranchType::UNKNOWN is still better than aborting on these cases.

Thanks @yota9!
I'm not allowed to submit the PR, @yota9, @paschalis-mpeis may I ask one of you to merge the PR, if the PR has met the criteria for merging?
