### PR TITLE
[FunctionAttrs] Improve handling of alias-preserving intrinsic calls

### LINKED ISSUE #68270: Inferring function argument attributes incorrectly ignoes (sets `readnone`) intrinsics that return aliasing pointers
# Steps to reproduce

Run `opt -passes='default<O3>'` on the following LLVM IR (I haven't managed to scope this down, but I think the function attributor has something to do with it)
```llvm
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8"
target triple = "amdgcn--"

define amdgpu_kernel void @buffer_creation_attributor_fail(ptr noalias %x, ptr noalias %y) {                                                                                     
  %x.rsrc = call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr %x, i16 0, i32 4, i32 822243328)
  %y.rsrc = call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr %y, i16 0, i32 4, i32 822243328)
  %v = call float @llvm.amdgcn.raw.ptr.buffer.load.f32(ptr addrspace(8) %x.rsrc, i32 0, i32 0, i32 0)
  call void @llvm.amdgcn.raw.ptr.buffer.store.f32(float %v, ptr addrspace(8) %y.rsrc, i32 0, i32 0, i32 0)
  ret void
}

declare ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr nocapture readnone, i16, i32, i32) #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare float @llvm.amdgcn.raw.ptr.buffer.load.f32(ptr addrspace(8) nocapture readonly, i32, i32, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: write)
declare void @llvm.amdgcn.raw.ptr.buffer.store.f32(float, ptr addrspace(8) nocapture writeonly, i32, i32, i32 immarg) #2

attributes #0 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #2 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: write) }
```

# Expected results
```llvm
define amdgpu_kernel void @buffer_creation_attributor_fail(ptr noalias nocapture readonly %x, ptr noalias nocapture writeonly %y) local_unnamed_addr #0 {
...
}
```

Note the `readonly` and `writeonly` attributions

# Actual results
```llvm
define amdgpu_kernel void @buffer_creation_attributor_fail(ptr noalias nocapture readnone %x, ptr noalias nocapture readnone %y) local_unnamed_addr #0 {
...
}
```

Note that the function arguments are incorrectly labelled `readnone`

### PR DESCRIPTION
**Pull request by krzysz00**
Fixes #68270

The function attribute analysis handles many instructions, like addrspacecast, which do not themselves read or write memory but which transform pointers into other values in the same alias set.

There are intrinsic functions, such as ptrmask or the AMDGPU-specific make.buffer.rsrc, which also preserve membership in alias sets without capturing. This commit adds the addrspacecast-like behavior to these calls.

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
This looks like a reasonable improvement to *precision*, but this is not a bug fix.

An argument that gets returned by a function must not be marked as `nocapture`. The return value counts as a capture. The current attributes on the `llvm.amdgcn.make.buffer.rsrc` intrinsic are incorrect.

**Comment by nikic** [comment]
> This looks like a reasonable improvement to _precision_, but this is not a bug fix.

Reading more carefully, you still fall through to the usual behavior, so it's not an improvement to precision either. So this appears to only be a workaround for an incorrect intrinsic annotation.

**Comment by krzysz00** [comment]
Huh

In which case, I'm confused by why the function in ValueTracking mentions `WithoutCapturing`.

And by what the semantics of `nocapture` are in general - my sense of it was that a capture involves storing a pointer somewhere such that it might be used after its SSA value is out of scope, and so nocapture indicates a lack of that behavior.

It's entirely possible that I'll want to go fix up `make.buffer.rsrc` and then also commit this as a precision improvement.

**Comment by nikic** [comment]
> In which case, I'm confused by why the function in ValueTracking mentions `WithoutCapturing`.

The name is a bit confusing, it would be more accurate to say without *other* capturing. The point of the function is to handle functions that only capture via the return value, as that's not something that can currently be expressed with attributes.

> And by what the semantics of `nocapture` are in general - my sense of it was that a capture involves storing a pointer somewhere such that it might be used after its SSA value is out of scope, and so nocapture indicates a lack of that behavior.

See https://llvm.org/docs/LangRef.html#pointercapture, especially the comments in the first example. Your description is basically right (at least for the provenance escape part of "capture"), but applies beyond stores to memory. What matters is that the pointer outlives the call in some way.

**Comment by krzysz00** [comment]
@nikic I've updated the commit messaged and removed the fallthrough, thus making this a precision-improving PR

**Comment by krzysz00** [comment]
Also, any insight on how to make the equivalent change to the attributor?

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 1]
```diff
@@ -654,6 +654,17 @@ determinePointerAccessAttrs(Argument *A,
...
 
+      // Some intrinsics (for instance ptrmask) do not capture their results,
+      // but return results thas alias their pointer argument, and thus should
+      // be handled like GEP or addrspacecast above.
+      if (isIntrinsicReturningPointerAliasingArgumentWithoutCapturing(
+              &CB, /*MustPreserveNullness=*/false)) {
+        for (Use &UU : CB.uses())
+          if (Visited.insert(&UU).second)
+            Worklist.push_back(&UU);
+        continue;
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp:665]: I think strictly speaking this continue here should be replaced by an `else` after the if.

That is, this code is a replacement for the capture check directly below it, but it does not replace the memory checks further down.

I don't think your code is *currently* incorrect because all functions in isIntrinsicReturningPointerAliasingArgumentWithoutCapturing() don't perform memory accesses on the pointer either, but as that isn't part of the contract of that functions, it may be that it becomes incorrect in the future.

File: llvm/test/Transforms/FunctionAttrs/AMDGPU/make-buffer-rsrc.ll [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+;
+  %p.rsrc = call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr %p, i16 0, i32 4, i32 822243328)
+  %q.rsrc = call ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr %q, i16 0, i32 4, i32 822243328)
+  %v = call i8 @llvm.amdgcn.raw.ptr.buffer.load.i8(ptr addrspace(8) %p.rsrc, i32 0, i32 0, i32 0)
+  call void @llvm.amdgcn.raw.ptr.buffer.store.i8(i8 %v, ptr addrspace(8) %q.rsrc, i32 0, i32 0, i32 0)
+  ret void
+}
+
+; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
+declare ptr addrspace(8) @llvm.amdgcn.make.buffer.rsrc.p0(ptr nocapture readnone, i16, i32, i32) #0
```
Comment (nikic) [inline llvm/test/Transforms/FunctionAttrs/AMDGPU/make-buffer-rsrc.ll:35]: Drop nocapture here to match new intrinsic signature?

**Comment by nikic** [comment]
> Also, any insight on how to make the equivalent change to the attributor?

Does it need any changes? I'd expect that Attributor uses CaptureTracking, which already handles this.

File: llvm/test/Transforms/FunctionAttrs/AMDGPU/make-buffer-rsrc.ll [hunk 3]
```diff
@@ -0,0 +1,47 @@
+; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-attributes
+; RUN: opt -passes=function-attrs -S < %s | FileCheck --check-prefixes=COMMON,FNATTRS %s
+; RUN: opt -passes=attributor-light -S < %s | FileCheck --check-prefixes=COMMON,ATTRIBUTOR %s
+
+target triple = "amdgcn-amd-amdhsa"
```
[the remark this answers is not in the document]
Comment (krzysz00) [reply llvm/test/Transforms/FunctionAttrs/AMDGPU/make-buffer-rsrc.ll:5]: Huh, then yeah, we can probably make this not target-specific, but I vaguely remember running into issues with AMDGPU-specific tests before that made me cautious.

[the remark this answers is not in the document]
Comment (nikic) [reply llvm/test/Transforms/FunctionAttrs/AMDGPU/make-buffer-rsrc.ll:5]: As long as dropping the triple doesn't make the test fail, you should be good.

**Comment by nikic** [comment]
Looks like this needs a rebase.

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 4]
```diff
@@ -654,7 +654,15 @@ determinePointerAccessAttrs(Argument *A,
       // must be a data operand (e.g. argument or operand bundle)
       const unsigned UseIndex = CB.getDataOperandNo(U);
 
-      if (!CB.doesNotCapture(UseIndex)) {
+      // Some intrinsics (for instance ptrmask) do not capture their results,
+      // but return results thas alias their pointer argument, and thus should
```
Comment (nikic) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp:658]:
```suggestion
      // but return results that alias their pointer argument, and thus should
```

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp (hunk 4 above)
Comment (krzysz00) [reply llvm/lib/Transforms/IPO/FunctionAttrs.cpp:658]: ... Apparently I forgot to `git commit --amend` in the typo fix. Should I make a new PR for that or?
