### PR TITLE
[Clang][Sema] Properly get captured 'this' pointer in lambdas with an explicit object parameter in constant evaluator

### LINKED ISSUE #80997: lambda with `this auto` that captures `this` in a member function is not an integral constant expression
https://godbolt.org/z/azqxac8xE
```cpp
struct S { 
  int i = 42;
  constexpr auto f() { 
    return [this](this auto) { 
      return this->i;
    }(); 
  }; 
};

static_assert(S().f() == 42);
```
Clang rejects the above code with:

```
<source>:10:15: error: static assertion expression is not an integral constant expression
   10 | static_assert(S().f() == 42);
      |               ^~~~~~~~~~~~~
<source>:5:14: note: use of 'this' pointer is only allowed within the evaluation of a call to a 'constexpr' member function
    5 |       return this->i;
      |              ^
```
If we remove `this auto` then [compile fine](https://godbolt.org/z/Gb8qE7Whh), the two should be equivalent right?
Not really sure what the standards say about this.

### PR DESCRIPTION
**Pull request by Sirraide**
There were some bugs wrt explicit object parameters in lambdas in the constant evaluator:
- The code evaluating a `CXXThisExpr` wasn’t checking for explicit object parameters at all and thus assumed that there was no `this` in the current context because the lambda didn’t have one, even though we were in a member function and had captured its `this`.
- The code retrieving captures as lvalues *did* account for explicit object parameters, but it did not handle the case of the explicit object parameter being passed by value rather than by reference.

This fixes #80997.

### CODE REVIEW

File: clang/lib/AST/ExprConstant.cpp [hunk 1]
```diff
@@ -8480,6 +8480,54 @@ class LValueExprEvaluator
...
+    if (Self->getType()->isReferenceType()) {
+      APValue *RefValue = Info.getParamSlot(Info.CurrentCall->Arguments, Self);
+      Result.setFrom(Info.Ctx, *RefValue);
+    } else {
+      auto *VD = Info.CurrentCall->Arguments.getOrigParam(Self);
+      auto *Frame =
+          Info.getCallFrameAndDepth(Info.CurrentCall->Arguments.CallIndex)
+              .first;
+      auto Version = Info.CurrentCall->Arguments.Version;
+      Result.set({VD, Frame->Index, Version});
```
Comment (Sirraide) [inline clang/lib/AST/ExprConstant.cpp:8509]: Not entirely sure this is the intended way to do this candidly, but I couldn’t figure out how else I should obtain an lvalue to the parameter here. This is based on `LValueExprEvaluator::VisitVarDecl`, where this entire function was also originally located. Is there perhaps some other helper that I missed?

**Comment by erichkeane** [comment]
> Should I fix the conflict in the release notes myself, or should that be done when this gets merged? Because at least in my experience, merge conflicts in the release notes just keep reappearing if a pr stays open for some time...

Lets hang out on that for a bit... Unfortunately you seem to have 'stepped in it' on this patch, so we might need to delay committing for a little while.  But updates are coming.

**Comment by Sirraide** [comment]
@cor3ntin ping

**Comment by Sirraide** [comment]
@cor3ntin ping

File: clang/lib/AST/ExprConstant.cpp [hunk 2]
```diff
@@ -8480,6 +8480,54 @@ class LValueExprEvaluator
...
+    Result = *Info.CurrentCall->This;
+
+  // ... then update it to refer to the field of the closure object
+  // that represents the capture.
+  if (!HandleLValueMember(Info, E, Result, FD))
+    return false;
+
+  // And if the field is of reference type (or if we captured '*this' by
+  // reference if this is a lambda), update 'Result' to refer to what
+  // the field refers to.
```
Comment (cor3ntin) [inline clang/lib/AST/ExprConstant.cpp:8521]:
```suggestion
  // And if the field is of reference type (or if we captured '*this' by
  // reference), update 'Result' to refer to what
  // the field refers to.
```

File: clang/lib/AST/ExprConstant.cpp [hunk 3]
```diff
@@ -8480,6 +8480,54 @@ class LValueExprEvaluator
 };
 } // end anonymous namespace
 
+/// Get an lvalue to a field of a lambda's closure type.
+static bool GetLambdaCaptureAsLValue(EvalInfo &Info, const Expr *E,
```
[the remark this answers is not in the document]
Comment (Sirraide) [reply clang/lib/AST/ExprConstant.cpp:8484]: That’s probably a better name, yeah; `GetLambdaCaptureAsLValue` is rather clumsy, but I couldn’t think of anything better myself.

File: clang/lib/AST/ExprConstant.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/lib/AST/ExprConstant.cpp:8508]: I don't know of a helper to do this (I couldn't spot one when I went looking), so it's good that you factored this out.

Comment (Sirraide) [reply clang/lib/AST/ExprConstant.cpp:8508]: I could make this a separate helper function, but it’s only used here from what I can tell (the code in `LValueExprEvaluator::VisitVarDecl` where I apparently got this from is quite a bit more complicated and does more iirc), so I personally don’t think it’s really necessary.

Comment (AaronBallman) [reply clang/lib/AST/ExprConstant.cpp:8513]: Sorry, I meant that the current factoring is good (we're able to call this from the two places it matters).

Comment (Sirraide) [reply clang/lib/AST/ExprConstant.cpp:8513]: Ah, I see now

**Comment by Sirraide** [comment]
@cor3ntin ping

**Comment by Sirraide** [comment]
Just requested more reviews real quick because this has been open for a month now, and Corentin apparently won’t be able to review prs until April, and I’d also feel a bit bad if I kept pinging just him about this over and over again...

**Review by cor3ntin — COMMENTED** [review]
LGTM but I'll let @AaronBallman approve as I'm in a flight with bad internet today.

File: clang/lib/AST/ExprConstant.cpp [hunk 4]
```diff
@@ -9037,45 +9055,46 @@ class PointerExprEvaluator
...
         Info.FFDiag(E, diag::note_constexpr_this) << E->isImplicit();
       else
         Info.FFDiag(E);
+    };
+
+    // Can't look at 'this' when checking a potential constant expression.
+    if (Info.checkingPotentialConstantExpression())
       return false;
+
+    const bool IsExplicitLambda =
```
Comment (AaronBallman) [inline clang/lib/AST/ExprConstant.cpp:9069]:
```suggestion
    bool IsExplicitLambda =
```

File: clang/lib/AST/ExprConstant.cpp [hunk 5]
```diff
@@ -8485,6 +8485,53 @@ class LValueExprEvaluator
...
+    auto *Self = MD->getParamDecl(0);
+    if (Self->getType()->isReferenceType()) {
+      APValue *RefValue = Info.getParamSlot(Info.CurrentCall->Arguments, Self);
+      Result.setFrom(Info.Ctx, *RefValue);
+    } else {
+      auto *VD = Info.CurrentCall->Arguments.getOrigParam(Self);
+      auto *Frame =
+          Info.getCallFrameAndDepth(Info.CurrentCall->Arguments.CallIndex)
+              .first;
+      auto Version = Info.CurrentCall->Arguments.Version;
```
Comment (AaronBallman) [inline clang/lib/AST/ExprConstant.cpp:8512]: Should spell these types out because they're not spelled out in the initialization.

File: clang/lib/AST/ExprConstant.cpp [hunk 6]
```diff
@@ -8485,6 +8485,53 @@ class LValueExprEvaluator
...
+  if (MD->isStatic()) {
+    assert(Info.CurrentCall->This == nullptr &&
+           "This should not be set for a static call operator");
+    return false;
+  }
+
+  // Start with 'Result' referring to the complete closure object...
+  if (MD->isExplicitObjectMemberFunction()) {
+    // Self may be passed by reference or by value.
+    auto *Self = MD->getParamDecl(0);
```
Comment (AaronBallman) [inline clang/lib/AST/ExprConstant.cpp:8503]: Should spell this type out as well

**Review by AaronBallman — APPROVED** [review]
LGTM aside from some coding style guideline nits

File: clang/lib/AST/ExprConstant.cpp (hunk 5 above)
Comment (Sirraide) [reply clang/lib/AST/ExprConstant.cpp:8512]: I probably intended to come back later because I sort of expected there to be a helper that I missed.
