### PR TITLE
[clang-tidy] Fixes to readability-implicit-bool-conversion

### LINKED ISSUE #71848: [clang-tidy] `readability-implicit-bool-conversion` suggests invalid fix
When running and applying the suggestions of readability-implicit-bool-conversion on the following code:
```
int main()
{
    bool foo;
    return( foo );
}
```

We get the following result:

```

int main()
{
    bool foo;
    returnstatic_cast<int>(( foo ));
}
```

godbolt: https://godbolt.org/z/bzbbbevsE

### PR DESCRIPTION
**Pull request by PiotrZSL**
- Fixed issue with invalid code being generated when static_cast is put into fix, and no space were added before it.
- Fixed issue with duplicate parentheses being added when double implicit cast is used.

Closes #71848

### CODE REVIEW

File: clang-tools-extra/clang-tidy/readability/ImplicitBoolConversionCheck.cpp [hunk 1]
```diff
@@ -173,16 +173,30 @@ StringRef getEquivalentBoolLiteralForExpr(const Expr *Expression,
...
+bool needsSpacePrefix(SourceLocation Loc, ASTContext &Context) {
+  SourceRange PrefixRange(Loc.getLocWithOffset(-1), Loc);
+  StringRef SpaceBeforeStmtStr = Lexer::getSourceText(
+      CharSourceRange::getCharRange(PrefixRange), Context.getSourceManager(),
+      Context.getLangOpts(), nullptr);
+  if (SpaceBeforeStmtStr.empty())
+    return true;
+
+  const StringRef AllowedCharacters(" \t\n\v\f\r(){}[]<>;,+=-|&~!^*/");
+  return SpaceBeforeStmtStr.rtrim(AllowedCharacters).size() ==
```
Comment (HerrCai0907) [inline clang-tools-extra/clang-tidy/readability/ImplicitBoolConversionCheck.cpp:185]: use `SpaceBeforeStmtStr.back()` and `SpaceBeforeStmtStr.front()`

Comment (PiotrZSL) [reply clang-tools-extra/clang-tidy/readability/ImplicitBoolConversionCheck.cpp]: Done

**Review by HerrCai0907 — APPROVED** [review]
