### PR TITLE
[clang-repl] Fix RuntimeInterfaceBuilder for 32-bit systems

### LINKED ISSUE #94994: clang-repl value unit test fails on 32 bit Arm
Since https://github.com/llvm/llvm-project/pull/89811 landed one of the unit tests has been failing on Arm 32 bit:
```
******************** TEST 'Clang-Unit :: Interpreter/./ClangReplInterpreterTests/10/26' FAILED ********************
Script(shard):
--
GTEST_OUTPUT=json:/home/tcwg-buildbot/worker/clang-armv8-quick/stage1/tools/clang/unittests/Interpreter/./ClangReplInterpreterTests-Clang-Unit-2678467-10-26.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=26 GTEST_SHARD_INDEX=10 /home/tcwg-buildbot/worker/clang-armv8-quick/stage1/tools/clang/unittests/Interpreter/./ClangReplInterpreterTests
--
Script:
--
/home/tcwg-buildbot/worker/clang-armv8-quick/stage1/tools/clang/unittests/Interpreter/./ClangReplInterpreterTests --gtest_filter=InterpreterTest.Value
--
../llvm/clang/unittests/Interpreter/InterpreterTest.cpp:293: Failure
Expected equality of these values:
  V1.getInt()
    Which is: 0
  42
```
It does not fail on AArch64. It does fail under qemu emulation too, but with different results. Which points to some UB in the program.

### PR DESCRIPTION
**Pull request by weliveindetail**
When generating runtime interface bindings, extend integral types to the native register size rather than 64-bit per se

Fixes #94994

### CODE REVIEW

File: clang/lib/Interpreter/Interpreter.cpp [hunk 1]
```diff
@@ -673,10 +673,12 @@ class InterfaceKindVisitor
...
 
 private:
-  // Force cast these types to uint64 to reduce the number of overloads of
-  // `__clang_Interpreter_SetValueNoAlloc`.
+  // Force cast these types to the uint that fits the register size. That way we
+  // reduce the number of overloads of `__clang_Interpreter_SetValueNoAlloc`.
   void HandleIntegralOrEnumType(const Type *Ty) {
-    TypeSourceInfo *TSI = Ctx.getTrivialTypeSourceInfo(Ctx.UnsignedLongLongTy);
+    uint64_t PtrBits = Ctx.getTypeSize(Ctx.VoidPtrTy);
+    QualType UIntTy = Ctx.getBitIntType(true, PtrBits);
```
Comment (vgvassilev) [inline clang/lib/Interpreter/Interpreter.cpp:680]:
```suggestion
    QualType UIntTy = Ctx.getBitIntType(/*Unsigned=*/true, PtrBits);
```

**Review by vgvassilev — APPROVED** [review]
Oh, that's a good catch. Any chance of adding a test case? Maybe something like:

```enum X : short {...}```?

**Comment by weliveindetail** [comment]
> Any chance of adding a test case?

We could add a lot more tests in general, but I don't think this specific detail requires a dedicated one. It's a fix for an existing bug, so we have coverage already.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by eymay** [comment]
Great work, I can imagine how hard it would be to uncover it!

Small note: I think you may also want to remove the Arm macro guards that mask the unittest in the same commit, as you did in the previous [PR](https://github.com/llvm/llvm-project/pull/96900/files#diff-9b27f347e7ca15f949d4453d24eeca3a6f841a1f7873c86eb98aa44192faaf15)

**Comment by DavidSpickett** [comment]
Also remove the comment that links to https://github.com/llvm/llvm-project/issues/94994 and add `Fixes #94994` to the commit message.

**Comment by weliveindetail** [comment]
Thanks for your feedback everyone!

**Review by DavidSpickett — APPROVED** [review]
