### PR TITLE
[Scalarizer] Fix to only scalarize if intrinsic was marked as isTriviallyScalarizable

### LINKED ISSUE #113624: [Scalarizer][Bug] Only scatter/gather in extract value for trivially vectorizable intrinsics
## Issue
Today we scatter/gather all extract values of struct return types. Thats out of lock step with how we split the call. The fix is to check if the call was trivially vectorizable before. handling the extract element case.

> Thats a bug.  Adding to `isTriviallyScalarizable` is not the right fix. Whats going on is because `uadd.with.overflow` isn't in `isTriviallyScalarizable` we aren't splitting the calls so when we call `Scatterer Op0` it isn't operating on the right type. A correct fix wouldn't  replace extract element unless we scalarized the call.

## Test case:
```
define <3 x i32> @test_(<3 x i32> %a, <3 x i32> %b) {
  %r = call { <3 x i32>, <3 x i1> } @llvm.uadd.with.overflow.v3i32(<3 x i32> %b, <3 x i32> %b)
  %el = extractvalue { <3 x i32>, <3 x i1> } %r, 0
  ret <3 x i32> %el
}
```

```
./build/bin/opt -passes='function(scalarizer)' ./build/test_fail.ll -S
opt: ./llvm-project/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From *) [To = llvm::VectorType, From = llvm::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

_Originally posted by @farzonl in https://github.com/llvm/llvm-project/issues/111569#issuecomment-2436239121_

### PR DESCRIPTION
**Pull request by farzonl**
fixes #113624

### CODE REVIEW

**Review by mariusz-sikora-at-amd — APPROVED** [review]
Thanks for the fix !

File: llvm/lib/Transforms/Scalar/Scalarizer.cpp [hunk 1]
```diff
@@ -1084,6 +1084,17 @@ bool ScalarizerVisitor::visitExtractValueInst(ExtractValueInst &EVI) {
...
+    Function *F = CI->getCalledFunction();
+    if (!F)
+      return false;
+    Intrinsic::ID ID = F->getIntrinsicID();
+    if (ID == Intrinsic::not_intrinsic || !isTriviallyScalarizable(ID))
+      return false;
+    // Note: Fall through means Operand is a`CallInst` and it is defined in
+    // `isTriviallyScalarizable`.
+  } else
+    return false;
```
Comment (jayfoad) [inline llvm/lib/Transforms/Scalar/Scalarizer.cpp:1097]: Will you ever see non-intrinsic calls here? If so, please add a test case for that.

Also nit: the "else" clause should have braces if the "if" clause has braces.

File: llvm/lib/Transforms/Scalar/Scalarizer.cpp [hunk 2]
```diff
@@ -1084,6 +1084,17 @@ bool ScalarizerVisitor::visitExtractValueInst(ExtractValueInst &EVI) {
   ValueVector Res;
   if (!isStructOfMatchingFixedVectors(OpTy))
     return false;
+  if (CallInst *CI = dyn_cast<CallInst>(Op)) {
```
Comment (jayfoad) [inline llvm/lib/Transforms/Scalar/Scalarizer.cpp:1087]: Can you just handle `IntrinsicInst` here, instead of manually checking for a known callee and looking up the id?

Comment (farzonl) [reply llvm/lib/Transforms/Scalar/Scalarizer.cpp:1087]: Still need to lookup the id, but yes this could be `IntrinsicInst`.
