### PR TITLE
[Clang] Use correct evaluation contexts when instantiating a var without initializer

### LINKED ISSUE #140622: "reference to local variable declared in enclosing function" linked with template instantiation
```cpp
template <typename To>
struct L {
  int operator()(const char*) const { return 1; }
};
template <typename To>
constexpr L<To> l;

int main() {
  constexpr auto LOCAL = "hello";
  LOCAL, l<float>("");
}
```
`clang++ -std=c++23`
```
<source>:10:3: error: reference to local variable 'LOCAL' declared in enclosing function 'main'
   10 |   LOCAL, l<float>("");
      |   ^
<source>:10:10: note: in instantiation of variable template specialization 'l<float>' requested here
   10 |   LOCAL, l<float>("");
      |          ^
<source>:9:18: note: 'LOCAL' declared here
    9 |   constexpr auto LOCAL = "hello";
      |                  ^
<source>:10:3: warning: left operand of comma operator has no effect [-Wunused-value]
   10 |   LOCAL, l<float>("");
      |   ^~~~~
1 warning and 1 error generated.
Compiler returned: 1
```

Tested with clang 20, clang trunk, see https://godbolt.org/z/hhxhqrxbo. GCC accepts it.

### LINKED ISSUE #140632: Valid code fails with "reference to local variable declared in enclosing function"
```cpp
#include <array>
#include <ranges>

int main() {
    constexpr auto v = std::array{1, 2, 3, 4, 5, 6};
    for (auto const& [t0, t1, t2] : v | std::views::adjacent<3>) {
    }
}
```
> error: reference to local variable 'v' declared in enclosing function 'main'

Works in GCC 15.1
Error in clang 20.1.0
Works if you remove constexpr

[godbolt link](https://godbolt.org/z/7d3aW5Y4b)

### PR DESCRIPTION
**Pull request by cor3ntin**
The evaluation context was improperly set up, such that we were trying to set up cleanups for a global variable at the point of use, which led to incorrect diagnostics about the variable not being capturable.

Fixes #140632
Fixes #140622

### CODE REVIEW

**Review by zyn0217 — APPROVED** [review]
thanks

File: clang/test/CodeGenCXX/cxx1y-variable-template.cpp [hunk 1]
```diff
@@ -18,6 +18,16 @@ int init_arr();
 template<typename T> template<typename U> template<typename V> int Outer<T>::Inner<U>::arr[sizeof(T) + sizeof(U) + sizeof(V)] = { init_arr() };
 int *p = Outer<char[100]>::Inner<char[20]>::arr<char[3]>;
 
+//CHECK: @_ZN8GH1406221gIiEE = linkonce_odr constant %"struct.GH140622::S" zeroinitializer
+namespace GH140622 {
+template <typename> struct S {};
+template <typename T> constexpr S<T> g;
+void test() {
+    constexpr auto x = 42;
```
Comment (shafik) [inline clang/test/CodeGenCXX/cxx1y-variable-template.cpp:26]: As I pointed out here: https://github.com/llvm/llvm-project/issues/140622#issuecomment-2892633775

this also happens when the local is *const*, so it is worth testing that case and the non const/constexpr case.

**Review by shafik — COMMENTED** [review]
It would also be nice to get a reduction for: https://github.com/llvm/llvm-project/issues/140632 and see if we can add a test for that if it looks significantly different from the other cases.
