### PR TITLE
[Clang] Fix dependency computation for pack indexing expression

### LINKED ISSUE #91884: C++26 Pack-indexing have BUG
```cpp
auto print(auto&&...args){
    [&]<std::size_t... idx>(std::index_sequence<idx...>){
        std::print("{} {} {} {}",args...[idx]...);
    }(std::make_index_sequence<sizeof...(args)>());
}

int main(){
    print(1,2,3,"🤣");
}
```

OK ! [godbolt..](https://godbolt.org/z/3KWWjb39T)

```cpp
auto print(auto&&...args){
    [&]<std::size_t... idx>(std::index_sequence<idx...>){
        (std::print("{} ",args...[idx]), ...);
    }(std::make_index_sequence<sizeof...(args)>());
}

int main(){
    print(1,2,3,"🤣");
}
```

Error ! [godbolt..](https://godbolt.org/z/Gfv5xd7f1)

If changed to:

```cpp
void print_one(auto& arg){
    std::print("{} ", arg);
}

void print(auto&&...args){
    [&]<std::size_t... idx>(std::index_sequence<idx...>){
        (::print_one<decltype((args...[idx]))>(args...[idx]), ...);
    }(std::make_index_sequence<sizeof...(args)>());
}
```

OK ! [godbolt..](https://godbolt.org/z/Es43szsnG)

Seems to be moving out? But it doesn't matter. It's a BUG.

### LINKED ISSUE #91885: [Clang] Expansion of pack indexing expression that is a pack in a lambda triggers ICE
It seems that some branches are missing for this case. [Godbolt link](https://godbolt.org/z/8YK9MGYdb).
```C++
#include <cstddef>
#include <utility>

void operate_one(auto&&) {}

void operate_multi(auto&&...args)
{
    [&]<std::size_t... idx>(std::index_sequence<idx...>)
    {
        (::operate_one(args...[idx]), ...);
    }(std::make_index_sequence<sizeof...(args)>{});
}

int main()
{
    ::operate_multi(1, 2, 3);
}
```

```
mangling a placeholder type
UNREACHABLE executed at /root/llvm-project/clang/lib/AST/ItaniumMangle.cpp:3339!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++26 <source>
1.	<eof> parser at end of file
2.	<source>:6:6: instantiating function definition 'operate_multi<int, int, int>'
3.	<source>:4:6: instantiating function definition 'operate_one<<dependent type> &>'
4.	<source>:4:6: LLVM IR generation of declaration 'operate_one'
5.	<source>:4:6: Mangling declaration 'operate_one'
 #0 0x00000000039a02d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39a02d8)
 #1 0x000000000399dfbc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x399dfbc)
 #2 0x00000000038ef028 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000752ae9242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000752ae92969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000752ae9242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000752ae92287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00000000038fa34a (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x38fa34a)
 #8 0x000000000774cdb4 (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) ItaniumMangle.cpp:0:0
 #9 0x0000000007743d03 (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) ItaniumMangle.cpp:0:0
#10 0x0000000007762408 (anonymous namespace)::CXXNameMangler::mangleTemplateArg(clang::TemplateArgument, bool) ItaniumMangle.cpp:0:0
#11 0x000000000775f59f (anonymous namespace)::CXXNameMangler::mangleTemplateArgs(clang::TemplateName, clang::TemplateArgumentList const&) ItaniumMangle.cpp:0:0
#12 0x0000000007740843 (anonymous namespace)::CXXNameMangler::mangleNameWithAbiTags(clang::GlobalDecl, llvm::SmallVector<llvm::StringRef, 4u> const*) ItaniumMangle.cpp:0:0
#13 0x000000000774144a (anonymous namespace)::CXXNameMangler::mangleName(clang::GlobalDecl) ItaniumMangle.cpp:0:0
#14 0x000000000775875d (anonymous namespace)::CXXNameMangler::mangleFunctionEncoding(clang::GlobalDecl) ItaniumMangle.cpp:0:0
#15 0x000000000775c70e (anonymous namespace)::ItaniumMangleContextImpl::mangleCXXName(clang::GlobalDecl, llvm::raw_ostream&) ItaniumMangle.cpp:0:0
#16 0x0000000007781523 clang::MangleContext::mangleName(clang::GlobalDecl, llvm::raw_ostream&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x7781523)
#17 0x0000000003d743dc getMangledNameImpl(clang::CodeGen::CodeGenModule&, clang::GlobalDecl, clang::NamedDecl const*, bool) CodeGenModule.cpp:0:0
#18 0x0000000003d85fad clang::CodeGen::CodeGenModule::getMangledName(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d85fad)
#19 0x0000000003db795c clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3db795c)
#20 0x0000000003dc1de3 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#21 0x000000000426ff86 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#22 0x00000000042604c8 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42604c8)
#23 0x0000000006f3816a clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f3816a)
#24 0x0000000006f3698f clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f3698f)
#25 0x0000000006f389b6 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f389b6)
#26 0x0000000006f3698f clang::Sema::PerformPendingInstantiations(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f3698f)
#27 0x00000000064473bf clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#28 0x0000000006447ba2 clang::Sema::ActOnEndOfTranslationUnit() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6447ba2)
#29 0x00000000062c2d0a clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x62c2d0a)
#30 0x00000000062b66ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x62b66ea)
#31 0x000000000426db08 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x426db08)
#32 0x00000000044f1349 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44f1349)
#33 0x0000000004478a2e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4478a2e)
#34 0x00000000045d805e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45d805e)
#35 0x0000000000c526cc cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc526cc)
#36 0x0000000000c4ba2a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#37 0x00000000042b0cd9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#38 0x00000000038ef4d4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x38ef4d4)
#39 0x00000000042b12cf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#40 0x00000000042773d5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42773d5)
#41 0x0000000004277e3d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4277e3d)
#42 0x000000000427fb35 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x427fb35)
#43 0x0000000000c4fbd5 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc4fbd5)
#44 0x0000000000b31264 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb31264)
#45 0x0000752ae9229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#46 0x0000752ae9229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#47 0x0000000000c4b4de _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc4b4de)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by cor3ntin**
Given `foo...[idx]` if idx is value dependent, the expression is type dependent.

Fixes #91885
Fixes #91884

### CODE REVIEW

File: clang/lib/AST/ComputeDependence.cpp [hunk 1]
```diff
@@ -376,6 +376,9 @@ ExprDependence clang::computeDependence(PackExpansionExpr *E) {
 
 ExprDependence clang::computeDependence(PackIndexingExpr *E) {
   ExprDependence D = E->getIndexExpr()->getDependence();
+  if (D & ExprDependence::Value)
+    D |= ExprDependence::TypeInstantiation;
```
Comment (zyn0217) [inline clang/lib/AST/ComputeDependence.cpp:380]: Does it mean "if the index expression is value-dependent, then the whole `PackIndexingExpr` is type-dependent despite its expressions"? For example,
```cpp
template <int N, int... E>
auto foo() {
  return E...[N];
}
```
Should `E...[N]` be treated as type-dependent regardless of the result being always an int?

Comment (zyn0217) [reply clang/lib/AST/ComputeDependence.cpp:380]: Probably `E->getPackIdExpression()->getDependence() & ExprDependence::TypeInstantiation`?

Comment (cor3ntin) [reply clang/lib/AST/ComputeDependence.cpp:380]: > Should E...[N] be treated as type-dependent regardless of the result being always an int?

Yes. (We don't do anything to look at whether all the expressions would have the same type)

Comment (cor3ntin) [reply clang/lib/AST/ComputeDependence.cpp:380]: NVM, you are right, we can simplify this whole thing, I'll do that shortly

File: clang/lib/Sema/SemaType.cpp [hunk 2]
```diff
@@ -9806,7 +9806,7 @@ QualType Sema::BuildCountAttributedArrayType(QualType WrappedTy,
 /// that expression, according to the rules in C++11
 /// [dcl.type.simple]p4 and C++11 [expr.lambda.prim]p18.
 QualType Sema::getDecltypeForExpr(Expr *E) {
-  if (E->isTypeDependent())
+  if (E->isInstantiationDependent())
```
Comment (zyn0217) [inline clang/lib/Sema/SemaType.cpp:9809]: Is it... right? I was assuming this would bring such regressions e.g.

```cpp
template <class T>
const int val = sizeof(T);

template <class T>
void foo() {
  decltype(val<T>);  // <-- this is instantiation-dependent, but not type-dependent.
}
```

Perhaps we can move it to line 9816 where the `PackIndexingExpr` is handled?

Comment (cor3ntin) [reply clang/lib/Sema/SemaType.cpp:9809]: > Perhaps we can move it to line 9816 where the PackIndexingExpr is handled?

I would be slightly concerned about having specific handling of `PackIndexingExpr` all over the place,
or about  `decltype` behaving differently for pack indexing.

Then again, I'm not sure there is a scenario where it matters.

Comment (cor3ntin) [reply clang/lib/Sema/SemaType.cpp:9809]: So here is a thought.
If the pack indexing expression is not type dependent, decltype should just produce the type of that expression.
By that logic we do want to modify decltype so that it does something more clever than to try to use the selected expression.

I'll try to do something in that direction, but it's unclear to me under which set of circumstances we can observe that.

**Review by zyn0217 — APPROVED** [review]
Thanks for the prompt fix! I think this looks good now, but please wait for @erichkeane for the final stamp.

**Review by erichkeane — APPROVED** [review]
