### PR TITLE
[Clang][C++23] update constexpr diagnostics for missing return statements per P2448

### LINKED ISSUE #92583: [C++23] "no return statement in constexpr function" no longer an error with P2448
These:

```c++
constexpr int f() {}
static_assert(__is_same(decltype([] constexpr -> int {}()), int));
consteval int g() {}
static_assert(__is_same(decltype([] consteval -> int {}()), int));
```

Should compile in C++23. It probably still should have a warning diagnostic (the `-Wreturn-type` "non-void {function|lambda} does not return a value" should be issued for `f`  and `g` at least), but it shouldn't be an error (<https://wg21.link/P2448R2#pnum_24>)

Currently, these issue the diagnostic `error: no return statement in constexpr/consteval function/lambda`

Also #63617 does not apply to C++23

See also: #77753

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #92583

### CODE REVIEW

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -2487,6 +2477,26 @@ static bool CheckConstexprFunctionBody(Sema &SemaRef, const FunctionDecl *Dcl,
...
+  bool IsVoidOrDependentType = Dcl->getReturnType()->isVoidType() ||
+                               Dcl->getReturnType()->isDependentType();
+
+  if (SemaRef.getLangOpts().CPlusPlus23 && !IsVoidOrDependentType)
+    return true;
+
+  // C++1y doesn't require constexpr functions to contain a 'return'
+  // statement. We still do, unless the return type might be void, because
+  // otherwise if there's no return statement, the function cannot
+  // be used in a core constant expression.
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaDeclCXX.cpp:2491]: Could you please also mention that we early-exit and don't emit error diagnostic in C++23 because it doesn't require `constexpr` function to produce a constant expression?

File: clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// RUN: %clang_cc1 -Wno-return-type -std=c++23 -fsyntax-only -verify %s
+// expected-no-diagnostics
+constexpr int f() { }
+static_assert(__is_same(decltype([] constexpr -> int { }( )), int));
```
Comment (Fznamznon) [inline clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp:4]: Should we emit at least a warning in case of missing return statement and non-void function and check it?

**Review by Fznamznon — COMMENTED** [review]
I wonder if we should always emit an error when a function with non-void return type doesn't have a return statement? In any case it is a serious yet dumb bug that will lead to problems and perhaps some time spent debugging it.
gcc rejects the case for C++23 as well https://godbolt.org/z/8xq8TdEGE . 
cc @AaronBallman

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 3]
```diff
@@ -2487,6 +2477,26 @@ static bool CheckConstexprFunctionBody(Sema &SemaRef, const FunctionDecl *Dcl,
...
 
+static bool CheckConstexprMissingReturn(Sema &SemaRef,
+                                        const FunctionDecl *Dcl) {
+  bool IsVoidOrDependentType = Dcl->getReturnType()->isVoidType() ||
+                               Dcl->getReturnType()->isDependentType();
+
+  if (SemaRef.getLangOpts().CPlusPlus23 && !IsVoidOrDependentType)
+    return true;
+
+  // C++1y doesn't require constexpr functions to contain a 'return'
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDeclCXX.cpp:2488]:
```suggestion
  // C++14 doesn't require constexpr functions to contain a 'return'
```

File: clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp:4]: For C++23, I think users will have to use `-Winvalid-constexpr` to be notified of "this will never be valid in a constant expression" thanks to P2448.

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this!

File: clang/lib/Sema/SemaDeclCXX.cpp (hunk 1 above)
Comment (a-tarasyuk) [reply clang/lib/Sema/SemaDeclCXX.cpp]: @Fznamznon Thanks for the review. I've added a comment.

File: clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp (hunk 2 above)
Comment (a-tarasyuk) [reply clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp]: @AaronBallman Should a new option (`-Winvalid-constexpr`) be added to control warnings for this case? Is that what you're referring to?

Comment (a-tarasyuk) [reply clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp]: @AaronBallman Thanks for the review. Should a new option (`-Winvalid-constexpr`) be added to control warnings for this case? Is that what you're referring to?

Comment (AaronBallman) [reply clang/test/SemaCXX/constexpr-return-non-void-cxx2b.cpp]: We already have such an option, but it wasn't until today that the diagnostic worked in C++23: https://github.com/llvm/llvm-project/commit/e5f7123dfef3a80937d088d846ddb3b2bb1869b9

Should be nothing here for you to do.

**Review by AaronBallman — APPROVED** [review]
LGTM

**Review by Fznamznon — APPROVED** [review]

**Comment by tbaederr** [comment]
@a-tarasyuk Do you need someone else to merge this?

**Comment by a-tarasyuk** [comment]
@tbaederr Yes, I do. I don't have access to merge…
