### PR TITLE
[clang-format] Fix breaking enum braces when combined with export

### LINKED ISSUE #186684: [clang-format] AfterEnum BraceWrapping does not work with exported enum
Tested with LLVM-22.1.1-Linux-X64

.clang-format
```
---
Language: Cpp
BreakBeforeBraces: Custom
BraceWrapping:
    AfterEnum: true
...
```
Input cpp
```cpp
export module testing;
enum class Works1 { Case1, Case2 };
enum class Works2 { Case1, Case2, };
export enum class DoesNotWork1 { Case1, Case2 };
export enum class DoesNotWork2 { Case1, Case2, };
```
Result
```cpp
export module testing;
enum class Works1
{
  Case1,
  Case2
};
enum class Works2
{
  Case1,
  Case2,
};
export enum class DoesNotWork1 { Case1, Case2 };
export enum class DoesNotWork2 {
  Case1,
  Case2,
};
```
Expected both exported and not exported enums to be formated in the same way.

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
This fixes #186684.

Also fix (not) breaking variables declared on the same line as the closing brace.

And adapt whitesmith to that changes.

### CODE REVIEW

File: clang/unittests/Format/FormatTest.cpp [hunk 1]
```diff
@@ -22143,6 +22159,11 @@ TEST_F(FormatTest, WhitesmithsBraceBreaking) {
                "  }",
                WhitesmithsBraceStyle);
   verifyFormat("enum X\n"
+               "  {\n"
+               "  Y = 0,\n"
+               "  Z = 1\n"
+               "  };\n"
+               "enum X\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp]: Delete?

**Review by owenca — COMMENTED** [review]
Seems all you need is the following:
```diff
--- a/clang/lib/Format/TokenAnnotator.cpp
+++ b/clang/lib/Format/TokenAnnotator.cpp
@@ -6045,6 +6045,7 @@ bool TokenAnnotator::mustBreakBefore(AnnotatedLine &Line,
 
     if (Style.BraceWrapping.AfterEnum) {
       if (Line.startsWith(tok::kw_enum) ||
+          Line.startsWith(tok::kw_export, tok::kw_enum) ||
           Line.startsWith(tok::kw_typedef, tok::kw_enum)) {
         return true;
       }
```

**Review by owenca — APPROVED** [review]
