### PR TITLE
[Clang] Fix the access checking for non-aggregates in default arguments

### LINKED ISSUE #62444: Incorrect and stateful access control for user-defined conversion in function template default argument initialization
Clang accepts-invalid:
```c++
struct B { friend struct A; private: B(int); };
template<class T> int f(T = 0);
struct A { A() { int i = f<B>(); } };
```
Per http://eel.is/c++draft/temp.inst#12.sentence-1 access control should be the same as for a function template specialization adjacent to `f`; the friendship of `A` is irrelevant. MSVC and gcc get this right, although gcc weirdly accepts-invalid if the ctor is `B()` and the default argument initializer is `{}`.

Worse, clang correctly rejects if the caller is not a friend:
```c++
struct B { friend struct A; private: B(int); };
template<class T> int f(T = 0);
int i = f<B>(); // error: calling a private constructor of class 'B'
```
but if the friend call is moved first it accepts, indicating that the instantiated default argument has been remembered, which would be fine if it didn't use `A`'s access control.
```c++
struct B { friend struct A; private: B(int); };
template<class T> int f(T = 0);
struct A { A() { int i = f<B>(); } };
int i = f<B>();
```

### LINKED ISSUE #83608: Clang doesn't recognise friendship in default parameters in C++20+
This code doesn't compile on Compiler Explorer. Moving the defaulted parameter to the constructor body seems to be okay.

```cpp
template<class T>
class single;

template<class T, class U>
class check_constructible {
    check_constructible() = default;

    static_assert(is_constructible_v<T, U>);

    template<class X>
    friend class single;
};

template<class T>
struct single {
    template<class U>
    single(U u, check_constructible<T, U> = {})
    : x(u)
    {}

    T x;
};

int main() {
    single<int> x(0);
}
```

Diagnostic:
```
<source>:25:45: error: calling a private constructor of class 'check_constructible<int, int>'
   25 |     single(U u, check_constructible<T, U> = {})
      |                                             ^
<source>:14:5: note: implicitly declared private here
   14 |     check_constructible() = default;
      |     ^
```

Compiler info:
```
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 5b058709536dd883980722ee000bb7b8c7b2cd8b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk-20240301/bin
Compiler returned: 0
```

Both GCC and MSVC accept this code. If it's not conforming, should we accept it as an extension?

### PR DESCRIPTION
**Pull request by zyn0217**
We check the accessibility of constructors when initializing a default argument whose type is not an aggregate.

Make sure the check is performed within the correct DeclContext. Otherwise, it will be delayed until the end of the declaration, at which point the context is mismatched.

Fixes #62444 
Fixes https://github.com/llvm/llvm-project/issues/83608

### CODE REVIEW

File: clang/test/SemaTemplate/default-arguments.cpp [hunk 1]
```diff
@@ -282,4 +283,25 @@ static_assert(S<short *>().SizeOfT<char>() == sizeof(short *), "");
...
+
+  friend class single;
+};
+
+struct single {
+  template <class T> single(T u, check_constructible = {}) {}
+};
+
+// We perform access checking when substituting into the default argument.
+// Make sure it runs within class single.
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/default-arguments.cpp:302]:
```suggestion
// Make sure it runs within the context of 'single'.
```

File: clang/test/SemaTemplate/default-arguments.cpp [hunk 2]
```diff
@@ -282,4 +283,25 @@ static_assert(S<short *>().SizeOfT<char>() == sizeof(short *), "");
 
 } // namespace GH68490
 
+namespace GH83608 {
+
+class single;
+
+class check_constructible {
+  // This makes it a non-aggregate in C++20+.
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/default-arguments.cpp:291]:
```suggestion
  // This makes a class a non-aggregate in C++20+.
```

File: clang/test/SemaTemplate/default-arguments.cpp [hunk 3]
```diff
@@ -282,4 +283,25 @@ static_assert(S<short *>().SizeOfT<char>() == sizeof(short *), "");
...
+  check_constructible() = default;
```
Comment (cor3ntin) [inline clang/test/SemaTemplate/default-arguments.cpp:292]: Can we user define it? It would be clearer what is tested.

**Review by cor3ntin — APPROVED** [review]
Thanks

**Comment by cor3ntin** [comment]
Does this fixes https://github.com/llvm/llvm-project/issues/62444 ?

**Comment by zyn0217** [comment]
> Does this fixes #62444 ?

Yes 😎

File: clang/test/SemaTemplate/default-arguments.cpp (hunk 3 above)
Comment (zyn0217) [reply clang/test/SemaTemplate/default-arguments.cpp:292]: Yes that way the C++20 tag is no longer necessary
