### PR TITLE
[X86] combineStore - fold scalar float store(fabs/fneg(load())) -> store(and/xor(load(),c))

### LINKED ISSUE #117557: Over-eager SIMD causing up to 6x regression on basic math functions [x64]
# Part 1

```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	for(int i=0;i<1000000000;i++){
		float r = accumulate;
		r = abs(r);
		// or indeed
		//r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7ffffff);
		accumulate = r;
	}
}
```
The loop is partially unrolled but the load/abs()/store is turned into
```asm
.LCPI0_0:
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
.main
	...
	movss   xmm1, dword ptr [rip + x]
	andps   xmm1, xmm0
	movss   dword ptr [rip + x], xmm1
	...
```
The compiler attempts to make use of SIMD but it ends up being much slower. On my machine the loop completes in 2.72s on average

In contrast, replacing `0x7ffffff` with `0x7fffffe` results in much nicer assembly:
```asm
; LCPI0_0 is gone
.main
	...
	and     dword ptr [rip + x], 2147483646
	...
```
On my machine the loop completes in 450ms on average

# Part 2

Let's say we perform the volatile load/store outside the loop

```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	float r = accumulate;
	for(int i=0;i<1000000000;i++){
		r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7ffffff);
	}
	accumulate = r;
}
```
The loop is unrolled 8x and compiled into
```asm
.LCPI0_0:
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
	.long   0x7fffffff
.main
        ; xmm1 = xmm0 = accumulate
	...
	andps   xmm0, xmm1
	...
        ; accumulate = xmm0
```
Completion time: 270ms

Now with the modified version, as earlier
```cpp
#include <math.h>
#include <bit>
using namespace std;

volatile float accumulate = 1.;
int main(){
	float r = accumulate;
	for(int i=0;i<1000000000;i++){
		r = bit_cast<float>(bit_cast<unsigned int>(r) & 0x7fffffe);
	}
	accumulate = r;
}
```
The above is completely optimized away into
```asm
main:
        and     dword ptr [rip + x], 2147483646
        xor     eax, eax
        ret
x:
        .long   0x3f800000
```
In the first case the compiler attempts to use SIMD instructions where not necessary, creating an additional data section in the process
In the second case the compiler does that plus fails to optimize a loop whose body is dependent on a volatile, despite the volatile not being accessed inside the loop.

**In both cases the compiler determines that it SIMD is faster if and only if the second operand to `&` is `0x7ffffff`, which is completely wrong as only one value is being modified, no SIMD is needed**

### PR DESCRIPTION
**Pull request by RKSimon**
As noted on #117557 - its not worth performing scalar float fabs/fneg on the fpu if we're not doing any other fp ops.

This is currently limited to store + load pairs - I could try to extend this further if necessary, but we need to be careful that we don't end up in an infinite loop with the DAGCombiner foldBitcastedFPLogic combine.

Fixes #117557

### CODE REVIEW

File: llvm/lib/Target/X86/X86ISelLowering.cpp [hunk 1]
```diff
@@ -52661,6 +52661,29 @@ static SDValue combineStore(SDNode *N, SelectionDAG &DAG,
                         St->getMemOperand()->getFlags());
   }
 
+  // Convert scalar fabs/fneg load-store to integer equivalents.
+  if ((VT == MVT::f32 || VT == MVT::f64) &&
```
Comment (phoebewang) [inline llvm/lib/Target/X86/X86ISelLowering.cpp:52665]: Should we consider more FP types like half, bfloat, fp128?

**Review by phoebewang — APPROVED** [review]
LGTM.
