### PR TITLE
[rtsan] Support legacy pthread_cond variables

### LINKED ISSUE #146120: Real-time Sanitizer causes pthread_cond_signal to segfaul when a thread is doing a timed wait on a condition variable
A simple std::condition_variable usage leads to segfault when building with clang 20, -fsanitizer=realtime.
Nothing is annotated as non-blocking.
```
#include <condition_variable>
#include <future>
#include <mutex>
#include <thread>

int main() {
  std::mutex mut;
  std::condition_variable cv;
  bool go{false};

  const auto fut = std::async(std::launch::async, [&] {
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    {
      std::unique_lock<std::mutex> lock(mut);
      go = true;
    }
    cv.notify_one();
  });

  std::unique_lock<std::mutex> lock(mut);
  // normal wait is fine
  // cv.wait(lock, [&] { return go; });
  // but timed wait segfaults
  cv.wait_for(lock, std::chrono::milliseconds(200), [&] { return go; });
}

```

```
(gdb) r
Starting program: /app/iplatform/rsan_bug_build/rsan_bug 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f05071ff640 (LWP 254606)]

Thread 2 "rsan_bug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f05071ff640 (LWP 254606)]
0x00007f0507c85233 in pthread_cond_signal () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f0507c85233 in pthread_cond_signal () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000058e1f2851b92 in main::$_0::operator()() const ()
```

If the condition_variable is not yet waited on, there is no segfault. If it is not a timed wait, there is no segfault.

[CMakeLists.txt](https://github.com/user-attachments/files/20952913/CMakeLists.txt)

### PR DESCRIPTION
**Pull request by cjappl**
fixes #146120 

Follows a pattern put forward in tsan:
https://github.com/llvm/llvm-project/blob/71ffa2a4d3c220c97fbffa6078a446cc17bbaada/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp#L1366-L1371

https://github.com/llvm/llvm-project/blob/71ffa2a4d3c220c97fbffa6078a446cc17bbaada/compiler-rt/lib/tsan/dd/dd_interceptors.cpp#L204-L208

To properly deal with memory corruption on older versions of pthread_cond variables.

I was never able to repro this problem, but I'm hopeful it's in the right direction considering the crash report. Seeing as it's basically behind a feature flag, I think introducing it to see if it fixes the problem is low risk.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
This is similar to compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp. Looks good if @adrew0809 can confirm that this fixes the issue.

File: compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp [hunk 1]
```diff
@@ -46,12 +46,52 @@
...
+DECLARE_REAL_AND_INTERCEPTOR(void *, malloc, usize size)
+DECLARE_REAL_AND_INTERCEPTOR(void, free, void *ptr)
+
 namespace {
 struct DlsymAlloc : public DlSymAllocator<DlsymAlloc> {
   static bool UseImpl() { return !__rtsan_is_initialized(); }
 };
 } // namespace
 
+// See note in tsan or ddsan as to why this is necessary
```
Comment (fmayer) [inline compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:69]: does `ddsan` refer to tsan/dd? I don't see any comment in that.

Comment (fmayer) [reply compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:69]: this file has no note though, so I am confused.

**Comment by cjappl** [comment]
I just hopped off a call with @adrew0809 and we confirmed this fixes the issue!

The surprising part is his code no longer crashes when the flag is omitted, or when it is it's default value (false)

```
./a.out # no crash
RTSAN_OPTIONS='legacy_pthread_cond=false` ./a.out # no crash
RTSAN_OPTIONS='legacy_pthread_cond=true` ./a.out # CRASH
```

I'm trying to reason about why this might be. Maybe it has something to do with the PTHREAD_ABI_BASE? I'm not entirely sure.


Considering this fixes the issue, I'm inclined to merge. Any objections @fmayer or @davidtrevelyan ?

**Review by davidtrevelyan — COMMENTED** [review]
No strong objections to merging this from me. If it fixes the issue on @adrew0809's machine and the CI is happy then I think it's low-enough risk to go for it. I do think we should consider whether it would be feasible to get this issue and its solution under meaningful test - if it's not too hard I think it would be wise to do it soon.

**Review by fmayer — APPROVED** [review]

File: compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp [hunk 2]
```diff
@@ -46,12 +46,52 @@
...
+
 namespace {
 struct DlsymAlloc : public DlSymAllocator<DlsymAlloc> {
   static bool UseImpl() { return !__rtsan_is_initialized(); }
 };
 } // namespace
 
+// See note in tsan as to why this is necessary
+static pthread_cond_t *init_cond(pthread_cond_t *c, bool force = false) {
+  if (!common_flags()->legacy_pthread_cond)
```
Comment (MaskRay) [inline compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:71]: The option is for DSO built against glibc 2.2.5 (released in 2002). For rtsan we can reasonably assume newer shared objects and don't allow this at all.

So, just delete this code path?

Comment (cjappl) [reply compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:71]: If I delete this codepath, I get a crash on almost all tests on my mac, with this stack trace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3cb0b1bb)
  * frame #0: 0x000000018d619e4c libsystem_pthread.dylib`pthread_cond_broadcast + 48
    frame #1: 0x000000018d54ae70 libc++.1.dylib`std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) + 224
    frame #2: 0x000000018d582914 libc++.1.dylib`std::__1::locale::id::__get() + 104
    frame #3: 0x000000018d57fb94 libc++.1.dylib`std::__1::locale::__imp::__imp(unsigned long) + 148
    frame #4: 0x000000018d580c10 libc++.1.dylib`std::__1::locale::classic() + 84
    frame #5: 0x000000018d582140 libc++.1.dylib`std::__1::locale::__global() + 72
    frame #6: 0x000000018d5821a0 libc++.1.dylib`std::__1::locale::locale() + 24
    frame #7: 0x000000018d55875c libc++.1.dylib`std::__1::basic_streambuf<char, std::__1::char_traits<char>>::basic_streambuf() + 52
    frame #8: 0x000000018d56aac8 libc++.1.dylib`std::__1::__stdinbuf<char>::__stdinbuf(__sFILE*, __mbstate_t*) + 40
    frame #9: 0x000000018d56a45c libc++.1.dylib`std::__1::DoIOSInit::DoIOSInit() + 68
    frame #10: 0x000000018d56aa50 libc++.1.dylib`std::__1::ios_base::Init::Init() + 80
    frame #11: 0x000000018d56be70 libc++.1.dylib`_GLOBAL__I_000100 + 32
    frame #12: 0x000000018d2b105c dyld`invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
    frame #13: 0x000000018d2ef308 dyld`invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 340
    frame #14: 0x000000018d2e299c dyld`invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 496
    frame #15: 0x000000018d2922fc dyld`dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
    frame #16: 0x000000018d2e1930 dyld`dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
    frame #17: 0x000000018d2eee1c dyld`dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 516
    frame #18: 0x000000018d2ad070 dyld`dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 524
    frame #19: 0x000000018d2b6d28 dyld`dyld4::PrebuiltLoader::runInitializers(dyld4::RuntimeState&) const + 44
    frame #20: 0x000000018d2ad45c dyld`dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 220
    frame #21: 0x000000018d2ad400 dyld`dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 128
    frame #22: 0x000000018d2b10ec dyld`dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 116
    frame #23: 0x000000018d2ad628 dyld`dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 380
    frame #24: 0x000000018d2d04d8 dyld`dyld4::APIs::runAllInitializersForMain() + 464
    frame #25: 0x000000018d296f7c dyld`dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3156
    frame #26: 0x000000018d295edc dyld`start + 1844
```

Specifically, the pthread_cond_broadcast interceptor gets called, but seemingly our `pthread_cond_init` function is never called. This means:

```cpp
INTERCEPTOR(int, pthread_cond_broadcast, pthread_cond_t *cond) {
  __rtsan_notify_intercepted_call("pthread_cond_broadcast");


  // This function returns a cond not initialized by us, 
  pthread_cond_t *c = init_cond(cond);

  // this call crashes, as it operates on a pthread_cond that wasn't initialized properly
  return REAL(pthread_cond_broadcast)(c);
}
```

Any thoughts on getting around this? I've tried a few things, but nothing seems to work.

**Comment by cjappl** [comment]
> I have created #154268 to simplify the tsan `pthread_cond_t` interceptors.
> 
> https://maskray.me/blog/2023-01-08-all-about-sanitizer-interceptors
> 
> > Before glibc 2.36, dlsym(RTLD_NEXT, name) returned the address of the oldest version definition of name in libc.so.6. And we got to use the old semantics. This is usually benign but not ideal (see [google/sanitizers#1371](https://github.com/google/sanitizers/issues/1371) for a regexec issue). I fixed glibc 2.36 ([BZ #14932](https://sourceware.org/bugzilla/show_bug.cgi?id=14932)) so that dlsym(RTLD_NEXT, name) returns the default version definition now.
> 
> https://maskray.me/blog/2022-05-29-glibc
> 
> > Take x86_64 as an example. sysdeps/unix/sysv/linux/x86_64/64/shlib-versions says that x86_64's earliest symbol is at GLIBC_2.2.5. $build/abi-versions.h contains:

Thanks @MaskRay ! After that's merged, I'll update to follow that pattern.

File: compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp (hunk 2 above)
Comment (cjappl) [reply compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:61]: @MaskRay - any ideas here? I'm inclined to just leave it, as it seems like MacOS may use some kind of shared condition variable to access locale. (but I admit I don't fully understand it).

I've updated the interception pattern to match your work in #154268

Comment (MaskRay) [reply compiler-rt/lib/rtsan/rtsan_interceptors_posix.cpp:61]: We should assume `common_flags()->legacy_pthread_cond` is always false for rtsan and delete the unreachable code path. Can you double check macOS really crashes?

**Comment by MaskRay** [comment]
`legacy_pthread_cond` is a legacy - we should remove it.
