### PR TITLE
[Clang] Implement P2308R1 - Template Parameter Initialization.

### LINKED ISSUE #36296: [cwg2049] allow braced-init-list as template-argument, at least in default template-arguments
|  |  |
| --- | --- |
| Bugzilla Link | [36948](https://llvm.org/bz36948) |
| Version | 6.0 |
| OS | All |
| CC | @DougGregor,@zygoloid |

## Extended Description 
// this code does not compile

template< int X = {} >
struct Test {};

int main() { return 0; }

### LINKED ISSUE #41227: Non-type template params with braced-init-list initializers are not supported
|  |  |
| --- | --- |
| Bugzilla Link | [41882](https://llvm.org/bz41882) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@JohelEGP,@OmerRosler,@riccibruno,@zygoloid,@Tomaqa |

## Extended Description 
template <int = {}> void f(); // expected expression

One of the things nobody uses, it doesn't even have a TODO somewhere or a intentionally broken test AFAICT. 

We should probably start supporting this, with C++2a's class type non-type template parameters potentially making this kind of construct more popular. :)

### LINKED ISSUE #49978: Clang rejects braced-init-list as default non-type template parameter
|  |  |
| --- | --- |
| Bugzilla Link | [50634](https://llvm.org/bz50634) |
| Version | 12.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Clang rejects this code:

```c++
template<bool = {}>
int f() {}
```

with:
> error: expected expression

However I believe that the C++ grammar permits that.

[temp.param]:
> The syntax for template-parameters is:
> template-parameter:
> 	type-parameter
>	parameter-declaration

[dcl.fct]:

> parameter-declaration:
> 	attribute-specifier-seq_{opt} decl-specifier-seq declarator
> 	attribute-specifier-seq_{opt} decl-specifier-seq declarator = initializer-clause
> 	attribute-specifier-seq_{opt} decl-specifier-seq abstract-declarator_{opt} 
> 	attribute-specifier-seq_{opt} decl-specifier-seq abstract-declarator
_{opt} = initializer-clause

[dcl.init]:
> initializer-clause:
>	assignment-expression
>	braced-init-list

My motivating usecase is:

```c++
template<std::true_type = {}>
int f() {}
```

which is accepted by G++.

### LINKED ISSUE #58434: Wrong error "expected expression" in parsing of braced-init-list inside template argument list
Repro (https://gcc.godbolt.org/z/ehMnoqf7h):
```cpp
template<int>
void f();

void test() {
  f<{42}>();
}
```

### LINKED ISSUE #73666: C++20: Deduction guides ignored for class type placeholder template argument
I experimented with placeholders for deduced class types in templates using `std::array` (passing it as a template argument without explicitly specifying `std::array` during instantiation, instead relying on deduction guides). I found that GCC uses deduction guides to deduce the argument type while Clang seems to ignore them. 

Here is the smallest example I could come up with based on `std::array`:

```C
// trimmed-down std::array
template<class T, int I>
struct A {
    T x[I];
};

// deduction guide (like std::array)
template< class T, class... U >
A( T, U... ) -> A<T, 1 + sizeof...(U)>;

template<A a> void foo() { }

void bar() {
    foo<{1}>(); // works with GCC, fails with Clang
}
```

See also: https://godbolt.org/z/7vWa3zKoj

Apologies if this was reported before, I tried to search the open issues but couldn't find anything related to this. Also, I am not sure whether this is legal in C++20, I was just surprised to see it work in GCC but not in Clang. Please feel free to close this issue if this is not legal.

### PR DESCRIPTION
**Pull request by cor3ntin**
https://wiki.edg.com/pub/Wg21kona2023/StrawPolls/p2308r1.html

This implements P2308R1 as a DR and resolves CWG2459, CWG2450 and CWG2049.

Fixes #73666
Fixes #58434 
Fixes #41227
Fixes #49978
Fixes #36296

### CODE REVIEW

File: clang/test/CXX/drs/dr24xx.cpp [hunk 1]
```diff
@@ -0,0 +1,32 @@
+// RUN: %clang_cc1 -std=c++98 -triple x86_64-unknown-unknown %s -verify -fexceptions -fcxx-exceptions -pedantic-errors \
```
Comment (Endilll) [inline clang/test/CXX/drs/dr24xx.cpp:1]: Is triple necessary for the test?

**Review by Endilll — APPROVED** [review]
DR test side looks good, except for a small nit.

**Review by erichkeane — APPROVED** [review]
I dont think the triple is necessary for the test, otherwise this LGTM!

File: clang/test/CXX/drs/dr24xx.cpp (hunk 1 above)
Comment (AaronBallman) [reply clang/test/CXX/drs/dr24xx.cpp:1]: I don't think we need `-fexceptions -fcxx-exceptions -Wno-variadic-macros -Wno-c11-extensions` either.

File: clang/test/SemaTemplate/temp_arg_nontype_cxx20.cpp [hunk 2]
```diff
@@ -62,7 +62,7 @@ namespace ClassNTTP {
   template<A a> constexpr int f() { return a.y; }
   static_assert(f<A{1,2}>() == 2);
 
-  template<A a> int id;
+  template<A a> int id; // expected-note {{passing argument to parameter 'a' here}}
```
Comment (AaronBallman) [inline clang/test/SemaTemplate/temp_arg_nontype_cxx20.cpp:65]: What diagnostic is this note associated with?

Comment (cor3ntin) [reply clang/test/SemaTemplate/temp_arg_nontype_cxx20.cpp:65]: L70. you want me to use a label i guess?

Comment (AaronBallman) [reply clang/test/SemaTemplate/temp_arg_nontype_cxx20.cpp:65]: Ahhh, it was just out of sight. Yeah might as well switch to a bookmark instead. I don't feel that strongly though.

File: clang/test/CXX/drs/dr20xx.cpp [hunk 3]
```diff
@@ -61,6 +61,14 @@ namespace dr2026 { // dr2026: 11
   }
 }
 
+namespace dr2049 { // dr2049: 18 drafting
+#if __cplusplus > 202002L
+template <int* x = {}> struct X {};
+X<> a;
+X<nullptr> b;
```
Comment (tahonermann) [inline clang/test/CXX/drs/dr20xx.cpp:68]: Perhaps add a same-type static assertion for `a` and `b` to ensure a consistent specialization is selected?

**Review by tahonermann — COMMENTED** [review]
Looks like good work to me!

File: clang/lib/Sema/SemaTemplate.cpp [hunk 4]
```diff
@@ -7313,49 +7313,73 @@ ExprResult Sema::CheckTemplateArgument(NonTypeTemplateParmDecl *Param,
...
+    InitializedEntity Entity =
+        InitializedEntity::InitializeTemplateParameter(ParamType, Param);
+    InitializationSequence InitSeq(*this, Entity, Kind, Inits);
+    ExprResult Result = InitSeq.Perform(*this, Entity, Kind, Inits);
+    if (Result.isInvalid() || !Result.get())
+      return ExprError();
+    Result = ActOnConstantExpression(Result.get());
+    if (Result.isInvalid() || !Result.get())
+      return ExprError();
+    Arg = ActOnFinishFullExpr(Result.get(), Arg->getBeginLoc(), false,
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplate.cpp:7363]:
```suggestion
    Arg = ActOnFinishFullExpr(Result.get(), Arg->getBeginLoc(), /*DiscardedValue=*/false,
```

File: clang/lib/Sema/SemaTemplate.cpp [hunk 5]
```diff
@@ -7313,49 +7313,73 @@ ExprResult Sema::CheckTemplateArgument(NonTypeTemplateParmDecl *Param,
...
-        SugaredConverted = TemplateArgument(Arg);
-        CanonicalConverted =
-            Context.getCanonicalTemplateArgument(SugaredConverted);
-        return Arg;
-      }
-    }
+  bool IsConvertedConstantExpression = true;
+  if (isa<InitListExpr>(Arg) || ParamType->isRecordType()) {
+    InitializationKind Kind = InitializationKind::CreateForInit(
+        Arg->getBeginLoc(), /*DirectInit*/ false, Arg);
```
Comment (shafik) [inline clang/lib/Sema/SemaTemplate.cpp:7352]:
```suggestion
        Arg->getBeginLoc(), /*DirectInit=*/false, Arg);
```

File: clang/lib/Sema/SemaOverload.cpp [hunk 6]
```diff
@@ -6226,6 +6226,15 @@ ExprResult Sema::CheckConvertedConstantExpression(Expr *From, QualType T,
   return R;
 }
 
+ExprResult Sema::EvaluateConvertedConstantExpression(Expr *E, QualType T,
+                                                     APValue &Value,
+                                                     Sema::CCEKind CCE,
+                                                     bool RequireInt) {
+
+  APValue PreNarrowingValue;
```
Comment (shafik) [inline clang/lib/Sema/SemaOverload.cpp:6234]: It feels a bit gratuitous to create a wrapper just to avoid a temporary variable. Maybe if we used it several times but I just see one use.

**Review by shafik — COMMENTED** [review]
Mostly nitpicks

File: clang/lib/Sema/SemaOverload.cpp (hunk 6 above)
Comment (cor3ntin) [reply clang/lib/Sema/SemaOverload.cpp:6234]: That's because I wanted to use the same pattern as 
CheckConvertedConstantExpression/BuildConvertedConstantExpression which both defer to a static function.
They probably could all be changed to be members of Sema if we wanted to.
I'd rather not do that in this patch though

Comment (cor3ntin) [reply clang/lib/Sema/SemaOverload.cpp]: After offline, i changed it. Let me know if that makes you happier.

**Review by shafik — APPROVED** [review]
LGTM
