### PR TITLE
[libc] Fix alignment issue for HermeticTestUtils.cpp.

### LINKED ISSUE #128185: [libc] Re-enable test/src/__support/File tests.
Currently the precommit bots are failing `LlvmLibcFileTest.WriteOnly` in `libc.test.src.__support.File.file_test.__hermetic__` with errors:
```
[1288/6528] Running hermetic test libc.test.src.__support.File.file_test.__hermetic__
FAILED: libc/test/src/__support/File/libc.test.src.__support.File.file_test.__hermetic__-cmd /home/runner/work/llvm-project/llvm-project/build/libc/test/src/__support/File/libc.test.src.__support.File.file_test.__hermetic__-cmd 
cd /home/runner/work/llvm-project/llvm-project/build/libc/test/src/__support/File && /home/runner/work/llvm-project/llvm-project/build/libc/test/src/__support/File/libc.test.src.__support.File.file_test.__hermetic__.__build__
[==========] Running 12 tests from 1 test suite.
[ RUN      ] LlvmLibcFileTest.WriteOnly
Bus error (core dumped)
```
The same errors happen with `LlvmLibcPlatformFileTest.CreateWriteCloseAndReadBack` in `libc.test.src.__support.File.platform_file_test.__hermetic__`.

Possible alignment issues with our public headers + implementations.

I could not reproduce the errors locally, so I will disable the test temporarily to reduce the noise and make the precommit bots' signal useful.

We need to investigate the root cause of the issue and re-enable the test.

### PR DESCRIPTION
**Pull request by lntue**
Full build precommit bots were failing due to mis-alignment of atomics in hermetic tests.  This PR enforces the alignment for the bump allocator of hermetic test framework.

Fixes https://github.com/llvm/llvm-project/issues/128185.

### CODE REVIEW

File: libc/test/UnitTest/HermeticTestUtils.cpp [hunk 1]
```diff
@@ -33,6 +33,10 @@ int atexit(void (*func)(void));
 
 } // namespace LIBC_NAMESPACE_DECL
 
+extern "C" {
```
Comment (jhuber6) [inline libc/test/UnitTest/HermeticTestUtils.cpp:36]: Why extern C? Constexpr has no linkage.

Comment (lntue) [reply libc/test/UnitTest/HermeticTestUtils.cpp:36]: it was inside an `extern "C"` block before so I kept it the same way when moving up.  Is it safe to remove `extern "C"` then?

Comment (jhuber6) [reply libc/test/UnitTest/HermeticTestUtils.cpp:36]: Should be.

Comment (lntue) [reply libc/test/UnitTest/HermeticTestUtils.cpp]: Done.

**Review by jhuber6 — APPROVED** [review]
