### PR TITLE
[Coverage] getMaxBitmapSize: Scan `max(BitmapIdx)` instead of the last `Decision`

### LINKED ISSUE #78922: [Coverage][MC/DC] Wrong BitmapIdx calculation in `getMaxBitmapSize`
In `CoverageMapping.cpp:getMaxBitmapSize`,
https://github.com/llvm/llvm-project/commit/8ecbb0404d740d1ab173554e47cef39cd5e3ef8c#diff-44b7cba1a9d87f9ec9e067d93ea9d29ea4d9c669942d73f89233e39e28f9a5f0R565-R581

This assumes the last `Decision` has the maximum `BitmapIdx`. It is not true.
It may crash`llvm-cov` with unexpected test vector. 

(https://godbolt.org/z/5bGYa8foe)
```
#define RANGE(a,b,c) ((a) <= (b) && (b) <= (c))

int foo(int c) {
  if (RANGE('A', c, 'F')) return 1;
  return ('0' <= c && c <= '9');
}
```

```
foo:
  (snip)
  Expansion,File 0, 4:7 -> 4:12 = #0 (Expanded file = 1)
  (snip)
  Decision,File 0, 5:11 -> 5:31 = M:1, C:2
  (snip)
  Decision,File 1, 1:23 -> 1:47 = M:0, C:2
  (snip)
```

### PR DESCRIPTION
**Pull request by chapuni**
In `CoverageMapping.cpp:getMaxBitmapSize()`, 
this assumed that the last `Decision` has the maxmum `BitmapIdx`.

Let it scan `max(BitmapIdx)`.

Note that `<=` is used insted of `<`, because `BitmapIdx == 0` is valid
and `MaxbitmapID` is `unsigned`. `BitmapIdx` is unique in the record.

Fixes #78922

### CODE REVIEW

**Comment by chapuni** [comment]
Let me push the testcase in advance of the fix, to confirm failure.

**Comment by chapuni** [comment]
The record of this testcase is:
```
sub:
  Decision,File 0, 5:11 -> 5:59 = M:1, C:4
  Branch,File 0, 5:12 -> 5:20 = #5, ((#0 - #1) - #5) [1,3,2]
  Branch,File 0, 5:24 -> 5:32 = #6, (#5 - #6) [3,0,2]
  Branch,File 0, 5:38 -> 5:46 = #7, (#4 - #7) [2,4,0]
  Branch,File 0, 5:50 -> 5:58 = #8, (#7 - #8) [4,0,0]
  Decision,File 1, 1:23 -> 1:47 = M:0, C:2
  Branch,File 1, 1:23 -> 1:33 = #2, (#0 - #2) [1,2,0]
  Branch,File 1, 1:37 -> 1:47 = #3, (#2 - #3) [2,0,0]
```

The current implementation picks up `M:0 C:2`.

**Comment by chapuni** [comment]
```llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:232: Expected<BitVector> llvm::coverage::CounterMappingContext::evaluateBitmap(const CounterMappingRegion *) const: Assertion `ID + SizeInBytes <= BitmapBytes.size() && "BitmapBytes overrun"' failed.``` in https://buildkite.com/llvm-project/github-pull-requests/builds/31563

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 1]
```diff
@@ -566,14 +567,14 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
                                  const CoverageMappingRecord &Record) {
   unsigned MaxBitmapID = 0;
   unsigned NumConditions = 0;
-  // The last DecisionRegion has the highest bitmap byte index used in the
-  // function, which when combined with its number of conditions, yields the
-  // full bitmap size.
+  // Scan max(BitmapIdx).
+  // Note that `<=` is used insted of `<`, because `BitmapIdx == 0` is valid
+  // and `MaxbitmapID is `unsigned`. `BitmapIdx` is unique in the record.
```
Comment (ornata) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:572]: Nit: s/MaxbitmapID/MaxBitmapID/

File: llvm/test/tools/llvm-cov/mcdc-maxbs.test [hunk 2]
```diff
@@ -0,0 +1,21 @@
+# Test the assertion failure in llvm-cov with empty bitmap (#78922)
```
Comment (ornata) [inline llvm/test/tools/llvm-cov/mcdc-maxbs.test:1]: Can you check for the specific assert?

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp [hunk 3]
```diff
@@ -566,14 +567,14 @@ static unsigned getMaxBitmapSize(const CounterMappingContext &Ctx,
...
   for (const auto &Region : reverse(Record.MappingRegions)) {
```
Comment (evodius96) [inline llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:573]: Since you need to check all MCDCDecisionRegions, don't need to look in reverse anymore.

File: llvm/test/tools/llvm-cov/mcdc-maxbs.test [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+# REQUIRES: asserts
+
+# RUN: llvm-profdata merge %S/Inputs/mcdc-maxbs.proftext -o %t.profdata
+# RUN: llvm-cov report --show-mcdc-summary %S/Inputs/mcdc-maxbs.o -instr-profile %t.profdata
+
+# Instructions for regenerating the test object:
+
+clang -O3 -fcoverage-mcdc -fprofile-instr-generate \
+    -fcoverage-mapping -fcoverage-compilation-dir=. \
+    mcdc-maxbs.c -c -o mcdc-maxbs.o
```
Comment (evodius96) [inline llvm/test/tools/llvm-cov/mcdc-maxbs.test:11]: You may want to note `cd $S/Inputs `to underscore the location of mcdc-maxbs.c

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 3 above)
Comment (chapuni) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:573]: I left it as is because larger BitmapIdx can be met earlier. :)

File: llvm/test/tools/llvm-cov/mcdc-maxbs.test (hunk 2 above)
Comment (chapuni) [reply llvm/test/tools/llvm-cov/mcdc-maxbs.test:1]: Passing w/o assertions is expected, so check(s) would not make sense, I think.
Let me update this sentence since it is misleading.

File: llvm/test/tools/llvm-cov/mcdc-maxbs.test (hunk 4 above)
Comment (chapuni) [reply llvm/test/tools/llvm-cov/mcdc-maxbs.test:11]: These are assumed to be done in `$S/Inputs`. I think it is not a bad manner since they are done manually.
I will add `cd $S/Inputs # Or copy %S/Inputs/mcdc-maxbs.c to the working directory`.

File: llvm/lib/ProfileData/Coverage/CoverageMapping.cpp (hunk 3 above)
Comment (evodius96) [reply llvm/lib/ProfileData/Coverage/CoverageMapping.cpp:573]: Yes, that's true -- then you wouldn't need to be constantly updating the variable on every iteration.  Disregard my comment.

File: llvm/test/tools/llvm-cov/mcdc-maxbs.test (hunk 4 above)
Comment (evodius96) [reply llvm/test/tools/llvm-cov/mcdc-maxbs.test:11]: Thanks. Also, I should've said `%S/Inputs` rather than `$S/Inputs`. sorry for the typo.

**Review by ornata — APPROVED** [review]
LGTM

**Comment by chapuni** [comment]
https://lab.llvm.org/buildbot/#/builders/16/builds/60018
> error: failed to load coverage: 'llvm/test/tools/llvm-cov/Inputs/mcdc-maxbs.o': profile uses zlib compression but the profile reader was built without zlib support

I'll rework.

**Comment by ornata** [comment]
Will the new test fail when the profile reader **is** built with zlib support? :(

**Comment by chapuni** [comment]
Should be fixed in d386c40b23798d6b80de5fea61b541dc8cbae36c

@ornata It was failing on zlib-unsupported hosts since I enabled zlib locally.
