### PR TITLE
[clang] Fix conflicting declaration error with using_if_exists

### LINKED ISSUE #85335: Conflicting declaration error with `__using_if_exists__` in libc++
When trying to use libc++ with LLVM libc on a baremetal platform, we encountered an issue with the `__using_if_exists__` attribute which was introduced in https://reviews.llvm.org/D90188:

```
In file included from /llvm_libcxx/include/algorithm:1973:                                                                                                                                                                                                                                                                                                                             
/llvm_libcxx/include/__algorithm/remove.h:28:1: error: declaration conflicts with target of using declaration already in scope                                                                                                                                                                                                                                                         
   28 | remove(_ForwardIterator __first, _ForwardIterator __last, const _Tp& __value) {                                                                                                                                                                                                                                                                                                                                                   
      | ^                                                                                                                                                                                                                                                                                                                                                                                                                                 
/llvm_libcxx/include/cstdio:155:1: note: target of using declaration                                                                                                                                                                                                                                                                                                                   
  155 | using ::remove _LIBCPP_USING_IF_EXISTS;                                                                                                                                                                                                                                                                                                                                                                                           
      | ^                                                                                                                                                                                                                                                                                                                                                                                                                                 
/llvm_libcxx/include/cstdio:155:9: note: using declaration                                                                                                                                                                                                                                                                                                                             
  155 | using ::remove _LIBCPP_USING_IF_EXISTS;                                                                                                                                                                                                                                                                                                                                                                                           
      |         ^                                 
```

This is because baremetal version of the `stdio.h` libc header doesn't include `remove` (since there's no filesystem support).

A more minimal example of this issue is:

```cpp
void foo();

namespace N {
  void bar();

  using ::foo __attribute__((__using_if_exists__));
  using ::bar __attribute__((__using_if_exists__));
}

void baz() {
  N::bar();
}
```

This results in the following error (you can also see it at https://godbolt.org/z/dTxqnc1oP):

```
<source>:7:11: error: target of using declaration conflicts with declaration already in scope
    7 |   using ::bar __attribute__((__using_if_exists__));
      |           ^
<source>:7:3: note: target of using declaration
    7 |   using ::bar __attribute__((__using_if_exists__));
      |   ^
<source>:4:8: note: conflicting declaration
    4 |   void bar();
      |        ^
1 error generated.
Compiler returned: 1
```

Normally, `remove` is declared in `stdio.h`, which corresponds to the `foo` case.

In our case, there's no `remove` symbol in `stdio.h` and as such there's no such symbol in the global namespace, but there's `remove` in the `std::` namespace introduced by `algorithm` corresponding to the `bar` case.

Is this an issue with the `__using_if_exists__` implementation or intended behavior?

This is related to issue https://github.com/llvm/llvm-project/issues/84879.

CC @ldionne @zygoloid @AaronBallman @epilk

### PR DESCRIPTION
**Pull request by PiJoules**
This fixes an issue with using_if_exists where we would hit `conflicts with target of using declaration already in scope` with a using_if_exists attribute referring to a declaration which did not exist. That is, if we have `using ::bar
__attribute__((using_if_exists))` but `bar` is not in the global namespace, then nothing should actually be declared here.

This PR contains the following changes:
1. Ensure we only diagnose this error if the target decl and [Non]Tag decl can be substitutes for each other.
2. Prevent LookupResult from considering UnresolvedUsingIfExistsDecls in the event of ambiguous results.
3. Update tests. This includes the minimal repo for a regression test, and changes to existing tests which also seem to exhibit this bug.

Fixes #85335

### CODE REVIEW

**Comment by Fznamznon** [comment]
> @Fznamznon @Sirraide Can one of you review this when you get a chance given you are Sema maintainers? Thanks!

I'm not familiar with the attribute, so maybe @erichkeane and @AaronBallman can weigh in here but I'll try to take a look as well.
Sorry for the delay, the review notification slipped into post-vacation pile of emails.

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 1]
```diff
@@ -12832,6 +12833,15 @@ bool Sema::CheckUsingShadowDecl(BaseUsingDecl *BUD, NamedDecl *Orig,
       (isa_and_nonnull<UnresolvedUsingIfExistsDecl>(NonTag))) {
     if (!NonTag && !Tag)
       return false;
+
+    // Only report the error if this using_if_exists decl can be a
+    // substitute for the original decl. LookupResult will find things with
+    // the same name but we also want to take into account namespaces and
+    // other scopes. GlobalDecl helps take care of that.
+    NamedDecl *UsedTag = NonTag ? NonTag : Tag;
+    if (GlobalDecl(Target) != GlobalDecl(UsedTag))
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaDeclCXX.cpp]: Hmm, how exactly `GlobalDecl` helps here?
I see it simply stores a pointer, say for a `FunctionDecl`. It is not asking for a canonical decl and then its operator `==` which is used by `!=` operator compares the stored pointers.

**Review by erichkeane — APPROVED** [review]
other than 1 comment request, LGTM.
