### PR TITLE
[Clang] Fix __has_cpp_attribute and C++11 attributes with arguments in C++03

### LINKED ISSUE #82995: C++03 mode ignores the arg in [[attribute(arg)]]
https://godbolt.org/z/aPKq1sKPT
`[[gnu::assume_aligned(4)]] static void *g() { return p; }`
In `-std=c++11` mode, this code is accepted and works as expected. In `-std=c++03` mode, it seems to ignore the `(4)` argument for some reason, and I get an error:
```
<source>:5:3: error: 'assume_aligned' attribute takes at least 1 argument
    5 | [[gnu::assume_aligned(4)]] static void *g() { return p; }
      |   ^
```
@philnik777 I think you enabled attributes in 874217f99b; is there something missing to enable attributes with arguments?

The problem is these lines in `ParseCXX11AttributeArgs`.
```
  // If the attribute isn't known, we will not attempt to parse any
  // arguments.
  if (Form.getSyntax() != ParsedAttr::AS_Microsoft &&
      !hasAttribute(LO.CPlusPlus ? AttributeCommonInfo::Syntax::AS_CXX11
                                 : AttributeCommonInfo::Syntax::AS_C23,
                    ScopeName, AttrName, getTargetInfo(), getLangOpts())) {
```
This is reusing the return code of `hasAttribute` to ask whether the attribute is recognized (a boolean). But the machine-generated code in `AttrHasAttributeImpl.inc` uses the return code to say what `__has_cpp_attribute` should be set to (an int), and invariably returns `0` in C++03 mode. https://godbolt.org/z/casKPfdez
```
} else if (ScopeName == "gnu") {
  return llvm::StringSwitch<int>(Name)
[...]
    .Case("assume_aligned", LangOpts.CPlusPlus11 ? 1 : 0)
```
That file is generated by `clang/utils/TableGen/ClangAttrEmitter.cpp`. Maybe a change is needed in that generator?

### PR DESCRIPTION
**Pull request by philnik777**
The values for `__has_cpp_attribute` don't have to be guarded behind `LangOpts.CPlusPlus` because `__has_cpp_attribute` isn't available if Clang isn't in a C++ mode.

Fixes #82995

### CODE REVIEW

**Comment by AMP999** [comment]
How about also enabling some existing C++11 tests for C++03 mode, too? E.g. `Preprocessor/has_attribute.cpp`, `SemaCXX/attr-declspec-ignored.cpp`, `SemaCXX/attr-gnu.cpp`, don't run in C++03 mode today but they could be made to.

File: clang/test/SemaCXX/attr-gnu.cpp [hunk 1]
```diff
@@ -1,7 +1,7 @@
-// RUN: %clang_cc1 -std=gnu++17 -fsyntax-only -fms-compatibility -verify %s
-
-void f() {
-  // GNU-style attributes are prohibited in this position.
+// RUN: %clang_cc1 -std=gnu++17 -fsyntax-only -fms-compatibility -verify %s
```
Comment (AaronBallman) [inline clang/test/SemaCXX/attr-gnu.cpp:1]: What... changed... here? I don't see any actual changes in the file...

**Review by AaronBallman — COMMENTED** [review]
The changes need a release note since this is fixing a bug in Clang 17

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -285,6 +285,10 @@ Bug Fixes to C++ Support
   templates when determining the primary template of an explicit specialization.
 - Fixed a crash in Microsoft compatibility mode where unqualified dependent base class
   lookup searches the bases of an incomplete class.
+  (`#782154 <https://github.com/llvm/llvm-project/issues/82154>`_`)
```
Comment (AaronBallman) [inline clang/docs/ReleaseNotes.rst:288]: This seems like an unintentional change.

File: clang/test/SemaCXX/constant-expression-cxx11.cpp [hunk 3]
```diff
@@ -1,4 +1,4 @@
-// RUN: %clang_cc1 -std=c++23 -isystem %S/Inputs -fsyntax-only -verify=expected,cxx20_23,cxx23    -triple x86_64-linux -Wno-string-plus-int -Wno-pointer-arith -Wno-zero-length-array -Wno-c99-designator -fcxx-exceptions -pedantic %s -Wno-comment -Wno-tautological-pointer-compare -Wno-bool-conversion
+// RUN: %clang_cc1 -std=c++23 -isystem %S/Inputs -fexperimental-new-constant-interpreter -fsyntax-only -verify=expected,cxx20_23,cxx23    -triple x86_64-linux -Wno-string-plus-int -Wno-pointer-arith -Wno-zero-length-array -Wno-c99-designator -fcxx-exceptions -pedantic %s -Wno-comment -Wno-tautological-pointer-compare -Wno-bool-conversion
```
Comment (AaronBallman) [inline clang/test/SemaCXX/constant-expression-cxx11.cpp:1]: This seems unrelated?

**Review by AaronBallman — APPROVED** [review]
LGTM modulo the testing request from @AMP999

File: clang/test/SemaCXX/attr-gnu.cpp (hunk 1 above)
Comment (philnik777) [reply clang/test/SemaCXX/attr-gnu.cpp:2]: I'm pretty sure these are trailing whitespace removals.

Comment (AaronBallman) [reply clang/test/SemaCXX/attr-gnu.cpp:2]: Huh, fair enough (though usually we want unrelated changes stripped from the patch, including trailing whitespaces).

**Review by AaronBallman — APPROVED** [review]
LGTM

**Comment by philnik777** [comment]
The CI failure is unrelated.
