### PR TITLE
[StackColoring] Delete lifetime markers even when pass is disabled by -opt-bisect-limit

### LINKED ISSUE #164336: [StackColoring] opt-bisect-limit prevents removal of LIFETIME_END instruction
If the stack coloring pass is disabled via opt-bisect-limit, it doesn't remove LIFETIME_END instructions. This can cause crashes in later passes like eliminateFrameIndex that don't expect to see these instructions.

Should we make StackColoring collect and remove the markers when it is disabled? I believe that's what we do for the `-no-stack-coloring` cl::opt.

CC: @arsenm @efriedma-quic @qcolombet

### PR DESCRIPTION
**Pull request by topperc**
Fixes #164336

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

File: llvm/lib/CodeGen/StackColoring.cpp [hunk 1]
```diff
@@ -1190,11 +1190,8 @@ void StackColoring::expungeSlotMap(DenseMap<int, int> &SlotRemap,
...
 bool StackColoringLegacy::runOnMachineFunction(MachineFunction &MF) {
-  if (skipFunction(MF.getFunction()))
-    return false;
-
   StackColoring SC(&getAnalysis<SlotIndexesWrapperPass>().getSI());
-  return SC.run(MF);
+  return SC.run(MF, skipFunction(MF.getFunction()));
 }
 
 PreservedAnalyses StackColoringPass::run(MachineFunction &MF,
```
Comment (preames) [inline llvm/lib/CodeGen/StackColoring.cpp]: How do we avoid the same problem with the new pass manager?  (Non blocking for review.)

**Review by preames — APPROVED** [review]
LGTM w/minor comment

File: llvm/lib/CodeGen/StackColoring.cpp (hunk 1 above)
Comment (boomanaiden154) [reply llvm/lib/CodeGen/StackColoring.cpp]: `-opt-bisect-limit` goes through `StandardInstrumentation` to add callbacks in the NewPM. So there's no way (currently) to even have the pass invoked for an IR unit if it gets skipped due to `-opt-bisect`. If we want to support this use in the NewPM, we probably need to add something there.

**Review by boomanaiden154 — COMMENTED** [review]
Postponing work for NewPM is probably fine for now. Can we add a regression test somewhere to ensure that this doesn't get dropped when we start getting closer to using the NewPM by default for Codegen?
