### PR TITLE
Reapply [AMDGPU] Avoid resource propagation for recursion through multiple functions

### LINKED ISSUE #115562: [AMDGPU] Compiler crash in `AMDGPUAsmPrinter` with circular function call involvement
```
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 small.ll %s -o -

define amdgpu_kernel void @kernel() {
entry:
  call void @callee1()
  ret void
}

define void @callee1() #0 {
entry:
  call void @callee2()
  ret void
}

define void @callee2() #0 {
entry:
  call void @callee1()
  ret void
}

attributes #0 = { noinline }
```

The crash is because of stack overflow.

`evaluateAsRelocatable -> evaluateAsRelocatableImpl -> evaluateAsRelocatableImpl -> evaluateAsRelocatable -> ...`

### PR DESCRIPTION
**Pull request by JanekvO**
I was wrong last patch. I viewed the `Visited` set purely as a possible recursion deterrent where functions calling a callee multiple times are handled elsewhere. This doesn't consider cases where a function is called multiple times by different callers still part of the same call graph. New test shows the aforementioned case.

Reapplies #111004, fixes #115562.

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 1]
```diff
@@ -91,13 +91,76 @@ MCSymbol *MCResourceInfo::getMaxSGPRSymbol(MCContext &OutContext) {
...
+
+// Symbols whose values eventually are used through their defines (i.e.,
+// recursive) must be avoided. Do a walk over Expr to see if Sym will occur in
+// it. The Expr is an MCExpr given through a callee's equivalent MCSymbol so if
+// no recursion is found Sym can be safely assigned to a (sub-)expr which
+// contains the symbol Expr is associated with. Returns true if Sym exists
+// in Expr or its sub-expressions, false otherwise.
+static bool foundRecursiveSymbolDef(MCSymbol *Sym, const MCExpr *Expr) {
+  SmallVector<const MCExpr *, 8> WorkList;
+  SmallPtrSet<const MCExpr *, 8> Visited;
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:144]: You're still doing this worklist + visited set for each visited callee. Can you pull this out and merge with the loop over callees? 

That is the Seen function set and the Visited MCExprs are probably redundant.

Comment (JanekvO) [reply llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp]: Unfortunately, I wasn't able to remove the `Seen` function set as creating a new `MCSymbolRefExpr` will always be unique, even if the same `MCSymbol` is used. This means that the new `WorkSet` wouldn't detect the duplicate and the function resource info expressions may end up with duplicate callees' resource info.

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 2]
```diff
@@ -163,23 +139,31 @@ void MCResourceInfo::assignResourceInfoExpr(
...
+      else
         ArgExprs.push_back(MCSymbolRefExpr::create(CalleeValSym, OutContext));
+
+      bool FoundRecursion = false;
+      while (!WorkSet.empty() && !FoundRecursion) {
+        auto It = WorkSet.begin();
+        const MCExpr *Expr = *It;
+        WorkSet.erase(Expr);
+
+        FoundRecursion = findSymbolInExpr(Sym, Expr, WorkSet);
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:162]: Looking explicitly for recursion as a case to handle still does not make sense to me. I expect a recursive visitor function that handles the recursive naturally, without trying to treat it as a special case. Have the function return null if it isn't resolvable?

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 3]
```diff
@@ -163,23 +139,31 @@ void MCResourceInfo::assignResourceInfoExpr(
...
     SmallPtrSet<const Function *, 8> Seen;
     ArgExprs.push_back(LocalConstExpr);
-    const Function &F = MF.getFunction();
-    Seen.insert(&F);
 
     for (const Function *Callee : Callees) {
       if (!Seen.insert(Callee).second)
         continue;
+
+      SmallPtrSet<const MCExpr *, 8> WorkSet;
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:149]: I expect to maintain the set for all callees to be visited, not redone on each one

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp (hunk 2 above)
Comment (JanekvO) [reply llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:162]: I may not completely understand the suggested approach but the reason I explicitly add `Sym` is because I want to explicitly check if `Sym` is part of a recursive definition and not so much whether `Sym` has any recursion as part of its expression. Is your suggested approach compatible with seeing whether `Sym` is part of the recursion or not?

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 4]
```diff
@@ -219,24 +226,18 @@ void MCResourceInfo::gatherResourceInfo(
...
-        while (!WorkSet.empty() && !FoundRecursion) {
-          auto It = WorkSet.begin();
-          const MCExpr *Expr = *It;
-          WorkSet.erase(Expr);
-
-          FoundRecursion = findSymbolInExpr(Sym, Expr, WorkSet);
-        }
-        if (CalleeValSym->isVariable() && !FoundRecursion)
+        if (!CalleeIsVar ||
+            (CalleeIsVar &&
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:235]: `CalleeIsVar &&` is redundant here

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 5]
```diff
@@ -146,24 +160,17 @@ void MCResourceInfo::assignResourceInfoExpr(
...
-        const MCExpr *Expr = *It;
-        WorkSet.erase(Expr);
-
-        FoundRecursion = findSymbolInExpr(Sym, Expr, WorkSet);
-      }
+      bool CalleeIsVar = CalleeValSym->isVariable();
 
-      if (CalleeValSym->isVariable() && !FoundRecursion)
+      if (!CalleeIsVar ||
+          (CalleeIsVar &&
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:168]: `CalleeIsVar &&` redundant

**Review by arsenm — COMMENTED** [review]
I've lost sight of the original problem. What is the problem with creating a recursive expression? Can you deal with the recursion when the expression is evaluated instead of avoiding creating it?

**Comment by JanekvO** [comment]
> What is the problem with creating a recursive expression?

The evaluation of the `MCExpr` will infinitely loop: https://github.com/llvm/llvm-project/issues/110863

> Can you deal with the recursion when the expression is evaluated instead of avoiding creating it?

It'd have to be in the `SymbolRef` case of `MCExpr::evaluateAsRelocatableImpl` which is an interface overloaded by all the target specific `MCExpr`. Perhaps I could add something in `AMDGPUMCExpr::evaluateAsRelocatableImpl` that deviates from the recursive walk to detect recursion but it would more than likely move the recursion detection I have here to `AMDGPUMCExpr::evaluateAsRelocatableImpl`. Additionally, that would still assume the recursion occurs within one of the AMDGPU specific `MCExpr` and not cover the case only looking through generic `MCExpr`.

**Review by arsenm — COMMENTED** [review]
It seems the precedent is for MCExprs to [not support recursion](https://github.com/llvm/llvm-project/blob/5c1752e368585e55c0335a7d7651fe43d42af282/llvm/lib/MC/MCParser/AsmParser.cpp#L6403)

If we are going this way, this code should be unified to deal with the weak edge cases.

Alternatively it feels more natural to directly support recursion in expressions, but maybe that is more difficult.

**Comment by JanekvO** [comment]
ping

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 6]
```diff
@@ -101,25 +101,28 @@ void MCResourceInfo::assignResourceInfoExpr(
...
     for (const Function *Callee : Callees) {
       if (!Seen.insert(Callee).second)
         continue;
+
       MCSymbol *CalleeFnSym = TM.getSymbol(&Callee->getFunction());
       MCSymbol *CalleeValSym =
           getSymbol(CalleeFnSym->getName(), RIK, OutContext);
-      ArgExprs.push_back(MCSymbolRefExpr::create(CalleeValSym, OutContext));
+      if (!CalleeValSym->isVariable() ||
+          !CalleeValSym->getVariableValue(/*isUsed=*/false)
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:118]: Comment that you need to avoid introducing a recursive expression

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp [hunk 7]
```diff
@@ -101,25 +101,28 @@ void MCResourceInfo::assignResourceInfoExpr(
...
+               ->isSymbolUsedInExpression(Sym)) {
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:119]: Can this miss adding other functions in the path to callee that we need to still add to the expression?

e.g. 

```
f1->f2->f3->f2
```

From f1, we see that callee f2 appears in a recursive expression, so it is skipped. but that will mean we do not add f3 to the expression, even though it is needed

File: llvm/test/CodeGen/AMDGPU/function-resource-usage.ll [hunk 8]
```diff
@@ -481,6 +481,132 @@ define amdgpu_kernel void @usage_direct_recursion(i32 %n) #0 {
...
+; GCN: .set multi_stage_recurse1.uses_vcc, 1
+; GCN: .set multi_stage_recurse1.uses_flat_scratch, 0
+; GCN: .set multi_stage_recurse1.has_dyn_sized_stack, 0
+; GCN: .set multi_stage_recurse1.has_recursion, 1
+; GCN: .set multi_stage_recurse1.has_indirect_call, 0
+; GCN: TotalNumSgprs: 38
+; GCN: NumVgprs: 41
+; GCN: ScratchSize: 16
+define void @multi_stage_recurse1(i32 %val) #2 {
+  call void @multi_stage_recurse2(i32 %val)
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/function-resource-usage.ll:511]: I think these test functions need some padding with some real register uses so the reported counts are more meaningful. Add some inline assembly with direct physical register uses?

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp (hunk 7 above)
Comment (JanekvO) [reply llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:122]: Yeah, sadly enough order matters in that it is possible for such a skip to occur. For now I've assumed worst case and taken the module level register maximums for recursion. Preferably I'd like to have cycle/SCC scope register maximums computed and used but I think that's out of scope for this PR.

**Comment by JanekvO** [comment]
Ping again, sorry

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp (hunk 7 above)
Comment (arsenm) [reply llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:122]: This should try to flatten the expression to remove the recursive edges

File: llvm/test/CodeGen/AMDGPU/multi-call-resource-usage-mcexpr.ll [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+; CHECK: .set qux.num_agpr, 0
+; CHECK: .set qux.numbered_sgpr, 32
+; CHECK: .set qux.private_seg_size, 0
+; CHECK: .set qux.uses_vcc, 0
+; CHECK: .set qux.uses_flat_scratch, 0
+; CHECK: .set qux.has_dyn_sized_stack, 0
+; CHECK: .set qux.has_recursion, 0
+; CHECK: .set qux.has_indirect_call, 0
+define void @qux() {
+entry:
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/multi-call-resource-usage-mcexpr.ll:14]: Needs some register usage content in this file

File: llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp (hunk 7 above)
Comment (JanekvO) [reply llvm/lib/Target/AMDGPU/AMDGPUMCResourceInfo.cpp:122]: Agreed, will do so in a follow up PR

**Comment by JanekvO** [comment]
ping

**Review by arsenm — APPROVED** [review]
lgtm but please continue working on flattening the expression instead of going to the worst case

**Comment by JanekvO** [comment]
Looking

**Comment by MaskRay** [comment]
The `isSymbolUsedInExpression` use within `parseAssignmentExpression` is a hack and should not be used externally. 
```
  if (Sym) {
    // Diagnose assignment to a label.
    //
    // FIXME: Diagnostics. Note the location of the definition as a label.
    // FIXME: Diagnose assignment to protected identifier (e.g., register name).
    if (Value->isSymbolUsedInExpression(Sym))
      return Parser.Error(EqualLoc, "Recursive use of '" + Name + "'");
    else if (Sym->isUndefined(/*SetUsed*/ false) && !Sym->isUsed() &&
             !Sym->isVariable())
      ; // Allow redefinitions of undefined symbols only used in directives.
    else if (Sym->isVariable() && !Sym->isUsed() && allow_redef)
      ; // Allow redefinitions of variables that haven't yet been used.
    else if (!Sym->isUndefined() && (!Sym->isVariable() || !allow_redef))
      return Parser.Error(EqualLoc, "redefinition of '" + Name + "'");
    else if (!Sym->isVariable())
      return Parser.Error(EqualLoc, "invalid assignment to '" + Name + "'");
    else if (!isa<MCConstantExpr>(Sym->getVariableValue()))
      return Parser.Error(EqualLoc,
                          "invalid reassignment of non-absolute variable '" +
                              Name + "'");
  } else if (Name == ".") {
```

If I ever have time to clean it, I think the traversal should be moved to AMDGPU.
