### PR TITLE
[LLDB][ELF] Fix section unification to not just use names.

### LINKED ISSUE #88001: [LLDB][ELF] LLDB gets confused if there are multiple .text sections in a binary
I had a Swift PR open (https://github.com/apple/swift/pull/72061) that changes how Swift handles the metadata sections (in particular), but as a consequence causes the compiler to set `SHF_GNU_RETAIN` on other sections as well. At time of writing, all of the tests are passing *except* some LLDB API tests, which was very puzzling.

The problem appears to be that, because of the behaviour of older versions of `ld.gold` (prior to binutils 2.36), `libswiftCore.so` ends up with two `.text` sections, and then when LLDB tries to print a Swift object, it attempts to call `Swift._DebuggerSupport.stringForPrintObject`, but gets mixed up and adds the offset it found for that function to the wrong `.text` section, jumps into the end of an entirely unrelated function and (eventually) crashes after triggering an assertion failure.

*The bug here is that LLDB appears to get confused about the presence of two `.text` sections, which leads to symbol lookups going awry.*

I've attached a small reproducer, which doesn't need Swift (or anything to do with Swift).

[lldb-two-text-sections.tar.gz](https://github.com/llvm/llvm-project/files/14906932/lldb-two-text-sections.tar.gz)

(We're tracking this internally as rdar://124467787.)

### PR DESCRIPTION
**Pull request by al45tair**
Section unification cannot just use names, because it's valid for ELF binaries to have multiple sections with the same name.  We should check other section properties too.

Fixes #88001.

rdar://124467787

### CODE REVIEW

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp [hunk 1]
```diff
@@ -1854,6 +1854,49 @@ class VMAddressProvider {
 };
 }
 
+namespace {
```
Comment (JDevlieghere) [inline lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1857]: Nit: LLVM and LLDB prefer static functions over anonymous namespaces.

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp [hunk 2]
```diff
@@ -1854,6 +1854,49 @@ class VMAddressProvider {
...
+         sect_iter != section_list.end();
+         ++sect_iter) {
+      if ((*sect_iter)->GetName() == name
+          && (*sect_iter)->GetType() == type
+          && (*sect_iter)->IsThreadSpecific() == thread_specific
+          && (*sect_iter)->GetPermissions() == permissions
+          && (*sect_iter)->GetFileSize() == file_size
+          && (*sect_iter)->GetByteSize() == byte_size
+          && (*sect_iter)->GetFileAddress() == vm_addr
+          && (*sect_iter)->GetLog2Align() == alignment) {
```
Comment (JDevlieghere) [inline lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1885]: This seems like it could be an `operator ==` in the Section class.

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp [hunk 3]
```diff
@@ -1854,6 +1854,49 @@ class VMAddressProvider {
...
+    offset_t file_size = section->GetFileSize();
+    offset_t byte_size = section->GetByteSize();
+    SectionType type = section->GetType();
+    bool thread_specific = section->IsThreadSpecific();
+    uint32_t permissions = section->GetPermissions();
+    uint32_t alignment = section->GetLog2Align();
+
+    for (auto sect_iter = section_list.begin();
+         sect_iter != section_list.end();
+         ++sect_iter) {
```
Comment (JDevlieghere) [inline lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1877]: Can this be a range-based for loop?

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp [hunk 4]
```diff
@@ -2067,10 +2110,8 @@ unsigned ObjectFileELF::ParseSymbols(Symtab *symtab, user_id_t start_id,
   SectionList *module_section_list =
       module_sp ? module_sp->GetSectionList() : nullptr;
 
-  // Local cache to avoid doing a FindSectionByName for each symbol. The "const
-  // char*" key must came from a ConstString object so they can be compared by
-  // pointer
-  std::unordered_map<const char *, lldb::SectionSP> section_name_to_section;
+  // Cache the section mapping
```
Comment (JDevlieghere) [inline lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:2113]: Nit: missing period. A map from SectionSP to SectionSP looks somewhat suspicious, might be worth explaining what the key and the value mean.

**Review by JDevlieghere — COMMENTED** [review]
Can we add a test for this with obj2yaml?

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 1 above)
Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1857]: This file already uses anonymous namespaces, but I'll change the function to `static` instead.

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 2 above)
Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1885]: I didn't want to do that, because I didn't want to give the impression that this was a general purpose way to compare two `Section`s. While it checks _many_ of the section attributes, it doesn't check all of them (intentionally in the case of which object they come from), and I think that would be surprising behaviour from an `==` operator.

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 3 above)
Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:1877]: Yes, it can (I just checked and apparently we can use C++17 in LLVM code, so that's nice :-)).

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 4 above)
Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:2113]: I'll improve the comment.

**Comment by al45tair** [comment]
> Can we add a test for this with obj2yaml?

Not sure what you're thinking here. We can't use `yaml2obj` to generate an object with this problem because that tool assumes symbols are in a uniquely named section (which is mostly reasonable), and `obj2yaml` doesn't exercise the code in LLDB. I'll take a look and see what we can do as a test.

**Comment by labath** [comment]
> > Can we add a test for this with obj2yaml?
> 
> Not sure what you're thinking here. We can't use `yaml2obj` to generate an object with this problem because that tool assumes symbols are in a uniquely named section 

[this](https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/yaml2obj/ELF/duplicate-section-names.yaml) test seems to indicate that's possible (the trick appears to me in `(n)` name tag suffixes). Can you give that a shot?

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 2 above)
Comment (labath) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp]: Am I correct in understanding that this code is used when unifying the sections of a separate debug file with a stripped file? If so, then I believe this comparison is too strict. An object file produced by `objcopy --only-keep-debug` will only have placeholder sections instead of the sections that contained actual code. That means (at least) their file size and file offset will be different from that in the original file.

I think it would be sufficient to use the file address (called virtual address in ELF), possibly confirmed by section name, as the unification key.

Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp]: I did wonder about exactly how strict we want to be (and exactly which things to compare). This isn't testing file offset, but you're right that it does check file size and maybe it shouldn't.

Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp]: @labath Let's get rid of the sizes; the other things should all be the same, correct?

**Comment by al45tair** [comment]
> [this](https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/yaml2obj/ELF/duplicate-section-names.yaml) test seems to indicate that's possible (the trick appears to me in `(n)` name tag suffixes). Can you give that a shot?

I've actually just included a binary file that exhibits the problem.

**Comment by labath** [comment]
> > [this](https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/yaml2obj/ELF/duplicate-section-names.yaml) test seems to indicate that's possible (the trick appears to me in `(n)` name tag suffixes). Can you give that a shot?
> 
> I've actually just included a binary file that exhibits the problem.

I saw that, but a textual test is definitely preferable, particularly after the linux xz fiasco. This wouldn't be the first test binary in our repo, but in this case, I think it actually adds a lot of value, since yaml2obj operates on the same level as what you are testing (so you can see the input of the test eyeball-verify that the expected output makes sense).

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 2 above)
Comment (labath) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp]: The section type can also change. You can see that with .text, because there we have a name-based fallback, but with anything else, it changes from "code" to "regular":
```$ bin/lldb-test object-file /tmp/a.debug  | grep -e foo -C 3
  Showing 1 subsections
    Index: 0
    ID: 0x6
    Name: .foo
    Type: regular
    Permissions: r-x
    Thread specific: no
$ bin/lldb-test object-file /tmp/a.out  | grep -e foo -C 3
  Showing 1 subsections
    Index: 0
    ID: 0x6
    Name: .foo
    Type: code
    Permissions: r-x
    Thread specific: no
```

The other fields are _probably_ fine.

**Comment by labath** [comment]
> > I saw that, but a textual test is definitely preferable, particularly after the linux xz fiasco. This wouldn't be the first test binary in our repo, but in this case, I think it actually adds a lot of value, since yaml2obj operates on the same level as what you are testing (so you can see the input of the test eyeball-verify that the expected output makes sense).
> 
> :-) Fair point (though this is very much not like the xz incident — I'm a colleague of Jonas's at Apple, albeit in a different team, with a fairly longstanding history of contributing to OSS projects, and doing something like that would be… very career limiting).
> 
> I'll have a go at changing things to use `yaml2obj`.

The new test looks great.

File: lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp (hunk 2 above)
Comment (al45tair) [reply lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp]: OK. I've removed the section type test as well.

**Comment by al45tair** [comment]
@labath @JDevlieghere Are we happy with this PR now? If so, I'll cherry pick it to the various Apple forks; I need it in order to merge https://github.com/apple/swift/pull/72061, which we need for both my fully statically linked Swift SDK work and for Amazon Linux 2023 support in Swift.

**Review by labath — APPROVED** [review]

**Review by JDevlieghere — APPROVED** [review]
Looks good to me as well.
