### PR TITLE
`__noop` not marked as constexpr #102064

### LINKED ISSUE #102064: `__noop` not marked as constexpr
https://godbo.lt/z/j1hG1YYqK

`constexpr int x = []{ __noop; return 0; }();`
flags: `-fms-extensions`

```
<source>:1:15: error: constexpr variable 'x' must be initialized by a constant expression
    1 | constexpr int x = []{ __noop; return 0; }();
      |               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:1:23: note: subexpression not valid in a constant expression
    1 | constexpr int x = []{ __noop; return 0; }();
      |                       ^~~~~~
<source>:1:19: note: in call to '[] {
    __noop();
    return 0;
}.operator()()'
    1 | constexpr int x = []{ __noop; return 0; }();
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by ofAlpaca**
Resolves #102064 
I think the problem is that the function `bool IntExprEvaluator::VisitBuiltinCallExpr(const CallExpr *E, unsigned BuiltinOp)` return default `false` directly when visiting expression of `__noop`.
Thus, `__noop` cannot be evaluated as constant initializer in here.
https://github.com/llvm/llvm-project/blob/b6603e1bf11dee4761e49af6581c8b8f074b705d/clang/lib/Sema/SemaDecl.cpp#L14402
By adding a `BI__noop` case in `bool IntExprEvaluator::VisitBuiltinCallExpr(const CallExpr *E, unsigned BuiltinOp)` should fix the problem.
Correct me if there is anything I misunderstood.

### CODE REVIEW

**Comment by ofAlpaca** [comment]
@DanielJump
Could you kindly help me review my commit?
Besides, I'm not sure how to solve the failed build test on GitHub.
The failed case is `C:\ws\src\clang\unittests\Support\TimeProfilerTest.cpp:278` on Windows platform.
It shows the following difference.
```
With diff:
@@ -7,5 +7,5 @@
 | | ParseFunctionDefinition (user)
 | PerformPendingInstantiations
-| | InstantiateFunction (fooA<int>, ./a.h:7)
-| | | InstantiateFunction (fooB<int>, ./b.h:3)
-| | | InstantiateFunction (fooMTA<int>, ./a.h:4)\n
+| | InstantiateFunction (fooA<int>, .\\a.h:7)
+| | | InstantiateFunction (fooB<int>, .\\b.h:3)
+| | | InstantiateFunction (fooMTA<int>, .\\a.h:4)\n
```
It looks like the problem is about Windows's backslash.
However, I don't know how this error relates to my code.

File: clang/test/SemaCXX/GH102064.cpp [hunk 1]
```diff
@@ -0,0 +1,3 @@
+// RUN: %clang_cc1 -std=c++20 -fms-extensions %s
+// expected-no-diagnostics
+constexpr int x = []{ __noop; return 0; }();
```
Comment (cor3ntin) [inline clang/test/SemaCXX/GH102064.cpp:3]: Can you move this test to test/SemaCXX/builtins.cpp ? thanks!

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -861,6 +861,8 @@ Bug Fixes to Compiler Builtins
 - Clang now allows pointee types of atomic builtin arguments to be complete template types
   that was not instantiated elsewhere.
 
+- Fix ``__noop`` not marked as constexpr. (#GH102064)
```
Comment (AaronBallman) [inline clang/docs/ReleaseNotes.rst:864]:
```suggestion
- ``__noop` can now be used in a constant expression. (#GH102064)
```

**Review by AaronBallman — APPROVED** [review]
Thank you! LGTM modulo tiny nits.

FWIW, the precommit CI failure looks unrelated to your changes, I wouldn't worry about it (the issue hopefully goes away if you rebase).

**Comment by zyn0217** [comment]
An off-topic concern:
The issue was initially assigned to @AdiSin123 three weeks ago. Did you talk to @AdiSin123 to ensure that @AdiSin123 gives up the fix? It would be polite to ask first in the issue before you start working on this.

**Comment by AdiSin123** [comment]
I am sorry, I couldn't make much headway in the last weeks because I was
still understanding the codebase. Please feel free to reassign. I will
attempt to take on issues in the future when I am much more prepared.

File: clang/test/SemaCXX/GH102064.cpp (hunk 1 above)
Comment (ofAlpaca) [reply clang/test/SemaCXX/GH102064.cpp]: @cor3ntin 
I have added this test to builtins.cpp.
I'm not sure if this is a good way to add this test.
Please have a look. Thanks!

**Comment by ofAlpaca** [comment]
@zyn0217
This comment explains. https://github.com/llvm/llvm-project/issues/95854#issuecomment-2185180676

File: clang/test/SemaCXX/GH102064.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/test/SemaCXX/GH102064.cpp]: You do not need the define/ifdef/etc

Comment (ofAlpaca) [reply clang/test/SemaCXX/GH102064.cpp]: If adding ``RUN: %clang_cc1 %s -std=c++20 -fms-extensions`` at the top line of builtins.cpp, without using define/ifdef, other testcases will fail.
Could @cor3ntin kindly give me more hints to this?

Comment (cor3ntin) [reply clang/test/SemaCXX/GH102064.cpp]: oh, because it's a MSVC extensions you can write 

```
#ifdef _MSC_VER
constexpr int x = []{ __noop; return 0; }();
#endif
```
(clang defines _MSC_VER, you do not need to do it)

Sorry, i did not realize it was a MS only extension

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks
Will you need me to merge that for you?

**Comment by ofAlpaca** [comment]
@cor3ntin 
Sure, thank you for the help.

**Comment by tbaederr** [comment]
You have to resolve the conflict in `ReleaseNotes.rst` firsrt
