### PR TITLE
[libc++][TZDB] Improves system time zone detection.

### LINKED ISSUE #105634: [libc++] tzdb throws if `/etc/localtime` is not a symlink
When `/etc/localtime` is a file rather than a symlink, tzdb throws. This can be seen e.g. in the following libc++ tests:

<details>

```
FAIL: llvm-libc++-shared.cfg.in :: std/time/time.zone/time.zone.db/time.zone.db.access/current_zone.pass.cpp (8284 of 9740)
******************** TEST 'llvm-libc++-shared.cfg.in :: std/time/time.zone/time.zone.db/time.zone.db.access/current_zone.pass.cpp' FAILED ********************
Exit Code: 250

Command Output (stdout):
--
# COMPILED WITH
/usr/lib/ccache/bin/i686-pc-linux-gnu-clang++ /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/std/time/time.zone/time.zone.db/time.zone.db.access/current_zone.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/support -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Werror=thread-safety -Wuser-defined-warnings  -lc++experimental -nostdlib++ -L /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -Wl,-rpath,/var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -lc++ -latomic -o /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir/t.tmp.exe
# executed command: /usr/lib/ccache/bin/i686-pc-linux-gnu-clang++ /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/std/time/time.zone/time.zone.db/time.zone.db.access/current_zone.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/support -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Werror=thread-safety -Wuser-defined-warnings -lc++experimental -nostdlib++ -L /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -Wl,-rpath,/var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -lc++ -latomic -o /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir/t.tmp.exe
# EXECUTED AS
/usr/bin/python3.12 /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/utils/run.py --execdir /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir --  /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir/t.tmp.exe
# executed command: /usr/bin/python3.12 /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/utils/run.py --execdir /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir -- /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.access/Output/current_zone.pass.cpp.dir/t.tmp.exe
# .---command stderr------------
# | libc++abi: terminating due to uncaught exception of type std::runtime_error: tzdb: the path '/etc/localtime' is not a symlink
# `-----------------------------
# error: command failed with exit status: 250

--

********************
FAIL: llvm-libc++-shared.cfg.in :: std/time/time.zone/time.zone.db/time.zone.db.tzdb/current_zone.pass.cpp (8298 of 9740)
******************** TEST 'llvm-libc++-shared.cfg.in :: std/time/time.zone/time.zone.db/time.zone.db.tzdb/current_zone.pass.cpp' FAILED ********************
Exit Code: 250

Command Output (stdout):
--
# COMPILED WITH
/usr/lib/ccache/bin/i686-pc-linux-gnu-clang++ /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/current_zone.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/support -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Werror=thread-safety -Wuser-defined-warnings  -lc++experimental -nostdlib++ -L /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -Wl,-rpath,/var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -lc++ -latomic -o /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir/t.tmp.exe
# executed command: /usr/lib/ccache/bin/i686-pc-linux-gnu-clang++ /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/current_zone.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/include/c++/v1 -I /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/test/support -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Werror=thread-safety -Wuser-defined-warnings -lc++experimental -nostdlib++ -L /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -Wl,-rpath,/var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/lib -lc++ -latomic -o /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir/t.tmp.exe
# EXECUTED AS
/usr/bin/python3.12 /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/utils/run.py --execdir /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir --  /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir/t.tmp.exe
# executed command: /usr/bin/python3.12 /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/libcxx/utils/run.py --execdir /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir -- /var/tmp/portage/sys-libs/libcxx-20.0.0_pre20240822/work/runtimes_build-abi_x86_32.x86/test/std/time/time.zone/time.zone.db/time.zone.db.tzdb/Output/current_zone.pass.cpp.dir/t.tmp.exe
# .---command stderr------------
# | libc++abi: terminating due to uncaught exception of type std::runtime_error: tzdb: the path '/etc/localtime' is not a symlink
# `-----------------------------
# error: command failed with exit status: 250

--

********************
```
</details>

While systemd requires `/etc/localtime` to be a symlink, there's no such requirement for non-systemd systems, and at least fresh non-systemd Gentoo installs still default to that (I'm going to work on changing that but the point remains that non-symlink `/etc/localtime` is still a valid scenario supported by glibc).

### PR DESCRIPTION
**Pull request by mordante**
On some (Linux) systems /etc/localtime is not a symlink to the time zone, but contains a copy of the binary time zone file. In these case there usually is a file named /etc/timezone which contains the text for the current time zone name.

Instead of throwing when /etc/localtime does not exist or is not a symlink use this fallback.

Fixes: #105634

### CODE REVIEW

**Comment by jrtc27** [comment]
This doesn't fully fix the bug. FreeBSD remains broken.

**Comment by mordante** [comment]
> This doesn't fully fix the bug. FreeBSD remains broken.

At the moment we don't support TZDB on FreeBSD, I've reached out privately to @emaste to get this working.
(There were some changes that needed to be made on the FreeBSD site, these are done now.)

File: libcxx/src/experimental/tzdb.cpp [hunk 1]
```diff
@@ -726,30 +759,29 @@ void __init_tzdb(tzdb& __tzdb, __tz::__rules_storage_type& __rules) {
...
   // - The time zone name is the target of the symlink /etc/localtime
   //   relative to /usr/share/zoneinfo/
+  //
+  // - The file /etc/timezone. This text file contains the name of the time
+  //   zone.
+  //
+  // On Linux systems it seems /etc/timezone is deprecated and being phased
+  // out. This file is used when /etc/localtime is not a symlink, but contains
+  // a copy of the binary time zone file. For more information and links see
+  // https://github.com/llvm/llvm-project/issues/105634
```
Comment (ldionne) [inline libcxx/src/experimental/tzdb.cpp:769]:
```suggestion
  // On Linux systems it seems /etc/timezone is deprecated and being phased
  // out. This file is used when /etc/localtime does not exist, or when it exists but is not a symlink. For more information and links see
  // https://github.com/llvm/llvm-project/issues/105634
```

IMO the sentence about "a copy of the binary time zone file" is not relevant since you don't check the contents anyway. The contents could be anything at all for what we know. I feel that removing that sentence  makes the comment less confusing.

**Review by ldionne — APPROVED** [review]
