### PR TITLE
[Modules] Delay deserialization of preferred_name attribute at r…

### LINKED ISSUE #56490: [Modules] Incorrect ODR checks caused by `preferred_name` attribute.
I met an incorrect ODR checks caused by `preferred_name`. Here is a reduced example.

```cpp
// string_view.h
template<class _CharT>
class basic_string_view;

typedef basic_string_view<char> string_view;

template<class _CharT>
class
__attribute__((__preferred_name__(string_view)))
basic_string_view {
public:
    basic_string_view() 
    {
    }
};

inline basic_string_view<char> foo()
{
  return basic_string_view<char>();
}
// A.cppm
module;
#include "string_view.h"
export module A;

// Use.cppm
module;
#include "string_view.h"
export module Use;
import A;
```

The input command line is:
```shell
clang++ -std=c++20 --precompile A.cppm -o A.pcm
clang++ -std=c++20 --precompile Use.cppm -fprebuilt-module-path=.  -fsyntax-only
```

The output would be the incorrect ODR warning:
```console
string_view.h:11:5: error: 'basic_string_view<char>::basic_string_view' from module 'A.<global>' is not present in definition of 'string_view' provided earlier
```

I've been fighting with the problem for several days. My current process is that when the ASTReader reads the `preferred_name` attribute, it would read the `string_view` type and find an existing one. However, the current behavior would create another RecordType for `string_view` despite there is already one. So here is the problem.

### PR DESCRIPTION
**Pull request by VitaNuo**
…ecord level.

This fixes the incorrect diagnostic emitted when compiling the following snippet

```
// string_view.h
template<class _CharT>
class basic_string_view;

typedef basic_string_view<char> string_view;

template<class _CharT>
class
__attribute__((__preferred_name__(string_view)))
basic_string_view {
public:
    basic_string_view() 
    {
    }
};

inline basic_string_view<char> foo()
{
  return basic_string_view<char>();
}
// A.cppm
module;
#include "string_view.h"
export module A;

// Use.cppm
module;
#include "string_view.h"
export module Use;
import A;
```

The diagnostic is 
```
string_view.h:11:5: error: 'basic_string_view<char>::basic_string_view' from module 'A.<global>' is not present in definition of 'string_view' provided earlier
```

The underlying issue is that deserialization of the `preferred_name` attribute triggers deserialization of `basic_string_view<char>`, which triggers the deserialization of the `preferred_name` attribute again (since it's attached to the `basic_string_view` template). 
The deserialization logic is implemented in a way that prevents it from going on a loop in a literal sense (it detects early on that it has already seen the `string_view` typedef when trying to start its deserialization for the second time), but leaves the typedef deserialization in an unfinished state. Subsequently, the `string_view` typedef from the deserialized module cannot be merged with the same typedef from `string_view.h`, resulting in the above diagnostic.

This PR resolves the problem by delaying the deserialization of the `preferred_name` attribute until the deserialization of the `basic_string_view` template is completed. As a result of deferring, the deserialization of the `preferred_name` attribute doesn't need to go on a loop since the type of the `string_view` typedef is already known when it's deserialized.

### CODE REVIEW

**Comment by VitaNuo** [comment]
Alternative approach to https://github.com/llvm/llvm-project/pull/122250.

File: clang/include/clang/Serialization/ASTReader.h [hunk 1]
```diff
@@ -1205,6 +1205,12 @@ class ASTReader
   /// been completed.
   std::deque<PendingDeclContextInfo> PendingDeclContextInfos;
 
+  struct PendingPreferredNameAttribute {
```
Comment (ilya-biryukov) [inline clang/include/clang/Serialization/ASTReader.h:1208]: NIT: there's nothing specific to `PreferredName` her, could we just call it `DeferredAttribute`?
(Same for functions that have it as a substring)

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 2]
```diff
@@ -3134,6 +3139,17 @@ Attr *ASTRecordReader::readAttr() {
   // Kind is stored as a 1-based integer because 0 is used to indicate a null
   // Attr pointer.
   auto Kind = static_cast<attr::Kind>(V - 1);
+  if (Kind == attr::PreferredName && D != nullptr) {
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:3142]: Could you add a comment explaining why we need to defer some attribute?

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 3]
```diff
@@ -3134,6 +3139,17 @@ Attr *ASTRecordReader::readAttr() {
...
+    if (D != nullptr) {
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:3143]: D is never null here, this if seems to be redundant.

Also, should we `assert` that `D != nullptr` when we deserialize `PreferredName`?
If we start deferring more attributes at some point, an assertion like this might not hold up, but it gives a good sanity check for preferred name specifically, because it should always be attached to some declaration.

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 4]
```diff
@@ -3159,13 +3175,27 @@ Attr *ASTRecordReader::readAttr() {
...
 
+Attr *ASTRecordReader::readAttr() { return readAttrImpl(nullptr); }
+
+/// Reads attributes from the current stream position.
+void ASTRecordReader::readAttributes(AttrVec &Attrs) {
+  readAttributesImpl(Attrs, nullptr);
+}
+
+/// Reads one attribute from the current stream position, advancing Idx.
+Attr *ASTRecordReader::readAttr(Decl *D) { return readAttrImpl(D); }
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:3192]: The behavior of this funciton is drastically different from `readAttr`, could we use a different name and document that it delays reading of some attributes?

Same for `readAttributes`

File: clang/include/clang/Serialization/ASTReader.h [hunk 5]
```diff
@@ -1205,6 +1205,12 @@ class ASTReader
...
+    uint64_t RecordIdx;
+    Decl *D;
```
Comment (ilya-biryukov) [inline clang/include/clang/Serialization/ASTReader.h:1210]: Could we use a more descriptive name and/or add a comment explaining why we have this `Decl` here?
`D` looks fine for parameters, but a little too short for a `struct`.

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 6]
```diff
@@ -4424,6 +4454,51 @@ void ASTReader::loadPendingDeclChain(Decl *FirstLocal, uint64_t LocalOffset) {
   ASTDeclReader::attachLatestDecl(CanonDecl, MostRecent);
 }
 
+void ASTReader::loadPreferredNameAttribute(
+    const PendingPreferredNameAttribute &PreferredNameAttribute) {
+  Decl *D = PreferredNameAttribute.D;
+  ModuleFile *M = getOwningModuleFile(D);
+
+  unsigned LocalDeclIndex = D->getGlobalID().getLocalDeclIndex();
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:4462]: I thought we might need to store the indices separately, but having the declaration around we actually have enough to look up the bitstream position.

Nice trick, kudos for coming up with this!

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 7]
```diff
@@ -4424,6 +4454,51 @@ void ASTReader::loadPendingDeclChain(Decl *FirstLocal, uint64_t LocalOffset) {
...
+  ASTRecordReader Record(*this, *Loc.F);
+  Expected<unsigned> MaybeRecCode = Record.readRecord(Cursor, Code);
+  if (!MaybeRecCode) {
+    llvm::report_fatal_error(
+        Twine(
+            "ASTReader::loadPreferredNameAttribute failed reading rec code: ") +
+        toString(MaybeCode.takeError()));
+  }
+  unsigned RecCode = MaybeRecCode.get();
+  if (RecCode != DECL_CXX_RECORD) {
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:4489]: Any reason to limit this to this particular `Decl`?
I think having a generic mechanism that works for any decls is fine here, just in case we need to defer more attributes.

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 8]
```diff
@@ -4424,6 +4454,51 @@ void ASTReader::loadPendingDeclChain(Decl *FirstLocal, uint64_t LocalOffset) {
...
+    llvm::report_fatal_error(
+        Twine("ASTReader::loadPreferredNameAttribute failed reading rec code: "
+              "expected CXXRecord") +
+        toString(MaybeCode.takeError()));
+  }
+
+  Record.skipInts(PreferredNameAttribute.RecordIdx);
+  Attr *PreferredNameAttr = Record.readAttr(nullptr);
+  AttrVec &Attrs = getContext().getDeclAttrs(D);
+  Attrs.push_back(PreferredNameAttr);
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTReaderDecl.cpp:4499]: NIT: maybe merge the two lines?

 `getContext().getDeclAttrs(D).push_back(PreferredNameAttr)`

File: clang/lib/Serialization/ASTWriter.cpp [hunk 9]
```diff
@@ -4925,6 +4930,11 @@ void ASTRecordWriter::AddAttr(const Attr *A) {
   Record.push_back(A->isRegularKeywordAttribute());
 
 #include "clang/Serialization/AttrPCHWrite.inc"
+
+  if (A->getKind() == attr::PreferredName)
+    // Record the actual size of preferred_name attribute (-1 to count the
```
Comment (ilya-biryukov) [inline clang/lib/Serialization/ASTWriter.cpp:4935]: LLVM Style Guide covers this situation and suggests to have braces when there are comments in the single branch, see https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements.

Could you add braces here?
The `if` above is a bit more borderline, but I'd also suggest adding braces there.

**Review by ilya-biryukov — COMMENTED** [review]
I know this is marked as `WIP`, but I find the direction promising so I went ahead and actually made a round of review.

Please wait for @ChuanqiXu9 in case he'll have more comments, but I hope two of us are not too far off in terms of where we want this to go.

File: clang/lib/Serialization/ASTWriter.cpp (hunk 9 above)
Comment (VitaNuo) [reply clang/lib/Serialization/ASTWriter.cpp:4935]: Sure, thank you.

File: clang/lib/Serialization/ASTReaderDecl.cpp (hunk 7 above)
Comment (VitaNuo) [reply clang/lib/Serialization/ASTReaderDecl.cpp:4489]: True. Though I think I still need to check that `RecCode` is a valid [DeclCode](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Serialization/ASTBitCodes.h#L1227).

File: clang/lib/Serialization/ASTReaderDecl.cpp (hunk 3 above)
Comment (VitaNuo) [reply clang/lib/Serialization/ASTReaderDecl.cpp:3143]: > D is never null here, this if seems to be redundant.

This is actually not true. This is a trick that allows to send deserialization on two different paths when (1) deserializing the decl in the main deserialization round vs. (2) deserializing the pending attribute.

In (1) Decl is not null, and the attribute is deferred (and the Decl stored in the pending attributes structure), whereas in (2) the deserialization of the attribute has been initiated by processing the pending attributes, and we don't want to send it on a circle by deferring it again, so we set the Decl to `nullptr` in this call `readOrDeferAttrImpl`.

**Comment by AaronBallman** [comment]
Can you add more details to the patch summary explaining why the changes are needed? That makes it easier for folks to review the patch but also helps us in the future when digging through historical changes. Thanks!

**Comment by VitaNuo** [comment]
> Can you add more details to the patch summary explaining why the changes are needed? That makes it easier for folks to review the patch but also helps us in the future when digging through historical changes. Thanks!

Sure, thank you for the comment.

**Comment by Endilll** [comment]
I don't feel qualified to review this, but I appreciate that you fix holes in my original quite naive implementation.

File: clang/include/clang/Serialization/ASTReader.h [hunk 10]
```diff
@@ -1205,6 +1205,23 @@ class ASTReader
...
   std::deque<PendingDeclContextInfo> PendingDeclContextInfos;
 
+  /// Deserialization of some attributes must be deferred since they refer
+  /// to themselves in their type (e.g., preferred_name attribute refers to the
+  /// typedef that refers back to the template specialization of the template
+  /// that the attribute is attached to).
+  /// More attributes that store TypeSourceInfo might be potentially affected,
+  /// see https://github.com/llvm/llvm-project/issues/56490 for details.
+  struct DeferredAttribute {
+    uint64_t RecordIdx;
```
Comment (ChuanqiXu9) [inline clang/include/clang/Serialization/ASTReader.h:1215]: nit: Add a comment to the field. e.g., something like the Index of the delayed attribute in the Record of the targeted decl.

File: clang/include/clang/Serialization/ASTReader.h [hunk 11]
```diff
@@ -1205,6 +1205,23 @@ class ASTReader
...
+    // Decl to attach a deferred attribute to.
+    Decl *ParentDecl;
```
Comment (ChuanqiXu9) [inline clang/include/clang/Serialization/ASTReader.h:1217]:
```suggestion
    Decl *TargetedDecl;
```

**Review by ChuanqiXu9 — COMMENTED** [review]
Thanks.

(1) Hardcoding is generally not good. And even if we have to, e.g., (we don't have an automatic mechanism to check if we need to defer an attribute), let's avoid hardcoding in both reader side and writer side. We can make this by adding a new bit in the record of attribute to indicate if we need to delay it or not in the reader side generally.

(2) Then I think we can keep the signature of `readAttr` as is, where it will always skip the check for the delay bit and always try to read it. Then we can add a `readOrDeferFor(Decl *D)` method as you did. The `readOrDeferFor` will try to read the `deferring` bits directly and if it is true, it will record the length `skipCount` and `D` to `PendingDeferredAttributes` . Otherwise, it will call `readAttr`. I think it is more clear.

File: clang/include/clang/Basic/Attr.td [hunk 12]
```diff
@@ -713,6 +713,10 @@ class Attr {
   // attribute may be documented under multiple categories, more than one
   // Documentation entry may be listed.
   list<Documentation> Documentation;
+  // Set to true if deserialization of this attribute must be deferred until 
+  // the parent Decl is fully deserialized (during header module file
+  // deserialization).
```
Comment (ChuanqiXu9) [inline clang/include/clang/Basic/Attr.td:718]: It reads better if we can give an example to describe when we want to defer it.

File: clang/include/clang/Basic/Attr.td [hunk 13]
```diff
@@ -3240,6 +3244,7 @@ def PreferredName : InheritableAttr {
   let InheritEvenIfAlreadyPresent = 1;
   let MeaningfulToClassTemplateDefinition = 1;
   let TemplateDependent = 1;
+  let DeferDeserialization = 1;
```
Comment (ChuanqiXu9) [inline clang/include/clang/Basic/Attr.td:3247]: Maybe it is better to add comment here to explain why we want to defer PreferredName.

File: clang/lib/Serialization/ASTReader.cpp [hunk 14]
```diff
@@ -10079,6 +10079,11 @@ void ASTReader::finishPendingActions() {
     }
     PendingDeducedVarTypes.clear();
 
+    // Load the delayed preferred name attributes.
+    for (unsigned I = 0; I != PendingDeferredAttributes.size(); ++I)
+      loadDeferredAttribute(PendingDeferredAttributes[I]);
+    PendingDeferredAttributes.clear();
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTReader.cpp:10085]:
```suggestion
    // Load the delayed preferred name attributes.
    while (!PendingDeferredAttributes.empty()) {
      auto DeferredAttributes = std::move(PendingDeferredAttributes);
      for (DeferredAttribute &DA : DeferredAttribute)
        loadDeferredAttribute(DA);
    }
```

Technically, it is possible to update `PendingDeferredAttributes` during `loadDeferredAttribute()`.

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 15]
```diff
@@ -3159,13 +3164,36 @@ Attr *ASTRecordReader::readAttr() {
...
 
+
+/// Reads one attribute from the current stream position, advancing Idx.
+/// For some attributes (where type depends on itself recursively), defer
+/// reading the attribute until the type has been read.
+Attr *ASTRecordReader::readOrDeferAttrFor(Decl *D) {
+  AttrReader Record(*this);
+  unsigned SkipCount = Record.readInt();
+  if (!SkipCount)
+    return readAttr();
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTReaderDecl.cpp:3183]: Now it assumes that `readAttr()` should be called after the skip bit. Then the caller has more responsibility. I feel it better to skip it in `readAttr` and not read here.

e.g.,
```suggestion
  unsigned SkipCount = Record.peekInt();
  if (!SkipCount)
    return readAttr();
```

**Review by ChuanqiXu9 — COMMENTED** [review]
LGTM basically.

File: clang/lib/Serialization/ASTReaderDecl.cpp (hunk 15 above)
Comment (VitaNuo) [reply clang/lib/Serialization/ASTReaderDecl.cpp:3183]: Ah nice idea. I didn't realize `peekInt()` is an option.

File: clang/lib/Serialization/ASTReader.cpp (hunk 14 above)
Comment (VitaNuo) [reply clang/lib/Serialization/ASTReader.cpp:10085]: Thanks. The original snippet seems more concise though, so it might be preferable to stick to it for now.

**Comment by VitaNuo** [comment]
Thank you for the review @ChuanqiXu9!

> (1) Hardcoding is generally not good. And even if we have to, e.g., (we don't have an automatic mechanism to check if we need to defer an attribute), let's avoid hardcoding in both reader side and writer side. We can make this by adding a new bit in the record of attribute to indicate if we need to delay it or not in the reader side generally.

Added a `DeferDeserialization` bit to `Attr` class that is set to `true` for the `preferred_name` and to `false` for all other attributes.
Depending on this field, the skip count field is set on the record (to the count of record fields to skip on initial read for the `preferred_name`, and to 0 otherwise).

> (2) Then I think we can keep the signature of readAttr as is, where it will always skip the check for the delay bit and always try to read it. Then we can add a readOrDeferFor(Decl *D) method as you did. The readOrDeferFor will try to read the deferring bits directly and if it is true, it will record the length skipCount and D to PendingDeferredAttributes . Otherwise, it will call readAttr. I think it is more clear.

Yes this makes sense. It seems like one field (skip count) should be enough.

File: clang/lib/Serialization/ASTReaderDecl.cpp [hunk 16]
```diff
@@ -3118,18 +3120,27 @@ class AttrReader {
...
+/// Reads one attribute from the current stream position, advancing Idx.
 Attr *ASTRecordReader::readAttr() {
   AttrReader Record(*this);
   auto V = Record.readInt();
   if (!V)
     return nullptr;
 
+  // Read and ignore the skip count, since attribute deserialization is not
+  // deferred on this pass.
+  Record.readInt();
```
Comment (ChuanqiXu9) [inline clang/lib/Serialization/ASTReaderDecl.cpp:3142]: nit: skipInt();

File: clang/include/clang/Serialization/ASTRecordReader.h [hunk 17]
```diff
@@ -83,6 +83,9 @@ class ASTRecordReader
   /// Returns the current value in this record, without advancing.
   uint64_t peekInt() { return Record[Idx]; }
 
+  /// Returns the next value in this record, without advancing.
+  uint64_t peekNextInt() { return Record[Idx + 1]; }
```
Comment (ChuanqiXu9) [inline clang/include/clang/Serialization/ASTRecordReader.h:87]:
```suggestion
  uint64_t peekInts(unsigned N) { return Record[Idx + N]; }
```
nit:

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM with nits.

**Comment by benlangmuir** [comment]
I see that this change has already been reverted by @ilya-biryukov , but FYI before this is re-applied: I am seeing crashes from this change if I attempt to bootstrap a build of clang with modules enabled on Darwin.  I haven't yet managed to minimize a test case, but compiling the following triggers the issue at least when using the current Darwin libc++ 

```
#  include <string_view>

template <class _CharT, class _Traits, class _Tp>
struct __can_be_converted_to_string_view
    : public _BoolConstant< is_convertible<const _Tp&, basic_string_view<_CharT, _Traits> >::value &&
                            !is_convertible<const _Tp&, const _CharT*>::value > {};

```

The crash is because we get a call to `loadDeferredAttribute ` with a  `nullptr` decl. During the read of `basic_string_view` from the module we end up calling `readAttributes` with no decl.  Not sure what was supposed to happen here.

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1c)
  * frame #0: 0x00000001032c293c clang++`clang::Decl::isFromASTFile(this=0x0000000000000000) const at DeclBase.h:786:39
    frame #1: 0x00000001032c28ec clang++`clang::ASTReader::getOwningModuleFile(this=0x000000015102d800, D=0x0000000000000000) const at ASTReader.cpp:8016:11
    frame #2: 0x00000001034642f8 clang++`clang::ASTReader::loadDeferredAttribute(this=0x000000015102d800, DA=0x0000600003cb01e0) at ASTReaderDecl.cpp:4517:19
    frame #3: 0x00000001032d35b4 clang++`clang::ASTReader::finishPendingActions(this=0x000000015102d800) at ASTReader.cpp:10244:7
    frame #4: 0x00000001032db234 clang++`clang::ASTReader::FinishedDeserializing(this=0x000000015102d800) at ASTReader.cpp:10799:5
    frame #5: 0x00000001033111bc clang++`clang::ExternalASTSource::Deserializing::~Deserializing(this=0x000000016fdeedf0) at ExternalASTSource.h:88:15
    frame #6: 0x000000010328fbec clang++`clang::ExternalASTSource::Deserializing::~Deserializing(this=0x000000016fdeedf0) at ExternalASTSource.h:87:22
    frame #7: 0x00000001032c5ddc clang++`clang::ASTReader::FindExternalVisibleDeclsByName(this=0x000000015102d800, DC=0x000000015157f240, Name=(Ptr = 5659675880), OriginalDC=0x000000015157f240) at ASTReader.cpp:8525:1
    frame #8: 0x0000000105794d78 clang++`clang::DeclContext::lookupImpl(clang::DeclarationName, clang::DeclContext const*) const + 716
    frame #9: 0x0000000104e13738 clang++`LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) + 108
```

**Comment by ilya-biryukov** [comment]
@benlangmuir thanks for pointing this out, we should definitely keep that in mind when relanding. We'll try to run the bootstrap process to fix that too.

Are the particular steps for the bootstraping you do documented somewhere? E.g. maybe we're lucky and one of the files in https://github.com/llvm/llvm-project/tree/main/clang/cmake/caches can be used for that?

**Comment by benlangmuir** [comment]
There's probably a better way, but I just built my first clang normally then built a second one with
`-DCMAKE_C_COMPILER` and `-DCMAKE_CXX_COMPILER` pointing to the first one, and `-DLLVM_ENABLE_MODULES=1` to enable modules.
