### PR TITLE
[analyzer] Fix assertion failure in `CXXInstanceCall::getCXXThisVal`

### LINKED ISSUE #69922: Clang static analysis assert in CXXInstanceCall::getCXXThisVal
While working with a build of clang that has assertions enabled, I found a simple repro for an assertion failure with tip of tree clang (e558be51bab051d1471d92e967f8a2aecc13567a to be precise):
https://github.com/llvm/llvm-project/blob/9330261143ccbe947ef0687fd20747ba47f26879/clang/lib/StaticAnalyzer/Core/CallEvent.cpp#L722

At the point where the assertion is triggered, `ThisVal.dump()` prints:
```
(reg_$1<long long Element{SymRegion{reg_$0<class a * this>},0 S64b,class a}.i>) & 1
```

Repro command-line:
```
clang -cc1 -analyze -analyzer-checker=core -x c++ repro.cpp
```

Contents of `repro.cpp`:
```
class a {
  void b();
  long long i;
  void d() { __builtin_bit_cast(a *, i & 1)->b(); }
};
```

### PR DESCRIPTION
**Pull request by steakhal**
Workaround the case when the `this` pointer is actually a `NonLoc`, by returning `Unknown` instead.
The solution isn't ideal, as `this` should be really a `Loc`, but due to how casts work, I feel this is our easiest and best option.

As this patch presents, I'm evaluating a cast to transform the `NonLoc`.
However, given that `evalCast()` can't be cast from `NonLoc` to a pointer type thingy (`Loc`), we end up with `Unknown`.
It is because `EvalCastVisitor::VisitNonLocSymbolVal()` only evaluates casts that happen from NonLoc to NonLocs.

When I tried to actually implement that case, I figured:
1) Create a `SymbolicRegion` from that `nonloc::SymbolVal`; but `SymbolRegion` ctor expects a pointer type for the symbol.
2) Okay, just have a `SymbolCast`, getting us the pointer type; but `SymbolRegion` expects `SymbolData` symbols, not generic `SymExpr`s, as stated:

> // Because pointer arithmetic is represented by ElementRegion layers,
> // the base symbol here should not contain any arithmetic.

3) We can't use `ElementRegion`s to perform this cast because to have an `ElementRegion`, you already have to have a `SubRegion` that you want to cast, but the point is that we don't have that.

At this point, I gave up, and just left a FIXME instead, while still returning `Unknown` on that path.
IMO this is still better than having a crash.

Fixes #69922

### CODE REVIEW

**Review by Xazax-hun — APPROVED** [review]

**Comment by Xazax-hun** [comment]
Hmm, I wonder if we should leave a FIXME comment, but it looks good to me.

**Comment by steakhal** [comment]
> Hmm, I wonder if we should leave a FIXME comment, but it looks good to me.

I was thinking where to put the FIXME, and as I explored that should be within the CastVisitor. After that, I argued, that then I should still have the (ineffective) `SVB.evalCast()` to actually exercise that path.
It should be a fancy way of returning `Unknown` now, but arguably for the better reason xD

@Xazax-hun WDYT?

**Comment by Xazax-hun** [comment]
> WDYT?

I like this! I hope we do not add too much redundant work, but at least we make it clear what is the plan to fix this in the future.

**Comment by steakhal** [comment]
> > WDYT?
> 
> I like this! I hope we do not add too much redundant work, but at least we make it clear what is the plan to fix this in the future.

Please approve the PR again, so that I could merge this after I give some time for others to look at this.

**Review by Xazax-hun — APPROVED** [review]

File: clang/test/Analysis/builtin_bitcast.cpp [hunk 1]
```diff
@@ -30,3 +30,24 @@ void test(int i) {
...
   // expected-warning@-1 {{&i [as 64 bit integer]}}
 }
+
+struct A {
+  int n;
+  void set(int x) {
+    n = x;
+  }
+};
+using ptr_size = decltype(sizeof(void *));
```
Comment (DonatNagyE) [inline clang/test/Analysis/builtin_bitcast.cpp:40]: Do I see it correctly that `ptr_size` just an alias of `size_t`? If yes, then why don't you use the standard name?

**Review by NagyDonat — COMMENTED** [review]
Basically LGTM, thanks for fixing this crash.

I don't give a formal approval because I didn't independently verify the correctness of the details, but I like the direction of the change.

File: clang/test/Analysis/builtin_bitcast.cpp [hunk 2]
```diff
@@ -30,3 +30,24 @@ void test(int i) {
...
+void gh_69922(ptr_size p) {
+  // expected-warning-re@+1 {{(reg_${{[0-9]+}}<ptr_size p>) & 1U}}
+  clang_analyzer_dump(__builtin_bit_cast(A*, p & 1));
```
[the remark this answers is not in the document]
Comment (steakhal) [reply clang/test/Analysis/builtin_bitcast.cpp:43]: Yes, that is to form a `SymExpr`, which is a `SymbolVal` (NonLoc) wrapping a `BO_And` `SymIntExpr` I think.

File: clang/test/Analysis/builtin_bitcast.cpp (hunk 1 above)
Comment (steakhal) [reply clang/test/Analysis/builtin_bitcast.cpp:40]: Fixed. Now using `size_t`.

Comment (DonatNagyE) [reply clang/test/Analysis/builtin_bitcast.cpp]: Thanks!
