### PR TITLE
[HLSL] Add support for modulo of floating point scalar and vectors

### LINKED ISSUE #135122: [HLSL] Add support for floating point modulo
clang-dxc is using c rules for modulo. That means modulo is not supported for floating point types.

https://hlsl.godbolt.org/z/zxxqqE7jG

## Errors
```bash
<source>:2:16: error: invalid operands to binary expression ('half' and 'int')
<source>:6:16: error: invalid operands to binary expression ('float' and 'int')
<source>:10:16: error: invalid operands to binary expression ('half2' (aka 'vector<half, 2>') and 'int')
<source>:14:16: error: invalid operands to binary expression ('float2' (aka 'vector<float, 2>') and 'int')
```

support needs to be added for float, half and the vector version of those two. 

DXC does not  support double or double vectors when targeting SPIRV or DirectX so that will become the default spec for now.

### PR DESCRIPTION
**Pull request by farzonl**
fixes #135122

SemaExpr.cpp - Make all doubles fail. Add sema support for float scalars and vectors when language mode is HLSL.
CGExprScalar.cpp - Allow emit frem when language mode is HLSL.

### CODE REVIEW

File: clang/lib/CodeGen/CGExprScalar.cpp [hunk 1]
```diff
@@ -3964,6 +3964,8 @@ Value *ScalarExprEmitter::EmitRem(const BinOpInfo &Ops) {
 
   if (Ops.Ty->hasUnsignedIntegerRepresentation())
     return Builder.CreateURem(Ops.LHS, Ops.RHS, "rem");
+  else if (CGF.getLangOpts().HLSL && Ops.Ty->hasFloatingRepresentation())
+    return Builder.CreateFRem(Ops.LHS, Ops.RHS, "rem");
   else
```
Comment (llvm-beanz) [inline clang/lib/CodeGen/CGExprScalar.cpp:3969]: I know this steps a little out from the code you're changing, but it would be a nice cleanup (https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return).
```suggestion
  if (CGF.getLangOpts().HLSL && Ops.Ty->hasFloatingRepresentation())
    return Builder.CreateFRem(Ops.LHS, Ops.RHS, "rem");
```

**Review by llvm-beanz — APPROVED** [review]

File: clang/test/CodeGenHLSL/BasicFeatures/frem_modulo.hlsl [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+ half2 half_vec_mod_by_half_vec(half2 p1, half2 p2 ) {
+// CHECK-LABEL: half_vec_mod_by_half_vec
+// CHECK: %rem = frem reassoc nnan ninf nsz arcp afn <2 x half> %{{.*}}, %{{.*}}
+    return  p1 % p2;
+}
+
+ half half_vec_mod_by_int(half p1) {
+// CHECK-LABEL: half_vec_mod_by_int
+// CHECK: %rem = frem reassoc nnan ninf nsz arcp afn half  %{{.*}}, 0xH4000
+    return  p1 % 2;
```
Comment (spall) [inline clang/test/CodeGenHLSL/BasicFeatures/frem_modulo.hlsl:37]: this wasn't abiguous?

**Review by spall — APPROVED** [review]

File: clang/test/CodeGenHLSL/BasicFeatures/frem_modulo.hlsl (hunk 2 above)
Comment (farzonl) [reply clang/test/CodeGenHLSL/BasicFeatures/frem_modulo.hlsl:37]: Thats a Good question. so no it isn't ambigious because in SemaExpr::CheckRemainderOperands if we get into either the `CheckVectorOperands` for the vector cases or `UsualArithmeticConversions` for the scalar cases.  the integer literal go  through a conversion to match the non literal type. I saw ints become halfs or floats depending on what the variable type was. 

The float literal however did not do this. The float literal would cast the  half variables to a float so to prevent this in the testing i cast the float literals to half. If thats a bug I'll try an address it in a future pr.
