### PR TITLE
[libc++][chrono] Fixes year_month year wrapping.

### LINKED ISSUE #73162: [libc++] std::chrono::year_month::operator+=(month) is broken
Like #63912, year_month::operator+= (and -= and probably more) do not increment the year.
https://godbolt.org/z/qds1oE7WM

### PR DESCRIPTION
**Pull request by mordante**
Adding months to a year_month should wrap the year when the month becomes greater than twelve or less than one.

This fixes the issue for year_month. Other classes with a year and month do not have this issue. This has been verified and tests are added to avoid possible regressions.

Also fixes some variable copy-paste errors in the tests.

Fixes https://github.com/llvm/llvm-project/issues/73162

### CODE REVIEW

File: libcxx/include/__chrono/year_month.h [hunk 1]
```diff
@@ -92,6 +92,26 @@ _LIBCPP_HIDE_FROM_ABI constexpr
 year_month operator-(const year_month& __lhs, const years& __rhs) noexcept
```
Comment (ldionne) [inline libcxx/include/__chrono/year_month.h:92]: Note to self: mark those operators as `inline` explicitly. Relying on `constexpr` for `inline` semantics is really not a good idea.

Comment (ldionne) [reply libcxx/include/__chrono/year_month.h:92]: https://github.com/llvm/llvm-project/issues/75227

File: libcxx/test/std/time/time.cal/time.cal.ymwdlast/time.cal.ymwdlast.members/plus_minus_equal_month.pass.cpp [hunk 2]
```diff
@@ -31,25 +31,34 @@ constexpr bool test() {
 
   for (unsigned i = 0; i <= 10; ++i) {
     year y{1234};
-    year_month_weekday_last ymwd(y, month{i}, weekday_last{Tuesday});
+    year_month_weekday_last ymwdl(y, month{i}, weekday_last{Tuesday});
```
Comment (ldionne) [inline libcxx/test/std/time/time.cal/time.cal.ymwdlast/time.cal.ymwdlast.members/plus_minus_equal_month.pass.cpp:34]: Ultra-nit: You could consider using `ymw` for year-month-weekday, since weekday is a single word. Just a thought.

**Review by ldionne — APPROVED** [review]

File: libcxx/test/std/time/time.cal/time.cal.ymwdlast/time.cal.ymwdlast.members/plus_minus_equal_month.pass.cpp (hunk 2 above)
Comment (mordante) [reply libcxx/test/std/time/time.cal/time.cal.ymwdlast/time.cal.ymwdlast.members/plus_minus_equal_month.pass.cpp:34]: the wd is the typical naming in the Standard. There is also weekday indexed so 'w' would be too short.
