### PR TITLE
[NVPTX] Fix lowering of i1 SETCC

### LINKED ISSUE #57405: [NVPTX] DAG->DAG Pattern Instruction Selection crashes on setcc
When compiling the following piece of code, NVPTX backend crashes.
The bug can be reproduced from LLVM14 or latest commit `e723c69b94`

You can find the reproduction here: https://llvm.godbolt.org/z/EWs3f5bsG

```llvm
define void @f(<32 x i1>* %A) {
BB:
  br label %BB1

BB1:                                              ; preds = %BB1, %BB
  %L = load <32 x i1>, <32 x i1>* %A, align 4
  %E1 = extractelement <32 x i1> %L, i1 false
  %E = extractelement <32 x i1> %L, i8 16
  %C = icmp sge i1 %E1, %E
  br i1 %C, label %BB1, label %BB2

BB2:                                              ; preds = %BB1
  %I = insertelement <32 x i1> zeroinitializer, i1 %E, i64 0
  store <32 x i1> %I, <32 x i1>* %A, align 4
  ret void
}
```
```console
LLVM ERROR: Cannot select: t14: i1 = setcc t304, t144, setge:ch
  t304: i1 = truncate t302
    t302: i16,ch = load<(load (s8) from %ir.A, align 4), anyext from i8> t0, t2, undef:i32
      t2: i32,ch = CopyFromReg t0, Register:i32 %1
        t1: i32 = Register %1
      t4: i32 = undef
  t144: i1 = truncate t142
    t142: i16,ch = load<(load (s8) from %ir.A + 2, align 2, basealign 4), anyext from i8> t0, t21, undef:i32
      t21: i32 = add nuw t2, Constant:i32<2>
        t2: i32,ch = CopyFromReg t0, Register:i32 %1
          t1: i32 = Register %1
        t20: i32 = Constant<2>
      t4: i32 = undef
In function: f
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/peter/aflplusplus-isel/llvm-project/build-debug/bin/llc -mtriple=nvptx setcc.ll
1.      Running pass 'Function Pass Manager' on module 'setcc.ll'.
2.      Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@f'
 #0 0x0000000003a45a1a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x0000000003a45bcb PrintStackTraceSignalHandler(void*) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x0000000003a44216 llvm::sys::RunSignalHandlers() /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Signals.cpp:103:5
 #3 0x0000000003a462f5 SignalHandler(int) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fd7f16e2980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #5 0x00007fd7f05d2e87 raise /build/glibc-uZu3wS/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #6 0x00007fd7f05d47f1 abort /build/glibc-uZu3wS/glibc-2.27/stdlib/abort.c:81:0
 #7 0x000000000396ca74 llvm::report_fatal_error(llvm::Twine const&, bool) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Support/ErrorHandling.cpp:125:5
 #8 0x00000000037bec8b /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:3765:3
 #9 0x00000000037bc222 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:3667:9
#10 0x0000000001e0e299 llvm::NVPTXDAGToDAGISel::SelectCode(llvm::SDNode*) /home/peter/aflplusplus-isel/llvm-project/build-debug/lib/Target/NVPTX/NVPTXGenDAGISel.inc:86754:1
#11 0x0000000001e00944 llvm::NVPTXDAGToDAGISel::Select(llvm::SDNode*) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp:505:1
#12 0x00000000037afdb9 llvm::SelectionDAGISel::DoInstructionSelection() /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1153:5
#13 0x00000000037aee0a llvm::SelectionDAGISel::CodeGenAndEmitDAG() /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:933:3
#14 0x00000000037ad7dd llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, bool&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:685:1
#15 0x00000000037ad27b llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1591:11
#16 0x00000000037aa81d llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:464:3
#17 0x0000000001e004e5 llvm::NVPTXDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp:46:3
#18 0x000000000281fadd llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:85:8
#19 0x0000000002ef9146 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1430:23
#20 0x0000000002efdf72 llvm::FPPassManager::runOnModule(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1476:16
#21 0x0000000002ef9a19 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1545:23
#22 0x0000000002ef958d llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535:16
#23 0x0000000002efe251 llvm::legacy::PassManager::run(llvm::Module&) /home/peter/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1672:3
#24 0x0000000000d1ad70 compileModule(char**, llvm::LLVMContext&) /home/peter/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:737:41
#25 0x0000000000d190f2 main /home/peter/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:418:13
#26 0x00007fd7f05b5c87 __libc_start_main /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:344:0
#27 0x0000000000d188fa _start (/home/peter/aflplusplus-isel/llvm-project/build-debug/bin/llc+0xd188fa)
Aborted
```

### LINKED ISSUE #58428: [NVPTX] `icmp i1` used as branching condition crashes backend
## Description

When `icmp` instruction with `i1` operands is used as a branching condition, `nvptx` backend crashes with error `Cannot select: t20: i1 = setcc t29, t24, setule:ch`.

`icmp eq` and `icmp ne` do not have the problem.
The problem doesn't exist when `icmp` is used on `i8`, `i16`, etc.

## Minimal Reproduction

https://godbolt.org/z/Taj5G5aGW

### Code

```ll
define i8 @f(i1 %0, i1 %1) {
BB:
  %C = icmp ugt i1 %1, %0
  br i1 %C, label %BB1, label %BB2

BB1:
  ret i8 1

BB2:
  ret i8 127
}
```

### Stack Trace

```console
LLVM ERROR: Cannot select: t20: i1 = setcc t29, t24, setule:ch
  t29: i1 = truncate t31
    t31: i16,ch = load<(dereferenceable invariant load (s8) from `ptr addrspace(101) null`, addrspace 101), anyext from i8> t0, TargetExternalSymbol:i64'f_param_1', undef:i64
      t7: i64 = TargetExternalSymbol'f_param_1'
      t3: i64 = undef
  t24: i1 = truncate t26
    t26: i16,ch = load<(dereferenceable invariant load (s8) from `ptr addrspace(101) null`, addrspace 101), anyext from i8> t0, TargetExternalSymbol:i64'f_param_0', undef:i64
      t1: i64 = TargetExternalSymbol'f_param_0'
      t3: i64 = undef
In function: f
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./llvm-project/build-debug/bin/llc -mtriple=nvptx64 ./crash-reports/dagisel-nvptx/2.ll
1.	Running pass 'Function Pass Manager' on module './crash-reports/dagisel-nvptx/2.ll'.
2.	Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@f'
 #0 0x0000000003b0f2aa llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x0000000003b0f45b PrintStackTraceSignalHandler(void*) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x0000000003b0daa6 llvm::sys::RunSignalHandlers() /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Support/Signals.cpp:104:5
 #3 0x0000000003b0fb85 SignalHandler(int) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f3ee5b58980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #5 0x00007f3ee4a48e87 raise /build/glibc-CVJwZb/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #6 0x00007f3ee4a4a7f1 abort /build/glibc-CVJwZb/glibc-2.27/stdlib/abort.c:81:0
 #7 0x0000000003a352f4 llvm::report_fatal_error(llvm::Twine const&, bool) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Support/ErrorHandling.cpp:125:5
 #8 0x00000000038829cb /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:3779:3
 #9 0x000000000387ff62 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:3681:9
#10 0x0000000001e968e9 llvm::NVPTXDAGToDAGISel::SelectCode(llvm::SDNode*) /home/henry/aflplusplus-isel/llvm-project/build-debug/lib/Target/NVPTX/NVPTXGenDAGISel.inc:86782:1
#11 0x0000000001e88f94 llvm::NVPTXDAGToDAGISel::Select(llvm::SDNode*) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp:505:1
#12 0x0000000003873a69 llvm::SelectionDAGISel::DoInstructionSelection() /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1165:5
#13 0x0000000003872aba llvm::SelectionDAGISel::CodeGenAndEmitDAG() /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:936:3
#14 0x000000000387148d llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, bool&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:688:1
#15 0x0000000003870f2b llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1603:11
#16 0x000000000386e4d6 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:467:3
#17 0x0000000001e88b35 llvm::NVPTXDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp:46:3
#18 0x00000000028bfd55 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:91:8
#19 0x0000000002fa7ca6 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1430:23
#20 0x0000000002facad2 llvm::FPPassManager::runOnModule(llvm::Module&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1476:16
#21 0x0000000002fa8579 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1545:23
#22 0x0000000002fa80ed llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535:16
#23 0x0000000002facdb1 llvm::legacy::PassManager::run(llvm::Module&) /home/henry/aflplusplus-isel/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1672:3
#24 0x0000000000d3dd1c compileModule(char**, llvm::LLVMContext&) /home/henry/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:737:41
#25 0x0000000000d3c0c2 main /home/henry/aflplusplus-isel/llvm-project/llvm/tools/llc/llc.cpp:418:13
#26 0x00007f3ee4a2bc87 __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:344:0
#27 0x0000000000d3b8ca _start (./llvm-project/build-debug/bin/llc+0xd3b8ca)
```

### PR DESCRIPTION
**Pull request by AlexMaclean**
Add DAG legalization support for expanding i1 SETCC nodes using appropriate logical operations to simulate integer comparisons. Use these expansions to handle i1 SETCC in NVPTX.

fixes #58428 and #57405

### CODE REVIEW

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 1]
```diff
@@ -2666,6 +2667,46 @@ SDValue NVPTXTargetLowering::LowerShiftLeftParts(SDValue Op,
   }
 }
 
+// Lowers SETCC nodes that aren't directly supported by our arch.
```
Comment (arsenm) [inline llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: Should use setCondCodeAction and not reinvent all of this

Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: @arsenm Can you please explain a little further how I can use setCondCodeAction to avoid all of this?

Comment (arsenm) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: It's an additional legality table because the single type based legality rules are insufficient for compares. It's the same as setting expand / custom / promote, except for the specific condition code and type

**Comment by Artem-B** [comment]
How much of a difference would it make on the SASS level if we were to just extend i1 arguments to i32 and then just run `setp` on them, instead of logical ops done directly on predicates? 

E.g. setp.lt(i1 a, i1 b) -> `setp.lt(i32 selp(a, 1, 0), i32 selp(b(1,0)))`

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp (hunk 1 above)
Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: Hmm, this table seems to be used inconsistently, does the type represent the value which is produced by the SETCC node or the types of the values which are being compared?

https://github.com/llvm/llvm-project/blob/c1cec8c/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L8798
vs.
https://github.com/llvm/llvm-project/blob/c1cec8c/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L4994

Also what is the advantage of using this table over the current approach? What will I be able to avoid reinventing?

**Comment by AlexMaclean** [comment]
> How much of a difference would it make on the SASS level if we were to just extend i1 arguments to i32 and then just run `setp` on them, instead of logical ops done directly on predicates?
> 
> E.g. setp.lt(i1 a, i1 b) -> `setp.lt(i32 selp(a, 1, 0), i32 selp(b(1,0)))`

The sass will likely be much worse in most cases if we add the selp instructions in here.

**Comment by Artem-B** [comment]
You're right. At least, ptxas-11.x does not optimize those selects: https://godbolt.org/z/GdPo4Tr1a

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: The types being compared.

You are reinventing condition code legalization here: https://github.com/llvm/llvm-project/blob/c1cec8c0dc5b0296f0bc86745b867ff72c0a21e3/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L11832

And generic code can no longer accurately query which conditions are legal, which is why you have the hack to check if SETCC is legal

Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2670]: Sorry, I'm still confused. I don't see anything like the boolean expansion I'm using for i1 in the LegalizeSetCCCondCode function. 

> And generic code can no longer accurately query which conditions are legal, which is why you have the hack to check if SETCC is legal

I think I'm going to need to add a check for legality to the dag combine no matter what, I suppose I can check this table instead. 

Also, is existing code like this incorrect? 

https://github.com/llvm/llvm-project/blob/c1cec8c0dc5b0296f0bc86745b867ff72c0a21e3/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L4994

Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:2674]: Okay, I've update the code to use the CondCode table. Not sure if this is what you had in mind though, I don't think it has made the implementation significantly simpler. I also did have to update a couple uses of the table which seemed incorrect. 

@arsenm does this look better?

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 2]
```diff
@@ -668,6 +668,11 @@ NVPTXTargetLowering::NVPTXTargetLowering(const NVPTXTargetMachine &TM,
     setTruncStoreAction(VT, MVT::i1, Expand);
   }
 
+  setCondCodeAction({ISD::SETNE, ISD::SETEQ, ISD::SETUGE, ISD::SETULE,
+                     ISD::SETUGT, ISD::SETULT, ISD::SETGT, ISD::SETLT,
+                     ISD::SETGE, ISD::SETLE},
+                    MVT::i1, Custom);
```
Comment (justinfargnoli) [inline llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:674]: Would `Expand` work here?

Comment (justinfargnoli) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:674]: If it doesn't work out of the box, should we instead expand the implementation of [`TLI.LegalizeSetCCCondCode()`](https://github.com/llvm/llvm-project/blob/dd1c99bac4dc1d5ceeadc79dd31fa12f3e615f18/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L11853-L11983)?

Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:674]: The boolean rules I've added are not present in the generic legalizer, so I don't think so. I suppose I could add them there instead, but NVPTX would be the only target using them.

Comment (justinfargnoli) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:674]: If it makes sense for something to live in `.../CodeGen/SelectionDAG/*`, I think we should implement it there instead of in `.../Target/NVPTX/*`. 

This is also my assumption of what @arsenm was asking for [above](https://github.com/llvm/llvm-project/pull/115035#discussion_r1829788004). 

CC @arsenm to correct me.

Comment (jholewinski) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:674]: If there is nothing PTX-specific about the expansion (which seems to be the case), I would agree that this could be part of the target-independent expansion. Even if NVPTX is the only backend that uses it, it would be good to make it easier for future backends that may have a use for it.

**Comment by AlexMaclean** [comment]
@arsenm ping for your thoughts on these discussions

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 3]
```diff
@@ -18738,8 +18738,9 @@ SDValue DAGCombiner::rebuildSetCC(SDValue N) {
       if (LegalTypes)
         SetCCVT = getSetCCResultType(SetCCVT);
       // Replace the uses of XOR with SETCC
-      return DAG.getSetCC(SDLoc(N), SetCCVT, Op0, Op1,
-                          Equal ? ISD::SETEQ : ISD::SETNE);
+      const ISD::CondCode CC = Equal ? ISD::SETEQ : ISD::SETNE;
+      if (!LegalOperations || TLI.isCondCodeLegal(CC, Op0.getSimpleValueType()))
+        return DAG.getSetCC(SDLoc(N), SetCCVT, Op0, Op1, CC);
```
Comment (Artem-B) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18743]: This could use an explanation. Previously we'd return SETCC unconditionally. Now we're only doing it... sometimes? While I know what `TLI.isCondCodeLegal` is for, it's not quite obvious how/why our decision here depends on `LegalOperations`.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 4]
```diff
@@ -4966,7 +4966,7 @@ SDValue TargetLowering::SimplifySetCC(EVT VT, SDValue N0, SDValue N1,
         APInt C = C1 + 1;
         ISD::CondCode NewCC = (Cond == ISD::SETLE) ? ISD::SETLT : ISD::SETULT;
         if ((DCI.isBeforeLegalizeOps() ||
-             isCondCodeLegal(NewCC, VT.getSimpleVT())) &&
+             isCondCodeLegal(NewCC, OpVT.getSimpleVT())) &&
```
Comment (Artem-B) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4969]: This looks like an independent bug fix, which has a good chance of exposing issues or changing compiler output. 
You may consider submitting it as a separate patch.

Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:4969]: Sounds good, I've created https://github.com/llvm/llvm-project/pull/116082 to land this separately

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 3 above)
Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp]: I'm disabling this particular transform from running after operation legalization on targets where the SETCC which would be created is not legal. I'm allowing the fold to happen prior to operation legalization in case this folding could trigger other transformations which might be beneficial.

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 5]
```diff
@@ -2666,6 +2671,46 @@ SDValue NVPTXTargetLowering::LowerShiftLeftParts(SDValue Op,
...
+SDValue NVPTXTargetLowering::LowerSETCC(SDValue Op, SelectionDAG &DAG) const {
+  SDValue L = Op->getOperand(0);
+  SDValue R = Op->getOperand(1);
+
+  if (L.getValueType() != MVT::i1)
+    return SDValue();
+
+  SDLoc DL(Op);
+  SDValue Ret;
+  switch (cast<CondCodeSDNode>(Op->getOperand(2))->get()) {
```
[the remark this answers is not in the document]
Comment (AlexMaclean) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp]: Okay, I've moved this expansion to LegalizeSetCCCondCode.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 6]
```diff
@@ -11874,6 +11874,47 @@ bool TargetLowering::LegalizeSetCCCondCode(SelectionDAG &DAG, EVT VT,
...
+      case ISD::SETUGE: // X >=u Y  -->  X == 1 | Y == 0  -->  ~Y | X
+      case ISD::SETLE:  // X <=s Y  -->  X == 1 | Y == 0  -->  ~Y | X
+        Ret = DAG.getNode(ISD::OR, dl, MVT::i1, LHS,
+                          DAG.getNOT(dl, RHS, MVT::i1));
+        break;
+      }
+
+      LHS = DAG.getZExtOrTrunc(Ret, dl, VT);
+      RHS = SDValue();
+      CC = SDValue();
```
Comment (justinfargnoli) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11914]: Explained [here](https://github.com/llvm/llvm-project/blob/196d5fdff1cb7b600dcf11b5464be4fc72dba675/llvm/include/llvm/CodeGen/TargetLowering.h#L5539-L5542).

File: llvm/test/CodeGen/NVPTX/i1-icmp.ll [hunk 7]
```diff
@@ -0,0 +1,193 @@
...
+; CHECK-NEXT:    mov.b32 %r4, 1;
+; CHECK-NEXT:    st.param.b32 [func_retval0], %r4;
+; CHECK-NEXT:    ret;
+; CHECK-NEXT:  $L__BB2_2: // %bb2
+; CHECK-NEXT:    mov.b32 %r3, 127;
+; CHECK-NEXT:    st.param.b32 [func_retval0], %r3;
+; CHECK-NEXT:    ret;
+  %p1 = icmp sgt i32 %a, 1
+  %p2 = icmp sgt i32 %b, 1
+  %c = icmp sgt i1 %p1, %p2
```
Comment (justinfargnoli) [inline llvm/test/CodeGen/NVPTX/i1-icmp.ll:93]: Can we add tests for the unsigned variants?

File: llvm/test/CodeGen/NVPTX/i1-icmp.ll [hunk 8]
```diff
@@ -0,0 +1,193 @@
...
+; CHECK-NEXT:    ret;
+  %p1 = icmp sgt i32 %a, 1
+  %p2 = icmp sgt i32 %b, 1
+  %c = icmp eq i1 %p1, %p2
+  br i1 %c, label %bb1, label %bb2
+bb1:
+  ret i32 1
+bb2:
+  ret i32 127
+}
```
Comment (justinfargnoli) [inline llvm/test/CodeGen/NVPTX/i1-icmp.ll:36]: Can we refactor this to:
```
define i1 @icmp_i1_eq(i1 %a, i1 %b) {
  %c = icmp eq i1 %a, %b
  ret i1 %c
}
```

Comment (AlexMaclean) [reply llvm/test/CodeGen/NVPTX/i1-icmp.ll:36]: No, setcc used by a brcond is handled differently and that is part of the problem.

https://github.com/llvm/llvm-project/blob/6a58c531762a78a3336793891cedbb44b9ed9eb0/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L18715

File: llvm/test/CodeGen/NVPTX/i1-icmp.ll (hunk 7 above)
Comment (AlexMaclean) [reply llvm/test/CodeGen/NVPTX/i1-icmp.ll:93]: Added

File: llvm/test/CodeGen/NVPTX/i1-icmp.ll (hunk 8 above)
Comment (justinfargnoli) [reply llvm/test/CodeGen/NVPTX/i1-icmp.ll:36]: And why not
```
define i32 @f(i1 %0, i1 %1) {
BB:
  %C = icmp ugt i1 %1, %0
  br i1 %C, label %BB1, label %BB2

BB1:
  ret i32 1

BB2:
  ret i32 127
}
```
like in the reproducer?

**Review by justinfargnoli — APPROVED** [review]
Overall, LGTM :)

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 9]
```diff
@@ -11874,6 +11874,47 @@ bool TargetLowering::LegalizeSetCCCondCode(SelectionDAG &DAG, EVT VT,
...
     }
 
+    // Special case: expand i1 comparisons using logical operations.
+    if (OpVT == MVT::i1) {
+      SDValue Ret;
+      switch (CCCode) {
+      default:
+        llvm_unreachable("Unknown integer setcc!");
+      case ISD::SETEQ: // X == Y  -->  ~(X ^ Y)
+        Ret = DAG.getNOT(dl, DAG.getNode(ISD::XOR, dl, MVT::i1, LHS, RHS),
```
Comment (justinfargnoli) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: Does this need to be guarded by `TLI.isLegal(ISD::XOR)`?

Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: I'd prefer not to. NVPTX is the only target using these expansions and we don't have any way to expand if not. I don't see what the point of adding them would be.

Comment (justinfargnoli) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: My question boils down to: will `xor` be legalized if it's generated for a target that doesn't support it? In other words, can `Expand` generate illegal code? 

My assumption was no, but based on your answer, I'm gathering that `Expand` can generate illegal code and rely on the legalizer to legalize it. Is that correct?

**Comment by AlexMaclean** [comment]
@arsenm @Artem-B when you have a minute could I please get another round of review on this change.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 9 above)
Comment (Artem-B) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: I think the issue here is that there's more than one possible interpretation of "lower SetCC(i1) differently". NVPTX can do it via logical ops on predicates, other targets may not. On other targets it may be something else. Whoever would use "setCondCodeAction(...,Expand)" would have no idea what it would expand into. This should at least be documented. If/when we would encounter a target which would have a different way of expanding setcc, we would probably need a more nuanced hint to tell LLVM which flavor we actually want.

I think at the moment only Hexagon uses `setCondCodeAction(...,i1, Expand)`. It would be good to check what effect this change has on them.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 10]
```diff
@@ -18754,8 +18754,9 @@ SDValue DAGCombiner::rebuildSetCC(SDValue N) {
       if (LegalTypes)
         SetCCVT = getSetCCResultType(SetCCVT);
       // Replace the uses of XOR with SETCC
-      return DAG.getSetCC(SDLoc(N), SetCCVT, Op0, Op1,
-                          Equal ? ISD::SETEQ : ISD::SETNE);
+      const ISD::CondCode CC = Equal ? ISD::SETEQ : ISD::SETNE;
+      if (!LegalOperations || TLI.isCondCodeLegal(CC, Op0.getSimpleValueType()))
```
[the remark this answers is not in the document]
Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18758]: Presumably it will infinite loop the combiner without this

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp [hunk 11]
```diff
@@ -11874,6 +11874,47 @@ bool TargetLowering::LegalizeSetCCCondCode(SelectionDAG &DAG, EVT VT,
       return true;
     }
 
+    // Special case: expand i1 comparisons using logical operations.
+    if (OpVT == MVT::i1) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11878]: Why does this need the type special case? LegalizeSetCCCondCode should do as asked regardless of the type

Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11878]: > Why does this need the type special case? 

The logical simplifications we're using to expand setcc for i1 will not be correct for larger types.

> LegalizeSetCCCondCode should do as asked regardless of the type

In theory yes, but this isn't the case today, and creating a valid expansion for all types x cond-codes would be a time consuming way to add a lot of in practice dead code.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (Artem-B) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18758]: OK. That should also be mentioned in the comments.

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp [hunk 12]
```diff
@@ -18753,7 +18753,9 @@ SDValue DAGCombiner::rebuildSetCC(SDValue N) {
       EVT SetCCVT = N.getValueType();
       if (LegalTypes)
         SetCCVT = getSetCCResultType(SetCCVT);
-      // Replace the uses of XOR with SETCC
+      // Replace the uses of XOR with SETCC. Note, avoid this transformation if
+      // it would introduce illegal operations post-legalization as this can
+      // result in an infinite loop.
```
Comment (Artem-B) [inline llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18758]: "result in an infite loop" could use more details. " converting it to xor->setcc here, and expanding setcc->xor if the back-end requested it."

Speaking of which. I assume the infinite loop affects only targets that have `Expand` set on the op. Can we narrow the condition from `!Legal` to `==Expand` ?

**Review by Artem-B — APPROVED** [review]
LGTM with a nit.

File: llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp (hunk 11 above)
Comment (arsenm) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: Do you have a more specific example for "not correct for larger types"? It's not an arbitrary wide typed value. The result conforms to getTargetBooleanContents, which in turn should respect all of the logical expansions

Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp:11884]: Most of these expansions take advantage of the unique nature of the i1 type. For example consider signed greater than, this will only be true for i1s if and only if the first operand is 0 and the second is -1, hence it can be expressed as ~X & Y. This sort of bit manipulation is of course totally invalid for any larger type. 

To see that this transformation is okay for i1, and not for a larger type here is an alive2 where the transform has been expressed on llvm IR: https://alive2.llvm.org/ce/z/6jS_rA

File: llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp (hunk 12 above)
Comment (AlexMaclean) [reply llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18758]: I can update to make the comment more descriptive but I'm not sure about narrowing the logic. `isCondCodeLegal` is used it lots of places to prevent combines that would produce illegal nodes and I'm not sure there would be a benefit to performing this combine if the resulting nodes are not legal. Further, Custom legalization or promotion could still maybe result in some sort of infinite loop. Is is alright if I leave the check as is?

**Review by arsenm — APPROVED** [review]
