### PR TITLE
[Clang] Fix crash when transforming a `DependentAddressSpaceType`

### LINKED ISSUE #101685: [clang] Crash on templated type with address space
Clang crashes with a TypeLocBuilder assertion when run on this code (https://godbolt.org/z/or16hfTzf), no other command line options necessary:

```
template <int AS>
using ASPtrTy = void [[clang::address_space(AS)]] *;

template <int AS>
struct EntryTy {
    ASPtrTy<AS> Base;
};
```
> clang::TypeLoc clang::TypeLocBuilder::pushImpl(clang::QualType, size_t, unsigned int): Assertion `TLast == LastTy && "mismatch between last type and new type's inner type"' failed.

### PR DESCRIPTION
**Pull request by Sirraide**
We were forgetting to pass the `TypeLocBuilder` along to `TransformType`, causing us to complain if we then tried to build a `DependentAddressSpaceTypeLoc` because the inner `TypeLoc` was missing from the TLB.

Fixes #101685.

### CODE REVIEW

File: clang/lib/Sema/TreeTransform.h [hunk 1]
```diff
@@ -5838,7 +5839,7 @@ QualType TreeTransform<Derived>::TransformDependentAddressSpaceType(
   } else {
     TypeSourceInfo *DI = getSema().Context.getTrivialTypeSourceInfo(
         Result, getDerived().getBaseLocation());
-    TransformType(TLB, DI->getTypeLoc());
+    TLB.TypeWasModifiedSafely(DI->getType());
```
Comment (Sirraide) [inline clang/lib/Sema/TreeTransform.h:5842]: I’m candidly not familiar enough with `TypeLocBuilder` to know if this is the correct solution to this, but without this, we now crash if the resulting type *isn’t* dependent, e.g. in
```c++
template <int AS>
using ASPtrTy = void [[clang::address_space(AS)]] *;

ASPtrTy<1> x;
```

Comment (mizvekov) [reply clang/lib/Sema/TreeTransform.h:5842]: It does look like it is always safely modified, because in the non-dependent case, we will just add qualifiers to the type, and we don't currently track source locations for qualifiers.

See `BuildAddressSpaceAttr` implementation.

But the `getTrivialTypeSourceInfo` is unnecessary in this case, you can remove it.:

```suggestion
    TLB.TypeWasModifiedSafely(Result);
```

Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h]: > But the `getTrivialTypeSourceInfo` is unnecessary in this case, you can remove it.:

Done

Comment (jdoerfert) [reply clang/lib/Sema/TreeTransform.h]: Does this pass the existing tests?

Comment (Sirraide) [reply clang/lib/Sema/TreeTransform.h]: I ran the tests both after adding the call to `TypeWasModifiedSafely` and after making this change here just now, and they were all fine.

**Review by mizvekov — APPROVED** [review]
LGTM, Thanks!

**Comment by jdoerfert** [comment]
Thanks a lot!
