### PR TITLE
[AMDGPU] Re-enable atomic optimization of uniform fadd/fsub with result

### LINKED ISSUE #97554: AMDGPUAtomicOptimizer: re-enable uniform path for fadd/fsub with result
See #96479: the uniform path for fadd/fsub was disabled because it can return the wrong value in the first active lane of the result in the presence of NaNs and signed zeros.

We should find a way to fix and re-enable it, e.g. by overwriting the first active lane of `%y * +0.0` with -0.0. And maybe this can be optimized more if certain values are known not to be zero or nan.

### PR DESCRIPTION
**Pull request by jayfoad**
Fix various problems to do with the first active lane of the result of
optimized fp atomics, as explained in the comment.

Fixes #97554

### CODE REVIEW

**Review by pravinjagtap — APPROVED** [review]

File: llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp [hunk 1]
```diff
@@ -937,18 +930,25 @@ void AMDGPUAtomicOptimizerImpl::optimizeAtomic(Instruction &I,
...
-        // - If BroadcastI is -0.0 and V is positive we will return +0.0 instead
-        //   of -0.0.
         LaneOffset = B.CreateFMul(V, Mbcnt);
         break;
       }
       }
     }
-    Value *const Result = buildNonAtomicBinOp(B, Op, BroadcastI, LaneOffset);
+    Value *Result = buildNonAtomicBinOp(B, Op, BroadcastI, LaneOffset);
+    if (isAtomicFloatingPointTy) {
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp:939]: Can you skip this if the function has the no-signed-zeros attribute?
