### PR TITLE
[clang-tidy] Avoid diagnosing std::array initializations for modernize-use-designated-initializers

### LINKED ISSUE #133715: modernize-use-designated-initializers Clang-Tidy check reports std::array when IgnoreSingleElementAggregates is false
With code like:
```c++
#include <array>

std::array small_primes{2, 3, 5, 7};
```
it issues the following (see [Compiler Explorer](https://godbolt.org/z/fEoYch83q)):
```none
[<source>:3:24: warning: use designated initializer list to initialize 'array<int, 4>' [modernize-use-designated-initializers]](javascript:;)
    3 | std::array small_primes{2, 3, 5, 7};
      |                        ^~~~~~~~~~~~
      |                         .[0]= .[1]= .[2]= .[3]=
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.1/../../../../include/c++/15.0.1/array:102:5: note: aggregate type is defined here
  102 |     struct array
      |     ^
1 warning generated.
```

Interestingly, the suggestion to use `.[i]=` is completely wrong:
```c++
#include <array>

std::array small_primes{.[0] = 2, .[1] = 3, .[2] = 5, .[3] = 7};
```
as the `.` there causes compilation error ([Compiler Explorer](https://godbolt.org/z/xM6T58h1v)):
```none
<source>:3:26: error: expected a field designator, such as '.field = 4'
    3 | std::array small_primes{.[0] = 2, .[1] = 3, .[2] = 5, .[3] = 7};
      |                          ^
1 error generated.
Compiler returned: 1
```

Finally, use of the same without `.`:
```c++
#include <array>

std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
```
results in other issues ([Compiler Explorer](https://godbolt.org/z/hdb5ePrb3)):
```none
<source>:3:25: warning: array designators are a C99 extension [-Wc99-designator]
    3 | std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
      |                         ^~~
<source>:3:25: error: array designator cannot initialize non-array type 'std::array<enable_if_t<is_same_v<int, int> && is_same_v<int, int> && is_same_v<int, int>, int>, 1 + sizeof...(_Up)>' (aka 'array<int, 1 + sizeof...(_Up)>')
<source>:3:34: error: array designator cannot initialize non-array type 'std::array<enable_if_t<is_same_v<int, int> && is_same_v<int, int> && is_same_v<int, int>, int>, 1 + sizeof...(_Up)>' (aka 'array<int, 1 + sizeof...(_Up)>')
    3 | std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
      |                                  ^
<source>:3:43: error: array designator cannot initialize non-array type 'std::array<enable_if_t<is_same_v<int, int> && is_same_v<int, int> && is_same_v<int, int>, int>, 1 + sizeof...(_Up)>' (aka 'array<int, 1 + sizeof...(_Up)>')
    3 | std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
      |                                           ^
<source>:3:52: error: array designator cannot initialize non-array type 'std::array<enable_if_t<is_same_v<int, int> && is_same_v<int, int> && is_same_v<int, int>, int>, 1 + sizeof...(_Up)>' (aka 'array<int, 1 + sizeof...(_Up)>')
    3 | std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
      |                                                    ^
<source>:3:59: warning: missing field '_M_elems' initializer [-Wmissing-designated-field-initializers]
    3 | std::array small_primes{[0] = 2, [1] = 3, [2] = 5, [3] = 7};
      |                                                           ^
2 warnings and 4 errors generated.
Compiler returned: 1
```

### PR DESCRIPTION
**Pull request by RiverDave**
**Edit:**
I suggest we avoid diagnosing initializers for  `std::array` type. The fixit provided is incorrect as observed in **#133715.** The only workaround would require C99-style array designators which don’t really align with the purpose of this check. This would also generate extra compiler warnings. 

Fixes #133715

### CODE REVIEW

**Comment by carlosgalvezp** [comment]
> I found interesting was the fact that you could access the implementation-defined internal array field

Yes, this is required in order for `std::array` to be an aggregate type.

File: clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp [hunk 1]
```diff
@@ -119,13 +119,18 @@ UseDesignatedInitializersCheck::UseDesignatedInitializersCheck(
 void UseDesignatedInitializersCheck::registerMatchers(MatchFinder *Finder) {
   const auto HasBaseWithFields =
       hasAnyBase(hasType(cxxRecordDecl(has(fieldDecl()))));
+
+  // see #133715
+  const auto IsSTLArray =
+      hasType(qualType(hasDeclaration(recordDecl(hasName("::std::array")))));
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp:125]: I can imagine this issue can trigger on other similar cases, for example if one creates their own `std::array` class.

Can we make this a bit more generic, for example not warn of 1) the class is an aggregate and 2) it contains only one member and 3) that member is an array type?

**Comment by carlosgalvezp** [comment]
Actually, it seems to me that `IgnoreSingleElementAggregates` should already be handling this situation. If it doesn't, there's a bug there that should be fixed, instead of patching it for `std::array`?

**Review by carlosgalvezp — CHANGES_REQUESTED** [review]
We should fix `IgnoreSingleElementAggregates` instead.

**Comment by RiverDave** [comment]
> We should fix `IgnoreSingleElementAggregates` instead.

great observation, will fix

**Comment by RiverDave** [comment]
> We should fix `IgnoreSingleElementAggregates` instead.

Very good observation I didn't get this detail when investigating this bug. indeed, we shouldn't warn when the 3 conditions you previously mentioned:

> 1) the class is an aggregate and 2) it contains only one member and 3) that member is an array type?

 are true and `IgnoreSingleElementAggregates` is toggled off

**Comment by RiverDave** [comment]
> We should fix `IgnoreSingleElementAggregates` instead.

Just to be clear,  I suppose we're looking to fix `std::array` + `IgnoreSingleElementAggregates = false` as It's the only problematic combination I could analyze. The fixit this check provides on aggregate types with a single field of array type, seem to be correct to me: https://godbolt.org/z/Tahfa7onP

File: clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp [hunk 2]
```diff
@@ -119,13 +119,18 @@ UseDesignatedInitializersCheck::UseDesignatedInitializersCheck(
...
+
   Finder->addMatcher(
       initListExpr(
           hasType(cxxRecordDecl(RestrictToPODTypes ? isPOD() : isAggregate(),
                                 unless(HasBaseWithFields))
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp:130]: Shouldn't we put the condition here instead? Since we already are inside a cxxRecordDecl, we can just check the `hasName` in it?

**Comment by carlosgalvezp** [comment]
Ok, I see, let's disable for ::std::array then, generalize in the future if we come across a similar use case.

File: clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp (hunk 2 above)
Comment (RiverDave) [reply clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp]: Good catch, fixed.

**Comment by RiverDave** [comment]
> Ok, I see, let's disable for ::std::array then, generalize in the future if we come across a similar use case.

Thanks, your feedback has been addressed.

File: clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp [hunk 3]
```diff
@@ -122,7 +122,10 @@ void UseDesignatedInitializersCheck::registerMatchers(MatchFinder *Finder) {
   Finder->addMatcher(
       initListExpr(
           hasType(cxxRecordDecl(RestrictToPODTypes ? isPOD() : isAggregate(),
-                                unless(HasBaseWithFields))
+                                unless(anyOf(HasBaseWithFields,
+                                             IgnoreSingleElementAggregates
+                                                 ? hasName("::std::array")
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp:127]: The condition seem wrong? "If `IgnoreSingleElementAggregates` is true, then ignore `std::array`. Shouldn't it be the other way around?

Regardless, I believe we want to always ignore `std::array`, regardless of `IgnoreSingleElementAggregates`, since the private member is never intended to be used by the caller. 

So I would just simplify to `unless(anyOf(HasBaseWithFields, hasName("::std::array")))

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -182,6 +182,11 @@ Changes in existing checks
   ``constexpr`` and ``static``` values on member initialization and by detecting
   explicit casting of built-in types within member list initialization.
 
+- Improved :doc:`modernize-use-designated-initializers
+  <clang-tidy/checks/modernize/use-designated-initializers>` check by avoiding
+  diagnosing designated initializers for ``std::array`` initializations when
```
Comment (carlosgalvezp) [inline clang-tools-extra/docs/ReleaseNotes.rst:187]: Please document this exception also in `IgnoreSingleElementAggregates`

**Review by carlosgalvezp — CHANGES_REQUESTED** [review]
Please add a unit test demonstrating that the related issue is fixed.

File: clang-tools-extra/docs/ReleaseNotes.rst (hunk 4 above)
Comment (RiverDave) [reply clang-tools-extra/docs/ReleaseNotes.rst]: Done

File: clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp (hunk 3 above)
Comment (RiverDave) [reply clang-tools-extra/clang-tidy/modernize/UseDesignatedInitializersCheck.cpp]: Thanks for clearing out my confusion!. Should be fixed now.

**Comment by RiverDave** [comment]
> Please add a unit test demonstrating that the related issue is fixed.

Added 👍

**Review by HerrCai0907 — CHANGES_REQUESTED** [review]
exclude std::array don't resolve root problem here. It can also happen in user defined class.
e.g. https://godbolt.org/z/cn46MT5Mn

But maybe it could be handled in another PR? since std::array is a special case that we don't know the detail member name in std::array.

**Review by HerrCai0907 — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp [hunk 5]
```diff
@@ -209,3 +209,18 @@ struct S15{
   S15(S14& d):d{d}{}
   S14& d;
 };
+
+//Issue #133715
+namespace std {
```
Comment (HerrCai0907) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-designated-initializers.cpp:214]: clang-tidy@main will also not give warning for this code.

**Review by HerrCai0907 — CHANGES_REQUESTED** [review]

**Comment by RiverDave** [comment]
Ping @carlosgalvezp :)

**Review by carlosgalvezp — APPROVED** [review]
LGTM!

**Comment by carlosgalvezp** [comment]
> It can also happen in user defined class.

Yes. But it's unclear what the behavior of the check should be. For `std::array`, it's clear, because one must not touch the internal element. For a user-defined type, "it depends" on how the user wants to design their struct. 

If the need comes, I envision we will need some sort of option so people can add other types on top `std::array` to be excluded from the check. But let's cross that bridge when we get there :)

**Comment by carlosgalvezp** [comment]
@RiverDave Do you have permissions to land the PR, or shall I do it for you?

**Comment by RiverDave** [comment]
> @RiverDave Do you have permissions to land the PR, or shall I do it for you?

Don't have permissions [yet](https://github.com/issues/created?issue=llvm%7Cllvm-project%7C131971)... You can merge it for me!
