### PR TITLE
[clang-format] Fix poor spacing in `AlignArrayOfStructures: Left`

### LINKED ISSUE #62904: clang-format poor spacing with braces initializer
`test.c` containing:
```c
static const CMD_HANDLER_T command_handlers[] =
{
    {   "a",            HandleA             },
    {   "bb",           HandleBB            },
    {   "ccc",          HandleCCC           },
    {   NULL,           NULL                },
};
```

Command:

```shell
clang-format -style="{ SpacesInParentheses: true, AlignArrayOfStructures: Left }" test.c > test.out.c
```

Result:

```c
static const CMD_HANDLER_T command_handlers[] = {
    {"a",    HandleA  },
    { "bb",  HandleBB },
    { "ccc", HandleCCC},
    { NULL,  NULL     },
};
```

Anomalous things:

* For the first row only, there is no space between the opening brace and the first value.
* For the row with the widest last value, there is no space between the last value and the closing brace.

I have tested this with Clang-Format v13.0.1, v15.0.7 and v16.0.0, with the same results.

### PR DESCRIPTION
**Pull request by XDeme1**
Fixes llvm/llvm-project#62904

`AlignArrayOfStructures: Left` combined with `SpacesInParentheses: true` causes the first cell of every row to have 1 additional space.
We were only setting the first cell of the first row to be against the left brace, now every row will be against the left brace.

### CODE REVIEW

**Comment by XDeme** [comment]
@HazardyKnusperkeks ping

**Review by HazardyKnusperkeks — APPROVED** [review]
Sorry, seems I've missed this change.

File: clang/lib/Format/WhitespaceManager.cpp [hunk 1]
```diff
@@ -1366,11 +1366,12 @@ void WhitespaceManager::alignArrayInitializersLeftJustified(
...
-  if (Changes[CellIter->Index].NewlinesBefore == 0)
-    Changes[CellIter->Index].Spaces = BracePadding;
-  else
-    Changes[CellIter->Index].Spaces = CellDescs.InitialSpaces;
+  // The first cell of every row needs to be against the left brace.
+  for (const auto *Next = CellIter; Next; Next = Next->NextColumnElement)
+    if (Changes[Next->Index].NewlinesBefore == 0)
+      Changes[Next->Index].Spaces = BracePadding;
+    else
+      Changes[Next->Index].Spaces = CellDescs.InitialSpaces;
```
Comment (owenca) [inline clang/lib/Format/WhitespaceManager.cpp:1374]:
```suggestion
  for (const auto *Next = CellIter; Next; Next = Next->NextColumnElement) {
    auto &Change = Changes[Next->Index];
    Change.Spaces = Change.NewlinesBefore == 0 ? BracePadding : CellDescs.InitialSpaces;
  }
```

**Review by owenca — APPROVED** [review]
