### PR TITLE
[Sema] Diagnose by-value copy constructors in template instantiations

### LINKED ISSUE #80963: Clang fails to detect illegal copy constructor with template class as its parameter
The following code is apparently illegal, as the declaration of `A(A<V,T>)` should be treated as a copy constructor, which forces passing the argument by reference. While clang ignores that error and accepts it:

```c++
template < class T, class V > struct A
{
    A ();
    A (A &);
    A (A < V,T >);
};

void f () 
{
    A <int, int> (A < int, int >());
}
```

Note that if replace `A<V,T>` with `A<T,T>` or `A<V,V>`, the code is still accepted. But when replacing it with `A<T,V>`, the code is correctly rejected.

Reducing the number of template class arguments to 1 (`template <class T> A` and `A(A<T>)`) also makes sense. We suspect the bug will occur only if the template argument list in copy ctor parameter is not identical to that in class declaration.

[https://godbolt.org/z/GKv3E6c4f](https://godbolt.org/z/GKv3E6c4f)

### PR DESCRIPTION
**Pull request by Megan0704-1**
Fixes #80963 

This PR ensures Clang diagnoses by-value copy constructors in implicitly instantiated class templates (e.g., `A<int, int>(A<int, int>)`), per [class.copy.ctor]. 

Changes: 
- Remove `TSK_ImplicitInstantiation` check in `SemaDeclCXX.cpp`.
- Add `!isFunctionTemplateSpecialization()` to skip templated constructors.
- Add regression tests.

### CODE REVIEW

**Comment by Megan0704-1** [comment]
@erichkeane, @shafik 
Could you please take a look and let me know if it looks good to you? Thank you very much!

File: clang/test/SemaCXX/copy-ctor-template.cpp [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+template<class T, class V>
+struct B{
+    B();
+    template<class U> B(U); // No error (templated constructor)
+};
+
+void g() {
+    B<int, int> b = B<int, int>(); // should use implicit copy constructor
+}
```
Comment (cor3ntin) [inline clang/test/SemaCXX/copy-ctor-template.cpp:22]: Can you add a test for @hubert-reinterpretcast comment here
https://github.com/llvm/llvm-project/issues/80963#issuecomment-2716322960

Can you add tests for something like
`A<int, double> a = A<double, int>();` // not a copy constructor

**Review by cor3ntin — COMMENTED** [review]
Thanks for working on this 

Can you add a changelog entry in clang/docs/ReleaseNotes.rst (in the bug fixes to c++ section)?

Thanks

File: clang/test/SemaCXX/copy-ctor-template.cpp (hunk 1 above)
Comment (Megan0704-1) [reply clang/test/SemaCXX/copy-ctor-template.cpp:22]: Thanks for the review! I’ll add tests for the A<int, double> case and update the PR shortly.

**Comment by Megan0704-1** [comment]
Thanks for your feedback and review!! I’ve updated the changelog and the test file to include the rvalue-to-lvalue case and templated constructor scenario. Please let me know if there’s anything else!

**Review by cor3ntin — APPROVED** [review]
LGTM. Thanks for fixing this issue!

Will you need me to merge this for you?

**Comment by Megan0704-1** [comment]
Thank you for reviewing and approving the PR!
Yes, please merge it for me. Thanks again for all your help!

**Comment by cor3ntin** [comment]
@Megan0704-1 Can you look into the test failures? thanks

**Comment by Megan0704-1** [comment]
@cor3ntin 
Thank you for flagging the test failures! 

I’ve investigated them, and here’s what I found: 
Failed Tests in constructor-template.cpp: 
- The failures occurred because the test wasn’t annotated to expect the new diagnostics introduced by the fix (e.g., A<int, int> instantiations now emit errors for invalid by-value copy constructors). 

Fix it by updating the test to: 
- Add expected-error to lines 142, 159, 172 (invalid by-value constructors when T = U). 
- Add expected-note to lines 147, 164, 176 (template instantiation points). 
- Remove an incorrect expected-error from line 76 (valid template specialization). 

Please Let me know if further adjustments are needed~

File: clang/lib/Sema/SemaDeclCXX.cpp [hunk 2]
```diff
@@ -10921,8 +10921,8 @@ void Sema::CheckConstructor(CXXConstructorDecl *Constructor) {
   //   parameters have default arguments.
   if (!Constructor->isInvalidDecl() &&
       Constructor->hasOneParamOrDefaultArgs() &&
-      Constructor->getTemplateSpecializationKind() !=
-          TSK_ImplicitInstantiation) {
+      !Constructor->isFunctionTemplateSpecialization()
+          ) {
```
Comment (shafik) [inline clang/lib/Sema/SemaDeclCXX.cpp:10925]: Did you run clang-format on this? I am surprised it would leave the `)` on the line like that but maybe I am off.

Comment (Megan0704-1) [reply clang/lib/Sema/SemaDeclCXX.cpp:10925]: Thank you for catching this, and I am so sorry for the oversight.
I forgot to run clang-format before merging. 
Should I submitt a follow-up PR to fix the formatting issues?

**Comment by avikivity** [comment]
> This error is [produced for the following code](https://github.com/carbon-language/carbon-lang/pull/5170):
> 
> ```c++
> template <typename KeyT>
> class SetView {
>   SetView(SetView<std::remove_const_t<KeyT>> other_view)
>     requires(!std::same_as<KeyT, std::remove_const_t<KeyT>>);
> };
> ```
> 
> ... which is never an eligible copy constructor. Is that intended? If this is in line with the language rules, perhaps we should file a core issue.
> 
> [Edit: I've mailed the core reflector.]

Can you link to the defect report please?
