### PR TITLE
[LLVM] [X86] Fix integer overflows in frame layout for huge frames

### LINKED ISSUE #48911: Computation of locals' offsets is wrong when stack size exceeds 2G
|  |  |
| --- | --- |
| Bugzilla Link | [49567](https://llvm.org/bz49567) |
| Version | trunk |
| OS | All |
| CC | @topperc,@cuviper,@jdm,@RKSimon,@phoebewang,@rotateright,@oToToT |

## Extended Description 
Given the following test case:

    ; RUN: llc -O0 -mtriple=x86_64 < %s
    ; RUN: llc -O0 -mtriple=i686 < %s

    %large = type [2148000000 x i8]

    define void @banana() unnamed_addr #0 {
      %1 = alloca %large, align 1
      %2 = alloca %large, align 1
      %3 = getelementptr inbounds %large, %large* %1, i64 0, i64 0
      store i8 42, i8* %3, align 1
      %4 = getelementptr inbounds %large, %large* %2, i64 0, i64 0
      store i8 43, i8* %4, align 1
      ret void
    }

Will produce the following assembly:

	movabsq	$4295999872, %rax               # imm = 0x1000FC180
	subq	%rax, %rsp
	.cfi_def_cfa_offset 1032584
	movb	$42, -2146967424(%rsp)
	movb	$43, -128(%rsp)
	movabsq	$4295999872, %rax               # imm = 0x1000FC180
	addq	%rax, %rsp
	.cfi_def_cfa_offset 8
	retq

You will notice that both the variables `alloca`d in this function are considered to be below the already adjusted stack pointer, rather than above it, where they ought to be.

This looks like a basic signed 32-bit integer overflow somewhere in prologepilog:
```
# *** IR Dump Before Prologue/Epilogue Insertion & Frame Finalization (prologepilog) ***:
# Machine code for function banana: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten
Frame Objects:
  fi#0: size=2148000000, align=1, at location [SP+8]
  fi#1: size=2148000000, align=1, at location [SP+8]

bb.0 (%ir-block.0):
  MOV8mi %stack.0, 1, $noreg, 0, $noreg, 42 :: (store 1 into %ir.3)
  MOV8mi %stack.1, 1, $noreg, 0, $noreg, 43 :: (store 1 into %ir.4)
  RET 0

# *** IR Dump After Prologue/Epilogue Insertion & Frame Finalization (prologepilog) ***:
# Machine code for function banana: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten
Frame Objects:
  fi#0: size=2148000000, align=1, at location [SP-2148000000]
  fi#1: size=2148000000, align=1, at location [SP-4296000000]

bb.0 (%ir-block.0):
  $rax = frame-setup MOV64ri 4295999872
  $rsp = SUB64rr $rsp(tied-def 0), $rax, implicit-def dead $eflags
  CFI_INSTRUCTION def_cfa_offset 1032584
  MOV8mi $rsp, 1, $noreg, -2146967424, $noreg, 42 :: (store 1 into %ir.3)
  MOV8mi $rsp, 1, $noreg, -128, $noreg, 43 :: (store 1 into %ir.4)
  $rax = frame-destroy MOV64ri 4295999872
  $rsp = ADD64rr $rsp(tied-def 0), $rax, implicit-def dead $eflags
  CFI_INSTRUCTION def_cfa_offset 8
  RET 0
```
Worth noting that the the `def_cfa_offset` directive also overflowed in this reproducer here.

### LINKED ISSUE #75944: [llc] Signed Overflow detected by UBSan.
```ll
target datalayout = "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-linux-gnu"

define void @test(ptr %0) {
  %2 = alloca [10 x i8], i32 0, align 1
  %3 = ptrtoint ptr %2 to i32
  %4 = add i32 %3, 2147483647
  br label %5

5:                                                ; preds = %5, %1
  %6 = phi i32 [ 0, %1 ], [ %7, %5 ]
  %7 = add i32 %6, 1
  %8 = icmp eq i32 %6, %4
  br label %5
]
```
with `llc` compiled with UBSan
```bash
> llc out.ll
.../llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:945:27: runtime error: signed integer overflow: 3 + 2147483647 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior .../llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:945:27 in
```
I can reproduce this on f17e76697289e6a54e89298a49f12b6799dd3e1a

### LINKED ISSUE #87154: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineBasicBlock::iterator, int, unsigned int, llvm::RegScavenger*) const: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
# Description
The following code crashes X86 backend with "Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed."

# Minimal Reproduction
https://godbolt.org/z/h57r6bMsq

## code
```java
define void @f(i16 %LGV2, i1 %LGV3) {
BB:
  %A = alloca i1, i33 2147483648, align 1
  %G = getelementptr i1, ptr %A, i16 %LGV2
  %G4 = getelementptr i1, ptr %G, i32 -2147483648
  store i1 %LGV3, ptr %G4, align 1
  ret void
}
```

## Stack Trace
```
llc: /root/llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:950: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineBasicBlock::iterator, int, unsigned int, llvm::RegScavenger*) const: Assertion `(!Is64Bit || isInt<32>((long long)FIOffset + Imm)) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel -mtriple=x86_64 -mattr=+avx512f -O=0 <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@f'
 #0 0x000000000392d5d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x392d5d8)
 #1 0x000000000392ad2c SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f2edc842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007f2edc8969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x00007f2edc842476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x00007f2edc8287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x00007f2edc82871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #7 0x00007f2edc839e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #8 0x0000000001cf0fb0 llvm::X86RegisterInfo::eliminateFrameIndex(llvm::MachineInstrBundleIterator<llvm::MachineInstr, false>, int, unsigned int, llvm::RegScavenger*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x1cf0fb0)
 #9 0x0000000002ac734c (anonymous namespace)::PEI::runOnMachineFunction(llvm::MachineFunction&) PrologEpilogInserter.cpp:0:0
#10 0x0000000002946051 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#11 0x0000000002f04a33 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2f04a33)
#12 0x0000000002f04c71 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2f04c71)
#13 0x0000000002f054d5 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x2f054d5)
#14 0x0000000000823e0c compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#15 0x0000000000722fd6 main (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x722fd6)
#16 0x00007f2edc829d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#17 0x00007f2edc829e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#18 0x000000000081a92e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llc+0x81a92e)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fix 32-bit integer overflows in the X86 target frame layout when dealing with frames larger than 4gb. When this occurs, we'll scavenge a scratch register to be able to hold the correct stack offset for frame locals. 

This completes reapplying #84114.

Fixes #48911
Fixes #75944 
Fixes #87154

### CODE REVIEW

File: llvm/lib/Target/X86/X86RegisterInfo.cpp [hunk 1]
```diff
@@ -945,11 +947,34 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+      RS->setRegUsed(ScratchReg);
+
+      BuildMI(MBB, II, DL, TII->get(X86::MOV64ri), ScratchReg).addImm(Offset);
+
+      MI.getOperand(FIOperandNum + 3).setImm(0);
+      MI.getOperand(FIOperandNum + 2).setReg(ScratchReg);
+
+      return false;
+    } else if (!Is64Bit) {
+      assert(FitsIn32Bits && "Requesting 64-bit offset in 32-bit immediate!");
```
Comment (wesleywiser) [inline llvm/lib/Target/X86/X86RegisterInfo.cpp:976]: Is the right thing to do here to assert or should we report some kind of fatal error?

File: llvm/lib/Target/X86/X86FrameLowering.cpp [hunk 2]
```diff
@@ -4140,6 +4141,14 @@ void X86FrameLowering::processFunctionBeforeFrameFinalized(
   // emitPrologue if it gets called and emits CFI.
   MF.setHasWinCFI(false);
 
+  MachineFrameInfo &MFI = MF.getFrameInfo();
+  // If the frame is big enough that we might need to scavenge a register to
+  // handle huge offsets, reserve a stack slot for that now.
+  if (STI.is64Bit() && !isInt<32>(MFI.estimateStackSize(MF))) {
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86FrameLowering.cpp:4147]: Don't see the point in checking for 64-bit, just check the value

File: llvm/lib/Target/X86/X86RegisterInfo.cpp [hunk 3]
```diff
@@ -945,11 +947,34 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+    if (Is64Bit && !FitsIn32Bits) {
+      assert(RS && "RegisterScavenger was NULL");
+      const X86InstrInfo *TII = MF.getSubtarget<X86Subtarget>().getInstrInfo();
+      DebugLoc DL = MI.getDebugLoc();
+
+      RS->enterBasicBlockEnd(MBB);
+      RS->backward(std::next(II));
+
+      Register ScratchReg =
+          RS->scavengeRegisterBackwards(X86::GR64RegClass, II, false, 0, true);
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86RegisterInfo.cpp:965]: Comment the parameter names? I think the last one is enable spill, which should be redundant with the assert below. It should assert if the scavenge fails

File: llvm/lib/Target/X86/X86RegisterInfo.cpp [hunk 4]
```diff
@@ -945,11 +947,34 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+      assert(ScratchReg != 0 && "scratch reg was 0");
+      RS->setRegUsed(ScratchReg);
+
+      BuildMI(MBB, II, DL, TII->get(X86::MOV64ri), ScratchReg).addImm(Offset);
+
+      MI.getOperand(FIOperandNum + 3).setImm(0);
+      MI.getOperand(FIOperandNum + 2).setReg(ScratchReg);
+
+      return false;
+    } else if (!Is64Bit) {
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86RegisterInfo.cpp:975]: No else after return

File: llvm/lib/Target/X86/X86RegisterInfo.h [hunk 5]
```diff
@@ -176,6 +178,13 @@ class X86RegisterInfo final : public X86GenRegisterInfo {
                              SmallVectorImpl<MCPhysReg> &Hints,
                              const MachineFunction &MF, const VirtRegMap *VRM,
                              const LiveRegMatrix *Matrix) const override;
+
+  bool requiresRegisterScavenging(const MachineFunction &MF) const override {
+    const MachineFrameInfo &MFI = MF.getFrameInfo();
+
+    // We need to register scavenge if the frame is very large.
+    return Is64Bit && !isInt<32>(MFI.estimateStackSize(MF));
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86RegisterInfo.h:186]: Don't need target check?

File: llvm/test/CodeGen/X86/huge-stack-offset.ll [hunk 6]
```diff
@@ -1,23 +1,15 @@
-; RUN: llc < %s -mtriple=x86_64-linux-unknown -verify-machineinstrs | FileCheck %s --check-prefix=CHECK-64
-; RUN: llc < %s -mtriple=i386-linux-unknown -verify-machineinstrs | FileCheck %s --check-prefix=CHECK-32
+; RUN: llc < %s -mtriple=x86_64-linux-unknown -verify-machineinstrs | FileCheck %s
```
Comment (arsenm) [inline llvm/test/CodeGen/X86/huge-stack-offset.ll:1]: Don't need verify-machineinstrs

File: llvm/test/CodeGen/X86/avx512f-large-stack.ll [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+; CHECK-NEXT:    addq $2147483528, %rsp # imm = 0x7FFFFF88
+; CHECK-NEXT:    .cfi_def_cfa_offset 8
+; CHECK-NEXT:    retq
+BB:
+  %A = alloca i1, i33 2147483648, align 1
+  %G = getelementptr i1, ptr %A, i16 %LGV2
+  %G4 = getelementptr i1, ptr %G, i32 -2147483648
+  store i1 %LGV3, ptr %G4, align 1
+  ret void
+}
```
Comment (arsenm) [inline llvm/test/CodeGen/X86/avx512f-large-stack.ll:23]: Can you include a test that hits the case where the scavenger requires the emergency spill?

File: llvm/test/CodeGen/X86/huge-stack-offset.ll (hunk 6 above)
Comment (RKSimon) [reply llvm/test/CodeGen/X86/huge-stack-offset.ll:1]: Why have you dropped 32-bit test coverage?

File: llvm/lib/Target/X86/X86RegisterInfo.cpp [hunk 8]
```diff
@@ -945,11 +947,34 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+    int64_t Imm = MI.getOperand(FIOperandNum + 3).getImm();
+    int64_t Offset = FIOffset + Imm;
+    bool FitsIn32Bits = isInt<32>(Offset);
+    // If the offset will not fit in a 32-bit displacement,
+    // then for 64-bit targets, scavenge a register to hold it.
+    // Otherwise, for 32-bit targets, this is a bug!
+    if (Is64Bit && !FitsIn32Bits) {
+      assert(RS && "RegisterScavenger was NULL");
+      const X86InstrInfo *TII = MF.getSubtarget<X86Subtarget>().getInstrInfo();
+      DebugLoc DL = MI.getDebugLoc();
```
Comment (arsenm) [inline llvm/lib/Target/X86/X86RegisterInfo.cpp:959]: const ref

File: llvm/lib/Target/X86/X86RegisterInfo.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Target/X86/X86RegisterInfo.cpp:976]: What happens if you just let it pass through? The operand always encodes i64

Comment (wesleywiser) [reply llvm/lib/Target/X86/X86RegisterInfo.cpp:976]: The operand is i64 but that isn't valid on X86:

```
$ llc -mtriple=i386-unknown-linux-gnu -verify-machineinstrs llvm/test/CodeGen/X86/huge-stack.ll
*** Bad machine code: Displacement in address must fit into 32-bit signed integer ***
- function:    foo
- basic block: %bb.0  (0x56a1b68390f0)
- instruction: MOV8mi $esp, 1, $noreg, 4294967301, $noreg, 42 :: (store (s8) into %ir.3)
LLVM ERROR: Found 1 machine code errors.
```

File: llvm/test/CodeGen/X86/huge-stack-offset.ll (hunk 6 above)
Comment (wesleywiser) [reply llvm/test/CodeGen/X86/huge-stack-offset.ll:1]: `-verify-machineinstrs` caught a few issues the last time I tried to merge this so i'd prefer to keep it unless there's a strong reason not to.

This test tries to stack allocate ~5gb which isn't valid on i386 so it wasn't clear to me what the point of the test was. I can add it back if you'd prefer.

File: llvm/test/CodeGen/X86/avx512f-large-stack.ll (hunk 7 above)
Comment (wesleywiser) [reply llvm/test/CodeGen/X86/avx512f-large-stack.ll:23]: Added another test that I think covers this case.

Comment (wesleywiser) [reply llvm/test/CodeGen/X86/avx512f-large-stack.ll:23]: That seems to have worked, thanks!

File: llvm/lib/Target/X86/X86RegisterInfo.cpp (hunk 1 above)
Comment (wesleywiser) [reply llvm/lib/Target/X86/X86RegisterInfo.cpp:984]: Folded the assert and condition together.

File: llvm/test/CodeGen/X86/huge-stack-offset.ll (hunk 6 above)
Comment (arsenm) [reply llvm/test/CodeGen/X86/huge-stack-offset.ll:1]: Just because it is invalid or won't work doesn't mean it's not worth testing. Ideally would emit an error or something, but the behavior should be captured in a test

Comment (wesleywiser) [reply llvm/test/CodeGen/X86/huge-stack-offset.ll]: That's fair. I think emitting an error would be good so I might take a stab at doing that in another PR. For now, I've reverted this.

**Review by arsenm — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks for all the feedback and reviews @arsenm! I don't have commit rights so if someone could merge for me, that would most appreciated 🙂

**Comment by zmodem** [comment]
We're hitting asserts after this when targeting 32-bit x86:

```
lib/Target/X86/X86RegisterInfo.cpp:989:
virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator, int, unsigned int, RegScavenger *) const:
Assertion `(Is64Bit || FitsIn32Bits) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
```

See https://crbug.com/361106069#comment4 for a reproducer.

Reverting for now.

**Comment by wesleywiser** [comment]
Looking at the repro mentioned,, I see exactly one difference in the asm between prior to my change and after my change:

```diff
.LBB0_46:                               # %while.body.i.preheader.i
                                        #   in Loop: Header=BB0_10 Depth=1
	movl	-20(%ebp), %ebx                 # 4-byte Reload
-	leal	2147483423(%ebp), %eax
+	leal	-2147483873(%ebp), %eax
	movl	$1, %ecx
	addl	$2147483647, %ebx               # imm = 0x7FFFFFFF
```

If I explicitly truncate the offset back to 32-bits, then I get the same output as before my change:

```diff
@@ -988,7 +988,7 @@ X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
     assert((Is64Bit || FitsIn32Bits) &&
            "Requesting 64-bit offset in 32-bit immediate!");
     if (Offset != 0 || !tryOptimizeLEAtoMOV(II))
-      MI.getOperand(FIOperandNum + 3).ChangeToImmediate(Offset);
+      MI.getOperand(FIOperandNum + 3).ChangeToImmediate((int64_t)((int)FIOffset + (int)Imm));
   } else {
     // Offset is symbolic. This is extremely rare.
     uint64_t Offset = FIOffset +
```

So I think the actual issue here is that the assertion was [previously written incorrectly](https://github.com/llvm/llvm-project/pull/101840/files#diff-9634de34ebe6c0515879267e2eddfa69a67d18de32f7767c24c09588e85f3654L960-L962) and didn't fire when it should have. 

I guess one possible "fix" here is to just remove the assert. Alternatively, we could truncate the offset back to 32-bit when targeting x86 like we used to. 

Does that seem reasonable? Suggestions? 🙂

**Comment by zmodem** [comment]
> Does that seem reasonable? Suggestions? 🙂

I don't have enough context here, sorry. Hopefully the reviewer of the PR can help.

**Comment by arsenm** [comment]
> > Does that seem reasonable? Suggestions? 🙂
> 
> I don't have enough context here, sorry. Hopefully the reviewer of the PR can help.

I don't know how you managed to encounter this in the real world, but that code can't work. This should be a compiler error

**Comment by zmodem** [comment]
> I don't know how you managed to encounter this in the real world, but that code can't work.

We hit the assert both in builds targeting 32-bit x86 Linux and Windows, from source files in different projects (ANGLE and V8).

I'll try to creduce one of them to see if we can get something that's easier to look at.

**Comment by wesleywiser** [comment]
I believe that's the same invocation I looked at to the get the assembly I posted above. If I'm understanding everything correctly, currently that code is miscompiled on 32-bit x86 and after my change (for clang/LLVM builds with assertions enabled) it will now instead trigger the assertion.

**Comment by arsenm** [comment]
> I believe that's the same invocation I looked at to the get the assembly I posted above. If I'm understanding everything correctly, currently that code is miscompiled on 32-bit x86 and after my change (for clang/LLVM builds with assertions enabled) it will now instead trigger the assertion.

But it does mean it should be upgraded to a proper backend error, instead of an assertion or verifier error. Preferably using DiagnosticInfo

**Comment by wesleywiser** [comment]
Thanks, I'll look into doing that and open a PR to re-land the updated patch.

**Comment by zmodem** [comment]
> I believe that's the same invocation I looked at to the get the assembly I posted above.

Yes, the source code is reduced, but it's the same origin.

> If I'm understanding everything correctly, currently that code is miscompiled on 32-bit x86

What makes you say it's miscompiled?

> But it does mean it should be upgraded to a proper backend error

Why backend error? If the source code is doing something erroneous, shouldn't it be a proper clang error?

**Comment by arsenm** [comment]
> Why backend error? If the source code is doing something erroneous, shouldn't it be a proper clang error?

It's not directly a source error, it's exceeding an encodable stack offset. Is this code ever even executed? Is it somehow relying on the overflow behavior of the stack pointer?

**Comment by zmodem** [comment]
I haven't looked deeply at the code yet, but the function that's hitting the assert is https://source.chromium.org/chromium/chromium/src/+/82472113b1df5e77637b78e10889340f4d405739:third_party/angle/src/gpu_info_util/SystemInfo.cpp;l=225 (I assume with a bunch of stuff inlined into it.) That doesn't look particularly edgy to me, and as far as I know it does get executed.

**Comment by zmodem** [comment]
The preprocessed source above was for the crash in V8, which is a different function. Sorry about that.

Here is a reproducer based on SystemInfo.cpp in ANGLE. Again, I don't see anything fishy in that code, so I don't think a compiler error is appropriate.

```
$ cat SystemInfo.cpp 
#include <string>
#include <sstream>

bool ParseAMDBrahmaDriverVersion(const std::string &content, std::string *version)
{
    const size_t begin = content.find_first_of("0123456789");
    if (begin == std::string::npos)
    {
        return false;
    }

    const size_t end = content.find_first_not_of("0123456789.", begin);
    if (end == std::string::npos)
    {
        *version = content.substr(begin);
    }
    else
    {
        *version = content.substr(begin, end - begin);
    }
    return true;
}

bool ParseAMDCatalystDriverVersion(const std::string &content, std::string *version)
{
    std::istringstream stream(content);

    std::string line;
    while (std::getline(stream, line))
    {
        static const char kReleaseVersion[] = "ReleaseVersion=";
        if (line.compare(0, std::strlen(kReleaseVersion), kReleaseVersion) != 0)
        {
            continue;
        }

        if (ParseAMDBrahmaDriverVersion(line, version))
        {
            return true;
        }
    }
    return false;
}

$ /work/llvm-project/build/bin/clang.bad --driver-mode=cl /c SystemInfo.cpp /winsysroot../../third_party/depot_tools/win_toolchain/vs_files/7393122652 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -I../../buildtools/third_party/libc++ -I../../third_party/libc++/src/include -fno-delete-null-pointer-checks -fmerge-all-constants -m32 -msse3 /O2 /Oy- /std:c++20
clang.bad: /work/llvm-project/llvm/lib/Target/X86/X86RegisterInfo.cpp:989: virtual bool llvm::X86RegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator, int, unsigned int, RegScavenger *) const: Assertion `(Is64Bit || FitsIn32Bits) && "Requesting 64-bit offset in 32-bit immediate!"' failed.
```

Here is the crash repro as emitted by Clang: 
[SystemInfo-e066e8.tar.gz](https://github.com/user-attachments/files/16728492/SystemInfo-e066e8.tar.gz)

Just speculating, I could imagine something along the lines of an `idx == string::npos` comparison getting replaced by `ptr + idx == ptr + string::npos` with `ptr` referring to a stack variable somewhere along the compilation path?

**Comment by wesleywiser** [comment]
Apologies for how long it's taken for me to get back to this, I've been looking at it off and on for the last few months in my spare time. 

I've reduced the `SystemInfo.cpp` reproducer into a self-contained 482 lines [here](https://gist.github.com/wesleywiser/f7bea9708557647c65cf303a36cdb054) and trimmed the compile flags a bit as well. It can probably be reduced even more but I haven't had much additional luck as the reproducer is very fragile. I think the problematic bit comes from libcxx: 

https://github.com/llvm/llvm-project/blob/7c86ab8a18897c434fdb1ee3cd5ff2a71e6aae5a/libcxx/include/sstream#L727-L730

This code is dead code in the reproducer. During instruction selection, I see we optimize an add which is very close to `min(int32_t)` into an `lea`:

```
Optimized legalized selection DAG: %bb.21 '?ParseAMDCatalystDriverVersion@@YA_NABVbasic_string@__Cr@std@@@Z:while.body.i.preheader'
SelectionDAG has 36 nodes:
  t0: ch,glue = EntryToken
    t18: i32,ch = CopyFromReg t0, Register:i32 %5
  t20: i32 = add t18, Constant:i32<-2147483647>
          t48: i32 = X86ISD::CMP t20, Constant:i32<0>
        t50: i32 = X86ISD::CMOV t20, Constant:i32<1>, TargetConstant:i8<8>, t48
      t26: ch = CopyToReg t0, Register:i32 %22, t50
            # this add becomes...
            t15: i32 = add FrameIndex:i32<0>, Constant:i32<-2147483625>   
              t10: i32,ch = CopyFromReg t0, Register:i32 %1
            t12: i32 = add nuw t10, Constant:i32<2147483647>
                  t2: i32,ch = CopyFromReg t0, Register:i32 %3
                t4: i32 = AssertSext t2, ValueType:ch:i8
              t5: i8 = truncate t4
            t44: i32 = X86ISD::CMP t5, Constant:i8<0>
          t47: i32 = X86ISD::CMOV t15, t12, TargetConstant:i8<8>, t44
            t35: i32 = sra t20, Constant:i8<31>
          t36: i32 = and t35, Constant:i32<2147483647>
        t28: i32 = add t47, t36
      t30: ch = CopyToReg t0, Register:i32 %23, t28
    t32: ch = TokenFactor t26, t30
  t33: ch = br t32, BasicBlock:ch<if.then23.i 0x569e4deeb3c8>


Selected selection DAG: %bb.21 '?ParseAMDCatalystDriverVersion@@YA_NABVbasic_string@__Cr@std@@@Z:while.body.i.preheader'
SelectionDAG has 41 nodes:
  t0: ch,glue = EntryToken
    t18: i32,ch = CopyFromReg t0, Register:i32 %5
  t20: i32,i32 = ADD32ri t18, TargetConstant:i32<-2147483647>
      t2: i32,ch = CopyFromReg t0, Register:i32 %3
    t58: i32 = COPY_TO_REGCLASS t2, TargetConstant:i32<48>
  t5: i8 = EXTRACT_SUBREG t58, TargetConstant:i32<1>
          t23: i32 = MOV32ri TargetConstant:i32<1>
            t48: i32 = TEST32rr t20, t20
          t55: ch,glue = CopyToReg t0, Register:i32 $eflags, t48
        t50: i32 = CMOV_GR32 t20, t23, TargetConstant:i8<8>, t55:1
      t26: ch = CopyToReg t0, Register:i32 %22, t50
            # ... this lea
            t15: i32 = LEA32r TargetFrameIndex:i32<0>, TargetConstant:i8<1>, Register:i32 $noreg, TargetConstant:i32<-2147483625>, Register:i16 $noreg    
              t10: i32,ch = CopyFromReg t0, Register:i32 %1
            t12: i32,i32 = ADD32ri nuw t10, TargetConstant:i32<2147483647>
              t44: i32 = TEST8rr t5, t5
            t53: ch,glue = CopyToReg t0, Register:i32 $eflags, t44
          t47: i32 = CMOV_GR32 t15, t12, TargetConstant:i8<8>, t53:1
            t35: i32,i32 = SAR32ri t20, TargetConstant:i8<31>
          t36: i32,i32 = AND32ri t35, TargetConstant:i32<2147483647>
        t28: i32,i32 = ADD32rr t47, t36
      t30: ch = CopyToReg t0, Register:i32 %23, t28
    t32: ch = TokenFactor t26, t30
  t33: ch = JMP_1 BasicBlock:ch<if.then23.i 0x569e4deeb3c8>, t32
```

and then during frame layout, when we adjust the offset to accommodate the frame layout and the frame pointer, we underflow `int32_t` and trigger the (corrected) offset assertion. 

It looks like there's already code that tries to handle this kind of thing in X86 ISel here:

https://github.com/llvm/llvm-project/blob/dc3cd2e95ee56cdb75f4d0d0742626f912b5c6f3/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp#L1803-L1811

If I add a check to [`X86DAGToDAGISel::foldOffsetIntoAddress`](https://github.com/llvm/llvm-project/blob/dc3cd2e95ee56cdb75f4d0d0742626f912b5c6f3/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp#L1813C6-L1813C44), then the reproducer no longer asserts and the add isn't converted into an `lea`:

```diff
@@ -1821,7 +1826,11 @@ bool X86DAGToDAGISel::foldOffsetIntoAddress(uint64_t Offset,
     if (Subtarget->isTarget64BitILP32() && !isUInt<31>(Val) &&
         !AM.hasBaseOrIndexReg())
       return true;
-  }
+  } 
+  else if (AM.hasBaseOrIndexReg() && ! isDispSafeForFrameIndex(Val))
+     // For 32-bit X86, make sure the displacement still isn't close to the
+     // expressible limit.
+     return true;
   AM.Disp = Val;
   return false;
 }
```

@arsenm does that seem like a reasonable thing to do?

**Comment by arsenm** [comment]
Yes, I'd assume any such checks would go before this offset was formed in the first place

**Comment by wesleywiser** [comment]
Opened #121678 to add this check.

**Comment by phoebewang** [comment]
> and then during frame layout, when we adjust the offset to accommodate the frame layout and the frame pointer, we underflow `int32_t` and trigger the (corrected) offset assertion.
> 
> It looks like there's already code that tries to handle this kind of thing in X86 ISel here:

I'm wondering if we can just disable the assertion for 32-bit target. My intuition is the underflow doesn't matter to a 32-bit address. The value should be the same w/ or w/o `lea`.
