### PR TITLE
[MLIR][OpenMP] Fix MLIR->LLVM value matching in privatization logic

### LINKED ISSUE #102935: [flang][openmp] OpenMP "firstprivate" directive doesn't work for character strings with non-constant length
Here's a program that shows the failure:
```
program bug
  implicit none
  call sub(3)
contains
  subroutine sub(n)
    use omp_lib
    integer,intent(in) :: n
    character(n) str
    str = "xyz"
    call omp_set_num_threads(3)
    !$omp parallel firstprivate(str)
      print *, "thread: ", omp_get_thread_num(), ", str: ", str
      str = "abc"
    !$omp end parallel
    print *, "str: ", str
  end subroutine
end program
```
If I compile this program with `flang-new -fopenmp bug.f90` and execute it, I get the following output:
```
thread:  1 , str: xyz
 thread:  2 , str: abc
 thread:  0 , str: abc
 str: abc
```
If I change the declaration of the variable `str` to be `character(3) str`, and compile and execute the program in the same way, I get the output:
```
 thread:  0 , str: xyz
 thread:  2 , str: xyz
 thread:  1 , str: xyz
 str: xyz
```

### PR DESCRIPTION
**Pull request by ergawy**
Fixes #102935

Updates matching logic for finding the LLVM value that corresponds to an MLIR value. We need that matching to find the delayed privatizer for an LLVM value being privatized.

The issue occures when there is an "indirect" correspondence between MLIR and LLVM values: in some cases the values we are trying to match stem from a pair of load/store ops that point to the same memref. This PR adds such matching logic.

### CODE REVIEW

**Review by luporl — COMMENTED** [review]
Given how translation from MLIR to LLVM can differ for distinct types, using the associated memory location to check if a translated MLIR value corresponds to the LLVM value being privatized seems a good approach to me.

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 1]
```diff
@@ -1444,12 +1444,43 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
+            if (llvmPrivVar == vPtr)
+              return true;
+
+            auto *vPtrLoad = llvm::dyn_cast_if_present<llvm::LoadInst>(vPtr);
+
+            if (vPtrLoad == nullptr)
+              return false;
+
+            // Otherwise, we check if both vPtr and llvmPrivVar refer to the
+            // same memory (through a load/store pair).
```
[the remark this answers is not in the document]
Comment (ergawy) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]: Thanks for the review. I renamed things to hopefully convery their meaning a bit better and also added a comment block with an example. Let me know if we can make it better.

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 2]
```diff
@@ -1424,35 +1424,107 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
+  SmallVector<llvm::Value *> llvmPrivateVars;
 
   // TODO: Perform appropriate actions according to the data-sharing
   // attribute (shared, private, firstprivate, ...) of variables.
   // Currently shared and private are supported.
   auto privCB = [&](InsertPointTy allocaIP, InsertPointTy codeGenIP,
-                    llvm::Value &, llvm::Value &vPtr,
-                    llvm::Value *&replacementValue) -> InsertPointTy {
-    replacementValue = &vPtr;
+                    llvm::Value &, llvm::Value &llvmOmpRegionInputPtr,
```
Comment (luporl) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:1434]: This is a question only: in this context, should I understand `llvmOmpRegionInputPtr` as an input, that is an LLVM pointer, in the OpenMP region being translated, that must be replaced with `llvmReplacementValue`?
But if so, won't it point to the result of a load sometimes, which is not a pointer? Or should I interpret it as "argument that points to the input value that must be replaced"?

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 3]
```diff
@@ -1424,35 +1424,107 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
       if (!opInst.getPrivateVars().empty()) {
-        auto privateVars = opInst.getPrivateVars();
-        auto privateSyms = opInst.getPrivateSyms();
+        auto mlirPrivVars = opInst.getPrivateVars();
+        auto mlirPrivSyms = opInst.getPrivateSyms();
 
-        for (auto [privVar, privatizerAttr] :
-             llvm::zip_equal(privateVars, *privateSyms)) {
+        // Try to find a privatizer that corresponds to the LLVM value being
+        // prvatized.
```
Comment (luporl) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:1448]:
```suggestion
        // privatized.
```

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 4]
```diff
@@ -1424,35 +1424,107 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
+            // mlirToLLVMPrivVar refer to the same memory (through a load/store
+            // pair). This happens if a struct (i.e. multi-field value) is being
+            // privatized.
+            //
+            // For example, if the privatized value is defined by:
+            // ```
+            //   %priv_val = alloca { ptr, i64 }, align 8
+            // ```
+            //
+            // Initialized this value (outside the omp region) will be something
```
Comment (luporl) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:1476]:
```suggestion
            // The initialization of this value (outside the omp region) will be something
```

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 5]
```diff
@@ -1424,35 +1424,107 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
+            // Now, we enter the OMP region, in order to access this privatized
+            // value, we need to load from the allocated memory:
+            // ```
+            // omp.par.entry:
+            //   %priv_val_load = load { ptr, i64 }, ptr %priv_val, align 8
+            // ```
+            //
+            // The 2 LLVM values tracked here map as follows:
+            // - `mlirToLLVMPrivVar`     -> `%fully_init_priv_val`
+            // - `llvmOmpRegionInputPtr` -> `priv_val_load`
```
Comment (luporl) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:1499]:
```suggestion
            // - `llvmOmpRegionInputPtr` -> `%priv_val_load`
```

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp [hunk 6]
```diff
@@ -1424,35 +1424,107 @@ convertOmpParallel(omp::ParallelOp opInst, llvm::IRBuilderBase &builder,
...
+            //
+            // Even though they eventually refer to the same memory reference
+            // (the memory being privatized), they are 2 distinct LLVM values.
+            // Therefore, we need to discover their correspondence by finding
+            // out if the store into and load from the same mem ref.
```
Comment (luporl) [inline mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp:1504]:
```suggestion
            // out if they store into and load from the same mem ref.
```

**Review by luporl — APPROVED** [review]
Thanks for greatly expanding the comment that explains the new value matching logic and for the renaming of variables, that makes clear what is from MLIR and what is from LLVM.

I have only a question and a few nits, but this LGTM.

File: mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp (hunk 2 above)
Comment (ergawy) [reply mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp]: The latter. I think removing the `ptr` suffix makes sense indeed.
