### PR TITLE
[Clang] Don't add top-level const qualifiers to captured function types

### LINKED ISSUE #84961: Code using a lambda to capture a reference to a function rejected with `could not match (null template argument) against (null template argument)`
The following code is accepted by other compilers but rejected by clang.  The error message is a bit weird.

```C++
template<typename T>
void g(const T& t) {
}

template<typename T>
void f(const T& t) {
  [t] { g(t); };
}

void h() {
}

int main() {
  f(h);
}
```

Output:
```
<source>:7:9: error: no matching function for call to 'g'
    7 |   [t] { g(t); };
      |         ^
<source>:7:7: note: while substituting into a lambda expression here
    7 |   [t] { g(t); };
      |       ^
<source>:14:3: note: in instantiation of function template specialization 'f<void ()>' requested here
   14 |   f(h);
      |   ^
<source>:2:6: note: candidate template ignored: could not match (null template argument) against (null template argument)
    2 | void g(const T& t) {
      |      ^
```

Changing the call `g(t)` to be either `g<T>(t)` or `g<void()>(t)` changes the error message to:

```
note: candidate function template not viable: 1st argument ('void (const()') would lose const qualifier
```

Note that the type mentioned here (`void (const()`) has unbalanced parentheses.

Workaround: change the lambda capture from `[t]` to `[t=t]`.

This code was accepted by clang 3.0.0 but is rejected by all version from 3.1 to the latest trunk currently available on Godbolt.

Godbolt link: https://godbolt.org/z/d87rPjja4

### PR DESCRIPTION
**Pull request by zyn0217**
This aligns with the logic in `TreeTransform::RebuildQualifiedType()` where we refrain from adding const qualifiers to function types. Previously, we seemed to overlook this edge case when copy-capturing a variable that is of function type within a const-qualified lambda.

This issue also reveals other related problems as in incorrect type printout and a suspicious implementation in DeduceTemplateArguments. I decide to leave them in follow-up work.

Fixes #84961

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -18789,7 +18792,11 @@ static bool captureInLambda(LambdaScopeInfo *LSI, ValueDecl *Var,
     //   parameter-declaration-clause is not followed by mutable.
     DeclRefType = CaptureType.getNonReferenceType();
     bool Const = LSI->lambdaCaptureShouldBeConst();
-    if (Const && !CaptureType->isReferenceType())
+    // C++ [dcl.fct]p7:
+    //   [When] adding cv-qualifications on top of the function type [...] the
+    //   cv-qualifiers are ignored.
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaExpr.cpp:18797]: I think the more relevant wording is https://eel.is/c++draft/expr.prim.lambda#capture-10.sentence-4

Comment (zyn0217) [reply clang/lib/Sema/SemaExpr.cpp]: Thanks, and sorry for missing this review

**Review by cor3ntin — APPROVED** [review]
