### PR TITLE
[llvm][lli] fix lli crash when run variable arguments function as a interpret

### LINKED ISSUE #173718: [lli] lli crash when run variable arguments function as a interpret
### Description
Run `lli` comand with the flag `-force-interpreter=true` to execute LLVM bitcode, if `lli` run `variable arguments` function in the bitcode, it will crash.

### Steps to reproduce

1、compile the c code below to bitcode
```
#include <stdarg.h>

int sum(int a, ...) {
  int total = a;
  va_list list;
  va_start(list, a);
  total += va_arg(list, int);
  total += va_arg(list, int);
  va_end(list);
  return total;
}

int main() {
    int total = sum(1, 2, 3);
    return total;
}
```

2、use the command below to execute bitcode which produced by `step 1`
`
lli -force-interpreter=true  xxx.bc
`

3 crashed

Crashing thread backtrace:
```
Stack dump:
0.	Program arguments: /Users/user/llvm-project/build/bin/lli -force-interpreter=true main.bc
 #0 0x0000000100d3edb0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/user/llvm-project/build/bin/lli+0x100b16db0)
 #1 0x0000000100d3ccd8 llvm::sys::RunSignalHandlers() (/Users/user/llvm-project/build/bin/lli+0x100b14cd8)
 #2 0x0000000100d3f804 SignalHandler(int, __siginfo*, void*) (/Users/user/llvm-project/build/bin/lli+0x100b17804)
 #3 0x000000018c1196a4 (/usr/lib/system/libsystem_platform.dylib+0x1804ad6a4)
 #4 0x00000001007ce900 llvm::Interpreter::visitVAArgInst(llvm::VAArgInst&) (/Users/user/llvm-project/build/bin/lli+0x1005a6900)
 #5 0x00000001007cfa84 llvm::Interpreter::run() (/Users/user/llvm-project/build/bin/lli+0x1005a7a84)
 #6 0x00000001007d2dfc llvm::Interpreter::runFunction(llvm::Function*, llvm::ArrayRef<llvm::GenericValue>) (/Users/user/llvm-project/build/bin/lli+0x1005aadfc)
 #7 0x00000001007b84e4 llvm::ExecutionEngine::runFunctionAsMain(llvm::Function*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, char const* const*) (/Users/user/llvm-project/build/bin/lli+0x1005904e4)
 #8 0x000000010022e0d8 main (/Users/user/llvm-project/build/bin/lli+0x1000060d8)
 #9 0x000000018bd3eb98
[1]    4895 segmentation fault  /Users/user/llvm-project/build/bin/lli -force-interpreter=true main.bc
```

### environment
Mac mini  Apple M2

### PR DESCRIPTION
**Pull request by Fushj89**
Run `lli` comand with the flag `-force-interpreter=true` to execute LLVM bitcode, if `lli` run `variable arguments` function in the bitcode, it will crash.
Fix #173718

### CODE REVIEW

**Comment by Fushj89** [comment]
same issue #21571

**Comment by Fushj89** [comment]
Ping

**Comment by Fushj89** [comment]
Ping

File: llvm/lib/ExecutionEngine/Interpreter/Execution.cpp [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ void Interpreter::visitVAStartInst(VAStartInst &I) {
   GenericValue ArgIndex;
```
Comment (shermpay) [inline llvm/lib/ExecutionEngine/Interpreter/Execution.cpp:1082]: Not a maintainer, so feel free to ignore if this doesn't make sense. I am wondering if this should be renamed to VAList? To be consistent with the code in `visitVAArgInst`, as this is technically `(ec-stack-depth var-arg-index)` pair, which represents the entire list.

Comment (Fushj89) [reply llvm/lib/ExecutionEngine/Interpreter/Execution.cpp:1082]: The `VAList ` var  in `visitVAArgInst` function  hava a little confused for me. I think the result of `VAStartInst.getOperand(0)` should be named `VAList `,  for example, the var `%2` in ir  should represent the `VAList`. 
```
define i32 @sum(i32 %0, ...)  {
  %2 = alloca ptr, align 8
  call void @llvm.va_start.p0(ptr nonnull %2)
.....
```

It may be more appropriate to rename the variable 'VAList' in`visitVAArgInst`  to 'ArgIndex' or   'VAListArgIndex' .
I am beginner and clear changes for review, so didn't change the name.

File: llvm/lib/ExecutionEngine/Interpreter/Execution.cpp [hunk 2]
```diff
@@ -1729,7 +1729,8 @@ void Interpreter::visitVAArgInst(VAArgInst &I) {
 
   // Get the incoming valist parameter.  LLI treats the valist as a
   // (ec-stack-depth var-arg-index) pair.
-  GenericValue VAList = getOperandValue(I.getOperand(0), SF);
+  Value *V = I.getOperand(0);
+  GenericValue VAList = getOperandValue(V, SF);
```
Comment (Fushj89) [inline llvm/lib/ExecutionEngine/Interpreter/Execution.cpp:1733]: @shermpay  as the above discussion , i will change **V** to **VAList**,  change **VAList** to **ArgIndex** which be consistent with the code in **visitVAStartInst** . Do change names will cause more code to be modifed.  Do you have any other suggestions？

**Comment by Fushj89** [comment]
@nikic  help review the pr

File: llvm/test/ExecutionEngine/Interpreter/test-interp-variable-arguments.ll
Comment (nikic) [inline llvm/test/ExecutionEngine/Interpreter/test-interp-variable-arguments.ll:1]: This should be in llvm/test/ExecutionEngine/Interpreter.

**Review by nikic — APPROVED** [review]
LGTM apart from one test nit.

File: llvm/test/ExecutionEngine/Interpreter/test-interp-variable-arguments.ll
Comment (Fushj89) [reply llvm/test/ExecutionEngine/Interpreter/test-interp-variable-arguments.ll:1]: Thanks, done
