### PR TITLE
[clang] fix classification of a string literal expression used as initializer

### LINKED ISSUE #82167: Clang rejects valid program involving user defined literal
The following valid(afaik) program is rejected by clang but accepted by gcc and msvc.

```
#include <array>

template<std::size_t N>
struct Literal
{
    std::array<char, N> arr;
    constexpr Literal(char const(&pp)[N]): arr(""){} 
};
 
template<Literal> 
constexpr auto operator""_S()
{
    return 4;
}
int main() {
    auto i = "test"_S;   
    auto j =  "ch"_S;       
}
```
Clang says:
```
<source>:7:48: error: initializer-string for char array is too long, array size is 3 but initializer has size 5 (including the null terminating character)
    7 |     constexpr Literal(char const(&pp)[N]): arr(""){}
      |    
      <source>:17:15: note: in instantiation of member function 'Literal<3>::Literal' requested here
   17 |     auto j =  "ch"_S;
```

Another thing to note that if we write `auto i = "test"_S;   auto j =  "chjjgjgjt"_S;` then clang starts [accepting](https://godbolt.org/z/qGPjhYeKe).

Similarly clang also [accepts](https://godbolt.org/z/Kcz3rco33) `auto i = "test"_S;   auto j =  "chjt"_S;`

### PR DESCRIPTION
**Pull request by mizvekov**
Since 3bf72d7d64b8465acd4f4af1a469d68d9dc86058 we have made a simplification where we transform a string literal into a prvalue, where normally they would always be lvalues.

This patch fixes expression classification to account for this case.

Fixes #82167

### CODE REVIEW

File: clang/lib/AST/ExprClassification.cpp [hunk 1]
```diff
@@ -150,6 +148,12 @@ static Cl::Kinds ClassifyInternal(ASTContext &Ctx, const Expr *E) {
   case Expr::OMPIteratorExprClass:
     return Cl::CL_LValue;
 
+    // C++ [expr.prim.general]p1: A string literal is an lvalue.
+    // Except we special case them as prvalues when they are used for
+    // initialization.
```
Comment (efriedma-quic) [inline clang/lib/AST/ExprClassification.cpp:153]: Maybe say more specifically "to initialize a char array".

File: clang/lib/AST/ExprClassification.cpp [hunk 2]
```diff
@@ -119,8 +119,6 @@ static Cl::Kinds ClassifyInternal(ASTContext &Ctx, const Expr *E) {
 
     // First come the expressions that are always lvalues, unconditionally.
   case Expr::ObjCIsaExprClass:
-    // C++ [expr.prim.general]p1: A string literal is an lvalue.
-  case Expr::StringLiteralClass:
     // @encode is equivalent to its string
   case Expr::ObjCEncodeExprClass:
```
Comment (efriedma-quic) [inline clang/lib/AST/ExprClassification.cpp:123]: I think we also need to handle ObjCEncodeExprClass the same way.

Comment (efriedma-quic) [reply clang/lib/AST/ExprClassification.cpp:123]: Also PredefinedExprClass in isTransparent mode (with -fms-extensions).

Comment (mizvekov) [reply clang/lib/AST/ExprClassification.cpp]: Done.

For PredefinedExprClass, it doesn't repro on the original scenario, since we delay building those.

**Review by efriedma-quic — APPROVED** [review]
LGTM
