### PR TITLE
[MLIR][python bindings] invalidate ops after PassManager run

### LINKED ISSUE #69730: [mlir][python] Tracking of live operations fails.
I am running into a problem with the Python bindings of MLIR related to how `PyOperation`s track the underlying `Operation`s.

If I understand things right, when a `PyOperation` is created, the pointer to the underlying `Operation` is tracked in [`PyMlirContext::liveOperations`](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRModule.h#L256) (e.g., [here](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRCore.cpp#L1092)). This is used (potentially among other things) to return the same `PyOperation` for existing `Operation`s, e.g., [here](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRCore.cpp#L1106-L1109).

However, it is possible to obtain a `PyOperation` to an `Operation` that is then destroyed without the Python binding noticing, for example, by running a pass that deletes that `Operation`. At that point, `PyMlirContext::liveOperations` has an entry for an `Operation` that doesn't exist anymore. It is then possible that that memory location is used for a new `Operation` that is created through `PyOperation::createDetached` (for example, through [`PyOperation::clone`](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRCore.cpp#L1419), which is called by the Python-bound method [`_OperationBase.clone`](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRCore.cpp#L2930-L2934)). `PyMlirContext::liveOperations` thus contains the pointer of the previous operation that has been destroyed in the meantime and `PyOperation::createDetached` wants to add that same pointer again for a (supposedly not-yet-existing) "new" `Operation`. Accordingly, the [assertion](https://github.com/llvm/llvm-project/blob/3a4b1d17/mlir/lib/Bindings/Python/IRCore.cpp#L1116-L1117) in `PyOperation::createDetached` fails.

I am unsure what the best way to fix this is. After a day of thinking about the problem, my best guess is to say that such a tracking is, in fact, not possible. My second best guess is to say that it is illegal to hold `PyOperation` to ops that could be modified by some other functions but (1) that seems quite error-prone and (2) I haven't been able to find out how to release the `PyOperation` that is causing the problem in my case. Before I spend more time to think about this topic, let me ask for input from the people that are more familiar with that part of the code: @stellaraccident, @teqdruid, @mikeurbach, @ftynse.

### PR DESCRIPTION
**Pull request by makslevental**
Fixes https://github.com/llvm/llvm-project/issues/69730 (also see https://reviews.llvm.org/D155543).

There are  two things outstanding (why I didn't land before):

1. add some C API tests for `mlirOperationWalk`;
2. potentially refactor how the invalidation in `run` works; the first version of the code looked like this:
    ```cpp
    if (invalidateOps) {
      auto *context = op.getOperation().getContext().get();
      MlirOperationWalkCallback invalidatingCallback =
          [](MlirOperation op, void *userData) {
            PyMlirContext *context =
                static_cast<PyMlirContext *>(userData);
            context->setOperationInvalid(op);
          };
      auto numRegions =
          mlirOperationGetNumRegions(op.getOperation().get());
      for (int i = 0; i < numRegions; ++i) {
        MlirRegion region =
            mlirOperationGetRegion(op.getOperation().get(), i);
        for (MlirBlock block = mlirRegionGetFirstBlock(region);
             !mlirBlockIsNull(block);
             block = mlirBlockGetNextInRegion(block))
          for (MlirOperation childOp =
                   mlirBlockGetFirstOperation(block);
               !mlirOperationIsNull(childOp);
               childOp = mlirOperationGetNextInBlock(childOp))
            mlirOperationWalk(childOp, invalidatingCallback, context,
                              MlirWalkPostOrder);
      }
    }
    ```
    This is verbose and ugly but it has the important benefit of not executing `mlirOperationEqual(rootOp->get(), op)` for every op underneath the root op. 

Supposing there's no desire for the slightly more efficient but highly convoluted approach, I can land this "posthaste".
But, since we have eyes on this now, any suggestions or approaches (or needs/concerns) are welcome.

### CODE REVIEW

File: mlir/include/mlir-c/IR.h [hunk 1]
```diff
@@ -698,6 +698,21 @@ MLIR_CAPI_EXPORTED void mlirOperationMoveAfter(MlirOperation op,
 /// ownership is transferred to the block of the other operation.
 MLIR_CAPI_EXPORTED void mlirOperationMoveBefore(MlirOperation op,
                                                 MlirOperation other);
+
+typedef enum MlirWalkOrder {
```
Comment (ftynse) [inline mlir/include/mlir-c/IR.h:702]: Nit: documentation, here and below.

**Review by ftynse — APPROVED** [review]
LGTM.

Stupid suggestion: if we could "revalidate" ops, we can invalidate everything including the root and than revalidate the root back.

**Comment by makslevental** [comment]
> Stupid suggestion: if we could "revalidate" ops, we can invalidate everything including the root and than revalidate the root back.

image

but if "validation" becomes reversible then it might be wise to put `LiveOperationMap liveOperations` behind a mutex? Just so someone doesn't accidentally create a race condition at some point down the line?

One alternative is to make the walk `MlirWalkPreOrder`, do nothing but set a flag like `rootSeen = true`, and from then on check that flag instead of performing `mlirOperationEqual`. I should've done that in the first place I think...

**Comment by jpienaar** [comment]
So invalidating is default on and only in cases where (expert user) knows it's safe can they opt out? (Reading on mobile so high chance of misreading :-))

**Comment by makslevental** [comment]
> So invalidating is default on and only in cases where (expert user) knows it's safe can they opt out? (Reading on mobile so high chance of misreading :-))

Yup "fail-dangerous" only if you're a professional 🙂.
