### PR TITLE
[RISCV] Treat bf16->f32 as separate ExtKind in combineOp_VLToVWOp_VL.

### LINKED ISSUE #144651: [RISCV] combineOp_VLToVWOp_VL can miscompile or crash with Zvfbfwma
This test case that mixes bf16 and f16 miscompiles to a vfwmacc.vv instruction when both Zvfh and Zvfbfwma are enabled.

```
define <4 x float> @fixed(<4 x float> %rd, <4 x half> %a, <4 x bfloat> %b) local_unnamed_addr #0 {
  %a_ext = fpext <4 x half> %a to <4 x float>
  %b_ext = fpext <4 x bfloat> %b to <4 x float>
  %fma = tail call <4 x float> @llvm.fma.v4f32(<4 x float> %a_ext, <4 x float> %b_ext, <4 x float> %rd)
  ret <4 x float> %fma
}
```

This test case crashes with Zvfbfwma

```
define <4 x float> @fixed(<4 x float> %rd, <2 x bfloat> %a, <4 x bfloat> %b) local_unnamed_addr #0 {
  %b_ext = fpext <4 x bfloat> %b to <4 x float>
  %1 = extractelement <2 x bfloat> %a, i64 1
  %a_extract = fpext bfloat %1 to float
  %a_insert = insertelement <4 x float> poison, float %a_extract, i64 0
  %a_shuffle = shufflevector <4 x float> %a_insert, <4 x float> poison, <4 x i32> zeroinitializer
  %fma = tail call <4 x float> @llvm.fma.v4f32(<4 x float> %a_shuffle, <4 x float> %b_ext, <4 x float> %rd)
  ret <4 x float> %fma
}
```

### PR DESCRIPTION
**Pull request by topperc**
This allows us to better track the narrow type we need and to fix miscompiles if f16->f32 and bf16->f32 extends are mixed.

Fixes #144651.

Still need to add tests, but it's late and I need sleep.

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -16628,17 +16630,17 @@ struct NodeExtensionHelper {
...
-      return false;
-    // The only bf16 extension we can do is vfmadd_vl -> vfwmadd_vl with
-    // zvfbfwma
-    if (NarrowEltVT == MVT::bf16 && (!Subtarget.hasStdExtZvfbfwma() ||
-                                     Root->getOpcode() != RISCVISD::VFMADD_VL))
-      return false;
-    return true;
+    if (NarrowEltVT == MVT::f16 && Subtarget.hasVInstructionsF16())
+      return true;
+    return false;
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp]: Nit, merge into `return NarrowEltVT == MVT::f32 || (NarrowEltVT == MVT::f16 && Subtarget.hasVInstructionsF16())`?

**Review by lukel97 — APPROVED** [review]
LGTM
