### PR TITLE
[mlir][OpenMP] Add __atomic_store to AtomicInfo

### LINKED ISSUE #113479: [flang][OpenMP] atomic write on complex
```
program complex_write
  complex :: z
  !$omp atomic write
    z = cmplx(1,1,kind(x))
end program
```

This currently hits an assertion guarding types allowed to be used in an atomic write. Similar work has been done already for atomic update and atomic read:
- https://github.com/llvm/llvm-project/pull/111377
- https://github.com/llvm/llvm-project/pull/92364

### LINKED ISSUE #115652: [flang][OpenMP] llvm-project/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:8095: OpenMPIRBuilder::InsertPointTy llvm::OpenMPIRBuilder::createAtomicWrite(const llvm::OpenMPIRBuilder::LocationDescription &, llvm::OpenMPIRBuilder::AtomicOpValue &, llvm::Value *, llvm::AtomicOrdering): Assertion `(XElemTy->isFloatingPointTy() || XElemTy->isIntegerTy() || XElemTy->isPointerTy()) && "OMP atomic write expected a scalar type"' failed.
Reproducer:
```f90
real :: r1
complex :: c1
!$omp atomic write
c1 = r1
end
```

Stack dump:
```console
 #0 0x00007f6aacc5f727 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) 
 #1 0x00007f6aacc5d2be llvm::sys::RunSignalHandlers() 
 #2 0x00007f6aacc5fdfa SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f6aac597520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f6aac5eb9fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007f6aac5eb9fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x00007f6aac5eb9fc pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x00007f6aac597476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f6aac57d7f3 abort ./stdlib/abort.c:81:7
 #9 0x00007f6aac57d71b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x00007f6aac58ee96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x00007f6aa0b1259b llvm::OpenMPIRBuilder::createAtomicWrite(llvm::OpenMPIRBuilder::LocationDescription const&, llvm::OpenMPIRBuilder::AtomicOpValue&, llvm::Value*, llvm::AtomicOrdering) 
#12 0x00007f6aa002f7f8 convertHostOrTargetOperation(mlir::Operation*, llvm::IRBuilderBase&, mlir::LLVM::ModuleTranslation&) OpenMPToLLVMIRTranslation.cpp:0:0
#13 0x00007f6aa2a44b1c mlir::LLVM::ModuleTranslation::convertOperation(mlir::Operation&, llvm::IRBuilderBase&, bool) 
#14 0x00007f6aa2a4515a mlir::LLVM::ModuleTranslation::convertBlockImpl(mlir::Block&, bool, llvm::IRBuilderBase&, bool) 
#15 0x00007f6aa2a49037 mlir::LLVM::ModuleTranslation::convertOneFunction(mlir::LLVM::LLVMFuncOp) 
#16 0x00007f6aa2a4beed mlir::LLVM::ModuleTranslation::convertFunctions() 
#17 0x00007f6aa2a4e83c mlir::translateModuleToLLVMIR(mlir::Operation*, llvm::LLVMContext&, llvm::StringRef, bool) 
#18 0x00007f6aad92632a Fortran::frontend::CodeGenAction::generateLLVMIR() 
#19 0x00007f6aad92a2e8 Fortran::frontend::CodeGenAction::executeAction() 
#20 0x00007f6aad91f0fc Fortran::frontend::FrontendAction::execute() 
#21 0x00007f6aad9052a2 Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) 
#22 0x00007f6aada8f37c Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) 
#23 0x000055dc62ae335b fc1_main(llvm::ArrayRef<char const*>, char const*) 
#24 0x000055dc62ae194a main 
#25 0x00007f6aac57ed90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#26 0x00007f6aac57ee40 call_init ./csu/../csu/libc-start.c:128:20
#27 0x00007f6aac57ee40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#28 0x000055dc62ae1465 _start 
flang-20: error: unable to execute command: Aborted (core dumped)
flang-20: error: flang frontend command failed due to signal (use -v to see invocation)
flang version 20.0.0git (https://github.com/llvm/llvm-project.git 0ac4821b718dd14e80d3856efa532d52df6878bb)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

### PR DESCRIPTION
**Pull request by NimishMishra**
This PR adds functionality for `__atomic_store` libcall in AtomicInfo. This allows for supporting complex types in `atomic write`.

Fixes https://github.com/llvm/llvm-project/issues/113479
Fixes https://github.com/llvm/llvm-project/issues/115652

### CODE REVIEW

**Comment by tblah** [comment]
Thanks for your work on this. I think there is some memory corruption going on for complex numbers of different kinds:
```
Program atomic_corruption
  Use omp_lib
  complex(8) :: x = 0
  ! problem goes away if this is turned into complex(8):
  complex v,v2
  v2 = 0
  !$omp parallel num_threads(1)
  if (real(v2)/=0.0) stop "v2 corrupted at 1"
  !$omp atomic read
    v = x
  if (real(v2)/=0.0) stop "v2 corrupted at 2"
  !$omp end parallel
end program
```
When I run this I hit the second stop "v2 corrupted at 2". The problem goes away when x and v have the same kind.

**Comment by NimishMishra** [comment]
Thanks for the issue @tblah. I am working on a fix for this.

**Comment by NimishMishra** [comment]
Hi @tblah,
    It seems the issue in your crash is with `__atomic_load`; still it affects `__atomic_store`. I think the issue is the way the first argument of the libcall is generated. Right now, the `type` of the atomic variable is coming out as `ptr`, which is 8 bytes by default. We rather want to argument to the libcall to include the size of the allocated type.

I have made a branch off this PR here: https://github.com/NimishMishra/f18-llvm-project/commits/atomic_allocated_type_size/. Could you check if you are happy with it? I can submit it for review as a separate PR then, since the issue is with all of atomic read/write/update.

**Comment by tblah** [comment]
> I have made a branch off this PR here: https://github.com/NimishMishra/f18-llvm-project/commits/atomic_allocated_type_size/. Could you check if you are happy with it? I can submit it for review as a separate PR then, since the issue is with all of atomic read/write/update.

Thanks for looking into this. I think we need to perform an actual cast at the fortran level. For example this segfaults when built with omp because the write of `x` overflows `v`:
```
program repo
  complex(8) :: x = 0
  complex v
  integer :: i = 1
  !$omp parallel
    !$omp atomic read
      v = x
  !$omp end parallel
  print *,"ok"
end program
```

Building without openmp there is a `fir.convert` to change `x` into a `complex(4)` before performing the assignment.

**Comment by NimishMishra** [comment]
Hi @tblah     

    It seems that just adding a convert in fortran is not sufficient. I added an explicit convert, and somewhere down the line, it gets removed, and I can still reproduce the segfault


FIR: 
```
omp.parallel {
      %15 = fir.convert %5 : (!fir.ref<complex<f64>>) -> !fir.ref<complex<f32>>
      omp.atomic.read %3 = %15 : !fir.ref<complex<f32>>, !fir.ref<complex<f32>>, complex<f64>
      omp.terminator
    }
```

Corresponding LLVM Dialect
```
    omp.parallel {
      omp.atomic.read %1 = %6 : !llvm.ptr, !llvm.ptr, !llvm.struct<(f64, f64)>
      omp.terminator
    }
```

  I'm investigating where the issue is.

**Comment by NimishMishra** [comment]
Hi @tblah 

I have implemented a WIP solution here: https://github.com/NimishMishra/f18-llvm-project/commit/ae1196fd98559f1a6d37b3e2e09957e02ffd9eb8#diff-a6c8db9d350ec59f4eb93f27f29468b01c9590426a11c9cb79e499bc96b28adc.

Do you think this could be an acceptable way of going about this? One upside I see is that we no longer need to do the implicit cast during building LLVM IR, about which Michael also had reservations. 

If you are okay with the approach, I'll prepare a new PR for the same combining casts for different atomic operations. In that case, maybe we can let this current PR go through (since the fix is completely unrelated).

**Comment by tblah** [comment]
> Hi @tblah
> Do you think this could be an acceptable way of going about this? One upside I see is that we no longer need to do the implicit cast during building LLVM IR, about which Michael also had reservations.

Thanks for the update.

This looks good to me. We might need casts for other kinds of atomic operations too.

**Comment by NimishMishra** [comment]
> The issues #113479 and #115652 are also fixed by #21055.

Thanks @Meinersbur. Indeed, that PR has a better approach. I am adding @tblah as a reviewer there, in case he would like to take a look.

Do we have to wait for acceptance from the Clang community though? Last time, iirc, there was some objection to the RFC.

**Comment by NimishMishra** [comment]
The test failure `lldb-shell.Unwind/split-machine-functions.test` seems unrelated to the PR.

File: llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp [hunk 1]
```diff
@@ -8684,20 +8684,31 @@ OpenMPIRBuilder::createAtomicRead(const LocationDescription &Loc,
...
   assert((XElemTy->isFloatingPointTy() || XElemTy->isIntegerTy() ||
-          XElemTy->isPointerTy()) &&
+          XElemTy->isPointerTy() || XElemTy->isStructTy()) &&
          "OMP atomic write expected a scalar type");
 
   if (XElemTy->isIntegerTy()) {
     StoreInst *XSt = Builder.CreateStore(Expr, X.Var, X.IsVolatile);
     XSt->setAtomic(AO);
+  } else if (XElemTy->isStructTy()) {
+
```
Comment (Meinersbur) [inline llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp:8702]: [nit] empty line looks unnecessary here

**Review by Meinersbur — APPROVED** [review]
LGTM

**Review by tblah — APPROVED** [review]
Thanks Nimish
