### PR TITLE
[Sema] Fix handling of fields with initializers in nested anonymous unions.

### LINKED ISSUE #91257: [Clang] CodeGen issues with C++20 bitfield initializers in anonymous structs/unions
Hi,

I noticed some issues when using C++20 bitfield member initialization inside nested anonymous structs/unions. I'm not entirely sure how much of this is undefined (or intended) behavior, but it still seems to me that clangs behavior isn't right here.

Given the following code, this returns an uninitialized value from main() (compiles down to just a `ret` after optimization) and when using clang with assertions enabled, this triggers the `(Field->isUnnamedBitfield() || Field->isAnonymousStructOrUnion()) && "Only unnamed bitfields or ananymous class allowed"` assert in [CGExprAgg.cpp](https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGExprAgg.cpp#L1737). Also, ananymous should be anonymous.
```cpp
struct nested_anon_bitfield_init_t {
    union {
        struct {
            int inner : 32 { 42 };
        };
        int outer;
    };
};

int main() {
    return nested_anon_bitfield_init_t{}.inner;
}
```
[on compiler-explorer](https://compiler-explorer.com/z/WoqvMdGK9)
Tested on current trunk and 18.1.
Note that GCC returns 0 here.

__

Similarly, when using less nesting, this no longer triggers the assertion, but still returns an uninitialized value:
```cpp
union less_nested_anon_bitfield_init_t {
    struct {
        int inner : 32 { 42 };
    };
};

int main() {
    return less_nested_anon_bitfield_init_t{}.inner;
}
```
[on compiler-explorer](https://compiler-explorer.com/z/e188a3dPP)
Again, GCC returns 0 here.

Intuitively, both should return 42 of course.

### PR DESCRIPTION
**Pull request by efriedma-quic**
Make sure we count the anonymous union as an initialized field, so we properly construct the AST.

Included bonus testcase Test3, which shows a remaining gap: an anonymous union can contain a partially initialized anonymous struct, and we handle that inconsistently.

Fixes #91257

### CODE REVIEW

**Review by Endilll — APPROVED** [review]
LGTM, but someone else should take a look as well.

**Comment by efriedma-quic** [comment]
Ping

File: clang/test/SemaCXX/cxx1y-initializer-aggregates.cpp [hunk 1]
```diff
@@ -77,3 +77,38 @@ namespace use_self {
...
+  static_assert(Test1{}.inner == 42, "");
+  struct Test2 {
+    union {
+      struct {
+        int inner : 32 { 42 }; // expected-warning {{C++20 extension}}
+      };
+      int outer;
+    };
+  };
+  static_assert(Test2{}.inner == 42, "");
```
Comment (zygoloid) [inline clang/test/SemaCXX/cxx1y-initializer-aggregates.cpp:97]: Might be useful to also test that the rest of the union member gets initialized.
```suggestion
  struct Test2 {
    union {
      struct {
        int inner : 32 { 42 }; // expected-warning {{C++20 extension}}
        int inner_no_init;
      };
      int outer;
    };
  };
  static_assert(Test2{}.inner == 42, "");
  static_assert(Test2{}.inner_no_init == 0, "");
```

File: clang/test/SemaCXX/cxx1y-initializer-aggregates.cpp [hunk 2]
```diff
@@ -77,3 +77,38 @@ namespace use_self {
...
+        int inner : 32 { 42 }; // expected-warning {{C++20 extension}}
+      };
+      int outer;
+    };
+  };
+  constexpr char f(Test3) { return 1; } // expected-note {{candidate function}}
+  constexpr char f(Int) { return 2; } // expected-note {{candidate function}}
+  // FIXME: This shouldn't be ambiguous; either we should reject the declaration
+  // of Test3, or we should exclude f(Test3) as a candidate.
+  static_assert(f({1}) == 2, ""); // expected-error {{call to 'f' is ambiguous}}
```
Comment (zygoloid) [inline clang/test/SemaCXX/cxx1y-initializer-aggregates.cpp:113]: Maybe an `expected-error` for `Test3 test3 = {1};` would be nice here too. I think that part at least should work -- if I'm understanding correctly, we're only missing the check for the uninitialized reference member during overload resolution / in `VerifyOnly` mode?

**Review by zygoloid — APPROVED** [review]
Looks good to me too.
