### PR TITLE
[DirectX] Simplify and correct the flattening of GEPs in DXILFlattenArrays

### LINKED ISSUE #140416: [DirectX] Validation: TGSM pointers must originate from an unambiguous TGSM global variable.
This bug looks very similar to  https://github.com/llvm/llvm-project/issues/139013

## error case:
```bash
../../DXC_DEBUG_BUILD/bin/dxv validation/GemmSmallGemm_Bias_float_b16c32.dat
```

https://github.com/microsoft/DirectXShaderCompiler/blob/adffd31eb02f690d9d1afe86c7fa6f12b4e70aa1/lib/DxilValidation/DxilValidation.cpp#L3541

```gdb
(lldb) expr Ptr
(llvm::BitCastInst *) $0 = 0x000000011e10ff58
(lldb) expr Ptr->dump()
  %18 = bitcast [512 x float] addrspace(3)* @aTile.1dim to [512 x float] addrspace(3)*
```

### LINKED ISSUE #145370: [DirectX] Indexing into TGSM flattened arrays of vectors is incorrect
Indexing into an array of vectors located in thread group shared memory are incorrect

https://godbolt.org/z/nq5Pq88eh
https://godbolt.org/z/9fesTfKre

```hlsl
// compile args: -E CSMain -T cs_6_4 -enable-16bit-types
groupshared uint2 g[2];
[numthreads(2, 1, 1)]
void CSMain(uint3 Tid: SV_GroupThreadId) {
  g[1][1] = 0;
}
```

```llvm
@g.scalarized.1dim = local_unnamed_addr addrspace(3) global [4 x i32] zeroinitializer, align 8

; Function Attrs: noinline nounwind memory(write, argmem: none, inaccessiblemem: none)
define void @CSMain() local_unnamed_addr #0 {
    #dbg_value(<3 x i32> poison, !29, !DIExpression(DW_OP_LLVM_fragment, 0, 96), !39)
  store i32 0, ptr addrspace(3) @g.scalarized.1dim, align 4, !dbg !40
  ret void
}
```

This is potentially the cause of some cases of #140417

### PR DESCRIPTION
**Pull request by Icohedron**
In tandem with #146800, this PR fixes #145370

This PR simplifies the logic for collapsing GEP chains and replacing GEPs to multidimensional arrays with GEPs to flattened arrays. This implementation avoids unnecessary recursion and more robustly computes the index to the flattened array by using the GEPOperator's collectOffset function, which has the side effect of allowing "i8 GEPs" and other types of GEPs to be handled naturally in the flattening / collapsing of GEP chains.

Furthermore, a handful of LLVM DirectX CodeGen tests have been edited to fix incorrect GEP offsets, mismatched types (e.g., loading i32s from a an array of floats), and typos.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 1]
```diff
@@ -225,131 +210,139 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
-    }
-  }
-}
+  // Obtain the variable and constant byte offsets computed by this GEP
+  const DataLayout &DL = GEP.getDataLayout();
+  unsigned BitWidth = DL.getIndexTypeSizeInBits(GEP.getType());
+  Info.ConstantOffset = {BitWidth, 0};
+  bool Success = GEP.collectOffset(DL, BitWidth, Info.VariableOffsets,
+                                   Info.ConstantOffset);
+  (void)Success;
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: what is this line for?

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: I think it's an alternative to `[maybe_unused]`. @bogner would probably know better what it's for.
I copied it over from DXILCBufferAccess.cpp https://github.com/llvm/llvm-project/blob/32180cf9f9eb921a793bb208cf3bbfb1b86ee2ae/llvm/lib/Target/DirectX/DXILCBufferAccess.cpp#L66-L69

**Comment by Icohedron** [comment]
I'm not sure why the HLSL Tests GitHub workflow is failing on `LLVM-Unit :: Analysis/./AnalysisTests/IR2VecTest/CreateInvalidMode`. I am not able to reproduce the failure on my end.
```
> build/unittests/Analysis/./AnalysisTests --gtest_filter=IR2VecTest.CreateInvalidMode
Note: Google Test filter = IR2VecTest.CreateInvalidMode
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from IR2VecTest
[ RUN      ] IR2VecTest.CreateInvalidMode
[       OK ] IR2VecTest.CreateInvalidMode (0 ms)
[----------] 1 test from IR2VecTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 2]
```diff
@@ -40,18 +41,19 @@ class DXILFlattenArraysLegacy : public ModulePass {
...
+  SmallMapVector<Value *, APInt, 4> VariableOffsets;
+  APInt ConstantOffset;
 };
 
 class DXILFlattenArraysVisitor
     : public InstVisitor<DXILFlattenArraysVisitor, bool> {
 public:
-  DXILFlattenArraysVisitor() {}
+  DXILFlattenArraysVisitor(
+      DenseMap<GlobalVariable *, GlobalVariable *> &GlobalMap)
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: It isn't clear why this was neccessary. Why do we need a reference of GlobalMap in the `DXILFlattenArraysVisitor`?

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 3]
```diff
@@ -78,35 +80,20 @@ class DXILFlattenArraysVisitor
...
-                         SmallVector<uint64_t> Dims = SmallVector<uint64_t>(),
-                         bool AllIndicesAreConstInt = true);
-  bool visitGetElementPtrInstInGEPChain(GetElementPtrInst &GEP);
-  bool visitGetElementPtrInstInGEPChainBase(GEPData &GEPInfo,
-                                            GetElementPtrInst &GEP);
 };
 } // namespace
 
 bool DXILFlattenArraysVisitor::finish() {
+  GEPChainInfoMap.clear();
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:96]: This is fine. not sure if its necessary though. The `GEPChainInfoMap` will get recreated on every construction of th `DXILFlattenArraysVisitor` which should be the same as clearing it. That said the idea makes sense, there are going to be many invalid gep chains the longer we don't clear because we are flattening as we walk the chains.  So I think it makes sense, but we should probably be clearing  the `GEPChainInfoMap` after each function, while I think this clears it after each module.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 4]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+      Value *NewGEP =
+          Builder.CreateGEP(GEP.getSourceElementType(), OldGEPI, Indices,
+                            GEP.getName(), GEP.getNoWrapFlags());
+      assert(isa<GetElementPtrInst>(NewGEP) &&
+             "Expected newly-created GEP to be an instruction");
+      GetElementPtrInst *NewGEPI = cast<GetElementPtrInst>(NewGEP);
+
+      GEP.replaceAllUsesWith(NewGEPI);
+      GEP.eraseFromParent();
+      visitGetElementPtrInst(*OldGEPI);
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: I have some concerns about this if this can be recursive in the constexpr case more than one level deep.  Your calls to `visitGetElementPtrInst` and you are doing `eraseFromParent` before you do the recursions. We usualy can only get away with doing one instruction erasure via the visitor pattern because of our use of `make_early_inc_range` To be able to  erase more you typically need to start by erasing the leaf geps in the gep chain.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 5]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+  // Construct GEPInfo for this GEP
+  GEPInfo Info;
+
+  // Obtain the variable and constant byte offsets computed by this GEP
+  const DataLayout &DL = GEP.getDataLayout();
+  unsigned BitWidth = DL.getIndexTypeSizeInBits(GEP.getType());
+  Info.ConstantOffset = {BitWidth, 0};
+  bool Success = GEP.collectOffset(DL, BitWidth, Info.VariableOffsets,
+                                   Info.ConstantOffset);
+  (void)Success;
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: i would prefer if we just did `[maybe_unused]`

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 6]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
-  auto [TotalElements, BaseType] = getElementCountAndType(ArrType);
-  ArrayType *FlattenedArrayType = ArrayType::get(BaseType, TotalElements);
+    Info.RootFlattenedArrayType = cast<ArrayType>(RootTy);
+  }
 
-  Value *PtrOperand = GEP.getPointerOperand();
+  // GEPs without users or GEPs with non-GEP users should be replaced such that
+  // the chain of GEPs they are a part of are collapsed to a single GEP into a
+  // flattened array.
+  bool ReplaceThisGEP = GEP.users().empty();
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:301]: this seems unnecessary, why can't you just do 
```suggestion
  bool ReplaceThisGEP =  false;
```

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 7]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+  for (Value *User : GEP.users())
+    if (!isa<GetElementPtrInst>(User))
+      ReplaceThisGEP = true;
+
+  if (ReplaceThisGEP) {
+    // GEP.collectOffset returns the offset in bytes. So we need to divide its
+    // offsets by the size in bytes of the element type
+    unsigned BytesPerElem = Info.RootFlattenedArrayType->getArrayElementType()
+                                ->getPrimitiveSizeInBits() /
+                            8;
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: I'm sure there is a byte size constant we can use here.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 8]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+    // variable byte offsets in the GEPInfo
+    IRBuilder<> Builder(&GEP);
+    Value *ZeroIndex = Builder.getInt32(0);
+    uint64_t ConstantOffset =
+        Info.ConstantOffset.udiv(BytesPerElem).getZExtValue();
+    assert(ConstantOffset < UINT32_MAX &&
+           "Constant byte offset for flat GEP index must fit within 32 bits");
+    Value *FlattenedIndex = Builder.getInt32(ConstantOffset);
+    for (auto [VarIndex, Multiplier] : Info.VariableOffsets) {
+      assert(Multiplier.getActiveBits() <= 32 &&
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:322]: isn't there a 32 bit constant we can use?

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 9]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+          Builder.CreateGEP(GEP.getSourceElementType(), OldGEPI, Indices,
+                            GEP.getName(), GEP.getNoWrapFlags());
+      assert(isa<GetElementPtrInst>(NewGEP) &&
+             "Expected newly-created GEP to be an instruction");
+      GetElementPtrInst *NewGEPI = cast<GetElementPtrInst>(NewGEP);
+
+      GEP.replaceAllUsesWith(NewGEPI);
+      GEP.eraseFromParent();
+      visitGetElementPtrInst(*OldGEPI);
+      visitGetElementPtrInst(*NewGEPI);
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: why do we need to visit the new Gep?

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 10]
```diff
@@ -225,131 +212,149 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
 
-    if (auto *ArrayTy = dyn_cast<ArrayType>(CurrentType)) {
-      Dims.push_back(ArrayTy->getNumElements());
-      CurrentType = ArrayTy->getElementType();
-    } else {
-      assert(false && "Expected array type in GEP chain");
+  // Replace a GEP ConstantExpr pointer operand with a GEP instruction so that
+  // it can be visited
+  if (auto *PtrOpGEPCE = dyn_cast<ConstantExpr>(PtrOperand))
+    if (PtrOpGEPCE->getOpcode() == Instruction::GetElementPtr) {
```
Comment (farzonl) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: combine these to one line like so 
```suggestion
  if (auto *PtrOpGEPCE = dyn_cast<ConstantExpr>(PtrOperand); 
    PtrOpGEPCE && PtrOpGEPCE->getOpcode() == Instruction::GetElementPtr) {
```

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 3 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:96]: > This is fine. not sure if its necessary though. 

This is a change I added later because I found that tests with multiple functions had GEPs that were incorrectly flattened because `GEPOperator*` from previous functions happened to collide with `GEPOperator*` in the `GEPChainInfoMap` while processing the current function.

>  The GEPChainInfoMap will get recreated on every construction of th DXILFlattenArraysVisitor which should be the same as clearing it.

The `DXILFlattenArraysVisitor` is only created once and it's for the module.
https://github.com/llvm/llvm-project/blob/db9162dd3c12e9f5e1d28abdfedf9758fd575814/llvm/lib/Target/DirectX/DXILFlattenArrays.cpp#L462-L490

> we should probably be clearing the GEPChainInfoMap after each function

The `finish()` function is called at the end of `DXILFlattenArraysVisitor::visit(Function &F)`, so the `GEPChainInfoMap` is indeed cleared after each function.
https://github.com/llvm/llvm-project/blob/db9162dd3c12e9f5e1d28abdfedf9758fd575814/llvm/lib/Target/DirectX/DXILFlattenArrays.cpp#L362-L371

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 4 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: It is fine because ~~there can only be one `ConstantExpr` GEP in a chain~~ and it has to be the root/start of the chain.
A `ConstantExpr` GEP can not take virtual registers as any of its operands, which would imply that the ptr operand has to be a global variable and the indices must be constant ints.

Edit: A ConstantExpr GEP can have its pointer operand be another ConstantExpr GEP. But this is still not an issue because these GEPs are being inserted before the current "head" of the `make_early_inc_range` traversal.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 6 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:301]: This was to preserve the behavior of the previous implementation in the `llvm/test/CodeGen/DirectX` tests. There are many tests that create GEPs that are not used. So I replace unused GEPs to keep the tests working.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 9 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: The `GEPChainInfoMap` entry for the new GEP needs to be filled in case the new GEP is not the leaf/end of a GEP chain.
The new GEP may also be the leaf/end of a GEP chain itself and need to be replaced with a fattened GEP.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 6 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:301]: I can set `bool ReplaceThisGEP =  false;` and then update the tests so that all the GEPs are used.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 2 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: It's necessary because otherwise the `DXILFlattenArraysVisitor` won't have visibility of the `GlobalMap` which comes from a stack-allocated variable here
https://github.com/llvm/llvm-project/blob/db9162dd3c12e9f5e1d28abdfedf9758fd575814/llvm/lib/Target/DirectX/DXILFlattenArrays.cpp#L462-L466

which is necessary to determine the type of the GEP
https://github.com/llvm/llvm-project/blob/db9162dd3c12e9f5e1d28abdfedf9758fd575814/llvm/lib/Target/DirectX/DXILFlattenArrays.cpp#L273-L284

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 6 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:301]: I suppose we can leave this as is for now.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 9 above)
Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: If it just needs to be for book keeping purposes can we take the book keeping part out and make it a helper that we can call here.

**Review by farzonl — APPROVED** [review]
LGTM

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 9 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: It's not just for book keeping; the new GEP can be replaced/flattened in that visit.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 7 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: I can maybe use `DL.getTypeAllocSize(Info.RootFlattenedArrayType->getArrayElementType());` but otherwise `Type *` doesn't have a function that returns size in bytes.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 8 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:322]: IMO, `Multiplier.getActiveBits() <= 32` is already clear enough that it's testing the number held fits within an unsigned 32 bit integer.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 2 above)
Comment (inbelic) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: nit: Can we use `SmallDenseMap` here (and elsewhere)?

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 11]
```diff
@@ -225,131 +212,145 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+  // Replace a GEP ConstantExpr pointer operand with a GEP instruction so that
+  // it can be visited
+  if (auto *PtrOpGEPCE = dyn_cast<ConstantExpr>(PtrOperand);
+      PtrOpGEPCE && PtrOpGEPCE->getOpcode() == Instruction::GetElementPtr) {
+    GetElementPtrInst *OldGEPI =
+        cast<GetElementPtrInst>(PtrOpGEPCE->getAsInstruction());
+    OldGEPI->insertBefore(GEP.getIterator());
+
+    IRBuilder<> Builder(&GEP);
+    SmallVector<Value *> Indices(GEP.indices());
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:236]: nit: Can we just pass `GEP.indices()` as the parameter below?

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 12]
```diff
@@ -225,131 +212,145 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
-                             AllIndicesAreConstInt);
-      GepUses = true;
+  // Construct GEPInfo for this GEP
+  GEPInfo Info;
+
+  // Obtain the variable and constant byte offsets computed by this GEP
+  const DataLayout &DL = GEP.getDataLayout();
+  unsigned BitWidth = DL.getIndexTypeSizeInBits(GEP.getType());
+  Info.ConstantOffset = {BitWidth, 0};
+  [[maybe_unused]] bool Success = GEP.collectOffset(
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:258]: Does `collectOffset` have a side-effect that we want? Or is this just for the assert?

nit: if it is just for the assert we could probably just but the expression directly there

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 13]
```diff
@@ -225,131 +212,145 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+    // We should try to determine the type of the root from the pointer rather
+    // than the GEP's source element type because this could be a scalar GEP
+    // into an array-typed pointer from an Alloca or Global Variable.
+    Type *RootTy = GEP.getSourceElementType();
+    if (auto *GlobalVar = dyn_cast<GlobalVariable>(PtrOperand)) {
+      if (GlobalMap.contains(GlobalVar))
+        GlobalVar = GlobalMap[GlobalVar];
+      Info.RootPointerOperand = GlobalVar;
+      RootTy = GlobalVar->getValueType();
+    } else if (auto *Alloca = dyn_cast<AllocaInst>(PtrOperand)) {
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: style-nit: We can remove the parens

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 14]
```diff
@@ -225,131 +212,145 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
-                    std::move(Indices), std::move(Dims), AllIndicesAreConstInt};
-    return visitGetElementPtrInstInGEPChainBase(GEPInfo, GEP);
+    // Construct a new GEP for the flattened array to replace the current GEP
+    Value *NewGEP = Builder.CreateGEP(
+        Info.RootFlattenedArrayType, Info.RootPointerOperand,
+        {ZeroIndex, FlattenedIndex}, GEP.getName(), GEP.getNoWrapFlags());
+
+    // Replace the current GEP with the new GEP. Store GEPInfo into the map
+    // for later use in case this GEP was not the end of the chain
+    GEPChainInfoMap.insert({cast<GEPOperator>(NewGEP), std::move(Info)});
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:348]: nit: is there any merit to removing the old gep from the map at this point? I see that we will clear it above anyway

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 15]
```diff
@@ -225,131 +212,145 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
+    // Compute the 32-bit index for this flattened GEP from the constant and
+    // variable byte offsets in the GEPInfo
+    IRBuilder<> Builder(&GEP);
+    Value *ZeroIndex = Builder.getInt32(0);
+    uint64_t ConstantOffset =
+        Info.ConstantOffset.udiv(BytesPerElem).getZExtValue();
+    assert(ConstantOffset < UINT32_MAX &&
+           "Constant byte offset for flat GEP index must fit within 32 bits");
+    Value *FlattenedIndex = Builder.getInt32(ConstantOffset);
+    for (auto [VarIndex, Multiplier] : Info.VariableOffsets) {
```
Comment (inbelic) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:321]: Will this work as we expect for a mix of variable and constant offsets?

Is there a test for this?

**Review by inbelic — COMMENTED** [review]
LGTM, almost all nits.

Just the last comment that I would like to be noted before I approve

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 12 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:258]: `collectOffset` does have a side effect that is populating `Info.ConstantOffset` and `Info.VariableOffsets`

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 11 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:236]: nope. `GEP.indices()` returns an iterator range and not a vector or array, so it's invalid.

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 14 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:348]: The old gep shouldn't even be put into the map in the first place. If a gep got replaced, its replacement will have an entry in the map. If a gep does not get replaced, then that gep will have an entry in the map and is guaranteed to not be replaced later (because GEPs are not visited more than once).

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 15 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:321]: Yes it will work as expected. There are existing tests mixing variable with constant offsets in `test/CodeGen/DirectX/flatten-array.ll`.

**Review by inbelic — APPROVED** [review]
