### PR TITLE
Fix #75686: add iter_swap and iter_move to the matched name

### LINKED ISSUE #75686: `bugprone-exception-escape.FunctionsThatShouldNotThrow` should consider `iter_move` and `iter_swap`
These are the (moral) equivalent of `*std::move(i)` and `swap(*i, *j)`, and shouldn't throw either.

### PR DESCRIPTION
**Pull request by da-viper**
Fixes  #75686

### CODE REVIEW

**Comment by EugeneZelenko** [comment]
Should Release Notes be updated?

**Review by PiotrZSL — CHANGES_REQUESTED** [review]
Missing tests, documentation, release notes.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/exception-escape.cpp [hunk 1]
```diff
@@ -586,6 +586,16 @@ void swap(int&, int&) {
   throw 1;
 }
 
+void iter_swap(int&, int&) {
+  // CHECK-MESSAGES: :[[@LINE-1]]:6: warning: an exception may be thrown in function 'iter_swap' which should not throw exceptions
+  throw 1;
+}
+
+void iter_move(int&, int&) {
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/exception-escape.cpp:594]: NOTE: Isn't iter_move taking single argument (iterator) ?

File: clang-tools-extra/clang-tidy/bugprone/ExceptionEscapeCheck.cpp [hunk 2]
```diff
@@ -58,14 +58,15 @@ void ExceptionEscapeCheck::storeOptions(ClangTidyOptions::OptionMap &Opts) {
...
-                                     isMain(), hasName("swap")),
-                               unless(isExplicitThrow())),
-                         isEnabled(FunctionsThatShouldNotThrow)))
+      functionDecl(
+          isDefinition(),
+          anyOf(isNoThrow(),
+                allOf(anyOf(cxxDestructorDecl(),
+                            cxxConstructorDecl(isMoveConstructor()),
+                            cxxMethodDecl(isMoveAssignmentOperator()), isMain(),
+                            hasAnyName("swap", "iter_swap", "iter_move")),
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/bugprone/ExceptionEscapeCheck.cpp:67]: NOTE: Here is old legacy bug. For example user can have method swap(), and it will still be counted in even if not needed. Would be good to check if those methods/functions got at least 1 parameter.
Also you can consider updating performance-noexcept-swap by adding there iter_swap.

**Review by PiotrZSL — APPROVED** [review]
LGTM. 
Looks fine even in current stage.

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/exception-escape.cpp (hunk 1 above)
Comment (Da-Viper) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/exception-escape.cpp:594]: Yeah the std:: common_iterator::iter_move

But the check checks only if the function name is iter_move then performs the check.

If you do prefer I could change it to only one arg

Comment (PiotrZSL) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/exception-escape.cpp:594]: One argument would be better. Just to keep it in sync with standard.
But thats not a blocker.

**Review by PiotrZSL — APPROVED** [review]
