### PR TITLE
[libc][sys/wait][linux] add missing and clean up existing macros

### LINKED ISSUE #124944: [libc][POSIX] provide WIFSIGNALED from <sys/wait.h>
building llvm with llvm-libc fails with:
```
/llvm-project-main/llvm/lib/Support/Unix/Program.inc:497:14: error: use of undeclared identifier 'WIFSIGNALED'
```
we're missing this macro from POSIX

### PR DESCRIPTION
**Pull request by nickdesaulniers**
This patch does a few things:
- replace macro definitions with an inclusion of the linux/wait.h kernel
  header.
  - WNOHANG
  - WUNTRACED
  - WEXITED
  - WCONTINUED
  - WSTOPPED
  - P_ALL
  - P_PID
  - P_PGID
  - P_PIDFD
- Add missing macro definitions mandated by POSIX. Some are needed to build
  LLVM.
  - WCOREDUMP
  - WIFCONTINUED
  - WIFSIGNALELD
  - WIFSTOPPED
  - WSTOPSIG
- Remove glibc style __W* macros.  Users should stick with the POSIX macros. We
  can re-add them if necessary.
  - __WEXITSTATUS
  - __WTERMSIG
  - __WIFEXITED
  - __WIFSIGNALED
  - __WIFSTOPPED
  - __WIFCONTINUED
  - __WCOREDUMP
  - __W_EXITCODE
  - __W_STOPCODE
  - __W_CONTINUED
  - __WCOREFLAG

Fixes: #124944

### CODE REVIEW

File: libc/include/llvm-libc-macros/linux/sys-wait-macros.h [hunk 1]
```diff
@@ -9,36 +9,19 @@
...
+#define WIFCONTINUED(status) ((status) == 0xffff)
+#define WIFEXITED(status) (WTERMSIG(status) == 0)
+#define WIFSIGNALED(status) ((WTERMSIG(status) + 1) >= 2)
+#define WIFSTOPPED(status) (WTERMSIG(status) == 0x7f)
+#define WSTOPSIG(status) WEXITSTATUS(status)
+#define WTERMSIG(status) ((status) & 0x7f)
+
+#define WCOREFLAG 0x80
+#define W_EXITCODE(ret, sig) ((ret) << 8 | (sig))
+#define W_STOPCODE(sig) ((sig) << 8 | 0x7f)
```
Comment (nickdesaulniers) [inline libc/include/llvm-libc-macros/linux/sys-wait-macros.h:25]: These three aren't specified by POSIX. Are they glibc extensions? Perhaps doesn't matter for this PR, but I did choose to retain them in case they're in widespread use.

Comment (nickdesaulniers) [reply libc/include/llvm-libc-macros/linux/sys-wait-macros.h:25]: Ah, thanks for the context.  Maybe ACSRG can standardize them at some point. Will leave them for now.

**Comment by nickdesaulniers** [comment]
ping for review

**Comment by enh-google** [comment]
(seemed plausible to me, but i'm assuming you want an llvm-libc committer's review...)

**Review by lntue — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
> (seemed plausible to me, but i'm assuming you want an llvm-libc committer's review...)

I want _you_ to be an llvm-libc _committer_ **and** _reviewer_ :wink: .  If you expect me to be for bionic, than it's only reciprocal.

**Comment by nickdesaulniers** [comment]
ack, looking:
```
In file included from /home/libcrv32buildbot/bbroot/libc-riscv32-qemu-yocto-fullbuild-dbg/llvm-project/libc/src/sys/wait/linux/waitpid.cpp:13:
/home/libcrv32buildbot/bbroot/libc-riscv32-qemu-yocto-fullbuild-dbg/llvm-project/libc/src/sys/wait/wait4Impl.h:68:22: error: use of undeclared identifier '__W_CONTINUED'
   68 |       *wait_status = __W_CONTINUED;
      |                      ^
```
