### PR TITLE
[Clang][CodeGen] Add __builtin_bcopy

### LINKED ISSUE #51409: Failure to compile __builtin_bcopy
|  |  |
| --- | --- |
| Bugzilla Link | [52067](https://llvm.org/bz52067) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon,@zygoloid,@rotateright |

## Extended Description 
#include <stddef.h>

void f(const void *s, void *d, size_t n)
{
    __builtin_bcopy((void *)s, d, n);
}

Trying to compile this with Clang results in this error:

<source>:5:5: error: cannot compile this builtin function yet
    __builtin_bcopy((void *)s, d, n);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I would assume implementing this is as simple as having it do `__builtin_memmove(d, s, n)`, so it seems odd that this isn't implemented

### LINKED ISSUE #63065: [clang] Wrong optimization when -D_FORTIFY_SOURCE is passed
When compiling a program that calls `bcopy`, clang replaces it by a `memmove` call (as per `llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp`). This is not taking into account that it should generate a `__memmove_chk` when any level of `-D_FORTIFY_SOURCE` is passed to the compiler.

I think the issue is caused by the fact that this `bcopy` to `memmove` conversion should be done somewhere else in the code (probably in `SemaChecking.cpp`).

This issue was seen while building the glibc testsuite (`debug/tst-fortify*.c`), in our work to add llvm/clang support for it upstream.  GCC builds these tests correctly.

To reproduce:

The branch can be accessed [here](https://github.com/zatrazz/glibc/tree/azanella/clang).

Configure glibc with:

```shell
AR="${PATH_TO_LLVM}/llvm-ar" \
AS="${PATH_TO_LLVM}/llvm-as" \
NM="${PATH_TO_LLVM}/llvm-nm" \
OBJDUMP="${PATH_TO_LLVM}/llvm-objdump" \
OBJCOPY="${PATH_TO_LLVM}/llvm-objcopy" \
RANLIB="${PATH_TO_LLVM}/llvm-ranlib" \
READELF="${PATH_TO_LLVM}/llvm-readelf" \
STRIP="${PATH_TO_LLVM}/llvm-strip" \
CC="${PATH_TO_LLVM}/clang -target ${arch}-linux-gnu -fuse-ld=lld -Wno-unused-command-line-argument" \
CXX="${PATH_TO_LLVM}/clang++ -target ${arch}-linux-gnu -fuse-ld=lld -Wno-unused-command-line-argument" \
LD="${PATH_TO_LLVM}/ld.lld" \
CFLAGS="-O2 -g" \
CXXFLAGS="${CFLAGS}" \
${GLIBCSRC}/configure \
            --prefix=/usr \
            --host=${arch}-linux-gnu \
            --with-binutils="${PATH_TO_LLVM}" \
            --enable-stack-protector=all \
            --enable-tunables=yes \
            --enable-bind-now=yes \
            --enable-profile=no
```

then `make` and `make check`

Failures will be inside the `debug` directory. Screen output is in `tst-fortify-cc-default-*.out` and binaries will be in `tst-fortify-cc-default-*o`.

### PR DESCRIPTION
**Pull request by ceseo**
Add __builtin_bcopy to the list of GNU builtins. This was causing a series of test failures in glibc.

Adjust the tests to reflect the changes in codegen.

Fixes #51409.
Fixes #63065.

### CODE REVIEW

File: clang/lib/CodeGen/CGBuiltin.cpp [hunk 1]
```diff
@@ -3703,6 +3703,20 @@ RValue CodeGenFunction::EmitBuiltinExpr(const GlobalDecl GD, unsigned BuiltinID,
     Builder.CreateMemSet(Dest, Builder.getInt8(0), SizeVal, false);
     return RValue::get(nullptr);
   }
+
+  case Builtin::BIbcopy:
```
Comment (jroelofs) [inline clang/lib/CodeGen/CGBuiltin.cpp:3707]: Is this the same as the body of `case Builtin::BImemmove:`?

Comment (jroelofs) [reply clang/lib/CodeGen/CGBuiltin.cpp:3707]: never mind, it can't be: src/dest vs dest/src

**Review by jroelofs — APPROVED** [review]
LGTM
