### PR TITLE
[clang][AST] fix ast-print of `extern <lang>` with >=2 declarators

### LINKED ISSUE #93085: -ast-print of an extern-C declaration skips closing semi-colon
https://godbolt.org/z/c1K3nMj6f

Given:
```
extern "C" int printf(const char *, ...);

template<typename T> void foo(T val) {
  printf("%d\n", val);
}

int main() {
  foo(10);
}
```

`-Xclang -ast-print` results in:

```
extern "C" int printf(const char *, ...)
template <typename T> void foo(T val) {
    printf("%d\n", val);
}
template<> void foo<int>(int val) {
    printf("%d\n", val);
}
int main() {
    foo(10);
}
```

Notice the missing semi-colon after the 'printf' declaration.  This comes back if `extern "C"` is not there.

### PR DESCRIPTION
**Pull request by temyurchenko**
Problem: the printer used to ignore all but the first declarator for unbraced language linkage declarators. Furthemore, that one would be printed without the final semicolon.

Solution: when there is more than one declarator, we print them in a braced `extern <lang>` block. If the original declaration was unbraced and there is one or less declarator, we omit the braces, but add the semicolon.

**N.B.** We are printing braces which were, in some cases, absent from the original CST. If that's an issue, I'll work on it. See the tests for the examples.

### CODE REVIEW

**Comment by temyurchenko** [comment]
Fixes #93085

File: clang/test/AST/ast-print-language-linkage.cpp [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// RUN: %clang_cc1 -ast-print %s -o - | FileCheck %s
+
+// CHECK: extern "C" int printf(const char *, ...);
+extern "C" int printf(const char *...);
+
+// CHECK: extern "C++" {
```
Comment (erichkeane) [inline clang/test/AST/ast-print-language-linkage.cpp:6]: @AaronBallman : What do we think of this?  This isn't a true representation of the original code, but I'm not sure what work we have to ensure this is done with commas?

File: clang/lib/AST/DeclPrinter.cpp [hunk 2]
```diff
@@ -1145,13 +1145,15 @@ void DeclPrinter::VisitLinkageSpecDecl(LinkageSpecDecl *D) {
     l = "C++";
   }
 
+  bool HasMoreThanOneDecl =
+      *D->decls_begin() && D->decls_begin()->getNextDeclInContext();
```
Comment (erichkeane) [inline clang/lib/AST/DeclPrinter.cpp:1149]:
```suggestion
      !D->decls().empty() && (++D->decls_begin() ) != D->decls_end()`
```
WDYT?

File: clang/test/AST/ast-print-language-linkage.cpp [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+extern "C++" int f(int), g(int);
+
+// CHECK: extern "C" {
+// CHECK-NEXT:  void foo();
+// CHECK-NEXT:  int x;
+// CHECK-NEXT:  int y;
+// CHECK-NEXT: }
+extern "C" {
+  void foo(void);
+  int x, y;
```
Comment (erichkeane) [inline clang/test/AST/ast-print-language-linkage.cpp:19]: This part in particular is unfortunate.  What do we look like in non-linkage specs?

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 1 above)
Comment (temyurchenko) [reply clang/test/AST/ast-print-language-linkage.cpp:6]: Unfortunately, I'm not aware of the design goals of `DeclPrinter`. How accurately is it trying to represent the original code? Because AST's are naturally a lossy projection of CST's, so there is always going to be a difference to the original. How much of that difference is admissible?

I can try to work around that by querying `VarDecl::isInExternCContext`/`isInExternCXXContext` inside of `VarDecl`, but my initial naive implementation didn't have the desired result.

File: clang/lib/AST/DeclPrinter.cpp (hunk 2 above)
Comment (temyurchenko) [reply clang/lib/AST/DeclPrinter.cpp:1149]: Sure!

For my own education though, I'd like to know the reasoning, just to be able to make the right decision in future situations.

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 3 above)
Comment (temyurchenko) [reply clang/test/AST/ast-print-language-linkage.cpp:19]: If you mean the splitting of `int x, y` into `int x; int y`, that's actually the «default». The declarators are split into different declarations whenever it's possible. So, the splitting doesn't happen only when there is a definition of a tagged type within the declaration, I believe. So, for example:

`union {} a, b;` → `union {\n} a, b;`

but

`int a, b;` → `int a; int b;`


That fact, that this very splitting already occurs in DeclPrinter and leads to the deviation from the original source, was the reason why I felt more comfortable to go forward with adding braces.

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 1 above)
Comment (erichkeane) [reply clang/test/AST/ast-print-language-linkage.cpp:6]: We don't really have much guarantees besides 'best effort', so I am querying Aaron to see if this is 'good enough'.  Just `VarDecl` isn't going to be sufficient (probably something in `DeclStmt` handling?) because we can have any sorts of declarations this way.

File: clang/lib/AST/DeclPrinter.cpp (hunk 2 above)
Comment (erichkeane) [reply clang/lib/AST/DeclPrinter.cpp:1149]: It just seems a bit more readable to me.  We're checking if the length of the decls is > 1, so it seemed more clear?

Though, as this isn't performance critical code, perhaps: 
`bool HasMoreThanOneDecl = std::distance(D->decls_begin(), D->decls_end()) > 1` is much more readable.

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 3 above)
Comment (erichkeane) [reply clang/test/AST/ast-print-language-linkage.cpp:19]: I see, yeah, I think this is fine then.  Same with the functions, but I'll give Aaron a chance to comment.

File: clang/lib/AST/DeclPrinter.cpp (hunk 2 above)
Comment (temyurchenko) [reply clang/lib/AST/DeclPrinter.cpp:1149]: Got it!

**Review by AaronBallman — COMMENTED** [review]
I think we're going to be printing incorrect code either way, but with this patch, we're more likely to be closer to the original intent of the code than without the patch. So even though this isn't perfect, it's forward progress and I think we're fine to land it as-is. However, if we can fix it correctly, that would be preferred.

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 1 above)
Comment (temyurchenko) [reply clang/test/AST/ast-print-language-linkage.cpp:6]: > Oofda, there are differences between the braced and non-braced versions, so ideally, we want to reproduce exactly what was in the user's source to avoid accidentally changing the meaning of code

You are completely right, my bad. I'll work on fixing this. 

> z, y, and z are external, a, b, and c are not: https://godbolt.org/z/evG9KPKMM

I believe, they all have external linkage. However, x, y and z are also definitions, while a, b, and c are just declarations. So, for example, you can reference `x` from another translation unit and the value will be `0`.

Comment (temyurchenko) [reply clang/test/AST/ast-print-language-linkage.cpp:6]: > ideally, we want to reproduce exactly what was in the user's source to avoid accidentally changing the meaning of code

Do you know why we split declarators from the same declaration into several declarations, whenever possible? Judging by the comments in `DeclPrinter::visitDeclContext` it seems intentional and desired.

Comment (temyurchenko) [reply clang/test/AST/ast-print-language-linkage.cpp]: Hopefully, the new implementation has fixed the issue.

File: clang/test/AST/ast-print-language-linkage.cpp (hunk 3 above)
Comment (erichkeane) [reply clang/test/AST/ast-print-language-linkage.cpp:22]: I like the new version.  Not quite perfect fidelity, but at least matches what is going on.

**Review by erichkeane — APPROVED** [review]
I'm in favor, let aaron take a look, else LGTM!

File: clang/lib/AST/DeclPrinter.cpp [hunk 4]
```diff
@@ -662,6 +678,11 @@ void DeclPrinter::VisitFunctionDecl(FunctionDecl *D) {
   CXXConversionDecl *ConversionDecl = dyn_cast<CXXConversionDecl>(D);
   CXXDeductionGuideDecl *GuideDecl = dyn_cast<CXXDeductionGuideDecl>(D);
   if (!Policy.SuppressSpecifiers) {
+    if (const char *lang = tryGetUnbracedLinkageLanguage(D)) {
+      // the "extern" specifier is implicit
+      assert(D->getStorageClass() == SC_None);
+      Out << "extern \"" << lang << "\" ";
+    }
```
Comment (AaronBallman) [inline clang/lib/AST/DeclPrinter.cpp:685]:
```suggestion
    if (const char *Lang = tryGetUnbracedLinkageLanguage(D)) {
      // the "extern" specifier is implicit
      assert(D->getStorageClass() == SC_None);
      Out << "extern \"" << Lang << "\" ";
    }
```

File: clang/lib/AST/DeclPrinter.cpp [hunk 5]
```diff
@@ -932,6 +953,11 @@ void DeclPrinter::VisitVarDecl(VarDecl *D) {
     : D->getASTContext().getUnqualifiedObjCPointerType(D->getType());
 
   if (!Policy.SuppressSpecifiers) {
+    if (const char *lang = tryGetUnbracedLinkageLanguage(D)) {
+      // the "extern" specifier is implicit
+      assert(D->getStorageClass() == SC_None);
+      Out << "extern \"" << lang << "\" ";
+    }
```
Comment (AaronBallman) [inline clang/lib/AST/DeclPrinter.cpp:960]:
```suggestion
    if (const char *Lang = tryGetUnbracedLinkageLanguage(D)) {
      // the "extern" specifier is implicit
      assert(D->getStorageClass() == SC_None);
      Out << "extern \"" << Lang << "\" ";
    }
```

File: clang/lib/AST/DeclPrinter.cpp [hunk 6]
```diff
@@ -1064,6 +1090,8 @@ void DeclPrinter::VisitNamespaceAliasDecl(NamespaceAliasDecl *D) {
 
 void DeclPrinter::VisitEmptyDecl(EmptyDecl *D) {
   prettyPrintAttributes(D);
+  if (const char *lang = tryGetUnbracedLinkageLanguage(D))
+    Out << "extern \"" << lang << "\";";
```
Comment (AaronBallman) [inline clang/lib/AST/DeclPrinter.cpp:1094]:
```suggestion
  if (const char *Lang = tryGetUnbracedLinkageLanguage(D))
    Out << "extern \"" << Lang << "\";";
```

**Review by AaronBallman — APPROVED** [review]
LGTM aside from some coding style nits. Because AST printing is not part of the public interface for Clang, I don't think these changes need a release note.

File: clang/lib/AST/DeclPrinter.cpp (hunk 4 above)
Comment (temyurchenko) [reply clang/lib/AST/DeclPrinter.cpp]: fixed

**Comment by temyurchenko** [comment]
What should be the next step following the approvals?

**Comment by erichkeane** [comment]
> What should be the next step following the approvals?

If you do not have 'squash and merge' rights here, one of us can do it for you once testing completes.

**Comment by temyurchenko** [comment]
> > What should be the next step following the approvals?
> 
> If you do not have 'squash and merge' rights here, one of us can do it for you once testing completes.

I don't have them, would be glad if you could do that!

**Comment by gulfemsavrun** [comment]
We started seeing an lldb test failure, and I bisected to this commit:
```
--
Command Output (stderr):
--
FAIL: LLDB (/b/s/w/ir/x/w/llvm_build/bin/clang-x86_64) :: test_completions (TestDAP_completions.TestDAP_completions.test_completions)
FAIL: LLDB (/b/s/w/ir/x/w/llvm_build/bin/clang-x86_64) :: test_completions (TestDAP_completions.TestDAP_completions.test_completions)
======================================================================
ERROR: test_completions (TestDAP_completions.TestDAP_completions.test_completions)
   Tests the completion request at different breakpoints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 150, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/tools/lldb-dap/completions/TestDAP_completions.py", line 89, in test_completions
    self.dap_server.get_completions("`log enable  "),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 448, in get_completions
    response = self.request_completions(text, frameId)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 979, in request_completions
    return self.send_recv(command_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 324, in send_recv
    raise ValueError(desc)
ValueError: no response for "completions"
Config=x86_64-/b/s/w/ir/x/w/llvm_build/bin/clang
======================================================================
ERROR: test_completions (TestDAP_completions.TestDAP_completions.test_completions)
   Tests the completion request at different breakpoints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2017, in tearDown
    Base.tearDown(self)
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1103, in tearDown
    hook()  # try the plain call and hope it works
    ^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/lldbdap_testcase.py", line 375, in cleanup
    self.dap_server.request_disconnect(terminateDebuggee=True)
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 666, in request_disconnect
    return self.send_recv(command_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 318, in send_recv
    self.send_packet(command)
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 273, in send_packet
    self.send.flush()
BrokenPipeError: [Errno 32] Broken pipe
Config=x86_64-/b/s/w/ir/x/w/llvm_build/bin/clang
----------------------------------------------------------------------
Ran 1 test in 1.600s

FAILED (errors=2)

--
```
https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8746482644341901905/+/u/lldb/test/stdout

**Comment by temyurchenko** [comment]
> We started seeing an lldb test failure, and I bisected to this commit:

I see the source of the bug, I'm thinking how to address it best. If it's urgent, I can produce an urgent fix.

**Comment by gulfemsavrun** [comment]
> > We started seeing an lldb test failure, and I bisected to this commit:
> 
> I see the source of the issue, I'm thinking how to address it best. If it's urgent, I can produce an urgent fix.

Can you please revert it in the meantime because it is breaking our builders? Instead of a quick fix, I recommend a revert and a reland with a fix. I can help you to verify whether it actually fixes the issue in our builders.

**Comment by gulfemsavrun** [comment]
> Unfortunately, I don't have the right to revert.

No worries, and I reverted for you. When you have the fix ready, I'm happy to verify it on our builders before you reland.

**Comment by temyurchenko** [comment]
> No worries, and I reverted it for you. When you have the fix ready, I'm happy to verify it on our builders before you reland.

Can you also reopen this PR, please? For documentation/history reasons, it's probably better to provide a fix within the scope of this PR.

**Comment by erichkeane** [comment]
> > No worries, and I reverted it for you. When you have the fix ready, I'm happy to verify it on our builders before you reland.
> 
> Can you also reopen this PR, please? For documentation/history reasons, it's probably better to provide a fix within the scope of this PR.

I don't think our github is configured to allow that.  You'll have to start a new PR.
