### PR TITLE
[Flang][OpenMP] fix crash on sematic error  in atomic capture clause

### LINKED ISSUE #139884: [Flang][OpenMP] crash on invalid atomic capture
Reproducer:
https://godbolt.org/z/ahqjKx3EE
```f90
logical x
complex y, z
!$omp atomic capture
x = y
z = y + x
!$omp end atomic
end
```

### PR DESCRIPTION
**Pull request by Mxfg-incense**
Fix a crash caused by an invalid expression in the atomic capture clause, due to the `checkForSymbolMatch` function not accounting for `GetExpr` potentially returning null.

Fix https://github.com/llvm/llvm-project/issues/139884

### CODE REVIEW

**Comment by Mxfg-incense** [comment]
@harishch4 @kiranchandramohan A  patch on semantic checks for the atomic capture clause.

**Review by tblah — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by Mxfg-incense** [comment]
@tblah I don't have merge permissions. Could you help me merge it?

File: flang/test/Semantics/OpenMP/atomic-capture-invalid.f90 [hunk 1]
```diff
@@ -0,0 +1,22 @@
+! REQUIRES: openmp_runtime
+
+! RUN: %python %S/../test_errors.py %s %flang_fc1 %openmp_flags
+! Semantic checks on invalid atomic capture clause
+
+use omp_lib
```
Comment (kparzysz) [inline flang/test/Semantics/OpenMP/atomic-capture-invalid.f90:6]: FYI, "omp_lib" is not needed for anything in this example.
