### PR TITLE
[clang-format] Change BracedInitializerIndentWidth to int

### LINKED ISSUE #108526: clang-format: `BracedInitializerIndentWidth` in parent config is ignored when using `BasedOnStyle: InheritParentConfig`
### Version

clang-format version 18.1.8

### How to reproduce

./.clang-format:

```
---
BracedInitializerIndentWidth: 2
```

./foo/.clang-format:

```
---
BasedOnStyle: InheritParentConfig
```

Run `clang-format --dump-config | grep BracedInitializerIndentWidth`, output is empty.

**When moving `BracedInitializerIndentWidth: 2` to ./foo/.clang-format:**

./.clang-format:

```
---
Language: Cpp  # An empty file does not work
```

./foo/.clang-format:

```
---
BasedOnStyle: InheritParentConfig
BracedInitializerIndentWidth: 2
```

Run `clang-format --dump-config | grep BracedInitializerIndentWidth`, now output is:

```
BracedInitializerIndentWidth: 2
```

### Hypothesis

According to https://clang.llvm.org/docs/ClangFormatStyleOptions.html#bracedinitializerindentwidth, `BracedInitializerIndentWidth` will fall back to `ContinuationIndentWidth` if it is not explicitly set. This behavior takes precedence over falling back to the parent configuration, effectively ignoring the `BracedInitializerIndentWidth` specified in the parent configuration.

I am not sure how to verify this hypothesis.

### PR DESCRIPTION
**Pull request by owenca**
Fixes #108526

### CODE REVIEW

File: clang/unittests/Format/ConfigParseTest.cpp [hunk 1]
```diff
@@ -1441,8 +1441,9 @@ TEST(ConfigParseTest, GetStyleOfFile) {
   ASSERT_EQ(*Style9, SubSubStyle);
 
   // Test 9.8: use inheritance from a file without BasedOnStyle
-  ASSERT_TRUE(FS.addFile("/e/withoutbase/.clang-format", 0,
-                         llvm::MemoryBuffer::getMemBuffer("ColumnLimit: 123")));
+  ASSERT_TRUE(FS.addFile(
+      "/e/withoutbase/.clang-format", 0,
+      llvm::MemoryBuffer::getMemBuffer("BracedInitializerIndentWidth: 2")));
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/ConfigParseTest.cpp:1446]: I'd add it, not replace the old value.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/unittests/Format/ConfigParseTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/ConfigParseTest.cpp]: It doesn't matter which option to use as it's testing that an option from the parent config gets inherited, but a little redundancy wouldn't hurt here.
