### PR TITLE
[libc][stdfix] Implement fixed point bitsfx functions in llvm libc

### LINKED ISSUE #113359: Implement fixed point bitsfx functions in llvm-libc
Some fixed point functions from ISO 18037 are implemented in llvm-libc, but not all of them are implemented. The various bits`fx`  functions should also be added. Copying from the extension:

```
4.1.7.4 The bitwise fixed-point to integer conversion functions

The bitwise fixed-point to integer conversion functions bitsfx, where fx stands for one of hr, r, lr, hk, k, lk, uhr, ur, ulr, uhk, uk or ulk, take one fixed-point type argument (corresponding to fx); the type of the function is an implementation-defined integer type int_fx_t (for signed fixed-point types) or uint_fx_t (for unsigned fixed-point types), defined in the <stdfix.h> headerfile, that is large enough to hold all the bits in the fixed-point type.

The bitwise fixed-point to integer conversion functions return an integer value equal to the fixedpoint value of the argument multiplied by 2^F, where F is the number of fractional bits in the fixed point type. The result type is an integer type big enough to hold all valid result values for the given fixed-point argument type. For example, if the fract type has 15 fractional bits, then after the declaration

  fract a = 0.5;

the value of bitsr(a) is 0.5 * 2^15 = 0x4000.
```

These can first be implemented as `__builtin_*` functions in clang then llvm-libc can provide the wrappers for each of the builtin functions.

### PR DESCRIPTION
**Pull request by krishna2803**
Fixes #113359

### CODE REVIEW

**Comment by krishna2803** [comment]
@PiJoules @lntue @nickdesaulniers 

Tests for `int_hr_t` (`short fract`) don't seem to work as it's just a `typedef` for `signed char`, and we don't have defined tests for that (and also `signed char` != `char`), I’ve excluded the tests for this type from `libc/test/CMakeLists.txt` for now. Apart from that, I built on the implementations of the already existing `fxbits` and `countlsfx` functions for this patch.

A side note: I noticed that the documentation for the fxbits functions is not updated in libc/docs/headers/math/stdfix.rst, even though we have an implementation for those. This also means that the "checks" are missing from the [llvm website](https://libc.llvm.org/headers/math/stdfix.html).

File: libc/test/src/stdfix/BitsFxTest.h [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    EXPECT_EQ(static_cast<XType>(1), func(eps));
+
+    // (0.6875)_10 = (0.1011)_2
+    EXPECT_EQ(static_cast<XType>(11ULL << (FXRep::FRACTION_LEN - 4)),
+              func(0.6875));
+
+    EXPECT_EQ(
+        static_cast<XType>(zero_point_forty_two >> (64 - FXRep::FRACTION_LEN)),
+        func(0.42));
+  }
```
Comment (PiJoules) [inline libc/test/src/stdfix/BitsFxTest.h:48]: Note that if the value cannot precisely fit in the fixed point type, rounding up or down is implementation-defined. I think this check assumes we always round down. Perhaps for numbers that don't precisely fit in a fixed point type, we should check the numbers both above and below the true value.

For example, for 0.42 as a `short fract` which has 7 fractional bits for this implementation, we check the result of `bitshr` is 53 or 54.

**Comment by PiJoules** [comment]
> Tests for `int_hr_t` (`short fract`) don't seem to work as it's just a `typedef` for `signed char`, and we don't have defined tests for that (and also `signed char` != `char`), I’ve excluded the tests for this type from `libc/test/CMakeLists.txt` for now. Apart from that, I built on the implementations of the already existing `fxbits` and `countlsfx` functions for this patch.

What's the failure you're seeing for `short fract`?

**Comment by krishna2803** [comment]
```
FAILED: libc/test/src/stdfix/libc.test.src.stdfix.bitshr_test.__unit__.__build__ 
: && /home/krishna/OpenSource/llvm-project/build/bin/clang++ --target=x86_64-unknown-linux-gnu -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -fuse-ld=lld -Wl,--color-diagnostics    -fpie -ffixed-point -Wimplicit-fallthrough -Wwrite-strings -Wno-c99-extensions -Wno-gnu-imaginary-constant -Wno-pedantic -Wstrict-prototypes -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wthread-safety -Xlinker --dependency-file=libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/link.d libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o -o libc/test/src/stdfix/libc.test.src.stdfix.bitshr_test.__unit__.__build__  libc/src/stdfix/CMakeFiles/libc.src.stdfix.bitshr.__internal__.dir/./bitshr.cpp.o  libc/src/errno/CMakeFiles/libc.src.errno.errno.__internal__.dir/./libc_errno.cpp.o  libc/src/__support/StringUtil/CMakeFiles/libc.src.__support.StringUtil.error_to_string.dir/./error_to_string.cpp.o  libc/src/__support/OSUtil/linux/CMakeFiles/libc.src.__support.OSUtil.linux.linux_util.dir/./exit.cpp.o  libc/src/__support/OSUtil/linux/CMakeFiles/libc.src.__support.OSUtil.linux.linux_util.dir/./fcntl.cpp.o  libc/test/UnitTest/libLibcDeathTestExecutors.unit.a  libc/test/UnitTest/libLibcTest.unit.a && :
ld.lld: error: undefined hidden symbol: bool __llvm_libc_21_0_0_git::testing::internal::test<signed char>(__llvm_libc_21_0_0_git::testing::internal::RunContext*, __llvm_libc_21_0_0_git::testing::TestCond, signed char, signed char, char const*, char const*, __llvm_libc_21_0_0_git::testing::internal::Location)
>>> referenced by bitshr_test.cpp
>>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
>>> referenced by bitshr_test.cpp
>>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
>>> referenced by bitshr_test.cpp
>>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
>>> referenced 3 more times
>>> did you mean: bool __llvm_libc_21_0_0_git::testing::internal::test<bool>(__llvm_libc_21_0_0_git::testing::internal::RunContext*, __llvm_libc_21_0_0_git::testing::TestCond, bool, bool, char const*, char const*, __llvm_libc_21_0_0_git::testing::internal::Location)
>>> defined in: libc/test/UnitTest/libLibcTest.unit.a(LibcTest.cpp.o)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

this is the exact failure for `int_hr_t` (`short fract`)

File: libc/test/src/stdfix/BitsFxTest.h [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  static constexpr T max = FXRep::MAX();
+  static constexpr T min = FXRep::MIN();
+  static constexpr T one_half = FXRep::ONE_HALF();
+  static constexpr T one_fourth = FXRep::ONE_FOURTH();
+  static constexpr T eps = FXRep::EPS();
+
+  // (0.42)_10 =
+  // (0.0110101110000101000111101011100001010001111010111000010100011110)_2 =
+  // (0.0x6b851eb851eb851e)_16
+  static constexpr unsigned long long zero_point_forty_two =
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/test/src/stdfix/BitsFxTest.h:27]: in an attempt to test for `10.72` (just as an example), i tried:

```cpp
// (10.72)_10 =
// (1010.101110000101000111101011100001010001111010111000010100011110)_2 =
// (a.b851eb851eb851e)_16
static constexpr unsigned long long ten_point_seven_two = 0xab851eb851eb851eULL;

static constexpr T ten_point_seven_two_t = 10.72;

if constexpr (FXRep::INTEGRAL_LEN > 0)
  EXPECT_EQ(
    static_cast<XType>(ten_point_seven_two >> (64 - (FXRep::VALUE_LEN))),
    func(ten_point_seven_two_t)
  );
```

where `FXRep::VALUE_LEN` is just `FXRep::INTEGRAL_LEN + FXRep::FRACTION_LEN`. When I traced the definition for `FXRep::INTEGRAL_LEN`, I found them to be different than the spec for example for `short accum` the spec suggests `s4.7` ([ref, pg11](https://standards.iso.org/ittf/PubliclyAvailableStandards/c051126_ISO_IEC_TR_18037_2008.zip)) while the `FXRep::INTEGRAL_LEN` is `8` for `short fract` defined here:

https://github.com/llvm/llvm-project/blob/dff2ca424c20c672b418ec86ac3a120fad4fb364/libc/include/llvm-libc-macros/stdfix-macros.h#L164-L168

so the above test fails.

---

but when i do:
```cpp
// (10.72)_10 =
// (1010.101110000101000111101011100001010001111010111000010100011110)_2 =
// (a.b851eb851eb851e)_16
static constexpr unsigned long long ten_point_seven_two = 0xab851eb851eb851eULL;

static constexpr T ten_point_seven_two_t = 10.72;

if constexpr (FXRep::INTEGRAL_LEN > 0)
  EXPECT_EQ(
    // just hardcoded 4 here in place of INTEGRAL_LEN
    static_cast<XType>(ten_point_seven_two >> (64 - (FXRep::FRACTION_LEN + 4))),
    func(ten_point_seven_two_t)
  );
```

the test passes! could you please provide some guidance on how to handle this?

[the remark this answers is not in the document]
Comment (PiJoules) [reply libc/test/src/stdfix/BitsFxTest.h:27]: > in an attempt to test for `10.72` (just as an example), i tried:
> 
> ```c++
> // (10.72)_10 =
> // (1010.101110000101000111101011100001010001111010111000010100011110)_2 =
> // (a.b851eb851eb851e)_16
> static constexpr unsigned long long ten_point_seven_two = 0xab851eb851eb851eULL;
> 
> static constexpr T ten_point_seven_two_t = 10.72;
> 
> if constexpr (FXRep::INTEGRAL_LEN > 0)
>   EXPECT_EQ(
>     static_cast<XType>(ten_point_seven_two >> (64 - (FXRep::VALUE_LEN))),
>     func(ten_point_seven_two_t)
>   );
> ```
> 
> where `FXRep::VALUE_LEN` is just `FXRep::INTEGRAL_LEN + FXRep::FRACTION_LEN`. When I traced the definition for `FXRep::INTEGRAL_LEN`, I found them to be different than the spec for example for `short accum` the spec suggests `s4.7` ([ref, pg11](https://standards.iso.org/ittf/PubliclyAvailableStandards/c051126_ISO_IEC_TR_18037_2008.zip)) while the `FXRep::INTEGRAL_LEN` is `8` for `short fract` defined here:
> 
> https://github.com/llvm/llvm-project/blob/dff2ca424c20c672b418ec86ac3a120fad4fb364/libc/include/llvm-libc-macros/stdfix-macros.h#L164-L168
> 
> so the above test fails.

That section is for the minimal formats of each type. Any implementation can have different integral and fractional bits as long as they meet those minimum formats. There's other possible formats in `A.3 Possible Data Type Implementations`. Clang's default formats are the `typical desktop processor` formats but we shouldn't assume those will always be the formats.

> but when i do:
> 
> ```c++
> // (10.72)_10 =
> // (1010.101110000101000111101011100001010001111010111000010100011110)_2 =
> // (a.b851eb851eb851e)_16
> static constexpr unsigned long long ten_point_seven_two = 0xab851eb851eb851eULL;
> 
> static constexpr T ten_point_seven_two_t = 10.72;
> 
> if constexpr (FXRep::INTEGRAL_LEN > 0)
>   EXPECT_EQ(
>     // just hardcoded 4 here in place of INTEGRAL_LEN
>     static_cast<XType>(ten_point_seven_two >> (64 - (FXRep::FRACTION_LEN + 4))),
>     func(ten_point_seven_two_t)
>   );
> ```
> 
> the test passes! could you please provide some guidance on how to handle this?

Hmmm so 10.72 can't precisely fit in a fixed point number, so the actual fixed point value will be either rounded up or down to the nearest fixed point value within 1 ULP. This means for something like 10.72 as a `short accum` with 7 fractional bits, it's actual value will be either 10.71875 or 10.7265625. If we test against `T ten_point_seven_two_t = 10.72` then we'd actually be testing against one of these 2 values. I think perhaps it would instead be better to test precise values that fit into the fixed point type rather than guessing the rounding here. That is, for a `short accum` use either 10.7265625 or 10.71875 rather than 10.72 directly.

Rather than using a hardcoded hex and shifting from a more precise number, I think maybe it would be easier if we tested against known values. That is, for a `short accum` with a value of 10.71875 and 7 fractional bits, we explicitly expect 1372.

File: libc/test/src/stdfix/BitsFxTest.h (hunk 1 above)
Comment (PiJoules) [reply libc/test/src/stdfix/BitsFxTest.h:48]: Actually disregard this comment, the rounding I mentioned will happen when 0.42 is passed as the argument, so the argument will have one of 2 values but the result of `func` could then have more than 2 possible return values. So I think rather than using values that don't fit precisely in a fixed point type, we should use precise values that do. So rather than 0.42, maybe use one of the fixed point values that is within 1 ULP of that value for that type. For example, for a `short accum` with 7 fractional bits, this would instead be either 0.421875 or 0.4140625.

**Comment by lntue** [comment]
> ```
> FAILED: libc/test/src/stdfix/libc.test.src.stdfix.bitshr_test.__unit__.__build__ 
> : && /home/krishna/OpenSource/llvm-project/build/bin/clang++ --target=x86_64-unknown-linux-gnu -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -fuse-ld=lld -Wl,--color-diagnostics    -fpie -ffixed-point -Wimplicit-fallthrough -Wwrite-strings -Wno-c99-extensions -Wno-gnu-imaginary-constant -Wno-pedantic -Wstrict-prototypes -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wthread-safety -Xlinker --dependency-file=libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/link.d libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o -o libc/test/src/stdfix/libc.test.src.stdfix.bitshr_test.__unit__.__build__  libc/src/stdfix/CMakeFiles/libc.src.stdfix.bitshr.__internal__.dir/./bitshr.cpp.o  libc/src/errno/CMakeFiles/libc.src.errno.errno.__internal__.dir/./libc_errno.cpp.o  libc/src/__support/StringUtil/CMakeFiles/libc.src.__support.StringUtil.error_to_string.dir/./error_to_string.cpp.o  libc/src/__support/OSUtil/linux/CMakeFiles/libc.src.__support.OSUtil.linux.linux_util.dir/./exit.cpp.o  libc/src/__support/OSUtil/linux/CMakeFiles/libc.src.__support.OSUtil.linux.linux_util.dir/./fcntl.cpp.o  libc/test/UnitTest/libLibcDeathTestExecutors.unit.a  libc/test/UnitTest/libLibcTest.unit.a && :
> ld.lld: error: undefined hidden symbol: bool __llvm_libc_21_0_0_git::testing::internal::test<signed char>(__llvm_libc_21_0_0_git::testing::internal::RunContext*, __llvm_libc_21_0_0_git::testing::TestCond, signed char, signed char, char const*, char const*, __llvm_libc_21_0_0_git::testing::internal::Location)
> >>> referenced by bitshr_test.cpp
> >>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
> >>> referenced by bitshr_test.cpp
> >>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
> >>> referenced by bitshr_test.cpp
> >>>               libc/test/src/stdfix/CMakeFiles/libc.test.src.stdfix.bitshr_test.__unit__.__build__.dir/bitshr_test.cpp.o:(LlvmLibcBitshrTest_SpecialNumbers::Run())
> >>> referenced 3 more times
> >>> did you mean: bool __llvm_libc_21_0_0_git::testing::internal::test<bool>(__llvm_libc_21_0_0_git::testing::internal::RunContext*, __llvm_libc_21_0_0_git::testing::TestCond, bool, bool, char const*, char const*, __llvm_libc_21_0_0_git::testing::internal::Location)
> >>> defined in: libc/test/UnitTest/libLibcTest.unit.a(LibcTest.cpp.o)
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> this is the exact failure for `int_hr_t` (`short fract`)

You might need to add `signed char` to this list of speciallizations https://github.com/llvm/llvm-project/blob/main/libc/test/UnitTest/LibcTest.cpp#L220

File: libc/src/__support/fixed_point/fx_bits.h [hunk 3]
```diff
@@ -121,7 +121,7 @@ bit_and(T x, T y) {
   using BitType = typename FXRep<T>::StorageType;
   BitType x_bit = cpp::bit_cast<BitType>(x);
   BitType y_bit = cpp::bit_cast<BitType>(y);
-  // For some reason, bit_cast cannot deduce BitType from the input.
+  // For some reason, bit_cast cannot deduce BitType T the input.
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/src/__support/fixed_point/fx_bits.h]: fixed in [6bd83934](https://github.com/llvm/llvm-project/pull/128413/commits/6bd83934dad9a71a7f51ab832523b9f634e75d6c)

File: libc/test/src/stdfix/BitsFxTest.h [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+      0x6b851eb851eb851eULL;
+
+public:
+  typedef XType (*BitsFxFunc)(T);
+
+  void testSpecialNumbers(BitsFxFunc func) {
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/test/src/stdfix/BitsFxTest.h:36]: added here:

https://github.com/llvm/llvm-project/blob/9d0a7d211a494a89f38146fb0b2876dbdc16db6a/libc/test/src/stdfix/BitsFxTest.h#L48-L50

and here:

https://github.com/llvm/llvm-project/blob/9d0a7d211a494a89f38146fb0b2876dbdc16db6a/libc/test/src/stdfix/BitsFxTest.h#L69-L85

File: libc/test/src/stdfix/BitsFxTest.h [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    EXPECT_EQ(static_cast<XType>(0), func(zero));
+    EXPECT_EQ(static_cast<XType>(1ULL << (FXRep::FRACTION_LEN - 1)),
+              func(one_half));
+    EXPECT_EQ(static_cast<XType>(1ULL << (FXRep::FRACTION_LEN - 2)),
+              func(one_fourth));
+    EXPECT_EQ(static_cast<XType>(1), func(eps));
+
+    // (0.6875)_10 = (0.1011)_2
+    EXPECT_EQ(static_cast<XType>(11ULL << (FXRep::FRACTION_LEN - 4)),
+              func(0.6875));
```
[the remark this answers is not in the document]
Comment (krishna2803) [reply libc/test/src/stdfix/BitsFxTest.h]: fixed here:
https://github.com/llvm/llvm-project/blob/9d0a7d211a494a89f38146fb0b2876dbdc16db6a/libc/test/src/stdfix/BitsFxTest.h#L24

https://github.com/llvm/llvm-project/blob/9d0a7d211a494a89f38146fb0b2876dbdc16db6a/libc/test/src/stdfix/BitsFxTest.h#L44-L46

File: libc/test/src/stdfix/BitsFxTest.h [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+          EXPECT_EQ(static_cast<XType>(1372), func(special_num_t));
+          break;
+        case 15:
+          EXPECT_EQ(static_cast<XType>(351232), func(special_num_t));
+          break;
+        case 23:
+          EXPECT_EQ(static_cast<XType>(89915392), func(special_num_t));
+          break;
+        default:
+          break;
```
Comment (PiJoules) [inline libc/test/src/stdfix/BitsFxTest.h:65]: Hmm ok rather than having the switch, perhaps we could do something like have a preset number for the lowest value we know and do the shifts. That is, we have something like

```
constexpr size_t kMinFbits = 7;
if (max >= 11 && FXRep::FRACTION_LEN >= kMinFbits) {
  constexpr XType kExpected = 1372;  // 10.71875 with a scale of 7 equals this.
  EXPECT_EQ(XType << (FXRep::FRACTION_LEN - kMinFbits), func(special_num_t));
}
```

This way we can always have these tests even if the fractional bits aren't one of 7, 15, or 23.

Sorry I probably should've said this instead of accepting the switch from your comment earlier. I just though of this now.

File: libc/test/src/stdfix/BitsFxTest.h [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+        }
+    }
+
+    if constexpr (FXRep::SIGN_LEN > 0 && FXRep::INTEGRAL_LEN > 0) {
+      if (static_cast<int>(min) <= -11)
+        switch (FXRep::FRACTION_LEN) {
```
Comment (PiJoules) [inline libc/test/src/stdfix/BitsFxTest.h:71]: Could you also apply the comment I made above to this switch?

**Review by PiJoules — COMMENTED** [review]
Looking good so far. Just a few more comments from me.

File: libc/test/src/stdfix/BitsFxTest.h (hunk 6 above)
Comment (krishna2803) [reply libc/test/src/stdfix/BitsFxTest.h]: updated! here:

https://github.com/llvm/llvm-project/blob/2f9b642f71f63973e0c3ae65fbdd7bd19dd0533b/libc/test/src/stdfix/BitsFxTest.h#L55-L61

File: libc/test/src/stdfix/BitsFxTest.h (hunk 7 above)
Comment (krishna2803) [reply libc/test/src/stdfix/BitsFxTest.h]: updated here:

https://github.com/llvm/llvm-project/blob/2f9b642f71f63973e0c3ae65fbdd7bd19dd0533b/libc/test/src/stdfix/BitsFxTest.h#L63-L70

also refactored the tests for signed accum types to share the common `if` for `FXRep::INTEGRAL_LEN > 0`

**Review by PiJoules — APPROVED** [review]
LGTM. Thanks! Maybe wait for an LGTM from Tue also to make sure it conforms to libc standards.

**Review by lntue — APPROVED** [review]
