### PR TITLE
[Flang][OpenMP] Fix lastprivate store issue

### LINKED ISSUE #79780: [Flang][OpenMP] Compilation error when specifying do-variable of integer*1 or integer*2 in lastprivate clause
```
Version of flang-new : 18.0.0(0fe86f9c518fb1296bba8d66ce495f9dfff2c435)
```

If a `do-variable` of `integer*1` or `integer*2` is specified in `lastprivate` clause, a compilation error occurs.  
Compilation ends normally in the following cases:
- do not specify `lastprivate` clause in `parallel do` construct or
- do not specify the compilation option `-fopenmp`

The following are the test program, Flang-new, Gfortran and ifort compilation result.

sngtomp014_31.f90:
```fortran
program main
  call aaaaa
  print *,'pass'
end program main

subroutine aaaaa
  integer*1 i1
  i1=0
!$omp parallel do lastprivate(i1)
  do i1=1,8
  enddo
!$omp endparalleldo
end subroutine aaaaa
```

```
$ flang-new -fopenmp sngtomp014_31.f90
error: loc("/work/sngtomp014_31.f90":9:7): 'fir.store' op store value type must match memory reference type
error: verification of lowering to FIR failed
```

```
$ gfortran -fopenmp sngtomp014_31.f90
$
```

```
$ ifort -qopenmp sngtomp014_31.f90 -diag-disable=10448
$
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Fix an issue where the lastprivate variable type is different from the type used for the index of the loop.

Fixes #79780

### CODE REVIEW

File: flang/lib/Lower/OpenMP/DataSharingProcessor.cpp [hunk 1]
```diff
@@ -226,7 +226,9 @@ void DataSharingProcessor::insertLastPrivateCompare(mlir::Operation *op) {
       auto ifOp = firOpBuilder.create<fir::IfOp>(loc, cmpOp, /*else*/ false);
       firOpBuilder.setInsertionPointToStart(&ifOp.getThenRegion().front());
       assert(loopIV && "loopIV was not set");
-      firOpBuilder.create<fir::StoreOp>(loopOp.getLoc(), v, loopIV);
+      mlir::Value cvtV = firOpBuilder.createConvert(
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/DataSharingProcessor.cpp:229]: nit: it would be cleaner to use `fir::FirOpBUilder::createStoreWithConvert` here

**Review by tblah — APPROVED** [review]
Thanks for the bugfix

**Review by NimishMishra — COMMENTED** [review]
Thanks for the patch. The change looks good.
