### PR TITLE
[AMDGPU] fixes duplicate expressions in if stmnts in SIISelLowering.cpp

### LINKED ISSUE #81766: llvm/lib/Target/AMDGPU/SIISelLowering.cpp: 2 * suspicious if statements
Static analyser cppcheck says

1.

llvm/lib/Target/AMDGPU/SIISelLowering.cpp:14576:46: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is 

    // v2i16 (scalar_to_vector i16:x) -> v2i16 (bitcast (any_extend i16:x))
    if (VT == MVT::v2i16 || VT == MVT::v2f16 || VT == MVT::v2f16) {

2.

llvm/lib/Target/AMDGPU/SIISelLowering.cpp:6308:65: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is

  if (VT == MVT::v4f16 || VT == MVT::v8f16 || VT == MVT::v16f16 ||
      VT == MVT::v16f16)

### PR DESCRIPTION
**Pull request by nickleus27**
fixes #81766

### CODE REVIEW

**Review by xgupta — APPROVED** [review]
LGTM

File: llvm/lib/Target/AMDGPU/SIISelLowering.cpp [hunk 1]
```diff
@@ -6306,7 +6306,7 @@ SDValue SITargetLowering::lowerFMINNUM_FMAXNUM(SDValue Op,
     return expandFMINNUM_FMAXNUM(Op.getNode(), DAG);
 
   if (VT == MVT::v4f16 || VT == MVT::v8f16 || VT == MVT::v16f16 ||
-      VT == MVT::v16f16)
+      VT == MVT::v32f16)
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/SIISelLowering.cpp:6309]: Should have been v16bf16, not v32f16
