### PR TITLE
[MCA][X86] Pretend To Have a Stack Engine

### LINKED ISSUE #152008: [MCA][X86] llvm-mca very inaccurate for pop instructions
(Doing the below in terms of reciprocal throughput to make it easier to compare different tools/benchmark results).

For the following snippet of code:
```asm
popq %rax
popq %rcx
popq %rdx
popq %rbx
popq %r12
```

llvm-mca predicts a reciprocal throughput of 30 cycles:
```
Iterations:        1000
Instructions:      5000
Total Cycles:      30003
Total uOps:        10000

Dispatch Width:    6
uOps Per Cycle:    0.33
IPC:               0.17
Block RThroughput: 2.5
```
```
Iterations:        2000
Instructions:      10000
Total Cycles:      60003
Total uOps:        20000
```

(60003-30003)/1000=30 cycles per iteration.

`llvm-exegesis` measures a reciprocal throughput of about 6.5-7 cycles, but runs into a bunch of cache misses since all of the cache lines it is touching haven't been loaded yet:
```asm
# LLVM-EXEGESIS-DEFREG RSP 20000
# LLVM-EXEGESIS-MEM-DEF test1 131072 7fffffff
# LLVM-EXEGESIS-MEM-MAP test1 131072
popq %rax
popq %rcx
popq %rdx
popq %rbx
popq %r12
```
```
taskset -c 5 /tmp/llvm-exegesis -mode=latency -snippets-file=/tmp/test.s -execution-mode=subprocess -benchmark-process-cpu=6 -repetition-mode=loop -min-instructions=10000 -validation-counter=l1d-cache-load-misses
---
mode:            latency
key:
  instructions:
    - 'POP64r RAX'
    - 'POP64r RCX'
    - 'POP64r RDX'
    - 'POP64r RBX'
    - 'POP64r R12'
  config:          ''
  register_initial_values:
    - 'RSP=0x20000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-grtev4-linux-gnu
min_instructions: 10000
measurements:
  - { key: latency, value: 1.3718, per_snippet_value: 6.859, validation_counters:
      l1d-cache-load-misses: 3744 }
error:           ''
info:            ''
assembled_snippet: 41554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA11000000000000004D89E849B9000000000000000048B809000000000000000F0548BF000002000000000048BE000002000000000048BA030000000000000049BA110000000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F00005141535057565248BF00E0FFFFFF7F00008B3F48BE032400000000000048BA010000000000000048B810000000000000000F055A5E5F58415B5948BC000002000000000049B8020000000000000058595A5B415C58595A5B415C4983C0FF75EE48BF00E0FFFFFF7F00008B3F48BE012400000000000048BA010000000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415DC3
...
```
```
taskset -c 5 /tmp/llvm-exegesis -mode=latency -snippets-file=/tmp/test.s -execution-mode=subprocess -benchmark-process-cpu=6 -repetition-mode=loop -min-instructions=5000 -validation-counter=l1d-cache-load-misses
---
mode:            latency
key:
  instructions:
    - 'POP64r RAX'
    - 'POP64r RCX'
    - 'POP64r RDX'
    - 'POP64r RBX'
    - 'POP64r R12'
  config:          ''
  register_initial_values:
    - 'RSP=0x20000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-grtev4-linux-gnu
min_instructions: 5000
measurements:
  - { key: latency, value: 1.4052, per_snippet_value: 7.026, validation_counters:
      l1d-cache-load-misses: 2169 }
error:           ''
info:            ''
assembled_snippet: 41554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA11000000000000004D89E849B9000000000000000048B809000000000000000F0548BF000002000000000048BE000002000000000048BA030000000000000049BA110000000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F00005141535057565248BF00E0FFFFFF7F00008B3F48BE032400000000000048BA010000000000000048B810000000000000000F055A5E5F58415B5948BC000002000000000049B8020000000000000058595A5B415C58595A5B415C4983C0FF75EE48BF00E0FFFFFF7F00008B3F48BE012400000000000048BA010000000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415DC3
...
```

uiCA predicts a reciprocal throughput of 2.5 cycles per iteration, although I'm not (currently) convinced that is completely accurate.

I'm pretty sure MCA is seeing the dependency on `%rsp` and delaying the instructions because of that, although it seems like the hardware is able to figure that out without delaying execution. If we reset `%rsp` every iteration, MCA seems to do much better. Given this is a real register dependency, I'm not sure this is super easy to fix.

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch removes RSP dependencies from push and pop instructions to pretend that we have a stack engine. This does not model details like sync uops that are relevant implementation details due to complexity. This is just enabled on all X86 CPUs given LLVM does not have a scheduling model for any X86 CPU that does not have a stack engine.

This fixes #152008.

### CODE REVIEW

File: llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp [hunk 1]
```diff
@@ -36,11 +36,31 @@ void X86InstrPostProcess::setMemBarriers(std::unique_ptr<Instruction> &Inst,
   }
 }
 
+void X86InstrPostProcess::useStackEngine(std::unique_ptr<Instruction> &Inst,
+                                         const MCInst &MCI) {
+  if (X86::isPOP(MCI.getOpcode())) {
+    assert(Inst->getUses().size() == 1 &&
+           "Expected pop instruction to only use stack pointer register");
+    Inst->getUses().clear();
+  }
```
Comment (adibiagio) [inline llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp:45]: A use of RSP is "free" only if the definition of RSP comes from another PUSH/POP/RET. That is because the stack engine only tracks RSP updates from those known stack opcodes. The stack engine computes a delta between the new RSP value and the old RSP value. That delta is then used as an implicit addend operand to other RSP dependent PUSH/POP/RET.

The first time a stack operation is encountered, we should treat RSP like a normal read dependency, and simulate the full cost of waiting on RSP. Dependent stack operations which immediately follow the last dispatched stack operation can safely eliminate the dependency from RSP.

Any write to RSP which isn't from a stack operation would force a synchronization, and we would go back to square one.

In your case, if the last definition of RSP is not coming from another PUSH/POP/RET, then we should pay the full dependency cost.

As  you post-process instructions, you should keep track of if (and where) the last definition came from a stack operation. If so, then you always eliminate the dependency. Otherwise, you keep the dependency. If you see a known stack opcode, then you update the info about where the definition is coming from.

Bottom line: your change is mostly OK. However, you need to add some state/context to the prost-processing logic so to be able to track where the last write to RSP happened, and to know when it is safe to eliminate that dependency.

I hope it makes sense.
-Andrea

**Review by adibiagio — COMMENTED** [review]
Hi Aidan,

I left a comment about your post-processing logic.
I think you are definitely on the right track. However, we need some extra logic to avoid always eliminating RSP dependencies (see my comment).

File: llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp (hunk 1 above)
Comment (adibiagio) [reply llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp:45]: I don't remember the custom-behaviour / instr postprocess mechanism.
However, can we add artificial dependencies (similar to chain deps in DAG) for POP instructions, so that they are always guaranteed to executed in-order? Maybe @mshockwave  knows the answer to it.

Comment (boomanaiden154) [reply llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp]: I think I made a bit of a mountain out of a mole hill.

The stack engine computes the rsp offset right after decode time. So if we have another operation after some push/pop instructions that uses rsp, the decoder generates a stack sync uop to sync the state held in the decoder which the instruction using/writing rsp then depends on. The dependency chain for the rsp using/writing instruction does not actually end up depending on the stack operations writing anything back.

UICA models it this way:

image

I think that is reasonably close to real hardware, although with the snippet uica is simulating above, I'm getting a reciprocal throughput of three cycles instead of 2.5 like uica simulates:

```
# LLVM-EXEGESIS-MEM-MAP test1 131072
movq $0x20030, %rsp
popq %rax
popq %rcx
popq %rdx
popq %rbx
popq %r12
```

(~10900 cycles with `min-instructions=20000`, ~5900 cycles with `min-instructions=10000`, 1667 iterations per 10000 instructions gives a reciprocal throughput of about 3).

So uica isn't completely accurate here, but the reciprocal throughput of this being three cycles I'm reasonably sure implies there can't be a blocking write dependency here.

As a side note it looks like the scheduling model for `pushq` on skylake is not accurate, but that's a separate problem.

File: llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp [hunk 2]
```diff
@@ -36,11 +36,31 @@ void X86InstrPostProcess::setMemBarriers(std::unique_ptr<Instruction> &Inst,
...
+  if (X86::isPUSH(MCI.getOpcode())) {
```
[the remark this answers is not in the document]
Comment (boomanaiden154) [reply llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp]: Added a TODO to do actual benchmarking. Ignoring them for now sounds good.

File: llvm/test/tools/llvm-mca/X86/stack-engine-pop.s [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+# CHECK-NEXT:  -      -      -     0.50   0.50   0.50    -      -     0.50    -     popq	%rbx
+# CHECK-NEXT:  -      -     0.50   0.50   0.50   0.50    -      -      -      -     popq	%r12
+
+# CHECK:      Timeline view:
+# CHECK-NEXT:                     0123
+# CHECK-NEXT: Index     0123456789
+
+# CHECK:      [0,0]     DeER .    .  .   movq	$128, %rsp
+# CHECK-NEXT: [0,1]     D=eeeeeeER.  .   popq	%rax
+# CHECK-NEXT: [0,2]     D=eeeeeeER.  .   popq	%rcx
```
[the remark this answers is not in the document]
Comment (boomanaiden154) [reply llvm/test/tools/llvm-mca/X86/stack-engine-pop.s:68]: Yeah, precisely. Each iteration of the snippet would take 30+ cycles.

```
Iterations:        1
Instructions:      6
Total Cycles:      34
Total uOps:        11

Timeline view:
                    0123456789          0123
Index     0123456789          0123456789

[0,0]     DeER .    .    .    .    .    .  .   movq	$128, %rsp
[0,1]     D=eeeeeeER.    .    .    .    .  .   popq	%rax
[0,2]     D=======eeeeeeER    .    .    .  .   popq	%rcx
[0,3]     .D============eeeeeeER   .    .  .   popq	%rdx
[0,4]     .D==================eeeeeeER  .  .   popq	%rbx
[0,5]     .D========================eeeeeeER   popq	%r12
```

File: llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp [hunk 4]
```diff
@@ -36,11 +36,29 @@ void X86InstrPostProcess::setMemBarriers(std::unique_ptr<Instruction> &Inst,
...
+    assert(
+        StackRegisterDef != Inst->getDefs().end() &&
+        "Expected push instruction to implicitly use stack pointer register.");
+    Inst->getDefs().erase(StackRegisterDef);
+  }
+}
+
 void X86InstrPostProcess::postProcessInstruction(
     std::unique_ptr<Instruction> &Inst, const MCInst &MCI) {
   // Currently, we only modify certain instructions' IsALoadBarrier and
```
[the remark this answers is not in the document]
Comment (boomanaiden154) [reply llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp:58]: Yep. Done.

File: llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp (hunk 1 above)
Comment (boomanaiden154) [reply llvm/lib/Target/X86/MCA/X86CustomBehaviour.cpp]: image

(My previous example on uiCA was bad, because the register would just get renamed. Here it models stack sync uops).

Keeping the writes around for the stack operations would mean that the `add` instruction in the second iteration could only finish executing after the last `pop` instruction in the first iteration. While completely ignoring the stack sync uop does makes us less accurate here, keeping the write would make us significantly less accurate.

**Review by adibiagio — APPROVED** [review]
