### PR TITLE
[clang-tidy] Fix false positive in cppcoreguidelines-avoid-const-or-ref-data-members when detecting templated classes with inheritance

### LINKED ISSUE #111985: cppcoreguidelines-avoid-const-or-ref-data-members gives false positive when a templated class inherits
When a class with a const ref member inherits a class that deletes move/copy constructors and assignment operators `cppcoreguidelines-avoid-const-or-ref-data-members` still points out the ref member. This is not an unusual technique (e.g. inheriting from `boost::noncopyable`). I have written a test case on [Compiler Explorer](https://godbolt.org/z/fxxPMdsh8) that you can tweak using the `#define`s.

If the derived class is _not_ a template the check works as expected. If the class _is_ a template but deletes deletes the move/copy constructors and assignment operators itself also works as expected.

Summary:
|Is template|Inherits|False positive|
|--------------|-----------|--------------------|
|Yes|Yes|**Yes**|
|Yes|No|No|
|No|Yes|No|

Also, if the derived class is a template and inherits _and deletes the constructors/operators anyway_ it works as expected. But  this is presumably a "sub-case" of the non-inheriting case.

### PR DESCRIPTION
**Pull request by HerrCai0907**
`hasSimpleCopyConstructor` series of functions are not reliable when these functions are not resolved. We need to manually resolve the status of these functions from its base classes.
Fixes: #111985.

### CODE REVIEW

**Comment by HerrCai0907** [comment]
ping @5chmidti @PiotrZSL

File: clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp [hunk 1]
```diff
@@ -19,75 +19,87 @@ AST_MATCHER(FieldDecl, isMemberOfLambda) {
...
-    if (Ctor->isCopyConstructor()) {
-      Constructors.Copy.Declared = true;
-      if (Ctor->isDeleted())
-        Constructors.Copy.Deleted = true;
-    }
-    if (Ctor->isMoveConstructor()) {
-      Constructors.Move.Declared = true;
-      if (Ctor->isDeleted())
-        Constructors.Move.Deleted = true;
+bool hasCopyConstructor(CXXRecordDecl const &Node) {
```
Comment (carlosgalvezp) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp:22]: Make these helper functions `static`, as per the guidelines?

File: clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp [hunk 2]
```diff
@@ -13,79 +13,92 @@
 using namespace clang::ast_matchers;
 
 namespace clang::tidy::cppcoreguidelines {
-namespace {
 
-AST_MATCHER(FieldDecl, isMemberOfLambda) {
-  return Node.getParent()->isLambda();
+static bool hasCopyConstructor(CXXRecordDecl const &Node) {
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp:17]: You can probably use `CXXRecordDecl::defaultedCopyConstructorIsDeleted` as well, at least for an earlier exit. (+ move ctor)

File: clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp [hunk 3]
```diff
@@ -13,79 +13,92 @@
...
 
-MemberFunctionPairInfo getAssignmentsInfo(CXXRecordDecl const &Node) {
-  MemberFunctionPairInfo Assignments{};
-
-  for (CXXMethodDecl const *Method : Node.methods()) {
-    if (Method->isCopyAssignmentOperator()) {
-      Assignments.Copy.Declared = true;
-      if (Method->isDeleted())
-        Assignments.Copy.Deleted = true;
+static bool hasCopyAssignment(CXXRecordDecl const &Node) {
```
Comment (5chmidti) [inline clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp:55]: You can use `hasUserDeclaredCopyAssignment` and `hasInheritedAssignmen` to short-circuit earlier for the copy assignment and move assignment

File: clang-tools-extra/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -195,6 +195,10 @@ Changes in existing checks
   fix false positive that floating point variable is only used in increment
   expression.
 
+- Improved :doc:`cppcoreguidelines-avoid-const-or-ref-data-members
+  <clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members>` check to
+  avoid false positive when detecting templated class with inheritance.
```
Comment (5chmidti) [inline clang-tools-extra/docs/ReleaseNotes.rst:200]: `positives when detecting a`

File: clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp (hunk 3 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp:55]: it does not work for template function because sema don't set this field.

File: clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp (hunk 2 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidConstOrRefDataMembersCheck.cpp:17]: `hasSimpleCopyConstructor` includes the `defaultedCopyConstructorIsDeleted`. The first check is for template function which the flag is not be setted.

**Review by carlosgalvezp — APPROVED** [review]
LGTM!

**Review by 5chmidti — APPROVED** [review]
