### PR TITLE
[mlir][tosa] Check for 0-ranked-tensors during fold

### LINKED ISSUE #67761: [mlir] --convert-amdgpu-to-rocdl crashed with assertion failure "invalid index for shaped type"
git version: 8c1270740f6bf659e5fbf556c1145ddaa7aa5366

system: ```Ubuntu 20.04.6 LTS (Focal Fossa)```

reproduced with: ```mlir-opt --convert-amdgpu-to-rocdl a.mlir```

a.mlir:

```
func.func nested @func2() {
  %c0 = arith.constant 0 : index
  %c22 = arith.constant 22 : index
  %22 = tensor.empty(%c22) : tensor<?x10xi32>
  %64 = tosa.reduce_min %22 {axis = 0 : i32} : (tensor<?x10xi32>) -> tensor<1x10xi32>
  %90 = tosa.slice %64 {size = array<i64>, start = array<i64>} : (tensor<1x10xi32>) -> tensor<i32>
  vector.warp_execute_on_lane_0(%c0)[32] {
    %155 = tosa.reverse %90 {axis = 0 : i32} : (tensor<i32>) -> tensor<1x10xi32>
  }
  return
}
```

trace:

```
mlir-opt: /data/bin/llvm-project/build/tools/mlir/include/mlir/IR/BuiltinTypeInterfaces.h.inc:195: int64_t mlir::ShapedType::getDimSize(unsigned int) const: Assertion `idx < getRank() && "invalid index for shaped type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/bin/llvm-project/build/bin/mlir-opt --convert-amdgpu-to-rocdl a.mlir
 #0 0x000055bfe0860d4f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/bin/llvm-project/build/bin/mlir-opt+0x157cd4f)
 #1 0x000055bfe085dde4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fec00a8c420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007fec0057700b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007fec00556859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007fec00556729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007fec00567fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x000055bfe2561570 auto llvm::dyn_cast_if_present<mlir::DenseElementsAttr, mlir::Attribute>(mlir::Attribute const&) (/data/bin/llvm-project/build/bin/mlir-opt+0x327d570)
 #8 0x000055bfe25675d3 mlir::tosa::ReverseOp::fold(mlir::tosa::ReverseOpGenericAdaptor<llvm::ArrayRef<mlir::Attribute>>) (/data/bin/llvm-project/build/bin/mlir-opt+0x32835d3)
 #9 0x000055bfe24d73e9 mlir::LogicalResult llvm::detail::UniqueFunctionBase<mlir::LogicalResult, mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&>::CallImpl<mlir::Op<mlir::tosa::ReverseOp, mlir::OpTrait::ZeroRegions, mlir::OpTrait::OneResult, mlir::OpTrait::OneTypedResult<mlir::TensorType>::Impl, mlir::OpTrait::ZeroSuccessors, mlir::OpTrait::OneOperand, mlir::OpTrait::OpInvariants, mlir::BytecodeOpInterface::Trait, mlir::InferShapedTypeOpInterface::Trait, mlir::ConditionallySpeculatable::Trait, mlir::OpTrait::AlwaysSpeculatableImplTrait, mlir::MemoryEffectOpInterface::Trait, mlir::tosa::TosaOp::Trait>::getFoldHookFn()::'lambda'(mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) const>(void*, mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x31f33e9)
#10 0x000055bfe254e8a6 mlir::RegisteredOperationName::Model<mlir::tosa::ReverseOp>::foldHook(mlir::Operation*, llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x326a8a6)
#11 0x000055bfe349c3e2 mlir::Operation::fold(llvm::ArrayRef<mlir::Attribute>, llvm::SmallVectorImpl<mlir::OpFoldResult>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x41b83e2)
#12 0x000055bfe349c728 mlir::Operation::fold(llvm::SmallVectorImpl<mlir::OpFoldResult>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x41b8728)
#13 0x000055bfe33cec6a mlir::OpBuilder::tryFold(mlir::Operation*, llvm::SmallVectorImpl<mlir::Value>&) (/data/bin/llvm-project/build/bin/mlir-opt+0x40eac6a)
#14 0x000055bfe333bbcb (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*, mlir::ConversionPatternRewriter&) DialectConversion.cpp:0:0
#15 0x000055bfe333c687 (anonymous namespace)::OperationConverter::convertOperations(llvm::ArrayRef<mlir::Operation*>, llvm::function_ref<void (mlir::Diagnostic&)>) DialectConversion.cpp:0:0
#16 0x000055bfe333eaf4 mlir::applyPartialConversion(mlir::Operation*, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, llvm::DenseSet<mlir::Operation*, llvm::DenseMapInfo<mlir::Operation*, void>>*) (/data/bin/llvm-project/build/bin/mlir-opt+0x405aaf4)
#17 0x000055bfe2827b25 (anonymous namespace)::ConvertAMDGPUToROCDLPass::runOnOperation() AMDGPUToROCDL.cpp:0:0
#18 0x000055bfe3293e8e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fafe8e)
#19 0x000055bfe329436a mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fb036a)
#20 0x000055bfe3294b94 mlir::PassManager::run(mlir::Operation*) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fb0b94)
#21 0x000055bfe328546b performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#22 0x000055bfe3286924 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPool*) MlirOptMain.cpp:0:0
#23 0x000055bfe3286ad4 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#24 0x000055bfe3384f84 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/data/bin/llvm-project/build/bin/mlir-opt+0x40a0f84)
#25 0x000055bfe327fef7 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/bin/llvm-project/build/bin/mlir-opt+0x3f9bef7)
#26 0x000055bfe3286dfb mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/bin/llvm-project/build/bin/mlir-opt+0x3fa2dfb)
#27 0x000055bfe0799feb main (/data/bin/llvm-project/build/bin/mlir-opt+0x14b5feb)
#28 0x00007fec00558083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#29 0x000055bfe0831a0e _start (/data/bin/llvm-project/build/bin/mlir-opt+0x154da0e)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by gptsarthak**
Fixes https://github.com/llvm/llvm-project/issues/67761
Trying `getDimSize()` before checking for 0-ranked-tensors throws assert errors. This PR ensures that it is checked for.
Or should we throw an error if we have a 0-ranked-tensor in a tosa operation?

### CODE REVIEW

File: mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp [hunk 1]
```diff
@@ -874,7 +874,8 @@ OpFoldResult ReverseOp::fold(FoldAdaptor adaptor) {
     return operandAttr;
 
   // If the dim-length is 1, tosa.reverse is a no-op.
-  if (operandTy.hasRank() && operandTy.getDimSize(axis) == 1)
+  if (operandTy.hasRank() && operandTy.getRank() != 0 &&
```
Comment (GeorgeARM) [inline mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp:877]: Should rank-0 tensors get folded as well?

File: mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp [hunk 2]
```diff
@@ -771,7 +771,7 @@ OpFoldResult ConstOp::fold(FoldAdaptor adaptor) { return getValueAttr(); }
     ShapedType inputTy = llvm::cast<ShapedType>(getInput().getType());         \
     if (!inputTy.hasRank())                                                    \
       return {};                                                               \
-    if (inputTy.getDimSize(getAxis()) == 1)                                    \
+    if (inputTy.getRank() != 0 && inputTy.getDimSize(getAxis()) == 1)          \
```
Comment (GeorgeARM) [inline mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp:774]: Shouldn't reduction on rank0 tensor get folded as well?

Comment (gptsarthak) [reply mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp:774]: Would you like me to change it to `if (inputTy.getRank() == 0 || inputTy.getDimSize(getAxis()) == 1)` ? That would solve the issue and fold rank0 tensors as well.

File: mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp (hunk 1 above)
Comment (GeorgeARM) [reply mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp:877]: Give it a go. Would be great to write a small canonicalization test as well in `canonicalize.mlir` in TOSA tests for these.

**Comment by GeorgeARM** [comment]
Looking again at the spec it says that reduce and reverse operators need to take as input tensor of rank 1 or higher. So the most appropriate solution here really is to change the TOSA operator specification to accept `AnyNon0RankedOrUnrankedTensor` as an input here.  Thoughts @eric-k256?

**Comment by gptsarthak** [comment]
> Looking again at the spec it says that reduce and reverse operators need to take as input tensor of rank 1 or higher.

Where can I find the specs?

File: mlir/test/Dialect/Tosa/canonicalize.mlir [hunk 3]
```diff
@@ -591,3 +591,13 @@ func.func @fold_abs_abs(%arg0: tensor<?x1xf32>) -> tensor<?x1xf32> {
   %1 = tosa.abs %0 : (tensor<?x1xf32>) -> tensor<?x1xf32>
   return %1 : tensor<?x1xf32>
 }
+
+// -----
+
+// CHECK-LABEL: @rank_zero
```
Comment (eric-k256) [inline mlir/test/Dialect/Tosa/canonicalize.mlir:597]: Can you make a change to make the name more descriptive? Maybe something like fold_reduce_rank_zero or something similar.

**Review by eric-k256 — CHANGES_REQUESTED** [review]
I think this change is good. @GeorgeARM is right that the spec doesn't support rank 0 right now, but we're trying to review support of rank0 and we might change the restrictions on reductions to allow rank0 to occur with result == input as you do with this fold.

Just the one request for a better test name. Thanks!

File: mlir/test/Dialect/Tosa/canonicalize.mlir [hunk 4]
```diff
@@ -591,3 +591,13 @@ func.func @fold_abs_abs(%arg0: tensor<?x1xf32>) -> tensor<?x1xf32> {
...
+func.func nested @rank_zero() {
+  %0 = tensor.empty() : tensor<i32>
+  %1 = tosa.reduce_min %0 {axis = 0 : i32} : (tensor<i32>) -> tensor<1x10xi32>
```
Comment (GeorgeARM) [inline mlir/test/Dialect/Tosa/canonicalize.mlir:600]: Also worth adding a `CHECK-NOT` label and ensure that the `reduce_min` and `reverse` ops are not present after the canonicalization

File: mlir/test/Dialect/Tosa/canonicalize.mlir (hunk 3 above)
Comment (gptsarthak) [reply mlir/test/Dialect/Tosa/canonicalize.mlir]: Sure, I renamed it to `fold_reduce_rank_zero`.

File: mlir/test/Dialect/Tosa/canonicalize.mlir (hunk 4 above)
Comment (gptsarthak) [reply mlir/test/Dialect/Tosa/canonicalize.mlir:602]: Added the `CHECK-NOT` labels for both the ops.

**Review by GeorgeARM — APPROVED** [review]
LGTM

**Review by eric-k256 — APPROVED** [review]
Thanks, looks good to me.

**Comment by GeorgeARM** [comment]
@gptsarthak was trying to merge the commit but I see the following `62467938+gptsarthak@users.noreply.github.com`.
Is this intentional?

**Comment by gptsarthak** [comment]
@GeorgeARM I don't understand what the issue is. Where do you see it?

**Comment by eric-k256** [comment]
That is what you get if you have told GitHub to 'keep private email'. When someone goes to merge the change, GitHub will remove the email address from the commit and substitute something like the above. There is no existing policy in LLVM on this as far as I'm aware.

**Comment by gptsarthak** [comment]
I have made my email public. It should no longer be an issue.
