### PR TITLE
Fix analyzer crash on 'StructuralValue'

### LINKED ISSUE #79575: [analyzer] Crash on using non-type template arguments
clang 18.1.0 crashes on the following code snippet, while clang-17 does not.
https://godbolt.org/z/h3sME4Gdz

This is a nullpointer dereference.

```c++
constexpr char abc[] = "abc";
void use(const char *fmt);

template <const char* in>
void use_template_param() {
  const char *p = in;
}
void force_instantiate() {
  use_template_param<abc>();
}
```

Stack trace:
```
#0  clang::Stmt::getStmtClass (this=0x0) at clang/include/clang/AST/Stmt.h:1357
#1  ignoreTransparentExprs (E=0x0) at Core/Environment.cpp:41
#2  ignoreTransparentExprs (E=0x0) at Core/Environment.cpp:62
#3  ignoreTransparentExprs (E=0x7f2d5418c080) at Core/Environment.cpp:62
#4  ignoreTransparentExprs (E=0x7f2d5418c098) at Core/Environment.cpp:62
#5  ignoreTransparentExprs (S=0x7f2d5418c0f8) at Core/Environment.cpp:67
#6  clang::ento::EnvironmentEntry::EnvironmentEntry () at Core/Environment.cpp:73
#7  clang::ento::ProgramState::getSVal () at Core/PathSensitive/ProgramState.h:807
#8  0x00007f2d68e76926 in clang::ento::ExprEngine::VisitCast () at Core/ExprEngineC.cpp:337
#9  0x00007f2d68e38cdc in clang::ento::ExprEngine::Visit () at Core/ExprEngine.cpp:2280
#10 0x00007f2d68e35039 in clang::ento::ExprEngine::ProcessStmt () at Core/ExprEngine.cpp:1134
#11 0x00007f2d68e34ccd in clang::ento::ExprEngine::processCFGElement () at Core/ExprEngine.cpp:976
#12 0x00007f2d68dfb5ff in clang::ento::CoreEngine::HandlePostStmt () at Core/CoreEngine.cpp:499
#13 0x00007f2d68dfad62 in clang::ento::CoreEngine::dispatchWorkItem () at Core/CoreEngine.cpp:220
```

In the AST, we have this segment for the `const char *p = in;` variable declaration:
```
`-VarDecl <col:3, col:19> col:15 p 'const char *' cinit
  `-SubstNonTypeTemplateParmExpr <col:19> 'const char *'
    |-NonTypeTemplateParmDecl <line:4:11, col:23> col:23 referenced 'const char *' depth 0 index 0 in
    `-ConstantExpr <line:6:19> 'const char *'
      |-value: LValue <todo>
      `-OpaqueValueExpr <col:19> 'const char *'
```

That dump comes from the `TextNodeDumper.cpp`:
```c++
  case APValue::LValue:
    (void)Context;
    OS << "LValue <todo>";
    return;
```
So, some APValue must be of kind `LValue`.

Anyways, bisections blames 5518a9d7673bfe55b4110bea049140316d032fbf (`[c++20] P1907R1: Support for generalized non-type template arguments of scalar type. (#78041)`, 2024.01.21.) commit for introducing this crash.

This is a regression, as clang-17 did not crash on the same input.

Notes for myself: CPP-4927

### PR DESCRIPTION
**Pull request by bolshakov-a**
`OpaqueValueExpr` doesn't necessarily contain a source expression. Particularly, after #78041, it is used to carry the type and the value kind of a non-type template argument of floating-point type or referring to a subobject (those are so called `StructuralValue` arguments).

This fixes #79575.

### CODE REVIEW

**Comment by bolshakov-a** [comment]
@steakhal, @cor3ntin, @erichkeane

**Review by cor3ntin — APPROVED** [review]
Thanks!

**Comment by zmodem** [comment]
I think a similar fix may be needed in `clang::IgnoreParensSingleStep`, see my comment here: https://github.com/llvm/llvm-project/pull/78041#issuecomment-1914407300

File: clang/lib/StaticAnalyzer/Core/Environment.cpp [hunk 1]
```diff
@@ -40,8 +40,12 @@ static const Expr *ignoreTransparentExprs(const Expr *E) {
...
   switch (E->getStmtClass()) {
   case Stmt::OpaqueValueExprClass:
-    E = cast<OpaqueValueExpr>(E)->getSourceExpr();
-    break;
+    if (const clang::Expr *SE = cast<OpaqueValueExpr>(E)->getSourceExpr()) {
+      E = SE;
+      break;
+    } else {
+      return E;
+    }
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Core/Environment.cpp:48]:
```suggestion
    if (const auto *SE = cast<OpaqueValueExpr>(E)->getSourceExpr()) {
      E = SE;
      break;
    }
    return E;
```
Fix `else-after-break`.
Use `auto` after `cast<>`.

**Review by steakhal — APPROVED** [review]
Approved with nits. This works around the crash.

File: clang/lib/StaticAnalyzer/Core/Environment.cpp (hunk 1 above)
Comment (bolshakov-a) [reply clang/lib/StaticAnalyzer/Core/Environment.cpp:48]: Thanks! `else` doesn't make sense, indeed.

But it should be noted that `SE` refers to the result of `->getSourceExpr()` and not to the result of `cast<OpaqueValueExpr>(E)`, hence its type is not a pointer to `OpaqueValueExpr`. Doesn't LLVM policy insist on the explicit type in such cases? Nevertheless, `clang::` qualification is redundant.

**Review by steakhal — APPROVED** [review]
LGTM for the Static Analyzer.
Thanks for fixing this crash.

File: clang/lib/StaticAnalyzer/Core/Environment.cpp (hunk 1 above)
Comment (steakhal) [reply clang/lib/StaticAnalyzer/Core/Environment.cpp]: Makes sense. Consider this resolved.

**Comment by steakhal** [comment]
> LGTM for the Static Analyzer.

Actually, the other hunk also makes sense. LGTM.

**Comment by zmodem** [comment]
> Shouldn't we add a regression test for the crash on that part too?

+1 that would be good to have.

**Review by erichkeane — APPROVED** [review]

**Comment by zmodem** [comment]
Thanks! It would be great to get this landed as soon as possible to unbreak trunk. (I believe we need it for the 18.x branch too?)

**Comment by steakhal** [comment]
> Thanks! It would be great to get this landed as soon as possible to unbreak trunk. (I believe we need it for the 18.x branch too?)

I'll take care of the backport, after this PR is merged by @bolshakov-a

**Comment by bolshakov-a** [comment]
Thanks!
