### PR TITLE
[Clang][Sema] Fix a bug on type constraint checking

### LINKED ISSUE #84368: "type constraint differs in template redeclaration" for `template` Inner Class
Consider the following semi-minimal example:
```cpp
template<class T> concept IsOk = requires() { typename T::Float; };

template<IsOk T> struct Thing;

template<IsOk T> struct Foobar {
	template<int> struct Inner {
		template<IsOk T2> friend struct Thing;
	};
};

struct MyType { using Float=float; };
Foobar<MyType>::Inner<0> foobar;
```
GCC and MSVC compile this happily, but Clang outputs (I believe erroneously):
```text
<source>:7:12: error: type constraint differs in template redeclaration
    7 |                 template<IsOk T2> friend struct Thing;
      |                          ^
<source>:12:26: note: in instantiation of template class 'Foobar<MyType>::Inner<0>' requested here
   12 | Foobar<MyType>::Inner<0> foobar;
      |                          ^
<source>:3:10: note: previous template declaration is here
    3 | template<IsOk T> struct Thing;
      |          ^
```
---

I note the similarity to:
- [Defining constrained member function out of line is rejected #47364](https://github.com/llvm/llvm-project/issues/47364)
( See also [bugzilla](https://bugs.llvm.org/show_bug.cgi?id=48020), [StackOverflow 1](https://stackoverflow.com/questions/64780598/why-isnt-this-class-specialization-using-a-concept-accepted), [StackOverflow 2](https://stackoverflow.com/questions/64601583/gcc-clang-disagree-on-constrained-partial-template-specialization-with-out-of-li), and [duplicate](https://github.com/llvm/llvm-project/issues/47364). )

However, this bug is still present in trunk ([tested version](https://github.com/llvm/llvm-project/commit/b84f3ea9963058cdd910f5106ca2a70c1bb9e460)).

### PR DESCRIPTION
**Pull request by jcsxky**
Try to fix https://github.com/llvm/llvm-project/issues/84368
When visiting class members in `TemplateDeclInstantiator::VisitClassTemplateDecl` during `Sema::InstantiateClass`, we miss to set attribute of friend declaration if it is(`isFriend` is true). This will lead to `Sema::AreConstraintExpressionsEqual` return false when invoked in `MatchTemplateParameterKind`. Because it makes `Sema::getTemplateInstantiationArgs` returns incorrect template argument(`MultiLevelTemplateArgumentList`). When we handle `CXXRecordDecl` In `Sema::getTemplateInstantiationArgs`, friend declaration(its parent context is `FileContext`) makes us to choose `LexicalDeclContext` not `DeclContext` and this is what we want.

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
The commit message and release note needs to be MUCH more detailed.  Else I think this looks like an acceptable patch.

**Comment by jcsxky** [comment]
> The commit message and release note needs to be MUCH more detailed. Else I think this looks like an acceptable patch.

Thanks for you remind! I have updated commit message and release note to make it more clear.

File: clang/test/Sema/PR84368.cpp [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// RUN: %clang_cc1 -std=c++20 -verify %s
+// RUN: %clang_cc1 -std=c++23 -verify %s
+// expected-no-diagnostics
+
+template<class T> concept IsOk = requires() { typename T::Float; };
+
+template<IsOk T> struct Thing;
+
+template<IsOk T> struct Foobar {
```
Comment (erichkeane) [inline clang/test/Sema/PR84368.cpp:9]: Indenting here doesn't match our clang-format rules. Please fix that.

**Review by erichkeane — APPROVED** [review]

**Review by erichkeane — APPROVED** [review]
