### PR TITLE
[FunctionAttrs] Don't infer noundef when return has nofpclass

### LINKED ISSUE #191338: [InstCombine] Incorrect select elimination cut the poison propagation on vector splat return
For the case:
```llvm
declare nofpclass(inf zero sub norm) half @returns_nan_f16()

define nofpclass(nan) <4 x half> @ret_nonan_splat(i1 %cond, half %unknown) {
  %nan = call half @returns_nan_f16()
  %freeze.ins = freeze half %nan
  %nan.vec = insertelement <4 x half> poison, half %freeze.ins, i32 0
  %unknown.vec = insertelement <4 x half> poison, half %unknown, i32 poison
  %splat.nan = shufflevector <4 x half> %nan.vec, <4 x half> poison, <4 x i32> zeroinitializer
  %splat.unknown = shufflevector <4 x half> %unknown.vec, <4 x half> poison, <4 x i32> zeroinitializer
  %select = select i1 %cond, <4 x half> %splat.nan, <4 x half> %splat.unknown
  ret <4 x half> %select
}
```

It may return `poison` if `%cond == true`

but the `Opt -passes=instcombine` will optimize it to: 

```llvm
declare nofpclass(inf zero sub norm) half @returns_nan_f16()

define nofpclass(nan) <4 x half> @ret_nonan_splat(i1 %cond, half %unknown) {
  %nan = call half @returns_nan_f16()
  %freeze.ins = freeze half %nan
  %nan.vec = insertelement <4 x half> poison, half %freeze.ins, i64 0
  %splat.nan = shufflevector <4 x half> %nan.vec, <4 x half> poison, <4 x i32> zeroinitializer
  ret <4 x half> %splat.nan
}
```

There is only `noundef` value that can be returned

Alive2: https://alive2.llvm.org/ce/z/kKjvL4

### PR DESCRIPTION
**Pull request by shoniecaplan**
- Fixes: #191338

nofpclass violations on a return produce poison.
Poison returns marked noundef are UB.
This turns off noundef inference when nofpclass attributes are present.

### CODE REVIEW

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 1]
```diff
@@ -1742,6 +1742,10 @@ static void addNoUndefAttrs(const SCCNodeSet &SCCNodes,
                 !Attr.getRange().contains(
                     computeConstantRange(RetVal, /*ForSigned=*/false)))
               return false;
+
+            Attribute NoFP = Attrs.getRetAttr(Attribute::NoFPClass);
+            if (NoFP.hasAttribute(Attribute::NoFPClass))
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp]: I'd suggest following the checks above: we keep nofpclass iff it can be derived from `computeKnownFPClass`.

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 2]
```diff
@@ -1742,6 +1743,11 @@ static void addNoUndefAttrs(const SCCNodeSet &SCCNodes,
                 !Attr.getRange().contains(
                     computeConstantRange(RetVal, /*ForSigned=*/false)))
               return false;
+
+            FPClassTest AttrFPClass = Attrs.getRetNoFPClass();
+            KnownFPClass ComputedFPClass = computeKnownFPClass(RetVal, DL);
+            if (!ComputedFPClass.isKnownNever(AttrFPClass))
+              return false;
```
Comment (dtcxzyw) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp]:
```suggestion
            if (AttrFPClass != fcNone) {
              KnownFPClass ComputedFPClass = computeKnownFPClass(RetVal, DL);
              if (!ComputedFPClass.isKnownNever(AttrFPClass))
                return false;
            }
```
RetVal may not be a nofpclass-compatible value.

Comment (shoniecaplan) [reply llvm/lib/Transforms/IPO/FunctionAttrs.cpp]: thank you!

**Review by arsenm — APPROVED** [review]

File: llvm/lib/Transforms/IPO/FunctionAttrs.cpp [hunk 3]
```diff
@@ -1742,6 +1743,13 @@ static void addNoUndefAttrs(const SCCNodeSet &SCCNodes,
                 !Attr.getRange().contains(
                     computeConstantRange(RetVal, /*ForSigned=*/false)))
               return false;
+
+            FPClassTest AttrFPClass = Attrs.getRetNoFPClass();
+            if (AttrFPClass != fcNone) {
+              KnownFPClass ComputedFPClass = computeKnownFPClass(RetVal, DL);
+              if (!ComputedFPClass.isKnownNever(AttrFPClass))
+                return false;
+            }
```
Comment (arsenm) [inline llvm/lib/Transforms/IPO/FunctionAttrs.cpp:1752]: Maybe there should be an assert there are no remaining poison generating return attributes in case another gets added
