### PR TITLE
[clang] Update typechecking of builtin elementwise ternary math operators

### LINKED ISSUE #155405: [clang] Ternary builtin operators treat constness differently than other builtins
Consider this code:

```c++
typedef float float3 __attribute__((ext_vector_type(3)));

typedef struct {
  float3 b;
} struct_float3;

float3 foo(float3 a, const struct_float3* hi) {
  return __builtin_elementwise_fma(a, a, hi->b.yyy);
}

float3 bar(float3 a, const struct_float3* hi) {
  return __builtin_elementwise_pow(a, hi->b.yyy);
}
```

Clang will report an error about `foo` but not `bar`:

```
source.cpp:19:36: error: arguments are of different types ('float3' (vector of 3 'float' values) vs 'const float3' (vector of 3 'float' values))
   19 |   return __builtin_elementwise_fma(a, a, hi->b.yyy);
      |                                    ^
```

The solution is to use `ASTContext::hasSameUnqualifiedType()` in `BuiltinElementwiseTernaryMath` similar to #141397. This was originally discovered by @tbaederr in https://github.com/llvm/llvm-project/pull/153572#discussion_r2299633300.

### PR DESCRIPTION
**Pull request by ckoparkar**
Fixes #155405

For scalars we directly compare their unqualified types. But even if we compare unqualified vector types, a difference in qualifiers in the element types can make the vector types be considered not equal. For example, vector of 4 'const float' values vs vector of 4 'float' values. So we compare unqualified types of their elements and number of elements.

/cc @tbaederr

### CODE REVIEW

**Comment by ckoparkar** [comment]
- This patch only changes the behavior for input arguments. For consistency, we should change how canonical types are computed for these vectors, but that will have a widespread impact.

File: clang/lib/Sema/SemaChecking.cpp [hunk 1]
```diff
@@ -15884,6 +15884,58 @@ static bool checkBuiltinVectorMathMixedEnums(Sema &S, Expr *LHS, Expr *RHS,
...
+/// compare unqualified vector types, a difference in qualifiers in the element
+/// types can make the vector types be considered not equal. For example,
+/// vector of 4 'const float' values vs vector of 4 'float' values.
+/// So we compare unqualified types of their elements and number of elements.
+/// See GitHub issue #155405.
+static bool checkBuiltinVectorMathArgTypes(Sema &SemaRef, unsigned NumArgs,
+                                           Expr *Args[]) {
+  assert(NumArgs > 0 && "Should have at least one argument.");
+
+  auto EmitError = [&](int I) {
```
Comment (tbaederr) [inline clang/lib/Sema/SemaChecking.cpp:15900]:
```suggestion
  auto EmitError = [&](unsigned I) {
```

File: clang/lib/Sema/SemaChecking.cpp [hunk 2]
```diff
@@ -15884,6 +15884,58 @@ static bool checkBuiltinVectorMathMixedEnums(Sema &S, Expr *LHS, Expr *RHS,
...
+    SemaRef.Diag(Args[0]->getBeginLoc(),
+                 diag::err_typecheck_call_different_arg_types)
+        << Args[0]->getType() << Args[I]->getType();
+  };
+
+  QualType Ty0 = Args[0]->getType();
+
+  // Compare scalar types.
+  if (!Ty0->isVectorType()) {
+    for (unsigned I = 1; I < NumArgs; ++I)
```
Comment (tbaederr) [inline clang/lib/Sema/SemaChecking.cpp:15910]:
```suggestion
    for (unsigned I = 1; I != NumArgs; ++I)
```

File: clang/lib/Sema/SemaChecking.cpp [hunk 3]
```diff
@@ -15884,6 +15884,58 @@ static bool checkBuiltinVectorMathMixedEnums(Sema &S, Expr *LHS, Expr *RHS,
...
+        EmitError(I);
+        return true;
+      }
+
+    return false;
+  }
+
+  // Compare vector types.
+  const auto *Vec0 = Ty0->castAs<VectorType>();
+  for (unsigned I = 1; I < NumArgs; ++I) {
```
Comment (tbaederr) [inline clang/lib/Sema/SemaChecking.cpp:15921]:
```suggestion
  for (unsigned I = 1; I != NumArgs; ++I) {
```

**Review by Sirraide — COMMENTED** [review]
This still needs a release note.

File: clang/lib/Sema/SemaChecking.cpp [hunk 4]
```diff
@@ -15884,6 +15884,58 @@ static bool checkBuiltinVectorMathMixedEnums(Sema &S, Expr *LHS, Expr *RHS,
...
+/// error message and return true. Otherwise return false.
+///
+/// For scalars we directly compare their unqualified types. But even if we
+/// compare unqualified vector types, a difference in qualifiers in the element
+/// types can make the vector types be considered not equal. For example,
+/// vector of 4 'const float' values vs vector of 4 'float' values.
+/// So we compare unqualified types of their elements and number of elements.
+/// See GitHub issue #155405.
+static bool checkBuiltinVectorMathArgTypes(Sema &SemaRef, unsigned NumArgs,
+                                           ArrayRef<Expr *> Args) {
```
[the remark this answers is not in the document]
Comment (ckoparkar) [reply clang/lib/Sema/SemaChecking.cpp]: I was passing in `Args` directly but wasn't aware of the ArrayRef class. I've used the `size()` function instead of the additional `NumArgs` parameter.

File: clang/lib/Sema/SemaChecking.cpp [hunk 5]
```diff
@@ -15884,6 +15884,55 @@ static bool checkBuiltinVectorMathMixedEnums(Sema &S, Expr *LHS, Expr *RHS,
...
 
+/// Check if all arguments have the same type. If the types don't match, emit an
+/// error message and return true. Otherwise return false.
+///
+/// For scalars we directly compare their unqualified types. But even if we
+/// compare unqualified vector types, a difference in qualifiers in the element
+/// types can make the vector types be considered not equal. For example,
+/// vector of 4 'const float' values vs vector of 4 'float' values.
+/// So we compare unqualified types of their elements and number of elements.
+/// See GitHub issue #155405.
```
Comment (shafik) [inline clang/lib/Sema/SemaChecking.cpp:15895]: We normally only refer to github issues in tests CC @erichkeane @AaronBallman

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -179,6 +179,10 @@ Non-comprehensive list of changes in this release
   Currently, the use of ``__builtin_dedup_pack`` is limited to template arguments and base
   specifiers, it also must be used within a template context.
 
+- Builtin elementwise operators now accept vector arguments that have different
+  qualifiers on their elements. For example, vector of 4 ``const float`` values
+  and vector of 4 ``float`` values.
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:184]:
```suggestion
- Builtin elementwise operators now accept vector arguments that have different
  qualifiers on their elements. For example, vector of 4 ``const float`` values
  and vector of 4 ``float`` values. (#GH155405)
```

Also, this is in the wrong section; please move it to ‘Bug Fixes in This Version’ below.

File: clang/lib/Sema/SemaChecking.cpp (hunk 5 above)
Comment (ckoparkar) [reply clang/lib/Sema/SemaChecking.cpp:15895]: I see. In that case I can remove this, I've already mentioned this in the test.

**Review by Sirraide — APPROVED** [review]

**Comment by ckoparkar** [comment]
Thanks everyone for reviewing :-)
