### PR TITLE
[BOLT] Gadget scanner: implement finer-grained --scanners=... argument

### LINKED ISSUE #170973: [BOLT] Gadget scanner: add finer-grained modes to `--scanners=` option
This issue is factored out of the discussion https://github.com/llvm/llvm-project/pull/131899#discussion_r2012073205. The existing `--scanners=` command line option defines three possible modes: `pacret`, `pauth` and `all` (technically, it is multiple choice):
* `pacret` only checks for non-protected returns
* `pauth` checks for any PAuth-related gadgets: those checked by `pacret` and additionally
  - tail calls performed with non-trusted address in LR
  - non-protected indirect calls
  - signing oracles (signing a pointer that is possibly attacker-controlled)
  - authentication oracles (authentication instructions whose success/fail result can be tested by the attacker without crashing the program)
* `all` is currently the same as `pauth`

Additionally, passing the `--auth-traps-on-failure` option disables the detection of authentication oracles completely and modifies the rules for other checkers.

It may be worth implementing a finer-grained control over which gadget kinds to search for.
* For example, a typical use case is to build programs with pac-ret protection enabled (which does not change the ABI, except maybe for requiring support in libunwind), but without signing function pointers (which is ABI-dependent). If this is the case, we should definitely disable "non-protected calls" check, but may or may not check for signing and authentication oracles.
* Whether we want to protect tail calls or not does not depend on the ABI, it is more of a security vs. performance trade-off. It is actually related to the `pacret` mode, but has to have a separate toggle.

Tagging @kbeyls, @jacobbramley.

### PR DESCRIPTION
**Pull request by atrosinenko**
Add separate options to enable each of the available gadget detectors. Furthermore, add two meta-options enabling all PtrAuth scanners and all available scanners of any type (which is only PtrAuth for now, though).

This commit renames `pacret` option to `ptrauth-pac-ret` and `pauth` to `ptrauth-all`.

Resolves #170973.

### CODE REVIEW

File: bolt/lib/Rewrite/RewriteInstance.cpp [hunk 1]
```diff
@@ -286,13 +286,23 @@ static cl::opt<bool> WriteBoltInfoSection(
...
+                   "Tail calls performed with unprotected link register"),
+        clEnumValN(GS_PTRAUTH_BRANCH_AND_CALL_TARGETS, "ptrauth-forward-cf",
+                   "Unprotected calls and branches (forward control-flow)"),
+        clEnumValN(GS_PTRAUTH_SIGN_ORACLES, "ptrauth-sign-oracles",
+                   "Signing of untrusted pointers (signing oracles)"),
+        clEnumValN(GS_PTRAUTH_AUTH_ORACLES, "ptrauth-auth-oracles",
+                   "Authentication oracles"),
+
+        clEnumValN(GS_PTRAUTH_ALL_MASK, "ptrauth-all",
+                   "All Pointer Authentication scanners"),
```
Comment (kbeyls) [inline bolt/lib/Rewrite/RewriteInstance.cpp]: Thank you, I like this patch :)
My only thought/comment is about the naming of the command line arguments.
My impression is that in most other places, we abbreviate "pointer authentication" to "pauth" rather than "ptrauth".
The AArch64 architecture extension family for pointer authentication is also called "FEAT_PAUTH_*".

To me it seems it would be more consistent to name these command line options `pauth-*` rather than `ptrauth-*` to keep naming more consistent.
Or maybe I haven't kept up well, and "ptrauth" is the most common abbreviation to refer to pointer authentication?

**Review by kbeyls — APPROVED** [review]

**Review by atrosinenko — COMMENTED** [review]
Trivial last minute cleanup (comments only).
