### PR TITLE
[libc] fix -Wshift-count-overflow in UInt.h

### LINKED ISSUE #74623: [libc] -Wshift-count-overflow in libc/src/__support/UInt.h
```
[692/693] Building CXX object projects/libc/src/stdio/prin...s/libc.src.stdio.printf_core.converter.dir/converter.cpp.o
In file included from /android0/llvm-project/libc/src/__support/UInt128.h:12,
                 from /android0/llvm-project/libc/src/__support/FPUtil/FloatProperties.h:12,
                 from /android0/llvm-project/libc/src/__support/FPUtil/FPBits.h:17,
                 from /android0/llvm-project/libc/src/stdio/printf_core/core_structs.h:13,
                 from /android0/llvm-project/libc/src/stdio/printf_core/converter.h:12,
                 from /android0/llvm-project/libc/src/stdio/printf_core/converter.cpp:9:
/android0/llvm-project/libc/src/__support/UInt.h: In instantiation of ‘constexpr __llvm_libc_18_0_0_git::cpp::BigInt<Bits, Signed>::operator T() const [with T = unsigned int; <template-parameter-2-2> = void; long unsigned int Bits = 320; bool Signed = false]’:
/android0/llvm-project/libc/src/__support/float_to_string.h:381:57:   required from here
/android0/llvm-project/libc/src/__support/UInt.h:125:53: warning: left shift count >= width of type [-Wshift-count-overflow]
  125 |       return static_cast<T>((static_cast<T>(val[1]) << 64) + lo);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```
I'm trying to get -Werror re-enabled in https://github.com/llvm/llvm-project/pull/74506; building with GCC flags the above warning.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Not that I'm very good at SFINAE, but it seems that conversion operators are
perhaps difficult to compose with SFINAE.  I saw an example that used one layer
of indirection to have an explicit return type that could then be used with
enable_if_t.

Link: https://stackoverflow.com/a/7604580
Fixes: #74623

### CODE REVIEW

File: libc/src/__support/UInt.h [hunk 1]
```diff
@@ -103,13 +103,20 @@ template <size_t Bits, bool Signed> struct BigInt {
       val[i] = words[i];
   }
 
-  template <typename T, typename = cpp::enable_if_t<cpp::is_integral_v<T> &&
-                                                    sizeof(T) <= 16 &&
-                                                    !cpp::is_same_v<T, bool>>>
-  LIBC_INLINE constexpr explicit operator T() const {
-    if constexpr (sizeof(T) <= 8)
-      return static_cast<T>(val[0]);
+  template <typename T> LIBC_INLINE constexpr explicit operator T() const {
```
Comment (michaelrj-google) [inline libc/src/__support/UInt.h:106]: does this template need any sort of limit (e.g. `enable_if_t<is_integral_v<T>>`)?

Comment (lntue) [reply libc/src/__support/UInt.h:106]: We don't need extra guard here, since it is already guarded with `to<T>()` templates.

**Review by lntue — APPROVED** [review]

File: libc/src/__support/UInt.h (hunk 1 above)
Comment (nickdesaulniers) [reply libc/src/__support/UInt.h:106]: yeah, if it doesn't fail here it will fail there.  I don't feel strongly either way, so merging for now.  If you feel strongly otherwise I'll send another patch to add that.
