### PR TITLE
[clang] Improve `_Alignas` on a `struct` declaration diagnostic

### LINKED ISSUE #58637: _Alignas on a struct declaration gives a low-quality diagnostic
```c
_Alignas(int) struct T {
  int i;
};
```
gives the diagnostic:  `warning: attribute '_Alignas' is ignored, place it after "struct" to apply attribute to type declaration` which seems like a really helpful message at first glance. However, C does not allow you to put an `_Alignas` specifier on the struct type itself. So following that advice:
```c
struct _Alignas(int) T {
  int i;
};
```
gives: `error: declaration of anonymous struct must be a definition` and `warning: declaration does not declare anything`.

The original diagnostic should say the attribute is ignored without the helpful message about placement (which is correct for C++).

### PR DESCRIPTION
**Pull request by jerinphilip**
Fixes https://github.com/llvm/llvm-project/issues/58637. 

Adds `isAlignas()` method on `AttributeCommonInfo` which accounts for
C++ `alignas` as well as C11 `_Alignas`.

The method is used to improve diagnostic in C when `_Alignas` is used in
C at the wrong location.  This corrects the previously suggested move
of `_Alignas` past the declaration specifier, now warns attribute
`_Alignas` is ignored.

Based on https://reviews.llvm.org/D141177.

### CODE REVIEW

**Comment by cor3ntin** [comment]
Generally looks good, thanks for working on this

I'd like to see more tests in `clang/test/Sema/alignas.c` - we don't have a test for `struct _Alignas(int)  T` either apparently.
Given this fixes a bug, it could benefit from a release note in `clang/docs/ReleaseNotes.rst`

**Comment by cor3ntin** [comment]
There is similar effort on Phab, we should pick one of them https://reviews.llvm.org/D141177

**Comment by AaronBallman** [comment]
> @AaronBallman you have a preference as to which PR we pursue?

No strong preference, but the author of D141177 seems to have gone silent again so if @jerinphilip is actively working on this patch, I'd say let's go with this one.

**Review by cor3ntin — COMMENTED** [review]
LGTM modulo nitpick.
Maybe @AaronBallman will want to look at it too.
Do we want a release notes for this?

File: clang/include/clang/Basic/AttributeCommonInfo.h [hunk 1]
```diff
@@ -186,14 +186,14 @@ class AttributeCommonInfo {
   bool isGNUScope() const;
   bool isClangScope() const;
 
-  bool isCXX11Attribute() const { return SyntaxUsed == AS_CXX11 || IsAlignas; }
-
+  bool isAlignas() const { return IsAlignas; }
+  bool isCXX11Attribute() const { return SyntaxUsed == AS_CXX11; }
```
Comment (AaronBallman) [inline clang/include/clang/Basic/AttributeCommonInfo.h:190]: This function was intended to tell you whether the attribute is a C++ attribute, and now it's changed to whether it's a C++ attribute spelled with `[[]]`. https://eel.is/c++draft/dcl.attr - note that `alignas` is an `attribute-specifier`. In C, `alignas` is *not* an attribute specifier (but it might become one someday) but is a kind of `declaration-specifier` instead.

I think it'd be better to keep this distinction, but I'll defer to @erichkeane if he has other opinions.

**Review by AaronBallman — COMMENTED** [review]
Thank you for working on this! I think the changes should come with a release note so users know about the fix. I did have a question on the design, but overall the direction seems sensible to me.

File: clang/include/clang/Basic/AttributeCommonInfo.h (hunk 1 above)
Comment (erichkeane) [reply clang/include/clang/Basic/AttributeCommonInfo.h:190]: I can see this both ways. It is typically used AFAIK as a 'is this a C++ spelling' despite not exactly meaning that.  On the other hand, as Aaron mentions, this is changing its meaning fairly significantly.  I'm still on the fence here.

File: clang/include/clang/Basic/AttributeCommonInfo.h [hunk 2]
```diff
@@ -186,14 +186,14 @@ class AttributeCommonInfo {
...
   bool isC23Attribute() const { return SyntaxUsed == AS_C23; }
 
   /// The attribute is spelled [[]] in either C or C++ mode, including standard
   /// attributes spelled with a keyword, like alignas.
   bool isStandardAttributeSyntax() const {
-    return isCXX11Attribute() || isC23Attribute();
+    return isCXX11Attribute() || isC23Attribute() || IsAlignas;
```
Comment (erichkeane) [inline clang/include/clang/Basic/AttributeCommonInfo.h:196]: So THIS one I definitely think shouldn't change.  BUT this shows another situation where `isCXX11Attribute` is being misused.

Comment (AaronBallman) [reply clang/include/clang/Basic/AttributeCommonInfo.h:196]: I think `isCXX11Attribute()` was being used properly there, at least per the comment. But you're right, this one now changed behavior in C23 because it will treat `_Alignas` as a standard attribute.

File: clang/include/clang/Basic/AttributeCommonInfo.h (hunk 1 above)
Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:190]: I realize there are backwards compatibility issues now (which I did not see before). Happy to defer to experts the decision.  I mostly went for a symptomatic treatment after I got failures since `kw_Alignas` was not added. Would it make sense to decompose `IsAlignAs` to `IsCXXAlignas || isCAlignAs` then? It'll bloat the code a bit but will allow retaining past behaviour by retaining the fine-grained information.

This is within an instance of an `AttributeCommonInfo` class and therefore an attribute, so I reasoned this is already an attribute - now these methods are intended to distinguish CXX or C is based on syntax.

Comment (AaronBallman) [reply clang/include/clang/Basic/AttributeCommonInfo.h:190]: I think the trouble is that we've got code like this: https://github.com/llvm/llvm-project/blob/eb14f47bf1ccfda500ba3c3092d70e269f6f0b56/clang/lib/Parse/ParseDeclCXX.cpp#L3062 where we're using "isCXX11Attribute()" to mean "attribute-specifier" as a grammar term and not `[[]]` syntax specifically.

As best I can tell, I think we're fine for `isAlignas()` to report true for both `alignas` and `_Alignas` spellings; we can distinguish between the C and C++ spellings by looking at the language options in force. WDYT @erichkeane?

File: clang/test/Parser/c2x-alignas.c [hunk 3]
```diff
@@ -0,0 +1,5 @@
+// RUN: %clang_cc1 -std=c23 -fsyntax-only -verify %s
+// RUN: not %clang_cc1 -std=c99 -pedantic -fsyntax-only %s 2>&1 | FileCheck -check-prefix=CHECK-EXT %s
+
+_Alignas(int) struct c1; // expected-warning {{attribute '_Alignas' before "struct" is ignored}}
+alignas(int) struct c1; // expected-warning {{attribute 'alignas' before "struct" is ignored}}
```
Comment (jerinphilip) [inline clang/test/Parser/c2x-alignas.c:5]: I tried to add a C23 test carrying over [D141177 (comment)](https://reviews.llvm.org/D141177#4606499_). The C23 test fails at the moment, because a CXX11 path is activated. My understanding is `alignas` being present pre C23 only in C++ has parse-paths that take the only C++ existence into consideration (from [isCXX11AttributeSpecifier](https://github.com/llvm/llvm-project/blob/041a786c78fbcee3537ca636bf796bb18fb6f313/clang/lib/Parse/ParseTentative.cpp#L740)). 

It ends up at https://github.com/llvm/llvm-project/blob/041a786c78fbcee3537ca636bf796bb18fb6f313/clang/include/clang/Parse/Parser.h#L2743 triggering the error messages to move it outward:
https://github.com/llvm/llvm-project/blob/041a786c78fbcee3537ca636bf796bb18fb6f313/clang/lib/Parse/ParseDecl.cpp#L1791

Is it possible to decouple C23 from this what this PR addresses?

Comment (AaronBallman) [reply clang/test/Parser/c2x-alignas.c:5]: > Is it possible to decouple C23 from this what this PR addresses?

Yeah, I think that's a good idea; there's plenty of moving parts here.

File: clang/include/clang/Basic/AttributeCommonInfo.h (hunk 1 above)
Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:190]: Trying to guess based on surroundings, the `AttributeCommonInfo::is<Method>(...)` corresponds consistently to [`Syntax`](https://github.com/llvm/llvm-project/blob/4345baaa02c5e2d27a727e8b2cf22d95b2842cd9/clang/include/clang/Basic/AttributeCommonInfo.h#L26-L27) enum save `isCXX11Attribute`, and assuming consistency is preferred a method with the name `isCXX11Attribute` should only tell if it corresponds to `AS_CXX11`, which is `[[ ]]` when C++ is used (consistent with `is{C23,GNU,Declspec,Microsoft,...}Attribute()`).

This function body appears to imply what is defined as `attribute-specifier` ([C++](https://eel.is/c++draft/dcl.attr#nt:attribute-specifier)) prior to this change. So it may be worth renaming this and such intended usages to `isCXXAttributeSpecifier() = [[]] | alignas(..) ` which can be inferred from this instance to improve.  

In the [C23-draft](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf) I picked off the Wikipedia page, `alignas` appears to be a _keyword_ part of an `alignment-specifier`, while `attribute-specifier` only includes `[[ ]]`. Common ancestor for `attribute-specifier`, `alignment-specifier` appears to be something called a `specifier-qualifier-list`. Based on the below details, I have a feeling it is okay to treat this as `isCAttributeSpecifier() == [[ ]] | alignas | _Alignas ` for practical purposes, moving the term `alignment-specifier` around. 

<details> <summary> C (grammar) </summary>

```
specifier-qualifier-list:
    type-specifier-qualifier attribute-specifier-sequence_opt
    type-specifier-qualifier specifier-qualifier-list
    
attribute-specifier-sequence:
    attribute-specifier-sequence_opt attribute-specifier

attribute-specifier:
    [[ attribute-list ]] 
    
type-specifier-qualifier:
    type-specifier
    type-qualifier
    alignment-specifier
    
alignment-specifier:
    alignas ( type-name )
    alignas ( constant-expression )
```
</details>

File: clang/include/clang/Basic/AttributeCommonInfo.h (hunk 2 above)
Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:196]: I've mentioned on discord this already, adding here to keep discussions consolidated. 

_Standard Attributes_ appear to be defined and documented in [C++](https://en.cppreference.com/w/cpp/language/attributes#Standard_attributes) and [C](https://en.cppreference.com/w/cpp/language/attributes#Standard_attributes) (See also [draft](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf), Page 141) as something different than the intended usage here making the clang terminology (`isStandardAttributeSyntax`) confusing. I realize I may be being pedantic about _naming this properly_, but I figure adding more information here should help synchronize and connect the implementation to the spec to take discussion forward. 

I'm not sure what this function intends at this stage, but I'm guessing a sane choice is `isCXX11AttributeSpecifier() || isC23AttributeSpecifier()`, including `_Alignas`.

File: clang/include/clang/Basic/AttributeCommonInfo.h [hunk 4]
```diff
@@ -94,7 +94,7 @@ class AttributeCommonInfo {
           IsRegularKeywordAttribute(IsRegularKeywordAttribute) {}
     constexpr Form(tok::TokenKind Tok)
         : SyntaxUsed(AS_Keyword), SpellingIndex(SpellingNotCalculated),
-          IsAlignas(Tok == tok::kw_alignas),
+          IsAlignas(Tok == tok::kw_alignas || Tok == tok::kw__Alignas),
```
Comment (jerinphilip) [inline clang/include/clang/Basic/AttributeCommonInfo.h:97]: Looking at the activated codepaths, `_Alignas` goes through this (attribute) infrastructure for C parsing as well, but fails to disambiguate the `_Alignas` vs `alignas` information at `isAlignAs` with this change. Ideas in https://github.com/llvm/llvm-project/pull/65638#discussion_r1367333111 requires retaining the distinction rather than mixing with an `||`.

Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:97]: If not mixed into `IsAlignAs`, the following can recover `_Alignas`, which [D141177](https://reviews.llvm.org/D141177) is relying on for a lesser invasive change. 

```cpp
getParsedKind() == AT_Aligned && isKeywordAttribute() && !IsAlignas;
```

This feels complicated, and potentially not future proof as in C23, `_Aligned` is an alternate spelling for `aligned`.

Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:97]: The other place to recover the `_Alignas` vs `alignas` is `SpellingIndex`. But the following (removed) comment still applies (regarding `SpellingIndex`):

[[clang] Reject non-declaration C++11 attributes on declarations](https://github.com/llvm/llvm-project/commit/8c7b64b5ae2a09027c38db969a04fc9ddd0cd6bb)

```cpp
    // FIXME: Use a better mechanism to determine this
    // We use this in `isCXX11Attribute` below, so it _should_ only return
    // true for the `alignas` spelling, but it currently also returns true
    // for the `_Alignas` spelling, which only exists in C11. Distinguishing
    // between the two is important because they behave differently:
    // - `alignas` may only appear in the attribute-specifier-seq before
    //   the decl-specifier-seq and is therefore associated with the
    //   declaration.
    // - `_Alignas` may appear anywhere within the declaration-specifiers
    //   and is therefore associated with the `DeclSpec`.
    // It's not clear how best to fix this:
    // - We have the necessary information in the form of the `SpellingIndex`,
    //   but we would need to compare against AlignedAttr::Keyword_alignas,
    //   and we can't depend on clang/AST/Attr.h here.
    // - We could test `getAttrName()->getName() == "alignas"`, but this is
    //   inefficient.
```

**Comment by jerinphilip** [comment]
I have rebased the PR with main (which appears to fix the formatting workflow). For the time being, I have left the C23 test using `alignas` in with the active error message and a `FIXME`.

I've altered the state of this PR to be close to [D141177](https://reviews.llvm.org/D141177), using the existing attribute warning for reduced complexity (happy to provide attribution). Key difference `isAlignas` instead of `isC23AlignasAttribute()`, thinking the former should be more future-proof. In the current state, `isCXX11Attribute()` and `isStandardAttributeSyntax()` is not modified, and the net improvement (in diagnostics) in changes here should be useful when C23 `alignas` comes in, I hope.

The following routes were also considered:

1. Store `tok::TokenKind` to resolve `_Alignas` vs `alignas`. This requires adding one more field to `Form` and `AttributeCommonInfo`, while the information is already present via (`IsAlignas`, `SpellingIndex`) tuple (This approach is in [jerinphilip/llvm-project#1](https://github.com/jerinphilip/llvm-project/pull/1) mixed with other things). 
2. Use `calculateAttributeSpellingIndex` (also discussed in meeting). This suffers from inability to use `AlignedAttr::Keyword_Alignas` (`clang/AST/Attrs.h`) - See [#65638 (comment)](https://github.com/llvm/llvm-project/pull/65638#discussion_r1367880789). Absent this, the `SpellingIndex` value `5` (`Keyword_Alignas`) will have to be maintained separately here to resolve `_Alignas`. Looking at the source requires string operations, which are inefficient.

File: clang/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -264,6 +264,11 @@ Attribute Changes in Clang
   supports but that are never the result of default argument promotion, such as
   ``float``. (`#59824: <https://github.com/llvm/llvm-project/issues/59824>`_)
 
+- Clang now warns you that the ``_Alignas`` attribute on declaration specifiers
+  is ignored, changed from the former incorrect suggestion to move it past
+  declaration specifiers.
+
```
Comment (AaronBallman) [inline clang/docs/ReleaseNotes.rst:270]:
```suggestion
  declaration specifiers.
  (#58637 <https://github.com/llvm/llvm-project/issues/58637>`_)
```

File: clang/lib/Sema/SemaDecl.cpp [hunk 6]
```diff
@@ -5339,16 +5339,22 @@ Decl *Sema::ParsedFreeStandingDeclSpec(Scope *S, AccessSpecifier AS,
...
+
+      auto EmitAttributeDiagnostic = [this, &DS](const ParsedAttr &AL) {
+        unsigned DiagnosticId;
+        if (AL.isAlignas() && !getLangOpts().CPlusPlus) {
+          DiagnosticId = diag::warn_attribute_ignored;
+        } else if (AL.isRegularKeywordAttribute()) {
+          DiagnosticId = diag::err_declspec_keyword_has_no_effect;
+        } else {
+          DiagnosticId = diag::warn_declspec_attribute_ignored;
+        }
```
Comment (AaronBallman) [inline clang/lib/Sema/SemaDecl.cpp:5351]:
```suggestion
        unsigned DiagnosticId = diag::warn_declspec_attribute_ignored;
        if (AL.isAlignas() && !getLangOpts().CPlusPlus)
          DiagnosticId = diag::warn_attribute_ignored;
        else if (AL.isRegularKeywordAttribute())
          DiagnosticId = diag::err_declspec_keyword_has_no_effect;
```
Changes for our odd choice coding style and to be slightly more succinct.

File: clang/test/Parser/cxx0x-attributes.cpp [hunk 7]
```diff
@@ -451,3 +451,5 @@ namespace P2361 {
                                  // expected-warning {{use of the 'deprecated' attribute is a C++14 extension}}
 [[nodiscard("\123")]] int b(); // expected-error{{invalid escape sequence '\123' in an unevaluated string literal}}
 }
+
+alignas(int) struct AlignAsAttribute {}; // expected-error {{misplaced attributes; expected attributes here}}
```
Comment (AaronBallman) [inline clang/test/Parser/cxx0x-attributes.cpp:455]: Note to other reviewers, this C++ test exhibits the same behavior on trunk already: https://godbolt.org/z/s5T3hfxsr

**Review by AaronBallman — COMMENTED** [review]
Aside from some nits, I think this looks reasonable to me. I'll leave the final sign-off to @erichkeane but if he doesn't approve in the next few days (WG21 meetings are upcoming so he may be busy), I'll come back to approve.

Thank you for all the help on this one! It turns out `good first issue` is really hard to determine accurately. ;-)

File: clang/include/clang/Basic/AttributeCommonInfo.h [hunk 8]
```diff
@@ -192,6 +192,13 @@ class AttributeCommonInfo {
 
   bool isC23Attribute() const { return SyntaxUsed == AS_C23; }
 
+  bool isAlignas() const {
+    // In the current state of code, IsAlignas is only configured to return
```
Comment (erichkeane) [inline clang/include/clang/Basic/AttributeCommonInfo.h:196]: This comment is immediately stale once we commit this, right?  Also, it refers to `IsAlignas`, but the function name is `isAlignas`.

**Review by erichkeane — COMMENTED** [review]
The comments Aaron made should be fixed, plus 1 more from me, else LGTM.

File: clang/include/clang/Basic/AttributeCommonInfo.h (hunk 8 above)
Comment (jerinphilip) [reply clang/include/clang/Basic/AttributeCommonInfo.h:196]: This refers to the variable `IsAlignAs` (not the parent function `isAlignas`), and the sentence holds for the current state of code. I believe I'm trying to explain why I cannot use `IsAlignas`'s current behaviour here (as it is more invasive). Normally I'd expect this function to be a `const` accessor to a private member per programming conventions, which is not the case here, hence a comment.

I'm sensing the review comment confusion indicates I need to communicate this better in source comments. Suggestions welcome.

Comment (AaronBallman) [reply clang/include/clang/Basic/AttributeCommonInfo.h:196]: How about:
```
// FIXME: In the current state, the IsAlignas member variable is only true with the C++
// `alignas` keyword but not `_Alignas`. The following expression works around the
// otherwise lost information so it will return true for `alignas` or `_Alignas` while still
// returning false for things like `__attribute__((aligned))`.
```

**Review by AaronBallman — APPROVED** [review]
LGTM! Thank you for the fix!
