### PR TITLE
[AST] Ensure getRawCommentsForAnyRedecl() does not miss any redecl with a comment

### LINKED ISSUE #108145: getRawCommentForAnyRedecl can fail to return definition comment
While working on a clangd enhancement (https://github.com/llvm/llvm-project/pull/67802), @ckandeler and I have run into what I believe is a bug in `ASTContext::getRawCommentForAnyRedecl()`: when called on the **definition** of a function or class, it can fail to return the comment above the definition (i.e. incorrectly return null instead), if it was previously called on a (non-defining) declaration at a time when the definition wasn't yet added to the redecl chain.

I wrote a (failing) unit test demonstrating the issue at https://github.com/HighCommander4/llvm-project/commit/99330759463a902e16b0d5976557077b6e06c938.

The bug is a regression from https://github.com/llvm/llvm-project/commit/f31d8df1c8c69e7a787c1c1c529a524f3001c66a, which introduced the cache `CommentlessRedeclChains` and related data structures. (I verified this with a local backout of the patch, which makes my unit test pass.)

@jkorous-apple and @gribozavr, as author and reviewer of the regressing patch, could you advise what an appropriate fix would be?

---

Here are some more details regarding the bug:

The failing unit test processes the following code:

```c++
void f();

// f is the best
void f() {}
```

with an `ASTConsumer` that calls `ASTContext::getRawCommentForAnyRedecl()` as soon as a declaration is parsed and given to the consumer.

(I assume this is a valid use of `getRawCommentForAnyRedecl()`, i.e. it's not the intention to require that the function only be called once the whole AST is built, otherwise I don't see what would be the purpose of having caches like `CommentlessRedeclChains` at all. Please let me know if I misunderstood.)

When `getRawCommentForAnyRedecl()` is first called, for the non-defining declaration of `f()`, the definition has not been parsed and added to the redecl chain yet. This results in `CommentslessRedeclChains` containing an entry mapping this declaration to itself [here](https://searchfox.org/llvm/rev/b0ffaa79050460d724eec1b12363c439b43d5ae5/clang/lib/AST/ASTContext.cpp#464).

When the function is called a second time for the definition of `f()`, the redecl chain of that contains itself (the definition) as the first element, and the non-defining declaration as the second. The previously stored mapping is looked up [here](https://searchfox.org/llvm/rev/b0ffaa79050460d724eec1b12363c439b43d5ae5/clang/lib/AST/ASTContext.cpp#445), and results in the loop skipping the definition [here](https://searchfox.org/llvm/rev/b0ffaa79050460d724eec1b12363c439b43d5ae5/clang/lib/AST/ASTContext.cpp#455), and therefore never checking the definition for a comment.

Based on the above debugging, I don't quite understand how this caching mechanism is supposed to work.

### PR DESCRIPTION
**Pull request by HighCommander4**
The previous implementation had a bug where, if it was called on a Decl later in the redecl chain than `LastCheckedDecl`, it could incorrectly skip and overlook a Decl with a comment.
    
The patch addresses this by only using `LastCheckedDecl` if the input Decl `D` is on the path from the first (canonical) Decl to `LastCheckedDecl`.
    
An alternative that was considered was to start the iteration from the (canonical) Decl, however this ran into problems with the modelling of explicit template specializations in the AST where the canonical Decl can be unusual. With the current solution, if no Decls were checked yet, we prefer to check the input Decl over the canonical one.

Fixes https://github.com/llvm/llvm-project/issues/108145

### CODE REVIEW

**Comment by HighCommander4** [comment]
Buildkite is showing the test `Clang :: Index/comment-to-html-xml-conversion.cpp` failing. Will investigate.

**Comment by HighCommander4** [comment]
> Buildkite is showing the test `Clang :: Index/comment-to-html-xml-conversion.cpp` failing. Will investigate.

I've been investigating this failure. It's caused by a slight change of behaviour of `ASTContext::getFullComment()` on explicit function template specializations, such as:

```c++
/// Aaa.
template<typename T, typename U>
void foo(T aaa, U bbb);

/// Bbb.
template<>
void foo(int aaa, int bbb);
```

While the correct comment (`// Bbb.`) is found for the explicit specialization, the returned `FullComment`'s `DeclInfo` does not have its [`TemplateKind`](https://searchfox.org/llvm/rev/3ae71d154e5dfb5e5a5d27b3699b27ce2b55f44d/clang/include/clang/AST/Comment.h#1047) set to `TemplateSpecialization` as expected.

This is in turn because the [code that sets this](https://searchfox.org/llvm/rev/3ae71d154e5dfb5e5a5d27b3699b27ce2b55f44d/clang/lib/AST/Comment.cpp#238-243) is conditioned on `FunctionDecl::getNumTemplateParameterLists() != 0`.

When `getRawCommentForAnyRedecl()` is called on the `FunctionDecl` for the explicit specialization (whose `getNumTemplateParameterLists()` returns 1), it previously returned the input `FunctionDecl` in its `OriginalDecl` out-parameter, but as a result of my change, it now returns the input decl's canonical decl, whose `getNumTemplateParameterLists()` returns 0, and it's this latter decl that ends up in the check mentioned above.

I'm not familiar enough with the AST modeling of template specializations to say what is going wrong here... @gribozavr as the author of the [mentioned check](https://searchfox.org/llvm/rev/3ae71d154e5dfb5e5a5d27b3699b27ce2b55f44d/clang/lib/AST/Comment.cpp#238-243), any advice would be appreciated.

**Comment by zyn0217** [comment]
> This is in turn because the [code that sets this](https://searchfox.org/llvm/rev/3ae71d154e5dfb5e5a5d27b3699b27ce2b55f44d/clang/lib/AST/Comment.cpp#238-243) is conditioned on FunctionDecl::getNumTemplateParameterLists() != 0.

I was curious why it is relying on `getNumTemplateParameterLists()`. To my understanding, it should call `FD->getTemplateSpecializationInfo()`, shouldn't it?

**Comment by zyn0217** [comment]
@HighCommander4 
I extended your test case a little to validate the `TemplateDeclKind` we would have.
```cpp
struct FoundComment {
  std::string DeclName;
  bool IsDefinition;
  std::string Comment;
  comments::DeclInfo::TemplateDeclKind TDK;
  // ... comparators are snipped ...
};
```
```cpp
  Action.Comments.push_back(FoundComment{
    ND->getNameAsString(), IsDefinition(D),
    RC ? RC->getRawText(Ctx.getSourceManager()).str() : "",
    RC->parse(Ctx, &Action.getCompilerInstance().getPreprocessor(), D)
         ->getDeclInfo()
         ->getTemplateKind()});
```

So for the following test case,
```cpp
  /// Aaa.
  template<typename T, typename U>
  void foo(T aaa, U bbb);

  /// Bbb.
  template<>
  void foo(int aaa, int bbb);
```

I didn't see the following failing
```cpp
  EXPECT_THAT(
      Comments,
      testing::ElementsAre(
          FoundComment{"foo", false, "/// Aaa.",
                       comments::DeclInfo::TemplateDeclKind::Template},
          FoundComment{
              "foo", false, "/// Bbb.",
              comments::DeclInfo::TemplateDeclKind::TemplateSpecialization}));
```

Did I misread anything from your last comment?

**Comment by zyn0217** [comment]
So the problem is that we would have another implicitly-created explicit template specialization `foo<int, int>` in the process of the DeduceTemplateArguments, and that specialization would share the same `FunctionTemplateSpecializationInfo` with the eventual template specialization that ends up being `D` in the `getRawCommentForAnyRedecl`, while the implicitly-created specialization would

1) have the explicit specialization flag set in `CheckFunctionTemplateSpecialization`
2) become the previous declaration of the last explicit specialization
3) have no `ExtInfo` set so one cannot get any template parameters from it.

So the status-quo is seemingly violating the contracts of `NumTemplParamLists` / `TemplParamLists` in light of their intents.

The `TemplateParameterList` would be attached to the newly created explicit specialization prior to the call to `CheckFunctionTemplateSpecialization()`, so one solution (which essentially preserves the ExtInfo in the implicitly-created specialization) is to add the following to `CheckFunctionTemplateSpecialization(),` in the code block below the comment.

```cpp
// Mark the prior declaration as an explicit specialization, so that later
// clients know that this is an explicit specialization.
```

```cpp
SmallVector<TemplateParameterList *, 4> TPL;
for (unsigned I = 0; I < FD->getNumTemplateParameterLists(); ++I)
  TPL.push_back(FD->getTemplateParameterList(I));
Specialization->setTemplateParameterListsInfo(Context, TPL);
```

An alternative might be to teach `DeclInfo::fill()` not to rely on `getNumTemplateParameterLists()`, but that way we still lack the `TemplateParameterList`.

**Comment by HighCommander4** [comment]
@zyn0217 Thank you for the analysis and suggestion! I updated the patch as suggested, let's see what buildkite says.

**Comment by HighCommander4** [comment]
Hmm, quite a few things are failing:

```
Failed Tests (14):
  Clang :: CXX/drs/cwg28xx.cpp
  Clang :: CXX/drs/cwg7xx.cpp
  Clang :: CXX/temp/temp.spec/temp.expl.spec/p2-20.cpp
  Clang :: CXX/temp/temp.spec/temp.expl.spec/p8.cpp
  Clang :: Index/index-file.cpp
  Clang :: PCH/cxx-ms-function-specialization-class-scope.cpp
  Clang :: PCH/cxx-templates.cpp
  Clang :: SemaCXX/ms-exception-spec.cpp
  Clang :: SemaTemplate/explicit-specialization-member.cpp
  Clang :: SemaTemplate/function-template-specialization.cpp
  Clang :: SemaTemplate/instantiate-member-specialization.cpp
  Clang :: SemaTemplate/member-specialization.cpp
  Clang :: SemaTemplate/ms-function-specialization-class-scope.cpp
  Clangd Unit Tests :: ./ClangdTests/DefineInlineTest/AddInline
```

**Comment by HighCommander4** [comment]
@zyn0217 I've debugged the `DefineInlineTest.AddInline` failure with your new suggested change, it concerns the following scenario:

header.h
```c++
template <typename T> void foo();
template <> void foo<int>();
```

source.cpp:
```c++
#include "header.h"
template <> void foo<int>() {}
```

It seems the `FuntionDecl` for the explicit specialization declaration in the header file gets assigned the template parameter lists of the definition in the main file, and its `getBeginLoc()` starts returning the main-file location.

File: clang/lib/AST/ASTContext.cpp [hunk 1]
```diff
@@ -444,7 +444,7 @@ const RawComment *ASTContext::getRawCommentForAnyRedecl(
     return CommentlessRedeclChains.lookup(CanonicalD);
   }();
 
-  for (const auto Redecl : D->redecls()) {
+  for (const auto Redecl : CanonicalD->redecls()) {
```
Comment (zyn0217) [inline clang/lib/AST/ASTContext.cpp:447]: I reread your analysis and I think the only safe usage of `getRawCommentForAnyRedecl()` previously was that, in the second call to the function, only those `D`s that live in between the `CanonicalDecl` and `LastCheckedRedecl` are expected to be used as the starting point of the traversal. Otherwise, the presence of `LastCheckedRedecl` would result in skipping over all declarations, including those whose associated comments were unparsed yet.

So I wonder if we could make use of LastCheckedRedecl opt-in. To be clear, we first check if `D` is in the path `Canonical` -> `LastCheckedRedecl`. If so, we use the mechanism that skips past every visited declaration; otherwise, we ignore it.

```cpp
// Any redeclarations of D that we haven't checked for comments yet?
const Decl *LastCheckedRedecl = CommentlessRedeclChains.lookup(CanonicalD);
bool CanUseCommentlessCache = false;
if (LastCheckedRedecl) {
  for (auto *Redecl : CanonicalD->redecls()) {
    if (Redecl == D) {
      CanUseCommentlessCache = true;
      break;
    }
    if (Redecl == LastCheckedRedecl)
      break;
   }
}
```

```cpp
// Skip all redeclarations that have been checked previously.
if (CanUseCommentlessCache && LastCheckedRedecl)
  ...
```

The solution could be improved to pick up the `LastCheckedRedecl` again after visiting the `CanonicalDecl`, though.

Comment (HighCommander4) [reply clang/lib/AST/ASTContext.cpp]: Thank you for the suggestion! It indeed feels safer to tweak `getRawCommentsForAnyRedecl()` like this than to muck around with the modeling of template specializations :laughing:

**Comment by HighCommander4** [comment]
Buildkite is green with this approach! Graduated patch from "Draft" state.

File: clang/lib/AST/ASTContext.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/AST/ASTContext.cpp]: Yeah, but I still feel the modeling of template specializations should be improved regarding `getSourceRange()` relying on `TemplateParameterListsInfo`, which is really peculiar. But that's another murky topic unrelated to this patch, anyway.

Comment (HighCommander4) [reply clang/lib/AST/ASTContext.cpp]: > regarding `getSourceRange()` relying on `TemplateParameterListsInfo`, which is really peculiar

FWIW, that part actually makes sense to me. For a function/method declaration that looks like this:

```
template <...>
ReturnType FunctionName(Parameters...);
```

the answer to the question "where does the source range begin?" is indeed "if there is a template parameter list, where does it begin?"

Comment (HighCommander4) [reply clang/lib/AST/ASTContext.cpp]: (The part that makes less sense to me is, why does the explicit specialization have a redeclaration at all in a case like

```c++
/// Aaa.
template<typename T, typename U>
void foo(T aaa, U bbb);

/// Bbb.
template<>
void foo(int aaa, int bbb);
```

There is only one declaration in the code.)

**Review by zyn0217 — APPROVED** [review]
Thanks for working on this! I think this probably needs a release note, otherwise it looks good on the whole.

Please give other folks some time before merging it, and I invited @AaronBallman for the second pair of eyes.

File: clang/lib/AST/ASTContext.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/AST/ASTContext.cpp]: Yup, in fact, I think we're not too confident about how many FunctionDecls would be generated during the template parsing e.g. they can be the byproducts of a TreeTransform/the process of the template argument deduction, such that the contract of `TemplateParameterListsInfo` would be less reliable.

File: clang/lib/AST/ASTContext.cpp [hunk 2]
```diff
@@ -440,14 +440,23 @@ const RawComment *ASTContext::getRawCommentForAnyRedecl(
...
+  if (LastCheckedRedecl) {
+    for (auto *Redecl : CanonicalD->redecls()) {
+      if (Redecl == D) {
+        CanUseCommentlessCache = true;
+        break;
+      }
+      if (Redecl == LastCheckedRedecl)
+        break;
+    }
+  }
```
[the remark this answers is not in the document]
Comment (AaronBallman) [reply clang/lib/AST/ASTContext.cpp:454]: I was thinking something similar -- let `LastCheckedRedecl == nullptr` be the test for `CanUseCommentlessCache` instead of using a dedicated variable for that.

**Review by AaronBallman — COMMENTED** [review]
Thanks for the fix! The changes should also come with a release note so users know about the improvement. Otherwise, changes basically LG modulo nits.

File: clang/lib/AST/ASTContext.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (HighCommander4) [reply clang/lib/AST/ASTContext.cpp]: Done, thanks

File: clang/unittests/AST/RawCommentForDeclTest.cpp [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+  std::vector<FoundComment> &Comments;
+
+private:
+  class Consumer : public clang::ASTConsumer {
+  private:
+    CollectCommentsAction &Action;
+
+  public:
+    Consumer(CollectCommentsAction &Action) : Action(Action) {}
+    ~Consumer() override {}
```
[the remark this answers is not in the document]
Comment (HighCommander4) [reply clang/unittests/AST/RawCommentForDeclTest.cpp]: The implicitly generated one does work. I think I just copied this from an existing test which had it. Removed now.

**Comment by HighCommander4** [comment]
Thanks for the reviews! I'll add the release note shortly (need to update to a newer baseline first).

**Comment by HighCommander4** [comment]
Note, I also updated the commit message to reflect the new fix approach.

**Comment by HighCommander4** [comment]
(Rebased)

**Comment by HighCommander4** [comment]
Added release note. I put it under "Bug Fixes to AST Handling" which seemed like a good fit.

**Review by zyn0217 — APPROVED** [review]
