### PR TITLE
[VectorCombine] Fold "shuffle (binop (shuffle, shuffle)), undef" --> "binop (shuffle), (shuffle)"

### LINKED ISSUE #49736: Compiler no longer producing single horizontal add instruction after ab2c499d
|  |  |
| --- | --- |
| Bugzilla Link | [50392](https://llvm.org/bz50392) |
| Version | trunk |
| OS | All |
| CC | @alexey-bataev,@anton-afanasyev,@RKSimon |

## Extended Description 
One of our internal tests compiles the following code and verifies that it generates a horizontal add instruction in the resulting assembly when optimizations are enabled and targeting btver2.
```
__attribute__((noinline))
__m256d add_pd_002(__m256d a, __m256d b) {
  __m256d r = (__m256d){ a[0] + a[1], a[2] + a[3], b[0] + b[1], b[2] + b[3] };
  return __builtin_shufflevector(r, a, 0, -1, 2, 3);
}
```
Prior to commit ab2c499, when compiled with "-g0 -O3 -march=btver2", the compiler would produce the following code:
```
        vinsertf128     $1, %xmm1, %ymm0, %ymm0
        vhaddpd %ymm1, %ymm0, %ymm0
```
But following the mentioned change, the compiler is now producing the following code instead:
```
        vextractf128    $1, %ymm1, %xmm2
        vhaddpd %xmm0, %xmm0, %xmm0
        vhaddpd %xmm2, %xmm1, %xmm1
        vperm2f128      $2, %ymm0, %ymm1, %ymm0 # ymm0 = ymm0[0,1],ymm1[0,1]
```

### LINKED ISSUE #94546: Regression in code quality for horizontal add after 70a54bca6f
We have an internal test which tests whether the compiler generates horizontal add instructions for certain cases. Recently we noticed that one of the cases, the code generated seems to have gotten worse after a recent change 70a54bca6f.

Consider the following code:
```c++
__attribute__((noinline))
__m256d add_pd_004(__m256d a, __m256d b) {
  __m256d r = (__m256d){ a[0] + a[1], a[2] + a[3], b[0] + b[1], b[2] + b[3] };
  return __builtin_shufflevector(r, a, 0, -1, -1, 3);
}
```
If compiled with optimizations targeting btver2 (`-S -O2 -march=btver2`), the compiler previously generated the following code:
```
        vhaddpd ymm0, ymm0, ymm1
        ret
```
But after 70a54bca6f, the compiler now is generating worse code:
```
        vextractf128    xmm1, ymm1, 1
        vhaddpd xmm0, xmm0, xmm1
        vinsertf128     ymm0, ymm0, xmm0, 1
        ret
```
@alexey-bataev, this was your change, can you take a look to see if there is a way we can avoid the regression in code quality in this case?

### PR DESCRIPTION
**Pull request by RKSimon**
Add foldPermuteOfBinops - to fold a permute (single source shuffle) through a binary op that is being fed by other shuffles.

Fixes #94546
Fixes #49736

### CODE REVIEW

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 1]
```diff
@@ -1400,6 +1401,92 @@ bool VectorCombine::scalarizeLoadExtract(Instruction &I) {
   return true;
 }
 
+/// Try to fold "shuffle (binop (shuffle, shuffle)), undef" into "binop (shuffle), (shuffle)".
+bool VectorCombine::foldPermuteOfBinops(Instruction &I) {
+  BinaryOperator *BinOp;
+  ArrayRef<int> OuterMask;
+  if (!match(&I,
+             m_Shuffle(m_OneUse(m_BinOp(BinOp)), m_Undef(), m_Mask(OuterMask))))
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1409]: I think need to check that OuterMask operates on a `binop` only, does not permute with undef value

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 2]
```diff
@@ -1400,6 +1401,92 @@ bool VectorCombine::scalarizeLoadExtract(Instruction &I) {
...
+  auto *BinOpTy = dyn_cast<FixedVectorType>(BinOp->getType());
+  auto *Op0Ty = dyn_cast<FixedVectorType>(Op00->getType());
+  auto *Op1Ty = dyn_cast<FixedVectorType>(Op10->getType());
+  if (!ShuffleDstTy || !BinOpTy || !Op0Ty || !Op1Ty)
+    return false;
+
+  unsigned NumSrcElts = BinOpTy->getNumElements();
+
+  // Don't accept shuffles that reference the second (undef/poison) operand.
+  if (any_of(OuterMask, [NumSrcElts](int M) { return M >= (int)NumSrcElts; }))
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1439]: I think it is safe to do this permutation with poison

Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1440]: Yes, we can enable this for non-intdiv cases

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 3]
```diff
@@ -1400,6 +1401,100 @@ bool VectorCombine::scalarizeLoadExtract(Instruction &I) {
...
+  auto *Op1Ty = dyn_cast<FixedVectorType>(Op10->getType());
+  if (!ShuffleDstTy || !BinOpTy || !Op0Ty || !Op1Ty)
+    return false;
+
+  unsigned NumSrcElts = BinOpTy->getNumElements();
+
+  // Don't accept shuffles that reference the second (undef/poison) operand in
+  // div/rem..
+  if (BinOp->isIntDivRem() &&
+      any_of(OuterMask, [NumSrcElts](int M) { return M >= (int)NumSrcElts; }))
```
Comment (alexey-bataev) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1442]: I think you need to check that the second shuffled value is poison, not undef. For undef it might be unsafe

Comment (RKSimon) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1442]: This will prevent the folds for DivRem with both Undef/Poison - using the m_Undef() match in the m_Shuffle() above - is that not enough?

Comment (alexey-bataev) [reply llvm/lib/Transforms/Vectorize/VectorCombine.cpp:1442]: m_Undef checks for both undef and poison, I assume. You can safely drop this for poison only, for undefs need to check the the first operand does not produce poisons, I think

**Review by alexey-bataev — APPROVED** [review]
LG
