### PR TITLE
[Diagnostics] Return rvalue reference from temporary argument

### LINKED ISSUE #105778: [IR]: Bug - dangling reference
```
/llvm-project/llvm/include/llvm/IR/DiagnosticInfo.h:584:10: error: cannot bind non-const lvalue reference of type 'llvm::OptimizationRemarkMissed&' to an rvalue of type 'llvm::OptimizationRemarkMissed'     
```

### PR DESCRIPTION
**Pull request by hahnjo**
This fixes compilation issues with GCC and C++23:
```
error: cannot bind non-const lvalue reference of type
'llvm::OptimizationRemarkMissed&' to an rvalue of type
'llvm::OptimizationRemarkMissed'
```

Closes #105778

### CODE REVIEW

File: llvm/include/llvm/Analysis/OptimizationRemarkEmitter.h [hunk 1]
```diff
@@ -69,6 +69,11 @@ class OptimizationRemarkEmitter {
   /// Output the remark via the diagnostic handler and to the
   /// optimization record file.
   void emit(DiagnosticInfoOptimizationBase &OptDiag);
+  /// Also allow r-value for OptDiag to allow emitting a temporarily-constructed
+  /// diagnostic.
+  void emit(DiagnosticInfoOptimizationBase &&OptDiag) {
+    emit(static_cast<DiagnosticInfoOptimizationBase &>(OptDiag));
```
Comment (dwblaikie) [inline llvm/include/llvm/Analysis/OptimizationRemarkEmitter.h:75]: Is the cast needed here? (eg: https://godbolt.org/z/rT8xnzfn3 )

**Review by dwblaikie — APPROVED** [review]
Looks like OK changes.

I wouldn't mind a unit test for something low level/broadly used like this, but wouldn't insist on it.

File: llvm/include/llvm/Analysis/OptimizationRemarkEmitter.h (hunk 1 above)
Comment (hahnjo) [reply llvm/include/llvm/Analysis/OptimizationRemarkEmitter.h]: No, it's not once we have an r-value. Removed.

**Comment by hahnjo** [comment]
> I wouldn't mind a unit test for something low level/broadly used like this, but wouldn't insist on it.

I generally agree, but unfortunately there is none for `OptimizationRemarkEmitter` and I'm not really familiar with the code (just trying to address compilation errors when experimenting with C++23) :anguished:

File: llvm/include/llvm/IR/DiagnosticInfo.h [hunk 2]
```diff
@@ -625,14 +626,14 @@ operator<<(RemarkT &R,
...
-RemarkT &
+RemarkT &&
 operator<<(RemarkT &&R,
            std::enable_if_t<
                std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
                StringRef>
                S) {
   R.insert(S);
-  return R;
+  return std::move(R);
```
Comment (kuhar) [inline llvm/include/llvm/IR/DiagnosticInfo.h:636]: How do we know that this is actually an rvalue reference? Seems like plain references (or const references) could also bind to `R` since `RemarkT` is a template argument and I'd expect the usual reference collapsing rules to apply.

Shouldn't this use `std::forward<RemarkT>(R)` instead?

Comment (hahnjo) [reply llvm/include/llvm/IR/DiagnosticInfo.h:636]: Not really a C++ language lawyer, but I think if the first argument can bind to an lvalue reference, the compiler should select the other overload a couple of lines up, no? I can still use `std::forward` if that's more appropriate than `std::move` here.

Comment (kuhar) [reply llvm/include/llvm/IR/DiagnosticInfo.h:636]: Then we should be able to handle both cases by dropping the other one and making this use `std::forward`.

Comment (hahnjo) [reply llvm/include/llvm/IR/DiagnosticInfo.h:636]: I thought so too, but I cannot get it to work. I tried
```diff
diff --git a/llvm/include/llvm/IR/DiagnosticInfo.h b/llvm/include/llvm/IR/DiagnosticInfo.h
index 1e26cfdd17b5..9f77e7de68e1 100644
--- a/llvm/include/llvm/IR/DiagnosticInfo.h
+++ b/llvm/include/llvm/IR/DiagnosticInfo.h
@@ -613,27 +613,14 @@ protected:
 /// common base class.  This allows returning the result of the insertion
 /// directly by value, e.g. return OptimizationRemarkAnalysis(...) << "blah".
 template <class RemarkT>
-RemarkT &
-operator<<(RemarkT &R,
-           std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
-               StringRef>
-               S) {
-  R.insert(S);
-  return R;
-}
-
-/// Also allow r-value for the remark to allow insertion into a
-/// temporarily-constructed remark.
-template <class RemarkT>
-RemarkT &&
+auto
 operator<<(RemarkT &&R,
            std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
+               std::is_base_of<DiagnosticInfoOptimizationBase, std::remove_reference_t<RemarkT>>::value,
                StringRef>
                S) {
   R.insert(S);
-  return std::move(R);
+  return std::forward<RemarkT>(R);
 }
 
 template <class RemarkT>
```
but Clang says:
```
/code/LLVM/patches/llvm/include/llvm/IR/DiagnosticInfo.h:623:10: error: allocating an object of abstract class type 'llvm::DiagnosticInfoIROptimization'                                                                                      
  623 |   return std::forward<RemarkT>(R);                                                                                                                                                                                                    
      |          ^                                                                                                                                                                                                                            
/code/LLVM/patches/llvm/include/llvm/IR/DiagnosticInfo.h:728:11: note: in instantiation of function template specialization 'llvm::operator<<<llvm::DiagnosticInfoIROptimization &>' requested here                                           
  728 |     *this << Prepend;                                                                                                                                                                                                                 
      |           ^                                                                                                                                                                                                                           
/code/LLVM/patches/llvm/include/llvm/IR/DiagnosticInfo.h:551:16: note: unimplemented pure virtual method 'isEnabled' in 'DiagnosticInfoIROptimization'                                                                                        
  551 |   virtual bool isEnabled() const = 0;                                                                                                                                                                                                 
      |                ^
```

Unless there is a very obvious mistake / solution, I think this also gets out of scope for this PR which was "just" trying to resolve a compilation issue. If you don't mind, I would prefer landing this in its current form and future improvements can be tackled by the respective maintainer / people with more C++ skill than me.

Comment (zero9178) [reply llvm/include/llvm/IR/DiagnosticInfo.h:636]: Try using `decltype(auto)` as return value rather than `auto`. The latter drops references from the type deduction, meaning it tries to copy or move construct an object of type `RemarkT`.

Comment (hahnjo) [reply llvm/include/llvm/IR/DiagnosticInfo.h:636]: > Try using `decltype(auto)` as return value rather than `auto`. The latter drops references from the type deduction, meaning it tries to copy or move construct an object of type `RemarkT`.

Thanks, that works. And thanks for the explanation, I didn't know / remember that detail.

File: llvm/include/llvm/IR/DiagnosticInfo.h [hunk 3]
```diff
@@ -613,93 +613,47 @@ class DiagnosticInfoOptimizationBase : public DiagnosticInfoWithLocationBase {
...
-RemarkT &
-operator<<(RemarkT &R,
-           std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
-               StringRef>
-               S) {
+decltype(auto) operator<<(
+    RemarkT &&R,
+    std::enable_if_t<std::is_base_of<DiagnosticInfoOptimizationBase,
+                                     std::remove_reference_t<RemarkT>>::value,
```
Comment (kuhar) [inline llvm/include/llvm/IR/DiagnosticInfo.h:619]:
```suggestion
    std::enable_if_t<std::is_base_of_v<DiagnosticInfoOptimizationBase,
                                     std::remove_reference_t<RemarkT>>,
```

File: llvm/include/llvm/IR/DiagnosticInfo.h [hunk 4]
```diff
@@ -613,93 +613,47 @@ class DiagnosticInfoOptimizationBase : public DiagnosticInfoWithLocationBase {
...
-RemarkT &&
-operator<<(RemarkT &&R,
-           std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
-               DiagnosticInfoOptimizationBase::Argument>
-               A) {
+decltype(auto) operator<<(
+    RemarkT &&R,
+    std::enable_if_t<std::is_base_of<DiagnosticInfoOptimizationBase,
+                                     std::remove_reference_t<RemarkT>>::value,
```
Comment (kuhar) [inline llvm/include/llvm/IR/DiagnosticInfo.h:630]:
```suggestion
    std::enable_if_t<std::is_base_of_v<DiagnosticInfoOptimizationBase,
                                     std::remove_reference_t<RemarkT>>,
```

File: llvm/include/llvm/IR/DiagnosticInfo.h [hunk 5]
```diff
@@ -613,93 +613,47 @@ class DiagnosticInfoOptimizationBase : public DiagnosticInfoWithLocationBase {
...
-RemarkT &
-operator<<(RemarkT &R,
-           std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
-               DiagnosticInfoOptimizationBase::setIsVerbose>
-               V) {
+decltype(auto) operator<<(
+    RemarkT &&R,
+    std::enable_if_t<std::is_base_of<DiagnosticInfoOptimizationBase,
+                                     std::remove_reference_t<RemarkT>>::value,
```
Comment (kuhar) [inline llvm/include/llvm/IR/DiagnosticInfo.h:641]:
```suggestion
    std::enable_if_t<std::is_base_of_v<DiagnosticInfoOptimizationBase,
                                     std::remove_reference_t<RemarkT>>,
```

File: llvm/include/llvm/IR/DiagnosticInfo.h [hunk 6]
```diff
@@ -613,93 +613,47 @@ class DiagnosticInfoOptimizationBase : public DiagnosticInfoWithLocationBase {
...
-RemarkT &&
-operator<<(RemarkT &&R,
-           std::enable_if_t<
-               std::is_base_of<DiagnosticInfoOptimizationBase, RemarkT>::value,
-               DiagnosticInfoOptimizationBase::setExtraArgs>
-               EA) {
+decltype(auto) operator<<(
+    RemarkT &&R,
+    std::enable_if_t<std::is_base_of<DiagnosticInfoOptimizationBase,
+                                     std::remove_reference_t<RemarkT>>::value,
```
Comment (kuhar) [inline llvm/include/llvm/IR/DiagnosticInfo.h:652]:
```suggestion
    std::enable_if_t<std::is_base_of_v<DiagnosticInfoOptimizationBase,
                                     std::remove_reference_t<RemarkT>>,
```

**Review by kuhar — APPROVED** [review]
LGTM % nit

**Comment by hahnjo** [comment]
@arsenm thanks for merging. However, for future changes I would prefer to do this myself, both to decide on the author email address (work or private; this merge got it right because I contributed privately outside of work hours) and to make sure I'm available to respond to any issues reported by the bots...
