### PR TITLE
[llvm-objcopy] Fix file offsets when PT_INTERP/PT_LOAD offsets are equal

### LINKED ISSUE #79887: llvm-objcopy produces wrong `p_offset` when PT_INTERP/PT_LOAD offsets are equal
Considering the following layout
```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x000268 0x000268 R   0x8
  INTERP         0x195000 0x0000000000195000 0x0000000000195000 0x00000f 0x00000f R   0x1
      [Requesting program interpreter: ]
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x1948c9 0x1948c9 R E 0x1000
  LOAD           0x195000 0x0000000000195000 0x0000000000195000 0x0df960 0x0df960 R   0x1000
```
llvm-objcopy produces ELF with the output below:
```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x000268 0x000268 R   0x8
  INTERP         0x1948c9 0x0000000000195000 0x0000000000195000 0x00000f 0x00000f R   0x1
      [Requesting program interpreter: ]
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x1948c9 0x1948c9 R E 0x1000
  LOAD           >>>>0x1948c9<<<< 0x0000000000195000 0x0000000000195000 0x0df960 0x0df960 R   0x1000

```
The p_offset of the 2nd PT_LOAD seg has incorrect value obtained from p_memsz of the first PT_LOAD segment
GNU objcopy (on the real ELF i have got) aligns p_offset to p_align of PT_LOAD segment that produces 0x195000 as the value of p_offset for the 2nd PT_LOAD.

### PR DESCRIPTION
**Pull request by MaskRay**
(#79887) When the offset of a PT_INTERP segment equals the offset of a
PT_LOAD segment, we consider that the parent of the PT_LOAD segment is
the PT_INTERP segment. In `layoutSegments`, we place both segments to be
after the current `Offset`, ignoring the PT_LOAD alignment.

This scenario is possible with fixed section addresses, but doesn't
happen with default linker layouts (.interp precedes other sections and
is part of a PT_LOAD segment containing the ELF header and program
headers).

```
% cat a.s
.globl _start; _start: ret
.rodata; .byte 0
.tdata; .balign 4096; .byte 0
% clang -fuse-ld=lld a.s -o a -nostdlib -no-pie -z separate-loadable-segments -Wl,-Ttext=0x201000,--section-start=.interp=0x202000,--section-start=.rodata=0x202020,-z,nognustack
% llvm-objcopy a a2
% llvm-readelf -l a2   # incorrect offset(PT_LOAD)
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000200040 0x0000000000200040 0x0001c0 0x0001c0 R   0x8
  INTERP         0x001001 0x0000000000202000 0x0000000000202000 0x00001c 0x00001c R   0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x000000 0x0000000000200000 0x0000000000200000 0x000200 0x000200 R   0x1000
  LOAD           0x001000 0x0000000000201000 0x0000000000201000 0x000001 0x000001 R E 0x1000
//// incorrect offset
  LOAD           0x001001 0x0000000000202000 0x0000000000202000 0x000021 0x000021 R   0x1000
  LOAD           0x002000 0x0000000000203000 0x0000000000203000 0x000001 0x001000 RW  0x1000
  TLS            0x002000 0x0000000000203000 0x0000000000203000 0x000001 0x000001 R   0x1000
  GNU_RELRO      0x002000 0x0000000000203000 0x0000000000203000 0x000001 0x001000 R   0x1000
```

The same issue occurs for PT_TLS/PT_GNU_RELRO if we PT_TLS's alignment
is smaller and we place the PT_LOAD after PT_TLS/PT_GNU_RELRO segments
(not linker default, but possible with a `PHDRS` linker script command).

Fix #79887: when two segments have the same offset, order the one with a
larger alignment first. In the previous case, the PT_LOAD segment will
go before the PT_INTERP segment. In case of equal alignments, it doesn't
matter which segment is treated as the parent segment.

### CODE REVIEW

**Comment by MaskRay** [comment]
@chestnykh

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp [hunk 1]
```diff
@@ -1234,6 +1234,13 @@ static bool compareSegmentsByOffset(const Segment *A, const Segment *B) {
     return true;
   if (A->OriginalOffset > B->OriginalOffset)
     return false;
+  // If one is PT_LOAD and the other isn't (e.g. PT_INTERP, PT_GNU_RELRO,
+  // PT_TLS), order the PT_LOAD first to ensure ParentSegment relationship will
+  // be correct.
+  bool AIsLOAD = A->Type == PT_LOAD;
+  bool BIsLOAD = B->Type == PT_LOAD;
+  if (AIsLOAD != BIsLOAD)
```
Comment (jh7370) [inline llvm/lib/ObjCopy/ELF/ELFObject.cpp:1242]: I don't know of a concrete example of this in the wild, but should we also handle the case where both are `PT_LOAD` somehow? I feel like just picking whichever is higher alignment would be enough to properly preserve the parent/child relationship and get the alignment correct.

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+    AddressAlign:    0x4
+    Offset:          0x1000
+    Content:         C3
+  - Name:            .interp
+    Type:            SHT_PROGBITS
+    Flags:           [ SHF_ALLOC ]
+    Address:         0x202000
+    AddressAlign:    0x1
+    Offset:          0x2000
+    Content:         2F6C696236342F6C642D6C696E75782D7838362D36342E736F2E3200
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:111]: `Content` seems irrelevant to the test? You can use `Size` to make it non-zero size. Same goes below.

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+--- !ELF
+FileHeader:
+  Class:           ELFCLASS64
+  Data:            ELFDATA2LSB
+  Type:            ET_EXEC
+  Machine:         EM_X86_64
+  Entry:           0x201000
+ProgramHeaders:
+  - Type:            PT_PHDR
+    Flags:           [ PF_R ]
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:40]: If I'm not mistaken, the section and program header flags are all irrelevant to the test, so can be scrapped.

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+# CHECK-NEXT:  GNU_RELRO      0x003000 0x0000000000203000 0x0000000000203000 0x000001 0x001000 R   0x1000
+# CHECK-NEXT:  LOAD           0x003000 0x0000000000203000 0x0000000000203000 0x000001 0x001000 RW  0x1000
+
+--- !ELF
+FileHeader:
+  Class:           ELFCLASS64
+  Data:            ELFDATA2LSB
+  Type:            ET_EXEC
+  Machine:         EM_X86_64
+  Entry:           0x201000
```
Comment (jh7370) [inline llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:37]: Pretty sure `Entry` will be irrelevant and can be deleted.

**Review by jh7370 — COMMENTED** [review]
Mostly looks fine.

I assume the test fails without the fix?

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp (hunk 1 above)
Comment (chestnykh) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp:1242]: I've testst the fix, yes, the fix is correct

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test (hunk 2 above)
Comment (MaskRay) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:111]: It's relevant. The content tests that `llvm-readelf -Sl %t2` retains the original .interp string, `[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]`

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test (hunk 3 above)
Comment (MaskRay) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:40]: It could be scrapped, but PT_PHDR makes the test more real.

In linker output, if PT_INTERP is present, PT_PHDR should be present as well (unless the user specifies a `PHDRS` command with just `PT_INTERP`).

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test (hunk 4 above)
Comment (MaskRay) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test]: Removed

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp (hunk 1 above)
Comment (MaskRay) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp:1242]: A program is broken if it has two `PT_LOAD` at the same offset. Most dynamic loaders will translate `PT_LOAD` to mmap commands. The map from a later `PT_LOAD` will overwrite the map from a previous one. I feel that testing this would be nice, but the value is quite low, since it is very difficult to create two `PT_LOAD` at the same offset even with a linker script... And the coverage is less relevant to this patch.

Just comparing `p_align` doesn't work when PT_TLS/PT_GNU_RELRO has an alignment of maxpagesize, as my description says:

> The same issue occurs for PT_TLS/PT_GNU_RELRO if we PT_TLS's alignment is smaller and we place the PT_LOAD after PT_TLS/PT_GNU_RELRO segments (not linker default, but possible with a PHDRS linker script command).

Comment (jh7370) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp:1242]: Sorry for the delayed response: I'm not sure I follow why simply picking the highest alignment in a set of overlapping segments isn't sufficient? The comment you made is about PT_TLS having a lower alignment than PT_LOAD, in which case we'd want the PT_LOAD's higher alignment. But actually, the type of the PT_LOAD is somewhat irrelevant I'd have thought: you could imagine a custom segment type that requires alignment overlapping another segment type and the higher alignment would still be desirable to be used, regardless of the order of those segments.

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test (hunk 2 above)
Comment (jh7370) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:110]: That's not really what this test is about though? This test is about making sure the alignment is respected when the higher alignment segment appears after another segment it nests, so it's about the final file offset in program headers. There are already tests that show that segment contents are preserved (see e.g. `preserve-segment-contents.test`).

File: llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test (hunk 3 above)
Comment (jh7370) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test:39]: I don't think I was advocating dropping `PT_PHDR`. I was referring to the `[ PF_R ]` flags (and similarly for all other program header and section header flags, since they have no bearing on the test). We want to reduce the noise in the test to make it easier to spot what's actually important for the test.

Comment (MaskRay) [reply llvm/test/tools/llvm-objcopy/ELF/non-load-at-load-start.test]: OK, removed `PF_* and SHF_*`

File: llvm/lib/ObjCopy/ELF/ELFObject.cpp (hunk 1 above)
Comment (MaskRay) [reply llvm/lib/ObjCopy/ELF/ELFObject.cpp]: I think I special cased `PT_LOAD` because in practice, for all segments that may overlap with a `PT_LOAD`, treating `PT_LOAD` as the parent/ancestor will work and the parent relationship is conceptually treated as such. Giving it another thought, when a `PT_LOAD` and a `PT_TLS` have the same offset and alignment, it doesn't matter if we make `PT_TLS` the parent. The algorithm will still work as intended.

Switched to the `return A->Align > B->Align;` rule.

**Review by jh7370 — APPROVED** [review]
LGTM, thanks for humouring my comments :)

**Comment by steven-johnson** [comment]
FWIW, we pass at the apparently-previous-commit (066773c4117512a76e127741631630fef57caf14) but fail 100% of the time with this commit. We should rollback if a fix-forward isn't imminent.

**Comment by steven-johnson** [comment]
Update: looks like `git bisect` was lying to me -- there is an injection point somewhere in LLVM for this crash, but this PR is definitely not the culprit. Sorry for the noise.
