### PR TITLE
[mlir][func] Fix multiple bugs in `DuplicateFunctionElimination`

### LINKED ISSUE #93483: [mlir][func] Duplicate function elimination pass can create invalid IR
In the duplicate function elimination logic [here](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp), there are a couple bugs:

1. It is not checked whether a function has a body or not, so in the below `some_external_func2` will be replaced with `some_external_func`:

```mlir
func.func private @some_external_func(i32, i32) -> i32
func.func private @some_external_func2(i32, i32) -> i32

func.func @some_caller(%arg0: i32, %arg1: i32) -> (i32, i32) {
  %0 = func.call @some_external_func(%arg0, %arg1) : (i32, i32) -> i32
  %1 = func.call @some_external_func2(%arg0, %arg1) : (i32, i32) -> i32
  return %0, %1 : i32, i32
}
```

2. The logic assumes that the only users of the `func.func` symbol are  `func::CallOp` ops, but it doesn't check this. There could be other users (e.g. `func.constant`, ops not in upstream, or even just a discardable `SymbolRefAttr` in any op). These symbols will still refer to the removed function symbol at the end of the pass.

### PR DESCRIPTION
**Pull request by CoTinker**
This PR fixes multiple bugs in `DuplicateFunctionElimination`.
- Prevents elimination of function declarations.
- Updates all symbol uses to reference unique function representatives.

Fixes #93483.

### CODE REVIEW

File: mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp [hunk 1]
```diff
@@ -97,14 +101,14 @@ struct DuplicateFunctionEliminationPass
...
-    });
-
-    // Erase redundant func ops.
+    // Update all symbol uses to reference unique func op
+    // representants and erase redundant func ops.
     for (auto it : toBeErased) {
+      auto oldSymbol = it.getSymNameAttr();
+      auto newSymbol = getRepresentant[oldSymbol].getSymNameAttr();
+      if (failed(
+              SymbolTable::replaceAllSymbolUses(oldSymbol, newSymbol, module)))
```
Comment (joker-eph) [inline mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp:110]: I'm concerned that `SymbolTable::replaceAllSymbolUses` is expensive inside the loop, we should be able to setup the mapping of definition/users in a single traversal of the module and then process the updates.

Comment (CoTinker) [reply mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp:110]: Okay, I'll try it. Maybe I can add a new function like `SymbolTable::replaceAllSymbolUses(DenseMap<StringAttr, StringAttr> &toBeReplaced, Operation *from)`. Could you please give me some guidance.

Comment (joker-eph) [reply mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp:110]: Such an API may work indeed.

**Comment by CoTinker** [comment]
I've noticed that `replaceAllSymbolUsesImpl` uses `collectSymbolScopes` to traverse the region and `addReplacement` to perform replacements. Perhaps using `SymbolTable::replaceAllSymbolUses` inside the loop isn't as costly as we think.
https://github.com/llvm/llvm-project/blob/8dd817b25ae8b666aef839d36ffe028c01d411b5/mlir/lib/IR/SymbolTable.cpp#L877-L891
I'm not familiar with this, could you please take a look at it. @River707

**Comment by joker-eph** [comment]
> In the following scenario, SymbolTable::replaceAllSymbolUses is also inside a loop.

I suspect It's just as bad

File: mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp (hunk 1 above)
Comment (christopherbate) [reply mlir/lib/Dialect/Func/Transforms/DuplicateFunctionElimination.cpp:110]: IIUC, the issue for performance looks to be the `module` in ` SymbolTable::replaceAllSymbolUses(oldSymbol, newSymbol, module)))`. That means it needs to traverse all the ops in `module` and look for uses of `oldSymbol` that can be replaced. 

The class `SymbolUserMap` pre-computes this information for just this use case. Create the `SymbolUserMap` and then call `SymbolUserMap::replaceAllUsesWith` in the loop. That will iterate over the relevant users and update them rather than iterating over the whole module.



```
SymbolTableCollection collection;
SymolUserMap userMap(collection, module);

for(....) {
    ....
    userMap.replace(old, new);
}
```

**Comment by christopherbate** [comment]
@CoTinker I commented above with a suggestion for how to fix.

**Comment by CoTinker** [comment]
> @CoTinker I commented above with a suggestion for how to fix.

Thanks, I'll refer to it.

**Review by joker-eph — APPROVED** [review]
