### PR TITLE
[clang] Do not infer lifetimebound for functions with void return type

### LINKED ISSUE #126231: compile with clang 20.1.0 error: 'lifetimebound' attribute cannot be applied to a....
```
[5/6] D:\LLVM-20.x.x-win64\bin\clang++.exe  -isystem D:/msvc/VC/Tools/MSVC/14.43.34808/include -isystem D:/msvc/V
C/Tools/MSVC/14.43.34808/atlmfc/include -isystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucr
t" -isystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -isystem "D:/Program Files (x86)
/Windows Kits/10/Include/10.0.18362.0/um" -isystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/w
inrt" -O3 -DNDEBUG -std=c++20 -Xclang -flto-visibility-public-std -D_MT -Xclang --dependent-lib=libcmt -MD -MT CM
akeFiles/demo.dir/main.cpp.obj -MF CMakeFiles\demo.dir\main.cpp.obj.d @CMakeFiles\demo.dir\main.cpp.obj.modmap -o
 CMakeFiles/demo.dir/main.cpp.obj -c D:/T60/test/CMake_Modules/main.cpp
FAILED: CMakeFiles/demo.dir/main.cpp.obj
D:\LLVM-20.x.x-win64\bin\clang++.exe  -isystem D:/msvc/VC/Tools/MSVC/14.43.34808/include -isystem D:/msvc/VC/Tool
s/MSVC/14.43.34808/atlmfc/include -isystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -is
ystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -isystem "D:/Program Files (x86)/Windo
ws Kits/10/Include/10.0.18362.0/um" -isystem "D:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt"
-O3 -DNDEBUG -std=c++20 -Xclang -flto-visibility-public-std -D_MT -Xclang --dependent-lib=libcmt -MD -MT CMakeFil
es/demo.dir/main.cpp.obj -MF CMakeFiles\demo.dir\main.cpp.obj.d @CMakeFiles\demo.dir\main.cpp.obj.modmap -o CMake
Files/demo.dir/main.cpp.obj -c D:/T60/test/CMake_Modules/main.cpp
In module 'MyModule' imported from D:/T60/test/CMake_Modules/main.cpp:1:
D:/msvc/VC/Tools/MSVC/14.43.34808/include\utility:784:6: error: 'lifetimebound' attribute cannot be applied to a
parameter of a function that returns void; did you mean 'lifetime_capture_by(X)'
  784 | void as_const(const _Ty&&) = delete;
      |      ^
1 error generated.
ninja: build stopped: subcommand failed.
```

https://github.com/microsoft/STL/issues/5271#issuecomment-2638782498

### PR DESCRIPTION
**Pull request by usx95**
Fixes: https://github.com/llvm/llvm-project/issues/126231
Also found in : https://github.com/microsoft/STL/issues/5271

### CODE REVIEW

**Review by hokein — APPROVED** [review]
It would be nice to have have a test for it. I think it should not be too hard to add one.

**Comment by ilya-biryukov** [comment]
LGTM!
I second the suggestion to add a test. Also see the suggestion to turn this into a warning in the first place: https://github.com/llvm/llvm-project/issues/126231#issuecomment-2735876367

I am not sure why lifetimebound needs to be an error while other attributes like `const` produce a warning and can be ignored.

**Review by ilya-biryukov — CHANGES_REQUESTED** [review]
There seem to be some errors missing the attribute tests now (see buildkite failures)

**Comment by ilya-biryukov** [comment]
@usx95 I struggled to come up with a reproducer and couldn't understand why at first.
I think we infer the attribute **after** we check for this error. This is obviously something  we need to fix, but you can get a reproducer like this:

https://gcc.godbolt.org/z/e66MY1nn5
```cpp
// RUN: %clang_cc1 -std=c++20 -verify %s

namespace std {
template <class T>
constexpr const T& as_const(T&) noexcept;

// We need two declarations to see the error for some reason *shrug*
template <class T> void as_const(const T&&) noexcept = delete;
template <class T> void as_const(const T&&) noexcept;
}

namespace GH126231 {

void test() {
  // Instantiate the overload returning `void` to trigger an error.
  int a = 1;
  std::as_const(a);
}
}

```

File: clang/test/Sema/GH126231.cpp [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// RUN: %clang_cc1 -std=c++20 -Wno-ignored-attributes -Wno-unused-value -verify %s
+// expected-no-diagnostics
+namespace std {
+template <class T>
+constexpr const T& as_const(T&) noexcept;
+
+// We need two declarations to see the error for some reason *shrug*
```
Comment (ilya-biryukov) [inline clang/test/Sema/GH126231.cpp:7]: NIT: could probably remove **shrug**

**Review by ilya-biryukov — APPROVED** [review]

File: clang/lib/Sema/SemaAttr.cpp [hunk 2]
```diff
@@ -219,6 +220,9 @@ void Sema::inferGslOwnerPointerAttribute(CXXRecordDecl *Record) {
 void Sema::inferLifetimeBoundAttribute(FunctionDecl *FD) {
   if (FD->getNumParams() == 0)
     return;
+  // Skip void returning functions (except constructors).
```
Comment (ilya-biryukov) [inline clang/lib/Sema/SemaAttr.cpp:223]: NIT: it would be useful to mention `as_const` is the motivating example.
