### PR TITLE
[Clang][Sema] Fix -Whigher-precision-for-complex-division

### LINKED ISSUE #131127: [clang] Multiple false positives and false negatives in -Whigher-precision-for-complex-division
The `-Whigher-precision-for-complex-division` emitted when `-fcomplex-arithmetic=promoted` option is used and the target does not support a higher precison type has multiple false positives and false negatives:
- Clang warns but shouldn't when the divisor is a real value, this is just elementwise division, which is already precise if performed in the lower precision type.
- Clang doesn't warn but should, if the divisor is a complex value but the divident is real.
- Clang doesn't warn but should, if the operation is going to be performed in a different type than the divident due to usual arithmetic conversions and the new type is the largest precision for the target. (e.g. `__complex__ float / __complex__ double`).
- Clang doesn't warn but should when using the `/=` (divide and assign) operator.

[Reproducer on Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:20,positionColumn:1,positionLineNumber:20,selectionStartColumn:1,selectionStartLineNumber:20,startColumn:1,startLineNumber:20),source:'double+__complex__+div_complex_real(double+__complex__+a,+double+b)+%7B%0A++++return+a+/+b%3B+//+This+should+not+warn+but+it+does!!%0A%7D%0A%0Adouble+__complex__+div_real_complex(double+a,+double+__complex__+b)+%7B%0A++++return+a+/+b%3B+//+This+should+warn+but+it+doesn!'t.%0A%7D%0A%0Adouble+__complex__+div_assign(double+__complex__+a,+double+__complex__+b)+%7B%0A++++return+a+/%3D+b%3B+//+This+should+warn+but+it+doesn!'t.%0A%7D%0A%0Adouble+__complex__+div_mixed(float+__complex__+a,+double+__complex__+b)+%7B%0A++++return+a+/+b%3B+//+This+should+warn+but+it+doesn!'t.%0A%7D%0A%0Adouble+__complex__+div_mixed(int+__complex__+a,+double+__complex__+b)+%7B%0A++++return+a+/+b%3B+//+This+should+warn+but+it+doesn!'t.%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:30.958904109589042,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang_trunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-target+aarch64-pc-windows-msvc+-fcomplex-arithmetic%3Dpromoted+-fsyntax-only+-Wno-unused-command-line-argument',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+(trunk)+(Editor+%231)',t:'0')),k:50,l:'4',m:50.60104694679994,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+(trunk)+(Compiler+%231)',t:'0')),header:(),l:'4',m:49.398953053200046,n:'0',o:'',s:0,t:'0')),k:69.04109589041096,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

### PR DESCRIPTION
**Pull request by Maetveis**
- Fix false positive when divisor is a real number.
- Fix false negative when divident is real, but divisor is complex.
- Fix false negative when due to promotion the division is performed in higher precision than the divident.
- Fix false negative in divide and assign (`a /= b`).

Fixes: #131127

### CODE REVIEW

File: clang/lib/Sema/SemaExpr.cpp [hunk 1]
```diff
@@ -10555,6 +10555,43 @@ static void checkArithmeticNull(Sema &S, ExprResult &LHS, ExprResult &RHS,
       << LHS.get()->getSourceRange() << RHS.get()->getSourceRange();
 }
 
+static void DetectPrecisionLossInComplexDivision(Sema &S, QualType DivisorTy,
+                                                 SourceLocation OpLoc) {
+  // Either real/real or complex/real division.
+  // Either way there can be no precision loss.
+  auto *CT = DivisorTy->getAs<ComplexType>();
+  if (!CT)
+    return;
```
Comment (Sirraide) [inline clang/lib/Sema/SemaExpr.cpp:10564]: Hmm, is this right? If this is the *divisor*, not the *dividend*, then isn’t this just complex/complex division? Because I don’t think real/complex is valid (at least I’d expect us to convert the dividend to a complex number first).

Comment (Sirraide) [reply clang/lib/Sema/SemaExpr.cpp:10564]: I noticed we were passing the *LHS* expression to this, but now we’re passing in the *RHS* type? Is that intended?

Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10564]: Changing to RHS (divisor) is intended. If the divisor is real (**not** `isAnyComplexType`) its either complex / real or real / real divison. I think the code is right. I also double checked the names of the terms of division because English isn't my primary language, but that seems right too.

Comment (Sirraide) [reply clang/lib/Sema/SemaExpr.cpp:10564]: That makes sense; looking at this again, I think the way the comment is worded just confused me a bit.

**Comment by Maetveis** [comment]
Rebased to fix conflict.
Ping @Sirraide

**Comment by Sirraide** [comment]
I think the implementation looks fine, but someone more familiar w/ floats than me should approve this.

**Comment by Maetveis** [comment]
> I think the implementation looks fine, but someone more familiar w/ floats than me should approve this.

Okay, thanks :)
@jcranmer-intel @zahiraam maybe?

**Review by AaronBallman — COMMENTED** [review]
The changes should come with a release note in `clang/docs/ReleaseNotes.rst` so users know about the fix.

File: clang/lib/Sema/SemaExpr.cpp [hunk 2]
```diff
@@ -10685,6 +10724,7 @@ QualType Sema::CheckMultiplyDivideOperands(ExprResult &LHS, ExprResult &RHS,
   if (compType.isNull() || !compType->isArithmeticType())
     return InvalidOperands(Loc, LHS, RHS);
   if (IsDiv) {
+    DetectPrecisionLossInComplexDivision(*this, RHS.get()->getType(), Loc);
```
[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10727]: The dividend is not relevant assuming its a built-in arithmetic type, which I think it must be at this point in the code already. I'll try verifying this assumption though. Note that IIUC the types have "usual arithmetic conversions" applied to them here.

Whether the dividend is real or complex does not matter because complex divided by complex and real divided by complex both need promotion, but neither complex by complex (because it is elementwise) or real by real do.

File: clang/lib/Sema/SemaExpr.cpp [hunk 3]
```diff
@@ -10591,6 +10591,45 @@ static void checkArithmeticNull(Sema &S, ExprResult &LHS, ExprResult &RHS,
       << LHS.get()->getSourceRange() << RHS.get()->getSourceRange();
 }
 
+static void DetectPrecisionLossInComplexDivision(Sema &S, QualType DivisorTy,
+                                                 SourceLocation OpLoc) {
+  // If the divisor is real, then this is real/real or complex/real division.
+  // Either way there can be no precision loss.
+  auto *CT = DivisorTy->getAs<ComplexType>();
+  if (!CT)
+    return;
```
[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10600]: No, this is true either way, because we're doing elementwise divisions only.
Complex divided by real: `(a + bi)/c = a/c + (b/c)i`. Here both divisions are already precise by definition.

File: clang/lib/Sema/SemaExpr.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10727]: > The dividend is not relevant assuming its a built-in arithmetic type (...). I'll try verifying this assumption though.

This codepath is reachable only from `CreteBuiltinBinOp` and there's a check right above the call that verifies that the types are arithmetic, so I don't think even an assert is warranted here for this.

File: clang/test/Sema/complex-div-warn-higher-precision.c [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+#ifdef DIV_RC
+_Complex double div_rc(double a, _Complex float b) {
+    return a / b; // #1
+}
+#endif // DIV_RC
+
+#ifdef DIVASSIGN
+_Complex double divassign(_Complex double a, _Complex double b) {
+    return a /= b; // #1
```
[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/test/Sema/complex-div-warn-higher-precision.c]: I added a test covering this.

**Comment by Maetveis** [comment]
Don't know what's up with buildkite, it looks as if it doesn't like multiple commits? The commit ID its trying to check out is the first in the series, but `git fetch -v --prune -- origin refs/pull/131477/head` is giving it `c62bde990396854bd4015c4ad19894e9297ebe18` which I guess is a squashed commit?

**Comment by Maetveis** [comment]
FYI: I found more issues when testing with `std::complex`: https://github.com/llvm/llvm-project/issues/134980

File: clang/lib/Sema/SemaExpr.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (zahiraam) [reply clang/lib/Sema/SemaExpr.cpp:10727]: > The dividend is not relevant assuming its a built-in arithmetic type, which I think it must be at this point in the code already. I'll try verifying this assumption though. Note that IIUC the types have "usual arithmetic conversions" applied to them here.
> 
> Whether the dividend is real or complex does not matter because complex divided by complex and real divided by complex both need promotion, but neither complex by complex (because it is elementwise) or real by real do.

OK looking at the divisor's type only is enough. When the divisor is of complex type than a promotion is needed. When the complex type of the divisor and the dividend are not of the same precision, a promotion is needed but that's happening with the current code.
How about if we have `_Complex float / double`? Or` _Complex double / float`? This should need a promotion, and it's not in the patch.

[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10727]: > How about if we have _Complex float / double? Or _Complex double / float? This should need a promotion, and it's not in the patch.

Why would that need a promotion besides the usual arithmetic conversions (i.e. to double and not long double)? Precision loss from using the complex division arithmetic formulas does not come into play here, because its elementwise.
Usual arithmetic conversions are already applied at this point: https://github.com/llvm/llvm-project/pull/131477/files#diff-3c28567b5e0c77d68f174541a0b77f5a85d093f58b89cd3675ee04a550a44880R10718-R10719

[the remark this answers is not in the document]
Comment (Maetveis) [reply clang/lib/Sema/SemaExpr.cpp:10727]: Or do you mean I should add a test that there's no warning for this case?

[the remark this answers is not in the document]
Comment (zahiraam) [reply clang/lib/Sema/SemaExpr.cpp:10727]: Ok now I am convinced, the various conversions would have been done by then. Yes adding another test that shows no warning for these cases would be great.

**Comment by Maetveis** [comment]
I tried a squash + force-push to get buildkite working again.

File: clang/docs/ReleaseNotes.rst [hunk 5]
```diff
@@ -349,6 +349,17 @@ Improvements to Clang's diagnostics
 - Now correctly diagnose a tentative definition of an array with static
   storage duration in pedantic mode in C. (#GH50661)
 
+- ``-Whigher-precisision-for-complex-divison`` no longer incorrectly warns when the divisor is real
+  in complex division. (#GH131127)
+
+- ``-Whigher-precisision-for-complex-divison`` now correctly warns when:
+
+  - The dividend is real, but the divisor is complex.
```
Comment (zahiraam) [inline clang/docs/ReleaseNotes.rst:357]: This is throwing me off again. Because you are mentioning the dividend here, but no where in the code we are looking at the dividend. So may be this should be-reworded.

Comment (Maetveis) [reply clang/docs/ReleaseNotes.rst:357]: > but no where in the code we are looking at the dividend.

That is correct, nowhere in the *new* code are we looking at the dividend. The code before the PR was looking at only the *dividend*, and ignored the divisor:
```cpp
DetectPrecisionLossInComplexDivision(*this, TokLoc, LHSExpr);
```

This caused it to have a false positive when the dividend was complex and the divisor real, and a false negative when the dividend was real and the divisor complex.

With the change in the PR we are looking at only the *divisor*, ignoring the dividend:
```cpp
DetectPrecisionLossInComplexDivision(*this, RHS.get()->getType(), Loc);
```

The divisor is what's relevant; therefore this change fixes both the false positive and the false negative present before the PR.

> So may be this should be-reworded.

I don't know how to word this better, The "dividend is real" part is there because that's what was broken before this PR, and the "but the divisor is complex" is mostly to clarify that this is still complex division. Real / real does not and should not warn before or after this PR. Maybe this second part of the sentence is redundant given the name of the warning. Is this what's confusing about the release note?

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -349,6 +349,17 @@ Improvements to Clang's diagnostics
 - Now correctly diagnose a tentative definition of an array with static
   storage duration in pedantic mode in C. (#GH50661)
 
+- ``-Whigher-precisision-for-complex-divison`` no longer incorrectly warns when the divisor is real
```
Comment (zahiraam) [inline clang/docs/ReleaseNotes.rst:352]:
```suggestion
- ``-Whigher-precisision-for-complex-divison`` warns when:
•	The divisor is complex.
•	When the complex division happens in a higher precision type due to arithmetic promotion.
•	When using the divide and assign operator (/=).
```

Comment (Maetveis) [reply clang/docs/ReleaseNotes.rst]: Thanks, applied!

File: clang/docs/ReleaseNotes.rst [hunk 7]
```diff
@@ -360,6 +360,14 @@ Improvements to Clang's diagnostics
 
 - An error is now emitted when a ``musttail`` call is made to a function marked with the ``not_tail_called`` attribute. (#GH133509).
 
+- ``-Whigher-precisision-for-complex-divison`` warns when:
+
+  -	The divisor is complex
+  -	When the complex division happens in a higher precision type due to arithmetic promotion
+  -	When using the divide and assign operator (``/=``)
+
```
Comment (zahiraam) [inline clang/docs/ReleaseNotes.rst:368]: NIT. Please put a "." at the end of each bullet.

**Review by zahiraam — APPROVED** [review]
Looks good. Just a few NIT things to edit. Thanks.
