### PR TITLE
Suppress errors from well-formed-testing type traits in SFINAE contexts

### LINKED ISSUE #132044: Bogus error when using `__reference_converts_from_temporary` in default template argument
We ran into this with an `std::function` (libstdc++ 13) returning an object with protected copy constructor. It boils down to this:

```c++
class X {
protected:
    X(const X&);
};

static_assert(!__reference_converts_from_temporary(X, X));

template<typename A, typename B,
         bool Dangle = __reference_converts_from_temporary(A, B)>
static void test();

using Result = decltype(test<X, X>());
```
produces:
```
bug.cpp:9:24: error: calling a protected constructor of class 'X'
    9 |          bool Dangle = __reference_converts_from_temporary(A, B)>
      |                        ^
```
Replacing either `A` or `B` by `X` doesn't make the error go away. Interestingly, if we define `test`, for example with an empty body, and do a full instantiation, then the error appears if the instantiation is implicit, but not if it's explicit:
```c++
template<typename A, typename B,
         bool Dangle = __reference_converts_from_temporary(A, B)>
static void test() {} // <-- Added an empty body.

template void test<X, X>(); // No error.

void f() {
    test<X, X>(); // Error.
}
```

### PR DESCRIPTION
**Pull request by aaronpuchert**
There are several type traits that produce a boolean value or type based on the well-formedness of some expression (more precisely, the immediate context, i.e. for example excluding nested template instantiation):
* `__is_constructible` and variants,
* `__is_convertible` and variants,
* `__is_assignable` and variants,
* `__reference_{binds_to,{constructs,converts}_from}_temporary`,
* `__is_trivially_equality_comparable`,
* `__builtin_common_type`.

(It should be noted that the standard doesn't always base this on the immediate context being well-formed: for `std::common_type` it's based on whether some expression "denotes a valid type." But I assume that's an editorial issue and means the same thing.)

Errors in the immediate context are suppressed, instead the type traits return another value or produce a different type if the expression is not well-formed. This is achieved using an `SFINAETrap` with `AccessCheckingSFINAE` set to true. If the type trait is used outside of an SFINAE context, errors are discarded because in that case the `SFINAETrap` sets `InNonInstantiationSFINAEContext`, which makes `isSFINAEContext` return an `optional(nullptr)`, which causes the errors to be discarded in `EmitDiagnostic`. However, in an SFINAE context this doesn't happen, and errors are added to `SuppressedDiagnostics` in the `TemplateDeductionInfo` returned by `isSFINAEContext`. Once we're done with deducing template arguments and have decided which template is going to be instantiated, the errors corresponding to the chosen template are then emitted. At this point we get errors from those type traits that we wouldn't have seen if used with the same arguments outside of an SFINAE context. That doesn't seem right.

So what we want to do is always set `InNonInstantiationSFINAEContext` when evaluating these well-formed-testing type traits, regardless of whether we're in an SFINAE context or not. This should only affect the immediate context, as nested contexts add a new `CodeSynthesisContext` that resets `InNonInstantiationSFINAEContext` for the time it's active.

Going through uses of `SFINAETrap` with `AccessCheckingSFINAE` = `true`, it occurred to me that all of them want this behavior and we can just use this parameter to decide whether to use a non-instantiation context. The uses are precisely the type traits mentioned above plus the `TentativeAnalysisScope`, where I think it is also fine. (Though I think we don't do tentative analysis in SFINAE contexts anyway.)

Because the parameter no longer just sets `AccessCheckingSFINAE` in Sema but also `InNonInstantiationSFINAEContext`, I think it should be renamed (along with uses, which also point the reviewer to the affected places). Since we're testing for validity of some expression, `ForValidityCheck` seems to be a good name.

The added tests should more or less correspond to the users of `SFINAETrap` with `AccessCheckingSFINAE` = `true`. I added a test for errors outside of the immediate context for only one type trait, because it requires some setup and is relatively noisy.

We put the `ForValidityCheck` condition first because it's constant in all uses and this would then allow the compiler to prune the call to `isSFINAEContext` when true.

Fixes #132044.

### CODE REVIEW

**Comment by aaronpuchert** [comment]
The tests would produce without the change:
```
error: 'expected-error' diagnostics seen but not expected:
  File clang/test/SemaCXX/type-traits.cpp Line 2676: calling a private constructor of class 'AllPrivate'
  File clang/test/SemaCXX/type-traits.cpp Line 2833: 'operator=' is a private member of 'AllPrivate'
  File clang/test/SemaCXX/type-traits.cpp Line 3209: calling a private constructor of class 'AllPrivate'
  File clang/test/SemaCXX/type-traits.cpp Line 4107: 'operator==' is a private member of 'is_trivially_equality_comparable::NotTriviallyEqualityComparablePrivateComparison'
4 errors generated.
```
and
```
error: 'expected-error' diagnostics seen but not expected:
  File clang/test/SemaCXX/type-trait-common-type.cpp Line 36: calling a private constructor of class 'PrivateConstructor'
1 error generated.
```

**Comment by aaronpuchert** [comment]
> (It should be noted that the standard doesn't always base this on the immediate context being well-formed: for `std::common_type` it's based on whether some expression "denotes a valid type." But I assume that's an editorial issue and means the same thing.)

Filed cplusplus/draft#7827 to clarify this.

File: clang/include/clang/Sema/Sema.h [hunk 1]
```diff
@@ -12240,16 +12240,16 @@ class Sema final : public SemaBase {
     bool PrevLastDiagnosticIgnored;
 
   public:
-    explicit SFINAETrap(Sema &SemaRef, bool AccessCheckingSFINAE = false)
+    explicit SFINAETrap(Sema &SemaRef, bool TestWellformedSFINAE = false)
```
Comment (cor3ntin) [inline clang/include/clang/Sema/Sema.h:12243]: Can you add a comment for the parameter?

Comment (cor3ntin) [reply clang/include/clang/Sema/Sema.h:12243]: Maybe `ForValidityCheck` would be clearer.

**Review by cor3ntin — COMMENTED** [review]
Can you add a changelog entry?

Other than that, the change makes sense to me

File: clang/include/clang/Sema/Sema.h (hunk 1 above)
Comment (aaronpuchert) [reply clang/include/clang/Sema/Sema.h:12243]: Adding a comment makes sense to me. I'm open to a different name, but I started with "well-formed" because that's how the standard calls it. "Valid" sounds fine, but it doesn't seem to be what the standard calls it.

Comment (aaronpuchert) [reply clang/include/clang/Sema/Sema.h:12243]: Although later it does say "only the validity of the immediate context is considered." So I guess it's fine.

**Comment by aaronpuchert** [comment]
I would push the change log entry separately to avoid conflicts if you don't mind. Here is what I would add (under "Bug Fixes in This Version"):

> Errors that occur during evaluation of certain type traits and builtins are no longer incorrectly emitted when they are used in an SFINAE context. The type traits are: `__is_constructible` and variants, `__is_convertible` and variants, `__is_assignable` and variants, `__reference_binds_to_temporary`, `__reference_constructs_from_temporary`, `__reference_converts_from_temporary`, and `__is_trivially_equality_comparable`. The builtin is `__builtin_common_type`.

**Comment by aaronpuchert** [comment]
Could also add this under "Bug Fixes to C++ Support". The entries about type traits [don't seem to be consistently categorized](https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html#bug-fixes-in-this-version), but I think this is all C++-only.

**Comment by cor3ntin** [comment]
@aaronpuchert Bug Fixes to C++ Support would be the correct place, yes. You can put the entry somewhere other than the end of the list to minimize the risk of conflicts, but it should be in the same commit.

**Review by cor3ntin — APPROVED** [review]
LGTM  modulo missing release note
