### PR TITLE
[OpenMP] Remove optimization skipping reduction struct initialization

### LINKED ISSUE #57522: Taskgroup task_reduction with target in_reduction segfaults
The following code segfaults at the end of the taskgroup when waiting for all tasks. If I remove nowait on the target tasks, the segfault goes away, which suggests the synchronisation at the end of the taskgroup construct is failing.

Tested with LLVM at commit 9ad0ace2, built for `-fopenmp-targets=nvtpx64` on a node with four A100 GPUs.
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>

#include <omp.h>

int main(void) {

  int N = 1000000;
  double *A, *B;
  A = malloc(N*sizeof(double));
  B = malloc(N*sizeof(double));

  double sum = 0.0;

  for (int i = 0; i < N; ++i) {
    A[i] = 1.5;
    B[i] = 2.0;
  }
  
  int num_devices = omp_get_num_devices();
  printf("Num devices: %d\n", num_devices);
  assert (N % num_devices == 0);
  int len = N / num_devices;

  #pragma omp taskgroup task_reduction(+:sum)
  {
    for (int dev = 0; dev < num_devices; ++dev) {
      int start = dev * len;
      int end = start + len;
 
      #pragma omp target map(to: A[start:len], B[start:len]) device(dev) in_reduction(+:sum) nowait
      {
        #pragma omp loop
        for (int i = start; i < end; ++i) {
                sum += A[i] * B[i];
        }
      }
    }
  }

  assert(fabs(sum - (3.0*N)) < 1.0E-10);

  printf("Success\n");

}
```

Some preliminary discussion occurred on [Discourse](https://discourse.llvm.org/t/taskgroup-task-reduction-with-target-in-reduction-segfaults/64683)

### PR DESCRIPTION
**Pull request by rodrigo-ceccato**
This commit removes an optimization that skips the initialization of the
reduction struct if the number of threads in a team is 1. This optimization
caused a bug with Hidden Helper Threads. When the task group is initially
initialized by the master thread but a Hidden Helper Thread executes a target
nowait region, it requires the reduction struct initialization to properly
accumulate the data.

This commit also adds a LIT test for issue #57522 to ensure that the issue is
properly addressed and that the optimization removal does not introduce any
regressions.

Fixes: #57522

### CODE REVIEW

File: openmp/runtime/src/kmp_tasking.cpp [hunk 1]
```diff
@@ -2699,6 +2694,7 @@ void *__kmpc_task_reduction_get_th_data(int gtid, void *tskgrp, void *data) {
         return p_priv[tid];
       }
     }
+    KMP_ASSERT(tg->parent != NULL);
```
Comment (shiltian) [inline openmp/runtime/src/kmp_tasking.cpp:2697]:
```suggestion
    KMP_ASSERT(tg->parent);
```

File: openmp/runtime/src/kmp_tasking.cpp [hunk 2]
```diff
@@ -2512,11 +2512,6 @@ void *__kmp_task_reduction_init(int gtid, int num, T *data) {
   KMP_ASSERT(tg != NULL);
   KMP_ASSERT(data != NULL);
   KMP_ASSERT(num > 0);
-  if (nth == 1) {
```
Comment (shiltian) [inline openmp/runtime/src/kmp_tasking.cpp:2515]: Instead of completely removing the branch, it might be better to check if HHT is enabled. If no, then we can safely return here.

Comment (jdoerfert) [reply openmp/runtime/src/kmp_tasking.cpp:2515]: I'm not sure how important single threaded reduction costs really are, but sure.

File: openmp/runtime/src/kmp_tasking.cpp (hunk 1 above)
Comment (rodrigo-ceccato) [reply openmp/runtime/src/kmp_tasking.cpp]: Done.

**Review by shiltian — APPROVED** [review]

**Comment by rodrigo-ceccato** [comment]
Squashed and updated the commit message.


```
ninja check-openmp
[0/1] Running OpenMP tests
-- Testing: 724 tests, 144 workers --
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 

Testing Time: 144.14s
  Unsupported: 100
  Passed     : 624
  ```
