### PR TITLE
[VectorCombine] foldShuffleOfBinops - failure to track OperandValueInfo

### LINKED ISSUE #170500: [VectorCombine] foldShuffleOfBinops - failure to track OperandValueInfo data in getArithmeticInstrCost calls
```
define <16 x i16> @concat_uniform_shift_v16i16_v8i16(<8 x i16> %a0, <8 x i16> %a1) {
  %v0 = shl <8 x i16> %a0, splat (i16 7)
  %v1 = shl <8 x i16> %a1, splat (i16 7)
  %res  = shufflevector <8 x i16> %v0, <8 x i16> %v1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %res
}
```
-passes=vector-combine -mtriple=x86_64-- -mcpu=znver2
```
define <16 x i16> @concat_uniform_shift_v16i16_v8i16(<8 x i16> %a0, <8 x i16> %a1) #0 {
  %v0 = shl <8 x i16> %a0, splat (i16 7)
  %v1 = shl <8 x i16> %a1, splat (i16 7)
  %res = shufflevector <8 x i16> %v0, <8 x i16> %v1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i16> %res
}
```
when it should be:
```
define <16 x i16> @concat_uniform_shift_v16i16_v8i16(<8 x i16> %a0, <8 x i16> %a1) #0 {
  %v = shufflevector <8 x i16> %a0, <8 x i16> %a1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %res = shl <16 x i16> %v, splat (i16 7)
  ret <16 x i16> %res
}
```

Vectorcombine fails to concatenate these shifts as the "NewCost" getArithmeticInstrCost calls fail to include any TTI::OperandValueInfo data - both of the shift amounts are OK_UniformConstantValue, so at the very least we should merge these into OK_NonUniformConstantValue.

A possible starting point would be to add TTI::getOperandInfo calls in the binop NewCost calculation for both LHS/RHS ops - and create some kind of 
OperandValueInfo::mergeInfo(X, Y) static helper that merge common info data (all constant, all powerof2 etc - although all uniform can't be done this way!).

But for this particular case, the RHS operands are identical - so we don't need to merge, we can just use the original OperandValueInfo.

foldPermuteOfBinops has a similar problem but it looks like OldCost and NewCost both use getArithmeticInstrCost - which is weird as I'd expect OldCost to use getInstructionCost at least.

### PR DESCRIPTION
**Pull request by KavinTheG**
Resolves #170500.

Implemented mergeInfo static helper to return common TTI::OperandValueInfo data . 

Added common OperandValueInfo `Op0Info` && `Op1Info` to NewCost calculation.

### CODE REVIEW

**Review by RKSimon — CHANGES_REQUESTED** [review]

**Comment by KavinTheG** [comment]
- Added an additional variant of mergeInfo to take Value args 
```C++
  LLVM_ABI static OperandValueInfo mergeInfo(const Value *X, const Value *Y);
  LLVM_ABI static OperandValueInfo mergeInfo(const OperandValueInfo X, const OperandValueInfo Y, bool IsEqual);
```

- I noticed that `foldShuffleOfBinops` already had an X == Z & Y == W statements, so I called `getOperandInfo(X)` if they're equal, and     `mergeInfo(TTI::getOperandInfo(X), TTI::getOperandInfo(Z), false)` otherwise. Ultimately makes mergeInfo with value inputs *not* needed for this patch, so I can remove it in the next commit if it's unnecessary fluff. Thought to keep it in to make it easier to use in other scenarios 

- Added the following test cases after examining `X86TTImpl::getArithmeticInstrCost`
	- Uniform constant shift 
	- Non uniform constant shift 
	- Uniform constant & pow2 mul
	- Nonuniform constant mul (non pow2)
	- Uniform constant & non pow2 mul 
	- Uniform mul (to test OK_UniformValue)
	- Uniform constant mul (different vector size)
	- Uniform constant add & sub
	- Uniform constant AND

**Comment by KavinTheG** [comment]
Ping.

File: llvm/lib/Transforms/Vectorize/VectorCombine.cpp [hunk 1]
```diff
@@ -2437,21 +2437,28 @@ bool VectorCombine::foldShuffleOfBinops(Instruction &I) {
...
   TargetTransformInfo::ShuffleKind SK1 = TargetTransformInfo::SK_PermuteTwoSrc;
   if (Y == W) {
     llvm::for_each(NewMask1, ConvertToUnary);
     SK1 = TargetTransformInfo::SK_PermuteSingleSrc;
     W = PoisonValue::get(BinOpTy);
-  }
+    Op1Info = TTI.getOperandInfo(Y);
+  } else
+    Op1Info =
+        TTI.mergeInfo(TTI::getOperandInfo(Y), TTI::getOperandInfo(W), false);
```
Comment (RKSimon) [inline llvm/lib/Transforms/Vectorize/VectorCombine.cpp]: `TTI::OperandValueInfo Op1Info = TTI.mergeInfo(Y, W);`

**Review by RKSimon — CHANGES_REQUESTED** [review]

File: llvm/test/Transforms/VectorCombine/X86/shuffle-of-binops.ll [hunk 2]
```diff
@@ -4,11 +4,172 @@
 
 declare void @use(<4 x i32>)
 
+; Uniform constant shift
```
Comment (RKSimon) [inline llvm/test/Transforms/VectorCombine/X86/shuffle-of-binops.ll]: Are there no tests that have a different cost benefit for SSE2 vs AVX2?

Comment (KavinTheG) [reply llvm/test/Transforms/VectorCombine/X86/shuffle-of-binops.ll]: Apologies for the late update. For clarification, should I only be adding test cases where both SSE2 and AVX2 cost table has an entry with  the same vector type and instruction? Like below?

```C++
  static const CostKindTblEntry AVX2UniformCostTable[] = {
    // Uniform splats are cheaper for the following instructions.
    { ISD::SHL,  MVT::v16i8,  { 3, 5, 5, 7 } }, // psllw + pand.
    ...
  }
  static const CostKindTblEntry SSE2UniformCostTable[] = {
    // Uniform splats are cheaper for the following instructions.
    { ISD::SHL,  MVT::v16i8, {  9, 10, 6, 9 } }, // psllw + pand.
  }
```

File: llvm/test/Transforms/VectorCombine/X86/shuffle-of-binops.ll [hunk 3]
```diff
@@ -4,11 +4,172 @@
...
+; CHECK-NEXT:    [[RES:%.*]] = mul <8 x i32> [[TMP1]], splat (i32 7)
+; CHECK-NEXT:    ret <8 x i32> [[RES]]
+;
+  %v0 = mul <4 x i32> %a0, splat(i32 7)
+  %v1 = mul <4 x i32> %a1, splat(i32 7)
+  %res = shufflevector <4 x i32> %v0, <4 x i32> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
+  ret <8 x i32> %res
+}
+
+; Uniform constant ADD
```
Comment (RKSimon) [inline llvm/test/Transforms/VectorCombine/X86/shuffle-of-binops.ll]: only shift/mul tests are likely to be useful

**Review by RKSimon — CHANGES_REQUESTED** [review]
Feedback still needs to be addressed

**Comment by KavinTheG** [comment]
- Refactored `mergeInfo(const OperandValueInfo X, const OperandValueInfo Y, bool IsEqual)` to  an OperandValueInfo member function `mergeWith(const OperandValueInfo Y)`
- Refactored variant `mergeInfo` to `commonOperandInfo` 
- Removed non-shift & non-mul tests 
- Added 
  - Variable shifts (Non-constant & non-uniform)
  - Different vector sizes
 
Perhaps I am missing something, but from what I have tried so far, only variable shifts and OK_UniformValue tests (where a value to be splat is given) produces different IR.

File: llvm/include/llvm/Analysis/TargetTransformInfo.h [hunk 4]
```diff
@@ -1254,6 +1255,19 @@ class TargetTransformInfo {
...
+      OperandValueProperties MergeProp = OP_None;
+
+      if (this->isConstant() || OpInfoY.isConstant())
+        MergeKind = OK_NonUniformConstantValue;
+      else
+        MergeKind = OK_AnyValue;
+
+      MergeProp = Properties == OpInfoY.Properties ? Properties : OP_None;
+      return {MergeKind, MergeProp};
+    }
```
Comment (RKSimon) [inline llvm/include/llvm/Analysis/TargetTransformInfo.h]: simplify:
```
    OperandValueInfo mergeWith(const OperandValueInfo OpInfoY) {
      OperandValueKind MergeKind = OK_AnyValue;
      if (isConstant() && OpInfoY.isConstant())
        MergeKind = OK_NonUniformConstantValue;
    
      OperandValueProperties MergeProp = OP_None;
	  if (Properties == OpInfoY.Properties)
	    MergeProp = Properties;
		
      return {MergeKind, MergeProp};
    }
```

**Review by RKSimon — CHANGES_REQUESTED** [review]
a few minor simplifications

**Comment by KavinTheG** [comment]
- Implemented suggest changes:
  - `Op0Info = TTI.commonOperandInfo(X, Z)` & `Op1Info` above their respective if statements
    - Removed `getOperandInfo`  call within if statements (X == Z and Y == W) as this is already performed within `commonOperandInfo`
  - Simplified `mergeWith`
  - Moved new test cases to the bottom

**Review by RKSimon — APPROVED** [review]
LGTM - cheers
