### PR TITLE
[AMDGPU] Avoid put implicit_def into bundle that break reg's liveness

### LINKED ISSUE #139102: [AMDGPU] Bundling in SIInsertHardClauses can break physical register liveness
With this [test case](https://github.com/user-attachments/files/20105970/r.txt) I get:
```
# After SI Insert Hard Clauses
# Machine code for function clause_implicit_def: IsSSA, NoPHIs, TracksLiveness, NoVRegs

bb.0:
  liveins: $vgpr0, $sgpr32
  BUNDLE implicit-def $vgpr2, implicit-def $vgpr2_lo16, implicit-def $vgpr2_hi16, implicit-def $vgpr3, implicit-def $vgpr3_lo16, implicit-def $vgpr3_hi16, implicit $vgpr0, implicit $sgpr32, implicit $exec, implicit $flat_scr, implicit $vgpr2_vgpr3 {
    S_CLAUSE 1
    SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr
    $vgpr2 = IMPLICIT_DEF
    $vgpr3 = IMPLICIT_DEF
    SCRATCH_STORE_DWORDX2_SADDR $vgpr2_vgpr3, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr
  }

# End machine code for function clause_implicit_def.

*** Bad machine code: Using an undefined physical register ***
- function:    clause_implicit_def
- basic block: %bb.0  (0x2a2d18a8)
- instruction: BUNDLE implicit-def $vgpr2, implicit-def $vgpr2_lo16, implicit-def $vgpr2_hi16, implicit-def $vgpr3, implicit-def $vgpr3_lo16, implicit-def $vgpr3_hi16, implicit $vgpr0, implicit $sgpr32, implicit $exec, implicit $flat_scr, implicit $vgpr2_vgpr3
- operand 10:   implicit $vgpr2_vgpr3

*** Bad machine code: Using an undefined physical register ***
- function:    clause_implicit_def
- basic block: %bb.0  (0x2a2d18a8)
- instruction: SCRATCH_STORE_DWORDX2_SADDR $vgpr2_vgpr3, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr
- operand 0:   $vgpr2_vgpr3
LLVM ERROR: Found 2 machine code errors.
```

### PR DESCRIPTION
**Pull request by Shoreshen**
Cause:
1. `implicit_def` inside bundle does not count for define of reg in machineinst verifier
2. Including `implicit_def` will cause relative reg not define, result in `Bad machine code: Using an undefined physical register` in the machineinst verifier

Fixes https://github.com/llvm/llvm-project/issues/139102

### CODE REVIEW

**Comment by jayfoad** [comment]
It's a workaround, not a proper fix.

**Comment by Shoreshen** [comment]
> It's a workaround, not a proper fix.

Hi @jayfoad , if I'm not wrong the implicit_def inside a bundle will not add definition of registers. So if we want to fix this, we cannot leave it inside the bundle

**Comment by jayfoad** [comment]
> > It's a workaround, not a proper fix.
> 
> Hi jayfoad , if I'm not wrong the implicit_def inside a bundle will not add definition of registers. So if we want to fix this, we cannot leave it inside the bundle

Your patch will generate worse code in some cases (because it won't be able to form hard clauses in some cases) and it only avoids one specific case of this problem.

What if some other meta instruction with an implicit-def appears in a bundle? We will have the same problem again.

What if some non-meta instruction with an implicit-def appears in a bundle? We will have the same problem again.

A better fix would be to understand how `finalizeBundle` works, and fix it to do the right thing with implicits-defs.

**Comment by Shoreshen** [comment]
Hi @jayfoad , from my perspective of view, if we want:
1. Solve the use undefined problem
2. Do not alter the logic of machine instruction verifier

We cannot include implicit_def into the bundle because inside the bundle implicit def will not count for defined register and any use of this register in the latter program will cause the verification error.

There will be bundle break by not including implicit_def. If it causes the program generate worse code, then the only possibility would be we move the implicit_def in front of the bundle. 

However, SIPostRABundler and SIInsertHardClauses are all post RA pass, which means they are not SSA. So if we move the implicit_def, we need to make sure that there is no overlap liveness for the defining register of implicit_def.

For other meta instruction with an implicit-def or other non-meta instruction with an implicit-def can be within a bundle, I think I need some time to summarize it since I'm kind of a new bee for llvm codegen. But we can solve the current problem first.

In summary:
1. To prevent both implicit_def inside the bundle and break bundle result in worse code, what we can do is: 
- if the register it is defining doesn't overlap with other instruction, move the implicit_def into the front of the bundle
- if not, break the bundle and may result in worse code
2. For other instructions that has implicit_def that can occur in the bundle, I'll read the code and try to understand the logic. We can handle all of them in this PR or solve the current problem first in this PR

**Comment by arsenm** [comment]
> We cannot include implicit_def into the bundle because inside the bundle implicit def will not count for defined register and any use of this register in the latter program will cause the verification error.

You can and should include implicit_def in the bundle. It does not matter that it's an implicit_def, the liveness of that def should work the same as any other real instruction inside the bundle. 

> if the register it is defining doesn't overlap with other instruction, move the implicit_def into the front of the bundle

You don't really need to move anything. I guess you could handle it this way, but I think it would be more difficult than just treating the implicit_def like any other load def in the bundle

**Comment by Shoreshen** [comment]
Hi @arsenm , by "cannot include implicit_def in the BUNDLE" is based on if we do not change the logic of machineinst verifer.

However, personally I think its little bit complicated because it not only create use undefined reg error for instructions inside the bundle, but also for BUNDLE inst itself since it add reg def & use to the BUNDLE inst. 

In order to solve error for BUNDLE inst itself, we can do:
1. Exclude the def & use inside the BUNDLE from the BUNDLE inst's def & use. or
2. Change the logic of verifier that do not check the reg liveness for BUNDLE inst (if use undefined reg occurs for BUNDLE itself, we need to further check inside instructions that it is not implicit defined, which act like normal reg liveness check)

Since the def & use of BUNDLE inst is hand written in different backends, it requires us to change all backend's BUNDLE creation logic if we want to use method 1.

If we use method 2, we give up opportunity to early reject bad code for BUNDLE.

So my preference is to adjust AMDGPU backend only for safety and its easier to modify. However if other method is the proper way of fixing or there maybe other methods can do better, I'm willing to implement it. Thanks

**Comment by jayfoad** [comment]
> Since the def & use of BUNDLE inst is hand written in different backends, it requires us to change all backend's BUNDLE creation logic if we want to use method 1.

No, the generic code in `finalizeBundle` does this. It looks at the operands of the instructions in the bundle, and adds corresponding operands to the BUNDLE instruction.

The idea is that the operands on the bundle should have the same overall effect as the sequence of instructions-and-operands inside the bundle. This gets a complicated when a def operand of an instruction early in the bundle gets partially redefined by a def of an overlapping register later in the bundle.

**Comment by Shoreshen** [comment]
Hi @jayfoad @arsenm , after read through `finalizeBundle` it seems like localdef cannot recognize that $vgpr2_vgpr3 was defined for their subreg $vgpr2 and $vgpr3.

I following the logic from MachineVerifier's liveness check for register that if 1 of the subreg is in localdef, then its locally defined.

This may cause problem that if we only define $vgpr2 but not $vgpr3. Currently I'm following the logic of MachineVerifier, but if needed, I think I can use regunit to avoid this problem.

Thanks for the kind help and illustration~~

**Comment by Shoreshen** [comment]
Hi @arsenm @jayfoad , would there be any unresolved issue for this PR?? Thanks

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 1]
```diff
@@ -115,6 +115,21 @@ static DebugLoc getDebugLoc(MachineBasicBlock::instr_iterator FirstMI,
...
 }
 
+static bool containRegOrSubReg(SmallSetVector<Register, 32> DefRegs,
+                               Register Reg, const TargetRegisterInfo *TRI) {
+  if (DefRegs.contains(Reg))
+    return true;
+  if (Reg.isPhysical()) {
+    for (const MCPhysReg &SubReg : TRI->subregs(Reg)) {
+      // Applying same logic with MachineVerifier that any of the SubReg is
+      // contained, it counts defined
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp]: Don't really need this comment

File: llvm/test/CodeGen/AMDGPU/bundle-break-phy-liveness.mir [hunk 2]
```diff
@@ -0,0 +1,36 @@
+# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
+# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -run-pass=si-insert-hard-clauses -verify-machineinstrs %s -o - | FileCheck -check-prefix=GCN-CLAUSE %s
+# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -run-pass=si-post-ra-bundler -verify-machineinstrs %s -o - | FileCheck -check-prefix=GCN-BUNDLE %s
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/bundle-break-phy-liveness.mir]: Shouldn't need -verify-machineinstrs.

Missing s in test name?

File: llvm/test/CodeGen/AMDGPU/bundle-break-phy-liveness.mir [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
```
Comment (arsenm) [inline llvm/test/CodeGen/AMDGPU/bundle-break-phy-liveness.mir]: Comment what this is for

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 4]
```diff
@@ -151,7 +166,7 @@ void llvm::finalizeBundle(MachineBasicBlock &MBB,
       if (!Reg)
         continue;
 
-      if (LocalDefs.contains(Reg)) {
+      if (containRegOrSubReg(LocalDefs, Reg, TRI)) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp]: What is the convention here supposed to be? Below LocalDefs inserts all subregs, but then you have to look for the subregisters at the use site? It should probably be one or the other

**Review by arsenm — COMMENTED** [review]
This is probably essentially correct, although I think this entire finalizeBundle should probably be rewritten to operate in terms of regunits, and then figure out how to turn that into physical register references at the end

File: llvm/lib/CodeGen/MachineInstrBundle.cpp (hunk 4 above)
Comment (Shoreshen) [reply llvm/lib/CodeGen/MachineInstrBundle.cpp]: Hi @arsenm , this is the other way around. While `LocalDefs` contains all the reg and subreg that inserted, but it does not contain any "super" reg that formed by regs in it. 

So this is used to check if the `Reg`'s subreg was contained in `LocalDefs`

**Comment by Shoreshen** [comment]
> This is probably essentially correct, although I think this entire finalizeBundle should probably be rewritten to operate in terms of regunits, and then figure out how to turn that into physical register references at the end

Hi @arsenm , I think you are right, I'll separate `LocalDefs` for physical and virtual (since I don't know if they will overlap) and use regunit for physical

File: llvm/lib/CodeGen/MachineInstrBundle.cpp (hunk 4 above)
Comment (arsenm) [reply llvm/lib/CodeGen/MachineInstrBundle.cpp]: Yes, so in that case you can just insert the raw register into the set. The query you're doing would then look at all aliasing registers references with MCRegAliasIterator

**Review by arsenm — CHANGES_REQUESTED** [review]
For the purposes of this patch, you should not be trying to do the switch to register units. Now you're mixing both physregs and regunits.

As far as what you track in the set, I think you would be better off tracking the registers as they appear (as in, stop using insert_range(subregs()) when you encounter them), and leave the iterating through MCRegAliasIterator for the query

**Comment by jayfoad** [comment]
Before going much further with this I think it would be good to have a way of directly testing the result of finalizeBundle on an arbitrary sequence of MachineInstrs. If there's no way to do that as a CodeGen test then maybe we need something in unittests?

**Comment by Shoreshen** [comment]
> Before going much further with this I think it would be good to have a way of directly testing the result of finalizeBundle on an arbitrary sequence of MachineInstrs. If there's no way to do that as a CodeGen test then maybe we need something in unittests?

Hi @jayfoad , I think we can use verification wit MIR to test this:
1. If a physical reg is not fully defined when using, it will not be marked internal
2. If the used reg is not marked as internal, verification will check if the reg (or any of the subreg) has been defined before
3. If we do not define the subreg before, it will dump a bad code error

I think we may not need to test arbitrary sequence of insts since we don't need to tests inst seq that cannot be bundled??

**Comment by jayfoad** [comment]
> I think we may not need to test arbitrary sequence of insts since we don't need to tests inst seq that cannot be bundled??

The whole point of unit testing is that you can test all the edge cases, not just the cases that currently occur in practice. I am suggesting we should do that for finalizeBundle. I'm just not sure exactly _how_ to do it.

**Comment by Shoreshen** [comment]
> > I think we may not need to test arbitrary sequence of insts since we don't need to tests inst seq that cannot be bundled??
> 
> The whole point of unit testing is that you can test all the edge cases, not just the cases that currently occur in practice. I am suggesting we should do that for finalizeBundle. I'm just not sure exactly _how_ to do it.

Hi @jayfoad , this patch fix the following situation:
1. physical registers are separately defined inside the bundle, e.g. we define SGPR1 and SGPR2 in 2 different insts
2. their "super" register was used in side the bundle. e.g. we use SGPR1_SGPR2 in some inst

In this situation, we should regard the "super" as internal for the bundle instruction.

I'm not sure what should we try to test by using unit tests. Simply from the functionality, we can use MIR tests in my point of view...

Thanks

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 5]
```diff
@@ -165,8 +179,10 @@ void llvm::finalizeBundle(MachineBasicBlock &MBB,
         }
       }
 
-      if (!MO.isDead() && Reg.isPhysical())
-        LocalDefs.insert_range(TRI->subregs(Reg));
+      if (!MO.isDead() && Reg.isPhysical()) {
+        for (MCRegUnit Unit : TRI->regunits(MCRegister::from(Reg.id())))
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:183]:
```suggestion
        for (MCRegUnit Unit : TRI->regunits(Reg.asMCReg())))
```

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 6]
```diff
@@ -94,6 +94,19 @@ static DebugLoc getDebugLoc(MachineBasicBlock::instr_iterator FirstMI,
   return DebugLoc();
 }
 
+static bool containReg(SmallSetVector<Register, 32> LocalDefsV,
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:97]:
```suggestion
static bool containsReg(SmallSetVector<Register, 32> LocalDefsV,
```

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 7]
```diff
@@ -94,6 +94,19 @@ static DebugLoc getDebugLoc(MachineBasicBlock::instr_iterator FirstMI,
...
+                       const BitVector &LocalDefsP, Register Reg,
+                       const TargetRegisterInfo *TRI) {
+  if (Reg.isPhysical()) {
+    for (MCRegUnit Unit : TRI->regunits(Reg.asMCReg()))
+      if (!LocalDefsP[Unit])
+        return false;
+
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:104]:
```suggestion
    for (MCRegUnit Unit : TRI->regunits(Reg.asMCReg())) {
      if (!LocalDefsP[Unit])
        return false;
    }

```

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 8]
```diff
@@ -130,7 +144,7 @@ void llvm::finalizeBundle(MachineBasicBlock &MBB,
       if (!Reg)
         continue;
 
-      if (LocalDefs.contains(Reg)) {
+      if (containReg(LocalDefs, LocalDefsP, Reg, TRI)) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:147]:
```suggestion
      if (containsReg(LocalDefs, LocalDefsP, Reg, TRI)) {
```

File: llvm/lib/CodeGen/MachineInstrBundle.cpp (hunk 6 above)
Comment (arsenm) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:97]: Document that LocalDefsV is for virtual registers, and LocalDefsP for physregs

**Review by arsenm — APPROVED** [review]

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 9]
```diff
@@ -165,8 +182,10 @@ void llvm::finalizeBundle(MachineBasicBlock &MBB,
         }
       }
 
-      if (!MO.isDead() && Reg.isPhysical())
-        LocalDefs.insert_range(TRI->subregs(Reg));
```
Comment (jayfoad) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:169]: This part is really nice since it avoids adding lots of redundant defs of subregisters to the BUNDLE. This is responsible for most of the test case diffs.

File: llvm/lib/CodeGen/MachineInstrBundle.cpp [hunk 10]
```diff
@@ -94,6 +94,22 @@ static DebugLoc getDebugLoc(MachineBasicBlock::instr_iterator FirstMI,
...
 }
 
+/// Check if target reg is contained in given lists, which are:
+/// LocalDefsV as given list for virtual regs
+/// LocalDefsP as given list for physical regs, in BitVector[RegUnit] form
+static bool containsReg(SmallSetVector<Register, 32> LocalDefsV,
+                        const BitVector &LocalDefsP, Register Reg,
+                        const TargetRegisterInfo *TRI) {
+  if (Reg.isPhysical()) {
+    for (MCRegUnit Unit : TRI->regunits(Reg.asMCReg()))
```
Comment (jayfoad) [inline llvm/lib/CodeGen/MachineInstrBundle.cpp:104]: This could use `all_of`.

The effect of this is to treat a physreg use as internal if all of its regunits were defined locally, regardless of whether that was a single local def of the whole register or multiple local defs of subregisters. This makes sense to me.

**Review by jayfoad — COMMENTED** [review]
Just adding some comments for posterity, mostly for my own understanding. The description of this PR was never updated to explain what it does.
