### PR TITLE
[Clang] Fix constexpr __builtin_(add|sub|mul)_overflow bugs

### LINKED ISSUE #204085: [clang] constexpr `__builtin_mul_overflow` returns wrong result for non-byte-aligned `_BitInt(N)`
## Summary

At compile time, `__builtin_mul_overflow` returns the wrong result for `_BitInt(N)` operands when N is not a multiple of 8 (e.g. `_BitInt(13)`). The runtime path is correct. Already fixed on trunk by PR #192568 (merged 2026-04-23); Clang 21 and 22 releases still ship the bug.

## Reproducer

https://godbolt.org/z/dbnbeafbf

```cpp
constexpr signed _BitInt(13) f() {
  signed _BitInt(13) r;
  __builtin_mul_overflow((signed _BitInt(13))-2, (signed _BitInt(13))3, &r);
  return r;
}
static_assert(f() == (signed _BitInt(13))-6);
```

Clang 21 and 22 reject the static_assert:

```
error: static assertion failed due to requirement 'f() == (_BitInt(13))-6'
note: expression evaluates to '-6 == -6'
```

The diagnostic prints `-6 == -6` and the assertion still fires: the compile-time multiplication stores its result at the storage width (16 bits for `_BitInt(13)`) instead of the integer width (13 bits), so the value does not compare equal to a freshly-constructed `_BitInt(13)` value of -6.

## Impact

`std::saturating_{add,sub,mul}` in libc++ and any C++ code calling `__builtin_*_overflow` with `_BitInt(N)` operands at compile time silently produce wrong values on Clang 21 and 22.

## Fix

[PR #192568](https://github.com/llvm/llvm-project/pull/192568) replaced `getTypeSize(ResultType)` with `getIntWidth(ResultType)` in `clang/lib/AST/ExprConstant.cpp`. Will ship in Clang 23.

### PR DESCRIPTION
**Pull request by widberg**
Fixes

1. constexpr/non-constexpr add overflowed disagree for 1 + 1 with a bool result https://godbolt.org/z/4Goaa63sc. I found this issue for a similar bug https://github.com/llvm/llvm-project/issues/40897.
2. constexpr unsigned assertion https://godbolt.org/z/MEahfsW9E.
3. constexpr bool result assertion https://godbolt.org/z/G3YsxozbE.

Fixes #204085.

Related CIR PR #192569.

### CODE REVIEW

File: clang/lib/AST/ByteCode/InterpBuiltin.cpp [hunk 1]
```diff
@@ -136,6 +136,8 @@ static void assignInteger(InterpState &S, const Pointer &Dest, PrimType ValueT,
     Dest.deref<IntegralAP<false>>() =
         S.allocAP<IntegralAP<false>>(Value.getBitWidth());
     Dest.deref<IntegralAP<false>>().copy(Value);
+  } else if (ValueT == PT_Bool) {
+    Dest.deref<Boolean>() = Boolean::from(!Value.isZero());
```
Comment (ojhunt) [inline clang/lib/AST/ByteCode/InterpBuiltin.cpp:140]: I don't think this change is correct.

I think the correct behavior is for the overflow functions to check for boolean values on assignment, or possibly add 

```cpp
static void assignToIntegralType(InterpState &S, const Pointer &Dest, PrimType ValueT,
                          const APSInt &Value) {
if (ValueT == PT_Bool)
  Dest.deref<Boolean>() = Boolean::from(!Value.isZero());
else
  assignToInteger(S, Dest, ValueT, Value);
```

and use that. The code in assignInteger seems to intentionally exclude bool assignment.

File: clang/test/AST/ByteCode/builtin-functions.cpp [hunk 2]
```diff
@@ -1964,6 +1964,29 @@ namespace I128Mul {
 }
 #endif
 
+namespace OverflowOps {
+  constexpr bool add_bool() {
+    bool r = false;
+    return __builtin_add_overflow(1u, 1u, &r) && r == false;
+  }
+  static_assert(add_bool());
```
Comment (ojhunt) [inline clang/test/AST/ByteCode/builtin-functions.cpp:1972]: add non-overflow tests as well - we already know that definitionally there are no tests for that because they're be broken by the bug you're fixing here

**Review by ojhunt — CHANGES_REQUESTED** [review]
I think the change to assignInteger is not right, but @tbaederr is the expert here

File: clang/lib/AST/ByteCode/InterpBuiltin.cpp (hunk 1 above)
Comment (tbaederr) [reply clang/lib/AST/ByteCode/InterpBuiltin.cpp:140]: I generally agree but I don't think it's worth it in this file. I'd rename the function to `assignIntegral` at best.

**Review by tbaederr — APPROVED** [review]
Rest looks fine.

**Review by ojhunt — APPROVED** [review]
LGTM as well given @tbaederr is ok with assignIntegral

File: clang/test/AST/ByteCode/builtin-functions.cpp [hunk 3]
```diff
@@ -1964,6 +1964,53 @@ namespace I128Mul {
 }
 #endif
 
+namespace OverflowOps {
+  constexpr bool add_bool() {
+    bool r = false;
+    return __builtin_add_overflow(1u, 1u, &r) && r == false;
```
Comment (shafik) [inline clang/test/AST/ByteCode/builtin-functions.cpp:1970]: I am curious what we expect for:

```cpp
constexpr bool add_bool() {
    bool r = false;
    return __builtin_add_overflow(true, true, &r) && r == false;
  }
  static_assert(add_bool());
```

I would also note gcc does not seem to like the third argument: https://gcc.godbolt.org/z/nT56hx935

Comment (widberg) [reply clang/test/AST/ByteCode/builtin-functions.cpp:1970]: Personally, I would expect that to compile, as it does right now. At least based on my understanding of the docs https://clang.llvm.org/docs/LanguageExtensions.html#checked-arithmetic-builtins. Also, GCC isn't happy because it explicitly forbids bools (https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html), whereas Clang explicitly allows them.

Comment (shafik) [reply clang/test/AST/ByteCode/builtin-functions.cpp:1970]: Can we add tests cases like this?
