### PR TITLE
[clang-format] Add Automatic and ExceptShortType options for AlwaysBreakAfterReturnType.

### LINKED ISSUE #78010: [clang-format] Ability to configure breaking after short return types
Currently, when ` AlwaysBreakAfterReturnType` is `None`, line breaks are prevented after 'short' return types.

From `ContinuationIndenter.cpp`
```
// Don't break after very short return types (e.g. "void") as that is often
// unexpected.
if (Current.is(TT_FunctionDeclarationName) && State.Column < 6) {
  if (Style.AlwaysBreakAfterReturnType == FormatStyle::RTBS_None)
    return false;
}
```

Note, that 'short' here isn't the length of the type itself, but the column where the type finishes.
So, the indentation can change the behaviour.

While the comment says that breaking would be unexpected, this behaviour takes precedence over any of the penalty options for configuring where to place line breaks. It is fairly specific behaviour and can also be unexpected as it avoids breaking after the return type seemly ignoring the penalty configuration.

It would be helpful if there was a way that this could be configured.

### PR DESCRIPTION
**Pull request by rmarker**
The RTBS_None option in Clang-format avoids breaking after a short return type.
However, there was an issue with the behaviour in that it wouldn't take the leading indentation of the line into account.
This meant that the behaviour wasn't applying when intended.

In order to address this situation without breaking the existing formatting, RTBS_None has been deprecated.
In its place are two new options for AlwaysBreakAfterReturnType.
The option RTBS_Automatic will break after the return type based on PenaltyReturnTypeOnItsOwnLine.
The option RTBS_ExceptShortType will take the leading indentation into account and prevent breaking after short return types.

This allows the inconsistent behaviour of RTBS_None to be avoided and users to decide whether they want to allow breaking after short return types or not.

Resolves #78010

### CODE REVIEW

File: clang/include/clang/Format/Format.h [hunk 1]
```diff
@@ -3928,6 +3928,13 @@ struct FormatStyle {
   /// \version 13
   unsigned ShortNamespaceLines;
 
+  /// When AlwaysBreakAfterReturnType is None, line breaks are prevented after
+  /// short return types. This configures the character limit for a type to be
+  /// regarded as short. Note that this isn't the length of the type itself,
+  /// but the column where it finishes. I.e. it includes indentation, etc.
+  /// \version 18
+  unsigned ShortReturnTypeLength;
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Yeah, that's much nicer.

File: clang/include/clang/Format/Format.h [hunk 2]
```diff
@@ -3928,6 +3928,13 @@ struct FormatStyle {
   /// \version 13
   unsigned ShortNamespaceLines;
 
+  /// When AlwaysBreakAfterReturnType is None, line breaks are prevented after
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Done.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by rmarker** [comment]
Merged main and fixed conflicts.

**Comment by rmarker** [comment]
@mydeveloperday, do you have an opinion on this pull request?
It addresses #78010 with minimal changes, or are you interested in exploring other possibilities?

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by HazardyKnusperkeks** [comment]
Just ping me in a few days, if there is no other reaction and we merge it.

**Comment by owenca** [comment]
> @mydeveloperday, do you have an opinion on this pull request? It addresses #78010 with minimal changes, or are you interested in exploring other possibilities?

It's weird to add such a top-level option to fix a bug and keep the current behavior. See https://github.com/llvm/llvm-project/issues/78010#issuecomment-1903300176.

**Comment by rmarker** [comment]
Merged main and fixed conflicts.
Also updated version badge to 19 with the recent branching for 18.
Keeping things up to date whilst discussion about the underlying issue continues on #78010.

**Comment by rmarker** [comment]
Reworked this PR with a new approach, as discussed in #78010.

`ShortReturnTypeColumn` has been replaced with a new enum option `RTBS_AllowShortType` for `AlwaysBreakAfterReturnType `.
Also, the short return type behaviour has been updated to ignore the leading indentation on the line.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 3]
```diff
@@ -587,7 +589,9 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
       !State.Line->ReturnTypeWrapped &&
       // Don't break before a C# function when no break after return type.
       (!Style.isCSharp() ||
-       Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
+       (Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None &&
+        Style.AlwaysBreakAfterReturnType !=
+            FormatStyle::RTBS_AllowShortType)) &&
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/lib/Format/ContinuationIndenter.cpp]: Nice.

File: clang/unittests/Format/FormatTest.cpp [hunk 4]
```diff
@@ -9872,9 +9872,30 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
...
+               Style);
+
+  // It is now allowed to break after a short return type if necessary.
+  Style.AlwaysBreakAfterReturnType = FormatStyle::RTBS_AllowShortType;
+  verifyFormat("class A {\n"
+               "  int f() { return 1; }\n"
+               "  int g();\n"
+               "  long\n"
+               "  "
+               "fooooooooooooooooooooooooooooooooooooooooooooooo::"
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Using `ColumnLimit` is a good idea.

File: clang/unittests/Format/FormatTest.cpp [hunk 5]
```diff
@@ -9891,13 +9912,20 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
                "  }\n"
                "  int\n"
                "  g();\n"
+               "  long\n"
+               "  "
+               "fooooooooooooooooooooooooooooooooooooooooooooooo::"
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Done.

File: clang/unittests/Format/FormatTest.cpp [hunk 6]
```diff
@@ -9906,12 +9934,19 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
   verifyFormat("class B {\n"
                "  int f() { return 1; }\n"
                "  int g();\n"
+               "  long\n"
+               "  "
+               "fooooooooooooooooooooooooooooooooooooooooooooooo::"
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Done.

File: clang/unittests/Format/FormatTest.cpp [hunk 7]
```diff
@@ -9920,13 +9955,20 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
   verifyFormat("class C {\n"
                "  int f() { return 1; }\n"
                "  int g();\n"
+               "  long\n"
+               "  "
+               "fooooooooooooooooooooooooooooooooooooooooooooooo::"
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Done.

File: clang/unittests/Format/FormatTest.cpp [hunk 8]
```diff
@@ -9938,12 +9980,19 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
                "    return 1;\n"
                "  }\n"
                "  int g();\n"
+               "  long\n"
+               "  "
+               "fooooooooooooooooooooooooooooooooooooooooooooooo::"
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Done.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 9]
```diff
@@ -326,11 +326,13 @@ bool ContinuationIndenter::canBreak(const LineState &State) {
...
 
-  // Don't break after very short return types (e.g. "void") as that is often
-  // unexpected.
-  if (Current.is(TT_FunctionDeclarationName) && State.Column < 6) {
-    if (Style.AlwaysBreakAfterReturnType == FormatStyle::RTBS_None)
+  if (Style.AlwaysBreakAfterReturnType == FormatStyle::RTBS_None) {
+    // Don't break after very short return types (e.g. "void") as that is often
+    // unexpected.
+    if (Current.is(TT_FunctionDeclarationName) &&
+        State.Column - State.FirstIndent < 6) {
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/lib/Format/ContinuationIndenter.cpp:334]: Yep.

File: clang/docs/ClangFormatStyleOptions.rst [hunk 10]
```diff
@@ -146,7 +146,7 @@ the configuration (without a prefix: ``Auto``).
 
 .. _BasedOnStyle:
 
-**BasedOnStyle** (``String``) :ref:`¶ <BasedOnStyle>`
+**BasedOnStyle** (``String``) :ref:`Ã‚Â¶ <BasedOnStyle>`
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/docs/ClangFormatStyleOptions.rst]: Yes it was generated on Windows.
My guess is the platform is causing it to default to the wrong encoding.
I had a look at the script and discovered that forcing the encoding to utf-8 when reading the contents stopped it inserting the spurious characters.

**Comment by rmarker** [comment]
Addressed feedback.

**Comment by owenca** [comment]
This would break polly:
```
$ ninja polly-check-format
[27/105] Checking format of /Users/Owe...ude/polly/CodeGen/BlockGenerators.h...
FAILED: tools/polly/polly-check-format1 /Users/Owen/llvm-project/build/tools/polly/polly-check-format1 
cd /Users/Owen/llvm-project/build/tools/polly && /Users/Owen/llvm-project/build/bin/clang-format -sort-includes -style=llvm /Users/Owen/llvm-project/polly/include/polly/CodeGen/BlockGenerators.h | diff -u /Users/Owen/llvm-project/polly/include/polly/CodeGen/BlockGenerators.h -
--- /Users/Owen/llvm-project/polly/include/polly/CodeGen/BlockGenerators.h	2024-01-05 20:58:16
+++ -	2024-01-26 23:25:21
@@ -794,9 +794,9 @@
   /// @param BBMap A mapping from old values to their new values in this block.
   /// @param LTS   A mapping from loops virtual canonical induction variable to
   /// their new values.
-  void
-  generateScalarStores(ScopStmt &Stmt, LoopToScevMapT &LTS, ValueMapT &BBMAp,
-                       __isl_keep isl_id_to_ast_expr *NewAccesses) override;
+  void generateScalarStores(
+      ScopStmt &Stmt, LoopToScevMapT &LTS, ValueMapT &BBMAp,
+      __isl_keep isl_id_to_ast_expr *NewAccesses) override;
 
   /// Copy a single PHI instruction.
   ///
[36/105] Checking format of /Users/Owe...ject/polly/include/polly/ScopInfo.h...
FAILED: tools/polly/polly-check-format35 /Users/Owen/llvm-project/build/tools/polly/polly-check-format35 
cd /Users/Owen/llvm-project/build/tools/polly && /Users/Owen/llvm-project/build/bin/clang-format -sort-includes -style=llvm /Users/Owen/llvm-project/polly/include/polly/ScopInfo.h | diff -u /Users/Owen/llvm-project/polly/include/polly/ScopInfo.h -
--- /Users/Owen/llvm-project/polly/include/polly/ScopInfo.h	2024-01-22 03:28:44
+++ -	2024-01-26 23:25:21
@@ -1987,8 +1987,8 @@
   void addAccessData(MemoryAccess *Access);
 
   /// Add new invariant access equivalence class
-  void
-  addInvariantEquivClass(const InvariantEquivClassTy &InvariantEquivClass) {
+  void addInvariantEquivClass(
+      const InvariantEquivClassTy &InvariantEquivClass) {
     InvariantEquivClasses.emplace_back(InvariantEquivClass);
   }
 
ninja: build stopped: subcommand failed.
```

**Comment by owenca** [comment]
OTOH, if we change `LLVMStyle.AlwaysBreakAfterReturnType` to `RTBS_AllowShortType`, we get the following:
```
$ ninja polly-check-format
[24/105] Checking format of /Users/Owe...olly/include/polly/DependenceInfo.h...
FAILED: tools/polly/polly-check-format16 /Users/Owen/llvm-project/build/tools/polly/polly-check-format16 
cd /Users/Owen/llvm-project/build/tools/polly && /Users/Owen/llvm-project/build/bin/clang-format -sort-includes -style=llvm /Users/Owen/llvm-project/polly/include/polly/DependenceInfo.h | diff -u /Users/Owen/llvm-project/polly/include/polly/DependenceInfo.h -
--- /Users/Owen/llvm-project/polly/include/polly/DependenceInfo.h	2024-01-05 20:24:43
+++ -	2024-01-27 02:13:13
@@ -332,8 +332,8 @@
 void initializeDependenceInfoPass(llvm::PassRegistry &);
 void initializeDependenceInfoPrinterLegacyPassPass(llvm::PassRegistry &);
 void initializeDependenceInfoWrapperPassPass(llvm::PassRegistry &);
-void initializeDependenceInfoPrinterLegacyFunctionPassPass(
-    llvm::PassRegistry &);
+void
+initializeDependenceInfoPrinterLegacyFunctionPassPass(llvm::PassRegistry &);
 } // namespace llvm
 
 #endif
[26/105] Checking format of /Users/Owe...polly/include/polly/LinkAllPasses.h...
FAILED: tools/polly/polly-check-format21 /Users/Owen/llvm-project/build/tools/polly/polly-check-format21 
cd /Users/Owen/llvm-project/build/tools/polly && /Users/Owen/llvm-project/build/bin/clang-format -sort-includes -style=llvm /Users/Owen/llvm-project/polly/include/polly/LinkAllPasses.h | diff -u /Users/Owen/llvm-project/polly/include/polly/LinkAllPasses.h -
--- /Users/Owen/llvm-project/polly/include/polly/LinkAllPasses.h	2024-01-05 20:58:16
+++ -	2024-01-27 02:13:13
@@ -138,8 +138,8 @@
 void initializeDependenceInfoPass(llvm::PassRegistry &);
 void initializeDependenceInfoPrinterLegacyPassPass(llvm::PassRegistry &);
 void initializeDependenceInfoWrapperPassPass(llvm::PassRegistry &);
-void initializeDependenceInfoPrinterLegacyFunctionPassPass(
-    llvm::PassRegistry &);
+void
+initializeDependenceInfoPrinterLegacyFunctionPassPass(llvm::PassRegistry &);
 void initializeIslAstInfoWrapperPassPass(llvm::PassRegistry &);
 void initializeIslAstInfoPrinterLegacyPassPass(llvm::PassRegistry &);
 void initializeCodeGenerationPass(llvm::PassRegistry &);
[33/105] Checking format of /Users/Owe...ect/polly/unittests/Isl/IslTest.cpp...
ninja: build stopped: subcommand failed.
```
which is an improvement IMO.

**Comment by rmarker** [comment]
Sounds good.

Updated formatting in polly.

**Comment by owenca** [comment]
@llvm/pr-subscribers-clang-format this patch fixes a very old bug and will cause behavior changes whether the default is changed to the new `AllowShortType` or left at `None`. Which way should we go?

**Comment by rmarker** [comment]
Updated FormatTests to account for the change to the style.
(Forgetting them is what I get for coding late).

This should help when evaluating the scope of the change.

File: clang/include/clang/Format/Format.h [hunk 11]
```diff
@@ -922,8 +922,23 @@ struct FormatStyle {
...
+    ///   };
+    ///   int f();
+    ///   int f() { return 1; }
+    ///   int
+    ///   foooooooooooooooooooooooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaaar();
+    /// \endcode
+    RTBS_AllowShortType,
     /// Always break after the return type.
     /// \code
     ///   class A {
```
Comment (HazardyKnusperkeks) [inline clang/include/clang/Format/Format.h:944]: Shouldn't it be added in this block also?

File: clang/include/clang/Format/Format.h [hunk 12]
```diff
@@ -922,8 +922,23 @@ struct FormatStyle {
     ///   };
     ///   int f();
     ///   int f() { return 1; }
+    ///   int foooooooooooooooooooooooooooooooooooooooooooooooo::
```
Comment (HazardyKnusperkeks) [inline clang/include/clang/Format/Format.h:925]: I'd go with short names, and just name them like `LongName` or similar and just break. This is documentation which should convey the settings, and must not break with LLVMs standard column limit.

File: clang/include/clang/Format/Format.h [hunk 13]
```diff
@@ -922,8 +922,23 @@ struct FormatStyle {
...
+    ///       baaaaaaaaaaaaaaaaaaaaar();
     /// \endcode
     RTBS_None,
+    /// Break after return type automatically, while allowing a break after
+    /// short return types.
```
Comment (HazardyKnusperkeks) [inline clang/include/clang/Format/Format.h:930]: This should be rephrased, I know what the option means, but I couldn't figure it out of the description.

File: clang/lib/Format/ContinuationIndenter.cpp [hunk 14]
```diff
@@ -587,7 +590,7 @@ bool ContinuationIndenter::mustBreak(const LineState &State) {
       !State.Line->ReturnTypeWrapped &&
       // Don't break before a C# function when no break after return type.
       (!Style.isCSharp() ||
-       Style.AlwaysBreakAfterReturnType != FormatStyle::RTBS_None) &&
+       Style.AlwaysBreakAfterReturnType > FormatStyle::RTBS_AllowShortType) &&
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/ContinuationIndenter.cpp:593]: I know Owen proposed this. But I have to note, that I personally really don't like greater or lesser with enums.

**Comment by HazardyKnusperkeks** [comment]
> @mydeveloperday @HazardyKnusperkeks @rymiel this patch fixes a very old bug and will cause behavior changes whether the default is changed to the new `AllowShortType` or left at `None`. Which way should we go?

What would change if the default was kept at `None`? I don't see it.

**Comment by owenca** [comment]
> What would change if the default was kept at `None`? I don't see it.

See https://github.com/llvm/llvm-project/pull/78011#issuecomment-1913052884.

**Comment by owenca** [comment]
> @mydeveloperday @HazardyKnusperkeks @rymiel this patch fixes a very old bug and will cause behavior changes whether the default is changed to the new `AllowShortType` or left at `None`. Which way should we go?

Now I'm leaning toward keeping the existing (buggy) behavior of `None` and using the new `AllowShortType` to allow wrapping after short return types.

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 14 above)
Comment (owenca) [reply clang/lib/Format/ContinuationIndenter.cpp:593]: What I suggested is more consistent with the existing code in clang-format. Also, explicitly including/excluding every enum value is cumbersome and doesn't provide any real advantage, IMO.

File: clang/docs/tools/dump_format_style.py [hunk 15]
```diff
@@ -474,7 +474,7 @@ class State:
 opts = sorted(opts, key=lambda x: x.name)
 options_text = "\n\n".join(map(str, opts))
 
-with open(DOC_FILE) as f:
+with open(DOC_FILE, encoding="utf-8") as f:
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/docs/tools/dump_format_style.py]: Moved change to its own PR. #79805

File: clang/include/clang/Format/Format.h (hunk 11 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h:945]: Yes, it should indeed be added.

File: clang/include/clang/Format/Format.h (hunk 13 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: I made another attempt at being clearer.
What do you think?

**Comment by rmarker** [comment]
> > @mydeveloperday @HazardyKnusperkeks @rymiel this patch fixes a very old bug and will cause behavior changes whether the default is changed to the new `AllowShortType` or left at `None`. Which way should we go?
> 
> Now I'm leaning toward keeping the existing (buggy) behavior of `None` and using the new `AllowShortType` to allow wrapping after short return types.

Yeah, it is a tricky trade-off.
The addition of `AllowShortType`, does alleviate the buggy behaviour and addresses the issue.

I can undo the fix for determining what types are short, if you think that is the way to go after the seeing the results.
I assume that this would also include changing the `LLVMStyle.AlwaysBreakAfterReturnType` back to `None`?

File: clang/lib/Format/ContinuationIndenter.cpp (hunk 14 above)
Comment (HazardyKnusperkeks) [reply clang/lib/Format/ContinuationIndenter.cpp:593]: I know, just wanted to state my opinion. The cumbersome part could be extracted into a function. I just don't like treating enums as numbers in general. Sometimes there are exceptions, but in my opinion I would use this in clang-format only for `Standard`.

File: clang/include/clang/Format/Format.h (hunk 13 above)
Comment (HazardyKnusperkeks) [reply clang/include/clang/Format/Format.h]: Better.

**Comment by rmarker** [comment]
> > > @mydeveloperday @HazardyKnusperkeks @rymiel this patch fixes a very old bug and will cause behavior changes whether the default is changed to the new `AllowShortType` or left at `None`. Which way should we go?
> > 
> > 
> > Now I'm leaning toward keeping the existing (buggy) behavior of `None` and using the new `AllowShortType` to allow wrapping after short return types.
> 
> Buggy would be no break? That would be what I expect from `None`. :) So +1 from me.

`None` prevents breaks after short return types. The buggy behaviour is that it doesn't take leading indentation into account when determining if a return type is short or not. This means that if there is indentation, it wouldn't think a type is short that otherwise would be, and would thus allow a break after the return type.
Fixing the bug would cause return types in more situations to be identified as short and thus prevent breaks previously allowed (changing the previous behaviour).

 ```
 // Buggy None
void LongName::
      AnotherLongName();
class C {
   void
   LongName::AnotherLongName();
};

// Fixed None
void LongName::
      AnotherLongName();
class C {
   void LongName::
        AnotherLongName();
};
 ```

**Comment by owenca** [comment]
Let's leave `None` alone and add `ExceptShortType`, e.g.:
```
--- a/clang/lib/Format/ContinuationIndenter.cpp
+++ b/clang/lib/Format/ContinuationIndenter.cpp
@@ -329,12 +329,18 @@ bool ContinuationIndenter::canBreak(const LineState &State) {
   // Don't break after very short return types (e.g. "void") as that is often
   // unexpected.
   if (Current.is(TT_FunctionDeclarationName) && State.Column < 6) {
     if (Style.AlwaysBreakAfterReturnType == FormatStyle::RTBS_None)
       return false;
   }
+  if (Current.is(TT_FunctionDeclarationName) &&
+      Style.AlwaysBreakAfterReturnType == FormatStyle::RTBS_ExceptShortType) {
+    assert(State.Column >= State.FirstIndent);
+    if (State.Column - State.FirstIndent < 6)
+      return false;
+  }
 
   // If binary operators are moved to the next line (including commas for some
   // styles of constructor initializers), that's always ok.
   if (!Current.isOneOf(TT_BinaryOperator, tok::comma) &&
       // Allow breaking opening brace of lambdas (when passed as function
       // arguments) to a new line when BeforeLambdaBody brace wrapping is
```

**Comment by rmarker** [comment]
Right, I'll look into adding `ExceptShortType`.

**Comment by rmarker** [comment]
@owenca, thinking on it, do you think `NeverShortType` would be a better name?
I'm wondering whether `ExceptShortType` could imply that non-short return types are always broken after.

**Comment by owenca** [comment]
> Let's leave `None` alone and add `ExceptShortType`

I meant to add `ExceptShortType` instead of `AllowShortType`. Sorry I didn't realize that adding `AllowShortType` and making it to mean "not `None`" might work, in which case we don't need to add `ExceptShortType`.

**Comment by rmarker** [comment]
> > Let's leave `None` alone and add `ExceptShortType`
> 
> I meant to add `ExceptShortType` instead of `AllowShortType`. Sorry I didn't realize that adding `AllowShortType` and making it to mean "not `None`" might work, in which case we don't need to add `ExceptShortType`.

No problem.

Now that we've got both options, should we keep them?
Currently, `None` sometimes forbids breaking after short return types and sometimes allows it and just bases things off the penalty configuration. I feel like there will be some people who use `None` who would want the behaviour to be consistent one way and the other group wanting it consistent the opposite. With both, they can decide for themselves. Especially since the implementation for both is pretty simple and self-contained.

Though, if we only go with one, my vote would be for allowing breaking after short return types.
That is what we were using `None` for at work. I only discovered the issue, and the short return type concept at all, when investigating why it wasn't breaking in a few odd places we couldn't understand.

**Comment by owenca** [comment]
> Now that we've got both options, should we keep them? Currently, `None` sometimes forbids breaking after short return types and sometimes allows it and just bases things off the penalty configuration. I feel like there will be some people who use `None` who would want the behaviour to be consistent one way and the other group wanting it consistent the opposite. With both, they can decide for themselves. Especially since the implementation for both is pretty simple and self-contained.

+1. In addition, we should deprecate `None` (in documentation only) and rename `AllowShortType` to `Automatic`, followed by `ExceptShortType` which means "`Automatic` except for short return types". Then IMO `ExceptShortType` is unambiguous. If you still think `NeverShortType` is clearer, I would change it to `NotShortType`.

File: clang/include/clang/Format/Format.h [hunk 16]
```diff
@@ -922,8 +922,39 @@ struct FormatStyle {
...
+    /// \code
+    ///   class A {
+    ///     int f() { return 0; };
+    ///   };
+    ///   int f();
+    ///   int f() { return 1; }
+    ///   int
+    ///   LongName::AnotherLongName();
+    /// \endcode
+    RTBS_AllowShortType,
```
Comment (owenca) [inline clang/include/clang/Format/Format.h:942]:
```suggestion
    RTBS_Automatic,
```

File: clang/include/clang/Format/Format.h [hunk 17]
```diff
@@ -922,8 +922,39 @@ struct FormatStyle {
     ///   };
     ///   int f();
     ///   int f() { return 1; }
+    ///   int LongName::
+    ///       AnotherLongName();
     /// \endcode
```
Comment (owenca) [inline clang/include/clang/Format/Format.h:927]: Change the comments (lines 917-927) to something like the following:
```
    /// This is **deprecated**. See ``Automatic`` below.
```

File: clang/include/clang/Format/Format.h [hunk 18]
```diff
@@ -922,8 +922,39 @@ struct FormatStyle {
...
     RTBS_None,
+    /// Break after return type automatically.
+    /// This mode doesn't have the same inherent restriction on breaking after
+    /// short return types as ``RTBS_None`` and is solely based on
+    /// ``PenaltyReturnTypeOnItsOwnLine``.
```
Comment (owenca) [inline clang/include/clang/Format/Format.h:932]: For example:
```suggestion
    /// Break after return type based on ``PenaltyReturnTypeOnItsOwnLine``.
```

File: clang/include/clang/Format/Format.h [hunk 19]
```diff
@@ -922,8 +922,39 @@ struct FormatStyle {
...
+    ///   int f() { return 1; }
+    ///   int
+    ///   LongName::AnotherLongName();
+    /// \endcode
+    RTBS_AllowShortType,
+    /// Break after return type automatically.
+    /// ``PenaltyReturnTypeOnItsOwnLine`` is taken into account.
+    /// This mode will never break after short return types, unlike
+    /// ``RTBS_None`` which will only sometimes choose not to break after short
+    /// return types.
```
Comment (owenca) [inline clang/include/clang/Format/Format.h:947]: For example:
```suggestion
    /// Same as ``Automatic`` above, except that there is no break after short
    /// return types.
```

**Review by owenca — COMMENTED** [review]
There is no need to update the release notes for new option values.

**Comment by rmarker** [comment]
> +1. In addition, we should deprecate `None` (in documentation only) and rename `AllowShortType` to `Automatic`, followed by `ExceptShortType` which means "`Automatic` except for short return types". Then IMO `ExceptShortType` is unambiguous. If you still think `NeverShortType` is clearer, I would change it to `NotShortType`.

Sounds like a plan.
Updated PR with changes.

File: clang/include/clang/Format/Format.h (hunk 16 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Done

File: clang/include/clang/Format/Format.h (hunk 17 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Done

File: clang/include/clang/Format/Format.h (hunk 18 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Done

File: clang/include/clang/Format/Format.h (hunk 19 above)
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Done

File: clang/unittests/Format/FormatTest.cpp [hunk 20]
```diff
@@ -9938,12 +9984,16 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
                "    return 1;\n"
                "  }\n"
                "  int g();\n"
+               "  long\n"
+               "  foooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaar();\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9988]: Delete it because it's not a definition?

File: clang/unittests/Format/FormatTest.cpp [hunk 21]
```diff
@@ -9938,12 +9984,16 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
...
                "};\n"
                "int\n"
                "f() {\n"
                "  return 1;\n"
                "}\n"
-               "int g();",
+               "int g();\n"
+               "int\n"
+               "foooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaaar();",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9996]: Ditto.

File: clang/unittests/Format/FormatTest.cpp [hunk 22]
```diff
@@ -9920,13 +9962,17 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
   verifyFormat("class C {\n"
                "  int f() { return 1; }\n"
                "  int g();\n"
+               "  long\n"
+               "  foooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaar();\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9966]: Delete because it's not top-level?

File: clang/unittests/Format/FormatTest.cpp [hunk 23]
```diff
@@ -9906,12 +9944,16 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
   verifyFormat("class B {\n"
                "  int f() { return 1; }\n"
                "  int g();\n"
+               "  long\n"
+               "  foooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaar();\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9948]: Delete it because it's not a definition?

File: clang/unittests/Format/FormatTest.cpp [hunk 24]
```diff
@@ -9906,12 +9944,16 @@ TEST_F(FormatTest, ReturnTypeBreakingStyle) {
...
                "};\n"
                "int\n"
                "f() {\n"
                "  return 1;\n"
                "}\n"
-               "int g();",
+               "int g();\n"
+               "int\n"
+               "foooooooooooooooooooooooooooo::baaaaaaaaaaaaaaaaaaaaar();",
```
Comment (owenca) [inline clang/unittests/Format/FormatTest.cpp:9956]: Ditto.

**Review by owenca — COMMENTED** [review]
Looks good otherwise.

File: clang/unittests/Format/FormatTest.cpp (hunk 23 above)
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp:9948]: Yeah, not sure if this example is completely relevant in the tests for these subsequent options.
Though to me, it seems that each of the options has a test with the same block of code. Since there are other lines which aren't definitions in the same test.
Wondering if it is worth keeping it so that the symmetry in this area is preserved?
Though, I don't have strong feelings either way if you think it isn't needed.

File: clang/include/clang/Format/Format.h [hunk 25]
```diff
@@ -914,16 +914,31 @@ struct FormatStyle {
...
     ///     int f() { return 0; };
     ///   };
     ///   int f();
     ///   int f() { return 1; }
+    ///   int
+    ///   LongName::AnotherLongName();
     /// \endcode
-    RTBS_None,
+    RTBS_Automatic,
+    /// Same as ``Automatic`` above, expect that there is no break after short
```
[the remark this answers is not in the document]
Comment (rmarker) [reply clang/include/clang/Format/Format.h]: Oof, spellcheck has failed me ;)

File: clang/unittests/Format/FormatTest.cpp (hunk 23 above)
Comment (owenca) [reply clang/unittests/Format/FormatTest.cpp:9948]: It's a declaration and supposed to have no break after the type. That's why I suggested that we delete it (and others).

File: clang/unittests/Format/FormatTest.cpp (hunk 20 above)
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Deleted.

File: clang/unittests/Format/FormatTest.cpp (hunk 21 above)
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Deleted.

File: clang/unittests/Format/FormatTest.cpp (hunk 22 above)
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Deleted.

File: clang/unittests/Format/FormatTest.cpp (hunk 23 above)
Comment (rmarker) [reply clang/unittests/Format/FormatTest.cpp]: Deleted.

**Review by owenca — APPROVED** [review]

**Comment by rmarker** [comment]
Thanks, @owenca.
Don't know if you want to wait for any others to look it over.
I had a look at the buildkite check failure. Not sure if it is related to the changes in the PR?
In any case, I'll need someone to merge for me when the time is right.

**Comment by owenca** [comment]
I don't think the buildkite failure is related to this PR, but I like to wait for a couple of days before merging in case others have any comments.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by rmarker** [comment]
Nice.
Thanks, @owenca, and @HazardyKnusperkeks.
