### PR TITLE
[DAG] SDPatternMatch - Fix m_Reassociatable mismatching

### LINKED ISSUE #169645: [DAG] SDPatternMatch - m_Reassociatable mismatches
Noticed while working on #169644

If we attempt to match a m_ReassociatableAdd pattern containing both the m_Value and m_Deferred for a given SDValue, the matcher gets corrupted and fails to match the correct SDValue pairs

foldAddToAvg:
```
  if ((!LegalOperations || hasOperation(ISD::AVGFLOORU, VT)) &&
      (sd_match(N,
                m_Add(m_And(m_Value(A), m_Value(B)),
                      m_Srl(m_Xor(m_Deferred(A), m_Deferred(B)), m_One()))) ||
       sd_match(N, m_ReassociatableAdd(
                       m_Srl(m_Value(A), m_One()), m_Srl(m_Value(B), m_One()),
                       m_ReassociatableAnd(m_Deferred(A), m_Deferred(B),
                                           m_One()))))) {
    return DAG.getNode(ISD::AVGFLOORU, DL, VT, A, B);
  }
```

in this case we end up with the same SDValue being matched for A and B.

Hopefully this is just an evaluation ordering issue, but there might be something else going on.

Good first issue for someone who likes template programming!

### PR DESCRIPTION
**Pull request by bermondd**
Fixes #169645

The issue was caused by a for-loop improperly overwriting SDValue binds when m_Reassociatable is given two or more patterns that (1) call m_Value with an SDValue parameter and (2) differ by that parameter. This fix comes with added unit tests relevant to SDValue bindings inside m_Reassociatable patterns.

Essentially, the original implementation first tried to match every combination of leaf node and pattern possible and stored that in a matrix-like structure, and then did a recursive search on that matrix to check if it's possible to pair every leaf with a pattern. The problem is that m_Value has a side effect where it changes an SDValue, and the creation of this matrix was corrupting these values. Below is an example of this, following the order of execution in the original implementation and using the case brought by issue #169645, where this behavior was found. The example tries to match ((a >> 1) + (b >> 1) + (a & b & 1)), using uppercase letters for the SDValue variables themselves and lowercase for their values. The result is that the pattern matches the same value for A and B, which was the behavior observed in the issue:

| Line | Leaf | Pattern | Match? | Effect |
|--------|--------|--------|--------|--------|
| 1 | a >> 1 | m_Srl(m_Value(A), m_One()) | Yes | A <- a |
| 2 | a >> 1 | m_Srl(m_Value(B), m_One()) | Yes | B <- a |
| 3 | a >> 1 | m_ReassociableAnd(m_Deferred(A), m_Deferred(B), m_One()) | No | -- |
| 4 | b >> 1 | m_Srl(m_Value(A), m_One()) | Yes | A <- b |
| 5 | b >> 1 | m_Srl(m_Value(B), m_One()) | Yes | B <- b |
| 6 | b >> 1 | m_ReassociableAnd(m_Deferred(A), m_Deferred(B), m_One()) | No | -- |
| 7 | a & b & 1 | m_Srl(m_Value(A), m_One()) | No | -- |
| 8 | a & b & 1 | m_Srl(m_Value(B), m_One()) | No | -- |
| 9 | a & b & 1 | m_ReassociableAnd(m_Deferred(A), m_Deferred(B), m_One()) | a == b | -- | 

To fix this, the function now matches the patterns during the recursive search itself, instead of preparing the matrix beforehand. Although this does fix the issue, it does mean that we're performing a best case of n and worst case of n! matching attempts, instead of the fixed nˆ2 in the original, where n is the number of patterns provided. Going back to the table above, using this fix the lines 2, 3, 4, 6, 7, and 8 do not happen, and so the only effects happening are A <- a and B <- b, which then will result in line 9 matching correctly.

Maybe the way this was fixed could be improved, tho. This is my first contribution to LLVM and I'm still fairly inexperienced with C++, so I'm not sure if template recursion is discouraged, but it was the way I found to abide by the compile time constraints of the template. This was also my first ever PR to any open source project, so I don't know if this is too length, sorry if so. Open to any feedback :)

### CODE REVIEW

File: llvm/include/llvm/CodeGen/SDPatternMatch.h [hunk 1]
```diff
@@ -1339,21 +1332,31 @@ template <typename... PatternTs> struct ReassociatableOpc_match {
...
+  template <typename MatchContext, typename PatternHd, typename... PatternTl>
   [[nodiscard]] inline bool
-  reassociatableMatchHelper(ArrayRef<SmallBitVector> Matches,
-                            SmallBitVector &Used, size_t Curr = 0) {
-    if (Curr == Matches.size())
-      return true;
-    for (size_t Match = 0, N = Matches[Curr].size(); Match < N; Match++) {
-      if (!Matches[Curr][Match] || Used[Match])
+  reassociatableMatchHelper(const MatchContext &Ctx,
+                            SmallVector<SDValue> &Leaves, SmallBitVector &Used,
```
Comment (mshockwave) [inline llvm/include/llvm/CodeGen/SDPatternMatch.h]: `Leaves` isn't modified in the function body right? then I think we can use `ArrayRef` here.

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp [hunk 2]
```diff
@@ -842,6 +842,16 @@ TEST_F(SelectionDAGPatternMatchTest, matchReassociatableOp) {
   EXPECT_TRUE(sd_match(
       MUL, m_ReassociatableMul(m_Value(), m_Value(), m_Value(), m_Value())));
 
+  // (Op0 + Op1) + Op0 binds correctly, allowing commutation
+  SDValue ADD010 = DAG->getNode(ISD::ADD, DL, Int32VT, ADD01, Op0);
+  SDValue A, B;
+  EXPECT_TRUE(sd_match(
+      ADD010, m_ReassociatableAdd(m_Value(A), m_Value(B), m_Deferred(A))));
+  EXPECT_TRUE(sd_match(
+      ADD010, m_ReassociatableAdd(m_Value(A), m_Value(B), m_Deferred(B))));
```
Comment (RKSimon) [inline llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: The problem I was often seeing wasn't that m_ReassociatableAdd etc. didn't return true - it was that the values of A + B weren't correct - please can you add additional checks that A and B are correctly initialized to the correct ADD01/Op0 pairs?

Comment (bermondd) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: Ah, alright. Just added tests for this in the newest commit.

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp [hunk 3]
```diff
@@ -842,6 +842,28 @@ TEST_F(SelectionDAGPatternMatchTest, matchReassociatableOp) {
   EXPECT_TRUE(sd_match(
       MUL, m_ReassociatableMul(m_Value(), m_Value(), m_Value(), m_Value())));
 
+  // (Op0 + Op1) + Op0 binds correctly, allowing commutation
+  SDValue ADD010 = DAG->getNode(ISD::ADD, DL, Int32VT, ADD01, Op0);
+  SDValue A, B;
+  EXPECT_TRUE(sd_match(
+      ADD010, m_ReassociatableAdd(m_Value(A), m_Value(B), m_Deferred(A))));
+  EXPECT_TRUE(sd_match(Op0, m_Deferred(A)));
```
Comment (mshockwave) [inline llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: `EXPECT_EQ(Op0, A)`? ditto for other similar lines

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp [hunk 4]
```diff
@@ -842,6 +842,28 @@ TEST_F(SelectionDAGPatternMatchTest, matchReassociatableOp) {
   EXPECT_TRUE(sd_match(
       MUL, m_ReassociatableMul(m_Value(), m_Value(), m_Value(), m_Value())));
 
+  // (Op0 + Op1) + Op0 binds correctly, allowing commutation
+  SDValue ADD010 = DAG->getNode(ISD::ADD, DL, Int32VT, ADD01, Op0);
+  SDValue A, B;
```
Comment (mshockwave) [inline llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: so far you have
  - m_Value(A), m_Value(B), m_Deferred(A)
  - m_Value(A), m_Value(B), m_Deferred(B)
  - m_Value(A), m_Deferred(A), m_Deferred(A)

Could you also add m_Value(A), m_Deferred(A), m_Value(B)?

Also, what happen when users write m_Value(A), m_Deferred(B), m_Value(B)? I guess this is also allowed due to commutation?

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp [hunk 5]
```diff
@@ -842,6 +842,28 @@ TEST_F(SelectionDAGPatternMatchTest, matchReassociatableOp) {
...
+  EXPECT_TRUE(sd_match(
+      ADD010, m_ReassociatableAdd(m_Value(A), m_Value(B), m_Deferred(A))));
+  EXPECT_EQ(Op0, A);
+  EXPECT_EQ(Op1, B);
+  EXPECT_NE(A, B);
```
[the remark this answers is not in the document]
Comment (bermondd) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: yeah, I was thinking of whether I should keep it or remove it. When both tests above that one pass then this one is indeed redundant, but if one of them fails, the outcome of this third check could provide some insight as to what happened. But it also does clutter the code a bit, so I'm very much not opposed to removing it.

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp (hunk 4 above)
Comment (bermondd) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: Sure! I'll implement a test for m_Value(A), m_Deferred(A), m_Value(B) in the next commit.

About m_Value(A), m_Deferred(B), m_Value(B): that actually fails (just tested locally), because as it currently is, the matching commutes the leaf nodes and not the patterns, so it will fail when trying to find a leaf match for m_Deferred(B) when B has yet to get it's value from m_Value(B), which will never be reached.

I can change this, but is it even desirable to support these kinds of patterns?

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (bermondd) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: I think I agree, to be honest. I'll remove these in the next commit.

File: llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp (hunk 4 above)
Comment (mshockwave) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: > because as it currently is, the matching commutes the leaf nodes and not the patterns,

Ah that makes sense to me. Then I think we should _not_ allow m_Value(A), m_Deferred(B), m_Value(B) to match. So on this end no change is needed.

Comment (bermondd) [reply llvm/unittests/CodeGen/SelectionDAGPatternMatchTest.cpp]: Alright, then I think I'll push a final commit with the additional m_Value(A), m_Deferred(A), m_Value(B) test and also remove the EXPECT_NE checks, and then I think it's done.

Edit: I'll also add the m_Value(A), m_Deferred(B), m_Value(B) test, expecting it to fail.

**Review by mshockwave — APPROVED** [review]
LGTM

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Review by RKSimon — COMMENTED** [review]
Looking at this again due to the compile time increase reported on #169644 - since NumPatterns is known at compile time, maybe we should be trying harder to avoid runtime data structures?
```
SmallVector<SDValue> Leaves; -> std::array<SDValue, NumPatterns>
SmallBitVector -> llvm::Bitset<NumPatterns>
```

**Comment by mshockwave** [comment]
> Looking at this again due to the compile time increase reported on #169644 - since NumPatterns is known at compile time, maybe we should be trying harder to avoid runtime data structures?
> 
> ```
> SmallVector<SDValue> Leaves; -> std::array<SDValue, NumPatterns>
> SmallBitVector -> llvm::Bitset<NumPatterns>
> ```

I think it's a good idea. I somehow had a wrong impression that the number of leaves might be larger than the number of patterns.

Another potential cause is that the worst time complexity now becomes `O(n!)`, and given the use cases in #169644 which nested two m_Reassociatable patterns, we might experience even higher time complexity -- about `O((n!)^2)`? -- in the worst case
