### PR TITLE
[Tooling][clang-tools-extra] Consume CommonOptionsParser errors in tools

### LINKED ISSUE #183009: [Clang] `clang-check` Aborted with Unchecked Error
**Environment:**
- Clang-Tidy Version: LLVM version 23.0.0git (Optimized build with assertions)
- Commit Hash: [`9a109fbb6e184ec9bcce10615949f598f4c974a9`](https://github.com/llvm/llvm-project/commit/9a109fbb6e184ec9bcce10615949f598f4c974a9)
- Platform: Linux 6.18.6

**Reproducer:**
```shell
$ touch foo.cpp
$ ./build/bin/clang-check -serialize-diagnostic-file=foo.dia foo.cpp --
clang-check: Unknown command line argument '-serialize-diagnostic-file=foo.dia'.  Try: './build/bin/clang-check --help'
clang-check: Did you mean '--print-options=foo.dia'?
Program aborted due to an unhandled Error:
clang-check: Unknown command line argument '-serialize-diagnostic-file=foo.dia'.  Try: './build/bin/clang-check --help'
clang-check: Did you mean '--print-options=foo.dia'?

 #0 0x00007f12a38b7208 __interceptor_backtrace (/usr/lib/libasan.so.8+0xb7208)
 #1 0x000055cba4cd3311 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./build/bin/clang-check+0x80f0311)
 #2 0x000055cba4cc3eea llvm::sys::RunSignalHandlers() (./build/bin/clang-check+0x80e0eea)
 #3 0x000055cba4cc47a3 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #4 0x00007f12a324d2d0 (/usr/lib/libc.so.6+0x3e2d0)
 #5 0x00007f12a32a7a2c (/usr/lib/libc.so.6+0x98a2c)
 #6 0x00007f12a324d1a0 raise (/usr/lib/libc.so.6+0x3e1a0)
 #7 0x00007f12a32345fe abort (/usr/lib/libc.so.6+0x255fe)
 #8 0x000055cba4a81962 llvm::Error::fatalUncheckedError() const (./build/bin/clang-check+0x7e9e962)
 #9 0x000055cba3134cd6 main (./build/bin/clang-check+0x6551cd6)
#10 0x00007f12a32366c1 (/usr/lib/libc.so.6+0x276c1)
#11 0x00007f12a32367f9 __libc_start_main (/usr/lib/libc.so.6+0x277f9)
#12 0x000055cba3126025 _start (./build/bin/clang-check+0x6543025)
Aborted                    ./build/bin/clang-check -serialize-diagnostic-file=foo.dia foo.cpp --
```

Seems like a regression:
```
$ /usr/bin/clang-check -serialize-diagnostic-file=foo.dia foo.cpp --
clang-check: Unknown command line argument '-serialize-diagnostic-file=foo.dia'.  Try: '/usr/bin/clang-check --help'
clang-check: Did you mean '--analyzer-output-path=foo.dia'?
$ /usr/bin/clang-check --version
LLVM (http://llvm.org/):
  LLVM version 21.1.8
  Optimized build.
```

### PR DESCRIPTION
**Pull request by zeyi2**
Several LibTooling-based tools printed errors returned from CommonOptionsParser::create() directly. However, printing an `llvm::Error` does not consume it, so argument parsing failures such as unknown tool options could abort. This commit fixes the problem.

Closes https://github.com/llvm/llvm-project/issues/183009

### CODE REVIEW

File: clang/include/clang/Tooling/CommonOptionsParser.h [hunk 1]
```diff
@@ -57,7 +57,7 @@ namespace tooling {
 ///   auto ExpectedParser =
 ///       CommonOptionsParser::create(argc, argv, MyToolCategory);
 ///   if (!ExpectedParser) {
-///     llvm::errs() << ExpectedParser.takeError();
+///     llvm::errs() << llvm::toString(ExpectedParser.takeError());
```
Comment (zeyi2) [inline clang/include/clang/Tooling/CommonOptionsParser.h:60]: By looking at existing code in the codebase:

https://github.com/llvm/llvm-project/blob/52e5d65561c5822549a3da051f176ae2de085cac/clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp#L633

I think this is actually the correct way to use this, so I'm changing the documentation here :)

**Review by AaronBallman — APPROVED** [review]
LGTM, good catch, it took me a bit to realize that `llvm::toString` actually consumes the error that's been taken.
