### PR TITLE
[DebugInfo] Handle additional types of stores in assignment tracking

### LINKED ISSUE #126417: [SLP][DebugInfo] "!DIAssignID attached to unexpected instruction kind" after store => @llvm.experimental.vp.strided.store conversion
I'm filing this issue rather than attempting a patch directly as I'd appreciate a second opinion on who is at fault here. Looking at [the docs on debug assignment tracking](https://llvm.org/docs/AssignmentTracking.html), SLPVectorizer's use of `mergeDIAssignID` when converting the stores to the strided store intrinsic seems (to my non-expert-in-debuginfo eye!) in line with the advice. Possibly the check in `Verifier::visitDIAssignIDMetadata` is simply overzealous (it checks `isa<AllocaInst>(I) || isa<StoreInst>(I) || isa<MemIntrinsic>(I)`). If so - would there be any concerns about adding `|| isa<IntrinsicInst>(I)` and assuming any intrinsic it is attached to acts like a store?

Thanks to @mikhailramalho for noting the crash when compiling SPEC with `-g`.

This is a reduced test case:

```
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @main_argv() #0 {
entry:
  %sar_height.i = getelementptr i8, ptr null, i64 24
  store ptr %sar_height.i, ptr null, align 8
  %vui.i = getelementptr i8, ptr null, i64 44
  %0 = load i32, ptr %vui.i, align 4
  %sar_width.i = getelementptr i8, ptr null, i64 20
  %1 = load i32, ptr %sar_width.i, align 4
  %i_sar_width.i = getelementptr i8, ptr null, i64 48
  store i32 %1, ptr %i_sar_width.i, align 8, !DIAssignID !4
  %2 = load i32, ptr %sar_height.i, align 4
  store i32 %2, ptr %vui.i, align 4
  ret void
}

attributes #0 = { "target-features"="+64bit,+a,+c,+d,+f,+m,+relax,+v,+zaamo,+zalrsc,+zicsr,+zifencei,+zmmul,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvl128b,+zvl32b,+zvl64b,-b,-e,-experimental-sdext,-experimental-sdtrig,-experimental-smctr,-experimental-ssctr,-experimental-svukte,-experimental-xqcia,-experimental-xqciac,-experimental-xqcicli,-experimental-xqcicm,-experimental-xqcics,-experimental-xqcicsr,-experimental-xqciint,-experimental-xqcilo,-experimental-xqcilsm,-experimental-xqcisls,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-h,-sha,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zabha,-zacas,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl4096b,-zvl512b,-zvl65536b,-zvl8192b" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang version 21.0.0git", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, globals: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x264.c", directory: "/home/asb/llvm-test-suite/build.clang-head-di-repro", checksumkind: CSK_MD5, checksum: "a24a70e9a69b8d18ca4f64525db2c55f")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DIAssignID()
```

Just do `~/llvm-project/build/default/bin/opt -passes=slp-vectorizer -S < reduced.ll` to get:

```
!DIAssignID attached to unexpected instruction kind
  call void @llvm.experimental.vp.strided.store.v2i32.p0.i64(<2 x i32> %1, ptr align 4 %i_sar_width.i, i64 -4, <2 x i1> splat (i1 true), i32 2), !DIAssignID !4
!4 = distinct !DIAssignID()
LLVM ERROR: Broken module found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
....
```

CC @OCHyams @SLTozer

### PR DESCRIPTION
**Pull request by SLTozer**
Fixes #126417.

Currently, assignment tracking recognizes allocas, stores, and mem intrinsics as valid instructions to tag with DIAssignID, with allocas representing the allocation for a variable and the others representing instructions that may assign to the variable. There are other intrinsics that can perform these assignments however, and if we transform a store instruction into one of these intrinsics and correctly transfer the DIAssignID over, this results in a verifier error. The AssignmentTrackingAnalysis pass also does not know how to handle these intrinsics if they are untagged, as it does not know how to extract assignment information (base address, offset, size) from them.

This patch adds _some_ support for some intrinsics that may perform assignments: masked store/scatter, and vp store/strided store/scatter. This patch does not add support for extracting assignment information from these, as they may store with either non-constant size or to non-contiguous blocks of memory; instead it adds support for recognizing untagged stores with "unknown" assignment info, for which we assume that the memory location of the associated variable should not be used, as we can't determine which fragments of it should or should not be used.

In principle, it should be possible to handle the more complex cases mentioned above, but it would require more substantial changes to AssignmentTrackingAnalysis, and it is mostly only needed as a fallback if the DIAssignID is not preserved on these alternative stores.

### CODE REVIEW

**Review by jmorse — COMMENTED** [review]
Do we need a test covering the poison/undef path, i.e. an untagged unknown store to something where there's not a live dbg.value?

Can we use Ìnstruction::mayWriteToMemory` as the test for whether a store is unknown, or is that signing us up to too much maintenance? It might make sense if we allow any intrinsic that writes to memory to adopt this behaviour.

**Comment by SLTozer** [comment]
> Do we need a test covering the poison/undef path, i.e. an untagged unknown store to something where there's not a live dbg.value?

It's unlikely to be a source of errors, but it should be covered.

> Can we use Ìnstruction::mayWriteToMemory` as the test for whether a store is unknown, or is that signing us up to too much maintenance? It might make sense if we allow any intrinsic that writes to memory to adopt this behaviour.

We might use it in the verifier to determine whether a given instruction should be allowed to have a DIAssignID attached; in AssignmentTrackingAnalysis for the "unknown store" case, I'll have to look into it - the important part is that we can identify the base address that is being written to, which looks like it might be possible.

File: llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp [hunk 1]
```diff
@@ -2123,6 +2183,25 @@ getUntaggedStoreAssignmentInfo(const Instruction &I, const DataLayout &Layout) {
...
+      ID != Intrinsic::masked_scatter && ID != Intrinsic::vp_store)
+    return nullptr;
+  Value *MemOp = II->getArgOperand(1);
+  // We don't actually use the constant offset for now, but we may in future,
+  // and the non-accumulating versions do not support a vector of pointers.
+  APInt Offset(Layout.getIndexTypeSizeInBits(MemOp->getType()), 0);
+  Value *Base = MemOp->stripAndAccumulateConstantOffsets(Layout, Offset, true);
+  // For Base pointers that are not an alloca instruction we don't need to do
+  // anything, and simply return nullptr.
+  return dyn_cast<AllocaInst>(Base);
```
Comment (OCHyams) [inline llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp:2202]: Could a `vp_scatter` store to multiple different allocas? My question is basically whether it's a given that we can return a _single_ "base" pointer for any given scatter?

**Review by OCHyams — COMMENTED** [review]
Tyvm for handling this.

Code changes SGTM, with one inline question.

More broadly, it's unfortunate to remove coverage for the entire variable. Part of me wonders whether it's better to go the other way, and state it's a def for the whole variable. This is obviously liable to introduce incorrect locations, but if we compare it to dbg.declare semantics (which this stuff sort-of replaces) I don't think it'd be a regression there. I'm not sure how convinced I am by my own argument; I'm not a massive fan of either option, but we do need to do something. cc @jmorse in case he wants to chime in.

File: llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp (hunk 1 above)
Comment (SLTozer) [reply llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp:2202]: It isn't a given, but all the examples I've seen *do* store to different offsets at a single alloca though, so I decided not to over-complicate this logic. In practice this is, as far as I can tell, quite a narrowly used intrinsic and the default behaviour of simply ignoring the intrinsic won't cause any errors, so it's probably not worth trying to cover all our bases here until we see this be a problem.

File: llvm/lib/IR/Verifier.cpp [hunk 2]
```diff
@@ -4956,8 +4956,19 @@ void Verifier::visitProfMetadata(Instruction &I, MDNode *MD) {
...
+  // DIAssignID metadata must be attached to either an alloca or some form of
+  // store/memory-writing instruction.
+  // FIXME: Is there any simpler way to express this property than manually
+  // enumerating all instructions that could perform an assignment?
+  bool ExpectedInstTy = isa<AllocaInst>(I) || isa<StoreInst>(I);
+  if (auto *II = dyn_cast<IntrinsicInst>(&I)) {
+    const static Intrinsic::ID StoreIntrinsics[] = {
+        Intrinsic::vp_store, Intrinsic::vp_scatter,
+        Intrinsic::experimental_vp_strided_store, Intrinsic::masked_store,
+        Intrinsic::masked_scatter};
```
Comment (asb) [inline llvm/lib/IR/Verifier.cpp:4968]: Perhaps llvm.masked.compress_store be included here as well?

**Comment by asb** [comment]
I can confirm that with this patch applied. I can compile SPEC in the llvm-test-suite with `-g` and the vector extension. As commented inline, I think llvm.masked.compressstore is probably missed.

There's also the case of target-specific instrinsics, e.g. llvm.riscv.vse. These should only be produced by the C intrinsics and I guess don't currently have the metadata attached,  but I'm not sure there's a fundamental reason a frontend wouldn't attach DIAssignID metadata.

I don't feel well placed to review the whole PR, but with the query about llvm.masked.compressstore answered the verifier changes LGTM.

**Comment by SLTozer** [comment]
> There's also the case of target-specific instrinsics, e.g. llvm.riscv.vse. These should only be produced by the C intrinsics and I guess don't currently have the metadata attached, but I'm not sure there's a fundamental reason a frontend wouldn't attach DIAssignID metadata.

I think it's probably a good idea to follow the original suggestion and just relax the verifier check - the rest of the changes in this patch are still useful, and if a store intrinsic wants to be handled more correctly when it's _untagged_ then it should be handled in `getUnknownStore`, but I don't think I'm in a position to add that for all possible store intrinsics.

**Comment by SLTozer** [comment]
Ping for the last set of code changes, in which I relaxed the verifier to accept DIAssignIDs on all intrinsics and added support for `masked_compressstore` (as described above).

**Comment by OCHyams** [comment]
I don't want to block this, since it fixes an assertion. But I don't think my question was addressed / answered:

> More broadly, it's unfortunate to remove coverage for the entire variable. Part of me wonders whether it's better to go the other way, and state it's a def for the whole variable. This is obviously liable to introduce incorrect locations, but if we compare it to dbg.declare semantics (which this stuff sort-of replaces) I don't think it'd be a regression there. I'm not sure how convinced I am by my own argument; I'm not a massive fan of either option, but we do need to do something. cc @jmorse in case he wants to chime in.

I'm leaning slightly more that way now, but it's better to do what you've got here already than assert.

**Review by OCHyams — APPROVED** [review]
(so... tentative LGTM)

**Review by OCHyams — APPROVED** [review]
