### PR TITLE
[fatlto] Add coroutine passes when using FatLTO with ThinLTO

### LINKED ISSUE #134409: fatal error: error in backend: Do not know how to promote this operator!
Hi, I hit the following crash when building WebKitGTK 2.49.1 using Clang 20.1.1.

It might be related to #104525 because:

 * The stack trace is similar (although not the same)
 * The crash depends on LTO, it does not crash if I disable LTO
 * This is likely the first version of WebKitGTK to depend on coroutines

```
fatal error: error in backend: Do not know how to promote this operator!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -Wextra -Wall -Werror=undefined-internal -Werror=undefined-inline -pipe -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare -fasynchronous-unwind-tables -fdebug-types-section -O2 -flto=thin -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security --config=/usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fno-strict-aliasing -fno-exceptions -fno-rtti -fcoroutines -ffunction-sections -fdata-sections -std=c++23 -fPIC -fvisibility=hidden -Wunsafe-buffer-usage -fsafe-buffer-usage-suggestions -Wno-unused-parameter -mfpmath=sse -msse -msse2 -pthread -fdiagnostics-color=always -fcolor-diagnostics -DBUILDING_GTK__=1 -DBUILDING_WEBKIT=1 -DBUILDING_WITH_CMAKE=1 -DBUILDING_WebKit -DBWRAP_EXECUTABLE=\"/usr/bin/bwrap\" -DDATADIR=\"/usr/share\" -DDBUS_PROXY_EXECUTABLE=\"/usr/bin/xdg-dbus-proxy\" -DGETTEXT_PACKAGE=\"WebKitGTK-6.0\" -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBDIR=\"/usr/lib64\" -DLOCALEDIR=\"/usr/share/locale\" -DPAS_BMALLOC=1 -DPKGLIBDIR=\"/usr/lib64/webkitgtk-6.0\" -DPKGLIBEXECDIR=\"/usr/libexec/webkitgtk-6.0\" -DSK_ASSUME_GL=0 -DSK_ASSUME_GL_ES=1 -DSK_ASSUME_WEBGL=0 -DSK_DISABLE_LEGACY_GL_MAKE_NATIVE_INTERFACE -DSK_DISABLE_LEGACY_IMAGE_READBUFFER -DSK_DISABLE_LEGACY_INIT_DECODERS -DSK_DISABLE_LEGACY_PNG_WRITEBUFFER -DSK_DISABLE_TRACING -DSK_DISABLE_WEBGL_INTERFACE -DSK_ENABLE_PRECOMPILE -DSK_R32_SHIFT=16 -DSK_RELEASE -DSK_TRIVIAL_ABI=[[clang::trivial_abi]] -DSTATICALLY_LINKED_WITH_PAL -DSTATICALLY_LINKED_WITH_WebCore -DUSE_SYSTEM_EGL -DWebKit_EXPORTS -D_GLIBCXX_ASSERTIONS=1 -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebKitGTK/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebKitGTK/Headers/webkitgtk-6.0 -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebKitGTK/Headers/webkitgtk-web-process-extension -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebKitGTK/DerivedSources/webkit -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebKitGTK/DerivedSources -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0 -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/PAL/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WebCore/PrivateHeaders -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/DerivedSources/ForwardingHeaders -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/DerivedSources/WebKit -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/DerivedSources/WebKit/include -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess/ShapeDetection -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess/graphics -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess/graphics/WebGPU -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess/media -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/GPUProcess/webrtc -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/ModelProcess -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/Authentication -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/Classifier -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/Cookies -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/CustomProtocols -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/Downloads -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/FileAPI -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/IndexedDB -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/Notifications -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/PrivateClickMeasurement -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/ServiceWorker -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/SharedWorker -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/cache -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/storage -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/watchos -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/webrtc -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/webtransport -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform/IPC -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/API -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/API/c -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/ApplePay -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Authentication -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/CoreIPCSupport -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Databases -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Databases/IndexedDB -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Extensions -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/FileAPI -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/graphics -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Gamepad -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/Notifications -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/RemoteLayerTree -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/WebGPU -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/WebsiteData -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/XR -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/C -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/cpp -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Authentication -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Automation -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/DigitalCredentials -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Downloads -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Extensions -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Gamepad -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/GPU -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Inspector -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Inspector/Agents -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Launcher -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Media -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Model -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Network -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Network/CustomProtocols -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Notifications -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Plugins -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/RemoteLayerTree -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/UserContent -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/WebAuthentication -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/WebAuthentication/Mock -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/WebsiteData -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/XR -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/ApplePay -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/ApplicationCache -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Automation -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Cache -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Databases -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Databases/IndexedDB -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/EncryptedMedia -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Extensions -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Extensions/API -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Extensions/Bindings -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/FileAPI -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/FullScreen -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Gamepad -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Geolocation -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU/ShapeDetection -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU/graphics -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU/graphics/WebGPU -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU/media -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/GPU/webrtc -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/IconDatabase -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle/API -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle/API/c -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle/DOM -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Inspector -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Launching -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/MediaCache -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/MediaStream -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Model -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Network -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Network/webrtc -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Notifications -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/OriginData -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Plugins -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Plugins/Netscape -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/ResourceCache -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Speech -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Storage -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/UserContent -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebCoreSupport -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebPage -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebPage/RemoteLayerTree -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebStorage -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/XR -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/WebKitLibraries -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/skia -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/JavaScriptCoreGLib/DerivedSources/jsc -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/NetworkProcess/soup -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform/IPC/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform/IPC/unix -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform/classifier -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Platform/generic -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/API/c/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/API/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/linux -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/Shared/soup -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/C/cairo -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/C/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/C/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/API/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/CoordinatedGraphics -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Inspector/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Inspector/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/Notifications/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/geoclue -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/gstreamer -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/linux -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/UIProcess/soup -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle/API/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/InjectedBundle/API/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/Inspector/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/glib -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/soup -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebCoreSupport/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebCoreSupport/soup -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebPage/CoordinatedGraphics -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebPage/gtk -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebProcess/WebPage/dmabuf -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/ThirdParty/skia -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/Skia/Headers/top -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/Skia/Headers/mod -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/JavaScriptCore/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/JavaScriptCore/PrivateHeaders -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/JavaScriptCoreGLib/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/JavaScriptCoreGLib/DerivedSources -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/WTF/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/bmalloc/Headers -I/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/ANGLE/Headers -isystem /usr/include/enchant-2 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/sysprof-6 -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/orc-0.4 -isystem /usr/include/gtk-4.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/webp -isystem /usr/include/cairo -isystem /usr/include/libxml2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/pixman-1 -isystem /usr/include/graphene-1.0 -isystem /usr/lib64/graphene-1.0/include -isystem /usr/include/libsoup-3.0 -isystem /usr/include/gtk-4.0/unix-print -isystem /usr/include/avif -isystem /usr/include/libmanette -isystem /usr/include/libdrm -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -DNDEBUG -include /home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/Source/WebKit/WebKit2Prefix.h -DWITH_GZFILEOP -DHWY_SHARED_DEFINE -DAVIF_DLL -DEB_DLL -DHAVE_HB_FEATURES_H -c -MD -MT Source/WebKit/CMakeFiles/WebKit.dir/__/__/DerivedSources/WebKit/WebFullScreenManagerProxyMessageReceiver.cpp.o -MF Source/WebKit/CMakeFiles/WebKit.dir/__/__/DerivedSources/WebKit/WebFullScreenManagerProxyMessageReceiver.cpp.o.d -fcolor-diagnostics -o Source/WebKit/CMakeFiles/WebKit.dir/__/__/DerivedSources/WebKit/WebFullScreenManagerProxyMessageReceiver.cpp.o /home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/DerivedSources/WebKit/WebFullScreenManagerProxyMessageReceiver.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/home/mcatanzaro/Projects/fedora-scm/webkitgtk/webkitgtk-2.49.1-build/webkitgtk-2.49.1/redhat-linux-build/webkitgtk-6.0/DerivedSources/WebKit/WebFullScreenManagerProxyMessageReceiver.cpp'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@_ZZN3IPC27callMemberFunctionCoroutineIN6WebKit25WebFullScreenManagerProxyES2_FN3WTF9AwaitableIbEERNS_10ConnectionENS3_23ObjectIdentifierGenericIN7WebCore19FrameIdentifierTypeENS3_38ObjectIdentifierMainThreadAccessTraitsImEEmEEbNS1_22FullScreenMediaDetailsEESt5tupleIJSD_bSE_EEFvbEEEvPT_MT0_T1_S7_OT2_ONS3_17CompletionHandlerIT3_EEENKUlSJ_E_clINSQ_ISI_EEEENS3_4TaskESJ_'
 #0 0x00007ff76a827eba llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.20.1+0x227eba)
 #1 0x00007ff76a824e44 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.20.1+0x224e44)
 #2 0x00007ff76a73e9a2 (/lib64/libLLVM.so.20.1+0x13e9a2)
 #3 0x00007ff76a6032cf llvm::CrashRecoveryContext::HandleExit(int) (/lib64/libLLVM.so.20.1+0x32cf)
 #4 0x00007ff76a82095f (/lib64/libLLVM.so.20.1+0x22095f)
 #5 0x0000557a224f3029 (/usr/bin/clang+++0xb029)
 #6 0x00007ff76a753650 llvm::report_fatal_error(llvm::Twine const&, bool) (/lib64/libLLVM.so.20.1+0x153650)
 #7 0x00007ff76a7534eb llvm::report_fatal_error(char const*, bool) (/lib64/libLLVM.so.20.1+0x1534eb)
 #8 0x00007ff76b1565ae (/lib64/libLLVM.so.20.1+0xb565ae)
 #9 0x00007ff76b18eea2 llvm::SelectionDAG::LegalizeTypes() (/lib64/libLLVM.so.20.1+0xb8eea2)
#10 0x00007ff76b2caec2 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/lib64/libLLVM.so.20.1+0xccaec2)
#11 0x00007ff76b2ca4fd llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/lib64/libLLVM.so.20.1+0xcca4fd)
#12 0x00007ff76b2c7492 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/lib64/libLLVM.so.20.1+0xcc7492)
#13 0x00007ff76b2c5358 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/lib64/libLLVM.so.20.1+0xcc5358)
#14 0x00007ff76ad18a1c llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/lib64/libLLVM.so.20.1+0x718a1c)
#15 0x00007ff76a9d657c llvm::FPPassManager::runOnFunction(llvm::Function&) (/lib64/libLLVM.so.20.1+0x3d657c)
#16 0x00007ff76a9de6f3 llvm::FPPassManager::runOnModule(llvm::Module&) (/lib64/libLLVM.so.20.1+0x3de6f3)
#17 0x00007ff76a9d6e4f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/lib64/libLLVM.so.20.1+0x3d6e4f)
#18 0x00007ff774590eaf clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/lib64/libclang-cpp.so.20.1+0x1790eaf)
#19 0x00007ff774a35728 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.20.1+0x1c35728)
#20 0x00007ff773012d59 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.20.1+0x212d59)
#21 0x00007ff77571719f clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.20.1+0x291719f)
#22 0x00007ff77567ab54 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.20.1+0x287ab54)
#23 0x00007ff7757aac7e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.20.1+0x29aac7e)
#24 0x0000557a224f2687 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+++0xa687)
#25 0x0000557a224ee727 (/usr/bin/clang+++0x6727)
#26 0x00007ff77521b9bd (/lib64/libclang-cpp.so.20.1+0x241b9bd)
#27 0x00007ff76a73e950 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.20.1+0x13e950)
#28 0x00007ff77521b275 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.20.1+0x241b275)
#29 0x00007ff7751d7529 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7529)
#30 0x00007ff7751d77e7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d77e7)
#31 0x00007ff7751fa349 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.20.1+0x23fa349)
#32 0x0000557a224edb54 clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang+++0x5b54)
#33 0x0000557a224fd978 main (/usr/bin/clang+++0x15978)
#34 0x00007ff76a0105f5 __libc_start_call_main (/lib64/libc.so.6+0x35f5)
#35 0x00007ff76a0106a8 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a8)
#36 0x0000557a224ebe05 _start (/usr/bin/clang+++0x3e05)
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 20.1.1 (Fedora 20.1.1-1.fc42)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/lib64/llvm20/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang++.cfg
Configuration file: /usr/lib/rpm/redhat/redhat-hardened-clang.cfg
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/WebFullScreenManagerProxyMessageReceiver-241f64.cpp
clang++: note: diagnostic msg: /tmp/WebFullScreenManagerProxyMessageReceiver-241f64.sh
clang++: note: diagnostic msg: 
```

[WebFullScreenManagerProxyMessageReceiver-241f64.zip](https://github.com/user-attachments/files/19607441/WebFullScreenManagerProxyMessageReceiver-241f64.zip)

### PR DESCRIPTION
**Pull request by ilovepi**
When coroutines are used w/ both -ffat-lto-objects and -flto=thin,
the coroutine passes are not added to the optimization pipelines.
Ensure they are added before ModuleOptimization to generate a
working ELF object.

Fixes #134409.

### CODE REVIEW

**Comment by ilovepi** [comment]
* **#134434** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/134434?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/134434?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nikic — COMMENTED** [review]
Switching to the ThinLTO post-link pipeline will have a big impact on optimization behavior and compile-time. I think it would be safer to make a change along the lines of https://github.com/llvm/llvm-project/pull/126168, i.e. to schedule the necessary passes in the FatLTO pipeline. Without having looked into it closely, it would probably be okay to just schedule them before the buildModuleOptimizationPipeline call.

**Comment by ilovepi** [comment]
hmm, I tried adding some of the individual passes, and ran into some other errors. Let me give that another try w/ that PR as an example.

File: llvm/lib/Passes/PassBuilderPipelines.cpp [hunk 1]
```diff
@@ -1692,6 +1692,19 @@ PassBuilder::buildFatLTODefaultPipeline(OptimizationLevel Level, bool ThinLTO,
...
+    // ThinLTOPreLink, so we need the coroutine passes to run for ThinLTO
+    // builds, otherwise they will miscompile.
+    if (ThinLTO) {
+      // TODO: replace w/ buildCoroWrapper() when it takes phase and level into
+      // consideration.
+      CGSCCPassManager CGPM;
+      CGPM.addPass(CoroSplitPass(Level != OptimizationLevel::O0));
+      CGPM.addPass(CoroAnnotationElidePass());
+      MPM.addPass(createModuleToPostOrderCGSCCPassAdaptor(std::move(CGPM)));
+      MPM.addPass(CoroCleanupPass());
```
Comment (ilovepi) [inline llvm/lib/Passes/PassBuilderPipelines.cpp:1705]: Also possible to do `MPM.addPass(buildModuleSimplificationPipeline(Level, ThinOrFullLTOPhase::ThinLTOPostLink));`

That seems to generate better code here, since it allows the tail call in the test to get removed. But that seems a bit expensive, just to give the inliner a second chance.

**Review by nikic — APPROVED** [review]
LGTM, but PR title needs adjustment.

File: llvm/lib/Passes/PassBuilderPipelines.cpp (hunk 1 above)
Comment (nikic) [reply llvm/lib/Passes/PassBuilderPipelines.cpp:1705]: I think the current PR is a good way to start, as it avoids the miscompilation in a minimal way that is suitable for backporting.

Using the module simplification pipeline here (+ the module optimization pipeline) would effectively be the same as using the ThinLTO post-link pipeline.

I ran some tests, and it looks like adding `-ffat-lto-objects` adds about 10% overhead to the clang build (https://llvm-compile-time-tracker.com/compare.php?from=44923d8631fb28b4de54d4210762f256c3894cef&to=2bdf721c2d37af6fcbd931d963f586478cb55f17&stat=instructions:u). On top of that, switching this from using the module optimization pipeline to the ThinLTO post-link pipeline (your original PR) adds an extra 4%: https://llvm-compile-time-tracker.com/compare.php?from=2bdf721c2d37af6fcbd931d963f586478cb55f17&to=63666418fbe19f30bf971796747a751b4e1c57f3&stat=instructions:u

Adding 4% overhead is not great, but also not terrible, so maybe it's worth it to avoid pipeline compatibility issues in a principled way. It does make the codegen for FatLTO ELF diverge more from a normal compilation though.

Ideally we'd be able to rerun the simplification pipeline, but skip the inliner pipeline for already optimized functions. (I think @aeubanks had a prototype that did that for the actual ThinLTO scenario, by looking at available_externally functions. The situation here is somewhat different.)

Comment (ilovepi) [reply llvm/lib/Passes/PassBuilderPipelines.cpp:1705]: Hmm, 10% seems a bit high for overhead on build times, though we haven't used it too much w/ ThinLTO in our toolchain, so maybe that's it?

Looking at our build times when we enabled it in our toolchain, we saw about a 2.5% slowdown in total build time, but a 22% improvement in test time (ninja check-*).  Overall that ended up being about 4.4% speedup in total time.

So, I'm not surprised it slowed down for just the build, but I am surprised it added a full 10%.  Well, I guess I/O can have a lot of variance between machines, so maybe that's enough to explain it, since for ThinLTO it probably more than doubles the size of the `.o`.

File: llvm/lib/Passes/PassBuilderPipelines.cpp [hunk 2]
```diff
@@ -1692,6 +1692,19 @@ PassBuilder::buildFatLTODefaultPipeline(OptimizationLevel Level, bool ThinLTO,
   if (ThinLTO && PGOOpt && PGOOpt->Action == PGOOptions::SampleUse)
     MPM.addPass(buildThinLTODefaultPipeline(Level, /*ImportSummary=*/nullptr));
   else {
+    // ModuleSimplification does not run the coroutine passes for
+    // ThinLTOPreLink, so we need the coroutine passes to run for ThinLTO
+    // builds, otherwise they will miscompile.
+    if (ThinLTO) {
+      // TODO: replace w/ buildCoroWrapper() when it takes phase and level into
+      // consideration.
+      CGSCCPassManager CGPM;
```
Comment (vitalybuka) [inline llvm/lib/Passes/PassBuilderPipelines.cpp:1701]: maybe better to use buildCoroWrapper?

Comment (vitalybuka) [reply llvm/lib/Passes/PassBuilderPipelines.cpp:1701]: just noticed TODO :)
