### PR TITLE
Inline: Fix handling of byval using non-alloca addrspace

### LINKED ISSUE #97086: [AMDGPU] [NVPTX] Infer Address Spaces pass leaving behind GEP with no operands
This crash was found using an IR fuzzer. It looks like Infer Address Spaces only runs under the AMDGPU and NVPTX backends. The only way I've been able to reproduce this was with a byval struct argument in a function that gets inlined. The inlined function is reading the second field of the struct in this case.

```
%struct = type { i64, i64 }

define i64 @bar(ptr byval(%struct) %a) alwaysinline {
  %1 = getelementptr %struct, ptr %a, i64 0, i32 1
  %2 = load i64, ptr %1, align 4
  ret i64 0
}

define i64 @foo(%struct* %arg) {
  %1 = call i64 @bar(%struct* byval(%struct) align 8 %arg)
  ret i64 0
}
```

Compiler Explorer: https://godbolt.org/z/9zW6nnffT

Here's the IR dump before and after the pass:
```
*** IR Dump After Infer address spaces (infer-address-spaces) ***
; Function Attrs: alwaysinline
define i64 @bar(ptr byval(%struct) %a) #0 {
  %1 = getelementptr %struct, ptr %a, i64 0, i32 1
  %2 = load i64, ptr %1, align 4
  ret i64 0
}
*** IR Dump After Infer address spaces (infer-address-spaces) ***
define i64 @foo(ptr %arg) #1 {
  %arg1 = alloca %struct, align 8, addrspace(5)
  call void @llvm.lifetime.start.p5(i64 16, ptr addrspace(5) %arg1)
  call void @llvm.memcpy.p5.p0.i64(ptr addrspace(5) align 1 %arg1, ptr align 1 %arg, i64 16, i1 false)
  %1 = getelementptr
  %2 = load i64, ptr addrspace(5) %1, align 4
  call void @llvm.lifetime.end.p5(i64 16, ptr addrspace(5) %arg1)
  ret i64 0
}
```

Notice how %1 turned into an empty GEP. This will cause an ICE when later passes assume GEP operands.

### PR DESCRIPTION
**Pull request by arsenm**
Use the address space of the original pointer argument instead
of querying the datalayout. This avoids producing a verifier error
since this was changing the address space for the user instructions.

Fixes #97086

### CODE REVIEW

**Comment by arsenm** [comment]
* **#97306** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/97306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: llvm/lib/Transforms/Utils/InlineFunction.cpp [hunk 1]
```diff
@@ -1674,8 +1674,9 @@ static Value *HandleByValArgument(Type *ByValType, Value *Arg,
   if (ByValAlignment)
     Alignment = std::max(Alignment, *ByValAlignment);
 
-  AllocaInst *NewAlloca = new AllocaInst(ByValType, DL.getAllocaAddrSpace(),
-                                         nullptr, Alignment, Arg->getName());
+  AllocaInst *NewAlloca = new AllocaInst(
+      ByValType, cast<PointerType>(Arg->getType())->getAddressSpace(), nullptr,
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/InlineFunction.cpp:1678]:
```suggestion
      ByValType, Arg->getType()->getPointerAddressSpace(), nullptr,
```

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Utils/InlineFunction.cpp [hunk 2]
```diff
@@ -1674,8 +1674,9 @@ static Value *HandleByValArgument(Type *ByValType, Value *Arg,
   if (ByValAlignment)
     Alignment = std::max(Alignment, *ByValAlignment);
 
-  AllocaInst *NewAlloca = new AllocaInst(ByValType, DL.getAllocaAddrSpace(),
```
Comment (MrSidims) [inline llvm/lib/Transforms/Utils/InlineFunction.cpp:1677]: Digging a bit into git log the patch that added DL.getAllocaAddrSpace() was the following:
```
commit 3c1fc768ed6cf2b01463df036ae6ae3b1f0de632
Author: Matt Arsenault <Matthew.Arsenault@amd.com>
Date:   Mon Apr 10 22:27:50 2017 +0000

    Allow DataLayout to specify addrspace for allocas.
```
and reasoning behind that patch:
"    These are problems for AMDGPU because alloca is used to
    implement the private address space, which uses a 32-bit
    index as the pointer value. Other pointers are 64-bit
    and behave more like LLVM's notion of generic address
    space. By changing the address space used for allocas,
    we can change our generic pointer type to be LLVM's generic
    pointer type which does have similar properties."
 
 makes sense to me especially in OpenCL context, where default address space is 4 (generic) and LLVM passes must respect target's datalayout when picking possible types for the created instructions.
 
Current fix brings some complications though, if byval pointer of a function was is default aka genetic address space, then the alloca would be in generic. Meanwhile per SPIR-V (to which LLVM IR is being lowered for OpenCL 2.0 and earlier) specification OpVariable must have non-generic storage class. It can probably be workarounded in https://github.com/KhronosGroup/SPIRV-LLVM-Translator by translating alloca addrspace(4) to OpVariable with Private storage class bringing extra address space casts or by modifying clang, introducing an exception for byval pointers making them not be in default address space, but in private, but I wonder if https://github.com/llvm/llvm-project/issues/97086 can be solved differently - instead here if Arg->getType()->getPointerAddressSpace() != DL.getAllocaAddrSpace() - we still create an alloca in default datalayout address space and add an AS cast, WDYT?

Comment (davidchisnall) [reply llvm/lib/Transforms/Utils/InlineFunction.cpp:1677]: > instead here if Arg->getType()->getPointerAddressSpace() != DL.getAllocaAddrSpace() - we still create an alloca in default datalayout address space and add an AS cast, WDYT?

I'm not sure I fully understand the proposal, but for the CHERI use case (the AMD version was based on the CHERI fork, which we aim to start upstreaming soon), allocas must be created in the alloca address space, not some other address space and cast.

Comment (MrSidims) [reply llvm/lib/Transforms/Utils/InlineFunction.cpp:1677]: I mean: leave alloca in DL.getAllocaAddrSpace() AS and if it doesn't match with byval pointer's address space - create a cast and update users of the alloca to use the cast. But digging more into it might be not as trivial as I though initially - at least it seems it shouldn't be done in HandleByValArgument, but probably later in the stack.

Comment (davidchisnall) [reply llvm/lib/Transforms/Utils/InlineFunction.cpp:1677]: That would not break anything for CHERI, if it works for other use cases.

Comment (arsenm) [reply llvm/lib/Transforms/Utils/InlineFunction.cpp:1677]: No, this is the correct fix. We should follow what the existing IR says. The rule is not all allocas must have the alloca address space, it's the alloca address space is the default for contextless new values. 

As far as OpenCL is concerned such IR would have been malformed in the first place. If we wanted to handle this as a generic pointer with a private backed alloca, it should be handled by lowering the alloca with the wrong address space to include the cast (which is essentially what NVPTX does, it's just more work for the backend and less optimizable IR)
