### PR TITLE
[libc][minor] Fix assertion in LlvmLibcFILETest.SimpleFileOperations

### LINKED ISSUE #126106: Test LlvmLibcFILETest.SimpleFileOperations fails due to file descriptor assertion
Repro steps:

I ran this test on Linux.

I have 0d7ee520d3a9b8997adf8eaaa22b33db9659d94e checked out (though the bug is present in earlier commits.)

```
$ cmake ../runtimes -GNinja \
  -DLLVM_ENABLE_RUNTIMES="libc;compiler-rt" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_C_COMPILER=clang \
  -DLLVM_LIBC_FULL_BUILD=ON \
  -DLLVM_LIBC_INCLUDE_SCUDO=ON \
  -DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
  -DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
  -DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF

$ ninja check-libc
```

Result:
```
[530/2361] Running unit test libc.test.src.stdio.fileop_test.__unit__
FAILED: libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fileop_test.__unit__ /usr/local/google/home/ayzhao/src/llvm-project/build-libc/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fileop_test.__unit__
cd /usr/local/google/home/ayzhao/src/llvm-project/build-libc/libc/test/src/stdio && /usr/local/google/home/ayzhao/src/llvm-project/build-libc/libc/test/src/stdio/libc.test.src.stdio.fileop_test.__unit__.__build__
[==========] Running 3 tests from 1 test suite.
[ RUN      ] LlvmLibcFILETest.SimpleFileOperations
/usr/local/google/home/ayzhao/src/llvm-project/libc/test/src/stdio/fileop_test.cpp:34: FAILURE
      Expected: __llvm_libc_20_0_0_git::fileno(file)
      Which is: 5
To be equal to: 3
      Which is: 3
[  FAILED  ] LlvmLibcFILETest.SimpleFileOperations
```

Looking at the [code](https://github.com/llvm/llvm-project/blob/16f7e961c600986de7814822fd118f431e0bb433/libc/test/src/stdio/fileop_test.cpp#L32-L34) the test opens a file and assert that its file descriptor is equal to the hardcoded value 3. This seems to be a brittle assertion as it makes assumptions about the test's process environment.

### PR DESCRIPTION
**Pull request by alanzhao1**
The file descriptor of the first opened file is not necessarily 3, so we change the assertion so that it's >= 0 (i.e. not an error.)

Fixes #126106

### CODE REVIEW

File: libc/test/src/stdio/fileop_test.cpp [hunk 1]
```diff
@@ -31,7 +31,7 @@ TEST(LlvmLibcFILETest, SimpleFileOperations) {
   constexpr char FILENAME[] = "testdata/simple_operations.test";
   ::FILE *file = LIBC_NAMESPACE::fopen(FILENAME, "w");
   ASSERT_FALSE(file == nullptr);
-  ASSERT_EQ(LIBC_NAMESPACE::fileno(file), 3);
+  ASSERT_GE(LIBC_NAMESPACE::fileno(file), 3);
```
Comment (nickdesaulniers) [inline libc/test/src/stdio/fileop_test.cpp:34]: Maybe this should just be `>= 0`. IIRC file descriptors get reused if you close stdin, stdout, stderr then open a new file.

Comment (alanzhao1) [reply libc/test/src/stdio/fileop_test.cpp]: Done

**Review by nickdesaulniers — APPROVED** [review]
Thanks for the patch.  We can probably further improve this using `fstat` and `lstat`, but I will leave that cleanup for another day.  This should at least unblock you from running the rest of the test suite. Thanks for the report, and the fix.
