### PR TITLE
[mlir][arith] Fix arith maxnumf/minnumf folder

### LINKED ISSUE #114594: [mlir][arith] Arith folder for maxnumf/minnumf has wrong NaN behaviour
IEEE754-2019's maximumnumf and minimumnumf have NaN as their identity element. The folder was copied from the regular maximumf and minimumf and considers that infinities are the identities.

For instance
```
%1 = arith.maxnumf %nan, %something : f32
```
should fold to `%something` but
```
%1 = arith.maxnumf %-inf, %something : f32
```
should not be folded, as if `%something` is NaN, then `%-inf` should be returned.

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #114594 
#### Context

[IEEE754-2019](https://ieeexplore.ieee.org/document/8766229) Sec 9.6 defines 2 minimum and 2 maximum operations. They are termed
- `maximum` and `maximumNumber`
- `minimum` and `minimumNumber`

In the arith dialect they are respectively named `maximumf` and `maxnumf`, `minimumf` and `minnumf` so I use these names.

These operations only differ in how they handle NaN values. For `maximumf` and `minimumf`, if any operand is NaN, then the result is NaN, ie, NaN is propagated. For `maxnumf` and `minnumf`, if any operand is NaN, then the other operand is returned, ie, NaN is absorbed. The following identities hold:
```
maximumf(x, NaN) = maximumf(NaN, x) = NaN
maxnumf(x, NaN) = maxnumf(NaN, x) = x
```
(and same for min).

#### Arith folders

In the following I am talking about the folders for the arith operations. The folders implement the following canonicalizations (`op` is one of maximumf, maxnumf, minimumf, minnumf):
1. `op(x, x)` folds to `x` 
2. for `op(x, y)`, if `y` folds to the neutral element of the `op`, then the `op` is folded to `x`.
    1. The neutral element of `maximumf` is -Infty
    2. The neutral element of `minimumf` is +Infty
    3. The neutral element of `maxnumf` and `minnumf` is NaN as shown above.
3. for `op(x, y)`, if both `x` and `y` fold to constants `x'` and `y'`, then the `op` is folded and the result is calculated with a corresponding runtime function.

The folders are properly implemented for `maximumf` and `minimumf`, but the same implementations were copied for the respective `maxnumf` and `minnumf` functions. This means the neutral element of the second folder above is wrong:
- `maxnumf(x, -Infty)` is folded to `x`, but that's wrong, because if `x` is NaN then -Infty should be the result
- `minnumf(x, +Infty)` is folded to `x`, but same thing, the result should be +Infty when `x` is NaN.

This is fixed by using `NaN` as neutral element for the `maxnumf` and `minnumf` ops.[^1]

Again because of copy paste mistake, the third pattern above is using `llvm::maximum` instead of `llvm::maximumnum` to calculate the result in case both arguments fold to a constant:
- `maxnumf(NaN, x')` would have been folded to `llvm::maximum(NaN, x')` which is `NaN`, whereas the result should be `x'`.

This folder for `minnumf` already correctly uses `llvm::minnum`, but I fixed the one for `maxnumf` in this PR.

[^1]: this is by the way already correctly implemented in [`arith::getIdentityValueAttr`](https://github.com/oowekyala/llvm-project/blob/a821964e0320d1e35514ced149ec10ec06d7131a/mlir/lib/Dialect/Arith/IR/ArithOps.cpp#L2493-L2498)

### CODE REVIEW

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 1]
```diff
@@ -1014,13 +1014,14 @@ OpFoldResult arith::MaxNumFOp::fold(FoldAdaptor adaptor) {
...
 
-  // maxnumf(x, -inf) -> x
-  if (matchPattern(adaptor.getRhs(), m_NegInfFloat()))
+  // maxnumf(x, NaN) -> x
+  if (matchPattern(adaptor.getRhs(), m_NaNFloat()))
     return getLhs();
 
-  return constFoldBinaryOp<FloatAttr>(
-      adaptor.getOperands(),
-      [](const APFloat &a, const APFloat &b) { return llvm::maximum(a, b); });
```
Comment (oowekyala) [inline mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1023]: This matters if the rhs folds to a number, and the LHS folds to NaN. Because this used `maximum` and not `maximumnum`, it would have folded the operation to `NaN` and not to the LHS.

**Review by kuhar — CHANGES_REQUESTED** [review]
Please add an explanation that clarifies what was broken, how it was fixed, and reference the relevant spec. These min/max intrinsic can be very trickly and there are many of them...

**Comment by oowekyala** [comment]
@kuhar I updated the PR description

Just finishing this and I noticed another edge case for more tedium...

There are in fact 2 different implementations for IEEE754-2019's `maximumNumber` and `minimumNumber` in LLVM's `APFloat.h`: `maximumnum` and `maxnum` (and same for minimum). They are not documented as such, but they differ in that one returns a quiet NaN if both operands are NaN (even if one is signalling), and the other returns one operand (which could be signalling).

I'm not sure which of those to use. The IEEE spec says the following:

> - maximumNumber(x, y) is x if x > y, y if y > x, and the number if one operand is a number and the other is a NaN. For this operation, +0 compares greater than −0. If x = y and signs are the same it is either x or y. **If both operands are NaNs, a quiet NaN is returned, according to 6.2. If either operand is a signaling NaN, an invalid operation exception is signaled**, but unless both operands are NaNs, the signaling NaN is otherwise ignored and not converted to a quiet NaN as stated in 6.2 for other operations.

The spec of the arith ops does not specify anything regarding the handling of signalling NaNs (and in fact does not say either that it follows IEEE754-2019 spec). Should the part about "signalling an invalid operation exception" be implemented in arith? And if so, how? Should we fold to a poison value? Or just prevent folding in this case and let lower-level dialects handle this?

If we don't care about signalling NaNs then I think we should use the APFloat functions that produce quiet NaNs consistently.

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 2]
```diff
@@ -1014,13 +1014,14 @@ OpFoldResult arith::MaxNumFOp::fold(FoldAdaptor adaptor) {
   if (getLhs() == getRhs())
     return getRhs();
 
-  // maxnumf(x, -inf) -> x
-  if (matchPattern(adaptor.getRhs(), m_NegInfFloat()))
+  // maxnumf(x, NaN) -> x
+  if (matchPattern(adaptor.getRhs(), m_NaNFloat()))
     return getLhs();
```
Comment (kuhar) [inline mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1019]: Shouldn't this be maintained but updated to check that x is not NaN?

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 3]
```diff
@@ -1014,13 +1014,14 @@ OpFoldResult arith::MaxNumFOp::fold(FoldAdaptor adaptor) {
...
 
-  return constFoldBinaryOp<FloatAttr>(
-      adaptor.getOperands(),
-      [](const APFloat &a, const APFloat &b) { return llvm::maximum(a, b); });
+  return constFoldBinaryOp<FloatAttr>(adaptor.getOperands(),
+                                      [](const APFloat &a, const APFloat &b) {
+                                        return llvm::maximumnum(a, b);
+                                      });
```
Comment (kuhar) [inline mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1024]: nit: could we pass in just `llvm::maximumnum` here instead of the lambda? I don't know if it's overloaded or not.

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp [hunk 4]
```diff
@@ -1014,13 +1014,14 @@ OpFoldResult arith::MaxNumFOp::fold(FoldAdaptor adaptor) {
...
+  // maxnumf(x, NaN) -> x
+  if (matchPattern(adaptor.getRhs(), m_NaNFloat()))
     return getLhs();
 
-  return constFoldBinaryOp<FloatAttr>(
-      adaptor.getOperands(),
-      [](const APFloat &a, const APFloat &b) { return llvm::maximum(a, b); });
+  return constFoldBinaryOp<FloatAttr>(adaptor.getOperands(),
+                                      [](const APFloat &a, const APFloat &b) {
+                                        return llvm::maximumnum(a, b);
```
Comment (kuhar) [inline mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1023]: This looks incorrect to me since maximumnum != maxnum

**Review by kuhar — CHANGES_REQUESTED** [review]
IIRC, we don't care about signaling NaNs but should otherwise distinguish between the 3 versions of max/min.

**Comment by joker-eph** [comment]
> IIRC, we don't care about signaling NaNs but should otherwise distinguish between the 3 versions of max/min.

Wouldn't users like Flang care about signaling NaNs?

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp (hunk 3 above)
Comment (oowekyala) [reply mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1024]: Yes I think that would work. Should I update other similar lambdas in the fold implementations?

**Comment by kuhar** [comment]
I meant this in the context of constants in the IR -- IIRC there's no way to represent a signaling NaN?

**Comment by kuhar** [comment]
A relevant thread: https://discourse.llvm.org/t/semantics-of-nan/66729

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp (hunk 3 above)
Comment (kuhar) [reply mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1024]: In general, I'd only update the code that relevant to this PR, and submit any other cleanups as a separate PR

File: mlir/lib/Dialect/Arith/IR/ArithOps.cpp (hunk 2 above)
Comment (oowekyala) [reply mlir/lib/Dialect/Arith/IR/ArithOps.cpp:1019]: To check that `x` is not NaN you need to have folded `x` to some constant. This is handled by the last pattern below, which computes the result of the operation if both operands are folded.

**Review by kuhar — APPROVED** [review]
LGTM but it would be nice to have someone more familiar with float semantics confirm the signaling NaN behavior

**Comment by krzysz00** [comment]
I think we can land this
