### PR TITLE
[C23] Accept an _Atomic underlying type

### LINKED ISSUE #147736: [C23] Clang should silently strip the `_Atomic` qualifier in enums with fixed underlying type
```c
/* ISO C23 6.7.3.3-5

   The underlying type of the enumeration is the unqualified,
   non-atomic version of the type specified by the type specifiers in
   the specifier qualifier list. */

enum e : _Atomic int { E };
enum e e;

enum f : const int { F };
enum f f;
```

```
<source>:7:18: error: non-integral type '_Atomic(int)' is an invalid underlying type
    7 | enum e : _Atomic int { E };
      |                  ^
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/Ka35GTTEr

GCC 15 accepts this. Clang 21 (trunk at the time of writing) rejects it.

cc @AaronBallman

### PR DESCRIPTION
**Pull request by AaronBallman**
The underlying type of an enumeration is the non-atomic, unqualified version of the specified type. Clang was rejecting such enumerations, but now accepts them.

Because we expose _Atomic in C++, the same behavior is carried over.

Fixes #147736

### CODE REVIEW

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -17152,6 +17152,13 @@ bool Sema::CheckEnumUnderlyingType(TypeSourceInfo *TI) {
   SourceLocation UnderlyingLoc = TI->getTypeLoc().getBeginLoc();
   QualType T = TI->getType();
 
+  // C++0x 7.2p2: The type-specifier-seq of an enum-base shall name an
+  // integral type; any cv-qualification is ignored.
+  // C23 6.7.3.3p5: The underlying type of the enumeration is the unqualified,
+  // non-atomic version of the type specified by the type specifiers in the
+  // specifier qualifier list.
+  T = T.getAtomicUnqualifiedType();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDecl.cpp]: Since we're now stripping qualifications, we should probably make sure that all of the callers of this 'treat' that like underlying.

File: clang/lib/Sema/SemaDecl.cpp [hunk 2]
```diff
@@ -17563,6 +17573,16 @@ Sema::ActOnTag(Scope *S, unsigned TagSpec, TagUseKind TUK, SourceLocation KWLoc,
...
 
+      // If the underlying type is atomic, we need to adjust the type before
+      // continuing. This only happens in the case we stored a TypeSourceInfo
+      // into EnumUnderlying because the other cases are error recovery up to
+      // this point. But because it's not possible to gin up a TypeSourceInfo
+      // for a non-atomic type from an atomic one, we'll store into the Type
+      // field instead.
+      if (TypeSourceInfo *TI = dyn_cast<TypeSourceInfo *>(EnumUnderlying);
+          TI && TI->getType()->isAtomicType())
+        EnumUnderlying = TI->getType().getAtomicUnqualifiedType().getTypePtr();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaDecl.cpp:17603]: Should we be stripping ALL cv qualifiers here?  Not just when it is atomic?

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp [hunk 3]
```diff
@@ -2022,8 +2022,14 @@ Decl *TemplateDeclInstantiator::VisitEnumDecl(EnumDecl *D) {
                                                 DeclarationName());
       if (!NewTI || SemaRef.CheckEnumUnderlyingType(NewTI))
         Enum->setIntegerType(SemaRef.Context.IntTy);
-      else
-        Enum->setIntegerTypeSourceInfo(NewTI);
+      else {
+        // If the underlying type is atomic, we need to adjust the type before
+        // continuing. See C23 6.7.3.3p5 and Sema::ActOnTag().
+        if (NewTI->getType()->isAtomicType())
```
Comment (erichkeane) [inline clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:2031]: Again wondering why we don't just 'silently' strip off all qualifiers?

File: clang/lib/Sema/SemaDecl.cpp [hunk 4]
```diff
@@ -17152,6 +17152,13 @@ bool Sema::CheckEnumUnderlyingType(TypeSourceInfo *TI) {
   SourceLocation UnderlyingLoc = TI->getTypeLoc().getBeginLoc();
   QualType T = TI->getType();
 
+  // C++0x 7.2p2: The type-specifier-seq of an enum-base shall name an
+  // integral type; any cv-qualification is ignored.
+  // C23 6.7.3.3p5: The underlying type of the enumeration is the unqualified,
+  // non-atomic version of the type specified by the type specifiers in the
+  // specifier qualifier list.
+  T = T.getAtomicUnqualifiedType();
+
```
Comment (cor3ntin) [inline clang/lib/Sema/SemaDecl.cpp]: Is there a reason this is done before checking for isDependentType?
If not, it would be better to do that after the following lines

**Review by erichkeane — COMMENTED** [review]
I THINK this is right, but we also need to have a codegen test to make sure we don't try to do goofiness with these.

**Comment by AaronBallman** [comment]
> I THINK this is right, but we also need to have a codegen test to make sure we don't try to do goofiness with these.

I was thinking the ast-dump test sufficed because it shows that we set the underlying type to non-atomic in the AST. But I can certainly add a codegen test, do you have anything in particular in mind?

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaDecl.cpp:17603]: `getAtomicUnqualifiedType()` strips all qualifiers *and* `_Atomic` (which is not a qualifier despite being listed as a qualifier in the standard. Yes, this is terrible.)

File: clang/lib/Sema/SemaDecl.cpp (hunk 4 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaDecl.cpp]: Good call!

**Comment by erichkeane** [comment]
> > I THINK this is right, but we also need to have a codegen test to make sure we don't try to do goofiness with these.
> 
> I was thinking the ast-dump test sufficed because it shows that we set the underlying type to non-atomic in the AST. But I can certainly add a codegen test, do you have anything in particular in mind?

Ah, yeah, that works.  I missed that was validating CV-A refs didn't make it into the AST.  Concern abaited :) 

But the test I was looking for was basically just a load/store to a variable of that type to make sure we treated it like an 'int' type not an _Atomic int type.  So that a store would look like:

```
  store i32 5, ptr %i, align 4
```
instead of :

```
  store atomic i32 6, ptr %AI seq_cst, align 4
```

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Right, i just mean "why the branch, why not do the stripping unconditionally"?

Comment (AaronBallman) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Oh, to be clear, the other qualifiers *are* stripped because the underlying QualType loses them due to us using a type pointer. The issue with `_Atomic` is that it creates an `AtomicType` which is a different kind of type pointer.

Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Right, so I guess I am wondering why the 'if' here, and not just 

`EnumUnderlying = TI->getType().getAtomicUnqualifiedType().getTypePtr();`.

without the `if` statement here.  Though I guess we have to make sure that `TI` is valid at least, so:

```
if (EnumUnderlying)
  EnumUnderlying = EnumUnderlying->getType().getAtomciUnqualifiedType().getTypePtr();
```

Side note: A little bit of a 'shadowing' problem happening here too.

**Comment by AaronBallman** [comment]
I went ahead and added a codegen test, better to test than hope. :-)

**Comment by AaronBallman** [comment]
I thought about this more overnight and I think I want to make a change here -- a user who sees `enum E : _Atomic(int)` may be reasonably thinking that values of type `enum E` are going to be atomically accessed, same as when they see `typedef _Atomic(int) atomic_int`. But they're not going to get the atomic behavior due to the silent stripping. Given that an atomic type is not the same as its underlying type (in terms of ABI or semantics) I think we should diagnose the behavior with at least a warning. I could even be convinced it should be a warning which defaults to an error because this is just weird.

Consider:
```
enum E : _Atomic(int) { Whatever };
static_assert(sizeof(enum E) == sizeof(_Atomic(int))); // Surprise! This can fail
```
because an atomic type is not required to have the same size as its non-atomic counterpart, per 7.17.6.p3.

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Ah! Because we want to keep the `TypeSourceInfo *` whenever possible (it carries more information than a `Type *`). But ginning up a `TypeSourceInfo *` for a part of a different type is nontrivial; we may want to do it someday, but it seemed like overkill to solve this issue. So in the atomic case we degrade the information a little bit by storing a `Type *` instead of a `TypeSourceInfo *`, but in usual cases we still store the `TypeSourceInfo *` we got.

**Comment by erichkeane** [comment]
> avior due to the silent stripping. Given that an atomic type is not the same as its underlying type (in terms of ABI or semantics) I think we should diagnose the behavior with at least a warning. I could even be convinced it should be a warning which defaults to an error because this is just weird.

Yeah, I 100% agree with that.  Warn-as-error is reasonable here IMO (as are ANY qualifiers?, but more so for atomic)

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Ah, gross... but yeah, I guess so.  Can I have a 'fixme' on it?  Something like, "we COOOOULD just unconditionally strip this but it loses the TypeSourceInfo... someday figure out how to do that"

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 3 above)
Comment (erichkeane) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:2031]: FIXME here would be nice too.

**Review by erichkeane — APPROVED** [review]
Would like a pair of fixmes, but this is otherwise good to me.

File: clang/lib/Sema/SemaDecl.cpp (hunk 2 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaDecl.cpp:17603]: Done!

File: clang/lib/Sema/SemaTemplateInstantiateDecl.cpp (hunk 3 above)
Comment (AaronBallman) [reply clang/lib/Sema/SemaTemplateInstantiateDecl.cpp:2031]: Done!

**Comment by AaronBallman** [comment]
> > avior due to the silent stripping. Given that an atomic type is not the same as its underlying type (in terms of ABI or semantics) I think we should diagnose the behavior with at least a warning. I could even be convinced it should be a warning which defaults to an error because this is just weird.
> 
> Yeah, I 100% agree with that. Warn-as-error is reasonable here IMO (as are ANY qualifiers?, but more so for atomic)

Would you like me to diagnose any qualifier? And turn it into warning-as-error?

**Comment by erichkeane** [comment]
> > > avior due to the silent stripping. Given that an atomic type is not the same as its underlying type (in terms of ABI or semantics) I think we should diagnose the behavior with at least a warning. I could even be convinced it should be a warning which defaults to an error because this is just weird.
> > 
> > 
> > Yeah, I 100% agree with that. Warn-as-error is reasonable here IMO (as are ANY qualifiers?, but more so for atomic)
> 
> Would you like me to diagnose any qualifier? And turn it into warning-as-error?

I thought about this more... I think a warning for 'qualifier ignored' for 'normal' qualifier is sensible, but not as error.

I can make a pretty strong case (as you did above) for the _Atomic who-what-zit to be a default warning-as- error.

As far as what I want... feel free to land as-is, or if you feel motivated, do the rest.

**Comment by AaronBallman** [comment]
> > > > avior due to the silent stripping. Given that an atomic type is not the same as its underlying type (in terms of ABI or semantics) I think we should diagnose the behavior with at least a warning. I could even be convinced it should be a warning which defaults to an error because this is just weird.
> > > 
> > > 
> > > Yeah, I 100% agree with that. Warn-as-error is reasonable here IMO (as are ANY qualifiers?, but more so for atomic)
> > 
> > 
> > Would you like me to diagnose any qualifier? And turn it into warning-as-error?
> 
> I thought about this more... I think a warning for 'qualifier ignored' for 'normal' qualifier is sensible, but not as error.
> 
> I can make a pretty strong case (as you did above) for the _Atomic who-what-zit to be a default warning-as- error.
> 
> As far as what I want... feel free to land as-is, or if you feel motivated, do the rest.

I decided it's worth it to warn about cv-qualifiers (we don't have to worry about `restrict` as that applies to pointers) and to default to an error for `_Atomic`.

File: clang/include/clang/Basic/DiagnosticSemaKinds.td [hunk 5]
```diff
@@ -9364,6 +9364,14 @@ def warn_atomic_implicit_seq_cst : Warning<
   InGroup<DiagGroup<"atomic-implicit-seq-cst">>, DefaultIgnore;
 def err_atomic_unsupported : Error<
   "atomic types are not supported in '%0'">;
+def warn_cv_stripped_in_enum : Warning<
+  "%select{'const' and 'volatile' qualifiers|'const' qualifier|'volatile' "
```
Comment (erichkeane) [inline clang/include/clang/Basic/DiagnosticSemaKinds.td]: Seems like a perfect time for an `enum_select` :)

**Review by erichkeane — APPROVED** [review]

File: clang/include/clang/Basic/DiagnosticSemaKinds.td (hunk 5 above)
Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticSemaKinds.td]: Good call!

Comment (AaronBallman) [reply clang/include/clang/Basic/DiagnosticSemaKinds.td]: Done!

**Comment by AaronBallman** [comment]
Another concrete reason for why this should default to an error for `_Atomic` is https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0943r6.html

In the C++ version of `stdatomic.h`, there's a `#define _Atomic(x) std::atomic<x>` which exists for shared header files between C and C++. `enum E : std::atomic<int> { Whatever };` is invalid in C++, it would be rather surprising for `enum E : _Atomic(int) { Whatever };` to then be valid in C and invalid in C++. So we error by default, but still allow users to opt out of the error if they find they need to support an `_Atomic` underlying type.

**Comment by Halalaluyafail3** [comment]
> So we error by default, but still allow users to opt out of the error if they find they need to support an `_Atomic` underlying type.

Does clang normally reject some valid programs by default with a non-gnu standard selected, intentionally (i.e. not a bug)? If so, is there an option to turn all of these errors off? It seems like `-w` has no effect, it has to be specifically named `-Wno-underlying-atomic-qualifier-ignored`.

**Comment by AaronBallman** [comment]
> > So we error by default, but still allow users to opt out of the error if they find they need to support an `_Atomic` underlying type.
> 
> Does clang normally reject some valid programs by default with a non-gnu standard selected, intentionally (i.e. not a bug)? 

Yes, though with a warning which defaults to an error so if someone wants their code accepted, they can do so for conformance reasons. As an example: https://godbolt.org/z/MTveG5xs4 We use it more for questionable extensions than we do for standards features though.

> If so, is there an option to turn all of these errors off? It seems like `-w` has no effect, it has to be specifically named `-Wno-underlying-atomic-qualifier-ignored`.

No, the point to defaulting a warning diagnostic as an error is because we want the user to consider carefully what they're trying to do, so you have to consider each category of diagnostic independently.
