### PR TITLE
[Clang] Back out the source location workaround for CXXConstructExpr

### LINKED ISSUE #143711: Wrong source range for CXXTemporaryObjectExpr
See https://godbolt.org/z/6cdcj1qqY

```c++
struct S {
    S(int, int);
};

void f() {
    S(S(0, 1));
}
```

When the `CXXTemporaryObjectExpr` is wrapped with a `CXXFunctionalCastExpr`, the source range of the `CXXTemporaryObjectExpr` contains the closing parenthesis of the `CXXFunctionalCastExpr`.

This occurs starting in `-std=c++17`, where guaranteed copy elision is in effect. In C++14, there is an intervening `CXXConstructExpr` and the `CXXTemporaryObjectExpr` has the correct source range (although Compiler Explorer's highlighting of AST nodes includes the closing parenthesis, as if `))` was a single token).

### PR DESCRIPTION
**Pull request by zyn0217**
This removes the workaround introduced in 3e1a9cf3b8 and 1ba7dc38d.

The workaround overwrote the right parenthesis location of the sub expression, which could be wrong when a CXXTemporaryObjectExpr occurs within a nested expression, e.g. `A(A(1, 2))`.

To completely take it down, we now propagate the left parenthesis source location throughout SemaCast, such that the ParenOrBraceRange can be properly set at the point of its creation.

Fixes https://github.com/llvm/llvm-project/issues/143711

### CODE REVIEW

File: clang/lib/Sema/SemaCast.cpp [hunk 1]
```diff
@@ -98,7 +98,36 @@ namespace {
     CXXCastPath BasePath;
     bool IsARCUnbridgedCast;
 
-    SourceRange OpRange;
+    struct OpRangeType {
+      SourceLocation Ranges[3];
```
Comment (erichkeane) [inline clang/lib/Sema/SemaCast.cpp]: This is a strange variable name here... `Ranges` for a series of locations?

**Review by erichkeane — APPROVED** [review]
I think this looks reasonable, 1 nit on the name of the member variable, else this LGTM.

File: clang/lib/Sema/SemaCast.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaCast.cpp]: Renamed to Locations :)
