### PR TITLE
[OpenMP][Flang] Fix atomic operations on complex types

### LINKED ISSUE #165184: [Flang][OpenMP] Incorrect execution result when using double precision complex in a statement within ATOMIC WRITE construct
```
Version of flang : 22.0.0(ea3dbb8b0061a7e44cba92b6e4e4486c4a416d65)/AArch64
```

In the attached program (`sngtatm029_21.f90`), when using `double precision complex` in a statement within `ATOMIC WRITE construct`, the execution result is incorrect.
The same issue also occurs with `quadruple precision complex`.

In the following cases, the execution result is correct.
- Do not specify the compilation option (`-fopenmp`), or
- Remove `ATOMIC WRITE construct`, or
- Change `double precision` or `quadruple precision` to `single precision`, or
- Change `complex` to `real` or `integer`

The following are the test program, Flang, Gfortran and ifx compilation/execution results.

sngtatm029_21.f90:
```fortran
program main
  complex(8)::c81
  complex(8)::c82
  c81=0
  c82=0
  write(6,*) "1 : c81 = ", c81
!$omp parallel
!$omp atomic write
  c81=c82+(1.0_8,1.0_8)
!$omp end parallel
  write(6,*) "2 : c81 = ", c81
end program main
```

```
$ export OMP_NUM_THREADS=2; flang -fopenmp sngtatm029_21.f90; ./a.out
 1 : c81 =  (0.,0.)
 2 : c81 =  (1.,0.)
$
```

```
$ flang sngtatm029_21.f90; ./a.out
 1 : c81 =  (0.,0.)
 2 : c81 =  (1.,1.)
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp sngtatm029_21.f90; ./a.out
 1 : c81 =                (0.0000000000000000,0.0000000000000000)
 2 : c81 =                (1.0000000000000000,1.0000000000000000)
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp sngtatm029_21.f90; ./a.out
 1 : c81 =  (0.000000000000000E+000,0.000000000000000E+000)
 2 : c81 =  (1.00000000000000,1.00000000000000)
$
```

### PR DESCRIPTION
**Pull request by KrxGu**
Fixes #165184

## Problem
When using OpenMP atomic read/write on Fortran `complex(8)` (16 bytes) or `complex(16)` (32 bytes), only the real part was being stored/loaded. The imaginary part remained unchanged (typically 0).

## Root Cause
In `OMPIRBuilder::createAtomicRead()` and `createAtomicWrite()`, the size parameter for `__atomic_load`/`__atomic_store` was incorrectly computed from the pointer type instead of the pointee (element) type.

On 64-bit systems, this resulted in only 8 bytes being transferred regardless of the actual struct size.

## Solution
Changed both functions to use `XElemTy` (element type) instead of the pointer type when computing `LoadSize`. This ensures the full struct is transferred:
- `complex(4)`: 8 bytes ✓
- `complex(8)`: 16 bytes ✓ (was 8 before)
- `complex(16)`: 32 bytes ✓ (was 8 before)

## Tests
Added three regression tests:
- `atomic-write-complex.f90` - Verifies IR for atomic write
- `atomic-read-complex.f90` - Verifies IR for atomic read  
image

- `issue-165184-atomic-complex8.f90` - Direct reproducer from the issue

### CODE REVIEW

**Review by kparzysz — APPROVED** [review]
LGTM

File: flang/test/Lower/OpenMP/atomic-read-complex.f90 [hunk 1]
```diff
@@ -0,0 +1,34 @@
+! Test lowering of atomic read to LLVM IR for complex types.
+! This is a regression test for issue #165184.
+
+! RUN: %flang_fc1 -emit-llvm -fopenmp -o - %s | FileCheck %s
```
Comment (kiranchandramohan) [inline flang/test/Lower/OpenMP/atomic-read-complex.f90]: We should try to avoid LLVM tests in the Lower directory.

**Comment by KrxGu** [comment]
@kparzysz Commit message updated and squashed per review. CI all green!!

@kiranchandramohan Re: colocating tests with the fix in OpenMPIRBuilder, plan is:
- Add a gtest in `llvm/unittests/Frontend/OpenMPIRBuilderTest.cpp` that builds atomic write/read on `{double,double}` and asserts the first arg to `__atomic_{load,store}` is 16.
- Add an MLIR translation check in `mlir/test/Target/LLVMIR/openmp-llvm.mlir` for `omp.atomic` lowering to `__atomic_*` with `i64 16`.

I can keep the Flang IR tests as frontend coverage, or drop them if you prefer only the two tests above. Please advise.

@kparzysz Does this test plan align with your expectations? and are we on the same page?

**Review by tblah — COMMENTED** [review]
Thank you for the bug fix!

**Comment by KrxGu** [comment]
@kiranchandramohan ,  @kparzysz  - I've addressed the feedback and made the requested changes. The PR now has:

**Unit test** for atomic operations on struct types (test `OMPAtomicRWStructType` in `OpenMPIRBuilderTest.cpp`)
   - Verifies that `__atomic_store` and `__atomic_load` are called with the correct size (16 bytes) for `{double, double}` struct type
   - Confirms the fix works for struct types similar to complex(8)
   
The commit history has been squashed into a single clean commit with a descriptive message. Please review when you get a chance. CI is all green, Good to Merge!!

**Review by tblah — APPROVED** [review]
LGTM, thanks!
