### PR TITLE
[Clang] Implement CWG2918 'Consideration of constraints for address of overloaded function'

### LINKED ISSUE #122523: Unique function identifier considered ambiguous as part of an overload set
clang 19.1

```cpp
#include <concepts>

template <typename T>
void f(T) {}

template <typename T>
requires std::same_as<T, int>
void f(T) {}

int main() {
	auto a = f<int>; // error: variable 'a' with type 'auto' has incompatible initializer of type '<overloaded function type>'
}
```

I don't know whether this should compile, but gcc does accept it. At least the diagnostic could use some work.

https://godbolt.org/z/bojPze9Kf

### PR DESCRIPTION
**Pull request by zyn0217**
Closes https://github.com/llvm/llvm-project/issues/122523

### CODE REVIEW

File: clang/test/CXX/drs/cwg29xx.cpp [hunk 1]
```diff
@@ -60,6 +60,90 @@ struct S {
 #endif
 } // namespace cwg2917
 
+namespace cwg2918 { // cwg2918: 21
+
+#if __cplusplus >= 202002L
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg29xx.cpp:65]: It seems that only example 2 needs C++20. Have you considered testing examples 1 and 3 in C++11 through C++17 modes?

File: clang/lib/Sema/SemaOverload.cpp [hunk 2]
```diff
@@ -13252,6 +13273,33 @@ class AddressOfFunctionResolver {
...
+      if (!F) {
+        Results.push_back(Matches[I]);
+        continue;
+      }
+      if (F == Matches[I].second) {
+        Results.clear();
+        Results.push_back(Matches[I]);
+      }
+    }
+    std::swap(Matches, Results);
```
Comment (mizvekov) [inline clang/lib/Sema/SemaOverload.cpp:13300]: Does this work if there are pairs of functions in the set which are not more constrained than the other both ways?
Do we have existing tests which cover that?

File: clang/lib/Sema/SemaConcept.cpp [hunk 3]
```diff
@@ -1773,20 +1773,19 @@ bool Sema::IsAtLeastAsConstrained(NamedDecl *D1,
                                   NamedDecl *D2,
                                   MutableArrayRef<const Expr *> AC2,
                                   bool &Result) {
+#ifndef NDEBUG
   if (const auto *FD1 = dyn_cast<FunctionDecl>(D1)) {
     auto IsExpectedEntity = [](const FunctionDecl *FD) {
       FunctionDecl::TemplatedKind Kind = FD->getTemplatedKind();
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaConcept.cpp:1779]: We have assumed FD2 to be non-null on line 1786, and besides that this change just gets rid of the if-body that is only intended for that assumption.

File: clang/lib/Sema/SemaOverload.cpp [hunk 4]
```diff
@@ -13443,9 +13499,9 @@ Sema::resolveAddressOfSingleOverloadCandidate(Expr *E, DeclAccessPair &Pair) {
     return nullptr;
 
   if (Result) {
-    SmallVector<const Expr *, 1> ResultAC;
     // We skipped over some ambiguous declarations which might be ambiguous with
     // the selected result.
+    // FIXME: This for-loop is dead code. Remove it?
```
[the remark this answers is not in the document]
Comment (zyn0217) [reply clang/lib/Sema/SemaOverload.cpp:13504]: The only way `AmbiguousDecls` comes with elements is on line 13433, where we also set `IsResultAmbiguous` to true. However, we bail out of the function on line 13442 when IsResultAmbiguous

File: clang/lib/Sema/SemaOverload.cpp (hunk 2 above)
Comment (zyn0217) [reply clang/lib/Sema/SemaOverload.cpp:13300]: It is supposed to work, though I haven't yet devised a test to exercise that branch. My understanding is that if there were more than one candidate that isn't more constrained than the others, we should have ruled them out earlier when checking the full address-taken expression, namely in `resolveAddressOfSingleOverloadCandidate()`, whose logic is similar to this `AddressOfFunctionResolver::EliminateLessPartialOrderingConstrainedMatches`, which is mainly used for initialization stuff purpose.

We unfortunately ended up with these separate pieces of address-of resolution logic for different scenarios such as type deduction and initialization sequence construction. While we might be doing some redundant work, from my understanding, the function in its current form aligns with the standard's intent.

File: clang/test/CXX/drs/cwg29xx.cpp (hunk 1 above)
Comment (zyn0217) [reply clang/test/CXX/drs/cwg29xx.cpp:65]: Done. Now it tests `Example3` in C++11 onwards
(Example 1 contains constraint expressions so it needs c++20)

File: clang/test/CXX/drs/cwg29xx.cpp [hunk 5]
```diff
@@ -60,6 +60,92 @@ struct S {
...
+
+} // namespace Example2
+#endif
+
+#if __cplusplus >= 201103L
+namespace Example3 {
+
+template <typename T> void f(T &&, void (*)(T &&)); // #cwg2918_f
+
+void g(int &); // #1
```
Comment (Endilll) [inline clang/test/CXX/drs/cwg29xx.cpp:128]: `#1` is a valid marker for `VerifyDiagnosticConsumer`. It doesn't seem to be useful for you test, so I suggest to drop it together with `#2` and `#3`.

File: clang/lib/Sema/SemaConcept.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaConcept.cpp:1779]: Yeah, sorry, I thought I deleted this comment.

File: clang/lib/Sema/SemaOverload.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (erichkeane) [reply clang/lib/Sema/SemaOverload.cpp:13504]: Hmm... perhaps this was supposed to be higher? in the code?  I'm concerned about it, but if no tests fail, then I think we have to go with it.  Just kill the loop.

**Review by erichkeane — APPROVED** [review]
I'm happy when the others are.

**Comment by zyn0217** [comment]
I'll merge it as-is now - post review comments are welcome
