### PR TITLE
flang][debug] Run AddDebugInfo before TargetRewrite.

### LINKED ISSUE #108711: [flang][debug] Wrong signature for functions with complex return type.
See the following example. The type of the `fn` as shown by GDB is wrong. It shows integer as return type.

```
complex function fn(a)
    complex, intent(in) :: a
    fn = a
end function

program function_calls
    implicit none
    interface
        complex function fn(a)
            complex, intent(in) :: a
        end function
    end interface
    complex :: b, c
    c = fn(b)
    print *, c
end program
```

```
(gdb) ptype fn
type = integer (complex)
```

### PR DESCRIPTION
**Pull request by abidh**
This help us generate debug info that better represents the actual Fortran source code. It was briefly discussed [here](https://github.com/llvm/llvm-project/pull/113917#pullrequestreview-2401339038).
    
Fixes #108711.

### CODE REVIEW

**Review by tarunprabhu — APPROVED** [review]
Thanks Abid.

**Review by tblah — APPROVED** [review]
LGTM

File: flang/lib/Optimizer/Passes/Pipelines.cpp [hunk 1]
```diff
@@ -264,10 +264,10 @@ void createDefaultFIRCodeGenPassPipeline(mlir::PassManager &pm,
   addNestedPassToAllTopLevelOperations(pm, fir::createAbstractResultOpt);
   fir::addCodeGenRewritePass(
       pm, (config.DebugInfo != llvm::codegenoptions::NoDebugInfo));
+  fir::createDebugPasses(pm, config.DebugInfo, config.OptLevel, inputFilename);
```
Comment (jeanPerier) [inline flang/lib/Optimizer/Passes/Pipelines.cpp:267]: Do you still get the correct assembly names for the external procedures (and common blocks) given `addExternalNameConversionPass` that goes from the `_QPfoo` to `foo_` name is now run afterwards?

You can move it before if needed, it does not need to be run after the target-rewrite and compiler-generated-name-conversion-pass.

Comment (abidh) [reply flang/lib/Optimizer/Passes/Pipelines.cpp:268]: Thanks for catching this. I moved `ExternalNameConversion` early so that `linkageName` field in the debug is correct and added a test to check this.

**Review by jeanPerier — APPROVED** [review]
Thanks, LGTM
