### PR TITLE
[AMDGPU] Select 64-bit imm moves if can be encoded as 32 bit operand

### LINKED ISSUE #67781: AMDGPU: support folding 64-bit immediates
SIFoldOperands should support folding 64-bit immediates into literal operands.

Before GFX10 this was rarely a problem because most 64-bit instructions are VOP3 only and VOP3 did not allow a literal operand. One exception is V_FMAC_F64 on gfx90a+. Here's an example where we generate `v_fmac_f64_e32 v[0:1], s[4:5], v[2:3]` which could be folded to `v_fmac_f64_e32 v[0:1], 0x41200000, v[2:3]`: https://godbolt.org/z/EMTjfj6jb

On GFX10+ VOP3 can take a literal operand, so there are lots of 64-bit instructions that could be folded.

### PR DESCRIPTION
**Pull request by rampitec**
This allows folding of 64-bit operands if fit into 32-bit. Fixes https://github.com/llvm/llvm-project/issues/67781

### CODE REVIEW

**Comment by rampitec** [comment]
Includes https://github.com/llvm/llvm-project/pull/70274, I still do not see a good story about stacked changes.

**Review by arsenm — APPROVED** [review]

**Comment by rampitec** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> You can test this locally with the following command:
> View the diff from clang-format here.
> 
> ```diff
> diff --git a/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp b/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp
> index 284943eae465..f62e273253e6 100644
> --- a/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp
> +++ b/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp
> @@ -1094,23 +1094,23 @@ void SIInstrInfo::copyPhysReg(MachineBasicBlock &MBB,
>        Register DstSubReg = RI.getSubReg(DestReg, SubIdx);
>        Register SrcSubReg = RI.getSubReg(SrcReg, SubIdx);
>        MachineInstrBuilder MIB =
> -        BuildMI(MBB, MI, DL, get(AMDGPU::V_PK_MOV_B32), DstSubReg)
> -        .addImm(SISrcMods::OP_SEL_1)
> -        .addReg(SrcSubReg)
> -        .addImm(SISrcMods::OP_SEL_0 | SISrcMods::OP_SEL_1)
> -        .addReg(SrcSubReg)
> -        .addImm(0) // op_sel_lo
> -        .addImm(0) // op_sel_hi
> -        .addImm(0) // neg_lo
> -        .addImm(0) // neg_hi
> -        .addImm(0) // clamp
> -        .addReg(SrcReg, getKillRegState(UseKill) | RegState::Implicit);
> +          BuildMI(MBB, MI, DL, get(AMDGPU::V_PK_MOV_B32), DstSubReg)
> +              .addImm(SISrcMods::OP_SEL_1)
> +              .addReg(SrcSubReg)
> +              .addImm(SISrcMods::OP_SEL_0 | SISrcMods::OP_SEL_1)
> +              .addReg(SrcSubReg)
> +              .addImm(0) // op_sel_lo
> +              .addImm(0) // op_sel_hi
> +              .addImm(0) // neg_lo
> +              .addImm(0) // neg_hi
> +              .addImm(0) // clamp
> +              .addReg(SrcReg, getKillRegState(UseKill) | RegState::Implicit);
>        if (IsFirstSubreg)
>          MIB.addReg(DestReg, RegState::Define | RegState::Implicit);
>      } else {
>        MachineInstrBuilder Builder =
> -        BuildMI(MBB, MI, DL, get(Opcode), RI.getSubReg(DestReg, SubIdx))
> -        .addReg(RI.getSubReg(SrcReg, SubIdx));
> +          BuildMI(MBB, MI, DL, get(Opcode), RI.getSubReg(DestReg, SubIdx))
> +              .addReg(RI.getSubReg(SrcReg, SubIdx));
>        if (IsFirstSubreg)
>          Builder.addReg(DestReg, RegState::Define | RegState::Implicit);
>  
> @@ -5308,13 +5308,10 @@ void SIInstrInfo::legalizeOpWithMove(MachineInstr &MI, unsigned OpIdx) const {
>    MO.ChangeToRegister(Reg, false);
>  }
>  
> -unsigned SIInstrInfo::buildExtractSubReg(MachineBasicBlock::iterator MI,
> -                                         MachineRegisterInfo &MRI,
> -                                         MachineOperand &SuperReg,
> -                                         const TargetRegisterClass *SuperRC,
> -                                         unsigned SubIdx,
> -                                         const TargetRegisterClass *SubRC)
> -                                         const {
> +unsigned SIInstrInfo::buildExtractSubReg(
> +    MachineBasicBlock::iterator MI, MachineRegisterInfo &MRI,
> +    MachineOperand &SuperReg, const TargetRegisterClass *SuperRC,
> +    unsigned SubIdx, const TargetRegisterClass *SubRC) const {
>    MachineBasicBlock *MBB = MI->getParent();
>    DebugLoc DL = MI->getDebugLoc();
>    Register SubReg = MRI.createVirtualRegister(SubRC);
> @@ -5341,12 +5338,9 @@ unsigned SIInstrInfo::buildExtractSubReg(MachineBasicBlock::iterator MI,
>  }
>  
>  MachineOperand SIInstrInfo::buildExtractSubRegOrImm(
> -  MachineBasicBlock::iterator MII,
> -  MachineRegisterInfo &MRI,
> -  MachineOperand &Op,
> -  const TargetRegisterClass *SuperRC,
> -  unsigned SubIdx,
> -  const TargetRegisterClass *SubRC) const {
> +    MachineBasicBlock::iterator MII, MachineRegisterInfo &MRI,
> +    MachineOperand &Op, const TargetRegisterClass *SuperRC, unsigned SubIdx,
> +    const TargetRegisterClass *SubRC) const {
>    if (Op.isImm()) {
>      if (SubIdx == AMDGPU::sub0)
>        return MachineOperand::CreateImm(static_cast<int32_t>(Op.getImm()));
> ```

I didn't touch that. Github needs to do better.

File: llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp [hunk 1]
```diff
@@ -2568,6 +2570,12 @@ bool AMDGPUInstructionSelector::selectG_CONSTANT(MachineInstr &I) const {
   unsigned Opcode;
   if (DstRB->getID() == AMDGPU::VCCRegBankID) {
     Opcode = STI.isWave32() ? AMDGPU::S_MOV_B32 : AMDGPU::S_MOV_B64;
+  } else if (Size == 64 &&
+             AMDGPU::isValid32BitLiteral(I.getOperand(1).getImm(), IsFP)) {
+    Opcode = IsSgpr ? AMDGPU::S_MOV_B64_IMM_PSEUDO : AMDGPU::V_MOV_B64_PSEUDO;
+    I.setDesc(TII.get(Opcode));
+    I.addImplicitDefUseOperands(*MF);
+    return constrainSelectedInstRegOperands(I, TII, TRI, RBI);
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp:2578]: Control flow is a bit ugly here, with a return in the middle of an if ... else ... chain, but I don't have any great suggestions. And we can always clean it up with a later NFC patch.

File: llvm/lib/Target/AMDGPU/SIInstructions.td [hunk 2]
```diff
@@ -1934,6 +1934,26 @@ def : GCNPat <
...
+>;
+
+def : GCNPat <
+  (VGPRImm<(f64 fpimm)>:$imm),
+  (V_MOV_B64_PSEUDO (f64 (bitcast_fpimm_to_i64 $imm)))
+>;
+
+def : GCNPat <
+  (i64 imm:$imm),
+  (S_MOV_B64_IMM_PSEUDO imm:$imm)
```
Comment (jayfoad) [inline llvm/lib/Target/AMDGPU/SIInstructions.td:1949]: AIUI the whole point of S_MOV_B64_IMM_PSEUDO is that unlike S_MOV_B64 it can be used with any 64-bit imm, not just encodable ones. But here we're only going to select it for encodable constants after all. It would be nice to have a comment explaining all that. I guess the same applies to V_MOV_B64_PSEUDO.

**Review by jayfoad — APPROVED** [review]
> [AMDGPU] Select 64-bit moves
> 
> This allows folding of 64-bit operands if fit into 32-bit. Fixes #67781

Description could be improved: "Select 64-bit immediate moves", "... of 64-bit immediate operands if they can be encoded as 32-bit literals"?

Anyway LGTM, thanks.

File: llvm/lib/Target/AMDGPU/SIInstructions.td (hunk 2 above)
Comment (rampitec) [reply llvm/lib/Target/AMDGPU/SIInstructions.td:1952]: Added comment.
