### PR TITLE
[clangd] Support suppressions for driver diagnostics

### LINKED ISSUE #1142: Suppressing diagnostics does not work as expected
The suppression filter is added after we run the driver, so driver diagnostics (e.g. `drv_unknown_argument`) cannot be suppressed.

### Discussed in https://github.com/clangd/clangd/discussions/1135

<div type='discussions-op-text'>

<sup>Originally posted by **alexcocinda** May  2, 2022</sup>
I am getting these two errors, but my project builds fine:
```
Unknown argument: '-forward-unknown-to-host-compiler'                       
[clang: drv_unknown_argument]                                               
───────────────────────────────────────────────────────────
Unsupported option '--generate-code=arch=compute_75,code=[compute_75,sm_75]'
[clang: drv_unsupported_opt]                                                
```
I tried to disable them with the following `.clangd` config:

```
CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda-11.4
    - --cuda-gpu-arch=sm_75
    - -L/usr/local/cuda-11.4/lib64
    - -I/usr/local/cuda-11.4/include
Diagnostics:
  Suppress:
    - drv_unknown_argument
    - drv_unsupported_opt
```
I am running on Ubuntu 20.04 with clangd 14.0.0. Am I missing something?</div>

### PR DESCRIPTION
**Pull request by joeedh**
Rebase of https://reviews.llvm.org/D127844#
Fixes [#1142](https://github.com/clangd/clangd/issues/1142)

### CODE REVIEW

File: clang-tools-extra/clangd/Diagnostics.h [hunk 1]
```diff
@@ -183,7 +183,7 @@ class StoreDiags : public DiagnosticConsumer {
 /// Determine whether a (non-clang-tidy) diagnostic is suppressed by config.
 bool isDiagnosticSuppressed(const clang::Diagnostic &Diag,
                             const llvm::StringSet<> &Suppressed,
-                            const LangOptions &);
+                            const std::optional<LangOptions> &);
```
Comment (ArcsinX) [inline clang-tools-extra/clangd/Diagnostics.h]: Sorry I didn't notice this initially. This function is only used within Diagnostics.cpp. So we can remove it from Diagnostics.h and move it to an anonymous namespace within Diagnostics.cpp or make it static.
I think that was the reason of modification ConfigCompileTests.cpp in original patch (to get rid of direct isDiagnosticSuppressed() usage)

**Review by ArcsinX — APPROVED** [review]
LGTM
