### PR TITLE
[clang-format] Fix a regression of annotating PointerOrReference

### LINKED ISSUE #149010: clang-format 20 ignores reference alignment in requires clause
This is a change of behavior from clang-format 19.

Example .clang-format:

```
Language: Cpp
Standard: c++20
PointerAlignment: Left
ReferenceAlignment: Left
DerivePointerAlignment: false
```

Example input file:

```cpp
bool kTrivialExample = requires { static_cast< int && >(1); };
```

Example output with clang-format 20:

```cpp
bool kTrivialExample = requires { static_cast<int &&>(1); };
```

Example output with clang-format 19:

```cpp
bool kTrivialExample = requires { static_cast<int&&>(1); };
```

### PR DESCRIPTION
**Pull request by owenca**
Fixes #149010

### CODE REVIEW

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -3122,6 +3122,9 @@ class AnnotatingParser {
       }
     }
 
+    if (PrevToken->isTypeName(LangOpts))
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/TokenAnnotator.cpp]: So this does not work with `bool foo = requires { static_cast<MyType &&>(1); };`?

Comment (owenca) [reply clang/lib/Format/TokenAnnotator.cpp]: It works if `TypeNames: [MyType]` is added to the config, but I've added a heuristic so that it won't be necessary.

**Review by HazardyKnusperkeks — APPROVED** [review]
