### PR TITLE
[InstCombine] If inst in unreachable refers to an inst change it to poison (#65107)

### LINKED ISSUE #65107: LLVM ERROR: Instruction Combining did not reach a fixpoint after 1 iterations
```llvm
define i1 @f(i16 %0) {
  br label %BB1

BB1:                                              ; preds = %BB1, %BB
  %C = icmp ult i16 256, %0
  br i1 true, label %BB1, label %BB2

BB2:                                              ; preds = %BB1
  ret i1 %C
}
```

https://godbolt.org/z/h7o9sbEKP

```
LLVM ERROR: Instruction Combining did not reach a fixpoint after 1 iterations
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -passes instcombine <source>
 #0 0x00000000034a5a58 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x34a5a58)
 #1 0x00000000034a318c SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f8a50d47420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f8a5080a00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f8a507e9859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00000000007834af (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x7834af)
 #6 0x000000000300c8d8 combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, bool, llvm::LoopInfo*) InstructionCombining.cpp:0:0
 #7 0x000000000300cf4a llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x300cf4a)
 #8 0x00000000036ba32e llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x36ba32e)
 #9 0x0000000000d3fd8d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xd3fd8d)
#10 0x0000000002e0ebde llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2e0ebde)
#11 0x0000000000d247de llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xd247de)
#12 0x0000000002e0cbdc llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2e0cbdc)
#13 0x000000000088448a llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x88448a)
#14 0x000000000078e621 main (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x78e621)
#15 0x00007f8a507eb083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#16 0x000000000087980e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x87980e)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

### PR DESCRIPTION
**Pull request by ParkHanbum**
Instructions in unreachable basic blocks are removed, but terminators
are not. In this case, even instructions that are only referenced by
a terminator, such as a return instruction, cannot be processed
properly.

This patch changes the operand of a return instruction in an
unreachable basic block to poison if it refers to the instruction,
allowing the instruction to be properly processed.

### CODE REVIEW

**Comment by nikic** [comment]
As I wrote in https://github.com/llvm/llvm-project/issues/65107#issuecomment-1890391251, I don't think this is the correct way to fix the issue.

**Comment by ParkHanbum** [comment]
> As I wrote in [#65107 (comment)](https://github.com/llvm/llvm-project/issues/65107#issuecomment-1890391251), I don't think this is the correct way to fix the issue.

I read your comment but I didn't know what that mean. what we do incorrectly exactly?

**Comment by nikic** [comment]
@ParkHanbum My suggestion is to fold
```llvm
define i1 @f(i16 %0) {
  br label %BB1

BB1:                                              ; preds = %BB1, %BB
  %C = icmp ult i16 256, %0
  br i1 true, label %BB1, label %BB2

BB2:                                              ; preds = %BB1
  ret i1 %C
}
```
to
```llvm
define i1 @f(i16 %0) {
  br label %BB1

BB1:                                              ; preds = %BB1, %BB
  %C = icmp ult i16 256, %0
  br i1 true, label %BB1, label %BB2

BB2:                                              ; preds = %BB1
  ret i1 poison
}
```
at which point `%C` becomes dead and can be removed, without having it to sink into BB2 first.

This is a more general solution, which allows us to handle additional cases. For example, cases where we wouldn't sink the instruction due to complex CFG, and cases where the instruction is used both in the dead block and somewhere else, in which case removing the use in the dead block may enable a one-use fold.

**Comment by ParkHanbum** [comment]
@nikic sounds reasonable. I'll change it like that!

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 1]
```diff
@@ -2779,6 +2779,11 @@ llvm::removeAllNonTerminatorAndEHPadInstructions(BasicBlock *BB) {
   Instruction *EndInst = BB->getTerminator(); // Last not to be deleted.
   // RemoveDIs: erasing debug-info must be done manually.
   EndInst->dropDbgValues();
+
+  if (isa<ReturnInst>(EndInst) && EndInst->getNumOperands() > 0 &&
+      isa<Instruction>(EndInst->getOperand(0)))
+    EndInst->setOperand(0, PoisonValue::get(EndInst->getOperand(0)->getType()));
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/Local.cpp:2785]: We shouldn't hardcode this to `ReturnInst`. We should replace any operand in the terminator. E.g. if this is a `br`, we should also set the condition to poison. (Skip the replacement for token types though.)

You should also do a similar change in `InstCombinerImpl::handleUnreachableFrom`.

Comment (ParkHanbum) [reply llvm/lib/Transforms/Utils/Local.cpp:2785]: @nikic got it. 
//‘ret’, ‘br’, 
// ‘switch’, ‘indirectbr’, ‘invoke’, ‘callbr’ ‘resume’, 
//‘catchswitch’, ‘catchret’, ‘cleanupret’, and ‘unreachable’.

I'll implement codes to handle above terminators.
except `CatchSwitch`. it is element of EHPad can be skipped.

Comment (nikic) [reply llvm/lib/Transforms/Utils/Local.cpp:2785]: The handling should be generic, not for specific terminator types.

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 2]
```diff
@@ -2770,15 +2770,31 @@ bool llvm::replaceAllDbgUsesWith(Instruction &From, Value &To,
   return false;
 }
 
+void llvm::handleUnreachableTerminator(Instruction *I) {
+  // RemoveDIs: erase debug-info on this instruction manually.
+  I->dropDbgValues();
+  unsigned Opcode = I->getOpcode();
+  if (Opcode >= Instruction::Ret && Opcode <= Instruction::Invoke &&
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/Local.cpp:2777]: Why do we need this opcode check?

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 3]
```diff
@@ -2770,15 +2770,31 @@ bool llvm::replaceAllDbgUsesWith(Instruction &From, Value &To,
...
+      I->getNumOperands() > 0) {
+    unsigned OpNum = isa<InvokeInst>(I) ? I->getNumOperands() - 1 : 0;
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/Local.cpp:2779]: You should loop over `I->operands()` here, not only update a single operand.

File: llvm/test/Transforms/InstCombine/sink_to_unreachable.ll [hunk 4]
```diff
@@ -157,3 +157,141 @@ bb3:
...
+;
+entry:
+  br label %loop
+
+loop:
+  %gep = getelementptr inbounds ptr, ptr %Ptr, i16 1
+  br i1 true, label %loop, label %unreach
+
+unreach:
+  invoke void %gep(i1 false)
```
Comment (nikic) [inline llvm/test/Transforms/InstCombine/sink_to_unreachable.ll:279]: Also add a call operand that can be replaced.

File: llvm/lib/Transforms/Utils/Local.cpp (hunk 3 above)
Comment (ParkHanbum) [reply llvm/lib/Transforms/Utils/Local.cpp:2779]: you mean set the poison to all of operand?

File: llvm/lib/Transforms/Utils/Local.cpp (hunk 2 above)
Comment (ParkHanbum) [reply llvm/lib/Transforms/Utils/Local.cpp:2777]: I thought that only the above commands could be processed among the terminators. This is just my opinion, so please let me know if I'm wrong. 

this is my sample IRs.
```
icatch.dispatch:
  %tmp1 = catchswitch within none [label %icatch] unwind to caller
icatch:
  %tmp2 = catchpad within %tmp1 [ptr null, i32 64, ptr null]
  catchret from %tmp2 to label %exit
unreach.cleanupret:
  %cl = cleanuppad within none []
  cleanupret from %cl unwind to caller

unreach.indirectbr:
  indirectbr ptr %gep, [label %unreach.switch]

unreach.callbr:
  callbr void asm "", "!i"()
  to label %dummy [label %toexit]
```

File: llvm/test/Transforms/InstCombine/sink_to_unreachable.ll (hunk 4 above)
Comment (ParkHanbum) [reply llvm/test/Transforms/InstCombine/sink_to_unreachable.ll:279]: I missed it! I'll update it ASAP

Comment (ParkHanbum) [reply llvm/test/Transforms/InstCombine/sink_to_unreachable.ll:279]: but call instruction is not belong to terminator, isn't it?

Comment (nikic) [reply llvm/test/Transforms/InstCombine/sink_to_unreachable.ll:279]: I meant an argument to the invoke. You currently have i1 false, but you can also pass an instruction to it, which could be replaced with poison.

Comment (ParkHanbum) [reply llvm/test/Transforms/InstCombine/sink_to_unreachable.ll:286]: it has be done!

File: llvm/lib/Transforms/Utils/Local.cpp (hunk 3 above)
Comment (ParkHanbum) [reply llvm/lib/Transforms/Utils/Local.cpp]: it has be done!

**Comment by dtcxzyw** [comment]
Could you have a look at https://github.com/dtcxzyw/llvm-opt-benchmark/pull/226#discussion_r1487162964?
It is wired to replace an argument in a reachable invocation with a poison.

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 5]
```diff
@@ -2770,15 +2770,32 @@ bool llvm::replaceAllDbgUsesWith(Instruction &From, Value &To,
   return false;
 }
 
+void llvm::handleUnreachableTerminator(Instruction *I) {
+  // RemoveDIs: erase debug-info on this instruction manually.
+  I->dropDbgValues();
+  unsigned Opcode = I->getOpcode();
+  if (Opcode >= Instruction::Ret && Opcode <= Instruction::Invoke &&
+      I->getNumOperands() > 0) {
+    for (unsigned i = 0; i < I->getNumOperands(); i++) {
```
Comment (nikic) [inline llvm/lib/Transforms/Utils/Local.cpp:2779]:
```suggestion
    for (Use &U : I->operands())
```
and then `U.set()`.

File: llvm/lib/Transforms/InstCombine/InstructionCombining.cpp [hunk 6]
```diff
@@ -3100,9 +3100,8 @@ void InstCombinerImpl::handleUnreachableFrom(
     MadeIRChange = true;
   }
 
-  // RemoveDIs: to match behaviour in dbg.value mode, drop debug-info on
-  // terminator too.
-  BB->getTerminator()->dropDbgValues();
+  // if terminator refer instruction, transform it into poison.
+  handleUnreachableTerminator(BB->getTerminator());
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3104]:
```suggestion
  MadeIRChange |= handleUnreachableTerminator(BB->getTerminator());
```
and return whether a change was made from that function.

File: llvm/lib/Transforms/Utils/Local.cpp [hunk 7]
```diff
@@ -2762,15 +2762,30 @@ bool llvm::replaceAllDbgUsesWith(Instruction &From, Value &To,
   return false;
 }
 
+bool llvm::handleUnreachableTerminator(Instruction *I) {
+  bool Changed = false;
+  // RemoveDIs: erase debug-info on this instruction manually.
+  I->dropDbgValues();
+  for (Use &U : I->operands()) {
+    Value *Op = U.get();
+    if (isa<Instruction>(Op) && !Op->getType()->isTokenTy()) {
```
[the remark this answers is not in the document]
Comment (ParkHanbum) [reply llvm/lib/Transforms/Utils/Local.cpp:2771]: ok. I have a question. when Op is Poison it can pass `isa<Instruction>(Op)` condition?

[the remark this answers is not in the document]
Comment (nikic) [reply llvm/lib/Transforms/Utils/Local.cpp:2771]: Nope :) You are right, checking poison is unnecessary.

File: llvm/lib/Transforms/InstCombine/InstructionCombining.cpp [hunk 8]
```diff
@@ -3231,9 +3231,8 @@ void InstCombinerImpl::handleUnreachableFrom(
     MadeIRChange = true;
   }
 
-  // RemoveDIs: to match behaviour in dbg.value mode, drop debug-info on
-  // terminator too.
-  BB->getTerminator()->dropDbgValues();
+  if (!DT.isReachableFromEntry(BB))
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3234]: Your previous version here was correct. handleUnreachableFrom already guarantees that the code is unreachable. Checking isReachableFromEntry does not work as desired inside InstCombine (it does not make use of reachability knowledge private to InstCombine).

File: llvm/include/llvm/Transforms/Utils/Local.h [hunk 9]
```diff
@@ -357,6 +357,13 @@ Value *salvageDebugInfoImpl(Instruction &I, uint64_t CurrentLocOps,
 bool replaceAllDbgUsesWith(Instruction &From, Value &To, Instruction &DomPoint,
                            DominatorTree &DT);
 
+/// If a terminator in an unreachable basic block has an operand of type
+/// Instruction, transform it into poison. Return true if any operands
+/// are changed to poison. Original Values prior to being changed to poison
+/// be returned to PoisonedValues.
```
Comment (nikic) [inline llvm/include/llvm/Transforms/Utils/Local.h:363]:
```suggestion
/// are returned in PoisonedValues.
```

File: llvm/lib/Transforms/InstCombine/InstructionCombining.cpp [hunk 10]
```diff
@@ -3231,9 +3231,12 @@ void InstCombinerImpl::handleUnreachableFrom(
     MadeIRChange = true;
   }
 
-  // RemoveDIs: to match behaviour in dbg.value mode, drop debug-info on
-  // terminator too.
-  BB->getTerminator()->dropDbgValues();
+  SmallVector<Value *, 4> Changed;
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3234]:
```suggestion
  SmallVector<Value *> Changed;
```

**Review by nikic — APPROVED** [review]
LGTM

File: llvm/include/llvm/Transforms/Utils/Local.h [hunk 11]
```diff
@@ -357,6 +357,13 @@ Value *salvageDebugInfoImpl(Instruction &I, uint64_t CurrentLocOps,
 bool replaceAllDbgUsesWith(Instruction &From, Value &To, Instruction &DomPoint,
                            DominatorTree &DT);
 
+/// If a terminator in an unreachable basic block has an operand of type
+/// Instruction, transform it into poison. Return true if any operands
+/// are changed to poison. Original Values prior to being changed to poison
+/// are returned to PoisonedValues.
```
Comment (dtcxzyw) [inline llvm/include/llvm/Transforms/Utils/Local.h:363]:
```suggestion
/// are returned in \p PoisonedValues.
```

**Comment by aaronpuchert** [comment]
As this fixes a crash, do you think we should port it back to LLVM 18? We're [running into this](https://bugzilla.opensuse.org/show_bug.cgi?id=1221664) with KDE 6 on aarch64.

CC @tstellar.

**Comment by nikic** [comment]
@aaronpuchert No, this change shouldn't be backported -- it's an optimization improvement, not a bug fix. The error is a development tool, not intended to surface to users.

You probably need to backport this mesa patch: https://gitlab.freedesktop.org/mesa/mesa/-/commit/99f0449987bec1f82cd42a06f40bb4a863a37792 We ran into a similar openQA failure in Fedora, and this is the fix for it.

**Comment by aaronpuchert** [comment]
Thanks, I was just confused by the crash tag on #65107. Will forward your suggestion.
