### PR TITLE
[clang-doc] Add regression test for test comments in macros

### LINKED ISSUE #59819: [clang-doc] Comments in macros don't appear in the generated docs
Make a class, declare some of its methods in a macro, with /* comments */ on them. They don't appear in the docs.

An example in action: https://danakj.github.io/subspace-docs/sus/num/i32.html

```cpp
struct i32 final {
  _sus__signed_impl(i32, /*PrimitiveT=*/int32_t, /*UnsignedT=*/u32);
};
```
In `_sus__signed_impl`:
```cpp
#define _sus__signed_log(T)                                                   \
  /** Returns the base 2 logarithm of the number, rounded down.               \
   *                                                                          \
   * Returns None if the number is negative or zero.                          \
   */                                                                         \
  constexpr Option<u32> checked_log2() const& {                               \
    if (primitive_value <= 0) [[unlikely]] {                                  \
      return Option<u32>::none();                                             \
    } else {                                                                  \
      uint32_t zeros = __private::leading_zeros_nonzero(                      \
          ::sus::marker::unsafe_fn,                                           \
          __private::into_unsigned(primitive_value));                         \
      return Option<u32>::some(BITS - 1_u32 - u32(zeros));                  \
    }                                                                         \
  }
```

The docs:
```
checked_log2
public [Option](https://danakj.github.io/subspace-docs/sus/option/Option.html) checked_log2()

Defined at line [37](https://github.com/chromium/subspace/blob/main/subspace/num/signed_integer.h#37) of file [signed_integer.h](https://github.com/chromium/subspace/blob/main/subspace/num/signed_integer.h)
```

### PR DESCRIPTION
**Pull request by ZhongUncle**
Fixes https://github.com/llvm/llvm-project/issues/59819. The underlying problem was fixed in https://reviews.llvm.org/D142560, but this patch adds a proper regression test.

### CODE REVIEW

**Comment by ZhongUncle** [comment]
@ilovepi  I am not familiar with PR, so accidentally closed the previous PR. This is a new one. Sorry for that.

**Comment by ilovepi** [comment]
> @ilovepi I am not familiar with PR, so accidentally closed the previous PR. This is a new one. Sorry for that.

It's fine. IIRC you can reopen one pretty easily, but 🤷 Its no problem.

**Comment by ilovepi** [comment]
Ah, I see you deleted your repository, then yeah, that would make it hard to reopen.

**Comment by ilovepi** [comment]
>I am not familiar with PR, so accidentally closed the previous PR https://github.com/llvm/llvm-project/pull/132360. This is a new one.

You can remove this part from the description. It isn't relevant to the rest of the project, and doesn't belong in the commit log.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 1]
```diff
@@ -0,0 +1,34 @@
+// Fixes #59819. The underlying problem was fixed in https://reviews.llvm.org/D142560, but this patch adds a proper regression test.
+// RUN: rm -rf %t && mkdir -p %t
+// RUN: clang-doc --format=md --doxygen --output=%t --executor=standalone %s
+// RUN: FileCheck %s < %t/GlobalNamespace/MyClass.md --check-prefix=MD-MYCLASS-LINE
+// RUN: FileCheck %s < %t/GlobalNamespace/MyClass.md --check-prefix=MD-MYCLASS
+// RUN: clang-doc --format=html --doxygen --output=%t --executor=standalone %s
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:6]:
```suggestion
// RUN: FileCheck %s < %t/GlobalNamespace/MyClass.md --check-prefix=MD-MYCLASS

// RUN: clang-doc --format=html --doxygen --output=%t --executor=standalone %s
```

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+// RUN: FileCheck %s < %t/GlobalNamespace/MyClass.html --check-prefix=HTML-MYCLASS
+
+#define DECLARE_METHODS                                           \
+    /**   							  \
+     * @brief Declare a method to calculate the sum of two numbers\
+     */                                                           \
+    int Add(int a, int b)                                         \
+    {                                                             \
+        return a + b;                                             \
+    }
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:17]:
```suggestion
    int Add(int a, int b)  {                                      \
        return a + b;                                             \
    }
```
Lets try and format this file according to the LLVM style. https://github.com/llvm/llvm-project/pull/132428 has the command I used to format other files. please try that on this test file. Otherwise, I'll need to make lots of comments on formatting.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+// MD-MYCLASS: ### Add
+// MD-MYCLASS: *public int Add(int a, int b)*
+// MD-MYCLASS: **brief** Declare a method to calculate the sum of two numbers
+
+// HTML-MYCLASS: <p>public int Add(int a, int b)</p>
+// HTML-MYCLASS: <div>brief</div>
+// HTML-MYCLASS: <p> Declare a method to calculate the sum of two numbers</p>
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: It isn't clear to me from the test if the `defined at...` part is matching where you want it. the following checks in the class body should probably have the `-NEXT:` suffix so we know we're matching the last part of the the `Add()` defintion w/in the macro.

Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: > It isn't clear to me from the test if the `defined at...` part is matching where you want it. the following checks in the class body should probably have the `-NEXT:` suffix so we know we're matching the last part of the the `Add()` defintion w/in the macro.

Yeah, I notice its line is in class, rather than line comment in macro.
Can you give me a example of -NEXT:? I don't know how to use it.

Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: I also have another problem: Why HTML match is not similar to Markdown?

Because I refer to `enum.cpp` to write this match. It matchs different parts. So I don't make sense which part must match in HTML.

Markdown match is clearly, HTML seem to ignore something.

Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-next-directive has information on how the `-NEXT` suffix works.

You use it the following way.

```
MYCHECK: match first line
MYCHECK-NEXT: match has to be on following line after the previous MYCHECK
MYCHECK: match something (potentially) far away
MYCHECK-NEXT: match has to be on the following line after the previous MYCHECK
```

What this allows you do do is be certain you're matching the correct part of the output, and that you're not accidentally matching things out of order.

This becomes more obvious w/ things in codegen where you have easy to spot delimiters, but are also likely to have many duplicate lines in your test program (e.g. most load instructions look the same).

So you use this pattern to match the start of a unique sequence w/ MYCHECK (or whatever your prefix is), and then use MYCHECK-NEXT to make sure the following lines match right afterwards, and not anywhere else.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 4]
```diff
@@ -0,0 +1,34 @@
+// Fixes #59819. The underlying problem was fixed in https://reviews.llvm.org/D142560, but this patch adds a proper regression test.
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:1]:
```suggestion
// Regression test for https://github.com/llvm/llvm-project/issues/59819

```

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp (hunk 3 above)
Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: > I also have another problem: Why HTML match is not similar to Markdown?
> 
> Because I refer to `enum.cpp` to write this match. It matchs different parts. So I don't make sense which part must match in HTML.
> 
> Markdown match is clearly, HTML seem to ignore something.

I'm not sure what you are asking. FileCheck pattern matching will match what it finds in the file that matches. IIRC it will take the last thing it finds that matches, not the first. So your lines may match arbitrary things in the output.

The markdown has a lot of empty lines, which makes writing checks w/ a `-NEXT` suffix hard to do. HTML is much more structured, so its (generally) more difficult to accidentally match something if you write stricter checks.

**Comment by ilovepi** [comment]
> I just have submitted a GSoC proposal, can you give me some advices?

This is a review thread for this feature. Please ask for feedback on the discourse thread. Typically you'd share a draft of your proposal w/ both prospective mentors over email (e.g. share a google doc or equivalent), and notify the thread that you'd like feedback.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+// MD-MYCLASS: **brief** Declare a method to calculate the sum of two numbers
+
+// HTML-MYCLASS: <p>public int Add(int a, int b)</p>
+// HTML-MYCLASS: <div>brief</div>
+// HTML-MYCLASS: <p> Declare a method to calculate the sum of two numbers</p>
+
+
+class MyClass {
+public:
+// MD-MYCLASS-LINE: *Defined at {{.*}}clang-tools-extra{{[\/]}}test{{[\/]}}clang-doc{{[\/]}}macro.cpp#[[@LINE+2]]*
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:30]: Looking at the premerge CI failure, this line fails to match, because this file is `comments-in-macros.cpp` and not `macro.cpp`.  You can update your check to fix this. Same problem for the check below this.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp (hunk 3 above)
Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:25]: Thank you very much for the explanation, I'll learn about these new LLVM concepts and get familiar with the FileCheck tools, and then improve the code. However, recently I am preparing for the interview for graduate school, so please forgive me for the slow progress.

File: clang-tools-extra/test/clang-doc/comments-in-macros.cpp [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+// HTML-MYCLASS-LINE: <p>Defined at line [[@LINE+1]] of file {{.*}}clang-tools-extra{{[\/]}}test{{[\/]}}clang-doc{{[\/]}}macro.cpp</p>
```
Comment (ilovepi) [inline clang-tools-extra/test/clang-doc/comments-in-macros.cpp:32]: The line number seems to not be where you expect in the test. Does this pass for you locally?

Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:32]: > The line number seems to not be where you expect in the test. Does this pass for you locally?

The line number is relative position, they are correct. 

Not passed may be due to `\` in EOL of comment. We talked about it in previous cloesd issue https://github.com/llvm/llvm-project/pull/132360#discussion_r2007941750. 

If I add `\`to each EOL in comment, it will generate some `\` in doc generated. So it doesn't passed. You said I can add `\` to each EOL, and report it as a new issue.

Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:32]: I understand how the relative line number works in the check line. I'm asking if this test passes when you run the test. So does `ninja check-clang-extra-clang-doc` pass w/ your changes? I think the line number reported is the line that defines the class, not where you wrote the macro that got expanded.

> Do we need it to generate completely correct Markdown/HTML codes and pass the test? Or can it have some harmless errors and pass the test?

Well, its a test, so it needs to be correct w.r.t. the thing you're testing, and shouldn't be broken overall (or at least not broken in a new way). 

That said, if there's an issue where the line number is not reported correctly, and that is a new/unrelated issue, then I'm OK if there is a corresponding tracking bug, and we have a TODO in the test referring to that bug.

Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:32]: > So does `ninja check-clang-extra-clang-doc` pass w/ your changes?

No, it doesn't passed w/ my change. I also test it via `llvm-lit llvm-project/clang-tools-extra/test/clang-doc/`. 

Because below code
```
#define DECLARE_METHODS                                           \
    /**                                                           \
     * @brief Declare a method to calculate the sum of two numbers\
     */                                                           \
    int Add(int a, int b) {                                       \
        return a + b;                                             \
    }
```
will generate something like below (there are additional `\` appearing):
```
\    
Declare a method to calculate the sum of two numbers\
```
rather than correct content generated:
```
Declare a method to calculate the sum of two numbers
```
But I test it using correct content generated. It is why not pass test. They don't match, so not pass. 

We discussed this rare comment style before, and you suggested that I add a `\` to each EOL, because it is example in #59819. But recently, I noticed via the editor highlighting that if you add a `\`, it will be considered as a character in the comment, rather than indicating the comment as a whole. If you add a `\`, it will be considered as a character in the comment.

Below image is in vim, you can see color of `\` is same as comment (I also test it in VS Code, same highlight):
截屏2025-04-17 14 39 51

So I don't think that it is issues of other feature. The problem is our example.

At beginning, I use this kind of comment
```
#define DECLARE_METHODS                                           \
    /**                                                           
     * @brief Declare a method to calculate the sum of two numbers
     */                                                           \
    int Add(int a, int b) {                                       \
        return a + b;                                             \
    }
```

It passed test. So I think: **Should I change code like above**?



> Well, its a test, so it needs to be correct w.r.t. the thing you're testing, and shouldn't be broken overall (or at least not broken in a new way).

Oh, make sense. I will remove this line check in Class. I checked the line numbers here because I saw it written in other tests, so I thought I had to check all the key parts.

Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp:32]: I think we may be talking past one another.

1)  the test needs to pass before it can land. I won't approve a patch with broken tests. 
2) The test should reflect what's actually going on right now. We may want to add some XFAIL test that has the correct behavior too.
3) looking at the test output, I don't see anything having to do w/ the `\` characters in the macro and the failing test check

```+ FileCheck /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-clshd-1/llvm-project/github-pull-requests/clang-tools-extra/test/clang-doc/comments-in-macros.cpp --check-prefix=MD-MYCLASS-LINE
/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-clshd-1/llvm-project/github-pull-requests/clang-tools-extra/test/clang-doc/comments-in-macros.cpp:31:21: error: MD-MYCLASS-LINE: expected string not found in input
// MD-MYCLASS-LINE: *Defined at {{.*}}clang-tools-extra{{[\/]}}test{{[\/]}}clang-doc{{[\/]}}macro.cpp#[[@LINE+2]]*
                    ^
<stdin>:1:1: note: scanning from here
# class MyClass
^
<stdin>:1:1: note: with "@LINE+2" equal to "33"
# class MyClass
^
<stdin>:3:95: note: possible intended match here
*Defined at /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-clshd-1/llvm-project/github-pull-requests/clang-tools-extra/test/clang-doc/comments-in-macros.cpp#29*
                                                                                              ^

Input file: <stdin>
Check file: /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-clshd-1/llvm-project/github-pull-requests/clang-tools-extra/test/clang-doc/comments-in-macros.cpp

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: # class MyClass 
check:31'0     X~~~~~~~~~~~~~~~ error: no match found
check:31'1                      with "@LINE+2" equal to "33"
            2:  
check:31'0     ~
            3: *Defined at /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-clshd-1/llvm-project/github-pull-requests/clang-tools-extra/test/clang-doc/comments-in-macros.cpp#29* 
check:31'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
That output says the check didn't see what you told it to expect. It found a line that looks right, but the line # is wrong (29 instead of 33). I don't see anyting failing due to a stray `\` in the output.

You're also asking about changing the macro, but the way you're trying to change it makes it invalid as a macro, so no, you can't do that. If you don't belevie me, dump the preprocessor output, and/or dump the AST w/ clang.

> Oh, make sense. I will remove this line check in Class. I checked the line numbers here because I saw it written in other tests, so I thought I had to check all the key parts.

Those are important things to test. You're just not testing it correctly, or more accuratly, you're expectation of the current behavior isn't correct. You have two choices 1) update the test to output the current line number and file an issue that it works in an unexpected way, or 2) fix the implementation in clang-doc so that it gets the correct line number. I'd suggest 1), since I expect that to be quite challenging.

Comment (ilovepi) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp]: yes, I believe I mentioned that the file name didn't match in an earlier comment. 

This patch is still not passing on CI, so please make it pass. I don't quite remember the parsing rules, so you'll either need to confirm the behavior by checking the AST, or by looking at the preprocessed output. I'm fine w/ any of the above if the test passes. We can always fix clang-doc behavior later if we don't like something about it or address it in clang's parsing.

Comment (ZhongUncle) [reply clang-tools-extra/test/clang-doc/comments-in-macros.cpp]: > I'm fine w/ any of the above if the test passes.

OK, I update code and passed CI. Please check.

**Review by ilovepi — APPROVED** [review]
