### PR TITLE
  [clang][CodeGen] Fix size calculation in vbptr split memory region in EmitNullBaseClassInitialization

### LINKED ISSUE #42101: Crash after explicit call to a base constructor with virtual base
|  |  |
| --- | --- |
| Bugzilla Link | [42756](https://llvm.org/bz42756) |
| Version | 8.0 |
| OS | Windows NT |
| Attachments | [Minimal example that reproduces the issue](https://user-images.githubusercontent.com/60944935/143759532-25cc5b40-80d7-4e84-b0c9-c7f42daf3d6f.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@zygoloid |

## Extended Description 

The code below crashes Windows:

struct interface { };
struct base1_if : virtual interface { };
struct base2_if : virtual interface { };
struct base_if : base1_if, base2_if { };

struct derived : base_if {
    derived()
        : base_if()
    { }
};

int main() { derived d; }

Command line:
$ clang-cl -v
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
$ clang-cl main.cpp
$ main.exe

Few notes:
- Removing explicit call to "base_if" avoids the issue.
- Generated assembly contains "memset(addr, 0, r8,0FFFFFFFFFFFFFFF8h)":

        00007FF7482310A9  mov         r8,0FFFFFFFFFFFFFFF8h  
        00007FF7482310B0  mov         dword ptr [rsp+2Ch],eax  
        00007FF7482310B4  call        memset (07FF748232FE0h)

### PR DESCRIPTION
**Pull request by schittir**
When splitting memory stores around multiple virtual base pointers (vbptrs)
  in the Microsoft ABI, the calculation for the size of the memory region after
  each vbptr was incorrect.

  The bug/old calculation: SplitAfterSize = LastStoreSize - SplitAfterOffset
  This subtracts an absolute offset from a relative size, causing
  incorrect (too small) sizes after the second vbptr.
  
  The correct size should be:
  SplitAfterSize = (LastStoreOffset + LastStoreSize) - SplitAfterOffset

  Since all store regions extend to the end of the non-virtual portion (NVSize),
  this patch uses the simplified form: 
  SplitAfterSize = NVSize - SplitAfterOffset

  The bug causes the assertion failure: "negative store size!"
  Fixes https://github.com/llvm/llvm-project/issues/42101

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Does this fix #42101 ?  If it does, can you mention that in the commit message, and add a testcase?

File: clang/test/CodeGenCXX/microsoft-abi-multiple-vbptrs.cpp [hunk 1]
```diff
@@ -0,0 +1,86 @@
+// RUN: %clang_cc1 -triple x86_64-windows-msvc -std=c++11 -emit-llvm -o - %s | FileCheck %s
```
Comment (efriedma-quic) [inline clang/test/CodeGenCXX/microsoft-abi-multiple-vbptrs.cpp]: What is this testcase testing? It appears to pass without the patch

File: clang/lib/CodeGen/CGExprCXX.cpp [hunk 2]
```diff
@@ -546,7 +545,7 @@ static void EmitNullBaseClassInitialization(CodeGenFunction &CGF,
       Stores.emplace_back(SplitBeforeOffset, SplitBeforeSize);
 
     CharUnits SplitAfterOffset = VBPtrOffset + VBPtrWidth;
-    CharUnits SplitAfterSize = LastStoreSize - SplitAfterOffset;
+    CharUnits SplitAfterSize = NVSize - SplitAfterOffset;
```
Comment (efriedma-quic) [inline clang/lib/CodeGen/CGExprCXX.cpp]: The more general way to write this would be `LastStoreOffset + LastStoreSize - SplitAfterOffset`... but that's equivalent to `NVSize - SplitAfterOffset` because the last store always goes to the end.  So this is fine.

**Comment by schittir** [comment]
> Does this fix #42101 ? If it does, can you mention that in the commit message, and add a testcase?

I am

> Does this fix #42101 ? If it does, can you mention that in the commit message, and add a testcase?

Yes, it does. I added the test case and commit description.

File: clang/lib/CodeGen/CGExprCXX.cpp (hunk 2 above)
Comment (schittir) [reply clang/lib/CodeGen/CGExprCXX.cpp]: Updated the description to clarify this.

**Review by efriedma-quic — APPROVED** [review]
LGTM

Note GitHub has special support if you write exactly "Fixes #42101" in the commit message: it closes the bug for you.

**Comment by schittir** [comment]
> LGTM
> 
> Note GitHub has special support if you write exactly "Fixes #42101" in the commit message: it closes the bug for you.

Thank you! I updated the wording.
