### PR TITLE
[clang-format] Fix a bug in wrapping function return type

### LINKED ISSUE #113766: [clang-format] Weird indentation of function definition after preprocessor directives
I would expect this code to be well-formatted:
```cpp
#ifdef __cplusplus
extern "C"
#endif
void f();
```

But clang-format disagrees and format it to:
```cpp
#ifdef __cplusplus
extern "C"
#endif
    void
    f();
```

Note that there is a related test:
https://github.com/llvm/llvm-project/blob/28a2f57c98431e71f62ce524481a1356a87b5696/clang/unittests/Format/QualifierFixerTest.cpp#L1182-L1187

---

1. I know this is probably opinionated, but do you agree this is indeed something that should be fixed?
2. I would like to help contribute and fix that issue myself? Any ideas where I should start at?

### PR DESCRIPTION
**Pull request by owenca**
Fixes #113766

### CODE REVIEW

File: clang/lib/Format/UnwrappedLineParser.cpp [hunk 1]
```diff
@@ -5091,8 +5091,10 @@ UnwrappedLineParser::parseMacroCall() {
 void UnwrappedLineParser::pushToken(FormatToken *Tok) {
   Line->Tokens.push_back(UnwrappedLineNode(Tok));
   if (MustBreakBeforeNextToken) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/UnwrappedLineParser.cpp:5093]: Maybe `MustBreakBeforeNextToken` should be renamed.

**Review by HazardyKnusperkeks — APPROVED** [review]

File: clang/lib/Format/UnwrappedLineParser.cpp (hunk 1 above)
Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:5093]: We can do that in a follow-up patch. Any suggestion?

Comment (HazardyKnusperkeks) [reply clang/lib/Format/UnwrappedLineParser.cpp:5093]: Couldn't we just reuse `FirstAfterPPDirectiveLine`?

Comment (owenca) [reply clang/lib/Format/UnwrappedLineParser.cpp:5093]: I renamed it to [`AtEndOfPPLine`](https://github.com/owenca/llvm-project/blob/a6ccda28f7569c1a03620d7520de7cfadc11f4a5/clang/lib/Format/UnwrappedLineParser.h#L304) instead.
