### PR TITLE
[InstCombine] Avoid folding `select(umin(X, Y), X)` with min/max values in false arm

### LINKED ISSUE #139050: Missing masked loop vectorization due to optimization in InstrCombine
Loop vectorization that worked on `clang-19` stopped on `clang-20`.

Minimal repro:
https://godbolt.org/z/Yd4KjG9Yo
https://godbolt.org/z/cP5jeeo5Y

I bisected the regression to [this PR](https://github.com/llvm/llvm-project/pull/116073). Looks like wrapping inside `select(...)` confuses LoopVectorizer.

Backreference: https://github.com/ClickHouse/ClickHouse/pull/77352#issuecomment-2852255156

### PR DESCRIPTION
**Pull request by thevar1able**
Fixes https://github.com/llvm/llvm-project/issues/139050.

Please suggest a better fix if I'm doing something wrong, I have no understanding of InstCombine optimization.
Missing optimization is a blocker for switching [ClickHouse build](https://github.com/ClickHouse/ClickHouse/pull/77352#issuecomment-2852255156) to `clang-20`.

The issue is that the following snippet:
```
declare i8 @llvm.umin.i8(i8, i8)

define i8 @masked_min_fold_bug(i8 %acc, i8 %val, i8 %mask) {
; CHECK-LABEL: @masked_min_fold_bug(
; CHECK:       %cond = icmp eq i8 %mask, 0
; CHECK:       %masked_val = select i1 %cond, i8 %val, i8 255
; CHECK:       call i8 @llvm.umin.i8(i8 %acc, i8 %masked_val)
;
  %cond = icmp eq i8 %mask, 0
  %masked_val = select i1 %cond, i8 %val, i8 255
  %res = call i8 @llvm.umin.i8(i8 %acc, i8 %masked_val)
  ret i8 %res
}
```

is being optimized to the following code, which can not be vectorized later. 
```
declare i8 @llvm.umin.i8(i8, i8) #0

define i8 @masked_min_fold_bug(i8 %acc, i8 %val, i8 %mask) {
  %cond = icmp eq i8 %mask, 0
  %1 = call i8 @llvm.umin.i8(i8 %acc, i8 %val)
  %res = select i1 %cond, i8 %1, i8 %acc
  ret i8 %res
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

Expected:
```
declare i8 @llvm.umin.i8(i8, i8) #0

define i8 @masked_min_fold_bug(i8 %acc, i8 %val, i8 %mask) {
  %cond = icmp eq i8 %mask, 0
  %masked_val = select i1 %cond, i8 %val, i8 -1
  %res = call i8 @llvm.umin.i8(i8 %acc, i8 %masked_val)
  ret i8 %res
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

https://godbolt.org/z/cYMheKE5r

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Why does one vectorize and not the other?

**Comment by thevar1able** [comment]
@nikic

`remark: loop not vectorized: value that could not be identified as reduction is used outside the loop [-Rpass-analysis=loop-vectorize]`
https://clang.godbolt.org/z/sqhYnrsYb

**Comment by nikic** [comment]
I see. The issue has no relation to the specific form of the select here, the problem is that we are breaking up a reduction pattern.

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp [hunk 1]
```diff
@@ -1654,6 +1654,29 @@ Instruction *InstCombinerImpl::visitCallInst(CallInst &CI) {
...
+        if ((TrueC && TrueC->isAllOnesValue()) ||
+            (FalseC && FalseC->isAllOnesValue())) {
+          LLVM_DEBUG(
+              dbgs()
+              << "InstCombine: skipping umin/umax folding for masked select\n");
+          return nullptr;
+        }
+      }
+    }
+  }
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp]: The fold you are actually interested in is located at https://github.com/llvm/llvm-project/blob/a19889c3952ed70d93aa40e36e38404e531f1ce1/llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp#L3870-L3879 If you want to add extra checks, they should be added there or inside FoldOpIntoSelect.

Though I'm not entirely sure precisely what we should be restricting.

Comment (thevar1able) [reply llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp]: Maybe it'd be better to revert https://github.com/llvm/llvm-project/pull/116073?

Comment (dtcxzyw) [reply llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp]: > Maybe it'd be better to revert https://github.com/llvm/llvm-project/pull/116073?

It may take more time to evaluate performance regression caused by the revert...

I'd like to disable this fold when the binary intrinsic is a reduction. We have a similar helper `matchSimpleRecurrence` in ValueTracking.

**Comment by nikic** [comment]
I've landed a phase ordering test in https://github.com/llvm/llvm-project/commit/cef5a3155bab9a2db5389f782471d56f1dd15b61. Please rebase & regenerate when updating this PR.

File: llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp (hunk 1 above)
Comment (nikic) [reply llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp]: > I'd like to disable this fold when the binary intrinsic is a reduction. We have a similar helper `matchSimpleRecurrence` in ValueTracking.

I agree that testing specifically for a recurrence would be best.

I think a simple check would look something like this (untested):

```
if (isa<MinMaxIntrinsic>(&Op))
  for (Value *IntrinOp : Op.operands())
    if (auto *PN = dyn_cast<PHINode>(IntrinOp))
      for (Value *PhiOp = PN->operands())
        if (PhiOp == &Op)
          return nullptr;
```

**Comment by thevar1able** [comment]
@nikic The test you added now fails, what's the next step?

**Comment by nikic** [comment]
> @nikic The test you added now fails, what's the next step?

Regenerate it using update_test_checks.py and commit the result.

File: llvm/lib/Transforms/InstCombine/InstructionCombining.cpp [hunk 2]
```diff
@@ -1719,6 +1719,13 @@ Instruction *InstCombinerImpl::FoldOpIntoSelect(Instruction &Op, SelectInst *SI,
   if (SI->getType()->isIntOrIntVectorTy(1))
     return nullptr;
 
+  if (isa<MinMaxIntrinsic>(&Op))
```
Comment (nikic) [inline llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:1724]: Add a comment here why we are doing this (avoid breaking min/max reduction pattern, which may prevent vectorization).

File: llvm/test/Transforms/InstCombine/select.ll [hunk 3]
```diff
@@ -5047,3 +5047,18 @@ define <2 x ptr> @select_freeze_constant_expression_vector_gep(i1 %cond, <2 x pt
...
+; ; CHECK-NEXT:  [[COND:%.*]] = icmp eq i8 [[MASK:%.*]], 0
+; ; CHECK-NEXT:  [[MASKED_VAL:%.*]] = select i1 [[COND:%.*]], i8 [[VAL:%.*]], i8 -1
+; ; CHECK-NEXT:  [[RES:%.*]] = call i8 @llvm.umin.i8(i8 [[ACC:%.*]], i8 [[MASKED_VAL:%.*]])
+; ; CHECK-NEXT:  ret i8 [[RES]]
+; ;
+;   %cond = icmp eq i8 %mask, 0
+;   %masked_val = select i1 %cond, i8 %val, i8 -1
+;   %res = call i8 @llvm.umin.i8(i8 %acc, i8 %masked_val)
+;   ret i8 %res
+; }
```
Comment (nikic) [inline llvm/test/Transforms/InstCombine/select.ll]: We'd still want the InstCombine test, but it should now have a loop with the reduction.

Comment (thevar1able) [reply llvm/test/Transforms/InstCombine/select.ll]: You want this test to have a loop, did I get you correctly? Won't it be the same as in https://github.com/llvm/llvm-project/commit/cef5a3155bab9a2db5389f782471d56f1dd15b61?

EDIT: I see that different optimizations are applied to `select.ll` and `vector-reductions.ll`

**Comment by nikic** [comment]
Why is this reverted back to the old code again?

**Comment by thevar1able** [comment]
@nikic I wasn't able to make your snippet work, sorry.

**Comment by nikic** [comment]
@thevar1able Doesn't exactly the code you had work? I tried it and the test was vectorized: https://gist.github.com/nikic/4cf44aac838daa41be953c8a7d06920c

**Comment by thevar1able** [comment]
@nikic No, it did not. I didn't realize at first that update_test_checks.py was picking up my `opt-19` from system. Later `ninja -C build check-llvm` had failed assertions on finding `vector body` section.

**Comment by thevar1able** [comment]
@nikic Sorry, I was wrong.

**Review by dtcxzyw — APPROVED** [review]
LG

**Review by nikic — APPROVED** [review]
LGTM

**Comment by thevar1able** [comment]
Is it ready for merge?

**Comment by thevar1able** [comment]
Thank you!

I see 20.1.7 was released just a couple hours before merge; is 20.1.8 expected, or should I expect this to land in 21?
