### PR TITLE
[Driver] Reject -mcmodel=tiny on X86

### LINKED ISSUE #125641: Crash when using '-mcmodel=tiny' on X86
The `mcmodel=tiny` memory model is only valid on ARM targets. While trying this on X86 compiler throws an internal error along with stack  dump. Here is the reduced testcase.

```
#include <stdio.h>
int main()
{ 
printf( "Hello, World!\n" ); 
return 0; 
}
``` 
Stack dump:
```
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -mcmodel=tiny <source>
1.	<eof> parser at end of file
 #0 0x0000000003b10218 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b10218)
 #1 0x0000000003b0e35c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b0e35c)
 #2 0x0000000003a5dbc3 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a5dbc3)
 #3 0x0000000003b05cfe llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b05cfe)
 #4 0x0000000000d4e3eb LLVMErrorHandler(void*, char const*, bool) cc1_main.cpp:0:0
 #5 0x0000000003a67c93 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a67c93)
 #6 0x0000000003a67df8 (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a67df8)
 #7 0x0000000002549148 llvm::X86TargetMachine::X86TargetMachine(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2549148)
 #8 0x00000000025491fc llvm::RegisterTargetMachine<llvm::X86TargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x25491fc)
 #9 0x0000000003db74cc clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3db74cc)
#10 0x0000000004460d95 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4460d95)
#11 0x00000000060005ec clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x60005ec)
#12 0x00000000044614b5 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44614b5)
#13 0x0000000004737121 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4737121)
#14 0x00000000046b777b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x46b777b)
#15 0x00000000048229e3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x48229e3)
#16 0x0000000000d50621 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd50621)
#17 0x0000000000d48e2d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#18 0x00000000044acc99 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#19 0x0000000003a5dac3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a5dac3)
#20 0x00000000044aceb9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#21 0x00000000044710dd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44710dd)
#22 0x0000000004472071 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4472071)
#23 0x000000000447c3fc clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x447c3fc)
#24 0x0000000000d4d2b1 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd4d2b1)
#25 0x0000000000c12464 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc12464)
#26 0x00007ae43b029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#27 0x00007ae43b029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#28 0x0000000000d488c5 _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd488c5)
```

[https://godbolt.org/z/c9qqGav9W](https://godbolt.org/z/c9qqGav9W)

### PR DESCRIPTION
**Pull request by ShashwathiNavada**
The mcmodel=tiny memory model is only valid on ARM targets. While trying this on X86 compiler throws an internal error along with stack dump. #125641 
This patch resolves the issue.
Reduced test case:
```
#include <stdio.h>
int main( void )
{
printf( "Hello, World!\n" ); 
return 0; 
}
```
```
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -mcmodel=tiny <source>
1.	<eof> parser at end of file
 #0 0x0000000003b10218 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b10218)
 #1 0x0000000003b0e35c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b0e35c)
 #2 0x0000000003a5dbc3 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a5dbc3)
 #3 0x0000000003b05cfe llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3b05cfe)
 #4 0x0000000000d4e3eb LLVMErrorHandler(void*, char const*, bool) cc1_main.cpp:0:0
 #5 0x0000000003a67c93 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a67c93)
 #6 0x0000000003a67df8 (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a67df8)
 #7 0x0000000002549148 llvm::X86TargetMachine::X86TargetMachine(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2549148)
 #8 0x00000000025491fc llvm::RegisterTargetMachine<llvm::X86TargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, std::optional<llvm::Reloc::Model>, std::optional<llvm::CodeModel::Model>, llvm::CodeGenOptLevel, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x25491fc)
 #9 0x0000000003db74cc clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3db74cc)
#10 0x0000000004460d95 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4460d95)
#11 0x00000000060005ec clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x60005ec)
#12 0x00000000044614b5 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44614b5)
#13 0x0000000004737121 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4737121)
#14 0x00000000046b777b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x46b777b)
#15 0x00000000048229e3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x48229e3)
#16 0x0000000000d50621 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd50621)
#17 0x0000000000d48e2d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#18 0x00000000044acc99 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#19 0x0000000003a5dac3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a5dac3)
#20 0x00000000044aceb9 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#21 0x00000000044710dd clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x44710dd)
#22 0x0000000004472071 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4472071)
#23 0x000000000447c3fc clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x447c3fc)
#24 0x0000000000d4d2b1 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd4d2b1)
#25 0x0000000000c12464 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc12464)
#26 0x00007ae43b029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#27 0x00007ae43b029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#28 0x0000000000d488c5 _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xd488c5)
```

### CODE REVIEW

**Comment by cor3ntin** [comment]
Can you add tests and a release note entry? Thanks!

**Comment by ShashwathiNavada** [comment]
> Can you add tests and a release note entry? Thanks!

Thank you for the response! 
Sure, will do that!

**Comment by ShashwathiNavada** [comment]
> Can you add tests and a release note entry? Thanks!

This PR adds diagnostics for unsupported options in mcmodel. Since this isn't a new feature, is a release note entry necessary?

**Comment by ShashwathiNavada** [comment]
> Can you add tests and a release note entry? Thanks!

@cor3ntin I have addressed your comment. Could you please look into it. Thank you!!

**Comment by ShashwathiNavada** [comment]
ping @cor3ntin

**Comment by ShashwathiNavada** [comment]
ping @cor3ntin  @hstk30-hw

**Comment by hstk30-hw** [comment]
Hi, these is a pending review suggestion. Just put the test cast to exist test file, maybe like clang/test/Driver/mcmodel.c
PLS

**Review by hstk30-hw — APPROVED** [review]
LGTM，thx. And you? @cor3ntin

**Comment by ShashwathiNavada** [comment]
ping @cor3ntin

**Comment by ShashwathiNavada** [comment]
ping @cor3ntin

**Comment by ShashwathiNavada** [comment]
@hstk30-hw I have been waiting for approval from @cor3ntin, the PR has been open for over 2 months now, can we go ahead and merge this if it's alright?

**Review by MaskRay — CHANGES_REQUESTED** [review]
We typically add such incompatibility check in clang/lib/Driver instead of clang/lib/Frontend.

(Apologies, I will have limited internet access between April 20th and May 4th, and my response time may be delayed.. Happy if a regular clang maintainer is happy.)

File: clang/lib/Frontend/CompilerInvocation.cpp [hunk 1]
```diff
@@ -1905,6 +1905,16 @@ bool CompilerInvocation::ParseCodeGenArgs(CodeGenOptions &Opts, ArgList &Args,
     Opts.setInlining(CodeGenOptions::NormalInlining);
   }
 
+  // -mcmodel option.
+  if (const llvm::opt::Arg *A =
+          Args.getLastArg(clang::driver::options::OPT_mcmodel_EQ)) {
+    llvm::StringRef modelName = A->getValue();
+    if (modelName == "tiny" && !(T.isARM() || T.isAArch64())) {
+      Diags.Report(diag::err_drv_unsupported_option_argument_for_target)
+          << A->getSpelling() << modelName << T.getTriple();
```
Comment (AaronBallman) [inline clang/lib/Frontend/CompilerInvocation.cpp:1914]:
```suggestion
    StringRef ModelName = A->getValue();
    if (ModelName == "tiny" && !(T.isARM() || T.isAArch64())) {
      Diags.Report(diag::err_drv_unsupported_option_argument_for_target)
          << A->getSpelling() << ModelName << T.getTriple();
```
Fixing for our coding style.

File: llvm/docs/ReleaseNotes.md [hunk 2]
```diff
@@ -240,6 +240,9 @@ Changes to Sanitizers
 Other Changes
 -------------
 
+* The -mcmodel=tiny option for the x86 architecture now triggers a frontend diagnostic.
```
Comment (AaronBallman) [inline llvm/docs/ReleaseNotes.md:243]: Oops, this belongs in `clang/docs/ReleaseNotes.rst` rather than in LLVM (because this is changing diagnostic behavior of the Clang driver).

Comment (AaronBallman) [inline llvm/docs/ReleaseNotes.md:243]:
```suggestion
* The ``-mcmodel=tiny`` option will now be diagnosed on all targets other than ARM or AArch64.
```

File: clang/test/Driver/mcmodel.c [hunk 3]
```diff
@@ -4,6 +4,7 @@
 // RUN: %clang --target=x86_64 -### -S -mcmodel=kernel %s 2>&1 | FileCheck --check-prefix=KERNEL %s
 // RUN: %clang --target=x86_64 -### -c -mcmodel=medium %s 2>&1 | FileCheck --check-prefix=MEDIUM %s
 // RUN: %clang --target=x86_64 -### -S -mcmodel=large %s 2>&1 | FileCheck --check-prefix=LARGE %s
+// RUN: not %clang --target=x86_64 -c -mcmodel=tiny %s 2>&1 | FileCheck %s
```
Comment (AaronBallman) [inline clang/test/Driver/mcmodel.c:7]: What about Line 2 of this file? That seems like it would now start failing, right?

**Comment by ShashwathiNavada** [comment]
> We typically add such incompatibility check in clang/lib/Driver instead of clang/lib/Frontend.
> 
> (Apologies, I will have limited internet access between April 20th and May 4th, and my response time may be delayed.. Happy if a regular clang maintainer is happy.)

Thanks for the response, I have made the changes in clang/lib/Driver

File: clang/test/Driver/mcmodel.c (hunk 3 above)
Comment (ShashwathiNavada) [reply clang/test/Driver/mcmodel.c]: Thanks for the response, I have modified the command.

File: clang/test/Driver/mcmodel.c [hunk 4]
```diff
@@ -44,3 +44,5 @@
 // ERR-AARCH64_32: error: unsupported argument 'small' to option '-mcmodel=' for target 'aarch64_32-unknown-linux'
 
 // ERR-LOONGARCH64-PLT-EXTREME: error: invalid argument '-mcmodel=extreme' not allowed with '-fplt'
+
+// CHECK: error: unsupported argument 'tiny' to option '-mcmodel=' for target '{{.*}}'
```
Comment (AaronBallman) [inline clang/test/Driver/mcmodel.c:48]: We have nothing with a check prefix of just `CHECK` so this will never actually be tested. Also, this is the same message as `ERR-TINY` so we wouldn't need this line anyway.

File: clang/lib/Driver/Driver.cpp [hunk 5]
```diff
@@ -1755,6 +1755,18 @@ Compilation *Driver::BuildCompilation(ArrayRef<const char *> ArgList) {
         << TC.getTriple().str();
   }
 
+  // Throw diagnosis if mcmodel=tiny option is passed for targets other than ARM
+  // or AArch64.
+  if (Arg *A = UArgs->getLastArg(options::OPT_mcmodel_EQ)) {
```
Comment (MaskRay) [inline clang/lib/Driver/Driver.cpp:1760]: Move to clang/lib/Driver/ToolChains/CommonArgs.cpp `addMCModel`. You might delete add an early return to that function and run `check-clang-driver` to find relevant tests. Then follow that style and add one for Arm.

Comment (MaskRay) [reply clang/lib/Driver/Driver.cpp:1760]: `tiny` is expected to work with AArch64.

Comment (ShashwathiNavada) [reply clang/lib/Driver/Driver.cpp:1765]: @MaskRay Thank you for your response!
I noticed that in the function you mentioned, there’s a check like this:

```
else if (Triple.getArch() == llvm::Triple::x86_64) {
    Ok = llvm::is_contained({"small", "kernel", "medium", "large", "tiny"}, CM);
}
```
I found that removing the tiny option here gives the desired result.
Would you mind confirming if this approach looks good before I push the changes?

**Comment by ShashwathiNavada** [comment]
ping @MaskRay

File: clang/docs/ReleaseNotes.rst [hunk 6]
```diff
@@ -391,6 +391,7 @@ Improvements to Clang's diagnostics
 
 
 - An error is now emitted when a ``musttail`` call is made to a function marked with the ``not_tail_called`` attribute. (#GH133509).
+- The ``-mcmodel=tiny`` option will now be diagnosed on all targets other than ARM or AArch64.
```
Comment (MaskRay) [inline clang/docs/ReleaseNotes.rst:394]: The commit message/description and the note should be changed. Only X86 is affected. This change is pretty niche and does not deserve a release note.

Comment (ShashwathiNavada) [reply clang/docs/ReleaseNotes.rst]: @MaskRay, Thank you for the response. I have removed the release note entry and updated the commit message as well.

**Review by MaskRay — APPROVED** [review]

**Comment by jplehr** [comment]
This patch causes a test fail on `check-flang` in our bot: https://lab.llvm.org/buildbot/#/builders/140/builds/22683
Local revert make the fail go away.
Not sure if this is a simple forward fix or something more substantial.

I tested with build: `ninja -G Ninja -C offload/cmake/caches/AMDGPUBot.cmake -S llvm -B build`

**Comment by Kewen12** [comment]
Hi there, we would appreciate it if you could revert this PR while investigating. It breaks our buildbot and will block our downstream merge.

**Comment by jplehr** [comment]
I put up https://github.com/llvm/llvm-project/pull/138959 which removes the offending `tiny` mcmodel from the Flang driver test. I don't know if this is the right fix though.
