### PR TITLE
[clang-format] Support globstar in .clang-format-ignore

### LINKED ISSUE #110160: [clang-format] .clang-format-ignore does not match `/` with `*` wildcard
When using a `.clang-format-ignore` file, a `*` wildcard is expected to match a directory separator. 
For example, a line containing `*g_*` should match any file in the current directory and all subdirectories that match the pattern `*g_*`

Currently, the `*` does not match the path separator. So a `*g_*` in the .clang-format-ignore file will only match this pattern for the current working directory. There does not seem to be a way to match the pattern for the current dir and subdirs.

Looking into the source code, it seems that this behavior is from the `matchFilePath` function, which is based on the POSIX `fnmatch()` function
https://github.com/llvm/llvm-project/blob/d4d38bcc3931d28d8b97d055258e27772119d0fe/clang/lib/Format/MatchFilePath.cpp#L10-L11

All of the following tests added to `MatchFilePathTest.cpp` fail:
```c++
  EXPECT_TRUE(match("some/nested/dir/file.cpp", "*nested*"));
  EXPECT_TRUE(match("some/nested/dir/file.cpp", "*/nested/*"));
  EXPECT_TRUE(match("some/nested/dir/g_file.cpp", "*g_*"));
  EXPECT_TRUE(match("some/nested/dir/g_file.cpp", "*/g_*"));
```

The `fnmatch()` function matches these cases:
https://godbolt.org/z/6qxYW41Yv

@owenca is this expected behavior?

P.S. I am seeing this behavior on Windows/MSVC, not sure if this affects all environments or is Windows specific.

### LINKED ISSUE #114969: clang-format continues to recurse into directories listed in .clang-format-ignore
Create a directory with a sub-directory. If we add the first directory into the ignore list, clang-format will still recurse into the sub-directory which is not expected.
Reasoning why it's not desirable, if you add a temporary build directory into the ignore list, clang-format will still format all files in sub-directories of the build directory.

Version: Ubuntu clang-format version 18.1.8 (++20240731024944+3b5b5c1ec4a3-1-exp1-20240731145000.144)

Recreate the directory structure, files, and execute clang-format:
`
mkdir -p level1/level2 && touch foo.c level1/bar.c level1/level2/bang.c && tree && echo 'level1/*' > .clang-format-ignore && shopt -s globstar && clang-format --verbose **/*
`
Result, it correctly ignores the file in level1 (bar.c), however continues to recurse into level2 (bang.c) which is not expected.

### PR DESCRIPTION
**Pull request by owenca**
Closes #110160.
Closes #114969.

### CODE REVIEW

File: clang/unittests/Format/MatchFilePathTest.cpp [hunk 1]
```diff
@@ -164,6 +164,41 @@ TEST_F(MatchFilePathTest, Path) {
...
+  EXPECT_TRUE(match("abc/foo", "abc/**"));
+  EXPECT_TRUE(match("abc/foo/", "abc/**"));
+  EXPECT_TRUE(match("abc/foo/bar", "abc/**"));
+
+  EXPECT_TRUE(match("a/b", "a/**/b"));
+  EXPECT_TRUE(match("a/x/b", "a/**/b"));
+  EXPECT_TRUE(match("a/x/y/b", "a/**/b"));
+
+  EXPECT_FALSE(match("a/x/b", "a**/b"));
+  EXPECT_FALSE(match("a/x/y/b", "a/**b"));
```
Comment (leijurv) [inline clang/unittests/Format/MatchFilePathTest.cpp:199]: This leaves me curious what `a/**b` should match, such as `a/x/b`, `a/b`, `a/xb`, `a/x/yb`?

Comment (owenca) [reply clang/unittests/Format/MatchFilePathTest.cpp:199]: When `**` are not globstar, it's equivalent to `*`. So `a/**b` is the same as `a/*b`, i.e. any file in `a/` with its name ending in `b`. OTOH `a/**/*b` would match any file in the directory tree rooted at `a/` with its name ending in `b`. The following bash session illustrates the difference:
```
~$ echo $BASH_VERSION
5.2.37(1)-release
~$ shopt globstar
globstar       	on
~$ ls -FR a
b	x/	xb

a/x:
b	yb
~$ echo a/**b
a/b a/xb
~$ echo a/**/*b
a/b a/x/b a/x/yb a/xb
~$ 
```

Comment (leijurv) [reply clang/unittests/Format/MatchFilePathTest.cpp:199]: Thanks! Could be worth testing, personally I might have guessed `a/**b` might have matched all of them, under the (false) assumption that `**` means "match anything, including `/`"

Comment (owenca) [inline clang/unittests/Format/MatchFilePathTest.cpp:199]:
```suggestion
  EXPECT_FALSE(match("a/x/b", "a/**b"));
```

**Review by mydeveloperday — APPROVED** [review]
