### PR TITLE
[hwasan] Fix stack tag mismatch report

### LINKED ISSUE #1723: TestCases/stack-uas.c occasionally misclassified as stack-buffer-overflow
Found as test flakiness on buildbot: https://lab.llvm.org/buildbot/#/builders/269/builds/4202/steps/9/logs/stdio

Relevant CLs:
- "[hwasan] Classify stack overflow, and use after scope" (https://github.com/llvm/llvm-project/commit/7db28dd3f897a)
- "[test][hwasan] Update another test after #76133" (https://github.com/llvm/llvm-project/commit/bb7f8f7938bf486ce67e824c94e9c87767694710)

Output from buildbot:
```
FAIL: HWAddressSanitizer-aarch64 :: TestCases/stack-uas.c (420 of 5436)
******************** TEST 'HWAddressSanitizer-aarch64 :: TestCases/stack-uas.c' FAILED ********************
Exit Code: 1
Command Output (stderr):
--
RUN: at line 2: /b/sanitizer-aarch64-linux/build/build_gcc/./bin/clang    -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta   -gline-tables-only -fsanitize=hwaddress -fuse-ld=lld -mllvm -hwasan-globals -mllvm -hwasan-use-short-granules -mllvm -hwasan-instrument-landing-pads=0 -mllvm -hwasan-instrument-personality-functions -O0 -g /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c -o /b/sanitizer-aarch64-linux/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/stack-uas.c.tmp && not  /b/sanitizer-aarch64-linux/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/stack-uas.c.tmp 2>&1 | FileCheck /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c
+ /b/sanitizer-aarch64-linux/build/build_gcc/./bin/clang -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -gline-tables-only -fsanitize=hwaddress -fuse-ld=lld -mllvm -hwasan-globals -mllvm -hwasan-use-short-granules -mllvm -hwasan-instrument-landing-pads=0 -mllvm -hwasan-instrument-personality-functions -O0 -g /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c -o /b/sanitizer-aarch64-linux/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/stack-uas.c.tmp
+ FileCheck /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c
+ not /b/sanitizer-aarch64-linux/build/build_gcc/runtimes/runtimes-bins/compiler-rt/test/hwasan/AARCH64/TestCases/Output/stack-uas.c.tmp
/b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c:73:12: error: CHECK: expected string not found in input
 // CHECK: Cause: use-after-scope
           ^
<stdin>:14:38: note: scanning from here
Potentially referenced stack objects:
                                     ^
<stdin>:15:1: note: possible intended match here
Cause: stack-buffer-overflow
^
Input file: <stdin>
Check file: /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c
-dump-input=help explains the following input dump.
Input was:
<<<<<<
            .
            .
            .
            9:  
           10: Cause: stack tag-mismatch 
           11: Address 0xffffc38ff8f0 is located in stack of thread T0 
           12: Thread: T0 0xeffe00002000 stack: [0xffffc3101000,0xffffc3901000) sz: 8388608 tls: [0xffff9037a700,0xffff9037b5a0) 
           13:  
           14: Potentially referenced stack objects: 
check:73'0                                          X error: no match found
           15: Cause: stack-buffer-overflow 
check:73'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:73'1     ?                             possible intended match
           16: 0xffffc38ff8f0 is located 281473962735616 bytes after a 2048-byte local variable zzz [0xfffffffffffff8f0,0x0000000000f0) in buggy /b/sanitizer-aarch64-linux/build/llvm-project/compiler-rt/test/hwasan/TestCases/stack-uas.c:44 
check:73'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           17:  
check:73'0     ~
           18:  
check:73'0     ~
           19:  
check:73'0     ~
           20: Memory tags around the buggy address (one tag corresponds to 16 bytes): 
check:73'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
>>>>>>
```

### PR DESCRIPTION
**Pull request by vitalybuka**
Existing code worked only for local, recorder FP, and the faulty address are the same 1 MiB page.

Now, instead of guessing FP, we guess variable address.
We need to try just two cases of addresses around of faulty one.

Fixes https://github.com/google/sanitizers/issues/1723

### CODE REVIEW

File: compiler-rt/lib/hwasan/hwasan_report.cpp [hunk 1]
```diff
@@ -230,33 +230,70 @@ static void PrintStackAllocations(const StackAllocationsRingBuffer *sa,
...
+      const char *whence;
+      const char *cause = nullptr;
+      uptr best_beg;
+
+      // Try two 1 MiB blocks options and pick nearest one.
+      for (uptr i = 0; i < 2; ++i, local_beg += kRecordFPModulus) {
+        uptr local_end = local_beg + local.size;
+        if (local_beg > local_end)
+          continue;  // This is a wraparound.
+        if (local_beg <= untagged_addr && untagged_addr < local_end) {
```
Comment (thurstond) [inline compiler-rt/lib/hwasan/hwasan_report.cpp:258]: The three if statements (`(local_beg <= untagged_addr && untagged_addr < local_end)`, `(untagged_addr >= local_end)`, `(untagged_addr < local_beg)`) seem mutually exclusive to me. If that is the case, would it be better to use 'if/else if' to make it clear to readers (and negligibly faster)?

**Review by thurstond — APPROVED** [review]

File: compiler-rt/lib/hwasan/hwasan_report.cpp (hunk 1 above)
Comment (fmayer) [reply compiler-rt/lib/hwasan/hwasan_report.cpp:258]: >  (and negligibly faster)

if you can figure it out, clang should be able to too.

File: compiler-rt/lib/hwasan/hwasan_report.cpp [hunk 2]
```diff
@@ -230,33 +230,70 @@ static void PrintStackAllocations(const StackAllocationsRingBuffer *sa,
...
-      // Guess top bits of local variable from the faulting address, because
-      // we only store bits 4-19 of FP (bits 0-3 are guaranteed to be zero).
-      uptr local_beg = (fp + local.frame_offset) |
-                       (untagged_addr & ~(uptr(kRecordFPModulus) - 1));
-      uptr local_end = local_beg + local.size;
+
+      // We only store bits 4-19 of FP (bits 0-3 are guaranteed to be zero).
+      // So we know only `FP % kRecordFPModulus`, and we can only calculate
+      // `local_beg % kRecordFPModulus`.
+      // Out of all possible `local_beg` we will only consider two candidates
```
Comment (fmayer) [inline compiler-rt/lib/hwasan/hwasan_report.cpp:237]: maybe state that 2 is an arbitrary number?

**Review by fmayer — APPROVED** [review]
