### PR TITLE
[RISCV] Fix matching bug in VLA shuffle lowering

### LINKED ISSUE #134126: [RISC-V] Miscompile on rv64gcv with -O3
Testcase:
```c
long a;
long c;
signed char d = 2;
char e;
unsigned f;
short j;
long long ac;
int i = 2320478;
_Bool l = 1;
_Bool m;
int n = 9;
int q = 18004875;
unsigned u[15][15][15];
long long w[5][15];
void g(int i, short j, _Bool l, _Bool m, int n, int q,
       unsigned u[][15][15], long long w[][15]) {
  if (n) {
    for (signed char x = 0; x < (char)q + 132; x += i - 90)
      for (signed y = 0; y < 14; y += ~50 + 54) {
        c = w[x][x];
        d *= l && u[x][y][y];
        e = u[x][x][y];
      }
  }
  f += a ? m : 0;
}
int main() {
  for (int x = 0; x < 15; ++x)
    for (int y = 0; y < 15; ++y)
      for (int z = 0; z < 15; ++z)
        u[x][y][z] = 807197787;
  g(i, j, l, m, n, q, u, w);
  ac = d;
  __builtin_printf("%llu\n", ac);
}
```

Commands
```
# riscv
$ /scratch/ewlu/daily-upstream-build/build-gcv/bin/clang -march=rv64gcv_zvl256b -flto -O3 ./red.c -o user-config.out -fsigned-char -fno-strict-aliasing -fwrapv
$ QEMU_CPU=rv64,vlen=256,rvv_ta_all_1s=true,rvv_ma_all_1s=true,v=true,vext_spec=v1.0,zve32f=true,zve64f=true timeout --verbose -k 0.1 4 /scratch/ewlu/daily-upstream-build/build-gcv/bin/qemu-riscv64 user-config.out 1
0

$ /scratch/ewlu/daily-upstream-build/build-gcv/bin/clang -march=rv64gcv_zvl256b -flto -O2 ./red.c -o user-config.out -fsigned-char -fno-strict-aliasing -fwrapv 
$ QEMU_CPU=rv64,vlen=256,rvv_ta_all_1s=true,rvv_ma_all_1s=true,v=true,vext_spec=v1.0,zve32f=true,zve64f=true timeout --verbose -k 0.1 4 /scratch/ewlu/daily-upstream-build/build-gcv/bin/qemu-riscv64 user-config.out 1
2

# x86
$ ./native.out
2
```

bisected to 25e43334a86804c77d460493e37b57274257461a as the first bad commit

Tried reducing testcase more by eliminating dead code but that causes the failure to disappear. Also at some point during manual reduction, -O2 also started to fail but now it's generating expected output. If anyone wants, I can provide the unreduced testcase with the -O2 failure as well.

Found via fuzzer.

### PR DESCRIPTION
**Pull request by preames**
Fix https://github.com/llvm/llvm-project/issues/134126.

The matching code was previous written as if we were mutating the indices to replace undef elements with preferred values, but the actual lowering code just took a prefix of the index vector.  This resulted in us using undef indices for lanes which should have been defined, resulting in incorrect codegen.

Longer term, we probably should rewrite the mask, but this seemed like an easier tactical fix.

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -5399,16 +5399,16 @@ static SDValue lowerDisjointIndicesShuffle(ShuffleVectorSDNode *SVN,
 /// Is this mask local (i.e. elements only move within their local span), and
 /// repeating (that is, the same rearrangement is being done within each span)?
 static bool isLocalRepeatingShuffle(ArrayRef<int> Mask, int Span) {
-  SmallVector<int> LowSpan(Span, -1);
+  // Require a prefix from the original mask until the consumer code
+  // is adjusted to rewrite the mask instead of just taking a prefix.
+  SmallVector<int> LowSpan(Mask.take_front(Span));
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:5404]: Nit, I think this can now be 
```suggestion
  ArrayRef<int> LowSpan = Mask.take_front(Span);
```

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 2]
```diff
@@ -5424,13 +5424,13 @@ static bool isLowSourceShuffle(ArrayRef<int> Mask, int Span) {
 /// span, and then repeats that same result across all remaining spans.  Note
 /// that this doesn't check if all the inputs come from a single span!
 static bool isSpanSplatShuffle(ArrayRef<int> Mask, int Span) {
-  SmallVector<int> LowSpan(Span, -1);
+  // Require a prefix from the original mask until the consumer code
+  // is adjusted to rewrite the mask instead of just taking a prefix.
+  SmallVector<int> LowSpan(Mask.take_front(Span));
```
Comment (lukel97) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:5429]: Same nit here, only worthwhile if you don't think we'll need the SmallVector again for the mask-rewriting patch
```suggestion
  ArrayRef<int> LowSpan = Mask.take_front(Span);
```

**Review by lukel97 — APPROVED** [review]
LGTM

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp (hunk 1 above)
Comment (preames) [reply llvm/lib/Target/RISCV/RISCVISelLowering.cpp]: I did this and then realized we could directly reference Mask removing LowSpan entirely.
