### PR TITLE
[LoopInterchange] Fix overflow in cost calculation

### LINKED ISSUE #104761: [LoopInterchange]  Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"
With options "-O3 --target=aarch64 func.cpp -mllvm -enable-loopinterchange" and this input:
```
unsigned int A[11][11][11] __attribute__((aligned(16)));
void a(int b) {
  for (int c;; c += b)
    for (long d = 0; d < -3ULL; d += 2ULL)
      A[c][d][d] = 0;
}
```

Loop-interchange runs in an assert:

```
llvm-project/llvm/include/llvm/ADT/APInt.h:1501: uint64_t llvm::APInt::getZExtValue() const: Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"' failed.
```

IR reproducer, compile this with "opt -passes=loop-interchange -S":

```
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

@A = local_unnamed_addr global [11 x [11 x [11 x i32]]] zeroinitializer, align 16

define void @_Z1ai(i32 noundef %b) local_unnamed_addr #0 {
entry:
  %0 = sext i32 %b to i64
  br label %for.cond

; Loop:
for.cond:                                         ; preds = %for.cond.cleanup, %entry
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond.cleanup ], [ 0, %entry ]
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  %indvars.iv.next = add nsw i64 %indvars.iv, %0
  br label %for.cond

for.body:                                         ; preds = %for.cond, %for.body
  %d.010 = phi i64 [ 0, %for.cond ], [ %add, %for.body ]
  %arrayidx3 = getelementptr inbounds [11 x [11 x [11 x i32]]], ptr @A, i64 0, i64 %indvars.iv, i64 %d.010, i64 %d.010
  store i32 0, ptr %arrayidx3, align 4
  %add = add nuw i64 %d.010, 2
  %cmp = icmp ult i64 %d.010, -5
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}
```

### PR DESCRIPTION
**Pull request by sjoerdmeijer**
If the iteration count is really large, e.g. UINT_MAX, then the cost calculation can overflows and trigger an assert. So saturate the cost to INT_MAX if this is the case (the cost value is kept in a signed integer).

This fixes #104761

### CODE REVIEW

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp [hunk 1]
```diff
@@ -338,8 +340,11 @@ CacheCostTy IndexedReference::computeRefCost(const Loop &L,
   assert(RefCost && "Expecting a valid RefCost");
 
   // Attempt to fold RefCost into a constant.
+  // CacheCostTy is a signed integer, but the tripcount value can be large
+  // and may not fit, so saturate/limit the value to the maximum signed
+  // integer value.
   if (auto ConstantCost = dyn_cast<SCEVConstant>(RefCost))
-    return ConstantCost->getValue()->getZExtValue();
+    return (CacheCostTy)ConstantCost->getValue()->getLimitedValue(~0ULL >> 1);
```
Comment (fhahn) [inline llvm/lib/Analysis/LoopCacheAnalysis.cpp:347]: If `CacheCostTy` is a regular integer type, using numeric_limits may be clearer?

```suggestion
    return (CacheCostTy)ConstantCost->getValue()->getLimitedValue(std::numeric_limits<CacheCostTy>::max());
```

**Review by fhahn — COMMENTED** [review]
Is it possible to test this more targeted via an analysis test in `llvm/test/Analysis/LoopCacheAnalysis/`?

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp [hunk 2]
```diff
@@ -712,7 +717,12 @@ CacheCost::computeLoopCacheCost(const Loop &L,
   CacheCostTy LoopCost = 0;
   for (const ReferenceGroupTy &RG : RefGroups) {
     CacheCostTy RefGroupCost = computeRefGroupCacheCost(RG, L);
-    LoopCost += RefGroupCost * TripCountsProduct;
+
+    // Saturate the cost to INT MAX if the value can overflow.
+    if (RefGroupCost > (std::numeric_limits<int64_t>::max() / TripCountsProduct))
+      LoopCost = std::numeric_limits<int64_t>::max();
+    else
+      LoopCost += RefGroupCost * TripCountsProduct;
```
Comment (madhur13490) [inline llvm/lib/Analysis/LoopCacheAnalysis.cpp:725]: Could use ternary operator to simplify

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll [hunk 3]
```diff
@@ -0,0 +1,44 @@
+; REQUIRES: asserts
+
+; RUN: opt < %s -passes=loop-interchange -S -debug 2>&1 | FileCheck %s
```
Comment (madhur13490) [inline llvm/test/Transforms/LoopInterchange/refcost-overflow.ll:3]: test with -cache-line-size too to bolster checks?

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+;   for (int c;; c += b)
+;     for (long d = 0; d < -3ULL; d += 2ULL)
+;       A[c][d][d] = 0;
+; }
+
+; CHECK:  Access is not consecutive: RefCost=922337203685477580700
+; CHECK:  Loop 'for.cond' has cost=9223372036854775807
+; CHECK:  TripCount=9223372036854775807
+; CHECK:  Access is not consecutive: RefCost=9223372036854775807
+
```
Comment (madhur13490) [inline llvm/test/Transforms/LoopInterchange/refcost-overflow.ll:18]: Want to check anything from the emitted IR?

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+
+target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
```
Comment (madhur13490) [inline llvm/test/Transforms/LoopInterchange/refcost-overflow.ll:20]: Is this required?

**Comment by sjoerdmeijer** [comment]
> Is it possible to test this more targeted via an analysis test in `llvm/test/Analysis/LoopCacheAnalysis/`?

Thanks for the suggestion, that worked, have moved it.

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp (hunk 2 above)
Comment (sjoerdmeijer) [reply llvm/lib/Analysis/LoopCacheAnalysis.cpp:727]: It didn't improve readability, in my opinion, so have left it like this.

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll (hunk 4 above)
Comment (sjoerdmeijer) [reply llvm/test/Transforms/LoopInterchange/refcost-overflow.ll]: It's a loop-cache-cost test now that prints its analysis. The cost that it prints is the interesting part that we want to check, so don't need to check the IR.

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp (hunk 2 above)
Comment (sjoerdmeijer) [reply llvm/lib/Analysis/LoopCacheAnalysis.cpp:727]: It didn't improve readability in my opinion, so have left it.

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll (hunk 3 above)
Comment (sjoerdmeijer) [reply llvm/test/Transforms/LoopInterchange/refcost-overflow.ll]: Don't think this is necessary.

File: llvm/test/Transforms/LoopInterchange/refcost-overflow.ll (hunk 4 above)
Comment (madhur13490) [reply llvm/test/Transforms/LoopInterchange/refcost-overflow.ll]: Then you want to -disable-output which you did!

**Comment by paulwalker-arm** [comment]
Would it make sense to use `InstructionCost` which already accounts for saturation?

**Comment by sjoerdmeijer** [comment]
> Would it make sense to use `InstructionCost` which already accounts for saturation?

Thanks for the suggestion, I think that would make a lot of sense, which might as simple as aliasing CacheCostTy to InstructionCost (it's just an int at the moment: `using CacheCostTy = int64_t;`). Will look into it.

**Comment by sjoerdmeijer** [comment]
Now using InstructionCost.

**Comment by sjoerdmeijer** [comment]
Friendly ping

**Comment by sebpop** [comment]
The change looks good to me.

File: llvm/include/llvm/Analysis/LoopCacheAnalysis.h [hunk 6]
```diff
@@ -31,7 +32,7 @@ class ScalarEvolution;
 class SCEV;
 class TargetTransformInfo;
 
-using CacheCostTy = int64_t;
+using CacheCostTy = InstructionCost;
```
Comment (fhahn) [inline llvm/include/llvm/Analysis/LoopCacheAnalysis.h:35]: This seems to now just obscure the concrete type?

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp [hunk 7]
```diff
@@ -338,14 +340,18 @@ CacheCostTy IndexedReference::computeRefCost(const Loop &L,
   assert(RefCost && "Expecting a valid RefCost");
 
   // Attempt to fold RefCost into a constant.
+  // CacheCostTy is a signed integer, but the tripcount value can be large
+  // and may not fit, so saturate/limit the value to the maximum signed
+  // integer value.
   if (auto ConstantCost = dyn_cast<SCEVConstant>(RefCost))
-    return ConstantCost->getValue()->getZExtValue();
+    return ConstantCost->getValue()->getLimitedValue(
```
Comment (fhahn) [inline llvm/lib/Analysis/LoopCacheAnalysis.cpp:347]: Is this still needed or sufficient to let wrapping handle by InstructionCost?

File: llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+@A = local_unnamed_addr global [11 x [11 x [11 x i32]]] zeroinitializer, align 16
+
+define void @foo(i32 noundef %b) {
+entry:
+  %0 = sext i32 %b to i64
+  br label %for.cond
+
+for.cond:
+  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond.cleanup ], [ 0, %entry ]
```
Comment (fhahn) [inline llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll:23]:
```suggestion
  %iv = phi i64 [ %indvars.iv.next, %for.cond.cleanup ], [ 0, %entry ]
```

File: llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+  br label %for.body
+
+for.cond.cleanup:
```
Comment (fhahn) [inline llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll:26]:
```suggestion
outer.latch:
```

can also move after inner loop to make things easier to read

File: llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+  %indvars.iv.next = add nsw i64 %indvars.iv, %0
+  br label %for.cond
+
+for.body:
```
Comment (fhahn) [inline llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll:30]:
```suggestion
inner.loop:
```

File: llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll [hunk 11]
```diff
@@ -0,0 +1,37 @@
...
+  %d.010 = phi i64 [ 0, %for.cond ], [ %add, %for.body ]
```
Comment (fhahn) [inline llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll:31]:
```suggestion
  %inner.iv = phi i64 [ 0, %for.cond ], [ %add, %for.body ]
```

File: llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+; CHECK: Loop 'for.body' has cost = 9223372036854775807
+
+@A = local_unnamed_addr global [11 x [11 x [11 x i32]]] zeroinitializer, align 16
+
+define void @foo(i32 noundef %b) {
+entry:
+  %0 = sext i32 %b to i64
+  br label %for.cond
+
+for.cond:
```
Comment (fhahn) [inline llvm/test/Analysis/LoopCacheAnalysis/interchange-refcost-overflow.ll:22]:
```suggestion
outer.header:
```

File: llvm/include/llvm/Analysis/LoopCacheAnalysis.h (hunk 6 above)
Comment (sjoerdmeijer) [reply llvm/include/llvm/Analysis/LoopCacheAnalysis.h:35]: Maybe. I personally don't mind the `CacheCostTy` alias here, think it is quite appropriately named. Thinking about it, maybe it's actually a better name than using InstructionCost here? But I don't have strong opinions so certainly don't mind a search/replace of CacheCostTy with InstructionCost assuming that's what you're suggesting, is that right @fhahn ?

File: llvm/lib/Analysis/LoopCacheAnalysis.cpp (hunk 7 above)
Comment (sjoerdmeijer) [reply llvm/lib/Analysis/LoopCacheAnalysis.cpp:347]: Yes, this is unfortunately still needed. Helper `getZExtValue()` returns an uint64_t and checks if the value fits in this number of bits.

**Comment by sjoerdmeijer** [comment]
Have addressed the comments about the test case.
As mentioned, I haven't renamed the type, but if you think it's better I am happy to rename things.

**Review by mshockwave — COMMENTED** [review]
Generally LGTM. Personally I don't have any strong opinion on using CacheCostTy instead of InstructionCost.

@fhahn do you have any other comment?

File: llvm/include/llvm/Analysis/LoopCacheAnalysis.h (hunk 6 above)
Comment (fhahn) [reply llvm/include/llvm/Analysis/LoopCacheAnalysis.h:35]: Personally I find it more inconvenient to hide the actual type behind another level of indirection, but changing it in this patch would unnecessarily increase the diff.

**Review by fhahn — APPROVED** [review]
LGTM, thanks!
