### PR TITLE
[clang] Improve nested name specifier AST representation

### LINKED ISSUE #43179: -ast-dump triggers assertion `!isa<ElaboratedType>(T) && "Elaborated type in nested-name-specifier"'
|  |  |
| --- | --- |
| Bugzilla Link | [43834](https://llvm.org/bz43834) |
| Resolution | WORKSFORME |
| Resolved on | Oct 29, 2021 07:01 |
| Version | trunk |
| OS | Linux |
| CC | @AaronBallman,@grandinj,@zygoloid |

## Extended Description 
At least with recent trunk ("clang version 10.0.0 (git@github.com:llvm/llvm-project 93e137f898296d142d056c892b10d40ca3c26f00)"):

> $ cat test.cc
> namespace N { template<typename> struct S1; }
> template<typename T> struct S2 {
>     using U = N::S1<typename N::S1<T>::t>;
>     S2(typename U::t);
> };
> template<typename T> S2(T) -> S2<void>;

> $ clang++ -Xclang -ast-dump -std=c++17 -fsyntax-only test.cc >/dev/null
> clang-10: /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:328: void clang::NestedNameSpecifier::print(llvm::raw_ostream&, const clang::PrintingPolicy&, bool) const: Assertion `!isa<ElaboratedType>(T) && "Elaborated type in nested-name-specifier"' failed.
> Stack dump:
> 0.	Program arguments: /data/sbergman/llvm/debug/inst/bin/clang-10 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -main-file-name test.cc -mrelocation-model static -mthread-model posix -mframe-pointer=all -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /data/sbergman/llvm/debug/inst/lib/clang/10.0.0 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/x86_64-redhat-linux -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/backward -internal-isystem /usr/local/include -internal-isystem /data/sbergman/llvm/debug/inst/lib/clang/10.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /data/sbergman/lo-clang2/core -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -ast-dump -faddrsig -x c++ test.cc 
> 1.	<eof> parser at end of file
>  #&#8203;0 0x00007f7b17f046fe llvm::sys::PrintStackTrace(llvm::raw_ostream&) /data/sbergman/github.com/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:544:22
>  #&#8203;1 0x00007f7b17f04791 PrintStackTraceSignalHandler(void*) /data/sbergman/github.com/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:605:1
>  #&#8203;2 0x00007f7b17f028e8 llvm::sys::RunSignalHandlers() /data/sbergman/github.com/llvm/llvm-project/llvm/lib/Support/Signals.cpp:68:20
>  #&#8203;3 0x00007f7b17f0414e SignalHandler(int) /data/sbergman/github.com/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:391:1
>  #&#8203;4 0x00007f7b170e3c60 __restore_rt (/lib64/libpthread.so.0+0x12c60)
>  #&#8203;5 0x00007f7b1462ce35 raise /usr/src/debug/glibc-2.29-32-g6d8eaf4a25/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
>  #&#8203;6 0x00007f7b14617895 abort /usr/src/debug/glibc-2.29-32-g6d8eaf4a25/stdlib/abort.c:81:7
>  #&#8203;7 0x00007f7b14617769 _nl_load_domain.cold /usr/src/debug/glibc-2.29-32-g6d8eaf4a25/intl/loadmsgcat.c:1177:9
>  #&#8203;8 0x00007f7b14625566 (/lib64/libc.so.6+0x30566)
>  #&#8203;9 0x00007f7b12492f69 clang::NestedNameSpecifier::print(llvm::raw_ostream&, clang::PrintingPolicy const&, bool) const (.localalias) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp:328:5
> #&#8203;10 0x00007f7b1258ee46 (anonymous namespace)::TypePrinter::printDependentNameBefore(clang::DependentNameType const*, llvm::raw_ostream&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:1367:37
> #&#8203;11 0x00007f7b1258a09b (anonymous namespace)::TypePrinter::printBefore(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) /data/sbergman/llvm/debug/build/tools/clang/include/clang/AST/TypeNodes.inc:35:1
> #&#8203;12 0x00007f7b12589ad6 (anonymous namespace)::TypePrinter::print(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&, llvm::StringRef) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:186:9
> #&#8203;13 0x00007f7b12589a56 (anonymous namespace)::TypePrinter::print(clang::QualType, llvm::raw_ostream&, llvm::StringRef) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:174:1
> #&#8203;14 0x00007f7b1258ccb1 (anonymous namespace)::TypePrinter::printFunctionProtoAfter(clang::FunctionProtoType const*, llvm::raw_ostream&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:791:5
> #&#8203;15 0x00007f7b1258aa61 (anonymous namespace)::TypePrinter::printAfter(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&) /data/sbergman/llvm/debug/build/tools/clang/include/clang/AST/TypeNodes.inc:44:1
> #&#8203;16 0x00007f7b12589b04 (anonymous namespace)::TypePrinter::print(clang::Type const*, clang::Qualifiers, llvm::raw_ostream&, llvm::StringRef) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:183:70
> #&#8203;17 0x00007f7b12590838 clang::QualType::getAsStringInternal(clang::Type const*, clang::Qualifiers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, clang::PrintingPolicy const&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:1906:3
> #&#8203;18 0x00007f7b125905fc clang::QualType::getAsString[abi:cxx11](clang::Type const*, clang::Qualifiers, clang::PrintingPolicy const&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TypePrinter.cpp:1877:10
> #&#8203;19 0x00007f7b12462f17 clang::QualType::getAsString[abi:cxx11](clang::SplitQualType, clang::PrintingPolicy const&) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/Type.h:982:3
> #&#8203;20 0x00007f7b1253957d clang::TextNodeDumper::dumpBareType(clang::QualType, bool) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TextNodeDumper.cpp:390:58
> #&#8203;21 0x00007f7b125396d4 clang::TextNodeDumper::dumpType(clang::QualType) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TextNodeDumper.cpp:403:1
> #&#8203;22 0x00007f7b1253d831 clang::TextNodeDumper::VisitFunctionDecl(clang::FunctionDecl const*) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TextNodeDumper.cpp:1274:39
> #&#8203;23 0x00007f7b1255944f clang::declvisitor::Base<llvm::make_const_ptr, clang::TextNodeDumper, void>::VisitCXXDeductionGuideDecl(clang::CXXDeductionGuideDecl const*) /data/sbergman/llvm/debug/build/tools/clang/include/clang/AST/DeclNodes.inc:399:1
> #&#8203;24 0x00007f7b12553e80 clang::declvisitor::Base<llvm::make_const_ptr, clang::TextNodeDumper, void>::Visit(clang::Decl const*) /data/sbergman/llvm/debug/build/tools/clang/include/clang/AST/DeclNodes.inc:399:1
> #&#8203;25 0x00007f7b12538c30 clang::TextNodeDumper::Visit(clang::Decl const*) /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/TextNodeDumper.cpp:277:1
> #&#8203;26 0x00007f7b11fe5869 clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()::operator()() const /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:78:32
> #&#8203;27 0x00007f7b11fef9ac void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:103:14
> #&#8203;28 0x00007f7b1200a153 std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /usr/include/c++/9/bits/std_function.h:302:7
> #&#8203;29 0x00007f7b11fefdae std::function<void (bool)>::operator()(bool) const /usr/include/c++/9/bits/std_function.h:690:71
> #&#8203;30 0x00007f7b11fef9ec void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)::operator()(bool) const /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:72:27
> #&#8203;31 0x00007f7b1200a153 std::_Function_handler<void (bool), void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper)::'lambda'(bool)>::_M_invoke(std::_Any_data const&, bool&&) /usr/include/c++/9/bits/std_function.h:302:7
> #&#8203;32 0x00007f7b11fefdae std::function<void (bool)>::operator()(bool) const /usr/include/c++/9/bits/std_function.h:690:71
> #&#8203;33 0x00007f7b11fefcae void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:116:33
> #&#8203;34 0x00007f7b11fe84ec void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(clang::ASTDumper) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:49:3
> #&#8203;35 0x00007f7b11fe5a0c clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:98:3
> #&#8203;36 0x00007f7b11fe8489 clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::dumpDeclContext(clang::DeclContext const*) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:230:5
> #&#8203;37 0x00007f7b11fe59c0 clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()::operator()() const /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:95:11
> #&#8203;38 0x00007f7b11fefb24 void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(llvm::StringRef, clang::ASTDumper) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:59:28
> #&#8203;39 0x00007f7b11fe84ec void clang::TextTreeStructure::AddChild<clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*)::'lambda'()>(clang::ASTDumper) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/TextNodeDumper.h:49:3
> #&#8203;40 0x00007f7b11fe5a0c clang::ASTNodeTraverser<clang::ASTDumper, clang::TextNodeDumper>::Visit(clang::Decl const*) /data/sbergman/github.com/llvm/llvm-project/clang/include/clang/AST/ASTNodeTraverser.h:98:3
> #&#8203;41 0x00007f7b11fdf118 clang::Decl::dump(llvm::raw_ostream&, bool, clang::ASTDumpOutputFormat) const /data/sbergman/github.com/llvm/llvm-project/clang/lib/AST/ASTDumper.cpp:193:77
> #&#8203;42 0x00007f7b155105cd (anonymous namespace)::ASTPrinter::print(clang::Decl*) /data/sbergman/github.com/llvm/llvm-project/clang/lib/Frontend/ASTConsumers.cpp:96:5
> #&#8203;43 0x00007f7b155101c9 (anonymous namespace)::ASTPrinter::HandleTranslationUnit(clang::ASTContext&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/Frontend/ASTConsumers.cpp:48:23
> #&#8203;44 0x00007f7b106ed7b0 clang::ParseAST(clang::Sema&, bool, bool) /data/sbergman/github.com/llvm/llvm-project/clang/lib/Parse/ParseAST.cpp:178:14
> #&#8203;45 0x00007f7b156ce653 clang::ASTFrontendAction::ExecuteAction() /data/sbergman/github.com/llvm/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1042:11
> #&#8203;46 0x00007f7b156cdfbf clang::FrontendAction::Execute() /data/sbergman/github.com/llvm/llvm-project/clang/lib/Frontend/FrontendAction.cpp:939:38
> #&#8203;47 0x00007f7b15654689 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /data/sbergman/github.com/llvm/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:964:42
> #&#8203;48 0x00007f7b1518e719 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /data/sbergman/github.com/llvm/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:290:38
> #&#8203;49 0x0000000000269729 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /data/sbergman/github.com/llvm/llvm-project/clang/tools/driver/cc1_main.cpp:250:40
> #&#8203;50 0x000000000025f64d ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) /data/sbergman/github.com/llvm/llvm-project/clang/tools/driver/driver.cpp:309:64
> #&#8203;51 0x000000000025fcad main /data/sbergman/github.com/llvm/llvm-project/clang/tools/driver/driver.cpp:382:26
> #&#8203;52 0x00007f7b14618f43 __libc_start_main /usr/src/debug/glibc-2.29-32-g6d8eaf4a25/csu/../csu/libc-start.c:342:3
> #&#8203;53 0x000000000025e02e _start (/data/sbergman/llvm/debug/inst/bin/clang-10+0x25e02e)

### LINKED ISSUE #68670: [clang-extdef-mapping] assertion failed on ElaboratedType NestedNameSpecifier
Testcase:
```cpp
// test.cpp

template <bool C, typename T>
struct cond {
  typedef T Ty;
};

template <typename _T>
class M;

template <typename T,
          typename U =
              typename cond<T::S, int>::Ty>
class R;

template <typename T>
class B {
  void f(R<const M<T>> arg);
};

template <typename T>
void B<T>::f(R<const M<T>> arg) {}
```

Run with `clang-extdef-mapping test.cpp`, crash dump:
```
clang-extdef-mapping: /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/NestedNameSpecifier.cpp:309: void clang::NestedNameSpecifier::print(llvm::raw_ostream &, const clang::PrintingPolicy &, bool) const: Assertion `!isa<ElaboratedType>(T) && "Elaborated type in nested-name-specifier"' failed.
 #0 0x00007f01f0e0706a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/xxxxx/Sources/llvm-project-main/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x00007f01f0e0726b PrintStackTraceSignalHandler(void*) /home/xxxxx/Sources/llvm-project-main/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x00007f01f0e05586 llvm::sys::RunSignalHandlers() /home/xxxxx/Sources/llvm-project-main/llvm/lib/Support/Signals.cpp:105:5
 #3 0x00007f01f0e07a85 SignalHandler(int) /home/xxxxx/Sources/llvm-project-main/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f01f085afd0 (/lib/x86_64-linux-gnu/libc.so.6+0x3bfd0)
 #5 0x00007f01f08a9d3c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x00007f01f085af32 raise ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00007f01f0845472 abort ./stdlib/abort.c:81:7
 #8 0x00007f01f0845395 _nl_load_domain ./intl/loadmsgcat.c:1177:9
 #9 0x00007f01f0853e32 (/lib/x86_64-linux-gnu/libc.so.6+0x34e32)
#10 0x00007f01f2ad54e7 clang::NestedNameSpecifier::print(llvm::raw_ostream&, clang::PrintingPolicy const&, bool) const /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/NestedNameSpecifier.cpp:311:50
#11 0x00007f01f2ba91b6 (anonymous namespace)::StmtPrinter::VisitDependentScopeDeclRefExpr(clang::DependentScopeDeclRefExpr*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:1184:7
#12 0x00007f01f2ba1c51 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::StmtPrinter, void>::Visit(clang::Stmt*) /home/xxxxx/Sources/llvm-project-main/build/tools/clang/include/clang/AST/StmtNodes.inc:1127:1
#13 0x00007f01f2ba0977 (anonymous namespace)::StmtPrinter::Visit(clang::Stmt*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:151:5
#14 0x00007f01f2badb40 (anonymous namespace)::StmtPrinter::PrintExpr(clang::Expr*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:136:9
#15 0x00007f01f2ba89bd (anonymous namespace)::StmtPrinter::VisitImplicitCastExpr(clang::ImplicitCastExpr*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:1642:1
#16 0x00007f01f2ba1b9d clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::StmtPrinter, void>::Visit(clang::Stmt*) /home/xxxxx/Sources/llvm-project-main/build/tools/clang/include/clang/AST/StmtNodes.inc:1055:1
#17 0x00007f01f2ba0977 (anonymous namespace)::StmtPrinter::Visit(clang::Stmt*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:151:5
#18 0x00007f01f2ba086b clang::Stmt::printPretty(llvm::raw_ostream&, clang::PrinterHelper*, clang::PrintingPolicy const&, unsigned int, llvm::StringRef, clang::ASTContext const*) const /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/StmtPrinter.cpp:2764:1
#19 0x00007f01f2bc9c26 clang::TemplateArgument::print(clang::PrintingPolicy const&, llvm::raw_ostream&, bool) const /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/TemplateBase.cpp:462:5
#20 0x00007f01f2c5d424 printArgument(clang::TemplateArgument const&, clang::PrintingPolicy const&, llvm::raw_ostream&, bool) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/TypePrinter.cpp:2011:1
#21 0x00007f01f2c53791 void printTo<clang::TemplateArgument>(llvm::raw_ostream&, llvm::ArrayRef<clang::TemplateArgument>, clang::PrintingPolicy const&, clang::TemplateParameterList const*, bool, unsigned int) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/TypePrinter.cpp:2226:33
#22 0x00007f01f2c533af clang::printTemplateArgumentList(llvm::raw_ostream&, llvm::ArrayRef<clang::TemplateArgument>, clang::PrintingPolicy const&, clang::TemplateParameterList const*) /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/TypePrinter.cpp:2267:1
#23 0x00007f01f2ad5576 clang::NestedNameSpecifier::print(llvm::raw_ostream&, clang::PrintingPolicy const&, bool) const /home/xxxxx/Sources/llvm-project-main/clang/lib/AST/NestedNameSpecifier.cpp:320:5
#24 0x00007f01e8a86268 printQualifier(llvm::raw_ostream&, clang::ASTContext&, clang::NestedNameSpecifier*) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:639:1
#25 0x00007f01e8a8549b (anonymous namespace)::USRGenerator::VisitType(clang::QualType) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:912:7
#26 0x00007f01e8a8616f (anonymous namespace)::USRGenerator::VisitTemplateArgument(clang::TemplateArgument const&) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:1030:5
#27 0x00007f01e8a85405 (anonymous namespace)::USRGenerator::VisitType(clang::QualType) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:906:28
#28 0x00007f01e8a88053 (anonymous namespace)::USRGenerator::VisitFunctionDecl(clang::FunctionDecl const*) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:269:17
#29 0x00007f01e8a8825d clang::declvisitor::Base<llvm::make_const_ptr, (anonymous namespace)::USRGenerator, void>::VisitCXXMethodDecl(clang::CXXMethodDecl const*) /home/xxxxx/Sources/llvm-project-main/build/tools/clang/include/clang/AST/DeclNodes.inc:443:1
#30 0x00007f01e8a7f711 clang::declvisitor::Base<llvm::make_const_ptr, (anonymous namespace)::USRGenerator, void>::Visit(clang::Decl const*) /home/xxxxx/Sources/llvm-project-main/build/tools/clang/include/clang/AST/DeclNodes.inc:443:1
#31 0x00007f01e8a7f221 clang::index::generateUSRForDecl(clang::Decl const*, llvm::SmallVectorImpl<char>&) /home/xxxxx/Sources/llvm-project-main/clang/lib/Index/USRGeneration.cpp:1160:13
#32 0x00007f01f4e8c670 clang::cross_tu::CrossTranslationUnitContext::getLookupName[abi:cxx11](clang::NamedDecl const*) /home/xxxxx/Sources/llvm-project-main/clang/lib/CrossTU/CrossTranslationUnit.cpp:247:8
#33 0x0000555bf8e2030e MapExtDefNamesConsumer::addIfInMain(clang::DeclaratorDecl const*, clang::SourceLocation) /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:89:8
#34 0x0000555bf8e20172 MapExtDefNamesConsumer::handleDecl(clang::Decl const*) /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:72:23
#35 0x0000555bf8e202ba MapExtDefNamesConsumer::handleDecl(clang::Decl const*) /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:81:24
#36 0x0000555bf8e24d5d MapExtDefNamesConsumer::HandleTranslationUnit(clang::ASTContext&) /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:54:3
#37 0x00007f01e70eb253 clang::ParseAST(clang::Sema&, bool, bool) /home/xxxxx/Sources/llvm-project-main/clang/lib/Parse/ParseAST.cpp:183:12
#38 0x00007f01f3b8d281 clang::ASTFrontendAction::ExecuteAction() /home/xxxxx/Sources/llvm-project-main/clang/lib/Frontend/FrontendAction.cpp:1186:1
#39 0x00007f01f3b8cc7c clang::FrontendAction::Execute() /home/xxxxx/Sources/llvm-project-main/clang/lib/Frontend/FrontendAction.cpp:1074:7
#40 0x00007f01f3a88968 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/xxxxx/Sources/llvm-project-main/clang/lib/Frontend/CompilerInstance.cpp:1054:23
#41 0x00007f01f3fe5983 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) /home/xxxxx/Sources/llvm-project-main/clang/lib/Tooling/Tooling.cpp:467:14
#42 0x00007f01f3fe5821 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) /home/xxxxx/Sources/llvm-project-main/clang/lib/Tooling/Tooling.cpp:442:18
#43 0x00007f01f3fe48bd clang::tooling::ToolInvocation::run() /home/xxxxx/Sources/llvm-project-main/clang/lib/Tooling/Tooling.cpp:427:3
#44 0x00007f01f3fe6b1e clang::tooling::ClangTool::run(clang::tooling::ToolAction*) /home/xxxxx/Sources/llvm-project-main/clang/lib/Tooling/Tooling.cpp:619:11
#45 0x0000555bf8e20ac6 HandleFiles(llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, clang::tooling::CompilationDatabase&) /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:193:5
#46 0x0000555bf8e208af main /home/xxxxx/Sources/llvm-project-main/clang/tools/clang-extdef-mapping/ClangExtDefMapGen.cpp:222:3
#47 0x00007f01f08461ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#48 0x00007f01f0846285 call_init ./csu/../csu/libc-start.c:128:20
#49 0x00007f01f0846285 __libc_start_main ./csu/../csu/libc-start.c:347:5
#50 0x0000555bf8e20001 _start (/home/xxxxx/Sources/llvm-project-main/build/bin/clang-extdef-mapping+0x18001)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/xxxxx/Sources/llvm-project-main/build/bin/clang-extdef-mapping test.cpp --
1.	<eof> parser at end of file
```

### LINKED ISSUE #92757: Assertion `!isa<ElaboratedType>(T) && "Elaborated type in nested-name-specifier"'
I tried the following code with clang (assertions):

<details><summary>Details</summary>
<p>

```c++
namespace std {
typedef long unsigned int size_t;
typedef decltype(nullptr) nullptr_t;

template <typename _Tp> class reference_wrapper;
template <typename _Tp, _Tp __v> struct integral_constant {
  static constexpr _Tp value = __v;
  using value_type = _Tp;
  using type = integral_constant<_Tp, __v>;
  constexpr operator value_type() const noexcept { return value; }
  constexpr value_type operator()() const noexcept { return value; }
};
template <bool __v> using __bool_constant = integral_constant<bool, __v>;
using true_type = __bool_constant<true>;
using false_type = __bool_constant<false>;
template <bool, typename _Tp = void> struct enable_if {};
template <typename _Tp> struct enable_if<true, _Tp> {
  using type = _Tp;
};
template <typename _Tp, typename _Up = _Tp &&> _Up __declval(int);
template <typename _Tp> _Tp __declval(long);
template <typename _Tp> auto declval() noexcept -> decltype(__declval<_Tp>(0));
template <bool _Cond, typename _Tp = void>
using enable_if_t = typename enable_if<_Cond, _Tp>::type;
} // namespace std

template <class T> struct type {};
template <typename Iterator> class fragmented_memory_input_stream {};
template <typename Iterator> class memory_input_stream {
public:
  using fragmented_type = fragmented_memory_input_stream<Iterator>;
  fragmented_type _fragmented;

public:
  template <typename StreamVisitor>
  decltype(auto) with_stream(StreamVisitor &&visitor) const {
    return visitor(_fragmented);
  }
  using has_with_stream = std::true_type;
};
template <typename Stream, typename StreamVisitor,
          typename = std::enable_if_t<Stream::has_with_stream::value>>
decltype(auto) with_serialized_stream(Stream &stream, StreamVisitor &&visitor) {
  return stream.with_stream(visitor);
}
template <typename Stream, typename StreamVisitor,
          typename = std::enable_if_t<!Stream::has_with_stream::value>,
          typename = void>
decltype(auto) with_serialized_stream(Stream &stream, StreamVisitor &&visitor);
class fragment_iterator {};
template <typename T> struct serializer;
template <typename T, typename Input> T deserialize(Input &in, type<T> t);
using input_stream = memory_input_stream<fragment_iterator>;
struct mutation_partition_view {};
struct canonical_mutation_view {
  input_stream v;
  auto partition() const {
    return with_serialized_stream(
        v,
        [this](
            auto &v) -> decltype(deserialize(std::declval<input_stream &>(),
                                             type<mutation_partition_view>())) {
          auto in = v;
          return deserialize(in, type<mutation_partition_view>());
        });
  }
};
```

</p>
</details> 

I got the following assertion:

```
1.	schema_tables.cpp:65:10: current parser token ')'
2.	schema_tables.cpp:55:1: parsing struct/union/class body 'canonical_mutation_view'
3.	schema_tables.cpp:57:26: parsing function body 'canonical_mutation_view::partition'
4.	schema_tables.cpp:57:26: in compound statement ('{}')
...
#10 0x00007f5fa1721560 llvm::PointerIntPairInfo<void*, 1u, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>>::updatePointer(long, void*) /home/dianqk/llvm/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:202:5
#11 0x00007f5fa1721560 llvm::PointerIntPair<void*, 1u, int, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>, llvm::PointerIntPairInfo<void*, 1u, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>>>::setPointerAndInt(void*, int) & /home/dianqk/llvm/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:111:29
#12 0x00007f5fa1721560 llvm::PointerIntPair<void*, 1u, int, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>, llvm::PointerIntPairInfo<void*, 1u, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>>>::PointerIntPair(void*, int) /home/dianqk/llvm/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:89:5
#13 0x00007f5fa1721560 llvm::pointer_union_detail::PointerUnionMembers<llvm::PointerUnion<clang::Type const*, clang::ExtQuals const*>, llvm::PointerIntPair<void*, 1u, int, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>, llvm::PointerIntPairInfo<void*, 1u, llvm::pointer_union_detail::PointerUnionUIntTraits<clang::Type const*, clang::ExtQuals const*>>>, 0, clang::Type const*, clang::ExtQuals const*>::PointerUnionMembers(clang::Type const*) /home/dianqk/llvm/llvm-project/llvm/include/llvm/ADT/PointerUnion.h:77:16
```

This code is from https://github.com/llvm/llvm-project/issues/91312#issuecomment-2116404306.

The output from `creduce`:

```c++
namespace std {
      template <typename _Tp, _Tp __v> struct integral_constant {
       static constexpr _Tp value = __v;
     };
      template <bool __v> using __bool_constant = integral_constant<bool, __v>;
      using true_type = __bool_constant<true>;
      template <bool, typename _Tp = void> struct enable_if {
    };
      template <typename _Tp> _Tp __declval(long);
      template <typename _Tp> auto declval() noexcept -> decltype(__declval<_Tp>(0));
      template <bool _Cond, typename _Tp = void> using enable_if_t = typename enable_if<_Cond, _Tp>::type;
        namespace seastar {
      template <class T> struct type {
   };
      template <typename Iterator> class memory_input_stream {
    public:   using fragmented_type = fragmented_memory_input_stream<Iterator>;
      using has_with_stream = std::true_type;
    };
      template <typename Stream, typename StreamVisitor,           typename = std::enable_if_t<Stream::has_with_stream::value>> decltype(auto) with_serialized_stream(Stream &stream, StreamVisitor &&visitor) {
    }
        class fragment_iterator {
      namespace ser {
    template <typename T, typename Input> T deserialize(Input &in, seastar::type<T> t);
      using input_stream = seastar::memory_input_stream<fragment_iterator>;
     struct mutation_partition_view {
     input_stream v;
     auto partition() const {
      return seastar::with_serialized_stream(         v,         [this](auto &v) -> decltype(ser::deserialize(                             std::declval<input_stream &>(),                             seastar::type<mutation_partition_view>())) {
         }
 );
```

godbolt 1: https://llvm.godbolt.org/z/6sd8he1Me
godbolt 2: https://llvm.godbolt.org/z/jqfnKz47d

### LINKED ISSUE #136624: Incorrect name qualification in AST / diagnostics for alias CTAD
Consider this example: https://compiler-explorer.com/z/bGqdsa3qc

```C++
template<typename U> struct A {
  U t;
};

template<typename V> A(V) -> A<V>;

namespace foo {
  template<class Y> using Alias = A<Y>;
}

foo::Alias t = 0;
```

Produces:
```
error: no viable conversion from 'int' to 'foo::A<int>' (aka 'A<int>')
```

Note that the `foo::` qualification is applied to Alias in the source code, which is in that namespace, but
on the AST (and consequently in the diagnostic) it gets applied to `A` , where it  cannot be found.

The problem here is many fold:
1) We have an elaborated type including `foo::` over the deduced template specialization (DTST), which names `foo::Alias`.
2) However, when printing a DTST which has already been deduced, we choose to print it as the deduced type instead, probably for diagnostics reasons (although this is wrong for -ast-print, and we don't control this with a policy).
3) For alias CTAD, we don't build a guide which actually contains the alias template specialization `Alias<int>`, instead the guide contains `A<int>`.

I see  a couple of solutions:
* If we fix 3, then this would print as intended: `'foo::Alias<int>' (aka 'A<int>')`
* We could stop doing 2, then this would print as `'foo::Alias' (aka 'A<int>')`.
  The first type does not include much information, as 2) probably intended to avoid, but it is correctly qualified, and then the 'aka' gives the missing information.

### PR DESCRIPTION
**Pull request by mizvekov**
This is a major change on how we represent nested name qualifications in the AST.

* The nested name specifier itself and how it's stored is changed. The prefixes for types are handled within the type hierarchy, which makes canonicalization for them super cheap, no memory allocation required. Also translating a type into nested name specifier form becomes a no-op. An identifier is stored as a DependentNameType. The nested name specifier gains a lightweight handle class, to be used instead of passing around pointers, which is similar to what is implemented for TemplateName. There is still one free bit available, and this handle can be used within a PointerUnion and PointerIntPair, which should keep bit-packing aficionados happy.
* The ElaboratedType node is removed, all type nodes in which it could previously apply to can now store the elaborated keyword and name qualifier, tail allocating when present.
* TagTypes can now point to the exact declaration found when producing these, as opposed to the previous situation of there only existing one TagType per entity. This increases the amount of type sugar retained, and can have several applications, for example in tracking module ownership, and other tools which care about source file origins, such as IWYU. These TagTypes are lazily allocated, in order to limit the increase in AST size.

This patch offers a great performance benefit.

It greatly improves compilation time for [stdexec](https://github.com/NVIDIA/stdexec). For one datapoint, for `test_on2.cpp` in that project, which is the slowest compiling test, this patch improves `-c` compilation time by about 7.2%, with the `-fsyntax-only` improvement being at ~12%.

This has great results on compile-time-tracker as well:
image

This patch also further enables other optimziations in the future, and will reduce the performance impact of template specialization resugaring when that lands.

It has some other miscelaneous drive-by fixes.

About the review: Yes the patch is huge, sorry about that. Part of the reason is that I started by the nested name specifier part, before the ElaboratedType part, but that had a huge performance downside, as ElaboratedType is a big performance hog. I didn't have the steam to go back and change the patch after the fact.

There is also a lot of internal API changes, and it made sense to remove ElaboratedType in one go, versus removing it from one type at a time, as that would present much more churn to the users. Also, the nested name specifier having a different API avoids missing changes related to how prefixes work now, which could make existing code compile but not work.

How to review: The important changes are all in `clang/include/clang/AST` and `clang/lib/AST`, with also important changes in `clang/lib/Sema/TreeTransform.h`.

The rest and bulk of the changes are mostly consequences of the changes in API.

PS: TagType::getDecl is renamed to `getOriginalDecl` in this patch, just for easier to rebasing. I plan to rename it back after this lands.

Fixes #136624
Fixes https://github.com/llvm/llvm-project/issues/43179
Fixes https://github.com/llvm/llvm-project/issues/68670
Fixes https://github.com/llvm/llvm-project/issues/92757

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
ExtractAPI changes look good.

**Review by erichkeane — COMMENTED** [review]
Is there ANYTHING we can do to split this up?  This is so huge that github is refusing to load half the changes.

**Comment by mizvekov** [comment]
> Is there ANYTHING we can do to split this up? This is so huge that github is refusing to load half the changes.

I broke the commit down into others, now the first commit only has the AST and TreeTransform changes.

**Comment by erichkeane** [comment]
> > Is there ANYTHING we can do to split this up? This is so huge that github is refusing to load half the changes.
> 
> I broke the commit down into others, now the first commit only has the AST and TreeTransform changes.

Can we split them up in reviews/do reviews as a stack if necessary? reviewing each individual 'commit' in the same review is also really difficult.

**Comment by mizvekov** [comment]
> Can we split them up in reviews/do reviews as a stack if necessary? reviewing each individual 'commit' in the same review is also really difficult.

Possible, although it would be difficult to split this in a way where each commit works individually.
If we accept that we will have to rely on the top of the stack being rebased in order to get testing feedback, and that this will have to be committed all in one go, I can do it.

**Comment by erichkeane** [comment]
> > Can we split them up in reviews/do reviews as a stack if necessary? reviewing each individual 'commit' in the same review is also really difficult.
> 
> Possible, although it would be difficult to split this in a way where each commit works individually. If we accept that we will have to rely on the top of the stack being rebased in order to get testing feedback, and that this will have to be committed all in one go, I can do it.

I'm definitely OK with accepting all of that, and would very much appreciate it.  Note that Graphite is a tool others have used to manage patch-stacks that can do a lot of that for you, if it makes it easier.

**Comment by mizvekov** [comment]
> I'm definitely OK with accepting all of that, and would very much appreciate it.

Done.

File: clang/include/clang/AST/ASTContext.h [hunk 1]
```diff
@@ -1749,34 +1748,51 @@ class ASTContext : public RefCountedBase<ASTContext> {
...
-    assert(Decl && "Passed null for Decl param");
-    if (Decl->TypeForDecl) return QualType(Decl->TypeForDecl, 0);
-
-    if (PrevDecl) {
-      assert(PrevDecl->TypeForDecl && "previous decl has no TypeForDecl");
-      Decl->TypeForDecl = PrevDecl->TypeForDecl;
-      return QualType(PrevDecl->TypeForDecl, 0);
-    }
+  QualType getTypeDeclType(const TypeDecl *Decl) const;
+  QualType getTypeDeclType(const TagDecl *) const = delete;
```
Comment (erichkeane) [inline clang/include/clang/AST/ASTContext.h:1778]: Can we do some sort of comments to explain why these are deleted, so that when someone runs into them, they can see what they should be using  instead?

File: clang/include/clang/AST/NestedNameSpecifierBase.h [hunk 2]
```diff
@@ -0,0 +1,585 @@
...
+
+    /// A type, stored as a Type*.
+    Type,
+
+    /// A namespace-like entity, stored as a NamespaceBaseDecl*.
+    Namespace,
+
+    /// Microsoft's '__super' specifier, stored as a CXXRecordDecl* of
+    /// the class it appeared in.
+    Super,
```
Comment (erichkeane) [inline clang/include/clang/AST/NestedNameSpecifierBase.h]: "While we are here" :)  It would be REALLY nice if instead of `Super` we spelled this as something more obvious what it is.  Something like`MicrosoftSuper`?  `Super` hits too many other language-keyword-type things for me, and it isn't particularly clear when reading other stuff in this patch that it was what this is.

File: clang/lib/AST/ASTContext.cpp [hunk 3]
```diff
@@ -3413,7 +3417,10 @@ static void encodeTypeForFunctionPointerAuth(const ASTContext &Ctx,
     //   type, or an unsigned integer type.
     //
     // So we have to treat enum types as integers.
-    QualType UnderlyingType = cast<EnumType>(T)->getDecl()->getIntegerType();
+    QualType UnderlyingType = cast<EnumType>(T)
+                                  ->getOriginalDecl()
```
Comment (erichkeane) [inline clang/lib/AST/ASTContext.cpp:3426]: This has shown up a few times so far... could this use a helper of some sort (getOriginalDecl->getDefinitionOrSelf)?

**Comment by rjmccall** [comment]
You should at minimum be able to layer the `NestedNameSpecifier` change on top of the `TagType` change. I can't see why that wouldn't work.

1. Add the structure for sugary `TagType`s.
2. Replace `ElaboratedType` with sugary `TagType`s.
3. Change the representation of NNS.

File: clang/lib/AST/ByteCode/Program.cpp [hunk 4]
```diff
@@ -326,7 +326,7 @@ Record *Program::getOrCreateRecord(const RecordDecl *RD) {
       const auto *RT = Spec.getType()->getAs<RecordType>();
       if (!RT)
         return nullptr;
-      const RecordDecl *BD = RT->getDecl();
+      const RecordDecl *BD = RT->getOriginalDecl()->getDefinitionOrSelf();
```
Comment (erichkeane) [inline clang/lib/AST/ByteCode/Program.cpp:328]: I'm pretty convinced by now, `getOriginalDefinitionOrSelf` would pay HUGE dividends in this patch :)

**Review by erichkeane — COMMENTED** [review]
For obvious reasons, I wasn't able to make even a reasonably thorough review here, but I came across a few things that seemed like good ideas.  All 4 of the patches are STILL huge.

IMO, unless this can be more bite-sized changes, I don't know how to proceed here.

File: clang/lib/AST/ByteCode/Program.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/AST/ByteCode/Program.cpp:328]: Yeah, the problem is that it would be really annoying to provide an inline definition of this helper, since it has to be defined with `Type.h`, but the definition depends on `Decl` bits which in turn depend on `Type.h`.

Not making them inline has a noticeable perf hit.

I had the same problem with providing inline implementations of a bunch of NestedNameSpecifier members.
What I did there, was to split this into `NestedNameSpecifierBase.h` and `NestedNameSpecifier.h`, the latter containing only inline definitions, and the former being included in places which would otherwise introduce a circular dependency.

I think making this change in `Type.h` for this patch would have been much larger though, so I'd propose doing this in a follow up.

Another possibility is providing these as inline free-function helpers, defined in `Decl.h`, but I think this looks uglier (even though we use this pattern elsewhere).

**Comment by mizvekov** [comment]
> You should at minimum be able to layer the `NestedNameSpecifier` change on top of the `TagType` change. I can't see why that wouldn't work.
> 
> 1. Add the structure for sugary `TagType`s.
> 2. Replace `ElaboratedType` with sugary `TagType`s.
> 3. Change the representation of NNS.

Well it's not just TagTypes which were changed in order to not need ElaboratedType, everything else too (TypedefTypes, TemplateSpecializationTypes, etc).

It would be really annoying to remove ElaboratedType from just TagType, leave it on everything else, while making every test pass, due for example how complicated some AST matchers would become in the intermediary state.

If you meant splitting the ElaboratedType removal from the NestedNameSpecifier representation change, that's easier to do, but still its a lot of work to make it in a way which every test passes.

If you would be happy to have dependent patches which must still be tested together, I can certainly split this patch (part 1) into NestedNameSpecifier changes and ElaboratedType changes, if that helps.

File: clang/include/clang/AST/NestedNameSpecifierBase.h (hunk 2 above)
Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifierBase.h]: Yeah, this rename would be straight forward.

**Comment by mizvekov** [comment]
> For obvious reasons, I wasn't able to make even a reasonably thorough review here, but I came across a few things that seemed like good ideas. All 4 of the patches are STILL huge.
> 
> IMO, unless this can be more bite-sized changes, I don't know how to proceed here.

Yes this can be more bite-sized changes, as long as we keep the patches not individually testable.

I will follow the suggestion above.

**Comment by rjmccall** [comment]
> > You should at minimum be able to layer the `NestedNameSpecifier` change on top of the `TagType` change. I can't see why that wouldn't work.
> > 
> > 1. Add the structure for sugary `TagType`s.
> > 2. Replace `ElaboratedType` with sugary `TagType`s.
> > 3. Change the representation of NNS.
> 
> Well it's not just TagTypes which were changed in order to not need ElaboratedType, everything else too (TypedefTypes, TemplateSpecializationTypes, etc).
> 
> It would be really annoying to remove ElaboratedType from just TagType, leave it on everything else, while making every test pass, due for example how complicated some AST matchers would become in the intermediary state.

I actually don't see why. AST matching becomes heinously complicated in the *end* state of your change if you don't have methods to ask questions like "was this written as an elaborated type" or whatever else the client code in Sema is looking for. So presumably you do have those predicates, and the end state uses them. You can certainly implement those predicates in terms of `ElaboratedType` while it still exists. That should be patch 1.

**Comment by mizvekov** [comment]
> I actually don't see why. AST matching becomes heinously complicated in the _end_ state of your change if you don't have methods to ask questions like "was this written as an elaborated type" or whatever else the client code in Sema is looking for. So presumably you do have those predicates, and the end state uses them. You can certainly implement those predicates in terms of `ElaboratedType` while it still exists. That should be patch 1.

Yes, that's possible, maybe this is not as hard as I originally made it seem to be, but any kind of splitting this up in which every test has to pass in intermediary states would be a huge time sink to me in my current condition.

I made this patch while I was working 100% on clang, and then continued while I was unemployed while looking for a new thing. Now I have a new project with another employer, and it's not dedicated to clang upstream anymore, so I am not sure when I will have that kind of time again.

**Comment by zyn0217** [comment]
Given the scale of the patch, it's not surprising if it undergoes some revert-reapplies cycles after the initial commit.

To reduce the churn, would it be possible to ask google (and other major downstream clients) to test it internally before we merge? @AaronBallman

**Comment by AaronBallman** [comment]
> Given the scale of the patch, it's not surprising if it undergoes some revert-reapplies cycles after the initial commit.
> 
> To reduce the churn, would it be possible to ask google (and other major downstream clients) to test it internally before we merge? @AaronBallman

We can certainly ask; it's in their best interests to avoid that amount of churn if there are problems. But I'm not certain we have a way to really do that aside from poke individuals and see whether they're willing to try it out internally or not.

File: clang/include/clang/AST/ASTContext.h [hunk 5]
```diff
@@ -2068,7 +2080,9 @@ class ASTContext : public RefCountedBase<ASTContext> {
   /// if it hasn't yet been built.
   QualType getRawCFConstantStringType() const {
     if (CFConstantStringTypeDecl)
-      return getTypedefType(CFConstantStringTypeDecl);
+      return getTypedefType(ElaboratedTypeKeyword::None,
+                            /*Qualifier=*/std::nullopt,
+                            CFConstantStringTypeDecl);
```
Comment (Sirraide) [inline clang/include/clang/AST/ASTContext.h:2108]: Thoughts about moving that third parameter to the front and adding default argument for what is currently the 1st and 2nd parameter? Because I’m noticing that there are a bunch of call sites that pass `ElaboratedTypeKeyword::None, /*Qualifier=*/std::nullopt` as the first two params.

File: clang/include/clang/AST/NestedNameSpecifierBase.h [hunk 6]
```diff
@@ -0,0 +1,585 @@
...
+    Type,
+    NamespaceOrSuper,
+    NamespaceWithGlobal,
+    NamespaceWithNamespace
+  };
+  static constexpr uintptr_t FlagBits = 2, FlagMask = (1u << FlagBits) - 1u,
+                             FlagOffset = 1, PtrOffset = FlagBits + FlagOffset,
+                             PtrMask = (1u << PtrOffset) - 1u;
+
+  uintptr_t StoredOrFlag;
```
Comment (Sirraide) [inline clang/include/clang/AST/NestedNameSpecifierBase.h:63]: I’m assuming we can’t use `PointerIntPair` for this because we’re dealing w/ a `const void*` here?

File: clang/include/clang/AST/NestedNameSpecifierBase.h [hunk 7]
```diff
@@ -0,0 +1,585 @@
...
+
+    /// A namespace-like entity, stored as a NamespaceBaseDecl*.
+    Namespace,
+
+    /// Microsoft's '__super' specifier, stored as a CXXRecordDecl* of
+    /// the class it appeared in.
+    Super,
+  };
+
+  inline Kind getKind() const;
```
Comment (Sirraide) [inline clang/include/clang/AST/NestedNameSpecifierBase.h:133]: Is there a reason a lot of these declarations are `inline`? Because from what I know that doesn’t really do anything on declarations that aren’t definitions, does it?

File: clang/include/clang/AST/NestedNameSpecifier.h [hunk 8]
```diff
@@ -6,534 +6,266 @@
...
-  SpecifierKind getKind() const;
-
-  /// Retrieve the identifier stored in this nested name
-  /// specifier.
-  IdentifierInfo *getAsIdentifier() const {
-    if (Prefix.getInt() == StoredIdentifier)
-      return (IdentifierInfo *)Specifier;
-
-    return nullptr;
+auto NestedNameSpecifier::getKind() const -> Kind {
```
Comment (Sirraide) [inline clang/include/clang/AST/NestedNameSpecifier.h:24]: Is there a reason all of these functions are defined in a header rather than a .cpp file? Does inlining them actually have that big of a performance impact?

**Review by Sirraide — COMMENTED** [review]
Some comments, but I will say that I haven’t nearly reviewed all of this because it’s rather massive (and I’m also not too familiar w/ everything around NNSs).

File: clang/include/clang/AST/NestedNameSpecifierBase.h (hunk 7 above)
Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifierBase.h:133]: It does, an inline definition can't be provided here due to circular dependencies, but it is provided in `NestedNameSpecifier.h`. This is a way to get around the interdependence with `Decl.h` and `Type.h`.

File: clang/include/clang/AST/NestedNameSpecifier.h (hunk 8 above)
Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifier.h:24]: It does yes, this was tested against results from `llvm-compile-time-tracker`.

File: clang/include/clang/AST/NestedNameSpecifierBase.h (hunk 6 above)
Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifierBase.h:63]: We can't use PointerIntPair because it needs a complete definition for `Decl`, which can't be made available at this point.

File: clang/include/clang/AST/ASTContext.h (hunk 5 above)
Comment (mizvekov) [reply clang/include/clang/AST/ASTContext.h:2108]: The lack of default parameters helped migrate code to conform to the changes, and I suspect it will equally help upstream users once this lands.

Comment (Sirraide) [reply clang/include/clang/AST/ASTContext.h:2108]: Makes sense

File: clang/include/clang/AST/NestedNameSpecifierBase.h (hunk 6 above)
Comment (rjmccall) [reply clang/include/clang/AST/NestedNameSpecifierBase.h:63]: You can't include Decl.h, but you might be able to include DeclBase.h. You could also just pull out a header with an explicit specialization of `PointerLikeTypeTraits<Decl*>`, the same way that DeclBase.h has to with `NamedDecl*` to handle the decl list in `DeclContext`.

Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifierBase.h:63]: Thanks, I will give that a try. Actually `NamedDecl` would be better here than `Decl`, since I can't think of a reason we would ever have a non-named entity named in a NestedNameSpecfier.

Comment (mizvekov) [reply clang/include/clang/AST/NestedNameSpecifierBase.h:63]: I tried the PointerIntPair approach using a custom PointerLikeTypeTrait: https://github.com/llvm/llvm-project/commit/0bdc690d5ee682848f508d0736a02135658cd214

The result has slightly worse performance than the current hand-rolled implementation:
image

In this case, I'd prefer keeping the current approach, as it is not much more complicated.

File: clang/lib/AST/ByteCode/Program.cpp (hunk 4 above)
Comment (mizvekov) [reply clang/lib/AST/ByteCode/Program.cpp]: I have split up all the trivial changes related to 'getOriginalDecl' into its own patch: https://github.com/llvm/llvm-project/pull/149747

**Comment by mizvekov** [comment]
I have further split up this patch series, now the changes related to the NNS representation are moved last in the patch series: https://github.com/llvm/llvm-project/pull/149748

I have also moved some of the trivial changes into yet another patch: https://github.com/llvm/llvm-project/pull/149747

As a result, this and the other patches in the series are smaller.
Let me know if that's enough, or if you would rather I keep splitting further.

Otherwise, I have addressed all pending reviews, and this is ready for another round.

File: clang/include/clang/AST/ASTTypeTraits.h [hunk 9]
```diff
@@ -307,7 +307,7 @@ class DynTypedNode {
 
   /// For nodes which represent textual entities in the source code,
   /// return their SourceRange.  For all other nodes, return SourceRange().
-  SourceRange getSourceRange() const;
+  SourceRange getSourceRange(bool IncludeQualifier = false) const;
```
Comment (erichkeane) [inline clang/include/clang/AST/ASTTypeTraits.h:310]: I have a mild preference for this being `getSourceRangeIncludingQualifier` (that is, an overload instead of a default arg)?  Unless it results in an `if/else` tree elsewhere.

File: clang/include/clang/AST/NestedNameSpecifier.h [hunk 10]
```diff
@@ -532,4 +532,4 @@ template <> struct DenseMapInfo<clang::NestedNameSpecifierLoc> {
 };
 } // namespace llvm
 
-#endif // LLVM_CLANG_AST_NESTEDNAMESPECIFIER_H
+#endif // LLVM_CLANG_AST_NESTEDNAMESPECIFIERBASE_H
```
Comment (erichkeane) [inline clang/include/clang/AST/NestedNameSpecifier.h:535]: This doesn't seem right?

**Review by erichkeane — APPROVED** [review]
I did as thorough of a review as I could.  a small nit, else this is LGTM once the other reviewers who have commented are happy.

File: clang/include/clang/AST/DynamicRecursiveASTVisitor.h [hunk 11]
```diff
@@ -181,14 +181,14 @@ template <bool IsConst> class DynamicRecursiveASTVisitorBase {
   ///
   /// \returns false if the visitation was terminated early, true
   /// otherwise (including when the argument is a Null type).
-  virtual bool TraverseType(QualType T);
+  virtual bool TraverseType(QualType T, bool TraverseQualifier = true);
```
[the remark this answers is not in the document]
Comment (mizvekov) [reply clang/include/clang/AST/DynamicRecursiveASTVisitor.h:184]: I find the parameter easier to debug, it's easier to trace how the value gets propagated.

With a data member / RAII object, it takes longer to figure out where, in a given stack trace, the value was changed.

There is also precedent for this solution here. For example see `clang-tools-extra/clang-tidy/modernize/UseTrailingReturnTypeCheck.cpp` TraverseTypeLoc implementation, where an analogous parameter was implemented (called 'Elaborated' instead).

**Comment by zwuis** [comment]
I added comment `// FIXME (GH147000): duplicate diagnostics` to `clang/test/SemaCXX/nested-name-spec.cpp` in #147003. Please remove the comment if that issue is fixed by this patch.

**Comment by mizvekov** [comment]
> I added comment `// FIXME (GH147000): duplicate diagnostics` to `clang/test/SemaCXX/nested-name-spec.cpp` in #147003. Please remove the comment if that issue is fixed by this patch.

This is actually fixed by changes I left out of this patch, I updated the commit description accordingly.

**Comment by katzdm** [comment]
Hey @mizvekov - Just wanted to point out a few C++26 changes to nested-name-specifiers (via P2996), in case it helps in any way to future-proof your design.
- A nested-name-specifier can now be either "_splice-specifier_ `::`" or "`template` _splice-specialization-specifier_ `::`", where _splice-specifier_ is "`[:` _constant-expression_ `:]`" and the _constant-expression_ may be dependent (so we may not yet know at parse-time whether it designates a type or a namespace); _splice-specialization-specifier_ is a _splice-specifier_ followed by a template argument list ([expr.prim.id.qual], [basic.splice]).
- A nested-name-specifier of the form "_namespace-name_ `::`" can now be dependent, e.g.,

```cpp
template <std::meta::info R>
  requires is_namespace(R)
int f() {
  namespace Alias = [:R:];
  return Alias::constant;  // 'Alias::' is a dependent namespace-name ([temp.dep.namespace]).
}
```

Hope that neither of these complicate your refactor! Looks like super impressive work; looking forward to seeing it land.

**Comment by mizvekov** [comment]
> Hope that neither of these complicate your refactor! Looks like super impressive work; looking forward to seeing it land.

Thanks, that was very a very helpful summary!

I don't think this changes much about the design here, we will get a few new nested name kinds, and these will be less common than all of the existing ones, so we can put them in the slow path, changing `NamespaceAndPrefixStorage` into something which can store the new kinds, without that affecting the existing stuff significantly.

**Comment by mizvekov** [comment]
The HLSL Tests bot failure was some GitHub permission issue when publishing the results of the successful run:
```
2025-08-09T07:06:35.4098240Z Request POST /repos/llvm/llvm-project/check-runs failed with 403: Forbidden
2025-08-09T07:06:35.4098670Z 2025-08-09 02:06:35 -0500 - github.GithubRetry -  INFO - Request POST /repos/llvm/llvm-project/check-runs failed with 403: Forbidden
2025-08-09T07:06:35.4099210Z Traceback (most recent call last):
2025-08-09T07:06:35.4100200Z   File "/Users/cbieneman/actions-runner/_work/_actions/EnricoMi/publish-unit-test-result-action/170bf24d20d201b842d7a52403b73ed297e6645b/macos/../python/publish_test_results.py", line 546, in <module>
2025-08-09T07:06:35.4101240Z     main(settings, gha)
2025-08-09T07:06:35.4101840Z   File "/Users/cbieneman/actions-runner/_work/_actions/EnricoMi/publish-unit-test-result-action/170bf24d20d201b842d7a52403b73ed297e6645b/macos/../python/publish_test_results.py", line 269, in main
2025-08-09T07:06:35.4102530Z     Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
2025-08-09T07:06:35.4103150Z   File "/Users/cbieneman/actions-runner/_work/_actions/EnricoMi/publish-unit-test-result-action/170bf24d20d201b842d7a52403b73ed297e6645b/python/publish/publisher.py", line 233, in publish
2025-08-09T07:06:35.4112040Z     data = self.publish_check(data)
2025-08-09T07:06:35.4112950Z   File "/Users/cbieneman/actions-runner/_work/_actions/EnricoMi/publish-unit-test-result-action/170bf24d20d201b842d7a52403b73ed297e6645b/python/publish/publisher.py", line 461, in publish_check
2025-08-09T07:06:35.4114640Z     check_run = self._repo.create_check_run(name=self._settings.check_name,
2025-08-09T07:06:35.4115270Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Repository.py", line 3885, in create_check_run
2025-08-09T07:06:35.4129000Z     headers, data = self._requester.requestJsonAndCheck(
2025-08-09T07:06:35.4129600Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Requester.py", line 550, in requestJsonAndCheck
2025-08-09T07:06:35.4133670Z     return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
2025-08-09T07:06:35.4134330Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Requester.py", line 715, in requestJson
2025-08-09T07:06:35.4134930Z     return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
2025-08-09T07:06:35.4135520Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Requester.py", line 812, in __requestEncode
2025-08-09T07:06:35.4136240Z     status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
2025-08-09T07:06:35.4136880Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Requester.py", line 846, in __requestRaw
2025-08-09T07:06:35.4137490Z     response = cnx.getresponse()
2025-08-09T07:06:35.4138000Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/Requester.py", line 198, in getresponse
2025-08-09T07:06:35.4138500Z     r = verb(
2025-08-09T07:06:35.4138940Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
2025-08-09T07:06:35.4141770Z     return self.request("POST", url, data=data, json=json, **kwargs)
2025-08-09T07:06:35.4142390Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
2025-08-09T07:06:35.4142900Z     resp = self.send(prep, **send_kwargs)
2025-08-09T07:06:35.4143390Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
2025-08-09T07:06:35.4143890Z     r = adapter.send(request, **kwargs)
2025-08-09T07:06:35.4144370Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
2025-08-09T07:06:35.4145190Z     resp = conn.urlopen(
2025-08-09T07:06:35.4145680Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 934, in urlopen
2025-08-09T07:06:35.4149990Z     retries = retries.increment(method, url, response=response, _pool=self)
2025-08-09T07:06:35.4150560Z   File "/Users/cbieneman/actions-runner/_work/llvm-project/llvm-project/enricomi-publish-action-venv/lib/python3.9/site-packages/github/GithubRetry.py", line 187, in increment
2025-08-09T07:06:35.4152030Z     raise Requester.createException(response.status, response.headers, content)  # type: ignore
2025-08-09T07:06:35.4152720Z github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run", "status": "403"}
2025-08-09T07:06:35.4812330Z ##[error]Process completed with exit code 1.
```

**Comment by DavidSpickett** [comment]
https://github.com/llvm/llvm-project/pull/152993 fixes this.

Pretty sure there's no problem with this PR, it uncovered an existing problem in the formatter itself.

**Comment by kimgr** [comment]
Did this PR intentionally break the `RecursiveASTVisitor` API? The new `TraverseQualifier` argument through the whole `Traverse.*Type` hierarchy makes all CRTP overrides not be called, unless I'm missing something.

It's a bit hard to test, because the NNS changes also break a lot of code in IWYU, so it's tricky to play with things in isolation.

**Comment by mizvekov** [comment]
> Observation using clangd: In the following construct
> ...
> The "arcana" field of the AST node of "Foo" inside the function reports the "QualType" as "Foo", whereas before it was "N::Foo". Is that expected?

It looks correct in that this is the as-written type.

Now I am not sure clangd wants to present the type that way, maybe they want to fully qualify it for printing instead?
@kadircet @hokein

**Comment by mysterymath** [comment]
We are seeing an assertion failure in one of Fuchsia's builders due to this:

```
[38296/176952](67) CXX user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o
FAILED: [code=1] user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o
../../prebuilt/third_party/clang/custom/bin/clang++ -MD -MF user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o.d -o user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o -DWITH_FRAME_POINTERS=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -DZX_ASSERT_LEVEL=2 -D_ALL_SOURCE -DHAVE_LLVM_PROFDATA=0 -I../../zircon/system/p...
clang++: clang/lib/AST/TemplateBase.cpp:610: clang::TemplateArgumentLoc::TemplateArgumentLoc(ASTContext &, const TemplateArgument &, SourceLocation, NestedNameSpecifierLoc, SourceLocation, SourceLocation): Assertion `QualifierLoc.getNestedNameSpecifier() == Argument.getAsTemplateOrTemplatePattern().getQualifier()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: ../../prebuilt/third_party/clang/custom/bin/clang++ -MD -MF user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o.d -o user.basic_x64-shared/obj/sdk/lib/ld/libld-startup.zircon-startup.cc.o -DWITH_FRAME_POINTERS=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -DZX_ASSERT_LEVEL=2 -D_ALL_SOURCE -DHAVE_LLVM_PROFDATA=0 -...
1.	<eof> parser at end of file
2.	../../sdk/lib/ld/startup-load.h:183:15: instantiating function definition 'ld::StartupLoadModule<elfldltl::LocalVmarLoader>::LinkModules<trivial_allocator::BasicLeakyAllocator<trivial_allocator::OwningAllocateFunction<trivial_allocator::PageAllocator<trivial_allocator::ZirconVmar>>>, InitialExecAllocator, (lambda at ../../sdk/lib/ld/zircon-startup.cc:210:23) &, zx::vmar &>'
3.	../../sdk/lib/ld/startup-load.h:289:15: instantiating function definition 'ld::StartupLoadModule<elfldltl::LocalVmarLoader>::LoadDeps<trivial_allocator::BasicLeakyAllocator<trivial_allocator::OwningAllocateFunction<trivial_allocator::PageAllocator<trivial_allocator::ZirconVmar>>>, InitialExecAllocator, (lambda at ../../sdk/lib/ld/zircon-startup.cc:210:23) &, zx::vmar &>'
4.	../../sdk/lib/ld/startup-load.h:269:8: instantiating function definition 'ld::StartupLoadModule<elfldltl::LocalVmarLoader>::EnqueueDeps<trivial_allocator::BasicLeakyAllocator<trivial_allocator::OwningAllocateFunction<trivial_allocator::PageAllocator<trivial_allocator::ZirconVmar>>>, zx::vmar &>'
#0 0x000055b727798b48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../prebuilt/third_party/clang/custom/bin/clang+++0x9396b48)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Fuchsia clang version 22.0.0git (https://llvm.googlesource.com/llvm-project 10e146a7161065429629a13f99c179a61ffe7721)
Target: x86_64-unknown-fuchsia
Thread model: posix
InstalledDir: ../../prebuilt/third_party/clang/cu...
```

Can you revert or fix forward? I've no idea whether this helps with debugging at all, but this is the source file that produced the assertion failure in clang: https://cs.opensource.google/fuchsia/fuchsia/+/main:sdk/lib/ld/zircon-startup.cc?q=zircon-startup.cc&ss=fuchsia

**Comment by kadircet** [comment]
> > Observation using clangd: In the following construct
> > ...
> > The "arcana" field of the AST node of "Foo" inside the function reports the "QualType" as "Foo", whereas before it was "N::Foo". Is that expected?
> 
> It looks correct in that this is the as-written type.
> 
> Now I am not sure clangd wants to present the type that way, maybe they want to fully qualify it for printing instead? @kadircet @hokein

clangd doesn't really have a preference here, we just surface `-ast-dump` in a editor friendly format, for debugging purposes.

one can repro the situation with `clang -xc++ -fsyntax-only -Xclang=-ast-dump a.cc`

where a.cc is:
```cpp
namespace N {
struct Foo {};
}  // namespace N
void f() {
  using namespace N;
  Foo foo;
  N::Foo x;
}
```

pre this change output looks like:
```
`-FunctionDecl 0x5621625282a0 <line:4:1, line:8:1> line:4:6 f 'void ()'
  `-CompoundStmt 0x562162528d10 <col:10, line:8:1>
    |-DeclStmt 0x5621625283e8 <line:5:3, col:20>
    | `-UsingDirectiveDecl 0x562162528390 <col:3, col:19> col:19 Namespace 0x562162528018 'N'
    |-DeclStmt 0x562162528b88 <line:6:3, col:10>
    | `-VarDecl 0x562162528440 <col:3, col:7> col:7 foo 'Foo':'N::Foo' callinit
    |   `-CXXConstructExpr 0x562162528b60 <col:7> 'Foo':'N::Foo' 'void () noexcept'
    `-DeclStmt 0x562162528cf8 <line:7:3, col:11>
      `-VarDecl 0x562162528c38 <col:3, col:10> col:10 x 'N::Foo' callinit
        `-CXXConstructExpr 0x562162528cd0 <col:10> 'N::Foo' 'void () noexcept'
```

emphasis on `-VarDecl 0x562162528440 <col:3, col:7> col:7 foo 'Foo':'N::Foo' callinit`

after thins change this is now reported as `VarDecl 0x5652a7615860 <col:3, col:7> col:7 foo 'Foo' callinit`

this was handled by https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/TextNodeDumper.cpp#L909-L926, I am not sure if change is intended (i think we should still be able to detect & desugar)

**Comment by bolshakov-a** [comment]
> The new `TraverseQualifier` argument through the whole `Traverse.*Type` hierarchy ...

@mizvekov, anyway, it would be good to know if `TraverseQualifier` is a customization point for users who implement their own `RecursiveASTVisitor` subclasses, or the default argument value should always be `true`? There is an assertion inside `TraverseQualifiedTypeLoc`:
https://github.com/llvm/llvm-project/blob/72b53cde1c80672217da963b0150a17b79a8383c/clang/include/clang/AST/RecursiveASTVisitor.h#L1282
However, I don't see where in the world `QualifiedTypeLoc` is created...

**Comment by mizvekov** [comment]
> After this commit, the comment in `clang/include/clang/AST/Decl.h` for `clang::TypeDecl::getTypeForDecl`,
> isn't accurate any more, there's no more `ASTContext::getRecordType`.

Thanks for reporting, I'll fix in a follow up patch.

 > Observation using clangd: In the following construct
> this was handled by https://github.com/llvm/llvm-project/blob/main/clang/lib/AST/TextNodeDumper.cpp#L909-L926, I am not sure if change is intended (i think we should still be able to detect & desugar)

Right, the difference here is that before this patch, if you print a fully desugared tag type (that's what the 'aka'  in the diagnostic does), the type is printed fully qualified. That's because the name qualifiers were carried in the 'ElaboratedType' sugar node, and we used to handle this situation specially: we assumed a bare tag type only occurred because of canonicalization.

With this patch the tag types themselves carry the name qualifier, so just removing the top level sugar doesn't make them lose name qualifier information.

We still fully qualify canonical tag types when printing them though, but that now happens because a canonical tag type is a special value which is not identical to any other tag type for the same declaration.

We may still want to fully qualify types for the 'aka' diagnostic, but I deferred that for a follow up patch in order to limit the amount of test churn.

For clangd, I assume the same thing is happening here, for this  arcana" field, you are fully desugaring the type before printing it.

> @mizvekov, anyway, it would be good to know if `TraverseQualifier` is a customization point for users who implement their own `RecursiveASTVisitor` subclasses, or the default argument value should always be `true`?

The TraverseQualifier flag means, 'should I traverse NestedNameSpecifiers?'

If you are simply customizing one of the Traverse* methods which take it, but still delegating to the base class Traverse method, you should just forward that flag along to the base method.

If you are implementing your own Traverse method for a type from scratch, then if this flag is false, you should not traverse the nested name specifier for that type.

> There is an assertion inside `TraverseQualifiedTypeLoc`:
> https://github.com/llvm/llvm-project/blob/72b53cde1c80672217da963b0150a17b79a8383c/clang/include/clang/AST/RecursiveASTVisitor.h#L1282
> 
> 
> However, I don't see where in the world `QualifiedTypeLoc` is created...

QualifiedTypeLoc is created implicitly for QualTypes which have top level qualifiers, and they represent the source locations for type qualifiers (not name qualifiers, different thing.)

This assert here means that a top level type qualifier can't appear within a nested name specifier (but it could appear for example in the underlying type for a typedef).

The C++ grammar doesn't allow you to write const / volatile in a way which applies to an entity in the name qualifier itself.

While such a NestedNameSpecifier could still be produced as part of template argument deduction, we simply remove the top level qualifiers in that case, as the NestedNameSpecifier AST node itself still can't represent it.

**Comment by mysterymath** [comment]
> > We are seeing an assertion failure in one of Fuchsia's builders due to this:
> 
> Can you please attach the crash reproducer which clang should have generated? Thanks.

https://storage.googleapis.com/fuchsia-artifacts/builds/8707018386865583409/build-debug/clang-crashreports/zircon-startup-bad996.tar

**Comment by mizvekov** [comment]
> @mizvekov, thanks for the clarifying! In fact, it means that at least `TraverseTypeLoc` should not, in general, be given `false` as `TraverseQualifier` argument because (it looks like) nothing inside `RecursiveASTVisitor` changes it to `true` before `TraverseQualifiedTypeLoc` call. Note that it may be called not only from the NNS traversal.

Yeah, it may only given false in the implementation of TraverseNestedNameSpecifier, which for out-of-tree users is only relevant if you are overriding that. If you mistakenly passed true instead, the name qualifiers would be visited twice.

**Comment by emaxx-google** [comment]
> > > We are seeing an assertion failure in one of Fuchsia's builders due to this:
> > 
> > 
> > Can you please attach the crash reproducer which clang should have generated? Thanks.
> 
> https://storage.googleapis.com/fuchsia-artifacts/builds/8707018386865583409/build-debug/clang-crashreports/zircon-startup-bad996.tar

Minimized this using C-Vise to 620 bytes: https://pastebin.com/yegBAfpe

**Comment by mizvekov** [comment]
> Minimized this using C-Vise to 620 bytes: https://pastebin.com/yegBAfpe

Thanks, that has been fixed here: https://github.com/llvm/llvm-project/pull/153344

**Comment by bolshakov-a** [comment]
They should be avoided not always but in certain circumstances, so there should be a new flag field in the visitor class. Not many new code, TBH, but using `TraverseQualifier` was so tempting...

**Comment by bolshakov-a** [comment]
The assert doesn't hurt us, as I've said. I just asked if it is a "documented way" of working with the new visitor interface. If it not to be avoided, then we will probably just proceed with the `TraverseQualifier` manipulation.

**Comment by mizvekov** [comment]
It would be hard for us to document this as an intended interface, but leave that assert in the way, even if you found yourself a way to avoid it. This wouldn't look very polished.

**Comment by bolshakov-a** [comment]
Out of curiosity. The old `getDecl()` methods returned the tag type definition (if present), whereas the new `getOriginalDecl()` returns just some of redeclarations (and not necessarily the first one). What is the reason of such change?

**Comment by DKLoehr** [comment]
I don't know if this is the same as the other crash report, but we're also seeing assert failures when building chromium. I've minimized the repro to the following program:
```
template <typename T> struct S {
  using typename T::Ty;
  static Ty Val;
};
template <typename T>
S<T>::Ty S<T>::Val;
```

This fails when running `clang++ -c repro.cc` when clang is built with asserts (`-std=c++20` silences a warning but isn't necessary). The crash looks like this:
```
llvm-project/clang/include/clang/AST/TypeLoc.h:79: T clang::TypeLoc::castAs() const [T = clang::DependentNameTypeLoc]: Assertion `T::isKind(*this)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang++ -c repro.cc
1.      p.cc:6:19: current parser token ';'
<snip long backtrace>
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 22.0.0git (https://github.com/llvm/llvm-project.git 91cdd35008e9ab32dffb7e401cdd7313b3461892)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Build config: +assertions
```

**Comment by mizvekov** [comment]
> Out of curiosity. The old `getDecl()` methods returned the tag type definition (if present) because they called `getInterestingTagDecl` function internally, whereas the new `getOriginalDecl()` returns just some of redeclarations (and not necessarily the first one). What is the reason of such change?

`getOriginalDecl()` returns exactly the declaration that was found by type lookup when producing the type. If this was a forward declaration, because that was the only thing that was in scope at that point the type was written in source code, that is the declaration that will be returned.

This helps establishing the source file origins of the dependencies of some piece of code.

**Comment by mizvekov** [comment]
> Thanks! However, for the following piece of code
> `getOriginalDecl()` called on the pointed-to type gives the forward-declaration from the 3rd line, and the forward-declaration from the 1st line for its canonical type.

Yes that is correct.

The 3rd line is what declaration was found by type lookup at that point, and the canonical declaration has long been established in clang as the first declaration.

**Comment by mizvekov** [comment]
> I don't know if this is the same as the other crash report, but we're also seeing assert failures when building chromium. I've minimized the repro to the following program:

Thanks, this is going to be fixed by https://github.com/llvm/llvm-project/pull/153862

**Comment by vbvictor** [comment]
Hi!
We are seeing regression in `clang-tidy` in `modernize-type-traits` check https://github.com/llvm/llvm-project/issues/153649. I confirmed locally that on 91cdd35008e9ab32dffb7e401cdd7313b3461892 it is bugged and commit before it is not fc44a4fcd3c54be927c15ddd9211aca1501633e7

File: clang/lib/AST/ItaniumMangle.cpp [hunk 12]
```diff
@@ -2586,8 +2561,9 @@ bool CXXNameMangler::mangleUnresolvedTypeOrSimpleId(QualType Ty,
   }
 
   case Type::InjectedClassName:
-    mangleSourceNameWithAbiTags(
-        cast<InjectedClassNameType>(Ty)->getDecl());
+    mangleSourceNameWithAbiTags(cast<InjectedClassNameType>(Ty)
+                                    ->getOriginalDecl()
+                                    ->getDefinitionOrSelf());
```
Comment (bolshakov-a) [inline clang/lib/AST/ItaniumMangle.cpp:2566]: Is this `getDefinitionOrSelf()` call necessary here? Shouldn't `InjectedClassNameType` always refer to the definition where the class name is injected to?

Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: Not always.

I mean you could certainly attempt to define an `InjectedClassNameType` whose declaration necessarily is the definition.

This would cause many annoyances, most of them surmountable, as you wouldn't be able to form a type to an arbitrary declaration (which we do offhandedly in error recovery and printing diagnostics), and the type would play by different rules than other tag types.

Though I think at the end, you would come to the problem of demoted definitions, which come up for example when merging definitions from the GMF of different modules. You would have to throw away the ability to represent an InjectedClassNameType pointing to a demoted definition.

Comment (bolshakov-a) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: I've caught an example:
```cpp
template <typename>
struct Tpl;

template <typename>
struct Tpl {
  Tpl(const Tpl&) {}
};
```
The injected name from the copy ctor prototype refers to the forward-declaration from the first two lines. Looks a little strange but Ok.

Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: Are you sure it's not just its canonical type which refers to the first two lines?

Comment (bolshakov-a) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: Heh, interesting. `getAs` function actually returns the canonical type.

Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: getAs only desugars. This could happen with a TemplateSpecializationType which its canonical type is an InjectedClassNameType, since in that case desugar just returns the canonical type, but that is not the case for that constructor, since its using an InjectedClassNameType as written in source code.

**Comment by mizvekov** [comment]
> We started to see a CI failure around the time this PR landed in https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/1079/
> Any ideas what might be going on here?

@Xazax-hun this could be the same as https://github.com/llvm/llvm-project/issues/153933

Could you confirm if the hang is limited to assertions enabled llvm builds, and if https://github.com/llvm/llvm-project/pull/153996 is sufficient to fix the problem?

File: clang/lib/AST/ItaniumMangle.cpp (hunk 12 above)
Comment (bolshakov-a) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: I've understood: there are specializations of `getAs` for the leaf non-sugar types:

https://github.com/llvm/llvm-project/blob/71925a90c8b713d8fccbfae496e10c68f80b932b/clang/include/clang/AST/Type.h#L3138-L3140

If you call `getAs<InjectedClassNameType>()` on a `Type` which is already `InjectedClassNameType`, you get its canonical type.

Comment (bolshakov-a) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: Btw, it is a drawback of templates that you can easily overlook a specialization.

**Comment by rupprecht** [comment]
Filed #154270 w/ another crash, which looks different from #153933 / #153996.

**Comment by shafik** [comment]
Git bisect also blame this PR for: https://github.com/llvm/llvm-project/issues/154270

**Comment by mizvekov** [comment]
> Okay, if this is just a temporary oddity, that's fine. My big concern is that "original" implies "first" and that doesn't match the comment on what's returned. Because temporary measures have a tendency to ossify sometimes, it might make sense to add some more comments to clarify the situation. WDYT?

Yeah sure, it would have been a good idea to add a FIXME explaining this, I will do.

**Comment by rupprecht** [comment]
I'm trying to reduce a crash that only reproduces w/ in module builds. Does this sound familiar?

```
assertion failed at clang/lib/AST/RecordLayoutBuilder.cpp:3380 in const ASTRecordLayout &clang::ASTContext::getASTRecordLayout(const RecordDecl *) const: D && "Cannot get layout of forward declarations!"
*** Check failure stack trace: ***
    @     0x557b3889784f  clang::ASTContext::getASTRecordLayout()
    @     0x557b3823cd68  clang::ASTContext::getTypeInfoImpl()
    @     0x557b3823e25c  clang::ASTContext::getTypeInfo()
    @     0x557b3823d855  clang::ASTContext::getPreferredTypeAlign()
    @     0x557b3823bf01  clang::ASTContext::getDeclAlign()
    @     0x557b366c6a06  clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca()
    @     0x557b366c165c  clang::CodeGen::CodeGenFunction::EmitVarDecl()
    @     0x557b366c1120  clang::CodeGen::CodeGenFunction::EmitDecl()
    @     0x557b36760580  clang::CodeGen::CodeGenFunction::EmitDeclStmt()
    @     0x557b36754d50  clang::CodeGen::CodeGenFunction::EmitSimpleStmt()
    @     0x557b3675403e  clang::CodeGen::CodeGenFunction::EmitStmt()
    @     0x557b36761891  clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope()
    @     0x557b368c47d5  clang::CodeGen::CodeGenFunction::GenerateCode()
    @     0x557b368ef9f6  clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition()
    @     0x557b368e6bc8  clang::CodeGen::CodeGenModule::EmitGlobalDefinition()
    @     0x557b368d7786  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x557b368d77a2  clang::CodeGen::CodeGenModule::EmitDeferred()
...
    @     0x557b368d77a2  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x557b368d77a2  clang::CodeGen::CodeGenModule::EmitDeferred()
    @     0x557b368d41ae  clang::CodeGen::CodeGenModule::Release()
    @     0x557b36a1e14e  (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit()
```

File: clang/lib/AST/ItaniumMangle.cpp (hunk 12 above)
Comment (mizvekov) [reply clang/lib/AST/ItaniumMangle.cpp:2566]: This will be fixed here: https://github.com/llvm/llvm-project/pull/155028

**Comment by michaelrj-google** [comment]
Hi, I'm helping fix some clang-as-a-library users and I'm running into some issues with the TypePrinter after this commit. Specifically the clang generator in sandboxed-api is broken (https://github.com/google/sandboxed-api/tree/main). After doing the trivial fixes (`getDecl` -> `getOriginalDecl`) some of the tests are failing (https://github.com/google/sandboxed-api/blob/main/sandboxed_api/tools/clang_generator/emitter_test.cc).

There are two specific tests failing in that test, `NamedEnumWithoutTypedef` and `NestedAnonymousStruct`.
`NamedEnumWithoutTypedef` expects
```
"enum Color { kRed, kGreen, kBlue }",
"typedef struct { enum Color member; } B"
```
and is getting
```
"typedef struct { enum Color member; } B"
```

While `NestedAnonymousStruct` expects
```
"struct A { struct { int number; } b; int data; }"
```
and is getting
```
"struct A { struct (unnamed struct at input.cc:2:16) b; int data; }"
```

Related, I think the change to [`void TypePrinter::printUsingBefore(const UsingType *T, raw_ostream &OS)`](https://github.com/llvm/llvm-project/blame/d439c9ea4a19bf783120d8efee5e671316666550/clang/lib/AST/TypePrinter.cpp#L1227) might be causing similar issues. The `getKeywordName` is causing `enum` to get printed when the type is listed for template instantiation, which is causing errors. 

If you need more information feel free to reach out, I'm happy to connect you with the relevant people.

**Comment by bgra8** [comment]
After further testing (at google) we're seeing *lots* of other crashes caused by this revision: https://godbolt.org/z/Y3adj3PY1

The previous revision compiles the reduced successfully. Can you please take a look?

**Comment by mizvekov** [comment]
> The previous revision compiles the reduced successfully. Can you please take a look?

Fixed in https://github.com/llvm/llvm-project/pull/155272

**Comment by aeubanks** [comment]
fyi this uncovered some mismatching struct/class declarations, which affects mangling in the MSVC C++ ABI, leading to linker undefined symbol errors. unsure why we weren't seeing this before this change

File: clang/lib/AST/ASTContext.cpp [hunk 13]
```diff
@@ -5254,153 +5253,297 @@ ASTContext::getPredefinedSugarType(PredefinedSugarType::Kind KD) const {
...
+      return QualType(T, 0);
+
+    bool IsInjected = ::getNonInjectedClassName(TD);
+    const Type *CanonicalType = getCanonicalTagType(TD).getTypePtr();
+    const Type *T =
+        getTagTypeInternal(Keyword,
+                           /*Qualifier=*/std::nullopt, TD,
+                           /*OwnsTag=*/false, IsInjected, CanonicalType,
+                           /*WithFoldingSetNode=*/false);
+    TD->TypeForDecl = T;
```
Comment (bradking) [inline clang/lib/AST/ASTContext.cpp:5527]: If `::getNonInjectedClassName(TD)` returns `true`, it updates `TD` to point at the non-injected decl.  Then `TD->TypeForDecl = T` mutates the non-injected decl to point at the `TagType` created for the injected decl.  This also leaves the injected decl's `TypeForDecl` unset, so the process repeats every time the injected decl is encountered, and a new `TagType` is allocated each time.

Comment (mizvekov) [reply clang/lib/AST/ASTContext.cpp:5527]: Thanks, indeed that looks like what happens.

**Comment by mizvekov** [comment]
> fyi this uncovered some mismatching struct/class declarations, which affects mangling in the MSVC C++ ABI, leading to linker undefined symbol errors. unsure why we weren't seeing this before this change

@aeubanks 
Could be because this patch fixes the canonicalization for dependent names and dependent template specialization types with regards to the elaborated keyword. That should affect how a nested dependent type is mangled if spelled w/o typename or struct/class keywords. These should be mangled differently because they are not functionally equivalent (ie the kind of lookup performed is different when these are instantiated, which could lead to ODR violations).

**Comment by mizvekov** [comment]
@aeubanks can you get us a reproducer?

**Comment by mizvekov** [comment]
@michaelrj-google 
> ```
>    ::sapi::v::IntBase<enum A::StorageType> v_type__(type__);
> ```
> 
> which clang errors on.

And that enum type, is that created by Sema, or is that synthesized by code from within your project?

If you are creating that type as a canonical type, or that type is being canonicalized for some reason, then the placement of the enum keyword is controlled by the `SuppressTagKeyword` printing policy.

If you are creating that type yourself within your project, you should use the new TagType ASTContext constructor which takes an ElaboratedKeyword as a parameter. Looks like in that case, you should set it to  `ElaboratedKeyword::None`.

File: clang/lib/AST/ASTContext.cpp (hunk 13 above)
Comment (mizvekov) [reply clang/lib/AST/ASTContext.cpp:5527]: This will soon be fixed here: https://github.com/llvm/llvm-project/pull/155347.

Comment (mizvekov) [reply clang/lib/AST/ASTContext.cpp:5527]: Done.

**Comment by aeubanks** [comment]
```
$ cat /tmp/a.cc
class A;
struct A;
void f(A*) {}
$ clang-old++ -S -o - /tmp/a.cc -O2 -target x86_64-msvc-windows-pc
...
"?f@@YAXPEAVA@@@Z"
...
$ clang-new++ -S -o - /tmp/a.cc -O2 -target x86_64-msvc-windows-pc
...
"?f@@YAXPEAUA@@@Z"
...
```

notice the `V` -> `U`

**Comment by mizvekov** [comment]
@aeubanks 

I see, so that's unfortunate MSVC mangles the struct / class difference.
This is a different problem than I had in mind.

So MSVC mangles according to the tag kind of the first declaration, clang after this changes now mangles it according to the    declaration found by lookup at the point of use.

Sounds like if we want strict MSVC bug-for-bug conformance, we should change that to use the first declaration then.

**Comment by mizvekov** [comment]
> (I think this was covered by tests even, right?) 
No, this patch didn't change any existing mangling tests at all, the behavior in question here was untested.

**Comment by bolshakov-a** [comment]
> We don't want bug-for-bug conformance, but we do want to be ABI compatible.

It really looks like an MSVC bug. If its mangling depends on whether the first (forward-)declaration of a class in a translation unit uses `class` or `struct` class-key, the TUs cannot be linked together in general.

**Comment by mizvekov** [comment]
The MSVC mangling issue is resolved here: https://github.com/llvm/llvm-project/pull/155662

**Comment by rjmccall** [comment]
I mean, it's an MSVC bug in the sense that it's non-conformant behavior, but it's non-conformant behavior that has long since become a cornerstone of the MSVC ABI, so the bugginess is no longer relevant. We are obliged to maintain compatibility with it if we want to say we implement the ABI correctly.

**Comment by nico** [comment]
FWIW, clang has a warning like that too, it's `-Wmismatched-tags` (part of `-Wmost`, which is part of `-Wall`).
