### PR TITLE
[Mips] Add the missing judgment when processing function handleMFLOSlot

### LINKED ISSUE #118223: [llvm][Mips] After 677177bb60d, Assertion failed: (!NodePtr->isKnownSentinel()), function operator*
After `llvmorg-20-init-06683-g`677177bb60d ("[Mips] Fix mfhi/mflo hazard miscompilation about div and mult (#91449)") by @yingopq, building parts of libzfs on FreeBSD for mips asserts with:

```text
Assertion failed: (!NodePtr->isKnownSentinel()), function operator*, file /home/dim/src/llvm/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h, line 168.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang -cc1 -triple mips-unknown-freebsd13.4 -S -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -mrelocation-model static -mframe-pointer=all -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu mips2 -target-feature -noabicalls -target-feature +soft-float -target-abi o32 -msoft-float -mfloat-abi soft -mllvm -mips-ssection-threshold=0 -mllvm -enable-shrink-wrap-region-split=false -O2 -Werror -Wall -std=iso9899:1999 -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -faddrsig arc-cacfd2.i
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'arc-cacfd2.c'.
4.      Running pass 'Mips Branch Expansion Pass' on function '@arc_init'
 #0 0x000000000469d6d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x469d6d8)
 #1 0x000000000469b4b9 llvm::sys::RunSignalHandlers() (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x469b4b9)
 #2 0x000000000469de9e SignalHandler(int) Signals.cpp:0:0
 #3 0x000000082a71057c handle_signal /usr/src/lib/libthr/thread/thr_sig.c:0:3
 #4 0x000000082a70fb4b thr_sighandler /usr/src/lib/libthr/thread/thr_sig.c:244:1
 #5 0x00000008293402d3 ([vdso]+0x2d3)
 #6 0x000000082e8d45ca __sys_thr_kill /usr/obj/usr/src/amd64.amd64/lib/libsys/thr_kill.S:4:0
 #7 0x000000082e61d0b4 __raise /usr/src/lib/libc/gen/raise.c:0:10
 #8 0x000000082e6d14f9 abort /usr/src/lib/libc/stdlib/abort.c:67:17
 #9 0x000000082e600871 (/lib/libc.so.7+0x9c871)
#10 0x0000000003045032 (anonymous namespace)::MipsBranchExpansion::handleMFLO() MipsBranchExpansion.cpp:0:0
#11 0x0000000003043565 (anonymous namespace)::MipsBranchExpansion::runOnMachineFunction(llvm::MachineFunction&) MipsBranchExpansion.cpp:0:0
#12 0x0000000003bc9cee llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x3bc9cee)
#13 0x0000000004181a50 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x4181a50)
#14 0x0000000004189ed4 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x4189ed4)
#15 0x0000000004182552 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x4182552)
#16 0x0000000004e92f2f clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x4e92f2f)
#17 0x0000000004eb790d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x4eb790d)
#18 0x000000000636b569 clang::ParseAST(clang::Sema&, bool, bool) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x636b569)
#19 0x00000000052edc93 clang::FrontendAction::Execute() (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x52edc93)
#20 0x0000000005279e3d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x5279e3d)
#21 0x00000000053cdefe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x53cdefe)
#22 0x00000000029e8d64 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x29e8d64)
#23 0x00000000029e58d5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#24 0x00000000029e4b82 clang_main(int, char**, llvm::ToolContext const&) (/home/dim/ins/llvmorg-20-init-12945-ga7427410dd7/bin/clang+0x29e4b82)
Abort trap
```

Minimized test case:

```c
// clang -cc1 -triple mips-- -S -target-cpu mips2 -O1 arc-min-2.c
int l2arc_feed_secs, l2arc_feed_min_ms, l2arc_write_interval_wrote, l2arc_write_interval_next;
void l2arc_write_interval() {
  int interval;
  if (l2arc_write_interval_wrote)
    interval = l2arc_feed_min_ms / l2arc_feed_secs;
  l2arc_write_interval_next = interval;
}
```

See also #118215.

### PR DESCRIPTION
**Pull request by yingopq**
In function handleMFLOSlot, we may get a variable LastInstInFunction with a value of true from function getNextMachineInstr and IInSlot may be null which would trigger an assert.
So we need to skip this case.

Fix #118223.

### CODE REVIEW

**Comment by yingopq** [comment]
@wzssyqa could you help review, thanks!

**Comment by yingopq** [comment]
Ping

**Comment by wzssyqa** [comment]
I think that we need a testcase for it.

File: llvm/lib/Target/Mips/MipsBranchExpansion.cpp [hunk 1]
```diff
@@ -751,9 +751,8 @@ bool MipsBranchExpansion::handleMFLOSlot(Pred Predicate, Safe SafeInSlot) {
   for (MachineFunction::iterator FI = MFp->begin(); FI != MFp->end(); ++FI) {
     for (Iter I = FI->begin(); I != FI->end(); ++I) {
 
-      if (!Predicate(*I) && !hasPendingMFLO) {
+      if (!Predicate(*I) && !hasPendingMFLO)
```
Comment (wzssyqa) [inline llvm/lib/Target/Mips/MipsBranchExpansion.cpp:754]: This change seems not needed.

**Comment by wzssyqa** [comment]
I guess that there may be some other problem: why this patch can effects MIPSr2?
I guess that the default port of FreeBSD is r2？

**Comment by yingopq** [comment]
> I guess that there may be some other problem: why this patch can effects MIPSr2? I guess that the default port of FreeBSD is r2？

We have already made a restriction at the beginning.
```
if (STI->hasMips32() || STI->hasMips5())
    return false;
```

**Comment by yingopq** [comment]
> I guess that there may be some other problem: why this patch can effects MIPSr2? I guess that the default port of FreeBSD is r2？

In file "clang/lib/Driver/ToolChains/Arch/Mips.cpp", have the following define.
```
// MIPS2 is the default for mips(el)?-unknown-freebsd.
  // MIPS3 is the default for mips64(el)?-unknown-freebsd.
  if (Triple.isOSFreeBSD()) {
    DefMips32CPU = "mips2";
    DefMips64CPU = "mips3";
  }
```

File: llvm/lib/Target/Mips/MipsBranchExpansion.cpp (hunk 1 above)
Comment (yingopq) [reply llvm/lib/Target/Mips/MipsBranchExpansion.cpp]: OK, applied.

**Comment by yingopq** [comment]
> I think that we need a testcase for it.

OK, added. Please help review again, thanks@

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 2]
```diff
@@ -0,0 +1,67 @@
+; RUN: llc -filetype=asm < %s -mcpu=mips2 | FileCheck %s -check-prefixes=MIPS2
+;
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:2]: We should keep the IR file simple.
we can use 
```
RUN: llc -filetype=asm --mtriple=mips -mcpu=mips2 < %s | FileCheck %s -check-prefixes=MIPS2
```

So that we won't need 
```
target datalayout = "E-m:m-p:32:32-i8:8:32-i16:16:32-i64:64-n32-S64"
target triple = "mips-unknown-freebsd"
```

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+; int l2arc_feed_secs, l2arc_feed_min_ms, l2arc_write_interval_wrote, l2arc_write_interval_next;
+; void l2arc_write_interval() {
+;   int interval;
+;   if (l2arc_write_interval_wrote)
+;     interval = l2arc_feed_min_ms / l2arc_feed_secs;
+;   l2arc_write_interval_next = interval;
+; }
+
+target datalayout = "E-m:m-p:32:32-i8:8:32-i16:16:32-i64:64-n32-S64"
+target triple = "mips-unknown-freebsd"
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:14]: We can remove these 2 lines.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+
+@l2arc_write_interval_wrote = local_unnamed_addr global i32 0, align 4
+@l2arc_feed_min_ms = local_unnamed_addr global i32 0, align 4
+@l2arc_feed_secs = local_unnamed_addr global i32 0, align 4
+@l2arc_write_interval_next = local_unnamed_addr global i32 0, align 4
+
+; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(readwrite, argmem: none, inaccessiblemem: none)
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:21]: This line can be removed.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+  %2 = load i32, ptr @l2arc_feed_secs, align 4, !tbaa !2
+  %div = sdiv i32 %1, %2
+  br label %if.end
+
+if.end:                                           ; preds = %if.then, %entry
+  %interval.0 = phi i32 [ %div, %if.then ], [ undef, %entry ]
+  store i32 %interval.0, ptr @l2arc_write_interval_next, align 4, !tbaa !2
+  ret void
+}
+
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:55]: The following lines can be removed.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+; MIPS2-NEXT:    lw $1, %lo(l2arc_feed_secs)($1)
+; MIPS2-NEXT:    lui $2, %hi(l2arc_feed_min_ms)
+; MIPS2-NEXT:    lw $2, %lo(l2arc_feed_min_ms)($2)
+; MIPS2-NEXT:    div $zero, $2, $1
+; MIPS2-NEXT:    teq $1, $zero, 7
+; MIPS2-NEXT:    mflo $2
+; MIPS2-NEXT:    j $BB0_3
+; MIPS2-NEXT:    nop
+entry:
+  %0 = load i32, ptr @l2arc_write_interval_wrote, align 4, !tbaa !2
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:40]: We can remove all `, !tbaa !2`

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+  br i1 %tobool.not, label %if.end, label %if.then
+
+if.then:                                          ; preds = %entry
+  %1 = load i32, ptr @l2arc_feed_min_ms, align 4, !tbaa !2
+  %2 = load i32, ptr @l2arc_feed_secs, align 4, !tbaa !2
+  %div = sdiv i32 %1, %2
+  br label %if.end
+
+if.end:                                           ; preds = %if.then, %entry
+  %interval.0 = phi i32 [ %div, %if.then ], [ undef, %entry ]
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:51]: Use `poison` instead of `undef`.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 5 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:55]: OK, because I refer to some other test files that generate .ll from .c, which are all included, I will delete them later.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll [hunk 8]
```diff
@@ -0,0 +1,67 @@
+; RUN: llc -filetype=asm < %s -mcpu=mips2 | FileCheck %s -check-prefixes=MIPS2
+;
+; Created from the following test case (PR121463) with
+; clang -cc1 -triple mips-unknown-freebsd -target-cpu mips2 -O2 -emit-llvm test.c -o test.ll
+; int l2arc_feed_secs, l2arc_feed_min_ms, l2arc_write_interval_wrote, l2arc_write_interval_next;
+; void l2arc_write_interval() {
+;   int interval;
```
Comment (wzssyqa) [inline llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:7]: maybe we should use
```
int interval = l2arc_write_interval_next;
```

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 2 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll:2]: OK, applied.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 3 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll]: OK, applied.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 4 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll]: OK, applied.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 6 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll]: OK, applied.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 5 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll]: OK, applied.

File: llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll (hunk 8 above)
Comment (yingopq) [reply llvm/test/CodeGen/Mips/llvm-ir/sdiv-freebsd.ll]: OK, I initialized the variable `interval` to 0, and it would not produce `undef`.
