### PR TITLE
[clang][bytecode] Revisit reference variables as constexpr-unknown in C++26

### LINKED ISSUE #187775: [Clang] [ByteCode] New constant interpreter rejects member call on object outside its lifetime
Consider (https://godbolt.org/z/dM77oEevY):
```c++
constexpr const char* arr = "1";
struct T { constexpr int a() const { return 42; } };

constexpr const T& f(const T& t) noexcept { return t; }
constexpr int f() {
    const T& range = f(T());
    return [&] consteval { return range.a(); }();
}

static_assert(f() == 42);
```

The old interpreter, GCC, and MSVC accept this code, but the new interpreter errors:
```console
<source>:7:12: error: call to consteval function 'f()::(lambda)::operator()' is not a constant expression
    7 |     return [&] consteval { return range.a(); }();
      |            ^
<source>:7:13: note: initializer of 'range' is not a constant expression
    7 |     return [&] consteval { return range.a(); }();
      |             ^
<source>:6:14: note: declared here
    6 |     const T& range = f(T());
      |              ^
<source>:10:15: error: static assertion expression is not an integral constant expression
   10 | static_assert(f() == 42);
      |               ^~~~~~~~~
<source>:7:41: note: member call on object outside its lifetime is not allowed in a constant expression
    7 |     return [&] consteval { return range.a(); }();
      |                                   ~~~~~~^~~
<source>:7:12: note: in call to '[&] {
    return range.a();
}.operator()()'
    7 |     return [&] consteval { return range.a(); }();
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:10:15: note: in call to 'f()'
   10 | static_assert(f() == 42);
      |               ^~~
<source>:6:24: note: temporary created here
    6 |     const T& range = f(T());
      |                        ^
```

I believe it is correct that `range` is outside its lifetime here (there is no lifetime extension since the reference doesn’t bind directly to the temporary), but afaik this should still be fine since `.a()` doesn’t actually attempt to access any data stored in `range`.

### PR DESCRIPTION
**Pull request by tbaederr**
When revisiting `const T& range = f(T());`, we do mark the variable for `range` as constexpr-unknown, but not the temporary variable we create for `T()`. Change that.

Then we also need to ignore constexpr-unknown pointers in `CheckInvoke()`.

Fixes https://github.com/llvm/llvm-project/issues/187775

### CODE REVIEW

File: clang/test/AST/ByteCode/cxx26.cpp [hunk 1]
```diff
@@ -62,3 +62,14 @@ namespace ExplicitThisInBacktrace {
   static_assert(test()); // both-error {{not an integral constant expression}} \
                          // both-note {{in call to}}
 }
+
+namespace ConstexprUnknownNestedVariables {
```
Comment (shafik) [inline clang/test/AST/ByteCode/cxx26.cpp:66]: Normally we use `GHIssueNumber` when writing tests for a specific GH issue.

**Review by shafik — COMMENTED** [review]
LGTM
