### PR TITLE
[clang-tidy] Fix readability-else-after-return for if statements appear in unbraced switch case labels

### LINKED ISSUE #160033: [clang-tidy] `readability-else-after-return` not detected in `case` blocks
```cpp
void f(int i, bool b)
{
    switch(i)
    {
        case 0:
            if (b) {
                return;
            }
            else {}
        break;
    }
}
```
https://godbolt.org/z/fG1z7b97d

### PR DESCRIPTION
**Pull request by berkaysahiin**
- Updates matcher registration in ElseAfterReturnCheck to also handle switchCase(has(ifStmt(...))) patterns
- Adds a regression test for the unbraced switch-case scenario

Fixes #160033

### CODE REVIEW

**Review by zeyi2 — COMMENTED** [review]
Would you please resolve the conflicts for the CI to run?

File: clang-tools-extra/test/clang-tidy/checkers/readability/else-after-return.cpp [hunk 1]
```diff
@@ -312,3 +312,19 @@ void testPPConditionals() {
...
 }
+
+void testSwitchCaseWithoutInnerCompound(int i, bool b) {
+  switch (i) {
+  case 0:
+    if (b) {
+      return;
+    } else {
+      // CHECK-MESSAGES: :[[@LINE-1]]:7: warning: do not use 'else' after 'return'
+      // CHECK-FIXES: {{^}}    }
```
Comment (zwuis) [inline clang-tools-extra/test/clang-tidy/checkers/readability/else-after-return.cpp]: This check doesn't work. If there is no fix-it, line 325 will be matched. You could refer to other tests in this file.

**Review by zwuis — COMMENTED** [review]
While we are here, how about handling labels (used for `goto`) as well?

---

We should handle fallthrough, which is common. You might write a new matcher to detect it.

```cpp
case 0:
case 1:
// arbitrary number of `case`
```

**Review by localspook — COMMENTED** [review]
> For tests, do you have any documentation you can point me ? Still bit unfamiliar with it

I'm not sure if this is specifically documented somewhere, but the idea is to do something like:

```cpp
if (b) {
  return;
} else { // comment-19
  // CHECK-MESSAGES: :[[@LINE-1]]:7: warning: do not use 'else' after 'return'
  // CHECK-FIXES: {{^}}    } // comment-19
  f(0);
}
```
If the fix-it isn't applied, `// CHECK-FIXES: {{^}}    } // comment-19` won't match any line, and the test will correctly fail.

> Do we need to add a new matcher ? Would something like this be enough ?

I'm wary of that `hasDescendant` in `SwitchCaseWithTargetIf`. I believe it causes a false positive in the following code:
```cpp
switch (1) {
case 1:
case 2:
  if (a == 1)
    f(0);
  else if (a == 2) // <-- We'll match on this `if`.
    return;
  else // <-- So, AFAIK, this 'else' will be incorrectly removed.
    f(1);
}
```

**Review by HerrCai0907 — COMMENTED** [review]
In this case, fix it may not work anymore.

The first version is valid code but the second not.

```c++
void f(int v) {
  switch (v) {
  case 1:
    if (1)
      return;
    else
      int a = 20;
    break;
  case 2:
  }
}
```

```c++
void f(int v) {
  switch (v) {
  case 1:
    if (1)
      return;
    int a = 20;
    break;
  case 2:
  }
}
```

**Review by localspook — APPROVED** [review]
LGTM!

**Comment by LegalizeAdulthood** [comment]
Thanks for the fix!
