### PR TITLE
[clang-tidy] Fix a false positive when converting a bool to a signed integer type

### LINKED ISSUE #191337: [bugprone-narrowing-conversions] False positive for `bool` to `char` conversion
For the following code ([CE](https://godbolt.org/z/YsTo5rhbq)):

```cpp
void test(bool b) {
  auto c = char{b};
}
```

Clang-Tidy warns:

```cpp
<source>:2:17: warning: narrowing conversion from 'bool' to signed type 'char' is implementation-defined [bugprone-narrowing-conversions]
    2 |   auto c = char{b};
      |                 ^
```

However, for this conversion, the standard mandates ([[conv.integral]/2](https://eel.is/c++draft/conv.integral#2.sentence-2)):

> [...] If the source type is `bool`, the value `false` is converted to zero and the value `true` is converted to one.

So no narrowing occurs here.

### PR DESCRIPTION
**Pull request by maochuanjun**
Fix #191337

### CODE REVIEW

**Comment by maochuanjun** [comment]
@zeyi2 please take a look when free,thanks

File: clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp [hunk 1]
```diff
@@ -402,6 +402,9 @@ void NarrowingConversionsCheck::handleIntegralCast(const ASTContext &Context,
       return;
     const BuiltinType *FromType = getBuiltinType(Rhs);
 
+    if (FromType->getKind() == BuiltinType::Bool)
```
Comment (zeyi2) [inline clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: I understand that this is correct, but IIUC there is already a dedicated handler for bool-to-signed-integral conversions in [`handleBooleanToSignedIntegral`](https://github.com/llvm/llvm-project/blob/b7febd772c57fc21a126a8e125d749df9e4a6a53/clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp#L484).

Would it make more sense to route this case there from the [`CK_IntegralCast`](https://github.com/llvm/llvm-project/blob/b7febd772c57fc21a126a8e125d749df9e4a6a53/clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp#L596) path instead of "special-casing" it here?

Comment (zeyi2) [reply clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: Also we already do similar dispatch in https://github.com/llvm/llvm-project/blob/b7febd772c57fc21a126a8e125d749df9e4a6a53/clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp#L522

Comment (maochuanjun) [reply clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.cpp]: like this？

**Review by zeyi2 — APPROVED** [review]

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions.cpp [hunk 2]
```diff
@@ -355,4 +355,12 @@ void typedef_context() {
   // CHECK-MESSAGES: :[[@LINE-1]]:7: warning: narrowing conversion from 'myint64_t' (aka 'long long') to signed type 'int' is implementation-defined [bugprone-narrowing-conversions]
 }
 
+void testBoolToSignedType() {
+  bool b = true;
```
Comment (vbvictor) [inline clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions.cpp:359]: Can we add these tests as well if not already present
```cpp
  auto c1 = static_cast<char>(b);
  auto c2 = (char)b;
```

**Review by vbvictor — APPROVED** [review]
lgtm

File: clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions.cpp (hunk 2 above)
Comment (maochuanjun) [reply clang-tools-extra/test/clang-tidy/checkers/bugprone/narrowing-conversions.cpp:359]: ok,already add
