### PR TITLE
[clang] Allow class with anonymous union member to be const-default-constructible even if a union member has a default member initializer (#95854)

### LINKED ISSUE #95854: Clang incorrectly considers a class with an anonymous union member to not be const-default-constructible even if a union member has a default member initializer
Testcase:
```c++
struct A {
  union {
    int n = 0;
    int m;
  };
};
const A a;
```
This is valid, but Clang rejects:
```console
<source>:7:9: error: default initialization of an object of const type 'const A' without a user-provided default constructor
```
(Clang accepts if `m` is removed.) See https://eel.is/c++draft/dcl.init#general-8.3 -- because `n` has an initializer, the entire anonymous union is treated as initialized.

### PR DESCRIPTION
**Pull request by Rajveer100**
Resolves #95854

-- As per https://eel.is/c++draft/dcl.init#general-8.3

### CODE REVIEW

**Comment by Rajveer100** [comment]
@zygoloid

**Review by shafik — COMMENTED** [review]
Thank you for this fix. It needs a release note and your summary should have some more details on what the cause of the bug is and how your PR fixes it. efriedma-quic's comment provides a good framework for explaining the cause.

It also looks like your change broke some tests:

```console
Clang :: AST/Interp/records.cpp
Clang :: SemaCXX/cxx0x-cursory-default-delete.cpp
```

Are these expected breaks? If so then please update these tests

File: clang/include/clang/AST/DeclCXX.h [hunk 1]
```diff
@@ -1392,7 +1392,8 @@ class CXXRecordDecl : public RecordDecl {
   bool allowConstDefaultInit() const {
     return !data().HasUninitializedFields ||
            !(data().HasDefaultedDefaultConstructor ||
-             needsImplicitDefaultConstructor());
+             needsImplicitDefaultConstructor()) ||
+           hasInClassInitializer();
```
Comment (shafik) [inline clang/include/clang/AST/DeclCXX.h:1396]: Based on the comment in the bug report I think this needs to be `(isUnion() && hasInClassInitializer())`

File: clang/test/Sema/debug-95854.cpp [hunk 2]
```diff
@@ -0,0 +1,11 @@
+// RUN: %clang_cc1 -std=c++23 -fsyntax-only -verify %s
```
Comment (shafik) [inline clang/test/Sema/debug-95854.cpp:1]: I think this may be a more appropriate place for the test:

https://github.com/llvm/llvm-project/blob/main/clang/test/SemaCXX/anonymous-union.cpp

We usually wrap tests from github issues in a namespace starting with `GH` and followed by the issue number for this case `namespace GH95854`

File: clang/include/clang/AST/DeclCXX.h (hunk 1 above)
Comment (zygoloid) [reply clang/include/clang/AST/DeclCXX.h:1396]: What happens for:

```
struct A {
  union {
    struct {
      int n = 5;
      int m;
    };
  };
};
const A a;
```

This is a language extension so we get to choose its semantics, but I think the most logical choice is to reject because the union member is not *fully* initialized.

Comment (Rajveer100) [reply clang/include/clang/AST/DeclCXX.h:1396]: > This is a language extension so we get to choose its semantics, but I think the most logical choice is to reject because the union member is not _fully_ initialized.

At the moment, this gets accepted.

File: clang/test/Sema/debug-95854.cpp (hunk 2 above)
Comment (Rajveer100) [reply clang/test/Sema/debug-95854.cpp:1]: Indeed.

File: clang/include/clang/AST/DeclCXX.h (hunk 1 above)
Comment (Rajveer100) [reply clang/include/clang/AST/DeclCXX.h:1396]: The two tests that were broken:

```c++
struct some_init {
  int a = 0;
  int b;
  int c = 0;
};

void constobjs() {
  // ...
  const some_init si;
  // ...
}
```

```c++
struct Ints2 {
  int a = 10;
  int b;
};
constexpr Ints2 ints22;
```

Comment (Rajveer100) [reply clang/include/clang/AST/DeclCXX.h]: @zygoloid 
Is there an existing method for checking nested structures for cases like you mentioned above?

Comment (zygoloid) [reply clang/include/clang/AST/DeclCXX.h]: I don't think so. Maybe we can change the behavior of `HasUninitializedFields` -- it only exists to support this check, so we can change it to do whatever this check needs. What I'm thinking is:

* If the class is not a union, then proceed as we currently do: start it off as `false` and set it to `true` if we find an uninitialized field.
* If the class is a union, then do the opposite: start it off as `true` and set it to `false` if we find an initialized field.

(So for a non-union, the field is true if all fields are const default initializable, and for a union, the field is true if *any* field is const default initializable.)

Then I think the only change we'd need here would be to also treat empty unions as const default initializable.

Comment (ofAlpaca) [reply clang/include/clang/AST/DeclCXX.h]: Hi @zygoloid 
I apologize if it's a silly question, I'm new here and want to learn something from you.
@Rajveer100's commit has already fixed the test (GH95854.cpp).
> The two tests that were broken:

And these two mentioned testcases' errors are expected. The behavior of the fix is correct.
Then, what are you planning to do next?
Are you planning to improve the code by changing the behavior of `HasUninitializedFields`?

**Comment by Rajveer100** [comment]
@zygoloid 
Let me know if the new changes work well.

**Comment by Rajveer100** [comment]
cc @cor3ntin @shafik @Sirraide

**Comment by Rajveer100** [comment]
@zygoloid 
Could you review this?

File: clang/test/SemaCXX/GH95854.cpp [hunk 3]
```diff
@@ -0,0 +1,21 @@
+// RUN: %clang_cc1 -std=c++23 -fsyntax-only -verify %s
+//
+// -expected-no-diagnostics
```
Comment (jrtc27) [inline clang/test/SemaCXX/GH95854.cpp:3]: ?

File: clang/docs/ReleaseNotes.rst [hunk 4]
```diff
@@ -217,6 +217,11 @@ Bug Fixes to C++ Support
 - Clang now preserves the unexpanded flag in a lambda transform used for pack expansion. (#GH56852), (#GH85667),
   (#GH99877).
 - Fixed a bug when diagnosing ambiguous explicit specializations of constrained member functions.
+- Clang incorrectly considers a class with an anonymous union member to not be
+  const-default-constructible even if a union member has a default member initializer.
+  This is valid as per ``8.3`` in `Draft C++ Standard <https://eel.is/c++draft/dcl.init#general-8.3>`_.
+  The ``allowConstDefaultInit`` member function in ``CXXRecordDecl`` needs
+  special-case unions to handle the rule. (#GH95854).
```
Comment (Sirraide) [inline clang/docs/ReleaseNotes.rst:224]:
```suggestion
  (#GH95854).
```
I don’t think any of that needs to be here.

File: clang/include/clang/AST/DeclCXX.h [hunk 5]
```diff
@@ -1395,7 +1395,8 @@ class CXXRecordDecl : public RecordDecl {
   bool allowConstDefaultInit() const {
     return !data().HasUninitializedFields ||
            !(data().HasDefaultedDefaultConstructor ||
-             needsImplicitDefaultConstructor());
+             needsImplicitDefaultConstructor()) ||
+           (isUnion() && isEmpty());
```
Comment (Sirraide) [inline clang/include/clang/AST/DeclCXX.h:1399]: Er, why do we special-case empty unions here? Shouldn’t that just work automatically because an empty union has no fields at all and therefore no uninitialised fields either?

**Review by Sirraide — COMMENTED** [review]
I think the changes generally make sense.

**Comment by Rajveer100** [comment]
@Sirraide The tests pass, not sure about the failure though.

**Review by shafik — COMMENTED** [review]
I don't think the test failures look related to the changes can you push and empty change to see if rerunning the tests comes up clean?

**Comment by Rajveer100** [comment]
Only windows failed.

File: clang/lib/AST/DeclCXX.cpp [hunk 6]
```diff
@@ -1125,7 +1128,11 @@ void CXXRecordDecl::addedMember(Decl *D) {
         data().DefaultedCopyConstructorIsDeleted = true;
     }
 
-    if (!Field->hasInClassInitializer() && !Field->isMutable()) {
+    if (isUnion() && !Field->isMutable()) {
+      if (Field->hasInClassInitializer()) {
+        data().HasUninitializedFields = false;
+      }
```
Comment (cor3ntin) [inline clang/lib/AST/DeclCXX.cpp:1134]:
```suggestion
      if (Field->hasInClassInitializer())
        data().HasUninitializedFields = false;
```

File: clang/docs/ReleaseNotes.rst [hunk 7]
```diff
@@ -318,6 +318,9 @@ Bug Fixes to C++ Support
   of the current instantiation in all cases.
 - Fix evaluation of the index of dependent pack indexing expressions/types specifiers (#GH105900)
 - Correctly handle subexpressions of an immediate invocation in the presence of implicit casts. (#GH105558)
+- Clang incorrectly considers a class with an anonymous union member to not be
```
Comment (cor3ntin) [inline clang/docs/ReleaseNotes.rst:321]:
```suggestion
- Clang incorrectly considered a class with an anonymous union member to not be
```

**Review by cor3ntin — COMMENTED** [review]
Here are more tests to consider https://godbolt.org/z/M6fj5zTfq 
Thanks!

**Comment by Rajveer100** [comment]
@cor3ntin 
CI looks good.

**Comment by cor3ntin** [comment]
Neither GCC, EDG nor MSVC agree with us https://godbolt.org/z/Wqrhnz63a
The behavior of GCC is a bit weird but I am pretty sure the last two tests should pass
@hubert-reinterpretcast

File: clang/test/SemaCXX/GH95854.cpp [hunk 8]
```diff
@@ -0,0 +1,43 @@
+// RUN: %clang_cc1 -std=c++23 -fsyntax-only -verify %s
+
+struct A {
```
Comment (shafik) [inline clang/test/SemaCXX/GH95854.cpp:3]: We should also test this case: 

```cpp
struct A {
  union {
    int n;
    int m=0;
  };
};
const A a;
```

Comment (Rajveer100) [reply clang/test/SemaCXX/GH95854.cpp:3]: Added.

**Review by cor3ntin — APPROVED** [review]
LGTM, Thanks!
Give a couple of days to @shafik before merging

**Comment by Rajveer100** [comment]
Thanks for the approval @cor3ntin, could you land this for me?!

**Comment by Rajveer100** [comment]
@Sirraide
