### PR TITLE
[libc++] Fix flat_{multi}set insert_range

### LINKED ISSUE #136656: `std::flat_set` dispatches non-c++17 iterators to container's `insert(const_iterator, InputIterator, InputIterator)`
```cpp
#include <flat_set>
#include <iterator>
#include <sstream>
#include <ranges>
#include <boost/interprocess/containers/vector.hpp>
 
int main() {
  boost::container::vector<int> v;
  std::flat_set s(v);
  std::istringstream ints("0 1 1 0");
  auto r = std::ranges::subrange(std::istream_iterator<int>(ints),
                                 std::istream_iterator<int>())
         | std::views::transform([](int i) { return i * i; });
  s.insert_range(r);
}
```
https://godbolt.org/z/6P3rnod76

### PR DESCRIPTION
**Pull request by huixie90**
fixes #136656

### CODE REVIEW

File: libcxx/include/__flat_set/utils.h [hunk 1]
```diff
@@ -60,7 +61,8 @@ struct __flat_set_utils {
       // C++23 Sequence Container should have insert_range member function
       // Note that not all Sequence Containers provide append_range.
       __set.__keys_.insert_range(__set.__keys_.end(), std::forward<_Range>(__rng));
-    } else if constexpr (ranges::common_range<_Range>) {
+    } else if constexpr (ranges::common_range<_Range> &&
+                         __has_input_iterator_category<ranges::iterator_t<_Range>>::value) {
```
Comment (frederick-vs-ja) [inline libcxx/include/__flat_set/utils.h:65]: No (functional) change requested. Do we want to say the fallback branches are (pedantically) extensions?

Comment (frederick-vs-ja) [reply libcxx/include/__flat_set/utils.h:65]: On the other hand, it seems that the missing parts of `MinSequenceContainer` for C++23 sequence container requirements "silently" enforced our `flat_meow` to contain some extensions.

Comment (frederick-vs-ja) [reply libcxx/include/__flat_set/utils.h:65]: Ah, I guess these cases should be moved to the `libcxx/test/libcxx` subdirectory.

File: libcxx/test/libcxx/containers/container.adaptors/flat.multiset/insert_range.pass.cpp [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+// UNSUPPORTED: c++03, c++11, c++14, c++17, c++20
+// UNSUPPORTED: no-localization
+
+// <flat_set>
+
+// https://github.com/llvm/llvm-project/issues/136656
```
Comment (ldionne) [inline libcxx/test/libcxx/containers/container.adaptors/flat.multiset/insert_range.pass.cpp:14]:
```suggestion
// As an extension, libc++ flat containers support inserting a non forward range into
// a pre-C++23 container that doesn't provide insert_range(...), since many containers
// out there are in that situation.
// https://github.com/llvm/llvm-project/issues/136656
```

File: libcxx/test/libcxx/containers/container.adaptors/flat.set/insert_range.pass.cpp [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+//
+//===----------------------------------------------------------------------===//
+
+// UNSUPPORTED: c++03, c++11, c++14, c++17, c++20
+// UNSUPPORTED: no-localization
+
+// <flat_set>
+
+// https://github.com/llvm/llvm-project/issues/136656
```
Comment (ldionne) [inline libcxx/test/libcxx/containers/container.adaptors/flat.set/insert_range.pass.cpp:14]:
```suggestion
// As an extension, libc++ flat containers support inserting a non forward range into
// a pre-C++23 container that doesn't provide insert_range(...), since many containers
// out there are in that situation.
// https://github.com/llvm/llvm-project/issues/136656
```

**Review by ldionne — APPROVED** [review]
LGTM but I'd like a LWG issue about it.

**Review by ldionne — APPROVED** [review]
