### PR TITLE
[llvm-lit] Fix error in compiler-rt tests when using lit internal shell with env

### LINKED ISSUE #106598: [llvm-lit] Environment variable not found in compiler-rt subproject with lit internal shell
Currently, there are multiple environment variables are not recognized within the compiler-rt subproject, resulting in test failures when using the lit internal shell.
**Example error message:**
```
'XRAY_OPTIONS=patch_premain=false': command not found
```
This error indicates that the internal shell is misinterpreting environment variable assignments as commands, leading to these failures.

files with failures:

- [x] compiler-rt/test/dfsan/custom.cpp
- [x] compiler-rt/test/dfsan/flags.c
- [x] compiler-rt/test/dfsan/fork.cpp
- [x] compiler-rt/test/dfsan/origin_limit.c
- [x] compiler-rt/test/msan/Linux/sendmsg.cpp 
- [x] compiler-rt/test/msan/chained_origin_empty_stack.cpp
- [x] compiler-rt/test/msan/chained_origin_limits.cpp
- [x] compiler-rt/test/msan/coverage-levels.cpp
- [x] compiler-rt/test/msan/dtor-member.cpp
- [x] compiler-rt/test/msan/fork.cpp
- [x] compiler-rt/test/msan/interception_sigaction_test.cpp
- [x] compiler-rt/test/msan/memcmp_test.cpp 
- [x] compiler-rt/test/msan/msan_check_mem_is_initialized.cpp
- [x] compiler-rt/test/msan/poison_in_free.cpp
- [x] compiler-rt/test/msan/print_stats.cpp
- [x] compiler-rt/test/msan/recover-dso.cpp
- [x] compiler-rt/test/msan/recover.cpp
- [x] compiler-rt/test/msan/release_origin.c 
- [x] compiler-rt/test/msan/strcmp.c
- [x] compiler-rt/test/msan/strndup.cpp
- [x] compiler-rt/test/profile/Linux/instrprof-comdat.test
- [x] compiler-rt/test/sanitizer_common/TestCases/Linux/signal_segv_handler.cpp
- [x] compiler-rt/test/ubsan/TestCases/Misc/Linux/static-link.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/arg1-arg0-logging.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/arg1-logger.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/arg1-logging-implicit-this.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/argv0-log-file-name.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/coverage-sample.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/fdr-reinit.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/fixedsize-logging.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/func-id-utils.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/optional-inmemory-log.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/patching-unpatching.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/pic_test.cpp
- [x] compiler-rt/test/xray/TestCases/Posix/typed-event-logging.cpp
- [x] compiler-rt/test/nsan/Posix/tls_reuse.c
- [x] compiler-rt/test/nsan/nan.cpp
- [x] compiler-rt/test/nsan/softmax.cpp
- [x] compiler-rt/test/nsan/sum.cpp
- [x] compiler-rt/test/nsan/vec_sqrt_ext.cpp
- [x] compiler-rt/test/fuzzer/out-of-process-fuzz.test
- [x] compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_allowlist_ignorelist.cpp
- [x] compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_symbolize.cpp
- [x] compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_trace_pc_guard-dso.cpp
- [x] compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_trace_pc_guard-init.cpp
- [x] compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_trace_pc_guard.cpp
- [x] compiler-rt/test/nsan/vec_sqrt.cpp
- [ ] compiler-rt/test/xray/TestCases/Posix/fdr-single-thread.cpp

### PR DESCRIPTION
**Pull request by Harini0924**
When running tests in compiler-rt using the lit internal shell with the following command:
```
LIT_USE_INTERNAL_SHELL=1 ninja check-compiler-rt
```
one common error that occurs is:
```
'XRAY_OPTIONS=patch_premain=false:verbosity=1': command not found
```
This error, along with over 50 similar "environment variable not found" errors, appears across 35 files in complier-rt. These errors happen because the environment variables are not being set correctly when the internal shell is used, leading to commands failing due to unrecognized environment variables.

This patch addresses the issue by using the `env` command to properly set the environment variables before running the tests. By explicitly setting the environment variables through `env`, the internal shell can correctly interpret and apply them, allowing the tests to pass.
fixes: #106598
[link to RFC](https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179)

### CODE REVIEW

**Comment by Harini0924** [comment]
CC: @ilovepi @petrhosek

File: compiler-rt/test/msan/poison_in_free.cpp [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // RUN: %clangxx_msan -O0 %s -o %t && not %run %t >%t.out 2>&1
 // FileCheck %s <%t.out
-// RUN: %clangxx_msan -O0 %s -o %t && MSAN_OPTIONS=poison_in_free=0 %run %t >%t.out 2>&1
+// RUN: %clangxx_msan -O0 %s -o %t && env env MSAN_OPTIONS=poison_in_free=0 %run %t >%t.out 2>&1
```
Comment (ilovepi) [inline compiler-rt/test/msan/poison_in_free.cpp:3]: typo?
```suggestion
// RUN: %clangxx_msan -O0 %s -o %t && env MSAN_OPTIONS=poison_in_free=0 %run %t >%t.out 2>&1
```

**Review by ilovepi — COMMENTED** [review]
LGTM, modulo a typo, but lets let compiler-rt code owners weigh in.

Also, please update the title and description to note that this occurs when using llvm-lit's internal shell. Referencing the RFC and any tracking bugs wouldn't be amiss either.

File: compiler-rt/test/msan/poison_in_free.cpp (hunk 1 above)
Comment (Harini0924) [reply compiler-rt/test/msan/poison_in_free.cpp:3]: Yes, I will fix that right now. Thank you!

**Comment by vitalybuka** [comment]
How did you get to the issue?
We run these test on bots and locally, and see no issue.

Please add that into description.

Also please address clang-format complains.

**Review by vitalybuka — APPROVED** [review]

**Comment by MaskRay** [comment]
`VAR=a command` is so commonly used that perhaps the internal lit shell should be taught this syntax.
Then we can avoid these changes.

**Comment by vitalybuka** [comment]
> `VAR=a command` is so commonly used that perhaps the internal lit shell should be taught this syntax. Then we can avoid these changes.

Are you asking to block the patch?
It's looks good to me regardless of lit improvement.

**Comment by ilovepi** [comment]
> `VAR=a command` is so commonly used that perhaps the internal lit shell should be taught this syntax. Then we can avoid these changes.

While I think it would be nice if `llvm-lit` handled this more gracefully, its already has a standard way to handle this via `env`, which I think (and forgive me if I'm mistaken here) works better w/ older shells, like `sh`, `csh`, `ksh`, etc.  Plus, `env` is already used pretty pervasively across LLVM, so I'm not seeing how this change isn't desirable on its own,  especially given that it allows the tests to run in more environments. 

You noted in https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179/20 that some improvements to `llvm-lit` aren't essential to change the default. This type of test fixing would seem to fall under that. If you feel strongly about your POV, then we should probably move the discussion to the RFC thread on discourse to solicit more feedback from the community.
