### PR TITLE
[clang-format] Handle doxygen commands starting with \

### LINKED ISSUE #63241: Clang-format fails to correctly format doxygen comments with \ as keyword starters
Hey

If I run Clang-Format on i.e.
```cpp
  /** \brief Convert a PCLPointCloud2 binary data blob into a pcl::PointCloud<T> object using a field_map.
    * \param[in] msg the PCLPointCloud2 binary blob (note that the binary point data in msg.data will not be used!)
    * \param[out] cloud the resultant pcl::PointCloud<T>
    * \param[in] field_map a MsgFieldMap object
    * \param[in] msg_data pointer to binary blob data, used instead of msg.data
    *
    * \note Use fromPCLPointCloud2 (PCLPointCloud2, PointCloud<T>) instead, except if you have a binary blob of I just want to test so this doesn't get moved around.
    * point data that you do not want to copy into a pcl::PCLPointCloud2 in order to use fromPCLPointCloud2.
    */
```
its formatted into:
```cpp
  /** \brief Convert a PCLPointCloud2 binary data blob into a pcl::PointCloud<T> object
   * using a field_map. \param[in] msg the PCLPointCloud2 binary blob (note that the
   * binary point data in msg.data will not be used!) \param[out] cloud the resultant
   * pcl::PointCloud<T> \param[in] field_map a MsgFieldMap object \param[in] msg_data
   * pointer to binary blob data, used instead of msg.data
   *
   * \note Use fromPCLPointCloud2 (PCLPointCloud2, PointCloud<T>) instead, except if you
   * have a binary blob of I just want to test so this doesn't get moved around. point
   * data that you do not want to copy into a pcl::PCLPointCloud2 in order to use
   * fromPCLPointCloud2.
   */
```

but if @ is used instead of \ :
```cpp
  /** @brief Convert a PCLPointCloud2 binary data blob into a pcl::PointCloud<T> object using a field_map.
    * @param[in] msg the PCLPointCloud2 binary blob (note that the binary point data in msg.data will not be used!)
    * @param[out] cloud the resultant pcl::PointCloud<T>
    * @param[in] field_map a MsgFieldMap object
    * @param[in] msg_data pointer to binary blob data, used instead of msg.data
    *
    * @note Use fromPCLPointCloud2 (PCLPointCloud2, PointCloud<T>) instead, except if you have a binary blob of I just want to test so this doesn't get moved around.
    * point data that you do not want to copy into a pcl::PCLPointCloud2 in order to use fromPCLPointCloud2.
    */
```

Its formatted correctly like this:
```cpp
  /** @brief Convert a PCLPointCloud2 binary data blob into a pcl::PointCloud<T> object
   * using a field_map.
   * @param[in] msg the PCLPointCloud2 binary blob (note that the binary point data in
   * msg.data will not be used!)
   * @param[out] cloud the resultant pcl::PointCloud<T>
   * @param[in] field_map a MsgFieldMap object
   * @param[in] msg_data pointer to binary blob data, used instead of msg.data
   *
   * @note Use fromPCLPointCloud2 (PCLPointCloud2, PointCloud<T>) instead, except if you
   * have a binary blob of I just want to test so this doesn't get moved around. point
   * data that you do not want to copy into a pcl::PCLPointCloud2 in order to use
   * fromPCLPointCloud2.
   */
```

Is this intentional - can we do some setting that makes it work with \ and @ - I think unfortunately both versions has been used.
Thanks, Lars

Ref: https://github.com/PointCloudLibrary/pcl/pull/5724

### PR DESCRIPTION
**Pull request by XDeme1**
Fixes llvm/llvm-project#63241

Doxygen commands can start with `@` or `\`.

### CODE REVIEW

File: clang/unittests/Format/FormatTestComments.cpp [hunk 1]
```diff
@@ -1909,6 +1909,14 @@ TEST_F(FormatTestComments, ReflowsComments) {
                    "// @param arg",
                    getLLVMStyleWithColumns(20)));
 
+  // Don't reflow lines starting with '\'.
+  EXPECT_EQ("// long long long\n"
```
Comment (owenca) [inline clang/unittests/Format/FormatTestComments.cpp:1913]: Can you use `verifyFormat` or `verifyNoChange` instead?

File: clang/unittests/Format/FormatTestComments.cpp [hunk 2]
```diff
@@ -1909,6 +1909,14 @@ TEST_F(FormatTestComments, ReflowsComments) {
...
+            "// long\n"
+            "// \\param arg",
+            format("// long long long long\n"
+                   "// \\param arg",
+                   getLLVMStyleWithColumns(20)));
```
Comment (owenca) [inline clang/unittests/Format/FormatTestComments.cpp:1918]: Redundant?

**Review by owenca — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]
