### PR TITLE
[PowerPC] Fix incorrect store alignment for __builtin_vsx_build_pair()

### LINKED ISSUE #107229: [PowerPC] Incorrect store alignment with __builtin_vsx_build_pair() builtin.
Function test2 from https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/PowerPC/builtins-ppc-build-pair-mma.c generates this pre-optimization IR:

```llvm
define dso_local void @test2(ptr noundef %vqp, ptr noundef %vpp, <16 x i8> noundef %vc1, <16 x i8> noundef %vc2, ptr noundef %resp) #0 {
entry:
  %vqp.addr = alloca ptr, align 8
  %vpp.addr = alloca ptr, align 8
  %vc1.addr = alloca <16 x i8>, align 16
  %vc2.addr = alloca <16 x i8>, align 16
  %resp.addr = alloca ptr, align 8
  %vq = alloca <512 x i1>, align 64
  %vp = alloca <256 x i1>, align 32
  %res = alloca <256 x i1>, align 32
  store ptr %vqp, ptr %vqp.addr, align 8, !tbaa !2
  store ptr %vpp, ptr %vpp.addr, align 8, !tbaa !2
  store <16 x i8> %vc1, ptr %vc1.addr, align 16, !tbaa !6
  store <16 x i8> %vc2, ptr %vc2.addr, align 16, !tbaa !6
  store ptr %resp, ptr %resp.addr, align 8, !tbaa !2
  call void @llvm.lifetime.start.p0(i64 64, ptr %vq) #3
  %0 = load ptr, ptr %vqp.addr, align 8, !tbaa !2
  %1 = load <512 x i1>, ptr %0, align 64, !tbaa !7
  store <512 x i1> %1, ptr %vq, align 64, !tbaa !7
  call void @llvm.lifetime.start.p0(i64 32, ptr %vp) #3
  %2 = load ptr, ptr %vpp.addr, align 8, !tbaa !2
  %3 = load <256 x i1>, ptr %2, align 32, !tbaa !9
  store <256 x i1> %3, ptr %vp, align 32, !tbaa !9
  call void @llvm.lifetime.start.p0(i64 32, ptr %res) #3
  %4 = load <16 x i8>, ptr %vc1.addr, align 16, !tbaa !6
  %5 = load <16 x i8>, ptr %vc2.addr, align 16, !tbaa !6
  %6 = call <256 x i1> @llvm.ppc.vsx.assemble.pair(<16 x i8> %5, <16 x i8> %4)
  store <256 x i1> %6, ptr %res, align 64
  %7 = load <256 x i1>, ptr %res, align 32, !tbaa !9
  %8 = load ptr, ptr %resp.addr, align 8, !tbaa !2
  store <256 x i1> %7, ptr %8, align 32, !tbaa !9
  call void @llvm.lifetime.end.p0(i64 32, ptr %res) #3
  call void @llvm.lifetime.end.p0(i64 32, ptr %vp) #3
  call void @llvm.lifetime.end.p0(i64 64, ptr %vq) #3
  ret void
}
```

Note that ` store <256 x i1> %6, ptr %res, align 64` performs a 64 aligned store of a 32 byte type to a 32 aligned alloca. Pretty sure this was supposed to get alignment 32.

I think this is due to the hardcoded 64 alignment in https://github.com/llvm/llvm-project/blob/c2b92a4250b3f514685676ba8985ea73450f14d3/clang/lib/CodeGen/CGBuiltin.cpp#L18219.

### PR DESCRIPTION
**Pull request by lei137**
Fixes #107229

### CODE REVIEW

File: clang/lib/CodeGen/CGBuiltin.cpp [hunk 1]
```diff
@@ -18197,7 +18197,7 @@ Value *CodeGenFunction::EmitPPCBuiltinExpr(unsigned BuiltinID,
       CallOps.push_back(Ops[i]);
     llvm::Function *F = CGM.getIntrinsic(ID);
     Value *Call = Builder.CreateCall(F, CallOps);
-    return Builder.CreateAlignedStore(Call, Ops[0], MaybeAlign(64));
+    return Builder.CreateAlignedStore(Call, Ops[0], MaybeAlign());
```
Comment (nikic) [inline clang/lib/CodeGen/CGBuiltin.cpp:18200]:
```suggestion
    return Builder.CreateStore(Call, Ops[0]);
```
Should work, I think? No need to use CreateAlignedStore if you want a naturally aligned store.

Comment (efriedma-quic) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: I'd prefer to just explicitly write the expected alignment here, though; LLVM DataLayout rules for alignment can be a bit strange.

Comment (lei137) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: > I'd prefer to just explicitly write the expected alignment here,

@efriedma-quic  Do you mean like hard code the expected alignment?

Currently `CreateAlignedStore(Call, Ops[0], MaybeAlign());` calls:
```
StoreInst *CreateAlignedStore(Value *Val, Value *Ptr, MaybeAlign Align,
                                bool isVolatile = false) {
    if (!Align) {
      const DataLayout &DL = BB->getDataLayout();
      Align = DL.getABITypeAlign(Val->getType());
    }
    return Insert(new StoreInst(Val, Ptr, isVolatile, *Align));
  }
```
and get the proper ABI alignment for the type given.  Since this section of code process types that are either 32bit or 64bit aligned, we can't hard code any alignment here.

Comment (efriedma-quic) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: Oh, didn't realize there were multiple different types coming through here.  It's not worth it to duplicate the implementation of CreateStore... @nikic suggestion is fine, then.

Comment (lei137) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: @nikic Using `CreateStore(Value, Address)` will require extra code to convert`Ops[0[` to type `Address`.

Comment (nikic) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: Ah, it looks like CGBuilder doesn't directly re-export this IRBuilder API, it's called CreateDefaultAlignedStore() instead.

Comment (lei137) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: I see a FIXME for this function, do we still want to use it?
```
  // FIXME: these "default-aligned" APIs should be removed,
  // but I don't feel like fixing all the builtin code right now.
  llvm::StoreInst *CreateDefaultAlignedStore(llvm::Value *Val,
                                             llvm::Value *Addr,
                                             bool IsVolatile = false) 
```
Since these need to be aligned stores, maybe it's more clear to just use `CreateAlignedStore()`?
The patch that added this FIXME:
```
commit 7f416cc426384ad1f891addb61d93e7ca1ffa0f2
Author: John McCall <rjmccall@apple.com>
Date:   Tue Sep 8 08:05:57 2015 +0000
```
Explicitly asks:
```
    I partially punted on applying this work to CGBuiltin.  Please
    do not add more uses of the CreateDefaultAligned{Load,Store}
    APIs; they will be going away eventually.

    llvm-svn: 246985
```
It is an old patch so I am not sure how much of that is still true...

Comment (efriedma-quic) [reply clang/lib/CodeGen/CGBuiltin.cpp:18200]: Oh, right, I forgot we were trying to get rid of those at one point... that's probably never happening for LLVM in general, but maybe for clang it'll get finished at some point.

Looking at the code again, it's calling EmitPointerWithAlignment, so you can just take the alignment from that.  Well, actually, it looks like there's a bug where we emit the first argument twice, but with that fixed, you should be able to do that.

**Review by nikic — APPROVED** [review]
LGTM, don't think exactly how the builder call looks like here is important...

**Comment by nemanjai** [comment]
Will this affect the code that is generated for ‘__vector_quad’ values? There is no direct way to load and store those so they will use pair loads and stores.

**Comment by lei137** [comment]
> Will this affect the code that is generated for ‘__vector_quad’ values? There is no direct way to load and store those so they will use pair loads and stores.

Not AFAIK. The change will get the alignment from the type given. The LIT test being updated also have `alloca` and `store` of vector quads.  The alignment for those instructions stayed 64bit.
