### PR TITLE
[BPF] Handle aliases in CodeGenModule::EmitExternalDeclaration. Fixes #192365

### LINKED ISSUE #192365: EmitExternalDeclaration doesn't handle function aliases
Clang crashes on the following input (https://gcc.godbolt.org/z/qTM168qe7):

```c++
extern "C" void e() {}
void __attribute__((alias("e"))) __cat_op0();
void r() { __cat_op0(); }
```

```
clang -cc1 -triple bpfel -emit-llvm -debug-info-kind=constructor -o /dev/null /tmp/q.cc
assert.h assertion failed at llvm/include/llvm/Support/Casting.h:572 in decltype(auto) llvm::cast(From *) [To = llvm::Function, From = llvm::Constant]: isa<To>(Val) && "cast<Ty>() argument of incompatible type!"
    @     0x5655561d107a  __assert_fail
    @     0x565544ea3edb  llvm::cast<>()
    @     0x5655459a05ed  clang::CodeGen::CodeGenModule::EmitExternalDeclaration()
    @     0x565545dd80ef  (anonymous namespace)::CodeGeneratorImpl::CompleteExternalDeclaration()
    @     0x565544d8dd32  clang::BackendConsumer::CompleteExternalDeclaration()
    @     0x565548489929  clang::Sema::ActOnEndOfTranslationUnit()
    @     0x565547cd18d6  clang::Parser::ParseTopLevelDecl()
    @     0x565547cb16c6  clang::ParseAST()
    @     0x56554790f0c5  clang::ASTFrontendAction::ExecuteAction()
    @     0x565544d9385d  clang::CodeGenAction::ExecuteAction()
    @     0x56554790e60b  clang::FrontendAction::Execute()
    @     0x5655477bdcf7  clang::CompilerInstance::ExecuteAction()
    @     0x565544d8116b  clang::ExecuteCompilerInvocation()
    @     0x565544d4ca48  cc1_main()
    @     0x565544d3a822  ExecuteCC1Tool()
    @     0x565544d38f86  clang_main()
    @     0x565544d3898f  main
    @     0x7f993c75bf12  __libc_start_main
    @     0x565544d3886a  _start
```

The problem was discovered after https://github.com/llvm/llvm-project/pull/189551#issuecomment-4256547239, but assertions-enabled clang crashes on the same test case already as of LLVM 19.

The problem is that [EmitExternalDeclaration](https://github.com/llvm/llvm-project/blob/326a9fa5631ebb497c1137d28469186a76f583ed/clang/lib/CodeGen/CodeGenModule.cpp#L5996) doesn't handle the case when `Addr` is a `llvm::GlobalAlias`.

### PR DESCRIPTION
**Pull request by alexfh**
Adds handling of global aliases in CodeGenModule::EmitExternalDeclaration. This fixes a clang crash on some real code, see llvm#192365.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
CC @llvm/pr-subscribers-debug-info

**Comment by MaskRay** [comment]
You can add `[BPF]` tag since the code path that crashes is gated on TargetInfo::allowDebugInfoForExternalRef(), only set by BPF.

File: clang/test/CodeGenCXX/bpf-debug-info-alias.cpp [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// RUN: %clang_cc1 -triple bpfel -emit-llvm -debug-info-kind=constructor %s -o - | FileCheck %s
```
Comment (dwblaikie) [inline clang/test/CodeGenCXX/bpf-debug-info-alias.cpp:1]: There aren't any types involved in this example, so probably `-debug-info-kind=constructor` isn't needed?

File: clang/lib/CodeGen/CodeGenModule.cpp [hunk 2]
```diff
@@ -5990,12 +5990,21 @@ void CodeGenModule::EmitExternalDeclaration(const DeclaratorDecl *D) {
...
-    if (!Fn->getSubprogram())
-      DI->EmitFunctionDecl(GD, FD->getLocation(), FD->getType(), Fn);
+    if (auto *Fn = dyn_cast<llvm::Function>(Addr)) {
+      if (!Fn->getSubprogram())
+        DI->EmitFunctionDecl(GD, FD->getLocation(), FD->getType(), Fn);
+    } else if (auto *GA = dyn_cast<llvm::GlobalAlias>(Addr)) {
+      DI->EmitGlobalAlias(GA, GD);
+    } else {
+      llvm_unreachable("Unexpected address for external function");
+    }
```
Comment (dwblaikie) [inline clang/lib/CodeGen/CodeGenModule.cpp]: Are both these codepaths tested by this test coverage? Looks like there's only functions in the test, and no global variables.

& could this code be refactored to be shared in some way between the two cases? Little lambda declared before the VarDecl dyn_cast, perhaps? That just takes the result of the dyn_cast GlobalVariable or Function as a parameter, and either returns it if non-null (& then the caller in each branch does the thing with it) otherwise the lambda does the GlobalAlias fallback?

File: clang/test/CodeGenCXX/bpf-debug-info-alias.cpp (hunk 1 above)
Comment (alexfh) [reply clang/test/CodeGenCXX/bpf-debug-info-alias.cpp:1]: The crash doesn't reproduce without this option.

File: clang/lib/CodeGen/CodeGenModule.cpp (hunk 2 above)
Comment (alexfh) [reply clang/lib/CodeGen/CodeGenModule.cpp]: I've added a test for a global variable alias and moved the common code out of the two branches.

Comment (alexfh) [reply clang/lib/CodeGen/CodeGenModule.cpp]: On another look it seems that using cast<> is not any worse than using llvm_unreachable() along with dyn_cast. Reverted this part and left just a single check for GlobalAlias.

**Review by dwblaikie — APPROVED** [review]
