### PR TITLE
Disallow btf_type_tag in C++ mode

### LINKED ISSUE #106864: [clang] Segmentation fault with `static_assert(__builtin_is_implicit_lifetime(int __attribute__((btf_type_tag("user"))) *))`
The following libc++ lit test causes a segmentation fault:

```c++
#include <cassert>

template <typename T>
constexpr void test1() {
    assert(true);
    static_assert(__builtin_is_implicit_lifetime(int __attribute__((btf_type_tag("user"))) *));
}

constexpr bool test() {
  test1<int>();
  return true;
}

int main(int, char**) {
  test();
  static_assert(test());

  return 0;
}
```

```
# .---command stderr------------
# | PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
# | Stack dump:
# | 0.  Program arguments: /usr/lib/llvm-20/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -dumpdir /home/h/Projects/llvm-project/build/default.debug.libcxx.clang-20/test/std/utilities/meta/meta.unary/meta.unary.prop/Output/is_implicit.pass.cpp.dir/t.tmp.exe- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name is_implicit.pass.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/h/Projects/llvm-project/build/default.debug.libcxx.clang-20/test/std/utilities/meta/meta.unary/meta.unary.prop -fcoverage-compilation-dir=/home/h/Projects/llvm-project/build/default.debug.libcxx.clang-20/test/std/utilities/meta/meta.unary/meta.unary.prop -nostdinc++ -resource-dir /usr/lib/llvm-20/lib/clang/20 -I /home/h/Projects/llvm-project/build/default.debug.libcxx.clang-20/include/c++/v1 -I /home/h/Projects/llvm-project/build/default.debug.libcxx.clang-20/include/c++/v1 -I /home/h/Projects/llvm-project/libcxx/test/support -D _LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D _LIBCPP_ENABLE_EXPERIMENTAL -D _LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -internal-isystem /usr/lib/llvm-20/lib/clang/20/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Werror=thread-safety -Wuser-defined-warnings -std=c++26 -fdeprecated-macro -ferror-limit 19 -pthread -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/lit-tmp-azt46ovm/is_implicit-847fa8.o -x c++ /home/h/Projects/llvm-project/libcxx/test/std/utilities/meta/meta.unary/meta.unary.prop/is_implicit.pass.cpp
# | 1.  /home/h/Projects/llvm-project/libcxx/test/std/utilities/meta/meta.unary/meta.unary.prop/is_implicit.pass.cpp:10:14: current parser token ')'
# | 2.  /home/h/Projects/llvm-project/libcxx/test/std/utilities/meta/meta.unary/meta.unary.prop/is_implicit.pass.cpp:9:23: parsing function body 'test'
# | 3.  /home/h/Projects/llvm-project/libcxx/test/std/utilities/meta/meta.unary/meta.unary.prop/is_implicit.pass.cpp:9:23: in compound statement ('{}')
# | 4.  /home/h/Projects/llvm-project/libcxx/test/std/utilities/meta/meta.unary/meta.unary.prop/is_implicit.pass.cpp:4:16: instantiating function definition 'test1<int>'
# | #0 0x00007fd805f4babf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-20/bin/../lib/libLLVM.so.20.0+0xf62abf)
# | #1 0x00007fd805f497d9 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-20/bin/../lib/libLLVM.so.20.0+0xf607d9)
# | #2 0x00007fd805f4c210 (/usr/lib/llvm-20/bin/../lib/libLLVM.so.20.0+0xf63210)
# | #3 0x00007fd804a7f320 (/lib/x86_64-linux-gnu/libc.so.6+0x45320)
# | #4 0x00007fd80e3fea20 clang::ObjCObjectTypeLoc::initializeLocal(clang::ASTContext&, clang::SourceLocation) (/usr/lib/llvm-20/bin/../lib/libclang-cpp.so.20.0+0x1333a20)
# | #5 0x00007fd80de35242 clang::ASTContext::getTrivialTypeSourceInfo(clang::QualType, clang::SourceLocation) const (/usr/lib/llvm-20/bin/../lib/libclang-cpp.so.20.0+0xd6a242)
# | #6 0x00007fd80ef17ff5 clang::Sema::SubstType(clang::QualType, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName) (/usr/lib/llvm-20/bin/../lib/libclang-cpp.so.20.0+0x1e4cff5)
# | #7 0x000055c21f13384c
# | clang++-20: error: unable to execute command: Segmentation fault
# | clang++-20: error: clang frontend command failed due to signal (use -v to see invocation)
# | Ubuntu clang version 20.0.0 (++20240828081755+22e55ba3293f-1~exp1~20240828081902.377)
# | Target: x86_64-unknown-linux-gnu
# | Thread model: posix
# | InstalledDir: /usr/lib/llvm-20/bin
# | clang++-20: note: diagnostic msg:
# | ********************
# |
# | PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
# | Preprocessed source(s) and associated run script(s) are located at:
# | clang++-20: note: diagnostic msg: /tmp/lit-tmp-azt46ovm/is_implicit-3295e8.cpp
# | clang++-20: note: diagnostic msg: /tmp/lit-tmp-azt46ovm/is_implicit-3295e8.sh
# | clang++-20: note: diagnostic msg:
# |
# | ********************
# `-----------------------------
# error: command failed with exit status: 1
```

### PR DESCRIPTION
**Pull request by AaronBallman**
This was always intended to be disallowed in C++ (see the definition in Attr.td), but failed to add the correct checking code in SemaType.cpp to ensure it was rejected.

Fixes #106864

### CODE REVIEW

File: clang/lib/Sema/SemaType.cpp [hunk 1]
```diff
@@ -6490,6 +6490,15 @@ static void HandleBTFTypeTagAttribute(QualType &Type, const ParsedAttr &Attr,
                                       TypeProcessingState &State) {
   Sema &S = State.getSema();
 
+  // This attribute is only supported in C.
+  // FIXME: we should implement checkCommonAttributeFeatures() in SemaAttr.cpp
```
Comment (erichkeane) [inline clang/lib/Sema/SemaType.cpp:6494]: Presumably this is pretty onerous to do?  Do we have an idea of what other attributes are going to fall into this same hole?

Comment (AaronBallman) [reply clang/lib/Sema/SemaType.cpp:6494]: Somewhat onerous given how few type attributes we have and how special type attributes tend to be.

The only other attribute in the same bucket is `lifetimebound` (which is a C++-only attribute rather than a C-only one). However, there are a pile of recent additions that are marked as `DeclOrTypeAttr` but have no handling whatsoever in SemaType.cpp (and so they probably aren't type attributes to begin with): `CountedByAttr`, `CountedByOrNullAttr`, `SizedByAttr`, and `SizedByOrNullAttr`.

I can handle `lifetimebound` in this PR or in a follow-up if you'd like. We should contact the authors of the other attributes and find out what the intent is for them rather than try to repair them as a drive-by.

Comment (erichkeane) [reply clang/lib/Sema/SemaType.cpp:6494]: I would think `lifetimebound` here would be acceptable/easy enough?  The others, please just ping the authors and get them to fix it themselves.

Comment (AaronBallman) [reply clang/lib/Sema/SemaType.cpp:6494]: Oh! It turns out `lifetimebound` is not really possible to run into in C because the only way it's accepted in a type position is as a member function qualifier. It also has some further issues in C++: https://godbolt.org/z/czPa3x7nb

So I think we should file an issue for the confusion and not make changes in this PR for it. WDYT?

Comment (AaronBallman) [reply clang/lib/Sema/SemaType.cpp:6494]: https://github.com/llvm/llvm-project/issues/107249 for the bounds-safety related attributes
https://github.com/llvm/llvm-project/issues/107252 for the `lifetimebound` attribute

File: clang/docs/ReleaseNotes.rst [hunk 2]
```diff
@@ -225,6 +225,11 @@ Attribute Changes in Clang
   more cases where the returned reference outlives the object.
   (#GH100567)
 
+- Now correctly diagnosing use of ``btf_type_tag`` in C++ and ignoring it; this
```
Comment (erichkeane) [inline clang/docs/ReleaseNotes.rst:228]:
```suggestion
- Clang now correctly diagnoses the use of ``btf_type_tag`` in C++ and ignores it; this
```

File: clang/docs/ReleaseNotes.rst [hunk 3]
```diff
@@ -225,6 +225,11 @@ Attribute Changes in Clang
...
+  attribute is a C-only attribute, and was causing crashes with template
```
Comment (erichkeane) [inline clang/docs/ReleaseNotes.rst:229]:
```suggestion
  attribute is a C-only attribute, and caused crashes with template
```

**Review by erichkeane — APPROVED** [review]
