### PR TITLE
[libc++] Fix erroneous internal capacity evaluation in vector<bool>

### LINKED ISSUE #121726: [libc++] Erroneous internal capacity evaluation causes SIGSEGV in `vector<bool>`
The internal capacity evaluation in `vector<bool>` is incorrect when evaluating `__external_cap_to_internal(0)`, resulting in an erroneous return value: `__external_cap_to_internal(0) = 288230376151711744` (`0x400000000000000`), while the correct result should be `__external_cap_to_internal(0) = 0`. Furthermore, this incorrect evaluation has propagated to other public APIs, causing a SIGSEGV error when compiling a program that calls `flip()` on `vector<bool>`, demonstrated as follows: 

[Godbolt Link](https://godbolt.org/z/G7E4x5hMj)

```cpp
#include <vector>

int main() {
  std::vector<bool> v;
  v.flip();
}
```
The complication error: 

```
Program returned: 139
Program stderr
Program terminated with signal: SIGSEGV
```

### Root cause analysis
The incorrect evaluation occurs due to the following faulty implementation of `__external_cap_to_internal`:

https://github.com/llvm/llvm-project/blob/8d2b070f07969f8358c93b9cf56834806fdc3efa/libcxx/include/__vector/vector_bool.h#L117-L119

The issue arises because `__n - 1` wraps around to become `size_type(-1) = 18446744073709551615` (`0xFFFFFFFFFFFFFFFF`) when `__n == 0`. A correct implementation should avoid this wrap-around behavior  for any `__n >= 0`.

### Proposed solution

To avoid the wrap-around arithmetic, the return statement can be rewritten as:

```cpp
return __n ? (__n - 1) / __bits_per_word + 1 : size_type(0);
```

or 

```cpp
return (__n + __bits_per_word - 1) / __bits_per_word;
``` 
This will automatically fix the SIGSEGV compilation error associated with `flip()`.

### PR DESCRIPTION
**Pull request by winner245**
This PR fixes the erroneous internal capacity evaluation in `vector<bool>`, which caused a subsequent SIGSEGV error when calling `flip()` on `vector<bool>`. By fixing the internal capacity evaluation, the SIGSEGV is automatically resolved. 

Closes #121726.

### CODE REVIEW

File: libcxx/include/__vector/vector_bool.h [hunk 1]
```diff
@@ -115,7 +115,7 @@ class _LIBCPP_TEMPLATE_VIS vector<bool, _Allocator> {
   }
   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 static size_type
   __external_cap_to_internal(size_type __n) _NOEXCEPT {
-    return (__n - 1) / __bits_per_word + 1;
+    return (__n + __bits_per_word - 1) / __bits_per_word;
```
Comment (frederick-vs-ja) [inline libcxx/include/__vector/vector_bool.h:118]: I guess we should handle the case where `__n + __bits_per_word - 1` wraps (and thus `(__n + __bits_per_word - 1) / __bits_per_word` becomes zero).

Comment (winner245) [reply libcxx/include/__vector/vector_bool.h:118]: In that case, maybe we should `return __n ? (__n - 1) / __bits_per_word + 1 : size_type(0);`?

**Review by ldionne — APPROVED** [review]

**Review by frederick-vs-ja — APPROVED** [review]
