### PR TITLE
[clang-tidy] Fix false positive in `readability-redundant-typename`

### LINKED ISSUE #169166: clang-tidy 22 check readability-redundant-typename triggers a false-positive result
In clang-tidy 22 this code fragment triggers a "Class.cpp:15:11: warning: redundant 'typename' [readability-redundant-typename]" warning.
```c++
#include <list>

template<typename T>
class Class
{
public:
    using Argument=std::list<T>;

    std::list<Argument> getArguments() const;
    
    std::list<Argument> arguments;
};

template<typename T>
std::list<typename Class<T>::Argument> Class<T>::getArguments() const // <-- the typename in question
{
    return arguments;
}
```

However if the "typename" keyword is removed from line 15, clang (and MSVC) refuse to compile the code.
clang (21.1.6/stable and 22/main) reports this error message:
```
Class.cpp:15:11: error: template argument for template type parameter must be a type; did you forget 'typename'?
```

It seems that the initial clang-tidy warning is a false-positive result.

### PR DESCRIPTION
**Pull request by zeyi2**
Closes #169166

### CODE REVIEW

**Review by vbvictor — APPROVED** [review]
LGTM, but I want to wait reasonable time for @localspook to look at this PR too.

**Review by localspook — COMMENTED** [review]
Thank you for investigating this!

File: clang-tools-extra/test/clang-tidy/checkers/readability/redundant-typename.cpp [hunk 1]
```diff
@@ -267,3 +267,17 @@ WHOLE_TYPE_IN_MACRO Macro2;
...
+class ClassWrapper {
+public:
+    using Argument = ListWrapper<T>;
+    ListWrapper<Argument> arguments;
+    ListWrapper<Argument> getArguments() const;
+};
+template<typename T>
+ListWrapper<typename ClassWrapper<T>::Argument> ClassWrapper<T>::getArguments() const {
+    return arguments;
+}
```
Comment (localspook) [inline clang-tools-extra/test/clang-tidy/checkers/readability/redundant-typename.cpp]: This test case could be reduced:
```suggestion
template <typename T> struct Wrapper {};
template <typename T>
struct ClassWrapper {
    using R = T;
    Wrapper<R> f();
};

template <typename T>
Wrapper<typename ClassWrapper<T>::R> ClassWrapper<T>::f() {
    return {};
}
```
(you can verify it still causes the FP: https://godbolt.org/z/vEx4GbaMa)

**Review by localspook — APPROVED** [review]
