### PR TITLE
CodeGen, IR: Add target-{cpu,features} attributes to functions created via createWithDefaultAttr().

### LINKED ISSUE #93633: Functions generated by Function::createWithDefaultAttr should respect -target-features
The following example usage of coverage + HWASan + LTO will fail:
```
$ cat test.cc
__attribute__((weak)) bool foo = false;

__attribute__((weak)) void bar() {}

int main() {
  if (foo) bar();
}
$ clang test.cc -O3 --target=aarch64-linux-android30 -flto -fsanitize=hwaddress -coverage --sysroot=$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot --gcc-toolchain=$NDK/toolchains/llvm/prebuilt/linux-x86_64
ld.lld: error: a.out.lto.o:(function __llvm_gcov_writeout: .text.__llvm_gcov_writeout+0x10): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 9079256848778895360 is not in [-4294967296, 4294967295]; references section '.rodata..L.hwasan'
>>> referenced by ld-temp.o

ld.lld: error: a.out.lto.o:(function __llvm_gcov_writeout: .text.__llvm_gcov_writeout+0x3c): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 8935141660703096832 is not in [-4294967296, 4294967295]; references section '.data..L__llvm_gcov_ctr.hwasan'
>>> referenced by ld-temp.o

ld.lld: error: a.out.lto.o:(function __llvm_gcov_writeout: .text.__llvm_gcov_writeout+0x64): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 9007199254741024768 is not in [-4294967296, 4294967295]; references section '.bss..L__llvm_gcov_ctr.1.hwasan'
>>> referenced by ld-temp.o

ld.lld: error: a.out.lto.o:(function __llvm_gcov_reset: .text.__llvm_gcov_reset+0x0): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 8935141660703096832 is not in [-4294967296, 4294967295]; references section '.data..L__llvm_gcov_ctr.hwasan'
>>> referenced by ld-temp.o

ld.lld: error: a.out.lto.o:(function __llvm_gcov_reset: .text.__llvm_gcov_reset+0xc): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 9007199254741024768 is not in [-4294967296, 4294967295]; references section '.bss..L__llvm_gcov_ctr.1.hwasan'
>>> referenced by ld-temp.o
```
The cause is that the compiler-generated functions `__llvm_gcov_writeout` and `__llvm_gcov_reset` do not have `target-features=+tagged-globals` attributes. These functions are created by `Function::createWithDefaultAttr`. The general form of this problem is known, and as such there's already an attempt in that function to copy certain attributes from the module flags onto the function. But for target features there's no module flag since the whole point of target features is that they're per-function.

I feel like this is probably a bug in `Function::createWithDefaultAttr` (which GCOV uses to create its compiler generated functions). It should probably set the target-features attribute to a list that it reads from the LLVMContext, or something like that (which Clang would fill in before running the pass pipeline). As things are, these generated functions won't respect things like `-ffixed-x*` flags either. That would imply that `Function::createWithDefaultAttr` shouldn't be used during LTO or in the backend. If looks like that's mostly already the case except for a couple of the GPU backends that are calling this function to create constructors.

### PR DESCRIPTION
**Pull request by pcc**
Functions created with createWithDefaultAttr() need to have the
correct target-{cpu,features} attributes to avoid miscompilations
such as using the wrong relocation type to access globals (missing
tagged-globals feature), clobbering registers specified via -ffixed-*
(missing reserve-* feature), and so on.

There's already a number of attributes copied from the module flags
onto functions created by createWithDefaultAttr(). I don't think
module flags are the right choice for the target attributes because
we don't need the conflict resolution logic between modules with
different target attributes, nor does it seem sensible to add it:
there's no unambiguously "correct" set of target attributes when
merging two modules with different attributes, and nor should there
be; it's perfectly valid for two modules to be compiled with different
target attributes, that's the whole reason why they are per-function.

This also implies that it's unnecessary to serialize the attributes in
bitcode, which implies that they shouldn't be stored on the module. We
can also observe that for the most part, createWithDefaultAttr()
is called from compiler passes such as sanitizers, coverage and
profiling passes that are part of the compile time pipeline, not
the LTO pipeline. This hints at a solution: we need to store the
attributes in a non-serialized location associated with the ambient
compilation context. Therefore in this patch I elected to store the
attributes on the LLVMContext.

There are calls to createWithDefaultAttr() in the NVPTX and AMDGPU
backends, and those calls would happen at LTO time. For those callers,
the bug still potentially exists and it would be necessary to refactor
them to create the functions at compile time if this issue is relevant
on those platforms.

Fixes #93633.

### CODE REVIEW

File: clang/test/CodeGen/coverage-target-attr.c [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// RUN: %clang -S -emit-llvm --coverage --target=aarch64-linux-android30 -fsanitize=hwaddress %s -o %t
```
Comment (MaskRay) [inline clang/test/CodeGen/coverage-target-attr.c:1]: Prefer %clang_cc1 in non-driver tests

File: llvm/include/llvm/IR/LLVMContext.h [hunk 2]
```diff
@@ -327,6 +327,26 @@ class LLVMContext {
...
+
+  /// See getDefaultTargetCPU().
+  void setDefaultTargetCPU(StringRef CPU);
+
+  /// Similar to getDefaultTargetCPU() but for default target-features instead.
+  StringRef getDefaultTargetFeatures();
+
+  /// See getDefaultTargetFeatures().
+  void setDefaultTargetFeatures(StringRef Features);
+
```
Comment (MaskRay) [inline llvm/include/llvm/IR/LLVMContext.h:349]: I agree with your analysis about "no serialization". I think we may have a lot of getters/setters.

Perhaps make a pair of getter/setter share the same comment so that it will look conciser?

```
// xxx
StringRef getDefaultTargetFeatures();
void setDefaultTargetFeatures(StringRef Features);

// yyy
StringRef getDefaultTargetFeatures();
void setDefaultTargetFeatures(StringRef Features);
```

**Review by MaskRay — APPROVED** [review]

File: clang/test/CodeGen/coverage-target-attr.c (hunk 1 above)
Comment (pcc) [reply clang/test/CodeGen/coverage-target-attr.c]: Done

File: llvm/include/llvm/IR/LLVMContext.h (hunk 2 above)
Comment (pcc) [reply llvm/include/llvm/IR/LLVMContext.h:345]: Done

**Comment by efriedma-quic** [comment]
I don't think I like this approach:

- This seems like an easy way to unintentionally pass state between different compilations.
- It seems very easy to try to use this API during LTO, and have it do nothing.
- I'm pretty sure this breaks existing workflows involving AMDGPUCtorDtorLowering/NVPTXCtorDtorLowering.

And please don't merge changes to core IR datastructures less than an hour after you post the patch.  Please revert and start a Discourse discussion so we can discuss the right direction here.

Off the top of my head, it might make sense to pass the relevant attributes as arguments to the constructor for the relevant IR passes.

**Comment by pcc** [comment]
https://discourse.llvm.org/t/functions-generated-by-function-createwithdefaultattr-should-respect-target-features/79838
