### PR TITLE
[clang-format] Allow decltype in requires clause

### LINKED ISSUE #78645: [clang-format] Incorrect method body when combining trailing return type  & `decltype` in `requires` clause
Continuation of #56176 (@HazardyKnusperkeks).

Tweaking the original example in that issue by adding `&` to the trailing return and using `decltype(...)` in the requires clause breaks it:
```c++
  template<typename T>
  struct Foo
  {
    auto bar(T in) -> int& requires (is_integral_v<decltype(in)>) {
                             call_something();
                             return 0;
                           }
  };
```

Changing one of the following fixes the formatting again:
* `-> int&` to `-> int`
* `decltype(in)` to `T`
* `requires (...)` to `requires ...`

You need parens if you negate (`(!...)`), but I guess a (highly arbitrary looking) workaround is to change from
`requires (is_integral_v<decltype(in)>)`
to
`requires is_integral_v<decltype(in)> || true`
works (tested).

```
$ clang++ --version
Homebrew clang version 17.0.6
```

### PR DESCRIPTION
**Pull request by rymiel**
If clang-format is not sure whether a `requires` keyword starts a requires clause or a requires expression, it looks ahead to see if any token disqualifies it from being a requires clause. Among these tokens was `decltype`, since it fell through the switch.

This patch allows decltype to exist in a require clause.

I'm not 100% sure this change won't have repercussions, but that just means we need more test coverage!

Fixes https://github.com/llvm/llvm-project/issues/78645

### CODE REVIEW

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -1071,6 +1071,16 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
                     "concept C = (!Foo<T>) && Bar;");
```
Comment (rymiel) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1071]: So, GitHub won't actually let me leave a comment on the line I want to actually talk about, but I noticed a few lines above this, on line 1066, it uses `EXPECT_EQ` instead of `ASSERT_EQ`, which is my mistake from 4 months ago.
But then I noticed a lot of these mistakes elsewhere in the file.
This is unrelated to this patch here, but do any of you have any opinions on unifying these? As I understand the assert exists to avoid out-of-bound accesses and thus segmentation faults. Is anyone opposed to an NFC commit changing all the EXPECTs into ASSERTs? @llvm/pr-subscribers-clang-format

Comment (HazardyKnusperkeks) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1071]: I'm in favor. Just for the correctness.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 2]
```diff
@@ -1071,6 +1071,16 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
...
+  Tokens = annotate("void f() & requires(C<decltype(x)>) {}");
+  ASSERT_EQ(Tokens.size(), 18u) << Tokens;
+  EXPECT_TOKEN(Tokens[4], tok::amp, TT_PointerOrReference);
+  EXPECT_TOKEN(Tokens[5], tok::kw_requires, TT_RequiresClause);
+
+  Tokens = annotate("auto f() -> int& requires(C<decltype(x)>) {}");
+  ASSERT_EQ(Tokens.size(), 20u) << Tokens;
+  EXPECT_TOKEN(Tokens[6], tok::amp, TT_PointerOrReference);
+  EXPECT_TOKEN(Tokens[7], tok::kw_requires, TT_RequiresClause);
 }
```
Comment (HazardyKnusperkeks) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: For the mentioned test coverage (you are completely right), something like:
```c++
int foo(auto t) {
    if (requires (decltype(t) x) {x.foo();}) {
        return 1;
    }
    return 0;
}
```

Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: Thanks, but this test input never actually runs parseRequires(), but I constructed another case which does, I'll add both

Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: I found a failing edge case
`bool x = t && requires(Foo<decltype(t)> x) { x.foo(); };`
will annotate the requires as a TT_RequiresClause. I'll add extra logic in the lookahead to fix this

Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: Well, the simplest fix is to remove `case tok::r_paren:` on line 3424 which always led to parseRequiresClause. Surprisingly removing that breaks no tests, but surely @HazardyKnusperkeks you put it there for a reason? I'm not sure if such a fix is the best idea

Comment (HazardyKnusperkeks) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: I _think_ the idea was that if it is an expression we would detect the type before reaching the `r_paren` and thus it has to be a clause. But 2 years have passed and I don't know what I was thinking last week. ;) Had to reread the code and try to guess the conditions.

Which shows why one should comment complicated code...

If I read the code right my question is why didn't `Foo<decktype(t)>` suffice `FoundType && !LastWasColonColon && OpenAngles == 0` when hitting the `x`?

On a different note one could extend the look behind to see if one finds a `=` or a `(` for any conditional, or a requires expression `}`, then it should be an expression.

Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: > If I read the code right my question is why didn't `Foo<decktype(t)>` suffice `FoundType && !LastWasColonColon && OpenAngles == 0` when hitting the `x`?

I'm not sure what you mean. If you're talking about `Foo<decltype(t)> x`, it never gets to the `x` because it reaches the `)` of the decltype first and that unconditionally leads to being parsed as a clause

Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: The fix I would originally do was just look behind again and see if the ) belongs to a decltype, I just also tried removing the case entirely, and was surprised it works. If you prefer, I can follow my original plan and add an extra check for decltype

Comment (HazardyKnusperkeks) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1084]: I have no problem with removing it. If you keep it, I would add a check for `OpenAngles == 0`. The same applies to `||` because one could write something like
```c++
requires (T<C1 || C2> t) {}
```

So the whole logic should only apply to the out of template area, similar to `const`, `volatile`, and `comma` above.

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1071]: +1. You don't even need to create a pull request for this kind of NFC changes.

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 3]
```diff
@@ -1071,6 +1071,37 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
...
+  ASSERT_EQ(Tokens.size(), 20u) << Tokens;
+  EXPECT_TOKEN(Tokens[6], tok::amp, TT_PointerOrReference);
+  EXPECT_TOKEN(Tokens[7], tok::kw_requires, TT_RequiresClause);
+
+  Tokens = annotate("int foo(auto t) {\n"
+                    "    if (requires (decltype(t) x) {x.foo();}) {\n"
+                    "        return 1;\n"
+                    "    }\n"
+                    "    return 0;\n"
+                    "}\n");
```
Comment (owenca) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1090]: Do we need the newline?

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 2 above)
Comment (owenca) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1105]: > The fix I would originally do was just look behind again and see if the ) belongs to a decltype, I just also tried removing the case entirely, and was surprised it works. If you prefer, I can follow my original plan and add an extra check for decltype

In general, I prefer to not include code that can't be reached by test cases as the code is likely superfluous. Because @HazardyKnusperkeks is ok with its removal, wouldn't be better to just do that?

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1071]: 88d1de5ec64210686d93a90529583505635d257d

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by owenca — APPROVED** [review]

**Comment by owenca** [comment]
Should we merge this patch?
