### PR TITLE
[clang-format] Don't annotate enum colon as InheritanceColon

### LINKED ISSUE #61156: [clang-format] There is no option to disable BreakInheritanceList and BreakConstructorInitializers
Hi, 
I want to achieve this formatting effect:
```cpp
class D : public A, public B, public C
{
public:
  int id_c;
}; 

typedef enum : int
{
  ALL = 0,
  DEBUG = 1,
  INFO = 2,
  WARN = 3,
  ERROR = 4,
} log_level_t;
```
I want to use Mozilla style, so I generated `.clang-format` with Mozilla style parameters:
```shell
clang-format -style=mozilla -dump-config > .clang-format
```
After formatting using this `.clang-format` file, I got the following:
```cpp
class D
  : public A
  , public B
  , public C
{
public:
  int id_c;
};

typedef enum
  : int
{
  ALL = 0,
  DEBUG = 1,
  INFO = 2,
  WARN = 3,
  ERROR = 4,
} log_level_t;
```
Trying to achieve my formatting goal, I found those values in the `.clang-format` file:
```yml
# BasedOnStyle:  Mozilla
BreakBeforeInheritanceComma: false
BreakInheritanceList: BeforeComma
BreakConstructorInitializersBeforeComma: false
BreakConstructorInitializers: BeforeComma
```
I want to disable line breaks, but there's no `false` value for those parameters:
```yml
# It doesn't work
BasedOnStyle:  Mozilla
BreakConstructorInitializers: false
BreakConstructorInitializers: false
```
I was only able to get the effect I wanted by commenting on the relevant parameters:
```yml
# BasedOnStyle:  Mozilla
BreakBeforeInheritanceComma: false
#BreakInheritanceList: BeforeComma
BreakConstructorInitializersBeforeComma: false
#BreakConstructorInitializers: BeforeComma
```
However, with this solution, I have to copy all the parameters from the Mozilla style instead of using `BasedOnStyle: Mozilla`.
Shouldn't there be an option to disable those parameters connected with breaks?

### PR DESCRIPTION
**Pull request by owenca**
Fix #61156

### CODE REVIEW

File: clang/lib/Format/TokenAnnotator.cpp [hunk 1]
```diff
@@ -1423,7 +1423,7 @@ class AnnotatingParser {
         Tok->setType(TT_BitFieldColon);
       } else if (Contexts.size() == 1 &&
                  !Line.First->isOneOf(tok::kw_enum, tok::kw_case,
-                                      tok::kw_default)) {
+                                      tok::kw_default, tok::kw_typedef)) {
```
Comment (HazardyKnusperkeks) [inline clang/lib/Format/TokenAnnotator.cpp:1426]: Sadly `typedef class` is a thing too, this would break, wouldn't it?

**Review by HazardyKnusperkeks — APPROVED** [review]

**Review by HazardyKnusperkeks — APPROVED** [review]
