### PR TITLE
[clang-format] Don't allow casts in front of ampamp

### LINKED ISSUE #77680: [clang-format] parenthesized expression in concept causes && to be misinterpreted as rvalue reference
The standard sometimes requires parentheses around expressions used in concepts, but they can cause `&&` to be interpreted incorrectly.  See how this example is missing the space after the `&&`:

```cpp
template <typename T>
concept concept1 =
        (!std::derived_from<T, MyClass1>) &&std::derived_from<T, MyClass2>;
```
but similar code with the parenthesized expression switched to come second is formatted correctly:
```cpp
template <typename T>
concept concept1 =
        std::derived_from<T, MyClass2> && (!std::derived_from<T, MyClass1>);
```

```
$ clang-format --version
clang-format version 18.0.0git (https://github.com/llvm/llvm-project.git c053e9f0f4b56a56582ad149a8c89434126eff7f)
```

### PR DESCRIPTION
**Pull request by rymiel**
clang-format performs a heuristic to see if a right parenthesis is the parenthesis of a cast expression. This check never looked ahead to see if the next token is an ampamp && token. This resulted in the paren being set as an CastRParen, and the following ampamp got annotated as an UnaryOperator!

Since && can never be a unary operator is standard C++, this patch forbids the right paren from ever becoming a cast.

Fixes https://github.com/llvm/llvm-project/issues/77680

### CODE REVIEW

**Review by owenca — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp [hunk 1]
```diff
@@ -1066,6 +1066,11 @@ TEST_F(TokenAnnotatorTest, UnderstandsRequiresClausesAndConcepts) {
   EXPECT_EQ(Tokens.size(), 17u) << Tokens;
   EXPECT_TOKEN(Tokens[4], tok::amp, TT_PointerOrReference);
   EXPECT_TOKEN(Tokens[5], tok::kw_requires, TT_RequiresClause);
+
+  Tokens = annotate("template <typename T>\n"
+                    "concept C = (!Foo<T>) && Bar;");
+  ASSERT_EQ(Tokens.size(), 19u) << Tokens;
+  EXPECT_TOKEN(Tokens[15], tok::ampamp, TT_BinaryOperator);
```
Comment (mydeveloperday) [inline clang/unittests/Format/TokenAnnotatorTest.cpp:1073]: out of interest what did it think it was  before?

**Review by mydeveloperday — COMMENTED** [review]
LGTM

**Review by mydeveloperday — APPROVED** [review]

File: clang/unittests/Format/TokenAnnotatorTest.cpp (hunk 1 above)
Comment (rymiel) [reply clang/unittests/Format/TokenAnnotatorTest.cpp:1073]: TT_UnaryOperator, as outlined in the issue description

**Review by HazardyKnusperkeks — APPROVED** [review]
