### PR TITLE
Poison last word of FakeFrame

### LINKED ISSUE #133640: AddressSanitizer's FakeStack metadata can be rewrite by users
AddressSanitizer save a &flag[pos] in the end of FakeStack, which can be rewrite by users. If you run this code snippet with `-fsanitize=address`, you would get SEGV signal. Because AddressSanitizer try to read &flag[pos] in __asan_stack_free, but it reads wrong place.

```
struct BigData {
        int x[1000];
};

void *test() {
        struct BigData x;
        int *y = x.x + 1032;
        for (int i = 0; i < 5000; i++)
                y[i] = 0xffffffff;
        return &x;
}

int main() {
        *(int *)test() = 1;
        return 0;
}
```
You should compile this program with `clang -fsanitize=address source.c -o a.out`. I'm using v18.1.6 to do this experiment.

### PR DESCRIPTION
**Pull request by brandb97**
Fix [issue#133640](https://github.com/llvm/llvm-project/issues/133640)

### CODE REVIEW

**Comment by brandb97** [comment]
@vitalybuka @ramosian-glider

**Comment by brandb97** [comment]
Ping

File: compiler-rt/lib/asan/asan_fake_stack.cpp [hunk 1]
```diff
@@ -107,7 +107,12 @@ FakeFrame *FakeStack::Allocate(uptr stack_size_log, uptr class_id,
     FakeFrame *res = reinterpret_cast<FakeFrame *>(
         GetFrame(stack_size_log, class_id, pos));
     res->real_stack = real_stack;
-    *SavedFlagPtr(reinterpret_cast<uptr>(res), class_id) = &flags[pos];
+    u8 **saved_flag_ptr = SavedFlagPtr(reinterpret_cast<uptr>(res), class_id);
+    *saved_flag_ptr = &flags[pos];
+
+    // Poison the last word of FakeFrame
+    u8 *shadow = reinterpret_cast<u8*>(MemToShadow(reinterpret_cast<uptr>(saved_flag_ptr)));
```
Comment (vitalybuka) [inline compiler-rt/lib/asan/asan_fake_stack.cpp:114]: do we know if saved_flag_ptr is granule aligned?

**Comment by vitalybuka** [comment]
> Ping

Sorry, usually it's for 1w+, but I was not working that week.

File: compiler-rt/lib/asan/asan_fake_stack.cpp [hunk 2]
```diff
@@ -107,7 +107,12 @@ FakeFrame *FakeStack::Allocate(uptr stack_size_log, uptr class_id,
...
+    *shadow = kAsanStackRightRedzoneMagic;
     return res;
```
Comment (vitalybuka) [inline compiler-rt/lib/asan/asan_fake_stack.cpp:116]: we need a test for the fix

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 1 above)
Comment (brandb97) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:114]: Yes, saved_flag_ptr is the last word of FakeFrame, and I suppose FakeFrame is granule aligned

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 2 above)
Comment (brandb97) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:116]: How to add a test, should I put test code in the comment?

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 1 above)
Comment (vitalybuka) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:114]: I think we should do that in SetShadow
and we need to poison everything beyond user size:  [size ,  BytesInSizeClass(class_id) )

And please add into SetShadow `CHECK(AddrIsAlignedByGranularity(ptr + size))`

Comment (brandb97) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:114]: Ok, I'll have a try

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 2 above)
Comment (brandb97) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:116]: Is compiler-rt/test/asan/fakeframe-right-redzone.cpp a good name for test file?

File: compiler-rt/lib/asan/asan_fake_stack.cpp [hunk 3]
```diff
@@ -231,6 +232,13 @@ static ALWAYS_INLINE uptr OnMalloc(uptr class_id, uptr size) {
     return 0;  // Out of fake stack.
   uptr ptr = reinterpret_cast<uptr>(ff);
   SetShadow(ptr, size, class_id, 0);
+
+  // Poison everything beyond user size, use kNumberOfSizeClasses to prevent
+  // SetShadow from inlining PoisonShadow
+  SetShadow(reinterpret_cast<uptr>(ptr + size),
```
[the remark this answers is not in the document]
Comment (vitalybuka) [reply compiler-rt/lib/asan/asan_fake_stack.cpp:238]:
```
ALWAYS_INLINE void SetShadow(uptr ptr, uptr size, uptr class_id, u64 magic) {
  u64 *shadow = reinterpret_cast<u64*>(MemToShadow(ptr));
  if (ASAN_SHADOW_SCALE == 3 && class_id <= 6) {
    // This code expects ASAN_SHADOW_SCALE=3.
    for (uptr i = 0; i < (((uptr)1) << class_id); i++) {
      shadow[i] = magic;
      // Make sure this does not become memset.
      SanitizerBreakOptimization(nullptr);
    }
  } else {
    // The size class is too big, it's cheaper to poison only size bytes.
    PoisonShadow(ptr, size, static_cast<u8>(magic));
  }

  if (magic != 0) {
    PoisonShadow(ptr + size , ???, kAsanStackRightRedzoneMagic);
  }
}
```

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 2 above)
Comment (vitalybuka) [reply compiler-rt/lib/asan/asan_fake_stack.cpp]: LGTM

File: compiler-rt/lib/asan/asan_fake_stack.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (brandb97) [reply compiler-rt/lib/asan/asan_fake_stack.cpp]: ok, and I remove array_bound test in compiler-rt/test/ubsan/TestCases/Integer/bit-int.c

File: compiler-rt/test/asan/TestCases/fakeframe-right-redzone.cpp [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+
+int main(int argc, char **argv) {
+  char *x = OverwriteFakeFrameLastWord();
+  // CHECK: ERROR: AddressSanitizer: stack-buffer-overflow on address
+  // CHECK: is located in stack of thread T0 at offset {{2040|2044}} in frame
+  // CHECK:  in OverwriteFakeFrameLastWord{{.*}}fakeframe-right-redzone.cpp:
+  // CHECK: [{{16|32}}, {{1040|1056}}) 'x'
+  pretend_to_do_something(x);
+  return 0;
+}
```
Comment (vitalybuka) [inline compiler-rt/test/asan/TestCases/fakeframe-right-redzone.cpp:36]: new line

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c [hunk 5]
```diff
@@ -49,13 +49,6 @@ uint32_t unsigned_shift_base() {
...
-uint32_t array_bounds() {
-  _BitInt(37) x[4];
-  _BitInt(37) y = x[10];
-  // CHECK: {{.*}}bit-int.c:[[#@LINE-1]]:19: runtime error: index 10 out of bounds for type
-  return (uint32_t)y;
-}
-
 uint32_t float_cast_overflow() {
   float a = 100000000.0f;
   _BitInt(7) b = (_BitInt(7))a;
```
Comment (vitalybuka) [inline compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:54]: This still test something,
can you just add -fsanitize-address-use-after-return=never into RUN above?

Comment (brandb97) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:54]: ok

Comment (vitalybuka) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c:54]: another option to wrap into struct

```
struct {
  x[4];
  something
};
```

**Review by vitalybuka — APPROVED** [review]
Thank you for that patch!

File: compiler-rt/test/ubsan/TestCases/Integer/bit-int.c (hunk 5 above)
Comment (brandb97) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: Just curious, why wrap array in struct prevent using fake frame?

Comment (vitalybuka) [reply compiler-rt/test/ubsan/TestCases/Integer/bit-int.c]: It will not prevent fake frame, but x[] will be followed by non-poisoned bytes of "something"
