### PR TITLE
feat: fix big endian shuffle vector miscompile

### LINKED ISSUE #65884: [AArch64] neon big endian miscompiled
https://godbolt.org/z/vWMz5K34r

```
#include <arm_neon.h>

extern void abort (void);

__attribute__((noinline)) uint8x16_t
wrap_vld1q_lane_u8 (const uint8_t *load, uint8x16_t vec) {
  return vld1q_lane_u8 (load, vec, 12);
}

int test_vld1q_lane_u8(const uint8_t *data) {
  uint8_t out[16];
  uint8_t overwrite = 7;
  int j;
  uint8x16_t in = vld1q_u8 (data);
  in = wrap_vld1q_lane_u8 (&overwrite, in);
  vst1q_u8 (out, in);
  for (j = 0; j < 13; j++)
    if (out[j] != (j == 12 ? overwrite : data[j])) {
      abort();
    }
  return 0;
}

int main (int argc, char **argv)
{
  uint64_t orig_data[2] = {0x1234567890abcdefULL, 0x13579bdf02468aceULL};
  test_vld1q_lane_u8((const uint8_t *)orig_data);
  return 0;
}
```

this code fail, when `-O3 -fno-inline`.

I see the https://llvm.org/docs/BigEndianNEON.html , but I still confuse about the asm:

```
        rev64   v0.16b, v0.16b
        ext     v0.16b, v0.16b, v0.16b, #8
        rev64   v0.16b, v0.16b
        ext     v0.16b, v0.16b, v0.16b, #8
```

this code seem do nothing, but appear many times. 

Can anyone give me some clue about this fail? Or just narrow this problem?

I opt bisect it, it's fail in `SLPVectorizerPass`, but I guess it just introduced this problem, but not the main point.

### PR DESCRIPTION
**Pull request by hstk30-hw**
fix https://github.com/llvm/llvm-project/issues/65884

### CODE REVIEW

File: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp [hunk 1]
```diff
@@ -10914,6 +10914,26 @@ SDValue AArch64TargetLowering::ReconstructShuffle(SDValue Op,
...
+      } else if (std::max(DstTypeSize, SrcTypeSize) == 64) {
+        REVOp = AArch64ISD::REV64;
+      }
+      if (REVOp) {
+        Shuffle = DAG.getNode(REVOp, dl, ShuffleVT, Shuffle);
+      }
+    }
+  }
+  
   SDValue V = DAG.getNode(ISD::BITCAST, dl, VT, Shuffle);
```
Comment (davemgreen) [inline llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:10937]: Would it fix things if this BITCAST was a NVCAST instead?

Comment (hstk30-hw) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:10937]: To be honest, I didn't take NVCAST into account :( 
Do you have relative test case?
I will see it later.

Comment (davemgreen) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:10936]: BITCAST is defined as a store+load of the data type, so can re-arrange data inside the vector lanes under big endian.
NVCAST is an AArch64 specific node that deliberately doesn't do the same lane interchanging.

So VREV+BITCAST should equal NVCAST (under BE), and I think if this ISD::BITCAST was a AArch64ISD::NVCAST instead then it would handle case you've found, where you've added the REV's (and should maybe optimize better?)

Comment (hstk30-hw) [reply llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:10936]: Thx your explanation, I will try it later.

**Comment by davemgreen** [comment]
Also - AArch64ISD::NVCAST == ISD::BITCAST under LE, so it can be used in both cases.

**Comment by davemgreen** [comment]
It looks like there might be a few failing tests, possibly that need updating?

It is possible that there are a number of places where bitcast is being used incorrectly under BE.

**Comment by hstk30-hw** [comment]
Yes，I need time to check it. Some tests are hard to check manually, it seem generates automatilly for be.

**Comment by hstk30-hw** [comment]
> Also - AArch64ISD::NVCAST == ISD::BITCAST under LE, so it can be used in both cases.

Replace `ISD::BITCAST` to `AArch64ISD::NVCAST` simply will let this commit:  https://github.com/llvm/llvm-project/commit/62fc58a61d153daa015b9e22b0c386c74a5f7076 not work.

Check it plz. @davemgreen

**Comment by hstk30-hw** [comment]
ping ... @davemgreen

**Comment by hstk30-hw** [comment]
Ping @nikic @ostannard @efriedma-quic

File: llvm/test/CodeGen/AArch64/fix-shuffle-vector-be-rev.ll [hunk 2]
```diff
@@ -0,0 +1,15 @@
+; RUN: llc < %s -mtriple=aarch64_be | FileCheck %s
```
Comment (davemgreen) [inline llvm/test/CodeGen/AArch64/fix-shuffle-vector-be-rev.ll:1]: Can you:
 - Add a LE test line, using --check-prefix=CHECKLE and CHECKBE
 - Autogenerate the check lines using the update_llc_test_checks script.
 - Perhaps add a simpler test that shows the same issue? Perhaps remove the loads and the freeze, but it appears to be the second shuffle that shows the problem. 
 - Maybe something like this (although it doesn't actually show the a due to the zip args both being the same):
```
define <4 x i16> @exttop(<16 x i8> %tmp1, <16 x i8> %tmp2) {
; CHECKLE-LABEL: exttop:
; CHECKLE:       // %bb.0:
; CHECKLE-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECKLE-NEXT:    zip2 v0.8b, v0.8b, v0.8b
; CHECKLE-NEXT:    bic v0.4h, #255, lsl #8
; CHECKLE-NEXT:    ret
;
; CHECKBE-LABEL: exttop:
; CHECKBE:       // %bb.0:
; CHECKBE-NEXT:    rev64 v0.16b, v1.16b
; CHECKBE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECKBE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECKBE-NEXT:    zip2 v0.8b, v0.8b, v0.8b
; CHECKBE-NEXT:    bic v0.4h, #255, lsl #8
; CHECKBE-NEXT:    rev64 v0.4h, v0.4h
; CHECKBE-NEXT:    ret
  %tmp4 = shufflevector <16 x i8> %tmp2, <16 x i8> undef, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
  %tmp6 = zext <4 x i8> %tmp4 to <4 x i16>
  ret <4 x i16> %tmp6
}
```
This one does:
```

define <4 x i16> @exttop2(<16 x i8> %tmp1, <16 x i8> %tmp2) {
; CHECKLE-LABEL: exttop2:
; CHECKLE:       // %bb.0:
; CHECKLE-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECKLE-NEXT:    zip2 v1.8b, v1.8b, v0.8b
; CHECKLE-NEXT:    zip2 v0.8b, v0.8b, v0.8b
; CHECKLE-NEXT:    add v0.4h, v1.4h, v0.4h
; CHECKLE-NEXT:    bic v0.4h, #255, lsl #8
; CHECKLE-NEXT:    ret
;
; CHECKBE-LABEL: exttop2:
; CHECKBE:       // %bb.0:
; CHECKBE-NEXT:    rev64 v0.16b, v1.16b
; CHECKBE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECKBE-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECKBE-NEXT:    zip2 v0.8b, v0.8b, v0.8b
; CHECKBE-NEXT:    zip2 v1.8b, v1.8b, v0.8b
; CHECKBE-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECKBE-NEXT:    bic v0.4h, #255, lsl #8
; CHECKBE-NEXT:    rev64 v0.4h, v0.4h
; CHECKBE-NEXT:    ret
  %tmp3 = shufflevector <16 x i8> %tmp2, <16 x i8> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %tmp4 = shufflevector <16 x i8> %tmp2, <16 x i8> undef, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
  %tmp5 = add <4 x i8> %tmp3, %tmp4
  %tmp6 = zext <4 x i8> %tmp5 to <4 x i16>
  ret <4 x i16> %tmp6
}
```
 - I would also pick a different name or add it to one of the existing test files.

**Review by davemgreen — COMMENTED** [review]
Hi - sorry about the delay it took a while to look through the details. There might be a way to convert NVCAST to BITCAST under LE and adjust all the needed patterns to handle either, but it doesn't look simple and this seems like a good fix for now. It checked out OK in all the tests I tried. There are some comments about adjusting the new test case below, but otherwise this looks OK to me.

File: llvm/test/CodeGen/AArch64/fix-shuffle-vector-be-rev.ll (hunk 2 above)
Comment (hstk30-hw) [reply llvm/test/CodeGen/AArch64/fix-shuffle-vector-be-rev.ll]: Solve it.

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM

**Comment by hstk30-hw** [comment]
"hstk30-hw hanwei62@huawei.com" 
Merge it for me, plz.
