### PR TITLE
[win/asan] Don't intercept memset etc. in ntdll

### LINKED ISSUE #114793: memset interception in compiler-rt asan is incompatible with ntdll.dll from Windows 11 24H2
ntdll
===

[ntdll.dll 10.0.26100.2161](https://msdl.microsoft.com/download/symbols/ntdll.dll/6C29F8C2263000/ntdll.dll) from Windows 11 24H2 26100.2161 differs from previous versions of ntdll.dll in a subtle way. [edit: In fact all Windows 11 24H2 since 26100.1 have this difference -- thank you Gov Maharaj for figuring this out.]

Previously RtlDispatchException would almost directly reach into the vectored exception handlers, but now two buffers of respective sizes 0x58 and 0xD8 are memset to zero before reaching into the vectored exception handlers:

```
// 10.0.26100.2161
    ntdll!RtlDispatchException:
push    rbp
push    rsi
push    rdi
push    r12
push    r13
push    r14
push    r15
sub     rsp, 210h
lea     rbp, [rsp+60h]
mov     qword ptr [rbp+200h], rbx
mov     rax, qword ptr [ntdll!__security_cookie]
xor     rax, rbp
mov     qword ptr [rbp+1A0h], rax
xor     esi, esi
mov     r15, rdx
mov     rdi, rcx
mov     dword ptr [rbp+20h], esi
xor     edx, edx
lea     rcx, [rbp+50h]
lea     r8d, [rsi+50h]
  // memset(foo, 0, 0x50)
call    ntdll!memset$thunk$772440563353939046
xor     edx, edx
mov     byte ptr [rbp], sil
mov     r8d, 0D8h
mov     qword ptr [rbp+8], rsi
lea     rcx, [rbp+0C0h]
mov     qword ptr [rbp+10h], rsi
mov     qword ptr [rbp+18h], rsi
mov     qword ptr [rbp+48h], rsi
mov     qword ptr [rbp+28h], rsi
mov     qword ptr [rbp+40h], rsi
  // memset(bar, 0, 0xD8)
call    ntdll!memset$thunk$772440563353939046
mov     rax, qword ptr gs:[60h]
test    dword ptr [rax+0BCh], 800000h
je      ntdll!RtlDispatchException+0xa0
cmp     qword ptr [ntdll!RtlpExceptionLog2], rsi
mov     byte ptr [rbp], 1
jne     ntdll!RtlDispatchException+0x609
xor     r8d, r8d
mov     rdx, r15
mov     rcx, rdi
call    ntdll!RtlpCallVectoredHandlers
```

Now let me detail why we care here.

memset interception with ASAN
=====================

When compiler-rt ASAN instrumentation is in place, memset is replaced for instrumentation purposes. So any memset will go through:

```c++
#define ASAN_MEMSET_IMPL(ctx, block, c, size) \
  do {                                        \
    if (LIKELY(replace_intrin_cached)) {      \
      ASAN_WRITE_RANGE(ctx, block, size);     \
    } else if (UNLIKELY(!AsanInited())) {     \
      return internal_memset(block, c, size); \
    }                                         \
    return REAL(memset)(block, c, size);      \
  } while (0)

#define ASAN_WRITE_RANGE(ctx, offset, size) \
  ACCESS_MEMORY_RANGE(ctx, offset, size, true)

#define ACCESS_MEMORY_RANGE(ctx, offset, size, isWrite)                   \
  do {                                                                    \
    uptr __offset = (uptr)(offset);                                       \
    uptr __size = (uptr)(size);                                           \
    uptr __bad = 0;                                                       \
    if (UNLIKELY(__offset > __offset + __size)) {                         \
      GET_STACK_TRACE_FATAL_HERE;                                         \
      ReportStringFunctionSizeOverflow(__offset, __size, &stack);         \
    }                                                                     \
    if (UNLIKELY(!QuickCheckForUnpoisonedRegion(__offset, __size)) &&     \
        (__bad = __asan_region_is_poisoned(__offset, __size))) {          \
      AsanInterceptorContext *_ctx = (AsanInterceptorContext *)ctx;       \
      bool suppressed = false;                                            \
      if (_ctx) {                                                         \
        suppressed = IsInterceptorSuppressed(_ctx->interceptor_name);     \
        if (!suppressed && HaveStackTraceBasedSuppressions()) {           \
          GET_STACK_TRACE_FATAL_HERE;                                     \
          suppressed = IsStackTraceSuppressed(&stack);                    \
        }                                                                 \
      }                                                                   \
      if (!suppressed) {                                                  \
        GET_CURRENT_PC_BP_SP;                                             \
        ReportGenericError(pc, bp, sp, __bad, isWrite, __size, 0, false); \
      }                                                                   \
    }                                                                     \
  } while (0)
```

In particular, `__asan_region_is_poisoned` will access the shadow memory corresponding to the region that we memset, in order to check if the region is poisoned.

Shadow memory lazy commit on Win64
==========================

On Win64, shadow memory pages are first allocated as `MEM_RESERVE`. They are dynamically turned to `MEM_COMMIT` on demand -- meaning that we rely on an exception handler `ShadowExceptionHandler` to change the status of the page when we fail to access a reserved shadow memory page because it is not yet commited. This change was pushed by [this revision](https://reviews.llvm.org/D21942).

Putting it together
============

The Win64 memset interception in ASAN is incompatible with ntdll 10.0.26100.2161. As soon as a first access violation gets raised because a shadow memory page is reserved but not committed, we immediately reach a call to memset before we get a chance to reach the `ShadowExceptionHandler`. This call to memset itself triggers a new access violation and a new call to memset, etc. This is a neverending cycle, until eventually we overflow the stack.

```c++
 # Child-SP          RetAddr               Call Site
00 0000003e`f3000fa0 00007ffb`03adf0da     clang_rt_asan_dynamic_x86_64!__asan_wrap_memset+0x18e [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc @ 87] 
01 0000003e`f3001830 00007ffb`03c236de     ntdll!RtlDispatchException+0x4a
02 0000003e`f3001a80 00007ffa`8c4c8632     ntdll!KiUserExceptionDispatch+0x2e
03 (Inline Function) --------`--------     clang_rt_asan_dynamic_x86_64!__asan::AddressIsPoisoned+0xe [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_mapping.h @ 395] 
04 0000003e`f3002180 00007ffa`8c4c56a3     clang_rt_asan_dynamic_x86_64!__asan_region_is_poisoned+0xf2 [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_poisoning.cpp @ 189] 
05 0000003e`f30021e0 00007ffb`03adf0da     clang_rt_asan_dynamic_x86_64!__asan_wrap_memset+0x193 [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc @ 87] 
06 0000003e`f3002a70 00007ffb`03c236de     ntdll!RtlDispatchException+0x4a
07 0000003e`f3002cc0 00007ffa`8c4c8632     ntdll!KiUserExceptionDispatch+0x2e
08 (Inline Function) --------`--------     clang_rt_asan_dynamic_x86_64!__asan::AddressIsPoisoned+0xe [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_mapping.h @ 395] 
09 0000003e`f30033c0 00007ffa`8c4c56a3     clang_rt_asan_dynamic_x86_64!__asan_region_is_poisoned+0xf2 [/builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_poisoning.cpp @ 189] 
// ...
```

Related Firefox bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1926680).

### PR DESCRIPTION
**Pull request by zmodem**
When ntdll was added to the list of of "interesting DLLs" list (in
d58230b9dcb3b312a2da8f874daa0cc8dc27da9b), the intention was not to
intercept the "mini CRT" functions it exports. OverrideFunction would
only intercept the *first* function it found when searching the list of
DLLs, and ntdll was put last in that list.

However, after 42cdfbcf3e92466754c175cb0e1e237e9f66749e,
OverrideFunction intercepts *all* matching functions in those DLLs. As
a side-effect, the runtime would now intercept functions like memset
etc. also in ntdll.

This causes a problem when ntdll-internal functions like
RtlDispatchException call the intercepted memset, which tries to
inspect uncommitted shadow memory, raising an exception, and getting
stuck in that loop until the stack overflows.

Since we never intended to intercept ntdll's memset etc., the simplest
fix seems to be to actively ignore ntdll when intercepting those
functions.

Fixes #114793

### CODE REVIEW

**Comment by zmodem** [comment]
I think this strikes the right balance between hacky and pragmatic, and is in line with @rnk's advice in https://github.com/llvm/llvm-project/issues/114793#issuecomment-2455265172

@rnk, @zacklj89, @barcharcraz, @yjugl What do you think?

**Comment by zacklj89** [comment]
@zmodem firstly, thanks for the review on https://github.com/llvm/llvm-project/pull/120110 and tagging here! I work on ASan at MS, and issues/conversations like these are helpful.

I think it's a reasonable implementation and tradeoff. My initial impression was that there are programs that use `ntdll` as their sole C runtime and thus would lose significant coverage by omitting these functions as candidates for interception. However, there's nothing stopping further changes to the EH machinery / ntdll stack which aggravates interception again.

If this is preferred over https://github.com/llvm/llvm-project/pull/120110, let me know.

**Comment by yjugl** [comment]
For Mozilla, `firefox.exe` imports and uses `ntdll`'s `memset`, whereas our DLLs like `mozglue.dll` and `xul.dll` import and use the one from `VCRUNTIME140.dll`. @glandium, would you know why we have this difference and whether it is intended? If yes, do you think our reasons for using `ntdll`'s `memset` here could apply to other projects?

Nonetheless this patch sounds like a reasonable compromise to me. I got progressively convinced that it's probably just best to not have any instrumentation for these two calls, like this patch suggests. As you mention, the uses of `ntdll`'s `memset` should be fairly marginal, and this instrumentation could be considered out-of-scope in the same way that, more generally, ASAN cannot and will not instrument every memory read/write operation performed by `ntdll`.

For the record here is a summary of [my own attempts](https://phabricator.services.mozilla.com/D228165) at fixing this issue:
- force-committing the shadow memory in `memset` instrumentation, which resulted in too much performance overhead;
- detecting `memset` reentrancy, which seemed to have a more reasonable overhead for non-24H2 platforms with Firefox, but could have had a more significant impact on 24H2 performance, where the reentrant calls would actually occur -- often.

#120110 by @zacklj89 is another attempt at force-committing the shadow memory, this time in a smarter way since it only does that for callers that live in `ntdll`. This should perform better than my own attempt -- perhaps similar to my `memset` reentrancy attempt in that regard.

As far as I am concerned, the correct way forward for Mozilla is probably to stop relying on `ntdll`'s `memset` at all here. And if we have a good reason to keep using it, the tradeoff from this patch seems acceptable -- there are not that many actual calls to this import.

File: compiler-rt/lib/interception/interception_win.cpp [hunk 1]
```diff
@@ -1281,9 +1280,22 @@ uptr InternalGetProcAddress(void *module, const char *func_name) {
...
+  };
+
   bool hooked = false;
   void **DLLs = InterestingDLLsAvailable();
   for (size_t i = 0; DLLs[i]; ++i) {
+    if (DLLs[i + 1] == nullptr) {
+      // This is the last DLL, i.e. NTDLL. It exports some functions that
+      // we only want to override in the CRT.
+      for (const char *ignored : kNtDllIgnore) {
+        if (strcmp(func_name, ignored) == 0)
```
Comment (rnk) [inline compiler-rt/lib/interception/interception_win.cpp:1294]: Is there some `internal_strcmp` function we should be calling instead in order to avoid libc re-entrancy, like hitting the ASan strcmp interceptor, for example?

File: compiler-rt/lib/interception/interception_win.cpp [hunk 2]
```diff
@@ -1281,9 +1280,22 @@ uptr InternalGetProcAddress(void *module, const char *func_name) {
...
+          return hooked;
```
Comment (rnk) [inline compiler-rt/lib/interception/interception_win.cpp:1295]: Nit, let's just `break` or `continue` so the reader doesn't have to think about what `hooked` is, we just hit the shared return codepath.

**Review by rnk — COMMENTED** [review]
I think this is a good way to go,  but in the long run I think we'll need to have flags or special macros on the interceptors to communicate which functions need ntdll interception.

**Comment by glandium** [comment]
> @glandium, would you know why we have this difference and whether it is intended?

Probably the consequence of how things are ordered on the linker command line. No specific intent there, just happenstance.

File: compiler-rt/lib/interception/interception_win.cpp (hunk 1 above)
Comment (zmodem) [reply compiler-rt/lib/interception/interception_win.cpp:1294]: Done.

File: compiler-rt/lib/interception/interception_win.cpp (hunk 2 above)
Comment (zmodem) [reply compiler-rt/lib/interception/interception_win.cpp:1295]: It's a nested loop, I think returning is the most straight-forward.

**Comment by zmodem** [comment]
It sounds like we have consensus on going with this approach. I'll push the button.

**Comment by mstorsjo** [comment]
This patch seems to have broken asan, when running on top of msvcrt.dll (rather than UCRT); this came up when trying to build a release of 20.1.0 RC 1 with msvcrt.dll, at https://github.com/mstorsjo/llvm-mingw/actions/runs/13123676548/job/36623780321. Whenever a process is started, it errors out with this message:
```
AddressSanitizer: CHECK failed: sanitizer_common_interceptors_memintrinsics.inc:239 "((__interception::real_memcpy)) != (0)" (0x0, 0x0) (tid=1128)
```

Given the list of potential DLLs that are attempted to intercept at https://github.com/llvm/llvm-project/blob/69ebac7ad6ae1db9bb19cf3a19ea978af6034ca3/compiler-rt/lib/interception/interception_win.cpp#L1175-L1195, I see that we don't include `msvcrt.dll` in there. I guess that means that previously, the only case of e.g. `memcpy` that was intercepted, was from `ntdll.dll`. For e.g. UCRT builds, we'd also find one in `ucrtbase.dll`, but here we no longer find any at all.

Intercepting `msvcrt.dll` is a bit special though, because even if the user code uses UCRT, most processes end up loading `msvcrt.dll` as well, because this is used by most system DLLs. And I guess in this case, it may have already been used before we get to intercepting it?

I did try adding `msvcrt.dll` to this list, but that doesn't seem to fix the issue entirely either - I'm ending up with errors like this instead:
```
==5236==ERROR: AddressSanitizer: attempting to call malloc_usable_size() for pointer which is not owned:
```

For further context; asan wasn't entirely working in `msvcrt.dll` builds anyway, as far as I  know (I've had a couple of reports where it doesn't, while it works fine in UCRT builds). But it seems to have been working well enough to pass my very minimal smoke tests at least.

I'm wondering what others think about this, which way we should go:
- Reinstate intercepting `ntdll.dll`, if building for mingw + `msvcrt.dll`. While it isn't the entirely right thing to do, we should reach the same level of functionality as before
- Try to intercept `msvcrt.dll`, possibly only in the mingw + `msvcrt.dll` case. But that apparently seems like it would require more work than just adding it to the list.
- Just give up on asan on `msvcrt.dll` - skip testing those aspects in such builds (and maybe skip shipping those DLLs entirely in such builds?)

What do e.g. @alvinhochun @bernhardu @cjacek @lazka @mati865 think about that?

**Comment by zacklj89** [comment]
@mstorsjo just adding some comments here to help with the conversation.

> I did try adding msvcrt.dll to this list, but that doesn't seem to fix the issue entirely either - I'm ending up with errors like this instead:
> ==5236==ERROR: AddressSanitizer: attempting to call malloc_usable_size() for pointer which is not owned:

Presumably this is happening as a result of calls to `_Crt*` APIs or msvcrt initialization routines that are dealing with memory that ASan is not aware of that end up making calls to intercepted APIs?

> Reinstate intercepting ntdll.dll, if building for mingw + msvcrt.dll. While it isn't the entirely right thing to do, we should reach the same level of functionality as before

Perhaps there should be a runtime option (defaulting off) that allows this, as if I remember correctly Mozilla was having both reentrancy and performance issues as a result of this. FWIW, MSVC behaves very similarly to #120110.

**Comment by rnk** [comment]
First, this is just venting, I think everyone who works on Windows already knows this and accepts this, but: The Windows C runtime ecosystem is such a nightmare. ⚡🧠⚡ 

At a really high level, I think the best direction here is to de-escalate the hotpatching wars.

Regarding `msvcrt.dll` ASan compatibility, I cannot remember any attempt to intentionally support WinASan usage in this configuration, so I'm somewhat inclined to say that it was an accident that it ever worked at all. Contributions to support it would be welcome, but we should keep this change in to prioritize the users (Chromium & Firefox) who benefit from this change.

If we want to intentionally support msvcrt.dll, there is prior art for relaxing the CHECK failure in `malloc_usable_size`. See these checks for OWNED_BY_RTL:
https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/asan/asan_malloc_win.cpp#L204

Adding checks for heap ownership on the hot malloc/free codepaths are prohibitively expensive, so we want to minimize those, but these malloc_usable_size APIs are usually much colder and its probably acceptable to add a wide variety of defensive checks there in the name of compatibility and ease of adoption.

My assumption is that calls to malloc from /instrumented DSOs/ are going to be very hot, while malloc calls from precompiled DLLs, system or third party, are going to be much colder. If we could find a way to separate the malloc entry points between instrumented and non-instrumented code, that could allow us to make the non-instrumented memory allocator entry points more flexible, meaning we have fewer CHECK failures and more recovery paths.

This would all be worth doing if it makes future Windows updates smoother.

**Comment by mati865** [comment]
My personal stance regarding msvcrt doesn't change - there is no real reason to use it when building for any somewhat modern Windows.
If somebody wants modern features with it, they should be ready to invest their own time and effort into it.

**Comment by mstorsjo** [comment]
> > I did try adding msvcrt.dll to this list, but that doesn't seem to fix the issue entirely either - I'm ending up with errors like this instead:
> > ==5236==ERROR: AddressSanitizer: attempting to call malloc_usable_size() for pointer which is not owned:
> 
> Presumably this is happening as a result of calls to `_Crt*` APIs or msvcrt initialization routines that are dealing with memory that ASan is not aware of that end up making calls to intercepted APIs?

I'm not entirely sure; surprisingly enough, if I include the same change (to intercept functions in `msvcrt.dll`) in an UCRT build, I'm not hitting the same issue, so the issue is at least not triggered by the background use of `msvcrt.dll` in other system DLLs.

> > Reinstate intercepting ntdll.dll, if building for mingw + msvcrt.dll. While it isn't the entirely right thing to do, we should reach the same level of functionality as before
> 
> Perhaps there should be a runtime option (defaulting off) that allows this, as if I remember correctly Mozilla was having both reentrancy and performance issues as a result of this. FWIW, MSVC behaves very similarly to #120110.

TBH, I'm not really sure if it is worth it.

And as @rnk says:

> Regarding `msvcrt.dll` ASan compatibility, I cannot remember any attempt to intentionally support WinASan usage in this configuration, so I'm somewhat inclined to say that it was an accident that it ever worked at all. Contributions to support it would be welcome, but we should keep this change in to prioritize the users (Chromium & Firefox) who benefit from this change.

Yeah - ASAN is already very complex, so I also agree that we should be wary of adding any extra complexity for something so unimportant as this target.

Especially as it already is known to not really be entirely working; see e.g. https://github.com/mstorsjo/llvm-mingw/issues/224 for a user case. I guess it's mostly surprising that I have been able to include this case in my smoke tests and having those tests passing up until now.

FWIW, to judge the tradeoff a bit better, to what extent it is worth spending effort on it, I wanted to have some sort of measurement on how well it was working before; was it working up to 95% of cases (then perhaps it would be worth spending some more effort on keeping it alive), or did it only manage to work for trivial cases?

I tried running the compiler-rt testsuite with such a toolchain. In mingw UCRT builds, I get clean runs. With msvcrt, I got the following results:

```
check-asan-dynamic:

Total Discovered Tests: 500
  Unsupported      : 243 (48.60%)
  Passed           : 155 (31.00%)
  Expectedly Failed:  19 (3.80%)
  Failed           :  83 (16.60%)

check-interception:

Total Discovered Tests: 14
  Passed: 14 (100.00%)

check-builtins:

Total Discovered Tests: 221
  Unsupported      :  63 (28.51%)
  Passed           : 157 (71.04%)
  Expectedly Failed:   1 (0.45%)

check-profile:

Total Discovered Tests: 145
  Unsupported      : 91 (62.76%)
  Passed           : 52 (35.86%)
  Expectedly Failed:  2 (1.38%)

check-sanitizer:

Total Discovered Tests: 804
  Unsupported: 456 (56.72%)
  Passed     : 348 (43.28%)

check-ubsan:

Total Discovered Tests: 88
  Unsupported      : 16 (18.18%)
  Passed           : 65 (73.86%)
  Expectedly Failed:  2 (2.27%)
  Failed           :  5 (5.68%)
```

So ubsan is mostly working, only a curious handful of testcases that seem to fail for some reason. Asan has got a much higher percentage of tests failing, and I had to disable the gtest based unit tests entirely as they crashed to the point of not getting any json output, so the lit test runner couldn't produce a summary.

So therefore, I guess I'll work around this in my smoke tests, to stop trying to use asan in msvcrt builds. And I'll consider entirely stripping out the asan libraries from those toolchains, so users get a clearer linker error, rather than more obscure runtime errors.
