### PR TITLE
[Clang] Implement CWG2351 `void{}`

### LINKED ISSUE #51552: Failure to compile void{}
|  |  |
| --- | --- |
| Bugzilla Link | [52210](https://llvm.org/bz52210) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid,@xgupta |

## Extended Description
```cpp
void f()
{
    void{};
}
```

This has been considered valid since http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2351 was accepted as a DR in 2018, but Clang fails to compile it, with this error:

```console
<source>:3:9: error: illegal initializer type 'void'
    void{};
        ^
```

### PR DESCRIPTION
**Pull request by MitalAshok**
Per [CWG2351](https://wg21.link/CWG2351), allow `void{}`, treated the same as `void()`: a prvalue expression of type `void` that performs no initialization.

Note that the AST for the expression `T{}` looks like:

```
// using T = int;
CXXFunctionalCastExpr 'T':'int' functional cast to T <NoOp>
`-InitListExpr 'T':'int'
// using T = const int;
CXXFunctionalCastExpr 'int' functional cast to T <NoOp>
`-InitListExpr 'int'
// using T = void;
CXXFunctionalCastExpr 'T':'void' functional cast to T <ToVoid>
`-InitListExpr 'void'
// using T = const void;
CXXFunctionalCastExpr 'void' functional cast to T <ToVoid>
`-InitListExpr 'void'
```

As for `void()`/`T() [T = const void]`, that looked like `CXXScalarValueInitExpr 'void'` and is unchanged after this.

For reference, C++98 [5.2.3p2] says:

> The expression `T()`, where `T` is a simple-type-specifier (7.1.5.2) for a non-array complete object type or the (possibly cv-qualified) void type, creates an rvalue of the specified type, whose value is determined by default-initialization (8.5; no initialization is done for the `void()` case).  [*Note:* if `T` is a non-class type that is *cv-qualified*, the `cv-qualifiers` are ignored when determining the type of the resulting rvalue (3.10). ]

Though it is a bit of a misnomer that, for `T = void`, `CXXScalarValueInitExpr` does not perform value initialization, it would be a breaking change to change the AST node for `void()`, so I simply reworded the doc comment.

Closes #51552.

### CODE REVIEW

**Review by Endilll — COMMENTED** [review]
DR testing part looks fine.
I'm worried there are no regular tests. It's also not clear what happens in 98 mode. New code doesn't seem to care about language mode.

**Comment by MitalAshok** [comment]
Initializer list syntax isn't available in C++98 mode (even as an extension? I can't find the option)  
Even so, as a defect report it should apply to all prior C++ versions.

**Comment by Endilll** [comment]
> Initializer list syntax isn't available in C++98 mode (even as an extension? I can't find the option)

I'm not confident enough to properly review your changes, but my line of thinking is the following: `void()` is available in all language modes, but you're adding C++11-specific functionality (as uniform initializer syntax is not a thing in 98) without ever checking language mode. This sound suspicious enough to me to bring attention to, even if there are other reasons why it's not really necessary to check language mode here (which I'm not aware of, but my knowledge is limited).

> Even so, as a defect report it should apply to all prior C++ versions.

Formally, defect reports apply to then latest publication, which is C++14, if not 17. Implementation indeed try to backport them as far back as they reasonably can. Start accepting uniform initialization syntax in 98 mode because of `void{}` DR doesn't sound reasonable to me.

**Comment by MitalAshok** [comment]
Looking at other places, it looks like init-list stuff is guarded behind `getLangOpts().CPlusPlus11`, so I'll add that check.

It looks like this DR is CD5 (after C++17, applies to C++17), but `void{}` in C++11/14 without a warning seems fine.

As for "regular tests", do you mean in [`/clang/test/CXX`](https://github.com/llvm/llvm-project/tree/main/clang/test/CXX)? Should I also add tests there?

I also found this: https://stackoverflow.com/q/41131806 that `void({})` apparently used to (erroneously) be accepted in Clang 3.8 but I can't find any tests for it

**Comment by Endilll** [comment]
> Looking at other places, it looks like init-list stuff is guarded behind getLangOpts().CPlusPlus11, so I'll add that check.

Corentin told me offline that check for list initialization that you do might be sufficient, as it can't pass in 98.

> It looks like this DR is CD5 (after C++17, applies to C++17), but void{} in C++11/14 without a warning seems fine.

Yes, 11 and 14 are totally fine. We may want a pedantic warning, though.

> As for "regular tests", do you mean in [/clang/test/CXX](https://github.com/llvm/llvm-project/tree/main/clang/test/CXX)? Should I also add tests there?

No, this is C++ conformance test suite. I meant `clang/test/SemaCXX`.

**Comment by cor3ntin** [comment]
I would recommend adding a test in C++98 mode. I don't think gating is necessary, the code should not parse.

Adding a test for ({}) is also a good idea.

**Comment by Endilll** [comment]
LGTM

**Review by cor3ntin — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaExprCXX.cpp [hunk 1]
```diff
@@ -1600,12 +1600,25 @@ Sema::BuildCXXTypeConstructExpr(TypeSourceInfo *TInfo,
...
-  // C++17 [expr.type.conv]p2:
-  //   If the type is cv void and the initializer is (), the expression is a
-  //   prvalue of the specified type that performs no initialization.
-  if (!Ty->isVoidType() &&
-      RequireCompleteType(TyBeginLoc, ElemTy,
-                          diag::err_invalid_incomplete_type_use, FullRange))
+  // C++17 [expr.type.conv]p2, per DR2351:
+  //   If the type is cv void and the initializer is () or {}, the expression is
+  //   a prvalue of the specified type that performs no initialization.
+  if (Ty->isVoidType()) {
```
Comment (shafik) [inline clang/lib/Sema/SemaExprCXX.cpp:1606]: I am trying to understand why the check is here, and I think it is b/c the diagnostic is coming from one of these two lines:

```cpp
InitializationSequence InitSeq(*this, Entity, Kind, Exprs);
  ExprResult Result = InitSeq.Perform(*this, Entity, Kind, Exprs);
```

is that correct? So then we need to handle this case before we attempt the initialization sequence.

**Review by shafik — COMMENTED** [review]
Just a quick question

**Comment by cor3ntin** [comment]
@MitalAshok ping

**Comment by shafik** [comment]
@MitalAshok ping

**Comment by zygoloid** [comment]
> Note that the AST for the expression `T{}` looks like:
> 
> ```
> // using T = int;
> CXXFunctionalCastExpr 'T':'int' functional cast to T <NoOp>
> `-InitListExpr 'T':'int'
> // using T = const int;
> CXXFunctionalCastExpr 'int' functional cast to T <NoOp>
> `-InitListExpr 'int'
> // using T = void;
> CXXFunctionalCastExpr 'void' functional cast to T <NoOp>
> `-InitListExpr 'void'
> // using T = const void;
> CXXFunctionalCastExpr 'void' functional cast to T <NoOp>
> `-InitListExpr 'void'
> ```
> 
> (Since the `InitListExpr` already has `void` before anything is done, the type doesn't need to be adjusted)

Nonetheless, I think it'd be more reasonable to use `CK_ToVoid` here rather than `CK_NoOp`. The `void` type for the `InitListExpr` is just a placeholder and not meant to mean that it's a real expression of type `void`. (We really ought to use a better placeholder there, so we can print the type out as `<braced initializer list>` instead of as `void` in diagnostics.)

**Comment by MitalAshok** [comment]
@zygoloid The commit message was a bit outdated, it now takes the void type from `T` instead of the initializer list (this also preserves extra info like if it came from a typedef)

I've also changed it to `CK_ToVoid`

**Review by zygoloid — APPROVED** [review]
LG

**Comment by MitalAshok** [comment]
Is there anything else that needs to be done for this? Also, thanks for all the reviews and help on this!

**Comment by cor3ntin** [comment]
@MitalAshok feel free to merge in ~2 days if you don't hear back from @shafik

**Comment by MitalAshok** [comment]
Ping @cor3ntin (This missed Clang 19 but could you merge it for Clang 20?)

**Comment by cor3ntin** [comment]
@AaronBallman

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by shafik** [comment]
Looks like this PR was the cause of this regression: https://github.com/llvm/llvm-project/issues/116440
