### PR TITLE
[mlir][llvm] Fix crash in LLVM inliner when callee has no recognized terminator

### LINKED ISSUE #108363: [mlir] -inline crashes in UNREACHABLE executed at /data/szy/MLIR/llvm-release/llvm-project/mlir/include/mlir/Transforms/InliningUtils.h:108!
git version: 8168088f0a9015b

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt -inline a.mlir`

a.mlir:
``` 
llvm.func @test_muli() -> i32 attributes {llvm.emit_c_interface} {
    "test.branch"()[^bb1] {tag = "muli"} : () -> ()
  ^bb1:  // pred: ^bb0
    %0 = llvm.mlir.constant(1 : i32) : i32
    llvm.return %0 : i32
  }
  llvm.func @_mlir_ciface_test_muli() -> i32 attributes {llvm.emit_c_interface} {
    %0 = llvm.call @test_muli() : () -> i32
    llvm.return %0 : i32
  }
``` 
stack trace:

``` 
must implement handleTerminator in the case of multiple inlined blocks
UNREACHABLE executed at /data/szy/MLIR/llvm-release/llvm-project/mlir/include/mlir/Transforms/InliningUtils.h:108!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.  Program arguments: /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -inline a.mlir
 #0 0x000055f72e1082c8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x10dc2c8)
 #1 0x000055f72e105dde llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x10d9dde)
 #2 0x000055f72e108c5d SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f10769a2420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f1075fdf00b raise /build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f1075fbe859 abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:81:7
 #6 0x000055f72e12832f (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x10fc32f)
 #7 0x000055f72e1f26c9 (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11c66c9)
 #8 0x000055f7312b3c74 inlineRegionImpl(mlir::InlinerInterface&, mlir::Region*, mlir::Block*, llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Operation, true, false, void, false, void>, false, false>, mlir::IRMapping&, mlir::ValueRange, mlir::TypeRange, std::optional<mlir::Location>, bool, mlir::CallOpInterface) InliningUtils.cpp:0:0
 #9 0x000055f7312b4b6a mlir::inlineCall(mlir::InlinerInterface&, mlir::CallOpInterface, mlir::CallableOpInterface, mlir::Region*, bool) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4288b6a)
#10 0x000055f7312ad6eb mlir::Inliner::doInlining() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x42816eb)
#11 0x000055f731255575 (anonymous namespace)::InlinerPass::runOnOperation() InlinerPass.cpp:0:0
#12 0x000055f73122f156 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4203156)
#13 0x000055f73122fac0 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4203ac0)
#14 0x000055f731232102 mlir::PassManager::run(mlir::Operation*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4206102)
#15 0x000055f73122a931 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#16 0x000055f73122a58b llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#17 0x000055f7312d6f25 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x42aaf25)
#18 0x000055f7312259b5 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41f99b5)
#19 0x000055f731225c5f mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41f9c5f)
#20 0x000055f731225f8e mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x41f9f8e)
#21 0x000055f72e0e8f07 main (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x10bcf07)
#22 0x00007f1075fc0083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#23 0x000055f72e0e8a8e _start (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x10bca8e)
```

### LINKED ISSUE #118766: [mlir] -inline crashes
git version: adf892d743d91afc1af7893f97c770db31c26916

system: `Ubuntu 18.04.6 LTS`

reproduce with: `mlir-opt  -inline  a.mlir`

a.mlir:  
``` 
module {
  llvm.func @test_muli() -> i64 attributes {llvm.emit_c_interface} {
    "test.foo"() : () -> ()
  }
  llvm.func @_mlir_ciface_test_muli() -> i64 attributes {llvm.emit_c_interface} {
    %0 = llvm.call @test_muli() : () -> i64
    llvm.return %0 : i64
  }
}

``` 
stack trace:

``` 
/data/szy/MLIR/seed/seed0/tmp.mRO4z47uRO.mlir:6:10: error: 'llvm.call' op operation destroyed but still has uses
    %0 = llvm.call @test_muli() : () -> i64
         ^
/data/szy/MLIR/seed/seed0/tmp.mRO4z47uRO.mlir:6:10: note: see current operation: %0 = "llvm.call"() <{CConv = #llvm.cconv<ccc>, TailCallKind = #llvm.tailcallkind<none>, callee = @test_muli, fastmathFlags = #llvm.fastmath<none>, op_bundle_sizes = array<i32>, operandSegmentSizes = array<i32: 0, 0>}> : () -> i64
/data/szy/MLIR/seed/seed0/tmp.mRO4z47uRO.mlir:7:5: note: - use: "llvm.return"(<<UNKNOWN SSA VALUE>>) : (i64) -> ()

    llvm.return %0 : i64
    ^
LLVM ERROR: operation destroyed but still has uses
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt -inline /data/szy/MLIR/seed/seed0/tmp.mRO4z47uRO.mlir
 #0 0x000055e94c826048 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1188048)
 #1 0x000055e94c823b5e llvm::sys::RunSignalHandlers() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1185b5e)
 #2 0x000055e94c8269dd SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f6d36298420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f6d358d500b raise /build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f6d358b4859 abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:81:7
 #6 0x000055e94c846017 llvm::report_fatal_error(llvm::Twine const&, bool) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11a8017)
 #7 0x000055e94c845e36 (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11a7e36)
 #8 0x000055e94fe06b7d mlir::Operation::~Operation() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4768b7d)
 #9 0x000055e94fe0efb2 llvm::iplist_impl<llvm::simple_ilist<mlir::Operation>, llvm::ilist_traits<mlir::Operation>>::erase(llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Operation, true, false, void, false, void>, false, false>) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4770fb2)
#10 0x000055e94fce1169 mlir::Inliner::doInlining() (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x4643169)
#11 0x000055e94fc88d5f (anonymous namespace)::InlinerPass::runOnOperation() InlinerPass.cpp:0:0
#12 0x000055e94fc627a6 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c47a6)
#13 0x000055e94fc630d0 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c50d0)
#14 0x000055e94fc656a2 mlir::PassManager::run(mlir::Operation*) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45c76a2)
#15 0x000055e94fc5df4a performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#16 0x000055e94fc5db9d llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#17 0x000055e94fd09d75 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x466bd75)
#18 0x000055e94fc57b85 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45b9b85)
#19 0x000055e94fc57e2f mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45b9e2f)
#20 0x000055e94fc5815e mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x45ba15e)
#21 0x000055e94c806b37 main (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x1168b37)
#22 0x00007f6d358b6083 __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:342:3
#23 0x000055e94c8066ae _start (/data/szy/MLIR/llvm-release/llvm-project/build/bin/mlir-opt+0x11686ae)
```

### PR DESCRIPTION
**Pull request by joker-eph**
When the callee of an llvm.call has a body block ending with an unregistered op (rather than a recognized LLVM terminator like llvm.return), the LLVM inliner's handleTerminator method was called with that unregistered op and crashed via a cast<LLVM::ReturnOp>() assertion or use-after-erase due to unresolved call result uses.

The root cause is that the generic MLIR verifier conservatively treats unregistered ops as potential terminators (using mightHaveTrait), so malformed IR of this shape passes verification. The inliner, however, assumes that the callee's terminator is a recognized LLVM op.

Fix by adding a guard in LLVMInlinerInterface::isLegalToInline() that refuses to inline a callee containing any block whose last operation does not have the IsTerminator trait. This prevents the crash and leaves the call site intact without any IR mutation.

Fixes #108363
Fixes #118766

### CODE REVIEW

File: mlir/lib/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.cpp [hunk 1]
```diff
@@ -725,6 +725,19 @@ struct LLVMInlinerInterface : public DialectInlinerInterface {
...
         return false;
     }
+    // Refuse to inline if any block in the callee ends with an op that does
+    // not have the terminator trait. The MLIR verifier conservatively accepts
+    // unregistered ops as potential terminators, but the LLVM inliner's
+    // handleTerminator relies on the terminator being a recognized LLVM op
+    // (e.g. llvm.return). Inlining a callee with an unrecognized terminator
+    // would crash.
+    for (Block &block : funcOp.getBody()) {
+      if (!block.empty() && !block.back().hasTrait<OpTrait::IsTerminator>()) {
```
Comment (matthias-springer) [inline mlir/lib/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.cpp]: Is it enough to check for `IsTerminator`? Based on the comment, it sounds like it must be an LLVM op.

Comment (joker-eph) [reply mlir/lib/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.cpp]: Added test to show CF branch and updated the comment here, PTAL!

**Review by krzysz00 — APPROVED** [review]
