### PR TITLE
[CodeGen] Fix non-determinism in MachineBlockHashInfo

### LINKED ISSUE #173933: Flaky test: CodeGen/X86/basic-block-sections-clusters-bb-hash.ll
Looks like the test:

```console
CodeGen/X86/basic-block-sections-clusters-bb-hash.ll
```

Might be flaky. It looks like it is failing randomly during post commit e.g.:

https://lab.llvm.org/buildbot/#/builders/169/builds/18446
https://lab.llvm.org/buildbot/#/builders/169/builds/18442
https://lab.llvm.org/buildbot/#/builders/169/builds/18427

### PR DESCRIPTION
**Pull request by vitalybuka**
The previous implementation used `hash_value(MachineOperand)`, which
is not guaranteed to be stable across different executions because it
hashes pointers for certain operand types (like MBB, GlobalAddress, etc).

Use existing stableHashValue which has no problem.
    
The rest of the file should the same, but it may break profile compatibility.
Changing behavior for Operand is not an issue, as existing one is a low quality RNG.

Code does not have test coverage, it will be fixed in #192911.

Fixes #173933.

### CODE REVIEW

File: llvm/lib/CodeGen/MachineBlockHashInfo.cpp [hunk 1]
```diff
@@ -11,12 +11,100 @@
...
+}
+
+static uint64_t hashCombine() { return 0; }
+
+template <typename T, typename... Ts>
+uint64_t hashCombine(const T &Hash, const Ts &...Args) {
+  return hashing::detail::hash_16_bytes(hashValue(Hash), hashCombine(Args...));
+}
+
+static uint64_t hashOpearand(const MachineOperand &MO) {
```
Comment (thurstond) [inline llvm/lib/CodeGen/MachineBlockHashInfo.cpp]: "hashOperand"?

File: llvm/lib/CodeGen/MachineBlockHashInfo.cpp [hunk 2]
```diff
@@ -11,12 +11,111 @@
...
+
+static uint64_t hashCombine() { return 0; }
+
+template <typename T, typename... Ts>
+uint64_t hashCombine(const T &Hash, const Ts &...Args) {
+  return hashing::detail::hash_16_bytes(hashValue(Hash), hashCombine(Args...));
+}
+
+// Similar to hash_code llvm::hash_value(const MachineOperand &MO) but stable.
+static uint64_t hashOperand(const MachineOperand &MO) {
```
Comment (arsenm) [inline llvm/lib/CodeGen/MachineBlockHashInfo.cpp]: This is mostly a copy. Can you just add an option to skip pointers instead of duplicating all of it?

Comment (vitalybuka) [reply llvm/lib/CodeGen/MachineBlockHashInfo.cpp]: Documentation explicitly says that hash_code and frieands are:
```
//     execution of the program has a high probability of producing a different
//     hash_code for a given input. Thus their values are not stable to save or
//     persist, and should only be used during the execution for the
//     construction of hashing datastructures.
```

Comment (vitalybuka) [reply llvm/lib/CodeGen/MachineBlockHashInfo.cpp]: I even think entire thing should be converted into llvm::stable_hash_combine and  xxHash64, 
hash_16_bytes does not promise stability as well

but there is actually llvm/lib/CodeGen/MachineStableHash.cpp :)

Comment (vitalybuka) [reply llvm/lib/CodeGen/MachineBlockHashInfo.cpp]: Done

**Review by arsenm — APPROVED** [review]

**Comment by vitalybuka** [comment]
Landing, hopefully flakiness will be gone https://lab.llvm.org/buildbot/#/builders/sanitizer-x86_64-linux-fast
