### PR TITLE
[OpenMP][FIX] Allocate per launch memory for GPU team reductions

### LINKED ISSUE #70249: [OpenMP] incorrect concurrent target reduction
```
#include <iostream>
#include <vector>

#define N 4

int main()
{
  std::vector<int> avec(N);
  int* a = avec.data();
  #pragma omp parallel for
  for(int i = 0; i < N; i++)
  {
    a[i] = 0;
    #pragma omp target teams distribute parallel for reduction(+:a[i])
    for(int j =0 ;j< N; j++)
      a[i] += 1;
  }

  std::cout << "results:";
  for(int i = 0; i < N; i++)
    std::cout << " " << a[i];
  std::cout << std::endl;
}
```
running `clang++ -fopenmp --offload-arch=sm_80 main.cpp && ./a.out`
expect
```
results: 4 4 4 4
```
but I got random failure
```
results: 0 4 0 0
results: 4 0 4 0
results: 4 0 4 0
```

Turning on debugging info
```
OMP_TARGET_OFFLOAD=mandatory OMP_NUM_THREADS=32 LIBOMPTARGET_DEBUG=1 ./a.out >& out && grep "Moving 4 bytes\|result" out
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c27c) -> (tgt:0x00007f7112600000)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c278) -> (tgt:0x00007f7112600200)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c274) -> (tgt:0x00007f7112600400)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c270) -> (tgt:0x00007f7112600600)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600000) -> (hst:0x00005572a0d9c27c)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600400) -> (hst:0x00005572a0d9c274)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600600) -> (hst:0x00005572a0d9c270)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600200) -> (hst:0x00005572a0d9c278)
results: 4 0 4 0
```
Mapping and transfers seem OK to me. The failure was miserable.

setting `OMP_NUM_THREADS=1` the test passes reliably.

### PR DESCRIPTION
**Pull request by jdoerfert**
We used to perform team reduction on global memory allocated in the
runtime and by clang. This was racy as multiple instances of a kernel,
or different kernels with team reductions, would use the same locations.
Since we now have the kernel launch environment, we can allocate dynamic
memory per-launch, allowing us to move all the state into a non-racy
place.

Fixes: https://github.com/llvm/llvm-project/issues/70249

### CODE REVIEW

File: openmp/libomptarget/DeviceRTL/src/Reduction.cpp [hunk 1]
```diff
@@ -194,6 +191,9 @@ int32_t __kmpc_nvptx_teams_reduce_nowait_v2(
     ThreadId = 0;
   }
 
+  uint32_t &IterCnt = state::getKernelLaunchEnvironment().ReductionIterCnt;
+  uint32_t &Cnt = state::getKernelLaunchEnvironment().ReductionCnt;
```
Comment (shiltian) [inline openmp/libomptarget/DeviceRTL/src/Reduction.cpp:195]: These two variables seem not used anywhere else.

File: openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.h [hunk 2]
```diff
@@ -387,7 +387,7 @@ struct GenericKernelTy {
   KernelEnvironmentTy KernelEnvironment;
 
   /// The prototype kernel launch environment.
-  KernelLaunchEnvironmentTy KernelLaunchEnvironment;
+  KernelLaunchEnvironmentTy KernelLaunchEnvironment = {0, 0};
```
Comment (shiltian) [inline openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.h:390]:
```suggestion
  KernelLaunchEnvironmentTy KernelLaunchEnvironment = {0, 0, nullptr};
```

**Review by shiltian — APPROVED** [review]
LG with some nits

File: openmp/libomptarget/DeviceRTL/src/Reduction.cpp (hunk 1 above)
Comment (jdoerfert) [reply openmp/libomptarget/DeviceRTL/src/Reduction.cpp:195]: They are, I replaced the globals with them.
