### PR TITLE
[Clang] incorrect assertion when checking template template parameter of a lambda

### LINKED ISSUE #136432: Compiler crash, fails to compile
Clang crashes when compiling my code. As instructed in the failure message, here is the backtrace, preprocessed source, and associated run script:

[Flash-90296d.zip](https://github.com/user-attachments/files/19821407/Flash-90296d.zip)

### LINKED ISSUE #137014: ICE in getLambdaCallOperatorHelper
The following reduced code ICEs clang 20.1.

```cpp
template < template < typename> typename> struct TypeTList;
template < typename >
constexpr auto LambdaThing = []< template < typename> typename... Args >( TypeTList< Args... > ) {};
template < template < typename > typename TheThingT, typename TheParam >
struct TraitApplier {
    template < typename >
    using X = TheThingT< TheParam >;
};
template < typename Traits >
concept FooTraitsConcept = requires {
    LambdaThing< typename Traits::FooTypes >;
};
template < FooTraitsConcept >
class Foo;
struct FooTraits {
    using FooTypes = int;
};
void foo() {
    TraitApplier< Foo, FooTraits> x;
}
```

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-20.1.0/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -fno-verbose-asm -S --gcc-toolchain=/opt/compiler-explorer/gcc-14.2.0 -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<source>:19:36: current parser token ';'
2.	<source>:18:12: parsing function body 'foo'
3.	<source>:18:12: in compound statement ('{}')
4.	<source>:5:8: instantiating class definition 'TraitApplier<Foo, FooTraits>'
  #0 0x0000000003a59568 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x3a59568)
  #1 0x0000000003a576ac llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x3a576ac)
  #2 0x00000000039a69e8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
  #3 0x00007235a6442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
  #4 0x0000000007375203 getLambdaCallOperatorHelper(clang::CXXRecordDecl const&) (.part.0) DeclCXX.cpp:0:0
  #5 0x00000000073760db clang::CXXRecordDecl::getLambdaCallOperator() const (/opt/compiler-explorer/clang-20.1.0/bin/clang+++0x73760db)
......
```

https://godbolt.org/z/qnGbPzTKv

This appears to be a clang 20.x regression.

### LINKED ISSUE #138018: ICE on clang: Assertion `!Calls.empty() && "Missing lambda call operator!"'
> clang HEAD from a couple hours ago (git@github.com:llvm/llvm-project e79d8f6892aa138bfef65334817c24d3d9881855) crashes:
> 
> [kabang_avnd-8e80cb.zip](https://github.com/user-attachments/files/19841836/kabang_avnd-8e80cb.zip) 

 _Originally posted by @jcelerier in [#136635](https://github.com/llvm/llvm-project/issues/136635#issuecomment-2819810879)_

Reduced:
```cpp
struct foo { };

template <typename T>
struct vec { };

auto structure_to_typelist(const auto& s) noexcept {
  return []<template <typename...> typename T, typename... Args>(T<Args...>) {
    return 0;
  }(vec<int>{});
}

template <typename T>
using helper2 = decltype(structure_to_typelist(T{}));
auto tl_ok2 = helper2<foo>{};

```

### PR DESCRIPTION
**Pull request by cor3ntin**
When a lambda is used in an alias declaration, we were trying to refer to its call operator. However, that could happen before (or during) the call operator is defined.

So we should not assume a lambda always has a call operator.

Fixes #136432
Fixes #137014
Fixes #138018

### CODE REVIEW

**Review by zyn0217 — APPROVED** [review]

File: clang/lib/AST/DeclCXX.cpp [hunk 1]
```diff
@@ -1696,7 +1696,11 @@ static NamedDecl* getLambdaCallOperatorHelper(const CXXRecordDecl &RD) {
       RD.getASTContext().DeclarationNames.getCXXOperatorName(OO_Call);
 
   DeclContext::lookup_result Calls = RD.lookup(Name);
-  assert(!Calls.empty() && "Missing lambda call operator!");
+
+  // This can happen while building the lambda.
+  if (Calls.empty())
+    return nullptr;
```
Comment (erichkeane) [inline clang/lib/AST/DeclCXX.cpp:1702]: So I'm REALLY concerned about this.  I don't think it is wrong, but just that we need to make sure we handle this value correctly.  At least `getLambdaStaticInvoker` doesn't handle the `nullptr` correctly (though I guess the other two uses DO, so thats fine).

I wouldn't mind a bit of an audit to make sure that uses of `getLambdaStaticInvoker` (and perhaps the others, but as they already acknowledged they could return null, i'm mildly less concerned) do a reasonable thing.

**Review by erichkeane — APPROVED** [review]
I'm concerned about the static-invoker ending up just being an assert, but I guess that is no behavioral change (just 1 assert to another).

File: clang/lib/AST/DeclCXX.cpp (hunk 1 above)
Comment (cor3ntin) [reply clang/lib/AST/DeclCXX.cpp:1702]: I added an assert, which hinges on the fact that we don't look at the static invoker in cases where the lambda is incomplete.
I agree that having these various states in lambdas is a bit unfortunate, but it is a consequence of P2036.
If you have a better solution, I'm all ears!
