### PR TITLE
[AMDGPU][MC] Disable sendmsg SYSMSG_OP_HOST_TRAP_ACK on gfx9+

### LINKED ISSUE #52903: [AMDGPU][MC][GFX9][GFX10] Disable SYSMSG_OP_HOST_TRAP_ACK
SYSMSG_OP_HOST_TRAP_ACK is not supported on GFX9 and GFX10. Update sendmsg accordingly.

An example of failed test:
    s_sendmsg sendmsg(MSG_SYSMSG, SYSMSG_OP_HOST_TRAP_ACK)
Expected result:
    an error message
Actual result:
    s_sendmsg sendmsg(MSG_SYSMSG, SYSMSG_OP_HOST_TRAP_ACK) ; encoding: [0x3f,0x00,0x90,0xbf]

### PR DESCRIPTION
**Pull request by epilk**
This is no longer supported as of gfx9. Fixes #52903

### CODE REVIEW

File: llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp [hunk 1]
```diff
@@ -1953,7 +1953,9 @@ bool isValidMsgOp(int64_t MsgId, int64_t OpId, const MCSubtargetInfo &STI,
     return 0 <= OpId && isUInt<OP_WIDTH_>(OpId);
 
   if (MsgId == ID_SYSMSG)
```
Comment (arsenm) [inline llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp:1955]: Braces

File: llvm/test/MC/AMDGPU/gfx9-asm-err.s [hunk 2]
```diff
@@ -41,3 +41,6 @@ global_load_dword v[2:3], off
 
 scratch_load_dword v2, off, offset:256
 // GFX9ERR: :[[@LINE-1]]:{{[0-9]+}}: error: too few operands for instruction
+
+s_sendmsg sendmsg(MSG_SYSMSG, SYSMSG_OP_HOST_TRAP_ACK)
+// GFX9ERR: :[[@LINE-1]]:{{[0-9]+}}: error: invalid operation id
```
Comment (arsenm) [inline llvm/test/MC/AMDGPU/gfx9-asm-err.s:46]: Error message leaves something to be desired. Can it mention the lack of support on the target, that shows it is recognized?

Comment (epilk) [reply llvm/test/MC/AMDGPU/gfx9-asm-err.s]: Sure, fixed in the update. I ended up doing a bit of refactoring to support this cleanly.

**Review by arsenm — APPROVED** [review]
