### PR TITLE
[ELF] Support DW_EH_PE_sdata8 encoding in .eh_frame_hdr

### LINKED ISSUE #172777: [lld/ELF] eh_frame_hdr generation only supports 32-bit values
trying the large code model on some binaries, we're running into lld complaining about eh_frame_hdr values not fitting in 32 bits:

```
$ cat /tmp/a.c
int main() {}
$ cat /tmp/bigtext.lds 
SECTIONS
{
    .ltext :
    {
        *(.ltext)
        *(.ltext.*)

        . = ALIGN(4);

        . = MAX(., 0x100000000);

    }
}
$ clang -fuse-ld=lld -mcmodel=large -T /tmp/bigtext.lds /tmp/a.c -o /tmp/a
ld.lld: error: /tmp/a-bdc8cb.o:(.eh_frame): PC offset is too large: 0xffffffff000002ac
```

according to https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB/ehframehdr.html, 64 bit values are allowed by specifying `DW_EH_PE_sdata8`

lld code that assumes 32 bit eh_frame_hdr values:

https://github.com/llvm/llvm-project/blob/796fafeff92fe5d2d20594859e92607116e30a16/lld/ELF/SyntheticSections.cpp#L616

https://github.com/llvm/llvm-project/blob/796fafeff92fe5d2d20594859e92607116e30a16/lld/ELF/SyntheticSections.cpp#L638

would lld be ok with going to 64 bit values in eh_frame_hdr when any value doesn't fit in 32 bits?

### PR DESCRIPTION
**Pull request by MaskRay**
Currently, both GNU ld and lld only support
`table_enc = DW_EH_PE_datarel | DW_EH_PE_sdata4` for .eh_frame_hdr.
When a table entry exceeds the 32-bit range, we can use
`DW_EH_PE_sdata8` instead of reporting an error
(https://reviews.llvm.org/D49607 introduced the "PC offset is too large"
error). This is useful for certain large executables.

This patch auto-detects when 64-bit encoding is needed and upgrades
the encoding accordingly. We use DW_EH_PE_sdata8 when either a table
entry or eh_frame_ptr exceeds the 32-bit range.

Technically, eh_frame_ptr could remain sdata4 when only table entries
require sdata8, but there is little value in this flexibility since
.eh_frame/.eh_frame_hdr distance is a much less strict constraint than
.text/.eh_frame_hdr distance.

The implementation caches FDE data in EhFrameHeader during
updateAllocSize and reuses it in writeTo.

Previously, `EhFrameSection::getFdePc` was used to read the
`initial_location` value from .eh_frame FDEs. Since the value equals the
relocated symbol's VA for all cases that matter, we now obtain the value
directly and simplify the implementation.

Also update the outdated comment about sorting the FDE list; the ICF
case mentioned there no longer applies after https://reviews.llvm.org/D116093.

In the new test eh-frame-hdr-sdata8.s, 3.lds is carefully crafted to
ensure that .eh_frame_hdr size requires fixed-point iteration (to test
`updateAllocSize`). This is also groundwork for compact unwind support
similar to Mach-O `__unwind_info`.

Close #172777

### CODE REVIEW

**Comment by MaskRay** [comment]
@fzakaria

File: lld/ELF/SyntheticSections.cpp [hunk 1]
```diff
@@ -659,15 +596,65 @@ void EhFrameHeader::writeTo(uint8_t *buf) {
...
+                                 return a.pcRel == b.pcRel;
+                               }),
+                  hdr->fdes.end());
+
+  // Determine if 64-bit encodings are needed.
+  size_t oldSize = hdr->size;
+  int64_t ehFramePtr = getParent()->addr - hdrVA - 4;
+  hdr->large =
+      !isInt<32>(ehFramePtr) || llvm::any_of(hdr->fdes, [](const FdeData &f) {
+        return !isInt<32>(f.pcRel) || !isInt<32>(f.fdeVARel);
```
Comment (aengelke) [inline lld/ELF/SyntheticSections.cpp]: Track in loop above to avoid extra iteration?

File: lld/ELF/SyntheticSections.cpp [hunk 2]
```diff
@@ -659,15 +596,65 @@ void EhFrameHeader::writeTo(uint8_t *buf) {
...
-size_t EhFrameHeader::getSize() const {
-  // .eh_frame_hdr has a 12 bytes header followed by an array of FDEs.
-  return 12 + getPartition(ctx).ehFrame->numFdes * 8;
-}
-
 bool EhFrameHeader::isNeeded() const {
   return isLive() && getPartition(ctx).ehFrame->isNeeded();
 }
 
+bool EhFrameSection::updateAllocSize(Ctx &ctx) {
```
Comment (aengelke) [inline lld/ELF/SyntheticSections.cpp]: What's the reason this is not in EhFrameHeader::updateAllocSize? Likewise for writeTo.

File: lld/ELF/SyntheticSections.cpp [hunk 3]
```diff
@@ -659,15 +596,65 @@ void EhFrameHeader::writeTo(uint8_t *buf) {
...
+    uint8_t enc = getFdeEncoding(rec->cie);
+    if ((enc & 0x70) != DW_EH_PE_absptr && (enc & 0x70) != DW_EH_PE_pcrel) {
+      Err(ctx) << "unknown FDE size encoding";
+      continue;
+    }
+    for (EhSectionPiece *fde : rec->fdes) {
+      // The FDE has passed `isFdeLive`, so the first relocation's symbol is a
+      // live Defined.
+      auto *isec = cast<EhInputSection>(fde->sec);
+      auto &reloc = isec->rels[fde->firstRelocation];
```
Comment (aengelke) [inline lld/ELF/SyntheticSections.cpp]: Is it actually guaranteed that the first relocation must be the symbol or is it just common practice? (There might be a second relocation in the piece for the LSDA.)

**Review by aengelke — COMMENTED** [review]
LGTM otherwise.

File: lld/ELF/SyntheticSections.cpp (hunk 3 above)
Comment (MaskRay) [reply lld/ELF/SyntheticSections.cpp]: In FDE, `initial_location` is the first field, and if relocated, its relocation is the first one. While assemblers aren't strictly required to emit relocations in a specific order, all known assemblers do so predictably. Since our implementation already relies on the firstRelocation assumption elsewhere, I leverage it here as well.

**Review by aengelke — APPROVED** [review]

**Review by aeubanks — APPROVED** [review]

**Review by smithp35 — APPROVED** [review]
LGTM too. I don't have any additional comments over what has been mentioned already.

**Review by fzakaria — COMMENTED** [review]
LGTM but I can't approve.
Left comments but they are purely informative for me as I try to learn the codebase.

File: lld/ELF/SyntheticSections.cpp [hunk 4]
```diff
@@ -602,53 +565,31 @@ void EhFrameSection::writeTo(uint8_t *buf) {
...
+  // eh_frame_ptr_enc
+  hdrBuf[1] = DW_EH_PE_pcrel | (large ? DW_EH_PE_sdata8 : DW_EH_PE_sdata4);
+  // fde_count_enc
+  hdrBuf[2] = DW_EH_PE_udata4;
+  // table_enc
+  hdrBuf[3] = DW_EH_PE_datarel | (large ? DW_EH_PE_sdata8 : DW_EH_PE_sdata4);
+  hdrBuf += 4;
+  writeField(hdrBuf, ehFramePtr);
+  hdrBuf += large ? 8 : 4;
+  write32(ctx, hdrBuf, hdr->fdes.size());
```
[the remark this answers is not in the document]
Comment (MaskRay) [reply lld/ELF/SyntheticSections.cpp]: IIRC the average size of a FDE > 20 bytes. .eh_frame will be at least `(1<<32) * 20` bytes to cause an overflow. `SmallVector` with an >1-byte element type also has a 4GiB entry limit. We don't do anything for such hypothetical overflows.

**Comment by rupprecht** [comment]
We also see the same crash here: https://compiler-explorer.com/z/M4GGxW8oh
