### PR TITLE
[clang-tidy]fix misc-unused-using-decls false positive false for using in elaborated type

### LINKED ISSUE #69714: misc-unused-using-decls incorrectly reports using as unused when it is used in elaborated-type-specifier
```
namespace ns {
 struct Foo {};
}
using ns::Foo; // reported as unused
struct Foo * a; 
```
See https://gcc.godbolt.org/z/WM58br3q1.

It seems that Clang does not store enough information in the AST right now as information about usings gets lost when parsing declaration specifiers.

### PR DESCRIPTION
**Pull request by HerrCai0907**
`ElaboratedType` including tag keywords and any nested-name-specifiers.
We should ignore nested-name-specifiers case but consider tag keywords case for `misc-unused-using-decls` check
Fixes: #69714

### CODE REVIEW

File: clang-tools-extra/clang-tidy/misc/UnusedUsingDeclsCheck.cpp [hunk 1]
```diff
@@ -71,6 +72,10 @@ void UnusedUsingDeclsCheck::registerMatchers(MatchFinder *Finder) {
                          templateArgument().bind("used")))),
                      this);
   Finder->addMatcher(userDefinedLiteral().bind("used"), this);
+  Finder->addMatcher(
+      elaboratedType(unless(hasQualifier(nestedNameSpecifier())),
+                     hasUnqualifiedDesugaredType(type().bind("usedType"))),
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/misc/UnusedUsingDeclsCheck.cpp:77]:
```suggestion
      loc(elaboratedType(unless(hasQualifier(nestedNameSpecifier())),
                     hasUnqualifiedDesugaredType(type().bind("usedType")))),
```

To avoid matching too much.

**Review by PiotrZSL — APPROVED** [review]
