### PR TITLE
[DirectX] Fix bug where Flatten arrays was only using last index

### LINKED ISSUE #142836: [DirectX] GEPs to multi-dimensional arrays are incorrectly flattened
The DXIL Flatten Arrays pass is incorrectly transforming `getelementptr` instructions operating on mutli-dimensional arrays.

The DXIL Flatten Arrays pass needs to be modified to maintain correctness when transforming GEPs on multi-dimensional arrays.

https://godbolt.org/z/evPPPWEfT

IR dump before flatten arrays (`-mllvm -stop-before=dxil-flatten-arrays`):
```llvm
@g = local_unnamed_addr addrspace(3) global [2 x [2 x float]] zeroinitializer, align 4, !dbg !0
...
  %2 = tail call i32 @llvm.dx.thread.id(i32 0)
  %3 = getelementptr inbounds nuw [2 x [2 x float]], ptr addrspace(3) @g, i32 0, i32 %2, i32 1, !dbg !91
  %4 = load float, ptr addrspace(3) %3, align 4, !dbg !91, !tbaa !92
```

IR dump after flatten arrays:
```llvm
@g.1dim = local_unnamed_addr addrspace(3) global [4 x float] zeroinitializer, align 4
...
  %2 = tail call i32 @llvm.dx.thread.id(i32 0)
  %3 = getelementptr inbounds [4 x float], ptr addrspace(3) @g.1dim, i32 1
  %4 = load float, ptr addrspace(3) %3, align 4, !dbg !91
```

As can be seen, the GEP after flatten arrays is incorrect (such as `%2` becoming unused) and out-of-bounds (because `g.1dim` is only one array, so `i32 1` is OOB).

A similar case can be seen for local arrays: https://godbolt.org/z/M7xaxGhMa

### PR DESCRIPTION
**Pull request by farzonl**
fixes #142836

We added a function called `collectIndicesAndDimsFromGEP` which builds the  Indicies and Dims up for the recursive case and the base case. really to solve #142836 we didn't need to add it to the recursive case. The recursive cases exists for gep chains which are ussually two indicies per gep ie ptr index and array index. adding collectIndicesAndDimsFromGEP to the recursive cases means we can now do some mixed mode indexing say we get a case where its not the ussual 2 indicies but instead 3 we can now treat those last two indicies as part of the computation for the flat array index.

### CODE REVIEW

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp [hunk 1]
```diff
@@ -218,6 +225,29 @@ bool DXILFlattenArraysVisitor::visitAllocaInst(AllocaInst &AI) {
...
 
+void DXILFlattenArraysVisitor::collectIndicesAndDimsFromGEP(
+    GetElementPtrInst &GEP, SmallVectorImpl<Value *> &Indices,
+    SmallVectorImpl<uint64_t> &Dims, bool &AllIndicesAreConstInt) {
+
+  // Skip the first index (which is ptr index ie always start at 0 for arrays)
+  // and collect all subsequent indices
+  Type *CurrentType = GEP.getSourceElementType();
+  for (unsigned I = 1; I < GEP.getNumIndices(); ++I) {
+    Value *Index = GEP.getOperand(I + 1); // +1 because operand 0 is the pointer
```
Comment (joaosaffran) [inline llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: Just to make sure this is the intended implementation: this will always check index 2 onwards, since `I` start at 1, and you are adding 1 to it when getting the operands. 

The comments, made me confused, so want to double-check you are intentionally skipping index 1.

**Review by joaosaffran — APPROVED** [review]
LGTM, just a question double-checking the logic to get the indexes from GEP calls

File: llvm/test/CodeGen/DirectX/flatten-array.ll [hunk 2]
```diff
@@ -187,5 +187,75 @@ define void @global_gep_store() {
...
+    ; CHECK-NEXT: getelementptr inbounds [16 x i32], ptr %.1dim, i32 0, i32 1
+    ; CHECK-NEXT: getelementptr inbounds [16 x i32], ptr %.1dim, i32 0, i32 3
+    ; CHECK-NEXT: getelementptr inbounds [16 x i32], ptr %.1dim, i32 0, i32 7
+    ; CHECK-NEXT: getelementptr inbounds [16 x i32], ptr %.1dim, i32 0, i32 15
+    ; CHECK-NEXT:    ret void
+    %1 = alloca [2x[2 x[2 x [2 x i32]]]], align 4
+    %2 = getelementptr inbounds [2x[2 x[2 x [2 x i32]]]], [2x[2 x[2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 0, i32 0, i32 1
+    %3 = getelementptr inbounds [2x[2 x[2 x [2 x i32]]]], [2x[2 x[2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 0, i32 1, i32 1
+    %4 = getelementptr inbounds [2x[2 x[2 x [2 x i32]]]], [2x[2 x[2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 1, i32 1, i32 1
+    %5 = getelementptr inbounds [2x[2 x[2 x [2 x i32]]]], [2x[2 x[2 x [2 x i32]]]]* %1, i32 0, i32 1, i32 1, i32 1, i32 1
```
Comment (Icohedron) [inline llvm/test/CodeGen/DirectX/flatten-array.ll]: nit: inconsistent spacing in the array type specifiers in this test and more below in the same file
```suggestion
    %1 = alloca [2 x [2 x [2 x [2 x i32]]]], align 4
    %2 = getelementptr inbounds [2 x [2 x [2 x [2 x i32]]]], [2 x [2 x [2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 0, i32 0, i32 1
    %3 = getelementptr inbounds [2 x [2 x [2 x [2 x i32]]]], [2 x [2 x [2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 0, i32 1, i32 1
    %4 = getelementptr inbounds [2 x [2 x [2 x [2 x i32]]]], [2 x [2 x[2 x [2 x i32]]]]* %1, i32 0, i32 0, i32 1, i32 1, i32 1
    %5 = getelementptr inbounds [2 x [2 x [2 x [2 x i32]]]], [2 x [2 x [2 x [2 x i32]]]]* %1, i32 0, i32 1, i32 1, i32 1, i32 1
```

**Review by Icohedron — APPROVED** [review]

File: llvm/lib/Target/DirectX/DXILFlattenArrays.cpp (hunk 1 above)
Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: Operand 0 is the ptr operand of the GEP.
Operand 1 is the first index operand which we skip because it will always be 0.
Therefore Operand 2 is the second index operand which is what we want. So yes, this is intentional.

Comment (joaosaffran) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: Gotcha, can we make this clear in the comments, please

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: fixed. I think i made the comment more clear that operand at index 0 is the ptr and  operand at index 1 is the ptr index. Since we always add the  0 pointer index in Builder.CreateGEP we want to skip these

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:236]: @Icohedron  maybe it makes more sense to start I at 2 and do I -1 for Index?

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp:236]: Or `GEP.getOperand(GEP->getPointerOperandIndex() + I);` to be clear that the `1` is the pointer operand.

Comment (Icohedron) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: You could also iterate over `GEP->indices()` and skip the first iteration.

Comment (farzonl) [reply llvm/lib/Target/DirectX/DXILFlattenArrays.cpp]: That is unfortunately an iterator.
