### PR TITLE
[MLIR][Operation] Fix `isBeforeInBlock` crash bug mentioned in https://github.com/llvm/llvm-project/issues/60909

### LINKED ISSUE #60909: [mlir] Using `convert-scf-to-cf` and `test-print-liveness` together cause segment fault
The problem only appears if we use a single command line on the IR below. 
Instead, if we first do `convert-scf-to-cf`, copy the output IR to a file, and then apply `test-print-liveness` on the file, we don't observe the problem.
(Please bear with me on the weird variable names; it's modified from triton IR)

We found one possible explanation.
Maybe `isBeforeInBlock` should add an edge case for `other == this` because `updateOrderIfNecessary` is expected to only be invoked on blocks with more than one. After skipping `updateOrderIfNecessary` when `other == this`, we did solve the problem but it doesn't explain why separating `convert-scf-to-cf` and `test-print-liveness` could avoid the problem.

https://github.com/llvm/llvm-project/blob/fd5d92e6220905f7d942a81108266d427babe143/mlir/lib/IR/Operation.cpp#L274
https://github.com/llvm/llvm-project/blob/fd5d92e6220905f7d942a81108266d427babe143/mlir/lib/IR/Operation.cpp#L304

cc @ptillet

Tested with f50cad2c55dfab4ff3da010a64119b4a93522289

Reproduced with:

```shell
mlir-opt -pass-pipeline="builtin.module(func.func(convert-scf-to-cf), func.func(test-print-liveness))" ./test.mlir
```

```mlir
func.func @for_if_for(%lb : index, %ub : index, %step : index, %i1 : i1) {
 %a_shared_init = arith.constant dense<0.00e+00> : tensor<128x32xf16>
 %b_shared_init = arith.constant dense<0.00e+00> : tensor<128x32xf16>
 %c_shared_init = arith.constant dense<0.00e+00> : tensor<128x32xf16>
 %c_blocked = arith.negf %c_shared_init : tensor<128x32xf16>

 %a_shared, %b_shared, %c_shared = scf.for %iv = %lb to %ub step %step iter_args(%a_shared = %a_shared_init, %b_shared = %b_shared_init, %c_shared = %c_shared_init) -> (tensor<128x32xf16>, tensor<128x32xf16>, tensor<128x32xf16>) {
  %c_shared_next_next = scf.if %i1 -> tensor<128x32xf16> {
   %cst0 = arith.constant dense<0.00e+00> : tensor<128x32xf16>
   scf.yield %cst0 : tensor<128x32xf16>
  } else {
   %c_shared_ = scf.for %jv = %lb to %ub step %step iter_args(%c_shared_next = %c_shared) -> (tensor<128x32xf16>) {
    %c_blocked_next = arith.negf %c_shared_next : tensor<128x32xf16>
    scf.yield %c_shared_next : tensor<128x32xf16>
   }
   scf.yield %c_shared_ : tensor<128x32xf16>
  }
  %b_blocked_next = arith.negf %b_shared: tensor<128x32xf16>
  scf.yield %a_shared, %b_shared, %c_shared_next_next : tensor<128x32xf16>, tensor<128x32xf16>, tensor<128x32xf16>
 }
 return
}
```

### PR DESCRIPTION
**Pull request by wang-y-z**
# summary
This MR fix `isBeforeInBlock` crash bug mentioned in https://github.com/llvm/llvm-project/issues/60909. Fixes #60909.
# Trigger condition
1. A block only have one operation.
2. `block->isOpOrderValid()` is true, but `op->hasValidOrder()` is false.
3. call: `op->isBeforeInBlock(op)`, compared with op itself.

Will crash on `assert(blockFront != blockBack && "expected more than one operation");`

# Case study
Simplified repro case in `mlir/test/Pass/scf2cf-print-liveness-crash.mlir`
When put `-convert-scf-to-cf -test-print-liveness` together in one cmd line, the first pass will work normally and crash on the second pass.
Details please refer  https://github.com/llvm/llvm-project/issues/60909

# Solutions
option1. in `isBeforeInBlock`, check if block only have one operation before step into `updateOrderIfNecessary`, if have only one, it must return false
option2. in `isBeforeInBlock`, check if `this == other`, if true return false
option3. fix `addNodeToList` logic

I prefer option3: 

When a block contains only one operation and the user calls op->isBeforeInBlock(op), if block->isOpOrderValid() returns true, updateOrderIfNecessary is called. If op->hasValidOrder() is false, it will crash at the assertion assert(blockFront != blockBack && "expected more than one operation");.

This behavior is abnormal and needs fixing. I discovered that after the first pass of `-convert-scf-to-cf`, there is a block with only one operation where the block order is valid but the operation order is invalid, leading to a crash when `-test-print-liveness` pass runs.

### CODE REVIEW

**Comment by wang-y-z** [comment]
Hi @joker-eph  , could you please help to review this PR, thanks in advance

File: mlir/lib/IR/Operation.cpp [hunk 1]
```diff
@@ -391,7 +391,7 @@ bool Operation::isBeforeInBlock(Operation *other) {
   // parent.
   if (!block->isOpOrderValid()) {
     block->recomputeOpOrder();
-  } else {
+  } else if (block->getOperations().size() > 1) {
```
Comment (joker-eph) [inline mlir/lib/IR/Operation.cpp:394]: That is costly, it's a linear scan.

However you could do:
```
  if (!llvm::hasSingleElement(*block)) {
```

Should this be done in `updateOrderIfNecessary` though?

Comment (wang-y-z) [reply mlir/lib/IR/Operation.cpp]: Thanks for pointing this out. You are right, and this `hasSingleElement` solution works as well.

I conducted an investigation on `updateOrderIfNecessary` and would like to propose another fix for `addNodeToList` that could address the root cause of the crash occurring with the `-convert-scf-to-cf -test-print-liveness` combination.

When a block contains only one operation and the user calls `op->isBeforeInBlock(op)`, if `block->isOpOrderValid()` returns true, `updateOrderIfNecessary` is called. If `op->hasValidOrder()` is false, it will crash at the assertion `assert(blockFront != blockBack && "expected more than one operation");`. 

This behavior is abnormal and needs fixing. I discovered that after the first pass of `-convert-scf-to-cf`, there is a block with only one operation where the **block order is valid** but the **operation order is invalid**, leading to a crash when `-test-print-liveness` pass runs.

Please review it again, thanks : )

**Review by joker-eph — APPROVED** [review]
Nice find! LG, thanks!

**Comment by joker-eph** [comment]
@River707  can you double check this? Wanna make sure I didn't miss something, this seems too obvious of a bug.

**Comment by River707** [comment]
> @River707 can you double check this? Wanna make sure I didn't miss something, this seems too obvious of a bug.

Let me double check, the addNodeToList method was supposed to be in-combination with another method (that would actually invalidate the list).

**Comment by River707** [comment]
Sorry, didn't have the time to look at this PR until now. I don't think the solution here is the one we want. It'll be overly conservative and thrash the order of a block every time an operation gets added (which makes the dominance checks a lot more expensive when transformations happen). Can we instead just update `updateOrderIfNecessary` to support single operation blocks? There isn't really a good reason why I didn't do that originally and the code has changed a lot around it.

**Comment by wang-y-z** [comment]
> Sorry, didn't have the time to look at this PR until now. I don't think the solution here is the one we want. It'll be overly conservative and thrash the order of a block every time an operation gets added (which makes the dominance checks a lot more expensive when transformations happen). Can we instead just update `updateOrderIfNecessary` to support single operation blocks? There isn't really a good reason why I didn't do that originally and the code has changed a lot around it.

Thanks for pointing this from performance perspective, and I had a minor fix on `updateOrderIfNecessary`, please review it : )

File: mlir/test/Pass/scf2cf-print-liveness-crash.mlir [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+        %2 = scf.for %arg6 = %arg0 to %arg1 step %arg2 iter_args(%arg7 = %arg5) -> (tensor<128x32xf16>) {
+          scf.yield %arg7 : tensor<128x32xf16>
+        }
+        scf.yield %2 : tensor<128x32xf16>
+      }
+      scf.yield %1 : tensor<128x32xf16>
+    }
+    return
+  }
+}
```
Comment (grypp) [inline mlir/test/Pass/scf2cf-print-liveness-crash.mlir:19]: nit : nl

File: mlir/test/Pass/scf2cf-print-liveness-crash.mlir [hunk 3]
```diff
@@ -0,0 +1,19 @@
+// RUN: mlir-opt %s -pass-pipeline="builtin.module(func.func(convert-scf-to-cf), func.func(test-print-liveness))"
```
Comment (grypp) [inline mlir/test/Pass/scf2cf-print-liveness-crash.mlir:1]: Nit : Can we make filename more generic? We could add other tests other than crash
`scf2cf-print-liveness-crash.mlir` -> `scf-to-cf-and-print-liveness.mlir`

**Review by grypp — COMMENTED** [review]
Thanks for fixing this. I've recently encountered this problem. :)

I am not familiar with this part of the compiler, but I think @River707 or @joker-eph are!

File: mlir/test/Pass/scf2cf-print-liveness-crash.mlir (hunk 2 above)
Comment (wang-y-z) [reply mlir/test/Pass/scf2cf-print-liveness-crash.mlir]: Thanks for reviewing this, added a new line

File: mlir/test/Pass/scf2cf-print-liveness-crash.mlir (hunk 3 above)
Comment (wang-y-z) [reply mlir/test/Pass/scf2cf-print-liveness-crash.mlir]: Sure, fixed

**Review by River707 — APPROVED** [review]
Thought I approved this, LGTM!
