### PR TITLE
[llvm][ELF]Add Shdr check for getBuildID

### LINKED ISSUE #126418: llvm-objdump crashed
log:

```
kernel/xCore:   file format elf64-x86-64
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-objdump -D kernel/xCore
```

`kernel/xCore` is uploaded [here](https://github.com/yiming564/SharedFile).

I am using Ubuntu 24.04 + WSL2. This fault can be stably reproduced.

### PR DESCRIPTION
**Pull request by cabbaken**
Add Section Header check for getBuildID, fix crash with invalid Program Header.

Fixes: #126418

### CODE REVIEW

**Comment by cabbaken** [comment]
I referred related logic of `llvm-readelf` which can correctly read the malformed program header, so I think the Section Header check is necessary.
Please let me know if there are additional considerations to be aware of.

**Comment by cabbaken** [comment]
This patch modifies a header that makes `llvm-symbolizer` crash, I will fix it soon.

File: llvm/include/llvm/Object/ELFTypes.h [hunk 1]
```diff
@@ -660,7 +660,7 @@ class Elf_Note_Impl {
 
   /// Get the note's descriptor.
   ArrayRef<uint8_t> getDesc(size_t Align) const {
-    if (!Nhdr.n_descsz)
+    if (!Nhdr.n_descsz || !Align)
```
Comment (jh7370) [inline llvm/include/llvm/Object/ELFTypes.h:663]: I'm not following why this check has been modified?

File: llvm/lib/Object/BuildID.cpp [hunk 2]
```diff
@@ -24,6 +24,20 @@ using namespace llvm::object;
...
+  if (!Sections.empty()) {
+    for (const auto &S : Sections) {
+      if (S.sh_type != ELF::SHT_NOTE)
+        continue;
+      Error Err = Error::success();
+      for (auto N : Obj.notes(S, Err))
+        if (N.getType() == ELF::NT_GNU_BUILD_ID &&
+            N.getName() == ELF::ELF_NOTE_GNU)
+          return N.getDesc(S.sh_addralign);
+      consumeError(std::move(Err));
```
Comment (jh7370) [inline llvm/lib/Object/BuildID.cpp:37]: I assume it is, but please check that `consumeError` is safe if `Err` is `Error::success()`.

**Review by jh7370 — COMMENTED** [review]
Don't include the issue reference in the PR/commit title: there's no need, because you mentioned it in the body.

This PR appears to be missing tests?

**Comment by cabbaken** [comment]
> Don't include the issue reference in the PR/commit title: there's no need, because you mentioned it in the body.

ok, I will modify it.

> This PR appears to be missing tests?

Yes, I am trying to construct a test, but I need to learn some basic syntax of the test-suite. I will add the test later.

File: llvm/include/llvm/Object/ELFTypes.h (hunk 1 above)
Comment (cabbaken) [reply llvm/include/llvm/Object/ELFTypes.h:663]: `test/DebugInfo/symbolize-build-id.test` will fail without this check. I'm not sure if I should do the check here, but I think it's valid to add a check here.

File: llvm/lib/Object/BuildID.cpp (hunk 2 above)
Comment (cabbaken) [reply llvm/lib/Object/BuildID.cpp:37]: This piece of code follows the logic of Program Header below.
I checked and it works properly!
Should I do something to optimize it?

Comment (jh7370) [reply llvm/lib/Object/BuildID.cpp:37]: No, it's fine. I was just being lazy and not looking around to check :D

That being said, could we use a small lambda to avoid the repeated logic? I think you could use an `auto` input parameter for the section/program header and pass in the alignment as another parameter, so something like this:
```
auto findBuildID = [](const auto &ShdrOrPhdr, uint64_t Alignment) -> std::optional<BuildIDRef> {
  Error Err = Error::success();
  for (auto N : Obj.notes(ShdrOrPhdr, Err))
    if (N.getType() == ELF::NT_GNU_BUILD_ID &&
        N.getName() == ELF::ELF_NOTE_GNU)
      return N.getDesc(Alignment);
  consumeError(std::move(Err));
  return std::nullopt;
};
```
Other similar approaches may work just as well (e.g. there might be a better way than returning a `std::optional`, but hopefully this gives you the idea.

Comment (cabbaken) [reply llvm/lib/Object/BuildID.cpp]: I will follow that, thanks~

File: llvm/include/llvm/Object/ELFTypes.h (hunk 1 above)
Comment (MaskRay) [reply llvm/include/llvm/Object/ELFTypes.h:663]: Agreed. Should just fix the test.

File: llvm/lib/Object/BuildID.cpp [hunk 3]
```diff
@@ -24,20 +24,27 @@ using namespace llvm::object;
...
         continue;
-      Error Err = Error::success();
-      for (auto N : Obj.notes(S, Err))
-        if (N.getType() == ELF::NT_GNU_BUILD_ID &&
-            N.getName() == ELF::ELF_NOTE_GNU)
-          return N.getDesc(S.sh_addralign);
-      consumeError(std::move(Err));
+      auto ShdrRes = findBuildID(S, S.sh_addralign);
+      if (ShdrRes)
+        return ShdrRes.value();
```
Comment (jh7370) [inline llvm/lib/Object/BuildID.cpp:45]: This can be shortened to the suggestion.

Please also review the documentation on `auto` in the coding standards, as I think you're over-using it.
```suggestion
      if (std::optional<BuildIDRef> ShdrRes = findBuildID(S, S.sh_addralign))
        return ShdrRes.value();
```
(and the same style below for the Phdrs).

Comment (cabbaken) [reply llvm/lib/Object/BuildID.cpp:45]: Thanks for your suggestion, I will refer this code.
I'm sorry for over-using `auto`, I should read the code standard before I submit my code.
I'm really sorry about this.

File: llvm/lib/Object/BuildID.cpp [hunk 4]
```diff
@@ -24,6 +24,26 @@ using namespace llvm::object;
...
+    for (auto N : Obj.notes(ShdrOrPhdr, Err))
+      if (N.getType() == ELF::NT_GNU_BUILD_ID &&
+          N.getName() == ELF::ELF_NOTE_GNU)
+        return N.getDesc(Alignment);
+    consumeError(std::move(Err));
+    return std::nullopt;
+  };
+
+  auto Sections = cantFail(Obj.sections());
+  if (!Sections.empty()) {
```
Comment (jh7370) [inline llvm/lib/Object/BuildID.cpp:39]: This seems like an unnecessary check to me. If `Sections.empty()` is true, the `for` loop after it will never do anything.

**Review by jh7370 — COMMENTED** [review]
The code change now looks good to me, but I think you need a test case for the new behaviour. This test should fail without your code change and pass with it.

Also, does this fix the crash from the original input in the bug?

File: llvm/lib/Object/BuildID.cpp (hunk 4 above)
Comment (cabbaken) [reply llvm/lib/Object/BuildID.cpp:39]: Yes, I just followed `llvm/llvm/tools/llvm-readobj/ELFDumper.cpp:6155: processNotesHelper()` here.
I will remove this judge in the next commit.
BTW, should I make a PR to modify the similar logic in `llvm-readobj`?

**Comment by cabbaken** [comment]
> The code change now looks good to me, but I think you need a test case for the new behaviour. This test should fail without your code change and pass with it.

I will add the test file in the next commit, I'm working on it now.

> Also, does this fix the crash from the original input in the bug?

Yes, I tested that and it works properly!

File: llvm/include/llvm/Object/ELFTypes.h (hunk 1 above)
Comment (cabbaken) [reply llvm/include/llvm/Object/ELFTypes.h]: I add the `AddressAlign` property to the Section, and it can pass now.

File: llvm/lib/Object/BuildID.cpp (hunk 4 above)
Comment (jh7370) [reply llvm/lib/Object/BuildID.cpp]: If you want, you can do so.

Comment (cabbaken) [reply llvm/lib/Object/BuildID.cpp]: > If you want, you can do so.

Got it.

File: llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test [hunk 5]
```diff
@@ -15,3 +15,26 @@ FileHeader:
   Type:    ET_EXEC
   Machine: EM_X86_64
   EPhOff:  0xffffff
+
+
+# RUN: yaml2obj --docnum=2 %s -o %t.note.err
+# RUN: llvm-objdump -D %t.note.err 2>&1 | \
+# RUN:   FileCheck %s --check-prefix=PFILESIZE
+
+# PFILESIZE:          Disassembly of section .note.gnu.build-id:
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:24]: This check simply shows that disassembly of the section has been attempted. It doesn't show anything about any warnings or errors that have been produced. I'm not sure how useful it is.

File: llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test [hunk 6]
```diff
@@ -15,3 +15,26 @@ FileHeader:
...
+--- !ELF
+FileHeader:
+  Class:          ELFCLASS64
+  Data:           ELFDATA2LSB
+  Type:           ET_EXEC
+  Machine:        EM_X86_64
+Sections:
+  - Name:         .note.gnu.build-id
+    Type:         SHT_NOTE
+    Content:      040000000800000003000000474e5500abb50d82b6bdc861
```
Comment (jh7370) [inline llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:35]: yaml2obj provides a way to write note sections in a human-readable form. See llvm/test/tools/yaml2obj/ELF/note-section.yaml for an example. That would be a better way of writing the notes than a binary blob like this.

**Review by jh7370 — COMMENTED** [review]
Having sat and looked at the test and the original issue, I'm not certain whether a lit test is particularly useful. I could see a place for it, but I think more useful would be a gtest unit test that directly tests the `getBuildID` function instead.

As things stand, the lit test you've written will cover the original issue (though it needs some improvements, I've commented on them anyway), but as I understand it, there's no particular reason why `-D` should trigger the `getBuildID` function and it's just an implementation detail of how the object file is read internally.

As `BuildID.cpp` doesn't currently have a corresponding test file in `llvm/test/unittests/Object`, I'd add a `BuildIDTest.cpp` file to that project, with just some tests to show the behaviour of `getBuildID`. I don't think (in this PR) you necessarily need to test every code path in that function, but you do need to test the ones you've modified. There are examples of how to use YAML ELF inputs, like the one in the lit test you've written, in `ELFObjectFileTest.cpp`, so those are probably good starting points on how to write these tests. Essentially, the behaviours you need to cover, in my opinion, are:
1) That the BuildID can be looked up from a section header, if there is no program header.
2) That the code handles a malformed program header that points at data outside the file.
3) That the code handles a malformed section header that points at data outside the file.

File: llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test (hunk 5 above)
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:24]: So, how should I modify this test?
Or I just need to add BuildIDTest.cpp and delete this test?

File: llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test (hunk 6 above)
Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:35]: I will fix it if this test is necessary.

File: llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test (hunk 5 above)
Comment (jh7370) [reply llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:24]: I think it would probably just be better to delete the test and use the new unit test.

The YAML could still be useful in the unit test, so start with writing the unit test before deleting this file.

Comment (cabbaken) [reply llvm/test/tools/llvm-objdump/ELF/invalid-phdr.test:24]: Ok, I will add the unit test in next commit.

**Comment by cabbaken** [comment]
The latest commit adds the unit test and modifies the format of yaml.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+  - Type:         PT_NOTE
+    FileSize:     0xffffffffffffffff
+    Offset:       0x100
+)");
+  ASSERT_THAT_EXPECTED(ElfOrErr, Succeeded());
+  BuildIDRef BuildID = getBuildID(&ElfOrErr.get());
+  EXPECT_EQ(
+      StringRef(reinterpret_cast<const char *>(BuildID.data()), BuildID.size()),
+      "\xAB\xB5\x0D\x82\xB6\xBD\xC8\x61");
+}
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:61]: Nit: this icon means you're missing an end of line character at the end of the file. Please add it.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+    Type:         SHT_NOTE
+    AddressAlign: 0x04
+    Notes:
+      - Name:     "GNU"
+        Desc:     "abb50d82b6bdc861"
+        Type:     3
+ProgramHeaders:
+  - Type:         PT_NOTE
+    FileSize:     0xffffffffffffffff
+    Offset:       0x100
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:54]: Rather than use `Offset`, use the fields for setting first section/last section (to the .note.gnu.build-id section), so that the start of the program header is lined up with the actual data.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+                                              StringRef Yaml) {
+  raw_svector_ostream OS(Storage);
+  yaml::Input YIn(Yaml);
+  if (!yaml::convertYAML(YIn, OS, [](const Twine &Msg) {}))
+    return createStringError(std::errc::invalid_argument,
+                             "unable to convert YAML");
+  return ELFObjectFile<ELFT>::create(MemoryBufferRef(OS.str(), "dummyELF"));
+}
+
+TEST(BuildIDTest, InvalidNoteFileSizeTest) {
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:34]: This is good as a starting point. I think you also need at least the following test cases:
1) A test case where you have an invalid program header and no section headers to rely on. You can do this using the same YAML, except also including a `SectionHeaderTable` chunk that uses the `NoHeaders` field (see https://github.com/llvm/llvm-project/blob/c5f40bf024ee2d62478c8036fb174d75ecabe51f/llvm/test/tools/yaml2obj/ELF/section-headers.yaml#L108 for an example). (Rather than duplicating the input string, you could add a helper function to construct it with/without the `NoHeaders` value set to true, for example).
2) This may be a little trickier to achieve, but if possible, identify the max file size that would be considered "valid" and have cases with it specified and not specified (where section headers are missing) to show that the correct edge value is used.
3) A test case where the section header is present but invalid for reading the build-id, e.g. it has an invalid `sh_offset` value. You can use the `SHOffset` field in the YAML to specify a section header with an offset that is invalid, without affecting the actual location of the section data. Your program header in this case should point at the section correctly, to show that the data is read properly.

Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:34]: Ok, I will add these cases in the next commit.

Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:65]: > This is good as a starting point. I think you also need at least the following test cases:
> 
> 1. A test case where you have an invalid program header and no section headers to rely on. You can do this using the same YAML, except also including a `SectionHeaderTable` chunk that uses the `NoHeaders` field (see https://github.com/llvm/llvm-project/blob/c5f40bf024ee2d62478c8036fb174d75ecabe51f/llvm/test/tools/yaml2obj/ELF/section-headers.yaml#L108
>     for an example). (Rather than duplicating the input string, you could add a helper function to construct it with/without the `NoHeaders` value set to true, for example).

I’m not sure if this aligns with your idea, but I’ve implemented it in the latest commit. Let me know if I misunderstood anything.

> 2. This may be a little trickier to achieve, but if possible, identify the max file size that would be considered "valid" and have cases with it specified and not specified (where section headers are missing) to show that the correct edge value is used.

If I did not misunderstand, I should know the generated ELF file size before I generate it? I think the file size may change according to `yaml2obj`.
Please let me know if I misunderstood anything...

> 3. A test case where the section header is present but invalid for reading the build-id, e.g. it has an invalid `sh_offset` value. You can use the `SHOffset` field in the YAML to specify a section header with an offset that is invalid, without affecting the actual location of the section data. Your program header in this case should point at the section correctly, to show that the data is read properly.

I've implemented this in the latest commit. Please let me know if I misunderstood anything.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 10]
```diff
@@ -31,7 +30,61 @@ static Expected<ELFObjectFile<ELFT>> toBinary(SmallVectorImpl<char> &Storage,
   return ELFObjectFile<ELFT>::create(MemoryBufferRef(OS.str(), "dummyELF"));
 }
 
+static StringRef optionalSectionHeaderELF(bool WithSec) {
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:33]: LLVM naming guidelines say that functions should be verbs or verb phrases. I also think it would be clearer if you called it something like `getInvalidNoteELF` and change the parameter to `WithShdr`, since it's slightly more explicit about what the code is doing.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 11]
```diff
@@ -40,22 +93,23 @@ TEST(BuildIDTest, InvalidNoteFileSizeTest) {
...
   Machine:        EM_X86_64
+ProgramHeaders:
+  - Type:         PT_NOTE
+    FirstSec:     .note.gnu.build-id
+    LastSec:      .note.gnu.build-id
 Sections:
   - Name:         .note.gnu.build-id
     Type:         SHT_NOTE
     AddressAlign: 0x04
+    Offset:       0x8000
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:104]: There are two similarly-named fields in yaml2obj, but with different meanings:
1) `Offset`: this says "put the section at the specified offset in the file (which will increase the file size to fit)" and "set the sh_offset field of the section header to the specified value".
2) `SHOffset`: "put the section at the offset specified by `Offset` (if present) or at the next possible valid offset (if not present), but set the section header sh_offset field to the specified value.

Using `Offset` like you've done means there's no invalid section header, since the object file will just be increased to fit the section in at the specified location. Using `SHOffset` will place the section data in a valid place (and the program header will point to it), but the section header itself will be incorrect. Since the details of the section are read from the section header in the first place, tools will try to read the section at the invalid `SHOffset` value, which will be outside the file and generate an error, causing the code to fall back to reading via the program headers.

For an example, see https://github.com/llvm/llvm-project/blob/15c49b9db3f60bdbd320271d5e97f118c00b95dd/llvm/test/tools/yaml2obj/ELF/override-shoffset.yaml#L22.

File: llvm/unittests/Object/BuildIDTest.cpp (hunk 9 above)
Comment (jh7370) [reply llvm/unittests/Object/BuildIDTest.cpp:65]: > I’m not sure if this aligns with your idea, but I’ve implemented it in the latest commit. Let me know if I misunderstood anything.

Looks perfect (barring some naming nits), thanks!

On the note of naming, you should probably change the name of `InvalidNoteFileSizeTest` to clarify the specific case this case is testing.

> If I did not misunderstand, I should know the generated ELF file size before I generate it? I think the file size may change according to yaml2obj.
Please let me know if I misunderstood anything...

You didn't misunderstand anything, but I think it's still worth it. Firstly, it's rare that yaml2obj will change how an ELF is generated, as the tool is quite stable now and the rules on how to line out an object are fairly well defined. Secondly, it's worth it to make sure we don't have e.g. an incorrect `<` versus `<=` comparison or similar. By adding a test case that passes with it being exactly the right offset and another that fails when it is one off the right offset, we also can see if the edge moves in either direction. Let me know if you have any difficulties.

Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:65]: Thanks for your explanation~
I will implement this case in the next commit.

File: llvm/unittests/Object/BuildIDTest.cpp (hunk 11 above)
Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:104]: Got it, I was mix the notion of `ShOffset` and `Offset`.
Thanks for your explanation, that's very helpful.

File: llvm/unittests/Object/BuildIDTest.cpp (hunk 9 above)
Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:65]: Looks perfect (barring some naming nits), thanks!

On the note of naming, you should probably change the name of InvalidNoteFileSizeTest to clarify the specific case this case is testing.

Could you give me some advice on naming this test? My poor English makes it difficult for me to come up with a comprehensive name to describe this test...

File: llvm/unittests/Object/BuildIDTest.cpp (hunk 11 above)
Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp:104]: I tried with `ShOffset`, and according to the code in llvm-readobj, it seems like that it's common if the `getBuildID()` can't get the buildID with the Invalid ShOffset. Should I just modify the `EXPECT_EQ()` to make the test pass?

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+        Type:     3
+)");
+  static std::string WithoutSection(WithSection + R"(
+  - Type:         SectionHeaderTable
+    NoHeaders:    true
+)");
+  if (WithSec)
+    return WithSection;
+  else
+    return WithoutSection;
```
Comment (jh7370) [inline llvm/unittests/Object/BuildIDTest.cpp:62]: Nit: [Don't use else after return](https://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return)

**Review by jh7370 — COMMENTED** [review]
Did you delete a comment? I got an email notification about it, but can't see the comment anymore.

**Comment by cabbaken** [comment]
> Did you delete a comment? I got an email notification about it, but can't see the comment anymore.

Yes, I was misunderstanding something, but I figured that out after checking comment history.

**Comment by cabbaken** [comment]
And I do have 2 questions:
1. About the test case about `ShOffset`. How can I make a program header point to a section? I tried setting the same `Offset` and `Vaddr`/`Address`, and that doesn't work. And if there are some documents about `yaml2obj`, please tell me how to find them😢.
2. About this case
> 2. This may be a little trickier to achieve, but if possible, identify the max file size that would be considered "valid" and have cases with it specified and not specified (where section headers are missing) to show that the correct edge value is used.

I think there might be a problem here. The crash in the issue occurs due to an overflow in `llvm/include/llvm/Object/ELF.h:405` (`if (Phdr.p_offset + Phdr.p_filesz > getBufSize())`). In this case, `Phdr.p_filesz` is extremely large, causing `Phdr.p_offset + Phdr.p_filesz` to exceed the `uint32_t` limit. As a result, the condition `Phdr.p_offset + Phdr.p_filesz > getBufSize()` evaluates to `true`, leading to the crash.
There is nothing but the limit of `uint32_t` making the function   behave incorrectly. 
Actually, I'm sorry about did not try to set the FileSize to a big number(like `0xffffffffffffffff`), I don't know if it will make the generated ELF be such huge due to the lack of documents of `yaml2obj`.

**Comment by jh7370** [comment]
> And I do have 2 questions:
> 
>     1. About the test case about `ShOffset`. How can I make a program header point to a section? I tried setting the same `Offset` and `Vaddr`/`Address`, and that doesn't work. And if there are some documents about `yaml2obj`, please tell me how to find them😢.

The best documentation for yaml2obj is the yaml2obj testsuite, which shows all the different functionality. You can find it at llvm/test/tools/yaml2obj (see the ELF subdirectory for the ELF-format related tests). In this case, you should use [FirstSec/LastSec](https://github.com/llvm/llvm-project/blob/c7dbf20e66606e7e26a28ad567ff75f3a493d3bd/llvm/test/tools/yaml2obj/ELF/program-header.yaml#L30), to force the program header to cover the location of the real section data (those parameters can be the same section, if you only have one section for that program header, as is the case here).

> > 2. This may be a little trickier to achieve, but if possible, identify the max file size that would be considered "valid" and have cases with it specified and not specified (where section headers are missing) to show that the correct edge value is used.
> 
> I think there might be a problem here. The crash in the issue occurs due to an overflow in `llvm/include/llvm/Object/ELF.h:405` (`if (Phdr.p_offset + Phdr.p_filesz > getBufSize())`). In this case, `Phdr.p_filesz` is extremely large, causing `Phdr.p_offset + Phdr.p_filesz` to exceed the `uint32_t` limit. As a result, the condition `Phdr.p_offset + Phdr.p_filesz > getBufSize()` evaluates to `true`, leading to the crash. There is nothing but the limit of `uint32_t` making the function behave incorrectly. Actually, I'm sorry about did not try to set the FileSize to a big number(like `0xffffffffffffffff`), I don't know if it will make the generated ELF be such huge due to the lack of documents of `yaml2obj`.

Do you mean `uint64_t`, because there shouldn't be any explicit `uint32_t` types involved in the file size/offset (there might be for specific cases, but they'll be referred to via a different ELF-specific type).

Either way, I'm not asking for a huge object when I refer to the "largest valid size". The "valid" size I'm talking about is the size such that it points at the very last byte in a simple ELF object. One past the end is then invalid, because it points outside the file.

That being said, specifying a huge value is a separate case and also interesting as you've discovered, since it can provoke overflows and the code should detect and handle them. You just have to be careful with your calculations. For example, you might need a check like `Phdr.p_offset + Phdr.p_filesz < Phdr.p_offset`. If that is true, then the calculation has overflowed, which clearly means that it is an invalid size. There are various other ways of formulating this too (for example, you could use `std::numeric_limits<uint64_t>::max() - Phdr.p_filesz < Phdr.p_offset` or similar).

**Comment by cabbaken** [comment]
Got it! I’ll add the test in the next commit.

**Comment by cabbaken** [comment]
> > And I do have 2 questions:
> > ```
> > 1. About the test case about `ShOffset`. How can I make a program header point to a section? I tried setting the same `Offset` and `Vaddr`/`Address`, and that doesn't work. And if there are some documents about `yaml2obj`, please tell me how to find them😢.
> > ```
> 
> The best documentation for yaml2obj is the yaml2obj testsuite, which shows all the different functionality. You can find it at llvm/test/tools/yaml2obj (see the ELF subdirectory for the ELF-format related tests). In this case, you should use [FirstSec/LastSec](https://github.com/llvm/llvm-project/blob/c7dbf20e66606e7e26a28ad567ff75f3a493d3bd/llvm/test/tools/yaml2obj/ELF/program-header.yaml#L30), to force the program header to cover the location of the real section data (those parameters can be the same section, if you only have one section for that program header, as is the case here).

I tried this(actually, I tried this originally):
```
--- !ELF
FileHeader:
  Class:          ELFCLASS64
  Data:           ELFDATA2LSB
  Type:           ET_EXEC
  Machine:        EM_X86_64
ProgramHeaders:
  - Type:         PT_NOTE
    FirstSec:     .note.gnu.build-id
    LastSec:      .note.gnu.build-id
Sections:
  - Name:         .note.gnu.build-id
    Type:         SHT_NOTE
    AddressAlign: 0x04
    ShOffset:     0x8000
    Notes:
      - Name:     "GNU"
        Desc:     "abb50d82b6bdc861"
        Type:     3
```
and the generated ELF's Program Header has an Offset valued `0x8000`(the section data itself is in the file properly), which means it is not pointing to the real section data.

**Comment by jh7370** [comment]
> and the generated ELF's Program Header has an Offset valued `0x8000`(the section data itself is in the file properly), which means it is not pointing to the real section data.
> Did I just misunderstand something😢?

Nope, that YAML looks perfect. Unfortunately, it looks like there's a bug in yaml2obj: it decides the program header offset (and other properties) based on the final section header sh_offset, rather than the actual intended properties.

The fix should be fairly easy, if you're willing to tackle it (in a separate PR). Specifically, there are three points that are of interest. This line is the place where values are obtained from section headers that are later used in setting the program header values of the program header they are in. Note that it uses sh_offset, sh_size and sh_addralign, all of which, I believe can be overridden by dedicated fields in the YAML.
https://github.com/llvm/llvm-project/blob/36cd60144b15dd35c8e0081100421c3511242e02/llvm/lib/ObjectYAML/ELFEmitter.cpp#L1159

This line is the start of the bit of code where the section sh_* field values are calculated.
https://github.com/llvm/llvm-project/blob/main/llvm/lib/ObjectYAML/ELFEmitter.cpp#L796
Note how it initially calculates the "real" values, before finally calling `overrideFields` (there are a few places `overrideFields` is called, depending on the exact nature of the section).

Finally, `overrideFields` is defined at https://github.com/llvm/llvm-project/blob/5c375c3283fcd2bf4f98fe8627658e056e25dc44/llvm/lib/ObjectYAML/ELFEmitter.cpp#L634.

My feeling is that you could look at moving the calls to `overrideFields` to much later, so that it happens after the program headers have been laid out, perhaps right before the section header data is actually written.

**Comment by cabbaken** [comment]
I’ll fix yaml2obj first, then come back to this PR.
Wait for me~

**Comment by cabbaken** [comment]
> Either way, I'm not asking for a huge object when I refer to the "largest valid size". The "valid" size I'm talking about is the size such that it points at the very last byte in a simple ELF object. One past the end is then invalid, because it points outside the file.

There are already checks in [`ELF.h`](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Object/ELF.h#L405), is it still necessary to implement a test for that?

**Comment by jh7370** [comment]
> > Either way, I'm not asking for a huge object when I refer to the "largest valid size". The "valid" size I'm talking about is the size such that it points at the very last byte in a simple ELF object. One past the end is then invalid, because it points outside the file.
> 
> There are already checks in [`ELF.h`](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Object/ELF.h#L405), is it still necessary to implement a test for that?

You're touching on a whole can of worms there, as there are many different testing philosophies that suggest you should or shouldn't have cases that test lower-level function behaviours. For example, if you were to write your tests without knowing what code it uses under the hood, you would write a whole suite of tests that cover various edge cases that might actually end up testing the same cases as are tested elsewhere.

In this case though, I agree it probably makes sense to avoid additional tests for that specific case IF there are already existing tests that cover that behaviour.

**Review by jh7370 — COMMENTED** [review]
Could you do a merge commit from main into your branch, to see if it fixes the issues that the pre-merge tests were highlighting before, please? (Once you've fixed the yaml2obj issue anyway)

**Comment by cabbaken** [comment]
> Could you do a merge commit from main into your branch, to see if it fixes the issues that the pre-merge tests were highlighting before, please? (Once you've fixed the yaml2obj issue anyway)

That’s exactly what I planned to do.

> You're touching on a whole can of worms there, as there are many different testing philosophies that suggest you should or shouldn't have cases that test lower-level function behaviours. For example, if you were to write your tests without knowing what code it uses under the hood, you would write a whole suite of tests that cover various edge cases that might actually end up testing the same cases as are tested elsewhere.
> 
> In this case though, I agree it probably makes sense to avoid additional tests for that specific case IF there are already existing tests that cover that behaviour.

Got it!
So my only task now is to fix yaml2obj and verify that this PR passes the checks, right?

**Comment by cabbaken** [comment]
Theoretically, this should pass the check after the merge of [130942](https://github.com/llvm/llvm-project/pull/130942).
How to restart a check? Should I just click the "__Update branch__" button?

**Comment by jh7370** [comment]
> > That and check that there is boundary condition testing already.
> 
> It's passed the check now~

Did you check to see if there was any boundary condition testing for this case?

**Comment by cabbaken** [comment]
> Did you check to see if there was any boundary condition testing for this case?

I've added a unit test to ensure the function checks both the program header and the section header to retrieve the build ID.

To clarify, are you suggesting that I should also add an additional build ID check to the test file at `llvm/test/DebugInfo/symbolize-build-id.test`?

**Comment by cabbaken** [comment]
Thanks for the reminder about why an invalid program header causes llvm-objdump to crash.

What would be the best approach for the test? Should I add a new test case to llvm/test/tools/llvm-objdump/ELF/program-headers.test, or is it better to modify an existing one?

**Comment by jh7370** [comment]
> What would be the best approach for the test? Should I add a new test case to llvm/test/tools/llvm-objdump/ELF/program-headers.test, or is it better to modify an existing one?

I literally just said don't add a new lit test. You have an existing set of unit tests that you're adding in this patch. You could either add duplicates of them, or probably better, change them to test the edge values, instead of `FileSize: 0xffffffffffffffff` and `ShOffset: 0x8000` (I don't not know what exactly those values should be, but they should be the value at which point it goes from a "valid" value to an "invalid" value).

**Comment by cabbaken** [comment]
After reading the unit test I wrote, I noticed something curious. In [`ELF.h`](https://github.com/cabbaken/llvm-project/blob/126418/llvm/include/llvm/Object/ELF.h#L410):
 ```c++
  Elf_Note_Iterator notes_begin(const Elf_Phdr &Phdr, Error &Err) const {
    assert(Phdr.p_type == ELF::PT_NOTE && "Phdr is not of type PT_NOTE");
    ErrorAsOutParameter ErrAsOutParam(Err);
    if (Phdr.p_offset + Phdr.p_filesz > getBufSize()) {
      Err =
          createError("invalid offset (0x" + Twine::utohexstr(Phdr.p_offset) +
                      ") or size (0x" + Twine::utohexstr(Phdr.p_filesz) + ")");
      return Elf_Note_Iterator(Err);
    }
```
The `p_filesz` in the unit test is set to `0x0xffffffffffffffff`. This cause `Phdr.p_offset + Phdr.p_filesz` to overflow, so `return Elf_Note_Iterator(Err);` is skipped. The unit test then "succeed" based on the overflow, but it may cause an invalid memory access if the elf has no buildID. For example:
```yaml
--- !ELF
FileHeader:
  Class:          ELFCLASS64
  Data:           ELFDATA2LSB
  Type:           ET_EXEC
  Machine:        EM_X86_64
ProgramHeaders:
  - Type:         PT_NOTE
    FileSize:     0xffffffffffffffff
    FirstSec:     .note.gnu.build-id
    LastSec:      .note.gnu.build-id
Sections:
  - Name:         .note.gnu.build-id
    Type:         SHT_NOBITS
    AddressAlign: 0x04
```

Given this, I think we should avoid iterating over `notes` if the ELF has an invalid `p_filesz`, so that we don’t run into boundary issues here. The large `p_filesz` value in the test is only meant to demonstrate that we detect the section header before the program header.

I'm sorry I was misunderstanding about this:
>That the BuildID can be looked up from a section header, if there is no program header.
That the code handles a malformed program header that points at data outside the file.
That the code handles a malformed section header that points at data outside the file.

File: llvm/include/llvm/Object/ELF.h [hunk 13]
```diff
@@ -407,7 +407,8 @@ class ELFFile {
   Elf_Note_Iterator notes_begin(const Elf_Phdr &Phdr, Error &Err) const {
     assert(Phdr.p_type == ELF::PT_NOTE && "Phdr is not of type PT_NOTE");
     ErrorAsOutParameter ErrAsOutParam(Err);
-    if (Phdr.p_offset + Phdr.p_filesz > getBufSize()) {
+    if (Phdr.p_offset + Phdr.p_filesz > getBufSize() ||
+        Phdr.p_offset + Phdr.p_filesz < Phdr.p_offset) {
```
[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/include/llvm/Object/ELF.h]: Yes, and I see you've put a PR up for it.

File: llvm/unittests/Object/BuildIDTest.cpp [hunk 14]
```diff
@@ -40,7 +40,7 @@ static StringRef getInvalidNoteELF(bool WithShdr) {
   Machine:        EM_X86_64
 ProgramHeaders:
   - Type:         PT_NOTE
-    FileSize:     0xffffffffffffffff
+    FileSize:     0xffffffffffffff88
```
[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp]: > Oh, I should add that the current case is a good way of testing the overflow boundary case in the other PR.

Yes, the boundary value is intended for the overflow check.
In this PR, I’ll remove the unrelated parts so it focuses on its main subject.

[the remark this answers is not in the document]
Comment (cabbaken) [reply llvm/unittests/Object/BuildIDTest.cpp]: Now that I add the boundary check in another PR, should I remove the boundary value here?

[the remark this answers is not in the document]
Comment (jh7370) [reply llvm/unittests/Object/BuildIDTest.cpp]: Please refer back to [this comment](https://github.com/llvm/llvm-project/pull/126537#discussion_r2374798980) above. I think that should mostly answer your question. It's enough to only check one of the paths there _in this PR,_ because what you're after is test the behaviour when an error is encountered in the underlying code.

**Review by jh7370 — COMMENTED** [review]
Looks good to me, once the other PR has been merged. Please update this PR once it has, and I'll give it one final look over.

**Review by jh7370 — APPROVED** [review]
LGTM, thanks! Let me know once you want me to merge this for you.
