### PR TITLE
[analyzer] Model builtin-like functions as builtin functions

### LINKED ISSUE #94193: [clang-tidy] `std::addressof` not checked by `clang-analyzer-core.StackAddressEscape`
The code examples are all in C++23 (`-std=c++23`) and libc++ (`-stdlib=libc++ -fexperimental-library`).

---

Given a basic example:

```cpp
#include <iostream>
#include <memory>
#include <string>

auto f1()
{
    std::string a = "123";
    return std::addressof(a);
}

int main()
{
    auto result = f1();
    std::cout << *result;
}
```

It isn't caught by `clang-tidy`, and instead ASan catches it in runtime:

```
==270312==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f5177600020 at pc 0x557cec62fff6 bp 0x7ffcf239dcb0 sp 0x7ffcf239dca8
```

This is weird, given the fact that `__builtin_addressof` is checked by `clang-tidy` and (at least in `libc++`) `std::addressof` is simply a wrapper that calls `__builtin_addressof`.

Definition of `std::addressof`:

```cpp
template <class _Tp>
inline _LIBCPP_CONSTEXPR_SINCE_CXX17 _LIBCPP_NO_CFI _LIBCPP_HIDE_FROM_ABI _Tp* addressof(_Tp& __x) _NOEXCEPT {
  return __builtin_addressof(__x);
}
```

When changing the example to use `__builtin_addressof`:

```cpp
auto f1()
{
    std::string a = "123";
    return __builtin_addressof(a);
}
```

`clang-tidy` is able to figure out that it's returning a dangling pointer:

```
main.cpp:38: error: Address of stack memory associated with local variable 'a' returned to caller [clang-analyzer-core.StackAddressEscape,-warnings-as-errors]
```

---

This issue might be what caused `std::reference_wrapper` and `std::ranges::ref_view` to be unchecked, since (in libc++) they also used `std::addressof` in their constructors.

Example of faulty code utilizing `std::ranges::ref_view`:

```cpp
#include <iostream>
#include <ranges>
#include <vector>

auto f2()
{
    std::vector a{1, 2, 3};
    return a | std::ranges::views::filter([](auto &&_) { return _ > 1; });
}

int main()
{
    auto result = f2();
    for (auto &&e : result) {
        std::cout << e;
    }
}
```

`clang-tidy` doesn't catch it. ASan catches it (`stack-use-after-return`).

Example of faulty code utilizing `std::reference_wrapper`:
```cpp
#include <iostream>
#include <functional>
#include <string>

auto f3()
{
    std::string a = "123";
    return std::ref(a);
}

int main()
{
    auto result = f3();
    std::cout << result.get();
}
```

`clang-tidy` doesn't catch it. ASan catches it (`stack-use-after-return`).

---

More interestingly, if you implement your own reference wrapper that works similar to the one in libc++ by storing address, `clang-tidy` can detect the returning of dangling pointer/reference as long as `std::addressof` isn't used in constructor.

Definition of `Ref`:

```cpp
template<typename T>
struct Ref
{
    Ref(T &ref)
        : ptr(&ref)
    {}
    auto &get(this auto &&self) { return *self.ptr; }
private:
    T *ptr;
};
```

Faulty code utilizing `Ref`:

```cpp
#include <iostream>
#include <string>

auto f4()
{
    std::string a = "123";
    return Ref{a};
}

int main()
{
    auto result = f4();
    std::cout << result.get();
}
```

`clang-tidy` catches it:

```
main.cpp:28: error: Address of stack memory associated with local variable 'a' is still referred to by the stack variable 'result' upon returning to the caller.  This will be a dangling reference [clang-analyzer-core.StackAddressEscape,-warnings-as-errors]
```

But, when you change the constructor of `Ref` to use `std::addressof(ref)`, `clang-tidy` can no longer detect it, which leads to me thinking the case with `std::reference_wrapper` and `std::ranges::ref_view`.

---

Version:

```
> clang-tidy-18 --version
Debian LLVM version 18.1.6
  Optimized build.
```

```
> clang++-18 --version
Debian clang version 18.1.6 (++20240518023138+1118c2e05e67-1~exp1~20240518143226.133)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### PR DESCRIPTION
**Pull request by steakhal**
Some template function instantiations don't have a body, even though their templates did have a body.
Examples are: `std::move`, `std::forward`, `std::addressof` etc.

They had bodies before
https://github.com/llvm/llvm-project/commit/72315d02c432a0fe0acae9c96c69eac8d8e1a9f6

After that change, the sentiment was that these special functions should be considered and treated as builtin functions.

Fixes #94193

CPP-5358

### CODE REVIEW

**Review by Xazax-hun — APPROVED** [review]
LGTM, thanks!

File: clang/test/Analysis/use-after-move.cpp [hunk 1]
```diff
@@ -570,13 +570,8 @@ void differentBranchesTest(int i) {
   {
     A a;
     a.foo() > 0 ? a.foo() : A(std::move(a)).foo();
-#ifdef DFS
-    // peaceful-note@-2 {{Assuming the condition is false}}
-    // peaceful-note@-3 {{'?' condition is false}}
-#else
-    // peaceful-note@-5 {{Assuming the condition is true}}
-    // peaceful-note@-6 {{'?' condition is true}}
-#endif
```
Comment (NagyDonat) [inline clang/test/Analysis/use-after-move.cpp:579]: What is the intent behind this change? Is it just opportunistic cleanup, or is there a connection to the core goals of the commit?

File: clang/test/Analysis/diagnostics/explicit-suppression.cpp [hunk 2]
```diff
@@ -19,6 +19,6 @@ class C {
 void testCopyNull(C *I, C *E) {
   std::copy(I, E, (C *)0);
 #ifndef SUPPRESSED
-  // expected-warning@../Inputs/system-header-simulator-cxx.h:757 {{Called C++ object pointer is null}}
+  // expected-warning@#system_header_simulator_cxx_std_copy_impl_loop {{Called C++ object pointer is null}}
```
Comment (NagyDonat) [inline clang/test/Analysis/diagnostics/explicit-suppression.cpp:22]: It's good to know that the test system provides this feature :smile:

**Review by NagyDonat — COMMENTED** [review]
LGTM.

File: clang/test/Analysis/use-after-move.cpp (hunk 1 above)
Comment (steakhal) [reply clang/test/Analysis/use-after-move.cpp:579]: To be fair, I didn't really investigate. But I believe that probably the graph looks different, and it always picks the "true" path. So, this is a necessary change, but I didn't find this as a regression.

Comment (NagyDonat) [reply clang/test/Analysis/use-after-move.cpp:579]: I see, thanks for the explanation. I agree that this isn't an important question and simply adjusting the TC is the right solution.
