### PR TITLE
[clang][dataflow] Check for backedges directly (instead of loop statements).

### LINKED ISSUE #67834: Built-in analysis fails to converge on simple loops
A number of (likely-related) simple loops cause the analysis to fail to converge. Below are a series of examples reduced from real code. I suspect they are all the same problem:

```
TEST(PointerNullabilityTest, NonConvergeBools1) {
  EXPECT_TRUE(checkDiagnostics(R"cc(
    bool cond();
    void target() {
      bool a = false;
      bool b = cond();
      while (!a || !b) {
        if (!cond()) return;
        if (cond()) {
          if (a) return;
          a = cond();
        } else {
          if (b) return;
          b = true;
        }
      }
    }
  )cc"));
}

TEST(PointerNullabilityTest, NonConvergeBools2) {
  EXPECT_TRUE(checkDiagnostics(R"cc(
    bool cond();
    void target() {
      bool c = false;
      while (cond() || cond()) {
        c = (3 == 4);
      }
    }
  )cc"));
}

TEST(PointerNullabilityTest, NonConvergeBools3) {
  EXPECT_TRUE(checkDiagnostics(R"cc(
    bool cond();
    void target() {
      if (cond())
        ;
      while (cond() || cond())
        ;
    }
  )cc"));
}

TEST(PointerNullabilityTest, NonConvergeBools4) {
  EXPECT_TRUE(checkDiagnostics(R"cc(
    bool cond();

    void target(int m, int n, bool b) {
      bool g = m == 0 ;
      while (cond() || cond() || g) {
        bool c = m == 0 ;
        g = false;
      }
    }
  )cc"));
}
```

### PR DESCRIPTION
**Pull request by ymand**
Widen on backedge nodes, instead of nodes with a loop statement as terminator.
This fixes #67834 and a precision loss from assignment in a loop condition. The
commit contains tests for both of these issues.

### CODE REVIEW

**Review by Xazax-hun — APPROVED** [review]
Nice fix! So, it looks like our definition of "loop head" was wrong.

**Comment by ymand** [comment]
> Nice fix! So, it looks like our definition of "loop head" was wrong.

Indeed. We didn't think of the way control-flow constructs *inside* the condition expression would be represented. Ironically (?), this is actually simpler and fixes another issue besides, which is nice. ;)

File: clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp [hunk 1]
```diff
@@ -502,14 +490,15 @@ runTypeErasedDataflowAnalysis(
...
+  PostOrderCFGView POV(&CFG);
+  ForwardDataflowWorklist Worklist(CFG, &POV);
 
   std::vector<std::optional<TypeErasedDataflowAnalysisState>> BlockStates(
-      CFCtx.getCFG().size());
+      CFG.size());
 
   // The entry basic block doesn't contain statements so it can be skipped.
-  const CFGBlock &Entry = CFCtx.getCFG().getEntry();
+  const CFGBlock &Entry = CFG.getEntry();
```
Comment (martinboehme) [inline clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp:501]: Nit: This refactoring is entirely independent of the rest of this PR. Suggest submitting changes like this as a separate "NFC" PR to minimize the size of PRs and ease review.

File: clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp [hunk 2]
```diff
@@ -53,19 +52,8 @@ static int blockIndexInPredecessor(const CFGBlock &Pred,
...
-      case Stmt::DoStmtClass:
-      case Stmt::ForStmtClass:
-      case Stmt::CXXForRangeStmtClass:
-        return true;
-      default:
-        return false;
-    }
-
-  return false;
+static bool isBackedgeNode(const CFGBlock &B) {
```
Comment (martinboehme) [inline clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp:55]: Can you add a short comment explaining what a "backedge node" is?

(I think the term "backedge node" isn't otherwise defined in Clang or the framework -- or if it is, it would be useful to add a link.)

File: clang/unittests/Analysis/FlowSensitive/TransferTest.cpp [hunk 3]
```diff
@@ -4099,6 +4099,20 @@ TEST(TransferTest, LoopDereferencingChangingRecordPointerConverges) {
   ASSERT_THAT_ERROR(checkDataflowWithNoopAnalysis(Code), llvm::Succeeded());
 }
 
+TEST(TransferTest, LoopWithDisjunctiveConditionConverges) {
```
Comment (martinboehme) [inline clang/unittests/Analysis/FlowSensitive/TransferTest.cpp:4102]: Test naming: I think the key aspect is not that the condition is a disjunction but that it's a short-circuited binary operator -- so maybe `LoopWithShortCircuitedConditionConverges`?

File: clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp [hunk 4]
```diff
@@ -913,6 +913,34 @@ TEST_F(FlowConditionTest, WhileStmt) {
...
+    }
+  )";
+  runDataflow(
+      Code,
+      [](const llvm::StringMap<DataflowAnalysisState<NoopLattice>> &Results,
+         ASTContext &ASTCtx) {
+        const ValueDecl *FooDecl = findValueDecl(ASTCtx, "Foo");
+        ASSERT_THAT(FooDecl, NotNull());
+
+        ASSERT_THAT(Results.keys(), UnorderedElementsAre("p"));
```
Comment (martinboehme) [inline clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp:936]: Suggest deleting this assertion. `getEnvironmentAtAnnotation()` already asserts that an annotation "p" exists.

(I know we assert this in a lot of existing tests, but it just seems like clutter.)

File: clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp [hunk 5]
```diff
@@ -913,6 +913,34 @@ TEST_F(FlowConditionTest, WhileStmt) {
...
+        const Environment &Env = getEnvironmentAtAnnotation(Results, "p");
+
+        auto &FooVal = cast<BoolValue>(Env.getValue(*FooDecl))->formula();
```
Comment (martinboehme) [inline clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp:939]:
```suggestion
        const Environment &Env = getEnvironmentAtAnnotation(Results, "p");
        auto &FooVal = getValueForDecl<BoolValue>(ASTCtx, Env, "Foo");
```

You may need to include "TestingSupport.h".

File: clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp [hunk 6]
```diff
@@ -913,6 +913,34 @@ TEST_F(FlowConditionTest, WhileStmt) {
...
+        /*[[p]]*/
+      }
+    }
+  )";
+  runDataflow(
+      Code,
+      [](const llvm::StringMap<DataflowAnalysisState<NoopLattice>> &Results,
+         ASTContext &ASTCtx) {
+        const ValueDecl *FooDecl = findValueDecl(ASTCtx, "Foo");
+        ASSERT_THAT(FooDecl, NotNull());
```
Comment (martinboehme) [inline clang/unittests/Analysis/FlowSensitive/TypeErasedDataflowAnalysisTest.cpp:934]: This assertion is unnecessary -- findValueDecl() already asserts internally that its return value is non-null. (But see also suggested edit below.)

**Review by martinboehme — APPROVED** [review]
LGTM with comments

File: clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp (hunk 1 above)
Comment (ymand) [reply clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp:501]: it was originally part of this patch, but I ended up undoing some of the new changes. I considered separating this out, but I think for such small NFC changes you run the real risk that you simply won't follow up. That is, it's a great idea, but if we try to make this the norm, I think the result will be many lost small cleanup opportunities. Maybe that's worth it, for review clarity. I don't really know where to draw the line.

File: clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp (hunk 2 above)
Comment (ymand) [reply clang/lib/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.cpp:61]: https://github.com/llvm/llvm-project/blob/eb14f47bf1ccfda500ba3c3092d70e269f6f0b56/clang/include/clang/Analysis/CFG.h#L805

Fwiw, I think this comment is better than the one in the CFG, so I don't know that linking is worth much, especially since it can be found pretty easily just by looking at `getLoopTarget`.
