### PR TITLE
[clang][Analyzer] Fix error path of builtin overflow

### LINKED ISSUE #136292: analyzer: Thinks result of `__builtin_mul_overflow` can be uninitialized
```c++
#include <stddef.h>

int test(size_t nel, size_t elsz) {
  size_t nbytes;
  int overflow = __builtin_mul_overflow(nel, elsz, &nbytes);
  int overflow2 = __builtin_add_overflow(nel, nbytes, &nbytes);
  return overflow * overflow2;
}
```

```
> clang++ --analyze -Xclang -analyzer-output=text -std=c++20
clang++: warning: argument unused during compilation: '-S' [-Wunused-command-line-argument]
<source>:6:19: warning: 2nd function call argument is an uninitialized value [core.CallAndMessage]
    6 |   int overflow2 = __builtin_add_overflow(nel, nbytes, &nbytes);
      |                   ^                           ~~~~~~
<source>:4:3: note: 'nbytes' declared without an initial value
    4 |   size_t nbytes;
      |   ^~~~~~~~~~~~~
<source>:5:18: note: Assuming overflow
    5 |   int overflow = __builtin_mul_overflow(nel, elsz, &nbytes);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:6:19: note: 2nd function call argument is an uninitialized value
    6 |   int overflow2 = __builtin_add_overflow(nel, nbytes, &nbytes);
      |                   ^                           ~~~~~~
1 warning generated.
Compiler returned: 0
```

Godbolt: https://godbolt.org/z/4q4Efcax8

### PR DESCRIPTION
**Pull request by pskrgag**
According to https://clang.llvm.org/docs/LanguageExtensions.html#checked-arithmetic-builtins, result of builtin_*_overflow functions will be initialized even in case of overflow. Align analyzer logic to docs and always initialize 3rd argument of such builtins. 

Closes #136292

### CODE REVIEW

File: clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp [hunk 1]
```diff
@@ -121,30 +120,24 @@ class BuiltinFunctionChecker : public Checker<eval::Call> {
...
     if (!BR.isInteresting(Result))
       return;
 
-    // Propagate interestingness to input argumets if result is interesting.
+    // Propagate interestingness to input arguments if result is interesting.
     BR.markInteresting(Arg1);
     BR.markInteresting(Arg2);
 
-    if (BothFeasible)
+    if (overflow)
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp:134]: You could have used a ternary expr here and save a couple of lines.

File: clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp [hunk 2]
```diff
@@ -194,30 +187,28 @@ void BuiltinFunctionChecker::handleOverflowBuiltin(const CallEvent &Call,
   SVal RetVal = SVB.evalBinOp(State, Op, Arg1, Arg2, ResultType);
 
   auto [Overflow, NotOverflow] = checkOverflow(C, RetValMax, ResultType);
-  if (NotOverflow) {
-    ProgramStateRef StateNoOverflow = State->BindExpr(
-        CE, C.getLocationContext(), SVB.makeTruthVal(false, BoolTy));
+  auto initializeState = [&](bool isOverflow) {
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp:190]: Llvm style uses UpperCamelCase local variables.

File: clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp [hunk 3]
```diff
@@ -194,30 +187,28 @@ void BuiltinFunctionChecker::handleOverflowBuiltin(const CallEvent &Call,
...
+                                                 Arg1, Arg2, RetVal));
+  };
 
-  if (Overflow) {
-    C.addTransition(State->BindExpr(CE, C.getLocationContext(),
-                                    SVB.makeTruthVal(true, BoolTy)),
-                    createBuiltinOverflowNoteTag(C));
-  }
+  if (NotOverflow)
+    initializeState(false);
```
Comment (steakhal) [inline clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp:208]: I don't likr that this call has a side-effect. I eish we would be explicit about mutations. Pass whats needed, get the return value that it would produce.

**Review by steakhal — CHANGES_REQUESTED** [review]
The tests and functionality looks correct to me.
I noticed you promptly fixed the linked issue. You shouldn't need to feel pressured for a fix right away.
I appreciate your swiftness and enthausiesm.

File: clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp (hunk 3 above)
Comment (pskrgag) [reply clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp]: Factored out lambda to separate function that returns new state.

File: clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp (hunk 1 above)
Comment (pskrgag) [reply clang/lib/StaticAnalyzer/Checkers/BuiltinFunctionChecker.cpp:139]: Redone code a bit, I guess, ternary now won't look better

**Comment by pskrgag** [comment]
> I noticed you promptly fixed the linked issue. You shouldn't need to feel pressured for a fix right away.

I just feel bad when introduce bugs and want to fix them asap. Thanks for review!

**Review by steakhal — APPROVED** [review]
Thanks!
