### PR TITLE
[Coverage] Fix region termination for GNU statement expressions

### LINKED ISSUE #124296: [coverage] __noreturn__ attribute leads to incorrect coverage report
The `__noreturn__` attribute appears to invalidate coverage of the following line, whereas `_Noreturn` demonstrates correct behavior.

```c
// coverage.c
#include <stdio.h>

__attribute__ ((__noreturn__)) void foo(void) { while (1); }
_Noreturn void bar(void) { while (1); }

int main(int argc, char **argv) {
    int rc = ({ if (argc > 3) foo(); 0; });
    printf("coverage after foo is missing\n");

    int rc2 = ({ if (argc > 3) bar(); 0; });
    printf("coverage after bar is present\n");
    return rc + rc2;
}
```

```bash
# build.sh
/usr/bin/clang --version | /bin/grep "clang version"
/usr/bin/clang -fprofile-instr-generate -fcoverage-mapping coverage.c -o coverage
./coverage
/usr/bin/llvm-profdata merge -sparse default.profraw -o default.profdata
/usr/bin/llvm-cov show ./coverage -instr-profile=default.profdata
```

Running the script:

```
$ ./build.sh
clang version 19.1.1 (Red Hat, Inc. 19.1.1-5.el10)
coverage after foo is missing
coverage after bar is present
    1|       |#include <stdio.h>
    2|       |
    3|      0|__attribute__ ((__noreturn__)) void foo(void) { while (1); }
    4|      0|_Noreturn void bar(void) { while (1); }
    5|       |
    6|      1|int main(int argc, char **argv) {
    7|      1|    int rc = ({ if (argc > 3) foo(); 0; });
    8|      0|    printf("coverage after foo is missing\n");
    9|       |
   10|      1|    int rc2 = ({ if (argc > 3) bar(); 0; });
   11|      1|    printf("coverage after bar is present\n");
   12|      1|    return rc + rc2;
   13|      1|}

$
```

- Line 8 is reported as uncovered, though it prints as expected. (incorrect behavior)
- Line 11 is reported as covered, and prints as expected. (correct behavior)

This seems like a bug connected to `__noreturn__`. FWIW I also tested this in C++ and observed the same results.

### PR DESCRIPTION
**Pull request by justincady**
Calls to __noreturn__ functions result in region termination for
coverage mapping. But this creates incorrect coverage results when
__noreturn__ functions (or other constructs that result in region
termination) occur within [GNU statement expressions][1].

In this scenario an extra gap region is introduced within VisitStmt,
such that if the following line does not introduce a new region it
is unconditionally counted as uncovered.

This change adjusts the mapping such that terminate statements
within statement expressions do not propagate that termination
state after the statement expression is processed.

[1]: https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

Fixes #124296

### CODE REVIEW

File: clang/test/CoverageMapping/terminate-statements.cpp [hunk 1]
```diff
@@ -346,6 +346,12 @@ int elsecondnoret(void) {
   return 0;
 }
 
+// CHECK-LABEL: _Z18statementexprnoretb
+int statementexprnoret(bool crash) {
+  int rc = ({ if (crash) abort(); 0; }); // CHECK-NOT: Gap,File 0, [[@LINE]]:41 -> [[@LINE+1]]:3 = 0
```
Comment (MaskRay) [inline clang/test/CoverageMapping/terminate-statements.cpp:351]: CHECK-NOT with a long pattern can easily become stale without being noticed. E.g., the columns 41 and 3 are pretty fragile.

You can use `CHECK(match a previous thing), CHECK-NEXT(match the next thing)` to state that there is no line in between, or add some newlines within the GNU statement expression..

**Review by MaskRay — APPROVED** [review]

**Comment by justincady** [comment]
Apologies, I mistakenly pulled commits into this PR when trying to rebase and address @MaskRay's comment. I'll clean this up.

File: clang/test/CoverageMapping/terminate-statements.cpp (hunk 1 above)
Comment (justincady) [reply clang/test/CoverageMapping/terminate-statements.cpp]: Thanks, I pushed a commit to fix this.

**Comment by justincady** [comment]
@MaskRay If you're satisfied with the current diff, could you please commit this whenever you get the chance? Thank you.
