### PR TITLE
[coro][CoroSplit] Use `llvm.lifetime.end` to compute putting objects on the frame vs the stack

### LINKED ISSUE #86580: [coroutines] LLVM incorrectly allocates variables on the coroutine stack
Example:

```cpp
struct StubbyMessageBuffer {
  StubbyMessageBuffer();
  ~StubbyMessageBuffer();
};

// Reduced version of absl::cleanup
class Cleanup  {
 public:
  Cleanup(void (*cleanup)()) : cleanup_(cleanup){}

  ~Cleanup() {
    cleanup_();
  }

 private:
  // Strangely enough this doesn't work if cleanup_ is a std::function
  void (*cleanup_)();
};

MyTask FooBar() {
  StubbyMessageBuffer smb;
  #ifdef DO_CLEANUP
  // This is produced by a LOG(FATAL) or a LOG(QFATAL)
  Cleanup cu([]{abort();});
  #endif
  co_await 1;
  co_return;
}
```

When compiled with `-O1` and `DO_CLEANUP` undefined, `smb` is constructed and stored in the coroutine frame:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %ref.tmp3.reload.addr = getelementptr inbounds i8, ptr %0, i64 24
  %smb.reload.addr = getelementptr inbounds i8, ptr %0, i64 18
```

However, if `DO_CLEANUP` *is* defined, `smb` is no longer stored on the frame; instead, it is constructed and allocated in the coroutine resume function:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %smb = alloca %struct.StubbyMessageBuffer, align 1
```

This behavior is wrong; the constructor for `StubbyMessageBuffer` may have side effects, and if `FooBar()` calls a function that takes a reference / pointer to `smb`, `smb` still does not get created on the coroutine frame object, and we get a segfault.

godbolt: https://godbolt.org/z/oMfKqExMK

### PR DESCRIPTION
**Pull request by alanzhao1**
The current logic for using lifetime intrinsics to determine whether a
coroutine alloca should live on the coroutine frame or stack doesn't
consider `llvm.lifetime.end`. As a result, some allocas are incorrectly
placed on the stack even though their lifetimes may outlive the stack.
For example, SimplifyCFG may generate code that drops the corresponding
`llvm.lifetime.end` of an `llvm.lifetime.start`, and that code is
incorrectly handled by the existing logic.

To fix this, new logic is introduced where if an alloca's address is
escaped, and there is a path from an `llvm.lifetime.start` to a
coroutine suspend point (e.g. `llvm.coro.suspend`) without an
`llvm.lifetime.end`, then we know the object lives beyond the suspension
point and therefore must go on the coroutine frame.

Fixes https://github.com/llvm/llvm-project/issues/86580

### CODE REVIEW

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp [hunk 1]
```diff
@@ -2830,9 +2855,9 @@ static void collectFrameAlloca(AllocaInst *AI, coro::Shape &Shape,
   bool ShouldUseLifetimeStartInfo =
       (Shape.ABI != coro::ABI::Async && Shape.ABI != coro::ABI::Retcon &&
        Shape.ABI != coro::ABI::RetconOnce);
-  AllocaUseVisitor Visitor{AI->getModule()->getDataLayout(), DT,
-                           *Shape.CoroBegin, Checker,
-                           ShouldUseLifetimeStartInfo};
+  AllocaUseVisitor Visitor{
+      AI->getModule()->getDataLayout(), DT,   *Shape.CoroBegin, Checker,
+      ShouldUseLifetimeStartInfo,       Shape};
```
Comment (ChuanqiXu9) [inline llvm/lib/Transforms/Coroutines/CoroFrame.cpp:2860]: nit: then we don't need `Shape.CoroBegin`

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp [hunk 2]
```diff
@@ -1614,6 +1621,24 @@ struct AllocaUseVisitor : PtrUseVisitor<AllocaUseVisitor> {
       // suspend point between lifetime markers. This should also cover the
       // case of a single lifetime.start intrinsic in a loop with suspend point.
       if (PI.isEscaped()) {
+        // If there is no explicit lifetime.end, then assume the address can
```
Comment (ChuanqiXu9) [inline llvm/lib/Transforms/Coroutines/CoroFrame.cpp:1624]: Due to github review system, I can only put the comments here for the above code. According to our discussion, we can only check the whether the lifetime.{start, end} cross suspend point. We don't need to check users. Then it can be cheaper.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp [hunk 3]
```diff
@@ -1614,6 +1621,24 @@ struct AllocaUseVisitor : PtrUseVisitor<AllocaUseVisitor> {
...
+          return true;
+
+        // If there is a path from a lifetime.start to a suspend without a
+        // corresponding lifetime.end, then the alloca's lifetime persists
+        // beyond that suspension point and the alloca must go on the frame.
+        for (AnyCoroSuspendInst *SuspendInst : CoroShape.CoroSuspends) {
+          SmallVector<BasicBlock *> LifetimeStartsBB;
+          for (IntrinsicInst *II : LifetimeStarts)
+            LifetimeStartsBB.push_back(II->getParent());
+          if (isPotentiallyReachableFromMany(LifetimeStartsBB,
```
Comment (ChuanqiXu9) [inline llvm/lib/Transforms/Coroutines/CoroFrame.cpp:1636]: This looks more expensive since it didn't cache any thing. It would be better if we can reuse the checker above.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp (hunk 2 above)
Comment (alanzhao1) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp:1624]: This algorithm as described would not work.

The problem is that checking for `lifetime.start` -> `coro.suspend` -> `lifetime.end` doesn't cover the case where `lifetime.end` is missing, which is the original bug.

Even if we modify the algorithm to check for `lifetime.end`, `unreachable`, and `return`, we would still need to make sure there is no `lifetime.end` between the `lifetime.start` and `coro.suspend` (since that would mean the object can live on the stack). The simpler algorithm therefore is to just check for `lifetime.start` -> (no `lifetime.end`) -> `coro.suspend`.

Comment (alanzhao1) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: I think I misunderstood your initial comment - my apologies.

If I understand correctly, you're saying that the following code before the line `if (PI.isEscaped()) {`:

```cpp
for (auto *I : Users)
  for (auto *S : LifetimeStarts)
    if (Checker.isDefinitionAcrossSuspend(*S, I))
      return true;
```

is not necessary because we're checking for all `Users` instead of just `llvm.lifetime.end`, so therefore, we can replace those lines of code with the `lifetime.end` logic I wrote below.

I made this change and `ninja check-llvm` passed locally, so LMK if this is what you meant.

Comment (ChuanqiXu9) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: Yes, we don't need check users if we check `lifetime.end`.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp (hunk 3 above)
Comment (ChuanqiXu9) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: >  "Is there a path from BasicBlock A to BasicBlock B without going through BasicBlocks { C, D, E, ...}. The current logic caches whether a path may go through a suspend point - it doesn't answer the reverse question

I don't understand this. The reverse form of it should be: there is not a path may go through a suspend point. Then it looks the same with the previous one.

Comment (alanzhao1) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: The problem is that we have to detect whether there are other `llvm.coro.end`s between `llvm.lifetime.start` and `llvm.lifetime.end` - see for example:

[Block A: `lifetime.start`] -> [Block B: `lifetime.end`] -> [Block C: `coro.suspend`] -> [Block D: `lifetime.end`].

In this case, if we were analyzing A -> D, then we would see that there is a path from A's `lifetime.start` to D's `lifetime.start`, suggesting that we need to put the object on the frame. However, this analysis is incorrect because B ends the lifetime before `coro.suspend`. A correct analysis would need some way to filter out all intermediate `lifetime.end` blocks

This is even more problematic for the case in the original bug where `lifetime.end` was missing. Therefore, we would need to check paths from `lifetime.start` to `return` and `unreachable`. So for example:

[Block A: `lifetime.start`] -> [Block B: `lifetime.end`] -> [Block C: `coro.suspend`] -> [Block D: `unreachable`].

we would run into the same problem because we see that `lifetime.start` -> `unreachable` requires a pass through `coro.suspend`, suggesting that we need to put the object on the frame when we actually don't due to the `lifetime.end`.

Comment (ChuanqiXu9) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: Got it. Then in another perspective, if `Checker` checks whether there is a path from block A to blockB touching suspending blocks, can we create a similar checker (or refactor the existing one) to check if there is a path from blockA (the block of the a lifeitme.start) to blockB (any suspending blocks) touching ending blocks (the blocks containing corresponding lifetime.end)? Then if there is such a path, we need to put the alloca to the frame. Otherwise we can put it on the stack. It looks like it can solve the two problems you raised.

Comment (ChuanqiXu9) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: Got it.  I think it will be better to extend `isPotentiallyReachableFromMany` to `isManyPotentiallyReachableFromMany`. e.g., we don't need to iterate the suspending block. The implementation of `isPotentiallyReachableFromMany` looks not complex and should be doable. We can add it in CoroFrame locally or contribute that to CFG.h. 

For cache, yeah, it looks like we can't have an easy one : (

**Comment by alanzhao1** [comment]
not sure why buildkite is failing - I didn't see any test failures and `ninja check-llvm` passed locally for me on Linux.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp (hunk 3 above)
Comment (alanzhao1) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: This should be done - PTAL

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp [hunk 4]
```diff
@@ -1550,13 +1556,16 @@ struct AllocaUseVisitor : PtrUseVisitor<AllocaUseVisitor> {
   }
 
   void visitIntrinsicInst(IntrinsicInst &II) {
+    if (II.getIntrinsicID() == Intrinsic::lifetime_end)
```
Comment (zmodem) [inline llvm/lib/Transforms/Coroutines/CoroFrame.cpp:1559]: Should this also take into account if the lifetime marker only applies to a subrange of the alloca (like below)?

File: llvm/include/llvm/Analysis/CFG.h [hunk 5]
```diff
@@ -96,6 +96,22 @@ bool isPotentiallyReachableFromMany(
...
+///
+/// Determine whether there is a path from at least one block in Worklist to
+/// at least one block in StopSet within a single function without passing
+/// through any of the blocks in 'ExclusionSet'. Returns false only if we can
+/// prove that once any block 'Worklist' has been reached then no blocks in
+/// 'StopSet' can be executed.
+/// Conservatively returns true.
+bool isManyPotentiallyReachableFromMany(
+    SmallVectorImpl<BasicBlock *> &Worklist,
+    const SmallPtrSetImpl<const BasicBlock *> &StopSet,
```
[the remark this answers is not in the document]
Comment (alanzhao1) [reply llvm/include/llvm/Analysis/CFG.h:105]: The `StopBB` parameter in `isPotentiallyReachableFromMany(...)` has type `const BasicBlock *`, so `StopSet` needs to be a set of `const BasicBlock *`s in order for us to implement `isPotentiallyReachableFromMany(...)` with `isManyPotentiallyReachableFromMany(...)`.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp (hunk 4 above)
Comment (alanzhao1) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: Done (but there's no logic change anyways since we don't check `LifetimeEndBBs` if there are no `LifetimeStarts`).

File: llvm/include/llvm/Analysis/CFG.h [hunk 6]
```diff
@@ -85,17 +85,27 @@ bool isPotentiallyReachable(
 /// Determine whether there is at least one path from a block in
 /// 'Worklist' to 'StopBB' without passing through any blocks in
 /// 'ExclusionSet', returning true if uncertain.
-///
-/// Determine whether there is a path from at least one block in Worklist to
-/// StopBB within a single function without passing through any of the blocks
-/// in 'ExclusionSet'. Returns false only if we can prove that once any block
-/// in 'Worklist' has been reached then 'StopBB' can not be executed.
-/// Conservatively returns true.
```
Comment (ChuanqiXu9) [inline llvm/include/llvm/Analysis/CFG.h:93]: Do we need to remove this really? I feel better to make it self contained.

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM with nits. Thanks.

File: llvm/lib/Transforms/Coroutines/CoroFrame.cpp (hunk 4 above)
Comment (zmodem) [reply llvm/lib/Transforms/Coroutines/CoroFrame.cpp]: There could be a "full" `lifetime.start` followed by a "partial" `lifetime.end`, so I think this matters. But the latest version of the PR handles that nicely.

**Review by zmodem — APPROVED** [review]
lgtm

File: llvm/include/llvm/Analysis/CFG.h (hunk 6 above)
Comment (alanzhao1) [reply llvm/include/llvm/Analysis/CFG.h:93]: Restored.

File: llvm/include/llvm/Analysis/CFG.h [hunk 7]
```diff
@@ -96,6 +96,22 @@ bool isPotentiallyReachableFromMany(
     const SmallPtrSetImpl<BasicBlock *> *ExclusionSet,
     const DominatorTree *DT = nullptr, const LoopInfo *LI = nullptr);
 
+/// Determine whether there is at least one path from a block in
+/// 'Worklist' to a block in 'StopSet' without passing through any
+///  blocks in 'ExclusionSet', returning true if uncertain.
```
[the remark this answers is not in the document]
Comment (alanzhao1) [reply llvm/include/llvm/Analysis/CFG.h]: Fixed.

**Comment by nikic** [comment]
Reverted in https://github.com/llvm/llvm-project/commit/924384161ffceda08099536dd07a953299a69b53 due to compile-time regressions, see https://llvm-compile-time-tracker.com/compare.php?from=94204f59e92473bb19333f40a2250b64a398191a&to=fcf341d3ddfe2289ac88aa3c122b25df8732cc8e&stat=instructions:u. Presumably your changes to the isPotentiallyReachable infrastructure have made it much slower than it was.
