### PR TITLE
Reland [Coverage] Fix region termination for GNU statement expressions

### LINKED ISSUE #124296: [coverage] __noreturn__ attribute leads to incorrect coverage report
The `__noreturn__` attribute appears to invalidate coverage of the following line, whereas `_Noreturn` demonstrates correct behavior.

```c
// coverage.c
#include <stdio.h>

__attribute__ ((__noreturn__)) void foo(void) { while (1); }
_Noreturn void bar(void) { while (1); }

int main(int argc, char **argv) {
    int rc = ({ if (argc > 3) foo(); 0; });
    printf("coverage after foo is missing\n");

    int rc2 = ({ if (argc > 3) bar(); 0; });
    printf("coverage after bar is present\n");
    return rc + rc2;
}
```

```bash
# build.sh
/usr/bin/clang --version | /bin/grep "clang version"
/usr/bin/clang -fprofile-instr-generate -fcoverage-mapping coverage.c -o coverage
./coverage
/usr/bin/llvm-profdata merge -sparse default.profraw -o default.profdata
/usr/bin/llvm-cov show ./coverage -instr-profile=default.profdata
```

Running the script:

```
$ ./build.sh
clang version 19.1.1 (Red Hat, Inc. 19.1.1-5.el10)
coverage after foo is missing
coverage after bar is present
    1|       |#include <stdio.h>
    2|       |
    3|      0|__attribute__ ((__noreturn__)) void foo(void) { while (1); }
    4|      0|_Noreturn void bar(void) { while (1); }
    5|       |
    6|      1|int main(int argc, char **argv) {
    7|      1|    int rc = ({ if (argc > 3) foo(); 0; });
    8|      0|    printf("coverage after foo is missing\n");
    9|       |
   10|      1|    int rc2 = ({ if (argc > 3) bar(); 0; });
   11|      1|    printf("coverage after bar is present\n");
   12|      1|    return rc + rc2;
   13|      1|}

$
```

- Line 8 is reported as uncovered, though it prints as expected. (incorrect behavior)
- Line 11 is reported as covered, and prints as expected. (correct behavior)

This seems like a bug connected to `__noreturn__`. FWIW I also tested this in C++ and observed the same results.

### PR DESCRIPTION
**Pull request by justincady**
Relands #130976 with adjustments to test requirements.

Calls to __noreturn__ functions result in region termination for
coverage mapping. But this creates incorrect coverage results when
__noreturn__ functions (or other constructs that result in region
termination) occur within [GNU statement expressions][1].

In this scenario an extra gap region is introduced within VisitStmt,
such that if the following line does not introduce a new region it
is unconditionally counted as uncovered.

This change adjusts the mapping such that terminate statements
within statement expressions do not propagate that termination
state after the statement expression is processed.

[1]: https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

Fixes #124296

### CODE REVIEW

**Comment by justincady** [comment]
This is the buildbot failure from the initial commit: https://lab.llvm.org/buildbot/#/builders/133/builds/13131

I updated the failing test with the same restrictions as other tests using `-fuse-ld=lld` under `compiler-rt/test/profile/Linux`, specifically:

```
// REQUIRES: lld-available
// XFAIL: powerpc64-target-arch
```

File: clang/test/CoverageMapping/terminate-statements.cpp [hunk 1]
```diff
@@ -346,6 +346,12 @@ int elsecondnoret(void) {
   return 0;
 }
 
+// CHECK-LABEL: _Z18statementexprnoretb
```
Comment (MaskRay) [inline clang/test/CoverageMapping/terminate-statements.cpp:349]: `_Z18statementexprnoretb:`

**Review by MaskRay — APPROVED** [review]
