### PR TITLE
[NVPTX] Fix internal indirect call prototypes not obeying the ABI

### LINKED ISSUE #100055: [NVPTX] Incorrect alignment in call prototype for 'sprintf' function
The NVPTX backend currently emits the incorrect alignment when trying to compile the `sprintf` function with LTO. It will emit errors like the following:
```
ptxas a.s, line 1509; error   : Alignment of argument does not match formal parameter '_'
```
Looking at  the IR in https://godbolt.org/z/n9nK6ddxb I noticed that many of these `_` function calls come from the main implementation. If this function is internalized, then these calls get an incorrect alignment of `16` as in the following:
```
prototype_82 : .callprototype (.param .b32 _) _ (.param .align 16 .b8 _[16], .param .b64 _);
```
If I make the indirect call instead have an alignment of `8`, then it works just fine, i.e. This also happens if I manually remove the `internal` keyword from the function and  thus make it `.visible`.
```
prototype_82 : .callprototype (.param .b32 _) _ (.param .align 8 .b8 _[16], .param .b64 _);
```

Any clue why this would cause issues? Since this is an indirect call it's not like there's a set prototype we need to adhere to. And I don't see why making the function `.visible` or not makes the alignment correct.

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
The NVPTX backend optimizes the ABI for functions that are internal,
however, this is not legal for indirect call prototypes. Previously, we
would modify the ABI on an aggregate byval type passed to an indirect
call prototype, which would make PTXAS error. This patch just passes the
function as a nullptr to force strict ABI compliance without
modification in the helper function.

Fixes https://github.com/llvm/llvm-project/issues/100055

### CODE REVIEW

**Comment by jhuber6** [comment]
The `libc` changes undo a hack I had to do to make the tests pass. I put them in this patch so they can be backported.

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp [hunk 1]
```diff
@@ -1471,10 +1470,11 @@ std::string NVPTXTargetLowering::getPrototype(
       continue;
     }
 
+    // Indirect calls need strict ABI alignment so we disable optimizations.
     Type *ETy = Args[i].IndirectType;
     Align InitialAlign = Outs[OIdx].Flags.getNonZeroByValAlign();
     Align ParamByValAlign =
-        getFunctionByValParamAlign(F, ETy, InitialAlign, DL);
+        getFunctionByValParamAlign(/*F=*/nullptr, ETy, InitialAlign, DL);
```
Comment (Artem-B) [inline llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:1477]: The comment above needs to mantion that it's the `nullptr` here that forces strict ABI-compliant alignment. Otherwise it's not clear which part of the code controls this.

Ideally, it would be even nicer to make "ABI-compliant alignment" a parameter.

**Review by Artem-B — APPROVED** [review]
LGTM in principle, with a nit.

File: llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp (hunk 1 above)
Comment (arsenm) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:1477]: This doesn't really make sense to me as a fix. Indirect calls shouldn't require special handling vs. direct

Comment (jhuber6) [reply llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:1477]: The NVPTX backend thinks that `internal` functions can have their ABI modified, so they up-scale alignment on things. This doesn't work for these indirect calls, which seem to strictly require the ABI.
