### PR TITLE
[flang][OpenMP][Lower] lower array subscripts for task depend

### LINKED ISSUE #132647: [Flang][OpenMP] Compilation error of combining select type construct and task construct with depend clause
```
Version of flang : 21.0.0(3e6f618e86f5fbad2c2d5802416ec3d3366a2837)/AArch64
```

Combining `select type construct` and `task construct` with `depend clause` results in a compilation error.  
Compilation ends normally in the following cases:
- Do not specify the compilation option (`-fopenmp`)
- Remove `depend clause`

The following are the test program, Flang, Gfortran and ifx compilation/execution result.

sngg362t_2.f90:
```fortran
program main
  type ty
     character(len=5)::i(3)
  end type ty

  type,extends(ty)::tt
     integer(kind=2),allocatable::n(:)
  end type tt
  class(ty),allocatable::obj

  allocate(tt::obj)
  obj%i = "AAAAA"

  select type (obj)
  type is (tt)
     allocate(obj%n(4))
     obj%n = 10
     associate(p2=>obj%n(1:4:2))
!$omp task depend(in:p2)
       obj%n(1:4:2) = 11
!$omp end task
       print *,'pass'
     endassociate
  class default
     print*,"912"
  end select
end program main
```

```
$ flang -fopenmp sngg362t_2.f90
flang-20: warning: OpenMP support in flang is still experimental [-Wexperimental-option]
error: loc("/work/home/ohno/CT/test/fort/tp/reproducerJ/FFE_2022_PH19703_08/sngg362t_2.f90":19:7): 'omp.task' op operand #0 must be variadic of OpenMP-compatible variable type, but got '!fir.box<!fir.array<2xi16>>'
error: verification of lowering to FIR failed
$
```

```
$ export OMP_NUM_THREADS=2; flang sngg362t_2.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp sngg362t_2.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=2; ifx -qopenmp sngg362t_2.f90; ./a.out
 pass
$
```

### PR DESCRIPTION
**Pull request by tblah**
The OpenMP standard says that all dependencies in the same set of inter-dependent tasks must be non-overlapping. This simplification means that the OpenMP only needs to keep track of the base addresses of dependency variables. This can be seen in kmp_taskdeps.cpp, which stores task dependency information in a hash table, using the base address as a key.

This patch generates a rebox operation to slice boxed arrays, but only the box data address is used for the task dependency. The extra box is optimized away by LLVM at O3.

Vector subscripts are TODO (I will address in my next patch).

This also fixes a bug for ordinary subscripts when the symbol was mapped to a box:

Fixes #132647

### CODE REVIEW

File: flang/lib/Lower/OpenMP/ClauseProcessor.cpp [hunk 1]
```diff
@@ -830,18 +845,38 @@ bool ClauseProcessor::processDepend(mlir::omp::DependClauseOps &result) const {
...
-      semantics::Symbol *sym = object.sym();
-      const mlir::Value variable = converter.getSymbolAddress(*sym);
-      result.dependVars.push_back(variable);
+      // The openmp dialect doesn't know what to do with boxes (and it would
+      // break layering to teach it about them). The dependency variable can be
+      // a box because it was an array section or because the original symbol
+      // was mapped to a box.
+      // Getting the address of the box data is okay because all the runtime
+      // ultimately cares about is the base address of the array.
+      if (fir::isa_box_type(dependVar.getType())) {
```
[the remark this answers is not in the document]
Comment (tblah) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:874]: The standard says that using an unallocated allocatable is undefined behavior. So I don't think this needs any special handling here.

[the remark this answers is not in the document]
Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:874]: Are you saying it is OK to use the address of the descriptor and not the real address of the array for this case?

[the remark this answers is not in the document]
Comment (tblah) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:874]: No that would not be okay. As I understand it, this will use the address of the data pointed to by the descriptor.

[the remark this answers is not in the document]
Comment (kiranchandramohan) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:874]: You will probably need to unwrap the ref or `dyn_cast_ptrEleTy` otherwise I think this code will only work for the box type (assumed shape?) and not ` fir.ref<fir.box`.

[the remark this answers is not in the document]
Comment (tblah) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:874]: Ohh I see what you mean now. Thanks

**Review by kiranchandramohan — APPROVED** [review]
LGTM. Please wait a day in case the other folks working in this area has comments.

Is there shared code with target dependencies? Would we need tests there?

Just as a side point. An alternative way to express dependencies is to use tokens like in async dialect.

File: flang/lib/Lower/OpenMP/ClauseProcessor.cpp [hunk 2]
```diff
@@ -830,18 +846,46 @@ bool ClauseProcessor::processDepend(mlir::omp::DependClauseOps &result) const {
...
+      } else {
+        semantics::Symbol *sym = object.sym();
+        dependVar = converter.getSymbolAddress(*sym);
       }
 
-      semantics::Symbol *sym = object.sym();
-      const mlir::Value variable = converter.getSymbolAddress(*sym);
-      result.dependVars.push_back(variable);
+      // If we pass a mutable box e.g. !fir.ref<!fir.box<!fir.heap<...>>> then
+      // the runtime will use the addres of the box not the address of the data.
```
Comment (NimishMishra) [inline flang/lib/Lower/OpenMP/ClauseProcessor.cpp:870]: Nit: "addres" -> "address"

File: flang/lib/Lower/OpenMP/ClauseProcessor.cpp [hunk 3]
```diff
@@ -808,7 +809,21 @@ bool ClauseProcessor::processCopyprivate(
   return hasCopyPrivate;
 }
 
-bool ClauseProcessor::processDepend(mlir::omp::DependClauseOps &result) const {
+template <typename T>
+static bool isVectorSubscript(const evaluate::Expr<T> &expr) {
+  if (std::optional<evaluate::DataRef> dataRef{evaluate::ExtractDataRef(expr)})
+    if (const auto *arrayRef = std::get_if<evaluate::ArrayRef>(&dataRef->u))
+      for (const evaluate::Subscript &subscript : arrayRef->subscript())
+        if (std::holds_alternative<evaluate::IndirectSubscriptIntegerExpr>(
```
Comment (NimishMishra) [inline flang/lib/Lower/OpenMP/ClauseProcessor.cpp:817]: I am assuming we are skipping `Triplet` from the `Subscript` because it by default holds `ScalarIntExpr`. Is this understanding right?

**Review by NimishMishra — COMMENTED** [review]
Thanks for the fix.

File: flang/lib/Lower/OpenMP/ClauseProcessor.cpp (hunk 3 above)
Comment (tblah) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:817]: Some examples might make this clearer

- `array(1:3)` here the triplet is `(1:3)` and `array` is the thing being subscripted. This doesn't need special handling as a vector subscript because we don't need to index a second array to know what indices are being selected in which order - we know the answer statically so a simple `hlfir.designate` is sufficient
- `array(indices)` (where indices is an array) requires special handling as a vector subscript because `indices` has to be read in order to know which elements of `array` have been selected. The access to the indices is indirect.
- `array(indices(1:4:2))`. Here the triplet `(1:4:2)` has to be first applied to `indices` to select `indices(1)` and `indices(3)`. Then those two elements have to be read to find the right elements to access in `array`. This is also a vector subscript because of the indirection through `indices`.

The same logic (mixed into other things) in the hlfir lowering code that handles this: see how `sawVectorSubscripts` is handled in `HlfirDesignatorBuilder::visit(const Fortran::evaluate::ArrayRef &, PartInfo &)` in `convertExprToHlfir.cpp`.

File: flang/lib/Lower/OpenMP/OpenMP.cpp [hunk 4]
```diff
@@ -2428,7 +2430,8 @@ genTaskOp(lower::AbstractConverter &converter, lower::SymMap &symTable,
           ConstructQueue::const_iterator item) {
   lower::StatementContext stmtCtx;
```
Comment (tblah) [inline flang/lib/Lower/OpenMP/OpenMP.cpp:2431]: While working on the next patch in this series I've noticed that this `stmtCtx` seems not to be scoped correctly. If any cleanup code is added to it, it will emit that cleanup code when it is destroyed. Unfortunately, when this goes out of scope at the end of `genTaskOp` the builder insertion point is inside of the task operation. It would make more sense to do the cleanup after the end of the task operation to avoid adding unnecessary shared variables (this might be only a theoretical bug because I haven't yet found an example where any cleanup code is still present by the time we reach FIR.)

File: flang/lib/Lower/OpenMP/ClauseProcessor.cpp (hunk 3 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/ClauseProcessor.cpp:817]: Sorry I was on leave.

Yes, this explains a lot. Thanks!

File: flang/lib/Lower/OpenMP/OpenMP.cpp (hunk 4 above)
Comment (NimishMishra) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:2431]: I am trying to understand the problem here. This `stmtCtx` is used in managing and cleaning up intermediates while generating expressions of certain clauses. At the time the cleanup code is emitted, the insertion point is inside the task's region. Is it after the operations in task's region are generated, or before that?

Comment (tblah) [reply flang/lib/Lower/OpenMP/OpenMP.cpp:2431]: Let's discuss this on the PR for this change. Hopefully the example will make it clearer: https://github.com/llvm/llvm-project/pull/133891#issuecomment-2768860434
