### PR TITLE
[DSE] Remove malloc from EarliestEscapeInfo before removing.

### LINKED ISSUE #84051: [DSE] crash
Reduced test case:
[tc_dse.tar.gz](https://github.com/llvm/llvm-project/files/14499403/tc_dse.tar.gz)

opt -mtriple=s390x-unknown-linux -mcpu=z16 -O3 -S ./tc_dse.ll

#6 0x0000000005287456 llvm::BasicAAResult::aliasCheck
#11 0x00000000048f0646 (anonymous namespace)::DSEState::isReadClobber
14 0x00000000049004d8 llvm::DSEPass::run
Segmentation fault (core dumped)

This is reported by user on F37 with clang-15, and is still failing on trunk.

@fhahn @BK1603 @nikic

### PR DESCRIPTION
**Pull request by fhahn**
Not removing the malloc from earliest escape info leaves stale entries in the cache.

Fixes https://github.com/llvm/llvm-project/issues/84051.

### CODE REVIEW

File: llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp [hunk 1]
```diff
@@ -1916,6 +1916,7 @@ struct DSEState {
     Updater.insertDef(NewAccessMD, /*RenameUses=*/true);
     Updater.removeMemoryAccess(Malloc);
     Malloc->replaceAllUsesWith(Calloc);
+    EI.removeInstruction(Malloc);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp:1919]: Should this use deleteDeadInstruction() instead? This can probably run into the same BatchAA invalidation issue, right?

Comment (fhahn) [reply llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp]: yeah that's better, updated, thanks!

File: llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp [hunk 2]
```diff
@@ -1908,15 +1908,9 @@ struct DSEState {
                               Malloc->getArgOperand(0), IRB, TLI);
     if (!Calloc)
       return false;
-    MemorySSAUpdater Updater(&MSSA);
-    auto *NewAccess =
-      Updater.createMemoryAccessAfter(cast<Instruction>(Calloc), nullptr,
-                                      MallocDef);
-    auto *NewAccessMD = cast<MemoryDef>(NewAccess);
-    Updater.insertDef(NewAccessMD, /*RenameUses=*/true);
```
Comment (nikic) [inline llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp:1916]: Don't we have to keep the part of this that creates the new access?

Comment (fhahn) [reply llvm/lib/Transforms/Scalar/DeadStoreElimination.cpp:1916]: Ah yes added back. Strangely this doesn't seem to be caught be the verifier in any of the tests we have.

**Review by nikic — APPROVED** [review]
LGTM
