### PR TITLE
[LVI][ValueTracking] Take UB-implying attributes into account in `isSafeToSpeculativelyExecute`

### LINKED ISSUE #137582: [CVP] Miscompilation at -O3
Reproducer: https://alive2.llvm.org/ce/z/x4KrLX
```

----------------------------------------
define i8 @func_124(i16 %.promoted) {
entry:
  %inc20.i = or i16 %.promoted, 1
  %conv.i.i = trunc i16 %inc20.i to i8
  %narrow.i.i.i = smin i8 %conv.i.i, 0
  assume_welldefined i8 %narrow.i.i.i
  %tobool.not.i46 = icmp eq i16 %.promoted, 0
  br i1 %tobool.not.i46, label %func_127.exit, label %land.rhs.i47

land.rhs.i47:
  br label %func_127.exit

func_127.exit:
  %conv5.i.i.pn.in = phi i8 [ %narrow.i.i.i, %entry ], [ 0, %land.rhs.i47 ]
  ret i8 %conv5.i.i.pn.in
}
=>
define i8 @func_124(i16 %.promoted) {
entry:
  %inc20.i = or i16 %.promoted, 1
  %conv.i.i = trunc nsw nuw i16 %inc20.i to i8
  %narrow.i.i.i = smin i8 %conv.i.i, 0
  assume_welldefined i8 %narrow.i.i.i
  %tobool.not.i46 = icmp eq i16 %.promoted, 0
  br i1 %tobool.not.i46, label %func_127.exit, label %land.rhs.i47

land.rhs.i47:
  br label %func_127.exit

func_127.exit:
  %conv5.i.i.pn.in = phi i8 [ %narrow.i.i.i, %entry ], [ 0, %land.rhs.i47 ]
  %#range_0_%conv5.i.i.pn.in = !range i8 %conv5.i.i.pn.in, i8 128, i8 1
  ret i8 %#range_0_%conv5.i.i.pn.in
}
Transformation doesn't verify!

ERROR: Source is more defined than target

Example:
i16 %.promoted = #x0080 (128)

Source:
i16 %inc20.i = #x0081 (129)
i8 %conv.i.i = #x81 (129, -127)
i8 %narrow.i.i.i = #x81 (129, -127)
i1 %tobool.not.i46 = #x0 (0)
  >> Jump to %land.rhs.i47
  >> Jump to %func_127.exit
i8 %conv5.i.i.pn.in = #x00 (0)

Target:
i16 %inc20.i = #x0081 (129)
i8 %conv.i.i = poison
i8 %narrow.i.i.i = poison
void = UB triggered!


Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Closes https://github.com/llvm/llvm-project/issues/137582.

In the original case, LVI uses the edge information in `%entry -> %if.end` to get a more precise result. However, since the call to `smin` has an `noundef` return attribute, an immediate UB will be triggered after optimization.

Currently, `isSafeToSpeculativelyExecuteWithOpcode(%min)` returns true because https://github.com/llvm/llvm-project/commit/6a288c1e32351d4be3b7630841af078fa1c3bb8b only checks whether the function is speculatable. However, it is not enough in this case.

This patch takes UB-implying attributes into account if `IgnoreUBImplyingAttrs` is set to false. If it is set to true, the caller is responsible for correctly propagating UB-implying attributes.

### CODE REVIEW

File: llvm/lib/Analysis/ValueTracking.cpp [hunk 1]
```diff
@@ -7287,7 +7286,20 @@ bool llvm::isSafeToSpeculativelyExecuteWithOpcode(
...
     // if marked readnone nounwind.
-    return Callee && Callee->isSpeculatable();
+    if (!Callee || !Callee->isSpeculatable())
+      return false;
+    // Since the operands may be changed after hoisting, undefined behavior may
+    // be triggered by some UB-implying attributes.
+    if (!AllowRefinement) {
+      if (CI->hasRetAttr(Attribute::NoUndef) ||
+          CI->getRetDereferenceableBytes() > 0 ||
+          CI->getRetDereferenceableOrNullBytes() > 0 ||
```
Comment (nikic) [inline llvm/lib/Analysis/ValueTracking.cpp:7296]: I think we should have a has() query for dropUBImplyingAttrsAndMetadata similar to how we have hasPoisonGeneratingAnnotations and dropPoisonGeneratingAnnotations, so we can keep these things in sync.

File: llvm/include/llvm/Analysis/ValueTracking.h [hunk 2]
```diff
@@ -539,31 +539,43 @@ bool isNotCrossLaneOperation(const Instruction *I);
 /// move the instruction as long as the correct dominance relationships for
 /// the operands and users hold.
 ///
+/// If \p UseVariableInfo is true, the information from non-constant operands
+/// will be taken into account.
+///
+/// If \p AllowRefinement is true, UB-implying attributes and metadata will be
+/// ignored. The caller is responsible for correctly propagating them after
+/// hoisting.
```
Comment (nikic) [inline llvm/include/llvm/Analysis/ValueTracking.h:547]: I don't think AllowRefinement is really the right flag name for this. E.g. refinement to poison is fine.

I'd give this a more explicit name like IgnoreUBImplifyAttrs.

**Review by nikic — COMMENTED** [review]
Do we also have to worry about this in other places that use isSafeToSpeculativelyExecuteWithVariableReplaced?

E.g. in replaceInInstruction -- though that one should drop the flags instead of bailing out.

It looks like the call in InstCombineCalls is ok because FoldOpIntoSelect already uses dropUBImplyingAttrsAndMetadata. (Which only handles return attributes, but that's a separate issue.)

File: llvm/lib/IR/Instruction.cpp [hunk 3]
```diff
@@ -554,6 +554,20 @@ void Instruction::dropUBImplyingAttrsAndMetadata() {
...
+  if (!CB)
+    return false;
+  // For call instructions, we also need to check parameter and return
+  // attributes that are can cause UB.
+  for (unsigned ArgNo = 0; ArgNo < CB->arg_size(); ArgNo++)
+    if (CB->isPassingUndefUB(ArgNo))
+      return true;
+  return CB->hasRetAttr(Attribute::NoUndef) ||
+         CB->getRetDereferenceableBytes() > 0 ||
+         CB->getRetDereferenceableOrNullBytes() > 0;
```
Comment (nikic) [inline llvm/lib/IR/Instruction.cpp:568]: Using hasRetAttr(Attribute::Dereferenceable) is more efficient (avoids looking up the actual attribute).

Though it would be nicer to base these checks on getUBImplyingAttributes() instead.

File: llvm/lib/IR/Instruction.cpp [hunk 4]
```diff
@@ -554,6 +554,20 @@ void Instruction::dropUBImplyingAttrsAndMetadata() {
   dropUBImplyingAttrsAndUnknownMetadata(KnownIDs);
 }
 
+bool Instruction::hasUBImplyingAttrs() const {
+  auto *CB = dyn_cast<CallBase>(this);
+  if (!CB)
+    return false;
+  // For call instructions, we also need to check parameter and return
+  // attributes that are can cause UB.
```
Comment (nikic) [inline llvm/lib/IR/Instruction.cpp:562]:
```suggestion
  // attributes that can cause UB.
```

**Review by nikic — APPROVED** [review]
LGTM
