### PR TITLE
[flang][semantics] fix IsConstantExpr for intrinsic with optional argument

### LINKED ISSUE #161694: [flang] Flang seems too restrictive on constant expression usage.
Consider the following code
```
    type A (p, r)
        integer, kind :: p, r
        real (selected_real_kind(p, r)) :: data
    end type
    type(a(6,23)) :: a1
    print*, a1%data%kind

end
```

Flang failed at the compile time with
```
error: Semantic errors in t.f
./t.f:3:15: error: Must be a constant value
          real (selected_real_kind(p, r)) :: data
                ^^^^^^^^^^^^^^^^^^^^^^^^
```

All ifort, gfortran and XLF compile and execute the code successfully.
The folding of `selected_real_kind` could occur when the type is instantiated.

### PR DESCRIPTION
**Pull request by akuhlens**
fixes https://github.com/llvm/llvm-project/issues/161694

Exposes that some sequences of duplicate messages are being printed, which is fixed in https://github.com/llvm/llvm-project/pull/161916 .

### CODE REVIEW

File: flang/lib/Evaluate/check-expression.cpp [hunk 1]
```diff
@@ -135,16 +135,21 @@ bool IsConstantExprHelper<INVARIANT>::operator()(
...
+                      &proc.dummyArguments[j].u)
+                : nullptr};
+        if (dataDummy &&
             dataDummy->attrs.test(
                 characteristics::DummyDataObject::Attr::OnlyIntrinsicInquiry)) {
           // The value of the argument doesn't matter
         } else if (!arg) {
-          return false;
+          // Missing optional arguments are constant
+          if (!(dataDummy &&
```
Comment (klausler) [inline flang/lib/Evaluate/check-expression.cpp:148]: Shouldn't this be `if (!dataDummy && ...) {`?

Comment (akuhlens) [reply flang/lib/Evaluate/check-expression.cpp:148]: Nope, this code is a little weird in that it is written in such a style that it is mimic the short circuiting of the logical check. The logic is, "If the argument is missing and it isn't optional then you can short circuit and return false. Otherwise, you need to check all the other arguments (by falling through)."

I think it is a little confusing because `dataDummy` is a pointer we are checking for whether it is present. By De Morgan's dual this is equivalent to `!dataDummy || !dataDummy->attrs.test(...)`.

**Review by klausler — APPROVED** [review]

**Review by DanielCChen — COMMENTED** [review]
The test cases are fixed.
Thanks.
