### PR TITLE
[clang][Itanium Mangle] Enable mangling of enclosing class for member…

### LINKED ISSUE #110088: [abi] Declaring class of a member-like friend method is not mangled.
The code sample

```cpp
template <class>
concept True = true;

namespace test2 {
 template<typename T> struct A {
    template<typename U = void>
    friend void g(...) requires True<T> && True<U> {}
 };

 void call() {
    A<int> ai;
    A<bool> ab;
    g(ai);
    g(ab);
 }
}
```

does not compile with the following error 

```
Output of x86-64 clang (trunk) (Compiler #1)
<source>:10:17: error: definition with same mangled name '_ZN5test2F1gIvEEvzQaa4TrueIT_E4TrueITL0__E' as another definition
   10 |     friend void g(...) requires True<T> && True<U> {}
      |                 ^
<source>:10:17: note: previous definition is here
1 error generated.
Compiler returned: 1
```

The reason appears to be that the enclosing class template specialization `A<int>` (or `A<bool>`, respectively) is not part of the mangled name `_ZN5test2F1gIvEEvzQaa4TrueIT_E4TrueITL0__E`, resulting in `g(ai)` and `g(ab)` mangled as the same string.

As per the discussion in https://github.com/itanium-cxx-abi/cxx-abi/issues/24#issuecomment-934493006, the code above is valid and the solution is to include the declaring class in the mangling. From @rjmccall on the aforementioned issue:

```
The only viable implementation path I can see, given that nothing in the standard prevents these friend declarations from otherwise matching perfectly in signatures and requires-clauses, is to mangle the declaring class for these friends.
```

Note 1: gcc can compile the above snippet by including the declaring class in the mangling, which results in the mangled string `_ZN5test21AIiEF1gIvEEvzQaa4TrueIT_E4TrueITL0__E` for `g(ai)` (Note `AIiE` mangles the declaring class),  and `_ZN5test21AIbEF1gIvEEvzQaa4TrueIT_E4TrueITL0__E`  for `g(ab)` (Note `AIbE` mangles the declaring class).

Note 2: this issue stands in the way of implementing the demangling of template parameters in constraints (https://github.com/llvm/llvm-project/blob/main/libcxxabi/src/demangle/ItaniumDemangle.h#L5795).
`T_` in `_ZN5test21AIiEF1gIvEEvzQaa4TrueIT_E4TrueITL0__E` is impossible to demangle, since it is a substitution for the template argument of class A that is not part of the mangling.

### PR DESCRIPTION
**Pull request by VitaNuo**
…-like friend function templates only if ` -fclang-abi-compat>19`.

### CODE REVIEW

**Comment by hokein** [comment]
Thanks.

Can you update the comment [here](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/LangOptions.h#L242-L245) to mention this case? 

And I think it is better to move the release note `Mangle friend function ...` from the `Bug Fixes to C++ Support` to `ABI Changes in This Version`.

**Comment by VitaNuo** [comment]
> Thanks.
> 
> Can you update the comment [here](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/LangOptions.h#L242-L245) to mention this case?
> 
> And I think it is better to move the release note `Mangle friend function ...` from the `Bug Fixes to C++ Support` to `ABI Changes in This Version`.

Thank you, the comments should be addressed now.

**Review by hokein — APPROVED** [review]
Thank you, this looks good to me. Let’s wait for a bit to see if other reviewers have any additional comments.

File: clang/lib/AST/ItaniumMangle.cpp [hunk 1]
```diff
@@ -704,6 +704,15 @@ ItaniumMangleContextImpl::getEffectiveDeclContext(const Decl *D) {
       return D->getLexicalDeclContext()->getRedeclContext();
   }
 
+  if (const auto *FTD = dyn_cast<FunctionTemplateDecl>(D)) {
+    // Member-like constrained friends are mangled as if they were members of
+    // the enclosing class.
+    if (FTD->getTemplatedDecl()->isMemberLikeConstrainedFriend() &&
+        getASTContext().getLangOpts().getClangABICompat() >
+            LangOptions::ClangABI::Ver19)
+      return D->getLexicalDeclContext()->getRedeclContext();
```
Comment (usx95) [inline clang/lib/AST/ItaniumMangle.cpp:713]: This looks quite a tech debt. I am not aware of our policy regarding the past ABIs we should be supporting, but there definitely should be a time limit.
We should add a fixme to remove ABI checks after supported time
```
FIXME: Remove check for Ver17 and use D->getAsFunction() after clang-X
FIXME: Remove check for Ver19 after clang-Y
``` 
@zygoloid Are you aware of a reasonable clang version (X and Y here) after which we should stop supporting Ver17 ? I can guess maybe 1-3 years ?

**Review by usx95 — COMMENTED** [review]
Thanks. Left a comment about adding a FIXME to remove ABI compat checks and figuring out the support for past ABI.

File: clang/lib/AST/ItaniumMangle.cpp [hunk 2]
```diff
@@ -693,7 +693,7 @@ ItaniumMangleContextImpl::getEffectiveDeclContext(const Decl *D) {
     if (VD->isExternC())
       return getASTContext().getTranslationUnitDecl();
 
-  if (const auto *FD = D->getAsFunction()) {
+  if (const auto *FD = dyn_cast<FunctionDecl>(D)) {
```
[the remark this answers is not in the document]
Comment (VitaNuo) [reply clang/lib/AST/ItaniumMangle.cpp]: Thank you, simplified.

File: clang/lib/AST/ItaniumMangle.cpp [hunk 3]
```diff
@@ -693,14 +693,13 @@ ItaniumMangleContextImpl::getEffectiveDeclContext(const Decl *D) {
...
+  if (const auto *FD = getASTContext().getLangOpts().getClangABICompat() >
+                               LangOptions::ClangABI::Ver19
+                           ? D->getAsFunction()
+                           : dyn_cast<FunctionDecl>(D)) {
     // Member-like constrained friends are mangled as if they were members of
     // the enclosing class.
-    if (FD->isMemberLikeConstrainedFriend() &&
-        getASTContext().getLangOpts().getClangABICompat() >
-            LangOptions::ClangABI::Ver17)
+    if (FD->isMemberLikeConstrainedFriend())
```
Comment (hokein) [inline clang/lib/AST/ItaniumMangle.cpp:702]: this looks like a behavior change, we should keep the `getClangABICompat() > LangOptions::ClangABI::Ver17` check.

File: clang/lib/AST/ItaniumMangle.cpp [hunk 4]
```diff
@@ -693,14 +693,13 @@ ItaniumMangleContextImpl::getEffectiveDeclContext(const Decl *D) {
     if (VD->isExternC())
       return getASTContext().getTranslationUnitDecl();
 
-  if (const auto *FD = D->getAsFunction()) {
-    if (FD->isExternC())
```
Comment (hokein) [inline clang/lib/AST/ItaniumMangle.cpp:697]: why removing the `isExternC()`? this will change the behavior.

File: clang/lib/AST/ItaniumMangle.cpp (hunk 3 above)
Comment (VitaNuo) [reply clang/lib/AST/ItaniumMangle.cpp]: Yes sorry, I might have misinterpreted the comment above.

File: clang/lib/AST/ItaniumMangle.cpp (hunk 4 above)
Comment (VitaNuo) [reply clang/lib/AST/ItaniumMangle.cpp:697]: It's back.

**Review by usx95 — APPROVED** [review]
Thanks. LGTM.
