### PR TITLE
Diagnose the code with trailing comma in the function call.

### LINKED ISSUE #125225: clang accepts invalid code that with trailing comma
Clang doesn't diagnose the following invalid code (with the trailing comma), it treats as valid code:

 
```
void func(int);
void k() {
  func(1, );
}
```

This is a regression caused by https://github.com/llvm/llvm-project/pull/114684.

### PR DESCRIPTION
**Pull request by hokein**
This patch fixes a regression caused by https://github.com/llvm/llvm-project/pull/114684 where clang accepts trailing commas for function calls.

Fixes #125225

### CODE REVIEW

File: clang/lib/Parse/ParseExpr.cpp [hunk 1]
```diff
@@ -2237,6 +2237,9 @@ Parser::ParsePostfixExpressionSuffix(ExprResult LHS) {
             if (PP.isCodeCompletionReached() && !CalledSignatureHelp)
               RunSignatureHelp();
             LHS = ExprError();
+          } else if (!HasError && HasTrailingComma) {
+            // FIXME: add a FIXIT to remove the trailing comma.
+            Diag(Tok, diag::err_extraneous_trailing_comma);
```
Comment (cor3ntin) [inline clang/lib/Parse/ParseExpr.cpp:2242]: I think we should just reuse `err_expected_expression`. The important point here is that there is a diagnostic.
Note sure this happens often enough to warrant a fixit

**Comment by cor3ntin** [comment]
Can you add a release note and a more detailed description? Thanks

File: clang/lib/Parse/ParseExpr.cpp (hunk 1 above)
Comment (hokein) [reply clang/lib/Parse/ParseExpr.cpp]: Reused the existing err_expected_expression.

I initially thought that the new `err_extraneous_trailing_comma` provided a clearer message than `err_expected_expression`, but it only applies to a specific test case (the one added in this PR).

For other cases, such as `function2Arg(1, );`, the new diagnostic is incorrect.

**Comment by hokein** [comment]
> Can you add a release note and a more detailed description? Thanks

Done. I think we don't need a release note, this is a regression fix, and https://github.com/llvm/llvm-project/pull/114684 is not released yet.

**Review by cor3ntin — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Comment by cor3ntin** [comment]
@hokein feel free to merge :)

**Comment by hokein** [comment]
> @hokein feel free to merge :)

Thanks for the ping.

We have several instances of `func(1,);` in our internal codebase, and the number is not small unfortunately. I'm currently working on a cleanup, which will take some time. I plan to merge this patch as soon as the cleanup is complete (ETA: by the end of this week).  

Additionally, we will need to backport this fix to the `release20` branch.

**Comment by hokein** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/922f339c4ef3631f66dc4b8caa4c356103dbf69d

**Comment by bjope** [comment]
This seems to break something with variadic args and the gcc hack with ## to ignore the trailing comma error:

```
#include <stdio.h>
#define debug_ok(format, ...) fprintf(stderr, format, ## __VA_ARGS__)
void foo() {
    debug_ok("qwerty");
}

#define debug_nok(...) fprintf(stderr, "qwerty", ## __VA_ARGS__)
void bar() {
    debug_nok();
}
```

At least with `-std=c23` we get this:
```
<source>:9:5: error: expected expression
    9 |     debug_nok();
      |     ^
<source>:7:64: note: expanded from macro 'debug_nok'
    7 | #define debug_nok(...) fprintf(stderr, "qwerty", ## __VA_ARGS__)
      |                                                                ^
1 error generated.
Compiler returned: 1
```

See godbolt test here: https://godbolt.org/z/fejP1oa1f

But given that there is a difference between the foo and bar tests maybe I've missed some special rule for when this variadic macro solution with ## applies.

**Comment by bjope** [comment]
Thanks. I see now that it did not work with older clang (at least not 19.1.0).

It did however work with our downstream fork before this patch. I haven't figured out how we avoided the error in the past. I guess we must have something downstream that avoided the error in the past, but I can't remember that we've done anything actively to suppress such errors. Weird.

I also agree that our downstream users should try to use __VA_OPT__ instead (hopefully there are no other tools that would complain about that).
