### PR TITLE
[Clang] Adjust concept definition locus

### LINKED ISSUE #55875: Clang gives an error when using recursion in a concept
MSVC: https://godbolt.org/z/M9YKEq6df
Clang: https://godbolt.org/z/rMM61PKKx

`error: use of undeclared identifier 'IsAnyType'`

I think the compiler gives this error for no reason, because "IsAnyType" has already been declared. Also, Microsoft's compiler compiles this code well.

### PR DESCRIPTION
**Pull request by cor3ntin**
Per [basic.scope], the locus of a concept is immediately after the introduction of its name.

This let us provide better diagnostics for attempt to define recursive concepts.

Note that recursive concepts are not supported per https://eel.is/c++draft/basic#scope.pdecl-note-3, but there is no normative wording for that restriction. This is a known defect introduced by [p1787r6](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html).

Fixes #55875

### CODE REVIEW

**Review by AaronBallman — APPROVED** [review]
LGTM

**Review by Sirraide — APPROVED** [review]

File: clang/lib/Sema/SemaTemplate.cpp [hunk 1]
```diff
@@ -8499,23 +8498,63 @@ Decl *Sema::ActOnConceptDefinition(
...
+                        forRedeclarationInCurContext());
+  LookupName(Previous, S);
+  FilterLookupForScope(Previous, CurContext, S, /*ConsiderLinkage=*/false,
+                       /*AllowInlineNamespace*/ false);
+
+  // We cannot properly handle redeclarations until we parse the constraint
+  // expression, so only inject the name if we are sure we are not redeclaring a
+  // symbol
+  if (Previous.empty())
+    PushOnScopeChains(NewDecl, S, true);
```
Comment (zyn0217) [inline clang/lib/Sema/SemaTemplate.cpp:8512]: We need to restore the scope chain outside of `Sema::ActOnStartConceptDefinition()` if the later parsed requires expression turns out to be invalid. Otherwise, the use of the concept would still find the invalid concept Decl, and since the declaration doesn't have the expression anymore, we would run into crashes in evaluation.

Comment (zyn0217) [reply clang/lib/Sema/SemaTemplate.cpp:8512]: Or rather, I think we should inject the concept decl in `ActOnFinishConceptDefinition()` instead of here.
