### PR TITLE
[mlir][linalg] Allow promotion to use the original subview size

### LINKED ISSUE #144268: [mlir][linalg][promotion] Allow promoting dynamic buffer with dynamic alloc size
Currently linalg promotion transform attempts to allocate the promoted buffer with the smallest size. It is achieved by computing a constant upper bound for the promoted subviews, and only when the computation fails it fallbacks to dynamic allocation size. It would be nice to have the option to prefer the exact allocation size, even at the price of dynamic allocation.

I'd be happy to add the support myself if there's interest.

### PR DESCRIPTION
**Pull request by zbenzion**
linalg promotion attempts to compute a constant upper bound for the allocated buffer size. Only when failed to compute an upperbound it fallbacks to the original subview size, which may be dynamic.

Adding a promotion option to use the original subview size by default, thus minimizing the allocation size.
Fixes #144268.

### CODE REVIEW

File: mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h [hunk 1]
```diff
@@ -427,6 +427,13 @@ struct LinalgPromotionOptions {
     useFullTileBuffersDefault = use;
     return *this;
   }
+  /// If true bufffers will be allocated with the original subview size. This
```
Comment (ftynse) [inline mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h]:
```suggestion
  /// If true, buffers will be allocated with the original subview size. This
```

File: mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h [hunk 2]
```diff
@@ -811,6 +819,7 @@ struct PromotionInfo {
 };
 FailureOr<PromotionInfo>
 promoteSubviewAsNewBuffer(OpBuilder &b, Location loc, memref::SubViewOp subView,
+                          bool useOriginalSubviewSize,
```
Comment (ftynse) [inline mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h:817]: Let's have this take `const LinalgPromotionOptions &` instead of an individual boolean.

**Review by ftynse — APPROVED** [review]
LGTM after comments addressed, thanks!

File: mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h (hunk 2 above)
Comment (zbenzion) [reply mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h:817]: In general, sounds good!

It seems though that the caller `promoteSubViews` is already using `LinalgOpInstancePromotionOptions`, which is an internal representation in Promotion.cpp. 
Another issue is that `LinalgPromotionOptions` doesn't force an explicit `allocationFn`, and `promoteSubviewAsNewBuffer` does.

We could maybe, alternatively, provide a `LinalgPromoteSubviewAsNewBufferOptions`, which will pack the boolean and the allocation function.
What do you think?

Comment (ftynse) [reply mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h:817]: Can we just extend one or another? I'd rather avoid yet another helper class so if it's impossible to extend one of the existing classes, we can stick with the single argument here.

File: mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h (hunk 1 above)
Comment (zbenzion) [reply mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h]: fixed :)

File: mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h (hunk 2 above)
Comment (zbenzion) [reply mlir/include/mlir/Dialect/Linalg/Transforms/Transforms.h:817]: Since this method is used both internally in Promotion.cpp (`LinalgOpInstancePromotionOptions`) and is exposed externally (`LinalgPromotionOptions`) I feel like it'd be a little unnatural to use one or the other at this stage. I kept the single argument, as you suggested.

If everything looks good, I'd appreciate if you can hit the merge button for me, since I don't have write access.
Thanks for the review!
