### PR TITLE
[SelectOptimize] Emit Fatal Error instead of Asserting on null PSI

### LINKED ISSUE #192759: Crash in select-optimize
Simplified IR program:

`$ cat simple.ll`

```llvm
define i32 @f(i1 %cond, i32 %a, i32 %b) {
  %s = select i1 %cond, i32 %a, i32 %b
  ret i32 %s
}
```

Crashes on opt with select-optmize (tested with LLVM commit 5b938b8c0366) :
```
$ opt --mtriple=x86_64-unknown-linux-gnu -passes=select-optimize -S simple.ll
opt: llvm-project/llvm/lib/CodeGen/SelectOptimize.cpp:372: llvm::PreservedAnalyses {anonymous}::SelectOptimizeImpl::run(llvm::Function&, llvm::FunctionAnalysisManager&): Assertion `PSI && "This pass requires module analysis pass `profile-summary`!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
Stack dump:
0.	Program arguments: llvm-project/build/bin/opt --mtriple=x86_64-unknown-linux-gnu -passes=select-optimize -S simple.ll
1.	Running pass "function(select-optimize)" on module "simple.ll"
2.	Running pass "select-optimize" on function "f"
 #0 0x00007ef654e39d62 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (llvm-project/build/bin/../lib/libLLVMSupport.so.23.0git+0x239d62)
 #1 0x00007ef654e369bf llvm::sys::RunSignalHandlers() (llvm-project/build/bin/../lib/libLLVMSupport.so.23.0git+0x2369bf)
 #2 0x00007ef654e36b0c SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x00007ef654845330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #4 0x00007ef65489eb2c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x9eb2c)
 #5 0x00007ef65484527e raise (/lib/x86_64-linux-gnu/libc.so.6+0x4527e)
 #6 0x00007ef6548288ff abort (/lib/x86_64-linux-gnu/libc.so.6+0x288ff)
 #7 0x00007ef65482881b (/lib/x86_64-linux-gnu/libc.so.6+0x2881b)
 #8 0x00007ef65483b517 (/lib/x86_64-linux-gnu/libc.so.6+0x3b517)
 #9 0x00007ef64c56545b llvm::SelectOptimizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (llvm-project/build/bin/../lib/../lib/libLLVMCodeGen.so.23.0git+0x76545b)
#10 0x00007ef6528b6865 llvm::detail::PassModel<llvm::Function, llvm::SelectOptimizePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (llvm-project/build/bin/../lib/../lib/libLLVMAMDGPUCodeGen.so.23.0git+0x4b6865)
#11 0x00007ef64a516b57 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (llvm-project/build/bin/../lib/../lib/libLLVMCore.so.23.0git+0x316b57)
#12 0x00007ef6528b90e5 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (llvm-project/build/bin/../lib/../lib/libLLVMAMDGPUCodeGen.so.23.0git+0x4b90e5)
#13 0x00007ef64a514d94 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (llvm-project/build/bin/../lib/../lib/libLLVMCore.so.23.0git+0x314d94)
#14 0x00007ef65506a715 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (llvm-project/build/bin/../lib/libLLVMOptDriver.so.23.0git+0x21715)
#15 0x00007ef64a5159d7 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (llvm-project/build/bin/../lib/../lib/libLLVMCore.so.23.0git+0x3159d7)
#16 0x00007ef655077129 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool, bool) (llvm-project/build/bin/../lib/libLLVMOptDriver.so.23.0git+0x2e129)
#17 0x00007ef655082717 optMain (llvm-project/build/bin/../lib/libLLVMOptDriver.so.23.0git+0x39717)
#18 0x00007ef65482a1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
#19 0x00007ef65482a28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
#20 0x0000645eabd05095 _start (llvm-project/build/bin/opt+0x1095)
```

This appears to be an issue with missing ProfileSummaryAnalysis results; select-optmize may need to use FAM.getResult instead of FAM.getCachedResult.

### PR DESCRIPTION
**Pull request by boomanaiden154**
SelectOptimize expects to have PSI available which will normally be available if the pipeline is set up correctly to require ProfileSummaryInfo at the beginning. However, we do not want to assert if someone sets up the pipeline incorrectly, instead reporting a fatal usage error.

Fixes #192759.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LG

File: llvm/lib/CodeGen/SelectOptimize.cpp [hunk 1]
```diff
@@ -369,7 +369,9 @@ PreservedAnalyses SelectOptimizeImpl::run(Function &F,
 
   PSI = FAM.getResult<ModuleAnalysisManagerFunctionProxy>(F)
             .getCachedResult<ProfileSummaryAnalysis>(*F.getParent());
-  assert(PSI && "This pass requires module analysis pass `profile-summary`!");
+  if (!PSI)
+    reportFatalUsageError("This pass requires the profile-summary module "
```
Comment (arsenm) [inline llvm/lib/CodeGen/SelectOptimize.cpp:373]: error messages should start with lowercase. Also test would be good

Comment (arsenm) [reply llvm/lib/CodeGen/SelectOptimize.cpp:373]: We also really need a utility function for get required module analysis. We repeat this pattern in so many places

Comment (boomanaiden154) [reply llvm/lib/CodeGen/SelectOptimize.cpp:373]: First comment done in #193034. I'll try and find some time this week to get a utility function set up and move some passes over.
