### PR TITLE
[Clang][Sema] set declaration invalid earlier to prevent crash in calculating record layout

### LINKED ISSUE #75221: crash on invalid after "error: 'foo' cannot be defined in a type alias template"
The following invalid code crashes on the current post 17 trunk(2e197602305be18b963928e6ae024a004a95af6d)
https://godbolt.org/z/e7GqqKEKf

```
template <class T> using foo = struct foo {
  T size = 0;
};
foo a;
```

It triggers the following assert
```
clang++: /root/build/tools/clang/include/clang/AST/TypeNodes.inc:74: 
clang::TypeInfo clang::ASTContext::getTypeInfoImpl(const clang::Type*) const: 
Assertion `!T->isDependentType() && "should not see dependent types here"' failed.
```
The full dump is
```
<source>:1:39: error: 'foo' cannot be defined in a type alias template
    1 | template <class T> using foo = struct foo {
      |                                       ^
clang++: /root/build/tools/clang/include/clang/AST/TypeNodes.inc:74: clang::TypeInfo clang::ASTContext::getTypeInfoImpl(const clang::Type*) const: Assertion `!T->isDependentType() && "should not see dependent types here"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++14 -pedantic-errors <source>
1.	<source>:4:6: current parser token ';'
 #0 0x000000000379d408 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x379d408)
 #1 0x000000000379b0ec llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x379b0ec)
 #2 0x00000000036e3bd8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f0798c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f0798c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007f0798c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007f0798c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007f0798c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x00007f0798c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x0000000006e9af1c clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e9af1c)
#10 0x0000000006e82df7 clang::ASTContext::getTypeInfo(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e82df7)
#11 0x0000000006e9b09b clang::ASTContext::getTypeInfoInChars(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e9b09b)
#12 0x0000000006e9b1b3 clang::ASTContext::getTypeInfoInChars(clang::QualType) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e9b1b3)
#13 0x0000000007340f25 (anonymous namespace)::ItaniumRecordLayoutBuilder::LayoutField(clang::FieldDecl const*, bool) RecordLayoutBuilder.cpp:0:0
#14 0x00000000073427af (anonymous namespace)::ItaniumRecordLayoutBuilder::LayoutFields(clang::RecordDecl const*) RecordLayoutBuilder.cpp:0:0
#15 0x000000000733e076 clang::ASTContext::getASTRecordLayout(clang::RecordDecl const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x733e076)
#16 0x0000000006e9ac51 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e9ac51)
#17 0x0000000006e82df7 clang::ASTContext::getTypeInfo(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e82df7)
#18 0x0000000006e99db7 clang::ASTContext::getTypeAlignInChars(clang::QualType) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e99db7)
#19 0x000000000613ca20 clang::Sema::CheckArgAlignment(clang::SourceLocation, clang::NamedDecl*, llvm::StringRef, clang::QualType, clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x613ca20)
#20 0x000000000616e327 clang::Sema::CheckConstructorCall(clang::FunctionDecl*, clang::QualType, llvm::ArrayRef<clang::Expr const*>, clang::FunctionProtoType const*, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x616e327)
#21 0x000000000635cebc clang::Sema::CompleteConstructorCall(clang::CXXConstructorDecl*, clang::QualType, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, llvm::SmallVectorImpl<clang::Expr*>&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x635cebc)
#22 0x00000000066a6050 PerformConstructorInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::InitializationSequence::Step const&, bool&, bool, bool, clang::SourceLocation, clang::SourceLocation) SemaInit.cpp:0:0
#23 0x00000000066b93f2 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66b93f2)
#24 0x00000000062b5114 clang::Sema::ActOnUninitializedDecl(clang::Decl*) (.part.0) SemaDecl.cpp:0:0
#25 0x0000000005f872d6 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f872d6)
#26 0x0000000005f96170 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f96170)
#27 0x0000000005f5f42b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f5f42b)
#28 0x0000000005f5fbb1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f5fbb1)
#29 0x0000000005f66e66 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f66e66)
#30 0x0000000005f67d0d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f67d0d)
#31 0x0000000005f5acfa clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f5acfa)
#32 0x000000000401e378 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x401e378)
#33 0x000000000428a9b9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x428a9b9)
#34 0x0000000004208c9e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4208c9e)
#35 0x000000000436974e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x436974e)
#36 0x0000000000c01496 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc01496)
#37 0x0000000000bf8d2a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#38 0x000000000405f3a9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#39 0x00000000036e4084 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x36e4084)
#40 0x000000000405f99f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#41 0x0000000004027c05 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4027c05)
#42 0x000000000402866d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x402866d)
#43 0x0000000004030585 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4030585)
#44 0x0000000000bfe90c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbfe90c)
#45 0x0000000000af7a71 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xaf7a71)
#46 0x00007f0798c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#47 0x00007f0798c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#48 0x0000000000bf880e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf880e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by jcsxky**
Try to fix https://github.com/llvm/llvm-project/issues/75221
This crash caused by calculating record layout which contains a field declaration with dependent type. Make it invalid before it is a complete definition to prevent this crash. Define a new scope type to record this type alias and set the record declaration invalid when it is defined in a type alias template.

### CODE REVIEW

File: clang/lib/Sema/SemaType.cpp [hunk 1]
```diff
@@ -3899,6 +3899,9 @@ static QualType GetDeclSpecTypeForDeclarator(TypeProcessingState &state,
       SemaRef.Diag(OwnedTagDecl->getLocation(), DiagID)
           << SemaRef.Context.getTypeDeclType(OwnedTagDecl);
       D.setInvalidType(true);
+      OwnedTagDecl->setCompleteDefinition(false);
+      OwnedTagDecl->setInvalidDecl();
+      OwnedTagDecl->setCompleteDefinition();
```
Comment (erichkeane) [inline clang/lib/Sema/SemaType.cpp:3904]: Are we sure the `OwnedTagDecl` is ALWAYS a complete definition here?  Should we cache the existing value before 3902 and restore that rather than always setting it complete?

Comment (shafik) [reply clang/lib/Sema/SemaType.cpp:3904]: `GetDeclSpecTypeForDeclarator` is called from two places `GetTypeForDeclaratorCast(...)` and where that is called `D.isInvalidType()` is checked. It is also called from `GetTypeForDeclarator(...)` and the checking of after that call is a bit more varied. I am wondering if we are being sloppy in one of those calls.

Comment (jcsxky) [reply clang/lib/Sema/SemaType.cpp:3904]: @erichkeane Condition holds in outer `if`(line 3841) indicates `OwnedTagDecl` is a complete definition.

Comment (jcsxky) [reply clang/lib/Sema/SemaType.cpp:3904]: @shafik If I understand correctly, you want to set `OwnedTagDecl` invalid before it is a complete definition. I will look into the code.

Comment (jcsxky) [reply clang/lib/Sema/SemaType.cpp:3904]:
```cpp
#0  clang::TagDecl::setCompleteDefinition (this=0x5555556cabd8, V=true) at /home/huqizhi/llvm-project/clang/include/clang/AST/Decl.h:3656
#1  0x00007fffe775b540 in clang::TagDecl::completeDefinition (this=0x5555556cabd8) at /home/huqizhi/llvm-project/clang/lib/AST/Decl.cpp:4720
#2  0x00007fffe775d110 in clang::RecordDecl::completeDefinition (this=0x5555556cabd8) at /home/huqizhi/llvm-project/clang/lib/AST/Decl.cpp:5049
#3  0x00007fffe779be00 in clang::CXXRecordDecl::completeDefinition (this=0x5555556cabd8, FinalOverriders=0x0) at /home/huqizhi/llvm-project/clang/lib/AST/DeclCXX.cpp:2059
#4  0x00007fffe779bdd9 in clang::CXXRecordDecl::completeDefinition (this=0x5555556cabd8) at /home/huqizhi/llvm-project/clang/lib/AST/DeclCXX.cpp:2055
#5  0x00007fffe44cbab2 in clang::Sema::ActOnFields (this=0x5555556b7060, S=0x5555556d6700, RecLoc=..., EnclosingDecl=0x5555556cabd8, Fields=..., LBrac=..., RBrac=..., Attrs=...)
    at /home/huqizhi/llvm-project/clang/lib/Sema/SemaDecl.cpp:19654
#6  0x00007fffe4636eed in clang::Sema::ActOnFinishCXXMemberSpecification (this=0x5555556b7060, S=0x5555556d6700, RLoc=..., TagDecl=0x5555556cabd8, LBrac=..., RBrac=..., AttrList=...)
    at /home/huqizhi/llvm-project/clang/lib/Sema/SemaDeclCXX.cpp:10540
#7  0x00007fffe5956cf2 in clang::Parser::ParseCXXMemberSpecification (this=0x5555556c4580, RecordLoc=..., AttrFixitLoc=..., Attrs=..., TagType=25, TagDecl=0x5555556cabd8)
    at /home/huqizhi/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:3782
#8  0x00007fffe5954f8e in clang::Parser::ParseClassSpecifier (this=0x5555556c4580, TagTokKind=clang::tok::kw_struct, StartLoc=..., DS=..., TemplateInfo=..., AS=clang::AS_none, EnteringContext=false, 
    DSC=clang::Parser::DeclSpecContext::DSC_alias_declaration, Attributes=...) at /home/huqizhi/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:2252
#9  0x00007fffe591b23e in clang::Parser::ParseDeclarationSpecifiers (this=0x5555556c4580, DS=..., TemplateInfo=..., AS=clang::AS_none, DSContext=clang::Parser::DeclSpecContext::DSC_alias_declaration, 
    LateAttrs=0x0, AllowImplicitTypename=clang::ImplicitTypenameContext::Yes) at /home/huqizhi/llvm-project/clang/lib/Parse/ParseDecl.cpp:4553
#10 0x00007fffe59167a3 in clang::Parser::ParseSpecifierQualifierList (this=0x5555556c4580, DS=..., AllowImplicitTypename=clang::ImplicitTypenameContext::Yes, AS=clang::AS_none, 
    DSC=clang::Parser::DeclSpecContext::DSC_alias_declaration) at /home/huqizhi/llvm-project/clang/lib/Parse/ParseDecl.cpp:2829
#11 0x00007fffe592bea4 in clang::Parser::ParseSpecifierQualifierList (this=0x5555556c4580, DS=..., AS=clang::AS_none, DSC=clang::Parser::DeclSpecContext::DSC_alias_declaration)
    at /home/huqizhi/llvm-project/clang/include/clang/Parse/Parser.h:2480
#12 0x00007fffe5906906 in clang::Parser::ParseTypeName (this=0x5555556c4580, Range=0x0, Context=clang::DeclaratorContext::AliasTemplate, AS=clang::AS_none, OwnedType=0x7fffffff8a88, 
    Attrs=0x7fffffff90b0) at /home/huqizhi/llvm-project/clang/lib/Parse/ParseDecl.cpp:59
```
From the trace we can see that if we want to set `OwnedTagDecl` invalid before it's a complete definition, `Context` (`DeclaratorContext`)should be passed through these funtions (I haven't found how to get this information without passing `Context` as of now). It's not a better approach than current version from my side. @shafik WDYT?

Comment (erichkeane) [reply clang/lib/Sema/SemaType.cpp:3904]: It DEFINITELY seems strange to me that we're marking this 'complete' before we know if it is valid.  So from that perspective, this patch is in the 'wrong' place.

**Comment by jcsxky** [comment]
gently ping. @erichkeane @shafik Any opinions on this pr?

**Review by erichkeane — APPROVED** [review]
