### PR TITLE
[clang-tidy] fix modernize-use-auto incorrect fix hints for pointer

### LINKED ISSUE #77891: clang-tidy check modernize-use-auto fails on pointer to array types
The clang-tidy (LLVM 17.0.6, Windows) check modernize-use-auto fails when a pointer-to-array variable is assigned a value returned by new.

The code in the functions
```
void foo()
{
    int(*pBar)[2] = new int[10][2];
}
```
is changed to
```
void foo()
{
    auto = new int[10][2];
}
```
which is missing the variable name. 

It should have been changed to this:
```
void foo()
{
    auto pBar = new int[10][2];
}
```

### PR DESCRIPTION
**Pull request by HerrCai0907**
avoid create incorrect fix hints for pointer to array type and pointer to function type Fixes: #77891

### CODE REVIEW

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 1]
```diff
@@ -333,6 +335,26 @@ void UseAutoCheck::replaceIterators(const DeclStmt *D, ASTContext *Context) {
       << FixItHint::CreateReplacement(Range, "auto");
 }
 
+namespace {
+
+void ignoreTypeLocClasses(
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:340]: use static instead of anonymous namespace

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 2]
```diff
@@ -333,6 +335,26 @@ void UseAutoCheck::replaceIterators(const DeclStmt *D, ASTContext *Context) {
...
+    TypeLoc &Loc, llvm::SmallVector<TypeLoc::TypeLocClass> const &LocClasses) {
+  while (llvm::is_contained(LocClasses, Loc.getTypeLocClass()))
+    Loc = Loc.getNextTypeLoc();
+}
+
+bool isMutliLevelPointerToTypeLocClasses(
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:346]: use static instead of anonymous namespace

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 3]
```diff
@@ -405,12 +421,20 @@ void UseAutoCheck::replaceExpr(
 
   auto Diag = diag(Range.getBegin(), Message);
 
+  bool ShouldReplenishVariableName = isMutliLevelPointerToTypeLocClasses(
+      FirstDecl->getTypeSourceInfo()->getTypeLoc(),
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:425]: Would be nice to verify if getTypeSourceInfo is not null.

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 4]
```diff
@@ -405,12 +421,20 @@ void UseAutoCheck::replaceExpr(
...
-  Diag << FixItHint::CreateReplacement(Range, RemoveStars ? "auto " : "auto")
-       << StarRemovals;
+  llvm::StringRef Auto = ShouldReplenishVariableName
+                             ? (RemoveStars ? "auto " : "auto *")
+                             : (RemoveStars ? "auto " : "auto");
+  std::string ReplenishedVariableName =
+      ShouldReplenishVariableName ? FirstDecl->getQualifiedNameAsString() : "";
+  std::string Replacement =
+      (Auto + llvm::StringRef{ReplenishedVariableName}).str();
+  Diag << FixItHint::CreateReplacement(Range, Replacement) << StarRemovals;
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:437]: Maybe instead of replacing everything we could just replace/remove what's needed, so variable name would be left in code not changed. In such case there would be no conflicts with other checks that could want to change name of that variable.

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 5]
```diff
@@ -333,6 +335,26 @@ void UseAutoCheck::replaceIterators(const DeclStmt *D, ASTContext *Context) {
...
+namespace {
+
+void ignoreTypeLocClasses(
+    TypeLoc &Loc, llvm::SmallVector<TypeLoc::TypeLocClass> const &LocClasses) {
+  while (llvm::is_contained(LocClasses, Loc.getTypeLocClass()))
+    Loc = Loc.getNextTypeLoc();
+}
+
+bool isMutliLevelPointerToTypeLocClasses(
+    TypeLoc Loc, llvm::SmallVector<TypeLoc::TypeLocClass> const &LocClasses) {
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:347]: take std::initialization_list instead of vector.

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp [hunk 6]
```diff
@@ -333,6 +335,26 @@ void UseAutoCheck::replaceIterators(const DeclStmt *D, ASTContext *Context) {
       << FixItHint::CreateReplacement(Range, "auto");
 }
 
+namespace {
+
+void ignoreTypeLocClasses(
+    TypeLoc &Loc, llvm::SmallVector<TypeLoc::TypeLocClass> const &LocClasses) {
```
Comment (PiotrZSL) [inline clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:341]: take std::initialization_list instead of vector.

**Review by PiotrZSL — CHANGES_REQUESTED** [review]
Missing tests for arrays and function pointers to confirm that fix work.
+ some nits or possible improvments

File: clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp (hunk 4 above)
Comment (HerrCai0907) [reply clang-tools-extra/clang-tidy/modernize/UseAutoCheck.cpp:438]: It is very hard to split the variable name according to `TypeLoc` and `VarDecl`.

File: clang-tools-extra/test/clang-tidy/checkers/modernize/use-auto-for-pointer.cpp [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+  // CHECK-FIXES-REMOVE: auto f1 =
+  // CHECK-FIXES: auto *f1 =
+}
+
+void pointerToArray() {
+  int(*a1)[2] = new int[10][2];
+  // CHECK-MESSAGES: :[[@LINE-1]]:3: warning: use auto when initializing
+  // CHECK-FIXES-REMOVE: auto a1 =
+  // CHECK-FIXES: auto *a1 =
+}
```
Comment (PiotrZSL) [inline clang-tools-extra/test/clang-tidy/checkers/modernize/use-auto-for-pointer.cpp:18]: Add test with member function pointer.

**Review by PiotrZSL — APPROVED** [review]
LGTM.
