### PR TITLE
[FMV] Allow target version definitions in any order.

### LINKED ISSUE #71698: [FMV] Unhelpful diagnostics when a multi-versioned `target_version("default")` definition comes first
The error message you get when specifying a `target_version("default")` as the first definition is really unhelpful. We should either:
  *  explicitly forbid that and improve the diagnostics such that they explain exactly what went wrong
  *   or (preferably) fix Sema and allow these to come in any order.

AFAICT, the ACLE doesn't place restrictions on the order that these may occur in: https://github.com/ARM-software/acle/blob/main/main/acle.md#function-multi-versioning

```
__attribute__((target_version("default")))
int callee() {
  return 0;
}

__attribute__((target_version("simd")))
int callee() {
  return 1;
}
```

```
example.c:6:16: warning: attribute declaration must precede definition [-Wignored-attributes]
    6 | __attribute__((target_version("simd")))
      |                ^
example.c:2:5: note: previous definition is here
    2 | int callee() {
      |     ^
example.c:7:5: error: redefinition of 'callee'
    7 | int callee() {
      |     ^
example.c:2:5: note: previous definition is here
    2 | int callee() {
      |     ^
1 warning and 1 error generated.
```

### PR DESCRIPTION
**Pull request by labrinea**
This patch fixes #71698. It allows defining the default target version prior to other version definitions without raising semantic errors.

### CODE REVIEW

**Comment by labrinea** [comment]
I appreciate there's some code repetition between `CheckTargetCausesMultiVersioning` and `CheckMultiVersionAdditionalDecl`. Perhaps they deserve some refactoring in a separate patch. Please advise if you have any suggestions for moving the fix elsewhere.

**Review by jroelofs — APPROVED** [review]
Thank you, this is great!

**Review by DanielKristofKiss — APPROVED** [review]
LGTM

File: clang/lib/Sema/SemaDecl.cpp [hunk 1]
```diff
@@ -11455,9 +11465,8 @@ static bool CheckTargetCausesMultiVersioning(Sema &S, FunctionDecl *OldFD,
   }
 
   // If this is 'default', permit the forward declaration.
-  if (!OldFD->isMultiVersion() &&
-      ((NewTA && NewTA->isDefaultVersion() && !OldTA) ||
-       (NewTVA && NewTVA->isDefaultVersion() && !OldTVA))) {
+  if ((NewTA && NewTA->isDefaultVersion() && !OldTA) ||
```
Comment (ilinpv) [inline clang/lib/Sema/SemaDecl.cpp:11468]: Seems we are changing "target" attribute semantic here as well that we would like to avoid, why are we sure that !OldFD->isMultiVersion() is always true ?

File: clang/lib/Sema/SemaDecl.cpp [hunk 2]
```diff
@@ -11429,6 +11429,16 @@ static bool CheckTargetCausesMultiVersioning(Sema &S, FunctionDecl *OldFD,
                                              bool &Redeclaration,
                                              NamedDecl *&OldDecl,
                                              LookupResult &Previous) {
+  assert(!OldFD->isMultiVersion() && "Unexpected MultiVersion");
+
+  // The definitions should be allowed in any order. If we have discovered
+  // a new target version and the preceeding was the default, then add the
+  // corresponding attribute to it.
+  if (OldFD->getMultiVersionKind() == MultiVersionKind::None &&
```
Comment (ilinpv) [inline clang/lib/Sema/SemaDecl.cpp:11437]: Should it work for case target_version("default") declared first? It would good to add tests for various orders of function definition and target_version attributes.

**Review by ilinpv — CHANGES_REQUESTED** [review]

File: clang/lib/Sema/SemaDecl.cpp (hunk 1 above)
Comment (labrinea) [reply clang/lib/Sema/SemaDecl.cpp:11468]: As far as I can tell yes, this is astatic function with exactly one call site.

**Review by ilinpv — APPROVED** [review]
Thanks for tests!
