### PR TITLE
[lldb] Fix Intel PT plugin compile errors

### LINKED ISSUE #77251: [lldb] Intel PT plugin fails to compile
Trying to build LLDB with [support for Intel PT](https://lldb.llvm.org/use/intel_pt.html) results in multiple compilation errors.
Here is how I am compiling it: 
```sh
cd llvm-project
git clone git@github.com:intel/libipt.git
cmake -S libipt -B libipt/build
cmake --build libipt/build
cmake -S llvm -B build -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_ENABLE_PROJECTS='clang;lldb' -DLLDB_BUILD_INTEL_PT=On -DLIBIPT_INCLUDE_PATH=$PWD/libipt/build/libipt/include -DLIBIPT_LIBRARY_PATH=$PWD/libipt/build/lib
cmake --build build
```

Here are the compile errors I get while building LLVM (i.e., the `cmake --build build` step):
```
ninja: Entering directory `build/'
[1/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/DecodedThread.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/DecodedThread.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/DecodedThread.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/DecodedThread.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/DecodedThread.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp
In file included from /usr/include/x86_64-linux-gnu/c++/11/bits/c++allocator.h:33,
                 from /usr/include/c++/11/bits/allocator.h:46,
                 from /usr/include/c++/11/unordered_map:40,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’:
/usr/include/c++/11/bits/alloc_traits.h:516:17:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:115:30:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:105:27:   required from here
/usr/include/c++/11/ext/new_allocator.h:162:11: error: use of deleted function ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::TraceItemStorage()’
  162 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:270:9: note: ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::TraceItemStorage()’ is implicitly deleted because the default definition would be ill-formed:
  270 |   union TraceItemStorage {
      |         ^~~~~~~~~~~~~~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:278:17: error: union member ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::error’ with non-trivial ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  278 |     std::string error;
      |                 ^~~~~
In file included from /usr/include/c++/11/optional:44,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/alloc_traits.h:848:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:248:62:   required from here
/usr/include/c++/11/bits/stl_construct.h:188:51: error: static assertion failed: value type is destructible
  188 |       static_assert(is_destructible<_Value_type>::value,
      |                                                   ^~~~~
/usr/include/c++/11/bits/stl_construct.h:188:51: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
In file included from /usr/include/x86_64-linux-gnu/c++/11/bits/c++allocator.h:33,
                 from /usr/include/c++/11/bits/allocator.h:46,
                 from /usr/include/c++/11/unordered_map:40,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::destroy(_Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’:
/usr/include/c++/11/bits/alloc_traits.h:535:15:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::destroy(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:488:28:   required from ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::iterator = std::vector<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>::iterator]’
/usr/include/c++/11/bits/vector.tcc:121:21:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:105:27:   required from here
/usr/include/c++/11/ext/new_allocator.h:168:20: error: use of deleted function ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::~TraceItemStorage()’
  168 |         { __p->~_Up(); }
      |           ~~~~~~~~~^~
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:270:9: note: ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::~TraceItemStorage()’ is implicitly deleted because the default definition would be ill-formed:
  270 |   union TraceItemStorage {
      |         ^~~~~~~~~~~~~~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:278:17: error: union member ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::error’ with non-trivial ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  278 |     std::string error;
      |                 ^~~~~
In file included from /usr/include/c++/11/vector:66,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/ADT/DenseMap.h:25,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/JSON.h:49,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:15,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/bits/stl_uninitialized.h: In instantiation of ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*>; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/stl_uninitialized.h:333:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*>; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_uninitialized.h:355:2:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Allocator = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:474:3:   required from ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::iterator = std::vector<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>::iterator]’
/usr/include/c++/11/bits/vector.tcc:121:21:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:105:27:   required from here
/usr/include/c++/11/bits/stl_uninitialized.h:138:72: error: static assertion failed: result type must be constructible from value type of input range
  138 |       static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,
      |                                                                        ^~~~~
/usr/include/c++/11/bits/stl_uninitialized.h:138:72: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
[2/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceCursorIntelPT.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceCursorIntelPT.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceCursorIntelPT.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceCursorIntelPT.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceCursorIntelPT.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp: In member function ‘void lldb_private::trace_intel_pt::TraceCursorIntelPT::ClearTimingRangesIfInvalid()’:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp:38:21: error: ‘None’ was not declared in this scope; did you mean ‘llvm::yaml::QuotingType::None’?
   38 |       m_tsc_range = None;
      |                     ^~~~
      |                     llvm::yaml::QuotingType::None
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/Args.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/CompletionRequest.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/ArchSpec.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValue.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValueProperties.h:16,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Core/UserSettingsController.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:18,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/ThreadDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/YAMLTraits.h:130:26: note: ‘llvm::yaml::QuotingType::None’ declared here
  130 | enum class QuotingType { None, Single, Double };
      |                          ^~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp:46:29: error: ‘None’ was not declared in this scope; did you mean ‘llvm::yaml::QuotingType::None’?
   46 |       m_nanoseconds_range = None;
      |                             ^~~~
      |                             llvm::yaml::QuotingType::None
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/Args.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/CompletionRequest.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/ArchSpec.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValue.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValueProperties.h:16,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Core/UserSettingsController.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:18,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/ThreadDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceCursorIntelPT.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/YAMLTraits.h:130:26: note: ‘llvm::yaml::QuotingType::None’ declared here
  130 | enum class QuotingType { None, Single, Double };
      |                          ^~~~
[3/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/ThreadDecoder.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/ThreadDecoder.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/ThreadDecoder.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/ThreadDecoder.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/ThreadDecoder.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/ThreadDecoder.cpp
In file included from /usr/include/c++/11/optional:44,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/ThreadDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/ThreadDecoder.cpp:8:
/usr/include/c++/11/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/alloc_traits.h:848:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:61:7:   required from ‘void __gnu_cxx::new_allocator<_Tp>::destroy(_Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread; _Tp = lldb_private::trace_intel_pt::DecodedThread]’
/usr/include/c++/11/bits/alloc_traits.h:535:15:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::destroy(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread; _Tp = lldb_private::trace_intel_pt::DecodedThread; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread>]’
/usr/include/c++/11/bits/shared_ptr_base.h:528:35:   required from ‘void std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_dispose() [with _Tp = lldb_private::trace_intel_pt::DecodedThread; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:526:7:   required from here
/usr/include/c++/11/bits/stl_construct.h:188:51: error: static assertion failed: value type is destructible
  188 |       static_assert(is_destructible<_Value_type>::value,
      |                                                   ^~~~~
/usr/include/c++/11/bits/stl_construct.h:188:51: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
[4/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/LibiptDecoder.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/LibiptDecoder.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/LibiptDecoder.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/LibiptDecoder.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/LibiptDecoder.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp: In function ‘llvm::Error lldb_private::trace_intel_pt::DecodeSingleTraceForThread(lldb_private::trace_intel_pt::DecodedThread&, lldb_private::trace_intel_pt::TraceIntelPT&, llvm::ArrayRef<unsigned char>)’:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp:575:66: error: ‘None’ was not declared in this scope; did you mean ‘llvm::yaml::QuotingType::None’?
  575 |         i + 1 < blocks->size() ? blocks->at(i + 1).starting_ip : None,
      |                                                                  ^~~~
      |                                                                  llvm::yaml::QuotingType::None
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/Args.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/CompletionRequest.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/ArchSpec.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValue.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValueProperties.h:16,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Core/UserSettingsController.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:18,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp:8:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/YAMLTraits.h:130:26: note: ‘llvm::yaml::QuotingType::None’ declared here
  130 | enum class QuotingType { None, Single, Double };
      |                          ^~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp: In function ‘llvm::Error lldb_private::trace_intel_pt::DecodeSystemWideTraceForThread(lldb_private::trace_intel_pt::DecodedThread&, lldb_private::trace_intel_pt::TraceIntelPT&, const llvm::DenseMap<unsigned int, llvm::ArrayRef<unsigned char> >&, const std::vector<lldb_private::trace_intel_pt::IntelPTThreadContinousExecution>&)’:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp:643:17: error: ‘None’ was not declared in this scope; did you mean ‘llvm::yaml::QuotingType::None’?
  643 |               : None,
      |                 ^~~~
      |                 llvm::yaml::QuotingType::None
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/Args.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/CompletionRequest.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/ArchSpec.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValue.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValueProperties.h:16,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Core/UserSettingsController.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:18,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.cpp:8:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/YAMLTraits.h:130:26: note: ‘llvm::yaml::QuotingType::None’ declared here
  130 | enum class QuotingType { None, Single, Double };
      |                          ^~~~
[5/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTMultiCpuDecoder.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTMultiCpuDecoder.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTMultiCpuDecoder.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTMultiCpuDecoder.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTMultiCpuDecoder.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTMultiCpuDecoder.cpp
In file included from /usr/include/c++/11/optional:44,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/LibiptDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTMultiCpuDecoder.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTMultiCpuDecoder.cpp:9:
/usr/include/c++/11/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/alloc_traits.h:848:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:61:7:   required from ‘void __gnu_cxx::new_allocator<_Tp>::destroy(_Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread; _Tp = lldb_private::trace_intel_pt::DecodedThread]’
/usr/include/c++/11/bits/alloc_traits.h:535:15:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::destroy(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread; _Tp = lldb_private::trace_intel_pt::DecodedThread; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread>]’
/usr/include/c++/11/bits/shared_ptr_base.h:528:35:   required from ‘void std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_dispose() [with _Tp = lldb_private::trace_intel_pt::DecodedThread; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:526:7:   required from here
/usr/include/c++/11/bits/stl_construct.h:188:51: error: static assertion failed: value type is destructible
  188 |       static_assert(is_destructible<_Value_type>::value,
      |                                                   ^~~~~
/usr/include/c++/11/bits/stl_construct.h:188:51: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
[6/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTBundleLoader.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTBundleLoader.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTBundleLoader.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTBundleLoader.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/TraceIntelPTBundleLoader.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp: In member function ‘llvm::Expected<lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParsedProcess> lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::CreateEmptyProcess(lldb::pid_t, llvm::StringRef)’:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:112:3: error: ‘process_sp’ was not declared in this scope
  112 |   process_sp->SetID(static_cast<lldb::pid_t>(pid));
      |   ^~~~~~~~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp: In lambda function:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:347:57: error: ‘None’ was not declared in this scope; did you mean ‘llvm::yaml::QuotingType::None’?
  347 |     proc->second->threads.push_back({tid, /*ipt_trace=*/None});
      |                                                         ^~~~
      |                                                         llvm::yaml::QuotingType::None
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/Args.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/CompletionRequest.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Utility/ArchSpec.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValue.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Interpreter/OptionValueProperties.h:16,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Core/UserSettingsController.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:17,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/../common/ThreadPostMortemTrace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/YAMLTraits.h:130:26: note: ‘llvm::yaml::QuotingType::None’ declared here
  130 | enum class QuotingType { None, Single, Double };
      |                          ^~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:347:36: error: no matching function for call to ‘std::vector<lldb_private::trace_intel_pt::JSONThread>::push_back(<brace-enclosed initializer list>)’
  347 |     proc->second->threads.push_back({tid, /*ipt_trace=*/None});
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/vector:67,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Thread.h:15,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/../common/ThreadPostMortemTrace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:9:
/usr/include/c++/11/bits/stl_vector.h:1187:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = lldb_private::trace_intel_pt::JSONThread; _Alloc = std::allocator<lldb_private::trace_intel_pt::JSONThread>; std::vector<_Tp, _Alloc>::value_type = lldb_private::trace_intel_pt::JSONThread]’
 1187 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:1187:35: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type&’ {aka ‘const lldb_private::trace_intel_pt::JSONThread&’}
 1187 |       push_back(const value_type& __x)
      |                 ~~~~~~~~~~~~~~~~~~^~~
/usr/include/c++/11/bits/stl_vector.h:1203:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = lldb_private::trace_intel_pt::JSONThread; _Alloc = std::allocator<lldb_private::trace_intel_pt::JSONThread>; std::vector<_Tp, _Alloc>::value_type = lldb_private::trace_intel_pt::JSONThread]’
 1203 |       push_back(value_type&& __x)
      |       ^~~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:1203:30: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<lldb_private::trace_intel_pt::JSONThread>::value_type&&’ {aka ‘lldb_private::trace_intel_pt::JSONThread&&’}
 1203 |       push_back(value_type&& __x)
      |                 ~~~~~~~~~~~~~^~~
[7/14] Building CXX object tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o
FAILED: tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o 
/home/linuxbrew/.linuxbrew/opt/ccache/libexec/c++ -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/../clang/include -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/build/tools/lldb/source -I/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/libipt/build/libipt/include -isystem /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.12.1/include/libxml2 -isystem /home/linuxbrew/.linuxbrew/Cellar/libedit/20230828-3.1/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o -MF tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o.d -o tools/lldb/source/Plugins/Trace/intel-pt/CMakeFiles/lldbPluginTraceIntelPT.dir/CommandObjectTraceStartIntelPT.cpp.o -c /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp:161:6: error: no declaration matches ‘bool lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::DoExecute(lldb_private::Args&, lldb_private::CommandReturnObject&)’
  161 | bool CommandObjectProcessTraceStartIntelPT::DoExecute(
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.h:108:8: note: candidate is: ‘virtual void lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::DoExecute(lldb_private::Args&, lldb_private::CommandReturnObject&)’
  108 |   void DoExecute(Args &command, CommandReturnObject &result) override;
      |        ^~~~~~~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/CommandObjectTraceStartIntelPT.h:65:7: note: ‘class lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT’ defined here
   65 | class CommandObjectProcessTraceStartIntelPT : public CommandObjectParsed {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

System: x86-64 Ubuntu/Linux 22.04
Compiler: GCC 11.4.0

### PR DESCRIPTION
**Pull request by nmosier**
Fix #77251.

### CODE REVIEW

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.h [hunk 1]
```diff
@@ -276,6 +276,10 @@ class DecodedThread : public std::enable_shared_from_this<DecodedThread> {
 
     /// The string message of this item if it's an error
     std::string error;
+
+    TraceItemStorage() {}
+    ~TraceItemStorage() {}
```
Comment (JDevlieghere) [inline lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:281]: Can this be `= default`?

File: lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp [hunk 2]
```diff
@@ -103,12 +103,10 @@ TraceIntelPTBundleLoader::CreateEmptyProcess(lldb::pid_t pid,
...
-  // This should instead try to directly create an instance of ProcessTrace.
-  // ProcessSP process_sp = target_sp->CreateProcess(
-  //    /*listener*/ nullptr, "trace",
-  //    /*crash_file*/ nullptr,
-  //    /*can_connect*/ false);
-
+  ProcessSP process_sp = target_sp->CreateProcess(
+      /*listener*/ nullptr, "trace",
+      /*crash_file*/ nullptr,
+      /*can_connect*/ false);
```
Comment (JDevlieghere) [inline lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:109]: Should the original comment be kept as a FIXME?

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp [hunk 3]
```diff
@@ -85,6 +85,11 @@ double DecodedThread::NanosecondsRange::GetInterpolatedTime(
   return interpolate(next_range->nanos);
 }
 
+DecodedThread::TraceItemStorage::TraceItemStorage(
+    const TraceItemStorage &other) {
+  std::memcpy(this, &other, sizeof *this);
```
Comment (JDevlieghere) [inline lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:90]: Does the `DecodedThread` know which member of the `TraceItemStorage` is being used? If so, you can pass an additional argument and copy the right member rather than just copying the bytes.

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.h (hunk 1 above)
Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:281]: `TraceItemStorage()` can't be defaulted because the union member `std::string error` has a non-trivial default constructor (quoted from [here](https://en.cppreference.com/w/cpp/language/union)):
> If a union contains a non-static data member with a non-trivial default constructor, the default constructor of the union is deleted by default unless a variant member of the union has a default member initializer.

`~TraceItemStorage()` can't be defaulted because the union member `std::string error` has a non-trivial destructor (quoted from [here](https://en.cppreference.com/w/cpp/language/union)):
> If a union contains a non-static data member with a non-trivial special member function (copy/move constructor, copy/move assignment, or destructor), that function is deleted by default in the union and needs to be defined explicitly by the programmer.


Anyways, if I try to default them, I get these compile errors:
```
In file included from /usr/include/x86_64-linux-gnu/c++/11/bits/c++allocator.h:33,
                 from /usr/include/c++/11/bits/allocator.h:46,
                 from /usr/include/c++/11/unordered_map:40,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’:
/usr/include/c++/11/bits/alloc_traits.h:516:17:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:115:30:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:110:27:   required from here
/usr/include/c++/11/ext/new_allocator.h:162:11: error: use of deleted function ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::TraceItemStorage()’
  162 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:280:5: note: ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::TraceItemStorage()’ is implicitly deleted because the default definition would be ill-formed:
  280 |     TraceItemStorage() = default;
      |     ^~~~~~~~~~~~~~~~
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:278:17: error: union member ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::error’ with non-trivial ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  278 |     std::string error;
      |                 ^~~~~
```
and
```
In file included from /usr/include/c++/11/optional:44,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:12,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/alloc_traits.h:848:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:253:62:   required from here
/usr/include/c++/11/bits/stl_construct.h:188:51: error: static assertion failed: value type is destructible
  188 |       static_assert(is_destructible<_Value_type>::value,
      |                                                   ^~~~~
/usr/include/c++/11/bits/stl_construct.h:188:51: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
In file included from /usr/include/x86_64-linux-gnu/c++/11/bits/c++allocator.h:33,
                 from /usr/include/c++/11/bits/allocator.h:46,
                 from /usr/include/c++/11/unordered_map:40,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::destroy(_Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’:
/usr/include/c++/11/bits/alloc_traits.h:535:15:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::destroy(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*) [with _Up = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:488:28:   required from ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::iterator = std::vector<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>::iterator]’
/usr/include/c++/11/bits/vector.tcc:121:21:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:110:27:   required from here
/usr/include/c++/11/ext/new_allocator.h:168:20: error: use of deleted function ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::~TraceItemStorage()’
  168 |         { __p->~_Up(); }
      |           ~~~~~~~~~^~
In file included from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:281:5: note: ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::~TraceItemStorage()’ is implicitly deleted because the default definition would be ill-formed:
  281 |     ~TraceItemStorage() = default;
      |     ^
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:278:17: error: union member ‘lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage::error’ with non-trivial ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  278 |     std::string error;
      |                 ^~~~~
In file included from /usr/include/c++/11/vector:66,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/ADT/DenseMap.h:25,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/llvm/include/llvm/Support/JSON.h:49,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/include/lldb/Target/Trace.h:15,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:13,
                 from /afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:9:
/usr/include/c++/11/bits/stl_uninitialized.h: In instantiation of ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*>; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*]’:
/usr/include/c++/11/bits/stl_uninitialized.h:333:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*>; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage]’
/usr/include/c++/11/bits/stl_uninitialized.h:355:2:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _ForwardIterator = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage*; _Allocator = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>]’
/usr/include/c++/11/bits/vector.tcc:474:3:   required from ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::iterator = std::vector<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>::iterator]’
/usr/include/c++/11/bits/vector.tcc:121:21:   required from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {}; _Tp = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage; _Alloc = std::allocator<lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage>; std::vector<_Tp, _Alloc>::reference = lldb_private::trace_intel_pt::DecodedThread::TraceItemStorage&]’
/afs/cs.stanford.edu/u/nmosier/llvm/bugfix-lldb-intelpt/lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:110:27:   required from here
/usr/include/c++/11/bits/stl_uninitialized.h:138:72: error: static assertion failed: result type must be constructible from value type of input range
  138 |       static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,
      |                                                                        ^~~~~
/usr/include/c++/11/bits/stl_uninitialized.h:138:72: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
```

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp (hunk 3 above)
Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:90]: `DecodedThread` does know which member is being used (it uses `enum TraceItemKind` to tag the union); however, it stores the tag separately in `DecodedThread::m_item_kinds` for space/alignment reasons.
I added this copy constructor for use by `std::vector<TraceItemStorage> DecodedThread::m_trace_data`; without it, it raises a compile error because it doesn't know how to copy/move `TraceItemStorage` elements when resizing the vector. This means that we can't add a second TraceItemKind argument to the copy constructor, because std::vector<TraceItemStorage> won't know how to use that.

File: lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp (hunk 2 above)
Comment (walter-erquinigo) [reply lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp]: Actually, if you could just do

```
ProcessTrace::CreateInstance(target_sp, /*listener*/ nullptr, /*crash_file*/ nullptr, /*can_connect*/ false);
```

Then we could consider this part of the code as fixed. You also need to make that `ProcessTrace::CreateInstance` function `public` instead of `private`.

Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp]: I double-checked, and looks like commit 555a71be457fo3 commented out these four lines. Here's the commit message:
```
commit 555a71be457f351411b89c6a6a66aeecf7ca5291
Author: Walter Erquinigo <a20012251@gmail.com>
Date:   Mon Nov 6 19:45:52 2023 -0500

    [LLDB] Don't forcefully initialize the process trace plugin (#71455)
    
    This was causing some process to wrongfully be handled by ProcessTrace.
    
    The only place this was being used is in the intel pt plugin, but it
    doesn't even build anymore, so I'm sure no one is using it.
```
I think the commit author meant to comment out the following line, `process_sp->SetID(static_cast<lldb::pid_t>(pid));`; however, they didn't catch the compile error because apparently the Intel PT plugin wasn't compiling back then anyway.

I updated my patch to keep those four lines plus the following two commented out. I verified that LLDB's Intel PT plugin still works just fine.

File: lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp [hunk 4]
```diff
@@ -108,8 +108,8 @@ TraceIntelPTBundleLoader::CreateEmptyProcess(lldb::pid_t pid,
   //    /*listener*/ nullptr, "trace",
   //    /*crash_file*/ nullptr,
   //    /*can_connect*/ false);
-
-  process_sp->SetID(static_cast<lldb::pid_t>(pid));
+  //
+  // process_sp->SetID(static_cast<lldb::pid_t>(pid));
```
Comment (walter-erquinigo) [inline lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp:112]: do you need to do this? Otherwise all processes loaded from JSON will appear with an invalid PID.

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp (hunk 3 above)
Comment (walter-erquinigo) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:90]: I think that the copies might cause unnecessary slowdowns because traces can contain tens of millions of items. What about using a deque instead of a vector? Then you don't need resizes anymore.

Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp]: Thanks for the  suggestion, I changed `DecodedThread::m_item_{kinds,data}` to `std::deque`s and removed the `TraceItemStorage`'s copy constructor.

File: lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp (hunk 2 above)
Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp]: @walter-erquinigo Thanks for the suggestion! I implemented that change.

File: lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp (hunk 4 above)
Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/TraceIntelPTBundleLoader.cpp]: I reverted this, given your suggestion in the other thread.

**Review by walter-erquinigo — COMMENTED** [review]
These changes lgtm at this point. Btw, how are you testing them?

**Comment by nmosier** [comment]
> Btw, how are you testing them?

Not very rigorously, ha. Just something like
```
b main
r
process trace start
c
thread trace dump instructions
```
I was using a version with my original fixes to debug other code that was crashing, and it worked fine for that.

Are there existing tests I should be using?

**Comment by walter-erquinigo** [comment]
`third-party/llvm-project/lldb/test/API/commands/trace` has a set of pythong tests.

You should be able to run them with

```
build lldb-dotest
lldb-dotest -p TestTrace
```

Also, the CMake variable `LLDB_INCLUDE_TESTS` must be enabled (e.g. `ON`) in order to build `lldb-dotest`

**Comment by nmosier** [comment]
At least one test fails: `./bin/lldb -o 'trace load -v /llvm/lldb/test/API/commands/trace/intelpt-trace/trace_2threads.json'` crashes with an assertion failure on TraceIntelPTBundleLoader.cpp:127 (`*process_sp` is a null pointer dereference).

Do you know why `process_sp` would be null in this case? I added some extra assertions and it looks like `target_sp->m_process_sp` is null after the call to `ProcessTrace::CreateInstance` on line 111.

**Comment by walter-erquinigo** [comment]
> At least one test fails: `./bin/lldb -o 'trace load -v /llvm/lldb/test/API/commands/trace/intelpt-trace/trace_2threads.json'` crashes with an assertion failure on TraceIntelPTBundleLoader.cpp:127 (`*process_sp` is a null pointer dereference).
> 
> Do you know why `process_sp` would be null in this case? I added some extra assertions and it looks like `target_sp->m_process_sp` is null after the call to `ProcessTrace::CreateInstance` on line 111.

It seems that the issue is that we still need to make `Target::m_process_sp` point to the newly created process...

So, let's give something else a try:

Return that code to its original form

```
ProcessSP process_sp = target_sp->CreateProcess(
    /*listener*/ nullptr, "trace",
    /*crash_file*/ nullptr,
    /*can_connect*/ false);
```

If that passes the test, then there's nothing else to do and we are good to go.
If that doesn't work, then we need to additional add the line `LLDB_PLUGIN_DEFINE(ProcessTrace)` before any function declaration in the ProcessTrace.cpp file. That `LLDB_PLUGIN_DEFINE` define will register the ProcessTrace process plugin with that "trace", which will be searchable by `target_sp->CreateProcess`, who is looking for a trace process called "trace".

**Comment by nmosier** [comment]
Thanks for the suggestions. Unfortunately, it's still crashing, now on the line
```c
process_sp->SetID(static_cast<lldb::pid_t>(pid));
```
because the prior call to `CreateProcess` on line 107 returned null.

**Comment by walter-erquinigo** [comment]
> because the prior call to `CreateProcess` on line 107 returned null.

If that call returned null, that means that CreateProcess wasn't able to find the "trace" process plugin. Another thing to add, which should definitely work, is to invoke

```
ProcessTrace::Initialize();
```
right before `CreateProcess`. That should definitely work

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp [hunk 5]
```diff
@@ -107,7 +107,15 @@ DecodedThread::CreateNewTraceItem(lldb::TraceItemKind kind) {
...
   if (m_last_nanoseconds)
     (*m_last_nanoseconds)->second.items_count++;
-  return m_item_data.back();
+
+  TraceItemStorage &data = m_item_data.back();
+
+  // If creating an error item, then properly initialize TraceItemStorage's
+  // non-trivially-constructible union member `error`.
+  if (kind == lldb::eTraceItemKindError)
+    new (&data.error) std::string();
```
Comment (walter-erquinigo) [inline lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:116]: could you just do `data.error = {}`?

**Comment by nmosier** [comment]
Thanks! That test passes now. Another test was crashing as well, but I fixed that (it was due to `TraceItemStorage.error` not being initialized properly in `DecodedThread::CreateNewTraceItem` when creating an error item.

49 out of 56 tests now pass, with the remaining tests being soft failures (e.g., unexpected output but no crashes, generally due to small differences like 
```
"memoryUsage": {         
  "totalInBytes": "924", 
  "avgPerItemInBytes": 33
},                       
```
vs. expected
```
"memoryUsage": {        
  "totalInBytes": "252",
  "avgPerItemInBytes": 9
}, 
```

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.h [hunk 6]
```diff
@@ -276,6 +276,9 @@ class DecodedThread : public std::enable_shared_from_this<DecodedThread> {
...
```
Comment (walter-erquinigo) [inline lldb/source/Plugins/Trace/intel-pt/DecodedThread.h:281]: do you still need these?

**Comment by walter-erquinigo** [comment]
Nice! Could you just delete all the tests that check for number of bytes? I think it's better to delete them because they might change in different systems.

File: lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp (hunk 5 above)
Comment (nmosier) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:116]: I don't think so (I tried it, and the crash came back). The problem is that before line 116, `data.error` is uninitialized. Thus `data.error = {}` implicitly invokes the destructor of `data.error` on uninitialized memory before constructing a new std::string, causing a crash.

Comment (walter-erquinigo) [reply lldb/source/Plugins/Trace/intel-pt/DecodedThread.cpp:116]: I see. Then I'm fine with `new (&data.error) std::string();`

But, if you want to make a more complex change that will also be very clean, you could use `std::variant` instead of `union` for `TraceItemStorage`. `std::variant` handles constructors and destructors nicely. Then we could also get rid of `m_item_kinds`. 

I'm fine with either option.

**Comment by nmosier** [comment]
I went ahead and turned `TraceItemStorage` into a variant. I also deleted the memory usage / bytes from the tests. Also, I noticed some error messages were different for some tests — I'm guessing they may have changed in newer versions of libipt.

Right now, only 1 test fails:
```
======================================================================                                                                                                                
FAIL: testStartPerCpuSession (TestTraceStartStopMultipleThreads.TestTraceStartStopMultipleThreads)                                                                                    
----------------------------------------------------------------------                                                                                                                
Traceback (most recent call last):                                                                                                                                                    
  File "/llvm/lldb/packages/Python/lldbsuite/test/decorators.py", line 162, in wrapper                                                                                                
    return func(*args, **kwargs)                                                                                                                                                      
  File "/llvm/lldb/packages/Python/lldbsuite/test/tools/intelpt/intelpt_testcase.py", line 14, in wrapper                                                                             
    func(*args, **kwargs)                                                                                                                                                             
  File "/llvm/lldb/test/API/commands/trace/multiple-threads/TestTraceStartStopMultipleThreads.py", line 260, in testStartPerCpuSession                                                
    self.expect("thread trace dump instructions")                                                                                                                                     
  File "/llvm/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2353, in expect                                                                                                  
    self.runCmd(                                                                                                                                                                      
  File "/llvm/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2031, in runCmd                                                                                                  
    self.assertTrue(self.res.Succeeded(), msg if (msg) else CMD_MSG(cmd))                                                                                                             
AssertionError: False is not True : Command 'thread trace dump instructions                                                                                                           
Error output:                                                                                                                                                                         
error: Malformed perf context switch trace for cpu 14 at offset 64. A context switch record doesn't happen after the previous record. Previous TSC= 2215501248, current TSC = 22155012
48.                                                                                                                                                                                   
' did not return successfully                                                                                                                                                         
Config=x86_64-/llvm-build/bin/clang                                                                                                                                                   
```

**Comment by walter-erquinigo** [comment]
> Also, I noticed some error messages were different for some tests — I'm guessing they may have changed in newer versions of libipt.

That makes sense. In this case I'd just drop text comparisons for those tests. Just knowing that an error was found is good enough.

> FAIL: testStartPerCpuSession (TestTraceStartStopMultipleThreads.TestTraceStartStopMultipleThreads)   

Leave that test failing. I'm pretty that your changes haven't affected this test, so it's been broken for a while. Just ignore it for now :) We can fix it later if that's something that prevents you from doing your actual work.

**Comment by walter-erquinigo** [comment]
Just let me know when your changes are ready and only that test fails.

**Review by walter-erquinigo — APPROVED** [review]

**Comment by nmosier** [comment]
@walter-erquinigo Could you merge this PR for me? I don't have commit access. Thanks!

**Review by JDevlieghere — APPROVED** [review]
