### PR TITLE
[LV] Use frozen start value for FindLastIV if needed.

### LINKED ISSUE #126836: [LV] wrf in SPEC2017 emits "Verification Error" on Grace when using llvmorg-20.1.0-rc1
* CPU2017.*.log
```
runcpu v6612 started at 2025-02-12 10:12:40 on "***"
runcpu is: /path/to/cpu2017-1.1.0/bin/harness/runcpu
runcpu: runcpu -I --action run -T base -c /path/to/config.cfg -i ref -n 1 --threads=1 --output_root=/path/to/output -o asc 521
toolset: linux-aarch64
suite: CPU2017 1.1.9
 :
Benchmarks selected: 521.wrf_r
Compiling Binaries
------------------------------------------------------------------------
 :
O: OPTIMIZE="-O2 -mcpu=neoverse-v2"
 :
flang version 20.1.0-rc1 (https://github.com/llvm/llvm-project.git af7f483a9d801252247b6c72e3763c1f55c5a506)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/bin
clang version 20.1.0-rc1 (https://github.com/llvm/llvm-project.git af7f483a9d801252247b6c72e3763c1f55c5a506)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/bin
 :
Setting Up Run Directories
  Setting up 521.wrf_r refrate (ref) base mytest-64 (1 copy): run_base_refrate_mytest-64.0000
-----------------------------------
Running Benchmarks
-----------------------------------
 :
Error with '/path/to/cpu2017-1.1.0/bin/specinvoke -d /path/to/output/benchspec/CPU/521.wrf_r/run/run_base_refrate_mytest-64.0000 -f compare.cmd -E -e compare.err -o compare.stdout'; no non-empty output files exist
  Command returned exit code 1
*** Miscompare of diffwrf_output_01.txt; for details see
    /path/to/output/benchspec/CPU/521.wrf_r/run/run_base_refrate_mytest-64.0000/diffwrf_output_01.txt.mis
0015:           W    PASSED
                W    121182    1   0.7117559909E-01   0.6272285812E-01   0   0.3873E-01   0.1085E+01
                  ^
0105:       RAINC    PASSED
            RAINC      1132    2   0.5266002302E+01   0.7384289461E+01   0   0.2787E+01   0.4166E+00
                  ^
0107:      RAINNC    PASSED
           RAINNC      4114    1   0.4236885721E+01   0.3284801810E+01   0   0.1728E+01   0.9835E+00
                  ^
0244:       RAINC    PASSED
            RAINC      1359    2   0.9852032964E+01   0.1287943984E+02   0   0.4379E+01   0.4672E+00
                  ^
0246:      RAINNC    PASSED
           RAINNC      4118    1   0.1017513524E+02   0.8983057159E+01   0   0.2827E+01   0.6375E+00
                  ^
0383:       RAINC    PASSED
            RAINC      1510    2   0.1283821850E+02   0.1616687672E+02   0   0.4926E+01   0.4845E+00
                  ^
Benchmark Times:
  Run Start:    2025-02-12 10:12:46 (1739322766)
  Rate Start:   2025-02-12 10:12:46 (1739322766.13335)
  Rate End:     2025-02-12 10:15:34 (1739322934.19951)
  Run Stop:     2025-02-12 10:15:34 (1739322934)
  Run Elapsed:  00:02:48 (168)
  Run Reported: 00:02:48 (168 66154003 168.066154)
 Error 521.wrf_r base refrate ratio=13.33, runtime=168.066154, copies=1, threads=1, power=0.00W, temp=0.00 degC, humidity=0.00%, errorcode=VE
Error: 1x521.wrf_r
 :
```
The verification is passed when the option `-mcpu=neoverse-v2` is removed.
(The option `-mcpu=neoverse-v2+nosve` doesn't work for this.)

### PR DESCRIPTION
**Pull request by fhahn**
FindLastIV introduces multiple uses of the start value, where in the
original source there was only a single use.

Each use of undef may produce a different result, so introducing
multiple uses can produce incorrect results when the input is
undef/poison.

If the start value may be undef or poison, freeze it and use the frozen
value, which will be the same at all uses.

Alive2 showing the issue: https://alive2.llvm.org/ce/z/mB4Jtb

Depends on https://github.com/llvm/llvm-project/pull/132689
(included in PR) and https://github.com/llvm/llvm-project/pull/132690
(included in PR)

Fixes https://github.com/llvm/llvm-project/issues/126836

### CODE REVIEW

**Comment by lukel97** [comment]
Makes sense to me. Although I think AnyOf reductions might have the same problem too?


With `opt -p loop-vectorize -force-vector-width=4`:

```llvm
define i32 @select_i32_from_icmp(ptr %v, i32 %a, i32 %b, i64 %n) {
entry:
  br label %loop

loop:                                      ; preds = %entry, %loop
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %rdx = phi i32 [ %a, %entry ], [ %sel, %loop ]
  %gep.v.iv = getelementptr inbounds i32, ptr %v, i64 %iv
  %load.v.iv = load i32, ptr %gep.v.iv, align 4
  %cmp.load.iv.3 = icmp eq i32 %load.v.iv, 3
  %sel = select i1 %cmp.load.iv.3, i32 %rdx, i32 %b
  %iv.next = add nuw nsw i64 %iv, 1
  %exit.cond = icmp eq i64 %iv.next, %n
  br i1 %exit.cond, label %exit, label %loop

exit:                                     ; preds = %loop
  ret i32 %sel
}
```

Becomes

```llvm
define i32 @select_i32_from_icmp(ptr %v, i32 %a, i32 %b, i64 %n) {
entry:
  %min.iters.check = icmp ult i64 %n, 4
  br i1 %min.iters.check, label %scalar.ph, label %vector.ph

vector.ph:                                        ; preds = %entry
  %n.mod.vf = urem i64 %n, 4
  %n.vec = sub i64 %n, %n.mod.vf
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <4 x i1> [ zeroinitializer, %vector.ph ], [ %5, %vector.body ]
  %0 = add i64 %index, 0
  %1 = getelementptr inbounds i32, ptr %v, i64 %0
  %2 = getelementptr inbounds i32, ptr %1, i32 0
  %wide.load = load <4 x i32>, ptr %2, align 4
  %3 = icmp eq <4 x i32> %wide.load, splat (i32 3)
  %4 = xor <4 x i1> %3, splat (i1 true)
  %5 = or <4 x i1> %vec.phi, %4
  %index.next = add nuw i64 %index, 4
  %6 = icmp eq i64 %index.next, %n.vec
  br i1 %6, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %7 = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> %5)
  %8 = freeze i1 %7
  %rdx.select = select i1 %8, i32 %b, i32 %a
  %cmp.n = icmp eq i64 %n, %n.vec
  br i1 %cmp.n, label %exit, label %scalar.ph

scalar.ph:                                        ; preds = %entry, %middle.block
  %bc.resume.val = phi i64 [ %n.vec, %middle.block ], [ 0, %entry ]
  %bc.merge.rdx = phi i32 [ %rdx.select, %middle.block ], [ %a, %entry ]
  br label %loop

loop:                                             ; preds = %scalar.ph, %loop
  %iv = phi i64 [ %bc.resume.val, %scalar.ph ], [ %iv.next, %loop ]
  %rdx = phi i32 [ %bc.merge.rdx, %scalar.ph ], [ %sel, %loop ]
  %gep.v.iv = getelementptr inbounds i32, ptr %v, i64 %iv
  %load.v.iv = load i32, ptr %gep.v.iv, align 4
  %cmp.load.iv.3 = icmp eq i32 %load.v.iv, 3
  %sel = select i1 %cmp.load.iv.3, i32 %rdx, i32 %b
  %iv.next = add nuw nsw i64 %iv, 1
  %exit.cond = icmp eq i64 %iv.next, %n
  br i1 %exit.cond, label %exit, label %loop, !llvm.loop !3

exit:                                             ; preds = %middle.block, %loop
  %sel.lcssa = phi i32 [ %sel, %loop ], [ %rdx.select, %middle.block ]
  ret i32 %sel.lcssa
}
```

We now have two uses of `%a` in `%rdx.select` and `%bc.merge.rdx`.

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp [hunk 1]
```diff
@@ -474,6 +475,12 @@ Value *VPInstruction::generate(VPTransformState &State) {
     Value *Idx = State.get(getOperand(1), /*IsScalar=*/true);
     return Builder.CreateExtractElement(Vec, Idx, Name);
   }
+  case Instruction::Freeze: {
+    if (State.hasVectorValue(this))
+      return State.get(this);
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:480]: Will we still generate a freeze instruction if we have a vector value?

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp [hunk 2]
```diff
@@ -939,6 +946,7 @@ bool VPInstruction::onlyFirstLaneUsed(const VPValue *Op) const {
   case Instruction::ICmp:
   case Instruction::Select:
   case Instruction::Or:
+  case Instruction::Freeze:
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:949]: We should probably also add this opcode to `VPInstruction::opcodeMayReadOrWriteFromMemory` and return `false`.

**Review by david-arm — COMMENTED** [review]
Thanks for this fix @fhahn!

File: llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp [hunk 3]
```diff
@@ -1571,7 +1602,6 @@ void VPWidenRecipe::execute(VPTransformState &State) {
   }
   case Instruction::Freeze: {
     Value *Op = State.get(getOperand(0));
-
```
Comment (Mel-Chen) [inline llvm/lib/Transforms/Vectorize/VPlanRecipes.cpp:1574]: Redundant blank

**Review by Mel-Chen — COMMENTED** [review]
Thanks for your help!

File: llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll [hunk 4]
```diff
@@ -6,6 +6,7 @@ define i64 @select_icmp_nuw_nsw(ptr %a, ptr %b, i64 %ii, i64 %n) {
 ; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i64 [[II:%.*]], i64 [[N:%.*]]) {
 ; CHECK-NEXT:  [[ENTRY:.*]]:
 ; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
+; CHECK-NEXT:    [[FR:%.*]] = freeze i64 [[II]]
```
Comment (Mel-Chen) [inline llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll:9]: Could we insert the freeze in vector preheader, or the scalar loop also need the frozen start value?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 5]
```diff
@@ -9866,14 +9869,31 @@ void LoopVectorizationPlanner::adjustRecipesForReductions(
...
+        Start = Builder.createNaryOp(Instruction::Freeze, {Start}, {}, "fr");
+      }
+      Builder.setInsertPoint(MiddleVPBB, IP);
       FinalReductionResult =
           Builder.createNaryOp(VPInstruction::ComputeFindLastIVResult,
                                {PhiR, Start, NewExitingVPV}, ExitDL);
+      // Update all users outside the vector region.
+      for (VPUser *U : to_vector(OrigExitingVPV->users())) {
+        auto *R = cast<VPRecipeBase>(U);
+        if (R->getParent() && R->getParent()->getParent())
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Updated to check that the parent's region is the vector loop region, thanks

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 6]
```diff
@@ -10365,24 +10385,7 @@ preparePlanForEpilogueVectorLoop(VPlan &Plan, Loop *L,
   VPBasicBlock *Header = VectorLoop->getEntryBasicBlock();
   Header->setName("vec.epilog.vector.body");
 
-  // Re-use the trip count and steps expanded for the main loop, as
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:10393]: I left it included in the patch for now, could also split it off.

File: llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll (hunk 4 above)
Comment (fhahn) [reply llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll]: I checked a bit more and I think the only issue is with epilogue vectorization; Here's a proof where we go via the main vector loop to the scalar remainder loop https://alive2.llvm.org/ce/z/yFSBrq  and here where we go from the vector loop to the exit block https://alive2.llvm.org/ce/z/D6Ppzr.

When vectorizing the epilogue, freeze is needed for the start value used in the selects and the resume phi from the main vector loop:

* Both main and epilogue vector loops execute, go to exit block: https://alive2.llvm.org/ce/z/_TSvRr
* Both main and epilogue vector loops execute, go to scalar loop: https://alive2.llvm.org/ce/z/CsPj5v
* Only epilogue vector loop executes, go to exit block: https://alive2.llvm.org/ce/z/5XqkNV
* Only epilogue vector loop executes, go to scalar loop: https://alive2.llvm.org/ce/z/JUpqRN

The latter 2 show  requiring freezing the resume phi. That means we cannot freeze in the preheader. We could move the freeze to the main iteration count check, but that would be a bit fragile to find and other transforms can sink the freeze if needed.

**Review by fhahn — COMMENTED** [review]
Updated to current main, so now only the PR changes should be included.

Updated the PR to only freeze when vectorizing the epilogue, as this is the only case where it should be needed

**Review by david-arm — COMMENTED** [review]
Thanks for the update - looks almost ready to go!

**Comment by pawosm-arm** [comment]
This is a vital patch. I'm sorry for this blatant question, but, is there any chance of landing it this week?

File: llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll (hunk 4 above)
Comment (Mel-Chen) [reply llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll]: I see. So it's because
```[[TMP11:%.*]] = icmp eq i8 [[BC_MERGE_RDX]], [[START]]```
passes the undef start value?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 7]
```diff
@@ -9892,14 +9895,22 @@ void LoopVectorizationPlanner::adjustRecipesForReductions(
     // also modeled in VPlan.
     VPInstruction *FinalReductionResult;
     VPBuilder::InsertPointGuard Guard(Builder);
-    Builder.setInsertPoint(MiddleVPBB, IP);
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: Restored, this was left over after moving the code

File: llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll (hunk 4 above)
Comment (fhahn) [reply llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll]: Yes, if we reach `vec.epilog.ph` without going through the main vector loop, `%bc.merge.rdx` will be the start value. If it is not frozen we have 2 uses of undef (both operands of the compare), and each use may have a different concrete value

**Review by lukel97 — APPROVED** [review]
LGTM

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 8]
```diff
@@ -10497,6 +10517,31 @@ preparePlanForEpilogueVectorLoop(VPlan &Plan, Loop *L,
...
+
+  // Re-use the trip count and steps expanded for the main loop, as
+  // skeleton creation needs it as a value that dominates both the scalar
+  // and vector epilogue loops
+  // TODO: This is a workaround needed for epilogue vectorization and it
+  // should be removed once induction resume value creation is done
+  // directly in VPlan.
+  for (auto &R : make_early_inc_range(*Plan.getEntry())) {
+    auto *VPI = dyn_cast<VPInstruction>(&R);
+    if (VPI) {
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:10529]: What guarantee is there that VPI corresponds to the frozen start value? Do we need to check for VPInstructions with opcode Instruction::Freeze? I assume this is supposed to match up with the VPInstructions added by `AddFreezeForFindLastIVReductions` above?

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (david-arm) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:10392]: That's fine. 👍

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 9]
```diff
@@ -10377,6 +10380,36 @@ static void preparePlanForMainVectorLoop(VPlan &MainPlan, VPlan &EpiPlan) {
       VPInstruction::ResumePhi,
       {VectorTC, MainPlan.getCanonicalIV()->getStartValue()}, {},
       "vec.epilog.resume.val");
+
+  // When vectorizing the epilogue, FindLastIV reductions can introduce multiple
+  // uses of undef/poison. If the reduction start value is not guaranteed to be
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp]: I update the comment to say `If the reduction start value may be undef or poison....`

File: llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll (hunk 4 above)
Comment (Mel-Chen) [reply llvm/test/Transforms/LoopVectorize/iv-select-cmp-no-wrap.ll]: Although the incoming value of FindLastIV PHI in epilogue vectorization can be directly broadcasted with the sentinel value to avoid generating this icmp, I'm not sure if AnyOf has a similar approach to bypass the icmp that propagates undef/poison. Therefore, I think continuing with the approach of freezing the start value is reasonable, as it allows both FindLastIV and AnyOf to share the same approach. :)

**Review by Mel-Chen — APPROVED** [review]
LGTM after all current comments are fixed.
BTW, I can help update the llvm-testsuite to cover this case if there isn't already a unit test for it.

**Comment by vzakhari** [comment]
Sorry for the ignorant question in advance - I am not familiar with the mechanics of vectorization.

How does this work with FP values? If the undef value happens to be NaN, then do we care that the comparison will return false (regardless of whether the initial value was updated or not by the vector loop)?

File: llvm/lib/Transforms/Vectorize/VPlanValue.h [hunk 10]
```diff
@@ -246,6 +246,9 @@ class VPUser {
     New->addUser(*this);
   }
 
+  /// Replaces all uses of \p From in the VPUser with \p To.
+  void replaceUsesOfWith(VPValue *From, VPValue *To);
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlanValue.h]: Yep, removed again

File: llvm/lib/Transforms/Vectorize/VPlan.cpp [hunk 11]
```diff
@@ -1403,6 +1403,13 @@ void VPValue::replaceUsesWithIf(
   }
 }
 
+void VPUser::replaceUsesOfWith(VPValue *From, VPValue *To) {
```
[the remark this answers is not in the document]
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/VPlan.cpp]: Yep, removed again

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp [hunk 12]
```diff
@@ -10501,6 +10521,31 @@ preparePlanForEpilogueVectorLoop(VPlan &Plan, Loop *L,
...
+  // Re-use the trip count and steps expanded for the main loop, as
+  // skeleton creation needs it as a value that dominates both the scalar
+  // and vector epilogue loops
+  // TODO: This is a workaround needed for epilogue vectorization and it
+  // should be removed once induction resume value creation is done
+  // directly in VPlan.
+  for (auto &R : make_early_inc_range(*Plan.getEntry())) {
+    auto *VPI = dyn_cast<VPInstruction>(&R);
+    if (VPI && VPI->getOpcode() == Instruction::Freeze) {
+      VPI->replaceAllUsesWith(Plan.getOrAddLiveIn(
```
Comment (david-arm) [inline llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:10534]: I think I understand what you're doing here, but it looks a bit odd at first glance. You're essentially replacing one freeze in the epilogue entry block with another from the MainLoopIterationCountCheck block, right? Perhaps worth a comment explaining what's happening?

**Review by david-arm — APPROVED** [review]
LGTM! Thanks for fixing this @fhahn.

File: llvm/lib/Transforms/Vectorize/LoopVectorize.cpp (hunk 12 above)
Comment (fhahn) [reply llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:10534]: Done, I also moved the comment about re-using the trip count inside the loop, thanks

**Comment by Mel-Chen** [comment]
> Sorry for the ignorant question in advance - I am not familiar with the mechanics of vectorization.
> 
> How does this work with FP values? If the undef value happens to be NaN, then do we care that the comparison will return false (regardless of whether the initial value was updated or not by the vector loop)?

@vzakhari Both AnyOf and FindLastIV do not support floating-point types so far.

**Comment by yus3710-fj** [comment]
Thank you for the fix!

I'd like to backport this fix to the release branch, but I'm not sure how to do it because it seems to depend on some other fixes. I was hoping that someone familiar with this fix could backport it.

**Comment by pawosm-arm** [comment]
Hi @fhahn, I need to kindly ask you a question. A fix for the issue #126836 has been aimed for LLVM20. Do you have any plans to implement it for the LLVM20 release branch too? It seems the PRs that fix this issue depend too much on the current state of the main branch to make them cherry-pick as-is.
